### ISSUE TITLE
[MUXC, WUXC] Memory leak in NavigationView

### ISSUE THREAD

**Issue by eugenegff** [microsoft/microsoft-ui-xaml#1000]
**Describe the bug**

Memory leak in NavigationView, both WUXC and MUXC.
Leaked NavigationView itself, all children, and navView.DataContext even if was inherited from parent control rather than being directly set as a property of navView.

The reason is four Bindings created in code of NavigationView that creates circular reference from part of NavigationView control template to NavigationView itself. Usually bindings from template to control are created in XAML as TemplateBinding, and do not cause strong reference to control, current code of NavigationView was not so careful.

Note, that issue is present in both WUXC and MUXC versions of NavigationView control.

**Steps to reproduce the bug**

[NavViewLeakTest1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3363241/NavViewLeakTest1.zip)
1. Unzip, build and run attached NavViewLeakTest project
2. Click on 'Navigate Forward from MainPage to TestPage' button.
Debug output will contain such strings:
NavViewLeakTest::LifeTimeProbe_DataContext::LifeTimeProbe_DataContext
NavViewLeakTest::LifeTimeProbe_TestPage::LifeTimeProbe_TestPage
NavViewLeakTest::LifeTimeProbe_NavView::LifeTimeProbe_NavView
NavViewLeakTest::TestPage::TestPage
NavViewLeakTest::MainPage::~MainPage
3. Click on 'Navigate Backward from TestPage to MainPage' button.
Debug output will contain such strings:
NavViewLeakTest::MainPage::MainPage
NavViewLeakTest::TestPage::~TestPage
NavViewLeakTest::LifeTimeProbe_TestPage::~LifeTimeProbe_TestPage
note the absence of 
NavViewLeakTest::LifeTimeProbe_NavView::~LifeTimeProbe_NavView
NavViewLeakTest::LifeTimeProbe_DataContext::~LifeTimeProbe_DataContext

**Expected behavior**

After the step 3 debug output should also contain evidence of NavigationView and DataContext destruction:
NavViewLeakTest::LifeTimeProbe_NavView::~LifeTimeProbe_NavView
NavViewLeakTest::LifeTimeProbe_DataContext::~LifeTimeProbe_DataContext

**Screenshots**

![NavViewLeakTest_Screenshot](https://user-images.githubusercontent.com/34012295/60732939-192d9e00-9f54-11e9-8e43-ab144b7afc6f.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        | Yes |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by eugenegff** [comment]
Note, that probes are destructed if NavigationView is replaced by Any other control.

Memory leak is also gone if style for NavigationView is tweaked to hide from code parts of template whose content was bound to control.

![NavViewLeakTest_Screenshot2](https://user-images.githubusercontent.com/34012295/60733801-99ed9980-9f56-11e9-8a77-9250abc76f88.png)

**Comment by eugenegff** [comment]
Issue could be fixed by replacing four guilty Bindings by five property changed callbacks on NavigationView.{PaneHeader, PaneCustomContent, PaneFooter, AutoSuggestBox, PaneDisplayMode} properties

**Comment by jevansaks** [comment]
Great bug report! We'll have to take a look. I wonder if there's an easy way to make the Binding target a weak reference instead?

@licanhua maybe you have time to investigate?
