### ISSUE TITLE
ComboBox’s Popup has lost its acrylic transparency effect.

### ISSUE THREAD

**Issue by SQc04** [microsoft/microsoft-ui-xaml#10005]
### Describe the bug

ComboBox’s Popup has lost its acrylic transparency effect. Even though the ComboBoxDropDownBackground pointing to AcrylicInAppFillColorDefaultBrush works correctly, the ComboBox’s Popup does not have transparency over the underlying content.

### Steps to reproduce the bug

ComboBox

### Expected behavior

The ComboBox's Popup should be acrylic transparent, just like the flyout (as shown in Figure 2).

### Screenshots

![image](https://github.com/user-attachments/assets/a03db236-c16f-4aa6-92f3-ded5e3a309f9)
![image](https://github.com/user-attachments/assets/73003642-d7dc-485a-9e2d-5b0f0dc16943)

### NuGet package version

None

**Comment by marcelwgn** [comment]
Thank you for creating this issue @SQc04, since this seems the same as #9523 I'll be closing this in favor of #9523.
