### ISSUE TITLE
Problem scrolling Dialog content in UWP - Windows 10 - DPI 125%, 150% and 175%

### ISSUE THREAD

**Issue by edsonmata** [microsoft/microsoft-ui-xaml#10000]
### Describe the bug

![Screenshot_1](https://github.com/user-attachments/assets/95f1016b-4fa2-4232-abbb-1ab6b5fb8ed4)

The dialog content is cut off when performing the described reproduction steps.
Bug:
- You must have DPI 125%, 150% and 175% and Windows 10
- You must enable the vertical scrollviewer of the dialog content.
- Remove the Title and/or Buttons from the dialog, the problem is more evident.
- Add a quantity of text that shows the scrollviewer
- If the last line has letters like g, j - the end may be cut off when scrolling with the mouse.

Investigating, we realized that Microsoft's own Content dialog ends up making the wrong calculation when enabling the vertical scrollviewer.
This problem occurs specifically in UWP, Windows 10.
Through investigation, it was discovered that when using fixed values

![image](https://github.com/user-attachments/assets/317fb35b-3089-4c96-9b2e-2ded0764955d)

The component behaves properly, but this approach is problematic because it does not know the fixed size of the content.
The correct way is to use it the way Microsoft itself uses it:

![image](https://github.com/user-attachments/assets/7192eab7-a4cc-4462-aa2c-42cdd71d8d77)

### Steps to reproduce the bug

Bug:
- Must have DPI 125%, 150% and 175% and Windows 10
- Must enable the vertical scrollviewer of the Dialog content.
- Remove the Title and/or Buttons from the dialog, the problem is more evident.
- Add a quantity of text that shows the scrollviewer
- If the last line has letters like g, j - the end may be cut off when scrolling with the mouse.

![image](https://github.com/user-attachments/assets/ec1bc6c4-87cd-4550-9bfd-1d5709ab7475)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 10 (21H2): Build 19044

**Comment by whiskhub** [comment]
offtopic, but congrats for creating the 10'000th issue on the WinUI GitHub repo 😅

**Comment by marcelwgn** [comment]
I am unable to reproduce this issue (though I am on Windows 11). Can you tell me where you found that OneUIContentDialogStyle? My app crashes since it's unable to locate that style.

**Comment by FernandoVeras** [comment]
> I am unable to reproduce this issue (though I am on Windows 11). Can you tell me where you found that OneUIContentDialogStyle? My app crashes since it's unable to locate that style.

This a personal style, you can use another style to simulate this bug. 

I'm creating another bug similar at this one, the same problem with border being cuted in 125% dpi 

https://github.com/microsoft/microsoft-ui-xaml/issues/10216
