### ISSUE TITLE
Children property is not being updated after drag complete

### ISSUE THREAD

**Issue by dpaulino** [microsoft/microsoft-ui-xaml#1002]
**Describe the bug**
The `Children` property of an item is not being updated after a different item is dragged into it. 

**Steps to reproduce the bug**
1. Clone the master branch of this repository: https://github.com/dpaulino/treeviewtest
2. Press F5 to launch the uwp app
3. Drag the item named `second` into the item named `first`. This will trigger logic that effectively "cancels" the drop and reinserts `second` back into the root list. 
4. Now do the opposite. Drag `first` into `second`. 
5. Crash occurs because the `Children` property of `second` was not updated.

**Expected behavior**
No crash

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190702001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
This may be related to my previous issue https://github.com/microsoft/microsoft-ui-xaml/issues/631

**Comment by jevansaks** [comment]
@kaiguo sounds similar to the other bug you fixed. It looks like this data source is observable so I think it's doing the right thing on the app side for this to work.

**Comment by dpaulino** [comment]
Hey all, any updates on this issue? Let me know if I can help determine root cause. My customers have been asking for drag and drop in my app for 3 months now and this issue is blocking me.

**Comment by kaiguo** [comment]
> Hey all, any updates on this issue? Let me know if I can help determine root cause. My customers have been asking for drag and drop in my app for 3 months now and this issue is blocking me.

Looking at it now...

**Comment by kaiguo** [comment]
@dpaulino Some operations are async due to the way ItemSource and Layout update works, so the children collection in ItemsSource doesn't have anything yet when you try to access it.

It should work if you put the code in a dispatcher like this,

```C#
private void TreeView_DragItemsCompleted(MUXC.TreeView sender, MUXC.TreeViewDragItemsCompletedEventArgs args)
{
    if (args.Items[0] is ExplorerItem item)
    {
        var dispatcher = CoreApplication.MainView.Dispatcher;
        var ignore = dispatcher.RunAsync(CoreDispatcherPriority.Normal,
            () => {
                ExplorerItem parent = GetParent(ViewModel.Nodes, item);
                parent.Children.Remove(item);
                ViewModel.Nodes.Add(item);
            });
    }
    originalParent = null;
}
```

I think you can probably consider overriding OnDrop method on TreeViewItem to prevent the operation happening from the beginning instead of manually "cancel" the drag&drop by swapping items back.

**Comment by dpaulino** [comment]
I will try the OnDrop method, and I'll report back soon.

**Comment by dpaulino** [comment]
@kaiguo can you point out exactly which "OnDrop" method I'm supposed to use? I tried the code below but the event is never fired when I drop a tree view item onto another tree view item.

```
<c:TreeViewItem ItemsSource="{x:Bind Children}" Content="{x:Bind Name}" AllowDrop="True"
                            Drop="TreeViewItem_Drop" DropCompleted="TreeViewItem_DropCompleted"/>
```

```
        private void TreeViewItem_Drop(object sender, DragEventArgs e)
        {
            // breakpoint here is never hit
        }

        private void TreeViewItem_DropCompleted(UIElement sender, DropCompletedEventArgs args)
        {
            // breakpoint here is never hit
        }
```

Here's a branch you can clone to test out the above code: https://github.com/dpaulino/treeviewtest/tree/dropOnTreeViewItem

**Comment by dpaulino** [comment]
By the way, it may be possible to close this issue if this question could be answered: https://github.com/microsoft/microsoft-ui-xaml/issues/1154

**Comment by kaiguo** [comment]
> By the way, it may be possible to close this issue if this question could be answered: #1154

I commented in #1154, closing this one.
