### ISSUE TITLE
Update SetTitlebar documentation to call out making background Transparent

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1004]
**Describe the bug**
Based on my understanding this requires WinUI3.0 when the rest of the code is here, but perhaps it can be tracked internally.

Given the following XAML on a new page, in combination with the code shown later, I would expect the `Grid` with the name *Titlebar* to be draggable.

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="32" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>

        <Grid Grid.Row="0" Grid.Column="0" x:Name="Titlebar">
            <TextBlock>This is the titlebar. It should be draggable.</TextBlock>
        </Grid>

        <TextBlock Grid.Row="1">Content goes here</TextBlock>
    </Grid>

C# code:

        public MainPage()
        {
            this.InitializeComponent();

            var coreTitlebar = CoreApplication.GetCurrentView().TitleBar;
            coreTitlebar.ExtendViewIntoTitleBar = true;

            Window.Current.SetTitleBar(Titlebar);
        }

Only the text "This is the titlebar. It should be draggable." can be dragged. Setting a background colour, such as 

        <Grid Grid.Row="0" Grid.Column="0" x:Name="Titlebar" Background="Transparent">

will make it work as intended..

**Expected behavior**
Expected that the grid that is set as the titlebar, which spans the width of the Page, should be draggable anywhere inside that grid.

**Version Info**
1903 Desktop

**Additional context**
Github link to repro here: https://github.com/knightmeister/SetTitlebarDoesntWorkWithNoBackground

**Comment by mdtauk** [comment]
If you set the background colour to **Transparent** it will work.  I think its to do with how XAML handles HitTargets.

**Comment by knightmeister** [comment]
> If you set the background colour to **Transparent** it will work. I think its to do with how XAML handles HitTargets.

Yes, I noticed that (and noted it in my bug report). I still would expect this to work without explicitly setting a background colour.

**Comment by Felix-Dev** [comment]
What speaks against _implicitly_ setting the background to "transparent"?

I've seen similar reports where people complained about missing click feedback on controls in scenarios like ListView/GridView items. The answer given was always to set the background of the item template to transparent (i.e. on the root Grid control).

This can be avoided by a) setting the background implicitly to transparent or b) improve the UWP documentation (perhaps a Remarks note in the ListViewItem/GridViewItem section?)

**Comment by YuliKl** [comment]
By default, Grid's background is null so it's simply not visible to hit testing. Because Grid is just a container for arranging UI, having it "disappear" by default feels correct. As you've noted, changing its background from null to Transparent changes that default behavior.

Changing controls to default to a transparent background feels like an enormous breaking change that's likely to break a lot of apps that rely on this null background. I don't think the benefits of making this change would outweigh the risks.

**Comment by Felix-Dev** [comment]
@YuliKl Then I'd advocate for better discovery of a description of this very behavior (and how to enable hit testing by setting the background to transparent (for example)) in the docs. As noted above, perhaps in the ListViewItem/GridViewItem sections?

**Comment by mdtauk** [comment]
The documentation and any examples or templates, should explicitly mention the need for some kind of background being set, explaining why it is needed also I think.

**Comment by chingucoding** [comment]
I've created a PR over at the docs repo to fix the documentation, so we probably can close this issue now or move it to https://github.com/MicrosoftDocs/windows-uwp

**Comment by chingucoding** [comment]
Late update: the PR has been merged: https://github.com/MicrosoftDocs/windows-uwp/pull/2368 @YuliKL @ranjeshj FYI

**Comment by YuliKl** [comment]
Thank you @chingucoding !
