### ISSUE TITLE
Is this currently supported OCR with Windows APP SDK 1.6 （stable）?

### ISSUE THREAD

**Issue by tjinjin95** [microsoft/microsoft-ui-xaml#10048]
### Describe the bug

ref: [https://learn.microsoft.com/en-us/windows/ai/apis/text-recognition](https://learn.microsoft.com/en-us/windows/ai/apis/text-recognition)

I remember the documentation mentioned that Windows APP SDK 1.6 （stable）would support NGAI, such as OCR in the ref, but I didn’t see the relevant libraries when I actually used it. Is this currently supported?

![Image](https://github.com/user-attachments/assets/7af321c6-e4a6-4d14-ab25-645035f89de4)

### Steps to reproduce the bug

1.Create a WinUI3 app by VS2022
2.Nuget windows app sdk 1.6(Latest stable 1.6.240923002)
3.using Microsoft.Windows.Vision;   using Microsoft.Windows.Imaging;      ->    (X)
    

### Expected behavior

OCR API can be found and work well.

### Screenshots

![Image](https://github.com/user-attachments/assets/2fd0a924-0cc2-4a8e-8533-0cc181e9715d)

### NuGet package version

WinUI 3 - Windows App SDK 1.6.1: 1.6.240923002

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmgallahan** [comment]
Wrong repo: https://github.com/microsoft/WindowsAppSDK

**Comment by tjinjin95** [comment]
@kmgallahan Thank you a lot.😁
