### ISSUE TITLE
MenuFlyoutItem with custom template does not have hover or reveal effects

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1006]
**Describe the bug**
Adding a `MenuFlyoutItem` with a custom template does not get the system hover or reveal effect.

This is most likely by design but I would argue that anything added to a menu should be selectable by default. There should be an opt out property for removing hover effects exposed so that the default behaviour is to show an item as selectable and show the reveal border. 

This is inconsistent as the default implementation will close the flyout when the item with the custom template is selected, but the item with the custom template does not indicate that it is selectable/clickable.

**Steps to reproduce the bug**

Reproduction at: https://github.com/knightmeister/MenuFlyoutNoRevealOrSelectionCustomContent

    <Grid>
        <Button Content="Show menu">
            <Button.Flyout>
                <MenuFlyout>
                    <MenuFlyoutItem>
                        <MenuFlyoutItem.Template>
                            <ControlTemplate>
                                <TextBlock>Custom menu doesn't have reveal or selection effect</TextBlock>
                            </ControlTemplate>
                        </MenuFlyoutItem.Template>
                    </MenuFlyoutItem>
                    <MenuFlyoutSeparator />
                    <MenuFlyoutItem Text="Item #1" />
                    <MenuFlyoutItem Text="Item #2" />
                </MenuFlyout>
            </Button.Flyout>
        </Button>
    </Grid>

The first item in the `MenuFlyout` is selectable but does not show hover or reveal effects.

**Expected behavior**
A `MenuFlyoutItem` with a custom template should have the system hover & reveal effects.

**Screenshots**
Reveal on normal `MenuFlyoutItem`:

![image](https://user-images.githubusercontent.com/1528425/60762931-fd89db00-a0ac-11e9-97a2-a4b49d6aae32.png)

Hover on the `MenuFlyoutItem` with the custom template:
![image](https://user-images.githubusercontent.com/1528425/60762935-12666e80-a0ad-11e9-9904-88e9596c9f2b.png)

**Version Info**
1903

NuGet package version: 
N/A

**Github link**
Reproduction at: https://github.com/knightmeister/MenuFlyoutNoRevealOrSelectionCustomContent

**Comment by Poopooracoocoo** [comment]
#559

**Comment by YuliKl** [comment]
@knightmeister, I think what you're describing is not only by design but is a fundamental limitation of Xaml. All the states of a control, including rest, hover, pressed, disabled, etc are defined in its control template. When you overwrite the default control template with a custom one, you gain the responsibility of specifying the control's states.

In this particular scenario, you probably just need to copy parts of `MenuFlyoutItemRevealStyle` from generic.xaml into your custom template.
