### ISSUE TITLE
The app crashes when the CallWindowProc function is used

### ISSUE THREAD

**Issue by MGGSK** [microsoft/microsoft-ui-xaml#10086]
### Describe the bug

The app crashes when the window receives a message. The thrown exception is a System.ExecutionEngineException. It can't be catched using a try block or the App.UnhandledException event. Visual Studio shows that the call to "CallWindowProc" caused the exception (As seen in the screenshot).

### Steps to reproduce the bug

1. Override the default window procedure (IntPtr oldWndProc = SetWindowLongPtr(hWnd, -4, CustomWindowProc);)
2. Call the window procedure that is build into WinUI (CallWindowProc(oldWndProc , hWnd, msg, wParam, lParam);)

### Expected behavior

The window should have a minimum size and all other messages should be handled by WinUI.

### Screenshots

![Image](https://github.com/user-attachments/assets/bd25f6d2-e8ca-4bfd-8564-6b90a0bf541a)

### NuGet package version

WinUI 3 - Windows App SDK 1.6.1: 1.6.240923002

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The code from my app:

    IntPtr oldWndProc = IntPtr.Zero;
    void RegisterWindowMessageHandler()
        => oldWndProc = User32.SetWindowLongPtr(hWnd, -4, NewWindowProc);

    private IntPtr NewWindowProc(IntPtr hWnd, uint msg, IntPtr wParam, IntPtr lParam)
    {
        switch (msg)
        {
            case WM_GETMINMAXINFO:
                var minMaxInfo = Marshal.PtrToStructure<MINMAXINFO>(lParam);
                minMaxInfo.ptMinTrackSize.X = minWidth; // Minimum width
                minMaxInfo.ptMinTrackSize.Y = minHeight; // Minimum height
                Marshal.StructureToPtr(minMaxInfo, lParam, true);
                break;

            default:
                break;
        }

        return User32.CallWindowProc(oldWndProc , hWnd, msg, wParam, lParam);
    }

**Comment by castorix** [comment]
You must use  
```
private delegate IntPtr WinProc(IntPtr hWnd, PInvoke.User32.WindowMessage Msg, IntPtr wParam, IntPtr lParam);
private WinProc newWndProc = null;
newWndProc = new WinProc(NewWindowProc);
```
like in [this thread](https://github.com/microsoft/microsoft-ui-xaml/issues/2945)
(but MS recommends _SetWindowSubclass_ (more recent))

**Comment by MGGSK** [comment]
> You must use
> 
> ```
> private delegate IntPtr WinProc(IntPtr hWnd, PInvoke.User32.WindowMessage Msg, IntPtr wParam, IntPtr lParam);
> private WinProc newWndProc = null;
> newWndProc = new WinProc(NewWindowProc);
> ```
> 
> like in [this thread](https://github.com/microsoft/microsoft-ui-xaml/issues/2945) (but MS recommends _SetWindowSubclass_ (more recent))

That fixed it.

**Comment by enda-mullally** [comment]
Just hit the same issue. Thank you @castorix.

Waiting patiently for min/max height/width, preferred sizing properties to be added to these WinUI3 Window wrappers. I have way too much code behind already :-)
