### ISSUE TITLE
Question: How to get the selected treeview item when ContextFlyout is shown

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1008]
Similar to [this StackOverflow ](https://stackoverflow.com/questions/38768205/how-do-you-use-the-contextflyout-with-a-listview) question, I need to know what node is selected in a `TreeView` when it is right clicked (or presumably long tapped on phone/tablet) and the context flyout is shown.

I could **probably** work around this by using the `ContextRequested` event and programatically showing a `MenuFlyout` but I'd rather do this all by XAML where possible.

I'm using the following `ContextFlyout` as follows:

                      <mux:TreeView.ContextFlyout>
                          <MenuFlyout>
                              <MenuFlyoutItem Text="Hello" Click="Rename_Click" />
                              <MenuFlyoutItem Text="World" />
                          </MenuFlyout>
                      </mux:TreeView.ContextFlyout>

Thanks.

**Comment by jevansaks** [comment]
If this is a single select treeview, it's a bug that SelectedItem isn't populated. Tracked by #124. I don't have a workaround for you at the moment, except you might be able to trawl for the item that has IsSelected on it?

**Comment by knightmeister** [comment]
> If this is a single select treeview, it's a bug that SelectedItem isn't populated. Tracked by #124. I don't have a workaround for you at the moment, except you might be able to trawl for the item that has IsSelected on it?

Appreciate the feedback. How can I get what is selected? I tried to walk the stack of RootNodes, but the item is of type `TreeViewNode` not `TreeViewItem`. My data template is using `TreeViewItem` which is where the `IsSelected` property is - how can I get to these from the tree?

Also, I'm not sure this would work, because the selected item does not change when another item is right clicked - i.e. if I have a tree of 8 items at the root level, the first item is selected and I then right click the third item, the first item remains selected when the menu flyout is shown.

**Comment by jevansaks** [comment]
Is there a way to do this with ListView? @kaiguo mentioned that this is a problem there as well. If that's the case then we probably have some thinking to do around how to expose this information.

**Comment by knightmeister** [comment]
Hey guys, I think this can be closed. Possibly, the documentation should be updated. I figured out how to do it last night with a ListView and (thankfully we have consistency) it's the same way to do it for the treeview.

Rather than showing the menu flyout automatically I'm going to show it manually in response to the [RightTapped](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.righttapped) event.

From the `RightTapped` event, you can pull the item that was tapped/clicked from `e.OriginalSource` from the [RightTappedRoutedEventArs](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Input.RightTappedRoutedEventArgs) parameter.

You can access the data context (what you *probably* want) by casting:

```((FrameworkElement)e.OriginalSource).DataContext```

**Comment by jevansaks** [comment]
We would recommend using ContextRequested since that will catch invocations of the menu from sources other than right-click. But otherwise that makes sense, I'm glad you figured it out.
