### ISSUE TITLE
Flyout shadow display not right while set the CornerRadius

### ISSUE THREAD

**Issue by h82258652** [microsoft/microsoft-ui-xaml#1010]
```XAML
<Grid>
    <Button HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Content="Test">
        <Button.Flyout>
            <Flyout>
                <Flyout.FlyoutPresenterStyle>
                    <Style TargetType="FlyoutPresenter">
                        <Setter Property="Background"
                                Value="White" />
                        <Setter Property="CornerRadius"
                                Value="20" />
                        <Setter Property="Padding"
                                Value="0" />
                    </Style>
                </Flyout.FlyoutPresenterStyle>
                <Border>
                    <TextBlock HorizontalAlignment="Center"
                               VerticalAlignment="Center"
                               Text="Shadow Test" />
                </Border>
            </Flyout>
        </Button.Flyout>
    </Button>
</Grid>
```
![Snipaste_2019-07-08_11-08-08](https://user-images.githubusercontent.com/5144550/60780863-b36b2d00-a172-11e9-99c9-46e5e9f69041.png)

**Comment by YuliKl** [comment]
@h82258652, as the *Note on keyboard focus rect and shadow* in the [Corner Radius How-To document PR](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/34/) states, this isn't really a supported scenario.

**Comment by mdtauk** [comment]
I think it's obvious that **ThemeShadow** is cheating when it is drawn, but there perhaps could be an alternative type of shadow, which actually either reflects the exact shape of the casting element, or at the very least, uses the CornerRadius to alter the shape of the shadow.

**Comment by h82258652** [comment]
> @h82258652, as the _Note on keyboard focus rect and shadow_ in the [Corner Radius How-To document PR](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/34/) states, this isn't really a supported scenario.

Thanks for the response. I change my app SDK version from 17763 to 18362 and found this problem. Is any way to solve this problem now?

**Comment by chigy** [comment]
@h82258652 , can you tell me your scenario why you are creating a flyout that has such a round shape? Are you trying to make your flyout sized to a content or something?

**Comment by h82258652** [comment]
@chigy 
I want to use the same design with other platforms that's why I need a round shape flyout.
I didn't try, I just change my SDK version as I mentioned above.

**Comment by chigy** [comment]
>I want to use the same design with other platforms that's why I need a round shape flyout.

@h82258652 , curious... Could you share with us why you want to use the same design with other platforms? I'm not saying it is good or bad, we are trying to understand the cross-platform wishes and desires of developers. For Fluent, we established that app should "feel native to the platform" which makes using the same design across sort of go against that principle. For Windows, we are going with 4px rounded flyouts for more coherent experience at least for now.

At this point in time, a solution for you is to either not make your flyout so round or turn off shadow. To turn off shadow, refer to this doc. https://docs.microsoft.com/en-us/windows/uwp/design/layout/depth-shadow#disabling-default-themeshadow-on-custom-flyout-controls

**Comment by chigy** [comment]
@h82258652 , as I mentioned, at this point in time, unless you want to make the flyout less rounded, the option is to turn off shadow and I've provided the link above.
