### ISSUE TITLE
Nested x:TypeArguments: "Type was not found" error.

### ISSUE THREAD

**Issue by Wirox** [microsoft/microsoft-ui-xaml#10114]
When using a nested generic type argument with the x:TypeArguments directive (such as Nullable\<bool\>), the following error is incorrectly shown in the XAML file:
![Image](https://github.com/user-attachments/assets/509a954b-6a03-404d-b9c1-5036a92d4dc7)

When you actually run the application, it works fine.

I'm using Visual Studio 2022 17.11.4.

**Comment by karkarl** [comment]
This looks like an issue with IntelliSense with Visual Studio.

**Comment by karkarl** [comment]
> [@karkarl](https://github.com/karkarl) Yeah, I wasn't quite sure where the issue lies. Do you know if this should be reported in https://github.com/dotnet/roslyn then?

You can try opening an issue there. In the meantime, this bug will routed internally to Visual Studio.

**Comment by evelynwu-msft** [comment]
Marking issue as closed as it's related to WPF and not WinUI 3, and a bug has been opened in the corresponding repo.
