### ISSUE TITLE
[WInUI] XLS0503 and WMC0020 errors occur when added the "Blank Window (WinUI 3 in Desktop)" into the MainWindow

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#10123]
### Describe the bug

When added the "Blank Window (WinUI 3 in Desktop)" item into the  MainWindow.xaml. The XLS0503 and WMC0020 errors occur.

### Steps to reproduce the bug

**Affected Branch:**  main
**Affected Build**: 35422.220

1.Create a C# Blank App, Package (WinUI3 in Desktop) project.
2.Right-click the Project name (Desktop) project node in Solution Explorer and select Add -> New Item.
3. In the Add New Item dialog box, select the WinUI tab, choose the "Blank Window (WinUI 3 in Desktop)" to add, and then click Add.
4.Build your solution
5.Add the new item created in step3 into MainWindow.xaml
![Image](https://github.com/user-attachments/assets/71e5eb28-5611-4d67-a84c-dd622927c73f)
6.Press F5

### Expected behavior

The project should be built successfully.

### Screenshots

**Actual Result:**
The project is built failed with XLS0503 & WMC0020 errors.
XLS0503: A value of type 'BlankWindow1' cannot be added to a collection or dictionary of type 'UIElementCollection'.
WMC0020: Cannot add 'BlankWindow1' into the collection property 'Children', type must be 'UIElement'

![Image](https://github.com/user-attachments/assets/7148f825-22a1-4e7b-b0a4-81392ad1510c)

### NuGet package version

None

### Additional context

1. This issue also repro on 17.6.21 p1 [35426.19.d17.6]
2. This issue is not repro on WPF Application project.
![Image](https://github.com/user-attachments/assets/8e213956-12ea-455d-9f5f-d5b2ae39e2d6)

**Comment by codendone** [comment]
I think this is by design: Window in WinUI3 is not a FrameworkElement.
