### ISSUE TITLE
ShowCursor(false) doesn't work. Window not created on UI thread?

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/microsoft-ui-xaml#10128]
### Describe the bug

I cant hide the cursor with [`ShowCursor`](https://learn.microsoft.com/en-gb/windows/win32/api/winuser/nf-winuser-showcursor)

>During the conversion to Win32, the cursor show counter became a thread-local state. (Naturally, multiple threads could merge their cursor show counters by attachment.) Consequently, when a thread calls ShowCursor it affects the cursor show state only for windows that belong to that thread.

https://devblogs.microsoft.com/oldnewthing/20091217-00

This suggests the UI thread was not used to create the window.

### Steps to reproduce the bug

https://github.com/tom-huntington/ShowCursorMRE

### Expected behavior

I expect some way to hide the cursor

### NuGet package version

WinUI 3 - Windows App SDK 1.6.1: 1.6.240923002

### Windows version

Windows 11 (21H2): Build 22000

**Comment by castorix** [comment]
_ShowCursor_ is for Win32 cursors
You can change/hide cursor for XAML UIElements with _ProtectedCursor_
(threads like https://github.com/microsoft/WindowsAppSDK/discussions/1816, https://github.com/microsoft/WindowsAppSDK/discussions/3601, ...)

**Comment by tom-huntington** [comment]
I noticed that `ShowCursor` does in fact hide the cursor... for the window chrome. Some how this is getting overwritten for the client region.
