### ISSUE TITLE
Proposal: Expose XamlDirect for WinUI

### ISSUE THREAD

**Issue by mikernet** [microsoft/microsoft-ui-xaml#10131]
# Proposal: XamlDirect for WinUI

## Summary
Not sure if I am missing something but `XamlDirect` APIs that were available for UWP do not appear to be present in WinUI 3.

I was interested in using them to improve the performance of Uno Platform's C# Markup feature when running on `WinAppSDK` by using `XamlDirect` where possible.

## Rationale

The documentation for `XamlDirect` explains the rationale better than I ever could: https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.core.direct?view=winrt-22621#remarks

>[XamlDirect](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.core.direct.xamldirect?view=winrt-22621) is purpose built for middleware that predominantly use imperative APIs to create UI instead of markup. With [XamlDirect](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.core.direct.xamldirect?view=winrt-22621) APIs, you can achieve performance parity with the XAML parser even when creating UI imperatively in code.
>
> [XamlDirect](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.core.direct.xamldirect?view=winrt-22621) APIs can be used side-by-side with traditional APIs and take advantage of the pay for play performance improvements.

It was designed specifically for this exact scenario.

## Scope
Expose all of UWP's `XamlDirect`-related functionality.

**Comment by karkarl** [comment]
XamlDirect was a retired experiment that was not carried to WinUI3. Closing as not planned.
