### ISSUE TITLE
PaneTitle on NavigationView is getting narrator focus even when its empty

### ISSUE THREAD

**Issue by brunasilvalopes** [microsoft/microsoft-ui-xaml#1017]
**Describe the bug**
When the NavigationView is expanded, there's no PanelTitle assigned to it, and I navigate through it using narrator, the focus disappears after the Menu button and then reappears on the first Menu Item. The focus is getting lost because narrator tries to focus on the PaneTitle, and because it's empty, there's nothing to focus on.

**Steps to reproduce the behavior**
1. Make sure XAML Controls Gallery is installed
2. Launch XAML Controls Gallery
3. Navigate to NavigationView Page
4. Scroll to the bottom of the page to "API in action"
5. Remove PaneTitle using the edit controls on the right
6. Turn on Narrator (Ctrl+Windows+Enter)
7. Navigate to the Menu button
8. Go one element forward (CAPS+Right Arrow) and notice the focus disappears
9. Go one more element forward and notice the focus shows up again on the first Menu Item.

**Expected behavior**
Narrator should go from the Menu button directly to the first Menu Item when there's no PaneTitle.

**Version Info**
XAML Controls Gallery: 1.2.8.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |  Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |              Yes            |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
I'm not able to repro this with the steps provided. 

And when you do see this, are you seeing the title be a narrator stop even after switching to another window and then back to the gallery?
