### ISSUE TITLE
ScrollerView causes app crash in Debug configuration

### ISSUE THREAD

**Issue by kmahone** [Microsoft/microsoft-ui-xaml#102]
Launch MUXControlsTest app in Debug x86 config. Navigate to ScrollerView Tests -> ScrollerViews with simple contents.

A crash occurs:

Unable to cast object of type 'Microsoft.UI.Xaml.Controls.ScrollerInputKind' to type 'System.Int32'.

> Microsoft.UI.Xaml.Markup.winmd!Microsoft.UI.Xaml.Markup.XamlReflectionType.CreateFromString(string value)	Unknown
> [Native to Managed Transition]	
> Windows.UI.Xaml.dll!DirectUI::ActivationAPI::ActivateInstanceFromString(const CClassInfo * pType, const xstring_ptr_view & strValue, IInspectable * * ppInstance) Line 133	C++
> Windows.UI.Xaml.dll!DirectUI::CValueBoxer::UnboxObjectValue(const CValue * box, const CClassInfo * pTargetType, bool targetTypeIsNullable, const _GUID & riid, void * * value) Line 2353	C++
> Windows.UI.Xaml.dll!DirectUI::CValueBoxer::UnboxObjectValue(const CValue * box, const CClassInfo * pTargetType, const _GUID & riid, void * * result) Line 2730	C++
> Windows.UI.Xaml.dll!DirectUI::CValueBoxer::UnboxObjectValue(const CValue * box, const CClassInfo * pTargetType, IInspectable * * value) Line 2741	C++
> Windows.UI.Xaml.dll!DirectUI::PropertyChangedParamsHelper::GetObjects(const PropertyChangedParams & args, IInspectable * * ppOldValue, IInspectable * * ppNewValue) Line 36	C++
> Windows.UI.Xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(const PropertyChangedParams & args) Line 2305	C++
> [Inline Frame] Windows.UI.Xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(CDependencyObject *) Line 2745	C++
> [Inline Frame] Windows.UI.Xaml.dll!CFxCallbacks::DependencyObject_NotifyPropertyChanged(CDependencyObject *) Line 723	C++
> Windows.UI.Xaml.dll!CDependencyObject::NotifyPropertyChanged(const PropertyChangedParams & args) Line 2703	C++
> Windows.UI.Xaml.dll!CDependencyObject::SetEffectiveValue(const CDependencyObject::EffectiveValueParams & args) Line 1588	C++
> Windows.UI.Xaml.dll!CDependencyObject::UpdateEffectiveValue(const CDependencyObject::UpdateEffectiveValueParams & args) Line 1856	C++
> Windows.UI.Xaml.dll!CDependencyObject::SetValue(const SetValueParams & args) Line 1630	C++
> Windows.UI.Xaml.dll!CUIElement::SetValue(const SetValueParams & args) Line 744	C++
> Windows.UI.Xaml.dll!CFrameworkElement::SetValue(const SetValueParams & args) Line 235	C++
> Windows.UI.Xaml.dll!CControl::SetValue(const SetValueParams & args) Line 104	C++
> Windows.UI.Xaml.dll!CDependencyObject::UpdateEffectiveValue(const CDependencyObject::UpdateEffectiveValueParams & args) Line 1896	C++
> Windows.UI.Xaml.dll!CDependencyObject::InvalidateProperty(const CDependencyProperty * dp, BaseValueSource baseValueSource) Line 314	C++
> Windows.UI.Xaml.dll!CFrameworkElement::InvalidateProperty(const CDependencyProperty * pDP, BaseValueSource baseValueSource) Line 947	C++
> Windows.UI.Xaml.dll!CFrameworkElement::OnStyleChanged(CStyle * pOldStyle, CStyle * pNewStyle, BaseValueSource baseValueSource) Line 827	C++
> Windows.UI.Xaml.dll!CControl::ApplyBuiltInStyle() Line 1144	C++
> 

This is not hit in Release configuration.

This is not being hit during test passes since they are run in Release configuration.

**Comment by micahl** [comment]
This is the same as #594.  The fix is in the markup compiler included in the [latest Win10 SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk).
