### ISSUE TITLE
TabView attempts to set its width to an absurdly small number, excepts

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/microsoft-ui-xaml#1020]
**Describe the bug**
https://github.com/microsoft/microsoft-ui-xaml/blob/65414302161b532f59a06c7c8105ca1e8638c809/dev/TabView/TabView.cpp#L314-L326

Stepping through these three conditionals during Windows Terminal startup (MUX package version 2.2.190702001-prerelease) shows that each column is "2147000000 pixels wide". When we attempt to derive an `availableWidth` from the width taken and set it, regardless of the `TabWidthMode`, we get an "invalid argument" HRESULT.

  | Name | Value | Type
-- | -- | -- | --
  | availableWidth | -6442450453.0000000 | double
  | widthTaken | 6442450944.0000000 | double

**Steps to reproduce the bug**
This reproduces in a local dev build of Windows Terminal. I'm not sure how to reproduce it elsewhere.

**Expected behavior**
Doesn't crash.

**Version Info**

NuGet package version: 
2.2.190702001-prerelease

**Additional context**
We're not inserting content into any of the TabView's left/add/right columns.

Xaml islands? We've got a window with xaml content in it, so I believe that it's already laid itself out correctly (ActualWidth is 491.00 on line 330 where availableWidth is calculated.)

**Comment by jevansaks** [comment]
Thanks, @DHowett-MSFT , can you share a branch/commitSha to check out for a build of terminal that repros this? That would help us debug locally.

I'm assigning to @teaP -- she'll be back on wednesday.

**Comment by DHowett-MSFT** [comment]
Sure: microsoft/terminal@cc45a50c, branch `dev/duhowett/nuget_updates`

Incidentally, would the change from is-a ListView to has-a ListView changing the return type of `Items` from `IObservableVector` to `IVector` warrant me filing another issue? Relevant [here](https://github.com/microsoft/terminal/commit/cc45a50c#diff-a011f61f234a66ac8dd94efe8e488244R112).

**Comment by jevansaks** [comment]
> Incidentally, would the change from is-a ListView to has-a ListView changing the return type of `Items` from `IObservableVector` to `IVector` warrant me filing another issue? Relevant [here](https://github.com/microsoft/terminal/commit/cc45a50c#diff-a011f61f234a66ac8dd94efe8e488244R112).

Yes, if only so that we don't lose track of it. It should be straightforward to do so.

**Comment by DHowett-MSFT** [comment]
Done; #1021. Thanks!

**Comment by DHowett-MSFT** [comment]
I'm not seeing this any more.

**Comment by teaP** [comment]
A lot has changed since this bug was filed so if you're not seeing it anymore -- awesome. Let me know if it comes back!
