### ISSUE TITLE
[BUG?] unable to set cursor type to Hand in a AppBarButton  (WINUI3)

### ISSUE THREAD

**Issue by vmiguelangmsft** [microsoft/microsoft-ui-xaml#10227]
Hi everyone! 👋

I've been working on a project where I need to customize the cursor type for an AppBarButton and MenuFlyoutItem  to a Hand cursor. I've looked through the official documentation but haven't been able to find the specific information on how to achieve this.

To give you a bit more context, I'm developing a user interface where it's important for the AppBarButton to clearly indicate it's clickable, hence the need for a Hand cursor. I've tried a few different approaches, but none seem to work as expected.

for instance the code below makes the icon in a AppBarButton.Flyout to have a inconsistent behavior.

```c#
public class CustomAppBarButton : AppBarButton
{
    public CustomAppBarButton():base()
    { 
        ProtectedCursor = InputSystemCursor.Create(InputSystemCursorShape.Hand);
    }
}
```

```xml
<local:CustomAppBarButton x:Name="ShareButton" x:Uid="ShareButton" Foreground="{ThemeResource TextFillColorPrimaryBrush}"
          Width="42">
    <local:CustomAppBarButton.Flyout>
        <MenuFlyout Placement="BottomEdgeAlignedRight">
            <MenuFlyout.SystemBackdrop>
                <MicaBackdrop/>
            </MenuFlyout.SystemBackdrop>                                
            <MenuFlyoutItem Text="X" Command="{x:Bind ViewModel.ShareClickCommand}">
                <MenuFlyoutItem.Icon>
                    <FontIcon FontFamily="{StaticResource glyphs}" Glyph="&#xe900;" />
                </MenuFlyoutItem.Icon>
            </MenuFlyoutItem>
        </MenuFlyout>
    </local:CustomAppBarButton.Flyout>
    <ToolTipService.ToolTip>
        <ToolTip x:Uid="ShareAppBarButtonTooltip" Placement="Bottom"></ToolTip>
    </ToolTipService.ToolTip>
    <FontIcon Glyph="&#xE72D;" FontFamily="{StaticResource SymbolThemeFontFamily}"/>
</local:CustomAppBarButton>
```

Does anyone have experience with this or know where I can find the relevant documentation? Any guidance or examples would be greatly appreciated! 😊

Thanks in advance for your help!

**Comment by ghost1372** [comment]
Cursor property is a protected property. 
But you can use my helper method to change cursor for any uielement:

```
GeneralHelper.ChangeCursor(element, InputSystemCursor.Create(InputSystemCursorShape.Hand));
```

https://github.com/ghost1372/DevWinUI/blob/main/dev/DevWinUI/Helpers/GeneralHelper.cs

**Comment by ghost1372** [comment]
I didn't test on MenuFlyoutItem. And I don't know about it.

**Comment by karkarl** [comment]
Thanks for chiming in @ghost1372. 

There's also this discussion thread in WindowsAppSDK - perhaps this can work as well: https://github.com/microsoft/WindowsAppSDK/discussions/1816

**Comment by vmiguelangmsft** [comment]
Thanks  @karkarl  but MenuFlyoutItem does not work even tried to subclass it.
