### ISSUE TITLE
AcrylicBrush.TintLuminosityOpacity can't be changed in release

### ISSUE THREAD

**Issue by AlKau** [microsoft/microsoft-ui-xaml#1022]
**Describe the bug**
I use the AcrylicBrush from Microsoft.UI.Xaml in my UWP app. The app can crash when TintLuminosityOpacity property is changed in runtime. It happens in Release mode. No matter how the property is changed from code behind or x:Bind.

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
We recently discovered this crash as well. :( Unfortunately I'm not able to recommend a workaround either -- it seems to be an over-release of a temporary object created during the set value call. We can hopefully fix this in the WinUI package at the very least.

**Comment by knightmeister** [comment]
I've also noticed this, and the problem can also be seen in XAML Controls Gallery.

**Comment by jevansaks** [comment]
Problem is understood. I'll work on a fix for WinUI, @codendone will bring a fix in the OS.
