### ISSUE TITLE
MenuFlyout's closing behavior should be configurable

### ISSUE THREAD

**Issue by HotCakeX** [microsoft/microsoft-ui-xaml#10225]
### Describe the bug

The `<MenuFlyout>` 's closing behavior needs to be configurable, so that it doesn't immediately close when the user wants to perform more than one action in the flyout menu.

### Steps to reproduce the bug

This is the exact implementation that causes the problematic behavior displayed above to happen

```xml
<Button>
    <Button.Content>
        <StackPanel Orientation="Horizontal">
            <FontIcon Glyph="&#xE71C;" />
            <TextBlock Text="Filter" Margin="5,0,0,0" />
        </StackPanel>
    </Button.Content>

    <Button.Flyout>
        <MenuFlyout>

            <ToggleMenuFlyoutItem Text="A" x:Name="A" IsChecked="True">
                <ToggleMenuFlyoutItem.Icon>
                    <FontIcon Glyph="&#xEB41;" />
                </ToggleMenuFlyoutItem.Icon>
            </ToggleMenuFlyoutItem>

            <ToggleMenuFlyoutItem Text="B" x:Name="B" IsChecked="True">
                <ToggleMenuFlyoutItem.Icon>
                    <FontIcon Glyph="&#xECC4;" />
                </ToggleMenuFlyoutItem.Icon>
            </ToggleMenuFlyoutItem>

            <ToggleMenuFlyoutItem Text="C" x:Name="C" IsChecked="False">
                <ToggleMenuFlyoutItem.Icon>
                    <FontIcon Glyph="&#xE770;" />
                </ToggleMenuFlyoutItem.Icon>
            </ToggleMenuFlyoutItem>

            <ToggleMenuFlyoutItem Text="D" x:Name="D"
                IsChecked="False">
                <ToggleMenuFlyoutItem.Icon>
                    <FontIcon Glyph="&#xEC12;" />
                </ToggleMenuFlyoutItem.Icon>
            </ToggleMenuFlyoutItem>

        </MenuFlyout>
    </Button.Flyout>
</Button>
```

### Expected behavior

A property to configure the automatic closing behavior of the MenuFlyout.

### Screenshots

https://github.com/user-attachments/assets/ae44f1f1-eef1-43c5-99b9-4770f60f98a4

### NuGet package version

WinUI 3 - Windows App SDK 1.6.3: 1.6.241114003

### Windows version

Windows 11 (24H2): Build 26100

**Comment by DHancock** [comment]
You obviously haven't found the [Closing](https://learn.microsoft.com/en-gb/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.primitives.flyoutbase.closing?view=windows-app-sdk-1.6) event which allows you to cancel the flyout closing in your event handler.

**Comment by HotCakeX** [comment]
> You obviously haven't found the [Closing](https://learn.microsoft.com/en-gb/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.primitives.flyoutbase.closing?view=windows-app-sdk-1.6) event which allows you to cancel the flyout closing in your event handler.

@AndrewKeepCoding suggested this method and it's solved my problem.
https://github.com/HotCakeX/Harden-Windows-Security/pull/452/files
