### ISSUE TITLE
CommandBar near top of window opens up, causes clipping

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1024]
**Describe the bug**

CommandBar appears to always open upward, whether or not there is space to do so.

**Steps to reproduce the bug**

1. Create a new blank app with
```Xaml
    <Grid>
        <CommandBar>
            <AppBarButton Icon="Delete" Label="Delete"/>
            <AppBarButton Icon="Save" Label="Save"/>
        </CommandBar>
    </Grid>
```
2. Run the app
3. Click on More button

**Expected behavior**

CommandBar opens downward.

**Screenshots**

Closed CommandBar:
![image](https://user-images.githubusercontent.com/13142665/60926981-12a56c00-a25d-11e9-93a8-686cd8e99b4c.png)

Opened CommandBar:
![image](https://user-images.githubusercontent.com/13142665/60926996-1c2ed400-a25d-11e9-9390-02914aaed4dd.png)

**Version Info**

NuGet package version: 

N/A. Targetting 18362 SDK.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18916)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by hansmbakker** [comment]
This is not only a problem when it is at the top of the page. It also makes it impossible to vertically center `CommandBar.Content` elements, and it produces an ugly gap below the buttons.

There is a 4px shift up of all elements inside the `CommandBar` when `IsOpen` switches to `true`, and I believe this is a bug.

**Comment by hansmbakker** [comment]
![CommandBar-bug](https://user-images.githubusercontent.com/3463496/97109727-26d0df00-16d5-11eb-9d29-7c79e335b757.gif)
![CommandBar-bug-top](https://user-images.githubusercontent.com/3463496/97109728-27697580-16d5-11eb-8fa1-02991634d922.gif)
![CommandBar-bug-verticallyalign](https://user-images.githubusercontent.com/3463496/97109729-28020c00-16d5-11eb-8303-11e1ab2249a0.gif)

**Comment by hansmbakker** [comment]
For me, there is a workaround shared by @v-zhumin [on StackOverflow](https://stackoverflow.com/questions/64524669/uwp-commandbar-moves-vertically-when-isopen-changes):

```xml
<AppBarSeparator Height="40"/>
```

That one worked for me.

However, I see that @YuliKl did not use `AppBarSeparator`, so for her it must be caused by something else?

Can you pick this up and solve the bug so that the workaround is not needed anymore?
Can you investigate what other causes there might be?

**Comment by kmgallahan** [comment]
@hansmbakker 

I believe you are running into the same issue described in #1454.

**Comment by hansmbakker** [comment]
> I believe you are running into the same issue described in #1454, although I didn't check using your repro.

@kmgallahan 
Please check my repro, because although there is similarity, there are really differences as well.

I am not using scaled text for example, which the issue you mention is about.
