### ISSUE TITLE
Win 10: There’s a problem with Microsoft Windows App Runtime DynamicDependency LifetimeManager. Reinstall the application from its original install location or contact your administrator

### ISSUE THREAD

**Issue by Rex000** [microsoft/microsoft-ui-xaml#10247]
### Describe the bug

After recent Windows update it pops up every now and then. I have seen online many people have this issue.

### Steps to reproduce the bug

N/A

### Expected behavior

N/A

### NuGet package version

None

### Windows version

Windows 10 (21H2): Build 19044

**Comment by karkarl** [comment]
This is a Windows OS issue and not related to WinAppSDK platform. Please file this issue on Feedback Hub.
