### ISSUE TITLE
Incorrect ExtentWidth and ExtentHeight returned for ScrollViewer 

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1026]
**Describe the bug**
When the ScrollViewer is loaded for the first time and the `SizeChanged` event handler is fired the ScrollViewer object does not provide the correct values for `ExtentWidth` and `ExtentHeight` , returned values are same as `ActualWith` and `ActualHeight`. Even when `Loaded` event is fired we don't get the correct values.

However, if we now change the size and `SizeChanged` event fired again, the ScrollViewer object has the correct values.

**Steps to reproduce the bug**

XAML
```XML
        <muxc:ScrollViewer
            x:Name="ScrollViewer"
            Grid.Row="1"
            Grid.Column="0"
            Grid.ColumnSpan="5"
            HorizontalScrollBarVisibility="Hidden"
            HorizontalScrollMode="Enabled"
            Loaded="ScrollViewer_OnLoaded"
            SizeChanged="ScrollViewer_OnSizeChanged"
            VerticalScrollMode="Disabled"
            ViewChanged="ScrollViewer_OnViewChanged">
            <muxc:ItemsRepeater x:Name="CategoryItems">
                <muxc:ItemsRepeater.ItemTemplate>
                    <DataTemplate x:DataType="viewModels:ContentViewModel">
                        <local:ContentView ViewModel="{x:Bind Mode=OneWay}" />
                    </DataTemplate>
                </muxc:ItemsRepeater.ItemTemplate>
                <muxc:ItemsRepeater.Layout>
                    <muxc:StackLayout Orientation="Horizontal" Spacing="10" />
                </muxc:ItemsRepeater.Layout>
            </muxc:ItemsRepeater>

        </muxc:ScrollViewer>
```
Code Behind

```csharp
        private void ScrollViewer_OnLoaded(object sender, RoutedEventArgs e)
        {
            var scroller = (ScrollViewer)sender;
            Previous.IsEnabled = scroller.HorizontalOffset > 0;
            Next.IsEnabled = scroller.ExtentWidth - (scroller.HorizontalOffset + ScrollViewer.ViewportWidth) > 0;
        }

        private void ScrollViewer_OnSizeChanged(object sender, SizeChangedEventArgs e)
        {
            var scroller = (ScrollViewer)sender;
            Previous.IsEnabled = scroller.HorizontalOffset > 0;
            Next.IsEnabled = scroller.ExtentWidth - (scroller.HorizontalOffset + ScrollViewer.ViewportWidth) > 0;
        }
```

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190702001-prerelease] 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
I think Loaded might be too early -- Layout hasn't run yet. @RBrid can you recommend a different event to listen for in this scenario?

**Comment by RBrid** [comment]
@harvinders, could you please listen to the ScrollViewer.ExtentChanged event. That should work. Thank you.

**Comment by RBrid** [comment]
@harvinders, also make sure that you are using the appropriate ScrollViewer,ContentOrientation property value. It looks like you want Horizontal instead of Vertical.

**Comment by harvinders** [comment]
@RBrid, thanks for that. I am not 100% sure but it seems my code worked with `Windows.UI.Xaml` `ScrollViewer`. Anyway other thing I noticed is that signatures for some event has `object` parameter instead of class derived `EventArgs`

    public extern event TypedEventHandler<ScrollViewer, object> IScrollViewer.ExtentChanged;
    public extern event TypedEventHandler<ScrollViewer, object> IScrollViewer.StateChanged;
    public extern event TypedEventHandler<ScrollViewer, object> IScrollViewer.ViewChanged;

In case of `ExtentChange` the second parameter of type `object` is coming as `null`, when the event is invoked.

**Comment by RBrid** [comment]
@harvinders, thanks. That is intentional. There are many controls that follow that pattern. Here are just a few as examples:
    event Windows.Foundation.TypedEventHandler<NavigationView, Object> PaneClosed;
    event Windows.Foundation.TypedEventHandler<NavigationView, Object> PaneOpened;
    event Windows.Foundation.TypedEventHandler<NavigationView, Object> PaneOpening;

    event Windows.Foundation.TypedEventHandler<Layout, Object> MeasureInvalidated;
    event Windows.Foundation.TypedEventHandler<Layout, Object> ArrangeInvalidated;

    event Windows.Foundation.TypedEventHandler<TabView, Object> AddButtonClick;

When there is no event-specific info we use a null object.
