### ISSUE TITLE
WinUI for desktop application

### ISSUE THREAD

**Issue by JohnF38** [microsoft/microsoft-ui-xaml#1027]
Hi everybody, 

I'm starting a new desktop-only application for Windows 10 and I'm not sure if WinUI is the right choice.

My desktop application deals with mathematical data processing and representation : different types of graphs that require heavy drawing on multiple floating windows.

I'd like to use c++/winrt  with Windows UI Library for this application.
Do you think WinUI would be OK (or will soon become OK) for this kind of application ?

Thanks for your help !
John

**Comment by michael-hawker** [comment]
Welcome @JohnF38!

WinUI doesn't have graph/charting controls it contains many more elements to create application interfaces or displaying different layouts of list or tiled data.

It will work perfectly fine and complement other libraries that can do so though, for instance using DirectX.

_Were there specific areas of your application you want to use controls in WinUI to address or specific scenarios or questions you had about integrating certain components together?_

**Comment by knightmeister** [comment]
The Telerik Controls for UWP provide a [Chart control](https://www.telerik.com/universal-windows-platform-ui/chart), which is (depending on your desired license) free and open source (free as in cost).

My biggest issues around window management have been:
1. Each window must be on its own thread. This is a good idea but it means you need to take care with your data structures and lock when you need to.
2. No proper dialog support - I have raised #885 and #930 - there is a content dialog which is great but doesn't fit all use cases.

Ultimately it's great using a modern framework that (I think) looks and behaves nicely. Sure beats using controls from User in a WinForms or C/C++/MFC/whatever app.

**Comment by mdtauk** [comment]
UWP Desktop has the potential to harness some of the power of those Win32 frameworks, but using a modern XAML UI.

What you are asking for, is more about Windowing APIs, and that will be part WinUI Desktop, and part changes to the Windows 10 OS

**Comment by JohnF38** [comment]
Many thanks for your answers !
Please find further details

I've been using wxWidgets during the last 10 years.
It's very easy to learn and only requires average computing skills.
But it seems wxWidgets development is now somehow stalling, so I'm looking around for fresh options.
The modern Win UI really looks great !

The new Win10 desktop application I need to develop requires:

Heavy bitmap drawing to represent data (clusters of points, lines, curves).  I don't rely on charts, those drawing functions will be implemented in the app.

Floating windows, any representation of the data set needs its own floating windows on the app.
Each floating window contains a bitmap for data set representation

Do you think Win UI would be fine for this ?

Thanks !
