### ISSUE TITLE
 RadioMenuFlyoutItem: changing selected item when menu is hidden is not working

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#1028]
**Describe the bug**
Changing the selected item from a radio menu flyout group from code behind/visual state/binding is not working.

**Steps to reproduce the bug**
1. Create a application with the following XAML code
```xml
<StackPanel>
<Button Content="Options button">
    <Button.Flyout>
        <MenuFlyout>
            <mux:RadioMenuFlyoutItem x:Name="radioButton1" GroupName="group" Text="Option 1" />
            <mux:RadioMenuFlyoutItem x:Name="radioButton2" GroupName="group" Text="Option 2" />
            <mux:RadioMenuFlyoutItem x:Name="radioButton3" GroupName="group" Text="Option 3" />
        </MenuFlyout>
    </Button.Flyout>
</Button>

<Button Content="Select option 1" Click="OnSelectOption1" />
<Button Content="Select option 2" Click="OnSelectOption2" />
<Button Content="Select option 3" Click="OnSelectOption3" />
</StackPanel>
```
2. Add the following code behind to force the selection of the items 
```csharp
private void OnSelectOption1(object sender, RoutedEventArgs e) => radioButton1.IsChecked = true;
private void OnSelectOption2(object sender, RoutedEventArgs e) => radioButton2.IsChecked = true;
private void OnSelectOption3(object sender, RoutedEventArgs e) => radioButton3.IsChecked = true;
````

3. Launch the application
4. Click on the "Options button" button
5. The menu flyout opens
6. Click on "Option 1"
7. "Option 1" radio menu item is now selected
![image](https://user-images.githubusercontent.com/20152272/60982182-ee6a8d80-a337-11e9-8fde-e8827fc0ef0d.png)
8. Dismiss the flyout menu
9. Click on "Select option 2"
10. Click on "Options button" to reopen th flyout
11. Both "Option 1" and "Option 2" are selected.
![image](https://user-images.githubusercontent.com/20152272/60982206-f7f3f580-a337-11e9-9951-7a588c3fd093.png)

**Expected behavior**
"Option 2" option should be the only selected option.

**Version Info**
NuGet package version: Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Additional context**
I've looked at the implementation and think I've found the issue. The [`UpdateSiblings()`](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem.cpp) method is unable to find the parent element of the selected item to unselect all the other radio menu items. 
`VisualTreeHelper::GetParent()` is returning null when the menu is not displayed.

**Repro**
[MuxRadioMenuItems.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3378263/MuxRadioMenuItems.zip)

**Comment by jevansaks** [comment]
Thanks for filing and debugging it too! I wonder if we could use DependencyObject.Parent instead of VisualTreeHelper::GetParent?

**Comment by vgromfeld** [comment]
> I wonder if we could use DependencyObject.Parent instead of VisualTreeHelper::GetParent?
I've tried and it is not working, both `VisualTreeHelper::GetParent()`  and `Parent` return `null` 😥

**Comment by mdtauk** [comment]
Is there no "buffer" for UI Elements that exist, but are not in the visual tree?

**Comment by jevansaks** [comment]
> Is there no "buffer" for UI Elements that exist, but are not in the visual tree?

Well I would have expected DependencyObject.Parent to work (the "logical" tree in WPF terms) but we'll have to debug it. 😕

**Comment by chingucoding** [comment]
I have looked into this, and tried accessing the parent when the RadioMenuFlyoutItem gets created, however since the popup is not open at creation, the Parent() and the VisualTreeHelper::GetParent() functions both return null. 

If there is no other way to access the parent (the MenuFlyoutPopup), the only solution to this problem seems to be to change the MenuFlyoutPopup to explicitly set the parent to the child elements or rework them to somehow have a reference to the other elements.

@jevansaks Any ideas regarding this? 😅

**Comment by ranjeshj** [comment]
@MikeHillberg @codendone @Austin-Lamb  Should DO.Parent be working in this case ? Are there any other ways to get from one sibling to another when the flyout is not open ?

**Comment by MikeHillberg** [comment]
[FrameworkElement.Parent](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.FrameworkElement.Parent) and [VisualTreeHelper.GetParent](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Media.VisualTreeHelper.GetParent) are the same and return null if the element's not in the live tree. I remember that that was done to solve a lifetime problem, I don't remember why a weak reference wasn't used. But maybe that could be done in the flyout items?

**Comment by chingucoding** [comment]
As long as the menu flyout does not get rendered, the RadioMenuFlyoutItem has no way of knowing it's parent as we don't pass them to the items. Since the code for MenuFlyout(Item) is inside the OS right now, this might be only be fixable with WinUI 3.0 :/

**Comment by vgromfeld** [comment]
Can we use an internal (attached?) property object to store the group/items relations instead of using the parent ? Something tied to the `GroupName` property ?

This *group* (attached) property would keep the links to all the `RadioMenuFlyoutItem`s and contains the logic done today in the `UpdateSiblings()` method.

**Comment by chingucoding** [comment]
Unfortunately, the way RadioMenuFyloutItem's works, we need to ask the parent whether or not there are siblings and what values it does have. Unlike the RadioButton**s** control, groups are defined using the the structure and relation in the visual tree, which is a pain point when we are not in the visual tree. If there was some sort of equivalent of RadioButtons for the Menuflyout, we could work with that, but the current way would probably be either not easy to use or fail if we don't know the parent.
