### ISSUE TITLE
Unable to style the MenuBarItem Flyout

### ISSUE THREAD

**Issue by jordui** [microsoft/microsoft-ui-xaml#1035]
There appears to be no way to style the flyout which appears in a menu bar item. In WPF the Popup was declared in XAML allowing us to make cutom changes to the flyout. Currently the menu flyout is created in code. I tried making a generic MenuFlyoutPresenter style but it isnt  getting picked up. Perhaps the code could check if the named ContentButton has a flyout and use that. or failing that the MenuBarItem needs a MenuFlyoutStyle DP?

**Comment by jevansaks** [comment]
@yulikl thinks there might be a way to do this, but if it's not straightforward then a new property on MenuBar & MenuBarItem for the style seems fine.

**Comment by YuliKl** [comment]
@jordui
I was able to modify the style of MenuBarItem's flyout by placing an implicit style in my App.xaml resources.
```Xaml
<Style TargetType="MenuFlyoutPresenter">
    <Setter Property="Background" Value="Red"/>
</Style>
``` 
This had the effect of coloring the backgrounds of all MenuBarItems and all MenuFlyouts in my app.

Can you tell us more about your scenario? Are you trying to style the Flyout of a single MenuBarItem, or all flyouts in a MenuBar? What aspects of the flyout do you need to style?

**Comment by jordui** [comment]
@YuliKl Ah yes you're right, I put the implicit style into my App.xaml and it worked. I thought it would work implicitly in my local usercontrol xaml resources (I also tried inside the MenuBarItem overridden Style.Resources). 

I am currently working with a customized version of the 19H1 Win32 XamlIslands sample using cppwinrt and mux as we need to use win32 for our app (at least for now). We have our own colour scheme manager so everything will need to be styled for most controls; the background colour and padding etc. That's not to say we couldn't consider ThemeResources though.

**Comment by YuliKl** [comment]
@jordui, sounds like your issue is resolved so I'll go ahead and close it. Please reopen if I'm misunderstanding.

**Comment by MarkIngramUK** [comment]
@YuliKl is it intentional that styling the flyout only works globally (via `App.xaml`) as opposed to locally in `MyUserControl.xaml`? For reference, we're using XAML Islands in Win32, so in theory we might want to have the ability to style menus differently depending on what window or dialog they appear on.

**Comment by YuliKl** [comment]
> @YuliKl is it intentional that styling the flyout only works globally (via `App.xaml`) as opposed to locally in `MyUserControl.xaml`? For reference, we're using XAML Islands in Win32, so in theory we might want to have the ability to style menus differently depending on what window or dialog they appear on.

I definitely would not call this intentional. While I didn't try adding the style to a user control, I did try making it a resource of the Page and more specific components. @MikeHillberg, any thoughts on this?
