### ISSUE TITLE
Hello World example ?

### ISSUE THREAD

**Issue by JohnF38** [microsoft/microsoft-ui-xaml#1036]
Hi everobody, 

I'd like to know if some basic examples ( Hello World! ) are available for WinUI with c++/winrt ?

Thanks, 
John

**Comment by jesbis** [comment]
I don't think we have too many examples for C++/WinRT yet.
[Calculator](https://github.com/microsoft/calculator) is one example but it's not very basic 🙂

You should be able to use the basic ["Blank app" C++/WinRT template](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package), then just add the WinUI NuGet package reference to the project and include the headers - there's an example here:

https://docs.microsoft.com/uwp/toolkits/winui/getting-started#additional-steps-for-a-cwinrt-project

Does that help?

**Comment by jevansaks** [comment]
Agreed, this should "just work". Let us know if you have any more questions!

(As an aside we'll expand the docs to include these details, @yulikl is following up on that)

**Comment by jesbis** [comment]
There's now a documentation page that walks through the steps for a "Hello world" WinUI + C++/WinRT in more detail: 

https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/simple-winui-example
