### ISSUE TITLE
Question: Reducing the size of AppBarButtons inside a CommandBar

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1041]
In my app, I need to display small buttons to control formatting for a text field (such as bold, italic, underline, etc).

The default size of an `AppBarButton` inside a `CommandBar` is quite large. I reduced the size by specifying the height & width of it, which worked fine, until the width becomes too small and buttons start being moved to the overflow menu area of the CommandBar. Here, the text is truncated because I have specified the height and width and just looks bad.

Is there a way that I can have small buttons in my `CommandBar`, but when the overflow menu is shown they are the normal width (where you can fully see the label)?

**Comment by mdtauk** [comment]
Is there a reason why you can't use the CommandBarFlyout control for this.  It is used by Office for their Text Formatting?

![image](https://user-images.githubusercontent.com/7389110/61128065-eaaa4880-a4a8-11e9-95b9-83d738a7cd57.png)

Is there some scope in enabling the CommandBarFlyout to be used like a Toolbar, or to provide styling for the ApplicationBar so it uses the same smaller buttons and overflow menu?

**Comment by jevansaks** [comment]
@lucashaines possibly a job for density?

**Comment by Poopooracoocoo** [comment]
@mdtauk oh hey. the commandbarflyout doesnt look like the one in Office. The layout is better and has more (although that's onenotes fault :P).
 
![image](https://user-images.githubusercontent.com/51363864/61166819-94f0a180-a577-11e9-907f-e9205eb48813.png)
