### ISSUE TITLE
Factor out DisableAnimationsStyles*.xaml into appropriate feature areas

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#1044]
**Describe the bug**
DisableAnimationsStyles.xaml and DisableAnimationsStylesOutsideStore_rs2.xaml are currently hardcoded to load from the test app. We should factor this out into individual projects and load them automatically when the project is compiled into mux.dll

Once this is done INNERLOOP_BUILD define can be removed

**Comment by chingucoding** [comment]
I'm not sure if I understand this correctly. Are you proposing that we create a new project inside the MUX.dll that contains those file and that we enable/disable them through feature flags? Does setting a compiler flag on the test app projects propagate down to MUX.dll?
