### ISSUE TITLE
Untangle Acrylic, Reveal, Effects and ColorPicker in feature area builds

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#1046]
**Describe the bug**
Currently Acrylic, Reveal, Lights, Effects and Color picker are kind of using each other in code/tests.. Would be nice to untangle them so that they can be built separately or other feature areas can be built without these.

This involves commenting these out in featureareas.props, building and making the parts that fail conditional compile.

**Comment by chingucoding** [comment]
Having looked into this, I am not sure if there is much we can do. The areas Acrylic,Reveal,Lights and Effects rely so heavily on each other (mainly Reveal depends on lights and effects). 

One thing worth thinking about is removing parts of lights area and move it into the reveal project, but in the end it does not make a huge difference as those will need to be compiled again anyway.

ColorPicker is only needed for some test pages.

So should I/we try to just not compile those areas (acrylic,reveal,lights and effects) everytime and just add them as dependencies where needed?
