### ISSUE TITLE
TemplateBinding and TemplatedParent Binding return different values (UnsetValue vs null) on failure to resolve

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#1048]
using TemplateBinding in VisualState.Setters will make app crash while using TemplatedParent won't.

**Comment by jevansaks** [comment]
They should be behaviorally equivalent, with the Binding to TemplateParent enabling more complex paths and converters. But I wouldn't have expected TemplateBinding to crash. What is the call stack you see?

**Comment by alwu-msft** [comment]
@HppZ if you could provide a repro project that would be ideal as it would ensure that we are investigating the right thing.

**Comment by HppZ** [comment]
https://github.com/HppZ/TemplateParentBug

**Comment by alwu-msft** [comment]
Thanks for the repro! So it seems like your template binding (whether as `{TemplateBinding}` or `{Binding RelativeSource={RelativeSource TemplatedParent}})` doesn't resolve to a value. However, there is a subtle difference in what the two markup expressions return: in the former case it's `unset value` whereas in the latter case it's `null`. VSM setters raise an error (when a debugger is attached) if Setter.Value is `unset value`, but `null` is considered a valid value.

Having said that, starting with the 1903 release VSM Setters *should* be permitting `unset value` on Setter.Value, so I suspect we have a bug of the backwards-logic sort in the framework.

**Comment by HppZ** [comment]
since it is a bug, please fix it, thanks!

**Comment by fabiant3** [comment]
Changed title, we'll be considering this issue in the future (bug, not a question anymore). Thanks for reporting and providing the sample code HppZ!

**Comment by alwu-msft** [comment]
Created issues #1104 and #1105 to track different aspects of the overall reported failure.

**Comment by chingucoding** [comment]
@StephenLPeters Should this be marked as WinUI 3 since this is currently part of OS XAML?

**Comment by StephenLPeters** [comment]
I think it should actually just be closed, Winui 3 wont have OS version specific code and from the comments it looks like this was fixed in 1903 so it should already be fixed in Winui 3. @alwu-msft can you confirm and close?

**Comment by anawishnoff** [comment]
This issue should be fixed as of the latest Windows App SDK 0.8 release, so I'm closing this. Let me know if it still persists and we can re-open.
