### ISSUE TITLE
Update TwoPaneView to use ApplicationViewMode::Spanning

### ISSUE THREAD

**Issue by teaP** [microsoft/microsoft-ui-xaml#1051]
Since this enum value doesn't currently exist in the published SDK that WinUI is using, I am hardcoding it. Once we upgrade to a new SDK which has the value this should be updated.

**Comment by lmcdougald** [comment]
Does this mean that WinUI 2.3 TwoPaneView doesn't respect the split? And if so, which WinUI version can we expect that to land in?

**Comment by SavoySchuler** [comment]
@teaP or @ranjeshj, will fixes for TwoPaneView like this be added to WinUI 2 or are we now looking at the WinUI 3 releases given the 10X focus shift to single screen? No pressure - I am only looking to provide accurate answers to a community member who was asking. Thanks! 🙂
