### ISSUE TITLE
Proposal: Define and implement distinct button styles, outline, fill, and ghost

### ISSUE THREAD

**Issue by chigy** [microsoft/microsoft-ui-xaml#1054]
# Proposal: Introduce button styles, outline, fill, and ghost

## Summary
Upon close visual analysis as part of request logged with #953 , it came to our attention that controls in WinUI appear to use mix of multiple button styles in one. This proposal is to clearly define each style and implement them as such for cleaner visual look and feel as well as better developer story.

## Rationale
* XAML controls are inconsistent with how web and mobile apps are evolving – this highlights the inconsistency across app ecosystem on Windows when these UI are used intermixed with each other.
* This is part of the work to refresh the UI to align with other platforms while keeping familiarity of the Windows. (part of request logged with #953)
* This logic supports WinForms and WPF as using the outline style.

## Scope
Note, since Windows will default to use the fill style, the focus and priority is set on fill style. 

| Capability | Priority |
| :---------- | :------- |
| Outline, fill and ghost style buttons are defined in documentation for app creators to be able to use them properly | Must |
| Developers are able to use WinUI2.2* package and without any work, get the new Windows visual style for fill button (this includes all variations of buttons like dropdownbutton) | Must |
| Changes outlined here must not be via control re-templating | Must |
| Developers and end users experience control update that feel coherent with the same controls used by Fabric, Edge, and Xbox. | Should |
| Checkbox and Radiobutton also defines the outline and fill styles and implements appropriate style (tracked with #839) | Should |
| Create clear outline and ghost style button design definition (i.e. visual comp) as well as sample definition in our doc | Should |
| Build built in named button styles for easy adoption by the devs | Could |

*Timing here is not a commitment, but to follow the release cycle. Just using the next version #.

## Important Notes
Actual visual comp is still being worked on but here's the high level style definition to outline the context of this proposal.
![image](https://user-images.githubusercontent.com/22958680/61986942-7783f480-afc7-11e9-80db-dc6a5259057b.png)

Here's the visual comp for all the proposed changes for fill.
![image](https://user-images.githubusercontent.com/22958680/62401160-d4872980-b536-11e9-9b16-6e6626113ab8.png)

In comparison, WPF, WinForms, and Fabric all use outline style (WPF sort of combines the two).
![Comparison](https://user-images.githubusercontent.com/22958680/61254987-935fde80-a71b-11e9-9243-a8f546182e0e.png)

Fill style is more visible especially against background that is not a solid color. Windows shell tend to use this style more as the buttons tend to be drawn on top of other UI element that is not solid white or black.

Instead of updating the default to outline which will be a huge change for our existing customers, proposal here is to keeping it to fill style but updating the visual so that there's no confusion between fill and outline styles that exist today.

**Comment by mdtauk** [comment]
Would these be provided as a style a dev can choose to use, or perhaps as an **enum** of something like **ButtonKind** with
* ButtonKind.Default
* ButtonKind.Primary
* ButtonKind.Outline

And if this is implemented, would these styles or enums extend to TextFields with buttons, or Dialogs and Message Boxes?  What about System UI like the Share Dialog?

**Comment by chigy** [comment]
> Would these be provided as a style a dev can choose to use, or perhaps as an **enum** of something like **ButtonKind** with
> 
> * ButtonKind.Default
> * ButtonKind.Primary
> * ButtonKind.Outline
> 
> And if this is implemented, would these styles or enums extend to TextFields with buttons, or Dialogs and Message Boxes? What about System UI like the Share Dialog?

Currently, I'm thinking it is a "could" option. Given shell is not using the outline, before we would supply something built into the system, I'd rather it be tested through style. 

There is no TextFields with button today. That'll be just a button that is used next to TextFields. Dialog should be using default button style and it should use the fill style unless decided otherwise, but good point, I should make sure it happens when we do this update. MessageBox is just a container where you'd put a button.

Share Dialog is a dialog created by another team who should be just getting the update when they take WinUI drop.

**Comment by mdtauk** [comment]
Looking at a few common controls next to each other, in **Outline**, **Default** (Filled) and **Primary** (Accent) style

![button styles extended](https://user-images.githubusercontent.com/7389110/61295336-be0b6f00-a7cf-11e9-82ca-8daf316b5715.png)


The CheckBoxes being proposed would be a mix of these.  Accent for Checked States, but Outline for Unchecked.
But Filled for use on GridViews.

Text Boxes would fit more of the Outline State, but filled with a subtle light colour to "lift" it from the background.

Buttons could be available in all three styles, but do other controls need to also be available in different styles?

Should the controls have a deliberate mix of these in a semantic way?  For instance, when a control is set to an off state, it uses an outline style.  ToggleSwitch does this, as do the RadioButtons and CheckBoxes. 
So an outlined button would be used for a less important action, where a filled button would do something more important, and Accented button is confirmatory or permanent in nature?

Form Fields are buttons in behaviour, where as Editable Form Fields are closer to TextBoxes.  So would they be available in all 3 styles too like buttons?

----

I know I am probably overthinking all this, but I believe the look of a control should impart some meaning to its behaviour and usage in the App or OS Shell

**Comment by mdtauk** [comment]
Just to add some more to the discussion.  Windows Phone 8 moved controls from a filled style to an outline style compared to Windows Phone 7.

![comparison-3](https://user-images.githubusercontent.com/7389110/61296896-f791a980-a7d2-11e9-8011-971a571ab8fa.jpg)

Windows 8 used an outline style for some controls in Light Mode, but Filled in Dark
![image](https://user-images.githubusercontent.com/7389110/61297209-a8984400-a7d3-11e9-8c06-e0f41373912a.png)

![image](https://user-images.githubusercontent.com/7389110/61297269-c9609980-a7d3-11e9-9558-9f49bb60a385.png)

----

Windows 10 unified the control designs between Mobile and Desktop, and most of these oddities are gone now.  But WinUI 3.0 feels like a fresh start, and so thinking through all these things, and learning from what went before is important.

**Comment by chigy** [comment]
### Status update
Updated the proposal to prepare for the pitch review as well as based on discussion with design team about how to rationalize the styles.

**Comment by Poopooracoocoo** [comment]
Why are you introducing an outlined style?

btw we can't forget that Windows has links. Look at the wifi flyout for example

**Comment by mdtauk** [comment]
> Why are you introducing an outlined style?
> 
> btw we can't forget that Windows has links. Look at the wifi flyout for example

Hyperlink Button is a separate control in WinUI XAML

**Comment by chigy** [comment]
> Why are you introducing an outlined style?
> 
> btw we can't forget that Windows has links. Look at the wifi flyout for example

@Poopooracoocoo , could you explain why you don't think it is a good idea to introduce outlined style? As is on any platform, there are many styles that a button can support?

I am not sure what your comment about the links. I do not believe links is neither a fill nor outline?

**Comment by Poopooracoocoo** [comment]
@chigy I'm not saying that I think it's a good or bad idea. I'm just wondering why. :) 

I know Material Design has a filled, outlined and text buttons but Chrome/ChromeOS don't (or rarely) use text buttons. I mentioned links because links are like text buttons from Material Design. 
Windows has accent buttons, primary filled buttons and links. Primary filled buttons are kinda like outlined buttons (if you compare it to Material).  

I hope I made sense. this all confuses me lol

**Comment by chigy** [comment]
> @chigy I'm not saying that I think it's a good or bad idea. I'm just wondering why. :)

The reason is because we saw some inconsistencies in the UI. We felt our UI was using fill and outline somewhat interchangeably. Also, Fabric UI uses outline while Windows use fill. This is purposeful. So, rather than keeping it at the confused state, we decided to clearly define and describe where to use which style and we are starting this with WinUI.

We are trying to establish Fluent Design _System_, so as we go through the UI to align, I am trying to make sure we have a system that we can explain why certain things are being chosen and reason for differences we see.

Clearly, I am not explaining it well and I take that as a feedback.

I probably should look at the links/text buttons but not current priority. Feel free to open it as a new idea for us to incubate. :)

**Comment by chigy** [comment]
### Status update
Upon further examination of the system with design team, we are adding ghost style to the list of styles. I'm still waiting for the comp from design to add it before the review.

**Comment by mdtauk** [comment]
Ghost Style.  Is that a new name for the outline style, or is this something new and different.

**Comment by chigy** [comment]
> Edit: So it's a new style... Is that something coming from the shell team, or maybe Xbox?

@mdtauk ,
Ghost style is something that we identified used for shell and Edge. Hopefully I can update the comp soon (Monday for sure). Naming could change, that's what design team calls it so I'm just using it as is for now.

> Also will there be guidance as to when each of these **4** styles should be used?

That's the idea. As soon as I get this proposal approved, we will move onto the guidance/spec piece where you will see those definitions.

**Comment by chigy** [comment]
### Status update
Ghost comp added

**Comment by mdtauk** [comment]
@chigy so Ghost is basically a **Borderless** style, to go along with Outlined, Filled, and Accent Filled styles.

But no text decoration or accent colour as with the hyperlink button.

**Comment by Poopooracoocoo** [comment]
Ghost complicates everything. How will users know what is a button and what is text?

**Comment by mdtauk** [comment]
> Ghost complicates everything. How will users know what is a button and what is text?

The guidance will help decide when each should be used, as will the apps that use that style - acting as best practice examples.

**Edge's uses...**
![image](https://user-images.githubusercontent.com/7389110/62063771-72bb7c80-b223-11e9-89a5-cb982d654868.png)

**UWP uses**
![image](https://user-images.githubusercontent.com/7389110/62064320-7ef40980-b224-11e9-9aa6-965ca1c0b4b3.png)
![image](https://user-images.githubusercontent.com/7389110/62064436-c084b480-b224-11e9-9366-573aa5453def.png)
![image](https://user-images.githubusercontent.com/7389110/62064769-76500300-b225-11e9-9ef3-686729dc81a8.png)
_Filled TextBox styles_
----

How will these be implemented on the button?  Making it be a ``Style="{ThemeResource GhostButtonStyle}"`` type of approach, wont be very discovarable, but would work well if you were to also add Ghost, Outlined, Filled styles for other form controls like TextBoxes etc - which could also have ``{ThemeResource FilledTextBoxStyle}`` type styles.

But you could do it as an enum on the Button or TextBox controls themselves:
* ButtonStyle="Filled" - ButtonStyle = ButtonStyle.Filled
* ButtonStyle="Outlined" - ButtonStyle = ButtonStyle.Outlined
* ButtonStyle="Accent" - ButtonStyle = ButtonStyle.Accent
* ButtonStyle="Ghost" - ButtonStyle = ButtonStyle.Ghost

**Comment by chigy** [comment]
### Status update
Based on team pitch review, this item is being tabled for future release and I'm bringing the #953 so we can have the border removal in the WinUI2.2 timeframe. This proposal is going to be a bit more lengthy than what we could do in that timeframe.

**Comment by mdtauk** [comment]
Pushing forward with thinking through the Outlined button style.

### Toggle Button

![image](https://user-images.githubusercontent.com/7389110/62253580-4738bd80-b3ee-11e9-91e8-391967734fbf.png)

Here are some rough initial thoughts.  I made some changes to the existing Filled and Accent button styles, as well as came up with an idea for the Outlined and Ghost Styles.

- With Accent style being made formal, I felt the Default ToggleButton should probably not use it for its toggled state, to avoid confusion.  So I use an "inverted" approach which gives emphasis.
- Like with the text and picker controls, I gave the Outlined buttons a 2px border, using the accent colour, for their toggled state. (I am not entirely happy with both Default and Accent styles sharing the same Toggled on state design, but apart from adding a border when toggled, I can't immediately think of a better approach)
- I took the idea of the selection indicator from the Pivot control, and used it for the Toggle State on the Ghost style buttons.

**Comment by mdtauk** [comment]
### Split Button
![image](https://user-images.githubusercontent.com/7389110/62348017-a0d6e000-b4f3-11e9-98ed-d096922a7e95.png)

**Comment by mdtauk** [comment]
Will Buttons use the Semibold font weight like Edgium and Fabric Web, as opposed to the regular weight like UWP XAML and FastDNA. as well as Hyperlinks and Body text?

![image](https://user-images.githubusercontent.com/7389110/62345126-e510b300-b4e8-11e9-8cab-1599149115c2.png)
_200% scale_

**Comment by chigy** [comment]
> Will Buttons use the Semibold font weight like Edgium and Fabric Web, as opposed to the regular weight like UWP XAML and FastDNA. as well as Hyperlinks and Body text?

No, we plan on keeping it on regular.

**Comment by chigy** [comment]
### Status update
Created #1126 to cover the topic of reveal and removed it from this proposal.

**Comment by mdtauk** [comment]
In my personal WinUI design doc I am building, I am trying to apply these Accent, Filled, Outlined, and Ghost styles across all the controls

![Default Button - 14-08-2019](https://user-images.githubusercontent.com/7389110/62985118-bc17e880-be2d-11e9-88bc-9ddceef852f6.png)

![Toggle Button - 14-08-2019](https://user-images.githubusercontent.com/7389110/62985186-039e7480-be2e-11e9-9332-e5b1bec481ad.png)

**Comment by mdtauk** [comment]
Looking at FastDNA's Buttons, they have chosen to use the name **Stealth** rather than **Ghost**

https://explore.fast.design/components/stealth-button

**Comment by chigy** [comment]
> Looking at FastDNA's Buttons, they have chosen to use the name **Stealth** rather than **Ghost**
> 
> https://explore.fast.design/components/stealth-button

@mdtauk , thanks and I know. We have not gotten to a place where we would agree with the name so naming is not the priority for us. Understanding the behavior and style detail is...

**Comment by mdtauk** [comment]
> > Looking at FastDNA's Buttons, they have chosen to use the name **Stealth** rather than **Ghost**
> > https://explore.fast.design/components/stealth-button
> 
> @mdtauk , thanks and I know. We have not gotten to a place where we would agree with the name so naming is not the priority for us. Understanding the behavior and style detail is...

I wasn't approving or suggesting the name, just bringing it to the attention of this discussion.  As it becomes more formalised in their UI Kit.  I think it was previously something like _Lightweight Button_.

**Comment by YuliKl** [comment]
Closing this issue for now. We won't be adding distinct styles at this time, but proposed changes to the default styles are summarized in #3546.
