### ISSUE TITLE
AppBarButton.IsInOverflow property not working

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#1056]
**Describe the bug**
I'm trying to have a different access key placement for `CommandBar`'s `AppBarButton`s when in primary or overflow menu.
This behavior is not supported by default so I've tried with some custom code and found that the `AppBarButton.IsOnOverflow` is not behaving as expected.

**Steps to reproduce the bug**
1. Create a new application with the following XAML code:
```xml
<CommandBar
    HorizontalAlignment="Center"
    VerticalAlignment="Center"
    AccessKey="M"
    DefaultLabelPosition="Right"
    IsDynamicOverflowEnabled="True"
    DynamicOverflowItemsChanging="CommandBar_DynamicOverflowItemsChanging"
    KeyTipPlacementMode="Top">
    <AppBarButton AccessKey="A" Icon="Accept" Label="Accept" KeyTipPlacementMode="Top"/>
    <AppBarButton AccessKey="B" Icon="Add" Label="Add" KeyTipPlacementMode="Top"/>
    <AppBarButton AccessKey="C" Icon="AddFriend" Label="Add friend"  KeyTipPlacementMode="Top"/>
    <AppBarButton AccessKey="D" Icon="AllApps" Label="All apps" KeyTipPlacementMode="Top"/>
</CommandBar>
```
2. Add the following code behind to change the `KeyTipPlacementMode` property of the `AppBarButton` based on their `IsIsOverflow` state.
```csharp
private void CommandBar_DynamicOverflowItemsChanging(CommandBar sender, DynamicOverflowItemsChangingEventArgs args)
{
        var primaryOverflowButtons = sender.PrimaryCommands;
        var secondaryOverflowButtons = sender.SecondaryCommands;
        var allButtons = primaryOverflowButtons.Concat(secondaryOverflowButtons).OfType<AppBarButton>();

        foreach (var ob in allButtons)
        {
            ob.KeyTipPlacementMode = ob.IsInOverflow ? Windows.UI.Xaml.Input.KeyTipPlacementMode.Left : Windows.UI.Xaml.Input.KeyTipPlacementMode.Top;
            Debug.WriteLine($"## isInOverflow {ob.IsInOverflow}");
        }
}
```
3. Run the application
4. The access keys remain at their default position (top in this case) and are displayed above the overflow menu items' labels.

**Expected behavior**
When items are moved to the overflow menu, the `CommandBar.DynamicOverflowItemsChanging` event callback is invoked and the key tip placement is set to the expected value. (left for overflow, top otherwise).

**Screenshots**

Here is what we see when running the sample program in a narrow window:
![image](https://user-images.githubusercontent.com/20152272/61301138-9cb47e00-a7e3-11e9-9df5-9be5027a0e31.png)

Here is what we expect to see:
![image](https://user-images.githubusercontent.com/20152272/61301292-eb621800-a7e3-11e9-8463-8ee8a94c1160.png)

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes but workaround available   |
| October 2018 Update (17763)        | Not tested |
| April 2018 Update (17134)          | Not tested  |
| Fall Creators Update (16299)       | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |   |
| Xbox                      |   |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
The sample application is working on build 18362 when using the `Dispatcher` to delay the execution of my code:

```csharp
private async void CommandBar_DynamicOverflowItemsChanging(CommandBar sender, DynamicOverflowItemsChangingEventArgs args)
{
    await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () =>
    {
        var primaryOverflowButtons = sender.PrimaryCommands;
        var secondaryOverflowButtons = sender.SecondaryCommands;
        var allButtons = primaryOverflowButtons.Concat(secondaryOverflowButtons).OfType<AppBarButton>();

        foreach (var ob in allButtons)
        {
            ob.KeyTipPlacementMode = ob.IsInOverflow ? Windows.UI.Xaml.Input.KeyTipPlacementMode.Left : Windows.UI.Xaml.Input.KeyTipPlacementMode.Top;
            Debug.WriteLine($"## isInOverflow {ob.IsInOverflow}");
        }
    });
}
```
With this trick, I'm able to see what I want.
It has no effect at all on RS3 😥

**Reproduction code**
[CommandBarTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3397489/CommandBarTest.zip)

**Comment by jevansaks** [comment]
Looking at the code, it makes sense that IsInOverflow wouldn't be updated yet -- it's DynamicOverflowItemsChang<B>ing</B> so it hasn't changed yet. The delay until the dispatcher event seems like a good workaround ... but I can't explain why it doesn't work in RS3. With WinUI 3.0 you'll get the 19H1 behavior everywhere so I wouldn't spend too much time looking at RS3.

I'm inclined to close this item and focus our effort on the linked proposal to solve this for you in the post-WinUI 3.0 world.

**Comment by vgromfeld** [comment]
I've spent more time on this and found that I can use the `AccessKeyDisplayRequested` event to do what I want. When raised, all the controls are in the appropriate state to do the key tip placement mode change I want. 
This approach is working fine on RS3.

```csharp
private void AppBarButton_AccessKeyDisplayRequested(Windows.UI.Xaml.UIElement sender, Windows.UI.Xaml.Input.AccessKeyDisplayRequestedEventArgs args)
{
    var appBarButton = (AppBarButton)sender;
    appBarButton.KeyTipPlacementMode = appBarButton.IsInOverflow ? Windows.UI.Xaml.Input.KeyTipPlacementMode.Left : Windows.UI.Xaml.Input.KeyTipPlacementMode.Top;
}
```

@jevansaks Agree to close this one and focus on #1057 for WinUI 3.x. 
I'm fine to use my workaround until WinUI integrates #1057.
