### ISSUE TITLE
Proposal: example for each control

### ISSUE THREAD

**Issue by JohnF38** [microsoft/microsoft-ui-xaml#1065]
Hello users !

It would be great to have a simple code example for each control type.
So you can clearly understand how to use specific features of a control, without being flooded by useless code.

The wxWidgets project has kind of samples; it's extremely valuable for new users (like me ! ).

Cheers
John

**Comment by huoyaoyuan** [comment]
Is the [Xaml Controls Gallery](https://github.com/Microsoft/Xaml-Controls-Gallery) enough?

**Comment by jevansaks** [comment]
Thanks @huoyaoyuan ! Yes, I agree that Xaml Controls Gallery is our solution here. If there's a sample missing there, please file an issue on that github to request it!
