### ISSUE TITLE
Popup & ThemeShadow (windowed popups can't cast shadows on other popups)

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#1074]
**Describe the bug**
when set Popup's ShouldConstrainToRootBounds to true, the ThemeShadow behaves strange.

**Steps to reproduce the bug**
https://github.com/HppZ/PopupThemeShadowBug

**Screenshots**
![QQ截图20190718093810](https://user-images.githubusercontent.com/12285582/61423322-efa44780-a941-11e9-9f4e-e172ab9ce1ea.png)
![QQ截图20190718094601](https://user-images.githubusercontent.com/12285582/61423323-f03cde00-a941-11e9-91e3-66366fe28c57.png)

**Version Info**
Windows 10 18362.239

**Comment by jevansaks** [comment]
This is because all the non-windowed Popups cast shadows onto the (hidden) PopupRoot. When they're windowed then they cast onto the desktop. 

I'll let @codendone decide out whether this is a "bug".

**Comment by HppZ** [comment]
@codendone please help

**Comment by codendone** [comment]
In general, the ShouldConstrainToRootBounds=true rendering, where the shadow from the second popup projects onto the first popup, is the intended/desired behavior.  By default, popups should be able to project shadows on other popups plus the main app content.

When popups are windowed (ShouldConstrainToRootBounds=false), the shadows are drawn outside of XAML's popup window via the Windows shell.  To optimize performance and simplicity for the shell code, it uses a single shadow receiver below the first opened popup.  This implementation unfortunately prevents the second popup from being able to cast a shadow on the first popup.  It isn't the desired behavior and we would like to fix this at some point, but it isn't currently high priority.

(In either case, if the popups have the same depth (/Translation.Z), then there will be no shadow in the overlap region.)
