### ISSUE TITLE
Question: Top and Bottom padding for flyouts - can it be removed?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1079]
![image](https://user-images.githubusercontent.com/7389110/61500621-f5db0800-a9c3-11e9-869f-1bd4c81ac78a.png)

All flyout menus have uneven padding at the top and bottom, compared to the sides.  Why is this the case, and should it be removed so menu items will be flush with the edges of the flyout - or at least even padding on all edges?

Adding the rounded corners may be an opportunity to reconsider this design choice, as similar menu controls in other Microsoft UI frameworks don't do this.

![image](https://user-images.githubusercontent.com/7389110/61500777-96c9c300-a9c4-11e9-8e75-89cc3303c10b.png)
![image](https://user-images.githubusercontent.com/7389110/61500839-bc56cc80-a9c4-11e9-9b33-6ef6b9ad7f7e.png)

_FastDNA Dropdown and ComboBox_

![image](https://user-images.githubusercontent.com/7389110/61500875-d690aa80-a9c4-11e9-91f9-27a36f561455.png)
![image](https://user-images.githubusercontent.com/7389110/61500901-f2944c00-a9c4-11e9-8f5b-d0f79ac16852.png)
_Fabric Web ComboBox and ContextualMenu_

![image](https://user-images.githubusercontent.com/7389110/61500930-135ca180-a9c5-11e9-9c9e-01913f16f8d8.png)
![image](https://user-images.githubusercontent.com/7389110/61500964-3be49b80-a9c5-11e9-9e54-22caffd35e1c.png)

_Office UWP XAML_

**Comment by chigy** [comment]
Checking with our design team.

**Comment by chigy** [comment]
In theory, we agree with the question that we probably don't need these added padding anymore with changes happening with the visuals. That said, in practice, there could be a consequence by doing so, one question I have is if it would look nice with the focus rect. And this is not a priority so we will address it when we have a chance. I'll add this to the visual change backlog.

**Comment by mdtauk** [comment]
@chigy the Xbox shell already had a focus visual that extends beyond the bounds of the control.  I think there is precedence there

**Comment by chigy** [comment]
> @chigy the Xbox shell already had a focus visual that extends beyond the bounds of the control. I think there is precedence there

@mdtauk , can you point out where this is seen?

**Comment by mdtauk** [comment]
> > @chigy the Xbox shell already had a focus visual that extends beyond the bounds of the control. I think there is precedence there
> 
> @mdtauk , can you point out where this is seen?

![image](https://user-images.githubusercontent.com/7389110/62065629-4ace1800-b227-11e9-89b6-4ff3ecc013df.png)

I added some lines to this screenshot.  You see the controls are lined up, and the Focus Visual appears around the outside of the control

**Comment by chigy** [comment]
@mdtauk , thank you! 

What you are showing, though, the focus rect is still flesh with the control border so they do not leave gaps whereas if we have a focus rect on flyout without the padding, there's going to be some gap between the flyout and focus rect. 
![image](https://user-images.githubusercontent.com/22958680/62091029-e78eb680-b223-11e9-80ff-29310717986a.png)

Talked with the design team and maybe it is not bad given the rounded corner is subtle but will have to look at what happens. This is part of the reason we are guiding not to use too big of a rounded corner.

**Comment by mdtauk** [comment]
I don't think the focus rect looks too bad extending outside of the Flyout

![image](https://user-images.githubusercontent.com/7389110/62092381-dc13ad80-b26c-11e9-852b-dcc45d0023b2.png)

**Comment by chigy** [comment]
> I don't think the focus rect looks too bad extending outside of the Flyout

@mdtauk , you missed the one in question. Please put the focus on the item that is actually rounded...

**Comment by mdtauk** [comment]
> > I don't think the focus rect looks too bad extending outside of the Flyout
> 
> @mdtauk , you missed the one in question. Please put the focus on the item that is actually rounded... Also, we draw focus rect inside, not outside of the menus.

In the bottom example, the top item is rounded.  The focus rectangle remains squared off as is the guidance.

**Comment by JustinXinLiu** [comment]
I do like some paddings for each group sections. One of the reasons is that this way, we don't need to provide a different border style for the very top or bottom menu item. I believe this is how Material Design has done it too.

However, we should get rid of the left and right paddings.

**Comment by mdtauk** [comment]
> I do like some top and bottom paddings for each group sections. One of the reasons is that this way, we don't need to provide a different border style for the very top or bottom menu item. I believe this is how Material Design has done it too.
> 
> However, we should get rid of the left and right paddings.

![image](https://user-images.githubusercontent.com/7389110/62500899-5baafa80-b7e0-11e9-8ce4-baff758e4e28.png)  
![image](https://user-images.githubusercontent.com/7389110/62501046-d8d66f80-b7e0-11e9-8825-80c7ed2cc0d3.png)

_Material Design Menu_

Not sure I agree with your reasoning there.  I find the top and bottom padding to be a little distracting, it adds more visual clutter, seeing the small gaps between separators, and selection backgrounds.

![image](https://user-images.githubusercontent.com/7389110/62500777-cf98d300-b7df-11e9-8503-80185c330494.png)

Not sure what border style you are talking about, if you mean the hover background for the Flyout Menu items, that should be clipped by the flyout itself right?

Also not every flyout is consistent with this top and bottom padding...
![image](https://user-images.githubusercontent.com/7389110/62500724-b5f78b80-b7df-11e9-9144-4b36dcf65e86.png)

**Comment by JustinXinLiu** [comment]
I am referring to the corner radius of the context menu.

If there’s no gap, then the top most menu item will have a different corner radius than zero, same as the bottom most one.

Potentially, they could be taller than the rest of the menu items too if you ever want to give the context menu a padding.

**Comment by mdtauk** [comment]
> I am referring to the corner radius of the context menu.
> 
> If there’s no gap, then the top most menu item will have a different corner radius than zero, same as the bottom most one.
> 
> Potentially, they could be taller than the rest of the menu items too if you ever want to give the context menu a padding.

The flyout shape would crop, so the rounded corners would come for free essentially.  I don't see the rounding being a problem personally.

Like most panel controls, the internal padding would affect the contents, I would imagine by default the flyout padding would be set to 0, so by default, they would look as they should.

This also feeds into a question I have.  At the moment, flyout menus adapt to whether they were invoked by Touch or Pointer.  What about Date and Time, Calendar flyouts?  Shouldn't these adapt too?
![image](https://user-images.githubusercontent.com/7389110/62596304-a52b4080-b8d9-11e9-82e2-67841f5be564.png)


What about when a Picker control is using a compact density, shouldn't that also affect the flyout it shows?

![image](https://user-images.githubusercontent.com/7389110/62596251-6dbc9400-b8d9-11e9-909f-41fd9be19190.png)

**Comment by chigy** [comment]
>This also feeds into a question I have. At the moment, flyout menus adapt to whether they were invoked by Touch or Pointer. What about Date and Time, Calendar flyouts? Shouldn't these adapt too?

@mdtauk , We considered that and we ended up not having enough resources to implement. As far as I am aware, no user has complained to us about the sizing being an issue.

**Comment by mdtauk** [comment]
@chigy  Compact density has not really been implemented in any first party apps, to have gathered feedback on.  But it seems a shame to allow this inconsistency to continue, because of a lack of interest or resources, the second being understandable, the former very disappointing.

The fact the selected part of the flyout is taller than the control which is summoning it, looks like a bug, rather than an intended design.

**Comment by chigy** [comment]
>The fact the selected part of the flyout is taller than the control which is summoning it, looks like a bug, rather than an intended design.

@LucasHaines to comment on the fact compact density entry point would open up non-compact one causing the sizes to be inconsistent. Do we have a backlog on this or is this intentional?

**Comment by chigy** [comment]
>it seems a shame to allow this inconsistency to continue, because of a lack of interest or resources, the second being understandable, the former very disappointing.

@mdtauk , I understand. However we do not have unlimited resources so we need to prioritize our work. We do try to prioritize things customers see often and are commonly used first. And we know the Date/Time picker is not used very much by our customers so we cannot justify spending a lot of time on it.

**Comment by mdtauk** [comment]
> > it seems a shame to allow this inconsistency to continue, because of a lack of interest or resources, the second being understandable, the former very disappointing.
> 
> @mdtauk , I understand. However we do not have unlimited resources so we need to prioritize our work. We do try to prioritize things customers see often and are commonly used first. And we know the Date/Time picker is not used very much by our customers so we cannot justify spending a lot of time on it.

I understand why, but it is still unfortunate.

**Comment by chigy** [comment]
>I understand why, but it is still unfortunate.

@mdtauk , what you could do if you want to make a difference here and any other issue like this is if you could make a case from usability perspective. Inconsistency sometimes cause usability issues. Those are types of issues that is easier to get traction than a small annoyance. I know that small issues become a bigger annoyance (thousand paper-cuts) but we have to start somewhere... And if we are to start somewhere, we should start from the issues we can prove we are making the difference.

**Comment by mdtauk** [comment]
@chigy  I don't have the data to put forward a detailed case, other than the fact it visually looks like a bug, and is inconsistent to other controls which both adapt to touch/cursor input, and Compact Density.

ComboBox flyouts are larger when you use a touch screen to make it drop down, compared to using a cursor.
Calendar, Date and Time Pickers, do not, and perhaps they should.

The design of the Date and Time picker centres the flyout above the control, and so the selection matches the 32px height, so it appears seamless, as if the whole control is expanding out.

When Compact Density is used, the control becomes 24px, but the flyout isn't affected.  This is not what you would expect, and appears to be a bug.

If some of the proposals ( #918 #735 #905 ) are considered, then this disconnect between the flyout and the control it expands from, will look even more stark.

![image](https://user-images.githubusercontent.com/7389110/62748615-2d802180-ba51-11e9-994f-b0a27fb53f75.png)

**Comment by chigy** [comment]
@mdtauk , I am not debating it is indeed a bug or something we *should* fix. I am letting you know that we do not have the resources to fix everything so we use the severity and data to make a call. In this case, this issue does not meet the bar. However as you mentioned, if we do the other proposals, then this should be considered. You should mention this bug in the other 3 proposals but I cannot justify fixing this issue by itself. BTW, did you open a bug for this issue? If not, you should and mention it on the other 2 proposals you mentioned. This proposal will not be tracking fixing that because this proposal does not make the issue worse.

**Comment by mdtauk** [comment]
Thank you @chigy, now it is considered a bug, I have submitted it as such. #1148

**Comment by chigy** [comment]
@jevansaks , I have the design decision for this item. Does this item need to be turned into a bug or can we reuse this question item?

1. Design would like the **_Left and Right_** pudding to be removed.
2. Please DO NOT remove **_Top and Bottom_** margins.

@mdtauk FYI
The reason for not removing top/bottom margin is because they would like retain optical vertical rhythm seen below. Without the top/bottom margin, the first and last items appear too close to the edge.

![image](https://user-images.githubusercontent.com/22958680/66687718-811d1000-ec38-11e9-9c99-a5df4308be9b.png)

**Comment by mdtauk** [comment]
It is only when you hover over a top or bottom item, that the gap looks awkward.  Ideally the top and bottom items would have a different size with a top and bottom padding, so hovering over would look flush with the edge of the flyout.

But it seems that this will not be changed, so it makes sense to close this.
