### ISSUE TITLE
Scroller wheel zooming while scrolling ends up way off

### ISSUE THREAD

**Issue by adrientetar** [microsoft/microsoft-ui-xaml#1085]
**Describe the bug**

I have a very large canvas in a Scroller. If I scroll down with the wheel and immediately unzoom by pressing Ctrl with it, I end up in position very far away (going towards bottom right of the scrollable area).

**Steps to reproduce the bug**

1. Have a scroller with a large scrollable+zoomable area
2. Scroll down the mouse wheel
3. Hit Ctrl while still scrolling down (which is zooming out the content area). You are propelled at the bottom right of the scrollable area.

**Expected behavior**

I would only scroll by a page or so.

**Screenshots**

I can provide screencast if needed.

**Version Info**

2.2.190702001-prerelease

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | X   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | X   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
Thanks for reporting! @RBrid is obviously the expert here but he's on vacation until late August. Would you like to take a crack at debugging it, @adrientetar  ? :)

**Comment by adrientetar** [comment]
@jevansaks Sure, I don't think I've a debug environment setup for the MUX package though. I'd have to go build it on my machine?

**Comment by jevansaks** [comment]
@adrientetar the symbols are [indexed on MSDL](https://docs.microsoft.com/en-us/windows/win32/dxtecharts/debugging-with-symbols#using-the-microsoft-symbol-server), and source indexed to point at GitHub. So you should be able to debug through the code without a MUX setup and likely figure out the problem that way.

But if you want to clone the repo and build it, you just need Visual Studio 2019 with the 18362 SDK installed. I'm happy to help you get up and building if you want to go that route.

**Comment by RBrid** [comment]
Thanks for the bug report @adrientetar. I opened an internal bug 23255271 against the underlying InteractionTracker component, with these comments:

> Here's the customer scenario:
> The InteractionTracker-based XAML Scroller control contains a large scrollable and zoomable content.
> That content is centered in the Scroller.
> The user starts to scroll down with the mouse wheel.
> While that vertical scroll is in progress the user hits the Control key and continues to rotate the mouse wheel.
> Result: the resulting horizontal position of the content is unexpectedly high. The InteractionTracker can properly handle vertical mouse-wheel-based scrolls, it can properly handle mouse-wheel-based zoom-in/out, but it does not seem to handle one immediately followed by the other. The horizontal position changes caused by the zoom-out seem to be overridden by the original scrolling.
> 
> Here's a log of events reported by the XAML Scroller for instance. The original horizontal offset is 4000, vertical offset is 4000 and zoom factor (i.e. scale) is 10.  There is lots of room for scrolling and zooming out:
> 
> StateChanged Inertia
> ViewChanged HorizontalOffset=4000, VerticalOffset=4004.19775390625, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4008.34790039063, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4015.853515625, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4023.27368164063, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4033.38598632813, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4043.3828125, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4055.54907226563, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4067.57641601563, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4081.36108398438, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4094.98852539063, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4110.04833984375, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4124.93701171875, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4141.001953125, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4156.8837890625, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4172.40185546875, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4187.6044921875, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4202.6337890625, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4217.318359375, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4231.93017578125, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4249.18212890625, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4266.2373046875, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4284.029296875, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4304.12255859375, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4326.271484375, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4350.2568359375, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4375.8828125, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4401.216796875, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4425.9697265625, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4447.7216796875, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4469.2255859375, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4490.236328125, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4509.33447265625, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4528.21484375, ZoomFactor=10​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4546.66259765625, ZoomFactor=9.974897​
> ViewChanged HorizontalOffset=3989.65991210938, VerticalOffset=4534.67919921875, ZoomFactor=9.950081​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4564.466796875, ZoomFactor=9.950081​
> ViewChanged HorizontalOffset=3981.49975585938, VerticalOffset=4542.9462890625, ZoomFactor=9.905788​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4581.42529296875, ZoomFactor=9.905788​
> ViewChanged HorizontalOffset=3973.35620117188, VerticalOffset=4550.32373046875, ZoomFactor=9.842284​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4597.34423828125, ZoomFactor=9.842284​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4612.04248046875, ZoomFactor=9.762179​
> ViewChanged HorizontalOffset=3966.28588867188, VerticalOffset=4572.4384765625, ZoomFactor=9.682987​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4625.35205078125, ZoomFactor=9.682987​
> ViewChanged HorizontalOffset=3963.11303710938, VerticalOffset=4581.90283203125, ZoomFactor=9.597045​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4637.12158203125, ZoomFactor=9.597045​
> ViewChanged HorizontalOffset=3957.10034179688, VerticalOffset=4586.46875, ZoomFactor=9.497981​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4647.216796875, ZoomFactor=9.497981​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4655.5224609375, ZoomFactor=9.38772​
> ViewChanged HorizontalOffset=3951.74340820313, VerticalOffset=4598.33056640625, ZoomFactor=9.278716​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4661.94482421875, ZoomFactor=9.278716​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4666.4091796875, ZoomFactor=9.170586​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4668.8662109375, ZoomFactor=9.063687​
> ViewChanged HorizontalOffset=3952.10717773438, VerticalOffset=4611.9521484375, ZoomFactor=8.95924​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.95924​
> ViewChanged HorizontalOffset=3956.01635742188, VerticalOffset=4617.1005859375, ZoomFactor=8.864423​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.864423​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.759457​
> ViewChanged HorizontalOffset=3950.76586914063, VerticalOffset=4610.8603515625, ZoomFactor=8.655687​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.655687​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.553195​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.45187​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.352869​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.257319​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.16631​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.080879​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=8.002001​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=7.930573​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=7.86741​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=7.813232​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=7.768658​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=7.734193​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=7.710233​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=7.697049​
> ViewChanged HorizontalOffset=4000, VerticalOffset=4669.375, ZoomFactor=7.694317​
> StateChanged Idle​
> 
> As you can tell it starts with a vertical scroll, and then the zoom-out operation's impact on HorizontalOffset is repeatedly undone, thus the content seems to fly to the left as noted by the customer.
> 
> Expected:
> The final horizontal offset should be smaller than 4000 since the content was zoomed out.
> 

I am afraid there's nothing the Scroller control can do at this point since the InteractionTracker is directly handling the mouse-wheel and Control key inputs. I will make sure this issue is on the InteractionTracker team's radar.

**Comment by adrientetar** [comment]
Pretty funny that the interactiontracker seems to race against itself, I think maybe because it was developed for touch where iirc, you're either panning or pinch-zooming but not both at the same time.

@RBrid, did the interactiontracker team tell you whether they'll fix this in this windows cycle?

**Comment by RBrid** [comment]
@adrientetar, that team already fixed the bug I opened for them, but I have not verified their fix yet.

**Comment by adrientetar** [comment]
FYI, I just updated to v1909 and recompiled but the issue is still present. There's no new SDK in this update so maybe that's why the bug is still there?
