### ISSUE TITLE
Bug: Incorrect BasedOn causes crash when debugger not attached

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1086]
**Describe the bug**
This bug took me a bit to track down. The behavior is very specific to reproduce.

When a style is defined in a resource dictionary, and applied to a control that is incompatible with the `BasedOn` attribute of the style, the application will crash when the debugger is not attached.

**Steps to reproduce the bug**
1. Create a new solution
2. Add a new page
3. Create a ToggleButton on the second page
4. To the application resource dictionary add the following
```
        <Style TargetType="Button" x:Name="RevealFlatButton" BasedOn="{StaticResource ButtonRevealStyle}">

        </Style>
```
5. Set the toggle button on Page2 style to the style added to the style dictionary
6. Add a button to the first page to navigate to the second page.
7. Run without debugger attached, app will crash. Run with debugger and it won't.

Reproduction available at: https://github.com/knightmeister/DictionaryMismatchBasedOnCrash

**Expected behavior**
If the ToggleButton is on the first page and the style is applied to it, Visual Studio will display an unhandled exception message at run time saying:

> Cannot apply a Style with TargetType 'Windows.UI.Xaml.Controls.Button' to an object of type 'Windows.UI.Xaml.Controls.Primitives.ToggleButton'. [Line: 13 Position: 39]'

![image](https://user-images.githubusercontent.com/1528425/61628301-42288f80-acc5-11e9-9216-8faecf747bc7.png)

For the button on the second page, no unhandled exception message is shown and the application will run fine with a debugger attached. However when there is no debugger the app just silently dies.

**Version Info**
1903

NuGet package version: 
NA, Windows.UI.Xaml controls

**Additional context**
**Question** Is it possible to get a stack trace when a UWP app crashes to diagnose the issue, like how you could with Winforms? They just disappear when they crash.

**Comment by fabiant3** [comment]
Nothing special about Style from a markup point of view, moving to FX. First suspect is metadata (somehow it doesn’t think that Button is assignable from ToggleButton).
