### ISSUE TITLE
Question: Multiple views binding to the same source - is this a bad idea

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1088]
My app supports 3 different views of data, which the user can select. Essentially a grid, a list and details view.

The controls being used are:

Grid - ListView with horizontal wrap grid
List - ListView with (most likely) vertical wrap grid
Details - DataGrid from the community toolkit

These three controls will all bind to the same view model property and visibility will be controlled based on what the user has elected to see. My intent is to have all three controls wrapped within a grid, set to the same row.

1. Are resources consumed by the controls when their visibility is collapsed?
2. Would I be better off setting their `ItemsSource` to `null` when making them hidden?
3. Would it be better for performance / memory consumption to have a dedicated page for each view, and navigate the user to the page for their view?

I would prefer to avoid 3 if possible because it will cause navigation headaches for me.

**Comment by jevansaks** [comment]
Yes, controls consume resources when collapsed -- not as much as when visible, for example a ListView should avoid stamping out UIs for its items but it will still be listening to changes on the items source. I think you'd be fine having them collapsed and still listening to the ItemsSource, though from a perf perspective.

Better than visibility for this scenario is [x:Load](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-load-attribute), this is the scenario that it was designed for.

**Comment by Djohnnie** [comment]
If I understand the question correctly: I mostly make use of DataTemplateSelectors for this purpose. You could create three data templates containing one of the three controls each and write the selector to select the appropriate one depending on some flag or setting on your ViewModel.

**Comment by knightmeister** [comment]
Thanks for the info @jevansaks, exactly what I was after.
