### ISSUE TITLE
MUXC cannot be referenced in a .NET Core 3.0 projects

### ISSUE THREAD

**Issue by ocalvo** [microsoft/microsoft-ui-xaml#1089]
**Describe the bug**

Dotnet core project do not include the targets file in the native folder (by design) and the reference to the winmd is not created.

**Steps to reproduce the bug**

1. Create a new DotNet core project.
2. Add a NuGet reference to Micrsosoft.
3. Declare a variable of type Microsoft.UI.Xaml.Controls.WhatEver

**Expected behavior**
Project builds with only a warning

**Actual behavior**
Project fails to build.

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| 19H1 | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@ocalvo, Could you include more repro steps or a sample project? It's normal that .NET projects only include the "build" directory, but it sounds like .NET Core's build targets don't correctly reference the winmd which would be a .NET Core issue. Obviously we could work around it but it seems better to have .NET fix it.

**Comment by ocalvo** [comment]
This [issue](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1563) tracks updating the docs

**Comment by ocalvo** [comment]
Here a minimal .NET Core project that repro the issue: [Repro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3419410/Repro.zip)

The guidance for native winrt components is incorrect, this [issue](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1563) tracks updating the docs

**Comment by ocalvo** [comment]
> @ocalvo, Could you include more repro steps or a sample project? It's normal that .NET projects only include the "build" directory, but it sounds like .NET Core's build targets don't correctly reference the winmd which would be a .NET Core issue. Obviously we could work around it but it seems better to have .NET fix it.

This is not a problem with .NET Core, this behavior is by design, see this native [component](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/blob/master/Microsoft.Toolkit.Win32.UI.XamlApplication.Package/Microsoft.Toolkit.Win32.UI.XamlApplication.Package.csproj#L81-L96) that include the correct targets file.

**Comment by jevansaks** [comment]
@ocalvo I know we had an email thread about this, did you ever figure out what the appropriate fix is?
