### ISSUE TITLE
Proposal: Add Label to Button

### ISSUE THREAD

**Issue by adrientetar** [microsoft/microsoft-ui-xaml#1092]
# Proposal: Add Label to Button

I have a Button, with a KeyboardAccelerator and a Tooltip description, and I would like the framework to display the KeyboardAccelerator at the end of the tooltip for me, e.g. I would set the description to "Copy" and the tooltip would be "Copy (Ctrl+C)".

It seems this is possible today using AppBarButton by setting its Label property with the description. The problem of AppBarButton is it's meant for a specific use-case and can behave weirdly when not contained in an AppBar (#423).

Could we have this functionality as part of Button?

## Alternatives

I'm not specifically arguing for having a Label property, just for having a built-in way to show a description + KeyboardAccelerator in the tooltip.

## Scope

| Capability | Priority |
| :---------- | :------- |
| Set a Button description, displayed alongside KeyboardAccelerator in a tooltip | Must |

**Comment by YuliKl** [comment]
Hi @adrientetar, thank you for the suggestion. I believe you're asking for a specific case of the broader topic suggested in #389. Would you agree? If you do, I'll close your issue as a duplicate of the other.

**Comment by adrientetar** [comment]
@YuliKl Yes indeed, thanks.
