### ISSUE TITLE
CommandBar is not properly rendering compact AppBarButtons

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#1099]
**Describe the bug**
The `CommandBar` is not able to display both labeled and compact (not labeled) buttons in the same `CommandBar` instance.

**Steps to reproduce the bug**

1. Add the following code in a XAML page:
```xml
<CommandBar Background="Transparent" DefaultLabelPosition="Right">
    <AppBarButton
        Icon="OpenFile"
        IsCompact="True"
        Label="Button 1" />
    <AppBarButton Icon="Clear" Label="Button 2" />
</CommandBar>
```
2. Run the application
3. You'll see the following result:
![image](https://user-images.githubusercontent.com/20152272/61880943-1809e400-aef6-11e9-8b4a-b7336b127310.png)

**Expected behavior**
The first button should be an **icon only button** (`IsCompact=true`). We should not see the label.

*Note:* I've added the label to more easily highlight the issue. If the label is empty, the button is not properly rendered. We are seeing a not centered icon because the label's `TextBlock` is displayed with a width of 0px and not null margins.

Here is a screenshot of what is expected:
![image](https://user-images.githubusercontent.com/20152272/61881221-8babf100-aef6-11e9-866a-8013a255fdbf.png)

It has been generated using the following snippet:
```xml
<StackPanel Orientation="Horizontal">
    <AppBarButton
        Style="{StaticResource AppBarButtonRevealStyle}"
        Icon="OpenFile"
        IsCompact="True"
        Label="Button 1" />
    <CommandBar Background="Transparent" DefaultLabelPosition="Right">
        <AppBarButton Icon="Clear" Label="Button 2" />
    </CommandBar>
</StackPanel>
```

**Version Info**
The `CommandBar` control is part of the Windows API: `Windows.UI.Xaml.Controls`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Repro app**
[MuxCommandBar.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3431945/MuxCommandBar.zip)

**Comment by YuliKl** [comment]
@vgromfeld, please use AppBarButton's [LabelPosition](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.appbarbutton.labelposition#Windows_UI_Xaml_Controls_AppBarButton_LabelPosition) property instead of IsCompact.
