### ISSUE TITLE
2.0.181018003 causing crash in 1803 or lower

### ISSUE THREAD

**Issue by dpaulino** [Microsoft/microsoft-ui-xaml#11]
**Describe the bug**
Updating my UWP app to use the latest package (2.0.181018003) causes app crashes in all versions of Windows below 1809. Upon further inspection, the 2.0.181018003 package apparently requires 1809 or higher. 

**Steps to reproduce the bug**
1. Set your target version to 1803 or lower.
2. Go to your app's nuget package manager and update Microsoft.UI.Xaml to 2.0.181018003

**Expected behavior**
I thought that the packages were backwards compatible? So I was expecting that updating to 2.0.181018003 will not cause crashes in 1803 or lower. I could be wrong, so please correct me if I am!

**Screenshots**
![image](https://user-images.githubusercontent.com/7649589/47333915-ac7aa980-d639-11e8-9505-73c5475a3103.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.0.181018003

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [x] April 2018 Update (17134)
- [x] Fall Creators Update (16299)
- [x] Creators Update (15063)
- [x] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by licanhua** [comment]
Daniel,

Just like the screenshot said, it requires 1809 or higher as TargetPlatformVersion. Microsoft.UI.Xaml doesn’t support a lower version as target version.
My question is why do you set target version to 1803?
If you want the app to run on 1803 os and above, you just set min version to 1803. And target version to 1809. Then your app works on any version of Windows in the range from Minimum Version to Target Version

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Gh0stWalk3r** [comment]
The readme lists following OS as  supported, which none of the available NuGet packages fulfill:
> Supported OS versions
> Windows Insider Preview (17135+)
> April 2018 Update (17134)
> Fall Creators Update (16299)
> Creators Update (15063)
> Anniversary Update (14393)

**Comment by dpaulino** [comment]
After further investigation, I have identified the crash to be something else. It's still related to Microsoft.UI.XAML and versioning but it's not as I described originally. Closing issue.

**Comment by jevansaks** [comment]
Windows SDK 17763 (1809) is available to install and target your projects, you don't need 1809 to run (that's what min version is for).
