### ISSUE TITLE
VSM Setter quirk for raising exception has backwards logic

### ISSUE THREAD

**Issue by alwu-msft** [microsoft/microsoft-ui-xaml#1104]
VSM Setters have a behavior of raising an exception if Setter.Value is “unset value” only when a debugger is attached (combination of bogus “compat” reasons and fundamental disagreements about how permissive VSM Setters should be). For 19H1, as part of some x:Bind in VSM work, a quirk (AllowVisualStateTransitionOnUnsetSetterValue) was added that permits apps targeting 19H1 and beyond to have VSM Setters whose Setter.Value is “unset value”. Unfortunately, I think the quirk checking logic is backwards and is resulting in the exception being raised (when under the debugger) only for 19H1+, the exact opposite of our intent. @ryalanms could you double check this?

**Comment by anawishnoff** [comment]
You should see a fix for this bug in the upcoming WinUI 3/Project Reunion 0.8 Preview, which you can expect soon. 

FYI @Hppz who filed the original bug related to this at #1048.

**Comment by alwu-msft** [comment]
The fix is now available in Project Reunion 0.8 Preview.
