### ISSUE TITLE
Rendering issue with rounded corners

### ISSUE THREAD

**Issue by kmelmon** [microsoft/microsoft-ui-xaml#1106]
![ClippingBug](https://user-images.githubusercontent.com/33470154/61917562-9bc9cd80-af02-11e9-94d9-6f1e816b8d1f.png)
**Describe the bug**

When using certain sizes in combination with rounded corners, there's a rendering bug - the child of the element with rounded corners can have its corners "poke out" instead of being clipped to the rounded corner.

**Steps to reproduce the bug**

Create an app with this markup:
```
    <Canvas>
        <Grid BorderBrush="Black" BorderThickness="3" CornerRadius="10">
            <StackPanel
          Orientation="Horizontal"
          Background="Red"
          BorderThickness="0"
          BorderBrush="Green">
                <TextBlock Text="Hello World XAML!" />
                <TextBlock Text="TextBlock #2" VerticalAlignment="Center" />
            </StackPanel>
        </Grid>
    </Canvas>


```**Expected behavior**
<!-- Please provide a description of what you expected to happen-->
The red background should be clipped inside the rounded corners

**Version Info**
This is with inbox XAML on rs_onecore_dep 190706.  Issue likely repro's on builds back to RS2 or so, when we first added rounded corner clipping via dcomp.

<!-- Which device form factors did you see the issue on? Leave blank if you didn't try that device. -->
Desktop

**Comment by JJBrychell** [comment]
I am unable to repro this issue in any WINUI 3 releases since 1.1 or in System Xaml, so am going to close it as fixed (since obviously at some point it existed given the image included above).
