### ISSUE TITLE
Visual Studio 2019 16.1.1 Remote Debugging failed (UWP)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#1117]
When I try to debug Remote from Windows 1903 to WIndows 1709 or 1803 the App failed on start with the current VS 2019 16.1.1. Local Debugging worked on both machine with same Code.
This Error is thown:
&quot;Cannot deserialize XBF metadata type list as 'XamlControlsResources' was not found in namespace 'Microsoft.UI.Xaml.Controls'. [Line: 0 Position: 0]&quot;

When I enable native toolchain this Error is thrown:
  private object Activate_0_XamlControlsResources() { return new global::Microsoft.UI.Xaml.Controls.XamlControlsResources(); }

C:\Users\username\.nuget\packages\microsoft.toolkit.uwp.ui.controls\5.1.1\lib\uap10.0.16299\Microsoft.Toolkit.Uwp.UI.Controls.dll
	Die Datei oder Assembly &quot;System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e&quot; oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
C:\Users\username\.nuget\packages\microsoft.toolkit.uwp.ui.controls\5.1.1\lib\uap10.0.16299\Microsoft.Toolkit.Uwp.UI.Controls.dll
	Die Datei oder Assembly &quot;System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e&quot; oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.

I tried to reinstall Visual Studio 2019 but this did not help.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/595662/visual-studio-2019-1611-remote-debugging-failed-uw.html
VSTS ticketId: 905563_
_These are the original issue comments:_

Visual Studio Feedback System on 6/5/2019, 03:16 AM (55 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jevansaks** [comment]
@SvetBonev If the project works locally but not remotely that points at a VS issue. Is VS deploying all dependent framework packages? I've seen that fail in the past.

**Comment by danzil** [comment]
@SvetBonev Svet, any chance you guys could have a look at this issue so we can close on it?

**Comment by bpulliam** [comment]
If you still see this on a recent build, please open a new issue.

Thanks!
