### ISSUE TITLE
Hyperlink consumes hit-testing in an unexpected way

### ISSUE THREAD

**Issue by jwoo-msft** [microsoft/microsoft-ui-xaml#1125]
**Describe the bug**
Hyperlink's hit testing bounds seem strange when used as the first inline in a TextBlock with TextAlignment="Right"

**Steps to reproduce the bug**
When using this markup:

        <TextBlock TextAlignment="Right">
            <TextBlock.Inlines>
                <Hyperlink>
                    Test
                </Hyperlink>
                <Span>content</Span>
            </TextBlock.Inlines>
        </TextBlock>

The Hyperlink's hit-testing region will extend to the far left of the TextBlock, rather than being constrained to the bounds of the Hyperlink's rendered text.  This causes the hand cursor to appear potentially far to the left of the underlined text, and causes the link to get clicked when the cursor can be a long distance away from the text.

**Expected behavior**
Hit testing should be taking place where the Hyperlink is rendering text.

**Screenshots**

**Version Info**
WinUI NuGet package: N/A, just using OS XAML
OS version: 1903
Form factor: desktop

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by codendone** [comment]
I agree this could be better.  The same problem occurs for left-aligned text which ends in a hyperlink.

For non-wrapping text, this can be worked around by instead setting HorizontalAlignment on the TextBlock, so that it will only be the size of its text and get aligned by layout.  With just TextAlignment set, the TextBlock gets the default HorizontalAlignment="Stretch", so it is the full width of its layout container which can result in the hyperlink extending to the layout edge.

**Comment by Felix-Dev** [comment]
I'm also seeing this in the "About" dialog in the newest released Windows Terminal store version (0.3.2171.0). Checked the Terminal github and I didn't find any commit addressing this issue, so I presume it hasn't been fixed yet. Pinging @DHowett-MSFT for awareness of the described workaround by @codendone.

**Comment by JJBrychell** [comment]
The same hittesting is used for both caret positioning (on click) and hyperlink rollover.  In caret positioning, if you click beyond the end of a line (but still within the text control), the position is pulled back in to just past the end of the last element on the line.  If this element is a hyperlink, then the hyperlink will be treated as if it had been rolled over.  To fix this we will need to have the rollover hittesting additionally check whether the position is in the zero length stop just beyond the actual link.
