### ISSUE TITLE
Proposal: Documentation - Show derived classes in a consistent and simpler way

### ISSUE THREAD

**Issue by andreinitescu** [microsoft/microsoft-ui-xaml#1127]
# Proposal: Documentation - Show derived classes in a consistent and simpler way

The UWP documentation shows the derived classes at the end of the **Remarks** section:

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.buttonbase#remarks

Sometimes it's even harder to get to it, because it's after some subsections within the **Remarks**:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button#button-derived-classes

![image](https://user-images.githubusercontent.com/743918/62422301-daa51380-b6b8-11e9-9d30-7fae87f8ded9.png)

You always need to scroll down and look for it. This becomes very tedious when you just try quickly understand the class hierarchy.

### The WPF documentation does it better

In the documentation for WPF, there's a "Derived" list **displayed immediately after** "Inheritance" which makes a lot of sense:

https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.button?view=netframework-4.8

![image](https://user-images.githubusercontent.com/743918/62422307-117b2980-b6b9-11e9-86b9-cacfa786dd7d.png)

**Comment by mijacobs** [comment]
I've forwarded this on to the engineering team.

**Comment by mijacobs** [comment]
We're switching over to the .NET rendering pipeline, at which point the docs will have derived type info like the WPF docs do. This work is being tracked in our internal Azure Devops database.

**Comment by andreinitescu** [comment]
Hi @mijacobs

> I've forwarded this on to the engineering team.

How can I track the status on this? Thanks!
