### ISSUE TITLE
LightStyling Bug

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#1135]
**Describe the bug**
Normal Foreground is not correct once you move your pointer over the button for more than one time.

**Steps to reproduce the bug**
https://github.com/HppZ/LightStylingBug

**Comment by chrisglein** [comment]
Confirmed repro. Here's the essential markup in the repro above:

```
        <Button Width="200" Height="200" HorizontalAlignment="Center" VerticalAlignment="Center">
            <Button.Resources>
                <ResourceDictionary>
                    <SolidColorBrush x:Key="ButtonForeground" Color="Red"></SolidColorBrush>
                    <SolidColorBrush x:Key="ButtonForegroundPointerOver" Color="Teal"></SolidColorBrush>
                    <SolidColorBrush x:Key="ButtonForegroundPressed" Color="Aqua"></SolidColorBrush>
                    <SolidColorBrush x:Key="ButtonForegroundDisabled" Color="Green"></SolidColorBrush>
                </ResourceDictionary>
            </Button.Resources>
            <BitmapIcon UriSource="ms-appx:///Assets/StoreLogo.png"></BitmapIcon>
        </Button>
```

ButtonForeground is applied initially as the idle state, but never again. It shows Red the first time, then always after that Black. Note this seems true even if you set the Foreground property directly (it applies once, and never again).
