### ISSUE TITLE
Need workaround for removing Shadow from controls for project built with SDK version < 1903, but project deployed to devices running Windows 1903

### ISSUE THREAD

**Issue by Skynet094** [microsoft/microsoft-ui-xaml#1136]
Hi, I am trying to remove shadow from a CommandBar, that initially did not have any MenuFlyout for the OverflowButton (More-button), it had SecondaryCommands, however there was this issue of shadow  around the pop up, as the Popup is has a large corner radius (26px) it looks bad with shadow. So we don't want it.  Also, we have several content dialogs, from which we were able to remove the shadow from, using a rather ugly hack. 

I am aware of the ""IsDefaultShadowEnabled" property fix, however as the Target build version of our project is 1809, that property is not available to us.  Can anyone here please tell me a workaround for getting rid of Shadows from xaml controls when  we not building with 1903, but our app is to be deployed in devices running windows 1903 too (min target is 14393)?

At this point, a workaround for removing shadow from MenuFlyout given the context could be really, really helpful. 

The QA team associated with our project isn't accepting that it's a platform issue. Any help would be much appreciated. 

As to the question, why we are not using build target 1903, one of the reasons is,  it's because it causes a lot of unrelated unwanted issues.

**Comment by adrientetar** [comment]
Isn't that what [conditional XAML](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml) is for?

**Comment by Skynet094** [comment]
Conditional xaml is available for when the min version of the project is 15063. For our case it's slightly lower , 14393. 

But that's not the issue, I can use ApiInformaion to know whether the property exists before applying .

Our issue is our target build version is not 1903. Where that property is exposed. But our app will run on devices that run min version to 1903 (this is where the shadow issue comes up). 

The decision to make 1809 as target version was set a long time ago.

**Comment by adrientetar** [comment]
Then the only way would be to use reflection if that works, there's no magic here.

**Comment by Skynet094** [comment]
I feel like you are not getting the issue. Obviously not expecting any magic.

**Comment by jevansaks** [comment]
@Skynet094 can you elaborate on why you can't target 1903? Is there a limitation with your build environment?

**Comment by Skynet094** [comment]
We moved to using SDK  version 1903

**Comment by Skynet094** [comment]
> @Skynet094 can you elaborate on why you can't target 1903? Is there a limitation with your build environment?

We

**Comment by Skynet094** [comment]
> @Skynet094 can you elaborate on why you can't target 1903? Is there a limitation with your build environment?

The senior members in the team I work in were reluctant to move as after building with SDK 1903, some additional issues arose,  for instance,  the commandbar's menuflyout started having a weird background but only when deployed to 1809 devices, there were some other issues, but we fixed them and then the management gave us the go. Thanks all for reading!

**Comment by jevansaks** [comment]
Oh ok! I was going to say that if it's quirks related (such as you might have been seeing) you can have your target SDK be 1903 (to let you use new APIs) but still set your MaxTestedVersion to 1809 to make the runtime behavior the same as before.

**Comment by Skynet094** [comment]
Thank you! I will use that information.
