### ISSUE TITLE
TabView: Middle click on tab should close the tab.

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#1142]

**Comment by mailinglists35** [comment]
coming here from https://github.com/microsoft/terminal/issues/3335 and I find this issue the closest to the other one, specifically Microsoft Terminal gained ability to hide the close button on it's open tabs.

However when close button is hidden, middle click to close the tab is disabled as well.

Can we have both please? Does this need creation of a new separate issue?

**Comment by ojhad** [comment]
@mailinglists35 Please create a new issue for middle click being disabled when close button is hidden
