### ISSUE TITLE
Control border thickness checklist

### ISSUE THREAD

**Issue by kaiguo** [microsoft/microsoft-ui-xaml#1144]
Checklist to track border thickness changes.

* Basic Input
  - [x] Button
  - [x] Checkbox
  - [x] DropDownButton
  - [x] RadioButton
  - [x] SplitButton
  - [x] ToggleButton
  - [x] ToggleSplitButton
  - [x] ToggleSwitch

* Text Input
  - [x] AutoSuggestBox
  - [x] PasswordBox
  - [x] RichEditBox
  - [x] TextBox

* Pickers
  - [x] CalendarDatePicker
  - [x] ComboBox
    - [x] EditableComboBox
  - [x] ColorPicker
  - [x] DatePicker
  - [x] TimePicker

[Figma](https://www.figma.com/file/TFXoyPH1SaecP71JFAmADy/XAML-Controls---1px-strokes?node-id=1008%3A830)
[Feature proposal](https://github.com/microsoft/microsoft-ui-xaml/issues/835)

**Comment by mdtauk** [comment]
I am guessing the Figma file is an internal one.  Clicking the link just brings up a 404 error for me.

**Comment by savatia** [comment]
You should also add RichEditBox to the checklist

**Comment by savatia** [comment]
@mdtauk yes its internal

**Comment by kaiguo** [comment]
> You should also add RichEditBox to the checklist

Added

**Comment by mdtauk** [comment]
Could I suggest the Editable ComboBox template be fixed to remove this visual bug?

![image](https://user-images.githubusercontent.com/7389110/62828352-17529c80-bbdc-11e9-8543-f2b3be44202b.png)

**Comment by savatia** [comment]
> Could I suggest the Editable ComboBox template be fixed to remove this visual bug?
> 
> ![image](https://user-images.githubusercontent.com/7389110/62828352-17529c80-bbdc-11e9-8543-f2b3be44202b.png)

I noticed this and I believe I have fixed this:
![image](https://user-images.githubusercontent.com/11960777/62841816-1d3e9100-bc61-11e9-85b9-369882d9a110.png)
 Can you pull changes and confirm?

**Comment by mdtauk** [comment]
I had to grab your forked version of the repo, but it seems like, you have fixed it.

![image](https://user-images.githubusercontent.com/7389110/62851314-98de2380-bcdd-11e9-9457-6c7b13f587f0.png)
