### ISSUE TITLE
Hover animations don't work if FocusVisualKind is set to Reveal

### ISSUE THREAD

**Issue by stefankueng** [microsoft/microsoft-ui-xaml#1146]
**Describe the bug**
As soon as the FocusVisualKind property is set to FocusVisualKind.Reveal the mouse-over/hover animations on at least some controls stop working. I've confirmed this with the NavigationViewItem and the buttons in the TabView control. There might be other controls affected, but I haven't tested those.

**Steps to reproduce the bug**
Create a new project, best with the "Windows Template Studio (Universal Windows)" in Visual Studio, select "Navigation Pane" as project type and "MVVM light" as the design pattern, then add one or more pages.

Build the project and run it, and you'll see the mouse-over/hover animations on the navigation view items work properly.

Now change the method OnLaunched() in App.xaml.cs like this:
```
        protected override async void OnLaunched(LaunchActivatedEventArgs args)
        {
            if (!args.PrelaunchActivated)
            {
                await ActivationService.ActivateAsync(args);
            }
            FocusVisualKind = FocusVisualKind.Reveal;
        }

```
Build and run again, and you now see that the mouse-over/hover animations on the navigation view items don't show anymore.

**Expected behavior**
I would expect to have the animations still working since the docs for [FocusVisualKind](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.focusvisualkind?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Application.FocusVisualKind)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue) don't mention anything about such behavior. And I also would expect to have something that affects a focus visual to not interfere with simple mouse-over animations.

**Version Info**
Windows 10 1903, Desktop

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |

[App2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3487517/App2.zip)

**Comment by jevansaks** [comment]
@Austin-Lamb I assume you moved this back to controls because you believe it's not something to do with the reveal focus implementation? @codendone moving to Rendering for now.
