### ISSUE TITLE
TabView: Crash if TabViewItem.Icon is unset

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#1147]
Create a TabView and add a TabViewItem, with content but no Icon. TabView will crash on load.

TabViewItem's ControlTemplate includes:
<ContentPresenter x:Name="Icon"
    Content="{TemplateBinding Icon}"
    Foreground="{TemplateBinding Foreground}" />

I THINK the issue is that ContentPresenter automatically binds to ContentControl.Content unless something else is specified. So, if Icon is null, we are getting this "magic binding" behavior, so TabViewItem.Content is getting added to the ContentPresenter (even though it is already in the tree in its regular spot).

One solution might be to change TabViewItem.Icon to IconElementSource instead of IconElement. Then use IconSourceElement instead of ContentPresenter.

IconElementSource is probably a better choice than IconElement anyway.

**Comment by jevansaks** [comment]
@teap I think the changes you're working on address this, but please take a look.

**Comment by teaP** [comment]
Fixed in master.
