### ISSUE TITLE
MenuBarTests.BasicMouseInteractionTest is unreliable and fails often in test passes

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#115]
See here for an example failures: 
https://microsoft.visualstudio.com/WinUI/WinUI%20Team/_build/results?buildId=13485467
https://microsoft.visualstudio.com/WinUI/WinUI%20Team/_build/results?buildId=13485381
https://microsoft.visualstudio.com/WinUI/WinUI%20Team/_build/results?buildId=13484514
https://microsoft.visualstudio.com/WinUI/WinUI%20Team/_build/results?buildId=13486221

**Comment by chingucoding** [comment]
The new "HoveringBehaviorTest" seems to also be unreliable. Mentioning it here for tracking.
