### ISSUE TITLE
When Secondary items has too many elements, it could show up weird on a small screen device.

### ISSUE THREAD

**Issue by alanlai-ms** [microsoft/microsoft-ui-xaml#1152]
**Describe the bug**
Porting bug from https://office.visualstudio.com/OneNote/_workitems/edit/3546459
When Floatie is too long, the expected behavior is it opens up if there's no room.
In pre_release OS build 18956, we are noticing that is no longer the case.

**Steps to reproduce the bug**

1. install onenote
2. insert picture
3. right click picture near bottom of screen.

**Expected behavior**
Floatie should open UPwards, also notice the scroll bar in the secondaryCommandBar. 
This did not repro in 19H1

**Screenshots**
![image](https://user-images.githubusercontent.com/49052408/62814981-44faf100-bac9-11e9-842f-38be2f2c34c8.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by alanlai-ms** [comment]
Ok, after trying it again, I dont think it is a regression.
But say on your laptop with a smaller screen like Surface Pro4 or Surface Book,
 Set text scaling to 300%, and try right clicking on a picture in OneNote. (Or rather, in your own sample app, create a context menu with many secondary items (Ours had 10)

In this situation, I guess no matter the secondary menu opens up or down it still wont fit the screen.

My expected behavior from the control is the control should relocate the context menu a little bit so everything fits on screen. (e.g. Try to mimic File Explorer's behavior)

**Comment by jevansaks** [comment]
Looks like @llongley didn't reply here but he found that this is due to the fact that we don't have access to monitor APIs in UWP so this is a known limitation and not a regression. We can still use this for tracking but you should work around it (as it sounds like you plan to do) for now.
