### ISSUE TITLE
Question: Performance of XAML Island ?

### ISSUE THREAD

**Issue by fforjan** [microsoft/microsoft-ui-xaml#1157]
The typical use case is that we would like to reuse the markdown viewer… for example in our application, we have the equivalent of an error list in message windows 
![image](https://user-images.githubusercontent.com/601810/62874109-7942fd00-bcd5-11e9-941c-d011f7bfee62.png)

But we would like to use the markdown viewer for the description field.

What would be the performance impact (memory/CPU) to use such markdown viewer via XAML Island ?

**Comment by marb2000** [comment]
@fforjan, we have some early performance analysis done and we’ve found __the costs are on par with using XAML in a UWP application__.  

We looked at memory usage, CPU usage on startup, and  I/O disk. These three cases are broadly similar in UWP and XAML Islands.  There could be differences in the end-to-end performance depending on how many Islands are you using (our tests contained just one Island).
