### ISSUE TITLE
Install/Debug on ARM64

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#1177]
I'm trying to run/remote debug an app on an ARM64 device, but getting this. How do I add/install the package on the device? Shouldn't it be included in the app package?

> Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073CF3] Windows cannot install package [redacted]_2.0.100.0_arm64__[redacted] because this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.1" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or ARM64 processor architecture and minimum version 2.11906.6001.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.1" currently installed are: {}	[redacted]

**Comment by jevansaks** [comment]
Yes it should, and we've done manual testing on the package on arm64. Does it work if you create store packages and then side-load the appx?

**Comment by myokeeh** [comment]
To debug ARM or ARM64 on a remote machine, **Authentication Mode** needs to be **Universal (Unencrypted Protocol)** to deploy properly. This was not directly a problem with `Microsoft.UI.Xaml`
