### ISSUE TITLE
Regression: NavigationView in Minimal mode launches with its Pane open

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1186]
**Describe the bug**

When the app launches in a narrow window (causing its NavigationView to appear in Minimal display mode), NavigationView's pane shows as open. 

This behavior regressed between 2.1.181025003-prerelease (good) and 2.1.181217001-prerelease (bad).

**Steps to reproduce the bug**

1. Create a test app with this code snippet
```xaml
<mux:NavigationView>
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem Icon="Play" Content="Menu Item1" Tag="SamplePage1" />
        <mux:NavigationViewItem Icon="Save" Content="Menu Item2" Tag="SamplePage2" />
    </mux:NavigationView.MenuItems>
    <Frame x:Name="contentFrame"/>
</mux:NavigationView>
```
2. Launch the app and resize its window to the most narrow width.
3. Restart the app.

**Expected behavior**

On launch, the Pane should be closed.
![image](https://user-images.githubusercontent.com/13142665/63473616-04856680-c42b-11e9-80ad-d9a5bbd520f8.png)

**Screenshots**

On launch, the Pane is defaulting to being open.
![image](https://user-images.githubusercontent.com/13142665/63473696-42828a80-c42b-11e9-952e-cf4dcdbfe89b.png)

**Version Info**

NuGet package version: 

Starting with 2.1.181217001-prerelease, I see the same bad behavior through 2.2.190731001-prerelease 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@licanhua can you take a look and see if we can get a fix in for 2.2?
