### ISSUE TITLE
Xbox One virtual keyboard delete does not work initially in a textbox

### ISSUE THREAD

**Issue by RexfelisLOC** [microsoft/microsoft-ui-xaml#1190]
**Describe the bug**

This bug was reported in the MSDN Forums back in June 2019 and is still an  issue:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/40ccda10-dc50-45bd-b191-95a9fd35d95b/rs61903cuwp-xbox-one-virtual-keyboard-delete-issue?forum=wpdevelop

The delete key is not working when a user selects a textbox control.

**Steps to reproduce the bug**

1. Add a textbox to your xaml
2. Deploy to Xbox One
3. Select the textbox with the cursor
4. Type some text
5.  When you attempt to use X or press Delete on the keyboard it does not work
6.  Workaround is to move the cursor off the virtual keyboard and back on to the virtual keyboard, at which point delete starts working again

This bug was introduced by one of the spring XBox One updates

**Expected behavior**

Press the X key on the controller or Delete on the virtual keyboard and the last character is deleted from the textbox

**Screenshots**

N/A, but easy to reproduce

**Version Info**

Occurs on any UWP XAML from 16299 to 18362

NuGet package version: 
N/A

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)             | Yes   |
| October 2018 Update (17763)       | No   |
| April 2018 Update (17134)             | No   |
| Fall Creators Update (16299)         | No   |
| Creators Update (15063)               | No   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | No   |
| Xbox                      | Yes   |

**Additional context**

**Comment by YuliKl** [comment]
Hi @RexfelisLOC, this sounds like an Xbox bug rather than a Xaml controls bug. Have you tried providing feedback from the Xbox directly? https://support.xbox.com/en-US/xbox-one/console/xbox-insider-hub-report-a-problem

**Comment by RexfelisLOC** [comment]
No I have not reported it there yet.  Roy Li (in the link I provided for the MSDN forums) did say he had already reported it, but I'm not sure where to search to see it has been reported and he isn't answering any further inquiries on it.

**Comment by jevansaks** [comment]
Please file a feedback item from Xbox and share the link here -- we can help make sure it gets to the right team.
