### ISSUE TITLE
Proposal: Update Slider Hover colours to match similar controls

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1193]
# Proposal: Update Slider Hover colours to match similar controls

## Summary
Slider was not updated along with the other controls, to the same Hover and Pressed behaviour.

## Rationale
Hover colours have been updated for most controls which lightens the control on Hover, and darkens on Pressed states.  Slider does not match this behaviour.

## Scope

| Capability | Priority |
| :---------- | :------- |
| Slider Hover and Pressed colours should match the other controls | Should |

## Important Notes
![image](https://user-images.githubusercontent.com/22958680/62231877-bf18d080-b379-11e9-8e4c-a9d9c19aa409.png)
_Changes made to button hover_

![image](https://user-images.githubusercontent.com/7389110/63538068-0b85a500-c50f-11e9-9ed5-25aebf8e238f.png)
_Slider states not matching_

Ideally, we'd like to do this.
![image](https://user-images.githubusercontent.com/22958680/63615813-0d954580-c59b-11e9-8b13-76bed719e35f.png)

**Comment by chigy** [comment]
@mdtauk , thank you for opening the issue. As mentioned in issue #953, due to time constraints, I didn't want to introduce too many changes, but the ideal design solution is being discussed. Not final yet but added it to the proposal section.

**Comment by mdtauk** [comment]
Good to hear @chigy   Further to that, would the Thumb be the only part to have a Hover and Pressed state?  You can tap on any part of the control to change the value.

Fabric Web has the Track, Progress Track and Thumb changing states, but it goes from monochrome to accent, so maybe not the same use case.
![image](https://user-images.githubusercontent.com/7389110/63616335-40f9c380-c5df-11e9-8032-1e5982af490f.png)


Fast DNA does not display a Progress part
![image](https://user-images.githubusercontent.com/7389110/63616293-2e7f8a00-c5df-11e9-9ea1-e172c434a4a6.png)

----

For my own experimenting, I had both Thumb and Progress changing State.
![Sliders - 23-08-2019](https://user-images.githubusercontent.com/7389110/63616436-74d4e900-c5df-11e9-9415-577b8d088c6f.png)

**Comment by chigy** [comment]
@mdtauk , if you look closely, XAML control already changes color of the slider part today. What we don't do is to change the accent colored part. The current thinking is to change both when hovered to denote actionable meaning.

**Comment by mdtauk** [comment]
> @mdtauk , if you look closely, XAML control already changes color of the slider part today. What we don't do is to change the accent colored part. The current thinking is to change both when hovered to denote actionable meaning.

That is true, my apologies, the Track changes on Hover, along with the Thumb, but not the Progress part.

**Comment by chigy** [comment]
This is actually now fixed. Possibly with PR #1223
