### ISSUE TITLE
Proposal: Add Multiple style to one control

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/microsoft-ui-xaml#1194]
I think it is useful to add multiple styles to one control like HTML and CSS.

**Comment by michael-hawker** [comment]
@khoshroomahdi how would you envision this working with templates within styles or conflicting property values?  Would the list of styles applied to a control be ordered and be applied FIFO or LIFO?

**Comment by khoshroomahdi** [comment]
I prefer LIFO.

**Comment by mdtauk** [comment]
Other than moving closer to CSS and HTML, could you provide some example uses for such a feature?

**Comment by jevansaks** [comment]
Are you proposing that the Style property is actually a List and we combine the styles together? Some code samples + expected output would be helpful for understanding the suggestion.

**Comment by khoshroomahdi** [comment]
For example i have some styles for button, some for colors and some for size
I should to use both for one button
Style="{staticresource style1 style2}"

**Comment by mdtauk** [comment]
I get you now @khoshroomahdi  Having a style for a control, made up from a button colour, or a font size.  It can be done by making each element a StaticResource, and making a style from those Resources (this is how the default control templates work) - but you want the style to be made dynamically, just by applying a list/collection of styles.

**Comment by khoshroomahdi** [comment]
I want just applying a list of styles.

**Comment by adrientetar** [comment]
I don't know if that would play well with the fact that Styles are typed (TargetType=Class), in css you can write any rule in a class and apply to any element and rules that don't apply just get ignored.

**Comment by mdtauk** [comment]
**StyleOverride** seems like a neat solution/suggestion.

As for how it applies, and effects inheritence - perhaps it is like a class in CSS, where as the **Style** with its typing, would be like an ID in CSS.  Eitherway it should work like CSS does, as developers will find that familiar.

**Comment by Nirmal4G** [comment]
There's a `BasedOn` in XAML Style element, but the resource must be target typed either to a base class of the target type or the target type itself.

**Comment by Tirraon** [comment]
There is another Xaml framework, which already supports CSS-like styles - Avalonia.
Each ui element can has multiple classes in "Classes" field separated by space.
And each concrete style can target multiple classes with Or (css-like) selector:
https://github.com/AvaloniaUI/Avalonia/pull/2345/files#diff-acd57219d354b2ac1ad9989ae377db10R14

More information about styles in Avalonia docs:
http://avaloniaui.net/docs/styles/styles
And more about css-like selectors:
http://avaloniaui.net/docs/styles/selectors

Note, that there is no documentation for 'Or' selector for now.

Also Avalonia guys work on xaml AOT-compiling ([XamlIL](https://github.com/kekekeks/XamlIl/)), and  style selectors are already [parsed and compiled](https://github.com/AvaloniaUI/Avalonia/blob/e59de05c04542d1bf9afec3f961c3bc33a4e37f2/src/Markup/Avalonia.Markup.Xaml/XamlIl/CompilerExtensions/Transformers/AvaloniaXamlIlSelectorTransformer.cs). But they always should be typed for that case, as I know. So it works without additional time wasting in runtime.
