### ISSUE TITLE
Problem with NavView Behavior

### ISSUE THREAD

**Issue by sibille** [Microsoft/microsoft-ui-xaml#12]
We're working on a Behavior that allows to customize the NavViews Header from the selected page, using a DataTemplate. It's working fine in MVVM Basic, Mvvmlight, Caliburn.Micro and Prism, but
we're facing an issue in the NavViewHeaderBehaviour with CodeBehind.
X:Bind is not working in the DataTemplate when the HeaderContext is set to a Page.

We've prepared a repro solution: [App1.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2506011/App1.zip), with the following projects:

- App1_XBind_Page: This project shows the problem, binding seems to work fine, but value is not shown.
- App1_XBind_Helper: Possible Solution 1: Bind to a HelperClass
- App1_Binding: Possible Solution 2: Use Binding instead of xBind
- App1_ContentPresenter: This project shows what we suspect is the underlying problem, a `ContentPresenter` with `Content` bound to a page does not resolve bindings in `ContentTemplate `correctly, a ContentPresenter with content bound to another class does.

Tracking issue on our side is https://github.com/Microsoft/WindowsTemplateStudio/issues/2711

**Comment by crutkas** [comment]
Any eta for this / triaging it?

**Comment by licanhua** [comment]
Problem is because ShellPage changed DataContext to ShellPage, but DataTemplate is MainPage.
We didn't setup DataContext for NavView and it deducted it used ShellPage.DataContext, and finally get a cast error.

```
        public ShellPage()
        {
            InitializeComponent();
            DataContext = this;
            Initialize();
        }

        <DataTemplate x:DataType="views:MainPage">

            <!--Show current data-->
            <TextBlock Text="{x:Bind MyText, Mode=OneWay}" />
        </DataTemplate>
```

You may have two options:
1. Remove DataContext = this or replace it with MainPage instance;
2. set correct DataContext for NavView. eg:
```
                    if (headerFromPage != null)
                    {
                        AssociatedObject.Header = headerFromPage;
                    }
                    else
                    {
                        AssociatedObject.Header = DefaultHeader;
                    }
                    AssociatedObject.DataContext = AssociatedObject.Header;
```
