### ISSUE TITLE
TreeView not working as expected when expanding and collapsing

### ISSUE THREAD

**Issue by tasmid** [microsoft/microsoft-ui-xaml#1201]
**Describe the bug**
TreeView with multiple levels not working as expected.

**Steps to reproduce the bug**
1. Go to "A TreeView with ItemTemplateSelector" in "TreeView"
2. Move the "Personal Folder" inside "Work Documents"
3. Expand all tree to have the same as the image (Image step 3).

4. Now, the first time you collapse the "Work Documents" and then expand it you will see the expected behavior, that is to see the same in step 3. But if you do it again, the "Home Remodel Folder" will not have any children as you can see in the image (Image step 4).

**Expected behavior**
To always see the same as the image (Image step 3).

**Actual behavior**
That the "Home Remodel Folder" don't have any child and it cannot expand or collapse again.

**Screenshots**
(Image step 3)
![image](https://user-images.githubusercontent.com/12250876/57837866-ec66d100-77c3-11e9-9f67-35c60788019c.png)

(Image step 4)
![image](https://user-images.githubusercontent.com/12250876/57838173-7dd64300-77c4-11e9-9c34-35729b2128b0.png)

**Version Info**

Gallery version (found on Settings page): 
1.2.7.0

Windows 10 version: October 2018 Update (17763)

Device form factor: Desktop

**Additional context**

**Comment by YuliKl** [comment]
Issue still repros in Gallery version 1.2.8.0 on a recent insider build. Agree with @chingucoding that this is likely a controls issue, so moved to the other repo.

**Comment by chingucoding** [comment]
@YuliKl I already created an issue. See #1182 😅

**Comment by YuliKl** [comment]
Oh, thank you for pointing that out! I'll close this issue because no further app work should be required once #1182 is fixed.
