### ISSUE TITLE
Discussion: Should Visual Studio Toolbox and Xaml Controls Gallery Icons sync?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1204]
# Discussion: Should Visual Studio Toolbox and Xaml Controls Gallery Icons sync?

The Icons used for the Control listing, in the Xaml Controls Gallery, look outdated, and more from the Metro Era of design language, and not even MDL2.

Then you have the icons used by Visual Studio for it's toolbox listing of controls.

Shouldn't some effort be made to unify these things, so each control has a "cannonical" iconic representation that would aid in identifying each control?

![image](https://user-images.githubusercontent.com/7389110/63629256-0efd5700-c609-11e9-8c5a-ea266c9fed6c.png)

![image](https://user-images.githubusercontent.com/7389110/63629277-2b998f00-c609-11e9-800a-2e4b4abaca17.png)

**Comment by shaheedmalik** [comment]
Short Answer: Yes.

**Comment by mdtauk** [comment]
Visual Studio 2019 changed up the icon designs IIRC.  And maybe its just a case of updating to the new VS'19 versions.

But perhaps this should be a part of the #1185 Win UI Logo design project.  Come up with an icon template which can be used for both the VS Toolbox, and Controls Gallery apps?

**Comment by mdtauk** [comment]
Here is an idea paired down to the minimum.
![idea 12](https://user-images.githubusercontent.com/7389110/63828347-0f298980-c95e-11e9-9fa6-773d0681ce47.png)

**Comment by chigy** [comment]
> But perhaps this should be a part of the #1185 Win UI Logo design project. Come up with an icon template which can be used for both the VS Toolbox, and Controls Gallery apps?

@mdtauk , VS Toolbox icons are designed by VS design team so we have no direct control over those icons like we do with Controls Gallery. That said, good news is I am currently talking with them so if there's an idea, I don't mind sharing with them (though no promises what-so-ever made :)).

**Comment by mdtauk** [comment]
> > But perhaps this should be a part of the #1185 Win UI Logo design project. Come up with an icon template which can be used for both the VS Toolbox, and Controls Gallery apps?
> 
> @mdtauk , VS Toolbox icons are designed by VS design team so we have no direct control over those icons like we do with Controls Gallery. That said, good news is I am currently talking with them so if there's an idea, I don't mind sharing with them (though no promises what-so-ever made :) ).

The VS Team should probably allow the WinUI SDK team to handle the Icons, so as new controls are added to the framework, there is no reliance on the VS team pushing out an update.

Of course that does not mean both teams can't contribute to a joint figma/team so there is some alignment in style.

**Comment by jevansaks** [comment]
Many (or all) of the icons do come from us. I believe we took them from the gallery. Take a look here:

https://github.com/microsoft/microsoft-ui-xaml/tree/master/dev/Microsoft.UI.Xaml.Design/Icons

**Comment by chigy** [comment]
>The VS Team should probably allow the WinUI SDK team to handle the Icons, so as new controls are added to the framework, there is no reliance on the VS team pushing out an update.

@mdtauk , it is flattered that you think WinUI is the only platform :) but there are many that VS team supports and they do their best to match those icons inside their toolbox.

**Comment by mdtauk** [comment]
> > The VS Team should probably allow the WinUI SDK team to handle the Icons, so as new controls are added to the framework, there is no reliance on the VS team pushing out an update.
> 
> @mdtauk , it is flattered that you think WinUI is the only platform :) but there are many that VS team supports and they do their best to match those icons inside their toolbox.

@chigy  LOL, I did mean that the VS team should allow the WinUI SDK team to provide the toolbox items, and for those same icons to be used in the Gallery App, and for documentation and WinUI talk slides at Build, etc :)

**Comment by chigy** [comment]
@mdtauk , @jevansaks covered that question, it seems. But that said, I am starting a conversation with the VS design team so I'll keep your feedback in mind.
