### ISSUE TITLE
Proposal:Substition Textbox / Substitution String

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1206]
# Proposal: Substition Textbox / Substitution String

## Summary

Over at [Xaml Controls Gallery](https://github.com/microsoft/Xaml-Controls-Gallery) there is a component (ControlExample component) that is able to substitute text inside its text using substitution objects that are defined in the XAML and can be disabled/enabled at runtime. 
See [this file](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ButtonPage.xaml#L33-L40) on how it is used in XCG.
## Rationale

* This would make it easier to render condition based text
* That kind of feature is (somewhat) existent in other UI frameworks (for example embedding objects in React).
* Would make code cleaner by not relying on C# and string manipulation to have dynamic text

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal must enable embedding of values/text that change dynamically in text | Must |
| This proposal should make it easier to display text with dynamic values embedded | Should |
| This proposal should enable developers to not rely on C# code to have dynamic text | Could |

## Important Notes

See usage of a component that among other things also has this substitution feature [here](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ButtonPage.xaml#L33-L40).

Proposal for a new component:
```xml
<SubstitutionText>
    <SubstitutionText.Content>
This is some text.
My favorite color is $(color).
$(greeting)
    </SubstitutionText.Content>
    <SubstitutionText.Substitutions>
        <SubstitutionText.Substitution Key="color" Value="{x:Bind User.FavouriteColor}" />
        <SubstitutionText.Substitution Key="greeting" Value="Hello!" 
                                     IsEnabled="{x:Bind User.WantsToBeGreeted}" />          
    </SubstitutionText.Substitutions>
</SubstitutionText>
```

Proposal for addition to TextBlock:
```xml
<TextBlock Text="This is some text.\nMy favorite color is $(color).\n$(greeting)">
    <TextBlock.Substitutions>
        <TextBlock.Substitution Key="color" Value="{x:Bind User.FavouriteColor}" />
        <TextBlock.Substitution Key="greeting" Value="Hello!" 
                                     IsEnabled="{x:Bind User.WantsToBeGreeted}" />    
    </TextBlock.Substitutions>
</TextBlock>
```

## Open Questions

Should this be an addition to existing components or should this be a new component?

**Comment by mdtauk** [comment]
Is this similar to masking in a TextBox?
![image](https://user-images.githubusercontent.com/7389110/63636036-d63d9c00-c661-11e9-9e85-e6245367a212.png)
_Image is just illustrative_

**Comment by chingucoding** [comment]
No, masking regulates the way user can enter input and how it is formatted (as least as far as I am aware).

This proposal would achieve something like this: 
![proposal-substition-text](https://user-images.githubusercontent.com/16122379/63636231-f161d900-c66c-11e9-8a69-c1223295c078.gif)

by only using XAML markup. The original xaml source code is this (using an internal component):
```xml
<local:ControlExample.Options>
                <StackPanel>
                    <CheckBox x:Name="DisableButton1" Content="Disable button" />
                </StackPanel>
            </local:ControlExample.Options>
            <local:ControlExample.Xaml>
                <x:String>
                    &lt;Button Content="Button" Click="Button_Click" $(IsEnabled)/&gt;
                </x:String>
            </local:ControlExample.Xaml>
            <local:ControlExample.Substitutions>
                    <local:ControlExampleSubstitution Key="IsEnabled" IsEnabled="{x:Bind DisableButton1.IsChecked.Value, Mode=OneWay}"
                                                  Value= "IsEnabled=&quot;False&quot; "/>
            </local:ControlExample.Substitutions>
```

**Comment by mdtauk** [comment]
I see, and how would this work with localised strings?

**Comment by chingucoding** [comment]
If you use a resx file as described [here](https://stackoverflow.com/questions/1142802/how-to-use-localization-in-c-sharp) you could bind to the properties e.g. :
```xaml
<SubstitutionText>
    <SubstitutionText.Content>
$(greeting)
    </SubstitutionText.Content>
    <SubstitutionText.Substitutions>
        <SubstitutionText.Substitution Key="greeting" Value="{x:Bind Properties.strings.Hello}" />       
    </SubstitutionText.Substitutions>
</SubstitutionText>
```

**Comment by chrisglein** [comment]
I don't think a new component is the most general purpose solution for this. That doesn't scale to other controls that might have similar needs. I think this is more of a straightforward binding scenario. Where you want this:

```
<TextBlock Content="{x:Bind String.Format("This is some text.
My favorite color is {0}.
{1}", User.FavouriteColor, User.WantsToBeGreeted}"/>          
```

Which I believe doesn't work today (I tried at some point, haven't in awhile), but can pretty easy by defining your own `Format` wrapper. I'd rather us address the inability to do a `String.Format` in an x:Bind than invent a TextBlock-specific solution.

Do you want to supply some justification for a new component? Or do you think a binding solution would suffice?

**Comment by chingucoding** [comment]
Thanks @chrisglein for your input! In some simple cases, this formatter solution might be enough.

The idea of this component came from the XAML Controls Gallery, where this already is a custom component. The main advantage I see is that I can simply enable/disable substitutions or replacements. 

I am not quite sure if this would be possible at all or how convenient that would be if one would try to achieve that using formatters.

**Comment by SavoySchuler** [comment]
Unassigning myself as this is item does not fall under my current area of ownership. Tagging @ranjeshj for reassignment.
