### ISSUE TITLE
How to test changes in components

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1209]
I have been trying to work on #70 and made some changes and tried running the MUXControlsTestApp, however the Components do not seem to look like the default Fluent Design Components (e.g. in the XAML Controls Gallery). Is this intentionally ? Or am I missing something?

And what are the other test apps for (e.g. MUXControlsTestApp.TAEF)?

**Comment by chingucoding** [comment]
This is a normal button in the MUXControlsTestApp:
![muxcontrolsbutton](https://user-images.githubusercontent.com/16122379/63798001-83860d80-c909-11e9-80fa-094ea335cab3.gif)

This is a normal button when creating a new UWP App with WinUI:
![uwpcontrolsbutton](https://user-images.githubusercontent.com/16122379/63798088-ad3f3480-c909-11e9-8616-b98a4296ae4c.gif)

What would cause this change of styling when in both programs the WinUI is included? Sorry if am just overseeing something totally obvious here 😅

**Comment by Felix-Dev** [comment]
@chingucoding There have been recent changes in the default styling for many WInUI controls. See https://github.com/microsoft/microsoft-ui-xaml/issues/524. I assume the MUXControlsTestApp already uses a version of WinUI with those changes implemented whereas the WinUI version you use still has the previous default control styling.

**Comment by chingucoding** [comment]
@Felix-Dev I thought about that, however the other app is using the most recent version available on Nuget (2.1.190606001). 

So did those changes not get pushed to Nuget yet? 😅

**Comment by Felix-Dev** [comment]
The latest, WinUI 2.2 preview releases have corner radius related work included (and to my knowledge WinUI 2.1 doesn't include any of those style changes related to corner radii.). So while I haven't verified this, my guess is that the MUXControlsTestApp consumes the latest WinUI (2.2) preview releases, hence the difference in styling you are seeing (WinUI 2.2 preview vs WinUI 2.1).

**Comment by chingucoding** [comment]
Ah I see. @Felix-Dev Thank you for pointing that to me out.

 So WinUI 2.2 will bring quite some changes. Looking forward to it!
