### ISSUE TITLE
Full screen startup Image

### ISSUE THREAD

**Issue by jrahma** [microsoft/microsoft-ui-xaml#1214]
Hi,

It will be great if you add an option for a full screen image for the startup window instead of center image

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by jevansaks** [comment]
Thanks for the suggestion, but this is part of the modern app manifest and isn't owned by XAML. Could you file a Feedback Hub issue? I can help make sure it finds its way to the right owners.

**Comment by jrahma** [comment]
@jevansaks Done....


![XAMLStartup](https://user-images.githubusercontent.com/6236241/64132691-9fdeea00-cde2-11e9-9422-f45d9b31879a.png)

**Comment by jevansaks** [comment]
Can you go into that item and click "Share" to copy a link and then paste the link here?

**Comment by jrahma** [comment]
With Thanks

[https://aka.ms/AA5yxym](https://aka.ms/AA5yxym
)

**Comment by jevansaks** [comment]
Sorry for the delay, I've routed the feedback to the team that owns that area. Thanks!
