### ISSUE TITLE
Style not applied inside MenuFlyoutItem.Icon

### ISSUE THREAD

**Issue by jbrianceau** [microsoft/microsoft-ui-xaml#1217]
**Describe the bug**

I'd like to apply a style for all `SymbolIcon` elements of my app, but it seems that this is not working when a `SymbolIcon` is used in a `MenuFlyoutItem.Icon`.

**Steps to reproduce the bug**

Create a new XAML page using the following repro snippet:
```
<Page
    x:Class="SandboxCSharp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">

    <Page.Resources>
        <Style TargetType="SymbolIcon">
            <Setter Property="Foreground" Value="Red" />
        </Style>
    </Page.Resources>

    <Grid>
        <AppBarButton Label="AppBar">
            <AppBarButton.Flyout>
                <MenuFlyout>
                    <MenuFlyoutItem Text="MenuFlyoutItem">
                        <MenuFlyoutItem.Icon>
                            <SymbolIcon Symbol="Accept" />
                        </MenuFlyoutItem.Icon>
                    </MenuFlyoutItem>
                </MenuFlyout>
            </AppBarButton.Flyout>
            <AppBarButton.Icon>
                <SymbolIcon Symbol="Accept" />
            </AppBarButton.Icon>
        </AppBarButton>
    </Grid>
</Page>
```

**Screenshot**
![image](https://user-images.githubusercontent.com/5746498/63694716-5a855000-c817-11e9-8d58-ab31716c6343.png)

**Expected behavior**
I would expect both `SymbolIcon` elements to be red, but the `MenuFlyoutItem` one isn't.

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@chrisglein This is the problem we've seen where resource lookups inside popups don't find resources in the owning tree. (this may be a dupe)

**Comment by Jay-o-Way** [comment]
Is this still an issue?

**Comment by ranjeshj** [comment]
This is because the flyout is in the popup tree instead of where it is defined. You can define the resource in the Menuflyout item instead like so.

```
<AppBarButton Label="AppBar">
    <AppBarButton.Flyout>
        <MenuFlyout>
            <MenuFlyoutItem Text="MenuFlyoutItem">
                <MenuFlyoutItem.Resources>
                    <Style TargetType="SymbolIcon">
                        <Setter Property="Foreground" Value="Red" />
                    </Style>
                </MenuFlyoutItem.Resources>
                <MenuFlyoutItem.Icon>
                    <SymbolIcon Symbol="Accept" />
                </MenuFlyoutItem.Icon>
            </MenuFlyoutItem>
        </MenuFlyout>
    </AppBarButton.Flyout>
    <AppBarButton.Icon>
        <SymbolIcon Symbol="Accept" />
    </AppBarButton.Icon>
</AppBarButton>
```
