### ISSUE TITLE
PasswordBox "show text button" missing after losing/regaining focus

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1224]
**Describe the bug**

After the PasswordBox loses focus (and some text was entered) and regains the focus the button that can be used to show the plain text is missing.
**Steps to reproduce the bug**

1. Enter text in PasswordBox
2. Click on other component in app so PasswordBox loses focus
3. Click in PasswordBox so it regains the focus

**Expected behavior**

The "show text" button is visible
**Screenshots**

![passwordbox-revealbug](https://user-images.githubusercontent.com/16122379/63758387-fb2d4b80-c8bb-11e9-86ad-95d18b186b4d.gif)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18956)              | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |

**Additional context**

The "RevealButton" is still in the visual tree, however its visibility mode is set to "Collapsed".
Fixes [this issue over at XCG](https://github.com/microsoft/Xaml-Controls-Gallery/issues/156).

**Comment by mrlacey** [comment]
I believe what you are seeing is the correct behavior and is also seen elsewhere.

The reason to prevent access to a previously entered password is for security. Once focus is lost from the control, removing the ability to see what was entered means that if a value is entered on a form and and the machine is then left unattended another person cannot see what was entered.

**Comment by chingucoding** [comment]
Oh that makes sense. Since this apparently is the default behavior on other platforms too, I agree this makes sense.
@mrlacey Thanks for your response!
