### ISSUE TITLE
AppBarToggleButton does not respect contrast requirements when IsChecked = true

### ISSUE THREAD

**Issue by dan-jac** [microsoft/microsoft-ui-xaml#1228]
The appearance of an AppBarToggleButton is fine when it's not enabled:
![image](https://user-images.githubusercontent.com/50617707/63868411-c0f4a480-c9b6-11e9-82ed-3305fb03b8a4.png)

But when toggled on, the background gets colored in but the text and symbol remain black. This does not meet contrast ratio requirements:
![image](https://user-images.githubusercontent.com/50617707/63868487-e4b7ea80-c9b6-11e9-8286-feaea3968e58.png)

This behaviour is also inconsistent with other controls.

For example, with the *extremely* similar ToggleButton...
![image](https://user-images.githubusercontent.com/50617707/63868559-04e7a980-c9b7-11e9-8a53-99199dfbce51.png)

The text and symbols on the button are changed to white when the button is toggled on:
![image](https://user-images.githubusercontent.com/50617707/63868601-15981f80-c9b7-11e9-82ee-d1a6bd177265.png)

**Conclusion**
I propose that the AppBarToggleButton should be modified to behave the same way as a ToggleButton: **the text and symbol on the button should be white when the button is toggled on.**

**Comment by mdtauk** [comment]
Beyond the immediate scope of this issue, but what if there was a Xaml Brush which can automatically determine a White or Black colour, based on the background the element is above?

**Comment by chigy** [comment]
@dan-jac , as @mdtauk mentions, this is not as simple as making the text always white because some accent colors are lighter like yellow. That said, thanks for raising the issue.

**Comment by mdtauk** [comment]
Thinking off the top of my head...

```xaml
<ContrastBrush x:Key="ButtonContrastBrush" 
      LighterColor="#FFF2F2F2" 
      DarkerColor="#FF1F1F1F" 
      ComparisonColor="{ThemeResource SystemAccentBackgroundColor}"/>

<Button Content="Button text" 
      Foreground="{StaticResource ButtonContrastBrush}" 
      Background="{ThemeResource SystemAccentBackgroundColor}" />
```

## **Contrast Brush**

**LighterColor**
Specifies the colour to be used when the background is of a Dark shade.

**DarkerColor**
Specifies the colour to be used when the background is of a Light shade.

**ComparisonColor**
Specifies the colour resource to determine what contrast is needed.
_(Ideally this would not be needed as the rendering would identify the colour behind the element.)_

**Comment by dan-jac** [comment]
> @dan-jac , as @mdtauk mentions, this is not as simple as making the text always white because some accent colors are lighter like yellow. That said, thanks for raising the issue.

@chigy, Even if it's not quite as simple as that, can the existing logic used for ToggleButton simply be copied and used for AppBarToggleButton? This would then be consistent and would be a safe, tried-and-tested implementation.

**Comment by mdtauk** [comment]
AFAIK There is no logic, just White Text on the Accent colour button

**Comment by chingucoding** [comment]
There are different solutions we could use to fix this:
1.Add template settings to the AppBarToggleButton and do the calculations for that in there. That however won't be possible until WinUI 3.
2. Create a converter that takes the system accent color and returns the appropriate foreground color.

@ranjeshj What are your thoughts?

**Comment by ranjeshj** [comment]
@chigy as FYI. Is this specific to this one brush or a more general issue ?

**Comment by chigy** [comment]
This is a general problem of accent color. To handle accent color correctly, we need to not only figure this out for controls but sort of algorithm should be available for general usage, thus this has been an ask to shell team that has not been prioritized.
