### ISSUE TITLE
Controls on MediaPlayerElement MTC Volume flyout are not vertically aligned

### ISSUE THREAD

**Issue by dan-jac** [microsoft/microsoft-ui-xaml#1229]
Here's the volume flyout from the Media Transport Controls of the MediaPlayerElement:
![image](https://user-images.githubusercontent.com/50617707/63869751-f8645080-c9b8-11e9-9320-c61e7c224b55.png)

The mute button and the volume slider are not vertically aligned. Ideally they should be.
This can be illustrated by drawing a line from the slider to the left – it passes through the mute button below its center:
![image](https://user-images.githubusercontent.com/50617707/63869930-44af9080-c9b9-11e9-9423-70c0a9034822.png)

Also, when hovering the mute button, its highlight box is clipped at the bottom:
![image](https://user-images.githubusercontent.com/50617707/63869981-5c871480-c9b9-11e9-9abc-455db764d89b.png)

**Comment by jevansaks** [comment]
Good eye @dan-jac! @kaiguo is this template in WinUI now?

**Comment by kaiguo** [comment]
Yes, should be in WinUI now, I'll fix the alignment.
