### ISSUE TITLE
Tooltip of MediaPlayerElement MTC Volume button incorrectly says “Mute“

### ISSUE THREAD

**Issue by dan-jac** [microsoft/microsoft-ui-xaml#1230]
The button to the lower-left of the Media Transport Controls of the MediaPlayerElement invokes the volume flyout. Its tooltip should be something like “Volume”. Instead, its tooltip is “Mute”:

![image](https://user-images.githubusercontent.com/50617707/63870110-9eb05600-c9b9-11e9-89d2-a749ac8a0cb0.png)

**Comment by jevansaks** [comment]
Looks like the tooltip might be getting set from code, so we can't fix this until 3.0.

**Comment by dan-jac** [comment]
Just to ensure I understand... what's the logical connection between it being set from code, and needing to wait for version 3.0?

Is there... a policy that there must be no code changes to versions 2.X?

**Comment by jevansaks** [comment]
No, not policy. WinUI 2.x is built as an add-on library so we can only override styles for platform controls in WinUI. In WinUI 3.0 we'll bring the full XAML framework with us in which case we can change code and other platform code too.

**Comment by dan-jac** [comment]
Interesting. It sounds like this GitHub repo is therefore not the right place to log this bug. Presumably this bug should be re-assigned to somewhere within the platform/OS-level.

@jevansaks, do you know who should take such a bug?

**Comment by jevansaks** [comment]
This is the right place to file that bug! We'll fix it in WinUI 3.0.
