### ISSUE TITLE
TreeView SelectedItems is always zero if SelectionMode is SingleItem

### ISSUE THREAD

**Issue by jverral** [microsoft/microsoft-ui-xaml#124]
If I have a TreeView, if it's set to SingleItem for it's selection mode, than it's SelectedItems is always zero, even when I clearly have something selected.

**Comment by limefrogyank** [comment]
Yes, and you can't even manually add nodes to the SelectedItems collection.  It is always empty.  (You seem to be able to manually add them when SelectionMode = Multiple )

**Comment by jevansaks** [comment]
@kaiguo can you take a look at this when you're done with 19H1 bugs?

**Comment by kaiguo** [comment]
@jevansaks I saw there's a related issue #197. Should we just add a SelectedNode property to be consistent with ListView?

**Comment by kaiguo** [comment]
Yeah, I'll add SelectedItem and SelectedItems too.

**Comment by predavid** [comment]
We'd need SelectedItem as well as SelectedNode. @kaiguo - I believe you are in the process of adding both.

**Comment by predavid** [comment]
Great Progress! Thanks @kaiguo

**Comment by GrandArth** [comment]
May i ask how can i apply the new version to a uwp project? It seems this problem still exist in UWP (6.2.12)

**Comment by StephenLPeters** [comment]
Download and import our Nuget package into your project! We have instructions here: https://github.com/microsoft/microsoft-ui-xaml#using-winui
