### ISSUE TITLE
Discussion: NavigationView Back Button and Windows Tablet Mode

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#1243]
The NavigationView back button and the back button that appears when Windows is set to "Tablet mode" seem to need some functional reconciliation.
![image](https://user-images.githubusercontent.com/3663297/63998491-182d6e80-cab6-11e9-864d-260abe9e73a6.png)

For example, the behavior I'm seeing in the Windows Settings app is the in-app back button is hidden when in tablet mode. Shouldn't the NavigationView control also behave in the same way by default?

The Windows back button on the task bar also functions as I would expect: navigating back to previous pages in the app. Currently, apps I have using NavigationView don't seem to respond as expected in Tablet mode--not navigating back to past pages. It goes to the Start Screen or last app instead.

**Comment by mdtauk** [comment]
Tablet Mode has a lot of QoL changes that should be added, but the Hardware Back Button is very useful, and consistency with hiding in app ones, would be welcome.

**Comment by jevansaks** [comment]
> Currently, apps I have using NavigationView don't seem to respond as expected in Tablet mode--not navigating back to past pages. It goes to the Start Screen or last app instead.

I don't know what the future of the back button is in Windows but this sounds like a bug report for NavigationView's handling of the system back button. Would you like me to convert this issue into a bug for that?

**Comment by myokeeh** [comment]
Sure. I wasn't sure if I needed to do more plumbing for the system back button to be handled by the apps a certain way. But again, my expectation, at least, is it gets handled automatically when in tablet mode.

________________________________

**Comment by chingucoding** [comment]
It seems like that the [UIViewSettings.UserInteractionMode](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.ViewManagement.UIViewSettings?redirectedfrom=MSDN&view=winrt-18362#Windows_UI_ViewManagement_UIViewSettings_UserInteractionMode) is our best bet to detect whether we are in tablet mode or not. 

So if that's a suitable API to use here, I would like to fix this issue. 

So to clarify, in Tablet mode, we hide the BackButton. Should we ignore the developers choice there or just switch if no choice was taken? 
We won't need to listen to the [NavigationManager.BackRequested](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.systemnavigationmanager.backrequested?view=winrt-18362) event right? Or should we listen to the event and just forward it?
