### ISSUE TITLE
TabView crashed on second Loaded event

### ISSUE THREAD

**Issue by eugenegff** [microsoft/microsoft-ui-xaml#1245]
**Describe the bug**
TabView crashed on second Loaded event if databound, duplicates count of tab items if not databound.

**Steps to reproduce the bug**

[TabViewCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3559853/TabViewCrash.zip)
1. Unzip, build and run attached TabViewCrash project
2. Click on 'Navigate Forward from MainPage to TestPage' button.
There would be databound TabView with "Tab 1" and "Tab 2" tabs,
and another not databound one with "Tab 11" and "Tab 12" tabs.
Note that width of tabs is not equal - separate issue.
3. Click on 'Navigate Backward from TestPage to MainPage' button.
4. Click on 'Navigate Forward from MainPage to TestPage' button again
Crash in TabView::OnListViewLoaded for databound TabView.
If first databound TabView would be commented out - there would be no crash, but tab count of second TabView would be duplicated.

**Expected behavior**
Results of second navigation to TestPage results should be the same as results of first navigation, i.e.
there should be databound TabView with "Tab 1" and "Tab 2" tabs,
and another not databound one with "Tab 11" and "Tab 12" tabs.

**Screenshots**
![TabViewCrashScreenshot](https://user-images.githubusercontent.com/34012295/64019933-1658bf00-cb39-11e9-9fae-d26c296401f5.jpg)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190822001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Note, that page with TabView had NavigationCacheMode=Required, that caused unloading and reloading without destruction.

**Comment by eugenegff** [comment]
Note, that Loaded event could occur several times. I suspect, that OnApplyTemplate could occur several times too.

**Comment by MuziburRahman** [comment]
Faced the same problem. The `TabItems` Collection seems to behave weirdly. `TabItems.Clear()` generates error : *Attempted to read or write protected memory*. Any update on this issue?
