### ISSUE TITLE
Test TabViewTests.KeyboardTest is unreliable

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#1251]

**Comment by kmahone** [comment]
Unclear what is happening here.

1. It is passing most of the time.
2. It is failing specifically on RS2
3. We are hitting a crash in Windows.UI.Xaml.dll
4. I have not been able to reproduce the crash on a local RS2 VM.

**Comment by jevansaks** [comment]
> 3\. We are hitting a crash in Windows.UI.Xaml.dll

I thought we were able to get crash dumps back from Helix -- is that possible here?

**Comment by kmahone** [comment]
@jevansaks it should be possible as it is something that Helix apparently supports. But I haven't seen it work. It seems like that will be the only way to resolve this as I have not been able to reproduce the issue locally.

**Comment by kmahone** [comment]
I have created PR **Collect crash dumps from Helix test passes #1276** to help investigate this issue. Collecting crash dumps from Helix has been something we have wanted to do for some time.

**Comment by kmahone** [comment]
Fixed as part of #1276
