### ISSUE TITLE
WebView prevents app exit when explorer.exe is not running

### ISSUE THREAD

**Issue by verelpode** [microsoft/microsoft-ui-xaml#1253]
Hello, [WebView](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview) is in the `Windows.UI.Xaml.Controls` namespace and this suggests that WebView issues can be posted to this microsoft-ui-xaml repo, but on the other hand, I don't see any WebView issues in this repo.  Can I post this WebView bug to this repo?

`Windows.UI.Xaml.Controls.WebView` has a wonderful option `WebViewExecutionMode.SeparateProcess` but it malfunctions when Windows Explorer (explorer.exe) is not running.  (I mean "explorer.exe" not "iexplore.exe".)

Firstly, create a WebView instance like this:
```
var myWebView = new Windows.UI.Xaml.Controls.WebView(WebViewExecutionMode.SeparateProcess);
testGridElement.Children.Add(myWebView);
...
myWebView.Navigate(new Uri("http://www.example.com"));
```

Either before or after creating the WebView instance at runtime, terminate explorer.exe.  For debugging purposes, you don't have to setup a real environment where explorer.exe does not run.  Instead you can simply perform tests by using this command to terminate explorer.exe:
```
taskkill /IM explorer.exe /F
```

Next, try to click the "X" to close/exit the UWP app that is using WebView.  Clicking the "X" does nothing.  The app refuses to close.  The associated "WWAHost.exe" process also remains running.  Thus, although UWP WebView does operate without explorer.exe, it malfunctions when you try to close/exit the app that is using WebView.

Re the order/sequence, I tested terminating explorer.exe before and after creating the WebView instance at runtime, and it seemed to make no difference.  Either way, the app failed to exit when clicking the "X" when explorer.exe was not running, regardless of when explorer.exe was terminated.

The bug is more severe when using the WPF version of WebView (`Microsoft.Toolkit.Wpf.UI.Controls.WebView`).  WPF WebView immediately **crashes** the whole app whenever explorer.exe is not running, whereas UWP WebView initially succeeds but then fails when you try to close/exit the app.  For the WPF version, I've already posted a report the Microsoft.Toolkit.Win32 repo.

Reasons why explorer.exe is not necessarily running include:
* Remote Desktop Services, potentially, depending on configuration.
* Computers configured to operate in a kiosk mode.  Multiple kiosk methods exist, as follows.
* The ["Client-EmbeddedShellLauncher"](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/shell-launcher) feature in Windows. 
* The registry key `Software\Microsoft\Windows NT\CurrentVersion\Winlogon` with `Shell` value configured, in order to launch a different .exe instead of explorer.exe. 
* The [kiosk / assigned access mode](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app) feature that is configured via Start menu > Settings > Accounts.

Version:  I tested with a UWP app with the "Target Version" and "Min version" properties set to Windows 10 version 1903.

**Comment by jevansaks** [comment]
Yes, we own WebView. Thanks for the report! @Austin-Lamb ?

**Comment by verelpode** [comment]
@jevansaks
Great.  The current version of the impressive `WebViewExecutionMode.SeparateProcess` option is sadly _completely unusable_ in our environment because of these 2 problems:
1. The aforementioned bug.  We produce kiosks thus explorer.exe does not run.  Thus from our point of view, when a WebView fails because explorer.exe isn't running, it's a _major problem_ for us.
2. Access to use essential temporary/session cookies is lost when using `WebViewExecutionMode.SeparateProcess`, whereas not lost when using `WebViewExecutionMode.SeparateThread`.

Should I open an issue here describing the cookie problem?  I ask because I've already opened a cookie issue in the repo for WebView-for-WPF, thus I don't know whether that's sufficient to also cover the equivalent bug in WebView-for-UWP.   The preexisting issue was written from the perspective of using `Microsoft.Toolkit.Wpf.UI.Controls.WebView` but that's not the same as `Windows.UI.Xaml.Controls.WebView` -- very similar but different.   I could write up the equivalent issue specifically from the perspective of using `Windows.UI.Xaml.Controls.WebView` -- should I do that and open it in this "microsoft-ui-xaml" repo?  

Thanks for your advice!

**Comment by Austin-Lamb** [comment]
@verelpode - unfortunately this is a requirement of WebView's SeparateProcess mode, as some functionality for how the process management works is in explorer.exe.  This will be a requirement for the forseeable future.

I wasn't aware of a kiosk mode where Explorer doesn't run.  Could you clarify how you configure Windows to get in this state, so we can understand your scenario better?

For the cookie problem, please open a separate Issue for that.  It may or may not be the same as the WebView-for-WPF bug so I'd rather track it to make sure we don't lose something or mistakenly assume it's a duplicate when it's not.

**Comment by verelpode** [comment]
@Austin-Lamb 
> I wasn't aware of a kiosk mode where Explorer doesn't run. 

Completely understandable, considering that it's impossible for anybody to know and memorize all details in a system as large and complex as Windows.

> Could you clarify how you configure Windows to get in this state, so we can understand your scenario better?

In Windows 10 Pro or Enterprise, latest version (for example version 1903), click Start -> Settings -> Accounts -> Family & other users -> Set up a kiosk (Assigned access).

Note "Family & other users" only appears when signed in with an admin account.  It completely disappears when signed in with an account of type "Standard User".

Click "Set up a kiosk (Assigned access)" and it guides you through the steps to create a new user account and choose a single UWP app to run in that account.  This particular kiosk mode only supports UWP apps, not WPF etc.  For example, choose "Paint 3D" or any other built-in UWP app, and then sign into the new kiosk account you created, and you'll see that only "Paint 3D" runs.  No taskbar at the bottom of the screen.  No explorer.exe.  Here is a link to the ["Set up a single-app kiosk (Assigned Access)" documentation](https://docs.microsoft.com/en-us/windows/configuration/kiosk-single-app).

Windows supports multiple kiosk-style modes.  Another one is the ["Client-EmbeddedShellLauncher"](https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/shell-launcher) feature in Windows 10 Enterprise (maybe also unofficially supported in Pro, but I'd also to check this detail).  "Client-EmbeddedShellLauncher" launches your own program **instead of** the standard shell; instead of explorer.exe.  Thus explorer.exe does not run when "Client-EmbeddedShellLauncher" is enabled.

"Client-EmbeddedShellLauncher" launches a WPF, WinForms, or Win32 app.  It does not directly support launching of a UWP app, but a UWP app can still be launched indirectly.  "Client-EmbeddedShellLauncher" first launches a WPF .EXE and this program subsequently launches a UWP app containing WebView.  For example, the WPF program in a ["Desktop Bridge"](https://developer.microsoft.com/en-us/windows/bridges/desktop) package can launch the UWP app in the same package.  Alternatively, in the case of WebView-for-WPF and XAML Islands, simply a WPF app alone can use WebView, without any UWP app required.  (And in the case of WebView2 beta, even a Win32 app can use WebView2.)

Both of those kiosk modes result in the configured app running fullscreen with no taskbar at the bottom of the screen, and no explorer.exe.  The Alt+Tab hotkey is usable if multiple windows exist, but it doesn't allow switching to Explorer -- Explorer is not running. 

Another scenario is RemoteApp (part of Remote Desktop Services), but I'm much more familiar with kiosk modes.

Does that answer your question sufficiently?  If not, I'd be happy to provide more details.

> unfortunately this is a requirement of WebView's SeparateProcess mode, as some functionality for how the process management works is in explorer.exe. This will be a requirement for the forseeable future.

Until a better solution is released, would it be possible to work around the problem by making the kiosk program do the same thing as whatever explorer.exe does for the process management for WebView?  I realize that a much easier workaround is to use `WebViewExecutionMode.SeparateThread` but this is only possible for fully-UWP apps.  In the case of a WPF app using WebView-for-WPF, the only supported mode is separate-process.

> For the cookie problem, please open a separate Issue for that. 

Will do, very soon.  When I say temporary/session cookies, I mean those cookies that don't have any expiration date specified, or those marked with the special HTTP cookie flag called "HTTP Only".  According to the rules of WinINet.dll used by WebView, temporary/session cookies are only stored in the RAM of the calling process, not on disk, thus an app loses access to these cookies when using WebView's SeparateProcess mode because the cookies are stored in the RAM of the separate web process.  This cookie loss makes it impossible to use some websites in conjunction with requirement to use `HttpClient`.  For example in order to use `HttpClient` to download a PDF to display in the app's own PDF viewer component outside of `WebView`.  Various websites only authorize the PDF download when the session cookies are present.  I will explain this properly in the separate issue.  Thanks!

**Comment by Austin-Lamb** [comment]
Thanks for providing so many details!  I'm going to go on vacation for a week very shortly, so I just wanted to let you know I plan to get back to this when I'm back in the office, so I don't suddenly go dark mysteriously.  I'll get back to you with a more thorough response next week :)

**Comment by verelpode** [comment]
@Austin-Lamb -- That was considerate (to let me know about your holiday), thanks.  By coincidence, I also have an upcoming holiday -- I'll be away all of next week.  Here are the links to the 2 cookie issues I opened today.  The first issue is a bug report re compatibility between WebView, HttpClient, HttpBaseProtocolFilter.  The second is a proposal for cookie methods in WebView independent of HttpClient and HttpBaseProtocolFilter.

* [WebView stops sharing temp cookies with HttpClient and HttpBaseProtocolFilter when mode is SeparateProcess #1297](https://github.com/microsoft/microsoft-ui-xaml/issues/1297)
* [Proposal: Provide access to cookies in WebView #1298](https://github.com/microsoft/microsoft-ui-xaml/issues/1298)

**Comment by Austin-Lamb** [comment]
At this time, we are not planning to further invest in new features or major bug fixes for the EdgeHTML-based WebView.  Unfortunately, what you've discovered is a large amount of work to fix, as the underlying technology used to host EdgeHTML across processes does take a dependency on explorer.exe in ways that are very hard to untangle.

@adambarlow is driving our future WebView efforts to use the Chromium-based engine that Edge is moving to.  Adam, can you make sure we capture @verelpode's scenario for WebView?

I think there's no good way to use SeparateProcess for your scenario today.  @verelpode - Would it be possible for you to use in-process WebView?  Why do you need it in a separate process when the machine is as locked-down as a kiosk?

**Comment by verelpode** [comment]
@Austin-Lamb
> Why do you need it in a separate process when the machine is as locked-down as a kiosk?

Although we would be willing to use `WebViewExecutionMode.SeparateThread` instead of `SeparateProcess`, this workaround is only sometimes possible.  If our kiosk software could entirely consist of 100% UWP apps, then yes we could use `SeparateThread` like you suggested, but 100% UWP is impossible because the functionality requirements from clients include multiple features that are unsupported or unavailable in UWP apps.  
* Some features are disallowed by the UWP security/sandbox restrictions (for example, administration/configuration of OS settings; or `HKEY_LOCAL_MACHINE` etc).  
* Some other features from Microsoft are currently only supported in WPF apps; not yet in UWP apps.  

Thus our kiosk software consists of multiple components:
* Components written as **UWP** apps.  Yes these can use `SeparateThread` instead of `SeparateProcess`.
* Components written as **WPF** apps.  `SeparateThread` is unsupported here.  The only supported execution mode in WebView-for-WPF (`Microsoft.Toolkit.Wpf.UI.Controls.WebView` 6.0.0-preview7.1) is separate-process.
* In future, a component could use WebView2/Chromium but presumably WebView2 will only ever support one mode:  Separate process.
* Two components that are Windows Services (no GUI; not applicable to WebView).

If **both** of WebView-for-UWP and WebView-for-WPF supported the `SeparateThread` mode, then this would be a big help -- it'd enable a workaround.

On the topic of crash control:  If WebView crashes when running in `SeparateThread` mode, then it also crashes the kiosk app, thus `SeparateProcess` is desirable/preferred, but nevertheless we would accept `SeparateThread` if possible, but the `SeparateThread` option isn't always available -- sometimes the only supported mode is `SeparateProcess` as I mentioned.

When a 100% UWP app is switched from `SeparateProcess` to `SeparateThread` mode, it still doesn't solve the other problem where `Windows.Web.Http.Filters.HttpBaseProtocolFilter.CookieManager` provides inadequate access to cookies, especially when the app cannot know/determine the exact URL/domain/path of each cookie.  For example, `Windows.Web.Http.HttpCookieManager` doesn't support these abilities:
* Get a listing of all cookies across all URI's/domains.
* Get a listing of all cookies for a specified domain (and/or partial-match "*.example.com") regardless of `HttpCookie.Path`.
* Delete all cookies across all URI's/domains.
* Delete all cookies for a specified domain (and/or partial-match "*.example.com") regardless of `HttpCookie.Path`.

**Comment by verelpode** [comment]
@Austin-Lamb -- What do you think of the following way of solving the problem?  I guess the following bug fix is probably much less work than removing the dependency on explorer.exe.  Maybe if we're lucky, the following is a tiny-but-very-helpful bug fix?

I would allow explorer.exe to run as normal, and then I would run the kiosk software in a separate new desktop ([HDESK](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw)).  When I create the new desktop, I would NOT launch an instance of explorer.exe in the new desktop.  Thus explorer.exe would run in the default desktop as normal, and no instance of explorer.exe would run in the new desktop where I run the kiosk software.

However, the above workaround-idea requires a bugfix before it can succeed:  When the WebView mode is `SeparateProcess`, the separate web process should be launched in the **same** `HDESK` as the app that uses WebView, but currently the separate web process is always launched in the **default** `HDESK`.  I've written more details about this bug in a new issue:  
[WebView launches separate process in wrong desktop (HDESK) #1384](https://github.com/microsoft/microsoft-ui-xaml/issues/1384)

Hopefully fixing the `HDESK` bug is much less work than removing the dependency on explorer.exe?   What do you think?

**Comment by adambarlow** [comment]
As we move to invest in Webview 2 we will not be addressing this issue in the existing EdgeHTML Webview. 

Please feel free to file a suggestion for the capability you want to see in Webview 2 here:
https://github.com/MicrosoftEdge/WebViewFeedback
