### ISSUE TITLE
With rounded corners, top right of TeachingTip has a gap

### ISSUE THREAD

**Issue by jevansaks** [microsoft/microsoft-ui-xaml#1254]
**Describe the bug**
Look at the top right corner of TeachingTip with rounded corners:

![image](https://user-images.githubusercontent.com/20667023/64058807-9c8afa80-cb65-11e9-8654-8c27f29225d0.png)

**Steps to reproduce the bug**

1. Install latest Nuget package to Xaml Controls Gallery
2. Run Xaml Controls Gallery and go to TeachingTip page
3. Click on the first button.

**Expected behavior**
All the corners should look rounded and even.

**Version Info**

NuGet package version: 
2.2.1908300001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by mdtauk** [comment]
The Teaching Tip should probably make use of the CornerRadius Filter, so you can turn off the rounding for those corners with the Tail

**Comment by StephenLPeters** [comment]
> The Teaching Tip should probably make use of the CornerRadius Filter, so you can turn off the rounding for those corners with the Tail

Here is a picture of what it looks like with change #1305.  Did you have something else in mind? 
![Capture](https://user-images.githubusercontent.com/7758786/64643754-f5f4f400-d3c5-11e9-971a-fdd93e170854.PNG)
