### ISSUE TITLE
MessageDialog's RTL

### ISSUE THREAD

**Issue by jrahma** [microsoft/microsoft-ui-xaml#1256]
Hi,

Please add an option for RTL to the MessageDialog..

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jevansaks** [comment]
Could you elaborate? Are you asking to pop up MessageDialog in RTL even though the UI language is set to LTR?

MessageDialog is a system dialog and isn't API that our team owns. Please file this bug in Feedback Hub and I can help route it to the owners.

Full transparency -- this is likely to be a "won't fix" as changing the flow direction of top level windows to be different than the system is not an expected scenario.

**Comment by jrahma** [comment]
@jevansaks my ContentPage's FlowDirection is RightToLeft so I expect that the MessageDialog should also be RightToLeft.. It make no sense for the app to use RightToLeft dircetion except in MessageDialog... Xamarin Forms has done it and I believe it's doable here too.

Done on Feedback :)

![MessageDialog](https://user-images.githubusercontent.com/6236241/64132833-8c804e80-cde3-11e9-8f81-8b1e5ff4488b.png)

**Comment by jevansaks** [comment]
Have you looked into using ContentDialog instead?

**Comment by jrahma** [comment]
That's what I am currently using but why should I use ContentDialog and design my down dialog when I just want a Yes / No confirmation

That's why I though it's something which needs to be fixed by the team

**Comment by jevansaks** [comment]
ContentDialog has yes/no -- you set PrimaryButtonText, CloseButtonText and Content. It should be as straightforward to configure as MessageDialog. Up to you.

**Comment by jrahma** [comment]
I know :)

but that doesn't mean MessageDialog's RTL is not an issue :)

**Comment by adrientetar** [comment]
ContentDialog is the replacement for MessageDialog. I think MessageDialog is only kept for backwards compatibility.

![image](https://user-images.githubusercontent.com/1250894/65055947-5bba2080-d970-11e9-9279-1f861b7d9c02.png)
