### ISSUE TITLE
ComboBox lost rounded corners if any explicit Style is set for it

### ISSUE THREAD

**Issue by eugenegff** [microsoft/microsoft-ui-xaml#1260]
**Describe the bug**

ComboBox lost rounded corners if any explicit Style is set for it, even if Style has no setters or is {x:Null}. Rounded corners should be enabled via implicit style, leaving explicit style for exclusive usage by application developer.

**Steps to reproduce the bug**

[ComboBoxLostRoundedCorners.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3565812/ComboBoxLostRoundedCorners.zip)

1. Unzip, build and run attached ComboBoxLostRoundedCorners project
2. ComboBox created with `<ComboBox/>` snippet will properly have rounded corners
ComboBox created with `<ComboBox Style="{x:Null}"/>` snippet would not

**Expected behavior**

ComboBox created with `<ComboBox Style="{x:Null}"/>` should have rounded corners

**Screenshots**

![image](https://user-images.githubusercontent.com/34012295/64111812-451ba300-cd8e-11e9-8191-68bc6e3614ac.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.2.190830001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
Yes, this is expected with WinUI 2.2. We'll be able to fix it for WinUI 3.0.

@kaiguo are the new styles named in such a way that someone can do a BasedOn style for them?

**Comment by kaiguo** [comment]
Hmm, looks like there's no name associated with it, should we give it one like "DefaultComboBoxStyle"?

**Comment by jevansaks** [comment]
I'm wondering if we should do that for all our new default styles? Giving it a name will make it no longer get picked up as the default, so you have to make an unnamed one that's based on that named one:
```xaml
<Style TargetType="ComboBox" BasedOn="{StaticResource DefaultComboBoxStyle}"/>
```

**Comment by dpaulino** [comment]
Hi, just wanted to chime in that I'm seeing this exact same issue with combo boxes and with buttons. Would be great if the proposed fix is applied to everything!

**Comment by jevansaks** [comment]
Kai is working on it -- #1300!
