### ISSUE TITLE
MediaPlayerElement time indicators deviate from Microsoft style guide requirements

### ISSUE THREAD

**Issue by dan-jac** [microsoft/microsoft-ui-xaml#1264]
Reference URL: https://styleguides.azurewebsites.net/Styleguide/Read?id=2547&topicid=14813

For “Time indicators (media)”, the style guide requires that there be no leading zeros in the number of minutes, and no visible zero ('0') for the number of hours for content that's less than one hour long.

E.g. In this sample video:
![image](https://user-images.githubusercontent.com/50617707/64169868-fda91b80-ce4e-11e9-9f97-688210ebe098.png)
The time remaining should be “0:12”, and not “00:00:12”.

**Comment by dpierangeli** [comment]
I this case i prefer the control way, if i see "0:12" without prior knowledge i would think that this is a 12 minutes video and not 12 seconds.

**Comment by shaheedmalik** [comment]
With SMTPE standards, seeing it as is the the correct way. I concur that 00:12 would make me think it's 12 mins.

**Comment by chigy** [comment]
I've opened https://github.com/MicrosoftDocs/windows-uwp/issues/1927 to track documentation update.

Upon discussion with the owner of the style guide, the way we are using time on our media control is good. Their style guide is more generic text style guidance and does not specifically cover this specifc application UI scenario. So our [media control topic ](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/media-playback)should cover the detail.

**Comment by chigy** [comment]
@dan-jac , talked with documentation team further. The document you refer to is an internal to Microsoft doc. We have an external facing document that should be followed by both internal and external application teams which is here. https://docs.microsoft.com/en-us/windows/uwp/design/ This document does not specify all the reasons for control design choice especially around certain UI that are built in and developers are not able to change.
