### ISSUE TITLE
Change App configuration to use the Win UI library

### ISSUE THREAD

**Issue by AMaini503** [microsoft/microsoft-ui-xaml#1267]
Hi,

I had developed an app earlier that used the SDK 17763. Can anyone summarize the steps to take to make my UWP application use the latest SDK i.e. 18362 ?

Further, if for some reason, all I want to do is port just one single control over from 18362 to 17763, what is the best way to do that ?

**Comment by jevansaks** [comment]
Changing SDK target is: right click project properties and change the SDK version.

Or if you are looking for a writeup on how to use WinUI: https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started
