### ISSUE TITLE
Buttons inside TextBox, PasswordBox and AutoSuggestBox don't correctly support CornerRadius

### ISSUE THREAD

**Issue by rudyhuyn** [microsoft/microsoft-ui-xaml#1268]
## Describe the bug
`TextBox`, `PasswordBox` and `AutosuggestBox` received an updated adding rounded corners to their default templates. Unfortunately, the template of the 3 buttons associated to these controls (TextBox and AutoSuggestBox: Clear button, PasswordBox: Reveal button) haven't been updated to support these new corners. 

These controls aren't correctly render when these buttons have a background (Pressed state for example), for 2 reasons: 
- a negative margin is added to these controls (`HelperButtonThemePadding` = 0,0,-2,0)
- the button/toggle button doesn't have rounded corners on the right side.

## Steps to reproduce the bug
- Create a new project
- Add a PasswordBox, TextBox and AutoSuggestionBox (be sure to add a margin on the right to see the issue)
- Type a text in these controls and press and hold their internal buttons

## Expected behavior

Controls should keep their round corner and buttons should not overflow the control

## Screenshots

**TextBox:**
![image](https://user-images.githubusercontent.com/1226538/64224993-619f0480-ce8e-11e9-8fb7-0ea27aad6774.png)

**PasswordBox**
![image](https://user-images.githubusercontent.com/1226538/64225016-7ed3d300-ce8e-11e9-9590-6aebf1cf4e14.png)

**AutoSuggestBox** (a lot less obvious because of the spacing but similar issue)
![image](https://user-images.githubusercontent.com/1226538/64225036-93b06680-ce8e-11e9-9cf4-dfefdc7aaf6f.png)

## Version Info

NuGet package version: 
2.2.190830001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18965)              | Yes   |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |

**Comment by deathmark512** [comment]
866d6a0847fee220bb6ab9950bcadeec390f06c2be454ed737ce3db46eb94927

**Comment by chigy** [comment]
@rudyhuyn , thanks for finding the issue.
