### ISSUE TITLE
Question: Is there a plan to release a pre-release 2.3 with goodies of 2.2?

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1270]
Many of us use pre-release packages and 2.2 was just release without the preview feature. Just wondering if there is plan to release a pre-release package with the goodies of 2.2 + preview features.

**Comment by jevansaks** [comment]
Yes! We'll publish a 2.3 package this week.

**Comment by jevansaks** [comment]
Now published!
