### ISSUE TITLE
ISupportIncrementalLoading not working TreeView

### ISSUE THREAD

**Issue by TheFo2sh** [microsoft/microsoft-ui-xaml#1271]
**Describe the bug**
Binidng TreeView.ItemsSource property to a collection that implement ISupportIncrementalLoading is not working , the LoadMoreItemsAsync is never called. 

**Steps to reproduce the bug**

1. Create a new project

2. create a dummy Incremental Collection that generate dummy data `class IncrementalCollection:ObservableCollection<DataModel>,ISupportIncrementalLoading`

3. create an instance of the Incremental Collection in MainPage.xaml.cs
public IncrementalCollection DataSource =new IncrementalCollection();

4. Bind the DataSource to treeViewControl
`<TreeView ItemsSource="{x:Bind DataSource}">
            <TreeView.ItemTemplate>
                <DataTemplate x:DataType="local:DataModel">
                    <TreeViewItem ItemsSource="{x:Bind Children}"
                                       Content="{x:Bind Title}"/>
                </DataTemplate>
            </TreeView.ItemTemplate>
        </TreeView>`
**Expected behavior**
The LoadMotreItems Async get called same as ListView

**Version Info**
Microsoft.NETCore.UniversalWindowsPlatform 6.2.9

NuGet package version: 
Microsoft.NETCore.UniversalWindowsPlatform 6.2.9

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       | Yes   |
| Creators Update (15063)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

you can find a complete sample here 
https://github.com/TheFo2sh/UWP-Sample-Issues/tree/master/TreeViewIncrementalCollectionSupport

**Comment by YuliKl** [comment]
Related to #723?

**Comment by TheFo2sh** [comment]
the case here is quite different , the treeview do not call the load more function from the start , I can imagine that it might be related to

https://github.com/microsoft/microsoft-ui-xaml/issues/723#issuecomment-495296009

> Sorry. Nesting ListView's is not supported. You end up de-virtualizing everything if you nest, so the incremental loading becomes pointless.

but I am not sure about the TreeView internals , at least the incremental loading can be supported to the outer DataSource ,if that is possible.

**Comment by jevansaks** [comment]
I can believe this, as TreeView does a custom flattening data source. We could make this work but I wonder if @ranjeshj has any thoughts about how we would handle this in a nested-Repeaters implementation of TreeView that we're hoping we might be able to move to.

**Comment by ranjeshj** [comment]
ItemsRepeater has the hooks to get the same information to make incremental loading work, but does not support ISupportIncrementalLoading interface. For one level it should be straightforward. Multiple levels is probably something that the control will need to do since it has the full picture.

**Comment by TheFo2sh** [comment]
Any updates?

**Comment by ranjeshj** [comment]
@TheFo2sh this is currently in the backlog. I believe this can be solved when we move TreeView to use ItemsRepeater instead of ListView. In the meantime, as a workaround, you could probably look at the last realized item in the underlying listview or offset of the ScrollViewer and use that to trigger loading of more items.
