### ISSUE TITLE
SplitButton template ignores its FontFamily, FontSize, etc.

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/microsoft-ui-xaml#1275]
**Describe the bug**

SplitButton fails to propagate a bunch of its properties into its child buttons; it instead chooses to forcibly set them to system resources.

https://github.com/microsoft/microsoft-ui-xaml/blob/f2b0459553152d69168aa6929c9ff0a7188ac8ea/dev/SplitButton/SplitButton.xaml#L41-L43

This makes it impossible to have a split button that _trivially_ contains glyphs from Segoe MDL2 Assets.

**Steps to reproduce the bug**

```xml
<mux:SplitButton
    x:Name="NewTabButton"
    Click="OnNewTabButtonClick"
    VerticalAlignment="Stretch"
    HorizontalAlignment="Left"
    Background="{ThemeResource TabViewItemHeaderBackground}"
    Foreground="{ThemeResource SystemControlBackgroundBaseMediumBrush}"
    Content="&#xE710;"
    FontFamily="Segoe MDL2 Assets"
    FontSize="12">
</mux:SplitButton>
```

The button shows up as containing a box. The font is not applied.

![image](https://user-images.githubusercontent.com/14316954/64288594-5c39cc80-cf17-11e9-8524-fa1404f86623.png)

**Expected behavior**

The button would display the glyph; in this example, it's `U+E710 ADD`.

![image](https://user-images.githubusercontent.com/14316954/64288670-81c6d600-cf17-11e9-9c47-454a263b01c3.png)

**Version Info**

NuGet package version: 
2.2

**Additional Context**
This can be worked around by adding a Viewbox or some other element capable of presenting text to the button's Content, but it doesn't seem like it should be necessary to do so.

**Comment by YuliKl** [comment]
@teaP do you have time to take a look?

**Comment by teaP** [comment]
Fixed.
