### ISSUE TITLE
Isn't it possible to bring back AU 14393 update support

### ISSUE THREAD

**Issue by NGame1** [microsoft/microsoft-ui-xaml#1278]
Isn't it possible to bring back AU 14393 update support
because of the large number of mobile users of my app I have to continue supporting the Anniversary update.

**Comment by dotMorten** [comment]
> because of the large number of mobile users of my app I have to continue supporting the Anniversary update.

Isn't Windows Mobile just about to go out of support (December 2019). And that's for the 1709 devices only, which AFAIK supports 10.0.15063. Support for 1703 ended in June.
And 14393 for Desktop went out of support in April. So it seems fair the min-version was moved up a notch.

I guess the real question is: If the underlying platform no longer supports it, should/can WinUI?

**Comment by Tirraon** [comment]
@jevansaks @dotMorten 
Hi!
I want to bump this issue for one question:
Which WinUI version supports AU 14393?

**Comment by dotMorten** [comment]
@Tirraon v2.1:
https://github.com/microsoft/microsoft-ui-xaml/commit/3b631bd85d3ffacb08e93e299d1d956be591d6ee

**Comment by Tirraon** [comment]
@dotMorten 
Thanks!
