### ISSUE TITLE
Replace theme dictionary for NavigationView

### ISSUE THREAD

**Issue by AMaini503** [microsoft/microsoft-ui-xaml#1281]
I am using a NavigationView on a page in my application as: 
`<Page>
    <NavigationView>
         ......
    </NavigationView>
</Page>`

I want to replace the Resource Dictionary for NavigationView ( specifically the one for "HighContrast" theme ). I have been able to achieve it by putting the resource dictionary in the <Page.Resources />. But, would it not replace the high contrast resource dictionary for all the controls on the page ? Is there a way to replace it just for the NavigationView ?

**Comment by YuliKl** [comment]
You are correct that the scope of the resource dictionary in this case is all Page content. Can you elaborate on what you're replacing? Typically, controls have their own resources, so what you're replacing may potentially only apply to the NavigationView control.

**Comment by AMaini503** [comment]
I want to replace the “NavigationViewButtonBackgroundPointerOver” property. And, if I add a resource dictionary with the same key as the one is already defined ( in this the key is “HighContrast” ), does the new dictionary completely replace the existing default dictionary or it overrides only the common properties ?

**Comment by YuliKl** [comment]
If you create a dictionary like this
```xaml
<Page.Resources>
    <ResourceDictionary>
        <ResourceDictionary.ThemeDictionaries>
            <ResourceDictionary x:Key="Dark">
                <SolidColorBrush x:Key="NavigationViewButtonBackgroundPointerOver" Color="Purple" />
            </ResourceDictionary>
            <ResourceDictionary x:Key="Light">
                <SolidColorBrush x:Key="NavigationViewButtonBackgroundPointerOver" Color="Pink" />
            </ResourceDictionary>
            <ResourceDictionary x:Key="HighContrast">
                <SolidColorBrush x:Key="NavigationViewButtonBackgroundPointerOver" Color="{ThemeResource SystemColorButtonFaceColor}" />
            </ResourceDictionary>
        </ResourceDictionary.ThemeDictionaries>
    </ResourceDictionary>
</Page.Resources>
```
Then every instance of `NavigationViewButtonBackgroundPointerOver` on the Page will be overwritten with the new colors. Resources with other keys (and likely belonging to other controls) won't change in any way.
