### ISSUE TITLE
Edit template of HyperlinkButton uses an invalid attribute value (Padding) that causes a crash on older builds

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/microsoft-ui-xaml#1287]
**Describe the bug**
Editing an HyperlinkButton will create the template with:
Padding Value="{StaticResource HyperlinkButtonPadding}"

Visual Studio says that the value is invalid which is weird because VS generates it. When running on the current SDK, the app runs well, but it crashes when running on 17134 or older

**Steps to reproduce the bug**

1. Edit a template of a HyperlinkButton and use the button template in MainPage.xaml
2. Deploy on 17134 -> Crash

**Expected behavior**
No crash and for the benefits to everyone, the XAML engine at runtime should be smart and ignore invalid/not-supported values
![hyperlink](https://user-images.githubusercontent.com/1608424/64392622-9096b100-d01b-11e9-9e28-b745e9e75455.jpg)
.

**Screenshots**
See screenshot

**Version Info**
Create the button with 17763 and deploy with 17134

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | No  |
| October 2018 Update (17763)        | No  |
| April 2018 Update (17134)          | Yes  |
| Fall Creators Update (16299)       | Yes   |
| Creators Update (15063)            |  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
All of these are the same problem/mitigation/resolution. Sorry! #1288
