### ISSUE TITLE
Edit template of a Button or Hyperlink will cause a crash on 16299 because of the value UseSystemFocusVisuals

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/microsoft-ui-xaml#1288]
**Describe the bug**
Editing the template of a Button or an HyperlinkButton on the recent SDK will cause a crash on Windows 10 16299.

**Steps to reproduce the bug**
1. Edit a template of a HyperlinkButton and use the button template in MainPage.xaml
2. Deploy on 16299 -> Crash

**Expected behavior**
No crash

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | No  |
| October 2018 Update (17763)        | No  |
| April 2018 Update (17134)          | No |
| Fall Creators Update (16299)       | Yes   |
| Creators Update (15063)            |  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by AMaini503** [comment]
How did you find the default template for the controls ? I assume Visual Studio doesn't support that for UWP apps at least.

**Comment by jevansaks** [comment]
They're included in the nuget package. This is a problem with Visual Studio's experience here. You'll get warnings that the template is incompatible and you can use conditional XAML to mitigate it.

But in truth this scenario won't get better until WinUI 3.0 -- but the good news is that when we switch to WinUI 3.0 there won't be any need for conditional XAML at all.

**Comment by ArchieCoder** [comment]
@jevansaks which nuget package are you referring too?

**Comment by jevansaks** [comment]
Oh sorry, I missed that this wasn't a bug about WinUI. Same problem with the templates from the SDK though.

**Comment by ArchieCoder** [comment]
Your colleagues asked me to fill the bug in this repo. This is a very scary bug that can backfire to any dev referring old Win10 updates.

**Comment by jevansaks** [comment]
Are you not seeing a build warning about those properties? There should be intellisense and build warnings.

**Comment by ArchieCoder** [comment]
There is an Intellisense warning, but I will not rely much on that tbh. 

As seen in the screenshot, BackgroundSizing is detected but nothing else.

![2019-09-09_14-39-48](https://user-images.githubusercontent.com/1608424/64557567-cd122780-d30f-11e9-9cf1-1ba4a9f9e793.png)

**Comment by jevansaks** [comment]
I don't mean to bounce you around, but this bug should be filed on Visual Studio's developer community site (via the VS "Send feedback" button). 

Or if you tell me which "colleagues", I can follow up with them via email.
