### ISSUE TITLE
ItemsRepeater doesn't arrange new child once becomes empty

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#1290]
**Describe the bug**
Live visual tree says corresponding items are present, but has no space.

**Steps to reproduce the bug**
1. Create an `ItemsRepeater` and bind it with some collection (using `DataTemplate`)
2. Trigger some action to modify the source collection with Add->Remove to empty->Add

**Expected behavior**
The added item shows correctly.

**Screenshots**
The last added item is not shown. If resize the window to trigger rearrange, then it's shown.

**Version Info**

NuGet package version: 
2.2.190830001
This is a regression from 2.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
Can you please attach a simple repro app that shows this behavior ?

**Comment by huoyaoyuan** [comment]
The visual tree of original application is very complicated, and heavily customized, using `ExtendViewIntoTitleBar`, directly setting `Window.Content` to page without using `Frame`, and `Microsoft.Toolkit.Uwp.UI.Controls.LayoutTransformControl`, with binding to a custom `INotifyCollectionChanged` collection.
I cannot repro this issue from a newly created app.
I may reduce original app if I'm free. But it may be resolved if any of them changes in WinUI 3.

**Comment by ranjeshj** [comment]
Closing this issue since it is not actionable without a repro. Please feel free to activate it once you have one. Thanks.
