### ISSUE TITLE
Proposal: Add an inset facing shadow to NavigationView in expanded mode

### ISSUE THREAD

**Issue by carmellolb** [microsoft/microsoft-ui-xaml#1291]
# Proposal: Add an inset facing shadow to NavigationView in expanded mode and an outset shadow to small and opened mode

## Summary
Add an inset shadow when NavigationView is in expanded mode and an outset shadow when in small and opened mode.

## Rationale
Adding an inset shadow to expanded NavigationView would add more visual hierarchy by implying that the content on the right is the focus. When in small and opened mode, an outset shadow should be used because it is transient and the user initiated the opening of it, so it is the focus.

**Comment by jevansaks** [comment]
In transient mode where the navigation pane slides out, we do have a shadow when running on Windows 1903 and up. I don't see it in XAML Controls Gallery though, that may be a bug.

For the other suggestion of having the content cast a shadow onto the navigationview pane, that's an interesting idea.

**Comment by mdtauk** [comment]
![blade-view-ideas-v2](https://user-images.githubusercontent.com/7389110/64635945-96640c00-d3f8-11e9-9759-167fb420dc0d.png)
![master-detail-view](https://user-images.githubusercontent.com/7389110/64635952-995efc80-d3f8-11e9-98e4-7aad2f90fb41.png)

These are some changes I proposed in the Community Toolkit a while back, to try to bring a consistent approach to Layering with Acrylic Panes.

**Comment by carmellolb** [comment]
> In transient mode where the navigation pane slides out, we do have a shadow when running on Windows 1903 and up. I don't see it in XAML Controls Gallery though, that may be a bug.
> 
> For the other suggestion of having the content cast a shadow onto the navigationview pane, that's an interesting idea.

Sorry for the late reply. Yes and it would provide visual hierarchy by giving the impression that the pane on the right (the main content) was in front. Is it possible?

**Comment by YuliKl** [comment]
@carmellolb, to double-check, are you thinking something like this? 
(focusing on the specific portion of @mdtauk's comp that I think illutrates your request)

![image](https://user-images.githubusercontent.com/13142665/65920877-3926ff00-e395-11e9-8cee-d8bb869d1535.png)

**Comment by mdtauk** [comment]
> @carmellolb, to double-check, are you thinking something like this?
> (focusing on the specific portion of @mdtauk's comp that I think illutrates your request)
> 
> ![image](https://user-images.githubusercontent.com/13142665/65920877-3926ff00-e395-11e9-8cee-d8bb869d1535.png)

That is what I understood the request to mean.  Even without Acrylic, it would visually enhance the SplitView/NavigationView controls.

The Pane in Overlay mode, would be the one casting the shadow, not receiving it.

And extending into the Titlebar would be the icing on the cake :)

**Comment by carmellolb** [comment]
> @carmellolb, to double-check, are you thinking something like this?
> (focusing on the specific portion of @mdtauk's comp that I think illutrates your request)
> 
> ![image](https://user-images.githubusercontent.com/13142665/65920877-3926ff00-e395-11e9-8cee-d8bb869d1535.png)

@mdtauk @YuliKl It sure is! I’m glad you like the idea! Yes I think it would really enhance the design.

**Comment by carmellolb** [comment]
> ![blade-view-ideas-v2](https://user-images.githubusercontent.com/7389110/64635945-96640c00-d3f8-11e9-9759-167fb420dc0d.png)
> ![master-detail-view](https://user-images.githubusercontent.com/7389110/64635952-995efc80-d3f8-11e9-98e4-7aad2f90fb41.png)
> 
> These are some changes I proposed in the Community Toolkit a while back, to try to bring a consistent approach to Layering with Acrylic Panes.

Yes so there are plans to add what I am saying?

**Comment by mdtauk** [comment]
@carmellolb  Those are mock-ups I submitted to the Community Toolkit when they were building their Navigation View and Master/Detail controls.

But they show the idea of the use of the inset shadows

**Comment by carmellolb** [comment]
> @carmellolb Those are mock-ups I submitted to the Community Toolkit when they were building their BladeView, NavigationView and Master/Detail controls.
> 
> But they show the idea of the use of the inset shadows

Yes I understand. Are they coming to WinUI for real though sometime?

**Comment by carmellolb** [comment]
> @carmellolb Those are mock-ups I submitted to the Community Toolkit when they were building their BladeView, NavigationView and Master/Detail controls.
> 
> But they show the idea of the use of the inset shadows

Yes, the mock-ups look like what I am suggesting.

**Comment by YuliKl** [comment]
@carmellolb, you've really made two related proposals.
1. Add an inset facing shadow to NavigationView in expanded mode 
2. Add an outset shadow to small and opened mode

The second part is already done...although something has regressed and I've opened #1394 to restore the shadow.
The first part is a great suggestion that we won't add **right** now but will definitely keep in mind as Fluent color and elevation story continues to get defined.

I'm going to update the title to more accurate reflect the remaining work and will remove myself as the issue assignee. I'll post updates as I hear more about the design direction for the whole system and decisions about elevation/shadow.

**Comment by YuliKl** [comment]
Looking at my last comment it seems that #2254 covers 1, and 2 is already implemented. Therefore, I don't think we need this issue to remain active and I'm closing it.
