### ISSUE TITLE
Layout Cycle Crash in ItemsRepeater inside ListViewItem

### ISSUE THREAD

**Issue by dannyp32** [microsoft/microsoft-ui-xaml#1293]
**Describe the bug**
An ItemsRepeater inside of a ListViewItem datatemplate causes a crash when trying to scroll due to a layout cycle. 
Its easy to repro if the window height is small like shown in the video and there are 2 (more than 1?) items in the item repeater that both are larger than the window height.  

**Steps to reproduce the bug**

1. Run the test app. 
[ItemsRepeaterCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3587103/ItemsRepeaterCrash.zip)

2. Make the height of the window small like shown in the video.
3. Scroll down and you should hit the crash. 

**Expected behavior**
Should scroll normally. No Crash. 

**Screenshots**

[ReproCrash.mp4.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3587084/ReproCrash.mp4.zip)
[callstack.txt](https://github.com/microsoft/microsoft-ui-xaml/files/3587085/callstack.txt)

**Version Info**
NuGet package version: 
[Microsoft.UI.Xaml 2.2.190830001] 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
ListView and ItemsRepeater do their own corrections and anchoring which at times can conflict with each other especially if the growth is in the same direction. Please nest ItemsRepeater instead which knows how to work when nested.
