### ISSUE TITLE
Implicitly grouped `RadioButton`s are treated as in the same group

### ISSUE THREAD

**Issue by NextTurn** [microsoft/microsoft-ui-xaml#1299]
**Describe the bug**

Only one of implicitly grouped `RadioButton`s can be set to `IsChecked` programmatically.

**Steps to reproduce the bug**
```xaml
<Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Button>
            <Button.Flyout>
                <Flyout>
                    <StackPanel>
                        <RadioButton x:Name="RadioButton1" IsChecked="True" />
                    </StackPanel>
                </Flyout>
            </Button.Flyout>
        </Button>
        <Button>
            <Button.Flyout>
                <Flyout>
                    <StackPanel>
                        <RadioButton x:Name="RadioButton2" IsChecked="True" />
                    </StackPanel>
                </Flyout>
            </Button.Flyout>
        </Button>
    </Grid>
</Page>
```

```cs
using System.Diagnostics;
using Windows.UI.Xaml.Controls;

namespace App1
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            InitializeComponent();
            Debug.WriteLine(RadioButton1.IsChecked);
            Debug.WriteLine(RadioButton2.IsChecked);
        }
    }
}
```

**Expected behavior**

```
True
True
```

**Actual behavior**

```
False
True
```

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Comment by jevansaks** [comment]
Seems by design? Unnamed RadioButtons are all in the same "group" and will find each other to make sure they stay mutually exclusive. Try setting GroupName on one of them to something non-default.

**Comment by NextTurn** [comment]
They are not exclusive. You can check one RadioButton in each group after the initialization.

**Comment by jevansaks** [comment]
If you just have two "ungrouped" RadioButtons in a page, they are exclusive. I think the bug is that at runtime if a flyout is open then changing one RadioButton doesn't affect the other because the closed flyout isn't in the tree and the RadioButton can't find its friend anymore.

**Comment by NextTurn** [comment]
This behavior is not relevant to `Flyout`s. See the following example with `Flyout`s changed to `StackPanel`s.

If `RadioButton1.IsChecked` is set to `true` programmatically, another will be unchecked.

But both can be checked manually by user input.

```xaml
<Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>
        <StackPanel Grid.Row="0">
            <StackPanel>
                <RadioButton x:Name="RadioButton1" IsChecked="True" />
            </StackPanel>
        </StackPanel>
        <StackPanel Grid.Row="1">
            <StackPanel>
                <RadioButton x:Name="RadioButton2" IsChecked="True" />
            </StackPanel>
        </StackPanel>
    </Grid>
</Page>
```

```cs
using System.Diagnostics;
using Windows.UI.Xaml.Controls;

namespace App1
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            InitializeComponent();

            Debug.WriteLine(RadioButton1.IsChecked); // False
            Debug.WriteLine(RadioButton2.IsChecked); // True

            RadioButton1.IsChecked = true;

            Debug.WriteLine(RadioButton1.IsChecked); // True
            Debug.WriteLine(RadioButton2.IsChecked); // False

            // Click RadioButton2

            RadioButton2.Checked += (sender, e) =>
            {
                Debug.WriteLine(RadioButton1.IsChecked); // True
                Debug.WriteLine(RadioButton2.IsChecked); // True
            };
        }
    }
}
```

```
False
True
True
False
True
True
```

**Comment by NextTurn** [comment]
@jevansaks ping?

**Comment by jevansaks** [comment]
In your later repro, if you wait until things have "settled", are both IsChecked properties still true? Sometimes these events fire before all the values are up to date (since we're calling the callback synchronously during state changes).

Backing up a bit, what's the scenario you're trying to achieve?

**Comment by NextTurn** [comment]
Before clicking
![image](https://user-images.githubusercontent.com/45985406/64754069-279dc480-d558-11e9-8ece-6ab43e40238a.png)
After clicking
![image](https://user-images.githubusercontent.com/45985406/64754077-32585980-d558-11e9-9101-787b21b105d9.png)

The doc says "Put them inside the same parent container" to group radio buttons. The behaviors of initialization and `IsChecked` property setter in UWP is inconsistent with both Windows Forms and WPF.

WPF after initialization
![image](https://user-images.githubusercontent.com/45985406/64754162-aeeb3800-d558-11e9-9ff0-1a9eda5cfaf2.png)

Windows Forms source
```cs
if (isChecked)
{
    Control parent = ParentInternal;
    if (parent != null)
    {
        ControlCollection children = parent.Controls;
        for (int i = 0; i < children.Count; i++)
        {
            Control ctl = children[i];
            if (ctl != this && ctl is RadioButton)
            {
                RadioButton button = (RadioButton)ctl;
                if (button.autoCheck && button.Checked)
                {
                    PropertyDescriptor propDesc = TypeDescriptor.GetProperties(this)["Checked"];
                    propDesc.SetValue(button, false);
                }
            }
        }
    }
}
```

**Comment by StephenLPeters** [comment]
duping to #2081 as the discussion there has more info

**Comment by robloo** [comment]
This one is pretty bad. I ran across it trying to make the ColorPickerButton
