### ISSUE TITLE
Organize Repeater folders in a better way.

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#1303]
**Describe the bug**
Organize files into folders in the dev project under Repeater. It should be named collection controls and Repeater should be a sub folder. Likely one more subfolders for Selection, Layouts, ItemsSource etc.

There are about 112 files in the repeater folder and it is getting hard to find the file I am looking for - need to scroll back and forth in visual studio solution explorer. We should factor it into folders to keep them organized perhaps like so.

CollectionServices
  * Repeater
  * Layouts
       * FlowLayouts
  * ViewManagement
  * DataSource
  * Selection
  * Phasing
 
It would also give people looking at the sources a clearer picture instead of making repeater look like a monolithic code base.

**Comment by chingucoding** [comment]
If it is a suitable fix, I can reorganize them in the solution view as such: 
![image](https://user-images.githubusercontent.com/16122379/74745102-a31c4400-5263-11ea-96d1-d530fe0fee2b.png)

I've tried organizing them into (sub)folders, but with that I got the following errors when trying to compile:
![image](https://user-images.githubusercontent.com/16122379/74744999-7cf6a400-5263-11ea-93c1-cdf79cc37867.png)

**Comment by ranjeshj** [comment]
@chingucoding That looks like a good place to start. Also, while we are at it, can we name the folder ItemsRepeater to match the API name. View management and phasing should probably be under ItemsRepeater  since they are specific to ItemsRepeater. Not sure about the build errors for sub folders.

**Comment by chingucoding** [comment]
Should we continue putting efforts into this issue and put them into separate folders or is using filters enough organization and we can close this issue?

The main issue I see with actual separate folders is that imports of the headers can become difficult to figure out. Currently it's enough to include "ItemsSourceView.h" but with separate folders, one then needs to include the folder so it would be "ItemsSource/ItemsSourceView.h".

And of course, there may be problems with how we currently set up the compilation process as it does not account for the sub folders.

**Comment by ranjeshj** [comment]
I think the folders is nice to have but if we are using VS, what we have currently works fine. We could be moving some components into separate projects altogether. For example, selection model stuff should not have any dependencies on the other stuff, so it can move out into its own shared project.

**Comment by chingucoding** [comment]
Where should those components which are not strictly related on ItemsRepeater be moved to? Would they be a top level component like other controls or rather a "sub" project in the ItemsRepeater folder?
Would it make sense to also decouple the tests for them too, that is move e,g, SelectionAPITests somewhere different?

**Comment by ranjeshj** [comment]
Top level similar to ItemsRepeater. Its tests would move with it as well.

**Comment by chingucoding** [comment]
If we move them into the top directory, would it make sense to maybe split up the dev folder into "Controls" and maybe "Common"? There are multiple areas that currently kind of behave the same, i.e. are a top level wrapper for a category. One example would be materials which contains Acrylic and Reveal.

**Comment by ranjeshj** [comment]
On second thoughts I think we better leave this as is and take this up post WinUI3. We need to merge these changes into WinUI3 and doing a bunch of moves/refactor will likely make the merge harder. The filter solution works for now. I think we can close this bug and re-evaluate the folder organization all up post WInUi3.

**Comment by chingucoding** [comment]
Seems like a good idea, should we postpone #2260 until WinUI 3 too?

**Comment by ranjeshj** [comment]
Yes. I think both can be post WinUI3. Thanks!
