### ISSUE TITLE
TabView: Add shadow to selected tab

### ISSUE THREAD

**Issue by teaP** [microsoft/microsoft-ui-xaml#1306]
I have the work partly done in user/teaP/TabViewShadows; just need to clean up a bit and get word from PM/design on what the z-depth of the shadow should be and if it looks ok with the 4px rounded corners.

**Comment by mdtauk** [comment]
Most controls use a 2px Corner Radius.  4px is used for flyouts and overlays.  Tabs are a bit of both.  They overlay with the content, and when being dragged off the Tab Bar.  But with hover and pressed states, they would most likely be 2px right?

I remember there being a comment about using straighter edges for tabs.

**Comment by teaP** [comment]
> Most controls use a 2px Corner Radius. 4px is used for flyouts and overlays. Tabs are a bit of both. They overlay with the content, and when being dragged off the Tab Bar. But with hover and pressed states, they would most likely be 2px right?
> 
> I remember there being a comment about using straighter edges for tabs.

In collaboration with design, we settled on 4px corners.

**Comment by teaP** [comment]
Fixed in commit #1368
