### ISSUE TITLE
Question: Can I restore the UI to how it looked before 2.0?

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/microsoft-ui-xaml#1313]
Is there an easy way to restore how the UI looked before the 2.0 release? It's nice and all, but things are not as crisp as they used to be.

**Comment by mdtauk** [comment]
You can manually override the CornerRadius and Border Thickness resources in App.xaml

**Comment by patriksvensson** [comment]
@mdtauk Thank you for your answer.
