### ISSUE TITLE
Question: How to get ComboBox flyout to always be bottom-aligned?

### ISSUE THREAD

**Issue by hooligan495** [microsoft/microsoft-ui-xaml#1326]
I'm trying to get a comboBox to always have the popup open below (even if the bottom item is selected)  It seems to me the ComboBox's default behavior supports a mobile/tablet experience by default.  But I'd like to override that.  Some internet searching always leads me to a link to build my own 'custom' control with a flyout.  Is that the right way?  Is there a better way (maybe create a control by inheriting from the ComboBox and overriding the default behavior?)  Or can it actually be done via styling?

THanks

**Comment by jevansaks** [comment]
I don't see a way to do this easily. You could maybe try to find the Popup in the template tree and attach to events on it to reposition it during the opening sequence, but it isn't something that's natively supported.

May I ask why you don't want the behavior the control is providing?

**Comment by hooligan495** [comment]
we are building a ui for a medical device (using uwp and windows 10). Our ux team has built a screen that has the combo box near the top of the page and they want it to open down.   

Do you have any pointers on how I could intercept the events?  With that I guess I could try to creat a custom combo box derived from combobox.  

I was hoping to be able to just customize it via a styling change (e.g an attribute on the pop up part of the control but that seems a no go

**Comment by mdtauk** [comment]
A quick work around could be to use a DropDownButton and bind the selected item's text to the Button's content.

But to enable a specific drop down direction, sounds like a good idea.  With **Overlay** as a default behaviour.  This could also be useful for the Split Date and Time Picker that has been proposed. #918

**Comment by jevansaks** [comment]
That sounds like a good workaround @mdtauk.

@hooligan495  sorry, I don't see any easy way to do this with styling-only.
