### ISSUE TITLE
Question: Will be guidelines for migrating Win32 Common Controls / WPF to WinUI in Desktop apps?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1333]
With WinUI 3.0 and a general encouragement to get Win32 and WPF developers to consider moving towards using WinUI for their, UI - Should there be documentation and guidance around how you translate controls and common patterns over to a modern design and app flow?

This I imagine would be in a few parts...

- There would be example Win32 apps that have been ported over (Wordpad, Notepad, Character Map etc) with Build talks detailing the steps and hurdles that had to be overcome.

- New WinUI controls to fill in gaps compared to the WPF Control Library, but also the Win32 Common Controls - https://docs.microsoft.com/en-us/windows/win32/controls/individual-control-info

- Documentation tailored to matching behaviour and patterns that telemetry and developers identify as common for the apps they build.  For example, **Instead of an MDI interface, consider using a TabView** and other transition guidance.

- Identify the pain points that GDI brings up, and how WinUI fixes them.

- How to transition pure C Win32 code, and reuse as much of it, but replacing the UI layers.

## Open Questions
Is there any merit to this idea?

Is there anything missing that should be considered for this suggestion?

To anyone on the team, with a good knowledge of how WinUI Desktop will work technically - is there any issues with the idea of reusing Win32 Code, but replacing the GDI UI rendering?

Should this idea also include some kind of matrix showing the benefits and disadvantages of WinUI Desktop over WinUI Universal (UWP)?

**Comment by marb2000** [comment]
Thanks for your feedback @mdtauk 

**Is there any merit to this idea?**
Docs that help developers to migrate and learn are always a good idea.

**Is there anything missing that should be considered for this suggestion?**
It is early in the process to know what are the most impactful topics that we should cover in such a migration doc. Your points are good, and we should prioritize them when we develop the doc plan. 

**Is there any issues with the idea of reusing Win32 Code, but replacing the GDI UI rendering?**
Your Win32 code should continue working. However, WinUI in desktop will require WinUI/RT hence your code on the UI project should be C++ 17 compliance. As usual, good architecture and SoC principles will help.

**Should this idea also include some kind of matrix showing the benefits and disadvantages of WinUI Desktop over WinUI Universal (UWP)?**
I already created one. Perhaps I should make it public soon. Let's say Ignite 2019 as ETA 😊
