### ISSUE TITLE
Question: SelectedItemChanged in TreeView

### ISSUE THREAD

**Issue by ac-lap** [microsoft/microsoft-ui-xaml#1334]
There is no _SelectedItemChanged_ event in the _TreeView_, the WinForm one has this event. What is the alternative for it in UWP.
I need this event to give a summary of all the items selected by the user, plz suggest someway to achieve this.

**Comment by robloo** [comment]
I've never used TreeView as I'm waiting for it to stabilize some more. However, TreeViewItem derives from SelectorItem and even ListViewItem. This means it has an IsSelected dependency property. You could hookup a callback to this property and handle it manually. This is easiest if you are also manually adding items to the TreeView already.

This should be feature request too. There are a lot of events standard in other repeater/selection controls that seem to be missing.

**Comment by ac-lap** [comment]
No, I am not adding the items manually. I am using data binding. Given the _TreeView_ does not even give the list of items, how can I hook a callback?

**Comment by robloo** [comment]
You might want to take a look at the second reply from Nico Zhu here:
https://stackoverflow.com/questions/56766785/uwp-get-selected-nodes-from-treeview-control

If you create your own view model class with an IsSelected property you can bind it in the data template of the TreeViewItem. Then your model itself will be reporting this information and you could hook up an to it.

**Comment by jevansaks** [comment]
We recently noticed this oversight as well. @kaiguo did you have another bug tracking this or should we turn this into it?

**Comment by kaiguo** [comment]
@jevansaks Yeah we have #322. Should we just close this one and use the other one to track?

**Comment by jevansaks** [comment]
Yes, I'll mark this as dupe.

**Comment by beatnikthedan** [comment]
how would I do this with SelectedItemsChanged? i'm trying to keep track of selected items. right now I'm doing it from a Tapped event on the treeview and have to loop through the entire treeview and figure out what is checked in my treeview and what is checked in my model that the nodes are bound to. if I bind to IsSelected it only works for single selection not multiple selection
