### ISSUE TITLE
Nuget package shows no dependencies.

### ISSUE THREAD

**Issue by panoukos41** [microsoft/microsoft-ui-xaml#1335]
Nuget as seen in the picture shows no dependencies. While a small issue it makes it a bit harder to update or install if you can't see the dependencies right away.

![image](https://user-images.githubusercontent.com/20771798/64923761-d276e280-d7e5-11e9-8dec-38bfbe5fe33f.png)

**Comment by jevansaks** [comment]
That is because at this time there are no other Nuget dependencies. Were you expecting some?

**Comment by panoukos41** [comment]
Sorry for being this late to answer the github email got lost with others,
Should it not show that it depends on UAP with it's version?
e.g: uap10.0.18362

**Comment by jevansaks** [comment]
There's no good way to communicate that I'm aware of. The readme specifies [our current version requirements](https://github.com/Microsoft/microsoft-ui-xaml#version-support).
