### ISSUE TITLE
AutoSuggestBox not refreshing properly when using paste/undo commands from default context menu flyout

### ISSUE THREAD

**Issue by jbrianceau** [microsoft/microsoft-ui-xaml#1338]
**Describe the bug**

`AutoSuggestBox` does not refresh properly when using commands from default context menu flyout that are updating the input text (i.e. paste and undo).

**Steps to reproduce the bug**
1. Create the following Xaml page:
```
<Page
    x:Class="SandboxCSharp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <TextBlock x:Name="MyTextBlock" />
        <AutoSuggestBox Grid.Row="1" TextChanged="AutoSuggestBox_TextChanged" />

    </Grid>
</Page>
```
2. With the following C# event handler:
```
private void AutoSuggestBox_TextChanged(AutoSuggestBox sender, AutoSuggestBoxTextChangedEventArgs args)
{
    var textBlock = FindName("MyTextBlock") as TextBlock;
    textBlock.Text = $"TextChanged called with '{sender.Text}'";

    var list = new List<string>(new string[]
    {
        $"{sender.Text} test1",
        $"{sender.Text} test2",
        $"{sender.Text} test3",
        $"{sender.Text} test4",
    });
    sender.ItemsSource = list;
}
```
3. Put a string in the clipboard (e.g. "def")
4. Launch this XAML page
5. Type "abc" in the AutoSuggestBox
6. Invoke the context menu from the AutoSuggestBox (using menu key or Shift-F10 shortcut for instance)
7. Select "Paste"
8. Invoke the context menu again
9. Select "Undo"

**Expected behavior**
Suggestion list should be updated properly in steps 7 and 9.

**Screenshots**
- step 5
![image](https://user-images.githubusercontent.com/5746498/64968253-23e4a780-d8a2-11e9-9a6c-4d3f98fbb12f.png)

- step 6
![image](https://user-images.githubusercontent.com/5746498/64968301-35c64a80-d8a2-11e9-9db1-a46f0245cc5a.png)

- step 7
![image](https://user-images.githubusercontent.com/5746498/64968316-3b239500-d8a2-11e9-9883-376b6db80b47.png)

- step 8
![image](https://user-images.githubusercontent.com/5746498/64968350-4676c080-d8a2-11e9-899a-bbc6676348d7.png)

- step 9
![image](https://user-images.githubusercontent.com/5746498/64968358-4a0a4780-d8a2-11e9-8723-1b8e82397901.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Thanks for the great bug report! It sounds like these events may be raising change notifications with the old text from the TextBox? @ddalp ?

**Comment by ddalp** [comment]
@jevansaks I debugged and it is a bug introduced in floatie feature. In AutoSuggestBox::OnItemsChanged function, we check if current textbox is focused. The focus is on app bar button, so some code is skipped and result in the drop down list not updated. We can fix it by also checking if the focused element belongs to TextBox's floatie too. How do we proceed with this bug, should we open a OS bug to track it?

**Comment by jevansaks** [comment]
I'd prefer to use GitHub for tracking stuff going forward. Can we just fix this in WinUI 3.0 or do you tihnk it should be fixed in OS for Vb?

**Comment by ddalp** [comment]
AutoSuggestBox is not in WinUI, I think we will have to fix it in OS.

**Comment by chrisglein** [comment]
Good bug. Our best vehicle to fix this is going to be WinUI 3, rather than an OS fix.
