### ISSUE TITLE
TextBox hosted in XAML Island doesn't show up the grips when DPI is above 100%

### ISSUE THREAD

**Issue by marb2000** [microsoft/microsoft-ui-xaml#1341]
**Current behavior**
When tapping on a text and the DPI scaling level is above 100%, text selection grips do not show up in XAML Islands.

**Steps to reproduce the bug**
1. Change your DPI higher than 100%
2. Run the XAML Islands Controls Gallery: https://github.com/marb2000/XamlIslands/tree/XAML_Islands_Controls_Gallery/XAML_Islands_Controls_Gallery
3. Click on Text sample, select TextBox, insert some text, and tap the text.

**Expected behavior**
The grips show up.

**Version Info**
Inbox control running in 18652

**Comment by chrisglein** [comment]
Believe this to be fixed in the next version of Windows. @ddalp is working with Miguel to verify.

**Comment by ddalp** [comment]
Verified the fix for WPF and AppWindow hosted island on VB windows build.
