### ISSUE TITLE
When continously scrolling down, ItemsRepeater starts 'jumping' back and forth in the list

### ISSUE THREAD

**Issue by Phranky** [microsoft/microsoft-ui-xaml#1342]
**Describe the bug**
I have 2 nested ItemsRepeaters with different scroll directions (outer list: vertical; inner list: horizontal) to display a hierarchical list of data. When I press and hold the down-arrow key on the keyboard or the D-pad down key on the Xbox-controller the focus is moved down through the vertical lists but at one point starts jumping back to the top of the list and continues to move down until it jumps up again.

I already filed this bug earlier (please see: https://github.com/microsoft/microsoft-ui-xaml/issues/853) and it was marked as fixed but I'm still able to reproduce the issue.

A demo app to reproduce the issue can be found here: https://github.com/Phranky/ItemsRepeaterDemo

**Steps to reproduce the bug**

1. Download the attached demo app
2. compile it and deploy it to a Xbox One and run it
3. press and hold the down-arrow key on the keyboard or the D-pad down key on the Xbox controller
4. watch the scrolling behavior

**Expected behavior**
fast de-virtualization and smooth scrolling

**Screenshots**

**Version Info**
- WinUI NuGet package version:
- OS version(s): PC: 10.0.18326.295, XboxOne S: 10.0.18362.6065 
- and form factor(s): any

NuGet package version: 
Microsoft.UI.Xaml 2.2.190830001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |     |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      | Yes   |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Please try to reproduce the issue using the following demo app: https://github.com/Phranky/ItemsRepeaterDemo

**Comment by jevansaks** [comment]
We should probably just re-open the old issue in the future but since this is here it's fine. :) @ranjeshj can you take a look?

**Comment by chingucoding** [comment]
@Phranky Can you share a video of this issue? I tried the repo app on my machine and the scrolling seemed to behave correctly.
