### ISSUE TITLE
GamepadView button opens empty pane when PaneDisplayMode is set to Top

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#1353]
**Describe the bug**
NavigationView.PaneDisplayMode is Set to NavigationViewPaneDisplayMode.Top
I'm pressing View button on gamepad.
NavigationView opens it's pane which is empty (because of NavigationViewPaneDisplayMode.Top).

![Screenshot_2019-09-19_04-09-13](https://user-images.githubusercontent.com/3244664/65239181-9a82de80-db08-11e9-9ecf-696dd49d396f.png)

**Comment by jevansaks** [comment]
Thanks for filing this bug, @ad1Dima! What version of the nuget package did you try? Is it a regression from a previous version?

**Comment by ad1Dima** [comment]
Reproduces on 2.2.190917002 

As I can see it there from beginning https://github.com/microsoft/microsoft-ui-xaml/blob/0a1fc4c35fe470dce887cbec6f872b3d2497915c/dev/NavigationView/NavigationView.cpp#L1603

Just nobody thought about it.
