### ISSUE TITLE
Proposal: Add ToggleTheme button to testapp

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1359]
As the title says, we could add an toggle theme button to the test apps.
This would make it easier to test changes with visual styles among multiple themes.

In addition we could maybe create a separate control out of this for WinUI, but I don't think that this is really a control a lot of people would need.

**Comment by jevansaks** [comment]
Just adding some buttons/settings to the test app for this sounds good. Thanks for asking first! :)

**Comment by chingucoding** [comment]
Upon further investigation, I found out that some pages hardcode colors for the UI resulting in a theme switch to make the testing UI completely unusable by e.g. resulting in buttons becoming dark on dark background.

Should we "sanitize" the pages and remove hard coded colors, so that the test app has a more uniform look across the testing pages?

@kaiguo You are working on a VisualTree baseline. Would this changes in the test app (mostly getting rid of non default colors) result in failing VisualTree baseline tests or would this be a safe operation?

**Comment by kaiguo** [comment]
@chingucoding should be fine I think. VisualTree verifications are running as API test, which is separate from the test UI, so they shouldn't be affected by UI changes in test app.

**Comment by chingucoding** [comment]
> @chingucoding should be fine I think. VisualTree verifications are running as API test, which is separate from the test UI, so they shouldn't be affected by UI changes in test app.

Thanks for the clarification!

**Comment by jevansaks** [comment]
> Should we "sanitize" the pages and remove hard coded colors, so that the test app has a more uniform look across the testing pages?

As we find these pages we should clean them up but I wouldn't block this change on completing that cleanup. The pages should work fine initially in Light theme right?

**Comment by chingucoding** [comment]
I just noticed that the acrylic basic page is a bit problematic when changing the requested theme property of the rootgrid. Some parts of the app just have a problem with dynamically changing the theme, but I don't really know where those "stubborn" components come from. Otherwise most pages look good in either theme even when changing.

**Comment by chingucoding** [comment]
Closing this as #1369 was merged into master!
