### ISSUE TITLE
Moving the NavigationView to another Frame makes it unresponsive.

### ISSUE THREAD

**Issue by frankvandeven** [Microsoft/microsoft-ui-xaml#137]
I am using the build 17134 SDK, but the latest Microsoft.UI.XAML 2.0.181018003.1 has the same problem.

When moving the NavigationView to another Frame, the NavigationView menu items cannot be clicked anymore. This means that giving the NavigationView another parent control upsets it. Hovering over menu items still works as I can see the color change.

object temp = Frame1.Content; // content is the NavigationView
Frame1.Content = null;
Frame2.Content = temp;

The problem is odd as other controls can be moved to another Frame without problems.

Placing the NavigationView inside a Grid (for example) does not solve the problem. I also tried placing it in a Grid and do a Grid.Children.Remove() before adding it to another Grid, but also not a solution.

I attached a sample UWP project illustrating the problem.

[NavigationViewPanelTest.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2708379/NavigationViewPanelTest.zip)

**Comment by frankvandeven** [comment]
I also added this issue to GitHub Microsoft/microsoft-ui-xaml

**Comment by jevansaks** [comment]
@frankvandeven this sounds like the same issue as #18, can you take a look and see if you agree?
