### ISSUE TITLE
TeachingTip will block some text content on the second occurrence.

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#1372]
**Describe the bug**
TeachingTip will block some text content on the second occurrence.

**Steps to reproduce the bug**

1. Set IsOpen=true ,IsLightDismissEnabled=true
2. On the first occurence, it's normal. Click some where to dismiss
3. Set IsOpen=true again, some text will be blocked.

**Expected behavior**
Work well

**Screenshots**

![image](https://user-images.githubusercontent.com/42038175/65492564-bb21ae80-dee3-11e9-8aaf-cb2ff19edc34.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
I think I saw this during development but it went away with a selfhost update.  I suspect it is a rendering bug, if I recall correctly the live visual tree seemed to think nothing was wrong.

**Comment by jp-weber** [comment]
I have the problem that no content is displayed at all at the second time, when IsLightDismissEnabled is true.

**Comment by rbwhitaker** [comment]
I had this happen with the XAML Controls Gallery. It is clipping some of the text, but not the first time it comes up. Only subsequent opens. When I restart the app, it works again the initial time, and fails afterwards.

![image](https://user-images.githubusercontent.com/3482875/69906723-0db89480-1385-11ea-88c7-2658ce58b22a.png)

**Comment by zhuxb711** [comment]
Same as @rbwhitaker 
![image](https://user-images.githubusercontent.com/42038175/69908414-e369e400-1423-11ea-87a9-41305712839a.png)

**Comment by jp-weber** [comment]
With the newer preview versions I don't have any problems anymore.

**Comment by zhuxb711** [comment]
if Target={x:Bind  Something} is used, text will be blocked

**Comment by quangaming2929** [comment]
If you hover your mouse on the TeachingTip with Visual Studio XAML Enable Selection, the content will show properly

**Comment by ranjeshj** [comment]
@gegao18 can you please help debug this issue ? @StephenLPeters has looked at it and can provide more context/repro.

**Comment by zhuxb711** [comment]
In the latest pre-release version, this problem still exists and has not been fixed @ranjeshj @gegao18 @StephenLPeters

**Comment by ranjeshj** [comment]
@gegao18 looked at it and found that this is likely an issue in the composition stack. Still being investigated...

**Comment by codendone** [comment]
The issue in the Composition code has been found and fix.  The fix will be in a future release of Windows, but will also be part of WinUI 3.  The workaround done for #2305 will cover other down-level scenarios in the meantime.
