### ISSUE TITLE
AutoSuggestBox does not respect font size

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1373]
**Describe the bug**

When setting the font size property of an AutoSuggestBox, the text inside the AutoSuggestBox does not get rendered with the size specified.
**Steps to reproduce the bug**

1. Create an app with WinUI
2. Copy this inside the mainpage:
```xaml
        <AutoSuggestBox Text="Some text" FontSize="50"></AutoSuggestBox>
```

**Expected behavior**

The text gets rendered in the size specified.
**Screenshots**

![image](https://user-images.githubusercontent.com/16122379/65506772-a4bc2880-decc-11e9-992d-0486694a5583.png)

**Version Info**

NuGet package version: 

>v2.2.190917002 (master branch of WinUI)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18985)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Do ComboBox and other controls with dropdowns pass FontSize through? It's probably right to do it here but I don't know if it's necessarily the right user experience. 

@yulikl @chigy -- thoughts?

**Comment by chingucoding** [comment]
In the case of AutoSuggestBox, I don't think that this is necessary (and my PR currently does not do that). If I recall correctly, one can set the template of the items in the dropdown, so if one would like larger or smaller text one can achieve that for the dropdown by providing a template.

**Comment by chigy** [comment]
@kikisaints , is there a separate knob for updating text size for AutoSuggest drop down area only?

**Comment by YuliKl** [comment]
Here's a quick test using ASB, ComboBox, TextBox and RichEditBox. Looks wrong for ASB to be the only control to ignore its font size.
![image](https://user-images.githubusercontent.com/13142665/65658671-8a25a480-dfdd-11e9-9d2c-b47ccace8477.png)

**Comment by chigy** [comment]
@YuliKl  , agreed. I was expecting that text to grow but the drop down UI would stay small. It would be wrong.

**Comment by jevansaks** [comment]
@chingucoding -- the ASB's control should respect FontSize but we don't think that it should apply to the flyout's items. The ItemContainerStyle can be used to customize that.

**Comment by jevansaks** [comment]
@yulikl mentioned that we should also make sure that the ASB headers pick up this font size.

**Comment by chingucoding** [comment]
@jevansaks, @YuliKl With #1378 , setting the font size (e.g. 50) results in the following:

![autosuggestbox-fontsize-gif](https://user-images.githubusercontent.com/16122379/65800443-cb9d8780-e176-11e9-8135-b1b2587feced.gif)
