### ISSUE TITLE
Application is not supported in a Windows Universal project

### ISSUE THREAD

**Issue by BRyeGmoney** [microsoft/microsoft-ui-xaml#1374]
Howdy,

Brand new to UWP and the UI project and windows c++. I created a new, blank Visual C++ UWP project in VS2017, added the Microsoft.ui.xaml nuget package and received the error: 

> Application is not supported in a Windows Universal project. 
> as well as a ton of other errors that are similar.

Looked up the c++/winrt vs extension. Downloaded that into vs 2017. Created a blank app (C++/winrt) and I get roughly the same errors.

So I then downloaded VS 2019, c++/winrt, started a new Blank project. Make sure that it builds. Add Microsoft.UI.Xaml nuget package and it auto-populates pch.h with:

```
#pragma once
#include <windows.h>
#include <unknwn.h>
#include <restrictederrorinfo.h>
#include <hstring.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Data.h>
#include <winrt/Windows.UI.Xaml.Interop.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Navigation.h>
```

Adding 
```
#include "MainPage.g.h"
```
as per instructions from: [UWP CPP WinUI docs](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/simple-winui-example) just causes errors (102 of them): 

> Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
> Error	C2039	'Microsoft': is not a member of 'winrt'	NotePaddest	C:\Users\bryegmoney\source\repos\NotePaddest\NotePaddest\Generated Files\XamlTypeInfo.g.cpp	216		

and another example error:

> Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
> Error	C3083	'UI': the symbol to the left of a '::' must be a type	NotePaddest	C:\Users\gamef\source\repos\NotePaddest\NotePaddest\Generated Files\XamlTypeInfo.g.cpp	216		

Same errors without the include.

What am I missing to be able to work in UWP and use the UI library? Any help would be appreciated.

**Comment by jevansaks** [comment]
@scott1js @danzil can you help?

**Comment by danzil** [comment]
@BRyeGmoney, when you add a reference to your project, be it from NuGet, Project Reference, or just a winmd reference, cppwinrt.exe runs automatically during build and generates C++/WinRT headers for that reference. You will then need to #include them at the call site (I recommend using pch.h for that). So I think you're missing an #include "winrt/microsoft.ui.xaml.h".

**Comment by BRyeGmoney** [comment]
I'm such a dope. I was actually just missing the specific references to microsoft.ui.xaml.controls and microsoft.ui.xaml.xamltypeinfo. I included them in my vs 2017 attempt to no avail and must have missed that step this time around when the files were actually correctly generated in the winrt folder.

Though winrt/microsoft.ui.xaml.h didn't generate. Thank you very much.

**Comment by danzil** [comment]
Great, I'm glad you're unblocked. Yes, I don't remember the exact header names, I think they're based on namespaces. It's not very intuitive at all that you need to include them. I hope we can teach Visual Studio to automatically help with including references or at least provide a better error or code-fix-up solution.
