### ISSUE TITLE
Remove *_RS1.xaml files

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1375]
Since the WinUI library has RS2 as minimum compatible Windows version, we should get rid of the RS1 files to clean up the project from files that are not needed anymore.

Thanks to @kaiguo for pointing that out [over here](https://github.com/microsoft/microsoft-ui-xaml/pull/1370#discussion_r327366340)!

**Comment by jevansaks** [comment]
Seems like righteous cleanup. On the other hand we'll be getting rid of all of the per-version stuff with WinUI 3.0 so i don't know if it's worth spending *too* much time on it now. If it's causing grief then I'm happy for you (or anyone) to contribute such a fix.

**Comment by kmahone** [comment]
#975 tracks getting rid of ALL the version specific Xaml generation once WinUI 3 is available. But we can get rid of the rs1 variants sooner than that if desired.

**Comment by chingucoding** [comment]
> #975 tracks getting rid of ALL the version specific Xaml generation once WinUI 3 is available. But we can get rid of the rs1 variants sooner than that if desired.

Oh I did not know that. 
@kaiguo, @kmahone : Is there any benefit in working on this issue right now/ before WinUI 3.0?

**Comment by kaiguo** [comment]
> Oh I did not know that.
> @kaiguo Kai Guo FTE, @kmahone Keith Mahoney FTE : Is there any benefit in working on this issue right now/ before WinUI 3.0?

I didn't know we had that either...

I don't see much immediate benefit doing it now compare to doing it later when 3.0 is ready. So we should probably just do it altogether after WinUI 3.

Closing the issue since it's covered by #975.
