### ISSUE TITLE
WebView launches separate process in wrong desktop (HDESK)

### ISSUE THREAD

**Issue by verelpode** [microsoft/microsoft-ui-xaml#1384]
## Describe the bug
When using `WebViewExecutionMode.SeparateProcess`, both of `Windows.UI.Xaml.Controls.WebView` and `Microsoft.Toolkit.Wpf.UI.Controls.WebView` fail to display themselves whenever the app (the app using WebView) is running in any desktop ([HDESK](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw)) other than the default desktop.  In other words, WebView always launches the separate web process ("WWAHost.exe") in the default desktop (the desktop named "Default") whereas the separate web process should be launched in the same desktop as the app using WebView.  

The separate web process creates a `HWND` but this `HWND` fails to appear because it is in the desktop named "Default", whereas the `HWND` can only appear if it is the same desktop as the app using WebView.  The result is that the WebView instance appears as a blank/empty space in the app because this blank space should be overlaid by the web `HWND` but the `HWND` fails to appear because it is not in the same desktop as the app.

Imagine you create two windows (`HWND`).  When you create the second window, imagine that you configure either the parent or "owner" of the second window to be the first window.  Thus the second window is either a child or "owned window" of the first window.   Win32 supports this arrangement, but only if both of the windows are inside the same desktop (`HDESK`).  The first `HWND` is for the app, and the second `HWND` is for the WebView with `SeparateProcess` mode, thus the separate web process fails to create/configure its `HWND` when it is running in a different desktop than the app's `HWND`.

## Steps to reproduce the bug
1. Write a small test UWP (or WPF) app that displays WebView and navigates to a webpage.
2. Create and switch to a new desktop by using [Microsoft SysInternals Desktops v2.0](https://docs.microsoft.com/en-us/sysinternals/downloads/desktops), or by writing your own program that executes the Win32 [CreateDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw) and [SwitchDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-switchdesktop) functions.
3. In the new desktop, launch an instance of "explorer.exe" if not already running.  This instance of the explorer.exe process should be running inside the newly created desktop.  If you're using SysInternals Desktops, then it already launches explorer.exe for you.
4. By using the mouse (meaning this step does not have to be performed programmatically), use the GUI of explorer.exe to launch the aforementioned UWP (or WPF) app that displays WebView and navigates to a webpage.  The explorer.exe instance launches your UWP (or WPF) app in the same desktop as the explorer.exe instance.  Thus your UWP (or WPF) app is launched in the new desktop, not in the default desktop.
5. Observe that the UWP (or WPF) app doesn't crash and doesn't throw any exception, but the WebView remains blank (white) and fails to display the webpage.
6. Observe that the WebView instance did launch an instance of the separate web process ("WWAHost.exe") but in the wrong desktop.  The WWAHost.exe instance is running in the desktop named "Default" instead of the newly created desktop where the app + WebView is located.  

You can use [SysInternals Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to see which desktop a process runs in:
1. Run SysInternals Process Explorer as administrator.
2. Click to select a process in the upper pane (the list of processes).
3. Process details are displayed in the lower pane.  The lower pane is a list with 2 columns named "Type" and "Name".
4. Look for the row in the lower pane that says "Desktop" under the column named "Type".  The name of the desktop is displayed in the second column.

![image](https://user-images.githubusercontent.com/32857007/65784327-1658d880-e152-11e9-9710-0bea467f2c27.png)

Note that the bug cannot be reproduced by using the so-called "desktops" feature that is available by clicking the "Task View" icon located immediately right of the Start menu icon in Windows 10 (Pro and Enterprise).  That feature does not create the same kind of "desktop" as what the Win32 [CreateDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw) function creates.  I think the "desktops" in "Task View" operate by hiding and showing windows, not by creating `HDESK` instances.  Thus WebView experiences no problems with multiple "desktops" created via "Task View".  In contrast, in kiosk environments and certain enterprise environments and in certain [Remote Desktop Services](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/welcome-to-rds) scenarios etc, multiple `HDESK` desktops may exist and this is where WebView fails.
![image](https://user-images.githubusercontent.com/32857007/65784411-40aa9600-e152-11e9-8e4c-5938c4bb8be0.png)

## Expected behavior
WebView (or `Windows.Web.UI.Interop.WebViewControlProcess` if applicable) needs to check what desktop the current app is inside (invoke [GetThreadDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getthreaddesktop)), and ensure that the separate web process ("WWAHost.exe") is launched in that same desktop, instead of always launching in the default desktop.

Before `WebView` or `WebViewControlProcess` launches the separate web process, it should:
1. Invoke the Win32 [GetThreadDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getthreaddesktop) function in order to determine which desktop the current app is running inside.  
2. Launch the separate web process in the same desktop as what `GetThreadDesktop` returns, by invoking the [CreateProcessWithTokenW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw) or [CreateProcessAsUserW](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessasuserw) function.  Set the [STARTUPINFOW.lpDesktop](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfow) field of the struct passed to the `lpStartupInfo` parameter of [CreateProcessWithTokenW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw) or [CreateProcessAsUserW](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessasuserw).
3. Consider also invoking [GetCurrentProcessToken](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocesstoken) at the same time as [GetThreadDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getthreaddesktop), in order to help solve the other bug where WebView + `WebViewExecutionMode.SeparateProcess` fails when the app is run as a different user, such as when the app is run as administrator.  i.e. WebView should launch the separate web process with the same user/access token and same desktop as the app using WebView.  (See also [windows-toolkit/Microsoft.Toolkit.Win32#13 "WebView can't run as administrator"](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/13).)

Ideally, if possible, WebView should not fail when explorer.exe is only running in the default desktop and not in the other desktop.  I suggest the following solution to avoid creating a new requirement for explorer.exe to run in other desktops:
1. The same as currently done, when an app uses WebView, WebView should continue to always communicate _only_ with the instance of explorer.exe in the default desktop, regardless of which desktop the app is in.  (That's what it already does currently, and this part would remain unchanged.)
2. Therefore WebView wouldn't care whether explorer.exe instances are running in other desktops because WebView would _only_ communicate with the explorer.exe instance in the default desktop.
3. The separate web process should be launched in the same desktop as the app using WebView, regardless of the fact that WebView always communicates only with the default explorer.exe in the default desktop.
4. Thus WebView wouldn't fail when the app runs in a non-default desktop where NO explorer.exe instance is running, provided that the default explorer.exe instance is running as normal in the desktop desktop.

## Additional context
Reasons why an app may be running in a non-default desktop (`HDESK`) include:
* Kiosk environments.  (We produce kiosk software.)
* Digital Signage (AKA "e-sign") environments (note e-sign computers may also put the OS in a kiosk mode).
* Special enterprise environments or any environment where security needs to be increased by running a program in a different desktop.
* Certain [Remote Desktop Services](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/welcome-to-rds) scenarios, depending on configuration.
* ["Desktop virtualization"](https://en.wikipedia.org/wiki/Desktop_virtualization).  See also [Citrix Systems](https://en.wikipedia.org/wiki/Citrix_Systems).
* A screensaver/idle-time program running in the Windows screensaver desktop.
* A program running in the Windows "Lock Screen" desktop (Windows already supports the ability for processes or tiles to display some info in the "Lock Screen").

## Version Info
| Info | Value |
| :--- | :--- |
| Windows 10 Version: | 1903 (Build 18362.267) |
| App min and target version: | 1903 |
| Device form factor: | Desktop |
| Visual Studio: | 2019 |
| WebView-for-WPF version: | 6.0.0-preview7.1 |

## See Also
* [windows-toolkit/Microsoft.Toolkit.Win32#166 "WebView launches WWAHost in the wrong desktop (HDESK)"](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/166)
* [windows-toolkit/Microsoft.Toolkit.Win32#13 "WebView can't run as administrator"](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/13)
* ["WebView prevents app exit when explorer.exe is not running" #1253](https://github.com/microsoft/microsoft-ui-xaml/issues/1253)

**Comment by verelpode** [comment]
@Austin-Lamb @adambarlow

**Comment by Austin-Lamb** [comment]
@verelpode - Would you be able to use in-proc WebView (ExecutionMode set to SameThread or SeparateThread)?  If not, could you explain more about why you need to use out-of-proc for your scenario?

**Comment by verelpode** [comment]
@Austin-Lamb -- Here's [a link to a message](https://github.com/microsoft/microsoft-ui-xaml/issues/1253#issuecomment-535933983) in the other issue where I've answered that question.

**Comment by adambarlow** [comment]
As we move to invest in Webview 2 we will not be addressing this issue in the existing EdgeHTML Webview. 

Please feel free to file a suggestion for the capability you want to see in Webview 2 here:
https://github.com/MicrosoftEdge/WebViewFeedback

**Comment by adambarlow** [comment]
@verelpode I am re-opening this issue to ensure you get a notification here (I'll close it again at the end of the week). We honestly appreciate all the work you have done here.

We are working on a new Webview and would really appreciate your feedback. Also when we have a preview available of the WinUI Webview, we will reach out so you can be an early validator for your scenarios.

Please do engage with the Webview team here:
https://github.com/MicrosoftEdge/WebViewFeedback

We'd love to continue to receive your feedback.

**Comment by verelpode** [comment]
@adambarlow
> We are working on a new Webview and would really appreciate your feedback. Also when we have a preview available of the WinUI Webview, we will reach out so you can be an early validator for your scenarios.

Thanks!  We're eager to start testing the WebView2/Chromium XAML Control as soon as it's available for preview testing in C# apps.  ASAP, we wish to upgrade our software at many locations across the USA to use the new WebView when it's ready and experiences no more problems in the lab environment.  Based on client requirements, the web control is a very important and essential component in our case, used hundreds of times every day of every week (literally every day; even Sundays in the case of 24/7/365 factories).  

However, when some critical functionality is missing or made unavailable via sandbox/security restrictions etc, the resulting jigsaw puzzle is challenging to solve, in my experience.  For example, a client says, _"We can't deploy until staff members can download documents from enterprise website XYZ"_, but website XYZ requires session cookies, but those session cookies are unavailable to `HttpClient` because WebView is running in a separate process, which could be solved by running WebView in the same process, except that the same-process mode is unsupported in WebView-for-WPF, which could be solved by using WebView-for-UWP, except that `HKEY_LOCAL_MACHINE` (or likewise) is unavailable in UWP but necessary in the kiosk/enterprise environment.  Therefore the jigsaw puzzle is challenging to solve, especially considering that the Windows programming and security rules make it impossible to implement our software as a single monolithic program.

Thus, one way or another, we're eager to test new versions of either WebView2/Chromium or EdgeHTML-for-UWP or EdgeHTML-for-WPF, in order to find a way of solving the jigsaw puzzle.  Yes WebView2/Chromium has the potential for solving everything, if the final version isn't missing anything critical such as cookie access.   I'll be very happy when the day eventually arrives when I can say that we have `System.Windows.Controls.WebBrowser` running at zero remaining locations in the USA.
