### ISSUE TITLE
ItemsRepeater throws AccessViolationException when DataTemplateSelector returns empty DataTemplate

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#1385]
**Describe the bug**
I got `AccessViolationException` when return new `DataTemplate()` from `DataTemplateSelector`. `ListView` and `GridView` deals well with it by just rendering nothing, but `ItemsRepeater` throws Exception.

**Expected behavior**
Do not throw Exception, just don't render this item.

Main case is when you get heterogeneous list of items filled from server, you can use `DataTemplateSelector` to choose how it will be rendered. Some unsupported items you can use empty `DataTemplate`

**Version Info**
NuGet package version: 
WinUI version 2.2.190830001.

**Additional context**
this issue follows #776
My guess is that `AccessViolation` appears here as `selectedTemplate.LoadContent()` returns `null`.

**Comment by ad1Dima** [comment]
I think, you can just return any `Panel` (`Grid` for ex.) if `selectedTemplate.LoadContent()` returns `null`

**Comment by jevansaks** [comment]
@ranjeshj was commenting in the PR that this might cause estimations to be weird and to de-virtualize a bunch of items that otherwise wouldn't need to be. I think it might require a bit more design thought?

**Comment by ad1Dima** [comment]
If template will be empty grid it'll also cause de-virtualize. 
But if DataTemplateSelector will return zero-sized element only in rare cases everything must be ok.

There is a lot of cases where developer can de-virtualize virtualization controls. Let it be up to him.

**Comment by ranjeshj** [comment]
@chingucoding, this seems like a reasonable thing to do in the data template selector case - if you want to pick it up. When creating views, we just need to return an empty element in this case.

**Comment by chingucoding** [comment]
> @chingucoding, this seems like a reasonable thing to do in the data template selector case - if you want to pick it up. 

Sure thing! I still have other issues that I will fix prior to this, but I would happily provide a fix for this.

> When creating views, we just need to return an empty element in this case.

@ranjeshj Any guidance on what element we should return, to prevent possible side effects and keep the performance foot print of that item low?

**Comment by ranjeshj** [comment]
I think perhaps a Rectangle would suffice.
