### ISSUE TITLE
Proposal: Change NavigationView.PaneTitle type to object

### ISSUE THREAD

**Issue by Tirraon** [microsoft/microsoft-ui-xaml#1390]
# Proposal: Change NavigationView.PaneTitle type to object

## Summary
It is not possible to use any kind of custom control in PaneTitle like TextBlock with custom Run  or ComboBox. We can set only plain string.

## Rationale
* Adds more customization to NavigationView

## Scope
| Capability | Priority |
| :---------- | :------- |
| Allow to use any control as PaneTitle | Must |
| Create style key for PaneTitlePresenter, so devs can replace it | Could |

## Important Notes
Usage example:
```xaml
<NavigationView>
   <NavigationView.PaneTitle>
      <TextBox x:Name="PaneTitleTextBox"/>
   </NavigationView.PaneTitle>
</NavigationView>
```

## Open Questions
It is breaking change for users, who read PaneTitle to string fields. So can we break their code?

**Comment by mdtauk** [comment]
You could also use a ContentPresenter, similar to other controls like the Button

**Comment by Tirraon** [comment]
@mdtauk PaneTitlePresenter is already ContentControl.
Or do you mean about possibility to set Template for PaneTitle object?

**Comment by jevansaks** [comment]
Looks like we added PaneHeader which is mutually exclusive with PaneTitle (you can't set both and they appear in the same place). That said, looks like PaneHeader is UIElement not object so it may still not be what you expect -- but you should be able to put arbitrary content in not via a DataTemplate. Hope this helps!

**Comment by Tirraon** [comment]
@jevansaks 
My bad, I didn't found PaneHeader before.
Thanks!
