### ISSUE TITLE
Regression: NavigationView pane is missing shadow

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1394]
**Describe the bug**

When open in Minimal or Compact display modes, NavigationView should draw a shadow behind its open pane. The shadow is present in WinUI 2.2.190702001-prerelease and missing in 2.2.190731001-prerelease.

**Steps to reproduce the bug**

1. Create a new test app and add `<muxc:NavigationView></muxc:NavigationView>` into MainPage.xaml
2. Run the app and resize its window to a narrow width
3. Press the hamburger button to open the pane

**Expected behavior**

Pane opens and draws a shadow.
![image](https://user-images.githubusercontent.com/13142665/65933556-c8003f80-e3c6-11e9-869c-600c448e9d68.png)

**Screenshots**

In recent WinUI versions, there's no shadow.
![image](https://user-images.githubusercontent.com/13142665/65933543-b9198d00-e3c6-11e9-8791-5414ad893828.png)

**Additional context**

Double-checked with @chigy that this is a regression.

**Comment by jevansaks** [comment]
@chingucoding do you want to take a look at this one?

**Comment by chingucoding** [comment]
Sure, I will see what I can do.
