### ISSUE TITLE
TeachingTip Title takes space even when there is no content.

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#1396]
When the tips Title content is set to null the remaining content still lays out as if there were text in the title.

**Comment by chingucoding** [comment]
I looked into this, and I found no way to solve this with retemplating. A possible solution would be to check if the Title is empty and update the height using code behind. But that, in my opinion, is not the best solution.

**Comment by jevansaks** [comment]
@StephenLPeters do you have a recommendation for the fix?

**Comment by StephenLPeters** [comment]
I think that title = null is a pretty strong indication that we should collapse the text block which displays that title.  We could make a string to visibility converter to declare this in markup, I don't think making this check from code behind is outlandish though.

**Comment by chingucoding** [comment]
Was the bug fix already released in the latest preview of WinUI?
If not the issue might not be fixed completely as it seems like the subtitle still takes up space even when nothing is specified in my project https://github.com/chingucoding/UWP-Resources-Gallery on the SystemColors page.

**Comment by ranjeshj** [comment]
This change should be in the recent pre-release. @StephenLPeters can you please take a look ?

**Comment by chingucoding** [comment]
@StephenLPeters Can I look into this issue or are you currently looking into this?

**Comment by StephenLPeters** [comment]
I'm not, please take it :)
