### ISSUE TITLE
Discussion: So, Windows 10 X... Time to talk about the dev and insider story?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1399]
# Discussion: Windows 10 X + WinUI

Windows 10 X has been demoed and outed.  Can work be ramped up on Win UI and supporting this new OS and UX.  Dev docs, SDKs, Insider builds, Demos, Samples, etc.

What kinds of devices this new shell will run on, and what new patterns and workflows are needed for a world without File Explorer, Taskbar Trays, Live Tiles, etc.

![image](https://user-images.githubusercontent.com/7389110/66077844-ba7abf00-e558-11e9-8262-5750185d2982.png)

## Related Links
[Introducing Windows 10X: enabling dual-screen PCs in 2020](https://blogs.windows.com/windowsexperience/2019/10/02/introducing-windows-10x-enabling-dual-screen-pcs-in-2020/)

**Comment by kmgallahan** [comment]
> for a world without File Explorer

There is a File Explorer icon in the image you linked.

No indication yet if the system tray will still be around or not.

Otherwise, the majority of the work appears to be in the shell which will handle all the window management (positioning/snapping/expanding).

The "Wonder Bar" is the main thing that needs new interaction APIs. Otherwise I presume we'll be using the new AppWindow API to create apps with interdependent, non-spanned windows.

**Comment by mdtauk** [comment]
I would guess there would be a modern and simplified File Explorer built with XAML for this new device/SKU - At least I would hope so, as this is a rethink of the OS UX.

**Comment by ryandemopoulos** [comment]
Hey folks!  There's a lot of excitement (and fun speculation) on these new devices and Windows 10X; I think we'll soon have more we can share on the WinUI / development implications for these devices.

**Comment by robloo** [comment]
Looking forward to hearing what is planned for developers around these new devices / UI experiences. I'm especially curious to see how we are expected to handle splitting the same app in two windows across screens. That's potentially going to change a lot in how apps are designed and I'm actually hoping it's an opt-in feature that apps can disable.

**Comment by DragoCubed** [comment]
I just keep thinking of the Nintendo DS consoles.

**Comment by pag3** [comment]
We will be rolling out more detailed information about developing for Windows 10X and dual screen devices over the coming months, eventually including builds, sdks, docs, samples, etc.

Astute observers of the [Surface Neo video](https://www.youtube.com/watch?v=fssZICsV4Rg) who may have noticed use of Fluent Design System and WinUI-based experiences. :)

If you want to take actions now to prepare for the opportunity Windows 10X provides, I'd say that following our [Fluent Design Guidelines for Windows](https://docs.microsoft.com/en-us/windows/uwp/design/) and other best practices for Windows 10 app development today - including things like being responsive to window sizes, working well with all inputs including touch and pen, and making use of standard controls where available - are all things that make sense to do that will accrue to help your app shine not only on Windows 10 but also on Windows 10X.

**Comment by sharpninja** [comment]
Will NavigationView be expanded to allow for two Frames which can be oriented side-to-side or top-and-bottom by the developer (and swap as the device is rotated)  It would be good for a NavigationView to treat both displays individually while also being able to apply a menu or command bar(s) across the top as a single app spanning both displays.
