### ISSUE TITLE
Performance issue for debug builds

### ISSUE THREAD

**Issue by COM8** [Microsoft/microsoft-ui-xaml#14]
**Describe the bug**
If I'm building my app in debug mode it takes up to 20s to start.
In release mode this is reduced to only 2-3s

**Steps to reproduce the bug**
1. Add the Microsoft.UI.Xaml NuGet package
2. Build the app in debug mode

**Expected behavior**
Better startup performance in debug mode.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.0.181018003

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [x] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [x] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by ranjeshj** [comment]
Hi,
    I am not seeing the 20 second delay you mention in debug build in a blank cs app with a colorpicker even if I edit the files. Can you provide more details on what you have in your project ? Does Visual studio mention what it is doing during those 20 seconds? 

Thanks,
Ranjesh

**Comment by COM8** [comment]
I've created a new empty project with just the "Microsoft.UI.Xaml" NuGet library.
And these are the start delays I've measured:

| Desktop | Mobile | Microsoft.UI.Xaml installed |
|---|---|---|
| 3.5s | 12s | Yes |
|  <1s  | 5s  | No |

```XML
<Application x:Class="AcvMemTest.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!--  Windows UI Library:  -->
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

</Application>
```

**Comment by ranjeshj** [comment]
Unfortunately I am still unable to repro this delay. Can you please do the build with/without the nuget package and get WPA traces ?

**Comment by COM8** [comment]
The way I'm measuringthe performance is:
1. Build the app in debug mode
2. Publish the app
3. Start it via the start menu

I sadly can't reproduce it any more...
Also my other apps where I'm using microsoft-ui-xaml are now somehow faster again.

Silly idea but could this be caused by Visual Studio, because the only thing I've changed since the last test is my VS version from `15.7.x` to `15.9.2`?
In generall I now experience apps starting much faster that got build in `debug` configuration on my PC and Phone (Lumia 950XL)?

I think you can see this issue as done. I will reopen it again if I can reproduce it again :D

Thanks for your help!

**Comment by jevansaks** [comment]
Thanks for the follow up! That's great news. I would not be surprised if the newer VS fixed it. Also we have all been using VS 15.8.* for some time so that's possibly why we didn't see the issue as you were seeing it. 

Please let us know if you see this again.
