### ISSUE TITLE
CalendarView group labels overlap with day number text

### ISSUE THREAD

**Issue by kikisaints** [microsoft/microsoft-ui-xaml#140]
**Describe the bug**
When you enable the IsGroupLabelVisible boolean on the CalendarView control, the month labels overlap with the day number.

**Steps to reproduce the bug**
Create an app and put a CalendarView in it. Enable the IsGroupLabelVisible bool.

```XAML
<CalendarView IsGroupLabelVisible="True"/>
```
Observe the overlapping text.

**Expected behavior**
No overlapping text.

**Screenshots**
![image](https://user-images.githubusercontent.com/6964369/50610568-4eafdc80-0e88-11e9-96b7-a117783741f1.png)

**Version Info**

NuGet package version: 
prerelease

Windows 10 version:
- [x] Insider Build (18309)

Device form factor:
- [x] Desktop

**Comment by YuliKl** [comment]
Is there a visual design for where the labels ought to go?
