### ISSUE TITLE
Tooltip shadow should be applied at 16px not 32px

### ISSUE THREAD

**Issue by chigy** [microsoft/microsoft-ui-xaml#1401]
**Describe the bug**
As described in our [Z-depth and shadow doc](https://docs.microsoft.com/en-us/windows/uwp/design/layout/depth-shadow#themeshadow-in-common-controls), tooltip should be applying shadow at 16pt not at 32pt. The shadow is overly heavy today and it is not per intended design.

**Comment by chrisglein** [comment]
ToolTip calls the elevation helper without setting a depth, giving it the default of 32. There's no way to give a value of 16 today through that API (it takes a uint depth, where 1 starts at 32), but it'd be easy to mod to get a different value. Regardless, this will require WinUI as the elevation calls in all those controls are hard coded into the control logic, not themeable.

**Comment by mdtauk** [comment]
When Tooltip is added to the repo, you may want to consider liasing with the Edge, Win32 Shell, and Office teams, and try to get a consistent look for ToolTips across apps.

**Comment by Poopooracoocoo** [comment]
any updates on this? would be neat if this could make it to v2.5 :)

**Comment by chingucoding** [comment]
Unfortunately almost all of the Tooltip code still sits in the OS right now, which means many changes to tooltip, including this issue, can only be done inside the OS or with WinUI 3. That's also why it is marked as "needs-winui-3".

**Comment by Poopooracoocoo** [comment]
Can this be closed? Are WinUI 2 and UWP now in maintenance mode?

**Comment by chrisglein** [comment]
This issue stands as it has before. It's unfixable in WinUI2. It could potentially be fixed in WinUI3+, but hasn't yet. Low priority relative to other things happening in WinUI3 currently.
