### ISSUE TITLE
Keyboard accelerator text is not shown if different types of items are added to a MenuFlyout

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#1407]
**Describe the bug**

When the KeyboardAccelerator property of a MenuFlyoutItem is set, the corresponding keyboard combination text will be shown on the right side of the item. This works correctly if only standard MenuFlyoutItem objects are added to a MenuFlyout. However, if additional items of a different type (e.g. the winui RadioMenuFlyoutItem) are added, only the text for the first item is shown.

**Steps to reproduce the bug**

Add a MenuFlyout (e.g. as the ContextMenu property of a control) and add different menu items with keyboard accelerators.

**Expected behavior**

The text for the keyboard accelerators is shown for every item

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml v2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@llongley this sounds like a bug you just fixed in System XAML, is that correct?

**Comment by llongley** [comment]
Fix checked into WinUI 3.0 branch.
