### ISSUE TITLE
Question: What is going to be in WinUI 3?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#1412]
I've looked, but I can't find details of what's going to be included in WinUI 3. Is there a public list anywhere?

Ideally I'd like a list of controls, and "other" things.

----
Background: I was looking at some of the issues with the [DataGrid in the Community Toolkit](https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid) but am not clear if it's worth investing time there. My recollection (I can't find evidence to back this up) was that the toolkit control was a quick port of the old Silverlight version and released as a temporary stop-gap until an "official" one was related at a later time. That the code for that control has hardly been touched in a year helps reinforce my memory. WinUI 3 seems like a great opportunity to add this control but there's nothing to say it's definitely coming.
Beyond this control, there are also other 3rd party and open source controls and tools/helpers that could be made redundant by WinUI 3. Knowing what will be included could help avoid wasting time contributing to things that have a very short future.

**Comment by kmgallahan** [comment]
Per: https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md

**New Features in WinUI 3.0**

Our primary focus for WinUI 3.0 is to decouple the UWP UI framework (Xaml, composition and input) while maintaining high compatibility with existing UWP APIs and behaviors to help make the update to WinUI 3.0 easy for existing UWP apps.

This means we won't be adding many new features in the first WinUI 3.0 release.

However, we are planning at least a few new features, including:

1. Downlevel support (backward compatibility) for all existing features: new Xaml and Composition features that were added in the Windows May 2019 Update will now work on Creators Update and newer!
2. A new Microsoft Edge (Chromium) WebView Xaml control
3. Input validation support
4. New Visual Studio 2019 app templates for different combinations of app type (Win32, UWP) and language (C#, C++)

**Comment by mrlacey** [comment]
Thanks Kevin.

Regarding point 4. Will the new templates be open-sourced before they're released? I have some strong thoughts about the current ones that I've tried to address through Windows Template Studio and would love to give feedback to the standard templates too.

**Comment by kmgallahan** [comment]
> would love to give feedback to the standard templates too.

Unsure if they will be open source.

Templates were one of the focuses of the **WinUI 3.0 Developer Experience and Tooling - Input Needed** issue: https://github.com/microsoft/microsoft-ui-xaml/issues/1045

I see you already commented on that issue, but anyways - from the Templates section:

Open Question(s)

- Is there interest/need for the previous versions of UWP XAML templates to remain in VS new project flow?
- **How can we help you be more efficient or successful with regards to templates and components in Visual Studio?**
- Is this walk through helpful and would you like to see more of this as scenarios take shape?

**Comment by jevansaks** [comment]
The roadmap that @kmgallahan shared above captures our plan. Basically we're taking OS XAML as-is, trying to preserve whatever's there as much as possible. We aren't really planning any new features in that move outside of what you already see being worked on in this repo in parallel with that effort.

Going forward we want to continue to migrate the popular/successful things from the toolkit into WinUI, including DataGrid. We don't have formal plans for DataGrid at this time but I was just talking to @harinikmsft and @rbrid about this and we'll hopefully be able to put together a plan for it after WinUI 3.0 ships.
