### ISSUE TITLE
DispatcherHelper constructor throws expected exception, creates developer confusion

### ISSUE THREAD

**Issue by oldnewthing** [microsoft/microsoft-ui-xaml#1414]
**Describe the bug**

When used in a Win32 (non-UWP) app, `DispatcherHelper`'s constructor raises and immediately catches an exception. This breaks into the debugger as a first-chance exception, causing developer confusion.

#### Details

The DispatcherHelper constructor [uses a try/catch](https://github.com/microsoft/microsoft-ui-xaml/blob/0e3c0ee916ac7bdbbb311613e793594ae395c7d7/dev/inc/DispatcherHelper.h#L20) to anticipate the exception thrown by `CoreApplication::GetCurrentView()` in the case where the host app is not a UWP app. For example, the host app could be a Win32 app using XAML islands.

Although the exception is handled, the fact that an exception is thrown at all causes Visual Studio to break into the debugger, and the developer must Continue past it. The developer could avoid the problem by configuring Visual Studio to ignore first-chance exceptions, but this forces the developer out of their preferred workflow to accommodate a platform issue.

In particular, the developer may not even realize that they are using XAML islands. As an example, [a plain Win32 app that calls `CredUIPromptForWindowsCredentials` encounters this unexpected exception](https://stackoverflow.com/q/58095555) because CredUI uses XAML to present its credentials dialog. The Win32 developer is unaware of this implementation detail. They see an exception and fear that they did something wrong.

In this specific case, we sent the developer on a wild goose chase trying to debug the exception, unaware that the exception is not something to be concerned about. This wastes the developer's time.

Even in the case where the developer is consciously using XAML islands, the spurious exception will lead the developer down the wrong path when trying to debug why their XAML islands are not working.

Suggest removing the `try/catch` and switching to
```cpp
winrt::CoreApplicationView TryGetCoreApplicationCurrentView()
{
    winrt::CoreApplicationView view{ nullptr };
    winrt::get_activation_factory<winrt::CoreApplication, ABI::ICoreApplication>()
        ->GetCurrentView(put_abi(view));
    return view;
}
```

```cpp
        if (!dispatcherQueue)
        {
            if (dependencyObject)
            {
                coreDispatcher = dependencyObject.Dispatcher();
            }
            else if (auto currentView = TryGetCoreApplicationCurrentView())
            {
                coreDispatcher = currentView.Dispatcher();
            }
        }            

```
**Steps to reproduce the bug**

1. Write a Win32 app.
2. From the Win32 app, call `CredUIPromptForWindowsCredentials()`.

**Expected behavior**
3. No spurious exception.

**Version Info**

This problem has existed since the `DispatcherHelper` constructor was introduced in 1809.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes  |
| April 2018 Update (17134)          | No  |
| Fall Creators Update (16299)       | No |
| Creators Update (15063)            | No |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   | N/A  |
| Xbox                      | N/A  |
| Surface Hub          | N/A  |
| IoT                         | N/A  |

(N/A because issue requires an OS that supports XAML islands.)

**Additional context**

**Comment by kmahone** [comment]
This has been merged to master. Currently working on porting it to the OS.

**Comment by kmahone** [comment]
Checked in to the OS now.

**Comment by StefanJKern** [comment]
Hi,
thank you for fixing this bug. It actually took me half an hour to realize the exception is not causing my crash. 

But I am having a crash succeeding this exception which occured in code that worked for 2 years after upgrading from 1803 to 1903 (problem persists in 1909) in our Visual C++ Application (compiled with vc12).
It almost always crashes after entering (valid or invalid) credentials in `CredUIPromptForWindowsCredentialsW`. At least if you try it three times.

The first of numerours exceptions in SHCore.dll before the application finally crashes is
Exception thrown at 0x00007FFE32D3A839 in SpecsLabProdigy.exe: Microsoft C++ exception: Platform::InvalidCastException ^ at memory location 0x00007FF423A6BF70. occurred

Final crash message from windows event log:
Faulting module name: KERNELBASE.dll, version: 10.0.18362.449, time stamp: 0x2bdaa583
Exception code: 0xe06d7363


Any insight would be higly appreciated.

Best Stefan

[CallStack_InvalidCastException.txt](https://github.com/microsoft/microsoft-ui-xaml/files/3874974/CallStack_InvalidCastException.txt)

**Comment by jevansaks** [comment]
@StefanJKern This sounds like a different issue, could you open a new issue to track it? Also please attach a simplified repro project or a crash dump at the point of the call stack (you can save one from visual studio's Debug menu) when you do. Thanks!

**Comment by StefanJKern** [comment]
@jevansaks Thanks for your feedback. I opened #1662 for this issue.
