### ISSUE TITLE
Close button in TabViewItem becomes visible on changing Visibility property

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#1416]
**Describe the bug**

When toggling the Visibility property from Collapsed to Visible (in a async continuation), the close icon will appear in the TabViewItem, even when IsClosable is set to False.

**Steps to reproduce the bug**

Given the following XAML:
```
<tk:TabViewItem  x:Name="tabViewItem" Header="Test" IsClosable="False">
</tk:TabViewItem>
```
Use this code in the code behind:

```
protected async override void OnNavigatedTo(NavigationEventArgs e)
 {
        tabViewItem.Visibility = Visibility.Collapsed;
        await Task.Delay(1);
        tabViewItem.Visibility = Visibility.Visible;
}
```
The close button is visible, even when the tab item is not closable.

**Expected behavior**
The close button should always be collapsed when the IsClosable property is set to False, independent of the Visibility property.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |  Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
Is OnApplyTemplate running again? Seems like we must be skipping a GoToState call somewhere.

**Comment by MartinZikmund** [comment]
I would love to take a look at this one

**Comment by jevansaks** [comment]
Sure @MartinZikmund I'll assign to you (assuming that's what you meant)!

**Comment by MartinZikmund** [comment]
That's what I meant 😉

**Comment by MartinZikmund** [comment]
I'm sorry I didn't get to this earlier. Seeing this is now being implemented, I will unassign myself
