### ISSUE TITLE
Binding to ItemsSource with UserControl as DataTemplate not displaying correctly

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1417]
**Describe the bug**

When using a component that can render using ItemsSource and ItemTemplate, UserControls do not get the object using binding correctly. Instead of every entry in the list rendering correctly, items that are not visible during setting of the ItemsSource do not get the item set correctly but instead receive null.
**Steps to reproduce the bug**

1. Create a UserControl with custom DependencyProperty:
```c#
ublic partial class MyAwesomeUserControl : UserControl
    {

        // Creating dependency property for XAML assignment
        public static readonly DependencyProperty MyNameProperty =
            DependencyProperty.Register(
                "MyName",
                typeof(string),
                typeof(MyAwesomeUserControl),
                new PropertyMetadata(default(string)));

        public string MyName
        {
            get
            {
                return (string)GetValue(MyNameProperty);
            }
            set
            {
                SetValue(MyNameProperty, value);
                MyNameChanged();
            }
        }

        public MyAwesomeUserControl()
        {
            this.InitializeComponent();
            this.Loaded += MyAwesomeUserControl_Loaded;
        }

        private void MyNameChanged()
        {
            if (MyName != null)
            {
                MyNameTextBlock.Text = MyName;
            }
            else
            {
                Debug.WriteLine("item null");
            }
        }
        private void MyAwesomeUserControl_Loaded(object sender, RoutedEventArgs e)
        {
            MyNameChanged();
        }
```
2. Create a ListView and add template with UserControl as template:
```xaml
        <ListView x:Name="ItemsListView" Height="500" Width="500">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <local:MyAwesomeUserControl MyName="{Binding}"/>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```
3. Set source in code behind:
```c#
        private IList<string> items = new List<string>();

        public MainPage()
        {
            this.InitializeComponent();

            for (int i = 0; i < 100; i++)
            {
                items.Add(i.ToString());
            }
            ItemsListView.ItemsSource = items;
        }
```
**Expected behavior**
All elements in list get rendered correctly and every UserControl has the binding set correctly (and not get null passed to it).

**Screenshots**

Note that the List in code behind consists of the numbers 1 to 500.
![binding-bug](https://user-images.githubusercontent.com/16122379/66432281-fc56aa00-ea1d-11e9-80c3-20cf0939c51e.gif)
**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18995)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Demo repository:
https://github.com/chingucoding/BindingProblem

This also seems to apply to GridView. The number of items does not seem to make a difference, as long as some items are not visible.

**Comment by MikeHillberg** [comment]
Changing the value of a DependencyProperty doesn't always happen through the property setter, so raising MyNameChanged in there isn't reliable. For example {Binding} sets the DependenyProperty directly ({x:Bind}, on the other hand, calls the property setter).

The solution is in the DependencyProperty.Register, use the [version of the PropertyMetadata constructor that takes a property changed callback](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.propertymetadata.-ctor#Windows_UI_Xaml_PropertyMetadata__ctor_System_Object_Windows_UI_Xaml_PropertyChangedCallback_).

**Comment by chingucoding** [comment]
Oh I did not know that! 😅 

Using your fix It works perfectly! Thanks for the answer!
