### ISSUE TITLE
Question: How to programmatically assign a value to the TreeView's SelectedItem property?

### ISSUE THREAD

**Issue by dpaulino** [microsoft/microsoft-ui-xaml#1420]
I want to programmatically assign a value to the TreeView's `SelectedItem` property. I assumed that `TreeView.SelectedItem = myObject` would work, but it seems to crash. Here's a blank UWP project I just created, and it crashes when I assign a string. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/7649589/66546820-a6076b00-eaf2-11e9-98be-fa5b19b5480d.png)

**Comment by jevansaks** [comment]
Can you provide more of the repro? Is "hello world" an object in your ItemsSource? 

Is your expectation that the call would silently do nothing since the item isn't present?

**Comment by jevansaks** [comment]
Looks like the discussion moved to #386.
