### ISSUE TITLE
ItemsRepeater layout fails after BringIntoView with CacheLength = 0

### ISSUE THREAD

**Issue by grokys** [microsoft/microsoft-ui-xaml#1422]
**Describe the bug**

Scrolling to a specific item in an `ItemsRepeater` breaks if `HorizontalCacheLength`/`VerticalCacheLength` is set to 0.

**Steps to reproduce the bug**

Create an `ItemsRepeater` with a horizontal/vertical cache length of 0 and a button to scroll to the last item:

```
<Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Button Name="end" Click="end_Click">End</Button>
        <ScrollViewer HorizontalScrollBarVisibility="Disabled"
                      VerticalScrollBarVisibility="Auto"
                      Grid.Row="1" Width="250" Height="350">
            <Border Background="LightBlue">
                <controls:ItemsRepeater x:Name="repeater"
                                        VerticalCacheLength="0"
                                        HorizontalCacheLength="0">
                    <controls:ItemsRepeater.ItemTemplate>
                        <DataTemplate>
                            <Border BorderBrush="Red" BorderThickness="1">
                                <TextBlock HorizontalAlignment="Stretch" Text="{Binding}"/>
                            </Border>
                        </DataTemplate>
                    </controls:ItemsRepeater.ItemTemplate>
                </controls:ItemsRepeater>
            </Border>
        </ScrollViewer>
    </Grid>
```

```
    public sealed partial class BasicDemo : Page
    {
        public BasicDemo()
        {
            this.InitializeComponent();
            repeater.ItemsSource = Enumerable.Range(0, 10000).Select(x => x.ToString()).ToList();
        }

        private void end_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
        {
            var element = repeater.GetOrCreateElement(9999);
            element.UpdateLayout();
            element.StartBringIntoView();
        }
    }
```

Run the app and click the "End" button. The list is scrolled to the end but only the final two items are displayed:

![image](https://user-images.githubusercontent.com/1775141/66566142-801aae80-eb64-11e9-977c-99f4b0c0a682.png)

**Version Info**

Running on current master (a53a6504583041204140d88718c9b39484ab22eb).

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
Good bug, thanks for the detailed repro!

**Comment by grokys** [comment]
This actually isn't limited to situations where the cache length is set to 0, it can affect other layouts too. 

The problem is demonstrated by the following trace log:

```
StackLayout: 	Using suggested anchor 99999
StackLayout: 	Picked anchor:99999 
StackLayout: 	Layout bounds of anchor 99999 are (0,0,1547,19). 
StackLayout: 	Generating forward from anchor 99999. 
StackLayout: 	Generating backward from anchor 99999. 
 GetElement: 99998 Not AutoRecycleCandidate: 
StackLayout: 	Created element for index 99998. 
StackLayout: 	Layout bounds of element 99998 are (0,-19,1547,19). 
StackLayout: 	Extent is (1547,1900000). Based on average 19. 
```

What happens is that `FlowLayoutAlgorithm` sets the origin of the anchor element at 0,0:

https://github.com/microsoft/microsoft-ui-xaml/blob/3e335559df87217eba0eddcab8d7ab5bbf218030/dev/Repeater/FlowLayoutAlgorithm.cpp#L110-L118

It then tries to generate items moving forward (it can't - we're at the end of the data) and then backwards. However when generating in the reverse direction it hits this code:

https://github.com/microsoft/microsoft-ui-xaml/blob/3e335559df87217eba0eddcab8d7ab5bbf218030/dev/Repeater/FlowLayoutAlgorithm.cpp#L479

`rectMajorStart` here is 0 and because earlier the anchor was placed at 0,0 we can't move backwards either.

I could try to fix this problem, but I'm not sure what the fix would be - any pointers?

**Comment by grokys** [comment]
Another question: is there any point in generating all of the items to fill the viewport when a scroll request is about to be received?

It feels like, when the anchor has to be realized, it should be sufficient to _only_ realize the anchor because we don't know ahead of time where the anchor will appear in the viewport after scrolling, i.e. when scrolling down currently the following happens:

- The anchor is generated
- The items are generated in the forward direction
- The viewport is scrolled
- The anchor now appears at the bottom of the viewport
- The previously generated items are thrown away
- Items are generated in the reverse direction

**Comment by grokys** [comment]
> Currently do we actually scroll or was it a no-op because the anchor is already in view ?

My test case is when scrolling from index 0 to index 99999 so, the anchor definitely isn't in view ;)

> Would putting the anchor at an offset instead of 0,0 so that the scrollintoview actually ends up with a scroll and provides a new rect help ?

That's what I was hoping the author(s) of the control could tell me. I can think of a few ways to make this work, but I'm not sure what the original author had in mind.

**Comment by ranjeshj** [comment]
> My test case is when scrolling from index 0 to index 99999 so, the anchor definitely isn't in view ;)
Yes, but the anchor (99999) got placed at layout offset 0,0 so even thought it looks far away index wise, we laid it out within the existing viewport that the ScrollVeiwer is already showing. I was thinking from scrollviewer's point of view, that anchor is already in view. 

Since layout is relative to the anchor, I think the anchor could be anywhere and 0,0 seemed like a reasonable point as any other.

**Comment by grokys** [comment]
> Yes, but the anchor (99999) got placed at layout offset 0,0 so even thought it looks far away index wise, we laid it out within the existing viewport that the ScrollVeiwer is already showing. I was thinking from scrollviewer's point of view, that anchor is already in view.

That doesn't seem to be quite how it works because measure coordinates are not the same as arrange coordinates.

My understanding of this is a bit fuzzy, but what seems to be happening is (with log excerpts to demonstrate):

## Measure

- Measure realizes the anchor at 0,0
- Measure calls `Generate` forwards and backwards, which manages to only generate one other item at 0,-63

```
StackLayout: 	Layout bounds of anchor 99999 are (0,0,1555,206). 
StackLayout: 	Generating forward from anchor 99999. 
StackLayout: 	Generating backward from anchor 99999. 
 GetElement: 99998 Not AutoRecycleCandidate: 
StackLayout: 	Created element for index 99998. 
StackLayout: 	Layout bounds of element 99998 are (0,-63,1555,63). 
```

- Measure sets `m_lastExtent = EstimateExtent(...)` this creates an extent of 0,-15399755,1555,15399961. Note that the extent starts at a negative number

## Arrange

- Arrange calls `PerformLineAlignment`
- The bounds are retrieved for item 99998: 0,-63,1555,63
- The `m_lastExtent` origin is subtracted from the bounds X,Y so that the bounds become 0,15399692,1555,63
- The element is arranged to these bounds

```
StackLayout: 	ArrangeLayout 
StackLayout: 	Arranging element 99998 at (0,15399692,1555,63). 
StackLayout: 	Arranging element 99999 at (0,15399755,1555,206). 
```

To be honest this all feels a little strange, and I can't help but wonder if it actually works _by accident_. Why separate coordinates for measure and arrange? Would it not make more sense to set the bounds for the anchor to the estimated position for the element during measure? If not, then doesn't `ShouldContinueFillingUpSpace` (run at measure time) need to know about this offset that's going to be applied at arrange time?

**Comment by grokys** [comment]
> Would it not make more sense to set the bounds for the anchor to the estimated position for the element during measure?

The strange thing about this is that `MakeAnchor` calls `Algorithm_GetAnchorForTargetElement` which returns the correct offset for the item, but this value is ignored.

**Comment by ranjeshj** [comment]
Estimating layouts like StackLayout work using a relative layout system which allows negative offsets, but the XAML layout itself expects positive offsets. The layouts arrange elements during the measure pass in order to know when to stop measuring. But those can all be relative. However when we ultimately arrange the elements, the need to be adjusted so that the XAML layout system can get the correct arrange bounds. 

@RBrid to help with the investigation.
