### ISSUE TITLE
ItemsRepeater scrolls to wrong element

### ISSUE THREAD

**Issue by grokys** [microsoft/microsoft-ui-xaml#1425]
**Describe the bug**

`ItemsRepeater` scrolls to the wrong element when scrolled to end and trying to bring into view last item.

**Steps to reproduce the bug**

Edit BasicDemo to contain the following:

```
    <ScrollViewer HorizontalScrollBarVisibility="Disabled"
                      VerticalScrollBarVisibility="Auto"
                      Grid.Row="1" Width="250" Height="350">
        <Border Background="LightBlue">
            <controls:ItemsRepeater x:Name="repeater">
                <controls:ItemsRepeater.ItemTemplate>
                    <DataTemplate>
                        <Border BorderBrush="Red" BorderThickness="1">
                            <TextBlock HorizontalAlignment="Stretch" Text="{Binding}"/>
                        </Border>
                    </DataTemplate>
                </controls:ItemsRepeater.ItemTemplate>
            </controls:ItemsRepeater>
        </Border>
    </ScrollViewer>
```

```
    public sealed partial class BasicDemo : Page
    {
        public BasicDemo()
        {
            this.InitializeComponent();
            repeater.ItemsSource = Enumerable.Range(0, 10000).Select(x => x.ToString()).ToList();
        }

        protected override void OnPointerPressed(PointerRoutedEventArgs e)
        {
            base.OnPointerPressed(e);

            var element = repeater.GetOrCreateElement(9999);
            element.UpdateLayout();
            element.StartBringIntoView();
        }
    }
```

Run the program and manually scroll to the end (using scrollbar). Click an item to trigger `OnPointerPressed`. `ItemsRepeater` scrolls to item 19 despite requesting item 9999.

**Expected behavior**

Nothing happens because item 9999 is already visible.

**Screenshots**

![xBZY6JZvaU](https://user-images.githubusercontent.com/1775141/66591557-82483180-eb93-11e9-8c33-0781c11786f2.gif)

**Version Info**

Current master (a53a650)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
Sounds very similar to #1423, maybe same root cause?

**Comment by grokys** [comment]
Quite possibly, I was unsure whether to put them both in the same issue, but I figured it would be easier to track in two issues if they turn out to be different bugs.

**Comment by grokys** [comment]
The problem seems to go something like this:

- `repeater.GetOrCreateElement(9999);` is called
- `ItemsRepeater::GetOrCreateElementImpl()` calls `m_viewportManager->OnMakeAnchor()` with the element, meaning `m_makeAnchorElement` is set 
- When the control is measured, at first `anchorRealized == true` at https://github.com/microsoft/microsoft-ui-xaml/blob/e7e08236a0c28269a8641cfc06adfc3c40766d9f/dev/Repeater/FlowLayoutAlgorithm.cpp#L53
- Then `m_elementManager.OnBeginMeasure()` is called
- This gets the realization rect from `m_context.RealizationRect()`
- Which ends up in  `ViewportManagerWithPlatformFeatures::GetLayoutVisibleWindow()`
- Which sees that `m_makeAnchorElement` is set and so returns a visible window starting at `0, 0`
- `OnBeginMeasure()` passes this rect to `DiscardElementsOutsideWindow`
- Which discards the anchor element as it thinks it's outside the window!

**Comment by chingucoding** [comment]
I would like to look into this issue.
