### ISSUE TITLE
NavigationView in Compact mode launches with pane opened

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1430]
**Describe the bug**

Related to #1186, NavigationView shows incorrect behavior on app launch in Compact (and LeftCompact) mode.

**Steps to reproduce the bug**

1. Create a test app with this code snippet
```xaml
<mux:NavigationView>
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem Icon="Play" Content="Menu Item1" Tag="SamplePage1" />
        <mux:NavigationViewItem Icon="Save" Content="Menu Item2" Tag="SamplePage2" />
    </mux:NavigationView.MenuItems>
    <Frame x:Name="contentFrame"/>
</mux:NavigationView>
```
2. Launch the app and resize its window to a medium width so a narrow sliver of NavigationView is showing.
3. Restart the app.
4. Alternatively, force NavigationView into LeftCompact mode.
```xaml
<mux:NavigationView PaneDisplayMode="LeftCompact">
```
5. Or make NavigationView LeftMinimal.
```xaml
<mux:NavigationView PaneDisplayMode="LeftMinimal">
```

**Expected behavior**

The Pane remains closed until user presses the hamburger button (or resizes the app into Expanded DisplayMode).

**Comment by chingucoding** [comment]
I think this is related to #1186 . Maybe we can simply change https://github.com/microsoft/microsoft-ui-xaml/blob/37273f6a68fb47988d3e4c25c328ef351e3a9690/dev/NavigationView/NavigationView.cpp#L588 to also respect compact and compact minimal.
