### ISSUE TITLE
HC colors aren't updating as expected when changing theme

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1437]
**Describe the bug**

When changing HC themes, I expect all controls to swap their colors to match the new theme. Some colors are getting "stuck", which is particularly noticeable when changing between HC Black and HC White. 

Restarting the app resolves the problem, and most users may not notice because it's uncommon to change HC themes on the fly. However, I believe this behavior is a regression and may be a symptom of some underlying problem.

**Steps to reproduce the bug**

1. Launch Xaml Controls Gallery
2. Navigate to CalendarView page (as an example)
3. Turn on HC and ensure you're in HC Black theme. Your app should look something like
![image](https://user-images.githubusercontent.com/13142665/66676729-04c90380-ec1d-11e9-921e-cef0f47f3a83.png)
4. Switch to HC White theme. Your app should look like this:
![image](https://user-images.githubusercontent.com/13142665/66676801-2924e000-ec1d-11e9-9a63-4f9176c5dc91.png)
Note that parts of NavigationView Pane's background remained black, and CalendarView's in-scope date cells remained white instead of flipping their colors.

**Expected behavior**

All colors should have changed to show the new theme. The app should have looked like this:
![image](https://user-images.githubusercontent.com/13142665/66677104-c718aa80-ec1d-11e9-9918-83d55dd0096b.png)

**Comment by jevansaks** [comment]
@chrisglein Seems like it could be a brush lookup or invalidation problem. Could you or Bartek take a look?
