### ISSUE TITLE
Many layout problems and at least one bug caused by layout rounding

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#1441]
**Describe the bug**
The value returned from `MeasureOverride` in the layout process seems to be rounded to the nearest display pixel (not view pixel). For example, the desired size of the element will be set to this rounded value. This is not a bug in itself, but there needs to be a clear strategy for handling this, and there need to be examples of how to deal with this issue when writing custom controls.

For an example of one of the bugs caused by layout round errors in the layout process, see <https://github.com/microsoft/microsoft-ui-xaml/issues/477>. I wrote a long comment in that thread. I think the bug is because a value is alternately being rounded up and down - so this needs to be made consistent, perhaps with some tolerance.

Now on to another example that causes a problem: trying to write a WrapPanel component. At the moment, the one in the community toolkit works mainly by accident and will not work properly for certain layout measurements. The basic problem is, you compute the size in `MeasureOverride` and return that value. But what if the width was between two display pixels, for example, 10.2 at 100% display scaling? This will be rounded down to 10 by the layout system. Then when it comes to `ArrangeOverride`, you will find that the child elements do not quite fit in the space available and wrap onto another line, overflowing the panel.

What is a potential solution to the WrapPanel problem? Well, one solution is to round up to the nearest display pixel before returning the measured size in the `MeasureOverride` function. However, to do this one needs access to `DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel`. I have checked this and it's actually a relatively expensive operation to perform on every measure (takes 0.1ms), therefore I'd like to offer one suggestion. Provide fast access to a cached value of `DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel`. For example, you could add a listener for DisplayInformation.GetForCurrentView().DpiChanged and update some static property for the view that can be easily accessed - not sure where. Either that, or provide a fast helper method for rounding view pixels to display pixels (closest or up or down). Note: it needs to be fast from C#, not just C++.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            |     Yes     |

**Comment by kmgallahan** [comment]
Reading this issue just reminded of some old crashes I had experienced a while back in the Windows Composition Samples app. 

I reported them [here](https://github.com/microsoft/WindowsCompositionSamples/issues/250), but the crashes couldn't be reproduced. With further testing I've found that the crashes only happen with display scaling set to 125% (others seem fine), so I updated my issue with [this comment](https://github.com/microsoft/WindowsCompositionSamples/issues/250#issuecomment-541436511).

So yeah, this is definitely an important issue that is potentially causing edge-case crashes in other apps as well.

**Comment by ranjeshj** [comment]
The framework internally does rounding when you use UseLayoutRounding property. Essentially does  floor((value * scalefactor) + .5)/scalefactor to avoid such issues with a non 1.0 scale factor. The issue with Slider is related but is specific to slider because slider does some layout updates during size changed event.

Would UniformWrapGrid with ItemsRepeater get what you need WrapPanel for ?

**Comment by benstevens48** [comment]
Hi @ranjeshj , thanks for the reply. If you'll bear with me I have a long comment to make and I'd like to suggest that 'to avoid such issues with a non 1.0 scale factor' is actually the opposite of what it is achieving in some cases. I think it's important to have a rock-solid layout system which is why I'm keen to see this properly addressed. Please correct m if I say anything wrong as some of it is guesswork.

First of all, I think you'll agree that you can't rely on floating-point arithmetic producing exactly the same result unless you do exactly the same calculation with exactly the same inputs in exactly the same order. At first I thought the rounding values to the nearest display pixel as the framework does might help, because then it's like doing integer arithmetic. This works if you have a panel/control with children and no padding/spacing/margin because the desired sizes of the children are rounded, and then the result of what you return from MeasureOverride is rounded, so you are essentially doing integer arithmetic. However, this all breaks down once you introduce margin/padding/spacing. Unless you always round the input values of margin/padding/spacing before performing a calculation (which I can't see any suggestion of), then layout calculations will involve adding together things that could be half-way between pixels (e.g. anything odd with 150% display scaling), and you end up with a result that might be half-way between display pixels. Due to floating-point arithmetic error, you can't really rely on this being exactly the same value (for example if you do a slightly different order of computation in Measure and Arrange that you expect to produce the same result). In this case, when you apply the formula `floor((value * scalefactor) + .5)/scalefactor`, it will turn a microscopic difference in `value` into a macroscopic difference. Now when writing a control I could expect to have to deal with microscopic arithmetic errors, but if I can't dismiss differences of 1 display pixel if I want a pixel-perfect layout.

In the case of the slider bug, it's true that it occurs because the slider does layout updates in the size changed event, but many other controls do this as well - anything that wraps content etc. When I was testing it I found that the problem was the size change event was receiving values for the size which differed by 1 display pixel even though the slider was stretched to fill its container, and the with of the container was ultimately determined higher up the tree (by some margin and a width set on a parent container). Correct me if I'm wrong, but I think in this case the width provided to the size changed event and the ActualWidth and ActualHeight values of the slide should be determined by the width of the container, which should be fixed, and should not be affected by moving things around in the control template of the sider. Assuming I'm not wrong here, my conjecture is that the size of the parent container was exactly between two display pixels and for some reason moving stuff around inside the sider was causing it to choose to round one way then the other way, perhaps due to some floating-point arithmetic error.

In any case, it seems that in order for the calculation `floor((value * scalefactor) + .5)/scalefactor` to be stable, you need to cache `value` and then when another measure pass comes along, if the new computed value, `newValue` only differs from `value` by a very small amount, then use the cached `value` instead. This is just a suggestion because I don't know how it works internally.

I'm not sure what control you are talking about when you mention `UniformWrapGrid`, but I need elements to be different sizes. I am perfectly happy with the custom WrapPanel I wrote based on the one in the Community Toolkit, except for the occasional issue related to the layout rounding that I mentioned. In fact, I have decided that the most reliable way to do it is to store which row items were assigned to in the measure phase (I just store a list of row counts), then use this in the Arrange phase. However, I am not sure I can rely absolutely on this - it would be helpful if there was more documentation on Measure/Array which could say whether this was a good idea or not. Because I am not 100% sure I can rely on Measure being called in all situation which would need me to recompute the row counts, I decided to use the row counts only as a 'tie-breaker' when within 1.1 view pixels of the edge of the row. Really I probably only need to consider the case of being within 0.5 + epsilon display pixels of the edge of the row, but because I don't have any guarantee of what the layout system does with the value returned from MeasureOverride, I thought I'd use 1 full view pixel instead.

Based on my experience I have a couple of suggestions that in my opinion are neaded to write pixel-perfect custom controls.

1. Provide some guarantee on the difference between the value returned from MesaureOverride and the DesiredSize given to the control - for example is it always within 0.5 display pixels, or within 1 etc.
2. Provide fast access to the display scaling factor. I already use this a lot in my app (for image size calculations) and it would be nice to have fast access to do layout calculations as well.

**Comment by benstevens48** [comment]
@ranjeshj , @jevansaks , it turns out the situation with regard to layout rounding is much worse than I initially thought. For example, consider the following XAML snippet, which is simply a horizontal StackPanel of with 360 view pixels with 24 identical children (except for a text marker to show the number of the child), each of which is 15 view pixels wide, so should exactly fit into the panel.
```xaml
        <StackPanel Orientation="Horizontal" Width="360" Height="40" Background="Red">
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="1"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="2"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="3"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="4"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="5"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="6"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="7"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="8"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="9"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="10"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="11"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="12"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="13"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="14"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="15"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="16"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="17"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="18"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="19"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="20"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="21"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="22"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="23"></TextBlock>
            </Grid>
            <Grid Width="15" Height="20" BorderBrush="Black" BorderThickness="1">
                <TextBlock Text="24"></TextBlock>
            </Grid>
        </StackPanel>
```
Running this at 100% display scaling, the children exactly fit as expected. But running it at 150% display scaling, the whole of the last number '4' in '24' is cut off. This is because the DesiredSize of each of the children is rounded to the nearest display pixel, which makes each 0.5 display pixels larger than specified, and the end result is 12 display pixels larger than specified! One can come up with examples where the content of the panel ends up being 1.5 times larger than it should be! This is a very big problem.

I think it's clear that in order to avoid issues like this, no layout rounding should be applied during the measure phase. Layout rounding should probably be applied to the 'finalRect' that is passed to the Arrange call, but then in order to position things properly it is necessary to get back the rounded final rect that the layout system used. Ideally Arrange would return it, but perhaps the new ActualOffset and ActualSize methods contain this information after Arrange is called. Also, guidance is needed for control authors on how to use this.

**Comment by jevansaks** [comment]
@ranjeshj can you look into getting the documentation updated or created to help layout authors with navigating this space?

**Comment by benstevens48** [comment]
@jevansaks , please don't label this as just a docs issue. It's a serious flaw which needs addressing. Actually, I think perhaps you should hold off documenting the effects of layout rounding until you've reviewed it. This problem is not confined to control authors but also affects everyday developers. My previous example showed it's impossible to fill a fixed width stackpnel exactly with fixed width children. Moreover the overflow can run into 10s of pixels and is different at different scale factors. It's even worse if you consider a fixed width wrappanel. Suppose someone puts 4 children 15 view px wide in a 30 view px wide wrappanel. You would expect 2 rows of 2 but would actually get 4 rows of 1 at 150% scaling, and you wouldn't notice this if you were testing at 100% scaling. There isn't a good way for the wrappanel to overcome this since the desired sizes of the children will have been rounded up. The more I think about it, the more obvious it becomes that layout rounding doesn't makes sense as a concept. I do want crisp lines though, so I would suggest a UseRenderRounding property instead is only applied on render and does not affect layout. If you think about what properties the rounding should have. 1. Things should be moved at most 1 display pixel from their intended position. 2. Boundaries which coincide before rounding should coincide after rounding. This suggests that the position of boundaries should be rounded relative to a global origin before render. However there are a few special cases like if I deliberately size an image to be an exact number of display pixels I would want to guarantee it mapped directly onto display pixels. I know you are probably very busy but I hope you can think seriously about this problem. I really want WinUI to succeed , but I think that will require issues such as this to be addressed.

**Comment by jevansaks** [comment]
@benstevens48 thanks for sharing your thoughts. This behavior has been this way for quite some time and I believe the general design is correct. You may be identifying some bugs and we can look into that first, so I've changed this from doc -> bug label. But I think the core approach is working as intended. 

Of course layout rounding is a tradeoff, and you can opt out if it isn't working well for you with [UseLayoutRounding](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.uselayoutrounding).

We have discussed exposing a Composition pixel snapping API but it just hasn't happened yet.

**Comment by benstevens48** [comment]
Thanks for the reply. A pixel snapping API that happens on render relative to a global origin would be great, assuming it could apply to all controls. Hopefully this could include shapes like Rectangle (maybe via an option) - at the moment Rectangle stroke is not snapped to display pixels, which means a Rectangle with a stroke width of 1 at 150% display scaling looks slightly blurred compared to a Border control with a stroke width of 1.

If you don't intend to change the behavior of layout rounding, then adding it to the docs would certainly be useful. It works as a concept (other than the slight issues it causes with designing a wrap panel and similar controls that I mentioned at the beginning) if everything has its natural width or Grid 'star' widths, with only a few things specifying a width, which probably covers most use cases, including how I've been working, but it breaks down when controls with specified widths need to fit together exactly, due to the acculumated error effect that I pointed out. If I had the option to replace it with pixel snapping/rounding on render, then I would, so I'd be keen to see that feature.

**Comment by gabrielconl** [comment]
I just ran into this issue, which breaks my use case because it requires perfect precision.

```
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*"/>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="*"/>
    </Grid.ColumnDefinitions>
    <Grid Grid.Column="1" Width="12" Height="12" Background="Black" />
    <Grid Grid.Column="0" Width="8" Height="8" Background="Red" Margin="-7,0,-4,0"  />
    <Grid Grid.Column="2" Width="8" Height="8" Background="Yellow" Margin="-4,0,-7,0"/>
</Grid>
```
![margin-4](https://user-images.githubusercontent.com/84711285/120110384-e018fb00-c175-11eb-9431-61087eebd9ed.png)
The colored squares are supposed to be at equal distance from the middle of the black square, but you can see that the red one is closer.
If you change the -4 in the margins to -5, they'll be symmetric as expected.
![margin-5](https://user-images.githubusercontent.com/84711285/120110390-e27b5500-c175-11eb-9fdc-abf44ac6624f.png)

**Comment by codendone** [comment]
@benstevens48 A change was just checked in for 1.5 to have Measure and Arrange be more consistent in their handling of layout rounding. This eliminates all non-control/app bugs I can find at the moment. I'd like to close this issue as fixed with that change.

There are no plans to remove layout rounding, nor to implement a "render-time rounding" feature which I believe would have different problems (for example, text layout needs to know the final render size at layout time to wrap appropriately).

**Comment by bencambridgemaths** [comment]
@codendone - thanks for the update and the fixes

 I don't really understand your concerns with render time rounding. It is sometimes called pixel snapping and is used in WPF as 'SnapsToDevicePixels', and also I believe most browsers do this in some way. It would only move things at most 1 device pixel (or even at most 0.5) from their exact intended layout position, so there is no need to know this before doing text wrapping.

I think maybe you even mentioned before somewhere that you might have some sort of pixel snapping property in the composition layer already?

Layout rounding falls down in a number of situations. 

For example, in HTML/CSS I often have something like a container that fills the whole window width which positions its child elements in a row then wraps to a new row on overflow. Say there are 4 child elements, or even a multiple of 4. I might set the child elements to all be 100% width at small window widths, but then set them to be say 205px wide for a min window width of 820px. Thus if the window is < 820px wide, each child is on its own row, and If the window size is >= 820px wide, I have a row of 4 children of width 205px each.

If I was to convert this to WinUI, it would work OK at 100% display scale. But at 150% display scale, all the child element sizes would be rounded up by 0.5 display pixels, and the 4th child would end up on a new row, with a large gap left on the row above, which is not what I want.

This sort of practice may not be so common amongst WinUI developers, but if you want to be able to port code from HTML/CSS to WinUI then this is a really basic scenario which needs to work. I can turn layout rounding off, but I still want crisp lines, hence some sort of render-time rounding or pixel snapping is needed.

**Comment by codendone** [comment]
The problem with rounding is that it isn't always consistent. Let's start with this example:
```xml
    <StackPanel Orientation="Horizontal">
        <Grid Width="10" Background="Red"/>
        <Grid Width="10" Background="Red"/>
        <Grid Width="10" Background="Red"/>
        <Grid Width="10" Background="Red"/>
    </StackPanel>
```
Say that we're running that at 125% scale. From a simple layout perspective, the StackPanel is 10\*4=40 width, which at 125% scale is 50 device pixels. But each Grid is 10*1.25=12.5 device pixels. What do we do now?
* Do we round each Grid up to 13 pixels? If we do that, the StackPanel will need 52 device pixels rather than the 50 it expected. If that StackPanel had a sibling element positioned at x=40 which should be adjacent to the StackPanel, it will overlap the StackPanel by those 2 pixels. Oops.
* Do we round down each Grid to 12 pixels? If we do that, they'll fit in the bounds of the StackPanel but now use only 48 of the 50 pixels, so there will be 2 blank pixels somewhere. Oops.

Layout rounding attempts to resolve these issues by ensure that layout accounts for the final rendering.

Layout sometimes also needs to be aware of final rendering size when width can affect height (or vice versa). Let's look at this example for text layout:
```xml
    <StackPanel BorderThickness="1" Width="10">
        <TextBlock TextWrapping="Wrap" ... />
    </StackPanel>
```
In this case, say we're running at 150% scale. Ignoring any rounding, the StackPanel is 10 pixels wide, minus 1 border on each side, leaving 8 pixels for the TextBlock to wrap its text in. When considering rounding, each border side should round up to 2 device pixels. The StackPanel as a whole will have its Width be 10\*1.5=15 device pixels, which leaves 15-2-2=11 pixels for the TextBlock. That means the TextBlock really has 11/1.5=7.3 logical pixels of width. If TextBlock did its layout at 8 logical pixels, the extra pixels may be clipped (and even clipping a partial pixel of text gets attention, based on some bugs like this we've fixed for TextBlock in the last few years!). If the rendering of the TextBlock simply adjusts to 7.3 logical pixels, the text may now wrap to a greater height, which will almost certainly will be a problem.

Overall, I'm not saying there isn't potential for improvement somewhere in all of this. You raise a good point that a fresh analysis of what WPF does may be useful -- I don't know how much WPF's design was considered when layout rounding was designed and implemented for UWP XAML ~15 years ago. I believe WPF originally did no rounding -- it just scaled all values faithfully, which would result in single pixel borders becoming blurred 1.5 pixel borders at 150% scale. I think at least some mitigations were added for borders, but I'm not familiar with specifically what has been done or how extensively WPF handles rounding.

My original desire to close this issue was based on the change coming in 1.5 to fix the inconsistency with how Measure and Arrange handled rounding (the example in your original post). I expect that fix to address many of the issues caused by layout rounding. If you'd like to keep an issue active to more broadly re-evaluate the existence/handling of layout rounding or shifting more rounding to render time, we can do that, either by marking this issue as a feature proposal or by logging a separate feature proposal.

**Comment by benstevens48** [comment]
@codendone - thanks for the discussion. I think that you are still thinking of render rounding in not quite the right conceptual way, which is probably my fault. Perhaps I should have called it pixel snapping. I have tried to explain it better in this feature proposal - https://github.com/microsoft/microsoft-ui-xaml/issues/9114. You can go ahead and close this issue and we can use the feature proposal for any further discussion. I should add that I have done no research on the subject and maybe it is more difficult than I imagine.
