### ISSUE TITLE
CalendarView crashes when changing Theme if not previously loaded into the VisualTree

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#1442]
**Describe the bug**

Changing the `RequestedTheme` on a page that contains a `CalendarView` that has not been loaded in to the Visual Tree causes the app to crash with an `AccessViolationException`. ("Attempted to read or write protected memory. This is often an indication that other memory is corrupt.")

Originally reported at https://github.com/microsoft/WindowsTemplateStudio/issues/3367

**Steps to reproduce the bug**

1. Create a new, blank UWP app
2. Set the content of MainPage to be

```xml
    <StackPanel>
        <Button Content="Set Theme to Dark" Click="DarkClicked" />

        <SplitView x:Name="SplitView"
                   IsPaneOpen="False"                   
                   DisplayMode="Overlay">
            <SplitView.Pane>
                <CalendarView />
            </SplitView.Pane>
        </SplitView>
    </StackPanel>
```

3. Add this to the code-behind

```cs
private void DarkClicked(object sender, RoutedEventArgs e)
{
    (Window.Current.Content as FrameworkElement).RequestedTheme = ElementTheme.Dark;
}
```

4. Run the app and click the button.
5. Experience crash.

**Expected behavior**

The app should switch to having the dark theme.

The app does not crash is the pane is opened before attempting to switch theme.

Having a CalendarView in the UI tree but not loaded (`X;Load="False"`) does not cause the exception.

**Version Info**

This is in `Windows.Foundation.UniversalApiContract, Version=8.0.0.0` 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Good bug! Putting on the backlog for WinUI 3.0.
