### ISSUE TITLE
Proposal: Get rid of uneven left/right spacing on MenuFlyout

### ISSUE THREAD

**Issue by chigy** [microsoft/microsoft-ui-xaml#1445]
We noticed this with #1079 which was pointing out the space on Top/Bottom which is by design.

However, during the conversion, design and I noticed the gap on left/right and further noticed that they don't seem to be even on both sides... We would like this gap to be removed and the hover state to go edge to edge.

![image](https://user-images.githubusercontent.com/22958680/66790571-2fc58880-eea5-11e9-9f57-f88de36fc240.png)

**Comment by shaheedmalik** [comment]
I agree. The way it currently is, the hover isn't even centered.

It should all the way across.

**Comment by chingucoding** [comment]
If this is a bug I would be happy to take my shot at it. 😃

**Comment by chigy** [comment]
@jevansaks , I debated if I should open a bug but technically, this is a design change request so I opened a feature proposal. No problem with that being handled as a bug.

**Comment by adrientetar** [comment]
Also, when opening a submenu, shouldn't the item text vertically align with base menu text? Seems like the padding at the top isn't accounted for currently.

**Comment by chigy** [comment]
@adrientetar , good eyes! We were about to open a request to fix that. The select visual should be aligned. Would you do me an honor if you don't mind? (Ignore the vertical circle)

![image](https://user-images.githubusercontent.com/22958680/67110411-8bcf2c00-f187-11e9-91dd-6c21bf2f8166.png)

**Comment by mdtauk** [comment]
@chigy, looking at the image
![image](https://user-images.githubusercontent.com/22958680/67110411-8bcf2c00-f187-11e9-91dd-6c21bf2f8166.png)

Shouldn't the sub menu be casting a shadow on the lower menu?  At the moment they blend together

**Comment by adrientetar** [comment]
> Would you do me an honor if you don't mind?

Huh, are you asking me to open an issue about it? See #1462

> Shouldn't the sub menu be casting a shadow on the lower menu? At the moment they blend together

Yeah, I'd say go ahead and open a design bug

**Comment by chigy** [comment]
@adrientetar , thanks for the design bug!

**Comment by chigy** [comment]
> Shouldn't the sub menu be casting a shadow on the lower menu? At the moment they blend together

Please feel free to open design bug. This could have been a shadow limitation but we should document it nonetheless...

**Comment by chigy** [comment]
> > Shouldn't the sub menu be casting a shadow on the lower menu? At the moment they blend together
> 
> Please feel free to open design bug. This could have been a shadow limitation but we should document it nonetheless...

@adrientetar , I confirmed this is a technical limitation that we cannot draw shadow on shell popups's sub-menus.

**Comment by adrientetar** [comment]
@chigy, could we have an updated design toolkit? here: https://docs.microsoft.com/en-us/windows/uwp/design/downloads/

**Comment by chigy** [comment]
> @chigy, could we have an updated design toolkit? here: https://docs.microsoft.com/en-us/windows/uwp/design/downloads/

@adrientetar , we are currently working on it with update for WinUI2.2.

**Comment by mdtauk** [comment]
Would be good if UI Toolkits were released at the same time as a WinUI version in the future.  Maybe formally tie the two together.

**Comment by chigy** [comment]
> Would be good if UI Toolkits were released at the same time as a WinUI version in the future. Maybe formally tie the two together.

@mdtauk , I understand, I'd like that also. We are doing what we can.
