### ISSUE TITLE
MenuFlyout submenu should align to its origin menu item

### ISSUE THREAD

**Issue by adrientetar** [microsoft/microsoft-ui-xaml#1462]
When opening a MenuFlyout submenu, the submenu items should vertically align with the origin menu item. It seems that the padding at the top of MenuFlyout isn't currently accounted for.

Image posted by @chigy in #1445 

![image](https://user-images.githubusercontent.com/1250894/67121128-0c734400-f1eb-11e9-84b6-19f3765ddc09.png)

**Comment by jevansaks** [comment]
@chigy should we remove the top/bottom padding on the menu? That would make this easy to solve. :)

**Comment by chigy** [comment]
> @chigy should we remove the top/bottom padding on the menu? That would make this easy to solve. :)

No, that was already discussed with design and decided they do not want the padding removed.

**Comment by jevansaks** [comment]
Hmm ... ok, do you have a comp for what it should look like? @karenbtlai was suggesting that it might look unbalanced/misaligned in other states if we try to shift the flyout position to address this.

**Comment by chigy** [comment]
@karenbtlai , Could you explain what the problem might be?

**Before**
![image](https://user-images.githubusercontent.com/22958680/67230214-b6242200-f3f1-11e9-87ac-1cb232ec7396.png)

**After**
![image](https://user-images.githubusercontent.com/22958680/67230234-c3411100-f3f1-11e9-9837-c09d12421d41.png)

**Comment by jevansaks** [comment]
I'm not sure if there's a way to do this with just style/template changes. In theory a negative Margin could do it, but IIRC we used to have that and removed it because of some shadow stuff. Is that right, @kaiguo?

**Comment by kaiguo** [comment]
> I'm not sure if there's a way to do this with just style/template changes. In theory a negative Margin could do it, but IIRC we used to have that and removed it because of some shadow stuff. Is that right, @kaiguo Kai Guo FTE?

I think negative margins were removed because the way we positioning popup changed, and we switched to vertical/horizontal offset instead. 

Looks like we don't want to remove the top padding, and don't want to shift flyout position either, what's the suggested change?

**Comment by jevansaks** [comment]
> don't want to shift flyout position either, what's the suggested change?

I believe @chigy is requesting to change the flyout position. Is that possible in WinUI today?
