### ISSUE TITLE
Add gridextra for responsive

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/microsoft-ui-xaml#1466]
Please look at this project. It's awesome to make app responsive. That's syntax is like bootstrap.
[Gridextra on github](https://github.com/sourcechord/GridExtra/blob/master/README.md)

**Comment by Tirraon** [comment]
That lib already support UWP (at least for C#).
Or you mean to add it in WinUI as build-in feature?

**Comment by khoshroomahdi** [comment]
I mean built in feature

**Comment by jevansaks** [comment]
We already have proposals for improving Grid and adding CSS-Grid (#54) and Flex (#896). Can you add your thoughts to those proposals?
