### ISSUE TITLE
Opening a ComboBox Flyout within another Flyout Closes all Flyouts

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#1467]
**Describe the bug**
Opening a ComboBox flyout itself nested in another flyout will close all flyouts and prevent making selections. Interestingly, this only seems to happen on the second opening of the ComboBox flyout.

This issue was not present until switching to Microsoft.UI.Xaml 2.2.190830001. Before that the app was using plain UWP.

**Steps to reproduce the bug**
Add a ComboBox to a Flyout. Clicking the ComboBox to make a selection the second time will close all Flyouts. (I didn't make a bare-bones repro of this but can if others can't see this issue).

**Expected behavior**
The ComboBox flyout should open normally and allow selections without closing other flyouts.

**Screenshots**

![image](https://user-images.githubusercontent.com/17993847/67151254-6dedee00-f291-11e9-8729-889cd92d2942.png)

A custom templated control is pictured which allows selecting both a date and time from a flyout. The time selection is done using ComboBoxes. Setting the hour will work fine, however, as soon as the minute ComboBox is clicked all flyouts are closed. 

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190830001 and 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |  Not tested |
| April 2018 Update (17134)          |  Not tested |
| Fall Creators Update (16299)       |  Not tested |
| Creators Update (15063)            |  Not tested |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Comment by jevansaks** [comment]
I don't know what could have changed in WinUI 2.2 to have cause this. @robloo Do you have a standalone repro that you could share?

**Comment by robloo** [comment]
@jevansaks I've made the small app attached to reproduce this issue. There appear to be multiple ways to cause it. It potentially has something to do with clicking between controls, the click speed, or bindings.

In the code-behind I am using techniques similar to what are used in the custom controls where this issue was first encountered. There are some work-arounds as 'clean' binding (like in WPF) can't be used to update the list of ComboBox items when a selection changes.... (that's been talked about a lot separately).

(1) Start the app (Debug or Release)
(2) Click the 'Open Flyout' button
(3) Select "12 hour clock" in the first (left) ComboBox
(4) Select an hour "11:00" in the second (right) ComboBox
(5) Very rapidly click a date in the calendar view 3-4 times (rapidly means at the speed of double click << 500ms)
(6) Click the left ComboBox to select "24 hour clock" -- as soon as the ComboBox dropdown flyout opens all flyouts close

This above steps reproduce the issue the vast majority of the time. There is a chance you will need to try it again though.

![Issue](https://user-images.githubusercontent.com/17993847/67415333-dc34f800-f592-11e9-8038-65a76bb3aead.gif)

[FlyoutTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3763475/FlyoutTest.zip)

**Comment by jevansaks** [comment]
Thanks for the repro! I can see that the flyout is closing because it's losing focus (presumably because it's being sent into the combobox flyout). I'm following up on if there's any work arounds for you here.

**Comment by robloo** [comment]
This was reported again in #1782 for the Windows magnifier app. Seems to be a fundamental issue with flyouts.

**Comment by ranjeshj** [comment]
@kaiguo Please take a look

**Comment by robloo** [comment]
Any news on this? Since it affects even Microsoft's own apps I would expect it is high priority. It should not wait until WinUI 3.0 to be fixed.

**Comment by XeorgeXeorge** [comment]
Hello, i encountered a similar issue, first i gotta say this seems to be underlying issue with the **Flyout** and **ComboBox**, and not necessarily tied with WinUI.

Upon clicking a **ComboBox**  hosted inside a **Flyout**,  Sometimes (about 30% of the time) the **Flyout** will suddenly close. much like in the OP.

Target Version was **18362**
Min Version was  **16299**

Thankfully i kinda fixed it with a bit of style sheet hacking, its kinda of a bandage solution but it worked for me.

This will be a bit of stretch so if you wanna skip it, Just grab [this Style](https://pastebin.com/wbaHNU0U) and apply it to your **ComboBox**, tell me how it goes.

# Steps

First, locate the **Generic** style sheet, its located at:
C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.**18362**.0\Generic

**18362** is my Target version, change accordingly.

Or you can open it through VS, by Right clicking a Static/ThemeResource  in a xaml document,
and clicking "Go To Definition"

 Inside the Generic.xaml file you press the Control+F and search for "ComboBox" with quotes, you'll find the default style of a **ComboBox**.

Copy this style to your desired location, the go and change all x:Load="False"  inside it to x:Load="True". (except of EditableText)

Depending on your version, the style sheet will throw minor complaining about features not being supported, just surgically remove those and you'll be fine (for the most part).
Give that style a key, and just apply it to your ComboBoxes.

**Comment by premiaware** [comment]
This problem is very serious. I have developed a CMR App, the customer enters the data in Flyout and it closes losing all the data. Is it unacceptable to work with this problem when it is fixed?

**Comment by ranjeshj** [comment]
@kaiguo did you get a chance to investigate this ? @llongley can you help diagnose this issue ?

**Comment by premiaware** [comment]
xaml code for testing, is incredible problem, renders flyout control unusable!


        <Button Content="Click Me" Margin="50">
            <Button.Flyout>
                <Flyout Placement="Right">
                    <StackPanel x:Name="stackContatto">
                        <TextBlock Text="click me, after select 2 in to the combo, after click me, and repeat." Margin="10,10,10,50" />
                        <ComboBox Margin="10" HorizontalAlignment="Stretch" SelectedIndex="0">
                            <ComboBoxItem>1</ComboBoxItem>
                            <ComboBoxItem>2</ComboBoxItem>
                            <ComboBoxItem>3</ComboBoxItem>
                        </ComboBox>
                    </StackPanel>
                </Flyout>
            </Button.Flyout>
        </Button>

**Comment by premiaware** [comment]
My solution for fix the problem, create a FlyoutBehavior and attach it to Flyout Control.
in the Behavior cancel the GettingFocus event of Popup.

protected override void OnAttached()
        {
            _flyout = AssociatedObject.Ancestors().OfType<FlyoutPresenter>().FirstOrDefault(); ;
            if (_flyout != null)
            {
                _popup = _flyout.Parent as Popup;
                _popup.GettingFocus += _popup_GettingFocus;
            }
        }

        private void _popup_GettingFocus(UIElement sender, GettingFocusEventArgs args)
        {
            args.Cancel = true;
        }

**Comment by ranjeshj** [comment]
@premiaware Thanks for posting the workaround and the small repro. 
@robloo I can repro it with OS Xaml bits as well as WinUI2. Was this not the case for you ? If this is an issue with the OS Xaml bits, then the fix will have to wait for WinUI3.

**Comment by kaiguo** [comment]
@llongley it's probably a focus issue. When ComboBox closes the focus drifted to its parent popup. Adding a DropDownClosed event handler on ComboBox and forcing the focus onto ComboBox itself might be able to fix it.

**Comment by robloo** [comment]
@ranjeshj It could have been an OS XAML update that caused this. I just noticed it about the same time I switched to using WinUI. Really is a fundamental issue. I really hope after WinUI 3.0 we don't have to wait ages for stuff like this to get fixed. It's not sustainable for development.

@premiaware Thanks for finding and posting a work-around. At least that's a good start.

**Comment by benstevens48** [comment]
I have also come across this issue with just one simple flyout and a combo box using system XAML on Windows 11. Here is the code.
```XAML
<Page x:Class="FlyoutCloseBug.MainPage" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <StackPanel>
        <Button Content="Show flyout">
            <Button.Flyout>
                <Flyout>
                    <StackPanel MinHeight="100">
                        <ComboBox>
                            <ComboBox.Items>
                                <ComboBoxItem IsSelected="True" Content="Test"></ComboBoxItem>
                            </ComboBox.Items>
                        </ComboBox>
                    </StackPanel>
                </Flyout>
            </Button.Flyout>
        </Button>
    </StackPanel>
</Page>
```
Click on the button to open the flyout, click anywhere in the flyout except on the combo box, then click in the middle of the combo box and the flyout closes. Seems like a pretty bad bug. It seems to be related to the flyout scroll viewer somehow (but perhaps this is just a special case of some sort of focus issue). For example, a flyout without a scrollviewer in the template works fine.
```XAML
<Page x:Class="FlyoutCloseBug.MainPage" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Page.Resources>
        <Style TargetType="FlyoutPresenter" x:Key="NoScrollFlyoutPresenterStyle">
            <Setter Property="HorizontalContentAlignment" Value="Left" />
            <Setter Property="VerticalContentAlignment" Value="Top" />
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="FlyoutPresenter">
                        <Border Background="{TemplateBinding Background}" BorderBrush="{TemplateBinding BorderBrush}" BorderThickness="{TemplateBinding BorderThickness}">
                            <ContentPresenter Content="{TemplateBinding Content}" ContentTemplate="{TemplateBinding ContentTemplate}" ContentTransitions="{TemplateBinding ContentTransitions}" Margin="{TemplateBinding Padding}" HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}" VerticalAlignment="{TemplateBinding VerticalContentAlignment}" />
                        </Border>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </Page.Resources>
    <StackPanel>
        <Button Content="Show flyout">
            <Button.Flyout>
                <Flyout FlyoutPresenterStyle="{StaticResource NoScrollFlyoutPresenterStyle}">
                    <StackPanel MinHeight="100">
                        <ComboBox>
                            <ComboBox.Items>
                                <ComboBoxItem IsSelected="True" Content="Test"></ComboBoxItem>
                            </ComboBox.Items>
                        </ComboBox>
                    </StackPanel>
                </Flyout>
            </Button.Flyout>
        </Button>
    </StackPanel>
</Page>
```
Also, if you put the scroll viewer inside the flyout's content instead of in the flyout presenter template, it also works fine.

**Comment by robloo** [comment]
If this doesn't occur in WinUI 3 I'm fine with closing it.

**Comment by ranjeshj** [comment]
Please re open if this does still repro with WinUI3.

**Comment by fasigno** [comment]
Definitely this issue also occurs in WinUI3,

microsoft.windows.sdk.buildtools 10.0.22621.3233
microsoft.windowsappsdk 1.5.240404000

Target framework: .NET 8.0

![FlyoutInsideFlyout1](https://github.com/microsoft/microsoft-ui-xaml/assets/1397516/10e4428c-2717-4115-a865-5646ba16c324)

As shown in this gif I've got a DataGrid with a button column that shows a flyout. The flyout contains two comboboxes in order to let the user configure a parameter.

I cannot select any of the comboboxes values as the flyout is closed immediately.

Silly thing, if I insert just one empty row without fulfill the other columns comboboxes work (first attempt always missed)!

![FlyoutInsideFlyout2](https://github.com/microsoft/microsoft-ui-xaml/assets/1397516/78ac7fdd-3368-4202-9385-2aaa01445a49)
