### ISSUE TITLE
Button with MenuFlyout doesn't work in tablet mode after instant drag of application

### ISSUE THREAD

**Issue by surzoprovakar** [microsoft/microsoft-ui-xaml#1470]
**Describe the bug**

In XAML ,a button with MenuFlyout doesn't work for tablet mode after instant dragging the app. Video link is attached. Same happens for tablet,space devices in tablet mode.

**Steps to reproduce the bug**

1. Go to "Tablet Mode"
2. Open any app contains button with MenuFlyout
3.Drag the app quickly
4.MenuFlyout won't work

**Expected behavior**
   MenuFlyout should work

**Screenshots**

   github link
   https://drive.google.com/open?id=18hhdak4pckIjBIw0XngbmXSvAiPCPGTC

**Additional context**
   Same result is noticed for the "XAML Controls Gallery" app in Microsoft Store

**Comment by shaheedmalik** [comment]
This is definitely broken.

**Comment by jevansaks** [comment]
Very weird bug! I debugged this and I can see that the Flyout is being asked to open and the flyout code thinks the popup is open. I also see the popup in the live visual tree so from the controls side we think it's visible. Over to rendering to dig further.

**Comment by surzoprovakar** [comment]
> Very weird bug! I debugged this and I can see that the Flyout is being asked to open and the flyout code thinks the popup is open. I also see the popup in the live visual tree so from the controls side we think it's visible. Over to rendering to dig further.

**Comment by surzoprovakar** [comment]
Will it be fixed at later update version?
