### ISSUE TITLE
Question: How long it takes to build MUXControlsTestApp ?

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/microsoft-ui-xaml#1476]
I cloned the repo, selected the MUXControlsTestApp as the startup project, chose Debug, x64 and hit F5.. as it says [here](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/developer_guide.md#building-the-repository). But it was 5 hour 50 minutes and the build was still going on. It wasn't stuck, it was progressing little by llittle. Is it normal? (NUGET restore finished normally)

Visual Studio version : 2019 , 16.3
Windows 10 : 1903
My pc RAM : 4GB
Processor : Intel core i3-7100 , 3.9 GHz

I also tried using msbuild /restore with cmd, same result.

**Comment by jevansaks** [comment]
Is it using 100% CPU for all cores or 100% disk during this time? I would recommend turning off any virus scanning on the repo and output folder, I've seen that impact build times.

On my work machine (an i7 with 32GB ram) it takes less than 10 minutes to F5 in that scenario. It takes a little longer on my laptop (also an i7 but with less ram), maybe 15-20 minutes?

Unfortunately C++ compilation is _very_ resource intensive so it could be that 4GB memory is causing lots of paging during compilation which is causing lots of disk activity, etc.

**Comment by MuziburRahman** [comment]
100 % disk. 
CPU use isn't that intensive as it normally gets when I build UWP apps.

**Comment by jevansaks** [comment]
I don't think there's much that can be done here. I can leave this question open for a bit in case others from the community have any advice.
