### ISSUE TITLE
Changing NavigationView's PaneDisplayMode also raises SelectionChanged event

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#148]
**Describe the bug**

When NavigationView changes its PaneDisplayMode between Auto and Top, it also raises a SelectionChanged event, even though the selected item was not modified. This is problematic when the currently selected item is Settings, because the event args incorrectly report IsSettingsSelected as false.

**Steps to reproduce the bug**

1. Run sample project: [NavigationViewPaneModeApp.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2734375/NavigationViewPaneModeApp.zip)
2. Click Settings
3. Click "Change Pane Mode" button

**Expected behavior**

The NavigationView should change its orientation from vertical to horizontal, or vice versa, while keeping the Settings item selected.

What's actually happening is that the app is crashing on trying to access the content of the selected item, which is null.

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.1.181217001-preview

Windows 10 version:
- [x] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)

- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chausner** [comment]
I just ran into this issue with the latest WinUI 3 release (3.0.0-alpha.200210.0), so the issue should probably be re-opened. #1997 supposedly fixes it but that MR has not been merged yet.
