### ISSUE TITLE
~AnimatedVisualPlayer should not tank the process if a visual is still animating

### ISSUE THREAD

**Issue by jaredhms** [microsoft/microsoft-ui-xaml#1480]
Isn't there a way to gracefully recover from this within ~AnimatedVisualPlayer?  How about just stopping the player?  That's what I have to do in my dtor to work around this.

AnimatedVisualPlayer::~AnimatedVisualPlayer()
{
    if (m_nowPlaying != nullptr)
    {
        MUX_FAIL_FAST_MSG("Owner AnimatedVisualPlayer is destroyed, current playing AnimationPlay is not empty!");
    }
}

**Comment by jevansaks** [comment]
This failfast indicates that we have a bug in our code. Do you have a repro solution or an app that shows this that you could share out?

Also @improbabilityphysics @chewworker as FYI

**Comment by jaredhms** [comment]
I don't have a complete isolated repro to share, but this is a ReactNative Windows app that's implementing a scoped LottieAnimationView.  As the app transitions through views, one LottieAnimationView is destructed while the player is still playing, causing the fail fast.  Why can't the destructor simply call stop?

**Comment by jevansaks** [comment]
This is likely a loaded/unloaded ordering problem and points to maybe some other things going awry in the internal state machine. Calling Stop in the destructor would likely be fine. I don't know why it wasn't done that way before, I'm hoping @improbabilityphysics or  @simeoncran remembers.

**Comment by simeoncran** [comment]
This seems to indicate that OnLoaded was called, but there was no OnUnloaded before the destructor ran. The failfast there is there to assert that this is not a valid state. @jevansaks  - is this state actually expected?

**Comment by jevansaks** [comment]
> This seems to indicate that OnLoaded was called, but there was no OnUnloaded before the destructor ran.

Yes, this is a problem that the XAML framework has had for a while. IIRC Loaded fires async but Unloaded is sync so you can get out-of-order and also inconsistent number of events. In RS5 framework added the IsLoaded property which I believe can be used as a replacement to get more reliable event ordering. Or maybe not a replacement but in conjuction with? @ddalp @mikehillberg where did this end up?
