### ISSUE TITLE
uwp: Binding to ElementName doesn't work

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#1483]
**Describe the bug**

Porting this from WPF:
I used to have a lot of Width="{Binding ElementName=grid,Path=ActualWidth}" , which would bind to another element's ActualWidth. Sadly (but not unexpectedly), it doesn't work on UWP.

**Steps to reproduce the bug**

This doesn't work as expected:

    <Grid x:Name="grid">
        <Canvas Width="{Binding ElementName=grid,Path=ActualWidth}" 
                Height="{Binding ElementName=grid,Path=ActualHeight}" 
                x:Name="canvas" />
    </Grid>

This works:

	<Grid x:Name="grid" SizeChanged="Grid_OnSizeChanged">
		<Canvas x:Name="canvas" />
	</Grid>
	private void Grid_OnSizeChanged(object sender, SizeChangedEventArgs e) {
		canvas.Width = grid.ActualWidth;
		canvas.Height = grid.ActualHeight;
	}

**Expected behavior**
Using the binding, should basically be the equivalent of:
            canvas.Width = grid.ActualWidth;
            canvas.Height = grid.ActualHeight;
but it's not

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)        | Yes   | 

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |

**Comment by kmgallahan** [comment]
Did you try `{x:Bind grid.ActualWidth, Mode=OneWay}`?

**Comment by dpierangeli** [comment]
Too much DnD.. i've read 'Binding an Elemental doesn't work'... :)

**Comment by kmgallahan** [comment]
> So to see if I understand correctly - I should always handle SizeChanged for my scenario, and update my children there.

Yes, that would be the solution for Canvas content. You could technically slap together a new bindable property [along these lines](https://stackoverflow.com/questions/1602148/binding-to-actualwidth-does-not-work).

**Comment by jtorjo** [comment]
Thanks, that works

**Comment by michael-hawker** [comment]
🦙 FYI for the future we have [extensions in the Windows Community Toolkit for ActualWidth/Height binding here](https://docs.microsoft.com/windows/communitytoolkit/extensions/frameworkelementextensions#enableactualsizebinding).
