### ISSUE TITLE
Question: Select nodes in the TreeView

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1489]
I've spent the best part of today on this, and am not sure the right way to do this without putting a hack like a Task.Delay in place.

First up, I'm on 2.2.190917002.

I am showing a content dialog which contains a bunch of categories. This is invoked from another view model, for manipulating an item (`ItemViewModel`). The view model which backs the content dialog (`CategorySelectorViewModel`) has a property which the `ItemViewModel` sets containing the IDs of categories to select. The `CategorySelectorViewModel` binds the treeview to an `ObservableRangeCollection<Category>` (this object is from James Montemagno and extends `ObservableRangeCollection`.

In an ideal world, I would probably have an IsSelected object on the `Category` and bind that to the node is selected property, however I am using a database object from another layer in our stack which I can't change and I would prefer not to create a new class just to do this.

The `TreeView` has a `DataContextChanged` property but it seems that there is no guarantee that 1) the items exist in the list view, or that 2) the selected items property is non null. 

I'm currently working around this issue with a Task.Delay, but I would rather not have this if I could avoid it:

        /// <summary>
        /// Fired when the binding context for the treeview is changed.
        /// </summary>
        private async void treeView_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
        {
            // Wait until we have a treeview and selected items
            while (treeView == null || treeView.SelectedItems == null)
                await Task.Delay(Constants.__WAIT_DELAY); // This is 50ms

            var flattenedCategories = ViewModel.Categories.Flatten(x => x.Subcategories);

            foreach (var id in ViewModel.InitialSelectedCategories.Select(x => x.Id))
            {
                var categoryToSelect = flattenedCategories.Where(x => x.Id == id).SingleOrDefault();
                if (categoryToSelect == null)
                    continue;

                treeView.SelectedItems.Add(categoryToSelect);

            }
        }

I think I need an event which is fired after the data binding has completed and the items are added?

Thoughts appreciated.

**Comment by kaiguo** [comment]
The ItemsSource binding was implemented in an async way initially, I tried removing it and everything seemed to be working just fine. 

https://github.com/microsoft/microsoft-ui-xaml/blob/ed988d471e56464cc9f73c5b0a606a8a8df0d03c/dev/TreeView/TreeViewItem.cpp#L324-L337

@knightmeister Could you try the package produced in this [build](https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=44715) and see if it fixes the problem? The binding should be synchronous now and hopefully you don't need Task.Delay anymore.

**Comment by kaiguo** [comment]
I uploaded the package here: [Microsoft.UI.Xaml.2.3.191026001-prerelease.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3774320/Microsoft.UI.Xaml.2.3.191026001-prerelease.zip)

**Comment by jevansaks** [comment]
@kaiguo sounds like this should be changed to a bug?
