### ISSUE TITLE
ColorPicker broken if placed in ContentDialog in Windows Mobile

### ISSUE THREAD

**Issue by COM8** [microsoft/microsoft-ui-xaml#15]
**Describe the bug**
If you add a ColorPicker to a ContentDialog and publish the app to a Windows Mobile device, it's broken visually like shown in the image below.
The red dot represents where you tap which results in the circle having some wired offset.

If you place one on a normal page it works like expected.
<img src="https://i.imgur.com/kLKQMK4.png" width="400">

**Steps to reproduce the bug**
1. Create ContentDialog
2. Add a ColorPicker to the dialog
3. Publish the app to a mobile device

```XML
<ContentDialog x:Class="AcvMemTest.ColorPickerDialog"
               xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
               xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
               xmlns:controlsComp="using:Microsoft.UI.Xaml.Controls"
               xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
               xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
               Title="TITLE"
               PrimaryButtonClick="ContentDialog_PrimaryButtonClick"
               PrimaryButtonText="Button1"
               SecondaryButtonClick="ContentDialog_SecondaryButtonClick"
               SecondaryButtonText="Button2"
               mc:Ignorable="d">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <controlsComp:ColorPicker x:Name="color_cp"
                                  Grid.Row="0"
                                  ColorSpectrumShape="Ring"
                                  IsAlphaEnabled="False"
                                  IsColorPreviewVisible="True"/>
    </Grid>
</ContentDialog>
```

**Expected behavior**
The ColorPicker should work in Windows Mobile ContentDialogs.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.181025003-prerelease

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [x] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [ ] Desktop
- [x] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**
Test device: Lumia 950XL
Target version: 17763
Min version: 15063

**Comment by jevansaks** [comment]
Good find! Is the ContentDialog necessary for the repro or is ColorPicker just not working on Lumia 950XL?

**Comment by COM8** [comment]
If you put the ColorPicker on a normal Page it works.
As soon you put it into a ContentDialog it's broken.
The only Windows Mobile device that I own is a Lumia 950XL so that's the only device I was able to validate this issue on.

**Comment by COM8** [comment]
I've created a simple test project: https://github.com/COM8/Control-Test
Just clone it and publish it to your phone.
Once started you can click on the `Add` button to show a `ContentDialog` hosting a `ColorPicker` control.

**Comment by Scherlac** [comment]
1>------ Deploy started: Project: AcvMemTest, Configuration: Release ARM ------
Creating a new clean layout...
Copying files: Total 8 mb to layout...
Checking whether required frameworks are installed...
Framework: Microsoft.UI.Xaml.2.0/ARM, app package version **2.1810.18003.0** is not currently installed.
Installing missing frameworks...
Registering the application to run from layout...
Deploying to Phone Internal Storage...
Deployment complete (0:00:17,668). Full package name: "fcf4610a-1d84-4269-8f55-f6501ea750a8_1.0.0.0_arm__9j9pnhqt7x5t4"
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========


This is how the screen looks like after pressing the add button:
![wp_ss_20181227_0002](https://user-images.githubusercontent.com/12424871/50488474-0b2a1e00-0a03-11e9-85dc-f11ee87440bc.png)

**Comment by COM8** [comment]
Weird for me it's broken. Which Windows 10 Mobile OS build is your phone running on?
Mine is running on `10.0.15254.544`.
`Settings` -> `System` -> `About` -> `More`

**Comment by Scherlac** [comment]
Mine is also 1709 / 10.0.15254.544
The above  test was with:

> Checking whether required frameworks are installed...
> Framework: Microsoft.UI.Xaml.2.0/ARM, app package version **2.1810.18003.0** is not currently installed.
> Installing missing frameworks…

I would like to test with prerelease version, but after installing prerelease nuget package for the project my device doesn't get updated to that version.

How to remove UI.Xaml framework from device?

**Comment by jevansaks** [comment]
Sorry for the delay, I was on vacation. 

If you have a debugger attached to the process with native debugging you should be able to check the version of Microsoft.UI.Xaml.dll -- it should be 2.1.1812.17001.

**Comment by COM8** [comment]
Had access to a WILEYFOX W10 phone and on it all looks good.
Then I did a factory reset on my Lumia 950 XL. Still same result.

**Comment by eugenegff** [comment]
Lumia 650 - can not repeat the problem as shown on screenshot, but in ContentDialog case ColorSpectrum ring is drawn with visible delay around 0.3s, and after repeated "add","back",...  in ~20% cases remains white till the click on it.

**Comment by eugenegff** [comment]
All of this could be fixed by having std::atomic<unsigned> m_workItemCounter, incrementing it in memory_order_relaxed mode, capturing incremented value in AsyncActionCompletedHandler lambda and comparing the results instead of asyncStatus. Nullifying of the createImageBitmapAction should be done later, on dispatcher thread, and again only after yet another check that workItemCounter is equal to captured value.

**Comment by jevansaks** [comment]
@eugenegff sounds like you have a really good handle on this problem. Do you want to [contribute a fix](https://github.com/microsoft/microsoft-ui-xaml/blob/master/CONTRIBUTING.md#code-contribution-process)?

**Comment by chingucoding** [comment]
Since Windows Mobile is now discontinued, should we still keep this issue in the backlog?

**Comment by StephenLPeters** [comment]
agreed, no longer seems relevant.
