### ISSUE TITLE
AnimatedVisualPlayer doesn't appear to allow playing animations in reverse

### ISSUE THREAD

**Issue by jaredhms** [microsoft/microsoft-ui-xaml#1502]
LottieView allows you to invert the start/end frames to play the animation in reverse.  However, AnimatedVisualPlayer doesn't appear to support wiring this up.

Here's how it's handled on Android, but I don't see a way to support this functionality on Windows:
https://github.com/react-native-community/lottie-react-native/blob/efd58fab776c2043775f16a07d57e7893acff1fb/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java#L116

**Comment by simeoncran** [comment]
To play in reverse, set the playback rate to -1.
See: https://docs.microsoft.com/en-us/windows/communitytoolkit/animations/lottie-scenarios/playback
The design is intended to allow playing of sections of loops that roll over the end point in either direction. The sign of the playback rate determines direction. The start and end points determine the start and end points.
