### ISSUE TITLE
Proposal: Add more build-in StateTriggers

### ISSUE THREAD

**Issue by maxkatz6** [microsoft/microsoft-ui-xaml#1504]
# Proposal: Add more build-in StateTriggers

## Summary
Add more StateTriggers that can be used in VisualStateManager-driven UI development.

## Rationale
* Make VisualStateManager more usable and flexible
* Reduce needs of custom StateTriggers, when they can be build in
* WPF hasn't any kind of StateTriggers, so it should with WinUI 3.0 support

## Scope
| Capability | Priority |
| :---------- | :------- |
| Triggers with logic composition of another state triggers (And, Or, Not) | Must |
| Equality and comparison triggers | Must |
| String triggers (RegexMatch, IsNullOrEmpty) | Should |
| Available for C++ projects | Should |
| Platform specific triggers (InputType, DeviceFamily, Orientation) | Could |
| Backport StateTriggers to WPF (WinUI 3.0) | Could |

## Important Notes
There is already created collection of StateTriggers from community:
https://github.com/dotMorten/WindowsStateTriggers
Usage example: [Samples/CompositeSample.xaml#L13-L41](https://github.com/dotMorten/WindowsStateTriggers/blob/master/src/TestApp/Samples/CompositeSample.xaml#L13-L41)
It works fine, but it is .Net-only lib and is not maintained anymore (last commit in 2016).
Scope was based on WindowsStateTriggers.

**Comment by mdtauk** [comment]
Devices like Surface Duo and Neo should be considered when designing new Triggers.

And if WinUI apps were ever to become a cross platform option with Android, then Triggers to support system calls should also be considered...

**Comment by Tirraon** [comment]
I have also found some StateTriggers in Windows Calculator repository:
https://github.com/microsoft/calculator/tree/master/src/Calculator/Views/StateTriggers

**Comment by Tirraon** [comment]
> Devices like Surface Duo and Neo should be considered when designing new Triggers.

Agree, DeviceFamilyStateTrigger from WindowsStateTriggers already supports something like that: Desktop, Mobile, Xbox, Hololens, but without Duo/Neo, because they were not exist in 2016.

**Comment by Tirraon** [comment]
There is already created issue to improve StateTriggerBase: https://github.com/microsoft/microsoft-ui-xaml/issues/1460

**Comment by Tirraon** [comment]
After some research I have found, that @dotMorten has started porting WindowsStateTriggers to https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3030

I am not sure, how features are distributed between WinUI and CommunityToolkit. And are they related at all.
So I will leave this issue at least for discussion.

**Comment by dotMorten** [comment]
@Tirraon I'd personally like to see 1460 you linked to addressed first, as this opens up the ability to create much more advanced triggers. I really don't care where the set of extra triggers live, but I'd lean towards the community toolkit and keep the main WinUI framework leaner and meaner.
