### ISSUE TITLE
AnimatedVisualPlayer.PlayAsync often completes before the animation is actually finished rendering/animating

### ISSUE THREAD

**Issue by jaredhms** [microsoft/microsoft-ui-xaml#1510]
One of our animations is performed in 3 phases: 1. Play the 'inrto', 2. Loop in the middle, 3. Play the 'outro'.

It often works fine, but other times the 'intro' phase completes almost immediately.

Phase 1: Play from 0.0->43.333
Phase 2: Once phase 1 completes, loop from frames ~43.333->80.00
Phase 3: Upon an external trigger, animate from ~80.00->100.0

The problem is that we're often seeing 'phase 1' complete almost immediately, so our animation just 'jumps' to the middle looping phase.

**Comment by simeoncran** [comment]
@jaredhms any chance of a simple repro?
