### ISSUE TITLE
Failed to navigate to a XAML View page by using HyperlinkButton

### ISSUE THREAD

**Issue by hemantbajpai4** [microsoft/microsoft-ui-xaml#1515]
Affected Branch: master
Affected Build: 29422.223
Affected SKU: ENT
Affected Product Language:  EN
Operation System Information:19h1
Machine: XETLAB030(10.195.200.193）
Workloads:.NET desktop development + Universal Windows Platform development
 
**Steps to reproduce**:
1. Create a C# Blank App(Universal Windows).
2. Right project->Add new item->Try to add a XAML View to the project and named it as 'Page1.xaml'->Change the background of Grid as LightBlue.
2. Open MainPage.xaml, and type below code inside the Grid.
`<HyperlinkButton Content="Click to go to page1" Click="HyperlinkButton_Click" HorizontalAlignment="Center" Height="50" Width="500"/>`
3. Open MainPage.xaml.cs, type below code to handle the click event of HyperlinkButton to navigate to the page1.xaml.
```
private void HyperlinkButton_Click(object sender, RoutedEventArgs e)
{
this.Frame.Navigate(typeof(Page1));
}
```
4. F5 ->Click the HyperlinkButton
 ​
**Expect**:
Page1 can be opened.
 
**Actual**:
Page1 can not be opened.

**Comment by jevansaks** [comment]
Sorry, this worked for me. Could you make a simple repro app?
