### ISSUE TITLE
SplitButton & ToggleSplitButton's chevron gets clipped when text scaling >= ~200%.

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/microsoft-ui-xaml#1519]
**Describe the bug**
The SplitButton & ToggleSplitButton each use a chevron for their dropdown menu, and it gets clipped when text scaling is set high enough (~200%). Preceding that it goes off-center to the left more and more.

**Steps to reproduce the bug**
1. Set text scaling to 200% or 225%
2. Open the XAML Controls Gallery
3. View the SplitButton and/or ToggleSplitButton

**Expected behavior**
It should remain centered and not get clipped. The DropDownButton is an example of the best case scenario. However, a quick and dirty solution would be to set `IsTextScaleFactorEnabled="false"`, as was done with [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/1413).

**Screenshots**
![Annotation 2019-10-31 095017](https://user-images.githubusercontent.com/5379488/67952562-e1fa9100-fbc3-11e9-87ad-a354acd50eb2.png)

![Annotation 2019-10-31 094930](https://user-images.githubusercontent.com/5379488/67952505-ca230d00-fbc3-11e9-8236-275c6ef9df7c.png)

**Version Info**
XAML Controls Gallery version 1.2.10.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by adrientetar** [comment]
Yeah I'm not sure about that IsTextScaleFactorEnabled workaround, although it's in the guidelines apparently I mean say you're on 300 or 400% scaling it means you have a large text with a very small icon? I would think allocating more space is the proper resolution indeed.

**Comment by kmgallahan** [comment]
@adrientetar The Settings app's slider only goes up to 225%. 

Although there might be a way to go higher elsewhere (registry?), I'd consider 225% to be the highest "supported" text scale factor that all stock controls should take into consideration. That is to say, although it might not look optimal at 300-400% scaling, it looks fine enough for lower values. 

A quick fix is better than doing nothing due to the complications involved (#275, #1454).

**Comment by jevansaks** [comment]
Agree that the chevron shouldn't get bigger as only text should. We should just set IsTextScaleFactorEnabled=false on the chevron.

**Comment by chingucoding** [comment]
@jevansaks I would be happy to fix this :)

**Comment by kmgallahan** [comment]
> Agree that the chevron shouldn't get bigger as only text should. We should just set IsTextScaleFactorEnabled=false on the chevron.

Should this be the case for any chevrons used throughout WinUI controls?

Other examples:

- DropDownButton
- ~~TreeView~~ already changed
- CalendarDatePicker
- CalendarView
- ~~DatePicker~~ already not scaled
- ~~DatePicker~~ already not scaled

**Comment by chingucoding** [comment]
> > Agree that the chevron shouldn't get bigger as only text should. We should just set IsTextScaleFactorEnabled=false on the chevron.
> 
> Should this be the case for any chevrons used throughout WinUI controls?
> 
> Other examples:
> 
> * DropDownButton
> * ~TreeView~ already changed
> * CalendarDatePicker
> * CalendarView
> * ~DatePicker~ already not scaled
> * ~TimePicker~ already not scaled

I don't think that those three need to change, since those do not begin to look weird or start clipping:
(Screenshots taken with text scaling set to 225%)
DropDownButton:
![image](https://user-images.githubusercontent.com/16122379/67993660-262c7680-fc42-11e9-9043-0a1d3de99523.png)

CalendarDatePicker:
![image](https://user-images.githubusercontent.com/16122379/67993706-55db7e80-fc42-11e9-9a8d-c50896c580fa.png)

CalendarView:
![image](https://user-images.githubusercontent.com/16122379/67993676-33e1fc00-fc42-11e9-8344-67dfb1650c69.png)

**Comment by kmgallahan** [comment]
@chingucoding For the DropDownButton at least I think it is more a case of consistent sizing, rather than fixing visual issues.

It's possible a DropButtonButton could appear right next to a SplitButton / ToggleSplitButton and the chevrons would have mixed sizes.
