### ISSUE TITLE
Conditional XAML doesn't work for Attached Properties

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#1526]
Originally Filed here: https://github.com/MicrosoftDocs/windows-uwp/issues/1378

**Describe the bug**
Conditional XAML doesn't seem to work on Attached Properties.  No mention of this limitation was called out in the docs, thus the original bug above.  This should be expected to work?

**Steps to reproduce the bug**
Create a class library
Add `contract6Present:AutomationProperties.HeadingLevel="Level2"` to your XAML.
Get this error: `XAML Binary Format (XBF) generator reported syntax error '0x09cc'` in VS 

Another user reported:
```
                            <Windows10version1809:Grid.BackgroundTransition>
                                <Windows10version1809:BrushTransition />
                            </Windows10version1809:Grid.BackgroundTransition>
```

**Expected behavior**
No error, conditional XAML should work.

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@danzil is this a known issue?

**Comment by danzil** [comment]
Looks like something we should look at according to @alwu-msft

**Comment by stevenbrix** [comment]
@michael-hawker do you think there is a need for conditional xaml with WinUI3? It was created to solve the downlevel issue, which seems to be a problem we should fundamentally no longer have with WinUI3.

**Comment by michael-hawker** [comment]
@stevenbrix assuming everything works in WinUI3 for all OS versions with the exact same behavior, will that still be the case for all OS platforms? I can also see the `IsTypePresent` and `IsPropertyPresent` conditionals being useful for other libraries and cases beyond just WinUI, especially if loaded via dependency injection?

**Comment by stevenbrix** [comment]
> assuming everything works in WinUI3 for all OS versions with the exact same behavior, will that still be the case for all OS platforms?

Yes, that is the main motivation for lifting the entire WinUI platform out of the OS :)

>I can also see the IsTypePresent and IsPropertyPresent conditionals being useful for other libraries and cases beyond just WinUI, especially if loaded via dependency injection?

Interesting, I hadn't thought of that! Can you explain why they would be useful? It would be nice to have a better understanding of what problems it solves in the WinUI3 world.

**Comment by michael-hawker** [comment]
@stevenbrix sorry for the delayed response with the holidays.

I see a scenario, especially in a Win32 container, where certain modules are loaded dynamically in a program.  There may be some that are purchased separately or part of some separate edition.  There could be a case where the main program still needs to know about if a Type is present for detection to change UI display based on that info.

**Comment by sylveon** [comment]
Seems to work for me? this builds
```xaml
<Page
    xmlns:muxcWindows11Present="using:Microsoft.UI.Xaml.Controls?IsApiContractPresent(Windows.Foundation.UniversalApiContract, 14)"
    xmlns:windows11NotPresent="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractNotPresent(Windows.Foundation.UniversalApiContract, 14)"
    muxcWindows11Present:BackdropMaterial.ApplyToRootOrPageBackground="True"
    windows11NotPresent:Background="{StaticResource SystemControlChromeMediumLowAcrylicWindowMediumBrush}">
```

**Comment by evelynwu-msft** [comment]
Does not repro with WinAppSDK 1.3.
