### ISSUE TITLE
Unable to build solution

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1527]
**Describe the bug**
I am unable to build the solution in VS Community 2019

**Screenshots**
![image](https://user-images.githubusercontent.com/7389110/68010333-3bbe9200-fc7c-11e9-9d5d-f42bfdc2ca70.png)

**Version Info**
Visual Studio Community 2019 Preview - 16.4.0 Preview 2.0

**Additional context**
Source file ____ could not be found.    MUXControlsTestAppWPF
- NavigationViewTestPage.g.cs
- XamlTypeInfo.g.cs
- NavigationViewTestPage.g.i.cs
- MainPage.g.cs
- MainPage.g.i.cs

Then there are lots of xbf files not found ( MUXControlsTestAppForIslands )

The project 'Microsoft.UI.Xaml' cannot be referenced.	MUXControlsTestAppWPF

Found conflicts between different vevrsions of ____ that could not be resolved.

and lots of other errors.

**Comment by chingucoding** [comment]
Can you look what the output of the build process is? I have noticed, that sometimes the output from the build process and the error output/list of Visual Studio differ with the error list being somewhat unreliable. Taking a look at the output window can help identify what is failing.

**Comment by jevansaks** [comment]
Also please attach the full build output? Usually something failed to build early on and the errors window is sorted in a very unhelpful way (the top error is not the first error).

**Comment by jevansaks** [comment]
It also occurred to me that you might not have all of the C++ support installed. Try installing all the optional C++ components too.
