### ISSUE TITLE
MenuBar Vertical Orientation???

### ISSUE THREAD

**Issue by dan-meier** [microsoft/microsoft-ui-xaml#1528]
Is it not possible to create a vertical menu using the MenuBar control???  I haven't found a way to do this, but perhaps I'm missing something...

**Comment by mdtauk** [comment]
I don't believe the MenuBar control has an orientation property.  You should add a feature request for that feature.

MenuBar.Orientation.Top/Bottom/Left/Right maybe, with the direction of the flyout menus set correctly as the orientation changes

**Comment by jevansaks** [comment]
This isn't supported for MenuBar. Depending on your scenario it might be more appropriate to use NavigationView for a left-docked bar. With the upcoming hierarchical support (#79) this might cover your needs.

**Comment by dan-meier** [comment]
Unfortunately, the NavigationView won't work in the scenario I'm working with.  I'm simply launching open file dialogs and the like, so the "back" button is problematic.  I would use the Menu control in the Windows Community Toolkit (which has an Orientation property), but I'm scared away by the warning banner indicating, "This control will be removed in a future release. Please use the MenuBar control from the WinUI library instead."  Doh!

**Comment by chingucoding** [comment]
You can disable and hide the "back" button by setting `IsBackEnabled="False"` and `IsBackButtonVisible="Collapsed"` respectively. So that would make it feel a bit more like a MenuBar.
