### ISSUE TITLE
Proposal: WinUI 3.0 -  VS template descriptions for Windows Runtime Components

### ISSUE THREAD

**Issue by thomasclaudiushuber** [microsoft/microsoft-ui-xaml#1533]
To me it looks like the description of the Windows Runtime Component template for C++ is a bit off, as it talks about "Windows Universal apps" while all other template descriptions talk about "Universal Windows Platform apps". Also the word "Component" starts with a lowercase letter for the C++ template and starts with a capital letter for the C# template. Here the screenshot from the docs.

![image](https://user-images.githubusercontent.com/7116546/68129520-0040f380-ff1a-11e9-9253-0aa473b7b5d7.png)

I suggest to adjust/align the description for the C++ component to this:

**"A project for creating a C++/WinRT Windows Runtime Component for Universal Windows Platform apps based on the Windows UI Library (WinUI)."**

And in the C# component description, get rid of the comma before "based", it should look like this:

**"A project for creating a managed Windows Runtime Component for Universal Windows Platform apps based on the Windows UI Library (WinUI)."**

**Comment by danzil** [comment]
Thanks for the feedback @thomasclaudiushuber! We'll reevaluate these descriptions when we add more language templates.

**Comment by SavoySchuler** [comment]
@ranjeshj or @fabiant3, I believe this issue may need to see triage again?
