### ISSUE TITLE
WinUI 3.0α : Scrollviewer behaves strangely with touchpad scroll

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1536]
**Describe the bug**

When scrolling a `ScrollViewer`/`GridView` with touchpad (using 2 finger swipes) the scrolling behaves strangely. When reaching the bottom, using the 2 finger gestures one can swipe even further down despite there not being items. I found this while using the WinUI 3.0α version of the XCG.
**Steps to reproduce the bug**

1. Visit page with ScrollViewer
2. Scroll down using touchpad

**Expected behavior**

The scrolling is smooth, and one should not be able to scroll further down when reaching the bottom.

**Screenshots**

![winui3-scrollviewer](https://user-images.githubusercontent.com/16122379/68141329-93375900-ff2d-11e9-87a2-86de4320070d.gif)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 3.0.0-alpha.191101.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19013)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jesbis** [comment]
Thanks @chingucoding! Gifs are super helpful!

That sounds like the known issue mentioned here: 

https://docs.microsoft.com/uwp/toolkits/winui3/#interactivity

> Interactivity
Multi-touch interactions on a touchscreen or precision touchpad can make scrolling and touch responsiveness unpredictable within the app and should be avoided at this time.

**Comment by chingucoding** [comment]
Oh I did not see that section,my bad 😅
