### ISSUE TITLE
Issue using winui in arm64

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#1537]
**Describe the bug**
Crash when buliding app using arm64 version of winui

**Steps to reproduce the bug**
Yup, repro should be:

1)	Clone Toolkit repo: https://github.com/windows-toolkit/WindowsCommunityToolkit
2)	Make sure to do msbuild /restore from root in VS Dev prompt (see https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3012)
3)	Open VS (should default to building Microsoft.Toolkit.Uwp.SampleApp) change to ARM64
4)	Build/Run app deployed to an ARM64 device
5)	Crash

**Comment by danzil** [comment]
@ranjeshj, I think @RealTommyKlein added an error to specifically call out we don't yet support ARM/ARM64.

**Comment by RealTommyKlein** [comment]
Is this issue for the WinUI 3.0 alpha, or WinUI 2.x?  I don't see a WinUI 3.0 branch of the WindowsCommunityToolkit, and when building ARM and ARM64 versions of the WinUI 3.0 alpha XamlControlsGallery I do see the expected build errors that ARM isn't supported yet.

**Comment by ranjeshj** [comment]
This is for 2.x (unrelated to winui3alpha).

**Comment by ranjeshj** [comment]
This seems to be an issue with one of the IXMP providers in projects referenced by the app. A simple app with MUX built for arm64 seems to work fine.
