### ISSUE TITLE
Setting SelectionFollowsFocus causes focus rect to not render

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1539]
**Describe the bug**

When NavigationView's SelectionFollowsFocus="Enabled", the menu items no longer render focus rects while they have keyboard focus.

**Steps to reproduce the bug**

1. Create new test app with 
```xaml
    <muxc:NavigationView PaneDisplayMode="Auto" SelectionFollowsFocus="Enabled">
        <muxc:NavigationView.MenuItems>
            <muxc:NavigationViewItem Icon="Play" Content="Menu Item1" Tag="SamplePage1" />
            <muxc:NavigationViewItem Icon="Save" Content="Menu Item2" Tag="SamplePage2" />
        </muxc:NavigationView.MenuItems>
        <Frame x:Name="contentFrame">
            <Grid>
                <Button>Hello</Button>
            </Grid>
        </Frame>
    </muxc:NavigationView>
```
2. Tab through the controls in the app
3. Note that the focus rect disappears between  hamburger and settings buttons.
4. Change SelectionFollowsFocus to Disabled.
5. Note focus draws as expected.

**Expected behavior**

When one of the MenuItems has keyboard focus, a focus rect is drawn around it.

**Screenshots**
![NavigationViewFocus](https://user-images.githubusercontent.com/13142665/68164123-e0f19880-ff10-11e9-99de-d426b7622f9b.gif)

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/23886593)

**Comment by chingucoding** [comment]
I would like to look into this.
