### ISSUE TITLE
Unhandled exception at Windows.UI.Xaml.dll (Access violation)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#1540]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/803359/unhandled-exception-at-windowsuixamldll-access-vio.html)._

---
<p>Our team is working on a UWP application which includes Drag-and-Drop functionality. </p><p><strong>Context</strong>: </p><p>We have a user control which is reused in multiple places in the application. We need to enable and </p><p>disable &quot;CanDrag&quot; on this user control in different places based on the requirements. </p><p>The exception occurs when I do the following steps. </p><p>1. Start the application. &quot;CanDrag&quot; is disabled for this user control in the main page. </p><p>2. Click on a particular button in our application. </p><p>3. &quot;CanDrag&quot; is enabled for the user control when the button in step 2 is invoked. </p><p>4. Click the button in step 2 again. The view switches back to the original view  and &quot;CanDrag&quot; is set to false for the user control.</p><p>5. As soon as the original view is shown, click on the usercontrol multiple times continuously as fast as one can. </p><p><strong>Result: Exception thrown: read access violation.
this was nullptr. <br></strong></p><p><strong>Visual studio debugger points to automaticdraghelper.cpp file which is not present in my </strong></p><p><strong>system.</strong></p><p><strong><br></strong></p><p><strong>Basically clicking on a control multiple times during &quot;CanDrag&quot; is being switched to a new value causes this exception.</strong></p><p><strong><br></strong></p><p><strong>The exception occurs with both mouse and touch interaction.</strong></p><p><strong><br></strong></p><p><strong>Please find the callstack below when the above steps are performed with mouse clicks.</strong></p><p>&gt;Windows.UI.Xaml.dll!DirectUI::<strong>AutomaticDragHelper</strong>::HandlePointerReleasedEventArgs(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pArgs) Line 310C++
 Windows.UI.Xaml.dll!DirectUI::UIElement::OnPointerReleased(IInspectable * pSender, Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pArgs) Line 254C++
 Windows.UI.Xaml.dll!DirectUI::ClassMemberEventHandler&lt;DirectUI::UIElement,Windows::UI::Xaml::IUIElement,Windows::UI::Xaml::Input::IHoldingEventHandler,IInspectable,Windows::UI::Xaml::Input::IHoldingRoutedEventArgs&gt;::Invoke(IInspectable * pSender, Windows::UI::Xaml::Input::IHoldingRoutedEventArgs * pArgs) Line 663C++
 Windows.UI.Xaml.dll!DirectUI::CRoutedEventSourceBase&lt;DirectUI::IUntypedEventSource,Windows::UI::Xaml::Input::IPointerEventHandler,IInspectable,Windows::UI::Xaml::Input::IPointerRoutedEventArgs&gt;::Raise(IInspectable * pSource, Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pArgs) Line 1041C++
 Windows.UI.Xaml.dll!DirectUI::CRoutedEventSourceBase&lt;DirectUI::IUntypedEventSource,Windows::UI::Xaml::Input::IPointerEventHandler,IInspectable,Windows::UI::Xaml::Input::IPointerRoutedEventArgs&gt;::UntypedRaise(IInspectable * pSource, IInspectable * pArgs) Line 995C++
 [Inline Frame] Windows.UI.Xaml.dll!DirectUI::DependencyObject::FireEvent(KnownEventIndex) Line 3475C++
 Windows.UI.Xaml.dll!DirectUI::DXamlCore::FireEvent(CDependencyObject * pCoreListener, KnownEventIndex eventId, CDependencyObject * pCoreSender, CEventArgs * pCoreArgs, unsigned int flags) Line 1962C++
 [Inline Frame] Windows.UI.Xaml.dll!AgCoreCallbacks::FireEvent(CDependencyObject *) Line 91C++
 [Inline Frame] Windows.UI.Xaml.dll!CFxCallbacks::JoltHelper_FireEvent(CDependencyObject *) Line 1035C++
 Windows.UI.Xaml.dll!CCoreServices::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 3224C++
 Windows.UI.Xaml.dll!CommonBrowserHost::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 771C++
 Windows.UI.Xaml.dll!CControlBase::ScriptCallback(void * pControl, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pInternalHandler) Line 267C++
 Windows.UI.Xaml.dll!CXcpDispatcher::OnScriptCallback(CEventInfo * pEventInfo) Line 1336C++
 Windows.UI.Xaml.dll!CXcpDispatcher::OnWindowMessage(HWND__ * msg, unsigned int wParam, unsigned int lParam, long) Line 1187C++
 Windows.UI.Xaml.dll!CXcpDispatcher::ProcessMessage(HWND__ * msg, unsigned int wParam, unsigned int lParam, long plRet, long * pbDoDefault, unsigned int *) Line 909C++
 Windows.UI.Xaml.dll!CXcpDispatcher::WindowProc(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam) Line 837C++
 user32.dll!__InternalCallWinProc@20&#30;()Unknown
 user32.dll!UserCallWinProcCheckWow()Unknown
 user32.dll!DispatchClientMessage()Unknown
 user32.dll!___fnDWORD@4&#30;()Unknown
 ntdll.dll!_KiUserCallbackDispatcher@12&#30;()Unknown
 user32.dll!SendMessageW()Unknown
 [Inline Frame] Windows.UI.Xaml.dll!CXcpDispatcher::SendMessageW(unsigned int) Line 807C++
 Windows.UI.Xaml.dll!CXcpBrowserHost::SyncScriptCallbackRequest(void * pVoidBH, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pHandler) Line 1048C++
 Windows.UI.Xaml.dll!CEventManager::RaiseHelper(xvector&lt;REQUEST *&gt; * pRegisteredRequests, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int bRefire, HRESULT(__stdcall*)(void *, CDependencyObject *, EventHandle, CDependencyObject *, CEventArgs *, int, IScriptObject *, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *)) pfnScriptCallback, unsigned int &amp; bFired, CDependencyObject * pSenderOverride) Line 1068C++
 Windows.UI.Xaml.dll!CEventManager::Raise(EventHandle hEvent, int bRefire, CDependencyObject * pSender, CEventArgs * pArgs, bool fRaiseSync, bool fInputEvent, bool bAllowErrorFallback, CDependencyObject * pSenderOverride) Line 902C++
 Windows.UI.Xaml.dll!CEventManager::RaiseRoutedEventBubbling(EventHandle hEvent, CDependencyObject * pSource, CRoutedEventArgs * pArgs, bool bIgnoreVisibility, bool fRaiseSync, bool fInputEvent, CDependencyObject * coerceToHandledAtElement) Line 1334C++
 [Inline Frame] Windows.UI.Xaml.dll!CEventManager::RaiseRoutedEvent(EventHandle hEvent, CDependencyObject *) Line 1241C++
 Windows.UI.Xaml.dll!CInputServices::RaiseDelayedPointerUpEvent(TouchInteractionMsg * pMsgGesture, CDependencyObject * pElement) Line 2663C++
 Windows.UI.Xaml.dll!CInputServices::ProcessGestureInput(CDependencyObject * pElement, TouchInteractionMsg * pMsg) Line 2414C++
 Windows.UI.Xaml.dll!CInputServices::ProcessTouchInteractionCallback(const xref_ptr&lt;CUIElement&gt; &amp; element, TouchInteractionMsg * message) Line 2310C++
 Windows.UI.Xaml.dll!CCoreServices::ProcessTouchInteractionCallback(const xref_ptr&lt;CUIElement&gt; &amp; element, TouchInteractionMsg * message) Line 1017C++
 Windows.UI.Xaml.dll!TIEAdapter::InteractionEngineCallback(const INTERACTION_CONTEXT_OUTPUT * const pOutputFromICM) Line 238C++
 Windows.UI.Xaml.dll!TIEAdapter::StaticInteractionEngineCallback(void * pvData, const INTERACTION_CONTEXT_OUTPUT * outputFromICM) Line 65C++
 ninput.dll!COutputConverter::Process(class CInteractionContextConfiguration const &amp;,enum InteractionContextProperties::MeasurementUnits,enum CInteractionContextGlobal::FeedbackSettings,struct DigitizerInfo const *,struct INTERACTION_INPUT const *,unsigned int,struct INTERACTION_OUTPUT const &amp;,int)Unknown
 ninput.dll!CInteractionContextImpl::OutputCallback(void *,struct INTERACTION_OUTPUT const *)Unknown
 ninput.dll!CInteractionGroupingFilter::_SendOutput(struct INTERACTION_OUTPUT const &amp;)Unknown
 ninput.dll!CInteractionGroupingFilter::_OnInput(struct INTERACTION_OUTPUT const &amp;)Unknown
 ninput.dll!CInteractionGroupingFilter::Input(void *,struct INTERACTION_OUTPUT const *)Unknown
 ninput.dll!COutputCoalescingFilter::Flush(void)Unknown
 ninput.dll!COutputCoalescingFilter::_OnInput(struct INTERACTION_OUTPUT const &amp;)Unknown
 ninput.dll!COutputCoalescingFilter::Input(void *,struct INTERACTION_OUTPUT const *)Unknown
 ninput.dll!CInteractionEngineImpl::DigitizerInput(enum DIGITIZER_KIND,unsigned __int64,unsigned int,unsigned int,struct INTERACTION_INPUT const *)Unknown
 ninput.dll!_ProcessInputInteraction@28&#30;()Unknown
 ninput.dll!CInteractionContextImpl::ProcessFrameHistory(unsigned int,unsigned int,struct tagPOINTER_INFO const *)Unknown
 ninput.dll!_ProcessPointerFramesInteractionContext@16&#30;()Unknown
 Windows.UI.Xaml.dll!ElementGestureTracker::ProcessPointerInformation(const InputMessage &amp; msg, Windows::UI::Input::IPointerPointStatics * const pointerPointStatics) Line 703C++
 Windows.UI.Xaml.dll!ElementGestureTracker::ProcessPointerMessage(const InputMessage &amp; msg, Windows::UI::Input::IPointerPointStatics * const pointerPointStatics) Line 91C++
 Windows.UI.Xaml.dll!CInputServices::ProcessPointerMessagesWithInteractionEngine(unsigned int pMsg, InputMessage * pInteractionElement, CUIElement * pManipulationElement, CUIElement * bIgnoreManipulationElement, unsigned int pInteractionContext, ElementGestureTracker * bForceDisableGesture, unsigned int) Line 1992C++
 Windows.UI.Xaml.dll!CInputServices::ProcessInteractionPointerMessages(unsigned int pointerId, InputMessage * pMsg) Line 1758C++
 Windows.UI.Xaml.dll!ContentRootInput::PointerInputProcessor::ProcessPointerInput(InputMessage * pMsg, int * handled) Line 716C++
 Windows.UI.Xaml.dll!CInputServices::ProcessInput(InputMessage * pMsg, CContentRoot * contentRoot, int * handled) Line 887C++
 Windows.UI.Xaml.dll!CCoreServices::ProcessInput(InputMessage * pMessage, CContentRoot * contentRoot, int * fHandled) Line 991C++
 Windows.UI.Xaml.dll!CXcpBrowserHost::HandleInputMessage(unsigned int uMsg, MsgPacket * pMsgPack, CContentRoot * contentRoot, bool &amp; fHandled) Line 1403C++
 Windows.UI.Xaml.dll!CJupiterControl::HandlePointerMessage(unsigned int uMsg, unsigned int wParam, long lParam, CContentRoot * contentRoot, Windows::UI::Input::IPointerPoint * pointerPoint, Windows::UI::Core::IPointerEventArgs * pointerArgs) Line 750C++
 Windows.UI.Xaml.dll!CJupiterControl::HandleWindowMessage(unsigned int uMsg, unsigned int wParam, long lParam, CContentRoot * contentRoot) Line 338C++
 Windows.UI.Xaml.dll!CJupiterWindow::CoreWindowSubclassProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 1084C++
 Windows.UI.Xaml.dll!CJupiterWindow::StaticCoreWindowSubclassProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 576C++
 user32.dll!__InternalCallWinProc@20&#30;()Unknown
 user32.dll!UserCallWinProcCheckWow()Unknown
 user32.dll!DispatchMessageWorker()Unknown
 user32.dll!_DispatchMessageW@4&#30;()Unknown
 Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessMessage(bool bDrainQueue, bool * pbWindowMessagesProcessed, bool * pbInvokeItemProcessed) Line 327C++
 Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal(bool bRunAlwaysOnce, void * hEventWait) Line 1953C++
 Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessEvents(Windows::UI::Core::CoreProcessEventsOption options) Line 581C++
 [Inline Frame] Windows.UI.Xaml.dll!CJupiterWindow::RunCoreWindowMessageLoop() Line 1233C++
 [Inline Frame] Windows.UI.Xaml.dll!CJupiterControl::RunMessageLoop() Line 1065C++
 [Inline Frame] Windows.UI.Xaml.dll!DirectUI::DXamlCore::RunMessageLoop() Line 2453C++
 Windows.UI.Xaml.dll!DirectUI::FrameworkView::Run() Line 101C++
 twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run()Unknown
 twinapi.appcore.dll!&lt;lambda_a740d69e4550265529206848c8e72a27&gt;::&lt;lambda_invoker_stdcall&gt;()Unknown
 SHCore.dll!_WrapperThreadProc()Unknown
 kernel32.dll!@BaseThreadInitThunk@12&#30;()Unknown
 ntdll.dll!__RtlUserThreadStart()Unknown
 ntdll.dll!__RtlUserThreadStart@8&#30;()Unknown</p><p></p><p><strong>Please find the callstack below when the same steps are repeated with touch.</strong></p><p>&gt;Windows.UI.Xaml.dll!DirectUI::AutomaticDragHelper::UnregisterEvents() Line 362C++
 Windows.UI.Xaml.dll!DirectUI::AutomaticDragHelper::HandlePointerReleasedEventArgs(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pArgs) Line 327C++
 Windows.UI.Xaml.dll!DirectUI::UIElement::OnPointerReleased(IInspectable * pSender, Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pArgs) Line 254C++
 Windows.UI.Xaml.dll!DirectUI::ClassMemberEventHandler&lt;DirectUI::UIElement,Windows::UI::Xaml::IUIElement,Windows::UI::Xaml::Input::IHoldingEventHandler,IInspectable,Windows::UI::Xaml::Input::IHoldingRoutedEventArgs&gt;::Invoke(IInspectable * pSender, Windows::UI::Xaml::Input::IHoldingRoutedEventArgs * pArgs) Line 663C++
 Windows.UI.Xaml.dll!DirectUI::CRoutedEventSourceBase&lt;DirectUI::IUntypedEventSource,Windows::UI::Xaml::Input::IPointerEventHandler,IInspectable,Windows::UI::Xaml::Input::IPointerRoutedEventArgs&gt;::Raise(IInspectable * pSource, Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pArgs) Line 1041C++
 Windows.UI.Xaml.dll!DirectUI::CRoutedEventSourceBase&lt;DirectUI::IUntypedEventSource,Windows::UI::Xaml::Input::IPointerEventHandler,IInspectable,Windows::UI::Xaml::Input::IPointerRoutedEventArgs&gt;::UntypedRaise(IInspectable * pSource, IInspectable * pArgs) Line 995C++
 [Inline Frame] Windows.UI.Xaml.dll!DirectUI::DependencyObject::FireEvent(KnownEventIndex) Line 3475C++
 Windows.UI.Xaml.dll!DirectUI::DXamlCore::FireEvent(CDependencyObject * pCoreListener, KnownEventIndex eventId, CDependencyObject * pCoreSender, CEventArgs * pCoreArgs, unsigned int flags) Line 1962C++
 [Inline Frame] Windows.UI.Xaml.dll!AgCoreCallbacks::FireEvent(CDependencyObject *) Line 91C++
 [Inline Frame] Windows.UI.Xaml.dll!CFxCallbacks::JoltHelper_FireEvent(CDependencyObject *) Line 1035C++
 Windows.UI.Xaml.dll!CCoreServices::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 3224C++
 Windows.UI.Xaml.dll!CommonBrowserHost::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 771C++
 Windows.UI.Xaml.dll!CControlBase::ScriptCallback(void * pControl, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pInternalHandler) Line 267C++
 Windows.UI.Xaml.dll!CXcpDispatcher::OnScriptCallback(CEventInfo * pEventInfo) Line 1336C++
 Windows.UI.Xaml.dll!CXcpDispatcher::OnWindowMessage(HWND__ * msg, unsigned int wParam, unsigned int lParam, long) Line 1187C++
 Windows.UI.Xaml.dll!CXcpDispatcher::ProcessMessage(HWND__ * msg, unsigned int wParam, unsigned int lParam, long plRet, long * pbDoDefault, unsigned int *) Line 909C++
 Windows.UI.Xaml.dll!CXcpDispatcher::WindowProc(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam) Line 837C++
 user32.dll!__InternalCallWinProc@20&#30;()Unknown
 user32.dll!UserCallWinProcCheckWow()Unknown
 user32.dll!DispatchClientMessage()Unknown
 user32.dll!___fnDWORD@4&#30;()Unknown
 ntdll.dll!_KiUserCallbackDispatcher@12&#30;()Unknown
 user32.dll!SendMessageW()Unknown
 [Inline Frame] Windows.UI.Xaml.dll!CXcpDispatcher::SendMessageW(unsigned int) Line 807C++
 Windows.UI.Xaml.dll!CXcpBrowserHost::SyncScriptCallbackRequest(void * pVoidBH, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pHandler) Line 1048C++
 Windows.UI.Xaml.dll!CEventManager::RaiseHelper(xvector&lt;REQUEST *&gt; * pRegisteredRequests, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int bRefire, HRESULT(__stdcall*)(void *, CDependencyObject *, EventHandle, CDependencyObject *, CEventArgs *, int, IScriptObject *, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *)) pfnScriptCallback, unsigned int &amp; bFired, CDependencyObject * pSenderOverride) Line 1068C++
 Windows.UI.Xaml.dll!CEventManager::Raise(EventHandle hEvent, int bRefire, CDependencyObject * pSender, CEventArgs * pArgs, bool fRaiseSync, bool fInputEvent, bool bAllowErrorFallback, CDependencyObject * pSenderOverride) Line 902C++
 Windows.UI.Xaml.dll!CEventManager::RaiseRoutedEventBubbling(EventHandle hEvent, CDependencyObject * pSource, CRoutedEventArgs * pArgs, bool bIgnoreVisibility, bool fRaiseSync, bool fInputEvent, CDependencyObject * coerceToHandledAtElement) Line 1334C++
 [Inline Frame] Windows.UI.Xaml.dll!CEventManager::RaiseRoutedEvent(EventHandle hEvent, CDependencyObject *) Line 1241C++
 Windows.UI.Xaml.dll!CInputServices::RaiseDelayedPointerUpEvent(TouchInteractionMsg * pMsgGesture, CDependencyObject * pElement) Line 2663C++
 Windows.UI.Xaml.dll!CInputServices::CleanPointerProcessingState(CContentRoot * contentRoot, InputMessage * pMsg, unsigned int pointerId, CPointerState * pPointerState, CDependencyObject * pDOContact) Line 1654C++
 Windows.UI.Xaml.dll!ContentRootInput::PointerInputProcessor::ProcessPointerInput(InputMessage * pMsg, int * handled) Line 780C++
 Windows.UI.Xaml.dll!CInputServices::ProcessInput(InputMessage * pMsg, CContentRoot * contentRoot, int * handled) Line 887C++
 Windows.UI.Xaml.dll!CCoreServices::ProcessInput(InputMessage * pMessage, CContentRoot * contentRoot, int * fHandled) Line 991C++
 Windows.UI.Xaml.dll!CXcpBrowserHost::HandleInputMessage(unsigned int uMsg, MsgPacket * pMsgPack, CContentRoot * contentRoot, bool &amp; fHandled) Line 1403C++
 Windows.UI.Xaml.dll!CJupiterControl::HandlePointerMessage(unsigned int uMsg, unsigned int wParam, long lParam, CContentRoot * contentRoot, Windows::UI::Input::IPointerPoint * pointerPoint, Windows::UI::Core::IPointerEventArgs * pointerArgs) Line 750C++
 Windows.UI.Xaml.dll!CJupiterControl::HandleWindowMessage(unsigned int uMsg, unsigned int wParam, long lParam, CContentRoot * contentRoot) Line 338C++
 Windows.UI.Xaml.dll!CJupiterWindow::CoreWindowSubclassProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 1084C++
 Windows.UI.Xaml.dll!CJupiterWindow::StaticCoreWindowSubclassProc(HWND__ * hwnd, unsigned int uMsg, unsigned int wParam, long lParam) Line 576C++
 user32.dll!__InternalCallWinProc@20&#30;()Unknown
 user32.dll!UserCallWinProcCheckWow()Unknown
 user32.dll!DispatchMessageWorker()Unknown
 user32.dll!_DispatchMessageW@4&#30;()Unknown
 Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessMessage(bool bDrainQueue, bool * pbWindowMessagesProcessed, bool * pbInvokeItemProcessed) Line 327C++
 Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal(bool bRunAlwaysOnce, void * hEventWait) Line 1953C++
 Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessEvents(Windows::UI::Core::CoreProcessEventsOption options) Line 581C++
 [Inline Frame] Windows.UI.Xaml.dll!CJupiterWindow::RunCoreWindowMessageLoop() Line 1233C++
 [Inline Frame] Windows.UI.Xaml.dll!CJupiterControl::RunMessageLoop() Line 1065C++
 [Inline Frame] Windows.UI.Xaml.dll!DirectUI::DXamlCore::RunMessageLoop() Line 2453C++
 Windows.UI.Xaml.dll!DirectUI::FrameworkView::Run() Line 101C++
 twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run()Unknown
 twinapi.appcore.dll!&lt;lambda_a740d69e4550265529206848c8e72a27&gt;::&lt;lambda_invoker_stdcall&gt;()Unknown
 SHCore.dll!_WrapperThreadProc()Unknown
 kernel32.dll!@BaseThreadInitThunk@12&#30;()Unknown
 ntdll.dll!__RtlUserThreadStart()Unknown
 ntdll.dll!__RtlUserThreadStart@8&#30;()Unknown</p><p><strong>
UWP target version: Windows 10 Anniversary Edition (10.0; Build 14393) </strong></p><p><strong>OS: Windows 10 Pro, Version 1903 (OS Build 18362.418)</strong></p>

---
#### Visual Studio Feedback System on 11/1/2019, 03:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jevansaks** [comment]
We need a repro app to be able to investigate further. Closing until more information is provided. (I've also posted back to the devcommunity thread).

**Comment by AkshathaKukkemane** [comment]
Hi, 

I have attached a sample UWP application(App1.zip) in which the issue can be reproduced.

Steps:
1)Run the application
2)Main page shows a single text block with a text "Drag Me"
3)Click on this text continuously as fast as can until the application crashes.
4)Application crashes within few seconds.

Background:
I'm switching the state of  "CanDrag" property of this textblock every second.

[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3814682/App1.zip)

Thanks,
Akshatha

**Comment by jevansaks** [comment]
Thanks, @AkshathaKukkemane ! We'll take a look at the repro.

**Comment by YuliKl** [comment]
@ranjeshj can you take a look?

**Comment by ranjeshj** [comment]
This does look like a bug in the drag drop code.

**Comment by AkshathaKukkemane** [comment]
Could you please let me know if any changes will be done in the framework or Is there any workaround for this issue?

**Comment by ranjeshj** [comment]
Yes. I'm working on a fix in the framework. I'm not sure if there is an easy workaround apart from not switching the CanDrag property often. There is a short time between when the property change handler is called and the other handlers like PointerMoved and PointerPressed etc where the state is not setup correctly causing the nullref. Is there a way to achieve your scenario without changing the CanDrag property ?

**Comment by AkshathaKukkemane** [comment]
Hi Ranjesh,

Thank you for your response. Yes I have found a workaround by creating that same control twice, one with drag behavior attached and one without. I will change the visibility of these controls based on my requirement.

**Comment by ranjeshj** [comment]
That sounds like a reasonable workaround for now.

**Comment by ranjeshj** [comment]
Fixed in platform code.
