### ISSUE TITLE
WinUI 3.0 alpha App deployment error

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1542]
**Describe the bug**

I get the following error when I try to run the app build using WinUI 3.0 alpha

> DEP0700: Registration of the app failed. [0x80073CF3] Windows cannot install package 5dd4b5e3-43af-4a81-825a-aac961b66542_1.0.0.0_x86__1fk83vj4aqw9y because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x86 processor architecture and minimum version 14.0.24217.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {}

**Steps to reproduce the bug**

1. Create the WinUI 3 app from the Visual studio project template

**Version Info**

WinUI 3.0 Alpha

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by kmahone** [comment]
@harvinders, can you try the following work-around:

In Solution Explorer, right click on References and select Add Reference. Under Universal Windows, Extensions, add a reference to 'Visual C++ 2015 UWP Desktop Runtime for native apps' and click OK. Switch from 'Debug' configuration to 'Release' configuration and try to build and launch again.

**Comment by kmahone** [comment]
You should also be able to work around this issue by manually installing the appx dependency. It is likely available on your machine under a path such as:
`C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0\Appx\Retail\x86\Microsoft.VCLibs.x86.14.00.Desktop.appx`

Please let me know if the package is not available on your machine or if installing it does not resolve the deployment error.

**Comment by llongley** [comment]
If you've created this project using the WinUI 3.0 alpha VSIX, you'll also need to remove this line from Package.appxmanifest using Notepad before you can deploy a project built using Debug configuration:

`<PackageDependency Name="Microsoft.VCLibs.140.00.UWPDesktop" MinVersion="14.0.24217.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />`

**Comment by harvinders** [comment]
Thanks, Adding the appx and removing the entry from manifest worked.

**Comment by MikeHillberg** [comment]
This will be addressed in the next preview release.
