### ISSUE TITLE
WinUI 3.0 Alpha Template comment links

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#1544]
**Describe the bug**

The links in the comments in the code generated by the new project and new item options do not direct to the content the comment describes.

**Steps to reproduce the bug**

1. Create a new Blank App (WinUI UWP) project 
2. Open MainPage.xaml.cs

There's a link in the comment in that file to https://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

This redirects to an outdated doc that refers to Windows 8
(Yes, this is the same link that is used in the current UWP app)
There does not appear to be an appropriate Windows 10/UWP version of that document.
Remove this link (and comment) if no updated/appropriate document will be created.
If there is a plan to eventually add a document, then create an issue for it and have the link redirect to the issue until the document is created. Once the document exists the link can be redirected to that doc.

_Updating the other UWP (non-WinUI) templates would be a nice improvement too but not sure where best to report this._

*Also* 

When adding a new templated control (with the new template) the following is included in the generated *.xaml.cs file
`// The Templated Control item template is documented at https://go.microsoft.com/fwlink/?LinkId=234235`
That link goes to a 2.5 year old video that talks in general about Custom Controls but doesn't directly document the item template.

Adding a new CustomControl using the new template, includes the following comment in the .xaml.cs file
`// The User Control item template is documented at https://go.microsoft.com/fwlink/?LinkId=234236`
This link redirects to the out-dated document about Windows 8 project templates. Either redirect to an appropriate document or remove the link from the comment.

**Expected behavior**

_Summary of above:_
- Don't link to docs that are known to be wrong or out of date.
- Don't add links just for the sake of it.
- If you want to link to a document that doesn't exist yet, put the 

**Version Info**

Not in a NuGet package but in the templates released as the first public WinUI 3.0 Alpha templates. v3.0.0.1911010

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by danzil** [comment]
Thanks for the detailed feedback @mrlacey. We'll address this. @SvetBonev, the same issues apply to the UWP templates that ship with VS. Do you want to open a bug to fix those, too?

**Comment by krschau** [comment]
As of the current 0.8 version, this has been fixed in the WinUI 3 templates -- the comment now reads
```
// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.
```
The other types mentioned ship with Visual Studio and can be reported to them [here](https://developercommunity.visualstudio.com/search?space=8).

Closing this item.
