### ISSUE TITLE
Targeted TeachingTips don't change position when the window is resized by changing maximized state.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1547]
@Nacimota commented on [Tue Nov 05 2019](https://github.com/microsoft/Xaml-Controls-Gallery/issues/259)

**Describe the bug**
Targeted TeachingTips don't change position when the window is resized by changing maximized state.

**Steps to reproduce the bug**
1. Go to `All Controls` > `TeachingTip`
2. Click `Show TeachingTip` under `Show a targeted TeachingTip [...]` or `Show a targeted TeachingTip with hero content [...]`
3. Toggle the window between maximized and non-maximized state (using maximize/restore button, double clicking/dragging the caption bar, etc.)

**Expected behavior**
The targeted TeachingTip/s should stick to the target control (the `Toggle Theme` button), like when the window is manually resized.

**Actual behavior**
The TeachingTip retains its original position, which may now be too far to the left or right (and even entirely outside the window, invisible)

**Screenshots**
![Screenshot](https://i.imgur.com/18puF3K.png)

**Version Info**

Gallery version (found on Settings page): 
1.2.9.0

Windows 10 version:
May 2019 Update (18362)

Device form factor:
Desktop

---

@YuliKl commented on [Tue Nov 05 2019](https://github.com/microsoft/Xaml-Controls-Gallery/issues/259#issuecomment-549950185)

@Nacimota, thank you for the repro. This sounds like a problem with the TeachingTip control rather than code in the Controls Gallery, so I'll move this issue to our WinUI repo.

**Comment by chingucoding** [comment]
I would like to look into this :)
