### ISSUE TITLE
Question: Is there any DirectX surface ?

### ISSUE THREAD

**Issue by ZeBobo5** [microsoft/microsoft-ui-xaml#1554]
I would like to use DirectX, or any other solution to draw custom video renderer. Is there any solution for that on WinUI ?

**Comment by YuliKl** [comment]
@Austin-Lamb can you help?

**Comment by jesbis** [comment]
Hi @ZeBobo5 are you asking about WinUI 2 or the WinUI 3 Alpha?

---

For the WinUI 3 Alpha, unfortunately DirectX swap chain interop isn't available yet: you can find the list of missing features we're still working on for WinUI 3 here (including SwapChainPanel):

https://docs.microsoft.com/uwp/toolkits/winui3/#controls-and-features

---

If you need to ship an app before WinUI 3 is ready then we recommend continuing to use system Xaml + WinUI 2, which should be easy to update to WinUI 3 in the future.

With system Xaml you can use any of the DirectX interop types documented here to render DirectX surfaces:

https://docs.microsoft.com/windows/uwp/gaming/directx-and-xaml-interop

For custom media, the best options are usually to either:

1. Use a [MediaPlayer](https://docs.microsoft.com/uwp/api/windows.media.playback.mediaplayer) rendered in a Xaml [MediaPlayerElement](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.mediaplayerelement). `MediaPlayer` supports custom streams and video effects 

2. Render a fully custom DirectX swap chain using [SwapChainPanel](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.SwapChainPanel)
