### ISSUE TITLE
Cannot click-drag TextBox text when windows is out of focus

### ISSUE THREAD

**Issue by adrientetar** [microsoft/microsoft-ui-xaml#1555]
**Steps to reproduce the bug**

1. Open a window with a TextBox, add some text to the TextBox
2. Focus a different window, with the TextBox window still visible
3. Try to select some text in the unfocused window TextBox by clicking and dragging in it.

It doesn't work. You can click the TextBox but not drag a selection. You have to do an extra click just to focus the window first.

**Expected behavior**

One would be able to click and drag even when the window was out of focus. This work with win32. It becomes annoying with apps that have multiple windows and TextBox controls.

NuGet package version: 

2.3.191007001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | X   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | X   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by yaichenbaum** [comment]
I would like to point out there is the same issue with the `RichEditBox` control as well.

**Comment by chrisglein** [comment]
The source for TextBox is out of the scope of WinUI2.x. We'd need to make more fundamental changes to TextBox to enable this. So this would require WinUI3.0 to take on.

**Comment by XamDR** [comment]
Hello. Any updates on this bug?

**Comment by DmitriyKomin** [comment]
The scenario appears fixed in WinUI3.

**Comment by yaira2** [comment]
Will this be backported to WinUI 2?
