### ISSUE TITLE
Discussion: Why have a Microsoft.UI.Xaml.Data.INotifyPropertyChanged in WinUI 3 Alpha 

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#1556]
While converting an app to WinUI 3 Alpha I noticed that there is a new  Microsoft.UI.Xaml.Data.INotifyPropertyChanged interface. It replace the  System.ComponentModel.INotifyPropertyChanged interface. Why? You need it for OneWay databinding but is this wise?

Some existing classes like System.Collections.ObjectModel.ObservableCollection<T> implement the System.ComponentModel.INotifyPropertyChanged interface. If I want to oneway databind to the Count property of collection no updates are received. It doesn't implement the correct interface. 

Will this stay like this or is this an Alpha solution.

**Comment by MikeHillberg** [comment]
We're working on a fix to this. The INotifyPropertyChanged and INotifyCollectionChanged interfaces have always been in the Windows.UI.Xaml.Data namespace, but in C# there's an interop layer that converts them to System.ComponentModel. That conversion isn't happening for the interfaces in the alpha.

**Comment by sonnemaf** [comment]
Hi Mike, that makes sense. With this you can close the issue. I will wait for a new version.
