### ISSUE TITLE
Unreliable test: ScrollerViewTestsWithInputHelper.VerifyScrollerViewGamePadInteraction

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#156]
See failures here:
https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=1172&view=ms.vss-test-web.test-result-details
and
https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=1167&view=ms.vss-test-web.test-result-details

**Comment by RBrid** [comment]
Fixed as part of #787.
