### ISSUE TITLE
Question: When will SwapChainPanel be available?

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#1562]
I tried the WinUI 3.0 for UWP and got 'Unknown type 'SwapChainPanel' in XML namespace'

I need to be able to create a SwapChain for both SwapChainPanel and CoreWindow (Xaml-less window). 

C#.

**Comment by YuliKl** [comment]
@Austin-Lamb can you take this one?

**Comment by jesbis** [comment]
Thanks for trying out WinUI 3!

Unfortunately SwapChainPanel isn't available yet: you can find the list of missing features we're still working on for WinUI 3 here (including SwapChainPanel):

https://docs.microsoft.com/uwp/toolkits/winui3/#controls-and-features

We don't have an exact availability date yet for SwapChainPanel but it should start appearing in preview builds before shipping next year.

If you need to create and ship an app before then, we recommend continuing to use system Xaml + WinUI 2, which should be easy to update to WinUI 3 next year.

For CoreWindow views you can also use `CompositionDrawingSurface` to render DierctX content as [shown here](https://docs.microsoft.com/windows/uwp/composition/composition-native-interop), including [`ICompositorInterop::CreateCompositionSurfaceForSwapChain`](https://docs.microsoft.com/windows/win32/api/windows.ui.composition.interop/nf-windows-ui-composition-interop-icompositorinterop-createcompositionsurfaceforswapchain) for rendering swap chains in a composition visual tree (with or without Xaml).

**Comment by Gavin-Williams** [comment]
Excited about WinUI, and .Net 5, I just hope game development isn't lost along the way. Remember that SharpDX is the only DirectX wrapper on the table. So any DX interop elements have to work with that.
