### ISSUE TITLE
WinUI 3 dlls' version does not match NuGet's version and is rather confusing

### ISSUE THREAD

**Issue by danzil** [microsoft/microsoft-ui-xaml#1566]
WinUI 3 dlls' version does not match NuGet's version and is rather confusing

**Steps to reproduce the bug**
* Create a new WinUI App
* Set breakpoint in MainPage's constructor
* F5
* Load modules' window and look at the Win UI dlls' version

**Expected behavior**
Version should match nuget version

**Comment by krschau** [comment]
With WinUI 3's inclusion in the Windows App SDK, version coordination is both more difficult and less useful. Closing.
