### ISSUE TITLE
Settings does not display indicator with PaneDisplayMode = Top

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1572]
**Describe the bug**

**Steps to reproduce the bug**
- Open XAML Controls Gallery (WinUI 3 Alpha) and navigate to the NavigationView example page
- Scroll down to the _NavigationView with PaneDisplayMode set to Top_ and tap the settings item

**Expected behavior**
Navigating to Settings should display the selected indicator as the other navigation links do.

**Screenshots**
![image](https://user-images.githubusercontent.com/7389110/68507244-576cfe00-0263-11ea-8967-46cd7f9f0ea4.png)
_Settings selected_

![image](https://user-images.githubusercontent.com/7389110/68507507-f3970500-0263-11ea-901a-48eccb6268f0.png)
_Menu Item1 selected_

**Version Info**
WinUI 3 Alpha

**Comment by chingucoding** [comment]
This issue is also present in WinUI 2(.3)

**Comment by robloo** [comment]
Funny, but I just noticed this a few hours ago myself. 

Also present in Microsoft.UI.Xaml 2.2.190917002

**Comment by jevansaks** [comment]
Good issue! I think this is one that I wouldn't want to try to fix until @ojhad's refactor is complete. But maybe @ojhad you can keep a list of these issues (and PRs) that we want to revisit when the NavView refactor is in?

**Comment by ad1Dima** [comment]
This can be fixed alongside with  bottom pinned menu items (#375) as i do in #1497

**Comment by ojhad** [comment]
Good idea! I moved the list of issues and PRs that will need to be revisited to the [ItemsRepeater move dev task](https://github.com/microsoft/microsoft-ui-xaml/issues/1477)

**Comment by ojhad** [comment]
Refactor is in and this can now be re-visited (as it is still an issue). Unassigning myself for now.
