### ISSUE TITLE
Duplicate type error when both c++/winrt app and c++ windows runtime component are using WinUI framework package

### ISSUE THREAD

**Issue by licanhua** [microsoft/microsoft-ui-xaml#1573]
How to repro:
Download and compile [BlankApp2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3826216/BlankApp2.zip)

Both BlankApp2 {Blank App(C++/WinRT) template} and RuntimeComponent1 {Windows Runtime Component (C++/WinRT) template} are cppwinrt project which is created by https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264
Both projects have reference to WinUI.

Here is the reference relationship:
BlankApp2  -> RuntimeComponent1  -> WinUI
BlankApp2  -> WinUI

Error on build:
Severity | Code | Description | Project | File | Line | Suppression State | Suppression State
-- | -- | -- | -- | -- | -- | -- | --
Error | MDM2009 | Duplicate type   Microsoft.UI.Xaml.Automation.Peers.AnimatedVisualPlayerAutomationPeer found   processing metadata file  
 
...\source\repos\BlankApp2\Debug\RuntimeComponent1\Microsoft.UI.Xaml.winmd,   type already exists in file ...\source\repos\BlankApp2\packages\Microsoft.UI.Xaml.2.2.190917002\lib\uap10.0\Microsoft.UI.Xaml.winmd. | BlankApp2 | ...\source\repos\BlankApp2\BlankApp2\MDMERGE | 1 |   |

**Comment by danzil** [comment]
@Scottj1s looks like this error comes from mdmerge, invoked from 2>C:\Users\danzil\Desktop\BlankApp\packages\Microsoft.Windows.CppWinRT.2.0.190530.8\build\native\Microsoft.Windows.CppWinRT.targets(340,9): error MSB3073: The command "mdmerge @"ARM\Debug\mdmerge.rsp"" exited with code 2.

**Comment by jevansaks** [comment]
It is surprising to me that Microsoft.UI.Xaml.winmd is in the RuntimeComponent1 output location. Is that expected @scott1js?

**Comment by Scottj1s** [comment]
Can we reevaluate with the latest C++/WinRT vsix/nuget/templates?  @jlaanstra has made some significant improvements to the msbuild support, addressing duplicate type definition errors like this, among others.

**Comment by jlaanstra** [comment]
@jevansaks @Scottj1s VS tends to copy Reference entries to the output folder which will then be picked up by mdmerge, because it uses the output directory as a metadata_dir. I have a OPR out internally to make mdmerge support files so we can be more specific about what we pass to mdmerge.exe. 

In the meantime you can use this as a workaround:

```
<ItemDefinitionGroup>
    <Reference>
        <Private Condition="'$(ConfigurationType)' != 'Application'">false</Private>
    </Reference>
</ItemDefinitionGroup>
```

**Comment by Scottj1s** [comment]
There is also an open issue to make duplicate type definitions (those that clearly don't violate ODR, such as from identical files) benign in mdmerge.
