### ISSUE TITLE
Question: is ItemsRepeater only allowed in XAML for Custom Control Templates?

### ISSUE THREAD

**Issue by CheathamPatrick** [microsoft/microsoft-ui-xaml#1576]
I notice that though I use examples from the UWP documentation on ItemsRepeater, my MainPage.xaml file and editor will not accept usage of the control in markup. Is this only to work in a custom control situation? Thank you for your time in answering!

**Comment by kmahone** [comment]
Can you share the xaml that is causing problems for you?

When you say the "editor will not accept usage of the control", what do you mean by this? Are you getting compiler errors? Can you share the error?

Have you included the Microsoft.UI.Xaml nuget package in your project? ItemsRepeater is only available in that package. It is not available from the Windows SDK.

**Comment by adrientetar** [comment]
Make sure you add xml namespace xmlns:muxc="using:Microsoft.UI.Xaml.Controls" then write muxc:ItemsRepeater

**Comment by CheathamPatrick** [comment]
Thanks all. The problem was simply the lack of Microsoft.UI.Xaml installed.

**Comment by kmahone** [comment]
@CheathamPatrick Happy to hear that this is resolved for you.
