### ISSUE TITLE
WinUI 3 sometimes doesn't render clearly

### ISSUE THREAD

**Issue by Berrysoft** [microsoft/microsoft-ui-xaml#1579]
**Describe the bug**
WinUI 3 sometimes not renders texts clearly, when setting the Margin of TextBlock to some certain value.

**Steps to reproduce the bug**
``` xaml
<Page
    x:Class="WinUIAlphaTest.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUIAlphaTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <StackPanel Orientation="Vertical">
        <TextBlock>Margin = 0</TextBlock>
        <TextBlock Margin="1">Margin = 1</TextBlock>
        <TextBlock Margin="2">Margin = 2</TextBlock>
        <TextBlock Margin="3">Margin = 3</TextBlock>
        <TextBlock Margin="4">Margin = 4</TextBlock>
        <TextBlock Margin="5">Margin = 5</TextBlock>
        <TextBlock Margin="6">Margin = 6</TextBlock>
        <TextBlock Margin="7">Margin = 7</TextBlock>
        <TextBlock Margin="8">Margin = 8</TextBlock>
    </StackPanel>
</Page>
```

**Expected behavior**
The text should all be clear.

**Screenshots**
![image](https://user-images.githubusercontent.com/37586447/68537855-d36f5f00-03a5-11ea-8c03-1693962b21ef.png)

When Margin is 2 or 5, the texts are rather blurred.

For comparison, here is the render result of the traditional UWP:
![image](https://user-images.githubusercontent.com/37586447/68537900-a96a6c80-03a6-11ea-9499-0a52fafb94e4.png)

(The title isn't well-named, ignore it.)
**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-alpha.191101.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19018)              | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**
The DPI of my screen is 90 (125%).

**Comment by kmgallahan** [comment]
Probably related to #1441

**Comment by be5invis** [comment]
Looks like text coordinates are not properly rounded.

**Comment by Berrysoft** [comment]
I don't use winui 3 anymore. Anyone who faces this problem, feel free to reopen.
