### ISSUE TITLE
TabView's desired width doesn't increase when HorizontalAlignment isn't set to Stretch

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/microsoft-ui-xaml#1581]
I inspected with visual studio and found that it's desired size only decrease when available space is less, but doesn't increase when available space is more.

![output](https://user-images.githubusercontent.com/21083609/68542057-062f4c80-03d2-11ea-8b14-8a310a9e557f.gif)

The bug also appears in Windows Terminal Preview:
![image](https://user-images.githubusercontent.com/21083609/68542066-4abae800-03d2-11ea-89b6-76c5dead1b10.png)

**Steps to reproduce the bug**

1. Create a blank UWP C# app
2. Install Microsoft.UI.Xaml nuget package 
3. make the *App.xaml* like this:
```
<Application
    x:Class="TestApp.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestApp">
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>
</Application>
```
 4. *MainPage.Xaml*:
```
<Page
    x:Class="TestApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:winui="using:Microsoft.UI.Xaml.Controls">

    <Page.Resources>
        <ResourceDictionary Source="ms-appx:///Microsoft.UI.Xaml/DensityStyles/Compact.xaml" />
    </Page.Resources>

    <winui:TabView 
            HorizontalAlignment="Left">
        <winui:TabView.TabItems>
            <winui:TabViewItem Header="This is a lonh header just to make more width"/>
            <winui:TabViewItem Header="This is another tab"/>
            <winui:TabViewItem Header="this is the third and last tab in the row"/>
        </winui:TabView.TabItems>
    </winui:TabView>
</Page>
```
5. Now build and run the app, resize it with mouse. Notice that once it's width get smaller, it doesn't enlarge when it gets available space.

NuGet package version: 
Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Comment by jevansaks** [comment]
Good find! Looks like we stash some information in MeasureOverride, I wonder if we're not getting re-measured (only re-arranged) and we need to InvalidateMeasure somehow?

**Comment by DHowett-MSFT** [comment]
(If this can help Terminal, I'd love to peep a fix for it :smile:)

**Comment by MuziburRahman** [comment]
A lot of things in the design of the `TabView` control rise question in my mind.
Can anyone explain why the `TabColumn` isn't given the star width instead of the `RightContentColumn` here :
![image](https://user-images.githubusercontent.com/21083609/69488437-8efabd80-0e93-11ea-8b33-e3893b1d5a3b.png)
