### ISSUE TITLE
MessageDialog does not respect app theme

### ISSUE THREAD

**Issue by mfeingol** [microsoft/microsoft-ui-xaml#1582]
**Describe the bug**

I'm not entirely sure this falls within your bailiwick, since MessageDialog is an OS control at the moment. But I wasn't sure where else to file it. This may ultimately be a feature request for a proper dialog box control.

In short, I have a UWP app that allows the user to select between light and dark themes. When the latter is selected on an OS whose default is the light theme, dialogs (ContentDialog, MessageDialog) will default to displaying the light theme colors, even if the app has selected the dark theme.

With ContentDialog, this can be worked around using the RequestedTheme property on FrameworkElement. However, MessageDialog is not a FrameworkElement and does not have a theme property.

**Steps to reproduce the bug**

Repro is trivial. Run an app in dark mode and open a MessageDialog. I can provide a repro project if needed.

**Expected behavior**

MessageDialog should either align to the theme set on the app's current window, or allow a theme to be set on each instance. Bonus points if `MessageDialog` weren't sealed, but presumably that ship has sailed.

**Version Info**
All version of Windows 10 have this problem.

**Comment by jevansaks** [comment]
This is by design for MessageDialog, that's showing a dialog from the system and so it follows the system theme. We would encourage you to use ContentDialog.

For ContentDialog, if you create it from code-behind then yes you would need to set RequestedTheme on it. But (and possibly surprisingly) you can actually add ContentDialog to your tree and in that case it will inherit the theme so you don't have to do anything.

**Comment by mfeingol** [comment]
That's unfortunate about MessageDialog. Would it make sense for the WinUI project to provide a better "standard" MessageDialog? It seems like every app presenting its own variation on something so simple would be detrimental to the platform.

When you mention adding ContentDialog to the tree, do you mean having it embedded in a page's XAML with an `x:Name` and then displayed on demand?

**Comment by jevansaks** [comment]
> That's unfortunate about MessageDialog. Would it make sense for the WinUI project to provide a better "standard" MessageDialog?

ContentDialog should encompass all the scenarios. What specifically do you prefer about the MessageDialog solution?



> When you mention adding ContentDialog to the tree, do you mean having it embedded in a page's XAML with an `x:Name` and then displayed on demand?

Exactly. Or if you create it from code-behind then you can find a Grid or other panel in the tree and do `.Children.Add(...)` from code-behind.

**Comment by mfeingol** [comment]
> What specifically do you prefer about the MessageDialog solution?

Well, except in cases where differentiation is strategic for some reason, I'm a big fan of using standard controls instead of custom controls. MessageDialog it's a turnkey way to display error or confirmation text with 1-2 buttons, without worrying about alignment/placement/button width/etc., and while (at least theoretically) presenting a familiar pattern to the user that looks like everything else on the system.

**Comment by mdtauk** [comment]
> Well, except in cases where differentiation is strategic for some reason, I'm a big fan of using standard controls instead of custom controls. MessageDialog is a turnkey way to display error or confirmation text with 1-2 buttons, without worrying about alignment/placement/button width/etc., and while (at least theoretically) presenting a familiar pattern to the user that looks like everything else on the system.
>
MessageBox/Dialog is a Win32 outdated way to display a message to the user, and the preferred way to do it is by displaying a ContentDialog.

This does bring up a point with WinUI encouraging people to move from Win32 UIs to WinUI with the same code behind.  

Should a MessageWindow be a top level object in XAML with WinUI 3?
Should there be a way to send a RequestedTheme to the existing Message Dialog?
And should a RequestedTheme work with the Common File Dialogs?

**Comment by jevansaks** [comment]
@mfeingol can you share the code for showing a MessageDialog that you feel is hard or impossible to do with ContentDialog? There may be a feature gap here that we should close.

**Comment by mfeingol** [comment]
Okay, I gave ContentDialog a quick spin and it looks like it's going to work fine. Apologies for not checking on this earlier. It looks like ContentDialog has seen some upgrades over the years.

```
            ContentDialogResult result = await new ContentDialog
            {
                Title = "Title",
                Content = "My Content",
                PrimaryButtonText = "OK",
                CloseButtonText = "Cancel",
                RequestedTheme = selectedTheme
            }.ShowAsync();
```

**Comment by jevansaks** [comment]
No problem, thanks for following up! Please holler if there are scenarios you think should be easy that aren't.
