### ISSUE TITLE
A11y_ControlUIupdatebasedonSantoriniOSvisualupdate_MiniControGallery_GenericControls_Keyboard : The "Hello World" text besides Tooltip receives keyboard focus which is incorrect.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/microsoft-ui-xaml#1585]
GitHubTags: #A11y_ControlUIupdatebasedonSantoriniOSvisualupdate, #A11yMAS, #A11yTCS, #Win10, #DesktopApp, #WindowsUILibrary, #MAS2.1.1, #Keyboard

**Environment Details:**
Application Name: Control UI update based on Santorini OS visual update
Application Version: 1.0.1.0
Windows Version: Windows10
Screen Reader: Narrator, NVDA 2019.2

**Steps to Reproduce:**
1. Launch Mini Control Gallery App from the installer location.
2. Screen with all generic controls would appear on left side of the screen.
3. Verify that all the elements of "MiniControlGallery-Generic Controls" are accessible and MAS Compliant.

**Actual:**
When keyboard users navigate through the screen an inactive element that is "Hello World" text receives keyboard focus which is present besides Tooltip.

**Expected:**
The "Hello World" text should not receive keyboard focus while navigation since it is not an interactive element.

**User Impact:**
If an inactive element receives keyboard focus, then the keyboard users will interpret it as an interactive element which will lead to confusion.

**Attachment**
[A11y_ControlUIupdatebasedonSantoriniOSvisualupdate_MiniControGallery_GenericControls_Keyboard  The Hello World text besides Tooltip receives keyboard focus which is incorrect..pptx](https://github.com/microsoft/microsoft-ui-xaml/files/3829928/A11y_ControlUIupdatebasedonSantoriniOSvisualupdate_MiniControGallery_GenericControls_Keyboard.The.Hello.World.text.besides.Tooltip.receives.keyboard.focus.which.is.incorrect.pptx)

**Comment by YuliKl** [comment]
Because the purpose of the app is to show visual changes at a glance, the app has very atypical usage of the ToolTip control. In practice, ToolTips aren't used in this way. Because this app does not ship to customers, we won't update this ToolTip behavior.
