### ISSUE TITLE
Proposal: Provide XAML basic functionality as a standalone library

### ISSUE THREAD

**Issue by arieradle** [microsoft/microsoft-ui-xaml#1586]
# Proposal: Provide XAML basic functionality as a standalone library

## Summary
XAML basic functionality should be available as a separate set of APIs for serialization/deserialization purposes, configuration etc.

## Rationale
* Many project utilize XAML generic functionality as a rich ML for configuration or serialization/deserialization. XAML is tightly coupled to UI platforms, and for no good reason. 
* Coupling to UI platforms does not allow XAML to exist as a portable component, and to be used in .NET Core applications on Linux.

## Scope
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to use basic XAML functionality as a standalone, Standard 2.1 library. (Namespace proposal: `System.Xaml.Base` ) | Must |
| This proposal will not provide all-flovours-all-functionality XAML standalone library  | Won't |

**Comment by stevenbrix** [comment]
@arieradle is there something in particular you are looking for that `System.Xaml` doesn't currently provide?

**Comment by weitzhandler** [comment]
Related: #1630.

**Comment by LucasHaines** [comment]
Can you outline your scenario a bit more? This is linked to 1630 and maybe there is something we are missing?

**Comment by weitzhandler** [comment]
@LucasHaines I deleted my previous comment. I think the OP was referring to the ability to manipulate or read XAML files from a non XAML project, i.e. .NET Standard.
Am I wrong @arieradle?

**Comment by arieradle** [comment]
In our case, we use XAML to create complex graphs of objects using the ability of XAML to specify references among the objects. **It has nothing to do with WPF or any other UI infra.** It is used purely for it's advanced features as a markup language.

Currently, XAML cannot be used in .NET Core projects, intended to be run on Linux.
Correct me if I'm wrong, but there is no System.XAML nuget, targeting Standard 2.1 or simillar.

**Comment by weitzhandler** [comment]
The immediate solution that comes in mind for your scenario @arieradle, is obviously the [Uno Platform](https://platform.uno).
Uno brings XAML projects and makes the same code work on iOS, Android, and also as a WASM website!
Although it's UWP-based rather than WPF, I'm sure, if you talk to the Uno team via their website or their twitter, they'll be happy to listen and try to help.
It also [looks](https://github.com/unoplatform/uno/issues/95#issuecomment-403817919) like Linux is well on their radar too.

**Comment by arieradle** [comment]
> The immediate solution that comes in mind for your scenario @arieradle, is obviously the [Uno Platform](https://platform.uno).
> Uno brings XAML projects and makes the same code work on iOS, Android, and also as a WASM website!
> Although it's UWP-based rather than WPF, I'm sure, if you talk to the Uno team via their website or their twitter, they'll be happy to listen and try to help.
> It also [looks](https://github.com/unoplatform/uno/issues/95#issuecomment-403817919) like Linux is well on their radar too.

Well actually, I would like to refrain from referencing any UI framework in my code. It's a huge overkill.

All I need is a simple nuget, similar to Portable.XAML, where I can load object graphs, defined in XAML. That's the whole purpose of the suggested feature - simply split some basic XAML functionality into a separate nuget - `System.XAML.Base` - and ship it publicly.

**Comment by weitzhandler** [comment]
>Well actually, I would like to refrain from referencing any UI framework in my code. It's a huge overkill.

That's what Uno does. The UWP head remains untouched.

**Comment by arieradle** [comment]
> > Well actually, I would like to refrain from referencing any UI framework in my code. It's a huge overkill.
> 
> That's what Uno does. The UWP head remains untouched.

I don't understand why UNO team should really work on this. 
Basic XAML should be a standalone component, not a part of any kind of framework or infrastructure. Same as YAML, XML, JSON parsers and DOMs.

**Comment by danzil** [comment]
@LucasHaines this looks like a request to have System.Xaml as a standalone NuGet. There's already an active issue in the WPF project about that but I can't find it.

**Comment by Felix-Dev** [comment]
@danzil Do you mean [this one](https://github.com/dotnet/wpf/issues/46)?

**Comment by danzil** [comment]
@Felix-Dev yes, thanks for sharing the link: dotnet/wpf#46
