### ISSUE TITLE
CalendarView: The selection of the date is just represented by a different color border.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/microsoft-ui-xaml#1587]
GitHubTags: #A11y_OSvisualupdate, #A11yMAS, #A11yTCS, #Win32, #DesktopApp, #WindowsUILibrary, #MAS1.4.1, #Keyboard

**Environment Details:**
Application Name: OS visual update
Windows Version: Windows10
Screen Reader: Narrator, NVDA 2019.2

**Steps to Reproduce:**
1. Launch Mini Control Gallery App from the installer location.
2. Screen with all generic controls would appear on left side of the screen.
3. Verify that all the elements of "MiniControlGallery-Generic Controls" are accessible and MAS Compliant.

**Actual:**
When keyboard users who are color blind navigate to the calendar then they will have difficulty in differentiating the normal date and selected date as the selected date is get shown by a blue color border only which is incorrect.

**Similar issue is observed in the below scenario:**
1. MiniControlGallery - Calender and Color Picker Controls -> Launch Mini Control Gallery App from the installer location. -> Screen with Calender and Color Picker controls would appear on right side of the screen.

**Expected:**
In order to differentiate the selected date should be bold in the text along with the border so that color-blind users can easily differentiate it.

**User Impact:**
If the selection of content on the screen is just differentiated by the change of color then the color blind users will miss out on the information that is available for visual users.

**Attachment:**
![A11y_ControlUIupdatebasedonSantoriniOSvisualupdate_MiniControGallery_GenericControls_Keyboard  The selection of the date is just represented by a different color borde](https://user-images.githubusercontent.com/52036772/68756018-738be900-062f-11ea-9cfc-c87982c58839.gif)

**Comment by jevansaks** [comment]
@mayurinaik can you elaborate on why it is incorrect that selection is just shown by a color border? Thanks!

**Comment by Poopooracoocoo** [comment]
icymi, @jevansaks the author updated the issue

**Comment by jevansaks** [comment]
Thanks @poopooracoocoo, I did miss it. @MayuriNaik please leave a comment when replying to a "needs-author-feedback" issue, the bot rule only updates it back to "needs-triage" after you leave a comment.

But still, I talked with @yulikl and we don't see a problem here. Maybe you can follow up with us over email to explain what guideline this breaks? This has been the behavior for a long time and we've had many accessibility passes where this issue was never raised.

**Comment by Poopooracoocoo** [comment]
@MayuriNaik it would be a nice idea to do the same recording but with the greyscale filter on. You can search for it in the UWP Settings app.

**Comment by YuliKl** [comment]
I'm aware that relying on a color-change only violates accessibility rules. But in this case, the selection border introduces both a color and a geometry change.
