### ISSUE TITLE
A11y_OSvisualupdate_MiniControGallery_ CalenderandColorPickerControls_AI4D : (MiniControlGallery/list item 'RGB') An onscreen element must not have a null BoundingRectangle property.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/microsoft-ui-xaml#1596]
GitHubTags: #A11y_OSvisualupdate, #A11yMAS, #A11yTCS, #Win32, #DesktopApp, #WindowsUILibrary, #MAS4.2.1, #AI4D, #A11yAuto 

The following accessibility issue needs investigation.

**App:** MiniControlGallery

**Element path:** list item 'RGB'

**Issue Details:** An onscreen element must not have a null BoundingRectangle property. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** If the element is offscreen, set its IsOffscreen property to TRUE.
If the element is onscreen, provide a BoundingRectangle property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Attachment:**
![A11y_OSvisualupdate_MiniControGallery_ CalenderandColorPickerControls_AI4D  (MiniControlGallerylist item 'RGB') An onscreen element must not have a null](https://user-images.githubusercontent.com/52036772/68587329-def97d80-04ac-11ea-8efb-521ae8da00a7.png)

**Comment by YuliKl** [comment]
I don't understand how this issue impacts users. This issue feels very app-specific, and MiniControlGallery will never ship to customers. So I don't think we should spend time fixing this issue.
