### ISSUE TITLE
WinUI 3.0 app fails to build when it has a reference to a WinUI 3.0 class library (C++)

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/microsoft-ui-xaml#1597]
**Describe the bug**
Adding a reference to a class library results in many MDMERGE errors, e.g.

```
MDMERGE : error MDM2009: Duplicate type Microsoft.System.DispatcherQueue found processing metadata file C:\Users\<username>\Code\WinUI3_Test\Debug\WinUI3_TestControls\Microsoft.System.winmd, type already exists in file C:\Users\<username>\Code\WinUI3_Test\packages\Microsoft.WinUI.3.0.0-alpha.191101.0\lib\uap10.0\Microsoft.System.winmd.
<snip>
```

**Steps to reproduce the bug**
1. Create a new solution with a WinUI 3.0 app, and a WinUI 3.0 class library, using C++.
2. Add a reference to the class library from the app.
3. Build.

**Expected behavior**
Build to complete successfully.

**Version Info**
Visual Studio 16.4.0 (Preview 4.0)
WinUI 3 Project Templates [Preview] 3.0.0.1911010

**Comment by danzil** [comment]
This is a known issue with C++/WinRT and MDMERGE. See #1573
