### ISSUE TITLE
ItemsRepeater jumps back and forth when scroll to last item using mouse

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#1601]
**Describe the bug**
ItemsRepeater jumps back and forth when scroll to last item using mouse.
Note: this bug not occurs every time, and as the items count varies(go to another repeater), it may behave normal.

**Steps to reproduce the bug**

1. Build and run my sample repo
2. Scroll to the last item.

**Expected behavior**

Scroll to the last item normally.

**Screenshots**

![68462458-8c6b5780-0247-11ea-9b78-71ae591245ef](https://user-images.githubusercontent.com/14960168/68638192-bd93a280-053b-11ea-9b64-67b016b8f6a1.gif)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |  Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Here is a small [repo](https://github.com/hupo376787/ItemsRepeater-throws-System.InvalidCastException-when-using-converter), and special thanks to @XamlBrewer's repo.

**Comment by ranjeshj** [comment]
@hupo376787 Which version of the OS are you running on ? I cannot repro this on a recent built of windows. If you are running on an older version of the operating system ScrollViewer does not have some of the features to enable Repeater's viewport management features. You will need to wrap it in an ItemsRepeaterScrollHost to make it work there. In more recent versions of the OS ItemsRepeaterScrollHost will no-op and let ScrollViewer do the work. - https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.itemsrepeaterscrollhost?view=winui-2.2 
Hope that helps.

**Comment by hupo376787** [comment]
Previously I run my app on 1903, but last night my pc update to 1909,  so I can't reproduce either.

So I'll keep watching on. Thx.
