### ISSUE TITLE
Update Accessibility Conformance Documentation

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/microsoft-ui-xaml#1605]
GitHubTags: #A11y_OSvisualupdate, #A11yMAS, #A11yTCS, #Win32, #DesktopApp, #WindowsUILibrary, #A11YAAT

Recommendation: "Fix and close other bugs before starting accessibility conformance documentation. Any bug that will not be fixed and closed within SLA must be declared in the AAT. The SLA for this bug is also 60 days."

**Comment by jevansaks** [comment]
@mayurinaik can you provide a link to the documentation you're referring to? I don't have context on this doc. Also if it's an internal doc I would recommend you follow up with the owner over email, this repo is for bugs about the WinUI product and not accessibility documentation.

**Comment by YuliKl** [comment]
Filled out AAT
