### ISSUE TITLE
Codegen bug with 'DoNotGenerateOtherProviders' w/ cppwinrt

### ISSUE THREAD

**Issue by danzil** [microsoft/microsoft-ui-xaml#1606]
XamlMetaDataProvider::AddOtherProvider(IXamlMetadataProvider otherProvider) is marked as const in C++/WinRT code-gen. It should not be because the projection generated by cppwinrt is not.

> 1>TestApp\XamlTypeInfo.Impl.g.cpp(25,5): error C2511:  'void winrt::TestApp::implementation::XamlMetaDataProvider::AddOtherProvider(winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider) const': overloaded member function not found in 'winrt::TestApp::implementation::XamlMetaDataProvider'
1>TestApp\XamlMetaDataProvider.h(36): message :  see declaration of 'winrt::TestApp::implementation::XamlMetaDataProvider'
1>TestApp\XamlTypeInfo.Impl.g.cpp(26,9): error C2352:  'winrt::TestApp::implementation::XamlMetaDataProvider::Provider': illegal call of non-static member function
1>TestApp\XamlMetaDataProvider.h(45): message :  see declaration of 'winrt::TestApp::implementation::XamlMetaDataProvider::Provider'

**Comment by evelynwu-msft** [comment]
Fixed in WinAppSDK 1.3.
