### ISSUE TITLE
ItemsRepeater can't scroll manually using ChangeView when used in ScrollViewer

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#1610]
**Describe the bug**
Hi, I'm using `ItemsRepeater`, and surrounded in a `ScrollViewer`. I have disabled `ScrollViewer`'s `HorizontalScrollMode` and `VerticalScrollMode`. And I want to use `ChangeView` method to scroll.
But it doesn't works.
However, `ScrollToHorizontalOffset`/`ScrollToVerticalOffset` works.

**Steps to reproduce the bug**

```
<Grid>
                    <muxc:ItemsRepeaterScrollHost Margin="12" Loaded="ItemsRepeaterScrollHost_Loaded">
                        <ScrollViewer
                            x:Name="sss"
                            VerticalScrollBarVisibility="Hidden"
                            HorizontalScrollBarVisibility="Hidden"
                            VerticalScrollMode="Disabled"
                            HorizontalScrollMode="Disabled">
                            <muxc:ItemsRepeater
                                x:Name="HorizontalRepeater"
                                ItemsSource="{x:Bind product}"
                                ItemTemplate="{StaticResource HorizontalTemplate}">
                                <muxc:ItemsRepeater.Layout>
                                    <muxc:StackLayout Orientation="Horizontal" Spacing="12"/>
                                </muxc:ItemsRepeater.Layout>
                            </muxc:ItemsRepeater>
                        </ScrollViewer>
                    </muxc:ItemsRepeaterScrollHost>
                    <Button
                        x:Name="ButtonLeft"
                        Tapped="ButtonLeft_Tapped">
                        <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE76B;" FontSize="18" />
                    </Button>

                    <Button x:Name="ButtonRight"
                        Tapped="ButtonRight_Tapped">
                        <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE76C;" FontSize="18" />
                    </Button>
                </Grid>
```

Then use this code to scroll.
`sss.ChangeView(sss.ActualWidth, null, null);` This code does't not work.

But `sss.ScrollToHorizontalOffset(sss.ActualWidth);` works.

**Expected behavior**

ItemsRepeater can scroll left/right using `ChangeView` method.

**Screenshots**

**Version Info**

 OS: 18362.418

And a weird thing is, I actually saw this bug on 18362. But last night I upgrade my pc to 1909(18363.476), `ChangeView` method works.

NuGet package version: 

Microsoft.UI.Xaml: 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |   Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |   Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

In 18362(1903) or lower, `ScrollToHorizontalOffset`/`ScrollToVerticalOffset` works.
In 18363(1909), `ChangeView` and `ScrollToHorizontalOffset`/`ScrollToVerticalOffset` works.

So for a better compatible， `ScrollToHorizontalOffset`/`ScrollToVerticalOffset` is the best choice, although this api is out of date.

**Comment by jevansaks** [comment]
@ranjeshj is the problem that downlevel the customer needs the ItemsRepeaterScrollHost?

**Comment by jevansaks** [comment]
Oops I see it in the repro. Ok, @Ranjeshj can you investigate?

**Comment by ranjeshj** [comment]
@RBrid  - Is this expected behavior with ScrollViewer ? I know that setting some properties on ScrollViewer stop it from scrolling through interaction but i dont remember of the top of my head. Is that the same for using the APIs as well ?

**Comment by RBrid** [comment]
@ranjeshj, no - there is no way to turn off programmatic view changes, like for user interactions.

The first key questions to answer are:
- when the call is made, what are the values of 
    sss.ActualWidth
    sss.ViewportWidth
   sss.ScrollableWidth
?
- what is the return value of ChangeView?  True or False?
- is a finger down on the ScrollViewer when the call is made?  (is the call triggered by a user gesture?)

Thanks.
