### ISSUE TITLE
WinUI 3 alpha - Gallery App - What's New header issue

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1613]
**Describe the bug**
On the home page of the Gallery App, when you scroll down, the "What's New" text is rendered on top of elements once the header is scrolled off screen

**Steps to reproduce the bug**
- Open XAML Controls Gallery (WinUI 3 Alpha)
- Scroll down

**Expected behavior**
The "What's New" header text should be contained within the Header as it scrolls out of view.  Or the heading should be "stickied" to the top of the screen, and it's foreground colour changed to be readable on the background colour.

**Screenshots**
![image](https://user-images.githubusercontent.com/7389110/68862880-274fb000-06e6-11ea-9e4d-b0492058d6bd.png)

![image](https://user-images.githubusercontent.com/7389110/68862868-228afc00-06e6-11ea-95b4-06461268778e.png)

**Version Info**
1.2.16.0

NuGet package version: 
WinUI 3 Alpha

**Comment by kmgallahan** [comment]
This should probably go to the [gallery repo](https://github.com/microsoft/Xaml-Controls-Gallery/) which houses the [WinUI 3 Alpha Gallery codebase](https://github.com/microsoft/Xaml-Controls-Gallery/tree/winui3alpha) - unless you think the issue is caused by WinUI 3 iteself.

**Comment by mdtauk** [comment]
@kmgallahan  You are correct, I guess I posted it here by mistake.
