### ISSUE TITLE
TabView: Change TabStripFooter's MinWidth when app started with a narrow window is not take effect

### ISSUE THREAD

**Issue by yanshouwang** [microsoft/microsoft-ui-xaml#1615]
**Describe the bug**
 After extend TabView into the title bar, we need to change the TabStripFooter's MinWidth to keep off the title bar buttons. But change TabStripFooter's MinWidth when app started with a narrow window is not take effect

**Steps to reproduce the bug**
1. Extend the TabView into the TitleBar, and change the TabStripFooter's MinWidth when "OnTitleBarLayoutMetricsChanged" event is invoked.
2. Add 3 or more tabitems in the TabView.
3. Close the app with a narrow window state.
4. Open the app with the narrow window, the OnTitleBarLayoutMetricsChanged is invoked and the TabStripFooter's MinWidth is changed, but the TabView still mixed with the TitleBar's buttons until drag the window to a wide state.

**Expected behavior**
TabView shoud keep away from the TitleBar's buttons.

**Screenshots**
![批注 2019-11-15 000540](https://user-images.githubusercontent.com/24455689/68875725-44b06880-073e-11ea-8a8e-1383c3f1bd6c.png)
![批注 2019-11-15 000428](https://user-images.githubusercontent.com/24455689/68875750-4f6afd80-073e-11ea-8f63-ffa1dea07724.png)
![批注 2019-11-15 000350](https://user-images.githubusercontent.com/24455689/68875761-52fe8480-073e-11ea-967e-740dd7a6b759.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by YuliKl** [comment]
@teaP can you take a look?

**Comment by chingucoding** [comment]
@teaP Are you looking into this issue right now? If not, can I look into this issue? @StephenLPeters FYI.

**Comment by chingucoding** [comment]
@ranjeshj @teaP Is this safe to work on? This bug has also caused issues in the XCG for quite some time now.

**Comment by ranjeshj** [comment]
@chingucoding go for it.
