### ISSUE TITLE
Question: How do I remove the default rounded corner of Buttons and TextBoxes?

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/microsoft-ui-xaml#1626]
After upgrading to the latest WinUI library, the Buttons and TextBoxes have rounded corners. But I want the previous sharp corners.
Manually setting CornerRadius to 0 fro all the controls is a pain. Is there a `ThemeResource` which I can override to set the default corner radius to 0 for Buttons and TextBoxes?

**Comment by Felix-Dev** [comment]
@MuziburRahman There is a global control corner radius theme resource which you can use: `ControlCornerRadius`

Example:
```
<Page.Resources>
     <CornerRadius x:Key="ControlCornerRadius">0</CornerRadius>
</Page.Resources>
````

This sets the corner radius for every control on that page to 0 (excluding overlay controls such as Popup and Flyout). If you only want to change the control corner radius for select controls, I'm afraid you currently have to use styles to achieve this. 

Note that if you also want to restore the previous border thickness, you have per-control resources to achieve this:
```
<Page.Resources>
     <Thickness x:Key="TextControlBorderThemeThickness">0</Thickness>
</Page.Resources>
```

Additional resources to check out:
- [Preview API documentation](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/2cfd60c0a7ca0173268418c1d07de4b4888e8a45/active/RoundedCorner/roundedcorner.md) about Corner Radius
- [Fluent XAML Theme Editor](https://github.com/microsoft/fluent-xaml-theme-editor/tree/kisai/shape-font-customization) to easily visualize border thickness/control corner radius changes and code generation to include in your app

**Comment by MuziburRahman** [comment]
@Felix-Dev thanks a lot. :D

**Comment by chingucoding** [comment]
As @Felix-Dev mentioned there is an open issue regarding the setting of this value in application resources. However maybe this issue was partially resolved, since I was able to remove the corner radius by adding the following

`<CornerRadius x:Key="ControlCornerRadius">0,0,0,0</CornerRadius>`

to the application resources.
