### ISSUE TITLE
Windows 10 optimization with UWP

### ISSUE THREAD

**Issue by Strypper** [microsoft/microsoft-ui-xaml#1627]
**Describe the bug**
UWP don't consume my laptop ram as task-manager reported, but always felt choppy and unresponsived. It's hardly animate anything on 60fps when on 3000x2000 screen (from 2000x1500 fine though)

**Steps to reproduce the bug**
Scale Windows 10 up to 3000x2000 or higher, then begin use any WinRT app like (old edge browser) I'm sure you will see the difference between 30fps and 60fps

**Expected behavior**
Animation choppy and lag, app sometime freeze 

https://www.youtube.com/watch?v=u0Gx36d2VRQ&feature=youtu.be

**Version Info**
- UWP (max: 18362, min: 17763)
- Laptop (Surface Book 2016, Intel I5 63000U, GeForce 940M)
- Windows 10 (10.0, Build 19013)
| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes  |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       | No Idea   |
| Creators Update (15063)            | No Idea   |

Surface book 2016 core i5, 940M

**Additional context**
If I resize my UWP app windows down very small (the point where UWP display only less than 2000 pixels) Windows 10 remain smooth and responsive. If switch to full screen mode, the app will end up like in the video,
Already put windows in high performance mode
Already update Nvidia Driver to the lastest
Already turn on High performance mode on every single UWP app in graphic setting
**My Opinion**
Since WPF and Win32 most of them default not enhanced for HDPI, I think that's the reason why UWP so choppy on High Res. It pack the whole pixels to the animations

**Comment by dotMorten** [comment]
Is the app running on the Nvidia GPU or the integrated GPU? There's been a firmware issue that made Microsoft disable the Nvidia GPU. Could just be it can't keep up. Also are you using an external monitor and if so how's it connected?

**Comment by Strypper** [comment]
> Is the app running on the Nvidia GPU or the integrated GPU? There's been a firmware issue that made Microsoft disable the Nvidia GPU. Could just be it can't keep up. Also are you using an external monitor and if so how's it connected?

This happen to both OnBoard-Intel GPU and Nvidia 940M. And no, I connected to no external display

**Comment by adrientetar** [comment]
FYI my laptop is 3000×2000 (Matebook X Pro, Intel GPU) and I don't have this issue. It's probably the specific hardware configuration or install of Windows.

**Comment by Strypper** [comment]
> FYI my laptop is 3000×2000 (Matebook X Pro, Intel GPU) and I don't have this issue. It's probably the specific hardware configuration or install of Windows.
> 
> Try disable "Panel Self Refresh" in Intel settings as it can cause flickering on the intel gpu.

Downloaded Intel Graphics Command Center
Disable Panel Self Refresg + Maximum Performance 
Still the same

**Comment by Strypper** [comment]
Seriously you guys gonna ignore this ? all of the High Resolution laptop in my office are really suffer from Frames Drop and Freezing. All of them are WinRT app. Win32 don't have issue

**Comment by jevansaks** [comment]
Sorry, we've been on Thanksgiving holiday for the last few days. We'll need you to take some traces to diagnose further -- I've sent email to my colleagues and I'll get back to you.

**Comment by Strypper** [comment]
> Sorry, we've been on Thanksgiving holiday for the last few days. We'll need you to take some traces to diagnose further -- I've sent email to my colleagues and I'll get back to you.

If you want more evidence I will upload more of Surface devices to show you 
I've been dig in and see what XAML element cause this and the Answer are 

- GridView 
- Acrylic 

I thought I didn't applying it right but then I notice many big UWP app on the store all have the same issue 

- This is my app https://github.com/Strypper/OClubs
- Awesome Tube
- Microsoft Edge

**Comment by kmelmon** [comment]
@Strypper Can you capture a trace using this tool and share with us:
https://answers.microsoft.com/en-us/windows/forum/windows_10-update/windows-performance-recorder/a1648e8c-50c7-4243-9f1d-4216385c7ff3
The settings you'll want to turn on for the trace:
-Under Scenario Analysis:
    Xaml App Responsiveness
    Video Glitches
-Under Resource Analysis:
    CPU activity
    GPU activity
This should give us enough info to see exactly what is causing the animation to be glitchy.
Thanks!

**Comment by codendone** [comment]
Closing for now. Please reactivate if you have a trace for us to investigate.
