### ISSUE TITLE
Bugs in ProgressBar style

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#1628]
**Describe the bug**

There are several bugs in the ProgressBar style. This needs to be reviewed in detail by MSFT.

Foreground is set twice in the XAML style of progress bar:

```XML
    <Style TargetType="local:ProgressBar">
        <Setter Property="Foreground" Value="{ThemeResource SystemControlHighlightAccentBrush}" />
        <Setter Property="Background" Value="{ThemeResource SystemControlBackgroundBaseLowBrush}" />
        <Setter Property="BorderThickness" Value="{ThemeResource ProgressBarBorderThemeThickness}" />
        <Setter Property="BorderBrush" Value="{ThemeResource SystemControlHighlightTransparentBrush}" />
        <Setter Property="Foreground" Value="{ThemeResource SystemControlForegroundAccentBrush}" />
```

A brush is being set as thickness

```XML
<Border x:Name="ProgressBarRoot"
              Background="{TemplateBinding Background}"
              BorderBrush="{TemplateBinding BorderBrush}"
              BorderThickness="{TemplateBinding BorderBrush}"
```

Setting a clipping here also seems to be unnecessary but I might be missing something.
```XML
<Border Clip="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.ClipRect}">
```

Please, please take care in code reviews!

**Lines of code are here**

https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/ProgressBar/ProgressBar.xaml

https://github.com/microsoft/microsoft-ui-xaml/blob/1a62591f95c4cec7af5360ca271e52dc4eb5443f/dev/ProgressBar/ProgressBar.xaml#L10

https://github.com/microsoft/microsoft-ui-xaml/blob/1a62591f95c4cec7af5360ca271e52dc4eb5443f/dev/ProgressBar/ProgressBar.xaml#L14

https://github.com/microsoft/microsoft-ui-xaml/blob/1a62591f95c4cec7af5360ca271e52dc4eb5443f/dev/ProgressBar/ProgressBar.xaml#L100

**Comment by YuliKl** [comment]
@karenbtlai can you take a look?

**Comment by robloo** [comment]
This should be an easy one to fix/review. Any feedback?

**Comment by jevansaks** [comment]
@robloo if you're suggesting that you want to do a PR to fix, we would be happy for you to do that. :)

**Comment by jevansaks** [comment]
Also if it means that we're lacking test coverage which would have caught it, please add some as part of the change!

**Comment by karenbtlai** [comment]
@robloo Thanks for submitting the issue and I apologize for the late response! The fix for this will actually be in the PR that will be submitted later tonight along with other accessibility features.

**Comment by robloo** [comment]
@jevansaks I'm always happy to help where I can! Hopefully, it didn't sound like I was pushing too much (I know you all are busy). I just knew it was easy and didn't want it to get lost with the other changes. In the future I would be happy to help with XAML fixes like this; however, UI unit tests I would have to read up on more.

@karenbtlai Ok, awesome! Thanks for following up with this :)
