### ISSUE TITLE
[UWP] Set Brush properties are invalid for control ScrollBar

### ISSUE THREAD

**Issue by v-wenjuz** [microsoft/microsoft-ui-xaml#1629]
Steps to reproduce:
 
1. Create a  C# UWP application.
2. Open the MainPage.xaml, and add a ScrollBar inside the Grid.
3. Try to set the background or borderbrush for ScrollBar.
 
Expected: 
the properties are all valid for ScrollBar 
 
 
Actual: 
the properties are all invalid for ScrollBar 

**Version Info**
Affected Branch: master/16.4/16.3
Affected Build: 29511.173/29511.114/29509.03
Affected SKU: ENT
Affected Product Language:  EN
Operation System Information:19h2
.NetCore Version: 3.1.1 p2-014569

**Comment by YuliKl** [comment]
@v-wenjuz can you clarify what you mean by invalid?
