### ISSUE TITLE
SelectionModel fires selection changed events when selection hasn't changed

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#1642]
I think that this issue is exclusive to SingleSelect. Selection Model clears selection as the first action whenever you call select on it.

**Comment by jevansaks** [comment]
@StephenLPeters from the description this seems simple enough. Can you take it?

**Comment by chingucoding** [comment]
@StephenLPeters Are you currently looking into this? 😅 If not, I would like to take this issue @ranjeshj .
