### ISSUE TITLE
Discussion: WinUI, Mixed Reality and the Future of Windowing

### ISSUE THREAD

**Issue by niels9001** [microsoft/microsoft-ui-xaml#1643]
# Discussion: WinUI, Mixed Reality and the Future of Windowing
One of the great things about WinUI, are wide range of input modalities such as mouse, keyboard, touch, controller, voice and even gaze! Another part is the cross platform model that is able to run our experiences on a wide range of device types, and even work in the Mixed Reality world on Immersive Headset and HoloLens.

However, these apps cannot be optimized for e.g. HoloLens UI-wise: it will render the app as a 2D slate. To take advantage of all the unique features of HoloLens developers basically need to start over and built their apps in Unity (although C#, it's basically a complete re-write).

I was wondering, especially since Microsoft is investing so much in Holographic computing, what the long term plan is for WinUI in this space? It would be great if we can some how tailor our experiences to the 3D world with [AppWindow ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow)and 3D UI styling.

Very much related to that, is the future of windowing. Would be great if the team could shed some light on what we can expect!

At Build 2018, there were some excellent talks about this topic and how teams in Microsoft are thinking about this next gen platform in terms of user experiences. I'm really excited about this and the possibilities it can bring and I'm wondering how the team, and the community is thinking about this going forward. For LOB apps, re-writing the UI in Unity to take advantage of Holographic computing is too much effort and requires additional skills - if it can seamlessly move and be optimized for that with WinUI x.x. / Windows vNext that would be awesome :)!

![FluentSpatial2](https://user-images.githubusercontent.com/9866362/69221982-ce19cd80-0b78-11ea-9325-a188cca98074.gif)

![FluentSpatial3](https://user-images.githubusercontent.com/9866362/69222555-ffdf6400-0b79-11ea-8c5f-566d3608f4c2.gif)

![Capture](https://user-images.githubusercontent.com/9866362/69224026-18507e00-0b7c-11ea-8ec0-0e8d66098e26.PNG)

![Windowing](https://user-images.githubusercontent.com/9866362/69224331-a0cf1e80-0b7c-11ea-84c0-e2682c301076.gif)

## Related Links
**[Our Fluent Path to Spatial Computing: Easy as 1-2D-3D (Build 2018)](https://youtu.be/kY5DnTHVcpc?t=782)** by Mike Harnisch

**[Building powerful desktop and MR applications with new Windowing APIs (Build 2018)](https://youtu.be/hZU0HDTI-zs?t=1846)** by Roberth Karman

**Comment by mdtauk** [comment]
Part of this will probably require OS APIs and changes, and not something that can be done entirely within WinUI - but it will be good to see some movement on this, especially for enabling Win32 apps to replace existing UI to XAML, with modal windows, tool windows, and possibly MDI parent windows, with the TabView.

**Comment by petroemil** [comment]
I think in the context of WinUI what we can realistically talk about is a 2.5D kind of UI elements... with a bit of thickness, some dropshadow, a bit of perspective... maybe positioning windows in the 3D space. But at the end of the day we have to keep in mind the "cross-platform" or "cross-device" nature of WinUI. Something truly 3D wouldn't work on any other device other than Mixed Reality devices.

With that said, I'm looking forward to those 2.5D additions, to give windows and UI elements a physical feel and also to support MR interactions in a natural, intuitive way.

![slider1](https://user-images.githubusercontent.com/13720703/69423784-fe02d580-0d1e-11ea-9a2d-fe7c0269fae2.gif)
![slider2](https://user-images.githubusercontent.com/13720703/69423786-fe02d580-0d1e-11ea-98b8-f02e5b72b185.gif)
![slider3](https://user-images.githubusercontent.com/13720703/69423787-fe02d580-0d1e-11ea-801a-5db3e6cd574e.gif)
![buttons](https://user-images.githubusercontent.com/13720703/69423790-00fdc600-0d1f-11ea-8e8e-c4e3cafd473b.gif)

GIFs are from [Intro to Building Apps for HoloLens 2 Using Unity and Mixed Reality Toolkit](https://www.youtube.com/watch?v=P8og3nC5FaQ)

**Comment by mdtauk** [comment]
> I think in the context of WinUI what we can realistically talk about is a 2.5D kind of UI elements... with a bit of thickness, some dropshadow, a bit of perspective... maybe positioning windows in the 3D space. But at the end of the day we have to keep in mind the "cross-platform" or "cross-device" nature of WinUI. Something truly 3D wouldn't work on any other device other than Mixed Reality devices.
> 
> With that said, I'm looking forward to those 2.5D additions, to give windows and UI elements a physical feel and also to support MR interactions in a natural, intuitive way.
> 
There were some early experiments with 3D Markup being explored.  Also Build mentioned taking XAML elements, and rendering the controls outside of the window, attaching them to your hands, etc.
![image](https://user-images.githubusercontent.com/7389110/69424640-08be6a00-0d21-11ea-9539-8f03458a56d7.png)
![image](https://user-images.githubusercontent.com/7389110/69424647-1116a500-0d21-11ea-8fc0-be37aaf0c8b0.png)

**Comment by niels9001** [comment]
Agreed.. for full-blown 3D experiences Unity would be the better option. But to have 2.5D slates out side of the main view, with 2.5D styling would already be a super great start.
