### ISSUE TITLE
Proposal: Add support for Pickers objects in XAML Islands

### ISSUE THREAD

**Issue by edetoc** [microsoft/microsoft-ui-xaml#1644]
# Proposal: Add support for Pickers objects in XAML Islands

## Summary

In a pure UWP world it is possible to create a custom user control and show a Picker object, like a FolderPicker for instance, from its code behind:

```
public sealed partial class MyUserControl1 : UserControl
{
	public MyUserControl1()
	{
		this.InitializeComponent();
	}

	private async void Button_Click(object sender, RoutedEventArgs e)
	{
		var fp = new FolderPicker();

		fp.FileTypeFilter.Add("*");
		var sf = await fp.PickSingleFolderAsync();

		if (sf != null)
			myButton.Content = sf.DisplayName;
	}
}
```

The link below describes and provides a sample on how to create a custom UWP user control as a XAML Island in a WPF application:

https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands

the sample could be easily modified (as above) to show a FolderPicker from the code behind of the user control. However in this scenario the call to PickSingleFolderAsync will cause the WPF application to crash. Here's the Visual Studio debug output showing the crash:

_onecore\shell\lib\calleridentity\callerwindow_twinapi.cpp(111)\twinui.appcore.dll!00007FFEB45899F5: (caller: 00007FFEB4589728) ReturnHr(1) tid(1794) 80040155 Interface not registered
    CallContext:[\PickSingleFolderAsync\SingleStorageItemOperation] 
Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
An exception of type '**System.Exception**' occurred in System.Private.CoreLib.dll but was not handled in user code
**Invalid window handle**. (0x80070578)_

it turns out Pickers objects in custom controls used as XAML Islands are currently not supported.

## Rationale

* Usage of Pickers objects in UWP user controls is a common scenario

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to use Pickers objects in XAML Islands | Must |

**Comment by contextfree** [comment]
It's apparently possible to use UWP pickers in Win32 apps now via the IInitializeWithWindow pattern, an explanation and example using C++/WinRT is here: https://devblogs.microsoft.com/oldnewthing/20190412-00/?p=102413

And here's an example of using IInitializeWithWindow in C# (for a different scenario): https://www.codeproject.com/Articles/5162896/Monetize-your-App-in-Microsoft-Store

This is a bit cumbersome and makes it harder to share code between UWP and Win32 apps, so maybe XAML Islands or another mechanism should provide a way to set up a global default window for the thread as UWP does.

**Comment by Austin-Lamb** [comment]
It wouldn't make sense for XAML Islands to establish a window for the thread, as a Win32 app is allowed to have multiple top-level windows on the same thread.  Those windows could be on different monitors, which would affect where you'd want the picker to show up - so the IInitializeWithWindow pattern is the correct way to do this as far as I know.

@edetoc - I'm going to close this, but please reactivate if you're not able to use the IInitializeWithWindow pattern.

**Comment by edetoc** [comment]
thanks @Austin-Lamb @contextfree 
indeed the IInitializeWithWindow  pattern helped me resolves this issue.
see my sample here:  [https://github.com/edetoc/samples/tree/master/WpfXamlIslandTest](url)
