### ISSUE TITLE
SelectionModel SelectionChangedEventArgs should be expanded

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#1645]
The selection changed event should report the previous and currently selected indices. Currently there is no way to know which index was selected before the changed event, in case you need to do clean up on those indices.

**Comment by jevansaks** [comment]
@ranjeshj @stephenlpeters can you recommend the API to use here? Presumably we have prior art from ListView that we can follow.

**Comment by ranjeshj** [comment]
AddedItems/RemovedItems is what Selector exposes. I would recommend AddedIndices/RemovedIndices since selection model works with indices and not the items.

**Comment by jevansaks** [comment]
Is RemovedIndices useful after the collection changes? Items makes sense, but I'm struggling to see how Indices would be used in practice.

**Comment by ranjeshj** [comment]
probably a better name would be SelectedIndices and DeselectedIndices or something along those lines .

**Comment by jevansaks** [comment]
But if an item is removed then I assume SelectionModel would "deselect" it, right?

**Comment by adrientetar** [comment]
I think you can just use Old/New like other eventargs already do.

**Comment by ranjeshj** [comment]
I see what you mean. The old index probably does not make sense once the item has been removed from the collection but old item does. If the index is removed, then we don't care about restoring the selection state for that container, so should it not be in the list ?

**Comment by jevansaks** [comment]
[SelectionChangedEventArgs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.selectionchangedeventargs?redirectedfrom=MSDN&view=netframework-4.8) has only AddedItems and RemovedItems, I suspect for a similar reason. 

Thinking more about @StephenLPeters's scenario I wonder if what we really want is AddedContainers+RemovedContainers? That way you can directly manipulate and clean up state on the UI elements instead of caring about their new or old indices.

**Comment by ranjeshj** [comment]
SelectionModel just tracks the collections and selected index ranges. It does not track containers (decoupled from the containers).

**Comment by grokys** [comment]
I've started porting `SelectionModel` to Avalonia, and the lack of information on what has changed in the selection is a show-stopper for us, so I was thinking of adding this feature: first to Avalonia and then trying to port it to WinUI (very rusty C++ skills permitting).

The comments here are on the money IMO: the best thing to expose would be indexes, but this is no use when items are removed from the source collection. For this, there will also have to be a `SelectedItems`/`DeselectedItems` property.

I'd like to propose the following API:

```csharp
public class SelectionModelSelectionChangedEventArgs : EventArgs
{
	/// <summary>
	/// Initializes a new instance of the <see cref="SelectionChangedEventArgs"/> class.
	/// </summary>
	/// <param name="selectedIndices">The indexes added to the selection.</param>
	/// <param name="deselectedIndices">The indexes removed to the selection.</param>
	/// <param name="removedItems">Any selected items removed from the source collection.</param>
	public SelectionModelSelectionChangedEventArgs(
		IReadOnlyList<IndexRange> selectedIndices,
		IReadOnlyList<IndexRange> deselectedIndices,
		IReadOnlyList<object> removedItems);

	/// <summary>
	/// Gets the indices of the items that were added to the selection.
	/// </summary>
	public IReadOnlyList<IndexRange> SelectedIndices { get; }

	/// <summary>
	/// Gets the indices of the items that were removed from the selection.
	/// </summary>
	public IReadOnlyList<IndexRange> DeselectedIndices { get; }

	/// <summary>
	/// Gets the items that were added to the selection.
	/// </summary>
	public IReadOnlyList<object> SelectedItems { get; }

	/// <summary>
	/// Gets the items that were removed from the selection.
	/// </summary>
	public IReadOnlyList<object> DeselectedItems { get; }
}
```

Where `SelectedItems` would simply get the items for `SelectedIndices`, but `DeselectedItems` would both get the items for `DeselectedIndices` but _also_ return `removedItems`.

This means that `DeselectedIndices.Count` may not always equal `DeselectedItems.Count`.

Questions:

- Should `removedItems` be exposed separately too?
- Should there be a flag for "indexes changed" where the selection hasn't changed, but the indexes of some of the selection has changed?
- How should this be implemented? Should the selected/deselectedIndices be built up by the `SelectionNode` as it does its work, or should we store a list of the currently selected indices at the start of an operation and diff it with the selected indices at the end?

**Comment by ranjeshj** [comment]
We could cache indices and diff, but we need to be careful about performance. We will need to generate and do the diff only when someone is asking for these properties. 

To give you some context, the API that the selection model that was initially designed around was that each container could listen to the selection changed and check its state and toggle if its state had changed. Hence the lack of these properties in the args or selection model itself.

**Comment by grokys** [comment]
> We will need to generate and do the diff only when someone is asking for these properties.

So make a copy of the `IndexRange`s before carrying out the operation, and pass these to the `SelectionModelSelectionChangedEventArgs`? 

> To give you some context, the API that the selection model that was initially designed around was that each container could listen to the selection changed and check its state and toggle if its state had changed.

Is the wish to keep `SelectionModel` limited to that scenario or to extend it? In my estimation the majority of scenarios will need to know what has changed in the selection, otherwise the API consumer will be forced into making a copy of the existing selection in order to work out what changed themselves (which essentially is what keeping a selection state in the container is doing).

**Comment by ranjeshj** [comment]
There are a couple of ways to do the diff. Either have the nodes keep track of what has changed and then accumulate it from SelectionModel or store it in selection model itself. Either way should work but perhaps the first option might be simpler to implement. 

@grokys, If it makes sense to have these properties, then i have no reservations in adding them, given that you and Stephen and you both hit this, it is likely that others will as well.

**Comment by grokys** [comment]
I've come up with an initial implementation of this in the Avalonia C# port of `SelectionModel` over at https://github.com/AvaloniaUI/Avalonia/pull/3470.

If you have time, I'd be interested to see what you think. One outstanding issue is what to do on collection reset. In this case, we don't have either indexes or items to present in the notification. Maybe a boolean `CollectionWasReset` flag is all that's needed?

**Comment by ranjeshj** [comment]
> If you have time, I'd be interested to see what you think. One outstanding issue is what to do on collection reset. In this case, we don't have either indexes or items to present in the notification. Maybe a boolean `CollectionWasReset` flag is all that's needed?

The way it is currently implemented is that we lose all the selected items and that is reflected in the event. We could avoid this if the ItemsSource implements IKeyIndexMapping, but checking what items in the selected ranges still remain after the reset. Also, I'm not sure about the CollectionWasReset flag - what possible action could the app do with that information ?

**Comment by grokys** [comment]
>  I'm not sure about the CollectionWasReset flag - what possible action could the app do with that information ?

Yeah, I'm not sure either, but it seems that we should have some way to let the user know: "the collection was reset and we can't do anything about it; you're on your own here".

I am going to open a new issue to talk about handling collection resets.

**Comment by grokys** [comment]
Another question: a selection can be made before `Source` is set. Current `SelectionChanged` is raised in this case. What should happen here?

1. `SelectedIndices` is set, `SelectedItems` is empty
2. `SelectedIndices` is set, `SelectedItems` contains `null` items
3. Don't actually raise `SelectionChanged` here as there's actually no selection

**Comment by grokys** [comment]
Actually looking further into this, yes [selection can be made with a `null` source](https://github.com/microsoft/microsoft-ui-xaml/blob/49d724e1d9f77d9c29a86bc09b749c4ec2c8dd7c/dev/Repeater/SelectionNode.cpp#L334-L337) and I assumed this was to allow a selection to be initialized before `Source` was set.

However, setting `Source` calls `[ClearSelection](https://github.com/microsoft/microsoft-ui-xaml/blob/49d724e1d9f77d9c29a86bc09b749c4ec2c8dd7c/dev/Repeater/SelectionModel.cpp#L46)` so maybe this isn't the reason? What was the reasoning here?

**Comment by ranjeshj** [comment]
@grokys  The idea is to keep Source as optional for flat case and fallback to not handling change notifications or index validations in that case.Perhaps we can just block that case and require that when setting source nothing be selected ? Do you see cases where the model is used for a little bit before source is set ?

**Comment by grokys** [comment]
Being able to set a selection before the `Source` is set is actually really useful in cases where `SelectionModel` backs a `ListBox`-type control:

```
<ListBox SelectedIndex="0" ItemsSource="{Binding Foo}"/>
```

Here `SelectedIndex` will be written before `ItemsSource`, and if you can set a selection before setting the source, the setter for `SelectedIndex` can call straight into the `SelectionModel.Select(value)` for example. If the `Source` needs to be set first, this gets a lot more complicated.

**Comment by ranjeshj** [comment]
Cool. That makes sense.

**Comment by grokys** [comment]
Excellent. Which of the [choices](https://github.com/microsoft/microsoft-ui-xaml/issues/1645#issuecomment-581392860) for `SelectionChanged` would be the best in this case in your opinion?

**Comment by ranjeshj** [comment]
We definitely want to raise selection changed when the selected indices change (even when no source is present). SelectedIndex values can always be valid, so no problems there. SelectedItems perhaps can be null to notify that there is no source and empty when there are no selected items. I think it would make sense to also raise the selection changed event again when the source is set to notify that there are items now that were already selected to give the handler a chance to do its thing on items. Thoughts ?

**Comment by grokys** [comment]
Ok, yeah that confirms what I thought. My implementation notifies with `SelectedIndices` set and `SelectedItems` empty. When `Source` is finally assigned, it raises another event with both `SelectedIndices` and `SelectedItems`  set.

**Comment by chingucoding** [comment]
I would like to take my shot at this, but I am a bit lost right now what the best option would be. Should we add "RemovedIndex" and/or "RemovedItem(s)" or what would be the right direction here?

**Comment by StephenLPeters** [comment]
@ranjeshj @chingucoding reading through the comments I'm not sure a behavior has been decided on.  I think before someone tries to fix the issue we should have a doc which explains the proposed API and goes through the edge cases discussed here.

**Comment by ranjeshj** [comment]
There are a bunch of details in this issue thread. @grokys - since you have gone through this process, would you be able to write down the details as a proposal with all the necessary details ? That would be really helpful.

**Comment by grokys** [comment]
Apologies for not getting back to you. I am mainly waiting for user testing to see if my changes have any problems. In the meantime, I'll start working on a proposal. Do you have a recommendation as to a similar proposal that I can use to see what mine should look like?

**Comment by ranjeshj** [comment]
@grokys You can see some existing feature proposals [here](https://github.com/microsoft/microsoft-ui-xaml/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+proposal%22). Please add the API information and details, reasoning etc that you hit during your effort. Thanks!

**Comment by anawishnoff** [comment]
Hi @grokys - do you have any updates/new details for a proposal? We are planning to start speccing out this feature soon!

**Comment by grokys** [comment]
Hi @anawishnoff - sorry about that, the PRs for the ports and features still haven't been reviewed over on Avalonia, but I can open a proposal with what I have so far.

**Comment by grokys** [comment]
Opened a proposal over at https://github.com/microsoft/microsoft-ui-xaml/issues/2247

I'm not sure I've got the level of detail correct in the proposal, please let me know if you want me to add more information on the API/implementation.
