### ISSUE TITLE
NavigationView prevents full navigation with an xbox contoller on Windows 10

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#1647]
**Describe the bug**
Having Settings visible on a NavigationView can prevent navigation to content in the page.

**Steps to reproduce the bug**
1. In a new blank app, add the following.

```xml
    <winui:NavigationView
        IsSettingsVisible="False">
        <Grid>
            <StackPanel>
                <RadioButton Content="Option 1" />
                <RadioButton Content="Option 2" />
                <RadioButton Content="Option 3" />
            </StackPanel>
        </Grid>
    </winui:NavigationView>
```

2. Connect an XBoxOne controller to a Windows desktop PC.
3. Run the app and notice that it's possible to use the controller to move focus to all 3 of the radio buttons.
4. Close app.
5. Change the [above] code to set `IsSettingsVisible="True"`.
6. Run the app again and notice that it's NOT possible to use the controller to move focus to the radio button captioned **Option 3**.

**Expected behavior**
It should be possible to use the xbox controller to get to every control on a page that can receive focus.
I understand that the issue is likely due to the XY navigation system only having a single item at the bottom of the screen but as pressing down when the focus is on **Option 2** this doesn't explain why focus cannot move to the radio button directly beneath it (Option 3).

This is not an issue of an automatically implied [radiobutton]group being applied to the `RadioButton`s.
1. If it was it should still be possible to navigate between the options in the group.
2. Changing the `RadioButton`s to `Button`s (so there should be no implied grouping of related options) still produces the same behavior. 

**Screenshots**
n/a

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
This issue was discovered as part of investigation into https://github.com/microsoft/WindowsTemplateStudio/issues/3407 A workaround is also listed there.
I appreciate that using an xbox controller to navigate a desktop app is a niche scenario but it is supported.

**Comment by shaheedmalik** [comment]
I figure this would also affect using a controller on Hololens and Xbox as well. If I could, I would use the controller to control the entire OS.

**Comment by jevansaks** [comment]
@Austin-Lamb can you help take a look?

**Comment by Austin-Lamb** [comment]
Thanks for reporting this!  I'm going to put this on my team's backlog - it may be related to the XYFocus system we have, but I'm not sure yet.
