### ISSUE TITLE
Provide documentation and samples around sharing ElementAnimator instances

### ISSUE THREAD

**Issue by bschoepke** [microsoft/microsoft-ui-xaml#165]
# Proposal: Provide documentation and samples around sharing ElementAnimator instances

## Summary
For scenarios where multiple ItemsRepeaters are nested inside each other--for example, a toolbar where each button has several icons that come and go--it's possible to share ElementAnimator instances between all the ItemsRepeaters in order to ensure add/remove animations within nested ItemsRepeaters are coordinated with parent ItemsRepeaters.

## Rationale
This powerful animation capability isn't obvious, and should be called out in docs and a sample.

**Comment by jevansaks** [comment]
@micahl you want this one? :)
