### ISSUE TITLE
Changes to MenuFlyoutSubItem.Items don't update UI

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#1652]
**Describe the bug**
Changes to `MenuFlyoutSubItem.Items` don't update UI. Sub menu shows previous items.

**Steps to reproduce the bug**
1. Create `MenuFlyout` with `MenuFlyoutSubItem` within.
2. Fill `MenuFlyoutSubItem.Items`
3. Show `MenuFlyout` and check content of  `MenuFlyoutSubItem` submenu
4. Call `MenuFlyoutSubItem.Items.Clear()` and than fill  `MenuFlyoutSubItem.Items` with new items
5. Open `MenuFlyout`  and check content of  `MenuFlyoutSubItem` submenu It's same as in step 3.

**Expected behavior**
`MenuFlyoutSubItem` menu should represent current `MenuFlyoutSubItem.Items` and follow it's changes

**Version Info**
`Windows.UI.Xaml.Controls.MenuFlyoutItem` from Windows 18362 SDK

**Comment by jevansaks** [comment]
Interesting bug! Probably a missing binding or something. I imagine the bug is in the framework so this would need WinUI 3 for a fix.

**Comment by SnowyWreath** [comment]
This bug is inhibiting me from offering a Recent Files submenu in my app.

**Comment by JosephMart** [comment]
@SnowyWreath running into the same issue. A hack I have found that seems to work so far is to reinstantiate `MenuFlyoutSubItem` every time you need to update it's Items.... 🤢

**Comment by mrjfalk** [comment]
@jevansaks Any progress on this issue?  The same bug appears in WinUI3 (WinAppSDK 1.0.0) as well.

**Comment by andreaslennartz** [comment]
@jevansaks Can confirm that this bug still exists in 1.1.4
As workaround, I needed to remove the `MenyFlyoutSubItem` completely from the menu, and reinsert it with a completely new instance.

**Comment by JohnCido** [comment]
This bug still presents in 1.2.221209.1, any updates? This should be considered a serious bug since this effect many apps that rely on submenus.

**Comment by JPTGamesAndApps** [comment]
WinAppSDK 1.3 continues to have this issue. Wasted quite a bit of time not knowing about this bug.

**Comment by shinta0806** [comment]
I faced same probrem, too. WindowsAppSDK 1.3.2.

**Comment by shinta0806** [comment]
Seems to be resolved in WindowsAppSDK 1.4.4.

**Comment by DmitriyKomin** [comment]
Thank you @shinta0806 for that bit of good news, I will go ahead and resolve. @ad1Dima, please comment here if you can still repro the issue in some way.
