### ISSUE TITLE
CredUIPromptForWindowsCredentials crashes in Win32 application

### ISSUE THREAD

**Issue by StefanJKern** [microsoft/microsoft-ui-xaml#1662]
**Describe the bug**
Invoking `CredUIPromptForWindowsCredentialsW` spuriously crashes the program after numerous Exceptions finally with Exception code: 0xe06d7363 in KERNELBASE.dll.

Our Application is a non-unicode Win32 Qt Application.

**Steps to reproduce the bug**
1. Invoke  `CredUIPromptForWindowsCredentials` from Main Thread multiple times until the program crashes. The bug usually occurs on the first or second invocation.

The first relevant Exception seems to be `Platform::InvalidCastException`  which gets raised in a Worker Thread in `SHCore.dll`. The error does not occur when I step through the code with the attached debugger.  Hiere is a [Minidump of Invalid Cast](https://github.com/microsoft/microsoft-ui-xaml/files/3878500/SpecsLabProdigy.Invalid.Cast.zip). 

Continuing after this exception I get a `Platform::ComException` rethrown a few times and than a memory access violation in wincorlib.dll reading 0xFFFFFFFFFFFFFFFF ([AccessViolation Minidump](https://github.com/microsoft/microsoft-ui-xaml/files/3878515/AccessViolation.zip))

Hier is a [CredUIPromptForWindowsCredentials Code Snippet](https://github.com/microsoft/microsoft-ui-xaml/files/3878520/CredUIPromptForWindowsCredentials.Code.Snippet.txt) of what we are doing. Removing the call `TaskFree` (leaking the memory) does not help.

**Expected behavior**
`CredUIPromptForWindowsCredentialsW` returns credentials entered by user without crashing.

**Version Info**
- Windows 1909 (OS Build 18363.476)
- Compiler is VS 2013 (this dump is compiled with VS 2019 using compatibility mode but this is not relevant)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| September 2019 Update (18363)          |  Yes (1909) |
| May 2019 Update (18362)            |  Yes (1903) |
| October 2018 Update (17763)        |     |
| April 2018 Update (17134)          | Yes (1803)   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by Felix-Dev** [comment]
@StefanJKern It does not appear to me - based on the context you have provided - that this is an issue for the WinUI team. Feedback Hub might be a better choice.

**Comment by jevansaks** [comment]
Thanks for all the details. I was able to track down an existing internal bug for this. Since it's not an issue in WinUI (it's in the OS), I'm going to close this issue. If you want to be able to track the internal issue and see when it gets resolved yourself, you can file a Feedback Hub item and share the link to it here. I can connect the feedback item to the existing bug so you can see when it's resolved.

**Comment by StefanJKern** [comment]
Thank you @jevansaks  for your help. I will file an issue next week. Hopefully I can get some information how to work around this issue until this issue is resolved.
