### ISSUE TITLE
Question: WinUI 3 and external libraries

### ISSUE THREAD

**Issue by jasonwurzel** [microsoft/microsoft-ui-xaml#1668]
In our currently developed project (UWP) we are using some external libraries, eg.: ReactiveUI, Win2D, CompositionProToolkit, Microsoft.Toolkit.*
We are very eager to upgrade to WinUI 3 when the time has come and the project has matured enough. 
But the question is, there would have to be a special WinUI version for all of our dependencies, right? This could mean a fair amount of extra work being that behind those dependencies of course is another tree of (maybe UWP related) dependencies, which would have to be converted to WinUI 3 themselfes.

Am I right in my assesment of the situation and what are the team's thoughts on this?

**Comment by kmgallahan** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/717

**Comment by jevansaks** [comment]
> Am I right in my assesment of the situation and what are the team's thoughts on this?

Yes, that's correct for where we're at with WinUI 3. We'd love your feedback on the threads that @kmgallahan linked. Especially if you have ideas about how to make this easier for scenarios like this. :)
