### ISSUE TITLE
Question: System.Windows.Window part of WinUI?

### ISSUE THREAD

**Issue by DHitchenUK** [microsoft/microsoft-ui-xaml#1684]
WinUI is looking great and I'm looking forward to translating my WPF apps to use it.

One of the areas we struggle with is System.Windows.Window, specifically all the UWP goodness like control of the title bar, extending the UI into the chrome area.

**Will there be a Windows.UI.Xaml.Window with full control similar to UWP ?**

**Comment by robloo** [comment]
Allowing multiple Windows in UWP now WinUI is something that I believe Microsoft promised back at Build 2018. 

https://mspoweruser.com/microsoft-finally-makes-it-easier-to-create-multi-window-experiences-in-uwp-apps/

Take a look at `AppWindow` [Preview AppWindow Class Docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow)

I believe this is coming in WinUI 3.0 now? Never used it myself.

Sounds like you already know about this too:
https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar

**Comment by DHitchenUK** [comment]
> Allowing multiple Windows in UWP now WinUI is something that I believe Microsoft promised back at Build 2018.
> 
> https://mspoweruser.com/microsoft-finally-makes-it-easier-to-create-multi-window-experiences-in-uwp-apps/
> 
> Take a look at `AppWindow` [Preview AppWindow Class Docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow)
> 
> I believe this is coming in WinUI 3.0 now? Never used it myself.
> 
> Sounds like you already know about this too:
> https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar

I asked if this was coming to WPF, not UWP - we already have this in UWP as you mentioned.

**Comment by shaheedmalik** [comment]
> 
> I asked if this was coming to WPF, not UWP - we already have this in UWP as you mentioned.

The point is to move over to WinUI 3.

**Comment by shaheedmalik** [comment]
WinUI is the where everything is moving to.

**Comment by Kinnara** [comment]
There are some WPF libraries that implement the "ExtendViewIntoTitleBar" feature. Just to name a couple:

1. [ModernWpf](https://github.com/Kinnara/ModernWpf) (disclaimer: I'm the author)
2. [FluentWPF](https://github.com/sourcechord/FluentWPF)

**Comment by duke7553** [comment]
Hey guys. Glad to see I'm not the only one hoping for a UWP-Style Window control in WinUI. In case anyone is curious, I previously filed [a report](https://github.com/microsoft/microsoft-ui-xaml/issues/1215) asking about this where I received a response. Unifying the windows across all WinUI apps would improve consistency and help with other projects such as Windows Terminal where what appears to be a custom window is in use. 

Really hoping to see work done in this area for either v3.0 or 3.1

**Comment by mdtauk** [comment]
It would be good to have some "proper" design resources, based around building core elements of an app, and showing how the Windows Shell of the future, and Inbox Apps which should be held up as exemplar for best practice - design and build those UI bits.

Common dialogs, Common navigation patterns, Common templates, etc.

There should be templates for adding common Content Dialogs, menus, flyouts - with code and behavioural guidance which can be copy and pasted into an app.

Anyway, back to the core of this issue.  I made a discussion issue #1323 precisely about top level elements coming to WinUI, including a Window element.  This seems like a WPF ask, rather than a WinUI ask, but WinUI for Desktop should have access to these things.

**Comment by jevansaks** [comment]
Do I understand that the original question is about bringing CoreApplicationView capabilities to WPF's Window? I think such a question/discussion should be asked in the https://github.com/dotnet/wpf repo. 

WinUI will be bringing its own top-level Window abstraction for the WinUI Desktop scenario and, where possible, it will do the things that you could do in UWP for drawing in the title bar. What the full API and feature set looks like is not yet determined.
