### ISSUE TITLE
Discussion: Prezi-like 3D/Immersive Navigation View

### ISSUE THREAD

**Issue by patware** [microsoft/microsoft-ui-xaml#1687]
# Discussion: Prezi-like 3D/Immersive Navigation View 

https://prezi.com/ blew my mind with a new way of doing presentations - in a 3D/Immersive manner.  Would such a 3D/immersive View Navigation make sense in a rich client world ?

## Related Links
[Prezi](https://prezi.com/)

**Comment by GeorgeS2019** [comment]
@patware 
The best chance for 3D WinUI control is to make [this 3D framework](https://github.com/vpenades/SharpGLTF/issues/30#issuecomment-559786926) to support WinUI control
