### ISSUE TITLE
Question: How do sticky groups stay at the top in listview

### ISSUE THREAD

**Issue by matthew4850** [microsoft/microsoft-ui-xaml#1691]
I know that the RenderTransform is set on ListViewHeaderItem so that it stays at the top but that means it appears on top of the ListViewItems. I know this is solved by setting the clip of the ItemsControl but why does this not clip ListViewHeaderItem?

**Comment by jevansaks** [comment]
If you're trying to implement sticky headers yourself, you might take a look at [this doc page](https://docs.microsoft.com/en-us/windows/uwp/composition/scroll-input-animations). To answer the question of how this works specifically in ListView, I think the best would be to wait until WinUI 3.0 is open source and then take a look at that code. :)

**Comment by matthew4850** [comment]
Yeah, hopefully this will be soon :)
