### ISSUE TITLE
NumberBox visuals seems broken on 1803

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1694]
**Describe the bug**

The visuals for NumberBox in 1803 are not looking like the proposal or the demo

**Steps to reproduce the bug**

1. Create a simple UWP project and add following 
```
    <StackPanel Width="200" Margin="12">
        <controls:NumberBox Header="Inline" SpinButtonPlacementMode="Inline"/>
        <controls:NumberBox Header="Compact" SpinButtonPlacementMode="Compact"/>
        <controls:NumberBox Header="Hidden" SpinButtonPlacementMode="Hidden"/>
    </StackPanel>
```
2. Run the app on 1803.

**Screenshots**

![image](https://user-images.githubusercontent.com/8557046/69770961-18392980-11df-11ea-8801-ec06df9236f5.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.191125001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Target version of UWP App 1903
Min Target version of UWP App 1709

**Comment by mdtauk** [comment]
Do you happen to have shadows turned off?

**Comment by harvinders** [comment]
1803 don't have shadows, I believe. 
Also note the non-rounded corners for `Inline` and `Compact`.  

Even selection highlight is different for `Compact`. It should be like 
![image](https://user-images.githubusercontent.com/8557046/69778371-29426480-11f8-11ea-81c3-33a6699af2e4.png)

**Comment by mdtauk** [comment]
So I am guessing the conditional XAML is not yet in place, or not working correctly.
@teaP @SavoySchuler

**Comment by stmoy** [comment]
I am seeing an issue where the inline SpinButtons don't line up with the top and bottom of the control: 
![image](https://user-images.githubusercontent.com/25991996/71036469-a0ba3400-20d2-11ea-9da0-8d7a8d9d8caf.png)

![image](https://user-images.githubusercontent.com/25991996/71036503-b4659a80-20d2-11ea-87a3-7e89654b8c7c.png)

Additionally, the widths of the middle border brush seem thicker than the textbox and right spin button. 

![image](https://user-images.githubusercontent.com/25991996/71036592-dd862b00-20d2-11ea-9f52-8a7366fb9af8.png)

The screenshot was taken on a 3840x2160 resolution monitor at 150% scale.

**Comment by ranjeshj** [comment]
@stmoy, the misalignment in high dpi is a dup of #1846 
@harvinders, with the latest bits this is what i see in 1803.
![image](https://user-images.githubusercontent.com/28935693/73608238-7c78c080-4575-11ea-94b4-f3f50b8eadd8.png)

The highlight being cutoff is because the increase/decrease buttons are in a popup overlayed on top of the textbox.
