### ISSUE TITLE
RadioButtons grows wider than its parent container

### ISSUE THREAD

**Issue by Kinnara** [microsoft/microsoft-ui-xaml#1695]
**Describe the bug**
```xaml
<Border
    Width="260"
    Background="{ThemeResource SystemControlPageBackgroundChromeLowBrush}">
    <muxc:RadioButtons MaxColumns="3">
        <x:Int32>1</x:Int32>
        <x:Int32>2</x:Int32>
        <x:Int32>3</x:Int32>
        <x:Int32>4</x:Int32>
        <x:Int32>5</x:Int32>
        <x:Int32>6</x:Int32>
        <x:Int32>7</x:Int32>
        <x:Int32>8</x:Int32>
        <x:Int32>9</x:Int32>
    </muxc:RadioButtons>
</Border>
```
![image](https://user-images.githubusercontent.com/1617766/69784405-ac5fbc80-11f0-11ea-9465-da53dd2854de.png)
As the image shows, RadioButtons shows 3 columns and gets clipped.

**Expected behavior**
RadioButtons shows 2 columns.

**Version Info**
NuGet package version: 
2.3.191127001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

**Comment by jevansaks** [comment]
Great bug, @Kinnara! We'll take a look.

**Comment by kikisaints** [comment]
Interesting! Thanks for logging @Kinnara - it looks like you're specifically setting the width to 260 in this case. That actually means the container is doing what a lot of our controls do when the width is set directly, which is to just clip. 

However, in the case of RadioButtons we have an option to simply rearrange the radiobuttons within the contrainer to be 2 columns (or 1) if there's not enough space to fit them all into your specified width.

My question for you is: would that behavior (auto-rearrangement) be something that you'd expect in this situation or in your scenario do you need `MaxColumns` to be honored 100% of the time/no matter what?

**Comment by jevansaks** [comment]
My feeling is that MaxColumns is a *maximum* but it's not a hard requirement. So I think we should have the available width win out in this case and have only 2 columns show up. This is what i talked to @StephenLPeters doing today and he agreed.

**Comment by kikisaints** [comment]
I also agree with that solution, it feels like the appropriate thing to do in this situation.

**Comment by Kinnara** [comment]
Auto-rearrangement is what I excepted. As @jevansaks said, `MaxColumns` is just a maximum.

**Comment by StephenLPeters** [comment]
Thanks all!
