### ISSUE TITLE
Discussion: WinUI - how will it bridge UWP and WPF?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#1697]
# Discussion: WinUI - how will it bridge UWP and WPF?

I know that on WinUI 3.0, we'll be able to use WinUI3.0 controls from both UWP and WPF apps.

My questions are:
1. How will this work, since as far as I know WPF is based on DirectX9 and UWP is based on DirectX11. Those are very huuge differences, and if you won't port WPF to DX11, how will this work?

2. We can load bitmaps in WPF pretty much any way we like (and on any thread, as long as you freeze them afterwards). You can only load bitmaps in the main thread in UWP, and you need to use the "awesome" StorageFile async API. Will WinUI3 handle both cases, or how will this work?

**Comment by robloo** [comment]
As I understand it, WPF can only use WinUI 3.0 with XAML Islands. You will have to host WinUI 3.0 controls inside a WPF window. This is just like you would host WPF in WinForms historically. How that works from a technical standpoint (DirectX versions) I have no idea. Disclaimer, this is now just guessing: You also probably won't be using WinUI 3.0 file dialogs for file pickers and things in WPF so there will be no use of the StorageFile API from WPF. That said, StorageFIle is part of WinRT so you could probably use it in the future.

For UWP, WinUI 3.0 becomes the latest and greatest 'presentation layer'. UWP then becomes pretty much just an app model. You will still have to use StorageFile, etc. as the UWP app model is still very locked-down.

Your overall questions seem very specific to working with bitmaps between WPF/UWP -- I can't help there though as I've never tried it. That said, it should be entirely possible to host a WinUI 3 image control using XAML Islands on WPF and pass it a bitmap image created from WPF API's. You would probably need to use a SoftwareBitmap created from a data stream -- not a file directly.

**Comment by jtorjo** [comment]
> ... You also probably won't be using WinUI 3.0 file dialogs for file pickers and things in WPF so there will be no use of the StorageFile API from WPF. That said, StorageFIle is part of WinRT so you could probably use it in the future.

I was quite curious, because I simply need win2d - as long as that internally uses the "great" StorageFile and the like, we're back at square one.

> 
> For UWP, WinUI 3.0 becomes the latest and greatest 'presentation layer'. UWP then becomes pretty much just an app model. You will still have to use StorageFile, etc. as the UWP app model is still very locked-down.

Yeah, that will, for lack of a better word, suck.
I'm not sure who came up with the great UWP app model, but that is beyond obsolete. 
 
> Your overall questions seem very specific to working with bitmaps between WPF/UWP -- I can't help there though as I've never tried it. That said, it should be entirely possible to host a WinUI 3 image control using XAML Islands on WPF and pass it a bitmap image created from WPF API's. You would probably need to use a SoftwareBitmap created from a data stream -- not a file directly.

That would actually be interesting to see. In other words, I'm dealing right now with SoftwareBitmap in UWP , and there's no such a class in WPF (not yet, at least)

**Comment by jesbis** [comment]
> I know that on WinUI 3.0, we'll be able to use WinUI3.0 controls from both UWP and WPF apps. How will this work, since as far as I know WPF is based on DirectX9 and UWP is based on DirectX11. Those are very huuge differences, and if you won't port WPF to DX11, how will this work?

@robloo is correct that this will require using Xaml Islands. There's more info on Xaml Islands in [this blog post](https://blogs.windows.com/windowsdeveloper/2019/06/13/xaml-islands-v1-updates-and-roadmap/). Currently Xaml Islands are only available for UWP Xaml but they will be included in WinUI 3 as well.

The separate DirectX device etc. is all handled for you by the Xaml Island infrastructure.

---

>  I'm dealing right now with SoftwareBitmap in UWP , and there's no such a class in WPF (not yet, at least)

You can use WinRT APIs today (including `SoftwareBitmap`) directly from a WPF by adding the [Microsoft.Windows.SDK.Contracts](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts) NuGet package. The docs here have more info: [Call UWP APIs in desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance).

---

> We can load bitmaps in WPF pretty much any way we like (and on any thread, as long as you freeze them afterwards). You can only load bitmaps in the main thread in UWP, and you need to use the "awesome" StorageFile async API. Will WinUI3 handle both cases, or how will this work?

For file handling in general, using the above interop you should be able to convert between .NET and WinRT file streams/APIs using existing extension methods in a WPF app, e.g. you should be able to create a WinRT SoftwareBitmap in a WPF app like this:

```csharp
using (var stream = File.Open("<file path>", FileMode.Open))
{                
    var iras = stream.AsRandomAccessStream();
    var decoder = await Windows.Graphics.Imaging.BitmapDecoder.CreateAsync(iras);
    var softwareBitmap = await decoder.GetSoftwareBitmapAsync(BitmapPixelFormat.Bgra8, BitmapAlphaMode.Premultiplied);
} 
```
If you use a `SoftwareBitmap` then you can also do interesting stuff like back it with a custom lockable `IWICBitmap` that enables native in-memory modification and processing, although that can get complex and definitely isn't required for most cases.

With a UWP (or WinUI) [BitmapImage](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Media.Imaging.BitmapImage) in particular, image loading is automatically optimized and handled on a background thread. That prevents blocking the UI thread and leads to better UI responsiveness without needing to explicitly manage multithreading.

Does that help answer your questions?

**Comment by jtorjo** [comment]
@jesbis Thanks for answering!

> The separate DirectX device etc. is all handled for you by the Xaml Island infrastructure.

Got it, was curious about it, since I ported my app to UWP - and it's been a huuuge pain. Having said that, I was interested if I could be using WPF in the future (with win2d from Xaml Islands), because clearly that's what I'd prefer.

However, kwnowing it's UWP under the hood, I'll probably stick to UWP.

> You can use WinRT APIs today (including `SoftwareBitmap`) directly from a WPF by adding the [Microsoft.Windows.SDK.Contracts] ...

Got it.

> For file handling in general, using the above interop you should be able to convert between .NET and WinRT file streams/APIs using existing extension methods in a WPF app, e.g. you should be able to create a WinRT SoftwareBitmap in a WPF app like this:
> 
> ```cs
> using (var stream = File.Open("<file path>", FileMode.Open))
> {                
>     var iras = stream.AsRandomAccessStream();
>     var decoder = await Windows.Graphics.Imaging.BitmapDecoder.CreateAsync(iras);
>     var softwareBitmap = await decoder.GetSoftwareBitmapAsync(BitmapPixelFormat.Bgra8, BitmapAlphaMode.Premultiplied);
> } 
> ```

Indeed, turns out I was wrong about loading bitmaps only on the UI thread on UWP - I was not aware of the above, but I'm really happy I was pointed this out. Long story short, I need to load a LOT of bitmaps really fast, and the above is the way to go.

> 
> If you use a `SoftwareBitmap` then you can also do interesting stuff like back it with a custom lockable `IWICBitmap` that enables native in-memory modification and processing, although that can get complex and definitely isn't required for most cases.

Cool! Right now I use SoftwareBitmap to turn it into a CanvasBitmap, since it's pretty much the only way to get a CanvasBitmap synchronously.

> Does that help answer your questions?

Yes it does, thanks!
