### ISSUE TITLE
MediaTransportControls show non-localized tooltips without a way to override them

### ISSUE THREAD

**Issue by lukasf** [microsoft/microsoft-ui-xaml#1698]
**Describe the bug**
The MediaTransportControls contain tooltips for all of the buttons inside the control. However, these tooltips are not localized. So even if my OS and app language is German, I still see English tooltips. 

The tooltips are not set in the control template, they are somehow set by the control itself in a hidden, non-overridable way. Some buttons change their tooltip as state changes (e.g. Play/Pause button, fullscreen button), so it is also not possible to override the tooltips reliably e.g. on OnTemplateApplyed.

The only way to localize a MediaTransportControl is to completely throw away all its content and roll out custom buttons for all functionality. That's pretty bad. Either, the control should come with proper localization for all supported Windows OS languages, or there should be a way to assign localized tooltips.

**Steps to reproduce the bug**
1. Set your UI language to anything other than English
2. Add a MediaPlayerElement to a blank app's MainPage.xaml
3. Run the app, hover the buttons, watch English tooltips

**Expected behavior**
All tooltips are localized. Or there is an API to localize all tooltips manually.

**Screenshots**
![MTC_Tooltips](https://user-images.githubusercontent.com/2306201/69832406-590c5f00-122e-11ea-928a-9b10352eede4.jpg)

**Version Info**
Windows 10 1903, SDK: 10.0.18362.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

**Comment by jevansaks** [comment]
@lukasf can you share a repro app? Are you doing the thing where you set your app's language to the current system language?

https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/manage-language-and-region

**Comment by lukasf** [comment]
I am sorry, this was my fault. As soon as I added other localized resources, the tooltips also came up localized. So it seems that we need to have at least one localized resource for a language, then the tooltips will also come up in that language.

**Comment by jevansaks** [comment]
> So it seems that we need to have at least one localized resource for a language, then the tooltips will also come up in that language.

I'm not super familiar with this, but I could believe that the auto-language choosing logic relies on you having those resources available. You can also force it by setting [PrimaryLanguageOverride](https://docs.microsoft.com/en-us/uwp/api/Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride), per those docs:

_The app can set it to override the top language of the user's ranked list of preferred languages (ApplicationLanguages.Languages ), and its value will persist between app sessions. It must be a single language tag; a delimited list of language tags will fail._

**Comment by lukasf** [comment]
Yes that makes sense. Thank you.
