### ISSUE TITLE
NavigationView is opening the left pane when leaving LeftMinimal display mode

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#1702]
**Describe the bug**
When changing the `NavigationView` display mode from `LeftMinimal` to `LeftCompact` the pane is opened.

**Steps to reproduce the bug**
1. Add a `NavigationView` in an app.
2. Set its display mode to `LeftMinimal`
3. On some condition, change the display mode to `LeftCompact`
4. The left pane is opening

**Expected behavior**
The left pane remains closed

**Screenshots**

**Version Info**
NuGet package version: 2.2.190917002

**Additional context**
The actual behavior is hardcoded in ` NavigationView::UpdatePaneDisplayMode(winrt::NavigationViewPaneDisplayMode oldDisplayMode, winrt::NavigationViewPaneDisplayMode newDisplayMode)`

    // For better user experience, We help customer to Open/Close Pane automatically when we switch between LeftMinimal <-> other PaneDisplayMode.
    // From other navigation PaneDisplayMode to LeftMinimal, we expect pane is closed.
    // From LeftMinimal to other left PaneDisplayMode other than Auto, we expect Pane is opened.
    if (!IsTopNavigationView())
    {
        bool isPaneOpen = IsPaneOpen();
        if (newDisplayMode == winrt::NavigationViewPaneDisplayMode::LeftMinimal && isPaneOpen)
        {            
            ClosePane();
        }
        else if (oldDisplayMode == winrt::NavigationViewPaneDisplayMode::LeftMinimal &&
            !isPaneOpen &&
            newDisplayMode != winrt::NavigationViewPaneDisplayMode::Auto)
        {
            OpenPane();
        }
    }

Having the pane opening on each transition from minimal to compact is very annoying because it requires us to close the pane to continue using the application. 
A resize of the window (the most probable cause of display mode change) should not interfere with what the user is doing.
This pane opening should at least be something that the application developer can decide based on what he wants for his application.

I'm actually using the following code to revert the control behavior
```csharp
private void OnNavigationViewPropertyChanged(DependencyObject sender, DependencyProperty dp)
 {
    if (dp == Mux.NavigationView.PaneDisplayModeProperty && navigationView.PaneDisplayMode == Mux.NavigationViewPaneDisplayMode.LeftCompact)
    {
        navigationView.IsPaneOpen = false;
    }
}
```

**Comment by chingucoding** [comment]
I would like to fix this 😊

**Comment by chingucoding** [comment]
Using the latest build on master, I can't seem to reproduce the issue. When switching between LeftMinimal and LeftCompact, the pane closes automatically:

![navview-displaymodeswitch](https://user-images.githubusercontent.com/16122379/71129279-62fefd80-21ef-11ea-8206-9ff40678328e.gif)


@vgromfeld Can you try updating your version of WinUI and check if the issue still persists after updating?
