### ISSUE TITLE
NumberBox should correctly handle mousewheel events 

### ISSUE THREAD

**Issue by jesbis** [microsoft/microsoft-ui-xaml#1705]
**Describe the bug**
When you spin a NumberBox using the MouseWheel, it doesn't set IsHandled on the event and it bubbles up to any parent ScrollViewer, resulting in the NumberBox value changing AND the parent form scrolling.

This makes the scrollwheel behavior unpredictable and can cause unintentional input or loss of user input in a scrolling form with one or more NumberBoxes.

**Steps to reproduce the bug**

1. Add a NumberBox to a ScrollViewer
2. Attempt to mousewheel over the NumberBox

**Expected behavior**
NumberBox should either not support mousewheel or should handle the event to prevent it bubbling.

**Screenshots**
![numberboxscroll](https://user-images.githubusercontent.com/16565497/69991258-38792900-14fc-11ea-85df-da9d2670d18b.gif)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.3.191129002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment]
I think it would be better to handle the event instead of disabling the mouse wheel support. In most cases having the mouse wheel support would be the better behavior. If the user can't scroll because the NumberBox is getting the scroll, I don't think this would be a large impact, especially since there are different ways to scroll for the user.

If it is okay, I would like to fix this @jevansaks 😅

**Comment by jevansaks** [comment]
Sure @chingucoding! You got it.
