### ISSUE TITLE
CommandBar height not correct when text scaling > 100%

### ISSUE THREAD

**Issue by TANG-Kai** [microsoft/microsoft-ui-xaml#1715]
**Describe the bug**
When system text scaling is set to be > 100% the CommandBar's height does not grow as the AppBarButtons inside it do.

**Steps to reproduce the bug**
1. Settings > Display > Make text bigger > set to be 100%.
2. Open the XAML Controls Gallery > Menus and Toolbars > CommandBar.
3. Settings > Display > Make text bigger > set to be greater than 100%.
3. Observe

**Expected behavior**
CommandBar should grow its height as the AppBarButton inside it.

**ScreenShots**
![image](https://user-images.githubusercontent.com/5684480/70145635-dc9bd500-16a0-11ea-8142-00da4062b4ef.png)

**Version Info**
XAML Controls Gallery v.1.2.11.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19033)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by Felix-Dev** [comment]
Seems to me this issue is covered by https://github.com/microsoft/microsoft-ui-xaml/issues/1454.
