### ISSUE TITLE
Add an AppBarDropDownButton

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#172]
# Proposal: Add an AppBarDropDownButton

## Summary

There is currently a DropDownButton control, but no corresponding control to place into a commandbar.

## Rationale

Adding dropdown menus in a commandbar currently requires adding a (maybe retemplated) AppBarButton with an associated menuflyout. Unfortunately, even if the placement property of the Flyout is set, there is still a gap between both elements:

![image](https://user-images.githubusercontent.com/38145893/51056011-ec6e7e80-15e1-11e9-932e-f9aaadc1de33.png)

In comparison, the commandbar menu for secondary controls does not show this issue:

![image](https://user-images.githubusercontent.com/38145893/51055940-b92bef80-15e1-11e9-9b0c-f5559e202c7f.png)

While it is possible to add workarounds to the application (e.g. manipulate the margins of the flyout), this should be handled automatically. As can be seen, the style of both flyout is also different (at least on the current windows insider build)

**Comment by mdtauk** [comment]
A future UWP ribbon may have need for this, as well as versions of other controls when placed into a ribbon/tool bar.  Thinner strokes on text and combobox fields for instance.

**Comment by mdtauk** [comment]
The idea of localised styles which override controls when they are placed into a panel, is very interesting.  It would have to apply to the control without giving it a **Style** value.  

An initial thought of adding a ResourceDictionary to the Panel.Resources of the Ribbon Control maybe.

Or perhaps taking the generic.xaml dictionary included in Microsoft.UI.Xaml package, adding in Styles and Templates for RibbonButton, RibbonComboBox, Ribbon SplitButton - and somehow translating the control's default template for these ones when placed in the Ribbon Control.
But that would probably need some platform changes to how XAML handles it's themeing/templates and styles.

**Comment by lhak** [comment]
Ok, for mow I will keep using a retemplated version of the MenuFlyoutPresenter to compensate for this gap. Is there any way to disable the shadow to keep a consistent look with the commandbar overflow menu?

**Comment by YuliKl** [comment]
@jesbis and @chigy, can you comment on how to disable shadow in MenuFlyout?

@lhak - thank you for this feature proposal. Sounds like you have a reasonable workaround for your scenario. Between your current approach and the option to use `AppBarElementContainer` to place a `DropDownButton` into a `CommandBar`, I don't think it makes sense for us to add a new AppBarDropDownButton class.

**Comment by mdtauk** [comment]
Just a little thought about applying default styles to controls based on their container/parent...

`
TargetType="AppBar/DropDownButton"
`

Treating the TargetType and Style values more like a path to help make things more conditional?

**Comment by kurema** [comment]
So there's also no chance for AppBarRepeatButton...
I want RepeatButton in CommandBar, but OK. There's workaround.
