### ISSUE TITLE
NumberBox properties are not in the Common category but in Miscellaneous

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#1720]
**Describe the bug**

The properties like Value, SpinButtonPlacementMode, Minimum, Maximum are not in the Common category of the Properties window. They are in Miscellaneous. This makes it hard to discover.

**Steps to reproduce the bug**

1. Select a NumberBox in the XAML Designer.
2. View the Properties window.

**Expected behavior**
NumberBox properties in the Common category and not in Miscellaneous

**Screenshots**

![image](https://user-images.githubusercontent.com/9335559/70220030-2c80a780-1746-11ea-9193-879a99223142.png)

The important properties of a TextBox are in the Common category
![image](https://user-images.githubusercontent.com/9335559/70220064-3dc9b400-1746-11ea-92b8-bc31c2502ef8.png)

NuGet package version: 
Microsoft.UI.Xaml 2.3.191129002

**Comment by jevansaks** [comment]
Here's the documentation for doing VS design light-up via nuget: https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls. It's pretty thin and I don't see anything about how to customize the properties pane.

@karann-msft @chabiss @svetbonev Is this something that's possible to customize with nuget today?

**Comment by sonnemaf** [comment]
@jevansaks I never expected that this would be difficult.

In C#/UWP I would only have to add the System.ComponentModel.Category attribute on the Dependecy Property. I expected a simular solution in C++.

```
[System.ComponentModel.Category("Common")]
public double Value {
    get => (double)GetValue(ValueProperty);
    set => SetValue(ValueProperty, value);
}

public static readonly DependencyProperty ValueProperty = DependencyProperty.Register(nameof(Value), typeof(double), typeof(NumberBox), new PropertyMetadata(default));
```

**Comment by jevansaks** [comment]
The thing I don't know is if those attributes are available in the IDL world for us to use. Someone just needs to sit down and investigate. I see that there's a RegisterMetadata.cs in our Design.dll -- that could be the connection we use to provide those attributes for the designer at runtime.

**Comment by ranjeshj** [comment]
@jevansaks perhaps something like [this](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/dd472146(v=vs.100)) ?
