### ISSUE TITLE
Proposal: Add TextAlignment property to NumberBox

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#1722]
# Proposal: Add TextAlignment property to NumberBox

## Summary
It would be nice if NumberBox also had a TextAlignment property. 

In this screenshot the NumberBoxes have Right TextAlignment 
![image](https://user-images.githubusercontent.com/9335559/70228718-1cbc8f80-1755-11ea-8348-6274242f3806.png)

## Rationale

* Make it consistent with TextBox and Excel
* Creating a Template for the NumberBox with only this extra property is a lot of work. Do-able but not nice.

```
<TextBox x:Name="InputBox"
                                     Grid.Column="0"
                                     TextAlignment="Right"
                                     Header="{TemplateBinding Header}"
                                     HeaderTemplate="{TemplateBinding HeaderTemplate}"
                                     PreventKeyboardDisplayOnProgrammaticFocus="{TemplateBinding PreventKeyboardDisplayOnProgrammaticFocus}"
                                     PlaceholderText="{TemplateBinding PlaceholderText}"
                                     SelectionHighlightColor="{TemplateBinding SelectionHighlightColor}"
                                     TextReadingOrder="{TemplateBinding TextReadingOrder}" />
```

**Comment by SavoySchuler** [comment]
Linked in: https://github.com/microsoft/microsoft-ui-xaml/issues/1736

**Comment by Felix-Dev** [comment]
@SavoySchuler Is this something the community can address while the team is busy working on WinUI 3?

**Comment by SavoySchuler** [comment]
Sorry for the late reply @Felix-Dev, it appears @sonnemaf and @StephenLPeters have already merged the PR.

**Comment by bogdan-patraucean** [comment]
I'm using WindowsAppSDK and I can't find the TextAlignment property on my WinUI 3 NumberBox control. Any idea why is this not available?
