### ISSUE TITLE
When in high contrast mode and navigating with the keyboard the focused tab is barely visible

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1727]
**Describe the bug**

In High Contrast mode, the keyboard-focused NavigationView item is barely discernible from non-focused NavigationView items.

**Steps to reproduce the bug**

1. Turn on HC
2. Open Xaml Controls Gallery, press Tab to move keyboard focus
3. Use arrow keys to continue moving focus within the list of items

**Expected behavior**

It's easy to see which item has keyboard focus.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/70285631-05919800-177d-11ea-994e-a908cfe4e409.png)
(focus is currently on "Collections")

**Proposed fix**
Remove the borders around NavigationViewItems. They don't seem necessary (MenuFlyoutItems don't draw borders in HC) and detract rather than improve the user experience.

**Additional context**

Copied from an [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/23103747)

**Comment by jevansaks** [comment]
Agree with @yulikl's proposed fix.

**Comment by chingucoding** [comment]
I would be happy to fix this :)
