### ISSUE TITLE
'Radio Button' Style Menu Items

### ISSUE THREAD

**Issue by adambarlow** [Microsoft/microsoft-ui-xaml#173]
# [The WinUI Team has started the Spec for this feature](https://github.com/Microsoft/microsoft-ui-xaml-specs/pull/19)

# Proposal: 'Radio Button' Style Menu Items

## Summary

Many applications, including visual studio, allow for the addition of checkboxes in the menu options of their MenuBars. These have been an important part of applications which use MenuBar for a very long time. The XAML MenuBar currently supports checkboxes.

However, another lesser used pattern is radio-button style menu options. This patter presents options that automatically swap selection within their group of items. While this patter is used less frequently, it does find precedent in various UIs and is a customer request.

Below is an example of this usage from the Win10 desktop context menu--
![image](https://user-images.githubusercontent.com/16247808/51059899-a219dd00-15a2-11e9-8994-1001725185a1.png)

## Rationale

Implementing this request will:
* Allow for radio-button style options in XAML MenuBars without having to custom implement the logic (e.g. for 'view' menus, etc.)
* Provide a consistent look and feel for this scenario (if we don't support this it will be implemented in various ways and will not be consistent)

## Functional Requirements

| # | Feature |  Priority |
| -- | -- | -- |
| 1 |  API is straightforward and simple | Must
| 2 | API doesn’t require styling, e.g. the 'dot' comes for free | Must
| 3 | API allows for the styling of the glyph used for the 'dot' | Should

## Detailed Feature Design

We plan to create a RadioMenuFlyoutItem in WinUI that derives from ToggleMenuFlyoutItem
It would have the following additional APIs:
   * String GroupName
     * All RadioMenuFlyoutItems within a MenuFlyout with the same GroupName will be grouped together
     * Note: This works the same as in RadioButton today

## Open Questions

* What should the visual distinction around the groups look like, if any?

### Prerelease readiness
- [x] Dev: quality review + code review done
- [x] Dev: test coverage added
- [x] Dev: initial accessibility review done
- [x] Dev: data metrics plan ready
- [x] PM: spec up to date
- [x] PM: feature ready for feedback
- [x] PM: docs.microsoft.com updates ready
### Stable release readiness
- [x] Dev: feature previously shipped in a prerelease NuGet package
- [x] Dev: Azure CI tests passing
- [x] Dev: data metrics ready
- [x] Dev: accessibility review done
- [x] Dev: API review done
- [x] Dev: IDL attribute switched from preview to public
- [x] PM: spec done
- [x] PM: glob/loc, privacy, security, license compliance ready
- [x] PM: customer validation done
- [x] PM: docs.microsoft.com updated
- [x] PM: Xaml Controls Gallery updated

**Comment by mdtauk** [comment]
Perhaps a hollow circle/ring for unselected items, and a filled one for selected.

**Comment by adambarlow** [comment]
@mdtauk, thanks for the suggestion, we will add that as a suggestion as design takes a look at this.

**Comment by michael-hawker** [comment]
@mdtauk I think the key of how this works in existing patterns is that they're always grouped together in a section of the menu, so the user sees this is clearly a group by that construction.

If these items can be placed anywhere though with the same name, a developer isn't bound by that design constraint though and this could lead to messy UX by a developer.  I'd almost like to see a `RadioMenuFlyoutGroup` collection item which is added to a menu and contains the set of items to be grouped.  This would force construction to behave like existing system implementations and provide a consistent UX where it's not possible to have radio menu items placed across a menu, e.g.

( We Don't Want This )
-- Radio Option 1
-- Some Checked Item
-- Radio Option 2

**Comment by mdtauk** [comment]
Of course, they would need to be grouped.  I would agree it needs to be done in a way where RadioMenuItems have to be placed within a RadioMenuGroup.

![image](https://user-images.githubusercontent.com/7389110/51131829-aeaf6700-1828-11e9-8627-e07d6ff63e27.png)
