### ISSUE TITLE
Discussion: [WinUI 3 App Design Ideas]

### ISSUE THREAD

**Issue by shaheedmalik** [microsoft/microsoft-ui-xaml#1732]
# Discussion: [Win UI 3 App Designs - Concepts] 

I came across these designs on twitter. They are concepts of how Windows Phone would look if it was still being worked on. These are some great designs for how UWP could look in WinUI 3 on Windows 10X & Windows 10. Tablet Mode would also benefit from apps designed like this.

This is the type of consistency I am looking for.
I would love for the XAML controls to make this a reality with WinUI 3.

![image](https://user-images.githubusercontent.com/51347950/70332903-7cc43c00-1810-11ea-8dcf-546513452ae3.png)

![image](https://user-images.githubusercontent.com/51347950/70332936-88affe00-1810-11ea-8bbf-4534833a05a1.png)

![image](https://user-images.githubusercontent.com/51347950/70332952-8e0d4880-1810-11ea-8003-97401204dd58.png)

![image](https://user-images.githubusercontent.com/51347950/70332571-e8f27000-180f-11ea-8a8a-ac96e792c330.png)

![image](https://user-images.githubusercontent.com/51347950/70332512-b9436800-180f-11ea-91e1-0a1ba9ba4ff3.png)

## Related Links

https://twitter.com/zeealeid/status/1202627055164313602?s=19

**Comment by mdtauk** [comment]
I do think a less "free" approach when recommending and inbox UIs would do a lot for bringing a greater sense of consistency and coherence - which could encourage other apps to do the same.

Microsoft should put forward an "opinion" on how app UIs should look on Windows, and "sell" that opinion.

**Comment by duke7553** [comment]
Microsoft should also make it very clear to third-party developers what the utility of a second screen is on the new dual-screen form factor.

Complimented by appropriate documentation, I expect there to be controls optimized for these devices. For instance, the SplitView should include a `FormFactor` property which adjusts the control's resizing behavior to work on them.

**Comment by shaheedmalik** [comment]
> I do think a less "free" approach when recommending and inbox UIs would do a lot for bringing a greater sense of consistency and coherence - which could encourage other apps to do the same.
> 
> Microsoft should put forward an "opinion" on how app UIs should look on Windows, and "sell" that opinion.

I agree with this. Just as important that we have feature complete finished templates that are so good that the developer don't feel the need to change them.

**Comment by shaheedmalik** [comment]
@zeealeid check this out.
