### ISSUE TITLE
WebView gets stuck on blank http error responses

### ISSUE THREAD

**Issue by nirbil** [microsoft/microsoft-ui-xaml#1741]
Loading the Windows.UI.Xaml.Controls.WebView with certain URLs results in a stuck navigation, where the NavigationStarting event is called but the NavigationCompleted is never called.

To reproduce it, you can use this site - https://www.mocky.io/ to produce a URL that returns an Http error response with a blank body.
Here's a sample 'Internal Server Error' response - http://www.mocky.io/v2/5debd1402f00006d0007e32c

Notice that if the body is not left blank then the NavigationCompleted event gets called.

**Comment by Austin-Lamb** [comment]
We aren't planning on investing more into WebView at this time, as we're focusing on WebView2 based on the Chromium-powered Edge.

**Comment by nirbil** [comment]
yea I figured, though for the foreseeable future there won't be UWP support in WebView2

**Comment by krschau** [comment]
I just tried this out with WebView2 in WinUI 3 and there it looks like we do get a NavigationCompleted event even with an empty body error response. Thanks for linking that mock.io site, that's nifty! I'm going to close this, but please do create a new item if you see this not working correctly in WebView2, I didn't test exhaustively.
