### ISSUE TITLE
NavigationViewItem template should respect CompactPaneLength

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#1742]
**Describe the bug**
The `NavigationViewItem` are partially hidden by the `MenuItemsHost`'s scrollbar when `NavigationView.PaneDisplayMode="LeftCompact".

**Steps to reproduce the bug**
1. Create a new app with a `NavigationView` containing a lot of `NavigationViewItems` 
```xml
<mux:NavigationView PaneDisplayMode="LeftCompact">
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem Content="Item 1">
            <mux:NavigationViewItem.Icon>
                <SymbolIcon Symbol="Add" />
            </mux:NavigationViewItem.Icon>
        </mux:NavigationViewItem>
[…]
        <mux:NavigationViewItem Content="Item 9">
            <mux:NavigationViewItem.Icon>
                <SymbolIcon Symbol="UnPin" />
            </mux:NavigationViewItem.Icon>
        </mux:NavigationViewItem>
    </mux:NavigationView.MenuItems>
</mux:NavigationView>
```
2. Run the application
3. Resize the window to force the `MenuItemsHost` to show its scrollbar

**Expected behavior**
The scrollbar is displayed on the edge and **not** covering the icons.

**Screenshots**
*Actual bevavior*
![image](https://user-images.githubusercontent.com/20152272/70443677-d8a0f600-1a98-11ea-9763-6a6054689794.png)
![image](https://user-images.githubusercontent.com/20152272/70443723-ebb3c600-1a98-11ea-9f07-07ead42d04c0.png)

Notice that the icons are **half hidden** making it hard to determine what is each entry.

*Expected bevahior*
The screenshots come from Groove Music. Notice that the scrollbar is **not** hiding the icons:
![image](https://user-images.githubusercontent.com/20152272/70443817-20278200-1a99-11ea-9f43-e21ba84b8ac9.png)
![image](https://user-images.githubusercontent.com/20152272/70443834-29185380-1a99-11ea-9f96-03798b570cff.png)

**Additional context**
`NavigationView` has a `CompactPaneLength` property that seems to be useful to get what we need but it doesn't give the expected result at all:
![image](https://user-images.githubusercontent.com/20152272/70443905-5238e400-1a99-11ea-8f20-478685d18c41.png)
The label of the `NavigationViewItem` are shown and the hamburger and back icons are no longer centered.

Comparing the sample app and Groove, we can see that Groove is using a **wider compact bar** to have enough room for the scrollbar.
![image](https://user-images.githubusercontent.com/20152272/70444020-83191900-1a99-11ea-95c9-dd9a1c29efda.png)

It would be great to have the same behavior in `NavigationView` to let the users properly see all the navigation icons when in compact mode;

[NavViewScrollBar.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3940200/NavViewScrollBar.zip)

**Proposed fix**
[Edited by @YuliKl ]
Update NavigationViewItem template to respect CompactPaneLength as the width of its first column. Also recenter the back and hamburger buttons when NavigationView is not in Top mode.

**Comment by ranjeshj** [comment]
Scrollbar by default overlays on top of the content. In this case it might make sense to add some extra spacing. @chigy @ojhad  Thoughts ?

**Comment by chigy** [comment]
> Scrollbar by default overlays on top of the content. In this case it might make sense to add some extra spacing. @chigy @ojhad Thoughts ?

@ranjesh, I'd need to check with the design team and this is just my personal feedback. But it feels the most natural and the way it won't impact the rest state design would be to draw the scrollbar outside (to the right of the navbar). Assuming this would be technically challenging?

**Comment by jevansaks** [comment]
We're hesitant to change the design here. This is the behavior of scrollviewer and the scrollbar overlapping content in this case is the intended design.

I think there's an argument for the scenario where the system setting is turned on to "never hide scrollbars" where the scrollbar would overlap all the time. But the only really good option we have is for the compact NavigationView mode to be bigger. And then we're taking away space from the app in a scenario they probably have never tested and don't even know to test.

CompactPaneLength would probably work but you'd need to retemplate the NavigationViewItems to handle the width change correctly.

We could re-purpose this item to track the issue where CompactPaneLength isn't applying to the layout of the NavigationViewItems by default if you want?

**Comment by chigy** [comment]
@jevansaks , I do not consider making the compact NavigationView mode to being bigger a good option, so looks like we don't have a good option. The compact mode is supposed to help user quickly identify the option and click from the set of icons.  I would hope that there are not so many options there that user has to scroll and scrolling design would be less frequent than non-scrolling design. So I cannot sacrifice the design for less likely option in my opinion.

**Comment by vgromfeld** [comment]
@jevansaks, we can re-purpose the bug to more specifically address the `CompactPaneLength` not being properly applied. We'd like to have a simple and cheap solution to not have the overlap (ie avoid a full re-template).

Regarding the scrollbar behavior, in most apps, we are adding a small margin/padding on the content to leave an empty space for the expanded scroll bar. We never want the content to be hidden by the scrollbar. 

Looking at other Windows apps (Mail, Weather, News ...), they seems to all use a minimum window height which prevents the need for a scrollbar. It is doable for them because they only have a limited number of items.

**Comment by YuliKl** [comment]
NavigationViewItem already has a read-only CompactPaneLength property that gets used for drawing correct hover and focus visuals. The control template should further utilize this value to change the width of the first column (the column containing the icon).

This change in behavior poses a few questions about how to handle the alignment of the items' icons and of the hamburger and back buttons. Today, all these icons are horizontally centered within the pane sliver's width (the width represented by CompactPaneLength). To keep the integrity of the design, I suggest all icons (NavigationViewItem including Settings, Back button, hamburger button) should continue to horizontally center themselves.

**Comment by chigy** [comment]
> NavigationViewItem already has a read-only CompactPaneLength property that gets used for drawing correct hover and focus visuals. The control template should further utilize this value to change the width of the first column (the column containing the icon).
> 
> This change in behavior poses a few questions about how to handle the alignment of the items' icons and of the hamburger and back buttons. Today, all these icons are horizontally centered within the pane sliver's width (the width represented by CompactPaneLength). To keep the integrity of the design, I suggest all icons (NavigationViewItem including Settings, Back button, hamburger button) should continue to horizontally center themselves.

@YuliKl , are you suggesting that the icons be centered in now a little wider pane? I think it is problematic because that would shift the icons off from the side of the app as well as you would need to make it even wider because the scrollbar will still cover the portion of the UI?

**Comment by YuliKl** [comment]
> @YuliKl , are you suggesting that the icons be centered in now a little wider pane? I think it is problematic because that would shift the icons off from the side of the app as well as you would need to make it even wider because the scrollbar will still cover the portion of the UI?

I am suggesting this, yes. This is the Groove Music behavior that @vgromfeld noted. The decision to widen the sliver will be entirely up to the app, we won't change the control's default 40px width.

I believe today the icons are centered inside inside the template's first column. Keeping them centered within a 40px strip while allowing the column's width to be changed feels unnecessarily complex.

**Comment by shaheedmalik** [comment]
Groove Music is how the Compact View was originally. Groove Music was never updated to the newer NavigationView that Your Phone uses for example.
