### ISSUE TITLE
Question: Windows app certification kit says: Unable to install Microsoft.UI.Xaml.<version_number> ...

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/microsoft-ui-xaml#1747]
After successfully creating app package of my app, when the App Certification was started,
this error window pops-up:
![image](https://user-images.githubusercontent.com/21083609/70616879-a5499d00-1c39-11ea-8796-c0dedb939fdf.png)

I even don't know what does it mean !! 
The issue is happening with the new WinUI (2.3.2), it didn't happen with the previous one.

**Comment by licanhua** [comment]
I didn't reproduce it on a simple C# app. Can you provide a step by step procedure?
It's better to provide more information like what's your running OS, what's the version of VS, Is it a C# app, what's the target version and min version of your App

**Comment by jevansaks** [comment]
Can you share out the AppxManifest.xml from the app? Or specifically take a look at the `<PackageDependency.../>` and see if there are multiple entries for Microsoft.UI.Xaml. It shouldn't happen but maybe the packaging process got confused.

Oh also can you share the version of Visual Studio you're using? FWIW we're all using VS2019 here and in our pipelines.

**Comment by MuziburRahman** [comment]
There is no such tag as `<PackageDependency.../>` in AppxManifest.xml.
This is the closest thing I got, in .csproj :
```
<ItemGroup> 
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.2.9</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Toolkit.Uwp.UI.Controls">
      <Version>6.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.UI.Xaml">
      <Version>2.3.191129002</Version>
    </PackageReference>
    <PackageReference Include="Win2D.uwp">
      <Version>1.24.0</Version>
    </PackageReference>
  </ItemGroup>
```

Visual Studio2019 version : 16.4

**Comment by ranjeshj** [comment]
Would it be possible for you to share a project where you can repro this ?

**Comment by michael-hawker** [comment]
There was a bug with a previous version of the kit. It shouldn't block the store, assuming it's the same one.

**Comment by MuziburRahman** [comment]
Yes, the app is now in the store, no problem for that.
But how do I update the certification kit?

**Comment by michael-hawker** [comment]
@MuziburRahman I think according to linked issue #1780, updating VS should fix it?

**Comment by ThE-TiGeR** [comment]
I have exactly the same problem. I allready cleaned my project and did a full rebuild.
I am using VS2019 16.4.2, Windows App Certification Kit 10.0.0.18362.1
Was there a solution found for this?

![image](https://user-images.githubusercontent.com/4369528/72107250-3ee79580-3331-11ea-97d1-7c070aad5110.png)
