### ISSUE TITLE
TreeView anomalies

### ISSUE THREAD

**Issue by EddieLotter** [microsoft/microsoft-ui-xaml#1756]
**Describe the bug**
I have encountered a problem when selecting a TreeView item programmatically and occasionally another problem where the user's selection is ignored.

**Steps to reproduce the bug**
For convenience, I have created [this project](https://github.com/EddieLotter/TreeViewAnomalies) that demonstrates the two problems.

**Expected behavior**
1. When a TreeView item is selected programmatically, it should either scroll into view automatically or there should be a method to allow the developer to choose when to scroll an item into view.
2. When a user selects a TreeView item in single-select mode, the SelectedNode property must consistently report the user's selection.

**Actual behavior**
1. Currently, the first time a TreeView item is programmatically selected, the selected item is automatically scrolled into view. Subsequent programmatic selections do not behave the same way.
2. When a TreeView item is selected programmatically, the SelectedNode property occasionally does not report a different TreeView item selected by the user in the UI.

**Screenshots**
Please see the [demo project's README](https://github.com/EddieLotter/TreeViewAnomalies/blob/master/README.md) for animated screen shots.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml v2.3.191129002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
For (1) can you call BringIntoView (https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.startbringintoview) on the element ?

**Comment by EddieLotter** [comment]
@ranjeshj thanks for the comment. I did try to use that method in my original project, but I could not get from a TreeViewNode to a UIElement. I tried ContainerFromNode and ItemFromContainer but I never got it to work.
If you can fork my example project and demonstrate how to do that, it would be exactly what is needed for (1).
Thanks again.

**Comment by ranjeshj** [comment]
Is the TreeViewItem associated with the TreeViewNode realized ? In other words, the parent chain to that TreeViewItem expanded ? If the TreeViewItem is not realized, I think that would prevent that api from getting the item.

**Comment by EddieLotter** [comment]
Yes, I explicitly expand the parent chain to ensure the node is realized.

**Comment by ptorr-msft** [comment]
I have the same problem -- I cannot get a container for a node if it's not already visible... at which point, `BringIntoView` is meaningless because it's already in view. For example, past this into a default C# project and run it...

```c#
public MainPage()
{
    this.InitializeComponent();

    var tree = new TreeView { Width = 300, Height = 300 };

    for (int i = 0; i < 20; ++i)
    {
        tree.RootNodes.Add(new TreeViewNode { Content = "Item " + i });
    }

    (Content as Grid).Children.Add(tree);

    tree.Loaded += (x, y) =>
    {
        // Passing 10 (or higher) will return null. Only visible items can be made visible :(
        var item = tree.ContainerFromNode(tree.RootNodes[5]) as TreeViewItem;
        item.IsSelected = true;
        item.StartBringIntoView();
    };
}
```
