### ISSUE TITLE
Proposal: Allow to target a specific point in Teaching Tip

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/microsoft-ui-xaml#1757]
`TeachingTip` currently allows only `FrameworkElement` as it's target.
But I think that it's a basic scenario to target a specific point of a relatively big `FrameworkElement`.

**Comment by StephenLPeters** [comment]
Hey @MuziburRahman currently teaching tip has a property `Windows.UI.Xaml.Thickness PlacementMargin;` which can be used to offset the position of the teaching tip.  Would this api satisfy your requirement? https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip#add-a-placement-margin

If not can you give us some more info about the scenario you have in mind that the api surface doesn't address?

@SavoySchuler FYI

**Comment by MuziburRahman** [comment]
Yes, this api satisfies my requirement.
