### ISSUE TITLE
Bug: ContentDialog is changing the application-scope default button style (setting BorderBrush)

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#1764]
**Describe the bug**

Opening a ContentDialog will change the application-scope default button style and add a border brush that wasn't previously there. The application will now be using the modified button style until it is restarted.

This initially appeared related to #1405 which had content dialog styling fixes for [Bug: CornerRadius Inconsistency/Missing in ContentDialog/MessageDialog #1345]( https://github.com/microsoft/microsoft-ui-xaml/issues/1345). However, that no longer appears to be true.

**Steps to reproduce the bug**

 1. Startup an application normally, all button styles are correct
 1. Show a ContentDialog from the CloseRequested application event, then close the dialog (cancel)
 1. Make sure to open no other ContentDialogs before step 2
 1. After a visual tree update (navigation to/from a page) the application buttons have a different/incorrect style with a new border brush

Edit: This is more complex than it initially appeared. Even when reverting from WinUI 2.3 back to 2.2 it still was present. Then it became apparent:
 * This may only be an issue when opening a ContentDialog from the CloseRequested application event which is a restricted API.
 * This is only an issue if the ContentDialog opened by the CloseRequested event is the FIRST content dialog shown. If another ContentDialog is opened first (during normal application life-cycle), the button styles will not be changed.

**Expected behavior**

The ContentDialog should not modify the application-scoped default button style in any way.

**Screenshots**

Normal Button Style:

![pic2](https://user-images.githubusercontent.com/17993847/70868047-54dc8300-1f4a-11ea-8f18-b3e60c0e56db.png)

Button Style after ContentDialog is opened then closed:

![pic3](https://user-images.githubusercontent.com/17993847/70868049-5908a080-1f4a-11ea-8d18-14be058553b6.png)

**Version Info**

Microsoft.UI.Xaml 2.3.191211002
Desktop Windows 10 Home 1903

**Comment by robloo** [comment]
@yaichenbaum I believe you mentioned in the past you use the CloseRequested event to open a content dialog prompting the user what to do with any unsaved changes. If you have a chance, and you think it's worth your time, could you see if this appears in your app?

**Comment by yaichenbaum** [comment]
@robloo I am using custom buttons in the dialog, so I don't see this behavior.

**Comment by robloo** [comment]
@yaichenbaum, Ok, thanks a lot for taking a look.

**Comment by YuliKl** [comment]
@robloo thank you for reporting this bug. Can you provide a repro app to help us investigate?

**Comment by robloo** [comment]
@YuliKl Thanks for your response. It's likely I'm missing something in the steps to reproduce but I don't have a lot of time to spend on this at the moment. So I'll see if I can provide more details but can't guarantee a repro app at the moment.

**Comment by robloo** [comment]
@YuliKl After going through the styles I found two lines that were not deleted when migrating to WinUI 2.3 (see `Themes\Styles.xaml` in the sample app source code at the bottom). These two lines changed the default border brush for the button (I was customizing most controls before WinUI 2.3 because 2px borders were undesirable, it's great borders are now improved by default!).

So that means most of, if not all of, this was a bug on my part. The question that is keeping me from closing this right now is why don't my border customizations always show? Why does it take the ContentDialog to make them appear? Something was either changed with styling precedence I don't understand or there is possibly still a bug some place. (At this point I'm thinking it's my mistake again).

**Screen Shot**
![Issue](https://user-images.githubusercontent.com/17993847/71043773-b98c0f00-20fd-11ea-8a96-3e5ed621e66b.gif)

**Source Code**
[App4.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3975956/App4.zip)

**Comment by YuliKl** [comment]
@robloo glad to hear that you were able to solve most of the problem.

> The question that is keeping me from closing this right now is why don't my border customizations always show? Why does it take the ContentDialog to make them appear? 

@MikeHillberg any ideas about these questions?

**Comment by StephenLPeters** [comment]
@robloo could you provide the app you used to make this gif? It would help a lot for our debugging purposes.

**Comment by robloo** [comment]
Hi @StephenLPeters, thanks for taking a look at this. The source code is in the zip file at the bottom of my last post -- sorry it's a bit hard to see.

**Comment by StephenLPeters** [comment]
> Hi @StephenLPeters, thanks for taking a look at this. The source code is in the zip file at the bottom of my last post -- sorry it's a bit hard to see.

Oh awesome! I totally missed that, thank you!

**Comment by kaiguo** [comment]
This should be a bug on application side according to https://github.com/microsoft/microsoft-ui-xaml/issues/1345#issuecomment-568587473, closing.

**Comment by robloo** [comment]
@kaiguo This is NOT the same as #1345. Per my comments above, yes, I'm changing the style of the button. However, why doesn't the custom border always appear on the button? Why does it only show up after the ContentDialog is opened? There may be a bug still in the framework.

Please re-open this or provide an explanation for:
> The question that is keeping me from closing this right now is why don't my border customization always show? Why does it take the ContentDialog to make them appear?

**Comment by chingucoding** [comment]
@StephenLPeters Seems like a framework issue, so it probably needs WinUI 3.

**Comment by StephenLPeters** [comment]
I'm not sure where the issue is, it could be a framework issue, but it could also be a weird by design quirk with how the app is importing the winui 2 package.. I think this could be looked into more before we push it to winui 3, however I don't think we have the resources.

**Comment by robloo** [comment]
I certainly agree there is no need to look at this before WinUI 3.0. Let's wait until WinUI 3.0 is solid and then I can test again to see if it has been fixed. I expect it is a strange case that might just disappear by then.

**Comment by robloo** [comment]
I'm closing this because I don't care to check if it still exists in WinUI3. It wasn't a critical issue (although indicated some fundamental flaws in styling) and someone else can bring it up in the future if it still exists.
