### ISSUE TITLE
Few pixels in Slider show wrong color

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#1765]
**Describe the bug**
Few pixels in slider show the wrong color. Shows up easier especially in higher scale factors.

![image](https://user-images.githubusercontent.com/28935693/70925645-72f4c280-1fe0-11ea-9137-12aa38682b44.png)

**Comment by mdtauk** [comment]
Looks like the end of the "progress" shape is rounded, without stretching underneath the Thumb part

**Comment by harvinders** [comment]
@YuliKl  While we are looking at slider, can we also look at the MediaTransportControls too. It too uses a customised version of slider.

**Comment by chingucoding** [comment]
> Looks like the end of the "progress" shape is rounded, without stretching underneath the Thumb part

Yes correct, this visual bug seems to have been introduced with #1239 , where the corner radius was set for multiple controls, including the the slider control.

A possible solution would be to use margin to move the thumb 1px to the left so it covers the missing corners. Unfortunately, the code behind is not available in WinUI, so we can't change the way the width of the background is calculated, to increase its width and move the corners behind the thumb button.
