### ISSUE TITLE
Update color of ProgressBar's error state

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1766]
**Describe the bug**

Design has specified that the error state of (determinate) ProgressBar should use the red error color:
![image](https://user-images.githubusercontent.com/13142665/70945058-32f60580-2009-11ea-897d-5a5bb2caf7a7.png)

Setting the foreground to `SystemControlErrorTextForegroundBrush` will provide the correct theming behavior.

**Additional context**

Details about indeterminate ProgressBar's appearance are still pending.

**Comment by mdtauk** [comment]
In Win32 guidance, Paused is shown to have a Yellow colour.

Will this Red colour be the same colour used for validation (which becomes yellow in dark mode) or match the Red colour used for Status Icons/Badges?

![image](https://user-images.githubusercontent.com/7389110/70945621-7f633480-204d-11ea-8950-ce0472800091.png)

**Comment by YuliKl** [comment]
> Will this Red colour be the same colour used for validation (which becomes yellow in dark mode) or match the Red colour used for Status Icons/Badges?

We'll use the same brushes that are used for validation.

**Comment by chingucoding** [comment]
So current behavior with determinate error state is this:

![gif](https://user-images.githubusercontent.com/16122379/90986874-86e8bf00-e586-11ea-8a8b-bcf2fa6163f3.gif)

Is it expected that it switches color when changing the value?

**Comment by karenbtlai** [comment]
@chingucoding @YuliKl This is a bug. This is because every time it is being updated, it quickly switches to an `Updating` Visual State for the animation. That visual state's foreground is the system foreground colour, and will need to update to Error colour when updating.

**Comment by chingucoding** [comment]
Thanks for the clarification @karenbtlai ! I assume, it is better to leave this issue (both #1766 and the color switch bug) to you? Or would you mind me helping out here? @ranjeshj FYI.

**Comment by YuliKl** [comment]
@chingucoding feel free to take this one! @karenbtlai is heads down on WinUI 3 work, so your help would be much appreciated.

@MarissaMatt FYI

**Comment by chingucoding** [comment]
Alright, I'll work on this!
