### ISSUE TITLE
TeachingTip Icon is clipped

### ISSUE THREAD

**Issue by stmoy** [microsoft/microsoft-ui-xaml#1773]
**Describe the bug**

TeachingTip icon is clipped when the Tip is opened for the second time. (See screenshots below)

**Steps to reproduce the bug**

1. Launch Xaml Controls Gallery
2. Navigate to TeachingTip page
3. Click the "Show TeachingTip" button. Notice that the tip displays correctly
4. Close the Teaching tip
5. Repeat step 3 and reopen the TeachingTip. Notice that the refresh icon is clipped. 

**Expected behavior**

Icon is not clipped.

**Screenshots**

![image](https://user-images.githubusercontent.com/25991996/71039592-5daf8f00-20d9-11ea-8c38-f1294d413072.png)

**Version Info**

Version	10.0.19041 Build 19041
10.0.19041

NuGet package version: 

2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Possibly related to #1372?

**Comment by StephenLPeters** [comment]
possible dup of #1372
