### ISSUE TITLE
VisualStateManager in explicit Style/ControlTemplate affects instances that do not reference that Style/ControlTemplate

### ISSUE THREAD

**Issue by kseitz10** [microsoft/microsoft-ui-xaml#1774]
**Describe the bug**
Visual states defined within a custom control template may affect instances of that control that do not make use of that template, e.g. theme colors may not be properly applied for selected/hover states.

**Steps to reproduce the bug**
* Extract the default `ItemContainerStyle` for `ListBox`. Do not modify the contents of the style/template. Make sure it is an explicitly-named style, not an implicit one. Put it into its own resource dictionary. Have this dictionary referenced by / merged into a dictionary at the _App.xaml_ level. 
* Define `ColorPaletteResources` that are different than the default theme colors, e.g. change the value for `Accent` so the selected items in the `ListBox` would appear with a color that does not match the user's accent color in Windows.
* Add a `ListBox` to a view and populate it through an `ItemsSource` binding with strings. Let it use the default `ItemContainerStyle.` Do _not_ reference the extracted style/template.

Given these conditions, you would expect to see a list box whose selected items reflect the color specified for `Accent`. However, you will observe that the user's accent color is used instead.

If you delete the `VisualStateManager` from the extracted control template for `ListBoxItem`, then the `Accent` value in the theme dictionary is honored by the list box.

If you make the `ControlTemplate` empty, you can indeed confirm that this style/template is not in use because the list box is still presenting items.

**Expected behavior**
If my App.xaml contains theme dictionaries, but no other merged dictionary contains theme dictionaries, I would expect that styles/templates defined throughout my application to make use of those theme resources. It should not matter if the style/template of a control is defined in the `Page` resources, a merged dictionary that is part of App.xaml, or App.xaml itself.

**Version Info**
Windows 10 1909. Brand new blank UWP application targeting 1903 with no additional Nuget packages. Visual Studio 16.4.1

NuGet package version: 
N/A

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
@kseitz10 Thanks for the bug report! If you have a minimal repro app that you could provide us that would be very helpful in tracking down the issue.

**Comment by StephenLPeters** [comment]
@chrisglein Is Framework team the right place for this?

**Comment by kseitz10** [comment]
[ThemeTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3989270/ThemeTest.zip)

**Comment by StephenLPeters** [comment]
Awesome! Thank you
