### ISSUE TITLE
WinUI3: Adding Templated control doesn't generate Themes/Generic.xaml

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#1778]
**Describe the bug**
When adding a templated control to Visual Studio, no Generic.xaml file is added.

**Steps to reproduce the bug**
1. Create a new WinUI Class Library
2. Right-click the project and select "Add new item..."
3. Choose "Templated Control (WinUI)"
4. Notice that the class is created, but no Themes/Generic.xaml file is added
5. Compare this to the behavior of a UWP Class lib where it is created.

**Expected behavior**
Generic.xaml is added/updated

**Screenshots**
![image](https://user-images.githubusercontent.com/1378165/71147113-94ba9900-21dc-11ea-9f95-e3f591b6b7d1.png)

WinUI Class Library:
![image](https://user-images.githubusercontent.com/1378165/71147131-a1d78800-21dc-11ea-8cee-029647f65d78.png)

UWP Class Library:
![image](https://user-images.githubusercontent.com/1378165/71147140-ab60f000-21dc-11ea-8e7d-2f1ba2b6b616.png)

**Version Info**

Visual Studio 2019 Update 5 Preview 1.
NuGet package version: `3.0.0-alpha.191101.0`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |  Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
@danzil Is this known?

**Comment by danzil** [comment]
Looks like a bug with the template, thanks for reporting it! As a workaround, folks could use the standard UWP template and just rename the namespace from Windows.UI.Xaml to Microsoft.UI.Xaml  in code-behing.

**Comment by dotMorten** [comment]
Yup workaround is easy. Found this will prepping for a WinUI3 custom controls presentation, and this just adds extra stuff to explain

**Comment by dotMorten** [comment]
Just pointing out that this is still an issue in Preview 1

**Comment by stevenbrix** [comment]
This issue has also been fixed, as always, thanks for filing @dotMorten!

**Comment by dotMorten** [comment]
Thank you @stevenbrix 

Confirmed fixed:
![Untitled Project](https://user-images.githubusercontent.com/1378165/99569928-1800e380-2986-11eb-86f7-a4d558a9d3c5.gif)

I did notice the build action for `Generic.xaml` is slightly different in the two cases:

Win32:
![image](https://user-images.githubusercontent.com/1378165/99570017-31a22b00-2986-11eb-9383-c38a0640f419.png)
UWP:
![image](https://user-images.githubusercontent.com/1378165/99570022-36ff7580-2986-11eb-80f6-04967301e8bb.png)

**Comment by stevenbrix** [comment]
Does this cause a problem, or is it just a difference?

**Comment by dotMorten** [comment]
Just an odd difference. Not sure if it'll be a problem. Maybe? 🤷‍♂️
