### ISSUE TITLE
Corner radius not set for ContentDialog and its buttons in 1803 

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1779]
**Describe the bug**

Rounded corner is not shown for the `ContentDialog` and the buttons (primary, secondary and close) inside.

**Steps to reproduce the bug**

1. Create a blank UWP app using visual studio 2019
2. Set the target to 1903 and min target to 1803
3. Include the Microsoft.UI.Xaml prerelease package
4. Make the neccessary resource dictionary change in app.xaml
5. Invoke a `ContentDialog`
6. Run on 1803

**Expected behavior**
Corner radius for buttons and the dialog

**Screenshots**

![image](https://user-images.githubusercontent.com/8557046/71217837-3e9c4180-2313-11ea-8872-2f9435559543.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.0-prerelease.191217001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by robloo** [comment]
Related to #1345 and #1405

**Comment by ranjeshj** [comment]
@kaiguo can you please check if this is resolved by your fix ?#1405

**Comment by kaiguo** [comment]
I think this should be fixed by #1405 as Ranjesh mentioned. I tested on 1803 vm with the same configurations and it looked fine.

![WeChat Screenshot_20191220125006](https://user-images.githubusercontent.com/4424330/71291397-63021900-2327-11ea-8b41-7b0670489cff.png)


@harvinders did you re-template the ContentDialog by any chance? Or were there any special configurations you did but not included in the repro steps ?

**Comment by ranjeshj** [comment]
Fixed by #1405

**Comment by harvinders** [comment]
@kaiguo I did a little bit more investigation and found the issue only comes when we create a `derived` `ContentDialog`. I should have explicitly mentioned it.

```cs
public sealed partial class CustomDialog : ContentDialog
{
}
```
```xaml
<ContentDialog
    x:Class="MyViews.CustomDialog"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    Title="Title"
    MinWidth="600"
    PrimaryButtonText="Primary"
    SecondaryButtonText="Secondary"
    CloseButtonText="Close">

    <Grid x:Name="ContentArea" >

        <Grid.RowDefinitions>
            <RowDefinition x:Name="TitleRow" Height="Auto" />
            <RowDefinition Height="10" />
            <RowDefinition Height="*" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <AutoSuggestBox  QueryIcon="Find" />
        ...
    </Grid>
</ContentDialog>
```
```cs
var customDialog = new CustomDialog()
await customDialog.ShowAsync();
```

However, if we simply create a Dialog using following code, rounded corner shows up properly.

```cs
var simpleDialog = new ContentDialog()
{
  Title = "Hello",
  PrimaryButtonText = "Primary"
};
await simpleDialog.ShowAsync();
 ```

**Comment by harvinders** [comment]
@kaiguo 
The work around is setting the `Style` for my `CustomDialog`
```xaml
<ContentDialog.Resources>
  <Style TargetType="local:CustomDialog" BasedOn="{StaticResource DefaultContentDialogStyle}" />
</ContentDialog.Resources>
```

But I feel one should not have to do it.

**Comment by ranjeshj** [comment]
@kaiguo, Is this a ContentDialog specific issue or a more generic framework issue that affects all derived controls ? If it is not a more common issue, what in ContentDialog is causing this ?

**Comment by kaiguo** [comment]
Yeah I think you have to do the "BasedOn" trick, otherwise it will use styles from the hosting OS, which doesn't have rounded corners.
