### ISSUE TITLE
SplitButton doesn't behave as split button using touch

### ISSUE THREAD

**Issue by GeertvanHorrik** [microsoft/microsoft-ui-xaml#178]
**Describe the bug**

SplitButton doesn't behave as split button using touch.

**Steps to reproduce the bug**

1. Create a split button with a default command and drop down (e.g. with content 'Play')
2. Try clicking the "button" part with the mouse => works
3. Try tapping the "button" part with touch => shows dropdown

**Expected behavior**

Since a default command is bound to the button, I don't want to repeat myself inside the dropdown for touch (otherwise I would have used the DropDownButton). I would expect the SplitButton to be invoking the command when tapping the button part.

**Screenshots**

Using mouse:

![image](https://user-images.githubusercontent.com/1246444/51102490-82bbc380-17df-11e9-8940-b43edd0351bf.png)

Using touch:

![image](https://user-images.githubusercontent.com/1246444/51102382-01fcc780-17df-11e9-9455-30a7f09f185f.png)

**Version Info**

All windows versions (Windows 10 Mobile, and the 1809 update on a surface tablet)

NuGet package version: 

```
<PackageReference Include="Microsoft.UI.Xaml">
  <Version>2.0.181018003.1</Version>
</PackageReference>
```

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [x] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [x] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

-

**Comment by jevansaks** [comment]
This behavior is intentional because the chevron button is smaller than the recommended touch target size and would be too difficult to reliably hit, so touch tap always expands. I'll let @adambarlow discuss whether in practice users like this behavior.

**Comment by mdtauk** [comment]
If you can detect if the control is on a touch capable display, then it could add padding to extend the width of the chevron button?

**Comment by adambarlow** [comment]
@GeertvanHorrik 
If it's not working correctly as a button then that would be a bug. Please let us know how it's misbehaving specifically.

@mdtauk 
A lot of devices have touch monitors that are primarily driven by mouse / keyboard. We would prefer to design our controls to look one way on all devices to ensure consistency of design, while also ensuring they work for all input modalities.

I think this is worth exploring further and would of course prefer for touch users to have the ability to have a split-button with two touch targets. We'll take a look at the sizing and reliability.

**Comment by mdtauk** [comment]
> @mdtauk
> A lot of devices have touch monitors that are primarily driven by mouse / keyboard. We would prefer to design our controls to look one way on all devices to ensure consistency of design, while also ensuring they work for all input modalities.
> 
> I think this is worth exploring further and would of course prefer for touch users to have the ability to have a split-button with two touch targets. We'll take a look at the sizing and reliability.

There are some controls, such as ComboBox flyouts, and Context Menus that do increase their item sizes when called via a touch input.  But it is true that the default state of a control tends to be consistent in all modes.

I would like to put forward a 32 x 32 chevron button, with a vertical separator alongside the standard button.  That separator would then give some confidence to people using touch input.

![image](https://user-images.githubusercontent.com/7389110/51155276-e0e3b780-186e-11e9-8e1a-4fcbb7adc22c.png)

**Comment by lukasf** [comment]
I agree that the current behavior feels broken on touch. There could be a property to always open the flyout on touch, so people could opt-in into the current behavior. But the default should be to execute the command.

**Comment by mdtauk** [comment]
#1207 Mentioning this related Issue, The Toggle Split Button doesn't work with Touch

**Comment by Dylanshapiro** [comment]
I have a client that is reporting this as a bug. will this ever get fixed?

**Comment by sonnemaf** [comment]
The SplitButton is now for me totally useless. Please reconsider this UX philosophy. If I would have wanted this behavior, I would have used a DropDownButton.

**Comment by WillPittenger** [comment]
How about a setting somewhere?

**Comment by sonnemaf** [comment]
> How about a setting somewhere?

I would use a property for that. For example, a `TouchMode` property which is an Enum (values 'Select', 'Popup'). 

```xml
<SplitButton TouchMode="Select">
    <StackPanel Orientation="Horizontal" Spacing="8">
        <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xE75C;" />
        <TextBlock Text="Erase" />
    </StackPanel>
    <SplitButton.Flyout>
        <MenuFlyout Placement="Bottom">
            <MenuFlyoutItem Text="Erase">
                <MenuFlyoutItem.Icon>
                    <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xE75C;" />
                </MenuFlyoutItem.Icon>
            </MenuFlyoutItem>
            <MenuFlyoutItem Text="Mark as guess">
                <MenuFlyoutItem.Icon>
                    <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xE11B;" />
                </MenuFlyoutItem.Icon>
            </MenuFlyoutItem>
            <MenuFlyoutItem Text="Mark as certain">
                <MenuFlyoutItem.Icon>
                    <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xE001;" />
                </MenuFlyoutItem.Icon>
            </MenuFlyoutItem>
        </MenuFlyout>
    </SplitButton.Flyout>
</SplitButton>
```

**Comment by WillPittenger** [comment]
I was referring to a user preference.  Something that would affect the accuracy required.

**Comment by simon-knuth** [comment]
This decision really doesn't make sense anymore, especially since Windows 11 launched. The shell features many buttons with much smaller touch targets (and no tolerance), yet the SplitButton doesn't trust the user's touch input.

![image](https://user-images.githubusercontent.com/50021001/217237459-147cc74f-c2a1-443d-97d5-0f717acb1801.png)
![image](https://user-images.githubusercontent.com/50021001/217237363-58e87e1a-534f-4bd6-baed-3fcc15ed70cb.png)

**Comment by mdtauk** [comment]
This is still an issue with the control by default I believe.

**Comment by sonnemaf** [comment]
I didn't find a solution for it. I just stopped using it.

**Comment by bkudiess** [comment]
This issue was fixed internally and will be available soon :)

**Comment by Pinguin2001** [comment]
@bkudiess Is this issue going to be fixed on the WUX side as well/backported to all currently supported builds? I have revived a bug report from a Surface Pro X user running 26100 about this exact issue on an app of mine
