### ISSUE TITLE
Holding down Enter in MenuFlyout causes visual glitches

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1781]
**Describe the bug**

When navigating a MenuFlyout with keyboard and holding down the Enter key, the menu item visually pulses and glitches.

**Steps to reproduce the bug**

1. In Xaml Controls Gallery, go to either the MenuBar or the MenuFlyout page
2. Using keyboard, open the menu
3. Put keyboard focus on a MenuFlyoutItem and hold down the Enter key

**Expected behavior**

MenuFlyoutItem remains in the *pressed* state while Enter is held.

**Screenshots**

![menuFlyout](https://user-images.githubusercontent.com/13142665/71287962-91c7c180-231e-11ea-93f2-d2c49234b5f1.gif)
(Note the shadow and acrylic in the menu look wrong. That issue is not related to this bug and is being tracked separately.)

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24331110)

**Comment by chingucoding** [comment]
I think since the code behind of MenuFlyout is currently inside the OS, this is something that we can only fix with WinUI 3. It seems like the event is firing upon key pressed and not on key lifted, which the latter is the default behavior of most controls as it seems.
