### ISSUE TITLE
Magnifier : Clicking on the voice combo box inside settings flyout often closes the settings flyout.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1782]
**Describe the bug**

**Steps to reproduce the bug**

1. Launch "Magnifier" application.
2. Activate settings button.
3. Click anywhere except on interactive elements i.e. just on the background
4. Now activate the voice combo box and observe.

**Expected behavior**

After clicking on the voice combo box, it should expand and user should be able to access it.

**Screenshots**

![magnifier](https://user-images.githubusercontent.com/13142665/71288770-42829080-2320-11ea-87a1-0ab414e17f30.gif)

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24402744)

Comment in the original bug:
> Doesn't seem like a Magnifier issue. Magnifier does not do anything when the combo box gets opened.

>Also, the only path of reproing this is clicking on the "background" or label of the flyout and then on the combo box. If you clicked on the slider before interacting with the combo box (even if you clicked on the background before interacting with the slider), the combo box would not dismiss.

**Comment by robloo** [comment]
This is the same as #1467 I believe. Its turned into a real problem recently especially with custom controls. Currently there is no known work-around.

**Comment by ranjeshj** [comment]
@kaiguo This is likely a dup. Can you please take a look at this repro when you have a fix for the other bug ? Thanks

**Comment by kaiguo** [comment]
Yeah this looks like a dup, I'll close this one and use #1467 to track.
