### ISSUE TITLE
Question: Is there any reasonable way to work with Reveal Focus (specifically with scrolling GridViews)?

### ISSUE THREAD

**Issue by bcassell** [microsoft/microsoft-ui-xaml#1783]
I'm trying to use Reveal Focus on UWP on Xbox.  Every time a control is in a scrollviewer (and other containers), the glow gets cut off in a very off-putting way, seemingly no matter how much I play around with margins and padding.  For example, if I have a grid view of buttons with Reveal Focus, and there are enough buttons to necessitate a scrollviewer, buttons at the edges of the gridview will have their glow cut off.  If I start messing with margins/padding the glow starts getting deformed, and still generally gets cut off.  There is an attached property that seems like it should help, ScrollViewer.CanContentRenderOutsideBounds, but when I set to true on the GridView, I see that the actual ScrollViewer hosting the content does not have this value set in the Live Property Explorer.

**Comment by ranjeshj** [comment]
@Austin-Lamb Is there something specific to reveal focus that would cause it to get clipped while the normal system focus visual does not ?
