### ISSUE TITLE
TreeViewItem Template IsExpanded ignored when reused

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#1790]
**Describe the bug**
```
        <muxc:TreeView x:Name="SyntaxTree"
                       ItemsSource="{x:Bind RootNodes, Mode=OneWay}">
            <muxc:TreeView.ItemTemplate>
                <DataTemplate x:DataType="local:XmlSyntaxData">
                    <muxc:TreeViewItem ItemsSource="{x:Bind Children}"
                                       IsExpanded="True">
                       <TextBlock Text="{Binding}"/>
                    </muxc:TreeViewItem>
                </DataTemplate>
            </muxc:TreeView.ItemTemplate>
        </muxc:TreeView>
```
I have a dependency property named RootNodes (a List of a hierarchical data type) bound to the TreeView.  When I set this property the first time, the tree view populates items from the data structure and all the nodes are expanded as would be expected.

When I set this property again a 2nd time and change the list, the tree view items are regenerated; however, they are now not in an expanded state.  They should be in an expanded state.

**Steps to reproduce the bug**

1. Use XAML structure above to configure a set of TreeViewItems
2. Replace the itemssource reference

**Expected behavior**
All TreeViewItems should be expanded as specified in the template.

**Screenshots**
First time:
![image](https://user-images.githubusercontent.com/24302614/71408902-9a591a00-25f4-11ea-922a-6198c1f881bb.png)

Second time:
![image](https://user-images.githubusercontent.com/24302614/71408915-a644dc00-25f4-11ea-8c60-57cf12f3e02e.png)

(Sometimes inconsistent results, e.g. first node will be expanded, but only first node, all other nodes still collapsed, unlike initial behavior.)

**Version Info**
NuGet package version: Microsoft.UI.XAML 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041.1)              | Yes |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by michael-hawker** [comment]
This is from a sample I've been working on, I need to publish it, so I can share a full example eventually.  This piece is just getting in the way of the core experience for the sample, so I need to figure out a workaround.

I actually just noticed even in the initial generation, some of the deeper nodes don't expand, so there may be something else going on even initially as well?

**Comment by ranjeshj** [comment]
@kaiguo, can you please take a look ? 
I'm curious if this is a timing issue between when the TreeViewItem gets children bound to it vs when the IsExpanded property is set. TreeViewItem has an ItemsSource dependency property - so perhaps as a workaround, when that propertychanges, you could manually expand the children.

**Comment by michael-hawker** [comment]
@ranjeshj @kaiguo thinking about this more if it's a timing with the items being loaded from the itemssource, could it be that the isexpanded needs to be updated in the itemssource property changed like the [opacity line here](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/TreeView/TreeViewItem.cpp#L333) too?

**Comment by ranjeshj** [comment]
@michael-hawker. Good catch. That is quite possibly what is causing it. Can you try updating isExpanded when ItemsSource changes and see if that fixes the issue ?

**Comment by michael-hawker** [comment]
Thanks @kaiguo!

@ranjeshj when will I know that the fix has made it in a build?  I can test it out from the NuGet easily when it's in a package.

**Comment by ranjeshj** [comment]
@michael-hawker for testing you can use the nuget package from the PR build artifacts.
