### ISSUE TITLE
WebView mishandles iframes with bad encryption

### ISSUE THREAD

**Issue by nirbil** [microsoft/microsoft-ui-xaml#1796]
If you set a WebView's Source to a page with a bad certificate iframe, the frame fails to load with a certificate error, but the page does not properly complete loading, and the NavigationCompleted event never gets called.

Here's an example project demonstrating the bug:
[UWPWebviewError.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4002355/UWPWebviewError.zip)

When the app loads it uses NavigateToString to load an html into the webview.
You can edit the html it loads in the MainPage.xaml.cs file.
Use html1 to reproduce the bug, html2 and html3 are examples for correctly terminated pages with iframes.

**Comment by Austin-Lamb** [comment]
We aren't planning on investing more into WebView at this time, as we're focusing on WebView2 based on the Chromium-powered Edge.
