### ISSUE TITLE
Question: What is the rationale for default NumberBox.NumberFormatter ?

### ISSUE THREAD

**Issue by tbolon** [microsoft/microsoft-ui-xaml#1798]
I have tested the NumberBox control introduced in WinUI 2.3 and was surprised by the default behavior which use English number formatting.

There is a NumberFormatter property which, in my case is set with a mix of french and english settings:
![image](https://user-images.githubusercontent.com/127185/71513085-3dca5900-2899-11ea-8824-467fbc607369.png)

I have standard french settings on my computer (only the OS is using english UI text), and the regional settings are set on french (the calculator is using the correct settings).

![image](https://user-images.githubusercontent.com/127185/71513186-900b7a00-2899-11ea-95c6-ae226aa1f19d.png)

How is this control supposed to work by default ?

**Comment by ranjeshj** [comment]
We should be getting the system number formatter. We could do the same as what calculator is doing here.
