### ISSUE TITLE
Navigation fails/ refuses to work if removed and re-added from SpliView.Pane

### ISSUE THREAD

**Issue by MuziburRahman** [Microsoft/microsoft-ui-xaml#18]
**Describe the bug**
When a WinUI `NavigationView` is inside a `Splitview.Pane`, removing and re-adding it in runtime stops it's navigation behavior. 

**Steps to reproduce the bug**

Simplest steps to reproduce the behavior:
1. Create a blank UWP/C# app
2. Add WinUI nuget package (Microsoft.UI.Xaml) 
3. Edit App.Xaml to add WinUI:
```
<Application
    x:Class="Test2.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Test2">

    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
    </Application.Resources>

</Application>
```
4. **Add** a SplitView in MainPage.xaml. **Add** WinUI NavigationView inside the pane of the SpliView. **Add** a button in the Splitview.Content which will add/remove the NavigationView from SpliView.Pane.

**MainPage.xaml**:
```
<Page
    x:Class="Test2.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Test2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:WinUI="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <SplitView x:Name="Split" DisplayMode="Inline" IsPaneOpen="True">
            <SplitView.Pane>
                <WinUI:NavigationView x:Name="NavView" IsSettingsVisible="False" IsBackButtonVisible="Collapsed" PaneDisplayMode="Top">
                    <WinUI:NavigationView.MenuItems>
                        <WinUI:NavigationViewItem Content="item 1"/>
                        <WinUI:NavigationViewItem Content="item 2"/>
                    </WinUI:NavigationView.MenuItems>
                </WinUI:NavigationView>
            </SplitView.Pane>

            <Button Content="Add/Remove NavigationView" Click="Button_Click"/>

        </SplitView>
    </Grid>
</Page>
```
**MainPage.xaml.cs**:

```
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;

namespace Test2
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            if (Split.Pane is null)
                Split.Pane = NavView;
            else Split.Pane = null;
        }
    }
}
```
5. Build and Run the app. Tap on the navigation items (Item1 and Item2) to ensure that everything works fine.
6. Remove and Re-add the NavigationView by pressing the *Add/Remove NavigationView* Button twice.
7. Now try the navigation items again. It doesn't work !

**Expected behavior**
Normal navigation behavior.

**Version Info**

NuGet package version: 
 Microsoft.UI.Xaml 2.0.181018003

Windows 10 version:
- [x] October 2018 Update (17763)

Device form factor:
- [x] Desktop

**Comment by YuliKl** [comment]
@MuziburRahman, can you explain your scenario? Putting NavigationView into a SplitView isn't expected usage of this control. Can you help me understand what behavior you're trying to achieve by adding/removing NavigationView?

**Comment by MuziburRahman** [comment]
@YuliKl I don't know how you decide which uses are appropriate and which are not, but look at the portion inside red rectangle, which is using `Pivot` control now (as `NavigationView` had it's problem), but my 1st try was `NavigationView` here, the animated focus follower of `NaviagtionView` looked kinda cool. Also, the header area of the `Pivot` control takes so much space. But I am out of option now.

![image](https://user-images.githubusercontent.com/21083609/48537938-44884d80-e8dd-11e8-9a83-5cb7337b42ab.png)

**Comment by jevansaks** [comment]
That seems like a reasonable usage, but not one we've encountered before. Is @licanhua's workaround suggestion an option for you, @MuziburRahman ?

**Comment by MuziburRahman** [comment]
It might be a workaround, but I have not tried it yet, I am using Pivot now.

**Comment by MuziburRahman** [comment]
Hi @jevansaks , I have tested @licanhua 's workaround. No, it doesn't work.
Even if I don't remove the `NavigationView`,  just close the pane and open it, the `NavigationView` doesn't work.

**Comment by YuliKl** [comment]
Hi @MuziburRahman , thank you for the explanation and screenshot! If Pivot is accomplishing what you need it to, that's great and please continue using Pivot. If things still aren't working to your liking, you can also look into using the [Windows Community Toolkit](https://www.microsoft.com/en-us/p/windows-community-toolkit-sample-app/9nblggh4tlcq#activetab=pivot:overviewtab)'s [TabView](https://github.com/windows-toolkit/WindowsCommunityToolkit) control.

**Comment by licanhua** [comment]
@MuziburRahman , could you please share a small project with the workaround if you still stick with navview? I verified the 'Collapse NavView then make it visible' workaround before and it should work.
