### ISSUE TITLE
New ScrollViewer doesn't properly scroll via mouse wheel on 1803 (17134) and earlier OS releases

### ISSUE THREAD

**Issue by micahl** [Microsoft/microsoft-ui-xaml#180]
**Describe the bug**
Scrolling via mouse wheel isn't working correctly except for 1809 (17763) and later.

**Steps to reproduce the bug**

1. Create and run an app using the new ScrollViewer (formerly ScrollerView) on an earlier release
2. Try scrolling via mouse wheel

**Expected behavior**

Mouse wheel scrolls content similar to the existing ScrollViewer control

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.1.181217001-prerelease (or earlier)

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] October 2018 Update (17763)
- [x] April 2018 Update (17134)
- [x] Fall Creators Update (16299)
- [x] Creators Update (15063)
- [x] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by RBrid** [comment]
@micahl, this bug is no longer valid, right?

**Comment by micahl** [comment]
I haven't tried it on an older version yet, but I'd assume that with your most recent changes it would no longer be valid.  Feel free to dupe to your PR.

**Comment by RBrid** [comment]
This is expected to work now after the work done for Issue #421.
