### ISSUE TITLE
ShowMode on flyout doesn't seem to respect xaml settings

### ISSUE THREAD

**Issue by EriWong** [microsoft/microsoft-ui-xaml#1803]
**Describe the bug**
ShowMode is not properly being set when set from xaml.  Code behind works properly.

**Steps to reproduce the bug**
1. Create a flyout in xaml
2. Set ShowMode to transient in xaml
3. See how focus behaves/examine the flyout properties in VS while debugging

**Expected behavior**
The flyout ShowMode property is set to Transient

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190830001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (vb_release_ingestion.191208-1700)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
This was found when working on a C++/CX project

**Comment by ranjeshj** [comment]
@EriWong What is the actual behavior that you are seeing ? Do you mean to say that the control is setting the property to something else after loading ?  In that case, can you attach a property change event handler on that property and get a callstack of where this is changing ? Thanks.
