### ISSUE TITLE
Unreliable CI test execution behavior

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1814]
Lately, the CI seems to become a bit unreliable since it reports multiple tests as failing despite no changes have been made for the controls the failing tests are for.

| PR | Error | Helix log error | Helix Loglink |
|---|------|------------------|----------|
| #1799 | SwipeItems Work item failed | App failed to start | [Link](https://helix.dot.net/api/2019-06-17/jobs/1d1df46c-3420-49cb-8889-7eb811dd3cd4/workitems/Windows.UI.Xaml.Tests.MUXControls.InteractionTests.SwipeControlTests/console)|
| #1759 | ProgressBarTests Work item failed (may be related to changes of PR) | Failed to setup tests | [Link](https://helix.dot.net/api/2019-06-17/jobs/98b91e44-99f3-4e36-8670-f70492b5b91b/workitems/Windows.UI.Xaml.Tests.MUXControls.InteractionTests.ProgressBarTests/console) |
| #1800 | ProgressBarTests Work item failed | "Animation complete wait took longer than idle timeout" | [Link](https://helix.dot.net/api/2019-06-17/jobs/2aef7683-6070-4ade-a3f9-9b2412c90473/workitems/Windows.UI.Xaml.Tests.MUXControls.InteractionTests.ProgressBarTests/console)
| #1788 | ApiTests.RepeaterTests.RepeaterTests.VerifyCurrentAnchor , InteractionTests.RadioButtonsTests.GamepadCanEscapeAndDoesNotSelectWithFocus | N/A | N/A |

**Comment by karenbtlai** [comment]
@chingucoding  Turns out the ProgressBarTests failing are due to down leveling issues from `SystemErrorTextColor` resource being not available in RS4 and below. I'm working to fix that right now.

**Comment by chingucoding** [comment]
@kmahone I think we can close this now, as @karenbtlai PR was merged successfully and reliability has improved (at least it seems like that)
