### ISSUE TITLE
Tab navigation is not symmetric for a ListView whose items contain a ListView

### ISSUE THREAD

**Issue by guybark** [microsoft/microsoft-ui-xaml#1819]
**Describe the bug**
Tab navigation is not symmetric for a ListView whose items contain a ListView.

**Steps to reproduce the bug**
1. Create a new blank UWP XAML app.
2. Add UI as follows:

`    <Grid Margin="20">
        <StackPanel>
            <Button Content="Before" />
            <ListView>
                <ListViewItem>
                    <local:MyUserControl Width="200" Height="200" />
                </ListViewItem>
                <ListViewItem>
                    <local:MyUserControl Width="200" Height="200" />
                </ListViewItem>
                <ListViewItem>
                    <local:MyUserControl Width="200" Height="200" />
                </ListViewItem>
            </ListView>
            <Button Content="After" />
        </StackPanel>
    </Grid>
`

Where MyUserControl is…

`    <Grid Margin="20">
        <StackPanel>
            <TextBlock Text="Some text" />
            <Button Content="Do something" />
            <ListView>
                <ListViewItem>
                    <TextBlock Text="Inner 1"/>
                </ListViewItem>
                <ListViewItem>
                    <TextBlock Text="Inner 2"/>
                </ListViewItem>
                <ListViewItem>
                    <TextBlock Text="Inner 3"/>
                </ListViewItem>
            </ListView>
        </StackPanel>
    </Grid>
`

3. Run the app.
4. Tab into the outer list. Notice focus moves to the first item in the outer list as expected. 
5. Tab again. Notice focus moves to the first focusable control inside the first item, as expected.
6. Tab again. Notice focus moves to the first item in the contained list, as expected.
7. Tab again. Notice focus moves out of the outer list. Seems reasonable.
8. Do Shift+Tab. Notice focus moves a control in the last item in the outer list.

**Expected behavior**
Shift+Tab should provide a navigation path symmetric to the Tab navigation. To have Shift+Tab move back into a different item than was encountered during the Tab navigation could lead to confusion.

I can apparently avoid hitting the last item in the outer list when doing this backward navigation, by explicitly selecting the items in the outer list as they get focus. However, even with that change, when I do the shift+tab back into the outer list, focus moves to an actual item in the outer list, rather than the last of the contained items within an item. Perhaps that's By Design for UWP XAML, as it means that whenever entering the outer list, focus moves to an actual item in the outer list, regardless of which direction the focus is moving from. So even though the focus isn’t symmetric it will be predictable once the user’s familiar with the UI.

**Screenshots**
![ListContainingLists](https://user-images.githubusercontent.com/14315611/71948950-a01f3580-3186-11ea-8343-b8bf118f89ac.png)

**Version Info**

NuGet package version: 
Microsoft.NETCoreUI.UniversalWindowsPlatform 6.2.9

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |

**Additional context**

**Comment by ranjeshj** [comment]
Navigation within nested ListViews is a bit tricky. There is some documentation on nested UI here - https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/nested-ui 

@chigy Is this behavior seen by @guybark expected with nested UI ?

**Comment by chigy** [comment]
@ranjesh , correct me if I am wrong but what @guybark is reporting here is not really nested UI issue, but it appears that Shift+Tab is not back tracking the tab behavior. Shift+Tab is expected to go to the last tab stop visited in the order of tab order and this shouldn't be special for nested UI.

**Comment by ranjeshj** [comment]
This is likely a bug in ListView. ListView has specialized tab handling logic to handle landing on the selected index.
