### ISSUE TITLE
NavigationViewList animation did not work correctly

### ISSUE THREAD

**Issue by HHChaos** [Microsoft/microsoft-ui-xaml#182]
**Describe the bug**
The animation does not work correctly when the selected item of NavigationViewList changed.

**Steps to reproduce the bug**
Toggle the selected item of NavigationViewList.

**Screenshots**
The animation is in the wrong place.(Services item in the GIF)

![screenshot](https://user-images.githubusercontent.com/9880072/51154629-72731980-18af-11e9-8004-9e3b2b7d158d.gif)

**Version Info**

NuGet package version: 
 [Microsoft.UI.Xaml 2.0.181011001] 

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by jevansaks** [comment]
Good find! Want to help contribute a fix? :)

**Comment by HHChaos** [comment]
@jevansaks Sure, I'm preparing it.
![navview](https://user-images.githubusercontent.com/9880072/51236781-fb707a80-19ad-11e9-9048-7a7533b67b8b.gif)
