### ISSUE TITLE
The selected node of TreeView will be automatic change when expand 

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#1820]
**Describe the bug**

The selected item in TreeView will be automatic change when expand 
**Steps to reproduce the bug**

1. Select a node in TreeView, which is not expanded
2. Then expand this node, now the selected node of treeview was changed to its sub node.

**Expected behavior**

The selected node of TreeView should not be changed
**Screenshots**

![GIF 2020-1-8 17-10-00](https://user-images.githubusercontent.com/42038175/71965021-d36ecc80-3239-11ea-88b8-acbba1c6e846.gif)

**Version Info**

NuGet package version: 

2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by kmahone** [comment]
@zhuxb711, thanks for reporting this issue. I was not able to reproduce the issue myself. Could you please share a repro app with us? 

Could you also please clarify how you are interacting with the TreeView? Are you using mouse or keyboard?

Thanks.

**Comment by zhuxb711** [comment]
@kmahone I'm using mouse to interact.

I make a demo for you, this problem does exist. &If I select parent node and then expand it, the selection will be changed to its subnode. 

Tips: Before you run the demo, please granting "file system access" in system setting for demo
[TreeViewTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4038287/TreeViewTest.zip)

**Comment by kmahone** [comment]
Thanks @zhuxb711 I can reproduce the issue now.

**Comment by kmahone** [comment]
@kaiguo can you please take a look to determine the root cause here and come up with a workaround if possible.

**Comment by zhuxb711** [comment]
@kmahone This problem is very confusing to my users and hopes to be fixed as soon as possible

**Comment by zhuxb711** [comment]
I want to know when this problem can be fixed @kmahone

**Comment by ranjeshj** [comment]
@zhub711 there have been some fixes to TreeView, can you see if the issue repros in the latest prerelease (went out today). @kaiguo did you get a chance to look at this ?

**Comment by zhuxb711** [comment]
I have installed the latest preview version and tested this issue, it still exists and has not been fixed @ranjeshj

**Comment by ranjeshj** [comment]
This is really weird behavior. I'm not sure yet why the expansion and populating of the children collection would affect the selection state. @zhuxb711 One hacky workaround to unblock you could be to save and restore the selection after the expand operation like so. 

 var oldSelectedNode = FolderTree.SelectedNode;
            if (args.Node.HasUnrealizedChildren)
            {
                await FillTreeNode(args.Node);
            }
            FolderTree.SelectedNode = oldSelectedNode;

**Comment by zhuxb711** [comment]
@ranjeshj @kaiguo  But this code still looks strange. I also think that expanding a selected TreeViewNode will cause the selected item to change very strangely. Is there any progress in the investigation of the cause of this problem?

**Comment by kaiguo** [comment]
@ranjeshj not 100% sure but it probably has something to do with this,
https://github.com/microsoft/microsoft-ui-xaml/blob/ca95be6f5248eaa55ec523f2d6e7b50f6e0d53e7/dev/TreeView/TreeViewList.cpp#L356-L359

I think this code was added to reverse some ListView selection changes we didn't want when using databinding. The demo code works on TreeNode directly and doesn't use ItemsSource binding. _Perhaps_ we should execute the code block above only in content mode so adding an extra `IsContentMode()` check *might* fix the issue.

**Comment by Felix-Dev** [comment]
@kaiguo You might want to test it yourself but I went ahead and added your suggestion to the TreeViewList, then built a nuget package of WinUI and used it on the repro app. Result: I'm still seeing the same erroneous selection change behavior reported here.

**Comment by zhuxb711** [comment]
@kaiguo @ranjeshj 
I see other people asking the same question. Is there any progress in the investigation of this issue?

**Comment by ranjeshj** [comment]
@chingucoding Thanks for the PR. @StephenLPeters can you please review this PR ? Thanks!
