### ISSUE TITLE
ItemsSourceView should expose IndexOf

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#1828]
There are cases where we need IndexOf to be exposed in ItemsSourceView. If the ItemsSource supports this we can provide a value. This is currently needed for NavigationView and RadioButtons and we do have it internally. We just need to expose it via ItemsSourceView.

**Comment by chingucoding** [comment]
Having looked at the ItemsSourceView file, I am not exactly sure how we could add that. Do we just add a function IndexOf and throw NotImplemented (like all core functions do)? Should this be listed as public API?

**Comment by ranjeshj** [comment]
This would be just exposing the IndexOf api on ItemsSourceView type (in preview). @anawishnoff Given that we will be exposing public API, we need to do an API review for this. 

Already implemented internally here.
https://github.com/microsoft/microsoft-ui-xaml/blob/440966762fcb622e12a8e6f596514a355d04739a/dev/Repeater/InspectingDataSource.cpp#L106

**Comment by chingucoding** [comment]
Okay, I see. I would like to add that. Would you like me to also create a PR for the API spec?
