### ISSUE TITLE
Investigate using `OnPreview` key events for NavigationViewItems

### ISSUE THREAD

**Issue by ojhad** [microsoft/microsoft-ui-xaml#1835]
After [the update to NavigationView where ListView was replaced with ItemsRepeater](https://github.com/microsoft/microsoft-ui-xaml/pull/1683), the NavigationViewItems utilize both the KeyDown and KeyUp events (same as the settings item behaves). However, using the`OnPreviewKeyDown` or `OnPreviewKeyUp`  event can improve implementation as we'd only need to use one keydown event type (KeyDown or KeyUp), as brought up in [this comment](https://github.com/microsoft/microsoft-ui-xaml/pull/1683#discussion_r360508286).

**Comment by chingucoding** [comment]
Is this issue still relevant given that we moved to only using KeyDown some time ago?
