### ISSUE TITLE
NumberBox header and description display issues

### ISSUE THREAD

**Issue by Kinnara** [microsoft/microsoft-ui-xaml#1839]
**Describe the bug**
```xaml
<muxc:NumberBox
    Width="300"
    Header="Header Header Header Header Header"
    Description="Description"
    SpinButtonPlacementMode="Inline" />
```

![image](https://user-images.githubusercontent.com/1617766/72310948-17405680-36be-11ea-9a27-5b08eadae689.png)

There are two issues:
1. The header wraps too early, before reaching the right edge of the control.
2. The spin buttons are offset when description is used.

I think one way to fix these is to move the header and description content presenters out of the TextBox and into the NumberBox itself.

**Expected behavior**
![image](https://user-images.githubusercontent.com/1617766/72311190-d7c63a00-36be-11ea-961b-7ee77bba988c.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

**Comment by StephenLPeters** [comment]
@TeaP FYI

**Comment by StephenLPeters** [comment]
@SavoySchuler should the header be wrapping at all?
