### ISSUE TITLE
New ScrollViewer doesn't animate bringing focused items into view on Xbox

### ISSUE THREAD

**Issue by micahl** [microsoft/microsoft-ui-xaml#184]
**Describe the bug**

The default behavior for the Windows.UI.Xaml ScrollViewer is that scrolling to bring a focused item into view is animated instead of an immediate jump.  The new ScrollViewer doesn't do this.

**Steps to reproduce the bug**

Include this in an app and run it on Xbox
```XAML
<mux:ScrollViewer>
 <!-- Insert a bunch of buttons here -->
</mux:ScrollViewer>
```

**Expected behavior**

Moving focus via Dpad/left thumbstick (or the triggers for pageup/down movement) should bring the newly focused item into view with an animated scroll.

**Version Info**

NuGet package version: 

Windows 10 version:
- [x] Insider Build (xxxxx)
- [x] October 2018 Update (17763)
- [x] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Xbox

**Comment by RBrid** [comment]
@micahl, this is By Design from the Scroller's perspective:  it responds to a UIElement::BringIntoViewRequested event occurrence with args.AnimationDesired set to False.  That request is coming from the framework.  So the Scroller jumps instead of animating as expected.

Now, I'll try to figure out why the framework makes such a request while the old WUX ScrollViewer animates.

**Comment by RBrid** [comment]
Summary of my findings: 

The old WUX ScrollViewer calls an internal method DependencyObject::SetFocusedElementWithDirection with an animateIfBringIntoView parameter set to True.
The new MUX ScrollViewer calls a public method FocusManager::TryFocusAsync which has no parameter to animate vs jump.

Currently there is no public alternative to FocusManager::TryFocusAsync, to launch an animated focus change.   We would have to extend the framework’s FocusManager to accept some kind of AnimationDesired flag like the existing BringIntoViewOptions::AnimationDesired.

This issue thus becomes a feature request for the XAML framework.

**Comment by micahl** [comment]
Let's continue to use this issue to track the work for the new ScrollViewer and I'll create a separate feature request for the focus manager.

**Comment by RBrid** [comment]
Working on a workaround for this XAML framework limitation.

**Comment by RBrid** [comment]
Added a workaround in the MUX ScrollViewer control so that gamepad input causes animated view changes.
