### ISSUE TITLE
 INotifyPropertyChanged.PropertyChanged with null parameter is incorrectly handled in UWP

### ISSUE THREAD

**Issue by Kill4kan** [microsoft/microsoft-ui-xaml#1840]
This issue was originally reported at https://developercommunity.visualstudio.com/content/problem/880126/inotifypropertychangedpropertychanged-with-null-pa.html, but I was suggested to report it here.

The thing is that the System.StubHelpers.HStringMarshaler.ConvertToNativeReference method does not handle PropertyChanged notifications correctly in UWP. As stated in the [INotifyPropertyChanged\.PropertyChanged Event](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged.propertychanged?view=netframework-4.8) topic, the _null_ parameter is valid and indicates that all properties were changed. However, if you raise this event in UWP as follows:

PropertyChanged(this, new PropertyChangedEventArgs(null));

you'll get ArgumentNullException with the following callstack:

at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)
at System.StubHelpers.EventArgsMarshaler.CreateNativePCEventArgsInstance(String name)
at System.Runtime.InteropServices.WindowsRuntime.PropertyChangedEventArgsMarshaler.ConvertToNative(PropertyChangedEventArgs managedArgs)
at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)

We expect that the PropertyChanged event with a _null_ parameter won't cause any error, as documented. This code worked in our libraries in all platforms for more than 10 years, and we cannot change it without a breaking change for our customers just to fix this UWP issue.

**Comment by ranjeshj** [comment]
@MikeHillberg Is this a bug in the .net interop layer ?

**Comment by MikeHillberg** [comment]
This is a confusion projection point between C# and WinRT; WinRT doesn't support null strings (hstring). So it's a 3 state mapping onto a 2 state. It's similarly an error to set TextBlock.Text to null. The INPC documentation does allow string.Empty.

**Comment by Felix-Dev** [comment]
@MikeHillberg If null is not a valid input for the INotifyPropertyChanged.PropertyChanged event for WinRT, the the documentation should be updated. As of now that [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged.propertychanged?view=dotnet-uwp-10.0) still reads as follows:

> The PropertyChanged event can indicate all properties on the object have changed by using either null or String.Empty as the property name in the PropertyChangedEventArgs.

It will also be helpful then to add a Remarks section (or Attention section, etc...) to highlight this change in API for folks wanting to port over their WPF projects to UWP (as an example).

**Comment by MikeHillberg** [comment]
I submitted an update to the INPC doc you referenced.

**Comment by chrisglein** [comment]
@MikeHillberg So to be clear this is a doc issue, you've submitted a fix (thank you! Can you link the update here if possible?), and this issue is safe to close?

**Comment by MikeHillberg** [comment]
Right. Doc update: https://github.com/dotnet/dotnet-api-docs/pull/3771

Thank you @Kill4kan and @Felix-Dev
