### ISSUE TITLE
TeachingTip crashes the application

### ISSUE THREAD

**Issue by eyalkapah** [microsoft/microsoft-ui-xaml#1841]
**Describe the bug**
When trying to open a TeachingTip control, the application shuts down.

**Steps to reproduce the bug**
1. Click the Save button
2. The application crashes

**Expected behavior**
TeachingTip to be opened

**Screenshots**

**Version Info**
NuGet package version: 
2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)         | No
| Anniversary Update (14393)      | Yes

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes|

**Additional context**
as mentioned, it occurs on 14393 build.
clicking on Open crashes the application.

Demo app provided: https://github.com/eyalkapah/WinUIDemo.git

**Comment by ranjeshj** [comment]
The repro works on recent builds. Teaching tip depends on certain platform features that are not available in the anniversary update. Post WinUI3 those platform features will be part of WinUI and will allow going further downlevel.

**Comment by StephenLPeters** [comment]
In general winui does not officially support RS1 (14393) builds. Unfortunately teaching tip does require some RS2 functionality to function.  I would suggest doing a platform check before calling the code that opens the teaching tip if you are trying to support RS1.  You can see how to do that in our SharedHelpers.cpp file.  With winui 3 this issue will go away.
