### ISSUE TITLE
TabViewItem can no longer be a child of TabView

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#1844]
**Describe the bug**
If you try and add a `TabViewItem` as the content of a `TabView` as in [this docs example](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tab-view#display-tabview-tabs-in-a-windows-titlebar) you get an error:

> TabView does not support TabViewItem as content.

(I feel like this may be a regression as the docs were probably valid at one point.)

In WinUI 2.3, you need to instead encase the TabViewItems in a special `<muxc:TabView.TabItems>` property.

**Steps to reproduce the bug**

1. Open XAML Studio
2. Paste in the example from the docs:

```
    <muxc:TabView HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
        <muxc:TabViewItem Header="Home" />
        <muxc:TabViewItem Header="Document 1" />
        <muxc:TabViewItem Header="Document 2" />
        <muxc:TabViewItem Header="Document 3" />

        <muxc:TabView.TabStripHeader>
            <Grid x:Name="ShellTitlebarInset" Background="Transparent" />
        </muxc:TabView.TabStripHeader>
        <muxc:TabView.TabStripFooter>
            <Grid x:Name="CustomDragRegion" Background="Transparent" />
        </muxc:TabView.TabStripFooter>
    </muxc:TabView>
```

Note: the Icon property from the example was also removed, as modified the above.

**Expected behavior**
Should display tabs without needing to wrap in TabItems property:

```
        <muxc:TabView.TabItems>
            <muxc:TabViewItem Header="Home" />
            <muxc:TabViewItem Header="Document 1" />
            <muxc:TabViewItem  Header="Document 2" />
            <muxc:TabViewItem  Header="Document 3" />
        </muxc:TabView.TabItems>
```

**Version Info**
WinUI 2.3.191129002

**Additional context**
Reference #1332

**Comment by ranjeshj** [comment]
@stmoy It looks like this is not working because TabItems is not the content property for TabView. We can either update the sample or make it as the content property.

**Comment by michael-hawker** [comment]
It'd be nice to see it as the content property, as that's a pretty standard practice. It's always nice to be able to type less. 🙂

**Comment by stmoy** [comment]
In the same way that one can add ListViewItems to ListView, I feel that we should be able to do the same with TabView.
