### ISSUE TITLE
Bug: NumberBox visual issue with anything other than 100% display & text scaling.

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/microsoft-ui-xaml#1846]
**Describe the bug**
The NumberBox visual is disjointed when `SpinButtonPlacementMode="Inline"` & display and/or text scaling is set to anything other than 100% (didn't test all values).

**Steps to reproduce the bug**
1. Set text and/or display scaling above 100%
2. Look at the NumberBox with `SpinButtonPlacementMode="Inline"`

**Expected behavior**
It should not look disjointed.

**Screenshots**
![Annotation 2020-01-14 202538](https://user-images.githubusercontent.com/5379488/72396865-0d454480-370c-11ea-9b02-04166b8e9514.png)

**Version Info**
XAML Controls Gallery v1.2.12.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by chingucoding** [comment]
I think the right behavior would be to not scale icon but increase button size, like we did with other controls.

**Comment by StephenLPeters** [comment]
@TeaP FYI

**Comment by StephenLPeters** [comment]
> I think the right behavior would be to not scale icon but increase button size, like we did with other controls.

I think you are right

**Comment by mdtauk** [comment]
I think the Icon/Glyph should remain centred within the button as the button size changes.  But the text size and icon glyphs should be scaled together, as I believe happens with Win32 controls.

**Comment by kmgallahan** [comment]
@mdtauk

The logic that was agreed upon via #1650, #1519, and #1413 was that:

* Glyphs/icons **do scale** with display scaling
* Glyphs/icons **do not scale** with text scaling

As per [this comment](https://github.com/microsoft/microsoft-ui-xaml/issues/1650#issuecomment-557232921):

> I think the default answer is: don't scale icons, even if they're glyph-based. The user wanted text to be bigger but if we made icons bigger too it would be the same behavior as DPI scaling for the most part. The spirit of the setting is that just text gets bigger.

**Comment by mdtauk** [comment]
> * Glyphs/icons **do** scale with display scaling
> * Glyphs/icons **do not** scale with text scaling
> 
That sounds perfect
