### ISSUE TITLE
Fix NavigationView ToolTipCustomContentTest interaction test

### ISSUE THREAD

**Issue by ojhad** [microsoft/microsoft-ui-xaml#1851]
There was an interaction test that was disabled as part of [the move to ItemsRepeater](https://github.com/microsoft/microsoft-ui-xaml/pull/1683).
Fix and re-enable it.

Test Name: `ToolTipCustomContentTest` -> Need to find a new way to test this because the old way of applying RS3 templates has been deleted. The old template had the tooltips defined which the old implementation of the test was leveraging to verify if tooltips where being shown. This is no longer the case for the current templates.

**Comment by ranjeshj** [comment]
@ojhad Do you need help figuring out how to fix this test or is this just for tracking ? If it is the former, can you provide more details.

**Comment by ojhad** [comment]
This is just for tracking, however i'm not currently working on this, which is why I left it unassigned. Updated the description in case someone decides to pick it up before I get the chance to circle back to this.
