### ISSUE TITLE
NumberBox does not set a default AutomationProperties.Name value based on its header.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1854]
**Describe the bug**

**Steps to reproduce the bug**

1. Launch XAML Controls Gallery.
2. Activate Automation Properties from home page.
3. Navigate to text box present beside Font Size of texts and observe its name property.

**Expected behavior**

Name Property should be there for text box

**Actual behavior**

Text box name property missing.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/72557372-7389ae80-3855-11ea-9acb-7533fcb29ea5.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.12.0

**Additional context**

Copied from [internal bug](https://dev.azure.com/microsoft/OS/_workitems/edit/24649841)

**Comment by StephenLPeters** [comment]
@SavoySchuler If there is no header, what should the default automation name be? should the placeholder text be used?  Header is an Object, what if it doesn't have a good string equivalent?

**Comment by ranjeshj** [comment]
We could do something similar to https://github.com/microsoft/microsoft-ui-xaml/blob/880dd229078ab8e68263c29a43f9f6580b10195f/dev/TreeView/TreeViewNode.cpp#L271

**Comment by chingucoding** [comment]
> @SavoySchuler If there is no header, what should the default automation name be? should the placeholder text be used? Header is an Object, what if it doesn't have a good string equivalent?

When you look at the sample in the XAML Controls Gallery, the "spinner" has a UIA name, when using AutomationProperties.LabeledBy or AutomationProperties.Name. I think this UIA name should also apply to the "edit".

**Comment by robloo** [comment]
I don't think this issue was actually fixed. Can someone re-check it? I still see it in version 2.4.2.
