### ISSUE TITLE
Cannot reference DefaultRadioButtonStyle from app. Resource not found error.

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#1855]
Add this Xaml to your app:

`<RadioButton Style="{StaticResource DefaultRadioButtonStyle}" Content="RadioButton" />`

An error is raised:

`'Cannot find a Resource with the Name/Key DefaultRadioButtonStyle'.`

I think this is due to the fact that DefaultRadioButtonStyle is ending up in generic.xaml instead of themeresources.xaml

**Comment by StephenLPeters** [comment]
@kmahone How did this come up? is it blocking something?

**Comment by kmahone** [comment]
The Settings app reported it.

**Comment by ranjeshj** [comment]
Right that style is in RadioButton.xaml.. perhaps it should be in RadioButton_themeresources.xaml.
