### ISSUE TITLE
Error Adding DataGrid in WinUI 3 Alpha Page

### ISSUE THREAD

**Issue by infoequipt** [microsoft/microsoft-ui-xaml#1860]
**XamlCompiler error WMC0020: Cannot add 'DataGrid' into the collection property 'Children', type must be 'UIElement'**

Create a new project using the WinUI 3.0 Alpha C# "Blank App (WinUI UWP)" template.
Add [Microsoft.Toolkit.Uwp.UI.Controls] DataGrid to Page.

VS 2019 Community 16.4.3
Microsoft.WinUI v3.0.0-alpha.191101.0
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid v6.0.0
Windows 10 Version 1903 10.0.18362

**Comment by ranjeshj** [comment]
@infoequipt The data grid in the toolkit is built on top of the platform xaml (Windows.Ui.Xaml). WinUI3 is the same XAML codebase that has been decoupled from the OS (and has an updated namespace Microsoft.UI.Xaml). The reason I believe you are seeing is that the datagrid is not compiled against WinUI3. We need a version of the toolkit that targets WinUI3 for that to work. @nmetulev and @MikeHillberg

**Comment by infoequipt** [comment]
Thanks Ranjesh, I thought that might me the case.

**Comment by nmetulev** [comment]
Ping @michael-hawker

**Comment by duke7553** [comment]
Hopefully, there will be work started on a [new DataGrid](https://github.com/microsoft/microsoft-ui-xaml/issues/1500)  before the stable release of WinUI 3 Desktop.

**Comment by StephenLPeters** [comment]
This should be extended to all of the toolkit, not just data grid.

**Comment by ranjeshj** [comment]
I filed a bug in Windows Community toolkit to track this.
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3106

**Comment by azchohfi** [comment]
I did push a branch of the toolkit that supports that, but it's in very early stages, and not everything is ported.
https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/winui
This is something that we will definitely support on the toolkit once winui3 is stable.

**Comment by ranjeshj** [comment]
@azchohfi  That is awesome ! Thanks.
