### ISSUE TITLE
Proposal: NavigationView Supporting Right and Left Pane Placement

### ISSUE THREAD

**Issue by ToddThomson** [microsoft/microsoft-ui-xaml#1861]
Has there been any past or present interest in providing a "RightCompact" display mode for the navigation view?

I feel that this would be a nice UI addition for "Secondary" page(s) navigation.

I've built a prototype user control using the LeftCompact display mode, but the selection indicators and shadowing don't quite look right.

I could get by with just eliminating the OpenPane shadow border, but the only way I can see to do this is to modify the internal SplitView XAML template. Any guidance to remove the OpenPane shadow would be appreciated!

**Comment by ToddThomson** [comment]
@YuliKl I have gotten a bit further in my development of a DockingNavigationView which utilizes the NavigationView. The DockingNavigationView can be put into 2 states: Docked Right; Docked Left. When docked right, the NavigationView needs to support PanePlacement="Right". When docked left the NavigationView needs to support PanePlacement="Left".

I have been able to add PanePlacement to the internal NavigationView SplitView by overriding OnApplyTemplate in a class deriving from NavigationView.

The main issue I had after this was customizing the positioning of the  NavigationView "PaneToggleButtonGrid". Currently the PaneToggleButton ( Hamburger Button ) floats in the top left of the  Navigation View. I relocated this button to float in the top left of the SplitView.Pane.

The 2nd issue I had was the SplitView.Pane list items. When the PanePlacement is set to "Right", the compact display mode does not show the menu list item icons. The fix for this is set the CompactPaneLength to the size of the navigation icon width (In my opinion this is a general bug in the NavigationView ).

I mention all this as it is generally quite easy to change the NavigationView to support both a Right and Left PanePlacement dependency property. I believe this would be a welcomed feature for the UWP community.

**Comment by YuliKl** [comment]
@ToddThomson thank you for your work so far! Although for complete transparency, I have to mention that the WinUI team doesn't currently have cycles to tackle this feature request. 

It would be very helpful for me to understand the exact scenario you're hoping to address. When would you want NavigationView's pane to open from the right? Do you have any wireframes or comps illustrating the scenario? You mention "secondary" pages in the proposal, can you elaborate?

**Comment by ToddThomson** [comment]
@YuliKl Here is a screenshot of the TdiView control where the a left tool dock has been added.

[TdiView](https://github.com/ToddThomson/TdiView/blob/master/TdiView-Shell.png)

**Comment by ToddThomson** [comment]
@YuliKl The screenshot above shows a RHS ToolDockView which uses the NavigationView with essentially a "Right" pane placement (The ToolDockView has a PanePlacement dependency property which has a Right or Left value ). The TdiView container control can have a right and left dock with a central tabbed document pane.

The purpose for the ToolDockView is to hold a variety of secondary, non-document types or "Tool" pages. 

As I mentioned earlier, there really isn't much that has to be done to the NavigationView to support a Right pane placement.

**Comment by YuliKl** [comment]
@ToddThomson, is your intent that the hamburger button open the yellow Output pane, or expand the icons on the right to be full NavigationViewItems in width?

I wonder if this scenario should use a SplitView with a hamburger button and custom content?

**Comment by ToddThomson** [comment]
@YuliKl The hamburger button is from the internal NavigationView. The hamburger button opens the internal SplitView.Pane which contains the NavigationViewItems.

I decided to use the NavigationView as it has essentially everything I need except the "Right" pane placement ( for the internal SplitView ). The visuals and animated transitions of the NavigationViewItems are what I liked from the NavigationView ( and why I didn't go the SplitView route - as I would then need to recreate all the visuals ).

I guess my ask comes down to this: the NavigationView ( along with the NavigationViewItem ) can be used to provide many features that I would like to have in a UWP desktop application. However the NavigationView is only provided with a Left placement. I have been able subclass the NavigationView and provided a Right placement, but it doesn't need to be that much work. The NavigationView could easily be augmented to supply a Right placement.

I understand that the WinUI team has a lot to do. I meant only to bring my request to your attention.

**Comment by mdtauk** [comment]
NavigationView has a Top placement mode also, but no Bottom placement mode

**Comment by ToddThomson** [comment]
@mdtauk @YuliKl Given both of your comments, I am rethinking this request/proposal.

Although the NavigationView has the visuals that I require ( primarily the navigation view menu list items ), it does not provide the placement properties that are required. In the general case, a ToolDockView would have Left, Right, Bottom ( and perhaps Tabbed/Top ). The NavigationView was also designed for a specific purpose and perhaps should not be changed if other, better control components would work.

When I look at the requirements for my ToolDockView it really is just a master detail 2 pane view. There are many ways that the visuals can be implemented.

My current ToolDockView was just a prototype so I think that I will move on to prototype revision 2 and rebuild it from scratch using a much simpler master-detail approach.

**Comment by kmgallahan** [comment]
This is turning into a similar request as #1473.

**Comment by ToddThomson** [comment]
@kmgallahan Perhaps now a bit more like #668 .

**Comment by YuliKl** [comment]
@ToddThomson do you feel we should keep this proposal on the books or close it?

Either way, I'm removing myself as the assignee because this won't be actionable by the WinUI team in the foreseeable future.

**Comment by ToddThomson** [comment]
@YuliKl I no longer feel that the NavigationView should be changed so that it meets my needs/requirements. I am in the process of converting my ToolDockView to utilize a simpler ( more concise ) master-detail pattern.

**Comment by ToddThomson** [comment]
@YuliKl I'm not sure if anyone would be interested, but here is what my solution was:

1. SplitPaneView Control. Like the SplitView/TwoPaneView, but with:
- Vertical and Horizontal orientation for the split. 
- The 2 content Panes can be ordered Pane1 - Pane2 or Reversed Pane2 - Pane1
- The Panes have settable Lengths
2. ToolbarNavView Control. Uses the SplitPaneView with a customized ListView based Toolbar in Pane1 and a ContentTemplate in Pane2.
- The Toolbar can be located: Top, Bottom, Left, Right

The solution is basically a very slim NavigationView. The problem with using the stock UWP controls was really the SplitView. There really is no reason that the UWP SplitView shouldn't have a Vertical and Horizontal Split. That should have been my original request/proposal! 

I will be open sourcing the UI controls once they are polished up a bit.

**Comment by ToddThomson** [comment]
<img width="440" alt="SplitPaneView" src="https://user-images.githubusercontent.com/918658/74062827-01b00b00-49a4-11ea-9c2d-e05d4c67c08d.png">
