### ISSUE TITLE
Applying NavigationView's style will result in menu items missing

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#1862]
**Describe the bug**

I copyed `NavigationView`'s [style](https://raw.githubusercontent.com/microsoft/microsoft-ui-xaml/master/dev/NavigationView/NavigationView.xaml) to App.xaml, build app, my `NavigationView` menu items are gone.
WHat's the right way to use `NavigationView`'s style.

**Steps to reproduce the bug**

1. Create a project with Windows Template Studio, it will use winui's `NavigationView`' automatically.
2. Copyed `NavigationView`'s [style](https://raw.githubusercontent.com/microsoft/microsoft-ui-xaml/master/dev/NavigationView/NavigationView.xaml) to App.xaml, build app.

**Expected behavior**

`NavigationView` menu items still exist, and apply changes.

**Screenshots**

![image](https://user-images.githubusercontent.com/14960168/72703826-a69fab00-3b91-11ea-81ed-8443adde5d74.png)

**Comment by ranjeshj** [comment]
NavigationView's style has recently changed from using ListView to ItemsRepeater. Can you check if the template you are using matches the WinUI package you are using ? If you are using master, try the pre-release package. If you are using the release package, use the template that has ListView in it.

**Comment by hupo376787** [comment]
Got it. I used pre-release, it works. Thx.
