### ISSUE TITLE
Access violation in TestAppCX 

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#1866]
**Describe the bug**
I'm getting Access violation at base.h:2088 when open pages in TestAppCX. Get this from any IVector.GetAt() call

**Steps to reproduce the bug**

1. Checkout master of winUI 
2. Open MUXControl.sln
3. Run TestAppCX for debug
4. Open TreeView test page

Got Access violation

**Version Info**
* master at https://github.com/microsoft/microsoft-ui-xaml/commit/e35343803779a885686d638b8fc8232b7b8deab5
* Windows 10 1909
* base.h was generated by C++/WinRT v2.0.191217.1
* Visual Studio Version 16.4.3

**Comment by StephenLPeters** [comment]
The TestAppCX isn't being used or maintained, we should probably delete it.

**Comment by ad1Dima** [comment]
StephenLPeters 
This also happens to my test project, where i refer to Microsoft.UI.Xaml.vcxproj

May be my environment is broken, but i cant understand

**Comment by ad1Dima** [comment]
It seems like VS update fixed this for me
