### ISSUE TITLE
ItemsRepeaterScrollHost returning invalid anchor in nested scenario 

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1867]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8557046/72782995-5ef44e80-3c79-11ea-9ca7-49005a403a9a.png)

Consider the above scenario with list of `TopicViews` containing list of `StoryView` in the code snippet below. Sometime ItemsRepeaterScrollHost.CurrentAnchor returns `StoryView`, instead of `TopicView` 

            <controls:ItemsRepeaterScrollHost  x:Name="ScrollHost">
                <ScrollViewer x:Name="ScrollViewer">
                    <controls:ItemsRepeater x:Name="ItemRepeater" ItemsSource="{x:Bind ViewModel.Topics}">
                        <controls:ItemsRepeater.ItemTemplate>
                            <DataTemplate x:DataType="viewModels:TopicViewModel">
                                <views:TopicView ViewModel="{x:Bind Mode=OneWay}" />
                            </DataTemplate>
                        </controls:ItemsRepeater.ItemTemplate>
                    </controls:ItemsRepeater>
                </ScrollViewer>
            </controls:ItemsRepeaterScrollHost>

TopicView.xaml

                <muxc:ScrollViewer x:Name="ScrollViewer">
                    <muxc:ItemsRepeater x:Name="CategoryItems" ItemsSource="{x:Bind ViewModel.Stories}">
                        <muxc:ItemsRepeater.ItemTemplate> 
                            <DataTemplate x:DataType="viewModels:StoryViewModel">
                                <local:StoryView ViewModel="{x:Bind Mode=OneWay}" />
                            </DataTemplate>
                        </muxc:ItemsRepeater.ItemTemplate>
                        <muxc:ItemsRepeater.Layout>
                            <muxc:StackLayout Orientation="Horizontal" Spacing="10" />
                        </muxc:ItemsRepeater.Layout>
                    </muxc:ItemsRepeater>
                </muxc:ScrollViewer>

**Steps to reproduce the bug**

The complete repo is at [ScrollHostApp](https://github.com/harvinders/ScrollHostApp).

Not easy to reproduce

1. make sure window size is small 
2. bring 3rd or 4th row in view
3. try scrolling that row horizontally and click on an item
4 If exception thrown, that means you have found the issue, and StoryView is returned.

**Expected behavior**

Only TopicView is returned as Anchor.

**Version Info**

NuGet package version: 

2.4.0-prerelease.200113001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@harvinders That is expected behavior. The anchor is picked based on which element is nearest to the anchor point (chosen using HorizontalAnchorRatio and VerticalAnchorRatio). If a nested item is closest to the anchor point, that can be chosen as well. If you are getting the inner element, you can walk up the tree to find the outer element parent to get what you need.

**Comment by harvinders** [comment]
@ranjeshj Thanks for pointing this out. Is this behaviour of CurrentAnchor documented somewhere? if not maybe we should.

**Comment by ranjeshj** [comment]
ScrollViewer/Scroller implement IScrollAnchorProvider to get this behavior which is documented here. https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.iscrollanchorprovider 
The feature is specific to anchoring elements during collection change, which we are trying to re-use for navigation back and forth.. but i agree samples here would be helpful.

**Comment by ranjeshj** [comment]
Turns out you have working code.. just missing a single line. 
 element.StartBringIntoView(new BringIntoViewOptions()
            {
                VerticalOffset = relativeVerticalOffset,
                **VerticalAlignmentRatio = 0**
            });

StartBringIntoView by default without any options just brings the item into view (somewhere in the visible area). If you set VerticalAlignmentRatio to 0, it will align the item to the top of the viewport and the offset will ensure that the element is offset by the same amount as before.
