### ISSUE TITLE
Dynamic width change is not working in Windows 10X

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1869]
It was working fine in Windows 10X 19531 version and windows 10, after upgraded to 19540 or above version, it is not reflecting in UI.

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_queries/edit/24632305/), which includes more details.

**Comment by StephenLPeters** [comment]
@TeaP fyi

**Comment by teaP** [comment]
The repro app is consuming the SDK version of TwoPaneView. I'm working with the owner to sort it out.
