### ISSUE TITLE
Should SelectionModel.SelectRangeFromAnchor clear existing selection?

### ISSUE THREAD

**Issue by grokys** [microsoft/microsoft-ui-xaml#1872]
Maybe I'm misunderstanding what `SelectionModel.AnchorIndex` and `SelectRangeFromAnchor` is intended for, but I'd assumed it was intended for situations where the user e.g. shift-clicks a list:

![uaZ3JerdH5](https://user-images.githubusercontent.com/1775141/72889402-e9878d00-3d0f-11ea-9687-16e97230b1a0.gif)

Usually in that situation, the shift-click resets the selection to be from `[Anchor..Click]`, however `SelectRangeFromAnchor` doesn't do this: if the selection range is smaller than an existing selection then the previously selected items outside the range remain selected. So currently we have to do:

```
var anchor = Selection.AnchorIndex ?? new IndexPath(0);
Selection.ClearSelection();
Selection.AnchorIndex = anchor;
Selection.SelectRangeFromAnchor(index);
```

Is this correct? Should the behavior of `SelectRangeFromAnchor` be changed? Should it have a new parameter, e.g. `bool resetSelection` added?

**Comment by ranjeshj** [comment]
This is the expected behavior. SelectionModel.Clear gets rid of the previous selection. There are similar cases where you want to not clear the selection in extended selection mode. Calling ClearSelection seems reasonable.

**Comment by grokys** [comment]
Calling `ClearSelection` isn't ideal because it will trigger two change notifications, but if this is by design I'm willing to accept it. Thanks @ranjeshj.
