### ISSUE TITLE
MenuFlyout not scaling properly with Windows Magnifier

### ISSUE THREAD

**Issue by chinwobble** [microsoft/microsoft-ui-xaml#1875]
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
<package id="Microsoft.UI.Xaml" version="2.3.191217003-prerelease" targetFramework="native" />
Windows Terminal version:  0.8.10091.0
```
# Steps to reproduce
- Open the new terminal
- press `Win + =` to open magnifier.exe
- press the + button to create a new tab in terminal 

# Expected behavior
the window should scale correctly when zoomed. Here is an example of what it should look like from Fluent Terminal
![image](https://user-images.githubusercontent.com/18226001/65818974-45f30800-e25a-11e9-995f-8355dff1049e.png)

# Actual behavior
The menu is scaled inappropriately 
![image](https://user-images.githubusercontent.com/18226001/65818955-03313000-e25a-11e9-9372-1e4cb0adc99f.png)

**Comment by StephenLPeters** [comment]
@DHowett-MSFT I would guess that this is a terminal app issue, what are your thoughts?

**Comment by DHowett-MSFT** [comment]
It is not a terminal app issue. We're using a standard `MenuFlyout`, but we're using it inside Xaml Islands. /cc @Austin-Lamb.

**Comment by Austin-Lamb** [comment]
Yep, I believe this is an issue another customer reported internally too - we're doing some double-scaling of the DPI somewhere, I think.  This will need WinUI 3 to fix, since it's in the core platform layer, so adding needs-winui-3 and putting it on the backlog.

**Comment by llongley** [comment]
I'm afraid I don't either.

**Comment by szilvasidave** [comment]
*bump*

Any news on this? Based on the amount of attached issues this seems like a major accessibility issue.
Basically anyone using an app with XAML Islands and needs a screen magnifier will experience this issue.

**Comment by zadjii-msft** [comment]
From the discussion I had with the WinUI folks internally, no one's quite sure when this got fixed in the Windows 11 timeframe. It's entirely possible that it was accidentally fixed by some totally unrelated bug fix.
