### ISSUE TITLE
Remove "#define __INTELLISENSE__" from CppWinRTIncludes.h once underlying issue with cppwinrt/msvc has been resolved

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#1877]
We hit an issue in MUX.dll after the build machines got updated to VS 16.4.3. The updated compiler contains a bug that is hit by C++/WinRT.

The cppwinrt Issue is described here:
[Visual Studio 2019 version 16\.4\.3 produces bad code gen · Issue 486 · microsoft/cppwinrt](https://github.com/microsoft/cppwinrt/issues/486)

To work around the issue we added "#define __INTELLISENSE__" to dev\inc\CppWinRTIncludes.h.

This was an effective workaround to avoid the msvc bug. However, we should remove it as soon as it is no longer necessary. We could easily end up getting into a weird situation when this __INTELLISENSE__ symbol has some other unexpected consequences.

**Comment by chingucoding** [comment]
It seems that the linked issue was fixed. Does this mean, that we can remove the defines now @kmahone ?

**Comment by kmahone** [comment]
> It seems that the linked issue was fixed. Does this mean, that we can remove the defines now @kmahone ?

Yes. We can remove it now.

**Comment by chingucoding** [comment]
Thanks for clarification, I'll create a PR for this then, if that's fine.
