### ISSUE TITLE
Narrator announces TextBox input incorrectly when mathematical operators are involved

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1879]
**Describe the bug**

**Steps to reproduce the bug**

1. Turn on Narrator and launch XAML Controls Gallery.
2. Activate a TextBox from home page.
3. E.g type  1+2+3 and observe the Narrator's description.

**Expected behavior**

Narrator should only announce entered text.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/73033553-3e520300-3df7-11ea-84e3-75566c7c74f4.png)

**Version Info**

Xaml Controls Gallery version 1.2.12.0

NuGet package version: 

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24650452)

**Comment by SavoySchuler** [comment]
@YuliKl We tested this and it appears to be an issue on TextBox. Any math operator will cause Narrator to read the whole number entered before the operator. 

E.g., I have "343" and type "+", Narrator will read "343".

I am not sure whether this is a bug or feature, but we will add it to the Framework Team's triage.
