### ISSUE TITLE
TabView should not allow Narrator users to deselect current tab

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1880]
**Describe the bug**

**Steps to reproduce the bug**

1. Turn on Narrator.
2. Launch XAML Controls Gallery.
3. Activate Tabview from All Controls Page.
4. Navigate to any tab and press caps+enter to select it now again caps+enter and observe. 

**Expected behavior**

Nothing should happen, the de-selection should be ignored.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/73034347-78bc9f80-3df9-11ea-89bb-c60176566a8d.png)

![image](https://user-images.githubusercontent.com/13142665/73034359-81ad7100-3df9-11ea-98e0-1d4e8b68548c.png)

**Version Info**

Xaml Controls Gallery version 1.2.12.0.

NuGet package version: 

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24663741)

**Comment by chingucoding** [comment]
I think this issue was fixed with the recent changes we made to the TabView automationpeer. This behavior is not reproducable in the MUXControlsTestApp anymore, so I think it's fine to close it now.

**Comment by chingucoding** [comment]
@StephenLPeters @ranjeshj FYI
