### ISSUE TITLE
Unable to increase the value of number box with a spin button when SpinButton Placement is set to Compact.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1881]
**Describe the bug**

**Steps to reproduce the bug**

1. Turn on Narrator.
2. Launch XAML Controls Gallery.
3. Activate NumberBox from WhatsNew Page.
4. Navigate to number box placed under header A number box with Spin button.
5. Ensure SpinButtonPlacement is set to Compact.
6. Now try to increase/decrease the value of number box with touchgestures.

**Expected behavior**

Narrator should set focus on spin buttons just like it does when SpinButton Placement is set to Inline.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/73034856-0b117300-3dfb-11ea-9093-de10e605ae3b.png)

**Version Info**

Xaml Controls Gallery version 1.2.12.0

NuGet package version: 

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24689832)

**Comment by SavoySchuler** [comment]
The proposed fix 1) not technically possible because we would need to move focus to the spin buttons which are in a popup - which we do not want to do, and 2) the NumberBox already supports other UIA patterns to be able to change the value.
