### ISSUE TITLE
Narrator's focus gets stuck on activating Adding new tab/Close tab button in TabView.

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1883]
**Describe the bug**

**Steps to reproduce the bug**

Prerequisite: 
* Turn on Narrator.
* Keep narrator in item mode.

Repro steps :
1. Launch XAML Controls Gallery.
2. Activate TabView from home page.
3. Navigate to "Add new Tab button", activate it and observe the Narrator's behavior.
4. Similarly, activate "close" button and observe.

**Expected behavior**

Narrator's focus should move to the next UI element after activating Adding new tab/Close tab button in TabView.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/73035143-01d4d600-3dfc-11ea-8481-f85de94f1aee.png)

**Version Info**

Xaml Controls Gallery version 1.2.12.0

NuGet package version: 

**Additional context**

Issue is with either tabview or list view.

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24727534)

**Comment by chingucoding** [comment]
@YuliKl Just to clarify, when the close button or the add tab button get's invoked, we should move the focus next focusable UI element? So in the case of the add button, it most likely would move the focus inside the content of the currently selected TabViewItem.

@StephenLPeters I would like to look into this.
