### ISSUE TITLE
GetAlphaMask() returns incorrect mask for shapes filled with XamlCompositionBrushBase, prevents drop shadow usage 

### ISSUE THREAD

**Issue by jesbis** [microsoft/microsoft-ui-xaml#1884]
**Describe the bug**
[`GetAlphaMask()`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.shapes.shape.getalphamask) seems to return an incorrect mask when shape is filled with a brush derived from [`XamlCompositionBrushBase` ](https://docs.microsoft.com/uwp/api/windows.ui.xaml.media.xamlcompositionbrushbase).

This causes the Windows Community Toolkit [`DropShadowPanel`](https://docs.microsoft.com/dotnet/api/microsoft.toolkit.uwp.ui.controls.dropshadowpanel?view=win-comm-toolkit-dotnet-stable) to not display any shadow for content filled with Acrylic, RadialGradientBrush, and any custom brushes (even if the CompositionBrush is just a CompositionColorBrush).

**Steps to reproduce the bug**

See example:
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3098

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18362)              | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**

Didn't test other element types (e.g. TextBlock) - they may have the same issue

**Comment by codendone** [comment]
Shape.GetAlphaMask() is created by XAML drawing the shape into a static bitmap.  The actual XamlCompositionBrushBase.CompositionBrush can't be used for this, so it gets drawn with the FallbackColor.  The default FallbackColor for XamlCompositionBrushBase is Transparent, so if the brush or the app doesn't set a different FallbackColor, the drawn shape in the AlphaMask will be completely transparent.  Setting, for example, FallbackColor = Colors.Green in the sample app's construction of the RadialGradientBrush in Ball.cs gets the shadow to render.

**Comment by jesbis** [comment]
Might it make the most sense to assume by default XCBB fills all pixels, and generate a solid mask whenever an XCBB **isn't** in fallback mode?

**Comment by codendone** [comment]
I don't think so.  If the FallbackColor is 50% alpha then shouldn't the mask ideally be 50% alpha?  The intention was for the mask to match the alpha of the real drawn element, and for XCBB we can only hope that the alpha in the FallbackColor is correct.

To provide more code details, GetAlphaMask uses the Print codepath to create the mask.  So whatever is seen when printing is what will be used for the mask.

**Comment by jesbis** [comment]
I have no data but it feels likely that XCBB's non-fallback overall alpha would be more likely to match XCBB.Opacity than XCBB.FallbackColor's alpha channel.

Neither approach is perfect but I guess matching printing makes sense.

Seems like we'd ideally want a way to tell the composition layer to handle mask (or shadow) generation itself based on a visual's actual rendered content? Would we be able to use any of the existing capture APIs for that or would it be too expensive, e.g. because it'd have to update every frame to catch updates to the brush?

**Comment by codendone** [comment]
We could potentially reimplement how the mask is generated by using visual capture.  In OS XAML, this would have the side-effect of the capture being at least one frame late (due to round-trip through DWM.exe), which means anything using the mask would be that frame (or two) late.  Maybe in WinUI we could get a synchronous API.

Or maybe we could reimplement the mask using CompositionVisualSurface, which didn't exist when the alpha mask feature was created.
