### ISSUE TITLE
Setting `MaximumRowsOrColumns` property of `UniformGridLayout` causes holes and crashes in ItemsRepeater.

### ISSUE THREAD

**Issue by MilesChing** [microsoft/microsoft-ui-xaml#1887]
**Describe the bug**

Setting `MaximumRowsOrColumns` property of `UniformGridLayout` causes holes and crashes in `ItemsRepeater`. Holes appear in the upper right corner when using the latest stable version `2.3.191211002` of `Microsoft.UI.Xaml.Controls` on Nuget. Sliding errors with the `ScrollViewer` occur as well. The application crashed directly when scrolling the `ScrollViewer` using the latest prereleased version `2.4.0-prerelease.200113001`.

**Steps to reproduce the bug**

The test code is as follows
```xaml
<!--MainPage.xaml-->
<Page
    x:Class="TestApplication.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestApplication"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Page.Resources>
        <!-- The Layout specifications used: -->
        <muxc:UniformGridLayout x:Name="UniformGridLayout"
                                MinRowSpacing="8" MinColumnSpacing="8"
                                MaximumRowsOrColumns="4"/>

        <!-- The DataTemplate used: CircularTemplate-->

        <DataTemplate x:Key="CircularTemplate" x:DataType="local:Bar">
            <Grid Background="Red"
                  Width="100"
                  Height="100">
                <TextBlock Text="{x:Bind str}" 
                           FontSize="20"/>
            </Grid>
        </DataTemplate>
    </Page.Resources>

    <ScrollViewer HorizontalScrollBarVisibility="Auto" 
        HorizontalScrollMode="Auto" 
        IsVerticalScrollChainingEnabled="False"
        MaxHeight="500">
        <muxc:ItemsRepeater
            ItemsSource="{x:Bind collection}"
            Layout="{StaticResource UniformGridLayout}"
            ItemTemplate="{StaticResource CircularTemplate}"
        />
    </ScrollViewer>
</Page>
```

```csharp
//MainPage.xaml.cs
using System;
using System.Collections.ObjectModel;
using Windows.UI.Xaml.Controls;

namespace TestApplication
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            for (int i = 0; i < 40; ++i)
                collection.Add(new Bar(i.ToString()));
        }

        public ObservableCollection<Bar> collection
            = new ObservableCollection<Bar>();
    }

    public class Bar
    {
        public Bar(string str) { this.str = str; }

        public String str;
    }
}
```

**Screenshots**

![a](https://user-images.githubusercontent.com/8838227/73132529-6d66af80-4057-11ea-98d7-9c8779997e0b.gif)

**Version Info**

Windows 10 18363.592

NuGet package version: 

- `Microsoft.UI.Xaml 2.4.0-prerelease.200113001`
- `Microsoft.UI.Xaml 2.3.191211002`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |  Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |   Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
Is this specifically when using MaximumRowsOrColumns? 
Which OS are you running on ? For this scenario to work downlevel, you will need to add [ItemsRepeaterScrollHost](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.itemsrepeaterscrollhost?view=winui-2.3), since ScrollViewer does not perform anchoring downlevel. ItemsRepeaterScrollhost is the interim solution until WinUI3 at which point it will not be needed.

**Comment by MilesChing** [comment]
> @MilesChing Is this specifically when using MaximumRowsOrColumns?
> Which OS are you running on ? For this scenario to work downlevel, you will need to add [ItemsRepeaterScrollHost](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.itemsrepeaterscrollhost?view=winui-2.3), since ScrollViewer does not perform anchoring downlevel. ItemsRepeaterScrollhost is the interim solution until WinUI3 at which point it will not be needed.

Yes and it don't happen when `MaximumRowsOrColumns` is not set.
I'm running the test code on version 1909. It seems that this version does not require an `ItemsRepeaterScrollHost`, and using it doesn't work.

**Comment by chingucoding** [comment]
I would like to look into this issue (feel free to assign this to me),
