### ISSUE TITLE
How to handle Reset notifications in SelectionModel

### ISSUE THREAD

**Issue by grokys** [microsoft/microsoft-ui-xaml#1889]
_(Opening this discussion here as requested in https://github.com/AvaloniaUI/Avalonia/pull/3470#issuecomment-578515248)_

Currently when the data source connected to a `SelectionModel` gets a [Reset](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedaction?view=netcore-2.0#System_Collections_Specialized_NotifyCollectionChangedAction_Reset) notification, it will lose the current selection. This is because `SelectionModel` only stores a list of selected ranges and not the selected items themselves, meaning that on reset the `SelectionModel` has no idea how the current selection that it has relates to the new data in the data source.

I'm not sure how much of a problem this will be in WinUI but in Avalonia this is likely to cause problems as DynamicData often [issues](https://github.com/reactiveui/DynamicData/wiki/Sorting#the-basics) [`Reset`](https://github.com/reactiveui/DynamicData/issues/74) notifications for large changes for performance reasons and we recommend using DynamicData for filtering, sorting and grouping. @ranjeshj [seems to think](https://github.com/AvaloniaUI/Avalonia/pull/3470#issuecomment-578515248) that this might be a problem in WinUI too.

> Aside: I don't 100% understand the need for `IKeyIndexMapping` in WinUI - is this because UWP doesn't handle reference equality the same as .NET? I'm not sure if we need this interface in Avalonia: usually the actual _items_ themselves will be the same object between resets. However I'll assume that this feature will only be enabled in WinUI for collections that implement IKeyIndexMapping

My evaluation is that there are probably 3 options here:

1. Don't try to maintain selection on `Reset` - tell users to avoid resetting their data sources. Need to investigate whether this is possible in all cases with DynamicData.
2. Maintain a single selected item on `Reset` by storing the `SelectedItem` in a field
3. Keep a list of all selected items at all times

Option 2 may be a decent compromise that works for 90% of use-cases.

Option 3 is ideal in terms of behavior but has a significant overhead in the case of large selections. Would probably need to be turned on with a flag in `SelectionModel`?

Related: https://github.com/microsoft/microsoft-ui-xaml/issues/1645

**Comment by ranjeshj** [comment]
IKeyIndexMapping is designed for sorting and filtering scenarios. It is used to uniquely identify items for diffing before/after the reset. Yes - there is no concept of default hashcode in unmanaged code and also you can have duplicates in the list. When IKeyIndexMapping is implemented by the ItemsSource ItemsRepeater can keep the same containers and animate them during a reset. However, it does not look like selection state is currently maintained in that case.
