### ISSUE TITLE
Start menu [NavigationView]: hover opening animation can prevent the click event

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#1890]
**Describe the bug**
Since the introduction of the function (the NavigationView of the start menu is open with the hovering), I noticed that the animation can prevent the click.

**Steps to reproduce the bug**
1. Open the start menu
2. Hover over 'start/stop' for example and click before the animation of the shell view is finished

**Expected behavior**
The click event should be saved and executed, if the animation is finish.

**Video**
![startmenu](https://user-images.githubusercontent.com/10946850/73196908-c0606580-4130-11ea-88f1-13c81190d40e.gif)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@jp-weber can you share a video of the issue ?

**Comment by jp-weber** [comment]
@ranjeshj 
I edited my post and add the video for the issue.

**Comment by ranjeshj** [comment]
@jp-weber, This seems to be feedback for the start menu and unrelated to WinUI, can you please file an issue through the [feedback hub app](https://www.microsoft.com/en-us/p/feedback-hub/9nblggh4r32n?ocid=9nblggh4r32n_ORSEARCH_Bing&rtc=1&activetab=pivot:overviewtab) ?

**Comment by bschoepke** [comment]
Yea the start menu implementation is custom, pre-dating NavigationView
