### ISSUE TITLE
PersonPicture Empty String x:Bind ProfilePicture causes other binding issues in controls in same ListBox item

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#1895]
**Describe the bug**
Other bindings in items in the same ListBox control as a PersonPicture break or behave inconsistently--values seem to come from other items in the same ListBox.

**Steps to reproduce the bug**
Value of "" (empty string) for QuoteCreatorImage causes some of the other controls in the ListBox to show values from other items in the ListBox or blank. Interesting thing to note is it also only affects controls above the PersonPicture. See screenshots.
```
<PersonPicture 
    ProfilePicture="{x:Bind QuoteCreatorImage, Mode=OneWay}"
    DisplayName="{x:Bind QuoteCreatorName, Mode=OneWay}"/>
```

PersonPicture after "Creator" TextBlock, all bindings above it are blank/broken:
![image](https://user-images.githubusercontent.com/3663297/73225628-99069a00-412a-11ea-9a14-1f772b0602db.png)

PersonPicture after "Expired about _ ago" TextBlock, all bindings above it are blank/broken:
![image](https://user-images.githubusercontent.com/3663297/73225531-44fbb580-412a-11ea-8754-7ae7ca45371a.png)

**Expected behavior**
Value of "" should not cause binding issues, and control should fall back to DisplayName

**Screenshots**

**Version Info**

NuGet package version: 
2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19551)              | Yes   |
| Insider Build (19041)              | Yes   |
| November 2019 Update (18363)  | Yes     |
| November 2019 Update (18362)  | Yes      |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Comment by ranjeshj** [comment]
@myokeeh can you please add a repro app ?

**Comment by myokeeh** [comment]
@ranjeshj that will be a little difficult to do at this time. However, i stumbled upon this: The unwanted behavior occurs with `x:Bind`, but not `Binding`

Works fine:
```
<PersonPicture 
    ProfilePicture="{Binding QuoteCreatorImage, Mode=OneWay}"
    DisplayName="{Binding QuoteCreatorName, Mode=OneWay}"/>
```
Has binding issues:
```
<PersonPicture 
    ProfilePicture="{x:Bind QuoteCreatorImage, Mode=OneWay}"
    DisplayName="{x:Bind QuoteCreatorName, Mode=OneWay}"/>
```

**Comment by ranjeshj** [comment]
@danzil  FYI

**Comment by danzil** [comment]
Hi there, I don't see why such a simple x:Bind expression will have any different behavior as {Binding}. Would it be easy for you to share a small repro project we could try? Thanks!

**Comment by danzil** [comment]
@myokeeh if you'd be able to send me a quick repro, I could have a look and see what this issue is about. By just looking at the code and markup you shared, I don't see any reason why this would behave that way.
