### ISSUE TITLE
Proposal: Allow ListView and GridView to TAB.

### ISSUE THREAD

**Issue by Elmarcotoro** [microsoft/microsoft-ui-xaml#1898]
The Gridview and ListView do not appear to allow the user to effectively Tab through the collection.
The ListView does allow Tab to move to controls on the same row, but it will not Tab to the next row. Instead, when you attempt to TAB to the next row the ListView loses focus and focus instead moves onto the next control in the visual tree of the page.

# Proposal: Allow ListView and GridView to TAB.

## Rationale
Users of LOB apps tend to work with a lot of data and need to be effecient.
* TAB allows them to move through a collection quickly with moving their hands from the keyboard.
* Users find it inconsistent to be able to TAB through the first row on the ListView but then find when they TAB to the next row in the list that the ListView has lost focus.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to have a more conventional experience when working through data collections

## Important Notes
![image](https://user-images.githubusercontent.com/42846535/73261354-cf442800-41c3-11ea-8376-673a4710ef4d.png)

**Comment by ranjeshj** [comment]
@Elmarcotoro  <ListView TabNavigation="Local"> should get you the behavior of tab moving to the next item. The reason for this not being the default is that you can have a large number of items in the list and with this option, you will have to tab through the entire list of items (potentially 1000s) before being able to tab out of it. Instead the default is to use tab to get in and out of the list and arrow keys to navigate up and down the list.
