### ISSUE TITLE
EventTriggerBehavior does not work in release mode on WinUI:NavView ItemInvoked event

### ISSUE THREAD

**Issue by sibille** [Microsoft/microsoft-ui-xaml#19]
We found an issue using the EventTriggerBehavior on the ItemInvoked event of Navigationview from WinUI. It works fine in Debug Mode, but doesn't work when compiled in Release.

Using the EventTriggerBehavior on the Loaded event works fine in debug and release though.
Could you have a look to see what is causing this?

Repro project:
[BehaviorReleaseBug.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2643506/BehaviorReleaseBug.zip)

(X-Ref Issue on our side https://github.com/Microsoft/WindowsTemplateStudio/issues/2774)

**Comment by sibille** [comment]
Also linking to the issue on the behaviour sdk where Pedro has given some insights.
X-Ref: https://github.com/Microsoft/XamlBehaviors/issues/142

**Comment by jevansaks** [comment]
Looks like the issue is known to be a problem with .NET Native because the metadata is not included unless the app author manually requests the reflection metadata to be included in their app. There's nothing that MUX can do here except help educate folks.
