### ISSUE TITLE
ItemsRepeater does not display items in order

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1906]
**Describe the bug**

I have noticed that ItemsRepeater sometime does not order the items properly. On my PC I am able to reproduce it using following steps. I have created a [sample repo](https://github.com/harvinders/ItemsRepeaterAnimationApp) 
**Steps to reproduce the bug**

1. Open the app and make sure only two columns are displayed
2. Observe the order of items. 
3. Maximise the app, the order of the displayed elements are changed.

**Expected behavior**

The order should not change

**Screenshots**

## Before
![image](https://user-images.githubusercontent.com/8557046/73354521-03b20400-42ea-11ea-9946-8113fa840ffc.png)
## After
![image](https://user-images.githubusercontent.com/8557046/73354045-ddd82f80-42e8-11ea-8907-4891e856d7c3.png)

**Version Info**

NuGet package version: 
2.4.0-prerelease.200113001

Could also reproduce with 2.3.191211002

## Before 
![image](https://user-images.githubusercontent.com/8557046/73354785-a9fe0980-42ea-11ea-8f88-1a3452de204a.png)

## After 
![image](https://user-images.githubusercontent.com/8557046/73354820-bd10d980-42ea-11ea-9cd5-f31ecf51b20d.png)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
@ranjeshj fyi

**Comment by harvinders** [comment]
@ranjeshj and sometimes an item is repeated too, though the count of items remain same. In the screenshot below Item 1 is repeated twice.

![image](https://user-images.githubusercontent.com/8557046/73498139-82a15c80-4410-11ea-9c52-ac3732ea0c87.png)

**Comment by ranjeshj** [comment]
Interesting. looks like some issue with recycling.

**Comment by ranjeshj** [comment]
@havinders, Unfortunately i won't get a chance to debug this further until early next week. I can give you an update once I understand the issue a little better. I appreciate your patience.

**Comment by ranjeshj** [comment]
@havinders  If I change the data template to the following, the order looks correct when going full screen.
<Button Content="{x:Bind Name}" Width="100" Height="100"/>

which gave me the impression that there is something wrong with the ViewModel's binding.

On looking closer, your StoryView should be implementing INotifyPropertyChanged and when ViewModel is changing, it should raise PropertyChanged like so.

   public sealed partial class StoryView : UserControl, System.ComponentModel.INotifyPropertyChanged
    {
        private StoryViewModel viewModel;
        public StoryViewModel ViewModel
        {
            get
            {
                return viewModel;
            }
            set
            {
                viewModel = value;
                if (PropertyChanged != null)
                {
                    PropertyChanged(this, new PropertyChangedEventArgs("ViewModel"));
                }
            }
        }

Also, you need your binding in StoryView.xaml needs to be OneWay. The default is one time.

 <TextBlock
            Grid.Row="1"
            x:Name="Title"
            Text="{x:Bind ViewModel.Name, Mode=OneWay}"

After fixing these two issues, I see that on going full screen the order is correct. The bindings were not firing correct which gave the impression that the order was wrong. Can you make these changes and see if it affects https://github.com/microsoft/microsoft-ui-xaml/issues/1954 ?

**Comment by harvinders** [comment]
Yes, this seems to work. I am going to spend some time understanding your logic here, I have never seen  `PropertyChanged`  raised for `ViewModel` from a `View` before. Is it because of recycling in `ItemsRepeater`. Would I have to do same changes if it was a GridView or ListView? Apologies @ranjeshj, If I am asking stupid questions.

However this did not help with #1954.

**Comment by ranjeshj** [comment]
The behavior should be the same for ListView/GridView. The problem is that ViewModel property gets assigned by the x:Bind on StoryView, however that does not trigger the binding in StoryView to re-evaluate because the property is not INPC. There is a mainpage.g.cs file that is generated by the markup compiler in the output folder where you can see the hookup (you can set breakpoints there to see if the ViewModel property is hit and when it gets updated)
