### ISSUE TITLE
Loading 'Geometry' from Resources in UWP throws an Exception during run-time

### ISSUE THREAD

**Issue by vlad-gregor** [microsoft/microsoft-ui-xaml#1909]
**Describe the bug**
Loading 'Geometry' from Resources in UWP throws an Exception of type "Windows.UI.Xaml.Markup.XamlParseException" during run-time. Exception message:
"The text associated with this error code could not be found. Failed to assign to property 'Windows.UI.Xaml.Shapes.Path.Data'. [Line: 23 Position: 1]"

**Steps to reproduce the bug**

1. Create a new blank UWP application.
2. Update your MainPage.xaml to contain the following XML:
```
<Page.Resources>
        <GeometryGroup x:Key="Geometry">
            <RectangleGeometry Rect="0 ,0 100 ,100"></RectangleGeometry>
            <EllipseGeometry Center="150, 50" RadiusX="35" RadiusY="25"></EllipseGeometry>
        </GeometryGroup>
    </Page.Resources>

    <Canvas x:Name="canMain" >
        <Path Fill="Yellow" Stroke="Blue" Margin="5" Canvas.Top="10" Canvas.Left="10"
Data="{StaticResource Geometry}">
        </Path>
        <Path Fill="Green" Stroke="Blue" Margin="5" Canvas.Top="150" Canvas.Left="10"
Data="{StaticResource Geometry}">
        </Path>
    </Canvas>
```

**Expected behavior**
No exception is thrown.

**Version Info**
I use Visual Studio 2019 Professional v. 16.4.3

I use Windows 10 Pro, I keep it updated.

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |Yes|

**Additional context**

The issue described also here:
https://stackoverflow.com/questions/59909032/load-geometry-from-resources-in-uwp?noredirect=1

Thank you.

**Comment by codendone** [comment]
Same issue as #1874.
