### ISSUE TITLE
NumberBox's Input TextBox's InputScope should be set to "Number"

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#1912]
# Proposal: Set NumberBox's Input TextBox's InputScope="Number"

The current NumberBox ControlTemplate does not set the "InputBox" TextBox's InputScope. This means the system will handle it using defaults. It's better to add InputScope="Number" in XAML to ensure the system will handle numerical entry better within the NumberBox. This is especially helpful for virtual keyboards on the desktop and mobile.

## Summary

In the code [here](https://github.com/microsoft/microsoft-ui-xaml/blob/49d724e1d9f77d9c29a86bc09b749c4ec2c8dd7c/dev/NumberBox/NumberBox.xaml#L88)
```XAML
<TextBox x:Name="InputBox"
    Grid.Column="0"
    Header="{TemplateBinding Header}"
    HeaderTemplate="{TemplateBinding HeaderTemplate}"
    PlaceholderText="{TemplateBinding PlaceholderText}"
    contract7Present:SelectionFlyout="{TemplateBinding SelectionFlyout}"
    SelectionHighlightColor="{TemplateBinding SelectionHighlightColor}"
    TextReadingOrder="{TemplateBinding TextReadingOrder}"
    PreventKeyboardDisplayOnProgrammaticFocus="{TemplateBinding PreventKeyboardDisplayOnProgrammaticFocus}"
    contract7Present:Description="{TemplateBinding Description}"/>
```

Simply add a new property to the TextBox

```XAML
InputScope="Number"
```

This is documented in UWP for the TextBox [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.inputscope) and generically [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.inputscope) and don't forget the [InputScopeNameValue Enum](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.inputscopenamevalue?view=netframework-4.8)

## Rationale

Better handing of the NumberBox by the system especially with virtual keyboards.

**Comment by robloo** [comment]
@SavoySchuler @teaP This is an easy one that is a nice-to-have for the NumberBox. If you agree with the concept, I would like to submit the PR myself.

**Comment by mdtauk** [comment]
The one issue about setting it to number, is when the common scenario is to do calculations which require operators and brackets - so this InputScope should be overridable.

**Comment by robloo** [comment]
@mdtauk I don't think this is an issue. I checked and the standard number keyboard has mathematical operators and parenthesis as well. This is true for the touch keyboard on mobile devices at least -- I can't seem to get the keyboard to change on Windows 10 desktop (which means it would show the full keyboard anyway).

```XAML
<TextBox InputScope="Number"/>
```
![number](https://user-images.githubusercontent.com/17993847/73479804-e450c080-4355-11ea-9eab-4e7b5a43e0b8.png)

See:
https://docs.microsoft.com/en-us/windows/uwp/design/input/use-input-scope-to-change-the-touch-keyboard

**Comment by StephenLPeters** [comment]
Great suggestion! @robloo I'll assign the issue to you and you can submit your fix? :)

**Comment by robloo** [comment]
Sure! Will be a few days before I get around to it, but will be happy to submit the PR.

**Comment by SavoySchuler** [comment]
I believe this is not a proposal, but a bug as NumberBox's spec notes here that "Number" should be used as the InputScope of NumberBox: https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/NumberBox/NumberBox.md#input-scope

@teaP if there was a reason for this change that I forgot to note in the spec, please let me know. 

Thanks for filing this @robloo!

**Comment by robloo** [comment]
I should get to this next week. @teaP please let me know if there was a reason it wasn't already done.

**Comment by chingucoding** [comment]
@robloo Would you like to add the inputscope or would you mind me creating a PR for this quickly?

**Comment by robloo** [comment]
@chingucoding Thanks for the reminder. I would rather keep this assigned to me and I'll finish it soon. It's an easy one but it will force me to setup the dev environment and read through the contribution docs. This will make future contributions easier.

**Comment by chingucoding** [comment]
Okay, sure @robloo . If you need help with setting up the environment or if you have troubles compiling, feel free to ask :)
