### ISSUE TITLE
Shouldn't UniformGridLayout.MaximumRowsOrColumns be a DependencyProperty

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#1918]
The UniformGridLayout.MaximumRowsOrColumns is a normal property. Shouldn't this be a DependencyProperty so it can support databinding?

**Comment by robloo** [comment]
If it's not, it certainly should be:

https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.uniformgridlayout.maximumrowsorcolumnsproperty?view=winui-2.3

**Comment by ranjeshj** [comment]
@sonnemaf looks like it already is ? Are you seeing otherwise ?

**Comment by StephenLPeters** [comment]
From the idl file:
Int32 MaximumRowsOrColumns{ get; set; };
static Windows.UI.Xaml.DependencyProperty MaximumRowsOrColumnsProperty{ get; };  
Looks fine to me.

**Comment by robloo** [comment]
If this really is an issue, I'm curious if it occurs during only x:Bind or Binding. It might be a bug in code and that would help indicate where to look.

**Comment by sonnemaf** [comment]
Sorry, my mistake. I just assumed it wasn't a DP because I got a strange Error when databinding it to the Length of an array. This problem is not associated with the UniformGridLayout. You get this message also on a TextBlock.Text property.

```
<TextBlock Text="{x:Bind Columns.Length}" />
```

The Columns property is an Array of integers. 

```
private int[] Columns = new int[5];
```

![image](https://user-images.githubusercontent.com/9335559/73647996-ec25a300-467c-11ea-9f16-237b934d04fd.png)

I'm not sure why this 'Derived classes must provide an implementation' goes off. There are many workarounds which I could use. For instance adding an extra ColumnLength property like below.

```
private int ColumnsLength => Columns.Length;
```

You can close the issue. Sorry for not investigating it enough before I created it.
