### ISSUE TITLE
Question: Will WinUI Desktop fully support UWP's Badge Notifications API?

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#1919]
UWP has a nice [Badge Notifications API](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/badges) which adds a badge to an app's tile in the Start Menu and to the app's taskbar button:
![image](https://user-images.githubusercontent.com/1398851/73558177-f1070e80-4452-11ea-99b5-fe8ddedd974a.png)
(Example UWP app showing taskbar app button badge.)

Using the same API in a MSIX packaged desktop app adds the badge to the app's tile in the Start Menu, but there is no additional badge in the app's taskbar button. Will WinUI Desktop apps using UWPs Badge API be able to show a badge in the taskbar just like UWP apps?

**Comment by ranjeshj** [comment]
@marb2000 as FYI

**Comment by andrewleader** [comment]
Hey Felix, thanks for asking this. We're investigating and will get back to you!

**Comment by andrewleader** [comment]
Hey Felix,

For Win32 apps using MSIX, we disabled the UWP badges from appearing on taskbar, since Win32 apps [can use ITaskbarList](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist3-setoverlayicon) to create custom taskbar "badges".

I'm aware this is definitely confusing though, and might not be what you'd expect!

Have you tried the ITaskbarList API? Are you still interested in instead using the UWP badges? We appreciate your feedback and it helps us prioritize what to work on next!

**Comment by Felix-Dev** [comment]
Hi @andrewleader 

thanks for getting back to me this quickly :)

Yes, I'm aware of ITaskbarList API and WPF also makes creating an own taskbar badge quite easy with the [TaskbarItemInfo](https://docs.microsoft.com/en-us/dotnet/api/system.windows.shell.taskbariteminfo?view=netframework-4.8) API. Two points why I would still welcome the team to add full UWP Badge support to non-UWP projects:

- With UWP, I just have to call the API and it works. I don't have think about creating an own icon overlay (the badge), draw a number aligned with the overlay (the badge content) and then how to apply it to the base icon in the taskbar. In UWP, all I have to do is specify I want to draw a number and then pass the number to the API. The system will take care of the rest for me. (For Win32, instead of drawning a number onto my custom badge, I could alternatively provide a set of images and then specify which one to use as the overlay.)
- Windows UI needs to be aligned as best as best as possible across the different native app frameworks. Adding UWP Badge support to Win32/WPF apps enables these apps to provide a native Windows 10 UI and goes one step further into unifying the app experience. We've seen work done for this in the Windows Shell by adding native Windows 10 toast notification support to Win32 apps. It would be great if this would be extended to the Badge API of the Shell as well! 

WinUI Desktop is about enabling Win32 apps to ship with the modern Windows 10 UI/UX. Thus, Win32 apps should have full access to the new Windows 10 Shell elements introduced by UWP to help in unifiying the app experience across the different Windows App models (Win32 and UWP).

The icing on the cake would be if you guys would also enable current Desktop Bridge apps (MSIX packaged apps) to provide a native Windows 10 Shell experience to their users. I'd be fine with this support only arriving for WinUI Desktop apps though as I can imagine your team being quite busy with the upcoming launch of Windows 10X.

If enabled for current MSIX packaged desktop apps, developers should be able to either use the existing ITaskbarList API (or equivalent in WPF) to create custom badges if needed, or use the UWP Badge API to create a familiar Badge experience for Windows 10 users.

**Comment by andrewleader** [comment]
Thanks Felix, that's excellent feedback! Really well articulated. We'll let you know if/when we have any updates.

**Comment by Felix-Dev** [comment]
@andrewleader

I tested out an MSIX packaged desktop app on the new Windows 10X emulator to see how badge suport is currently looking like and I'm happy to report that badges show up in both the taskbar and and the new Start menu!
![10X-shell-badge](https://user-images.githubusercontent.com/1398851/74386650-caec5180-4df6-11ea-80cf-0f8acb70ea1b.png)
and a closer look:
![10X-shell-badge-2](https://user-images.githubusercontent.com/1398851/74386670-dc355e00-4df6-11ea-9411-f9326231458d.png)
(TestAppWpf.... is the name of my Win32 app packaged as an MSIX)

I will use full badge support in the 10X shell as another argument why it would be nice to have the same level of support for our MSIX desktop apps/WinUI Desktop apps on Windows 10 😁

**Comment by Felix-Dev** [comment]
@marb2000 @andrewleader This seems like a fitting issue for Project Reunion (extended to all Windows apps - UWP and Win32).

**Comment by marb2000** [comment]
@Felix-Dev, yep, this sounds like a Windowing project Reunion thing.
