### ISSUE TITLE
[Holographic] Search icon (magnifying glass) sometimes hidden in the NavigationView

### ISSUE THREAD

**Issue by jskollin** [microsoft/microsoft-ui-xaml#1932]
**Describe the bug**
Search icon (magnifying glass) sometimes hidden in the NavigationView

**Steps to reproduce the bug**
1. Open an application with a NavigationView in Left DisplayMode, with a search box.
2. Resize the application to make it slightly smaller.
3. Open the NavigationView so that it is expanded.
4. Close the NavigationView so that it is compact.
(steps 2-4 may need to be repeated in order to see the behavior)

**Expected behavior**
The magnifying glass icon should be visible in the compact NavigationView (however, it is not).

**Screenshots**
N/A, since working on a HoloLens.

**Version Info**
Windows Holographic: 10.0.18362.1024

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@jskollin can you please attach a picture showing the issue ? Also, are you using WinUI2.3 or 2.4 prerelease ? There are several updates to NavigationView in 2.4 pre-release so it would be great to know if this issue is in the pre-release.

**Comment by jskollin** [comment]
This is what we see (no magnifying class)
![HololensBug](https://user-images.githubusercontent.com/18020494/73791545-89adcf00-4770-11ea-933a-f7a56f70a1fe.PNG)


This is what is expected (magnifying glass):
![ExpectedHololens](https://user-images.githubusercontent.com/18020494/73791667-c5489900-4770-11ea-9909-d2016a844269.PNG)

**Comment by ranjeshj** [comment]
@jskollin which version of the WinUI nuget package are you using ?

**Comment by jskollin** [comment]
WinUI2.2

**Comment by ranjeshj** [comment]
@ojhad can you take a look and see if it repro's on the pre-release after the updates ?

**Comment by ojhad** [comment]
@jskollin I am unable to reproduce this issue. 
Is it possible for you to upload a project where I can reproduce this issue?
Also, can you try and update your nuget package and see if that resolves the issue?
