### ISSUE TITLE
Color Picker Clipped Text with Text Scaling 

### ISSUE THREAD

**Issue by maygchen1997** [microsoft/microsoft-ui-xaml#1934]
When using Color Picker with text scalled ~200-225%, the More/Less button is clipped but still clickable.

**Comment by StephenLPeters** [comment]
@maygchen1997 If you have a picture for the issue that would be great!

**Comment by StephenLPeters** [comment]
@llongley fyi

**Comment by maygchen1997** [comment]
Unfortunately I don't, but @llongely looked at this with me and was able to repro it.

**Comment by llongley** [comment]
Here's a picture:

![ColorPickerMoreButtonClipped](https://user-images.githubusercontent.com/18177025/73787667-9f130100-4750-11ea-8f30-323d3dffd9b2.png)

**Comment by llongley** [comment]
Note that you need to do *text* scaling, not *display* scaling to repro the issue.  I imagine the issue is that the "more" text block is a set size, such that scaling it up causes the text to no longer fit.

**Comment by chingucoding** [comment]
> Note that you need to do _text_ scaling, not _display_ scaling to repro the issue. I imagine the issue is that the "more" text block is a set size, such that scaling it up causes the text to no longer fit.

Yes, the height of the ToggleButton is hardcoded, resulting in text clipping:

https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/ColorPicker/ColorPicker.xaml#L332
