### ISSUE TITLE
"Cannot deserialize XBF metadata" crash when derived control hides base property

### ISSUE THREAD

**Issue by lostmsu** [microsoft/microsoft-ui-xaml#1935]
**Describe the bug**
I have a custom control derived from `ItemsControl`, and implementing its own `ItemsSource` property, and in Debug trying to instantiate it causes

> Cannot deserialize XBF metadata property list as ‘ItemsSource’ was not found in type ‘HelixToolkit.UWP.ItemsModel3D’. [Line: 0 Position: 0]’

**Steps to reproduce the bug**
1. Clone https://github.com/helix-toolkit/helix-toolkit
2. Open `Source\HelixToolkit.SharpDX.sln`
3. Switch target platform to x64
4. Select `Examples\UWP\SimpleDemo` as startup project
5. Launch

**Expected behavior**
No crash

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by danzil** [comment]
@lostmsu to help us troubleshoot, does this work in Release builds?

**Comment by lostmsu** [comment]
@danzil , when I switch to Release, the issue goes away.

**Comment by danzil** [comment]
@lostmsu thanks for checking! I believe @RealTommyKlein would know if this was fixed recently or if it's a new issue.
