### ISSUE TITLE
Question: [CalendarDatePicker looks and feels disabled when displayed from ContentDialog]

### ISSUE THREAD

**Issue by raymartf31** [microsoft/microsoft-ui-xaml#1938]
CalendarDatePicker feels disabled when shown from a ContentDialog.

![image](https://user-images.githubusercontent.com/14161056/73811807-756fdd80-4815-11ea-8302-8ebbe8b2652a.png)

Here's the code:
 
```xaml
 <CalendarDatePicker
                        x:Name="DatePickerCtlFrom"
                        Grid.Row="2"
                        Grid.Column="1"
                        Style="{StaticResource CheckSearchControl}"
                        MinDate="{Binding MinDate}"
                        MaxDate="{Binding MaxDate}"
                        Date="{Binding FromCalendarDateSelected, Mode=TwoWay}"
                        Visibility="{Binding IsCalendarSelected}"
                        IsEnabled="{Binding IsCalendarEnabled}">
                        <interactivity:Interaction.Behaviors>
                            <core:EventTriggerBehavior
                                EventName="DateChanged">
                                <core:InvokeCommandAction
                                    Command="{Binding Path=FromCalendarDatePickerCommand}" />
                            </core:EventTriggerBehavior>
                        </interactivity:Interaction.Behaviors>
                    </CalendarDatePicker>
```

It didn't look that way before until today, not sure if this is a bug or is there a new way - correct way to fix this. Btw, this happens in several other dialog, if the CalendarDatePicker is used in a normal page, it looks okay.

Thank you. Appreciate your help.

Regards,
Raymart

**Comment by robloo** [comment]
Please see my comment [here](https://github.com/microsoft/microsoft-ui-xaml/issues/1916#issuecomment-580434515) and try adding `BasedOn="{StaticResource DefaultCalendarDatePicker}"` to your Style.

```XAML
    <Style x:Key="CalendarStyle"
           TargetType="CalendarDatePicker"
           BasedOn="{StaticResource DefaultCalendarDatePicker}">
    </Style>
```

There is also an added level of complexity with ContentDialog styling that I don't fully understand. I expect all of this to be simplified with WinUI 3.0 (hopefully).

**Comment by raymartf31** [comment]
Thanks for your reply robloo. I'll look into this, Btw, I created a test project and tried to reproduce this issue I'm having, but I wasn't able to do so, the CalendarDatePicker in ContentDialog looks okay with the test project. So maybe some updates from WinUI conflicts with our current code, I'll investigate further and will post my updates. Thanks,
