### ISSUE TITLE
UWP TextBox will Fill of the Page if they display text with too many combining marks

### ISSUE THREAD

**Issue by lindexi** [microsoft/microsoft-ui-xaml#194]
**Describe the bug**

When we use the TextBox to display text with too many combining marks that the TextBox will fill with the Page and then it can fix after we focus the TextBox.

**Steps to reproduce the bug**

1. Create a TextBox in xaml
1. Display text with too many combining marks

xaml:

```
    <Grid>
        <TextBox x:Name="Txt" HorizontalAlignment="Center" VerticalAlignment="Center"></TextBox>
    </Grid>
```

code:

```
        public MainPage()
        {
            this.InitializeComponent();

            Txt.Text = new string('\u0483', 550);
        }
```

Then you can see the Screenshots after you run the application.

**Expected behavior**

At startup, the TextBox fills the entire page.

**Screenshots**

![](http://image.acmx.xyz/lindexi%2F20191179354379)

**Version Info**

NuGet package version: 

Microsoft.NETCore.UniversalWindowsPlatform 6.1.9

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |  Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

See https://github.com/dotnet/wpf/issues/244

**Comment by jevansaks** [comment]
Good find. I've filed an [internal issue](https://microsoft.visualstudio.com/OS/_workitems/edit/20223830) to track and will report back when we have more information.

**Comment by lindexi** [comment]
Thx for @jevansaks but I can not open the link : https://microsoft.visualstudio.com/OS/_workitems/edit/20223830

**Comment by jevansaks** [comment]
Yeah, that’s to be expected since I filed the bug in the internal database where the team that owns this particular area can track it. I’ll post status changes back here.
