### ISSUE TITLE
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.449

### ISSUE THREAD

**Issue by klettier** [microsoft/microsoft-ui-xaml#1940]
**Describe the bug**

My windows search is not working anymore and when I'm trying to rebuild my index I have the two errors bellow in event viewer

```
Faulting application name: SystemSettings.exe, version: 10.0.18362.449, time stamp: 0x066bf1a5
Faulting module name: SettingsHandlers_Cortana.dll, version: 10.0.18362.1, time stamp: 0x308f304d
Exception code: 0xc0000005
Fault offset: 0x0000000000006b15
Faulting process id: 0x2888
Faulting application start time: 0x01d5dc328c3e93a1
Faulting application path: C:\Windows\ImmersiveControlPanel\SystemSettings.exe
Faulting module path: C:\Windows\System32\SettingsHandlers_Cortana.dll
Report Id: 12351bc6-5336-46b8-8cdb-cd142d442ee0
Faulting package full name: windows.immersivecontrolpanel_10.0.2.1000_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: microsoft.windows.immersivecontrolpanel
```

```
Faulting application name: SystemSettings.exe, version: 10.0.18362.449, time stamp: 0x066bf1a5
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.449, time stamp: 0xb90db728
Exception code: 0xc0000409
Fault offset: 0x000000000013e780
Faulting process id: 0x1b68
Faulting application start time: 0x01d5dc31df7fb449
Faulting application path: C:\Windows\ImmersiveControlPanel\SystemSettings.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: ba11ffd7-604b-4a82-8550-b2dca985e8c7
Faulting package full name: 
Faulting package-relative application ID: 
```

**Steps to reproduce the bug**

1. Go to **Indexing options** -> Advanced options
2. Click **Rebuild**

**Expected behavior**

* No error in event viewer

**Screenshots**

![image](https://user-images.githubusercontent.com/3425823/73861173-ef678d00-483c-11ea-87d1-1350030c464b.png)

**Version Info**

* Windows 10 Pro x64 1903

NuGet package version: 

* Microsoft.UI.Xaml 10.0.18362.449

**Comment by ranjeshj** [comment]
@klettier can you provide a crash dump or callstack when running settings under the debugger. Unfortunately this issue is not actionable without more information.

**Comment by klettier** [comment]
@ranjeshj sure, could you guide me on how to get those information?

**Comment by kmgallahan** [comment]
This was a widespread Windows 10 issue that was already resolved yesterday.

I'm doubting the Settings issue is related to anything WinUI specific, but rather the app was just misbehaving due to the search problem.

**Comment by ranjeshj** [comment]
@klettier, you can create a registry entry to collect local dumps described [here](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps )

**Comment by klettier** [comment]
as @kmgallahan mentioned the search issue disappeared and I cannot reproduce the error ```Windows.UI.Xaml``` anymore.

Cheers
