### ISSUE TITLE
Invalid TemplateBinding Error in Style causes crash and cryptic message 'No matching constructor found on type X'

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#1943]
**Describe the bug**
See #1289, [As described here](https://github.com/microsoft/microsoft-ui-xaml/issues/1289#issuecomment-582615776)

I've had this happen in a few instances, but this is the most recent one:

> I had an invalid template binding name used in property as part of a control template in the default style for a templated control. So I get an error at runtime of `No matching constructor found on type X` in the app unhandled exception handler (even with all the exceptions on); the stack trace is all just the error reporting stack. (I can even hit a breakpoint I set in the constructor, so the message makes no sense). Sometimes you get a line number, but that's actually indexed into the resource dictionary file instead (which is the only hint of what's wrong). Instead it should be saying like "Invalid resource of name X not found in file Y. [line ...]" to make it super clear to the developer where to go look.

(I believe similar cryptic errors can occur in other places with static resource references as well. Sometimes, they provide a better error message, but not always?)

**Steps to reproduce the bug**

1. Paste the following into XAML Studio or in VS and run:

```xml
<Page
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Page.Resources>
        <Style TargetType="AutoSuggestBox">
            <Setter Property="VerticalAlignment" Value="Top" />
            <Setter Property="IsTabStop" Value="False" />
            <Setter Property="TextBoxStyle" Value="{StaticResource AutoSuggestBoxTextBoxStyle}" />
            <Setter Property="UseSystemFocusVisuals" Value="{ThemeResource IsApplicationFocusVisualKindReveal}" />
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="AutoSuggestBox">
                        <Grid x:Name="LayoutRoot" BorderBrush="Red" BorderThickness="1">

                            <VisualStateManager.VisualStateGroups>
                                <VisualStateGroup x:Name="Orientation">
                                    <VisualState x:Name="Landscape" />
                                    <VisualState x:Name="Portrait" />

                                </VisualStateGroup>

                            </VisualStateManager.VisualStateGroups>

                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                            </Grid.ColumnDefinitions>

                            <Grid.RowDefinitions>
                                <RowDefinition Height="*" />
                            </Grid.RowDefinitions>

                            <TextBox x:Name="TextBox"
                                Style="{TemplateBinding TextBoxStyle2}"
                                PlaceholderText="{TemplateBinding PlaceholderText}"
                                Header="{TemplateBinding Header}"
                                Width="{TemplateBinding Width}"
                                Description="{TemplateBinding Description}"
                                ScrollViewer.BringIntoViewOnFocusChange="False"
                                Canvas.ZIndex="0"
                                Margin="0"
                                DesiredCandidateWindowAlignment="BottomEdge"
                                UseSystemFocusVisuals="{TemplateBinding UseSystemFocusVisuals}" />

                            <Popup x:Name="SuggestionsPopup">
                                <Border x:Name="SuggestionsContainer">
                                    <ListView x:Name="SuggestionsList"
                                        Background="{ThemeResource AutoSuggestBoxSuggestionsListBackground}"
                                        BorderThickness="{ThemeResource AutoSuggestListBorderThemeThickness}"
                                        BorderBrush="{ThemeResource AutoSuggestBoxSuggestionsListBorderBrush}"
                                        DisplayMemberPath="{TemplateBinding DisplayMemberPath}"
                                        IsItemClickEnabled="True"
                                        ItemTemplate="{TemplateBinding ItemTemplate}"
                                        ItemTemplateSelector="{TemplateBinding ItemTemplateSelector}"
                                        ItemContainerStyle="{TemplateBinding ItemContainerStyle}"
                                        MaxHeight="{ThemeResource AutoSuggestListMaxHeight}"
                                        Margin="{ThemeResource AutoSuggestListMargin}"
                                        Padding="{ThemeResource AutoSuggestListPadding}" />
                                </Border>
                            </Popup>

                        </Grid>

                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </Page.Resources>

    <Grid Padding="40">
        <AutoSuggestBox/>
    </Grid>
</Page>
```
2. App will crash and provide the error message on restart.

**Note the invalid Template Binding `TextBoxStyle2`.**

**Expected behavior**
Not crash/better error message about source of problem.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.191129002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19555)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@danzil Is it possible to catch this issue at compile time ?

**Comment by danzil** [comment]
Yes, I think Alan plans to make some of these scenarios raise compile time errors. I can't say at this time when will this be available. We're 100% focused on getting WinUI 3 out the door at this point.
