### ISSUE TITLE
Setting NavigationView.Header = null does not remove it anymore

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1947]
**Describe the bug**

It is possible to remove the header of the NavigationView by setting `AlwaysShowHeader="False"`. However, this does not work in the minimal mode. If one wants to remove the header then you need to set `Header=null`. Till version 2.4.0-prerelease.191217001, it was possible to set the `Header = null` and get rid of it. However, in subsequent releases it is no longer possible and breaks existing apps.

Interestingly in latest insider build, setting `Header=null` hides it.

**Steps to reproduce the bug**

Please find repo app [here ](https://github.com/harvinders/NavigationHeaderTest) for the reference.
1. Build the app 
2. Reduce the width to reach the minimal mode
3. There is vacant space for header

**Expected behavior**

Setting the `Header=null` should allow us to get rid of the Header. This functionality is also [used](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/projectTypes/navigationpane.md#navigationviewheaderbehavior) by Windows Template Studio 

**Screenshots**

2.4.0-prerelease.191217001 | 2.4.0-prerelease.200203002
------------ | -------------
![image](https://user-images.githubusercontent.com/8557046/73922815-dc78b980-491d-11ea-912a-f3dd4513984a.png)| ![image](https://user-images.githubusercontent.com/8557046/73922684-af2c0b80-491d-11ea-9966-6686242fd5cf.png)
 
If the app decide to extend into the titlebar, there would be a white space left in minimal mode.

**Version Info**

NuGet package version: 2.4.0-prerelease.200203002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19555, 200127-0900)              | No   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by StephenLPeters** [comment]
@ojhad FYI, Yulia is investigating.

**Comment by ranjeshj** [comment]
@ojhad can you please take a look ? Is it possible that this behavior might have changed with the recent NavigationView refactor.

**Comment by harvinders** [comment]
@ranjeshj @ojhad @YuliKl 
According to the latest community call, new navigation view is going to be out with WinUI 2.4. Given, that this issue is still not addressed, it may break many existing application, especially those build using WTS and using this behaviour. 

If this issue is not to be addressed, then please provide us with alternative.

**Comment by ranjeshj** [comment]
@harvinders, This is what I see for the repro app with the[ latest pre-release build.](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.4.0-prerelease.200322001)

When the window is wide.
![image](https://user-images.githubusercontent.com/28935693/77857821-c1efed80-71b4-11ea-8c2a-793466bf4ec3.png)

When the window is narrow.
![image](https://user-images.githubusercontent.com/28935693/77857838-db913500-71b4-11ea-859e-ca7e742519ab.png)

**Comment by harvinders** [comment]
@ranjeshj 
Interesting I tested it on 1803 and this is what I see.
![image](https://user-images.githubusercontent.com/8557046/77864420-1f973f00-7274-11ea-9c7c-d39f4b3692fd.png)

I can't imaging this is going to be OS specific. Anyway, I would test it on the latest insider build later today and update my comments.

**Comment by ranjeshj** [comment]
@harvinders The OS version is less likely to make a difference. Can you make sure you are using the  latest pre-release version of the microsoft.ui.xaml nuget package ([this one](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.4.0-prerelease.200322001)) ? The repro app is using an older one, so you will need to update it.

**Comment by harvinders** [comment]
@ranjeshj 
Yes I am using the latest pre release version.

**Comment by harvinders** [comment]
@ranjeshj, I have tested it on the latest windows 10 insider preview and I don't see this issue. @sibille has also found it to be not an issue on 1909. 

I have also tested it on another 1803, and I could reproduce this issue. Maybe, now if someone can independently verify it on 1803, we can know it is only happening in 1803.
