### ISSUE TITLE
FontVariants.Superscript only supports certain character

### ISSUE THREAD

**Issue by DZetko** [microsoft/microsoft-ui-xaml#1957]
**Describe the bug**
When using FontVariants.Superscript in Run in XAML, only some characters are superscripted. Namely, numbers and the character _n_ for example, but not other characters (_x_, _q_, _f_, ...).

**Steps to reproduce the bug**
When using this code in my XAML view file, the _x_ stays inline with the 10 (10x).
`<TextBlock>Velocity: 10<Run Typography.Variants="Superscript">x</Run></TextBlock>`

**Expected behavior**
When using _x_ within Run I expect it to be superscripted in a way in which _n_ is.

**Screenshots**
![Wrong](https://user-images.githubusercontent.com/8233943/74101566-841f0300-4b3b-11ea-90b4-5c7664082b1d.png)

![Correct](https://user-images.githubusercontent.com/8233943/74101573-8c773e00-4b3b-11ea-85af-692862bec2ab.png)

**Version Info**
WinUI: v2.3.191211002
OS: Windows 10 Pro 1903
IDE: Microsoft Visual Studio Professional 2019, v16.4.2

NuGet package version: 
Microsoft.UI.Xaml 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by codendone** [comment]
This is weird. I repro the issue on the latest version of Windows and on RS4, so it appears this has been around for a while and still exists.

The font impacts this. The Segoe UI font showing proper superscript only for lowercase 'i' and 'n', along with the 0-9 digits. Arial and Times New Roman don't show superscript for any letters.

I don't know why this is happening, and I'm following up with some text experts for their ideas.

**Comment by JohnnyWestlake** [comment]
> This is weird. I repro the issue on the latest version of Windows and on RS4, so it appears this has been around for a while and still exists.
> 
> The font impacts this. The Segoe UI font showing proper superscript only for lowercase 'i' and 'n', along with the 0-9 digits. Arial and Times New Roman don't show superscript for any letters.
> 
> I don't know why this is happening, and I'm following up with some text experts for their ideas.

Likely because that Typography.Superscript doesn't force rendering superscript characters - it only enables support for superscript characters the font itself actually declares as superscript variants. Arial and Times New Roman don't actually have superscript or subscript support inside their fonts, where as Segoe UI does for all numbers and i & n. 

Same at the DirectWrite level underneath (which makes sense given that's what it uses).


So it's technically correct behaviour at a font level - you're asking for the Typographic Superset feature that the font doesn't actually support

**Comment by codendone** [comment]
Thanks @JohnnyWestlake, you are exactly correct.  The text dev I checked with provided a similar description:

> There’s a difference between "real" superscript (invoking the sups typographic feature) and "fake" superscript (reducing the font size and moving the text up off the baseline). The Typography.Variants property is invoking a typographic feature, which is the superior approach in terms of typographic quality/legibility, but depends on font support. A font may provide superscript variants for only some characters, not at all.
>
> When you select superscript in many editors, what you’re getting is "fake" superscript, in which it just scales the text and bumps it up off the baseline. This works regardless of the character and font, but is not as legible as superscript glyphs provided by a font. DirectWrite doesn't have a feature to do fake superscript.

As noted above, I've submitted a change to the Typography.Variants documentation to briefly mention that this depends on support in the font.

**Comment by codendone** [comment]
Thanks @DZetko for raising this issue. With the documentation updated, I'm closing this issue.
