### ISSUE TITLE
Back button shows incorrect background color on hover

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#196]
**Describe the bug**

Back button's hover background should be the same as the hamburger button's.

**Steps to reproduce the bug**

1. Start an app with NavigationView
2. Move cursor to hover over the pane toggle (hamburger button)
3. Now move cursor to hover over back button

**Expected behavior**

Both buttons should show the same color on their hover backplate.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/51347502-1cd87180-1a55-11e9-8914-608f82df6268.png)

**Version Info**

NuGet package version: 

Current prerelease version

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   | Yes   |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by KevinTXY** [comment]
Was this resolved already? I'm unable to reproduce - both the back button and navigation menu give hover values of 53, 53, 53.
![Untitled](https://user-images.githubusercontent.com/21269445/58361082-0bf39e80-7e41-11e9-8d08-ec69b34c490a.png)

**Comment by YuliKl** [comment]
Indeed this appears to have been fixed. At least, I'm no longer seeing the issue in the Controls Gallery. @ojhad may have fixed in this while correcting some HC styles.

The Search button still looks off, but that's a separate issue.
