### ISSUE TITLE
IsTitleBarAutoPaddingEnabled of NavigationView not working on Windows 10X Emulator

### ISSUE THREAD

**Issue by JustinXinLiu** [microsoft/microsoft-ui-xaml#1964]
**Describe the bug**
The `IsTitleBarAutoPaddingEnabled` property of `NavigationView` is not working on the Windows 10X Emulator but working fine on desktop.

**Steps to reproduce the bug**

1. Create an empty app and then place a `winui:NavigationView` in it. 
2. Enable custom title bar.
`CoreApplication.GetCurrentView().TitleBar.ExtendViewIntoTitleBar = true;`
2. Run the app on desktop and you will see there's a clear gap (normally 32epx) in between the top of the window and the `NavigationView`, thanks to the `IsTitleBarAutoPaddingEnabled` property being set to `true` by default.
3. However, now run the same app on the Windows 10X Emulator, you will see there's no gap and the `NavigationView` is drawn into the title bar.

**Expected behavior**

The same gap should be preserved for the Windows 10X Emulator.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.0-pre

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19563)              | Yes |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |
| Dual screen                         | Yes    |

**Additional context**

**Comment by ranjeshj** [comment]
@Austin-Lamb Is this a known issue with CoreApplicationView on 10X ?

**Comment by rudyhuyn** [comment]
This is a known problem, which is not related to NavigationView but to the title bar., `CoreApplicationViewTitleBar->IsVisible` returns False + `CoreApplicationViewTitleBar->Height` returns 0 when `ExtendViewIntoTitleBar = true`, it's currently under investigation by the team in charge.

**Comment by pratikone** [comment]
no longer applicable
