### ISSUE TITLE
WinUI 3.0 Alpha (February 2020) w/ WebView2 🚀👩‍💻🎉

### ISSUE THREAD

**Issue by adambarlow** [microsoft/microsoft-ui-xaml#1965]
# WinUI 3.0 Alpha (February 2020) w/ WebView2
As mentioned in the recent [community call](https://github.com/microsoft/microsoft-ui-xaml/issues/1857) **we now have a WinUI 3.0 Alpha available w/ Chromium-based Microsoft Edge WebView2**!

Please note that WinUI 3.0 Alpha is a very early prerelease and has lots of known issues and missing functionality, so it isn't ready for production apps. Future previews and the first stable version of WinUI 3 in 2020 will add support for everything outlined in the [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md).

In particular if you don't see an API in the [WebView2 API spec](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/WebView2/WebView2_spec.md) and it is existing functionality of the current WebView, it is likely planned to be included on the base WinRT object, whose API is likely to closely match the current [ICoreWebView2 interface](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2).

Feedback on WebView2 can be posted as comments to this issue or alternatively on the [WebView2 proposal](https://github.com/microsoft/microsoft-ui-xaml/issues/1658).

## Installation info

For installation info and known issues see:

[**WinUI 3.0 Alpha (February 2020)**](https://docs.microsoft.com/uwp/toolkits/winui3/)

There's a super-short survey with the download link - we'd love to know more about how you're interested in using WinUI.

Please try out the Alpha, let us know what you think and open issues if you run into any bugs that aren't listed already!

## What's next?

As outlined in the [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) we're hard at work getting WinUI ready for open source development, plus working toward a more complete preview, .NET 5 support, and more!

**Comment by weitzhandler** [comment]
Are .NET Core 3, C#8 and there newer csproj type ready?

**Comment by mdtauk** [comment]
Is WebView2 the only change, is there a fuller changelog available somewhere?

What progress is there with Win32 runtime support with WinUI 3.0 XAML UI?

**Comment by adambarlow** [comment]
@mdtauk 
The Feb 2020 alpha refresh includes all of the work since our last release in Nov. Although WebView2 is the biggest new feature, a number of other fixes have been made to increase stability and to prepare for open source. Progress was made on Win32 runtime support, however, it was not complete enough that we recommend additional self-hosting exploring of this functionality at this point in time.

**Comment by mdtauk** [comment]
> @mdtauk
> The Feb 2020 alpha refresh includes all of the work since our last release in Nov. Although WebView2 is the biggest new feature, a number of other fixes have been made to increase stability and to prepare for open source. Progress was made on Win32 runtime support, however, it is not yet complete enough that we recommend additional self-hosting / exploring of this functionality at this point in time.

Thank you for the reply.  Good to know things are happening.  Once the thing has been open sourced, change logs will become the norm :)

**Comment by adambarlow** [comment]
Yes, they will be very easy to produce and peruse as well!

**Comment by danzil** [comment]
@weitzhandler Support for .Net 5 and SDK-style projects is not yet ready. We're currently working on this as we speak.

**Comment by nabilahmed739** [comment]
@adambarlow with WebView2 can a Progressive Web App (PWA) be installed or rather can service worker registration?
The scenario is to run a PWA application inside a WebView2 in a WPF app.
Reasons for not wrapping it in a UWP could be:

- App needs to start and communicate with third party console apps or windows services (In UWP there is a restriction for such communication within the app package)
- Install app for at system level so all users can use (Plus avoid all the UWP sideloading and remote deployment overhead)
- Access device features like fielesystem without need for defining restricted capabilities, etc..

**Comment by vascofernandes** [comment]
I ma not able to run a WinUI3 UWP app with WebView2 v0.9.430. 

The app just crashes.

https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.430

**Comment by adambarlow** [comment]
@vascofernandes we did not test with this version of the WebView2 nuget package (as it wasn't released yet). Please try version 0.8.355. Also please open a new issue so we can discuss there.

@nabilahmed739 the goal is to have a WPF element as well. So you would use that element and not the WinUI version for WPF apps.

**Comment by michael-hawker** [comment]
@adambarlow looks like this link to the interface is 404ing now?

@azchohfi want to summarize your findings from moving the Monaco WebView wrapper over to the WebView2 alpha here?

**Comment by azchohfi** [comment]
PR is here:
https://github.com/hawkerm/monaco-editor-uwp/pull/32

1) A few events are missing that Monaco uses are: NewWindowRequested, DOMContentLoaded.
2) The worst part was the missing AddWebAllowedObject method. I had to implement an equivalent system using WebMessages, promisses and async/await.
3) There is a bug that prevented me from templating the control, since the timings for the OnApplyTemplate of the WebView2 are not correct (GetTemplateChild inside OnApplyTemplate throws an exception). I worked around it by manually creating the WebView2 control inside the custom control's Loaded event.
4) The control doesn't support the ms-appx-web or ms-appx protocol, so I had to do this to set the UriSource:
```cs
_view.UriSource = new Uri(@"file:///" + (await StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///Monaco/MonacoEditor.html"))).Path);
```
and also changed the html files I had inside the package to point to "./" instead of "ms-appx-web:///".

**Comment by adambarlow** [comment]
@azchohfi I've updated the link to the CoreWebView2 interface in the OP. Your issues 1 and are covered there and therefore should be available once we are able to dot into the CoreInterface (hopefully in the next preview release). On your issue 3, are you trying to template WebView2 or trying to use it inside the template for another control?
 
On #4 we plan to add support for local content it didn't make it to Alpha though. Thank you for the early feedback.

**Comment by hawkerm** [comment]
@azchohfi @adambarlow issue 2 should be the [`AddRemoteObject`](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2#addremoteobject) from the core interface, eh?

**Comment by azchohfi** [comment]
> On your issue 3, are you trying to template WebView2 or trying to use it inside the template for another control?
I'm trying to use it inside the template of another control.

**Comment by azchohfi** [comment]
@hawkerm Yes, but I have no idea how that will be mapped to a .Net type. I don't think it will.

**Comment by adambarlow** [comment]
@hawkerm yes AddRemoteObject is correct.

**Comment by JensNordenbro** [comment]
Hi!

Will the .Net5 support for WinUI3 be cross platform or Windows-only?

**Comment by weitzhandler** [comment]
> Will the .Net5 support for WinUI3 be cross platform or Windows-only?

It'll be Windows only, but you'll be able to use the [Uno Platform](https://bit.ly/2Viimjx) to make your WinUI app run on Android, iOS, Mac and as a website (WASM).

**Comment by JensNordenbro** [comment]
Ok ;
 
Will the .NET 5 support at least be able to do what follows: 
1. dotnet new winui3   // or similar, I am just mimcin .  
2. dotnet publish -r win-x64 
3. without having Visual Studio installed ?
 
Just like it is for wpf, winforms, asp.net on .net core 3.x !  

That is, the .net core sdk style is used but with the difference that the source code for the UWP engine is not disclosed and Uno is a separate set of sdks and project file definitions and the only thing in common is WinUI xaml and backing C#-classes for the definitions.

**Comment by michael-hawker** [comment]
@JensNordenbro I don't have any of those .NET 5 answers; not sure why you pinged me specifically. I maintain the Windows Community Toolkit. 

Pinging @ryandemopoulos to help direct this WinUI 3 question. 🙂

**Comment by JensNordenbro** [comment]
Hi @michael-hawker, it was because you profil suggest you work at Microsoft. Weitzhandler who kindly answered seems to work at Uno. I hope for ryamdelopolus then.

**Comment by weitzhandler** [comment]
@JensNordenbro lol, I don't work for either, I'm just an enthusiastic user.

**Comment by JensNordenbro** [comment]
Ok @weitzhandler ;) 

I got the impression that Uno uses Xamarin.Forms underneath with som renderers  for WebAssembly and that the solutions presented where tied to the full Visual Studio. 

I know from before that Xamarin.Forms is possible to build using CLI-only if one omitts the Android and IOS parts. Do you know if the same applies for Uno? (It relates to my question above).

**Comment by weitzhandler** [comment]
> I got the impression that Uno uses Xamarin.Forms underneath with som renderers for WebAssembly and that the solutions presented where tied to the full Visual Studio.

It doesn't. For WASM it uses Mono, for Android and iOS, it uses Xamarin.Android and Xamarin.iOS respectively.

> Do you know if the same applies for Uno?

I'm sorry, I don't. I can only guess it's probably supported, because of the above, and the WASM project is an ASP.NET Core project.

**Comment by JensNordenbro** [comment]
Yes @weitzhandler , that could be it! 

I checked out Uno, it has recently gotten "dotnet new"-templates to do what I want for webassembly targets. Although it feel to ugh to rely on a smaller consultancy firm for cross platform. Microsoft buy these guys ;) Perfect complement to Xamarin!

**Comment by weitzhandler** [comment]
@JensNordenbro
Read [this](https://platform.uno/blog/announcing-uno-platform-2-0/) article. They have tools to generate templates from cmd or vsix.

**Comment by koenvd** [comment]
Hi

I created a very basic UWP app with a WebVIew2 control on the MainPage. 

When setting the `UriSource` it apperars that for some URL's (like http://www.google.com)  the webview doesn't become visible. However for other URL's it does work (eg http://www.bing.com). 

Based on the requests it's doing it looks like the webview is fully active but just does not become visible. I already tried to set the `UriSource` at different moments in the `Page` lifetime but couldn't make it work.

Not sure if anyone might have noticed this is as well? Or what might be going on ... 

Also let me know if I need to create a specific issue for this: Thanks already!

**Comment by codendone** [comment]
@koenvd Do you also see this problem if trying to navigate to those URL's directly in the Edge Beta browser?  I don't repro this issue.  How recent is your install of Edge Beta?

Since you can also repro the issue outside of WinUI, please log your issue in the Edge WebView Feedback project here:  https://github.com/MicrosoftEdge/WebViewFeedback/issues/

**Comment by koenvd** [comment]
@codendone I didn't see the issue when navigating to those URL's directly in (latest) Edge Beta.   However I uninstalled the beta and installed the stable version (81.0.416.68 (Official build) (64-bit)) and now everything started working! It looks great!! 

Thanks for the support!

**Comment by phraemer** [comment]
Any word on when we'll see the next Alpha of `WebView2`?

**Comment by adambarlow** [comment]
@phraemer, the latest improvements will be coming in the Preview 1 release of WinUI 3 that is going to release for BUILD 2020.

**Comment by phraemer** [comment]
Great news @adambarlow , thanks!

**Comment by dstaley** [comment]
I also want to echo the experience that @koenvd had. I had the latest Edge Canary and Dev installed, and my WebView2 components wouldn't render correctly. Uninstalling both Canary and Dev and installing Stable fixed the issue.

**Comment by mqudsi** [comment]
Is there some resource on migrating from WebView2 in WinUI 3.0 Feb 2020 Alpha to WinUI 3.0 Preview 1? 

`UriSource` is gone, `WebView2.ExecuteAsync(@$"window.location = ""{url}"";")` throws an exception, `webview.NavigateToString($"<meta http-equiv='refresh' content='0; URL='{url}' />");` refuses to work with a `file:///` path (exception about loading local files), and even though it *appears* to work even though ultimately nothing is loaded if using the same approach with `ms-appx:///Assets/...`.

**Comment by Felix-Dev** [comment]
Now that WinUI 3.0 Preview 1 has been released I think we can close this issue in favor of https://github.com/microsoft/microsoft-ui-xaml/issues/2472.
