### ISSUE TITLE
WebView2 not loading local app package file 

### ISSUE THREAD

**Issue by mykebates** [microsoft/microsoft-ui-xaml#1967]
**Describe the bug**
Not sure if I have goofed something up in my setup or not... but I cannot seem to get WebView2 to load a file from the app package. Setting the UriSource to a web url local/remote works just fine.

But when trying to load an html file from the root of the project "/index.html" the screen stays blank and the NavigationCompleted event never fires.

**Steps to reproduce the bug**
Start a blank WinUI 3 project.
Install Microsoft.Web.WebView2 nuget package

Set controls namespace
xmlns:controls="using:Microsoft.UI.Xaml.Controls"

Add WebView2 in XAML
<controls:WebView2 UriSource="ms-appx-web:///index.html"/>

**Expected behavior**
Expect the index.html file to be loaded.

**Version Info**
NuGet package version: 
WinUI Version: 3.0.0-alpha.200210.0
WebView2 Version: 0.8.355

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            | YES   |
| October 2018 Update (17763)        |  |
| April 2018 Update (17134)          |   |
| Fall Creators Update (16299)       |  |
| Creators Update (15063)            |  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | YES  |
| Mobile                   |   |
| Xbox                      |   |
| Surface Hub          |   |
| IoT                         |   |

**Comment by ranjeshj** [comment]
@adambarlow @codendone does WebView2 support URIs into the app package ?

**Comment by codendone** [comment]
WebView2 _will_ support that, but ms-appx-web:/// and ms-appx-data:/// support is not yet implemented.

**Comment by codendone** [comment]
The internal task to implement this is https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/22121393.

**Comment by jabak** [comment]
Does webview2 support Uri's like ms-appx:///test.html or file:///C/temp/test.html or even ms-appx:///Assets/mypdf.pdf

I've not been able to load any local file using any variant of the above.

**Comment by mqudsi** [comment]
I had alpha 1 working with `file:///` for local resources (after resolving a `ms-appx:///` url to a `file:///` via the `StorageFile` API) but with preview 1 I cannot get a local file to load via any means.

**Comment by jabak** [comment]
Great! Good to know that I'm not the only one seeing this behaviour in preview 1. I guess we'll have to wait for the next update then.

**Comment by adambarlow** [comment]
@codendone , which changes might have caused the local file loading to no longer function?

**Comment by mqudsi** [comment]
@adambarlow fyi I filed a full issue for that in MicrosoftEdge/WebViewFeedback here: https://github.com/MicrosoftEdge/WebViewFeedback/issues/212#issuecomment-634195158

**Comment by codendone** [comment]
@mqudsi Is this still not working for you?  I see local files working fine in a Preview1 UWP with what sounds like the same approach you're using:

```
var storageFile = await Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///Assets/SimplePage.html"));
this.webview.Source = new Uri(storageFile.Path);
```

**Comment by jabak** [comment]
@codendone You are right. Resolving the path as shown in your sample actually works. But loading local files by the following approach doesn't work:

this.webView.Source = new Uri("ms-appx:///Assets/SimplePage.html");
or
this.webView.Source = new Uri("file:///C:/temp/SimplePage.html");
or
this.webView.Source = new Uri("file:///C/temp/SimplePage.html");
or
this.webView.Source = new Uri("ms-appdata:///local/SimplePage.html");
or
this.webView.Source = new Uri("ms-appdata://local/SimplePage.html");

My impression was that if you can load a file in Edge/Chromium then WebView2 should be able to load the file as well.

**Comment by codendone** [comment]
@jabak Thanks for providing those explicit examples.

- ms-appx:// and ms-appdata:// are not supported at all yet. This is being tracked both for WinUI3 ([internal workitem](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/22121415)) and for core Edge WebView2 (https://github.com/MicrosoftEdge/WebViewFeedback/issues/37).
- file:/// works, but only for files which the app has access to.  UWP applications have restricted file system access, which is largely just the app package files and temp files. As a result, most files, including anything in C:\temp, would not be accessible.

Supporting access to app files such as with ms-appx:/// is something we believe is required, and is something we're planning for. We could easily support this for just the WebView2.Source property, but expect that this type of protocol also needs to work from within the WebView2 (in the html/js), and therefore we are working towards that more complete solution.  If having just WebView2.Source support would significantly help until we have the complete support, though, please let us know so we can consider adding this interim support.

**Comment by phraemer** [comment]
>  but expect that this type of protocol also needs to work from within the
WebView2

Yep. Absolutely needed for us.

**Comment by jabak** [comment]
@codendone For me support for the source property would be adequate right now. But as I've only just started testing various things, including webview2, for my upcoming project I'm in no hurry. So I would say it's significant for me. The more complete solution whenever that will be ready to ship gets my vote :o)

**Comment by codendone** [comment]
@phraemer Thanks for confirming. We'll keep that full support as required.

@jabak Thanks for your feedback!

**Comment by oSethoum** [comment]
Is this issue solved, or should i go with Electron ?

**Comment by codendone** [comment]
@oSethoum Yes, with the latest preview you can now load files from the app directory using [SetVirtualHostNameToFolderMapping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.774.44). Note that this isn't using the old "ms-appx:///" and similar custom protocols, and is instead using virtual host names to map to the file location.

Here's an example:

```
    var core_wv2 = myWebview.CoreWebView2;
    if (core_wv2 != null)
    {
        core_wv2.SetVirtualHostNameToFolderMapping(
            "appassets.example", "assets",
            Microsoft.Web.WebView2.Core.CoreWebView2HostResourceAccessKind.Allow);

        myWebview.Source = new Uri("https://appassets.example/myVideo.mp4");
    }
```

**Comment by oSethoum** [comment]
@codendone  Thank you sir.

**Comment by georgsku** [comment]
Is there a way to load files from the app package? Or does SetVirtualHostNameToFolderMapping only enable loading files from the app directory?

**Comment by codendone** [comment]
@georgsku Loading from the app's resources.pri isn't something we have direct support for currently. I think it might be possible to use the [CoreWebView2.WebResourceRequested](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=webview2-dotnet-1.0.774.44) event, lookup/load the resource into a stream, and return that in the response. We haven't tried that, though.

**Comment by shelllet** [comment]
```
auto core_wv2 = VELK_WebView().CoreWebView2();
if (core_wv2)
{
	core_wv2.SetVirtualHostNameToFolderMapping(
		L"appassets.example", L"C:/Users/admin/doc",
		winrt::Microsoft::Web::WebView2::Core::CoreWebView2HostResourceAccessKind::Allow);

	VELK_WebView().Source(Uri(L"https://appassets.example/README.md"));


	//	VELK_WebView().Source(Uri(L"file:///C:/Users/admin/doc/README.md"));
}
```
in c++/winrt core_wv2 always null.

**Comment by codendone** [comment]
@shellet You need to EnsureCoreWebView2Async() first before accessing the CoreWebView2.

**Comment by shelllet** [comment]
> @shellet You need to EnsureCoreWebView2Async() first before accessing the CoreWebView2.

![image](https://user-images.githubusercontent.com/16729017/111949286-63392780-8b1b-11eb-8f73-493a548e2204.png)

**Comment by codendone** [comment]
Closing this issue, since I think it has been addressed.

Summary (and corrections):
* It is no longer the plan for WebView2 to support ms-appx-web:/// and ms-appx-data:///. Instead of using these proprietary protocols the [SetVirtualHostNameToFolderMapping](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_3?view=webview2-1.0.902.49&preserve-view=true&viewFallbackFrom=webview2-1.0.781-prerelease#setvirtualhostnametofoldermapping) API is recommended. See MicrosoftEdge/WebViewFeedback#37.
* You can load files from the app directory using [SetVirtualHostNameToFolderMapping](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_3?view=webview2-1.0.902.49&preserve-view=true&viewFallbackFrom=webview2-1.0.781-prerelease#setvirtualhostnametofoldermapping). Note that this isn't using the old "ms-appx:///" and similar custom protocols, and is instead using virtual host names to map to the file location. Here's an example:

```
    await myWebview.EnsureCoreWebView2Async(); // ensure the CoreWebView2 is created
    var core_wv2 = myWebview.CoreWebView2;
    if (core_wv2 != null)
    {
        core_wv2.SetVirtualHostNameToFolderMapping(
            "appassets.example", "assets",
            Microsoft.Web.WebView2.Core.CoreWebView2HostResourceAccessKind.Allow);

        myWebview.Source = new Uri(https://appassets.example/myVideo.mp4);
    }
```
* Loading directly from the app's resources.pri isn't currently supported by default. I think it might be possible to use the [CoreWebView2.WebResourceRequested](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=webview2-dotnet-1.0.902.49) event, lookup/load the resource into a stream, and return that in the response. We haven't tried that, though. If there is strong desire to have this as a default feature of the WebView2 control, feel free to log a proposal for this feature, such as to have `http://app.resources/path/file.ext` automatically hook into the app’s resources.pri via the WebResourceRequested event.

**Comment by mqudsi** [comment]
Thanks for the summary, @codendone. I wasn't aware support for `ms-appx-*://` was dropped but we've already migrated to `SetVirtualHostNameToFolderMapping` because that's all what was available in the previews.
