### ISSUE TITLE
TreeView should have a SelectedItem property

### ISSUE THREAD

**Issue by rawlinson** [microsoft/microsoft-ui-xaml#197]
Similarly to ListViews etc., the TreeView class should have a SelectedItem property that is used when SelectionMode = Single. This would make data binding when using the TreeView to select single items a lot simpler.

This would also fix/bypass #124.

**Comment by jevansaks** [comment]
Seems like a reasonable request. Probably just an oversight. Follow the API on ListView.

**Comment by MikeHillberg** [comment]
Like the idea too.  Note that the challenging part is making the setter work, which is likely why the TreeView.SelectedItem in WPF is get-only.

**Comment by predavid** [comment]
@jevansaks - this PR is in Code review and @MikeHillberg  is reviewing the API spec currently. Should we move this item to the Backburner?

**Comment by jevansaks** [comment]
> @jevansaks - this PR is in Code review and @MikeHillberg is reviewing the API spec currently. Should we move this item to the Backburner?

Sure!

**Comment by predavid** [comment]
Updated to move to BackBurner.

**Comment by chigy** [comment]
@predavid , have we documented this new property yet?
