### ISSUE TITLE
How does Compact density work for controls other than TextBox ?

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/microsoft-ui-xaml#1970]
Grid level resources don't seem to change the density of the controls other than textbox.
When I asked about it, I was given [this reply](https://github.com/microsoft/microsoft-ui-xaml/issues/1531#issuecomment-549474475) which show compact density is working. But the result I got is this:
![image](https://user-images.githubusercontent.com/21083609/74357039-7ee6e000-4de9-11ea-8375-3f24c69fa72a.png)

You can see that up to the `TextBox`, all other control remained same in size. Am I missing something?

The code is here:
```
<Page
    x:Class="Test.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">

    <winui:TwoPaneView Pane1Length="*" Pane2Length="*">
        <winui:TwoPaneView.Pane1>
            <Grid Margin="5">
                <Grid.RowDefinitions>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                    <RowDefinition />
                </Grid.RowDefinitions>
                <TextBlock
                    HorizontalAlignment="Center"
                    Style="{ThemeResource HeaderTextBlockStyle}"
                    Text="Normal density" />
                <CheckBox Content="Checkbox" Grid.Row="1"/>
                <Slider Header="Slider" Grid.Row="2" />
                <ToggleSwitch Header="Toggle switch" Grid.Row="3" />
                <TextBox Header="Textbox"  Grid.Row="4"/>
            </Grid>
        </winui:TwoPaneView.Pane1>
        <winui:TwoPaneView.Pane2>
            <Grid Margin="5">
                <Grid.RowDefinitions>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                    <RowDefinition />
                </Grid.RowDefinitions>
                <Grid.Resources>
                    <ResourceDictionary Source="ms-appx:///Microsoft.UI.Xaml/DensityStyles/Compact.xaml" />
                </Grid.Resources>
                <TextBlock
                    HorizontalAlignment="Center"
                    Style="{ThemeResource HeaderTextBlockStyle}"
                    Text="Compact density" />
                <CheckBox Content="Checkbox" Grid.Row="1"/>
                <Slider Header="Slider" Grid.Row="2" />
                <ToggleSwitch Header="Toggle switch" Grid.Row="3" />
                <TextBox Header="Textbox"  Grid.Row="4"/>
            </Grid>
        </winui:TwoPaneView.Pane2>
    </winui:TwoPaneView>
</Page>

```

**Comment by ranjeshj** [comment]
@LucasHaines @licanhua @chrisglein  do you know what might be happening here.

**Comment by licanhua** [comment]
I think it's expected.
For compact, it only applies to Controls like CombBox, TreeView, NavigationView. You can see the full list by [compact.xaml](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/dll/DensityStyles/Compact.xaml). The ones you questioned is not in the list.

For 19H1(possible RS5) or above, we implemented 'density' in OS(a smaller size than rs5-).
To support down-level, we built it into WinUI.
For Slider and ToggleSwitch,  it's actually already in 'density'. And you can switch it back to not density by SliderPreContentMargin and other parameters which are described in [CommonStylesPage.xaml](https://github.com/microsoft/microsoft-ui-xaml/blob/a89011804234f43fa7c4f5126521cfe1de290745/dev/CommonStyles/TestUI/CommonStylesPage.xaml)

If you create a app with winui and another app without winui and run them in rs5- machines, then you can see the difference.

**Comment by MuziburRahman** [comment]
> For compact, it only applies to Controls like CombBox, TreeView, NavigationView.

Is there any plan to extend compact into other controls?

**Comment by mdtauk** [comment]
> > For compact, it only applies to Controls like CombBox, TreeView, NavigationView.
> 
> Is there any plan to extend compact into other controls?

I think most controls fall into the 16px, 24px, and 32px categories - with controls that default to 40px being shrunk
