### ISSUE TITLE
SizeOfSet and PositionInSet are not set for a NavigationViewList in NavigationView.PaneFooter

### ISSUE THREAD

**Issue by abbasms** [microsoft/microsoft-ui-xaml#1971]
**Describe the bug**
The 'Accessibility Insights' tool expects the 'SizeOfSet' and 'PositionOfSet' items to be set for every item in a list. In the NavigationView, these items are set for the main list and the Pane Footer if we use the default Pane Footer with 'Settings'.

However, if we use a NavigationViewList as Pane Footer list, the values are not set for these items.

**Steps to reproduce the bug**

1. Create a UWP App with a NavigationView control, a NavigationView.PaneFooter control and a NavigationViewList in the NavigationView.PaneFooter control.
2. Provide the values to these lists. (I used a ViewModel and referenced that in MenuItemsSource/ItemsSource property.)

```
<controls:NavigationView 
        x:Name="NavigationView"
        MenuItemsSource="{x:Bind ViewModel.MenuItemsSource}">
		<controls:NavigationView.PaneFooter>
			<controls:NavigationViewList
                                x:Name="FooterList"
                               ItemsSource="{x:Bind ViewModel.FooterItemsSource}">
			</controls:NavigationViewList>
		</controls:NavigationView.PaneFooter>
</controls:NavigationView>
```

3. Launch the App and open Accessibility Insights.
4. Hover over the top list items and observe the values for 'SizeOfSet' and 'PositionInSet'
5. Hover over the pane footer items and observe the values for 'SizeOfSet' and 'PositionInSet'

**Expected behavior**

We expect the 'SizeOfSet' and 'PositionInSet' to have values for both the lists.

**Actual behavior**
'SizeOfSet' and 'PositionInSet' doesn't have values for the pane footer list items.

**Screenshots**

Top list items
![image](https://user-images.githubusercontent.com/3537213/74367007-1a069800-4d9f-11ea-9272-72adcdc0ed26.png)

Footer pane list items
![image](https://user-images.githubusercontent.com/3537213/74367135-5934e900-4d9f-11ea-855e-799a60ed2872.png)

**Version Info**

NuGet package version:
2.3.191211002 and 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

I was going thru [https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/NavigationViewItemAutomationPeer.cpp](url) and it seems that there doesn’t seem to be checks to set these properties only for the regular pane items and for footer panes it is assumed that only the default ‘Settings’ will be present.

**Comment by ranjeshj** [comment]
@abbasms This is a scenario that we currently do not support well. There is a proposal to improve this [here](https://github.com/microsoft/microsoft-ui-xaml/issues/375). The only workaround we can think of is to set the size and position properties on the items manually. You should also not use the NavigationViewList outside of its current usage in the template. With the latest updates to NavigationView to use ItemsRepeater instead of ListView this type has been removed from the latest pre-release.

**Comment by abbasms** [comment]
So in the future we can expect the NavigationView control to have improvements, which will help fix this issue?

Also this [article](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater#is-this-the-right-control) talks about when to use ItemsRepeater vs ListView. With the ListView gone, is the expectation to switch to using ItemsRepeater (which requires custom tweaking)?

**Comment by ranjeshj** [comment]
@abbasms This specific issue is tracked by the proposal I mentioned above. ListView is still available (not gone). **NavigationViewList** is a derived type of ListView specifically for usage in NavigationView. NavigationViewList is gone with the most recent refactor of NavigationView. NavigationView internally uses ItemsRepeater instead in preparation for allowing hierarchical navigation support. For your current usage NavigationViewList does not provide anything more than what ListView does.

**Comment by carlos-zamora** [comment]
> The only workaround we can think of is to set the size and position properties on the items manually.

Windows Terminal is being affected by this issue (tracked in https://github.com/microsoft/terminal/issues/11154). We're using MUX 2.7.0-prerelease.210913003.

I have tried setting it manually via the following methods:
1. update via the XAML file
```
                <mux:NavigationView>
                    <mux:NavigationView.PaneFooter>
                        <!--  The OpenJson item needs both Tapped and KeyDown handler  -->
                        <mux:NavigationViewItem x:Name="OpenJsonNavItem"
                                     x:Uid="Nav_OpenJSON"
                                     AutomationProperties.SizeOfSet="1"
                                     AutomationProperties.PositionInSet="1">
                            <mux:NavigationViewItem.Icon>
                                <FontIcon Glyph="&#xE713;" />
                            </mux:NavigationViewItem.Icon>
                            <mux:NavigationViewItem.Content>
                                CUSTOM ITEM
                            </mux:NavigationViewItem.Content>
                        </mux:NavigationViewItem>
                    </mux:NavigationView.PaneFooter>
                </mux:NavigationView>
```
2. update via code
```
Automation::AutomationProperties::SetSizeOfSet(OpenJsonNavItem(), 1);
Automation::AutomationProperties::SetPositionInSet(OpenJsonNavItem(), 1);
```

In both cases, the `SizeOfSet` and `PositionInSet` remain unchanged. This also repros using XAML Studio.

E+D Accessibility is requiring this of us in https://github.com/microsoft/terminal/issues/11154. For tracking, can we reopen this issue, or should we open another one?

**Comment by chingucoding** [comment]
@carlos-zamora The proposal to add navigationview footer items, you should not need to set the items as part of the PaneFooter. If I see this correctly, and you just want to have a bottom pinned navigation view item, the PaneFooterItems should be enough for this.

**Comment by carlos-zamora** [comment]
@chingucoding Yeah, I just want to have a `NavigationViewItem` pinned to the bottom by the settings button. We're using `PaneFooter`, but `SizeOfSet` and `PositionInSet` aren't being set. And if I try to set it manually, it remains unset.

**Comment by chingucoding** [comment]
Good in that case, you could try putting the NavigationViewItem in the NavigationViewPaneFooterItems collection instead of the NavigationViewPaneFooter. Size of set and position in set should be set then.

**Comment by carlos-zamora** [comment]
That works! Thank you!
