### ISSUE TITLE
Cannot start to use UI.XAML searched all over the web but cannot figure it out.. help!

### ISSUE THREAD

**Issue by winsrp** [microsoft/microsoft-ui-xaml#1973]
Using VS 2019 or VS2019 preview 2, making a blank C# WPF project, added nuget package on version 2.3.191211002 and added the code

```xaml
<Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
</Application.Resources>
```
to my app.xaml results in an error :

The name "XamlControlsResources" does not exist in the namespace "using;Microsoft.UI.Xaml.Controls".

No other line of code added, how can I move forward and remove this issue, this is surely something stupid that I have not done, but I cannot figure it out. I have tried using previous version of the nuget package but it is always the same thing.

Thanks.

**Comment by ranjeshj** [comment]
@winsrp WinUI needs XAML islands to work in a WPF project which needs more steps. This will work if you create a blank UWP app. @Austin-Lamb @marb2000 can comment on usage of XAML islands if that is what you are trying to do.

**Comment by winsrp** [comment]
I was trying to setup WinUI in a WPF project for testing how controls would look but it seems I would need the XAML host controller according to my research, right?

**Comment by winsrp** [comment]
honestly, I finally got it to work following this [steps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands) and I can tell, I will wait for it to someday work without the 100 steps involved and not to mention the amount of errors I had to google to get this to work starting from a fresh VS install.
