### ISSUE TITLE
Build error on adding new page in new UWP Win UI 3.0 C# project

### ISSUE THREAD

**Issue by jessestr** [microsoft/microsoft-ui-xaml#1974]
**Describe the bug**
Build error on adding new page in new UWP Win UI 3.0 C# project

**Steps to reproduce the bug**

1. Create a new C# UWP Win UI 3.0 project
2. Add a new page
3. Build

**Expected behavior**
Shouldn't give an error on adding a new page

**Screenshots**
![image](https://user-images.githubusercontent.com/55050897/74421499-6dcfba80-4e4d-11ea-8946-a7bf3237ce76.png)

**Version Info**
Win UI 3.0 Alpha
Windows 10 & Visual Studio 2019 + Visual Studio 2019 Preview

NuGet package version: 
3.0.0-alpha.200210.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Comment by ranjeshj** [comment]
@jessestr Please use the Add New Page (WinUI) instead of the Add New Page item.
![image](https://user-images.githubusercontent.com/28935693/74441491-c2127480-4e24-11ea-86c0-a9fce8911338.png)

The Add New Page template adds page with the Windows.UI.Xaml namespace hence the error complaining about the base class.

@danzil Is there a way to filter the item types for a WinUI3 project so that the OS XAML item templates do not show up ?

**Comment by jessestr** [comment]
> @jessestr Please use the Add New Page (WinUI) instead of the Add New Page item.
> ![image](https://user-images.githubusercontent.com/28935693/74441491-c2127480-4e24-11ea-86c0-a9fce8911338.png)
> 
> The Add New Page template adds page with the Windows.UI.Xaml namespace hence the error complaining about the base class.
> 
> @danzil Is there a way to filter the item types for a WinUI3 project so that the OS XAML item templates do not show up ?

Thanks! Actually just tried it and the Blank Page (WinUI) wasn't an option. Had to reboot before it showed up as an option.

**Comment by danzil** [comment]
There should be a way for us to make it show only WinUI Item Templates. I'll keep this issue as a bug to figure out how to do that.

**Comment by bpulliam** [comment]
UWP is no longer supported by WinUI 3.  If you can repro the issue on current builds without UWP, please reactivate or open a new issue.

Thanks!
