### ISSUE TITLE
NavigationView displaymode changing and ItemInvoked call

### ISSUE THREAD

**Issue by imthewiseguy** [microsoft/microsoft-ui-xaml#1976]
**Describe the bug**
when the NavigationView Display mode changes "Top" <---> Left, the selected NavigationViewItem will re-invoke causing unwanted commands to run (i.e. Page Navigation)

**Steps to reproduce the bug**

I have Visualstates to change the displaymode.
If i switch visualstates (and thus changing the displaymode) the above mentioned action occurs

**Expected behavior**
The NavigationViewItem will not be reinvoked and the Page's Content will not change

**Screenshots**

**Version Info**
Windows 10 Build 19559, Windows 10 sdk 18362

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19559)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by imthewiseguy** [comment]
![example](https://user-images.githubusercontent.com/25320332/74511429-d1440180-4eba-11ea-8326-cf51c156cfa2.gif)

**Comment by ranjeshj** [comment]
@imthewiseguy are you using Windows.UI.Xaml.NavigationView ? If so can you try using Microsoft.UI.Xaml.NavigationView from the latest prerelease of microsoft.ui.xaml nuget package. There have been some recent changes made for NavigationView in the latest prerelease.

**Comment by imthewiseguy** [comment]
Unfortunately the Microsoft.UI.Xaml NavigationView does the same thing

Sent from my iPhone

On Feb 14, 2020, at 4:07 AM, Ranjesh <notifications@github.com> wrote:

﻿

@imthewiseguy<https://github.com/imthewiseguy> are you using Windows.UI.Xaml.NavigationView ? If so can you try using Microsoft.UI.Xaml.NavigationView from the latest prerelease of microsoft.ui.xaml nuget package. There have been some recent changes made for NavigationView in the latest prerelease.

**Comment by imthewiseguy** [comment]
this issue needs to be fixed because for some reason on first run when the display mode changes the control is effectively reloaded thus causing the re-invoking.

**Comment by ranjeshj** [comment]
@imthewiseguy @ojhad Is this the same as  #1956

**Comment by ojhad** [comment]
> @imthewiseguy @ojhad Is this the same as #1956

Based on the gif, it looks like top nav settings is left selected when the display mode is changed. Is that correct @imthewiseguy ? In that case, it is the same issue.

**Comment by imthewiseguy** [comment]
Yes that’s correct

Sent from my Windows 10 device
