### ISSUE TITLE
Build error on master branch

### ISSUE THREAD

**Issue by tang-kai-ms** [microsoft/microsoft-ui-xaml#1977]
**Describe the bug**
Contrary to what is documented in developer_guide#Prerequisites, the master branch doesn't build with VS 2019 and WinSDK 18362 + 17763.

First I encountered duplicate project item in Microsoft.UI.Xaml.vcxproj. After resolving it, it shows the project asserts the CPPWINRT_VERSION to be 2.0.191217.1, which is higher than what is publicly available in WinSDK 18362.

**Steps to reproduce the bug**
1. Git clone the project
2. Open MUXControls.sln
3. Set build config to be Debug-x64-MUXControlsTestApp
4. Hit F5

**Expected behavior**
Project should build, a sample app should be launched.

**Version Info**
VS2019: 16.4.5
WinSDK: 10.0.18362.0 + 10.0.17763.0
OS: 10.0.19565

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by kmahone** [comment]
@tang-kai-ms we don't use cppwinrt from the Windows SDK. Instead we consume it from a nuget package. Did you run nuget restore on the solution before building? In Visual Studio, in the Solution Explorer pane, right click on the MUXControls solution and select Restore NuGet Packages.

Try that and see if it resolved your issue. If so, we should make sure to add that step to the readme.md.

**Comment by tang-kai-ms** [comment]
It still doesn't work on my workstation nor on those of my colleagues and nuget package restore doesn't change that. But on my newly installed laptop it builds normally without any issue. I'll investigate more to see if there is anything incompatible in our environment.

Thanks for replying.

**Comment by kmahone** [comment]
> It still doesn't work on my workstation nor on those of my colleagues and nuget package restore doesn't change that. But on my newly installed laptop it builds normally without any issue. I'll investigate more to see if there is anything incompatible in our environment.
> 
> Thanks for replying.

@tang-kai-ms Interesting. If you do find out what the issue is, please let me know and we can see if we can address the problem, or at least mention it in our readme. Thanks.
