### ISSUE TITLE
ListView does not report IsOffscreen correctly

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#1979]
**Describe the bug**

ListView is not correctly reporting when it is offscreen.

**Steps to reproduce the bug**

Repro can be achieve by creating an empty UWP app and adding a single element to it:

        <ListView Margin="500,500,0,0">
            <ListView.Items>
                <ListViewItem Content="Test" />
                <ListViewItem Content="Test" />
            </ListView.Items>
        </ListView>

Resizing the window to move the list view out of bounds will cause AccessibilityInsights to report an issue: the ListView's IsOffscreen property is not set to true.

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/24638397)

**Comment by RobGallo** [comment]
FYI: The Accessibility Insights team has received a bug based on this issue: https://github.com/microsoft/axe-windows/issues/387

We believe the error is not a false positive, and will reference this issue. Glad you have a bug for this!

**Comment by giladtaase** [comment]
Hi, any progress with this issue, or fix plan?

**Comment by aniketr99** [comment]
Hi @YuliKl , this bug is auto closed by BOT. Could you please create a new bug and provide tracking ID. Thanks!

**Comment by ranjeshj** [comment]
@PadminiGariki does this still repro? There have been fixes in WinUI3 for this and I do not see it repro in WinUI3 Gallery ListView page anymore.
