### ISSUE TITLE
Can't use Narrator item navigation to leave the lower part of the CommandBarFlyout

### ISSUE THREAD

**Issue by llongley** [microsoft/microsoft-ui-xaml#198]
(Copied from [internal issue](https://microsoft.visualstudio.com/OS/_workitems/edit/19391243).)

**Core/Non Core Scenario:** Unable to come out of lower part of sub context menu in both item/shift tab navigation, in a rich edit box

**Build Info:** 18268

**Pre-requisite:**
- Install XAML Controls Gallery from Store.
- Turn on Narrator.
- Set narrator to item mode.
- Require touch enabled device.

**Repro steps:**
- Launch XAML Controls Gallery app.
- Activate RichEdit box list item from All Controls page.
- Go to any rich-edit box and type some thing and do two finger double tap to invoke context menu.
- With single finger swipe come to lower part of context menu containing items like Paste, Select All etc.
- Now try to go to upper part of context menu containing items "Bold/Italic/See more" either with item navigation(single swipe)/three finger back swipe.

**Expected result:** With item navigation as well as with three finger back swipe focus should move from paste/select all menu item to "see less" button.

**Actual result:** The focus gets trapped in the pop-up.

**Observation:** Shift+tab from paste button to "see less" button works.In rs5_release three finger back swipe works but item mode navigation doesn't work.

**User Impact:** Touch users will be affected as the focus is getting trapped and user cannot come out of pop-up

**Comment by chingucoding** [comment]
I think this was fixed, using the item navigation, I was able to navigate between the primary and secondary commands without getting stuck:
![gif](https://user-images.githubusercontent.com/16122379/90820190-480dfb80-e331-11ea-974d-7f4f0cdcb9ee.gif)
(The focus switching doesn't always work as simulating the touch gestures with a mouse is not that easy and often narrator didn't recognize the gesture)
