### ISSUE TITLE
Missing Implicit convertions on WinUI3

### ISSUE THREAD

**Issue by azchohfi** [microsoft/microsoft-ui-xaml#1981]
**Describe the bug**
CS0029 Cannot implicitly convert type 'System.TimeSpan' to 'Microsoft.UI.Xaml.Duration'
This worked fine for **Windows**.Ui.Xaml.Duration.

**Expected behavior**
Should work as expected. Some implicit conversions are missing from WinUI3.

**Version Info**
February refresh of WinUI3.

NuGet package version: 
Microsoft.UI.Xaml 3.0.0-alpha.200210.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes  |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@MikeHillberg Is this known ?

**Comment by MikeHillberg** [comment]
Yes, there are several limitations in the C# projection of the WinUI 3 Alpha. Mostly they're related to members on structs, such as constructors. There's a related limitation is described in the release notes for [INotifyPropertyChanged](https://docs.microsoft.com/en-us/uwp/toolkits/winui3/#inotifypropertychanged-and-inotifycollectionchanged).

Most/all of the missing struct functionality is available in *Helper classes. For example [DurationHelper.FromTimeSpan](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.DurationHelper.FromTimeSpan) to convert a TimeSpan to a Duration.

**Comment by azchohfi** [comment]
Is it still the plan to migrate those for stable v3? Devs could just move to the helper methods, but that seems like an unnecessary breaking change.

**Comment by MikeHillberg** [comment]
Yes, we're hoping to have those migrated.

**Comment by chrisglein** [comment]
@MikeHillberg where are you tracking that work? I don't want this issue to turn stale if we're tracking this elsewhere internally.

**Comment by MikeHillberg** [comment]
Let's keep track of it here until it's addressed.

**Comment by ranjeshj** [comment]
@stevenbrix  Can we feed this requirement into cs/winrt so that these are available in the projection ?

**Comment by stevenbrix** [comment]
@ranjesh, yeah these are being tracked in the cs/winrt repo. @LucasHaines  for FYI

**Comment by hawkerm** [comment]
This this is the same type of issue. Hit this in 1.0-preview3 between string and int in a `CommandParameter` that was trying to execute a RelayCommand.

```xml
Command="{x:Bind ViewModel.MyCommand}"
CommandParameter="0">
```

Where `MyCommand` was defined as a `RelayCommand<int>`.

Had to instead define it like this instead...

```xml
<Button.CommandParameter>
    <x:Int32>0</x:Int32>
</Button.CommandParameter>
```

**Comment by hawkerm** [comment]
Says these got tracked in the C#/WinRT repo, but then no links provided, so unclear if this is resolved?

**Comment by Scottj1s** [comment]
Conversion for all Microsoft.UI.Xaml.* struct types has been supported by C#/Winrt since April, 2020
