### ISSUE TITLE
How to properly compile?

### ISSUE THREAD

**Issue by Damonsoft** [microsoft/microsoft-ui-xaml#1982]
Hello! I just have a simple question. I've been trying to get debugging going on WinUI, and I'm a little lost. I cloned the repository and updated my Visual Studio to version 16.4.5. I also made sure the SDK's 17763 and 18362 we're properly installed. When selecting Debug, x64, and the project MUXControlsTestApp, executing a build causes the following error.

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot resolve Assembly or Windows Metadata file 'C:\Users\damon\Documents\GitHub\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\Microsoft.winmd'	MUXControlsTestApp (test\MUXControlsTestApp\MUXControlsTestApp)	C:\Users\damon\Documents\GitHub\microsoft-ui-xaml\test\MUXControlsTestApp\MSTest\MUXControlsTestApp.csproj		

So my next thought was to just use the build command in the root directory which builds everything properly. Then use Visual Studio to debug the application. Unfortunately I cant figure out where the PDB file for the specific source files I need are outputted. I tried pointing Visual Studio towards the Microsoft.Ui.Xaml.pdb in the BuildOutput directory but no luck.

Also the build command ends correctly but when building the TestApp it indicates a missing reference to System.Runtime 4.0.0.

**Comment by ranjeshj** [comment]
@Damonsoft can you try running restore nuget packages (right click on MuxControls.sln in solution explorer) and do a rebuild from VisualStudio ?

**Comment by Damonsoft** [comment]
@ranjeshj Hey, so I did a fresh Git Clone of the repository and I right clicked the MuxControls.sln in solution explorer and did a nuget restore. The output stated all nuget packages were already installed.

`All packages are already installed and there is nothing to restore.`

I then did a rebuild and I got around 12 errors at least, all stating the same general error of missing Microsoft.winmd configuration file. However I did notice this time that Microsoft.Ui.Xaml project failed to load in Visual Studio. When hitting reload project in the context menu of solution explorer Visual studio gives me this error.

`C:\Users\damon\Documents\GitHub\microsoft-ui-xaml\dev\dll\Microsoft.UI.Xaml.vcxproj : error  : Cannot load project with duplicated project items: C:\Users\damon\Documents\GitHub\microsoft-ui-xaml\dev\RadioButtons\RadioButton_themeresources.xaml is included as 'Page' and as 'Page' item types.`

I tried poking around the Microsoft.UI.Xaml.vcxproj file to see whats going on but couldn't come up with a solution. Thanks a bunch for you help!

**Comment by ranjeshj** [comment]
@Damonsoft This looks like a duplicate entry in one of the included projects. I created a PR to remove the duplicate entry - try pulling that change and see if it fixes it for you.
https://github.com/microsoft/microsoft-ui-xaml/pull/1987

Also, delete the BuildOutput folder before loading the solution and do a full rebuild to ensure that you start at a clean point. It takes a little while during the initial load, but it should get faster in future loads.

Its a long weekend, so responses might be delayed. Thanks.
