### ISSUE TITLE
Cannot resolve Assembly or Windows Metadata file 'Y:\Dev\Repos\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\Microsoft.winmd'

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#1985]
**Describe the bug**
Cannot resolve Assembly or Windows Metadata file 'Y:\Dev\Repos\microsoft-ui-xaml\BuildOutput\Debug\x64\Microsoft.UI.Xaml\Microsoft.winmd'

**Steps to reproduce the bug**
Trying to build the project and run the MUXControlsTestApp as startup project

**Expected behavior**
Build should complete and Test App runs

**Screenshots**
![image](https://user-images.githubusercontent.com/7389110/74607712-ec895980-50d2-11ea-9898-4ee581ddfb52.png)

**Version Info**
Current repo

**Comment by chingucoding** [comment]
I also get the same error when downloading a fresh copy. If you revert [to this commit](https://github.com/microsoft/microsoft-ui-xaml/commit/f0643470a2d60d58c3d793748582f1a046f2a4e6) you should be able to compile again.

**Comment by ranjeshj** [comment]
This is likely the same issue being fixed by this PR - https://github.com/microsoft/microsoft-ui-xaml/pull/1987
