### ISSUE TITLE
Text not rendered in RichEditBox when large number of lines present

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/microsoft-ui-xaml#1989]
**Describe the bug**

When large number of lines are inserted(around 15000 and above) after certain amount of line(around 13000) the text is not rendered. Although other operations can be done on those invisible texts (i.e. copy pasting).

**Steps to reproduce the bug**

1. Add a RichEditBox control.
2. Insert around 15000 lines 
Or just copy and paste all the lines in the text file below:
[NotepadsMainPage.StatusBar.txt](https://github.com/microsoft/microsoft-ui-xaml/files/4215258/NotepadsMainPage.StatusBar.txt)

**Expected behavior**

The texts should be rendered.

**Screenshots**

Notice all the invisible texts from the scroll bar:
![ApplicationFrameHost_2020-02-17_22-51-08](https://user-images.githubusercontent.com/51203900/74675264-2fcdf000-51d9-11ea-8bdc-5420f9cc12d4.png)

Even though text is not shown, it can be copy-pasted:
![2020-02-17_22-53-19](https://user-images.githubusercontent.com/51203900/74675299-42482980-51d9-11ea-9d45-7f710dfce57e.gif)

**Version Info**

NuGet package version: 2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19564)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by yaichenbaum** [comment]
This sounds similar to #1842

**Comment by JasonStein** [comment]
This is related to WinRT ScrollViewer. The WinRT RichEdit control itself can handle such amount of text but the ScrollViewer cannot since there is an upper rendering limit set inside ScrollViewer.

**Comment by ranjeshj** [comment]
@RBrid does the Mux.ScrollViewer support very large extents ?

**Comment by 0x7c13** [comment]
Hey folks, any plan for supporting larger canvas for RichEditBox?

**Comment by DmitriyKomin** [comment]
This is tracked as feature proposal #1842 , closing this bug as duplicate.
