### ISSUE TITLE
Question: Is there a color/brush resource to display validation error text?

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#1991]
I know there is some work started for input validation and wondering if some theme resource were created which developer can also use?

**Comment by mdtauk** [comment]
I believe it will use the SystemErrorText color

**Comment by ranjeshj** [comment]
You can use SystemErrorText, but that is defined only in October 2018 Update (17763 aka "Redstone 5") or later builds. The other option if you want to go further down level is to use your own resource.
