### ISSUE TITLE
<TextBox TextWrapping="Wrap" ... /> hides text in some layout updates

### ISSUE THREAD

**Issue by jess-rod** [microsoft/microsoft-ui-xaml#1992]
**Describe the bug**

Given a TextBox, if TextWrapping is set to Wrap, HorizontalAlignment is set to Stretch, VerticalAlignment is not set to Stretch and Text is set to some text long enough so that the number of lines changes depending on its actual width, then its actual height doesn't update when a significant and sudden change to its actual width happens, at least, not always. The result is some text hidden until a user takes some action like select some text.

**Steps to reproduce the bug**

1. Create a UWP project with a single page.
2. Add a TextBox as the only child of the Page.
3. On the TextBox, set TextWrapping to Wrap and VerticalAlignment to Top.
4. Leave the rest of the properties unset.
5. Start debugging (F5).
6. Make the window's width approximately half the width of a maximized window.
7. Double click on the title bar to (suddenly) maximize the window.
8. Write a single line of text so that it almost reaches the window's width.
9. Double click on the title bar several times to change the window's width.

**Expected behavior**

The TextBox's actual height should always update automatically so it shows the whole text (wrapped or not).

**Screenshots**

Expected behavior:
<img width="960" alt="1" src="https://user-images.githubusercontent.com/56958190/74729806-f3cc7680-523c-11ea-9ddb-b856c72c8fe7.png">

Expected behavior:
<img width="960" alt="2" src="https://user-images.githubusercontent.com/56958190/74729813-f75ffd80-523c-11ea-9a2d-76a962729075.png">

Unexpected behavior:
<img width="960" alt="3" src="https://user-images.githubusercontent.com/56958190/74729819-f9c25780-523c-11ea-8f18-dd0f06744cf7.png">

Unexpected behavior:
<img width="960" alt="4" src="https://user-images.githubusercontent.com/56958190/74729827-fb8c1b00-523c-11ea-9e7b-0dbcfe7ff22d.png">

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  |  Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |

**Additional context**

**Comment by jess-rod** [comment]
I've run some tests and I believe it's a race condition. In some cases, like the test above, it happens some times, whereas, in other scenarios, it happens every time.

Anyway, in one test, I modified the TextBox's width with the aid of two buttons which increased or decreased the width by one pixel. At the threshold, the TextBox's height and/or text wrapping didn't adjust to the content as they should. Then, if the width was increased (or decreased, depending on the case) once more, the TextBox height and/or text wrapping adjusted as expected.

**Comment by jess-rod** [comment]
Anything?

**Comment by chrisglein** [comment]
Thanks for the detailed bug report, @jess-rod. I have tried but been unable to repro it so far. Your info includes the version of the Microsoft.UI.Xaml, but the steps from building a blank project didn't include adding its application resources - did you also do that (I tried with and without and it didn't seem to affect it, but it's worth asking)? What was the min/max tested version for your app?

Tagging @ddalp in case he's heard of a similar bug in text layout being logged internally.

To set expectations, the layer of logic involved here would be in the core of layout, so not something that can be addressed with WinUI2. The soonest this could be addressed is after WinUI3.

**Comment by ddalp** [comment]
It's likely a bug in the CTextBoxView::MeasureOverride and ArrangeOverride. We do things special for TextWrapping wrap. It looks like we probably skipped or did not ask RichEdit to redo the text layout and used the NaturalSize(GetTextNaturalSize) instead.

**Comment by jess-rod** [comment]
I've just reproduced the bug by creating a blank project with 1903 (10.0; Build 18362) as the target and minimum version (the only NuGet package installed is Microsoft.NETCore.UnversalWindowsPlatform 6.2.9). Then, I've followed the steps above.

```
<Page
    x:Class="TextWrappingBug.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TextWrappingBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <TextBox TextWrapping="Wrap"
             VerticalAlignment="Top" />
</Page>
```

To see the bug in action, you need to fill the text box with some text so that there be (if there wasn't a bug) (A) a one-line text box when the window is maximized and (B) a two-line text box when the window isn't maximized.

Then, switch between these two window's width states as many times as needed until you see the bug (either a two-line text box when the window is maximized or a one-line text box when the window isn't maximized) because it doesn't happen every single time.

It is important that you do not hold and drag from a window's edge to switch between the maximized and non-maximized state. The bug happens right before transitioning to (or from) the two-line text box, then it readjusts accordingly to the expected behavior. Instead, double click on the window's top bar, so that the window's width change instantly.

**Comment by jess-rod** [comment]
> It is important that you do not hold and drag from a window's edge to switch between the maximized and non-maximized state. The bug happens right before transitioning to (or from) the two-line text box, then it readjusts accordingly to the expected behavior.

Actually, you can hold and drag and still reproduce the bug, but you need to be very precise (1-pixel precise) to stop holding right before the transition is to occurs. One thing is true, being that precise, the bug happens every single time.
