### ISSUE TITLE
Error creating WinUI blank App

### ISSUE THREAD

**Issue by jrahma** [microsoft/microsoft-ui-xaml#1994]
Hi,

I am trying to create a new Blank WinUI App (C#) but getting this error:

![WinUIError](https://user-images.githubusercontent.com/6236241/74775348-f5cf1d80-52ae-11ea-900e-665bad1ea667.png)

I am using Visual Studio Version 16.4.5

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by ranjeshj** [comment]
@jrahma Are you seeing this after just creating a blank app ? Are there any other changes to the blank app ? Can you share a callstack ?

**Comment by jrahma** [comment]
It's just when I try to create a new blank app like this:

![WinUIErrorScreen](https://user-images.githubusercontent.com/6236241/74776426-f963a400-52b0-11ea-8e6b-5d97c5c3fd34.png)

**Comment by ranjeshj** [comment]
@danzil can you help ?

**Comment by danzil** [comment]
@jrahma, do you have the following 3 Visual Studio workloads installed? 

  * .Net Desktop Development
  * Desktop Development with C++
  * Universal Windows Platform development

**Comment by jrahma** [comment]
@danzil only (Desktop Development with C++) was not installed but I am getting the same error even after installing it.

**Comment by danzil** [comment]
Bummer, that works for me (I'm on an even newer VS pre-release version). Any chance you could start VS using the "devenv.exe /log file.log" command and try reproducing again, and see if the log file reveals more details on what's failing? See the [VS /Log switch](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/ms241272(v=vs.100)?redirectedfrom=MSDN) for details on this flag.

Thanks for your help identifying the issue!

**Comment by jrahma** [comment]
@danzil here is the log file:

[winuilog.log](https://github.com/microsoft/microsoft-ui-xaml/files/4221849/winuilog.log)

**Comment by danzil** [comment]
Thanks for sharing the log. I'm trying to figure out what's going on, it looks like a path is not being formed correctly - don't know why yet.

**Comment by danzil** [comment]
@jrahma while I wait for an answer from the Visual Studio team, I installed the same version of VS that you have (and made sure I checked all the 3 boxes I mentioned above). The same scenario works for me.  Are you able to create the equivalent (a regular) UWP C# app? Have you made any additional changes to your VS installation that I should know about in order to reproduce? Thanks!

**Comment by jrahma** [comment]
@danzil No changes at all, just the VS only with no special configuration

yes, I am able to create UWP and Mobile apps too (Xamarin)

**Comment by danzil** [comment]
@jrahma sorry about the delay, this fall off my radar. Are you still having problems with this?
