### ISSUE TITLE
Unify Controls and Properties with Xamarin Forms

### ISSUE THREAD

**Issue by jrahma** [microsoft/microsoft-ui-xaml#1995]
Hi,

Please make all Microsoft controls unified,

You cannot use Label in Xamarin Forms and TextBlock in WinUI for example

This applies to all other controls

In addition, we should have the same properties, e..g HorizontalOptions should be the same for the XF as well as WinUI

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by robloo** [comment]
This was supposed to happen. Then XAML standard (announced a few years ago now) died and nobody from Microsoft has ever explained why. It's Xamarin Forms that needs to change to the other XAML flavors -- perhaps this would be better in their repo. I still can't fathom why they every decided to change names like that.

**Comment by YuliKl** [comment]
@jrahma at this point in time, both Xaml and Xamarin.Forms have sizable developer communities and updating API names would constitute a significant breaking change. A renaming exercise just isn't feasible at this time for either framework. And adding new control aliases to Xaml (e.g. <Label/> would just create a <TextBlock/>) would lead to API bloat and runs the risk of making Xaml even more difficult to learn.

If you have suggestions for specific properties or features present in Xamarin.Forms but missing in Xaml, I would encourage you to open new proposals for the specific gaps.
