### ISSUE TITLE
Numberbox does not format placeholder text to the system specified number format.

### ISSUE THREAD

**Issue by rogihee** [microsoft/microsoft-ui-xaml#1998]
**Describe the bug**
The number box in the sample uses a fixed decimal separator in the sample text and placeholder, but uses the current culture separator for formatting.

Not sure this is a general bug in the control, or only a wrong configuration in the sample. 

**Steps to reproduce the bug**
1. Open the Controls Gallery app, go to Text -> NumberBox and the last sample that rounds to the nearest 0.25 dollars. Notice that the text message and the numberbox both use a "." as decimal separator.

![image](https://user-images.githubusercontent.com/4984486/74834357-90654600-531b-11ea-8e06-bf6a6f413902.png)

2. Set the keyboard to a Culture that has a "," instead of "." as separator, say English United States International.
3. After entering a value, it is only updated / rounded if entered with the correct decimal separator for the current culture, not the "." that is displayed.

**Expected behavior**
NumberBox should display 0,00 and the message should be "A formatted NumberBox that rounds to the nearest 0,25". In other words: it should either apply the correct DecimalSeparator from the Current Culture or it should force the decimal separator to be a "." in both the text and formatting. 

**Screenshots**
When entering, use ",":
![image](https://user-images.githubusercontent.com/4984486/74834992-cc4cdb00-531c-11ea-92ec-cce47de04508.png)

After completion it shows the value with correct decimal separator:
![image](https://user-images.githubusercontent.com/4984486/74835018-da9af700-531c-11ea-9d86-2435cbf759de.png)

**Version Info**
Grabbed latest Store version as of 19/02/2020.

**Comment by StephenLPeters** [comment]
@rogihee I think what you are saying is that the placeholder text that is provided to the numberbox ("0.00") is not being formated with the correct user specified separator.  I think if it was, the issue you are presenting would be resolved?  @teaP do we do any processing of the place holder text right now?

@stmoy While looking into this I was playing around with the xaml controls gallery numberbox page and am noticing a lot of issues in this space (changing the number formattor at the system level) we did some work previously to address some of these issues. Has the gallery been updated to have these fixes?

**Comment by StephenLPeters** [comment]
@teaP playing around a bit more, it looks like the number parser can not take in numbers which have separators which are not '.'  so if you change your number separator to ',' you can't do expressions in numberboxes any more.

**Comment by StephenLPeters** [comment]
@SavoySchuler I think we should examine what it will take to truely support the custom number format settings in windows.  There are a number of settings that our expression parser is not remotely equipped to handle. Getting this exactly right seems hard.
![image](https://user-images.githubusercontent.com/7758786/74878476-43ce3a80-531c-11ea-804c-c4dee4d6cb08.png)

**Comment by rogihee** [comment]
@StephenLPeters Yes, that is what I mean. I had not realized that WinUI is C++ not C#, there you have the NumberFormatInfo CultureInfo classes that handle all this nicely for your. Let's not talk about datetime formatting then or left to right support ;-).

**Comment by robloo** [comment]
This is an old discussion. See some of my past comments trying to avoid these sorts of foreseen issues.

> Please also make sure this is correctly localised.
https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-488530306

> Localization would have to be supported by the control and moving the decimal place (whether comma, period, etc.) handled as a special case (I keep bringing this up because it's easy to miss)
https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-497545781

> Localization needs to be well thought out in the spec ahead of time. Additionally there are cases where you would want to override the UI local. Therefore setting a NumberformatInfo property or CultureInfo might be very useful. For example, in some applications both a foreign and local value are tracked. Each could potentially be a different format.
https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-496750885

> Please confirm that NumberBox will accept any INumberFormatter/INumberFormatter2 implementation -- and will continue to do so in the future (that's how it's implemented in code, I just want to make sure the spec calls it out too).
https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-558704145

> I am adamant I need this control to support overriding the UI localization and number format.
https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-511440982

And my personal favorite:

> I think Microsoft is going to have to consider biting the bullet on this one and fully implementing a conversion mechanism between .net cultures/localization (CultureInfo) and native/WinRT. Ideally you would not be considering a new way of doing things:
https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-515709679

**Comment by teaP** [comment]
PlaceholderText is a string. NumberBox can't parse "1.00" -> "1,00" because it can't know what culture to parse _from_, if that makes sense -- if the current decimal symbol is "," it doesn't know what the "." in the string is supposed to mean. The correct fix is for the dev to format their PlaceholderText before setting it on NumberBox. If you wish to open a bug on the controls gallery, that would be fine!

> @teaP Tammy Paine FTE playing around a bit more, it looks like the number parser can not take in numbers which have separators which are not '.' so if you change your number separator to ',' you can't do expressions in numberboxes any more.

I wasn't able to repro this issue.
