### ISSUE TITLE
Proposal: Single-instance mode for WinUI Desktop

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2008]
## Summary
Currently, Win32 apps are multi-instance by default. If you want to realize the default UWP single-instance behavior developers need to add additional logic to implement this behavior which might not be straightforward. It would be nice if WinUI Desktop apps can easily switch between single-instance and multi-instance behavior thanks to in-built framework support.

## Rationale
With Desktop Bridge and especially WinUI Desktop the boundaries between UWP apps and desktop apps are "softening". Examples are desktop apps which can now call native toast notifications or - in the future - look and feel like UWP apps except they have to use the Win32 app model for some yet missing or inadequately supported feature in the UWP. For many current and future desktop apps only the single-instance behavior makes sense. Right now though, however, there is no in-built support for these desktop single-instance apps:

* Starting a Win32 app via the start menu launches a new instance by default
* Activating a Desktop Bridge app using native toast notifications launches a new instance by default (you need to use a COM Activator to get an in-process activation)
* Invoking a jumplist task starts a new app instance
* Activating an app by protocol launches a new instance by default

Implementing the single-instance behavior does not only require an app lock (i.e. a mutex) to determine if an app instance is already running but in many cases, such as toast notification/jumplist activation, also requires inter-process communication. Since only the launched new app instance has the arguments specified in the toast notification or jumplist task, the new app instance needs to pass these arguments to the running app instance. This requires additional logic (for example using the Win32 *SendMessage* API and hooking the Win32 [WndProc](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms633573(v=vs.85)) function) which might not be straightforward to implement depending on the actual situation. 

As UWP apps and desktop apps will likely become more and more similar thanks to WinUI and increased access to WinRT APIs it would be great if WinUI Desktop apps could get an opt-in to the default single-instance behavior of UWP apps. In other words, if a WinUI app runs in the single-instance mode and the app is invoked (via start menu, jumplist, toast notification, etc.) the currently running app instance - if any - is activated and any specified arguments are passed to it. See the UWP API [Application.OnActivated](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.onactivated) for an example how WinUI could provide API support for this. 
If the app runs in multi-instance mode the current default behavior of Win32 apps would apply (so any new API like `Application.OnActivated` would not be called).

Support in the framework for WinUI Desktop apps would be a great a help for developers and would enable them to focus on the *what* and not the *how* when it comes to building desktop apps which behave similar to UWP apps. It would greatly aid in the process of incrementally updating your existing desktop app to match the look & feel of modern Windows apps.

## API
This is a very brief concept which is just meant to be a starting point. The proposed API could be added to the new WinUI XamlApplication class to be introduced in WinUI 3:

Add a property which determines the instance mode of the app:
```cs
public bool IsSingleInstance { get; set; }
```
Add an overridable method to handle app activation:
```cs
protected virtual void OnActivated(IActivatedEventArgs args);
```
```cs
public interface IActivatedEventArgs
{
        //
        // Summary:
        //     Gets the reason that this app is being activated.
        //
        // Returns:
        //     One of the enumeration values.
        ActivationKind Kind { get; }
        //

       [...]
}

public enum ActivationKind
{
        //
        // Summary:
        //     The user launched the app or tapped a content tile.
        Launch = 0,

        [...]

        // Summary:
        //     An app launched a URI whose scheme name this app is registered to handle.
        Protocol = 4,

        [...]

        //
        // Summary:
        //     The app was activated when a user tapped on the body of a toast notification
        //     or performed an action inside a toast notification.
        ToastNotification = 1010,

       [...]
}
```
[IActivatedEventArgs](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.iactivatedeventargs) and [ActivationKind](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.activationkind) are only briefly shown here to give an overview. How exactly they would compare to the linked UWP APIs would need to be determined.

**Comment by dotMorten** [comment]
@Felix-Dev Doesn't this apply to all kinds of Win32 apps and not specific to the UI Framework you chose to use? And if so, shouldn't this issue really be in the .NET 5 repo?

**Comment by Felix-Dev** [comment]
@dotMorten I don't know about the the roadmap and plan of investments for Win32 apps going forward. We do know that many future investments in the desktop space will happen in WinUI Desktop such as new Windowing APIs like easily extending into the titlebar. Currently, this is the best place to ask about WinUI Desktop and, from what I've seen, the only MS repo for now where WinUI Desktop has considerable focus. This issue is also a bit related to the WinUI Desktop UWP Jumplist issue https://github.com/microsoft/microsoft-ui-xaml/issues/2005 which according to the recent community call seems to be fine to be tracked in this repo for now.
Furthermore, based on the UWP API, support for this proposal would also likely require API changes/additions to WPF/Winforms (i.e. WPFs Application class) and in my view I see that as very unlikely to happen. 

Hence, in order to increase the chances of this proposal being realized I am strictly speaking about adding support to WinUI Desktop here. Whether this proposal would in fact include all kinds of Win32 apps would be up to Microsoft to decide and I would of course move this issue to the most suitable place if asked.

**Comment by Felix-Dev** [comment]
@jesbis I think we can close this as this will be addressed as part of Project Reunion in issue https://github.com/microsoft/ProjectReunion/issues/111. Feel free to transfer that issue to the Project Reunion repo (and re-open it) if you feel that would be helpful information to have there.

**Comment by ptorr-msft** [comment]
[Late to the party...] 

> shouldn't this issue really be in the .NET 5 repo?

@dotMorten the .NET repo would be the wrong place to log issues like this anyway, since that doesn't help people not using .NET (like C++, Python, Rust, etc.).

**Comment by dotMorten** [comment]
@ptorr-msft fair point. And another example of us never knowing the right place to log cross-cutting issues. Connect was a mess, but at least we always knew where to log issues 😉
