### ISSUE TITLE
Why you people still can't provide a consistent UI? Whats wrong with you people?

### ISSUE THREAD

**Issue by m2058** [microsoft/microsoft-ui-xaml#2009]

**Comment by ranjeshj** [comment]
@m2058 Can you provide more details ? What do you find to be inconsistent with what ?

**Comment by m2058** [comment]
context menus, app layouts, flyouts,and more

**Comment by kmgallahan** [comment]
@ranjeshj Fairly sure he doesn't understand the purpose of the repo, and thinks it is just for Windows 10 feedback. #2010

**Comment by ranjeshj** [comment]
@m2058 More details/pictures on specific UI side by side and what you find inconsistent (which apps it came from and maybe which technology) would be helpful and possibly actionable. In this repo, we build framework/controls and we try to be consistent in the set of controls we build. App developers can use it to build apps and customize it to fit their needs. Unfortunately without more information this is not actionable.

Also, please give the [code of conduct ](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/CODE_OF_CONDUCT.md) a read for future posts.
