### ISSUE TITLE
The following are the requested features....

### ISSUE THREAD

**Issue by m2058** [microsoft/microsoft-ui-xaml#2010]
Context menus need to be consistent. if possible, make them like these:
![image](https://user-images.githubusercontent.com/39938037/75062597-3c20b880-550b-11ea-91de-a3a54812b9bc.png)

and also the login scree, profile image is too huge.
proposed design:
![Login Screen](https://user-images.githubusercontent.com/39938037/75062840-b81b0080-550b-11ea-92ac-fdef237542f8.png)

**Comment by kmgallahan** [comment]
@m2058 This repo is not the place for random Windows 10 feedback.
