### ISSUE TITLE
Discussion: Let's try to get this repo into the Discussions beta

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/microsoft-ui-xaml#2013]
# Discussion: Let's try to get this repo into the Discussions beta
I just learned that GitHub has introduced [Discussions in beta](https://github.com/zeit/next.js/discussions).

Let's get rid of these "discussion issues", and try to be an early adopter of the new Discussions feature!

Good idea? Bad idea?

Where should proposals fit in? Issues or discussions?

I personally have always disliked calling anything that is **not** an issue/bug an "issue", so IMO proposals should go under discussions. Not quite sure about work-in-progress items like #264.

It would obviously be very helpful if there were a mechanism for converting existing issues into discussions, but I can't find much information about the feature at this time.

@ranjeshj You control this repo, not sure if you have a means to squeeze us into the beta though.

## Related Links

https://github.com/zeit/next.js/discussions

https://news.ycombinator.com/item?id=22388639

**Comment by Felix-Dev** [comment]
This repo is currently also the only place where we can have discussions about the WinRT API surface/UWP app model in an acceptable fashion. As a result, we've seen multiple proposals/discussions being opened over the past weeks and months which do not belong to WinUI at all. In that sense, having those threads grouped outside of the WinUI issues space seems like a good call to me and the new Discussions feature would allow that.

PS: We need to hammer this time and time again: We need an own platform to discuss WinRT/UWP app model related issues with other users and Microsoft engineers. It is badly needed! (The fact that I have to write this here in an unrelated repo just shows how bad the current situation is.)

**Comment by jtorjo** [comment]
@Felix-Dev 

> PS: We need to hammer this away again and again: We need an own place where we can discuss WinRT/UWP

Agreed 100% !

**Comment by ranjeshj** [comment]
@kmgallahan Thank you for suggesting. Definitely looks interesting. Taking a look. @jesbis as FYI.

**Comment by ranjeshj** [comment]
The discussions beta seems to be in pretty early stages. While it looks promising, it might be worth waiting a little bit before adopting for a few reasons.
•	It seems to cater more towards questions with a marked answer (which is sort of similar to Microsoft Q&A). 
•	We already have lots of discussions in issues with ‘discussion’ label and no straightforward one shot move to the new discussions feature. Having two mechanisms for discussions seems less than ideal.
•	No easy way to sort, filter, query discussions using labels which is really useful. We currently add labels for feature areas for example to be able to query discussions related to a specific feature.

**Comment by kmgallahan** [comment]
@gabbybilka Just bumping this suggestion to add Discussions that I made ~2 years ago.

A good amount has changed since the beta, including the addition of labels for discussions.

At a minimum discussions should existing as a place to reroute all/most Issues flagged with the Question label.

Release and community call announcements could definitely be moved there as well.

The WindowsAppSDK setup would be a good starting place: https://github.com/microsoft/WindowsAppSDK/discussions

Regarding above concerns:

> It seems to cater more towards questions with a marked answer (which is sort of similar to Microsoft Q&A).

You can now set Answers be be on/off per Category.

> We already have lots of discussions in issues with ‘discussion’ label and no straightforward one shot move to the new discussions feature. Having two mechanisms for discussions seems less than ideal.

You can now convert Issues to Discussions and create Issues from Discussions. Probably no way to do it in bulk, but that may not be desirable anyways.

> • No easy way to sort, filter, query discussions using labels which is really useful. We currently add labels for feature areas for example to be able to query discussions related to a specific feature.

Labels exist now with filtering & searching available. Sorting is partially available, although [can't sort by creation date for some reason](https://github.com/github/feedback/discussions/3235).

**Comment by kmgallahan** [comment]
Completed with https://github.com/microsoft/microsoft-ui-xaml/discussions/7333
