### ISSUE TITLE
TabView: Close button of tab items shows item header on hover

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2018]
**Describe the bug**
When hovering over a TabView item's close button, the displayed tooltip reads the content of the item header. Instead, the displayed content should match that of Edge UWP/Edge Chromium:
![image](https://user-images.githubusercontent.com/1398851/75119930-a8282b80-5687-11ea-8a8b-f400749b801e.png)

**Steps to reproduce the bug**
1. Open the XAML Controls Gallery
2. Go to the TabView page
3. Hover over the close button of a tab item. Observe that the tooltip displays the item's header content.

**Expected behavior**
The displayed tooltip should look like this:
![image](https://user-images.githubusercontent.com/1398851/75119964-cf7ef880-5687-11ea-8576-46e9f92d6641.png)

**Version Info**

NuGet package version: 
* Microsoft.UI.Xaml 2.4.0-prerelease.200203002
* Microsoft.UI.Xaml 2.3.200213001

**Additional Info**
I would like to give this one a try with help from the team. To set expectations straight: I'm an absolute beginner at C++ and C++/WinRT. I already did some testing and changing the tooltips to display `Close tab` doesn't seem to be much of an issue (basically looked at TeachingTip's close button for guidance). Adding the keyboard accelerator to the tooltip content is where I will likely need some help. I have a local commit ready with the changes above and a hint of how I would possibly add the keyboard accelerator string.

**Comment by ranjeshj** [comment]
@stmoy Does this sound reasonable to you ?

**Comment by stmoy** [comment]
Seems righteous to me! I believe the current ToolTip comes from the tab itself (ie. the x-to-close button doesn't have its own tooltip), but I think matching the behavior of Edge seems like a good thing to do.

**Comment by Felix-Dev** [comment]
@stmoy Correct. I had to add a tooltip specifically for the tab close button. Without that, the tooltip shown is the tab tooltip, i.e. [SecondTab] if that's the header of the tab (see pic above).

**Comment by Nirmal4G** [comment]
Close button should show `close <tabName> tab` text while the tab tool tip should show `<tabName/tabTitle>` itself. here, `tabName` should be a short 64char limited friendly identifier (e.g.: domain name part of the url, friendly short name, etc...) and `tabTitle` can be anything the user/app sets it to (e.g.: page title in the case of web page).

I prefer this kind of behaviour.
