### ISSUE TITLE
Framework-provided keyboard accelerators should be localized

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2023]
**Describe the bug**
When discussing issue #2018 with @chingucoding we noticed that currently framework-provided keyboard accelerators are not localized. For example, setting the app language to German and using the `Copy` StandardUICommand for a context menu item, we get the following result:
![image](https://user-images.githubusercontent.com/1398851/75249796-3bbc4200-57d7-11ea-8d5b-573ed20e0adb.png)

**Expected behavior**
The Context menu entry should be fully localized, i.e. "Kopieren (Strg+C)".

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Files**
[Minimal repro app](https://github.com/microsoft/microsoft-ui-xaml/files/4250100/KeyboardAccelLocalizationIssue.zip)

**Comment by Marv51** [comment]
This is still an issue. Please keep open.

**Comment by codendone** [comment]
This was internally duplicated to another internal item. Reopening so the status of this can be tracked against that other item.

**Comment by bpulliam** [comment]
Removed wrong one.  This fix will be in 1.4.2
