### ISSUE TITLE
UWP TextBox backspace not working

### ISSUE THREAD

**Issue by MartinHorst** [microsoft/microsoft-ui-xaml#2026]
**Describe the bug**
I add a normal TextBox inside a page.
`<TextBox x:Name="textBoxTest" TextAlignment="Center" Width="76" />`

In the code behind file I assign a text to the TextBox control

this.textBoxTest.Text = "1";

**Steps to reproduce the bug**
Click inside the TextBox between the text and the clear button near to the right side of the text.
In some case the TextBox got the focus. I can input text but I can't delete text using backspace or delete. Neither can I select the using the cursor keys. The TextBox behaves like it's empty.

**Version Info**
Windows.Foundation.UniversalApiContract, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | No   |
| November 2019 Update (18363)  | No  |
| May 2019 Update (18362)            | No  |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          | No  |
| Fall Creators Update (16299)       | No  |
| Creators Update (15063)            | No  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   | No   |
| Xbox                      | No   |
| Surface Hub          | No  |
| IoT                         | No    |

**Comment by chrisglein** [comment]
@MartinHorst Can I assume in your version table that you tested on 17763 but not the others? I just want to clarify if you're saying that's where you saw this, versus you saw it there but explicitly _not_ on other versions you tried (you can leave those blank).

I'm having some trouble reproducing this. Can you provide a screenshot of where exactly you're clicking? Or better yet, use the game bar (Win+G) to get a video capture of what you're doing.

**Comment by MartinHorst** [comment]
Hi,

I was also able to reproduce this on a Surtface Pro 6 with the Windows version 1903. It is easier to reproduce this if the TextAlignment is set to center. Screenshots won't help much because everything looks pretty normal. As I mentioned, the textbox handles normal keys but not backspace or arrow keys. It's important to position the mouse pointer as close as possible to the right side of the text. Don't position the pointer over the text.

**Comment by chingucoding** [comment]
@StephenLPeters I think this needs to wait until WinUI 3.
