### ISSUE TITLE
The TreeView class does not respect the HorizontalContentAlignment property of the ItemContainerStyle

### ISSUE THREAD

**Issue by rawlinson** [Microsoft/microsoft-ui-xaml#203]
Setting the HorizontalContentAlignment property off the ItemContainerStyle seems to do nothing. For example, if you set it to `Stretch`, the Content of the TreeViewItems is still left-aligned.
```
<TreeView.ItemContainerStyle>
    <Style TargetType="TreeViewItem">
        <Setter Property="HorizontalContentAlignment"  Value="Stretch"></Setter>
    </Style>
</TreeView.ItemContainerStyle>
```

This seems to be because the ContentPresenter within the TreeViewItem is in a StackPanel. The StackPanel itself is the only item in a Grid - removing the StackPanel and laying out its contents by ColumnDefinitions in the Grid fixes the issue. The StackPanel also has its Margin property bound to take care of indentations - this can instead be moved to the Padding property of the grid.

**Comment by jevansaks** [comment]
Good bug! Seems like you also know how to fix it, do you want to contribute the fix? :)

**Comment by rawlinson** [comment]
I'm happy to contribute the fix - it's a simple change to TreeViewItem.xaml - but I notice there is also a TreeViewItem_rs1.xaml file, which I presume needs changing as well. Is there a way to force its use to make sure the change is correct? I'm running RS5.

**Comment by rawlinson** [comment]
A second question: fixing this changes the default behaviour to 'Stretch' rather than 'Left', which is probably what it should be. Nevertheless, should the previous default be preserved or is such a change small enough not to be an issue, especially as it is a bug?

**Comment by kmahone** [comment]
@rawlinson take a look at dev\dll\ThemeResources.cpp. You should be able to modify the file for testing purposes to force a particular version of generic.xaml to be loaded at runtime.
