### ISSUE TITLE
Coordinated Animations cannot be Configured

### ISSUE THREAD

**Issue by stmoy** [microsoft/microsoft-ui-xaml#2035]
**Describe the bug**

#2006 uncovered an issue where coordinated animations always play the default Gravity configuration even when the connected animation has a configuration set. 

**Steps to reproduce the bug**

https://stackoverflow.com/questions/60290093/uwp-version-1809-connected-coordinated-animations-not-configured-the-same

**Expected behavior**

Coordinated animations can be configured

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by JJBrychell** [comment]
This is probably a bug and potential feature request. 

When an animation does not have a configuration, the default is used.  This applies to both regular and coordinated animations.  However, if we have a coordinated animation, we should probably use configuration of the base animation.  This would be an easy bug fix.

If the objective is that a coordinated animation can have a different configuration than its base, then that would be significant feature request involving api additions/changes.
