### ISSUE TITLE
Flyout shadow is drawn on top of sub-flyout

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#2041]
**Describe the bug**
Create a flyout which contains a button which opens another flyout that is displayed on top of the original one. Then the shadow from the original flyout is drawn on top of the just-opened flyout.

As a workaround, I've had to disable FlyoutPresenter.IsDefaultShadowEnabled, which is a real pain since I'm targeting versions of Windows 10 without conditional XAML.

**Expected behavior**
Shadow should not be drawn on top of the sub-flyout.

**Version Info**
Not using WinUI.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  |   Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |   Yes   |

**Comment by ranjeshj** [comment]
@benstevens48 can you please share a picture/reporo app ?

**Comment by benstevens48** [comment]
@ranjeshj - something like this is enough.
```
<Button Content="Test flyout">
            <Button.Flyout>
                <Flyout Placement="Bottom">
                    <Grid Width="300">
                        <Button Margin="0,0,0,50" Content="Test sub-flyout">
                            <Button.Flyout>
                                <Flyout Placement="Bottom">
                                    <StackPanel>
                                        <TextBlock Text="Some text"></TextBlock>
                                        <TextBlock Text="Some text"></TextBlock>
                                        <TextBlock Text="Some text"></TextBlock>
                                        <TextBlock Text="Some text"></TextBlock>
                                        <TextBlock Text="Some text"></TextBlock>
                                    </StackPanel>
                                </Flyout>
                            </Button.Flyout>
                        </Button>
                    </Grid>
                </Flyout>
            </Button.Flyout>
        </Button>
```
![flyout-shadow](https://user-images.githubusercontent.com/10088503/75590996-7bed2000-5a76-11ea-8aa2-790152e8539f.png)

It seems like it's not exactly the shadow, but maybe the backing visual for the shadow, that's drawn on top. It's definitely related to the shadow because setting FlyoutPresenter.IsDefaultShadowEnabled to true fixes it.

**Comment by ranjeshj** [comment]
@jesbis Do you know what might be happening here ?

**Comment by jesbis** [comment]
Not sure - @codendone ?

**Comment by codendone** [comment]
This is a known bug (tracked internally as https://microsoft.visualstudio.com/OS/_workitems/edit/20538560) in the Composition ProjectedShadow code that could result in a shadow from a visual to draw on another visual at the same Z depth.  The bug has been fixed and will be in the next release of Windows.  (It will also be fixed in WinUI3.)

This can theoretically be worked around by ensuring the nested flyout has a greater depth, but I believe the only way you can do that is to open the flyout then use VisualTreeHelper to walk up from the Flyout.Content until you find the FlyoutPresenter and change its .Translation property to have slightly larger Z.  That obviously isn't the most convenient.  (For this scenario, you could also do similar code to find the FlyoutPresenter of the original popup and change it to a smaller Translation.Z value.)

MenuFlyout has code to ensure submenus have greater Z (which was also to intentionally have different shadow depth). But depending on your flyout content, that may not be an option for you.

**Comment by benstevens48** [comment]
I created a workaround. In case anyone else wants it, use this class instead of the Flyout class for nested flyouts.
```C#
    public class CustomFlyout : Flyout {

        //This works around a bug in Windows 10 1903 and 1909 which causes a flyout to draw its shadow on top of a sub-flyout at the same z-index. This class should be used where a nested flyout is needed instead of the Flyout class.
        protected override Control CreatePresenter() {
            var presenter = base.CreatePresenter();
            if (presenter == null || !ApiInformation.IsPropertyPresent("Windows.UI.Xaml.UIElement", "Translation")) {
                return presenter;
            }
            UIElement targetParent = Target;
            while (targetParent != null && !(targetParent is FlyoutPresenter)) {
                targetParent = VisualTreeHelper.GetParent(targetParent) as UIElement;
            }
            if (targetParent is FlyoutPresenter && targetParent.Translation.Z >= presenter.Translation.Z) {
                var translation = targetParent.Translation;
                translation.Z += 0.0001f;
                presenter.Translation = translation;
            }
            return presenter;
        }

    }
```

**Comment by codendone** [comment]
Great job, @benstevens48!  Thanks for sharing!

Since this issue has been fixed for future versions of Windows using system XAML and will also be fixed in WinUI3, I'm closing this issue.  See helpful workaround above if you need a workaround prior to WinUI3.
