### ISSUE TITLE
Provider.GetXamlType on ARM64

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2042]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/933011/providergetxamltype-on-arm64.html)._

---
We have an app in the Microsoft Store (UWP) that is complied for x86 and ARM and they work well. With the exact code we target ARM64 and when the first XAML page load (using UWP) we get this error:

public global::Windows.UI.Xaml.Markup.IXamlType GetXamlTypeByType(global::System.Type type)
        {
            return Provider.GetXamlType(type);  <---- error on this line
        }

System.Reflection.MissingMetadataException
  HResult=0x80131543
  Message=Windows.Foundation.IReference`1<Double>
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

This is XAML created by the IDE. We are not doing anything special and it seems the issue is with the MS generated code. Like stated above this app runs as an x86 and ARM currently with no issues. That XAML page uses no NuGet packes.

We target Fall Creators and greater. We also targeted just the newest Windows release (1903) with no difference.

Please advise.

---
#### Visual Studio Feedback System on 2/27/2020, 03:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ranjeshj** [comment]
@danzil Is this a known issue ? It looks like an issue in the OS XAML not WinUI.

**Comment by danzil** [comment]
I asked Ryan to try disabling the reflection type info provider (which is a feature that speeds up incremental builds in debug project configs), by adding this to the project file (it will only affect arm64 in debug).

<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
  <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
</PropertyGroup>

If this works, please use it as a workaround until we investigate the issue. Adding @RealTommyKlein who would know if this is a known issue for ARM64.

**Comment by RealTommyKlein** [comment]
Yes, we have a bug open on this - the issue is with Debug ARM64 apps that consume another Debug component.  We correctly disable the reflection provider in the app since we know the .NET Native toolchain is being used, but components don't know what toolchain will be used and still use the provider.

**Comment by RyanSpark** [comment]
The suggestion of adding <EnableTypeInfoReflection>false</EnableTypeInfoReflection> worked.

As the project contains referenced projects, all the projects referenced required the same edit.

Thank you.

**Comment by hoffe86** [comment]
Any updates on this BUG?
I have also this issue with "Release|x86"

**Comment by RealTommyKlein** [comment]
@hoffe86 - if your issue is happening on Release x86, it sounds like a different issue.  `Microsoft.UI.Xaml.Markup.winmd`, which causes this issue, should never be loaded on Release builds unless you've also disabled the .NET Native Toolchain.  If `Microsoft.UI.Xaml.Markup.winmd` is getting loaded by your app, you could also try adding this to your projects (and I'd be very interested to see what's going on :smile: ):
```
<PropertyGroup>
  <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
</PropertyGroup>
```

**Comment by hoffe86** [comment]
@RealTommyKlein 
The .NET Native Toolchain is enabled, but it seems it is an issue with my working machine.
Over the weekend I tried to compile the same code base on another pc and there it worked without any issue.

On my working machine I cleaned up everything (obj, bin folder, .user setting and the cached nuget files) and repaired the VS installation without any success.

``` xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <DefineConstants>TRACE;RELEASE;NETFX_CORE;WINDOWS_UWP;CODE_ANALYSIS</DefineConstants>
    <Optimize>true</Optimize>
    <NoWarn>;2008</NoWarn>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x86</PlatformTarget>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <ErrorReport>prompt</ErrorReport>
    <Prefer32Bit>true</Prefer32Bit>
    <UseDotNetNativeToolchain>true</UseDotNetNativeToolchain>
    <CodeAnalysisRuleSet>
    </CodeAnalysisRuleSet>
  </PropertyGroup>
```

Tried also to add "EnableTypeInfoReflection" without success,

**Comment by ShaneOss** [comment]
I also had this issue on x64. Adding fixed the issue for me for now.
<EnableTypeInfoReflection>false</EnableTypeInfoReflection>
