### ISSUE TITLE
ProgressRing get's announced as image

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2049]
**Describe the bug**

Using narrator, the ProgressRing get's announced as image, not as ProgressRing with a percentage.

**Steps to reproduce the bug**

1. Start Narrator
2. Open MUXControlsTestApp
3. Navigate to ProgressRing page
4. Tab to the ProgressRing, oberserve that it gets anounced as image.

**Expected behavior**

When the progressring is indeterminate, it should get announced as "busy progressring", otherwise it should announce it's progress like the ProgressBar 

**Screenshots**

**Version Info**

NuGet package version: 

Latest commit on master

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19596)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

When opening the XAML Controls Gallery, the ProgressRing gets announced correctly.

**Comment by ranjeshj** [comment]
ProgressRing needs to implement an automation peer just like ProgressBar
