### ISSUE TITLE
pull/#1223 causes theme inconsistencies and breaking changes

### ISSUE THREAD

**Issue by LeadAssimilator** [microsoft/microsoft-ui-xaml#2053]
**Describe the bug**

#1223 introduces breaking and inconsistent object types for ToggleSwitch control properties.  Specifically ToggleSwitchFillOnPointerOver, ToggleSwitchFillOnPressed, ToggleSwitchStrokeOnPointerOver, ToggleSwitchStrokeOnPressed defaults changed from Brush to Color, but are still treated as Brushes in subsequent states.  

This inconsistency is confusing since one would expect the properties to not change type based on state.  It also differs from generic.xaml that most people reference since that uses Brush, not Color.  Lastly it breaks existing code expecting these properties to be Brushes and to always be Brushes. See xamarin/Xamarin.Forms#9694.

**Steps to reproduce the bug**

1. Inspect #1223
2. Observe inconsistent property types

**Expected behavior**
ToggleSwitchFillOnPointerOver to always be a Brush
ToggleSwitchFillOnPressed to always be a Brush
ToggleSwitchStrokeOnPointerOver to always be a Brush
ToggleSwitchStrokeOnPressed to always be a Brush

**Version Info**

NuGet package version: 
2.2.190830001 and later

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

There may be similar inconsistencies and breaking changes lurking in other controls in the referenced and/or other commits.

**Comment by StephenLPeters** [comment]
Looking at the commit this definitely looks wrong, do you feel comfortable making the fix yourself and submitting the PR since you have the context @LeadAssimilator? I think it is probably as simple as changing the theme dictionary to reference a brush for those 4 types.

**Comment by LeadAssimilator** [comment]
I didn't see existing brushes referencing SystemAccentColorLight1 and SystemAccentColorDark1 that could be easily referenced.  While I could certainly add some brushes, I'm not entirely sure what to name them or where to put them ideally.  While each control could redefine the same two brushes over and over, it would be better if only two brushes could be added in some common location and referenced everywhere since this issue affects many more controls and properties as indicated below.

#### Controls
CheckBox
Button
RadioButton
ToggleButton
ToggleSwitch
Slider
SplitButton

#### Properties
CheckBoxCheckBackgroundStrokeCheckedPointerOver
CheckBoxCheckBackgroundStrokeCheckedPressed
CheckBoxCheckBackgroundStrokeIndeterminatePointerOver
CheckBoxCheckBackgroundStrokeIndeterminatePressed
CheckBoxCheckBackgroundFillCheckedPointerOver
CheckBoxCheckBackgroundFillCheckedPressed
CheckBoxCheckBackgroundFillIndeterminatePointerOver
CheckBoxCheckBackgroundFillIndeterminatePressed

AccentButtonBackgroundPointerOver
AccentButtonBackgroundPressed

RadioButtonOuterEllipseCheckedStrokePointerOver
RadioButtonOuterEllipseCheckedStrokePressed
RadioButtonOuterEllipseCheckedFillPointerOver
RadioButtonOuterEllipseCheckedFillPressed

ToggleButtonBackgroundCheckedPointerOver

ToggleSwitchFillOnPointerOver
ToggleSwitchFillOnPressed
ToggleSwitchStrokeOnPointerOver
ToggleSwitchStrokeOnPressed

SliderThumbBackgroundPointerOver
SliderThumbBackgroundPressed

SplitButtonBackgroundCheckedPointerOver

**Comment by chingucoding** [comment]
The fact that those colors (SystemAccentColorLight1 etc) don't have corresponding SystemBrushes was the reason why the colors were used.

I think one place to put them is in a separate file in the CommonStyles folder (e.g. it could be called "CommonBrushes". We could also place it in the "Button_themeresource.xaml" file as the AccentButton style also is in that file, and it makes use of those colors, hence one might search for them in that file.

Regarding the naming scheme:

SystemAccentColorLight1 -> SystemControlBackgroundAccentLight1Brush
SystemAccentColorLight2 -> SystemControlBackgroundAccentLight2Brush

would be a good way to name them to stay coherent with existing system brushes.

**Comment by StephenLPeters** [comment]
@kikisaints are you still the owner of this space? could you weigh in on the proper fix and proposed names?
