### ISSUE TITLE
Question: ElementName binding doesn't work in EntranceThemeTransition

### ISSUE THREAD

**Issue by aosyatnik** [microsoft/microsoft-ui-xaml#2054]
I'm not sure if it's a bug or I'm doing something wrong. In order to reproduce it you will need source code: https://github.com/aosyatnik/UWP_ElementNameBinding_Issue

# Steps to reproduce:
1. Build and run the app. You will see a list of 10 numbers and "Redraw" button.
2. Click on "Redraw" button. See, that the whole list is updated at once.
3. Go to `\Themes\Generic.xaml` and fine next code:
```xaml
<TransitionCollection>
   <!-- THIS BINDING IS NOT WORKING -->
   <EntranceThemeTransition IsStaggeringEnabled="{Binding ElementName=Items, Path=DataContext.IsStaggeringEnabled}"
                            FromVerticalOffset="-20"
                            FromHorizontalOffset="-20" />

   <!--<EntranceThemeTransition IsStaggeringEnabled="True"
                                FromVerticalOffset="-20"
                                FromHorizontalOffset="-20" />-->
</TransitionCollection>
```

4. Comment the first `EntranceThemeTransition` and uncomment the second `EntranceThemeTransition`. Code should look like this:
```xaml
<TransitionCollection>
   <!-- THIS BINDING IS NOT WORKING -->
   <!--<EntranceThemeTransition IsStaggeringEnabled="{Binding ElementName=Items, Path=DataContext.IsStaggeringEnabled}"
                                FromVerticalOffset="-20"
                                FromHorizontalOffset="-20" />-->

   <EntranceThemeTransition IsStaggeringEnabled="True"
                            FromVerticalOffset="-20"
                            FromHorizontalOffset="-20" />
</TransitionCollection>
```

5. Click on "Redraw" and see how each item is updated with animation one by one.

# Question:
Why binding of `IsStaggeringEnabled` is not working? `IsStaggeringEnabled` is presented in `MainViewModel` and set to `true`. The view model is bind to UI and I can see a collection of numbers, so the view model is working.

# Stackoverflow:
I also asked on stackoverflow, but people are suggesting to use `x:Bind`, but I can not do it, because it's templated control, do I?

https://stackoverflow.com/questions/60207057/uwp-elementname-binding-doesnt-work-in-entrancethemetransition

Possible duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/560 .

**Comment by ranjeshj** [comment]
Not quite sure if this related to #560. This seems to be specific to just element name bindings within a control template while the other is about reaching out of the data template in an items control.  @MikeHillberg @danzil  Is this a known limitation of what can be done within a control template ?

**Comment by chrisglein** [comment]
Seems like it should work. We need someone to get it under a debugger and figure out why this isn't working.

**Comment by aosyatnik** [comment]
Any updates on this? Is it a bug?
