### ISSUE TITLE
Discussion: [uwp] Will Microsoft ever admit when it's its fault?

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#2057]
# Discussion: [uwp] Will Microsoft ever admit when it's its fault?

Long story short, when I have a bug that is my own, and my app crashes, it's my responsibility. It was my fault -- I could have caught the exception or whatever, recovered and/or logged something, optionally shown something to the user and that's that.

But when the crash happens on some of Microsoft's assemblies, and the crash is FATAL (an Access violation, or C++ exception, or whatever), and I don't even get a warning, **will you Microsoft, stand up and take the blame?**

# .Net Exceptions

When i program .Net, I honestly don't care what happens behind the scenes. If there's an error, I expect to get a .Net exception. It's as simple as that - if you, Microsoft, don't deliver that, it's your fault.

The least you can do, is show that to the user.

# Stand up and take the Blame

Me - my app - can't do anything, since I don't even get any warning. To the user, **this is just a crash**. The user doesn't know it's NOT my fault.

What I expect is simple - when this happens, show some message box to the user, clearly stating it's Microsoft's fault, and that you're looking into it, and that you're sorry.

Even then, the user may still not care that much. But at least I can say - yeah, that was not my fault, and I'm looking for a workaround. As is right now, users will always blame my app and stop using it. 

And I'm really tired of fixing stuff I shouldn't have to, and wasting time not even knowing what I'm to fix, instead of actually doing development.

# Examples

Here are two examples, both ending up in crashes - #2056 and #1949. I know I'm far from alone in experiencing this, and lots of people just give up, instead of writing about it.

**Comment by robloo** [comment]
You are really testing the content moderators again. Let me go start the popcorn :) As I said in the past, I share several of your frustrations with the UWP/WinRT tooling (such as #1830). It happens to those of us that use it every day. 

Post WinUI 3.0, Microsoft needs to make quality/stability the number 1 priority and close the vast majority of severe bugs. If they don't I'm afraid widespread adoption is going to be a problem again.

Exception handling has always been an issue too and fixing that should be another priority. Perhaps it would be better to write this issue from that standpoint. Make WinRT exceptions clear at runtime (for the user) and when debugging applications (for the developer). Actually, I think there is already an issue for that some place. Exceptions don't get through the interop layer very well at all for managed apps.

**Comment by jtorjo** [comment]
@robloo 

> You are really testing the content moderators again. Let me go start the popcorn :) As I said in the past, I share several of your frustrations with the UWP/WinRT tooling (such as #1830). It happens to those of us that use it every day.

Yes, I totally agree. But when this happens on a user's machine -- I'm the one suffering. The user won't have the slightest clue that it's not my app's fault.

> Post WinUI 3.0, Microsoft needs to make quality/stability the number 1 priority and close the vast majority of ~severe~ bugs. If they don't I'm afraid widespread adoption is going to be a problem again.

Agree 100% here. But until WinUI 3.0, this - what I suggested here - , would be a decent compromise. 

> Make WinRT exceptions clear at runtime (for the user) and when debugging applications (for the developer). Actually, I think there is already an issue for that some place. Exceptions don't get through the interop layer very well at all for managed apps.

I'm totally ok with having WinRT exceptions clear at runtime, but I have a feeling that will take months to solve.
