### ISSUE TITLE
TwoPaneView.Mode dependency property doesn't update

### ISSUE THREAD

**Issue by sonnemaf** [Microsoft/microsoft-ui-xaml#206]
This Binding in Xaml doesn't show the changes of the Mode although I have set the binding mode to OneWay. The ModeChanged event is fired correctly.

**Steps to reproduce the bug**

The following code shows a TwoPaneView with in each pane 4 TextBlocks (Pane name, PageSize, Mode and Mode). The first Mode textBlock is set in the ModeChanged event (that works). he last Mode TextBlocks are databind (x:bind) to the mode of the TwoPaneView. That doesn't work. It always reports 'SinglePane'. Also if you resize the page.

```xml
<TwoPaneView x:Name="twoPaneViewDemo"
                Pane1Length="2*"
                Pane2Length="1*"
                PanePriority="Pane1"
                MinTallModeHeight="550"
                MinWideModeWidth="750"
                TallModeConfiguration="TopBottom"
                WideModeConfiguration="LeftRight"
                ModeChanged="TwoPaneViewDemo_ModeChanged">
    <TwoPaneView.Pane1>
        <Grid Background="Red"
                Padding="8"
                Margin="4">
            <StackPanel>
                <TextBlock Text="Pane 1"
                            Style="{StaticResource HeaderTextBlockStyle}" />
                <TextBlock x:Name="textBlockPageSize1"
                            Style="{StaticResource TitleTextBlockStyle}" />
                <TextBlock  x:Name="textBlockMode1"
                            Style="{StaticResource TitleTextBlockStyle}" />
                <TextBlock  Text="{x:Bind twoPaneViewDemo.Mode, Mode=OneWay}"
                            Style="{StaticResource TitleTextBlockStyle}" />
            </StackPanel>
        </Grid>
    </TwoPaneView.Pane1>
    <TwoPaneView.Pane2>
        <Grid Background="Blue"
                Padding="8"
                Margin="4">
            <StackPanel>
                <TextBlock Text="Pane 2"
                            Style="{StaticResource HeaderTextBlockStyle}" />
                <TextBlock x:Name="textBlockPageSize2"
                            Style="{StaticResource TitleTextBlockStyle}" />
                <TextBlock  x:Name="textBlockMode2"
                            Style="{StaticResource TitleTextBlockStyle}" />
                <TextBlock  Text="{x:Bind twoPaneViewDemo.Mode, Mode=OneWay}"
                            Style="{StaticResource TitleTextBlockStyle}" />
            </StackPanel>
        </Grid>
    </TwoPaneView.Pane2>
</TwoPaneView>
```

```csharp
private void Page_SizeChanged(object sender, SizeChangedEventArgs e) {
    textBlockPageSize1.Text = textBlockPageSize2.Text = $"Page Size {e.NewSize}";
}

private void TwoPaneViewDemo_ModeChanged(TwoPaneView sender, object args) {
    textBlockMode1.Text = textBlockMode2.Text = $"Mode {sender.Mode}";
}
```

**Expected behavior**
See the same Mode value in the last Mode TextBlock as the first one.

**Screenshots**

![image](https://user-images.githubusercontent.com/9335559/51444819-0ce2bb00-1cfd-11e9-8d22-416b8b7c226d.png)

**Version Info**
I'm using the TwoPaneView of the 18312 Insider Build SDK. It works correctly with the TwoPaneView from the NuGet package 2.1.181217001-prerelease.

NuGet package version: 
18312 Insider Build SDK

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18317)                 | Yes                        |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |

**Additional context**

**Comment by jevansaks** [comment]
Thanks for the bug report! @teaP can you take a look to see if this was fixed or perhaps there's a bug with the logic when compiled in the OS?

**Comment by sonnemaf** [comment]
The bug is not fixed in the new 18137 SDK.

**Comment by ranjeshj** [comment]
Thanks for reporting. This is indeed a bug - in the markup compiler. In the mean time you can use Binding to workaround the issue. 

<TextBlock  Text="{Binding ElementName='twoPaneViewDemo', Path='Mode', Converter={StaticResource 'converter'}, Mode=OneWay}"  />
    public class MyConverter: IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            return value.ToString();
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }

**Comment by sonnemaf** [comment]
The bug is solved in the new 18323 SDK. Thanks!
