### ISSUE TITLE
Discussion: Darken the background color of active textboxes in dark mode

### ISSUE THREAD

**Issue by skyanchor** [microsoft/microsoft-ui-xaml#2068]
# Discussion: Darken the background color of active textboxes in dark mode 

The background color of a windows page is usually black or dark gray when in dark mode. A white colored textbox might be too flashy, especially when the textbox is wide and large, say the ones in feedback hub.
One possible workaround is setting the background color a little lighter than one for the page background, and put the text inside the textbox white.

**Comment by mdtauk** [comment]
I would rather the default ApplicationPageBackground colour be changed to a very Dark Grey, instead of pure black. #807 #920

**Comment by chingucoding** [comment]
I think what @skyanchor refers to is more like #2046 and #142 .

**Comment by mdtauk** [comment]
> I think what @skyanchor refers to is more like #2046 and #142 .

In which case he is going to be happy soon :)

**Comment by JohnnyWestlake** [comment]
> I would rather the default ApplicationPageBackground colour be changed to a very Dark Grey, instead of pure black. #807 #920

As someone with an OLED laptop, I really pray this doesn't happen. I get enough of this useless dark mode from Google on my Android phone with all it's dark greys rather than black 😅

**Comment by mdtauk** [comment]
> > I would rather the default ApplicationPageBackground colour be changed to a very Dark Grey, instead of pure black. #807 #920
> 
> As someone with an OLED laptop, I really pray this doesn't happen. I get enough of this useless dark mode from Google on my Android phone with all it's dark greys rather than black 😅

Issue #807 which I submitted, calls out OLED as a possible exception

**Comment by chigy** [comment]
This is now fixed.
https://docs.microsoft.com/en-us/uwp/toolkits/winui/release-notes/winui-2.4
