### ISSUE TITLE
TreeView parent indeterminate mode not working when...

### ISSUE THREAD

**Issue by tedrog36** [microsoft/microsoft-ui-xaml#207]
Take a TreeView and specify the ItemContainerStyle using the style from Generic.xaml included in the Nuget package.  I changed nothing in the style and the indeterminate state in the parent nodes stop working.  They remain in the checked state.

FYI: the reason I want to edit a copy of the style is that I want the tree view to take the entire width so I want to use a Grid instead of a StackPanel in the TreeViewItem control template.

Example project attached.

**Expected behavior**
You should be able to modify the style and keep the indeterminate state functionality.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.181217001-prerelease

April 2018 Update (17134)

\
Desktop

**Additional context**
Demo project:

[TreeViewIndeterminateBug.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2780126/TreeViewIndeterminateBug.zip)

**Comment by jevansaks** [comment]
Sounds very similar to #203 , if that was working you probably wouldn't need to retemplate. But very weird that retemplating causes this issue.

**Comment by tedrog36** [comment]
@jevansaks What I discovered was that the template I grabbed from the Nuget packages generic.xaml or from creating a template copy in VS did not include the indeterminate checkbox states.  I was able to modify that from the template in the GitHub project and got it to work.

**Comment by kaiguo** [comment]
I just checked generic.xaml file in the latest stable NuGet package (2.2.190917002) and I think it contains the right style now. 

Also, #218 removed the internal StackPanel so hopefully you don't need to re-template any more.
