### ISSUE TITLE
Blank App (C++/WinRT) project begins with “winrt_”

### ISSUE THREAD

**Issue by stevewhims** [microsoft/microsoft-ui-xaml#2070]
Just passing along feedback from a customer (for context, and customer contact info for repros/questions/whatnot, please see https://github.com/MicrosoftDocs/windows-uwp/issues/2254).

It seems that if the name of a new Blank App (C++/WinRT) project begins with “winrt_” (lower-case), then the build fails. I’ve pasted in the details from the original issue.

It is related to the name of the solution. I've tried a few solution names and here is the result:
HelloWinUICppWinRT >> success
HelloWinUI_CppWinRT >> success
HelloWinUI >> success
WinRTBlank >> success
winrt_blank >> fail
winrt_demo >> fail
win_rt_demo >> success

This is the build output in the fail cases:

1>Processing input metadata file Debug\Unmerged\App.winmd.
1>Processing input metadata file Debug\Unmerged\MainPage.winmd.
1>Processing input metadata file Debug\Unmerged\XamlMetaDataProvider.winmd.
1>Saved output metadata file winrt_demo.winmd.
1>Validating metadata file Debug\Merged\winrt_demo.winmd.
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(308,5): Xaml Internal Error error WMC9999: Name should contain ::winrt prefix
1>Done building project "winrt_demo.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by stevewhims** [comment]
Is this issue still relevant? Should I keep it open (in which case should it be assigned to someone?), or should I close it?

Many thanks!
Steve

**Comment by RealTommyKlein** [comment]
@stevewhims - I'll assign it to myself, thanks!

**Comment by Scottj1s** [comment]
Closing this due to low customer impact and available workaround
