### ISSUE TITLE
ComboBox.ItemSource does not support binding to IObservableCollection<MyStruct>, unlike ListView and others (c++/winrt)

### ISSUE THREAD

**Issue by axodox** [microsoft/microsoft-ui-xaml#2073]
**Describe the bug**
ComboBox.ItemSource does not support binding to IObservableCollection<MyStruct> where MyStruct is a struct, unlike ListView, where this works, it results in exceptions, or in best case produces no items in the drop down. I have tried both setting *MemberPath and also specifying ItemTemplate, but it does not work. The same exact binding works flawlessly in ListView, so I think this is a bug in winUI.

**Steps to reproduce the bug**
In c++/winrt I have defined a struct in IDL and used it in a viewmodel, e.g.:

```
struct GraphicsAdapterInfo
  {
    String Name;
    UInt64 Id;
    Boolean IsActive;
  };

  struct GraphicsProfileInfo
  {
    String Name;
    Boolean IsActive;
  };

  [default_interface]
  runtimeclass SettingsViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
  {
    Windows.Foundation.Collections.IObservableVector<GraphicsAdapterInfo> GraphicsAdapters{ get; };
    Int32 SelectedGraphicsAdapterIndex;

    Windows.Foundation.Collections.IObservableVector<GraphicsProfileInfo> GraphicsProfiles{ get; };
    Int32 SelectedGraphicsProfileIndex;

    Boolean IsRestartRequired{ get; };
    void Restart();

    SettingsViewModel(IViewModelContext context);
  };
```

GraphicsAdapters and GraphicsProfiles can be bound in xaml properly with ListView, but not with ComboBox

**Expected behavior**
Should work like in ListView with the ItemTemplate.

**Screenshots**
In most cases the app fails to luanch, or no items show up in combobox.

**Version Info**

NuGet package version: 
c++/winrt (2.0.190730.2)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@axodox can you share the failure callstack ? This could possible be related to [this winrt cpp issue](https://github.com/microsoft/cppwinrt/pull/544).
