### ISSUE TITLE
an empty NavigationView panel slides in from the right side, when used in top configuration on Hololens 2 when used with an xbox controller

### ISSUE THREAD

**Issue by axodox** [microsoft/microsoft-ui-xaml#2074]
**Describe the bug**
As it says in the title. It happens every time when use it in a 2d app on HoloLens 2 and a bluetooth connected xbox controller, I use pivot instead for now. It is strange since I have used the top layout, and still an empty opaque panel slides over my content.

**Steps to reproduce the bug**
Create a navigation panel on a blank xaml app, set it to use top layout instead of left side. Get a HoloLens 2, and pair an xbox controller, open the app (maybe repeatedly) and it start happening. I could not reproduce the issue on desktop or without the controller.

Please note that I have used the 2d app as a secondary view in an immersive HoloLens app, the issue started happening when I closed and reopened the view with the controller.

I expect you can check how the left panels, background could slide in when in top configuration. Please note that this also happens in left configuration as well, in that case it does slide over the actual open panel with items, and occcludes it with an empty panel.

**Expected behavior**
The left panel cannot be displayed in top confgiuration in any way, anywhere, with any input device.

**Screenshots**

I do not have the device at me anymore.

**Version Info**

NuGet package version: 

I am using Windows SDK 18362 with c++/winrt + xaml.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Windows Holographic 2020 2B (february update)              | Yes  |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| HoloLens 2                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@axodox Are you using **Microsoft**.UI.Xaml.Controls.NavigationView from the WinUI nuget package or **Windows**.UI.Xaml.Controls.NavigationView ? Some screenshots, video would be helpful to understand the issue.

**Comment by axodox** [comment]
Windows.UI.Xaml.Controls.NavigationView from the windows sdk

**Comment by ranjeshj** [comment]
@axodox Can you give the one from WinUI [prerelease package](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.4.0-prerelease.200203002) a try ? There have been several fixes made to that control compared to the one that shipped in the Windows namespace.
