### ISSUE TITLE
UWP : NullReferenceException when hitting a key in a ComboBox

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/937424/uwp-nullreferenceexception-when-hitting-a-key-in-a.html)._

---
<p>Hi,</p><p>
I have a UWP project targeting the 1903 SDK.</p> <p>On the MainPage, I have a ComboBox.
The ItemsSource property of the ComboBox is bound to a collection of a nullable enums.</p> <p>
The SelectedItem property of the ComboBox is bound to a nullable enum. I use a do-nothing converter to allow the compilation of this binding.</p> <p>When I run the application, If I hit a key when the ComboBox is focused, my application crashes with a NullReferenceException.</p> <p>The error message is &quot;Invalid pointer&quot;. There is no stack trace.</p> <p>As this happens in a big application, I created a small repro project. Please find it in the &quot;<a href="https://developercommunity.visualstudio.com/storage/attachments/121408-reproinvalidpointer.zip">reproinvalidpointer.zip</a>&quot; attached file.</p> <p>
My Visual Studio is upgraded to the latest version.
My Windows 10 is up to date... </p> <p>Could you please fix this bug and / or provide a workaround ?</p> <p>Thanks,</p>

---
#### Visual Studio Feedback System on 3/3/2020, 03:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Svet Bonev [MSFT] on 3/4/2020, 02:26 PM: 

<p>Hello! Thank you for your feedback.</p>
<p>I was able to reproduce the crash with your sample app.<br>
I have a question, though, was there a reason to include ‘null’ in the list of items?<br>
Removing the ‘yield return null;’ line resolves the issue.</p>
<p>Best regards,<br>
Svet Bonev<br>
Visual Studio Client Tools</p>

#### Nicolas Séveno on 3/5/2020, 01:41 AM: 

<p>Hi,</p><p>Yes, there is a reason. The property in the model and the column in the database are nullable. The null item in the ComboBox allows the user to put a null in the property (even after a value has been selected). If I remove the null item, and a non null value is selected in the combo, then the user is unable to set null in the property...</p><p>I know nullable enums are not a good practice. But we also have problems with ComboBoxes bound to nullable Guids that we use for primary keys in the database...</p>

#### Svet Bonev on 3/6/2020, 01:46 PM: 

<p>Hi Nicolas,<br>
The Windows team has acknowledged that this is a bug in the ComboBox control.<br>
Until that bug is fixed, I would recommend you to use a workaround, for example, to wrap the nullable items in non-nullable objects.</p>
<p>I will close this feedback report and open an issue for it in the microsoft-ui-xaml repo on github.</p>
<p>Best regards,<br>
Svet Bonev<br>
Visual Studio Client Tools</p>

---
### Original Solutions
(no solutions)

**Comment by ranjeshj** [comment]
Simplified repro.

```
Xaml markup:
        <ComboBox x:Name="cmb" Margin="100"/>

C# code:
    public sealed partial class MainPage : Page
    {
        private List<string> items = new List<string>();

        public MainPage()
        {
            this.InitializeComponent();
            items.Add("One");
            items.Add("Two");
            items.Add(null);
            items.Add("Three");
            cmb.ItemsSource = items;
        }
    }
```

**Comment by chingucoding** [comment]
While it should definitely not crash, what exactly should happen for null? What should we display? "" or "null"?

I am not quite sure if there is a sensible way to to support null as value.

**Comment by nseveno** [comment]
@chingucoding for me it doesn't really matter what is displayed by default. Because I will often use an ItemTemplate with a TextBlock and a converter to display something like "<None>" or "<All>" or "<Null>"... The really important thing is that the application does not crash and that the ItemTemplate works !

**Comment by chingucoding** [comment]
@nseveno Yes the application should definitely not crash. However we have to define some default behavior for that case.

**Comment by nseveno** [comment]
As a "basic" developper, I would expect "". Because if you bind a textbox to a numeric nullable value, the displayed value for the null value is "".

**Comment by RBrid** [comment]
I put in a fix for the next WinUI 3 release.  The app will no longer crash. Thanks!
