### ISSUE TITLE
Discussion: Differences between Debug and Release builds

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#2086]
It can be a bit of a surprise when you see different behaviors between Debug and Release builds (as in the case of #1949). This is an attempt to document any existing such behavior differences in one place (and evaluate if there is a better way to achieve the same results without these differences). 

1. Markup compiler uses reflection based provider instead of code gen to speed up debug builds. This behavior can be changed by adding <EnableTypeInfoReflection>false</EnableTypeInfoReflection> to the project file.

2. Release builds use .Net Native tool chain to improve performance.

Other ?

**Comment by jevansaks** [comment]
We should probably elaborate on what is different with .NET Native. Specifically we've seen ARM64 codegen issues in .NET Native and you have to sometimes use the rdinfo.xml file to customize what types are included for reflection.
