### ISSUE TITLE
MUXControls.TestApp Interaction Tests fail to run if Windows SDK was installed in a custom location

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2088]
**Describe the bug**
When trying to run [interaction tests](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/developer_guide.md#automated-testing) the operation fails because the referenced `Windows.winmd` file cannot be found. 

![image](https://user-images.githubusercontent.com/1398851/76245153-acce1180-623b-11ea-9d85-aa6a97f0f50e.png)

The error message VS gives me is the following: `C:\Program Files (x86)\Programming\IDEs\VS2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Windows.winmd". Check to make sure the assembly exists on disk.`

**Why this happens**
I have installed the Windows 10 SDK in a custom location and not the standard `C:\Program Files (x86)\Windows Kits` location. Looking into the MUXControls.Test.Shared.projitems file I see the following line: `<WindowsMetadataPath>$(UniversalCRTSdkDir)\UnionMetadata\$(TargetPlatformVersion)</WindowsMetadataPath>` with `UniversalCRTSdkDir` defined as: `<UniversalCRTSdkDir Condition="'$(UniversalCRTSdkDir)' == ''">$(MSBuildProgramFiles32)\Windows Kits\10</UniversalCRTSdkDir>` (line directly above).

The [documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2019) for `MSBuildProgramFiles32` says:
![image](https://user-images.githubusercontent.com/1398851/76246217-8e691580-623d-11ea-95cc-60d67c0cf764.png)
 
So MUXControls.TestApp ends up looking in location `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\$(TargetPlatformVersion)` for the Windows.winmd file, yet as I mentioned at the beginning, I installed the Windows 10 SDK in a non-standard location. 

In order to find the Windows metadata file and thus run the interaction tests, I am currently overwriting the definition of the UniversalCRTSdkDir entry in the `MUXControls.Test.Shared.projitems` file to point to the correct windows 10 SDK location (which in my case is D:\Windows Kits\10). Now that I changed that file I have to be careful not to accidentally include this change in every commit I will make to the WinUI repo (as it would break the setup for others). As such, it would be great if WinUI itself could update the file so that the Windows 10 metadata file will be found even if the SDK location differs from the standard location.

Note: There might also be a solution using VS. I've read that one can run %VSInstallDir%\Common7\Tools\VsDevCmd.bat file to set directories like `UniversalCRTSdkDir`. If this works (haven't tested it here) this could be an alternative to changing the MUXControls.Test.Shared.projitems file in case that should prove challenging. In this case, documentation should be added though in the [Testing](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/developer_guide.md#testing) paragraph.

**Comment by Felix-Dev** [comment]
Found this thread on github with the same problem and a proposed solution. Perhaps it can be of help: https://github.com/microsoft/vcpkg/issues/8288

**Comment by Felix-Dev** [comment]
(pinging @StephenLPeters again as I'm not sure he saw the recent edits after my first ping 😅)

**Comment by StephenLPeters** [comment]
@ranjeshj do you know why @Felix-Dev 's comment did not add the needs triage tag back on? shouldn't the bot be adding it in this case?

**Comment by StephenLPeters** [comment]
I'd still like @llongley or @kmahone to weigh in but I think the proposed solution seems okay? i'd say go ahead and open the PR! thanks :D!

**Comment by ranjeshj** [comment]
> @ranjeshj do you know why @Felix-Dev 's comment did not add the needs triage tag back on? shouldn't the bot be adding it in this case?

It should have. Not sure why it did not. 

@Felix-Dev, the fix looks reasonable to me as long as it goes through the build pipeline fine without issues.

**Comment by Felix-Dev** [comment]
Alright, added a [PR](https://github.com/microsoft/microsoft-ui-xaml/pull/2099). Let's see how it will go 😆
