### ISSUE TITLE
TextBox control hides content when the number of characters in the control passes certain threshold

### ISSUE THREAD

**Issue by unparadise** [microsoft/microsoft-ui-xaml#2097]
**Describe the bug**

TextBox control hides content when the number of characters in the control passes certain threshold.

**Steps to reproduce the bug**

1. Go to "Store" and download the "Notepads" app.
2. Copy a large body of text into a new file.
3. Notice that once the number of characters in the control passes a certain threshold, the content disappears completely.

**Expected behavior**

The content in the control should not disappear regardless the size of the file.

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by JohnnyWestlake** [comment]
Related to GPU/XAML maximum texture sizes on a single element? Used to be quite common back on Windows Phone, though it's maximum size was a lot lower.

I ran into this a few days ago too and had to split the content in my TextBlocks to work around it.
