### ISSUE TITLE
UWP / C++ Style is not applied to a TabView and TabViewItem as expected

### ISSUE THREAD

**Issue by SteveWeavers** [microsoft/microsoft-ui-xaml#2100]
Create a Windows Runtime Component (C++/WinRt)

Use the following styles in App.xaml

![image](https://user-images.githubusercontent.com/62107501/76534907-7b7a5f00-6450-11ea-941a-09f459655083.png)

Create a TabView in a XAML userControl

<UserControl
    x:Class="UWPApplication.TabControl"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    xmlns:local="using:UWPApplication"
    mc:Ignorable="d">

    <Grid>
        <controls:TabView Name="tabViewControl" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" SelectionChanged="tabViewControl_SelectionChanged" >
            <controls:TabViewItem Name="PreviewTab" Header="Preview" />
            <controls:TabViewItem Name="DataCardTab" Header="Data card" />
            <controls:TabViewItem Name="VersionTab" Header="Version"/>
            <controls:TabViewItem Name="BomTab" Header="Bill of Materials">
                <Grid Height="400" HorizontalAlignment="Left" VerticalAlignment="Stretch">
                    <ScrollViewer VerticalAlignment="Stretch"  VerticalScrollMode="Auto"  VerticalScrollBarVisibility="Auto">
                        <GridView x:Name="BomGrid" ItemsSource="{x:Bind Src}"  CharacterSpacing="0"  Padding="0" Margin="0" FocusVisualMargin="0" HorizontalAlignment="Stretch"  VerticalAlignment="Stretch"  FlowDirection="LeftToRight"  VerticalContentAlignment="Stretch" Width="600">
                            <GridView.HeaderTemplate>
                                <DataTemplate>
                                    <StackPanel Margin="0" Orientation="Horizontal" Height="30"  BorderThickness="0,0,0,2" BorderBrush="Black">
                                        <TextBlock Text="Item" Height="30" Width="100" HorizontalTextAlignment="Left" FontSize="13" FontFamily="Segoe UI"/>
                                        <TextBlock Text="Quantity" Height="30" Width="100" HorizontalTextAlignment="Left" FontSize="13" FontFamily="Segoe UI"/>
                                        <TextBlock Text="Item cost" Height="30" Width="100" HorizontalTextAlignment="Left" FontSize="13" FontFamily="Segoe UI"/>
                                        <TextBlock Text="Total cost" Height="30" Width="100" HorizontalTextAlignment="Left" FontSize="13" FontFamily="Segoe UI"/>
                                    </StackPanel>
                                </DataTemplate>
                            </GridView.HeaderTemplate>
                            <GridView.ItemTemplate>
                                <DataTemplate x:DataType="local:BomItemViewModel">
                                    <StackPanel Height="23" Margin="0" Orientation="Horizontal" Padding="0" VerticalAlignment="Center" Background="AliceBlue">
                                        <TextBlock Text="{x:Bind ItemName}" Height="23" Width="100" HorizontalTextAlignment="Left" FontSize="11"  FontFamily="Segoe UI" />
                                        <TextBlock Text="{x:Bind Quantity}" Height="23" Width="100" HorizontalTextAlignment="Left" FontSize="11" FontFamily="Segoe UI"/>
                                        <TextBlock Text="{x:Bind ItemCost}" Height="23" Width="100" HorizontalTextAlignment="Left" FontSize="11" FontFamily="Segoe UI"/>
                                        <TextBlock Text="{x:Bind TotalCost}" Height="23" Width="100" HorizontalTextAlignment="Left" FontSize="11" FontFamily="Segoe UI"/>
                                    </StackPanel>
                                </DataTemplate>
                            </GridView.ItemTemplate>
                            <GridView.FooterTemplate>
                                <DataTemplate x:DataType="local:BomViewModel">
                                    <StackPanel Margin="0" Orientation="Horizontal" Height="30"  BorderThickness="0,1,0,2" BorderBrush="Black">
                                        <TextBlock Text="Total Cost: " Height="30" Width="300" HorizontalTextAlignment="Left" FontSize="13" FontFamily="Segoe UI"  FontWeight="Bold"/>
                                        <TextBlock Text="{x:Bind TotalCost}" Height="30" Width="100" HorizontalTextAlignment="Left" FontSize="13" FontFamily="Segoe UI"/>
                                    </StackPanel>
                                </DataTemplate>
                            </GridView.FooterTemplate>
                        </GridView>
                    </ScrollViewer>
                </Grid>
            </controls:TabViewItem>
            <controls:TabViewItem Name="ContainsTab" Header="Contains"/>
            <controls:TabViewItem Name="WhereTab" Header="Where Used"/>
        </controls:TabView>
    </Grid>
</UserControl>

Expect to see:

![image](https://user-images.githubusercontent.com/62107501/76533122-f42bec00-644d-11ea-92a4-26f2e9925ee3.png)

Actually see:
![image](https://user-images.githubusercontent.com/62107501/76533344-4a009400-644e-11ea-849b-30cd69c5bf7f.png)

**Version Info**
Microsoft Visual Studio Professional 2019   Version 16.4.5
Microsoft.UI.Xaml   2.4.0-prerelease.200203002

Windows 10 Enterprise  Version 1903 OS build 18362.657

Using Desktop device.

Implementing as a XAML Island
Microsoft.Toolkit.Win32.UI.XamlApplication 6.00 

Full example code is at 
https://filetransfer.dsone.3ds.com/Workspace.aspx?id=AE97B24FF219F5B770FC41C6739A4986

**Comment by ranjeshj** [comment]
TabViewHeaderForeground theme resource is currently not being used in the TabView's template which is likely what is causing this issue.

**Comment by stmoy** [comment]
> TabViewHeaderForeground theme resource is currently not being used in the TabView's template which is likely what is causing this issue.

In the pictures above, foreground is the *only* thing that is being set correctly 😅  I disagree with this assessment. 

However, I do wonder if there is a way to achieve the visual effect desired using lightweight styling instead. For example:

``` xml
<muxc:TabView TabWidthMode="SizeToContent">
    <muxc:TabView.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Light">
                    <SolidColorBrush x:Key="TabViewItemHeaderBackground" Color="LightGreen"/>
                    <x:Double x:Key="TabViewItemHeaderFontSize">23</x:Double>
 
                    <!-- Why doesn't this one work? -->
                    <SolidColorBrush x:Key="TabViewItemHeaderForeground" Color="Blue"/>
                </ResourceDictionary>
                <ResourceDictionary x:Key="Dark">
                    <SolidColorBrush x:Key="TabViewBackground" Color="{ThemeResource SystemAccentColorDark2}"/>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </muxc:TabView.Resources>
 
    <muxc:TabView.TabItems>
        <muxc:TabViewItem Header="Preview" Content="Hello" />
        <muxc:TabViewItem Header="Data Card" Content="Hello" />
        <muxc:TabViewItem Header="Version" Content="Hello" />
    </muxc:TabView.TabItems>
</muxc:TabView>

```

Produces: 
![tabview](https://user-images.githubusercontent.com/25991996/76576169-8fd55080-647e-11ea-9015-ab20ae0465ab.png)

Which is almost right. The only thing missing is the foreground color, which is broken per the Ranjesh's comment. 

@SteveWeavers - if we provided a solution using lightweight styling instead of Style, would that satisfy the scenario?

**Comment by SteveWeavers** [comment]
This solution did produce the correct result (even the foreground color  worked for me). This also produced the same result in a C# XAML island. We can proceed using this method.
Are there any plans to support global styles in the future?

**Comment by SteveWeavers** [comment]
Steven

               Thanks for this. I tried it in my test application and it did work, even the foreground color.
               I tried the same thing in the C# XAML island test application with the same result.
               This will allow us to move forward.

               I’ve put a comment on github to this effect.

               Will there be support for global styles in the future? This is useful where there are many instances of a control type (button for example) with perhaps elaborate styling. They are also useful where we want a consistent style across multiple projects.

Steve

**Comment by SteveWeavers** [comment]
I am having the same issue with a Pivot control. I have not been able to set the foreground color. With a Pivot the style does not work for Foreground either.

            <controls:Pivot.Resources>
                <ResourceDictionary>
                    <Style TargetType="controls:PivotItem">
                        <Setter Property="Foreground" Value="Blue"/>  
                    </Style>
                    <ResourceDictionary.ThemeDictionaries>
                        <ResourceDictionary x:Key="Light">
                            <SolidColorBrush x:Key="PivotHeaderForground" Color="Blue"/>        
                            <SolidColorBrush x:Key="PivotHeaderBackground" Color="LightGreen"/>
                            <x:Double x:Key="PivotHeaderFontSize">23</x:Double>
                        </ResourceDictionary>
                        <ResourceDictionary x:Key="Dark">
                            <SolidColorBrush x:Key="PivotBackground" Color="AliceBlue"/>
                        </ResourceDictionary>
                    </ResourceDictionary.ThemeDictionaries>
                </ResourceDictionary>
            </controls:Pivot.Resources>

Produces:
![image](https://user-images.githubusercontent.com/62107501/77574448-64a02780-6ea8-11ea-955f-8945bff08403.png)

This is using 2.4.0-prerelease.200322001 version of Microsoft.UI.Xaml
Is there a date for the release of 2.4.0 ?
