### ISSUE TITLE
XAML Islands: Certain mouse events appear to be scaled incorectly on High-DPI displays

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#2101]
**Describe the bug**

This is being filed to track the following bug in the Windows Terminal: https://github.com/microsoft/terminal/issues/2606

For XAML Islands, it seems that there are a few bugs related to mouse input on high-dpi displays. 
* With "scroll inactive window when I hover over them" disabled, and the terminal focused on a high-dpi display, the bottom-right of the monitor can't be used to scroll the window
![image](https://user-images.githubusercontent.com/18356694/76543018-e5483800-6453-11ea-9511-f901479e49d1.png)
* The same region can't be used to drag and drop files into the Terminal
* Mentioned offline was talk that drag events weren't being scaled correctly on high-DPI displays.

**Steps to reproduce the bug**
(see above issue)

**Expected behavior**
* The whole Island should be a valid drag-drop target
* The whole island should be able to be scrolled while "scroll inactive window when I hover over them" is disabled

**Version Info**

NuGet package version: `Microsoft.UI.Xaml.2.3.191217003-prerelease

I'm seeing this on Microsoft Windows [Version 10.0.19578.1000], RS_ONECORE_DEP, though this has been around for months.

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |  n/a |
| Xbox                      | n/a  |
| Surface Hub          | n/a    |
| IoT                         | n/a    |

**Additional context**

I've previously discussed this with @Austin-Lamb and @ocalvo

**Comment by Austin-Lamb** [comment]
Thanks for filing this.  We won't be able to fix this until WinUI 3.

@zadjii-msft - if this is a top issue for Terminal let's discuss more to see if there's anything else we can do but I'm not optimistic.

**Comment by zadjii-msft** [comment]
FYI to whoever is on WinUI triage these days: This was promoted internally to MSFT:35026617. It's apparently fixed in Windows 11 (at least from my own experimentation). It also didn't meet the bar for servicing to downlevel Windows 10. Based on that, we can probably close this one out (unless there's significant pushback from the community).
