### ISSUE TITLE
EffectiveViewport event not raised in XamlIsland scenario

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#2102]
This bug is to track the underlying framework issue causing #2095. #2095 will be used to make a targeted workaround for NavigationView to unblock the scenario.  Please see the linked bug for repro steps.

**Comment by Austin-Lamb** [comment]
I'm not sure which team worked on effective viewports, but it wasn't the reach team.  I think it was probably Controls or Framework - so guessing and re-assigning this to Controls.

**Comment by crutkas** [comment]
any movement on this?

**Comment by DHowett** [comment]
@ranjeshj ah, since #3642 was linked to this . . . is there a workaround? Terminal's not afraid to work around random Xaml Islands issues :smile:

**Comment by pziezio** [comment]
Any progress on that? It's over a year now...
Hierarchical NavigationView being broken combined with weird rendering of background in Flyouts, just that makes using XamlIslands in anything serious impossible.

Funny how MS advertises whole WinUI 2.x and 3.x stack as "production-ready" when both are just ridden with simple bugs 😄

**Comment by pratikone** [comment]
it appears that the PR above has fixed it. can you check. if not fixed, feel free to re-open this.
