### ISSUE TITLE
Proposal: Add custom sln file to enable using XCG for testing changes

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2109]
### Rationale

So currently, when one tries to test changes that are not in the Nuget package (e.g. for demos or bug fixes), they need to either grab the Nuget package from the CI pipeline or manually hook the XCG into the solution.

To make this easier for devs/PMs to try the latest builds in the XCG, we could provide a new sln file that maps to an existing XCG project.

### Schematic folder structure:
```
microsoft-ui-xaml/
└─MUXControlsXCGLoop.sln <-- Has a reference to "../Xaml-Controls-Gallery/.../XamlControlsGallery.csproj
Xaml-Controls-Gallery/
└─XamlControlsGallery/
     └─XamlControlsGallery.csproj <-- Based on the solution name, compiles either using nuget package OR using actual reference to "../.../microsoft-ui-xaml/.../Microsoft.UI.Xaml" project
```

### Requirements
That solution / csproj would assume that:
1. Both projects have the same root, i.e. that when cloning, they are cloned into the same root
2. Projects got cloned into a folder with the name being their GitHub name (without the organization). So WinUI sits in a folder called microsoft-ui-xaml and XCG sits in the folder "Xaml-Controls-Gallery"

That structure would require the following adjustements: 
1. Add a solution file in this repo with the correct reference
2. Modify XCG cs-project file to check for the solution it is loaded in and compile accordingly 

### Remarks
This solution would require certain requirements from the developers using them, and if the developer did not download the XCG in the folder with the right name, the solution wouldn't be able to load the file. However unless one does not need to use the XCG with the freshest build of WinUI, building projects the regular way would work, so we are not breaking/interfering existing workflows.

@ranjeshj @jevansaks @stmoy FYI

**Comment by ranjeshj** [comment]
Not sure why this did not show up in triage until now. Looks like the issue was filed in March 12th :0 .
One thought to avoid the duplicate solutions might be to add conditionals to the projects, just so we have less files to maintain

Very interesting idea. I'm not a huge fan of cross repo references. This sounds like a nice to have for sure.

**Comment by chingucoding** [comment]
Maybe a more appropriate way to solve this nice to have would be to have XCG as a git submodule reference? Given that VS and other clients usually don't clone submodules this should be fine. If someone wants to try changes out with the XCG, they can still do that.
