### ISSUE TITLE
NumberBox takes up space for header even when header is not specified

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2114]
When one does not specify a header for the NumberBox control, it still takes up a bit of space, despite it shouldn't. The following XAML snippet generates the following output:
```XAML
<StackPanel Orientation="Horizontal">
    <TextBox Height="30"/>
    <muxc:NumberBox Height="30"/>
</StackPanel>
```
![image](https://user-images.githubusercontent.com/16122379/76648492-13ff0500-655f-11ea-8e84-04b6a1557499.png)

WinUI version: 2.4.0-prerelease.200203002

**Comment by ranjeshj** [comment]
The TextBox likely takes up layout space even when there is no content. We could fix it by collapsing it the TextBox in this case, but this looks like a general issue with TextBox. Marcel, can you see if this repro's with just a TextBox ? If so, we need to file a bug on TextBox.

**Comment by chingucoding** [comment]
The problem I was trying to outline is the fact that the Header of our NumberBox takes up space. Thats why those two controls are not aligned correctly. From debugging that, it seems that the header has a 3px bottom margin, which is still being applied even if the header is not used, thus we have the gap here.

**Comment by ranjeshj** [comment]
I see. That makes sense.

**Comment by chingucoding** [comment]
I can take this issue, if that's okay.

**Comment by JohnnyWestlake** [comment]
Probably worth Delay/Lazy loading the header too like most of the other framework controls?

**Comment by chingucoding** [comment]
@JohnnyWestlake What exactly do you mean by delay/lazy loading the header? Do you have a control at hand, which currently does this? 😅

**Comment by japf** [comment]
@JohnnyWestlake do you mean use `x:Load`?

**Comment by chingucoding** [comment]
Oh, yes I see. I will add the `x:DeferLoadStrategy` to the header property of the NumberBox with that PR to align with other control's headers.

**Comment by Felix-Dev** [comment]
> Starting in Windows 10, version 1703 (Creators Update), x:DeferLoadStrategy is superseded by the x:Load attribute. Using x:Load="False" is equivalent to x:DeferLoadStrategy="Lazy", but provides the ability to unload the UI if required. See the x:Load attribute for more info.

What is the reason x:Load is not used here? It's available since 1703 which is the required minimum version an app consuming WinUI 2 needs to target.

**Comment by chingucoding** [comment]
The WinUI repo is not consistent here, some controls use x:Load, others use x:DeferLoadStrategy.
You might want to create an issue for this, since it might be better to only use x:Load instead of x:DeferLoadStrategy

**Comment by Felix-Dev** [comment]
@chingucoding Why are you deciding not to use x:Load here but instead older API? Is there precedence in NumberBox which is why you use x:DeferLoadStrategy? Otherwise, why not use x:Load?

**Comment by chingucoding** [comment]
> @chingucoding Why are you deciding not to use x:Load here but instead older API? Is there precedence in NumberBox which is why you use x:DeferLoadStrategy? Otherwise, why not use x:Load?

Simply to stay consistent within the file. Changing API's of areas that are not affected by this bug is not ideal, that's why for now I would like to keep the NumberBox files consistent. Changing from xDeferLoadStrategy to x:Load is something that needs to be done throughout multiple files within the project and thus should be a separate issue and PR.
