### ISSUE TITLE
FlyoutMenu crashes on Windows 10 < 1809

### ISSUE THREAD

**Issue by felixse** [microsoft/microsoft-ui-xaml#2115]
**Describe the bug**
FlyoutMenu crashes the app on Windows 10 below 1809 Update. Got reports from both 1803 and 1709 (minimum version of the app)

**Steps to reproduce the bug**
1. Download and install latest [Fluent Terminal (0.6.1.0)](https://github.com/felixse/FluentTerminal/releases/tag/0.6.1.0) on a  1803 machine
2. Click on the menu button in the left top corner

**Expected behavior**
Button flyout shows

**Version Info**

NuGet package version: 
reproduced with 2.2.190917002 and 2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | No   |
| May 2019 Update (18362)            | No   |
| October 2018 Update (17763)        | No   |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       | Yes   |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I created a dump following the steps [here](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps)
Dmp can be found here: https://1drv.ms/u/s!Ai6miMIM80LYu1bmKdzF7Pmbv7ZV?e=p0lwqv

The XAML of the MenuFlyout is [here](https://github.com/felixse/FluentTerminal/blob/b08fb11a78b9ec03d6dfcc20a03ce02ca026f423/FluentTerminal.App/Views/MainPage.xaml#L48)

**Comment by JohnnyWestlake** [comment]
PlacementMode `BottomEdgeAlignedLeft` does not exist before 1809, as noted at https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Primitives.FlyoutPlacementMode

So you should use a different placement mode or at least use conditional XAML to provide a fallback.

**Comment by felixse** [comment]
Thanks @JohnnyWestlake, it's working now. Damn it, I was only looking at properties of MenuFlyoutItemBase and its children 😄
