### ISSUE TITLE
WinUI breaks ListViewItemReveal brush resources

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2118]
**Describe the bug**
When using WinUI and the several **ListViewItemReveal*** brush resources in generic.xaml (such as `ListViewItemRevealBackgroundPointerOver`)  for styling, the reveal effect of these brushes is lost. A minimal repro is attached below demonstrating this issue. Observe that once you comment out `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />` in <Application.Resources> the reveal effect works as expected.

A workaround for now is to just redefine the brush resources based on [RevealBrush_rs2_themeresources.xaml](https://github.com/microsoft/microsoft-ui-xaml/blob/fd3e7fce4467b212df48dd04dee0f49dd4145f3a/dev/Materials/Reveal/RevealBrush_rs2_themeresources.xaml) in your own XAML.

**Expected behavior**
Reveal effect should be seen even when using WinUI.

**Screenshots**
![image](https://user-images.githubusercontent.com/1398851/76806260-2daf7f00-67e1-11ea-8403-4930e09228d6.png)

For comparison, this is how it should look like:
![image](https://user-images.githubusercontent.com/1398851/76806302-491a8a00-67e1-11ea-9ec2-fd8425cbf011.png)

NuGet package version: 
Microsoft.UI.Xaml 2.3.200213001 and newest 2.4 pre-release.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Attached Files**
[WinUIListViewRevealIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4340717/WinUIListViewRevealIssue.zip)

**Comment by ranjeshj** [comment]
@kikisaints @codendone Any ideas what might be happening here ?

**Comment by mdtauk** [comment]
> @kikisaints @codendone Any ideas what might be happening here ?

I think this was mentioned before, as the same thing happened in the Start Menu shell.  There was no backing plate along with the reveal effect.
