### ISSUE TITLE
Question: Why is TitleBar customisation not coming to Win32 WinUI 3 Windows?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#2124]
Regarding the API Spec being proposed here [Window_and_Application_API_Spec.md](https://github.com/thomasclaudiushuber/microsoft-ui-xaml-specs/blob/patch-1/active/Win32/Window_and_Application_API_Spec.md).
Could you provide some information as to why the ability to customise or replace the TitleBar and Window Controls is not being ported/enabled for Win32 created Windows?  I understand this is part of the CoreWindow which is reserved for UWP applications, but Win32 should typically be a superset of UWP features, but with more customisation.

I realise there is a way to access the Hwnd underlying for the window, but it could be beneficial to wrap up some of this ability in a simple to use API, accessible from XAML and code - which does not require such deep access to window drawing - in a way that enables the same scenarios that CoreWindow enables.

https://github.com/thomasclaudiushuber/microsoft-ui-xaml-specs/blob/patch-1/active/Win32/Window_and_Application_API_Spec.md#windowsettitlebaruielement-method

### Visual examples:
![image](https://user-images.githubusercontent.com/7389110/76898349-71f85900-688d-11ea-8565-e0c8e91afe40.png)
![image](https://user-images.githubusercontent.com/7389110/76898435-9e13da00-688d-11ea-9be8-8576f562d584.png)
![image](https://user-images.githubusercontent.com/7389110/76898505-be439900-688d-11ea-818a-e9743c1dd666.png)

_with NavigationView Extended into TitleBar area_

----

![image](https://user-images.githubusercontent.com/7389110/76898850-62c5db00-688e-11ea-9709-77824eaf35b5.png)

![image](https://user-images.githubusercontent.com/7389110/76898888-740ee780-688e-11ea-80ab-3ed09228bf52.png)

_customised but not Extended into TitleBar area_

----

![image](https://user-images.githubusercontent.com/7389110/76898543-d1eeff80-688d-11ea-9af1-42af1d4968ce.png)

![image](https://user-images.githubusercontent.com/7389110/76898627-fcd95380-688d-11ea-856b-5e2b1345daf6.png)

_without extending into TitleBar_

**Comment by Felix-Dev** [comment]
> There are other proposed APIs proposed that will be part of the future phases.

Titlebar customization might be part of the future APIs. If I recall correctly, the team stated that it is having in mind the UWP-style titlebar customization APIs for future WinUI support: https://github.com/microsoft/microsoft-ui-xaml/issues/1323#issuecomment-542785441

That might or might not mean support for WinUI desktop.

**Comment by mdtauk** [comment]
Then the questions are:
Will the TitleBar API come in the future?
Will it be there for WinUI 3.0 release?
If its not coming, why was that decision made?
Will there be code guidence to achieve the same effect of colourising the window controls, extending Acrylic into the titlebar area, and using custom Xaml elements as the grabbable title area - using HWND access.

**Comment by ranjeshj** [comment]
@marb2000 @YuliKl as FYI

**Comment by shaheedmalik** [comment]
I wish they wouldn't bring the customizations over in order to keep the title bar consistent. It isn't consistent even in UWP apps.

**Comment by mdtauk** [comment]
> I wish they wouldn't bring the customizations over in order to keep the title bar consistent. It isn't consistent even in UWP apps.

By default, the app window gives you the typical TitleBar you would see with Win32 mostly.  But many apps use the NavigationView, and that does not look good when it does not extend into the TitleBar.

UWP makes it easy to achieve this, but WInUI Desktop (as of the current spec) will not have a way to achieve this.

![image](https://user-images.githubusercontent.com/7389110/76898349-71f85900-688d-11ea-8565-e0c8e91afe40.png)
![image](https://user-images.githubusercontent.com/7389110/76898435-9e13da00-688d-11ea-9be8-8576f562d584.png)
![image](https://user-images.githubusercontent.com/7389110/76898505-be439900-688d-11ea-818a-e9743c1dd666.png)

_with NavigationView Extended into TitleBar area_

----

![image](https://user-images.githubusercontent.com/7389110/76898850-62c5db00-688e-11ea-9709-77824eaf35b5.png)

![image](https://user-images.githubusercontent.com/7389110/76898888-740ee780-688e-11ea-80ab-3ed09228bf52.png)

_customised but not Extended into TitleBar area_

----

![image](https://user-images.githubusercontent.com/7389110/76898543-d1eeff80-688d-11ea-9af1-42af1d4968ce.png)

![image](https://user-images.githubusercontent.com/7389110/76898627-fcd95380-688d-11ea-856b-5e2b1345daf6.png)

_without extending into TitleBar_

**Comment by shaheedmalik** [comment]
With all of those apps, the title bar behavior isn't consistent when you put them in Tablet Mode.

**Comment by mdtauk** [comment]
> With all of those apps, the title bar behavior isn't consistent when you put them in Tablet Mode.

Tablet Mode "should" autohide the Window Controls/TitleBar - This is to have a full-screen experience.  I would expect the same behaviour for all WinUI apps, UWP or Win32.

**Comment by shaheedmalik** [comment]
It *should* but isn't consistent. See Microsoft Store, People app, Photos, and Feedback Hub.

In regards to Win32, I figure that has a lot to do with Sets returning. Programs such as Word were great offenders, obstacles in the way of that initiative.

**Comment by mdtauk** [comment]
> It _should_ but isn't consistent. See Microsoft Store, People app, Photos, and Feedback Hub.
> 
> In regards to Win32, I figure that has a lot to do with Sets returning. Programs such as Word were great offenders, obstacles in the way of that initiative.

Different apps will have different needs.  You will never get 100% rigid consistency with TitleBars, but there will be a disparity between UWP app capabilities and WinUI Desktop apps - unless there is sample code for achieving the same effects with HWND interfaces - or these capabilities are introduced.

WPF Windows have options for transparency and titlebar displays - so you should expect WinUI Desktop apps to be capable of matching both UWP behaviours, WPF behaviours, as well as traditional Win32 window behaviours.

**Comment by mveril** [comment]
I write an issue for that in #microsoft/ProjectReunion/49 Project Reunion may be the good place for this issue I think

**Comment by MikeHillberg** [comment]
The technical difficulty with this in WinUI3 is enabling a custom title bar that the user can still drag and double-click on. This is enabled in WinUI2 with [Window.SetTitleBar](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Window.SetTitleBar), which registers with the shell the system (WinUI2) Visual behind the specified element. But with WinUI3 we need a new mechanism because we don't currently have a system Visual there.

**Comment by mdtauk** [comment]
Could WinUI / Reunion include a TitleBar xaml control, with built in behaviours and the ability to re-colour and theme/re-template?

**Comment by jarno9981** [comment]
@MikeHillberg  when will titlebar costimizing come to winui3 is very help full feature

**Comment by Wufus** [comment]
#4835

**Comment by Wufus** [comment]
We have a problem with using xBind converters in MainWindow.xaml - they are not working. #4966 pushes to use UI in another file. This make united title and UI impossible.

**Comment by knightmeister** [comment]
I'm curious what the state of this issue is. Today, in Win UI 3 it's possible to set a custom titlebar and extend the view into the titlebar area.

There are, however a lot of issues I've seen; I am unable to get any elements in the title bar to respond to click events in the same way they did with UWP, and if you set a background it paints over the min/max/close boxes.

From my (uninformed) perspective, the most obvious thing to do for the system when setting a custom titlebar would be to paint the system min/max/close boxes over the top of the element that is set as the titlebar. This would then allow things like a custom background to be set.

I really like the idea @mdtauk raised above about having a custom TitleBar xaml control. Another possibility would be to make a templated property (not sure if this is the right term) on the window.

**Comment by LeonBlade** [comment]
> I'm curious what the state of this issue is. Today, in Win UI 3 it's possible to set a custom titlebar and extend the view into the titlebar area.
> 
> There are, however a lot of issues I've seen; I am unable to get any elements in the title bar to respond to click events in the same way they did with UWP, and if you set a background it paints over the min/max/close boxes.
> 
> From my (uninformed) perspective, the most obvious thing to do for the system when setting a custom titlebar would be to paint the system min/max/close boxes over the top of the element that is set as the titlebar. This would then allow things like a custom background to be set.
> 
> I really like the idea @mdtauk raised above about having a custom TitleBar xaml control. Another possibility would be to make a templated property (not sure if this is the right term) on the window.

I'm experiencing a similar issue on my end while exploring WinUI 3 for the first time. I'm having to recreate the TitleBar entirely in order to achieve the same thing that you could use `CoreApplication` for on UWP for example. It also (seemingly) means I have to implement drag and drop again for titlebar if you extend it the entire width of the window?

Perhaps my ignorance here is causing my issues. There aren't many resources on WinUI 3 from developers at large so I can better understand certain practices. I'm not creating a UWP app, so this also causes issues.

**Comment by tuggernuts** [comment]
@knightmeister not sure if this helps at all, but this [doc](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0#remarks) explains how to properly set colors in custom title bar. Apologies if this isn't your issue.

Also in agreement that for custom title bars to have any purpose, we should be able to customize them. That means controls that can exist in that space, i.e. sliding NavigationView into that area, or the occasional button, searchbox, etc. I tend not to like to put anything in the bar, except the aforementioned NavView as @mdtauk points out.

**Comment by knightmeister** [comment]
Hi @tuggernuts, cheers yes I have seen that doc. Getting this all working is very nuanced and would be great if it could be slightly less so.

**Comment by Xyncgas** [comment]
I just simply wanting to color the title bar so it fits my app themes

**Comment by pratikone** [comment]
You can now customize the titlebar of a WinUI app by setting your own UI Element as a custom titlebar. The background of of the titlebar can be set by defining resource keys here https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.window.settitlebar?view=windows-app-sdk-1.1#colors. You can also set `WindowCaptionBackground` as Transparent and just set background of your uielement which is set as titlebar.

Hopefully this helps. I am closing this issue. Feel free to open it if it doesn't work.
