### ISSUE TITLE
generic.xaml not taking advantage of TintLuminosityOpacity in system Acrylic brushes

### ISSUE THREAD

**Issue by kikisaints** [microsoft/microsoft-ui-xaml#2125]
**Describe the bug**
Acrylic has a property on it called `TintLuminosityOpacity` which when set to a range between 90% and 95% is a perfect sweetspot for eliminating all visibility of Shadows that could be behind it - this is especially important for popups and other controls that have shadows by default.

However, today our WinUI generic.xaml is not setting that property and therefore not taking advantage of it.

**Expected behavior**
WinUI has this property set on all of our system Acrylic brushes.

**Comment by chingucoding** [comment]
So right behavior would be to set the TintLuminosityOpacity of every AcrylicBrush in WinUI to some value between 90% an 95%?

**Comment by ranjeshj** [comment]
@kikisaints If what @chingucoding is saying is accurate, should we just update the default value ?

**Comment by kikisaints** [comment]
@ranjeshj if by "update" you mean actually set them, then yes! 😅 

I'm currently still working with design to determine what those values actually should be.

**Comment by YuliKl** [comment]
I plan to replace this with a more concrete proposal for value changes shortly.

**Comment by YuliKl** [comment]
This topic is now covered by #3478
