### ISSUE TITLE
Roaming/Mandatory Profile Problems

### ISSUE THREAD

**Issue by ryanwb3** [microsoft/microsoft-ui-xaml#2127]
This thread describes it in detail:
http://www.edugeek.net/forums/windows-10/207082-windows-10-1903-uwp-apps-roaming-u-ev-profiles.html

Basically with mandatory profiles and roaming profiles, when delete cached copies of profiles is used , the UI.Xaml appx's have to be registered at every logon for apps like the calculator and photos to work. If the apps are not registered, this error is produced in Event Viewer\Windows Logs\Application:

Faulting application name: Microsoft.Photos.exe, version: 2020.19081.28230.0, time stamp: 0x5e3211c3
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.657, time stamp: 0xda02d3eb
Exception code: 0xc000027b
Fault offset: 0x0000000000712ec0
Faulting process id: 0x2324
Faulting application start time: 0x01d5fd3bc9204d2a
Faulting application path: C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2020.19081.28230.0_x64__8wekyb3d8bbwe\Microsoft.Photos.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 9f2d67d2-a387-405b-ab8a-c92fd0094183
Faulting package full name: Microsoft.Windows.Photos_2020.19081.28230.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

Faulting application name: Calculator.exe, version: 10.1910.0.0, time stamp: 0x5dc9c5e0
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.657, time stamp: 0xda02d3eb
Exception code: 0xc000027b
Fault offset: 0x0000000000712ec0
Faulting process id: 0x9d0
Faulting application start time: 0x01d5fd3bc4b080fd
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.1910.0.0_x64__8wekyb3d8bbwe\Calculator.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: d61557c2-ab9f-4192-a55c-1d26cb076c9c
Faulting package full name: Microsoft.WindowsCalculator_10.1910.0.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by StephenLPeters** [comment]
@Austin-Lamb @codendone Do either of you know what this issue is? Notably the fauling module is **windows**.ui.xaml

**Comment by ranjeshj** [comment]
@ryanbley3  can you please share a process dump ? You could share this by filing a feedback hub issue and sharing the link to the feedback hub issue here.

**Comment by ryanbley3** [comment]
> @ryanbley3 can you please share a process dump ? You could share this by filing a feedback hub issue and sharing the link to the feedback hub issue here.

Feedback hub will not load when this problem is occuring. Here is the error in the application log:
Faulting application name: PilotshubApp.exe, version: 1.1907.1911.11002, time stamp: 0x5dc9c390
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.657, time stamp: 0xda02d3eb
Exception code: 0xc000027b
Fault offset: 0x0000000000712ec0
Faulting process id: 0x2700
Faulting application start time: 0x01d6132cb6bff3b4
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsFeedbackHub_1.1907.3152.0_x64__8wekyb3d8bbwe\PilotshubApp.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 78bf0333-02bd-4555-a087-9f2b3a0b1ed9
Faulting package full name: Microsoft.WindowsFeedbackHub_1.1907.3152.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by ranjeshj** [comment]
@ryanbley3 The log information you shared does not provide details to debug the issue. Can you try collecting a dump manually and sharing it ? Details on how to collect a local dump can be found [here.](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps)

**Comment by ryanbley3** [comment]
[Here is a link](https://cincinnatilibrary-my.sharepoint.com/:u:/g/personal/ryan_bley_cincinnatilibrary_org/EctGmZum329GvHZsq80PKOwBIavXewMGxp9DXvSkYBKkPQ?e=9uHRya) to a dump.  Let me know what I can do or provide next.

Thanks!

**Comment by ryanbley3** [comment]
Any update @ranjeshj ?

**Comment by ranjeshj** [comment]
@MikeHillberg @ptorr-msft This seems to be an issue with the way the appx packages are registered in the system across profiles. Can you help route this bug ? Should this be moved to the project reunion repo ?

**Comment by ptorr-msft** [comment]
@jvintzel FYI.

**Comment by StephenLPeters** [comment]
@ptorr-msft and @jvintzel pinging this thread.

**Comment by ptorr-msft** [comment]
John is OOF. Let me see if anyone else can help.

**Comment by ptorr-msft** [comment]
We are trying to find out...

**Comment by ryanbley3** [comment]
Any update @ptorr-msft ?

**Comment by ryanbley3** [comment]
@ptorr-msft @jvintzel Any update?

**Comment by ptorr-msft** [comment]
Still trying to get info, sorry.

**Comment by ryanbley3** [comment]
@ptorr-msft I am unable to perform a trace with Feedback Hub as noted above. The feedback hub app is affected by this bug and will not run correctly. I have a link to a trace in this issue. I will attach that trace to a feedback hub issue.

**Comment by RDMacLachlan** [comment]
Hello @ryanwb3,

Please follow the steps below to capture the log information using AppxDiag tool. Once you've successfully captured the logs, please share them with us for review.

**Steps:**
    - Save appxdiag.zip from http://aka.ms/appxdiagzip and unzip to c:\logs
    - From an admin command prompt,
    - C:\logs\appxdiag\appxdiag>appxdiag.cmd
    - Hit ‘Y’ for tracing and wait for repro to happen (i.e. see Settings -> Apps and Features page).
    - Hit 'Enter' to stop tracing and share the zip produced.

If you have any questions or concerns, please let me know.
Thanks!

**Comment by JoshTech1** [comment]
Hello @RDMacLachlan! I'm also experiencing this issue on multiple Windows 10 1909 workstations where we use roaming user profiles with the group policy "Delete cached copies of roaming profiles". Our version of Windows.UI.Xaml.dll is a bit newer but the same exception code. Happens with calculator and photos where they crash when opened.

Faulting application name: Calculator.exe, version: 10.1905.28.0, time stamp: 0x5cf593c9
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.997, time stamp: 0xe85f9394
Exception code: 0xc000027b
Fault offset: 0x0000000000713500
Faulting process id: 0x36c0
Faulting application start time: 0x01d6b76ec173bbcd
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.1905.28.0_x64__8wekyb3d8bbwe\Calculator.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: ca1abe26-b84c-4651-a226-0a7f17c5bace
Faulting package full name: Microsoft.WindowsCalculator_10.1905.28.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

I collected a package with AppxDiag and I'll message you to see how to get it to you privately.

**Comment by RDMacLachlan** [comment]
Hello @JoshTech1,

Thank you for reaching out, I've received your email. Once we receive the appxdiag from you, we'll be able to investigate the issue further.

Thanks!

**Comment by bpulliam** [comment]
Closing a stale external issue. If you are still seeing this, please open a new issue with updated repro steps and logs/diagnostics.
