### ISSUE TITLE
Proposal: Add some public documentation/information on how language 'projection' works in WinRT

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#2131]
I know that WinRT components have interface definition files, which somehow enable the API for the component to be used by multiple languages e.g. C#, C++. However, I can find very little information on the finer details of how this works. I've heard rumours that the way this works might change with something called cswinrt, but it would still be useful to know the principles and some more details, in some centralised documentation or guidance. Ideally a developer would not need to know this, but it seems like there are quite a few reasons to know the details such as
- the performance implications of using WinRT types vs .Net types etc
- how it's possible that weird behavior like #2047 can occur
- what sort constraints to bear in mind when submitting proposals and feature requests etc

My knowledge of the lower-level workings of C# and programming in general is pretty limited, so forgive some of the naive questions I have, but here are a few of them.

1. A broad overview of how it works. My understanding is we have .idl files, which produce .winmd files, and from there I'm a little lost. For C#, does it generate very simple wrapper classes from winmd files, for example
   ```
   class MyClass{
   IntPtr ptrToUnmanagedObject;
   public void DoSomething{
   //somehow invoke DoSomething method on unmanagedObject
   }
   }
   ```
   What about for C++?

2. How are structs projected? Is it the same as classes? So would there be a backing object, involving marshalling, in which case presumably performance in .net is much worse than using a .net struct. How is something like #2047 possible? In addition, how is it possible that a type like WIndows.Foundation.Numberics.Vector2 can be mapped to System.Numerics.Vector2. Presumably, if a WinRT API returns a System.Numerics.Vector2, it's genuinely a System.Numerics.Vector2 and not some strange wrapper as in the case of #2047?

3. How do enums work? Are there performance implications with using enums defined via WinRT rather than in .net? Also, I've noticed that declaring a type involving a WinRT enum, even something like an empty list of enums, causes the corresponding winmd file to load even if the enum has not yet been initialized. Is that expected? If I want to increase performance and also ensure DLLs etc are lazy-loaded, is it better to write a separate .net version of the enum and then convert between the two when needed?

4. What are the implications for garbage collection, especially involving event handlers. I've read that XAML has a complicated system for exsuring garbage collection works correctly, but does this extend to custom WinRT components. For example, if I write a component in C++/WinRT that has an event, and I add some class member as a handler for the event in C#, do I need to remove the handler when I no longer need the class instance in order to avoid a memory leak?
6. Why is there the restriction on inheritance when writing WinRT components that are submitted to the store? Is there any guidance on the alternatives, e.g. if I don't care about being about to inherit from my class in the consuming project, then should I use multiple inheritance in C++/WinRT as a way of avoiding writing a wrapper around a class that uses standard C++ inheritance? Or is there a better way?

5. This might be drifting a bit away from the main topic, but when I return an array from a C++/WinRT component, how is it converted into a .net object? For example, I store a large byte array in a com_array and I have a 'Detach' public method that swaps it into a new com_array and returns that. I would like to know if that avoids any copying or not, i.e. can .net somehow start managing the memory directly or is it copied.

6. Do we need to worry about ABI compatibility in any way? I guess as developers we will be shipping any components we write with our apps so it doesn't matter, and this will also be the case for WinUI 3, but I assume that UWP in general has to worry about it. It would be useful to know what restrictions this places on API changes or additions that we might want to request.

There are probably more questions but I've forgotten them. Also, feel free to turn this issue into a question instead of a feature proposal.

**Comment by StephenLPeters** [comment]
@kennykerr @Scottj1s for FYI

**Comment by ranjeshj** [comment]
@benstevens48 The documentation on this topic is slim (links below). I have bubbled this up to the appropriate team/folks.

[The Windows Runtime (WinRT) type system](https://docs.microsoft.com/en-us/uwp/winrt-cref/winrt-type-system)
[Windows Metadata (WinMD) files](https://docs.microsoft.com/en-us/uwp/winrt-cref/winmd-files)
