### ISSUE TITLE
SystemAccentColor-based brushes merged into App.xaml via Source files do not update when FrameworkElement::RequestedTheme is toggled

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#2138]
**Describe the bug**
SolidColorBrushes using SystemAccentColor which are merged into App.xaml from separate files do not update when FrameworkElement::RequestedTheme is toggled as outlined [here].(https://github.com/microsoft/fluent-xaml-theme-editor/blob/master/README.md#using-colorpaletteresources-in-code-behind)

**Steps to reproduce the bug**

1. Set up App.xaml to include theme dictionaries from separate files:
```xaml
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Dark" Source="ms-appx:///Themes/Dark.xaml" />
                <ResourceDictionary x:Key="Light" Source="ms-appx:///Themes/Light.xaml" />
                <ResourceDictionary x:Key="HighContrast" Source="ms-appx:///Themes/HighContrast.xaml" />
            </ResourceDictionary.ThemeDictionaries>
<...>
```
2. In those files, declare a brush based on SystemAccentColor:
> Light/Dark:
> ``` xaml
> <SolidColorBrush x:Key="MyBrush" Color="{ThemeResource SystemAccentColor}" />
> ```
> HighContrast:
> ``` xaml
> <SolidColorBrush x:Key="MyBrush" Color="{ThemeResource SystemColorHighlightColor}" />
> ```
3. Override SystemAccentColor in code, and toggle the app's top UI element's RequestedTheme to another theme and back.

**Expected behavior**
Brushes should update to reflect the new accent color. They do update for the opposite theme of the original, but in the original theme they will retain the starting color.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19589)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@chrisglein Can you take a look at this one ?
