### ISSUE TITLE
UWP App crashes throwing TypeLoadException when using a custom build configuration

### ISSUE THREAD

**Issue by Kumara-Krishnan** [microsoft/microsoft-ui-xaml#2141]
**Description:**
When a custom build configuration is used, TypeLoadException is thrown and crashes the app during OnLaunched.

It works fine for default configs Debug and Release.

**Steps to reproduce:**
1. Clone the sample repo from https://github.com/Kumara-Krishnan/CustomBuildConf
2. Rebuild the app and switch to 'PreProduction' build configuration. Build will succeed and once app starts, TypeLoadException will be thrown in OnLaunched.
3. Now change the config to Debug/Release, app will start successfully without any exception.

**Expected behavior**
App should start properly without throwing any exception when custom build configuration is used.

**Version Info**
Microsoft.UI.Xaml  Nuget Version: 2.1.190606001
Microsoft.NETCore.UniversalWindowsPlatform Nuget Version: 6.2.9
OS Version: 1903
OS Build: 18362.720
App Target Build Version: 17763
App Target Min Version: 17134

**NuGet package version:**
Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | |
| November 2019 Update (18363)  |  |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by Kumara-Krishnan** [comment]
Even-though this issue doesn't occur with the latest version of Microsoft.UI.Xaml package, I am not able to use it since it requires 18362 SDK. [When I use 18362 SDK my app doesn't build](https://developercommunity.visualstudio.com/content/problem/544057/uwp-visual-studio-2019-targetting-1903-18362.html). Is it possible to provide a fix that's backward compatible and doesn't require 18362 SDK version?

**Comment by JeanRoca** [comment]
Assigning back to team-Controls since this is WinUI 2

**Comment by ranjeshj** [comment]
From the link you shared, it looks like it was fixed in VS and not a WinUI issue.
