### ISSUE TITLE
Tab strip scroll bumpers don't disable when scrolling to the edge

### ISSUE THREAD

**Issue by AmineI** [microsoft/microsoft-ui-xaml#2143]
Tab strip scroll bumpers don't disable when scrolling to the edge

**Steps to reproduce the bug**

1. Add enough tabs to make the tab strip scrollable, so that the scroll arrows appear.
2. Scroll as much as possible in one direction (left or right)

**Expected behavior**

The corresponding arrow should be disabled and grayed out to indicate the state of being at the complete left/right. Example with Microsoft Edge (Legacy) tab strip :

![image](https://user-images.githubusercontent.com/15179425/77209163-cefa4600-6afd-11ea-8836-94293d7018aa.png)
Screenshot above on MS Edge, after doing the repro steps, with the _mouse cursor on the arrow button_ 
As you can see, MS Edge reacts to the edges of the tab strip. (..Mandatory pun)

**Actual behavior**

Notice that even though you can't scroll anymore, the scroll arrow doesn't reflect this state. (Not grayed out, and reacts to clicks, even though nothing happens

![image](https://user-images.githubusercontent.com/15179425/77208907-31067b80-6afd-11ea-9dcc-5da47f6ad034.png)

Screenshot above on Windows Terminal, after doing the repro steps, with the _mouse cursor on the arrow button_

**Version Info**
WinUI 2.4 & WinUI 3alpha, both through their respective branches of [Xaml-Controls-Gallery](https://github.com/microsoft/Xaml-Controls-Gallery/) 
So that's
NuGet package version:
Microsoft.UI.Xaml 3.0.0-alpha.200210.0 
Microsoft.UI.Xaml 2.4.0-prerelease.200203002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19577)              |  Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes/No   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Initially noticed on Windows Terminal and filled it there https://github.com/microsoft/terminal/issues/5053

**Comment by chingucoding** [comment]
This is definitely an issue. Not only is this confusing UI wise, but this might also be an issue accessibility wise as we have buttons in the UIA tree, that don't serve a purpose in that scenario.

**Comment by chingucoding** [comment]
If it's fine and nobody else is working on this, I would like to tackle this issue, @ranjeshj

**Comment by JasonStein** [comment]
I created a PR here to fix the problem: https://github.com/microsoft/microsoft-ui-xaml/pull/2162
