### ISSUE TITLE
WinUI 3.0 - UserControl Is No Longer Possible

### ISSUE THREAD

**Issue by goh-chunlin** [microsoft/microsoft-ui-xaml#2146]
**Describe the bug**
When we tried to add a new UserControl to a WinUI 3.0 UWP project, the code-behind of the UserControl will show the following error stating that it does not contain a definition for 'InitializeComponent'.

![image](https://user-images.githubusercontent.com/8535306/77250736-d6982700-6c84-11ea-8dc6-759b3007d9af.png)

**Steps to reproduce the bug**

1. Create a new WinUI 3.0 UWP Black App project;
![image](https://user-images.githubusercontent.com/8535306/77250656-6db0af00-6c84-11ea-9599-970e64c2a26f.png)
2. Create a new UserControl with "User Control (WinUI)", as shown in the screenshot below;
![image](https://user-images.githubusercontent.com/8535306/77250708-abadd300-6c84-11ea-8f05-13bd1f1759ff.png)
3. The error will be shown stating that it does not contain a definition for 'InitializeComponent'.

**Expected behavior**
There should not be any error.

**Version Info**

NuGet package version: 
NuGet: Microsoft.WinUI 3.0.0-alpha.200210.0
![image](https://user-images.githubusercontent.com/8535306/77250757-ff202100-6c84-11ea-8a1e-91e541f69c97.png)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Comment by ranjeshj** [comment]
@goh-chunlin Is this an intellisense error or a build error ? If you do a clean build, does it go away ?

**Comment by goh-chunlin** [comment]
Thanks, @ranjeshj .

The problem goes away after I did a build. So it seems like Visual Studio didn't rebuild after we add a new User Control.

**Comment by ranjeshj** [comment]
@danzil This looks like an issue with intellisense showing the error before first build.

**Comment by danzil** [comment]
Design time builds don't work in the Alpha version of WinUI. They will start working soon and we already have a work-item to enable that functionality back (so no need to keep this one open). Thanks for reporting the issue, though! We appreciate all reports even if they're known issues.

**Comment by sigmarsson** [comment]
Yeah, Clean is essntial otherwise `InitializeComponent()` not found.
