### ISSUE TITLE
WinUI 3.0 Alpha: app certification kit fails

### ISSUE THREAD

**Issue by lostmsu** [microsoft/microsoft-ui-xaml#2149]
**Describe the bug**
App certification kit fails to validate an app, that uses `WebView2`.

Logs attached: [AppCertKitValidationResult.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4370395/AppCertKitValidationResult.zip)

**Steps to reproduce the bug**

1. Create blank WinUI app
2. Add `WebView2` to `MainPage`, set `UriSource` to "https://bing.com"
3. Right click on the project -> Publish -> Create App Packages...
4. Enable `x86` and `x64` targets
5. In the dialog, ensure you enabled "Generate artifacts to validate the app with the Windows App Certification Kit"
6. Wait for build to complete and launch certification

**Expected behavior**
Certification should pass.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 3.0.0-alpha.200210.0
Microsoft.Web.WebView2 0.8.355

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@lostmsu This is an alpha release to get early feedback and currently we do not support publishing production apps with the store as mentioned in the [release notes.](https://docs.microsoft.com/en-us/uwp/toolkits/winui3/)
