### ISSUE TITLE
TwoPaneView should not be included in tab navigation

### ISSUE THREAD

**Issue by rudyhuyn** [microsoft/microsoft-ui-xaml#2150]
**Describe the bug**
The TwoPaneView control is currently added automatically to tab-navigation although it shouldn't be for many reasons:
- No user interaction possible
- Its behavior should be similar to all other layout controls (Grid, StackPanel, RelativePanel)

**Steps to reproduce the bug**
- Create a new app
- Add a TwoPaneView control
- Add a Button
- Press many times <kbd>tab</kbd>
--> The focus will switch between the button and the TwoPaneView control

**Expected behavior**
- The focus should stay on the Button

**Version Info**

NuGet package version: 
2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |
| 10X                         | Yes |

**Additional context**
I would like to fix it.

**Comment by ranjeshj** [comment]
@rudyhuyn Thanks for filing. @teaP Is there any reason why we might want TwoPaneView to be a tab stop ?

**Comment by teaP** [comment]
> @rudyhuyn Rudy Huyn FTE Thanks for filing. @teaP Tammy Paine FTE Is there any reason why we might want TwoPaneView to be a tab stop ? If there is none, @rudyhuyn Rudy Huyn FTE go ahead with the fix - Thanks!

No, it definitely shouldn't be!

**Comment by shaheedmalik** [comment]
Rudy is fast.
