### ISSUE TITLE
WinUI 3.0 Alpha: ListView Issue

### ISSUE THREAD

**Issue by goh-chunlin** [microsoft/microsoft-ui-xaml#2154]
**Describe the bug**
In the following code, there is an exception saying "(Error CS1503) cannot convert from 'Microsoft.UI.Xaml.Controls.ListView' to 'Windows.UI.Xaml.UIElement'".

```
var _compositor = Window.Current.Compositor;
VisualExtensions.GetVisual(ImageList).Clip = _compositor.CreateInsetClip();
```
However, in fact, the ImageList is actually Windows.UI.Xaml.Controls.ListView, which should be inherting from Windows.UI.Xaml.UIElement.
![image](https://user-images.githubusercontent.com/8535306/77389643-ac528080-6dce-11ea-9390-9799a09b4568.png)

So it is a bit confusing because XAML and code behind tell different story.

**Expected behavior**
The namespace of ListView in both XAML and code behind should be the same.

**Version Info**

NuGet package version: 
NuGet: Microsoft.WinUI 3.0.0-alpha.200210.0
![image](https://user-images.githubusercontent.com/8535306/77250757-ff202100-6c84-11ea-8a1e-91e541f69c97.png)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@goh-chunlin Is this a build error or just what the editor is saying on hovering over ? In WinUI3 we are switching the namespaces from Windows to Microsoft, so both the Markup and Code should say Microsoft. This might be an issue with the Visual studio Xaml designer showing the incorrect type.

**Comment by goh-chunlin** [comment]
Hi @ranjeshj ,

I have cleaned and rebuilt the solution but the problem is still there. 

The editor only shows correct namespace if I indicate the prefix, as shown in the code below.

```
<Page
    x:Class="Demo01.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Demo01"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <winui:ListView x:Name="ImageList"></winui:ListView>
    </Grid>
</Page>

```

**Comment by ranjeshj** [comment]
@goh-chunlin You cannot mix Windows.UI.Xaml and Microsoft.UI.Xaml types in WinUI3. So using WUX.ListView will not work. The compositor might still be the system compositor which is expecting Windows types. @codendone Is there a way to make this work ?

**Comment by codendone** [comment]
VisualExtensions.GetVisual() comes from the Windows Community Toolkit, which does not yet have a WinUI 3 compatible version.  The current version expects a Windows.UI.Xaml element, which is why you're getting that error.  A WinUI 3 version is currently in progress: see windows-toolkit/WindowsCommunityToolkit#3106.

Until then, you can replace this VisualExtensions.GetVisual(ImageList) call with its implementation: ElementCompositionPreview.GetElementVisual(ImageList).

**Comment by goh-chunlin** [comment]
Thanks for the help, @codendone 

I think my doubts are well answered and I will wait for the updates. For now, I will proceed to close this Issue, @ranjeshj
