### ISSUE TITLE
TextDecoration on TextBlock can't be removed

### ISSUE THREAD

**Issue by Dexxes** [microsoft/microsoft-ui-xaml#2156]
I think  TextDecorations.None ist not working on a TextBlock, because I can't remove it by setting `txtBlock.TextDecorations = TextDecorations.None;`
It makes no difference whether the text was underlined or striked-through, no change will occur.

**Steps to reproduce the bug**
1. Create TextBlock named _txt_ and a CheckBox named _cb_ with the checked/unchecked handlers
2.
```
private void cb_Checked(object sender, RoutedEventArgs e)
        {
            txt.TextDecorations = Windows.UI.Text.TextDecorations.Underline;
        }

        private void cb_Unchecked(object sender, RoutedEventArgs e)
        {
            txt.TextDecorations = Windows.UI.Text.TextDecorations.None;
        }
```

**Expected behavior**
Well, the strike-though or underline should vanish

**Screenshots**

**Version Info**

Destination version Build 18362

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | YES |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | YES  |

**Additional context**

**Comment by Felix-Dev** [comment]
Should be the same as https://github.com/microsoft/microsoft-ui-xaml/issues/1093. There's also a workaround mentioned there.
