### ISSUE TITLE
WinUI 3.* Item templates (Project -> Add New -> *) are broken in VS 16.5.*

### ISSUE THREAD

**Issue by danzil** [microsoft/microsoft-ui-xaml#2157]
Visual Studio 2019 16.5 item templates (e.g., the View Model), but not project templates (e.g., Runtime Component) are currently broken because of a regression from Visual Studio. Visual Studio support ticket is here for tracking:
https://developercommunity.visualstudio.com/content/problem/959456/item-template-dependent-nesting-behavior-broken-in.html

**Steps to reproduce the bug**
Right Click a project file and select Add New -> [any WinUI item template that has nested page metadata like BlankPage or UserControl]

This affects all versions of WinUI 3.*.

Thanks @Scottj1s for debugging and reporting this issue to Visual Studio!

**Comment by JeanRoca** [comment]
Closing due to unsupported version of VS.
