### ISSUE TITLE
TreeViewItem's don't show up in Live Visual Tree 

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/microsoft-ui-xaml#2164]
Big thanks to @Felix-Dev for finding this bug and providing the screenshots/gif! 🎉

**Describe the bug**

`TreeViewItem` elements don't show up under `TreeView` in the Live Visual Tree

**Steps to reproduce the bug**

1. Open the `MuxControlsInnerLoop` solution and select the `MuxControlsTestApp` as the startup project and F5 in Visual Stduio
2. Go to the `TreeView` page
3. Enable "Select Elements in the Running Application"
4. Try to select the `TreeViewItem` on the page

**Expected behavior**

When you enable the "Select Elements in Running Application" mode in the Live Visual Tree, you should be able to select the `TreeViewItem` elements. As it turns out, this doesn't always happen, and you are only able to select the `TreeView`. 

The gif below shows the correct and incorrect behavior. The `TreeView` on the right side of the screen has the expected behavior, and the one on the left is broken. With the `TreeView` on the right, you can see when the mouse hovers over the `TreeViewItem` that they are able to be selected.

![issue](https://cdn.discordapp.com/attachments/684797559004201031/692180712828436540/vs_issue.gif)

**Screenshots**
You can see from the screenshot below, that there aren't any `TreeViewItem` elements as children in the LVT. This is what makes them not able to be selected.
![nothing in lvt](https://cdn.discordapp.com/attachments/684797559004201031/692165792568967198/unknown.png)

**Version Info**

Visual Studio Version: 16.4.6

NuGet package version: using latest master build

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |   Yes   |
| Mobile                   |     |
| Xbox                      |     |
| Surface Hub          |      |
| IoT                         |      |

**Comment by stevenbrix** [comment]
@fabiant3-zz and @danzil for FYI. I don't expect us to have time to get to this in RTM

**Comment by michael-hawker** [comment]
@stevenbrix is this with or without the new 'show just my xaml' feature?

**Comment by Felix-Dev** [comment]
@michael-hawker Good call. Disabling *Just My XAML* now shows the created TreeViewItems as expected:

![vs_treeview_vtree](https://user-images.githubusercontent.com/1398851/79550020-11308c00-8098-11ea-9d86-c0b2e04227b8.gif)

@stevenbrix Seems like we can close this issue 🙂

**Comment by michael-hawker** [comment]
@Felix-Dev happy to help! 🦙

> **Enable Just My XAML**: Starting in Visual Studio 2019 version 16.4, the Live Visual Tree by default shows only XAML that is classified as user code. If you disable this option, all generated XAML code is shown in the tool.

[This is a new feature](https://docs.microsoft.com/en-us/visualstudio/debugger/general-debugging-options-dialog-box?view=vs-2019) which I was enabled by default not long ago in VS. So, if you normally populate your items control via a collection, you won't see the containers by default vs. if you were writing a sample and putting all the items by hand in your XAML.

**Comment by stevenbrix** [comment]
I keep forgetting about this feature ☺️

@Felix-Dev if you have a custom `ItemTemplate` for the case where you're binding to a collection, do the items show up then?

**Comment by Felix-Dev** [comment]
@stevenbrix Works as well.

**Comment by stevenbrix** [comment]
Awesome, closing this issue then!
