### ISSUE TITLE
Question: [How are app sound notifications handled on WinUI 3?]

### ISSUE THREAD

**Issue by shaheedmalik** [microsoft/microsoft-ui-xaml#2165]
As a current Windows Mobile 10 user, I have experienced the ability to customize the app's notifications in Settings. Over the years, I have noticed that same feature hasn't translated over to Windows 10. I figured that this would be hard implement with Win32 programs. They weren't designed to change an program's notification sound other than the antiquated "Sounds" menu. I have also noticed the inability to change UWP notifications in Windows 10 as well.

My question is, is this ability built into Windows 10 UWP apps like they were in Windows 10 Mobile apps? Will this ability be added to WinUI 3 which will allow for app developer to use an api to set their notification sounds and allow for the OS to change those sounds to a custom one if perfered?

Thanks.

**Comment by StephenLPeters** [comment]
@Austin-Lamb or @codendone do either of you know where we could route this?

**Comment by Felix-Dev** [comment]
@shaheedmalik As far I'm aware, on desktop you can only change the notification sound in the app itself and not via the OS. In other words, currently, if you want to change the notification sound, you can only do that on a per-app basis and only if the developer supports this feature and it further depends on how they implemented it (providing a set of sounds packaged via the app to pick from/enable the user to pick a sound file on their file system).

See https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/custom-audio-on-toasts for API details.
