### ISSUE TITLE
Visual Studio keeps modifiying and removing items from MUXControls.sln

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2168]
When opening the MUXControls.sln file with Visual Studio, VS removes some entries (similiar to #821).
This behavior only occurred recently and was not present few days/weeks ago, so this seems to be a regression.

**Comment by StephenLPeters** [comment]
@llongley maybe you can weigh in here? looks like you handled the previous similar issue.

**Comment by llongley** [comment]
What entries are being removed?

**Comment by chingucoding** [comment]
The following ones are being removed:
![image](https://user-images.githubusercontent.com/16122379/77695181-a1a11280-6fab-11ea-82ca-44495a09a37b.png)

**Comment by llongley** [comment]
Hmm, I'm seeing that too.  I *think* that that might be OK just to check in, actually.  To take one example, the ColorPicker entry that was removed:

```
dev\ColorPicker\InteractionTests\ColorPicker_InteractionTests.projitems*{4d8c5d1b-f982-44a1-b744-dd0e51651bf2}*SharedItemsImports = 4
```

...has another entry further down with a larger number:

```
dev\ColorPicker\InteractionTests\ColorPicker_InteractionTests.projitems*{a4d2fae8-e7fc-4100-91ff-2202fac91c70}*SharedItemsImports = 13
```

It could be that there was an old disused entry left in the .sln file that a more recent version of Visual Studio is cleaning up, or something like that.  Perhaps the best thing to do would be to send that out for a pull request, we can see if anything breaks either in build or test with those changes incorporated, and if not, we can just check that in.

**Comment by chingucoding** [comment]
I agree, this is probably the easiest way to fix this issue. I've created #2176 so we can run the CI pipeline, and maybe merge this into master.
