### ISSUE TITLE
Question: Using WinUI 3.0 without UWP app model

### ISSUE THREAD

**Issue by Elekhyr** [microsoft/microsoft-ui-xaml#2179]
Hi, 
From https://docs.microsoft.com/en-us/uwp/toolkits/winui3/ we know that there is no project template for application not using UWP app model. But is it possible to do it by hand ? From a Windows Console Application (C++/WinRT) project or, even better, from a plain Win32 application. 
Our team is really keen on the idea of using WinUI without XamlIslands.

Thanks for your answer and your work.

**Comment by Felix-Dev** [comment]
The bits required to make WinUI 3 work in Win32 apps are not yet included in the WinUI 3 Alpha currently. The team currently aims to release a new WinUI 3 preview around Build this year including initial support for Win32 apps:
![image](https://user-images.githubusercontent.com/1398851/77750229-b8834b80-7023-11ea-93c8-c37afb046fc0.png)
(Image taken from the [WinUI Community Call (March 18, 2020)](https://github.com/microsoft/microsoft-ui-xaml/issues/2104)

**Comment by Elekhyr** [comment]
Thanks for your answer

**Comment by IngwiePhoenix** [comment]
What's the current status of this?

I am looking at the current situation of GUI toolkits across platforms (cocoa, win32, gtk - wxWidgets, Qt, FLTK, lvgl, ...) and noticed that there are quite a few ways to make GUIs on Windows. The most modern looking seems to be WinUI. But the XAML part is - albeit readable - also a little confusing. So I was looking to see if WinUI could be used from C/C++ without XAML.

**Comment by sotanakamura** [comment]
I shared Step-by-step Guide: WinUI 3 in C++ Without XAML #8151
