### ISSUE TITLE
ProcessHelixFiles job is unreliable (PR pipeline)

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2187]
The ProcessHelixFiles job is unreliable and fails on multiple PR's despite them not touching the controls in question.

The following PR's pipelines have failed:
#2176
#2155
#2162

with error: "Cannot bind argument to parameter 'Path' because it is null"

For some reason. AppBarButton's and CommandBarFlyout's visual tree files keep being generated every time.

**Comment by ranjeshj** [comment]
@llongley Were you able to investigate this issue? It is starting to block PRs.
