### ISSUE TITLE
update RadialGradientBrush property values to be ratios instead of percentages

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#2193]
Update property values to match the spec. See comment [here.](https://github.com/microsoft/microsoft-ui-xaml/pull/2181#issuecomment-606227100).

**Comment by michael-hawker** [comment]
> What does it mean for Radius to be 0 to 1 ?

@ranjeshj it's all about proportions of the original size of the parent surface. We spent a lot of time in the Toolkit making sure we interoped 99% with the WPF brush in terms of the main properties (we just couldn't support absolute mapping mode), so we tried to make our [documentation robust](https://docs.microsoft.com/en-us/windows/communitytoolkit/brushes/radialgradientbrush), you can see how we actually use the values to do the mapping in the brush itself here:

https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/adf771eadba828495a051adcac820a1c56385335/Microsoft.Toolkit.Uwp.UI.Media/Brushes/RadialGradientBrush.cs#L77-L93

**Comment by chingucoding** [comment]
@ranjeshj I would like to take this issue, if thats fine.

@michael-hawker Unfortunately, the RadialGradientBrush uses the CompositionRadialGradientBrush which behaves differently than the WPF RadialGradientBrush does, e.g. to get the GradientOrigin to be starting in the top left, we had to transform the input to get that to work. But it should be fixable :)

**Comment by michael-hawker** [comment]
@chingucoding we used the `CanvasRadialGradientBrush` from Win2D in the toolkit and had to do all the translation as well, so I imagine it's pretty similar types of mappings still? 

Anyway, feel free to ping me on the discord server if you want to chat about anything for this topic. I implemented the brush in the Toolkit and am passionate about WPF interop for the community. 😊

**Comment by chingucoding** [comment]
@michael-hawker Thank you for that offer! 🦙

However I am not sure if there is actually anything do right now. It seems that the spec is just not correctly aligned with the source code right now. Setting `EllipseRadius` to (0.5,1.0) stretches the RadialGradientBrush as expected (like in WPF with RadiusX and RadiusY). All points need to be specified with values in [0,1] for the Mappingmode "RelativeToBoundingBox" and in that mode they behave the same like the WPF properties do.

Or am I missing something here?

**Comment by chingucoding** [comment]
@MikeHillberg , @ranjeshj , @jesbis FYI

**Comment by MikeHillberg** [comment]
I updated the [spec](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/67):
* Renamed GradientOriginOffset to GradientOrigin
* Updated EllipseCenter and EllipseRadius to be [0,1] rather than [1,100].

Does that match?

**Comment by chingucoding** [comment]
Yes that should be matching the current implementation.

**Comment by ranjeshj** [comment]
> I updated the [spec](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/67):
> 
> * Renamed GradientOriginOffset to GradientOrigin
> * Updated EllipseCenter and EllipseRadius to be [0,1] rather than [1,100].
> 
> Does that match?

Yes. That is what i see as well. With the default mapping mode, this is accurate.
