### ISSUE TITLE
Is SwapChainPanel supported in xaml islands?

### ISSUE THREAD

**Issue by vibkumar** [microsoft/microsoft-ui-xaml#2199]
Hello,

I have two questions regarding xaml islands:
1. I have a xaml user control that consists of a grid containing a swapchainpanel. I host this xaml control in a win32 window with xaml islands. I notice that I'm unable to render anything to this swapchainpanel (even a simple test like painting some solid color to the swapchainpanel doesn't render). Is what I'm doing valid and are swapchainpanels supported? If so, is there any way I can debug this further?

2. Is it possible to retrieve a xaml user control from a win32 window?

**Comment by StephenLPeters** [comment]
@Austin-Lamb @codendone fyi

**Comment by lhak** [comment]
I can confirm that at least CanvasSwapChainPanel (from win2d) does work in xaml islands

**Comment by codendone** [comment]
SwapChainPanel should work, and it is great @lhak confirmed it works in at least that scenario.

For debugging, if you set a background color on the grid containing the SwapChainPanel, does that background draw correctly?  Have you confirmed that your swapchain is being created at the correct size?  If you setting a scale on the swapchain, is the scale value correct?

> Is it possible to retrieve a xaml user control from a win32 window?

Is your goal to be able to take an HWND value and get to a XAML element from that?  I don't believe there is any automatic way to do this.  You could theoretically store a lookup somewhere, including potentially using [SetProp](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setpropw) on the HWND to point to whatever object you're interested in (just be careful to clear this out when the target object gets destroyed, of course).

**Comment by codendone** [comment]
@vibkumar I think the questions have been answered, so I'm closing this. Please let me know if you have more here.
