### ISSUE TITLE
NavigationView: Pane light dismiss does not adjust item width

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2208]
**Describe the bug**
When light dimissing the NavigationView pane in left display mode, the NavigationViewItems widths are not adjusted to now match the new width of the closed pane. This causes UI issues especially for *NavigationViewItemSeparators* as they are not applying their *right* margin to the new width of the collapsed pane. Please the see the following gif for illustration:

![navviewpane_issue](https://user-images.githubusercontent.com/1398851/78189005-8f264d80-7471-11ea-88b0-2d8e7407a9a7.gif)

**Expected behavior**
NavigationViewItems should work with the correct pane width when the pane is light dismissed:
![image](https://user-images.githubusercontent.com/1398851/78189102-baa93800-7471-11ea-9b65-687f8d8c2732.png)

**Version Info**
NuGet package version: 
2.4.0-prerelease.200322001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I would like to fix this.

**Comment by shaheedmalik** [comment]
That is a bug.
