### ISSUE TITLE
[Accessibility] Tab navigation can get stuck on Pivot control header in some cases

### ISSUE THREAD

**Issue by totallymonkey** [microsoft/microsoft-ui-xaml#2209]
**Describe the bug**
If certain actions are taken while focus is on the Pivot control header, then tabbing past the header can get broken.  Action described in repro steps.

**Steps to reproduce the bug**

1. Navigate to Pivot header with keyboard by tabbing
2. While focus is on the header, invoke a shortcut that uses the Ctrl key to move focus somewhere else in the application.  For example, hook up Ctrl+Tab in a PreviewKeyDownHandler to move focus to a different element
3. Navigate back to the Pivot header with keyboard by tabbing
4. Try to tab past the header.  Header item selection will change instead of navigating into the Pivot content
5. Now, press Ctrl on the keyboard and then tab again.  Focus will now go into the Pivot content

**Expected behavior**
Focus being moved out of a Pivot control with a shortcut that uses the Ctrl key should not break further navigation in that Pivot

| Windows 10 version                  | Saw the problem? |
| 2004

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop

**Additional context**
I have debugged this with internal symbols, so please feel free to reach out to me for more information.

**Comment by ranjeshj** [comment]
@totallymonkey  If you can share a repro app and a video of what you are seeing, that would be helpful. Since Pivot is a controls in the framework, any fixes for this would have to wait for WinUI3.

**Comment by totallymonkey** [comment]
Here are the exact repro steps using Xbox Game Bar:
1. Open Game Bar with Win+G
2. Link an account to Xbox Live in the Settings if not already done
3. Open the Xbox Social widget from the menu if it's not open
4. Press Ctrl+Tab until the Social widget is highlighted
5. Tab until focus is on the Pivot control that has FRIENDS and CHAT as the options
6. Press Ctrl+Tab to move focus out of the widget
7. Ctrl+Tab again until the Social widget is highlighted
8. Tab through until focus is on the Pivot control and then tab once more

At this point you will notice that the tab that is selected changes to CHAT instead of focus moving on to the friends list and focus is essentially trapped.  If you press Ctrl at this point and then try to tab again the issue will be resolved and you can move focus normally once again.
