### ISSUE TITLE
Improve InnerLoop workflow

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2217]
Currently when using the InnerArea.props file, essentially one has to manually figure out the dependency chain. Few examples:
* ItemsRepeater tests have a dependency on the LayoutPanel, Scroller and ScrollBar
* If you want to use the NavigationView, you need the ItemsRepeater to be compiled too. 

By the time one has figured out all of that, it might have been faster to just use the full loop.

I would like to work on this. The ways we could solve this are:
- Different InnerLoop files for every control
  - Drawback: You would need to copy files all the time, which is to much work
- A script doing all the magic
  - A lot of work and logic to put into a single script, can become messy to write
- Conditional compile in FeatureAreas.props
  - Already done to detect InnerLoop area

Unless there seem to be better options, I would implement this using the last option as it provides the best clarity.

**Comment by ranjeshj** [comment]
Yes. The last option seems like the best to me.

**Comment by ranjeshj** [comment]
One thing that might not be common knowledge is that apart from 'True' and 'False' you can also use 'ProductOnly' to include a dependency but not its associated tests, which can break the set of dependencies you have to compile.

**Comment by chingucoding** [comment]
I would create a PR in the next few days, where I would update the props files to be include the needed dependencies for every control (which getting there is an tedious process as it involves compiling a lot). In that PR, I would also update the documentation regarding the inner loop.
