### ISSUE TITLE
Proposal: Make isChecked of ToggleSplitButton a bindable property

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#2218]
# Proposal: Make isChecked of ToggleSplitButton a bindable property

## Summary

It should be possible to bind the isChecked property to another property (e.g. for two-way binding)

## Rationale

* The functionality of the binding currently has to be implemented manually
* The ToggleButton class implements isChecked as a dependency property

## Scope

| Capability | Priority |
| :---------- | :------- |
| isChecked should support bindings | Must |

**Comment by ranjeshj** [comment]
@adambarlow do you own this one ?

**Comment by ranjeshj** [comment]
MUX_PROPERTY_NEEDS_DP_FIELD seems to be used incorrectly for this property. @jevansa to confirm. I think this needs to be straight up dependency property that is public.

**Comment by Felix-Dev** [comment]
@ranjeshj You typed "@jevansa". Will let you correct it 🙂

**Comment by chingucoding** [comment]
Very weird, why is this not a public DP? Would changing that to a public DP be considered a breaking change here or can/should we change this now?

**Comment by ranjeshj** [comment]
> Very weird, why is this not a public DP? Would changing that to a public DP be considered a breaking change here or can/should we change this now?

This would be adding API, so I think this should be fine. @MikeHillberg to correct me if I am wrong.

**Comment by Felix-Dev** [comment]
Wouldn't mind working on this though would refer to @chingucoding in case he's already working on it/just about to/wants to.

**Comment by chingucoding** [comment]
Sure, you can go for it @FelixDev . Probably an easy issue to fix: Update IDL and maybe add a test to check that binding is working.

**Comment by ranjeshj** [comment]
@FelixDev Please hold for the time being. I am trying to figure out if this was intentional or accidental.

**Comment by jevansaks** [comment]
x:Bind should work for this property too in the meantime, right?

**Comment by adambarlow** [comment]
@YuliKl took commanding some time ago, but I can help if you have a specific question from me.

**Comment by YuliKl** [comment]
> I am trying to figure out if this was intentional or accidental.

I would be surprised to learn that this had been a deliberate choice, feels like an accident that isChecked isn't already bindable.

**Comment by ranjeshj** [comment]
@FelixDev confirmed that this was accidental. Please feel free to go ahead with the change. Thanks!

**Comment by Felix-Dev** [comment]
@ranjeshj Alright 🙂

**Comment by Felix-Dev** [comment]
I did some testing locally and I noticed that binding in XAML (two-way binding,...) already works. As in 
```xml
<muxc:ToggleSplitButton x:Name="BindingToggleSplitButton" Content="IsChecked" IsChecked="{Binding IsChecked, Mode=TwoWay}"/>
```
where `IsChecked` is a public property of the DataContext. We still need to expose the DP in order to set it via
```cs
BindingToggleSplitButton.SetValue(ToggleSplitButton.IsCheckedProperty, true);
```
