### ISSUE TITLE
Documentation: positioning of resources for overwriting is wrong

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#2228]
**Describe the bug**
Overwriting the CornerRadius in app.xaml has for example no effect on the TeachingTip control.
See https://github.com/microsoft/microsoft-ui-xaml/issues/2228#issuecomment-609012999

```xaml
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary>
                <CornerRadius x:Key="OverlayCornerRadius">0</CornerRadius>
                <CornerRadius x:Key="ControlCornerRadius">0</CornerRadius>
            </ResourceDictionary>
            <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

**Version Info**

NuGet package version:  2.4.0-prerelease.200322001 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by Felix-Dev** [comment]
@jp-weber Overriding the *OverlayCornerRadius* theme resource works for me on the *page* level:
```xml
<Page
    x:Class="UwpTestApp.MainPage"
    <!-- ... -->
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls">
    <Page.Resources>
        <CornerRadius x:Key="OverlayCornerRadius">0</CornerRadius>
    </Page.Resources>

    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button Content="Show TeachingTip" Click="TeachingTipButton_Click" x:Name="TeachingTipButton"/>
        <muxc:TeachingTip x:Name="ToggleThemeTeachingTip1"                   
	                      Target="{x:Bind TeachingTipButton}"
	                      Title="TeachingTip"                                        
	                      Subtitle="TeachingTip content"/>
    </StackPanel>
</Page>
```
 
![image](https://user-images.githubusercontent.com/1398851/78424899-e6464100-7670-11ea-9812-9e65b3c1ae0a.png)

**Comment by jp-weber** [comment]
On page level it did not work for me strangely. I tried a little bit more and it is probably due to the problem of the order of the resources. The resources must be positioned under the import of muxc. So it works fine.

The documentation would be wrong.
https://docs.microsoft.com/de-de/windows/uwp/design/style/rounded-corner#rounded-corners-and-performance
```xaml
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
            <ResourceDictionary>
                <CornerRadius x:Key="OverlayCornerRadius">0</CornerRadius>
                <CornerRadius x:Key="ControlCornerRadius">0</CornerRadius>
            </ResourceDictionary>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
```

**Comment by kikisaints** [comment]
Thanks for catching this! I made a PR to fix it on our docs.
