### ISSUE TITLE
XAML fails to resolve an existing type declared as a string

### ISSUE THREAD

**Issue by paulovila** [microsoft/microsoft-ui-xaml#2230]
**XAML fails to resolve an existing type declared as a string**

**Steps to reproduce the bug**
1. Create a new _WinUI app project_, add the following classes:
```csharp
public class TypeResource 
{
    public Type TargetType { get; set; }
}
public class MyClass
{
}
```
2. In MainPage.xaml add ```TypeResource```  initialising the ```TargetType```  to ```MyClass``` type:
```xaml
<Page 
 xmlns:local="using:ChecksQA.WinUI"
   ...>
<Page.Resources>
    <local:TypeResource x:Key="SSVM"  TargetType="local:MyClass"/>
</Page.Resources>
```
3. Build & Run

**Expected behavior**
It should not generate an exception at runtime trying to find the type declared in the string.
Exception:
```
Windows.UI.Xaml.Markup.XamlParseException
  HResult=0x802B000A
  Message=The text associated with this error code could not be found.

Failed to create a 'System.Type' from the text 'local:MyClass'. [Line: 13 Position: 43]
  StackTrace:
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at ChecksQA.WinUI.MainPage.InitializeComponent() in C:\Repos\ChecksQAClient\src\ChecksQA.WinUI\obj\x64\Debug\MainPage.g.i.cs:line 33
```

This exception **does not** occur in 'UWP classic', or else, how is WinUI serialising types in XAML?

**Version Info**
NuGet package version: 
[Microsoft.NETCore.UniversalWindowsPlatform 6.2.10]
[Microsoft.WinUI 3.0.0-alpha.200210.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | Yes  |

**Comment by JeanRoca** [comment]
Hey @paulovila thanks for filing this issue. Would you be able to verify if this issue repros in a WinUI 3 Desktop app using the latest Preview 3?
