### ISSUE TITLE
Progress ring with value set to 0 does not show as expected

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2239]
**Describe the bug**
The progress ring does not show the visuals properly with the `Value=0`

**Steps to reproduce the bug**
Set Value=0

**Expected behavior**

The visual should not have any filled part

**Screenshots**

![image](https://user-images.githubusercontent.com/8557046/78555504-84443200-7850-11ea-9432-1254425ac015.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.0-prerelease.200322001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@MarissaMatt Is the blue dot intentional when value is 0 ?

**Comment by mdtauk** [comment]
I thought the control had special cases for handling 0% and 100%?

**Comment by ranjeshj** [comment]
@harvinders @mdtauk Unfortunately there are a few open issues with the determinate visuals. We decided to take out the determinate part for 2.4 release and add it back in the next release as a lottie animation unlike before where it was coded up as paths/storyboard. That should make the control simpler and more performant.

**Comment by mdtauk** [comment]
So determinate will also be an animation?

Will the After Effects source file be included in the Repo to aid developers who may choose to more fully customise it in the future?

**Comment by ranjeshj** [comment]
@mdtauk that is an excellent idea. @chigy can we do that ?

**Comment by MarissaMatt** [comment]
Hi @harvinders and @mdtauk , thanks for filing this issue! 

The determinate state is still a work in progress and is undergoing active design iteration. The current thinking aligns with your suggestion that 0% *won't* show the blue dot at the top but would be fully empty instead. Because this issue is under active investigation from the design side and not *technically* a bug, I will close this issue for now, but please rest assured your feedback is being actively worked on! 

ProgressRing and ProgressBar control have been recently assigned to my ownership and I am actively working on refreshing the proposal and spec for the determinate state. If you either of you have thoughts on the design, please feel free to add them to the proposal and spec [here](https://github.com/microsoft/microsoft-ui-xaml/issues/837) and [here](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/progress/ProgressRing.md).

Thanks again!

**Comment by chigy** [comment]
> So determinate will also be an animation?
> 
> Will the After Effects source file be included in the Repo to aid developers who may choose to more fully customise it in the future?

@mdtauk , I am looking into this. For my education, does it need to be After Effects file or can we share the JSON file for Lottie?

**Comment by mdtauk** [comment]
> > So determinate will also be an animation?
> > Will the After Effects source file be included in the Repo to aid developers who may choose to more fully customise it in the future?
> 
> @mdtauk , I am looking into this. For my education, does it need to be After Effects file or can we share the JSON file for Lottie?

Not sure if the JSON can be imported back into After Effects, I am not super experienced with Lottie.  I assumed it was a one way process out of After Effects and into JSON, before being converted to Code.

Having checked there is an initial attempt to import JSON files, but not sure how reliable it is.  Saving to After Effects native format would be the purest source for the asset, but I am not sure if the Design Team feel the design source is part of the open source nature, or if only the converted/compiled animation is what should be open.

Also not sure if making the thickness and colour values come from the Xaml resources was done manually, or as part of the AE/JSON source.

**Comment by chigy** [comment]
> > > So determinate will also be an animation?
> > > Will the After Effects source file be included in the Repo to aid developers who may choose to more fully customise it in the future?
> > 
> > 
> > @mdtauk , I am looking into this. For my education, does it need to be After Effects file or can we share the JSON file for Lottie?
> 
> Not sure if the JSON can be imported back into After Effects, I am not super experienced with Lottie. I assumed it was a one way process out of After Effects and into JSON, before being converted to Code.
> 
> Having checked there is an initial attempt to import JSON files, but not sure how reliable it is. Saving to After Effects native format would be the purest source for the asset, but I am not sure if the Design Team feel the design source is part of the open source nature, or if only the converted/compiled animation is what should be open.
> 
> Also not sure if making the thickness and colour values come from the Xaml resources was done manually, or as part of the AE/JSON source.

@mdtauk , thanks. As mentioned, we are talking about this but please don't expect anything soon. IF this is something we do, we need to have a sustainable model and plan. We do not want to release something that only gets stale and we don't have any plans for continued support.
