### ISSUE TITLE
怎么用C++播放音乐

### ISSUE THREAD

**Issue by wu23873chen** [microsoft/microsoft-ui-xaml#2251]
Visual Studio 2019，基于C++/XAML的UWP开发，怎么播放声音

**Comment by ranjeshj** [comment]
@wu23873chen Can you please post your questions in English ? Is your question how to play sound ? Here are some links that you might find useful. 
https://docs.microsoft.com/en-us/windows/uwp/design/style/sound
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/media-playback

**Comment by Paul-Dempsey** [comment]
For reference, Bing Translate says:: 

> Visual Studio 2019, UWP Development based on C?/XAML, how to play sound

**Comment by wu23873chen** [comment]
> @wu23873chen Can you please post your questions in English ? Is your question how to play sound ? Here are some links that you might find useful.
> https://docs.microsoft.com/en-us/windows/uwp/design/style/sound
> https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/media-playback

How to play sound with C++？

**Comment by trekhs** [comment]
I hope provided links addressed your question. If you need further assistance, please reopen the issue. Thanks.
