### ISSUE TITLE
Crash in Windows.UI.Xaml in Release mode with animations triggered by Microsoft.Xaml.Interactivity behaviors

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/microsoft-ui-xaml#2256]
**Describe the bug**

When running my app in Release mode, I get the following exception when hovering with the mouse over a template that uses some behaviors to trigger some animations. This is the exception:

> Unhandled exception at 0x00007FFF1D7B2EC0 (Windows.UI.Xaml.dll) in WinUICrashRepro.exe: 0xC000027B: An internal exception occurrend in the application (parameters: 0x00000239CD4ADBE0, 0x0000000000000003).

**Steps to reproduce the bug**

1. Download this repro: [WinUICrashRepro_2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4452125/WinUICrashRepro_2.zip)
2. Open the solution
3. Run the app in Debug mode, and hover with the mouse on the template being displayed
4. Notice how the app behaves normally and the animations all work fine
5. Run the app in Release mode
6. Notice how the app crashes as soon as you hover on the template

**Expected behavior**

The app should work in Release mode just like it does in Debug mode

**Screenshots**

![UiBcn5RMdf](https://user-images.githubusercontent.com/10199417/78815462-9c42bf80-79d0-11ea-9c20-071ad36eaf8e.gif)

**Version Info**

NuGet package version: 
- `Microsoft.NETCore.UniversalWindowsPlatform` version `6.2.10`
- `Microsoft.UI.Xaml` version `2.3.200213001`.
- `Microsoft.Xaml.Behaviors.Uwp.Managed` version `2.0.1`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Looks like this issue might be related to the APIs in `Microsoft.Xaml.Interactivity`.
In particular, the storyboard animations are triggered with these behaviors:

```xml
<interactivity:Interaction.Behaviors>
    <core:EventTriggerBehavior EventName="PointerEntered">
        <core:CallMethodAction TargetObject="{x:Bind StoryboardZoomIn}" MethodName="Begin"/>
    </core:EventTriggerBehavior>
    <core:EventTriggerBehavior EventName="PointerExited">
        <core:CallMethodAction TargetObject="{x:Bind StoryboardZoomOut}" MethodName="Begin"/>
    </core:EventTriggerBehavior>
</interactivity:Interaction.Behaviors>
```

Removing these lines removes the animations, but it also seems to prevent the issue from happening. Hopefully this might help a bit in investigating this issue.

Thank you for your time! 😄

**Comment by michael-hawker** [comment]
@Sergio0694 the XAML Behaviors repo is [here](https://github.com/Microsoft/XamlBehaviors). The Toolkit also uses an older version, we have an [issue to update it](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3008) as well.

So, if you can isolate the toolkit out of the issue, that may be beneficial in finding the root cause and the right place to direct the issue too.

**Comment by JasonStein** [comment]
@Sergio0694 Can you try add below entry in your csproj file and to see if it resolve your problem? The one comes with WCT is on version 1.x, adding below line will force your project to use 2.0.1 version of the Behaviors package.

    <PackageReference Include="Microsoft.Xaml.Behaviors.Uwp.Managed">
      <Version>2.0.1</Version>
    </PackageReference>

**Comment by Sergio0694** [comment]
I've updated the issue: all the `Microsoft.Toolkit.*` references are gone now, and I've updated to `Microsoft.Xaml.Behaviors.Uwp.Managed` version `2.0.1` directly, same issue unfortunately 😟

**Comment by ranjeshj** [comment]
can you see if details in [this ](https://github.com/microsoft/microsoft-ui-xaml/issues/2086)issue helps make it repro in debug ? I'm guessing some type is not in the metadata and possibly needs the bindable attribute.

**Comment by Sergio0694** [comment]
Hi @ranjeshj - thanks for chiming in!
I tried your suggestion and added the directive in question to my `.csproj` file (here for reference):

```xml
<EnableTypeInfoReflection>false</EnableTypeInfoReflection>
```

This didn't reproduce the issue though, the Debug build still worked fine for me.
Looks like it's not exactly the same issue then 🤔

**Comment by ranjeshj** [comment]
This looks like a crash in Microsoft.ui.xaml.interactions library.

Cannot find method named Begin on object of type Windows.UI.Xaml.Media.Animation.Storyboard that matches the expected signature.

 	[Managed to Native Transition]	
>	Microsoft.Xaml.Interactions.dll!Microsoft.Xaml.Interactions.Core.CallMethodAction.Execute(object sender, object parameter = {Windows.UI.Xaml.Input.PointerRoutedEventArgs}) Line 104	C#
 	Microsoft.Xaml.Interactivity.dll!Microsoft.Xaml.Interactivity.Interaction.ExecuteActions(object sender = {System.Runtime.InteropServices.WindowsRuntime.IIterator_PrivateRCWAdapter<Windows.UI.Xaml.DependencyObject>}, Microsoft.Xaml.Interactivity.ActionCollection actions, object parameter = {Windows.UI.Xaml.Input.PointerRoutedEventArgs}) Line 95	C#
 	Microsoft.Xaml.Interactions.dll!Microsoft.Xaml.Interactions.Core.EventTriggerBehavior.OnEvent(object sender = {Windows.UI.Xaml.Input.PointerRoutedEventArgs}, object eventArgs) Line 214	C#
 	System.Private.SharedLibrary.Interop.Generated.dll!Windows.Foundation.Collections.MapChangedEventHandler<System.__Canon, System.__Canon>.Invoke(Windows.Foundation.Collections.IObservableMap<System.__Canon, System.__Canon> sender, Windows.Foundation.Collections.IMapChangedEventArgs<System.__Canon> event)	C#
 	WinUICrashRepro.McgInterop.dll!__Interop.ReverseComStubs.Stub_5<System.__Canon>(object __this, void* unsafe_sender, void* unsafe_e, System.IntPtr __methodPtr)	C#
 	WinUICrashRepro.McgInterop.dll!Windows.UI.Xaml.Input.PointerEventHandler__Impl.Vtbl.Invoke__n(System.IntPtr pComThis = 0x1124f940, void* unsafe_sender = 0x112159cc, void* unsafe_e = 0x11372770)	C#
