### ISSUE TITLE
NavigationView uses AutomationName for both full control and list of menu items

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#2269]
**Describe the bug**
A change was made to bind the NavView automation name to the list of menu items [here](https://github.com/microsoft/microsoft-ui-xaml/commit/580e5cedfed05bb11f6b5bfdc74125ea6f3bfafb).

This created a new issue where the automation name is announced whenever focus is moved back to the NavigationView, such as when focus is moved from a control outside the NavView to the hamburger button.

**Steps to reproduce the bug**
1. Set AutomationProperties.Name on the NavigationView
2. Navigate to the list of menu items via Narrator and observe the name is announced (correct).
3. Navigate to a button or other control outside the NavView.
4. Navigate to the hamburger button, observe Narrator announces the name again (incorrect).

**Expected behavior**
Need a way to set an automation name for the list of menu items without impacting the Narrator experience for the rest of the control.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19605)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment]
Would anybody benefit from having the NavigationView have a different UIA name compared to its menu items? Afaik the menu items list is known to the narrator as list, so there probably is not much confusion about that.

To decouple those two values and enable easy setting of the list, we would need to create a new property. I am not sure if this would be a good from an API standpoint, just having a member that is just used to set the name of an internal control.

**Comment by StephenLPeters** [comment]
Does this repro with the latest prerelease?  The change you linked is to NavigationViewList which was removed recently with the refactor to use itemsRepeater.  @ojhad maybe you know?

**Comment by joshkoon** [comment]
@StephenLPeters Yes, it still repros. I linked to the change where it was introduced, but it was brought forward to the ItemsRepeater.

@chingucoding I agree having a separate property just for the list isn't ideal from an API standpoint. I haven't had a chance to think through a proper fix, yet, but I did want to get the issue filed. The original request for a name for the list came from an accessibility need to name lists to describe the contents. However, naming the list, e.g. "Features", then led to this new issue where the name is now also read out when navigating to the Hamburger button, or other controls in NavView.

**Comment by StephenLPeters** [comment]
Work arounds that you have access to now are retemplating the control and replacing the automationproperties.name with the name you want. Or you can use VisualTreeHelper to walk to the repeater from code behind and set the property there.  I'm not sure what the proper fix to this would look like. I don't think a new API is appropriate, perhaps we can figure out some way to expose this as a resource that you could override at the page level.   Would it be better if we just changed the Accessibility view of this component to raw so it didn't participate in the narrator experience?

**Comment by chingucoding** [comment]
Adding a new API is indeed not ideal. A themeresource for would be a possible solution, though usually theme resources are used for "settings" that apply to all controls, and the UIA name of the list probably doesn't fit into that list that much.

**Comment by ranjeshj** [comment]
@joshkoon There does not seem to be a good fix for this issue and there are some workarounds. Would the workarounds suffice for you ? @anawishnoff as FYI.
