### ISSUE TITLE
Remove Navigation view code for checking if selection really changed

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#2270]
With #2253 checked in I think there is some code in navigation view which guarded against selection changed events that weren't real. We could now delete that code.

**Comment by StephenLPeters** [comment]
@ojhad FYI

**Comment by ojhad** [comment]
@StephenLPeters 
See my comment regarding this here: https://github.com/microsoft/microsoft-ui-xaml/pull/2253#issuecomment-611794971

**Comment by chingucoding** [comment]
If I understand @ojhad correctly, there is nothing to do here and this issue can be closed right?

**Comment by ojhad** [comment]
Yep, that's correct. @StephenLPeters closing this issue.
