### ISSUE TITLE
RichEditBox highlighted on pointer over when IsHitTestVisible="False"

### ISSUE THREAD

**Issue by ivanicin** [microsoft/microsoft-ui-xaml#2273]
**Describe the bug**
This code should show no highlight on hover:

`<RichEditBox IsHitTestVisible="False">
                                        <RichEditBox.Resources>
                                            <SolidColorBrush x:Key="TextControlBackgroundPointerOver" Color="Transparent"/>
                                        </RichEditBox.Resources>
                                    </RichEditBox>`

**Steps to reproduce the bug**

1. Use the code above

**Expected behavior**

When the pointer is over the `RichEditBox `the background should be transparent

Probably it shouldn't react to pointer over at all if `IsHitTestVisible="False"`, but if it reacts it should respect then `TextControlBackgroundPointerOver `resource.

**Screenshots**
When the pointer is over the `RichEditBox `the background is highlighted

**Version Info**

NuGet package version: 

2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

November 2019 Update (18363) Yes

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |
Desktop Yes

**Additional context**

**Comment by StephenLPeters** [comment]
Is this a scenario where you can use a RichTextBlock instead?

**Comment by ivanicin** [comment]
> Is this a scenario where you can use a RichTextBlock instead?

From the theory standpoint yes, from the practical standpoint no. Meaning if RichTextBlock  supported all text formattings, yes, but it doesn't support even some basic things let alone some more complex things.

**Comment by chrisglein** [comment]
@ivanicin Can you elaborate more on your scenario for wanting a RichTextBox that doesn't respond to any pointer/mouse input? This does seem like a bug, but understanding the reason you'd want this helps put the priority into context.

**Comment by ivanicin** [comment]
> @ivanicin Can you elaborate more on your scenario for wanting a RichTextBox that doesn't respond to any pointer/mouse input? This does seem like a bug, but understanding the reason you'd want this helps put the priority into context.

I need to highlight the text with a custom highlight color. That is impossible with the `TextBlock `for multiple reasons. First reason is that it doesn't have a `Background `property. Second reason is that dividing text into `Run` parts seem to be buggy and now and then text flow isn't stable. The final reason is that even if all those things worked sometimes I would need a flexible number of highlights that may happen. Making this with `Run `with be very hard or even impossible, at the very best it would be a code that would be extremely hard to read and edit further if needed.
