### ISSUE TITLE
Setting CompactPaneLength before rendering in XAML does not update pane correctly

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2277]
**Describe the bug**

**Steps to reproduce the bug**

1. Create NavView in XAML, set CompactPaneLength to a non standard value, e.g. 80
2. Open page with that NavView

**Expected behavior**

TogglePaneButton and BackButton get rendered correctly, that is the button icons are centered and the buttons take up the same space as the NavigationViewItems icons.
**Screenshots**

![image](https://user-images.githubusercontent.com/16122379/79081274-20bc7780-7d1c-11ea-8af1-fed1e2c0ef5a.png)

**Version Info**

NuGet package version: 

Latest commit on master branch.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19603)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
@chingucoding Looking at the description and the pictures provided, we aren't sure what is wrong, could you elaborate further?

**Comment by chingucoding** [comment]
The expected behavior/UI would be that the pane and back buttons are centered too:

![image](https://user-images.githubusercontent.com/16122379/79156881-ef9f7e00-7dd3-11ea-8e32-b46c80ceb990.png)

**Comment by ranjeshj** [comment]
@ojhad as FYI

**Comment by chingucoding** [comment]
@ojhad @ranjeshj I would like to look into this. Would it be better to wait until the other NavView PR's have gone through, especially  #2271 to avoid merge conflicts?

**Comment by Kinnara** [comment]
The reason why calling `UpdatePaneButtonWidths` in `OnApplyTemplate` doesn't fix this is that `paneToggleButton`'s template hasn't been applied by the time the `NavigationView`'s `OnApplyTemplate` is called. And calling `GetTemplateChild` won't realize the child if the template hasn't been applied. Waiting for the `Loaded` event won't always help either, since a collapsed element can be loaded without its template applied. We could call `paneToggleButton.ApplyTemplate()` to force apply the template, however I still think using a binding to set the icon column's width would be simpler.

**Comment by StephenLPeters** [comment]
@chingucoding I believe we would not accept a fix to this until #2271 is in so if you'd rather wait I think that is reasonable.

**Comment by chingucoding** [comment]
I'll wait then until #2271 is through :)
