### ISSUE TITLE
Proposal: Support Visualtree dumping and 'master file' testing

### ISSUE THREAD

**Issue by licanhua** [Microsoft/microsoft-ui-xaml#228]
# Proposal: Support Visualtree dumping and 'master file' testing

## Summary
The visual tree is used internally for the UI rendering process, but knowing the structure of the visual tree is important for certain scenarios, such as writing or replacing a control template, or analysis of a control's structure and parts at run-time. 
A "master file" is the expected output of the test and it's stored as a separate file. When the test is executed, it will read in the file and compare it to the output of the product.
So this proposal is a combination of the visual tree and 'master file', and applies them in controls testing: we dump visualtree for each control as a baseline or 'master file', then we compare the runtime visualtree with the 'master file'. 

## Rationale
We have similar implementation in OS, and it used internal API for dumping and comparsion.

The goal is to help to catch the bugs because the change of:
1. Layout like height, width, thickness of border
2. Colors like Background and foreground.
3. Margin, padding, Name
4. VisualState change like PointerOver, Pressed
5. Downlevel. We supports OS from RS1 to latest insider OS. The changes can be seen from the failed test cases.
6. Things related to Dark or Light theme

## Functional Requirements

| # | Feature
--- | ---
1| Allow user to collect currect visual tree
2| Allow user to customize the collection process for the visual tree.
3| Allow testapp to package the 'master file'
4| Support we have different 'master file' for difference OS release for the same test case
5| Allow user to verify visual tree for Dark and Light mode
6| Allow diff the output with 'master file' and log it in test output

### Collect the visual tree and update master files
In this proposal, we still need to manually run the tests and update master files. And also we need to do it against different version of OS one by one.
It would be a headache since we supports all version of OS from RS1 to RS5, 19H1 to latest OS. We can automated the collect/update process, but it's not in the scope of this proposal.

-  Collect 'master files'
    `.\RunTests.ps1 *VerifyVisualTree* -LogMasterFile`
When running the test with `-LogMasterFile`, 'master files' will be collected if test fails. And master file(.xml.org) and dumped file(.xml) are put into a folder out of the app like 'Music'. it would includes paired files like below:
    CommonStylesVisualTreeTests_VerifyVisualTreeExampleWithCustomerFilter-Dark-7.xml.orig
    CommonStylesVisualTreeTests_VerifyVisualTreeExampleWithCustomerFilter-Dark-7.xml
You can see the difference from output of RunTests.ps1, also you can diff the above two files.

- Update master file
When the new master file are accepted, copy them(.xml only) to master directory and check in the changes. master directory is in:
    test\MUXControlsTestApp\master
      
- Customize the collected data
We only collect very limited data by default, but it allows us to customize the collection process. 
We can control it in three ganularities:
1. Element level - ShouldLogElement
2. Property level - ShouldLogProperty
3. property/value level - IsKnownProperty. If IsKnownProperty returns true, the property would not be logged.

IFilter interface:
```
        public interface IFilter {
            bool ShouldLogElement(string elementName);
            bool ShouldLogProperty(string propertyName);
            bool IsKnownProperty(string propertyName, string value);
        }    
```

Sample Filter: Ignore all properties expect it starts with Actual
```
        class CustomFilter1 : VisualTreeDumper.DefaultFilter 
        {
            public override bool ShouldLogProperty(string propertyName)
            {
                if (!propertyName.StartsWith("Actual"))
                {
                    return false;
                }
                return true
            }
        }
        
        var content = VisualTreeDumper.DumpToXML(root, new CustomFilter1());
```

Sample Filter: If Padding/IsTabStop/IsEnabled/IsLoaded equal to their known value, don't log it.
```
        class CustomFilter2 : VisualTreeDumper.DefaultFilter 
        {
            public override bool IsKnownProperty(string propertyName, string value)
            {
                string v = _knownPropertyValueDict.ContainsKey(propertyName) ? _knownPropertyValueDict[propertyName] : VisualTreeDumper.NULL;
                return v.Equals(value);
            }
            
            private static readonly Dictionary<string, string> _knownPropertyValueDict = new Dictionary<string, string> {
                {"Padding", "0,0,0,0"},
                {"IsTabStop", "False" },
                {"IsEnabled", "True"},
                {"IsLoaded", "True" },
            };
        }         
```
        
### Support different visualtree for different version of OS
Some rule to avoid conflicts for 'master file' name:
1. master name format: [testclass]_[testname]_[theme/customized name].xml or [testclass]_[testname]_[theme/customized name]-[apiversion].xml. 
2. master file searching: If running os is RS5, the api version = 7, then first  look if [testclass]_[testname]_[theme/customized name]-7.xml exists, if not, try [testclass]_[testname]_[theme/customized name]-6.xml... [testclass]_[testname]_[theme/customized name]-2.xml, and finally [testclass]_[testname]_[theme/customized name].xml

### Authoring test case
To supports different kinds of scenarios, We provides three functions: 
1. * VerifyVisualTree(string xaml) 
   It loads and setups the visualtree from a xaml string, then setups RequestedTheme and verifies visualtree for Light and Dark theme.
 2. * VerifyVisualTree(UIElement root, Theme theme)
  You setup the visual tree, then provides root. Then it setups RequestedTheme to theme specified and verifies visualtree for it.
 3. * VerifyVisualTree(UIElement root, String customName)
  You setup the visual tree and RequestedTheme, it only verifies visualtree with customized master name.

- Simple case

```
    var xaml = @"<Grid Width='400' Height='400' xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'> 
                    <StackPanel>
                        <AppBarButton Icon='Accept' Label='Accept'/>
                        <AppBarToggleButton Icon='Dislike' Label='Dislike'/>
                    </StackPanel>
               </Grid>";
    VerifyVisualTree(xaml);
```

- Verify visual tree only for Light theme

 ```
  UIElement root = SetupVisualTree();
  VerifyVisualTree(root, Theme.Light);
```

- Control changing Theme by yourself and allow multiple pair of master files.
By default, We have the name like [Prefix]-Dark-7.xml/[Prefix]-Light-7.xml when you VerifyVisualTree(root, Theme.All). If we have more than one checkpoint, we need more than one pair of files. For example:
[Prefix]-Dark1-7.xml/[Prefix]-Light1-7.xml [Prefix]-Dark2-7.xml/[Prefix]-Light2-7.xml 

```
     UIElement root = SetupVisualTree();
    RunOnUIThread.Execute(() =>
    {
        (root as FrameworkElement).RequestedTheme = ElementTheme.Light;
    });
    VerifyVisualTree(root, "Light1");
    // Do something
    RunOnUIThread.Execute(() =>
    {
        (root as FrameworkElement).RequestedTheme = ElementTheme.Light;
    });
    VerifyVisualTree(root, "Light2");
    // Do something
         UIElement root = SetupVisualTree();
    RunOnUIThread.Execute(() =>
    {
        (root as FrameworkElement).RequestedTheme = ElementTheme.Dark;
    });
    VerifyVisualTree(root, "Dark1");
    // Do something
    RunOnUIThread.Execute(() =>
    {
        (root as FrameworkElement).RequestedTheme = ElementTheme.Dark;
    });
    VerifyVisualTree(root, "Dark2");
```
    
- Verify visual tree with customized visualtree dumper.

```
    var xaml = @"<Grid Width='400' Height='400' xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'> 
               </Grid>";
    VisualTreeDumpFilter = new CustomFilter();
    VerifyVisualTree(xaml);    
```

- Do visual tree comparsion from the testapp other than test case

```
        public void OnRunTestClicked(object sender, object args)
        {
            var content = VisualTreeDumper.DumpToXML(root);
            var expectedContent = "..."
            
            ResultDiff.Text = VisualTreeOutputCompare(content, expectedContent);
        }
```

## Important Notes
Suggestions to author the test case:
1. By default, to keep the solution to be easy to maintain and easy to use, we collected data as less as possible.
2. Avoid one control's change will impacts a dozen test cases.

## Open Questions
1. How to verify HC
2.

**Comment by chrisglein** [comment]
> So here 'master' is the same term as 'golden file' in this proposal.

Why the change in term?

**Comment by chrisglein** [comment]
> * Customize the collected data

Your example filters based on property name. It might be handy to write a filter that can filter on value. Particularly whether the property matches the default value.

**Comment by chrisglein** [comment]
> * Allow more control on visual tree setup and provide multiple customized filenames for the same test case

In this example you specifically change theme, but in the next you passed in an arg. The XAML is the same in the first example regardless of theme. Can you just specify the theme instead? Can you pass in multiple themes as flags?

**Comment by chrisglein** [comment]
> VisualTreeDumpFilter = new CustomFilter();
    VerifyVisualTree(xaml);

Why isn't the filter an arg to VerifyVisualTree like it seems to be for DumpToXML?

**Comment by chrisglein** [comment]
> 1. By default, to keep the solution to be easy to maintain and easy to use, we collected data as less as possible.

This is a pretty important point and worth expanding on. You outlined a CustomFilter, but I think we should talk through what some standard filters should be. Just hierarchy, bounding boxes, colors, etc. We're going to want standard options and guidelines on when to use them.

**Comment by chrisglein** [comment]
> * When running the test `-LogMasterFile`, 'golden files' will be collected and put into a folder out of the app like 'Music'

And then what? How do we want to use that file moving forward? Does it live in a repo somewhere? Is it the same one? Can we automate updating the golden files into the repo so maintaining these files is painless in the common case?

**Comment by licanhua** [comment]
> > So here 'master' is the same term as 'golden file' in this proposal.
> 
> Why the change in term?

Master is hard to u

> > * Customize the collected data
> 
> Your example filters based on property name. It might be handy to write a filter that can filter on value. Particularly whether the property matches the default value.

The pull request #126 already provides a function in IFilter for this:
` IsKnownProperty(string propertyName, string value)
`
I will add an example for this

**Comment by licanhua** [comment]
> > So here 'master' is the same term as 'golden file' in this proposal.
> 
> Why the change in term?

Removed 'golden'
