### ISSUE TITLE
Can't drag tabs to adjust order in Winui3 for a tabview

### ISSUE THREAD

**Issue by yinyue200** [microsoft/microsoft-ui-xaml#2281]
**Describe the bug**
  Can't drag tabs to adjust order in Winui3 for a tabview

**Steps to reproduce the bug**

1. Go to Xaml-Controls-Gallery Tab View Page
2. Try to move document3 to front of document2 using a mouse

**Expected behavior**
moved

**Screenshots**

**Version Info**
winui3 alpha

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI, looks like a bug coming in from the work Xaml Controls Gallery did to run their tests against winui3.  We should investigate/track.

**Comment by codendone** [comment]
This works now in the 0.8 release (albeit with some visual problems tracked by other issues).
