### ISSUE TITLE
MediaPlayer in FrameServer mode - sometimes returns blank frames

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#2285]
**Describe the bug**

When using MediaPlayer with `IsVideoFrameServerEnabled=true`, and handling VideoFrameAvailable, sometimes I get blank frames (basically, the whole screen is black).

**Steps to reproduce the bug**

I'm writing a class to preview specific video frames. I have a function `public get_video_frame_info get_closest_frame(double ms)`, which gives me the closest frame I have cached.

Assuming the user usually travels forward, my cache will load frames ahead - so, when user is requesting a frame, I will start loading the first 3.5 seconds ahead.

I handle the `VideoFrameAvailable`, more or less:

	var rt = new use_render_target(this);
	if (rt.render_target != null) {
		using (rt.render_target.CreateDrawingSession())
			sender.CopyFrameToVideoSurface(rt.render_target);

		// the idea here is not to block the "play thread"
		Task.Run(async () => {
			var bmp = await SoftwareBitmap.CreateCopyFromSurfaceAsync(rt.render_target);
			lock(this)
				cache_.Add(new frame_info(pos_ms, bmp));
			rt.Dispose();
		});
	}

Every now and then, I end up having a "blank" frame out of nowhere.

Note: initially I thought this would have something to do with the fact that I'm playing the video while grabbing frames (even though it should not matter), but that is not the case - I've changed to code to manually move to the next frame using `.StepForwardOneFrame()`.

[test_video_frame_grabber_play.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4475345/test_video_frame_grabber_play.zip)

I've attached a full running example: you just need to copy an .mp4 file with at least 20 seconds of footage into folder `ApplicationData.Current.LocalFolder.Path`. Mine is an mp4 of 1920x1080.

I'm saving different frames to disk - you'll see that some of them have a size of 1023 bytes (blank frames).

Just in case you can't repro, I'll give you a link to my .mp4 - I'm not allowed to distribute it.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  |  Yes    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**

**Comment by jtorjo** [comment]
Another note: it seems that sometimes CopyFrameToVideoSurface fails silently. If we just had a way to know it failed, I'd be happy. 

Like, simply return a bool.

**Comment by weltkante** [comment]
I assume you made sure the "obvious" race condition doesn't happen where the next frame arrives before the previous finished copying? Your snippet above does not protect `rt.render_target` from being overwritten by the next available frame.

**Comment by jtorjo** [comment]
@weltkante The use_render_target is so I can continue processing frames while I copy them to SoftwareBitmaps (basically, I lock a render target until it's done copying). 

Even if you slightly modify the code to not use Task.Run(), the black frames will still happen.

**Comment by Austin-Lamb** [comment]
The WinUI team doesn't author the MediaPlayer itself, just the MediaPlayerElement that ties MediaPlayer into a XAML element tree.  I've forwarded this feedback on to the other team at Microsoft that owns MediaPlayer.

**Comment by bpulliam** [comment]
Closing stale external bug. If you are still seeing this issue, please open a new issue in the Feedback Hub so that it may gather related logs/diagnostics.
