### ISSUE TITLE
MediaPlayer in FrameServer mode - sometimes it sends VideoFrameAvailable events indefinitely on the same frame

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#2286]
**Describe the bug**

Using MediaPlayer with `IsVideoFrameServerEnabled=true`, it will sometimes send the VideoFrameAvailable indefinitely. 

Every now and then, it comes back to normal (sending it one once, when it reaches a frame) - at this point, I can't figure out why this is happening.

**Steps to reproduce the bug**

You can use the example from https://github.com/microsoft/microsoft-ui-xaml/issues/2285 - and while just by running it, you'll see a lot of `same play frame` on the console.

To make this even clearer, you can modify test_video_frame_grabber_play() like this:

        private void test_video_frame_grabber_play() {
            var root_dir = get_root_directory();
            var grabber = new video_frame_grabber_play(root_dir + "transition2.mp4", 1500) {
                desired_size = new BitmapSize{ Width = 640, Height = 360 }
            };
		}

**Expected behavior**

I'm expecting, when MediaPlayer arrives at a frame, to send me a **single** VideoFrameAvailable event.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Comment by Austin-Lamb** [comment]
The WinUI team doesn't author the MediaPlayer itself, just the MediaPlayerElement that ties MediaPlayer into a XAML element tree.  I've forwarded this feedback on to the other team at Microsoft that owns MediaPlayer.

**Comment by bpulliam** [comment]
Closing stale external bug. If you are still seeing this issue, please open a new issue in the Feedback Hub so that it may gather related logs/diagnostics.
