### ISSUE TITLE
Installing with Visual Studio 2017 and C++/WinRT causes project to rebuild every time and crashes the XAML designer.

### ISSUE THREAD

**Issue by JosephClampett** [Microsoft/microsoft-ui-xaml#229]
**Steps to reproduce the bug**
1. Create a "Blank App" using the template provided with the C++/WinRT VSIX.
2. Change "Target Platform Min. Version" to match "Target Platform Min. Version" (probably not necessary)
2. Install this NuGet package.
3. Add the required snippet (`
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
    </Application.Resources>`) to App.xaml and `#include` the four headers (`
#include "winrt/Microsoft.UI.Xaml.Automation.Peers.h"
#include "winrt/Microsoft.UI.Xaml.Controls.h"
#include "winrt/Microsoft.UI.Xaml.Media.h"
#include "winrt/Microsoft.UI.Xaml.XamlTypeInfo.h"`) to pch.h.
4. Add `xmlns:control="using:Microsoft.UI.Xaml.Controls"` on line #4 of MainPage.xaml.
5. Replace the button element with a color picker (`<controls:ColorPicker/>`) and remove the click event handler in MainPage.cpp and its prototype in MainPage.h.
6. Press [Build] or [Ctrl] + [Shift] + [B]
7. Press [Build] or [Ctrl] + [Shift] + [B] again

**Expected behavior**
- The XAML designer should simply not crash.
- Pressing [Build] without making changes to the project should not rebuild it.

**Version Info**
- Windows 10 Version: 17763.292
- Windows SDK Version: 10.0.17763.0
- Visual Studio 2017 Version: 15.9.6
- Microsoft.UI.Xaml NuGet Package Version: 2.0.181018003.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)   | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |

**Comment by jevansaks** [comment]
I'm following up to see who owns these areas (probably xlang and VS).

**Comment by chabiss** [comment]
Regarding the issue with the designer crashing... Please report this problem using "Report a Problem:" tool in Visual Studio 
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017

**Comment by JosephClampett** [comment]
The extension alone causes this though.

**Comment by JosephClampett** [comment]
That's not really true.

**Comment by jevansaks** [comment]
@JosephClampett please report this issue through the VS reporting tool. If you are still seeing the rebuild issue I can help you get that ported over to the xlang repo.
