### ISSUE TITLE
MediaPlayer in FrameServer mode - when changing position, the first few frames are incorrect

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#2291]
**Describe the bug**

This is **really bad**. I'm trying to capture video frames by setting the player's `.PlaybackSession.Position` to a specific position. 

I'm grabbing frames from several locations in the video, so I do change `.Position` quite a lot.
When I do change the Position, the first few frames are incorrect. By doing quite a bit of trial and error, this seems to be for the first 2-3 frames, **but I can't be sure**.

I really need a way to know if a frame is correct or not, like, an .IsAccurate on the frame itself, or in the arguments of `VideoFrameAvailable` event.

**Steps to reproduce the bug**

	private async void Player__VideoFrameAvailable(MediaPlayer sender, object args) {
		// when changing position -> this is incorrectly set when I get here			
		var pos_ms = player_.PlaybackSession.Position.TotalMilliseconds;
		....
	}

Say you have a 1 minute video, and you want 4 consecutive frames from beginning, 4 consecutive frames at second 10, and 4 consecutive frames at second 30. 

You grab the first 4 frames, change position, grab the next 4 frames, change position and grab the last 4 frames. Probably 6 frames will be incorrect.

**Expected behavior**

When `VideoFrameAvailable` is fired, one of the following should happen:
1.  the position reported by `player_.PlaybackSession.Position.TotalMilliseconds` should be accurate to the frame, if not to the millisecond.
2. if the position is inaccurate, I should have an `.IsAccurate` property, either in `MediaPlayer`, or in the args sent to `VideoFrameAvailable` event

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |

**Comment by Austin-Lamb** [comment]
The WinUI team doesn't author the MediaPlayer itself, just the MediaPlayerElement that ties MediaPlayer into a XAML element tree.  I've forwarded this feedback on to the other team at Microsoft that owns MediaPlayer.

**Comment by jtorjo** [comment]
@Austin-Lamb Thanks! Where is that - I can post to another repository if needed. Anyway, I'm really curious about this, because this is pretty critical to me. 

For the other 2 issues, I can have workarounds, but to this one, I don't know if there's any workaround.

**Comment by jtorjo** [comment]
I've played with this for quite a bit. The incorrect positioning happens while I change the `player.PlaybackSession.Position`. Contrary to docs, it can happen to up to 3 frames (so, I change the position, and then the first 3 received frames are incorrect). 

I've temporarily solved this by listening to .`SeekComplete`, and from then on, disregarding the first 2 frames. It's pretty far from ideal.

For this, I would love one of the following:
1. either have some extra property `IsAccurate`, in MediaPlayer.PlaybackSession, OR even better
2. have another property, more or less `.AccuratePosition`, which would be a get-only property, and return the actual position of the frame I'm at

**Comment by JohnnyWestlake** [comment]
A usable workaround is to actually grab the frame from inside an IBasicVideoEffect (or IVideoCompositor) implementation, where you can actually determine the *exact* timing of each frame as they're rendered (because there's a video buffer you might get extra frames, but you'll know whether or not you want them).

As you don't instantiate your own VideoEffectDefinition's and the framework does it for you, passing that frame back into your code can require some workarounds - like a static handler or some messenger (and they may also be attached to a different IDirect3DDevice instance than your foreground app, so you may need to convert if you want to draw the frame outside the video pipeline)

**Comment by jtorjo** [comment]
@JohnnyWestlake Thanks! This is definitely something to keep in mind. Right now, I'm kinda' happy with my workaround, and I need to do quite a bit to integrate it into my app. Having said that, I've encapsulated the implementation so that I can easily change it to use what you're saying.

I'm curious if you know how this will behave to a lot of re-instantiations. In other words, assuming the user is doing a lot of editing, I would need to either:
1. modify MediaComposition (I've never done that in the past, I would just construct it and then use it)
2. re-create the MediaComposition on each edit.

If 1. is possible, things would be pretty easy. I don't mind doing 2. as long as it's fast.

**Comment by jtorjo** [comment]
@Austin-Lamb I've updated the bug description - I hope it's easier to understand now.

@Austin-Lamb Is what I want doable, and if so -- in the more or less near future (1-2 months)? This is a quite important feature for me. I need to be able to accurately grab frames

@JohnnyWestlake I've thought about this quite a bit. At this time, i can't really use your workaround, because I'm about to implement time remapping, and  I will need quite a few frames from a lot of places in the video (and not necessary consecutive frames), so it won't always be contiguous frames.

**Comment by bpulliam** [comment]
Closing stale external bug. If you are still seeing this issue, please open a new issue in the Feedback Hub so that it may gather related logs/diagnostics.
