### ISSUE TITLE
Proposal: TabView should expose internally used ItemContainerTransitions as a property

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2294]
# Proposal: TabView should expose internally used ItemContainerTransitions as a property

## Summary
This came up recently in the UWP Discord Community. Someone wanted to remove the default animations of the TabView control (animation used for adding/deleting/reordering/... TabViewItems). In order to do that, the `TabViewListView` style can be overriden in XAML:
```xml
<Style TargetType="primitives:TabViewListView">
    <Setter Property="ItemContainerTransitions">
        <Setter.Value>
            <TransitionCollection />
        </Setter.Value>
    </Setter>
</Style>
```
(Using code-behind is also possible.)

These approaches don't seem to be easily discoverable without having to look at the TabView.xaml file located in the WinUI repo.

To improve the developer experience, this proposal seeks to have the `TabView` control directly expose an `ItemContainerTransitions` property so that these animations can be modified directly from the TabView itself.

## Rationale
This proposal is mainly aimed at providing a similar animation customization experience for the TabView control compared to item controls like the ListView/GridView. These controls expose an `ItemContainerTransitions` property usable like this:
```xml
<ListView>
    <ListView.ItemContainerTransitions>
        <TransitionCollection />
    </ListView.ItemContainerTransitions>
</ListView>
```
(This removes the default animations.)

| Capability | Priority |
| :---------- | :------- |
| This proposal will expose an `ItemContainerTransitions` property directly on the TabView control and thus allow developers to customize animations used, for example, for adding/reordering/removing TabViewItems. | Must |

## API Details
```cs
//
// Summary:
//     Gets or sets the collection of Transition style elements that apply to the item
//     containers of a TabView.
//
// Returns:
//     The collection of Transition style elements that apply to the item containers
//     of a TabView.
public TransitionCollection ItemContainerTransitions { get; set; }
```

```xml
<TabView>
    <TabView.ItemContainerTransitions>
        <TransitionCollection />
    </TabView.ItemContainerTransitions>
</TabView>
```

This new TabView property would just get and set the *ItemContainerTransitions* property of the internally used TabViewListView.

## Additional Context
If this gets the greenlight I would like to implement this.

**Comment by ranjeshj** [comment]
Currently we can retemplate the control to change this. Once we move TabView over from ListView to use ItemsRepeater, we will be using the ElementAnimator API instead. So I think we should not do this and for now let folks re-template to achieve this behavior. @stmoy would you agree ?

**Comment by stmoy** [comment]
Agreed. One of the big motivators to move to ItemsRepeater is animations. When we move to ItemsAnimator, we won't use ItemContainerTransitions so we shouldn't surface this API at this time.
