### ISSUE TITLE
ComboBox Dictionary binding bug

### ISSUE THREAD

**Issue by ccornici** [microsoft/microsoft-ui-xaml#2298]
**Describe the bug**
When binding a `Dictionary<string, string>` to a `ComboBox` having the `SelectedValuePath="Key"`, 
- the `SelectedItem` is not being updated.
- the `SelectedItem` set in the MainViewModel ctor is not being reflected in the UI

**Steps to reproduce the bug**

[Here's a repo which reproduces the issue.](https://github.com/ccornici/potential-uwp-bug) Please ignore the other controls. They are meant to showcase other bugs I filled.
But if I delete it in the future, then here's some context:

Give a ComboBox like:
`<ComboBox SelectedValuePath="Key" DisplayMemberPath="Value" SelectedItem="{x:Bind vm.SelectedItem, Mode=TwoWay}" ItemsSource="{x:Bind vm.MyItems, Mode=TwoWay}"/>`

And a ViewModel like:
```
public Dictionary<string, string> MyItems { get; set; } = new Dictionary<string, string>()

public MainViewModel()
{
    MyItems.Add("item_1", "ITEM 1");
    MyItems.Add("item_2", "ITEM 2");
    SelectedItem = "item_1";
}

private string _selectedItem;
public string SelectedItem
{
    get => _selectedItem;
    set => SetProperty(ref _selectedItem, value);
}
```

- When the user selects an item in the ComboBox, the SelectedItem is not updated with the....well....selected item.,,
- When setting the SelectedItem in the ctor, the ComboBox is empty, so the value is not reflected in the UI.

**Expected behavior**
- SelectedItem is updated with the selected item
- SelectedItem has "ITEM 1" selected when updated from the ctor

**Version Info**
Win 10 November 2019 Update (18363)

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Not sure if this is the right repo to fill the bug in since the ComboBox is not from WinUI but dunno which else if not...

**Comment by Marv51** [comment]
I had the same issue as you. I know this was filed a long time ago, but here is the solution: 

[Here](https://github.com/ccornici/potential-uwp-bug/blob/1507b48310e16b68dd83a4770154bc7518172f81/WinUIProblem/MainPage.xaml#L18) you are setting `Selected**Item**`. `SelectedValuePath` is completely ignored by design, as that is what the `Selected**Value**` property is for. 

I think this works as designed and the issue can be closed @ranjeshj.
