### ISSUE TITLE
Introduce the notion of OS Theme and App Theme in XAML

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#23]
# Proposal: OS Theme Resources as well as App Theme Resources

## Summary
With Windows 10 19H1 introducing the idea of System UI using a different theme to the Apps - It may be necessary to include the notion of providing UI to match the system, such as dialogs, or integrated XAML views outside of the app.

## Rationale
Providing the ability for an app's controls to adopt the OS colours may be needed for things like Sets where the window's colours may come from the OS setting, rather than the app's.  If controls like the NavigationView, Menu, top toolbars, etc start to blend into the Window Frame - the controls will need to handle fallback, so mapping resources and RequestedTheme options applied to templates, will need to map to compatible resource dictionaries.

## Functional Requirements
May require work in 19H1 to allow calling on resources provided by system settings for the OS theme and the App Theme options.

## Open Questions
I fully accept this may be me jumping several steps ahead with my thinking, considering the ability to have separate themes for System UI and for Apps has just been added, and it may be more of a request for all user's colour preferences to be exposed by the framework, and the intention may be not to provide that for any number of reasons.

**Comment by kikisaints** [comment]
Hmm, I'm not sure I fully understand what's being asked to add here. I believe all of the system colors (in Windows Shell) can be accessed today. Things like SystemAccentColorDark1, SystemAccentColorDark2, etc. can be called and used by the app-author. Those system colors should map to the user's colors that are picked in settings.

Perhaps I'm misunderstanding though, can you give an example of what you'd like (markup, pictures, whatever works to explain)?

**Comment by mdtauk** [comment]
At the moment there is a requested theme option for XAML.  By default this uses the current Theme setting.  As of 19H1 there is a Theme setting for apps, and a Theme setting for the OS.

I am suggesting that there could be a brush resources which use the OS Theme setting, as well as the App Theme setting.

But perhaps when rendering XAML outside of the app window, say for My People - that will automatically apply the OS theme resources to the app's XAML?

**Comment by chigy** [comment]
When Theme setting for the OS was introduced in 19H1, the intention was that OS is now supporting light theme that already existed for apps, and user has a choice to turn on this same light theme at the OS level or for all the applications they are running on their PC. 

In other words, the app theme and OS theme were not meant to be different. Given your comment, it appears that you see the theme for OS and apps to be different. I'd be curious to know what are the characteristics of differences that made you think so. 

Did I capture this correctly or did you mean something different?

**Comment by mdtauk** [comment]
> When Theme setting for the OS was introduced in 19H1, the intention was that OS is now supporting light theme that already existed for apps, and user has a choice to turn on this same light theme at the OS level or for all the applications they are running on their PC.
> 
> In other words, the app theme and OS theme were not meant to be different. Given your comment, it appears that you see the theme for OS and apps to be different. I'd be curious to know what are the characteristics of differences that made you think so.
> 
> Did I capture this correctly or did you mean something different?

As it is right now, you can choose between **Light, Dark, Custom**

If you choose custom, you can have the Taskbar, Action Centre, Start Menu and flyouts using the Dark Theme, while the apps use Light, or vice versa (which is what I am using on my Surface Go)

I was wondering if both options were discreet choices, and so if your app appears in a System Tray flyout, you would want to ensure it matches the theme.

It may not be a separate concept within the API though - it could be a local **RequestedTheme** override in the DLLs which contain those XAML/Win32 surfaces.

If it is a unique concept in the framework, it could be exposed to the developer.

![screenshot 8](https://user-images.githubusercontent.com/7389110/51726303-95938b00-205e-11e9-917a-629a4ef844db.png)

**Comment by chigy** [comment]
@mdtauk - Thank you for your clarification. The imgae you attached appears to be a bug. If you are an insider, I know the icons sometimes dissapear and I believe they are being addressed. Attaching what I see on my machine.
![image](https://user-images.githubusercontent.com/22958680/51765564-f6d25300-208c-11e9-9a71-09b57c6668fe.png)

**Comment by chigy** [comment]
@mdtauk - I also wanted to explain the logic and see if this helps and/or you have additional feedback/idea you would like us to consider.

You can set the theme in the following manner.
Choose your color – light / dark / custom
o	Light -- System/shell would be light and app would be light
o	Dark – System dark, app dark
o	Custom – starts by current selection before you selected custom, but you are able to mix and match the theme

So you can end up with all these combinations (system/app)
•	Light/Light, Dark/Dark, Light/Dark, and Dark/Light

As to the way app icons are selected for task bar is:
•	First check for light or dark theme icon and use appropriate icon.
•	If one is not specified, shell checks for the dominate color and selects the one that works for light theme (assuming dark theme icon works since it’s been the theme supported before)
•	If fails, try for high contrast light or dark icon.

**Comment by mdtauk** [comment]
@chigy that explanation makes sense to me.  My view is simply if the OS has the notion of apps using one theme, and system UI using another, should there be a way for developers to know or set Xaml elements to use the users choice of both within the app?

So the app is running in dark mode, but if the system UI is set to light, things like dialog boxes, share UI, could **RequestedTheme = "System theme"**

**Comment by chigy** [comment]
@mdtauk, when you say dialog boxes, do you mean ContentDialog that draws only on top of an app or the MessageBox that is a system level dialog? 

Here's our current design. ContentDialog, because it draws only on top of an app, it respects the theme of the page/app. If the page is light, light dialog popups up, etc. MessageBox should be opening up the dialog that matches the theme of the system since it would draw over everything. 

I'm not too familiar with the share UI design, but I'd think similar concept might be at play? It'd be great if you could share pictures to illustrate your point? Perhaps I am not seeing what you are seeing...

**Comment by mdtauk** [comment]
With 19H1 there are new Windowing APIs coming, so Content Dialog may be updated to render outside of the window bounds.

And the image I posted is not a bug, on my Surface Go I have it on Tablet mode, and hiding taskbar buttons.

**Comment by chigy** [comment]
@mdtauk - Content Dialog is not expected to be allowed to be rendered outside of the window bounds.

Could you explain what you meant to show by the image? I must have misunderstood your intention by the image of calculator...

**Comment by chigy** [comment]
@mdtauk , how is this proposal related or not related to the series of request on the other issue? #807

**Comment by mdtauk** [comment]
I posted this back in Dec 2018, when the first Insider builds included this feature.  I don't see it as directly related.  My point was that when XAML calls RequestedTheme, it is given the current App Mode theme.  But since 19H1 there is the App Mode and the Windows Mode.
![image](https://user-images.githubusercontent.com/7389110/59946755-5f1e3880-9463-11e9-8ff5-9204c22f8c33.png)

But developers currently have no way to query the Windows Mode theme.

I suppose the big question is, **Should** XAML devs be able to know what Windows Mode is currently set?

When developers are able to make taskbar flyout apps, and other Shell integrations with WinUI Desktop - will these UI surfaces use the Windows Modem or App Mode?

**Comment by chigy** [comment]
@mdtauk
>I suppose the big question is, Should XAML devs be able to know what Windows Mode is currently set?

Yes, indeed. Do you know the answer to this question or are you speculating? It would be helpful if you have the means to find out from developers out there. Otherwise not sure if we have the need for this feature since I don't know who'd use it.

**Comment by mdtauk** [comment]
@chigy  Sadly I am just an enthusiast and user, and rather than a concrete and defined proposal - as stated it is exploring the idea - but there was not too much discussion here, so I may well be on a wrong path.

**Comment by ShankarBUS** [comment]
Hey @mdtauk, this will be helpful for apps that show taskbar flyouts like EarTrumpet. They achieve this by reading the `HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\SystemUsesLightTheme` registry key. I don't know if you can read registries from UWP apps. This is not that important for **Pure UWP apps** and WinUI desktop apps can read the registry if needed.
