### ISSUE TITLE
Such a shit ui element

### ISSUE THREAD

**Issue by gwiesner** [microsoft/microsoft-ui-xaml#2306]
The user expects the back button to navigate to the previous location in the app's navigation history...
Except they dont. In fact they probably won't even see it when their focus is on toolbar in opposite corner....

**Comment by robloo** [comment]
The back button is handled on a per-app basis. It can part of the titlebar, in the NavigationView or a custom button within the app. To approach this we will need a lot more details such as which app or control and screenshots would be helpful.

The title is also against the code of conduct guidelines so I suggest you change it if you don't want this closed immediately. We've all been frustrated at one point or another, I get that. But we do have to be professional.
