### ISSUE TITLE
Question: Is there an Event that fires on reordering a TreeView?

### ISSUE THREAD

**Issue by Shad0wlife** [microsoft/microsoft-ui-xaml#2314]
I'm using a TreeView to display data from a database and the user is able to reorder elements (but not drag elements into new parents). I now want to be able to update the changed order in the database. I am currently exploring the possibility to either do so with every change or register that a change in order has been made to enable manually saving the new order later. Both would require that an event somehow notifies that such a change has happened. 
I cannot use `TreeView.DragItemsCompleted` for this purpose, as a drag operation implies a change of the Parent. I also attempted casting `TreeView.RootNodes` as `INotifyCollectionChanged` and subscribe to the `CollectionChanged` event, but the `IList` used does not implement `INotifyCollectionChanged` (`TreeView.RootNodes is INotifyCollectionChanged` fails).

I do not fill my Nodes with `TreeViewItems` and their `ItemsSouce`, but instead manually add `TreeViewNodes` to the `TreeView.RootNodes` and `TreeViewNode.Children` collections, so I can not just use `ObservableCollection`s as `ItemsSource` manually.

Does anyone know a workaround to register that the order has changed?

Edit: A quick check in [the TreeviewNode's code](https://github.com/microsoft/microsoft-ui-xaml/blob/v2.4.0-prerelease.200322001/dev/TreeView/TreeViewNode.cpp#L129-L138) shows that internally, such an event exists, at least at a node level. Sadly, TreeViewNode does not actually expose it.

**Comment by ranjeshj** [comment]
@Shad0wlife The way to achieve this would be through the INotifyCollectionChanged on the ItemsSource. Is there a reason you are not using the ItemsSource with an ObservableCollection ?

**Comment by Shad0wlife** [comment]
To be honest: because I followed [this tutorial](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view#fill-a-node-when-its-expanding) as it seemed fitting to my use case. 
I also use a class derived from TreeViewNode, not the supplied class itself because I have every node hold a cancellationtoken for prematurely cancelling the population if the node is closed before fully expanded. I slowly add the elements because adding hundreds at once causes freezes of the UI because layouting is takes too long (according to my profiling results).

I am not certain whether I can put my data in an ItemsSouce instead, I will try and see if I can split my program logic that way. In theory I could add a ItemsSource to the enclosed TreeViewItem on expanding a node manually easy enough. But doing so automatically creates the children nodes and items for the items in the collection and I can't make the nodes be of a derived class then. I might be able to put wrapper classes around my data to carry the information I previously carried in the node. 

But since I still need to add the data from code and not in xaml, can I just do an assignment like `TreeViewItem.ItemsSouce = new ObservableCollection<T>()`, or do I have to create a Binding in code for it?

**Comment by ranjeshj** [comment]
I see. @predavid as FYI.
You should be able to assign ItemsSource from code.

**Comment by Shad0wlife** [comment]
Ok, I have now modified my sourcecode to use ItemsSouce and managed to x:Bind them in the DataTemplate. It works nicely, but as soon as I want to drag and drop move an Item (CanDragItems is false, CanReorderItems is true), the program now crashes with an InvalidCastException telling me an Interface is not supported and the Data contains something about System.Collections.ListDictionaryInternal.
Sadly, the Exception has no Stacktrace, just that message, no Info about what Interface is not supported.

All I can say is that when still directly managing the TreeViewNodes, I could reorder the elements just fine. Should I use another Collection instead of ObservableCollection for the ItemsSource? (Just tested: a List causes the same crash to happen). Or is this an Issue with using an ItemTemplateSelector and different ItemTemplates for different Item subtypes?

**Comment by ranjeshj** [comment]
@Shad0wlife  Yes. Please file an issue for the crash and provide the repro app.
