### ISSUE TITLE
Possible regression: NavigationView.ItemInvoked raised before selected item is updated

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2315]
With the last few pre release versions of WinUI, starting with 2.4.0-prerelease.200113001, ItemInvoked get's raised before the actual selection has changed, that is the selected item is out of sync when checking in ItemInvoked. In versions prior to 2.4.0-prerelease.200113001, the selected item was set before ItemInvoked was raised. Is this breaking change intentional?

**Comment by ranjeshj** [comment]
It is likely not intentional but @anawishnoff @ojhad can confirm.

**Comment by StephenLPeters** [comment]
I think this needs to be fixed.. @chingucoding would you like to look into it?

**Comment by chingucoding** [comment]
Sure, if that behavior is not wanted, I will gladly fix this.

**Comment by ojhad** [comment]
> It is likely not intentional but @anawishnoff @ojhad can confirm.

Yep, this behavior should be fixed.
