### ISSUE TITLE
Bug: Combo box is empty when minimize window and hover on app in taskbar

### ISSUE THREAD

**Issue by ivayle** [microsoft/microsoft-ui-xaml#2322]
**Describe the bug**
It seems that combo box goes to some soft of intermittent state and loses its selected item, before the app window is actually restored from minimized state.

**Steps to reproduce the bug**

1. Create an empty UWP app
2. Create a combo box with a 3 items and set selected index to 0

```
        <ComboBox SelectedIndex="0">
            <ComboBoxItem Content="Item1" />
            <ComboBoxItem Content="Item2" />
            <ComboBoxItem Content="Item3" />
        </ComboBox>
```

3. Run the application
4. Open the combo box
5. Minimize the main window (without closing the opened combo box)
6. Hover the mouse over the app icon in taskbar

**Expected behavior**
Combo box's selected item is visible

**Screenshots**
![combo-box-is-emtpy](https://user-images.githubusercontent.com/4266678/79976363-23019d00-84a5-11ea-88c8-7e51286c284e.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
Selection seems to be gone. Even after maximizing again, the selection is empty. Looks like the flyout is forcefully closed and the control is missing this case.
