### ISSUE TITLE
Proposal: Support WinUI in VSIX

### ISSUE THREAD

**Issue by eluchsinger** [microsoft/microsoft-ui-xaml#2335]
# Proposal: Support WinUI in VSIX

## Summary

Use WinUI to build Visual Studio extensions with a new, modern look.

## Open Questions

One of the drawbacks to this proposal is that extensions will be able to look off compared with the current Visual Studio design, but I think believe that to be up to the developer of the extension.

**Comment by huoyaoyuan** [comment]
I wonder if Visual Studio itself can be rewritten in WinUI. It should be a big project.

**Comment by ranjeshj** [comment]
@Austin-Lamb @marb2000 Is it possible to host WinUI3 inside an extension for Visual Studio (given that Visual Studio is WPF)

**Comment by Austin-Lamb** [comment]
@ranjeshj - I don't know what VS extensibility supports, but I believe that at least some parts of the extensibility story rely on WPF (at least, some extensibility interfaces begin with "IWpf."

Recommend we move this ticket to the Visual Studio team's feedback system.

**Comment by marb2000** [comment]
Agreed. Please, move this to Visual Studio team.

**Comment by ranjeshj** [comment]
@eluchsinger  could you please file the issue through VisualStudio's "Help/Send Feedback/Suggest a Feature" ?

**Comment by weitzhandler** [comment]
https://developercommunity.visualstudio.com/t/Enable-writing-Visual-Studio-extensions/10239615
