### ISSUE TITLE
Live Visual Tree still shows TreeViewItems after collapsing parent node

### ISSUE THREAD

**Issue by carmineos** [microsoft/microsoft-ui-xaml#2337]
**Describe the bug**

Sometimes Live Visual Tree still shows children TreeViewItems after collapsing parent node, I notice this happens when having nested TreeViewItems and you first collapse a more nested node and then its parent (or higher level).

**Steps to reproduce the bug**

1. Create a TreeView with some levels of nested nodes
2. Collapse a nested node first
3. Collapse parent (or parent of parent and so on..) node of the previously collapsed one
4. Now some children TreeViewItems of the first collapsed node (at step 2) will show in the TreeView according to Live Visual Tree

**Expected behavior**

If I collapse directly the parent node (so if we skip step 2) according to Live Visual Tree the TreeView behaviour seems correct, as it will only contain TreeViewItems which are currently visible. Isn't supposed to be always like this?

**Screenshots**

**Version Info**

NuGet package version: `Microsoft.UI.Xaml 2.4.0-prerelease.200422001`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@carmineos Are these elements only in the live visual tree and don't show in the view ? Do they have a size, position on screen ? I would expect this to be the same as what happens in ListView when items are removed from the list.

**Comment by carmineos** [comment]
Yes rhey don't show in the view, I've recorded a small clip with Xaml-Control-Gallery to show what I mean.
https://streamable.com/75640d
