### ISSUE TITLE
TreeViewItem wrong chevron GlyphOpacity when using HasUnrealizedChildren

### ISSUE THREAD

**Issue by carmineos** [microsoft/microsoft-ui-xaml#2338]
**Describe the bug**

When binding TreeViewItem.HasUnrealizedChildren to a view model property sometimes the chevron `GlyphOpacity` is wrong, it has opacity 0 even if `HasUnrealizedChildren` is true while it's 1 even if `HasUnrealizedChildren` is false. In the first case chevron area will still be clickable. 
It often happens after that after collapsing a node and clearing the `ItemsSource` binded collection, the chevron `GlyphOpacity` will set to 0, even if `HasUnrealizedChildren` binded property is still true.

**Expected behavior**

Is TreeViewItem.HasUnrealizedChildren meant to be used to show the chevron glyph even if TreeViewItem.Children is empty? (In case I want to load children on expanding, and clear collection on collapsing)
If yes, then:
GlyphOpacity for the chevron should always 1 if HasUnrealizedChildren is true and 0 if HasUnrealizedChildren is false if the property is binded.

**Screenshots**

**Version Info**

NuGet package version: `Microsoft.UI.Xaml 2.4.0-prerelease.200422001`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
We only want to hide the glyph if Children is empty and HasUnrealizedChildren is false. @predavid does that sound reasonable ?
