### ISSUE TITLE
ItemsRepeater - NotImplementedException while moving an item inside an ObservableCollection bound to ItemsRepeater

### ISSUE THREAD

**Issue by ldocquir** [microsoft/microsoft-ui-xaml#2339]
**Describe the bug**
My app uses ItemsRepeater to display a list of tasks. The list is an ObservableCollection<> bound to the control using the ItemsSource property. Adding, Inserting or Deleting items in the collection works just fine: the ItemsRepeater refreshes the UI to reflect the changes. But moving an Item position using the **Move method on ObservableCollection<> raises a NotImplemented Exception**.

**Steps to reproduce the bug**
I created a small sample app that reproduces the bug. Can be found here: https://github.com/ldocquir/Repros/tree/master/ItemsRepeaterMove

**Expected behavior**
I expect the ItemsRepeater to detect the move operation inside the collection and refresh the UI to reflect new items positions.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I also tried Microsoft.UI.Xaml 2.4.0-prerelease.200422001 without success

**Comment by ranjeshj** [comment]
Looks like it is indeed not implemented - code [here](https://github.com/microsoft/microsoft-ui-xaml/blob/ca95be6f5248eaa55ec523f2d6e7b50f6e0d53e7/dev/Repeater/ElementManager.cpp#L316). You can workaround by removing and adding the item to workaround.

**Comment by ldocquir** [comment]
Hi ranjeshj,

Thanks for your reply.

In my repro app, your proposed workaround is already implemented but I feel it is a sub-optimal solution. In my use case I want to have my list synchronized with a local SQLite database, I planned to rely on the data source notifications to trigger DB updates. Removing and inserting an element will result in a record being deleted and then re-inserted which is a burden and a waste. 

Moreover the [ItemsRepeater documentation](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater#configure-the-data-source) states that it is supposed to be working. It is mentionned that move operations are not supported with data sources that implement IObservableVector. It further says that if move operations are required, one should use a data source that implements INotifyCollectionChanged like ObservableCollection\<T\>... which is obviously not the case!

This excerpt from the documentation led me to believe that it was more a bug than an intentionally not implemented feature.

**Comment by ranjeshj** [comment]
@ldocquir Thanks for the context. This is specific to the layouts (not a repeater thing if I am correct). I agree that this is a bug. Would you like to contribute a fix ? This specific case would be similar in the ElementManager, call OnItemsRemoved and OnItemsAdded with the correct indices. My guess is that ElementManager was coded before we supported INotifyCollectionChanged which brought the move API.

**Comment by ldocquir** [comment]
@ranjeshj I'm willing to contribute. I'll take a look at the code. I'll be working on this on my spare time as it is related to a side projet.
