### ISSUE TITLE
Whitespace in Nuget file causes build to fail on Mac

### ISSUE THREAD

**Issue by jlf0dev** [microsoft/microsoft-ui-xaml#2343]
**Describe the bug**

I am building a Xamarin application that has iOS, Android, and UWP versions. I also have a shared library for all my views that has the Microsoft.UI.Xaml nuget package. When I attempt to build my solution on a Mac, whitespace in the Microsoft.UI.Xaml.Props file causes errors.
**Steps to reproduce the bug**

1. Create a new xamarin project.
2. Make sure Microsoft.UI.Xaml nuget package is installed on all projects except .iOS and .Android.
3. Try to build this new project on a mac or apple computer. We are using XCode 11.3.1 with VS 8.4.6.
4. See error "Text content is not allowed inside a Project element /Users/dev/.nuget/packages/microsoft.ui.xaml/2.3.191129002/buildTransitive/Microsoft.UI.Xaml.props"

**Expected behavior**

Build should finish successfully
**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.2.190830001 and greater

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

I believe its any whitespace thats causing the issue, including the extra spaces between lines, but also down at the bottom in the Targets there is some weird spaces before lines.  I've included a file i've edited to work on the build machine. Obviously I can't just use this one because it will be refreshed with the other Nuget packages. 
[Microsoft.UI.Xaml.props.txt](https://github.com/microsoft/microsoft-ui-xaml/files/4541717/Microsoft.UI.Xaml.props.txt)

**Comment by ranjeshj** [comment]
@jlf0dev would you like to contribute a fix ?

**Comment by jlf0dev** [comment]
Created new fix for this: [#2351](https://github.com/microsoft/microsoft-ui-xaml/pull/2351)
