### ISSUE TITLE
Proposal: Add lightweight styling resource(s) for TabView's Separator

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2344]
# Proposal: Add lightweight styling resource(s) for TabView's Separator

## Summary
Currently, the margin of the TabView's Separator cannot be easily modified:

```xml
<Border x:Name="TabSeparator"
      HorizontalAlignment="Right"
      Width="1"
      BorderBrush="{ThemeResource TabViewItemSeparator}"
      BorderThickness="1"
      Margin="0,6,0,6"/>
```

This proposal would expose this value via a resource to enable easy styling. Proposed resources:
* TabViewItemSeparatorMargin

This will enable TabView's item separator to be styled like Edge UWP's TabView separator, for example:

![image](https://user-images.githubusercontent.com/1398851/80423024-7ded2700-88df-11ea-96c0-d2ebd4a32bf6.png)

Edge UWP:
![image](https://user-images.githubusercontent.com/1398851/80423126-b55bd380-88df-11ea-958b-7d6b52b9d183.png)

## Open Questions
Should we also expose the width of the separator as a resource? On first glance, this could create issues with the shadow casting and tab item layout in general (i.e. overlaying the casted shadow on the left & shrinking the space between the close button of the previous tab and the beginning of the next tab).

## Additional Context
If approved, I would look like to work on this.

**Comment by Felix-Dev** [comment]
@stmoy Your thoughts on this?

**Comment by mdtauk** [comment]
This should be worked into this proposal I think. #2587

**Comment by stmoy** [comment]
> This should be worked into this proposal I think. #2587

Depends. @Felix-Dev, is the motivation for this work to make the TabView look more like the one from Windows Community Toolkit? If so, agree that this should probably be bundled alongside #2587.

However, I think having more customizable light-weight styling keys seems like a righteous thing in general. 

In terms of names, I'm conflicted about `TabViewSeparatorMargin`, as it really describes the height of the line, right? But I guess the height is determined by a `Margin` so, maybe the name is appropriate.

**Comment by Felix-Dev** [comment]
@stmoy The motivation for this proposal is to make styling the TabView (here: the TabViewItemSeparator) as easy as possible for developers without having to retemplate the control. This light-weight styling key *could* be used to create a TabView UI matching the Community Toolkit's TabView look but *it doesn't have to*. Developers/Designers can just pick any margin for the TabViewItemSeparator they favor.

> In terms of names, I'm conflicted about TabViewSeparatorMargin, as it really describes the height of the line, right? But I guess the height is determined by a Margin so, maybe the name is appropriate.

The proposed theme resource works on the Margin property of the TabViewItemSeparator. It can be used to control the height of the separator but since it sets a *margin*, on paper not only the height can bet set but also the position of the separator in relation to the surrounding TabViewItems. As such, I find it proper to make this relationship clear in the naming of the theme resource - you can modify the separator's margin and not just strictly its height.

**Comment by mdtauk** [comment]
> > This should be worked into this proposal I think. #2587
> 
> Depends. @Felix-Dev, is the motivation for this work to make the TabView look more like the one from Windows Community Toolkit? If so, agree that this should probably be bundled alongside #2587.
> 
> However, I think having more customizable light-weight styling keys seems like a righteous thing in general.
> 
> In terms of names, I'm conflicted about `TabViewSeparatorMargin`, as it really describes the height of the line, right? But I guess the height is determined by a `Margin` so, maybe the name is appropriate.

I was thinking more about how @chingucoding  would be able to apply a style to the TabView control, which would allow him to change the separator style between both Edge and Legacy Edge styles.
