### ISSUE TITLE
Proposal/Question: Add Tooltips to TabView's scroll buttons

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2345]
# Proposal/Question: Add Tooltips to TabView's scroll buttons

This is more a question than a proposal as of now:

Edge UWP's TabView scroll buttons have Tooltips describing their functionality:
![image](https://user-images.githubusercontent.com/1398851/80423984-28197e80-88e1-11ea-990c-feeab6292826.png) ![image](https://user-images.githubusercontent.com/1398851/80423938-1a63f900-88e1-11ea-86fc-f98b5c89fb7e.png)

Should we also add those Tooltips to WinUI's TabView?

Based on some quick testing, Firefox' tab scroll buttons don't have tooltips. For Edgium, I could not get these buttons to show up at all (tabs just got smaller and smaller until I could create no more tabs).

**Comment by ranjeshj** [comment]
@stmoy This sounds like a reasonable request...

**Comment by stmoy** [comment]
Seems reasonable to me too. We'll need to make sure that the strings are localized, but this otherwise seems straightforward.

**Comment by Felix-Dev** [comment]
@stmoy I would like to work on this then. I would follow the precedence set in my PR https://github.com/microsoft/microsoft-ui-xaml/pull/2022 where I only had to create the resources for US English with the localizations added to WinUI in a later [PR](https://github.com/microsoft/microsoft-ui-xaml/pull/2093) by the team.
