### ISSUE TITLE
Positions reported by Manipulation_Delta are not correct

### ISSUE THREAD

**Issue by tonuv** [microsoft/microsoft-ui-xaml#2346]
**Describe the bug**
In using WinUI 3 the positions reported by the ManipulationDelta event seem to be scaled by a factor compared to real world. The same code compiled with Windows.UI references works perfectly

**Steps to reproduce the bug**
1. Create a WinUI3 C# application

Use this XAML:
    <Grid>
        <Path x:Name="theCircle" Fill="Red" ManipulationMode="TranslateX,TranslateY" ManipulationStarted="Path_ManipulationStarted" ManipulationDelta="Path_ManipulationDelta">
            <Path.RenderTransform>
                <CompositeTransform TranslateX="200" TranslateY="200"></CompositeTransform>
            </Path.RenderTransform>
            <Path.Data>
                <EllipseGeometry RadiusX="100" RadiusY="100"></EllipseGeometry>
            </Path.Data>
        </Path>
    </Grid>

and these event handlers:

        Point _startingPoint;

        private void Path_ManipulationStarted(object sender, Microsoft.UI.Xaml.Input.ManipulationStartedRoutedEventArgs e)
        {
            var transform = ((sender as Path).RenderTransform as CompositeTransform);
            _startingPoint = new Point(transform.TranslateX, transform.TranslateY);
        }

        private void Path_ManipulationDelta(object sender, Microsoft.UI.Xaml.Input.ManipulationDeltaRoutedEventArgs e)
        {
            var transform = ((sender as Path).RenderTransform as CompositeTransform);
            transform.TranslateX = _startingPoint.X + e.Cumulative.Translation.X;
            transform.TranslateY = _startingPoint.Y + e.Cumulative.Translation.Y;
        }

**Expected behavior**
When you run the app, you should be able to drag the circle with mouse. However the circle moves less that mouse movements. Compiling this code referencing Windows.UI gives correct behaviour

**Screenshots**

**Version Info**
WinUI: 3.0.0-alpha.200210.0

NuGet package version: 
3.0.0-alpha.200210.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

This bug was reproed on Surface book at 200% scale. 

**Additional context**

**Comment by tonuv** [comment]
`    <Grid>
        <Path x:Name="theCircle" Fill="Red" ManipulationMode="TranslateX,TranslateY" ManipulationStarted="Path_ManipulationStarted" ManipulationDelta="Path_ManipulationDelta">
            <Path.RenderTransform>
                <CompositeTransform TranslateX="200" TranslateY="200"></CompositeTransform>
            </Path.RenderTransform>
            <Path.Data>
                <EllipseGeometry RadiusX="100" RadiusY="100"></EllipseGeometry>
            </Path.Data>
        </Path>
    </Grid>`

**Comment by ranjeshj** [comment]
@gegao18 as FYI

**Comment by michael-hawker** [comment]
There's more details in #7221 related to this issue, I'm not sure why this was closed if it's still an issue?

**Comment by JJBrychell** [comment]
Sorry, this and 7221 are duplicates and two different people closed them as dups of the other.  I chose to keep this one because it was filed earlier.

**Comment by JJBrychell** [comment]
This appears to be fixed in 1.3 as I am unable to repro it.  There were a number of scale issues early on but most of those have been fixed.  If you can repro this on 1.3 or later, feel free to reopen.
