### ISSUE TITLE
Proposal: Add feature to set NavigationView's background in xaml directly instead of editing app resources.

### ISSUE THREAD

**Issue by imthewiseguy** [microsoft/microsoft-ui-xaml#235]
# Proposal: Add feature to set NavigationView's background in xaml directly instead of editing app resources.

## Summary

instead of going to the app/pages resources and editing the "DefaultPaneBackground", "TopPaneBackground', and "ExpnandedPaneBackground", the user should be able to create a NavigationView in xaml and directly edit it's Pane Backgrounds.
## Rationale

It would save a lot of time and would be a lot easier.

## Important Notes

example xaml: `<NavigationView AlwaysShowHeader="False" IsBackButtonVisible="Collapsed" DefaultPaneBackground="{ThemeResource SystemControlAcrylicElementBrush}" TopPaneBackground="{ThemeResource SystemControlAcrylicElementBrush}" ExpandedPaneBackground="{ThemeResource SystemControlAcrylicWindowBrush}">`

**Comment by jevansaks** [comment]
Having strongly typed properties available would be really nice for intellisense and developer experience. @kikisaints this is related to another proposal you were working on, I think?

**Comment by mdtauk** [comment]
I would prefer to have all properties accessible from XAML without having to override styles - but I can understand the reasoning for not doing that, means you are further separating the presentation and UI of the control, from the logic and code of that control.

**Comment by dimOk00** [comment]
Maybe add something like in SplitView?

**Comment by kikisaints** [comment]
Adding a property to change colors or edit styling values kind of goes against our general styling model of having resources and style tags where all your visual information is held. 

Thurs, I'm going to close this one - however if you feel strongly that this is something we should do, please re-open the issue with more scenarios supporting why properties would be better to have versus resources.

Thank you!
