### ISSUE TITLE
UWP selected item is not focused/highlighted in masterdetailview

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2352]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1000691/uwp-selected-item-is-not-focusedhighlighted-in-mas.html)._

---
<p>I am setting the selecteditem of masterdetailview programmatically but item is not highlighted.
In MasterDetailView i gave selecteditem as a binding property whose mode is TwoWay, When I set this binding property from code behind the detailcontrol is displayed but item in master panel is not highlighted</p>

---
#### Visual Studio Feedback System on 4/21/2020, 07:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by michael-hawker** [comment]
Thanks @ranjeshj, I commented on the VS forum about filing an issue on our repo instead with a bit more detail. You can close this issue here.
