### ISSUE TITLE
NumberBox Header Missing in WinUI 2.4

### ISSUE THREAD

**Issue by stmoy** [microsoft/microsoft-ui-xaml#2367]
**Describe the bug**

The NumberBox samples in the Gallery use `Header` to provide context about the NumberBox. This used to work, but as of WinUI 2.4, the Headers seem to be missing.

**Steps to reproduce the bug**

1. Go to NumberBox page in the Xaml Controls Gallery
2. Notice the missing headers

**Expected behavior**

This is the version of the Gallery from the store. Note the headers:

![image](https://user-images.githubusercontent.com/25991996/80826597-6049e700-8b97-11ea-8587-5183adda5be5.png)

**Screenshots**

This is the version of the Gallery built from `master` branch. Note the missing headers:

![image](https://user-images.githubusercontent.com/25991996/80826494-31337580-8b97-11ea-82d6-b900c3d6f39b.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment]
I will look into this this evening.

**Comment by stmoy** [comment]
Looks like this has actually been fixed already with this change: https://github.com/microsoft/microsoft-ui-xaml/commit/41c7fa3ea98e5df218fcbb559e43fb9b4633431b

The master version of the Gallery hasn't been updated to the latest 2.4 package yet, but I confirmed this issue is fixed on the latest package.

**Comment by chingucoding** [comment]
Oh right, you are right.
