### ISSUE TITLE
C++ example code is where?

### ISSUE THREAD

**Issue by rjewell999** [microsoft/microsoft-ui-xaml#2370]
I would like to copy pixel data into a SoftwareBitmap and the simple task seems almost impossible. After a lot of reading I am searching for C++ sample code relating to WriteableBitmap.PixelBuffer. The page and various discussions online talk about C++/WinRT solutions (example code) but I can't find them. Could you add links to the page to the code examples?

**Comment by ranjeshj** [comment]
Are you looking for C++ winrt samples ? Is this what you are looking for ?
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/
