### ISSUE TITLE
Support for webcam eye tracking 

### ISSUE THREAD

**Issue by jhanna** [microsoft/microsoft-ui-xaml#2371]
Why is this just being restricted to hardware eye trackers?
xLabsgaze.com is the worlds leading webcam based eye and gaze tracking software solution. Since 2014 over 1.8m eye tracking sessions have been commercially successful with billions of data points driving  continuous improvements to the ML Lagos. 
It’s proprietary. Runs really time interactive on device. And is comparable performance with hardware based solutions

**Comment by StephenLPeters** [comment]
@SavoySchuler or @ryandemopoulos do either of you know where we could route this?

@jevansaks maybe you know the owners?

**Comment by JayBeavers** [comment]
Hi jhanna, eye tracking in Windows isn't restricted to hardware eye trackers, though it was certainly designed with them in mind as it's based on receiving input from a USB HID specialty class device.  Why was it designed that way?  At the time this work started, webcam based eye trackers simply didn't exist in any meaningful form.

You can implement a HID driver that meets the specification requirements in software and I've seen two prototype webcam eye trackers that have done this.  If you work for xLabsgaze, drop me a line at jay.beavers@microsoft.com and I will get you connected with the right people to help you understand how to make this work.

 - Jay
