### ISSUE TITLE
Strange behavior of TreeView control

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#2375]
**Describe the bug**

Suppose there is a folder named "test" and its subfolder "NewFolder"
![image](https://user-images.githubusercontent.com/42038175/80908733-f6773c00-8d54-11ea-9047-d36d50504705.png)

When I remove the "NewFolder" folder, the following code is executed
```csharp
Node.Children.Remove(RemoveNode)
```

Now the HasUnrealizedChildren property of the “test” folder is false
Therefore, the small arrow on the left should not be displayed, like this
![image](https://user-images.githubusercontent.com/42038175/80908832-cf6d3a00-8d55-11ea-8e9a-f9a1ffd21047.png)

The icon on the left shows the "folder opened" icon, which is caused by the IsExpanded property failing to automatically become false

However, when I manually set the IsExpanded property to false, the small arrow on the left appeared again, but the HasUnrealizedChildren property was still false, like this:

![image](https://user-images.githubusercontent.com/42038175/80908989-fbd58600-8d56-11ea-8064-9b6833d834b6.png)

![无标题](https://user-images.githubusercontent.com/42038175/80908980-e95b4c80-8d56-11ea-97f6-57291fc523bb.png)

**Steps to reproduce the bug**

1. Create a folder with subfolders, like “test” and “NewFolder” mentioned above
2. Remove all subfolders
3. Set IsExpanded = false

**Expected behavior**

Without small arrow on the left

**Screenshots**

**Version Info**

NuGet package version: 
2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
TreeView is indeed a bad control with many bugs!

**Comment by StephenLPeters** [comment]
@predavid fyi

**Comment by StephenLPeters** [comment]
@zhuxb711 if you reverse the order that you perform these repro steps in do you get the same result? for instance, set the isExpanded property to false and then remove the last child.

**Comment by zhuxb711** [comment]
@StephenLPeters I have reversed the order

> Set IsExpanded=false and then remove the last child

But although this TreeViewNode has no child nodes, it still shows the small arrow on the left

**Comment by StephenLPeters** [comment]
Okay thanks that is good info. So we know how to prioritize fixing this with all the work we are doing for WinUI 3.0, is this a blocking issue for you? Have you been able to find a work around?

**Comment by zhuxb711** [comment]
@StephenLPeters
There is no solution for the time being, all I can do is to set HasUnrealizedChildren=false instead of IsExpanded = false after removing the last child node

Does this bug require WinUI3 to be fixed?
