### ISSUE TITLE
Navigation View Scrollbar

### ISSUE THREAD

**Issue by rasyidf** [microsoft/microsoft-ui-xaml#2376]
**Describe the bug**
When opening XAML Control Gallery with my small resolution (mine is 1366x768), the navigation menu item overlapped by the scrollbar when It's in compact mode.

**Steps to reproduce the bug**
1. Disable *Setting > Ease of Access > Automatically Hide Scrollbar in Windows*
2. Open Xaml Control Gallery (or Windows Security)
3. Resize to smaller view.
3. Notice the scrollbar overlapping the NavigationMenuItems

**Expected behavior**
when the navigation menus exceeding the height, should the scroll bar is not shown, instead, show some overflow button. 

**Screenshots**
This is Windows Security Settings, 
![image](https://user-images.githubusercontent.com/28984914/80927640-468fe600-8dc9-11ea-8164-a05f9aad5c02.png)

XAML Control Gallery
![image](https://user-images.githubusercontent.com/28984914/80927529-9a4dff80-8dc8-11ea-867c-9408f99d8cfd.png)
 

**Version Info**
NuGet package version: 

Microsoft.UI.Xaml 2.4.0-prerelease.200422001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19619)              |  Yes   |
| November 2019 Update (18363)  |     |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by shaheedmalik** [comment]
This has been marked already.

**Comment by shaheedmalik** [comment]
#1742

**Comment by rasyidf** [comment]
then, it's a duplicate.

**Comment by Felix-Dev** [comment]
@rasydif 
To my understanding this is "fixed" in the sense that an app developer can now use the the [CompactPaneLength](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.navigationview.compactpanelength?view=winui-2.3)  API of the NavigationView to set an increased compact pane width if required. 

The WinUI team opted for this per-app approach instead of a global change approach as reasoned [here](https://github.com/microsoft/microsoft-ui-xaml/issues/1742#issuecomment-563390861)

**Comment by rasyidf** [comment]
Okay, so this is not an issue anymore, thank you.

**Comment by Felix-Dev** [comment]
I presume this issue can be closed then? Please do so if you agree. Thanks 🙂

**Comment by Noemata** [comment]
With 2.5 I see this:

![image](https://user-images.githubusercontent.com/6632315/101835951-8d398180-3b0a-11eb-92ed-413647172cfb.png)

All I did was set IsSettingsVisible="True", with nothing in the PaneFooter.

If I place markup in my PaneFooter to work around this issue (this previously worked), somehow my button is occluded and does not receive any events.

Note: this markup no longer works!!!

```
            <ui:NavigationView.PaneFooter>
                <StackPanel Margin="0,0,0,-30" >
                    <Rectangle Height="1" HorizontalAlignment="Stretch" Fill="Gray" Margin="0,0,1,0" />

                    <StackPanel Orientation="Horizontal" Margin="0,0,0,0">
                        <ToggleButton Style="{StaticResource ToggleButtonStyle}" cm:Message.Attach="[Event Click] = [Action ShowSetup()]" >
                            <FontIcon Glyph="&#xE115;"/>
                        </ToggleButton>
                        <TextBlock Text="Setup" VerticalAlignment="Center" Margin="8,0,0,0" />
                    </StackPanel>
                </StackPanel>
            </ui:NavigationView.PaneFooter>
```

It's a real drag that we go through so many breaking changes.  A test suite should be provided for some of these components so they can be regression tested properly.

Please restore the ability to have custom markup for the setup button.
