### ISSUE TITLE
The SwipeControl control will prevent dragging of the GridViewItem when using touch screen

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#2379]
**Describe the bug**

If there is no SwipeControl in the GridView DataTemplate, you can drag the GridViewItem completely normally

However, if there is a SwipeControl in it, it will get stuck when dragging the GridViewItem using the touch screen, and all drag related events will not be raised

**Steps to reproduce the bug**

1. Use touch screen
2. Insert SwipeControl to DataTemplate
3. Drag "GridViewItem" in GridView
4. It will get stuck

**Expected behavior**

Drag normally

**Screenshots**

**Version Info**

NuGet package version: 

2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@zhuxb711 The swipe is interfering with drag and drop gesture. I think this is by design. I don't see an easy way to get swipe and dragging working they way you are proposing.
