### ISSUE TITLE
[WinUI3] Microsoft.UI.Xaml.Thickness is missing methods

### ISSUE THREAD

**Issue by jeromelaban** [microsoft/microsoft-ui-xaml#2387]
**Describe the bug**
The `Microsoft.UI.Xaml.Thickness` only has properties when used from C#.

Other types have similar characteristics, such `Matrix` and `GridLength`, though `GridLengthHelper.FromValueAndType` exists.

**Expected behavior**
The `Thickness` type should have a constructor, and equality members, this is not something that is easily extensible.

If it's not possible/easy to add, could the `ThicknessHelper` be improved ?

**Version Info**
3.0.0-alpha.200210.0

**Comment by ranjeshj** [comment]
@MikeHillberg @Austin-Lamb @fabiant3 I was sure this was documented and tracked somewhere but I'm having trouble finding it. If not we can use this issue to track value types usage.

**Comment by JeanRoca** [comment]
Hey @jeromelaban thank you for filing this bug. This is currently fixed for WinUI 3 in Desktop and will be fixed for UWP once we move to .NET 5.
