### ISSUE TITLE
Add EffectiveViewportChanged event listener will break down the app while the control hosting under the Viewbox control

### ISSUE THREAD

**Issue by h82258652** [microsoft/microsoft-ui-xaml#2389]
**Describe the bug**

Add a control under the ```Viewbox``` control and add ```EffectiveViewportChanged``` event listener to the control. Run the app and the app crashed.

**Steps to reproduce the bug**

1. Add a control under the ```Viewbox``` control.
2. Add ```EffectiveViewportChanged``` event listener to the control.
3. Run the app.
4. The app crashed.

**Expected behavior**

The app should not be crashed.

**Version Info**

Windows 10 Home 18362.778
18362 SDK

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |  Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

The source code is here: https://github.com/h82258652/UwpViewboxChildEffectiveViewportChangedBugRepo

**Comment by codendone** [comment]
Thanks for providing a repro!

During the EffectiveViewport walk, the Viewbox has scale=0, so the Image with the EffectiveViewportChanged handler can't invert the transform matrix and crashes using a null transform. This is definitely a bug.

Here is the top of the stack:
```
Windows_UI_Xaml!CGeneralTransform::TransformRect
Windows_UI_Xaml!CUIElement::TransformToElementCoordinateSpaceThroughViewports
Windows_UI_Xaml!CUIElement::ComputeEffectiveViewportChangedEventArgsAndNotifyLayoutManager
Windows_UI_Xaml!CUIElement::EffectiveViewportWalk
...
Windows_UI_Xaml!CLayoutManager::UpdateLayout
```
