### ISSUE TITLE
Tests on RS3 sometimes fail due to appx installation error: "The Visual Elements extension failed while processing the Notification element."

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#239]
E.g. see CommandBarFlyoutTests failure in:

https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=1884&view=ms.vss-test-web.build-test-results-tab

**Comment by kmahone** [comment]
I'm not seeing this in recent test passes. If this issue occurs again we can try can get logs.

**Comment by jevansaks** [comment]
Just saw this here: https://github.com/Microsoft/microsoft-ui-xaml/pull/412/checks?check_run_id=77188765

**Comment by kmahone** [comment]
This hasn't been an issue lately. Without a way to repro the issue there is not much we can do. Let's see if it comes up again.
