### ISSUE TITLE
WinUI SplitView Right Placement CompactInline DisplayMode  behaves differs to UWP SplitView

### ISSUE THREAD

**Issue by TheXamlGuy** [microsoft/microsoft-ui-xaml#2392]
The WinUI SplitView control Right Placement CompactInline  DisplayMode behaviour is different to those found in in the inbox version of the SplitView control. 

WinUI SplitView 

![1](https://user-images.githubusercontent.com/14894973/81166026-eba5ec80-8f8a-11ea-820e-ce54b77ce723.gif)

UWP SplitView

![2](https://user-images.githubusercontent.com/14894973/81166562-acc46680-8f8b-11ea-8139-142321f1b7ea.gif)

While we can note the lack of animation for Right Placement CompactInline DisplayMode in contrast to the animations that are available in Left Placement CompactInline DisplayMode in both controls, it can be noted that the WinUI Splitview Right Placement CompactInline DisplayMode is incorrectly closing and it does look as if it is closing to the Left within the Grid Column rather to the Right.

**Comment by ranjeshj** [comment]
@TheXamlGuy can you switch App1 to use the UWP SplitView (windows.ui.xaml.controls.splitview) and see if it has the same issue ? I'm wondering if the placement of the SplitView is causing the issue.

**Comment by chingucoding** [comment]
The problem here is the sample in the XAML controls gallery. If you open the pane, the SplitView will expand to show both the open pane and not occlude it's main content. If we set the width of the SplitView, it stops this behavior and only expands to the left when set to right placement.

**Comment by Fritierkelle** [comment]
Am i missing something?! I had to change the "value" from Lily's code as follows and now it works for me, if closing (From="OpenInlineRight" To="Closed"): 

`                                                    <DoubleAnimationUsingKeyFrames Storyboard.TargetName="PaneClipRectangleTransform" Storyboard.TargetProperty="TranslateX">
                                                        <SplineDoubleKeyFrame KeyTime="{StaticResource SplitViewPaneAnimationCloseDuration}" KeySpline="0.0,0.35 0.15,1.0" Value="{Binding TemplateSettings.NegativeOpenPaneLength, RelativeSource={RelativeSource Mode=TemplatedParent}}"/>
                                                    </DoubleAnimationUsingKeyFrames>`
