### ISSUE TITLE
Question: [Release note for WinUI 2.4.0]

### ISSUE THREAD

**Issue by katan-ms** [microsoft/microsoft-ui-xaml#2393]
There is a WinUI 2.4.0 package with no prerelease tag out on [nuget.org](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.4.0), but I cannot find any release note neither on this repo nor on msdn. And this build seems to cut a lot of new features like RecyclePool, SelectionModel and LayoutPanel. Is this expected?

**Comment by ranjeshj** [comment]
@katan-ms This is the 2.4 stable release package. It does not contain the preview types like RecyclePool and SelectionModel. The preview types ship only in the pre-release packages. The release notes will be out shortly. @predavid as FYI

**Comment by ranjeshj** [comment]
release notes are available now :) 

https://docs.microsoft.com/en-us/uwp/toolkits/winui/release-notes/winui-2.4
https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.4.0

**Comment by katan-ms** [comment]
Thanks ! I'll go check them out :D
