### ISSUE TITLE
XamlCompiler or GenXBF bug causes wrong index when Xaml parses the property

### ISSUE THREAD

**Issue by improbabilityphysics** [Microsoft/microsoft-ui-xaml#240]
**Describe the bug**

InteractionTests.SplitButtonTests
InteractionTests.SwipeControlTests.SwipeIsNotTabStop
InteractionTests.TreeViewTests.ExpandCollapseViaAutomationTest_NodeMode
randomly failed in RS3 desktop run when SDK updating to insider 18312.

**Steps to reproduce the bug**

1. Go to 'MUXControlsTestApp' on RS3 desktop VM with x86fre flavor
2. Click on 'SplitButtonTests' by holding mouse a little bit long and then letting it go

**Expected behavior**

App is expected to be crashed.

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18312)                   | Yes   |
| October 2018 Update (17763)   |  No    |
| April 2018 Update (17134)        |  No   |
| Fall Creators Update (16299)     |  No   |
| Creators Update (15063)           |  No   |
| Anniversary Update (14393)      |  No   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |  No  |
| Xbox                      |  No  |
| Surface Hub          |  No  |
| IoT                         | No  |

**Additional context**

The simple way to repro this is to find a master commit without AVP change and modify its RS5 number 17763 to 18312.

**Comment by jevansaks** [comment]
Filed [internal issue](https://microsoft.visualstudio.com/OS/_workitems/edit/20366248)

**Comment by licanhua** [comment]
need to revert change #245 when internal issue is resolved.

**Comment by jevansaks** [comment]
Fix will be available in an upcoming Windows SDK.
