### ISSUE TITLE
ProgressRing control does not work on Windows release 17134

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#2400]
**Describe the bug**

The new ProgressRing control does not work on older Windows releases like 17134. 

**Steps to reproduce the bug**

1. Use a ProgressRing control on Windows version 17134

**Expected behavior**

The progress ring should be shown. If this is not possible, the fact that this control is only supported on more recent Windows versions should be pointed out in the documentation.

**Screenshots**

**Version Info**

NuGet package version: 

WinUI 2.4

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@lhak Good point. @MarissaMatt can we please document this issue ? Lottie currently works only on RS5 and above. This will be resolved in WinUI3 when the platform is decoupled from the OS.
