### ISSUE TITLE
How does WinUI create the color pallette(?) for a given (accent) color and color mode (dark/light)?

### ISSUE THREAD

**Issue by SFM61319** [microsoft/microsoft-ui-xaml#2402]
[This noise PNG](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Materials/Acrylic/Assets/NoiseAsset_256X256_PNG.png "Acrylic Noise") doesn't look like the noise texture **actually** used in acrylic. It has an `alpha` of value (possibly) `1`, which means it is not the noise texture PNG used in the real `AcrylicBrush`.  
  
Please update the noise texture to the correct PNG to remove any (potential) errors/threats, as it could be misleading.  
Or at least make a `README.md` file that gives the correct `alpha` value for that PNG to be the same as the noise in acrylic.

**Comment by mdtauk** [comment]
Acrylic's noise texture actually has an alpha of 100%, but when it is layered onto the surface, that layer is set to 2%

**Comment by SFM61319** [comment]
Oh, thanks!

**Comment by SFM61319** [comment]
I have a few more doubts.  
1. If the blur radius is `30.0f` in `C++`, then how many `px` (pixels) is the blur radius (in `CSS`)? (I'm trying to learn to code in XAML and CS for UWPs and I would find it easier if I try it in `CSS`, as I know some `CSS`)
2. What is the background-size of the noise PNG used? (A small one would make no difference and a big one will increase the size of the noise texture which would be of no use to us)

**Comment by mdtauk** [comment]
CSS is very different from XAML.

The Background Noise file I believe is either 256x256 but is tiled, so it repeats and is layed over the surface it is applied to.

The Blur would be 30px.

There are various over layers that make the Acrylic effect though.

![image](https://user-images.githubusercontent.com/7389110/82066779-c66e5800-96c7-11ea-873f-b0269f11bdde.png)

This is how I do it for Mock Up designs
![image](https://user-images.githubusercontent.com/7389110/82067137-37ae0b00-96c8-11ea-815a-8f96c42bc0da.png)

In Figma Microsoft uses a 60px blur, but all other samples say 30, and that is what is in the code too

**Comment by SFM61319** [comment]
1. I know that the noise is tiled (because the noise image would be stretched or zoomed to fit if not tiled), but I don't know the scale value or the dimensions (other than 256x256) to which the noise is set (I think the noise PNG is resized to a smaller value because 256x256 doesn't look like the correct noise texture used in acrylic).  
  
2. At first, I too thought the blur would be `30px`, but when I used  
```css
.acrylic {
  background-image: url("/Assets/Noise_5%.png");  /* 2% was invisible */
  background-size: round auto;  /* Tiled noise */
  backdrop-filter: blur(30px) brightness(90%) saturate(112%);
  /*
   * brightness = Tint White + Exclusion White ≡ Luminosity blend
   * saturate = Saturation (R|G|B) + 100% ≡ Tint/Color blend
   */
}
```
The background looked way more blurry than acrylic. So I tried `blur(20px)` instead and the result was somewhat closer:  
***CSS***  
![delete1](https://user-images.githubusercontent.com/45308169/82078650-1c122700-96ff-11ea-8176-2d152498c6ec.png)
  
  
***Acrylic (Windows Terminal)***  
![delete](https://user-images.githubusercontent.com/45308169/82071929-66da7180-96f4-11ea-91a9-7875dbb87156.png)  
And the fact that `blur(20px)` looked more accurate than `blur(30px)` got me confused.  
  
3. Another reason why I used `5%` noise instead of `2%` noise is this:  
***Acrylic (Windows Terminal)***  
![delete_](https://user-images.githubusercontent.com/45308169/82083390-49fb6980-9707-11ea-9426-a6e3931bc293.png)

  
***CSS (Noise 2%)***  
![delete_1](https://user-images.githubusercontent.com/45308169/82082302-639bb180-9705-11ea-8fe6-342d2e5cf666.png)  
  
Notice the black area in [this image](https://user-images.githubusercontent.com/45308169/82083390-49fb6980-9707-11ea-9426-a6e3931bc293.png "Acrylic - Windows Terminal"). The noise PNG can be clearly seen in it. And in the [second image](https://user-images.githubusercontent.com/45308169/82082302-639bb180-9705-11ea-8fe6-342d2e5cf666.png "CSS - Noise 2%"), the noise can be barely seen and that too on the colored part only, meaning the tiled noise PNG is not a `256x256` image but something else, the same image with different dimensions. If the correct dimensions are known, we can resize the image and use an alpha of `2%` for the image, and then it would look exactly the same in both the pictures.

**Comment by mdtauk** [comment]
DPI scaling may be a factor.

The Noise asset is from the SDK, so is direct from Microsoft.

Originally the Noise was set to 5% but in the next versions after, Microsoft changed this value and introduced Saturation Boost and Luminosity layers.

**Comment by chingucoding** [comment]
@SFM61319 The thing with XAML rendering is that there is no such unit like PX in CSS. All measurements are done in "Pixels" which then are converted into DPI pixels/PPI which are aware of factors such as display scaling and screen size. So on my device 40 "pixel" would be the same size as on a device with a smaller or larger screen, because those units get scaled to ensure that text is readable etc.

**Comment by SFM61319** [comment]
Oh, thank you, @chingucoding! I have another question. Do you know like the conversion factor or value or the logic used in the saturation and brightness of Acrylic based on `acrylicOpacity` (i.e., the logic which uses `12%` saturation and `(80+10)%` luminosity when `acrylicOpacity` is `0` and a different value, which keeps on increasing or decreasing by a factor/value, for when the `acrylicOpacity` is `1`)?

**Comment by mdtauk** [comment]
There is something I was wondering @chingucoding 
Windows has traditionally used 96 dpi as it's 100% scaling value, unlike Adobe and Apple which uses 72dpi.  Does UWP Xaml use 96 or 72 (as the 100% scale factor)?

**Comment by SFM61319** [comment]
Hey @mdtauk, since you are online, can you please answer [this question](https://github.com/microsoft/microsoft-ui-xaml/issues/2402#issuecomment-631002457 "The one above your latest comment")?

**Comment by mdtauk** [comment]
> Hey @mdtauk, since you are online, can you please answer [this question](https://github.com/microsoft/microsoft-ui-xaml/issues/2402#issuecomment-631002457)?

I thought I had.  The Noise texture is tiled and set to a 2% opacity on top of the other layers that make up Acrylic

**Comment by SFM61319** [comment]
Oh no, that was not my question, @mdtauk. I was talking about saturation and luminosity for different acrylic opacities.  
It's ok if you don't know it, I just read you were not a Microsoft employee (I thought you were an employee the whole time)

**Comment by chingucoding** [comment]
@SFM61319 The source code for AcrylicBrush is available online.

The logic for determining the luminosity is the following:

https://github.com/microsoft/microsoft-ui-xaml/blob/6381f8207a29b20bd417c8b7202926e3ccffe8be/dev/Materials/Acrylic/AcrylicBrush.cpp#L414-L463

All logic done to calculate the correct colors can should be in that page, albeit a bit nested or "hidden".

@mdtauk I don't know what the default DPI value for UWP XAML is. I think it might still be 96, though the question itsself confuses me a bit. Doesn't DPI rely on your monitor size?

**Comment by SFM61319** [comment]
@chingucoding I already read the source code online, and I did not quite understand some stuff.  
I did understand that a value of `0` acrylic opacity is actually `0.125` and `1` is `0.965` (and not `1`) (I don't know if I am correct). But what I did not understand is why the value of `luminosityOpacityRangeMax` particularly `0.88` (`1.03 - 0.15`) and how can I represent it in CSS (like `brightness(88%) /* Different than` [this (at 90%)](https://github.com/microsoft/microsoft-ui-xaml/issues/2402#issuecomment-629304059 "brightness(90%)") `*/` or `brightness(12%) /* 100% - 88%; Too dark */`)

**Comment by chingucoding** [comment]
Why some values are exactly the values they are is probably something @chigy or @kikisaints know.

Regarding the calculated luminosity, here is CSS pseudo code (assuming you have set aOpacity to the respective opacity (a value from 0 to 1) ):

```css

--newOpacity : calc(calc(aOpacity * 0.88) + 0.15);

```

**Comment by SFM61319** [comment]
Oh, thanks, @chingucoding!

**Comment by mdtauk** [comment]
Luminosity was a recent addition, and I think it is used to solve the visibility of shadows within the Acrylic surfaces

**Comment by SFM61319** [comment]
I am so sorry for raising these many doubts but I have one more doubt, @chingucoding (This is another doubt I realized I didn't raise).  
What/where is the variable for the luminosity blend and what equation is used to calculate the luminosity blend value? The one in the code:  
```cpp
double mappedTintOpacity = ((tintColor.A / 255.0) * 0.88) + 0.15;    // line: 457
```  
gives you the `tintOpacity` but not the luminosity blend value. I believe that luminosity value increases with `tintOpacity` for light mode (or light colors) and decreases with `tintOpacity` for dark mode (or dark colors). I just don't know by what factor (as I didn't understand some part of the source code).

**Comment by chingucoding** [comment]
@SFM61319 Are there any other questions regarding the Acrylic brush and its blur? Or can this issue be closed?

**Comment by SFM61319** [comment]
> @SFM61319 Are there any other questions regarding the Acrylic brush and its blur? Or can this issue be closed?

Oh yea I'm so sorry I forgot I created this issue. Gonna close this!

**Comment by SFM61319** [comment]
I didnt want to open another issue so i am renaming and reopening this issue

**Comment by SFM61319** [comment]
How does WinUI create the color pallete (like `themePrimaryColor` which is what the user gives, `themeSecondaryColor` which is part of the pallette which is calculated by WinUI)?

**Comment by SFM61319** [comment]
and no this doesnt need triage, bot

**Comment by SFM61319** [comment]
like how does [Fluent UI Theme Designer](https://aka.ms/ThemeDesigner) do that (too)?

**Comment by SFM61319** [comment]
@chingucoding uhh sorry for pinging you but this was the fastest way...

**Comment by chingucoding** [comment]
I don't know how the different shades for a given accent color is being generated, sorry. Maybe someone from the team knows more.

**Comment by mdtauk** [comment]
I think the Fluent Xaml Theme Editor is open source, so you could look at how they generate their shades.  I am not sure WinUI 3.0 will contain the code, as it may remain a Windows OS feature - but it is possible WinUI 3.0 will contain the code to do it, for backwards compatible support?

**Comment by SFM61319** [comment]
> I don't know how the different shades for a given accent color is being generated, sorry. Maybe someone from the team knows more.

oh, np.  
  
&nbsp;&nbsp;  
  
> I think the Fluent Xaml Theme Editor is open source, so you could look at how they generate their shades. I am not sure WinUI 3.0 will contain the code, as it may remain a Windows OS feature - but it is possible WinUI 3.0 will contain the code to do it, for backwards compatible support?

Yep I'll take a look at it, thanks!

**Comment by SFM61319** [comment]
Also, I am kinda confused. How is the `tintColor` in acrylic set again? Like i said a while ago, i was trying to implement acrylic and reveal brushes in CSS and JS to have a better understanding of how it all works. I wrote the exact same functions written in `AcrylicBrush.cpp` but in js, but i dont know how to get the final color, opacity, saturation and brightness for the acrylic. i will be pasting the functions i wrote in js just in case. thanks!

**Comment by SFM61319** [comment]
```js
const clamp = (value=0.5, min=0, max=1) => {
  if (value < min)
    return min;

  if (value > max)
    return max;

  return value;
}

// ----------------------------------------------------------------------------------------------------------------------------------

const _getEffectiveTintColor = (tintColor, tintOpacity, tintLuminosityOpacity=null) => {
  let [r, g, b, a] = tintColor;
  
  a = a * tintOpacity;
  
  // Update tintColor's alpha with the combined opacity value
  // If LuminosityOpacity was specified, we don't intervene into users parameters
  if (tintLuminosityOpacity == null || tintLuminosityOpacity == undefined) {
    const tintOpacityModifier = _getTintOpacityModifier(tintColor);
    a = a * tintOpacityModifier;
  }
  
  return [r, g, b, a];
}


const _getTintOpacityModifier = (tintColor) => {
  /*
   * This method supresses the maximum allowable tint opacity depending on the luminosity and saturation of a color by 
   * compressing the range of allowable values - for example, a user-defined value of 100% will be mapped to 45% for pure 
   * white (100% luminosity), 85% for pure black (0% luminosity), and 90% for pure gray (50% luminosity).  The intensity of 
   * the effect increases linearly as luminosity deviates from 50%.  After this effect is calculated, we cancel it out
   * linearly as saturation increases from zero.
   */

  const midPoint = 0.5; // Mid point of HsvV range that these calculations are based on. This is here for easy tuning.

  const whiteMaxOpacity = 0.45; // 100% luminosity
  const midPointMaxOpacity = 0.9; // 50% luminosity
  const blackMaxOpacity = 0.85; // 0% luminosity
  
  const [h, s, v, a] = RGBAToHSVA(...tintColor);
  
  let opacityModifier = midPointMaxOpacity;
  
  if (v != midPoint) {
    // Determine maximum suppression amount
    let lowestMaxOpacity = midPointMaxOpacity;
    let maxDeviation = midPoint;
    
    if (v > midPoint)
      lowestMaxOpacity = whiteMaxOpacity, // At white (100% hsvV)
      maxDeviation = 1 - maxDeviation;
      
    else if (v < midPoint)
      lowestMaxOpacity = blackMaxOpacity; // At black (0% hsvV)
    
    let maxOpacitySuppression = midPointMaxOpacity - lowestMaxOpacity;
    
    // Determine normalized deviation from the midpoint
    const deviation = Math.abs(v - midPoint);
    const normalizedDeviation = deviation / maxDeviation;
    
    // If we have saturation, reduce opacity suppression to allow that color to come through more
    if (s > 0)
      // Dampen opacity suppression based on how much saturation there is
      maxOpacitySuppression = maxOpacitySuppression * Math.max(1 - (s * 2), 0);
    
    const opacitySuppression = maxOpacitySuppression * normalizedDeviation;
    
    opacityModifier = midPointMaxOpacity - opacitySuppression;
  }
  
  return opacityModifier;
}


const _getEffectiveLuminosityColor = (tintColor, tintOpacity, tintLuminosityOpacity=null) => {
  let [r, g, b, a] = tintColor;
  
  a = a * tintOpacity;
  
  return _getLuminosityColor([r, g, b, a], tintLuminosityOpacity);
}


const _getLuminosityColor = (tintColor, luminosityOpacity=null) => {
  const [r, g, b, a] = tintColor;
  
  // If luminosity opacity is specified, just use the values as is
  if (luminosityOpacity != null && luminosityOpacity != undefined)
    return [r, g, b, clamp(luminosityOpacity)];
  
  // To create the Luminosity blend input color without luminosity opacity,
  // we're taking the TintColor input, converting to HSV, and clamping the V between these values
  const minHsvV = 0.125;
  const maxHsvV = 0.965;
  
  const [h, s, v, o] = RGBAToHSVA(r, g, b, a);
  const clampedHsvV = clamp(v, minHsvV, maxHsvV);
  const [lr, lg, lb, la] = HSVAToRGBA(h, s, clampedHsvV, o);
  
  // Now figure out luminosity opacity
  // Map original *tint* opacity to this range
  const minLuminosityOpacity = 0.15;
  const maxLuminosityOpacity = 1.03;
  
  const luminosityOpacityRangeMax = maxLuminosityOpacity - minLuminosityOpacity;
  const mappedTintOpacity = (a * luminosityOpacityRangeMax) + minLuminosityOpacity;
  
  // Finally, combine the luminosity opacity and the HsvV-clamped tint color
  return [lr, lg, lb, Math.min(mappedTintOpacity, 1)];
}
```

**Comment by SFM61319** [comment]
what confuses me even more is there are two different functions for the colors (`GetEffectiveTintColor` and `GetEffectiveLuminosityColor`) and idk which is to be used for the final background color and which returns the filters like `saturate` and `brightness` along with `blur` (which we know to be `~20px`)

**Comment by SFM61319** [comment]
> I think the Fluent Xaml Theme Editor is open source, so you could look at how they generate their shades. I am not sure WinUI 3.0 will contain the code, as it may remain a Windows OS feature - but it is possible WinUI 3.0 will contain the code to do it, for backwards compatible support?

@mdtauk i could not find the editor's source which creates the themes based on the accent color passed (and the color mode - light/dark - iirc)...

**Comment by chingucoding** [comment]
AcrylicBrush is not just a simple color, it consists of multiple different layers that are stacked on top of each other:

![Image showing recipe](https://user-images.githubusercontent.com/16122379/97211107-d5048380-17be-11eb-9798-996ea61e05a6.png)

So in order to properly implement that, you would need to be able to stack multiple different filters on top of each other.

**Comment by SFM61319** [comment]
@chingucoding yes I know that but in CSS you can use multiple (backdrop) filters in a single frame(?) by doing:
```css
.acrylic {
  background-color: rgba(r, g, b, a);
  backdrop-filter: blur(20px) /* For the blur */ saturate(some_integer_or_double_for_saturation) brightness(some_integer_or_double_for_brightness);
}
```
and i wanted to know how to calculate the `r`, `g`, `b`, `a` values (idk which function of the above functions to use) for the *background-color* (passing an opaque color (i.e. `alpha = 1`) is returning an opaque color but thats not what `AcrylicBrush` does, it's minimum opacity is `0.125` and maximum is `0.965` (and not `1` so not opaque) iirc), the saturation level (`some_integer_or_double_for_saturation`) and the brightness (`some_integer_or_double_for_brightness`)

**Comment by chingucoding** [comment]
Both the tint and luminosity layer have colors and both of them are stacked on top of each other from what I can tell. If you don't want to use a luminosity layer, just use the `_getEffectiveTintColor` method.
