### ISSUE TITLE
UWP datagrid / Erratic Tab key navigation 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2406]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1014322/uwp-datagrid-erratic-tab-key-navigation.html)._

---
When using DataGridTemplateColumn, and having a textbox in edit mode,
when we are pressing the Tab key the application is selecting the colun header.

The the second Tab key press will go to the next cell. But after the end of the row, it will never go to the next row.

A workaround found but not elegant is:
Create the first column with DataGridTextColumn and start in edit mode in that column.

Note: Has been tested in debug mode

---
#### Visual Studio Feedback System on 5/3/2020, 07:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ranjeshj** [comment]
@michael-hawker This is an issue for the community toolkit.

**Comment by Felix-Dev** [comment]
Is there a way to improve the "vsfeedback" system so that issues like these will be posted to the correct repo - the Windows Community Toolkit - in the first place? I believe we have seen a number of these issues showing up here over the past months when they were actually community toolkit issues.
