### ISSUE TITLE
Alt-F4 keyboard shortcut not working with XAML island

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2408]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1019177/alt-f4-keyboard-shortcut-not-working-with-xaml-isl.html)._

---
I'm implementing a native desktop app using winrt. I'm using Visual Studio 2019 16.5.4, Windows 1909 (Build 18363.778)

Pressing Alt F4 is not working to close the application window when the application is hosting content with XAML Island and 
the keyboard focus has been moved to a XAML control.

Can be reproduced with the following sample:

https://github.com/microsoft/Xaml-Islands-Samples/tree/master/Standalone_Samples/CppWinRT_Basic_Win32App

Steps to reproduce
- Start the application
- Click on the "Hello from Win32" content
- Press Alt F4, the application close OK.

- Start the application gain
- Click on the "Hello from XAML island"
- Press Alt FT, the application does not close.

I did not found any reference on how to handle the keyboard navigation, including handling PreTranslateMessage (using 
IDesktopWindowXamlSourceNative2) to make the standard Windows behavior to work as expected.

Thanks for your time,
Pascal

---
#### Visual Studio Feedback System on 5/6/2020, 07:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Austin-Lamb** [comment]
Thanks for reporting this - we are investigating, and think we may have a possible fix, but we'll do more testing.

**Comment by sylveon** [comment]
Can reproduce this

**Comment by crutkas** [comment]
affecting powertoys.

**Comment by sylveon** [comment]
My crude workaround was putting this before `PreTranslateMessage`
```cpp
// prevent XAML islands from capturing ALT-F4 because of
// https://github.com/microsoft/microsoft-ui-xaml/issues/2408
if (msg.message == WM_SYSKEYDOWN && msg.wParam == VK_F4) [[unlikely]]
{
	SendMessage(GetAncestor(msg.hwnd, GA_ROOT), msg.message, msg.wParam, msg.lParam);
	continue;
}
```
to send back the message to my hosting window.

**Comment by crutkas** [comment]
@sylveon that is the c++ workaround, now to see what the WPF workaround is :)

**Comment by crutkas** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/2481 looks to be the same issue

**Comment by sylveon** [comment]
If you do any processing of ALT+some key it seems that you have to the same. I just needed some special alt+space processing, and had to replace that if by `if (msg.message == WM_SYSKEYDOWN && (msg.wParam == VK_F4 || msg.wParam == VK_SPACE))` to get things to work.

As for WPF, you need to use `ComponentDispatcher.ThreadFilterMessage` @crutkas. I haven't personally tested it, but it's how the WPF XamlHost does its `PreTranslateMessage` processing, so it's your best chance.

**Comment by Jay-o-Way** [comment]
Is there an update for this issue?

> Thanks for reporting this - we are investigating, and think we may have a possible fix, but we'll do more testing.

@Austin-Lamb That's one year ago now.

**Comment by sylveon** [comment]
Still a problem

**Comment by JesseCol** [comment]
Hi there -- if you're interested in moving to WinAppSDK / WinUI3, the version 1.4 stable release now includes similar islands APIs.  We've got a sample in progress here: https://github.com/microsoft/WindowsAppSDK-Samples/pull/307 .  I've validated that ALT+F4 works fine in that sample.  (Note though that the sample contains a WebView2, and ALT+F4 does not automatically work when keyboard focus is in the WebView2, sadly. (see https://github.com/microsoft/microsoft-ui-xaml/issues/8058) )

**Comment by Aetopia** [comment]
> My crude workaround was putting this before `PreTranslateMessage`
> 
> // prevent XAML islands from capturing ALT-F4 because of
> // https://github.com/microsoft/microsoft-ui-xaml/issues/2408
> if (msg.message == WM_SYSKEYDOWN && msg.wParam == VK_F4) [[unlikely]]
> {
> 	SendMessage(GetAncestor(msg.hwnd, GA_ROOT), msg.message, msg.wParam, msg.lParam);
> 	continue;
> }
> 
> to send back the message to my hosting window.

Your solution worked for me in a WPF app (.NET Framework) that has uses XAML Islands.

```csharp
static void OnThreadFilterMessage(ref MSG msg, ref bool handled)
{
    if (handled) return;
    var hwnd = GetAncestor((HWND)msg.hwnd, GA_ROOT);

    if (msg.hwnd == hwnd || hwnd.IsNull) return;
    SendMessage(hwnd, (uint)msg.message, (nuint)(nint)msg.wParam, msg.lParam);
}
```
The following method is attached to `ComponentDispatcher.ThreadFilterMessage` with a couple of changes.

- Check if the message was already handled.

- Only send messages back if the target window isn't the root window.
