### ISSUE TITLE
Visual regression in PointerOver when no MenuItems are defined in NavigationView

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/microsoft-ui-xaml#2409]
**Describe the bug**
When no MenuItems are defined in a NavigationView the Settings (and PaneFooter if using a NavigationViewItem) do  not get the PointerOver background extended to the full width of the control.

**Steps to reproduce the bug**
1. Add a NavigationView control
2. Do not add any MenuItems to the control only the NavigationView tag
3. Run the app

**Expected behavior**
When hovering over Settings entry at the bottom of the NavigationView, the PointerOver state shows the background of the Settings item to expand the whole width of the Navigation pane.

**Screenshots**
![image](https://user-images.githubusercontent.com/13546698/81330926-a8648000-9055-11ea-90a8-de086da4dd2d.png)

**Version Info**
2.4.0-prerelease.200506001 on Windows build 19041.21 running on Desktop

NuGet package version: 
2.4.0-prerelease.200506001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@JuanMejiaVelez Does setting HorizontalAlignment=Stretch on the NavigationViewItem fix the issue ? @ojhad can you take a look and recommend a fix ?

**Comment by ranjeshj** [comment]
When there are no Items it looks like the PaneContentGrid sizes to the footer items and aligns to the left instead of stretching to take the entire pane width.

@ojhad Should this be Stretch instead of Left ?
https://github.com/microsoft/microsoft-ui-xaml/blob/de7ddff2f1e5e228a698293b888575d046f8198d/dev/NavigationView/NavigationView.xaml#L373

**Comment by ojhad** [comment]
> When there are no Items it looks like the PaneContentGrid sizes to the footer items and aligns to the left instead of stretching to take the entire pane width.
> 
> @ojhad Should this be Stretch instead of Left ?
> https://github.com/microsoft/microsoft-ui-xaml/blob/de7ddff2f1e5e228a698293b888575d046f8198d/dev/NavigationView/NavigationView.xaml#L373

If I remember correctly, changing that property to `Stretch` will break the control when collapsing the pane into compact mode. This is due to `PaneContentGrid` still being full width (just hidden) even when in compact mode. So I think the problem lies somewhere else.
