### ISSUE TITLE
focus of textbox (and derivatives) is glitchy

### ISSUE THREAD

**Issue by Trolldemorted** [microsoft/microsoft-ui-xaml#2412]
**Describe the bug**
If a textbox (or a derivative control) does not have focus when your app loses focus and you click directly into that textbox, it appears to have focus (it is highlighed, a cursor appears, the cursor blinks), but you can't type anything into the box.

Note that
- if a textbox has focus when the app loses it, this particular textbox will always work
- this behaviour is not winui specific - I can reproduce it with a normal UWP app too, but I was hoping winui would solve it

**Steps to reproduce the bug**

1. Open XAML Controls Gallery, go to Text -> TextBox
2. Click on any of the textboxes to give it focus
3. Click on any other open window on your system to lose focus
4. Click directly on a different textbox
5. Try to type things

**Expected behavior**
I can type into the textbox I clicked.

**Version Info**
I don't think the store tells me the exact app version, but it says it was updated to winui 2.2.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
All my devices are using W10 Pro N, if that matters.

**Comment by chrisglein** [comment]
This sounds like the same as #1849.
Please speak up if that doesn't seem like the case to you, and feel free to add detail to that issue.

**Comment by Trolldemorted** [comment]
Yeah, this looks like #1849 to me too. Sorry, I didn't find it while searching for potential duplicates!
