### ISSUE TITLE
Question: In WinUI 3.0 will all the conditional XAML be removed?

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#2414]
Lots of XAML has conditions Contract7Present, Contract7NotPresent, etc. I assume this will all go away in WinUI 3.0, correct?

Will someone go through and remove all the conditions before open sourcing?

**Comment by ranjeshj** [comment]
@robloo Yes. You are correct. These will not be needed in WinUI3. @llongley  as FYI.

**Comment by robloo** [comment]
@ranjeshj Ok, good news, that cleans up the XAML quite a bit! Thanks for answering

I'll close this question.

**Comment by jeganrajm** [comment]
Hi Team,

I could see Contract7Present, Contract7NotPresent in WinUI 3. If this going to remove from code, how it will be handled in below code

contract7Present:CornerRadius="{TemplateBinding CornerRadius}"
contract7NotPresent:CornerRadius="{ThemeResource OverlayCornerRadius}"/>

From<https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/CalendarDatePicker/CalendarDatePicker_themeresources.xaml>

I'm trying to provide global support for my custom control as mentioned in https://docs.microsoft.com/en-us/windows/uwp/design/style/rounded-corner#page-or-app-wide-cornerradius-changes

**Comment by Felix-Dev** [comment]
@jeganrajm 
> I could see Contract7Present, Contract7NotPresent in WinUI 3. If this going to remove from code, how it will be handled in below code

Only WinUI 2 is open-source right now so the resource dictionary you are linking below is only for WinUI 2.

To my understanding, WinUI 3 will ship with its own version of the `CalendarDatePicker` which will include that `CornerRadius` property. Right now, you are seeing WinUI using the OS XAML CalendarDatePicker which does not have that API on all WinUI targeted Windos versions, hence why we need to use conditional XAML here. As the WinUI 3 CalendarDatePicker will have that API included, this code will be changed to `CornerRadius="{TemplateBinding CornerRadius}"` in WinUI 3 and will work on all Windows versions targeted by WinUI 3.

**Comment by jeganrajm** [comment]
@Felix-Dev  Thanks for your reply, i'm clear now.
