### ISSUE TITLE
Unable to change scroll position programmatically in some cases and weird behavior in RichEditBox inside ScrollViewer

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/microsoft-ui-xaml#2415]
**Describe the bug**
[Here](https://github.com/JasonStein/Notepads/pull/495) is a pull request to a simple text editor app in which I implement changing scroller position from scrollbar context menu. However the view is reset when app comes into focus. Changes have been made to change scroller position after RichEditBox comes into focus which makes it work for vertical scrollbar but for horizontal scrollbar it doesn't work.

Also, after RichEditBox comes into focus, if you click on any of the text and move your mouse, it will select from there acting like you are doing mouse left click + text selection.

**Steps to reproduce the bug**
1. Clone [this](https://github.com/soumyamahunt/Notepads.git) repo.
2. Switch to "scroll-enhancement" branch.
3. Build and launch the app.
4. Right click on horizontal scrollbar and choose a position for scroller.
5. Click anywhere inside the editor and move/hover the pointer.

**Expected behavior**
Scroll position should change and selection should work normally.

**Screenshots**

![](https://user-images.githubusercontent.com/51203900/81115020-b1aff880-8f40-11ea-87f2-3f4299c786fe.gif)

![](https://user-images.githubusercontent.com/51203900/81118971-8250ba00-8f47-11ea-91d6-6d8447703f9a.gif)

**Version Info**

NuGet package version: not applicable

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19608)              | Yes   |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |  Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by chrisglein** [comment]
@ranjeshj This seems to be scrolling related, or do you have some context here that indicates it's a rich edit bug?
@RBrid Anything look familiar here with regards to programmatic interactions with ScrollViewer?

**Comment by ranjeshj** [comment]
@soumyamahunt Is this specific to having a RichEditBox ? If there was a large rectangle instead of the RichEditBox does it still repro ?
