### ISSUE TITLE
App does not start in release mode

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2416]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1021790/app-does-not-start-in-release-mode.html)._

---
Hi,

I have an Xamarin UWP App.
When I compile it in Debug mode, everything wokrs fine.
When I compile it in Releasemode the desaster begins. Emdiatly after starting the App I receive an unhandled exception in Windows.UI.Xaml.Dll, aatched is a screeshot of the error.

When I disable compile with .NET native chain, the App runs in release mode but the Store certification-kit fails(Also the certification in the Store process fails).

It is extremly important for me to get this run. It is a App-supporting german Companies to help with Corona related issues,so please help me to get out of this!

---
#### Visual Studio Feedback System on 5/7/2020, 08:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ranjeshj** [comment]
Posted on feedback link. Need a repro to debug.

**Comment by Martin-Stein** [comment]
Hi,
It looks like I have found the reason:
My ImageSource needed to have the Assembly as a parameter, like this: 

ToolbarConfig.IconImageSource = ImageSource.FromResource("VisitorCounter.Assets.icons.Settings.png", typeof(MainPage).GetTypeInfo().Assembly);

You can close the case.

Thank you
