### ISSUE TITLE
[BUG] From AppCenter: Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources'

### ISSUE THREAD

**Issue by maxkatz6** [microsoft/microsoft-ui-xaml#2422]
**Describe the bug**
Everything works fine for me and most of my users on all supported devices including Mobile.
But I see crashes from small percent of users (about 0.09%) with next message and stacktrace from AppCenter (unfortunately not really helpful in this case):
```
System.Exception: Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources'

System.Runtime.InteropServices
McgMarshal.ThrowOnExternalCallFailed (Int32 hr, RuntimeTypeHandle typeHnd) f:\dd\ndp\fxcore\CoreRT\src\System.Private.Interop\src\Shared\McgMarshal.cs at 1267:13
__Interop
ComCallHelpers.Call ($__ComObject __this, RuntimeTypeHandle __typeHnd, Int32 __targetIndex) C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Packages\appcompile-20200508-084433-18692\AC\Temp\Ilc1380765118\App.McgInterop\SharedStubs.g.cs at 11369:5
__Interop.ForwardComStubs
Stub_10<System.__Canon> (Void* InstParam, $__ComObject __this, Int32 __targetIndex) C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Packages\appcompile-20200508-084433-18692\AC\Temp\Ilc1380765118\App.McgInterop\SharedStubs.g.cs at 392:4
Microsoft.AppCenter.Utils
ApplicationLifecycleHelper.<ctor>b__17_1 (Object sender, $UnhandledErrorDetectedEventArgs eventArgs) at 0
```

**Steps to reproduce the bug**
Install application from store on specific devices.
I can't reproduce on my dev machine, but see error reports on AppCenter.

**Version Info**
TargetPlatformMinVersion: 10.0.14393.0 (and reason to use WinUI 2.1)
Microsoft.NETCore.UniversalWindowsPlatform: 6.2.10
NetNative: 1.7
Visual Studio: 2019

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

For information about Win10 version and device I have used reports from AppCenter.
| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041, 19624)              | Yes  |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        | Yes  |
| April 2018 Update (17134)          | Yes  |
| Fall Creators Update (16299)       | No  |
| Creators Update (15063)            | No  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   | No  |
| Xbox                      | Yes  |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Related issues:
https://github.com/microsoft/microsoft-ui-xaml/issues/999 - not my case, because I already use VS 2019
https://github.com/microsoft/microsoft-ui-xaml/issues/616 - I don't add PackageDependency to manifest file, but Microsoft.UI.Xaml.2.1 dependency exists in appx package's manifest, so it looks like packed correctly.
https://github.com/microsoft/microsoft-ui-xaml/issues/1632 - I don't use Xamarin, and WinUI nuget package is added to every UWP project in solution.
https://github.com/microsoft/microsoft-ui-xaml/issues/1712 - different error, but probably related.

Could it be problem with Net Native 1.7, which is used for 1607 min target?
Could it be resolved with latest WinUI 2.4 and 1709 min target? I think, I can maintain two packages with different min targets for that.

For me that bug is low priority, because of small amount of users faced it. But I decided to report it just for case.

**Comment by ranjeshj** [comment]
@maxkatz6 I'm not sure what the issue exactly is from the details here. XamlControlsResources is the first type that gets activated, so anything going wrong in activation could be causing this error.

**Comment by codendone** [comment]
This sounds like a known race condition issue in the appx installer which can result in the .pri file not getting installed.  That known issue has been fixed, but I believe the fix has not yet gone out on Windows Update.  If it is this issue, a user could theoretically uninstal all apps using the affected version of WinUI and reinstall to fix the problem.

**Comment by maxkatz6** [comment]
@codendone thanks for information.
I think it could be closed for now.

**Comment by kingofthebongo2008** [comment]
I am experiencing this crash when i try to use examples here for XAML Islands

100% repro

Os : 20h2 19042.487

Microsoft.UI.Xaml version 2.4.3

https://github.com/freistli/ModernizeApp/tree/master/MFC/MFCAppWinUI

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by TheWebartist** [comment]
I'm experencing this issue too on an historical project (previously target 10.0.14393 version with upgrade to 10.0.134) using 2.4.3 version of Microsoft.UI.Xaml librabry.

When I launch the app in debug on PC, that's OK, but on my Xbox One Devkit, that's KO.

I found the solution to my problem with the following change :
In my `.AppxManifest` file, I replace the line of `TargetDeviceFamily` and reset the `MinVersion` and `MaxVersionTested` attributes to `"10.0.0.0"` value.

See the following screenshot
![image](https://user-images.githubusercontent.com/5822487/95061014-535b9180-06fb-11eb-9750-85495d9cc1c3.png)

**Comment by ejserna** [comment]
We're experiencing this too in our app. This started happening in 2.4.2.

**Comment by ejserna** [comment]
[Internal bugs](https://microsoft.visualstudio.com/DefaultCollection/OS/_search?text=Cannot_create_instance_of_type__Microsoft.UI.Xaml.Controls.XamlControlsResources&type=workitem&pageSize=25&filters=Projects%7bOS%7dStates%7bClosed%7d)
[Our bug](https://microsoft.visualstudio.com/OS/_workitems/edit/25626560/)

**Comment by TheWebartist** [comment]
I've experiencing the bug on another PC on 2004 Windows 10 version.
I've downgrading the version of Microsoft.UI.Xaml to 2.4.0 (in replacement of 2.4.3 version) and I've no issue on this device.

**Comment by tipa** [comment]
I am still seeing this crash on a 10.0.22631 device, so I am not sure if this is really fixed...

**Comment by TheWebartist** [comment]
This type of issue occurs on many updates....
It's generaly a missing key in default styles from Microsoft.UI.Xaml

**Comment by tipa** [comment]
Anyone knows if there's any way to fix or workaround it? THese types of crashes are spamming my crash reporting...
