### ISSUE TITLE
UnauthorizedAccessException in UIElement.

### ISSUE THREAD

**Issue by Aberro** [microsoft/microsoft-ui-xaml#2424]
**Describe the bug**
Consecutive changing two properties of a UIElement causes exception.

**Steps to reproduce the bug**
1. Create UWP application with following code:
```
	var icon = new SymbolIcon((Symbol) 0xE71C);
	icon.RenderTransformOrigin = new Point(0.5, 0.5);
	icon.Rotation = 180;
```
2. Run it
3. See error

**Expected behavior**
No exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/3986884/81507522-b7258e00-9306-11ea-892c-cea243c15344.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
I believe this is by design. These two properties are mutually exclusive and the exception message seems to convey that.

**Comment by Aberro** [comment]
Why they are exclusive, why docs doesn't say anything about it and why exception doesn't say that these properties are exclusive? Why, in the first place, throw an exception, instead of just overriding value?

**Comment by h82258652** [comment]
```UIElement.Translate```, ```UIElement.Rotation``` and ```UIElement.Scale``` are base on ```Composition API``` and they can not use with ```UIElement.RenderTransform``` and ```UIElement.RenderTransformOrigin```. But I think it is very necessary to display a friendly error message.

**Comment by kmelmon** [comment]
Apologies for the lack of clear documentation.  In your example, you've used two properties that are incompatible with each other.  The Rotation property is part of a new set of "simple properties" that will eventually take the place of the RenderTransform property.  Right now we support both sets of properties because so many apps are using RenderTransform.

For this example you should use the UIElement.CenterPoint property instead of the RenderTransformOrigin property if you want to control the center of rotation using the UIElement.Rotation property.

From:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.rotation?view=winrt-19041

"Rotates relative to the RotationAxis and the CenterPoint."

**Comment by Aberro** [comment]
Yes, that explains. But still, though, I hope MSDN would be updated with some clarification for other devs to avoid this. Should I close this issue?

**Comment by kmelmon** [comment]
@stmoy can we get a doc bug filed to improve the docs on "simple properties"?  I'll leave this open for a bit to track that request.

**Comment by stmoy** [comment]
Yes, this would be good to document. I'll take a look at this.

**Comment by michael-hawker** [comment]
@stmoy also for `CenterPoint` doesn't this now rely on the size of the component in order to know how to rotate around it's center compared to `RenderTransformOrigin`? This means a lot of extra math is required and that can't easily be done in XAML either.

**Comment by michael-hawker** [comment]
The other confusing thing here is what happens if the `RotationAxis` property is preset on a control and then the Visual is attempted to be obtained:

![image](https://user-images.githubusercontent.com/24302614/94623022-1e1cf280-0268-11eb-876e-e538daa64163.png)

```xml
                    <Button Content="🦙" x:Name="CoverCard" RotationAxis="0,1,0">
                        <Interactivity:Interaction.Behaviors>
                            <Core:EventTriggerBehavior EventName="Click">
                                <Core:ChangePropertyAction PropertyName="Visibility" Value="Collapsed"/>
                                <Core:ChangePropertyAction TargetObject="{Binding ElementName=ContentCard}" PropertyName="Visibility" Value="Visible"/>
                            </Core:EventTriggerBehavior>
                        </Interactivity:Interaction.Behaviors>
                        <animations:Implicit.ShowAnimations>
                            <animations:OpacityAnimation Duration="0:0:1" From="0" To="1.0"></animations:OpacityAnimation>
                        </animations:Implicit.ShowAnimations>
                        <animations:Implicit.HideAnimations>
                            <animations:ScalarAnimation Target="RotationAngleInDegrees" Duration="0:0:1">
                                <animations:ScalarKeyFrame Key="0.001" Value="180"></animations:ScalarKeyFrame>
                                <animations:ScalarKeyFrame Key="1.0" Value="0.0"></animations:ScalarKeyFrame>
                            </animations:ScalarAnimation>
                            <animations:OpacityAnimation Duration="0:0:1" To="0.0"></animations:OpacityAnimation>
                        </animations:Implicit.HideAnimations>
                    </Button>
```
