### ISSUE TITLE
Disabled MenuBarItem can be opened with keyboard navigation

### ISSUE THREAD

**Issue by r2d2rigo** [microsoft/microsoft-ui-xaml#2425]
A user is able to open disabled menu bar items when using keyboard navigation.

**Steps to reproduce the bug**
1. Add the following XAML code to a sample project:

>            <muxc:MenuBar>
>                 <muxc:MenuBarItem Title="File">
>                     <MenuFlyoutItem Text="New"/>
>                     <MenuFlyoutItem Text="Open..."/>
>                     <MenuFlyoutItem Text="Save"/>
>                     <MenuFlyoutItem Text="Exit"/>
>                 </muxc:MenuBarItem>
> 
>                 <muxc:MenuBarItem Title="Edit" IsEnabled="false">
>                     <MenuFlyoutItem Text="Undo"/>
>                     <MenuFlyoutItem Text="Cut"/>
>                     <MenuFlyoutItem Text="Copy"/>
>                     <MenuFlyoutItem Text="Paste"/>
>                 </muxc:MenuBarItem>
> 
>                 <muxc:MenuBarItem Title="Help">
>                     <MenuFlyoutItem Text="About"/>
>                 </muxc:MenuBarItem>
>             </muxc:MenuBar>

2. Run the project. Notice that the "Edit" menu bar item is disabled.
3. Click on the "Edit" menu bar item. Notice that nothing happens.
4. Click on the "File" menu bar item. Notice that it opens.
5. Press the "right arrow" keyboard key. The selection changes to the "Edit" menu bar item and it opens, despite it being disabled. 

**Expected behavior**
The selection should skip the "Edit" menu bar item and jump to the "Help" menu bar item.

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |   |
| April 2018 Update (17134)          |  |
| Fall Creators Update (16299)       |   |
| Creators Update (15063)            |   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |  |
| Surface Hub          |     |
| IoT                         |  |

**Additional context**

**Comment by ranjeshj** [comment]
@adbarlow as FYI. I think when the menu bar item is disabled, it should not react to interactions keyboard or mouse.

**Comment by chingucoding** [comment]
I would like to look into this.
