### ISSUE TITLE
TabView's TabItemTemplate seems to be broken in 1803

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2427]
**Describe the bug**

When binding data to `ItemSource` of `TabView` to display `TabViewItem`s 

1. the `Content` property in the data template does not do anything
2. Setting the `Header` sets the content instead.
3. Content also displays the cross on the right hand margin.

        <winui:TabView.TabItemTemplate>
            <DataTemplate x:DataType="models:TabViewItemData">
                <winui:TabViewItem
                    Header="ABC" // sets the content
                    Content="Content"> // not displayed
                </winui:TabViewItem>
            </DataTemplate>
        </winui:TabView.TabItemTemplate>

However if TabViewItems are added directly to the XAML, it is displayed properly.

**Screenshots**

1803 Screen shot of XAML Gallary
![image](https://user-images.githubusercontent.com/8557046/81534930-38832c00-93ac-11ea-86a7-58927297dbca.png)

2004 Screen shot of XAML Gallary
![image](https://user-images.githubusercontent.com/8557046/81536088-4df95580-93ae-11ea-850c-07aca83c6026.png)

**Version Info**

Seems all

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | No   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |  Yes  |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
There was a feature that was added to ListView to be able to use the container as part of the DataTemplate (as used in this example). This feature is not available in earlier version of the OS. That might explain why this works in Xaml controls gallery on later OS builds. In WinUI3, the fix will go down-level as well, so I expect this to be fixed once we have WinUI3.

To verify, can you see if there are two TabViewItems one under the other in the live visual tree ?
