### ISSUE TITLE
MenuFlyout should have page background color in high contrast

### ISSUE THREAD

**Issue by mcooley** [microsoft/microsoft-ui-xaml#2432]
**Describe the bug**
In recent versions of WinUI, MenuFlyouts have a gray background in high contrast themes. They should have the page background color.

**Steps to reproduce the bug**
Add the following XAML to a test app:
```
<Button Content="Open Flyout">
  <Button.Flyout>
    <MenuFlyout>
      <MenuFlyoutItem Text="Test 1"></MenuFlyoutItem>
      <MenuFlyoutItem Text="Test 2"></MenuFlyoutItem>
    </MenuFlyout>
  </Button.Flyout>
</Button>
```

**Expected behavior**
The background of a MenuFlyout should match the user's preferred background color, like it does in Windows.UI.Xaml.

**Screenshots**
![image](https://user-images.githubusercontent.com/296848/81625351-7c2a6580-93ad-11ea-989f-76ed78d3ba5e.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.200213001
Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19628.mn_release.200508-1414)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Internal bug: 26080077.

**Comment by ranjeshj** [comment]
This does look like a bug. We should match the behavior of Windows.UI.Xaml in this case.
