### ISSUE TITLE
Question: [How can I use local file as xmlns in activeCodePage]

### ISSUE THREAD

**Issue by ymjia** [microsoft/microsoft-ui-xaml#2433]
I am trying to use utf-8 in an existing executable following this [page](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page)

It works ok, but cannot work offline, so Is it possible to save the code page 'http://schemas.microsoft.com/SMI/2019/WindowsSettings' and make xmlns point to that local file?

**Comment by weltkante** [comment]
This is not an online resource, why do you think it doesn't work offline? Its just a way to disambiguate names.
