### ISSUE TITLE
Question: Possible to know when a user started swiping a SwipeControl?

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/microsoft-ui-xaml#2435]
Hello,

In a list item, I have a couple of UI elements I want to hide once the user starts to swipe. Is there an event I can listen to that tells me this? I've tried reacting to the `ManipulationStarting` etc, but that doesn't seem to do anything.

Any help is appreciated here. Thanks!

**Comment by mrlacey** [comment]
If you set `ManipulationMode` you can enable the `ManipulationStarting` Event. This should be what you're after.

```
            ManipulationMode="All"
            ManipulationStarting="SwipeControl_ManipulationStarting"
```

**Comment by patriksvensson** [comment]
@mrlacey This solved it for me! Thank you!
