### ISSUE TITLE
[W10M] MediaElement Hangs on full screen

### ISSUE THREAD

**Issue by NGame1** [microsoft/microsoft-ui-xaml#2438]
Starting from Microsoft.UI.Xaml V2.2.X update every time I try to bring media element to the full screen view I get a black screen and phone will going into a hanged state. sometimes it reboots automatically sometimes I have to hold power key to soft reset. 

I tried this on W10M build 15254 on Microsoft Lumia 950XL DS RM-1116 

A very simple MediaElement even run in this issue
```

    <Grid>
        <MediaElement x:Name="MediaVideo" AreTransportControlsEnabled="True" AutoPlay="False"  Source="https://www.radiantmediaplayer.com/media/bbb-360p.mp4">
            <MediaElement.RenderTransform>
                <CompositeTransform/>
            </MediaElement.RenderTransform>
            <MediaElement.TransportControls>
                <MediaTransportControls IsPlaybackRateButtonVisible="True" IsPlaybackRateEnabled="True"
                                            IsStopEnabled="True" IsCompact="True" IsZoomButtonVisible="False" IsVolumeButtonVisible="False"/>
            </MediaElement.TransportControls>
        </MediaElement>
    </Grid>
```

**Comment by NGame1** [comment]
Finally with helps from @chingucoding I find a temporary workaround for this issue. 
The main issue is coming from the MediaTransportControl style overriding of MS.UI.Xaml
My workaround is like this hope can help other Devs.
```
<MediaElement.TransportControls>
                        <MediaTransportControls IsPlaybackRateButtonVisible="True" IsPlaybackRateEnabled="True"
                                            IsStopEnabled="True" IsCompact="True" IsZoomButtonVisible="False" IsVolumeButtonVisible="False">
                            <MediaTransportControls.Style>
                                <Style TargetType="MediaTransportControls"/>
                            </MediaTransportControls.Style>
                        </MediaTransportControls>
                    </MediaElement.TransportControls>
```
This will ignore the MS.UI.Xaml styles

**Comment by Austin-Lamb** [comment]
We are not investing in MediaElement or Windows 10 Mobile.  For future media usage, I recommend MediaPlayerElement, as it is the replacement for MediaElement - though I don't know if it's available on mobile.
