### ISSUE TITLE
Question: Will WinUI switch from MDL2 Icons to Fluent Icons?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#2439]
It seems that Microsoft has decided to modernise their UI Icons to make them rounder, and more friendly.

![image from the Microsoft Design Medium article](https://user-images.githubusercontent.com/7389110/81793078-c7a15880-9500-11ea-8449-5649c5238b8f.png)

https://medium.com/microsoft-design/developing-an-open-source-icon-system-at-microsoft-b1796315df9f

- So will these replace the MDL2 ones with WinUI 3?
- Will they still come as a font?
- Will there be a version on a 16px grid so as to act as a 1:1 replacement for MDL2 Icons?
- Will the 24px versions also be included as a font choice, and which controls would move to use them? (I could see these working well for Icon Buttons and ApplicationBar Buttons)

https://www.figma.com/community/file/836835755999342788/Microsoft-Fluent-System-Icons
_24px grid Icons released to the community through Figma_

**Comment by ShankarBUS** [comment]
Aren't they already being used in Microsoft's mobile apps such Edge, Outlook?

**Comment by mdtauk** [comment]
> Aren't they already being used in Microsoft's mobile apps such Edge, Outlook?
>
Android and iOS have gotten them first, with the Office app redesign.

AFAIK Edge on Windows is still using MDL2

**Comment by robloo** [comment]
I know I'm asking too much, but please consider open sourcing these new icons or font if it will replace MDL2.

**Comment by mdtauk** [comment]
> I know I'm asking too much, but please consider open sourcing these new icons or font if it will replace MDL2.

They are open, on Figma

**Comment by robloo** [comment]
>>I know I'm asking too much, but please consider open sourcing these new icons or font if it will replace MDL2.
>
>They are open, on Figma

Open as in licencing too? In other words can I use these icons for iOS/Android apps via Uno Platform?

**Comment by mdtauk** [comment]
> > > I know I'm asking too much, but please consider open sourcing these new icons or font if it will replace MDL2.
> > 
> > 
> > They are open, on Figma
> 
> Open as in licencing too? In other words can I use these icons for iOS/Android apps via Uno Platform?

**Our icons are available for everyone to use!**

**Comment by weltkante** [comment]
Note that the license still requires attribution (CC BY 4.0), at least thats what the Figma page says.

**Comment by maxkatz6** [comment]
While I am fine with Fluent Icons, there could be ability to switch back to MDL2 Icons.

**Comment by mdtauk** [comment]
> While I am fine with Fluent Icons, there could be ability to switch back to MDL2 Icons.

Microsoft could include the Full MDL2 Assets font within WinUI, so developers can opt into using them with various controls.  But I think Fluent Icons should become the default

**Comment by shaheedmalik** [comment]
Would it be easy as replacing the font?

**Comment by mdtauk** [comment]
I can't say for sure, but if there is a 1:1 16px version of the icons, and the font uses the same unicode values for the equivalent icons - it should only require a change of FontFamily value in the Resource Dictionaries

**Comment by mdtauk** [comment]
Is there any word on these icons?  Do they come with WinUI 3 or can they be added to WinUI 2.X?

**Comment by gabrieln17** [comment]
I hope the new Fluent icons will properly support FontWeight when they're implemented. This is how the old MDL2 icons behave:
![fontweight](https://user-images.githubusercontent.com/78622729/107124095-64373200-68aa-11eb-9332-9acced0054ad.png)

This is how the SF Symbols work in iOS:
![sfsymbols](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/images/sf-symbols-scales-weights.png)

The new SplitButton style currently uses a ChevronDownSmall glyph instead of ChevronDown, which is why it's thicker. This style can't be replicated easily today for other icons.
![splitbutton](https://user-images.githubusercontent.com/78622729/107124136-a06a9280-68aa-11eb-8973-11be3f338ea7.png)

**Comment by mdtauk** [comment]
They will not support Font Weight.

The Icons come in a variety of sizes, and come in both Regular and Filled versions

**Comment by chigy** [comment]
Please take a look:
https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/iconography
