### ISSUE TITLE
TreeView ItemSource data binding broken in 1803

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2441]
**Describe the bug**
Tree view items are not shown properly in 1803

**Screenshots**

Screenshot from XAML Gallary
![image](https://user-images.githubusercontent.com/8557046/81810236-f56cb880-9565-11ea-9744-c2404776d83f.png)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | No   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |  Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by Felix-Dev** [comment]
Sounds like related to https://github.com/microsoft/microsoft-ui-xaml/issues/2427.

**Comment by ranjeshj** [comment]
Yes. TreeView and TabView use ListView under the covers so it is quite possible that you are hitting the same issue across controls.
