### ISSUE TITLE
In 2.4  NavigationView Items don't display correctly if a drag is attempted from unselected item. 

### ISSUE THREAD

**Issue by groovykool** [microsoft/microsoft-ui-xaml#2443]
**Describe the bug**
In 2.4  NavigationView Items don't display correctly if a drag is attempted from unselected item. 
The reveal style is shown and sticks in pointerover mode?
**Steps to reproduce the bug**

Repo:  https://github.com/groovykool/WinuiNavView1.git
1. Run/debug repo project.
2. Try to drag an unselected NavigationViewItem,
3. Try multiple drags.

**Expected behavior**
The attempts to drag items does not change the appearance of the items.  The reveal style is not stuck on any items.
**Screenshots**
![screen1](https://user-images.githubusercontent.com/48837150/81874957-c003a300-9544-11ea-8daf-06bcafb8e5f5.png)

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml  2.4

| Windows 10 version                  | Saw the problem? |
| November 2019 Update (18363)  | Yes |

| Device form factor | Saw the problem? |
| Desktop                 | Yes  |

**Additional context**
It works fine in Ver 2.32

The XAML Controls Gallery app also exhibits the issue.

Regards,
Tony

**Comment by chingucoding** [comment]
It looks like that clicking and then moving the pointer off the NavigationViewItem results in the "Clicked" state not being unregistered properly.

**Comment by ranjeshj** [comment]
@groovykool NavigationView does not support drag/drop, so I'm curious what you are trying to do. Is it an issue that if someone tries dragging we get into a weird state ?

**Comment by groovykool** [comment]
Why wouldn't someone try dragging?  I have Drag and Drop working fine with NavigationViewItems.  They are UIElements and they DO support drag and drop.

Regards,
Tony

**Comment by ranjeshj** [comment]
> Why wouldn't someone try dragging? I have Drag and Drop working fine with NavigationViewItems. They are UIElements and they DO support drag and drop.

@groovykool I see. You are using the UIElement drag/drop APIs to achieve this. Can you provide more detail on your scenario? Collection controls like ListView had explicit support/APIs for drag/drop/reorder which is what I meant NavigationView did not have. 

@anawishnoff as FYI since you might be hitting a scenario that we did not consider.

What you are seeing does look like a bug.

**Comment by groovykool** [comment]
My scenario is that I will have sections of NavigationViewItems that can be reordered by dragging and dropping.  I will also have a set of NavigationViewItems that are fixed.  I have this working in 2.32 with one workaround.  In 2.4 dragging from no drag items causes the UI issues  

Would it be possible to set the Drop Target Item to the Normal Visual state after drop?  Right now it gets set to the PointerOver Visual state and can't be cleared from code using VisualStateManager?

Regards,
Tony

**Comment by ranjeshj** [comment]
@ojhad can you please take a look/suggest a fix/workaround ?

**Comment by ojhad** [comment]
I can't repro this anymore. It looks like this issue was fixed recently in this PR: https://github.com/microsoft/microsoft-ui-xaml/pull/2625
@ranjeshj do you think those changes are viable to cherry-pick to release or should we just include them with 2.5?
