### ISSUE TITLE
ProgressBar: problems with `Padding`

### ISSUE THREAD

**Issue by carldebilly** [microsoft/microsoft-ui-xaml#2445]
**Describe the bug**
There's many bugs in the ProgressBar when using the `Padding` property. Those tests has been done using the `WinUIProgressBarSimple` sample on the Uno project (unmerged yet, in this PR: https://github.com/unoplatform/uno/pull/3083).

1. Changing the `Value` is causing the left-hand edge of the indicator to move with a padding is applied:
   ![progressbar-bug5](https://user-images.githubusercontent.com/4174207/81962256-787f2480-95e1-11ea-8a93-7d8fb311bc5e.gif)
2. Changing the `Padding` change the right-hand edge of the indicator. Here's it's at 50%, so the right-hand edge shouldn't move at all:
   ![progressbar-bug6](https://user-images.githubusercontent.com/4174207/81962574-eaf00480-95e1-11ea-9bf8-bda1c1b3fba3.gif)
3. After changing the `Height` of the control (here it's illustrated using the `MinHeight`), it's fixing the maximum size of the padding:
   ![progressbar-bug7](https://user-images.githubusercontent.com/4174207/81962987-81bcc100-95e2-11ea-961f-bb0e1ea82731.gif)
4. Setting the `Padding` to a high value will make the indicator dissapear:
   ![progressbar-bug8](https://user-images.githubusercontent.com/4174207/81963358-f98aeb80-95e2-11ea-86be-e2549676e886.gif)
5. Unrelated to `Padding`, but there's also this bug where the animation restarts when the `Height` changes (but it's correct when the `Padding` changes):
   ![progressbar-bug9](https://user-images.githubusercontent.com/4174207/81964830-28a25c80-95e5-11ea-930c-56f84ee58c16.gif)

**Version Info**

NuGet package version: 
`Microsoft.UI.Xaml` version `2.4.0`

**Comment by mdtauk** [comment]
Should the padding be affecting the background track, as well as the progress indicator bar?

**Comment by karenbtlai** [comment]
> Should the padding be affecting the background track, as well as the progress indicator bar?

@MarissaMatt would you be able to help determine the behaviour of padding?

**Comment by MarissaMatt** [comment]
@karenbtlai and @mdtauk the padding should be applied equally to all sides of the blue fill and should not change the background track. The MinHeight value can change the background track size.
