### ISSUE TITLE
wrong behavior when mouse over and exit

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#2448]
repo: https://github.com/HppZ/BitmapIconBug

**Comment by ranjeshj** [comment]
@HppZ can you provide more details on what the current behavior is and what you expect ? Pictures showing the current state would be very helpful as well. Thanks!

**Comment by HppZ** [comment]
mouse over then exit those two controls respectively, then:
![image](https://user-images.githubusercontent.com/12285582/82107657-0717b100-975c-11ea-9877-c0dd601ca5f1.png)

click on them to check them, then mouse over then exit those two controls respectively:
![image](https://user-images.githubusercontent.com/12285582/82107709-5cec5900-975c-11ea-8753-d2782e5f2c05.png)

**Comment by HppZ** [comment]
any update here?

**Comment by HppZ** [comment]
when will you be fixing it?
