### ISSUE TITLE
"By default, the DataGrid.ColumnWidth property is set to SizeToHeader", or is it!

### ISSUE THREAD

**Issue by dragus0** [microsoft/microsoft-ui-xaml#2451]
While not specified in the XAML Code, but shown as SizeToHeader in the Properties Window, it actually behaves like SizeToCells.

https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/sizing-options-in-the-datagrid-control

Sorry if this is the wrong repo. It probably is lol.

<DataGrid x:Name="Tables_DataGrid" Grid.Row="3" Grid.RowSpan="1" Margin ="0" RowDetailsVisibilityMode="VisibleWhenSelected" EnableRowVirtualization="True" DataContext="{StaticResource Tables_ViewSource}" ItemsSource="{Binding Source={StaticResource Tables_ViewSource}}" Grid.Column="1" IsTextSearchEnabled="True" TextSearch.TextPath="Hardware_Model" SelectedIndex="30">

![grafik](https://user-images.githubusercontent.com/62744978/82055978-f159ab80-96c9-11ea-89fd-ac9440f1879a.png)

![grafik](https://user-images.githubusercontent.com/62744978/82055951-e737ad00-96c9-11ea-8869-0ddfc6438077.png)
But when a cell with longer text is reached:
![grafik](https://user-images.githubusercontent.com/62744978/82056019-00405e00-96ca-11ea-8884-0e127f5ede43.png)

VS2019

**Comment by ranjeshj** [comment]
@dragus0 If this issue is regarding the WPF DataGrid, can you post it in the WPF repo ? https://github.com/dotnet/wpf

**Comment by dragus0** [comment]
sure. thanks
