### ISSUE TITLE
Question: How to use a custom enum in a dependency property?

### ISSUE THREAD

**Issue by ackh** [microsoft/microsoft-ui-xaml#2453]
I'm working on a C++/CX based user interface element and I'm stuck with a particular problem. I'm asking here because I cannot find documentation or sample code that would help. Apologies if this is not the right location but I'm frankly running out of options.

On my C++/CX user interface element I need to add a dependency property that uses a custom `enum class` as type. Here's the code that I have:

    // enum file:

    public enum class DemoEnum
    {
      One = 1,
      Two = 2,
      Three = 4,
    };

    // Header file:

    public ref class MyUserInterfaceElement sealed
    {
      property DemoEnum Demo
      {
        DemoEnum get();
        void set(DemoEnum value);
      };

      static property Windows::UI::Xaml::DependencyProperty^ DemoProperty
      {
        Windows::UI::Xaml::DependencyProperty^ get();
      };

      static Windows::UI::Xaml::DependencyProperty^ _demoProperty;
    };

    // cpp file:

    DemoEnum MyUserInterfaceElement::Demo::get()
    {
      return static_cast<DemoEnum>(GetValue(DemoProperty));
    }

    void MyUserInterfaceElement::Demo::set(DemoEnum value)
    {
      SetValue(DemoProperty, value);
    }

    DependencyProperty^ MyUserInterfaceElement::_demoProperty =
      DependencyProperty::Register("Demo",
                                   TypeName(DemoEnum::typeid),
                                   MyUserInterfaceElement::typeid,
                                   ref new PropertyMetadata(DemoEnum::One,
                                                            ref new PropertyChangedCallback(&MyUserInterfaceElement::OnDemoChanged)));

    void MyUserInterfaceElement::OnDemoChanged(DependencyObject^ d, DependencyPropertyChangedEventArgs^ e)
    {
      MyUserInterfaceElement^ myUserInterfaceElement = static_cast<MyUserInterfaceElement^>(d);
      myUserInterfaceElement->_renderer->SetDemo(static_cast<DemoEnum>(e->NewValue));
    }

The strange thing is that it works at runtime, i.e. getting and setting the value of the dependency property while the application is running works as expected. However, the problem occurs at design time. Attempting to set the property via XAML results in the XAML error message 

> No such interface supported

Does anyone know what is going on here?

**Comment by ackh** [comment]
It seems that I need to first cast `e->NewValue` to `int` before I can cast it to `DemoEnum`. Interestingly this is only necessary when changing the dependency property in the XAML designer. If the application is running it works without the cast to `int`. It eludes me why this is the case, XAML designer magic I guess.

The corrected code looks like this:

void MyUserInterfaceElement::OnDemoChanged(DependencyObject^ d, DependencyPropertyChangedEventArgs^ e)
{
  MyUserInterfaceElement^ myUserInterfaceElement = static_cast<MyUserInterfaceElement^>(d);
  myUserInterfaceElement->_renderer->SetDemo(static_cast<DemoEnum>(static_cast<int>(e->NewValue)));
}

The issue is resolved by this, sorry for the noise.

**Comment by JeanRoca** [comment]
Closing this issue as resolved.
