### ISSUE TITLE
Question: Why users can't set uwp app as default opener for custom/undeclared file types

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/microsoft-ui-xaml#2456]
For win32 apps user can provide path of .exe to open a custom file type, this is especially helpful for text editor apps as it is impossible to declare all file types. But in uwp there is no way to do this, currently in [this PR](https://github.com/JasonStein/Notepads/pull/534), I am implementing desktop extension so user can choose to open file with the extension which then redirects activation to the uwp app, but I am running into issues described [here](https://stackoverflow.com/questions/61796192/open-unsupported-file-type-extensions-with-uwp-app). My question is why isn't this supported by default, why aren't we allowed to support file types based on their content/mime type (which android does)??

**Comment by JasonStein** [comment]
One thing I want to add here: It is not possible to even rename a file without extension in UWP. 
You can register extensions like ".txt" or ".md" with your app and your app can deal with them nicely but once you use StorageFile.RenameAsync to change a file from "file.txt" to "file", you will get blocked because you have do not have support for that and there is no way to specify no extension registration with UWP, right?

**Comment by soumyamahunt** [comment]
> One thing I want to add here: It is not possible to even rename a file without extension in UWP.
> You can register extensions like ".txt" or ".md" with your app and your app can deal with them nicely but once you use StorageFile.RenameAsync to change a file from "file.txt" to "file", you will get blocked because your app do not have registration for that and there is no way to specify no extension registration with UWP, right?

Yes, also for `Launcher.LaunchFileAsync()` if you pass any file type that isn't supported by uwp it won't open even if you specify `TargetPackageFamilyName` and `ContentType` in `LauncherOptions`. It doesn't throw any exception or return any value the execution just stops.

**Comment by shaheedmalik** [comment]
They actually added that ability to Windows Insider recently.
> What’s new in Build 19608
> 
> Improving your default apps experience
> Over the years, we’ve made a number of improvements to Settings based on your feedback, and we’re happy to share the next one is starting to roll out. We’re adding the ability to search the lists of file types, protocols, and apps when setting a default.
> 
> Showing the Choose default apps by file type Settings window, now with a search box.
> 
> This change is currently available for 50% of Insiders in the Fast ring as we evaluate the quality. We’ll let you know when that rollout increases. Please give it a try once it’s available on your device, and let us know what improvements you’d like to see next!
>https://blogs.windows.com/windowsexperience/2020/04/15/announcing-windows-10-insider-preview-build-19608/

**Comment by soumyamahunt** [comment]
> They actually added that ability to Windows Insider recently.
That's just adding search ability in default apps settings, that's not what the question is about.

**Comment by jesbis** [comment]
closing in favor of https://github.com/microsoft/ProjectReunion/issues/27
