### ISSUE TITLE
Bug: Pivots inside of a TabView's content disappear when rearranging the selected tab

### ISSUE THREAD

**Issue by dpaulino** [microsoft/microsoft-ui-xaml#2460]
**Describe the bug**

Pivot headers inside of a TabView's content will disappear when you rearrange the selected tab, **but only if you perform the drag drop slowly such as ~3 seconds**.
Video of bug: https://streamable.com/mzrxvs 

**Steps to reproduce the bug**

1. Follow instructions here: https://github.com/dpaulino/tabview-content-disappearing/tree/disappearingPivot#description-for-disappearingpivot-branch

**Expected behavior**

Pivot header text does NOT disappear after rearranging.

**Screenshots**

Video of bug: https://streamable.com/mzrxvs

**Version Info**

NuGet package version: 

WinUI 2.4

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (version 2004 build 19041.264)              |  Yes  |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

I created this issue earlier: https://github.com/microsoft/microsoft-ui-xaml/issues/2455. Not sure if it's related.

**Comment by ranjeshj** [comment]
@RBrid Does this issue look familiar ?

**Comment by RBrid** [comment]
@ranjeshj No - I don't think that's the same bug as the Pivot bug I am currently investigating for WinUI 3.0 Desktop.

**Comment by dpaulino** [comment]
Bump

**Comment by DmitriyKomin** [comment]
@dpaulino, thank you for reporting this. Unfortunately we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).

If this reproes in WinAppSDK, it would also be a lower priority issue as NavigationView/TabView are now preferred over Pivot.
