### ISSUE TITLE
ContentDialog rendering z-order should be higher than FlyoutBase

### ISSUE THREAD

**Issue by 0x7c13** [microsoft/microsoft-ui-xaml#2461]
Screenshots are pretty much self explained:

![image](https://user-images.githubusercontent.com/1166162/82145322-d046a700-97fe-11ea-82d0-4f02f2737c0b.png)

![image](https://user-images.githubusercontent.com/1166162/82145531-f704dd80-97fe-11ea-8d4e-d6bdf1263a47.png)

![image](https://user-images.githubusercontent.com/1166162/82145562-fc622800-97fe-11ea-888a-599150777cf5.png)

If not, I need to manage EVERY single flyout used in my app so that I can manually "Hide" them before any ContentDialog is showing.

Another approach would be auto hiding all existing flyouts before showing the ContentDialog.

**Comment by mdtauk** [comment]
This seems like a good suggestion, I am curious as to how your flyouts are appearing when the UI behind the content dialog is not supposed to be interactive?  The Smoke layer is supposed to prevent buttons being hit.

**Comment by JasonStein** [comment]
> This seems like a good suggestion, I am curious as to how your flyouts are appearing when the UI behind the content dialog is not supposed to be interactive? The Smoke layer is supposed to prevent buttons being hit.

The flyouts were opened before ContentDialog is showing, not after.

**Comment by chingucoding** [comment]
What if somebody has some fields/buttons in the ContentDialog that can create a flyout? Which should have precedence there?

**Comment by ranjeshj** [comment]
When the content dialog opens, it should dismiss any existing light dismiss flyouts. If a flyout is opened from the content dialog, it should be above the content dialog. Any non light dismiss flyouts should be below the content dialog.  When the dialog is dismissed, the non light dismiss flyout will still be available.

@chigy as FYI.
