### ISSUE TITLE
Hamburger menu button appears at wrong location when changing NavigationView.PaneDisplayMode from Top to LeftCompact

### ISSUE THREAD

**Issue by chausner** [microsoft/microsoft-ui-xaml#2462]
**Describe the bug**
When `NavigationView.PaneDisplayMode` is changed programmatically from `Top` to `LeftCompact`, the hamburger menu button appears at the wrong location. Once you force a layout update (e.g. by resizing the window), it jumps to the expected location.

**Steps to reproduce the bug**
1. Create a new blank WinUI 3 app.
2. Add a `NavigationView` with `PaneDisplayMode` set to `Top`.
3. Add a button that, when clicked, changes `PaneDisplayMode` to `LeftCompact`.
4. Run the app and click the button.

**Expected behavior**
The hamburger button should get displayed immediately at the correct location.

**Screenshots**
![bug](https://user-images.githubusercontent.com/15180557/82154076-e8a0db00-986b-11ea-9222-bf3d2f0363ab.png)

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-alpha.200210.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment]
The NavigationView inside the "latest" WinUI 3 alpha version is a bit old and probably does not contain the latest bug fixes. Since the WinUI 2 NavView does render this correctly, maybe this was an issue that was already fixed, but has to be released in WinUI 3.

**Comment by ranjeshj** [comment]
@chingucoding is correct. Can you see if this repros with the latest winui 2.4 prerelease ?

**Comment by chingucoding** [comment]
I've tried switching from Top to LeftCompact in the MUXControlsTestApp and XAML Controls Gallery and couldn't repo the issue.

**Comment by chausner** [comment]
Thanks for the hint. I can confirm I cannot reproduce the issue anymore after updating to NuGet package version 3.0.0-preview1.200515.3.
