### ISSUE TITLE
Expand messes up selected item

### ISSUE THREAD

**Issue by msavazzi** [microsoft/microsoft-ui-xaml#2463]
**Describe the bug**
When the item is expanded the selected item is messed up, goes to a random one, and often is out of screen

**Steps to reproduce the bug**
download solution: [https://1drv.ms/u/s!AohVtHaw3aCiwaE8ADrS0bbIbs6vkA?e=DaJGvn](https://1drv.ms/u/s!AohVtHaw3aCiwaE8ADrS0bbIbs6vkA?e=DaJGvn)
1. Compile
2. Click on the first folder - Pictures (NOT on the expand glyph)

**Expected behavior**
Pictures to be expanded AND remain selected and visible

**Screenshots**
I just clicked on the PictureFolder and the LAST item is selected!
![image](https://user-images.githubusercontent.com/2660032/82159854-a68a9000-9891-11ea-9502-c11f182954fd.png)

**Version Info**
Windows 10 1909 - 64bit.
App compiled debug 64bit

NuGet package version: 
Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            | |
| October 2018 Update (17763)        ||
| April 2018 Update (17134)          | |
| Fall Creators Update (16299)       | |
| Creators Update (15063)            | |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes | 
| Mobile                   | |
| Xbox                      | |
| Surface Hub          | |
| IoT                         | |

**Additional context**
Example directly from page: [TreeView](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)

**Comment by ranjeshj** [comment]
This looks like the same/similar issue as #1820

**Comment by msavazzi** [comment]
in my case it does not always select the item below, it's more random
