### ISSUE TITLE
  After adding new templated control to my namespace running into XamlCompiler error WMC0610: The XAML Binary Format (XBF) generator reported syntax error '0x09c6'

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2467]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1034515/after-adding-new-templated-control-to-my-namespace.html)._

---
Facing this error across many places during compilation after adding a templated control (often) on the working namespace and sometimes while referring to his namespace  (some cases), 

Removing back the added empty templated control We were able to build the solution which actually feels wierd and seems to be like a glitch. If this is not a glitch Can you throw us some lights on that error letting us know why it could possibly occur ?

Commenting out the error lines out in xaml helps us to generate a build without having to remove the templated control.

Case 1: 
```
<UserControl.Resources>
        <ResourceDictionary>
            <DataTemplate x:DataType="model:myModelObj"
                          x:Key="myControl">
 <!-- Replacing the below line with a textblock helps us to get a build -->
                <controls:myControl myProperty="{Binding}"
                                                    myControlClick="myControlClick_click"/>
            </DataTemplate>
        </ResourceDictionary>
  </UserControl.Resources>
```
Case 2:
```
<!--  xbf error occurs with the folowing lines as well after adding a new control to the existing namespace-->
<myControl:MyOwnControl HorizontalAlignment="Left"/>
```
---
#### Visual Studio Feedback System on 5/18/2020, 02:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ranjeshj** [comment]
can you please provide a repro project ?

**Comment by GeorgeKerwood** [comment]
Having exactly the same issue.

**Comment by legistek** [comment]
Why is this closed?

So we can't put a `DataTemplate` with an `x:DataType` in a `ResourceDictionary`? This is by design???

**Comment by legistek** [comment]
Oh I see, it needs a code-behind class.

Would it have killed them to make the error message for this intelligible?
