### ISSUE TITLE
Override AutoSuggestBox TextBoxStyle with the DefaultTextBoxStyle

### ISSUE THREAD

**Issue by NGame1** [microsoft/microsoft-ui-xaml#2469]
The issue is so simple and simple to fix also But unfortunately I can't test because I'm getting this issue when trying to debug the code 
Type 'StaticResource' used after '{' must be a Markup Extension. Error code 0x03e9.
The main issue is that the AutoSuggestBox style is different from TextBox 
![image](https://user-images.githubusercontent.com/19765248/82266915-3e66a780-9980-11ea-8061-6942834ae066.png)
I think simply 2 or 3 lines of Xaml code can solve this issue simply.

**Comment by chingucoding** [comment]
I am not entirely sure what the issue here is. On my machine the TextBox and the AutoSuggestBox look quite the same except for the quereybutton:

![image](https://user-images.githubusercontent.com/16122379/82268573-a8c31c00-996f-11ea-9030-da523b70b2a1.png)

![image](https://user-images.githubusercontent.com/16122379/82268607-b8dafb80-996f-11ea-98cb-c6837645209c.png)

**Comment by NGame1** [comment]
uh You're right @chingucoding 
Is there any way to exclude any of the styles in Microsoft.Xaml.UI
Seems this style https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/CommonStyles/MediaTransportControls_themeresources.xaml
is causing this issue on mobile:
https://github.com/microsoft/microsoft-ui-xaml/issues/2438

And another question is there any way to reference the MS.UI.Xaml styles in my resource dictionary for example this way 
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="ms-appx:///UserControlLibs/Styles.xaml"/>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>

or no?
Thanks for your help anyhow

**Comment by chingucoding** [comment]
Afaik there is no good way to exclude styles. If the old style of a control is not causing this issues, you could get the old style and add it to your application (or page) resources.

Regarding merged dictionaries:

In the [XAML Controls Gallery](https://github.com/microsoft/Xaml-Controls-Gallery), we do the following to load the WinUI resource dictionary alongside another dictionary:

```xml
<Application>
            <ResourceDictionary.MergedDictionaries>
                <!-- Custom dictionary -->
                <local:ItemTemplates />
                <!-- WinUI styles and resources -->
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
            </ResourceDictionary.MergedDictionaries>
</Application>
```

**Comment by NGame1** [comment]
Thanks really for your helps @chingucoding

**Comment by chingucoding** [comment]
Happy that I could help you :)
