### ISSUE TITLE
Why reinvent the wheel instead of using KeyRoutedEventArgs.KeyStatus.RepeatCount ?

### ISSUE THREAD

**Issue by eugenegff** [microsoft/microsoft-ui-xaml#2471]
https://github.com/microsoft/microsoft-ui-xaml/blob/c99f508d96b395c49c9730360294e39e0e14e8dd/dev/NavigationView/NavigationView.cpp#L2178

**Comment by eugenegff** [comment]
Correction: CorePhysicalKeyStatus.WasKeyDown should be used instead of CorePhysicalKeyStatus.RepeatCount

**Comment by ranjeshj** [comment]
That sounds like a good idea. We can avoid the member variable as well. @chingucoding as FYI. @eugenegff would you like to contribute a fix ?

**Comment by chingucoding** [comment]
@eugenegff Would you like to contribute a fix, or would you be fine with me creating a PR for this?

**Comment by eugenegff** [comment]
> @eugenegff Would you like to contribute a fix, or would you be fine with me creating a PR for this?

I'll be fine :)
