### ISSUE TITLE
WinUI 3 Preview 1 – Featuring Desktop App Support 💻🎉

### ISSUE THREAD

**Issue by adambarlow** [microsoft/microsoft-ui-xaml#2472]
# WinUI 3 Preview 1 – Featuring Desktop App Support
As mentioned in the recent community call, and this morning at //BUILD, today we are releasing [WinUI 3 Preview 1](http://aka.ms/winui3/preview1).

We are excited to bring you this release, which includes the following high-level feature additions:

- Ability to create Desktop (Win32) Apps with WinUI
	- Including using .NET 5 (for Win32)
- Feature additions from WinUI 2.4
	- RadialGradientBrush
	- TabView updates
	- Dark Theme updates
- Improvements and updates to the WebView2
	- Support for High DPI
	- Support for window resizing and moving
	- Updated to target more recent version of Edge
	- No longer necessary to reference a WebView2-specific Nuget package
- SwapChainPanel
- Improvements needed for open source migration

Please note that [WinUI 3 Preview 1](http://aka.ms/winui3/preview1) remains a an early pre-release style product. As such it has known issues and missing functionality. It is not ready for production apps. In particular there are some considerations to make when making Desktop (Win32) apps.

Please take some time to [review the instructions for getting started with Desktop apps](http://aka.ms/winui3/desktopguide).
 
We welcome feedback on all areas of the release by filing issues here on GitHub. Please let us know about any issue, no matter how large or small.
 
## What's next?
We're hard at work getting WinUI ready for open source development, which will be released later this year. We will be continuing our preview releases with increased quality and stability moving forward.
 
## Installation info
For download please go to the [download page and release notes](http://aka.ms/winui3/preview1)

**Comment by adrientetar** [comment]
Congrats!! Btw it would be nice to have the Win2D support, I need it for my project unfortunately.

**Comment by vitorgrs** [comment]
Is there any plans to support it on VS Code? And I mean, without needing to install full VS.
UWP SDK + .NET + VS Code only?

**Comment by hatharry** [comment]
I'm trying to use ANGLE.WindowsStore and SwapChainPanel in WinUI 3, this is the function I'm using:

public EGLSurface CreateSurface(SwapChainPanel panel)
        {
            if (panel == null)
            {
                throw new ArgumentNullException("SwapChainPanel parameter is invalid");
            }

            EGLSurface surface = EGL_NO_SURFACE;

            int[] surfaceAttributes =
            {
					// EGL_ANGLE_SURFACE_RENDER_TO_BACK_BUFFER is part of the same optimization as EGL_ANGLE_DISPLAY_ALLOW_RENDER_TO_BACK_BUFFER (see above).
					// If you have compilation issues with it then please update your Visual Studio templates.
					EGL_ANGLE_SURFACE_RENDER_TO_BACK_BUFFER, EGL_TRUE,
                    EGL_NONE
                };

            // Create a PropertySet and initialize with the EGLNativeWindowType.
            PropertySet surfaceCreationProperties = new PropertySet();
            surfaceCreationProperties.Add("EGLNativeWindowTypeProperty", panel);

            surface = eglCreateWindowSurface(mEglDisplay, mEglConfig, surfaceCreationProperties, surfaceAttributes);
            if (surface == EGL_NO_SURFACE)
            {
                throw new Exception("Failed to create EGL surface"); <--- ERRORS HERE
            }

            return surface;
        }
 Using a Universal Windows app the function works fine, but moving to WinUI 3 it fails to create a EGL surface.

**Comment by MehediH** [comment]
Hey @adambarlow, is it possible to add WinUI 3 to an existing Win32 C++ desktop app? I have installed the preview and the WinUI extension as explained here https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop#create-a-winui-3-desktop-app-for-cwin32 but I am not sure how to add the WinUI 3 nuget package to my existing project...for some reason searching for Microsoft.WinUI does not display anything on Nuget.

Am I missing something?

**Comment by Symbai** [comment]
I've tried the Win32 support (basically wanted to created an WPF app which is using WinUI features & controls) and I have a question: Are there any plans to make it work natively? I mean without all these side-load / app package / UWP-_thing_, that makes me feel this is more like a wrapper, something like XAML Island is, which takes some UWP-`thing` and host it inside WPF. Is this is only because its the first alpha or is this the way to go?

Also on following step 7 to create a new blank WinUI page, the first one, everything crashed. So I cannot give any other feedback.
