### ISSUE TITLE
When automatically hide scroll bars is off, scroll bars are initially collapsed and then expand

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#2478]
**Describe the bug**

when "automatically hide scrollbars" is off in Windows, when you first open the app, the scrollbars are collapsed and then expand. This behaviour is consistent across Windows. The Start menu is where I notice this most often.

**Steps to reproduce the bug**

1. Enable "Automatically hide scroll bars"
2. Open XAML Controls Gallery

**Expected behavior**

scroll bars would already be expanded.

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update |  Yes  |
| November 2019 Update (18363)  |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by Poopooracoocoo** [comment]
Do not close

**Comment by DmitriyKomin** [comment]
@Poopooracoocoo, thank you for reporting this. At this time we are not planning to revisit scrollbar visual behavior.
