### ISSUE TITLE
WinUI Win32 apps missing window close animation

### ISSUE THREAD

**Issue by BreeceW** [microsoft/microsoft-ui-xaml#2479]
**Describe the bug**
Usually, with system animations enabled, Windows apps (that is, both UWP and Win32) play a shrinking and fading animation when closed. WinUI Win32 apps play no animation when closed. See below for a comparison.

**Steps to reproduce the bug**
1. Open a WinUI Win32 app
2. Click close

**Screenshots**
| Expected | WinUI Win32 |
| :-: | :-: |
| ![Normal closing](https://user-images.githubusercontent.com/18747724/82367286-908be500-99e1-11ea-9b9c-5c09952f1179.gif) | ![No animation](https://user-images.githubusercontent.com/18747724/82367299-95509900-99e1-11ea-80cf-cb655d58e416.gif) |

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview1.200515.3]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@MikeHillberg @Austin-Lamb Can you help route this ?

**Comment by krschau** [comment]
@codendone FYI

**Comment by BreeceW** [comment]
The window animations have been working for a while now. Unfortunately, the XAML content of a WinUI 3 window still flickers in after the window opening animation and flickers out before the window closing animation, but that warrants a separate issue.
