### ISSUE TITLE
WinUI Win32 app opens and closes in taskbar before opening

### ISSUE THREAD

**Issue by BreeceW** [microsoft/microsoft-ui-xaml#2480]
**Describe the bug**
A WinUI Win32 app pops up in the taskbar before disappearing, before reappearing and finally opening. See the animation below.

**Steps to reproduce the bug**

1. Open a WinUI Win32 app (through Start, search, or desktop icon—doesn’t seem to matter)
2. Observe taskbar (slightly different behavior that is also wrong if pinned to taskbar)

**Expected behavior**
The icon should appear on the taskbar once and stay open.

**Screenshots**
![Weird opening](https://user-images.githubusercontent.com/18747724/82368931-34769000-99e4-11ea-83b6-4b30823420f9.gif)

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Some Win32 apps (notably, I believe Google Chrome) also occasionally exhibit something similar to this behavior.

**Comment by ranjeshj** [comment]
@MikeHillberg @Austin-Lamb Any ideas what might be happening here and where this issue needs to be routed ?

**Comment by llongley** [comment]
This looks like it's fixed in the latest preview version.  Let me know if that's not the case.
