### ISSUE TITLE
WinUI3 Assembly is not strong named

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#2483]
**Describe the bug**
When compiling a class library with strong name enabled and referencing WinUI, I'm getting the following build warnings:
```
3>CSC : warning CS8002: Referenced assembly 'Microsoft.WinUI, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

**Steps to reproduce the bug**
1. Create a strong-named class library and reference WinUI
1. Compile
2. Observe the warning

**Expected behavior**
No warning generated / assemblies should be strong named.

**Version Info**
3.0.0-preview1.200515.3

NuGet package version: 
Microsoft.UI.Xaml 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by karenbtlai** [comment]
Closing this task as it is now resolved in the Azure Devops repo. The assembly is now strong-named signed with additional versioning information.
