### ISSUE TITLE
Framerate annihilation on iteraction with UI elements

### ISSUE THREAD

**Issue by Yen** [microsoft/microsoft-ui-xaml#2486]
When interacting with the button on the default template for C# blank app in preview 1, the framerate of my entire desktop gets lowered drastically for up to a second at which point it returns to normal. Both clicking and just hovering over the button cause this to happen.

Note that I am recording this on a high refresh rate monitor (144hz) and as such, samples and videos shown below might not be visible on lower refresh rate devices.

**Steps to reproduce the bug**
Create the blank app C# template in preview 1.
Hover over button.

**Expected behavior**
Not make my desktop and any other graphically enhanced content (games, videos) break.
I can fully confirm that this does _not_ happen on older UWP applications (both the settings and and the windows calculator do not cause this issue).

**Screenshots**
This is a video here and not a gif as to show the issue best requires high refresh rate playback.
https://streamable.com/wkybdm
The website used here is https://www.testufo.com/ and is a common website used for testing high refresh rate issues. Please ignore that the website is saying stuttering issues are occuring even before the UI component is interacted with, the video recording software causes enough of a disruption to trigger this. Even without a high refresh rate monitor, you can see the UFOs desync and slow down massively for a second after interaction indicating a massive issue with the framerate of the desktop at that time.

**Version Info**

NuGet package version: [Microsoft.WinUI 3.0.0-preview1.200515.3]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@MikeHillberg @jeffstall @codendone as FYI

**Comment by codendone** [comment]
@Yen We have not be successful at reproing this issue. Could you try this on Preview 3 to see if the problem still repros for you there?

**Comment by Yen** [comment]
@codendone I have updated to the latest preview version of visual studio and reinstalled the winui3 preview extension. I can confirm the issue persists.

**Comment by codendone** [comment]
Thanks for checking, @Yen! We'll keep working on this, then.

**Comment by Yen** [comment]
@codendone I had another look and it turns out this bug only presents itself when the window itself is in focus even though the visual effects for the hover event are firing when not in focus! Here is an example of this https://streamable.com/dihpx1 (again, not an embedded gif because of the playback framerate). You can see the same behaviour as before where it causes any other hardware accelerated content on the device to get serious frame timing issues for a second before resolving.

10.0.19041 Build 19041
GTX 1070 driver version 456.38

**Comment by codendone** [comment]
Very interesting. Thanks for these extra details!

**Comment by ChewWorker** [comment]
I just checked this with a recent windows build with a 144Hz monitor.  I tried a variety of different scenarios including the blank sample app not in focus and hovering over the button.  I couldn't reproduce the issue.  If this is still reproing we need more information to be able to reproduce your configuration or get a trace from this machine/configuration.

Thanks!

**Comment by Yen** [comment]
@ChewWorker Would you be able to see if you can reproduce this on a machine with both a 144hz monitor and a 60hz monitor attached at the same time? This is the only other thing I can think of that has caused issues for me in the past as far as high refresh rate goes.

**Comment by pratikone** [comment]
could you verify if this issue still appears. The old video link has expired. if it does, feel free to reopen this issue and also attach a new video as it has been hard to debug

**Comment by a1steaksa** [comment]
Hey, I've just come across this issue after running into this problem.  I have a 144hz left monitor and a 60 hz right monitor.  The Windows Store version of the WinUI 3 Gallery app shows this effect.

It can be repro'd on my end by comparing quickly minimizing/maximizing the WinUI 3 Gallery by clicking the taskbar icon.  By comparison, Windows Explorer performs just fine when doing the same.

Some additional details, in case it's useful:
* Running Windows 11 21H2 OS Build 22000.1335
* I've been able to get this same effect in a custom window using the `Blank App, Packaged (WinUI 3 in Desktop)` template, potentially to a lesser degree, though it's hard to say for sure from just looking at it.

[DxDiag.txt](https://github.com/microsoft/microsoft-ui-xaml/files/10296582/DxDiag.txt)

https://user-images.githubusercontent.com/8369707/209383350-a3b97ae8-603b-4f8e-b237-573a6636718d.mp4

If there's any other info I can give that might help, please let me know.

**Comment by pratikone** [comment]
thanks. I will check it out. re-opening the issue
