### ISSUE TITLE
WinUI 3 - Horrible dependency property performance, more than 1000-3000 times slower than in wpf

### ISSUE THREAD

**Issue by Xarlot** [microsoft/microsoft-ui-xaml#2487]
Please tell me Im doing something totally wrong. 
I can`t even imagine that so long waited WinUI 3 has such terrible and unusable performance

**Steps to reproduce the bug**
Download repo https://github.com/Xarlot/dependencypropertytest
Run WinUI and WPF app

200k dp write
WPF - ~40 ms 
WinUI 3 - ~44500 ms

200k dp read
WPF - 5 ms
WinUI 3 - 18000 ms

**Expected behavior**
WinUI dependency property significantly faster than WPF

**Version Info**
NuGet package version: 
```
    <PackageReference Include="Microsoft.VCRTForwarders.140" Version="1.0.6" />
    <PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview1.200515.3" />
```

Windows version:
Windows 10 Enterprise 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)

As far as i can see from visual studio diagnostics session new marshalling is totally unefficient

**Comment by ranjeshj** [comment]
@bartekk8 @stevenbrix @MikeHillberg @Austin-Lamb

**Comment by robloo** [comment]
> Unmatched Native Performance
WinUI is powered by a highly optimized C++ core that delivers blistering performance, long battery life, and responsive interactivity that professional developers demand. Its lower system utilization allows it to run on a wider range of hardware, ensuring your sophisticated workloads run with ease.
https://microsoft.github.io/microsoft-ui-xaml/

Some work left to do :)

**Comment by stevenbrix** [comment]
There is already an open issue regarding DependencyProperty performance: https://github.com/microsoft/microsoft-ui-xaml/issues/1633

Any problems with closing this one as a dupe?

**Comment by ranjeshj** [comment]
I'll link and up it. I can add the preview tag to that bug. Definitely a work in progress.

**Comment by ranjeshj** [comment]
@Xarlot Thanks for reporting. Lets track it as part of the linked bug since it is the same issue.
