### ISSUE TITLE
KeyboardAccelerators ToolTip is not shown when using x:bind for the Key and Modifiers Properties

### ISSUE THREAD

**Issue by luEbe** [microsoft/microsoft-ui-xaml#2489]
Hello!
I am trying to use a KeyboardAccelerator within a reusable UserControl I wrote. I am now having a problem, when I try to set the Key and Modifiers Properties using x:Bind. The Accelerator works fine, but the ToolTip is not automatically shown, as it would normally be, without using x:Bind.

This is the part in question of my xaml File:
`<Grid.KeyboardAccelerators>
<KeyboardAccelerator Key="{x:Bind ViewModel.AcceleratorKey}" Modifiers="{x:Bind ViewModel.AcceleratorModifiers}" Invoked="{x:Bind ViewModel.NavigateToTarget}"/>
</Grid.KeyboardAccelerators>`

It works just fine when putting the Key and Modifiers directly into the Properties like so:
`<Grid.KeyboardAccelerators>
<KeyboardAccelerator Key="O" Modifiers="Control,Shift" Invoked="{x:Bind ViewModel.NavigateToTarget}"/>
</Grid.KeyboardAccelerators>`

Furthermore, I have already tried to bind them to a string property within my ViewModel, as well as to a VirtualKey and VirtualKeyModifiers property. Both did not work.

My question now is, is there something I am doing wrong, or is it just not possible to do it this way?

**Comment by StephenLPeters** [comment]
I think that this should work, would it be possible to provide a repro app so we can take a look at the issue?

**Comment by luEbe** [comment]
Here is a repro app for the issue:
https://github.com/luEbe/keyboard-accelerators-repro

As you will notice, the KeyboardAccelerator is working fine, but the ToolTip is not shown when hovering over the Grid.

**Comment by luEbe** [comment]
Is there any progress on this issue?

**Comment by stevenbrix** [comment]
Hey @luEbe, sorry for the delay - thanks for opening this issue. We don't have any progress on this issue.

@RealTommyKlein can you take a look and see if this is an x:Bind issue?

**Comment by RealTommyKlein** [comment]
@luEbe @stevenbrix - this does not appear to be specific to x:Bind.  The tooltip is only updated when the `KeyboardAccelerator` enters the visual tree for the first time.  If the `KeyboardAccelerator` properties used to generate the tooltip (e.g. `Key`, `Modifiers`) like are modified after the `KeyboardAccelerator` is in the visual tree, which is the case for x:Bind, the tooltip won't be updated.

**Comment by stevenbrix** [comment]
Thanks for confirming @RealTommyKlein.

@luEbe can you confirm if this repro's with `{Binding}`? Or is this just an issue with `{x:Bind}`?
