### ISSUE TITLE
NavigationView doesn't handle MenuItemsSource changes properly

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#2491]
**Describe the bug**
`NavigationView` doesn't seem to properly handle `MenuItemsSource` changes when the source is a `ObservableCollection`.
In particular I can describe few odd behaviors:
- `Reset` event leaves the list blank
- `Add` event is completely ignored
- Replacing `MenuItemsSource` will trigger some awkward animations
![alt](https://media.giphy.com/media/H1MFoQC0KnfWEPFYrr/giphy.gif)

The animations persist even implementing `IKeyIndexMapping` (that seems to be completely ignored)

**Expected behavior**
- `Add` should make a new menu item appear
- `Reset` should refresh the list taking care of `IKeyIndexMapping`
- Replacing the list should probably not start any animation

**Version Info**
NuGet package version: Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
@FrayxRulez can you please share a repro app ?

**Comment by FrayxRulez** [comment]
Hi Ranjesh, this seems to be actually caused by how I customized the NavigationView. 
I actually modified it to wrap the TopNav into a ScrollViewer, to actually prevent the overflow menu from getting created.

**Comment by ranjeshj** [comment]
Curious why you did that. Another control that is similar but does the scrolling behavior is TabView. @anawishnoff as FYI

**Comment by FrayxRulez** [comment]
I find TabView design too much prominent, as navigation here is secondary in the app. Also we have a design more similar to NavigationView on iOS and Android counterpart apps.
I ended up by making a control that looks exactly the same by myself, but I think it would be nice to have this built in WinUI!

**Comment by StephenLPeters** [comment]
@FrayxRulez did you consider the pivot control? It is close to a TopNav without the overflow.

**Comment by FrayxRulez** [comment]
Hi @StephenLPeters, I honestly consider Pivot quite obsolete in terms of UI, and I don’t use one directly since a long time now. 
There are actually few views in the app where I rather use a headerless Pivot inside a NavigationView.

**Comment by StephenLPeters** [comment]
Fair enough, I'd like to understand the customization that you needed to make and if it is wide spread or unique to your app.

**Comment by FrayxRulez** [comment]
I received multiple requests from users about being able to scroll through NavigationView items rather than accessing them from the overflow menu, I believe it actually feels more immediate when the NavigationView let you access categories that are part of the same data set, examples in my app are chat folders and shared media grouped by type (photo and video, audio, documents...)

**Comment by ranjeshj** [comment]
Adding @anawishnoff @YuliKl and @chigy since we are talking about the design of NavigationView.

**Comment by chigy** [comment]
@FrayxRulez , looks like there is the issue and the request.
In order to make it clear, I'd like to keep this GH for issue and the request be opened as a new item if you wish us to consider it. 1) weird motion issue, 2) make top NavView items scrollable.

Does this sound right?

**Comment by anawishnoff** [comment]
Thanks all - so if I'm understanding correctly, there isn't a bug with NavigationView itself but was caused by wrapping it in a ScrollViewer? @ranjeshj /@ojhad Why does a ScrollViewer block the NavigationView itself from being edited/updated?

As for NavigationView's overflow design, it seems to me that an overflow menu was created so that the difference between left and right or top and bottom pinned menu items was still visible. 

For example, the settings item is always bottom/right pinned on the NavigationView:

![image](https://user-images.githubusercontent.com/22504341/83067260-37dccd80-a01b-11ea-8bae-d545f1e7da9d.png)

If the items scrolled, we would either have to keep settings in a fixed position as the other items scroll (which might be a little awkward) or we'd have to include settings in the overflow menu, which wouldn't make as much logical and visual sense as it's technically its own entity and not a part of the menu items list.
