### ISSUE TITLE
Cannot create WinUI3 C++ app for desktop or UWP

### ISSUE THREAD

**Issue by mariusbancila** [microsoft/microsoft-ui-xaml#2492]
I am trying to create a WinUI 3 Preview 1. I have followed every step for configuring my dev environment from here [https://docs.microsoft.com/en-us/windows/apps/winui/winui3/](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/). I am running on Windows 10 build 18362.

I have installed all the work loads and packages as required. Screenshots of it can be viewed [here](https://pbs.twimg.com/media/EYcwUTZWoAEnHeE?format=png&name=medium).

![screenshots](https://pbs.twimg.com/media/EYcwUTZWoAEnHeE?format=png&name=medium)

When I create either a WinUI 3 C++ project for desktop of UWP I get the following error.

--------------------------- Microsoft Visual Studio ---------------------------

A problem was encountered creating the sub project 'App1'. Project 'App1' could not be loaded because it's missing install components. To fix this launch Visual Studio installer with the following selections: C++ (v142) Universal Windows Platform tools

--------------------------- OK ---------------------------

I have all this. I have uninstalled and reinstalled everything, the same error occurs.

**Comment by MikeHillberg** [comment]
In the Installation Details on the right-hand side of the installer, try checking the 142 option there. It turns on multiple of the individual components.

![image](https://user-images.githubusercontent.com/18429489/82464507-055b2f80-9a73-11ea-8775-8f8d1131168c.png)

**Comment by StephenLPeters** [comment]
If these instructions don't resolve your issue, feel free to reopen.

**Comment by mariusbancila** [comment]
This solution fixed the problem. Thank you.
