### ISSUE TITLE
Error on VSIX install: This extension is not installable on any currently installed products

### ISSUE THREAD

**Issue by simonrhart** [microsoft/microsoft-ui-xaml#2493]
I am trying to install the VSIX from here on my Windows 10 machine: https://marketplace.visualstudio.com/items?itemName=Microsoft-WinUI.WinUIProjectTemplates

And the installer fails with the following log:
20/05/2020 14:53:05 - Microsoft VSIX Installer
20/05/2020 14:53:05 - -------------------------------------------
20/05/2020 14:53:05 - vsixinstaller.exe version:
20/05/2020 14:53:05 - 16.5.2047
20/05/2020 14:53:05 - -------------------------------------------
20/05/2020 14:53:05 - Command line parameters:
20/05/2020 14:53:05 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\sihart\Downloads\WinUI.ProjectTemplates (2).vsix
20/05/2020 14:53:05 - -------------------------------------------
20/05/2020 14:53:05 - Microsoft VSIX Installer
20/05/2020 14:53:05 - -------------------------------------------
20/05/2020 14:53:05 - Skipping product Microsoft.VisualStudio.Product.BuildTools (13d3538a) since it does not support extensions
20/05/2020 14:53:05 - Initializing Install...
20/05/2020 14:53:06 - Extension Details...
20/05/2020 14:53:06 - 	Identifier         : Microsoft.WinUI.ProjectTemplates
20/05/2020 14:53:06 - 	Name               : WinUI 3 Project Templates
20/05/2020 14:53:06 - 	Author             : Microsoft
20/05/2020 14:53:06 - 	Version            : 3.0.0.2005153
20/05/2020 14:53:06 - 	Description        : The Microsoft Windows UI Library (WinUI) Visual Studio extension adds project and item templates to support building WinUI 3 apps and components.
20/05/2020 14:53:06 - 	Locale             : en-US
20/05/2020 14:53:06 - 	MoreInfoURL        : https://github.com/microsoft/microsoft-ui-xaml/
20/05/2020 14:53:06 - 	InstalledByMSI     : False
20/05/2020 14:53:06 - 	SupportedFrameworkVersionRange : [4.5,)
20/05/2020 14:53:06 - 
20/05/2020 14:53:07 - 	SignatureState     : ValidSignature
20/05/2020 14:53:07 - 	SignedBy           : Microsoft Corporation
20/05/2020 14:53:07 - 	Certificate Info   : 
20/05/2020 14:53:07 - 		-------------------------------------------------------
20/05/2020 14:53:07 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
20/05/2020 14:53:07 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
20/05/2020 14:53:07 - 		[Serial Number] : 330000033C51C393599E34695900000000033C
20/05/2020 14:53:07 - 		[Not Before]    : 11/03/2020 18:06:39
20/05/2020 14:53:07 - 		[Not After]     : 05/03/2021 18:06:39
20/05/2020 14:53:07 - 		[Thumbprint]    : F9DFA92ED94D8DFD37D9465D89BBFA260B920287
20/05/2020 14:53:07 - 
20/05/2020 14:53:07 - 	Supported Products : 
20/05/2020 14:53:07 - 		Microsoft.VisualStudio.Community
20/05/2020 14:53:07 - 			Version : [16.7,17.0)
20/05/2020 14:53:07 - 		Microsoft.VisualStudio.Pro
20/05/2020 14:53:07 - 			Version : [16.7,17.0)
20/05/2020 14:53:07 - 		Microsoft.VisualStudio.Enterprise
20/05/2020 14:53:07 - 			Version : [16.7,17.0)
20/05/2020 14:53:07 - 
20/05/2020 14:53:07 - 	References         : 
20/05/2020 14:53:07 - 	Prerequisites      : 
20/05/2020 14:53:07 - 		-------------------------------------------------------
20/05/2020 14:53:07 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
20/05/2020 14:53:07 - 		Name         : Visual Studio core editor
20/05/2020 14:53:07 - 		Version      : [16.0,17.0)
20/05/2020 14:53:07 - 
20/05/2020 14:53:07 - 		-------------------------------------------------------
20/05/2020 14:53:07 - 		Identifier   : Microsoft.VisualStudio.ComponentGroup.UWP.Support
20/05/2020 14:53:07 - 		Name         : Universal Windows Platform tools
20/05/2020 14:53:07 - 		Version      : [16.2.29003.222,17.0)
20/05/2020 14:53:07 - 
20/05/2020 14:53:07 - Signature Details...
20/05/2020 14:53:07 - 	Extension is signed with a valid signature.
20/05/2020 14:53:07 - 
20/05/2020 14:53:07 - Searching for applicable products...
20/05/2020 14:53:07 - Found installed product - Global Location
20/05/2020 14:53:07 - Found installed product - Visual Studio Enterprise 2019
20/05/2020 14:53:07 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

Any idea how to install this?

**Comment by ranjeshj** [comment]
@stevenbrix can you take a look ?

**Comment by MikeHillberg** [comment]
The VSIX requires the preview of Visual Studio 16.7. http://aka.ms/winui3 has a link.

**Comment by simonrhart** [comment]
Excellent, thanks. Can I install the preview of VS along side VS2019 without issue?

**Comment by chingucoding** [comment]
Yes, you can install them side by side.
