### ISSUE TITLE
WinUI Project Templates extension not install able on any currently installed products 

### ISSUE THREAD

**Issue by edcurtin** [microsoft/microsoft-ui-xaml#2494]
**Describe the bug**

Tried to install templates and met with an error Visual Studio Professional 16.5.4 - 2019 - Windows 10 1903

**Steps to reproduce the bug**

Install templates fails

**Expected behavior**

templates should of installed 

20/05/2020 15:06:27 - Microsoft VSIX Installer
20/05/2020 15:06:27 - -------------------------------------------
20/05/2020 15:06:27 - vsixinstaller.exe version:
20/05/2020 15:06:27 - 16.5.2047
20/05/2020 15:06:27 - -------------------------------------------
20/05/2020 15:06:27 - Command line parameters:
20/05/2020 15:06:27 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ed.curtin\Downloads\WinUI.ProjectTemplates.vsix
20/05/2020 15:06:27 - -------------------------------------------
20/05/2020 15:06:27 - Microsoft VSIX Installer
20/05/2020 15:06:27 - -------------------------------------------
20/05/2020 15:06:27 - Skipping product Microsoft.VisualStudio.Product.BuildTools (1d73218c) since it does not support extensions
20/05/2020 15:06:27 - Initializing Install...
20/05/2020 15:06:28 - Extension Details...
20/05/2020 15:06:28 - 	Identifier         : Microsoft.WinUI.ProjectTemplates
20/05/2020 15:06:28 - 	Name               : WinUI 3 Project Templates
20/05/2020 15:06:28 - 	Author             : Microsoft
20/05/2020 15:06:28 - 	Version            : 3.0.0.2005153
20/05/2020 15:06:28 - 	Description        : The Microsoft Windows UI Library (WinUI) Visual Studio extension adds project and item templates to support building WinUI 3 apps and components.
20/05/2020 15:06:28 - 	Locale             : en-US
20/05/2020 15:06:28 - 	MoreInfoURL        : https://github.com/microsoft/microsoft-ui-xaml/
20/05/2020 15:06:28 - 	InstalledByMSI     : False
20/05/2020 15:06:28 - 	SupportedFrameworkVersionRange : [4.5,)
20/05/2020 15:06:28 - 
20/05/2020 15:06:28 - 	SignatureState     : ValidSignature
20/05/2020 15:06:29 - 	SignedBy           : Microsoft Corporation
20/05/2020 15:06:29 - 	Certificate Info   : 
20/05/2020 15:06:29 - 		-------------------------------------------------------
20/05/2020 15:06:29 - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
20/05/2020 15:06:29 - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
20/05/2020 15:06:29 - 		[Serial Number] : 330000033C51C393599E34695900000000033C
20/05/2020 15:06:29 - 		[Not Before]    : 11/03/2020 18:06:39
20/05/2020 15:06:29 - 		[Not After]     : 05/03/2021 18:06:39
20/05/2020 15:06:29 - 		[Thumbprint]    : F9DFA92ED94D8DFD37D9465D89BBFA260B920287
20/05/2020 15:06:29 - 
20/05/2020 15:06:29 - 	Supported Products : 
20/05/2020 15:06:29 - 		Microsoft.VisualStudio.Community
20/05/2020 15:06:29 - 			Version : [16.7,17.0)
20/05/2020 15:06:29 - 		Microsoft.VisualStudio.Pro
20/05/2020 15:06:29 - 			Version : [16.7,17.0)
20/05/2020 15:06:29 - 		Microsoft.VisualStudio.Enterprise
20/05/2020 15:06:29 - 			Version : [16.7,17.0)
20/05/2020 15:06:29 - 
20/05/2020 15:06:29 - 	References         : 
20/05/2020 15:06:29 - 	Prerequisites      : 
20/05/2020 15:06:29 - 		-------------------------------------------------------
20/05/2020 15:06:29 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
20/05/2020 15:06:29 - 		Name         : Visual Studio core editor
20/05/2020 15:06:29 - 		Version      : [16.0,17.0)
20/05/2020 15:06:29 - 
20/05/2020 15:06:29 - 		-------------------------------------------------------
20/05/2020 15:06:29 - 		Identifier   : Microsoft.VisualStudio.ComponentGroup.UWP.Support
20/05/2020 15:06:29 - 		Name         : Universal Windows Platform tools
20/05/2020 15:06:29 - 		Version      : [16.2.29003.222,17.0)
20/05/2020 15:06:29 - 
20/05/2020 15:06:29 - Signature Details...
20/05/2020 15:06:29 - 	Extension is signed with a valid signature.
20/05/2020 15:06:29 - 
20/05/2020 15:06:29 - Searching for applicable products...
20/05/2020 15:06:29 - Found installed product - Global Location
20/05/2020 15:06:29 - Found installed product - Visual Studio Professional 2017
20/05/2020 15:06:29 - Found installed product - Visual Studio Professional 2019
20/05/2020 15:06:29 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by MikeHillberg** [comment]
This VSIX requires the VS preview version of 16.7, or you'll see this message. There's a link at http://aka.ms/winui3
