### ISSUE TITLE
Cannot use PathIconSource for TabViewItem.IconSource

### ISSUE THREAD

**Issue by Hanzalah-Adalan** [microsoft/microsoft-ui-xaml#2495]
When I use `SymbolIconSource` or `FontIconSource` for `TabViewItem.IconSource`, the application is happy.. but when I use `PathIconSource` for example:
        `<MUXC:TabViewItem Header="Bookmarks"
                          IsClosable="False">
            <MUXC:TabViewItem.IconSource>
                <MUXC:PathIconSource Data="M17 3H7c-1.1 0-1.99.9-1.99 2L5 21l7-3 7 3V5c0-1.1-.9-2-2-2z"/>
            </MUXC:TabViewItem.IconSource>
        </MUXC:TabViewItem>`

then I got an exception: "The parameter is incorrect.\r\n\r\nThe parameter is incorrect.\r\n"	System.Exception {System.ArgumentException}

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.2]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by StephenLPeters** [comment]
To be sure, does this same PathIconSource work outside of a Tabview, like in a grid?

**Comment by Hanzalah-Adalan** [comment]
yes it does work outside of a Tabview.. in my case it works fine in `NavigationViewItem`..

**Comment by chingucoding** [comment]
I would like to look into this.

**Comment by chingucoding** [comment]
I think I found the issue, the `PathIcon(Source).Data` property is causing us problems here as it can't be shared, see #827. A possible solution would be to set the icon sources data to null while the TabViewItem consumes it. This of course is not ideal though. Another option would be to copy the data, however I am not quite sure how we would do this.

**Comment by chingucoding** [comment]
While not ideal, I think the "clearing" approach might be the best here given that it can not be shared anyway. If we are not choosing that approach, I would open a PR to at least catch PathIcons and skip them to not cause crashes.
@stmoy What are your thoughts on this?

**Comment by mikernet** [comment]
Just ran into this. Is there a workaround I can use to get it working?
