### ISSUE TITLE
Proposal: Fluid Framework Control

### ISSUE THREAD

**Issue by dpaulino** [microsoft/microsoft-ui-xaml#2503]
# Proposal: FluidView - a control that lets developers add Fluid Framework components easily into their WinUI-based app.

## Summary

With Microsoft's recent announcements of Fluid Framework, it is clear that the future of Office apps, Microsoft 365 apps, and other applications will make use of Fluid Framework components. If we can either make a native-version of this control OR simply make a wrapper control to make it easier to plug Fluid Framework components into apps, it would make WinUI-based apps a viable target for developers that need/want to use Fluid Framework.
![image](https://www.microsoft.com/en-us/microsoft-365/blog/wp-content/uploads/sites/2/2020/05/8-IMAGE_Fluid-Framework.gif)

https://techcommunity.microsoft.com/t5/microsoft-365-blog/introducing-the-first-microsoft-fluid-framework-experiences-in/ba-p/1345543

## Rationale

* Fluid Framework has the potential to become a cornerstone of future application development. A WinUI control for this will ensure that native applications using WinUI remain viable endpoints when creating apps with Fluid Framework.
* This control would help provide solutions for developers who are wanting a way to automatically synchronize data across web and other platforms but are not able to invest in a native implementation. Fluid Framework solves that problem, and so FluidView would let developers use Fluid Framework in their WinUI applications.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to add Fluid Framework based components into their WinUI app | Must |

## Important Notes

- Maybe this control can take advantage of WebView2?

**Comment by BreeceW** [comment]
It would be very encouraging to see a native (not web-based) version of this technology.

**Comment by mdtauk** [comment]
Even if a native control or set of control behaviours is some way off, perhaps something could be done by wrapping a simple WebView control into a control that can have behaviours, properties, and events included, which will make it easy to host Fluid content and experiences in WinUI apps.

**Comment by dpaulino** [comment]
@mdtauk I would not be opposed to that either as a first iteration. Anything to make the process simpler for devs using WinUI. Makes me wonder if WCT would make more sense for a v1 of a control like this.

**Comment by mdtauk** [comment]
I am not immersed in Fluid's code, I assume its web based and uses Javascript.

For native Xaml, I doubt the sum of all of Fluid's capabilities could be wrapped in a single control.  It would need to either wrap around various text, list, and other controls - binding to a Fluid datasource and the Microsoft Graph.
