### ISSUE TITLE
WinUI 3 UWP does not load smoothly like the built-in XAML

### ISSUE THREAD

**Issue by BreeceW** [microsoft/microsoft-ui-xaml#2505]
**Describe the bug**
When a UWP XAML app opens, it shows its splash screen, which then fades away to show the XAML content, already loaded. This does not appear to be happening for WinUI 3 UWP apps, however. WinUI 3 UWP apps show their splash screen, then the icon fades away, leaving the color of the splash screen visible for a noticeable amount of time, and then the XAML content loads. Worse, when splash screen is set to optional, the app pops up with the splash screen’s color before changing to the XAML content (no fade effect, either). This was a great thing about UWP—if your app was lightweight enough, you could have user-percieved instant startup times. I would like to see that returned to WinUI 3.

**Steps to reproduce the bug**

1. Create a WinUI 3 UWP
2. Open it and carefully observe a brief period where the splash screen’s background is the only thing on screen—the fading animation of the app opening is ruined

**Expected behavior**
When a UWP has its splash screen disabled, the app’s content should already be visible *as* the app is animating in. With a splash screen enabled, the XAML should load *underneath* the splash screen and be ready to fade in as the splash screen fades out.

**Screenshots**
With the splash screen set to optional, the effect is particularly pronounced. It is shown below in the animations.
| UWP XAML (no splash screen) | WinUI 3 UWP (no splash screen) |
| :-: | :-: |
| ![UWP XAML](https://user-images.githubusercontent.com/18747724/82496860-627ad380-9abb-11ea-90b7-b9967789c7bd.gif) | ![WinUI 3 UWP](https://user-images.githubusercontent.com/18747724/82496875-6870b480-9abb-11ea-852b-220545ed4b64.gif) |

This issue is much harder to see when there is a splash screen, so I slowed down the recording a lot.
| UWP XAML (splash screen) | WinUI 3 UWP (splash screen) |
| :-: | :-: |
|  ![Slow Splash UWP](https://user-images.githubusercontent.com/18747724/82498188-922adb00-9abd-11ea-840b-65289918dda6.gif) | ![Slow WinUI 3](https://user-images.githubusercontent.com/18747724/82498207-9951e900-9abd-11ea-9219-c27f40f1db0b.gif) |

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by StephenLPeters** [comment]
@jeffstall @MikeHillberg @codendone for FYI, looks like the container animations aren't playing.

**Comment by krschau** [comment]
Closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615). If you are still seeing the behavior with the latest WindowsAppSDK version, please open a new issue.
