### ISSUE TITLE
Question: Do we still need the [Mobile] device form factor in the issue templates?

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2507]
Windows 10 Mobile support ended in January this year. Do we still need the *Mobile* device form factor listed in the issue templates or can we remove it?

![image](https://user-images.githubusercontent.com/1398851/82503843-4e09fb80-9afa-11ea-93f3-3d833d2ccf4a.png)

**Comment by StephenLPeters** [comment]
I think we could probably remove it.

**Comment by Felix-Dev** [comment]
Let me know if I should create a PR to remove it.

**Comment by Felix-Dev** [comment]
Since PR #2696 was merged I'm closing this question.
