### ISSUE TITLE
Calling ApplicationView.GetForCurrentView throws an error

### ISSUE THREAD

**Issue by dstaley** [microsoft/microsoft-ui-xaml#2509]
**Describe the bug**

Calling `ApplicationView.GetForCurrentView()` in `App.OnLaunched()` throws this error:

```
System.Runtime.InteropServices.COMException: 'Element not found. (0x80070490)'
```

**Steps to reproduce the bug**

1. Create a Blank, Packaged WinUI 3 C# app
1. Add the following code to beginning of the `App.OnLaunched` method in `App.xaml.cs`

```
ApplicationView.PreferredLaunchViewSize = new Size(500, 800);
ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.PreferredLaunchViewSize;
ApplicationView.GetForCurrentView().SetPreferredMinSize(new Size(500, 800));
```

**Expected behavior**

App launches without an uncaught exception.

**Version Info**

NuGet package version: 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

This issue does not occur when using the non-WinUI C# Desktop App project template.

**Comment by kmelmon** [comment]
We're also seeing this in react-native scenarios.  See:  https://github.com/microsoft/react-native-windows/issues/5232

**Comment by asklar** [comment]
This is failing because there is no CoreWindow for the calling thread yet. I think it's illegal to call ApplicationView functionality in an app's constructor since the app seems to get constructed before the CoreWindow.

**Comment by asklar** [comment]
filed https://github.com/MicrosoftDocs/winrt-api/issues/1698

**Comment by sigmarsson** [comment]
Acknowledged. The same happing here. I wish to repaint the title bar to harmonize with the theme but it throws the exception;


```
ApplicationViewTitleBar titleBar = ApplicationView.GetForCurrentView().TitleBar;

            if (IsDarkTheme())
            {
                titleBar.ButtonForegroundColor = Colors.White;
            }
            else
            {
                titleBar.ButtonForegroundColor = Colors.Black;
            }

```

**Comment by Bigous** [comment]
More than a year and a half, is there any news about this issue?

**Comment by asklar** [comment]
This is by design, all corewindow APIs are not supported in WinAppSDK. See https://docs.microsoft.com/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#apis-that-have-dependencies-on-uwp-only-ui-features

**Comment by Slion** [comment]
How can be modify the appearance on the title bar on WinUI 3 Desktop then?

**Comment by NPadrutt** [comment]
@Slion  it looks like you would have to extend it yourself: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.extendscontentintotitlebar?view=winui-3.0

**Comment by Slion** [comment]
Thanks for the tip @NPadrutt. I had seen that API since but only now got around trying it.
Here it what it should look like in C#:

```C#
    public sealed partial class MainWindow : Microsoft.UI.Xaml.Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            Title = "My App Title";     
            ExtendsContentIntoTitleBar = true;
            SetTitleBar(iTitleBar);
        }
```

I've added the following title bar as the first row in my XAML grid. Row height was set to auto.
It matches exactly the height off other standard title bars:

```xaml
        <StackPanel x:Name="iTitleBar" Grid.Row="0" Orientation="Horizontal" Padding="8,5,5,6" >
            <Image Source="icon.ico" Width="16" Height="16" />
            <TextBlock Text="My App Title" Padding="10,0,0,0"/>
        </StackPanel>
```
However there is surely a more standard way to do that. What's notably annoying is that the title text color is not dimmed together with the window control buttons when the window loses focus.
