### ISSUE TITLE
ListView SelectedValue/SelectedValuePath binding breaks when the current SelectedItem is removed from the ItemsSource

### ISSUE THREAD

**Issue by shufan** [microsoft/microsoft-ui-xaml#251]
**Describe the bug**
ListView SelectedValue/SelectedValuePath binding breaks when the current SelectedItem is removed from the ItemsSource.

**Steps to reproduce the bug**

1. Go to https://shufantsz.visualstudio.com/_git/ListViewSelectedValueBindingBugReproApp to get the simple App project I created that allows you to easily repro the issue described.
2. F5 deploy the App from VS.
3. Use the available buttons in the test app to add and remove items to the ItemsSource reflected by the existing ListView and manipulate the SelectedItem by setting the SelectedValue binding source property. You'l see that this works properly until you ever remove the current SelectedItem, from that point on, you won't be able to manipulate the selected item anymore by using the buttons to change the SelectedValue binding source property.

**Expected behavior**
What I expect is for the SelectedValue/SelectedValuePath binding to be respected, so that as the Binding source for SelectedValue changes, the SelectedItem in the ListView changes to reflect that.

The expected behavior works fine until the currently SelectedItem is removed from the ItemsSource, from that point on the Binding is no longer respected. Re-setting the binding programatically does cause the binding to begin working again.

**Screenshots**

**Version Info**

NuGet package version: _Wasn't sure where to get this information..._

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18321.rs_shell.190117-1615) | Yes |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Good issue, thanks for reporting it! We'll put this on the backlog.
