### ISSUE TITLE
PreferredLaunchViewSize has no effect

### ISSUE THREAD

**Issue by dstaley** [microsoft/microsoft-ui-xaml#2510]
**Describe the bug**

Setting `ApplicationView.PreferredLaunchViewSize` does not result in the app launching at the provided size on subsequent launches.

**Steps to reproduce the bug**

1. Create a Blank, Packaged WinUI 3 C# app
1. Add the following code to beginning of the `App.OnLaunched` method in `App.xaml.cs`

```
ApplicationView.PreferredLaunchViewSize = new Size(500, 800);
ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.PreferredLaunchViewSize;
```

3. Close the app, and then reopen it

**Expected behavior**

App launches in a 500x800 window

**Actual behavior**

App launches in default window size

**Version Info**

NuGet package version: 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

This issue does not occur when using the non-WinUI C# Desktop App project template.

**Comment by Balkoth** [comment]
Seriously, why release version 1.0 where not even the initial size of the main window can be set?

**Comment by pratikone** [comment]
These apis are not supported in winui 3 . you can refer here : https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api

You can instead use  `Window.Bounds` instead https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.window.bounds?view=windows-app-sdk-1.2#microsoft-ui-xaml-window-bounds.
You can call it in a constructor.

We are working on a good way for the intellisense and compiler to inform users if they are using any unsupported apis. 

Hope this helps :)
