### ISSUE TITLE
WinUI 3 has inferior “scrolling personality” compared to UWP in some scenarios

### ISSUE THREAD

**Issue by BreeceW** [microsoft/microsoft-ui-xaml#2513]
**Describe the bug**
UWP apps on devices with precision trackpads have a silky-smooth feel as you scroll through them with two fingers with a touchpad. It glides down pages and slows down as you release your fingers and bounces when you hit the ends. This experience continues in UWP apps using WinUI 3 in UWP. WinUI 3 apps in Win32, however, have a very choppy feel, where the scrolling does not glide or bounce.

The issues I’m writing about here occur with a precision touchpad. With a Synaptics touchpad (non-precision), the two-finger scrolling is choppy in WinUI 3 UWP, and in WinUI 3 Win32, essentially non-functional (see separate issue https://github.com/microsoft/microsoft-ui-xaml/issues/2482).

To summarize:
| Device | UWP without WinUI | UWP WinUI 3 | UWP Win32 |
| :-- | :-- | :-- | :-- |
| **Precision touchpad** | ✅ Perfect scrolling | ✅ Perfect scrolling | ⚠ Low quality scrolling |
| **Synaptics touchpad** | ✅ Perfect scrolling | ⚠ Low quality scrolling | 🛑 Totally non-functional https://github.com/microsoft/microsoft-ui-xaml/issues/2482 |
| **Scroll wheel** | ✅ Perfect scrolling | ✅ Perfect scrolling | ✅ Perfect scrolling | ✅ Perfect scrolling |
| **Touch screen** | ✅ Perfect scrolling | ✅ Perfect scrolling | ✅ Perfect scrolling | ✅ Perfect scrolling |

**Steps to reproduce the bug**

1. Use a two-finger touchpad on a page with a scroll bar
2. Depending on the scenario in the table, you will witness beautiful, smooth scrolling, or clunky scrolling, or no scrolling

**Expected behavior**
Scrolling with the scroll wheel and touch screen (and just dragging the scrollbar with the mouse) all function as expected already. The main issue is that WinUI 3 Win32 apps do not have high-quality scrolling with precision touchpads. Scrolling should feel the same in WinUI 3 for both UWP and Win32 as it does in UWP XAML for both precision and other touchpads alike.

**Screenshots**
| WinUI UWP | WinUI Win32 |
| :-: | :-: |
|  ![WinUI 3 UWP Scrolling](https://user-images.githubusercontent.com/18747724/82535625-21171200-9b15-11ea-9238-9b5b982375cc.gif) Beautiful, smooth with precision touchpad | ![WinUI 3 Win32 Scrolling](https://user-images.githubusercontent.com/18747724/82535636-27a58980-9b15-11ea-881c-b94f0b0b788b.gif) Choppy, no bounce effect with precision touchpad |

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes (tested Synaptics touchpad)   |
| May 2019 Update (18362)            | Yes (tested precision touchpad) |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by kmgallahan** [comment]
This, #2506, and #2486 seem related in that interactions with WinUI elements running in a Win32 process are rendered at 30 fps. @ranjeshj

**Comment by Poopooracoocoo** [comment]
just while you're here I want to mention that you can't scroll horizontally in task manager and just overall scrolling in win32 apps sucks. Microsoft uses win32, even in new apps like Teams, so they can't just tell you to use WinUI and UWP.

**Comment by lhak** [comment]
Changing the zoom factor of a scrollviewer in a mouse wheel handler is very smooth with the platform XAML in a XAML island but very choppy in winui3 desktop (Preview2)

**Comment by lhak** [comment]
Touchpad scrolling and panning is still broken in preview 3.

**Comment by bkudiess** [comment]
I believe this is working correctly now in Project Reunion latest releases. @BreeceW @lhak Could you guys double check if you still can repro this issue?

**Comment by BreeceW** [comment]
@bkudiess, it looks like everything is working as expected now.

**Comment by bkudiess** [comment]
Thank you for confirming @BreeceW

**Comment by dylech30th** [comment]
It seems that the latest release only brings a good scrolling experience when using the mouse wheel(I haven't tested it on other input devices yet), I've posted a new issue and [linked two videos](https://github.com/microsoft/microsoft-ui-xaml/issues/5850#issuecomment-916816208) that shows the difference when users are scrolling by using the slider in the scroll bar

**Comment by BreeceW** [comment]
This has regressed in 1.2.0-preview1. It’s lost the Precision Touchpad “rubber banding” effect and the “scolling personality” is undone.

**Comment by MikeHillberg** [comment]
@BreeceW, could you open this as a new issue?
