### ISSUE TITLE
How do I get key events?

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#2514]
I have the following to collect keyboard from the window, but it's now working.
```
CoreWindow.KeyDown += CoreWindow_KeyDown;
```
How do I collect input?

**Comment by Felix-Dev** [comment]
Seems to work fine for me. In the following cases, the event is not raised according to the [documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corewindow.keydown?view=winrt-18362):
* Is fired when a non-system key is pressed.
* Apps do not receive this event when an Input Method Editor (IME) is enabled. The Input Method Editor (IME) handles all keyboard input and sets Handled to true.

Does one of these apply in your case?

**Comment by Gavin-Williams** [comment]
OK, I was about to delete this question, because I was being lazy. I need to check the documentation. But thanks for the info - I was worried that I was going to find my whole Platform layer (UWP) not compatible with .Net 5. But if that works, then that's good.

For me, CoreWindow is null.

I've only just loaded the VS template for WinUI for Desktop and added a SwapChainPanel and a couple controls and the single check for keypress.

I don't actually know what an IME is. I've never used it.

**Comment by Felix-Dev** [comment]
@Gavin-Williams Only UWP apps will have a CoreWindow, there is no CoreWindow for WinUI Desktop apps.

**Comment by Gavin-Williams** [comment]
Hmm, that's what I was worried about. So I will have to rewrite a whole heap of code.

**Comment by Felix-Dev** [comment]
@Gavin-Williams This sounds like something [Project Reunion](https://github.com/microsoft/ProjectReunion) can help with (by providing a similar CoreWindow implementation for Win32 apps). Alternatively, the new [WinUI 3 Window class](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/Win32/active/Win32/Window_and_Application_API_Spec.md) (which abstracts both a CoreWindow for UWP apps and a HWND for win32 apps) could expose events like `KeyDown` so you can use the same code for your WinUI UWP and WinUI Desktop apps. The spec is still in the early stages and will continue to be fleshed out.

**Comment by Gavin-Williams** [comment]
@Felix-Dev OK. Thanks for highlighting all that for me. Good to know. In the mean time, I'll have to dig into the preview and see what I can work out.
