### ISSUE TITLE
After list item keyboard reorder operation, -1 is always returned as the index of the item

### ISSUE THREAD

**Issue by bnh2011** [microsoft/microsoft-ui-xaml#2522]
**Describe the bug**

**Steps to reproduce the bug**

1. open Desktop Settings app - ease of access- Narrator and enable Narrator
2. open settings app - time and language - language. Click to add additional languages. Add fr-FR and de-DE
3. user preferred language list will be in the order of 
en-US
fr-FR
de-DE
4. Click de-DE language entry
5. Use keyboard combination (Shift+Alt_Up) to move the language entry up to the second index

Repro: 

**Expected behavior**
Actual: Narrator does not read out the correct strings depending on index
Expecting: Narrator reads out messages corresponding to the index that the listview item was moved to

**Screenshots**

**Version Info**

OS: 10.0.19610.1000.amd64fre.rs_loc_dev3.200415-1700

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19610)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
Not exactly sure if this is a ListView issue or an app issue. Would it be possible for you to create a standalone repro outside of the settings app ? That would be very helpful.

**Comment by brwithro** [comment]
Hi,
This issue still repros in Settings. It does not seem to repro in other apps. I've debugged the issue to a file in the OS repo that apparently doesn't exist in this repo. Would someone be able to look into this?
