### ISSUE TITLE
ContentDialog does not respect BorderThickness

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2525]
**Describe the bug**

The ContentDialog does not respect BorderThickness, setting the BorderBrush does work however
**Steps to reproduce the bug**

1. Create ContenDialog with BorderThickness and BorderBrush set to some value

**Expected behavior**

Both values are respected.
**Screenshots**

**Version Info**

WinUI 2.4.2
NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19628)              | Yes  |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by MikeHillberg** [comment]
A couple of things going on
* The default ContentDialog control template has a root Grid that sets the BorderThickness to a ThemeResource. It should be TemplateBinding it to the ContentDialog's BorderThickness property, and defaulting that property to the ThemeResource
* ContentDialog's behavior changes if it's in a tree or not. If it's not in a tree, setting the resource takes effect. If it's in a tree there's some resizing logic that causes it to get ignored.
