### ISSUE TITLE
WinUI 3 (Desktop) Secondary windows closes the application when try to resize them

### ISSUE THREAD

**Issue by marck7jr** [microsoft/microsoft-ui-xaml#2528]
**Describe the bug**

If I try to resize the main window, all secondary windows closes but the resize action work, but if I try to resize any other window, the application closes without any exception.

**Steps to reproduce the bug**

1. Open any Win32 application with WinUI 3
2. Open any secondary window
3. Try to resize it.

**Expected behavior**

The resize action have to complete successfully.

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 3.0.0-preview1.200515.3]
[Microsoft.VCRTForwarders.140 1.0.6]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041.264)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by kmgallahan** [comment]
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#preview-1-limitations-and-known-issues

> WinUI 3.0 content can only be in one window per process or one ApplicationView per app
