### ISSUE TITLE
Custom VirtualizingLayout crashes the app in Release

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#2531]
**Describe the bug**
I have a custom VirtualizingLayout in my app that works perfectly fine until I compile it release configuration. After (too many) hours trying to figure out what was going on I decided to replace my code with the sample found in [XAML Controls Gallery](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/Common/ActivityFeedLayout.cs) and the issue persists, so I guess this depends on my "outer" XAML setup.
The exception seems to be triggered by `VirtualizingLayoutContext.GetOrCreateElement` that gets invoked in `MeasureOverride`.
The `ItemsRepeater` lives inside a `Pivot` that has `Visibility` set to `Collapsed`, and no crash occurs if `Layout` property is set after a delay (Literally `Task.Delay(2000)`) on control Loaded event.
This is some log printed right before the crash:
`MeasureOverride, availableSize: 344,∞, realizationRect: 0,3.814697E-06,344,473.6, itemCount: 200`

**Steps to reproduce the bug**
Still trying to figure out what's the cause, maybe I'll be able to provide a repro project - If not the main project is open source.

**Expected behavior**
The app won't crash

**Screenshots**

**Version Info**
Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by FrayxRulez** [comment]
I managed to build a repro, launching it in Release configuration should crash the app: [RepeaterCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4669814/RepeaterCrash.zip)

**Comment by FrayxRulez** [comment]
So, I ran the repro project by referencing WinUI source code directly, and the crash actually occurs in my ElementPrepared callback, specifically accessing `ItemsRepeater.ItemsSourceView` generated a invalid cast exception.

**Comment by ranjeshj** [comment]
This seems to be an error with the .net native compilation. If I turn it off, I do not see the crash anymore in release. Can you file this issue in the .net repo ?
![image](https://user-images.githubusercontent.com/28935693/83041489-60ea6780-9ff5-11ea-90ca-cab4288886ca.png)

**Comment by FrayxRulez** [comment]
Here's the follow up ticket: https://github.com/microsoft/dotnet/issues/1210
