### ISSUE TITLE
Question: does/will WinUI support UI remoting?

### ISSUE THREAD

**Issue by ldematte** [microsoft/microsoft-ui-xaml#2533]
In order to facilitate sandboxing and isolation, it is a good idea to isolate components in sandboxes. The historic way of doing it in .NET was using AppDomains, but today the preferred way of doing is just using different processes (more portable/.NET core will not support AppDomains).

The problem is: what about components with UI? All plugin-based systems will need to come up with their own way to support "UI remoting", i.e. rendering in the isolated process and then reporting it back to the main process for the actual UI presentation, in a way similar to Edge/Firefox/Chromium.

WPF provided a solution through INativeHandleContract. Unfortunately, it is heavily dependent on remoting. It could be a good idea to provide a similar API based on some other kind of IPC.

In essence: would it be possible to re-implement Chromium tabs-as-processes using WinUI?

**Comment by mdtauk** [comment]
This could also be very useful for the Windows Terminal, if it ever chooses to support mixing Admin processes in tabs, alongside standard level tabs - or even handling it similar to the "In Private" mode of Edge

**Comment by ranjeshj** [comment]
@MikeHillberg as FYI
