### ISSUE TITLE
AnimatedVisualPlayer - Pause animations when suspended and maybe when minimized

### ISSUE THREAD

**Issue by ajbennet** [microsoft/microsoft-ui-xaml#2534]
**Describe the bug**
Follow XAML policy for pausing animations that cannot be seen. Currently once the animation starts we will cause DWM to wake up 60 times a second even if the app got suspended.

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment]
Unless I am missing something, we already are listening to suspended/resume and stop the animation if needed:

https://github.com/microsoft/microsoft-ui-xaml/blob/36fb735b62b87f9bc1c0f6928d99df77e56abfb7/dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp#L292-L315

Is there an easy way to check whether this is behaving correctly, or do you have scenario where this was not the case @ajbennet ?
