### ISSUE TITLE
MicrQuestion: [The Microfoft.WinUI nuget package is not on nuget.org. Where can I find it?]

### ISSUE THREAD

**Issue by terrycox** [microsoft/microsoft-ui-xaml#2535]

**Comment by terrycox** [comment]
Not well written, my apologies. Here's the question better said. I have a UWP app I wish to upgrade to WinUI 3 Preview 1. For the Alpha, I just used the NuGet manager to add the WinUI prerelease NuGet package. That doesn't work with Preview 1; the package isn't out there. Is it on a restricted server? Also, the 'how to upgrade a UWP project' notes have disappeared; all that's out there now is aimed at desktop apps.

**Comment by chingucoding** [comment]
Turns out the Microsoft.WinUI package is currently unlisted. If you want to use it in an existing UWP projects, you can update the package reference manually.

However currently it is not stable enough to use in production code, and will most likely change in the future or stop working with newer versions of Windows 10 (side effect of the preview 1).

**Comment by terrycox** [comment]
I'm having no luck updating the package reference. Nuget Console Manager 'Find-Package winui' shows the alpha (2.4.2) packages. If you have any specifics I'd be grateful.
The alpha version worked with Nuget; somehow that got dropped with the prerelease version. I find that confusing. 
The loss of the 'how to upgrade a UWP project' notes is also confusing. It seems UWP got pushed aside by the effort to get desktop apps up. But the Nuget issues seem to be there for both.

**Comment by ranjeshj** [comment]
@terrycox Are you trying to create a WinUI3 app ? Have you tried the steps mentioned [here ](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)? Are you building UWP or Desktop WinUI3 app ?

**Comment by terrycox** [comment]
It's a UWP app, and it's attempting to update rather than create a new one from the new templates. Editing the .csproj file worked. 
My primary question was why things went from a NuGet package for the Alpha to your unlisted package for the Preview. Seems regressive.

**Comment by evelynwu-msft** [comment]
This question is no longer relevant since WinUI has long since been made part of Windows App SDK which is delivered through the `Microsoft.WindowsAppSDK` Nuget package.
