### ISSUE TITLE
NavigationViewItem content clipping regression in 2.4.x

### ISSUE THREAD

**Issue by mfeingol** [microsoft/microsoft-ui-xaml#2541]
**Describe the bug**

NavigationViewItem clips its internal contents in 2.4.x much more than 2.3.x. This makes it very difficult to render custom elements in NavigationViewItem alongside standard NavigationViewItem icons. The problem is visible when the NavigationViewItem is in collapsed mode.

The following are screenshots of the NavigationView's PaneFooter:

2.3.2:

![2 3 2](https://user-images.githubusercontent.com/218865/82761908-98b59d00-9db2-11ea-8670-0a8ed78acb48.jpg)

2.4.2:

![2 4 2](https://user-images.githubusercontent.com/218865/82761911-9bb08d80-9db2-11ea-9672-3a11ae3e10ae.jpg)

**Steps to reproduce the bug**

Steps to reproduce the behavior: use this XAML as a NavigationView footer, and compare results between 2.3.x and 2.4.x:

```xml
            <ui:NavigationView.PaneFooter>
                <ui:NavigationViewItem>
                    <StackPanel Orientation="Horizontal" Margin="-6,0,0,0">
                        <ui:PersonPicture PreferSmallImage="True" Height="24">
                            <ui:PersonPicture.ProfilePicture>
                                <BitmapImage UriSource="some source" />
                            </ui:PersonPicture.ProfilePicture>
                        </ui:PersonPicture>
                        <TextBlock Margin="6,0,0,0" VerticalAlignment="Center" Text="some text" />
                    </StackPanel>
                </ui:NavigationViewItem>
            </ui:NavigationView.PaneFooter>
```

**Expected behavior**

Clipping behavior in 2.3.x seems much more sane.

**Screenshots**
See above

**Version Info**
Comparing 2.3.200213001 and 2.4.2.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041)              | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Comment by ranjeshj** [comment]
@mfeingol is this the same as seen in [this ](https://github.com/microsoft/microsoft-ui-xaml/issues/2409)issue ? Does it repro with items only in the pane footer and no other items ?

**Comment by mfeingol** [comment]
@ranjeshj: not sure if it's the same issue.

It repros with with items under `NavigationView.MenuItems` as well as items under `NavigationView.PaneFooter`.

**Comment by chingucoding** [comment]
The root issue is that the we now enforce a margin for the Content presenter, which results in 16px to the right of the content to allow the Expand chevron for hierarchical NavigationViewItems to always be completely visible and not block the NavigationViewItems content.

The question would be: How do we enforce that the expand/collapse chevron has enough space while also not clipping the content of the NavViewItems in Compact.

**Comment by Felix-Dev** [comment]
As the expand/collapse chevron is *not* shown in compact mode with pane closed, we can utilize the work done in PR https://github.com/microsoft/microsoft-ui-xaml/pull/2342 to restore the ContentPresenter margin to its value seen in WinUI 2.3 (and below)
