### ISSUE TITLE
Dynamic assignment to ListView.ContextFlyout may cause ListView to scroll unexpectedly

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#2542]
**Describe the bug**

Consider the following scenario, there is now a file manager, which needs to decide what CommandBarFlyout pops up based on the object selected when right-clicking

The following is pseudo code, where ListViewControl represents ListView, FileFlyout and FolderFlyout are CommandBarFlyout
```csharp
private void ViewControl_RightTapped(object sender, Windows.UI.Xaml.Input.RightTappedRoutedEventArgs e)
{
    if(Target is Folder)
    {
        ListViewControl.ContextFlyout=FolderFlyout;
    }
    else
    {
        ListViewControl.ContextFlyout=FileFlyout;
    }
}
```

### If you comment out the code that changes ContextFlyout, this problem will not be caused

**Expected behavior**

Do not scroll when change ContextFlyout property

**Screenshots**

![GIF 2020-5-25 13-31-41](https://user-images.githubusercontent.com/42038175/82781366-34670c00-9e8c-11ea-814e-b065eecc3c27.gif)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by zhuxb711** [comment]
@ranjeshj 

### Here is an example.
[BugTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4796310/BugTest.zip)
#### After running, first scroll the ListView to the bottom, then scroll up a few lines, and then right-click on the item, you can observe the unexpected scrolling of the ListView. This phenomenon will cause the pop-up position of the right-click menu to not match the position of the item.

**Comment by zhuxb711** [comment]
Is there any solution? What is the cause of this problem?

**Comment by ranjeshj** [comment]
@zhuxb711 This looks like it might be caused by ScrollHeader (with sticky mode) control from the toolkit. It looks like that control is also moving the ScrollViewer content. If I remove the ScrollHeader, I am not able to repro this issue. @Michael-hawker as FYI.

**Comment by zhuxb711** [comment]
@ranjeshj 
After deleting A, indeed all the problems disappeared. But I still need sticky header.
Is there any workaround?

**Comment by ranjeshj** [comment]
This looks like the ScrollHeader control is a bit more aggressive than it needs to be. The fix would have to be in that control. I can't think of an easy way to workaround that.
