### ISSUE TITLE
ComboBox Not Rendering Correctly When ScaleTransform is Applied to Parent Canvas

### ISSUE THREAD

**Issue by Plegin** [microsoft/microsoft-ui-xaml#2544]
- Using VS2019 v16.6.0
- Start a new UWP project
- Use this MainPage Xaml:

<Page
    x:Class="ComboBoxBug.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:ComboBoxBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Canvas RenderTransformOrigin="0.5,0.5">
        <Canvas.RenderTransform>
            <CompositeTransform ScaleX="0.75" ScaleY="0.75"/>
        </Canvas.RenderTransform>
        <ComboBox>
            <ComboBoxItem Content="Item 1"/>
            <ComboBoxItem Content="Item 2"/>
            <ComboBoxItem Content="Item 3"/>
            <ComboBoxItem Content="Item 4"/>
            <ComboBoxItem Content="Item 5"/>
            <ComboBoxItem Content="Item 6"/>
            <ComboBoxItem Content="Item 7"/>
        </ComboBox>

    </Canvas>
</Page>

- Run the app and click on the ComboBox to see that the contents are not rendered correctly and some of the ComboBoxItems cannot be seen or accessed

**Comment by codendone** [comment]
This is a "windowed popup" bug.  If the ComboBox Flyout could be set to ShouldConstraintToRootBounds="true", then the problem wouldn't repro.  The other mode doesn't expect and handle extra scales which may be applied to any ancestor elements.

**Comment by Plegin** [comment]
Thanks for the reply.  Can I expect this new behaviour to be corrected?
