### ISSUE TITLE
[NumberBox] Right-click menu appears when tapping on the spinner using touchscreen (in compact mode)

### ISSUE THREAD

**Issue by niels9001** [microsoft/microsoft-ui-xaml#2546]
**Describe the bug**
When a NumberBox is in compact mode a right-click menu appears when selecting it and sometimes blocking the actual buttons. 

In my opinion, touching the buttons should only show the up and down spinner. Selecting the textbox should show the right-click menu, not the up and down spinners.

**Steps to reproduce the bug**

1. Make sure you have a touch screen.
2. Click on the NumberBox that has Compact mode enabled

**Expected behavior**
The up and down buttons should appear, not the right click menu.

**Screenshots**
![NumberBoxbug](https://user-images.githubusercontent.com/9866362/82827959-5f635700-9eb0-11ea-8fa0-26c123739b79.gif)

**Version Info**
Can be observed in the latest, stable, XAML Controls Gallery app.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041.264 (W10 2004 update))              |  Yes   |

**Device**
Surface Laptop 3 (with touchscreen)

**Comment by shaheedmalik** [comment]
That's not actually the right click menu.
![image](https://user-images.githubusercontent.com/51347950/82841698-0b9f4080-9ea5-11ea-8b04-3d51e286d9ce.png)
Right clicking on it brings up select all.
![image](https://user-images.githubusercontent.com/51347950/82841736-296ca580-9ea5-11ea-9032-405f0fbdc712.png)

I tell you what though; the bug is the menu is blocking the Up arrow on that control.

**Comment by niels9001** [comment]
Ah, yes - my bad.

It's blocking, that's for sure. But I also think that no menu should pop-up whenever tapping the spinner buttons. Only when the text gets selected. It's distracting and unintentional.

**Comment by shaheedmalik** [comment]
> Ah, yes - my bad.
> 
> It's blocking, that's for sure. But I also think that no menu should pop-up whenever tapping the spinner buttons. Only when the text gets selected. It's distracting and unintentional.

That's the problem: it's being selected on first click.

**Comment by ranjeshj** [comment]
It looks like the text gets selected when tapping on the spinner and that causes the floatie to show up. Perhaps the text should not get selected when tapping the spinner.

**Comment by shaheedmalik** [comment]
One tap to activate spinner, another tap to bring up the floatie.
