### ISSUE TITLE
Proposal:  RadialController injection input

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/microsoft-ui-xaml#2548]
# Proposal: RadialController injection input

## Summary

There is a [preview API to inject HID input](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection?view=winrt-18362). Currently the input types are restricted to
- keyboard
- mouse
- gamepad
- pen

It would be great if RadialController (Surface Dial) input could be injected, too. This would enable making non-compatible devices act as RadialController devices via a user-space app instead of writing a driver.

## Rationale

* I put the request in this repository since the [current preview API](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection?view=winrt-18362) is in the `Windows.UI.*` namespace, and there is no good alternative where feedback feels heard
* Would enable people to write e.g. emulators for RadialController without having to resort to driver development (which is a barrier)

## Open Questions

If there is a better place to request this, please let me know. I just do not feel that feedback hub entries with API proposals are responded to, they seem to get lost in the stream of other feedback.

**Comment by ranjeshj** [comment]
can you please file this issue in [this ](https://github.com/microsoft/ProjectReunion)repo ?

**Comment by hansmbakker** [comment]
Done, please see https://github.com/microsoft/ProjectReunion/issues/54
