### ISSUE TITLE
CornerRadius Graphics Corruption

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#2550]
> 
> # Environment
> 
> ```
> Windows build number:  Microsoft Windows NT 10.0.18363.0
> Windows Terminal version (if applicable):  1.0.1401.0
> 
> Been running various graphics tools, half dozen copies of VS, dozens of Chrome tabs, etc.
> ```
> 
> # Steps to reproduce
> 
> I unfortunately don't have clear steps... it just started happening out of the blue.
> 
> I opened terminal and had three tabs open for around 12 hours. In that time i did several commands in each tab and went back and forth between them and other tasks.
> 
> Some time after about 12 hours i looked up and various graphical elements were corrupted.
> # Expected behavior
> 
> Not having the UI corrupted.
> # Actual behavior
> 
> The window frames, tabs, dropdowns, dialogs are corrupted across the terminal:
> 
> ![image](https://user-images.githubusercontent.com/103522/82685169-61f84f00-9c19-11ea-9c2a-780f081f83b9.png)
> 
> ![image](https://user-images.githubusercontent.com/103522/82685202-6f153e00-9c19-11ea-8a8d-785a00e701b6.png)
> 
> ![image](https://user-images.githubusercontent.com/103522/82685120-4ee57f00-9c19-11ea-86b1-1472332fbfcf.png)
> 
> But note that the actual content of the terminal windows are not corrupted:
> 
> ![image](https://user-images.githubusercontent.com/103522/82685420-c9160380-9c19-11ea-8400-3dda6b5a450a.png)
> 
> Note closing and reopening the terminal application didn't fix the corruption.
> 
> No other applications were affected. Visual Studio, Chrome, Skype, Calc, Discord, etc all looked normal and fine.

_Originally posted by @tomspilman in https://github.com/microsoft/terminal/issues/6142_

Refer to that thread for more details. Seem like this isn't local to just the Terminal on @tomspilman's machine, it's happening to all WinUI apps.

**Comment by ranjeshj** [comment]
@codendone @gegao18 Is this a rendering issue ?

**Comment by shaheedmalik** [comment]
I've had similar happen. Explorer crashed soon afterwards. It makes me think it is a Shell issue.

**Comment by tomspilman** [comment]
I can say that i've been running now for a few days with the graphics glitch still occuring.  At no time did the Shell crash on me before or since.  Everything seems stable overall other than this.

I did have a situation a few weeks and at least one reboot ago where the mouse cursor was corrupted on one monitor only.  I had to do the trick of enabling mouse trails to have it fix itself.  Not sure if that is relevant or not.

**Comment by codendone** [comment]
This looks like a Composition issue, and likely something in the graphics driver getting into a bad state.

**Comment by StevenTCramer** [comment]
I have this issue right now.  And after reading this it probably did correlate with updating the Radeon graphics driver.

**Comment by iandk** [comment]
Same issue here
