### ISSUE TITLE
AppBarButton doesn't react to AppBarButtonBackgroundPointerOver when in CommandBar

### ISSUE THREAD

**Issue by ivanicin** [microsoft/microsoft-ui-xaml#2552]
**Describe the bug**
`AppBarButton `doesn't react to `AppBarButtonBackgroundPointerOver `when in `CommandBar`

**Steps to reproduce the bug**

Use this code:
```
    <Grid>
        <CommandBar Background="Transparent">
            <CommandBar.PrimaryCommands>
                <AppBarButton Icon="Add" Label="Add">
                    <AppBarButton.Resources>
                        <SolidColorBrush x:Key="AppBarButtonBackgroundPointerOver" Color="AliceBlue"/>
                    </AppBarButton.Resources>
                </AppBarButton>
            </CommandBar.PrimaryCommands>
        </CommandBar>

    </Grid>
```

**Expected behavior**
The AppBarButton  should have AliceBlue color when the pointer is over

**Screenshots**

![Screenshot (23)](https://user-images.githubusercontent.com/20874207/83013380-357b7300-a01d-11ea-8787-445cfb701c3c.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by ranjeshj** [comment]
CommandBar uses reveal on its children which likely what is causing this. You cannot get both reveal and this color at the same time.

**Comment by chingucoding** [comment]
Having reveal AND custom colors doesn't work, the reveal style ignores those lightweighstyling resources. As @ranjeshj correctly pointed out, the CommandBar sets the style of the AppBarButtons it contains to the reveal style, that is why the color is being ignored. @ranjeshj @StephenLPeters  How should we continue with this issue? Is this a "no fix" then as this is just how CommandBar and revel style works?

**Comment by ivberg** [comment]
Do we know what the status of this is? It seems this is an issue with the latest WinUI3 and not sure what the workaround is? I tried using styles (AppBarButtonBackgroundPointerOver) but they don't seem to be recognized?

https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.appbarbutton?view=winui-3.0
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-styles

**Comment by ivberg** [comment]
Ping to @ranjeshj @StephenLPeters and @chingucoding given previous unanswered Q's on this
