### ISSUE TITLE
WinUI 3 Preview 1, ANGLE.WindowsStore and SwapChainPanel

### ISSUE THREAD

**Issue by hatharry** [microsoft/microsoft-ui-xaml#2558]
I'm trying to use ANGLE.WindowsStore and SwapChainPanel in WinUI 3, this is the function I'm using:

public EGLSurface CreateSurface(SwapChainPanel panel)
{
if (panel == null)
{
throw new ArgumentNullException("SwapChainPanel parameter is invalid");
}
EGLSurface surface = EGL_NO_SURFACE;
int[] surfaceAttributes =
{
EGL_ANGLE_SURFACE_RENDER_TO_BACK_BUFFER, EGL_TRUE,
EGL_NONE
};
PropertySet surfaceCreationProperties = new PropertySet();
surfaceCreationProperties.Add("EGLNativeWindowTypeProperty", panel);
surface = eglCreateWindowSurface(mEglDisplay, mEglConfig, surfaceCreationProperties, surfaceAttributes);
if (surface == EGL_NO_SURFACE)
{
throw new Exception("Failed to create EGL surface"); <--- ERRORS HERE
}
return surface;
}

Using a Universal Windows app the function works fine, but moving to WinUI 3 it fails to create a EGL surface.

**Comment by codendone** [comment]
ANGLE.WindowsStore doesn't currently have any support for WinUI 3.  It would need to optionally support **Microsoft**::UI::Xaml::Controls::ISwapChainPanel in addition to the **Windows**::UI::Xaml::Controls::ISwapChainPanel it supports today.

**Comment by codendone** [comment]
The fix here would be to eventually have ANGLE.WindowsStore updated to also support WinUI 3.  Since that is external from any work in this project, I'm going to close this as external.

**Comment by hummeleBop** [comment]
ANGLE could be really useful for Winui 3 though.
Too bad, the developers behind google angle don't plan to work on this feature.

**Comment by rick-palmsens** [comment]
To quote [this blog post](https://clarkezone.github.io/angle/2020/02/24/angle.html):
> Microsoft is an official contributor to the project ...

It would be nice if Microsoft could update their patch to also work on WinUI.
Waiting for google to feel the need to update it is probably going to take a long time, while Microsoft should have more intensive to get GPU acceleration for libraries such as SkiaSharp up and running.

**Comment by gmurray81** [comment]
I think this is really important guys. It would be very good to be able to get GPU acceleration in WINUI in SkiaSharp.
