### ISSUE TITLE
Proposal: Add acrylic to CalendarView

### ISSUE THREAD

**Issue by licanhua** [microsoft/microsoft-ui-xaml#256]
# Proposal: Add acrylic to CalendarView

## Summary

Adding acrylic on transient UI as we now have the principled approach.
CalendarView is a transient UI that we add acrylic too.
TBD

## Rationale

TBD

## Functional Requirements

TBD 

## Important Notes

TBD

## Open Questions

TBD

**Comment by kikisaints** [comment]
@kimsealls - you might want to also take a look at this.
I know we discussed the "older" acrylic designs from a few releases ago - would you still want us to go with those? If so I can send them over to licanhua to get started on.

**Comment by mdtauk** [comment]
I am guessing this is when the Calendar View is displayed as a flyout, and not when placed as a control?

**Comment by kikisaints** [comment]
Closing this as I don't believe it's necessary or relevant anymore.

**Comment by mdtauk** [comment]
> Closing this as I don't believe it's necessary or relevant anymore.

Was it decided that the control in a flyout, shouldn't use acrylic?  What changed between when it was suggested and now?

**Comment by kikisaints** [comment]
Closed for a few reasons: 

1. We don't have the design resources at this time to give us visuals for an acrylic one and a non acrylic one.
2. CalendarView is currently suffering from "incomplete" visuals in this department which led to the removal of day item spacing in preparation for an acrylic that didn't get implemented (going to log a separate issue on "reverting" the visuals so they're actually more legible).
3. Both the flyout calendarview and the inline calendarview share the same template, so I cannot in good conscious prescribe a "CalendarView" to use acrylic when doing so will make the inline one not follow the guidance correctly. I'm erring on the side of more visibility versus less in this case.

**Comment by mdtauk** [comment]
> Closed for a few reasons:
> 
> 1. We don't have the design resources at this time to give us visuals for an acrylic one and a non acrylic one.
> 2. CalendarView is currently suffering from "incomplete" visuals in this department which led to the removal of day item spacing in preparation for an acrylic that didn't get implemented (going to log a separate issue on "reverting" the visuals so they're actually more legible).
> 3. Both the flyout calendarview and the inline calendarview share the same template, so I cannot in good conscious prescribe a "CalendarView" to use acrylic when doing so will make the inline one not follow the guidance correctly. I'm erring on the side of more visibility versus less in this case.

If only it was as simple as setting the Background brush resource to Transparent, and using an Acrylic flyout for the Calendar Form control.  Acrylic for all flyouts would be consistent with guidelines and the intention of using it for transient UI.

Maybe a WinUI 3.x option in the future.
