### ISSUE TITLE
Narrator reading wrong index for Hierarchical Navigation items.

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#2560]
Navigate to any navigation view item in the XCG and notice that narrator reads "n of n" instead of "i of n".  You can also see this behavior in the MuxControlsTestApp on the "Hierarchical NavigationView DataBinding Test" page when selecting "Menu Item 17"

ported from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/26617531)

**Comment by StephenLPeters** [comment]
@ranjeshj This seems bad to me, I think it is a candidate for cherry picking.

**Comment by ranjeshj** [comment]
Agree. @ojhad one more your way.
