### ISSUE TITLE
SvgImageSource never renders

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#2565]
**Describe the bug**

In a WinUI 3 preview 1 desktop application, an `<Image source="Foo.svg" />` never draws correctly and instead renders a grey box.

**Steps to reproduce the bug**

Add an svg as an asset to the spares package named "/Assets/image.svg"

Create an `Image` element in the XAML:

```xaml
<Image Source="ms-appx:///Assets/image.svg" />
```

I believe the problem is that it only attempts to set the client render size once at startup when ActualWidth/ActualHeight is 0; future attempts to set the client render size are always no-op. My workaround was two-fold, first use a `.Loaded` event to recreate the `SvgImageSource` with either a made-up client render size > 0 or using (if now available) ActualWidth/ActualHeight to create a new `SvgImageSource` with the client render size set (note: it must be a new image source, changes to it have no effect if it was previously initialized with 0), then I use `.Resized` to change the client render size based off the new width/height.

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview1.200515.3]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by codendone** [comment]
Thanks for the detailed description!  SVG works fine in a UWP for Preview 1, but definitely has this problem for desktop apps.  I believe you correctly identified this as a sizing issue.

**Comment by ranjeshj** [comment]
This issue should be fixed in WinUI3 Preview2. Thanks!
