### ISSUE TITLE
overscroll gets stuck when you move your cursor quickly (touchpad)

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#2567]
**Describe the bug**

overscroll can get stuck when you move your cursor quickly (touchpad)

**Steps to reproduce the bug**

1. Open something you can scroll. Let's go with the start menu
2. Scroll down a little bit using your touchpad (by moving your fingers up w/ default settings)
3. Scroll up (by moving your fingers down w/ default settings) and let go then quickly move your cursor

**Expected behavior**

it would go back down, just like it does when you do not quickly move your cursor. Note that scrolling usually stops when you move the cursor and that it should stay like that. I'm only talking about overscroll. I think that WinUI handles this now but I honestly have no idea.

**Screenshots**

Normal: 
![image](https://user-images.githubusercontent.com/51363864/83212792-d136eb80-a1a3-11ea-8bca-621b4da0bc10.png)

Bug: 
![image](https://user-images.githubusercontent.com/51363864/83212794-d3994580-a1a3-11ea-93fe-32a03e498fa8.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update | Yes |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
@Poopooracoocoo We are having trouble reproducing this issue, if you could provide a recording of your repro that might be helpful for us. You can record your screen using Gamebar (invoked by windows key + G) or powerpoint.  Also, what version of Windows are you running on?

**Comment by Poopooracoocoo** [comment]
@StephenLPeters idk if a screen recording will be very useful but ok. and wow. gamebar and powerpoint are what y'all recommend? i used sharex for this one:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51363864/83593696-b9df7000-a5a0-11ea-9e19-bdef5fff8e56.gif)

I usually encounter this in the start menu but it happens in any UWP/XAML/WinUI (I don't really know the difference) app.

**Comment by ranjeshj** [comment]
@RBrid any thoughts ?

**Comment by RBrid** [comment]
@ranjeshj, no idea unfortunately. I think this would require a lengthy investigation.

**Comment by Poopooracoocoo** [comment]
I'm pretty sure this has to do with scrolling stopping once you move your cursor (as I mentioned in the issue)

**Comment by Poopooracoocoo** [comment]
Any updates on this issue now that WinUI 3.0 is headed for release?

**Comment by RBrid** [comment]
@ojhad , @ranjeshj , @Poopooracoocoo , I just tried to repro in Windows 11's Settings app, and yes I can easily run into this situation:

- using two fingers overpan the ScrollViewer content down with the trackpad.
- release the fingers and while the content moves back up quickly click on it with the trackpad.

Result: the content stops instead of animating back all the way!

**Comment by Poopooracoocoo** [comment]
>release the fingers and while the content moves back up quickly click on it with the trackpad.

For me I don't need to click on it. You just need to move your cursor.

**Comment by Poopooracoocoo** [comment]
Do not close

**Comment by DmitriyKomin** [comment]
@Poopooracoocoo, thank you for reporting this. Unfortunately we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).

We tried this on WinAppSDK 1.5 / WinUI3 Gallery and the issue does not appear to repro. If you find that it does still repro in WinAppSDK, please comment here and we will revisit.
