### ISSUE TITLE
IconSources don't respect Style values

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#2568]
I just realized that I [can't style an Icon/IconSource](https://stackoverflow.com/questions/41116779/fonticons-style-override-by-local-properties), when I get the `FontIconSource` from the developer's XAML it's fixed at `20` for `FontSize`, any amount of style I have in my template is ignored and won't inherit or override that FontSize value, even if I call `ClearValue` on the FontIcon, as that just sets it back to 20...

For instance if I have the following XAML:
```xml
<Page
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Page.Resources>
        <FontIconSource FontFamily="Segoe MDL2 Assets" Glyph="&#xE115;" x:Key="MyFontIconSource"/>
        <x:Double x:Key="MyTextSize">64</x:Double>
    </Page.Resources>

    <Grid Padding="40">
        <ContentPresenter FontSize="{StaticResource MyTextSize}">
            <StackPanel>
                <IconSourceElement IconSource="{StaticResource MyFontIconSource}"/>
                <TextBlock>Text</TextBlock>
            </StackPanel>
        </ContentPresenter>
    </Grid>
</Page>
```

The TextBlock value respects the parent FontSize value (set or from style), but the IconSourceElement does not, event though I didn't specify a `FontSize` property in the resource (if I did, I'd expect it to use that like other style/override scenarios).

_Originally posted by @michael-hawker in https://github.com/microsoft/microsoft-ui-xaml/issues/1494#issuecomment-635744690_

**Comment by michael-hawker** [comment]
It's odd too that these two scenarios produce different results because of this:

![image](https://user-images.githubusercontent.com/24302614/83309697-d35a7380-a1be-11ea-9306-e0dd2c55786d.png)

```xml
      <AutoSuggestBox QueryIcon="Setting" Margin="0,0,0,16"/>
      <AutoSuggestBox>
        <AutoSuggestBox.QueryIcon>
          <IconSourceElement>
            <SymbolIconSource Symbol="Setting"/>
          </IconSourceElement>
        </AutoSuggestBox.QueryIcon>
      </AutoSuggestBox>
```

So even those these both end up as `SymbolIcon` the one coming from an IconSource doesn't respect the `FontSize` of the ContentPrenter.

![image](https://user-images.githubusercontent.com/24302614/83309667-b887ff00-a1be-11ea-8289-67c96d05fc84.png)

**Comment by chingucoding** [comment]
@StephenLPeters @michael-hawker There also is the MUXC FontIconSource, which seems to respect the property properly as it passes all properties down to the generated FontIcon. This issue however is about the WUXC FontIconSource. Does it make sense to keep this issue open as with WinUI 3, those would be unified, and then we would use the MUXC FIS which works correctly?
