### ISSUE TITLE
AddWebAllowedObject dictates project structure, unusable

### ISSUE THREAD

**Issue by avakhrushev** [microsoft/microsoft-ui-xaml#2571]
**Describe the bug**
AddWebAllowedObject API is allowed to impose requirements on the project structure, unusable unless abided
See [https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.addweballowedobject#remarks](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.addweballowedobject#remarks)
the "must be imported from a Windows Runtime component" part.

**Steps to reproduce the bug**
1. Use AddWebAllowedObject API as described to register a "web-allowed" object, but in the same (single) app assembly.
2. Make calls from JS to the registered object
3. Observe the object receiving no calls

**Expected behavior**
3. API should allow establishing functioning JS-native interop channels without requiring the addition of Components, or any structural changes to a project.

**Additional context**
Class attributes and related security considerations themselves might make sense in their respective areas, but the way they are let to affect this particular API is destructive, making hacks look more appealing than the intended way, in some cases turning it completely unusable.
Generally speaking, APIs that dictate project structure is not something that should exist. It looks as if the implementation simply was made public before it could be brought to a complete resolution, and whatever unsolved issues left were just dumped off into Remarks.

The ScriptNotify, an alternative way of receiving calls from JS, is also verily limited and not usable in every case, looks obsolete. Is probably supereseded by AddWebAllowedObject, which would make the latter being accessible even more important.

**Comment by michael-hawker** [comment]
🦙 @adambarlow has the `AddRemoteObject` for WebView2 been added yet to play with? Do we know if it'll have the same restriction or will be more flexible as WebView2 targets .NET as well for Win32 apps?

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by mqudsi** [comment]
FWIW, [this is my implementation of AddWebAllowedObject](https://gist.github.com/mqudsi/ceb4ecee76eb4c32238a438664783480) marshalling through JSON and and using `WebMessageReceived` that does not place any restrictions on project design and works with WebView2.

**Comment by adambarlow** [comment]
As we move investments to WinUI 3 and WebView2 we will not be doing feature investments here in WebView as requested in this issue.

**Comment by michael-hawker** [comment]
@adambarlow did preview4 ship a version of [`AddHostObjectToScript`](https://docs.microsoft.com/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript) to the WinUI version of WebView2? (It was hard to find the WinUI specific version of the [docs here](https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.controls.webview2?view=winui-3.0-preview), but I'm not sure if they're complete?)

I think it'd be good to ask @avakhrushev if the new version of this method is less restrictive and meets their needs vs. closing this out. I think it's been clearly communicated that future investments are being done on WebView2, but that doesn't mean the base scenarios related to WebView are completely invalidated.

**Comment by michael-hawker** [comment]
Ah, just found this issue here saying it's not working still in preview4: https://github.com/microsoft/microsoft-ui-xaml/issues/4377
