### ISSUE TITLE
x:Bind inside a ResourceDictionary but outside a DataTemplate does not work

### ISSUE THREAD

**Issue by matthew4850** [microsoft/microsoft-ui-xaml#2573]
**Describe the bug**
If you have a ResourceDictionary with a code-behind and you try to x:Bind one element to the property of another but are not inside a data template it will generate a bad g.cs file that does not compile. It seems to assume the ResourceDictionary is a FrameworkElement as it uses the Loading property.

**Steps to reproduce the bug**
Create a ResourceDictionary with a code-behind.
Then create two elements, one with an x:Name and the other binding to that x:Name.

**Expected behavior**
It successfully x:Binds.

**Screenshots**
Used xaml code.
![image](https://user-images.githubusercontent.com/40522069/83298602-ac1a9b00-a1ec-11ea-9486-24dbebd1d730.png)
Error inside generated .g.cs file
![image](https://user-images.githubusercontent.com/40522069/83298696-cbb1c380-a1ec-11ea-93d1-9fa6321d4acf.png)

**Version Info**
MinSDK: 15063
TargetSDK: 18362

**Comment by alexdi220** [comment]
Hi @matthew4850 
I've noticed that you used the x:Name instead of x:Key. Try to replace it.

**Comment by michael-hawker** [comment]
Is this related to https://github.com/microsoft/microsoft-ui-xaml/issues/2508?
