### ISSUE TITLE
Question: How to use WinUI 3 XAML islands in an unpackaged WPF project?

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#2574]
A .NET Core WPF project uses `<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">` with `<UseWpf>true</UseWpf>` , but that conflicts with the application definition that is added by including `<PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview1.200515.3" />` 

Is there a way to use the WinUI 3 package to host XAML islands in a WPF .NET Core app (i.e. with the WindowsDesktop SDK)?

**Comment by StephenLPeters** [comment]
@MikeHillberg and @JesseCol for FYI

**Comment by mqudsi** [comment]
If you use the four separate projects approach with a regular UWP app hosting `XamlApplication`, the instantiation of the UWP app in `Program.cs` is rejected because `IXamlMetadataProvider` is now provided by WinUI, and there's no way to reference it without adding WinUI 3 to the WPF Core project (which again is not allowed).

It might be necessary to move `IXamlMetadataProvider` to a different assembly so that it can be referred to by WPF Core apps, although I would much provide an approach that didn't require **four** projects to host MUXC XAML in a WPF Core application.
