### ISSUE TITLE
No intellisense support in xaml editor

### ISSUE THREAD

**Issue by KirillPom** [microsoft/microsoft-ui-xaml#2578]
![image](https://user-images.githubusercontent.com/65759581/83361217-cd67bc80-a38f-11ea-8dd7-600984aea2df.png)

There is no intellisense support in xaml editor.
Not showing any controls.

I created just blank C# winui app (packaged)

**Comment by FrayxRulez** [comment]
You might want to take a look at the release notes before opening issues: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#preview-1-limitations-and-known-issues

**Comment by KirillPom** [comment]
Sorry, but "Intellisense is incomplete" doesn`t mean to me "Intellisense not working at all"

**Comment by StephenLPeters** [comment]
This is a known issue with preview1.

**Comment by stevenbrix** [comment]
Closing this since as of 16.8 the xaml intellisense in VS has been fixed.
