### ISSUE TITLE
EffectiveViewportChanged performance disruption

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#2580]
**Describe the bug**
Hooking `EffectiveViewportChanged` to a `ItemsRepeater` children will cause the scrolling to lag in a distruptive way, even when the `ItemTemplate` only contains a `Grid`

**Steps to reproduce the bug**

1. Add a ItemsRepeater to your view
2. Hook `EffectiveViewportChanged` to its `ItemTemplate` root
3. Try to scroll the list

**Expected behavior**
The app performances won't get affected by the scrolling

**Version Info**

NuGet package version: 
- [x] Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
This is a follow up to https://github.com/microsoft/microsoft-ui-xaml/issues/2540

**Comment by StephenLPeters** [comment]
@ranjeshj for FYI. I'm not sure if this is on repeaters side or the EffectiveViewPortChanged API

**Comment by ranjeshj** [comment]
ItemsRepeater just consumes EffectiveViewport framework feature. This sounds more like a perf issue with having many elements hookup to the EffectiveViewportEvent. I'm curious if we are doing extra transforms for each hookup as opposed to caching the viewport at the common parent.
