### ISSUE TITLE
Focus is on the list rather than on the menu when right clicking links

### ISSUE THREAD

**Issue by dmnmsc** [microsoft/microsoft-ui-xaml#2581]
Right click a link and try to navigate through menu with arrow keys: will move the list instead of menu.

Right click a message and try to navigate through menu with arrow keys: will work as expected.

![YVDRn7S1Qg](https://user-images.githubusercontent.com/8472142/83425858-98f70d80-a42e-11ea-9322-fed1ccdf51c0.gif)

Expected behavior:
Right clicking links working as right clicking messages. 

Device: Windows 10 pro November 2019 Update (18363). Desktop.

**Comment by StephenLPeters** [comment]
Flyout from text has the correct behavior, flyout from the link should match
