### ISSUE TITLE
NavigationView causes startup time increase by ~40ms when updating from WinUI 2.0

### ISSUE THREAD

**Issue by joseartrivera** [microsoft/microsoft-ui-xaml#2582]
**Describe the bug**
NavigationView causes startup time increase by ~40ms when updating from WinUI 2.0

**Steps to reproduce the bug**
1. Clone the [Windows Calculator repo](https://github.com/microsoft/Calculator)
2. Build Calculator based on Commit [5dcfdd4](https://github.com/microsoft/calculator/commit/5dcfdd4ae020ba90bdd4796953e11e22a91977e2) to measure performance with WinUI 2.0
3. Build Calculator based on commit Commit [9b7834f](https://github.com/microsoft/calculator/commit/9b7834fdc97d02a3cb8d4928c82b474c1146c7ea) to measure performance with WinUI 2.1
4. Use [MeasureAppStartupTime](https://gist.github.com/mcooley/86450e22ee0a8ffb6430ccec74317234) to get a quick reading on launch performance, notice ~40 ms difference. More instructions on how to use in issue Microsoft/Calculator#939

**Version Info**
I have also reproduced this regression using the latest 2.4.0 and 2.4.2 WinUI nuget packages.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by StephenLPeters** [comment]
@bartekk8 you might have insight into how to track down this issue?

**Comment by StephenLPeters** [comment]
@ojhad and @ranjeshj for FYI

**Comment by ranjeshj** [comment]
@ojhad and @bartekk8 tracked this down to the point where we added top nav which increased the number of elements in each NavViewItem. x:Load/pruning the elements in each Item are some options.
