### ISSUE TITLE
XAML generator error when DataTemplate is in ResourceDictionary

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2586]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1057560/xaml-generator-error-when-datatemplate-is-in-resou.html)._

---
There are no errors when when the very same DataTemplate resides in the page XAML file.

---
#### Visual Studio Feedback System on 6/1/2020, 00:48 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mc0re** [comment]
I'm pretty sure I also posted a screen shot of the problem...

**Comment by ranjeshj** [comment]
@mc0re unfortunately there isn't enough information in this issue to make it actionable. can you provide a repro or more details ?

**Comment by mc0re** [comment]
Please find the provided screen shot in the ticket mentioned above,

**Comment by StephenLPeters** [comment]
I'm sorry, I don't see any screenshots in the attached link. could you put the screenshot in this github issue?
