### ISSUE TITLE
Animate TabView tab resizing

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2588]
This is a tracking/follow up issue for #2569 .
When the pointer leaves, we should animate the width change instead of having the items jump to their new width.

Context:

![gif](https://user-images.githubusercontent.com/16122379/83306756-76cd7780-a203-11ea-8724-a68f617a8c31.gif)

![gif](https://user-images.githubusercontent.com/16122379/83307001-f2c7bf80-a203-11ea-9d06-35de199957ea.gif)

**Comment by shaheedmalik** [comment]
Good job with the previous changes. Yep, it should animate.

**Comment by StephenLPeters** [comment]
I'm not sure that we have the tools to do this easily with list view.

**Comment by mdtauk** [comment]
> I'm not sure that we have the tools to do this easily with list view.

Items Repeater?

**Comment by ranjeshj** [comment]
@mdtauk Yes, ItemsRepeater can help with animations here and that is being tracked by a relatively large work item.
