### ISSUE TITLE
Windows.UI.Xaml.dll gives error 0xc000027b

### ISSUE THREAD

**Issue by shmykelsa** [Microsoft/microsoft-ui-xaml#259]
Windows.UI.Xaml.dll gives error 0xc000027b
Little background:

yesterday I had a Skype group video chat and my PC gave me 3/4 times a GSOD (can't find the dumps, though) VIDEO SCHEDULER INTERNAL ERROR.

Since yesterday I'm having a pretty annoying bug, or shall I say two:

A lot of UWP crash at start (calculator, mail, Unigram etc.).
When searching something with Cortana, the font is weird. It looks like times new roman.
Closer inspection, and every time bug #1 occurs, Windows.UI.Xaml.dll gives an error.

Windows.UI.Xaml.dll, version: 10.0.17763.292
Exception code: 0xc000027b
Directory of the module generating the error: C:\Windows\System32\Windows.UI.Xaml.dll

And along with these errors, some .NET Runtime errors 1026

framework version: v4.0.30319
Exception: System.IO.FileNotFoundException
in MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32)
in MS.Internal.Text.TextInterface.FontFamily.GetFirstMatchingFont(MS.Internal.Text.TextInterface.FontWeight, MS.Internal.Text.TextInterface.FontStretch, MS.Internal.Text.TextInterface.FontStyle)
in MS.Internal.Text.TextInterface.FontFamily.get_Metrics()
in MS.Internal.FontFace.PhysicalFontFamily.MS.Internal.FontFace.IFontFamily.LineSpacing(Double, Double, Double, System.Windows.Media.TextFormattingMode)
in MS.Internal.TextFormatting.SimpleTextLine..ctor(MS.Internal.TextFormatting.FormatSettings, Int32, Int32, System.Collections.ArrayList, Int32 ByRef, Int32 ByRef, Double)
in MS.Internal.TextFormatting.SimpleTextLine.Create(MS.Internal.TextFormatting.FormatSettings, Int32, Int32, Double)
in MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(System.Windows.Media.TextFormatting.TextSource, Int32, Int32, Double, System.Windows.Media.TextFormatting.TextParagraphProperties, System.Windows.Media.TextFormatting.TextLineBreak, System.Windows.Media.TextFormatting.TextRunCache)
in MS.Internal.TextFormatting.TextFormatterImp.FormatLine(System.Windows.Media.TextFormatting.TextSource, Int32, Double, System.Windows.Media.TextFormatting.TextParagraphProperties, System.Windows.Media.TextFormatting.TextLineBreak, System.Windows.Media.TextFormatting.TextRunCache)
in System.Windows.Controls.TextBlock.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.Controls.Grid.MeasureCell(Int32, Boolean)
in System.Windows.Controls.Grid.MeasureCellsGroup(Int32, System.Windows.Size, Boolean, Boolean, Boolean ByRef)
in System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.Controls.Grid.MeasureCell(Int32, Boolean)
in System.Windows.Controls.Grid.MeasureCellsGroup(Int32, System.Windows.Size, Boolean, Boolean, Boolean ByRef)
in System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
in System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.Controls.Border.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.Controls.Control.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.Controls.Grid.MeasureCell(Int32, Boolean)
in System.Windows.Controls.Grid.MeasureCellsGroup(Int32, System.Windows.Size, Boolean, Boolean, Boolean ByRef)
in System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement, System.Windows.Size)
in System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.Controls.Border.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.Controls.Control.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size)
in System.Windows.FrameworkElement.MeasureCore(System.Windows.Size)
in System.Windows.UIElement.Measure(System.Windows.Size)
in System.Windows.ContextLayoutManager.UpdateLayout()
in System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
in System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
in System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
in System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
in System.Windows.Interop.HwndTarget.OnResize()
in System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
in System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
in MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
in MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
in MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

Here's the things I've tried so far:

Reset each and every app I've found affected by this
Windows Apps Troubleshooter (absolutely no effort from it)
sfc scannow
Dism repair
Reset of Windows Apps through Powershell
In-place re-installation
None of the above worked. Can someone help me figure out how to solve these issues?

**Comment by jevansaks** [comment]
Hi @shmykelsa, thanks for reporting this. If you grabbed the error code out of event viewer, could you past the full text of the Windows Error reporting from the event? There is a GUID (long string of hexadecimal with some dashes) that could be useful for correlating to get us some more info.

Or, if you are getting this by attaching a debugger to the process could you make sure to attach with Native Debugging enabled and get the full native stack as well?

From your description it sounds like something may be wrong with some font files on your machine.

**Comment by jevansaks** [comment]
Actually if you file your issue in Feedback Hub (use a title that includes the word "crash" and it will associate recent crash dumps with your feedback item) then provide the URL to the feedback item here I can help follow up on it and make sure it gets to the appropriate team.

**Comment by shmykelsa** [comment]
Hi @jevansaks and thank you for your follow up.

Fortunately, the problem was solved by an update (KB4480056) but for the sake of diagnosing the problem, here are three XMLs of the problem.

By the way, Feedback Hub had the exact same problem, so I wouldn't have been able to open a feedback. But I'm doing it now.

[Examples.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2828255/Examples.zip)

**Comment by jevansaks** [comment]
Unfortunately I wasn't able to correlate that event with any crash data. Hopefully you're unblocked now?
