### ISSUE TITLE
WinUI 3 VSIX project templates cause Properties dialog to not display

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/microsoft-ui-xaml#2591]
VS 16.7 preview 2, created several simple projects from WinUI 3 preview VSIX templates. Right-clicking on the app’s csproj project node causes the project context menu to appear. But selecting Properties, nothing happens - no dialog.

Issue was originally opened in VS feedback, but they determined this is due to the WinUI VSIX:
[Project context menu does not launch Properties dialog](https://developercommunity.visualstudio.com/content/problem/1044553/project-context-menu-does-not-launch-properties-di.html)

**Comment by JeanRoca** [comment]
Closing as just validated this has been fixed as of WinUI 3 Preview 3.
