### ISSUE TITLE
Edit and Continue doesn't work when using DeviceFamily-Xbox folder

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#2600]
Open a new solution.
Create a “DeviceFamily-Xbox” folder.
Copy your “MainPage.xaml” file in that folder.
Launch the app on Xbox One.
Try modifying something on the “MainPage.xaml” under “DeviceFamily-Xbox” folder.

Result: Edit and Continue cannot find elements to update.

**Comment by antoniovecchio** [comment]
Please resolve it ASAP, it's so frustrating!

**Comment by StephenLPeters** [comment]
Is this issue specific to a version of Winui or is it present in system xaml as well?

**Comment by ranjeshj** [comment]
@fabiant3 as FYI

**Comment by fabiant3** [comment]
@chabiss , @maxbrister could you take a look?

**Comment by maxbrister** [comment]
@fabiant3 Source info reported to VS excludes the DeviceFamily-XBox folder. It looks like an OS bug to me.
