### ISSUE TITLE
Does WinUI support multiple languages now ? It seems x:Uid doesn't work

### ISSUE THREAD

**Issue by DaZiYuan** [microsoft/microsoft-ui-xaml#2602]
The same code works in UWP

**Comment by StephenLPeters** [comment]
Could you please provide more information about what is not working for you? Is this specific to the Winui3 preview, or a particular version of winui 2?

**Comment by DaZiYuan** [comment]
Hi StephenLPeters,
I try to make app localizable with Winui3 preview but doesn't work.
the code in below picture works in UWP but not in Winui3 preview.
![image](https://user-images.githubusercontent.com/80653/83827438-f16d2a00-a710-11ea-86f5-0127de2ffcab.png)

**Comment by StephenLPeters** [comment]
Thanks, that helps route the issue to the right spot :)

**Comment by abhi-msft** [comment]
@StephenLPeters : Not sure I understand on why this is closed. Is it fixed? I am using Preview 2 and its not working for me.

**Comment by StephenLPeters** [comment]
> @StephenLPeters : Not sure I understand on why this is closed. Is it fixed? I am using Preview 2 and its not working for me.

This issue is not closed.

**Comment by abhi-msft** [comment]
Thank you!

**Comment by Palatis** [comment]
as a workaround, use full path for `x:Uid`.
for example, given `<ProjectDir>/Strings/<Language>/<ResourceFileName>.resw`:
| key | value |
| :--- | :----- |
| TextBlock1.Text | Test123 |

do this in your `Whatever.xaml`:
```<TextBlock x:Uid="[ProjectName]/[ResourceFileName]/TextBlock1"/>```

**Comment by stevenbrix** [comment]
@alwu-msft is this a known issue?

**Comment by alwu-msft** [comment]
This should be functional, without need for workarounds, as of Preview 3.

**Comment by JKwarn** [comment]
Where is the tutorial located?about WinUI support multiple languages.

**Comment by ghost1372** [comment]
@Palatis  Your solution does not work. Can you create a sample?

**Comment by ghost1372** [comment]
> Where is the tutorial located?about WinUI support multiple languages.

Look here
https://github.com/microsoft/WindowsAppSDK-Samples

But no xUid was used and the translation was done in c# code

**Comment by Palatis** [comment]
> @Palatis  Your solution does not work. Can you create a sample?

i dunno, maybe something changed internal.

**Comment by ghost1372** [comment]
Oh oh
I think the problem was solved  And this issue can be closed 😁
I used the following and everything works fine

`<TextBlock  x:Uid="TextBlock1"/>`

|key|value|
|-|-|
|TextBlock1.Text|Test123|

The point is that I did not pay attention to the last part TextBlock1.**Text**

![image](https://user-images.githubusercontent.com/9213496/132977791-d54a1d19-f525-4a9f-98a8-5cf19e5ecafe.png)

i tested in version 1.0.0-experimental1
@StephenLPeters  i think you can close this issue and related issues

**Comment by HavenDV** [comment]
How can I control the language used to get values for x:Uid for unpackaged Desktop apps?

**Comment by duanqn** [comment]
> Oh oh I think the problem was solved And this issue can be closed 😁 I used the following and everything works fine
> 
> `<TextBlock x:Uid="TextBlock1"/>`
> 
> key	value
> TextBlock1.Text	Test123
> The point is that I did not pay attention to the last part TextBlock1.**Text**
> 
> ![image](https://user-images.githubusercontent.com/9213496/132977791-d54a1d19-f525-4a9f-98a8-5cf19e5ecafe.png)
> 
> i tested in version 1.0.0-experimental1 @StephenLPeters i think you can close this issue and related issues

I can't get this to work on my computer with latest stable 1.0.0. Can we get a full example somewhere?

**Comment by sakurai-5317** [comment]
This probably needs to be reopened.  Under windowsappsdk1.1.3, the minimal example does not work:
```
<Page
    x:Class="TestWinUI.Views.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid x:Name="ContentArea">
        <TextBlock x:Uid="AppDisplayName.Text" />
    </Grid>
</Page>
```
And in Strings/en-us/Resources.resw:
```
<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="AppDisplayName" xml:space="preserve">
    <value>TestWinUI</value>
  </data>
	<data name="AppDescription" xml:space="preserve">
		<value>TestWinUI</value>
  	</data>
  <data name="Shell_Main.Content" xml:space="preserve">
    <value>Main</value>
  </data>
</root>
```

**Actual**: The `<TextBlock>` is empty.
**Expected**: The `<TextBlock>` says `TestWinUI`.

**Comment by evelynwu-msft** [comment]
@sakurai-5317 The name of the string resource in the `.resw` needs to include the name of the property you are specifying a value for, e.g.
```xml
<data name="AppDescription.Text" xml:space="preserve">
  <value>TestWinUI</value>
</data>
```

**Comment by AndrewKeepCoding** [comment]
I'm working on this [NuGet package](https://github.com/AndrewKeepCoding/AK.Toolkit#-localizer) for dynamic localization and it works for me. 😎
