### ISSUE TITLE
NumberBox Font size not change the text inside the editor

### ISSUE THREAD

**Issue by chinkan** [microsoft/microsoft-ui-xaml#2603]
**Describe the bug**
I cannot change the font size of the NumberBox

**Steps to reproduce the bug**
1. Add NumberBox to Page
2. Set the attribute FontSize to any size.

**Expected behavior**
The size of the UI and the number text will be change.

**Actual behavior**
Only the UI box changed and the number text nothing change.

**Screenshots**
![2020-06-04_112518](https://user-images.githubusercontent.com/16433287/83711713-88c17700-a656-11ea-83d3-f5b7862f1125.png)
`<muxc:NumberBox x:Name="WaterLevelBox" Header="Water Level:"
                SmallChange="1"
                LargeChange="5"
                Minimum="0"
                FontSize="72"
                SpinButtonPlacementMode="Inline"/>`

**Version Info**
UWP target version: 10.0.18362
Microsoft.UI.Xaml version: 2.4.2 (from nuget)

Gallery version (found on Settings page): 
1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] November 2019 Update (18363)
- [x] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by chingucoding** [comment]
Seems like we are just missing a template binding. Should be an easy issue to fix.

**Comment by StephenLPeters** [comment]
@MikeHillberg Does FontSize, FontFamily, etc. flow down the tree or do we need to explicitly template bind them?

**Comment by MikeHillberg** [comment]
Yes, generally all of the text properties should inherit down the element tree.
