### ISSUE TITLE
Add button to test app that set's inner frame size to CI dimensions

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2604]
The CI pipeline renders the app in a certain size which is smaller than most devices. This results in some pages not working as expected because they work differently in the CI because of the different rendering sizes.

The exact value of the rendered innerframe in CI has to be determined, but as @kmahone mentioned, it is probably something around 1024x768 .

**Comment by StephenLPeters** [comment]
Sounds like a good idea to me.
