### ISSUE TITLE
NavigationView‘s style changed again?

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#2608]
I update winui from 2.3 to 2.4, and I found my code not works.
```
var obj = TreeHelper.FindChildByName(ShellPage.shellPage.ViuNavigationView, "MenuItemsHost") as MUXC.NavigationViewList;
if (obj != null)
{

}
```

So guys, I remember the left nav list control changed history:
`ListView` ----> `NavigationViewList` ----> `ItemsRepeater`

Do you have any detailed plan about where this control go.

**Comment by mdtauk** [comment]
NavigationView was/is being moved from a ListView to an ItemsRepeater

**Comment by hupo376787** [comment]
So how to get all items of an `ItemsRepeater`.
I can easily get all items of a `ListView` using `foreach (var item in ListView.Items)`.

**Comment by StephenLPeters** [comment]
@ojhad and @ranjeshj FYI

**Comment by ranjeshj** [comment]
@hupo376787 can you describe/share your markup and what you intend to do with the items ?

**Comment by hupo376787** [comment]
Hi, @ranjeshj . I'm customizing 'NavigationView' to Xbox. On Xbox, I need to set item's focused foreground/backfround color, and unfocused foreground/backfround color, for example, when the focus moves from one item to another.

So I need to manually set these color, then I need to get all the items.

**Comment by mdtauk** [comment]
> Hi, @ranjeshj . I'm customizing 'NavigationView' to Xbox. On Xbox, I need to set item's focused foreground/backfround color, and unfocused foreground/backfround color, for example, when the focus moves from one item to another.
> 
> So I need to manually set these color, then I need to get all the items.
> 
> ![image](https://user-images.githubusercontent.com/14960168/84241171-b49a9c00-ab31-11ea-8d5d-e6b3096ce77c.png)
> ![image](https://user-images.githubusercontent.com/14960168/84241197-bf553100-ab31-11ea-933b-1a58fb2039d8.png)


Can you not do that by changing the control's styling by overriding ThemeResources?

- **NavigationViewItemBackground**
- **NavigationViewItemBackgroundPointerOver**
- **NavigationViewItemBackgroundSelected**
- etc...

**Comment by hupo376787** [comment]
Hi, guys. I tried long time ago, but I forgot the details. I'll try later.

Another question is how to set the focus to the specified item, ie, if my focus now is in settings, I want to set focus the `Setting` `NavigationViewItem`.

**Comment by mdtauk** [comment]
@hupo376787  When you say focus, are you separating the Focus of a NavigationViewItem, from the Selection of the NavigationViewItem?

Are you using the Focus Indicator values as recommended for the Xbox UI?
https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal-focus

```Xaml
<!-- App.xaml -->
<Application.Resources>

    <!-- Override Reveal Focus default resources. -->
    <SolidColorBrush x:Key="SystemControlRevealFocusVisualBrush" Color="{ThemeResource SystemBaseHighColor}"/>
    <SolidColorBrush x:Key="SystemControlFocusVisualSecondaryBrush" Color="{ThemeResource SystemAccentColor}"/>
</Application.Resources>
```

**Comment by hupo376787** [comment]
CLosed now, thx. I will try again later.
