### ISSUE TITLE
Question: WinUI3 dispatchers (And why is Window.Current null in Desktop?)

### ISSUE THREAD

**Issue by tomasfabian** [microsoft/microsoft-ui-xaml#2609]
I wanted to create a Rx DispatcherScheduler for WinUI 3 Preview 1 based on [UWP implementation](https://github.com/dotnet/reactive/blob/7ad606b3dcd4bb2c6ae9622f8a59db7f8f52aa85/Rx.NET/Source/src/System.Reactive/Platforms/UWP/Concurrency/CoreDispatcherScheduler.cs), but the static readonly property Window.Current is null. How should I or the Rx team get the corresponding CoreDispatcher?

**Steps to reproduce:**

1. Create new Blank App, Packaged (WinUI in Desktop) app

2. Open MainWindow.xaml.cs and try get Window.Current

**Expected behavior:**

Window.Current in Blank App, Packaged (WinUI in UWP) returns a window instance

**Comment by Felix-Dev** [comment]
Your stated expected behavior (WinUI UWP) does not match your bug description (WinUI Desktop). Is that intended? 

`Window.Current` only returns a window instance when called from an UWP app's UI thread. In all other cases it returns `null`, including WinUI Desktop apps.

The CoreDispatcher is only available for UWP apps currently. Can you use the [Dispatcher class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher?view=netcore-3.1) from .NET instead?

**Comment by tomasfabian** [comment]
@Felix-Dev sorry I probably confused you, I didn't state that it's a bug, it was just my expectation.

I tried to get the dispatcher from .NET as you kindly suggested me. This returned null:
```C# 
var dispatcher = Windows.Threading.Dispatcher.FromThread(Thread.CurrentThread);
```
but I was able to get the dispatcher like this:
```C# 
var dispatcher = Windows.Threading.Dispatcher.CurrentDispatcher;
```

I have to admit that I'm confused, because I checked that for example a text box returns a CoreDispatcher from it's Dispatcher property:
```C#
Windows.UI.Core.CoreDispatcher dispatcher = MyTextBox.Dispatcher
```

I'm used from WPF that this is true:
```C#
System.Windows.Threading.Dispatcher.FromThread(Thread.CurrentThread) == MyTextBox.Dispatcher
```

Isn't that CoreDispatcher confusing in WinUI Desktop apps, if it's only used in UWP apps currently?

Thank you, Tomas

**Comment by weltkante** [comment]
Your steps to reproduce are
> Packaged (WinUI in **Desktop**) app

But you say your expectation is
> Packaged (WinUI in **UWP**) returns a window instance

As such you are mixing up UWP/Desktop packaging in your issue description and were asked to clarify which of them is actually your problem.

**Comment by tomasfabian** [comment]
Packaged (WinUI in Desktop) app is my actual problem. 
Packaged (WinUI in UWP) was an example how it could behave in Packaged (WinUI in Desktop), too.

**Comment by tomasfabian** [comment]
@Felix-Dev 
> Your stated expected behavior (WinUI UWP) does not match your bug description (WinUI Desktop). Is that intended?

Yes it was intended, but it is obviously confusing, sorry again. 

So my main issue was to get the correct current dispatcher for switching from a background thread to the main UI thread. I wanted to use Window.Current.Dispatcher for that purpose in a Packaged  (WinUI in Desktop) app, but it was null.

**Comment by Felix-Dev** [comment]
@tomasfabian Interesting that you get a valid `CoreDispatcher` reference when accessing `MyTextBox.Dispatcher` in a WinUI Desktop app! I honestly thought a `CoreDispatcher` was related to a `CoreWindow` and as WinUI Desktop apps don't have a CoreWindow (they directly use the classic HWND) I was under the impression that there won't be a `CoreDispatcher` then for WinUI Desktop apps. If I'm wrong here and this caused you additional confusion I would like to apologize!

**Comment by MikeHillberg** [comment]
In a UWP WinUI app there's guaranteed to be one Window on the UI thread, because multiple windows aren't supported. To create a second Window you need to create a new thread. So Window.Current returns the Window on the calling thread.

In a Desktop WinUI app, in the current preview only one Window can be created, but the plan is to allow multiple Windows to be created on the same thread. So Window.Current doesn't make sense any longer, and now just returns null. (It's behavior is unchanged in a UWP app.)

About dispatchers, CoreDispatcher only works in a UWP app, but [DispatcherQueue](https://docs.microsoft.com/uwp/api/Windows.System.DispatcherQueue) always works. DispatcherQueue isn't new to the WinUI preview, it's been around for a while, but what is new in the preview is that Xaml elements (and Window) have a DispatcherQueue property so that you can get one for any element.

**Comment by tomasfabian** [comment]
@Felix-Dev that's alright. Your constructive explanation was actually very helpful for me to learn that there is another (not used?) core dispatcher in the Desktop version which misled me.  

**For all** I'm going to change the title to WinUI 3 dispatchers (Why is Window.Current null?) if it's not a problem for anyone.

I realize now, based on the information gathered by you, that my original question should be split to two issues (these issues are coupled via Dispatcher property):

1. Window.Current is not self explanatory in my opinion. @MikeHillberg explained to us that it produces different results in both platforms and the behavior in Desktop WinUI will probably change. What kind of behavior should we expect from MAUI integration (Android/iOS etc)? 

Originally I used Window.Current only to get the dispatcher, but it was null (and of type CoreDispatcher).

2. It would be great to have a unified (cross-platform) dispatcher provider.  
I learnt that MyTextBox.Dispatcher is a CoreDispatcher used only in UWP, but the DispatchedHandler agileCallback passed to RunAsync was called in the main thread.
```C#
    public async void Init()
    {
      await MyTextBox.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
       {
       });
    }
```

@MikeHillberg DispatcherQueue is not new in WinUI, but its new for new/adapting developers.
```C#
          DispatcherQueueSyncContext.Current.Post(c =>
          {
          }, null);
```
```C#
          var t = DispatcherQueue.CreateTimer();

**Comment by MikeHillberg** [comment]
You're right that the DispatcherQueue isn't new, what's new to WinUI3 is that Xaml elements have a DispatcherQueue property. This works whether in a UWP or Desktop app, whether C++ or C#.

.Net has the similar but abstract concept of a SynchronizationContext, and in WinUI3 an implementation is provided that wraps the current thread's DispatcherQueue. As a result, in a c# app there's two ways to post:

```c#
        public MainWindow()
        {
            this.InitializeComponent();

            SynchronizationContext.Current.Post(
                (o) => Debug.WriteLine("Sync Context"),
                null);

            this.DispatcherQueue.TryEnqueue(() => Debug.WriteLine("Dispatcher Queue"));
        }
```

**Comment by tomasfabian** [comment]
I found `DispatcherQueue.GetForCurrentThread`, this works in **Desktop**:
```C#
      var dispatcherQueue = DispatcherQueue.GetForCurrentThread();

      dispatcherQueue.TryEnqueue(() => Debug.WriteLine("Dispatcher Queue"));

      var timer = dispatcherQueue.CreateTimer();
      timer.Interval = TimeSpan.FromSeconds(2);
      timer.Tick += Timer_Tick;
      timer.Start();
```

@MikeHillberg you wrote that DispatcherQueue works also in **UWP**. I tried it and the methods are marked as Experimental. I would usually do this with MVVM, but I tried the code bellow to verify where will be the continuation executed and in **UWP** it was on a worker thread, not on main thread:
```C#
      await Window.Current.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
          {
            myButton.Content = "Updated content";
          });
```
In spite of that it was successfully updated. Interesting... Thank you

**Comment by sjb-sjb** [comment]
@MikeHillberg , you commented that "CoreDispatcher only works in a UWP app". Noting it will also work on a WinUI 3 desktop app that is in an MSIX package. To access the CoreDispatcher, create a Window in OnLaunched, assign the Content of the window to be a UI element ("rootElement"), and subscribe to the Activated event of the Window. Then in the Activated event, test that the WindowActivationState is CodeActivated or PointerActivated and access rootElement.Dispatcher (not Window.Dispatcher).

**Comment by Gavin-Williams** [comment]
Seems like it might be mighty sensible to make UWP and desktop behave the same way and have the same capabilities with regard to Windows. UWP is just a security model after all, not a model for application design.

**Comment by sjb-sjb** [comment]
@Gavin-Williams i agree they should do that as far as possible, including setting Window.Current equal to the first Window that is created (or the first in order of creation among all remaining windows). It might be a bigger challenge for the application lifecycle ... should be doable for a packaged desktop application though.

**Comment by sjb-sjb** [comment]
@MikeHillberg  what I don’t understand about using DispatcherQueue instead of CoreDispatcher is that DispatcherQueue.TryEnqueue returns synchronously but CoreDispatcher.RunAsync returns an awaitable. How should I achieve the same effect as RunAsync using DispatcherQueue?

**Comment by MikeHillberg** [comment]
I would use a Semaphore and wait on it from the non-UI thread. CoreDispatcher.RunAsync can be a bit difficult to use, because it returns/completes early if the code itself makes an async call.

@scott-moore-ms  FYI

**Comment by sjb-sjb** [comment]
@MikeHillberg I did it with a TaskCompletionSource, which is a bit lighter-weight than Semaphore. 

As a philosophical comment, it seems funny to have the Windows.UI.Core namespace mixed up in the signatures in WinUI.

**Comment by MikeHillberg** [comment]
@sjb-sjb, about WinUI referencing types in Windows.UI.Core: WinUI isn't meant to be a complete stack; it's a layer. So it references types in Windows.UI.Core, Windows.Storage, Windows.Media, etc.

**Comment by sigmarsson** [comment]
I witness too `Window.Current` is null even on the UI thread :

https://github.com/unoplatform/uno/issues/5642

Win UI desktop is launched as a Uno Head.

**Comment by sigmarsson** [comment]
As for this null reference matter, I found this. They differentiate for net5 and Windows : 

![image](https://user-images.githubusercontent.com/43340959/113407967-b4b0a480-93ae-11eb-90a1-9bd45e404885.png)

**Comment by MikeHillberg** [comment]
In WinUI2 most UI objects have a [CoreDispatcher](https://docs.microsoft.com/uwp/api/Windows.UI.Core.CoreDispatcher), like [DependencyObject.Dispatcher](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.DependencyObject.Dispatcher).

In WinUI3 we've moved to CoreDispatcher's successor: [DispatcherQueue](https://docs.microsoft.com/uwp/api/Windows.System.DispatcherQueue). So you should be able to get that for WinUI3?

**Comment by tinmac** [comment]
@MikeHillberg yeah thanks appreciate that, ive managed to sus it out. I added the DispatcherQueue as a property on my VM. Was a little to used to 'the WPF way'

**Comment by tinmac** [comment]
@MikeHillberg  I was generally using MVVM LIght's DispatcherHelper & forgot just how much it was doing & how helpful it was 😉

**Comment by eduardobragaxz** [comment]
Is there an alternative for Window.Current.Content for WinUI 3?

**Comment by KangUnia** [comment]
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#core-unsupported-classes

I don't understand.

        protected InputCursor ProtectedCursor
        {
            get
            {
                return IUIElementProtectedMethods.get_ProtectedCursor(_objRef_global__Microsoft_UI_Xaml_IUIElementProtected);
            }
            set
            {              IUIElementProtectedMethods.set_ProtectedCursor(_objRef_global__Microsoft_UI_Xaml_IUIElementProtected, value);
            }
        }

this is protected 
not public 
cannot be used

How do I use it?
Cursor should change when using this 'PointerPressed' function

Why did you make this?

**Comment by castorix** [comment]
>     protected InputCursor ProtectedCursor
>     {
>         get
>         {
>             return IUIElementProtectedMethods.get_ProtectedCursor(_objRef_global__Microsoft_UI_Xaml_IUIElementProtected);
>         }
>         set
>         {              IUIElementProtectedMethods.set_ProtectedCursor(_objRef_global__Microsoft_UI_Xaml_IUIElementProtected, value);
>         }
>     }
> ```
> 
> this is protected not public cannot be used
> 
> How do I use it? Cursor should change when using this 'PointerPressed' function

With Reflection

**Comment by eduardobragaxz** [comment]
> Is there an alternative for Window.Current.Content for WinUI 3?

I found my way around _my_ issue by getting the XamlRoot.
