### ISSUE TITLE
Microsoft.UI.Xaml.Controls.NumberBox does not use "number" as it's input scope

### ISSUE THREAD

**Issue by baleszkr** [microsoft/microsoft-ui-xaml#2610]
According to the documentation on [https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/number-box](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/number-box): _"Number will be used for the input scope. This input scope is intended for working with digits 0-9. This may be overwritten but alternative InputScope types will not be explicitly supported"_

When the NumberBox implemented, the touch keyboard shows the default keyboard, which gives me suspicion that the InputScope is not set to Number.

I am using library version 2.4.2, on windows 10.0.18362 on a tablet in Kiosk mode.

**Comment by Felix-Dev** [comment]
@baleszkr This is being tracked by issue #1912 and PR #2605.

**Comment by StephenLPeters** [comment]
closing as duplicate
