### ISSUE TITLE
NavigationViewItem.MenuItems not working in markup why?

### ISSUE THREAD

**Issue by tharun916** [microsoft/microsoft-ui-xaml#2612]

**Comment by StephenLPeters** [comment]
@tharun916 thanks for the feedback, could you please include the markup which is not working so we can better understand the issue?

**Comment by tharun916** [comment]
<Page
    x:Class="App14.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App14"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Windows.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <muxc:NavigationView>
        <muxc:NavigationView.MenuItems>
            <muxc:NavigationViewItem Content="Home" Icon="Home" ToolTipService.ToolTip="Home"/>
            <muxc:NavigationViewItem Content="Collections" 
                            Icon="Keyboard" ToolTipService.ToolTip="Collections">

                <muxc:NavigationViewItem.MenuItems>
                    <muxc:NavigationViewItem Content="Collections" 
                            Icon="Keyboard" ToolTipService.ToolTip="Collections"/>
                </muxc:NavigationViewItem.MenuItems>
                
            </muxc:NavigationViewItem>
        </muxc:NavigationView.MenuItems>
        
    </muxc:NavigationView>
    
</Page>

**Comment by ranjeshj** [comment]
@tharun916 can you post a screenshot of what you are seeing when using this markup and what you expect it to show ?

**Comment by tharun916** [comment]
![nav](https://user-images.githubusercontent.com/34917430/84900047-2ee59600-b0c7-11ea-9450-aaa021b86ef2.png)

**Comment by chingucoding** [comment]
@tharun916 If you want a NavigationViewItem to not have children, you will need to remove:
```xaml
<muxc:NavigationViewItem.MenuItems>

</muxc:NavigationViewItem.MenuItems>
```

If you specify that without adding content, unfortunately, the XAML won't compile as it is not valid markup.

**Comment by Felix-Dev** [comment]
@tharun916 Please make sure you are using WinUI **2.4** or newer. Your posted XAML markup works fine for me:
![image](https://user-images.githubusercontent.com/1398851/84902159-bd005300-b0ac-11ea-8d0b-dbd5441ef7cc.png)

> If you specify that without adding content, unfortunately, the XAML won't compile as it is not valid markup.

@chingucoding Seems to work just fine for me (app compiles and runs correctly):
![image](https://user-images.githubusercontent.com/1398851/84902520-339d5080-b0ad-11ea-89e9-b52abff40579.png)

**Comment by chingucoding** [comment]
Oh ignore my comment then, thanks for correcting me @Felix-Dev !

**Comment by tharun916** [comment]
i want add children for NavigationViewItem  .. give me a sample solution

**Comment by Felix-Dev** [comment]
@tharun916 Are you using either WinUI **2.4.x** or WinUI **2.5 Preview**? These are the WinUI versions with hierarchical NavigationView support. Other WinUI versions - such as WinUI 2.3 or WinUI 3 Preview 1 don't have support for this feature. (See for example the missing [Platform features](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#missing-platform-features) of WinUI 3 Preview 1).

**Comment by tharun916** [comment]
> @tharun916 Please make sure you are using WinUI **2.4** or newer. Your posted XAML markup works fine for me:
> ![image](https://user-images.githubusercontent.com/1398851/84902159-bd005300-b0ac-11ea-8d0b-dbd5441ef7cc.png)
> 
> > If you specify that without adding content, unfortunately, the XAML won't compile as it is not valid markup.
> 
> @chingucoding Seems to work just fine for me (app compiles and runs correctly):
> ![image](https://user-images.githubusercontent.com/1398851/84902520-339d5080-b0ad-11ea-89e9-b52abff40579.png)

its not  working for me . im using WinUi 2.4 pls give a sample project

**Comment by Felix-Dev** [comment]
@tharun916 Here's a sample project:

[HierarchicalNavView.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4792888/HierarchicalNavView.zip)

It's using the exact same XAML Markup for the NavigationView you have posted above. WinUI 2.4.2 is used.

**Comment by tharun916** [comment]
ya it's working perfectly now .thank you @Felix-Dev

**Comment by Felix-Dev** [comment]
It seems this issue can be closed then.

**Comment by StephenLPeters** [comment]
Thanks!

**Comment by Dreller** [comment]
Hi, how may I check which version of WinUI my project is currently using ?  I have a similar issue and I would like to see if I'm on WinUI 2.4.2.
Thanks!

**Comment by chingucoding** [comment]
You can check by right clicking the solution file in solution view and clicking "Manage NuGet packages for solution...". In there, you open the "Installed" tab and need to find the Microsoft.UI.Xaml package. There, you can see which version you are using:
![Screenshot of Microsoft.UI.Xaml package in list of packages showing version 2.5.0](https://user-images.githubusercontent.com/16122379/110235770-29b8c780-7f32-11eb-8ada-f1b7b009ef4a.png)

**Comment by Dreller** [comment]
> You can check by right clicking the solution file in solution view and clicking "Manage NuGet packages for solution...". In there, you open the "Installed" tab and need to find the Microsoft.UI.Xaml package. There, you can see which version you are using:
> ![Screenshot of Microsoft.UI.Xaml package in list of packages showing version 2.5.0](https://user-images.githubusercontent.com/16122379/110235770-29b8c780-7f32-11eb-8ada-f1b7b009ef4a.png)

Thank you very much @chingucoding  !  It didn't solved my issue so it must be elsewhere.  At least, now I know how to manage NuGet Packages Versions!
Thanks!

**Comment by chingucoding** [comment]
Hmm unfortunate to hear that it didn't solve the issue, if you suspect it is an issue with WinUI feel free to create an issue! Happy to hear that you now know how to manage NuGet package versions @Dreller!
