### ISSUE TITLE
x:Bind and ItemsControl behaves weirdly with null values

### ISSUE THREAD

**Issue by BioTurboNick** [microsoft/microsoft-ui-xaml#2614]
**Describe the bug**
If an ItemsControl finds a null in its ItemsSource, it will instead bind the item to the ItemsControl's DataContext.

Note: I was directed here from https://developercommunity.visualstudio.com/content/problem/760441/xbind-and-itemscontrol-behaves-weirdly-with-null-v.html

**Steps to reproduce the bug**
XAML:
```
<Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <ItemsControl ItemsSource="{x:Bind Foos, Mode=OneWay}">
            <ItemsControl.ItemTemplate>
                <DataTemplate x:DataType="local:Foo">
                    <ItemsControl ItemsSource="{x:Bind Values, Mode=OneWay}"/>
                </DataTemplate>
            </ItemsControl.ItemTemplate>
        </ItemsControl>
    </Grid>
</Page>
```

CS:
```
namespace App1
{
    public class Foo
    {
        ObservableCollection<int?> _Values = new ObservableCollection<int?>();

        public ReadOnlyObservableCollection<int?> Values;

        public Foo()
        {
            Values = new ReadOnlyObservableCollection<int?>(_Values);
            _Values.Add(null);
            _Values.Add(5);
            _Values.Add(null);
        }
    }

    public sealed partial class MainPage : Page
    {
        ObservableCollection<Foo> _Foos = new ObservableCollection<Foo>();

        public ReadOnlyObservableCollection<Foo> Foos;

        public MainPage()
        {
            Foos = new ReadOnlyObservableCollection<Foo>(_Foos);
            _Foos.Add(new Foo());
            _Foos.Add(new Foo());

            this.InitializeComponent();
        }
    }
}
```

Result observed:

App1.Foo
5
App1.Foo
App1.Foo
5
App1.Foo

**Expected behavior**
[blank]
5
[blank]
[blank]
5
[blank]

**Version Info**

NuGet package version: 
[Microsoft.NETCore.UniversalWindowsPlatform 6.2.10]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)             | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |   |
| Xbox                      |   |
| Surface Hub          |    |
| IoT                         |    |

**Additional context**
Workaround: For the inner `ItemsControl` `ItemTemplate`, use `Binding` instead of `x:Bind`, don't set `x:DataType` on the `DataTemplate`, and use a `ValueConverter` that provides a sensible default value when an unusual object is passed in as the `value`.

**Comment by JeanRoca** [comment]
Hey @BioTurboNick thanks for filing this issue. Would it be possible to use `TargetNullValue` on the X:Bind instead of the workaround provided? Is this occurring with WinUI 2?

**Comment by BioTurboNick** [comment]
@JeanRoca - Ah, I didn't realize that existed. Yeah that would work, thank you. If this is by design, I suppose this can be closed. I'm not sure what component version would be involved, but I can check if you tell me how?

**Comment by JeanRoca** [comment]
> @JeanRoca - Ah, I didn't realize that existed. Yeah that would work, thank you. If this is by design, I suppose this can be closed. I'm not sure what component version would be involved, but I can check if you tell me how?

Sure thing. In Visual Studio go to Tools -> NuGet Package Manager -> Manage NuGet Packages for Solution and check the version of Microsoft.UI.Xaml or Micrtosoft.WinUI if using WinUI 3.
