### ISSUE TITLE
Proposal: ItemTemplate/ItemTemplateSelector support for NavigationViewItem

### ISSUE THREAD

**Issue by bkaankose** [microsoft/microsoft-ui-xaml#2615]
# Proposal:  ItemTemplate support for NavigationViewItem's MenuItems for visually better hierarchical navigation.

## Summary
With the recent changes to NavigationViewItem for enabling hierarchical navigation, it now supports additional menu items as MenuItems or MenuItemsSource. However, it lacks ItemTemplate /ItemTemplateSelector support. In general, anything that allows hosting additional content should be allowed to be templated.

For context, this is the PR that merged to enable multi-level navigation.
https://github.com/microsoft/microsoft-ui-xaml/pull/2004

## Rationale
* Enabling developers to create more visually customized multi-level navigation system.
* For general purpose, developers are familiar with ItemsSource-ItemTemplate-ItemTemplateSelector concept. They will likely to want more control over the visual when they see something with name ItemsSource.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Developers need to be able to customize each multi-level NavigationViewItem separately. | Must |

## Important Notes
This problem can be fixed by creating an advanced control to be used as root ItemTemplate. However, this will require a lot of effort from developers and as naming convention goes, developers expect ItemTemplate and ItemTemplateSelector.

**Comment by chingucoding** [comment]
I am not sure if it makes sense to have to have a ItemTemplate property on NavigationViewItem if there already is one on the NavigationVIew. Is there a use case where you only want to specify a specific style/template for some of your NavigationViewItems but not all? Note that there also is a MenuItemTemplateSelecto property on NavigationView..

**Comment by bkaankose** [comment]
I didn't know it was inheriting template/selector from the parent :) This makes no sense then.
