### ISSUE TITLE
Proposal: Allow to select the whole paragraph with triple click

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/microsoft-ui-xaml#2619]
In a TextBlock or in a RichTextBlock allow to select the whole paragraph with triple mouse/touchpad click

# Proposal: [Allow paragraph selection with triple click] 

## Summary
In a TextBlock or in a RichTextBlock allow to select the whole paragraph with triple mouse/touchpad click

## Rationale
* Match textboxes behaviour

**Comment by Felix-Dev** [comment]
Related #2128

**Comment by chrisglein** [comment]
Added the mention of triple-click to #2619. Good catch.

Duplicate of #2619.
