### ISSUE TITLE
StackLayout isn't thread safe

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#2623]
**Describe the bug**
All `ItemsRepeater`s seem to automatically use a singleton instance of `StackLayout` as the default layout to arrange items.
The problem with `StackLayout` is that it isn't thread safe, and having it in multiple windows of the app will cause a crash because of cross thread access.

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.3]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 (xxxxx) | Yes |
| May 2020 (xxxxx)              | Yes   |
| November 2019 Update (18363)  | Yes      |
| May 2019 Update (18362)            | Yes      |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes      |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment]
@FrayxRulez I assume there isn't a repro or crash dump to investigate ? If you have more information, can you share it ?

**Comment by FrayxRulez** [comment]
No crash dumps for now, but if I’ll manage to get one I will definitely upload it here

**Comment by FrayxRulez** [comment]
So @ranjeshj this is kinda late but if I understood correctly this happens when a new ItemsRepeater with a ItemTemplate and **standard Layout** gets created and there's more than a window open for the app.

**Comment by FrayxRulez** [comment]
Even removing the ItemTemplate the app is obviously crashing due to cross thread calls.

**Comment by FrayxRulez** [comment]
So I've updated the ticket with a bit more of infos.

**Comment by ranjeshj** [comment]
StackLayout is stateless, so it can be shared, however I think there is an expectation that everything is on the same UI thread. @MikeHillberg @Austin-Lamb @jevansaks do we need to be able to work cross thread in the multiple window scenario ?

**Comment by FrayxRulez** [comment]
I think that this is what developers would expect. At least the fact that this scenario isn't supported isn't clear at all and I had to debug WinUI directly to find out.

**Comment by jevansaks** [comment]
StackLayout is a DependencyObject, and DependencyObject is fundamentally affinized with the thread it was created on. I think there's a world where we could make "Agile" DOs that can be shared across threads, but that would require quite a bit of work we haven't planned. 😐

Is there a way for us to provide a better error so you don't need to debug into our code, perhaps?

**Comment by FrayxRulez** [comment]
That would help. Currently a generic XamlParseException is raised.

**Comment by FrayxRulez** [comment]
So now that I moved StackLayout creation in App.xaml.cs I started to see a lot of this errors in AppCenter:
Windows.UI.Xaml.Markup.XamlParseException: Cannot create instance of type 'Microsoft.UI.Xaml.Controls.StackLayout'
