### ISSUE TITLE
Question: Will a WinUI app be able to call SystemMediaTransportControls from an unpackaged app?

### ISSUE THREAD

**Issue by jeremyVignelles** [microsoft/microsoft-ui-xaml#2631]
I am one of the LibVLCSharp maintainer, and we would like to provide examples for `SystemMediaTransportControls`.
For now, it's an UWP-only API. Will that change with WinUI becoming mainstream? Will any WinUI app be able to use SMTC in any app, including unpackaged ones? Are there any plans for a new API?

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI

**Comment by mveril** [comment]
It's not really a UWP or WinUI specific API, for example Edge chromium already use it
There is a Project Reunion discussions about that microsoft/ProjectReunion#127

**Comment by Austin-Lamb** [comment]
Closing this one out, as the reunion issue noted seems like the correct place to track this.
