### ISSUE TITLE
WebView2 cursor cannot be set

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#2636]
**Describe the bug**

In a WinUI 3 project with WebView2 loading an HTML document, the shape of the mouse pointer/cursor does not change in the same way it would in WebView 1 or in a native Edgium session. It does not change when hovering over a link and using the CSS cursor property (e.g. on hover over a certain element) does not actually result in any updates to the mouse cursor.

**Steps to reproduce the bug**
Add WebView2 to XAML. Load HTML document. Hover over link and observe cursor.

**Expected behavior**
Cursor respects CSS styling and changes to a pointing hand .

**Screenshots**
N/A (cursor not captured in screenshot)

**Version Info**
WinUI 3 Preview 1

NuGet package version: 
Microsoft.WinUI 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Originally filed here: https://github.com/MicrosoftEdge/WebViewFeedback/issues/242

**Comment by codendone** [comment]
Good timing for logging of this issue, since we just ironed out the implementation we need for this ([internal link](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/21132292)).  The plan is to start on this later this month.

**Comment by codendone** [comment]
This has now been fixed, and will be in the next WinUI3 preview.

**Comment by mqudsi** [comment]
Thanks. Any idea when we can expect to see a preview?

**Comment by codendone** [comment]
We haven't announced when the next preview will be released; we'll make that public as soon as we know.

**Comment by applefanbois** [comment]
3 years later, still not working. Test with this
 https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

It does not work at all in WebView2 2023, the cursor won't appear and won't change.

Weird because Apple took the time to implement them on macCatalyst (iOS app on Mac) WKWebview.

**Comment by baxasoft** [comment]
2025 and still not working

**Comment by applefanbois** [comment]
2032 and still not working
