### ISSUE TITLE
Scroller/ScrollViewer refactoring work following API reviews

### ISSUE THREAD

**Issue by RBrid** [microsoft/microsoft-ui-xaml#264]
# Proposal: Scroller/ScrollViewer updates following API reviews 

- [x]  Rename ScrollerView to ScrollViewer (5d)
- [x]  Replace ScrollBar2 with IScrollController adapter (2.75)
	Update ScrollViewer control template
	Create ScrollBarAdapter which implements IScrollController	
	Rename ScrollerViewScrollControllerVisibility to ScrollControllerVisibility	
	Remove IScrollController HorizontalScrollController { get; } and VerticalScrollController { get; }	
	Use IScrollController implementations of the PART_HorizontalScrollBar / PART_VerticalScrollBar parts if any. Else set inner Scroller.HorizontalScrollController / VerticalScrollController with internal ScrollBarController instances.	
- [x]  Update IScrollController interface (1d)
	Replace InteractionVisualRailingMode with IsInteractionVisualRailEnabled
	Replace GetOffsetChangeAnimation with GetScrollAnimation
	Replace OnOffsetChangeCompleted with OnScrollCompleted
	Replace OffsetChangeRequested with ScrollToRequested and ScrollByRequested
	Replace OffsetChangeWithAdditionalVelocityRequested with ScrollFromRequested
	Add void SetScrollMode(ScrollMode scrollMode)
	Add Boolean AreInteractionsAllowed { get; }
- [x]  Add ScrollViewer.ComputedHorizontalScrollBarVisibility and ScrollViewer.ComputedVerticalScrollBarVisibility (0.25d)
- [x]  Remove ScrollViewer.ComputedHorizontalScrollMode and ScrollViewer.ComputedVerticalScrollMode (0.25d)
- [x]  Remove Scroller.ComputedHorizontalScrollMode and Scroller.ComputedVerticalScrollMode (0.25d)
- [x]  Delete ScrollBar2 control. New internal ScrollBarController adapter replaces it. (0.5d)
- [x]  Replace layout properties IsChildAvailableWidth/HeightConstrained with ContentOrientation property (1d)
	Replace Boolean IsChildAvailableWidthConstrained { get; set; } / Boolean IsChildAvailableHeightConstrained { get; set; } with ContentOrientation { get; set; }.  ContentOrientation includes Vertical, Horizontal, Both.
- [x]  Remove Scroller and ScrollViewer's IsAnchoredAtHorizontalExtent / IsAnchoredAtVerticalExtent (0.5d)
	Replace properties with HorizontalAnchorRatio and VerticalAnchorRatio use of special values 0 and 1.	
- [x]  Refactor all view change methods (4.5d)
	Replace ScrollerChangeOffsetsOptions with ScrollOptions
	Replace ScrollerChangeZoomFactorOptions with ZoomOptions
	Add AnimationMode enum
        Add SnapPointsMode enum
	Add ScrollInfo struct
	Add ZoomInfo struct
	Replace ChangeOffsets with ScrollTo and ScrollBy
	Replace ChangeOffsetsWithAdditionalVelocity with ScrollFrom
	Replace ChangeZoomFactor with ZoomTo and ZoomBy
	Replace ChangeZoomFactorWithAdditionalVelocity with ZoomFrom
	Replace event Windows.Foundation.TypedEventHandler<ScrollerView, ScrollerChangingOffsetsEventArgs> ChangingOffsets with ScrollAnimationStarting
	Replace event Windows.Foundation.TypedEventHandler<ScrollerView, ScrollerChangingZoomFactorEventArgs> ChangingZoomFactor with ZoomAnimationStarting
	Replace event Windows.Foundation.TypedEventHandler<ScrollerView, ScrollerViewChangeCompletedEventArgs> ViewChangeCompleted with ScrollCompleted and ZoomCompleted
- [x]  Replace ScrollerState State { get; } with Microsoft.UI.Xaml.Controls.InteractionState State { get; } for both controls (0.5d)
	Rename ScrollerState enum name with InteractionState name. Replace CustomAnimation enum value with Animation. Replace Interacting enum value with Interaction. The resulting enum becomes:  public enum InteractionState? 
{? Idle = 0, Interaction = 1, Inertia = 2, Animation = 3 }
- [x]  Expose Double ScrollableWidth { get; } and Double ScrollableHeight { get; }, Double ViewportWidth { get; } and Double ViewportHeight { get; } read-only properties for both controls (0.5d)
- [x]  Support Microsoft.UI.Xaml.Controls.Primitives.SnapPointsAlignment Center and Far for the horizontal and vertical scroll snap points (3d)
- [x]  Replace ScrollViewer's HorizontalScrollControllerVisibility/VerticalScrollControllerVisibility properties with HorizontalScrollBarVisibility/VerticalScrollBarVisibility (0.5d)
	ScrollBarVisibility enum is { Auto=0, Visible=1, Hidden=2 }
- [x]  Replace InputKind properties with IgnoredInputKind properties. (0.5d)
	Add None to InputKind enumeration (new default value)
- [x]  Support mouse-wheel-based scrolling on prior OS releases (2d)
	Implement mouse-wheel-scrolling without using the built-in InteractionTracker support for downlevel support.
- [x]  Support mouse-wheel-based zooming on prior OS releases (1.25d)
- [x]  Move Scroller to Primitives namespace (0.75d)
	Scroller is moved to the Microsoft.UI.Xaml.Controls.Primitives namespace, along with all snap points related APIs and all IScrollController related APIs.
- [x]  Achieve parity with old ScrollViewer in regards to XBox gamepad support (1.25d)
- [x]  Remove ScrollMode.Auto. Only ScrollMode's Enabled and Disabled remain. (0.5d)
- [x]  Add Keyboard and Gamepad to InputKind enum (0.75d)
	Skip keyboard or gamepad input when those enum values are present in IgnoredInputKind.
- [x]  Update snap points object model (2.5d)
	Remove ScrollerSnapPointApplicableRangeType.
        Replace ScrollerSnapPointAlignment with SnapPointsAlignment.
	Replace old classes with SnapPointBase, ScrollSnapPointBase, ScrollSnapPoint, RepeatedScrollSnapPoint
	Add classes ZoomSnapPointBase, ZoomSnapPoint and RepeatedZoomSnapPoint
- [x]  ScrollViewer exposes IScrollAnchorProvider APIs and forwards calls to inner Scroller's implementation (0.5d)
	void RegisterAnchorCandidate(Windows.UI.Xaml.UIElement element) and void UnregisterAnchorCandidate(Windows.UI.Xaml.UIElement element) methods are exposed and forward calls to inner Scroller's IScrollAnchorProvide implementation.
- [x]  Remove Scroller prefix in enumeration names (0.5d)
	Example: ScrollerScrollMode befomes ScrollMode, etc...
- [x]  Replace Scroller.Child with Scroller.Content property (0.5d)
- [x]  Optionally account for snap points in bring-into-view participations. Figure out which public API to expose for this feature.
- [ ] Add two read-write dependency properties: Scroller.ScrollInertiaDecayRate (as a vector2<float>) and Scroller.ZoomInertiaDecayRate as a float.
- [x] Investigate whether MouseWheelParameters class can be used in custom handling of mouse-wheel, and potentially use it.
- [ ] Include an additional InteractionState (e.g. Pending or maybe call it Unknown) to represent the "not in Idle, but not yet in a state of movement" and raise the StateChanged event before each scroll/zoom request whether initiated by the user or programmatic.  This should enable an app to trigger re-rasterization of content if it owns rendering via something like Win2D.  May need to potentially rename InteractionState to something else like ScrollState.

**Comment by micahl** [comment]
Once the inertia decay rate properties are exposed let's plan to revisit the default values to refine and review with others.  We should also sync with @likuba since there might be other adjustments planned for InterationTracker based on feedback from partners.

**Comment by micahl** [comment]
@rbrid added another line item to this set of tasks to adjust StateChanged behavior and include another value in the enum.

**Comment by adrientetar** [comment]
Are the three remaining items all that's needed to get Scroller out of prerelease? I think we're very close now (modulo OS bugs ofc).

**Comment by RBrid** [comment]
Hello Adrien,
Regarding the three work items
- Achieve parity with old ScrollViewer in regards to XBox gamepad support
    I closed this one because there are no known discrepancies left between the framework ScrollViewer and the new control as far as gamepad handling is concerned.
- 
 Add two read-write dependency properties: Scroller.ScrollInertiaDecayRate (as a vector2) and Scroller.ZoomInertiaDecayRate as a float
    These two properties are not required to get the control out of prerelease. We will add them at a later time.
- Include an additional InteractionState
    This change is not required either in my opinion to get the control out of prerelease. We may not implement it depending on its complexity. Users can already listen to the ScrollCompleted/ZoomCompleted/StateChanged events today.

What is really needed to get the control out of prerelease is an official API review under https://github.com/micahl/microsoft-ui-xaml-specs. We are working on getting that started. 
The new Scroller/ScrollViewer controls also need to be renamed to avoid clashing with the old framework ScrollViewer which will move into the Microsoft.UI.Xaml.Controls namespace.

**Comment by micahl** [comment]
https://github.com/micahl/microsoft-ui-xaml-specs/blob/scrollviewer/active/ScrollViewer/ScrollViewer.md
