### ISSUE TITLE
ImageSource in ListViewItem is invalidated on click

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#2642]
In WinUI 3 Preview 1 a regression from alpha1 exists where all Image xaml elements have their source invalidated when the ListView item is selected. An Image with source set to a url will not display any issues, but if an image is loaded from a ReadOnlyStream/RandomAccessStream instead of a URL, it will display fine until the list view item is clicked and redrawn. In a UWP app, this causes the image to be under altogether. 

As the stream may no longer be available (eg the reference to it is not stored) there is no way to redraw the image. I have had to cache read-only streams locally to work around this. Caching in memory means I need to manually redraw the the image when it is invalidated (causing an ugly flash of missing image in addition to being a chore) so now I cache images to disk and loads the BitmapImageSource with a file:/// uri. This is obviously undesirable for performance reasons, but eliminates the flash of missing image when the image is redrawn on click after invalidation.

**Comment by JJBrychell** [comment]
We have been unable to reproduce this issue and so would like some additional information so we can  better understand the scenario.  The repro steps that we use are....

1. Create a page with a listview containing multiple images.
        &lt;ListView&gt;
            &lt;Image x:Name="ImageControl1" Height="100" Width="100"/&gt;
            &lt;Image x:Name="ImageControl2" Height="100" Width="100"/&gt;
            ….
        &lt;/ListView&gt;


2. Populate those images using a random access stream:

            var file = await StorageFile.GetFileFromApplicationUriAsync(uri);
            using (IRandomAccessStream stream = await file.OpenAsync(Windows.Storage.FileAccessMode.Read))
            {
                var bitmapImage = new BitmapImage();
                using (Windows.Storage.Streams.IRandomAccessStream fileStream = 
                       await file.OpenAsync(Windows.Storage.FileAccessMode.Read))
                {
                    bitmapImage.SetSource(fileStream);
                    image.Source = bitmapImage;
                }
            }

3.  Run the app and select list view items.

In our test those images appear fine and do not flicker or blank out.  Further, we also cached the BitMapImage objects and attempted to use them after the streams were disposed and we were successful in doing so.  Which is excepted.  When XAML creates a image, it will copy the image bits and as long as the object holding that copy of the bits exists, we should be able to reproduce the image.

Which leads us to believe there is something we are missing about this scenario.  Any additional information you could provide on this that would help us narrow it down would be appreciated.  This includes, Full Exception information, Call Stacks, sample code, etc.

Thanks

**Comment by ranjeshj** [comment]
@mqudsi can you provide a repro app ? Thanks!
