### ISSUE TITLE
Discussion: Bugs to be fixed in WinUI 3 Preview 2 

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#2643]
# Discussion: Bugs to be fixed in WinUI 3 Preview 2

Hi everyone! 

Our team is hard at work on WinUI 3 Preview 2 and are excited to share it with you all as soon as possible. As we announced previously, Preview 2 will be a stability and quality focused release, with an emphasis on fixing bugs from Preview 1. In order to make sure that our work really focuses on our developers, I wanted to ask our community:

What are the serious and/or blocking bugs that you encountered in Preview 1?

As we work through bugs we want to make sure that we're fixing ones that will really impact your quality of life as a developer, so feel free to share any significant ones in the comments. 

**NOTE:** Please "thumbs up" ones that you agree with/have also encountered! This makes it much easier for us to keep track.

Thanks!

**Comment by myokeeh** [comment]
Thorn on side: https://github.com/microsoft/microsoft-ui-xaml/issues/597

**Comment by dotMorten** [comment]
Support for `System.Collections.Specialized.INotifyCollectionChanged`

It's quite involved to try and rewrite your app currently to make it work, and a lot of View Models rely on observable collections to function. I gave up trying to port any current applications to WinUI, simply because significant rewrites were required. It was by far the single most biggest blocker for trying to run any existing code on WinUI.

**Comment by robloo** [comment]
System.Collections.Specialized.INotifyCollectionChanged is the biggest one that hides all the rest

**Comment by shaheedmalik** [comment]
#2236

**Comment by terrycox** [comment]
Back on March 25th, I posted this (regarding the Alpha release):

Windows UI should support at least the major MVVM frameworks- MVVM Light, Prism, and Caliburn. Unfortunately, your documented problem with changes to INotifyPropertyChanged and INotifyCollectionChanged breaking ObservableCollection certainly breaks MVVM Light, and probably the other two frameworks as well. Thought you should know.

(https://github.com/microsoft/microsoft-ui-xaml/issues/1045)

If the goal is 'one UI to bind them all', you need to maintain enough compatibility that developers aren't chasing some moving target you keep shifting. How many projects do you think uses these frameworks?

**Comment by terrycox** [comment]
I'd also like to see you bring some love for WinRT back into Win UI.  The Win32 support is lovely, but where did WinRT go? And why?

**Comment by MikeHillberg** [comment]
@terrycox, what lack of WinRT love are you referring to?

**Comment by terrycox** [comment]
The Alpha documentation contained procedures and templates for updating WinRT apps to use Win UI 3. All of that disappeared in Preview 1, which had templates for Win32 apps, but no templates for UWP progs, and no mention in the documentation whatsoever. 

I understand that the focus was on the new bits, Win32, and that the code didn't vanish, but it was disconcerting to see WinRT references disappear altogether.

**Comment by terrycox** [comment]
The documentation and templates in the Alpha disappeared in Preview 1. The bits were still there, but all the WinRT stuff- nope. I realize the focus was on the new stuff (Win32), but hey.

**Comment by dotMorten** [comment]
@terrycox huh? It's not just Win32. The WinUI UWP templates are still there.

**Comment by sonnemaf** [comment]
I have played around with Validation. It is quite instable. It crashes a lot. 

I'm using an improved version of ValidationBase baseclass with an extra AllError property. Use it for a kind of 'Validation Summary' (ListView)

```
public class ValidationBase : INotifyPropertyChanged, INotifyDataErrorInfo {

    public event PropertyChangedEventHandler PropertyChanged;
    public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;

    protected void SetValue<T>(ref T currentValue, T newValue, [CallerMemberName] string propertyName = "") {
        if (!EqualityComparer<T>.Default.Equals(currentValue, newValue)) {
            currentValue = newValue;
            OnPropertyChanged(propertyName, newValue);
        }
    }

    readonly Dictionary<string, List<ValidationResult>> _errors = new Dictionary<string, List<ValidationResult>>();

    public bool HasErrors {
        get {
            return _errors.Any();
        }
    }
    public IEnumerable GetErrors(string propertyName) {
        return _errors[propertyName];
    }

    private void OnPropertyChanged(string propertyName, object value) {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        Validate(propertyName, value);
    }

    private void AddErrors(string propertyName, IEnumerable<ValidationResult> results) {
        if (!_errors.TryGetValue(propertyName, out List<ValidationResult> errors)) {
            errors = new List<ValidationResult>();
            _errors.Add(propertyName, errors);
        }

        errors.AddRange(results);
        ErrorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(propertyName));
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(AllErrors)));
    }

    private void ClearErrors(string propertyName) {
        if (_errors.TryGetValue(propertyName, out List<ValidationResult> errors)) {
            errors.Clear();
            ErrorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(propertyName));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(AllErrors)));
        }
    }

    public void Validate(string memberName, object value) {
        ClearErrors(memberName);
        List<ValidationResult> results = new List<ValidationResult>();
        bool result = Validator.TryValidateProperty(
                value,
                new ValidationContext(this, null, null)
                {
                    MemberName = memberName
                },
                results
                );

        if (!result) {
            AddErrors(memberName, results);
        }
    }

    public IEnumerable<ValidationResult> AllErrors => _errors.Values.SelectMany(v => v);
}
```

```
public class Employee : ValidationBase {

    private string name;
    private double _salary;

    public Employee(string name, double salary) {
        Name = name;
        Salary = salary;
    }

    [MinLength(4)]
    [MaxLength(6)]
    public string Name {
        get { return name; }
        set { SetValue(ref name, value); }
    }

    [Range(0, 10000)]
    public double Salary {
        get { return _salary; }
        set { SetValue(ref _salary, value); }
    }
}
```

```xml
<Page x:Class="App23.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:local="using:App23"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
      mc:Ignorable="d">

    <StackPanel HorizontalAlignment="Center"
                VerticalAlignment="Center"
                Spacing="12"
                Width="300"
                Orientation="Vertical">
        <TextBox Text="{x:Bind Employee.Name, Mode=TwoWay}" />
        <NumberBox Value="{x:Bind Employee.Salary, Mode=TwoWay}" />
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
        <ListView ItemsSource="{x:Bind Employee.AllErrors, Mode=OneWay}" />
    </StackPanel>
</Page>
```

**Comment by anawishnoff** [comment]
> Why don't you look through the repo to see the bugs people have reported in Preview 1?

Oh we definitely are! I put this issue together so that we have an easy way of seeing peoples **biggest** blockers. Using an issue like this is also a tool that helps aggregate upvotes on issues, which gives us an easier view into how widespread the issue is.

**Comment by myokeeh** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/2440

**Comment by robloo** [comment]
Thanks @anawishnoff for creating this issue. Addressing bugs has been a long standing problem with UWP and I'm glad to finally see them being addressed head-on and talked about.

A focus here will ensure WinUI 3.0 is smooth for developers to use. I look forward to trying out future previews!

**Comment by cirrusone** [comment]
Webview2 is always on top of other controls so other controls with animations are hidden behind the webview2 control. I think this used to be called the 'Airspace problem'.

**Comment by eleanorleffler** [comment]
Win2D! Not that this is a bug, but it would be a much-needed addition to Preview 2, rather than waiting until later.

**Comment by harvinders** [comment]
It would be great if #2602 could be addressed.

**Comment by lhak** [comment]
Not sure if it qualifies as a bug, but can you please add header files and idl files for WRL? These are required to get win2d working (see https://github.com/microsoft/Win2D/issues/707). I created them manually from the .winmd file (not sure if I did it correctly) but a lot of manual editing was required afterwards.

**Comment by eleanorleffler** [comment]
TreeView with derived TreeViewNodes crashes in WinUI3 Desktop #2699

**Comment by eleanorleffler** [comment]
DataGrid Not Displaying in WinUI3 Desktop #2703

**Comment by eleanorleffler** [comment]
Unable to Enter Text into TextBox inside ContentDialog in WinUI3 Desktop #2704

**Comment by eleanorleffler** [comment]
NavigationView inside ContentDialog causes crash #2713

**Comment by eleanorleffler** [comment]
Change in Appearance of AppBarButton with Flyout on CommandBar in WinUI3 Desktop #2714

**Comment by eleanorleffler** [comment]
Unable to drop files onto Grid in WinUI3 Desktop #2715

**Comment by eleanorleffler** [comment]
FileOpenPicker, FileSavePicker, and FolderPicker break in WinUI3 Desktop #2716

**Comment by eleanorleffler** [comment]
Not exactly a blocking bug, but would be nice to have the TitleBar customization back in Preview 2!

Window.SetTitleBar method is missed in WinUI/Uwp #2559

**Comment by Wigmund** [comment]
Working ObservableCollections is a must!

**Comment by harvinders** [comment]
It would be nice to see some progress on [Dispatcher](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/Win32/active/Win32/Window_and_Application_API_Spec.md#windowdispatcher-property) too.

**Comment by eleanorleffler** [comment]
Unable to drop items from ListView onto Grid in WinUI3 Desktop #2782

**Comment by eleanorleffler** [comment]
Unable to move item (drag and drop) inside TreeView in WinUI3 Desktop #2783

**Comment by Wigmund** [comment]
Any news on the Preview 2 release date, with working observable collections ;) ?

**Comment by Felix-Dev** [comment]
@Wigmund Tune into today's WinUI Community Call, if possible (Preview 2 seems quite close to release by now).
