### ISSUE TITLE
EETypeLoadException in OnBackgroundActivated w/ WinUI 3

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#2644]
**Describe the bug**

In a UWP (not WinUI Desktop) application that's registered an in-process background task, every time `OnBackgroundActivated` is invoked (at least with a managed debugger attached), an `EETypeLoadException` is thrown.

**Steps to reproduce the bug**

1. Create a UWP app and add a reference to WinUI 3 Preview 1
2. Register an in-process background task (say, system timer on 15 minute intervals)
3. Run in the debugger with break on all managed, Win32, and C++ exceptions configured and wait for the background task to be activated.
4. Observe as an `EETypeLoadException` is thrown from Microsoft.UI.Xaml.dll

**Expected behavior**
No exception. 

**Screenshots**

**Version Info**
WinUI 3 Preview 1

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview1.200515.3]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by JJBrychell** [comment]
We have been unable to reproduce this issue and so would like some additional information so we can better understand the scenario. The repro steps that we used are....

1. Defined a background task in Application object:
            var builder = new Windows.ApplicationModel.Background.BackgroundTaskBuilder();
            builder.Name = "My Background Trigger";
            builder.SetTrigger(new Windows.ApplicationModel.Background.TimeTrigger(15, false));
            Windows.ApplicationModel.Background.BackgroundTaskRegistration task = builder.Register();
2.  Override the OnBackgroundActivated method:
       protected override void OnBackgroundActivated(BackgroundActivatedEventArgs args)
        {
            base.OnBackgroundActivated(args);
            System.Diagnostics.Debug.WriteLine("Entered OnBackgroundActivated");
        }
3. Run the app and minimize it.

In our test after about 15 minutes the diagnostic message is displayed in the debugging window and the application continues to run with no error.

Which leads us to believe there is something we are missing about this scenario. Any additional information you could provide on this that would help us narrow it down would be appreciated. This includes, Full Exception information (e.g. the type being created), Call Stacks, sample code, etc.

Thanks

**Comment by mqudsi** [comment]
Are you debugging both native and managed code and have break on all win32 exceptions enabled?

**Comment by MikeHillberg** [comment]
@mqudsi - When not breaking on exceptions is there an issue? Or is the issue here that there shouldn't be exceptions as part of normal running (there shouldn't be exceptions in non-exceptional conditions)?

**Comment by mqudsi** [comment]
The second (there shouldn't be exceptions as part of normal running)

Thanks

**Comment by JJBrychell** [comment]
Yes I have debugged native, managed and mixed and all exceptions are enabled.  No exception break and no exception information appears in the debug windows.
