### ISSUE TITLE
TabViewItem should consume Foreground/Background properties

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2653]
**Describe the bug**
The `TabViewtem` currently ignores the `Foreground` and `Background` properties. While, for example, overriding theme resources such as `TabViewItemHeaderBackground` can be used to set the background color of tabs, developers rightfully expect to be able to use the aforementioned properties as well.

See for example the following XAML:
```xml
<muxc:TabView>
    <muxc:TabView.TabItems>
        <muxc:TabViewItem Header="Tab 1">
            <muxc:TabViewItem.IconSource>
                <muxc:SymbolIconSource Symbol="Home" />
            </muxc:TabViewItem.IconSource>
        </muxc:TabViewItem>
        <muxc:TabViewItem Header="Tab 2" Foreground="Orange" Background="Green">
            <muxc:TabViewItem.IconSource>
                <muxc:SymbolIconSource Symbol="Emoji" />
            </muxc:TabViewItem.IconSource>
        </muxc:TabViewItem>
    </muxc:TabView.TabItems>
</muxc:TabView>
```

The expected look would be:
![image](https://user-images.githubusercontent.com/1398851/84577885-6b13b080-adc0-11ea-87ee-d847947a7596.png)

but the actual look is this (neither `Foreground` nor `Background` value is respected):
![image](https://user-images.githubusercontent.com/1398851/84577383-035b6680-adbc-11ea-8b61-4463962ea127.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml2.5.0-prerelease.200609001

**Open Questions**
I based the `Foreground` property affecting both the icon and the Tab header on the fact that they are "content" to be set by the user and the precedence set by the `MenuFlyoutItem` and the `NavigationViewItem`:
```xml
<muxc:TabViewItem.ContextFlyout>
    <MenuFlyout>
        <MenuFlyoutItem Text="123" Foreground="Red" Icon="Accept"/>
    </MenuFlyout>   
</muxc:TabViewItem.ContextFlyout>
```
with the corresponding image:
![image](https://user-images.githubusercontent.com/1398851/84578143-cd6db080-adc2-11ea-85a1-b6541efb0ffb.png)

And the NavigationViewItem XAML as follows:
```xml
<muxc:NavigationViewItem Content="Menu Item 1" Icon="Home" Foreground="Red">
    <muxc:NavigationViewItem.MenuItems>
        <muxc:NavigationViewItem Content="Menu Item 1.1" Icon="Emoji"/>
    </muxc:NavigationViewItem.MenuItems>
</muxc:NavigationViewItem>
```

with the resulting look:
![image](https://user-images.githubusercontent.com/1398851/84578373-ec6d4200-adc4-11ea-9368-3a3f8731ae39.png)

I think it is worth thinking about creating a consistent foreground styling behavior here. The specific issue with the `TabViewItem` compared to the above two controls is that it has an explicit `TabViewItemIconForeground` theme resource to enable independent icon styling from the rest of the TabViewItem content (like the header). I would like to see some consistency here between all three controls so that either
* setting `Foreground` affects both Icon and Content/Header/Text in TabViewItem/MenuFlyoutItem/NavigationViewItem or
* we can set the Icon foreground value independently in all three cases (for example via theme resources) and the `Foreground` property would only affect the Content/Header/Text

Scenario 1 would mean that the specific `TabViewItemIconForeground*` theme resources would no longer be useful (to prevent a breaking change I would keep them in the resource dictionary with an added comment that they are no longer in use) whereas Scenario 2 should mean that both MenuFlyoutItem and NavigationViewItem will get specific `MenuFlyoutItemIconForeground*/NavigationViewItemIconForeground*` theme resources *and* the `Foreground` API will no longer effect their *Icon* foreground color.

**Comment by StephenLPeters** [comment]
I agree, the foreground and background properties should do something.  You bring up some good points though, its not clear what exactly the foreground property should do. @stmoy thoughts?

**Comment by DHowett** [comment]
Terminal is interested in this as well. We have a feature that allows a user to customize her tab colors, but it's implemented by locally overriding the `TabViewItemHeader*` resources. It's terribly unpleasant.

**Comment by Felix-Dev** [comment]
Pinging @stmoy for thoughts about the how we should proceed here (given the TabViewItem's unique situation with the Icon and ContentPresenter theme resources).

**Comment by mdtauk** [comment]
How would inheritance work for this?

**Comment by Felix-Dev** [comment]
@mdtauk I would use TemplateBinding here.

**Comment by stmoy** [comment]
Thanks for the ping @Felix-Dev - this slipped past my radar. 

Agreed that foreground and background properties should do something as @StephenLPeters mentions. I believe the most straightforward and consistent approach would be to do what MenuFlyout and NavigationView do (Scenario 1, above).

I'm not sure if _not_ using a named brush is a breaking change or not. Sure, you could still set it, but it wouldn't do anything - which is the same as what happens if we remove it altogether, right?

**Comment by Felix-Dev** [comment]
@stmoy If we remove them altogether, apps which are using them now *could* end up crashing after updating to a WinUI version where these have been removed, to my understanding. For example, picture someone using them like this (without a theme resource override on an app/page level in scope):
```xml
<[SomeClass].Foreground="{ThemeResource TabViewItemIconForeground}"/>
```
Now, such a usecase arguably looks quite unlikely but if an app does consume those theme resources similar to above then a removal here would mean this app couldn't run any longer (since that referenced resource is now missing) without the developer having to modify their app code. If we keep the resources included, then they won't break apps, but, as you said correctly, they also won't do anything any longer. They will basically be "garbage" at this point...only to be kept because of an arguably small chance someone out there might be using them in such a way that their removal from WinUI would result in an app crash.

**Comment by Felix-Dev** [comment]
@stmoy What is the status here? Are there still open questions or can we proceed with a PR for this issue (by following the outlined Scenario 1)?

**Comment by stmoy** [comment]
Thanks for the reminder - let me ping the team. The biggest question is related to "is this a breaking change, and if it is, should we hold off?" - it's a philosophical question so it is taking longer than I'd hope 😅

**Comment by stmoy** [comment]
CC: @StephenLPeters 

One idea that was floated was moving the **unused** brush to a separate resource dictionary (like "DeprecatedResources" or something) so that it's still technically accessible while being in a place that clearly marks that it will be removed soon. This would be just another theme dictionary that gets merged in similar to TabViewThemeResources_RS1.xaml. 

@Felix-Dev I think you're good to move forward with a PR and we can discuss further there if there are more concerns.
