### ISSUE TITLE
Proposal: TabViewItem's CloseButton & TabView's AddButton should have dedicated theme resources

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2655]
# Proposal: TabViewItem's CloseButton & TabView's AddButton should have dedicated theme resources

## Summary
If you currently try to change the foreground of the TabViewItem's Close button, the easiest way to do so is to use lightweight styling by overriding the `TabViewButtonForeground` theme resource. See the following XAML:
```xml
<muxc:TabView>
    <muxc:TabView.Resources>
        <SolidColorBrush x:Key="TabViewButtonForeground" Color="Red" />
    </muxc:TabView.Resources>
    <muxc:TabView.TabItems>
        <muxc:TabViewItem Header="Tab 1">
            <muxc:TabViewItem.IconSource>
                <muxc:SymbolIconSource Symbol="Home" />
            </muxc:TabViewItem.IconSource>
        </muxc:TabViewItem>
        <muxc:TabViewItem Header="Tab 2">
            <muxc:TabViewItem.IconSource>
                <muxc:SymbolIconSource Symbol="Emoji" />
            </muxc:TabViewItem.IconSource>
        </muxc:TabViewItem>
    </muxc:TabView.TabItems>
</muxc:TabView>
```

this creates the following TabView result:
![image](https://user-images.githubusercontent.com/1398851/84579349-42de7e80-adcd-11ea-84f7-f027e2d17f26.png)
Notice how not only the TabViewItem's Close button has changed its foreground but also the TabView's Add button! In other words, it is currently not possible to independently style the (foreground) color of the close button (this applies to the close button's background as well) using lightweight styling.

This proposal aims to split up the current `TabViewButton*` theme resources into specific theme resources for the TabViewItem's *Close* button and the TabView's *Add* button (as these are the only instances in the in-box tab control where they are used):

TabViewItem's Close button:
```
TabViewItemCloseButtonBackground"           
TabViewItemCloseButtonBackgroundPressed"    
TabViewItemCloseButtonBackgroundPointerOver"
TabViewItemCloseButtonBackgroundDisabled"   
TabViewItemCloseButtonBackgroundActiveTab"  
TabViewItemCloseButtonForeground"           
TabViewItemCloseButtonForegroundPressed"    
TabViewItemCloseButtonForegroundPointerOver"
TabViewItemCloseButtonForegroundDisabled"   
TabViewItemCloseButtonForegroundActiveTab"  
```

TabView's Add button:
```
TabViewAddButtonBackground"           
TabViewAddButtonBackgroundPressed"    
TabViewAddButtonBackgroundPointerOver"
TabViewAddButtonBackgroundDisabled"   
TabViewAddButtonForeground"           
TabViewAddButtonForegroundPressed"    
TabViewAddButtonForegroundPointerOver"
TabViewAddButtonForegroundDisabled"   
```

## Rationale
Gives customers more design flexibility by enabling them to independently style the TabView's Add button and the TabViewItem's Close button.

## Additional Context
TabView's scrolling buttons can currently be lightweight styled using the specific RepeatButton theme resources such as `RepeatButtonForeground`. It seems reasonable to add specific TabView resources for these buttons too, such as `TabViewScrollButtonForeground`. This would give us the benefit of further decoupling TabView's lightweight styling feature from the TabView's implementation (where these scroll buttons are currently implemented as `RepeatButton`'s) and thus make it more future-proof.

This could either be tracked in its own issue or added to this one if this suggestion is accepted by the team.

**Comment by StephenLPeters** [comment]
I think seperating the resources that the components point to makes sense.  @stmoy and @teaP fyi

**Comment by stmoy** [comment]
+1 - agree with @StephenLPeters that having dedicated resources makes sense.
