### ISSUE TITLE
Seems like attached properties are not working in WinUI 3 preview 1 (Desktop)

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2658]
**Describe the bug**

Using attached property in xaml give compilation error, `XamlCompiler error WMC0010: Unknown attachable member 'NavHelper.NavigateTo' on element 'NavigationViewItem'`

**Steps to reproduce the bug**

1. Create a attached property like

```
public class NavHelper
    {
        public static Type GetNavigateTo(NavigationViewItem item)
        {
            return (Type)item.GetValue(NavigateToProperty);
        }

        public static void SetNavigateTo(NavigationViewItem item, Type value)
        {
            item.SetValue(NavigateToProperty, value);
        }

        public static readonly DependencyProperty NavigateToProperty =
            DependencyProperty.RegisterAttached("NavigateTo", typeof(Type), typeof(NavHelper), new PropertyMetadata(null));
    }
```

2. Reference it like below in XAML
```
            <NavigationViewItem Content="General"  helpers:NavHelper.NavigateTo="view:MyPage"/>
```

**Expected behavior**

No compilation error

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |  Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I have checked it for only desktop version and not UWP.

**Comment by pratikone** [comment]
It looks like you are missing some syntax. As per [MSDN](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-attached-properties), the custom property needs to be added within a namespace which needs to be referenced. Once you do that, this error goes away. This is how your code will look like with these changes :  
```cpp
namespace foo {
  public class NavHelper
    {
        public static Type GetNavigateTo(NavigationViewItem item)
        {
            return (Type)item.GetValue(NavigateToProperty);
        }

        public static void SetNavigateTo(NavigationViewItem item, Type value)
        {
            item.SetValue(NavigateToProperty, value);
        }

        public static readonly DependencyProperty NavigateToProperty =
            DependencyProperty.RegisterAttached("NavigateTo", typeof(Type), typeof(NavHelper), new PropertyMetadata(null));
  }
}
  ```
Add `foo` namsepace to your class's xaml definition (refer to MSDN article linked above)   
```xaml
<MyClass
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
  xmlns:foons="using:foo"
  ... >
```

It, later can be referenced like this :  
```xaml
<NavigationViewItem Content="General"  foons:NavHelper.NavigateTo="view:MyPage"/>
``` 

See if this solves your problem. I am closing this bug for now. you can re-open it if it doesn't resolve the issue for you.
