### ISSUE TITLE
Proposal: RadialGradientBrush 

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/microsoft-ui-xaml#266]
# Proposal: RadialGradientBrush 

## Summary

This feature would add RadialGradientBrush  to UWP XAML. 

![colorful radial gradient](https://user-images.githubusercontent.com/16964652/52248061-6ae8d400-28a1-11e9-9652-8e4d84f45133.png)

## Rationale

The Composition team has recently added radial gradient brush capability to Windows for XAML to leverage. RadialGradientBrush is a popular and enduring request that will delight veteran XAML customers. There exists RadialGradientBrush for WPF, however many core properties such as the transform property and animation are not supported. Additionally, design research indicates a resurgence of radial gradient use in applications targeting communication, social, and recreational functions. 

## Functional Requirements

| # | Feature | Priority |
|:-:|:--|:-:|
| 1 | Able to customize the number of stops on the gradient | Must |
| 2 | Able to customize the color of each stop | Must |
| 3 | Able to set gradient and ellipse origin | Must |
| 4 | Support for absolute and relative mapping modes | Must |
| 5 | Able to change color space of interpolation | Must |
| 6 | WPF, Silverlight, and C++/WinRT compatibility (XAML and Visual) to enable leveraging of existing assets. | Must |
| 7 | AlphaMode modifier to support natural transparency blending | Should |
| 8 | Able to animate the stops and stop colors with Storyboard support | Should |

### Prerelease readiness
- [x] Dev: quality review + code review done
- [x] Dev: test coverage added
- [x] Dev: initial accessibility review done
- [x] Dev: telemetry implemented
- [x] PM: spec up to date
- [x] PM: feature ready for feedback
- [x] PM: docs.microsoft.com updates ready
### Stable release readiness
- [x] Dev: feature previously shipped in a prerelease NuGet package
- [x] Dev: Azure CI tests passing
- [x] Dev: accessibility review done
- [x] Dev: API review done
- [x] Dev: IDL attribute switched from preview to public
- [x] Dev: Add test coverage to the NugetReleaseTest test
- [x] PM: spec done
- [x] PM: glob/loc, privacy, security, license compliance ready
- [x] PM: customer validation done
- [x] PM: docs.microsoft.com updated
- [x] PM: Xaml Controls Gallery updated

**Comment by SavoySchuler** [comment]
Thanks, @michael-hawker, I have updated the Functional Requirements list with these bullets! Please let me know if you agree or disagree with the priorities I assigned to them - are either of the Should's worth gating the release for?

**Comment by michael-hawker** [comment]
@SavoySchuler thanks! Think the only thing is for the WPF compatibility, if it's not done upfront then changing syntax can be difficult after an initial release, so it's more of a note to make sure to not deviate too far from the existing property names, enum value names, or default values.

**Comment by Berrysoft** [comment]
@michael-hawker The one added to the Windows Community Toolkit isn't compatible with C++/WinRT. There's also a [bug](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2733) of it.

**Comment by michael-hawker** [comment]
@Berrysoft yes good call.  That's one of the scenarios we don't cover as the toolkit is mostly C#.  We've since started adding more support for some things in C++, but it's a good call out that by adding it to WinUI it'll work for both. :)

**Comment by SavoySchuler** [comment]
Thanks @michael-hawker and @Berrysoft, I have updated the proposal with those details and upgraded the priority to "Must" for that feature.

**Comment by SavoySchuler** [comment]
# This proposal has been approved for [spec writing](https://github.com/Microsoft/microsoft-ui-xaml-specs/blob/savoyschuler/radialgradientbrush/active/RadialGradientBrush/RadialGradientBrush.md)!

Please feel encouraged to continue high-level discussion here on the proposal. I will open up the associated PR for more detailed discussion once it is available.

**Comment by SavoySchuler** [comment]
I've had a full plate recently and I want to make sure this proposal keeps moving forward, so I will be handing #266 over @jesbis. He will be the PM owner, so be sure to @ him if you have any questions or ideas! 😊

**Comment by michael-hawker** [comment]
Welcome @jesbis! If you have any questions or want to sync, let me know.  I wrote the initial stop-gap version that we put in the Windows Community Toolkit.

**Comment by michael-hawker** [comment]
🦙 For History, Linking to completed WPF Parity issues #2180 #2193
