### ISSUE TITLE
Impossible to create WinUI 3 C++ Desktop Project

### ISSUE THREAD

**Issue by ePirat** [microsoft/microsoft-ui-xaml#2661]
**Describe the bug**
It is impossible to create a WinUI C++ Desktop Project in Visual Studio Community 2019 Preview

**Steps to reproduce the bug**

1. Open VS 2019 Preview
2. Create new Blank App, Packaged (WinUI in Desktop) C++ App

**Expected behavior**
Should create a new WinUI C++ Desktop app

**Screenshots**
![image](https://user-images.githubusercontent.com/323210/84592155-c3d85d00-ae43-11ea-926b-491046581eeb.png)

I've installed all components with a similar name in the installer, there is none that exactly matches that name, does not help either that the names are translated so its really really hard to Google for this issue...

**Version Info**

NuGet package version: 
Can't tell as I dont end up with a working project that has it.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

(Tested on Windows 10 Pro 1909 18363.900)

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ePirat** [comment]
Figured it out.
You need to search for it in the Project Templates **not** in the Installer. Create a Project with it and it will launch the installer and install the needed tools. (It will not actually create a project, just install the tools)

![image](https://user-images.githubusercontent.com/323210/84592544-b96b9280-ae46-11ea-9b16-f5705c7a9dd8.png)

**Comment by weltkante** [comment]
for people coming across this later, there is also #2492 with some info on what you need to check in the installer
