### ISSUE TITLE
Does WinUI have plans to support non-rectangular window?

### ISSUE THREAD

**Issue by milchchan** [microsoft/microsoft-ui-xaml#2668]
I'm developer of desktop agent using non-rectangular windows (https://github.com/milchchan/Apricot). I want to migrate to WinUI from WPF in the future.

**Comment by ShankarBUS** [comment]
I don't think that would ever happen 😔

**Comment by Felix-Dev** [comment]
See issue https://github.com/microsoft/microsoft-ui-xaml/issues/1247 which requests window transparency to be added to WinUI as a start point for non-rectangular window support.

**Comment by milchchan** [comment]
Thank you for your comment. I expect to implement window transparency feature.

**Comment by jtbrower** [comment]
I author applications that run as a KIOSK and should have no Window title bar, minimize / maximize or close buttons.  Not being able to support Window transparency and title bar removal prevents me from migrating to WinUI from WPF.
