### ISSUE TITLE
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.815

### ISSUE THREAD

**Issue by RicardoCorralT** [microsoft/microsoft-ui-xaml#2669]
**Modern print dialog not working in WUP apps on Windows 10 (e.g. Photos, Edge)**

1. Open an image in Photos or open Edge browser
2. Click on Print...
3. Print dialog briefly comes up and then disappears, the below is logged in the Application Log every time:

Faulting application name: PrintDialog.exe, version: 10.0.18362.1, time stamp: 0xb40b5d8f
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.815, time stamp: 0x9fa806f2
Exception code: 0xc000027b
Fault offset: 0x0000000000713530
Faulting process id: 0x2f60
Faulting application start time: 0x01d642c78fc434be
Faulting application path: C:\WINDOWS\PrintDialog\PrintDialog.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 6bfc1f2b-16d6-4bbd-a4c0-f6700563814e
Faulting package full name: Windows.PrintDialog_6.2.1.0_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: Microsoft.Windows.PrintDialog

Windows 10 version: 1903 (18362.900) and 1909 (18363.900)

Device Form Factor: Desktop

Additional Info: Issue is isolated to user profiles pre-existing in the PC prior the 1903 feature update, re-creating the profile on a PC fixes the issue, however, re-creating each user profile across all computers is not practical.

Tried the following Powershell commands as per #716 without success:
```
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.0_2.1810.18004.0_x64__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.0_2.1810.18004.0_x86__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.1_2.11906.6001.0_x64__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.1_2.11906.6001.0_x86__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.2_2.21909.17002.0_x64__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.2_2.21909.17002.0_x86__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.3_2.32002.13001.0_x64__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.3_2.32002.13001.0_x86__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.4_2.42005.18002.0_x64__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.4_2.42005.18002.0_x86__8wekyb3d8bbwe\AppxManifest.xml"

```
and

```
$Apps = @("Photos");

$base   = @();
$depend = @();
$Apps | %{
    $base   += $base   = (Get-AppxPackage -Name "*$_*").InstallLocation;
    $depend += $depend = (Get-AppxPackage -Name "*$_*").Dependencies.InstallLocation;
    };

$Apps = (($base + $depend) | Sort -Unique);
$Apps | %{Add-AppxPackage -Path "$_\Appxmanifest.xml" -Register -DisableDevelopmentMode};
```

**Comment by StephenLPeters** [comment]
@Austin-Lamb and @codendone do you know anything about this? looks like a system upgrade issue.

"Issue is isolated to user profiles pre-existing in the PC prior the 1903 feature update, re-creating the profile on a PC fixes the issue, however, re-creating each user profile across all computers is not practical."

**Comment by codendone** [comment]
@RicardoCorralT From your description where recreating the user profile fixes the issue, I agree this sounds like a version of #716.  Does Feedback Hub work on an affected profile, such that you can post an issue in Feedback Hub and then share a link to the issue so we can check the logs?  (If Feedback Hub does work, recording a repro as part of the issue would help ensure we get the necessary information.)

If Feedback Hub doesn't work, could you share a crash dump, or use !pde.dse to dump the stowed exceptions from a crash dump, as described [here](https://github.com/microsoft/microsoft-ui-xaml/issues/716#issuecomment-637921964)?

**Comment by RicardoCorralT** [comment]
@codendone thanks and apologies for the delay, just got back to this issue and to this client's environment. Yes, Feedback Hub works on affected profiles, I've submitted a bug, link is here: [https://aka.ms/AA8x3dt](url)

**Comment by codendone** [comment]
@RicardoCorralT It looks like you're hitting an Access Denied crash in PrintDialog!PrintDialog::DataModel::PrinterMruStoreImpl::GetMruList.  A lot of the code in that function is looking at regkeys, so this might be a problem with some regkeys.

I've asked the PrintDialog owners to take look, and linked your Feedback Hub report to their tracking bug ([internal link](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/23870900/)).

**Comment by RicardoCorralT** [comment]
@codendone Hi Mike, have you heard back from the PrintDialog team? Thanks.

**Comment by codendone** [comment]
@RicardoCorralT They have assigned the issue for investigation, but they don't currently have an update. I pinged them.

**Comment by RicardoCorralT** [comment]
@codendone Hi Mike, do you know if the PrintDialog team has any updates? Thanks.

**Comment by codendone** [comment]
@RicardoCorralT They have reassigned the issue to someone who can look at it sooner, but looks like they still haven't started the investigation.
