### ISSUE TITLE
SplitButton doesn't respect *ContentAlignment

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/microsoft-ui-xaml#267]
**Describe the bug**
The default SplitButton XAML doesn't TemplateBind the HorizontalContentAlignment & VerticalContentAlignment properties to it's "PrimaryButton" component, effectively ignoring them.

**Steps to reproduce the bug**
1. Apply HorizontalContentAlignment & VerticalContentAlignment to SplitButton, nothing changes

**Expected behavior**
1. Properties should template bind down to the primary button

**Comment by jevansaks** [comment]
Sounds very similar to #203, and I expect the fix would be similar. @JohnnyWestlake do you want to take a crack at the fix? :)
