### ISSUE TITLE
Question: Is it possible to combine ScrollViewer and SwapChainPanel?

### ISSUE THREAD

**Issue by greg904** [microsoft/microsoft-ui-xaml#2675]
Let's say that I am making a browser, a terminal emulator or even a drawing app. I have a big document, and I want to render only a small view (the viewport) of that document at a time in a SwapChainPanel (it has the size of the viewport, not of the document), and I want the user to be able to scroll and pan in this document with a ScrollBar, the mouse wheel, the touch pad or the touch screen.

Is there a way to do this with ScrollViewer? Can I make a custom ScrollViewer that only contains a SwapChainPanel of the size of the viewport and then this ScrollViewer would tell me when the viewport changed so that I can manually render a new frame with the new viewport in my SwapChainPanel?

I know that I could just put a ScrollBar at the right of my SwapChainPanel and then when the user scrolls (using the ValueChanged event on the ScrollBar) update the viewport and render a new frame.

But then using the mouse wheel to scroll on the document would no longer work, because it is separate from the ScrollBar, so I would have to detect mouse wheel events myself and update the ScrollBar accordingly. The same is true for scrolling with a touch pad, scrolling a touch screen, and also panning.

Additionally, if I reimplement this functionality myself, I loose some of the behavior of ScrollViewer:
- The smooth scroll when using the mouse wheel.
- The over scroll effect that appears when the user scrolls too much such that it would go past the end/start of the page, with their touch pad or with a touch screen.
- I think ScrollViewer takes into account OS settings that allow the user to change how many lines should be scrolled per wheel step.
- in conclusion, the scrolling behavior would not be as good as the native one, and would not be consistent with other applications.

Did I miss something here?

I've seen 2 apps that also do it this "hacky" way that I described above:
- The Windows Terminal does it, and the developers had to reimplement some of the stuff themselves like touch pad precision scrolling which created issues (some of them are still not fixed now):
  - https://github.com/microsoft/terminal/issues/1066
  - https://github.com/microsoft/terminal/issues/3109
  - https://github.com/microsoft/terminal/issues/5610
- It looks like the developers of the UWP version of Microsoft Edge have had to reimplement their own ScrollViewer too because it doesn't exactly behave like the system one. For example, when you disable animations in the Windows settings, the scrolling in UWP apps stays smooth but the one in the UWP version of Microsoft Edge is no longer smooth. Also, they modified the amount of pixels that are scrolled, and also possible the scroll animation curve.

It looks like this use of a SwapChainPanel to render content, and a ScrollBar to scroll the content is very common in applications that don't use XAML exclusively to render things. And all of those applications end up being inconsistent with other UWP apps because they have a different scroll  behavior.

So my first question is whether it is possible to somehow reuse parts of the ScrollViewer to implement scrolling with a SwapChainPanel more easily, and consistent to the other UWP apps.

And in case the answer to the first question is no, then my second question is whether the team behind WinUI is considering to fix this issue in the future.

**Comment by StephenLPeters** [comment]
@RBrid Could you weigh in here?

**Comment by RBrid** [comment]
A colleague just suggested this approach:

```
<Grid>
  <SwapChainPanel/>
  <ScrollViewer>
    <StackPanel Width="..." Height="..."/>
  </ScrollViewer>
</Grid>
```
It's a neat idea. The StackPanel is given the large size, while the Grid is given the small one.
The user can interact with the ScrollViewer.  You need to listen to the ScrollViewer.ViewChanged event to update the SwapChainPanel. Of course it'll be UI-thread-bound and rather choppy compared to a regular ScrollViewer content. But I can't think of a better idea with the ScrollViewer.

You won't get everything you were hoping for though. In particular:
- you won't be able to show the overpan effect because the ViewChanged event is not raised during overpan and the HorizontalOffset/VerticalOffset properties are clamped between [0,ScrollableWidth] & [0,ScrollableHeight].
- it won't be as smooth as the ScrollViewer content as noted.

We do work on a new scroller control based on the InteractionTracker Composition component and supporting a "virtual mode" where you provide a fake content size is definitely on our radar.
Thanks for the feedback!

**Comment by greg904** [comment]
Thank you for the answer. Indeed, this is a neat workaround for now and it's also cool that you are working a new component that will solve this! I guess I should close this issue because my question has been answered.
