### ISSUE TITLE
hostpolicy.pdb not loaded error

### ISSUE THREAD

**Issue by Wigmund** [microsoft/microsoft-ui-xaml#2679]
I have done a vanilla creation of a Desktop WinUI 3.0 Preview 1 (Packaged) application and simply run it, but get an error when running the unmodified blank app:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void System.Runtime.InteropServices.ComWrappers.RegisterAsGlobalInstance()'.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ComWrappersSupport.set_ComWrappers(ComWrappers value)
   at WinRT.ComWrappersSupport.InitializeComWrappers(ComWrappers wrappers)
   at TestDesktopUI.Program.Main(String[] args) in xxx\TestDesktopUI\TestDesktopUI\TestDesktopUI\obj\x64\Debug\netcoreapp5.0\win-x64\App.g.i.cs:line 25

Anything I missing or not doing?

Windows Desktop 1909
Visual Studio Version 16.7.0 Preview 2.0

**Comment by weltkante** [comment]
Bad combination of library/framework versions, `RegisterAsGlobalInstance` has been renamed in the .NET Core framework previews. Correct repo is probably [microsoft/CsWinRT](https://github.com/microsoft/CsWinRT) since that contains the WinRT projections.

**Comment by Felix-Dev** [comment]
@Wigmund Please check if you have the .NET 5 Preview **4** x86 & x64 versions insalled and not the newer .NET 5 Preview 5.

**Comment by Wigmund** [comment]
I have .Net preview 5 - will install preview 4 and try again.

**Comment by stevenbrix** [comment]
Yeah, this is a known issue. Here is the issue that is tracking this fix: https://github.com/microsoft/CsWinRT/issues/316

**Comment by Wigmund** [comment]
Removing preview 5 seemed to work, although now (with preview 4 installed) its seems to take an age (10+ minutes!) to load all the debug symbols - is this normal?

**Comment by stevenbrix** [comment]
If you have mixed mode (or native) debugging enabled, then yeah - that would be expected. The WinUI symbols themselves are pretty large and VS doesn't load them on demand.
