### ISSUE TITLE
Performance: ColorPicker/ColorSpectrum Control Poor Performance When Changing Color

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#2683]
# Performance: ColorPicker/ColorSpectrum Control Poor Performance When Changing Color

**Steps to reproduce the bug**

1. Using a ColorPicker control, press on a location within the color spectrum
2. While continuing to press, move the cursor position around the spectrum
3. Notice the color isn't updated until there is a pause or slowdown of movement

**Expected behavior**

The current color understandably can't update continuously, but it needs to update fast enough that the user can see the preview as they move the cursor position. It should not require stopping for a period of time to update.

**Screenshots**

Note: Press was held the entire time

![example](https://user-images.githubusercontent.com/17993847/84729019-a77e1280-af60-11ea-8a8d-c3193fbd6383.gif)

![example1](https://user-images.githubusercontent.com/17993847/84729195-19565c00-af61-11ea-8e64-c09975926c29.gif)

Forgive the compression artifacts and loss of bit depth, gif isn't suited for this use case but is still easiest to show the movement.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4 (reproducible in all versions with ColorPicker)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by sylveon** [comment]
More examples: https://i.imgur.com/rrMxUnF.gifv

Compare this to my own color picker which renders the entire background each time the mouse moves while changing colors (it doesn't use a static image for the spectrum): [it's always snappy](https://i.imgur.com/VQF6QDO.gifv)

**Comment by robloo** [comment]
In the WIP Windows community toolkit's ColorPickerButton I worked around this by only re-rendering every N milliseconds using a timer.

**Comment by sylveon** [comment]
I removed the flyout from ColorSpectrum because it was causing crashing issues in XAML islands and now it's as snappy as my Win32 implementation.

**Comment by robloo** [comment]
@michael-hawker This might explain the crash with ColorPickerButton in islands too.

**Comment by robloo** [comment]
Valid, but isn't worth keeping this open anymore. I think we just have to wait for computers running WinUI to get faster :)
