### ISSUE TITLE
Proposal: Support Custom Formatting and Parsing in NumberBox

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#2684]
# Proposal: Support Formatting of Value in NumberBox

During the original NumberBox spec discussion, it was asked to provide a way to support overriding or customizing the Value format before it is displayed as text in the TextBox (https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-558866275, https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-514110804). This would allow, for example, the double Value to be formatted as:

 1. "17" -> "1' 5"" or "1 foot 5 inches"
 2. "15.23" -> "$15.23 USD"
 3. "1234567890" -> "(123) 456-7890"

## Summary

Relates to: #2055, #1736, #2757

### Data Flow Definition

In order to support formatting of the double Value, the pipeline of parsing and formatting (flow of data) between Text<->Value needs to be clearly defined. This was something missed in the initial NumberBox spec. The current implementation of the NumberBox has undefined behavior if the Text property is changed programmatically and the recommendation is to change only the double Value.

**Text Property Changed**

May happen from User Input, Copy/Paste, Programmatic Input. Evaluation is initially triggered the same as before: on loss of focus, Enter key, etc. The flow of data; however, is now defined to be:

Input Text -> Parser -> double **Value** -> Formatting -> **Text**

Changing the Text value from code would behave as if the user inputted some text. However, what triggers evaluation? There will need to be a new way of triggering the evaluation used in code-behind -- an Evaluate() method.

Also note that the Input Text may be in non-numerical form "1 + (2 * 3)". This Input Text would still be valid in this proposal as formatting is done after the text is already parsed and converted to a double Value.

**Value Property Changed**

Changing the Value directly would go through only the Formatting and the Text step:

**Value** -> Formatting -> **Text**

Unlike Text changed evaluation, any change to the Value property triggers evaluation immediately. There is no need to call Evaluate() or wait for loss of focus, etc.

### Formatting Step

The new step in converting a double Value to final display Text is Formatting. Formatting will be moved into a method that can be overridden:

`protected override string FormatValueOverride(double value) { ... }`

This allows derived controls to customize the conversion of a double Value to the display Text string and apply any rules they would like. A derived control could also add the properties appropriate for controlling formatting.

### Default Formatting Implementation

The NumberBox already has a default formatting implementation and property:

`Windows.Globalization.NumberFormatting.INumberFormatter2 NumberFormatter`

This should be maintained unchanged. This proposal just clarifies where it should happen in the data flow.

Follow up: In the original spec discussion it was mentioned that a custom INumberFormatter2 implementation is not possible (is that a WinRT issue?). Supporting a custom implementation of this interface would allow customizing the format without deriving a new control and overriding the FormatValueOverride() method.

### API Additions

```csharp

// Indicates that the Text property should be re-evaluated and the Value re-calculated.
public void Evaluate();

// Method that can be overridden in derived controls to implement custom formatting
protected override string FormatValueOverride(double value) { ... }

// Method that can be overriden in derived controls to implement custom parsing
protected override double ParseTextOverride(string text) { ... }

```

## Rationale

* Formatting is required in some use cases of the NumberBox. It is undesirable to create new controls when NumberBox can be extended to support this.

## Scope

TBD based on discussion

## Open Questions

 * What about custom parsing? This should be covered here in a similar way. "1' 5"" could then be converted to "17" 
 * How does this support potential future masking? 
 * Numerical rounding may need to be included as an additional step either before, or after, Value is evaluated.

**Comment by robloo** [comment]
@eugenegff Based on https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-514110804, could you provide your comments to this proposal?

**Comment by eugenegff** [comment]
> @eugenegff Based on [#483 (comment)](https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-514110804), could you provide your comments to this proposal?

This proposal is not MVVM friendly, it requires View layer to do the formatting. On the other hand, IValueConverter property would allow to bind to the formatter implemented in Model layer. The same with custom parsing - it is open question in this proposal, but parsing and formatting is tightly coupled in real life, and IValueConverter approach handles it naturally. Also, this proposal requires inheritance for customization, comparing to the simple property setting. One more issue is with customizable custom formatting, i.e. ability to switch from feet to yards to meters. Proposed approach would require creation of several additional dependency properties in class derived from NumberBox to handle this, when for IValueConverter approach another differently configured instance of the converter could be created in single place, and propagated via bindings to all bound NumberBoxes.

**Comment by robloo** [comment]
@eugenegff Good idea! I was unaware of Slider doing this and it is a good way to combine parsing/formatting together in an IValueConverter. I will extend the proposal to include this case as well.

There should now be 3 ways to customize the NumberBox in my opinion:

 1. Supplying a custom implementation of INumberFormatter2. This would only change formatting and leave existing parsing logic. I need to understand why that isn't support currently (or perhaps I recall incorrectly that it isn't)
 2. Supplying an IValueConverter implementation to Convert from value to text and also ConvertBack from text to value (following the Slider ideas).
 3. Support plugging directly into the data flow pipeline by overriding methods in a derived control. This is still useful for advanced cases I think.

**Comment by robloo** [comment]
I'm going to close this because I don't think Microsoft will ever get around to doing it. Personally, I'll try to incorporate this into Avalonia someday.
