### ISSUE TITLE
SwipeControl does not reverse touch gestures for RtL languages

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#2694]
**Describe the bug**
When using SwipeControl, the gestures used to activate the control do not reverse for RtL languages, even though the UI does.

**Steps to reproduce the bug**

1. Create an app with a list of items with SwipeControls, and a Delete option in the RightItems
3. Swipe right-to-left on an item and see the option to Delete appear.
4. Switch to RtL language.
5. Attempt to swipe left-to-right on an item. See that no option appears.
6. Swipe right-to-left. See that the delete swipe item UI animates mirrored (from left to right), the opposite direction of the gesture.

**Expected behavior**
Swipe gestures should reverse when switching to RtL languages.

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.4.2]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
@StephenLPeters reminder for myself :)
