### ISSUE TITLE
Adding a TabViewItem derived class to TabView crashes the application

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2698]
**Describe the bug**

If I add a class derived from `TabViewItem` to TabView, it crashed the application with 
```
ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32)
System.Exception: No installed components were detected. ListViewItemPresenter can only be used as the first child in the template for a ListViewItem.
```
StackTrace from AppCenter

```
System.Runtime.InteropServices
McgMarshal.ThrowOnExternalCallFailed (Int32 hr, RuntimeTypeHandle typeHnd) f:\dd\ndp\fxcore\CoreRT\src\System.Private.Interop\src\Shared\McgMarshal.cs at 1189:13
__Interop
ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32)
__Interop
ForwardComStubs.Stub_12[TThis] (__ComObject, Int32)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelper.<ctor>b__17_1 (Object, UnhandledErrorDetectedEventArgs)
```

**Steps to reproduce the bug**

1. Use following code to add 
```
public class TabularItem : TabViewItem
{
        public TabularItem()
        {
        }
 }
```

```
private void AddTabItem(TabView tabView) 
{
    var newTab = new TabularItem();
 
    // The Content of a TabViewItem is often a frame which hosts a page.
    var frame = new Frame();
    newTab.Content = frame;
    frame.Navigate(typeof(OptionPage));
    tabView.TabItems.Add(newTab);
}
```

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes  |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by Felix-Dev** [comment]
I cannot reproduce this issue on either WinUI 2.4.2 or WinUI 2.5 prerelease:

![image](https://user-images.githubusercontent.com/1398851/84915187-c72a4d80-b0bc-11ea-9bdf-963450a73c29.png)

with this code:
![image](https://user-images.githubusercontent.com/1398851/84915318-e9bc6680-b0bc-11ea-9f56-0f25145ca303.png)

(so New Tab 4/5 are all `TabularItem` objects - added in the `AddTabButtonClick` event handler)

Unfortunately I cannot test it on WinUI 2.4.0 because I'm getting unrelated build errors there:
![image](https://user-images.githubusercontent.com/1398851/84914473-ef657c80-b0bb-11ea-826f-4a8c54ef01eb.png)

**Comment by harvinders** [comment]
Are you doing it on 1803? Another thing I failed to mentioned it comes in
release build only. There were other issues with TavView in 1803 also.

**Comment by Felix-Dev** [comment]
@harvinders I'm running on Windows 2004 built with 1903 SDK.  

Good point about the release build! I can confirm this crashes the app upon adding a sub-classed `TabViewItem` object to the TabView as shown in the code above:

![image](https://user-images.githubusercontent.com/1398851/84958721-43915080-b0fe-11ea-9303-70f512a0c21f.png)

**Comment by StephenLPeters** [comment]
@ranjeshj for FYI, issue only repro's in release builds.

**Comment by ranjeshj** [comment]
Try adding the Bindable attribute on the custom type. In debug builds the metadata is obtained through reflection but in release builds it is code gen which causes issues like this one.  [This issue](https://github.com/microsoft/microsoft-ui-xaml/issues/2086) documents a couple of differences between debug and release builds.
````
 [Bindable]
    public class MyTabViewItem: TabViewItem
    {
        public MyTabViewItem()
        {
            Content = "new";
        }
    }
```

**Comment by harvinders** [comment]
@ranjeshj I just tested it, the fix works.
