### ISSUE TITLE
TreeView with derived TreeViewNodes crashes in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#2699]
**Describe the bug**

TreeView using derived TreeViewNodes causes crash in WinUI3 Desktop. TreeView using derived TreeViewNodes works in UWP.

**Steps to reproduce the bug**

1. Checkout [WinUI3 Problems TreeView repository](https://github.com/eleanorleffler/WinUI3_Problems_TreeView). 
2. Go to TreeViewWinUI folder.
3. Open the TreeViewWinUI solution.
4. Build and Run with Debug x64.
5. You should see that an exception was thrown. See Screenshot#1 for details.

**Expected behavior**

We expect the TreeView using inherited TreeViewNodes to behave as it does in UWP. We expect to see two TreeViews - one on the left and another on the right. 

See Screenshot#2 for exact expected behavior. 

Build and run TreeViewUWP solution inside the TreeViewUWP folder to see expected behavior.

**Screenshots**

![TreeViewCurrentBehavior](https://user-images.githubusercontent.com/9272634/84907659-164e8f00-b079-11ea-93ea-015e97d17a7e.PNG)

Screenshot#1 - Current Behavior

![TreeViewExpectedBehavior](https://user-images.githubusercontent.com/9272634/84907688-1fd7f700-b079-11ea-9e24-44492e6cda9a.PNG)
Screenshot#2 - Expected Behavior

**Version Info**

NuGet package version: 

[Microsoft.VCRTForwarders.140 1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

Targeting:
Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1809 (10.0; Build 17763)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |                       |
| November 2019 Update (18363)  	 |                       |
| May 2019 Update (18362)            |                       |
| October 2018 Update (17763)        | Yes                   |
| April 2018 Update (17134)          |                       |
| Fall Creators Update (16299)       |                       |
| Creators Update (15063)            |                       |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop               | Yes                  |
| Mobile                |                      |
| Xbox                  |                      |
| Surface Hub           |                      |
| IoT                   |                      |

**Additional context**

 Extra debugging
 - If we collapse treeView1, the application still crashes.
	To replicate this, change the Visibility on line 34 in MainWindow.xaml to "Collapsed".
	Line 34: `Visibility="Collapsed"/>`
 
 - However, if we collapse treeView2, the application runs, but does not display the TreeView with the inherited TreeViewNodes.
	To replicate this, change the Visibility on line 40 in MainWindow.xaml to "Collapsed".
	Line 40: `Visibility="Collapsed"/>`

**Comment by StephenLPeters** [comment]
@stevenbrix This sounds familiar, is there a CSWinrt issue that is preventing deriving from types?

**Comment by anawishnoff** [comment]
This bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!
