### ISSUE TITLE
Windows.UI.Xaml Exception

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2701]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1080162/windowsuixaml-exception.html)._

---
The Exception was:

>Unhandled exception at 0x00007FFD287D3530 (Windows.UI.Xaml.dll) in Sentry.UWP.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001EE6B0FA120, 0x0000000000000002).

The call stack was:

>>	KernelBase.dll!RaiseFailFastException()	Unknown
 	combase.dll!00007ffd3d79735b()	Unknown
 	Windows.UI.Xaml.dll!DirectUI::ErrorHelper::ProcessUnhandledError(DirectUI::ErrorInfo & errorInfo, unsigned int fSkipFailFastIfNoErrorContext, unsigned int * pfHandled) Line 618	C++
 	Windows.UI.Xaml.dll!DirectUI::FinalUnhandledErrorDetectedRegistration::OnFinalUnhandledErrorDetected(IInspectable * pSender, Windows::ApplicationModel::Core::IUnhandledErrorDetectedEventArgs * pArgs) Line 1013	C++
 	[Inline Frame] Windows.UI.Xaml.dll!Microsoft::WRL::Callback::__l2::<lambda_fa46ac39691f4ca87fe78d9a3f2f4de1>::operator()(IInspectable * &&) Line 327	C++
 	Windows.UI.Xaml.dll!Microsoft::WRL::Details::DelegateArgTraits<long (__cdecl Windows::Foundation::IEventHandler_impl<Windows::Foundation::Internal::AggregateType<Windows::ApplicationModel::Core::UnhandledErrorDetectedEventArgs *,Windows::ApplicationModel::Core::IUnhandledErrorDetectedEventArgs *>>::*)(IInspectable *,Windows::ApplicationModel::Core::IUnhandledErrorDetectedEventArgs *)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,Windows::Foundation::IEventHandler<Windows::ApplicationModel::Core::UnhandledErrorDetectedEventArgs *>,Microsoft::WRL::FtmBase>,<lambda_fa46ac39691f4ca87fe78d9a3f2f4de1>,-1,IInspectable *,Windows::ApplicationModel::Core::IUnhandledErrorDetectedEventArgs *>::Invoke(IInspectable * <args_0>, Windows::ApplicationModel::Core::IUnhandledErrorDetectedEventArgs * <args_1>) Line 245	C++
 	twinapi.appcore.dll!Windows::Internal::Details::GitInvokeHelper<struct Windows::Foundation::IEventHandler<class Windows::ApplicationModel::Core::UnhandledErrorDetectedEventArgs *>,class Windows::Internal::GitPtr,2>::Invoke(struct IInspectable *,struct Windows::ApplicationModel::Core::IUnhandledErrorDetectedEventArgs *)	Unknown
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::UnhandledErrorInvokeHelper::Invoke(struct IInspectable *,struct Windows::ApplicationModel::Core::IUnhandledErrorDetectedEventArgs *)	Unknown
 	twinapi.appcore.dll!Microsoft::WRL::InvokeTraits<2>::InvokeDelegates<<lambda_d3aa4dff9873c46d1acd593e89259f7b>,Windows::Foundation::IEventHandler<Windows::ApplicationModel::Core::UnhandledErrorDetectedEventArgs *>>()	Unknown
 	twinapi.appcore.dll!Microsoft::WRL::EventSource<Windows::Foundation::IEventHandler<Windows::ApplicationModel::Core::UnhandledErrorDetectedEventArgs *>,Microsoft::WRL::InvokeModeOptions<2>>::DoInvoke<<lambda_d3aa4dff9873c46d1acd593e89259f7b>>()	Unknown
 	twinapi.appcore.dll!Microsoft::WRL::EventSource<struct Windows::Foundation::IEventHandler<class Windows::ApplicationModel::Core::UnhandledErrorDetectedEventArgs *>,struct Microsoft::WRL::InvokeModeOptions<2> >::InvokeAll<std::nullptr_t,class Windows::ApplicationModel::Core::UnhandledErrorDetectedEventArgs *>(std::nullptr_t,class Windows::ApplicationModel::Core::UnhandledErrorDetectedEventArgs *)	Unknown
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplication::ForwardLocalError(struct IRestrictedErrorInfo *)	Unknown
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationFactory::ForwardLocalError(struct IRestrictedErrorInfo *)	Unknown
 	combase.dll!00007ffd3d795eb0()	Unknown
 	System.Private.CoreLib.dll!00007ffcbeade064()	Unknown
 	System.Private.CoreLib.dll!00007ffcbeaa3da4()	Unknown
 	System.Private.CoreLib.dll!00007ffcbeaa3ece()	Unknown
 	00007ffc6226b63f()	Unknown
 	coreclr.dll!ExceptionTracker::CallHandler(unsigned __int64 uHandlerStartPC, StackFrame sf, EE_ILEXCEPTION_CLAUSE * pEHClause, MethodDesc * pMD, EHFuncletType funcletType) Line 3423	C++
 	coreclr.dll!ExceptionTracker::CallCatchHandler(_CONTEXT * pContextRecord, bool * pfAborting) Line 646	C++
 	coreclr.dll!ProcessCLRException(_EXCEPTION_RECORD * pExceptionRecord, unsigned __int64 MemoryStackFp, _CONTEXT * pContextRecord, _DISPATCHER_CONTEXT * pDispatcherContext) Line 1177	C++
 	[External Code]	
 	coreclr.dll!ClrUnwindEx(_EXCEPTION_RECORD * pExceptionRecord, unsigned __int64 ReturnValue, unsigned __int64 TargetFrameSp, unsigned __int64) Line 5326	C++
 	coreclr.dll!ProcessCLRException(_EXCEPTION_RECORD * pExceptionRecord, unsigned __int64 MemoryStackFp, _CONTEXT * pContextRecord, _DISPATCHER_CONTEXT * pDispatcherContext) Line 1132	C++
 	[External Code]	
 	coreclr.dll!RaiseTheExceptionInternalOnly(Object * throwable, int rethrow, int fForStackOverflow) Line 2996	C++
 	coreclr.dll!IL_Throw(Object * obj) Line 4860	C++
 	[External Code]	
 	coreclr.dll!COMToCLRDispatchHelper() Line 290	Unknown
 	[Inline Frame] coreclr.dll!InvokeStub(ComCallMethodDesc *) Line 262	C++
 	[Inline Frame] coreclr.dll!COMToCLRInvokeTarget(unsigned __int64) Line 424	C++
 	[Inline Frame] coreclr.dll!COMToCLRWorkerBody(Thread *) Line 556	C++
 	coreclr.dll!COMToCLRWorker(Thread * pThread, ComMethodFrame * pFrame) Line 807	C++
 	coreclr.dll!GenericComCallStub() Line 138	Unknown
 	[External Code]

---
#### Visual Studio Feedback System on 6/17/2020, 03:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
The callstack looks pretty useless, I'm not sure this is actionable.  @codendone do you think it would be possible to find an associated crash dump?

**Comment by codendone** [comment]
@StephenLPeters I agree the stack not useful, and there isn't enough information to search for dumps.

**Comment by StephenLPeters** [comment]
Closing this as not actionable then.
