### ISSUE TITLE
DataGrid Not Displaying in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#2703]
**Describe the bug**

The CommunityToolKit DataGrid works in UWP but once transferred over to WinUI3 Desktop, the DataGrid does not display anything. See Screenshot#1 for current behavior.

The DataGrid is loading because the dataGrid_AutoGeneratingColumn event is called.

**Steps to reproduce the bug**
1. Clone [WinUI3 Problems DataGrid repository](https://github.com/eleanorleffler/WinUI3_Problems_DataGrid).
2. Go to the DataGridWinUI folder.
3. Open the DataGridWinUI solution in Visual Studio 2019 Preview.
3. Build and run with Debug x64.
4. You should see that the DataGrid does not appear.

**Expected behavior**

We expect to see the DataGrid filled with 4 customers, the same behavior as we saw in UWP. See Screenshot#2. 

Build and run the DataGridUWP solution in the DataGridUWP folder to see expected behavior.

**Screenshots**

![DataGridBlank](https://user-images.githubusercontent.com/9272634/84948915-030be580-b0b2-11ea-89a7-2bba9f6995ad.PNG)
Screenshot#1 - Current Behavior

![DataGridExpectedBehavior](https://user-images.githubusercontent.com/9272634/84948939-0901c680-b0b2-11ea-9f04-441c30ae62cd.PNG)
Screenshot#2 - Expected Behavior

**Version Info**

NuGet package version: 

[Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 8.0.0-preview1]
[Microsoft.VCRTForwarders.140 1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

Targeting:

Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1809 (10.0; Build 17763)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |                       |
| November 2019 Update (18363)  	 |                       |
| May 2019 Update (18362)            |                       |
| October 2018 Update (17763)        | Yes                   |
| April 2018 Update (17134)          |                       |
| Fall Creators Update (16299)       |                       |
| Creators Update (15063)            |                       |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop               | Yes                  |
| Mobile                |                      |
| Xbox                  |                      |
| Surface Hub           |                      |
| IoT                   |                      |

**Comment by RBrid** [comment]
This is caused by https://github.com/microsoft/CsWinRT/issues/345. While we wait for that to be fixed, try to work around this problem by adding this line to an application's app.xaml file:
`<ResourceDictionary Source="ms-appx:///Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGrid.xaml"/>`

```
<Application
 x:Class="..."
 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
 xmlns:local="using:...">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
        <!-- Other merged dictionaries here -->
        <ResourceDictionary Source="ms-appx:///Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGrid.xaml"/>
      </ResourceDictionary.MergedDictionaries>
      <!-- Other app resources here -->
    </ResourceDictionary>
  </Application.Resources>
</Application>
```

Sorry for the inconvenience.

**Comment by eleanorleffler** [comment]
Hi @RBrid , 

Thank you for the workaround! 

Just an update, the workaround allows the DataGrid to display! However, we have come across crashes when we click on a cell or scroll vertically. We also noticed when we programmatically add styling to the DataGridColumnHeader, the header disappears. Are these issues related to this original issue?

**Comment by RBrid** [comment]
@eleanorleffler, please have a look at https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3374.  Those changes in the WCT winui branch should address the crashes.   But I am not aware of the DataGridColumnHeader styling problems. Feel free to open a new issue for that. Thanks, -R

**Comment by eleanorleffler** [comment]
@RBrid We will be looking out for the next release of the Community Toolkit and will be opening a new issue for that styling problem! Thanks!

**Comment by anawishnoff** [comment]
This bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!
