### ISSUE TITLE
Unable to Enter Text into TextBox inside ContentDialog in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#2704]
**Describe the bug**

In WinUI3 Desktop, we are unable to type in text into the TextBoxes inside ContentDialogs with some exceptions.

More detailed observations and debugging below in the "Additional Context" section.

**Steps to reproduce the bug**

1. Clone our [WinUI3 Problems TextBox repository](https://github.com/eleanorleffler/WinUI3_Problems_TextBox).
2. Go to the TextBoxWinUI folder.
2. Open the TextBoxWinUI solution.
3. Build and run with Debug x64.
4. Once the application is loaded, click the "Click me" button.
5. Without clicking or clicking away from or outside of the application window, start typing into the TextBox.
6. No characters should appear - unless actions described in the "Additional context" are performed.

**Expected behavior**

We expect text to appear within the textbox when typing. We expect to see the same behavior we saw in UWP. 

Build and run the TextBoxUWP solution inside the TextBoxUWP folder to see expected behavior.

**Screenshots**

![TextBoxCurrentBehavior](https://user-images.githubusercontent.com/9272634/84950397-744c9800-b0b4-11ea-9ca7-953d76a34f7e.PNG)

Screenshot#1 - TextBox inside ContentDialog

**Version Info**

NuGet package version: 
[Microsoft.VCRTForwarders.140 1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

Targeting:
Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1809 (10.0; Build 17763)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |                       |
| November 2019 Update (18363)  	 |                       |
| May 2019 Update (18362)            |                       |
| October 2018 Update (17763)        | Yes                   |
| April 2018 Update (17134)          |                       |
| Fall Creators Update (16299)       |                       |
| Creators Update (15063)            |                       |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop               | Yes                  |
| Mobile                |                      |
| Xbox                  |                      |
| Surface Hub           |                      |
| IoT                   |                      |

**Additional context**

- When trying to type into the TextBox immediately, no characters appear.

- When trying to type quickly with many characters into the TextBox immediately, the text cursor seems to freeze up and not blink.

- However, after clicking away from or outside of the application window, we are able to type in a subset of characters into the TextBox. This subset includes: 
	- These characters which use the same 5 keys with and without the shift key: []{}'"\|`~
	- Backspace key works.
	- Characters created using the Alt key and numeric keypad (e.g. Alt-65 for "A").
	- Characters copied from elsewhere can be pasted into the TextBox.

**Comment by dynamiquel** [comment]
I'm having the same issue, is there no workaround? My app depends on ContentDialogs with text boxes.

**Comment by ranjeshj** [comment]
@Austin-Lamb @JesseCol @anawishnoff  as FYI.

**Comment by smj389** [comment]
Just to say, I have the same problem with Preview 2.

**Comment by Austin-Lamb** [comment]
This bug appears to be fixed internally, hopefully it will be in Preview 3 later this year.

**Comment by smj389** [comment]
@Austin-Lamb  I am having this issue in Preview 3 as well.

**Comment by smj389** [comment]
@anawishnoff Sorry for pinging you as well - I just want to make sure it is known that this bug still exists in WinUI Preview 3.0, and is not fixed as @Austin-Lamb predicted on Sep 3.

**Comment by anawishnoff** [comment]
No problem @smj389 - we're actively looking into this and I hope to report back soon!

**Comment by smj389** [comment]
I am also experiencing the same issue with Flyouts.

**Comment by crramirez** [comment]
Please add this to the WinUI 3.0 Milestone. The march version shouldn't be shipped without this been solved.

**Comment by anawishnoff** [comment]
@smj389, @crramirez It looks like this bug will be fixed in the next release of WinUI 3.

**Comment by anawishnoff** [comment]
Confirming - this bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!

**Comment by crramirez** [comment]
Wiiiii, thanks a lot for letting us know.

**Comment by AlexeiNaabal** [comment]
The label `fixed-internally` was removed, does it means this issue is still exists? Does this issue being investigating?

**Comment by codendone** [comment]
@AlexeiNaabal `fixed-internally` was removed because the fix was released long ago.
