### ISSUE TITLE
Image not always showing

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#2708]
**Describe the bug**
I have a problem that an Image is not always showing.

**Steps to reproduce the bug**

1. Create a UWP app in Visual Studio 
2. Create an Images folder in the Assets folder
3. Add an image in this folder, for example **chip.png**

```xml
<Page x:Class="ImageTest.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:local="using:ImageTest"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
      mc:Ignorable="d">

    <Grid>
        <StackPanel Height="200"
                    HorizontalAlignment="Center"
                    Orientation="Horizontal">
            <Image Source="/Assets/Images/chip.png" />
            <Image Source="/Assets/Images/chip.png" />
            <Image Source="/Assets/Images/chip.png" />
        </StackPanel>
    </Grid>
</Page>
```

When you run the app it works most of the times correctly.

![image](https://user-images.githubusercontent.com/9335559/85022302-64e05400-b173-11ea-8129-4110fb784fd9.png)

Sometimes though you get only one image shown. Not often, maybe one in the 50 starts. In the screenshot below the 3rd chip image is shown, the first two are not. It can also happen that the first one or second one is shown, they others not. One is always shown.

![image](https://user-images.githubusercontent.com/9335559/85022280-5db94600-b173-11ea-8dd7-2e2324f45519.png)

If you resize the Window the two other images will be shown automatically. 

Maybe this issue is related to this [tweet](https://twitter.com/RudyHuyn/status/1270820308656611329) from @rudyhuyn. I know this issue is hard to reproduce which makes it "impossible" to solve. Believe me it is there. 

**Expected behavior**
Always have all images shown

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)  | Yes  |
| November 2019 Update (18363)  | Yes |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
@sonnemaf do you know if this is unique to a specific version of WinUI or if it reproduces using system xaml as well?

@gegao18 This makes me think there is a race condition resulting in a stale rendering property. Do you recognize or have thoughts on the issue?

**Comment by sonnemaf** [comment]
I'm not using WinUI. It is just plain UWP. Just used this repository to log the Issue. It will become a WinUI 3 issue eventually.

**Comment by StephenLPeters** [comment]
Thanks! I ask because it helps us track down the issue because we have a better idea of where to look.
