### ISSUE TITLE
navigationview width

### ISSUE THREAD

**Issue by tharun916** [microsoft/microsoft-ui-xaml#2709]
i want  reduce the width of  navigation view pane. how?

**Comment by Felix-Dev** [comment]
See these two properties of the NavigationView:
* [OpenPaneLength](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.navigationview.openpanelength?view=winui-2.4#Microsoft_UI_Xaml_Controls_NavigationView_OpenPaneLength)
* [CompactPaneLength](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.navigationview.compactpanelength?view=winui-2.4#Microsoft_UI_Xaml_Controls_NavigationView_CompactPaneLength)
