### ISSUE TITLE
Proposal: Expose  InputScope property on NumberBox

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#2710]
In this PR #2605 we set the default InputScope property to Number, however it was brought up that there are quite a few values that make sense in numberbox's case and that we should expose this an an API on numberbox.

**Comment by robloo** [comment]
Related to #1912, InputScope will be exposed as a DependencyProperty on the NumberBox itself. I'll take this one -- I'm sure I'll have some questions related to IDL and projection along the way but it's good to learn.

I copied the discussion from the PR if anyone is interested in the future:

> Should this property be exposed so that developers can set it if they choose to without re-templating? I'm thinking about scenarios such as Currency or TimeHour, etc.

...

> As a NumberBox I don't think this really needs to be configurable. The only concern we talked through was in terms of operators +-() etc. However, those are all in the Number virtual keyboard as documented here: https://docs.microsoft.com/en-us/windows/uwp/design/input/use-input-scope-to-change-the-touch-keyboard#number
>
>Additionally, I'm just implementing what @SavoySchuler had already speced out based on our original discussions for the NumberBox spec https://github.com/microsoft/microsoft-ui-xaml/issues/1912#issuecomment-588003232.
>
>> I believe this is not a proposal, but a bug as NumberBox's spec notes here that "Number" should be the InputScope of NumberBox: https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/NumberBox/NumberBox.md#input-scope

> I ended up going through the [InputScopeNameValue Enum](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Input.InputScopeNameValue?view=winrt-19041) and realize @karenbtlai has a good point. I somehow missed the `Currency` and `TimeHour` examples in her comment so wasn't thinking this through as deeply. That said, I think the actual virtual keyboard doesn't have all these cases implemented separately so value added at this point is unknown.
>
>Entries that require numerical-only input:
>`CurrencyAmount`, `CurrencyAmountAndSymbol`, `DateDayNumber`, `DateMonthNumber`, `DateYear`, `TimeHour`, `TimeMinutesOrSeconds`, `Digits`, `Number`, `NumberFullWidth`, `NumericPassword`, `NumericPin`, `TelephoneAreaCode`, `TelephoneCountryCode`, `TelephoneLocalNumber`, `TelephoneNumber`
>
>`Formula` and `FormulaNumber` may be needed in the future if the forumla is preserved and not immediately evaluated by the number box.
>
> The telephone input scopes would be a lot more useful if we had formatted supported. But we should still support that as hopefully it's added in the future.
>
> I'll wait for additional feedback but am leaning towards making this a DP now.
