### ISSUE TITLE
Resources and binding

### ISSUE THREAD

**Issue by Wigmund** [microsoft/microsoft-ui-xaml#2712]
I have an application which uses ViewModel to View resolution via DataTemplates:

`<DataTemplate x:Name="dtStartPageView" x:DataType="vms:StartPageViewModel">`
`   <local:StartPageView />`
` </DataTemplate>`

`<ContentControl Content="{x:Bind ViewModel.CurrentViewModel, Mode=OneWay}" />`

However, using .Net 5 preview 4 and WinUI 3 preview 1 I cannot find anyway to get it work to work (similar to that of WPF), I've tried:

- Adding the DataTemplate to App Resources - "DataType" property not found
- Adding the DataTemplate to Window Resources - Doesn't exist
- Adding the DataTemplate to Page Resource - Doesn't resolve content ViewModel to View
- Adding the DataTemplate to root Grid resource - Doesn't resolve content ViewModel to View

Is this supported yet? Will it be? Am I doing something wrong?
I want a way for a content control or page to bind to a given viewmodel and it create the specified view and have the newly created view's datacontext bound to the viewmodel.

**Comment by StephenLPeters** [comment]
@MikeHillberg @RealTommyKlein @fabiant3 FYI. I'm not sure this is expected to work but will defer to you.

**Comment by JeanRoca** [comment]
@Wigmund it looks like this is not supported yet and we would be looking into it post WinUI 3.0

**Comment by tuggernuts** [comment]
Hi, is there any progress on this?

**Comment by RealTommyKlein** [comment]
Is the repro stating that `StartPageView.xaml` has the `{x:Bind ViewModel.CurrentViewModel, Mode=OneWay}`  statement, which developers expect to resolve to the `StartPageViewModel` data context outside of `StartPageView.xaml`'s definition?  If so, x:Bind can only resolve to things within its immediate `.xaml` file scope, and doesn't support "duck-binding" to properties/contexts outside of the `.xaml` file it's used in - for that, `{Binding}` would work.
