### ISSUE TITLE
Change in Appearance of AppBarButton with Flyout on CommandBar in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#2714]
**Describe the bug**

We used a CommandBar with AppBarButton with a Flyout in our UWP application. However, once we switched over to WinUI3 Desktop, the appearance of the button changed. 

The button in the WinUI application has a ">" next to the icon whereas the UWP application did not. 

See Screenshots below to compare differences.

**Steps to reproduce the bug**

1. Clone the [WinUI3 Problems CommandBarFlyout repository](https://github.com/eleanorleffler/WinUI3_Problems_CommandBarFlyout).
2. Go to the CommandBarFlyoutWinUI folder.
3. Open the CommandBarFlyoutWinUI solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Notice the additional ">" next to the first icon in the CommandBar on the right side of the application.

**Expected behavior**

We expect to see no difference in the UWP and WinUI3 Desktop CommandBar buttons. The button in the WinUI3 Desktop application should only be the AppBarButton icon.

Build and run the CommandBarFlyoutUWP inside the CommandBarFlyoutUWP folder to see expected behavior.

**Screenshots**

![CommandBarFlyoutExpectedAppearance](https://user-images.githubusercontent.com/9272634/85137839-6e1b0080-b207-11ea-973a-de193035452f.PNG)

Screenshot#1 - Expected Appearance (UWP)

![CommandBarFlyoutCurrentAppearance](https://user-images.githubusercontent.com/9272634/85137904-87bc4800-b207-11ea-8850-3506aa66d24e.PNG)

Screenshot#2 - Current Appearance (WinUI3 Desktop)

**Version Info**

NuGet package version:

[Microsoft.VCRTForwarders.140 1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

Targeting:

Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1809 (10.0; Build 17763)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |                       |
| November 2019 Update (18363)  	 |                       |
| May 2019 Update (18362)            |                       |
| October 2018 Update (17763)        | Yes                   |
| April 2018 Update (17134)          |                       |
| Fall Creators Update (16299)       |                       |
| Creators Update (15063)            |                       |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop               | Yes                  |
| Mobile                |                      |
| Xbox                  |                      |
| Surface Hub           |                      |
| IoT                   |                      |

**Comment by marb2000** [comment]
Sorry for the late response. 
@eleanorleffler, I think that we already sync the UWP and Desktop styles. Closing this bug. Please, feel free to open it in case I miss something.

**Comment by eleanorleffler** [comment]
Hi @marb2000 , 

I have actually opened a new issue for Preview 4 (#4197) - closing this issue is fine, but the bug can be replicated in Preview 4!
