### ISSUE TITLE
Proposal: NavigationView: Add theme resources to enable easy flyout padding customization

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2718]
# Proposal: NavigationView: Add theme resources to enable easy flyout padding customization

## Summary
In the review of the hierarchical NavigationView PR it was [suggested](https://github.com/microsoft/microsoft-ui-xaml/pull/2004#pullrequestreview-376317815) to create theme resources to enable easy customization of the overflow menu padding in *Top* PaneDisplayMode and the children flyout padding in closed compact mode. This proposal aims to introduce two theme resources to customize these two paddings:
* TopNavigationViewOverflowMenuPadding
* NavigationViewItemChildrenMenuFlyoutPadding

Why two resources instead of one? Logically, the content of both flyouts differ. One flyout lists the children for a menu item, whereas the overflow menu lists distinct top-level items (including their children if any). As such it could make sense to give customers the ability to choose a different padding for these two different flyout types.

I'm proposing using "MenuFlyout" instead of just "Menu" for the children flyout padding theme resource as children can also be displayed inline (in Left mode) and I'm not sure if `NavigationViewItemChildrenMenuPadding` would make it clear that this resource only affects the padding when the children are displayed inside a flyout and not inline. As such, I picked "MenuFlyout" to make it crystal clear when the padding will be applied.
I don't believe adding "Flyout" to the `TopNavigationViewOverflowMenuPadding` name is required as the [documentation](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#top-to-left-navigation) also only speaks of the "overflow menu" and not the "overflow menu flyout".

## Rationale
According to @YuliKl a "small but non-zero percentage of customers" likely want to customize these flyout paddings. Adding theme resources will enable these customers to do just that.

CC @StephenLPeters @ojhad @YuliKl

**Comment by StephenLPeters** [comment]
@anawishnoff I think you or @YuliKl would like to take a look at this.

**Comment by anawishnoff** [comment]
Thanks for posting this! Sorry for the delay here - this definitely seems like an overall win and a relatively easy way to make sure customers can customize their UI as they wish. Also a nice non-intrusive solution being resources.

I'm ok with the naming scheme. I think I lean towards TopNavigationViewOverflowMenuFlyoutPadding as it keeps things consistent, but it is pretty long. But as long as the overflow menu is never NOT a flyout, your naming scheme should be fine.

**Comment by Felix-Dev** [comment]
@anawishnoff Yes, naming it `TopNavigationViewOverflowMenuFlyoutPadding` would make it consistent with `NavigationViewItemChildrenMenuFlyoutPadding`. As I wrote above, I picked *TopNavigationViewOverflowMenuPadding* to match the current UWP NavigationView documentation. That said, I'm fine using *TopNavigationViewOverflowMenuFlyoutPadding* instead if you feel a bit better about that and I don't think we have to worry about the Overflow menu not represented via a flyout for the forseeabe future.

Should I pick *TopNavigationViewOverflowMenuFlyoutPadding* then?

**Comment by anawishnoff** [comment]
Thanks, the more I think about it, it seems like we should stay consistent with the docs. As you mentioned, it's highly unlikely there'll be an overflowmenu that isn't a flyout. I'm giving you the go-ahead from me on your original naming scheme and proposal😊.
