### ISSUE TITLE
Discussion: [Class library project for WinUI3 C++]

### ISSUE THREAD

**Issue by jeganrajm** [microsoft/microsoft-ui-xaml#2726]
# Discussion: [Class library project for WinUI3 C++] 
Is there any separate class library project in WinUI3 C++, or how to create component in WinUI3 C++

## Related Links
https://marketplace.visualstudio.com/items?itemName=Microsoft-WinUI.WinUIProjectTemplates
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/

**Comment by Jaiganeshkumaran** [comment]
Use Windows Runtime Component, Static Library or Dynamic Link Library.

**Comment by jeganrajm** [comment]
@Jaiganeshkumaran  But i cant refer Windows Runtime Component in WinUI UWP project.

**Comment by Jaiganeshkumaran** [comment]
> @Jaiganeshkumaran But i cant refer Windows Runtime Component in WinUI UWP project.

What error do you get?

**Comment by jeganrajm** [comment]
> > @Jaiganeshkumaran But i cant refer Windows Runtime Component in WinUI UWP project.
> 
> What error do you get?

Error	MDM2009	Duplicate type Microsoft.UI.Composition.CompositionBackfaceVisibility found processing metadata file ...\Debug\RuntimeComponent2\Microsoft.UI.winmd, type already exists in file ..\App1\packages\Microsoft.WinUI.3.0.0-preview1.200515.3\lib\uap10.0\Microsoft.UI.winmd.

**Comment by ranjeshj** [comment]
@stevenbrix as FYI

**Comment by JeanRoca** [comment]
@jeganrajm does this still repro in our [latest preview](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)?

**Comment by shelllet** [comment]
yeah! I have same problem in winui3-preview4 .

**Comment by asklar** [comment]
Duplicate of #1597, and ultimately microsoft/cppwinrt#452

You can try to work around this by adding this to your project:
```xml
<ItemDefinitionGroup>
    <Reference>
        <Private Condition="'$(ConfigurationType)' != 'Application'">false</Private>
    </Reference>
</ItemDefinitionGroup>
```

The fix must come from the sdk (mdmerge)
