### ISSUE TITLE
XAML Islands failing with NVidia chipsets on WPF

### ISSUE THREAD

**Issue by crutkas** [microsoft/microsoft-ui-xaml#2729]
XAML Islands with a WPF main app is failing to render when run against a NVidia chipset in non-elevated mode.

https://github.com/microsoft/PowerToys/issues/3384

How we can repro it is with systems running Nvidia's nView Desktop Manager .  Here is the issue with the basic WPF Xaml Island Sample (https://github.com/microsoft/Xaml-Islands-Samples - WPF_XAMLIslands_v1). 

When nView is disabled
![image](https://user-images.githubusercontent.com/1462282/85060899-d3fd7e80-b15a-11ea-889a-279264bac6de.png)

When nView is enabled 
![image](https://user-images.githubusercontent.com/1462282/85060863-c811bc80-b15a-11ea-9494-bcd008caf898.png)

Reason why when settings is run as Admin no one hits it is nView runs on the user level.  When Settings is elevate, nView can't touch the process.

Under the hood, basically a visibility flag is getting set when it shouldn't.  More importantly, we didn't set the flag to hide it.

**Comment by crutkas** [comment]
https://github.com/microsoft/PowerToys/pull/4428 is our workaround

**Comment by crutkas** [comment]
We've just verified a second nVidia bug with WPF.  https://github.com/microsoft/PowerToys/issues/3407 is our tracking issue.

**Comment by Jay-o-Way** [comment]
Any update for this?

**Comment by crutkas** [comment]
Hi xaml team, any update here?
