### ISSUE TITLE
menubar not working

### ISSUE THREAD

**Issue by tharun916** [microsoft/microsoft-ui-xaml#2732]
i added a menubar to the titlebar, but menubar not working. please solve this isuue
![image](https://user-images.githubusercontent.com/34917430/85392576-54f8b380-b569-11ea-8cea-c88e12662320.png)

![image](https://user-images.githubusercontent.com/34917430/85392395-14993580-b569-11ea-82a1-e441d8cd867c.png)

**Comment by michael-hawker** [comment]
🦙 @tharun916 if the background is set on the AppTitleBar grid it won't work, it'll take the input, see the note [here in the docs](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#draggable-regions). You'll also need to layer them separately and make sure the background of the MenuBar where you want to still be able to drag the window is also Transparent.

You can look at the similar [TabView type scenario I did in the Windows Community Toolkit here](https://github.com/windows-toolkit/Sample-TabView-TearOff#optional-tabs-in-titlebars).

**Comment by ranjeshj** [comment]
Thanks for sharing this @michael-hawker .
