### ISSUE TITLE
Bug: Scroll viewer's scrollbar is fully visible on touch enabled device

### ISSUE THREAD

**Issue by ivayle** [microsoft/microsoft-ui-xaml#2733]
**Describe the bug**

When text block is wrapped within scroll viewer on touch enabled device, the scrollbar is fully visible but not functional.

**Steps to reproduce the bug**

1. Create an empty UWP app
2. Create text block with long text within scroll viewer

```
    <Page.Resources>
        <x:String x:Key="DummyText">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing </x:String>
    </Page.Resources>

    <Grid>
        <ScrollViewer>
            <TextBlock Text="{StaticResource DummyText}"
                       TextWrapping="Wrap" />
        </ScrollViewer>
    </Grid>
```
3. Run the application on touch enabled device or simulator

**Actual behavior**

![image](https://user-images.githubusercontent.com/4266678/85401740-2f68ab80-b563-11ea-9582-0999d6b3ee74.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/4266678/85401810-51fac480-b563-11ea-9583-425f4617acad.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@ivayle can you check if you have the automatically hide scrollbars feature in system settings turned off ?
![image](https://user-images.githubusercontent.com/28935693/85625757-c8113100-b620-11ea-957d-dcb03007cf65.png)

**Comment by ivayle** [comment]
Yes, it is on.

![image](https://user-images.githubusercontent.com/4266678/86370801-d5659580-bc88-11ea-9bbe-80db6dab95dd.png)

**Comment by StephenLPeters** [comment]
@ivayle I just ran your code sample on my machine (touch monitor) and am not able to reproduce the issue of the scrollbar remaining expanded.  Could you double check that you had that setting on while running the app and if so provide a link to an project I can build that reproduces the issue? Also, do you notice this happening in any other UWP apps? or is it just with this particular sample code. Thanks.
