### ISSUE TITLE
Proposal: Support for setting the cursor for a XAML UI Element

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#2734]
# Proposal: Support for declaring the cursor for a XAML UI Element
## Summary
In WPF, you can easily change the cursor of an element. However, in WinUI you have to subscribe to the OnPointerEntered and OnPointerExited events and change the shown cursor accordingly using WinRT APIs in a UWP CoreWindow or Win32 APIs in a Desktop HWND or use the XAML extensions from Windows Community Toolkit. WinUI should offer a built-in way to change the cursor. 

## Rationale

Many developers who are familiar with WPF expect a straightforward way to change the cursor of any element. Although devs can use Windows Community Toolkit, I believe that WinUI should offer it built-in. This will also allow C++ devs to change the cursor within XAML markup. It will also be better if we could define custom cursor in XAML without code-behind (Refer [this link](https://docs.microsoft.com/en-us/archive/blogs/devfish/customcursors-in-windows-8-csharp-metro-applications)).

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to set the mouse cursor for a UI Element using XAML markup | Must |
| This proposal will allow developers to set the mouse cursor for a UI Element from code-behind without pointer events  | Must |
| This proposal will allow developers to define and use custom cursors in markup without code-behind | Could |

## Important Notes
UIElement should have a Cursor property of CoreCursor. It should also work with WinUI Desktop Apps.

**Comment by Felix-Dev** [comment]
This should be integrated into proposal https://github.com/microsoft/microsoft-ui-xaml/issues/506 which mentions in point 4) the addition of a Cursor API.

**Comment by ranjeshj** [comment]
Lets track it through #506. @Jaiganeshkumaran  please feel free to add information to that proposal if needed. Thanks!
