### ISSUE TITLE
RichEditBox TextCommandBarFlyout UI glitches

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#2735]
**Describe the bug**
I am trying to migrate my custom `RichEditBox.ContextFlyout` to a `TextCommandBarFlyout`, mostly to get advantage of proofing menu, but I'm encountering a lot of problems in doing so.
I don't want to have primary commands for text formatting, so I disabled key accelerators for them using `DisabledFormattingAccelerators`.
Now the problem is that `CommandBar` primary part isn't visible, but it's still in the visual tree, and it is hit test visible. This causes the whole flyout to appear shifted up/down by the bar height.
Also, position is shifted horizontally, by flyout width/2 (That's it, it doesn't appear corner aligned with the mouse pointer, but center aligned).

I also found one more bug, this time when primary commands are available:
![giphy](https://media.giphy.com/media/h2HIXvBLC0C7MilMBf/giphy.gif)

Last one is: having a secondary command with a `Flyout` assigned, the flyout often closes by itself when moving the pointer from the `CommandBar` to it.

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.2]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@FrayxRulez It sounds like you have 3 issues
1) You set DisabledFormattingAccelerators and expected the formatting commands in the primary bar (Bold, Underline, etc) to go away and they did not.
2) After setting DisabledFormattingAccelerators you are seeing a gap between the two components of the flyout.
3) Nesting a flyout within your command bar makes for a bad experience because the flyouts are easily dismissed. 

Can you confrim this description?
Would it be possible to provide a repro app?

**Comment by FrayxRulez** [comment]
@StephenLPeters in the first case, CommandBar primary bar isn't visible, but it's there. I can see a invisible occluded rectangle, and I cant click on that area of the screen (I can't dismiss the flyout by clicking there). I actually noticed this as the flyout did appear shifted, and when I tried to capture a screenshot the snipping tool recognized the non-clickable rectangle as a window.
Other two are correct, sorry for the confusion :)

I will try to provide you a repro app ASAP!

**Comment by Poopooracoocoo** [comment]
this shouldn't be closed, should it?

**Comment by StephenLPeters** [comment]
@FrayxRulez did you ever get that repro app?  @Poopooracoocoo we have a bot which closes issues with NeedsAuthorFeedback tag on them after a few weeks automatically because we assume that the issue has been resolved if they never report back. Is this turning out to be an issue for you as well?

**Comment by FrayxRulez** [comment]
I moved away from TextCommandBarFlyout and I forgot about the repro. I'm sorry, I will try to get something today.

**Comment by ranjeshj** [comment]
Is this fixed as part of this PR ?
https://github.com/microsoft/microsoft-ui-xaml/pull/3594

**Comment by chingucoding** [comment]
I don't think it would be fixed by #3594 though that's hard to tell without a repro.

**Comment by Poopooracoocoo** [comment]
uh should this be closed????

**Comment by ranjeshj** [comment]
Please reopen once there is a repro or more details.
