### ISSUE TITLE
Question: The Default Size of Window is too large and I don't know how to modify that

### ISSUE THREAD

**Issue by PanJunzhong** [microsoft/microsoft-ui-xaml#2739]
In the Win32 (C#)

The app starts with a large window even there is only a single button in the default template
I tried  the GetForCurrentView method in ApplicationView class and methods, it didn't work.
And the Width and Height Attributes of <Window> at Xaml or in the Window class originally availble for WPF are not
available now.
I wonder how to set the default size of the window and resize the window

![image](https://user-images.githubusercontent.com/18226542/85451590-a4240000-b5cc-11ea-8515-3afc122bde5e.png)

**Comment by StephenLPeters** [comment]
@marb2000 In WinUI Desktop we have Application Window right? Is this a feature request for that?

**Comment by PanJunzhong** [comment]
> @marb2000 In WinUI Desktop we have Application Window right? Is this a feature request for that?

Maybe it is, But I am asking for a solution ,the size is very large when there are only few components in the window. I wonder if there any solution to make the initial window size smaller just like the uwp window ? the current width of win32 window is  twice as the uwp one. Or is that a common case? if yes, I think this issue could be moved or closed.

**Comment by marb2000** [comment]
@PanJunzhong, I believe that the WinUI 3 should have a set of APIs that allows you to do this easily. These set of APIs are in our radar, but I'm not sure when we will be able to add them.

Meamwhile, you can use Win32 APIs, for example:

1. Use the PInvoke.User32 NuGet package 
2. After activation the Window, you can call the MoveWindow method:

```cs
protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
{
            DispatcherQueueSyncContext.SetForCurrentThread();
            base.OnLaunched(args);

            m_window = new MainWindow();
            WindowWrapper windowWrapper = WindowWrapper.FromAbi(m_window.ThisPtr);
            m_windowHandle = windowWrapper.WindowHandle;
            m_window.Title = "Folder Inspector (.NET Desktop WinUI 3)";
            m_window.Activate();
            PInvoke.User32.MoveWindow(m_windowHandle, 0, 0, 1080, 920, true);
            
}

```

**Comment by PanJunzhong** [comment]
> @PanJunzhong, I believe that the WinUI 3 should have a set of APIs that allows you to do this easily. These set of APIs are in our radar, but I'm not sure when we will be able to add them.
> 
> Meamwhile, you can use Win32 APIs, for example:
> 
> 1. Use the PInvoke.User32 NuGet package
> 2. After activation the Window, you can call the MoveWindow method:
> 
> ```cs
> protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
> {
>             DispatcherQueueSyncContext.SetForCurrentThread();
>             base.OnLaunched(args);
> 
>             m_window = new MainWindow();
>             WindowWrapper windowWrapper = WindowWrapper.FromAbi(m_window.ThisPtr);
>             m_windowHandle = windowWrapper.WindowHandle;
>             m_window.Title = "Folder Inspector (.NET Desktop WinUI 3)";
>             m_window.Activate();
>             PInvoke.User32.MoveWindow(m_windowHandle, 0, 0, 1080, 920, true);
>             
> }
> ```

thank you.
