### ISSUE TITLE
NavigationView: hamburger button sometimes overlaps header in Minimal mode

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#274]
**Describe the bug**
If the back button is disabled and the minimum VisualState for the width is active, the reactivating of the back button leads to the wrong VisualState. So the header is faded over.

**Steps to reproduce the bug**
1. disable the NavigationView back button
2. Change the width of the app, so that the 'Minimal' VisualState is active
3. active the back button again
4. => wrong style view

**Expected behavior**
In this case, the VisualState should be 'MinimalWithBackButton' and not 'Minimal'.

**Version Info**

NuGet package version: 2.1.190131001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   | Yes   |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by myokeeh** [comment]
![image](https://user-images.githubusercontent.com/3663297/56946274-7a616d00-6ade-11e9-8a8b-9b9214ec4df9.png)

Same issue.

**Comment by jevansaks** [comment]
@myokeeh what version of the nuget package are you using?

**Comment by jp-weber** [comment]
@myokeeh since version 2.1.x it works for me like it should. If it was just the wrong version for you, i'd close the ticket.

**Comment by myokeeh** [comment]
@jevansaks 2.1.190405004.2.

Steps to reproduce:

1. Run app.
2. Resize app window width to smallest possible.
3. Close app.
4. Run app.

Result: NavigationView Header text overlaps with hamburger button.

Resizing app window width wider and back fixes the issue.

**Comment by jp-weber** [comment]
@myokeeh
Can you upload a sample project with the problem? I cannot reproduce this issue.

**Comment by myokeeh** [comment]
[DELETE1.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3136820/DELETE1.zip)

Attached is created using Windows Template Studio (MVVM Light) with the following changes.

App.xaml.cs:
```
protected override async void OnLaunched(LaunchActivatedEventArgs args)
        {
            if (!args.PrelaunchActivated)
            {
                await ActivationService.ActivateAsync(args);
            }
            //simulate app start up and other setup, navigate to main page.
            await Task.Delay(10000);
            ViewModelLocator.Current.NavigationService.Navigate(typeof(MainViewModel).FullName);
        }
```

DefaultLaunchActivationHandler.cs:
```
protected override async Task HandleInternalAsync(LaunchActivatedEventArgs args)
        {
            // When the navigation stack isn't restored, navigate to the first page and configure
            // the new page by passing required information in the navigation parameter
            //NavigationService.Navigate(_navElement, args.Arguments);

            await Task.CompletedTask;
        }
```

![image](https://user-images.githubusercontent.com/3663297/57058048-4747e680-6c62-11e9-9690-7b9b40c42d02.png)

**Comment by jp-weber** [comment]
@jevansaks , @myokeeh 
I can confirm that the bug is still there. But at my app I use no custom control inside the header and I have not this bug.

Visible is the bug for example also with the newest update for the XAML Controls Gallery app:
![grafik](https://user-images.githubusercontent.com/10946850/57573680-bc1ddc00-742b-11e9-8827-88b923da40de.png)

**Comment by jevansaks** [comment]
Thanks for the ping @jp-weber. @ojhad submitted another fix for this but there hasn't been a nuget update with the fix yet.

**Comment by myokeeh** [comment]
Woohoo, a fix. https://github.com/microsoft/microsoft-ui-xaml/pull/652

**Comment by jevansaks** [comment]
Oh yay @myokeeh thanks for pointing out this should be closed!
