### ISSUE TITLE
ProgressRing: Narrator issue when ring is not visible (IsActive set to false)

### ISSUE THREAD

**Issue by MarissaMatt** [microsoft/microsoft-ui-xaml#2741]
**Describe the bug**

Narrator announces "0% ProgressRing" when opacity is set to 0. 

**Expected behavior**

When the ProgressRing has IsActive set to false, opacity should be set to 0 and the visibility should be collapsed so narrator will not announce the ProgressRing. 

**Version Info**

This issue was found in WinUI 2.4. 

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
This sounds like it is by design. If the app sets opacity to 0, then it will not show but it is still in the tree and visible to accessibility tools. If you want to remove it from the tree, you should set Visibility=Collapsed.

**Comment by ranjeshj** [comment]
This is an issue in the control code. The control sets opacity when IsActive is toggled which is causing the issue. It should be using Visibility.

**Comment by chingucoding** [comment]
@karenbtlai Are you looking into this issue or can I work on this? 😃

**Comment by karenbtlai** [comment]
@chingucoding go for it! thanks in advance.
