### ISSUE TITLE
WinUI for Desktop

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2746]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1088991/winui-for-desktop.html)._

---
[regression] [worked-in:16.7.0 Preview 2]
Using Visual Studio 2019 16.7.0 Preview 2
using Windows 10 pro 2004 19041.329

I did try to convert UWP app's to WinUI UwP this work for app not using MapControl or WebView2
I did try the same for WINUI for Desktop

When i create an app WinUI for Desktop nothing change and compile is ok.
But then by run it crash (error as Attachment)

I mean the app should open the MainWindow and showing the button isn'i it ?

What is wrong ?

---
#### Visual Studio Feedback System on 6/24/2020, 02:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ranjeshj** [comment]
I don't see any attachments. Can you please provide more details or provide a repro app. This issue is not actionable without more information.

**Comment by Fernand-Delavy** [comment]
![Error](https://user-images.githubusercontent.com/43344217/85833693-6e307880-b792-11ea-9c8c-f8465ffac758.jpg)
The error is attached.
Thanks

**Comment by ranjeshj** [comment]
Looks like a dup of this issue 
https://github.com/microsoft/microsoft-ui-xaml/issues/2679
