### ISSUE TITLE
visual studio 2017 missing xaml menubar for uwp

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2749]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1086118/visual-studio-2017-missing-xaml-menubar-for-uwp.html)._

---
visual studio is missing xaml menubar and maybe more

---
#### Visual Studio Feedback System on 6/21/2020, 11:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ranjeshj** [comment]
Can you ensure that you have the Microsoft.UI.Xaml nuget package is added to your project ? You can find more details in the link.
https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started
