### ISSUE TITLE
Overriding AppBarThemeMinHeight doesn't cause AppBarButton to fill available height.

### ISSUE THREAD

**Issue by dPJinjo** [microsoft/microsoft-ui-xaml#275]
**Describe the bug**
AppBarButton (and other such controls) need to have their "ContentRoot" Grid's first RowDefinition be "1*" (default value) instead of "Auto". Also, "TextLabel" needs to set VerticalAlignment="Center". This is so that app developers can increase the height by overriding AppBarThemeMinHeight and have the icon and right-aligned TextLabel center vertically rather than being stuck on the top of the button visual.

Example fix to first RowDefinition:
```
                        <Grid x:Name="ContentRoot" MinHeight="{ThemeResource AppBarThemeMinHeight}">

                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition Width="Auto" />
                            </Grid.ColumnDefinitions>

                            <Grid.RowDefinitions>
                                <RowDefinition />
                                <RowDefinition Height="Auto" />
                            </Grid.RowDefinitions>
```

**Steps to reproduce the bug**
`<CommandBar DefaultLabelPosition="Right" ><CommandBar.Resources><x:Double x:Key="AppBarThemeCompactHeight">48</x:Double></CommandBarResources><AppBarButton Icon="Delete" Label="Delete"/></CommandBar>`

Observe icon, label, and border are top aligned in the upper 40px of the button.

**Expected behavior**
Icon and Label should be vertically centered instead of top aligned. Border should be edge aligned with the button.

**Screenshots**
![image](https://user-images.githubusercontent.com/16249087/52380184-ac07f200-2a21-11e9-9f83-c10da8098296.png)

left button has local fix, right button and separator do not.

**Version Info**
all

NuGet package version: 
all

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)   | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |

**Comment by jevansaks** [comment]
@licanhua we've wrestled with the layout of this control a bunch, especially with density and text scaling. Can you take a look at this?

@dPJinjo the title of the bug proposes a fix but I am not totally clear on the problem. Could you fix the title and make the problem a bit more clear? I think it's that if you change the height of the AppBarButton that the reveal border doesn't take the full height of the control?

**Comment by licanhua** [comment]
It's worth to dig into it and support the auto scaling. We have debate about this before, and finally we decided that we hard-coded a lot of parameters.

When you make change to AppBarThemeCompactHeight, I expect you will tune the following parameters too. And that's what we did to support density

```
<Thickness x:Key="AppBarButtonContentViewboxMargin">12,14,0,14</Thickness> 
<Thickness x:Key="AppBarButtonContentViewboxCompactMargin">0,14,0,14</Thickness> 
<Thickness x:Key="AppBarButtonContentViewboxCollapsedMargin">0,14,0,4</Thickness> 
<Thickness x:Key="AppBarButtonOverflowTextTouchMargin">0,11,0,13</Thickness> 
<Thickness x:Key="AppBarButtonOverflowTextLabelPadding">0,5,0,7</Thickness> 
<Thickness x:Key="AppBarButtonTextLabelMargin">2,0,2,8</Thickness> 
<Thickness x:Key="AppBarButtonTextLabelOnRightMargin">8,15,12,17</Thickness> 
<Thickness x:Key="AppBarToggleButtonOverflowTextTouchMargin">0,11,0,13</Thickness> 
<Thickness x:Key="AppBarToggleButtonOverflowCheckTouchMargin">12,12,12,12</Thickness> 
<Thickness x:Key="AppBarToggleButtonOverflowCheckMargin">12,6,12,6</Thickness> 
<Thickness x:Key="AppBarToggleButtonTextLabelMargin">2,0,2,8</Thickness> 
<Thickness x:Key="AppBarToggleButtonTextLabelOnRightMargin">8,15,12,17</Thickness> 
<Thickness x:Key="AppBarToggleButtonOverflowTextLabelPadding">0,5,0,7</Thickness>
<x:Double x:Key="AppBarButtonContentHeight">20</x:Double> 
<x:Double x:Key="AppBarThemeMinHeight">60</x:Double> 
<x:Double x:Key="AppBarThemeCompactHeight">48</x:Double>

```

**Comment by jevansaks** [comment]
Making this knob work correctly will require a bit of extra thought and it doesn't seem worth the effort at this time. If you disagree, let us know what the scenario is and we'll try to solve it more holistically.
