### ISSUE TITLE
RadioButtons, CheckBoxes and ToggleSwitch don't look very good on screens with 100% scaling

### ISSUE THREAD

**Issue by massijay** [microsoft/microsoft-ui-xaml#2751]
Some controls like RadioButtons, CheckBoxes and ToggleSwitch have the stroke that is too thin and don't look very good when the scaling (from Windows display setting) is set to 100%. In my opinion the stroke should be a little bit thicker.
Here is a comparison of the controls with and without WinUI:

With WinUI | Without WinUI
------------ | -------------
![winui](https://user-images.githubusercontent.com/16278647/85698631-21d63180-b6db-11ea-9574-4ca5949414b3.png) | ![no winui](https://user-images.githubusercontent.com/16278647/85698502-04a16300-b6db-11ea-9fb7-1247486e0e67.png)

**Comment by Felix-Dev** [comment]
This is a general problem with the current rendering used for the 1px border with corner radius > 0. See for example the Text controlusing the default WinUI 2.2+ style and observe the visible "gaps" in the cornern (1920x1080 100% DPI scaling):
![image](https://user-images.githubusercontent.com/1398851/85702099-5ac3d580-b6de-11ea-86fa-849cd7f52377.png)

This is the reason why I immediately set the border thickness to 2px again in all my new WinUI apps.

**Comment by massijay** [comment]
> This is the reason why I immediately set the border thickness to 2px again in all my new WinUI apps.
There is a way to set border tickness all at once? Can you explain how do you do that?

**Comment by Felix-Dev** [comment]
You can use the [Fluent XAML Theme editor](https://github.com/Microsoft/fluent-xaml-theme-editor) to manually generate XAML code which will set the border thickness of most controls (depending on the editor version used some reently added control border thickness theme resources might be missing). Example output generated by it below:
```
<Thickness x:Key="MenuBarItemBorderThickness">2,2,2,2</Thickness>
<Thickness x:Key="GridViewItemMultiselectBorderThickness">2,2,2,2</Thickness>
<Thickness x:Key="CheckBoxBorderThemeThickness">2</Thickness>
<x:Double x:Key="GridViewItemSelectedBorderThemeThickness">2</x:Double>
<x:Double x:Key="RadioButtonBorderThemeThickness">2</x:Double>
<Thickness x:Key="ButtonBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="CalendarDatePickerBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="TimePickerBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="DatePickerBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="ToggleSwitchOuterBorderStrokeThickness">2,2,2,2</Thickness>
<Thickness x:Key="RepeatButtonBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="SearchBoxBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="ToggleButtonBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="TextControlBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="ButtonRevealBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="RepeatButtonRevealBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="ToggleButtonRevealBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="AppBarEllipsisButtonRevealBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="AppBarButtonRevealBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="AppBarToggleButtonRevealBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="ListViewItemRevealBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="GridViewItemRevealBorderThemeThickness">2,2,2,2</Thickness>
<Thickness x:Key="ComboBoxItemRevealBorderThemeThickness">2,2,2,2</Thickness>
<x:Double x:Key="PersonPictureEllipseBadgeStrokeThickness">2</x:Double>
```

You can just post this code into your `Application.Resources` and then have these controls above use a 2px border thickness across the app.

**Comment by massijay** [comment]
Thank you! (It also looks good with thickness set to 1.5).
This should be changed by default for consistency across all WinUI apps

**Comment by StephenLPeters** [comment]
@chigy FYI

**Comment by jp-weber** [comment]
Any update on this? I find many apps that use WinUI with these changes have a worse visibility in the controls than before. This should be changed.
