### ISSUE TITLE
Question: Where is SystemControlBackgroundBaseLowBrush defined?

### ISSUE THREAD

**Issue by JVimes** [microsoft/microsoft-ui-xaml#2758]
Where is `SystemControlBackgroundBaseLowBrush` defined? I see it used [here](https://github.com/microsoft/microsoft-ui-xaml/blob/865e4fcc00e8649baeaec1ba7daeca398671aa72/dev/CommonStyles/Button_themeresources.xaml#L22) but can't find where its value is defined.

**Comment by Felix-Dev** [comment]
You can find it in the `generic.xaml` file of the Windows SDK, typically located at `[your specified root path to the Windows SDKs]\WindowKits\10\DesignTime\CommonConfiguration\Neutral\UAP\[SDK version]\Generic\`. [SDK version] for example is `10.0.18362.0` for the 1903 SDK.

```xml
<Color x:Key="SystemBaseLowColor">#33000000</Color>
<SolidColorBrush x:Key="SystemControlBackgroundBaseLowBrush" Color="{StaticResource SystemBaseLowColor}" />
```

**Comment by JVimes** [comment]
Thanks, @Felix-Dev!

For readers wondering why themeresources.xaml is also there with some of the same content as generic.xaml, [looks like](https://github.com/microsoft/microsoft-ui-xaml/issues/1040#issuecomment-512941281) it's either SDK cruft or is used by the designer, and can be ignored.
