### ISSUE TITLE
Composition layer does not correctly respond to changes in the pixel format of a swap chain

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#2761]
I've been experimenting with HDR support in my app. I've got a monitor which supports HDR and HDR can be turned on in windows display settings. I have a SwapChainPanel in my app to render the HDR content. There are various options in my app to set the output to HDR/SDR which changes the swap chain pixel format from 8-bit uint to 16-bit float. I'm using the Resize method provided by Win2D to change the pixel format. However, the composition layer doesn't seem to notice the change. What I mean is, when Windows HDR mode is on, the white level scaling and color management behaviour, some of which is described [here](https://docs.microsoft.com/en-us/windows/win32/direct2d/white-level-adjustment-effect), is not updated when the pixel format changes. I have to create a new swap chain instead.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)       |    Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@jeffstall and @codendone Same here, not sure which team to put this on.

**Comment by peter-bertok** [comment]
Win UI up to and including v3 seem to have all color-management, wide-color, HDR, etc... features broken completely. Only sRGB SDR works.

For example, DisplayInformation is completely unavailable: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api?tabs=csharp#classes-with-an-xxxforcurrentview-method

**Comment by imbushuo** [comment]
@peter-bertok It's a side effect of the windowing architecture change, so use classic Win32 `DisplayConfigGetDeviceInfo` and friends as a replacement: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-displayconfiggetdeviceinfo. 

I have an example here: https://github.com/imbushuo/ShareX/blob/master/ShareX.ScreenCaptureLib/AdvancedGraphics/HdrMetadataUtility.cs
