### ISSUE TITLE
NavigationView: Selection indicator erroneously changes position when closing the pane

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2762]
**Describe the bug**
In certain cases the NavigationView selection indicator mistakenly changes position even though the selection does not change.

**Steps to reproduce the bug**
1. Open the XAML Controls Gallery (a version with a hierarchical navview sample)
1. Go to the hierarchical NavView sample on the NavigationView page
2. Ensure the NavView pane is open and select a NavViewItem child item (like Document options -> Create new)
3. Now select the Settings item in the NavView
4. CLose the NavView pane (for example by clicking the pane toggle button)

Observe that while selection remains unchanged the selection indicator moves back from the Settings item to the Document options item.

**Expected behavior**
The selection indicator should stay at the Settings item.

**Gif**
![navview-selectionindicator-issue](https://user-images.githubusercontent.com/1398851/85882580-ccd01380-b7df-11ea-8d63-07fd74e2ee28.gif)

**Version Info**

NuGet package version: 
2.5.0-prerelease.200609001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This bug is currently fixed in PR https://github.com/microsoft/microsoft-ui-xaml/pull/1997. How are the plans for that PR? Should we still provide a specific fix for this bug (perhaps to be deployed in a future WinUI 2.4.x version) or wait until the PR above will be merged (seems like work on it is almost done)?

**Comment by StephenLPeters** [comment]
@ojhad FYI. I'm Optimistic that #1997 is nearly done, so I think we can just resolve this when that is checked in.

**Comment by chingucoding** [comment]
Given that #1997 was closed, and I can't seem to repro this with the hierarchical databinding test page, I think we can close this issue.

**Comment by StephenLPeters** [comment]
Thanks!
