### ISSUE TITLE
navigationviewitem bitmap icon  ignores foreground 

### ISSUE THREAD

**Issue by tharun916** [microsoft/microsoft-ui-xaml#2763]
<muxc:NavigationView.Resources>

                <SolidColorBrush x:Key="NavigationViewItemForeground" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundPointerOver" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundPressed" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundDisabled" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundChecked" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundCheckedPointerOver" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundCheckedPressed" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundCheckedDisabled" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundSelected" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedPointerOver" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedPressed" Color="White" />
                <SolidColorBrush x:Key="NavigationViewItemForegroundSelectedDisabled" Color="White" />
            </muxc:NavigationView.Resources>

these are not working for bitmap icons in the navigationviewitem

**Comment by StephenLPeters** [comment]
@ojhad
