### ISSUE TITLE
Proposal: support design time xaml properties similar to xamarin forms do

### ISSUE THREAD

**Issue by JanabiSoft** [microsoft/microsoft-ui-xaml#2769]
# Proposal: support design time xaml properties similar to xamarin forms do

## Summary
in xamarin forms we can do this:
<Button Text="{Binding.....}" d:Text="Click me"/>
the designer will show Click me in previewer instead of empty button.
in UWP it is more complicated so please make it as easy as that

**Comment by MartinZikmund** [comment]
Have you tried the new Visual Studio 2019 16.7 Preview 3? It contains design-time data support for WPF and UWP using the `d:` prefixed attributes (see [here in release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#--visual-studio-2019-version-167-preview-3))

**Comment by JanabiSoft** [comment]
@MartinZikmund thanks for letting me know, that's good news, will wait for 16.7 release.
