### ISSUE TITLE
AnimatedVisualPlayer ignores AutoPlay property when set by style

### ISSUE THREAD

**Issue by simeoncran** [microsoft/microsoft-ui-xaml#2779]
**Describe the bug**
The AnimatedVisualPlayer ignores AutoPlay property when set by style. The AutoPlay property defaults to true. If I try to make all my AnimatedVisualPlayers default to false using a <Setter Property="AutoPlay" Value="False"/> it doesn't do anything.

**Steps to reproduce the bug**
1. Add an AnimatedVisualPlayer to a page with a codegen'd Lottie as it's child.
2. Add a style to control the AnimatedVisualPlayer with a <Setter Property="AutoPlay" Value="False"/> element.

**Expected behavior**
The Lottie will not play when the page is loaded.

**Screenshots**

**Version Info**
All.

NuGet package version: 
All.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I believe this behavior is caused by the order in which properties are evaluated. If the Source property (that refers to the Lottie to play) is set before the AutoPlay property is set, the animation will auto play despite what AutoPlay is later set to. I think the only way around this is to defer the auto-playing of the animation until after all properties are set.

**Comment by Felix-Dev** [comment]
I would like to take a look at this.
