### ISSUE TITLE
XAML Controls Gallery : Whole main landmark is overlapped by left empty navigation pane

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#2781]
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/27033778?src=WorkItemMention&src-action=artifact_link)

Repro steps :
Launch XAML Control Gallery app .
Navigate to Settings and activate it.
Now navigate to "Navigation control location" toggle button and activate it.
Now close XAML Control Gallery and re-launch it. Now observe for Navigation pane.
Expected result : As we changed the navigation control location, it should be on top, but the area of the left navigation pane should be occupied by the reset of the main UI.

Actual result : The Navigation control location is shifted to top but the default navigation control location in the left is still appearing over the occupied UI.
![NavigationPane](https://user-images.githubusercontent.com/7758786/86041839-23fe0000-b9fb-11ea-9d93-c04f036f2130.PNG)

**Comment by StephenLPeters** [comment]
@ojhad FYI

**Comment by StephenLPeters** [comment]
possible dupe of #2635

**Comment by chingucoding** [comment]
I can't seem to repro this with the latest commit on the Xaml Control Gallery repo. Could it be that it was fixed alongside #2635 ?

**Comment by ranjeshj** [comment]
I cannot repro it either with latest version of XamlControlsGallery. Closing this issue. Thanks @chingucoding
