### ISSUE TITLE
Unable to move item (drag and drop) inside TreeView in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#2783]
**Describe the bug**

We are able to move items around (drag and drop) inside a TreeView in our UWP application. 

However, once we switched over to WinUI3 Desktop, we are no longer able to move items around (drag and drop) inside the TreeView.

**Steps to reproduce the bug**
1. Clone the [WinUI3 Problems DragDropTreeView repository](https://github.com/eleanorleffler/WinUI3_Problems_DragDropTreeView).
2. Go to the DragDropTreeViewWinUI folder.
3. Open the DragDropTreeViewWinUI solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Attempt to drag an item (not the root node) in the TreeView onto another location in the TreeView.
6. You should see the "not permitted" symbol (circle with slash) as you are dragging over. See Screenshot#1 and Screenshot#2.

**Expected behavior**

We expect to see the drag indicator change to "Move" and be able to drop items back onto the TreeView. 

On the right side of the application, there is the TreeView Actions Log that tracks the drag and drop events to verify what is happening.

We expect to see the same behavior we saw in UWP. See Screenshot#3 and Screenshot#4

Build and run the DragDropTreeViewUWP solution inside the DragDropTreeViewUWP folder to see expected behavior.

**Screenshots**

![DragDropTreeViewCurrentBehavior](https://user-images.githubusercontent.com/9272634/86047236-37699500-ba14-11ea-9268-39785f529dbc.PNG)

Screenshot#1 - Current Behavior

![DragDropTreeViewCurrentBehaviorEndResult](https://user-images.githubusercontent.com/9272634/86047252-3d5f7600-ba14-11ea-91ee-ff2317e3da92.PNG)

Screenshot#2 - Current Behavior End Result

![DragDropTreeViewExpectedBehavior](https://user-images.githubusercontent.com/9272634/86047264-44868400-ba14-11ea-89ed-58a7ba8176cb.PNG)

Screenshot#3 - Expected Behavior

![DragDropTreeViewExpectedBehaviorEndResult](https://user-images.githubusercontent.com/9272634/86047282-4a7c6500-ba14-11ea-8a55-58627a75b533.PNG)

Screenshot#4 - Expected Behavior End Result

NuGet package version:

[Microsoft.VCRTForwarders.140 1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

Targeting:

Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1809 (10.0; Build 17763)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |                       |
| November 2019 Update (18363)  	 |                       |
| May 2019 Update (18362)            |                       |
| October 2018 Update (17763)        | Yes                   |
| April 2018 Update (17134)          |                       |
| Fall Creators Update (16299)       |                       |
| Creators Update (15063)            |                       |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop               | Yes                  |
| Mobile                |                      |
| Xbox                  |                      |
| Surface Hub           |                      |
| IoT                   |                      |

**Additional context**

When we debugged the solution, we noticed that the treeView1_DragItemsCompleted (MainPage.xaml.cs Line 72) does get called.

However, the drop was not allowed so the dropped node is the same as the dragged node.

**Comment by jevansaks** [comment]
I've checked in fixes for a few different drag&drop issues in WinUI3, and they'll be in the next preview.
