### ISSUE TITLE
scrollview does not change it’s contentheight correctly on narrow screens resulting in users not being able to scroll down.

### ISSUE THREAD

**Issue by sjorsmiltenburg** [microsoft/microsoft-ui-xaml#2791]
**Describe the bug**

I was redirected here with my bugreport from:
https://developercommunity.visualstudio.com/content/problem/1095262/scrollview-does-not-take-into-account-resize-due-t.html

problem:
In xamarin forms project, scrollview does not change it’s contentheight correctly on narrow screens /window sizes resulting in users not being able to scroll down.

**Steps to reproduce the bug**
take a view with content inside a scrollview.
reduce the window width (UWP) so the content get’s re-arranged to take up more y space
try and scroll to the bottom, it will snap back up and you won't be able to 'stay' at the bottom fo the view.

**Expected behavior**
scrollview detects the increased y dimension of the view and adjusts its contentview accordingly so a user can scroll down

**Screenshots**
a recording of the problem on UWP and on a Iphone SE can be seen here: https://youtu.be/1LOdM8hI51s 

**Version Info**
VisualStudio 16.6.2
Xamarin.Forms v4.7.0.968

NuGet package version: 
Microsoft.Ui.xaml v 10.0.0.0

Windows v 1909 (os build 18363.900)

**Additional context**
my screen for reference:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage  xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:viewModels="clr-namespace:BB.App.ViewModels;assembly=BB.App"
             xmlns:pancakeView="clr-namespace:Xamarin.Forms.PancakeView;assembly=Xamarin.Forms.PancakeView"
             x:Class="BB.App.ViewModels.StoreView"
             NavigationPage.HasNavigationBar="False">
    <ScrollView HorizontalScrollBarVisibility="Never">
        <Grid >
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"></RowDefinition>
                    <RowDefinition Height="*"></RowDefinition>
                </Grid.RowDefinitions>

                <viewModels:BBHeaderView BindingContext="{Binding BBHeaderViewModel}"  Grid.Row="0" ></viewModels:BBHeaderView>

                <StackLayout Grid.Row="1" VerticalOptions="Start" HorizontalOptions="Center" WidthRequest="600" Margin="20" >
                    <pancakeView:PancakeView BackgroundColor="#3bb273" Padding="40,20,40,20" CornerRadius="30"  HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" IsVisible="{Binding UserHasSubscription}">
                        <Label TextColor="Black" Text="Er is een abonnement actief." FontAttributes="Bold" FontSize="Medium"></Label>
                    </pancakeView:PancakeView>

                    <pancakeView:PancakeView BackgroundColor="#44bfde" Padding="10" CornerRadius="15"  HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
                        <StackLayout>
                            <Label Text="Abonneer je op BookaBooka!" FontAttributes="Bold" FontSize="Large" HorizontalTextAlignment="Center" TextColor="White"/>
                            <pancakeView:PancakeView BackgroundColor="White" Padding="10" CornerRadius="15"  HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
                                <StackLayout>
                                    <Label Padding="20,0,20,0" Text="De eerste 7 dagen gratis, daarna slechts € 4,99 per maand."  TextColor="#0c2442" FontAttributes="Bold" HorizontalTextAlignment="Center"/>
                                    <Label Padding="20,0,20,0" Text="Je zit nergens aan vast, het abonnement is op elk moment opzegbaar." TextColor="Gray" HorizontalTextAlignment="Center"  />
                                    <pancakeView:PancakeView BackgroundColor="Green" Padding="10" Margin="10" HeightRequest="60" CornerRadius="30"  HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" WidthRequest="550">
                                        <pancakeView:PancakeView.GestureRecognizers>
                                            <TapGestureRecognizer Command="{Binding PurchaseCommand}"></TapGestureRecognizer>
                                        </pancakeView:PancakeView.GestureRecognizers>
                                        <Label FontSize="Large" TextColor="White" FontAttributes="Bold" HorizontalTextAlignment="Center" Text="Start nu je gratis week." VerticalTextAlignment="Center" VerticalOptions="Center"></Label>
                                    </pancakeView:PancakeView>
                                    <StackLayout Padding="20,0,20,10">
                                        <Label Text="• Ongelimiteerde toegang tot alle prentenboeken" TextColor="#0c2442" FontSize="Medium"/>
                                        <BoxView HeightRequest="2" Color="LightGray" WidthRequest="550" HorizontalOptions="Center"></BoxView>
                                        <Label Text="• Offline toegang, handig voor op vakantie of onderweg" TextColor="#0c2442" FontSize="Medium"/>
                                        <BoxView HeightRequest="2" Color="LightGray" WidthRequest="550" HorizontalOptions="Center"></BoxView>
                                        <Label Text="• Meerdere te kiezen voorleesstemmen" TextColor="#0c2442" FontSize="Medium"/>
                                        
                                    </StackLayout>

                                    <Label Padding="20,0,20,0" Text="De kosten van het abonnement worden maandelijks in rekening gebracht op je account. Betalingen lopen door totdat je het abonnement opzegt, ten minste 24 uur voordat een volgende periode start. Je krijgt een email met een bestelbevestiging en de link naar de Account Settings pagina waar je het abonnement kunt opzeggen." TextColor="Gray"/>
                                </StackLayout>
                            </pancakeView:PancakeView>

                            
                            <Label  TextColor="White" HorizontalTextAlignment="Center" FontSize="Medium">
                                <Label.FormattedText>
                                    <FormattedString>
                                        <Span  Text="Heb je al een abonnement? Herstel "/>
                                        <Span Text="hier"  TextDecorations="Underline">
                                            <Span.GestureRecognizers>
                                                <TapGestureRecognizer Command="{Binding RefreshStatusCommand}" />
                                            </Span.GestureRecognizers>
                                        </Span>
                                        <Span Text=" een eerdere aankoop."></Span>
                                    </FormattedString>
                                </Label.FormattedText>
                            </Label>
                        </StackLayout>

                    </pancakeView:PancakeView>

                </StackLayout>
            </Grid>
            <Grid WidthRequest="600" IsVisible="{Binding IsBusy}">
                <Grid BackgroundColor="Black" Opacity="0.6" ></Grid>
                <StackLayout VerticalOptions="Center" HorizontalOptions="Center">
                    <pancakeView:PancakeView Grid.Row="1" BackgroundColor="#44bfde" Padding="40,0,40,0" CornerRadius="30"  HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
                        <pancakeView:PancakeView.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding PurchaseCommand}"></TapGestureRecognizer>
                        </pancakeView:PancakeView.GestureRecognizers>
                        <StackLayout Orientation="Vertical" VerticalOptions="CenterAndExpand" Padding="20">
                            <Label Text="De bibliotheek wordt ververst." HorizontalOptions="CenterAndExpand" HorizontalTextAlignment="Center" FontAttributes="Bold" FontSize="Medium" TextColor="#0c2442" ></Label>
                        </StackLayout>
                    </pancakeView:PancakeView>
                    <ActivityIndicator HeightRequest="50" x:Name="ActivitySpinner" IsVisible="True" IsRunning="True" HorizontalOptions="Center" />

                </StackLayout>
            </Grid>
        </Grid>
    </ScrollView>
</ContentPage>

**Comment by ranjeshj** [comment]
@sjorsmiltenburg Xamarin Forms issues should go to https://github.com/xamarin
