### ISSUE TITLE
Flyout placement does not have any effect in SplitButton

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#2797]
**Describe the bug**
Changing the `Placement` property on a `SplitButton`'s `Flyout` does not have any effect.

**Steps to reproduce the bug**
1. Run the following code
```xaml
    <Grid Padding="40">
        <muxc:SplitButton Content="Button Action 1">
            <muxc:SplitButton.Flyout>
                <MenuFlyout Placement="BottomEdgeAlignedRight">
                    <MenuFlyoutItem Text="SubAction 1" />
                    <MenuFlyoutItem Text="SubAction2" />
                </MenuFlyout>
            </muxc:SplitButton.Flyout>
        </muxc:SplitButton>
    </Grid>
```
2. Open the spit button flyout
3. The flyout is left aligned.

**Expected behavior**
The flyout should be right aligned.

**Screenshots**

![image](https://user-images.githubusercontent.com/20152272/86150286-82130c00-bafd-11ea-9c72-af276a45cc2b.png)

**Version Info**
NuGet package version: 
[Microsoft.UI.Xaml 2.3.191129002]
[Microsoft.UI.Xaml 2.4.0-prerelease.200506001]

**Additional context**
I'm not expecting all the flyout placements to work since it would be debatable to have a *top* placement with the actual chevron design but, it would be interesting to let us choose between a bottom left and a bottom right alignment.

**Comment by mdtauk** [comment]
If you were to enable the placement to take affect, would the Chevron change to match the orientation where the flyout will appear from?

**Comment by StephenLPeters** [comment]
Not currently, it doesn't with combobox either.
