### ISSUE TITLE
Bug: [uwp] RectHelper is the opposite of helping (RPC_E_WRONG_THREAD)

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#2799]
Trust me, this is not the first title I came up with.

`RectHelper.Intersect` throws an exception: The application called an interface that was marshalled for a different thread.

![image](https://user-images.githubusercontent.com/13891601/86043465-75d17500-ba51-11ea-8f82-6a7f5a460fea.png)

My take is that this is because I'm not calling RectHelper.Intersect on the UI thread (I can't think of any other possibilities). 

**However, how can this happen, for something that should be so simple?**

It's like forcing us to use `Math.Sin` only on the UI thread. Who in their right mind would do such a thing?

Please, either fix it, or just throw away the whole `RectHelper` class.

**Comment by MikeHillberg** [comment]
Sorry you ran into this issue. I moved this to the Xaml repo because that's where this is implemented, and it's something we could address in WinUI3. Much of Xaml depends on running on the UI thread and performs runtime validation checks, but these static members shouldn't need to be restricted.

**Comment by jtorjo** [comment]
> but these static members shouldn't need to be restricted.

Thanks, agreed 100%

**Comment by Scottj1s** [comment]
@jtorjo - if it helps lessen the pain, the C#/WinRT projection support in .Net 5 actively excludes these helper types from the projection, so that developers who happen to not see the docs won't fall into that pit (even with the thread affinity fix, there's still the inefficiency of these calls).  Thanks a lot for reporting the issue.

**Comment by jtorjo** [comment]
@Scottj1s Thanks! As I said, I would never have originally used this, if Rect.Intersect would have returned a copy, instead of being in-place.
