### ISSUE TITLE
Move NavView interaction test pages into folders

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2805]
Since we split up the NavigationView interaction tests, we should also move the pages into different folders to make it easier to navigate the project. The folders for this would be chosen based on these categories:

![image](https://user-images.githubusercontent.com/16122379/86226655-4410f900-bb8c-11ea-96dc-5b765034e58c.png)

If that's a change the team would be fine with, I would happily change this.

**Comment by StephenLPeters** [comment]
@ojhad FYI, @chingucoding seems fine albeit not very exciting. If you want to do it I'd say go for it.

**Comment by chingucoding** [comment]
Cool. @ad1Dima you are adding new pages as part of your bottom menu items PR. Would you like me to wait until your PR gets merged to avoid merge conflicts?

**Comment by ad1Dima** [comment]
@chingucoding I didn't add new pages. I modified existing. Anyway there will be a lot of merges before my PR will be accepted
