### ISSUE TITLE
NavigationView: Selection indicator becomes invisible when switching PaneDisplayModes

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2813]
**Describe the bug**
When switching the PaneDisplayMode of a NavigationView, the selection indicator will become invisible (selection is kept unchanged).

**Steps to reproduce the bug**

1. Open the XAMl Controls Gallery with hierarchical NavigationView support
2. Go to the hierarchical NavigationView example on the NavigationView examples page
3. See the GIF below 

![navview-selectionindicator-invisible](https://user-images.githubusercontent.com/1398851/86417955-ef29cb80-bcce-11ea-9449-05d830d00f84.gif)

**Expected behavior**
The selection indicator will remain visible.

**Version Info**

NuGet package version: 
Every WinUI version since 2.4 release up to the current WinUI 2.5 previews (this is a regression introduced with WinUI 2.4).

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This issue will be fixed - as of now - by PR #1997.

**Comment by StephenLPeters** [comment]
@ad1Dima same here, does your PR fix this one as well?

**Comment by StephenLPeters** [comment]
@ojhad FYI, this gets fixed by Ad1Dima's change

**Comment by ad1Dima** [comment]
@StephenLPeters i guess this can be closed also

**Comment by StephenLPeters** [comment]
Fixed with #1997
