### ISSUE TITLE
NavigationView: Top-level NavigationViewItem is not shown in Top PaneDisplayMode when one of its children is selected when switching to Top mode

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2814]
**Describe the bug**
When switching from a different PaneDisplayMode to **Top** PaneDisplayMode the top-level NavigationViewItem is not explicitly shown in the pane when it has a selected child.

Ignore the missing selection indicator, this is tracked in #2813. 

**Steps to reproduce the bug**
1. Open the MUXControlsTestApp
2. Go the NavigationView tests page -> Hierarchical NavigationView Markup Test page
3. Watch the GIF below:

![navview-toppanedisplaymode-selecteditem-issue](https://user-images.githubusercontent.com/1398851/86418868-da026c00-bcd1-11ea-9726-574fd9a8c517.gif)

**Expected behavior**

Menu Item 29 should be shown in Top PaneDisplayMode as its child is selected:
![image](https://user-images.githubusercontent.com/1398851/86419023-64e36680-bcd2-11ea-8c3a-9523224f7369.png)

**Version Info**

NuGet package version: 
Newest WinUI builds directly from the master branch.

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This issue - as of now - will be fixed by PR #1997.

**Comment by StephenLPeters** [comment]
Seems like a good bug. @ad1Dima I see you mentioned this but can't find the corresponding message. Does your change fix this?

**Comment by Felix-Dev** [comment]
@StephenLPeters I ran the MUXControlsTestApp in @ad1Dima's branch and could not reproduce this error (see [Additional context] above).

**Comment by StephenLPeters** [comment]
Ah, great, sorry I missed that.

**Comment by ad1Dima** [comment]
@StephenLPeters i guess this can be closed also

**Comment by StephenLPeters** [comment]
Fixed by #1997

**Comment by Felix-Dev** [comment]
Hmm, not sure what happened here but I can still repro that on newest WinUI master builds:

![navview-toplevel-selecteditem-display-issue](https://user-images.githubusercontent.com/1398851/89953237-fa0d3f80-dc2e-11ea-928a-6acbfc6bdb27.gif)

The expected result would me that Menu Item 29 is visible and selected when switching back to top navigation after selecting its child item.

**Comment by StephenLPeters** [comment]
Dang, I'd say lets reopen the issue but looks like I never closed it.  Maybe my subconscious knew it wasn't resolved
