### ISSUE TITLE
NavigationView crashes when changing the collection bound to MenuItemsSource

### ISSUE THREAD

**Issue by MichaelRumpler** [microsoft/microsoft-ui-xaml#2818]
**Describe the bug**
I bound the NavigationView.MenuItemsSource to an array. When I replace the array, the navigation items are updated the first time. But when I do it a second time, then the app crashes.

**Steps to reproduce the bug**
1. Run the attached repro project
2. Click on one of the first 6 menu items (the last one also breaks in Windows.UI.Xaml.Controls.NavigationView, but that's a different bug)
3. The ViewModel will update the Pages property to add a new item
4. Click again on any item but the last.
5. The app crashes

**Expected behavior**
The new item will be added to the list

**Version Info**
NuGet package version: 
[Microsoft.UI.Xaml 2.4.0]
[Microsoft.UI.Xaml.2.5.0-prerelease.200609001]

Windows 10 version 2004 (19041.329)

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
The app does not crash, when I use the Windows.UI.Xaml.Controls.NavigationView instead of the WinUI control.

This problem is very similar to [#766](https://github.com/microsoft/microsoft-ui-xaml/issues/766), but @ranjeshj said I should open a new issue. That the last item does not work may be related to #2682 .

[Repro_NavigationView_AddItems.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4868993/Repro_NavigationView_AddItems.zip)

**Comment by ranjeshj** [comment]
@MichaelRumpler Thanks for filing this issue. Interesting bug. It seems to be a bug when changing the property entirely with a new object. I was able to workaround by just updating the collection instead of replacing.

```
 public class ViewModel : ViewModelBase
	{
		private ObservableCollection<Page> _pages;
		public ObservableCollection<Page> Pages
		{
			get => _pages;
			set => SetProperty(ref _pages, value);
		}

		private Page _selectedPage;
		public Page SelectedPage
		{
			get => _selectedPage;
			set => SetProperty(ref _selectedPage, value);
		}

		public ICommand ItemInvoked { get; }

		public ViewModel()
		{
			Pages = new ObservableCollection<Page>
			{
				new Page("First"),
				new Page("Second"),
				new Page("Third"),
				new Page("Fourth"),
				new Page("Fifth"),
				new Page("Sixth"),
				new Page("Seventh"),
			};

			SelectedPage = Pages[0];

			ItemInvoked = new DelegateCommand<Page>(OnItemInvoked);
		}

		private void OnItemInvoked(Page page)
		{
			System.Diagnostics.Debug.WriteLine($"ItemInvoked {page.Name}");
			Pages.Insert(0, new Page($"Clicked {page.Name}"));
			SelectedPage = Pages[0];
		}
	}
```

**Comment by MichaelRumpler** [comment]
I didn't do that because of #766

**Comment by ranjeshj** [comment]
I've closed that issue since that issue is quite stale. Thanks.

**Comment by StephenLPeters** [comment]
@ojhad FYI

**Comment by chingucoding** [comment]
The stacktrace for the crash does not contain `Microsoft.UI.Xaml.dll` at all, only WUXC dll comes up. Could it be an issue with the underlying framework then?

**Comment by MichaelRumpler** [comment]
> **Additional context**
> The app does not crash, when I use the Windows.UI.Xaml.Controls.NavigationView instead of the WinUI control.

**Comment by chingucoding** [comment]
Yes, but that doesn't necessarily mean that the MUXC NavigationView is at fault, but rather that it is hitting an underlying framework bug. The fact that there doesn't seem to be any calls to MUXC.dll in the stacktrace of the crash is really strange.

**Comment by MichaelRumpler** [comment]
I don't want to be rude, but as a consumer I don't care whos fault it is. I only want it to work. And fact is: it works with the Windows.UI.Xaml.Controls.NavigationView, but not with the Microsoft.UI.Xaml.Controls.NavigationView.

If WinUI would be written in C#, I could debug it and maybe fix it myself, but unfortunately my C++ skills are very limited.

While I tested that, I also ran into another bug which also happens with the UWP control. I reported that one [here](https://developercommunity.visualstudio.com/content/problem/1101684/uwp-navigationviewiteminvoked-reports-wrong-item.html). So I do try to find the right place to report a bug. I was not so sure about the UWP issue, but this should be the right place for a bug which only happens in the WinUI version of NavigationView.

**Comment by chingucoding** [comment]
> I don't want to be rude, but as a consumer I don't care whos fault it is. I only want it to work. And fact is: it works with the Windows.UI.Xaml.Controls.NavigationView, but not with the Microsoft.UI.Xaml.Controls.NavigationView.

I can understand that you might not care whos fault it is, but the team and contributors who might want to fix this issue definitely care about informations into crashes, that is why I was sharing what I found out on this thread.

> If WinUI would be written in C#, I could debug it and maybe fix it myself, but unfortunately my C++ skills are very limited.

I also thought that I wouldn't able to go contribute to WinUI given that I never really worked with C++ back then, but in my opinion you can read the C++ code, even if you are only proficient with C#.

**Comment by ranjeshj** [comment]
@MichaelRumpler This is the correct repo to file both MUXC and WUXC issues. @chingucoding is correct in saying that the framework code is not part of this repo. But the plan is to move the framework code open source as well as part of the WinUI3 effort - so this is a good place to track those bugs. 

C# is unfortunately not an option for WinUI framework/controls code since it is used in purely native scenarios where we do not want the CLR loaded.
