### ISSUE TITLE
Update tile and icon generator templates

### ISSUE THREAD

**Issue by massijay** [microsoft/microsoft-ui-xaml#2821]
The [tile and icon generator templates](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/#tools) should be updated to match the new fluent design style.

In particular, the logo layer should have a default style applied, with the same effects (shadow, etc.) we find in first-party apps (such as Mail, Calculator, Paint 3D...) so developer can create icons coherent with other apps' with ease.

**Comment by mdtauk** [comment]
#2307

**Comment by StephenLPeters** [comment]
@chigy fyi
