### ISSUE TITLE
Proposal: Add Color.IsEmpty and Color.Empty

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#2826]
# Proposal: Add Color.IsEmpty and Color.Empty

## Summary

The Color struct in UWP/WinUI does not currently have an IsEmpty property or an Empty color field. This creates complications when trying to handle #00000000. Lack of support for this is likely also an issue with the WinUI ColorPicker (though I'm not addressing that here). This needs to be added just like it was in System.Drawing.Color from WPF.

API to add:

```csharp
public static readonly Color Empty;
public bool IsEmpty { get; }
```

## Rationale

Empty colors need to be fully supported without special code every time it's needed. Empty colors represent 'null' for no color has been selected or set. This is valid information that needs to be retained especially in pickers.

## Scope

| Capability | Priority |
| :---------- | :------- |
| public static readonly Color Empty | Must |
| public bool IsEmpty | Must |

## Important Notes
 * Color is missing several other properties that probably should be discussed as well `IsKnownColor`, `IsNamedColor` etc...

**Comment by mdtauk** [comment]
How is this different to **Color.Transparent**?

**Comment by robloo** [comment]
Color.Transparent is equal to #00FFFFFF. This was all designed like this on purpose. It allows you to just use the Color struct instead of having to have a 'null' value using a nullable Color.

**Comment by robloo** [comment]
Historically this convention was used in Size.IsEmpty, Rect.IsEmpty, etc... It allows 'no value' to be communicated without have to resort to 'null'. Representing 'no value' is required for logic all over the place and it's inefficient to use nullable structs for this.

**Comment by StephenLPeters** [comment]
@MikeHillberg I'm not sure that Windows.UI.Color is in our wheelhouse, is this one for project reunion?

**Comment by MikeHillberg** [comment]
It is, indeed, shipping first in WinUI3 (as Microsoft.UI.Color). We don't have support for members on structs in WinRT though, at least not yet, so we've been putting helpers like these on [ColorHelper](https://docs.microsoft.com/uwp/api/Windows.UI.ColorHelper).

**Comment by JaiganeshKumaran** [comment]
> It is, indeed, shipping first in WinUI3 (as Microsoft.UI.Color). We don't have support for members on structs in WinRT though, at least not yet, so we've been putting helpers like these on [ColorHelper](https://docs.microsoft.com/uwp/api/Windows.UI.ColorHelper).

.NET already provides special members on these, projecting members of ColorHelper on Color itself. But these kinds of trivial members are extremely inefficient when using WinRT, so I strongly believe these should be done through language-specific means. For C++, IsEmpty doesn't even make sense as you'll just write color == {}.

**Comment by robloo** [comment]
Very well, closing as I won't follow this further.
