### ISSUE TITLE
WinUI 3 Arm64 build?

### ISSUE THREAD

**Issue by eklipse2k8** [microsoft/microsoft-ui-xaml#2829]
Will you be providing Arm64 builds of WInUI 3 anytime soon?

**Comment by StephenLPeters** [comment]
Hey @eklipse2k8, this is a known issue with the winui3 preview. @JesseCol or @MikeHillberg FYI

**Comment by anawishnoff** [comment]
This functionality was provided with WinUI 3 Preview 3, so I'm going to close this issue. Feel free to re-open and let us know if the issue persists.
