### ISSUE TITLE
Scrolling behavior inconsistent between WinUI 3 and regular UWP Apps in WMR with mouse

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#2830]
**Describe the bug**
When scrolling in WinUI 3 apps with a mouse in Windows Mixed Reality, the scrolling experience is very different compared to a non WinUI 3 UWP app in Windows Mixed Reality.

**Steps to reproduce the bug**

1. Open the UWP XAML Controls Gallery WinUI 3 app in Windows Mixed Reality.
2. Try scrolling with a mouse.
3. Open the Settings app in Windows Mixed Reality.
4. Try scrolling with a mouse.

**Expected behavior**
Scrolling should feel the same in both apps.

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.WinUI 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@KonqiTheKonqueror do you know if this issue is unique to MixReality? Is is possible to get a video or some other way of seeing the issue in the bug report? most of the team does not have access to a mixed reality device.
