### ISSUE TITLE
Proposal: TabViewItem: Remove the Close button's tilt animation when pressed

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#2831]
# Proposal: TabViewItem: Remove the Close button's tilt animation when pressed
## Summary
The TabViewItem's Close button currently uses the standard UWP button tilt animation when pressed: https://github.com/microsoft/microsoft-ui-xaml/blob/78fa7f674364e7c3e0facd424760826d284296b6/dev/TabView/TabView.xaml#L279

Here's a demonstration of this effect:
![tabitemclosebutton-tilteffect](https://user-images.githubusercontent.com/1398851/86517482-830faa80-be29-11ea-866f-1aea05d146ef.gif)

If you don't really see the tilt animation here (because the button is very small) you can also open any app using a WinUI TabView (like the XAML Controls Gallery) and use Magnifier to zoom in.

This proposal aims to remove this tilt animation from the Close button. Without this animation, pressing the Close button will look like this:
![tabitemclosebutton-notilteffect](https://user-images.githubusercontent.com/1398851/86517419-0d0b4380-be29-11ea-945a-9df3272a59b7.gif)

## Rationale
Personally, the tilt animation, especially when you click on the corners of the Close button, looks kinda weird to me here.
More importantly though, other TabView controls like seen in Edgium or - I believe - Edge UWP do not have this tilt animation for their TabViewItem's Close button. Furthermore, The Clear button used in the TextBox, AutoSuggestBox, NumberBox,..controls doesn't have this tilt animation either: https://github.com/microsoft/microsoft-ui-xaml/blob/78fa7f674364e7c3e0facd424760826d284296b6/dev/CommonStyles/TextBox_themeresources.xaml#L144

Aslo add in issue https://github.com/microsoft/microsoft-ui-xaml/issues/242 which states that a button is often re-templated simply to remove this tilt animation. As this animation is not present in other well-known apps using Tab controls or for buttons used in a similar context like the TextBox's Clear button, it seems like a good call to me here to remove this built-in animation for the TabViewItem's Close button.

## Important Notes
The Close button's tilt animation is currently the only way in High-contrast mode to distinguish between the hover state and the pressed state: 
![tabitemclosebutton-tilteffect-HC](https://user-images.githubusercontent.com/1398851/86517517-d255db00-be29-11ea-8248-c2ca58453621.gif)

As part of a PR for this proposal - if greenlit - we should update the Close button's hover and pressed theme resources in High-contrast mode to provide a visual distinction between these two states.

**Comment by chingucoding** [comment]
The thing with high contrast is, that that is the default behavior for pressed. Given that AppBarButton does not have the animation and thus looks same onhover and pressed in high contrast, maybe this is a gap. 

@YuliKl Do you know what the best guidance is here?

**Comment by YuliKl** [comment]
I would be very hesitant to remove the tilt animation as a one-off behavior change, and believe this case would be best handled holistically in #242. Yes, TextBox companion buttons do work differently and avoid tilt. I acknowledge we have introduced fragmentation in the tilt behavior as a result of historic decisions, but this proposal feels like it's more likely to add further inconsistencies.

Perhaps @kikisaints can revive #242. Although removing tilt requires WinUI 3 so probably isn't feasible for a while.

**Comment by Felix-Dev** [comment]
@YuliKl Should I close this proposal then?

**Comment by ranjeshj** [comment]
@Felix-Dev Yes. Lets close this and track it as part of #242 . Thanks!
