### ISSUE TITLE
Setting TeachingTip.Template causes an unhandled win32 exception

### ISSUE THREAD

**Issue by tesar-tech** [microsoft/microsoft-ui-xaml#2832]
**Describe the bug**
Running this piece of code causes the exception:

```xaml
 <winui:TeachingTip IsOpen="True" Title="Helou">
            <winui:TeachingTip.Template>
                <ControlTemplate>
                    <Grid/>
                </ControlTemplate>
            </winui:TeachingTip.Template>
        </winui:TeachingTip>
```

**Expected behavior**
At least it should not crash...

**Version Info**
OS build 18363.900 (1909)
NuGet package version: 2.4.2

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |

**Comment by maxkatz6** [comment]
> At least it should not crash...

It should, you are redefining standard control template, but not defining expected elements inside of it. At least [Border#Container](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/TeachingTip/TeachingTip.xaml#L21) is missed, and it is required for minimal teachingtip work. But I would except exceptions about other elements too.

But it should crash with more specific error message.

**Comment by maxkatz6** [comment]
In general, you need to update existed template (copy-paste and update), but not creating new one.

**Comment by tesar-tech** [comment]
Oh, I see. Thank you.
