### ISSUE TITLE
Rectangle ambiguous reference in XAML

### ISSUE THREAD

**Issue by IbrahimElshafey** [microsoft/microsoft-ui-xaml#2837]
**Describe the bug**
After updating to the latest Xamarin forms version (4.7.0.1080) which contains a new UI element called rectangle in namespace **Xamarin.Forms.Shapes** I can't use a constructor for rectangle type which is a `struct` in namespace **Xamarin.Forms**

**Steps to reproduce the bug**
1. Create new Xamarin forms App
2. Add an `AbsoluteLayout` element to MainPage 
3. Set 'AbsoluteLayout.LayoutBounds' in XAML as below
```
<AbsoluteLayout.LayoutBounds>
     <Rectangle X="0" Y="1" Width="1" Height="1" />
</AbsoluteLayout.LayoutBounds>
```

**The Problem**
The project will not be built and the error appeared:
XFC0009	No property, BindableProperty, or event found for "Height", or mismatching type between value and property.

**Expected behavior**
Use both UI rectangle and rectangle struct constructor without a problem in XAML file.

**Version Info**

NuGet package version: 
[Xamarin.Forms 4.7.0.1080]

**Comment by chingucoding** [comment]
This looks like an issue with Xamarin XAML, not WinUI/UWP XAML. I think the [Xamarin forms repo](https://github.com/xamarin/Xamarin.Forms) would be the right place to create that issue.

**Comment by StephenLPeters** [comment]
@chingucoding is correct, @IbrahimElshafey Could you please open this issue on that Github instead?

**Comment by Reintjuu** [comment]
@IbrahimElshafey, I know this is closed but I've found a workaround. You can import the Shapes namespace in your view to prevent the conflict:

```C#
xmlns:Shapes="clr-namespace:Xamarin.Forms.Shapes;assembly=Xamarin.Forms.Core"
```

And use the namespace's Rectangle:

```C#
<Shapes:Rectangle />
```
