### ISSUE TITLE
Enable testing on Arm64 platform

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#284]
Helix has Arm64 queues so we should be able to use them to execute Arm64 tests.
The taef.redist.wlk nupkg does contain Arm64 versions of the taef binaries, so we should be good there.
The WDK also includes an Arm64 version of wttlog.dll, so we can use that.

First we need to be able to build and run our test collateral for Arm64.

**Comment by azchohfi** [comment]
Win2D now supports ARM64 https://www.nuget.org/packages/Win2D.uwp/1.24.0
