### ISSUE TITLE
Question: Persaonal Access Token

### ISSUE THREAD

**Issue by jdm7dv** [microsoft/microsoft-ui-xaml#2841]
I need a PAT for microsoft.visualstudio.com

Thanks,

Jonathan

**Comment by StephenLPeters** [comment]
I'm not sure what your question is for, I think this is not the correct place to receive this. Here is some [documentation on PAT](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
