### ISSUE TITLE
NavigationView fails to show selection indicator when first loading the app

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#2845]
**Describe the bug**

I am not able to see the selection indicator next to my item when my app first loads. I've tried setting both `IsSelected` in markup and `SelectedItem` in code behind. Subsequently clicking on a item shows selection as expected. I'm using hierarchical nav in my app.

**Steps to reproduce the bug**

Launch the app. Source code: https://github.com/YuliKl/WinUI-2-4-Test

**Expected behavior**

RadialGradientBrush item looks selected.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/86648788-04844b80-bf96-11ea-9800-c9093cbba3da.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.2

**Additional context**

This feels like a familiar issue but I wasn't able to find a dupe. Possibly regressed after adding hierarchy?

**Comment by chingucoding** [comment]
There is #2813 which happens if the NavigationView switches between DisplayMode Top and Left.

**Comment by Felix-Dev** [comment]
Yes, while I can repro this, it is worth checking out if this won't be fixed by PR #1997.

**Comment by Felix-Dev** [comment]
Ok, for once, that PR *won't* fix this issue in its current state.

https://github.com/microsoft/microsoft-ui-xaml/blob/71a81bc4a0bf58900dfac9b7019158344eaa235c/dev/NavigationView/TestUI/HierarchicalNavigationViewMarkup.xaml#L35
Setting the item above to `IsSelected=true` doesn't show the selection indicator and its also not selected in the `NavigationView.SelectedItem` API. The expected look on here would be:
![image](https://user-images.githubusercontent.com/1398851/86655344-ed217e80-bfe6-11ea-8512-f37b40ba39e6.png)
But the actual look is this:
![image](https://user-images.githubusercontent.com/1398851/86655229-d9761800-bfe6-11ea-94ba-8deab657295b.png)

As such, it seems like we will need to tackle this on in its own PR. I would be up to take at look into this though I also won't mind if others have an interest (like @chingucoding) to take this one on.

**Comment by StephenLPeters** [comment]
@ojhad FYI

**Comment by tpxxn** [comment]
The first time I chose sub-items instead of top-level items, I had this problem.

**Comment by chingucoding** [comment]
@tpxxn Yes this is currently a limitation/bug with hierarchical NavigationView, see #3015 for additional context.
