### ISSUE TITLE
Release version of DatePicker not binding to, or simply not rendering provided date on load

### ISSUE THREAD

**Issue by TomgGX** [microsoft/microsoft-ui-xaml#2846]
[Microsoft.UI.Xaml 2.1.190606001]

Debug version working fine.

**Comment by StephenLPeters** [comment]
Thanks for the bug, could you please provide a repro app so that we can see the issue in action?

**Comment by TomgGX** [comment]
Hi Stephen,

We’ll create UWP ap that reproduces the issue and get it out to you.

Thanks,
-Tom

**Comment by StephenLPeters** [comment]
Awesome thank!

**Comment by TomgGX** [comment]
Hi Stephen,

As you might have guessed we found a work-around for the UWP DataPicker issue.

We have a different issue with the UWP TreeView control.

Our nodes are 3 levels deep, and if we select a top level node we only get one level down showing
up in the SelectedNodes collection. We have to expand the top level node as well in order to select
all the node’s children.  Where using this feature for an archive process, so when the user selects a top level
node expecting to archive all the data associated with this selection, they’re missing data.

Please advise…

Thanks,
-Tom

**Comment by TomgGX** [comment]
We’re running in MultiSelect mode, so I can’t use the that click event handler.
Is there a way of picking up a click event on the top-level node after the tree-view
Is populated.  If I could do this I could automatically expand the node so the user
Would pickup all the data

From: Grosso, Thomas J
Sent: Wednesday, July 29, 2020 4:37 PM
To: microsoft/microsoft-ui-xaml <reply@reply.github.com>
Subject: RE: [microsoft/microsoft-ui-xaml] Release version of DatePicker not binding to, or simply not rendering provided date on load (#2846)

Hi Stephen,

As you might have guessed we found a work-around for the UWP DataPicker issue.

We have a different issue with the UWP TreeView control.

Our nodes are 3 levels deep, and if we select a top level node we only get one level down showing
up in the SelectedNodes collection. We have to expand the top level node as well in order to select
all the node’s children.  Where using this feature for an archive process, so when the user selects a top level
node expecting to archive all the data associated with this selection, they’re missing data.

Please advise…

Thanks,
-Tom

**Comment by StephenLPeters** [comment]
Can you please open a new issue for the new treeview bug.
