### ISSUE TITLE
TeachingTips in page can cause memory leaks

### ISSUE THREAD

**Issue by cnbluefire** [microsoft/microsoft-ui-xaml#2849]
**Describe the bug**
When create a TeachingTips in ResourceDictionary and navigate to another page, the old page will not be released by GC.

**Steps to reproduce the bug**

1. Create PageA include TeachingTips Sample: [https://docs.microsoft.com/zh-cn/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip#create-a-teaching-tip](https://docs.microsoft.com/zh-cn/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip#create-a-teaching-tip).
2. Then navigate to PageB, and back to PageA, repeat this action.
3. Open the diagnostic tool window and take a memory snapshot. We will see multiple PageA when we search "PageA" in this snapshot. Every PageA were holding in memory by TeachingTips.

**Expected behavior**
In the diagnostic tool, we should not see multiple PageA.

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.4.2
| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by cnbluefire** [comment]
The memory gets released properly if you don’t put the TeachingTips in the ResourceDictionary like this:
```xaml
<Button x:Name="SaveButton" Content="Save" />
<muxc:TeachingTip x:Name="AutoSaveTip"
            Target="{x:Bind SaveButton}"
            Title="Save automatically"
            Subtitle="When you save your file to OneDrive, we save your changes as you go - so you never have to.">
</muxc:TeachingTip>
```

**Comment by StephenLPeters** [comment]
@cnbluefire does the repro require that the teaching tip be open when you navigate away? Or only that it have ever been opened (and then closed)? Or does the open/close status not matter at all?

**Comment by cnbluefire** [comment]
> @cnbluefire does the repro require that the teaching tip be open when you navigate away? Or only that it have ever been opened (and then closed)? Or does the open/close status not matter at all?

Sometimes it leaks when the tip has been opened, you should navigate to another page and go back multiple times.
