### ISSUE TITLE
NavigationView.MenuItems not populated when using NavigationView.ItemsSource

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2852]
**Describe the bug**

If I bind the to `NavigationView.ItemsSource` and use DataTemplate like below, I am not able to see any items in  NavigationView.MenuItems.

**Steps to reproduce the bug**

```
    <winui:NavigationView
        x:Name="NavigationView"
        x:Uid="Settings_Title" IsPaneToggleButtonVisible="False"
        PaneDisplayMode="LeftCompact" CompactModeThresholdWidth="0"
        IsSettingsVisible="False"
        IsBackButtonVisible="Collapsed"
        Background="{ThemeResource SystemControlBackgroundAltHighBrush}">
        <winui:NavigationView.MenuItemTemplate>
            <DataTemplate x:DataType="models:IRepository">
                <winui:NavigationViewItem Content="{x:Bind Name}">
                    <winui:NavigationViewItem.Icon>
                        <FontIcon x:Name="OptionIcon" Grid.RowSpan="2" FontFamily="Segoe MDL2 Assets" Glyph="{x:Bind Icon}" FontSize="40" />
                    </winui:NavigationViewItem.Icon>
                </winui:NavigationViewItem>
            </DataTemplate>
        </winui:NavigationView.MenuItemTemplate>
```

**Expected behavior**

`MenuItems` should still be populated

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Felix-Dev** [comment]
Can you create a repro app? I tested your XAML markup on Windows 10 19041 and Microsoft.UI.Xaml 2.4.2 and I cannot reporduce your issue. The NavigationView is populated in my case.

**Comment by harvinders** [comment]
@Felix-Dev NavigationView is populated but when I try to get the MenuItems it returns empty MenuItems.

**Comment by Felix-Dev** [comment]
@harvinders Ah, my bad.

Yeah, this seems like a bug to me since it works for the TabView control (you can use the TabView.TabItemsSource API to bind a data source and then also access it via the TabView.TabItems API). It would expect this to work the same way for the NavigationView then.

**Comment by ranjeshj** [comment]
Curious why you need the TabItems ? Are you trying to get the NavigationViewItems when you have provided a collection to MenuItemsSource ? What if the items are virtualized ?

**Comment by StephenLPeters** [comment]
@harvinders is there something blocking you from accessing the items through the .ItemsSource property instead?

**Comment by harvinders** [comment]
@StephenLPeters I was trying to migrating WTS generated code to use dynamic NavigationViewItems instead of the statically declared one. The logic there required that I iterate over the MenuItems. However, I realised that I don't need that and I can achieve same using SelectedItem and ItemsSource.

**Comment by ranjeshj** [comment]
@harvinders Thanks for the info. Going against those properties is a better idea when using ItemsSource.
