### ISSUE TITLE
ContentDialog.PrimaryButtonText/SecondaryButtonText throws ArgumentNullException

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#2853]
**Describe the bug**
`ContentDialog`'s `PrimaryButtonText` or `SecondaryButtonText` properties are throwing an `ArgumentNullException` when set to `null`.

**Steps to reproduce the bug**
1. Create a new app and add the following code in a button click event handler:
```csharp
private async void Button_Click(object sender, RoutedEventArgs e)
{
    var dialog = new ContentDialog
    {
        Title = "Title",
        PrimaryButtonText = "OK",
        SecondaryButtonText = null,
        CloseButtonText = "Close"
    };

    await dialog.ShowAsync();
}
```
2. Click on the button

**Observed behavior**
The application crashes with an uncaught `ArgumentNullException`.

**Expected behavior**
The content dialog is displayed.

**Version Info**
WinUI is not used.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

**Additional context**
The documentation available [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog.primarybuttontext?view=winrt-19041) and [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog.secondarybuttontext?view=winrt-19041) says that `null` is an allowed value.

> The text to display on the primary[/secondary] button. To hide this button, set the text to **null** or string.empty. The default is empty.

**Comment by robloo** [comment]
This behavior is the same as TextBox and TextBlock. UWP doesn't like setting null to the text properties -- unlike WPF. 

The solution I always use is `.Text = SomeText ?? string.Empty;`

**Comment by StephenLPeters** [comment]
This can and should be fixed post WinUI3 but until that is available we should changed the docs to reflect that this doesn't work. @YuliKl FYI.
