### ISSUE TITLE
Bug: NavigationViewItem is left in bad visual state on click-drag-exit interaction.

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/microsoft-ui-xaml#2860]
**Describe the bug**

NavigationViewItems in a NavigationView can be left in a broken visual state by clicking them and dragging away outside of the parent NavigationView.

**Steps to reproduce the bug**

1. Open the XAML Controls Gallery
2. Go to the NavigationView examples
3. Click and drag away from any NavigationViewItem in Left or Top mode

**Expected behavior**

Pointer state should be returned to `c_normal` or `c_selected`.

**Screenshots**

![NavigationView_PointerExitBug](https://user-images.githubusercontent.com/5379488/86874423-515b4580-c0ae-11ea-891e-eb61febf3dc5.jpg)

**Version Info**

NuGet package version: 
2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This could probably be fixed by just adding `m_isPressed = false;` to `OnPresenterPointerExited`:

https://github.com/microsoft/microsoft-ui-xaml/blob/a33c9f9d73863082a47a3b60740a404d61f26708/dev/NavigationView/NavigationViewItem.cpp#L784-L799

**Comment by ranjeshj** [comment]
This might be one of the issues fixed by [this](https://github.com/microsoft/microsoft-ui-xaml/pull/2625) change.

**Comment by kmgallahan** [comment]
Ah, yes, looks like #3.

**Comment by kmgallahan** [comment]
@ranjeshj As an aside, kind of amusing that repo issues 1-5 get lots of mentions piled on due to the common use of # + *

https://github.com/microsoft/microsoft-ui-xaml/issues/3
