### ISSUE TITLE
Can't use WinUI ("XamlControlResources" does not exist) in XML editor 

### ISSUE THREAD

**Issue by devcoar** [microsoft/microsoft-ui-xaml#2862]
**Describe the bug**

I have created a new blank UWP app. Did the instructions as per the [Documentation](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started) - installed the NuGet package, added necessary lines to App.xaml and MainPage.xaml.

And this is what I get: 
`The name "XamlControlsResources" does not exist in the namespace "using;Microsoft.UI.Xaml.Controls".`

This is basically what my App.xaml looks like:
```
<Application
    x:Class="Devcor_s_Multitool.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Devcor_s_Multitool">

    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>

</Application>
```
    
I am running the latest (2004) version of Windows 10 and the latest stable Visual Studio (16.6.3) with the 2.4.2 package version.

**Comment by StephenLPeters** [comment]
@devcoar the error message has this `using;Microsoft.UI.Xaml.Controls` with a semi-colon `;` not a colon `:`. Is this just a typo? if you replace the ; with a : does it resolve the issue?

**Comment by devcoar** [comment]
@StephenLPeters unfortunately, i just mistyped the error message. In the project, I have a colon.

**Comment by StephenLPeters** [comment]
@devcoar can you provide a link to your repro app so we can take a look at this specifically?

**Comment by devcoar** [comment]
@StephenLPeters, it's basically a newly created empty UWP app with Microsoft.UI.Xaml NuGet package installed and two new lines added to App.xaml and MainPage.xaml according to the setup guide I mentioned in my original post.
But here you go:
https://github.com/devcoar/EmptyUWP

**Comment by ranjeshj** [comment]
@devcoar your repro app builds and runs fine for me. Can you check if you are seeing any errors during nuget restore ? You can try right clicking on the solution file and clicking on restore nuget packages.

**Comment by devcoar** [comment]
@ranjeshj That's the thing... The app runs fine for me as well. And the restore NuGet packages didn't yield any results - it says nothing to restore.

But the thing is:
a) I'm still getting that error for the App.xaml (`The name "XamlControlsResources" does not exist in the namespace "using;Microsoft.UI.Xaml.Controls".`) for this line:
![image](https://user-images.githubusercontent.com/13005446/87120835-16ae0480-c28a-11ea-9130-2eabb84bb812.png)
You can even see the tiny wavy line showing me where the error is.

b) I don't see the WinUI components in the toolbox... I did initially when I installed the Windows.ui.xaml package, but after the restart it's gone.

**Comment by ranjeshj** [comment]
If the app builds and runs fine, then this is likely an intellisense error that designer/editor is showing. @stevenbrix @fabiant3

**Comment by devcoar** [comment]
I think that this is indeed IntelliSense error.
I have recreated everything from scratch in a new project - works fine there)
