### ISSUE TITLE
Discussion: [WinUI treeview vs UWP treeview performance]

### ISSUE THREAD

**Issue by syncsiva** [microsoft/microsoft-ui-xaml#2863]
# Discussion: [WinUI treeview is slower than UWP treeview] 

I have created two samples using WinUI UWP and UWP and both sample uses exactly same ViewModel.

| PLATFORM | Loading 1K root nodes [each root node has 500 sub nodes] | Demo app |
| ------------- | ------------- |------------- |
| UWP| 0.2 secs | [UWP App](https://github.com/microsoft/microsoft-ui-xaml/files/4889482/uwpapp.zip) |
| WinUI | 1.7 secs | [WinUI UWP App](https://github.com/microsoft/microsoft-ui-xaml/files/4889484/winuiuwpapp.zip) | 

## Related Links
https://github.com/microsoft/microsoft-ui-xaml/issues/2686

**Comment by StephenLPeters** [comment]
@syncsiva Which version of WinUI are you comparing to?

**Comment by syncsiva** [comment]
@StephenLPeters  I'm using [WinUI 3 preview](https://www.nuget.org/packages/Microsoft.WinUI).
