### ISSUE TITLE
RadioButton defaults to 120 MinWidth

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#2864]
**Description**

RadioButton defaults to MinWidth=120, I have to explicitly set it to 0 to override this behaviour. In my case, I've applied a template to completely override the buttons visuals, making it like an ImageButton so this behavior is probably highlighted as a bug particularly in cases where the control has a template applied. But you can see the behavior with the normal RadioButton and then imagine how that is going to create friction when templates are applied. I don't even understand how RadioButton can express layout onto a template.

**Steps to reproduce the bug**

Create a RadioButton as follows...

`            <RadioButton 
                        Width="42" Height="42" Margin="2"
                        Background="Orange"/>`

Here's the template I've applied which does not contain a configuration for MinWidth...

`    <ControlTemplate x:Key="ImageRadioBtnTemplate" TargetType="RadioButton">
        <Border Width="40"
            BorderBrush="Gray"
            BorderThickness="2"
            Background="{TemplateBinding Background}">
        </Border>
    </ControlTemplate>`

**Expected behavior**

I expect the radio button to adopt a width of 42 as described in the code.

**Screenshots**

![Annotation 2020-07-08 222908](https://user-images.githubusercontent.com/4374176/86918795-7f9e5b00-c16a-11ea-9f98-f15f2b9d19c5.png)

**Version Info**

WinUI 2.4.2

NuGet package version: 

Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Felix-Dev** [comment]
That sounds a lot like issue https://github.com/microsoft/microsoft-ui-xaml/issues/2671.

**Comment by StephenLPeters** [comment]
Yes, this is the same issue. The reason that MinWidth has been set on these controls is that we require a large size (120px wide) to meet accessibility standards for touch input on these controls. Setting Width does not override MinWidth, but the app developer is able to set MinWidth themselves to something else. We'd encourage you to consider touch scenarios before you do this though.

**Comment by Gavin-Williams** [comment]
I'm overriding it anyway, because 120px width is too wide, it's ridiculously wide. Your design team is wrong, sorry. 120px is not the minimum size of buttons. I'm also making this app for desktop and mouse. I don't even own a Windows touch device and I'm not going to be particularly supporting touch devices. Even if I did down the track, I still wouldn't make the button 120 pixels wide. That's nonsense. Absolute nonsense. When I look around my desktop and my phone, there actually aren't too many clickable elements that I can see that are 120px.

You should reconsider trying to enforce weird rules about UI supporting touch and accessibility in particular cases like this? App developers are not going to adopt odd-ball control sizes like 120px in their apps for accessibility reasons. It just doesn't work. I would switch to Linux in a heartbeat if you adopted LCD (Lowest Common Denominator) design specs.

I'm actually shocked that this is the reason, I thought you were going to respond that when RadioButton was originally designed, one particular design was in mind and it was an oversight that the MinWidth was set in place. And that the team maybe hadn't envisioned how RadioButton was going to be used with templates.

**Comment by StephenLPeters** [comment]
The microsoft accessibility guidance is that minimum touch targets be one of:

-  44 pixels high by 44 pixels wide  (it might be 40x40, my memory is failing me)

- 32 pixels high by 120 pixels wide

Most of the time RadioButtons and Checkboxes have content associated with them which brings their touch target width well above 120 pixels:

- [ ] Remember My Password

but sometimes they don't: 

- [ ] 1

In the latter case the minimum width allows us to adhere to these accessibility standards without having to make this specific checkbox's footprint taller.

Then there is the question of why these numbers were chosen. The answer is that we are building a framework which we want to be inclusive to as many Windows users as possible, by default.  Some developers will not consider the users who need to use touch screen devices and may not be capable of precise inputs, lets say for some medical reason. By making the controls accessible to these users by default we can make apps built on the framework more friendly to these users. We understand that this decision has down sides and sometimes the app developer will decide that they need to override the default value but the upsides of supporting that class of users and devices outweigh the downsides in our mind. Here is a [link](https://ux.stackexchange.com/questions/39023/what-is-the-optimum-button-size-of-touch-screen-applications) to another discussion on touch button sizes, although I think it is focused on able users. I hope this better answers your concerns.
