### ISSUE TITLE
Controls are not rendered properly after installing WinUI 2.4.2

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2868]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1105051/controls-are-not-rendered-properly-after-installin.html)._

---
So VS was previewing my Xaml fine with just the UWP. UI but with WinUI installed as well, none of the text is rendered - menu's & textblocks.

---
#### Feedback Bot on 7/7/2020, 07:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
We need some additional information. Is this a xaml designer issue, or is the app rendering incorrectly after you build as well. Can you provide screenshots/videos/a repro app?

**Comment by Gavin-Williams** [comment]
This is just in VS Xaml designer. It renders fine at runtime.

**Comment by Gavin-Williams** [comment]
![Annotation 2020-07-18 160952](https://user-images.githubusercontent.com/4374176/87846197-7dc65b80-c911-11ea-85d5-968feedfb759.png)

Here you can see that the menu text is not being rendered.

**Comment by StephenLPeters** [comment]
@fabiant3 the user is reporting this as new as of Winui 2, so its probably something the controls team did, but I think you might have more luck figuring out what it was?
