### ISSUE TITLE
Adding a NavigationView to the application in certain way causes user to click once before clicks have any impact

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2872]
**Describe the bug**

Please see the repo for [sample app](https://github.com/harvinders/ShadowTestApp). The first click on the application has no impact on the application.

**Steps to reproduce the bug**

1. Create a SplitView and add a NavigationView with the `PaneDisplayMode="LeftCompact"` to the `SplitView.Pane`
2. Add a button to the Content of SplitView
3. Click on the button
4. Button is not clicked
5. Click again on the button
6. Button is clicked

Setting the `PaneDisplayMode="Top"` removed the problem.

**Expected behavior**

Clicking first time should have the desired effect.

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes|
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@harvinders the linked repro project doesn't have a navigation view in it. Was there a typo?

**Comment by harvinders** [comment]
@StephenLPeters NavigationView is present in the SettingsPage.xaml file.

**Comment by mdtauk** [comment]
> @StephenLPeters NavigationView is present in the SettingsPage.xaml file.

So you are loading a NavigationView inside a Page, inside a Frame, inside a SplitView, on a main page in the CoreWindow?

**Comment by StephenLPeters** [comment]
Can you try setting the display mode of your outer split view to something other than overlay? I think that what may be happening is that the first click is dismissing the Overlay split view pane (light dismiss)

**Comment by harvinders** [comment]
@mdtauk What I am trying to do is something like the old edge settings page. It comes from the right when a button is pressed and shows you all the different settings using navigation view. 

@StephenLPeters However I don't the issue if the NavigationView's PaneDisplayMode="Top". Also removing the Overlay as suggested had no impact.

**Comment by mdtauk** [comment]
> @mdtauk What I am trying to do is something like the old edge settings page. It comes from the right when a button is pressed and shows you all the different settings using navigation view.
> 
> @StephenLPeters However I don't see the issue if the NavigationView's PaneDisplayMode="Top". Also removing the Overlay as suggested had no impact.

Have you considered doing the Settings as a UserControl?  In the Pane of the SplitView on the Main Page
