### ISSUE TITLE
App Crash After Store Submission

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2882]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1105456/app-crash-after-store-submission.html)._

---

App runs fine debug and release mode and when compiled version is installed with the power script. However, once the app is submitted to the store and downloaded from there, it crashes at the startup. Spend months trying to figure it out. Started my app from scratch and rewrote the whole thing a few times trying to figure out the issue. Finally found App Center SDK/API that helped me with at least some hint about the app is crashing.

Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources' [Line: 0 Position: 0]
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
   at __Interop.ForwardComStubs.Stub_8[TThis](__ComObject, Int32) + 0x24
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper. <.ctor>b__17_1(Object, UnhandledErrorDetectedEventArgs) + 0x3d

It appears to be similar issue as here: https://github.com/microsoft/microsoft-ui-xaml/issues/616. The dependency is included in the installed version.

<Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.18362.0" MaxVersionTested="10.0.18362.0" />
    <PackageDependency Name="Microsoft.UI.Xaml.2.4" MinVersion="2.42005.18002.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
    <PackageDependency Name="Microsoft.NET.Native.Framework.2.2" MinVersion="2.2.27912.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
    <PackageDependency Name="Microsoft.NET.Native.Runtime.2.2" MinVersion="2.2.28604.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
    <PackageDependency Name="Microsoft.VCLibs.140.00" MinVersion="14.0.27810.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
  </Dependencies>

---
#### Feedback Bot on 7/8/2020, 00:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### sdfdsfsdf on 7/9/2020, 08:40 PM: 

<p>The issue is potentially solved.</p><p>For some reason the Microsoft.UI.Xaml.winmd file for version 2.4.2 has "AL" attributes. Because of the "L" attribute, it does not get copied during the build process. As such, the app builds without the winmd file fails to start. I switched to winui 2.4.0. The winmd file for this version has attribute "A" and it gets copied successfully while building. I am not sure if the attributes are different because of something I did or it was meant to be like that for some reasons.</p><p>I'll wait and see if the version gets accepted.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
Seems similar to #1712.  Also maybe these internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/26540032) [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/24872104)

**Comment by jevansaks** [comment]
This sounds like the problem where an older version of VS (like VS2017) was used to compile the app. In that case the store needs to recompile the app's IL with the newer .NET Native but it fumbles the recompile because that version of VS also fails to include the Windows.UI.Xaml.winmd in the app's package, resulting in an app that crashes. The customer should be able to upgrade to a newer version of VS2019 to resolve the issue.

**Comment by shresthasource** [comment]
I'm using visual studio 2019. So, not an issue with 2017 version.

**Comment by shresthasource** [comment]
So, continued to have similar problem. This time it is Microsoft.UI.Xaml.winmd and Microsoft.Toolkit.Uwp.UI.Controls.xr.xml files. These files inside .nuget/packages folder have AL attributes.

**Potential Workaround** 
Create a copy of these files of the files with issue: Properties -> Details -> Remove Properties and Personal Information -> Create a copy with all possible properties removed. Replace the original one with the new copy. Probably a good idea to rename original file, just in case.

**Comment by ranjeshj** [comment]
Attribute L seems to mean reparse point - https://docs.microsoft.com/en-us/windows/win32/fileio/reparse-points . @shresthasource Is something special about the folder you are building the app under ?

**Comment by shresthasource** [comment]
@ranjeshj I have my code in OneDrive folder. But, every time I need to build it for store submission, I copy it to desktop (not included in OneDrive). If I build from the OneDrive synced folder, it always have issue copying asset files. The .nuget/package is in my user directory C:\Users\username\.nuget.
