### ISSUE TITLE
UWP - WinUI 3.0 Error: No overload for 'ButtonTest_Click' matches delegate 'RoutedEventHandler'

### ISSUE THREAD

**Issue by saf-itpro** [microsoft/microsoft-ui-xaml#2887]
I'm working on [Windows UI Library 3.0 Preview 1][1]. Have performed all the `4 steps` for [prerequisites][2]. On `VS2019 - Preview`, created a project using `UWP blank` template for `WinUI 3`. Added a button and it's click event as follows. And I get the following compile error:

**Error**:
>>No overload for 'ButtonTest_Click' matches delegate 'RoutedEventHandler'

**Remark**: 

 1. Error shows the file `C:\DotNET5VS2019\UWP\UWP_WinUITest\obj\x86\Debug\MainPage.g.cs`
 2. On my `Windows 10 Pro- v1903`, the project max version was selected as `1903` and min as `1809`

 **MainPage.Xaml**:

    <Page
      x:Class="UWP_WinUITest.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:UWP_WinUITest"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    
      <Grid>
            <Button x:Name="ButtonTest" Content="Test" Click="ButtonTest_Click"/>
      </Grid>
    </Page>

**MainPage.xaml.cs** [Note: the contenct inside the event has nothing to do with the error as exact error occurs even without these content:

    private void ButtonTest_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
    {
        var msgDialog = new MessageDialog("Test message");
        msgDialog.ShowAsync();
    }

**Question**: What could be the cause of the error, and how can it be resolved?

  [1]: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/
  [2]: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop#prerequisites

**Comment by MikeHillberg** [comment]
This is an issue with the current state of the preview. Changing the event args parameter from Windows to the Microsoft namespace should fix it:

```cs
private void ButtonTest_Click(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
```

**Comment by saf-itpro** [comment]
@MikeHillberg You are the best. Your suggestion worked (thank you). Special thanks for pointing out that this is an issue with the current state of the preview so I know I wasn't missing something.
