### ISSUE TITLE
WinUI 3.0: Why UWP project is asking for MS Edge for Business for WebView2?

### ISSUE THREAD

**Issue by saf-itpro** [microsoft/microsoft-ui-xaml#2888]
When I use `WebView2` control in a `UWP` project with `WinUI 3.0` and run the app, the webpage inside `WebView2` control is not displayed. Instead, the app displays the following message that takes me to [Microsoft Edge for Business][1] download page:

>a suitable version of Microsoft edge was not detected. Please install the latest beta channel build from [here][1]

**Question**: Why it's asking for Microsoft Edge for Business? I already have the latest version of `MS Edge Canary Channel` and the latest release version MS Edge installed on my `Windows 10 - Pro`. I don't want to install too many versions.

**MainPage.xaml**:

    <Page
      x:Class="UWP_WinUI.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:UWP_WinUI"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
            <WebView2 x:Name="wvTest" Grid.Row="1" Source="https://www.bing.com/"/>
        </Grid>
    </Page>

**Display of the app**

The webpage is supposed to display in the `WebVeiw2` below the button control. But instead, the message (shown below) is displayed:

[![enter image description here][2]][2]

  [1]: https://www.microsoft.com/en-us/edge/business/download
  [2]: https://i.stack.imgur.com/IOsHP.png

**Comment by ranjeshj** [comment]
@codendone as FYI

**Comment by codendone** [comment]
You're right, we're not pointing to the best download link. Edge *for Business* is **not** required. What is required is a sufficiently recent install containing the WebView2 runtime with the Beta channel currently recommended, and https://www.microsoftedgeinsider.com/ would have been a better link to point to.  The link at https://developer.microsoft.com/en-us/microsoft-edge/webview2/ for the WebView2 Runtime installer is theoretically even better, though we're only just starting to update to that version and haven't tested if WinUI Preview is compatible with that.

This will, of course, be changing when the WebView2 runtime moves out of preview.

**Comment by saf-itpro** [comment]
@codendone Mike, I eventually installed [MS Edge Deve Channel](https://www.microsoftedgeinsider.com/en-us/download/) that may be the same thing your first link refers to. The Dev Channel actually just updated my existing MS Edge (not Cannary Channel), and my app started working now. If you think your first link would have done the same, this post can be closed now.

**Comment by StephenLPeters** [comment]
Lets leave this open to track the changing of the link.

**Comment by codendone** [comment]
The fix for this was just checked in, and will be included in the next preview. Since that's done, I'll now close this.

**Comment by saf-itpro** [comment]
@codendone Thank you for having the issue fixed. Hopefully in the next preview it would not be confusing.
