### ISSUE TITLE
Question: Why does NavigationView enforce min width for custom content pane

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#2890]
The NavigationView enforces a minwidth of 48px for custom pane content when in DisplayMode top:

https://github.com/microsoft/microsoft-ui-xaml/blob/1672b337111e7f1d36a1b3aebf27ead9a0fcbc2b/dev/NavigationView/NavigationView.xaml#L236

However this can seem a bit strange in compact overlay which allows a very narrow window, which can result in content being pushed off the screen by essentially nothing as the 48px are always being enforced.

See this gif for an example of how it currently behaves:
![gif](https://user-images.githubusercontent.com/16122379/87258028-9f05f280-c4a0-11ea-8eb9-1fe371504b92.gif)

-------------------------

Currently the only way to get rid of it, is to retemplate the control. Should we introduce a lightweight styling resource for this, to make it easier to customize this?

**Comment by StephenLPeters** [comment]
@YuliKl FYI

@chingucoding how are you getting the app window to be so narrow? isn't there a min window width?

**Comment by chingucoding** [comment]
In compact overlay the minimum dimensions are 150x50 if I recall correctly.

**Comment by YuliKl** [comment]
To be honest, that feels like a bug. We usually forget to take compact overlay mode into account, assuming we have more horizontal space to work with in the min case. And while I can hypothesize some rationale of wanting to maintain a bit of whitespace between items and footer, the custom content area feels like a strange column to do this in.

I'm not clear whether removing that minWidth is likely to cause a breaking change for apps. @licanhua, any thoughts on this one?

**Comment by licanhua** [comment]
It's from designer.
For better user experience, it's app's responsibility to make sure that the settings and other button always be in the screen. If you start to see settings button is disappear, that means nav view is going to be in minimal mode(use change the threhold). But because of string localization, it's hard to do that. so 48 is used to district overflow button with the right part. If min width is reached, the right side is pushed off the screen.

**Comment by chingucoding** [comment]
I am not sure if we should remove it entirely, after all this is a niche case. However it's a bit annoying that I would need to retemplate the NavigationView in order to get rid of the 48px gap, which in compact overlay, can be almost a third of the available width when the app is in it's minimum dimensions.

Also in the gif I shared, I used different visual states to hide items when the windows gets narrow to still be able to show a button to exist compact overlay. After all, you have to make sacrifices with such small sizes. Without the enforced gap, the button would still be visible with the narrow size of 150px.

**Comment by YuliKl** [comment]
I would support adding a resource for this with the same 48px default as today.

**Comment by chingucoding** [comment]
Would it be fine if I make this change then @ranjeshj ?

**Comment by ranjeshj** [comment]
That sounds reasonable to avoid re-templating. @chingucoding go for it. Thanks!
