### ISSUE TITLE
WinUI 3.0: Why print functionality of WebView2 not working?

### ISSUE THREAD

**Issue by saf-itpro** [microsoft/microsoft-ui-xaml#2894]
According to this [GitGub post,](https://github.com/MicrosoftEdge/WebViewFeedback/issues/42), we can now use `window.print()` to print webpage in `WebView2`. But the following code is not printing:

In my [WinUI 3.0][1] - UWP project, I have a `WebView2` control that displays a simple html as follows. But when I call the following `javascript` code using [ExecuteScriptAsync][2] (as shown below), I get the following error:

**Error**:
>>Check your printer or select another printer. The printer you chose isn't available or isn't installed correctly.

**Screenshot of Error**:

[![enter image description here][3]][3]

**Remarks**: There is nothing wrong on my Windows 10's default `Print to PDF` printer as I can print the exact same html page from a browser (MS Edge or Google).

**Question**: What I may be doing wrong here, and can we resolve the issue? Note: `wvTest`, as you may have guessed, is the name of WebView2 control.

**Code**:

    //Correctly displays the html page with a simple text: `Test paragraph`
    private async void myButton_Click(object sender, RoutedEventArgs e)
    {
        string sHTML = "<!DOCTYPE html>" +
            "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">" +
            "<head>" +
                "<meta charset=\"utf-8\" />" +
                "<title>Test Title</title>" +
            "</head>" +
            "<body>" +
                "<p>Test paragraph</p>" +
                "<script>function myFunction() {" +
                                "window.print();" +
                    "}</script>" +
            "</body>" +
            "</html>";
        //System.Diagnostics.Debug.WriteLine(sHTML);
        wvTest.NavigateToString(sHTML);
    }

//This event opens the `Print Dialog` with the message shown above:

    private async void btnPrint_Click(object sender, RoutedEventArgs e)
    {
        await wvTest.ExecuteScriptAsync(javascriptCode: "myFunction();");
    }

  [1]: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/
  [2]: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/wpf/0-9-515/microsoft-web-webview2-wpf-webview2#executescriptasync
  [3]: https://i.stack.imgur.com/3G7R2.png

**Comment by codendone** [comment]
This is due to that print dialog not being compatible currently with the UWP AppContainer.  It works fine in a WinUI Desktop project.  At least for UWP, the print request will likely need to be proxied by the WebView2 element out to the WinRT PrintDialog API, but we haven't gotten to that task yet.

**Comment by saf-itpro** [comment]
@codendone Thank you for providing a reason for the issue and hence saving my time for investigating further.

**Comment by codendone** [comment]
Adding a link for my convenience: The work to support this is internally tracked here: [internal link](https://microsoft.visualstudio.com/DefaultCollection/Edge/_workitems/edit/27694507)
