### ISSUE TITLE
Clicking several NavigationViewItems very quickly messes the layout.

### ISSUE THREAD

**Issue by edfullest** [microsoft/microsoft-ui-xaml#2897]
**Describe the bug**
If you click several navigation view items within less than a second, the NavigationView shows the previously selected one as selected, and this stays as such until you close the app.

**Steps to reproduce the bug**
1. Click one navigation view item
2. Click another one very quickly

Repeat 1-2 by clicking different items very quickly.

**Expected behavior**
It shouldn't show that several items are selected (i.e. show just one)

**Screenshots**
![image](https://user-images.githubusercontent.com/11062927/87362651-12047d00-c524-11ea-86af-f79485dd8c60.png)

![ezgif-4-f0e70cfe4268](https://user-images.githubusercontent.com/11062927/87362815-95be6980-c524-11ea-89aa-3511aab14bf4.gif)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |Yes|
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by kmgallahan** [comment]
Fairly sure this bug is related to click-drag rather than speed of clicks. #2860 

It is resolved via https://github.com/microsoft/microsoft-ui-xaml/pull/2625

That patch is available in the latest pre-release build.

**Comment by ranjeshj** [comment]
@edfullest  Several input issues were fixed in #2625. If you see it with latest pre-release build, please feel free to activate this issue back. Thanks!
