### ISSUE TITLE
ItemsRepeater needs to expose Background property

### ISSUE THREAD

**Issue by ranjeshj** [Microsoft/microsoft-ui-xaml#29]
**Describe the bug**
The problem is that ItemsRepeater does not set its background property and does not  expose a background property as well. So none of the events like dragover/drop etc are raised on repeater. We should expose the background property like all other panels do.

**Steps to reproduce the bug**
Try listening to drag/drop events on ItemsRepeater. Note that these do not get raised when interacting within the ItemsRepeater's  bounds. 

**Expected behavior**
ItemsRepeater should expose a background property. Setting that will cause the drag/drop events to be raised similar to existing panels like StackPanel etc.

**Comment by jevansaks** [comment]
This is fine but @micahl @ranjeshj please create a feature request spec template following the template of #21 for overall Repeater discussion. Thanks!
