### ISSUE TITLE
Canvas SizeChanged is not triggered when it is inside another Canvas

### ISSUE THREAD

**Issue by cnbluefire** [microsoft/microsoft-ui-xaml#2900]
**Describe the bug**
When modifying the width and height of the Canvas, If it's **directly** in another Canvas, ActualWidth and ActualHeight will change but SizeChanged is not triggered. 

**Steps to reproduce the bug**
like this: [https://github.com/cnbluefire/CanvasSizeChangedTest](https://github.com/cnbluefire/CanvasSizeChangedTest)

**Expected behavior**
When a control's width and height change, it should trigger SizeChanged

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by michael-hawker** [comment]
I was also noticing that if an element within the Canvas is moved (via `Canvas.Top` or `Canvas.Left`) that element's `LayoutUpdated` event isn't fired. So I don't think there's a way for the element to detect that it's moved either... I think that'd be a separate bug though. @ranjeshj know if that's the expected behavior or not?

**Comment by michael-hawker** [comment]
_Related to #674_
