### ISSUE TITLE
Proposal: Promote Focus related events to UIElement

### ISSUE THREAD

**Issue by kmelmon** [microsoft/microsoft-ui-xaml#2910]
React-native-windows will be exposing a focused() event, as described here:
https://microsoft-my.sharepoint-df.com/:w:/r/personal/harinik_microsoft_com/_layouts/15/guestaccess.aspx?e=vboyhr&wdLOR=c64CA0AED-7A7D-4BDB-A982-CA52A8FB65F4&share=EY4TcWAvR4tKu7EjxUG7OcwBkIHpcehA26atyX4BTwCYLw

We've already promoted most of the focus related APIs to UIElement, which will allow react-native-windows to avoid extra complexity and a performance hit (by avoiding wrapping RN components with an extra ContentControl).  However I don't believe we've promoted the focus related events (OnGotFocus, OnLostFocus) yet.

This proposal is tracking promoting OnGotFocus/OnLostFocus up to UIElement.

**Comment by chingucoding** [comment]
[UIElement](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement?view=winrt-19041#events) already has the following events:

* GotFocus
* GettingFocus
* LosingFocus
* LostFocus

Are those events lacking any features/behaviors that would be needed for a focused event in React native?
What would be the differences between those events and the events you mentioned?

**Comment by kmelmon** [comment]
Good catch!  Looking at the RNW code, we already subscribe to Control.GotFocus/LostFocus for the TextInput control, we can very likely do the same when we promote the event to the basic View component.

It would be nice if we lifted the virtuals too but this isn't required for RNW, closing this for now.
