### ISSUE TITLE
Adding SwipeItems to a SwipeControl from code-behind throws an AccessViolationException

### ISSUE THREAD

**Issue by yoshiask** [microsoft/microsoft-ui-xaml#2911]
**Describe the bug**
I have been trying to add a SwipeControl to a StackPanel from a C# code-behind. Doing everything from XAML works as expected, but doing the exact same in C# always throws an AccessViolationException when attempting to add a new SwipeItem to SwipeControl.LeftItems (or any of the other four directions).

I also tried not setting LeftItems in the 'constructor' (not sure what it's called) and not setting it at all. The former resulted in the same error, and the latter threw a NullReferenceException as expected.

**Steps to reproduce the bug**
```cs
var swipeControl = new SwipeControl()
{
    LeftItems = new SwipeItems()
    {
        Mode = SwipeMode.Execute
    }
};
swipeControl.LeftItems.Add(new SwipeItem() {
    Text = "Dismiss",
    IconSource = new SymbolIconSource()
    {
         Symbol = Symbol.Forward
    }
});
```

**Expected behavior**
WinUI should not throw an AccessViolationException.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.2
Microsoft.UI.Xaml 2.5.0-prerelease.200708003

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This should be a separate issue, but without native or mixed debugging enabled, the real exception is hidden behind a non-descriptive COM exception. The only information that can be extrapolated from that COM exception is which assembly it's coming from (which in this case is Microsoft.UI.Xaml)

**Comment by StephenLPeters** [comment]
@StephenLPeters FYI

**Comment by yoshiask** [comment]
It's been almost two weeks now, is there anything new on this?

**Comment by StephenLPeters** [comment]
This is on my radar but I haven't had the time to investigate it yet. I'm sorry.

**Comment by Felix-Dev** [comment]
@yoshiask Can you use the WinUI `SwipeControl` instead of the OS version? Your posted code works fine - tested on WinUI 2.4.2.

To make the switch easier from the OS `SwipeControl` control, you could use the following `using` statements:
```cs
using SymbolIconSource = Microsoft.UI.Xaml.Controls.SymbolIconSource;
using SwipeControl = Microsoft.UI.Xaml.Controls.SwipeControl;
using SwipeItem = Microsoft.UI.Xaml.Controls.SwipeItem;
using SwipeItems = Microsoft.UI.Xaml.Controls.SwipeItems;
using SwipeMode = Microsoft.UI.Xaml.Controls.SwipeMode;
```

**Comment by StephenLPeters** [comment]
The issues description says the exception is coming from Microsoft.UI.Xaml in the Additional Context section, so I assumed that the Winui versions of the controls are being used.  Perhaps its a winui 2 Swipe with an OS xaml swipeItem?  @yoshiask can you please confrim the repro with what @Felix-Dev suggested?

**Comment by Felix-Dev** [comment]
@StephenLPeters I can confirm the exception reported by @yoshiask using the OS XAML `SwipeControl`. Code works fine using the WinUI version. If you happen to mix WinUI and OS XAML in the code snippet above, the code won't compile. Hence why I think @yoshiask is using the OS code here (would also match the repro code posted).

If they are using the WinUI controls already I will upload my working test app so it can be compared with the failing code.

**Comment by yoshiask** [comment]
I tried it again with the using statements you provided, and it does indeed work as expected. It turns out that I was using the OS `SwipeControl` (and all of the related classes). I'm glad that solves the issue, but why is the exception coming from WinUI?
