### ISSUE TITLE
Announcing WinUI 3 Preview 2! 🎉💻

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#2917]
# WinUI 3 Preview 2 – Stability improvements and bug fixes 

As mentioned in the recent community call, today we are releasing WinUI 3 Preview 2! Preview 2 is a quality-driven release that focuses on fixing critical bugs from Preview 1.  

WinUI is going to be released in a series of previews, and you can expect exciting feature updates and additional stability improvements in Preview 3, which is currently planned for the Fall.  

## Critical Bug Fixes and Improvements

Here are some of the critical fixes and improvements that we're excited to bring you in Preview 2. 

**For an exhaustive list of the bugs fixed, please see our [release notes](https://aka.ms/winui3/preview2#bug-fixes-and-other-improvements-in-winui-3-preview-2).**

- INotifyCollectionChanged and INotifyPropertyChanged are now working as expected in C# Desktop apps, also allowing you to use ObservableCollection as you'd expect to 
- Crash fixes for Input Validation and general Text Box scenarios 
- For Desktop apps, Point, Rect, and Size structs have been changed to Double types in C# 
- Also for C# Desktop apps, local definitions of geometry types on Nullable now work 
- Parity with WinUI 2.4 (bringing you hierarchical NavigationView, ProgressRing, and more).  
- Updated version of .NET 5 for Desktop apps (now targeting .NET 5 Preview 5) 
- Updated version target of Visual Studio Preview – now targeting VS 16.7 Preview 3. 
- Lots of other UI and functionality bug fixes, crash fixes, and increased stability.  

Please keep in mind that Preview 2 is still an early release product, and has a number of [known issues and limitations](https://aka.ms/winui3/preview2#preview-2-limitations-and-known-issues) that our team will be working on throughout upcoming releases. This preview is not intended for production apps.  

## Getting started with Preview 2
First, you'll need to set up your dev environment with the appropriate technologies. See our documentation for installation instructions and more information on project types: 

**[Install WinUI 3 Preview 2](https://aka.ms/winui3/preview2#install-winui-3.0-preview-2)**

Also, take a look at the walk-through documentation on [building a UWP app with WinUI 3 Preview 2](https://aka.ms/winui3/uwpguide) and [building a Desktop app with WinUI 3 Preview 2](https://aka.ms/winui3/desktopguide). 

We love feedback! We encourage you to file any bug, big or small, on our repo using [this template](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=). Knowing which issues and features are important and/or critical to our customers highly influences which ones we tackle.  

For upgrading Preview 1 apps to Preview 2, carefully follow the instructions laid out [here](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/preview_upgrade_instructions.md). 

## What's next
The team's next big milestone will be Preview 3, which is planned for the Fall! After that, we're planning on going open source and releasing production-ready previews before general availability. For more detailed information, see our continuously-updated [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md).

**Comment by ad1Dima** [comment]
> number of known issues and limitations 
link is broken right one is https://aka.ms/winui3/preview2#preview-2-limitations-and-known-issues

**Comment by anawishnoff** [comment]
> > number of known issues and limitations
> > link is broken right one is https://aka.ms/winui3/preview2#preview-2-limitations-and-known-issues

Link should be fixed now, thanks!

**Comment by lhak** [comment]
Not sure if this issue should be reported here, but it is no longer possible to reference a C++ runtime component from a C# (winui desktop) project. Error message is related to the removal of winmd support in .net.

**Comment by ranjeshj** [comment]
> Not sure if this issue should be reported here, but it is no longer possible to reference a C++ runtime component from a C# (winui desktop) project. Error message is related to the removal of winmd support in .net.

@lhak can you open a new issue with details and a repro app  ? Thanks

**Comment by huoyaoyuan** [comment]
> we're planning on going open source

I'm looking forward to seeing xaml compiler and language design to be open-sourced!

**Comment by manuelroemer** [comment]
> 
> 
> > > number of known issues and limitations
> > > link is broken right one is https://aka.ms/winui3/preview2#preview-2-limitations-and-known-issues
> 
> Link should be fixed now, thanks!

Hey, just a quick note: The other links in the issue are also broken (for me, at least). They all start with "https://github.com/microsoft/microsoft-ui-xaml/issues". Removing that part makes them work.

**Comment by anawishnoff** [comment]
@manuelroemer Thanks! Let me fix that up.

**Comment by tim-weis** [comment]
I just tried to update a project from Preview 1 to Preview 2 (*Blank App, Packaged (WinUI in Desktop)* using C++/WinRT). The *WinUI 3 Project Templates* VSIX auto-updated to Preview 2 previously, but the project's *Manage NuGet Packages...* UI wouldn't offer me to update.

I manually updated all references in the *packages.config* as well as the *.vcxproj* file, and upon relaunching the NuGet UI was offered to install the missing dependencies.

While this all worked out I need to double-check, whether there was no provision to provide an automated upgrade path (which would be totally fine, this being a preview), or something didn't work out as intended, and I should file an issue. If it is the former, it would help to have the steps required to manually upgrade a project documented under [Windows UI Library 3 Preview 2 (July 2020)](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/).

**Comment by ranjeshj** [comment]
You can upgrade from preview1 to preview2 but it is a bit more involved since there are project system updates. So it will likely be easier to create a new project and copy files over. The instructions to upgrade can be found [here](https://github.com/microsoft/microsoft-ui-xaml/blob/24cec5c464eafc58fc2f96d34af38101ce23dc2a/docs/preview_upgrade_instructions.md).

**Comment by tim-weis** [comment]
@ranjeshj Thanks a lot for the link to the detailed upgrade instructions. They were written with a lot of care, and helped me every step of the way.

Except for step 4: For me, the option *"WinUI.Dependencies"* is not available. The dropdown lists these options:

* All
* nuget.org
* Microsoft Visual Studio Offline Packages

None of the options allowed me to upgrade through the NuGet UI. Is this supposed to work with *Blank App, Packaged (WinUI in Desktop)* for C++?

**Comment by michael-hawker** [comment]
Should Tabbing out of a TextBox be working? (WinUI 3 Desktop project on Preview 2)

**Comment by ranjeshj** [comment]
> @ranjeshj Thanks a lot for the link to the detailed upgrade instructions. They were written with a lot of care, and helped me every step of the way.
> 
> Except for step 4: For me, the option _"WinUI.Dependencies"_ is not available. The dropdown lists these options:
> 
> * All
> * nuget.org
> * Microsoft Visual Studio Offline Packages
> 
> None of the options allowed me to upgrade through the NuGet UI. Is this supposed to work with _Blank App, Packaged (WinUI in Desktop)_ for C++?

@alwu-msft @stevenbrix  FYI

**Comment by ranjeshj** [comment]
> I was playing with the ComboBox and was confused by its behavior when setting a `SelectedItem`. WinUI 3 should be using the latest SDK behavior in all cases and not the old behavior ([see docs](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/combo-box#selected-item-behavior-change))?
> 
> Also, this may be a new general issue, but if I just have a ListView and items contain textboxes, hitting tab doesn't do anything, is that expected?

@michael-hawker can you file a new issue ?

**Comment by anawishnoff** [comment]
@ranjeshj @tim-weis 

The link to the instructions that Ranjesh posted are from the original branch, but they have since been updated. The WinUI.Dependencies option was an internal-only step that was included by mistake.

Please reference the instructions here: https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/preview_upgrade_instructions.md.

I'll also update this issue with the instructions link. Thanks!

**Comment by r2d2Proton** [comment]
Is the goal to support non-WinRT applications with WinUI 3?
I was following the instructions on installing WinUI 3 Preview 2 but stopped because of a note on the VSIX page:

C# and C++/WinRT are the only languages supported at this time
https://marketplace.visualstudio.com/items?itemName=Microsoft-WinUI.WinUIProjectTemplates

**Comment by ranjeshj** [comment]
@r2d2Proton There have been proposals/requests for [Rust ](https://github.com/microsoft/microsoft-ui-xaml/issues/2488)and [F#](https://github.com/microsoft/microsoft-ui-xaml/issues/740), but C# and C++/WinRT are the only ones the team is currently working on supporting.

**Comment by r2d2Proton** [comment]
@ranjeshj Thank you for the response ranjeshj. I am actively developing a C++ Windows SDK application. Currently I am using WC_TREEVIEW and other resources (.rc), for example, EDITTEXT, PUSHBUTTON, etc. for the user interface. No WinRT.
Will WinUI 3 work in this environment?

**Comment by ranjeshj** [comment]
@marb2000 @Austin-Lamb can you answer the hosting question ?

**Comment by MarcoEnxuto** [comment]
@anawishnoff Quick question. Since this is a preview, are you expecting to support minimum 15063 at a later date?

**Comment by michael-hawker** [comment]
@MarcoEnxuto is there a specific reason you need 15063? 14393 is the older LTSC in support after November. Then it's 1809 (17763).

**Comment by MarcoEnxuto** [comment]
> @MarcoEnxuto is there a specific reason you need 15063? 14393 is the older LTSC in support after November. Then it's 1809 (17763).

Hi @michael-hawker, i would like to keep supporting Mobile. Are you expecting to support ARM32?

**Comment by jindal1979** [comment]
Can we publish apps to Microsoft Store using WINUI 3 Preview 2 ? I know that it is not production ready, but still I would like to publish the app to Microsoft Store for limited use within organization. Will Microsoft Store all the app to be published (WINUI 3 Preview 2) ?

**Comment by anawishnoff** [comment]
Hi @jindal1979, I don't believe that you can publish apps to the Microsoft Store that are using WinUI 3 Preview 2, because as you said it's not yet production app ready.

**Comment by ranjeshj** [comment]
@jindal1979 Ana is correct. WinUI3 Preview2 is not production ready. An app built on WinUI3 Preview2 can get broken by an update to the OS currently, so this is not recommended or supported got production apps.

**Comment by huoyaoyuan** [comment]
It's time for Preview 3. With the release of VS16.8, currently there are no version of VS can work with WinUI desktop.

**Comment by chingucoding** [comment]
@huoyaoyuan You might want to check out next weeks App Delopment Community Standup in which they will talk about WinUI 3 Preview 3! Link: https://www.youtube.com/watch?v=aerGF9kqMJY&feature=youtu.be

**Comment by Fabi** [comment]
> It's time for Preview 3. With the release of VS16.8, currently there are no version of VS can work with WinUI desktop.

In addition to that it got support for Preview as stated in the release post. Still waiting for it tho...

**Comment by amocsy-cc** [comment]
> 
> 
> It's time for Preview 3. With the release of VS16.8, currently there are no version of VS can work with WinUI desktop.

WinUI 3 Preview 2 also seems to [depend on .net 5 preview 5](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-2). Since .net 5 is released, we need a new WinUI 3 preview for stable .net 5 as well.

**Comment by gabbybilka** [comment]
Check out #6172 to see bug fixes from this release in Windows App SDK 1.0.
