### ISSUE TITLE
Question: The "XamlResourceMapName" parameter is not supported by the "CompileXaml" task in CMake builds?

### ISSUE THREAD

**Issue by smk2007** [microsoft/microsoft-ui-xaml#2925]
I have been trying to generate projects that pull and register WinUI 3's NuGet package using in cmake to create a user controls component dll.

However, I get to point where msbuild complains with:
packages\Microsoft.WinUI.3.0.0-preview1.200515.3\build\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(433,17): error MSB4064: The "XamlResourceMapName" parameter is not supported by the "CompileXaml" task. Verify the parameter exists on the task, and it is a settable public instance property.

I have ensured that the compiler being used is infact the dll being shipped in the Microsoft.* winui package.

Does anyone know what this error could be caused by? Thanks!

Details:

I create a standard shared library in cmake using:
```
add_library(target SHARED
  ${CMAKE_SOURCE_DIR}/../src/game/ui/test.idl
  ${CMAKE_SOURCE_DIR}/../src/game/ui/test.xaml
  ${CMAKE_SOURCE_DIR}/../src/game/ui/test.xaml.cpp
  ${CMAKE_SOURCE_DIR}/../src/game/ui/test.xaml.h
)
```

The xaml and idl files for the test component are generated by the WinUI 3 User Control template.

I configure the project with the following properties:
```
set_target_properties(target PROPERTIES VS_USER_PROPS ${CMAKE_SOURCE_DIR}/packages.props)
set_target_properties(target PROPERTIES VS_GLOBAL_CppWinRTOptimized true)
set_target_properties(target PROPERTIES VS_GLOBAL_CppWinRTRootNamespaceAutoMerge true)
set_target_properties(target PROPERTIES VS_GLOBAL_RootNamespace target)
set_target_properties(target PROPERTIES VS_GLOBAL_MinimalCoreWin true)
set_target_properties(target PROPERTIES VS_GLOBAL_DefaultLanguage en-US)
set_target_properties(target PROPERTIES VS_GLOBAL_AppContainerApplication false)
set_target_properties(target PROPERTIES VS_GLOBAL_AppxPackage false)
set_target_properties(target PROPERTIES VS_GLOBAL_ApplicationType "Windows Store")
set_target_properties(target PROPERTIES VS_GLOBAL_ApplicationTypeRevision 10.0)
set_target_properties(target PROPERTIES VS_GLOBAL_WindowsTargetPlatformVersion 10.0)
set_target_properties(target PROPERTIES VS_GLOBAL_IsWinUIAlpha true)
set_target_properties(target PROPERTIES VS_GLOBAL_WindowsKitsPath WinUI-Alpha-Projects-Don-t-Use-SDK-Xaml-Tools)
set_target_properties(target PROPERTIES VS_GLOBAL_ForceImportAfterCppTargets ${CMAKE_SOURCE_DIR}/packages.targets)
```

In the custom props i add the NuGet props imports manually and a reference to the packages.config:
```
<Project>
  <ImportGroup Label="PropertySheets">
    <Import Project="$(MSBuildProjectDirectory)\..\build\packages\Microsoft.Windows.CppWinRT.2.0.200316.3\build\native\Microsoft.Windows.CppWinRT.props"
            Condition="exists('$(MSBuildProjectDirectory)\..\build\packages\Microsoft.Windows.CppWinRT.2.0.200316.3\build\native\Microsoft.Windows.CppWinRT.props')" />
  <Import Project="$(MSBuildProjectDirectory)\..\build\packages\Microsoft.WinUI.3.0.0-preview1.200515.3\build\native\Microsoft.WinUI.props"
            Condition="exists('$(MSBuildProjectDirectory)\..\build\packages\Microsoft.WinUI.3.0.0-preview1.200515.3\build\native\Microsoft.WinUI.props')" />
  </ImportGroup>

  <ItemGroup>
      <None Include="packages.config" />
  </ItemGroup>  
</Project>
```

In the targets i import the targets:
```
<Project>
  <ItemDefinitionGroup>
      <Midl>
		  <!-- Output directory needs to be cleared for cppwinrt generated files -->
          <OutputDirectory></OutputDirectory>
      </Midl>
  </ItemDefinitionGroup>
	
  <ImportGroup Label="ExtensionTargets">
    <Import Project="$(MSBuildProjectDirectory)\..\build\packages\Microsoft.Windows.CppWinRT.2.0.200316.3\build\native\Microsoft.Windows.CppWinRT.targets"
            Condition="exists('$(MSBuildProjectDirectory)\..\build\packages\Microsoft.Windows.CppWinRT.2.0.200316.3\build\native\Microsoft.Windows.CppWinRT.targets')" />
    <Import Project="$(MSBuildProjectDirectory)\..\build\packages\Microsoft.WinUI.3.0.0-preview1.200515.3\build\native\Microsoft.WinUI.targets"
            Condition="exists('$(MSBuildProjectDirectory)\..\build\packages\Microsoft.WinUI.3.0.0-preview1.200515.3\build\native\Microsoft.WinUI.targets')" />
    <Import Project="$(MSBuildProjectDirectory)\..\build\packages\Microsoft.VCRTForwarders.140.1.0.6\build\native\Microsoft.VCRTForwarders.140.targets"
            Condition="Exists('$(MSBuildProjectDirectory)\..\build\packages\Microsoft.VCRTForwarders.140.1.0.6\build\native\Microsoft.VCRTForwarders.140.targets')" />   
  </ImportGroup>
</Project>
```

**Comment by StephenLPeters** [comment]
@stevenbrix @alwu-msft FYI

**Comment by StephenLPeters** [comment]
@smk2007 [preview2](aka.ms/winui3/preview2) is available now, could you see if the issue still reproduces with the update?

**Comment by smk2007** [comment]
I updated to preview2, and use the following cmake project configuration.

I added UseXamlCompilerExecutable = true, and am able to make more progress. but the build now fails during:

Target MarkupCompilePass2:
2>  packages\Microsoft.WinUI.3.0.0-preview2.200713.0\build\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(662,13): error MSB3073: The command ""packages\Microsoft.WinUI.3.0.0-preview2.200713.0\build\..\tools\XamlCompiler.exe" "Generated Files\\input.json" "Generated Files\\output.json"" exited with code 1.

I ran the command directly and get the same result with no additional error information :(
```
add_library(target SHARED
  ${CMAKE_SOURCE_DIR}/../src/game/ui/start.idl
  ${CMAKE_SOURCE_DIR}/../src/game/ui/start.xaml
  ${CMAKE_SOURCE_DIR}/../src/game/ui/start.xaml.cpp
  ${CMAKE_SOURCE_DIR}/../src/game/ui/start.xaml.h
)

target_include_directories(target PRIVATE ${CMAKE_SOURCE_DIR}/../src/game/ui)
target_include_directories(target PRIVATE ${CMAKE_SOURCE_DIR}/../src/engine/public_inc)

target_compile_features(target PRIVATE cxx_std_17)
target_compile_definitions(target PRIVATE UNICODE)
target_compile_definitions(target PRIVATE _UNICODE)

set_target_properties(target PROPERTIES VS_USER_PROPS ${CMAKE_SOURCE_DIR}/packages.props)

set_target_properties(target PROPERTIES VS_GLOBAL_CppWinRTOptimized true)
set_target_properties(target PROPERTIES VS_GLOBAL_CppWinRTRootNamespaceAutoMerge true)
set_target_properties(target PROPERTIES VS_GLOBAL_RootNamespace target)
set_target_properties(target PROPERTIES VS_GLOBAL_MinimalCoreWin true)
set_target_properties(target PROPERTIES VS_GLOBAL_DefaultLanguage en-US)
set_target_properties(target PROPERTIES VS_GLOBAL_AppContainerApplication false)
set_target_properties(target PROPERTIES VS_GLOBAL_AppxPackage false)
set_target_properties(target PROPERTIES VS_GLOBAL_ApplicationType "Windows Store")
set_target_properties(target PROPERTIES VS_GLOBAL_ApplicationTypeRevision 10.0)
set_target_properties(target PROPERTIES VS_GLOBAL_WindowsTargetPlatformVersion 10.0)
set_target_properties(target PROPERTIES VS_GLOBAL_IsWinUIAlpha true)
set_target_properties(target PROPERTIES VS_GLOBAL_WindowsKitsPath WinUI-Alpha-Projects-Don-t-Use-SDK-Xaml-Tools)
set_target_properties(target PROPERTIES VS_GLOBAL_ForceImportAfterCppTargets ${CMAKE_SOURCE_DIR}/packages.targets)
set_target_properties(target PROPERTIES VS_GLOBAL_UseXamlCompilerExecutable true)
```

**Comment by smk2007** [comment]
I was able to get it building by removing the explicit setting of the applicationtyperevision and windowstargetplatformversion:
set_target_properties(goa_ui PROPERTIES VS_GLOBAL_ApplicationTypeRevision 10.0)
set_target_properties(goa_ui PROPERTIES VS_GLOBAL_WindowsTargetPlatformVersion 10.0)

**Comment by stevenbrix** [comment]
@RealTommyKlein for the xaml compiler exe issue

@smk2007 I'm glad to hear you got it figured it out - sorry for not being of much help, I'm not as familiar with cmake as I'd like to be. Do you know what removing those properties did?

**Comment by smk2007** [comment]
Hmm, I think cmake competes with the setting of these properties and that mismatch can possibly lead to the errors i was seeing.

**Comment by StephenLPeters** [comment]
@smk2007 Can you share what the solution was? :)

**Comment by RealTommyKlein** [comment]
I don't have too much experience with CMake/MSBuild together, but for the `XamlResourceMapName` error I suspect an old Windows.UI.Xaml Xaml compiler that ships with Visual Studio is getting used instead of the WinUI 3 Xaml compiler, although I'd have to do some digging into what properties weren't set that would cause that to happen.

As far as the executable Xaml compiler goes, we should be logging errors back up to the MSBuild process that invoked the executable compiler, but perhaps something is going wrong when it's invoked using CMake+MSBuild.  For this scenario though, you should not need to use the executable Xaml compiler and can leave `UseXamlCompilerExecutable` as `false`.
