### ISSUE TITLE
Cannot get App to run with .Net5 preview 5 and WinUI3 preview 2

### ISSUE THREAD

**Issue by Wigmund** [microsoft/microsoft-ui-xaml#2928]
Building a C# WinUI desktop app (previously working on winui3 preview 1), didn't do the upgrade process, but instead removed the winui projects (Desktop, Packaged), recreated and copied in my assets. Recompiled successfully, but when I run it gets as far as starting the diagnostic tools, but then stops (before running anything) without error.

I'm also seeing a "WMC999 Type universe cannot resolve assembly: WinRT.Runtime, Version=0.1.0.215..." on all my .xaml files which I don't think was there before.

The project also links to the Microsoft.Toolkit.Uwp.Controls (8.00-preview2) if that has any bearing.

Any ideas?

**Comment by ranjeshj** [comment]
@Wigmund  can you share a repro app ?

**Comment by Wigmund** [comment]
Sorry, my bad, I was running the startup project as the project without the (Package) suffix - still not quite sure why there's a need for two separate projects? It seems to be running now, but I still have the "universe cannot resolve" warnings.

**Comment by StephenLPeters** [comment]
@Wigmund can you provide a repro project so we can look at the warnings as well?

**Comment by StephenLPeters** [comment]
@alwu-msft and @stevenbrix fyi

**Comment by Wigmund** [comment]
Sadly no repro, sensitive data, but will try and recreate if I can find the time!
