### ISSUE TITLE
ProgressBar: Paused and Error Transitions take too long

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#2930]
**Describe the bug**
Transitions between Indeterminate state to both Paused and Error states, takes too long.

**Steps to reproduce the bug**
1. Using the XAML Controls Gallery;
2. Go to **Status and Info**;
3. Choose **ProgressBar**;
4. Choose either **Paused** or **Error** in the _Progress state_ selections;
5. Observe the almost 5 secs it takes for the control to transition into it's new state.

**Expected behavior**
The playing animation should slow to a stop with easing, and the colour should change to the correct brush.  Rather than waiting for the current cycle to complete, a short pause, and the bar animating to the centre and stopping with a colour fade.

**Screenshots**
It is about motion, so screenshots will not help

**Version Info**
WinUI 2.X
XAML Controls Gallery version **1.2.16.0**

NuGet package version: 
[2.5.0-prerelease.200708003]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |

**Additional context**

**Comment by StephenLPeters** [comment]
Looking at this myself there seems to be another issue where, depending on when you switch to paused, the progressbar show two indicators at once between the states.

**Comment by StephenLPeters** [comment]
@MarissaMatt FYI

**Comment by MarissaMatt** [comment]
@StephenLPeters were you looking at the XAML controls gallery example or was this in a sample app or other application?

**Comment by StephenLPeters** [comment]
xaml controls gallery

**Comment by MarissaMatt** [comment]
@mdtauk I am working with design to figure out the best solution for this issue but I just wanted to let you know I am looking in to this!
