### ISSUE TITLE
Question: [Project update to preview 2]

### ISSUE THREAD

**Issue by Artain** [microsoft/microsoft-ui-xaml#2935]
In the Readme for project updates from preview 1 to preview 2 it mentions under no.4 to select the WinUi.dependencies as the package source. Maybe I'm overlooking something but I don't know where to get these winui.dependencies. Can someone please help me.

**Comment by willynt** [comment]
+1

**Comment by marcomas2000** [comment]
+1

**Comment by StephenLPeters** [comment]
@anawishnoff is there a missing step in the read me? @aclwu-msft @MikeHillberg @JesseCol FYI

**Comment by anawishnoff** [comment]
@alwu-msft Any ideas?

**Comment by alwu-msft** [comment]
That was an internal-only step (@anawishnoff we should update the doc to remove it). As long as you have the Nuget.org package feed enabled, you should be fine. However, you will likely need to update the version number manually as the package is still unlisted: the latest version is **3.0.0-preview2.200713.0**.

**Comment by anawishnoff** [comment]
Thanks! I'll go ahead and remove that line.

**Comment by mqudsi** [comment]
Can someone please update https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/preview_upgrade_instructions.md to include the tidbit about needing to manually run `install-package Microsoft.WinUI -Version 3.0.0-preview2.200713.0`?

**Comment by StephenLPeters** [comment]
@anawishnoff has this been addressed?

> Can someone please update https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/preview_upgrade_instructions.md to include the tidbit about needing to manually run `install-package Microsoft.WinUI -Version 3.0.0-preview2.200713.0`?

**Comment by anawishnoff** [comment]
@StephenLPeters 
Sorry for the late reply, but yes that's been added. Thanks @mqudsi for pointing it out. I believe this issue can now be closed.
