### ISSUE TITLE
Catalan Windows 10 datepicker uses wrong form for months

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#2937]
copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/27297270)

![Untitled](https://user-images.githubusercontent.com/7758786/87735313-087c4e80-c78a-11ea-9e2f-ee1b332def4e.png)
 
"In this context, correct/good forms are ones *without* "de" proposition: gen., febr., marc, abr., maig, juby, jul., ag., set. oct. nov.,and dec."

**Comment by YuliKl** [comment]
Closing because this issue will be handled by localization team.

**Comment by StephenLPeters** [comment]
Turns out this is a bug in CalendarView's code behind
