### ISSUE TITLE
Why the WinUI 3.0 desktop default project giving this runtime error?

### ISSUE THREAD

**Issue by saf-itpro** [microsoft/microsoft-ui-xaml#2939]
Using [Windows UI Library 3 Preview 2 (July 2020)][1] that was released just yesterday. On latest version of `VS2019 - Preview`, followed this official tutorial [Get started with WinUI 3 for desktop apps][2] to create a desktop project. Project successfully compiles but gives the following error when running in debug mode. I'm using `Windows10 Pro ver. 1903`:

    System.MissingMethodException
      HResult=0x80131513
      Message=Method not found: 'Void System.Runtime.InteropServices.ComWrappers.RegisterForTrackerSupport(System.Runtime.InteropServices.ComWrappers)'.
      Source=WinRT.Runtime
      StackTrace:
       at WinRT.ComWrappersSupport.set_ComWrappers(ComWrappers value)
       at WinRT.ComWrappersSupport.InitializeComWrappers(ComWrappers wrappers)
       at WinUI_DesptopPreview2.Program.Main(String[] args) in C:\DotNET5VS2019\Desktop_WinUI\WinUI_DesptopPreview2\WinUI_DesptopPreview2\obj\x64\Debug\net5.0\win-x64\App.g.i.cs:line 25

**Screenshot of the error**:

[![enter image description here][3]][3]

  [1]: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/
  [2]: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop
  [3]: https://i.stack.imgur.com/pc9lG.png

**Comment by StephenLPeters** [comment]
This usually indicates something has gone wrong with the project setup.  @alwu-msft or @MikeHillberg might have more specific instuctions.

**Comment by StephenLPeters** [comment]
@saf-itpro have you installed both the x86 and the x64 versions of .net 5

**Comment by saf-itpro** [comment]
@StephenLPeters  Yes. Per `step 3` of [Install WinUI 3 Preview 2](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-2), I did install  both the x86 and the x64 versions of .NET 5 Preview 5 SDK.

**Comment by VijayanRamachandran** [comment]
Hi,

FYI....
I also faced the same problem. ( Even after installation of x86 and x64 version of .Net5 Preview 5 ).
I think there is some problem with .Net Preview 5 SDKs.

I switched back to dotnet-sdk-5.0.100-preview.**4.20268.1**-win-x64 and dotnet-sdk-5.0.100-preview.**4.20268.1**-win-x86.exe and now i am not getting the above specified runtime error.

PS: Just a hint from my end.

Regards,
Vijayan R

**Comment by Scottj1s** [comment]
The latest version of C#/WinRT calls RegisterForTrackerSupport, which requires  .NET 5 Preview 5.  This error indicates that an older .NET SDK is in use, even if Preview 5 is installed.  The global.json should be checked, and/or "dotnet --version" run to confirm.

**Comment by krschau** [comment]
Closing, as the newer .NET version should not have this error. Let me know if the problem comes up again and I can reopen the issue.
