### ISSUE TITLE
NuGet package does not support win32 projects

### ISSUE THREAD

**Issue by Scottj1s** [Microsoft/microsoft-ui-xaml#294]
The build\native\Microsoft.UI.Xaml.targets contains this ItemGroup condition:
  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'UAP'">

This prevents application of the winmd reference to win32 projects.  The condition can be removed.

**Comment by Scottj1s** [comment]
Repro project:
\UWPCompositionDemos\HelloVectors\HelloVectors_win32_cpp\HelloVectors_win32_cpp.vcxproj 
https://github.com/clarkezone/UWPCompositionDemos/tree/vectors

**Comment by DHowett-MSFT** [comment]
Oh, it looks like I accidentally filed a duplicate as #494. Sorry.

**Comment by Scottj1s** [comment]
no worries - might help to get it fixed
