### ISSUE TITLE
NavigationViewItem selection indicator doesn't display the first time visibility changed

### ISSUE THREAD

**Issue by Psykobal** [microsoft/microsoft-ui-xaml#2941]
**Describe the bug**
I have some `NavigationViewItem` `Collapsed` at launch. After some action, the visibility changed to `Visible` and I select it in code behind as `SelectedItem`. The first time the selected indicator doesn't appear. If you select another one or repeat the scenario (`Collapsed` -> `Visible` -> `SelectedItem`), it works.

**Steps to reproduce the bug**
Demo project: https://github.com/Psykobal/NavView_Indicator
-Launch the app
-Tap on NavigationViewItem "Switch User" and "Sign Out" to display or hide main NavigationViewItem

**Expected behavior**
Selection indicator is displayed everytime on NavigationView SelectedItem

**Screenshots**
-Initial state :
![Initial_state](https://user-images.githubusercontent.com/15339175/87772745-707e7380-c822-11ea-9890-8530e53d45ef.png)
-Tap on "Switch user":
![No_indicator](https://user-images.githubusercontent.com/15339175/87772861-93a92300-c822-11ea-95f7-bc97ddd1d304.png)
-Tap on "Signout":
![Initial_state](https://user-images.githubusercontent.com/15339175/87772745-707e7380-c822-11ea-9890-8530e53d45ef.png)
-Tap again on "Switch user":
![Second_time](https://user-images.githubusercontent.com/15339175/87772933-ae7b9780-c822-11ea-80c6-4fba7f605d25.png)

**Version Info**
NuGet package version: 

[Microsoft.UI.Xaml 2.4.0]
[Microsoft.UI.Xaml 2.4.2]
[Microsoft.UI.Xaml.2.5.0-prerelease.200708003]

It was working on [Microsoft.UI.Xaml.2.3.200213001]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |  Yes    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by chingucoding** [comment]
It seems that the selection indicator does not get animated correctly since the template for the collapsed NavigationViewItem has not loaded yet, when you change selection. As a workaround, you can add `NavView.UpdateLayout()` before setting the selected item.
