### ISSUE TITLE
WinUI3: Old removed SwapChainPanel renders on top of new SwapChain

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#2942]
**Describe the bug**
When tearing down a SwapChainPanel and later creating a new one, the old swapchain panel is left as an artifact on top of the new one.
![swapchain_left_behind](https://user-images.githubusercontent.com/1378165/87809948-10cb9c80-c811-11ea-8489-58e258b59a7f.gif)
Also when the swapchain gets removed, it leaves a small sliver of artifact along the left side.

**Steps to reproduce the bug**
1. Open up the attached solution. This consists of two projects: A native control library that renders a SwapChainPanel, and a .NET App that consumes that control
[MyNativeControlLib.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4938997/MyNativeControlLib.zip)
2. Run the C# application
3. Click the "Create New Box" button, and observe the spinning cube rendering. When resizing the window the control stays centered.
4. Click the "Remove Box" button and observe the control is now gone, except for a sliver along the left side.
5. Click "Create New Box", and see the box now shows again, but is not spinning. This is in fact the "old" box that's rendered.
6. Resize the window, and you'll see the new spinning cube peaks out from under the old swapchain.

**Expected behavior**
No sliver rendered on remove, and new swapchain will show not behind an artifact of the old one.

**Screenshots**
See GIF above

**Version Info**

NuGet package version: 
Microsoft.WinUI.3.0.0-preview2.200713.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by dotMorten** [comment]
If you repeat the steps a few times, the problem gets worse and worse, and you'll even see the left over artifacts briefly outside the window.
![Untitled Project](https://user-images.githubusercontent.com/1378165/87818610-aff79080-c81f-11ea-8915-a4060ffbf6b9.gif)

**Comment by StephenLPeters** [comment]
@RBrid fyi

**Comment by codendone** [comment]
In debugging, the number of SpriteVisuals remains unchanged, but the reference count of the system Comp device, which gets the swapchain on screen. Looks like a leak in that mechanism.

**Comment by dotMorten** [comment]
It's much better in Preview 3, but I'm still seeing this.
The first two times I added a swapchain it was ok. 3rd time I saw a "flash" of the old swapchain right at first, and now when I resize fast, I again see remnants of the removed view:
![winuibug](https://user-images.githubusercontent.com/1378165/99348517-a2462c00-284e-11eb-930a-30df1c09326c.gif)

**Comment by dotMorten** [comment]
Update: While the original scenario is much better, revisiting in a larger sample application, this keeps happening on and off, and I don't believe this issue is fixed. Opening one page with a swapchain, then switching to a new page with a different swapchain, the new swapchain more often than not will render below the first one.

**Comment by dotMorten** [comment]
Here's an updated reproducer using page navigation instead:
[MyNativeControlLib.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5706887/MyNativeControlLib.zip)

![swp_issue](https://user-images.githubusercontent.com/1378165/102442229-c6756400-3fd8-11eb-80e3-918cc6e8a39e.gif)

It appears on page-back navigation the old one stays around, but in this case resize generally resolves the issue (resize isn't enough in my other reproducer but I believe this is still showing the crux of the problem).

**Comment by dotMorten** [comment]
Here's a more realistic end-to-end app that reproduces the problem:
Clone the `winui` branch of `https://github.com/Esri/arcgis-runtime-samples-dotnet`

Open and run the `src/WinUI/ArcGISRuntime.WinUI.Viewer.sln` solution (https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/winui/src/WinUI/ArcGISRuntime.WinUI.Viewer.sln)
When running it, switch between the various samples, and notice that when you run the second or following samples, the preview view will show. Flip back and forth in the tab control in the upper right to get the view to update and show the new view.

**Comment by anawishnoff** [comment]
This bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!

**Comment by dotMorten** [comment]
Awesome! Thank you! This was my #.1 issue.

**Comment by dotMorten** [comment]
Just confirming this is working great for me as well
