### ISSUE TITLE
C++ Xaml Islands application attached to debugger crashes on right-clicking a Textbox

### ISSUE THREAD

**Issue by arjunbalgovind** [microsoft/microsoft-ui-xaml#2944]
**Describe the bug**

If you set up a C++ Xaml Island project with a TextBox, and you right-click in the TextBox the application crashes. This seems to happen only if you run it from the VS debugger, and not if you run the executable independently. I was able to repro this on the [C++ Xaml Island Sample](https://github.com/microsoft/Xaml-Islands-Samples/blob/611a1437728d2087791b081a5de11bc33c1845c5/Standalone_Samples/CppWinRT_Basic_Win32App/Win32DesktopApp/HelloWindowsDesktop.cpp). I have not verified if it can be reproduced on the latest version of those samples since there seems to be a lot of refactoring on that code base.

**Steps to reproduce the bug**

Modify the [xaml island sample](https://github.com/microsoft/Xaml-Islands-Samples/blob/611a1437728d2087791b081a5de11bc33c1845c5/Standalone_Samples/CppWinRT_Basic_Win32App/Win32DesktopApp/HelloWindowsDesktop.cpp) to include a TextBox. No specific properties need to be set. Run the app from the VS debugger.
1. Right-click inside the TextBox

Application crashes in VS. This is displayed in the VS output window:
`Exception thrown at 0x00007FF9BC73A799 (KernelBase.dll) in Win32DesktopApp.exe: WinRT originate error - 0x80040111 : 'Windows.UI.Xaml.Controls.Primitives.CommandBarFlyoutCommandBarTemplateSettings'.
onecore\com\combase\objact\dllcache.cxx(4713)\combase.dll!00007FF9BD95964E: (caller: 00007FF9BD861D1D) ReturnHr(1) tid(4860) 80040111 ClassFactory cannot supply requested class
Exception thrown at 0x00007FF9BC73A799 in Win32DesktopApp.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0000000A4213D9D0.`

**Expected behavior**

Context-menu with the option to Paste should appear

**Screenshots**

![xamlIslandBug](https://user-images.githubusercontent.com/32061677/87827698-42a02b80-c830-11ea-8e8a-215a6edea44d.gif)

**Version Info**

Cpp WinRT version: 2.0.200703.9

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

The crash only happens if the app is run from the VS debugger. If the .exe is launched independently the context menu appears as expected.

**Comment by StephenLPeters** [comment]
@ocalvo FYI issue is in the island sample

**Comment by chrisglein** [comment]
The sample in question has actually been removed: https://github.com/microsoft/Xaml-Islands-Samples/blob/master/Standalone_Samples/CppWinRT_Basic_Win32App/Win32DesktopApp/HelloWindowsDesktop.cpp
