### ISSUE TITLE
Access violation while scrolling in DataGrid

### ISSUE THREAD

**Issue by TroelsL** [microsoft/microsoft-ui-xaml#2946]
**Describe the bug**
In trying to create a new WinUI 3 preview 2 app and including the ToolKit DataGrid, it throws exceptions when scrolling.

MouseWheel scroll and get:

Exception thrown at 0x76FB0C00 (KernelBase.dll) in Vetivity.exe: 0xC0000005: Access violation reading location 0xFFFFFFFF.

I've also seen an System.ExecutionEngineException, but I am unable to reproduce that currently.

**Steps to reproduce the bug**

1. Open and run attached sample
2. Click on Customers in the Navigation Menu
3. Scroll the DataGrid using mouse wheel (down to the end, then up). Or using the scrollbar.

**Expected behavior**
DataGrid would scroll to the desired position, or a more useful exception message if the code is incorrect.

**Screenshots/Attachments**

[DataGridMRE.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4940699/DataGridMRE.zip)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@RBrid and @XAMLLlama FYI

**Comment by eleanorleffler** [comment]
We are getting the same crash (mentioned in the comments of our issue #2703). Our sample code is using Preview 1, but we have also upgraded to Preview 2 and saw no differences.

**Comment by RBrid** [comment]
Thanks for the bug report. 
@StephenLPeters, I repro'd and this turned out to be a known issue in Preview 2: see internal task 26322572.

**Comment by akanieski** [comment]
Also seeing this issue in Preview 3. Any update?

**Comment by alwu-msft** [comment]
Thanks for the report! The fix for this will be included in the next WinUI 3 Preview.
