### ISSUE TITLE
Proposal: Prevent ScrollViewer from responding to mouse scroll events without affecting touch

### ISSUE THREAD

**Issue by WilliamABradley** [microsoft/microsoft-ui-xaml#2947]
# Proposal: Prevent ScrollViewer from responding to mouse scroll events without affecting touch

## Summary

This would provide native support to disable mouse scroll in ScrollViewers. This is helpful in situations where you want to show horizontal scrollable content in a child horizontal ScrollViewer, on a vertically scrollable page, while maintaining vertical scroll and inertia, to not interrupt the page.

I managed to achieve this for the MarkdownTextBlock in Windows Community Toolkit: https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/2093, for a Markdown Code Block, using reflection to pass a child's PointerWheelChanged Event back to a parent's scrollviewer, which was needed to maintain scrolling inertia. This replicates the GitHub Web Experience with Code Blocks.

It would be nice to be able to configure this without having to use reflection.

## Rationale

* This is important in document-like situations, where you still want to have users be scrolling downward, but with the ability to provide horizontal scrollable content.
* Perhaps an alternate solution for this problem would be that you can horizontal scroll with the mouse, as long as you have no vertical inertia.
* You can disable Horizontal Scroll, but it has the undesirable effect of affecting Touch Scrolling, this should allow Developers to tweak the Mouse Scroll Experience, without affecting Touch.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to disable mouse scroll, but maintain touch scroll in a ScrollViewer. | Must |
| This proposal will allow developers to allow horizontal mouse scroll in a child ScrollViewer, if there is no vertical inertia. | Could |

## Important Notes

- Similar situation, but not handling inertia: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/1e5b3af6-8a1e-4e16-833d-ae97921ddcda/uwp-how-to-make-scrollviewer-ignore-mouse-wheel-event-and-pass-on-to-parent-flipview?forum=wpdevelop
- Similar situation, breaking Touch Support: https://stackoverflow.com/questions/37122576/uwp-disable-mouse-scroll-in-grid-view

**Comment by MikeHillberg** [comment]
So the goal in this case is that the mouse wheel always scrolls the page, even if the mouse is over the horizontally scrolling inner region?

**Comment by StephenLPeters** [comment]
@RBrid FYI

**Comment by RBrid** [comment]
I don't think we should invest further into the old ScrollViewer control. Instead we should make sure that the new WinUI ScrollView control which is in preview mode allows such scenarios.

The new ScrollView control exposes a ScrollView.IgnoredInputKinds read-write property that allows you to ignore mouse wheel input as a whole (without affecting touch input). You cannot ignore it in a more granular fashion though, like for horizontal/vertical scrolling or zooming alone.
Is that good enough for your needs?  Thanks!

**Comment by WilliamABradley** [comment]
In this scenario, the user can use touch bar or the scrollbar, so that would work :)
