### ISSUE TITLE
TextBox ContextFlyout with custom options doesn't show if no text is in clipboard

### ISSUE THREAD

**Issue by boarder2** [microsoft/microsoft-ui-xaml#2950]
**Describe the bug**
When custom actions are added to the `ContextFlyout` on the `TextBox` control, the flyout quickly shows then disappears if there is no text in the clipboard and nothing in the Undo stack. Sometimes it doesn't show at all.

**Steps to reproduce the bug**
1. Have empty or non-text data in your clipboard.
2. Right click in the TextBox
3. ContextFlyout shows briefly then disappears

**Expected behavior**
The flyout should show if there are custom actions like the code sample below.  If there are no custom actions, the flyout should not show at all, even briefly.

**Version Info**
NuGet package version:
[Microsoft.UI.Xaml 2.4.2]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
Example code to reproduce the behavior in a new UWP app
XAML:
```xml
<TextBox x:Name="tb" Loaded="tbloaded" Unloaded="tbunloaded"/>
```

C#:
```C#
private void tbloaded(object sender, RoutedEventArgs e)
{
    tb.ContextFlyout.Opening += ContextFlyout_Opening;
}

private void tbunloaded(object sender, RoutedEventArgs e)
{
    tb.ContextFlyout.Opening -= ContextFlyout_Opening;
}

private void ContextFlyout_Opening(object sender, object e)
{
    var flyout = (sender as CommandBarFlyout);
    flyout.PrimaryCommands.Add(new AppBarButton()
    {
        Command = new StandardUICommand(StandardUICommandKind.Close) //Just used as an example, doesn't matter what the UICommand is. Behavior is the same
    });
}
```

**Comment by StephenLPeters** [comment]
The text command bar flyout is likely checking if any of its default commands are valid, and closing when they aren't. seems like a bug.

**Comment by chingucoding** [comment]
I am not sure if this is an issue on my end, but I am having troubles hitting breakpoints inside the (Text)CommandBarFlyout in MUXC. The constructor get's called, beside that however almost no code path seems to get hit.

**Comment by boarder2** [comment]
@chingucoding I played around with it a little bit and saw similar behavior. Admittedly I'm not familiar with the MUXC code base at all, so I may be missing something.

**Comment by StephenLPeters** [comment]
@llongley If you still remember the context can you weigh in here?

**Comment by llongley** [comment]
@chingucoding @boarder2 The sample code is using the default ContextFlyout, which would be the WUX version of the control.  You'd need to explicitly set the ContextFlyout property to an instance of the MUXC TextCommandBarFlyout to see breakpoints getting hit.

**Comment by chingucoding** [comment]
Thanks @llongley for the help!

@boarder2 If you add the following in your TextBox loaded, the behavior seems to function correctly, and the ContextFlyout does not clear itsself.

```c#
tb.ContextFlyout = new Microsoft.UI.Xaml.Controls.CommandBarFlyout();
```

@StephenLPeters @ranjeshj Is there anything we or should do to make the default TextBox control (and others) make use of the MUXC one? Or is it easier to wait until WinUI 3? Is this bug report still actionable then or should we close it then, given that the MUXC version seems to behave correctly?

**Comment by ranjeshj** [comment]
If it works with the MUXC.CommandBarFlyout, it should be fixed in WinUI3 as well, so closing this bug. Thanks @chingucoding !

**Comment by boarder2** [comment]
If I set it to a new instance of the MUXC CommandBarFlyout none of the system level functions like copy/paste/undo, etc work. I'd have to build the whole text based menu manually. That doesn't seem like a great workaround here.

**Comment by chingucoding** [comment]
Yes you are right, and I made a mistake. Using MUXC.CommandBarFlyout works, but it is a normal ContextFlyout without the Paste/Undo... options. In your case you would need to use the MUXC.TextCommandBarFlyout, which does not work correctly.

I think we need to reopen this issue, mind if I work on this @ranjeshj ?

**Comment by ranjeshj** [comment]
ok. Sounds like there are issues with the MUXC flyout as well. @chingucoding go for it. Thanks!

**Comment by StephenLPeters** [comment]
We should also open a new issue to track updating text block in Winui3 to use the updated commandbar flyout

**Comment by chingucoding** [comment]
Does the WinUI 3 use the MUXC contextflyout or is it using the WUXC one? Would you like me to create the tracking issue?

**Comment by ranjeshj** [comment]
We don't need to fix this in WinUI3. In WinUI3 we are using MUXC one.
