### ISSUE TITLE
Setting PivotItem.Visiblity to Collapsed Does not Remove It from Pivot

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#2952]
**Describe the bug**

Setting PivotItem.Visiblity to Collapsed does not remove a PivotItem, it only collapses the Content. 

A common scenario when using a Pivot for tab navigation requires sometimes hiding a tab. This was always possible in other controls like in WPF's TabControl which Pivot was supposed to replace. However, in UWP, setting PivotItem.Visiblity=Collapsed will hide the Content but the PivotItem and its header are still shown within the Pivot and appear in the VisualTree. This means there is no way to hide a pivot's 'tab'.

This is a very old issue that has been reported years ago on user voice (before it was deleted) and is on multiple forums. It's something that should be simple to address in the platform but is complex to work-around in applications.

**Steps to reproduce the bug**

 1. Add a Pivot in XAML with at least 1 PivotItem
 2. Set a PivotItem's Visiblity=Collapsed
 3. The PivotItem Header is still visible in the Pivot

**Expected behavior**

If the PivotItem itself is Collapsed the Header and the entire PivotItem should be removed from the VisualTree. This also means keyboard navigation is no longer possible.

**Screenshots**

![image](https://user-images.githubusercontent.com/17993847/87887823-6f9e3b00-c9f6-11ea-83a2-25e6122c6709.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This will require WinUI 3.0 to be fixed. I will fix it myself if it comes to it -- this has been a thorn for years.

**Comment by scottkuhl** [comment]
I was quite shocked to find out this feature was not implemented in UWP and has been brought up multiple times over the years with no fix.

**Comment by mdtauk** [comment]
I get the impression Microsoft sees little value in the Pivot control these days.

**Comment by scottkuhl** [comment]
> I get the impression Microsoft sees little value in the Pivot control these days.

That would be a good question to ask on the next community call.  I found comments about this issue going back 6 years with no resolution.  I'm considering replacing the pivot control entirely because of this.

**Comment by robloo** [comment]
The Pivot is not the only control that has been neglected since the beginning. Lack of fixes like this is often cited as one of the reasons devs went back to WPF. 

On Microsoft's part: since everything historically shared the same UI framework including the OS, breaking changes were nearly impossible. With WinUI 3 decoupled and the compatible version set by each app I hope it all changes and we can finally address things like this. This will be a good litmus test if WinUI 3 will really take off.

**Comment by robloo** [comment]
I doubt Microsoft is going to fix the pivot so someone from the team can close this if they want.

Also, if the Pivot gets replaced this can be closed.

**Comment by DmitriyKomin** [comment]
@robloo, thank you for opening this issue and additional insight in your comments. Pivot is indeed not recommended currently (NavigationView or TabView are preferred), so indeed this does not currently make the bugfix bar. More information here: (https://learn.microsoft.com/en-us/windows/apps/design/controls/pivot#use-navigationview-instead-of-pivot)

**Comment by robloo** [comment]
@DmitriyKomin It was widely discussed and even mentioned in the community call some years ago that the NavigationView and TabView are NOT full replacements for Pivot. The WinUI team agreed to find a replacement even if that meant porting Pivot -- which is why Pivot was added back albeit with original code that includes this issue.

NavigationView is an App-level navigation control -- clearly not a TabControl (using the classic terminology). You can't seriously consider that a replacement. TabView is closer but was unfortunately designed and over constrained as a document-level/top-level tab control. Not suited to tabbing through lighter content such as settings. Pivot still is the best for a TabControl that we've had since WinForms.

**Comment by mdtauk** [comment]
> @DmitriyKomin It was widely discussed and even mentioned in the community call some years ago that the NavigationView and TabView are NOT full replacements for Pivot. The WinUI team agreed to find a replacement even if that meant porting Pivot -- which is why Pivot was added back albeit with original code that includes this issue.
> 
> NavigationView is an App-level navigation control -- clearly not a TabControl (using the classic terminology). You can't seriously consider that a replacement. TabView is closer but was unfortunately designed and over constrained as a document-level/top-level tab control. Not suited to tabbing through lighter content such as settings. Pivot still is the best for a TabControl that we've had since WinForms.

WinAppSDK 1.5 has a Pivot replacement called Selector Bar
