### ISSUE TITLE
In WinUI 3, is it possible to create a transparent Xaml Island overlay on top of parent hwnd?

### ISSUE THREAD

**Issue by smk2007** [microsoft/microsoft-ui-xaml#2956]
I have created a Xaml Island in a C++ Desktop Application:

        xaml_app_host_ = winrt::Microsoft::UI::Xaml::Application{};
        desktop_window_xaml_source_ = winrt::Microsoft::UI::Xaml::Hosting::DesktopWindowXamlSource{};
        desktop_window_xaml_source_.as<IDesktopWindowXamlSourceNative>()->AttachToWindow(window_);

I see the window created and the child corewindow and bridge window children under my main window:

![image](https://user-images.githubusercontent.com/6754002/87903635-5787e500-ca11-11ea-99a2-1b917bdec9bf.png)

Controls render fine, but the entire window turns black, covering contents rendered to the parent window. I would like the controls in the xaml island to show up overlaid on the contents rendered to the parent window (which is rendering at low latency and controlling the message pump).

This behavior happens even without any controls set to the content.

I have tried futzing with setting ws_ex_layered, and a COLORKEY:

```
        auto content_bridge = FindWindowEx(window_, NULL, L"Microsoft.UI.Input.DesktopWindowLiftedContentBridge", NULL);
        ::SetWindowLong(content_bridge, GWL_EXSTYLE, GetWindowLong(content_bridge, GWL_EXSTYLE) | WS_EX_LAYERED | WS_EX_TRANSPARENT);
        ::SetLayeredWindowAttributes(content_bridge, RGB(0,0,0), 0, LWA_COLORKEY);
```

Is this possible? If not, are there any work arounds?

**Comment by StephenLPeters** [comment]
@MikeHillberg and @Austin-Lamb FYI.

**Comment by Austin-Lamb** [comment]
At this time we don't support transparency in WinUI 3's background (for islands, desktop or UWP), but we are discussing adding that at a later time to at least Win32.

@smk2007 - there are two kinds of transparency, output and input.  Would you want output transparency (can see through to what's below), or also input transparency (input seamlessly flows through to what's below the transparent pixels)?

**Comment by smk2007** [comment]
I would like both :) 

My scenario is that I would like most of the interaction to happen with the win32 window which controls a real time rendered dx app.

The underlying window renders a dx app with a real time loop. I want to add a XAML overlay so that it seamlessly integrates with the rendered content below. In order to do that we are experimenting with full screen overlays and chrome that frames the underlying dx rendered window. We would like for the underlying window to handle all input when the user isn't interacting with it :)

At the very least they would need to see what is behind the overlay. If the overlay needs to forward input events it is OK, but less than ideal.

**Comment by smk2007** [comment]
Hi is there any update on adding transparency to WinUI 3?

**Comment by Austin-Lamb** [comment]
No update yet - but the request for both types of transparency is being tracked as a feature request.  I think it will be a while before we can get to it, and it's possible we will do output transparency first and input transparency at a later time (we're treating the two separately as some folks only need output).

**Comment by annmanvel** [comment]
Hi,
I am currently working to make Transparent overlay and click through. Is it possible to achieve this functionalities using UWP(C#) or WinUI 3 in UWP (C#); without using win32 api dlls.
