### ISSUE TITLE
Release Build Error with NavigationView

### ISSUE THREAD

**Issue by Artain** [microsoft/microsoft-ui-xaml#2957]
**Describe the bug**
When I create a project with a NavigationView and start the package in den the debug configuration everything works fine, but if I start it with the release configuration I get a `Cannot find a Resource with the Name/Key TabViewButtonBackground` error message.

**Steps to reproduce the bug**

1. Create a blank WinUi desktop project with package
2. Delete the button from the xaml and cs
3. Add a simple NavigationView to the xaml
4. Build and start the app in release configuration

**Expected behavior**
App works the same as in debug configuration

**Version Info**
- Nuget WinUI: 3.0.0-preview2.200713.0
- .net SDK: 5.0.100-preview.5.20279.10 (x86 and x64)
- VS: 16.7.0 Preview 4.0 (4.8.04084)
- Windows: Win10 19041

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | not tested |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | not tested |
| May 2019 Update (18362)            | not tested  |
| October 2018 Update (17763)        |  not tested |
| April 2018 Update (17134)          |  not tested  |
| Fall Creators Update (16299)       |  not tested    |
| Creators Update (15063)            |  not tested    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  not tested  |
| Surface Hub        |  not tested  |
| IoT                |  not tested  |

**Additional context**
I found the following Issue [1295](https://github.com/microsoft/microsoft-ui-xaml/issues/1295) which sounded similar enough but the fix did not work. 
A simple Test project with all the described reproduce steps
[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4947481/App1.zip)

**Comment by StephenLPeters** [comment]
@stevenbrix @alwu-msft FYI
@ranjeshj we've had a few of these release only build failures in the past, but this one is Winui3 preview specific.

**Comment by ranjeshj** [comment]
> @stevenbrix @alwu-msft FYI
> @ranjeshj we've had a few of these release only build failures in the past, but this one is Winui3 preview specific.

This does seem specific to Preview2. I see this issue when using any of the controls from WinUI2 so it seems more wide spread than just NavigationView. debug builds seem to work fine.

**Comment by icnocop** [comment]
Is there a work-around?

**Comment by stevenbrix** [comment]
This sounds somewhat familiar, can you try adding this to your project file:
```xml
<PropertyGroup>
   <DisableEmbeddedXbf>true</DisableEmbeddedXbf>
</PropertyGroup>
```

**Comment by icnocop** [comment]
Thank you, @stevenbrix!

That worked! 🎉
