### ISSUE TITLE
NavigationView UI looks off when changing high contrast modes

### ISSUE THREAD

**Issue by ejserna** [microsoft/microsoft-ui-xaml#2958]
**Describe the bug**
When changing high contrast modes, you can see weird patches in the NavigationView. 

**Steps to reproduce the bug**
1. Start in High Contrast White
2. Change to High Contrast Dark

**Expected behavior**
It shouldn't look like screenshot 2 and should look like 3.

**Screenshots**
1
<img width="2217" alt="1" src="https://user-images.githubusercontent.com/11062927/87967663-03fab300-ca74-11ea-9bee-045004e4059a.png">
2 (look at the white patch)
<img width="2266" alt="2" src="https://user-images.githubusercontent.com/11062927/87967683-0b21c100-ca74-11ea-8eba-911071fe7c1b.png">
3 (this is how it should look)
<img width="1258" alt="3" src="https://user-images.githubusercontent.com/11062927/87967826-4a501200-ca74-11ea-801c-af985068ce37.png">

**Version Info**
WinUI 2.4

NuGet package version: 
Microsoft.UI.Xaml.2.4_2.42005.18002.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes  |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |Yes|
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
This is an issue with the framework, not with navigationview, which has been brought up before. The actual user impact is pretty low because users very rarely change high contrast themes and this is only an issue if that is done while the app is running and goes away if you restart the app.

**Comment by StephenLPeters** [comment]
related internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/27503608)

**Comment by chrisglein** [comment]
Potentially related issues on this repo: #1437 #2138.
Agree with Stephen's assessment above that while this is definitely broken, it is a less common user scenario so thankfully it isn't seen often.
