### ISSUE TITLE
Seeking in MediaPlayerElement

### ISSUE THREAD

**Issue by mc0re** [microsoft/microsoft-ui-xaml#2964]
I assign a home-made stream to `MediaPlayerElement.Source`. To be more exact, the stream ID is assigned to a `MediaBinder`, which is wrapped into a `MediaSource`, which is wrapped into a `MediaPlaybackItem`, and a bunch of those items are added to a `MediaPlaybackList`, which is finally assigned to `MediaPlayerElement.Source`.

When I start the playback, I can trace that the player seeks close to the end of the file, so I assume it reads the MP4 look-up table - and knows it can seek in the stream. But when I click on the time bar in order to seek forward during the playback, the player starts reading the data sequentially towards the destination, instead of *seeking* directly to the destination offset - which it should know from the look-up table. This takes really long time (seeking 1 hour video file in ~256KB blocks takes a noticeable amount of seconds).

I assume I am missing something in the setup. Could you tell me, under which conditions the player reads sequentially instead of seeking, or what I can do to make it use *seek*?

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI

**Comment by mc0re** [comment]
Please?
