### ISSUE TITLE
NavigationView left side can get stuck

### ISSUE THREAD

**Issue by crutkas** [microsoft/microsoft-ui-xaml#2966]
**Describe the bug**

reported in
https://github.com/microsoft/PowerToys/issues/5123

**Steps to reproduce the bug**

click on an item in the navigationview and drag your cursor outside of the area.

**Expected behavior**

only one item selected

**Screenshots**

![image](https://user-images.githubusercontent.com/51363864/88065681-445f4b80-cbb0-11ea-874f-3257fac9d97a.png) you can select all of them!

**Version Info**

NuGet package version: 
2.5.0-prerelease.200609001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | yes    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

can reproduce in xaml gallery

**Comment by Felix-Dev** [comment]
@crutkas Can you test this with Microsoft.UI.Xaml v2.5.0-prerelease.200708003? This appears to me as an issue which has been fixed in https://github.com/microsoft/microsoft-ui-xaml/pull/2625. This fix is not available in the 2.5 preview version you are currently using.

**Comment by StephenLPeters** [comment]
Yeah, I think this should be fixed by #2625. I'm going to close the issue, but if that doesn't fix feel free to reopen it.
