### ISSUE TITLE
Build failing with error - MSB4175 : The task factory "CodeTaskFactory" could not be loaded from the assembly

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/microsoft-ui-xaml#2967]
Win UI 3 build started failing with error - MSB4175 The task factory "CodeTaskFactory" could not be loaded from the assembly "Microsoft.Build.Tasks.Core.dll". Operation did not complete successfully because the file contains a virus or potentially unwanted software at (Package)\build\Microsoft.WinUI.AppX.targets

**Version Info**
dot net - 5.0.100-preview.5.20279.10
Win UI  - 3.0.0-preview2.200713.0
Win 10 - May 2020 Update (19041)
Desktop - Yes

**Comment by LuisMiguelGarcia** [comment]
I had the same error. Checking my code a bit I saw that I had the package "Microsoft.CodeDom.Providers.DotNetCompilerPlatform" from the NuGet console, I removed it and it already lets me compile my project.

**Comment by abhi-msft** [comment]
I have only these two..
![image](https://user-images.githubusercontent.com/52011872/88120535-fb8ba080-cb77-11ea-8855-c8580c688d2b.png)

**Comment by LuisMiguelGarcia** [comment]
Check on menu Project > Manage NuGet Packages and check if is allready installed: 

![image](https://user-images.githubusercontent.com/27976015/88121300-e9ffc400-cb8a-11ea-9fcd-06fc379c9b00.png)

**Comment by abhi-msft** [comment]
Earlier screenshot was also from Installed tab :) 
![image](https://user-images.githubusercontent.com/52011872/88124217-73aa9400-cb81-11ea-9f54-f959a74e6c0f.png)

**Comment by LuisMiguelGarcia** [comment]
Another thing that can interfere is the windows defender. You can add the dll in the path that causes you problems as an Exclusion.

![image](https://user-images.githubusercontent.com/27976015/88156038-7c758700-cbce-11ea-85ca-b9b960a3180a.png)

**Comment by slide** [comment]
We're getting this same thing using the net35 sdk docker image in our CI.

**Comment by riraccuia** [comment]
we are experiencing the same problem starting today

**Comment by riraccuia** [comment]
it's definitely windows defender

**Comment by shimpossible** [comment]
Windows defender log show it detecting files in the temp directory that look like dynamically compiled assemblies. Probably from tasks.core.dll

**Comment by shaheedpak** [comment]
we are also seeing similar issues but another item we noted is bunch of random .dll files being written to C:\temp, is anyone setting this issue along with this error as well? Defender flagging this as VirTool:MSIL/EMesbild.A and not much info on Microsoft references.

**Comment by abaines-phx** [comment]
![vmware_qF0BrdGS20 clean3](https://user-images.githubusercontent.com/36737846/88209445-bb342d00-cc20-11ea-93d5-942c441bc844.png)


The `Learn more` link takes me to [https://go.microsoft.com/fwlink/?linkid=142185&name=VirTool:MSIL/Emesbild.A&threatid=2147741673](https://go.microsoft.com/fwlink/?linkid=142185&name=VirTool:MSIL/Emesbild.A&threatid=2147741673).

**Comment by abaines-phx** [comment]
FWIW, updating Microsoft Windows Defender seems to fix the problem. 😎

**Comment by kwoodard** [comment]
Updating the Windows Defender virus definitions definitely seems to solve the problem.

**Comment by perkerk** [comment]
Seeing this too, coinciding with the randomly named DLL's being created in a temp directory. Is that (DLL creation) the signature of the virus, or is there a virus signature in these newly created DLL's. The latter would be a lot more suspicious. I'm hesitant to whitelist this without finding a definitive answer

**Comment by shimpossible** [comment]
> Updating the Windows Defender virus definitions definitely seems to solve the problem.

What version of definitions are you using?  And by chance what version was it broken in?

**Comment by perkerk** [comment]
Upgrading from the definitions installed 2 days ago:
Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.319.1877.0)
to:
Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.319.2051.0)
did fix it for me

**Comment by perkerk** [comment]
> > Updating the Windows Defender virus definitions definitely seems to solve the problem.
> 
> What version of definitions are you using? And by chance what version was it broken in?

Upgrading from the definitions installed 2 days ago:
Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.319.1877.0)
to:
Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.319.2051.0)
did fix it for me

**Comment by JawedCIA** [comment]
Thanks @perkerk !
Yes, Updated Microsoft Defender Antivirus fixed the issue.
Validated with V 1.319.2068.0 👍 

![image](https://user-images.githubusercontent.com/16477789/88268267-78329200-ccd2-11ea-8873-5355c7c648ba.png)

**Comment by shimpossible** [comment]
I've no nuget packages installed.  I get this error using msbuild v14.  But not with the one in the framework directory, or using msbuild from vs2019.
