### ISSUE TITLE
Discussion: How to enable Reveal style in WinUI

### ISSUE THREAD

**Issue by jeganrajm** [microsoft/microsoft-ui-xaml#2972]
How to enable Reveal style in WinUI?

The same code which I run in UWP with "Microsoft.UI.Xaml" nuget, shows reveal background and reveal border, but in WinUI UWP (Microsoft.WinUI) project, it has no effect.
Do I need to make changes in my settings?

Code:
`<Button Content="MS Button"
                Style="{ThemeResource ButtonRevealStyle}" />`
`<AppBarButton Label="Like" 
                           Style="{ThemeResource AppBarButtonRevealStyle}" />`

![image](https://user-images.githubusercontent.com/18045503/88184538-732cfe80-cc50-11ea-81f9-85d62f28aecc.png)

Reference link: https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal

**Comment by StephenLPeters** [comment]
The Preview 2 version of Winui3 does not yet support reveal so for the time being you cannot. Setting this style will fallback to the solid color brush. https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#preview-2-limitations-and-known-issues
