### ISSUE TITLE
How do we edit a control template for WinUI 3 alpha while the designer isn't working?

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2975]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1118289/how-do-we-edit-a-control-template-for-winui-3-alph.html)._

---
<p>While the Xaml designer isn’t working, we don’t have the option to right click a control to Edit Template. Is there another way to get access to the default template?</p>
<p>PS. This page crashed several times (threw exceptions) when I clicked away to VS and tried switching back. It kept throwing exceptions when I closed the popup exception window. Took a few goes before returning to the page. Edit: It was the devcommunity2 page.</p>

---
#### Feedback Bot on 7/20/2020, 02:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Nikola Mihaylov [MSFT] on 7/20/2020, 01:56 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/12449/34ad05d5-16e4-4652-83de-6c0d60ea082e.html" nodeid="12449">@Gavin Williams</a> re: feedback crash/exceptions: thanks for the info! Fixed as of this morning at 11 AM PST (~12 hours after this report.) </p><p>To make sure we fixed the feedback bug you mentioned: Could you please confirm if you still see any feedback site crashes or exceptions?</p><p>Thanks!</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
This wont be an issue after OSS, however right now I think there is not way to do this... @MikeHillberg FYI

**Comment by dotMorten** [comment]
Along those lines it's same problem for control libraries built on top. Historically [we're supposed to include the generic.xaml file in the nuget package](https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls#add-design-time-support), so that the designer can use this, but the pack step doesn't include it, but only packages the template inside the `.pri` file.

**Comment by fabiant3** [comment]
It is unfortunate but we do not plan to have the designer available at the time we'll be shipping WinUI3. @dotMorten we do ship generic.xaml with our Nuget package since Preview2.

**Comment by dotMorten** [comment]
@fabiant3 I know. It was more to point out that your Pack step doesn't pack the xaml when packing a WinUI class library with controls

**Comment by thomasclaudiushuber** [comment]
@fabiant3 I don't know about the designer plans. But wouldn't it possible to populate at least the Document Outline window, so that elements can be right-clicked there to get this functionality?

**Comment by thomasclaudiushuber** [comment]
Ah, sorry, just noticed that this issue was already closed. I think the current state is not ideal. In Visual Studio, there should be a functionality to create a copy of a ControlTemplate, with or without a designer.
