### ISSUE TITLE
Discussion: epx shouldn't scale with screen size

### ISSUE THREAD

**Issue by SetTrend** [microsoft/microsoft-ui-xaml#2976]
# Discussion: epx shouldn't scale with screen size

Taken from: https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro:

>When your app runs on a device, the system uses an algorithm to normalize the way UI elements display on the screen. This scaling algorithm takes into account viewing distance and screen density (pixels per inch) to optimize for perceived size (rather than physical size). The scaling algorithm ensures that a 24 px font on Surface Hub 10 feet away is just as legible to the user as a 24 px font on 5" phone that's a few inches away.
>
>![Image scaling in XAML](https://docs.microsoft.com/en-us/windows/uwp/design/basics/images/scaling-chart.png)
<br/>

### I believe that the assumption of larger screens being farther away from the user than smaller screens is a popular myth.

Just to give an example from my personal experience:

- I'm currently sitting in front of a 32" monitor, **80cm away from my eyes**.
- Using my 2-in-1 Surface Pro tablet, equipped with a 12" screen, it usually is **80cm away from my eyes**.
- My smartphone, equipped with a 3" screen, commonly is **80cm away from my eyes**.

I couldn't imagine any other application than television screens to be put far away from the user and still be interacted with. And I can hardly imagine someone interacting with a smartphone just "a few inches away" - except the user is myopic.

So, I believe "effective picels" should be determined by the absolute size of a pixel on screen (i.e. dpi) alone.

## Related Links
https://github.com/SetTrend/CSS3---absolute-media-queries

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by ad1Dima** [comment]
>My smartphone, equipped with a 3" screen, commonly is 80cm away from my eyes.
>And I can hardly imagine someone interacting with a smartphone just "a few inches away" - except the user is myopic.

80cm is about full arm length. If you had to interact with smartphone this way, it's hyperopia

Anyway, there is Scale settings user can set per monitor. So can you explain, what exact problem do you have with effective pixels?

**Comment by SetTrend** [comment]
Thank you for taking the time.

It's particularly the definition given in the document. It's pointing out an effectively similar assumption that's been taken by the "Bootstrap" CSS library, commonly used for web pages.

I'm constantly working in front of a large screen using Websites being displayed with giant letters and smartphone layout because the Bootstrap library is based on pixels instead of real device size.

So I want to raise a discussion (and awareness) of applying sensible parameters when it comes to screen layout and breakpoints.
