### ISSUE TITLE
x:Bind does not work with Hot Reload

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/microsoft-ui-xaml#2983]
As we know, x:Bind offers good advantages over regular binding markup extension. However, one of the drawback of using x:Bind is it is incompatible with Hot Reload.

**Steps to reproduce the bug**
1. Start a debug session
2. Modify a XAML attribute that uses x:Bind -> the attribute will not take into account the change

**Expected behavior**
The Hot Reload should take into account the new change.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
All of them

**Additional context**
As a temporary suggestion, maybe during debug time x:Bind could be regular binding when an option is applied

**Comment by AathifMahir** [comment]
I also prefer that, changing x:bind to bind during debugging only once profiling performance of the app the binding should stay with x:bind instead of changing.

**Comment by kmgallahan** [comment]
Per [the Hot Reload docs](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload), "Changing data binding that uses the {x:Bind} markup extension" works with W10 v1809 and later.

Your repro states: "Modify a XAML attribute that uses x:Bind", but I'm not quite clear what modifications aren't working for you. I can change both the bind path and source value and those changes are reflected via Hot Reload.

**Comment by ArchieCoder** [comment]
@kmgallahan I have 2 examples: removing a Converter={StaticResource...} OR changing a path like Text="{x:Bind Task.Text}" with "{x:Bind Meeting.Name}" are not working for me (the last one is from a DataTemplate.

**Comment by fabiant3** [comment]
We currently don't have HotReload working for WinUI3, but we are working on it and expect to have it done part of the WinUI3. See current [release notes](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#developer-tools).
