### ISSUE TITLE
Question: Is it possible to integrate AAD with Win UI-3 Desktop (SSO/Hello Pin/Certificates)?

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/microsoft-ui-xaml#2985]
Is it possible to integrate AAD with Win UI-3 Desktop (SSO/Hello Pin/Certificates)?

I see below options but with limitations.
- Web account manager (WAM) seems to work only on Apps deployed to store. 
- With MSAL, user has to provide user name/password and phone authentication but not a certificate or pin.

![image](https://user-images.githubusercontent.com/52011872/88424265-17728a80-cda2-11ea-8d2e-e46e32dad62c.png)

**Comment by ranjeshj** [comment]
@MikeHillberg could you help route this question ?

**Comment by abhi-msft** [comment]
Able to use AAD with logged in Windows credentials as described [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#uwp-does-not-use-the-system-webview) but with a limitation of using opening web browser under http://localhost:portnumber.

Is this a recommended practice? I see no other option for .NET Core(including .NET 5)
