### ISSUE TITLE
Intellisense - Wrong RoutedEventArgs created for button Click 

### ISSUE THREAD

**Issue by HerrickSpencer** [microsoft/microsoft-ui-xaml#2986]
**Describe the bug**
When creating a Xaml button, and assigning a handler method to the Click property, Intellisense uses the wrong RoutedEventArgs when you tab to accept the offer to create a new handler.

**Steps to reproduce the bug**

1. Open new project with the 'Blank App (WinUI in UWP)' template
2. Open the Xaml editor for the mainpage.xaml file
3. Start to add a tag for `<Button x:Name="myButton" Click="myButton_Click">Click Me</Button>`
4. When you type 'Click="' it will pop an Intellisense `"<New Event Handler>"` flyout. use arrows and tab to select this.
5. Check the generated code in mainpage.xaml.cs

**Expected behavior**

Code in mainpage.xaml.cs should have used the RoutedEventsArgs from Microsoft.UI.Xaml namespace

**Actual behavior**
Code in mainpage.xaml.cs should have used the RoutedEventsArgs from Windows.UI.Xaml namespace. This causes a build error.

**Screenshots**

![image](https://user-images.githubusercontent.com/13108756/88432860-e437f780-cdb1-11ea-91ae-1e7ac171fa15.png)
![image](https://user-images.githubusercontent.com/13108756/88432906-fb76e500-cdb1-11ea-8b20-21a3a26155bf.png)

**Version Info**

NuGet package version: Microsoft.WinUI 3.0.0-preview2.200713.0
OS Name:	Microsoft Windows 10 Enterprise Insider Preview
Version:	10.0.20175 Build 20175
System Type:	x64-based PC

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20175)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by evelynwu-msft** [comment]
This was fixed some time ago. @HerrickSpencer if you still see this behavior with the 1.2 release of Windows App SDK, please open a new issue in this repository.
