### ISSUE TITLE
ScrollViewer's content is lag while panning with ManipulationDelta event

### ISSUE THREAD

**Issue by d2phap** [microsoft/microsoft-ui-xaml#2990]
**Describe the bug**
ScrollViewer's content is lag while panning with `ManipulationDelta` event.
Please see the attached videos.

**Steps to reproduce the bug**
```xaml
<ScrollViewer
    Background="LightGray"
    x:Name="viewer"
    ZoomMode="Enabled"
        
    MaxZoomFactor="100"
    HorizontalScrollBarVisibility="Hidden"
    VerticalScrollBarVisibility="Hidden"

    HorizontalScrollMode="Enabled"
    VerticalScrollMode="Enabled">
    <Grid
        HorizontalAlignment="Center"
        VerticalAlignment="Center"
        ManipulationMode="All"
        ManipulationDelta="Image_ManipulationDelta">
        <Image
            x:Name="picMain"
            Source="ms-appx:///Assets/photo.jpg">
        </Image>
    </Grid>
</ScrollViewer>
```

```csharp
private void Image_ManipulationDelta(object sender, ManipulationDeltaRoutedEventArgs e) {
    var tranX = -1 * e.Delta.Translation.X;
    var tranY = -1 * e.Delta.Translation.Y;

    var offsetX = tranX + viewer.HorizontalOffset;
    var offsetY = tranY + viewer.VerticalOffset;

    viewer.ChangeView(offsetX, offsetY, null, true);
}
```

**Expected behavior**
The content should be moving smooth without being lag.

**Screenshots**
[WinUI3-ScrollViewer bug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4977240/WinUI3-ScrollViewer.bug.zip)

**Version Info**
NuGet package version: 
**Microsoft.WinUI 3.0.0-preview2.200713.0**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Windows 10 2004            |  Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@RBrid and @jeffstall FYI.
