### ISSUE TITLE
Question: Transparent background support for WebView2?

### ISSUE THREAD

**Issue by Gunners6522** [microsoft/microsoft-ui-xaml#2992]
When working with UWP apps it is possible for a WebView to set "DefaultBackgroundColor='Transparent'" and receive a WebView with a transparent background. However, in WinUI3 the WebView2 component does not have this property. 

So I'm wondering if the WinUI3 WebView2 component supports having a transparent background or if it is something Microsoft will eventually support? And will it then work for both WinUI3 UWP Apps and WinUI3 Desktop Apps?

This question might be related to other issues, but I wasn't sure and couldn't find a post discussing background transparency in WebView2.

**Comment by StephenLPeters** [comment]
@adambarlow FYI

**Comment by codendone** [comment]
This may be something we eventually support, but it will not be supported in WinUI 3.

The rendering integration we can currently achieve does not allow a transparent background to properly show rendering from other WinUI elements beneath the WebView2. We'd like to change how this works in the future, which would also allow for transparency, but this will require significant changes in both the Edge WebView2 code and the WinUI code.

**Comment by darkguy2008** [comment]
Just maybe a far-fetched idea, but would it be possible to override WebView2's OnPaint() method (if it has any?) and take the WebView2's view and paint a color key (like Chroma key works) with a transparent color or something that Windows sees as transparent? Somewhat like Win98, WinXP and so on managed transparent windows in game installers, WinAmp and so on?

Yeah I know I'm talking about WinForms, don't like WPF very much, but maybe it's an idea.

**Comment by sylveon** [comment]
Color keys ruin text antialiasing
