### ISSUE TITLE
Text selection highlighting disappears

### ISSUE THREAD

**Issue by krlvm** [microsoft/microsoft-ui-xaml#2996]
**Describe the bug**

1. Highlight of selected text disappears after opening a context menu (right click) when it is already opened.\
The highlight returns after closing the context menu (left click).
2. Highlight of selected text disappears (and appears again after opening and closing context menu) after user minimized/restored/maximized window (affects not all controls).
3. Highlight of selected text disappears after user changes the focus inside window, but the selection still remain, it appears again after opening and closing context menu (affects not all controls).

**Steps to reproduce the bug**

The bugs is present in all UWP apps, including the Windows 10 system ones.\
They can be easily reproduced in `XAML Controls Gallery` app.

Bug №1:
1. Go to 'Text -> TextBox'
2. Select some text, in a TextBox or in a code snippet.
3. Open context menu (highlight is visible).
4. Open it again quickly, do not close the previous before (highlight is gone).
5. Close the context menu by left click (highlight is visible).

Bug №2:
1. Go to 'Text -> TextBox'
2. Select some text in a code snippet.
3. Minimize/restore/maximize window (highlight is gone).
4. Open code snippet's context menu (highlight is not visible).
5. Close the context menu by left click (highlight is visible).

Bug №3:
1. Go to 'Text -> TextBox'
2. Select some text in a code snippet.
3. Lose focus, click on TextBox for example.
4. Open code snippet's context menu (highlight is not visible).
4. Close the context menu by left click (highlight is visible).

**Expected behavior**

1. Highlight of selected text should not disappear.
2. Highlight of selected text should not disappear if user minimized/restored/maximized window.
3. Text selection should be completely removed after user changed focus inside window, not only the highlight.

**Screenshots**

Bug №1:
![Bug1](https://user-images.githubusercontent.com/51774833/88546901-12297000-d02e-11ea-88fd-9fd24e17d0d7.gif)

Bug №2:
![Bug2](https://user-images.githubusercontent.com/51774833/88546921-18b7e780-d02e-11ea-919f-219f617d957a.gif)

Bug №3:
![Bug3](https://user-images.githubusercontent.com/51774833/88546933-1c4b6e80-d02e-11ea-8159-29252ed5c7f7.gif)

**Version Info**

NuGet package version: 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20175)              | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by Felix-Dev** [comment]
This sounds similar to https://github.com/microsoft/microsoft-ui-xaml/issues/1801.

**Comment by krlvm** [comment]
Exactly, didn't find it right away.\
This issue can be marked as duplicate, since all of bugs is related to highlighting color when control is not in focus.
