### ISSUE TITLE
A few problems with the new NavigationView control on winui library

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/microsoft-ui-xaml#3]
a few problems with the new NavigationView control on winui library :
1. No Acrylic.
2. No way to manually set acrylic because there is no "PaneBackground" property.
3. No way to edit its template in blend either.

**Comment by jebishopms** [comment]
Actually we just pushed a package version (2.0.181011001 ) that will cause 3. to be an issue for all apps - now tracking that here:
 #4
