### ISSUE TITLE
EffectiveViewport does not work in certain cases for WinUI desktop apps

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#3001]
EffectiveViewport value obtained by elements in WinUI3 desktop apps seems to be incorrect sometimes and empty at other times.

```
 <Grid  HorizontalAlignment="Left" VerticalAlignment="Top">
        <TextBlock x:Name="text" HorizontalAlignment="Right" VerticalAlignment="Top"/>
        <ScrollViewer>
            <Button Width="200" Height="5000" x:Name="button" />
        </ScrollViewer>
    </Grid>

  button.EffectiveViewportChanged += Button_EffectiveViewportChanged;
  private void Button_EffectiveViewportChanged(FrameworkElement sender, EffectiveViewportChangedEventArgs args)
        {
            var viewport = args.EffectiveViewport;
            text.Text = viewport.ToString();
        }

```

**Version Info**

![image](https://user-images.githubusercontent.com/28935693/88596306-ad641a80-d019-11ea-854e-d409cd38195f.png)

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

**Comment by anawishnoff** [comment]
This has been fixed in the most recent release of WinUI 3 (Windows App SDK 0.8), so I'm closing this issue.
