### ISSUE TITLE
[NumberBox] Header is not using correct brush when disabled.

### ISSUE THREAD

**Issue by niels9001** [microsoft/microsoft-ui-xaml#3003]
**Describe the bug**
When the NumberBox is disabled (IsEnabled = false) the Header doesn't use the approriate brush and stays the same. It should be inline with ComboBox and TextBox brushes. 

As a result, in PowerToys, we are now not using the Header but using a custom TextBlock which is an annoyance and breaks productivity.

**Steps to reproduce the bug**
1. Set NumberBox to IsEnabled = false.

**Expected behavior**
The header text will become lighter gray, inline with ComboBox and TextBox. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9866362/88670199-0ea4f000-d0e5-11ea-8bb2-f8d9fe06d467.png)

**Version Info**
Latest stable and pre-release version.

**Additional context**
It might be that this topic is already raised, but couldn't find it. Please close if so.

**Comment by Felix-Dev** [comment]
Looks like we have to create a *Disabled* visual state for the NumberBox in its default control template where we will update the foreground color of the header.
