### ISSUE TITLE
PRI252: 0xdef00071 - File (ProjectPath)\bin\x86\Debug\net5.0\(Project).pri not found when publishing the package

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/microsoft-ui-xaml#3004]
WinUI-3 Desktop sideload publish is failing after adding a class library project with error - PRI252: 0xdef00071 - File (ProjectPath)\bin\x86\Debug\net5.0\(Project).pri. (Build and debug happening with out issues)

I see that process is trying to look for .pri file under the directory - \bin\x86\Debug\net5.0\ but the file is under the directory \bin\x86\Debug\net5.0\win-x86\

Seems like Class library project (Win UI Desktop) template is missing the runtime identifier making it look under the net 5.0 instead of runtime identifiers folder

**Adding the below to the proj file fixed the issue. But this should be taken care in the template similar to Blank app packaged template.**
`<RuntimeIdentifier>win-$(Platform)</RuntimeIdentifier>`

Version Info
dot net - 5.0.100-preview.5.20279.10
Win UI - 3.0.0-preview2.200713.0
Win 10 - May 2020 Update (19041)
Desktop - Yes

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by alwu-msft** [comment]
Preview 3 will resolve this issue.

**Comment by anawishnoff** [comment]
This was fixed in WinUI 3 Preview 3, so I'm going to go ahead and close this issue. Feel free to re-open and let us know if the issue still persists.
