### ISSUE TITLE
Fix "blurry" new tab icon on 100% DPI

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#3006]
###### This is being moved from https://github.com/microsoft/terminal/issues/7111

# Description of the new feature/enhancement

This is a little graphic detail that I noticed long ago. The "new tab" icon in Windows Terminal (1.1.2021.0) **with 100% DPI scaling level** is somewhat _"blurry"_ or _"thick"_, in comparison of other "new tab" icons like Microsoft Edge.

![issue1](https://user-images.githubusercontent.com/49621788/88761685-99b1d480-d13d-11ea-976c-478121b280bd.png)

> This graphic detail **does not occur when the DPI scaling is at 125%**.
> ![issue2](https://user-images.githubusercontent.com/49621788/88761704-a5050000-d13d-11ea-9814-8d50870b1774.png)

# Proposed technical implementation details (optional)

Update the "new tab" icon to a more _"cleaner"_ version when DPI scaling is at 100%. An example:

![issue3](https://user-images.githubusercontent.com/49621788/88762129-9408be80-d13e-11ea-9748-52fcac304746.png)

**Comment by Felix-Dev** [comment]
The "+" glyph looks fine to me with 100% DPI scaling in the XAML Controls Gallery:
![image](https://user-images.githubusercontent.com/1398851/88797374-89344500-d1a3-11ea-916e-a410b25fe571.png)

and in a WInUI 2.4.2 (and WinUI 2.5 preview) test project:
![image](https://user-images.githubusercontent.com/1398851/88797833-4030c080-d1a4-11ea-8a64-96a5f529712e.png)

Seems to me this is a Terminal (XAML Island?) specific issue (I am seeing the thicker "+" glyph in Terminal as well).

**Comment by DHowett** [comment]
Yeah, this is a terminal issue. We forgot we were using our own custom Add Tab button.

**Comment by zadjii-msft** [comment]
🤦‍♂️ that's what I get for doing triage at _6 am_
