### ISSUE TITLE
ItemsRepeater crash in WinUI 3 Preview 2 for Win32

### ISSUE THREAD

**Issue by hshristov** [microsoft/microsoft-ui-xaml#3007]
**Describe the bug**
When scrolling **ItemsRepeater** with **StackLayout** there is a crash when target is WinUI 3 Preview 2 Win32 application.

[RepeaterCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4994687/RepeaterCrash.zip)

**Steps to reproduce the bug**
1. Open the attached project
2. Select x86 and run the project
3. Drag the thumb around

**Expected behavior**
There should be no exception.

**Version Info**
NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
I saw issue #2834 but I think this one is different. First it use StackLayout and second the stack trace shows that it is something related to binding.

**Stacktrace**
>	KernelBase.dll!CompareStringOrdinalCounted()	Unknown
 	KernelBase.dll!_CompareStringOrdinal@20()	Unknown
 	combase.dll!WindowsCompareStringOrdinal(HSTRING__ * string1, HSTRING__ * string2, int * result) Line 377	C++
 	Microsoft.UI.Xaml.dll!DirectUI::PropertyProviderPropertyAccess::TryReconnect(IInspectable * pSource, unsigned char fListenToChanges, unsigned char & bConnected, const CClassInfo * & pResolvedType) Line 172	C++
 	Microsoft.UI.Xaml.dll!DirectUI::PropertyAccessPathStep::ConnectPropertyAccessForObject(IInspectable * pSource, unsigned int fListenToChanges, unsigned char * pbConnected) Line 233	C++
 	Microsoft.UI.Xaml.dll!DirectUI::PropertyAccessPathStep::ConnectToPropertyOnSource(IInspectable * pSource, unsigned int fListenToChanges) Line 156	C++
 	Microsoft.UI.Xaml.dll!DirectUI::PropertyAccessPathStep::ReConnect(IInspectable * pSource) Line 36	C++
 	Microsoft.UI.Xaml.dll!DirectUI::PropertyPathListener::ConnectPathStep(DirectUI::PropertyPathStep * pStep, IInspectable * pSource) Line 81	C++
 	Microsoft.UI.Xaml.dll!DirectUI::PropertyPathListener::SetSource(IInspectable * pSource) Line 60	C++
 	Microsoft.UI.Xaml.dll!DirectUI::BindingExpression::ConnectToEffectiveSource() Line 1259	C++
 	Microsoft.UI.Xaml.dll!DirectUI::BindingExpression::RefreshBindingValue() Line 1327	C++
 	Microsoft.UI.Xaml.dll!DirectUI::BindingExpression::BindingSourceChanged() Line 1309	C++
 	Microsoft.UI.Xaml.dll!DirectUI::BindingExpression::DataContextChanged(const DirectUI::DataContextChangedParams * pArgs) Line 1692	C++
 	Microsoft.UI.Xaml.dll!DirectUI::BindingExpressionDataContextChangedHandler::Invoke(DirectUI::DependencyObject * pSender, const DirectUI::DataContextChangedParams * pArgs) Line 445	C++
 	Microsoft.UI.Xaml.dll!DirectUI::CEventSourceBase<DirectUI::IDataContextChangedEventSource,DirectUI::IDataContextChangedHandler,DirectUI::DependencyObject,DirectUI::DataContextChangedParams const>::Raise(DirectUI::DependencyObject * pSource, const DirectUI::DataContextChangedParams * pArgs) Line 271	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!DirectUI::FrameworkElement::NotifyBindingExpressions(const DirectUI::DataContextChangedParams &) Line 662	C++
 	Microsoft.UI.Xaml.dll!DirectUI::FrameworkElement::NotifyOfDataContextChange(const DirectUI::DataContextChangedParams & args) Line 448	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!DirectUI::FrameworkElement::OnPropertyChanged2(const PropertyChangedParams &) Line 567	C++
 	Microsoft.UI.Xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(const PropertyChangedParams & args) Line 2240	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(CDependencyObject *) Line 2661	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!CFxCallbacks::DependencyObject_NotifyPropertyChanged(CDependencyObject *) Line 606	C++
 	Microsoft.UI.Xaml.dll!CDependencyObject::NotifyPropertyChanged(const PropertyChangedParams & args) Line 2823	C++
 	Microsoft.UI.Xaml.dll!CDependencyObject::SetEffectiveValue(const CDependencyObject::EffectiveValueParams & args) Line 1637	C++
 	Microsoft.UI.Xaml.dll!CDependencyObject::UpdateEffectiveValue(const CDependencyObject::UpdateEffectiveValueParams & args) Line 1903	C++
 	Microsoft.UI.Xaml.dll!CDependencyObject::SetValue(const SetValueParams & args) Line 1669	C++
 	Microsoft.UI.Xaml.dll!CUIElement::SetValue(const SetValueParams & args) Line 729	C++
 	Microsoft.UI.Xaml.dll!CFrameworkElement::SetValue(const SetValueParams & args) Line 235	C++
 	Microsoft.UI.Xaml.dll!CPanel::SetValue(const SetValueParams & args) Line 104	C++
 	Microsoft.UI.Xaml.dll!CStackPanel::SetValue(const SetValueParams & args) Line 894	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!DependencyObject_SetValue(CDependencyObject *) Line 2221	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!DirectUI::DependencyObject::SetValueCore(const SetValueParams &) Line 1034	C++
 	Microsoft.UI.Xaml.dll!DirectUI::DependencyObject::SetValueCore(const CDependencyProperty * dp, IInspectable * value, bool setEffectiveValueOnly, BaseValueSource baseValueSource) Line 1372	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!DirectUI::DependencyObject::SetValueCore(const CDependencyProperty *) Line 247	C++
 	Microsoft.UI.Xaml.dll!DirectUI::DependencyObject::SetValueByKnownIndex(KnownPropertyIndex nPropertyIndex, IInspectable * pValue) Line 1107	C++
 	Microsoft.UI.Xaml.dll!DirectUI::FrameworkElementGenerated::put_DataContext(IInspectable * pValue) Line 123	C++
 	Microsoft.UI.Xaml.Controls.dll!winrt::impl::consume_Microsoft_UI_Xaml_IFrameworkElement<struct winrt::Microsoft::UI::Xaml::IFrameworkElement>::DataContext(struct winrt::Windows::Foundation::IInspectable const &)	Unknown
 	Microsoft.UI.Xaml.Controls.dll!ViewManager::GetElementFromElementFactory()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!ViewManager::GetElement()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!RepeaterLayoutContext::GetOrCreateElementAtCore(int,enum winrt::Microsoft::UI::Xaml::Controls::ElementRealizationOptions const &)	Unknown
 	Microsoft.UI.Xaml.Controls.dll!winrt::impl::produce<VirtualizingLayoutContext,winrt::Microsoft::UI::Xaml::Controls::IVirtualizingLayoutContextOverrides>::GetOrCreateElementAtCore()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!winrt::impl::produce<VirtualizingLayoutContext,winrt::Microsoft::UI::Xaml::Controls::IVirtualizingLayoutContext>::GetOrCreateElementAt2()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!FlowLayoutAlgorithm::Generate(enum FlowLayoutAlgorithm::GenerateDirection,int,struct winrt::Windows::Foundation::Size const &,double,double,unsigned int,bool,class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> > const &)	Unknown
 	Microsoft.UI.Xaml.Controls.dll!FlowLayoutAlgorithm::Measure(struct winrt::Windows::Foundation::Size const &,struct winrt::Microsoft::UI::Xaml::Controls::VirtualizingLayoutContext const &,bool,double,double,unsigned int,enum ScrollOrientation const &,bool,class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> > const &)	Unknown
 	Microsoft.UI.Xaml.Controls.dll!StackLayout::MeasureOverride()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!winrt::impl::produce<VirtualizingLayout,winrt::Microsoft::UI::Xaml::Controls::IVirtualizingLayoutOverrides>::MeasureOverride()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!winrt::impl::produce<Layout,winrt::Microsoft::UI::Xaml::Controls::ILayout>::Measure()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!ItemsRepeater::MeasureOverride()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!winrt::impl::produce<ItemsRepeater,winrt::Microsoft::UI::Xaml::IFrameworkElementOverrides>::MeasureOverride()	Unknown
 	[Inline Frame] Microsoft.UI.Xaml.dll!DirectUI::FrameworkElementGenerated::MeasureOverrideProtected(ABI::Windows::Foundation::Size) Line 1029	C++
 	Microsoft.UI.Xaml.dll!DirectUI::FrameworkElement::MeasureOverrideFromCore(CFrameworkElement * nativeTarget, float inWidth, float inHeight, float * outWidth, float * outHeight) Line 246	C++
 	Microsoft.UI.Xaml.dll!CFxCallbacks::FrameworkElement_MeasureOverride(CFrameworkElement * nativeTarget, float inWidth, float inHeight, float * outWidth, float * outHeight) Line 753	C++
 	Microsoft.UI.Xaml.dll!CFrameworkElement::MeasureCore(XSIZEF availableSize, XSIZEF & desiredSize) Line 1573	C++
 	Microsoft.UI.Xaml.dll!CUIElement::MeasureInternal(XSIZEF availableSize) Line 3982	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3842	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3892	C++
 	Microsoft.UI.Xaml.dll!CLayoutManager::UpdateLayout(unsigned int controlWidth, unsigned int controlHeight) Line 278	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!CLayoutManager::UpdateLayout() Line 225	C++
 	Microsoft.UI.Xaml.dll!CUIElement::UpdateLayout() Line 3618	C++
 	Microsoft.UI.Xaml.dll!CUIElement::BoundsTestEntry<XPOINTF>(const HitTestParams & hitTestParams, const XPOINTF & target, CBoundedHitTestVisitor * pCallback, bool canHitDisabledElements, bool canHitInvisibleElements) Line 13043	C++
 	Microsoft.UI.Xaml.dll!CUIElement::HitTestEntry(const HitTestParams & hitTestParams, XPOINTF hitPoint, bool canHitMultipleElements, bool canHitDisabledElements, bool canHitInvisibleElements, CHitTestResults * pHitElements) Line 2389	C++
 	Microsoft.UI.Xaml.dll!CUIElement::HitTestEntry(const HitTestParams & hitTestParams, XPOINTF hitPoint, bool canHitDisabledElements, bool ppHitElement, CUIElement * *) Line 2363	C++
 	Microsoft.UI.Xaml.dll!CCoreServices::HitTest(XPOINTF ptHit, CDependencyObject * pHitTestRoot, CDependencyObject * * ppVisualHit, bool hitDisabledElement) Line 4474	C++
 	Microsoft.UI.Xaml.dll!ContentRootInput::PointerInputProcessor::HitTestHelper(XPOINTF ptHit, CDependencyObject * pHitTestRoot, CDependencyObject * * ppVisualHit) Line 968	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!ContentRootInput::PointerInputProcessor::HitTestWithLightDismissAwareness(xref_ptr<CDependencyObject> & message, XPOINTF) Line 1010	C++
 	Microsoft.UI.Xaml.dll!ContentRootInput::PointerInputProcessor::ProcessPointerInput(InputMessage * pMsg, int * handled) Line 250	C++
 	Microsoft.UI.Xaml.dll!CInputServices::ProcessInput(InputMessage * pMsg, CContentRoot * contentRoot, int * handled) Line 801	C++
 	Microsoft.UI.Xaml.dll!CCoreServices::ProcessInput(InputMessage * pMessage, CContentRoot * contentRoot, int * fHandled) Line 944	C++
 	Microsoft.UI.Xaml.dll!CXcpBrowserHost::HandleInputMessage(unsigned int uMsg, MsgPacket * pMsgPack, CContentRoot * contentRoot, bool & fHandled) Line 1179	C++
 	Microsoft.UI.Xaml.dll!CJupiterControl::HandlePointerMessage(unsigned int uMsg, unsigned int wParam, long lParam, CContentRoot * contentRoot, ABI::Windows::UI::Input::IPointerPoint * pointerPoint, ABI::Windows::UI::Core::IPointerEventArgs * pointerArgs) Line 650	C++
 	Microsoft.UI.Xaml.dll!CJupiterWindow::OnIslandPointerMessage(unsigned int uMsg, CContentRoot * contentRoot, ABI::Windows::UI::Core::IPointerEventArgs * args) Line 1295	C++
 	Microsoft.UI.Xaml.dll!CXamlIslandRoot::InjectPointerMessage(unsigned int msg, ABI::Windows::UI::Core::IPointerEventArgs * args) Line 521	C++
 	Microsoft.UI.Xaml.dll!CXamlIslandRoot::OnIslandPointerMoved(IInspectable * e, ABI::Windows::UI::Core::IPointerEventArgs *) Line 464	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!CXamlIslandRoot::SubscribeToPointerInputObserverEvents::__l27::<lambda_e2145e005effdb03dacdc93f97610bcf>::operator()(ABI::Microsoft::UI::Input::IPointerInputObserver *) Line 1279	C++
 	Microsoft.UI.Xaml.dll!Microsoft::WRL::Details::DelegateArgTraits<long (__stdcall ABI::Windows::Foundation::ITypedEventHandler_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Microsoft::UI::Input::PointerInputObserver *,ABI::Microsoft::UI::Input::IPointerInputObserver *>,ABI::Windows::Foundation::Internal::AggregateType<ABI::Windows::UI::Core::PointerEventArgs *,ABI::Windows::UI::Core::IPointerEventArgs *>>::*)(ABI::Microsoft::UI::Input::IPointerInputObserver *,ABI::Windows::UI::Core::IPointerEventArgs *)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,ABI::Windows::Foundation::ITypedEventHandler<ABI::Microsoft::UI::Input::PointerInputObserver *,ABI::Windows::UI::Core::PointerEventArgs *>,Microsoft::WRL::FtmBase>,<lambda_e2145e005effdb03dacdc93f97610bcf> &,1,ABI::Microsoft::UI::Input::IPointerInputObserver *,ABI::Windows::UI::Core::IPointerEventArgs *>::Invoke(ABI::Microsoft::UI::Input::IPointerInputObserver * <args_0>, ABI::Windows::UI::Core::IPointerEventArgs * <args_1>) Line 245	C++
 	Microsoft.UI.Input.dll!Microsoft::WRL::Details::DelegateArgTraits<long (__stdcall Windows::Foundation::ITypedEventHandler_impl<Windows::Foundation::Internal::AggregateType<Microsoft::UI::Input::PointerInputObserver *,Microsoft::UI::Input::IPointerInputObserver *>,Windows::Foundation::Internal::AggregateType<Windows::UI::Core::PointerEventArgs *,Windows::UI::Core::IPointerEventArgs *>>::*)(Microsoft::UI::Input::IPointerInputObserver *,Windows::UI::Core::IPointerEventArgs *)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,Windows::Foundation::ITypedEventHandler<Microsoft::UI::Input::PointerInputObserver *,Windows::UI::Core::PointerEventArgs *>,Microsoft::WRL::FtmBase>,<lambda_07255e26298e7bfb5ddf912aec68f900>,-1,Microsoft::UI::Input::IPointerInputObserver *,Windows::UI::Core::IPointerEventArgs *>::Invoke()	Unknown
 	Microsoft.UI.Input.dll!Microsoft::WRL::InvokeTraits<-2>::InvokeDelegates<class <lambda_0f7ed10ea9bd78fd5ccc52048e23d277>,struct Windows::Foundation::ITypedEventHandler<class Microsoft::UI::Input::KeyboardInput *,class Windows::UI::Core::CharacterReceivedEventArgs *> >(class <lambda_0f7ed10ea9bd78fd5ccc52048e23d277>,class Microsoft::WRL::Details::EventTargetArray *,class Microsoft::WRL::EventSource<struct Windows::Foundation::ITypedEventHandler<class Microsoft::UI::Input::KeyboardInput *,class Windows::UI::Core::CharacterReceivedEventArgs *>,struct Microsoft::WRL::InvokeModeOptions<-2> > *)	Unknown
 	Microsoft.UI.Input.dll!Microsoft::WRL::EventSource<struct Windows::Foundation::ITypedEventHandler<class Microsoft::UI::Input::FocusObserver *,class Microsoft::UI::Input::FocusChangedEventArgs *>,struct Microsoft::WRL::InvokeModeOptions<-2> >::InvokeAll<class FocusObserverWinRT::Api *,class FocusChangedEventArgs *>(class FocusObserverWinRT::Api *,class FocusChangedEventArgs *)	Unknown
 	Microsoft.UI.Input.dll!Microsoft::WRL2::ContextSession::LeaveSession_Callback<<lambda_1f19750b936c004a60173d14097a51ab>>()	Unknown
 	Microsoft.UI.Input.dll!PointerInputObserverWinRT::OnPointerMovedMessage_Callback(struct WindowsMessageDeliveryMessage *)	Unknown
 	Microsoft.UI.Input.dll!PointerInputObserverWinRT::OnWindowMessage(struct WindowsMessageDeliveryMessage *)	Unknown
 	Microsoft.UI.Input.dll!WindowsMessageDeliveryInputObject::Private::OnWindowMessage(struct WindowsMessageDeliveryMessage *)	Unknown
 	Microsoft.UI.Input.dll!<lambda>(void)()	Unknown
 	Microsoft.UI.Input.dll!std::_Func_class<enum InputSiteIterationDecision,class Microsoft::WRL::ComPtr<class BaseInputObjectWinRT> const &>::operator()(class Microsoft::WRL::ComPtr<class BaseInputObjectWinRT> const &)	Unknown
 	Microsoft.UI.Input.dll!InputSiteWinRT::ForEachAttachedObject(class std::function<enum InputSiteIterationDecision > const &)	Unknown
 	Microsoft.UI.Input.dll!WindowsMessageDeliveryInputSiteWinRT::OnWindowMessage(struct WindowsMessageDeliveryMessage *)	Unknown
 	Microsoft.UI.Input.dll!IslandInputSiteWinRTBase::OnWindowMessage(struct WindowsMessageDeliveryMessage *)	Unknown
 	Microsoft.UI.Input.dll!WindowsMessageDeliveryInputSiteWinRT::Private::OnWindowMessage(struct WindowsMessageDeliveryMessage *)	Unknown
 	Microsoft.UI.Input.dll!WindowsMessageDeliveryAdapter::ProcessWindowMessage(struct HWND__ *,unsigned int,unsigned int,long)	Unknown
 	Microsoft.UI.Input.dll!WindowsMessageDeliveryAdapter::StaticSubclassWndProc(struct HWND__ *,unsigned int,unsigned int,long)	Unknown
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	user32.dll!_DispatchMessageW@4()	Unknown
 	Microsoft.UI.Xaml.dll!DirectUI::FrameworkApplication::ProcessEvents() Line 1191	C++
 	Microsoft.UI.Xaml.dll!DirectUI::FrameworkApplication::StartDesktop() Line 215	C++
 	Microsoft.UI.Xaml.dll!DirectUI::FrameworkApplicationFactory::Start(ABI::Microsoft::UI::Xaml::IApplicationInitializationCallback * pCallback) Line 713	C++
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStatics.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	App1.dll!App1.Program.Main(string[] args) Line 26	C#
 	[Native to Managed Transition]	
 	hostpolicy.dll!788b1670()	Unknown
 	hostpolicy.dll![Frames below may be incorrect and/or missing, no symbols loaded for hostpolicy.dll]	Unknown
 	hostpolicy.dll!788c17cf()	Unknown
 	hostpolicy.dll!788aa86a()	Unknown
 	hostfxr.dll!7890e296()	Unknown
 	hostfxr.dll!7890f883()	Unknown
 	hostfxr.dll!78910916()	Unknown
 	hostfxr.dll!7890f9ab()	Unknown
 	hostfxr.dll!7890d1c7()	Unknown
 	App1.exe!0090a659()	Unknown
 	App1.exe!0090a8d6()	Unknown
 	App1.exe!0090beac()	Unknown
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

**Comment by alwu-msft** [comment]
Thanks for the report! The fix for this will be included in the next WinUI 3 Preview.
