### ISSUE TITLE
WebView2 doesn't expose NewWindowRequested event

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#3013]
**Describe the bug**
The `NewWindowRequested` event from [WebView (1)](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewnewwindowrequestedeventargs) and the underlying [WebView2 API](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#add_newwindowrequested) is not exposed to the XAML based WebView2. ☹

**Expected behavior**
`NewWindowRequested` event is on WebView2 XAML control.

**Version Info**
NuGet package version: WinUI 3 Preview2

**Comment by StephenLPeters** [comment]
Not sure if this is a feature request or a bug. @adambarlow

**Comment by michael-hawker** [comment]
@StephenLPeters it's exposed on the underlying WebView2 C++ API, it's just missing in the projection/wrapper in WinUI 3. So it's both? Maybe we call it an unimplemented requirement from the spec? 😂

**Comment by adambarlow** [comment]
The WinRT wrapper for the WebView2 is still in the works. We hope to have something to share soon. But yes, it's neither bug nor feature request as it is in plan for delivery.

**Comment by codendone** [comment]
The work to expose the CoreWebView2 WinRT APIs with its full capabilities is starting now ([internal task](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/27381901)). And, we have another more specific task to ensure NewWindowRequested works ([internal task](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/21173937)).

**Comment by DmitriyKomin** [comment]
With the recently released [WinUI Preview3](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.newwindowrequested?view=WebView2-dotnet-1.0.674-prerelease), this is now exposed as [WebView2.CoreWebView2.NewWindowRequested](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.newwindowrequested?view=WebView2-dotnet-1.0.674-prerelease).
