### ISSUE TITLE
Will WinUI 3.0 ever support unpackaged apps?

### ISSUE THREAD

**Issue by rcohn** [microsoft/microsoft-ui-xaml#3014]
Hello -

From what I am seeing, there seem to be no formal plans to support unpackaged apps.  

This proposal addresses that: [Proposal: Deploy WinUI 3 runtime using Framework Packages for Packaged and Unpackaged apps #2767](https://github.com/microsoft/microsoft-ui-xaml/issues/2767).

Can anybody tell me if there are plans for WinUI 3.0 .NET support to be part of standard Windows updates (which would seem to obviate the need for packaging WinUI 3.0 apps)?

Thanks very much.

**Comment by StephenLPeters** [comment]
@ryandemopoulos and @MikeHillberg FYI

**Comment by jonasnordlund** [comment]
I have wondered the same but I assume so given the [WinUI Library Roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) released since you asked your question, although this will apparently be a post-3.0 release.

**Comment by glowtape** [comment]
I tried to figure out what the plan is nowadays, just to find out that it's been deprioritized and postponed to the very least release 3.1

I'm not entirely sure what alternate reality Microsoft is living in, but one thing I don't see is an abundance of ~~WinRT~~ WinUI apps in the wild. And I can tell you at least one reason why, and that's the lack of unpackaged apps. Endless requests for this go back to the release of Windows 8.

Personally I have to start a bunch of new applications, and I was wanting to advocate going .NET 5.0 and WinUI 3.0, but need the ability to deploy them unpackaged. Now that it's been "deprioritized", again I suppose, I'm just throwing the towel on this and might as well considering going with the grain and go with Node.js and all that.

**Comment by ryandemopoulos** [comment]
Unpackaged support remains something we intend on adding.  As @jonasnordlund pointed out, we expect to add this post-3.0--probably later this year alongside full Islands support.  That's the soonest we'd be able to introduce it, given the other priorities we're working on now.

Happy to answer any additional question you have; I'll close this Issue for now since I think the original question has been answered.

**Comment by rcohn** [comment]
Thanks for the responses, all.  For now, I'm going with WPF + xaml islands.
