### ISSUE TITLE
Discussion: Does UWP map control support GeoJson?

### ISSUE THREAD

**Issue by sukesh-ak** [microsoft/microsoft-ui-xaml#3018]
# Discussion: Does UWP map control support GeoJson?

Does UWP map control support GeoJson? If not when do we expect to have this support added?

## Related Links

Bing maps v8 web control already supports it. [Link here](https://docs.microsoft.com/en-us/bingmaps/v8-web-control/modules/geojson-module/)

**Comment by StephenLPeters** [comment]
@MikeHillberg who can we ask about the map control?

**Comment by YuliKl** [comment]
The WinUI team does not own MapControl directly. I received some clarification from the team that does: there is currently no built-in support for GeoJson, this would be a new feature request. In the meantime, you should be able to parse the GeoJson and add MapElements yourself.

**Comment by sukesh-ak** [comment]
> The WinUI team does not own MapControl directly. I received some clarification from the team that does: there is currently no built-in support for GeoJson, this would be a new feature request. In the meantime, you should be able to parse the GeoJson and add MapElements yourself.

Thank you @YuliKl 
Is there a repo for MapControl where I can open a suggestion to track it?

**Comment by StephenLPeters** [comment]
> > The WinUI team does not own MapControl directly. I received some clarification from the team that does: there is currently no built-in support for GeoJson, this would be a new feature request. In the meantime, you should be able to parse the GeoJson and add MapElements yourself.
> 
> Thank you @YuliKl
> Is there a repo for MapControl where I can open a suggestion to track it?

I think [Project Reunion](https://github.com/microsoft/ProjectReunion) is probably the best place
