### ISSUE TITLE
Repeatedly building and deploying causes deployment errors due to file being held by another process error.

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#3020]
Repeatedly building and running a winui desktop C# app ends up with a build failure sometimes. You can recover by restarting visual studio. Also, I notice that sometimes rebuilding and F5 from visual studio does not terminate the app instance that is already running.

Here is the error message when it fails.
```
Updating the layout... 
Copying files: Total <1 mb to layout... 
DEP1000: Cannot copy file "BlankPreview2CsDesktopApp\BlankPreview2CsDesktopApp\bin\x86\Debug\net5.0\win-x86\BlankPreview2CsDesktopApp\App.xbf" to layout "BlankPreview2CsDesktopApp\BlankPreview2CsDesktopApp (Package)\bin\x86\Debug\AppX\BlankPreview2CsDesktopApp\App.xbf". IOException - The process cannot access the file 'BlankPreview2CsDesktopApp\BlankPreview2CsDesktopApp (Package)\bin\x86\Debug\AppX\BlankPreview2CsDesktopApp\App.xbf' because it is being used by another process. [0x80070020] 
3>Deployment of the application to the target device failed 
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ========== 
========== Deploy: 0 succeeded, 1 failed, 0 skipped ========== 
```
NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

**Comment by fabiant3** [comment]
@ranjeshj - what is the process holding onto your build? Process Explorer will tell ya.

**Comment by fabiant3** [comment]
per @Scottj1s https://msbuildlog.com/ should help generate a binlog which should help understand if this is a makepri regression.

**Comment by ranjeshj** [comment]
It looks like the running app instance is holding that file. I was able to get a consistent repro. I build and run using Ctrl+F5 and the app is running without debugging. Then I make a change to the markup and do Ctrl+F5, it gives the error. If I do another Ctrl+F5, VS terminates the running app and launches again with latest changes. 

Its a bit more rare to get into the situation where it just stops deploying altogether. I can try to get more information once I get into that state.

**Comment by Scottj1s** [comment]
this sounds like a VS issue then - especially if the third Ctrl+F5 terminates the app (why doesn't the second one?)

**Comment by ranjeshj** [comment]
> this sounds like a VS issue then - especially if the third Ctrl+F5 terminates the app (why doesn't the second one?)

Exactly.

**Comment by robloo** [comment]
I get similar errors from time-to-time when not using WinUI 3.0 previews. These errors have been around for as long as UWP itself. I definitely think this is a VS-related issue.

**Comment by evelynwu-msft** [comment]
Issues relating to Visual Studio should be filed through VS itself: https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022.
