### ISSUE TITLE
where is ItemsRepeater control in toolbox? 

### ISSUE THREAD

**Issue by jsman123** [microsoft/microsoft-ui-xaml#3027]
Hello. I'm using WIUI 2.4, can't find out ItemsRepeater control in toolbox, see only ItemsControl and ItemsPresenter.

Do I need to install something others to get the ItemsControl? 

thanks!

**Comment by StephenLPeters** [comment]
@jevansaks and/or @MikeHillberg I don't know how the VisualStudio ToolBox feature works. Is there a step we are missing when publishing Winui 2.x to enable this?

**Comment by jevansaks** [comment]
It's a nuget feature. You include a specially named XML file and put it in the right place in the nupkg and then the gallery will show items from it. Our config file is here:
https://github.com/microsoft/microsoft-ui-xaml/blob/master/build/NuSpecs/VisualStudioToolsManifest.xml

And then if you want to add icons, they come from the design dll that's built and also included in the nupkg. It's here:
https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Microsoft.UI.Xaml.Design/Microsoft.UI.Xaml.Design.csproj#L60

**Comment by jevansaks** [comment]
@StephenLPeters documentation about the nuget feature is here: https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls#add-toolboxassets-pane-support-for-xaml-controls

**Comment by StephenLPeters** [comment]
> @StephenLPeters documentation about the nuget feature is here: https://docs.microsoft.com/en-us/nuget/guides/create-ui-controls#add-toolboxassets-pane-support-for-xaml-controls

@jevansaks thanks! @jsman123 We haven't included ItemsRepeater, and a couple of other controls in the appropriate manifest. Thank you for bringing this to our attention!

**Comment by chingucoding** [comment]
@StephenLPeters @ranjeshj Mind if I update the file to include the (new) WinUI controls? It seems there are a few missing.

**Comment by StephenLPeters** [comment]
> @StephenLPeters @ranjeshj Mind if I update the file to include the (new) WinUI controls? It seems there are a few missing.

That would be awesome!
