### ISSUE TITLE
Bug/Feature Request: NavigationView FooterMenu - No overflow handling for Top mode

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#3029]
**Describe the bug**
With the addition of the FooterMenu from Issue #375 and PR #1997, the corner case of having an overflow of footer menu items in a top mode NavigationView was not handled. Currently, if you add more footer items than can fit within the viewport of the NavigationView in top mode, the items will render "off-screen" - they aren't visible and they aren't able to be scrolled to.  

**Steps to reproduce the bug**

1. Set PaneDisplayMode = Top on a NavigationView
2. Add multiple items to FooterMenuItems until they can't all fit within the NavigationView
3. See that those overflowing items are inaccessible to the user. 

**Expected/Suggested behavior**
There should either be a ScrollViewer that horizontally scrolls all of the overflow FooterMenuItems or there should be a flyout that holds the overflow items. Implementation/behavior of this feature is still up for discussion.

**Comment by ad1Dima** [comment]
Some screenshots for context
![image](https://user-images.githubusercontent.com/3244664/89387432-abdad680-d72c-11ea-8b45-b2a7c1bcb4a1.png)
![image](https://user-images.githubusercontent.com/3244664/89387464-b4331180-d72c-11ea-9662-321d4f800a8c.png)
![image](https://user-images.githubusercontent.com/3244664/89387484-bb5a1f80-d72c-11ea-9c63-3117cc74eabd.png)
