### ISSUE TITLE
Null Reference Crash in TwoPaneView::ActualWidth

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#3030]
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/26111242?src=WorkItemMention&src-action=artifact_link)

The call stack makes it look like the size changed event handler isn't being detached.

**Comment by chingucoding** [comment]
Would creating a PR that detaches the event handler once the TwoPaneView get's collected be sufficient to close this issue?

**Comment by StephenLPeters** [comment]
That would be my first guess, but I the internal issue has more context. @Teap FYI
