### ISSUE TITLE
Initials in PersonPicture are wrong for LATAM and other countries/culture that use more than 1 word for "last name'

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#3031]
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/27686030?src=WorkItemMention&src-action=artifact_link)

"If last name has more than 1 word, the login screen in WCOS (10X) shows the initial of the first name followed by the initial of the last word of the last name, which is completely incorrect for LATAM (and other countries/cultures/people that have multi-word "last name"). For context, in ALL LATAM, pretty much everyone has at least 2 words in their last name, separated by a space.
​
In my case (for my MSA dogfood account):
First Name: Guillermo
Middle Name: Enrique
Last Name: Rueda Quintero
Tile Initials (expected): GR
Tile Initials (actual): GQ

The expectation is that the initial of the "last name" is the beginning of the last name, not a letter from somewhere else, independently of dashes, spaces, or other special characters in last names."

**Comment by Felix-Dev** [comment]
I can take a look at this.

**Comment by StephenLPeters** [comment]
@YuliKl FYI.

@Felix-Dev you can take a look, however I worry that the behavior of choosing the R over the Q in the example would not be ubiquitous for all cultures.  I think we need to reach out to the original team that authored this control for their input. (It wasn't the winui team originally)

**Comment by Felix-Dev** [comment]
@StephenLPeters Should I wait then until we heard from the original team?

**Comment by StephenLPeters** [comment]
I think @YuliKl is reaching out to them. I think there needs to be some research done into what different cultures expect their initials to be before we can be confident what the right solution for this issue is.
