### ISSUE TITLE
Question: IMultiValueConverter support is missing ?

### ISSUE THREAD

**Issue by VijayanRamachandran** [microsoft/microsoft-ui-xaml#3033]
Hi,

I am currently trying out some prototypes creating custom controls in WinUI.

During prototype I noticed that there is support for IValueConverter  ( available in Microsoft.UI.Xaml.Data ) but support or implementation is missing for **IMultiValueConverter**

Support for IMultiValueConverter will be available in near WinUI Preview release ?
Untill then any alternative shall be tried it out in our end ( if you could suggest and if possible with some samples ) ?

I am using right now 
**VS**             => Version 16.7.0 Preview 5.0
**.Net SDK**   => dotnet-sdk-5.0.100-preview.4.20268.1-win-x64 / dotnet-sdk-5.0.100-preview.4.20268.1-win-x86

Thanks in advance.

**Comment by Felix-Dev** [comment]
@VijayanRamachandran The recommended way in WinUI is to use [function binding](https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings).

**Comment by StephenLPeters** [comment]
@VijayanRamachandran does Function binding solve your use case?

**Comment by StephenLPeters** [comment]
As a note, x:bind is not available in control templates so function binding is not possible from a template.

**Comment by VijayanRamachandran** [comment]
@Felix-Dev 

Thanks for information. As you mentioned i will check function binding.

@StephenLPeters 

Let me check that Stephen in our end and get  back here ( probably after another 2 to 3 days ) and thanks for the hint about x:bind not compatible with ControlTemplate.
