### ISSUE TITLE
Question: XamlReader and XamlWriter Support is missing ?

### ISSUE THREAD

**Issue by VijayanRamachandran** [microsoft/microsoft-ui-xaml#3034]
Hi,

I am currently trying out some prototypes creating custom controls in WinUI.

During prototype I noticed that support is missing for XamlReader and XamlWriter. 
( In WPF we could see that support for XamlReader and XamlWriter is available in System.Windows.Markup. )

Support for XamlReader and XamlWriter will be available in near WinUI Preview release ?

I am using right now
VS => Version 16.7.0 Preview 5.0
.Net SDK => dotnet-sdk-5.0.100-preview.4.20268.1-win-x64 / dotnet-sdk-5.0.100-preview.4.20268.1-win-x86

Thanks in advance.

**Comment by StephenLPeters** [comment]
I think XamlReader is available.. @fabiant3 ?

**Comment by MikeHillberg** [comment]
Yes, there is a [XamlReader](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Markup.XamlReader). There's no plan for a feature to serialize to Xaml (XamlWriter).

**Comment by MarkAllan007** [comment]
This is a less than poor answer.
- Where is the XamlWriter link that explains the XamlWriter class is not planned?
- Where is documentation that explains why and what is an alternative to using XamlWriter class?
- One goal is to write documentation that helps developers hit the ground running. 
- One goal is to provide tech support that helps developers hit the ground running.
