### ISSUE TITLE
Question: Microsoft.Xaml.Behaviors.Wpf => Equivalent WinUI Nuget ???

### ISSUE THREAD

**Issue by VijayanRamachandran** [microsoft/microsoft-ui-xaml#3037]
Hi,

I am currently doing some prototypes migrating custom controls available in our end from WPF to WinUI.

During prototype I noticed that, in our end there are some WPF custom behaviour types inheriting from **Microsoft.Xaml.Behaviors.Behavior<>** ( available in Nuget **Microsoft.Xaml.Behaviors.Wpf** ) and when i try to migrate those custom behaviours to WinUI i am not seeing the equivalent implemenation or Nuget in WinUI.

These implementations will be available soon in near WinUI Preview release ?

I am using right now
VS => Version 16.7.0 Preview 5.0
.Net SDK => dotnet-sdk-5.0.100-preview.4.20268.1-win-x64 / dotnet-sdk-5.0.100-preview.4.20268.1-win-x86

Thanks in advance.

**Comment by robloo** [comment]
https://blogs.windows.com/windowsdeveloper/2015/11/30/xaml-behaviors-open-source-and-on-uwp/

**Comment by StephenLPeters** [comment]
@VijayanRamachandran does rob's response satisfy your requirement?

**Comment by VijayanRamachandran** [comment]
@robloo 

Thanks for quick feedback. I will go through the link which you shared.

@StephenLPeters 

I will check the link and come back here Stephen in case if there is any more doubts related to it. 

Thanks for the clarification.

**Comment by ganesanviji** [comment]
Hi

Is the Microsoft.Xaml.Behaviors.WinUI.Managed NuGet package supporting for the WinUI UWP application. because I can't install this NuGet package in the WinUI UWP application. Please let me know whether this NuGet support or not for WinUI UWP. if not, let me know when will it be supported

**Comment by ganesanviji** [comment]
Hi 
Any update on this?
