### ISSUE TITLE
Question: DependencyPropertyKey missing ?

### ISSUE THREAD

**Issue by VijayanRamachandran** [microsoft/microsoft-ui-xaml#3040]
Hi,

I am currently doing some prototypes migrating custom controls available in our end from WPF to WinUI.

During prototype I noticed that, in our end there are some WPF custom controls using **DependencyPropertyKey** ( available in System.Windows ) but equivalent implementation for WinUI is missing. 
( Below is the sample code snippet about how we are using DependencyPropertyKey )

These implementations will be available soon in near WinUI Preview release ?

I am using right now
**VS**           => Version 16.7.0 Preview 5.0
**.Net SDK** => dotnet-sdk-5.0.100-preview.4.20268.1-win-x64 / dotnet-sdk-5.0.100-preview.4.20268.1-win-x86

Thanks in advance.

**Code Snippet**

private static readonly DependencyPropertyKey IsXyzPropertyKey = 
					      DependencyProperty.RegisterReadOnly("IsXyz", typeof(bool), typeof(CustomControlExample), new PropertyMetadata(false));

public static readonly DependencyProperty IsXyzProperty = IsMultipleCalendarPropertyKey.DependencyProperty;

public bool IsMultipleCalendar 
{ 
    get { 
	   return (bool)GetValue(IsXyzProperty); 
        } 

    protected set { 
                     SetValue(IsXyzPropertyKey, value); 
		  } 
}

**Comment by robloo** [comment]
Same comment as here: https://github.com/microsoft/microsoft-ui-xaml/issues/3041#issuecomment-668695595

**Comment by VijayanRamachandran** [comment]
@robloo @StephenLPeters 

Thanks for the clarification and assignment.

**Comment by chrisglein** [comment]
Have also left comments on #3074, #3073, #3041, please spruce this up with some scenarios/priorities and such by going through our feature proposal process. Sorry for the extra red tape, but it helps us frame these as changes in plan, not questions.
