### ISSUE TITLE
Question: DependencyProperty => RegisterReadOnly method missing ???

### ISSUE THREAD

**Issue by VijayanRamachandran** [microsoft/microsoft-ui-xaml#3041]
Hi,

I am currently doing some prototypes migrating custom controls available in our end from WPF to WinUI.

During prototype I noticed that, in our end there are some WPF custom controls using DependencyProperty ( from System.Windows ) and the equivalent type DependencyProperty is available in WinUI ( from Microsoft.UI.Xaml ).

WPF DependencyProperty contains both Register and RegisterReadOnly method whereas WinUI DependencyProperty **doesnot** contain **RegisterReadOnly** method.

These implementations will be available soon in near WinUI Preview release ?

I am using right now
VS => Version 16.7.0 Preview 5.0
.Net SDK => dotnet-sdk-5.0.100-preview.4.20268.1-win-x64 / dotnet-sdk-5.0.100-preview.4.20268.1-win-x86

**Code Snippet**

private static readonly DependencyPropertyKey IsXyzPropertyKey = 
					      DependencyProperty.RegisterReadOnly("IsXyz", typeof(bool), typeof(CustomControlExample), new PropertyMetadata(false));

public static readonly DependencyProperty IsXyzProperty = IsMultipleCalendarPropertyKey.DependencyProperty;

public bool IsMultipleCalendar 
{ 
    get { 
	   return (bool)GetValue(IsXyzProperty); 
        } 

    protected set { 
                     SetValue(IsXyzPropertyKey, value); 
		  } 
}

Thanks.

**Comment by robloo** [comment]
I ran across the same issue a while ago and ended up asking in the Microsoft Docs repo at the time:

https://github.com/MicrosoftDocs/windows-uwp/issues/1878

Read-only dependency properties are especially important to implement collections. However, in UWP Collection-Type Dependency Properties are not supported. In fact, in UWP `SelectedItems` isn't even a DP which is really bad architecture. All of this needs to be tackled at once IMO to bring the DP system in-line with WPF.

Like you I ran across this issue with custom controls.

**Comment by MikeHillberg** [comment]
There's no near-term plan to add RegisterReadOnly. Agreed it's a useful feature, and should be used for some existing properties like [TwoPaneView.Mode](https://docs.microsoft.com/uwp/api/Microsoft.UI.Xaml.Controls.TwoPaneView.Mode) and [MenuBar.Items](https://docs.microsoft.com/uwp/api/Microsoft.UI.Xaml.Controls.MenuBar.Items).

**Comment by robloo** [comment]
> There's no near-term plan to add RegisterReadOnly. Agreed it's a useful feature, and should be used for some existing properties like TwoPaneView.Mode and MenuBar.Items.

Thanks for the feedback. In my experience, if there is no near-term plan then there is no plan to do it and it likely won't happen. Honestly, doing it during WinUI 3.0 is really the best shot as well since it's a breaking change to do it properly and add to existing controls.

**Comment by robloo** [comment]
@ranjeshj @StephenLPeters @ryandemopoulos

I'll state this here but it could apply to many different issues. @VijayanRamachandran and all the issues he's filed recently is a good illustration of the problems many of us went through a while ago during the initial migration from WPF to UWP. This is now happening again as devs and companies are looking at going to WinUI. Missing features like this left a really bad taste for devs and it's one of the reasons UWP was never successful. Honestly, the goal needs to be to close ALL missing functionality with WPF in areas such as these where the feature hasn't been reimplemented another way.

**Comment by chrisglein** [comment]
Seeing a bulk of UWP vs. WPF issues. For example #3074, #3073, #3040, and this. For all of these, these are totally valid requests. But we are coming at this from the perspective of moving UWP XAML out of of Windows into a separate thing. Changes to the UWP API have to be handled as such: changes. These changes have cost, so we need to be intentional about what we do when, so I'm sorry to ask that these asks all go through the proposal process but that's the way we handle asks and can weigh cost/benefit. I appreciate your situation and the effort you've put in so far to identify gaps in the platform.

**Comment by robloo** [comment]
Created feature-request here: https://github.com/microsoft/microsoft-ui-xaml/issues/3139
