### ISSUE TITLE
Two Pane View control not working as expected

### ISSUE THREAD

**Issue by assassin316** [microsoft/microsoft-ui-xaml#3043]
**Describe the bug**

According to the Microsoft documentation, it states the following for the Two Pane View:

     By default, Pane1Length is set to Auto and it sizes itself to fit its content. Pane2Length is set to * and it uses all the remaining space.
With the following code, I don't see that defualt behavior being applied. Am I missing some extra properties I need to explicitly set? My end goal is simply for Pane1 to always show on a Single screen device, and hide Pane2.

**Steps to reproduce the bug**
Use the following code in a UWP project referencing WinUI 2.4 nuget package:

```xml
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <muxc:TwoPaneView x:Name="MyTwoPaneView">
        <muxc:TwoPaneView.Pane1>
            <Grid x:Name="Pane1Root"
                  Background="Orange">
            </Grid>
        </muxc:TwoPaneView.Pane1>
        <muxc:TwoPaneView.Pane2>
            <Grid x:Name="Pane2Root"
                  Background="Green">
            </Grid>
        </muxc:TwoPaneView.Pane2>
    </muxc:TwoPaneView>
</Grid>
```

**Expected behavior**
According to the docs, default usage should be a master-detail setup:

![image](https://user-images.githubusercontent.com/17514380/89321540-1ae2fd00-d651-11ea-8ebb-b64e1c837a1f.png)

**Screenshots**

![twopane](https://user-images.githubusercontent.com/17514380/89321747-5087e600-d651-11ea-8496-0a416c0bd078.gif)

**Version Info**
**Microsoft.UI.Xaml 2.4.0, Windows 10 Pro, 1909**

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@teaP can you weigh in on the two pain view API surface? I think you need to set some of the PaneConfiguration properties, but looking at the API it isn't obvious to me

**Comment by StephenLPeters** [comment]
@predavid-zz FYI

**Comment by teaP** [comment]
Since Pane1 has no content or min width, Auto sizing gives it 0px of width in wide mode. If you add content or set MinWidth you will find that it appears when the window is wide enough.
