### ISSUE TITLE
Run as administrator crashes WinUI Desktop App

### ISSUE THREAD

**Issue by ParkhutRoman** [microsoft/microsoft-ui-xaml#3046]
Faulting application name: TYTYTY.exe, version: 1.0.0.0, time stamp: 0x5eda9993
Faulting module name: KERNELBASE.dll, version: 10.0.19041.423, time stamp: 0xed02c0bc
Exception code: 0xc000027b
Fault offset: 0x000000000010b3cc
Faulting process id: 0x6e34
Faulting application start time: 0x01d66a95fb1d5bdc
Faulting application path: F:\Work\net5\FWMonitor\TYTYTY\TYTYTY (Package)\bin\x64\Debug\AppX\TYTYTY\TYTYTY.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ce67f678-5617-444b-8207-72b6901c29e3
Faulting package full name: 48e80bab-2df9-4a42-9e48-3f67efd23e12_1.0.0.0_x64__q29dnkf5r4tp2
Faulting package-relative application ID: App

Crashes even blank WinUI Desktop app after UAP.
Crashes with 
```
<rescap:Capability Name="runFullTrust" />
<rescap:Capability Name="allowElevation" />
```
in Package.appxmanifest

`    <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />`

in app.manifest get the same result

With desktop netcoreapp3.1 in Package i dont have such problem.

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@llongley FYI

**Comment by abhi-msft** [comment]
Any update on this?

**Comment by mrjfalk** [comment]
I'm running into a similar issue in the Reunion 0.5 release. When pressing Debug in Visual Studio I get the UAC dialog, but after allowing that nothing happens (the debugger still seems to be attached though). But if I press "Break All" button it says "No processes are currently being debugged", so it's most likely crashed.

**Comment by DaZiYuan** [comment]
Encountered the same issue please fix it.

**Comment by FrankAtHexagon** [comment]
My team is also encountering the issue, which is preventing us from implementing functionality in Uno.

**Comment by ParkhutRoman** [comment]
I get around this problem by using Microsoft.WinUI(3.0.0-preview4.210210.4) in main program, and Microsoft.ProjectReunion.WinUI(0.5.7) in package (pure ProjectReunion 0.5-0.8 have the same problem with uac).
Idk why this works. 
Downside you cant use nuget CommunityToolkit and Microsoft.Xaml.Interactions (but it's easy to solve, just a monotonous job), but if you using some package witch relies on ProjectReunion.WinUI(0.5.7) and its not a open source - for now its dead end.

**Comment by ParkhutRoman** [comment]
Microsoft.ProjectReunion Version=0.8.0, fix all uac problems 
Windows 11 Pro 22000.1
You can use WindowsTemplateStudio and all run from the box with manifest edits for Administrator elevation.
Closed.

**Comment by DaZiYuan** [comment]
hi,@ParkhutRoman  can you provide a boilerplate about WINUI Administrator elevation?

I just tried again, it seems doesn't launch the WINUI window when I clicked the UAC

**Comment by ranjeshj** [comment]
@marb2000 as FYI

**Comment by ebt6a48uxua24rf4** [comment]
@abhi-msft @mrjfalk @FrankAtHexagon  @DaZiYuan 

see [the clarification here](https://github.com/microsoft/WindowsAppSDK/discussions/671#discussioncomment-1032396)  from Windows Engineer

>WinUI3 in an unpackaged app does not currently support elevation because the underlying tech to support unpackaged apps (Dynamic Dependencies) does not currently support elevation. That's due to a limitation of Packaged COM.

>This is an unpackaged app issue. Terminal is a packaged app so it doesn't need Dynamic Dependencies to use WinUI.

If you want the functionality, you can Upvote [Dynamic Dependencies doesn't support Elevation](https://github.com/microsoft/WindowsAppSDK/issues/567)  issue  in the Windows App SDK repo to help prioritize it.

**Comment by mrjfalk** [comment]
From the same issue mentioned in the previous comment it now also says it won't work in packaged apps either:

> actually WinUI 3 in packaged apps also does NOT support elevation. It's an OS-level issue, COM/WinRT doesn't allow per-user class registrations to be activated from an elevated process. Inbox APIs work when elevated, but WinAppSDK isn't inbox. We've fixed that in the OS in the next release.

(see https://github.com/microsoft/WindowsAppSDK/discussions/671#discussioncomment-1039294)

**Comment by GhostAndMoreGhosts** [comment]
> **if you're running Windows 11 Insider builds, you should be able to run a packaged WinUI 3 app in elevated mode. The OS-level bug fix should be in the latest Insider builds.**

> **Otherwise, this won't work for older versions of Windows (it's an OS-level issue, packaged apps running elevated cannot access non-inbox WinRT APIs -** that's why a WPF packaged app not using WinAppSDK works, but when you use WinAppSDK APIs, it doesn't work)
https://github.com/microsoft/WindowsAppSDK/issues/896#issuecomment-890005213

@mrjfalk
 **"packaged elevated WinUI 3 app issue"** got fixed in windows 11 insider builds. will be backported to windows 10 ? probably not.
**"for unpackaged elevated WinUI 3 app issue"** keep an eye on [Dynamic Dependencies doesn't support Elevation.](https://github.com/microsoft/WindowsAppSDK/issues/567)

**Comment by Sacwith** [comment]
is there any way to make overlay on top of always including start menu  windows in winui3 preview deskotop apart from uiAcess=true in appmanifest bcoz elivation wont support in winui3 ?
