### ISSUE TITLE
Checkbox border resource broken

### ISSUE THREAD

**Issue by rectified95** [microsoft/microsoft-ui-xaml#3051]
The resource controlling the checkbox border at rest and unchecked does not work - CheckBoxCheckBackgroundStrokeUnchecked.
Its peers: CheckBoxCheckBackgroundStrokeUncheckedPointerOver, and CheckBoxCheckBackgroundStrokeUncheckedPressed work properly. The result is that when I specify all 3, the border only appears when I hover over or press the checkbox.

XAML version: 2.3_2.32002

**Comment by StephenLPeters** [comment]
@rectified95 it would be super helpful if you could include the xaml you are using as well as some screen shots of the result.
