### ISSUE TITLE
Invoking an item in a secondary command's flyout does not close the command bar.

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#3052]
Repro in this gif: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7758786/89464252-0112ea00-d725-11ea-97cd-15461013d588.gif)

The 95% solution here is to, if the flyout is a menu flyout, recursively iterate through the children attaching the CommandBar close function to the MenuFlyoutItem's click event, the MenuFlyoutToggleItem's toggle event, and recursing on MenuFlyoutSubItem's

**Comment by chingucoding** [comment]
I would like to work on this issue, if nobody else is currently working on this.
