### ISSUE TITLE
MediaCapture: Window Closes but not Process

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/microsoft-ui-xaml#3058]
**Describe the bug**

This doesn't happen when `MediaCapture` is locally scoped, only when it's a member of my MainWindow.

```
struct MainWindow : MainWindowT<MainWindow>
    {
        ...
        Windows::Media::Capture::MediaCapture m_mediaCapture{};
    };
```

**Steps to reproduce the bug**

1. Run in Debug mode
2. Click on the close caption button

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview2.200713.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
Sometimes the debug output shows:
...
The thread 0x5b14 has exited with code 0 (0x0).
The thread 0x51d4 has exited with code 0 (0x0).
'App1.exe' (Win32): Loaded 'C:\Windows\SysWOW64\netutils.dll'.

**Comment by StephenLPeters** [comment]
I'm guessing this is a desktop app but I'm not sure.  @tom-huntington are you able to provide a repro app?

**Comment by tom-huntington** [comment]
Hi Stephen, yes its a desktop app. The bug only happens in debug mode. The process closes successfully when I start without debugging. Sorry I should have checked this first.

https://github.com/tom-huntington/MediaCaptureBug

The only changes to the template are:

```
#include "winrt/Windows.Media.Capture.h"
struct MainWindow : MainWindowT<MainWindow>
    {
        ...
    private:
        Windows::Media::Capture::MediaCapture m_mediaCapture{};
    };
```
