### ISSUE TITLE
Proposal: Add StandardUICommand 

### ISSUE THREAD

**Issue by lukasf** [microsoft/microsoft-ui-xaml#306]
# Proposal: Add StandardUICommand 

## Summary
The StandardUICommand class is very useful. But it is impossible to add this to apps targeting older Windows versions. Using StandardUICommands for newer Windows versions plus manual commands for older versions would cause lots of extra code. It could also lead to inconsistent UI between old an new, because manual translations, shortcuts, etc might be different from the ones in StandardUICommand. 

To be really useful, we need this class (along with XamlUICommand) in Microsoft.UI.Xaml. Only then it will be useful for a large number of apps.

### Mandatory:
- Support all values from StandardUICommandKind

### Optionally include more commands:

Not sure how MS selects which commands are available. These are just some ideas. Some of those items could only provide a common translation, maybe an icon, which IMHO is still helpful. Devs would have to fill missing properties (description, icon, shortcut), so it matches their app. Docs would have to mention which properties are filled for each value.

This must be aligned with MS internal strategy/roadmap for the class.

General:
- Search
- Select (multi select button, e.g. in photos app)
- Add
- Remove
- Export
- Import
- Edit
- Start
- Cancel
- OpenFile
- OpenFolder
- Enable
- Disable
- Activate
- Deactivate
- Clear

Note: Sometimes, having a button to enable/activate a function is appropriate, e.g. if that function triggers long running actions. For those cases, I'd prefer a button over a checkbox/switch.

Media:
- Cast To Device
- Shuffle
- Repeat
- Skip forward
- Skip backward
- Fast forward
- Fast backward
- Fullscreen
- Resize
- Equalizer

**Comment by YuliKl** [comment]
@lukasf, I completely agree with your sentiment and this request is already in plan for WinUI 3. I'll close this issue because we don't need to keep track of this class separately, this is simply a part of lifted Xaml that's already on our roadmap.
