### ISSUE TITLE
 error MSB4181: The "CompileXaml" task returned false but did not log

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#3067]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1125615/error-msb4181-the-compilexaml-task-returned-false.html)._

---
[severity:I'm frustrated, but able to complete my work] [regression] "worked-in:actual on July 9, 2020"
The studio breaks its teeth on this fragment:
```
<Button.Content>
    <StackPanel Orientation="Horizontal">
        <TextBlock FontSize="20" Text="⏱" />
        <ProgressRing Name="StopwatchIndic" Margin="5,0,0,0" IsActive="True" Visibility="Visible" />
    </StackPanel>
```
When you try to assemble a project in any of the modes (debug/release-x86/x64) everything goes well, but when you build a package for the store immediately for x86 x64 I receive an error message. It is often accompanied by reports that StopwatchIndic has not been included in the xaml.cs file.
This ugliness occurs on two computers and two Studios - 16.6.5 and 16.7.0 Preview 5. "Recovery" Studio does not help to solve the problem.

---
#### Feedback Bot on 7/26/2020, 11:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
Could the author please provide a repro app?

**Comment by chungweileong94** [comment]
Yeah, I faced the exact same issue, works fine on both release & debug mode, but the error shows up immediately when I try to package it.

**Comment by chungweileong94** [comment]
In my case, it seems like the `/obj` is outdated.  
I managed to solve it by removing both `/obj` & `/bin` (you probably don't need to remove `/bin`) folders, then rebuild the project again.

**Comment by StephenLPeters** [comment]
Hmm, @chungweileong94 what version of WinUI 2 are you using?

@ranjeshj @and @llongley or maybe @jevansaks. Does the fix of deleting the /obj directory point to something in our packaging being broken?

**Comment by AnriaruDoragon** [comment]
Had the same problem, but without error code, description only.
I deleted `/obj` folder and tried to package again, now everything is works fine.
`Microsoft.UI.Xaml` version: `2.4.2`

**Comment by jevansaks** [comment]
@fabiant3 @stevenbrix can you assist with this CompileXaml regression?

**Comment by stevenbrix** [comment]
@chungweileong94 and @AnriaruDoragon if you could share either repro project or binlog that would be incredibly helpful.

To get an appropriate binlog that simulates building for the store, you can build your project from a Developer Command prompt with this command: 
`msbuild /p:AppxBundlePlatforms=x86 /p:Platform=x86 /p:Configuration=Release /p:BuildAppxUploadPackageForUap=true /bl`

If you do this, does the issue reproduce ? If so, please upload the msbuild.binlog file that is created.

**Comment by chungweileong94** [comment]
> Hmm, @chungweileong94 what version of WinUI 2 are you using?
> 
> @ranjeshj @and @llongley or maybe @jevansaks. Does the fix of deleting the /obj directory point to something in our packaging being broken?

I'm using `v2.4.3`.
From what I found, it's mainly because I changed the `x:name` for one of the elements, then for some reason, the obj not getting the update and it still referencing the old name.

**Comment by chungweileong94** [comment]
> @chungweileong94 and @AnriaruDoragon if you could share either repro project or binlog that would be incredibly helpful.
> 
> To get an appropriate binlog that simulates building for the store, you can build your project from a Developer Command prompt with this command:
> `msbuild /p:AppxBundlePlatforms=x86 /p:Platform=x86 /p:Configuration=Release /p:BuildAppxUploadPackageForUap=true /bl`
> 
> If you do this, does the issue reproduce ? If so, please upload the msbuild.binlog file that is created.

I will try my best to reproduce that again.

**Comment by AnriaruDoragon** [comment]
> @chungweileong94 and @AnriaruDoragon if you could share either repro project or binlog that would be incredibly helpful.
> 
> To get an appropriate binlog that simulates building for the store, you can build your project from a Developer Command prompt with this command:
> `msbuild /p:AppxBundlePlatforms=x86 /p:Platform=x86 /p:Configuration=Release /p:BuildAppxUploadPackageForUap=true /bl`
> 
> If you do this, does the issue reproduce ? If so, please upload the msbuild.binlog file that is created.

@stevenbrix I tried to build a project using this command, no errors occurred, the project was built and works, but when I try to pack it again from menu, it gives the same error, deleting the `/obj` still solves this problem.

Here is the repository, in the readme I described the versions and how to get this error.
[AnriaruDoragon/UWP-MSB4181-CompileXaml](https://github.com/AnriaruDoragon/UWP-MSB4181-CompileXaml)

The first time the error occurred was in another project, I created a new one to specifically cause this error.

**Comment by stevenbrix** [comment]
Thanks @AnriaruDoragon for the repro. I'm bummed that didn't work...I wonder if you need to specify both x86 an x64 for the AppxBundlePlatforms property to simulate the environment more correctly?

**Comment by AnriaruDoragon** [comment]
@stevenbrix `/p:AppxBundlePlatforms="x86|x64"`, `/p:AppxBundlePlatforms="x86|x64|ARM|ARM64"` and `/p:AppxBundlePlatforms="x86|x64" /p:Configuration=Debug` works fine too.
The error is thrown regardless of platform or configuration. Tried packaging Release for `x86` and `ARM|ARM64` only, and Debug for `x86|x64|ARM` via the context menu in Solution Explorer, it still throws this error.

**Comment by AnriaruDoragon** [comment]
Note: After causing this error i still can run project in `Debug x86`, but `Release x86` won't start and thrown this error.

I'll try to upload broken `/obj`.

**Comment by AnriaruDoragon** [comment]
I uploaded broken folder to and update [repo](https://github.com/AnriaruDoragon/UWP-MSB4181-CompileXaml). Link to the folder in README.

**Comment by kareemsulthan07** [comment]
I have an UWP project. Recently I successfully created a package and submitted to the Microsoft Store. Today (28/Aug/2020), after changing some UI, when I try to create another package with higher version number for submitting it to the Microsoft Store, it is throwing this error. "The "CompileXaml" task returned false but did not log an error."

This error is particularly happening when Visual Studio is creating .appx file in x64 (Release) configuration. I tested the app in both configurations - Debug (x86 and x64).  No such error.

I need some help here.

**Comment by stevenbrix** [comment]
@kareemsulthan07 can you try running this command from a developer command prompt?

```
msbuild /p:AppxBundlePlatforms=x64 /p:Platform=x64 /p:Configuration=Release /p:BuildAppxUploadPackageForUap=true /bl
```

**Comment by stevenbrix** [comment]
@kareemsulthan07 and @AnriaruDoragon, are there any other errors or warnings you see in the ErrorList or Build output window?

**Comment by AnriaruDoragon** [comment]
@stevenbrix No other errors.

An error occurs when you trying to generate app bundle for Release x86 and x64

`msbuild /p:AppxBundlePlatforms="x86|x64" /p:Configuration=Release /p:BuildAppxUploadPackageForUap=true /p:AppxBundle=Always /bl` 
returns error (russian, sorry)
```
"D:\My Folder\VS Projects\UWP-MSB4181-CompileXaml\UWP-MSB4181-CompileXaml.sln" (целевой объект по умолчанию) (1) ->
"D:\My Folder\VS Projects\UWP-MSB4181-CompileXaml\UWP-MSB4181-CompileXaml\UWP-MSB4181-CompileXaml.csproj" (целевой объект по умолчанию) (2) ->
(Целевой объект _CreateBundle) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(5276,5): error APPX3104: вы не можете создать пакета прилож
ений для платформы "arm", которая не включена в список платформ, выбранных для создания пакета приложений. Задайте для платформы одно из следующих значений: x86,x64. [D:\My Folder\VS Projects\UWP-MSB418
1-CompileXaml\UWP-MSB4181-CompileXaml\UWP-MSB4181-CompileXaml.csproj]
```

**[msbuild.binlog (Google Drive)](https://drive.google.com/file/d/15Gujo0wdz_lazexVVI9QSELMZuOzYCNL/view?usp=sharing)**

**Comment by AnriaruDoragon** [comment]
After `msbuild` command Build works fine until you change something.

**Comment by kareemsulthan07** [comment]
Alright, I fixed this issue. This is what was wrong with my solution and what I did to resolve the issue.

1. I renamed a Xaml resource key, but in one file of the project (UWP) was still using the old resource key. I changed it to the new resource key.
2. In my solution, projects were using different versions of the same nuget packages, like ms.netcore.uwp, ef core, uwp community toolkit, etc., I update all the nuget packages to the latest version. This caused me another issue which might not be related to the error.
3. After I update all of the nuget packages to the latest version, a database related error raised, specifically foreign key column. I had to re-create entire database schema using sql and migrations. I completed this in a day.

After fixing all the above issues, no error in debug configuration. Then, I proceed to create a store package in release configuration. No error. And Yes, I successfully submitted a package as an update to my app in Microsoft Store.

I think I tried my best to explain the scenario so that others can find it useful.

**Comment by fabiant3** [comment]
Thanks for the follow up @kareemsulthan07 .

**Comment by Gavin-Williams** [comment]
I got this error message today for WinUI 3 Preview 2 UWP blank app. It was working last night, and today I'm getting the error and it won't build.

**Comment by stevenbrix** [comment]
@AnriaruDoragon I put the text of the error into Google Translate, and it said something about the configurations being incorrect (trying to build arm, but you should choose x64 or x86) - this might be a red herring based off what properties you pass into msbuild.

@Gavin-Williams can you follow the steps here for collecting binlogs through VS? https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/debugging_buildfailures.md#collecting-binlogs-through-visual-studio

**Comment by AnriaruDoragon** [comment]
@stevenbrix I forgot to add `/p:Platform="x64"`, false alarm...
MSBuild is doing its job well. It rebuilds objects in solution and after that package the project. When you trying to package the project from the context menu it is trying to package it using already existing objects. This is how I understand the situation 🤷‍♂️

**Comment by stevenbrix** [comment]
@AnriaruDoragon thanks, so does this only repro in Visual Studio then?

**Comment by AnriaruDoragon** [comment]
@stevenbrix Yes, problem only occurs in Visual Studio, in dev prompt everything is ok.

**Comment by stevenbrix** [comment]
@AnriaruDoragon can you please capture logs using the steps described here: https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/debugging_buildfailures.md#collecting-binlogs-through-visual-studio?

And please, capture them in English, or I wont be able to do much with them!

**Comment by AnriaruDoragon** [comment]
@stevenbrix I hope that I did correctly
https://github.com/AnriaruDoragon/UWP-MSB4181-CompileXaml/blob/master/CompileErrorTest_Release_x86_Build_2020-09-22T23_10_37.4827196%2B03_00.binlog
