### ISSUE TITLE
Crash in Microsoft.UI.Xaml.dll!GridLayoutState::SetSize

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#3069]
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/27718884?src=WorkItemMention&src-action=artifact_link).

Could be caused by the app in question using an older version of WinUI.

@ranjeshj thinks this is a dupe.

**Comment by ranjeshj** [comment]
This is likely already fixed. This is currently not actionable due to the lack of crash dumps.
