### ISSUE TITLE
CommandBar in NavigationView Header show incorrect font size in secondary command

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/microsoft-ui-xaml#307]
**Describe the bug**
When I add a CommandBar in NavigationView Header, the secondary command font size is too large.

**Steps to reproduce the bug**
1. Create a blank UWP app.
2. Add NavigationView control to MainPage
3. Add in NavigationView HeaderTemplate a CommandBar with some SecondaryCommands.
4. Run app and open secondary commands in CommandBar.

**Expected behavior**
Secondary commands have normal font size.

**Screenshots**
![image](https://user-images.githubusercontent.com/12777039/52715787-a409fe00-2f9d-11e9-9c73-2d83afd8a722.png)

**Version Info**
UWP Blank App with Microsoft.UI.Xaml version 2.0.181018004 nuget package, in Windows 10 October Update.

NuGet package version: 
Microsoft.UI.Xaml version 2.0.181018004 nuget package

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)   |Yes|
| April 2018 Update (17134)        |No|

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |Yes|

**Additional context**
This issue was detected by @TheJoeFin in Windows Template Studio.
X-ref: https://github.com/Microsoft/WindowsTemplateStudio/issues/2921

Repro App: 
[CommandBarExample.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2860607/CommandBarExample.zip)

**Comment by jevansaks** [comment]
This is somewhat expected. The header uses a larger font than the default and most of our controls don't explicitly set a FontSize and just inherit it down the tree. If you want to try to use a CommandBar here and have it be the default size then you'll need to set FontSize to 14 to go back to the default.

**Comment by dgomezc** [comment]
@jevansaks Thanks for looking into this. We adapt our templates.
