### ISSUE TITLE
Crash in Microsoft.UI.Xaml.dll!ParallaxView::EnsureProperties

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#3070]
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/27565766?src=WorkItemMention&src-action=artifact_link).

Potentially from an app using older versions of WinUI 2.

**Comment by ranjeshj** [comment]
No crash dumps, so this is not actionable.
