### ISSUE TITLE
Crash in Microsoft.UI.Xaml.dll!VirtualizationInfo::UpdatePhasingInfo

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#3071]
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/27186342?src=WorkItemMention&src-action=artifact_link).

Potentially from an app using older versions of WinUI 2.

**Comment by ranjeshj** [comment]
No crash dumps available for this to make it actionable.
