### ISSUE TITLE
Question: FrameworkPropertyMetadata and FrameworkPropertyMetadataOptions missing ?

### ISSUE THREAD

**Issue by Suvarnnan** [microsoft/microsoft-ui-xaml#3073]
Hi,

I am currently doing some prototypes migrating custom controls available in our end from WPF to WinUI.

During prototype I noticed that, in our end there are some WPF custom controls using FrameworkPropertyMetadata and FrameworkPropertyMetadataOptions for DP but equivalent implementation for WinUI is missing.

These implementations will be available soon in near WinUI Preview release ?

I am using right now
VS => Version 16.7.0 Preview 5.0
.Net SDK => dotnet-sdk-5.0.100-preview.4.20268.1-win-x64 / dotnet-sdk-5.0.100-preview.4.20268.1-win-x86

Thanks.

**Comment by VijayanRamachandran** [comment]
Example for above query..

public static readonly DependencyProperty exampleDependencyProperty =
            DependencyProperty.RegisterAttached("example", typeof(string), typeof(xyz), new 
            **FrameworkPropertyMetadata**(string.Empty, **FrameworkPropertyMetadataOptions.BindsTwoWayByDefault,** 
            NotifyPropertyChanged));

or

public static readonly DependencyProperty exampleDependencyProperty =
            DependencyProperty.RegisterAttached("example", typeof(string), typeof(xyz), new 
            **FrameworkPropertyMetadata**(string.Empty, **FrameworkPropertyMetadataOptions.AffectsRender,** 
            NotifyPropertyChanged));

**Comment by chrisglein** [comment]
Similar to the question for #3074. Different API, but same answer. WinUI will not necessarily align with WPF at release or afterwards, however you may submit a feature request (see issue template) to do so.
