### ISSUE TITLE
Question: UIPropertyMetadata is missing ?

### ISSUE THREAD

**Issue by Suvarnnan** [microsoft/microsoft-ui-xaml#3074]
Hi,

I am currently doing some prototypes migrating custom controls available in our end from WPF to WinUI.

During prototype I noticed that, in our end there are some WPF custom controls using UIPropertyMetadata for DP but equivalent implementation for WinUI is missing.

These implementations will be available soon in near WinUI Preview release ?

I am using right now
VS => Version 16.7.0 Preview 5.0
.Net SDK => dotnet-sdk-5.0.100-preview.4.20268.1-win-x64 / dotnet-sdk-5.0.100-preview.4.20268.1-win-x86

Thanks.

**Comment by chrisglein** [comment]
> These implementations will be available soon in near WinUI Preview release ?

WinUI Preview's release will most closely match UWP XAML (aka the version of XAML that ships inbox with Windows). There is no immediate work planned to align with WPF although we do of course take proposals for feature requests (you can use the issue template for that, fill out your scenario and such).
