### ISSUE TITLE
WinUI 2.2 UWP User Defined Themes Possible?

### ISSUE THREAD

**Issue by FrogsLegs** [microsoft/microsoft-ui-xaml#3075]
Hi Team,

Great effort on the Fluent XAML Theme Editor, just a quick question from me regarding exporting the theme:

Is there a way to dynamically import user defined themes from Microsoft Fluent XAML Theme Editor into a `ResourceDictionary` inside a UWP project? E.g if a user wanted to create their own theme and "import" it into my app, what would be the most straightforward way to approach this?

Thanks 👍

**Comment by ranjeshj** [comment]
@kikisaints as FYI

**Comment by groovykool** [comment]
Follow the instructions here?

https://github.com/Microsoft/fluent-xaml-theme-editor
