### ISSUE TITLE
Fix manifest in arm64 framework package.

### ISSUE THREAD

**Issue by ranjeshj** [Microsoft/microsoft-ui-xaml#308]
**Describe the bug**
The framework package creation scripts use the manifest from the test app to create the activatable type entries. Since the test app is not building for arm64, this gets ignored and will cause apps to not launch in arm64. We either need to change the way the manifest is updated or build the test app for arm64.

**Comment by jevansaks** [comment]
@ranjeshj you have a PR open for this, right? If so please assign to yourself, thanks!
