### ISSUE TITLE
What is the second parameter of `Microsoft::UI::Xaml::Controls::IFrame::Navigate`?

### ISSUE THREAD

**Issue by bsld** [microsoft/microsoft-ui-xaml#3080]
I don't understand it. If I implement my own object with `IInspectable`, `IUnknown` and `IAgileObject` it gets queried for some unknown for me `IID` and then it crashes.

What interface should I use here?

**Comment by StephenLPeters** [comment]
According to this [documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame.navigate?view=winrt-19041) it is "The navigation parameter to pass to the target page; must have a basic type (string, char, numeric, or GUID) to support parameter serialization using GetNavigationState."

**Comment by StephenLPeters** [comment]
Internally we QI for Windows.Foundation.IPropertyValue, It might work if you implement that as well.

**Comment by bsld** [comment]
@StephenLPeters Would I ask if I haven't tried? - The basic type of `IReference` first don't have a string interface exported in the idl (winmd) files second the one that are don't have an defined `GUID` so how can the `Microsoft::UI::Xaml::Controls::IFrame::Navigate` method know the object type passed to it? I tried implementing one of those interfaces with its get method but its never even called. Right now I'm trying a suggestion from discord that says the actual interface expected here is of type `Microsoft::UI::Xaml::Controls::IPage`. Ok - I didn't see you last point I assume my fellow discord members are wrong. I'll try `IPropertyValue`.

**Comment by StephenLPeters** [comment]
let us know if it works

**Comment by bsld** [comment]
Definitely.

**Comment by bsld** [comment]
@StephenLPeters I don't understand where to register said class I'm passing the metadata for. I tried dllgetactivationfactory but it doesn't seem to affect anything.

**Comment by bsld** [comment]
I figured it out - and implemented my own metadata provider. Closing this issue now.

**Comment by StephenLPeters** [comment]
@bsld could you share you solutions incase someone else hits the issue?

**Comment by bsld** [comment]
@StephenLPeters Sure - it's written in pure C btw - here is the [implementing source file](https://github.com/bsld/CWebView2/blob/master/metadataprovider.c).
