### ISSUE TITLE
Question: C++ Class Library(WinUI in Desktop) project template?

### ISSUE THREAD

**Issue by knat** [microsoft/microsoft-ui-xaml#3081]
Hi, I'd like to know how to create a C++ Class Library(WinUI in Desktop) project?

**Comment by StephenLPeters** [comment]
I *think* you can just use a UWP c++ class library here. This should work because for c++ we go through the winmd's and there shouldn't been any difference between how you reference the dll. (where as with c# we reference the DLL directly and in that case we need a different UWP and Desktop project.)  @llongley and @alwu-msft FYI

**Comment by alwu-msft** [comment]
"Class Library" is a .Net concept; you're probably thinking of a "Windows Runtime Component" project. We don't have one yet for C++ WinUI in Desktop, but it is part of our plans for WinUI 3.0.

**Comment by knat** [comment]
A C++ Windows Runtime Component(WinUI in UWP) project cannot be referenced by a C# WinUI desktop app project:
```
Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.
```
I'd like to see C++ Windows Runtime Component(WinUI in Desktop) project template to be added in the next release.

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by alwu-msft** [comment]
@Scottj1s Is automatic generation of the interop assembly by CsWinrt for referenced .winmds in the works?

**Comment by Scottj1s** [comment]
@alwu-msft No, there's no explicit backlog item for that, for two reasons: 1) we'd prefer all component/framework developers (e..g, WinUI) to produce and distribute an interop explicitly, avoiding concerns over type identity, etc; 2) we've done some experimenting with slipstreaming an interop in for a winmd reference and there are some rough edges that could make this approach unreliable.  Alternatively, we could offer a template for creating an interop from a winmd reference, for app devs to explicitly use.

**Comment by MikeHillberg** [comment]
To the original point, there is a C++ WinUI Runtime Component project template now.
