### ISSUE TITLE
NavigationView: The OverflowMenu button will not collapse when the overflow menu only contains one item and NavigationView menu items are removed to empty the overflow menu

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3086]
**Describe the bug**
When the top NavigationView's overflow menu only contains a *single* menu item and 
* either removing that item or
* removing menu item(s) to create enough room for the overflow menu item be displayed in the NavigationView pane area

will not collapse the OverflowMenu button (even though the overflow menu is now empty):

![navview-overflowmenubutton](https://user-images.githubusercontent.com/1398851/89736093-53c30d80-da67-11ea-87cc-440c6f4bb82d.gif)

**Expected behavior**
The OverflowMenu button should be collapsed.

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.5.0-prerelease.200708003
Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by chingucoding** [comment]
I think the issue here is that we simply forget to reevaluate the overflow menu situation when the list of NavigationViewItems changes.

**Comment by Felix-Dev** [comment]
@chingucoding Yes, I am already working ona  fix for this issue.
