### ISSUE TITLE
Proposal: Add Windows app type (UWP/Desktop) question to bug report template for WinUI 3

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3090]
# Proposal: Add Windows app type (UWP/Desktop) question to bug report template for WinUI 3

## Summary
Since WinUI 3 Preview 1 has been released we have seen WinUI 3 issues being created for either WinUI 3 Win32 apps or WinUI 3 UWP apps. Take for example the recent issue https://github.com/microsoft/microsoft-ui-xaml/issues/3058 where the used WinUI 3 Preview version was specified but the information about whether it's a UWP or Win32 app was only given, I believe, in the [Additional Context] section as part of the given debug output ("App1.exe (Win32)").

There will be different internal WinUI 3 codeflows taken depending on the Windows app type so I think we should prominently ask the bug report author to specify for which app type they encountered the bug.

To increase the probability the bug report author will specify that information I propose adding the following section to the [bug report template](https://github.com/microsoft/microsoft-ui-xaml/blob/master/.github/ISSUE_TEMPLATE/bug_report.md):

```
**Version Info**

NuGet package version: 
<!-- 
Examples
[Microsoft.UI.Xaml 2.4.0]
[Microsoft.WinUI 3.0.0-preview2.200713.0]
-->

// Start of proposed section below:

<!-- If you are using WinUI 3, please specify for which Windows app type you have enountered the issue. Leave blank if you didn't try that version. -->
Windows app type:
| UWP | Win32 |
| :---: | :---: |
| <!-- Yes/No? --> | <!-- Yes/No? --> |

// End of proposed section.

<!-- Which Windows versions did you see the issue on? Leave blank if you didn't try that version. -->
| Windows 10 version                  | Saw the problem? |
```

Adding such a template section visible by default will, in my opinion, better lead bug report authors to specify the relevant Windows app type(s) for WinUI 3 instead of just a simple comment in the bug report template. For WinUI 2 bug reports, this table is irrelevant and will be shown in a compact state thus reducing the "noise" added here:
![image](https://user-images.githubusercontent.com/1398851/89840307-2ada6f80-db70-11ea-983c-fe2c1ed43f73.png)

**Comment by ranjeshj** [comment]
Thanks @Felix-Dev for opening this issue. 
We are currently labeling issues with appropriate tags during triage. 

We could add these
WinUI2 vs WinUI3 (currently specified through nuget package used). 
If using WinUI3, Is it UWP or Desktop

@Austin-Lamb @MikeHillberg any other details you can think of that would be useful to collect when issues are filed ?

**Comment by MikeHillberg** [comment]
This looks great, thanks @Felix-Dev!

**Comment by Felix-Dev** [comment]
Seems like I can create a PR then :)
