### ISSUE TITLE
WebView2 crashes my UWP app

### ISSUE THREAD

**Issue by bsld** [microsoft/microsoft-ui-xaml#3091]
**Describe the bug**
`WebView2` suddenly crashes my UWP app. It worked before.

**Steps to reproduce the bug**
Create a new C++/WinRT WinUI 3 UWP blank app and add `WebView2` in the main page.

**Expected behavior**
Not crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/16734426/89856097-fc28bd00-dba0-11ea-84d6-fb32a2501f8a.png)

**Version Info**

NuGet package version: 

Microsoft.Windows.CppWinRT 2.0.200729.8
Microsoft.WinUI 3.0.0-preview2.200713.0

Microsoft Windows [Version 10.0.19041.388]

On a laptop desktop.

**Additional context**
As I've mentioned above it worked before.

I've a crash dump to upload but it doesn't allow me.

**Comment by bsld** [comment]
I reinstalled some stuff and it's working now. But I still have the dump of this instance if someone is interested to provide me some means to upload it.

**Comment by codendone** [comment]
@bsld Do you have the line number in CreateCoreWebView on that stack, and potentially the hresult value in the throw_hresult line?  Likely options include the WebView2 Runtime code returning an error, or the webview2loader.dll missing for some reason.

**Comment by codendone** [comment]
Closing this issue, since reinstall fixed it and we don't have more info.  We'll continue to keep watch for any potential install issues.
