### ISSUE TITLE
TreeView: Drag&Drop operation does not update selection state of affected parent items

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3092]
**Describe the bug**
Given a TreeView in multi-selection mode, drag&drop operations do not update the selection state of the affected parent nodes when dropping the selected items into a new node:

![treeview-multiselection-issue](https://user-images.githubusercontent.com/1398851/89929180-2ca44180-dc09-11ea-98a4-8be1f52acc8c.gif)

**Steps to reproduce the bug**
1. Open the XAML Controls Gallery and go to the TreeView page
2. Scroll down to the multi-selection TreeView example
3. Do the same (or similar) steps as shown in the GIF.

**Expected behavior**
![image](https://user-images.githubusercontent.com/1398851/89929231-3f1e7b00-dc09-11ea-8104-0a565f7d263a.png)

**Version Info**

NuGet package version: 
Newest WinUI 2.4 and 2.5 preview versions.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional Context**
I would like to fix this.

**Comment by StephenLPeters** [comment]
@predavid-zz fyi
