### ISSUE TITLE
TreeView: Dragging and dropping a selected item in single selection mode causes the item to be unselected

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3096]
**Describe the bug**
Given a TreeView in single-selection mode, dragging and then dropping a selected item causes the item to be unselected:

![treeview-singleselection-issue](https://user-images.githubusercontent.com/1398851/89933144-f10c7600-dc0e-11ea-85cb-78ccd1d1a34d.gif)

I view this as a bug. A drop should not cause the selected item to be unselected. In fact, it works as expected in multi-selection mode:

![treeview-multiselection](https://user-images.githubusercontent.com/1398851/89933352-38930200-dc0f-11ea-8a1b-d1cd6a796e6a.gif)
(The issue you see in the above where the parent nodes' selection state is not updated after the drag and drop operation is being tracked in issue https://github.com/microsoft/microsoft-ui-xaml/issues/3092.)

**Steps to reproduce the bug**

1. Open the XAML Controls Gallery and go to the TreeView page
2. Scroll down to the single-selection TreeView drag and drop example
3. Do the same (or similar) steps as shown in the GIF.

**Expected behavior**
The drag & drop'ed TreeViewItem should remain selected:
![image](https://user-images.githubusercontent.com/1398851/89933417-53fe0d00-dc0f-11ea-986f-09cff2b74008.png)

**Version Info**

NuGet package version: 
WinUI 2.4 and WinUI 2.5 previews

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I would like to fix this.

**Comment by StephenLPeters** [comment]
Single selection we are inheriting from list view and multi select we rolled our own solution, so i'm not surprised there is differences.  Interestingly list view does keep selection during drag and drop, so we must be doing something to affect it.
