### ISSUE TITLE
TreeView expand node doesn't work for non-visible nodes, causing inconsistent state.

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#3099]
When using the new TreeView control in UWP, expanding of nodes only works if the node is visible in the window. For example, if you expand a root node that has many children (too many to fit vertically in the window) using TreeView.Expand( rootTreeViewNode) and then expand the following root node in the same manner, the following root node will not show as expanded in the tree. This has many bad consequences such as:

- The IsExpanded property of the TreeViewNode can be out of sync with the expanded state of the TreeViewItem
- It is nearly impossible to expand the entire tree programatically.

**Steps to reproduce the bug**

Steps to reproduce:

(1) Compile XamlControlsGallery with Min Version set to 1089 (build 17763), using UWP targeting x86.

(2) In TreeViewPage.xaml:

(2a) Change "Microsoft" to "Windows" in the xmlns:muxcontrols= statement at the top of file;

(2b) Add a button in the "TreeView with DataBinding Using ItemsSource" example

(2c) Remove 'IsExpanded="True"' from the DataTemplate in TreeView1

(3) In TreeViewPage.xaml.cs, change "Microsoft" to "Windows" in the "using mux=Microsoft.Ui.Xaml.Controls" statement and add the following methods:

    private void AddMoreData()
    {
        ExplorerItem folder = new ExplorerItem() { Name="More Data", Type=ExplorerItem.ExplorerItemType.Folder };
        for (int i = 0; i < 50; i++) {
            ExplorerItem child = new ExplorerItem() { Name = "Child " + i, Type = ExplorerItem.ExplorerItemType.File };
            folder.Children.Add( child);
        }
        this.DataSource.Insert(1, folder);
    }
    private void Button_Click(object sender, RoutedEventArgs e)
    {
        System.Collections.Generic.Queue<TreeViewNode> toDo = new System.Collections.Generic.Queue<TreeViewNode>();
        foreach (TreeViewNode tvn in this.TreeView1.RootNodes) {
            toDo.Enqueue(tvn);
        }
        while (toDo.Count > 0) {
            TreeViewNode tvn = toDo.Dequeue();
            tvn.IsExpanded = true;
            foreach (TreeViewNode child in tvn.Children) {
                toDo.Enqueue(child);
            }
        }
    }

(4) Call AddMoreData in the TreeViewPage constructor after 'DataSource = GetData'; and call Button_Click from the button added in (2b).

Result: run the program, click the button, and scroll down in the TreeView to observe that "Personal Folder" is not expanded. Expand "Personal Folder" by clicking on the chevron and observe that "Home Remodel Folder" is also not expanded. Both of them have IsExpanded set to true, and should be expanded in the display.

**Comment by StephenLPeters** [comment]
@sjb-sjb Why are you changing the Microsoft to Windows in your repro examples?  The TreeView that is check into the OS is quite old, we have made a large number of fixes since then and this issue has likely already been fixed in the Microsoft.UI.Xaml version.

**Comment by sjb-sjb** [comment]
@StephenLPeters good question, I don't know why I did that! Suggest we close this issue as it is malformed.
