### ISSUE TITLE
Pointer Replay feature is busted in XAML Islands scenario

### ISSUE THREAD

**Issue by kmelmon** [microsoft/microsoft-ui-xaml#3102]
This bug was discovered by Facebook through react-native-windows.  See tracking bug:
https://github.com/microsoft/react-native-windows/issues/5671

The "pointer replay" feature replays the last valid pointer message whenever layout changes, so that these types of scenarios can work:
-The mouse is over an element
-The layout changes in such a way that the element moves
-The mouse does not move
In this case the mouse suddenly becomes over another element.  So the element it was over should react as if the mouse moved out of it, and the new element should react as if the mouse moved into it.

This feature doesn't work in XAML Islands mode.  I debugged this to this function in winbrowserhost.cpp:

bool CXcpBrowserHost::IsPreviousPointerUpdateMessageValid(UINT32 previousPointerUpdateMsgId)
{
ASSERT(m_spPreviousPointerUpdateMsg != nullptr);

// Match the id that was requested against the id of the current cached pointer update message. If they don't match,
// that means we received a newer pointer update message and did a new hit test walk already, so we ignore the request
// and no-op.
if (m_previousPointerUpdateMsgId == previousPointerUpdateMsgId)
{
    // Check if the PointerId of the latest WM_POINTERUPDATE message is still valid. Delete the saved message if it is not.
    POINTER_INFO pointerInfo = {};
    if (::GetPointerInfo(m_spPreviousPointerUpdateMsg->m_pointerInfo.m_pointerId, &pointerInfo))
    {
        // Check the cached hwnd associated with the pointer. It might be a popup window that has since closed, in which case we
        // shouldn't replay the pointer update.
        if (m_previousPointerUpdateHwnd == m_pSite->GetXcpControlWindow()     

This check isn't islands-aware. It's comparing the HWND of the last pointer message to the core's notion of its window, which in the case of islands is a "fake CoreWindow" and certainly isn't going to pass this check. Thus this function return false, and XAML refuses to fire the pointer replay event.

JJ tells me that with lifted XAML everything is an island and we no longer use HWNDs for input messages, so it appears that pointer replay may be broken across the board in lifted XAML.  We should take a close look at this as it's an important feature that should work in islands mode.

**Comment by ranjeshj** [comment]
@Austin-Lamb @ocalvo as FYI

**Comment by kmelmon** [comment]
This bug got fixed by:
https://microsoft.visualstudio.com/WinUI/_git/microsoft-ui-xaml-lift/pullrequest/5127704
@Austin-Lamb FYI
RNW can wait until we re-target to WinUI 3, as the only known customer has a workaround.

**Comment by kmelmon** [comment]
george tells me pointer replay is still broken... reopening for now
