### ISSUE TITLE
TabView throw ArgumentOutOfRange exception when TabItemSource is cleared

### ISSUE THREAD

**Issue by Psykobal** [microsoft/microsoft-ui-xaml#3104]
**Describe the bug**
If you clear an ObservableCollection attached to TabItemsSource, app will crash with ArgumentOutOfRangeException

**Steps to reproduce the bug**

1. Open XamlControlsGallery project
2. Modify `private void TabViewItemsSourceSample_AddTabButtonClick(TabView sender, object args)` in TabViewPage.xaml.cs as follow:
`myDatas.Clear();`
 `// Add a new MyData item to the collection. TabView automatically generates a TabViewItem.`
 `myDatas.Add(CreateNewMyData(myDatas.Count));`

3. Launch the project and add a tab in the TabView page (third exemple)

**Expected behavior**
Old tabs are removed and the new tab appear

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.5.0-prerelease.200708003]

It was working on [Microsoft.UI.Xaml.2.4.2]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Felix-Dev** [comment]
I would like to take a look at this if nobody else is already looking into it.

**Comment by DHowett** [comment]
I believe Terminal is running into this reliably on startup now that it has moved to the latest prerelease.
