### ISSUE TITLE
'Failed to assign to property 'Microsoft.UI.Xaml.Controls.UserControl.Content'

### ISSUE THREAD

**Issue by bsld** [microsoft/microsoft-ui-xaml#3105]
I'm trying to implement my own metadata provider and for now it's working good - it looks like the respective functions are called (i.e. for my App.xaml, MainPage.xaml, WebView2 component initialization , WebView2 Source property setting). However for said WebView2 control I'm getting the above error. Any ideas what is the common issue for this problem and how to fix it?

**Comment by ranjeshj** [comment]
@alwu-msft as FYI. @bsld  could you provide a repro app ?

**Comment by bsld** [comment]
@alwu-msft Sorry - I figured it out - it was my implementation of the inner/outter connection of interfaces was incorrect. After I fixed it the issue vanished. Closing this issue now.
