### ISSUE TITLE
Proposal: Accept icon font glyphs and SVG for notification button images

### ISSUE THREAD

**Issue by SetTrend** [microsoft/microsoft-ui-xaml#3107]
# Proposal: Accept icon font glyphs and SVG for notification button images

## Summary
Currently, [according to documentation](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts#buttons-with-icons), a [ToastButton](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.notifications.toastbutton) only accepts rasterized images for displaying icons.

I'd like to suggest to provide options to allow an icon font glyph or SVG image alternatively.

## Rationale
* Rasterized images don't scale well on deviating Windows scaling settings
* Converting glyphs from `Segoe MDL2 Assets` is cumbersome and tedious
* Theming can easily be applied to both, font glyphs and monochrome SVG files.

**Comment by ad1Dima** [comment]
> Rasterized images don't scale well on deviating Windows scaling settings
You can use several images for different scale https://docs.microsoft.com/en-us/windows/uwp/app-resources/tailor-resources-lang-scale-contrast

**Comment by SetTrend** [comment]
Indeed, yet they are unnecessarily bloating the assets folder with variations a font glyph or SVG provides automatically per definition.

**Comment by StephenLPeters** [comment]
The ToastButton is a Windows Community Toolkit controls, can you please open this proposal on their [repo](https://github.com/windows-toolkit/WindowsCommunityToolkit)
