### ISSUE TITLE
There is a bug when PersonPicture in ListView？

### ISSUE THREAD

**Issue by doghappy** [Microsoft/microsoft-ui-xaml#311]
**Describe the bug**
There is a bug when `PersonPicture` in `ListView`?  
I tried to bind a **FontFamily** to `PersonPicture`, it works for a single `PersonPicture`, but in `ListView`, the binding does not seem to work.

**Steps to reproduce the bug**

### Result

![image](https://user-images.githubusercontent.com/20038914/52759412-b8560580-3046-11e9-8014-136c15c81163.png)

### Code behind

```cs
public sealed partial class TestPage : Page
{
    public TestPage()
    {
        InitializeComponent();
        Fonts = new List<FontFamily>
        {
            new FontFamily("Segoe MDL2 Assets"),
            new FontFamily("Segoe MDL2 Assets"),
            new FontFamily("Segoe MDL2 Assets")
        }
    }

    public List<FontFamily> Fonts { get; }
}
```

### XAML

```xaml
<StackPanel Padding="32" Orientation="Horizontal">
    <ListView ItemsSource="{x:Bind Fonts}">
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="FontFamily">
                <StackPanel Orientation="Horizontal">
                    <PersonPicture DisplayName="Test" Initials="&#xE13D;" FontFamily="Segoe MDL2 Assets"/>
                    <TextBlock Text="&#xE13D;" FontFamily="{x:Bind}"/>
                </StackPanel>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>

    <ListView ItemsSource="{x:Bind Fonts}">
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="FontFamily">
                <StackPanel Orientation="Horizontal">
                    <PersonPicture DisplayName="Test" Initials="&#xE13D;" FontFamily="{x:Bind}"/>
                    <TextBlock Text="&#xE13D;" FontFamily="{x:Bind}"/>
                </StackPanel>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
</StackPanel>
```

| Windows 10 version                  | Saw the problem? |
| :-------------------- | :------------------- |
| October 2018 Update (17763)   | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |

**Comment by jevansaks** [comment]
Interesting bug. I don't see any obvious reason why the FontFamily on PersonPicture wouldn't get the right value. Did you happen to debug into the code or look at the values in the live visual tree to see what might be wrong?

**Comment by licanhua** [comment]
From the live visualtree, PersonPicture itself is with FontFamily="Segoe MDL2 Assets", but InitialsTextBlock inside PersonPicture is "Segoe UI". We have TemplateBinding between InitialsTextBlock and PersonPicture style, so we expect it should work but not.
Problem should related to x:bind, so I suggest we start the investigation from compiler.

```
 <TextBlock
      x:Name="InitialsTextBlock"
                       ...
     FontFamily="{TemplateBinding FontFamily}"
```

**Comment by jevansaks** [comment]
Thanks for investigating. x:Bind just sets values the same as if you'd done from code-behind -- it just does it later. @harinikmsft is there a way to make x:Bind set values during template construction instead of deferred? That seems to be the difference between the working/not-working scenarios.

**Comment by MikeHillberg** [comment]
It should always be valid to change the PersonPicture.FontFamily, just like it is to change the TextBlock.FontFamily.  This looks like some kind of change notification issue in PersonPictures.

**Comment by jevansaks** [comment]
Looking at [the code](https://github.com/Microsoft/microsoft-ui-xaml/blob/050168409f55530c4af2bf17a6831b1be0a922b6/dev/PersonPicture/PersonPicture.cpp#L158), the control is doing something weird to explicitly set FontFamily from code-behind. I think we should probably shift this to use VSM so that it can set the font but also unset it, which is what the code seems to want to do.

**Comment by jevansaks** [comment]
Fixing this requires API additions, proposed in Microsoft/microsoft-ui-xaml-specs#9.
