### ISSUE TITLE
Proposal: Improve Badge notification API

### ISSUE THREAD

**Issue by SetTrend** [microsoft/microsoft-ui-xaml#3111]
# Proposal: Improve Badge notification API
I suggest to add two type-safe overloads for updating/setting tile/taskbar badge values.

## Summary
In order to support compile-time type checking and automated testing I suggest to add the following two uploads plus enumeration to the `Windows.UI.Notifications.BadgeUpdater` class:

```c#
public class BadgeUpdater
{
  public void Update(byte newValue) {...}
  public void Update(BadgeGlyph newValue) {...}

  //...

  public enum BadgeGlyph
  {
    None,
    Activity,
    Alarm,
    //...
  }

  //...
}
```

## Rationale
Manipulating `XML` text doesn't seem either compile-time safe nor adequate when programming in a programming language.

`XML` isn't a programming language, it's a serialization medium, like `YAML`, `JSON` or plain text.

Editing plain text in terms of XML doesn't provide compile-time safety nor does it support IntelliSense.

Hence, for API purity I suggest do add these two type-safe overloads to the API, basically implementing the two functions documentented [in the documentation](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/badges#create-a-numeric-badge).

**Comment by Felix-Dev** [comment]
@SetTrend I think [Project Reunion](https://github.com/microsoft/ProjectReunion) might be a better place for this issue (as the Badge APIs ae not part of WinUI).

**Comment by SetTrend** [comment]
Thanks for pointing me to the right direction. I'll drop the issue over there.
