### ISSUE TITLE
Proposal: Remove Sealed modifier from RepeatButton

### ISSUE THREAD

**Issue by jtbrower** [microsoft/microsoft-ui-xaml#3113]
# Proposal: Remove Sealed modifier from RepeatButton 

## Summary
ButtonBase, ToggleButton, HyperLinkButton, DropDownButton, SplitButton and ToggleSplitButton, are all defined to be inheritable classes while RepeatButton is marked with the Sealed modifier.

## Rationale
It is beneficial when designing a user interface if you can subclass basic foundational types such as those that provide button features.  Since the RepeatButton is sealed, it forces developers to create a subclass of ButtonBase, add the features that the RepeatButton provides and then add additional custom properties and/or overrides.

## Open Questions
I am guessing that there was solid rationale for preventing this class from being inherited from.  If that rationale far outweighs the benefit that developers achieve with that flexibility then I can certainly understand a quick closure of this proposal.

**Comment by Felix-Dev** [comment]
@jtbrower Your suggestion is part of proposal https://github.com/microsoft/microsoft-ui-xaml/issues/780 which as of now is still unclear when it will be acted upon. Make sure to make your voice heard in that issue as the team is monitoring how highly requested a feature this would be (everything unsealed).

**Comment by jtbrower** [comment]
@Felix-Dev sounds good, I will go ahead and close this out and provide feedback at #780
