### ISSUE TITLE
TreeView bound to ObservableCollection not updated on Move

### ISSUE THREAD

**Issue by sis2004** [microsoft/microsoft-ui-xaml#3119]
**Describe the bug**
When a TreeView has its ItemSource bound to an ObservableCollection, the tree doesn't get updated after calling the Move() method on that collection.

**Steps to reproduce the bug**
Here is a sample MainPage.xaml
```xaml
<Page
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    x:Class="App1.MainPage">

    <StackPanel>
        <muxc:TreeView ItemsSource="{x:Bind Mode=OneWay, Path=List}"/>
        <Button Content="Change List" Click="ChangeList"/>
    </StackPanel>
</Page>
```

And the code-behind MainPage.xaml.cs
```cs
namespace App1
{
    public sealed partial class MainPage : Page
    {
        private ObservableCollection<string> List { get; set; } = new ObservableCollection<string>()
        {
            "Item 1",
            "Item 2",
            "Item 3",
        };

        public MainPage()
        {
            this.InitializeComponent();
        }

        private void ChangeList(object sender, RoutedEventArgs e)
        {
            List.Move(0, 1);
        }
    }
}

```

1. Run the app.
2. Click on the 'Change List' button.

**Expected behavior**
Item 1 should move down after Item 2 in the tree view.

**Version Info**
NuGet package version: Microsoft.UI.Xaml 2.5.0-prerelease.200708003 or earlier

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
The workaround is to remove the item, and then insert it at the desired location and restore the tree selection.

**Comment by fabianoriccardi** [comment]
The same issue is still present in v1.6.5 and in v1.7-preview1. Very annoying. 

May moderators reopen this issue?
