### ISSUE TITLE
An Image with SVG source is not correctly Center, Right or Bottom aligned. 

### ISSUE THREAD

**Issue by sonnemaf** [Microsoft/microsoft-ui-xaml#312]
**Describe the bug**
An Image with SVG source is not correctly Center, Right or Bottom aligned. 

**Steps to reproduce the bug**

1. Create an UWP app with the following XAML in the MainPage
```xml
<Page x:Class="SvgDemo.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:SvgDemo"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Image Source="https://upload.wikimedia.org/wikipedia/commons/a/ae/Nuclear_symbol.svg"
               Width="600"
               Height="600"
               HorizontalAlignment="Right"
               VerticalAlignment="Bottom" />
    </Grid>
</Page>
```
2. Run the app. 

**Expected behavior**
I would expect that the SVG image was aligned to the Right Bottom corner of the page. It is not. The SVG I used has a Width and Height of 600.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="600" height="600" viewBox="-300 -300 600 600">
<circle r="292.3"/>
<g style="fill:#f1cd43" transform="scale(0.9783764)">
	<circle r="50"/>
	<path d="M75,0A75,75 0 0,0 37.5-64.951905L125-216.50635A250,250 0 0,1 250,0Z" id="bld"/>
	<use xlink:href="#bld" transform="rotate(120)"/>
	<use xlink:href="#bld" transform="rotate(240)"/>
</g>
</svg>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/9335559/52773963-80e25b80-303c-11e9-92bd-1e0bcf1850da.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@codendone Can you take a peek at this and advise?

**Comment by reddvid** [comment]
No problems on 18834 insider build. (Target version: 17763)

**Comment by jevansaks** [comment]
Thanks, @reddvid ! I'm following up to see if this is something that the team fixed in this release to explain the fact that it's fixed on latest insider.

**Comment by sonnemaf** [comment]
I confirm that it is fixed in the insider build.

**Comment by jevansaks** [comment]
Closing since it has been resolved.
