### ISSUE TITLE
Clicking on NavigationViewItem does not dismiss the opened pane in when that item is already in selected state

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#3124]
**Describe the bug**

**Steps to reproduce the bug**

1. Open the XAML Control gallary
2. Reduce the width enough to collapse the NavigationView pane
3. Click on the hamburger menu -> Settings Items
4. Navigation Pane is dismissed
5. Click on the hamburger menu -> Settings Items
6. Navigation Pane is not dismissed this time

**Expected behavior**

Navigation pane should be dismissed

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Felix-Dev** [comment]
I cannot reproduce this issue on the WinUI master branch. As such, I suspect the fix will land in the next WinUI 2.5 preview version (current WinUI 2.5 preview versions still show this issue).

**Comment by harvinders** [comment]
I can confirm that it seems fixed in the latest preview (Microsoft.UI.Xaml v2.5.0-prerelease.200812001).
