### ISSUE TITLE
RadioButtons raises duplicate SelectionChanged events

### ISSUE THREAD

**Issue by mcooley** [microsoft/microsoft-ui-xaml#3128]
**Describe the bug**
The Microsoft.UI.Xaml.Controls.RadioButtons.SelectionChanged event is raised multiple times.

**Steps to reproduce the bug**
[Demonstration code is available in this gist](https://gist.github.com/mcooley/e5484c305005f3c2f8952a5b49b104b1). 

1. Create a <muxc:RadioButtons> control containing three radio buttons
2. Switch the selection from one radio button to a different radio button. Notice that the SelectionChanged event is raised twice.

**Expected behavior**
Behavior should match ListView.SelectionChanged. A single SelectionChanged event should be raised with one RadioButton in the AddedItems list and one RadioButton in the RemovedItems list.

**Screenshots**
![image](https://user-images.githubusercontent.com/296848/90276043-17e9c880-de18-11ea-9dd4-c0e49470c270.png)

**Version Info**
NuGet package version: 
[Microsoft.UI.Xaml.2.4.3]
[Microsoft.UI.Xaml.2.5.0-prerelease.200708003]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20192)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by Felix-Dev** [comment]
I would like to take a look at this.

**Comment by Felix-Dev** [comment]
So, there's not just the issue of the selection changed event being raised two times but also an issue with the [SelectionChangedEventArgs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.selectionchangedeventargs?view=winrt-19041) instance passed to the event handler. For example, when setting the initial selection (via code or click interaction), not only does the SelectionChangedEventArgs instance say that an item has been selected, but also that an item has been deselected (`SelectionChangedEventArgs.RemovedItems.Count` = 1)! However, there is no such item being deselected (as none was selected before) and SelectionChangedEventArgs.RemovedItems[0] returns `null`. Thus this could lead to apps to crash if developers trust `SelectionChangedEventArgs.RemovedItems` to only contain non-null elements (and the expectation is just that).

In the case of selecting an item when another item has already been selected: This not only raises the SelectionChanged event two times, as reported here, but we also see the above described issue again:

##### 1st SelectionChanged event:
`SelectionChangedEventArgs.AddedItems.Count` = 1 even though the SelectionChangedEventArgs.AddedItems[0] returns `null`. The SelectionChangedEventArgs.RemovedItems are correct here (Count is 1 and RemovedItems[0] is the deselected item).

##### 2nd SelectionChanged event:
`SelectionChangedEventArgs.RemovedItems.Count` = 1 even though the SelectionChangedEventArgs.RemovedItems[0] returns `null`. The SelectionChangedEventArgs.AddedItems are correct here (Count is 1 and AddedItems[0] is the newly selected item).

Thus, not only do we have to fix the duplicated event raise here but we also have to make sure that SelectionChangedEventArgs.*Items.Count is 0 when there is no valid item in the list (basically matching the behavior of ListView's SelectionChanged event).

**Comment by Felix-Dev** [comment]
Observation 2: The duplicated SelectionChanged event is only raised when the user changes the slection by *clicking*. Selecting a ne item either programmatically or via keyboard focus, only raises one SelectionChanged with both AddedItems and RemovedItems of the SelectionChangedEventArgs instance being populated correctly.

(Reason being that we listen to the RadioButton.Uchecked and RadioButton.Checked event. Changing that to RadioButton.Clicked should provide a solution here.)

**Comment by AndreiHarasemiuc** [comment]
Is there any way around this?
