### ISSUE TITLE
ProgressRing determinate mode animation feels slow (~3 s) when initial Value is set to 100

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#3134]
**Describe the bug**

I have a ListView that display status of various items. One important thing the item display's is the download percentage. I am using the determinate ProgressRing to display the percentage.

One issue I noticed is that when the item view is displayed, the animation takes close to 3 seconds to animate to the 100% value. Which feels very slow. This is especially true, when the initial value is already 100%.

Also, because of virtualisation the item view is reused with different view models and hence every time a new viewmodel is used that has a 100% for download status, the control is animated again (taking ~3 seconds). This happens when you scroll up and down enough to trigger the virtualisation.

**Expected behavior**

The animation should probably take less than a second. 

Also, for virtualisation scenario ideally there should be no animation. I can understand that is going to be not possible unless animation is completely disabled for 100% (value is already 100% when the control is loaded/displayed).

**Screenshots**

**Version Info**

NuGet package version: 
2.5.0-prerelease.200812001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Would it be possible to include Gif's of the animation in question?

**Comment by harvinders** [comment]
@StephenLPeters Give me a day or so, I need a tool record it. Gaming bar is disabled for me.

**Comment by StephenLPeters** [comment]
PowerPoint has a good screen recording option if that is available to you.

**Comment by harvinders** [comment]
@StephenLPeters  
The one drive video link is https://1drv.ms/v/s!AjCjW_y_qIQIga88B8RNM1f1r4Dsbg?e=L9IJPH

Many of the items have the download status of 100%. Notice when I first load the items. The progress ring takes time to reach 100%. I think the animation should not take that long. 

Also at the very end of the video, when I scroll down and scroll up again I suspect the virtualisation kicks in and the progress ring again takes time to show the status of 100%.

**Comment by StephenLPeters** [comment]
Thanks, very helpful!

**Comment by robloo** [comment]
Here is the referenced video as a gif in case the OneDrive link goes bad in the future. If you didn't want this so prominently displayed I can delete this comment.

![ezgif-7-832a45dedf22](https://user-images.githubusercontent.com/17993847/90993652-ab8f6780-e583-11ea-91da-00ffeffc043d.gif)

**Comment by harvinders** [comment]
@robloo. I would appreciate it if we can remove the gif, it is from an
unreleased app.

I would try to upload another video before I remove this one from onedrive.

**Comment by AzAgarampur** [comment]
Question: Why did we move away from the spinning dots? Almost every progress ring uses that, even the Windows bootloader.
