### ISSUE TITLE
Dropdown glyph alignment and sizing

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#3140]
**Describe the bug**

There are several controls which have a sort of "dropdown" glyph - `ComboBox`, `NumberBox`, `SplitButton`. Each, however, has a bit different glyphs as well as button alignment and size:

![image](https://user-images.githubusercontent.com/1075116/90329341-4e544e80-dfa4-11ea-9952-22ad0c08d209.png)

Only `SplitButton` and `ComboBox` seem to have "overlapping" arrows, but others differ. For me, the consistency would be greatly improved if:

1. `NumberBox` inline style would use the same down glyph as `ComboBox` and it would be the same size and alignment
2. The compact style buttons of `NumberBox` would become a bit wider to match the "width" of a `ComboBox` dropdown button or at least aligned with the centre of its glyph.

**Steps to reproduce the bug**

Use the following XAML for testing:
```
<StackPanel>
    <StackPanel.RenderTransform>
        <ScaleTransform ScaleX="5" ScaleY="5" />
    </StackPanel.RenderTransform>
    <ComboBox Width="120" HorizontalAlignment="Left" />
    <controls:NumberBox HorizontalAlignment="Left" Width="120" SpinButtonPlacementMode="Inline" />
    <controls:NumberBox HorizontalAlignment="Left" Width="120" SpinButtonPlacementMode="Compact" />
    <controls:SplitButton HorizontalAlignment="Left" Width="120" />
</StackPanel>
```

**Expected behavior**
Improved consistency in vertically structured input-based applications.

![image](https://user-images.githubusercontent.com/1075116/90329417-0e419b80-dfa5-11ea-965c-8a4d78164dd8.png)

**Screenshots**

**Version Info**

NuGet package version: 

2.5.0-prerelease.200812001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by robloo** [comment]
NumberBox might make sense as a separate case. The up/down glyphs there are for a different purpose and differences for the repeat buttons might actually be a good idea. 

ComboBox and SplitButton certainly should be the same. Alignment (right-side margin) in all the controls should be standard as well I think.

**Comment by StephenLPeters** [comment]
@chigy fyi
