### ISSUE TITLE
Tab scroll button inconsistently clipped 

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#3144]
_Originally posted by @simonratner in microsoft/terminal#7313._

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version (if applicable): Windows Terminal Preview [Version: 1.2.2022.0]

Display scale: 125%.
```

# Steps to reproduce

Open more tabs than fit horizontally across the window, and observe the tab scroll buttons.

# Expected behavior

Tab scroll buttons consistent in size and style to other buttons in the tab/title bar (new tab, dropdown, min/max/close), and aligned to the same baseline

# Actual behavior

Tab scroll buttons differ in style and alignment from all other buttons, and the icon within the scroll-right button appears clipped.

![image](https://user-images.githubusercontent.com/667283/90361717-c443ce80-e013-11ea-99ed-cea9edccb08a.png)

**Comment by StephenLPeters** [comment]
similar to #1650

**Comment by Felix-Dev** [comment]
I would like to take a look at this.

**Comment by StephenLPeters** [comment]
Awesome, thank you!
