### ISSUE TITLE
RadioButtons: Custom ItemTemplate is not automatically prefaced by a RadioButton if it doesn't specify one itself as its root element

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3159]
**Describe the bug**
According to https://github.com/microsoft/microsoft-ui-xaml/issues/333#issuecomment-468839517 by @kikisaints, a custom ItemTemplate for the `RadioButtons` control will be prefaced by a RadioButton icon:

> Meaning you can customize your data template in any way you like, and get that exact definition represented in the RadioButton group, but prefaced with a RadioButton icon.

Thus, if we have the following XAML:
```xml
<muxc:RadioButtons Header="Test Group"
                   ItemsSource="{x:Bind Options}">
    <muxc:RadioButtons.ItemTemplate>
        <DataTemplate x:DataType="local:OptionDataModel">
            <StackPanel Orientation="Horizontal">
                <TextBlock Text="{x:Bind Label}" Margin="5"/>
                <HyperlinkButton Content="My Link" Margin="5"/>
                <Rectangle Fill="Orange" Width="10" Height="10" Margin="5"/>
            </StackPanel>
        </DataTemplate>
    </muxc:RadioButtons.ItemTemplate>
</muxc:RadioButtons>
``` 
and code-behind like this:
```cs
public class OptionDataModel
{
    public string Label { get; set; }
}

public IList<OptionDataModel> Options { get; set; }

public MainPage()
{
    this.InitializeComponent();

    Options = new List<OptionDataModel>
    {
        new OptionDataModel() { Label = "Item 1" },
        new OptionDataModel() { Label = "Item 2" },
        new OptionDataModel() { Label = "Item 3" },
        new OptionDataModel() { Label = "Item 4" },
        new OptionDataModel() { Label = "Item 5" },
    };
}
```

The expected UI is this:
![image](https://user-images.githubusercontent.com/1398851/90634864-ae5b2700-e228-11ea-92ce-a539216626e4.png)

But the actual UI we get is this:
![image](https://user-images.githubusercontent.com/1398851/90634900-c2068d80-e228-11ea-88d5-5de68ac2659e.png)

As you can see, there are no RadioButton icons, plus our items  are no longer represented as `RadioButton`s internally, thus we cannot select our options in a mutually exclusive way (actually, we cannot select them at all).

**Version Info**

NuGet package version: 
Newest WinUI 2.5 preview.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I would like to fix this.

**Comment by robloo** [comment]
It seems like the current functionality might be by design. How do you change the look of the radio button itself otherwise?

**Comment by Felix-Dev** [comment]
@robloo The issue that the current impementation makes this RadioButtons control more or less useless when a custom ItemTemplate is specified. You cannot select items mutually exclusive any longer, let alone select them at all.

I'd say this is the same as if I specifiy a button as a child element of a RadioButtons controls:

```xml
<muxc:RadioButtons>
    <Button Content="OptionButton1"/>
    <Button Content="OptionButton2"/>
</muxc:RadioButtons>
```
![image](https://user-images.githubusercontent.com/1398851/90643537-ff244d00-e233-11ea-9a4f-2a0d1121fa56.png)

If you want to style the RadioButton icon itself, my guess was you could do it like this:
```xml
<muxc:RadioButtons>
    <muxc:RadioButtons.Resources>
        <Style x:Key="DefaultRadioButtonStyle" TargetType="RadioButton">
            <!---->
        </Style>
    </muxc:RadioButtons.Resources>
    <Button Content="OptionButton1"/>
    <Button Content="OptionButton2"/>
</muxc:RadioButtons>
```
so you overwrite the default RadoButton style in use. Unfortunately, that does not appear to work.

**Comment by robloo** [comment]
> The issue is that the current impementation makes the RadioButtons control more or less useless when a custom ItemTemplate is specified. 

I definitely see there is an issue here, but we don't want to make it useless for those that need to change the radio button style too :)

> Also, I think adding a RadioButton icon by default is the correct step here, as we are in a RadioButtons control, so RadioButtons are expected here.

I couldn't agree more!

> I agree with you though that the RadioButton itself should be stylable. I would expect that to work just like I would normally style a RadioButton (by specifying a new RadioButton style), just that here we overwrite the existing default RadioButton style.

I agree with your thinking overall, we just have to figure out how to support styling the radio button itself too separate from the item content if needed. Changing the DefaultRadioButtonStyle across the board should be supported -- but it should be possible to do this on a per-control basis as well. (Actually, UWP needs implicit styles and to also define keys for all system default styles... separate issue). Adding a new property for the style of the RadioButton itself might work.

We also have to consider right-to-left text layouts where the RadioButton should probably be on the right-hand side.

**Comment by ranjeshj** [comment]
Would the below pattern work ? That way you can set the properties on the RadioButton directly and don't need a Style.
```
<muxc:RadioButtons Header="Test Group"
                   ItemsSource="{x:Bind Options}">
    <muxc:RadioButtons.ItemTemplate>
        <DataTemplate x:DataType="local:OptionDataModel">
         **<RadioButton>**
            <StackPanel Orientation="Horizontal">
                <TextBlock Text="{x:Bind Label}" Margin="5"/>
                <HyperlinkButton Content="My Link" Margin="5"/>
                <Rectangle Fill="Orange" Width="10" Height="10" Margin="5"/>
            </StackPanel>
          **</RadioButton>**
        </DataTemplate>
    </muxc:RadioButtons.ItemTemplate>
</muxc:RadioButtons>
```

**Comment by Felix-Dev** [comment]
@ranjeshj That works as expected (only adjusted some Margins for better design):

![image](https://user-images.githubusercontent.com/1398851/90657902-3a7a4800-e243-11ea-8e32-45b0828dc002.png)

This should also make RadioButton customizattion easily achievable by just setting the style on the RadioButton.

The question is: Is this just a workaround? or is this how the ItemTemplate has to be styled? In other words, do developers have to explictily specify a RadioButton in the Item or do they not?

**Comment by ranjeshj** [comment]
I see. If the RadioButton containers are automatically created by RadioButtons control, then there is no easy way to style that without exposing a Style/StyleSelector.

**Comment by robloo** [comment]
A DataTemplate that requires a RadioButton as the root element actually makes sense to me in this case. It is a RadioButtons control after all. Technically speaking, are there actually any limitations with @ranjeshj solution? It seems to me it works in all cases. If you aren't using a RadioButton in the style then another repeater control should be used. We should just add a note in the documentation for this.

**Comment by Felix-Dev** [comment]
@robloo @ranjeshj How about this: If we don't specifiy a RadioButton as the root of our ItemTemplate, then WinUI will wrap that ItemTemplate in a RadioButton. No easy customization available.

However, if more styling flexibility for the RadioButton itself is required, I can specify a RadioButton as the root of the ItemTemplate and set all kinds of properties on it. In that case, WinUI won't wrap a RadioButton around the ItemTemplate as it already is a RadioButton.

**Comment by Felix-Dev** [comment]
@robloo Do you think we should also an an ItemTemplateSelector to the RadioButtons control? That API is missing so far and would give even more fine granular styling possibilities. Plus, it would help bring the same level of customization options to the RadioButtons control as known from other such Item controls.

**Comment by robloo** [comment]
> @robloo Do you think we should also add an ItemTemplateSelector API to the RadioButtons control? 

It wouldn't hurt. However, I'm not sure it's really justified. The RadioButons is not a general-purpose control. I can't really envision scenarios where we would need to change the template... Except maybe for when an item is checked.

**Comment by Felix-Dev** [comment]
@robloo Yeah, I do not recall `ItemTemplateSelector` being an API request until now. Thta might change but it seems like we don't have to invest resources into that for now.

And yes, we should add documentation how to customize the actual RadioButtons for the RadioButtons control (for example by specifying an ItemTemplate with a `RadioButton` as its root element).
