### ISSUE TITLE
Proposal: MUXC ScrollView should implement IScrollAnchorProvider

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3164]
# Proposal: MUXC ScrollView should implement IScrollAnchorProvider

## Summary

The muxc ScrollView should implement the IScrollAnchorProvider interface, just like the wuxc version does.

## Rationale

* Consistency with wuxc ScrollViewer
* Makes it easier to switch to muxc ScrollViewer

## Scope

| Capability | Priority |
| :---------- | :------- |
| Be consistent with existing wuxc ScrollViewer | Must |

**Comment by StephenLPeters** [comment]
@RBrid I'm surprised this isn't already the case.. I this a bug or a feature proposal?

**Comment by chingucoding** [comment]
The interesting thing is that ScrollPresenter does implement that interface, but the ScrollView which contains a ScrollPresenter does not.

**Comment by RBrid** [comment]
Yes this is intentional - By Design. The ScrollView publicly exposes the three IScrollAnchorProvider APIs and delegates the calls to its inner ScrollPresenter which actually implements the interface.

**Comment by chingucoding** [comment]
@RBrid [ScrollView](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.scrollview?view=winui-2.5.0-prerelease.200708003) does implement RegisterAnchorCandidate and UnregisterAnchorCandidate, but I can't seem to find the [CurrentAnchor property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.iscrollanchorprovider.currentanchor?view=winrt-19041#Windows_UI_Xaml_Controls_IScrollAnchorProvider_CurrentAnchor) that [IScrollAnchorProvider](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.iscrollanchorprovider?view=winrt-19041) has. Is it missing in the docs or is this intentional too?

**Comment by RBrid** [comment]
I added it recently - it should be in the code at least:  see #2936 "Adding public ScrollView.CurrentAnchor read-only property"
Not sure if the doc was updated accordingly.

**Comment by chingucoding** [comment]
Oh must have missed that PR, sorry about that. In that case, there isn't anything to track with this issue then, given that it is by design to not implement the interface on ScrollView but instead on ScrollPresenter.

**Comment by RBrid** [comment]
Thank you Marcel!
