### ISSUE TITLE
[RNW] Xaml Islands application leak memory when closing an instance of DesktopWindowXamlSource

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#3169]
This has already been fixed in winui3 but we need a public issue to track for our partners using OS XAML
[Bug 24039954](http://osgvsowi/24039954)

**Comment by stmoy** [comment]
If this has already been fixed, should we close this?

**Comment by asklar** [comment]
@stmoy it's only fixed in WinUI 3, it would still repro in OS XAML which is what current partners would use

**Comment by sylveon** [comment]
Note that I **cannot** use WinUI 3 because of the recent announcement of unpackaged support being pushed back to 3.1. So this bug and #2817 are still relevant, huge blockers, and should be fixed. I cannot wait to late 2021.

**Comment by pratikone** [comment]
@asklar  the bug link is broken so i cannot verify the status of internal bug. could you see if this is still an issue ? closing it for now.

**Comment by asklar** [comment]
yeah, sadly this GitHub issue is so old (and still open) that the system we used to link bugs with is now dead and there is a new one...

The new link is http://task.ms/24039954

Reopening.
