### ISSUE TITLE
ProgressRing: Determinate with Lottie only works with increasing value

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#3173]
**Describe the bug**
ProgressRing with Lottie not working if the value is counted down. When the value is started for example with the maximum value and count down, the Lottie animation breaks.

**Steps to reproduce the bug**

1. Set the value (for example same as maximum)
2. Set IsIndeterminate to false
3. Count down the value (with timer or something else)

**Expected behavior**
The decreasing value should work with Lottie animation.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.5.0-prerelease.200812001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by chingucoding** [comment]
I would like to look into this, if that's fine with everyone else.

**Comment by karenbtlai** [comment]
I believe it may be something to do with the playback rate for AnimatedVisualPlayer. Counting down is currently not a supported ProgressRing scenario, and will need to be implemented.

**Comment by chingucoding** [comment]
So this isn't supported by the animation itsself? I was able to "support" this by setting the playback rate to -1 when decreasing, however the progress  just jumps to the new value, it doesn't animate.

**Comment by jp-weber** [comment]
Any updates? For this problem only a new animation would have to be implemented, which is used when the new value of the property change is smaller than the old one.
