### ISSUE TITLE
MenuFlyout acrylic effect doesn't work in light theme

### ISSUE THREAD

**Issue by Alkanores** [microsoft/microsoft-ui-xaml#3185]
### **Describe the bug**
MenuFlyout acryllic effect show dark solid color (it is possible that this is due to the shadows of this menu, I link 2 images, which prove it).

### **Steps to reproduce the bug**

1. Create any element & add Menu Flyout
2. Add this Acryllic for light/dark theme(change TintColor to White/Black respectively)
3. Add Grid MenuFlyout (or any MenuFlyout)

```xaml
xmlns:muxm="using:Microsoft.UI.Xaml.Media"

....

<muxm:AcrylicBrush 
    x:Key="FlyoutMenuAcrylic" 
    BackgroundSource="Backdrop"
    TintOpacity="0.2"
    TintLuminosityOpacity="0.4"
    TintColor="(here White or Black color)"
    />

 ....
    
<MenuFlyout>
    <MenuFlyout.MenuFlyoutPresenterStyle>
        <Style TargetType="MenuFlyoutPresenter">
            <Setter Property="Background" Value="{ThemeResource FlyoutMenuAcrylic}" />
        </Style>
    </MenuFlyout.MenuFlyoutPresenterStyle>
    <MenuFlyoutItem FontSize="13px" Text="First">
        <MenuFlyoutItem.Icon>
            <FontIcon Glyph="&#xE751;"/>
        </MenuFlyoutItem.Icon>
    </MenuFlyoutItem>
    <MenuFlyoutItem FontSize="13px" Text="Second">
        <MenuFlyoutItem.Icon>
            <FontIcon Glyph="&#xE74D;"/>
        </MenuFlyoutItem.Icon>
    </MenuFlyoutItem>
    <MenuFlyoutItem FontSize="13px" Text="Third">
        <MenuFlyoutItem.Icon>
            <FontIcon Glyph="&#xE734;"/>
        </MenuFlyoutItem.Icon>
    </MenuFlyoutItem>
</MenuFlyout>
```

4. See, what in dark theme acrylic shows background, but in light theme acrylic is a gray solid color

### **Expected behavior**
In light theme acrylic effect must show blured green color

### **Screenshots**

*(with win+shift+s, without shadows, light theme)*
![image](https://user-images.githubusercontent.com/49155506/90961268-50407500-e4b0-11ea-91b9-ae7389aab014.png)

*(with print screen, with shadows, light theme)*
![image](https://user-images.githubusercontent.com/49155506/90961258-474fa380-e4b0-11ea-9218-b9a735994dd6.png)

*(with win+shift+s, without shadows, dark theme)*
![image](https://user-images.githubusercontent.com/49155506/90961487-12dce700-e4b2-11ea-80e9-44373cace71e.png)

*(with print screen, with shadows, dark theme)*
![image](https://user-images.githubusercontent.com/49155506/90961497-22f4c680-e4b2-11ea-8f41-4de872d79c37.png)

###  **Version Info:**

|     Property      |      Version       |
| :--------------- | :--------------- |
| OS version | Windows 10, may update (build 19041.450) |
| Microsoft.UI.Xaml | v2.4.3 |

### **NuGet package version:** 

[Microsoft.UI.Xaml 2.4.3]
[Microsoft.UI.Xaml.2.4.2]

### **Windows app type:**
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       | didn't check   |
| May 2019 Update (18362)            | didn't check  |
| October 2018 Update (17763)        | didn't check  |
| April 2018 Update (17134)          | didn't check  |
| Fall Creators Update (16299)       | didn't check  |
| Creators Update (15063)            | didn't check   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes  |

**Comment by YuliKl** [comment]
Thank you for reporting this. I think you're seeing expected behavior with shadows rendering behind the acrylic, causing the flyouts to look very dark. In part, this is because we don't really support such transparent acrylic to avoid legibility concerns.

**Comment by Alkanores** [comment]
> this is because we don't really support such transparent acrylic to avoid legibility concerns.

But why then Acrylic effect works in dark theme?

**Comment by YuliKl** [comment]
Both acrylics work, but the shadow is making the acrylic look darker. In dark theme, the darkening looks as expected, while it looks too dark in light theme.

**Comment by Alkanores** [comment]
Will this be fixed? Or this isn't bug?

**Comment by YuliKl** [comment]
It's not a bug, although we are looking into updates to the shadow implementation to enable some sort of cutout that avoids the muddy visual you're seeing.

**Comment by ad1Dima** [comment]
seeing this with latest Xaml Controls Gallery from store 
![image](https://user-images.githubusercontent.com/3244664/123525626-5caee300-d6fc-11eb-863e-702274173293.png)

**Comment by michaelcoelsch** [comment]
I have the same problem here as @ad1Dima.
Waiting for a fix.

**Comment by StephenLPeters** [comment]
should be fixed with this change https://github.com/microsoft/microsoft-ui-xaml/pull/5297

**Comment by movpushmov** [comment]
> should be fixed with this change #5297

![image](https://user-images.githubusercontent.com/49155506/125997898-0b8e2d5b-0388-4418-9491-58f306fa28d6.png)
![image](https://user-images.githubusercontent.com/49155506/125997936-9bdbfdbc-9349-4014-af19-f943bd866e62.png)

# And this shadow doesn't hide after app hiding!

![image](https://user-images.githubusercontent.com/49155506/125998001-68bab739-11e3-4a01-be70-09fecd5ee0c8.png)

**Comment by movpushmov** [comment]
@StephenLPeters

**Comment by StephenLPeters** [comment]
Which version of Winui is your repro app using?

**Comment by movpushmov** [comment]
> Which version of Winui is your repro app using?

@StephenLPeters WinUI 2.6

**Comment by StephenLPeters** [comment]
This has been fixed internally.
