### ISSUE TITLE
Question: How do you set selected and unselcted foreground color for a textblock in a MenuItemTemplate for the NavigationView control?

### ISSUE THREAD

**Issue by Going-Gone** [microsoft/microsoft-ui-xaml#3193]
Is there a way to modify the template textblock behavior based on the navigation view visual state?
When the menu item is selected, the text foreground should be black.
When the menu item is not selected, the text foreground should be white.

I've not been able to figure out how to modify the behavior of the template textbox for the menu items.

```
      <DataTemplate x:Key="MenuItemTitleTemplate">
            <Grid >
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto" />
                </Grid.RowDefinitions>
                <TextBlock Text="{Binding MenuItemText}" 
                           Style="{StaticResource NavigationViewItemHeaderTextStyle}" />
            </Grid>
        </DataTemplate>

``` 
       <muxc:NavigationView  
                x:Name="nvSubMenu" 
                IsBackButtonVisible="Collapsed"
                IsSettingsVisible="False"
                IsEnabled="True"
                HorizontalAlignment="Left"              
                PaneDisplayMode="Top"
                IsPaneToggleButtonVisible="False"
                AlwaysShowHeader="False"
                IsBackEnabled="False" 
                MenuItemsSource="{Binding list}"
                MenuItemTemplate="{StaticResource MenuItemTitleTemplate}">
            
        </muxc:NavigationView>

> 
> 
> @Going-Gone to double-check, do you mean TextBox or TextBlock? You're using `TextBlock` in your data template.
> 
> Are you also planning on changing the background of the selected menu item to ensure the text remains legible?

**Comment by YuliKl** [comment]
@Going-Gone to double-check, do you mean TextBox or TextBlock? You're using `TextBlock` in your data template.

Are you also planning on changing the background of the selected menu item to ensure the text remains legible?

**Comment by YuliKl** [comment]
If I'm understanding your scenario correctly, the easiest way to achieve this is with light weight styling. Overwrite the brushes defined for NavigationViewItemForeground* resources to use values you prefer. https://github.com/microsoft/microsoft-ui-xaml/blob/4d0baa4cc846de73969953b8e57772e97d8e3149/dev/NavigationView/NavigationView_rs1_themeresources.xaml#L32

**Comment by Going-Gone** [comment]
> 
> 
> @Going-Gone to double-check, do you mean TextBox or TextBlock? You're using `TextBlock` in your data template.
> 
> Are you also planning on changing the background of the selected menu item to ensure the text remains legible?

Apologies, TextBlock. 
Yep the background is set with 
```
        <SolidColorBrush x:Key="TopNavigationViewItemBackgroundSelected" Color="White"/>
        <SolidColorBrush x:Key="NavigationViewItemBackground" Color="#477DAC"/>

**Comment by Going-Gone** [comment]
> 
> 
> If I'm understanding your scenario correctly, the easiest way to achieve this is with light weight styling. Overwrite the brushes defined for NavigationViewItemForeground* resources to use values you prefer.
> 
> https://github.com/microsoft/microsoft-ui-xaml/blob/4d0baa4cc846de73969953b8e57772e97d8e3149/dev/NavigationView/NavigationView_rs1_themeresources.xaml#L32



> 
> 
> If I'm understanding your scenario correctly, the easiest way to achieve this is with light weight styling. Overwrite the brushes defined for NavigationViewItemForeground* resources to use values you prefer.
> 
> https://github.com/microsoft/microsoft-ui-xaml/blob/4d0baa4cc846de73969953b8e57772e97d8e3149/dev/NavigationView/NavigationView_rs1_themeresources.xaml#L32

That works, Thanks.

**Comment by YuliKl** [comment]
Sounds like the question is resolved. Closing.
