### ISSUE TITLE
Cannot resolve TargetName HeaderContentPresenter on 17134 and lower

### ISSUE THREAD

**Issue by andrewleader** [microsoft/microsoft-ui-xaml#3199]
I'm seeing crashes appear in App Center specifically on users running build 17134 and lower with the following...

```
System.Exception: No installed components were detected. Cannot resolve TargetName HeaderContentPresenter.
```

**Repro steps**
Not sure... It seems like a problem with using WinUI in a complex app

**Expected behavior**
Don't crash

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.3

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | No   |
| November 2019 Update (18363)       | No   |
| May 2019 Update (18362)            | No   |
| October 2018 Update (17763)        | No   |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Possibly related to #2719, I added the workaround and will be updating my app, I'll see if this error also stops happening

**Comment by StephenLPeters** [comment]
Without a crash dump, or at least knowing which type is causing this crash I think it is going to be difficult to track this down. Is there anymore info you are able to provide?  I wonder if we have a type that we changed the template for and removed the HeaderContentPresenter, but the app was referencing it and that is causing the crash on newer versions.

**Comment by StephenLPeters** [comment]
here is some info on collecting crash dumps https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by andrewleader** [comment]
Closing as dupe of #2719, I'm no longer seeing this crash after implementing the workaround in #2719. So must have been related to that (hopefully this issue helps anyone else who runs into that!)
