### ISSUE TITLE
Question: Do WinUI Desktop Application (C++) support MFC classes and COM Interfaces?

### ISSUE THREAD

**Issue by densonpd** [microsoft/microsoft-ui-xaml#3210]
In an MFC application, there will be logic implemented in event handlers and those logics may contain MFC classes.
- While migrating an MFC UI to WinUI application, is it possible to re-use those logics containing MFC classes CString, CArray etc?
- Is it possible to include a library which has MFC dependency in WinUI Desktop Application?
- Can WinUI applications communicate with other COM applications?

**Comment by YuliKl** [comment]
@MikeHillberg FYI
