### ISSUE TITLE
Visual Studio 2019 Preview Version 16.8.0 Preview 2.0 unable to create WinUi 3 project

### ISSUE THREAD

**Issue by alexandrevk** [microsoft/microsoft-ui-xaml#3211]
**Describe the bug**
Unable to create WinUi project in Visual Studio 2019 Preview Version 16.8.0 Preview 2.0 
The above VS version is incompatible with .NET 5 preview 5. WinUi in desktop project failed to create with .NET 5 preview 8

1. Go to 'File/New/Project
2. Select C# Windows WinUi Blank App, Packaged(WinUi in desktop)  template
3. Click Create

**Expected behavior**
new two projects created

**Actual behavior**
Error message: ... "targetPlatformIdentifier" cannot have zero length ...  Project was not created.

**Screenshots**
![WinUi_error](https://user-images.githubusercontent.com/13483929/91604025-ce72a080-e922-11ea-8891-4691fd645124.PNG)

NuGet package version: 

Windows app type:
 | Desktop         |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |  |
| Fall Creators Update (16299)       |   |
| Creators Update (15063)            |   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        | |
| IoT                |  |

**Additional context**

**Comment by lolametro** [comment]
Can reproduce, I have the same problem.

**Comment by alwu-msft** [comment]
VS 2019 16.8 Preview 2 includes .Net 5 Preview 8, which WinUI 3 Preview 2 is unfortunately not compatible with. However, now that VS 2019 16.7 is generally available, our recommendation is that you use that instead of the VS 2019 Preview for now while we work on supporting newer previews of .Net 5.

**Comment by lolametro** [comment]
Thanks for the info, this works!
Could you also update the documentation to mention this? https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-2

**Comment by alwu-msft** [comment]
I'm glad to hear that it works for you! We've already started the process of updating the documentation.

**Comment by zsolt3991** [comment]
Since Visual Studio 16.8 is now GA, when can we expect a compatibility update to be able to use WinUi project templates?

**Comment by sigmarsson** [comment]
![image](https://user-images.githubusercontent.com/43340959/99255670-92a9f180-2814-11eb-8b58-78b1657c7be6.png)

**Comment by bpulliam** [comment]
If you still see this on current builds, please open a new issue with updated repro steps.  Thanks!
