### ISSUE TITLE
Image control become black sometimes when used in ItemsRepeater

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#3214]
**Describe the bug**

**Steps to reproduce the bug**

I'm using Image control in ItemsRepeater. The general XAML is like below.

```
<ScrollViewer>
   <ItemsRepeater> //vertical
      <StackPanel>
         <TextBlock/>
         <ItemsRepeater>//horizontal 
             <Image/>
         </ItemsRepeater>
      </StackPanel>
   </ItemsRepeater>
</ScrollViewer>
```
But sometimes, when I go to other pages and back, some Image control becomes black. Sometimes, I scroll up/down, then scroll back, the same situation. I guess the image is disposed of by memory when navigating to other pages. But I'm not sure.
Are there any solutions?

**Expected behavior**

Show the images, not the black area.

**Screenshots**

![image](https://user-images.githubusercontent.com/14960168/91653202-0fa8b300-ead1-11ea-8beb-c48bb666dd51.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.3.200213001]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop           |  Yes   |
| Xbox               |  Yes   |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@hupo376787 Are you able to provide a repro app that we could use to debug this issue?

**Comment by hupo376787** [comment]
I'm trying to reproduce a repo.
