### ISSUE TITLE
What magic is applied to Binding.Path property so it is default?

### ISSUE THREAD

**Issue by mc0re** [microsoft/microsoft-ui-xaml#3215]
I'm trying to create a custom extension (localization from a server-side database).
The goal:
```xaml
<AppBarButton Label="{l:Text TextId=About}" Click="{x:Bind About_Click}"/>
```
I tried:
```csharp
    /// <summary>
    /// Provides a localized string for UI.
    /// </summary>
    [MarkupExtensionReturnType(ReturnType = typeof(string))]
    public class TextExtension : MarkupExtension
    {
        #region Properties

        /// <summary>
        /// Text ID to show.
        /// </summary>
        public string TextId { get; set; }

        #endregion


        #region Init and clean-up

        public TextExtension()
        {
            // Do nothing
        }


        public TextExtension(string textId)
        {
            TextId = textId;
        }

        #endregion


        #region Main functionality

        protected override object ProvideValue()
        {
            return TextId;
        }

        #endregion
    }
```

But having the parameterized constructor does not seem to help, I get an error:
```
XamlCompiler error WMC0610: The XAML Binary Format (XBF) generator reported syntax error '0x09d7'
```

So I assume there is a class or property attribute. But I can't find the source code for `Binding` markup extension. Can you help me out here?

**Comment by StephenLPeters** [comment]
@MikeHillberg Can you weigh in here?

**Comment by mc0re** [comment]
Bonus question - how do I force the app to redraw when the user changes the language?

**Comment by alwu-msft** [comment]
Correct, support for parameterized constructors isn't currently on the radar. @mc0re is the motivation syntactic cleanliness, or is there some kind of desired functionality that requires initialization of the markup extension's state to happen in the constructor and which can't be equivalently done via properties that are set by the markup and then read in the extension's `ProvideValue()` implementation?

**Comment by mc0re** [comment]
@alwu-msft, It's the desire to have a shorter code :-)  So in short, one shouldn't expect that feature any time soon.
