### ISSUE TITLE
Cascading styles in xaml

### ISSUE THREAD

**Issue by mustafaasaber** [microsoft/microsoft-ui-xaml#3218]
I hope introducing cascading styles in xaml like one on css

**Comment by robloo** [comment]
WPF is also a bit more functional in this area.

**Comment by StephenLPeters** [comment]
@kikisaints fyi

**Comment by chrisglein** [comment]
I'm certainly down with taking the best learnings from CSS and applying to XAML in a thoughtful way. But it's certainly an area of strong emotions. See [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/696) where I just used the name of CSS in the title and the response was very divided.

This is obviously a topic that requires a lot of design work. @kikisaints I know we've had lots of discussion about taking inspiration from CSS in a couple spots. Are there some proposals we can link to?

**Comment by mdtauk** [comment]
As a first step it could be useful to have ResourceDictionaries and a new CSS format interchangable.

**Comment by robloo** [comment]
I'm hoping this will be considered with all the styling rework ongoing within Microsoft. I believe they also plan to generate all styles for web/uwp, etc. from common design elements and definitions (I can't find the repo a the moment). Something like this would then be quite useful to combine css/xaml ideas.

**Comment by mdtauk** [comment]
> I'm hoping this will be considered with all the styling rework ongoing within Microsoft. I believe they also plan to generate all styles for web/uwp, etc. from common design elements and definitions (I can't find the repo a the moment). Something like this would then be quite useful to combine css/xaml ideas.

As I understand it, there will be a Figma plugin, which will allow you to set both global and specific properties on components you use to design your apps.  It will then allow you to export:
- XAML Resource Dictionaries for WinUI (possibly also React Native for Windows;
- CSS/TypeScript for Fast and FluentUI React web;
- iOS and macOS resources for FluentUI components and React Native for macOS;
- Android assets and resources for FluentUI components;

So designers can design once, export the code and assets, and the developers get to import those into their app projects.

Not sure how this will work for Xbox app designs, I hope those will come along with WinUI 3.X for Xbox, featuring open source control templates and app layouts.

----

![Fluent Design overview](https://user-images.githubusercontent.com/7389110/99161364-7b221a00-26e9-11eb-8d20-f75401f4f2fc.png)


**Design Tokens** is the approach being adopted, which essentially separates the colour values used in a design system, from the actual uses of those values.  

So you would define a group of _Global_ colours, fonts, thicknesses, strokes, gradients, margins, etc

Those values would be grouped typically by State.  So Background.Rest or Background.Pressed.

Then you create an _Alias_ which would be something like Control.Border, Flyout.Background or Text.Fill - which would consume those grouped values.

All of these create a Style Dictionary for the design language.

From what I can see from Microsoft's work so far [FluentUI Token Pipeline](https://github.com/microsoft/fluentui-token-pipeline)

_**Fluent Design would have values in JSON format**_
```JSON
{	
"Global": {
	"Color": {
		"Grey": {
			"0": { "value": "hsl(0, 0%, 0%)" },

			"100": { "value": "hsl(0, 0%, 100%)" }
		}
	},
	"Stroke": {
		"Width": {
			"0": { "value": 0 },
			"100": { "value": 1 }
		}
	},
	"Corner": {
		"Radius": {
			"None": { "value": 0 },
			"Small": { "value": 2 },
			"Medium": { "value": 4 }
		}
	},		
	"Font": {
		"Family": {
			"Default": { "value": "\"Segoe UI\", Roboto, \"SF Pro Text\", \"Helvetica Neue\", Helvetica, Arial, sans-serif" }
		},
		"Weight": {
			"Regular": { "value": 400 },
			"Semibold": { "value": 600 }
		},
		"Size": {
			"100": { "value": 10 },
			"200": { "value": 12 },
			"300": { "value": 14 },
		},
		"LineHeight": {
			"100": { "value": 14 },
			"200": { "value": 16 },
		}
	}
},
```

**_A Group of values_**
```JSON
"BrandBackground": {
	"Fill": {
		"Color": {
			"Rest": { "aliasOf": "Global.Color.Brand.42" },
			"Hover": { "aliasOf": "Global.Color.Brand.40" },
			"Pressed": { "aliasOf": "Global.Color.Brand.24" },
			"Disabled": { "aliasOf": "Global.Color.Grey.94" }
		}
	}
},
```

**_And those Values applied to a "style"_**
```JSON
"ButtonPrimary": {
	"Content": {
		"Font": { "aliasOf": "Set.Control.Font" },
		"Fill": { "Color": { "aliasOf": "Set.NeutralForegroundInvertedAccessible.Fill.Color", "Selected": { "aliasOf": "Set.NeutralForegroundInvertedAccessibleSelected.Fill.Color" } } }
	},
	"Icon": {
		"Fill": { "Color": { "aliasOf": "Set.NeutralForegroundInvertedAccessible.Fill.Color", "Selected": { "aliasOf": "Set.NeutralForegroundInvertedAccessibleSelected.Fill.Color" } } }
	},
	"Base": {
		"Fill": { "Color": { "aliasOf": "Set.BrandBackground.Fill.Color", "Selected": { "aliasOf": "Set.BrandBackgroundSelected.Fill.Color" } } },
		"Stroke": {
			"Color": { "aliasOf": "Set.Borderless.Stroke.Color", "Selected": { "aliasOf": "Set.Borderless.Stroke.Color" } },
			"Width": { "aliasOf": "Set.Borderless.Stroke.Width", "Selected": { "aliasOf": "Set.Borderless.Stroke.Width" } }
		},
		"Corner": { "aliasOf": "Set.Control.Corner" },
		"Layout": { "Padding": { "value": [7, 15, 7, 15] } },
		"Shadow": {}
	}
},
```

Images of the Build 2020 demo for this workflow...
----

![figma plugin screen 1](https://user-images.githubusercontent.com/7389110/99161306-d7386e80-26e8-11eb-9b0a-0bda8768ac78.png)
![figma plugin screen 2](https://user-images.githubusercontent.com/7389110/99161331-31393400-26e9-11eb-9d21-e74c17aae3f4.png)
_Figma Plugin_


![example output Swift](https://user-images.githubusercontent.com/7389110/99161300-cdaf0680-26e8-11eb-993f-41045631b6d7.png)
_Swift UI Output_

![example output Xaml](https://user-images.githubusercontent.com/7389110/99161318-0a7afd80-26e9-11eb-8556-937cf9443b4b.png)
_Xaml ResourceDictionary Output_

**Comment by robloo** [comment]
Really awesome summary @mdtauk, Thanks! Thats exactly the info I was looking for. 

I'm excited about this all coming together. I hope they dont hit any technical roadblocks. High-level meta concepts are really a fundamental component of cross platform development in the future.

I also envision a future where control logic can be defined, for example, mathematically like Modelica. Then even source code could be generated in whatever language needed and we can stop re-writing the same controls every time a new language or framework comes around :)

**Comment by mdtauk** [comment]
> Really awesome summary @mdtauk, Thanks! Thats exactly the info I was looking for.
> 
> I'm excited about this all coming together. I hope they dont hit any technical roadblocks. High-level meta concepts are really a fundamental component of cross platform development in the future.
>

I think this is why we are seeing new Control designs being proposed now, so they can share values with these Design Tokens alongside FluentUI Web (which may get a design refresh to match, or if not, will match better with the updated WinUI designs)

**Comment by mdtauk** [comment]
From what I see in the tokens branch XAML - the new naming conventions are logical and clear, however something like **ControlAAFillColorDefault** - I can't figure out what the AA stands for, but @chigy informed me its not a final name, so hopefully once the Design Token work is done - hopefully that will change.

It also seems the plugin will possibly replace the Fluent Theme Editor, and allow exporting a custom theme to use in your app,  whilst by default, will use the default Design Tokens?

**Comment by mdtauk** [comment]
The Button is one of the XAML controls updated to use the new Design Tokens in the feature branch, so I am illustrating how they reference the Lightweight styles, and they reference the Global Design Tokens

![Illustrating the xaml style referencing](https://user-images.githubusercontent.com/7389110/99177666-cfd28e80-2703-11eb-8ca2-7dc7a8d16250.png)

Using the plugin, I think you will be able to override the Global Tokens, probably in App.xaml - those will propagate down to controls and views in the app.

Then the next level down, you can override the Lightweight Styles to allow only certain control types to deviate from the default Fluent Design / WinUI provided values.  App level or page level or view/panel level.

Then there are the properties on the Button control, which you would normally be able to override, but it is not encouraged.  If you wish to alter the PointerOver, Pressed, or Disabled states, you would need to re-template the control.

**Comment by SetTrend** [comment]
Just like to bring this thread back to attention.

**Comment by StephenLPeters** [comment]
@chigy FYI
