### ISSUE TITLE
Proposal: TreeView selection changed event

### ISSUE THREAD

**Issue by AlexeyBKuznetsov** [microsoft/microsoft-ui-xaml#322]
# Proposal: TreeView selection changed event

## Summary
What is the right way to get notified when TreeView selection changed. Would it be possible to introduce something similar to the list view selection changed

**Comment by jevansaks** [comment]
Looks like we just neglected to add this event when bringing Selection-things to TreeView. Seems like a reasonable request, @predavid can you take a look?

**Comment by predavid** [comment]
@AlexeyBKuznetsov - Thanks for opening this feature request. This is certainly an issue we want to pursue as soon as we get done with the current investments in our Win3.0 roadmap : https://github.com/microsoft/microsoft-ui-xaml/issues/717. 

Please do review the article and provide us your feedback.

**Comment by dpaulino** [comment]
I desperately need this feature. Any ETA?

**Comment by jevansaks** [comment]
Realistically we wouldn't get to this at least until the new year, but I think we would accept a contribution for either the API spec proposal and implementation. If you could propose an API we could help write up that API spec proposal and then we can tag this with "help wanted" to get some external help.

**Comment by dpaulino** [comment]
@japf thanks for this!

**Comment by beatnikthedan** [comment]
any word on this?

**Comment by Felix-Dev** [comment]
@beatnikthedan The API is currently in preview (available in WinUI preview versions like 2.5 previews). API spec (draft) [here](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/80).
