### ISSUE TITLE
Bug/Refactor: Function declaration should be in Header File

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#3226]
I believe the following code should be moved to ColorHelpers.h

https://github.com/microsoft/microsoft-ui-xaml/blob/986d48adaccaabd569dab76137543b1102b24b6c/dev/ColorPicker/ColorHelpers.cpp#L11-L18

**Comment by StephenLPeters** [comment]
agreed

**Comment by robloo** [comment]
Just wanted to get your feedback, I'll do the PR
