### ISSUE TITLE
The texts in calendar flyout overlaps for some languages while using text scaling.

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#3228]
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/28770721).

Steps:  
1) Go to Settings --> Time & Language --> Date & Time.
2) Select "Simplified Chinese" for Show additional calendars in the taskbar.
3) Click the date and time area in the taskbar to confirm the additional calendar is displayed.
4) Go to Settings --> Ease of Access --> Display.
5) Slide the slider bar in Make text bigger to the right edge (225%), and click [Apply].
6) Click the date and time area in the taskbar to show the calendar flyout.

Expected result:
Calendar flyout will be displayed with no texts overlapped.
<img width="960" alt="360713_calendar_org" src="https://user-images.githubusercontent.com/7758786/91915994-d6a74480-ec70-11ea-8c2a-5866c43ff19f.png">

Actual result:
Calendar flyout will be displayed with texts overlapped.
<img width="960" alt="360713_calendar_big" src="https://user-images.githubusercontent.com/7758786/91915996-da3acb80-ec70-11ea-9477-f49bc7880e4c.png">

**Comment by StephenLPeters** [comment]
@kikisaints fyi

**Comment by chigy** [comment]
We will be tracking this in our [internal issue](https://microsoft.visualstudio.com/OS/_workitems/edit/33595713)

**Comment by chigy** [comment]
Should not have closed but we should merge all the similar issues together.
