### ISSUE TITLE
Setting IsTabStop attribute to False doesn't work for ListView

### ISSUE THREAD

**Issue by arjunbalgovind** [microsoft/microsoft-ui-xaml#3229]
**Describe the bug**

IsTabStop does not seem to be recognized for ListView. In my scenario I have a ListView which is "read only" as the SelectionMode is set to None. I would like to remove it from tab navigation for accessibility since the ListView isn't interactive. Setting IsTabStop to false had no effect.

Here is an example code snippet

    <ListView x:Name="Control2" 
                          ItemTemplate="{StaticResource ContactListViewTemplate}"
                          BorderThickness="1"
                          BorderBrush="{ThemeResource SystemControlForegroundBaseMediumLowBrush}"
                          Width="400" 
                          Height="400"
                          HorizontalAlignment="Left"
                          SelectionMode="None"
                          IsTabStop="False"/>

**Steps to reproduce the bug**

1. Modify a ListView in the Xaml Controls Gallery App with the IsTabStop=False property
1. Open the ListView page in the app
2. Tab through the page

**Expected behavior**

ListView should not get keyboard focus

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.5.0-prerelease.200812001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

- I tried disabling [XYFocusKeyboardNavigation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.xyfocuskeyboardnavigation?view=winrt-19041#Windows_UI_Xaml_UIElement_XYFocusKeyboardNavigation) as well, but I could still tab to the ListView and use the up and down arrow keys to navigate the list.
- Setting IsEnabled to False removes the ListView from the tab ordering, but it also makes the ListView appear different. Is it possible to remove it from the tab ordering without this?

**Comment by StephenLPeters** [comment]
ListView is already not a tab stop, ListViewItems are tab stops by default. You'll need to update the ListViewItemContainterStyle on ItemsControl which sets the IsTabStop on the items to false.

**Comment by StephenLPeters** [comment]
I'm going to close the issue, if this doesn't resolve your issue comment here and we can reopen it.

**Comment by arjunbalgovind** [comment]
@StephenLPeters thanks for the help! I was able to prevent the ListView items from getting tab focus using those steps, however I still see that I need 2 tabs to cross a ListView instead of 0. When I tab to it, instead of reaching the next control after the list I'm able to move the horizontal scrollbar with the left/right arrow keys. Is there another property I need to set to avoid this?

**Comment by amercer-fdi** [comment]
> ListView is already not a tab stop, ListViewItems are tab stops by default. You'll need to update the ListViewItemContainterStyle on ItemsControl which sets the IsTabStop on the items to false.

In case anyone else stumbles across this, this works for the community toolkit ListDetailsView control also.
