### ISSUE TITLE
There is a bug when NavigationView in Flyout?

### ISSUE THREAD

**Issue by doghappy** [Microsoft/microsoft-ui-xaml#323]
**Describe the bug**
When the `NavigationView` is in the `Flyout` control and `Flyout` first expands, the `NavigationView` works, but if `Flyout` loses focus(Flyout is closed), click the Button again, all `NavigationViewItem` cannot be clicked.

**Steps to reproduce the bug**

### XAML

```xaml
<Button Content="flyout2">
    <Button.Flyout>
        <Flyout>
            <NavigationView x:Name="nvSample" PaneDisplayMode="Top">
                <NavigationView.MenuItems>
                    <NavigationViewItem Icon="Play" Content="Menu Item1" Tag="SamplePage1" />
                    <NavigationViewItem Icon="Save" Content="Menu Item2" Tag="SamplePage2" />
                    <NavigationViewItem Icon="Refresh" Content="Menu Item3" Tag="SamplePage3" />
                    <NavigationViewItem Icon="Download" Content="Menu Item4" Tag="SamplePage4" />
                </NavigationView.MenuItems>
                <Frame x:Name="contentFrame"/>
            </NavigationView>
        </Flyout>
    </Button.Flyout>
</Button>
```

| Windows 10 version                  | Saw the problem? |
| :-------------------- | :------------------- |
| October 2018 Update (17763)   | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |

**Comment by doghappy** [comment]
May be caused by Flyout cache Content

**Comment by jevansaks** [comment]
This sounds like #18 which is fixed in the latest prerelease MUX. Could you give [this nuget package](https://www.nuget.org/packages/Microsoft.UI.Xaml/absoluteLatest) a try? (You would need to switch your usage of NavigationView from the SDK to Microsoft.UI.Xaml)
