### ISSUE TITLE
WebView2: Tab key doesn't work to switch the focus between elements

### ISSUE THREAD

**Issue by cdhawan** [microsoft/microsoft-ui-xaml#3231]
**Describe the bug**
WebView2: Tab key doesn't work to switch the focus between elements

**Steps to reproduce the bug**
1. Create a UWP app with WebView2
2. Set WebView2 source uri to <b>https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_test</b>
3. Launch the app
4. Click on first input box (First name) on the right pane
5. Press tab key to move the focus to the next input field.

**Expected behavior**
Tab key doesn't respond and focus doesn't move.

**Screenshots**
None

**Version Info**
WinUI 3.0 with WebView2 Preview 2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | < N/A   |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  Don't know |
| Surface Hub        | Don't know |
| IoT                | Don't know |

**Additional context**
None

**Comment by adambarlow** [comment]
@DmitriyKomin , will this be fixed by work items we have for Preview 3?

**Comment by codendone** [comment]
This is fixed in Preview 4.
