### ISSUE TITLE
Bug: ColorSpectrum Left/Right Arrow Key Navigation is Reversed.

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#3234]
**Describe the bug**

ColorSpectrum Left/Right Arrow Key navigation is reversed.

**Steps to reproduce the bug**

Navigating on a ColorSpectrum (by itself, works fine in the ColorPicker) by pressing the left arrow will actually move the selected color to the right. Pressing the right arrow moves the selected color left.

Edit: It only happens in certain Components. Setting to Components="SaturationValue" will cause the issue while "HueSaturation" will not. I expect this is why I wasn't seeing it in ColorPicker originally.

**Expected behavior**

Left = Left
Right = Right

**Screenshots**

N/A

**Version Info**

Microsoft.UI.Xaml 2.4.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Would like someone else to confirm my sanity on this one.

**Comment by StephenLPeters** [comment]
I confirmed this does repro in the Mux Controls test app.

**Comment by robloo** [comment]
Ok, I'll add this to my list of things to circle back to.

**Comment by chingucoding** [comment]
Just to clarify, @robloo do you want to work on this issue?

**Comment by robloo** [comment]
If you want to take a look at this go for it! It will be a while before I get to this.

**Comment by chingucoding** [comment]
Okay, if that's fine with you, I will take a look.
