### ISSUE TITLE
Bug: ColorSpectrum off-by-1 Rendering?

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#3235]
**Describe the bug**

It appears the ColorSpectrum has an off-by-1 bug when rendering the Ring (Box looks OK). The off-by-1 is on the bottom and potentially the right as well.

**Expected behavior**

The bottom and Right of the Ring should not have the last pixel clipped.

**Screenshots**

![image](https://user-images.githubusercontent.com/17993847/92062805-91b20980-ed67-11ea-95c8-31b86a6ce5c6.png)

**Version Info**

Microsoft.UI.Xaml 2.4.x

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Where did this screenshot from? I see the clip on the right and bottom in the MuxControlsTestApp but i don't see the red strip appearing on the left like your screenshot.

**Comment by robloo** [comment]
Screenshot is just from a test app comparing side-by-side two different implementations. It was useful to kind-of see the right of the other control being clipped as well. I probably should have cropped this better though.

**Comment by StephenLPeters** [comment]
ah so that is a second color spectrum, got it.

**Comment by chingucoding** [comment]
I would like to look into this issue.
