### ISSUE TITLE
PasswordBox: Password reveal button is not shown any longer when re-entering the control

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3252]
**Describe the bug**
By [default](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.passwordbox?view=winrt-19041#password-reveal-mode) the `PasswordBox` shows a password reveal button when the PasswordBox has focus and some content. However, when stepping out of the PasswordBox and then back into it, the password reveal button is no longer shown. Instead, the user will first have to clear the PasswordBox and then start typing again for the reveal button to show up.

**Steps to reproduce the bug**
1. Open the XAML Controls Gallery app and go to the PasswordBox page.
2. Start typing into a PasswordBox so that the reveal button is shown
3. Set focus on another UI element, then re-enter the PasswordBox

Observe that the reveal button is no longer shown even though the PasswordBox has both focus and content.

**Expected behavior**
The password reveal button should be shown when re-entering a PasswordBox with content.

**Screenshots**
![image](https://user-images.githubusercontent.com/1398851/92324164-4cc7f480-f03f-11ea-9f2c-8671ffa7682e.png)
(A focused PasswordBox with focus and content, yet no password reveal button.)

**Version Info**

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by chingucoding** [comment]
This is by design. See #1224 where I also raised that concern.

**Comment by Felix-Dev** [comment]
Re-opening this issue as I think we should add the "by design" information to the documentation (meant as tracking the documentation issue). Just so we will avoid repeated mentions of this behavior as a bug in the future.

I could create a PR in the docs repo shortly.

@YuliKl FYI.

**Comment by chingucoding** [comment]
I think it makes sense to also mention this on the main page, not everyone will read the API documentation if they want to use the PasswordBox, especially since the API is not too surprising (in my opinion).

**Comment by YuliKl** [comment]
The behavior is documented [here](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/password-box#peek-mode) but I agree would also be useful on the main API page. Can someone open a doc bug (by providing feedback for this page) on the [main API page](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.passwordbox)?

![image](https://user-images.githubusercontent.com/13142665/92533900-52147300-f1e8-11ea-8fdb-bc41fa90287f.png)

**Comment by Felix-Dev** [comment]
@YuliKl I would just open a PR with the updated documentation instead (and link it here). Will get the change faster into this docs based on previous experiences :)

**Comment by YuliKl** [comment]
Thank you, our docs team loves user contributions!

**Comment by Felix-Dev** [comment]
@YuliKl Created PR https://github.com/MicrosoftDocs/winrt-api/pull/1811.
