### ISSUE TITLE
More bugs in the HEIF/HEIC decoder

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#3253]
Having previously found an HEIF decoder bug in #2386 I've now found another one. I'm running into an unhandled Win32 exception when displaying HEIC images. The image is loaded via BitmapImage.SetSourceAsync, then used as the source of an Image control. The image displays OK for a second but then the app crashes with an unhandled Win32 exception. It's not completely consistent. Sometimes it only crashes if I scroll up and down the page, and sometimes it doesn't crash at all. I couldn't create a minimal repro. Here is the most error info I have (no debug symbols were available).

```
Unhandled exception at 0x00007FF89DCEF64B (mfh265enc.dll) in MyApp.exe: 0xC0000005: Access violation reading location 0x0000000000101AC0.
```
Also on another occasion (the same setup)
```
Exception thrown at 0x00007FF89C1920A5 (msheif_store.dll) in MyApp.exe: 0xC0000005: Access violation reading location 0x0000000000013698.
```

I've had to resort to using a SoftwareBitmapSource instead for HEIC files (despite the bug in #2386). It would be nice if these bugs could be fixed. HEIC is not an uncommon image format nowadays since iPhones shoot in that format.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)       |  Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by benstevens48** [comment]
Not sure if these codec bugs were ever fixed, but the codec bugs are external I guess.

**Comment by codendone** [comment]
I believe multiple important fixes have been made in the HEIF/HEIC decoder in the last few years. (Note, this decoder is updated via the Microsoft Store as a framework package.) If there is still an issue, please open an issue with a repro for that issue and we can direct that to the decoder team. Thanks.
