### ISSUE TITLE
ContentControl not properly measured while adding ContentTemplate

### ISSUE THREAD

**Issue by JagadeesanPichaimuthu** [microsoft/microsoft-ui-xaml#3258]
**Describe the bug**
ContentControl not properly measured while adding ContentTemplate. In our application, we defined the DataTemplate for item and tried to calculate the height by assign the DataTemplate to the ContentControl in code behind. When create the ContentControl and measure the size in code behind without attach visual tree, it not properly calculated the size. It always return the height as 0, and it not calculated the height based on the ContentTemplate. Please find the sample here,

[AutoFit.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5189391/AutoFit.zip)

<Page
    x:Class="AutoFit.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:AutoFit"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Page.Resources>
        <DataTemplate x:Key="dataTemplate">
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="Auto"/>
                </Grid.RowDefinitions>
                <TextBlock
                    Margin="5" 
                    FontWeight="Bold"
                    VerticalAlignment="Center"
                    FontSize="13" Foreground="Black"
                    Text="Sanitation"
                    TextWrapping="Wrap" />
                <TextBlock
                    Margin="5,0,5,5" 
                    Grid.Row="1"
                    FontSize="12" Foreground="Black"
                    Text="Sanitation is a an important aspect of public health policy. One of its primary purposes is to treat wastewater so that any pollutants are eliminated, thereby reducing negative environmental impacts."
                    TextWrapping="Wrap" />
            </Grid>
        </DataTemplate>
    </Page.Resources>

    <Grid x:Name="grid" HorizontalAlignment="Center" VerticalAlignment="Center" Background="White">
        
    </Grid>
</Page>

public sealed partial class MainPage : Page
    {
        ContentControl contentControl = new ContentControl();
        
        public MainPage()
        {
            this.InitializeComponent();
            contentControl.Width = 250;
            contentControl.ContentTemplate = this.Resources["dataTemplate"] as DataTemplate;
            this.Loaded += MainPage_Loaded;
        }

        private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            contentControl.Measure(new Size(contentControl.Width, double.PositiveInfinity));
            contentControl.Height = contentControl.DesiredSize.Height;
        }
    }

**Steps to reproduce the bug**
1. Run the sample.
2. Put break point in Loaded method.
3. After measure the ContentControl, check the size.
4. The measure method is not properly calculated.

**Expected behavior**
The measure method need to properly calculate when assign the ContentTemplate.

**Comment by StephenLPeters** [comment]
It looks like you haven't added the contentControl to the visual tree, does adding it to the page resolve the issue? Does calling ApplyTemplate on the content control before calling measure fix the issue? I'd kind of expect the code you have currently to work, although it is a weird scenario and I could imagine content control having some optimization in it to not bother expanding the template while its not in the tree.

**Comment by JagadeesanPichaimuthu** [comment]
Hi Team,

Thanks for your update. Our purpose is to measure the DataTemplate  size based on the width. So that we created the content control and assigned the DataTemplate and measure the size of the ContentControl. We just used the ContentControl for meaure purpose alone, so we don't added this to visual tree. Is there is any other way to measure the DataTemplate?

**Comment by ranjeshj** [comment]
It does look like some optimization is at play here. If the content control is in the tree, then the measure call produces a desired size. As a workaround you can add it to the grid, measure, get the desired size and remove it from the grid immediately after. @MikeHillberg as FYI.
