### ISSUE TITLE
On TabViewItem Add - The parameter is set incorrectly

### ISSUE THREAD

**Issue by mcobrahacker** [microsoft/microsoft-ui-xaml#3261]
Hello, I using simple code for add tab item (Tabs.TabItems.Add(item);). I using Microsoft UI XAML to do it. But when I need to add TabItem I have this error "The parameter is set incorrectly". A few month ago before use Microsoft UI Xaml this action work well

**Comment by StephenLPeters** [comment]
@mcobrahacker are you mixing name spaces?  for instances is your TabView a **Microsoft**.UI.Xaml.Controls.TabView while your tab view item is a **Windows**.UI.Xaml.Controls.TabViewItem?

**Comment by StephenLPeters** [comment]
barring that guess, could you please provide more info like a repro app?
