### ISSUE TITLE
StackOverflowException when custom class derives IEnumerable with an Add function that takes the class as a parameter

### ISSUE THREAD

**Issue by RobertVS-MS** [microsoft/microsoft-ui-xaml#3266]
**Bug description**
When building a UWP project w/ a minimum target version > 10586, a Debug app that has a custom class that derives from IEnumerable and contains a function named Add() that takes a parameter of the class custom class type will crash with a StackOverflowException.

**Steps to reproduce the bug**
1. Create a blank UWP project
2. Add the following class
```
public class User : INotifyPropertyChanged, IEnumerable
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private string _name;
        public string Name
        {
            get { return _name; }
            set
            {
                _name = value;
                NotifyPropertyChanged();
            }
        }
        private void NotifyPropertyChanged(String propertyName = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        // This is the cause of the StackOverflow. The User class is a parameter within the Add, so this results in an endless Reflection loop 
        public void Add(string element, User config)
        {

        }

        public IEnumerator<User> GetEnumerator()
        {
            throw new NotImplementedException();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
```
3. Build in Debug mode, will get SOE upon launch

**Expected behavior**
Not to crash

**Workarounds**
Multiple, including renaming function from Add, changing the parameter count, disabling type reflection in the project settings, 

**Version Info**
Set min version of project to be 15063

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Issue has been debugged down to code in XamlReflectionType.cs lines 127-137.   Feel free to follow up with me directly if you need additional information as to what specifically was found.

**Comment by ranjeshj** [comment]
@RobertVS-MS can you share a repro app ? How are you using this User class in your app ?

**Comment by hjharvey-MSFT** [comment]
@ranjeshj the User class is being added to a listview, which is displayed on a page.

**Comment by RobertVS-MS** [comment]
@ranjeshj - I have followed up with you directly on the repro app, let me know if you need anything further

**Comment by ranjeshj** [comment]
@RealTommyKlein and @fabiant3  as FYI.

**Comment by RealTommyKlein** [comment]
Thanks - this is for Windows.UI.Xaml specifically.  If anyone is hitting this, the workaround is to add this to your project or .props file:
```
<PropertyGroup>
  <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
</PropertyGroup>
```

**Comment by RobertVS-MS** [comment]
@RealTommyKlein - Yes...  we have confirmed that does resolve it, just reporting it in case something can be done to address without needing one of the various workarounds
