### ISSUE TITLE
👩‍💻☎ September WinUI Community Call (September 16, 2020) 

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#3269]
## Details
Date: Wednesday September 16, 2020
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

## Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. In this community call we'll be welcoming a community guest and some team members from within Microsoft. 

**Q&A:** At the end of every community call we have a Q&A session where our team and guests answer your questions about all things WinUI. Ask your questions in the comments of this issue! If any questions come up during the call, you can ask them live in the comments as well.

**Agenda**
Intro, updates on WinUI
Community Spotlight Guest: @mrlacey 
Ecosystem Spotlight: React Native for Windows with @kikisaints 
Q&A

**Comment by thomasclaudiushuber** [comment]
Looking forward to it. I hope I can make it next week. 

I have one little question, not directly related to WinUI, but related to WinUI and Windows Terminal. It came up after I read this fantastic blog post: https://blogs.windows.com/windowsdeveloper/2020/09/08/building-windows-terminal-with-winui/

Hey, I have to say here that I really enjoyed reading it! Well done! 

**My question is:**
The Windows Terminal team decided to build a thin Win32 Window that hosts UWP via XAML Islands. Are they working already together with the WinUI team to make the next version of the Windows Terminal with WinUI 3.0, which means they don't have to create their own Win32 Window to escape the UWP sandbox? :-) That would mean Windows Terminal vNext could be a pure WinUI 3.0 application.

**Comment by huoyaoyuan** [comment]
Can you share any progress about when the framework components of WinUI 3 can be open-sourced?
It has been buggy and hard to understand with some features starting with initial version of UWP, comparing to WPF. With open sourcing it, at least we can read and understand its behaviors. For WPF, we used to decompile it before it's open source, but it's harder for WinUI to decompile.

**Comment by hansmbakker** [comment]
Are there any updates on non-desktop WinUI3 usage?

**Comment by niels9001** [comment]
What are the top features the community / partners / customers request that will NOT make it in WinUI 3.0? And when will we see these features arrive?

**Comment by Skittles2519** [comment]
Our team would like to use WebView2 in production as soon as possible, any eta of when it will receive it's first release under production win UI? Also, are there any updates on Xbox getting WebView2 or the new edge browser? Thanks

**Comment by MartinZikmund** [comment]
Not fully WinUI question, but what are the chances of getting a way to debug/run Windows apps under compatibility mode of older Windows 10 builds? (see feedback item https://developercommunity.visualstudio.com/idea/1184084/debug-apps-in-windows-10-compatibility-mode.html)

**Comment by zeealeid** [comment]
There is a rumor of WinUI getting used in Start Menu, Action Center etc. 
https://mspoweruser.com/microsoft-may-be-getting-ready-to-replace-the-windows-10-desktop-with-a-fluent-winui-version/

When would we be able to start seeing these changes?

**Comment by Psykobal** [comment]
Do you have a roadmap for non-WinUI3 package release (2.4.4, 2.5,...)?
