### ISSUE TITLE
NavigationView.ShoulderNavigationEnabled Property with value Always work as WhenSelectionFollowsFocus

### ISSUE THREAD

**Issue by pavelshapovalov** [microsoft/microsoft-ui-xaml#328]
**Describe the bug**
When I set value `Always` in the `NavigationView.ShoulderNavigationEnabled` property, it still work as `WhenSelectionFollowsFocus`. This bug related with function [NavigationView::BumperNavigation](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/NavigationView.cpp#L1541). Which have incorrect check in [line](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/NavigationView.cpp#L1552):
```
|| !IsNavigationViewListSingleSelectionFollowsFocus()
```

**Steps to reproduce the bug**
1. Create navigation view with follow params:
```
    <NavigationView x:Name="testNavigation"
                    PaneDisplayMode="Top"
                    ShoulderNavigationEnabled="Always"></NavigationView>
```
2. Run application on xBox and trying to press gamepad bumpers buttons.

**Expected behavior**
Navigation work correct.

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |  Yes   |
| Surface Hub          |     |
| IoT                         |     |

**Comment by YuliKl** [comment]
Here's the documentation for [ShoulderNavigationEnabled](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.shouldernavigationenabled) and [SelectionFollowsFocus](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.selectionfollowsfocus#Windows_UI_Xaml_Controls_NavigationView_SelectionFollowsFocus) properties. The behavior described in this issue does not match the docs, so definitely sounds like a bug to me.

@pavelshapovalov - are you able to work around this issue by setting your app's SelectionFollowsFocus to Enabled? This behavior may be expected by Xbox users from their interactions with the Xbox homepage.

**Comment by pavelshapovalov** [comment]
@YuliKl Unfortunately not. Because I have toggle switch control into the navigation view, and SelectionFollowsFocus breaks the logic of the work. I will need to go through three tabs to enable or disable toggle in this case.
I've added other temporary work around. I added function like BumperNavigation which handle key up event for navigation view on page.
