### ISSUE TITLE
Proposal: Add HsvColor Struct and HsvColor Property to ColorPicker

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#3281]
# Proposal: Add HsvColor Struct and HsvColor Property to ColorPicker

## Summary

 1. Add a new HsvColor struct to WinUI. The struct should support the properties below. The design is based on the [Windows Community Toolkit implementation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.hsvcolor?view=win-comm-toolkit-dotnet-stable).

```csharp
// The hue channel 0..359
public double H { get; }

// The saturation channel 0..1 (a percentage)
public double S { get; }

//  The value channel 0..1 (a percentage)
public double V { get; }

// The alpha channel 0..1 (a percentage)
public double A { get; }
```

 2. Add an HsvColor property to the ColorPicker itself
 3. Switch the ColorSpectrum HsvColor property to use the HsvColor struct instead of Vector4

## Rationale

The color picker internally works in HSV. If applications require high color precision they cannot be converting to/from RGB and HSV repeatedly or the values will drift.

It also makes sense to expose the HSV color to clean-up internal ColorPicker code that shares the value between components.

## Scope

| Capability | Priority |
| :---------- | :------- |
| Add a new HsvColor struct | Must |
| Expose the internal HsvColor in the ColorPicker | Must |
| Expose conversion methods from RGB <-> HSV | Must |
| Rework internal ColorPicker/ColorSpectrum code to use HsvColor instead of Vector4 | Should |

**Comment by StephenLPeters** [comment]
@kikisaints fyi

**Comment by chingucoding** [comment]
I think the best place for a HsvColor struct would be in Windows.UI or rather Microsoft.UI . @StephenLPeters Would that be something we could do before WinUI 3 or where should such a struct be placed (MUXC is not the right place since it is not a control or eventargs).

**Comment by mdtauk** [comment]
It does seem like a generic Colour structure, like ARGB / RGBA / Decimal / Hex / RGB / CMYK etc

Will there also be the conversion colour math in there when switching mode and preserving the colour value chosen?

**Comment by chingucoding** [comment]
The proposal does not require it, but I think it would make sense to provide it. Maybe it should be required, having to implement the conversion yourself doesn't sound like a great experience.

**Comment by robloo** [comment]
> Will there also be the conversion colour math in there when switching mode and preserving the colour value chosen?

Yes, I included as a 'should' it but the intention would be to make the color conversion helpers in ColorPicker/ColorConversion.cpp publicly exposed. These could also be integrated with the existing ColorHelper.cpp.

The ColorPicker actually already operates in HSV and does the conversion automatically from RGB. No change would be needed there.

**Comment by chingucoding** [comment]
Oh I see, that would also work. Maybe that would be a `must` then, after all we are already adding a separate API here for the ColorPicker and introducing just the HSV struct without any conversion helpers seems a bit lacking.
