### ISSUE TITLE
Question: How to write UI tests in WinUI 3 Desktop

### ISSUE THREAD

**Issue by Xarlot** [microsoft/microsoft-ui-xaml#3282]
I`ve tried to write a test in WinUI 3 Desktop that shows some UI. However, it failed on showing UI with     System.Runtime.InteropServices.COMException : Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)) exception.
I used "Microsoft.NET.Test.Sdk" stable Version="16.7.0" and latest Version="16.8.0-preview-20200812-03".
It seems that this version of SDK doesn't support WinUI 3 Desktop testing.

Do you have any recommendations on how to test UI?

**Comment by StephenLPeters** [comment]
@stevenbrix @alwu-msft fyi

**Comment by stevenbrix** [comment]
Adding @azchohfi in case he has any guidance.

Can you share a repro project, so that we can take a look?

**Comment by azchohfi** [comment]
**WinUI3 Desktop? No. WinUI3 UWP, yes.**

I think this is all I've added:
```
...
  <PropertyGroup>
    <IsWinUIAlpha Condition="'$(IsWinUIAlpha)' == ''">true</IsWinUIAlpha>
    <WindowsKitsPath Condition="'$(IsWinUIAlpha)' == 'true'">WinUI-Alpha-Projects-Don-t-Use-SDK-Xaml-Tools</WindowsKitsPath>
  </PropertyGroup>
...
  <ItemGroup>
    <PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview2.200713.0" />
  </ItemGroup>
...
```
I'm using 16.6.1 of Microsoft.NET.Test.Sdk, but it should work with newer versions just fine.

Here is the source of the csproj:
https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/winui_multitarget/UnitTests/UnitTests.UWP/UnitTests.UWP.csproj

We don't have templates for MSTests+UITests+WinUI3+Desktop (also nothing for WinUI3+UWP).

Also MSTest doesn't support WinUI3 yet. It is still using CoreDispatcher, and not **DispatcherQueue**, so it won't work as-is.

@stmoy fyi

**Comment by Xarlot** [comment]
I end up with creating a custom nunit test runner. IsWinUIAlpha and WindowsKitsPath helped a lot with copying testhost.exe. Thanks.

However, I encountered difficulties related to building a test runner application package.
I've created three libraries, two of them have custom control and themes/generic.xaml file with styles (custom library winui in desktop template) and application (blank app packaged winui in desktop template). Then I've added all libraries as project references to an application project. The problem is that I can't compile it with some strange errors.  

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1947,5): error APPX1110: Payload contains two or more files with the same destination path 'DevExpress.WinUI.TestRunner\Themes\Generic.xbf', and one of source files is missing. Source files: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1947,5): error APPX1110: C:\GitHub\WinUI3DesktopPackageBug\Bin\WinUI\win-x86\DevExpress.WinUI.TestRunner\Themes\Generic.xbf  
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1947,5): error APPX1110: C:\GitHub\WinUI3DesktopPackageBug\Bin\WinUI\win-x86\Themes\Generic.xbf 
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1947,5): error APPX1110: Payload contains two or more files with the same destination path 'DevExpress.WinUI.Core\Themes\Generic.xbf', and one of source files is missing. Source files: 
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1947,5): error APPX1110: C:\GitHub\WinUI3DesktopPackageBug\Bin\WinUI\win-x86\DevExpress.WinUI.Core\Themes\Generic.xbf  
       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1947,5): error APPX1110: C:\GitHub\WinUI3DesktopPackageBug\Bin\WinUI\win-x86\Themes\Generic.xbf  

I'm stuck with this problem, maybe you can help. 

The minimal reproducible project. 
https://github.com/Xarlot/WinUI3DesktopBuildPackageBug

**Comment by stevenbrix** [comment]
@Xarlot can you set this in your library projects:

```xml
<PropertyGroup>
  <GenerateLibraryLayout>true</GenerateLibraryLayout>
</PropertyGroup>
```

I think that should get you around this issue.

**Comment by Xarlot** [comment]
It works. Thanks

**Comment by dotMorten** [comment]
See here: https://devblogs.microsoft.com/ifdef-windows/winui-desktop-unit-tests/

**Comment by ytrewww** [comment]
Can we write test in winUI3 using Nunit framework ? 
Is that possible ?
