### ISSUE TITLE
The "CompileXaml" task returned false but did not log an error.

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#3285]
**Describe the bug**

Build fails, outputting The "CompileXaml" task returned false but did not log an error.

**Steps to reproduce the bug**

1. Build a a simple project. It runs
2. Go to bed.
3. Wake up.
4. Load project, and start it.
5. You will see the error message.

**Expected behavior**

I expect the build to work. Or a useful error message to be returned if there is a problem with the code.

**Version Info**

**NuGet package version:**

[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :-------------- | :-------------- |
| Yes                 | No                  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Gavin-Williams** [comment]
This error was hiding the fact that VS was generating references to Windows.UI instead of Microsoft.UI

**Comment by stevenbrix** [comment]
This error message is generally a red herring, and as you pointed out, was hiding a real issue. I think @RealTommyKlein fixed this in Preview3, can you confirm this still repros?

**Comment by RealTommyKlein** [comment]
The fix didn't make it into Preview 3, but will be in the next WinUI 3 release.  For anyone else who sees this error, it will likely be accompanied by other errors - fixing those should make the CompileXaml task error go away.
