### ISSUE TITLE
Question: Using WinINK RT APIs to draw inside a WebView2 html canvas?

### ISSUE THREAD

**Issue by ChristophWahnsinn** [microsoft/microsoft-ui-xaml#3287]
Hi, I am a designer involved in a large german software project currently built as a UWP (visual studio 2017) hybrid app, used in production. We think about switching to WinUI3 with WebView2 but one critical info is hard for us to come by :)

Can we use WindowsINK RT APIs to draw inside a html canvas element in WebView2 today or in the future, as we currently do in the UWP implementation?

Thanks a lot in advance.
Chris

**Comment by codendone** [comment]
To help us focus our answer, could you be more specific about which APIs you're interested in?

**Comment by ChristophWahnsinn** [comment]
Sure. 

We **need** to be able to
• vectorised handwriting in black and a fixed additional color (like OneNote)
• vectorised multiplicative highlighting with a green text marker (like OneNote)
• eraser-style deleting (like OneNote)
• print the result (mixed handwriting & html) to .ps and .pdf.

Additionally we **would like** to be able to do
• basic shape recognition
• lasso-style moving/deleting of handwriting
• handwriting-to-machine text transcription

I currently do not have the technical names of these APIs we currently use in the UWP. Is this sufficient for you or should I check back with the devs for these?

Thanks!

**Comment by ChristophWahnsinn** [comment]
Hi @codendone, is there a chance to find an answer to my question or do you perhaps know someone who could help?
