### ISSUE TITLE
Question: Flyout within/over ContentDialog

### ISSUE THREAD

**Issue by kseitz10** [microsoft/microsoft-ui-xaml#3288]
If you create a ContentDialog that contains controls which are capable of displaying Flyouts, there is this weird behavior where the Flyout is affected by the ContentDialog. Where the two items overlap, the Flyout becomes shaded. (In the image below, the HotPink area and the default Flyout background become shaded.) This same behavior can be witnessed with Popups. Is there a way to make this not happen, or is this a bug? I tried fiddling with the background colors for the default ContentDialog template and it didn't seem to have an effect.

![image](https://user-images.githubusercontent.com/1263088/93245980-b3d95d80-f751-11ea-989f-abeb1b0deb1b.png)

(I know one of the devs thinks this is a use case per this comment on another issue: https://github.com/microsoft/microsoft-ui-xaml/issues/2461#issuecomment-629865558   It just doesn't seem to be working properly out of the box.)

Targeting 1903. Easily reproducible in a blank UWP project by newing up a ContentDialog and then triggering the display of a Flyout/Popup inside of it.

**Comment by kseitz10** [comment]
This seems to be an issue that is reproducible in Windows 10 release 1909 but not Windows 10 release 2004 (H1). I guess the fix is to require users to update...

**Comment by kseitz10** [comment]
Re-opening this question because upgrading to Windows 10 release 2004 fixed it for some people but not others. This misbehavior seems to be tied to display/visual ease of access settings for some users, but they don't seem to have an effect on my computer.

**Comment by StephenLPeters** [comment]
@codendone or @gegao This looks like a shadows bug, do either of you have an idea what might be happening?

**Comment by codendone** [comment]
The only potential user difference should be if shadows are fully disabled for the user.  The only known issue here was fixed in 2004.

@DmitriyKomin for any additional thoughts.
