### ISSUE TITLE
Discussion: Vulkan embedding

### ISSUE THREAD

**Issue by tomzorz** [microsoft/microsoft-ui-xaml#3291]
# Discussion: Vulkan embedding

Hi folks,

Our company is currently shipping a WPF application with a Vulkan renderer embedded in it for a 3D LOB application. While this solution works, we have several issues:
- we'd love to use Fluent Design components, and get all the new design/HiDPI goodness;
- there are a few WPF bugs that make our designers sad, e.g. applying drop shadows kills both perf and makes text blurry;
- there are many airspace issues with rendering on top of the Vulkan render area - we have to resort to using windows/dialogs for many things that wouldn't require them.

Are there any plans for better integration paths, maybe solving some of these airspace issues? We'd love to work together on this - we can definitely provide real life feedback/data on how things currently are.

Thanks,
Tamás

**Comment by StephenLPeters** [comment]
@tomzorz are you asking for Winui support for Vulkan renderer?

@Austin-Lamb @ryandemopoulos @MikeHillberg @codendone  FYI

**Comment by tomzorz** [comment]
@StephenLPeters No (although that could be cool as well...). More like a Vulkan variant of SwapChainPanel - I guess that might necessitate the rest of the application to render using Vulkan as well?

**Comment by tomzorz** [comment]
But essentially today we just use a HwndHost to embed our Vulkan renderer - if there'd be any improvement over this process that'd be awesome.

**Comment by tomzorz** [comment]
Any updates to this, now that we've got to the preview 3 release?

I tried asking @ryandemopoulos during the community standup, but we didn't got to this question.

**Comment by GeorgeS2019** [comment]
@tomzorz   do consider Godot 4 with Vulkan renderer.  Godot already support export to UWP. It just need to export UWP XAML app instead of UWP console app.

**Comment by drewcrawford** [comment]
Have this issue as well. 

On the vulkan side, the [API appears to accept any HWND](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkWin32SurfaceCreateInfoKHR.html), in which case, a plausible implementation is merely “a control with an HWND”

unfortunately, the only way I know of to get an hwnd is via IWindowNative (only supported on a window). 

[this issue looks related](https://github.com/microsoft/microsoft-ui-xaml/issues/1833), as I assume you could put any win32 control in that and get its hwnd, although it seems not a priority

if anyone knows a cheap back door to get an HWND out of some winui control, that might work for now…

**Comment by orion160** [comment]
As a use case to be used to create game engine tooling as formerly WPF.

But i am not that concerned about the technical details to make it possible.

**Comment by LmTinyToon** [comment]
Yes, support of vulkan would be very nice. I am also looking the way to integrate WinUi with vulkan renderer. I found out that winui uses custom drawing for wide range of controls (without exposing Win32 controls). At the same time vulkan requires `HWND` to work.

**Comment by orion160** [comment]
I dont know how this can help but with Windows App SDK 1.0 there is [AppWindow](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow?view=windows-app-sdk-1.0), and you can obtain a HWND via [GetWindowFromWindowId](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/win32/microsoft.ui.interop/). There is the catcha that there is a 1-1 correspondence between AppWindow and HWND

**Comment by abenedik** [comment]
If you do not want to write your own rendering engine, then you can use the new Ab4d.SharpEngine that uses Vulkan and also supports WinUI 3.0 applications. See the WinUI sample on [GitHub](https://github.com/ab4d/Ab4d.SharpEngine.Samples). The engine is currently in beta (April 2023).
Disclaimer: I am the author of the engine.
