### ISSUE TITLE
Lab Support Files in the Windows 8.1 SDK

### ISSUE THREAD

**Issue by jonathanchapmanmoore** [microsoft/microsoft-ui-xaml#3292]
The Lab support Files seem to be missing from the Windows 8.1 SDK I attached them.
[BuildLabSupportFiles.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5233906/BuildLabSupportFiles.zip)

![Untitled](https://user-images.githubusercontent.com/8218836/93372545-05e9b400-f822-11ea-9e08-62c909e68223.png)
 A final windows 8.1 Build lab should look something like this. With the VS 2013 build tools.

**Comment by StephenLPeters** [comment]
This doesn't seem like a winui issue, @stevenbrix or @MikeHillberg do you know where this should go?

**Comment by stevenbrix** [comment]
I do not, @AdamBraden do you have any idea where this should go? Is Windows 8.1 SDK still supported? 

@jdm7dv, what kind of 8.1 project are you trying to build?

**Comment by michael-hawker** [comment]
🦙 @stevenbrix Win 8.1 left mainstream support in Jan 2018. It's only extended support until Jan 2023: https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

Also see [Support Policy Info](https://docs.microsoft.com/en-us/lifecycle/policies/fixed).
