### ISSUE TITLE
Partner Center: stowed_exception_800f1000_microsoft.ui.xaml.dll (AcrylicBrush::OnConnected should not sync call MaterialHelper::IsFullScreenOrTabletMode)

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#3297]
**Describe the bug**

It's unclear to me if this is causing crashes for users, but thought I'd report it anyway.

From Partner Center:
stowed_exception_800f1000_microsoft.ui.xaml.dll!winrt::impl::consume_windows_ui_viewmanagement_iapplicationview3_winrt::windows::ui::viewmanagement::applicationview_::isfullscreenmode

> Frame	Image	Function	Offset
0	combase.dll	RoOriginateErrorW	0x000000000000004D	
1	Windows.UI.Xaml.dll	DirectUI::ErrorHelper::OriginateError	0x000000000000013C	
2	Windows.UI.Xaml.dll	CJupiterErrorServiceListener::NotifyErrorAdded	0x0000000000000188	
3	Windows.UI.Xaml.dll	CErrorService::AddError	0x000000000000013C	
4	Windows.UI.Xaml.dll	CErrorService::ReportRuntimeError	0x00000000000000D2	
5	Windows.UI.Xaml.dll	CErrorService::ReportGenericError	0x0000000000000155	
6	Windows.UI.Xaml.dll	CDependencyObject::SetAndOriginateError	0x0000000000000086	
7	Windows.UI.Xaml.dll	CCollection::FailIfLocked	0x0000000000247491	
8	Windows.UI.Xaml.dll	CUIElement::RemoveChild	0x000000000000003D	
9	Windows.UI.Xaml.dll	CPopup::Close	0x00000000000000F5	
10	Windows.UI.Xaml.dll	CPopup::SetValue	0x0000000000000142	
11	Windows.UI.Xaml.dll	CDependencyObject::SetValueByKnownIndex	0x00000000000000A1	
12	Windows.UI.Xaml.dll	CDependencyObject::SetValueByKnownIndex	0x000000000000005B	
13	Windows.UI.Xaml.dll	DirectUI::Popup::OnXamlLostFocus	0x0000000000229413	
14	Windows.UI.Xaml.dll	DirectUI::Popup::OnWindowActivated	0x000000000000005A	
15	Windows.UI.Xaml.dll	DirectUI::ClassMemberEventHandler_DirectUI::Popup,Windows::UI::Xaml::IDependencyObject,Windows::UI::Xaml::IWindowActivatedEventHandler,IInspectable,Windows::UI::Core::IWindowActivatedEventArgs_::Invoke	0x000000000000009E	
16	Windows.UI.Xaml.dll	RaiseActivatedEvent	0x0000000000000059	
17	undefined	DirectUI::EventAdapter_Windows::Foundation::ITypedEventHandler_Windows::UI::Core::CoreWindow *,Windows::UI::Core::WindowActivatedEventArgs *_,Windows::UI::Xaml::IWindowActivatedEventHandler,Windows::UI::Core::ICoreWindow,Windows::UI::Core::IWindowActivate	0x0000000000000065	
18	Windows.UI.dll	Microsoft::WRL::InvokeTraits_-2_::InvokeDelegates__lambda_9379b092ad14cf6845b3059e727100d5_,Windows::Foundation::ITypedEventHandler_Windows::UI::Core::CoreWindow *,Windows::UI::Core::WindowActivatedEventArgs *_ _	0x0000000000000065	
19	Windows.UI.dll	Microsoft::WRL::EventSource_Windows::Foundation::ITypedEventHandler_Windows::UI::Core::CoreWindow *,Windows::UI::Core::WindowActivatedEventArgs *_,Microsoft::WRL::InvokeModeOptions_-2_ _::DoInvoke__lambda_9379b092ad14cf6845b3059e727100d5_ _	0x0000000000000071	
20	Windows.UI.dll	Windows::UI::Core::WindowServer::OnWindowActivateEventInternal	0x00000000000000D6	
21	Windows.UI.dll	Windows::UI::Core::WindowServer::OnWindowActivateEvent	0x000000000000006E	
22	Windows.UI.dll	Windows::UI::Core::WindowServer::WndProc	0x00000000000002B1	
23	user32.dll	UserCallWinProcCheckWow	0x00000000000002F8	
24	user32.dll	CallWindowProcW	0x000000000000008E	
25	Windows.UI.Xaml.dll	CJupiterWindow::CoreWindowSubclassProc	0x00000000000001D5	
26	Windows.UI.Xaml.dll	CJupiterWindow::StaticCoreWindowSubclassProc	0x000000000000004F	
27	user32.dll	UserCallWinProcCheckWow	0x00000000000002F8	
28	user32.dll	DispatchClientMessage	0x000000000000009C	
29	user32.dll	__fnDWORD	0x0000000000000033	
30	ntdll.dll	KiUserCallbackDispatcherContinue	0x0000000000000000	
31	win32u.dll	ZwUserPeekMessage	0x0000000000000014	
32	user32.dll	_PeekMessage	0x0000000000000043	
33	user32.dll	PeekMessageW	0x0000000000000143	
34	combase.dll	ModernSTAWaitContext::DispatchAllSentMessages	0x000000000000003A	
35	combase.dll	ModernSTAWaitContext::Wait	0x00000000000006A5	
36	combase.dll	ModernSTAWaitInExistingContext	0x0000000000000085	
37	combase.dll	ModernSTAThreadWaitForCall	0x00000000000000F8	
38	combase.dll	CSyncClientCall::SendReceive2	0x00000000000009D6	
39	combase.dll	SyncClientCallRetryContext::SendReceiveWithRetry	0x0000000000000047	
40	combase.dll	CSyncClientCall::SendReceiveInRetryContext	0x0000000000000044	
41	combase.dll	ModernSTAThreadSendReceive	0x00000000000000F6	
42	combase.dll	CSyncClientCall::SendReceive	0x000000000000018B	
43	combase.dll	CClientChannel::SendReceive	0x0000000000000084	
44	combase.dll	NdrExtpProxySendReceive	0x000000000000004E	
45	rpcrt4.dll	NdrpClientCall3	0x00000000000003A4	
46	combase.dll	ObjectStublessClient	0x0000000000000138	
47	combase.dll	ObjectStubless	0x0000000000000042	
48	twinapi.appcore.dll	GetBrokerInterface	0x000000000005822F	
49	twinapi.appcore.dll	DoRetryableBrokerOperation_IFullScreenBroker,_lambda_3970ae1404966bf0d5ecf4d2d63da1c0_ _	0x000000000009A8A5	
50	twinapi.appcore.dll	CApplicationView::get_IsFullScreenMode	0x0000000000000057	
51	Microsoft.UI.Xaml.dll	winrt::impl::consume_Windows_UI_ViewManagement_IApplicationView3_winrt::Windows::UI::ViewManagement::ApplicationView_::IsFullScreenMode	0x000000000000005A	
52	Microsoft.UI.Xaml.dll	MaterialHelper::IsFullScreenOrTabletMode	0x0000000000000114	
53	Microsoft.UI.Xaml.dll	AcrylicBrush::OnConnected	0x00000000000001F8	
54	Microsoft.UI.Xaml.dll	winrt::impl::produce_AcrylicBrush,winrt::Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverrides_::OnConnected	0x0000000000000038	
55	Windows.UI.Xaml.dll	DirectUI::XamlCompositionBrushBaseGenerated::OnConnectedProtected	0x0000000000000045	
56	Windows.UI.Xaml.dll	DirectUI::XamlCompositionBrushBase::OnConnectedFromCore	0x000000000000007C	
57	Windows.UI.Xaml.dll	CXamlCompositionBrush::FireOnConnected	0x00000000000002B3	
58	Windows.UI.Xaml.dll	CXamlCompositionBrush::EnterImpl	0x0000000000000049	
59	Windows.UI.Xaml.dll	CDependencyObject::Enter	0x0000000000000132	
60	Windows.UI.Xaml.dll	CNoParentShareableDependencyObject::Enter	0x0000000000000070	
61	Windows.UI.Xaml.dll	CDependencyObject::EnterEffectiveValue	0x00000000000003F1	
62	Windows.UI.Xaml.dll	CDependencyObject::SetEffectiveValueInField	0x00000000000003B4	
63	Windows.UI.Xaml.dll	CDependencyObject::SetEffectiveValue	0x00000000000001AD	
64	Windows.UI.Xaml.dll	CDependencyObject::UpdateEffectiveValue	0x00000000000000DF	
65	Windows.UI.Xaml.dll	CDependencyObject::SetValue	0x00000000000000AB	
66	Windows.UI.Xaml.dll	CUIElement::SetValue	0x00000000000000D5	
67	Windows.UI.Xaml.dll	CFrameworkElement::SetValue	0x000000000000009F	
68	Windows.UI.Xaml.dll	CControl::SetValue	0x0000000000000044	
69	Windows.UI.Xaml.dll	CContentControl::SetValue	0x0000000000000071	
70	Windows.UI.Xaml.dll	CDependencyObject::SetThemeResourceBinding	0x0000000000000146	
71	Windows.UI.Xaml.dll	CDependencyObject::TryProcessingThemeResourcePropertyValue	0x000000000000010D	
72	Windows.UI.Xaml.dll	CDependencyObject::UpdateEffectiveValue	0x000000000000018C	
73	Windows.UI.Xaml.dll	CFrameworkElement::InvalidateProperty	0x00000000000000D2	
74	Windows.UI.Xaml.dll	CFrameworkElement::OnStyleChanged	0x00000000000000EA	
75	Windows.UI.Xaml.dll	CControl::ApplyBuiltInStyle	0x000000000000005D	
76	Windows.UI.Xaml.dll	CControl::EnterImpl	0x00000000000000C8	
77	Windows.UI.Xaml.dll	CContentControl::EnterImpl	0x0000000000000054	
78	Windows.UI.Xaml.dll	CCommandBar::EnterImpl	0x0000000000000047	
79	Windows.UI.Xaml.dll	CDependencyObject::Enter	0x0000000000000132	
80	Windows.UI.Xaml.dll	CDOCollection::ChildEnter	0x0000000000000105	
81	Windows.UI.Xaml.dll	CDOCollection::Append	0x00000000000002E3	
82	Windows.UI.Xaml.dll	CUIElementCollection::Append	0x000000000000005D	
83	Windows.UI.Xaml.dll	CUIElement::AddChild	0x0000000000000092	
84	Windows.UI.Xaml.dll	CContentPresenter::ApplyTemplate	0x000000000000028D	
85	Windows.UI.Xaml.dll	CFrameworkElement::InvokeApplyTemplate	0x0000000000000097	
86	Windows.UI.Xaml.dll	CFrameworkElement::MeasureCore	0x00000000000000D1	
87	Windows.UI.Xaml.dll	CUIElement::MeasureInternal	0x00000000000001AA	
88	Windows.UI.Xaml.dll	CUIElement::Measure	0x0000000000000518	
89	Windows.UI.Xaml.dll	DirectUI::UIElement::MeasureImpl	0x0000000000000074	
90	Windows.UI.Xaml.dll	DirectUI::UIElementGenerated::Measure	0x0000000000000073	
91	Windows.UI.Xaml.dll	DirectUI::ScrollContentPresenter::MeasureOverride	0x00000000000004B3	
92	Windows.UI.Xaml.dll	DirectUI::FrameworkElementGenerated::MeasureOverrideProtected	0x0000000000000056	
93	Windows.UI.Xaml.dll	DirectUI::FrameworkElement::MeasureOverrideFromCore	0x00000000000000E4	
94	Windows.UI.Xaml.dll	CFrameworkElement::MeasureCore	0x000000000000043E	
95	Windows.UI.Xaml.dll	CUIElement::MeasureInternal	0x00000000000001AA	
96	Windows.UI.Xaml.dll	CUIElement::Measure	0x0000000000000518	
97	Windows.UI.Xaml.dll	CGrid::MeasureCellsGroup	0x0000000000000133	
98	Windows.UI.Xaml.dll	CGrid::MeasureOverride	0x000000000000026B	
99	Windows.UI.Xaml.dll	CFrameworkElement::MeasureCore	0x000000000000020C	
100	Windows.UI.Xaml.dll	CUIElement::MeasureInternal	0x00000000000001AA	
101	Windows.UI.Xaml.dll	CUIElement::Measure	0x0000000000000518	
102	Windows.UI.Xaml.dll	CBorder::MeasureOverride	0x000000000000009B	
103	Windows.UI.Xaml.dll	CFrameworkElement::MeasureCore	0x000000000000020C	
104	Windows.UI.Xaml.dll	CUIElement::MeasureInternal	0x00000000000001AA	
105	Windows.UI.Xaml.dll	CUIElement::Measure	0x0000000000000518	
106	Windows.UI.Xaml.dll	DirectUI::UIElement::MeasureImpl	0x0000000000000074	
107	Windows.UI.Xaml.dll	DirectUI::UIElementGenerated::Measure	0x0000000000000073	
108	Windows.UI.Xaml.dll	DirectUI::ScrollViewer::MeasureOverride	0x00000000000001A9	
109	Windows.UI.Xaml.dll	DirectUI::FrameworkElementGenerated::MeasureOverrideProtected	0x0000000000000056	
110	Windows.UI.Xaml.dll	DirectUI::FrameworkElement::MeasureOverrideFromCore	0x00000000000000E4	
111	Windows.UI.Xaml.dll	CFrameworkElement::MeasureCore	0x000000000000043E	
112	Windows.UI.Xaml.dll	CUIElement::MeasureInternal	0x00000000000001AA	
113	Windows.UI.Xaml.dll	CUIElement::Measure	0x0000000000000518	
114	Windows.UI.Xaml.dll	CBorder::MeasureOverride	0x000000000000009B	
115	Windows.UI.Xaml.dll	CFrameworkElement::MeasureCore	0x000000000000020C	
116	Windows.UI.Xaml.dll	CUIElement::MeasureInternal	0x00000000000001AA	
117	Windows.UI.Xaml.dll	CUIElement::Measure	0x0000000000000518	
118	Windows.UI.Xaml.dll	CControl::MeasureOverride	0x0000000000000049	
119	Windows.UI.Xaml.dll	DirectUI::FrameworkElement::MeasureOverrideImpl	0x000000000000006E	
120	Windows.UI.Xaml.dll	DirectUI::FrameworkElementGenerated::MeasureOverride	0x0000000000000067	
121	Windows.UI.Xaml.dll	DirectUI::ContentControl::MeasureOverride	0x00000000000000AE	
122	Windows.UI.Xaml.dll	DirectUI::FrameworkElementGenerated::MeasureOverrideProtected	0x0000000000000056	
123	Windows.UI.Xaml.dll	DirectUI::FrameworkElement::MeasureOverrideFromCore	0x00000000000000E4	
124	Windows.UI.Xaml.dll	CFrameworkElement::MeasureCore	0x000000000000043E	
125	Windows.UI.Xaml.dll	CUIElement::MeasureInternal	0x00000000000001AA	
126	Windows.UI.Xaml.dll	CUIElement::Measure	0x0000000000000518	
127	Windows.UI.Xaml.dll	CPopupRoot::MeasureOverride	0x00000000000000B7	
128	Windows.UI.Xaml.dll	CFrameworkElement::MeasureCore	0x000000000000020C	
129	Windows.UI.Xaml.dll	CUIElement::MeasureInternal	0x00000000000001AA	
130	Windows.UI.Xaml.dll	CUIElement::Measure	0x0000000000000518	
131	Windows.UI.Xaml.dll	CUIElement::Measure	0x00000000000004BD	
132	Windows.UI.Xaml.dll	CLayoutManager::UpdateLayout	0x0000000000000107	
133	Windows.UI.Xaml.dll	CCoreServices::NWDrawTree	0x000000000000023E	
134	Windows.UI.Xaml.dll	CCoreServices::NWDrawMainTree	0x00000000000000AD	
135	Windows.UI.Xaml.dll	CWindowRenderTarget::Draw	0x000000000000006F	
136	Windows.UI.Xaml.dll	CXcpBrowserHost::OnTick	0x0000000000000096	
137	Windows.UI.Xaml.dll	CXcpDispatcher::Tick	0x000000000000008D	
138	Windows.UI.Xaml.dll	CXcpDispatcher::OnReentrancyProtectedWindowMessage	0x0000000000000042	
139	Windows.UI.Xaml.dll	CXcpDispatcher::WindowProc	0x0000000000000119	
140	Windows.UI.Xaml.dll	CDeferredInvoke::DispatchQueuedMessage	0x00000000000000CB	
141	Windows.UI.Xaml.dll	CXcpDispatcher::MessageTimerCallbackStatic	0x000000000000001C	
142	CoreMessaging.dll	System__Action$CallbackThunk	0x000000000000011B	
143	CoreMessaging.dll	Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch	0x000000000000018B	
144	CoreMessaging.dll	Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop	0x00000000000006FB	
145	CoreMessaging.dll	Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch	0x00000000000001D6	
146	CoreMessaging.dll	Microsoft::CoreUI::Dispatch::UserAdapter_DoWork	0x00000000000000F1	
147	CoreMessaging.dll	Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc	0x00000000000000A3	
148	user32.dll	UserCallWinProcCheckWow	0x00000000000002F8	
149	user32.dll	DispatchMessageWorker	0x0000000000000249	
150	Windows.UI.dll	Windows::UI::Core::CDispatcher::ProcessMessage	0x000000000000018B	
151	Windows.UI.dll	Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal	0x00000000000000C0	
152	Windows.UI.dll	Windows::UI::Core::CDispatcher::ProcessEvents	0x000000000000007B	
153	Windows.UI.Xaml.dll	CJupiterWindow::RunCoreWindowMessageLoop	0x000000000000004C	
154	Windows.UI.Xaml.dll	DirectUI::DXamlCore::RunMessageLoop	0x0000000000000047	
155	twinapi.appcore.dll	Windows::ApplicationModel::Core::CoreApplicationView::Run	0x000000000000003A	
156	twinapi.appcore.dll	_lambda_643db08282a766b00cec20194396f531_::operator	0x00000000000001EF	
157	SHCore.dll	_WrapperThreadProc	0x00000000000000E9	
158	kernel32.dll	BaseThreadInitThunk	0x0000000000000014	
159	ntdll.dll	RtlUserThreadStart	0x0000000000000021	

**Version Info**
2.4.0

NuGet package version: 

[Microsoft.UI.Xaml 2.4.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| YES |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | YES   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ejserna** [comment]
This seems to me a XAML layout cycle issue because of:
```
73 Windows.UI.Xaml.dll CFrameworkElement::InvalidateProperty 0x00000000000000D2
132 Windows.UI.Xaml.dll CLayoutManager::UpdateLayout 0x0000000000000107
```

**Comment by StephenLPeters** [comment]
@codendone have you seen a crash like this before?

**Comment by codendone** [comment]
The stack shows bad reentrancy.  CCollection::FailIfLocked causes a failure if there is an attempt to change the CCollection when it is locked for other changes, in this case the CDOCollection::Append far down on the stack.  So what the stack shows is this sequence:

1. CDOCollection::Append is adding an element to the collection.
2. The element being added includes an AcrylicBrush, which runs its collection code, which includes asking if the app IsFullScreenOrTabletMode.
3. IsFullScreenOrTabletMode uses ApplicationView::IsFullScreenMode, which is an out-of-proc COM object, which pushed a nested message pump while it waits for the synchronous COM call to complete.
4. The nested message pump just happened to process OnWindowActivated, since apparently the user switched away from the app and OnWindowActivated hadn't yet been processed by the app.
5. There was an open Popup somewhere, which tried to close itself due to the app being deactivated. But the Popup is apparently related the CDOCollection from the start, so its attempt to close triggered the FailIfLocked.

Nested message pumps are generally bad, since they can cause problematic reentrancy like this.  It is unfortunate that various APIs, such as this ApplicationView property, are synchronous COM calls which create nested message pumps.  When calling one of these, whether or not the app gets unlucky and hits bad reentrancy is all dependent on timing and other behaviors (in this case: did the user deactivate the app or was a popup open, but other situations can also trigger reentrancy issues).

Just looking at the stack, it isn't clear if there is any workaround you could do.  If AcrylicBrush::OnConnected is a common trigger for the reentrancy, then its IsFullScreenOrTabletMode call could be moved to a DispatcherQueue.TryEnqueue() task to ensure it doesn't happen on a stack which could be affected by a nested message pump.

**Comment by benstevens48** [comment]
I just read the explanation here and it's quite interesting. @codendone, are you saying that when I call certain WinRT APIs, even though they are synchronous, it's possible that they might cause the message/dispatcher queue to be processed, so in theory another input handler or async continuation in my app could be called in the middle of that synchronous API call? If I haven't misunderstood, that sounds like terrible behavior, and I've always written code assuming that can't happen. Is there a chance to get rid of the instances where that happens in WinUI 3?

**Comment by codendone** [comment]
@benstevens48 Yes, you understood that correctly.  We agree this is potential reentrancy is bad, but it can only be fixed by each API which uses a synchronous COM call.  Those calls can really only be fixed by getting rid of the synchronous COM call, which typically either means having the API cache any data it may return or switch to become asynchronous.  Switching to asynchronous usually means getting rid of the synchronous API to switch to an async form.

I most commonly see this bad reentrancy from app calls to problematic APIs, where most of those APIs are not part of XAML.  We won't be able to fix any of those in WinUI 3.  But in this dump XAML is the caller to the problematic ApplicationView::IsFullScreenMode API, and there could be a change in XAML (either WinUI 3 or WinUI 2.x) along the lines of the last sentence in my previous comment.
