### ISSUE TITLE
Microsoft.UI.Xaml.winmd needs to be placed in the root of AppX files when distributed via a framework package

### ISSUE THREAD

**Issue by llongley** [microsoft/microsoft-ui-xaml#3298]
Stable releases of WinUI 2 contains the target `_FixWinmdPackaging` that causes Microsoft.UI.Xaml.winmd to be placed in a WinMetadata subdirectory of the AppX.  This causes WACK certification tests not to be able to find the WinMD file for dependency resolution, which fails the test suite.  We need to:

1. Figure out whether the WinMD file needs to be put in that subdirectory at all, first - it was stated that at one point .NET Native required that it be present in that folder;
2. If it is still needed in that subdirectory, add a target to additionally copy the WinMD file to the root of the AppX; and
3. If it is *not* still needed in that subdirectory, delete the target altogether so it can be placed in the root of the AppX via the default means of MSBuild NuGet package resolution.

**Comment by michael-hawker** [comment]
@llongley to clarify, this is the root cause we discovered for the issue blocking Lottie shipping from the store in https://github.com/windows-toolkit/Lottie-Windows/issues/214, correct?

**Comment by llongley** [comment]
@michael-hawker Yes, that's correct.
