### ISSUE TITLE
PersonPicture crash on release configuration

### ISSUE THREAD

**Issue by De-Os** [microsoft/microsoft-ui-xaml#3300]
**Describe the bug**
Crash on Release config when creating exstension class for PersonPicture

**Steps to reproduce the bug**
1. Create class which extends PersonPicture:
```c#
public class Avatar : PersonPicture
{
    public Avatar()
    {
    }
}
```
2. Add it to any place:
```c#
public MainPage()
{
    this.InitializeComponent();

    for (int x = 0; x < 10; x++)
    {
        this.Stack.Children.Add(new Avatar() { Margin = new Windows.UI.Xaml.Thickness(10), Height = 100 });
    }
}
```
3. Run application in debug mode and get expected result
4. Run application in release mode and get crash:
```
Unhandled exception at 0x063356F1 (Windows.UI.Xaml.dll) in AvatarTest.exe: 0xC000027B: an internal exception occurred in application(parameters: 0x09D79A80, 0x00000003).
```

**Expected behavior**
App doesn't crash in release mode

**Video**
[Youtube](https://youtu.be/HxqbAt4ywXQ)

**Version Info**
NuGet package version: 
[Microsoft.UI.Xaml 2.4.3]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
You should be able to attach a (mixed mode) debugger and get a call stack for what the issue is.

**Comment by De-Os** [comment]
@StephenLPeters problematic trace:
```
Вызвано исключение по адресу 0x00007FFAAE1C3E49 (KernelBase.dll) в AvatarTest.exe: WinRT originate error - 0x800F1000 : 'Cannot apply a Style with TargetType 'Windows.UI.Xaml.Controls.PersonPicture' to an object of type 'Windows.UI.Xaml.Controls.Control'.'.
Необработанное исключение по адресу 0x00007FFAAE2AB3CC (KernelBase.dll) в AvatarTest.exe: 0xC000027B: Возникло внутренне исключение приложения (параметры: 0x000001A0B6259220, 0x0000000000000003).
```
Full trace: 
<details>
  <summary>Spoiler</summary>
   <pre>
"AvatarTest.exe" (Win32). Загружено "C:\Users\al3ta\source\repos\AvatarTest\bin\x64\Release\AppX\AvatarTest.exe". Сборка модуля выполнена без символов.
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\ntdll.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\kernel32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\KernelBase.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\combase.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\ucrtbase.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\rpcrt4.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\ole32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\gdi32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\win32u.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\gdi32full.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\msvcp_win.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\user32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\advapi32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\msvcrt.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\sechost.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\bcrypt.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\oleaut32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\normaliz.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\crypt32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe\mrt100_app.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\WinTypes.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\bcryptprimitives.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe\vcruntime140_app.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\dpapi.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\mrt100.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\kernel.appcore.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\rmclient.dll". 
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "C:\Program Files\WindowsApps\Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe\mrt100_app.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\imm32.dll". 
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.2_2.2.27912.0_x64__8wekyb3d8bbwe\SharedLibrary.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Collections.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Collections.Concurrent.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Diagnostics.Tools.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Diagnostics.Tracing.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Linq.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Linq.Expressions.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Memory.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.ObjectModel.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.Interop.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.Reflection.Core.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.Reflection.Execution.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.Reflection.Metadata.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.StackTraceMetadata.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.Threading.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.TypeLoader.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.Uri.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Reflection.TypeExtensions.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Runtime.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Runtime.Extensions.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Security.Principal.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Text.RegularExpressions.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Threading.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.SharedLibrary.Generated.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.SharedLibrary.Interop.Generated.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.CoreLib.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "C:\Users\al3ta\source\repos\AvatarTest\bin\x64\Release\AppX\AvatarTest.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "AvatarTest.exe". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "AvatarTest.McgInterop.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Numerics.Vectors.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.AvatarTest.Generated.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.DeveloperExperience.AppX.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.StackTraceGenerator.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Private.WinRTInterop.CoreLib.dll". Символы загружены.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Runtime.CompilerServices.Unsafe.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Runtime.InteropServices.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Runtime.InteropServices.WindowsRuntime.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Runtime.WindowsRuntime.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Runtime.WindowsRuntime.UI.Xaml.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
"AvatarTest.exe" (Компиляция машинного кода CLR v1.0). Загружено "System.Text.Encoding.CodePages.dll". PDB-файл отсутствовал во время компиляции IL-кода в машинный код.
Поток 0x2ca0 завершился с кодом 0 (0x0).
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\twinapi.appcore.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.UI.Xaml.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\SHCore.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\iertutil.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\BCP47Langs.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\CoreMessaging.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\dcomp.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\ws2_32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.StateRepositoryCore.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.UI.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\WindowManagementAPI.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\InputHost.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\TextInputFramework.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\propsys.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\CoreUIComponents.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\CoreUIComponents.dll". 
"AvatarTest.exe" (Win32). Выгружено "C:\Windows\System32\CoreUIComponents.dll"
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\ntmarta.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\OneCoreUAPCommonProxyStub.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\uxtheme.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\urlmon.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\dxgi.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\MrmCoreR.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.StateRepositoryClient.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\ResourcePolicyClient.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\profapi.dll". 
"AvatarTest.exe" (Win32). Выгружено "C:\Windows\System32\ResourcePolicyClient.dll"
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\d3d11.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_93cd1ac04c27c7e5\igd10iumd64.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\shlwapi.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\ncrypt.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\ntasn1.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\BCP47mrm.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_93cd1ac04c27c7e5\igdgmm64.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_93cd1ac04c27c7e5\igc64.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\shell32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\msctf.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.Shell.ServiceHostBuilder.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\execmodelproxy.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\DXCore.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\cfgmgr32.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\d2d1.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\UiaManager.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\DWrite.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\TextShaping.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.UI.Core.TextInput.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.UI.Immersive.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\DataExchange.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\cryptbase.dll". 
Поток 0x31b8 завершился с кодом 0 (0x0).
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.UI.Xaml.Controls.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\directmanipulation.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\threadpoolwinrt.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\Windows.Globalization.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.4_2.42007.9001.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe\msvcp140_app.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Program Files\WindowsApps\Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe\vcruntime140_1_app.dll". 
Вызвано исключение по адресу 0x00007FFAAE1C3E49 (KernelBase.dll) в AvatarTest.exe: WinRT originate error - 0x800F1000 : 'Cannot apply a Style with TargetType 'Windows.UI.Xaml.Controls.PersonPicture' to an object of type 'Windows.UI.Xaml.Controls.Control'.'.
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\userenv.dll". 
"AvatarTest.exe" (Win32). Загружено "C:\Windows\System32\profext.dll". 
Необработанное исключение по адресу 0x00007FFAAE2AB3CC (KernelBase.dll) в AvatarTest.exe: 0xC000027B: Возникло внутренне исключение приложения (параметры: 0x000001A0B6259220, 0x0000000000000003).
</pre>
</details>

**Comment by Felix-Dev** [comment]
@De-Os To get your `PersonPicture` subclass working in *Release* configuration, add the [BindableAttribute](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.bindableattribute?view=winrt-19041) to it:
```c#
[Windows.UI.Xaml.Data.Bindable]
public class AvatarClass : PersonPicture {}
```

See [this post] as a brief overview of the issue.

**Comment by Felix-Dev** [comment]
@StephenLPeters I think this calls for a documentation improvement as we have seen this issue coming up multime times already (see https://github.com/microsoft/microsoft-ui-xaml/issues/2698 and https://github.com/microsoft/microsoft-ui-xaml/issues/1949 for example).

There is a [.NET Native section](https://docs.microsoft.com/en-us/dotnet/framework/net-native/) on docs.microsoft.com. Perhaps we can add this issue and the solution for it there as well (for example to both the [Reflection and .NET Native](https://docs.microsoft.com/en-us/dotnet/framework/net-native/reflection-and-net-native) section and the [.NET Native General Troubleshooting](https://docs.microsoft.com/en-us/dotnet/framework/net-native/net-native-general-troubleshooting) section). I could create a PR for that if this sounds good to you.

We could also link that .NET Native documentation in the [documentation](https://github.com/microsoft/microsoft-ui-xaml/issues/2086) started by @ranjeshj about the differences between the *Debug* and *Release* configurations for UWP and optionally decide to pin that post. That would help with discoverability which seems to be an issue seeing the number of reports we have seen being opened about this very problem in the past.

**Comment by StephenLPeters** [comment]
@RealTommyKlein @fabiant3  Is this fixable so that our customers don't keep hitting this going foreword?  @YuliKl to weigh in on the documentation aspect in the mean time.

**Comment by RealTommyKlein** [comment]
@StephenLPeters - this is tricky since the Xaml compiler doesn't have enough information to know it has to generate type information for the `Avatar` class (type information is generated when the type is used in markup, or has the `Bindable` attribute on it).  It works in Debug since debug builds use the reflection provider, which doesn't rely on compiler-generated type information.
