### ISSUE TITLE
Proposal: MediaPlayerElement enhancement

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#3301]
1. Bring native MediaPlayerElement UI to Xbox. 
    For more details, please refer to [Bring native MediaPlayerElement UI to Xbox](https://github.com/microsoft/microsoft-ui-xaml/issues/3275)

~~2. Keep the playback rate.
    Currently, `MediaPlayerElement` reset the playback rate when playing a new media, even I set the rate manually. This means developers can't set the rate, this is annoying when playing a series drama. Users want 2x rate, they have to set every episode.......
This code doesn't work.~~
```
ViuMediaPlayer.Source = mediaPlaybackItem;
mediaPlayer.PlaybackSession.PlaybackRate = 2.0;
```

3. Add debug panel and relative APIs.
    Currently, Apple TV player supports debug panel like YouTube's `stats for nerds`. This debug panel is critically important for developers to check the network status.
![image](https://user-images.githubusercontent.com/14960168/93730192-21760580-fbfa-11ea-9334-74db78426633.png)

4. More.
    The above is what I'm facing now, but I think there is more to improve. Cause the [UWP user voice forum](https://wpdev.uservoice.com/forums/110705-universal-windows-platform) is closed, I can't find any more info.

**Comment by maxkatz6** [comment]
> This means developers can't set the rate

You need to set playback rate after media opened, I think.
At least it worked for me for a while ago.

**Comment by hupo376787** [comment]
> > This means developers can't set the rate

Hi, I tried the code, If I use a static speed, it works.
`mediaPlayer.PlaybackSession.PlaybackRate = 2.0;`

But I have to store the rate in a global param. Then the rate always is reset to 1.0 when changing the source.
        private async void MediaPlayer_MediaOpened(MediaPlayer sender, object args)
        {
            if(videoType == VideoType.Video)
                mediaPlayer.PlaybackSession.PlaybackRate = Globals.playbackRate;
        }

        //PlaybackRate will always be set to 1.0 when changing the source
        private void PlaybackSession_PlaybackRateChanged(MediaPlaybackSession sender, object args)
        {
            Globals.playbackRate = mediaPlayer.PlaybackSession.PlaybackRate;
        }

**Comment by maxkatz6** [comment]
@hupo376787 can you check playback session state in the PlaybackSession_PlaybackRateChanged?

**Comment by hupo376787** [comment]
> @hupo376787 can you check playback session state in the PlaybackSession_PlaybackRateChanged?

Thanks, @maxkatz6 . I can keep the playback rate now by checking `MediaPlaybackState`.

```
        private void PlaybackSession_PlaybackRateChanged(MediaPlaybackSession sender, object args)
        {
            Debug.WriteLine(mediaPlayer.PlaybackSession.PlaybackState);
            if(mediaPlayer.PlaybackSession.PlaybackState != MediaPlaybackState.None)
                Globals.playbackRate = mediaPlayer.PlaybackSession.PlaybackRate;
        }
```

**Comment by StephenLPeters** [comment]
@Austin-Lamb or @codendone I'm struggling to remember where this should get pathed, I think reach is correct?
