### ISSUE TITLE
Wrong Style TargetType and similar errors are supressed by having debugger attached

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#3304]
**Describe the bug**
I originally reported this [here](https://developercommunity.visualstudio.com/content/problem/761506/xaml-error-not-thrown-when-debugger-attached.html), but they weren't interested in fixing it so I thought I'd report it here so maybe it can be fixed in WinUI 3.

I have a UWP C#/XAML project. If there is an error such as a style set on an element and the style is not of the correct target type, then it will compile fine, and it will run in debug mode with the debugger attached fine. However, when I run it without the debugger it will crash. This makes it difficult to diagnose errors. I suggest it should also throw an exception when the debugger is attached. Note this has nothing to do with release/debug build, it is simply whether or not the debugger is attached (something to do with hot reload or visual tree inspection maybe). Note that the control containing the error must be dynamically added to the visual tree after launch to observe the behavior.

Minimal repro here - 
[XamlErrorNotThrownWithDebugger.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5256683/XamlErrorNotThrownWithDebugger.zip)

Run with app in Visual Studio with the debugger attached. Click the button to add the usercontrol to the page. This does not throw an error. Now stop debugging, launch the app normally and try again. This time the app crashes. 

Source code: 
```
***MainPage.xaml***

<Page x:Class="App2.MainPage" xmlns="https://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="https://schemas.microsoft.com/winfx/2006/xaml" xmlns:local="using:App2" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
<StackPanel Name="mainPanel">
<Button Content="Add item" Click="Button_Click"></Button>
</StackPanel>
</Page>

***MainPage.xaml.cs***

using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls; namespace App2
{
public sealed partial class MainPage : Page
{
public MainPage()
{
this.InitializeComponent();
}

private void Button_Click(object sender, RoutedEventArgs e) {
mainPanel.Children.Add(new MyUserControl1());
}
}
}

***MyUserControl1.xaml***

<UserControl x:Class="App2.MyUserControl1" xmlns="https://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="https://schemas.microsoft.com/winfx/2006/xaml" xmlns:local="using:App2">
<Grid>
<Grid.Resources>
<Style x:Key="S1" TargetType="CheckBox">
<Setter Property="IsChecked" Value="True"/>
</Style>
</Grid.Resources>
<Button Content="Hello World" Style="{StaticResource S1}"/>
</Grid>
</UserControl>
```

Even though it was seen as low priority by the VS team, in my opinion this should be fixed because it makes it very easy to miss bugs during development that then end up crashing the app in the final release. It may be a long time in between testing the app without the debugger attached, and even if you do come across the crash this makes it difficult to diagnose. Also, the error itself is sometimes highlighted in blue in VS, but sometimes not, whereas sometimes things that aren't errors are highlighted in blue, so its easy to miss. It certainly cost me several hours to identify the source of the crash that happened in my app because of this behavior.

Not using WinUI, using built-in UWP.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)       | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@fabiant3 It looks to me like the xaml complier should be throwing an error here.

**Comment by stevenbrix** [comment]
This is a known issue that has been reported before. We do notify VS of the invalid style being applied, so the ideal experience is to break into the debugger and navigate to the exact location of the error.

This is tricky to do in the compiler, because we then have to try and duplicate/mimic the runtimes resource resolution logic. Which is not trivial.

**Comment by benstevens48** [comment]
@stevenbrix thanks for the reply. I don't mind so much that it doesn't throw a compiler error (although that would definitely be best - the more runtime errors that can be converted to compile time ones the better), what I find annoying is that no runtime error is thrown with the debugger attached, which means I miss the error when testing. But perhaps this is something that would have to be fixed in VS (and it seems like they are not too enthusiastic about it)?

**Comment by benstevens48** [comment]
This needs checking in WinUI3.

**Comment by JesseCol** [comment]
Hi, is this still an important issue for you?  If so, can you please check WinUI3 to see if repros?  Thanks!

**Comment by Pawel-Malinowski** [comment]
I've got the same issue in UWP swallowing this exception in debug in VS while it crashes the app when debugging in Rider or running without debugger at all. Don't know if there is any way to make VS not to swallow it, but wasn't able find any setting in VS (ex. Exception settings window) to figure it out.
