### ISSUE TITLE
ContentDialog background is not properly displayed when exiting compact overlay display mode

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#3307]
**Describe the bug**
Before displaying a `ContentDialog`, I'm forcing my application to exit the *compact overlay* display mode to be sure that I will have enough room to display the dialog. This is working but the `ContentDialog` background is not properly resized to the window size.

**Steps to reproduce the bug**
See the attached sample application to see the current behavior: [ContentDialogWhenExistingCompactOverlay.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5261403/ContentDialogWhenExistingCompactOverlay.zip)

The basic steps are:
1. Enter compact overlay mode
```csharp 
ApplicationView.GetForCurrentView().TryEnterViewModeAsync(ApplicationViewMode.CompactOverlay)
```

2. Exit compact overlay and display a content dialog
```csharp
await ApplicationView.GetForCurrentView().TryEnterViewModeAsync(ApplicationViewMode.Default);
var dialog = new ContentDialog
{
    PrimaryButtonText = "OK",
    Content = "This is the content",
    Title = "Title",
};

await dialog.ShowAsync();
```
**Expected behavior**
The application is back in default mode and the `ContentDialog` is properly displayed (content + background)
![image](https://user-images.githubusercontent.com/20152272/93881533-560fbd00-fcdf-11ea-86ea-8fe881aaecc9.png)

**Actual behavior**
The application is back in default mode but the `ContentDialog` **background is not covering the whole app**. 
It seems to keep the size of the compact overlay window.
![image](https://user-images.githubusercontent.com/20152272/93881587-6758c980-fcdf-11ea-9ac9-273bd6433f3a.png)

**Workarounds**
Some workarounds are working like:

1. Showing the content dialog before changing the display mode
```csharp
var dialog = new ContentDialog
{
    PrimaryButtonText = "OK",
    Content = "This is the content",
    Title = "Title",
};

var showDialogTask = dialog.ShowAsync();

var applicationView = ApplicationView.GetForCurrentView();
if (applicationView.ViewMode == ApplicationViewMode.CompactOverlay)
{
    await applicationView.TryEnterViewModeAsync(ApplicationViewMode.Default);
}

await showDialogTask;
```
This works but we see the `ContentDialog`'s background flickering when the application gets its final size.

2. Monitor the `SizeChanged` event with some filtering
```csharp
var applicationView = ApplicationView.GetForCurrentView();
if (applicationView.ViewMode == ApplicationViewMode.CompactOverlay)
{
    var sizeChangeCompletion = new TaskCompletionSource<bool>();
    var currentBounds = Window.Current.Bounds;
    async void OnSizeChanged(object s, WindowSizeChangedEventArgs args)
    {
        var deltaX = Math.Abs(currentBounds.Width - args.Size.Width);
        var deltaY = Math.Abs(currentBounds.Height - args.Size.Height);

        if (deltaX < 2 && deltaY < 2)
        {
            // The size didn't change enough. Give up.
            return;
        }

        // We wait a little to let the layout complete
        await Task.Delay(TimeSpan.FromMilliseconds(100));
        sizeChangeCompletion.TrySetResult(true);
    }

    Window.Current.SizeChanged += OnSizeChanged;

    var resizeCompleteCompletion = new TaskCompletionSource<bool>();
    void CoreWindow_ResizeCompleted(CoreWindow s, object args) => resizeCompleteCompletion.TrySetResult(true);
    Window.Current.CoreWindow.ResizeCompleted += CoreWindow_ResizeCompleted;

    var result = await applicationView.TryEnterViewModeAsync(ApplicationViewMode.Default);
    if (result)
    {
        await Task.WhenAny(resizeCompleteCompletion.Task, sizeChangeCompletion.Task);
    }

    Window.Current.CoreWindow.ResizeCompleted -= CoreWindow_ResizeCompleted;
    Window.Current.SizeChanged -= OnSizeChanged;
}

await ShowDialogAsync();
```
This works fine but it is "complicated" to write and shouldn't be needed.

**Comment by StephenLPeters** [comment]
Unfortunately we would not be able to fix this until post winui3, so you will be stuck with a work around for a little while.  I'm not sure that this will work but you can try to change the view mode, then wait for exactly 1 rendering tick, using the winrt::Xaml::Media::CompositionTarget::Rendering event, and then create and show the dialog.  If you do this be sure that you un register from the rendering event as keeping a handler attached to this event would cause a large perf hit.  you can see the winui2 project do something similar with this helper https://github.com/microsoft/microsoft-ui-xaml/blob/2390f15356323bf051f253c0fd24e81ed591d82e/dev/dll/SharedHelpers.cpp#L401
