### ISSUE TITLE
Question: WinUI 3 Desktop. How to debug why default theme resources are not loading

### ISSUE THREAD

**Issue by Xarlot** [microsoft/microsoft-ui-xaml#3309]
I`ve created a custom control in the custom control library.
I`ve specified the DefaultStyleKey property in the constructor and added a default style into themes/generic.xaml.
```
        <Page Update="Themes\Generic.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
```
For some reason, my custom control doesn't load or even request the default style. When I created a resource dictionary descendant and added it to themes/generic.xaml, it doesn`t instantiate.  Also, there are no warnings or errors in the debugger output. 
I can't reproduce it with a simple project and I can't see the difference. Maybe some non-obvious property is specified or not.

So, the questions are how WinUI lookup the default styles, how to add it properly, and how to debug/trace/whatever why my resources are not loading.

**Comment by StephenLPeters** [comment]
Are you able to provide the project that does reproduce the issue? debugging these sorts of errors tends to be very difficult.  With your simple repro are you using a class library, the winui desktop project structure is still being worked on and its possible that could cause this.

**Comment by Xarlot** [comment]
That the problem. It works in a simple project. We need some kind of diagnostics or logging because we just can't debug in like in WPF.

**Comment by Xarlot** [comment]
I`ve simplified our project
https://github.com/Xarlot/WinUI3DesktopBuildPackageBug
Open and run the sources/DevExpress.WinUI.Core/DevExpress.WinUI.Core.Tests.Runner.sln. It should execute the https://github.com/Xarlot/WinUI3DesktopBuildPackageBug/blob/10c87b23842fb1dc926b07ef295db4b9a34382e1/sources/DevExpress.WinUI.Core/DevExpress.WinUI.Core.Tests/Editors/TextEditTests.cs#L11 test. 
If you replace custom control with TextBox you should see it in UI. 

There is a resource dictionary descendant in themes/generic.xaml. It never created.
https://github.com/Xarlot/WinUI3DesktopBuildPackageBug/blob/10c87b23842fb1dc926b07ef295db4b9a34382e1/sources/DevExpress.WinUI.Core/DevExpress.WinUI.Core/Themes/Generic.xaml#L7

**Comment by stevenbrix** [comment]
@Xarlot, thanks for filing this issue and providing a repro. There were quite a few fixes and changes in preview3, so I'd like to make sure this issue has been properly fixed. There were some cswinrt issues that were causing similar issues:

https://github.com/microsoft/CsWinRT/issues/345
https://github.com/microsoft/CsWinRT/issues/208

Both of these have been fixed, so this should no longer be an issue. Would you mind confirming?

**Comment by Xarlot** [comment]
It works now. 
Thanks
