### ISSUE TITLE
Cannot build release 

### ISSUE THREAD

**Issue by DaZiYuan** [microsoft/microsoft-ui-xaml#3315]
**Describe the bug**

got errors when create app package .
please fix it as soon as possible, I plan to publish my winui app to the store

 
**Steps to reproduce the bug**

1. create winui desktop project
2. publish app package for Microsoft store
3. got errors

**Screenshots**

![image](https://user-images.githubusercontent.com/80653/93959995-cf64e980-fd8b-11ea-82ef-498914eb2533.png)
![image](https://user-images.githubusercontent.com/80653/93960129-d855bb00-fd8b-11ea-9cfa-02384c491aba.png)
![image](https://user-images.githubusercontent.com/80653/93961080-15ba4880-fd8c-11ea-877b-9802ed519839.png)
![image](https://user-images.githubusercontent.com/80653/93961893-4bf7c800-fd8c-11ea-90d3-effe8bad9c55.png)
![image](https://user-images.githubusercontent.com/80653/93962049-6c278700-fd8c-11ea-9e1d-99e40672f76d.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |  Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

``` error logs
Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload file 'D:\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\themeresources.xaml' does not exist.	App2 (Package)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	3036	
Error		Payload file 'D:\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\DensityStyles\CompactDatePickerTimePickerFlyout.xaml' does not exist.	App2 (Package)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	3036	
Error		Payload file 'D:\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\compact_themeresources.xaml' does not exist.	App2 (Package)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	3036	
Error		Payload file 'D:\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\DensityStyles\Compact.xaml' does not exist.	App2 (Package)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	3036	
Error		Payload file 'D:\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\generic.xaml' does not exist.	App2 (Package)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets	3036	
```

**Comment by StephenLPeters** [comment]
@stevenbrix @alwu-msft @MikeHillberg do we have known issues with desktop release mode in the preview?

**Comment by alwu-msft** [comment]
This is probably related to @stevenbrix 's recent discovery that "create a package for publishing" and "hit F5 in VS" do different things.

**Comment by stevenbrix** [comment]
Yeah, in one way or another that is a proper characterization of this issue☺️

@DaZiYuan WinUI3 is not ready for you to submit your app to the store. This issue will be fixed with our next preview release in this coming November.

**Comment by huoyaoyuan** [comment]
@stevenbrix I can **build** in Release mode, but cannot **run** it. Got error 0xC000027B. Is this a separated issue, or a different symptom of the same issue?

**Comment by anawishnoff** [comment]
This was fixed in WinUI 3 Preview 3, so I'm going to go ahead and close this issue. Feel free to re-open and let us know if the issue still persists.
