### ISSUE TITLE
MediaTransportControls progress is not updated when changing PlaybackSession.Position while playback is paused

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#3316]
**Describe the bug**
When the media playback is paused, the progress bar and the time information in the `MediaTransportControls` seek bar are not updated. The video content changes but not the other element of the MTC.

**Steps to reproduce the bug**
Repro app: [MediaPlayerPositionChanged.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5269765/MediaPlayerPositionChanged.zip)

1. Create a basic app with a media player element:
```xaml
<MediaPlayerElement
    x:Name="player"
    Grid.Row="1"
    AreTransportControlsEnabled="True"
    AutoPlay="True" />
```
2. Add a button to change the position of the media
```csharp
private void OnAddThirtySeconds(object sender, RoutedEventArgs e)
{
    var newPosition = player.MediaPlayer.PlaybackSession.Position + TimeSpan.FromSeconds(30);
    if (newPosition > player.MediaPlayer.PlaybackSession.NaturalDuration)
    {
        newPosition = TimeSpan.Zero;
    }
    player.MediaPlayer.PlaybackSession.Position = newPosition;
}
```
3. Launch the application, open a media and **pause** it.
4. Change the playback position by calling `OnAddThirtySeconds()`

**Expected behavior**
The video frame displayed is the one at the new position, the **seek bar** and the **elapsed duration** text block have the new position value.

**Actual behavior**
The video image is the expected one but **the seek bar and the elapsed duration are still displaying the time when the video was paused** (1second in my screenshot):
![image](https://user-images.githubusercontent.com/20152272/94045982-5e93f080-fdd0-11ea-9be7-c29a3bdf2271.png)

As soon as I press play, the seek bar and the elapsed duration are updated with their expected value:
![image](https://user-images.githubusercontent.com/20152272/94046067-779ca180-fdd0-11ea-9566-6565075b567d.png)

**Additional information**
This is working fine while playback is running.

**Comment by StephenLPeters** [comment]
@Austin-Lamb and @codendone I forget which team owns MPE, I think its reach?

**Comment by BladeXR** [comment]
I'm finding myself in the very same problem. Is there any update on this or a workaround you've found @vgromfeld ?

**Comment by vgromfeld** [comment]
I know that an OS fix is coming but I don't know in which build it will be delivered.

**Comment by bpulliam** [comment]
Closing stale external bug. If you are still seeing this issue, please open a new issue in the Feedback Hub so that it may gather related logs/diagnostics.
