### ISSUE TITLE
NavigationViewItem will support svg icons

### ISSUE THREAD

**Issue by Javier118** [microsoft/microsoft-ui-xaml#3318]
Hello:
In the new version of WinUI NaviagtionViewItem will support svg icons?

**Comment by Felix-Dev** [comment]
Not directly yet to my understanding. You could use a [PathIcon](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.pathicon?view=winrt-19041) for now using a tool converting SVGs into paths. There is proposal https://github.com/microsoft/microsoft-ui-xaml/issues/3101 which could enable this scenario in the future.

**Comment by Javier118** [comment]
the question is whether in this version WInUi3 in the NavigationViewItem it would support Svg image.  To the PathIcon as you could add the Svg file for NavigationViewItem.

**Comment by StephenLPeters** [comment]
seem like you opened identical issues? #3319
