### ISSUE TITLE
NavigationViewItem will support Svg icons in this version WinUI

### ISSUE THREAD

**Issue by Javier118** [microsoft/microsoft-ui-xaml#3319]
Hello:
In the new version of WinUI NavigationViewItem will support svg icons?

**Comment by StephenLPeters** [comment]
Unfortunately no, our IconSource only supports symbols, bitmaps, paths, and font glyphs.  It does have a content property that you can put an svg image into though, does that meet your needs?

**Comment by StephenLPeters** [comment]
An SVG icon sounds like a pretty reasonable feature request that you and other developers might want. If so I'd encourage you to open a feature request!

**Comment by Felix-Dev** [comment]
@StephenLPeters How about leveraging https://github.com/microsoft/microsoft-ui-xaml/issues/3101 for SVG support?

**Comment by StephenLPeters** [comment]
I think that would also help Javier, however I think expanding IconSource would still be interesting independently

**Comment by Javier118** [comment]
the idea is to make some icons of your own for App in NaviagtionViewItem menu.
![menu](https://user-images.githubusercontent.com/17751683/94188051-1eed0780-fea9-11ea-8d6c-38adf949d42b.png)

**Comment by StephenLPeters** [comment]
Question seems answered, if not feel free to reopen. feature proposal has been opened.
