### ISSUE TITLE
Invalid Binding on NumberBox with unitialized int DP

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3320]
**Describe the bug**

The following code does not create a valid binding:

IDL
```IDL
    //[MUX_DEFAULT_VALUE("1")] <-- Adding this fixes the issue
    Int32 MyInt;
```

XAML
```XAML
<!-- Maximum does not update correctly. -->
<muxc:NumberBox Maximum="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=MyInt, Mode=OneWay}"/>
<!-- Updates correctly! -->
<TextBlock Text="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=MyInt, Mode=OneWay}"/>
```

This is probably related to the fact that NumberBox.Maximum is a float, while MyInt is an int. When MyInt is not default valued, binding might not know the type and thus discard the binding. This might be related to the WinUI code gen for DPs.

**Expected behavior**

Binding should update.
**Screenshots**

**Version Info**

https://github.com/microsoft/microsoft-ui-xaml/commit/44767d110716d560286072b66ea5bf1f1ccf7b61
NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by stevenbrix** [comment]
Thanks for filing this issue @chingucoding. I agree this is clunky and should be fixed.
