### ISSUE TITLE
Proposal: richer image support for [Bitmap]icons

### ISSUE THREAD

**Issue by bschoepke** [microsoft/microsoft-ui-xaml#3323]
# Proposal: Richer image support for [Bitmap]Icons

## Summary
Add the ability to use any XAML ImageSource as an icon for MenuFlyoutItem. The BitmapIcon control currently only supports URI image sources; we need it to support stream image sources in order to render things like app icons.

## Rationale
* Enable the shell to render app icons and favicons in context menus. These are backed by Windows.Graphics.Imaging.SoftwareBitmap objects rather than URI's and work fine with the Image control and ImageBrush.
* Achieve long-term visual consistency by avoiding re-templating MenuFlyoutItem to render these icons.

## Scope
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to render any bitmap supported by Windows.UI.Xaml.Media.ImageSource inside a MenuFlyoutItem | Must |

## Important Notes
Usage examples: File Explorer context menus and taskbar jump lists

## Open Questions
n/a

**Comment by Felix-Dev** [comment]
@StephenLPeters Should we bundle issues asking for broader image support for `Icon` properties in a larger work item? With the idea being that we look at this platform-wide?

So far, we have seen asks for broader image support for the NavigationViewItem ([here](https://github.com/microsoft/microsoft-ui-xaml/issues/3319) and [here](https://github.com/microsoft/microsoft-ui-xaml/issues/3101)) and the MenuFlyoutItem (this issue). Then we also have the [AppBarButton.Icon](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.appbarbutton.icon?view=winrt-19041#Windows_UI_Xaml_Controls_AppBarButton_Icon) property and the [TabViewItem.IconSource](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.tabviewitem.iconsource?view=winui-2.4#Microsoft_UI_Xaml_Controls_TabViewItem_IconSource) property in the framework, for example, for which we should also enable richer image support then if we do it for MenuFlyout and NavigationView items.

Thoughts so far range from expanding the `IconSource` and `IconElement` classes to cover more image scenarios to changing the type of the `Icon` poperty to `object` and adding an additional `IconTemplate` API.

This sounds too me like we should group all these issues and think about a solution applicable to all of WinUI then where `Icon`s exist.

**Comment by StephenLPeters** [comment]
I agree, these all seem related and I think we should be thinking about the problem holistically.  A Meta feature proposal is probably warranted.  Additionally we'll want to keep in mind that we have an Animated Icon spec #2802 which is also in the same/similar space.

**Comment by mdtauk** [comment]
Is this only for strictly image types, so JPG, PNG, SVG, GIF?

What about ICO format icons? If these are supported, how do you choose the ICO size/format?
