### ISSUE TITLE
".NET 5 Support for UWP apps" in WinUI3 roadmap: what does it means for .NET 5 and Webview2 ?

### ISSUE THREAD

**Issue by pfresnay** [microsoft/microsoft-ui-xaml#3328]
Official roadmap (https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-30-feature-roadmap ) indicates ".NET 5 Support for UWP apps" will be in 3.x release.

Can we expect .NET 5 support in UWP before WinUI 3 ? UWP is still on netcore2/C#7.3...

Regarding WinUI3, most API are already present in UWP but one piece is missing, Webview2: will we be able to use Webview2 with UWP in a near future or do we have to wait for .NET 5 UWP support ?

**Comment by robloo** [comment]
Webview2 is implemented in C++ and does not use .NET. Therefore, it has no dependency on .NET 5 and when UWP actually gets .NET 5 support has no influence on when UWP can use Webview2. The Microsoft team has previously committed (most recently in the community call I believe) to ship Webview2 with WinUI 3.0 initial release. That means UWP can use it as soon as WinUI 3 is released. HOWEVER, WinUI 3.0 will not be feature complete when it is released. If your existing UWP app depends on some of the missing features you won't be able to update to WinUI 3 and I expect won't be able to use Webview2.

I'm rapidly getting disappointed with how this is all rolling out. It's repeating several of the same mistakes as UWP all over again. Except thankfully we are no longer dependent on the Windows team so hopefully we can fix those mistakes faster.

**Comment by StephenLPeters** [comment]
@adambarlow FYI

**Comment by StephenLPeters** [comment]
The original questions seems to be answered, thanks Rob.

**Comment by pubtom** [comment]
If you need .NET>5 in UWP please give a vote on this: https://developercommunity.visualstudio.com/t/Add-NET-678-support-to-UWP/1596483
