### ISSUE TITLE
Question: What 'Rounded corners' are not going to be in WinUI 3.0?

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#3330]
In the latest [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-30-feature-roadmap), What rounding corners are you talking about?

![image](https://user-images.githubusercontent.com/17993847/94281639-de2ed600-ff1c-11ea-854e-5b0510486da3.png)
![image](https://user-images.githubusercontent.com/17993847/94281686-f0107900-ff1c-11ea-8fed-6ffd9beda047.png)

If this is rounded-corners for all controls like border, grid, etc. (or CornerRadius property usage in styles) it's going to be a problem. I expect this really is talking about popups or window corners?

**Comment by mdtauk** [comment]
I'd also like to see more details about the rounded corners, and other ambiguous things in that roadmap like Fluent Shadows.

**Comment by anawishnoff** [comment]
Thanks for filing this @robloo. This does refer to top-level windows and pop-ups. I have a PR #3332 out to clarify this.
