### ISSUE TITLE
Pivot control throws 'COMException: Unspecified error' on setting SelectedItem

### ISSUE THREAD

**Issue by sis2004** [microsoft/microsoft-ui-xaml#3334]
**Describe the bug**
The Pivot control throws a System.Runtime.InteropServices.COMException: 'Unspecified error when setting its SelectedItem to a value that is not in its Items list. Technically, it may still be a valid item, but the code generated from XAML's x:Bind could update the selected item before it updates the list of items, as shown below.

**Steps to reproduce the bug**
Here is a sample MainPage.xaml
```xaml
<Page
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    x:Class="App1.MainPage">

    <StackPanel>
        <Button Content="Go Bananas" Click="GoBananas_Click"/>
        <TextBlock Text="{x:Bind VM.SelectedItem, Mode=OneWay}"/>
        <Pivot ItemsSource="{x:Bind VM.List, Mode=OneWay}"
               SelectedItem="{x:Bind VM.SelectedItem, Mode=TwoWay}"/>
    </StackPanel>
</Page>
```

Here is the code-behind MainPage.xaml.cs
```cs
    public sealed partial class MainPage : Page, INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private ViewModel vM;
        private ViewModel VM
        {
            get => vM;
            set
            {
                vM = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(VM)));
            }
        }

        public MainPage()
        {
            this.InitializeComponent();
            VM = new ViewModel("Apples");
        }

        private void GoBananas_Click(object sender, RoutedEventArgs e)
        {
            VM = new ViewModel("Bananas");
        }
    }
```

And finaly the ViewModel class:
```cs
    public class ViewModel : INotifyPropertyChanged
    {
        private List<string> list;
        public List<string> List
        {
            get => list;
            set
            {
                list = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(List)));
            }
        }

        private string selectedItem;
        public string SelectedItem
        {
            get => selectedItem;
            set
            {
                selectedItem = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(SelectedItem)));
            }
        }

        public ViewModel(string type)
        {
            List = new List<string>()
            {
                $"{type} 1",
                $"{type} 2",
                $"{type} 3",
            };
            SelectedItem = List[0];
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
```

1. Launch the App1
2. Click on the 'Go Bananas' button
3. Observe it crash with the following exception:
```
System.Runtime.InteropServices.COMException: 'Unspecified error

Unspecified error
'
```

**Expected behavior**
The app should not crash and change the Pivot to a list of Bananas, with the first item selected.
Note, that if you comment out the TextBlock in the XAML and rebuild/rerun, then it will work as expected, since the x:Bind code generated from XAML will be in the right order.

**Version Info**

NuGet package version: Microsoft.UI.Xaml.2.5.0-prerelease.200923002

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
This looks like an issue with x:bind to me, not pivot.

**Comment by stevenbrix** [comment]
@sis2004, does this repro with `{Binding}`?

@RealTommyKlein, do you see any way that we could address this in x:Bind? It feels like there is an ordering issue, but I don't know if there is anything x:Bind can do.

**Comment by RealTommyKlein** [comment]
@stevenbrix - it would probably entail a new feature/directive to re-order x:Bind evaluations instead of evaluating x:Binds in the order they're declared in markup.  I was originally thinking we could repurpose `x:Phase`, but that's on a per-element basis instead of per-x:Bind, and requires the x:Bind to be used in a virtualizing control that would invoke x:Bind with its different phases.  Could see something like an optional `Priority` directive for each x:Bind to specify what x:Bind statements should be evaluated first, e.g. a Priority 0 x:Bind would be evaluated before a Priority 1 x:Bind.

**Comment by sis2004** [comment]
@stevenbrix  this does not repro with `{Binding}` , since it doesn't use generated code the way `x:Bind` does.

You can try to make x:Bind more clever and generate the code in the right order, but that sounds like a complicated task to me that could result in a messy design.

Alternatively, you can try to update the Pivot control to make it tolerant to the order its properties are updated in (without losing the SelectedItem, of course). This seems like it can be an easier option to me.
