### ISSUE TITLE
Performance degradation on showing huge content

### ISSUE THREAD

**Issue by Xarlot** [microsoft/microsoft-ui-xaml#3335]
While investigating WinUI 3 Desktop performance I`ve observed a performance degradation on showing new windows with huge content. 

**Describe the bug**
Every new window with huge content shows 20% times slower compared to the previous.

**Steps to reproduce the bug**
1. Create a window with 1000 number boxes
2. Subscribe to Loaded event
3. Activate it 
4. Repeat from step 1

Sample project [App10.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5287065/App10.zip)
Click a "click me" button, the result will be shown in the title.

**Expected behavior**
There is no difference between activations

**Version Info**
Package version 3.0.0-preview2.200713.0
AppModel WinUI 3 Desktop
OS Name Microsoft Windows 10 Enterprise
OS Version 10.0.19041 N/A Build 19041

**Comment by lhak** [comment]
I think have seen a similar issue (not sure if related) where the performance degrades after the window size was changed a few times. This could especially be seen with XAML animations.

**Comment by ranjeshj** [comment]
This might be related to this [leak in cs/winrt. ](https://github.com/microsoft/CsWinRT/issues/413). @Xarlot can you check task manager and see if memory usage is increasing each time you activate ? @Scottj1s as FYI

**Comment by Xarlot** [comment]
It seems my steps to reproduce weren`t good. 
You should create and activate a new window. I`ve updated the description

**Comment by BorzillaR** [comment]
I upgrade the origin project to Preview 3. The performance issue still here.

|Window num|Load time|
|---------------|-----------|
|1                    |5949        |
|2                    |7242        |
|3                    |9553        |
|4                    |12310      |
|5                    |15862      |

Each next window loads about 20% slower than the previous.

Updated project:
[App10.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5573524/App10.zip)

**Comment by stevenbrix** [comment]
Thanks @BorzillaR and @Xarlot.

@bartekk8 can you see if this is still reproing on the latest?

**Comment by JeanRoca** [comment]
@Austin-Lamb would someone on your team be able to look at this?

**Comment by bartekk8** [comment]
Thanks for reporting this issue.  I verified and it still repros on the latest.  The repro app creates multiple windows with a lot of content and in such case a slowdown is to be expected, but when windows are destroyed the perf should improve.  Unfortunately, it doesn't, so It looks like there's a leak here!  Again, thanks for catching it!
