### ISSUE TITLE
ArgumentException when trying to use enum array as ItemsSource

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#3339]
**Describe the bug**

**Steps to reproduce the bug**

```csharp
    private Array arr = new [] { E.A, E.B, E.C };

    public enum E { A, B, C }
```

```xaml
<ComboBox ItemsSource="{x:Bind arr}" />
```

No repro if switching to WinUI3 UWP. Only repro for desktop (.NET 5)
Also repro for ListView.
Also repro when changing the type to `object[]`.

**Is this a CsWinRT issue?** Can you do a verification? It seems also repro when setting `ContentPresenter.Content` to single enum value.

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by JeanRoca** [comment]
Hi @huoyaoyuan thank you for filing this issue, Would you be able to verify if this issue is still replicated in our latest [WinUI 3 Preview 3](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)?

**Comment by huoyaoyuan** [comment]
@JeanRoca Yes, still present in Preview 3.

**Comment by stevenbrix** [comment]
@Scottj1s this sounds like a C#/WinRT issue - would you be able to take a look?

**Comment by stevenbrix** [comment]
Closing this since there is a C#/WinRT issue (mentioned above) tracking this
