### ISSUE TITLE
Change the RadioMenuFlyoutItem glyph

### ISSUE THREAD

**Issue by adambarlow** [Microsoft/microsoft-ui-xaml#334]
**Describe the bug**

The glyph for the RadioMenuFlyoutItem is currently a checkmark and should instead be a dot as in other 'Radio' experiences, like RadioButtons.
**Steps to reproduce the bug**

1. Create a multiple RadioMenuFlyoutItems with the same group name
2. Look at the glyph provided

**Expected behavior**

The glyph should be a bullet (dot). The correct glyph code is " E915"

**Comment by YuliKl** [comment]
@jevansaks @teaP - can this be fixed soon, perhaps this week?

**Comment by jevansaks** [comment]
@teaP said she'll do it today.
