### ISSUE TITLE
NavigationView hierarchical navigation: NavigationViewItem.IsAccessKeyScope not working in left compact mode 

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#3343]
**Describe the bug**
When using the hierachical navigivation of `NavigationView`, the access key scope is not working properly when the navigation pane display mode is set to left compact.

**Steps to reproduce the bug**

1. Create a new application with the following code:
```xaml
<mux:NavigationView PaneDisplayMode="LeftCompact" >
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem
            AccessKey="A"
            Content="Item 1"
            KeyTipPlacementMode="Right" />

        <mux:NavigationViewItem
            AccessKey="B"
            Content="Item 2"
            IsAccessKeyScope="False"
            KeyTipPlacementMode="Right">
            <mux:NavigationViewItem.MenuItems>
                <mux:NavigationViewItem
                    AccessKey="D"
                    Content="Sub item 2.1"
                    KeyTipPlacementMode="Right" />
                <mux:NavigationViewItem
                    AccessKey="E"
                    Content="Sub item 2.2"
                    KeyTipPlacementMode="Right" />
                <mux:NavigationViewItem
                    AccessKey="F"
                    Content="Sub item 2.3"
                    KeyTipPlacementMode="Right" />
            </mux:NavigationViewItem.MenuItems>
        </mux:NavigationViewItem>

        <mux:NavigationViewItem
            AccessKey="C"
            Content="Item 3"
            IsAccessKeyScope="True"
            KeyTipPlacementMode="Right">
            <mux:NavigationViewItem.MenuItems>
                <mux:NavigationViewItem
                    AccessKey="A"
                    Content="Sub item 3.1"
                    KeyTipPlacementMode="Right" />
                <mux:NavigationViewItem
                    AccessKey="B"
                    Content="Sub item 3.2"
                    KeyTipPlacementMode="Right" />
                <mux:NavigationViewItem
                    AccessKey="C"
                    Content="Sub item 3.3"
                    KeyTipPlacementMode="Right" />
            </mux:NavigationViewItem.MenuItems>
        </mux:NavigationViewItem>
    </mux:NavigationView.MenuItems>
</mux:NavigationView>
```
2. Run the application
3. Press "ALT" to display the access keys.
4. Press "C" to open *Item 3* 

**Expected behavior**
The sub items of *Item 3* are displayed, their access keys are displays and the previous one are removed.

**Actual behavior**
The sub items are displayed as well as their access keys. But, the one from the first level are still displayed. The *access key scope* set on *Item 3* is not working:
![image](https://user-images.githubusercontent.com/20152272/94448592-5ca0a780-01ab-11eb-9059-f48dec081277.png)

In *Left* mode (not compact), there is no issue:
![image](https://user-images.githubusercontent.com/20152272/94448656-6e824a80-01ab-11eb-814e-d3e005087a2b.png)

**Version Info**
NuGet package version: Microsoft.UI.Xaml 2.4.3

**Repro sample**
[NavigationViewAndAccessKeyScope.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5293154/NavigationViewAndAccessKeyScope.zip)

**Comment by ranjeshj** [comment]
I am guessing that when we have the flyout, the access key logic does not know the parent chain.
