### ISSUE TITLE
ItemsRepeater - slow scrolling performance

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3345]
Hello!

I`ve attached a small sample with ItemsRepeater. I use the data-dependent layout sample from [this] (https://docs.microsoft.com/en-us/windows/uwp/design/layout/attached-layouts#virtualizing-layouts) article. I notice that scrolling is slow. If I set HorizontalCachLength and VerticalCacheLength to 0, the scrolling becomes faster.

**Steps to reproduce the bug**

1. Open and run project in attachment
2. Scroll items by mouse. Notice, that perfomance of scrolling is slow.
3. Open app.xaml and add HorizontalCacheLength="0" VerticalCacheLength="0" properties to ItemsRepeater.
4. Run app again and notice, that scrolling becomes faster.

**Version Info**

Windows 10 1903 (OS Build 18362.1082)
WinUI 3.0.0-preview2.200713.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        | |
| IoT                | |

Project: 
[App24.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5297821/App24.zip)

**Comment by StephenLPeters** [comment]
@ranjeshj can you weigh in?

**Comment by ranjeshj** [comment]
possibly the same issues as https://github.com/microsoft/microsoft-ui-xaml/issues/3008
