### ISSUE TITLE
To large list/right-click menues when using magnifier in full screen

### ISSUE THREAD

**Issue by Pit-Storm** [microsoft/microsoft-ui-xaml#3346]
Dear Team,

I opened [this issue](https://github.com/microsoft/terminal/issues/7765) on Terminal repo. But the described behaviour also exists e.g. with sticky notes. So the Terminal-Team told me to point it out here.

What do you need from my side to clearify the behaviour?

Kind regards!

**Comment by DHowett** [comment]
This looks like https://github.com/microsoft/microsoft-ui-xaml/issues/1875 possibly? :smile:

**Comment by Pit-Storm** [comment]
Looks like ;-)

Is there a schedule when ui3 will be available and is it dependend to sole specific build/win version?

🎉

**Comment by StephenLPeters** [comment]
Here is the winui 3 roadmap : https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-30-feature-roadmap

Winui 3 is designed to be independent of the operating system and the initial release will support any version after RS4.
