### ISSUE TITLE
UWP - serious performance degradation due to Garbage Collector, working with Bitmaps and large object collections 

### ISSUE THREAD

**Issue by IanBelchamber** [microsoft/microsoft-ui-xaml#3347]
We have a large solution with a UWP project providing user interface and WPF project providing connection to hardware we can't get to through UWP like machine vision cameras. We have found that GC is causing unacceptable delays and latency to GUI and background processing, apparently when it stops all threads to check all our objects, most of which are persistent for the lifetime of the application and we would prefer to be left alone. 

This effect is easy to demonstrate with a remarkably simple program, copied below. Simply put the code into the Mainpage of a blank UWP c# project.

The button is rotated on a timer. It should rotate smoothly, but it pauses regularly as the GC is active. The form also regularly freezes if you are trying to resize it.

Prevent the initial objects going to the obs list and it will be fine. GC is therefore stealing the responsiveness from our application while it does a load of work we know does not need to be done. I would have thought the most time consuming part of this, checking if objects have been de-referenced, could be done with minimal overhead and without stopping the other threads anyway.

Various solutions (such as restructuring our project in c++) have been discussed but the timeframes of this are prohibitive.

This is a critical issue for our business. Any suggestions (or GC improvements) welcome. 

```

namespace App1
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        private List<object> obs = new List<object>();
        
        private Button Rotating = new Button();
        private float Angle = 0;
        private StackPanel ContentSp = new StackPanel();

        public MainPage()
        {
            this.InitializeComponent();
        }

        private void Grid_Loaded(object sender, RoutedEventArgs e)
        {
            for (int i = 0; i < 100000; i++)
            {
                var o = new TextBlock ();
                obs.Add(o);
            }

            Content = ContentSp;
            Rotating.Margin = new Thickness(100);
            ContentSp.Children.Add(Rotating);

            DispatcherTimer t = new DispatcherTimer();
            t.Tick += timerTick;
            t.Interval = new TimeSpan(0, 0, 0, 0, 1);
            t.Start();

        }

        private void timerTick(object sender, object e)
        {
            Angle += (float)0.1;
            var RT = Matrix4x4.CreateRotationZ(Angle, new Vector3(20, 20, 0));
            Rotating.TransformMatrix = RT;

            var bm = new SoftwareBitmap(BitmapPixelFormat.Rgba16, 640, 480);
            bm.Dispose();
            GC.SuppressFinalize(bm);
        }


    }
}


```

**Comment by StephenLPeters** [comment]
If you are mostly concerned with animation performance during GC you can look into using independent animations, some info here: https://docs.microsoft.com/en-us/windows/uwp/design/motion/storyboarded-animations#dependent-and-independent-animations and here: https://docs.microsoft.com/en-us/windows/uwp/composition/composition-animation#:~:text=Composition%20APIs%20allows%20you%20to,animations%20in%20your%20application%20UI.  

avoiding GC is one of the primary reasons people use c++, if you want complete control that may be your best option.

@MikeHillberg @jevansaks or @codendone  do you know if there are tricks Ian can use to work around GC?

**Comment by mdtauk** [comment]
@StephenLPeters  Am I right in thinking it is possible to mix C++ code in a C# project - if you needed to write performant code for a specific thing within your app?

**Comment by codendone** [comment]
Having a large number of XAML objects will result in slow Gen2 GC.  For best performance, regardless of the situation, we recommend trying to limit the number of current XAML objects to no more than a couple thousand.  Use of virtualization and x:Defer can be helpful for this.

Separate from that, @mdtauk has a good suggestion of using C++ code in places which matter.  That can be a little tricky, depending on the scenario and how much code you move to C++.  In the above example, moving just the SoftwareBitmap code into C++ would prevent that code from doing a GC.AddMemoryPressure() call, which would avoid that triggering GC.  So you could theoretically create the SoftwareBitmap code in C++, and assuming you want to use that on a XAML Image then also create the SoftwareBitmapSource and set the SoftwareBitmap on it so C# never sees this.  But if you have any code which explicitly triggers a GC or does other allocates which happen to trigger a GC, you'll still see the cost of the 100,000 TextBlocks.

I think creating the TextBlocks in C++ (and never accessing them from C#) will avoid them from being walked during GC, but that obviously entails moving more code.  @MikeHillberg can correct me if I'm wrong about this.
