### ISSUE TITLE
Question: What is proper way to compose an AppWindow with a Frame in desktop app?

### ISSUE THREAD

**Issue by tuggernuts** [microsoft/microsoft-ui-xaml#3348]
I am porting an UWP application to a WinUI 3 (Preview 2) Desktop app.

When launching an `AppWindow` in UWP, an `AppWindow`  with `Frame` content is composed with:
`ElementCompositionPreview.SetAppWindowContent(AppWindow, Frame)`

and an `AppWindow`  is referenced by the `Frame.UIContext` property.

In the WinUI app, whereas both `ElementCompositionPreview` and `Frame` are available, neither `ElementCompositionPreview.SetAppWindowContent` nor `Frame.UIContext` are available.

How should an AppWindow be composed and referenced by the parent application?

**Comment by tuggernuts** [comment]
Well, I can't even create an instance of AppWindow. The static method TryCreateAsync() causes an Unauthorizedaccessexception: Access is Denied. So I'm clearly going about this the wrong way. I know this is bleeding edge stuff, but some rudimentary documentation would be helpful.

**Comment by tuggernuts** [comment]
Ok, I think I found the answer to this question buried here:[https://github.com/microsoft/microsoft-ui-xaml/issues/2104#issuecomment-600749665](url)

**Comment by StephenLPeters** [comment]
@marb2000 is there any extra info to post here?
