### ISSUE TITLE
TabView will crash if no TabViewItem was added to TabItems in 2.5.0-prerelease.200923002

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#3351]
**Describe the bug**
TabView will crash if no TabViewItem was added to TabItems

**Steps to reproduce the bug**
1. Do not add any TabViewItem to TabItems

**Expected behavior**
Should not crash

**Screenshots**

**Version Info**

NuGet package version: 
[2.5.0-prerelease.200923002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Felix-Dev** [comment]
@zhuxb711 This should be fixed by PR https://github.com/microsoft/microsoft-ui-xaml/pull/3118 which is currently blocked from being merged due to down-level testing failures.

**Comment by zhuxb711** [comment]
@Felix-Dev OK, Got it, Thanks a lot.

**Comment by DHowett** [comment]
[Terminal](https://github.com/microsoft/terminal) is in an unfortunate position here. It needs many of the NavigationView fixes in later 2.5 prereleases, but can't move beyond the 2.5 June preview because of this crash. It's pretty much a full blocker on forward progress. :)
