### ISSUE TITLE
NavigationViewPaneClosingEventArgs.Cancel = true is not preventing the navigation pane from beeing closed

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#3352]
**Describe the bug**
I want a menu flyout to be opened when clicking on one navigation view item (see #1570).
![image](https://user-images.githubusercontent.com/20152272/94702037-9bfefd80-033d-11eb-9624-809911476a9c.png)
![image](https://user-images.githubusercontent.com/20152272/94702046-9ef9ee00-033d-11eb-9adc-585440f81e8c.png)

I was planning to use the hierarchical navigation for my scenario but because of #3343, I cannot use it 😥.
I will keep using a regular flyout and was planning to use the `NavigationView.PaneClosing` event (and the `NavigationViewPaneClosingEventArgs.Cancel property) to prevent the panel to close while my custom flyout is opened.

Unfortunately, this is not working. The event handler is invoked but the `NavigationViewPaneClosingEventArgs.Cancel` value is ignored.

**Steps to reproduce the bug**
Use the following sample application: [NavigationViewClosingEvent.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5306394/NavigationViewClosingEvent.zip)
1. In the `ItemInvoked` event handler use the following code:
```csharp
if (args.InvokedItemContainer == menuEntry)
{
    var flyout = FlyoutBase.GetAttachedFlyout(menuEntry);
    flyout.Closed += Flyout_Closed;
    _disablePaneAutoClosing = true;
    flyout.ShowAt(menuEntry);
}
```
2. In the `PaneClosing` event handler use the following code
```csharp
private void NavigationView_PaneClosing(Mux.NavigationView sender, Mux.NavigationViewPaneClosingEventArgs args)
{
    args.Cancel = _disablePaneAutoClosing;
}
```
3. Launch the application and click on the "menu entry" in the navigation pane.
4. The menu flyout is displayed

**Expected behavior**
The navigation pane remains open when `NavigationViewPaneClosingEventArgs.Cancel` is set to true.

**Actual behavior**
The navigation pane is closing.

**Additional context**
I tried to handle the `SplitView.PaneClosing` event from the inner `SPlitView` but it is also not working.

```csharp
private void NavigationView_Loaded(object sender, Windows.UI.Xaml.RoutedEventArgs e)
{
    var splitview = ((FrameworkElement)sender).FindDescendant<SplitView>();
    splitview.PaneClosing += Splitview_PaneClosing;
}

private void Splitview_PaneClosing(SplitView sender, SplitViewPaneClosingEventArgs args)
{
    args.Cancel = _disablePaneAutoClosing;
}
```

**Comment by Felix-Dev** [comment]
This looks like a bug to me. I can cancel the pane closing when in the LeftCompact/LeftMinimal modes and click elsewhere on the app surface (i.e. light dismiss behavior), yet I cannot prevent the pane from closing when selecting a menu item. Since this API exists, I would expect it to be respected in such a case as well.

Perhaps we could extend the [NavigationViewPaneClosingEventArgs](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.navigationviewpaneclosingeventargs?view=winui-2.4) API to have a `Reason` API which states the reason for the pane close? I.e. light-dismissed (clicking elsewhere on the app surface), item invoked,...That way @vgromfeld wouldn't have to use a custom flag like `_disablePaneAutoClosing` here. 

@StephenLPeters @YuliKl What do you think?

**Comment by StephenLPeters** [comment]
Agreed, this seems like a bug, canceling the close should work regardless of the reason for the close.

I think your suggestion for adding a reason to the args would increase consistency. We have a few event args which have close reasons already, I think I'm in favor of adding it but it should probably be its own Feature Proposal.

**Comment by Felix-Dev** [comment]
@StephenLPeters I would like to look into this bug then. I will also create a Feature Proposal for the `Reason` API which can then be used for further discussions.

**Comment by tuggernuts** [comment]
I am assuming this was reported for WinUI 2.x. (How to tell?)

Same issue is in the WinUI 3 NavigationView (SDK 1.0.0)

Related issue: Any expanded items will have their `IsExpanded` property set to false BEFORE the PaneClosing event is raised. One might expect pane cancellation to occur before NVI's are collapsed.

A test repo is [here](https://github.com/tuggernuts/NavViewTestApp).

@Felix-Dev @StephenLPeters
