### ISSUE TITLE
ColorSpectrum RightToLeft arrow key navigation is inverted

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3355]
**Describe the bug**
A ColorSpectrum with Flowdirection RightToLeft has inverted arrow key navigation as the images are mirrored. When pressing left, the indicator moves to the right and vice versa. Instead, left should be left and right should be right.

**Steps to reproduce the bug**
1. Set FlowDirection to RightToLeft
2. Press left arrow key, observe that the indicator moves to the right
3. Press right arrow key, observe that the indicator moves to the left

**Expected behavior**
Left is left, right is right.

**Version Info**

Commit:
f4c811b

**Comment by robloo** [comment]
This is the same as #3234, what was it created? Should instead this be the issue for RightToLeft?

**Comment by chingucoding** [comment]
Oh I thought #3234 was with regard to RightToLeft. I'll update this issue. Thanks for pointing that out!
