### ISSUE TITLE
generic.xaml is not loaded when AssemblyName set in project

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3360]
Hello!

I found a follow issue. Resources of the class library are not loaded when AssemblyName is not equal RootNamespace, In attachement there is a project with two class libraries and one app. Every class library contains a simple control with a default style in generic.xaml. The difference between two libraries is that ClassLibrary1.csproj has an AssemblyName element set, but ClassLibrary2 has not. When you run app, you will see the only one control in the window (red square from ClassLibrary2). Seems, when the AssemblyName set, the framework incorrectly generates the xaml paths.

**Steps to reproduce the bug**
1. Open and run the project in attachement. You will see the red square.
2. Open ClassLibrary1.csproj.
3. Remove <AssemblyVersion> element
4. Rebuild ClassLibrary1
5. Remove ClassLibrary1.v1 reference  from App24.csproj and add reference to ClassLibrary1.dll
6. Run app. You will see black and red squares. 

**Version Info**
Windows 10 1903 (OS Build 18362.1082)

NuGet package version: 
WinUI 3.0.0-preview2.200713.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |

Sample project:
[AssemblyNameBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5316775/AssemblyNameBug.zip)

**Comment by BorzillaR** [comment]
I found another issue related to this. Implicit style of the custom control is not loaded If namespace of the custom control is not starts with root namespcae of the assembly.

**Comment by BorzillaR** [comment]
I`ve checked it on Preview 3. It seems the issue was fixed.

**Comment by chrisglein** [comment]
Closing out this issue, cuz

> I`ve checked it on Preview 3. It seems the issue was fixed.

🎉
