### ISSUE TITLE
Question: System.ServiceModel namespace is empty in WinUI for Desktop?

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3363]
Hello!

I am migrating my WinUI/UWP app to WinUI/Desktop. Seems all the classes from System.ServiceModel are missed. ChannelFactory<>, ServiceContractAttribue, OperationContractAttribute and so on. Is there another way to create WCF services in WinUI/Desktop?

**Comment by StephenLPeters** [comment]
@MikeHillberg or @stevenbrix or maybe @Austin-Lamb fyi

**Comment by stevenbrix** [comment]
@BorzillaR WCF wasn't ported to .NET Core, but there is a community driven effort here: https://github.com/CoreWCF/CoreWCF

**Comment by BorzillaR** [comment]
@stevenbrix, thank you!

**Comment by krschau** [comment]
Closing since stevenbrix pointed to the community driven effort. I can reopen if anyone thinks there should be more conversation here.
