### ISSUE TITLE
Question: Type ramp in compact mode

### ISSUE THREAD

**Issue by jolleekin** [microsoft/microsoft-ui-xaml#3365]
It looks like the only font types adjusted in compact mode are the **base** and **body** (font size reduced to 14px). Why are the other types not adjusted?

References
- https://docs.microsoft.com/en-us/windows/uwp/design/style/typography
- https://docs.microsoft.com/en-us/windows/uwp/design/style/spacing
- https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/dll/DensityStyles/Compact.xaml

**Comment by StephenLPeters** [comment]
@YuliKl or @chigy can you weigh in?

**Comment by chigy** [comment]
@jolleekin ,
It is because compact mode is a mode to update controls sizing and not a UI scale feature.
The only font sizes that are impacted by the update to control sizing are automatically impacted. Other text sizes are not.

**Comment by jolleekin** [comment]
@chigy Thanks for the answer. I'll close this one then.
