### ISSUE TITLE
[WinUI3] Cannot create "Blank App, Packaged (WinUI in Desktop)" project due to `ToolLocationHelper::GetPlatformSDKLocation` error

### ISSUE THREAD

**Issue by Palatis** [microsoft/microsoft-ui-xaml#3369]
**Describe the bug**
Creating a "Blank App, Packaged (WinUI in Desktop)" project throws exception:
"The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation('', 10.0.18362.0)" cannot be evaluated. Parameter "targetPlatformIdentifier" cannot have zero length. C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets"

**Steps to reproduce the bug**
1. Install "WinUI 3 Project Templates" VSIX
2. Create a new "Blank App, Packaged (WinUI in Desktop)" project

**Expected behavior**
Blank project successfully created

**Screenshots**

**Version Info**
- Visual Studio: 16.8.0 Preview 3.2
- WinUI 3 Project Templates [Preview]: 3.0.0.2007130
- Windows 10 Workstation (Insider Preview) - 20226.1000

NuGet package version: 
N/A

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? | Version
| :--------------------------------- | :-------------------- | :----------|
| Insider Build (xxxxx)              | Yes | 20226.1000 |
| May 2020 Update (19041)            |    | |
| November 2019 Update (18363)       |    | |
| May 2019 Update (18362)            |    | |
| October 2018 Update (17763)        |    | |
| April 2018 Update (17134)          |    | |
| Fall Creators Update (16299)       |    | |
| Creators Update (15063)            |    | |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by carmineos** [comment]
If you are using .NET 5, be sure to have the Preview 5 installed as it's the only one currently supported as stated [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-2).

**Comment by Palatis** [comment]
> If you are using .NET 5, be sure to have the Preview 5 installed as it's the only one currently supported as stated [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-2).

Yes I do, I followed that instruction and confirmed multiple times.
both
- x64: https://aka.ms/dotnet/net5/preview5/Sdk/dotnet-sdk-win-x64.exe
- x86: https://aka.ms/dotnet/net5/preview5/Sdk/dotnet-sdk-win-x86.exe
are installed.

**Comment by Palatis** [comment]
I tried adding
```<TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>```
to my `csproj` file, and now the problem become:
```The target platform identifier UAP was not recognized.```

**Comment by StephenLPeters** [comment]
This is a known issue we are currently working on fixing. For now you should be able to use the release version of VS 16.7 to avoid this.  The latest preview version of VS (16.8) is known not to work.  (If you have more questions feel free to post here and I'll reopen.)
