### ISSUE TITLE
CommandBarFlyout sometimes has dim color

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#3373]
**Describe the bug**
In some case:
<img width="190" alt="无标题" src="https://user-images.githubusercontent.com/42038175/95148667-75661a00-07b6-11eb-93c3-873df86c4d1c.png">

We expect:
<img width="189" alt="屏幕截图 2020-10-06 092814" src="https://user-images.githubusercontent.com/42038175/95148686-81ea7280-07b6-11eb-88ca-bbc07d9e7cfa.png">

It is worth noting that if the CommandBarFlyout is in a dimly colored state, at this time I use Win+Shift+S to take a screenshot, it will return to normal.

**Steps to reproduce the bug**

1. Try to pop up CommandBarFlyout multiple times

**Expected behavior**
Same color

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.5.0-prerelease.200923002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@codendone and @gegao18 The taking a screenshot fixing the issue makes me think this is a rendering bug.

**Comment by codendone** [comment]
Since taking a screenshot fixes the problem, it sounds like there is a Composition bug here, such as not rendering the last frame of fade-in animation.

**Comment by zhuxb711** [comment]
Is there any progress in investigating this issue? Because this phenomenon is often encountered

**Comment by zhuxb711** [comment]
Any solutions?

**Comment by zhuxb711** [comment]
Is there any progress on fixing this issue now?

**Comment by mdtauk** [comment]
I've experienced this, it seems to affect menus too.

Could it be a ThemeShadow issue, it rendering above the menu or flyout itself?

**Comment by zhuxb711** [comment]
It only appeared after a certain version of 2.5.0.prerelease

**Comment by StephenLPeters** [comment]
@jeffstall FYI

**Comment by zhuxb711** [comment]
Any progress?

**Comment by zhuxb711** [comment]
ComboBox has the same issue

**Comment by mdtauk** [comment]
All the CommandBarFlyouts are currently appearing in a dimmed state with the Light Theme.  I think it may be due to the recent animation change https://github.com/microsoft/microsoft-ui-xaml/pull/4988 or https://github.com/microsoft/microsoft-ui-xaml/pull/5005

![image](https://user-images.githubusercontent.com/7389110/119073292-e88a6c80-b9e4-11eb-919d-7125cc45925f.png)
![image](https://user-images.githubusercontent.com/7389110/119073331-00fa8700-b9e5-11eb-809d-7962f4d7539e.png)

**Comment by ad1Dima** [comment]
seeing this with all popups 
![image](https://user-images.githubusercontent.com/3244664/123525724-0a21f680-d6fd-11eb-9a93-33283f1dda8c.png)
![image](https://user-images.githubusercontent.com/3244664/123525740-202fb700-d6fd-11eb-8ef4-8f625a23695c.png)
![image](https://user-images.githubusercontent.com/3244664/123525749-363d7780-d6fd-11eb-80bd-35ce54659938.png)

**Comment by Poopooracoocoo** [comment]
@StephenLPeters Was this fixed by WinUI 2.6.1?

**Comment by pratikone** [comment]
can you verify if it got fixed or not ? I am closing it for now, do open it up if it repros in current version of winui 2

**Comment by zhuxb711** [comment]
Not seen this issue in Win11, but don't know this got fixed on Win10
