### ISSUE TITLE
Discussion: WinUI UWP App publishing fails in certificate test

### ISSUE THREAD

**Issue by jeganrajm** [microsoft/microsoft-ui-xaml#3374]
# Discussion: WinUI UWP App publishing fails in certificate test
Publishing WinUI UWP app fails in certificate testing

I have faced certificate issue while try to publish my application. To narrow down the issue, removed all my code and tried, still faced the issue.

So, Created empty WinUI UWP project and tried to run certificate test in this. (No codes included, just default template), still faced issue in this.
![image](https://user-images.githubusercontent.com/18045503/95168823-8707eb80-07cf-11eb-8f89-c067f5ae7b4f.png)
![image](https://user-images.githubusercontent.com/18045503/95168848-9129ea00-07cf-11eb-9c1e-b597507fa2b6.png)

**Certificate validation issue:** [ValidationResult.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5331792/ValidationResult.zip)
**Min Target version** : 1809 (17763)
**Target version**     : 1903 (18362)
**VS version**          : 16.8.0 Preview 3.2

Do I need to change my environment or something issue with WinUI publish.

**Comment by StephenLPeters** [comment]
@ryandemopoulos @MikeHillberg @Austin-Lamb FYI.

**Comment by bpulliam** [comment]
UWP is no longer supported by WinUI 3.  If you can repro the issue on current builds without UWP, please reactivate or open a new issue.

Thanks!
