### ISSUE TITLE
Question: Is there analogue for Window.Current.Compositor in WinUI for Desktop?

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3376]
Hello!

I am porting UWP application to WinUI (Desktop) and found an issue with porting custom composition brushes.

The issue is when composition brush connected, I should get Compositor to create effects, as described in [this](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.xamlcompositionbrushbase?view=winrt-19041) article.

![image](https://user-images.githubusercontent.com/23479280/95196955-7eb8ac00-07e1-11eb-83e7-7d0327e6ca9c.png)

But in Desktop app the Window.Current property is always null. What I should use in this case?

**Comment by StephenLPeters** [comment]
The desktop app template has a MainWindow which derives from Window which you can grab the compositor from.

**Comment by BorzillaR** [comment]
@StephenLPeters, yes, when brush classes is defined in the application this approach will work. But we have custom brushes in a custom class library. We have no access to the application and the main window. How we can get Compositor in this case?

**Comment by alexdi220** [comment]
Updates? Is there a way to get Compositor without the window? At now, the WinUI has a gap beside the window and its content. There is no way to get the main window in App because the CoreWindow is null for the desktop. On the other side, each UIElement has the XamlRoot. It looks similar but there is no access to the composition layer via that.

**Comment by codendone** [comment]
@alexdi220 We added this API for this scenario: [CompositionTarget.GetCompositorForCurrentThread()](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.media.compositiontarget.getcompositorforcurrentthread?view=winui-3.0)

**Comment by alexdi220** [comment]
Thank you so much @codendone! Best thing that's happened to me all last day. It would be great to mention that case in docs, maybe [here](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.composition.compositor?view=winui-3.0)

**Comment by DRAirey1** [comment]
Spent a day trying to hunt this down. There are no examples anywhere that Google could find. No examples of this in the gallery either. I even posted on StackOverflow and no answers there.
