### ISSUE TITLE
Move styles from RevealBrush_..._themeresources.xaml to appropriate control projects

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3378]
Unless there is a specific reason for this, I think it would be better to move reveal styles into the control projects. When trying to search for something like "AppBarButtonRevealStyle", most people would probably look in the AppBarButton_themeresources.xaml file. Given that the RevealBrush project isn't directly visible as it sits inside the Material folder, people might not find the resources without using ctrl+f.

**Comment by StephenLPeters** [comment]
I think I agree.
