### ISSUE TITLE
ResourceManager.LoadPriFiles() throws InvalidCastException

### ISSUE THREAD

**Issue by Palatis** [microsoft/microsoft-ui-xaml#3379]
**Describe the bug**
```
Loading ResourceMap failed: System.InvalidCastException: Specified cast is not valid.
  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
  at WinRT.IObjectReference.As[T](Guid id)
  at ABI.System.Collections.Generic.IEnumerable`1.CreateMarshaler(IEnumerable`1 obj)
  at ABI.Windows.ApplicationModel.Resources.Core.IResourceManager.LoadPriFiles(IEnumerable`1 files)
  at Windows.ApplicationModel.Resources.Core.IResourceManager.LoadPriFiles(IEnumerable`1 files)
  at TestWinUI3.App.LoadMyPriFiles()
```

**Steps to reproduce the bug**

1. just call the `ResourceManager.Current.LoadPriFiles()`...

**Expected behavior**
pri file loaded successfully

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20226)              | yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@stevenbrix or @alwu-msft thoughts here? my hunch is a cs winrt bug?

**Comment by alwu-msft** [comment]
Yeah, most likely a CsWinrt bug. @Scottj1s

**Comment by evelynwu-msft** [comment]
Closing as this does not repro with WinAppSDK 1.3.
