### ISSUE TITLE
ItemsRepeater Scroll Loop Bug

### ISSUE THREAD

**Issue by dannyp32** [microsoft/microsoft-ui-xaml#3380]
**Describe the bug**
In some cases, when scrolling all the way to the bottom in an items repeater, it loops around the last and 2nd to last items. I've attached a gif that shows this in more detail. 

**Steps to reproduce the bug**

We are able reproduce with the Your Phone app in the notifications section. The current repro has about 16 items in the list. 
The easiest way to repro is as soon as the list loads, scroll to the very bottom. It does not always repro. I think there is some combination of the vertical height of the items and the available verticle size that causes the issue. 

1. Have enough notifications to be able to scroll.
2. Scroll all the way to the bottom. 
3. See the list jumping/looping around the last item. 

**Expected behavior**
Scrolling ends, no looping behavior. 

**Screenshots**
![scrollloop_short](https://user-images.githubusercontent.com/921928/95243113-00e6a780-07c5-11eb-95c0-3b487c4c08b3.gif)

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.4.3]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20226.1000)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ranjeshj thoughts here as well?

**Comment by ranjeshj** [comment]
@dannyp32 sorry for the delayed response, if you can share a standalone repro, that would be very helpful. Are items being added when you are scrolling ? (I see refreshing... at the top)
