### ISSUE TITLE
ItemsRepeater list blank rendering bug

### ISSUE THREAD

**Issue by dannyp32** [microsoft/microsoft-ui-xaml#3381]
**Describe the bug**
This does not repro 100% of the time, but there are cases where the items of the list do not render. Scrolling fixes the issue if there are enough items to scroll.  

I’ve attached an image of what this bug looks like to users in the Your Phone app. As you can see in the picture the scrollbar is visible and shows that there are several items in the list. Typically when scrolling up and down the items in the list will eventually appear, but only if the list is long enough to scroll a decent amount (possibly until the virtualization reaches a new window of items that are realized so a new batch is being rendered). 
This issue I can reproduce pretty regularly by inserting a lot of items quickly. 

**Steps to reproduce the bug**
Hard to tell what causes this. I've noticed it occur when inserting lots of items into the list quickly. 

**Expected behavior**
The list of items is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/921928/95247833-3bebd980-07cb-11eb-8dab-89ff347dceb8.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.3]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20226.1000)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by dannyp32** [comment]
Gif showing inserting multiple items can cause the issue to appear

![itemsrepeaterBug](https://user-images.githubusercontent.com/921928/95266881-f3431900-07e8-11eb-8109-33750f7ef6fa.gif)

**Comment by StephenLPeters** [comment]
@ranjeshj thoughts?

**Comment by ranjeshj** [comment]
@dannyp32 sorry about the delayed response. Would you be able to provide a standalone repro to debug ?

**Comment by dannyp32** [comment]
@ranjeshj  @StephenLPeters Here's a test app you can use to repro. Repros 100% if you insert into the beginning of the list a few times. 



[TestAppRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5581716/TestAppRepro.zip)


![RepeaterRepro](https://user-images.githubusercontent.com/921928/99941789-78e04100-2d23-11eb-8674-e5035c2b671a.gif)
.

**Comment by chingucoding** [comment]
I would like to look into this issue,

**Comment by wbokkers** [comment]
I have rendering issues in WinUI Desktop, where ItemsRepeater will only show the first item. Maybe this is related.

**Comment by chingucoding** [comment]
Thank you for mentioning that! Do the other items render if you resize the window or repeater? If not, I think you are experiencing a different bug; resizing the repro app of this issue shows the items in question.

**Comment by wbokkers** [comment]
I have the repeater in a ScrollViewer. I use horizontal scrolling, and the layout property is set as follows:
 ```
<ItemsRepeater.Layout>
            <controls:StackLayout Orientation="Horizontal"  />
 </ItemsRepeater.Layout>
```

**Comment by chingucoding** [comment]
With "resizing", I meant the following:
![Gif of resizing app which shows items](https://user-images.githubusercontent.com/16122379/100145303-69363900-2e98-11eb-997d-9ce244172346.gif)

**Comment by wbokkers** [comment]
When I want to try to resize, I need to remove the ScrollViewer. If I do this, the ItemRepeater works as expected. So my issue is ScroViewer related. Sorry for the confusion.

**Comment by chingucoding** [comment]
@ranjeshj Is that a know WinUI 3 issue? I couldn't find an open issue for this.

@wbokkers If you have time, it would be great if you can create a repro app for that bug.

**Comment by wbokkers** [comment]
@chingucoding I will try to create a repro app

**Comment by wbokkers** [comment]
@chingucoding Check out this github repro to see an issue with items added to an ItemRepeater not being rendered:
https://github.com/wbokkers/winui-desktop-issues
