### ISSUE TITLE
UWP XAML Templated Control is broken in VS2019 Preview 1.0

### ISSUE THREAD

**Issue by marb2000** [microsoft/microsoft-ui-xaml#3382]
**Describe the bug**
In the past, the item template for a XAML Templated Control generates a simple sample that compiles and builds properly. However, this item template no longer compiles and builds.

**Steps to reproduce the bug**

1. Open VS2019 Version 16.9.0 Preview 1.0
2. Create a UWP Class Library in C#
3. Add an New Item - Templated Control
4. Compile

**Observed**
Severity              Code     Description        Project  File        Line              Suppression State
- Error                   The XAML Binary Format (XBF) generator reported syntax error '0x03e9'    UILibrary C:\source\repos\TemplatedControlBug\UILibrary\Themes\Generic.xaml              6            

- Error                   The "CompileXaml" task returned false but did not log an error.    TemplatedControlBug                                

- Error                   Cannot resolve Assembly or Windows Metadata file 'C:\source\repos\TemplatedControlBug\UILibrary\bin\x86\Debug\UILibrary.dll'              TemplatedControlBug C:\source\repos\TemplatedControlBug\TemplatedControlBug\TemplatedControlBug.csproj

**Expected behavior**

Compile and build, so I can use the new templated custom control in my projects.

**Version Info**

VS2019 Version 16.9.0 Preview 1.0

**Repro**
[UILibrary.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5336783/UILibrary.zip)

**Comment by jordanisaacs** [comment]
I am on VS2019 Version 16.8.1 and received the XBF error 0x03e9 syntax error when using the Visual Studio menu to create a template control. My solution compiled and ran before creating the template control. I updated to 16.8.2 and still received the error. It XBF error was accompanied with an error saying that the CustomControl does not exist in the namespace autogenerated (even though it does).

**Comment by stevenbrix** [comment]
@jordanisaacs thanks for your input, can you confirm that this is a regression?

**Comment by bpulliam** [comment]
UWP is no longer supported by WinUI 3.  If you can repro the issue on current builds without UWP, please reactivate or open a new issue.

Thanks!
