### ISSUE TITLE
App does not respond to theme changes  in Windows when selecting Windows Default theme until restarted

### ISSUE THREAD

**Issue by vmadurga** [microsoft/microsoft-ui-xaml#3385]
**Describe the bug**
App does not respond to theme changes in Windows when selecting Windows Default theme until restarted
  
**Steps to reproduce the bug**
In the attached repro project
 
1. Start ThemeSupportApp
2. Go to the setting page
3. Ensure Default Theme is selected
4. Open Windows Settings and change default app mode to Dark

 
**Observed**
 
The App continues to show in Light Theme
Re-opening the app causes correct theme to be applied
 
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/25466105/95323205-1380df80-089e-11eb-9429-c0ce4a0807bc.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/25466105/95323202-12e84900-089e-11eb-89dd-13a468a05990.png)
 
**Expected behaviour:**
 
The app should respond to the Theme change and switch to dark theme.
  
**Version Info**
 
WinUI3 3.0.0-preview2.200713.0
 
**Repro**
[ThemeSupportApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5340109/ThemeSupportApp.zip)

 
The project was created with WinUI3 Templates from Windows Template Studio, tracking issue on our side is https://github.com/microsoft/WindowsTemplateStudio/issues/3810

**Comment by StephenLPeters** [comment]
We saw an issue similar to this about switching high contrast theme, which is a bug that has been in the system for effectively ever.  This however appears to be a Winui 3 regression.

**Comment by chrisglein** [comment]
> This however appears to be a Winui 3 regression.

Do we have anything to show that? My assumption is that this issue that existed in OS XAML has persisted into WinUI 3. Which is unfortunate but expected.

See this issue #2958.

**Comment by StephenLPeters** [comment]
> > This however appears to be a Winui 3 regression.
> 
> Do we have anything to show that? My assumption is that this issue that existed in OS XAML has persisted into WinUI 3. Which is unfortunate but expected.
> 
> See this issue #2958.

The issue you linked is about changing high contrast themes where this is just windows theme, dark to light.  You can see this working with xaml controls gallery today by changing your theme from light to dark with it open.

**Comment by mvegaca** [comment]
Still happens in WinUI 3 Preview 4

**Comment by codendone** [comment]
This issue is now fixed internally, but wasn't in time for Preview 4.

**Comment by sibille** [comment]
This issue is solved after updating to Project Reunion 0.5 Preview

**Comment by codendone** [comment]
Indeed. Thanks for confirming, @sibille! Closing as fixed in Project Reunion 0.5 Preview.
