### ISSUE TITLE
Application crashed on set binding from code

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3388]
**Describe the bug**

I tried to set binding from the code

![image](https://user-images.githubusercontent.com/23479280/95382056-bc0c5f00-08f1-11eb-9e9f-024029119a7a.png)

Application crashed on start up. I noticed that this happens when MyViewModel is descendant of DependencyObject

**Steps to reproduce the bug**

1. Open and run a sample in attachment

**Version Info**

Windows 10 1903 (OS Build 18362.1082)

**NuGet package version:**

WinUI 3.0.0-preview2.200713.0

**Windows app type:**

| UWP              | Win32            |
| :--------------- | :--------------- |
|| Yes|

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

[SampleProject.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5343530/AttachedCollections.zip)

**Comment by BorzillaR** [comment]
The Issue is not reproduced in Preview 3 and can be closed.
Thank you!

**Comment by codendone** [comment]
Excellent, thanks for confirming!
