### ISSUE TITLE
Winui 3.0 licensing scheme

### ISSUE THREAD

**Issue by JohnF38** [microsoft/microsoft-ui-xaml#3391]
Hi !

I'm considering the forthcoming Winui 3.0 for a new data visualization application.
This new app would be commercial one, so I'm wondering : what is the licensing scheme of Winui 3.0 ?

Do we have to buy a license to release commercial apps based on Winui 3.0 ?

Thanks, 
John

**Comment by kmgallahan** [comment]
https://github.com/microsoft/microsoft-ui-xaml/blob/master/LICENSE

**Comment by StephenLPeters** [comment]
You do not need to buy a license.
