### ISSUE TITLE
Application crasches when Window has content with CustomControl

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3392]
**Describe the bug**
Hi, I've faced an issue when I put an inheritor of the FrameworkElement to MainWindow.Content the app crashes without any exception. The stack and project were attached.

~~~ csharp
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
            Content = new TestFrameworkElement();
        }

    }
    public class TestFrameworkElement : FrameworkElement {
        public TestFrameworkElement() {
        }
    }
~~~

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | < Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            |  Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

[CustomContentCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5347853/CustomContentCrash.zip)
[Stack.txt](https://github.com/microsoft/microsoft-ui-xaml/files/5347854/Stack.txt)

**Comment by StephenLPeters** [comment]
@stevenbrix Is this also a cswinrt bug? the provided call stack doesn't have any useful symbols, but I don't see any dll names that would suggest cswinrt... however the C# derivation usually points to this.

**Comment by VitalyTVA** [comment]
This issue also exists in C++/WinRT - see attached sample. 

```cs
    MainWindow::MainWindow()
    {
        InitializeComponent();
        MyFrameworkElement element;
        Content(element);

    }
```

```
namespace App2CPP
{
    [default_interface]
    runtimeclass MyFrameworkElement : Microsoft.UI.Xaml.FrameworkElement
    {
        MyFrameworkElement();
    }
}
```

[App2CPP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5400524/App2CPP.zip)
[stack.txt](https://github.com/microsoft/microsoft-ui-xaml/files/5400562/stack.txt)

**Comment by BorzillaR** [comment]
This issue is not reproduced in Preview 3 and can be closed. 

Thank you!

**Comment by codendone** [comment]
Excellent! Thanks for testing on Preview 3!
