### ISSUE TITLE
NugetPackage: Searching "WinUI" does not show WinUI package in first 30 results

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3398]
When searching for "WinUI" on nuget.org or the VS Nuget Package Manager, WinUI shows up very low in the list. Maybe we can add tags or update the description of the package so it shows up higher in the list?

**Comment by kmgallahan** [comment]
![Screenshot 2020-10-09 093756](https://user-images.githubusercontent.com/5379488/95589733-249f2d00-0a13-11eb-8396-0d46aa072850.jpg)

**Comment by chingucoding** [comment]
![image](https://user-images.githubusercontent.com/16122379/95590199-0a327700-0a46-11eb-96cc-2c7e54d1b2d1.png)

Notice that WinUI (not winui) is the official capitalization of this project, using the official name should not result in the product ending on page 2 of the nuget searches.

**Comment by Felix-Dev** [comment]
The following tags in use are displayed by the VS Nuget Package Manager:

![image](https://user-images.githubusercontent.com/1398851/95590847-da37a380-0a46-11eb-9353-ee69987945d2.png)

A "WinUI" tag is already included, yet searching for "WinUI" still doesn't make it show up high in the list: 
![image](https://user-images.githubusercontent.com/1398851/95591106-297dd400-0a47-11eb-87c7-028cc5b95da7.png)

**Comment by chingucoding** [comment]
So the nuget search is just bad in that regard? What's the purpose of the tags then if they don't seem to help. Maybe adding the "WinUI" to the description helps? I'm quite confused now what exactly is being used to order the list of search results.

**Comment by kmgallahan** [comment]
Apparently capitalization matters, as the owners of the package are Microsoft and winui, rather than WinUI.

Seems more of a problem with the nuget search function than anything, as changing to owner to WinUI would then presumably produce the same bad results while searching for winui.

**Comment by kmgallahan** [comment]
Further, the search seems equally bad in the regard that the "WinUI" string is completely absent from their description/tags/owners/etc. E.g. https://www.nuget.org/packages/Microsoft.Win32.Registry

**Comment by StephenLPeters** [comment]
Thanks for the report, following up with some folks internally.

**Comment by chingucoding** [comment]
Closing this issue now as searching for "WinUI" now also lists WinUI as the first result and as such has been resolved:

![Screenshot of search results for WinUI](https://user-images.githubusercontent.com/16122379/103142016-b60e6900-46fd-11eb-8306-521d5ae78a90.png)

Thanks to everyone who was involved in fixing this :)
