### ISSUE TITLE
FileSavePicker.FileTypeChoices throws InvalidCastException

### ISSUE THREAD

**Issue by KiruyaMomochi** [microsoft/microsoft-ui-xaml#3399]
## Describe the bug

**Trying to execute any methods of `folderPicker.FileTypeFilter` will throw an exception.**

## Steps to reproduce the bug

1. Clone https://github.com/microsoft/WinUI-3-Demos/
2. Edit [36-45 Lines of MainWindow.xaml.cs](https://github.com/microsoft/WinUI-3-Demos/blob/0bc934a6716235a7f55e3f2a90f4dbb045a0697d/DemoBuildCs/DemoBuildCs/DemoBuildCs/MainWindow.xaml.cs#L36-L45) to 
```c#
var savePicker = new FileSavePicker();

//Make folder Picker work in Win32
IntPtr windowHandle = (App.Current as App).WindowHandle;
InitializeWithWindowWrapper initializeWithWindowWrapper = InitializeWithWindowWrapper.FromAbi(savePicker.ThisPtr);
initializeWithWindowWrapper.Initialize(windowHandle);
folderPicker.FileTypeFilter.Add("*");

savePicker.FileTypeChoices.Add("Plain Text", new List<string>() { ".txt" });
savePicker.SuggestedFileName = "OUTPUT";
Windows.Storage.StorageFile file = await savePicker.PickSaveFileAsync();
textBox.Text = file!= null ? file.Name: string.Empty;
```
3. Run the app, click the Browse button.
4. The app will crash with exception `System.InvalidCastException` ("Specified cast is not valid").

  | Name | Value | Type
-- | -- | -- | --
▶ | savePicker.FileTypeChoices.Add("Plain Text", new List<string>() { ".txt" }); | 'savePicker.FileTypeChoices.Add("Plain Text", new List<string>() { ".txt" })' threw an exception of type 'System.InvalidCastException' | void {System.InvalidCastException}

## Expected behavior
A file save picker is opened. User can pick a file, then it's path is shown in textbox.

## Screenshots
![image](https://user-images.githubusercontent.com/65301509/95590372-9067b100-0a78-11eb-9feb-158e7d2b3817.png)

## Version Info

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20231)              | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

## Additional context

When trying to watch `savePicker`, I can see

  | Name | Value | Type
-- | -- | -- | --
▶ | FileTypeChoices | 'savePicker.FileTypeChoices' threw an exception of type 'System.InvalidCastException' | System.Collections.Generic.IDictionary<string, System.Collections.Generic.IList<string>> {System.InvalidCastException}

I guees there is something abnormal with `savePicker.FileTypeChoices`.

**Comment by StephenLPeters** [comment]
@stevenbrix this seems very similar to some previous file picker issues we've had, but we are having trouble finding them.  I'd guess another cswinrt issue.

**Comment by StephenLPeters** [comment]
@Scottj1s FYI

**Comment by Jaiganeshkumaran** [comment]
File picker isn't part of WinUI

**Comment by stevenbrix** [comment]
@KiruyaMomochi we're preparing for the upcoming Preview3 release of WinUI3, and there have been a lot of C#/WinRT and .NET5 changes since then. I'm sorry you are running into this, I personally won't be able to debug into this issue with Preview2. `System.InvalidCastExceptions` are fairly common in earlier versions of C#/WinRT, but should hopefully be fixed with the introduction of https://github.com/microsoft/CsWinRT/issues/292

@marb2000 we should do a sweep of the WinUI3 demos and make sure they are updated/functional for the upcoming November preview of WinUI3, can you drive this?

**Comment by marb2000** [comment]
@stevenbrix sure, demo samples will be updated. 
@KiruyaMomochi I will take a look to this issue to see if it repros in the next Preview.

**Comment by marb2000** [comment]
I forgot to say that the demos where updated: https://github.com/microsoft/WinUI-3-Demos/ and I'm no longer see this issue.

Thanks. I'm closing the issue, feel free to reopen it in case I miss something.
