### ISSUE TITLE
Consolidate tests on either MSTest or TAEF instead of cross-compiling for both

### ISSUE THREAD

**Issue by llongley** [microsoft/microsoft-ui-xaml#340]
Our automated testing is currently split into two parts: MSTest for local test runs and TAEF for remote test runs.  This adds ultimately unnecessary complexity to our solution and means that we need to build more binaries than we actually are likely to want to use.  We should ultimately move away from TAEF and only use MSTest, but before we can do that, we need to find a way to run the tests that we currently have as AppX-based tests on a remote machine.  DLL-based tests can be ran simply by copying the test running infrastructure from VS to a remote machine, but AppX-based tests require a VS install to work properly.  We should invest time to find and implement a solution to this issue to simplify our test infrastructure.

**Comment by chingucoding** [comment]
It seems that for appx tests, you "only" need vstest console, which apparently ships with [the Microsoft.TestPlatform nuget package](https://www.nuget.org/packages/Microsoft.TestPlatform/). Since nupgk files are just zips and inside that zip, there is actually a vstest.console.exe we could use for the tests. Maybe that is a possible way to deprecate TAEF tests?

**Comment by ranjeshj** [comment]
@llongley @kmahone could we use this nuget ? Are there any other issues you can think of that might be blocking this.

**Comment by chingucoding** [comment]
An additional motivation to move to MSTest only, is that we could safely start using DataTestMethods, to make it easier to write parameterized tests.

**Comment by kmahone** [comment]
We are fairly unlikely to ever move away from TAEF. It would be more likely that we would consolidate on TAEF (after getting them to work from within VS) and get rid of MSTest. One reason for this is that WinUI3 has thousands of tests, all written in TAEF and it would not be feasible to port them to MSTest.
