### ISSUE TITLE
Question: What is the future of the Acrylic material?

### ISSUE THREAD

**Issue by Alkanores** [microsoft/microsoft-ui-xaml#3401]
In the newest versions of WinUI library for UWP we cannot use the Acrylic material as background in NavigationView and  MenuFlyout controls by default. What is the future of the Acrylic material?

+
In video "Windows 10 reaches 1 Billion" we see new design concept, how many time will need to realize this in the WinUI?

![image](https://user-images.githubusercontent.com/49155506/95606515-1b3db100-0a63-11eb-87bc-0c30abd685c6.png)

Thanks.

**Comment by StephenLPeters** [comment]
We've had a few discussions about this in the past, I can point you to @ryandemopoulos reponse to one of them here: https://github.com/microsoft/microsoft-ui-xaml/issues/2236#issuecomment-610120152
