### ISSUE TITLE
NumberBox height behavior is inconsistent with TextBox

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/microsoft-ui-xaml#3402]
**Describe the bug**

The vertical behavior of `NumberBox` is different than from `TextBox`:
- `TextBox` seems to follow the height of its container
- `NumberBox` seems not to follow the height of its container.

**Steps to reproduce the bug**
Code to reproduce:
```xml
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="Auto" />
    </Grid.ColumnDefinitions>
    <StackPanel Orientation="Horizontal">
        <muxc:NumberBox PlaceholderText="Quantity" />
        <TextBox PlaceholderText="Unit" />
        <TextBox PlaceholderText="Name" />
    </StackPanel>
    <Grid Grid.Column="1" x:Name="hoverArea" Visibility="Visible" VerticalAlignment="Stretch">
        <AppBarButton Icon="Delete" Background="red" Height="50" IsTabStop="False" LabelPosition="Collapsed" VerticalAlignment="Stretch" />
    </Grid>
</Grid>
```

**Expected behavior**

Since `NumberBox` looks like a `TextBox` with additional number capabilities, I would expect `NumberBox` to behave the same. **I do not have preference for either behavior, I just expect them to behave the same.**

**Screenshots**

![image](https://user-images.githubusercontent.com/3463496/95632306-a7f96680-0a85-11eb-81ed-236b75f62e73.png)

**Version Info**

NuGet package version: Microsoft.UI.Xaml.2.5.0-prerelease.200923002

Windows app type: UWP
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Not applicable |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |Did not test  |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       | Did not test   |
| May 2019 Update (18362)            |Did not test   |
| October 2018 Update (17763)        | Did not test   |
| April 2018 Update (17134)          | Did not test  |
| Fall Creators Update (16299)       | Did not test   |
| Creators Update (15063)            | Did not test

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | Did not test |
| Surface Hub        |Did not test |
| IoT                | Did not test |

**Additional context**

**Comment by chingucoding** [comment]
I would like to work on this.
