### ISSUE TITLE
Discussion: Stop using rounded corners by default in Fluent and Windows

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#3406]
# Discussion: Stop using rounded corners by default in Fluent and Windows

I always liked MDL and Fluent because the have sharp corners which I really like. It's the unique thing that was different for Microsoft products and please stop using Rounded Corners and please stop copying other designs in the name of Fluent. I hate rounded corners and even with 2px it's bad and only wastes power and has no value. If apps want they can change Corner Radius but Microsoft shouldn't use it by default and Windows should have sharp corners forever. If you do use Rounded Corners, please attest to improve the rendering. Currently, it looks like it has been cut and looks terrible. I like thin border sizes introduced recently but not the rounded corners.

**Comment by Felix-Dev** [comment]
@Jaiganeshkumaran You can read through use https://github.com/microsoft/microsoft-ui-xaml/issues/524 which first introduced rounded corners to WinUI to find out why Microsoft Design wanted these changes.

We already have quite a few issues where rendering is called out: https://github.com/microsoft/microsoft-ui-xaml/issues/2751 and https://github.com/microsoft/microsoft-ui-xaml/issues/1953 for example

**Comment by AzAgarampur** [comment]
Honestly, I've always loved Windows especially because of the sharp corners. The UI is pleasant and looks professional. I don't think we can use rounded corners in just WinUI, as the rest of the OS (non UWP aka Win32) still has sharp corners.

IMO making everything have a soft corner gives a very "fisher-price" feel to me. Many people complain that a rectangle-like UI element looks old, but with a little bit of shadows and fabric colors, I bet they'd look amazing.

**Comment by mdtauk** [comment]
For your own apps, you can set the CornerRadius values to 0 to remove them.

But this is the new Fluent Design which has taken over from MDL2 and the previous Metro design elements.  Android, iOS, macOS, and pretty much most Linux distros - all make use of rounded corners, as did Windows 7, Vista, XP.

Fluent and Windows 10 is about making the UI feel familiar among other devices, whilst also remaining clean and functional.

**Comment by Jaiganeshkumaran** [comment]
@mdtauk Just because other operating systems use doesn't mean Windows should use it. Rounded corners are ugly and looks bad.

**Comment by mdtauk** [comment]
> @mdtauk Just because other operating systems use doesn't mean Windows should use it. Rounded corners are ugly and looks bad.

This is your personal subjective opinion, of which I disagree,

My comment before was just to illustrate that rounded corners are not abnormal, and certainly not new to Windows.

**Comment by adambarlow** [comment]
@Jaiganeshkumaran we really appreciate your opinion and sharing the way you feel. The rounded corners are a deliberate design choice and represent and aesthetic quality that we are comfortable with and excited about!
