### ISSUE TITLE
Failed to assign to property 'Windows.UI.Xaml.Controls.AppBarButton.Label' because the type '%2' cannot be assigned to the type 'Windows.Foundation.String'

### ISSUE THREAD

**Issue by mc0re** [microsoft/microsoft-ui-xaml#3407]
**Describe the bug**
All the description I have is here:
https://appcenter.ms/users/admin-shieldplayer/apps/Shield-Player/crashes/errors/3448336883u/reports

The error report looks like this.
```
Incident Identifier: 40844f61-50cd-4f3f-8271-c2d9ad254da6
CrashReporter Key:   33478228-b8fd-4861-8839-1cb148e12ea5
Hardware Model:      A55MD2
```

***ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32)***
System.Exception: Failed to assign to property 'Windows.UI.Xaml.Controls.AppBarButton.Label' because the type '%2' cannot be assigned to the type 'Windows.Foundation.String'. Failed to assign to property 'Windows.UI.Xaml.Controls.AppBarButton.Label' because the type '%2' cannot be assigned to the type 'Windows.Foundation.String'.

OS: WINDOWS 10.0.17763

***Main thread***
```
System.Runtime.InteropServices
McgMarshal.ThrowOnExternalCallFailed (Int32, RuntimeTypeHandle)
__Interop
ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32)
__Interop
ForwardComStubs.Stub_10[TThis] (__ComObject, Int32)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelper.<ctor>b__17_1 (Object, UnhandledErrorDetectedEventArgs)
```

**Steps to reproduce the bug**
Unfortunately, I don't know.

**Expected behavior**
No error message *or* some explanation about "type '%2'".

**Screenshots**
N/A

**Version Info**
UWP app: UAP,Version=10.0.18362.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Tes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  |
| May 2020 Update (19041)            |   |
| November 2019 Update (18363)       |  |
| May 2019 Update (18362)            |  |
| October 2018 Update (17763)        | Yes |
| April 2018 Update (17134)          |  |
| Fall Creators Update (16299)       |  |
| Creators Update (15063)            |  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
I don't have access to that link, can you provide more details in this issue description?

**Comment by mc0re** [comment]
Updated the description.

**Comment by mc0re** [comment]
Found some additional, potentially useful info.

The `Label` property is set in XAML via a custom markup extension:
```xaml
<AppBarButton Click="{x:Bind About_Click}" Label="{l:Text TextId=Player.AboutMenu}"/>
```

The extension creates a `Binding` object, which points to a `string`.

Maybe, `Binding` is not supported in that version of Windows (17763)? If so, I can return a static string (which becomes non-updateable), but how do I know, which version(s) of Windows to do that for, and how can I determine that from a markup extension?

**Comment by StephenLPeters** [comment]
Can you provide a repro app as an attachment to the issue? without it there isn't much we can do here.

**Comment by mc0re** [comment]
I can try putting together the code pieces I posted above. But I do not know whether this will reproduce the issue, I do not have that old version of Windows 10. Is it not possible for you guys to scan the code for "%2"? It's not often "%2" is used in C#...

**Comment by StephenLPeters** [comment]
%2 is coming from the formatted string for the error message, the parameter is null. This will be difficult to track down just from a source scan.

**Comment by mc0re** [comment]
> the parameter is null
What parameter?

**Comment by StephenLPeters** [comment]
The parameter to whatever formatted string the error system is attempting to present. We need a repro under a debugger to see what it is.

**Comment by mc0re** [comment]
@StephenLPeters I have crafted a sample project, which includes the text handling part of the main project. As said, it only fails on 10.0.17763, so I do not know whether it can reproduce the error. How do I send it to you guys? It's a mere 64 KB archive.

**Comment by StephenLPeters** [comment]
@mc0re either upload it to github or attach it to a comment as a zip file.

**Comment by mc0re** [comment]
I couldn't find the "attach" button. But now I noticed the footnote about drag-and-drop :-)
[ProcentTwoError.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5493671/ProcentTwoError.zip)

**Comment by StephenLPeters** [comment]
@chrisglein and @fabiant3 I suspect this is a platform issue with MarkupExtension, not sure which team owns it.

**Comment by chrisglein** [comment]
Based on this involving a custom markup extension I'd guess team-Markup.

**Comment by fabiant3** [comment]
@alwu-msft - please take a look when you get a chance

**Comment by mc0re** [comment]
Anyone, please? The problem is still there. I know you won't make a Windows update for that :-), but maybe you can tell me how to avoid this problem. Currently it crashes the app without even `Analytics` picking up the error.

**Comment by alwu-msft** [comment]
@mc0re Sorry for the delay in responding; I thought I'd already answered your question, but I'm failing to find it so maybe it was just in my head. :(

Unfortunately the behavior you're trying to take advantage of (return a `Binding` from a custom markup extension to set up a binding targeting a non-`Binding` property) was only added with Windows 10 1903 (18362). You can use the [`ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 8)`](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.apiinformation.isapicontractpresent?view=winrt-19041) API to determine if the app is running on at least 18362, and return a `String` rather than a `Binding` if that is not the case.

**Comment by mc0re** [comment]
Thanks, this is the answer I needed.
