### ISSUE TITLE
Binding with complex path does not work

### ISSUE THREAD

**Issue by zed220** [microsoft/microsoft-ui-xaml#3409]
**Describe the bug**
Binding with complex path like "{Binding Path=MyClass.Value}" does not work.

**Steps to reproduce the bug**
1. Create some class with property like following:
```
public class MyClass : INotifyPropertyChanged {
	public MyClass(string value) => Value = value;

	public string Value { get; }

	public event PropertyChangedEventHandler PropertyChanged;
}
```
2. Bind from xaml to it's property:
`<TextBlock Text="{Binding Path=MyClass.Value}"/>`
3. Run app.

**Expected behavior**
Binding works fine.

**Version Info**
NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**

I have attached an example project that illustrates this problem.
[App13.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5364504/App13.zip)

**Comment by chrisglein** [comment]
@zed220 Did this equivalent markup+project worth without WinUI3?
(I'm assuming given that you're targeting WinUI3 that this is a regression relative to WinUI2/OS XAML)

**Comment by zed220** [comment]
Hi,

WPF, UWP and WinUI on UWP applications with similar binding works fine.

I can't test this on WinUI2.

**Comment by MichaeIDietrich** [comment]
Hi, correct me if I am wrong, but I don't see where you set the `DataContext` property in your code.

Could it be that you mixed up `{Binding}` and `{x:Bind}`?

`{Binding}` as in WPF uses the `DataContext` of the surrounding `FrameworkElement` while `{x:Bind}` uses the properties of the surrounding `FrameworkElement` directly.

**Comment by zed220** [comment]
Hello,

Thanks for your answer. As I can see, bindings to the Window class does not work at all because it does not have the DataContext property. Is it right behavior? Why the Window class does not have 
the DataContext property? Is It by design?

Thanks.

**Comment by chrisglein** [comment]
This sort of scenario definitely works in plain UWP against the `Page` type. This may be something specific to the WinUI3 `Window` type where it doesn't set up the binding context the same way that Page does. I'll follow up.

As general rule it's worth trying out `{x:Bind}` where you can. It's a bit more sensitive to the types of the objects involved so I find you can get clearer errors.

**Comment by marb2000** [comment]
@zed220 Are you assigning the ViewModel to the XAML's Window object? XAML's Window isn't a DependencyObject and doesn't have DataContext.

**Comment by zed220** [comment]
Hello,

Yes, right. In WPF I use the Window's DataContext property to set the root view model (MVVM). So, in WinUI I will place some container in Window's content and use it as a root object with the DataContext. 
Thanks
