### ISSUE TITLE
Windows Repo Access

### ISSUE THREAD

**Issue by jdm7dv** [microsoft/microsoft-ui-xaml#3410]
In WinUI 2.1 Release

There was a a batch file in the Windows Porting Directory  called 'PerformFullOSBuild'

I installed GVFS but my Microsoft account login fails after I set the initial passwords.

Do I need to set the System32 on the path? I might but it's the Microsoft Account. in the end.

what is 'rm' it's not in System32 or SystemWOW64

https://stackoverflow.com/questions/97875/rm-rf-equivalent-for-windows 

Do I need to install the Windows Subsystem for Linux I like UNIX better and Apple.

'rm' in just an old UNIX tool I don't have the Windows Store because I'm on 10 2019 Enterprise LTSC. here is the manual APPX

https://docs.microsoft.com/en-us/windows/wsl/install-manual

![Untitled](https://user-images.githubusercontent.com/8218836/95742090-7935e880-0c5d-11eb-89dc-8d29ae9df44a.png)
![Untitled2](https://user-images.githubusercontent.com/8218836/95742092-7935e880-0c5d-11eb-99c5-5eea3a834c8c.png)

![Untitled](https://user-images.githubusercontent.com/8218836/95745834-c61cbd80-0c63-11eb-89b5-32b912682d6d.png)

Installed the WSL and the Debian App Package.

![Untitled](https://user-images.githubusercontent.com/8218836/95746125-4511f600-0c64-11eb-88a1-9af286752eba.png)
 
Set up defaults on WSL, Maybe I need to use the WSL to setup the Windows Repo I'll run the batch file the in WSL or can I it's a batch file not a UNIX Shell script. Or do I need to build the new terminal?

![Untitled](https://user-images.githubusercontent.com/8218836/95748303-c9b24380-0c67-11eb-8f4e-0019f7107998.png)

Tried installing the Terminal but it's only for the Windows Mobile device family you can't build a 300gb GIt repo on Windows Mobile. I understand now maybe I need to run the batch file in the pws. 'rm' isn't even recognized in the powershell even through there is one.

All I can gather is it might be Windows remote management. I figured it out I need to put a GIt dir on the PATH.

![Untitled](https://user-images.githubusercontent.com/8218836/95754509-282fef80-0c71-11eb-89fe-9cbb749b702d.png)

What diskette is it? I guess I'll wait for Windows Internal 7th Part 2 in January. After the election.

I get it, it deleted Windows Porting and you do need a diskette with the batch files on it don't close this issue until I order some A: drive diskettes I have a floppy USB drive.

![1012201016](https://user-images.githubusercontent.com/8218836/95757008-8f9b6e80-0c74-11eb-92d4-c9d09dc1b511.jpg)

![Untitled](https://user-images.githubusercontent.com/8218836/95758596-aba00f80-0c76-11eb-8cf1-a8212fa11329.png)

re-extratcted Windows Porting and you might need to run the Cleanup batch file first it does set some GIt Env. Variables.
 and copy the 'ScriptstoCopy' to a diskette.

I ordered some AT&T Diskettes from ebay I rarely order from ebay.

I guess you should have an A, B, C, and D drive per group policy.

![Untitled](https://user-images.githubusercontent.com/8218836/95780189-6c36ea80-0c99-11eb-83b7-1f65a7062019.png)

![Untitled2](https://user-images.githubusercontent.com/8218836/95780191-6ccf8100-0c99-11eb-84ee-4e2a0caa52b1.png)

The diskette worked it just asks for my Microsoft Account before cloning the GVFS I tried entering in my credentials before and failed can someoneone @LanceMcCarthy grant me access please?

![Untitled2](https://user-images.githubusercontent.com/8218836/95781650-495a0580-0c9c-11eb-962c-38964388854b.png)

Reading the log "Git could not get credentials: Logon failed, use ctrl+c to cancel basic credential prompt." I'll try ctrl-c 

I also tried building WinUI 2.1 and use PkgGen.cmd  but Microsoft moved thier consumers the a condescending Azure dev ops domain at least I have a nuget account now.

**Comment by sylveon** [comment]
What

**Comment by yoshiask** [comment]
eh?

**Comment by LanceMcCarthy** [comment]
Hi Johnathan,

I'd like to help point you in the right direction, but I'm having difficulty in finding what you're trying to accomplish.  I'm not familiar with the folder path I see in that screenshot, it seems to be a old private repository, not this one.

![image](https://user-images.githubusercontent.com/3520532/95785509-e7050300-0ca3-11eb-878e-9a7f75552b68.png)


Try starting fresh:
1. Clone this repository https://github.com/microsoft/microsoft-ui-xaml/
2. Go into [the Tools folder](https://github.com/microsoft/microsoft-ui-xaml/tree/master/tools)  and find the script you're trying to use 
3. Run the script you were looking for.


Regarding the problem with authentication, at no point should you be required to connect to an internal Microsoft git/TFS endpoint. If that happens again, please let me know exactly what script was causing it and we can open a new issue to fix the URLs in that script

**Comment by LanceMcCarthy** [comment]
Quick follow up, I found the part of the script that is requiring ADAL login. This is indeed for internal build agent access and is not intended for use externally. See https://github.com/microsoft/microsoft-ui-xaml/blob/master/tools/BuildMachineUtils.psm1


Looping in @jevansaks 

Jevan, 
Johnathan is attempting to build this repo using the Microsoft PowerShell tasks. This requires authentication from an identity  that has access the TFS DefaultCollection OS (https://microsoft.visualstudio.com/DefaultCollection/OS/_apis/build/builds).

What can you recommend as an alternative?

**Comment by jevansaks** [comment]
None of these scripts/resources should be needed to build the project, as you suspect it's all for internal stuff. Much of it is deprecated now that we're shipping only out of band (and not as Windows.UI.Xaml.Controls.* also). 

If you want to build just clone the repo and build in VS or with "build.cmd".

**Comment by jdm7dv** [comment]
I guess I'll work on systems engineering and work on engineering a star on earth. goodbye.

**Comment by jevansaks** [comment]
Windows Repo Access is not publicly available. There's some scripts in here that can do things if you work at Microsoft and have access to the right resources, but most of them should just be deleted as they aren't even used anymore.

If you are looking to build the code in the open-source repo you can follow the [Developer Guide](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/developer_guide.md) for help getting started.

**Comment by jdm7dv** [comment]
According the Harvard Microsoft has lost there way I remember full OS source code licenses. at the academic level

[https://web.archive.org/web/20010418220512/http://research.microsoft.com/programs/NTSrcLicInfo.asp](url)

**Comment by jdm7dv** [comment]
Per United States Policy 20% of a companies code must be open.

[https://www.cio.gov/2016/08/11/peoples-code.html](url)

**Comment by sylveon** [comment]
This policy is only for government-developed source code. Microsoft still (and can) keeps Windows closed source.

**Comment by jevansaks** [comment]
Since this question is unrelated to this repo or component, I'm going to close this issue.

**Comment by jdm7dv** [comment]
According to Harvard Microsoft has lost there way There used to be better university programs. [https://hbr.org/2012/08/how-microsoft-and-netflix-lost](url)

**Comment by jdm7dv** [comment]
[https://www.quora.com/How-do-I-enable-hacker-mode-in-CMD](How to enable hackermode in ipconfig)
