### ISSUE TITLE
How to embed another executable inside a UserControl with WinUI 3 desktop (win32).

### ISSUE THREAD

**Issue by placasse** [microsoft/microsoft-ui-xaml#3411]
It is possible to embed a Unity engine game inside an application.
They give a working example using Windows Form [here](https://docs.unity3d.com/uploads/Examples/EmbeddedWindow.zip).
I'd like to reproduce this example with WinUI 3 for desktop (not UWP).

An example with notepad.exe embed into a wpf application can be found [here](https://www.codeproject.com/Tips/673701/Hosting-EXE-Applications-in-a-WPF-Window-Applicati).
I tried to port this example to WinUI 3 and I can briefly see the child process embed into my app but then it disappears.
Here is my attempt: [AppContainerWinUI3](https://github.com/placasse/AppContainerWinUI3) 

I used the IWindowNative trick to get a HWND of my application window.
However, in the example from Unity they use the System.Windows.Forms.Control.Handle .
What is the equivalent for a Microsoft.UI.Xaml.Controls.Control ?

**Comment by StephenLPeters** [comment]
I highly doubt this is supported (especially in UWP) but maybe @MikeHillberg knows how the WPF application hosting works and what winui might be missing for that.

**Comment by marb2000** [comment]
I don't believe you can do it. XAML's Window place a top window over the client area (using DesktopWindowXamlSource API) to render the XAML. I do recommend to open a feature request. 

Closing this question.

**Comment by isadrastea** [comment]
Can i get the proposal proceeding status ? Actually, i'd like to get the simple example like to embed notepad.exe.
