### ISSUE TITLE
Discussion: Employee or Independent Contractor? The Implications of Microsoft III

### ISSUE THREAD

**Issue by jdm7dv** [microsoft/microsoft-ui-xaml#3413]
"One might ask: "Who cares?" Until recently, the answer was: "The Internal Revenue Service cares." Obviously, an employer's report of an employee's earnings is presumed to be more accurate than an employee's individual return (if any). Further, withholding by the employer creates a more steady cash flow for the government than does the worker's annual return, even if quarterly estimated payments are made. More recently, however, the answer has been: "The misclassified employees care and so do their lawyers." This is because, due to the misclassification, the so-called independent contractors are deprived of lucrative fringe benefits enjoyed by the company's acknowledged "employees."

It developed a three-pronged test entailing the worker's expectations, his reliance on the expected payment, and his lack of bargaining power to negotiate the forfeiture clause out of the agreement. Based on this newly fashioned test, the appeals court remanded the case to the trial court which now found Darden to be an employee."

[Employee or Independent Contractor? The Implications of Microsoft III](https://corporate.findlaw.com/human-resources/employee-or-independent-contractor-the-implications-of-microsoft.html)

**Comment by jskeet** [comment]
I have contacted @jdm7dv as I believe their GitHub account has probably been compromised. (It posted a similar message in the .NET Foundation members team.)

**Comment by juanfranblanco** [comment]
Edited and changed the content too now

**Comment by Felix-Dev** [comment]
On the website https://www.jonathanmoore.net/ they claim to have officially worked on WinUI 2.1 as part of their Microsoft career. If that were true, the WinUI team should be able to easily recognize them.

I'm not sure if this isn't a bot account after all...

**Comment by jdm7dv** [comment]
No my GitHub was not compromised I've had it with Microsoft's promises.

**Comment by mdtauk** [comment]
> No my GitHub was not compromised I've had it with Microsoft's promises. not is not a bot account I'm real.
>
Not sure this is the appropriate place to bring up this subject however.
