### ISSUE TITLE
Discussion: A bright future for Moore’s Law

### ISSUE THREAD

**Issue by jdm7dv** [microsoft/microsoft-ui-xaml#3414]
Moore’s Law has been the guiding principle for the semiconductor industry for more than fifty years. For thirty of those years, I have had the privilege of working in Intel’s technology development organization — giving me a bird’s eye view of the breakthrough innovations that have enabled continued improvements in transistor density, performance, and energy efficiency. While there are many voices today predicting the imminent demise of Moore’s Law, I couldn’t disagree more. I believe the future is brighter than ever, with more innovative technology options in the pipeline now than I have seen at any point in my career.

[A bright future for Moore’s Law](https://venturebeat.com/2020/01/07/a-bright-future-for-moores-law/)

**Comment by mdtauk** [comment]
What has this got to do with WinUI?
