### ISSUE TITLE
Discussion: Intel Clear Linux is a distro that outperforms Windows 10 and Ubuntu… on cheap AMD hardware

### ISSUE THREAD

**Issue by jdm7dv** [microsoft/microsoft-ui-xaml#3415]
Intel’s Clear Linux distribution looks like it could be the best operating system to run on cheap AMD hardware, with benchmarks showing it outperforms Windows 10 and Ubuntu on a $199 laptop with a budget AMD Ryzen 3200U processor.

[Intel Clear Linux is a distro that outperforms Windows 10 and Ubuntu… on cheap AMD hardware](https://www.msn.com/en-us/news/technology/intel-clear-linux-is-a-distro-that-outperforms-windows-10-and-ubuntu%E2%80%A6-on-cheap-amd-hardware/ar-BBZKuUt#:~:text=Intel%20Clear%20Linux%20is%20a%20distro%20that%20outperforms,laptop%20with%20a%20budget%20AMD%20Ryzen%203200U%20processor.)

**Comment by mdtauk** [comment]
What has this got to do with WinUI?

**Comment by Felix-Dev** [comment]
@mdtauk This might be a bot/compromised github account (also see [this issue]/https://github.com/microsoft/microsoft-ui-xaml/issues/3413)).

**Comment by mdtauk** [comment]
> @mdtauk This might be a bot/compromised github account (also see [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/3413)).

I am coming to that conclusion
