### ISSUE TITLE
Custom Window Border, Dragable Controls & Unclickable Window (-> Overlay)

### ISSUE THREAD

**Issue by CXCubeHD** [microsoft/microsoft-ui-xaml#3419]
# Proposal: [Custom Window Border, Dragable Controls & Unclickable Window (-> Overlay)] 

## Summary

Add support for Custom Window Borders, Dragable Controls (not drag & drop) and to make a window unclickable (for overlay)

## Rationale

we need Custom Window Borders, because the default Win32 borders are ugly and don't fit mostly into our applications.
Also we could make OVERLAYS with unclickable window (example: Game Overlay WITHOUT DLL injection).
Even though making unclickable a window is possible with the win32 api, it's still kinda complicated and requires much effort

## Scope

| Capability | Priority |
| :---------- | :------- |
| Custom Window Border | Must |
| Dragable Controls | Should |
| Unclickable Window | Could |

**Comment by StephenLPeters** [comment]
These types of features would end up being implemented and owned by different technology teams at Microsoft.  Can you please open up separate feature proposals for each so I can loop in the right teams.
