### ISSUE TITLE
How to get notification in MFC application from UWP UI during user operations (E.g. Button click)?

### ISSUE THREAD

**Issue by densonpd** [microsoft/microsoft-ui-xaml#3421]
I have an MFC dialog based application and need to change that UI with UWP UI.
For that, designed a UWP UI and hosted on MFC application using XAML Hosting API.
But the problem is to invoke event handlers already present MFC application during a user operation on UWP UI.

For example; MFC button click event is handled in MFC application. Some logics are already implemented in this handler function.
I need to execute these logics during button click in UWP UI.
Is it possible to assign event handlers from MFC application to UWP button?
It will be very helpful if any reference is present for handling events from UWP UI in MFC application.

**Comment by StephenLPeters** [comment]
@Austin-Lamb or @marb2000 FYI

**Comment by marb2000** [comment]
Did you take a look at the [XAML Islands Samples](https://github.com/microsoft/Xaml-Islands-Samples)? There is a MFC sample using XAML Islands.
