### ISSUE TITLE
MRT Integration issue: BitmapIcon doesn't participate in resource qualifier change

### ISSUE THREAD

**Issue by marb2000** [microsoft/microsoft-ui-xaml#3423]
**Describe the bug**

 
#### The scenario
Terminal app is using a **BitmapIcon**. The app supports per-monitor DPI, switching on/off high-contrast, and light to dark themes. BitmapIcon is handful because it automatically recolors to match the foreground and works properly on high-contrast without having to ship a whole bunch of recolored image assets.

#### The issue
There is a bitmap icon’s source as UriSource=”ms-appx:///test.png”
```XAML
<AppBarButton Label="BitmapIcon" Click="AppBarButton_Click">
    <AppBarButton.Icon>
        <BitmapIcon UriSource="ms-appx:///test.png"/>
    </AppBarButton.Icon>
</AppBarButton>
```
Test.png is represented by two files on disk: test.scale-100.png and test.scale-150.png.
When the application is loaded at 150% scale, the scale-150 variant is chosen.
When the application is loaded at 100% scale, the scale-100 variant is chosen.
 
When the application is moved from one display at 100% to another at 150%, the icon does not change. This is true of moving into/out of high contrast as well with the .contrast_ modifiers.

**Expected behavior**
Load the right icon as soon as the display DPI changes.

**Version Info**
Terminal is using XAML Islands based on System XAML and WinUI 2.x. It happens in System XAML and WinUI 3 too.

**Comment by JeanRoca** [comment]
@marb2000 moving this over to the backlog

**Comment by michael-hawker** [comment]
Similar, if not related to [this internal tracking bug](https://microsoft.visualstudio.com/OS/_workitems/edit/20167860) for `Image` and theme changes as well.
