### ISSUE TITLE
ComboBoxBackgroundUnfocused is not used reasonably

### ISSUE THREAD

**Issue by bcassell** [microsoft/microsoft-ui-xaml#3424]
**Describe the bug**
In order to change the background of a ComboBox when it becomes focused, you have to modify the ComboBoxBackgroundUnfocused brush, since this controls HighlightBackground, which becomes opaque only on focus.

**Steps to reproduce the bug**
Try in vain to style the focus look of the background of a ComboBox using lightweight styling only to find out you have to modify ComboBoxBackgroundUnfocused

**Expected behavior**
The brush to modify would be named ComboBoxBackgroundFocused

**Comment by StephenLPeters** [comment]
Thanks for reporting this! definitely seems like a bug.

**Comment by chingucoding** [comment]
I would like to work on this.
