### ISSUE TITLE
Question: Is possible to implement with current version of the NavigationView like the Microsoft Store Style in Build 2017?

### ISSUE THREAD

**Issue by marck7jr** [microsoft/microsoft-ui-xaml#3439]
I would like to implement like that way, because for NavigationView with PaneDisplayMode set to Top, I prefer hidding some itens and show others instead the current Hierarchical behavior and honestly, I love how the animations and items respond in each context. Sorry if have any documentation with code sample, but I tried to search and I didn't find it, just only a sample in the presentation in the Build 2017 at 37:04 in the video below. Thanks for the attention.

https://www.youtube.com/watch?v=olNj4l0vxQU&feature=youtu.be&t=2205

![image](https://user-images.githubusercontent.com/30981574/96296542-6e60b800-0fbd-11eb-8af8-4a6ff7057439.png)

**Comment by StephenLPeters** [comment]
@marck7jr simply setting the navigation view's PaneDisplayMode to top will give the layout that is being presented in the youtube clip you linked.  If you are concerned with the over flow menu, which is when there are too many items to show in your navigation view and we end up showing a more button with the rest of the items in a drop down, you can see that store also does this at the 38:33 minute mark in that video.

Hierarchical navigation view only occurs when your navigation view items contain other navigation view items, so to avoid that look just avoid that scenario.

If your trying to get the affect where the items change when the home item is selected, I believe store is achieving that by changing the navigation view's item source when the home button is clicked to a different collection.

**Comment by StephenLPeters** [comment]
I'm going to close the question, but if this didn't answer it feel free to post again and I'll reopen.

**Comment by marck7jr** [comment]
Thanks @StephenLPeters I suspected that the implementation would be like this, but I was worried about the animations that, how I said, they are so good, but I think that with the implicit animations I can do something similar. So again, thanks for support.

**Comment by StephenLPeters** [comment]
Thats right, I think that store acheived these animations using implicit animations. Unfortunately I think it would be hard to dig up the specific implementation used in this demo... :/
