### ISSUE TITLE
x:Bind with ValueConverter raises exception 

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3442]
**Describe the bug**
Hi,  I've x:Bind with a converter that is set from StaticResource. When I start an application, it crashes with the exception - System.Runtime.InteropServices.COMException: 'Unspecified error Cannot find a resource with the given key: BoolToVisibilityConverter.'

**Steps to reproduce the bug**
Run the attached project. [xBindConverterIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5402235/xBindConverterIssue.zip)
The project is simple - UserControl with bool property and TextBlock. 

UserControl.xaml
~~~ xml
<UserControl
    x:Class="xBindConverterIssue.UserControl1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:xBindConverterIssue"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <Grid.Resources>
            <local:BoolToVisibilityConverter x:Key="BoolToVisibilityConverter"/>
        </Grid.Resources>
        <TextBlock Text="Visible Text"  
                   Visibility="{x:Bind Path=ShowTextBlock, Mode=OneWay, Converter={StaticResource BoolToVisibilityConverter}}"/>
    </Grid>
</UserControl>
~~~

MainWindow.xaml
~~~ xaml
<Window
    x:Class="xBindConverterIssue.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:xBindConverterIssue"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <local:UserControl1 ShowTextBlock="True"/>
    </StackPanel>
</Window>
~~~
**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
[StackTrace.txt](https://github.com/microsoft/microsoft-ui-xaml/files/5402227/StackTrace.txt)

**Comment by BorzillaR** [comment]
Reproduced in Preview 3

Updated project:

[xBindConverterIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5566885/xBindConverterIssue.zip)

**Comment by JeanRoca** [comment]
This is a known issue with x:Bind. Converters only work if the resources are in the app or the root of the XAML file, but for your scenario BoolToVisibilityConverter is not needed so just: 
```XML
 <Grid>
        <TextBlock Text="Visible Text"  
                   Visibility="{x:Bind Path=ShowTextBlock, Mode=OneWay}"/>
  </Grid> 
````
would work. If you run into this issue again the way to fix it would be to move BoolToVisibilityConverter like so:
```XML
<UserControl
    x:Class="xBindConverterIssue.UserControl1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:xBindConverterIssue"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
        <UserControl.Resources>
            <local:BoolToVisibilityConverter x:Key="BoolToVisibilityConverter"/>
        </UserControl.Resources>

    <Grid>
        <TextBlock Text="Visible Text"  
                   Visibility="{x:Bind Path=ShowTextBlock, Mode=OneWay, Converter={StaticResource BoolToVisibilityConverter}}"/>
    </Grid>
</UserControl>


```

**Comment by alexdi220** [comment]
@JeanRoca Thank you for the answer. Your approach with implicit conversion boot to visibility is good and I'll try a workaround.
