### ISSUE TITLE
In Media -> Person Picture, changing radio button from Person Picture to something else, then back, causes crash

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/microsoft-ui-xaml#3443]
Found while validating C#/WinRT release:

Source:
x86chk internal build from winui3

Repro:
Load the Motion | Person Picture page
Change the radio button to Display Name
Change the radio button back to Profile Image
App crashes with unhandled exception in DXamlCore::FireEvent

Call stack excerpt:
>	XamlControlsGallery.Desktop.dll!AppUIBasics.App.InitializeComponent.AnonymousMethod__21_1(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e) Line 62	C#
 	[Lightweight Function]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.UnhandledExceptionEventHandler.Do_Abi_Invoke.AnonymousMethod__0(Microsoft.UI.Xaml.UnhandledExceptionEventHandler invoke) Line 51449	C#
 	WinRT.Runtime.dll!WinRT.ComWrappersSupport.MarshalDelegateInvoke<Microsoft.UI.Xaml.UnhandledExceptionEventHandler>(System.IntPtr thisPtr, System.Action<Microsoft.UI.Xaml.UnhandledExceptionEventHandler> invoke)	Unknown
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.UnhandledExceptionEventHandler.Do_Abi_Invoke(System.IntPtr thisPtr, System.IntPtr sender, System.IntPtr e) Line 51447	C#
 	[Native to Managed Transition]	
 	microsoft.ui.xaml.dll!DirectUI::CFTMEventSource<ABI::Microsoft::UI::Xaml::IUnhandledExceptionEventHandler,ABI::Microsoft::UI::Xaml::IApplication,ABI::Microsoft::UI::Xaml::IUnhandledExceptionEventArgs>::Raise(ABI::Microsoft::UI::Xaml::IApplication * pSource, ABI::Microsoft::UI::Xaml::IUnhandledExceptionEventArgs * pArgs) Line 318	C++
 	microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::RaiseUnhandledExceptionEvent(HRESULT hrToReport, HSTRING__ * hstrMessage, unsigned int * pfHandled) Line 849	C++
 	microsoft.ui.xaml.dll!DirectUI::ErrorHelper::RaiseUnhandledExceptionEvent(HRESULT hrToReport, const xstring_ptr & strMessage, unsigned int * pfHandled) Line 287	C++
 	microsoft.ui.xaml.dll!DirectUI::ErrorHelper::ProcessUnhandledError(DirectUI::ErrorInfo & errorInfo, unsigned int fSkipFailFastIfNoErrorContext, unsigned int * pfHandled) Line 550	C++
 	microsoft.ui.xaml.dll!DirectUI::ErrorHelper::ReportUnhandledError(HRESULT hrError) Line 486	C++
 	microsoft.ui.xaml.dll!DirectUI::DXamlCore::FireEvent(CDependencyObject * pCoreListener, KnownEventIndex eventId, CDependencyObject * pCoreSender, CEventArgs * pCoreArgs, unsigned int flags) Line 1965	C++
 	microsoft.ui.xaml.dll!AgCoreCallbacks::FireEvent(CDependencyObject * pListener, KnownEventIndex eventId, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 85	C++
 	microsoft.ui.xaml.dll!CFxCallbacks::JoltHelper_FireEvent(CDependencyObject * pListener, KnownEventIndex eventId, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 906	C++
 	microsoft.ui.xaml.dll!CCoreServices::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 3079	C++
 	microsoft.ui.xaml.dll!CommonBrowserHost::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 686	C++
 	microsoft.ui.xaml.dll!CControlBase::ScriptCallback(void * pControl, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pInternalHandler) Line 213	C++
 	microsoft.ui.xaml.dll!CXcpDispatcher::OnScriptCallback(CEventInfo * pEventInfo) Line 1108	C++
 	microsoft.ui.xaml.dll!CXcpDispatcher::OnWindowMessage(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam) Line 879	C++
 	microsoft.ui.xaml.dll!CXcpDispatcher::ProcessMessage(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam, long * plRet, unsigned int * pbDoDefault) Line 715	C++
 	microsoft.ui.xaml.dll!CXcpDispatcher::WindowProc(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam) Line 652	C++

**Comment by codendone** [comment]
This works in Preview 3.
