### ISSUE TITLE
Bug: TabView shadow does not update receivers when dropped on TabView

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3453]
**Describe the bug**

When dragging and dropping TabView items, the shadow does not update their receiver list leaving the TabViewItem with no shadow when moving to a different TabView.

**Steps to reproduce the bug**

0. Override TabViewItemHeaderBackgroundSelected resource to Transparent to have shadow be easily visible
1. Have two TabViews
2. Drop a TabViewItem from TabView onto the other TabView
3. Observe shadow is missing.

**Expected behavior**

Shadow moves over to new TabView and accompanies the TabViewItem everywhere it goes on it's journey through XAML land.
**Screenshots**

![Gif showing missing shadow on TabViewItem](https://user-images.githubusercontent.com/16122379/96630410-4783e800-1315-11eb-9fa8-329fcfb1a0ad.gif)

**Version Info**

NuGet package version: 

Latest commit as of writing this: beb29d6

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20236)              | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

I can work on this, if that's fine.

**Comment by ranjeshj** [comment]
@adambarlow and @chigy as FYI.

**Comment by chingucoding** [comment]
Note that this is not caused by ThemeShadows but rather TabView. The only scenario where the receivers for the TabView are being set is in ApplyTemplate. After that, the receivers are not being updated so moving to a different TabView leaves the TabViewItem with no shadow as the new TabView hasn't been added to the list of receivers.
