### ISSUE TITLE
Dropping element on ListViewItem leaves drop target in bad VSM state

### ISSUE THREAD

**Issue by marcelwgn** [microsoft/microsoft-ui-xaml#3458]
**Describe the bug**

When dropping an element on a ListViewItem, the ListViewItem gets stuck in a bad state where it thinks that the pointer is still above it.

[ListViewDragBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5416939/ListViewDragBug.zip)

**Steps to reproduce the bug**

Run the attached app and drag one ListViewItem onto another one.

**Expected behavior**

ListViewItem should respond accordingly and not act like the pointer is still above it.

**Screenshots**

![Gif showing dragging and dropping a ListViewItem and the resulting faulty behavior.](https://user-images.githubusercontent.com/16122379/96740410-1d87ff80-13c1-11eb-83de-9e7b6a4758db.gif)

**Version Info**

NuGet package version: 

WinUI 2.4.3

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20236)              | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by benstevens48** [comment]
This might be related to this fundamental issue that I created a while ago - https://github.com/microsoft/microsoft-ui-xaml/issues/1959. (Note the title was changed to add the 'When pointer captured' bit, but I think there might other circumstances where entered/exited are not properly fired in pairs, e.g. during drag and drop).

**Comment by chingucoding** [comment]
Yes, I noticed that PointerEntered/PointerExited are not being raised when the cursor drags something over the item. Though, in contrast, DragEnter and DragLeave seem to work correctly and could be used when implementing your own control pointer over behavior.

**Comment by benstevens48** [comment]
PointerEntered/PointerExited need to be guaranteed to fire in a pair in all circumstances in order to void bugs like this. I suppose they should even fire when dragging, otherwise you can have DragEnter then drop, then PointerExited, which would violate the pair rule. Alternatively, rather than being guaranteed as a pair, it should at least be guaranteed that PointerExited always fires if PointerEntered has fired, because otherwise things end up getting stuck in the temporary mouse over state. The behavior should also be clearly documented.
