### ISSUE TITLE
NavigationView appears blurry temporarily at 125% scaling for WPF XAML Islands

### ISSUE THREAD

**Issue by arjunbalgovind** [microsoft/microsoft-ui-xaml#3459]
**Describe the bug**

If the system is set to 125% scaling a NavigationView initially appears blurry and after a short duration (less than a second) renders normally for WPF Xaml Island projects. The bug can be reproduced on PowerToys.  https://github.com/microsoft/PowerToys/issues/6592 is the tracking issue on our repo.

**Steps to reproduce the bug**

WPF Xaml Islands project with NavigationView of the form:
```
        <winui:NavigationView
        x:Name="navigationView"
        IsBackButtonVisible="Collapsed"
        IsBackEnabled="{x:Bind ViewModel.IsBackEnabled, Mode=OneWay}"
        SelectedItem="{x:Bind ViewModel.Selected, Mode=OneWay}"
        IsSettingsVisible="False"
        OpenPaneLength="296"
        CompactModeThresholdWidth="0"
        Background="{ThemeResource SystemControlBackgroundAltHighBrush}">
```
1. Launch the UI (For PowerToys, start PowerToys and click PowerToys from the sys tray to launch the Settings app (WPF Xaml Island with NavView)

**Expected behavior**

`NavigationView` should render normally.

**Screenshots**

On launch:
![image](https://user-images.githubusercontent.com/32061677/96759521-06c7b580-138d-11eb-9070-af1d8e06fed0.png)
After a short duration:
![image](https://user-images.githubusercontent.com/32061677/96759586-1c3cdf80-138d-11eb-86e8-869522a2a953.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.5.0-prerelease.200923002

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |
Xaml Island on WPF

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Source for the page with NavigationView https://github.com/microsoft/PowerToys/blob/master/src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml

**Comment by crutkas** [comment]
any updates here?

**Comment by Jay-o-Way** [comment]
Is this still an issue?

**Comment by ranjeshj** [comment]
We're not planning on taking a fix for this on WinUI2. Closing this bug. Note that there is an issue tracking blurry text in WinUI3 here - https://github.com/microsoft/microsoft-ui-xaml/issues/2278 

If you have a similar repro in WinUI3, please reactivate.
