### ISSUE TITLE
TreeView: DragItemsCount is not updated when removing selected items

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3460]
**Describe the bug**
When dragging selected items in the TreeView, a drag item count is being displayed to indicate how many items are included in the drag operation. This variable is not being updated when removing selected items:

![treeview-DragItemsCount-issue](https://user-images.githubusercontent.com/1398851/96759696-b1b19100-13d8-11eb-8c5f-52927f53a60a.gif)

While the initial drag count of "2" is correct, the subsequently displayed drag count of "3" is not as the previously selected items have been removed and only one item is currently selected. The count should be "1"  internally and no drag item count should be displayed (we only display it when more than one item is selected).

**Version Info**

NuGet package version: 
2.5.0-prerelease.200923002
2.4.0 (and earlier)

**Additional context**
I would like to take a look at this.

**Comment by StephenLPeters** [comment]
I assume this is caused by us only changing the number in the selected items changed event, not in the collection changed events as well. Please go ahead and take a look :)
