### ISSUE TITLE
[Localization]Warning did not translated when created an UWP Application without enable Developer mode

### ISSUE THREAD

**Issue by SvetBonev** [microsoft/microsoft-ui-xaml#3463]
[Environment]

OS: Windows-10-Enterprise-19H1-VSDrop-ja-jp

VS: 16.8 Preview 5(d16.8/30615.102) 

Repro steps:

1. Create a UWP Application

2. Don't enable Developer mode

[Expected]

Warning should be translated 

[Actual]

Warning did not translated
![attachments](https://user-images.githubusercontent.com/46607019/96798335-8a959800-13b5-11eb-8eb4-7c094f21d35f.png)

**Comment by SvetBonev** [comment]
The warning comes from Microsoft.Windows.UI.Xaml.Build.Tasks.dll in the Windows 10 SDK.

**Comment by StephenLPeters** [comment]
Warnings and errors are always presented in English, this is by design for errors in Winui to reduce our package size. I'm not positive about this specific error but it is a pretty common pattern to not locallize these, just like we don't localize our API names.

**Comment by SvetBonev** [comment]
There are certain expectations from Microsoft products to comply with Accessibility, World Ready, and other requirements. Package size concerns shouldn't trump those.

**Comment by maxkatz6** [comment]
@SvetBonev there is another issue for that https://github.com/microsoft/microsoft-ui-xaml/issues/2299
As for me, it is controversial topic. A lot of developers do not prefer localized exception messages.

**Comment by SvetBonev** [comment]
@maxkatz6 Thank you for the pointer to the other issue.

Because this is an error message issued by MSBuild which is part of Visual Studio, the error message needs to follow the Visual Studio localization rules. 
It is a matter of providing consistent experience within the Visual Studio product as well as ensuring regulatory compliance with the laws of different countries and regions.

**Comment by StephenLPeters** [comment]
@jevansaks FYI.
