### ISSUE TITLE
Can't work with C# WinUI in Desktop projects.

### ISSUE THREAD

**Issue by mitran79** [microsoft/microsoft-ui-xaml#3471]
**Describe the bug**

Can't create new Blank App(WinUi in UWP) in either C# or C++.
Unable to sucessfully open WinUi-3-Demo DemoBuildCs.
Dialog reports:
The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation(",10,0.18362.0)" cannot be evaluated. Parameter "targetPlatformIdentifier" cannot have zero length.

**Steps to reproduce the bug**

- Make fresh install of Visual Studio 2019 and 2019 Preview.
- Install WinUI.ProjectTemplates.vsix.
- Start Visual Studio 2019 Preview.
- Select C# WinUi in Desktop project.

- Download WinUi-3-Demo
- Open DemoBuildCs.

**Expected behavior**

File Opens normally without errors.

**Screenshots**

[
<img width="770" alt="Bug" src="https://user-images.githubusercontent.com/36862623/96943068-ac605d80-1522-11eb-886f-599dd1926aa2.PNG">
](url)
**Version Info**

NuGet package version: 

Unknown, can't seem to get that far.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| NO | YES |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | YES  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ad1Dima** [comment]
Did you install Universal Windows Platform Development?
![image](https://user-images.githubusercontent.com/3244664/96962200-82ae3300-1530-11eb-85cc-05810f81d66a.png)

**Comment by mitran79** [comment]
Yes, I sure did. With a whole lot of other stuff too.
<img width="655" alt="Capture" src="https://user-images.githubusercontent.com/36862623/97022879-68ac3900-15a0-11eb-9674-62cb96582f4f.PNG">

**Comment by StephenLPeters** [comment]
This is caused by Visual studio version 16.8, it is incompatible with Winui3 preview 2. The solution is to either use VS16.7 (the non preview version) or wait for Winui3 preview 3 which will support it and be here soon _TM_
