### ISSUE TITLE
TeachingTip: Closed TeachingTips appear in tab order

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#3473]
**Describe the bug**

TeachingTips declared in XAML do not have IsTabStop set to False by default. The result is they appear as ghost tabs in the tab order.

**Steps to reproduce the bug**

1. Add a TeachingTip to XAML, with IsOpen=False
2. Tab through the controls. TeachingTip appears in the tab order.

**Expected behavior**
TeachingTip shouldn't appear in the tab order. Workaround is to set IsTabStop=False on every TeachingTip that isn't part of a control's Resources.

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.4.3]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19042)              | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
This is because of teaching tips weird behavior of reparenting its children and placing them in a popup. The teaching tip itself remains in the tree but has not children and therefore doesn't render. To fix this we need to make sure that the teaching tip itself is not a tab stop while maintaining its children's tab stop settings.

**Comment by Felix-Dev** [comment]
@StephenLPeters Seeing as there is no "help-wanted" tag, are you taking a look at this? Otherwise, I wouldn't mind fixing this.
