### ISSUE TITLE
Can we remove " Tests" from test inventory button UIA names?

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3475]
The test inventory automatically appends " Tests" to the top level page buttons:

https://github.com/microsoft/microsoft-ui-xaml/blob/560b07508af2d8e49a1b36b7607ebcb3c1b6ea74/test/TestAppUtils/TestDeclaration.cs#L23

This is not documented though and can be really confusing to people new to the project as the test helper references "NavigationView Tests", though when opening the app, there is no button with the text "NavigationView Tests".

**Comment by StephenLPeters** [comment]
Seems fine to me.

**Comment by chingucoding** [comment]
Is this something that should wait until WinUI 3 to be merged in this repo to prevent merge conflicts?
