### ISSUE TITLE
Impossible to pick any color other than black after setting ColorPicker to black

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#3476]
This issue was originally found over in https://github.com/microsoft/terminal/issues/7948. I'm moving relevant details to the WinUI repo for more discussion on this behavior, despite us working around this in the Terminal.

The Terminal is using MUX 2.5.0-prerelease.200609001.

## TL;DR

If you use the ColorPicker with `IsColorSliderVisible=False` then set the color of the picker to Black (`#000000`), then it becomes impossible to change the color using the ColorPicker. This might be by-design, but I want to make sure this is documented if it is. 

### Original Post:
> # Environment
> 
> ```none
> Windows build number: Win32NT, 10.0.18362.0 Microsoft Windows NT 10.0.18362.0
> Windows Terminal version (if applicable): 1.3.2651.0
> ```
> 
> # Steps to reproduce
> 
> 1. Right click on tab and select _Color..._
> 1. Click _Custom_
> 1. Click _More_
> 1. Remove value from hex code field, tab background is set to black
> 1. Try to pick any color from color picker
> 
> # Expected behavior
> 
> User should be able to pick new color from color picker.
> 
> # Actual behavior
> 
> Tab color is black and can't be change by picking color from color picker, it can be only change by selecting one from predefined list or by setting any other color hex code other than black
> ![image](https://user-images.githubusercontent.com/13621655/96272672-b76d3800-0fce-11eb-9e16-d6197b2b27b0.png)
> 

### https://github.com/microsoft/terminal/issues/7948#issuecomment-711007751
> 
> ## This is what I think is the reason why this is not working
> 
> ![Look at this](https://user-images.githubusercontent.com/67918878/96326340-694b4980-104d-11eb-9a25-aa3aeb38e121.png)
> 
> Look at the slider. It is set to black. So if you change the color using that rainbow like thing, that slider is still at black.
> You have to move the slider in order for it to work (and I have confirmed it).
> 
> This also explains why the color changes successfully when you choose a preset color or you give another hex value.
> 
> The funny thing is that Windows Terminal does not have this slider
> 
> This is probably because
> 
> The one with the slider:
> 
> ![image](https://user-images.githubusercontent.com/67918878/96339185-9d0b8b00-10b0-11eb-9c6c-a4b1ed85b6ff.png)
> 
> The one that Windows Terminal be likely be using:
> 
> ![image](https://user-images.githubusercontent.com/67918878/96339213-d9d78200-10b0-11eb-8cb1-c598d98ecad5.png)

### https://github.com/microsoft/terminal/issues/7948#issuecomment-711865063
> 
> 
> GIFing this problem:
> 
> (Sorry for my extremely bad GIFs. Especially the ColorPicker control 🤢)
> 
> The problem:
> 
> ![The problem](https://user-images.githubusercontent.com/67918878/96421881-f55b9d80-1214-11eb-8f04-c81482947d64.gif)
> 
> Demonstrating the problem and a possible fix in XAML Studio:
> 
> ![potential-fix](https://user-images.githubusercontent.com/67918878/96422065-2dfb7700-1215-11eb-8da1-fae215383f17.gif)
> 
> I think we can fix this by enabling Color Slider in the ColorPicker control.
> 
> I would like to make a PR on this if you agree on this fix (only if this fix is going to be as easy as I did in XAML Studio)

**Comment by StephenLPeters** [comment]
I think this is by design, the color spectrum area lets you set the saturation and hue while the slider lets you set the color value.  If you set the value to 0 (which is what choosing black color does) than any hue and saturation combination is also going to be black.  Since there is no way to change the value with the spectrum and you've hidden the value slider then yes there is no way to change the value.
