### ISSUE TITLE
Update acrylic theme resources

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#3478]
# Proposal: Update acrylic theme resources

## Summary

Update some existing AcrylicBrush theme resources, add a few more, and update controls to reference correct resources.

## Proposed changes

1. Update SystemControlTransientBackgroundBrush
To take advantage of the (not so new) `TintLuminosityOpacity` property, update the existing `SystemControlTransientBackgroundBrush` to use new values.
 

  | TintColor | TintOpacity | TintLuminosityOpacity | FallbackColor | BackgroundSource
-- | -- | -- | -- | -- | --
Light theme | #FCFCFC | 0.0 | 0.85 | #FCFCFC | HostBackdrop
Dark theme | #2C2C2C | 0.15 | 0.96 | #2C2C2C | HostBackdrop

2. Add new theme resources
2.1 Create `SystemControlTransientAcrylicElementBrush` using the following properties (all values are the same as above with the exception of `BackgroundSource`).

  | TintColor | TintOpacity | TintLuminosityOpacity | FallbackColor | BackgroundSource
-- | -- | -- | -- | -- | --
Light theme | #FCFCFC | 0.0 | 0.85 | #FCFCFC | Backdrop
Dark theme | #2C2C2C | 0.15 | 0.96 | #2C2C2C | Backdrop

   2.1.1 Update `NavigationViewDefaultPaneBackground`, `DefaultCommandBarFlyoutCommandBarStyle.Background`, `NavigationViewTopPaneBackground` to all use the new SystemControlTransientAcrylicElementBrush instead of their current acrylic resources.

2.2 Create `SystemControlTransientBackgroundInverseBrush` using the following properties (same as above but reversed per theme).

  | TintColor | TintOpacity | TintLuminosityOpacity | FallbackColor | BackgroundSource
-- | -- | -- | -- | -- | --
Light theme | #2C2C2C | 0.15 | 0.96 | #2C2C2C | HostBackdrop
Dark theme | #FCFCFC | 0.0 | 0.85 | #FCFCFC | HostBackdrop

2.3 Create `SystemControlBaseAcrylicBrush` 

  | TintColor | TintOpacity | TintLuminosityOpacity | FallbackColor | BackgroundSource
-- | -- | -- | -- | -- | --
Light theme | #F3F3F3 | 0.0 | 0.9 | #F3F3F3 | HostBackdrop
Dark theme | #202020 | 0.0 | 0.96 | #202020 | HostBackdrop

2.4 Create a new SolidColorBrush named `SystemControlDefaultBrighteningBrush`

  | Fill color | Opacity
-- | -- | --
Light theme | #FFFFFF | 0.5
Dark theme | #FFFFFF | 0.0419

## Down-level behavior
The updated values described above rely on the TintLuminocityOpacity property, which was added in 19H1. Therefore, we will need to introduce a new AcrylicBrush_19h1_themeresources.xaml (or similar name) with new resources. We'll also need to add new resources into the existing AcrylicBrush_rs2_themeresources.xaml and AcrylicBrush_rs1_themeresources.xaml files. For the RS2 dictionary, we'll need to provide alternative values for these AcrylicBrush resources.

Proposed RS2 alternative values:
```xaml
<!-- Light theme -->
        <muxm:AcrylicBrush x:Key="SystemControlTransientBackgroundBrush" TintColor="#FCFCFC" TintOpacity="0.8" FallbackColor="#FCFCFC" BackgroundSource="HostBackdrop"/>
        <muxm:AcrylicBrush x:Key="SystemControlBaseAcrylicBrush" TintColor="#F3F3F3" TintOpacity="0.8" FallbackColor="#F3F3F3" BackgroundSource="HostBackdrop"/>

<!-- Dark theme -->
        <muxm:AcrylicBrush x:Key="SystemControlTransientBackgroundBrush" TintColor="#1C1C1C" TintOpacity="0.8" FallbackColor="#2C2C2C" BackgroundSource="HostBackdrop" />
        <muxm:AcrylicBrush x:Key="SystemControlBaseAcrylicBrush" TintColor="#1C1C1C" TintOpacity="0.8" FallbackColor="#202020" BackgroundSource="HostBackdrop" />
```

**Comment by mdtauk** [comment]
Is this just a refresh for consistency sake, or is there a change/tweak to the direction from a high level design pov?

Are these changes also taking into account the temporary loss of the HostBackdrop Acrylic for WinUI 3.0?

**Comment by chingucoding** [comment]
If this is good to work on, I would gladly work on this. Regarding the RS2 resources, the simplest way would be to leave out the tint-luminosity-opacity for those brushes, not sure if that is the best solution. Maybe @chigy has an idea?

**Comment by shaheedmalik** [comment]
> Is this just a refresh for consistency sake, or is there a change/tweak to the direction from a high level design pov?
> 
> Are these changes also taking into account the temporary loss of the HostBackdrop Acrylic for WinUI 3.0?

I think you need to make a proposal for this one.

**Comment by chigy** [comment]
@chingucoding , is it possible to prototype the fallback without the tint-luminosity-opacity as you suggest?

**Comment by chingucoding** [comment]
I can create the brushes without said property and show how they compare to the brushes with tint-luminosity-opacity specified. However, I'm not quite sure if they will render exactly the same on RS2 compared to later versions where that property exists but is not specified.

**Comment by chigy** [comment]
> I can create the brushes without said property and show how they compare to the brushes with tint-luminosity-opacity specified. However, I'm not quite sure if they will render exactly the same on RS2 compared to later versions where that property exists but is not specified.

@YuliKl , @kikisaints , I would think the visual should not be different between property existing but not set, vs. property not existing?

**Comment by chingucoding** [comment]
From left to right in every row, we have:
- the light theme version
- the light theme version without TintLuminosityOpacity
- the dark theme version
- the dark theme version without TintLuminosityOpacity

![gif](https://user-images.githubusercontent.com/16122379/97201529-daf46780-17b2-11eb-9eaf-faad42421e60.gif)

Interestingly, the dark theme versions differ quite a lot when leaving out the tint luminosity opacity property.

**Comment by YuliKl** [comment]
@chingucoding I have basically the same prototype and feel that just leaving out TintLuminosityOpacity is not acceptable (primarily for dark theme). Will try to propose replacement values shortly.

And yes, please add the new resources to the RS1 dictionary. They should just be solid color brushes with the fallback color as their values.

**Comment by mdtauk** [comment]
Some of those fallback colours are near indistinguishable from the base White and Black colours.  Is that intended?

**Comment by YuliKl** [comment]
Updated the description with what I believe to be reasonable RS2 alternatives. They don't look as great as the new values but remain usable.

> Some of those fallback colours are near indistinguishable from the base White and Black colours. Is that intended?

@mdtauk, yes. Because acrylic ought to be used on transient surfaces, most users shouldn't see the fallback color at all. When acrylic is completely turned off on the user's system, the backgrounds they see should match the color of the base page background.

**Comment by mdtauk** [comment]
> > Some of those fallback colours are near indistinguishable from the base White and Black colours. Is that intended?
> 
> @mdtauk, yes. Because acrylic ought to be used on transient surfaces, most users shouldn't see the fallback color at all. When acrylic is completely turned off on the user's system, the backgrounds they see should match the color of the base page background.
>
How would this affect usability for things like the Numberbox pop over buttons, or context menus.  Unless of course the guidance stipulates borders and shadows should be used on these transient surfaces. (and even then the user can turn shadows off, which will also hamper visibility)

**Comment by chingucoding** [comment]
> Updated the description with what I believe to be reasonable RS2 alternatives. They don't look as great as the new values but remain usable.

Awesome! Since there don't seem to be any open questions on this proposal, I'll start working on this.

**Comment by YuliKl** [comment]
> How would this affect usability for things like the Numberbox pop over buttons, or context menus. Unless of course the guidance stipulates borders and shadows should be used on these transient surfaces.

Yes, borders feel like the right answer.

**Comment by mdtauk** [comment]
> > How would this affect usability for things like the Numberbox pop over buttons, or context menus. Unless of course the guidance stipulates borders and shadows should be used on these transient surfaces.
> 
> Yes, borders feel like the right answer.
>
What values would be used for the borders, and will they be documented.  It would be good to find a consistent set of values, for all controls to use - if you are in the process of updating style resources.

**Comment by YuliKl** [comment]
> What values would be used for the borders, and will they be documented. It would be good to find a consistent set of values, for all controls to use - if you are in the process of updating style resources.

[SystemControlTransientBorderBrush](https://github.com/microsoft/microsoft-ui-xaml/blob/d883cf3593912ded1a1fcc73f38768fda8ee3a45/dev/Materials/Acrylic/AcrylicBrush_rs2_themeresources.xaml#L435)

**Comment by mdtauk** [comment]
> > What values would be used for the borders, and will they be documented. It would be good to find a consistent set of values, for all controls to use - if you are in the process of updating style resources.
> 
> [SystemControlTransientBorderBrush](https://github.com/microsoft/microsoft-ui-xaml/blob/d883cf3593912ded1a1fcc73f38768fda8ee3a45/dev/Materials/Acrylic/AcrylicBrush_rs2_themeresources.xaml#L435)

I think there may be a mistake with the Dark Theme value
``<SolidColorBrush x:Key="SystemControlTransientBorderBrush" Color="#000000" Opacity="0.36" />``

Shouldn't that be **Color="#FFFFFF" Opacity="0.36"**

I think I brought this same point up when the Numberbox Flyout buttons were changed #3127

**Comment by chingucoding** [comment]
I think you are right, but @YuliKl or @chigy probably know more on this.

**Comment by Felix-Dev** [comment]
Note that I tried to update that brush locally for me back then as I also view this as a mistake but it didn't work. See my [Note] remark.

**Comment by mdtauk** [comment]
> Note that I tried to update that brush locally for me back then as I also view this as a mistake but it didn't work. See my [Note] remark.

I know you worked on the Numberbox Flyout buttons, to try to stop them "disappearing" into the backgrounds

**Comment by mdtauk** [comment]
>2.1.1 Update NavigationViewDefaultPaneBackground, DefaultCommandBarFlyoutCommandBarStyle.Background, NavigationViewTopPaneBackground to all use the new SystemControlTransientAcrylicElementBrush instead of their current acrylic resources.
>
I am hoping this is a temporary change until WinUI 3.X gets support for HostBackdrop Acrylic or some form of Fauxcrylic as has been discussed and was said to be under consideration during numerous WinUI Community Calls?

#3401 #2236
