### ISSUE TITLE
Question: Controls with AccessibilityView=Content return null as AutomationPeer

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3480]
I noticed that a few controls such as StackPanel or Grid have AccessibilityView set to `Content`, however those elements return null when calling `FrameworkElementAutomationPeer.CreatePeerForElement`. According to [the documentation on the control-view tree](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-treeoverview#content-view), such controls should specify `IsControlElement=true` and `CurrentIsContentelement=true`. The latter doesn't seem to exist on the FrameworkElementAutomationPeer, the first one does though. But if the peer is null for those controls, how are they able to report true for `IsControlElement`? Is this behavior by design or is this a possible bug?

**Comment by ranjeshj** [comment]
@MikeHillberg do you know ?
