### ISSUE TITLE
XAML Islands: Broken rendering after closing a window

### ISSUE THREAD

**Issue by sylveon** [microsoft/microsoft-ui-xaml#3482]
**Describe the bug**
If multiple XAML islands windows are hosted on the same thread, closing one of those windows can lead to the rendering on other windows (both existing and any newly created) to stop working correctly.

**Steps to reproduce the bug**
1. Create a new blank WPF .NET Framework app.
2. Add the `Microsoft.Toolkit.Wpf.UI.XamlHost` NuGet package.
3. Add a project reference to the UniversalApiContract winmd from the Windows SDK.
4. Add an app manifest to the app, and within `<compatibility>` add `<maxversiontested Id="10.0.19041.0" />`
5. In MainWindow.xaml, write the following
   ```xaml
   <Window x:Class="WpfApp2.MainWindow"
           xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
           xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
           xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
           xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
           xmlns:local="clr-namespace:WpfApp2" xmlns:xamlhost="clr-namespace:Microsoft.Toolkit.Wpf.UI.XamlHost;assembly=Microsoft.Toolkit.Wpf.UI.XamlHost"
           mc:Ignorable="d"
           Title="MainWindow" Height="450" Width="800">
       <Grid>
           <xamlhost:WindowsXamlHost x:Name="host" />
       </Grid>
   </Window>
   ```
6. In MainWindow.xaml.cs, write this code in the class
   ```cs
   private static bool createdSecondWindow = false;

   public MainWindow()
   {
       InitializeComponent();

       var grid = new Windows.UI.Xaml.Controls.Grid
       {
           Background = new AcrylicBrush
           {
               BackgroundSource = AcrylicBackgroundSource.HostBackdrop,
               TintOpacity = 0
           }
       };

       grid.HorizontalAlignment = Windows.UI.Xaml.HorizontalAlignment.Stretch;
       grid.VerticalAlignment = Windows.UI.Xaml.VerticalAlignment.Stretch;

       var button = new Windows.UI.Xaml.Controls.Button
       {
           Content = "Click me!",
       };

       button.Click += (s, e) =>
       {
           // native code crash if the close is not dispatched.
           Dispatcher.InvokeAsync(Close);
       };

       grid.Children.Add(button);
       host.Child = grid;

       if (!createdSecondWindow)
       {
           createdSecondWindow = true;
           new MainWindow().Show();
       }
   }
   ```
7. Launch the app.
8. Once the two windows show up, one should be active but not have acrylic effect.
9. Click on an empty region of the taskbar.
10. Click on the black region of one of the two windows. Acrylic should be active.
11. Click on the black region of the other window. Acrylic should be active on the window you left focus from but not the one that just got it.
12. Click the button in the active window.
13. Notice that resizing the other window doesn't work anymore, and hover effects for the button do not display anymore.

**Expected behavior**
The rendering doesn't stop from working.

**Screenshots**
I've uploaded a video to better illustrate the problem: https://www.youtube.com/watch?v=dC0Z-zFjoHY

**Version Info**
NuGet package version: 
[Microsoft.Toolkit.Wpf.UI.XamlHost 6.1.2]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This also happens in my C++-based XAML islands app, so this is not an issue specific to the WCT WPF host, it just makes reproduction easier.

**Comment by ranjeshj** [comment]
@marb2000 as FYI

**Comment by sylveon** [comment]
Haven't seen this issue since then.
