### ISSUE TITLE
The Path with specific data has rendering artifacts

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3487]
**Describe the bug**
Hi, 
I use the Path figure (see attached XAML) and it renders different from WPF. The WinUI's Path has an additional vertical line (see screen1). WPF not (screen 2). It looks like a bug.

**Steps to reproduce the bug**
XAML to reproduce:
~~~ xaml
    <Grid UseLayoutRounding="True">
        <Path Data="M14,2H12V1H11V2H5V1H4V2H2V14H14ZM4,3V4H5V3h6V4h1V3h1V5H3V3Zm9,10H3V6H13ZM7,10V7H4v3ZM5,8H6V9H5Z" 
                              Width="16" Height="16" Fill="#FF666666"
                              HorizontalAlignment="Center" VerticalAlignment="Center"/>
    </Grid>
~~~

**Expected behavior**
Should works like WPF

**Screenshots**
![image](https://user-images.githubusercontent.com/47348109/97143964-b083b980-1774-11eb-8df7-bd95afbae7b4.png)
![image](https://user-images.githubusercontent.com/47348109/97144035-d01ae200-1774-11eb-8848-af6f874a980b.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by BorzillaR** [comment]
The issue is reproduced in Preview3 too.

**Comment by codendone** [comment]
Looks like a bug. The OS version of XAML has the same issue, so this looks like an old bug.
