### ISSUE TITLE
Cannot Submit Xaml Island App to Microsoft Store

### ISSUE THREAD

**Issue by jindal1979** [microsoft/microsoft-ui-xaml#3488]
I am trying to submit an App built using XAML ISLAND based WPF .Net Core 3.1 App. However, the package is failing with:

WAP_3.20.1.0_x64_bundle.msixupload121.2 MB
Package acceptance validation error: You cannot submit pre-compiled .NET Native packages. Please upload the Microsoft Store appxupload file and try again

I have built the sample Xaml Island Apps from this github also, however they all fail with same error. Please help me.

**Comment by stevenbrix** [comment]
@marb2000 and @ocalvo, is this a known issue with mixing WPF and UWP?

**Comment by michalleptuch** [comment]
@jindal1979 Did you fix it? I have got the same issue.

**Comment by jindal1979** [comment]
@michalleptuch, yes I resolved it by adding the reference xaml island project into the installer project.

**Comment by atiyka** [comment]
@jindal1979 I got the same issue, thanks for sharing! It was working to me as well

**Comment by pratikone** [comment]
closing as others reported a way  to do it
