### ISSUE TITLE
FindElement.Refresh stuck in infinite loop when setting a child's events source to the parent's

### ISSUE THREAD

**Issue by ejserna** [microsoft/microsoft-ui-xaml#3491]
**Describe the bug**
If you set a control's events source to a parent's, the ````foreach```` loop in ````FindElement.Refresh()```` will get stuck in an infinite loop.

**Steps to reproduce the bug**
Try this code:
**XAML**:
````
<local:TestControl x:Name="CustomControl" AutomationProperties.Name="CustomControl">
                    <Button x:Name="Button1" Content="Button"/>
 </local:TestControl>
````
**XAML.CS**
````
namespace MUXControlsTestApp
{
    public sealed class TestControl : ContentControl
    {
        protected override AutomationPeer OnCreateAutomationPeer()
        {
            return new TestControlAutomationPeer(this);
        }
    }

    public sealed class TestControlAutomationPeer : FrameworkElementAutomationPeer
    {
        public TestControlAutomationPeer(TestControl owner) : base(owner){}
        protected override AutomationControlType GetAutomationControlTypeCore()
        {
            return AutomationControlType.Custom;
        }
    }

    [TopLevelTestPage(Name = "Expander")]
    public sealed partial class ExpanderPage : TestPage
    {
        public ExpanderPage()
        {
            this.InitializeComponent();
            var customControlPeer = FrameworkElementAutomationPeer.FromElement(CustomControl);
            var buttonPeer= FrameworkElementAutomationPeer.FromElement(Button1);

            buttonPeer.EventsSource = customControlPeer;
        }
    }
}
````
**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@ejserna  Is this an issue with the test code in WinUI ?

**Comment by ejserna** [comment]
@ranjeshj yes, this is an issue in the test infrastructure, in ````FindElement.cs````.

**Comment by chingucoding** [comment]
I would like to look into this.

**Comment by chingucoding** [comment]
It seems that this is not an issue with the test infra, but rather the underlying framework/library that provides us with the `UIObject` objects. In the scenario described by @ejserna , the list of descendants seems to be infinite, at some point it keeps containing the same element over and over again. So the only efficient solution I can think of is save the previous element and break the for loop if the previous element is equal to the current item, does that sound reasonable as a workaround?

**Comment by ejserna** [comment]
@chingucoding I think that's a good workaround.
