### ISSUE TITLE
The control doesn't raise IsEnabledChanged

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3496]
**Describe the bug**
Hi,
I have an inheritor from the Control class (CustomControl) and the event IsEnabledChanged doesn't raise.

**Steps to reproduce the bug**
MainWindow.xaml
~~~xaml 
<Window
    x:Class="PropertyChangeIssue.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:PropertyChangeIssue"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <local:CustomControl IsEnabled="False">
            <local:CustomControl.Template>
                <ControlTemplate TargetType="local:CustomControl">
                    <Border Width="100" Height="100" Background="Red"/>
                </ControlTemplate>
            </local:CustomControl.Template>
        </local:CustomControl>
    </StackPanel>
</Window>
~~~
MainWindow.xaml.cs
~~~csharp
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using System.Diagnostics;

namespace PropertyChangeIssue {
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
        }
    }
    public class CustomControl : Control {
        public CustomControl() {
            Debug.WriteLine($"IsEnabled: {IsEnabled}");
            IsEnabledChanged += CustomControl_IsEnabledChanged;
        }
        private void CustomControl_IsEnabledChanged(object sender, DependencyPropertyChangedEventArgs e) {
            Debug.WriteLine($"IsEnabledChanged: {IsEnabled}"); // doesn't work
        }
    }
}

~~~
**Expected behavior**
The event should be raised

**Screenshots**

**Version Info**

[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes
 |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
[PropertyChangeIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5444425/PropertyChangeIssue.zip)

**Comment by BorzillaR** [comment]
This issue is reproduced in Preivew 3.

Updated project:

[PropertyChangeIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5567029/PropertyChangeIssue.zip)

**Comment by alexdi220** [comment]
Any updates? At now it a critical behavior and I can't manage the visual state of the control when it was disabled.

**Comment by MikeHillberg** [comment]
@alexdi220, I think the issue is that this event doesn't raise as it should when the property is set in markup like this. As a workaround for now you should be able to do initialization by listening to the Loaded event (but still hook up the IsEnabledChanged handler).

**Comment by mdtauk** [comment]
#3934 I made an issue about doing something about this in the Templated Control item template

**Comment by alexdi220** [comment]
Hi @MikeHillberg and @mdtauk. Thanks for the answers. The workaround is well and I have used it. But still waiting for a fix. There is the [issue](https://github.com/microsoft/microsoft-ui-xaml/issues/3557) found by my colleague. The subscription of the standard events causes performance issues. We facing cases 5 and 6 in huge components like DataGrid, ToolBars, Ribbon, etc, or enterprise applications with high-density UI and data forms. That's why these issues are critical and the [support "Disabled" state out of the box](https://github.com/microsoft/microsoft-ui-xaml/issues/3497) may be a good idea.
