### ISSUE TITLE
CommandBarFlyout.ShowMode is not available in earlier target platform minimum versions

### ISSUE THREAD

**Issue by DL444** [Microsoft/microsoft-ui-xaml#350]
**Describe the bug**
CommandBarFlyout.ShowMode property is not available in earlier target platform minimum versions

**Steps to reproduce the bug**
1. Create a UWP project targeting minimum versions earlier than 17763
2. Create a `CommandBarFlyout` element in XAML markup.
3. Try to set its `ShowMode` property in XAML.
4. Build the project.

**Expected behavior**
The project is built successfully and the behavior of CommandBarFlyout is accordingly changed.

**Actual behavior**
XAML editor indicates that ShowMode property is not available in the target platform minimum version, and the project will fail to build with error "The XAML Binary Format (XBF) generator reported syntax error '0x09C4' : Property Not Found"

**Screenshots**
Not applicable

**Version Info**
- Package version: 2.0.181018004
- Windows version: 17763.346
- Target Platform Version: 17763
- Minimum Platform Version: 16299
- Visual Studio version: 15.9.6

**NuGet package version**
Microsoft.UI.Xaml 2.0.181018004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |             Yes             |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |           Yes               |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Not applicable

**Comment by jevansaks** [comment]
You can use [Conditional XAML](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml) to make it so that you only use ShowMode on supported platforms. Unfortunately with the split between WinUI and the platform today we can't make all functionality available on downlevel Win10. In particular with CommandBarFlyout there is some Flyout functionality that was implemented in the platform.
