### ISSUE TITLE
Question: Can WinUI Use Processes and Files?

### ISSUE THREAD

**Issue by mysteryx93** [microsoft/microsoft-ui-xaml#3510]
I just read about WinUI. I was wondering whether it can replace WPF. The main issue with UWP is that it can't start processes, access the file system, access Win API, and is thus useless for many types of Windows applications.

Can WinUI start processes and access the file system, or does it have the same restrictions as UWP?

**Comment by chingucoding** [comment]
WinUI desktop projects are Win32 projects exactly like WPF and Winforms, so a WinUI 3 Desktop app can start processes and access all files. WinUI 3 UWP projects will still be limited to the features of the UWP container, e.g. not starting a process or only accessing certain files.

**Comment by StephenLPeters** [comment]
@chingucoding is correct. With winui3 you can use desktop apps to access this functionality.  UWP apps will still not be able to do these things.

**Comment by AtosNicoS** [comment]
Hey guys, coming later to the party, I am wondering how I can differenciate between a "win32 project" and an "uwp project". For version 1.0 of winui3 there is no such difference.

My goal is to access the filesystem without the UWP capabilities restrictions. Is there any way to do that, maybe even a sample?

**Comment by chingucoding** [comment]
If i recall correctly, only the experimental versions of the Win App SDK support creating UWP apps. If you create a WinUI 3 WASDK Version 1.0 app, it will be a win32 project. A good way to tell if it is win 32 or not is to look at the .NET version being used. Win32 WinUI 3 apps use .NET 5 and higher, the UWP apps are still on the UWP .NET SDK/.NET Native.
