### ISSUE TITLE
TeachingTip buttons do not expand when content is wider than 50% of the teaching tip width

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#3513]
**Describe the bug**

TeachingTip buttons do not expand when content is wider than 50% of the teaching tip width.

**Steps to reproduce the bug**

1. Add a teaching tip to a button
2. Set the ActionButtonContent to a long string

**Expected behavior**
Button should expand to hold the specified content. Workaround is to set the content to a text block that wraps.

**Screenshots**
![image](https://user-images.githubusercontent.com/45607479/97493363-16fa0a80-1922-11eb-991b-b2c1d837cf03.png)

Workaround (wrapping text block):
![image](https://user-images.githubusercontent.com/45607479/97493798-bae3b600-1922-11eb-8702-f1779df13e24.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.3

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19042)              | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
I think that this is by design. @SavoySchuler Can you confirm?  The design is that the close and action buttons take up 50% (minus some padding) of the width of the teaching tip. We should probably make the content wrap though.

**Comment by StephenLPeters** [comment]
@joshkoon are you asking for the button width to expand past the 50% mark or its height to expand to fit the content?

**Comment by joshkoon** [comment]
@StephenLPeters it seems like a bug that if there is only one button, it is still limited to 50% width. I also agree that the content should wrap by default. As it is today, it's easy to end up with clipped UI due to localization or text scaling.

**Comment by chingucoding** [comment]
I would like to look into this.
