### ISSUE TITLE
The PrimaryCommand of CommandBarFlyout closes faster than the SecondardCommand

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#3515]
**Describe the bug**
![GIF 2020-10-29 11-13-49](https://user-images.githubusercontent.com/42038175/97521280-35224200-19d8-11eb-9281-e747ef5b0cf8.gif)

**Expected behavior**
Close animation should be same as SecondaryCommand

**Version Info**
2.5.0-prerelease.201027002

NuGet package version: 

[Microsoft.UI.Xaml.2.5.0-prerelease.201027002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@zhuxb711 good find. It looks like the animations on the primary and secondary are not the same.

**Comment by zhuxb711** [comment]
Just default.

Here is an example:
```xaml
<muxc:CommandBarFlyout x:Name="ItemFlyout"
                               Placement="RightEdgeAlignedTop">
            <AppBarButton Icon="Copy" />
            <AppBarButton Icon="Cut" />
            <AppBarButton Icon="Delete"/>
            <muxc:CommandBarFlyout.SecondaryCommands>
                <AppBarButton>
                    <AppBarButton.Icon>
                        <FontIcon FontFamily="Segoe MDL2 Assets"
                                  Glyph="&#xEC50;" />
                    </AppBarButton.Icon>
                </AppBarButton>
                <AppBarButton >
                    <AppBarButton.Icon>
                        <FontIcon FontFamily="Segoe MDL2 Assets"
                                  Glyph="&#xF5EF;" />
                    </AppBarButton.Icon>
                </AppBarButton>
            </muxc:CommandBarFlyout.SecondaryCommands>
</muxc:CommandBarFlyout>
```

**Comment by chingucoding** [comment]
I would like to look into this.
