### ISSUE TITLE
Links to MS Settings displays "Applications" in XAML Islands v1

### ISSUE THREAD

**Issue by crutkas** [microsoft/microsoft-ui-xaml#3524]
**Describe the bug**

**Steps to reproduce the bug**

1. Have hyperlink to settings
2. click settings
3. dialog comes up with 'applications' but no where is the title set to that.

Tried the WPF and Native XAML implementations.  Both affected, see screenshots

**Expected behavior**
Says application's title.  Preferable the set by the parent application.

PowerToys is affected by this.
https://github.com/microsoft/PowerToys/issues/7651

**Screenshots**

![image](https://user-images.githubusercontent.com/1462282/97644556-e12f5180-1a07-11eb-8c0e-8f9a7fd5fefd.png)
![image](https://user-images.githubusercontent.com/1462282/97645362-045b0080-1a0a-11eb-9b17-2a0341b91029.png)

**Version Info**
https://github.com/microsoft/Xaml-Islands-Samples/commit/4889c827866adfc9ef95a675384cebe998cc28ce

NuGet package version: 
What is included in https://github.com/microsoft/Xaml-Islands-Samples/commit/4889c827866adfc9ef95a675384cebe998cc28ce

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI, I'm not sure where the message dialog would be getting the "applications" string.

**Comment by crutkas** [comment]
My thought was the manifest I think the node is applications.

**Comment by Austin-Lamb** [comment]
@crutkas - what API are you using that opens that dialog?

**Comment by crutkas** [comment]
hyperlink URI to "ms-settings:colors"
