### ISSUE TITLE
WinUI 3 Preview 2 Win2D Blur brush has a gradient masked effect around element/window border

### ISSUE THREAD

**Issue by roxk** [microsoft/microsoft-ui-xaml#3533]
**Describe the bug**

Using Win2D `GaussianBlurEffect` in WinUI 3 Preview 2 produces weird artifact around element/window border regardless of border mode. In particular, the artifact is a black gradient around element border, and no blur around window border.

**Steps to reproduce the bug**
1. Clone the minimal reproducible repo: https://github.com/roxk/winui3-blur-brush-bug-min-repro
2. Build the project in `BlurBrushTestWinUI3Preview2Uwp`.
2. Observe blur around the window border has a gradient masked effect.

**Expected behavior**

WinUI blur brush is the same as UWP blur brush.

**Actualy behavior**

WinUI blur brush has a weird masked gradient effect around window border.

**Screenshots**

UWP:
![](https://github.com/roxk/winui3-blur-brush-bug-min-repro/blob/main/uwp.png?raw=true)

WinUI 3 Preview 2: 
![](https://github.com/roxk/winui3-blur-brush-bug-min-repro/blob/main/winui3-preview2.png?raw=true)

**Version Info**
Windows: 10 2004
Visual Studio Community 2009 Preview 16.7.7

NuGet package version: 
Win2D 1.25.0
Microsoft.WinUI 3.0.0-preview2.200713.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by roxk** [comment]
@StephenLPeters @codendone Any update on this issue? Similar visual artifact can be reproduced in WinUI 3 Control Gallery in the Acrylic page. Just scroll the content so that the acrylic rectangle is across the window border and the same artifact can be seen.

Below is a comparison image:
![winui3-blur-edge-bug-comparison](https://user-images.githubusercontent.com/16918354/118261517-3d5e4c80-b4e6-11eb-9a9f-104445072bb3.png)

A zoomed version for those who can't spot the artifact easily:
![winui3-blur-edge-bug-comparison-zoomed](https://user-images.githubusercontent.com/16918354/118261548-46e7b480-b4e6-11eb-9828-400d4d873e83.png)

In my testing, only window border has this artifact. A scroll view that has large margin (to the window border) isn't affected.

I suspect the community toolkit sample App also has this issue but the minimum window size is big enough that all blur/acrylic samples I tried do not go out of border.

Any update would be appreciated. Thanks!

**Comment by akilarajesh1313** [comment]
Hi @roxk, our teams are currently investigating the issue. Thank you for your patience!

**Comment by pratikone** [comment]
@gegao18  it looks similar to another bug you fixed sometime back. is it same issue or different ?
