### ISSUE TITLE
Question: Will WinUI 3 TextBlock,TextBox and RichEditBox peers implement IText(Range)Provider interface?

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3534]
According to the [documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.provider.itextprovider?view=winrt-19041#remarks) (and verified through manual testing), inbox windows runtime automation peers do not implement the ITextProvider, ITextProvider2 and ITextRangeProvider interface. Will this also be true for the WinUI 3 controls or will that change?

**Comment by codendone** [comment]
There is at least a partial implementation today, copied from OS XAML. I'm not sure how "partial" that implementation is.

Currently there is no plan to make improvements here for WinUI 3.0. But we could consider improvements for a later release.
