### ISSUE TITLE
CalendarView: Navigation buttons do not change appearance when disabled

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3540]
**Describe the bug**

This post is a bug + an additional feature request for now (could be decoupled idepending on what gets approved).

**Steps to reproduce the bug**

1. Open the XAML Controls Gallery
2. Go to the CalendarView control page
3. Scroll until year 1920 (the earliest year available by default)
4. Observe that the foreground of the navigate-to-previous button does not change its foreground even though it is now disabled.

![calendarview-navbuttons-disabled-issue](https://user-images.githubusercontent.com/1398851/97889966-47c8ae00-1d2d-11eb-8b15-a6ed2dcddc3c.gif)

**Expected behavior**
The foreground of the button should be changed:
![calendarview-navbuttons-disabled-issue-2](https://user-images.githubusercontent.com/1398851/97890366-bf96d880-1d2d-11eb-8ace-cece6ecc1a33.gif)

**Version Info**
WinUI 2.4 (and possibly earlier), WinUI 2.5 previews

**Additional Context**
There already exists a `CalendarViewNavigationButtonForegroundDisabled` theme resource to set the foreground of the navigation buttons when they are disabled. However, this resource is not applied when the button is disabled: https://github.com/microsoft/microsoft-ui-xaml/blob/f5034668462987302f1e1c58d1e055e45e40c658/dev/CalendarView/CalendarView_themeresources.xaml#L191

Note that the `NavigationButtonStyle` where this resource would be specified in the disabled visual state is applied to the CalendarView's header button as well the previous/next navigation buttons. In the above GIF showing the epxected behavior I changed the Xaml markup to:
```xml
<VisualState x:Name="Disabled">
    <VisualState.Setters>
        <Setter Target="Text.Foreground" Value="{ThemeResource CalendarViewNavigationButtonForegroundDisabled}" />
    </VisualState.Setters>
</VisualState>
```

If you compare both posted GIFs, you will notice that the background of the header button differs as well (the button saying "1920-1929" for example, which sets the display mode of the CalendarView (month view, year view, decade view)). In the second GIF, it now uses the disabled foreground color since the user can no longer click it to change the display view any further (there is only month/year/decade view available). I'm not sure if the header button was the reason why we don't make use of the `CalendarViewNavigationButtonForegroundDisabled` theme resource for now. I do think it makes sense to indicate to the user that they cannot change the display view any further once they've picked the decade view by clicking that button, so I think changing its foreground color is reasonable here (even though that button is also an informational button to the user as opposed to the navigate backward/forward buttons).

Furthermore, I would like to see more theme resources being added for the navigation buttons. For now, we offer the following resources:
```xml
CalendarViewNavigationButtonBackground
CalendarViewNavigationButtonForegroundPointerOver
CalendarViewNavigationButtonForegroundPressed
CalendarViewNavigationButtonForegroundDisabled
CalendarViewNavigationButtonBorderBrushPointerOver
CalendarViewNavigationButtonBorderBrush
```

Why not add 
```xml
CalendarViewNavigationButtonBackgroundPointerOver
CalendarViewNavigationButtonBackgroundPressed
CalendarViewNavigationButtonBackgroundDisabled

CalendarViewNavigationButtonForeground

CalendarViewNavigationButtonBorderBrushPressed
CalendarViewNavigationButtonBorderBrushDisabled
```
as well? This can be done for WinUI 2.

It might also be worth thinking about separating the header button from the Previous/Next navigation buttons. For now, they all use the same `NavigationButtonStyle` button style which consumes the resources listed above. But since these three buttons are not exactly the same (the header button can also be viewed as an informational button to the user), customers might want to style the header button and the Previous/Next buttons differently. In order to achive that, we could create a new `CalendarViewHeaderButtonStyle` style which will consume a new set of the dedicated theme resources - like `CalendarViewHeaderButtonsForegroundPointerOver`. This would represent a "UI customization" breaking change though, since the current resources like `CalendarViewNavigationButtonBackground` or the button style will differ then for the header button (so WinUI 4?)

@StephenLPeters @YuliKl FYI.

**Comment by StephenLPeters** [comment]
the disabled state is for sure good. I think I agree with the resources as well

**Comment by StephenLPeters** [comment]
@kikisaints fyi
