### ISSUE TITLE
Proposal:  Add "ItemSelected" event to TreeView control

### ISSUE THREAD

**Issue by dan-meier** [microsoft/microsoft-ui-xaml#3548]
This event would occur when a TreeView item's checkbox is checked or unchecked (when the control's SelectionMode property is "Multiple"). The event should include an argument containing the related node object and the new checkbox state (i.e., IsChecked).

There is currently no way to detect when a node checkbox is checked or unchecked.

**Comment by Felix-Dev** [comment]
The TreeView control currently has in API preview (WinUI preview versions) a SelectionChanged event which should come with the necessary data requested here. PR [here](https://github.com/microsoft/microsoft-ui-xaml/pull/2063) and spec (draft) [here](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/80).

**Comment by StephenLPeters** [comment]
There is a selection changed event in preview. Does that cover your needs?

**Comment by dan-meier** [comment]
Yep...that'll work. Thanks!
