### ISSUE TITLE
Question: [In UWP, how to skip tab key navigation for an UserControl and all of its child element?]

### ISSUE THREAD

**Issue by Selvamz** [microsoft/microsoft-ui-xaml#3560]
In UWP, I want to handle and skip the tab key navigation for particular set of controls dynamically.

For e.g., I've two user controls (Both have lot of children which will be added dynamically) in my main page and want to skip tab key navigation for one usercontrol dynamically on specific scenario for a moment.

So I've tried to set "IsTabStop" as false to that UserControl. But which is not effective on its child controls. Still tab key focus moved inside the children of that UserControl.

Note: If I set "IsEnabled" as false, then its working. But I don't want to use because it affects Visual appearance.

Thanks in advance.

**Comment by stevewri** [comment]
WinUI controls issue.

**Comment by StephenLPeters** [comment]
I think the way to do this is subscribe to the GettingFocus event on your control and you can use the TryCancel method on the args when you determine this shouldn't get focus. Then you can use GetNextFocusable element to find the next thing in the tab order and call SetFocus using focus type programatic (which will behave the same as the last user input for touch/mouse differences).  Pretty complicated but IsTabStop doesn't do this for you.
