### ISSUE TITLE
Attached Property doesn't get updated to x:Null when property type is MenuFlyout

### ISSUE THREAD

**Issue by TANG-Kai** [microsoft/microsoft-ui-xaml#3564]
**Describe the bug**
Setting an attached MenuFlyout to {x:Null} won't update the property nor will it call OnPropertyChanged. This can be worked around by setting the PropertyType to object instead.

**Steps to reproduce the bug**
1.Run the attached project [AttachedPropertyTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5500322/AttachedPropertyTest.zip)

2. In AttachedPropertyClass.cs you have:
```c#
        public static readonly DependencyProperty AttachedMenuFlyoutProperty = DependencyProperty.RegisterAttached(
            "AttachedMenuFlyout",
            typeof(MenuFlyout),
            typeof(AttachedPropertyClass),
            new PropertyMetadata(default(MenuFlyout), OnPropertyChanged));

        private static void OnPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var sender = d as TextBlock;
            sender.Text += Environment.NewLine + "PropertyChanged !";
        }
```
Run the project to see that the textblock doesn't actually get updated.

3. Change the typeof(MenuFlyout) to typeof(object) and run again. You can see the textblock will get updated as expected now.

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21253)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by ranjeshj** [comment]
Is the default already null  in which case setting it to x:Null is a no-op ?

**Comment by chrisglein** [comment]
> Is the default already null in which case setting it to x:Null is a no-op ?

This `default(MenuFlyout)` should resolve to null, not an empty `MenuFlyout` type, correct?
@TANG-Kai what default value are you expecting here? Does it work if you change between other non-null values?

**Comment by StephenLPeters** [comment]
@katan-ms responded in #3790
