### ISSUE TITLE
InfoBar strings are not localized

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#3566]
InfoBar is missing localized strings. 

I think we need to add an entry to the loc config here - https://github.com/microsoft/microsoft-ui-xaml/blob/master/build/Localization/Settings/LocConfig.xml

We should take a look at other controls and make sure they are not missed out as well.

**Comment by chingucoding** [comment]
I would like to look into this, it seems that there are a few controls missing from that list.
