### ISSUE TITLE
CalendarDatePicker when selecting same date. Exception "Nullable object must have a value"

### ISSUE THREAD

**Issue by ccarlo88** [microsoft/microsoft-ui-xaml#3571]
Hello,

I am having an issue on UWP with CalendarDatePicker when trying to x:Bind it to my model which uses DateTimeOffset. It throws a "Nullable object must have a value" if I select the same date which is already selected.

I could use a converter in the middle, which may solve the problem (didn't try it) but I don't see a reason on to why using it as both uses the same data type, correct?

I also tried declaring my model with DateTimeOffset? which won't compile then.

If I use DatePicker everything works fine, no exceptions thrown.

Thanks.

**Comment by wbokkers** [comment]
In WinUI 3 Preview 4, I always get an exception when x:Bind to the Date property. I am not sure if this is related:

Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Exception thrown at 0x76D8A8B2 (KernelBase.dll) in ....  WinRT originate error - 0x80131604 : 'Exception has been thrown by the target of an invocation.'.

**Comment by BalazsSzekeres** [comment]
Experience the same issue using the Microsoft Toolkit MVVM for data binding. 

The XAML looks like the following:
`<CalendarDatePicker
                                PlaceholderText="Pick a start date"
                                Header="Start Date"
                                Margin="10,10,10,10"
                                Date="{x:Bind ViewModel.startDate , Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                                />`

The view model has the following property:
`private DateTimeOffset _startDate = DateTimeOffset.Now;
        public DateTimeOffset startDate
        {
            get => _startDate;
            set
            {
                SetProperty(ref _startDate, value);
            }
        }`

If I select the same date twice I get the following exception: 

> Event Type Moniker	Event	Time	Duration	Thread
> Activated Historical Code Context	Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll ("Nullable object must have a value.") Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll ("Nullable object must have a value.") Hyperlink: Activate Historical Debugging	5.64s		[35204] <No Name>

**Comment by anlocnghg** [comment]
Got the same exception as followed:

XAML:
`<CalendarDatePicker
                Date="{x:Bind ViewModel.KnownRDO, Mode=TwoWay}" />`

ViewModel:
`public DateTimeOffset KnownRDO
        {
            get => _knownRDO;
            set => SetProperty(ref _knownRDO, value);
        }`

When select the same date again:
> Exception	{"Operation is not valid due to the current state of the object."}	System.Exception {System.InvalidOperationException}
> Message		"Nullable object must have a value."	string

**Comment by anlocnghg** [comment]
I've found a walkaround that, in the event handler DateChanged, let's name it 'myDatePicker', then check if `myDatePicker.Date == null`. If so, then set the ViewModel's binded property to `myDatePicker.MinDate` if it's not MaxDate, and set it to MaxDate if it's currently not MinDate, and display a message saying 'hey, you have selected the same date twice, and thus I reset your date to MinDate/MaxDate'.

**Comment by jcbeppler** [comment]
@anlocnghg Hey, good catch! I am basically not working with .NET anymore but I think I tried something similar... maybe I try that when I have time. Thanks for sharing!

**Comment by Lucitus** [comment]
I ran into the same issue.
