### ISSUE TITLE
Textbox context menu doesn't detect touch keyboard presence

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/microsoft-ui-xaml#3573]
**Describe the bug**
The keyboard goes over the context menu

**Steps to reproduce the bug**
1. Add a textbox in the bottom part of the app;
2. Long press on it while focused in tablet mode or without a keyboard attached

**Expected behavior**
Firstly open the keyboard, then display the context menu in the right position (over it)

**Screenshots**

![image](https://user-images.githubusercontent.com/43090263/98483952-566f0380-220c-11eb-9f15-0507f019638e.png)

**Version Info**

NuGet package version: 
2.4.2

Windows app type:
Uwp
| :--------------- | :--------------- |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |

| May 2020 Update (19041)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop           

**Additional context**
Not needed

**Comment by kmgallahan** [comment]
Pretty sure no content appears over on-screen keyboards on any OS by design.

**Comment by MarcAnt01** [comment]
I think long press shouldn't open the keyboard, but I was told this is intended (even if I think this behavior is very bad).

**Comment by MarcAnt01** [comment]
Can this be reopened?

**Comment by DmitriyKomin** [comment]
@MarcAnt01, thank you for reporting this issue. Unfortunately we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).  

I tried this out on WinAppSDK 1.5 / WinUI3 Gallery on a SurfaceBook3 with "Show Touch Keyboard" (in Settings) set to "When no keyboard attached", and the issue does not appear to repro. Tapping in the textbox causes the app window to get repositioned such that the textbox is visible above the onscreen keyboard.
