### ISSUE TITLE
WinUI Dekstop app crashes on Navigate to View from another Library

### ISSUE THREAD

**Issue by Berkunath** [microsoft/microsoft-ui-xaml#3574]
I have created the application with Navigation View contains Frame. While try to navigate to the view from another library using Frame.Navigate method application get crash. If the view is inside the same library, Frame.Navigate works properly.

![image](https://user-images.githubusercontent.com/74045266/98506348-46453b80-2281-11eb-8c68-cb1ba4dff2a3.png)

**Steps to reproduce the bug**
1. Run the attached sample
2. Application get crash on Frame.Navigate 

**Expected behavior**
Application should not throw any exception

**Version Info**
WinUI NuGet package version - 3.0.0-preview2.200713.0,
Windows app type - WinUI Desktop app,
OS version(s) - 10.0.18362.1139

Sample: 
[FrameNavigation.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5508445/FrameNavigation.zip)

**Comment by chrisglein** [comment]
Reminding me of #3371, which also was an issue doing things cross-library with WinUI3 preview.

**Comment by chrisglein** [comment]
@JesseCol The actual crash seems to be in the UDK. Is that expected to show up that way or is that a red herring in this type of issue?

@Berkunath Could you try this repro on preview3 of WinUI3? Also, does this same scenario work without WinUI3 on a plain OS XAML app?

**Comment by Berkunath** [comment]
@chrisglein After WinUI 3 Preview 3, It seems working fine without crash.
