### ISSUE TITLE
Xaml island: Setting "RequestedTheme" results in broken theming and unreadable text when value differs from system-wide setting

### ISSUE THREAD

**Issue by Isopod** [microsoft/microsoft-ui-xaml#3576]
When setting the "RequestedTheme" property of an element to a value differing from the system-wide setting (e.g. `RequestedTheme='dark'`, when system setting is "light" and vice versa), parts of the UI are rendered inconsistently. For example, the window background color does not respect the local setting, instead using the value from the system-wide theme. (This particular issue can be worked around by explicitly setting the background to `SystemAltHighColor` in the Xaml code.) A more serious issue is that text in context menus becomes unreadable because the text color is taken from the system theme, but the background is not.

**Steps to reproduce the bug**
1. Download [this simple demo project](https://github.com/Isopod/xaml-bugs/tree/main/theme-bug)
2. The demo project assumes that the system-wide setting is "light". Please make sure you are using the light theme. Alternatively, change [these lines](https://github.com/Isopod/xaml-bugs/blob/main/theme-bug/theme-bug.c#L161).
3. Run the project. The Xaml island should be using dark mode according to the Xaml markup. Note immediately, that the window background color is wrong: it should be dark, but it is light.
4. Right-click on the TextBox to open the context menu. The text in the context menu is unreadable.

**Expected behavior**
All UI rendering should respect the "RequestedTheme" set in the Xaml code. It should not randomly mix in colors from the system theme.

**Screenshots**
Video: https://imgur.com/a/vs9qKKU

**Version Info**
Windows Kit 10.0.18362.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by pratikone** [comment]
it fixed in latest releases. closing now.
