### ISSUE TITLE
One or more arguments are invalid

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#3579]
**Describe the bug**
Due to unknown reasons, the UI framework throws this exception and the source cannot be traced

**Steps to reproduce the bug**
1. Unknown

**StackTrace**
[StackTrace.txt](https://github.com/microsoft/microsoft-ui-xaml/files/5511026/StackTrace.txt)

**Version Info**
2.5.0-prerelease.201027002

NuGet package version: 
[Microsoft.UI.Xaml.2.5.0-prerelease.201027002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by ranjeshj** [comment]
can you please attach a repro app ?

**Comment by zhuxb711** [comment]
It is temporarily unclear what UI controls cause this problem. But it may be related to double-clicking the ListView/GridView that enables drag and drop.
