### ISSUE TITLE
Hierarchical NaviagationView doesn't work properly using Xaml Islands

### ISSUE THREAD

**Issue by LadislavPataki** [microsoft/microsoft-ui-xaml#3580]
**Describe the bug**

I have a WPF application which is using Xaml Islands to host winui hierarchical NavigationView (see code sample below). The issue is that only the first item of the submenu is displayed. I've also checked  the control in an UWP app and it worked fine.

```
        <muxc:NavigationView
            x:Name="navView"  
            ...
            PaneDisplayMode="Left">
            <muxc:NavigationView.MenuItems>
                <muxc:NavigationViewItem
                    Content="Home"
                    Icon="Home"
                    Tag="HomePage"
                    ToolTipService.ToolTip="Home" />

                <muxc:NavigationViewItem
                    Content="Collections"
                    Icon="Keyboard"
                    SelectsOnInvoked="False"
                    ToolTipService.ToolTip="Collections">

                    <muxc:NavigationViewItem.MenuItems>
                        <muxc:NavigationViewItem Content="Item1" Tag="Page1" />
                        <muxc:NavigationViewItem Content="Item2" />
                        <muxc:NavigationViewItem Content="Item3" />
                    </muxc:NavigationViewItem.MenuItems>

                </muxc:NavigationViewItem>

                ...
            </muxc:NavigationView.MenuItems>
          ...
        </muxc:NavigationView>
```

**Steps to reproduce the bug**

1. Run the application.
2. Expand one of the expandable menu items.
3. Only the first menu item is visible.

**Expected behavior**

I can see all the submenu items when the menu is expanded.

**Screenshots**

![image](https://user-images.githubusercontent.com/12115874/98562479-676e5200-22aa-11eb-815c-b9e8b9ce54f1.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.5.0-prerelease.201027002]
[Microsoft.UI.Xaml.2.5.0-prerelease.200923002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |  Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Sample app:
[WpfApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5511658/WpfApp.zip)

**Comment by ranjeshj** [comment]
This looks like a dup of #2102

**Comment by LadislavPataki** [comment]
@ranjeshj Thanks for the response. I thought it was fixed in some of the previous releases because this [#2102](https://github.com/microsoft/microsoft-ui-xaml/issues/2102) was about the menu items not about the submenu items. Non collapsible menu items works fine in my case (all are shown not just the first one).

Is there possibility to somehow overcome this issue? Is it going to be fixed in the near future?

**Comment by ranjeshj** [comment]
Unfortunately this is a platform bug which will have to be fixed in WinUI3 codebase.
