### ISSUE TITLE
InfoBar icon theming incorrect

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#3581]
**Describe the bug**
![infobar-icon](https://user-images.githubusercontent.com/20007011/98576558-8dc2cc00-226f-11eb-98f6-4d8769a56053.png)

The icon foreground color does not react to theme change, it should be white instead of black.
 
**Reproduce the bug**
The XCG generated with the 2.5 prerelease.201027002 package at user/gabilka/InfoBar in the XCG repo shows this bug on theme change from light to dark.

**Comment by mdtauk** [comment]
Switch to using ThemeResource Brushes

**Comment by ranjeshj** [comment]
> Switch to using ThemeResource Brushes

Looks like we are already using theme brushes for the icon.
