### ISSUE TITLE
NumberBox up/down arrows default to being disabled

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#3585]
**Describe the bug**

When using NuberBox, its increment/decrement buttons are showing in their disabled state by default.

**Steps to reproduce the bug**

1. Add NumberBox to a sample app `<muxc:NumberBox SpinButtonPlacementMode="Inline" />`
2. Run the app
3. Note that the buttons are disabled

**Expected behavior**

Buttons should be enabled by default, and only show as disabled when some specific condition (like getting to the min/max value) is encountered.

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/98629070-ebd1cc80-22cc-11eb-91db-e80cc9289c2d.png)

**Version Info**

NuGet package version: 2.5.0-prerelease.201027002

**Additional context**

This issue can be worked around by setting the value of NumberBox to 0 instead of leaving it unset.
![image](https://user-images.githubusercontent.com/13142665/98629220-3eab8400-22cd-11eb-86f6-6d2ffaa70925.png)

**Comment by ranjeshj** [comment]
@SavoySchuler [Value seems to default to quiet_nan](https://github.com/microsoft/microsoft-ui-xaml/blob/9b264ff73eeea18f6e13abe0b8ad9395b1c0138b/dev/NumberBox/NumberBox.idl#L43) which is probably why we are seeing this behavior. Should the default be something else ?

**Comment by kmgallahan** [comment]
IMO if Value isn't set, then the buttons should remain disabled. Otherwise the first interaction would then also be responsible for initializing Value.

If the buttons don't remain disabled then an assumption is being made about what the initial value should be, unless another property is added to change this.
