### ISSUE TITLE
The FocusManager.TryMoveFocusAsync throws exception

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3586]
**Describe the bug**
Hi,
I've tried to use the FocusManager.TryMoveFocusAsync method and got an exception:
> System.TypeLoadException: 'Unable to find a type named 'IAsyncOperation<Windows::UI::Xaml::Input::FocusMovementResult*''

**Steps to reproduce the bug**
MainWindow ctor:
~~~csharp
 public MainWindow() {
            this.InitializeComponent();
            FocusManager.TryMoveFocusAsync(FocusNavigationDirection.Next);
        }
~~~

**Expected behavior**
The exception shouldn't throw or hide the TryMoveFocusAsync method

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by MikeHillberg** [comment]
It looks like some code was trying to use the wrong type for the IAsyncAction (Windows namespace rather than the Microsoft namespace). But this is no longer happening in the Preview3 version.
