### ISSUE TITLE
The FocusManager.TryMoveFocus doesn't move focus

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3587]
**Describe the bug**
Hi,
When I use the FocusManager.TryMoveFocus method to move focus to the next element (TextBox) it always returns false and the focus doesn't move. What I do wrong and how I can move focus to the next?

**Steps to reproduce the bug**
MainWindow.xaml
~~~xaml
<Window
    x:Class="IssueSample.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:IssueSample"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="button" Content="Click" Click="Button_Click"/>
        <TextBox x:Name="box"/>
    </StackPanel>
</Window>
~~~
MainWindow.xaml.cs
~~~csharp
using System.Diagnostics;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Input;

namespace IssueSample {
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
        }

        private async void Button_Click(object sender, RoutedEventArgs e) {
            var result = FocusManager.TryMoveFocus(FocusNavigationDirection.Next);
            Debug.WriteLine($"{result} {FocusManager.GetFocusedElement(box.XamlRoot)}");
        }
    }
}
~~~

**Expected behavior**
After FocusManager.TryMoveFocus the focused element should be the TextBox

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by BorzillaR** [comment]
I have reproduced this issue in Preview 3.

**Comment by JesseCol** [comment]
Thanks BorzillaR!  

It should work if you scope the "SearchRoot" to the relevant XamlRoot.Content with TryNextFocus like this:

```
            FocusManager.TryMoveFocus(FocusNavigationDirection.Next, 
                new FindNextElementOptions { SearchRoot = ((Button)sender).XamlRoot.Content });
```

In the future the platform and app may support multiple "fragments" of XAML on the same thread.  This code will keep working if that happens.  The "XamlRoot" object above is basically a handle to the fragment of XAML that contains the Button.

Granted, we need a better error message here, because it's not clear what's going wrong.  We're tracking that in our internal database.
