### ISSUE TITLE
Xaml island: Having more than one island kills Acrylic effect

### ISSUE THREAD

**Issue by Isopod** [microsoft/microsoft-ui-xaml#3590]
When you have more than one Xaml island in an application, the Acrylic effect stops working. Even when you remove the additional islands later, the functionality does not return.

**Steps to reproduce the bug**
1. Download [this demo project](https://github.com/Isopod/xaml-bugs/tree/main/acrylic-bug) and run it
2. Click the button to spawn an additional window with a xaml island
3. Observe how the Acrylic effect stops working

**Expected behavior**
Acrylic should work regardless of how many windows or islands you have in your application.

**Screenshots**
Video: https://imgur.com/hMcWOgS

**Version Info**
Windows Kit 10.0.18362.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by ranjeshj** [comment]
@codendone @DmitriyKomin any ideas what might be happening here ?

**Comment by DmitriyKomin** [comment]
Unfortunately, this is a known limitation – sharing of AcrylicBrush / RevealBrush across islands is not supported (additional work is required that we have not undertaken). IIRC, the behavior in that case is: usage in 1st island is correct acrylic, in other islands it will always be in fallback.

As a workaround you should be able to duplicate the brush instance for each island and avoid cross-island sharing that way.

**Comment by Isopod** [comment]
> IIRC, the behavior in that case is: usage in 1st island is correct acrylic, in other islands it will always be in fallback.
Actually, as you can see in the video, both islands start to use fallback as soon as the second island is opened, and this is permanent, i.e. continues even after the second island has been closed again.

> As a workaround you should be able to duplicate the brush instance for each island and avoid cross-island sharing that way.
How do I do that?

**Comment by sylveon** [comment]
> How do I do that?

You're using ThemeResources for the acrylic brush. Instead, manually declare the brush, for example like this:
```xaml
<Grid.Background>
    <AcrylicBrush BackgroundSource="HostBackdrop" TintColor="{ThemeResource SystemAltHighColor}" TintOpacity="0.3" FallbackColor="{ThemeResource SystemChromeLowColor}" />
    </Grid.Background>
````

This will use a different instance of AcrylicBrush for each new island instead of sharing the same instance across islands.

**Comment by Isopod** [comment]
@sylveon Thank you, I can confirm this works as a workaround.

Although, there is some weirdness still: At first, all windows created this way use the Acrylic effect, even the ones that are not in the foreground, as long as the application is focused (not sure if this is intended?). But when the application loses focus, after gaining focus again, only the last active window uses Acrylic while the other ones use the fallback color. And this remains even when you then switch to a different window in the same application. That is to say, not the foreground window will use the Acrylic effect, but the window that was last in the foreground *before* the application lost focus. To "move" the Acrylic from one window to another one has to first switch to something else (e.g. by clicking on empty space in the taskbar) and then switch back.

It seems like there is some internal confusion between app focus and window focus, most likely stemming from the fact that UWP apps only have a single window.

**Comment by sylveon** [comment]
Yes, there is a lot of brokenness with multiple Islands in a single thread - I learnt that the hard way.

My solution was to use an unique thread for each XAML Island, and recycle those threads (because for some reason tearing down the WindowsXamlManager in a thread broke creating a new one in every other thread). Then everything, including acrylic, seems to work fine.
