### ISSUE TITLE
Possible Failure of Target Platform detection?

### ISSUE THREAD

**Issue by maschgit** [microsoft/microsoft-ui-xaml#3596]
**Describe the bug**

After update of Visual Studio to version 16.8.0 I get the following failure:
.nuget\packages\microsoft.ui.xaml\2.4.3\buildTransitive\Common.targets(10,5): error : Microsoft.UI.Xaml nuget package requires TargetPlatformMinVersion >= 10.0.15063.0 (current project is -1)
No idea why the microsoft.ui.xaml detect 10.0.15063.0, because I have only installed the Windows 10 SDK 10.0.19041.0.

**Steps to reproduce the bug**

Compile the project.

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.3

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |   Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

The application is a WPF application based on NET Core 3.1.
Visual Studio 2019 16.8.0 is running on Windows 10 Pro Version 2004 OS Build 19041.630 with Windows Feature Experience Pack 120.2212.31.0

**Comment by StephenLPeters** [comment]
Our projects work with VS 16.8.0, could you provide a repro project for us to debug to find the issue?

**Comment by maschgit** [comment]
I'm very sorry for my late answer. I had lot of work... 
I created a demo project in which the Problem occurs.
My Visual Studio is on version 16.8.1.
Here is the link to the [DemoTestProject](https://github.com/maschgit/DotNetCoreDemoTest/tree/main).

**Comment by Bobbesmaennle** [comment]
Hello,
I'm still facing the same error when I create a WPF application with .NET Core 3.1 in Visual Studio 2022 17.4.1 on Windows 11 version 22H2 build 22621.819.
Are there news on this issue or a workaround available in the meantime.
Any help would be appreciated.

**Comment by XamlTest** [comment]
Hello,
The issue is also reproduced when I create a WPF application using .NET Core 6.0 in Visual Studio 2022 17.7 Preview 1 on Windows 11 version 22H2 build 22621.1555.
Is there any news about this issue or a workaround available at the same time.
Thanks!

**Comment by DmitriyKomin** [comment]
@maschgit, are you hosting Xaml (WinUI2 island) in your WPF application? If not, we should move this issue to the WPF GH repository.
