### ISSUE TITLE
TabView: Memory usage does not go down after opening/closing tabs

### ISSUE THREAD

**Issue by duke7553** [microsoft/microsoft-ui-xaml#3597]
It appears that there are invisible items in the WinUI TabView visual tree which stick around even after they are removed. This behavior isn't desirable because users could have many TabViewItems with memory-intensive pages as their content.

**Steps to reproduce the bug**

1. Create a project where TabViewItems have a ContentTemplate property of a Frame with somewhat memory-intensive content. 
2. Remove all of the tabs (hopefully destroying their content) by clearing the ObservableCollection.
3. Inspect memory usage to see persistently high levels

**Expected behavior**
TabView must support scenarios with robust XAML content inside the TabViewItems by freeing the memory when tabs are closed via removal from ObservableCollection.

**Screenshots**
![image](https://user-images.githubusercontent.com/20365014/126883113-c6706c09-6db0-4a88-a56c-1e06eaf17126.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.6.1

| Windows version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.100)              | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Old comment: https://github.com/microsoft/microsoft-ui-xaml/issues/1332#issuecomment-559997193

**Comment by ranjeshj** [comment]
@duke7553 can you see if this is resolved in the latest pre-release ? Do you happen to know if this regressed or something that is in older releases as well ?

**Comment by duke7553** [comment]
@ranjeshj Thanks for getting back to my issue. This has been an issue with use of TTabViewin our project for a long time. Probably since we switched to the WinUI TabView. Since this could very well be an issue with my app specifically, I am working on a sample project to demonstrate if the behavior is reproducible or not. 

I expect to add it to this issue report soon.

**Comment by ranjeshj** [comment]
Thanks @duke7553 for the clarification. A repro app would be great.

**Comment by duke7553** [comment]
@ranjeshj This is a v2.4 sample app which reproduces the bug in a minimal way.
 
Download APPX Package for x64:
https://1drv.ms/u/s!AvgU7aa_XojB6RIRaTmDb65Jsb1W?e=PJu6V6

Download source code:
https://1drv.ms/u/s!AvgU7aa_XojB6RPkbJxFtH3P-p1U?e=y7Kl9N

**Comment by duke7553** [comment]
@ranjeshj @StephenLPeters I've updated the repro project for this bug to WinUI v2.6. The issue is definitely still present and it makes using the TabView for any kind of robust XAML content a nonstarter.

Please give it a look when you get a chance. 😔🙏🏻

**Comment by duke7553** [comment]
@ranjeshj @StephenLPeters I did some more detective work on this: **It looks like this bug still exists even when completely replacing TabView with a regular ListView in my repro app.**

Memory usage stays elevated despite clearing the ListView ItemSource. This includes setting it to null, removing each item one-by-one, and doing .Clear() on it.

Should this behavior be expected of ListView and XAML controls in general with C#? How can I free an item's memory usage after it's closed? Am I missing something, or is this just an awful bug reported by [many](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/61df6098-3f31-4ce4-a6e0-031d1a619554/uwp-memory-leaks-in-uwp-listview), [other](https://github.com/xamarin/Xamarin.Forms/issues/3065) [users](https://stackoverflow.com/questions/51200302/uwp-memory-leak) [over](https://docs.microsoft.com/en-us/answers/questions/111194/memory-leak-on-uwp-with-target-versions-100177630.html) the years.

**Comment by StephenLPeters** [comment]
@duke7553 have you ensured that GC has run by calling GC.Collect() during your testing?

**Comment by duke7553** [comment]
@StephenLPeters Yes. The repro app does this after it clears the tabs

**Comment by duke7553** [comment]
Most of the memory growth is from unmanaged memory btw

**Comment by duke7553** [comment]
@StephenLPeters Is the team aware that this is an issue with TabView and ListView or is there something I'm doing incorrectly regarding coding practices with these controls?

**Comment by StephenLPeters** [comment]
It is on our radar, thank you for raising the issues.

**Comment by StephenLPeters** [comment]
The underlying issue has been fix, unfortunately it is an operating system bug and cannot be addressed from Winui2.

**Comment by yaichenbaum** [comment]
> The underlying issue has been fix, unfortunately it is an operating system bug and cannot be addressed from Winui2.

@StephenLPeters do you know which build of the OS incudes the fix?

**Comment by duke7553** [comment]
> It was a recent fix so it will be included in a future release. Although, my understanding is the current plan is to service this fix, so some older versions of window 10/11 will receive the fix in a service update at some point.

Wow! Thanks for circling back and the transparency here. By any chance, would this fix already be present in WinUI Desktop? Or maybe UWP XAML is the only stack affected.

This made my day!

**Comment by lukeblevins** [comment]
@StephenLPeters @RBrid Has the OS fix shipped in Windows or the decoupled UI stack yet?

**Comment by ojhad** [comment]
We have made the fix but it has not shipped yet. We are working on porting it to WinUI3.

**Comment by lukeblevins** [comment]
@ojhad @RBrid @StephenLPeters Has this fix shipped yet?

**Comment by lukeblevins** [comment]
@ojhad @RBrid @StephenLPeters Should this be reopened?

**Comment by lukeblevins** [comment]
What a joke.

Hopefully this repository situation improves in the coming years, or else it's abundantly clear that WinUI isn't sustainable nor is it a priority to Microsoft.

**Comment by yaira2** [comment]
This issue appears to be affecting File Explorer and Notepad as well.

**Comment by 0x5bfa** [comment]
@ojhad Has that fix been ported into WinUI3?

**Comment by neildmd** [comment]
This memory leak has been present for an embarrassingly long time... It's not like this is insignificant. Why are they dragging their feet on this?

**Comment by neildmd** [comment]
> @ojhad Has that fix been ported into WinUI3?

You would think that it would have been ported by now... This memory leak has been present for an embarrassingly long time. It's not like this is insignificant. Why are they dragging their feet on this?

**Comment by 0x5bfa** [comment]
lol. Maybe they have been busy for a long time.
Do you think we should reopen? Looks like they have their mirrored issue tracker internally.

**Comment by codendone** [comment]
I checked with the team, and the fix has been in WinUI3 since WinAppSDK 1.3 (ported via [internal bug](http://task.ms/40689381)).

It sounds like there are additional leaks beyond that fix. Please open a new issue with a repro for us to investigate those leaks. Thanks!
