### ISSUE TITLE
WinUI Desktop app crashes on scroll NavigationView

### ISSUE THREAD

**Issue by Berkunath** [microsoft/microsoft-ui-xaml#3598]
I have created application with NavigationView with MenuItemsSource. Navigation View have scrollviewer due to insufficient space. While scrolling NavigationView items, application get crash.  Adding NavigationViewItems not throws exception on scrolling but Application crashes only when items populated through MenuItemsSource.

**Steps to reproduce the bug**
1. Run the application
2. Scroll down to last item
3. Now select last item
4. Scroll up to top of the navigation view
5. Expand navigation page crash the application
6. If application not crash on step 5, Scroll down the Navigation application crash

**Expected behavior**
Application should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/74045266/98906495-257c2080-24e3-11eb-8bcd-57461ee44bd5.png)

**Version Info**
WinUI NuGet package version - 3.0.0-preview2.200713.0,
Windows app type - WinUI Desktop app,
OS version(s) - 10.0.18362.1139

**Additional context**
Application crashes on scrolling down the navigation in original application 

**Sample**
[FrameNavigation.WinUI.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5528822/FrameNavigation.WinUI.zip)

**Comment by StephenLPeters** [comment]
@ojhad FYI

**Comment by alwu-msft** [comment]
Hi @Berkunath, this may be a known C#/WinRT bug that wasn't fixed in time for WinUI 3 Preview 3. Could you try installing .NET SDK >= 5.0.101, adding the following lines to your project file, and seeing if the crash still repros? Thanks!
```xml
  <ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.19041.12" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.19041.12" />
  </ItemGroup>
```

**Comment by anawishnoff** [comment]
Looks like this bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Please let us know if this issue persists in Preview 4. Thanks!

**Comment by Berkunath** [comment]
We could not able to reproduce this issue in WinUI 3 preview 4.

Thanks

**Comment by MikeHillberg** [comment]
Thanks for checking @Berkunath!

**Comment by Berkunath** [comment]
Hi @MikeHillberg , @anawishnoff 

This has been fixed in WinUI Desktop. But after upgrade to WinUI 3 Preview 4, scrolling navigation view in WinUI UWP application hangs.

Sample : 
[Scroll Navigation UWP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5987038/Scroll.Navigation.UWP.zip)

**Comment by MikeHillberg** [comment]
Thanks for checking the first issue! And sorry about the second, we'll follow up on that with #4204 that you opened.

**Comment by rcohn** [comment]
Hello -

I am seeing expand crash problems in NavigationView in a WinUI3 desktop app with Windows App SDK 1.1.2.

In my code, I am wrapping a NavigationView with ScrollViewer.  NavigationViewItems are added dynamically to the NavigationView and top-level NV groups are allowed to be expanded and collapsed by the user.  We have some workarounds for the crash, such as playing with the ScrollViewer height, but it's non-deterministic when the crash will occur.

And, before you ask, I could not get NV ScrollViewer properties to produce a vertical scrollbar.

I have not seen any examples or usable tips that help with ScrollViewer problems of this type.

I would welcome any advice from the experts who read this forum, or from anybody who may have found a workable solution.

Thanks and best regards.
