### ISSUE TITLE
Please add RelativePanel here

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#36]
I'm interested in creating the equivalent RelativePanel control for WPF. I got an implementation close to it, but the layout cycle isn't completely in sync with the UWP one. It would be really helpful if RelativePanel was part of the open sourced controls, so that we can create consistent implementations across the XAML platforms.

**Comment by pag3** [comment]
Thanks for raising this!  I'm curious are there any changes/improvements folks would like in this feature, too, or just getting access to see the control's source code?

**Comment by dotMorten** [comment]
Well my immediate need is to see how the layout cycle is implemented, so that the exact behavior can be duplicated in WPF. Having said that knowing how Panels work is a great learning experience, as they form the basic for a lot of advanced controls.

**Comment by dotMorten** [comment]
@kodamaSakanu I have an implementation too. Afaik it matches the behavior of UWP, but there are so many edge cases I likely don't handle: https://github.com/dotMorten/UniversalWPF/tree/master/src/UniversalWPF

**Comment by pag3** [comment]
Okay thanks.  We’d certainly like to help move all our XAML developers forward and help bridge folks to the latest WinUI / UWP XAML.  In general, there are a number of controls we need to migrate into WinUI - e.g. see recent requests for ComBox features - and as we do so it’s not always just a “copy and paste” from the in-box code as we need to ensure the code is layered over the core os the right way, follows the coding and engineering practices that support good open source collaboration, etc.  One option to get you the code is to wait until we’ve done that migration and moved the feature into WinUI, but given your feedback we’re going to look into if there are ways for us to accelerate that and possibly do more of the migration itself in the open which would let you see more of the code sooner.

**Comment by mdtauk** [comment]
> Okay thanks. We’d certainly like to help move all XAML developers - even those on WPF - forward and help bridge folks to the latest WinUI / UWP XAML. In general, there are a number of controls we need to migrate into WinUI - e.g. see recent requests for ComboBox features - and as we do so it’s not always just a “copy and paste” from the in-box code as we need to ensure the code is layered over the core os the right way, follows the coding and engineering practices that support good open source collaboration, etc. One option to get you the code is to wait until we’ve done that migration and moved the feature into WinUI, but given your feedback we’re going to look into if there are ways for us to accelerate that and possibly do more of the migration itself in the open which could let you see more of the code sooner.

How about ComboBoxPreview   **__________Preview**  For slowly updating inbox controls until they are mature enough to totally replace them?

**Comment by jesbis** [comment]
This would be included in WinUI 3.0, which we plan to make open source.

So, closing this in favor of the general WinUI 3.0 issue #717
