### ISSUE TITLE
Proposal: Visual Studio xaml editor is not showing color inline preview when using AppThemeBinding in Xamarin

### ISSUE THREAD

**Issue by Cfun1** [microsoft/microsoft-ui-xaml#3600]
Related link to Xamarin.Forms repo: https://github.com/xamarin/Xamarin.Forms/pull/11012
[Themes for Xamarin.Forms](https://devblogs.microsoft.com/xamarin/app-themes-xamarin-forms/) enables to fast implementation of dark/light themes.

when using for example:
```
<Label Text="Xamarin.Forms!" TextColor="{AppThemeBinding Dark=#2196F3, Light=#2196F3}"/>
```
 ## Summary
Visual studio should display an incline color preview near beside `Dark=#2196F3`" and `Light=#2196F3` the same way it did for something like: <Label TextColor="#2196F3"/>

## Rationale
* Because you are setting a color hex code it make sens to have preview inline for it.

Note:
I am not able to report this thru visual studio because of some session issues, if this is not the right place please someone report this as a visual studio issue.

**Comment by StephenLPeters** [comment]
@fabiant3 I'm not sure if this is us or VS's issue

**Comment by Cfun1** [comment]
@StephenLPeters, @fabiant3 @chingucoding  any update if this issue is in the right place or no ?

**Comment by JeanRoca** [comment]
@LyalinDotCom is this something on the Xamarin team?

**Comment by LyalinDotCom** [comment]
@Cfun1 J.P is correct this seems like a Xamarin issue, please be sure to report it in our repo for triage. Thanks!

**Comment by Cfun1** [comment]
@LyalinDotCom Thanks for clarification, (It is already there) I will ask to be reopened https://github.com/xamarin/Xamarin.Forms/issues/12441

**Comment by JeanRoca** [comment]
Closing as duplicate in Xamarin.Forms repo.
