### ISSUE TITLE
Compositor Lines have a strange color with StrokeThickness=1

### ISSUE THREAD

**Issue by zed220** [microsoft/microsoft-ui-xaml#3601]
**Describe the bug**
Compositor Lines have strange color and stroke thickness with StrokeThickness=1. Also, lines are blurry with odd StrokeThickness.
I have created two crossed lines with StrokeThickness=1 and the crossed pixel has the wrong color (lines at all have the wrong color too). I have attached an image.

**Steps to reproduce the bug**
Create two crossed lines via Compositor with StrokeThickness=1. Set color like Color.FromArgb(255, 65, 65, 65).

**Expected behavior**
Line with StrokeThickness=1 must have 1 stroke thickness. It must have the right color. Crossed pixels must look equals to other line parts.

**Screenshots**
![image](https://user-images.githubusercontent.com/7091626/98946770-5b320100-2505-11eb-9dfd-6244e9dbf421.png)
Zoomed
![image](https://user-images.githubusercontent.com/7091626/98947240-00e57000-2506-11eb-948d-bc553fa012b0.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
I have attached an example project.
[App25.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5530906/App25.zip)

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by StephenLPeters** [comment]
@gegao18 FYI

**Comment by BorzillaR** [comment]
Its still reproduced in Preview 3.
Updated project:
[CompositorLinesBlury.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5567763/CompositorLinesBlury.zip)

**Comment by codendone** [comment]
I see the same behavior with OS XAML+Composition. I tried with simple 100% scaling to avoid any effects from scaling, and with the element set to HorizontalAlignment="Left" VerticalAlignment="Top" to avoid any pixel alignment issues.
