### ISSUE TITLE
Windows.UI.Input.PointerPoint.Timestamp is unreliable on Surface Pro 7 - drifting away from QPC during gesture

### ISSUE THREAD

**Issue by eugenegff** [microsoft/microsoft-ui-xaml#3606]
Pointer messages can be delivered faster than they are processed by application. It's natural to try to handle this problem by ignoring late PointerMoved events, so that things "stick to the fingers". Win32 has GetMessageTime+GetTickCount pair for this, macOS has NSEvent.timestamp, iOS has UIEvent.timestamp. UWP has only Windows.UI.Input.PointerPoint.Timestamp.

PointerPoint.Timestamp is always equal to QueryPerformanceCounter() converted to microseconds at the start of the gesture (i.e. PointerPressed), but during the gesture on Surface Pro 7 timestamps drifts away from QPC values as if digitizer clock is 5% slower than QPC clock. This makes fresh events to appear as late very soon. PointerPoint.Timestamp resync to QPC value at the start of the next gesture, and start to drift again.

We need either reliable PointerPoint.Timestamp or ability to call GetMessageTime() in UWP apps.

P.S. It's definitely the wrong project to file such bugreport, but it is the closest that I can find.

**Comment by kmgallahan** [comment]
> P.S. It's definitely the wrong project to file such bugreport, but it is the closest that I can find.

[ProjectReunion](url) @ranjeshj @stevewri ?

**Comment by eugenegff** [comment]
The problem occurs only for finger, not for mouse. Here is the log where DeliveryDelay calculated as (Timestamp - QPC) and DeliveryDelay2 as (GetTickCount  - GetMessageTime). Unfortunately code with GetMessageTime does not pass WACK checks.

TS = 64758185353, DeliveryDelay = 6497, DeliveryDelay2 = 0
TS = 64758195353, DeliveryDelay = 6440, DeliveryDelay2 = 0
TS = 64758204353, DeliveryDelay = 7647, DeliveryDelay2 = 0
TS = 64758214353, DeliveryDelay = 7211, DeliveryDelay2 = 0
TS = 64758223353, DeliveryDelay = 8718, DeliveryDelay2 = 16000
TS = 64758233353, DeliveryDelay = 8640, DeliveryDelay2 = 0
TS = 64758242353, DeliveryDelay = 9650, DeliveryDelay2 = 0
TS = 64758252353, DeliveryDelay = 9666, DeliveryDelay2 = 0
TS = 64758261353, DeliveryDelay = 10268, DeliveryDelay2 = 0
TS = 64758271353, DeliveryDelay = 10568, DeliveryDelay2 = 0
TS = 64758280353, DeliveryDelay = 11525, DeliveryDelay2 = 0
TS = 64758290353, DeliveryDelay = 11761, DeliveryDelay2 = 0
TS = 64758299353, DeliveryDelay = 12210, DeliveryDelay2 = 0
TS = 64758309353, DeliveryDelay = 12311, DeliveryDelay2 = 0
TS = 64758318353, DeliveryDelay = 13530, DeliveryDelay2 = 0
TS = 64758328353, DeliveryDelay = 13698, DeliveryDelay2 = 0
TS = 64758337353, DeliveryDelay = 14513, DeliveryDelay2 = 0
TS = 64758347353, DeliveryDelay = 16087, DeliveryDelay2 = 0
TS = 64758375353, DeliveryDelay = 15111, DeliveryDelay2 = 31000
TS = 64758413353, DeliveryDelay = 21079, DeliveryDelay2 = 47000
TS = 64758423353, DeliveryDelay = 22020, DeliveryDelay2 = 0
TS = 64758451353, DeliveryDelay = 27123, DeliveryDelay2 = 15000
TS = 64758461353, DeliveryDelay = 21064, DeliveryDelay2 = 16000
TS = 64758499353, DeliveryDelay = 27961, DeliveryDelay2 = 31000
TS = 64758537353, DeliveryDelay = 33046, DeliveryDelay2 = 31000
TS = 64758546353, DeliveryDelay = 30814, DeliveryDelay2 = 16000
TS = 64758584353, DeliveryDelay = 35958, DeliveryDelay2 = 31000
TS = 64758594353, DeliveryDelay = 29927, DeliveryDelay2 = 16000
TS = 64758603353, DeliveryDelay = 28142, DeliveryDelay2 = 0
TS = 64758641353, DeliveryDelay = 38932, DeliveryDelay2 = 32000
TS = 64758689353, DeliveryDelay = 41822, DeliveryDelay2 = 62000
TS = 64758698353, DeliveryDelay = 40400, DeliveryDelay2 = 16000
TS = 64758736353, DeliveryDelay = 43405, DeliveryDelay2 = 31000
TS = 64758746353, DeliveryDelay = 40729, DeliveryDelay2 = 16000
TS = 64758755353, DeliveryDelay = 39538, DeliveryDelay2 = 0
TS = 64758765353, DeliveryDelay = 37575, DeliveryDelay2 = 0
TS = 64758793353, DeliveryDelay = 44962, DeliveryDelay2 = 31000
TS = 64758803353, DeliveryDelay = 38394, DeliveryDelay2 = 0
TS = 64758831353, DeliveryDelay = 46066, DeliveryDelay2 = 31000
TS = 64758841353, DeliveryDelay = 41933, DeliveryDelay2 = 0
TS = 64758869353, DeliveryDelay = 48803, DeliveryDelay2 = 32000
TS = 64758879353, DeliveryDelay = 44230, DeliveryDelay2 = 0
<skiped>
TS = 64766232353, DeliveryDelay = 416057, DeliveryDelay2 = 0
TS = 64766242353, DeliveryDelay = 414109, DeliveryDelay2 = 0
TS = 64766251353, DeliveryDelay = 413250, DeliveryDelay2 = 16000
TS = 64766280353, DeliveryDelay = 419192, DeliveryDelay2 = 31000
TS = 64766289353, DeliveryDelay = 414516, DeliveryDelay2 = 0
TS = 64766318353, DeliveryDelay = 424536, DeliveryDelay2 = 31000
TS = 64766327353, DeliveryDelay = 421893, DeliveryDelay2 = 16000
TS = 64766375353, DeliveryDelay = 421166, DeliveryDelay2 = 47000
TS = 64766384353, DeliveryDelay = 420097, DeliveryDelay2 = 0
TS = 64766413353, DeliveryDelay = 437968, DeliveryDelay2 = 31000

**Comment by StephenLPeters** [comment]
Pointer Point is owned by IXP right? @jeffstall is this your teams issue?

**Comment by feisu** [comment]
@eugenegff thanks for reporting the issue. Can you explain in more details what you are trying to do?

If app doesn't pick up messages quickly enough, touch messages will coalesce in the queue so app will always retrieve the latest touch event, with the option to get intermediate coalesced touch points. You can choose to ignore those coalesced points since they are not the latest.

Digitizer timer drift is definitely possible. I'll follow up with hardware team on whether this is in the normal range for SP7 or not. But it sounds like that's not the problem you are trying to solve.

**Comment by eugenegff** [comment]
> @eugenegff thanks for reporting the issue. Can you explain in more details what you are trying to do?
> 
> If app doesn't pick up messages quickly enough, touch messages will coalesce in the queue so app will always retrieve the latest touch event, with the option to get intermediate coalesced touch points. You can choose to ignore those coalesced points since they are not the latest.

I'm developer at[ Live Home 3D](https://www.livehome3d.com/) project, that was released in 2007 for Mac, in 2014 [for Win8.1](https://www.microsoft.com/en-us/p/live-interior-3d-free/9wzdncrfj165), in 2016 for Win10 as [UWP app](https://www.microsoft.com/store/apps/9pg2cxwtkvb1), and in 2019 for iOS. 

At late 2016 our application was mature enough, worked really well with mouse, pen and touch input on a range of platforms and test devices, including [Samsung Slate PC](https://www.slashgear.com/samsung-series-7-slate-pc-hands-on-03176816/) from Build 2011 conference. But on one test device, [ASUS ZenBook Flip UX360CA](https://www.asus.com/sg/Laptops/ASUS-ZenBook-Flip-UX360CA/) 2-in-1 convertible touch input was extremely laggy, while mouse input was quite responsive. Investigation shows that on this device PointerMoved events from fingers were sent to us at 100Hz rate, rather than typical 60Hz rate as on other devices, and this happens on relatively weak passively cooled CPU. Those events were not coalesced, with dragging some item by circle in our app I was able to remove hand from touch screen and then see the dragged item does two more laps while catching up. According to version control system, we introduced code for skipping 'too late' PointerMoved events at Nov 2016, and with it dragged items 'sticks to the fingertips'. 'Too late event' was defined as PointerMoved event having timestamp earlier than (current timestamp - 1/60s). Other, faster hardware benefited from this 'throttling' too, dragging became much more responsive on devices that were not considered as laggy before. That code worked inside Live Home 3D for 4 years, ported to other platforms, and was removed on Windows several days ago due to the unreliable timestamps on Surface Pro 7.

I suppose that PointerMoved coalescing machinery is implemented on WM_POINTERMOVE or lower layer, and probably does not coalesce events that are separated by message of other type, otherwise not all events would be delivered in chronological order. Quite possible that desktop composition that happens at 60Hz rate sends some messages to our application, or there are artificial limit on timespan of coalescing, as WM_POINTERMOVE messages should then be routed from thread input queue to corresponding HWNDs, and all coalesced event are routed as single message to single HWND. All of that is my speculation, measured fact was that we typically got PointerMoved at ~60Hz rate, on some hardware at >100Hz, and there are no documented restriction on the this rate.

**Comment by feisu** [comment]
For the scenario you described, you can rely on Windows' coalescing feature. The internal pointer messages are coalesced if they are the same type and when app retrieves a pointer move, it will be the latest one so app has a chance to catch up if it falls behind momentarily. Though Windows doesn't artificially throttle 100Hz touch input down to 60Hz. If app is fast, it can receive each one of those input events. I also want to mentioned that gaming mouse can be super fast, like >1000Hz. Windows does coalescing for mouse as well. So your app is likely OK but you may still want to test high frequency mouse on your app.
