### ISSUE TITLE
Error when trying to create a new win32 WinUI project

### ISSUE THREAD

**Issue by dylech30th** [microsoft/microsoft-ui-xaml#3610]
I'm trying to try WinUI 3 preview-2 by following this [article](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/), but when I created the project, it shows that "CS0234: The type or namespace 'UI' does not exist in the namespace 'Microsoft'" and all the namespaces and XAML controls are unavailable (including FCL namespaces such as `System` where I showed below). There're both x86 and x64 version of .NET 5 preview-5 installed on my computer (However I specified the default SDK to x64 version in global.json otherwise VS will use the .NET 5.0.100) and my Windows 10 version is Windows 10 20H2 (19042.572), it was considered as a Nuget problem at first but when I try to run `dotnet restore` it follows "error NETSDK1083: The specified RuntimeIdentifier 'win-AnyCPU' is not recognized.", after then I switch the restore option to `/p: Platform=x64` and seems it has been restored successfully, but the problem is still there
![image](https://user-images.githubusercontent.com/31894334/99157836-94d25a00-2707-11eb-8fbe-eebf29120c11.png)
![image](https://user-images.githubusercontent.com/31894334/99158049-86853d80-2709-11eb-99b4-14978c33c8df.png)

**Comment by huoyaoyuan** [comment]
WinUI 3 Preview 2 is only supported by .NET 5 Preview 5~7. Please wait for Preview 3 at next week.

**Comment by dylech30th** [comment]
I am indeed using preview 5

**Comment by huoyaoyuan** [comment]
As I tried, it must be used with the combination of SDK Preview 5~7 and VS16.7 . VS16.8 won't work.

**Comment by StephenLPeters** [comment]
That's correct. Preview 3 wont have these limitations but for preview 2 you need to use SDK Preview 5~7 and VS16.7
