### ISSUE TITLE
Access Violation (Null Pointer Dereferenced) in Windows.UI.Xaml.dll

### ISSUE THREAD

**Issue by solocle** [microsoft/microsoft-ui-xaml#3612]
**Describe the bug**
Combo Box crashes application

**Steps to reproduce the bug**
Click multiple times on a combo box.
TODO - this only happens with some combo boxes, so it'll take time to come up with a repro app.

**Expected behavior**
Combo box keeps selecting, not a crash!

**Screenshots**

**Version Info**
Windows 10 version 1903
SDK - 10.0.18362.0

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Stack trace:

Exception thrown at 0x00007FF9AFFAEADD (Windows.UI.Xaml.dll) in AviGui.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

>	Windows.UI.Xaml.dll!ElementGestureTracker::ProcessPointerInformation(const InputMessage & msg, Windows::UI::Input::IPointerPointStatics * const pointerPointStatics) Line 711	C++
 	Windows.UI.Xaml.dll!ElementGestureTracker::ProcessPointerMessage(const InputMessage & msg, Windows::UI::Input::IPointerPointStatics * const pointerPointStatics) Line 91	C++
 	Windows.UI.Xaml.dll!CInputServices::ProcessPointerMessagesWithInteractionEngine(unsigned int pMsg, InputMessage * pInteractionElement, CUIElement * pManipulationElement, CUIElement * bIgnoreManipulationElement, unsigned int pInteractionContext, ElementGestureTracker * bForceDisableGesture, unsigned int) Line 1992	C++
 	Windows.UI.Xaml.dll!CInputServices::ProcessInteractionPointerMessages(unsigned int pointerId, InputMessage * pMsg) Line 1758	C++
 	Windows.UI.Xaml.dll!ContentRootInput::PointerInputProcessor::ProcessPointerInput(InputMessage * pMsg, int * handled) Line 716	C++
 	Windows.UI.Xaml.dll!CInputServices::ProcessInput(InputMessage * pMsg, CContentRoot * contentRoot, int * handled) Line 887	C++
 	Windows.UI.Xaml.dll!CCoreServices::ProcessInput(InputMessage * pMessage, CContentRoot * contentRoot, int * fHandled) Line 991	C++
 	Windows.UI.Xaml.dll!CXcpBrowserHost::HandleInputMessage(unsigned int uMsg, MsgPacket * pMsgPack, CContentRoot * contentRoot, bool & fHandled) Line 1411	C++
 	Windows.UI.Xaml.dll!CJupiterControl::HandlePointerMessage(unsigned int uMsg, unsigned __int64 wParam, __int64 lParam, CContentRoot * contentRoot, Windows::UI::Input::IPointerPoint * pointerPoint, Windows::UI::Core::IPointerEventArgs * pointerArgs) Line 750	C++
 	Windows.UI.Xaml.dll!CJupiterControl::ForwardWindowedPopupMessageToJupiterWindow(HWND__ * window, unsigned int message, unsigned __int64 wParam, __int64 lParam, CContentRoot * contentRoot) Line 1191	C++
 	[Inline Frame] Windows.UI.Xaml.dll!DirectUI::DXamlCore::ForwardWindowedPopupMessageToJupiterWindow(HWND__ *) Line 4379	C++
 	Windows.UI.Xaml.dll!DirectUI::DXamlCore::ForwardWindowedPopupMessageToJupiterWindow(HWND__ * window, unsigned int message, unsigned __int64 wParam, __int64 lParam, CContentRoot * contentRoot, __int64 * pResult) Line 4346	C++
 	[Inline Frame] Windows.UI.Xaml.dll!CFxCallbacks::Core_ForwardWindowedPopupMessageToJupiterWindow(HWND__ * contentRoot, unsigned int) Line 1152	C++
 	Windows.UI.Xaml.dll!CPopup::HandleWindowedPopupMessage(HWND__ * hwnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 1729	C++
 	Windows.UI.Xaml.dll!CPopup::WindowedPopupWindowProc(HWND__ * hwnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 1702	C++
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessMessage(bool bDrainQueue, bool * pbWindowMessagesProcessed, bool * pbInvokeItemProcessed) Line 327	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal(bool bRunAlwaysOnce, void * hEventWait) Line 1953	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessEvents(Windows::UI::Core::CoreProcessEventsOption options) Line 599	C++
 	Windows.UI.Xaml.dll!CJupiterWindow::RunCoreWindowMessageLoop() Line 1233	C++
 	[Inline Frame] Windows.UI.Xaml.dll!CJupiterControl::RunMessageLoop() Line 1065	C++
 	Windows.UI.Xaml.dll!DirectUI::DXamlCore::RunMessageLoop() Line 2453	C++
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run()	Unknown
 	twinapi.appcore.dll!<lambda>(void)()	Unknown
 	SHCore.dll!_WrapperThreadProc()	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

**Comment by StephenLPeters** [comment]
@codendone This looks like an issue with windowed popups to me, based on the call stack. That's rendering right? @solocle That repro app would be really useful, the call stack isn't very helpful

**Comment by codendone** [comment]
The location of the crash according to the callstack suggests some possible reentrancy which may have left things in a bad state. If the repro steps include selecting a different value in the combo box, the code responding to selection changed may be calling an API which allows reentrancy.

The best option to get more information would be to grab a Time Travel trace. To do that, launch the app without a debugger, navigate the UI until the combo box is visible, then attach to the process with WinDbg Preview using the Time Travel Debugging option (more info [here)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/windbg-user-mode-preview#attach-to-a-process), and perform the repro. Share the trace it captures and I can investigate that further.

**Comment by solocle** [comment]
Hi, I wasn't able to get WinDbg to do TTD with our pure UWP configuration, but the Xaml Islands configuration I was able to get to attach, and replicate the bug. 

How do I best share the trace with you? Github is complaining that 700MB is rather bigger than their 10MB limit.

**Comment by Blinue** [comment]
Suffering with the same issue. Here's a minimal repro project: 
[XamlIslandsCpp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10671694/XamlIslandsCpp.zip)

![动画](https://user-images.githubusercontent.com/34770031/217153430-940beca2-b333-47a1-a5c3-238ab8e3aca4.gif)
OS: Win10 22H2
