### ISSUE TITLE
MapControl with default Style crashes UWP app

### ISSUE THREAD

**Issue by DaanTul** [microsoft/microsoft-ui-xaml#3616]
**Describe the bug**
Showing MapControl with default Style crashes UWP app.

Style="Aerial"

**Steps to reproduce the bug**
1. Add MapControl to xaml page
2. Open page

**Expected behavior**
App doesn't crash

Multiple Versions

**Comment by tipa** [comment]
There's already an issue for this here: https://github.com/microsoft/microsoft-ui-xaml/issues/3614
