### ISSUE TITLE
Bug: WinUI-2.5: Accessibility: [MAS1.4.4]: Action/Informational link text is getting truncated in Infobar tab content when TextScaling is applied to 200%

### ISSUE THREAD

**Issue by v-amnat** [microsoft/microsoft-ui-xaml#3617]
**Tags**
Accessibility, A11yFT,  A11yMAS, A11yMediumImpact, MAS1.4.4, Large Text, Sev3, WinUI-2.5, Win32, Wipro 

**User Impact**
People with Low vision are not able to identify the Action button/Informational link in Infobar canvas area.

**Steps to reproduce the bug**
Settings-->Display-->Set TextScaling to 200%

Launch the WinUI_2.5_TestApp

1. Go to 'Infobar' tab and activate it.
2. For 2nd type of Inforbar, set Action button to Button and Hyperlink
3. In Infobar, Action/Informational controls
4. But in Textscaling 200%, these two controls(Action/Informational) truncated.

**Expected behavior**
Action/Informational link text should visible properly in Infobar tab content, when TextScaling is applied to 200%.
 
**Actual behavior**
Action/Informational link text is getting truncated in Infobar tab content.
 
**Screenshots**
 
 
![image](https://user-images.githubusercontent.com/74585893/99396172-6b801c80-2907-11eb-9b4a-7b93557a54ca.png)

![image](https://user-images.githubusercontent.com/74585893/99396253-83f03700-2907-11eb-9429-29b2ba915397.png)

Version Info
Win32
Windows OS Version: Windows 10
App: WinUI_2.5_TestApp

**Comment by ranjeshj** [comment]
The height is [fixed to 24](https://github.com/microsoft/microsoft-ui-xaml/blob/fa324b3433c5352bba719d866e9e1e6f97dca250/dev/InfoBar/InfoBar_themeresources.xaml#L103) which is what is causing it. If we remove it button will by default get 32 pixels. @gabbybilka Is there a requirement to keep the height 24 ?

**Comment by gabbybilka** [comment]
The height of the button is 24px (compact styling) as the control height itself is only 40px so we needed ample spacing. We wanted to keep the control vertically short as it is likely to be horizontally long to reduce visual impact of what is often just a single line of text. We're currently looking into increasing the height to 48px as part of a styling update anyways. The designs with the increased 48px height have 30px buttons, let me confirm the 30 vs 32px difference.

Would we want to move forward with the default button height and 48px control height for this release then?

**Comment by ranjeshj** [comment]
ok. we can just remove the Height on the buttons and hyperlink then and let it grow based on text scaling.

**Comment by chingucoding** [comment]
I would like to work on this.

**Comment by gabbybilka** [comment]
Thank you!
