### ISSUE TITLE
Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml'.

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#3625]
I just created a Blank WinUI 3 preview 2 project and hit F5 , encountered this exception :

Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml'. [Line: 9 Position: 40]

**Csproj:**

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.18362</TargetFramework>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
    <RootNamespace>Weather.History.WinUI3</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VCRTForwarders.140" Version="1.0.7" />
    <PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview3.201113.0" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
</Project>
```

**The generated file :** 

![image](https://user-images.githubusercontent.com/43340959/99428785-60c58780-2907-11eb-9560-76e4a795eaad.png)

**Windows Version:** 

![image](https://user-images.githubusercontent.com/43340959/99428679-4095c880-2907-11eb-90b2-783b1746e33c.png)

**Comment by Austin-Lamb** [comment]
I've seen some folks hit this when leaving the application project as the startup project - make sure you set the Packaging project as the startup project as Preview 3 only supports packaged apps.

**Comment by sigmarsson** [comment]
Yeah maybe it would be good to strip off this dependency because running the makeappx.exe in the CI may be regular. Maybe people have already the msix comprising a WPF. They wish to try WinUI for size maybe without packaging a piece of migrated software.

**Comment by BrunoBlanes** [comment]
Why aren't both projects united? Why can't the package be part of the Desktop application?

**Comment by BrunoBlanes** [comment]
Also, is package `Microsoft.VCRTForwarders.140` going to be a thing in the final version?

**Comment by sigmarsson** [comment]
No. Dev -> QA ->  ... ->  Packaging, Deployment. Since dev & deployment aren't adjacent in sw life cycle therefore must not incorporate. That is simply a weird dependency that due to the absence of the shipping package, you cannot debug.

**Comment by CoderTyn** [comment]
> Yeah maybe it would be good to strip off this dependency because running the makeappx.exe in the CI may be regular. Maybe people have already the msix comprising a WPF. They wish to try WinUI for size maybe without packaging a piece of migrated software.

I can't agree more.
