### ISSUE TITLE
Do you consider rename this repo as WinUI? 

### ISSUE THREAD

**Issue by DEVBOX10** [microsoft/microsoft-ui-xaml#3628]
Hello.
I would like to ask these questions.
Do you consider rename this repo as WinUI? 
And will it use the name of package of the library like this "Microsoft.UI.Xaml 3.x" after the release WinUI 3 too?

When I have got some news about WinUI, it always makes me confuse the name of this repo and future roadmap.
This repo or WinUI will represents only XAML?
And between WinUI and WinForm will be as separate model?
Or offer another next level of unified and mixed composition approaches possible besides MAUI?

I wish to hear some hints at least as you can share till now or can keep update such news too.
Thanks.

**Comment by robloo** [comment]
In the past I know it was mentioned that a completely new repo might be created for the open-source WinUI. Then this would become a sub-repo for just the controls. Not sure how much further that line of thinking progressing inside Microsoft though.

Also see: https://github.com/microsoft/microsoft-ui-xaml/issues/1908

**Comment by niels9001** [comment]
Naming is a bit messy really. @WindowsUI on Twitter, WinUI is the name and NuGet packages / this repo is Microsoft.UI.Xaml. i understand why, but it doesn't help :-)

**Comment by ScriptBox21** [comment]
Thanks for the comments.
Well, as for me, WinUI the name and some parts of documentation looks like represents its more broad concept can be total approach for the UI on Windows at least.
It may not ready to share to the public, how can be evolved include WinForm too.
At the moment, by .NET 6 roadmap, I hope we could see MAUI, especially Blazor style model which can adopt CSS styling, web-friendly model as core features also could be arrived well with WinUI.
And also wish WinUI not only represents XAML model, I'm not sure that makes sense for the features in coming releases.

**Comment by charlesroddie** [comment]
Related to https://github.com/microsoft/microsoft-ui-xaml/issues/392

**Comment by ScriptBox21** [comment]
Thanks for the comment.
I could read that #392 issues.
It would be better to offer more details and some changes in coming schedule.
