### ISSUE TITLE
Cannot build WinUI3 Preview3 desktop package project in fresh installed VS

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#3635]
Originally posted at https://github.com/microsoft/microsoft-ui-xaml/issues/3620#issuecomment-729466735 by @VagueGit .

*This issue involves machine-wide shared component. You may need to reproduce it in a new VM.*

I have two dev machines. One can build the preview 3 template project, one can't. The error is `Can't find SDK reference Microsoft.VCLibs and Microsoft.VCLibs.Desktop`.

The **working** machine has VS installation upgraded since 16.0. It's using electron-based VSInstaller UI.
The **not working** machine has VS fresh installed for 16.8 and 16.9P1. It's using WPF-based VSInstaller UI.

The newly installed machine misses unversioned `Microsoft.VCLibs` and `Microsoft.VCLibs.Desktop` here.
![image](https://user-images.githubusercontent.com/5644458/99527197-612d5380-29d7-11eb-884f-77bcb5c7832d.png)

After trying to modify the installation, I find that C++ UWP tools workload will bring `Microsoft.VCLibs.Desktop`. But nothing I tried brings `Microsoft.VCLibs`.

This may be a VS installer issue.

**Update:** Repairing the VS 16.9 instance fixes this for me.

**Comment by get-flat** [comment]
https://developercommunity.visualstudio.com/content/problem/1256345/uwp-build-fails-after-update-to-1682-error-msb3774.html

**Comment by aoshiwik** [comment]
![settings](https://user-images.githubusercontent.com/5297420/99559040-37454400-2979-11eb-8027-586c1f390933.PNG)

**Comment by placasse** [comment]
Thanks aoshiwik. This is effectively part of the [documentation](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/) for WinUI 3. Unfortunately, it was already selected in my installation
![image](https://user-images.githubusercontent.com/3594016/99560030-6799dc00-2993-11eb-8058-e79f0c0dbb6e.png)

There is a manual workaround, I found 
C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs
and
C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop
on another computer not infected by Visual Studio 16.9 Preview.
I copied those files on my disk to fix the issue.

**Comment by huoyaoyuan** [comment]
@aoshiwik as I mentioned, this brings VCLibs.Desktop, but not VCLibs for me.

**Comment by llongley** [comment]
[This looks like an issue with the VS installation](https://developercommunity2.visualstudio.com/t/UWP-build-fails-after-update-to-1682--/1256345?preview=true).  A workaround for now that seems to work for some people is to grab the directory at C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs from an install of an earlier version of VS and copy that over (and similarly for Microsoft.VCLibs.Desktop).

**Comment by chanallenk** [comment]
Anybody have a copy of the binaries in that folder for those who don't have another machine?

**Comment by placasse** [comment]
Here is the two folders I took from my PC
https://github.com/placasse/MicrosoftSDKs

**Comment by thomasclaudiushuber** [comment]
> @aoshiwik as I mentioned, this brings VCLibs.Desktop, but not VCLibs for me.

After modifying VS 2019 Preview and including the C++ options mentioned above, it still didn't work for me, the Microsoft.VCLibs folder was still missing, while Microsoft.VCLibs.Desktop was there.

Nnother repair of VS 2019 Preview after the modification brought also Microsoft.VCLibs to my machine.

**Comment by dotMorten** [comment]
This happened to me as well, and a repair didn't address it (using 16.8.0 at the time). I used the copy method as well to resolve it and didn't think much more of it - seeing this now, it's clear it's a common issue.

**Comment by fabiant3** [comment]
Closing as no new reports have surfaced. If reopen please provide a recent repro.
