### ISSUE TITLE
WinUI 3 preview c# blank desktop app exception on launch "Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml'"

### ISSUE THREAD

**Issue by aoshiwik** [microsoft/microsoft-ui-xaml#3638]
created a new c# desktop project from the template, no modifications made, getting an exception on launch. using nuget package 3.0.0-preview3.201113.0, exception is not thrown after removing the line "XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />" from the app.xaml.

![exception](https://user-images.githubusercontent.com/5297420/99559486-b2a6f580-2979-11eb-913e-98ca82f9e869.PNG)

**Comment by ranjeshj** [comment]
@aoshiwik Do you see two projects in your solution ? Do you have the start up project as the package ?

**Comment by aoshiwik** [comment]
Setting the package as the startup project fixed the issue.
