### ISSUE TITLE
WinUI 3: Clicking on a ToggleSplitButton causes the application to crash

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#3641]
**Describe the bug**

Clicking on a ToggleSplitButton causes the app to crash with the following debug message:

onecoreuap\windows\moderncore\inputv2\inputhost\inside\lifted\compositioncontent.cpp(971)\Microsoft.UI.Input.dll!18430561: (caller: 18431213) FailFast(1) tid(738) 8000FFFF

**Steps to reproduce the bug**

1. Add a ToggleSplitButton
2. Click on it

**Expected behavior**

No crash

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by MikeHillberg** [comment]
@lhak, thanks for reporting this, I think we found the issue.

**Comment by anawishnoff** [comment]
This bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!

**Comment by lhak** [comment]
Works fine in preview 4. Thank you!
