### ISSUE TITLE
2.5RC: Hierarchical NavigationView hides nested items when used in Xaml Islands

### ISSUE THREAD

**Issue by DHowett** [microsoft/microsoft-ui-xaml#3642]
**Describe the bug**

A hierarchical navigation view dropped in a Xaml island will only display the first sub-item for any item.

**Steps to reproduce the bug**

1. Host a NavigationView in a Xaml island
2. Add multiple sub-items to a toplevel item

**Expected behavior**
1. They all appear (as they do in a non-island)

**Screenshots**

![image](https://user-images.githubusercontent.com/189190/99579571-328d8980-2993-11eb-81ca-04ad517193c6.png)

![image](https://user-images.githubusercontent.com/189190/99579585-38836a80-2993-11eb-8487-10711ffe340c.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.5 rc1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This was reduced from a [terminal](https://github.com/microsoft/terminal) reproducer.

**Comment by DHowett** [comment]
This does not repro outside of islands.

The behavior changes if you use the nav view in collapsed mode and open the flyout:

![image](https://user-images.githubusercontent.com/189190/99581169-3f12e180-2995-11eb-9f6f-25d6cf2ee12b.png)

![image](https://user-images.githubusercontent.com/189190/99581183-42a66880-2995-11eb-90da-748a8347ebf1.png)

after this, "Two" appears in the list:

![image](https://user-images.githubusercontent.com/189190/99581205-4b973a00-2995-11eb-808d-b681bc205a3e.png)

Three, four, five, six remain cut off.

**Comment by ranjeshj** [comment]
@DHowett This is a known issue with effective viewport being broken in xaml islands - #2102
