### ISSUE TITLE
Microsoft.UI.Colors throwing TargetInvocationException

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#3643]
Since I updated to version 3.0.0-preview3.201113.0, I'm getting the following exception when accessing Microsoft.UI.Colors.Red static property

> System.Reflection.TargetInvocationException
>   HResult=0x80131604
>   Message=Exception has been thrown by the target of an invocation.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
>    at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
>    at System.Activator.CreateInstance[T]()
>    at WinRT.WeakLazy`1.get_Value()
>    at Microsoft.UI.Colors._IColorsStatics.get_Instance()
>    at Microsoft.UI.Colors.get_Red()
>    at InputHandling.MainWindow..ctor() in C:\Projects\GrapeCity\c1-netcore\WinUI\Samples\Core\InputHandling\InputHandling\MainWindow.xaml.cs:line 34
>    at InputHandling.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Projects\GrapeCity\c1-netcore\WinUI\Samples\Core\InputHandling\InputHandling\App.xaml.cs:line 31
>    at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
>    at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_1(IntPtr thisPtr, IntPtr args)
> 
>   This exception was originally thrown at this call stack:
>     System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int)
>     WinRT.BaseActivationFactory.BaseActivationFactory(string, string)
>     Microsoft.UI.Colors._IColorsStatics._IColorsStatics()
> 
> Inner Exception 1:
> COMException: ClassFactory cannot supply requested class (0x80040111 (CLASS_E_CLASSNOTAVAILABLE))
>

**Comment by ranjeshj** [comment]
@Scottj1s as FYI

**Comment by stevenbrix** [comment]
@arivoir, this can happen if you update a preview2 project to preview3. There are some files that are in the `build` folder of the packaging project that have changed and need to be updated.

You can copy them over from a new preview3 project and that should unblock you

**Comment by arivoir** [comment]
Copying the "build" folder worked. Thanks for the workaround!
