### ISSUE TITLE
Designer issue

### ISSUE THREAD

**Issue by santhoshkumarmk** [microsoft/microsoft-ui-xaml#3644]
Why designer is not working in winui 3.0 framework.

**Comment by huoyaoyuan** [comment]
I remember it worked for me yesterday, but currently it doesn't work for me on both machines.

**Comment by santhoshkumarmk** [comment]
we need proper solution for this . Any body can help one this ?

**Comment by santhoshkumarmk** [comment]
I working on Blankapp, Packaged(WINUI in Desktop)

**Comment by anawishnoff** [comment]
Hi @santhoshkumarmk, are you talking about the XAML Designer in Visual Studio? This is not supported in Preview 3. More info in issue #3656
