### ISSUE TITLE
Click PrimaryCommandButton in CommandBarFlyout will not close whole flyout

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#3647]
**Describe the bug**
![image](https://user-images.githubusercontent.com/42038175/99636252-28948500-2a7e-11eb-827c-b8d5586ff623.png)

**Steps to reproduce the bug**

1. Click any primarycommandbutton

**Expected behavior**
Should close whole commandbarflyout.

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.5.0-prerelease.201027002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
I think #3098 will resolve this issue.  @chingucoding and @adambarlow ?

**Comment by chingucoding** [comment]
@StephenLPeters Yes, this will be fixed with #3098 (also updated description of that PR to close this issue on merge).
