### ISSUE TITLE
Setting tooltip using attached method syntax in resw no longer works in WinUI 3 Preview 3

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#3649]
**Describe the bug**
Setting tooltip using attached method syntax in resw no longer works in WinUI 3 Preview 3

**Steps to reproduce the bug**
1. Start with WinUI 3 Desktop app template

2. Declare some UI element with Uid:
```xaml
<Button x:Uid="button1" />
```

3. Create `Resources.resw` under `Strings\en`, and add a `<PRIResource Include=Strings\**\*.resw` to the project.

4. Add tooltip in the resource file. According to [UWP doc](https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest#refer-to-a-string-resource-identifier-from-xaml), the syntax for the key should be `button1.[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip`.

5. Run the app.
The app will fail with `XamlParseException`.

**Expected behavior**
The app should work with tooltip set from the localized resource.
It worked in preview 2. This is a regression in preview 3.

**Version Info**

NuGet package version: 

Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 20H2(19042)              | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by huoyaoyuan** [comment]
@roxk I've also met the tooltip issue here 

The current workaround is explicitly define a `ToolTip` element:

```xaml
<Button>
    <ToolTipService.ToolTip>
        <ToolTip x:Uid="button1ToolTip" />
    </ToolTipService.ToolTip>
</Button>
```

and set `button1ToolTip.Content` in resources.

**Comment by roxk** [comment]
@huoyaoyuan That was speedy :D I'm here to report that while the workaround fixes the exception, tooltip would not actually show when the ui element is hovered.

**Comment by huoyaoyuan** [comment]
The workaround works for me. There may be other minor differences.

**Comment by roxk** [comment]
@huoyaoyuan I wasn't able to get tooltip to show, and out of curiosity I tried changing `XXXToolTip.Content` to `XXXToolTip.Text`, built the app, saw exception, then reverted back the change, and now _all_ tool tips are showing up😅 I don't know what's happening but at least things are working for me now. Hope it helps.

**Comment by StephenLPeters** [comment]
@fabiant3 FYI, the xaml markup exception makes me think its a markup issue rather than a tooltip one.

**Comment by alwu-msft** [comment]
@StephenLPeters In this specific case, that is likely as the parser is the one that interprets x:Uid, but in general that is not a safe assumption to make. "A XamlParseException occurred" is about as meaningful as "Something has happened" since the parser is often the outermost developer-visible layer of the framework; you need to examine the inner exception (whether it's a real exception, a stowed exception, or even just an error message that is only visible while debugging the framework) to determine the true root cause.

**Comment by huoyaoyuan** [comment]
@alwu-msft I got this message in Visual Studio output window:
```
onecoreuap\base\appmodel\statemanager\winrt\lib\windows.storage.applicationdatafactory.server.cpp(235)\Windows.Storage.ApplicationData.dll!00007FFD72EF83F3: (caller: 00007FFD72F087B3) ReturnHr(1) tid(695c) 8000000B 该操作尝试访问的数据超出了有效范围
```

**Comment by Elmarcotoro** [comment]
I was able to get working as @huoyaoyuan suggested.  However I get the below exception.  

`Exception thrown at 0x75D8A892 in [appName].exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0337E618.`

If I click continue in VS the app initialises and I can see the tooltip.

This is a more verbose exercise.  I would rather be explicit in the resw resource, especially where a control may have two or more resources. E.g. MyButton.Content, MyButton.ToolTipService.ToolTip.

P.s. I have a UWP app that works with the following statement in the resw. "Control.ToolTipService.ToolTip".

**Comment by sibille** [comment]
This issue seems to be solved after updating to Project Reunion 0.5 Preview

**Comment by huoyaoyuan** [comment]
Yes, confirmed.

**Comment by Maddog2412** [comment]
I got new Problems in my App.
When I try to create a ToolTip and an Icon as Content, so 

`<Button x:Name="BtnTest" x:Uid="BtnTest"
            Width="45" Height="25"
            Margin="5,40,0,0">
            <ToolTipService.ToolTip>
                <ToolTip x:Uid="ProjToolTip"/>
            </ToolTipService.ToolTip>
            <Button.Content>
                <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE712;" />
            </Button.Content>
</Button>`

With
`<data name="ProjToolTip.Content" xml:space="preserve">
    <value>Set the File Path for the Project File</value>
  </data>`

I does not Work for me. A ToolTip appears, but without content. Anyone who maybe knows, how to fix this issue?

NuGet package version:

Microsoft.WinUI.UI.Controls 7.1.2
WinUi3
Windows 10
Version 22H2(19045.2965)

For Dektop

Thanks for Help

**Comment by evelynwu-msft** [comment]
@Maddog2412 Please open a new issue to track the problem you're encountering. Thanks!
