### ISSUE TITLE
Setting an image source to a file in the app's directory causes a base.h not found exception

### ISSUE THREAD

**Issue by Spyromaniac31** [microsoft/microsoft-ui-xaml#3654]
**Describe the bug**
When the source of an Image control is set to a file in the app's directory, whether it's just "image.png" or "ms-appx:///image.png," the app crashes with a "base.h not found" exception.

**Steps to reproduce the bug**
1. Create a new WinUI in Desktop (C#) Project
2. Add an image to the app's directory
3. Add an Image control to MainWindow.xaml and set its source to "ImageName.png"
4. Run the app

**Expected behavior**
The image should load as normal and not cause an exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/55723056/99701298-8068c700-2a51-11eb-89c2-e4b45fde49c6.png)
![image](https://user-images.githubusercontent.com/55723056/99701654-f40ad400-2a51-11eb-81ee-b051c13d590f.png)

**Version Info**

NuGet package version: 
3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20257)              | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Is it possible that your resource path is wrong? I think by default the CS project name is appended to the resource name. If you want to see what exactly the name needs to be you can use the MakePri dump tool in the VS command line to dump the PRI file and see what the resource name is https://docs.microsoft.com/en-us/windows/uwp/app-resources/makepri-exe-command-options

**Comment by Spyromaniac31** [comment]
I dumped the PRI from the app and there was nothing there related to the images in the directory. Is that what I should be looking for? I'm not sure what I should be doing with the dumped contents of the PRI file.

**Comment by Spyromaniac31** [comment]
Strangely enough, after moving the image in and out of folders, adding and removing the slash at the start of the path, and experimenting with workarounds, the image started working. Even when I set the source to exactly what it was when the issue occurred, it worked fine. Sorry for the inconvinience.
