### ISSUE TITLE
Proposal:

### ISSUE THREAD

**Issue by palejana** [microsoft/microsoft-ui-xaml#3655]
# Proposal: [your title here] 

## Summary
i

## Rationale

* {First reason for why we should consider this proposal}
* {Second reason for why we should consider this proposal}
* {etc}

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by stevenbrix** [comment]
@palejana, welcome to WinUI :)

It looks like you accidentally opened this, so I'm going to close this out. Feel free to file a proposal for a feature you'd like to see!
