### ISSUE TITLE
WinUI3: Rotation in Manipulation events is wrong

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#3658]
**Describe the bug**
When using the ManipulationDelta event to track rotation changes, the values reported are way too large. Rotating your fingers reports a value exactly 180/Pi too large.

**Steps to reproduce the bug**
1. Add the following XAML to the view:
```xml
        <Border Background="Red" Width="300" Height="300" 
                ManipulationMode="All"
                ManipulationStarted="Border_ManipulationStarted"
                ManipulationDelta="Border_ManipulationDelta"
                ManipulationCompleted="Border_ManipulationCompleted">
            <TextBlock Text="Rotate me" x:Name="status" Foreground="White" HorizontalAlignment="Center" VerticalAlignment="Center" />
        </Border>
```
2. Add the following code-behind:
```cs
        private double angle = 0;
        private void Border_ManipulationStarted(object sender, ManipulationStartedRoutedEventArgs e)
        {
            angle = 0;
            status.Text = "Begin";
        }

        private void Border_ManipulationDelta(object sender, ManipulationDeltaRoutedEventArgs e)
        {
            angle += e.Delta.Rotation;
            status.Text = $"Cumulative (sum of deltas): {angle}\nDelta: {e.Delta.Rotation}\nCumulative: {e.Cumulative.Rotation}";
        }

        private void Border_ManipulationCompleted(object sender, ManipulationCompletedRoutedEventArgs e)
        {
            status.Text += "\nCompleted!";
        }
```
3. Run the application on a touch screen, and rotate with two fingers over the red box.
4. Observe the values reported doesn't match what you're doing (all 3 values written are wrong of about 17-18 times larger than expected).

**Expected behavior**
Rotation values reported matches actual user input

**Screenshots**
![Untitled Project](https://user-images.githubusercontent.com/1378165/99719959-de050f80-2a61-11eb-9cb8-89de58d1d332.gif)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes (Surface Book 2 & Surface Go 1 |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by codendone** [comment]
Thanks for reporting. As you found, there is a place where we're incorrectly converting radians to degrees when the value was already in degrees.

**Comment by dotMorten** [comment]
@codendone Any update on this? Sounds like an easy fix, and some might consider this a breaking change down the line once it's v1.0

**Comment by codendone** [comment]
I agree, and I had hoped we'd get to this sooner. This is scheduled to be fixed for 0.8, and hopefully will be completed around the end of April.

**Comment by anawishnoff** [comment]
This has been fixed in the most recent release of WinUI 3 (Windows App SDK 0.8), so I'm closing this issue. Feel free to re-open if the issue still persists.

**Comment by dotMorten** [comment]
sorry forgot to close this when I confirmed the fix last week. Thank you!
