### ISSUE TITLE
Question: How can I edit the built-in control's theme

### ISSUE THREAD

**Issue by dylech30th** [microsoft/microsoft-ui-xaml#3659]
when developing UWP or WPF I can right-click on the control in the XAML designer and select "Edit theme", but WinUI 3 Preview 3 is apparently doesn't has a XAML designer yet, so what should I do when I want to change some details or layout of the built-in control(It could be any of them, not specifically someone)

**Comment by StephenLPeters** [comment]
@MikeHillberg I don't think we currently support the VisualStudio "Edit theme" button in winui 3 right now correct?

@dylech30th many of the Winui3 control templates are going to be the same or similar to the Winui 2 ones which are open source and can be found in this repo. Some of the controls are not included in this repo and then I would recommend using the Edit theme button in a regular UWP app to get the template.  Other than that I don't *think* there is a way to get the template.

**Comment by huoyaoyuan** [comment]
For built-in UWP controls, you can find the template themes at `C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.18362.0\Generic` .

**Comment by mdtauk** [comment]
> For built-in UWP controls, you can find the template themes at `C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.18362.0\Generic` .

Are these for the WinUI controls, or the Inbox Xaml controls?

**Comment by huoyaoyuan** [comment]
The inbox xaml controls.
