### ISSUE TITLE
Question: equivalent to NavigationRail in FluentDesign

### ISSUE THREAD

**Issue by Rogardo** [microsoft/microsoft-ui-xaml#3662]
I have a WPF programm that use a RailNavigation on the left like MS Teams and want to port it to WinUI3. 

What is the best/right way to get a navigation like this with WinUI/Fluent design?
In best case with the option of this little badges.
For programms with only a few pages this looks much better then the heavy NavigationView list

![image](https://user-images.githubusercontent.com/28587500/99768022-6936e180-2b04-11eb-8296-08e00c710f9c.png)

**Comment by mdtauk** [comment]
The **NavigationView** control is the WinUI Standard.

![image](https://user-images.githubusercontent.com/7389110/99768781-48b75900-2afd-11eb-9e9f-a4f9cf117215.png)

**Comment by Rogardo** [comment]
Ok, thank you for your quick response.
Than I have to build a UserControll for my portation

**Comment by robloo** [comment]
@Rogardo Yes, you might need to quickly make your own UserControl to get the same look as pictured. However, the NavigatiokView can be significantly customized. You can turn off the settings and hamburger button. You can also keep the sidebar from expanding to full size. I suspect you could actually get pretty close to what you want with NavigationView. It might be better to use NavigationView for your initial port and only write your own control if that fails.

**Comment by StephenLPeters** [comment]
I think with navigation view you can get very close to what teams has, some differences would include the selection icon being on the right in navigation view and the left in teams. Maybe some of the colors, and the badge which would be adressed in a future update when #2963 is resolved

**Comment by StephenLPeters** [comment]
Closing the issue but feel free to post more questions if you have them and I'll reopen
