### ISSUE TITLE
Setting attached property of custom enum type in code throws System.ArgumentException

### ISSUE THREAD

**Issue by s-beltz** [microsoft/microsoft-ui-xaml#3663]
**Describe the bug**
When creating a Style object in code and adding a setter for an attached property of custom enum type an System.ArgumentException is thrown. After changing the type of the attached property to Integer code works as expected.

**Steps to reproduce the bug**

1. Open attached WinUI 3 Desktop repro app.
2. The app will crash on startup in class MainWindow in the constructor.

[WinUI3Test 2020-11-20.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5574770/WinUI3Test.2020-11-20.zip)

**Expected behavior**
Attached properties should support custom enum types as in UWP.

**Code sample**

```
Style formSectionStyle = new Style {​​ TargetType = typeof(ContentPresenter) }​​;
formSectionStyle.Setters.Add(new Setter(ContentPresenter.HorizontalAlignmentProperty, HorizontalAlignment.Stretch));
// Works
formSectionStyle.Setters.Add(new Setter(FormLayout.VerticalSizingProperty, 1));
// Crashes
formSectionStyle.Setters.Add(new Setter(FormLayout.HorizontalSizingProperty, HorizontalSizingMode.AllColumns));

```
**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|   | Yes  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2020 Update (19042.630)            | Yes  |
| May 2020 Update (19041)            |   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@stevenbrix is this another cswinrt projection issue?

**Comment by stevenbrix** [comment]
Interesting, I'm not really sure. Does this repro in a uwp app?

**Comment by s-beltz** [comment]
> Interesting, I'm not really sure. Does this repro in a uwp app?

Hi @stevenbrix, no it doesn't repro in UWP. That works just fine.

**Comment by chrisglein** [comment]
If this did work with a classic UWP with inbox OS XAML then this could either be a WinUI3 regression or a cswinrt issue. @stevenbrix how do we resolve if this is a cswinrt issue?

**Comment by codendone** [comment]
This works on Project Reunion 0.5.5, presumably due to the new cswinrt in that release.
