### ISSUE TITLE
WinUI3: SurfaceImageSource seems to leak GPU memory

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#3665]
**Describe the bug**

I had previously recompiled win2d for winui 3 (see https://github.com/lhak/Win2D/tree/winui3) and already noticed this issue with preview 2. When using the CanvasControl (uses SurfaceImageSource), the GPU memory usage grows whenever it is resized. I do not see this behavior using win2d compiled for platform XAML. As I have not made any changes to this class (except the namespace change), this seems to be an internal winui issue.

**Steps to reproduce the bug**

1. Run the SimpleSample.uap project from the github repository mentioned above (use the winui3 branch)
2. Continously resize the app window and notice that the allocated GPU memory (in task manager) keeps growing

**Expected behavior**

With the default win2d code using platform XAML, this issue is not observed.

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by lhak** [comment]
This is still an issue in preview 4.

**Comment by lhak** [comment]
Still an issue in 0.8, especially in combination with win2d (CanvasControl).

**Comment by lhak** [comment]
I have added an updated repro project based on the newest winui and win2d releases. If you rapidly change the window size you can see this issue.

[Win2DMemoryTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7386742/Win2DMemoryTest.zip)

**Comment by lhak** [comment]
This is still not fixed over 2 years later and a blocking issue for me. I have updated the repro to automatically resize the control. Just run the application and monitor GPU memory usage. The repro also contains a UWP version that does not show this memory leak:

[Win2DMemoryTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10368906/Win2DMemoryTest.zip)

**Comment by ChewWorker** [comment]
@lhak I don't remember exactly why, but we had investigated and thought this was fixed. However, within the last month we found the repro still existed and have begun investigating. Expect regular updates as we are prioritizing this issue.

**Comment by getrou** [comment]
This is fixed with WinAppSDK version 1.3.230228005-preview1
The Win2DMemoryTest app no longer leaks memory when updated to that version of WinAppSDK. @lhak could you confirm what I'm seeing?

**Comment by lhak** [comment]
@getrou I cannot reproduce the issue anymore with 1.3 preview 1.
