### ISSUE TITLE
Question: Use of WinUI in XamlLand

### ISSUE THREAD

**Issue by oldoldman** [microsoft/microsoft-ui-xaml#3668]
I've declared Microsoft.UI.Xaml.dll in my Win32 manifest file and got the dll loaded , but finally failed with loading the resource :
```
Cannot load DefaultStyleResourceUri 'ms-appx:///Microsoft.UI.Xaml/Themes/19h1_generic.xaml' for TargetType 'Microsoft.UI.Xaml.Controls.SplitButton' in assembly 'Unknown'
```
So can I use WinUI in XamlLand? Or is there some way to map above URI ? Many thanks!!!

**Comment by ranjeshj** [comment]
@oldoldman unpackaged apps are not currently supported in WinUI3. Are you using a package or is it unpackaged ?

**Comment by oldoldman** [comment]
> @oldoldman unpackaged apps are not currently supported in WinUI3. Are you using a package or is it unpackaged ?

I'm using unpackaged app. I'll resort to packaged one. thanks!
