### ISSUE TITLE
NavigationViewItem still shows an Empty Flyout when selected in Left Compact mode even if it has no child menu items

### ISSUE THREAD

**Issue by MarkIvanDev** [microsoft/microsoft-ui-xaml#3670]
**Describe the bug**

Binding the NavigationViewItem's MenuItemsSource to an empty collection still shows an empty flyout when selected in Left Compact mode.

**Steps to reproduce the bug**

1. Create a NavigationView in left compact mode.
2. Bind an empty Collection to a NavigationViewItem
2. Click on the NavigationViewItem, it will show an empty flyout

**Expected behavior**

If the NavigationViewItem has no children, it should not show an empty flyout when selected in Left Compact mode

**Screenshots**

![image](https://user-images.githubusercontent.com/16188252/99896609-178d8300-2ccd-11eb-89eb-b831f2cf1fc1.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.5.0-prerelease.201027002

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by chingucoding** [comment]
I would like to look into this.
