### ISSUE TITLE
DataContext Assignment errors

### ISSUE THREAD

**Issue by zsolt3991** [microsoft/microsoft-ui-xaml#3671]
**Describe the bug**

WMC0015 -> Cannot assign 'MainWindowViewModel' into property 'DataContext', type must be assignable to 'Object' occurs when binding ViewModels

**Steps to reproduce the bug**

1. New WinUI Desktop App
2. Create a ViewModel and try binding it to a DataContext of a Control

**Expected behavior**

Binding works

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No> | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)            | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Visual Studio 2019 16.8.2 and Visual Studio 2019 16.9 Preview 1 both have same behavior

**Comment by nr0225** [comment]
666

**Comment by MikeHillberg** [comment]
@zsolt3991, is the setup like this?:

```xaml
    <StackPanel x:Name="_root">
        <TextBlock Text="{Binding}" />
```

```cs
        public MainWindow()
        {
            this.InitializeComponent();
            _root.DataContext = "Hello world";
        }
```

**Comment by zsolt3991** [comment]
@MikeHillberg I was setting the value of DataContext on the highest level element in XAML when it didn't work. Setting it in the codebehind file works.

**Comment by MikeHillberg** [comment]
Can you add a code snippet of what that looks like?

**Comment by LokiMidgard** [comment]
I have the same problem

<details>
<summary>Xaml Snippet</summary>

<Window
    x:Class="App3.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App3"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid HorizontalAlignment="Center" VerticalAlignment="Center" x:Name="root">
        <Grid.ColumnDefinitions>
            <ColumnDefinition></ColumnDefinition>
            <ColumnDefinition></ColumnDefinition>
        </Grid.ColumnDefinitions>
        <Grid.DataContext>
            <local:Viewmodel/>
        </Grid.DataContext>
        
        <GridView ItemsSource="{Binding Items}" SelectionMode="Multiple">
            <GridView.ItemTemplate>
                <DataTemplate>
                    <StackPanel>
                        <TextBlock Text="{Binding Text}"/>
                        <TextBlock Text="{Binding IsSelected}"/>
                    </StackPanel>
                </DataTemplate>
            </GridView.ItemTemplate>
        </GridView>
    </Grid>
</Window>

</details>

program|version
-|-
Visual Studio |16.9.0 Preview 4.0
Windows | 1809 17763.1697
WinUI | 3.0.0-preview4.210210.4
