### ISSUE TITLE
MakePRI fails with PRI175 for certain project only in Release

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#3672]
**Describe the bug**

Create a side-load appx package for this project in Visual Studio. Include `Release (x64)` only.
It will fail with `PRI175: duplicated item`, in the following step:
```
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\MakePri.exe New -ProjectRoot "C:\Users\Meow\source\repos\EHunter\Source\EHunter.UI (Package)\\" -ConfigXml "C:\Users\Meow\source\repos\EHunter\Artifact\obj\EHunter.UI (Package)\x64\Release\priconfig.xml" -OutputFile "C:\Users\Meow\source\repos\EHunter\Source\EHunter.UI (Package)\bin\x64\Release\resources.pri" -IndexName e8341ccf-1b5f-4054-b712-814094a4dde1 -Verbose -Overwrite  
```

However, it does success on Debug configuration. I cannot reproduce this with the template WinUI3 desktop app, or a minimal repro.

Note: I can run the app in Release with Visual Studio, without building appx package.

I did success once for packaging in Release with commenting out `BaseOutputPath` and `BaseIntermediateOutputPath` in `Directory.Build.props`, but it's not reproducible. (I can't package after `git clean -xdf`)

In WinUI 3 preview 2, I met the same problem for both Debug and Release. For preview 3, it only fails with Release.

I turned off PublishTrim and ReadyToRun in public profile for reproduction speed. They doesn't contribute to this issue.

Repro solution:
[EHunter (repro).zip](https://github.com/microsoft/microsoft-ui-xaml/files/5579571/EHunter.repro.zip)

**Comment by huoyaoyuan** [comment]
Difference I found during investigating:
The input files `priconfig.xml` and `.resources` are nearly identical.

**The output path of .NET projects in Debug and Release are different.** This also reproduces for the template project.
For Debug, it's `bin\x64\Debug\net5.0-windows10.0.18362.0`.
For Release, it's `bin\x64\Release\net5.0-windows10.0.18362.0\win10-x64`.

**Comment by ranjeshj** [comment]
@stevenbrix as FYI

**Comment by huoyaoyuan** [comment]
Additional context:
When packaging from command line in Release, it will fails with error in `UseDebugCRT` from `Microsoft.VCRTForwarders.140`, which shouldn't been invoked. (Not invoked in template app). Adding `/p:VCRTForwarders-IncludeDebugCRT=false` solves it and gets the same behavior in Visual Studio.

Full command line used:
```
msbuild /p:Configuration=Release /p:platform=x64 /p:platform=x86 /p:AppxBundle=Always "/p:AppxBundlePlatforms=x64|x86" /p:UapAppxPackageBuildMode=StoreAndSideLoad /p:VCRTForwarders-IncludeDebugCRT=false /bl:release.binlog
```

**Comment by huoyaoyuan** [comment]
When building from command line for Release, I get the MakePRI error even when packaging for a single platform. This differs from Visual Studio. Packaging for Debug is always good.

**Comment by stevenbrix** [comment]
Thanks for the additional context @huoyaoyuan.

The paths being different for Debug/Release sounds expected. Do you think this is causing an issue?

**Comment by huoyaoyuan** [comment]
@stevenbrix The error message is about xbf in control library project, so I think there might be case not considered for project reference.

It doesn't matter whether the control library project is x64 or anycpu.

**Comment by huoyaoyuan** [comment]
Still present for preview4. This is currently a hard blocker of production.
Modification of `bin` and `obj` directory may be the cause, but I haven't got minimal repro now.

**Comment by huoyaoyuan** [comment]
I'm trying to investigate using project system tool. However, I'm going to a weird situation:

![image](https://user-images.githubusercontent.com/5644458/110923839-4c951280-835c-11eb-8437-b4f64e567337.png)

If I turn this on, it will pack successfully. If turned off, I'll get the error.

**Comment by huoyaoyuan** [comment]
There may be some concurrency issue. I can't get a stable result on the same form of project. Even reopening VS without changing anything can make it fail.

**Comment by huoyaoyuan** [comment]
Updating to 19041 SDK will change the error message to:
```
PRI175: 0x80073b0f - Processing Resources failed with error: Duplicated item
PRI222: 0x80073b0f - Unspecified error occurred.
```

while 18362 SDK outputs:
```
PRI175: 0x80073b0f - Processing Resources failed with error: Duplicated item
PRI277: 0xdef00532 - Conflicting values for resource 'Files/xxx.xbf'
```

I think 18362 output is misleading. It's actually some other issue.

@stevenbrix Can you help me to delegate this to the team owns MakePri.exe? Thanks.

**Comment by huoyaoyuan** [comment]
The issue no longer reproduces in Windows App SDK 1.0 Preview 3.

**Comment by michael-hawker** [comment]
I'm seeing this issue with a UWP app (and in Debug):

```
3>  GENERATEPROJECTPRIFILE : error : PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.
3>  GENERATEPROJECTPRIFILE : error : PRI222: 0x80073b0f - Unspecified error occurred.
```

Trying to upgrade from WinUI 2.7.3 to 2.8.6... not sure where to go from here.
