### ISSUE TITLE
Investigate why TextControlThemeMinHeight should be defined 3 times and be put into ThemeDictionaries

### ISSUE THREAD

**Issue by licanhua** [Microsoft/microsoft-ui-xaml#368]
**Describe the bug**
This is found when providing compact dictionary. In PR #351 , 
We have to define the key like TextControlThemeMinHeight three times.
`            <x:Double x:Key="TextControlThemeMinHeight">24</x:Double>`

Otherwise the setting is ignored in following app.xaml setting.
```
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
                <ResourceDictionary Source="ms-appx:///Microsoft.UI.Xaml/Density/Compact.xaml" />
            </ResourceDictionary.MergedDictionaries>
```

**Comment by jevansaks** [comment]
@licanhua are you going to investigate this one?

**Comment by licanhua** [comment]
Not right now. From my aspect, I think it's low priority since we can workaround the problem.

**Comment by jevansaks** [comment]
Doesn't seem worth putting on the backlog.
