### ISSUE TITLE
OnIdiom not working with the new RowDefinitions ColumnDefinitions syntax

### ISSUE THREAD

**Issue by Cfun1** [microsoft/microsoft-ui-xaml#3681]
xaml is not accepting `OnIdiom ` when used with the new syntax of RowDefinitions and `ColumnDefinitions` https://github.com/microsoft/microsoft-ui-xaml/issues/673:

`RowDefinitions="{OnIdiom Tablet="*,*,auto", Phone="*,*,*"}"`

Tried the following workaround but crashing the app on Xamarin and throwing the exception:
> **System.Reflection.TargetInvocationException:** 'Exception has been thrown by the target of an invocation.'

```
 <Grid.RowDefinitions>
            <RowDefinitionCollection>
                <OnIdiom x:TypeArguments="RowDefinitionCollection">
                    <OnIdiom.Phone>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="*"/>
                    </OnIdiom.Phone>
                    <OnIdiom.Tablet>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="auto"/>
                    </OnIdiom.Tablet>
                </OnIdiom>
            </RowDefinitionCollection>
        </Grid.RowDefinitions>
```

**Comment by StephenLPeters** [comment]
#673 is a proposal, it hasn't been integrated in the product yet. What is OnIdiom?

**Comment by StephenLPeters** [comment]
Looks like a xamarin forms type. Should this issue be on their repo? https://github.com/xamarin/Xamarin.Forms

**Comment by Cfun1** [comment]
@StephenLPeters I didn't know `OnIdiom` was used by Xamarin.Forms only then I will move it there, but https://github.com/microsoft/microsoft-ui-xaml/issues/673 I am already using the new syntax with Xamarin.forms project.
