### ISSUE TITLE
Grid Star-Sizing does not work inside ListView

### ISSUE THREAD

**Issue by nailuj29gaming** [microsoft/microsoft-ui-xaml#3682]
**Describe the bug**

When Star-Sizing is used inside of a `Grid` which is a child of `ListView`, the columns have no sizing and fill their minimum amount of space
**Steps to reproduce the bug**

```
class Counter {
	string Name {
		get; set;
	}
	
	int Count {
		get; set;
	}
}
```

```
<ListView
        x:Name="itemsList"
        HorizontalContentAlignment="Stretch">
        <ListView.ItemTemplate>
            <DataTemplate>
                
                <Grid x:Name="itemGrid">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="4*"/>
                        <ColumnDefinition Width="1*"/>
                        <ColumnDefinition Width="2*"/>
                        <ColumnDefinition Width="1*"/>
                   
                    </Grid.ColumnDefinitions>


                    <TextBlock Text="{Binding Name}" Grid.Column="0"/>
                    <Button Content="+" Grid.Column="1"/>
                    <TextBlock Text="{Binding Count}" Grid.Column="2"/>
                    <Button Content="-" Grid.Column="3" />

                </Grid>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
```

Set the `ListView.itemSource` in code. 

**Expected behavior**

Name is 4x larger than the buttons, which are half the size of the number
**Screenshots**

**Version Info**

Microsoft.WinUI 3.0.0-preview3.201113.0
Microsoft.NETCore.UniversalWindowsPlatform 6.2.10
NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | |
| 20H2 (19042)		                 | Yes |
| May 2020 Update (19041)            | |
| November 2019 Update (18363)       | |
| May 2019 Update (18362)            | |
| October 2018 Update (17763)        | |
| April 2018 Update (17134)          | |
| Fall Creators Update (16299)       | |
| Creators Update (15063)            | |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               ||
| Surface Hub        | |
| IoT                | |

**Additional context**

**Comment by StephenLPeters** [comment]
@nailuj29gaming can you provide a screenshot of what the code currently does?  Can you also try the suggestions here: https://blog.mzikmund.com/2017/02/tip-stretching-list-items-in-uwp/?

**Comment by nailuj29gaming** [comment]
@StephenLPeters The link you sent worked. I will now close this issue

**Comment by robloo** [comment]
This is confusing for a lot of developers and I don't think historic controls worked this way (WPF, etc.). The first thing I end up doing in the vast majority of cases is to stretch the horizontal alignment of the container style. @StephenLPeters Can we change the default style to stretch automatically? This is much more intuitive.

**Comment by nailuj29gaming** [comment]
I think allowing the style attributes on the `DataTemplate` would be even more intuitive

**Comment by mdtauk** [comment]
I seem to have a vague memory if this being a default change some years back, possibly when Windows Phone moved to WinRT?

**Comment by robloo** [comment]
@mdtauk Yes, I have the same recollection.

**Comment by StephenLPeters** [comment]
I agree, it does seem pretty confusing. @robloo want to open a new issue, (or repurose this one) into a feature request? it will require winui 3 but I think it sounds like goodnes..

**Comment by Felix-Dev** [comment]
@StephenLPeters Such a request was already made in the past (see the now closed issue https://github.com/microsoft/microsoft-ui-xaml/issues/1402) and back then @anawishnoff was [not yet convinced](https://github.com/microsoft/microsoft-ui-xaml/issues/1402#issuecomment-540160715) of such a change. I suggest we re-open that issue if the team is open to discuss this again.

**Comment by robloo** [comment]
I'm fine with re-purposing this one or using the older, closed issue I didnt know about. Definitely think this needs to be rediscussed. If it really is different from WPF its something obvious to change to make everyone's job easier moving to WinUI 3. Personally, I will then cleanup some xaml removing the customized styling.
