### ISSUE TITLE
Question: [How to navigate to a new page using WinUI3 with C++ desktop app?]

### ISSUE THREAD

**Issue by YonghuiKing** [microsoft/microsoft-ui-xaml#3683]
Firstly I create a project using template "Blank App, Packaged(WinUI in Desktop)" in Visual Studio.

Then I changed code in MainWindow.xaml to a simple Frame:

<Frame x:Name="rootFrame"></Frame>
And then I add a BlankPage and try to navigate to the BlankPage like this:

rootFrame().Navigate(xaml_typename<BlankPage>());
And then visual studio give me error:

winrt\Windows.UI.Xaml.Interop.h(643,29): error C2338: T must be WinRT type.
I don't know how to do...

**Comment by StephenLPeters** [comment]
I think you want something like what this thread suggests: https://stackoverflow.com/questions/53688012/c-winrt-navigation-between-two-pages

**Comment by StephenLPeters** [comment]
so: `rootFrame().Navigate(xaml_typename<BlankPage>());`

**Comment by YonghuiKing** [comment]
rootFrame().Navigate(xaml_typename<BlankPage>()); is exactly what I code...but same error.

**Comment by Jaiganeshkumaran** [comment]
> rootFrame().Navigate(xaml_typename()); is exactly what I code...but same error.

You are passing the implementation type instead of the projection type. This issue occurs when you are inside the implementation namespace. Instead write the fully qualified type name eg: YourApp::YourPage instead of just YourPage
