### ISSUE TITLE
AppBarSeparator not aligned with AppBarButtons in CommandBar

### ISSUE THREAD

**Issue by katan-ms** [microsoft/microsoft-ui-xaml#3684]
**Describe the bug**
By default, the AppBarSeparator is not located in the vertical center of the CommandBar, causing it to not align with the center of AppBarButtons.

Sample code:
` 
<CommandBar>
    <AppBarButton Icon="ClearSelection" />
    <AppBarButton Icon="SelectAll" />
    <AppBarSeparator />
    <AppBarButton Icon="Clear" />
</CommandBar>
`

As you can see in screenshots, the separator is clearly off center.

**Steps to reproduce the bug**
1. Use the code provided above and observe.
2. Change the CommandBar VerticalAlignment to Center, and we'll have the same results.

**Expected behavior**
AppBarSeparator should align well with other elements in the CommandBar. Or at least, when VerticalAlignment is set to center, it should be vertically centered.

We have used the following style to resolve the issue, but this only works when the label position is set to right or none.

`<Style TargetType="AppBarSeparator">
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="AppBarSeparator">
                <Rectangle x:Name="SeparatorRectangle"
                    Width="1"
                    Height="20"
                    Fill="{TemplateBinding Foreground}"
                    Margin="16,0"
                    VerticalAlignment="Center">
                </Rectangle>
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>
`

**Screenshots**
![image](https://user-images.githubusercontent.com/59658471/100061005-add8ba80-2e2d-11eb-8460-1d4046c40424.png)
![image](https://user-images.githubusercontent.com/59658471/100061308-26d81200-2e2e-11eb-950a-b5bbca6fbf18.png)

**Version Info**

NuGet package version: 2.4.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21264)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@teaP FYI

**Comment by shaheedmalik** [comment]
That's a bug indeed.

**Comment by hansmbakker** [comment]
This is not the only layout issue with `CommandBar`: please also see https://github.com/microsoft/microsoft-ui-xaml/issues/1024

**Comment by mdtauk** [comment]
Does the separator resize or move at all when the button labels come into view?

**Comment by chingucoding** [comment]
@mdtauk The separator does not reposition itsself or extend. The current behavior is that it moves up with the rest of the icons. I am not sure if that is the best behavior, but I think that it might look a bit weird if it rearranges itself to be the center of the larger row.

Also, I would like to work on this issue.

**Comment by mdtauk** [comment]
If the separator won't resize to be centred into the bar when it resizes to show the labels, it should at the very least remain in line with the icons.

But I think being centred in the bar, and resizing, would make the most sense.

![image](https://user-images.githubusercontent.com/7389110/102944169-e661c780-44b1-11eb-8263-58e41aeb8c37.png)

**Comment by chingucoding** [comment]
Looking at this now, the AppBarSeparator style doesn't seem to have already been added to WinUI. As part of my PR, I would add a new file "AppBarSeparator" with an appropriately named style for BasedOn usage and the AppBarSeparator style from the SDK generic.xaml file.

**Comment by mdtauk** [comment]
Would a Stretch Vertical alignment, with 4px top and bottom margin, do the trick, or do you manually have to adjust the height with a Storyboard?

Multi-line wrapped text would need to be considered too.

**Comment by chingucoding** [comment]
> If the separator won't resize to be centred into the bar when it resizes to show the labels, it should at the very least remain in line with the icons.

Yes, totally agree with you and this was my plan for the fix.

> But I think being centred in the bar, and resizing, would make the most sense.

In most cases, yes it would probably be the best behavior. However, there are two issues here:
1. The sizing of items on the CommandBar is actually always the "expanded" height, only that the bottom part is hidden. Because of that, I am not sure if this is possible to implement just through the style
2. In the case of a CommandBar where AppBarButtons have no text, an extended CommandBar could look strange since the icons are at the top, however your separator extends the whole height. Though this configuration would look weird either way.

**Comment by mdtauk** [comment]
> > If the separator won't resize to be centred into the bar when it resizes to show the labels, it should at the very least remain in line with the icons.
> 
> Yes, totally agree with you and this was my plan for the fix.
> 
> > But I think being centred in the bar, and resizing, would make the most sense.
> 
> In most cases, yes it would probably be the best behavior. However, there are two issues here:
> 
> 1. The sizing of items on the CommandBar is actually always the "expanded" height, only that the bottom part is hidden. Because of that, I am not sure if this is possible to implement just through the style
> 2. In the case of a CommandBar where AppBarButtons have no text, an extended CommandBar could look strange since the icons are at the top, however your separator extends the whole height. Though this configuration would look weird either way.
> 
> > Would a Stretch Vertical alignment, with 4px top and bottom margin, do the trick, or do you manually have to adjust the height with a Storyboard?
> 
> Unfortunately, stretch vertical alignment won't do the trick here, in collapsed state, the separator would extend to the bottom and not leave a gap as desired.

AppBar/CommandBar is not open sourced yet, so changing the way it works would have to wait until 3.0 right?

It is also an older control, like Pivot - so probably has not been holistically looked at.  The CommandBarFlyout control is more modern, and seems to animate much more fluidly (guessing its composition animations?) so would it also make it easier if that control is updated?

**Comment by chingucoding** [comment]
> AppBar/CommandBar is not open sourced yet, so changing the way it works would have to wait until 3.0 right?

Exactly, it might be that the ideal scenario is not possible to achieve until WinUI 3.

> It is also an older control, like Pivot - so probably has not been holistically looked at. The CommandBarFlyout control is more modern, and seems to animate much more fluidly (guessing its composition animations?) so would it also make it easier if that control is updated?

Does CommandBarFlyout even have vertical separators? None of the test pages in the MUXControlsTestApp seem to expose that. So I don't think that CommandBarFlyout would have an impact here.

**Comment by mdtauk** [comment]
> Does CommandBarFlyout even have vertical separators? None of the test pages in the MUXControlsTestApp seem to expose that. So I don't think that CommandBarFlyout would have an impact here.
>
Wasn't saying it did (although maybe it should) Only that the way CommandBarFlyout animates is a lot smoother than many other controls, so maybe the CommandBar/AppBar could gain something when you are able to edit/update it.

**Comment by chingucoding** [comment]
Oh misunderstood you there, sorry. I agree that other controls could get updated/edited animation wise given that CommandBarFlyout has very good animations.
