### ISSUE TITLE
WinUI-WPF one way or bidirectional support

### ISSUE THREAD

**Issue by aqibbanday** [microsoft/microsoft-ui-xaml#3685]
1>------ Rebuild All started: Project: WpfLibrary1, Configuration: Debug Any CPU ------
1>WpfLibrary1 -> F:\Downloads\Documents\WorkingDirectory\WpfApp1\WpfLibrary1\bin\Debug\net5.0-windows\WpfLibrary1.dll
2>------ Rebuild All started: Project: App1, Configuration: Debug x86 ------
2>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(240,9): error MC1003: Project file cannot specify more than one ApplicationDefinition element.
2>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(240,9): error BG1003: The project file contains a property value that is not valid.
2>Done building project "App1.csproj" -- FAILED.
3>------ Rebuild All started: Project: WapProjTemplate1, Configuration: Debug x86 ------
3>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(240,9): error MC1003: Project file cannot specify more than one ApplicationDefinition element.
3>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk.WindowsDesktop\targets\Microsoft.WinFX.targets(240,9): error BG1003: The project file contains a property value that is not valid.
3>Done building project "App1.csproj" -- FAILED.
========== Rebuild All: 1 succeeded, 2 failed, 0 skipped ==========

**Comment by StephenLPeters** [comment]
@MikeHillberg can you weigh in? or maybe @stevenbrix or @alwu-msft ?

**Comment by alwu-msft** [comment]
@aqibbanday  WPF and WinUI are not supported within the same project for WinUI 3.0, although this may change for a future release of WinUI. What is your scenario that would be enabled/improved by this?

**Comment by aqibbanday** [comment]
I want to build a WinUI app, that can also utilize APIs available in WPF.

**Comment by alwu-msft** [comment]
XAML Islands would allow you to mix WPF and WinUI 3 content within the same app, but it is not supported yet as of Preview 3.

**Comment by aqibbanday** [comment]
Ok, Thanks.

Is it possible for you to give some information regarding this issue?
https://github.com/dotnet/core/issues/5670

**Comment by stevenbrix** [comment]
@aqibbanday, which WPF api's are you interested in using in your WinUI app?

**Comment by aqibbanday** [comment]
i wanted to use Dock control but its not present in WinUI.

**Comment by stevenbrix** [comment]
@michael-hawker @azchohfi, is there a Dock control in the toolkit?

**Comment by stevenbrix** [comment]
It looks like there is: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/dockpanel

@aqibbanday, will that work for you?

**Comment by michael-hawker** [comment]
@stevenbrix yup, `DockPanel` is the one. It's been in the Toolkit forever, pretty sure it was added explicitly because there's one in WPF.

@aqibbanday you can find out about the Toolkit preview for WinUI 3 here: https://aka.ms/wct-winui3

**Comment by aqibbanday** [comment]
I will check this.

**Comment by nickrandolph** [comment]
What's the status of this - Seems to me that a common scenario would be for a WPF app that wants to make use of Project Reunion (and eventually winui3 via xaml islands - I know this isn't there yet). You'd have thought just adding project reunion ref to existing wpf project should just work?
cc @andrewleader I know that @dotMorten has raised this (https://github.com/microsoft/ProjectReunion/issues/593) but I have no idea why the issue was closed?

**Comment by andrewleader** [comment]
@nickrandolph microsoft/ProjectReunion#593 was closed because it's fixed and will be released in the next servicing update. When Hui closed it, Hui left a comment explaining that.

Once that servicing update to 0.5 is released, you'll be able to use Project Reunion features like MRT Core from your WPF apps.

**Comment by nickrandolph** [comment]
Thanks @andrewleader (🤭 I missed the comment about it being fixed as was busy reading @dotMorten s comments lol)
 I assume this issue on WinUI repo can be closed too?

**Comment by andrewleader** [comment]
I think this specific issue thread is asking to be able to intermix WinUI and WPF (a.k.a. XAML Islands), which is a slightly different topic and not supported yet. I'll leave it up to the WinUI folks to decide whether they want to use this issue to track that request (or maybe they already have one for that, I haven't looked personally).

Although it sounds like the DockPanel from Windows Community Toolkit might have resolved @aqibbanday's root problem... @aqibbanday did you try out the Windows Community Toolkit DockPanel control and did that remove your need for using WPF in your WinUI 3 app?

**Comment by aqibbanday** [comment]
It works.
Also: https://github.com/microsoft/microsoft-ui-xaml/issues/4772
https://github.com/aqibbanday/WinUIWPFSample

**Comment by michael-hawker** [comment]
@aqibbanday why are you still trying to use the `<UseWPF>` flag in the project? Can you explain in more detail exactly what you're trying to accomplish and how you are blocked?

If you follow the guidance provided by the WinUI docs and our guide for the Windows Community Toolkit for WinUI 3 [here](https://aka.ms/wct-winui3). Then you shouldn't have a problem using a `DockPanel` type control (that should be functionally equivalent to the WPF one, as far as I know) within WinUI 3.

**Comment by dotMorten** [comment]
> XAML Islands would allow you to mix WPF and WinUI 3 content within the same app, but it is not supported yet as of Preview 3.

That's excluding the scenario where you might want to use a non-UI class from one framework within the other app. It's sort of rare that referencing one nuget package would break another nuget package in the way that this does it. IMHO there should be nothing wrong with referencing both, just like there's nothing with referencing both WinForms and WPF in the same app.

**Comment by andrewleader** [comment]
@dotMorten the scenario you described works as of 0.5.5 of Project Reunion. You can reference 0.5.5 from a WPF app and use non-WinUI classes from Project Reunion in your WPF app.

We previously had a bug in the first version of 0.5 that caused that to break, but we fixed that in the 0.5.5 servicing update.

In the future, we hope to allow mixing UI of WinUI and WPF (XAML Islands), but right now you can mix WPF with non-WinUI Project Reunion APIs (there currently aren't many of them, but there will be more in the future).

**Comment by dotMorten** [comment]
@andrewleader But not the other way around: If I want to use a WPF class in my WinUI app, I get this:
![image](https://user-images.githubusercontent.com/1378165/115476816-79f49c00-a1f7-11eb-974c-70f744c7ee76.png)

**Comment by andrewleader** [comment]
@dotMorten what non-UI-related WPF APIs are you trying to use in your WinUI app?

**Comment by nickrandolph** [comment]
@dotMorten (and I'm asking this to you because you're more familiar with WPF and what devs may want to use from that framework) are there clear scenarios where it makes sense to support WPF inside a Reunion app? 

My concern is that we're asking a lot for there to be bi-directional support - I'd have assumed that the most common scenario is existing WinForms/WPF apps that want to leverage Reunion, and eventually WinUI. I'm not sure I see a scenario where it makes sense to use WinForms/WPF from a Reunion app.

**Comment by dotMorten** [comment]
@andrewleader Personally I'm not at the moment, but that's what this issue is about. Generally referencing a few assemblies shouldn't step on referencing a few other assemblies. But I could imagine prior to getting xaml islands, you could launch multiple windows and have them be mixed, so one is a winui window, the other a WPF window.
But also base libraries like System.Xaml have some useful stuff in it, PresentationCore and WindowsBase has some good types that could serve some reuse purpose, there's the PackWebRequest class that's useful, and probably a lot more.

I'm guessing the main issue here is when referencing both, which XAML parser wins? There might have to be some project setting where you control what the default XAML parser should be (and in the long run being able to pick which xaml build action you need per file once we allow using both)

**Comment by aqibbanday** [comment]
In preview i launched a WPF window as Dialog (referenced WPF class library in WinUI)

            Window win = new Window();
            win.ShowDialog();
            
Exception thrown at 0x00007FFF37D24B59 (KernelBase.dll) in WinUIApp.exe: 0x0000071A: The remote procedure call was canceled, or if a call time-out was specified, the call timed out.
Exception thrown at 0x00007FFEE086D6AC (Microsoft.ui.xaml.dll) in WinUIApp.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

**Comment by aqibbanday** [comment]
The problem is WinUI window has very less properties and customization available as compared to WPF.
eg. I want a to show a window as dialog, with no borders and transparent background.

**Comment by aqibbanday** [comment]
> > You can reference 0.5.5 from a WPF app and use non-WinUI classes from Project Reunion in your WPF app.
> 
> @andrewleader But not the other way around: If I want to use a WPF class in my WinUI app, I get this:
> ![image](https://user-images.githubusercontent.com/1378165/115476816-79f49c00-a1f7-11eb-974c-70f744c7ee76.png)

Have you tried using a WPF Class library in WinUI?

**Comment by aqibbanday** [comment]
> @dotMorten what non-UI-related WPF APIs are you trying to use in your WinUI app?

Can we know what non-UI API's are available, maybe prepare a list?

**Comment by dotMorten** [comment]
> Have you tried using a WPF Class library in WinUI?
Also, try removing arm64 from Platforms tag.

I already removed it from the RIDs. The platforms tags are just for the configuration manager. It has no effect on the error I showed above

**Comment by aqibbanday** [comment]
> > Have you tried using a WPF Class library in WinUI?
> > Also, try removing arm64 from Platforms tag.
> 
> I already removed it from the RIDs. The platforms tags are just for the configuration manager. It has no effect on the error I showed above
> 
> > Can we know what non-UI API's are available, maybe prepare a list?
> 
> Anything that doesn't inherit from UIElement.

I was able to reference project's both side and build successfully. With no reference to any API.

**Comment by aqibbanday** [comment]
I was even able to show WPF window in WinUI project, worked as multi window as well.

**Comment by MikeHillberg** [comment]
I'm not sure which to focus on as the primary topic of this discussion, but the general mix-n-match story with WPF and WinUI and WinAppSDK is (in WinAppSDK 1.0):
* You can generally reference WinAppSDK in a WPF project
* But you can't use WinUI in that project; you need to create a separate project in the solution for WinUI
* To use WinUI in that project you need to set the <UseWinUI>true</> project property (which is set automatically by the WinUI project templates)
* You can't mix WPF and WinUI elements (borrow a panel from one and a control from the other), instead you'll need to have one host the other.

WPF hosting a Xaml island is experimental right now and pretty difficult to use, but is a current focus of effort. Hosting a WPF island in WinUI is further out. (Same story for WinForms)

The <UseWinUI> project property is required to light up some WinUI build targets. WPF similarly has <UseWPF> and I think WinForms has one too.

**Comment by pratikone** [comment]
this issue has many separate things being discussed for which I suggest a feature proposal issue to better get all things on topic concentrated at one place. I am closing this issue as original question has been answered.
