### ISSUE TITLE
Question: What is the process of adding Resources to a Window in Desktop development?

### ISSUE THREAD

**Issue by Elmarcotoro** [microsoft/microsoft-ui-xaml#3686]
I'm working on a WinUi 3 Desktop application and want to add resources to the Window.
There does not appear to be an attached property for Resources on the Window.

`<Window.Resources>
        
    </Window.Resources>`

What is the process now?

**Comment by MikeHillberg** [comment]
We are looking at adding a Window.Resources property at some point, but not yet. In the meantime, you need to put resources on the root of the Window's content.

```xml
<Window>
    <Grid>
        <Grid.Resources>
            ...
        </Grid.Resources>
    </Grid>
</Window>
```
