### ISSUE TITLE
WebAuthenticationBroker on Xbox doesn't pop soft keyboard

### ISSUE THREAD

**Issue by RobbyRobbyRobby** [microsoft/microsoft-ui-xaml#369]
**Describe the bug**
WebAuthenticationBroker on Xbox doesn't pop soft keyboard.
This prevents signing in to any OAuth protected APIs as the user can't type.
It used to work months ago, now it doesn't.

**Steps to reproduce the bug**
1) Create a blank UWP app.
2) Add a WebAuthenticationBroker (For example, to Pinterest).
3) Deploy to Xbox.
4) Notice that the WebAuthenticationBroker doesn't pop the keyboard, and in fact takes the cursor.

(as a side note; it ignores the any attempts at preventing scaling with  ApplicationViewScaling.TrySetDisableLayoutScaling(true); but that's not a big issue.)

**Expected behavior**
When the dialog pops up, and the text fields are selected, it should pop the soft keyboard so login can be attempted.

**Which Windows versions did you see the issue on? Leave blank if you didn't try that version**
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |    |

**Which device form factors did you see the issue on? Leave blank if you didn't try that device.**
| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | **No**   |
| Xbox                      | **Yes**   |

**Additional context**
These used to work.  An app with no changes which used to function, now doesn't so it may be an incompatibility with later OS builds of Win10/Xbox.

**Comment by jevansaks** [comment]
@Austin-Lamb any thoughts on this issue?

**Comment by jevansaks** [comment]
We've filed an [internal issue](https://microsoft.visualstudio.com/OS/_workitems/edit/20695059) for tracking.

**Comment by jevansaks** [comment]
The internal issue is marked as fixed. I don't have information at this time about what releases will contain the fix.

**Comment by NitradoJustus** [comment]
How exactly was this fixed? Was the cursor completely removed?? How do you solve recaptchas then?

**Comment by StephenLPeters** [comment]
@jevansaks do you happen to remember any of the context around this? I followed the internal bug but it isn't clear to me how this is was fixed from that's resolution.

**Comment by jevansaks** [comment]
@stephenlpeters I don't have any more context on the fix, sorry.
