### ISSUE TITLE
UWP design behaves different on desktop as raspberry

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#3693]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/UWP-design-behaves-different-on-desktop-/1262060?preview=true)._

---
We have found that the controls in the 4. column are lightly cut, but on desktop PC with forces window size of 800x480 does it fit. We used an increased font via style for TextBox, TextBlock and Button controls.

```
<Grid Background="White" Grid.Row="1">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto" MinWidth="100"/>
                <ColumnDefinition Width="Auto" MinWidth="300"/>
                <ColumnDefinition Width="Auto" MinWidth="200" />
                <ColumnDefinition Width="Auto" MinWidth="100"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="60" />
                <RowDefinition Height="60" />
                <RowDefinition Height="60" />
                <RowDefinition Height="60" />
                <RowDefinition Height="60" />
                <RowDefinition Height="60" />
            </Grid.RowDefinitions>

.. here are controls assigned to the rows
</Grid>
```
---
#### Feedback Bot on 11/19/2020, 05:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
Can the author please provide more information? screen shots/ project setups etc. I'm not sure how to proceed with this info.
