### ISSUE TITLE
ProgressBar doesn't show difference between Paused and Error option

### ISSUE THREAD

**Issue by j0shuams** [microsoft/microsoft-ui-xaml#3694]
**Describe the bug**

Under **Status and Info**, the **ProgressBar** page. If you select paused or error there doesn't seem to be a difference 

**Screenshots**

![image](https://user-images.githubusercontent.com/70237359/100157720-e2656a00-2e5f-11eb-8a3f-1a948074c828.png)
![image](https://user-images.githubusercontent.com/70237359/100157729-e5f8f100-2e5f-11eb-9fc1-6f219a2d4a8b.png)

**Version Info**

Using winui preview 3, cswinrt v1.1.0

Gallery version (found on Settings page): 

**Additional context**

**Comment by MikeHillberg** [comment]
Yes, this is a bug in WinUI3. There are also a couple of updates to WinUI2 ProgressBar that aren't in the WinUI3 version yet.

**Comment by anawishnoff** [comment]
Hi @j0shuams, you should see a fix for this bug in the upcoming WinUI 3/Project Reunion 0.8 Preview, which you can expect soon. Thanks for filing this bug!
