### ISSUE TITLE
COMException on adding/removing from ObservableCollection

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#3702]
**Describe the bug**
Regularly when adding or removing items from an ObservableCollection, I get the following exception:

System.Runtime.InteropServices.COMException:

"The callee (server [not server application]) is not available and disappeared; all connections are invalid. The call did not execute. (0x80010012 (RPC_E_SERVER_DIED_DNE))"

Stacktrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.IObjectReference.As[T](Guid iid)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)

It does not matter if I run the code on a DispatcherQueue from a UI thread. 
It does not matter if the user control is still on the screen (in the visual tree) or not.
I see this happening on raising events with INotifyPropertyChanged as well.
There is not way to ignore/skip over this exception. Continuing with debugging will keep nagging me about unhandled exceptions in combase.dll.

**Steps to reproduce the bug**
Adding/removing/clearing items from an ObservableCollection as part of a user control. 

**Expected behavior**
No exceptions on raising notify changed events. 

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|   | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by wbokkers** [comment]
I do add/remove often from the visual tree, by detaching controls from the parent, store them for later use and attach them again. Maybe these exception occur when notification events are raised when the control is not part of the visual tree? But I think it also sometimes happens with controls that are always visible.

**Comment by wbokkers** [comment]
This issue occurs due to calling (PInvoke) into our own DLL from a wrong thread, probably the UI thread. Changing audio devices in our DLL caused this issue to happen.

**Comment by StephenLPeters** [comment]
@stevenbrix or @Scottj1s is this a cswinrt issue? the top of the stack makes me think so.
