### ISSUE TITLE
[UWP]1 warning occurred when a uwp app add a reference to a ClassLibrary(Universal Windows)

### ISSUE THREAD

**Issue by SvetBonev** [microsoft/microsoft-ui-xaml#3706]
**Describe the bug**
Adding a reference to a ClassLibrary project from a UWP application project generates a XAML compiler warning.

**Steps to reproduce the bug**
1. Open Visual Studio 2019 (or 2017)
2. Create a new Universal Windows Class Library project
3. Create a new Universal Windows Application project in the same solution
4. Add a reference to the Class Library project from the Application project

**Expected behavior**
It just works.

**Actual behavior**
Visual Studio displays the following warning message in the Error List:
Cannot resolve Assembly or Windows Metadata file 'C:\Users\user\source\repos\ClassLibrary4\ClassLibrary4\bin\Debug\ClassLibrary4.dll'

**Screenshots**

**Version Info**
The behavior is observed with the XAML Compiler in the Windows 10 SDK.
I have no reason to believe that the behavior will be different with the WinUI version of the compiler.
Windows 10 OS version doesn't impact the issue.

**Additional context**
The error comes from a design-time build in Visual Studio that executes the DesignTimeMarkupCompilationCT msbuild target.
Errors from design-time builds are not actionable as they are not user-initiated actions.
Missing assemblies (especially from project references) are to be expected and such errors should be suppressed during design-time builds.

**Comment by huoyaoyuan** [comment]
Is the message still present if you compile the solution and reopen VS?

I've seen similar design-time warnings, but they are not permanent.

**Comment by SvetBonev** [comment]
> Is the message still present if you compile the solution and reopen VS?
The message goes away after rebuilding the solution.

I don't expect to see a message in the first place. It tells me that I did something wrong when in fact I simply added a reference.

**Comment by stevenbrix** [comment]
Thanks @SvetBonev for filing this and for the insight. I agree that we shouldn't be supplying a message here.

To set expectations, this is probably not our highest priority at the moment, but once we are open source we'd be happy to accept contributions.
