### ISSUE TITLE
Question: [Can't query ISwapChainPanelNative from SwapChainPanel?]

### ISSUE THREAD

**Issue by YonghuiKing** [microsoft/microsoft-ui-xaml#3707]
It's a desktop app with WinUI3.0 preview project, write by c++.
I tried two ways to query panelNative:
1.
`winrt::com_ptr<ISwapChainPanelNative> panelNative = m_swapChainPanel.as<ISwapChainPanelNative>();`
2.
```
m_swapChainPanel.Dispatcher().RunAsync(winrt::Windows::UI::Core::CoreDispatcherPriority::High, [=]()
	{
		winrt::com_ptr<ISwapChainPanelNative> panelNative = nullptr;

		winrt::check_hresult(
			winrt::get_unknown(m_swapChainPanel)->QueryInterface(__uuidof(panelNative), panelNative.put_void())
		);

		winrt::check_hresult(
			panelNative->SetSwapChain(m_swapChain.get())
		);
	});
```
both of them throws exception:WinRT originate error - 0x80004002 : 'No such interface supported'.Microsoft C++ exception: winrt::hresult_no_interface at memory location 0x010FE714.

**Comment by tonecool** [comment]
I have exactly the same problem, the only difference is that I created SwapChainPanel from managed project and passed it's pointer. I asked question [here](https://stackoverflow.com/questions/64932443/how-to-consume-iswapchainpanelnative-interface-from-swapchainpanel-intptr), but didn't get response so far :(

**Comment by codendone** [comment]
Do you have #include <**microsoft**.ui.xaml.media.dxinterop.h>? For WinUI3 you need to #include <**microsoft**.ui.xaml.media.dxinterop.h> rather than <**windows**.ui.xaml.media.dxinterop.h>.

**Comment by tonecool** [comment]
Thanks for help @codendone . This worked for me:

`m_swapChainPanel.Dispatcher().RunAsync(CoreDispatcherPriority::High, winrt::Windows::UI::Core::DispatchedHandler([=]()
		{
			winrt::com_ptr<ISwapChainPanelNative> panelNative;
			DX::ThrowIfFailed(
				winrt::get_unknown(m_swapChainPanel)->QueryInterface(IID_PPV_ARGS(&panelNative))
			    );

			DX::ThrowIfFailed(
				panelNative->SetSwapChain(m_swapChain.get())
			    );
		}));`

**Comment by YonghuiKing** [comment]
> Do you have #include <**microsoft**.ui.xaml.media.dxinterop.h>? For WinUI3 you need to #include <**microsoft**.ui.xaml.media.dxinterop.h> rather than <**windows**.ui.xaml.media.dxinterop.h>.

Thank you. This worked for me too.
