### ISSUE TITLE
Question: How to move from version 2 to 3?

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#3708]
Any tips or advice for the rest of us converting a UWP app to (UWP) WinUI 3? 

With some issues on my own app, I was trying to understand how the sample gallery was done. 
They have a single commit with ["346 changed files with 9,847 additions and 7,468 deletions"](https://github.com/microsoft/Xaml-Controls-Gallery/commit/37bbd908e4321332ef688ab9c13f48c29a7960c1) to convert the Gallery to WinUI 3. 

Is this the kind of effort expected for the move?

The namespace changes are pretty straight forward. There are so many other changes that I have not been able to get our app to build coming from UWP WinUI 2, after hours of work. The path UWP WinUI 2 to 3 seems impossible right now, because of the INotifyPropertyChanged incompatibilities. 

In addition, the removal of WebView at the same time is unfortunate, combined with the unavailability of a preview of the community toolkit for UWP makes testing the preview with our app impractical right now.

Is there much more here planned until release?

**Comment by huoyaoyuan** [comment]
The major work should converting namespaces `Windows.UI.*` to `Microsoft.UI.*`. Changing project config is also required, but you can start with WinUI 3 blank template.
