### ISSUE TITLE
Cannot bind to BitmapIconSource.UriSource in WinUI3 preview3

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#3709]
**Describe the bug**

It is not possible to bind the icon in a `TabViewItem` to a dynamically created `BitmapIconSource`. (But, setting it in XAML does work.)

**Steps to reproduce the bug**

1. Create a new Blank App (WinUI in Desktop)
2. Replace the contents of `MainWindow.xaml` with:

```xml
<TabView TabItemsSource="{x:Bind Tabs}">
    <TabView.TabItemTemplate>
        <DataTemplate x:DataType="local:TabItem">
            <TabViewItem
                        Header="{x:Bind Header}">
                <!-- UNCOMMENT FOR STEPS TWO AND THREE -->
                <!--IconSource="{x:Bind Icon}">-->
                <!-- COMMENT OUT FOR STEPS TWO AND THREE -->
                <TabViewItem.IconSource>
                    <BitmapIconSource UriSource="/Images/dataset-icon.png" />
                </TabViewItem.IconSource>
            </TabViewItem>
        </DataTemplate>
    </TabView.TabItemTemplate>
</TabView>
```

3. Replace the contents of `MainWindows.xaml.cs` with:

```cs
public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.Tabs = new ObservableCollection<TabItem> { new TabItem() };
        this.InitializeComponent();
    }

    public ObservableCollection<TabItem> Tabs { get; set; }
}

public class TabItem
{
    // This is just to show that it is possible to bind this in the TabViewItem
    public string Header => "My tab";

    public IconSource Icon
    {
        get
        {
            // This doesn't work (Just an arbitrary content image in the project)
            // UNCOMMENT FOR STEP THREE
            // return new BitmapIconSource { UriSource = new Uri("/Images/dataset-icon.png", UriKind.RelativeOrAbsolute) };

            // This works
            // COMMENT OUT FOR STEP THREE
            return new SymbolIconSource { Symbol = Symbol.Placeholder };
        }
    }
}
```

4. Add an `Images` folder to the project and add this file with a **Build Action** of `Content`
![dataset-icon](https://user-images.githubusercontent.com/189547/100364916-a87a9c00-2ff6-11eb-91a9-5f3273e4f512.png)

5. `STEP ONE`
Run the app and see the icon displayed correctly when defined in XAML

![partial screenshot showing the displayed bitmap image](https://user-images.githubusercontent.com/189547/100366281-900b8100-2ff8-11eb-8614-97887657ae75.png)

`STEP TWO`
Comment and uncomment the XAML as per the instructions, then run the app again to see the icon defined via bindings for a SymbolIconSource

![partial screenshot showing the displayed symbol](https://user-images.githubusercontent.com/189547/100366757-26d83d80-2ff9-11eb-9f92-ef42e5dbb366.png)

`STEP THREE`
Comment and uncomment the C# code as per the instructions, then run the app

See this error

```ascii
System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.System.WinRTUriRuntimeClassFactory.CreateUri(String uri)
   at ABI.System.Uri.CreateMarshaler(Uri value)
   at ABI.Microsoft.UI.Xaml.Controls.IBitmapIconSource.global::Microsoft.UI.Xaml.Controls.IBitmapIconSource.set_UriSource(Uri value)
   at Microsoft.UI.Xaml.Controls.BitmapIconSource.set_UriSource(Uri value)
   at App73.TabItem.get_Icon() in C:\Users\matt\source\repos\App73\App73\App73\MainWindow.xaml.cs:line 40
   at App73.MainWindow.MainWindow_obj4_Bindings.Update_(TabItem obj, Int32 phase) in C:\Users\matt\source\repos\App73\App73\App73\obj\x86\Debug\net5.0-windows10.0.18362.0\MainWindow.g.cs:line 209
   at App73.MainWindow.MainWindow_obj4_Bindings.Update() in C:\Users\matt\source\repos\App73\App73\App73\obj\x86\Debug\net5.0-windows10.0.18362.0\MainWindow.g.cs:line 175
   at App73.MainWindow.MainWindow_obj4_Bindings.DataContextChangedHandler(FrameworkElement sender, DataContextChangedEventArgs args) in C:\Users\matt\source\repos\App73\App73\App73\obj\x86\Debug\net5.0-windows10.0.18362.0\MainWindow.g.cs:line 114
```

**Expected behavior**

The icon should be displayed in the tab without error.

**Screenshots**

**Version Info**

NuGet package version: Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Note. this does not apply to WinUI2 as it doesn't support adding a `BitmapIconSource` to a `TabViewItem.IconSource`.

**Comment by MikeHillberg** [comment]
@Scottj1s, could this be the [known issue](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#known-issues) with URI marshaling in Preview3? It looks similar, but I thought that issue showed up when boxing a URI as an object, which I don't see happening here.

**Comment by Elmarcotoro** [comment]
I have the same issue with a WinUI 3 project in VS2019 Preview.

<AppBarButton Label="Square">
                <AppBarButton.Icon>
                    <BitmapIcon UriSource="ms-appx:///Assets/Test.png"/>
                </AppBarButton.Icon>
</AppBarButton>

The above does not display an image.  I've tested in a UWP project and it runs without fault.

I wonder if this a deeper issue with images in general.  I'm struggling to get any image to display.
e.g. <Image Source="../Assets/Cloud.jpg"/>
When I open an image in the image editor nothing displays.

**Comment by chrisglein** [comment]
I _think_ this is the critical comment:

> Note. this does not apply to WinUI2 as it doesn't support adding a BitmapIconSource to a TabViewItem.IconSource.

WinUI3 generally is by default going to behave the same as inbox OS XAML. If it didn't work on that (and WinUI2) then it isn't going to start working without additional work that hasn't happened yet. Which is to say this doesn't sound like a regression, but is a gap. Lots of things in XAML work in markup but don't work in code, which creates gaps like this :(.

@mrlacey let me know if I'm reading your comment there correctly.

**Comment by mrlacey** [comment]
@chrisglein  The difference with WinUI2 is that it doesn't support adding a BitmapIconSource to a TabViewItem.IconSource **in any way**.

If I try and add one in XAML I get compile errors.

![image](https://user-images.githubusercontent.com/189547/104377563-9ad59300-551e-11eb-92d3-24b015fd0626.png)
![image](https://user-images.githubusercontent.com/189547/104377931-19323500-551f-11eb-96f2-a0ea677812cf.png)

WinUI3 does add this capability (it works if set in XAML) but not if set in code.

This is something new in WinUI3 but it only works if set in XAML, not from code.
There has already been additional work done in for WinUI3.

It's not a regression, it's a "gap" (bug?) in the implementation of work done for WinUI3.
