### ISSUE TITLE
Please bring back WebView 1 in UWP WinUI 3

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#3711]
# Proposal: Temporarily make WebView (1) available in UWP WinUI 3 projects

## Summary
Please enable WebView (1) in WinUI 3 UWP projects.

## Rationale
Please make the move to WinUI 3 as easy for us as possible. The legacy WebView has a different API than the new WebView2 component. It would be great if we could tackle these migrations not all at the same time.

Marking WebView (1) as `[Obsolete]` seems like a great way to send a clear message and at the same time make the porting from 2 to 3 easier. (Or some other kind of compiler warning)

## Scope

| Capability | Priority |
| :---------- | :------- |
| API compatible to WebView (1) | Must |
| Clearly marked as obsolete | Should |
| Long term compatibility/support for WebView 1 | Won't |

## Important Notes
The rendering engine used does not matter for this proposal, a shim from WebView 1 to 2 would also work.

## Open Questions
Bringing WebView2 to UWP WinUI 2 would also solve this problem, as we can than move to WebView 2 first and WinUI 3 at a later time.

**Comment by mdtauk** [comment]
You can continue using Inbox UWP until you are ready to move to WinUI 3 and WebView 2

**Comment by Marv51** [comment]
Yes I can. But to make the move I have to change all WebView instances at the same time while I am so changing the UI framework. That's quite a big task.

(Over on the Apple side: WKWebView was introduced 5 years ago and the predecessor UIWebView is deprecated but still works)

**Comment by huoyaoyuan** [comment]
Is WebView 2 compatible with UWP WinUI 2? If so, you can migrate to WebView2 first.

**Comment by Marv51** [comment]
@huoyaoyuan It is not.

**Comment by adambarlow** [comment]
@Marv51 we appreciate your feedback. We understand the migration experience is a challenge. However, given a number of trade-offs and resource constraints we won't be able to address this. Let us know if you encounter issues while migrating to WebView2 and any issues that come up with that.
