### ISSUE TITLE
InfoBarPanel: totalWidth is ignoring the left margin on the first item, shouldn't it also ignore the right margin on the last item?

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#3713]
totalWidth is ignoring the left margin on the first item, shouldn't it also ignore the right margin on the last item?

_Originally posted by @MikeHillberg in https://github.com/microsoft/microsoft-ui-xaml/pull/3704#discussion_r530549344_

**Comment by MikeHillberg** [comment]
Resolved in https://github.com/microsoft/microsoft-ui-xaml/pull/3739
