### ISSUE TITLE
Scoped KeyboardAccelerator will not fire in MenuFlyout if the containing MenuFlyoutItem has no focus

### ISSUE THREAD

**Issue by zh4ui** [microsoft/microsoft-ui-xaml#3715]
**Describe the bug**

A MenuFlyoutItem whose KeyboardAccelerator's ScopeOwner's set to the MenuFlyout will not be invoked by using the KeyboardAccelerator if it's not focused.

**Steps to reproduce the bug**

XAML

```xml
<Page ...>
   <Page.Resources>
      <MenuFlyout x:Key="flyout" x:Name="menuLayout">
         <MenuFlyout.Items>
            <MenuFlyoutItem Icon="Edit" Text="Edit" />
            <MenuFlyoutItem
               Click="MenuFlyoutItem_Click"
               Icon="Delete"
               Text="Delete">
               <MenuFlyoutItem.KeyboardAccelerators>
                  <KeyboardAccelerator Key="Delete" ScopeOwner="{x:Bind menuLayout}" />
               </MenuFlyoutItem.KeyboardAccelerators>
            </MenuFlyoutItem>
         </MenuFlyout.Items>
      </MenuFlyout>
   </Page.Resources>
   <ListView ContextFlyout="{StaticResource flyout}">
      <ListViewItem>Item 1</ListViewItem>
      <ListViewItem>Item 2</ListViewItem>
      <ListViewItem>Item 2</ListViewItem>
   </ListView>
</Page>
```

code behind:

```cs
    private void MenuFlyoutItem_Click(object sender, RoutedEventArgs e)
    {
      ContentDialog dialog = new ContentDialog { Content = "Delete clicked", PrimaryButtonText = "Okay", DefaultButton = ContentDialogButton.Primary };
      dialog.ShowAsync();
    }
```

**Expected behavior**

As you can see, a KA (KeyboardAccelerator) is associated with key "Delete", and scoped to the MenuFlyout by setting `ScopeOwner="{x:Bind menuLayout}`. Also observe, the MenuFlyoutItem with "Delete" KA is the second item in the Flyout. 
When the MenuFlyout is opened by right clicking on a ListViewItem, clicking "Delete" key on the keyboard doesn't give the expected behavior which is opening the content dialog. One has to use Up/Down arrow key to move the focus to the MenuFlyoutItem with "Delete" KA to make the "Delete" key functioning.

The "Delete" key will work as expected (without the extra step of moving focus on the MenuFlyoutItem) if either one of the following changes is applied:

- Removing the first MenuFlyoutItem, making the MenuFlyoutItem the only item in the MenuFlyout
- Removing ScopeOwner on "Delete" KA

**Screenshots**

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

Windows 10 May 2020 Update (19041)       

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Visual Studio 16.8.2
Windows SDK 10.0.19041

**Comment by StephenLPeters** [comment]
Setting ScopedOwner to menuLayout is intended to prevent the keyboard accelerator from taking effect unless keyboard focus is on menuLayout or one of its descendants . My interpretation of this issue is that there is a misunderstanding of what scopedOwner does and that if you simply don't set scoped owner you'll get the behavior your looking for. Let me know if thats not the case! :)

**Comment by zh4ui** [comment]
Thanks. But the reason I am using scopedOwner is that I don't want to make the "delete" a global shortcut. I was wondering if there is way to both localize the "delete" and it can be triggered by pressing the "delete" key when the context menu is popped up.

**Comment by ranjeshj** [comment]
Do you want delete to work when focus is on the listitem as well as when the context menu is open ? Would setting the scope owner to the listview provide that behavior ?

**Comment by zh4ui** [comment]
I tried setting the scopeOwner to the listview, but it doesn't seem to work. It can  work  if "Delete" is the only item in the MenuFlyout.
