### ISSUE TITLE
Compile error C2760 in App.xaml.g.h if C++ Conformance Mode enabled

### ISSUE THREAD

**Issue by boostafazoo** [microsoft/microsoft-ui-xaml#3716]
Microsoft.WinUI.3.0.0-preview3.201113.0

1) New "Blank App (WinUI in Desktop)" project

2) App1 properties -> C/C++ -> Language -> Conformance Mode: Yes (/permissive-)

3) Build

```
1>XamlTypeInfo.Impl.g.cpp
1>F:\Source\Misc\App1\App1\App1\Generated Files\App.xaml.g.h(31,17): error C2760: syntax error: unexpected token 'identifier', expected ';' (compiling source file App.xaml.cpp)
1>F:\Source\Misc\App1\App1\App1\Generated Files\App.xaml.g.h(62): message : see reference to class template instantiation 'winrt::App1::implementation::AppT<D,Interfaces...>' being compiled (compiling source file App.xaml.cpp)
1>F:\Source\Misc\App1\packages\Microsoft.WinUI.3.0.0-preview3.201113.0\build\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(752,9): error MSB4181: The "CompileXaml" task returned false but did not log an error.
1>Done building project "App1.vcxproj" -- FAILED.
```

App.xaml.g.h:

```
void InitializeComponent()
{
    if (_contentLoaded)
        return;
        
    _contentLoaded = true;

    Uri resourceLocator{ L"ms-appx:///App.xaml" };    // C2760 here. Requires ::winrt::Windows::Foundation namespace.
    Application::LoadComponent(*this, resourceLocator);    // C2760 here if above is fixed. Requires ::winrt::Microsoft::UI::Xaml namespace.
}
```

**Comment by StephenLPeters** [comment]
@alwu-msft FYI, if this isn't your space can you pass it on?

**Comment by alwu-msft** [comment]
@RealTommyKlein the first C2760 has already been fixed internally, but I believe the second one (need to fully qualify Application::LoadComponent) has not been.

**Comment by RealTommyKlein** [comment]
@boostafazoo @alwu-msft - thanks for the report.  Alan's correct that the first instance for `Uri` is fixed internally, and I have fixes for both the `LoadComponent` call in App.xaml.g.h and similar `Uri` and `LoadComponent` calls in MainPage.xaml.g.hpp which should also be submitted internally fairly soon.

**Comment by anawishnoff** [comment]
This bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!

**Comment by krschau** [comment]
Closing as fixed. If someone sees this with the latest version, let me know and I'll reopen.
