### ISSUE TITLE
WinUI 3.0 in a desktop autocad plugin

### ISSUE THREAD

**Issue by kingofthebongo2008** [microsoft/microsoft-ui-xaml#3717]
Hello,
I am developing an autocad plugin which is a dll actually called from Autocad.
I want to be able to put winui into my windows, which i open in response to user commands.
Are there any obstacles to this right now?

**Comment by StephenLPeters** [comment]
I don't know very much about the structure of Autocad or its plugins, are they Win32 apps? WPF? something else? Its tough to say for sure without knowing the specifics, can you share more info?

@MikeHillberg fyi

**Comment by kingofthebongo2008** [comment]
They are win32 apps and they use mfc.

**Comment by marb2000** [comment]
It's unlikely that this scenario will be enabled by the next release of XAML Islands.  XAML Islands content (the WinRT types used) requires registering the classes that will be used by the Island. This registration is done in the application manifest, which goes with the EXE of your app. Given this is a plugin and I guess you won't be able to add the info to the manifest, you won't be able to load the types of the island.

**Comment by kingofthebongo2008** [comment]
Can I register them programmatically?
Is this an option?

**Comment by marb2000** [comment]
No, it's not an option. It will be great to do it, but it won't happen in 2021 for our current engineering plan. You can open a feature request for asking about it.

**Comment by FabianOswald-WolfSystem** [comment]
Any new ideas? Is .Net Standard a way?

**Comment by Basnederveen** [comment]
Any updates on this?

**Comment by myth384** [comment]
Hi all, I've just created a [feature request](https://github.com/microsoft/microsoft-ui-xaml/issues/9359#issuecomment-1960067276) that may interest you. I've aimed to define the scope of the use case as broadly as possible.
