### ISSUE TITLE
Microsoft C++ exception: winrt::hresult_error at memory location 

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#3732]
**Describe the bug**

I encounter the exception while hitting F5.

**Steps to reproduce the bug**
I added a single Page and hit F5.

**Screenshots**

![image](https://user-images.githubusercontent.com/43340959/100769098-e3683f80-33fb-11eb-89d1-4fa1dfa59cec.png)

**Version Info**

NuGet package version: 

WinUI 3 Preview 3 Blank project. 

![image](https://user-images.githubusercontent.com/43340959/100769507-6d180d00-33fc-11eb-9f7d-7ecf3fa0ac78.png)

**csproj:**

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
    <RootNamespace>Weather.History.WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
  </PropertyGroup>
```

**Comment by ranjeshj** [comment]
Is your startup project the package project in the solution ? If it is, could you share a repro ?

**Comment by sigmarsson** [comment]
Thanks for your rapid response. I did not understand. I do not understand. I closed VS, obliterated .vs folder, rebuilt; vanished. Hmm.

**Comment by sigmarsson** [comment]
Btw, pkg project. Could we just get rid of the pkg project in the event Developer mode is on ?

![image](https://user-images.githubusercontent.com/43340959/100857667-43f38d00-348d-11eb-9c04-b0bf0cc3b043.png)

I doubt the requirement of having a pkg in order to debug is an appropriate requirement.

**Comment by stevenbrix** [comment]
We require the packaging project at the moment, but it's a point-in-time thing.

Is this the same as #3741?

**Comment by sigmarsson** [comment]
Yes, it Is the same as #3741 

Pkg project is the startup project. Issue evolves in #3741
