### ISSUE TITLE
Control measure and arrange override method calls at two times on loading after upgrade Microsoft.WinUI version to 3.0.0-preview3.201113.0

### ISSUE THREAD

**Issue by sheiksyedm** [microsoft/microsoft-ui-xaml#3743]
**Describe the bug**
We have created the custom control that MeasureOverride and ArrangeOverride method calls on two times on the initial control loading case. This issue occurs after upgrading `Microsoft.WinUI` NuGet version to the latest `3.0.0-preview3.201113.0`. In the previous version(`3.0.0-preview2.200713.0`), control measure and arrange override methods called only one time. 

**Steps to reproduce the bug**
1. Open the sample [Sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/winui_test_sample653674407)
2. Add breakpoint for ControlExt's class MeasureOverride and ArrangeOverride methods. 
3. Run and you can notice the breakpoint hit on two times on both methods. 

**Expected behavior**
Method should be called only one time when control loading. 

**NuGet package version** 

[Microsoft.WinUI 3.0.0-preview3.201113.0]
Microsoft.NETCore.UniversalWindowsPlatform - 6.2.10

**Windows app type**
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by ranjeshj** [comment]
@sheiksyedm What is the issue this is causing ? There might be multiple measure/arrange passes before layout settles, so this is not unexpected.

**Comment by sheiksyedm** [comment]
@ranjeshj If I do any logic within the measure override method based on the available size, then the second time flow was unnecessarily executed. The two times of measure/arrange passes did not occur in WPF, Universal Windows App(UWP), or WinUI until version 3.0.0-preview2.200713.0. After upgrade to the latest version, the methods were called twice on load time.

**Comment by StephenLPeters** [comment]
Since this behavior has regressed for preview 3 I think this probably does point to an issue. Thanks for pointing it out and providing a repro app.

**Comment by StephenLPeters** [comment]
Putting on framework because it seems like a layout system bug (which I think is team-framework?)

**Comment by chrisglein** [comment]
Agree with what's said above, specifically that there is no guarantee that you only get measured/arranged once... but also if this is a change in behavior between inbox OS XAML and WinUI3 that it could indicate an unintentional regression (even if this symptom should be benign).

@sheiksyedm What's the impact on this issue to you? Your statement about expected behavior ("Method should be called only one time when control loading.") can't necessarily hold true. But is it negatively affecting you in some other way?

**Comment by sheiksyedm** [comment]
@chrisglein Yes, if I add any logic and some layout flows inside the measure and arrange method based on available size, it will unnecessarily execute on the second time when control is loading at the initial time.

**Comment by chrisglein** [comment]
@sheiksyedm What's the impact on your app of the extra layout measure? As stated above, extra measure/arrange isn't necessarily an error state.

**Comment by sheiksyedm** [comment]
@chrisglein I have measured and arranged the control's inner elements inside the measure/arrange method.  But, in load time, that flow was run two times without making any layout changes that would lead to some loading performance issue.

**Comment by FarjanaParveen** [comment]
@chrisglein  Any update on this

**Comment by chrisglein** [comment]
@FarjanaParveen No update. As I said above, there isn't any error here that I'm seeing. This sounds like a change in layout behavior that'd be good to understand, but is still operating within the limits of how layout is allowed to behave. I would definitely not recommend any apps take dependencies on how often many layout passes occur.
