### ISSUE TITLE
Stop using "Segoe MDL2 Assets" font by name

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#3745]
**Describe the bug**

I'm calling this a bug even though the code works correctly. I consider it a bug as the SymbolThemeFontFamily resource was added for a reason but it isn't being used consistently. Feel free to change this to a proposal if desired.

Several places in code (usually XAML) the symbol font is specified directly by name. This is bad practice and should switch to `"{ThemeResource SymbolThemeFontFamily}"` which ensures that this font can be switched out if ever needed in the future without having to change styles.

It's also a big help to the Uno Platform for example where the font it switched with a similar one licensed for all platforms.

**Steps to reproduce the bug**

Search WinUI source code, it's everywhere.

https://github.com/microsoft/microsoft-ui-xaml/blob/c6c8d084231f8cc4ffa978305e9f2a0f93a9a39c/dev/TabView/TabView.xaml#L195

**Expected behavior**

`FontFamily="Segoe MDL2 Assets"` should be replaced with `FontFamily="{ThemeResource SymbolThemeFontFamily}"`

**Screenshots**

N/A

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.4.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by mdtauk** [comment]
:)

This will make swapping out the MDL2 Icons and Fluent Icons much easier - as long as there is a way to either translate the Glyph unicode values with the new ones, or the Fluent UI System Icons repo can produce a font where the codepages match specifically for WinUI

**Comment by ranjeshj** [comment]
Assigning to @MarissaMatt

**Comment by robloo** [comment]
I can make the code change in XAML if approved.

**Comment by robloo** [comment]
I believe this is closed now via #3923
