### ISSUE TITLE
Published Package doesn't start

### ISSUE THREAD

**Issue by Artain** [microsoft/microsoft-ui-xaml#3749]
**Bug description**
If a sideload package is created and installed it will not start. After attaching a VS debugger the following error message is produced even on the machine the build was created and release or debug builds within VS work fine.
`Error:
  An assembly specified in the application dependencies manifest (App1.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '5.0.0'
    path: 'Microsoft.VisualBasic.Core.dll''App1.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Symbols loaded.`

`dotnet --info` produces following output:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Steps to reproduce the bug**
1. Create a new project with package
2. Publish package with sideloading (Add a valid Certificate for installation)
3. Install published package
4. (optional) Attach debugger (Debug -> Other debug targets -> Debug installed app packages)
5. Start App

**Expected behavior**
App should start the same way as it does in VS

**Version Info**
- Microsoft.WinUI 3.0.0-preview3.201113.0
- Blank desktop App with package C#
- VS 16.9.0 Preview 1.0
- .net SDK 5.0.100 (Installed with VS)
- Windows 10 19041

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |  |
| May 2019 Update (18362)            |  |
| October 2018 Update (17763)        |  |
| April 2018 Update (17134)          | |
| Fall Creators Update (16299)       ||
| Creators Update (15063)            ||

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by akanieski** [comment]
Running into the exact same problem as you list out above.

**Comment by lhak** [comment]
I have observed the same issue with the app not starting. In my case, setting PublishTrimmed to false in the Properties\PublishProfiles\win10-X.pubxml file fixed it.

**Comment by Artain** [comment]
> 
> 
> I have observed the same issue with the app not starting. In my case, setting PublishTrimmed to false in the Properties\PublishProfiles\win10-X.pubxml file fixed it.

@lhak Thanks this seems to resolve the issue. The question remains is this expected behavior.

**Comment by akanieski** [comment]
I too was able to set PublishTrimmed to false and it resolved it for me.

**Comment by stevenbrix** [comment]
This is a know issue with the deps.json file generation with the packaging project. @wli3, are you aware of any workarounds or status of this issue? Hereis the link to the internal VS issue tracking this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1242899

**Comment by stevenbrix** [comment]
For WinUI3 RTM, we'll set `PublishTrimmed` to false, and include an error that ensures that property isn't set. To follow when trimming will be officially supported for C#/WinRT assemblies, see https://github.com/microsoft/CsWinRT/issues/373

**Comment by stevenbrix** [comment]
This should be fixed in Preview4, the default publish profiles no longer set `PublishTrimmed`

**Comment by Bigous** [comment]
Same is happening to me. Version 1.0 of the Windows App SDK... (WinUI)...

The windows event logger complains about this:

```log
Application: IBovTrackerWinUI.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Dll was not found.
   at IBovTrackerWinUI.Program.XamlCheckProcessRequirements()
   at IBovTrackerWinUI.Program.Main(String[] args) in R:\Richard\src\GitHub\Bigous\MarketMonitor\IBovTrackerWinUI\obj\x64\Release\net6.0-windows10.0.19041.0\win10-x64\App.g.i.cs:line 28
```

Running from inside Visual Studio works... the project is open source and the [link is here](https://github.com/Bigous/MarketMonitor).

You will need the Proft running prior to run the application (it uses a COM+ object from it to get the RTD information).

The WinForms version of the application works both inside the visual Studio 2022 and the published version from the command line...

**Comment by krschau** [comment]
@Bigous If you're still seeing this with version 1.1 and want help with it, can you open a new issue?

**Comment by bryfa** [comment]
I have the same issue with my WindowsAppSDK1.1 It doesnt run anymore when deployed, but it does work in Visual Studio. We use separate MSIX installer project.

**Comment by Bigous** [comment]
> @Bigous If you're still seeing this with version 1.1 and want help with it, can you open a new issue?

I decided to use only the Windows Forms which works perfectly. The tool is just for me, so, I'm ok with that.
