### ISSUE TITLE
Unable to cast Compositor to ICompositorInterop

### ISSUE THREAD

**Issue by alexserov** [microsoft/microsoft-ui-xaml#3752]
**Describe the bug**
In our WinUI for UWP app, we are trying to create an `ICompositionGraphicsDevice2` instance as [documented here](https://docs.microsoft.com/en-us/windows/uwp/composition/composition-native-interop). For this, we try to cast the `Window.Current.Compositor` instance to the `ICompositorInterop` interface:
```csharp
var compositorPtr = Marshal.GetIUnknownForObject(Window.Current.Compositor);            
var guid = typeof(ICompositorInterop).GUID;
var hresult = Marshal.QueryInterface(compositorPtr, ref guid, out var pCompositorInterop);
var compositorInterop = (ICompositorInterop)Marshal.GetObjectForIUnknown(pCompositorInterop);
```
However, the `QueryInterface` returns the E_NOINTERFACE hresult.

I've listed available IIDs for the compositor object using the `IInspectable` API and have not found the `ICompositorInterop` iid (`25297D5C-3AD4-4C9C-B5CF-E36A38512330`)

**Steps to reproduce the bug**

1. Download and run the sample from the *Additional Context* section
2. Click on the "Click Me" button
3. The exception will be thrown.

**Expected behavior**
The `ICompositorInterop` should be available

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview3.201113.0]
[Microsoft.NETCore.UniversalWindowsPlatform 6.2.10]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

[App6.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5635962/App6.zip)

**Comment by StephenLPeters** [comment]
@stevenbrix and @Scottj1s could this be a cswinrt issue?

@jeffstall FYI

**Comment by Scottj1s** [comment]
See the C#/WinRT [COM Interop Guide](https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md).  After defining your ComInterop interface, you'd cast via
```
Window.Current.Compositor compositor;
var interop = compositor.AsInterface<ICompositionGraphicsDevice2>();
```

**Comment by alexserov** [comment]
Hello @Scottj1s, I've already seen the article you referred to, and it works well for WinUI for Desktop. However, I don't see any of the new API mentioned there in the **WinUI for UWP** project (I create projects using the templates shipped with the WinUI3 preview 3).

More, I see that the new marshaling API applies to .Net5, but according to [the roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#legend), WinUI for UWP will support .Net5 only in the post-release updates.

I'm definitely missing something...

**Comment by Scottj1s** [comment]
@alexserov - my apologies, I missed that this was UWP.  Your original interop code looks correct, so this may be a regression in WinUI's implementation of ICompositorInterop.  Your attempt to discover support via IInspectable::GetIIds doesn't always work - many implementations ignore it, and non-WinRT COM interop interfaces are not likely to be reported.

**Comment by alexserov** [comment]
@Scottj1s I tried your solution - it works like a charm, thanks!

Your link to the header file helped me a lot.
