### ISSUE TITLE
WinUI 3 Project Templates should contain the "XAML" tag

### ISSUE THREAD

**Issue by thomasclaudiushuber** [microsoft/microsoft-ui-xaml#3753]
**Describe the bug**
When the language filter in Visual Studio's "Create a new project" dialog is set to "XAML", the WinUI project templates should still show up, but they don't, as they don't have that tag.

**Steps to reproduce the bug**
Open the "Create a new project" dialog in Visual Studio and select "XAML" as a language filter. The WinUI project templates don't show up, just WPF and old-school "Blank UWP" project template. 
When you filter even to "XAML" | "All platforms" | "WinUI", you see nothing at all, like in the screenshot below.
 
**Expected behavior**
WinUI project templates should show up when language is filtered to "XAML". 

**Screenshots**
Screenshot below is ok, language filter set to C#, project type filter set to WinUI:
![image](https://user-images.githubusercontent.com/7116546/101036244-43392480-357b-11eb-8564-39d288bda618.png)

Screenshot below shows bug: Language filter set to XAML, project type filter set to WinUI:
![image](https://user-images.githubusercontent.com/7116546/101033513-7e872380-357a-11eb-8b3f-7f60c6fabbe5.png)

**Version Info**
Latest WinUI 3 Preview 3 templates

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by alwu-msft** [comment]
Closing as this has been addressed since at least Project Reunion 0.5.
