### ISSUE TITLE
Proposal: Turn off animation of SelectionIndicator

### ISSUE THREAD

**Issue by jskollin** [Microsoft/microsoft-ui-xaml#376]
# Proposal: Enable turning off animation of SelectionIndicator in NavigationView

## Summary
Users have no way to turn off the animation of the SelectionIndicator in the NavigationView. In other words, users cannot use the SelectionIndicator without the animation in the top part of the NavigationView.

## Rationale
Rationale can be found with this feature request: https://github.com/Microsoft/microsoft-ui-xaml/issues/375. Workarounds can be found for points 1 & 2, however no easy solution can be found to fix the animation inconsistency between the "top" and "bottom" NavigationViewItems without completely disabling the SelectionIndicator. Being able to simply disable or "turn off" the animation for the "top" NavigationViewItems would solve this.

**Comment by jevansaks** [comment]
The animation issue seems ok, I'd rather spend time on #375 and fix this more holistically.
