### ISSUE TITLE
new FontFamily( "file:///absolutepath#fontname" ) doesn't load TTF

### ISSUE THREAD

**Issue by Red-Rover** [microsoft/microsoft-ui-xaml#3766]
**Describe the bug**
Loading a font dynamically from the file system doesn't work correctly in a WinUI 3 Desktop application.  Loading fonts dynamically using the file:///absolutepath#fontname syntax works in WPF.

**Steps to reproduce the bug**
1. Create a blank project using the "Blank App, Packaged (WinUI Desktop)" Visual Studio Template
2. Add a TextBlock to the <Grid> to the MainWindow.xaml file with the following properties:

<TextBlock x:Name="_textBlock" Text="Testing 1234567890. ABCDEFG" FontSize="24"/>

3. In the MainWindow.cs file add the following after InitializeComponent() in the MainWindow() constuctor:

_textBlock.FontFamily = new FontFamily(@"file:///absoluatepath#fontname");

// replace absolutepath with the path to a TTF and fontname with the name of the font.

4. Run the application.

**Expected behavior**
It should load the font and apply it to the component.

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|                       |  Yes |

Windows 10 2004 20262.1010 Windows Feature Experience Pack 120.27510.103230.0

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox                 |  |
| Surface Hub     |  |
| IoT                | |

**Comment by StephenLPeters** [comment]
@MikeHillberg FYI

**Comment by chrisglein** [comment]
Not a surprising gap given that WinUI3 is coming from the code written to target UWP and not Win32, and in UWP absolute file paths are not so much a thing.

To be clear, this is a mismatch with WPF, not a mismatch between inbox OS XAML and WinUI3?

**Comment by castorix** [comment]
> Finally, I wrote the ttf file in AppData folder from EmbeddedResource. How do I load this now?

It works with relative path for custom fonts or full path for System fonts
I used it in [DWriteCore test](https://github.com/castorix/WinUI3_SwapChainPanel_DWriteCore) to fill the ComboBoxes with fonts (_{x:Bind FontFamilyPath}_ in XAML, _pFonts.Add_ in code)

**Comment by PetrMinar** [comment]
Hello to all,

I just discovered this old issue while searching for the same thing. And I found an [workaround](https://github.com/microsoft/microsoft-ui-xaml/issues/10054), though a bit limited. Hope it might help you a bit.
