### ISSUE TITLE
WinUI 2.5 is now available!

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#3767]
This morning the team released the newest version of the WinUI 2 controls library, WinUI 2.5! This release includes new controls and functionality that you can use in UWP apps. 

### InfoBar
InfoBar is a new control that's used to display app-wide status messages that are highly visible to users, yet are also non-intrusive. You can choose from different severity states to style the InfoBar, as well as add your own custom content such as buttons or hyperlinks. 

### ProgressRing - determinate state
You can now create ProgressRings that show percentage completion towards a task.

### NavigationView - footer menu feature
With the new FooterMenu property, NavigationView can display a group of Navigation items that are aligned to the bottom (or right) of your NavigationView. These items participate in the same selection model as all other items in the NavigationView. 

This release also includes a number of bug fixes and quality of life improvements, which you can read through here: [Release Details](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.5.0)

## Get started
If you're new to WinUI, get started by following the steps in this doc: [Getting started with the WinUI 2.x library](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started)

If you've used WinUI in the past, get started with 2.5 by downloading the latest NuGet package: [NuGet Download]( https://www.nuget.org/packages/Microsoft.UI.Xaml/2.5.0)

## Thank you!
Your contributions as a developer community have been incredibly valuable in shipping WinUI. We'd like to extend a big thank you to everyone who contributed to this release by filing or fixing bugs, requesting features, implementing features, and generally being a significant part of the development process!

**Comment by tipa** [comment]
Thanks a lot for the update! Unfortunately I cannot use it in my apps as I rely on the [FlowLayout](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.flowlayout?view=winui-3.0-preview), which is only available in the `-previews`. Any news on when this will make it to the stable releases?

**Comment by anawishnoff** [comment]
Pinging @ranjeshj for your question.

**Comment by ranjeshj** [comment]
@tipa  Thanks for your interest in FlowLayout. As you already mentioned, it is in pre-release and currently in the backlog. Unfortunately I don't have a target date for that yet since we are not actively working on that layout. During our initial review there was feedback about exposing this vs a more flexible Flex layout similar to the web.

**Comment by duke7553** [comment]
Are the new PaneFooter Items intended to be used by binding with a data source like ObservableCollection? We have an ItemTemplateSelector set up for the normal items and tried to use the same strategy with a separate dedicated data source for footer items. Unfortunately, the project still crashes on startup with these changes.

I guess I'll go ahead and report it as a bug if this behavior wasn't intentional. I did set a breakpoint in the ItemTemplateSelector for the respective template and this exception occurs before the breakpoint is hit.

```
Exception thrown at 0x00007FFBC111FD2C in Files.exe: Microsoft C++ exception: EEMessageException at memory location 0x000000EE964F84D0.
Exception thrown at 0x00007FFBC111FD2C in Files.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown: 'System.MissingMethodException' in Files.exe
Exception thrown at 0x00007FFBC111FD2C (KernelBase.dll) in Files.exe: WinRT originate error - 0x80131513 : 'System.MissingMethodException: Method not found: 'Void Microsoft.UI.Xaml.Controls.NavigationView.put_FooterMenuItemsSource(System.Object)'.
   at Files.Controls.SidebarControl.XamlBindingSetters.Set_Microsoft_UI_Xaml_Controls_NavigationView_FooterMenuItemsSource(NavigationView obj, Object value, String targetNullValue)
   at Files.Controls.SidebarControl.SidebarControl_obj1_Bindings.Update_Files_Controls_SidebarControl_FooterItemsSource(ObservableCollection`1 obj, Int32 phase)
   at Files.Controls.Sideba'.
```

**Comment by anawishnoff** [comment]
@duke7553 Thanks for your question. Yes, you should be able to bind [FooterMenuItems ](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.navigationview.footermenuitems?view=winui-2.5) to a data source such as an ObservableCollection. Please file a bug on this so we can take a look - thanks!

**Comment by michael-hawker** [comment]
@anawishnoff was just playing with the updated XAML Controls Gallery, noticed some issues with the new determinate Progress Ring:

- [ ] Value of 50 isn't half of the circle:
![image](https://user-images.githubusercontent.com/24302614/101382506-e4222b00-386c-11eb-9b58-6706e4610ca1.png)

- [ ] Values aren't determinate. Setting a value doesn't result in the same behavior all the time:
![image](https://user-images.githubusercontent.com/24302614/101382758-2ea3a780-386d-11eb-9aef-2ce844df9ca1.png)
![image](https://user-images.githubusercontent.com/24302614/101382782-36634c00-386d-11eb-8a39-1563c8494e0e.png)

- [ ] The above means that in many cases there is no visual increment when incrementing between numbers (every value should show a discrete amount of the arc when the control is large enough on screen):
![image](https://user-images.githubusercontent.com/24302614/101382729-264b6c80-386d-11eb-97a9-e84ccc017aec.png)
![image](https://user-images.githubusercontent.com/24302614/101382748-2cd9e400-386d-11eb-80a9-02b524b683d0.png)

(I saw it go for 3-4 steps without moving, and then this seemed to cause a large jump between 99 and 100 at times.)

- [ ] The ring isn't completely filled at 100 (you can still see the end caps of the segment):
![image](https://user-images.githubusercontent.com/24302614/101382863-4a0eb280-386d-11eb-8735-60d4987997a4.png)

**Comment by anawishnoff** [comment]
Thanks for pointing that out @michael-hawker. Handing this off to @MarissaMatt - perhaps we need a bug filed in the XCG repo for this.

**Comment by MarissaMatt** [comment]
@michael-hawker thank you for pointing this out! I'll investigate and file a bug.

**Comment by michael-hawker** [comment]
@MarissaMatt filed #3832

FYI you can turn any comment into a new issue, super handy:
![image](https://user-images.githubusercontent.com/24302614/102666443-c8a40380-413b-11eb-817c-ee53ad907b76.png)
