### ISSUE TITLE
Multi-instance winui 3 UWP...

### ISSUE THREAD

**Issue by davecarlisle** [microsoft/microsoft-ui-xaml#3772]
Quick roadmap question. We're successfully using the multi-window support for desktop but have a question on the UWP side.

Is there an ETA on winui 3 multi-instance support will be available in preview for UWP apps? 

Also, is there an ETA re a winui 3 multi-instance template? 

Thanks much!

**Comment by YuliKl** [comment]
@ryandemopoulos can you help?
