### ISSUE TITLE
ComObject from Window (.Net 5)

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#3773]
I want to create a swapchain for the window without any xaml.

SharpDX has the following technique to construct a swapchain ...

`   using (var windowAsCom = new ComObject(coreWindow))
    {
        tempSwapChain = new SwapChain1(CoreGraphics.dxgiFactory, CoreGraphics.Device3d, windowAsCom, ref SwapChainDesc);
`

Can .Net 5 / WinUI provide a ComObject for this call?

**Comment by YuliKl** [comment]
@Gavin-Williams I suspect your question would be better posed in one of the [.Net repos](https://github.com/dotnet) as it doesn't pertain to WinUI.

**Comment by Gavin-Williams** [comment]
Posted there as well ..
https://github.com/dotnet/runtime/issues/45735

**Comment by YuliKl** [comment]
Great. Closing this question as it's not WinUI-related.
