### ISSUE TITLE
WinUI build experience: Incremental building rarely working as of late

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#3786]
Since roughly a week or so, I am starting to get build errors unrelated to code changes made by me when incrementally building WinUI (Microsoft.UI.Xaml). These build errors look like this:
![image](https://user-images.githubusercontent.com/1398851/101533779-8e49a200-3996-11eb-8b3f-aa1445de905e.png)

Sometimes, it takes 1-2 successive incremental builds for them to occur, but they are a common occurence and basically force me to do a clean build - defeating the purpose of incremental building and considerably increasing WinUI development time in return. The full build following a clean completes successfully.

I am running VS 16.8.1 right now and while I don't recall getting these incremental build errors on VS 16.7, I am not sure if VS 16.8 is the culprit here or if the build fail reason lies elsewhere.

Also to note: These build errors occur using both the full solution *and* innerloop solution.

**Expected behavior**
I expect incremental building to work and not fail due to errors unrelated to the changes made since the last build.

@chingucoding FYI.

**Comment by chingucoding** [comment]
Thanks for the ping, I am also experiencing this issue. It came up in the past few days, building the MUXControlsTestApp twice in a row almost always give me these errors which defeats the point of incremental compile as @Felix-Dev noted correctly.

**Comment by StephenLPeters** [comment]
@teaP and @llongley

**Comment by StephenLPeters** [comment]
Looks like luke has a fix! :D
