### ISSUE TITLE
Determinate ProgressRing not filling based off of the value entered

### ISSUE THREAD

**Issue by MarissaMatt** [microsoft/microsoft-ui-xaml#3787]
**Describe the bug**
There are a few issues with the determinate progress ring not filling the circle correctly when a particular value is set. These values are described below: 

Value of 50 isn't half of the circle:
![image](https://user-images.githubusercontent.com/62765959/101557561-1c5f6180-3972-11eb-93e6-011690c49800.png)

 Values aren't determinate. Setting a value doesn't result in the same behavior all the time:
![image](https://user-images.githubusercontent.com/62765959/101557603-30a35e80-3972-11eb-9755-bcfbc3126f26.png)

 The above means that in many cases there is no visual increment when incrementing between numbers (every value should show a discrete amount of the arc when the control is large enough on screen):
![image](https://user-images.githubusercontent.com/62765959/101557654-4749b580-3972-11eb-8107-1289794e8d97.png)

(I saw it go for 3-4 steps without moving, and then this seemed to cause a large jump between 99 and 100 at times.)

 The ring isn't completely filled at 100 (you can still see the end caps of the segment):
![image](https://user-images.githubusercontent.com/62765959/101557677-5597d180-3972-11eb-98e3-01f2d09812c2.png)

**Comment by StephenLPeters** [comment]
@karenbtlai I think I remember there being some code which ensures that 99/100 looks clearly distinct from 100/100.  Is this code causing this?

**Comment by MarissaMatt** [comment]
@StephenLPeters @karenbtlai part of it could be with the Lottie file as well so I will reach out to design and see if they can help.

**Comment by mdtauk** [comment]
If I were working on the Animation file, I would have Keyframes for:
- 0%
- 1%
- 25%
- 50%
- 75%
- 99%
- 100%

**Comment by michael-hawker** [comment]
Originally posted from: https://github.com/microsoft/microsoft-ui-xaml/issues/3767#issuecomment-740059870

**Comment by jp-weber** [comment]
Any new info on this? It would be great if with WinUI 2.6 release the ProgressRing would work properly.

**Comment by HppZ** [comment]
microsoft is not good at UI & UX.

**Comment by michael-hawker** [comment]
@MarissaMatt @karenbtlai @StephenLPeters any updates? Can this be put in the 2.6 milestone?

**Comment by michalleptuch** [comment]
Any new info on this?

**Comment by MarissaMatt** [comment]
@ranjeshj @karenbtlai could we look to see if the lottie file is not aligning with the value of the progress ring?

**Comment by jp-weber** [comment]
Any news?

**Comment by MarissaMatt** [comment]
@jp-weber yes, we are testing out a new Lottie file that will fix some of the inconsistencies the community is noticing but there is an underlying code issue that we are trying to work through as well. I'm hoping to have another update by the end of this week. Thank you all for your patience on this!

**Comment by jp-weber** [comment]
@MarissaMatt thank you for the first update. What also would be interested, if the update have an inpact for the issue #4636 where the rendering of the ProgressRing will be destroyed, when the ProgressRing is in a CommandBar.

**Comment by MarissaMatt** [comment]
Thanks for bringing this to my attention as well! I will talk to the dev team to see if that issue is due to something going on with the ProgressRing rendering or if it's an AppBar issue.

**Comment by MarissaMatt** [comment]
@StephenLPeters do you think this bug [(here)](https://microsoft-my.sharepoint-df.com/:w:/p/mamatth/EYXSZdStMaRDqdGMiyxNz3IBVmHVIGwHIal4oJk0I1kruQ?e=NUvXEG) filed by @jp-weber will be fixed with the bug as well?

**Comment by karenbtlai** [comment]
Hey Marissa, it seems the link you linked below is the ItemsView spec? 😊

**Comment by MarissaMatt** [comment]
@StephenLPeters would this be a fix for this bug as well? https://github.com/microsoft/microsoft-ui-xaml/issues/4636
