### ISSUE TITLE
Assign an Attached Property to x:Null in VisualState won't call PropertyChangedCallback and throws COMException

### ISSUE THREAD

**Issue by katan-ms** [microsoft/microsoft-ui-xaml#3790]
**Describe the bug**

Setting an attached property to {x:Null} in visual state won't call the PropertyChangedCallback. This can be worked around by setting the PropertyType to object instead.

**Steps to reproduce the bug**

1. Run the attached project
[AttachedPropertyTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5665179/AttachedPropertyTest.zip)

2. In AttachedPropertyClass.cs you have:
`
        public static readonly DependencyProperty AttachedMenuFlyoutProperty = DependencyProperty.RegisterAttached(
            "AttachedMenuFlyout",
            typeof(MenuFlyout),
            typeof(AttachedPropertyClass),
            new PropertyMetadata(default(MenuFlyout), OnPropertyChanged));
`
`
        private static void OnPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var sender = d as TextBlock;
            sender.Text += Environment.NewLine + "PropertyChanged !";
        }
`
Run the project to see that the OnPropertyChanged isn't called when we try to assign the MenuFlyout from a menu with two items to x:Null. In debug mode it even throws a COMException.

3. Change `typeof(MenuFlyout)` to `typeof(object)` and run again. You can see OnPropertyChanged called and the text block gets updated as expected.

**Version info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21273)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Same issue as #3564 but I was using a wrong GitHub handle and wasn't notified of the updates. Sorry for that part.

**Comment by StephenLPeters** [comment]
I'm going to reopen the original issue, and close this one. Please post your response to @chrisglein there :)
