### ISSUE TITLE
TabView: TabItemsSource cannot be updated from another thread 

### ISSUE THREAD

**Issue by iomismo** [microsoft/microsoft-ui-xaml#3792]
Updating a binded TabItemsSource ObservableCollection from another thread throws a Windows.UI.Xaml.UnhandledExceptionEventArgs (using dispatcher).

System.ArgumentException: Value does not fall within the expected range.

A server sends a message to a client, which parses the message and adds a tab to the observablecollection.

```
await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
{
      Tabs.Add(tab);
});
```
Exception does not throws immediately after adding the tab, but at method end.

XAML:
```
<winui:TabView
        x:Name="MainTab"
        AllowDropTabs="True"
        TabItemsSource="{x:Bind ViewModel.Tabs}"
        AddTabButtonCommand="{x:Bind ViewModel.AddTabCommand}"
        SelectedItem="{x:Bind ViewModel.SelectedItem, Mode=TwoWay}"
        ScrollViewer.HorizontalScrollBarVisibility="Auto"
        ScrollViewer.VerticalScrollBarVisibility="Auto">

        <i:Interaction.Behaviors>
            <ic:EventTriggerBehavior EventName="TabCloseRequested">
                <ic:InvokeCommandAction Command="{x:Bind ViewModel.CloseTabCommand}" />
            </ic:EventTriggerBehavior>
        </i:Interaction.Behaviors>
        <winui:TabView.TabItemTemplate>
            <DataTemplate x:DataType="models:TabViewItemData">
                <winui:TabViewItem
                    Header="{x:Bind Header}"
                    AutomationProperties.Name="{x:Bind Header}"
                    Content="{x:Bind Content}">
                    
                </winui:TabViewItem>
            </DataTemplate>
        </winui:TabView.TabItemTemplate>
    </winui:TabView>
```

```
public class TabViewItemData
    {
        public int Index { get; set; }

        public string Header { get; set; }

        public object Content { get; set; }
    }
```
The Content of TabViewItemData is a Page.

UPDATE: 
__vfptr	0x7a24bb1c {Windows.UI.Xaml.dll!void(__stdcall* ctl::ComObject<DirectUI::UnhandledExceptionEventArgs>::`vftable'[10])()} {...}	void * *
		[0]	0x7a3cff40 {Windows.UI.Xaml.dll!ctl::ComObject<DirectUI::MenuFlyoutItem>::QueryInterface(const _GUID &, void * *)}	void *
		[1]	0x7a7c7ff0 {Windows.UI.Xaml.dll!ctl::ComObject<DirectUI::DropOperationTarget>::AddRef(void)}	void *
		[2] 0x7a922ce0 {Windows.UI.Xaml.dll!ctl::ComObject<DirectUI::AccessKeyInvokedEventArgs>::Release(void)}

**Comment by StephenLPeters** [comment]
Xaml is almost completely single threaded. Changing the collection causes xaml to relayout, which must occur from the UI thread.  I think crashing here is expected behavior and you should dispatch this call back to the UI thread.

**Comment by StephenLPeters** [comment]
@MikeHillberg can you confirm?

**Comment by iomismo** [comment]
Already dispatching to the UI thread
```
await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
{
      Tabs.Add(tab);
});
```

**Comment by iomismo** [comment]
The problem is the TabItemTemplate
```
<winui:TabView.TabItemTemplate>
                <DataTemplate x:DataType="models:TabViewItemData">
```

Using a TabView with no DataTemplate, and only adding "normal" TabViewItem, does not throw exceptions.

**Comment by StephenLPeters** [comment]
So the issue doesn't have anything to do with updating from another thread?  Can you provide a repro app? the call stack provided doesn't really make sense.

**Comment by iomismo** [comment]
It is from another thread, so I need to use dispatcher to be able to update the collection. It all starts from a received message in a websocket:

(Simplified version)

```
public static ObservableCollection<TabViewItemData> Tabs { get; set; } = new ObservableCollection<TabViewItemData>();

private async void MessageReceivedAsync(object sender, MessageReceivedEventArgs args)
{
   await ClientsPage.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
   {
            int newIndex = Tabs.Any() ? Tabs.Max(t => t.Index) + 1 : 1;
            TabViewItemData tab = new TabViewItemData()
            {
                Index = newIndex,
                ClientId = clientId,
                Header = header,
                Content = new Page()
            };

            Tabs.Add(tab);
   });
}
```
I will provide a complete example later (bit bussy). When adding a tabitem to the TabView with itemdatatemplate (TabViewItemData), there is no problem if it comes directly from the UI thread, e.g.: clicking the add button, that will add a TabViewItemData to the Tabs ObservableCollection property in the ViewModel. But, when I try to modify this collection from another thread (e.g: a received message from a websocket server), I need to use a dispatcher to be able to modify the tabs collection, and there is when an unhandled exception arises, with no stack, first as "invalid parameter" and when stepping with F11 it becomes "Value does not fall within the expected range." All of this using TabViewItemData as ItemDataTemplate. If I replace the collection to be a simple TabViewItem collection (not using ItemDataTemplate in the TabView), it works, both directly and using dispatcher.

I can continue programming without the ItemDataTemplate, but if you think it could be a bug or something to fix or improve...

Sorry for the lack of code, I will attach a sample app later.

Thanks

**Comment by StephenLPeters** [comment]
Got it, I think we will need to sample app to make progress on this.
