### ISSUE TITLE
Issue with FooterMenuItems not showing Selection when manually added to xaml instead of FooterMenuItemsSource.

### ISSUE THREAD

**Issue by avknaidu** [microsoft/microsoft-ui-xaml#3793]
**Describe the bug**

If you have a `ObservableCollection` Bound to `MenuItemsSource` But if you add `FooterMenuItems` Manually in xaml, The selections do not appear on FooterMenuItems

**Steps to reproduce the bug**

Create a Blank UWP Project. Add 'Microsoft.UI.Xaml` Package.

In `MainPage.xaml` add below

        <muxc:NavigationView x:Name="MyNavigationView" >
            <muxc:NavigationView.MenuItemTemplate>
                <DataTemplate>
                    <muxc:NavigationViewItem Icon="Favorite" Content="{Binding Content}"/>
                </DataTemplate>
            </muxc:NavigationView.MenuItemTemplate>
            <muxc:NavigationView.FooterMenuItems>
                <muxc:NavigationViewItem Icon="Favorite" Content="Footer 1"/>
            </muxc:NavigationView.FooterMenuItems>
        </muxc:NavigationView>

In `MainPage.xaml.cs` add below.

        private void Page_Loaded(object sender, RoutedEventArgs e)
        {
            ObservableCollection<BindableItems> bindableItems = new ObservableCollection<BindableItems>();
            for (int i = 1; i < 5; i++)
            {
                bindableItems.Add(new BindableItems() { Content = "Header " + i.ToString() });
            }
            MyNavigationView.MenuItemsSource = bindableItems;
        }

    public class BindableItems
    {
        public string Content { get; set; }
    }

**Expected behavior**

Expecting Footer Item to also show selection on left side of MenuItem

**Screenshots**

![sc](https://user-images.githubusercontent.com/6171200/101680629-f972a180-3a86-11eb-9227-6c47732ef92f.gif)

**Version Info**

NuGet package version: **Microsoft.UI.Xaml 2.5.0**

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  No   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@avknaidu any idea if this was introduced with Winui 2.5 or if the issue was present in earlier versions of the package?

**Comment by avknaidu** [comment]
@StephenLPeters I think `FooterMenuItems` was introduced in 2.5.

**Comment by StephenLPeters** [comment]
It was present in the 2.4 prerelease packages as well.  If your not sure its okay, but would be useful for when someone gets time to fix this

**Comment by chingucoding** [comment]
I would like to look into this.

**Comment by chingucoding** [comment]
@avknaidu The issue is being caused by the usage of the MenuItemTemplate. As a temporary workaround, you can try to use NavigationView without a datatemplate, e.g. by implementing your own "ElementFactory" and pass the processed collection to NavigationView.

**Comment by hawkerm** [comment]
Any update on this? The NavigationView sharing the Data Template for everything really makes it hard to use. It's very weird for hierarchical data of different types as well. Is there any reason the PR just stalled out over a year ago https://github.com/microsoft/microsoft-ui-xaml/pull/3811?
