### ISSUE TITLE
Compile Error when setting Window Title in MainWindow.xaml in a Winui3 App (Packaged Desktop)

### ISSUE THREAD

**Issue by sibille** [microsoft/microsoft-ui-xaml#3795]
**Describe the bug**
Setting Window Title inthe  MainWindow.xaml in a Winui3 App (Packaged Desktop) causes the following error when compiling: 

```
The XAML Binary Format (XBF) generator reported syntax error '0x09C4' : Property Not Found	
```

**Steps to reproduce the bug**
1. Create a new Blank App, Packaged (WinUI in Desktop) with the WinUI Vsix (Preview 3)
2. Set the Title property on the MainWindow.xaml to "App1"
3. Build the app

**Expected behavior**
App should compile and show App1 as title

**Version Info**

NuGet package version: 

Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes|

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Repro App: [App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5673698/App1.zip)

Setting the title on the MainWindow.xaml.cs works as a workaround.

**Comment by mrlacey** [comment]
Dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/3689 ??

**Comment by sibille** [comment]
Oh, yes, exact same issue. 
Didn't see that one, sorry.
