### ISSUE TITLE
ToggleSwitch ignores click

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3796]
**Describe the bug**
Hi,
If I click by switch a little faster it doesn't change state. Take a look at the GIF. Looks like click ignored during an animation.

**Steps to reproduce the bug**
![](https://i.imgur.com/GvoZvbC.gif)

**Expected behavior**
The ToggleSwitch should change state independently how fast you clicked

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
This is not unique to Winui3, it occurs in system xaml as well.

**Comment by StephenLPeters** [comment]
I suspect that fixing this would require code changes, which would mean fixing this requires Winui3, however its possible there is a template change that would fix it.  @karenbtlai FYI for when you look at toggle switch.
