### ISSUE TITLE
Bug: Collection object reused when new control instantiated

### ISSUE THREAD

**Issue by mandalorianbob** [microsoft/microsoft-ui-xaml#3797]
In the MUX github it said if I was having a UWP issue to post it here.

So I've got a fairly complex custom User Control that's referencing another custom User Control for trying to layout a master/details view.

I have a PopupHost that is a Popup which has a Grid, which has a control of type CustomPopup.

CustomPopup has a layout control in it, DetailPaneLayout, which takes a collection of dependency objects of type DetailPane, and uses those to populate a ListView (master list) and and a ContentControl (with the selected details). These DetailPane objects are instantiated in CustomPopup, in the XAML.

One of those DetailPanes has a List of Vendors. That binding, and the template for the list of Vendors are also defined in CustomPopup. 

DetailPanes has a ContentProperty of type DetailPaneCollection, because XAML doesn't play well with Generics.

This allows me to put all the DetailPane objects directly into the XAML. Unfortunately, after the control is unloaded, if the control is ever recreated, it _reuses_ the DetailPaneCollection, and all of the Panes within it.

This is obviously hugely problematic, because the Pane objects are UIElements with databindings, which are now pointing at old data (not to mention the memory leaks from them holding references)

I therefore must call Clear() on the DetailPaneCollection when I unload the DetailPaneLayout control. This took me several days to figure out what was going on, because I'm instantiating brand new controls and yet getting old data.

This seems like it could be a bad issue to drag into Project Reunion. 

A min repro could be hard to make, but I'm willing if it will help solve this issue.

**Comment by StephenLPeters** [comment]
I'm having trouble picturing exactly what is going on from your description and could imagine a few things in the system that could cause something like this.  At the very least it would be helpful to see the xaml you are using, but event better would be that min repro app.

**Comment by mandalorianbob** [comment]
I have no idea why I didn't provide a snippet haha. Here's a little snippet to help explain - I'll start working on trying to get a min repro.

```xaml
<UserControl x:Class="CustomPopup">
<Grid>
    <local:DetailPaneLayout x:Name="DetailPaneLayout">
        <local:DetailPane HeaderLabel="First Pane Header">
            <StackPanel x:Name="FirstPaneContentPanel" />
        </local:DetailPane>
        <local:DetailPane HeaderLabel="Second Pane Header">
            <StackPanel x:Name="FirstPaneContentPanel" />
        </local:DetailPane>
    </local:DetailPaneLayout>
</Grid>
</UserControl>
```
Detail Pane is just a DO
```C#
[ContentProperty(Name = nameof(Pane))]
    internal class DetailPane : DependencyObject
    {
        public string HeaderLabel
        {
            get { return (string)GetValue(HeaderLabelProperty); }
            set { SetValue(HeaderLabelProperty, value); }
        }

        // Using a DependencyProperty as the backing store for Header.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty HeaderLabelProperty =
            DependencyProperty.Register(nameof(HeaderLabel), typeof(string), typeof(DetailPane), new PropertyMetadata(defaultValue: null));




        public UIElement Pane
        {
            get { return (UIElement)GetValue(PaneProperty); }
            set { SetValue(PaneProperty, value); }
        }

        // Using a DependencyProperty as the backing store for Pane.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty PaneProperty =
            DependencyProperty.Register(nameof(Pane), typeof(UIElement), typeof(DetailPane), new PropertyMetadata(defaultValue: null));


    }
```
And DetailPaneLayout has a Panes property set to be the Content Property
```C#
  public DetailPaneCollection Panes
        {
            get { return (DetailPaneCollection)GetValue(PanesProperty); }
            set { SetValue(PanesProperty, value); }
        }

        // Using a DependencyProperty as the backing store for Panes.  This enables animation, styling, binding, etc...
        public static readonly DependencyProperty PanesProperty =
            DependencyProperty.Register(nameof(Panes),
                                        typeof(DetailPaneCollection),
                                        typeof(DetailPaneLayout),
                                        new PropertyMetadata(defaultValue: new DetailPaneCollection(), OnPanesPropertyChanged));

 private static void OnPanesPropertyChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs eventArgs)
        {
            if (dependencyObject is DetailPaneLayout layout)
            {
                layout.SetPanes();
            }
        }
```

DetailPaneCollection is literally just
```C#
        public class DetailPaneCollection : List<DetailPane> { }
```

So I don't know if that helps, but I'll begin on a min repro. Hopefully just copying the relevant controls to a new proj will cause a repro.

**Comment by mandalorianbob** [comment]
Oh right - the version of the SDK I'm building against is 16299. Undoubtedly that's relevant.

**Comment by mandalorianbob** [comment]
[CachingBugMinRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5692605/CachingBugMinRepro.zip)
Oh, apparently it wasn't actually relevant. I'm in 16299, but I repro'd it in 19041 too.

So if you open the popup, then close it, when you reopen it, you'll see that it did not _not_ recreate the collection object. It's very obvious with this one, because it just makes multiples.

Even weirder, is for my app it does not create multiples, but it makes sense that it does, I guess. It's holding on to that DetailPaneCollection reference, so it makes sense that it's not clearing out the old ones. But I'm not sure why I never saw that behavior on my app. I suppose it's possible the multiples were just being hidden by the UI.

From my understanding when you have a Content Property, the default value should be "new Collection()" because if you put null, InitializeComponent fails. So if it's not new, and not null, I dunno what else it could be. But it appears that it's keeping the default value, instead of getting rid of it when the control goes?

**Comment by StephenLPeters** [comment]
@mandalorianbob Thanks for all the info, this should be actionable with your demo app. The team is very busy and many people are taking time off at the end of the year so I suspect we wont get to this until January.

**Comment by mandalorianbob** [comment]
FWIW, I did run into an issue where I had a crash that seemed related to this on first launch, which is bizarre. But I got "Element already child of another element" on first launch. But I can't seem to reproduce it which is disconcerting.

When you do find out what's up, any work arounds to try to prevent this would be appreciated.

**Comment by mandalorianbob** [comment]
I did find a work around. 
```C#
DetailPaneCollection _instanceCollection = new DetailPaneCollection();

 public DetailPaneCollection Panes
        {
            get { return _instanceCollection; }
            set { SetValue(PanesProperty, value); }
        }

public static readonly DependencyProperty PanesProperty =
            DependencyProperty.Register(nameof(Panes),
                                        typeof(DetailPaneCollection),
                                        typeof(DetailPaneLayout),
                                        new PropertyMetadata(defaultValue: null, OnPanesPropertyChanged));

 private static void OnPanesPropertyChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs eventArgs)
        {
            if (dependencyObject is DetailPaneLayout layout && eventArgs.NewValue is DetailPaneCollection newCollectionValue)
            {
                layout._instanceCollection = new DetailPaneCollection();
                layout._instanceCollection.AddRange(newCollectionValue);
                layout.SetPanes();
            }
        }
```
This seems to work, though it's a bit weird..
I'm curious ... is this not a fundamental design issue with the way DependencyProperties work with default values? If your default value is a reference type how could you not have _every_ instance of the DependencyObject have the same value? It appears that once it's applied, it's sealed, and the value doesn't change. So like ... every single instance of the DO will have the same reference by default, right?

There doesn't seem to be any mention of this in the docs. 

The UIPropertyMetadata/FrameworkPropertyMetadata don't seem to provide any help here either. 

I'm very confused about how this could ever work. There's loads of examples of doing XAML Content collections this way, but it seems like at a very fundamental level it could _never_ work haha.

**Comment by mandalorianbob** [comment]
Okay so I found the PropertyMetadata.Create function with the factory delegate. As pointed here: https://devblogs.microsoft.com/oldnewthing/20191002-00/?p=102950 this is incorrect and doesn't work as expected because the factory delegate is called constantly. 

Thankfully, Raymond posted the correct solution. https://devblogs.microsoft.com/oldnewthing/20191003-00/?p=102959

It keeps the Dependency Registration as is, has a DefaultValue of null, and then you assign a value prior to the InitializeComponent call - which is a remarkably simple solution, though one that escaped me the whole time.

So ultimately, this is a two-fold issue.

First and easiest is the documentation issue, which I'll locate the relevant docs and submit an issue there.

Second is that ... this solution seems like it poses a _lot_ of issues, as that blog even points out.

> One is that the local value is fairly high in the precedence of value sources, sitting above template properties, implicit styles, style triggers, template triggers, style setters, the default style, and inheritance. Setting a local value means that the dependency property cannot be styled, triggered, or inherited.

> Another is that somebody might try to reset the property back to the default by calling Clear­Value. In that case, the value of the dependency property returns to the default value, which we implicitly declared as null

This seems bad. Anyway, I guess the initial issue is "solved" as such. Boy I wish there was an explanation as to _why_ the DO can't store its own default that it gets from the PropertyMetadata.

**Comment by StephenLPeters** [comment]
@MikeHillberg or maybe even @oldnewthing FYI
