### ISSUE TITLE
TreeView: Large amount of space is reserved for checkbox

### ISSUE THREAD

**Issue by knightmeister** [Microsoft/microsoft-ui-xaml#380]
**Describe the bug**
A large amount of space is reserved for the selection checkbox and chevron as can be seen in the below image. The checkbox space is reserved even when the selection mode is set to None.

**Steps to reproduce the bug**
All TreeViewItems exhibit this behaviour.

**Expected behavior**
The space for the checkbox should not be reserved unless required. At the minimum, there should be a way of controlling this.

**Screenshots**
![image](https://user-images.githubusercontent.com/1528425/53793367-d944b300-3f81-11e9-8181-3b6aa5df4ab2.png)

**Version Info**
1809

NuGet package version:

**Comment by jevansaks** [comment]
@predavid please find the figma file and then we can fix this to match the design comp.

**Comment by jevansaks** [comment]
Here's the values from the spec:
![image](https://user-images.githubusercontent.com/20667023/54157845-61a1d880-4406-11e9-9485-e5f4de70928f.png)
