### ISSUE TITLE
WebView2: UWP App crashes when minimizing maximizing or resizing.

### ISSUE THREAD

**Issue by cdhawan** [microsoft/microsoft-ui-xaml#3802]
**Describe the bug**
UWP App crashes when minimizing/maximizing/resizing. This may not happens at once, but if we keep using the app for some time, we can repro this.

**Steps to reproduce the bug**

Create a UWP app with WebView2
Set WebView2 source uri to "https://www.microsoft.com"
Launch the app
Minimize and maximize the app (or resize) for few times.
Keep the app minimized for some time 
Try to minimize and maximize the app (or resize) for few times again.

App crashes. 

**Expected behavior**
App shouldn't not crash.

**Screenshots**
None

**Version Info**
WinUI 3.0 with WebView2 Preview 3

Windows app type:
UWP | Win32
-- | --
Yes | No

Windows 10 version | Saw the problem?
-- | --
Insider Build (xxxxx) | < N/A
Oct 2020 Update (19042) | Yes

Device form factor | Saw the problem?
-- | --
Desktop | Yes
Xbox | Don't know
Surface Hub | Don't know
IoT

**Additional context**
None

**Comment by BobbyESP** [comment]
Nice!! Infinite thanks!
