### ISSUE TITLE
XamlControlsResources "using:Microsoft.UI.Xaml.Controls"  -> Namespace NOT found after installed nugget 2.5

### ISSUE THREAD

**Issue by gmgallo** [microsoft/microsoft-ui-xaml#3803]
**Describe the bug**

The namespace Microsoft.UI.Xaml.Controls is not available after installing WinUI 2.5 NuGet package on a new project.

**Steps to reproduce the bug**

In Visual Studio create a new WPF project targeting .NET Framework 4.8.
Add WinUI 2.5 NuGet using "Manage NuGet Packages" by right clikcikng on the project explorer.
After installation Microsoft.UI.Xaml shows in the list of References as installed.
Add the using directives to App.Xaml and MainWindow.Xaml.cs 
Compile the clean project skeleton (nothing else added).
Got a bunch of errors:
XDG0008	The name "XamlControlsResources" does not exist in the namespace "using:Microsoft.UI.Xaml.Controls".
XLS0414	The type 'XamlControlsResources' was not found.
On MainWindow.Xaml.cs you can see that .UI. sub-namespace is missing.

**Expected behavior**

Compile without errors.

**Screenshots**

**Version Info**

Visual Studio 16.8.3
WinUI 2.5
NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  Yes       |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by gmgallo** [comment]
What is the installation path for this package, and the namespace files?
This may be an easy fix.

**Comment by huoyaoyuan** [comment]
`Microsoft.UI.Xaml` package is for UWP project. How can you install it to WPF project without a warning?
It takes no effect to WPF.

**Comment by gmgallo** [comment]
Hi, I started writing WPF in 2018 for embedded projects with Windows IoT. Now I want to use these controls in desktop applications as described in [this page](https://docs.microsoft.com/en-us/windows/apps/winui/), with Xaml Islands (until WinUI 3 gets released), so, I followed the instructions in this page [Getting started with the Windows UI 2.x Library](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started)
In this step:
Open an existing project, or create a new project using the Blank App template under Visual C# -> Windows -> Universal, **or the appropriate template for your language projection.**
The highlighted part made me believe that it will work with other frameworks like WPF and Windows Forms. So, should I manually install xaml islands first?

**Comment by StephenLPeters** [comment]
Unfortunately you cannot use release candidate builds with xaml islands. This is because you need the DLL's to be copied locally for a WPF app to reference them and that doesn't happen with a framework package, which is they way our release canditates work.  You'll instead need to use a prerelease package like this one: https://www.nuget.org/packages/Microsoft.UI.Xaml/2.5.0-prerelease.201202003 Which should be the same as the 2.5 release but with the preview APIs included as well.

**Comment by gmgallo** [comment]
Thanks for the clarification, I'll try that.
By the way, in my initial line I meant to say I was writing UWP since 2018, not WPF.
