### ISSUE TITLE
ContentDialog Input not working for TextBox

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/microsoft-ui-xaml#3804]
**Describe the bug**
I tried create ContentDialog with input like TextBox or PasswordBox, but text input is not working. CheckBox (like in sample gallery) is okay. Shortcuts are okay and deleting chars (backspace or delete) is okay too. Content of ContentDialog is created as User Control (from WinUI 3) and testing it as Control in page is its behavior ok too. Is this behavior intentional?

**Steps to reproduce the bug**
ContentDialog with TextBox (or PasswordBox).

**Actual behavior**
Input from keyboard not working, Ctrl+V is okay, backspace is okay too.

**Version Info**
- Tested sample from WinUI 3 branch sample gallery.

Sample gallery version: 1.2.16.0

Windows 10 version: 20211
Settings of project
- Min. version: 17763
- Target version: 18362

**Comment by stmoy** [comment]
I think there's still an issue in the XCG which needs to update the ContentDialog page to use XamlRoot. I wonder if this is a symptom of that.

**Comment by JanRajnoha** [comment]
Xaml root is not problem. I reported bug about it, but this is new. I assign into property button, which worked okay, everything was okay, but when I try text input, nothing.

**Comment by stmoy** [comment]
Thanks for clarifying @JanRajnoha - in that case, I agree with @YuliKl that it sounds like this might be a platform issue.

**Comment by StephenLPeters** [comment]
@JanRajnoha do you know if this issue is unique to Winui3 or if its present in system xaml as well?

**Comment by mdtauk** [comment]
This may be related to an issue that Windows Terminal has found
https://github.com/microsoft/terminal/pull/8403#issuecomment-744827896

**Comment by DHowett** [comment]
Thanks for the link-up @mdtauk! Yeah, this is impacting us on system islands.

**Comment by JanRajnoha** [comment]
@StephenLPeters ContentDialog with text input works fine in UWP and I suppose it is same bug which @mdtauk wrote.

**Comment by DHowett** [comment]
@StephenLPeters Yeah -- Terminal is an app using system Xaml (Islands) that has the same issue.

**Comment by StephenLPeters** [comment]
@DHowett a fix to this issue would require system xaml changes and wouldn't go down level, thus I've marked the issue as needs-winui-3 to be addressed after winui3 is shipped.  Has Terminal team found a work around that we can post back here?

**Comment by DHowett** [comment]
No. The workaround we've chosen is to not use ContentDialogs.

**Comment by JanRajnoha** [comment]
Okay, but I think this problem will be more Serious after releasing version ready for production apps, so avoiding to use it is not good idea. 😕🤔

**Comment by JanRajnoha** [comment]
Input is working again, closing issue

**Comment by DHowett** [comment]
I believe someone on the team should reopen this. It's still an issue on system Xaml Islands, and it will be an issue forever. It should only be closed when WinUI3 hits GA :smile:

**Comment by StephenLPeters** [comment]
Right now we have a very very high bar for moving fixes back into system xaml.  I don't think this will meet that bar, and since it is fixed in winui3 I'm going to keep this closed.

**Comment by ShortDevelopment** [comment]
This bug can be fixes for System-Xaml / Xaml-Islands by attaching a `ITextInputProducer` to the `CoreWindow`.

https://github.com/ShortDevelopment/ShortDev.Uwp.FullTrust/blob/e2b3df75c499716f7cc586c1793426a2bee34377/ShortDev.Uwp.FullTrust/ShortDev.Uwp.FullTrust/Activation/CoreWindowActivator.cs#L104-L116

> **Warning**
> This is a private API that may change at any time!
