### ISSUE TITLE
Revert color changes for ListBox

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#3808]
**Describe the bug**

We checked in sweeping color changes in #3728. This PR had the unintended consequence of partially updating colors used by ListBox such that this control no longer meet contrast ratio requirements. We need to undo the problem by reverting a few changes to make sure ListBox can continue to use the colors defined in the OS generic.xaml

**ListBox**
The background of selected ListViewItems no longer meets contrast ratios, it's almost invisible.
"updated" (incorrect)

![image](https://user-images.githubusercontent.com/13142665/102150854-62ab3980-3e26-11eb-82c3-f6a25cac3e32.png)
![image](https://user-images.githubusercontent.com/13142665/102150872-6ccd3800-3e26-11eb-843a-769a9a81c8b0.png)

previous (correct)
![image](https://user-images.githubusercontent.com/13142665/102150940-8a9a9d00-3e26-11eb-840e-a08ce38c4cd0.png)
![image](https://user-images.githubusercontent.com/13142665/102150972-9b4b1300-3e26-11eb-9823-aa6a7cf66d7b.png)

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/30831230)

**Comment by chingucoding** [comment]
I would like to work on this.
