### ISSUE TITLE
NavigationView documentation is outdated.

### ISSUE THREAD

**Issue by bkaankose** [microsoft/microsoft-ui-xaml#3814]
**Describe the bug**
https://github.com/microsoft/microsoft-ui-xaml/blob/dfbe38bfb2996dfaa2f09544c4e86aa69ccc906b/dev/NavigationView/docs/rendering.md

This document says that '**SettingsNavPaneItem**' is part of the templated controls. However, I think recent changes in the control made this templated part to be moved somewhere dynamic. Potentially Pane Footer area.

**Steps to reproduce the bug**

1) Try to retrieve this templated part of the control in OnApplyTemplate

**Expected behavior**
Settings button's NavigationViewItem is returned.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.5.0

**Bug doesn't occur on version 2.4.0. So the documentation is valid for 2.4.0** 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Unknown (Potentially yes) |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This bug is related to documentation itself. However, not sure if fixing the documentation or fixing the actual code and re-name the element as '**SettingsNavPaneItem**' should be done. GetTemplateChild might not work for dynamically generated content in OnApplyTempalte call. Therefore, fixing this on the code itself can be challenging.

**Comment by StephenLPeters** [comment]
@chingucoding You authored that doc, right? Would you like to update it?

**Comment by chingucoding** [comment]
Sure! Feel free to assign me to the issue.
