### ISSUE TITLE
WinUI 3.0 Preview 3 Applications crash on startup in Windows Insider Build 21227

### ISSUE THREAD

**Issue by smj389** [microsoft/microsoft-ui-xaml#3815]
**Describe the bug**
WinUI 3.0 Preview 3 Applications (both UWP and Desktop and both C# and C++) crash on startup in Windows Insider Build 21227. This behaviour was not observed in earlier builds.

**Steps to reproduce the bug**

1. Load Visual Studio 2019 Preview 2.
2. Create a new WinUI 3,0 Preview 3 Project (UWP or Desktop, C# or C++) 
3. Build the Application (x86 or x64 - both exhibit this behaviour)
4. If you attempt to debug the Application on Windows Insider Build 21227, the VS Debugger will crash.
5. If you deploy the Application on Windows Insider Build 21227 and run it (e.g. from Start) it will crash.

**Expected behavior**
The Application to load. 

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| <Yes> | <Yes> |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21227)              | Yes   |
| Insider Build (20270)               | No   |

If it helps, on each crash (both x64 and x86) there is a watson report with the following sort of details:
Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	cf710d84-b57a-45d1-927b-35e5575541be_1.0.0.0_x64__pzhjvzqrkcdyt
Application Name:	praid:App
Application Version:	1.0.0.0
Application Timestamp:	5f8de3c6
Fault Module Name:	combase.dll
Fault Module Version:	10.0.21277.1000
Fault Module Timestamp:	5ebfb7ba
Exception Code:	c0000602
Exception Offset:	0000000000213e49
OS Version:	10.0.21277.2.0.0.256.48
Locale ID:	2057
Additional Information 1:	f848
Additional Information 2:	f848ae3eb9da603e3d133c649245b573
Additional Information 3:	6c20
Additional Information 4:	6c20af286a841c116e408ceff9fafd07

And under the debugger:
Problem Event Name:	APPCRASH
Application Name:	msvsmon.exe
Application Version:	16.9.733.0
Application Timestamp:	5fc92e7f
Fault Module Name:	combase.dll
Fault Module Version:	10.0.21277.1000
Fault Module Timestamp:	5ebfb7ba
Exception Code:	c0000602
Exception Offset:	0000000000213e49
OS Version:	10.0.21277.2.0.0.256.48
Locale ID:	2057
Additional Information 1:	19be
Additional Information 2:	19be555bc0752265a36ee49cbe0b2fac
Additional Information 3:	6daa
Additional Information 4:	6daab691c59d0ef5816d18d88c9c7b7d

**Comment by syndek** [comment]
I'm having the same issue on build 21277.1000, but if my memory serves correctly, this was happening to me before I actually installed an Insider build. I don't have a machine to test this on right now, but I'm pretty sure this is unrelated to the Windows build you use.

**Comment by robloo** [comment]
WinUI 3 was to decouple itself from the OS to prevent these sorts of issues and incompatibilities. I am very curious to know what is causing this from a technical standpoint.

**Comment by JanRajnoha** [comment]
I have this problem too. No workaround, no response from VS team, where i report it as bug, because one day I updated both, Windows and VS, and don't think this should be related to Windows.

**Comment by gavinwilliams** [comment]
Same issue on build 21286.1000 for both Desktop and UWP apps. UWP app launches and then the debugger crashes, Desktop app doesn't even launch. The same happens with the XAML Controls Gallery app.

**Comment by codendone** [comment]
Thanks for the report. We believe this is an issue we recently fixed, and are working to confirm that.

**Comment by gavinwilliams** [comment]
> Thanks for the report. We believe this is an issue we recently fixed, and are working to confirm that.

Just curious, is there a workaround for those of us who are super keen to have a play with WinUI in the mean time?

**Comment by codendone** [comment]
@gavinwilliams Unfortunately, the only workaround for this issue is to use an older build of Windows. And #3954 just reported a similar issue on a newer build which should contain the fix here, so we need to investigate that.

**Comment by gavinwilliams** [comment]
@codendone that's frustrating, more so for you guys I assume, I know quite a few Windows dev's are all running Insider builds so the feedback on WinUI 3 must be limiting.

**Comment by codendone** [comment]
@gavinwilliams Yes, certainly a very unhappy situation. On the plus side, we are planning to ship a Preview 4 in early-mid Feb, which will have the fix.

**Comment by anawishnoff** [comment]
This bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!

**Comment by krschau** [comment]
Closing as fixed. Please open a new issue if you see a similar problem in the future.
