### ISSUE TITLE
ObservableCollection binding not working for UWP

### ISSUE THREAD

**Issue by IQBigBang** [microsoft/microsoft-ui-xaml#3816]
**ObservableCollection bound to a ListView does not correctly update the ListView on UWP**
When a ListView is bound to an ObservableCollection with `x:bind`, it does not update when the collection is changed.
This bug only works for the UWP platform. Creating a _Packaged Desktop_ project works properly.

1. Create a new Blank App (WinUI in UWP)
2. Modify the code like this:
**MainPage.xaml**
```xml
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <ListView ItemsSource="{x:Bind Items, Mode=OneWay}"></ListView>
        <Button Content="Add" Click="Button_OnClick"></Button>
</StackPanel>
```
**MainPage.xaml.cs**
```csharp
public sealed partial class MainPage : Page
{
    public ObservableCollection<string> Items = new ObservableCollection<string>();
    public MainPage()
    {
        this.InitializeComponent();
        Items.Add("A");
        Items.Add("B");
    }
    private void Button_OnClick(object sender, RoutedEventArgs e)
    {
        Items.Add("Next");
    }
}
```

**Expected behavior**
The list is visibly updated when the button is clicked.

**Screenshots**
![Result on the UWP platform.](https://user-images.githubusercontent.com/19934663/102373081-1f84ce00-3fc0-11eb-851b-2a37ad5b4ba7.PNG)
![Expected result. Works on the Desktop platform.](https://user-images.githubusercontent.com/19934663/102372731-cc128000-3fbf-11eb-85d2-b8723f202681.PNG)

**Version Info**
NuGet package version: 
Microsoft.NETCore.UniversalWindowsPlatform 6.2.10
Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Windows 10 Home Version 20H2            |  Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
Sorry if this is my error in the code, but I really don't understand why it works on Desktop and not on UWP so I assume it is a bug.

**Comment by StephenLPeters** [comment]
@stevenbrix or @Scottj1s was this an issue that was fixed through cswinrt with desktop? If so, would this be fixed with UWP being on .net 5?

@MikeHillberg FYI

**Comment by Scottj1s** [comment]
The UWP support for WinRT in NetCore doesn't know about the new MUX interface IDs for INotifyPropertyChanged, etc.  Not sure how this could work without that support.

**Comment by MikeHillberg** [comment]
Until there's support for .Net5 in UWP, WinUI3 UWP apps need to use the INotifyCollectionChanged and INotifyPropertyChanged from the Microsoft namespace rather than the System namespace, which breaks ObservableCollection.

The Xaml Controls Gallery app has an implementation of ObservableCollection that implements the right interfaces for UWP though. You can [copy it from there](https://github.com/microsoft/Xaml-Controls-Gallery/blob/winui3preview/XamlControlsGallery/CollectionsInterop.cs).

**Comment by IQBigBang** [comment]
Ok thanks, but I think this should be mentioned somewhere in the documentation as I was going through the documentation for [ItemsSource](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.itemscontrol.itemssource?view=winui-3.0-preview#Microsoft_UI_Xaml_Controls_ItemsControl_ItemsSource), which points to the [INotifyCollectionChanged](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.inotifycollectionchanged?view=dotnet-uwp-10.0&preserve-view=true) interface from the System namespace.

**Comment by MikeHillberg** [comment]
Agreed, sorry it was difficult to find. I created an [Issue on the doc page](https://github.com/MicrosoftDocs/winui-api/issues/42). (There's also info in the [release notes](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#known-issues).)
