### ISSUE TITLE
Discussion: Can we talk about the new Alarms and Clock app UI changes...

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#3817]
# Can we talk about the new Alarms and Clock app UI changes...

So as a little surprise, an updated Alarms & Clock app has shown up for Windows Insiders.  There have been lots of changes, but a couple I think should be called out and discussed.

The Time Pickers being used have ditched the standard WinUI/Xaml controls, and are doing something much more customised.
These changes seem to address some of the issues that have been brought up here, and I was hoping the app designers could perhaps share some thoughts, and maybe discuss how some of these changes could work their way into the standard controls?

## Screenshots

![Screenshot (25)](https://user-images.githubusercontent.com/7389110/102397368-b3ad6000-3fd5-11eb-885a-9a1e5c685af1.png)
![Screenshot (29)](https://user-images.githubusercontent.com/7389110/102397374-b445f680-3fd5-11eb-8db1-7c4846fdfd82.png)
![Screenshot (30)](https://user-images.githubusercontent.com/7389110/102397376-b4de8d00-3fd5-11eb-89e0-5db02ec16f2b.png)

## Behaviour

The individual digits can accept keyboard input, and also support using the spin buttons above and below for changing the value, with a tap, or a tap and hold with a RepeatButton behaviour.

There are no flyouts, which were useful for making precise value changes with Touch input, but is that mitigated, by use of the spin buttons above and below?

The digits are larger, so remain visible better when your finger is hovering over the spin button or pressing it.

How could this control work at the size of a regular control, keep the touch friendly behaviour, and accept keyboard input?

## Related Links

Below are previous issues that have discussed or proposed changes to these controls.  
**Now Microsoft has seen fit to make changes, maybe its time for a wide ranging conversation about these kinds of controls.**

Proposal: Improve Time/DatePicker to be more desktop enabled, accessible, and user-friendly #918
Proposal: Option to select seconds in the TimePicker control #1440
Proposal: Duration Picker #1807
Proposal: TimePicker should be split into single digits again. #905
Proposal: Ability to type a date into CalendarDatePicker #735 (behaviour related, but for Calendar and Date rather than Time)

**Comment by mdtauk** [comment]
There are more screenshots here looking at the New App UI

https://medium.com/changewindows/alarms-clock-10-2012-a-closer-look-3f47718bdfa6

Some other off topic things I have noticed.
- The CommandBars have been replaced with bottom aligned Buttons - maybe this is a direction other apps will move towards?
- There are "Card" like items in some of the views, which looks like a UI affordance that feels fluent and modern.
- Typography is a little odd, what we have seen with newer Fluent UIs is moving away from light weight larger text, but this seems to be using these lighter weights in a way that feels a little pre-fluent...

![image](https://user-images.githubusercontent.com/7389110/102407838-a481de80-3fe4-11eb-903c-9f27986388d2.png)
_Bye Bye Command Bar_


![image](https://user-images.githubusercontent.com/7389110/102407621-47862880-3fe4-11eb-8f93-db8f2673fa6f.png)
![image](https://user-images.githubusercontent.com/7389110/102407692-62f13380-3fe4-11eb-9f3b-608fa5a625db.png)
_Card like UI_

**Comment by StephenLPeters** [comment]
@YuliKl FYI

**Comment by Poopooracoocoo** [comment]
My reactions:
I hate the side navigation. Takes up so much space unnecessarily and you don't have labels. 
The cards largen on hover, something I thought the designers had finally figured out that it is a bad experience. 
The new design doesn't use the new Fluent UI icons. 
The tooltips still have a bug with them in that the outline appears at full opacity during transitions. 
It's funny that all of the inbox apps that use WinUI have acrylic. 
Google has gone with a card UI and now they've significantly reduced the amount of "cards" in their UI, most lacking their shadows now. 
The modals remind me of what's going on in the GNOME world with Libhandy. Microsoft should've gone with such "adaptive" modals that automatically become fullscreen on smaller windows. 
I never really liked Alarms & Clock, and the new design doesn't really improve it. It's something I'd access more often if Windows Search had GNOME-like app integration and shortcuts. The reordered navigation and new home page is an improvement though, that's for sure. 
(most of what I said here was covered by martin and in the changewindows article he linked, but just saying it anyway before i forget :P )

**Comment by mdtauk** [comment]
To make it clear, I am happy with the new design, and I think there are some changes which are very interesting and curious.

Some UI changes feel like a shift in approach, but without any formalised documentation or conversation, I could be reading too much into some of these changes.

Buttons aligned to the bottom, replacing the Application Bar.  I am wondering if Microsoft feels that the AppBar is somewhat of a hang over from Windows Phone days?

Looking at the new Theme Resources in the **design token** branch, there are specific layer and card resources which made me assume Cards were becoming a formalised UI pattern.  This app seems to be evidence of this.

I would speculate that this is part of the push to get Windows 10X out there with a refreshed suite of Inbox apps.  So if we see more inbox apps get insider refreshes, we will be able to see which UI patterns permeate through all the apps.

The side aligned NavigationView is fine as a change, but when the window is narrow, it feels like it should switch to top orientated, I submitted it as feedback https://aka.ms/AAamv66

----

I wanted to focus this conversation a little on the changes to the existing app patterns, rather than a general do you like or dislike the design.  **Specifically the Time Picker controls which replace standard WinUI Controls, for a custom solution.**

**Comment by shaheedmalik** [comment]
I hate the side navigation as well as the color used for the Navigation Bar is not the same color as the Feedback Hub. It seems as Alarms and Clock has inverted the navigation menu color from the standard color to the background color and the background color to the navigation menu color.

The lack of back button in the Navigation menu stands out as well. It also doesn't support the Taskbar back button while in Tablet Mode.

**Comment by mdtauk** [comment]
The Card elements are lighter on a darker background, so it makes sense to darken the main area to accommodate for that.

I think when the new Design Tokens are in place, the default Black and White background colours will change.

Feedback Hub may need to be one of the next apps to get updated.

**Comment by shaheedmalik** [comment]
> The Card elements are lighter on a darker background, so it makes sense to darken the main area to accommodate for that.
> 
> I believe when the new Design Tokens are in place, the default Black and White background colours will change.
> 
> Feedback Hub may need to be one of the next apps to get updated.

My thing is the Navigation Menu isn't the same color.

**Comment by mdtauk** [comment]
> > The Card elements are lighter on a darker background, so it makes sense to darken the main area to accommodate for that.
> > I believe when the new Design Tokens are in place, the default Black and White background colours will change.
> > Feedback Hub may need to be one of the next apps to get updated.
> 
> My thing is the Navigation Menu isn't the same color.

I do prefer the colours used for the new Alarms app, I think the contrast works well, and it better represents the fact that Acrylic looks lighter in the Dark Theme, so should look lighter with it's fallback colour

**Comment by Jaiganeshkumaran** [comment]
> I hate the side navigation. Takes up so much space unnecessarily and you don't have labels.

@Poopooracoocoo I agree that the hamburger menu is ugly and needs to be reconsidered but on a larger screen, it's better since without the app feels empty. Maybe on smaller window sizes put the navigation view on the top.

**Comment by mdtauk** [comment]
> > I hate the side navigation. Takes up so much space unnecessarily and you don't have labels.
> 
> @Poopooracoocoo I agree that the hamburger menu is ugly and needs to be reconsidered but on a larger screen, it's better since without the app feels empty. Maybe on smaller window sizes put the navigation view on the top.

One solution would be at a certain width, the NavigationView switches to top orientation

**Comment by Jaiganeshkumaran** [comment]
One thing that I don't like with these newer apps is that they have a full-screen settings page instead of a side panel where 70% of the screen space is plain white or black by left aligning everything. Maybe on a 13-inch device, you would not see but on a larger display, it doesn't look good.

**Comment by mdtauk** [comment]
> One thing that I don't like with these newer apps is that they have a full-screen settings page instead of a side panel where 70% of the screen space is plain white or black by left aligning everything. Maybe on a 13-inch device, you would not see but on a larger display, it doesn't look good. Full-screen pages should be used only for pages that have a lot of content that needs to fit without a lot of scrolling.
>

I think those apps which originally had very few settings available, felt they could use sidebars or flyouts for them, have come to realise having an entire page makes it easier to add more settings as needed, and so much so, that the NavigationView has a consistent location for the Settings Page.

I happen to like the idea of a settings page, and find the Office UWP apps in particular, very out dated with it's sidebar settings.  After all, this was a Windows 8 UI pattern, and makes it harder to focus on the actual settings, if it shares screen space with everything else.

**Comment by Jaiganeshkumaran** [comment]
@mdtauk No you are wrong. Even if more settings are added they are added at the bottom and not in the side making it really bad requiring a lot of scrolling just to see a few options. Example Apps & features vs Programs & features. Even Visual Studio can fit may options in a dialogue than UWP apps will full screen available to them.

![திரைப்பிடிப்பு (160)](https://user-images.githubusercontent.com/45227503/102630726-e8a2e980-4172-11eb-955c-15231acd096a.png)

![திரைப்பிடிப்பு (163)](https://user-images.githubusercontent.com/45227503/102630879-19831e80-4173-11eb-95d1-f483cb3b3b0e.png)

![திரைப்பிடிப்பு (164)](https://user-images.githubusercontent.com/45227503/102630946-328bcf80-4173-11eb-99a4-a71111305a83.png)

Third party apps using this pattern: 

![திரைப்பிடிப்பு (162)](https://user-images.githubusercontent.com/45227503/102630815-03755e00-4173-11eb-95d4-c26eedb388c0.png)

**Comment by mdtauk** [comment]
> @mdtauk No you are wrong. Even if more settings are added they are added at the bottom and not in the side making it really bad requiring a lot of scrolling just to see a few options. Example Apps & features vs Programs & features. Even Visual Studio can fit may options in a dialogue than UWP apps will full screen available to them.
> 

I didn't mean you **can't** add new settings with a sidebar view, but Calculator for example, is adding a Settings page, instead of the current button flyout it uses.

My main issue with Settings in a sidebar is that, it is an out-dated design pattern from Windows 8, and it feels cramped and harder to read, when all the App's UI is still visible.

Your image examples are slightly skewing the conversation, in that they are Maximised on a large display.  When the app is in a smaller window, the UI makes better use of the space - and these UIs need to work on small tablet displays, where the UI needs to fit in a smaller resolution, with higher DPIs.

![Screenshot (49)](https://user-images.githubusercontent.com/7389110/102631745-0443cb00-4146-11eb-8c1c-837c41b79cb2.png)

**Comment by Jaiganeshkumaran** [comment]
@mdtauk Apps should not waste a full page just for a some options that don't benefit from the full page frame model because they have put in the left. I would suggest putting each category next to each other on a larger screen and up and down on a smaller screen. Windows is not made only for small screen tablet users.

**Comment by Jaiganeshkumaran** [comment]
Why not something like this and remove content dialog max width limitations: 
![திரைப்பிடிப்பு (165)](https://user-images.githubusercontent.com/45227503/102632196-beeac200-4174-11eb-9514-6cdea20fe53f.png)

**Comment by Jaiganeshkumaran** [comment]
Responsive UI should not be mobile-first UI that doesn't optimize itself on larger screens but should be UI that is optimized and appropriate the current screen size.

**Comment by Jaiganeshkumaran** [comment]
Full screen pages should be full screen only they fit the screen. This is a fundamental flaw in Modern UI and should be stopped or the page should be reconsidered to put overlay in the side on large window sizes

**Comment by mdtauk** [comment]
Modal Windows are something that modern apps try to avoid using.

>Responsive UI should not be mobile-first UI that doesn't optimize itself on larger screens but should be UI that is optimized and appropriate the current screen size. Full-screen pages should be full screen only they fit the screen. This is a fundamental flaw in UIs these days and should be avoided
>
We are not necessarily talking about mobile UIs here, Windows runs on many devices, including on displays running lower resolutions like 1024 x 768 (although I think 1366 x 768 is considered the baseline now)

![Screenshot (50)](https://user-images.githubusercontent.com/7389110/102635095-bb424580-414a-11eb-8f57-b22f0f6ccb1a.png)


Settings in particular tries to contain their page content so you will fit the Sidebar and Main Content at this kind of resolution.  When you widen the Window, the right hand side gets the additional content show up.

Then there is guidance on the amount of words you should have on each line, to ensure the readability of the content.  So even if the body text reflowed to fill the width, it would lead to a poor reading experience.

![image](https://user-images.githubusercontent.com/7389110/102635282-02c8d180-414b-11eb-825c-31bb456dc75f.png)
_[10 Tips On Typography in Web Design](http://babich.biz/typography-for-web/)_


Then you need to consider how much space may be taken up with a multi-tasking layout, with Settings on one side, and another app beside in TabletMode.
![Screenshot (51)](https://user-images.githubusercontent.com/7389110/102635147-ce551580-414a-11eb-9eb2-9e6a814616d1.png)
![Screenshot (52)](https://user-images.githubusercontent.com/7389110/102635148-cf864280-414a-11eb-960a-ff7bb9312aaf.png)
_You can see in the second screenshot, the Font's page is not handling the TextBox width properly_

**Comment by yoshiask** [comment]
> Your image examples are slightly skewing the conversation, in that they are Maximised on a large display. When the app is in a smaller window, the UI makes better use of the space - and these UIs need to work on small tablet displays, where the UI needs to fit in a smaller resolution, with higher DPIs.

This is certainly true, but the design should work reasonably well for all screen sizes. The current settings layout works pretty well on mobile/small portrait devices and 13" laptops, but even on my 15" (125% scaled) laptop (which is pretty standard for a laptop), it looks like it's wasting some space. UWP XAML has the VisualStateManager, isn't this exactly what it's for?

**Comment by mdtauk** [comment]
> > Your image examples are slightly skewing the conversation, in that they are Maximised on a large display. When the app is in a smaller window, the UI makes better use of the space - and these UIs need to work on small tablet displays, where the UI needs to fit in a smaller resolution, with higher DPIs.
> 
> This is certainly true, but the design should work reasonably well for all screen sizes. The current settings layout works pretty well on mobile/small portrait devices and 13" laptops, but even on my 15" (125% scaled) laptop (which is pretty standard for a laptop), it looks like it's wasting some space. UWP XAML has the VisualStateManager, isn't this exactly what it's for?

And it already is in place.  The right hand sidebar moves below the main Settings screen.  The Sidebar then collapses down as it gets even narrower.

On the larger screens, you do have the option to size the Window, so there is no need to maximise it in those circumstances.

But yes, for really large resolutions, the layout will not fill the screen/panel.  But it is not because of modern UI or mobile first, its just a fact of small content in a large view.
![image](https://user-images.githubusercontent.com/7389110/102656244-7549a980-416b-11eb-8519-ad6a7aafceb2.png)

![image](https://user-images.githubusercontent.com/7389110/102656280-8397c580-416b-11eb-861a-36e0a6a93e53.png)

![image](https://user-images.githubusercontent.com/7389110/102656314-93afa500-416b-11eb-809d-ad54d9db787d.png)

And of course, there is some non-modern UI that can't be resized at all...

![image](https://user-images.githubusercontent.com/7389110/102656375-b0e47380-416b-11eb-9cb0-e3596ea76711.png)

![image](https://user-images.githubusercontent.com/7389110/102656407-be99f900-416b-11eb-9b8d-5d3bcd134852.png)

**Comment by Jaiganeshkumaran** [comment]
> But yes, for really large resolutions, the layout will not fill the screen/panel. But it is not because of modern UI or mobile first, its just a fact of small content in a large view.

That's true but what I feel like is newer stuff are wasting more screen space. Whitespace should be used but 70% of the page should not be whitespace.

**Comment by Jaiganeshkumaran** [comment]
If the content is small obviously it will not fit but if there's a lot of content, I expect it to fit the screen. For example, the apps and features list would be better as a GridView

**Comment by mdtauk** [comment]
> > But yes, for really large resolutions, the layout will not fill the screen/panel. But it is not because of modern UI or mobile first, its just a fact of small content in a large view.
> 
> That's true but what I feel like is newer stuff are wasting more screen space. Whitespace should be used but 70% of the page should not be whitespace.
>
>If the content is small obviously it will not fit but if there's a lot of content, I expect it to fit the screen. For example, the apps and features list would be better as a GridView
>

With the examples you have given, it does not make sense for the UI elements to move into multiple columns.  And if they are to follow the correct recommendation with line length etc - there is no benefit from stretching the content to fill the width available.

Your suggestion for the Apps and Features page has some merit to it, however, you then run the risk of the different Settings screens being inconsistent.  They have come up with a set of rules that work 99% of the time, with the various screen and window sizes, so making exceptions for the 1 or two pages where it would be useful, would be inconsistent with the majority of other pages.

----

I wanted to take your comments on a bit, as you seemed to put the blame on the UI Framework, where it is a functional decision to offer an experience that works for the majority of times.  WinUI/Xaml is much more responsive and flexible than the older Win32 frameworks, but app design has moved on since then, and what you are criticising is a design choice, and not the fault of Xaml or the platform.

**Comment by Jaiganeshkumaran** [comment]
@mdtauk I never said this is a fault. This is a fault of Microsoft designers you can't see beyond 13-inch screens. It does make sense to put each section in columns because you can see more options with less scrolling.

**Comment by mdtauk** [comment]
> @mdtauk I never said this is a fault. This is a fault of Microsoft designers you can't see beyond 13-inch screens. It does make sense to put each section in columns because you can see more options with less scrolling.

If your goal is to fill the screen with stuff, then yes columns make sense.

If you wish to provide a sorted list of settings controls, then the hierarchy of how they are listed matters, and how much you provide in one view, can overwhelm.

We are all entitled to our opinions of course, but trying to be inclusive and sticking to best practices of UI design and Information architecture - should override an aesthetic or personal opinions.

**Comment by Jaiganeshkumaran** [comment]
@mdtauk Yes there should be empty space to not overwhelm the user but at the same time, it should not require a lot of scrolling just to see a few options when enough screen space is available.

**Comment by mdtauk** [comment]
> @mdtauk Yes there should be empty space to not overwhelm the user but at the same time, it should not require a lot of scrolling just to see a few options when enough screen space is available.
>
Long scrolling is probably more of a sign that the settings should be split onto multiple pages, or that there may be a need for expandable/collapsable sections of content.

Not necessarily a call for spreading it all out into multiple columns when the settings only make sense in a vertical single column view.

**Comment by Jaiganeshkumaran** [comment]
@mdtauk Why not change layout using VisualStateManager? Small screen users will get the same exact UI but wider screen users can see more by filling the screen more

**Comment by mdtauk** [comment]
> @mdtauk Why not change layout using VisualStateManager? Small screen users will get the same exact UI but wider screen users can see more by filling the screen more

VisualStateManager is already used to reposition the right hand sidebar content, to collapse and hide the left sidebar when narrow.

![image](https://user-images.githubusercontent.com/7389110/102679558-7fd66400-41a8-11eb-9b59-3f896bead840.png)
_Narrowest_

![image](https://user-images.githubusercontent.com/7389110/102679578-8ebd1680-41a8-11eb-8264-aa15244fd670.png)
_Narrow_

![image](https://user-images.githubusercontent.com/7389110/102679589-9977ab80-41a8-11eb-84a0-2b36e579dd60.png)
_Medium_

![image](https://user-images.githubusercontent.com/7389110/102679599-aa282180-41a8-11eb-9c5c-ae998930b595.png)
_Wide_

![image](https://user-images.githubusercontent.com/7389110/102679609-bad89780-41a8-11eb-9ab9-b73cd136f7f4.png)
_Wider_

**Comment by Poopooracoocoo** [comment]
I wonder if that settings page would look less empty if the content were centred or had larger margins on the sides. 

Something like Chrome's internal Polymer pages with its card UI? ~~Edge's pages have a larger width that increases the distance between a label and a toggle, and it lacks separators.~~ It's what Unigram does.

Photos is a better example than Alarms & Clock as you have more than one setting. :P

**Comment by mdtauk** [comment]
The Photos settings page has headered sections, which could probably be split into Settings Pages, like the Your Phone Settings screens.

Many apps will increase the left and right margins as the window gets wider already.  I am not sure centring will do much good for the perception of space used.  Also most UWPs call for left alignment, so things would start to look odd, especially if content from page to page is not of the same width.

**Comment by Jaiganeshkumaran** [comment]
This is the best-designed settings page in a UWP app according to me:
![திரைப்பிடிப்பு (167)](https://user-images.githubusercontent.com/45227503/102680251-a57d6080-41dc-11eb-88d9-8be107209c2c.png)

**Comment by mdtauk** [comment]
It's a nice layout, but it is only a few options, on a single page.

The Settings app itself, needs to accommodate a lot more variety of content and pages, which is why it has the widths and layouts that it does.

Alarms & Clock has a few settings, but not too many right now.

The only change I would make to it, is to move the About content to the right, as you see in Paint 3D and the right sidebar content in the Settings app.

**Comment by Jaiganeshkumaran** [comment]
One change that I noticed in Alarms and Clock is dialogs are light dismissable. Are there any plans to bring this to WinUI?

**Comment by mdtauk** [comment]
A nice touch with the TimePickers, is being able to use the scroll wheel while hovering over the value

**Comment by suchja** [comment]
Does anyone know how the overlay (meaning when you add a new timer or edit an existing) is realized? Is it a `ContentDialog`?

I'm not really aware of all the design guidelines, but what I found is that `ContentDialog` is supposed to inform a user. Here it seems it is used as a way for getting different information from the user. I'm planning on having something similar for a user to enter at least 10 different values (mainly text) and was wondering whether this is inline with the fluent design guidelines.
