### ISSUE TITLE
Crash when using TreeView on 15063 and lower and navigating back/forth

### ISSUE THREAD

**Issue by lukaszorg** [microsoft/microsoft-ui-xaml#382]
**Describe the bug**
Sometimes when I navigate several times to page which have TreeView control on it application crashes with Access Violation exception.

**Steps to reproduce the bug**
1. Create page with frame and button
2. Create another page with TreeView control
3. On button click navigate to page with TreeView control
4. Repeat until app crashes
Bug is can be only reproduced in release mode and only without attached visual studio.

**Expected behavior**
No crash

**Version Info**
NuGet package version: 
 Microsoft.UI.Xaml 2.0.181018003.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| April 2018 Update (17134)        | No |
| Creators Update (15063)           | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   | No   |
| Xbox                      | No   |
| Surface Hub          | no  |
| IoT                         | No    |

**Additional context**
Here you can see logs from WinDbg https://github.com/lukaszorg/xaml-defect/blob/master/WinDbgException.txt. 
Windows_UI_Xaml!DirectUI::DependencyObject::Deinitialize+0x35 this object is an instance of TreeView control

**Comment by MikeHillberg** [comment]
In step 4, are you navigating to a new instance of the page with the TreeView control?  Or are you navigating back/forth between two pages?  Could you add the Xaml files?

**Comment by jevansaks** [comment]
@lukaszorg if you've got this under windbg would you be able to take a heap dump at the time of the crash and attach it to this issue? Run:

```
.dump /ma heap.dmp
```

**Comment by lukaszorg** [comment]
Heap dump can be found here: https://drive.google.com/open?id=17MNefD185KM2qLSlQeY3MU767blDH5E3  

In step 4 I'm navigating to new instance of the page with TreeView.

**Comment by jevansaks** [comment]
Awesome, thanks. We'll investigate and see if there's something we can do to work around this downlevel XAML framework bug from the controls side.

**Comment by jevansaks** [comment]
Looking at the heap dump we see that the framework is crashing accessing a ItemTemplateSelector property, so we might be able to work around this by holding a strong ref to the ItemTemplateSelector property. Need to make a repro and then validate this workaround.

**Comment by jevansaks** [comment]
Sorry for the delay here. I tried to write an app as you described but I could not get it to crash running in either release or debug , with or without a debugger attached, on 15063.

Can you provide a repro app?

**Comment by jevansaks** [comment]
Closing until we get more details.

**Comment by jevansaks** [comment]
Thank you for sharing the repro! I'll reopen this issue and we can try to repro it locally.

**Comment by lukaszorg** [comment]
Probably there is some issue with disposing local resources.
Moving DataTemplateSelector  to global resources fixed this issue.

**Comment by jevansaks** [comment]
That's very helpful information! It confirms the theory that it's the ItemTemplateSelector field. Unfortunately I see now that this isn't something peculiar that the control is doing (we're just storing the TemplateSelector in a DependencyProperty) and we know that the issue has been fixed in newer OS versions. With WinUI 3.0 we'll be bringing the whole framework (including this fix) along with WinUI (see #717 for more details).

Closing since we won't do anything in the short term to try to work around this and WinUI 3.0 will fix it.
