### ISSUE TITLE
Feature Request: ToolTipService.InitialShowDelay

### ISSUE THREAD

**Issue by DHowett** [microsoft/microsoft-ui-xaml#3820]
## Summary
WPF supports configuring the tooltip delay. We do not.

## Rationale

* This is [already part of WPF](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.tooltipservice.initialshowdelay?view=net-5.0)
* An application might conceivably want to configure it
* To "configure" it today, an application will need to manually implement its own tooltips (and painstakingly recreate the system style.)

**Comment by Felix-Dev** [comment]
See issue https://github.com/microsoft/microsoft-ui-xaml/issues/2262 which asks for feature parity between UWP XAML's tooltip and WPF's tooltip.

**Comment by DHowett** [comment]
Ah. I searched the repo for specifically "InitialShowDelay", which as you might surmise turned up nothing.

**Comment by DHowett** [comment]
It does not appear to be in the "list of missing APIs"

**Comment by Felix-Dev** [comment]
@DHowett I can remove the "Property" suffix from those APIs to make those APIs easier to find when searching for them - typically we would search for "InitialShowDelay" and not "InitialShowDelayProperty". Searching for "InitialShowDelayProperty" gives me that iisue as a result so I assume it will also show up when I remove the "Property" suffix and search for "InitialShowDelay".

**Comment by DHowett** [comment]
Thanks for finding the duplicate :smile:

**Comment by Felix-Dev** [comment]
Edited that issue: It should now show up when entering "InitialShowDelay" when searching the repo.
