### ISSUE TITLE
NavigationView throws threading error when used in new window

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#3822]
**Describe the bug**

As of WinUi 2.5, NavigationView throws the following error when used in a separate UWP window:
`The application called an interface that was marshalled for a different thread.`

**Steps to reproduce the bug**

1. Create UWP app
2. Add NavigationView to main page
3. Create new page with a NavigationView
4. Add code to launch a new window, and navigate to that frame. (See example below)
5. Launch the app and run code to open the new window
6. See error

Window launch code example: 
```cs
CoreApplicationView newWindow = CoreApplication.CreateNewView();
ApplicationView newView = null;
await newWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
{
  Frame frame = new Frame();
  frame.Navigate(typeof(NewPage), null, new SuppressNavigationTransitionInfo());
  Window.Current.Content = frame;
  Window.Current.Activate();

  newView = ApplicationView.GetForCurrentView();
  newWindow.TitleBar.ExtendViewIntoTitleBar = true;
});
bool viewShown = await ApplicationViewSwitcher.TryShowAsStandaloneAsync(newView.Id);
```
**Expected behavior**

The navigation view should work in a separate window.

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |?  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21277.1000)              | yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop         | Yes |
| Xbox               | ? |
| Surface Hub       | ? |
| IoT                |?  |

**Additional context**

This bug was discovered [here](https://github.com/files-community/Files/issues/2537)

Edit: fixed package version

**Comment by MikeHillberg** [comment]
@winston-de - are you able to get a call stack at the exception? I couldn't reproduce, using this as NewPage.xaml:

```xaml
<muxc:NavigationView>
    <muxc:NavigationView.MenuItems>
        <muxc:NavigationViewItem Icon="Play" Content="Menu Item1" Tag="SamplePage1" />
        <muxc:NavigationViewItem Icon="Save" Content="Menu Item2" Tag="SamplePage2" />
        <muxc:NavigationViewItem Icon="Refresh" Content="Menu Item3" Tag="SamplePage3" />
        <muxc:NavigationViewItem Icon="Download" Content="Menu Item4" Tag="SamplePage4" />
    </muxc:NavigationView.MenuItems>
    <Frame />
</muxc:NavigationView>
```

**Comment by winston-de** [comment]
@MikeHillberg There is no stack trace (that I know of). The entire output of the error is below. The only reason I figured this was an issue with NavigationView is because the issue started just after updating to WinUI 2.5 and switching to the Windows.UI NavigationView fixed the issue.

Also, give me a minute, I'll try and figure out why you can't reproduce the issue.

Here is the data from the error:
  | Name | Value | Type
-- | -- | -- | --
◢ | Exception | {"The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))"} | System.Exception
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2147417842 | int
  | HelpLink | null | string
  | IPForWatsonBuckets | 0x00000000 | System.UIntPtr
  | ▶ InnerException | null | System.Exception
  | IsTransient | false | bool
  | Message | "The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))" | string
  | RemoteStackTrace | null | string
  | Source | null | string
  | StackTrace | null | string
  | TargetSite | null | System.Reflection.MethodBase
  | WatsonBuckets | null | object
  | _HResult | -2147417842 | int
  | _className | null | string
  | ▶ _data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | _dynamicMethods | null | object
  | _exceptionMethod | null | System.Reflection.MethodBase
  | _helpURL | null | string
  | ▶ _innerException | null | System.Exception
  | _ipForWatsonBuckets | 0x00000000 | System.UIntPtr
  | _message | "The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))" | string
  | _remoteStackIndex | 0 | int
  | _remoteStackTraceString | null | string
  | _source | null | string
  | _stackTrace | null | object
  | _stackTraceString | null | string
  | _watsonBuckets | null | object
  | _xcode | -532462766 | int
  | _xptrs | 0x00000000 | System.IntPtr

**Comment by winston-de** [comment]
@MikeHillberg 
It seems like the issue occurs when you have two different windows with NavigationViews open simultaneously.
Try adding another NavigationView to your main page, or just open the window twice.

**Comment by jingkecn** [comment]
I only used the MUXC version NavigationView but I also got crash w/ NV in a new window after updating to WinUI 2.5

**Comment by ranjeshj** [comment]
@winston-de Can you share a repro app ?

**Comment by tsvietOK** [comment]
@ranjeshj 
[TestApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5773466/TestApp.zip)

**Comment by guominrui** [comment]
This issue has been fixed in 2.6.0 release build.

**Comment by DaveAurionix** [comment]
That's fantastic news, thank you!  (I've pulled that package and it is working great for me).

**Comment by winston-de** [comment]
I can't repro the issue anymore either, so closing. Thanks for the fix! 😄
