### ISSUE TITLE
RadioButtons does not support direct content.

### ISSUE THREAD

**Issue by Elmarcotoro** [microsoft/microsoft-ui-xaml#3823]
I'm trying to place RadioButton inside the RadioButtons group as per [documentation](https://docs.microsoft.com/en-gb/windows/uwp/design/controls-and-patterns/radio-button).

```
<RadioButtons>
                    <RadioButton Content="Button1"/>
                    <RadioButton Content="Button2"/>
 </RadioButtons>
```

I keep getting RadioButtons does not support direct content.
RadioButtons does not support layout controls like StackPanel or Grid.

The only way I seem I seem to get it to work is if I create my own RadioButton group.  

Is anyone else experiencing this, I can't work out what I'm doing wrong.

**Comment by mdtauk** [comment]
I believe the RadioButtons control takes String values, and it creates it's own RadioButton controls...

```XAML
<muxc:RadioButtons Header="Background color"
                   SelectedIndex="0"
                   SelectionChanged="BackgroundColor_SelectionChanged">
    <x:String>Red</x:String>
    <x:String>Green</x:String>
    <x:String>Blue</x:String>
</muxc:RadioButtons>
```

**Comment by chingucoding** [comment]
I think you can also just pass RadioButton controls and it will use them.

**Comment by Felix-Dev** [comment]
> I believe the RadioButtons control takes String values, and it creates it's own RadioButton controls...

The RadioButtons control should be able to work with elements passed as a `RadioButton` though. We only wrap an element in a `RadioButton` control if said element is *not* a RadioButton.

**Comment by Elmarcotoro** [comment]
@mdtauk @Felix-Dev Thank you for your reply.
If you use <x:String> value, or also as per the example shows in the docs <SymbolIcon> The same error is thrown.  

The [docs](https://docs.microsoft.com/en-gb/windows/uwp/design/controls-and-patterns/radio-button) clearly state that the following can be implemented but the error "The type 'RadioButtons' does not support direct content" is thrown for each.

`<RadioButtons>
                    <x:String>Button1</x:String>
                    <x:String>Button2</x:String>
  </RadioButtons>`

`<RadioButtons>
                    <SymbolIcon Symbol="Back"/>
                    <SymbolIcon Symbol="Forward"/>
 </RadioButtons>`

`<RadioButtons> 
                 <RadioButton Content="Button1"/> 
                 <RadioButton Content="Button2"/> 
</RadioButtons>`

It also shows these examples in the xaml control gallery??

**Comment by YuliKl** [comment]
@Elmarcotoro just to confirm, you're using the WinUI (Microsoft.Ui.Xaml.Controls) namespace when declaring RadioButtons?

**Comment by Elmarcotoro** [comment]
Hello @YuliKl.  Thank you for your response.  The project is a WinUI3 desktop project. running in Visual studio 2019 Preview.  
I would have thought RadioButtons was part of the standard namespaces as the other controls are.  If I hover over <RadioButtons> it maps to Microsoft.UI.Xaml.Controls.RadioButtons and there are no squigglies unless I try to add content.  

If I go to the Nuget Package manager select Package source as "All" and browse for [Microsoft.UI.Xaml.Controls](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls?view=winui-2.5) I only get Microsoft.UI.Xaml.  Installing and referencing this nuget does not help.  

I'm thinking that Microsoft.UI.Xaml.Controls is a WinUI2 class not WinUI3?

**Comment by MikeHillberg** [comment]
@Elmarcotoro - I'm seeing this too (WinUI3 Preview3), but as an Intellisense error rather than a Build error. So when I build/run it actually works. Is this what you're seeing too?

**Comment by Elmarcotoro** [comment]
@MikeHillberg Thank you, You are correct, it does build and run.  I never tried to build because of the error.  I feel foolish:-(
For the WinUI guys this is happening on the ProjectReunion nuget package.
