### ISSUE TITLE
Out for the holidays! ❄😴🐱‍💻🥳🎄😊

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#3826]
Most of the WinUI team is taking some much needed vacation throughout December 2020. Thank you for being patient while we relax, recharge, and return to a normal responsiveness in January 2021. In the meantime feel free to continue to pose questions, open issues, and make feature requests - you just may not get a response right away.

**Comment by Felix-Dev** [comment]
Happy holidays to the team! See you all in 2021 😊

**Comment by chingucoding** [comment]
Happy holidays to everyone and the team, see you all in 2021!

**Comment by mdtauk** [comment]
I hope you all have a happy festive season, and return in the new year refreshed, and recharged.
