### ISSUE TITLE
Bug: WinUI3 Preview 3, problems getting User

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#3827]
I am using WinUI 3 Preview 3 with C#9 to create a desktop application with an MSIX package. I am converting from UWP to desktop, which I know is a somewhat retrograde thing to do but I would like to be able to use .NET 5 and the various things that go along with it. 

In my App class I have 

        protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs e)

and in there I try to access 

       e.UWPLaunchActivatedEventArgs.User

but I get a System.InvalidCastException in System.Private.CoreLib.dll. 

This would appear to be a bug given that the WinUI documentation for LaunchActivatedEventArgs says that you can get a (functional) UWPLaunchActivatedEventArgs: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.launchactivatedeventargs?view=winui-3.0-preview 

Steps to reproduce: Install Visual Studio Version 16.9.0 Preview 2.0 with WinUI 3 Project Templates [Preview] version 3.0.0.2011130. Download and compile the Xaml Controls Gallery branch for WinUI 3 - Desktop (i.e. with the MSIX package). In App.xaml.cs, add the following line at the start of OnLaunched: 

            System.Diagnostics.Debug.WriteLine($"Getting user ... {args.UWPLaunchActivatedEventArgs.User}");

Expected: prints "Getting user ... User" (since User.ToString() should be the type name).
Actual: System.InvalidCastException is thrown. 

Steve

**Comment by MikeHillberg** [comment]
About the signature of `OnLaunched`, you're talking about the change from the `Windows.ApplicationModel.Activation` namespace to the `Microsoft.UI.Xaml.LaunchActivatedEventArgs` namespace? That's intentional in WinUI3, but confusing because of the name duplication; we're planning to rename the type.

About the other problems (User and VCRTForwarders), could you split them into separate issues? The User case looks like a bug.

**Comment by sjb-sjb** [comment]
@MikeHillberg glad the namespace change is intentional. 
The main point of my question is the User exception. I'd rather leave the other items in there because they could interact with the question about User throwing an exception, and I don't feel they need solving other than that. I will edit to reflect this.

**Comment by get-flat** [comment]
https://github.com/microsoft/microsoft-ui-xaml-specs/blob/Win32/active/Win32/Window_and_Application_API_Spec.md#xamllaunchactivatedeventargs-class

"UWPLaunchActivatedEventArgs Gets the LaunchActivatedEventArgs from UWP. This property is null in a Desktop app." - can it be read as for winui3 you cannot use User info?

**Comment by sjb-sjb** [comment]
@get-flat I don't think those are the same thing. For one thing, the UWPLaunchActivatedEventArgs is not null, for another the comment you quoted is not in the WinUI vesion of the docs (I have edited the original post and linked it above). This looks like a bug to me. Shouldn't the MSIX package should provide the user?
