### ISSUE TITLE
Minimum windows 10 version for WinUI 3 GA...

### ISSUE THREAD

**Issue by davecarlisle** [microsoft/microsoft-ui-xaml#3829]
By chance is it already known what the minimum win 10 version requirement will be come the WinUI 3 GA? For preview 3 we see the minimum required version is 1803 and ideally would like to know if that will be the minimum for GA or if we should expect a higher minimum version requirement.

Thanks!

**Comment by Felix-Dev** [comment]
As per the [official documentation](https://microsoft.github.io/microsoft-ui-xaml/about.html#controls), 1803 and above will be the supported Windows versions for WinUI 3 (so the same as for the preview versions).

**Comment by davecarlisle** [comment]
Thanks @Felix-Dev!
