### ISSUE TITLE
Bug: XAML children of a MapControl do not update location until the user interacts with the map

### ISSUE THREAD

**Issue by pingzing** [microsoft/microsoft-ui-xaml#3834]
**Describe the bug**
If a XAML element has been added to a MapControl, and that element's `MapControl.Location` attached property is changed, that change will not be reflected on the map until the user interacts with the map, or the map redraws. Things that seem to trigger an update:
 - Mousing over a MapIcon (anywhere on the map)
 - Zooming/panning/rotating/tilting the map
 - Mousing over a transit icon or other pre-built map marker

Things that do _not_ trigger an update:
 - Calling `InvalidateArrange()` on the XAML element itself
 - Calling `InvalidateArrange()` on the MapControl

**Steps to reproduce the bug**
1. Add a XAML element to a MapControl's `Children` collection.
2. Update its geoposition by calling `MapControl.SetLocation()` in code.
3. Observe the lack of change until the map redraws.

I've also created a repository with code that showcases this behavior: https://github.com/pingzing/UwpMapIssue

**Expected behavior**
I would expect an update to a XAML element's `MapControl.Location` to trigger a visual update to that element shortly after being set, instead of waiting for the next time the map happens to redraw.

**Version Info**
As the MapControl is not part of WinUI (yet?) no WinUI version applies.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       | Unknown |
| May 2019 Update (18362)            | Unknown |
| October 2018 Update (17763)        | No* |
| April 2018 Update (17134)          | Unknown   |
| Fall Creators Update (16299)       | Unknown   |
| Creators Update (15063)            | Unknown   |

\* The device running Win10 v.17763 is running Windows 10 IoT Core--it does not seem to exhibit this issue, but I have no idea whether to attribute that to Windows version, or the fact that it's a Raspberry Pi running IoT Core ¯\\\_(ツ)_/¯

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | Unknown |
| Surface Hub        | Unknown |
| IoT                | No |

**Additional context**
As mentioned above, I _don't_ see this issue on the Raspberry Pi running IoT Core, but I _do_ see it on my development machine, which is running Windows 10 19041.

The application itself is targeting 17763, and has a minimum version of 17763. Release (.NET Native) vs Debug doesn't seem to matter.

And a follow-up question: if this is truly a bug with MapControl (and not just my usage of it) _is there a workaround_? Is there some element in the XAML tree I can call `InvalidateArrange()` on that would force an update? Some way to force the map to repaint (simulating a click on it, for example)?

Thanks for your time!

**Comment by ranjeshj** [comment]
Sounds like the item is not going to the correct visual states. MapControl is not in WinUI.
@MikeHillberg any thoughts ? can you help route this bug ?

**Comment by BobbyCannon** [comment]
Seems like this isn't getting fixed but here is a hack to force the MapControl to update. Draw a MapPolyline, with 0 alpha color, in the top of the map control. I do top left corner to top right corner.

Do it every time you want the MapControl to update all MapElement.Controls using MapControl.Location positioning.
