### ISSUE TITLE
Application.OnActivated is not called.

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#3835]
Using WinUI 3 Preview 3, use the project template to create a desktop app with MSIX package.

Add the following to App.xaml.cs:

        protected override void OnActivated(IActivatedEventArgs args)
        {
            Debug.WriteLine($"App activated! Kind is {args.Kind}");
            base.OnActivated(args);
        }

Expected: the method is called when m_window is activated
Actual: not called.

**Comment by davecarlisle** [comment]
Having the same issue with WinUI 3 Preview 3 with desktop...

**Comment by asklar** [comment]
@anawishnoff @Austin-Lamb @MikeHillberg could one of you confirm whether this will be fixed in Preview 4?

**Comment by MikeHillberg** [comment]
No, this is one of several virtual methods in the Application class that are not currently invoked when running as a Desktop app. [This spec](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/71/files) describes the differences in behavior for the Window and Application classes when running as a Desktop app.

**Comment by mqudsi** [comment]
Note that in the Microsoft.ProjectReunion 0.8.0, the base class method has been dropped and `protected override void OnActivated()` and `protected override void OnBackgroundActivated` are compile-time errors.

**Comment by KasperHoldum** [comment]
Any update on this? There is documentation for activation on MSDN but only with c++ examples.

**Comment by pratikone** [comment]
as mentioned above, `OnActivated` and `OnBackgroundActivated` are not supported on Winappsdk currently. Infact, if the compile time warnings will stop you if you try to create a function with override keyword.

Maybe you can work with other ways like Window created and loaded events for your code.

Closing the bug
