### ISSUE TITLE
Window's visibility

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#3836]
How to hide a WinUI window and its respective taskbar icon ? I can see only the opacity can be changed of the Content's UIElement.

**Comment by ranjeshj** [comment]
@marb2000  Is there a way to hide the Window ?

**Comment by chanallenk** [comment]
I'm sure they will add this functionality in later releases, however, I've managed to do so right now by getting the window handler and using win32 "ShowWindow" function to hide the window.

**Comment by marb2000** [comment]
If the OP is talking about Desktop WinUI 3, you need to call the Win32 APIs as @chanallenk said. 
```C
// Win32 C API
ShowWindow(hwnd, SW_HIDE);
```

There is no **Microsoft.UI.XAML** WinRT API that does this. I hope Reunion's Windowing expose it in a WinRT fashion way.
