### ISSUE TITLE
<OutputType>Exe</OutputType>

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#3837]
1. Why is there an assembly Weather.History.Splash.dll in the output folder even though I requested an Exe as output ?
2. Why is there a ./ref subfolder in the output folder, containg also an assembly with the same name ?

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0-windows10.0.18362.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWpf>True</UseWpf>
    <AssemblyName>Weather.History.Splash</AssemblyName>
    <RootNamespace>Weather.History.Splash</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="PropertyChanged.Fody" Version="3.3.1" />
    <PackageReference Include="Stylet" Version="1.3.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Weather.History.Log\Weather.History.Log.csproj" />
    <ProjectReference Include="..\Weather.History.Utils\Weather.History.Utils.csproj" />
  </ItemGroup>
</Project>
```

**Comment by huoyaoyuan** [comment]
> 1. Why is there an assembly Weather.History.Splash.dll in the output folder even though I requested an Exe as output

This is the structure of .NET Core output. The exe isn't managed if you inspect it with ILSpy. It's a native executable that starts coreclr. The dll contains actual managed application. *In fact, the exe is optional.*


> 2\. Why is there a ./ref subfolder in the output folder, containg also an assembly with the same name

Maybe some tooling requires it. I'm not sure.

**Comment by ranjeshj** [comment]
@Scottj1s @stevenbrix, do you know the answer to question (2) ?
