### ISSUE TITLE
Can I consume an app service from a WinUI ? 

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#3838]
Can I add a **Windows Runtime Component** to my WinUI project ? I guess no since that is an UAP. An app service must be hosted in this type of runtime component. 

How can I integrate an app service into a WinUI exe ? 

[Consume an app service](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)

**Comment by huoyaoyuan** [comment]
Maybe you should look into **CsWinRT** repo to find how to reference winmd in .NET 5 project.
Even you can reference it, consuming app service may still not be supported.
This issue falls into the scope of CsWinRT or ProjectReunion.

**Comment by sigmarsson** [comment]
Could you estimate the WinUI version that will support hosting and consuming app services ?

**Comment by huoyaoyuan** [comment]
This not bound to WinUI version. It's about .NET 5/UWP.
WinUI 3 for UWP should be able to consume app service from the start.

**Comment by sigmarsson** [comment]
I have a .NET 5 WPF (client) and the WinUI 3 (as service provider). I wish to alter some appearance of the WinUI application from the client, through this app service IPC. Can you advise how to integrate a **Windows Runtime Component (Universal Windows)** project through CsWinRT ?

**Comment by huoyaoyuan** [comment]
https://github.com/microsoft/CsWinRT/blob/master/docs/usage.md

**Comment by sigmarsson** [comment]
Do you think it is more straightforward than a classic named pipe empowered by the classic WCF ? 
Frankly, I do not understand this :)

**Comment by ranjeshj** [comment]
@stevenbrix @Scottj1s as FYI

**Comment by sigmarsson** [comment]
I do not expect the App Service architecture will fusion with the WinUI. Close if true. 
I have found an alternative with gRpc through named pipes. [GrpcDotNetNamedPipes](https://github.com/cyanfish/grpc-dotnet-namedpipes) 
This seems to work for me as an IPC across different processes.
