### ISSUE TITLE
The Window.Current.CoreWindow.PointerPressed event is never raised

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3843]
**Describe the bug**

Hello!

I subscribe to the Window.Current.CoreWindow.PointerPressed event in my WinUI for **UWP** application by this way

![image](https://user-images.githubusercontent.com/23479280/102795183-838f0400-43bd-11eb-8793-b5ef053d6950.png)

Event is never raised.

**Version Info**

Windows 10 1903 (OS Build 18362.1082)

**NuGet package version:**

WinUI 3.0.0-preview3.201113.0

**Windows app type:**

| UWP              | Win32            |
| :--------------- | :--------------- |
|Yes| |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by BorzillaR** [comment]
This issue is not reproduced in Preview 4 and can be closed. Thank you!

**Comment by MikeHillberg** [comment]
Thank you @BorzillaR!
