### ISSUE TITLE
Rename acrylic resources

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#3845]
**Describe the bug**

With #3498 we added and updated acrylic resources. Now it's time to change the names of these resources to better align with other new colors/brushes that are being checked in.

I would like to see the following changes:
| Current resource name                  | New name |
| :--------------------------------- | :-------------------- |
SystemControlBaseAcrylicBrush | AcrylicBackgroundFillColorBaseBrush
SystemControlTransientBackgroundBrush | AcrylicBackgroundFillColorDefaultBrush
SystemControlTransientAcrylicElementBrush | AcrylicInAppFillColorDefaultBrush
SystemControlTransientBackgroundInverseBrush | AcrylicBackgroundFillColorDefaultInverseBrush

Control styles that use the old names (in particular `SystemControlTransientBackgroundBrush` and `SystemControlTransientAcrylicElementBrush`) will also need to be updated. 

**Additional context**

Copied from [internal task](https://microsoft.visualstudio.com/defaultcollection/OS/_workitems/edit/31000997)

**Comment by YuliKl** [comment]
@chingucoding FYI, just in case you would be interested in tackling this work.

**Comment by chingucoding** [comment]
Sure, I'll work on this.

**Comment by mdtauk** [comment]
Is this for the main branch, or for the Design Tokens one?
