### ISSUE TITLE
Task view system animation broken for the past 2 years

### ISSUE THREAD

**Issue by CrazyBatkin** [microsoft/microsoft-ui-xaml#3848]
I know it's probably not the right place to talk about this, as you guys are the team working on UWP apps and not the Windows shell, but I was wondering if you could spread the word to the Windows shell team, as it's now been over two years and this bug still got no fix. It's hard for me to believe that none of the devs have noticed it yet, and I feel it's kind of a shame that this bug is still there.

The animation of the timeline/task view (Windows + tab) is broken, and has been since the introduction of timeline. Every time you open it, there is one small jump at the end of the animation as the animation of each window is not going to the exact spot where the miniature of the window is. The bigger the screen resolution is, the worse it gets. Sometimes the animated windows even get cut in half, or flicker, or disappear for half of the animation. It's been broken since 1803, and it is a problem on all Windows 10 computers running version 1803 and above. Why is this still not fixed to this day ? Aren't you devs using your own operating system annoyed by that ? Didn't anyone of you notice that ? I feel this should have never made it to the final version of Windows...

The bug report on the feedback hub from over a year ago (feedback-hub:?contextid=790&feedbackid=4a37e756-8e2f-4a1e-aeb4-92dff0a77a66&form=1&src=1), doesn't seem to get much attention from the devs, neither the post on the microsoft community blog (https://answers.microsoft.com/en-us/windows/forum/windows_10-start-win_general/windows-10-task-view-flickering-choppy-loading-of/7497dae7-04ad-48db-aca6-fb15dce932b2?messageId=345bb4c7-c960-46e1-b692-e268f8a9e30e) (You can find a good example of glitches of the animation from the video there)

I hope I'm not asking too much, or taking too much of your time, but I feel those kind of bugs are litteraly defeating the whole point of having animations in the first place. Making an animation that glitches is even worse than having no animation at all.

**Comment by Felix-Dev** [comment]
@CrazyBatkin Outside of the Feedback Hub, the right place to report this issue right now is the [WinDev](https://github.com/microsoft/WinDev) repo where an issue about this exact behavior already exists: https://github.com/microsoft/WinDev/issues/38 It is my understanding that the Windows engineering teams will use that issue for tracking and status updates.

**Comment by CrazyBatkin** [comment]
@Felix-Dev thanks a lot ! I'll have a look over there then :)
