### ISSUE TITLE
Should EF Core 5.0.1 work with WIN UI preview 3?

### ISSUE THREAD

**Issue by Changed-Daily** [microsoft/microsoft-ui-xaml#3850]
Hi,

I am trying to get EF Core working in my test WIN UI project ("Packaged, WINUI in Desktop"). I have created the basic template packaged application and then followed the Getting Started guide for EF Core:

Install-Package Microsoft.EntityFrameworkCore.Sqlite
Added Model.cs
Install-Package Microsoft.EntityFrameworkCore.Tools
Add-Migration InitialCreate

At this point the process fails:

> PM> Add-Migration InitialCreate

> Build started...
> Build succeeded.
> Exception calling ".ctor" with "1" argument(s): "The parameter 'frameworkName' cannot be an empty string.
> Parameter name: frameworkName"

These are the packages installed:

![image](https://user-images.githubusercontent.com/38410834/102887026-15465200-444e-11eb-88b6-417761208865.png)

I am hoping there is some basic step I have missed!

Thanks

**Comment by huoyaoyuan** [comment]
The EF migration command uses `dotnet build`, which is not supported by WinUI project now.
The workaround is defining EF related things in another project and reference it from WinUI project.

**Comment by Changed-Daily** [comment]
Hello huoyaoyuan,

I already have my "Model" and "DataLayer" in separate projects so re-targetting those was easy. I of course also had to remove references to the Microsoft.WinUI package in those projects. They are all in the same solution as my WINUI project but setting the "DataLayer" (EF Core) project as the startup project for the Add-Migration - it works now. Great and thanks for your help.

Patrick

**Comment by stevenbrix** [comment]
@Changed-Daily and @huoyaoyuan, it sounds like you figured this out so I'm going to close this out. If this is incorrect, please respond and I'll open it.

**Comment by Bondarenko1990** [comment]
@Changed-Daily  Did you use Sqlite?

**Comment by Bondarenko1990** [comment]
And how can I get the path to the database in class library project? 

![image](https://user-images.githubusercontent.com/32612104/172067527-e19ed9eb-3560-4560-9567-132ea054e834.png)
