### ISSUE TITLE
0x76C4A892 处(位于 App1.exe 中)引发的异常: Microsoft C++ 异常: winrt::hresult_error，位于内存位置 0x005CF0F0 处。

### ISSUE THREAD

**Issue by CoderTyn** [microsoft/microsoft-ui-xaml#3853]
**Describe the bug**
使用VS2019自带模板新建winui3 c++桌面项目，编译通过，运行报这个错误。

**Steps to reproduce the bug**

使用VS2019自带模板新建winui3 c++桌面项目，编译通过，运行报这个错误。

**Expected behavior**
正常编译运行

**Version Info**

winui3 preview3 Nov
NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop          | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by CoderTyn** [comment]
when i run the packaged project,it works.but this error occurs everytime i run the project named App1(auto-generated).

**Comment by YuliKl** [comment]
@CoderTyn, can you please translate your issue description into English? This isn't actionable for us as written. Please reopen the issue with an English description.
