### ISSUE TITLE
ExpIndependentPointerInputObserver - usage.

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#3854]
When setting up an ExpIndependentPointerInputObserver (the WinUI version of CoreIndependentInputSource) how do I get it to process events? The old way was..
```cs
CIInputSource.Dispatcher.ProcessEvents(CoreProcessEventsOption.ProcessUntilQuit);
```
But the DispatcherQueue for the new pointerObserver lacks the ProcessEvents method.

**Comment by kevinguo305** [comment]
The DispatcherQueue does not require an explicit “ProcessEvents” call. The best way to get the ExpIndependentInputObserver from a Xaml SwapChainPanel element is to create a dedicated DispatcherQueue thread that will automatically process events. Here’s some sample code using the InputPointerSource API (only available in 1.0 preview and beyond), which is the public stable version of ExpIndependentPointerInputObserver

```
void SetupBackgroundPenInput(Visual visual)
{
    var dispatcherQueueController = DispatcherQueueController.CreateOnDedicatedThread();

    dispatcherQueueController.DispatcherQueue.TryEnqueue(
        () =>
        {
            var inputPointerSource = InputPointerSource.GetForVisual(visual);

            inputPointerSource.TrySetDeviceKinds(
                InputPointerSourceDeviceKinds.Pen |
                InputPointerSourceDeviceKinds.Touch);

            inputPointerSource.PointerMoved += OnPointerMoved;
        });
}
void OnPointerMoved(InputPointerSource source, PointerEventArgs args)
{
    PointerPoint point = args.CurrentPoint;

    DrawToPoint(point.Position.X, point.Position.Y);
}
```

I'm going to close this issue, but please feel free to reopen if you have other comments!
