### ISSUE TITLE
NumberBox appears to be throwing "Source information is missing" exception.

### ISSUE THREAD

**Issue by Elmarcotoro** [microsoft/microsoft-ui-xaml#3856]
**Describe the bug**
We are running a WinUI3 desktop app with Visual Studio 2019 preview.  
We have a NumberBox prepopulated using a Twoway x:bind to an integer.

**Steps to reproduce the bug**
If we edit the number box with another integer.
Tab or click away from the NumberBox control we receive the following error.

"Source information is missing from the debug information for this module."
"Unhandled exception at 0x00007FF9C58FBD5C (KernelBase.dll) in [App Name] 0xC000027B: An application-internal exception has occurred (parameters: 0x000002AE7E85AE00, 0x0000000000000005)."

**Version Info**
Nuget Package: Microsoft.ProjectReunion, v0.1.0.  
Windows app type: WinUI in desktop. 
OS version: Windows10 PRO.
OS build:1904. 

NuGet package version: 
Examples
Microsoft.ProjectReunion. v0.1.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  No  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes  |

**Comment by ranjeshj** [comment]
@Elmarcotoro can you provide a repro or the callstack ? There is some information on how to debug [here](https://github.com/microsoft/microsoft-ui-xaml/blob/dfbe38bfb2996dfaa2f09544c4e86aa69ccc906b/docs/debugging_crashes.md).
