### ISSUE TITLE
Not possible to select treeview nodes programmatically

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#386]
**Describe the bug**
Previous Windows tree views had properties such as SelectedNodes which allowed you to set the nodes which are selected/highlighted in the control.

The UWP treeview exposes a `SelectedNodes` [property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview.selectednodes) which is a collection. The collection is read only and calling `.Add` on it and specifying a TreeViewNode does not add it to the collection and does not select the item in the user interface.

An IsSelected property should also be added to `TreeViewNode` to match with `TreeViewItem`.

**Steps to reproduce the bug**
Add items to a TreeView and then use the following code, which you would expect would select the first item.

```
if (treeView.RootNodes.Count > 0)
                treeView.SelectedNodes.Add(treeView.RootNodes[0]);
```

SelectedNodes = 0

**Expected behavior**
The first tree node would be selected.

**Version Info**
1809

**Comment by jevansaks** [comment]
@kaiguo Is this something you fixed recently or is it part of the pending PR you have out?

**Comment by kaiguo** [comment]
SelectedNoes collection only works in multi-select mode, @knightmeister can you set TreeView to multi-select and see if it still repros?

We are working on adding a new SelectedNode property for single selection. See PR #243

**Comment by jevansaks** [comment]
Shouldn't we make SelectedNodes contain the one and only selected item in single select? I'm pretty sure Selector.SelectedItems works this way.

**Comment by kaiguo** [comment]
@jevansaks Yeah I think that works, then we can probably just get rid of the singular form SelectedItem and SelectedNode?

**Comment by knightmeister** [comment]
@kaiguo Yes, it works when SelectionMode=Multiple.

**Comment by jevansaks** [comment]
> @jevansaks Jevan Saks FTE Yeah I think that works, then we can probably just get rid of the singular form SelectedItem and SelectedNode?

No, having the singular one is still convenient when in single select mode.

**Comment by kaiguo** [comment]
I see. I'll make some updates in #243

**Comment by jevansaks** [comment]
Ok, i'll assign this to you then.

**Comment by dpaulino** [comment]
Just wanted to chime in and ask if there's any progress on this? I really need to be able to programmatically set the selected item

**Comment by kaiguo** [comment]
> Just wanted to chime in and ask if there's any progress on this? I really need to be able to programmatically set the selected item

Hey @dpaulino, sorry I've been working on rounded corners stuff. Will get back to this some time next week hopefully.

**Comment by kaiguo** [comment]
> @kaiguo Kai Guo FTE hey, just wanted to triple check. With your PR regarding this, should I now be use TwoWay binding for `SelectedItem`.

Yes, you can use binding like that for single selection. 
SelectedItems for multi-select is still read only (we kept it consistent with ListView), so you'll have to do it through a TreeView instance, like the example we showed in this [spec](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/31/files?short_path=81ff309#diff-81ff3094337017f74d91702b19e8750c).

**Comment by dpaulino** [comment]
Okay thanks for confirming. I think I'm getting an access violation error when I use two way binding though... But I'll try to get a proper repro, and I'll create a new issue if I see any issues
