### ISSUE TITLE
Empty scrollbars are often shown

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#3870]
**Describe the bug**

**Steps to reproduce the bug**

I don't know. Open Intel Graphics Command Center.

**Expected behavior**

No useless scrollbars that overlap content?

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.4.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       | No   |
| Creators Update (15063)            | No   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Directed to here from https://github.com/microsoft/Xaml-Controls-Gallery/issues/615

PLEASE DO NOT DIRECT ME TO THE VOID THAT IS THE FEEDBACK HUB. I just want sane scrollbars. This isn't that big of an issue because not many people use apps that use WinUI. Most people use Chrome and Office, both of which don't have an automatically disappearing scrollbar.

**Comment by Felix-Dev** [comment]
I believe the "empty" scrollbars show up because the developers forgot to set the [VerticalScrollBarVisibility](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer.verticalscrollbarvisibility) to "Auto" on the used ScrollViewers. By default, it is set to "Visible" which explains why you see the scrollbar.

For the new WinUI ScrollView class, the default value for this API has been changed to "Auto" so this situation should improve in the future.

**Comment by stmoy** [comment]
Can confirm that @Felix-Dev's recommendation to set VerticalScrollBarVisbility to "Auto" solves this issue. 

It's good that the default has been updated on the new WinUI ScrollView, but should we update the value on ScrollViewer to Auto as well?

**Comment by chingucoding** [comment]
I'm not sure if this would break existing applications/UIs if we switch this to auto.

**Comment by stmoy** [comment]
I guess I don't know what the behavior is now. Right now, it looks like "Auto" since it'll show/hide the scrollbars as appropriate _until the "Always Show Scrollbars" setting is enabled_ which seems like the wrong thing.

**Comment by chingucoding** [comment]
If you hover of where the scrollbar would be if there was something to scroll, the scrollbar would still show without visibility set to auto, so it's not only with the *"always show scrollbars"* settings; it's just hard to hit without that setting.

**Comment by StephenLPeters** [comment]
Ideally we would change the default value for the VerticalScrollBarVisibility property, but we can't because it drives some scrollViewer interactions and wouldn't preserve back compat. We probably aren't going to change this.

**Comment by Poopooracoocoo** [comment]
Anyone know about why these scrollbars show up in Intel Graphics Command Center?

**Comment by chingucoding** [comment]
Probably because they have not said the VerticalScrollBarVisibility to Auto?
