### ISSUE TITLE
Question: [Is WinUI 3.0 going to use native controls for windows 8.1 and below?]

### ISSUE THREAD

**Issue by Shadowblitz16** [microsoft/microsoft-ui-xaml#3873]
**Is WinUI 3.0 going to use native controls for windows 8.1 and below?**
I don't see any point in people moving to this if their apps are not native by default on older systems.

Also the fact that win32 is backwards compatible back to win95 and dot.net is only backwards compatible back to WinXp without backwards compatible libraries and AOT.

I understand Microsoft wants to move more towards UWP apps and allow custom rendering but I feel their forgetting why the winapi is used in the first place.

EDIT: WinForms doesn't even have native menus anymore
![image](https://user-images.githubusercontent.com/2453707/103448098-2dd21b80-4c49-11eb-83af-f28512b449b3.png)
![image](https://user-images.githubusercontent.com/2453707/103448102-417d8200-4c49-11eb-833e-bf5385a05ca2.png)

**Comment by chingucoding** [comment]
WnUI 3.0 as of right now will only be available to Windows 10 1803, so the question what controls are being used for Windows 8.1 and below does not arise at is not available for those platforms.

**Comment by Shadowblitz16** [comment]
are there plans on eventually supporting all windows versions?

**Comment by chingucoding** [comment]
I wouldn't bet on it. If you need downlevel support, you should try out [Uno Platform](https://platform.uno/), especially if you want cross platform support.

**Comment by Shadowblitz16** [comment]
Is uno even native on older versions of windows?

**Comment by chingucoding** [comment]
No for older Windows versions such as Windows 7, Uno platform can use a native shell. To read more about Windows 7 you can check this link out: https://platform.uno/windows7/

**Comment by Shadowblitz16** [comment]
ok ty
