### ISSUE TITLE
Adding WinUI 3 to .Net 5 Class Library

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#3881]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Adding-WinUI-3-to-Net-5-Class-Library/1296796)._

---
\[severity:I'm unable to use this version\] I'm trying to create a .Net 5 Class Library with WinUI 3 preview 3 package. There is no nuget package available for WinUI 3, even with show preview version, and when i add this itemgroup to the class libraries project file .. \`\`\` \`\`\` I get the following solution output and the project will not load. \`\`\` Library.csproj : error : A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "" instead of a number, in condition "'$(TargetPlatformVersion)' >= '10.0.11000.0'". C:\\Users\\...\\Microsoft.ApplicationModel.Resources.PriGen.targets \`\`\` I've been using WinUI 3 Preview 3 in VS 16.8.3 - could this be an issue? I notice that some of the tooling requires VS 16.9.

Here's my project file...
```xml


  
    net5.0
  

  
    true
  

  
    
  


```

---
#### Gavin Williams on 12/26/2020, 06:10 PM: 

<p>Yikes. Some formatting craziness, the forums seem to transform the layout after editing for the worse, because this looked OK, before I edited and added the xml.</p>

#### Feedback Bot on 12/27/2020, 06:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by stevenbrix** [comment]
The WinUI package is unlisted while we're still in preview. If you want to use VS16.8, the version you have to specify in your project file is 3.0.0-preview3.201113.0
