### ISSUE TITLE
ArgumentOutOfRangeException was thrown when setting min date between 1/1/0001 and 31/12/1600 range in DatePicker and CalendarDatePicker control in WinUI Desktop

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#3889]
**Describe the bug**
ArgumentOutOfRangeException was thrown when setting min date between 1/1/0001 and 31/12/1600 range in DatePicker and CalendarDatePicker control in WinUI Desktop. This issue does not happen in WinUI UWP.

**Steps to reproduce the bug**
1. Run attached sample
2. Application crashes when setting date between 1/1/0001 and 31/12/1600 range. 

**Expected behavior**
Should be able to set date between 1/1/0001 and 31/12/1600 range.

**Screenshots**
![image](https://user-images.githubusercontent.com/55440472/103652629-634c7100-4f89-11eb-89fc-344fbb1c435c.png)

**NuGet package version:** 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

**Sample:**
[DatePicker-sample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5770479/DatePicker-sample.zip)

**Comment by mageshsankar** [comment]
Hi Team,

Any update on this issue?

**Comment by huoyaoyuan** [comment]
The marshaling is performed in CsWinRT:

https://github.com/microsoft/CsWinRT/blob/5351b4bab3148715969529d358e07f864f43ac8d/src/WinRT.Runtime/Projections/SystemTypes.cs#L65

which directly calls `ToFileTime()` in CLR.

1601-1-1 0:00 UTC is the zero point of file time. I think it should be asked CLR team "why UWP CLR allowed this".

**Comment by StephenLPeters** [comment]
@Scottj1s @stevenbrix FYI

**Comment by huoyaoyuan** [comment]
Seems fixed by CsWinRT. Will take a look.

**Comment by ranjeshj** [comment]
@huoyaoyuan Thanks! Please feel free to reopen if this still repros.

**Comment by huoyaoyuan** [comment]
Confirmed that it's fixed in latest version.
