### ISSUE TITLE
Visual State manager for adaptive size does not work with Window

### ISSUE THREAD

**Issue by Elmarcotoro** [microsoft/microsoft-ui-xaml#3890]
Application: WinUI 3
Nuget: Project Reunion 
Visual Studio 2019 PREVIEW.

I'm trying to set adaptive visual states to a Window (WinUi Desktop) for when the app is resized.

VisualStateManager works when using a Page (winUI) But does not work if it is a Window.

Is this meant to be?

 ```
 <x:Double x:Key="NarrowMinWidth">0</x:Double>
  <x:Double x:Key="NormalMinWidth">580</x:Double>
  <x:Double x:Key="WideMinWidth">1100</x:Double>
```
```
<Grid>
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="AdaptiveVisualStateGroup">
                <VisualState x:Name="VisualStateNarrow">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="{StaticResource NarrowMinWidth}" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Target="myButton.Width" Value="40"/>
                    </VisualState.Setters>
                </VisualState>

                <VisualState x:Name="VisualStateNormal">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="{StaticResource NormalMinWidth}" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Target="myButton.Width" Value="80"/>
                    </VisualState.Setters>
                </VisualState>
                
                <VisualState x:Name="VisualStateWide">
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="{StaticResource WideMinWidth}" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Target="myButton.Width" Value="150"/>
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>

        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
            <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
        </StackPanel>
</Grid>
```

**Comment by mdtauk** [comment]
Can you host the page in the Window?  Maybe within a Frame?

**Comment by Elmarcotoro** [comment]
@mdtauk The Idea of using a Window is that it is not sandboxed and we can access system files.  Hosting a page inside a Window surely loses that functionality?  Why would you go to that complication, if you are not concerned about being sandboxed would you not just use the page on its own?

I wonder why Windows do not get triggered by size change, is it the Frame that updates the size change?

**Comment by mdtauk** [comment]
> @mdtauk The Idea of using a Window is that it is not sandboxed and we can access system files. Hosting a page inside a Window surely loses that functionality? Why would you go to that complication, if you are not concerned about being sandboxed would you not just use the page on its own?
> 
> I wonder why Windows do not get triggered by size change, is it the Frame that updates the size change?

AFAIU A Page is just a way to display a set of Xaml controls, and you can have a Window, with a Frame, and it handles navigation.

The NavigationView would work this way too.

If I am wrong, I would like to be corrected.

The CoreWindow is part of the Sandbox, and it hosts a page which can contain a Frame, which hosts multiple pages, and can navigate back and forward through a BackStack of pages

**Comment by Elmarcotoro** [comment]
@mdtauk 

I think I understand what you are saying.  

I do have a NavigationView in a Window hosting pages in a Frame.

With regards to hosting pages in a frame within a Window and Navigating back and forward through the backstack.  Won't any code in the code behind of the pages be sandboxed?

I'm interested in knowing if there are plans to allow the VisualStateManager to adapt if the Window size changes?

**Comment by chingucoding** [comment]
If something gets sandboxed (if we are talking about UWP sandbox) does not depend on if you load it in a window or page but rather who created it, i.e. the project type. Since you are using WinUI desktop, it shouldn't matter if you do something in the windows code behind or the pages code behind, both are have the same level of access and sandboxing.

**Comment by Elmarcotoro** [comment]
@chingucoding Thank you for that clarification.  I have misunderstood this (I did mean UWP sandbox).
In that case I should be able to use Pages and still have access to system files from the code behind?

I'm sorry to ask this but I have struggled to find a satisfactory answer.  What is the benefit of using a Window over a Page in a Desktop app?

**Comment by chingucoding** [comment]
> In that case I should be able to use Pages and still have access to system files from the code behind?

Yes you should be able to use pages and be able to access system files.

> I'm sorry to ask this but I have struggled to find a satisfactory answer. What is the benefit of using a Window over a Page in a Desktop app?

Window and Page are two different things. A Page is part of an window, a window can have multiple pages, pages get switched out inside windows and you can navigate between pages. Windows on the other hand are top level elements, everything you see  has a window at it's visual tree root. You can not navigate between windows. Two windows will display regardless of each other.

**Comment by mdtauk** [comment]
@chingucoding  I think the WinUI 3.0 documentation would benefit from a "blueprint" of an app, with the Window > Frame > Page construct detailed with an illustration.

A basic set of guides and examples of how you navigate your app structure, as well as showing the alternate patterns such as NavigationView (Top and Side) - TabView (document model) - Immersive (calculator, acrylic) etc

**Comment by Elmarcotoro** [comment]
@chingucoding @mdtauk 
Thank you both for you clarification, it has been very helpful with getting a better understanding and moving forward.  I agree with @mdtauk that some documentation would really help especially at these early stages.  I was quite confused.

**Comment by chingucoding** [comment]
I agree with you @mdtauk and @Elmarcotoro, this might be good to explain in the documentation. I'm not sure though who would be the right person to direct this to, @ranjeshj do you happen know who is the right person for this?

**Comment by lennartb-** [comment]
This is still an issue and confusing. On https://docs.microsoft.com/en-gb/windows/apps/design/controls/navigationview there seems to be made no distinction between Page and Window and purely from that documentation I still don't see why we can't use the VisualStateManager. Is there a workaround if I don't want to use Frames and Pages? I don't need the navigation components, I just want to have a menu that sits on top and collapses into a hamburger if the window width falls below a certain threshold.
