### ISSUE TITLE
Window size changes on navigation

### ISSUE THREAD

**Issue by Elmarcotoro** [microsoft/microsoft-ui-xaml#3894]
**Describe the bug**

When I run the app the Window displays as not full screen.
If I maximise the Window to full screen and then Navigate to a new Window the new window resizes back to the original not full screen size.

**Steps to reproduce the bug**

1. Run the application
2. Maximise screen
3. Navigate to a new Window
4. New window returns back to original not full screen size.

**Expected behavior**

I expect the Window sizes to remain maximised.
I have also noticed that when leaving the Window size at the original size sometimes they do move to different locations on the screen when navigating between Windows.  This gives a weird user experience.
I would also like a way to run the App in full screen mode. like this with UWP `ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.FullScreen;`

**Screenshots**

**Version Info**

WinUI 3
Microsoft.ProjectReunion
WinUi in Desktop

NuGet package version: 
0.1.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by marb2000** [comment]
@Elmarcotoro I don't have clear the scenario yet. What does mean Navigate to a new window? Create a new Window or navigate to a new Page?
