### ISSUE TITLE
Desktop WinUI 3 window may appear behind other windows

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#3895]
**Describe the bug**
Desktop WinUI 3 window may appear behind other windows when operating other windows, and disappear in task bar.

**Steps to reproduce the bug**
1. Do some change in the project to trigger rebuild.
2. Launch the entry app in Visual Studio by F5. This will take some time to build it.
3. **Keep operating** on other window, for example browser. This is the requirement to reproduce this.
4. The app launches, but its window doesn't appear in task bar. It will appear at the last in Alt+Tab view. The DesktopWindowXamlSource mentioned in #3698 appears in task bar. Once the app window is focused, it will appear in task bar.

**Expected behavior**
The app window should appear in task bar. The window should appear in front of other windows.

**Version Info**

NuGet package version: 
I've confirmed on these versions.

Microsoft.WinUI 3.0.0-preview2.200713.0
Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 19042            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI

**Comment by marb2000** [comment]
Hey @huoyaoyuan I couldn't repro with the latest bits of WinUI 3 and VS2019. Perhaps it's something that was a temporary thing.  Can you double check when you get the new bits?

**Comment by huoyaoyuan** [comment]
It should be easier to repro when the application contains more visual tree and takes more time to initialize.

**Comment by codendone** [comment]
@huoyaoyuan Can you confirm this still repros for you on Preview 4? We made a big change in Preview 4 which fixed a common issue here.

**Comment by huoyaoyuan** [comment]
It doesn't repro for a small amount of tries. Since it's kind of random issue, I'll reopen this if it repros later.

**Comment by codendone** [comment]
Excellent! Thanks!
