### ISSUE TITLE
NavigationView's Settings menu item space is still present when `IsSettingsVisible` set to false

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/microsoft-ui-xaml#3900]
**Describe the bug**
In a `NavigationView`, when the Settings `NavigationViewMenuItem` is hidden with `IsSettingsVisible="False"`, the spacing for that menu item still exists.

**Steps to reproduce the bug**
<details>
<summary> Sample Code</summary>

```xml
<Page
    x:Class="WinUIPlayground.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUIPlayground"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d">
    <Page.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Page.Resources>

    <muxc:NavigationView
        IsSettingsVisible="True">
        <muxc:NavigationView.MenuItems>
            <muxc:NavigationViewItem>Menu Item 1</muxc:NavigationViewItem>
            <muxc:NavigationViewItem>Menu Item 2</muxc:NavigationViewItem>
            <muxc:NavigationViewItem>Menu Item 3</muxc:NavigationViewItem>
            <muxc:NavigationViewItem>Menu Item 4</muxc:NavigationViewItem>
        </muxc:NavigationView.MenuItems>

        <muxc:NavigationView.PaneFooter>
            <muxc:NavigationViewItem>
                <muxc:NavigationViewItem.Icon>
                    <FontIcon Glyph="&#xE713;" />
                </muxc:NavigationViewItem.Icon>
                <muxc:NavigationViewItem.Content>
                    Custom Settings Menu Item
                </muxc:NavigationViewItem.Content>
            </muxc:NavigationViewItem>
        </muxc:NavigationView.PaneFooter>
    </muxc:NavigationView>
</Page>

```
</details>

1. Create a muxc:NavigationView with a PaneFooter and `IsSettingsVisible="False"` (see sample code above)
2. Launch the sample app

**Expected behavior**
The `PaneFooter` should be flush with the bottom of the NavigationView.

**Screenshots**
![NavigationViewPaneFooterBug](https://user-images.githubusercontent.com/11050425/103823015-d233d380-5036-11eb-8513-f40d12e4ec43.gif)

**Version Info**
NuGet package version: 
[Microsoft.UI.Xaml.2.5.0-prerelease.201202003]

**NOTE:** This did not exist in [Microsoft.UI.Xaml.2.5.0-prerelease.200609001]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by chingucoding** [comment]
Would you like to take a look at this @carlos-zamora ? The issue is very likely related to this [section](                                                <RowDefinition x:Name="FooterItemsRow" Height="Auto" MinHeight="{ThemeResource NavigationViewItemOnLeftMinHeight}"/> ) where we set the minimum height.

**Comment by carlos-zamora** [comment]
> Would you like to take a look at this @carlos-zamora ? The issue is very likely related to this [section](https://github.com/microsoft/microsoft-ui-xaml/blob/6bc89f93c91a420c76b2960cd11a34f90631db14/dev/NavigationView/NavigationView.xaml#L462) where we set the minimum height.

I'm curious what would happen if I remove `MinHeight`. If you/somebody can direct me to resources on how to build/test this, I'd be down to give it a shot.

**Comment by chingucoding** [comment]
> I'm curious what would happen if I remove `MinHeight`. If you/somebody can direct me to resources on how to build/test this, I'd be down to give it a shot.

Of course, you can find the building steps here: https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/developer_guide.md#building-the-repository

Regarding removing `MinHeigh`, you will need to look at `dev/NavigationView/NavigationView.xaml` (line 462). Best case would be that we can just remove the line and everything works fine. In case you want to run to check if that broke something automatically, run the "VerifyPaneLayout*" tests; searching for "VerifyPaneLayout" in the test explorer should give you the correct tests. For testing this manually, start the "MUXControlsTestApp" project. You will probably need to modify a test page though to test this. The best page would probably be "NavigationView_TestUI/Footer/PaneLayoutTestPage.xaml".

**Comment by carlos-zamora** [comment]
Hey @chingucoding. Tried working on this a few times now and haven't been able to dedicate much time to it or fix it. I'm officially dropping working on this fix. I'd love to see what had to be changed to fix this though. So looking forward to a PR from someone else 😊

**Comment by chingucoding** [comment]
Thank you for trying to work on this @carlos-zamora! I would work on this then and I'll ping you on the PR 😊
