### ISSUE TITLE
Investigate enabling brush transitions on new styles that were disabled by accent brush update

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#3913]
Accent brush PR #3909 is removing brush animations since we hit an issue, This issue is to track investigating a way to enable that back.

**Comment by mdtauk** [comment]
Could it be an issue with the ``ColorAnimationByKeyFrames``

What about something like this
```Xaml
<ColorAnimation Storyboard.TargetName="ControlPartColorBrush"
                Storyboard.TargetProperty="Color" Duration="0:0:0.083" 
                By="{ThemeResource ControlColorChange}"/>
```

Maybe @JustinXinLiu could offer an insight, he has done a lot of Xaml animation stuff

Essentially, what is needed is for the system provided Accent Colour to be given to WinUI - and for that to generate the needed AccentColor and AccentAAColor variations as both brushes and colours in the WinUI ThemeResource Dictionaries.

At the moment there are System Colours provided, I think as Brushes - but I believe @chigy mentioned some experiments with the Accent Colour generation - so maybe this is something that will be changing in the future?  Will that be WinUI 3 only, or could that change make it to WinUI 2.X also?

**Comment by karenbtlai** [comment]
> Could it be an issue with the `ColorAnimationByKeyFrames`
> 
> What about something like this
> 
> ```
> <ColorAnimation Storyboard.TargetName="ControlPartColorBrush"
>                 Storyboard.TargetProperty="Color" Duration="0:0:0.083" 
>                 By="{ThemeResource ControlColorChange}"/>
> ```

Unfortunately, this syntax also requires the TargetProperty to be a colour, not a brush, so also does not work ([Docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.animation.coloranimation?view=winrt-19041)). And you are right, some investigation is needed to re-enable the colour transitions.
