### ISSUE TITLE
Proposal: Navigation View - Don't use LeftMinimal & LeftCompact and use top mode for smaller screens when auto mode is set

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#3915]
# Proposal: Navigation View - Don't use LeftMinimal & LeftCompact and use top mode for smaller screens when the auto nide is set
Hamburger menus are not that intuitive and hard to use. In left mode, it is not an issue since it's open but in left compact and minimal it hard to use especially on a touch screen. I would suggest to get rid of them and use top mode on smaller screens.

## Summary

Hamburger menus are hard to use on a touch screen and don't provide a great experience. Please get rid of left minimal and compact which require opening the hamburger menu as well as remove the hamburger menu from the left mode and use top mode on smaller screens/window sizes.

## Rationale

* Better experience for users

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to use navigation view easily on smaller screens without moving their finger over long distance | Must |

## Open Questions

Since existing apps may use it, you can just modify auto mode to not go into left compact or minimal and disable hamburger menus for auto mode. This will not affect apps that set mode on their own.

**Comment by mdtauk** [comment]
I think there is a place for moving from a side orientated NavigationView to a top orientated one - for certain apps when the window or screen size is narrow/small.

But it should not be a default behaviour, because this is not an ideal situation when there is a large amount of NavigationView Items, or when a developer wishes to not use icons alongside text labels for their Nav View.

The "Hamburger Icon" as a toggle for showing or hiding the sidebar is a known paradigm (even if I am not a big fan of it for many apps) is at least predictable, and a minimised sidebar, displays it's icons nicely. (Icons only with a top Nav View, have some alignment issues with the selection indicator.)

![nav-view-top-icon-alignment](https://user-images.githubusercontent.com/7389110/104117428-182fb680-5319-11eb-8e82-02d7cd079252.png)

**Comment by Jaiganeshkumaran** [comment]
@mdtauk However I find hamburger menus hard to use and should not be the default in auto mode.

**Comment by mdtauk** [comment]
> @mdtauk However I find hamburger menus hard to use and should not be the default in auto mode.

If you are making a proposal for a big change in default behaviour, you will need to provide a more detailed explanation of what exactly is wrong, provide a technical think through of the implications of making the change, and find evidence of others who have a similar opinion.

Now when Windows 10 was in development, I was quite vocal about the use of the "Hamburger Menus" and there have been a few articles written about how it is not always a great UX.  When Windows 10's MDL2 was also being designed for Mobile form factors, it was felt the Sidebar Menu was a good use of space with small sized app windows.

Calculator is one of the few apps to use a totally collapsed NavigationView, and in that circumstance, it is tricky to imagine that app design without it, considering there are lots of items/modes on it.  That would not work well orientated to the top.

![image](https://user-images.githubusercontent.com/7389110/104117617-7f9a3600-531a-11eb-92ac-e2020405c118.png)

![image](https://user-images.githubusercontent.com/7389110/104117621-89bc3480-531a-11eb-8401-02f5a9f463ea.png)

**Comment by mdtauk** [comment]
The default behaviour, relies on the user seeing the Toggle button with the "Hamburger Icon" - and that will show the labels for the Icons which are visible in the compact mode.  When the app window is wide enough, the sidebar expands to show Icons and Labels.

The collapsed mode, I don't think is used by default.

**Comment by Jaiganeshkumaran** [comment]
Maybe on small screens, instead of an icon only with overflow on a more menu, could be like the old pivot style. Today Navigation view top can't be swiped which needs to bring back. However the problem is for more than 5 items, pivot swipe becomes confusing so navigation view top, unlike pivot, should not go back to the first item after reaching the last item and should be done manually by swiping long.
