### ISSUE TITLE
Combobox items are not selected properly when using the custom items panel

### ISSUE THREAD

**Issue by ssaran046** [microsoft/microsoft-ui-xaml#3918]
**Describe the bug**

Combobox items are not selected properly when using the custom items panel.

_Sample link:_  https://1drv.ms/u/s!AsISs7GoFbYYgsFYiS9jJmnpHeB5_w?e=ObT7oK

**Steps to reproduce the bug**

1. Run the provided sample
2. Click on Combobox dropdown

**Expected behavior**

Only one Combobox item needs to be selected.

**Screenshots**

![image](https://user-images.githubusercontent.com/24865096/104177060-35a27480-542e-11eb-8260-41da6ca77206.png)

**Version Info**

NuGet package version: [Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ssaran046 do you know if this issue is unique to Winui3 or if it is present in winui2/system xaml as well?

**Comment by ssaran046** [comment]
@StephenLPeters Not sure about winui2/system XAML.

**Comment by ssaran046** [comment]
Hi Team,

Any update on this issue?

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by ssaran046** [comment]
Hi Team,

Any update on this issue?
