### ISSUE TITLE
PipsPager: first focused pip should be the selected one

### ISSUE THREAD

**Issue by beervoley** [microsoft/microsoft-ui-xaml#3919]
**Describe the bug**

Currently the first pip that gets focused (when tabbing into the control) is the first one. It's not intuitive and the first focused pips should be the selected one.
**Steps to reproduce the bug**

1. Tab into the control.
2. Observe the first focused pip to be the first pip in the list (not the selected one).

**Expected behavior**

The first focused pip should be selected pip.

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by chingucoding** [comment]
@ranjeshj Mind if I work on this? Also what is the best way to solve this? Just check when pips got focus and then select focused item? That's what NavigationView is doing.

**Comment by ranjeshj** [comment]
@gabbybilka @beervoley Is the expected behavior to have tab land on the selected item instead of the first ?

**Comment by chingucoding** [comment]
It would seem reasonable to me given that PipsPager is a selection control and other selection controls such as ListView, TabView or NavigationView follow this pattern. So following that behavior in PipsPager would make the experience more consistent.

**Comment by beervoley** [comment]
@chingucoding yup, you can fix it :)
check when the pips get focus and go to the selected pip (not skipping navigation buttons because they also can be focused)

**Comment by beervoley** [comment]
@ranjeshj @chingucoding yes, it is expected behavior to go to the selected pip first. We discussed it with @gabbybilka
