### ISSUE TITLE
PipsPager themeresources typo

### ISSUE THREAD

**Issue by beervoley** [microsoft/microsoft-ui-xaml#3921]
**Describe the bug**

In both the templates for **NavigationButton** and **PipsPagerButtonBaseStyle** the brushes for Pressed state are not correct - it's a typo:
![image](https://user-images.githubusercontent.com/21356912/104224361-bd21c080-53f9-11eb-8e5b-fce097a54537.png)

**Expected behavior**

Correct the visual states to use correct themeresources.

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |

**Comment by chingucoding** [comment]
@ranjeshj @beervoley Mind if I fix this?

**Comment by mdtauk** [comment]
@chingucoding  You may also want to set the border explicitly to transparent or thickness of 0 - it looks odd with the new button Visual Styles that are coming.

**Comment by chingucoding** [comment]
I am not sure if that would be the right PR to fix that but if @ranjeshj is fine with it, sure. Otherwise, I think it would be better to handle that separately.

**Comment by beervoley** [comment]
> @ranjeshj @beervoley Mind if I fix this?

that would be very helpful, thank you 👍

**Comment by beervoley** [comment]
> I am not sure if that would be the right PR to fix that but if @ranjeshj is fine with it, sure. Otherwise, I think it would be better to handle that separately.

I'll create a new ticket regarding this for 2.6

**Comment by beervoley** [comment]
@chingucoding @mdtauk FYI [3922](https://github.com/microsoft/microsoft-ui-xaml/issues/3922)
