### ISSUE TITLE
PipsPager: missing Border thicknesses and Border brushes

### ISSUE THREAD

**Issue by beervoley** [microsoft/microsoft-ui-xaml#3922]
**Describe the bug**

Control as well as **Pips** and **Navigation Buttons** (NavigatonButtonBaseStyle and PipsPagerButtonBaseStyle) are missing their own border thickness and border brush.

**Expected Behaviour**
Add transparent border to the control, pips and buttons so it doesn't use the default inherited values.

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by mdtauk** [comment]
This is how they look with the ``Latest`` Visual Styles on them

![image](https://user-images.githubusercontent.com/7389110/104237942-bb371c00-5450-11eb-9cf3-30524d674ada.png)

**Comment by chingucoding** [comment]
@mdtauk Would you like to work on this issue by any chance? It seems that you already have a good idea of what needs to be fixed here.

**Comment by mdtauk** [comment]
> @mdtauk Would you like to work on this issue by any chance? It seems that you already have a good idea of what needs to be fixed here.

I think we have established I am not super confident with doing Pull Requests, so I am happy to sit this one out, and just act as a signpost lol.

It is also worth mentioning that the Expander is exhibiting the same issue - but work is still on-going with that control, and I don't think any of the design work has been finalised.

![image](https://user-images.githubusercontent.com/7389110/104246349-bdec3e00-545d-11eb-8b2b-4a733592a956.png)

**Comment by chingucoding** [comment]
I would say practice makes perfect, but of course you are already doing so much on this repository! If you and @ranjeshj and @beervoley don't mind, I would like to look into this. @mdtauk since it looks like you got an idea of what the problem is, can you recommend what the best way to fix this would be? Also @Felix-Dev since you also have good ideas regarding these kind of scenarios.

**Comment by mdtauk** [comment]
> I would say practice makes perfect, but of course you are already doing so much on this repository! If you and @ranjeshj and @beervoley don't mind, I would like to look into this. @mdtauk since it looks like you got an idea of what the problem is, can you recommend what the best way to fix this would be? Also @Felix-Dev since you also have good ideas regarding these kind of scenarios.

I think it is because only the Button Foreground and Background theme resources are included, so there is no override for the border strokes.

https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/PipsPager/PipsPager_themeresources.xaml

This is ok with the WinUI2_dot_5 visuals, as the buttons don't use borders.  Setting the border strokes to **Transparent** and/or setting the **BorderThickness** to 0, will probably do it.

```Xaml
<ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Light">
            <StaticResource x:Key="PipsPagerSelectionIndicatorForeground" ResourceKey="SystemControlForegroundAccentBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundPointerOver" ResourceKey="SystemControlHighlightListLowBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundPressed" ResourceKey="SystemControlHighlightListMediumBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundDisabled" ResourceKey="SystemControlDisabledTransparentBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundPointerOver" ResourceKey="SystemControlHighlightAltBaseHighBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundPressed" ResourceKey="SystemControlHighlightAltBaseHighBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundDisabled" ResourceKey="SystemControlDisabledBaseMediumLowBrush" />
        </ResourceDictionary>

        <ResourceDictionary x:Key="Dark">
            <StaticResource x:Key="PipsPagerSelectionIndicatorForeground" ResourceKey="SystemControlForegroundAccentBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundPointerOver" ResourceKey="SystemControlHighlightListLowBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundPressed" ResourceKey="SystemControlHighlightListMediumBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundDisabled" ResourceKey="SystemControlDisabledTransparentBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundPointerOver" ResourceKey="SystemControlHighlightAltBaseHighBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundPressed" ResourceKey="SystemControlHighlightAltBaseHighBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundDisabled" ResourceKey="SystemControlDisabledBaseMediumLowBrush" />
        </ResourceDictionary>

        <ResourceDictionary x:Key="HighContrast">
            <StaticResource x:Key="PipsPagerSelectionIndicatorForeground" ResourceKey="SystemControlForegroundAccentBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundPointerOver" ResourceKey="SystemControlHighlightListLowBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundPressed" ResourceKey="SystemControlHighlightListMediumBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonBackgroundDisabled" ResourceKey="SystemControlTransparentBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundPointerOver" ResourceKey="SystemControlHighlightAltBaseHighBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundPressed" ResourceKey="SystemControlHighlightAltBaseHighBrush" />
            <StaticResource x:Key="PipsPagerPageNavigationButtonForegroundDisabled" ResourceKey="SystemControlDisabledBaseMediumLowBrush" />
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
```

**Comment by chingucoding** [comment]
Thank you @mdtauk , I'll create the PR in the next few days then.

**Comment by mdtauk** [comment]
> Thank you @mdtauk , I'll create the PR in the next few days then.

There is the 2dot5 and the Latest ThemeResource Dictionaries now, so it whilst only the ``Latest`` visuals have the problem, it would be wise to include the Border resources in both sets.

**Comment by beervoley** [comment]
> I would say practice makes perfect, but of course you are already doing so much on this repository! If you and @ranjeshj and @beervoley don't mind, I would like to look into this. @mdtauk since it looks like you got an idea of what the problem is, can you recommend what the best way to fix this would be? Also @Felix-Dev since you also have good ideas regarding these kind of scenarios.

@chingucoding sure, go ahead :) I think just by adding the border brush and thickness to the buttons should do the trick

**Comment by ranjeshj** [comment]
we are going to be updating pips pager style shortly :)
