### ISSUE TITLE
Question: Which Windows version for Development and/or running

### ISSUE THREAD

**Issue by JohnF38** [microsoft/microsoft-ui-xaml#3928]
Hello, 

I'm a bit confused with the minimum required Windows 10 version for developing and running WinUI 3.0 applications.

What about current state and future plans : to develop a WinUI3.0  app and to run a WinUI3.0 app ?

Thanks for your help !
BR 
John

**Comment by StephenLPeters** [comment]
WinUI 3.0 requires the minimum target version for your app to be RS4 (build 17134) or higher and that you have very specific versions VS 2019.  you can find more info at https://docs.microsoft.com/en-us/windows/apps/winui/winui3/
