### ISSUE TITLE
Proposal: Adopt __CxxFrameHandler4 for improved binary size

### ISSUE THREAD

**Issue by Austin-Lamb** [microsoft/microsoft-ui-xaml#393]
# Proposal: Adopt __CxxFrameHandler4 for improved binary size

## Summary
See this blog post for details, using MUX as an example already: 
https://devblogs.microsoft.com/cppblog/making-cpp-exception-handling-smaller-x64/

## Rationale
If this is turned on for MUX, the binary size reduces significantly, which helps with disk space, package size, disk I/O and so on.

This benefits every consumer of MUX 'for free' once they pick up a new package version.

## Functional Requirements
This is a perf improvement, not a functional change, so not sure what to write here.  It should reduce binary size, and have no other functional impact.

## Important Notes
This can't be adopted today since the Store library support isn't done yet, and VS 2019 hasn't yet RTM'd.  Per the blog post noted above, this should land in VS 2019 Update 1.  Then the MUX repo and CI system would need to be able to use that toolchain before this could be enabled.

**Comment by jevansaks** [comment]
I hear that what we need for this is in VS2019 RTM so we'll wait for that to ship and for Hosted agents in azure pipelines to be available with that before we switch.
