### ISSUE TITLE
The Windows.UI.Color type has no fields in ref assembly

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/microsoft-ui-xaml#3931]
**Describe the bug**

The `Windows.UI.Color` type in the `System.Runtime.WindowsRuntime` ref assembly shipped with the UWP SDK is incorrecty trimmed and contains no fields. This causes the C# compiler to allow methods that have an `out Color` parameter and no definite assignment to it. Given that the type actually does have fields, this technically breaks the C# spec and can result in incorrect behavior for users of the method. Essentially, this is like if a dev used `Unsafe.SkipInit(out color)` every time.

Noticed this while reviewing https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3503.
See comment [here](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3503#discussion_r555927366).

**EDIT:** apparently this is/was an issue with pretty much all .NET Standard 2.0 ref assemblies, see: https://github.com/dotnet/runtime/issues/16402.
Leaving this open (unless you want to close it) just as a reference until we can confirm this is no longer an issue with WinUI 3 😄

**Steps to reproduce the bug**

1. Add `using Windows.UI`
2. Paste the following snippet:

```csharp
static void Test(out Color color)
{
}
```

3. Build

**Expected behavior**

The build should fail with the following error:

> The out parameter 'color' must be assigned to before control leaves the current method

**Screenshots**

Here is the `Color` type opened in dotPeek:

<details>
    <summary><b>Color type in dotPeek (click to expand):</b></summary>
<br/>

![image](https://user-images.githubusercontent.com/10199417/104347313-bfbb0d80-5500-11eb-8d51-87f6596d5ad3.png)
</details>

<details>
    <summary><b>Color type in dnSpy (click to expand):</b></summary>
<br/>

![image](https://user-images.githubusercontent.com/10199417/104347423-e37e5380-5500-11eb-99d4-d9c9dbf0d399.png)
</details>

The properties are empty as expected (ref assembly), but the fields being stripped away as well are causing the compiler to consider the type as an empty struct, and therefore allowing this method to build. There should be at least one field to block this behavior.

**Version Info**

- SDK-style project using `uap10.0.17763`
- `Microsoft.NETCore.UniversalWindowsPlatform` 6.2.9

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by Scottj1s** [comment]
Confirmed that the issue repros in a UWP app, but not in a WinUI 3 app.
