### ISSUE TITLE
ContentPresenter Background brush not filled for text background in SystemHighContratTheme

### ISSUE THREAD

**Issue by susmitha-sundar** [microsoft/microsoft-ui-xaml#3940]
**Describe the bug**

ContentPresenter background color not filled for entire control. ContentPresenter's content background filled with black color while applying the system highcontrast theme.

**Steps to reproduce the bug**
1. Run the attached sample.
2. ContentPresenter's content background filled with black color. 

**Expected behavior**

ContentPresenter's background color should applied for content background.

**Screenshots**

HighContrast Theme:
![image](https://user-images.githubusercontent.com/60175573/104446309-44b92c00-55c0-11eb-9a9b-db95ddb12ee8.png)

Default Theme:
![image](https://user-images.githubusercontent.com/60175573/104446379-5f8ba080-55c0-11eb-845e-3836aeb0b00a.png)

**Version Info**
NuGet package version: [Microsoft.WinUI 3.0.0-preview3.201113.0]

Sample:
[SystemTheme_Issue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5808304/SystemTheme_Issue.zip)

**Comment by chingucoding** [comment]
@YuliKl Is this a behavior to ensure that contrast ratios for text are always met?

**Comment by YuliKl** [comment]
@susmitha-sundar I believe you're seeing the [HighContrastAdjustment property](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.highcontrastadjustment?view=winrt-19041) in action. Try setting it to `None` if you don't want the black color behind your text to show up in HC.

**Comment by susmitha-sundar** [comment]
Hi Team,

Thanks for your solution.

Its working.

Regards,
Susmitha S
