### ISSUE TITLE
Proposal: Automatically scroll to selected TabViewItem

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#3945]
See https://github.com/microsoft/terminal/issues/8785

Say an app has many tabs open, such that the tabs must scroll in the tab view. If the app selects a tab that's currently not visible, then the TabView should automatically scroll that TabViewItem into view.

Either that, or provide some way of manually scrolling the TabViewItems so we can implement it ourselves.

**Comment by michael-hawker** [comment]
@zadjii-msft in the meantime, could you use the `TabView.SelectionChanged` event to then grab the selected `TabViewItem` object and call `Focus` on it?

**Comment by chingucoding** [comment]
@stmoy What do you think about this? Would this be fine to work on?

**Comment by stmoy** [comment]
Seems like a righteous feature to me, though I am curious if the workaround that @michael-hawker proposed would work.

**Comment by chingucoding** [comment]
Michaels workaround should work and would also be the way to solve this in TabView.
