### ISSUE TITLE
Issue: ImageIcon (& AnimatedIcon?) do not support IconElement's Foreground colour

### ISSUE THREAD

**Issue by JohnnyWestlake** [microsoft/microsoft-ui-xaml#3946]
**Describe the bug**

 ImageIcon appears to be missing support from `IconElement`'s `Foreground` property, which other `IconElement` support.

**Steps to reproduce the bug**

1. Use 2.6. pre-release pacakge
2. Create an ImageIcon in XAML, set the source to a coloured image, and then set Foreground to green
3. Image is loaded with foreground not applied

**Expected behavior**
So the question is here is what is the intention. All other IconElements respect the foreground colour and re-colour their icons to support the Foreground colour. BitmapIcon will recolour its source image by default. I would assume ImageIcon should either do the same, or explicitly note somewhere in the documentation that it is not applicable to this Icon source. Same for `AnimatedIcon`?

NuGet package version: 
2.6.0-prerelease.210113001

**Comment by ranjeshj** [comment]
Thanks for the quick feedback @JohnnyWestlake  :) 

I believe ImageIcon does not support the Foreground property. @MarissaMatt @StephenLPeters  as FYI. The Spec should include details - https://github.com/microsoft/microsoft-ui-xaml-specs/pull/109

**Comment by MarissaMatt** [comment]
Thank you @JohnnyWestlake for bringing this to our attention! I will update the spec to document that ImageIcon does not support the foreground property but @ranjeshj is correct that AnimatedIcon does support the foreground property. I will make it clearer in the AnimatedIcon spec and the guidance documentation for icons where the foreground property is/isn't supported.

**Comment by chingucoding** [comment]
What would be the best way to resolve this issue? Has this been solved by updating the documentation to point that out and this can be closed or would this be a WinUI 3 feature to add? @StephenLPeters @ranjeshj FYI
