### ISSUE TITLE
Enable ImageIconTest

### ISSUE THREAD

**Issue by licanhua** [microsoft/microsoft-ui-xaml#3949]
reenable what is disabled in  #3948
                /*
                This is an unparented ImageIcon, so looking up the default foreground and verifying	
                is a bit wierd. The colors are also chaning, so this is going to fail with those changes	
                So commenting this check out for now to make the test more resilient.

                var theme = Application.Current.RequestedTheme;
                if (theme == ApplicationTheme.Dark)
                {
                    Verify.AreEqual(((SolidColorBrush)imageIcon.Foreground).Color, Colors.White);
                }
                else
                {
                    Verify.AreEqual(((SolidColorBrush)imageIcon.Foreground).Color, Colors.Black);
                }
                */

**Comment by ranjeshj** [comment]
@StephenLPeters FYI
