### ISSUE TITLE
TabView color problems

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#3950]
**Describe the bug**

With the new colors we introduced in the token-experiment branch, we broke TabView items' contrast. There are two specific problems that need to be corrected:
1. **Icon color** - currently it's almost invisible
![image](https://user-images.githubusercontent.com/13142665/104660759-03865200-567c-11eb-9c82-67fa0d6c19b3.png)
![image](https://user-images.githubusercontent.com/13142665/104660803-1862e580-567c-11eb-8e14-ed91320454e6.png)
![image](https://user-images.githubusercontent.com/13142665/104660889-46e0c080-567c-11eb-9992-ca2dee2debfc.png)
![image](https://user-images.githubusercontent.com/13142665/104660851-3597b400-567c-11eb-8337-1bdc988a00de.png)

2. **Difference between selected vs unselected tabs** - again, identifying which tab is currently selected based on current color alone is very difficult, the differences in background color do not meet 3:1 contrast ratios.
![image](https://user-images.githubusercontent.com/13142665/104661096-ab9c1b00-567c-11eb-9840-8e08faef8e9f.png)
![image](https://user-images.githubusercontent.com/13142665/104661127-b8b90a00-567c-11eb-8c11-fa9d34a8ae79.png)

**Proposed fix**

As a temporary solution, we should update the 1) color of the icon, and 2) the font weight of the selected tab title.
1. Set `TabViewItemIconForeground`, `TabViewItemIconForegroundPressed` and `TabViewItemIconForegroundPointerOver` resources to TextFillColorSecondaryBrush. Set `TabViewItemIconForegroundSelected` to TextFillColorPrimaryBrush
https://github.com/microsoft/microsoft-ui-xaml/blob/574dc96089be6a46887924cdabe70b41651c4b8b/dev/TabView/TabView_themeresources.xaml#L20
2. Change tab item's ContentPresenter's https://github.com/microsoft/microsoft-ui-xaml/blob/99e91397792854dea2f474fae22ededa944b8ad7/dev/TabView/TabView.xaml#L682 font weight to semibold when the tab is in Selected, PointerOverSelected and PressedSelected states.

**Additional context**

Copied from internal [bug 1](https://microsoft.visualstudio.com/OS/_workitems/edit/30849808) and [bug 2](https://microsoft.visualstudio.com/OS/_workitems/edit/30849769)

**Comment by mdtauk** [comment]
👍 for Semibold

**Comment by chingucoding** [comment]
I would like to work on this.

**Comment by mdtauk** [comment]
> I would like to work on this.

You may want to give the Windows Terminal guys a heads up on the changes you make.
