### ISSUE TITLE
Re-enable the failed test cases because testapp is changed default style to latest

### ISSUE THREAD

**Issue by licanhua** [microsoft/microsoft-ui-xaml#3956]
reenable the test case which is disabled in PR #3948
search 3956

**Comment by licanhua** [comment]
@karenbtlai Can you take a look at the left test cases? two of the radiobutton test cases are missing the definition of RadioButtonCheckGlyphFillPressedDisabled 
I don't know who is working on TabView and GamePadTest should be enabled

**Comment by karenbtlai** [comment]
> @karenbtlai Can you take a look at the left test cases? two of the radiobutton test cases are missing the definition of RadioButtonCheckGlyphFillPressedDisabled
> I don't know who is working on TabView and GamePadTest should be enabled

I am unable to test for TabView's GamePadTest since I don't have a gamepad to debug. Who can be assigned to that test failure?

**Comment by chingucoding** [comment]
> I am unable to test for TabView's GamePadTest since I don't have a gamepad to debug. Who can be assigned to that test failure?

I can take a loo at the GamePad test failure. Is the test failure only on lower versions or across all versions?
