### ISSUE TITLE
Proposal: Pivot visual refresh

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#3957]
# Proposal: Pivot visual refresh 

![image](https://user-images.githubusercontent.com/7389110/104764614-8c29ee80-575f-11eb-851c-63e85a188deb.png)

https://user-images.githubusercontent.com/7389110/104976838-0a072780-59f6-11eb-8ceb-3c163fe23b84.mp4

_This example uses a selection indicator to fit the text string, as suggested by @Jaiganeshkumaran_ 

## Summary

As most of the the WinUI controls are being given a visual refresh, Pivot should also be given some changes to make it feel like it belongs with the other controls, and to improve the look and feel of this control.

## Rationale

* Pivot is under utilised and under valued, it also feels awkwardly static compared to the smooth animating and transitioning controls coming with the visual refresh
* Pivot is used as a primitive for other controls such as the ``TabbedCommandBar`` coming to the Windows Community Toolkit
* FluentUI includes this control, with some of the same visual style changes I am proposing

## Scope

| Capability | Priority |
| :---------- | :------- |
| The control must sit comfortably with the other WinUI refreshed control visuals | Must |
| The Selection Indicator width should animate/transition between VisualStates | Must |
| The brushes and styling of the controls should allow it to feel closer to the FluentUI implementation | Should |
| The position of the Selection Indicator could transition when the Selected PivotItem is changed | Could |

## Important Notes

The changes to this control consist of a few notable changes:
- The overall height of the control will be reduced when the Pivot Title is visible.
- The brushes used correspond to the new brushes coming as part of the visual refresh (including the use of the Accent AA colours for the selection indicator.
- Font sizing for the Pivot Labels is reduced slightly, to fit better with the backing plates added for the PointerOver and Pressed VisualStates

## ThemeResources Used

<img width="664" alt="New Pivot Item" src="https://user-images.githubusercontent.com/7389110/104791125-7c2b0280-5791-11eb-8f34-3469a35dd70e.png">

_Pivot Item Header States_

----

Here is a breakdown of which theme resources could be used for each state:

| VisualState | Property | Value |
| :---------- | :------- | :------- |
| Default | Background | GhostFillTransparent |
|  | Foreground | TextFillSecondary |
| PointerOver | Background | GhostFillSecondary |
|  | Foreground | TextFillPrimary |
| Pressed | Background | GhostFillTertiary |
|  | Foreground | TextFillTertiary |
| Disabled | Background | GhostFillTransparent |
|  | Foreground | TextFillDisabled |
|  |  |
| Default - Selected | Background | GhostFillTransparent |
|  | Foreground | TextFillPrimary |
|  | Selection Indicator Fill | AccentAAFillDefault |
|  | Selection Indicator Width | 32px • or text length −12px |
| PointerOver - Selected | Background | GhostFillSecondary |
|  | Foreground | TextFillPrimary |
|  | Selection Indicator Fill | AccentAAFillSecondary |
|  | Selection Indicator Width | 48px • or text length |
| Pressed - Selected | Background | GhostFillTertiary |
|  | Foreground | TextFillTertiary |
|  | Selection Indicator Fill | AccentAAFillTertiary |
|  | Selection Indicator Width | 16px • or text length −24px |
| Disabled - Selected | Background | GhostFillTransparent |
|  | Foreground | TextFillDisabled |
|  | Selection Indicator Fill | TextFillDisabled |
|  | Selection Indicator Width | 32px • or text length |

### Transitioning between Selected and Unselected state
- extend the Selection Indicator width by +20px - into the Default or PointerOver width;
- fade in the indicator visual;

When transitioning into the Unselected state from the Selected state:
- reduce the Selection Indicator width by −20px;
-fade the indicator out;

## Open Questions

There have been a few issues asking for the Selection Indicator to animate between PivotItem selection changes, as the NavigationView's indicator does.  Whether this is following the finger as you swipe, or after you release and the Selected Item actually changes. #848 

Fluent UI animates the SelectionIndicator within the Pivot Item itself, which may be a good compromise, as it should not result in a big re-working of how the control is built.

![FluentUI Pivot control](https://user-images.githubusercontent.com/7389110/104766957-4bcc6f80-5763-11eb-9214-73db6caa11b4.gif)

**Comment by Jaiganeshkumaran** [comment]
@mdtauk I feel like your proposal has a very small underline and needs to be increased. Maybe 24px from left and right of the text

**Comment by mdtauk** [comment]
That is a fair point, the width of the underline could be variable to the width of the text.

For the proposal, I thought it would be easier to specify at sizes, and it would be visually distinctive.

The key part would be the animation of the Selection Indicator as you hover and press each pivot header.

**Comment by mdtauk** [comment]
Here is an example of the Pivot Selected Indicator reduced 12px from either side at **Default** and reduced 24px from either side at **Pressed**

![image](https://user-images.githubusercontent.com/7389110/104898289-5ceacb80-5971-11eb-9510-e40694d11498.png)

**Comment by jp-weber** [comment]
It would also be great if the line under the items could be implemented with connected animations like the NavigationView and the individual items.

**Comment by mdtauk** [comment]
> It would also be great if the line under the items could be implemented with connected animations like the NavigationView and the individual items.

That is one of the open questions, but will require a lot of work to re-implement the control.

**Comment by mdtauk** [comment]
Adding a motion example of the Pivot states and transitions

https://user-images.githubusercontent.com/7389110/104976838-0a072780-59f6-11eb-8ceb-3c163fe23b84.mp4

**Comment by YuliKl** [comment]
Thank you @mdtauk, but we're no longer investing in Pivot.

**Comment by mdtauk** [comment]
Can I just check, would you accept community pull requests, especially when the source is added?

Allowing the community to update and maintain the control will allow yourselves to divest it.

I understand this may require WinUI 3 @YuliKl

**Comment by StephenLPeters** [comment]
In general we are very excited to accept community contributions once we are able to open source.

**Comment by jordan-msftfan** [comment]
@YuliKl Can you disclose to the community which controls are no longer officially invested?

**Comment by chigy** [comment]
@mdtauk , we currently have no intention of maintaining Pivot control. As I mentioned in other Pivot related topic, we expect people to use top NavigationView which already has the built in motion and visual. If that does not suffice some of the needed functionalities, please propose those separately.

**Comment by jp-weber** [comment]
@chigy 
That's really sad to hear, I can understand it well with the Hub control, but I find the Pivot control indispensable.

The behaviour of the two control elements is already very different. I don't see how we could adequately add functions to the NavigationView to enable the same behaviour. For example the the gesture navigation (touch) and already loading the other page/item. I would find the control very useful, especially for Windows 10X.

**Comment by mdtauk** [comment]
> @mdtauk , we currently have no intention of maintaining Pivot control. As I mentioned in other Pivot related topic, we expect people to use top NavigationView which already has the built in motion and visual. If that does not suffice some of the needed functionalities, please propose those separately.

So is it now advised that you should add a NavigationView within another NavigationView?

When a pivot is being used for a section of content, within a page, hosted in a NavigationView?

**Comment by chigy** [comment]
> @chigy
> That's really sad to hear, I can understand it well with the Hub control, but I find the Pivot control indispensable.
> 
> The behaviour of the two control elements is already very different. I don't see how we could adequately add functions to the NavigationView to enable the same behaviour. For example the gesture navigation (touch) and already loading the other page/item. I would find the control very useful, especially for Windows 10X.

Hello @jp-weber ,
Could you please open separate requests for us to consider a control that provides the above capabilities and reason why they are helpful, including use cases, etc.?

As to touch, it is a behavior carried over from Windows Phone era and it has not been something that had been useful on a larger tablet size devices, so I would like to understand how you are using it and find it indispensable.

**Comment by chigy** [comment]
> > @mdtauk , we currently have no intention of maintaining Pivot control. As I mentioned in other Pivot related topic, we expect people to use top NavigationView which already has the built in motion and visual. If that does not suffice some of the needed functionalities, please propose those separately.
> 
> So is it now advised that you should add a NavigationView within another NavigationView?
> 
> When a pivot is being used for a section of content, within a page, hosted in a NavigationView?

@mdtauk , Please first consider such a nesting is useful and makes productive experience to your users. If so, NavigationView is what might give you the easiest way to construct such UI today. That said, think not about what control to use, but focus on what user experience you want to provide. It might not be Pivot nor NavigationView depending on what you want to do.

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/108241811-235dd980-7144-11eb-8e76-cfd6b3fd8810.png)
![image](https://user-images.githubusercontent.com/7389110/108241834-2953ba80-7144-11eb-83be-c572283d312e.png)

Microsoft News is a clear example

**Comment by jp-weber** [comment]
> Hello @jp-weber ,
> Could you please open separate requests for us to consider a control that provides the above capabilities and reason why they are helpful, including use cases, etc.?
> 
> As to touch, it is a behavior carried over from Windows Phone era and it has not been something that had been useful on a larger tablet size devices, so I would like to understand how you are using it and find it indispensable.

Hello @chigy, I will open a separate issue on this tomorrow. Regarding the touch story, if you have an app active in full-screen mode, this may seem strange, but there is the option of reducing the app or having several apps open next to each other. 
e.g. also the MS News and the MS Finance app without clicking the header items.
![Pivot_Tablet](https://user-images.githubusercontent.com/10946850/108258008-db4cb000-715f-11eb-841e-6740ebca9194.gif)

If you are also an Apple user, such gestures are very intuitive if you then use windows applications that can do this.

**Comment by jordan-msftfan** [comment]
by the way, microsoft recently released an application called "Journal" that makes heavy use of Pivot in its UI
for this reason, I don't think Pivot is out of date in MS design specifications
![be2yGsKvmE](https://user-images.githubusercontent.com/77601580/108582018-95643780-736b-11eb-8f1d-6706291e372d.png)
![pf5ZDT0Fug](https://user-images.githubusercontent.com/77601580/108582021-96956480-736b-11eb-9a01-fbd08e79064a.png)

**Comment by mdtauk** [comment]
Pivots used not for navigation, but for tool set changes, or view changes.

As this control is still used, I hope eventually Microsoft will allow the community to maintain and update the Pivot control.

**Comment by saint4eva** [comment]
> As to touch, it is a behaviour carried over from Windows Phone era and it has not been something that had been useful on a larger tablet size device, so I would like to understand how you are using it and find it indispensable.

Many Windows devices are not touch enabled - both laptops and tablets. Even Surface Studio and Hub are touch-enabled. Note that all the modern Windows devices are touch capable. So, the feature should be useful and has use cases.

**Comment by robloo** [comment]
This needs to be revisited considering the Pivot conversations elsewhere. Removing Pivot caught everyone by surprise and is poor direction from Microsoft.
