### ISSUE TITLE
NumberBox has a precision floating point bug

### ISSUE THREAD

**Issue by crutkas** [microsoft/microsoft-ui-xaml#3959]
**Describe the bug**

**Steps to reproduce the bug**

Use the following code:
`<muxc:NumberBox 
    Margin="0, 10, 0, 0"
    Header="Search weight:"
    Value="1"
    SpinButtonPlacementMode="Compact"
    SmallChange=".01"
    LargeChange=".1"
    Minimum="0"
    Maximum="5"
    />`

Then do a small or large change,

**Expected behavior**

Get proper precision, to small / large snap.  Seems like a floating point precision error

**Screenshots**

![image](https://user-images.githubusercontent.com/1462282/104772510-67feeb00-5728-11eb-8129-96f51e9a91ea.png)

**Version Info**
UWP 6.2.10

NuGet package version: 
Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by SavoySchuler** [comment]
This bug would be coming off the [iNumberFormatter2 object](https://docs.microsoft.com/en-us/uwp/api/Windows.Globalization.NumberFormatting.INumberFormatter2?view=winrt-19041) consumed by NumberBox  [here](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.numberbox.numberformatter?view=winui-2.5#Microsoft_UI_Xaml_Controls_NumberBox_NumberFormatter). 

My assumption is that this is might be a behavior of the default iNumberFormatter2 object. Have you can creating a custom NumberFormatter to use here to see if this could be resolved by an increase in significant figures or alternate [RoundingAlgorithm](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.numberformatting.roundingalgorithm?view=winrt-19041)?

**Comment by crutkas** [comment]
Im reporting the issue with how to reproduce it easily. Sadly I don’t have cycles to dive in more. Please fix as this makes it unusable for decimal based numbers and should be an easy thing to validate with unit tests.

**Comment by StephenLPeters** [comment]
@teaP Do you know if there are settings we can tweak on the default number formatter to get something a bit nicer here? Would this require exposing those settings on numberbox as well?

**Comment by teaP** [comment]
> @teaP Do you know if there are settings we can tweak on the default number formatter to get something a bit nicer here? Would this require exposing those settings on numberbox as well?

This didn't readily repro in the test app, so I'd have to dig a bit deeper.

**Comment by crutkas** [comment]
[TestUxForPlugin.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5876113/TestUxForPlugin.zip)

Here is the app i used to find the issue.

**Comment by carlos-zamora** [comment]
I'm guessing sliders have that issue too? Windows Terminal just got a similar issue filed: https://github.com/microsoft/terminal/issues/9008

**Comment by DHowett** [comment]
No, the terminal issue is in jsoncpp.

**Comment by tomtom-m** [comment]
I'm experiencing the same behavior. First thought it only occurred when smallChange=0.1, but later I also saw the behavior when smallChange had the value 0.01. 

I will tryout overriding the formatter, but I would be nice if that wasn't necessary. 

![image](https://user-images.githubusercontent.com/8580402/140894877-25fbc343-4a40-461d-906e-eb0ab320a3df.png)
