### ISSUE TITLE
TabView.UpdateSelectedItem sets incorrect item

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#3969]
**Describe the bug**

While porting `TabView` to Uno Platform I have noticed, that when the items are data bound (via `TabItemsSource`), the item selection is buggy. While debugging I noticed that the `UpdateSelectedItem` method is doing the following:

```c++
void TabView::UpdateSelectedItem()
{
    if (auto&& listView = m_listView.get())
    {
        auto tvi = SelectedItem().try_as<winrt::TabViewItem>();
        if (!tvi)
        {
            tvi = ContainerFromItem(SelectedItem()).try_as<winrt::TabViewItem>();
        }

        if (tvi)
        {
            listView.SelectedItem(tvi);

            // Setting ListView.SelectedItem will not work here in all cases.
            // The reason why that doesn't work but this does is unknown.
            tvi.IsSelected(true);
        }
    }
}
```

Notice the code tries to set the `SelectedItem` of `ListView` to the `TabViewItem`. However, when I checked the control at runtime, the item type of the `ItemsSource` of the `TabListView` is actually the item type of the bound collection (for example for `ObservableCollection<MyTabViewModel>` it would be `MyTabViewModel`). That may explain the issue mentioned in the comment - when the code sets `SelectedItem` to `TabViewItem`, it does not select anything in case the items are data bound.

This may also be the cause of #3907.

**Steps to reproduce the bug**
See above.

**Expected behavior**
`SelectedItem` should be set to the actual item type - so in case of data bound collection it should match the item type of such collection.

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml.Controls 2.5

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by MartinZikmund** [comment]
If you agree this is a bug, I am happy to implement the fix :-) .

**Comment by StephenLPeters** [comment]
Yeah, seems like you figured it out! Thanks!  And we would definitely appreciated the fix.

**Comment by MartinZikmund** [comment]
I'm on it :-)
