### ISSUE TITLE
newbie question about OnApplyTemplate

### ISSUE THREAD

**Issue by oldoldman** [microsoft/microsoft-ui-xaml#3970]
I'm trying to override the default functionality of the clear button of the TextBox . From the doc it  seems that OnApplyTemplate is the right place, so I have my class derived from TextBox as follow (CppWinRT)
```c++
//struct MyTextBox : TextBox<MyTextBox>
struct MyTextBox : TextBoxT<MyTextBox>
{
  void OnApplyTemplate()
  {}
};
```
but it never get called. How does this happen? Many thanks!

**Comment by chingucoding** [comment]
Have you created a MyTextBox or TextBox control in XAML? If you create a TextBox, your MyTextBox.OnApplyTemplate will not be called as no MyTextBox instance gets its template applied.

**Comment by oldoldman** [comment]
No.  My use case is : create MyTextBox instance in code , set its Style to my customized style (which is a modified copy of TextBox default Style) and add the instance to an Xaml Page. I my understanding, in the process of setting Style, the OnApplyTemplate will be called. If not , how can I get the instance of the clear button ?

**Comment by chingucoding** [comment]
This is strange, if you are doing everything correct, that should create call OnApplyTemplate. It's hard to tell what is going on here without the actual code.

**Comment by oldoldman** [comment]
I can confirm that everything is correct, because the visual appearance changed according to my customized Style. And tried the Loaded callback, it not works
```c++
struct MyTextBox : TextBoxT<MyTextBox>
{
  MyTextBox()
  {
    Loaded([&](IInspectable const &sender,RoutedEventArgs const args){
      printf("loaded\n");  // console and appcontainer
    });
  }
  void OnApplyTemplate()
  {
    printf("OnApplyTemplate\n");
  }
};
```

**Comment by chingucoding** [comment]
How are you adding the control to a page? Is the page added in the visual tree (that is rendered)? Given that loaded is not being called, this sounds like a possible issue of your control not being rooted in the visual tree.

**Comment by oldoldman** [comment]
The outline of my app is
1. MainPage.xaml
```xml
<Page xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
	<Canvas Grid.Row="0" x:Name="MainCanvas"/>
</Page>
```
2. MainPage.h
```c++
struct MainPage : PageT<MainPage>
{
  MainPage::MainPage()
  {
    Application::LoadComponent(*this,Uri(L"ms-appx:///MainPage.xaml"));
    cvs = FindName(L"MainCanvas").as<ICanvas>();    // hold the cvs for later use
  }
};
```
3.  App.h
```c++
struct App : ApplicationT<App>
{
  void OnLaunched(LaunchActivatedEventArgs const &)
  {
    Window window = Window::Current();
    window.Content(make<MainPage>());
    window.Activate();
  }
}
```
4. on some none-UI thread
```c++
auto dispatcher = cvs.as<IDependencyObject>().Dispatcher();
dispatcher.RunAsync(CoreDispatcherPriority::Normal,[&,cvs]{
  auto resource = Application::Current().Resources();
  auto txt = MyTextBox();
  auto style = resource.Lookup(box_value(L"MyStyle"));
  txt.Style(style.as<Style>());
  cvs.as<IPanel>().Children().Append(txt);
  Canvas::SetLeft(txt,100);
  Canvas::SetTop(txt,100);
}
```

**Comment by StephenLPeters** [comment]
Hmm, can you provide a zipped up copy of a repro app so one of us can take a look? I don't see anything wrong from the provided code.

**Comment by oldoldman** [comment]
> Hmm, can you provide a zipped up copy of a repro app so one of us can take a look? I don't see anything wrong from the provided code.

Found why, if I use make in step 4 , it will work
```c++
auto txt = make<MyTextBox>();
```

**Comment by StephenLPeters** [comment]
great!

**Comment by oldoldman** [comment]
Sadly, I have to reopen this issue :). This time I'm extending the ContenControl as follow
```c++
struct MyControl : ContentControlT<MyControl>
{
  MyControl();
  void OnApplyTemplate();
};
```
```make<MyControl>()``` does not work for ContenControl (OnApplyTemplate does not get called). Please help!

**Comment by StephenLPeters** [comment]
The FooT<Foo> pattern in cppwinrt is used for types defined in your IDL.  If you have a MyControl runtimeclass defined in your IDL which inherits from ContentControl You should be able to do something like 

```
struct MyControl : MyControlT<MyControl>
```
Should work. See some more documentation here: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-apis#if-youre-authoring-a-runtime-class-in-a-windows-runtime-component.

I also noticed you wrote ContenControl instead of ContentControl twice in your comment, which might indicate you have a typo in your code you were copy pasting from?

**Comment by oldoldman** [comment]
I've checked my code carefully and found why. I just ```make<MyControl>()``` and does not add it to the visual tree (for example add as content of Page), so OnApplyTemplate does not get called. Very sorry for my careless. :)
