### ISSUE TITLE
Improve missing Resource Not Found exception info

### ISSUE THREAD

**Issue by zed220** [microsoft/microsoft-ui-xaml#3971]
**Describe the bug**
I'm using the WinUI in UWP. I have created a class library with custom control (such as "Class1") and refer to it in my project. Custom control has default style with setter to missing static resource. If I create this control dynamically and add it to window content, app crashes with no additional exception info.

**Steps to reproduce the bug**
1. Run example.
2. Click on button.

**Expected behavior**
Exception info must contain additional info such as "Resource WrongResource not found".

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

[App33.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5828913/App33.zip)

**Comment by StephenLPeters** [comment]
@zed220 If you enable all of the exception in the exception settings do you get more info? If so, Is this essentially a feature request to expand the error reporting for this case?  Is this the same behavior as Winui2 or system xaml or is this a regression with Winui3?

**Comment by zed220** [comment]
1. No, exception settings are not affected.
2. I can't test it in WinUI 2, sorry.

**Comment by StephenLPeters** [comment]
My last message wasn't clear, so I edited it. Is this issue essentially a feature request to expand the error reporting?

**Comment by zed220** [comment]
Yes, I think this is a feature request. This is very important for us because we work with a lot of controls in many xaml files.

**Comment by chrisglein** [comment]
The information you need is probably available in a stowed exception or some internal data structures, but it doesn't surface through the error you're seeing. Agreed this could be better. After WinUI3 has transitioned to open source and we start looking at debugging tools/extensions this seems like a candidate for improvement.

**Comment by zed220** [comment]
It would be great for this functionality to appear!

**Comment by michael-hawker** [comment]
🦙 Is this related to https://github.com/microsoft/microsoft-ui-xaml/issues/2350?

**Comment by bpulliam** [comment]
This does look like the same as #2350
