### ISSUE TITLE
Proper place to call _CrtDumpMemoryLeaks

### ISSUE THREAD

**Issue by partmachine** [microsoft/microsoft-ui-xaml#3973]
I have implemented a WinRT Component and created an App (Universal Windows Blank App) for testing.
I would like to call _CrtDumpMemoryLeaks to check for memory leaks but since the startup code is generated I cannot put it in wWinMain. I also tried the App destructor but the destructor isn't called.
What would be the proper place for this?

**Comment by StephenLPeters** [comment]
@kennykerr or maybe @jevansaks can you weigh in?

**Comment by jevansaks** [comment]
UWP apps don't do an orderly shutdown, they get called to suspend and then they're TerminateProcess'd. As a result I guarantee that the shutdown code (even if you can make it happen) is not leak-free even from the OS components. But leaks at shutdown aren't indicative of runtime leaks. If your goal is to find and fix memory leaks (especially ones that aren't in the CRT allocator), you probably want an approach like this: https://docs.microsoft.com/en-us/visualstudio/profiling/analyze-memory-usage?view=vs-2019

**Comment by duncanmacmichael** [comment]
Closing as this appears to have been answered by Jevan.
