### ISSUE TITLE
Is there any way to "bind" the svg colors to system brushes/colors?

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3974]
Hello!

I use svg images in my app. I want them to change colors according to the current color scheme / accent colors. For-example, in toolbar items the svg colors should be consistent with the text color in different visual states/themes.

Is there any way to change svg colors at runtime?

**Comment by codendone** [comment]
The current svg support is static with no object model support. The only option I can think of is to load the svg file into a buffer and search/replace the desired colors.
