### ISSUE TITLE
Update TeachingTip PlacementMode names

### ISSUE THREAD

**Issue by StephenLPeters** [Microsoft/microsoft-ui-xaml#398]
The current placement of teaching tip does not match Flyout's placement when and aligned placement mode is elected. Currently the teaching tip is placed to maximize the placement in that direction while maintaining the pointer is positioned at the center of the target. Instead the aligned placement should align the edge of the tip with the edge of the target and attempt to get the pointer as close to the center of the target as possible.

**Comment by jevansaks** [comment]
Discussed offline, we're going to update the enum names instead.
