### ISSUE TITLE
ComboBox binded with Enum Description - TextSearch looking for key instead of value

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#3980]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/ComboBox-binded-with-Enum-Description---/1311799)._

---
[severity:It bothers me. A fix would be nice]
We have created a simple sample with Combobox bound with enum description. Combobox displays the enum description values properly. when I have searched the description value by pressing text. In this case, searched text not highlighted in Combobox. 

Sample Link: 
[ComboBox.zip] (https://aka.ms/dc/file?name=B28a3ca5238e8416f8130b87ee44b4d59637463268540203388_ComboBox.zip&tid=28a3ca5238e8416f8130b87ee44b4d59637463268540203388)

Step 1: Run the sample

Step 2: Click the Combobox to open

Step 3:  Press the 'S' string to search the Second value in Combobox. In this case, the Searched word not highlighted in ComboBox.

Screenshot for your reference,
! [IssueOccuringCase.png] (https://aka.ms/dc/image?name=Ba2740e3528374d91b83c33943a676f44637463267174005353_IssueOccuringCase.png&tid=a2740e3528374d91b83c33943a676f44637463267174005353)

**Note:** In case we have type Enum first letter that bound enum value is highlighted properly

Screenshot for your reference,
! [Properlyhighlight.png] (https://aka.ms/dc/image?name=B420ccf36c31a43d0b33fcb94f8076592637463267755182343_Properlyhighlight.png&tid=420ccf36c31a43d0b33fcb94f8076592637463267755182343)

Can you provide how to search the enum description value in Combobox?

---
#### Feedback Bot on 1/17/2021, 09:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by DavidMartinSerrano** [comment]
Hi team, has anyone taken a look into this? Thanks
