### ISSUE TITLE
[Breadcrumb] Control doesn't match design

### ISSUE THREAD

**Issue by almedina-ms** [microsoft/microsoft-ui-xaml#3981]
**Describe the bug**
The control doesn't currently match the proposed design. 

Known issue from:
https://github.com/microsoft/microsoft-ui-xaml/pull/3891

**Comment by StephenLPeters** [comment]
@almedina-ms When convenient, please post a link to the design and provide info about what is missing.

**Comment by mdtauk** [comment]
> @almedina-ms When convenient, please post a link to the design and provide info about what is missing.

The Breadcrumb control is still being built - the styling for the buttons etc will come once it is functioning, I would imagine.
