### ISSUE TITLE
NumberBox's inline buttons looks strange

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#3987]
**Describe the bug**
The buttons look strange and overlap the focused border

**Steps to reproduce the bug**
``` xaml
<NumberBox Width="100" Margin="0,5" SpinButtonPlacementMode="Inline"/>
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/47348109/105159716-73835500-5b20-11eb-915a-106ad7876b60.png)   
![image](https://user-images.githubusercontent.com/47348109/105160679-96623900-5b21-11eb-8e95-e0d0127f73e7.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by MartinZikmund** [comment]
This happens when the `Width` you set is too small, so it doesn't "fit" inside the given space. However, not sure why there is a min width limitation for the text box

**Comment by alexdi220** [comment]
Buttons overlap border by height. The spin buttons should look like ComboBox 
![image](https://user-images.githubusercontent.com/47348109/105167745-286e3f80-5b2a-11eb-87f5-73d27b6c3e52.png)

**Comment by kmgallahan** [comment]
@chigy Is this issue still relevant now that the new theme doesn't use a focus rect?

![Screenshot 2021-11-18 190105](https://user-images.githubusercontent.com/5379488/142515862-e2d611eb-b82f-41f1-ba12-a67fb01a822e.jpg)

**Comment by chigy** [comment]
@kmgallahan , I don't think so. Thanks for catching!
@alexdi220 , I am closing this issue since it is fixed with new design. :)
