### ISSUE TITLE
The process has no package identity - Error in XAML Islands

### ISSUE THREAD

**Issue by deanchalk** [microsoft/microsoft-ui-xaml#3990]
**Describe the bug**

After following exactly this tutorial: 
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands
I get an error 'The process has no package identity. (0x80073D54)'.
This error occurs in the UWP App (Initialize()) that runs with the WPF app.

If I don't add the Microsoft.UI.XAML nuget to the solution, and use standard controls instead it works fine

**Steps to reproduce the bug**

Create a solution that uses XAML Islands and the Toolkit, as per the Microsoft tutorial above

**Expected behavior**
I expect the solution to run without issues

**Screenshots**

![image](https://user-images.githubusercontent.com/11065294/105202945-6bd0aa00-5b3a-11eb-9187-223d39945894.png)

**Version Info**
2.6.0-prerelease.210113001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by deanchalk** [comment]
Any update one this ? It seems that XMAL Islands is now completely broken

**Comment by deanchalk** [comment]
OK, seems like Im trying to setup XAML Islands in a WPF app that targets .net 5 - which Ive just read as being unsupported. I will therefore close this issue

**Comment by deanchalk** [comment]
Actually, Ive just tried with a WPF app that targets ,Net core 3.1, and the issue is still there

**Comment by StephenLPeters** [comment]
@Austin-Lamb and @JesseCol FYI

**Comment by JesseCol** [comment]
Adding @marb2000

**Comment by marb2000** [comment]
@deanchalk can you create a app manifest in your WPF app? The toolchain requires a manifest to adding automatically some attributes.  If this doesn't work, you can follow this guideline: 
https://techcommunity.microsoft.com/t5/windows-dev-appconsult/using-xaml-islands-on-windows-10-19h1-fixing-the-quot/ba-p/376330 
Let me know of this helps.

**Comment by deanchalk** [comment]
Adding an app manifest or a packaging project didn't work, but thanks for the suggestion. 
It seems like XAML islands are no longer something that works, as these are all new projects following a Microsoft tutorial - it doesn't get any simpler than that. I need to move onto something else, so ill try again after the next release to see if its been fixed
