### ISSUE TITLE
Proposal: Pre-emptive NavigationView visual refresh

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#3999]
# Proposal: Pre-emptive NavigationView visual refresh

## Summary

I know there is probably work and code ready to add to the repo for this control, but it would be good for the community to submit ideas and feedback before work is done with this control's refresh.

![Visual Mockup example 1](https://user-images.githubusercontent.com/7389110/105447773-c23e0580-5c6c-11eb-8f11-1fa691d4965c.png)

![Visual Mockup example 2](https://user-images.githubusercontent.com/7389110/105447741-b3efe980-5c6c-11eb-8ff0-47cde1e4c291.png)

As the visual refresh works its way across all of WinUI - here is a place for the community to share thoughts on the NavigationView - which is essentially the default app pattern for WinUI apps.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This refresh should fit nicely with Edge and FluentUI - whilst adopting the new colours and styling | Must |
| With reveal going away, defaults should take this into accound | Should |
| An Inset Shadow should be added when in Left and LeftCompact modes (as well as RtL flow) | Should |
| Minimal mode could remain alongside a **Flyout** mode which displays a menu flyout with NavigationViewItems | Could |

## Important Notes

Allowing the NavigationView to use MenuFlyouts would enable a scenario like this one created by @zeealeid
![calculator concept by @zeealeid on twitter ](https://user-images.githubusercontent.com/7389110/105428388-38c80c80-5c47-11eb-98d1-9ed1594b4c71.png)

Which I think is a very good use of space for smaller windows, and other utility style applications.

----

Other things to point out:
- Selected Nav View Items would have a backplate which has a 4px margin top, left, and bottom - but flush with the right, below the inset shadow;
- The Search Box would have it's search icon aligned to the left, to better match the NavigationViewItems with icons on their left;
- When in Minimal or Flyout modes, the navigation pane would swap it's Inset Shadow for a DropShadow - as with other flyouts;
- Icons would use the Fluent UI System Icons, for Settings, Back and the Hamburger buttons - it would be an open question as to how or if the Filled icon states are adopted by the control.

## Open Questions

As mentioned above, Fluent UI System Icons have a Regular and Filled state, which are typically used to indicate an Active or Selected state - the NavigationView (and TabView) have a selected concept, and so an easy way to use these Filled states would be useful I think.

**Comment by jordan-msftfan** [comment]
This design looks fantastic!

One question is that NavigationView has 2 different PaneDisplayMode, one is at left like the design the other is at the top.
How about NavigationView with PaneDisplayMode set at top? Should it also have a new design, or be part of Pivot or TabsView?

**Comment by mdtauk** [comment]
> This design looks fantastic!
> 
> One question is that NavigationView has 2 different PaneDisplayMode, one is at left like the design the other is at the top.
> How about NavigationView with PaneDisplayMode set at top? Should it also have a new design? Or be part of Pivot or TabsView?

I need to have a think about the top design mode - it has other considerations but is not radically different to the side aligned version

**Comment by mdtauk** [comment]
Guess I was right to put **Pre-emptive** in the title lol

#4009  **Navigation View Visual Update**

**Comment by jordan-msftfan** [comment]
Interestingly, this design is highly consistent with Microsoft's new style.

**Comment by mdtauk** [comment]
> Interestingly, this design is highly consistent with Microsoft's new style xd.

When you see the direction the wind is blowing, its not too difficult to put yourself into the mindset of what is to come.

But I went a little further with some details like the Selected Item States and the Inset Shadow.

The Overlay/Flyout mode is also a new feature I am proposing, rather than just a visual update.

**Comment by jordan-msftfan** [comment]
> But I went a little further with some details like the Selected Item States and the Inset Shadow.
> 
> The Overlay/Flyout mode is also a new feature I am proposing, rather than just a visual update.

There's still a lot of room to enhance NavigationView in terms of functionality

For example, in WinUI 3, Hierarchical NavigationView is currently ignored.

In have multiple items in the navigation menu, if there is the Overlay/Flyout navigation menu mode and compact mode 2 kind of variable type, I'll prefer to go to choose the Overlay/Flyout mode.

Under the compact mode while it is possible to save the screen space, but in some cases difficult to jump to other items, in the Overlay/Flyout mode, I can put it in screen space position and focus on the work of other free.

**Comment by mdtauk** [comment]
When WinUI 3 is out, all the updates and controls from WinUI 2's modern branches will be merged back in

**Comment by YuliKl** [comment]
Thank you, @mdtauk. NavigationView has been updated to match our internal designers' work with #4009. Closing this proposal.
