### ISSUE TITLE
[Feature Request] Enable copying control templates in Visual Studio/Blend

### ISSUE THREAD

**Issue by jebishopms** [Microsoft/microsoft-ui-xaml#4]
Beginning with WinUI NuGet package version 2.0.181011001, right clicking a control and selecting Edit Template -> Edit a Copy isn't enabled.

**Comment by jevansaks** [comment]
With the latest nuget and VS 15.9 Preview this should be resolved.

**Comment by touseefbsb** [comment]
what about the stable version of VS? i.e 15.8.7 ?

**Comment by jevansaks** [comment]
Unfortunately not, the VS team says that it was fixed on their side only in 15.9. Sorry!

**Comment by danielvistisen** [comment]
Can you document the templates while we wait for that release? So we can C/P the xaml.

**Comment by jevansaks** [comment]
Visual Studio 15.9 is live (you can update to it today) and this is working end-to-end there. But if you can't update yet then it's in the nuget package. You can find it unpacked on your local machine here:
```
%userprofile%\.nuget\packages\microsoft.ui.xaml\2.0.181018003\lib\uap10.0\Microsoft.UI.Xaml\Themes\Generic.xaml
````

**Comment by touseefbsb** [comment]
may I suggest that this path of Generic.xaml if documented on ReadMe would
be extremely helpful :)
