### ISSUE TITLE
ItemsRepeater performs bad when scrolling fast on Xbox

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#4002]
**Describe the bug**

**Steps to reproduce the bug**

I have attached a reproduced repo, please run it on Xbox one S/X, Xbox Series S/X still not good.
**Bug1, On Xbox, press and hold GamepadDPadDown/GamepadDPadUp, the focus moves quickly to the bottom and top, then the focus may be lost, and the UI update very slow.**

Press GamepadDPadDown every second, the focus can focus next element, and ui update nearly fine.
https://user-images.githubusercontent.com/14960168/105456679-8df43480-5cc0-11eb-8686-5d504810474e.mp4

Press and hold GamepadDPadDown, the focus may be lost, and auto-scroll to top.
https://user-images.githubusercontent.com/14960168/105456710-977d9c80-5cc0-11eb-816f-c1b4fbc9ac71.mp4

Even on my pc(i7 8th, 16GB) still happens.

**Bug2, The focus jumps randomly when scrolling up/down.**

For example, the current focus is B1, press GamepadDPadDown, the focus jumps to C1 in most cases. But it may be also jump to C2 or C3 or C4, or C last.

![image](https://user-images.githubusercontent.com/14960168/105456170-a9127480-5cbf-11eb-97d7-d3b1dc8aab65.png)

**Expected behavior**
On Xbox and PC, the focus should always show, and scroll up/down, UI update smoothly.

**Screenshots**

**Version Info**
OS: Xbox one s 19041.5496

NuGet package version: 
[Microsoft.UI.Xaml 2.4.3]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | < Yes>   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               | < Yes |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

I paste this repo to confirm, whether it's my code problem or the `ItemsRepeater` can hold massive data.

Sample repo, see [https://github.com/hupo376787/TestRepeater.git](https://github.com/hupo376787/TestRepeater.git), you can run it on Xbox to reproduce.

**Comment by hupo376787** [comment]
For now, I have to use the delay method to stop users scrolling too fast.
I know this is not a good solution, can you provide any other solution, thanks.
![image](https://user-images.githubusercontent.com/14960168/105461767-9e101200-5cc8-11eb-8c75-55d4c1a2817e.png)

**Comment by chingucoding** [comment]
Have you tried setting [VerticalCacheLength](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.itemsrepeater.verticalcachelength?view=winui-2.5) to a higher value (e.g. 2 or 3)? This could potentially improve scrolling performance as the virtualization area get's larger and thus more items would be available to scroll to without having to recycle elements.

**Comment by JohnnyWestlake** [comment]
That still won't fix the root issue - it's worth noting that ListViewBase internally handles its own focusing logic to avoid this sort of issue and to vastly improve the performance on focus logic. As ItemsRepeater isn't a direct replacement for ListViewBase but a lower-level alternative, you would probably have to roll your own focusing logic based on the known layout of items to handle this. (And for performance reasons, you would want to try and around asking the FocusManager for the next element which can be a performance bottleneck on Xbox, and explicitly give in the next one instead).

**Comment by chingucoding** [comment]
Yes, VerticalCacheLength won't fix focus issues, however it can (and most of the time does) fix issues with stuttering when scrolling. From the videos, it looks like that the ItemsRepeater is not able to get the next elements in time which then confuses the focus logic resulting in that weird behavior.

**Comment by hupo376787** [comment]
I'll try setting `VerticalCacheLength` tomorrow on my Xbox one s.

And for focusing logic, I once wrote my own to override FocusManager's logic, the same happens if I press and hold GamepadDPadDown.

**Comment by JohnnyWestlake** [comment]
For rolling your own focusing logic, the general idea is you know the exact layout of items (especially on Xbox where you have a fixed layout), so you would explicitly call something like 
```
int nextIndex = WorkOutNextItemForDirection();
((Control)myRepeater.GetOrCreateElement(nextIndex )).Focus(FocusState.Programmatic);
``` 
on GamepadButtonDown, and handle the original event to stop FocusManager doing it itself. This would realise and focus the element. Setting VerticalCacheLength typically just delays the inevitable (and, especially on something like an Xbox One S which is very CPU constrained, greatly effects performance of page navigations) rather than properly handling the issue.

At this point the focus shouldn't be going anywhere because you're expictly stopping FocusManager from doing it automatically.

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by hupo376787** [comment]
Hi, guys, I have changed the focusing method as @JohnnyWestlake said.
The new repo is [https://github.com/hupo376787/TestRepeaterWithCustomFocus.git](https://github.com/hupo376787/TestRepeaterWithCustomFocus.git).

But it still has problems when press and hold up/down button.

The key code like:
```
                                var grid = VerticalRepeater.TryGetElement(riverIndex) as Grid;
                                if(grid != null)
                                {
                                    grid.StartBringIntoView();
                                    var horizontalRepeater = TreeHelper.FindVisualChild<ItemsRepeater>(grid);
                                    if (horizontalRepeater != null)
                                    {
                                        horizontalRepeater.UpdateLayout();
                                        var lastFocusedItem = horizontalRepeater.GetOrCreateElement(listIndexes[riverIndex]);
                                        var button = TreeHelper.FindVisualChild<Button>(lastFocusedItem);
                                        if (button != null)
                                        {
                                            button.Focus(FocusState.Programmatic);
                                            button.StartBringIntoView();

                                            canTap = true;
                                            e.Handled = true;
                                        }
                                    }
                                }
```

**Comment by hupo376787** [comment]
Hi, guys. Any ideas? Thanks.

**Comment by hupo376787** [comment]
Closing as no one uses it.
