### ISSUE TITLE
Question: where is System.Media and SystemSounds?

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#4007]
Using WinUI 3 preview and VS preview , I created a project with the "Class Library (WinUI in Desktop)" template and tried to access SystemSounds. But, there does not seem to be any System.Media namespace linked in. For example on the using statement, intellisense did not find Media as a namespace within System. What package do I need to include?

**Comment by StephenLPeters** [comment]
@Austin-Lamb  or maybe @alwu-msft fyi

**Comment by sjb-sjb** [comment]
Another similar question, again in a "Class Library (WInUI in Desktop)" project: 

I have "using Microsoft.UI.Xaml.Input" and the compiler allows the use of the KeyboardAccelerator class; however the ICommand interface is not found. I get CS0246, the type is not found. Yet the [docs](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.input.icommand?view=winui-3.0-preview) clearly say it is in Microsoft.UI.Xaml.Input. Again, it looks like I am missing a library or NuGet package, but which one? 

What am I missing? Also curious how am I supposed to figure out what package is missing --

**Comment by sjb-sjb** [comment]
Maybe ICommand was not moved from System.Windows.Input to Microsoft.UI.Xaml.Input as the documents claim it was -- ? 

Still missing SystemSounds.

**Comment by huoyaoyuan** [comment]
See the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.media.systemsound?view=dotnet-plat-ext-5.0): it's available as platform extension in .NET Core.

You can add the nuget package [System.Windows.Extensions](https://www.nuget.org/packages/System.Windows.Extensions/).

**Comment by sjb-sjb** [comment]
Hmmm, RTFM ... OK so what I take from this is that if the Version dropdown on the class documentation says .NET Platform Extensions 5.0 then I should load the NuGet package whose name matches the DLL shown next to "Assembly". Easy as pie. 

Seems to all be linking now. Admittedly I did also upgrade VS, install a new .NET 5 version, and update the projects to 19041 (the templates seem to put in 18362).

**Comment by marb2000** [comment]
@sjb-sjb did you solved the issue? If so, can you close this issue, please?

**Comment by sjb-sjb** [comment]
See also #4065.
Thanks for all the help!
