### ISSUE TITLE
Question: Is reveal possible to return?

### ISSUE THREAD

**Issue by Shomnipotence** [microsoft/microsoft-ui-xaml#4011]
I love reveal effect, I think this is one of the souls of Fluent Design (the other is acrylic). I noticed that the new design no longer has reveal, is it possible to return?

![image](https://user-images.githubusercontent.com/6630660/105574416-5f995680-5d9f-11eb-9023-3d91e49179ec.png)
![image](https://user-images.githubusercontent.com/6630660/105574420-6627ce00-5d9f-11eb-8a6e-c6c299fe37c9.png)

**Comment by mdtauk** [comment]
@chigy had said they were not happy with Reveal and are adding animations to controls to meet the same goal of indicating interactive controls on hover.

There was a proposal that was discussing possible changes, but it seemed to not go anywhere
https://github.com/microsoft/microsoft-ui-xaml/issues/1126

They may be open to future ideas, but are not actively working on a replacement for now.

```
@chigy we are going away with reveal effect. With the new styles of visuals, reveal just does not work as an effective visual effect to express interaction. We are looking into micro-animations or other types effects (you might have seen in some other controls we are working on) to ensure controls get the interaction communicated. That said, I would say, consider this as we are halting on reveal. We may find a good use for it in the future (or not...). We just haven't found effective one at the moment...
```

```
We try to be thoughtful on adding effects or visual feedback and be systematic about it. We are currently busy with the visual refresh this is not something we are focused on at the time.
```

**Comment by AJLeuer** [comment]
Please don't get rid of it. WinUI on the desktop is in desperate need of any kind of visual flourish it can get - it looks barren and lifeless as it is. And it appears as though the acrylic material isn't available in desktop apps as well. If that's the case, that's again a real shame, for the same reason.

**Comment by Jaiganeshkumaran** [comment]
Microsoft got rid of Reveal because it's hard to implement on their websites efficiently and users do except a similar look across platforms.
