### ISSUE TITLE
Question: ListBoxItem common visual states

### ISSUE THREAD

**Issue by zed220** [microsoft/microsoft-ui-xaml#4015]
Hello,

What common visual states support the ListBoxItem in ListBox?

I have found in the ListBoxItem template the following states: Normal, Disabled, PointerOver, Pressed, Selected, SelectedUnfocused, Focused, SelectedPointerOver, SelectedPressed. Are these all visual states?

Thanks

**Comment by StephenLPeters** [comment]
Yes, these are visual states.  A control only supports states which are present in its template, so if your looking at the template that is an exhaustive list.  Also, we do encourage people to use ListView instead of ListBox where possible.
