### ISSUE TITLE
Add colored acrylic theme resources

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#4016]
# Add accent-colored acrylic theme resources

## Summary

Add new AcrylicBrush theme resources for showing accent-colored acrylics and overlays. Related to #3478. 

## Proposed changes

1. Add new theme resources

1.1 Create `AccentAcrylicBackgroundFillColorDefaultBrush` using the following properties.

  | TintColor | TintOpacity | TintLuminosityOpacity | FallbackColor | BackgroundSource
-- | -- | -- | -- | -- | --
Light theme | Accent Light 3 | 0.8 | 0.8 | Accent Light 3 | HostBackdrop
Dark theme | Accent Dark 1 | 0.8 | 0.8 | Accent Dark 1 | HostBackdrop

1.2 Create `AccentAcrylicBackgroundFillColorBaseBrush` using the following properties.

  | TintColor | TintOpacity | TintLuminosityOpacity | FallbackColor | BackgroundSource
-- | -- | -- | -- | -- | --
Light theme | Accent Light 2 | 0.8 | 0.8 | Accent Light 2 | HostBackdrop
Dark theme | Accent Dark 2 | 0.8 | 0.8 | Accent Dark 2 | HostBackdrop

1.3 Create a new SolidColorBrush named `AccentLayerFillColorDefaultBrush`

  | Fill color | Opacity
-- | -- | --
Light theme | Accent Light 3 | 0.25
Dark theme | Accent Dark 1 | 0.25

## Down-level behavior
The updated values described above rely on the TintLuminocityOpacity property, which was added in 19H1. Therefore, for the RS2 dictionary, we'll need to provide alternative values for these AcrylicBrush resources. At 80%, the TintOpacity should be enough to provide adequate contrast, so simply dropping the TintLuminocityOpacity values should work fine.

Proposed RS2 alternative values:
```xaml
<!-- Light theme -->
        <muxm:AcrylicBrush x:Key="AccentAcrylicBackgroundFillColorDefaultBrush" TintColor="{ThemeResource AccentLight3}" TintOpacity="0.8" FallbackColor="{ThemeResource AccentLight3}" BackgroundSource="HostBackdrop"/>
        <muxm:AcrylicBrush x:Key="AccentAcrylicBackgroundFillColorBaseBrush" TintColor="{ThemeResource AccentLight2}" TintOpacity="0.8" FallbackColor="{ThemeResource AccentLight2}" BackgroundSource="HostBackdrop"/>

<!-- Dark theme -->
        <muxm:AcrylicBrush x:Key="AccentAcrylicBackgroundFillColorDefaultBrush" TintColor="{ThemeResource AccentDark1}" TintOpacity="0.8" FallbackColor="{ThemeResource AccentDark1}" BackgroundSource="HostBackdrop"/>
        <muxm:AcrylicBrush x:Key="AccentAcrylicBackgroundFillColorBaseBrush" TintColor="{ThemeResource AccentDark2}" TintOpacity="0.8" FallbackColor="{ThemeResource AccentDark2}" BackgroundSource="HostBackdrop"/>
```

**Comment by chingucoding** [comment]
I'll work on this.
