### ISSUE TITLE
ToggleSplitButton's "On" state looks wrong while its flyout is open

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#4019]
**Describe the bug**

Opening a ToggleSplitButton's flyout causes the button to "grey-out", looking like it's in the Off state.

**Steps to reproduce the bug**

1. Open ToggleSplitButton page in Xaml Controls Gallery
2. Make sure the ToggleSplitButton is On, painted with accent color.
![image](https://user-images.githubusercontent.com/13142665/105752653-6a1d3280-5efc-11eb-8416-931beb0f08d4.png)
3. Press the secondary chevron button to open ToggleSplitButton's flyout.
4. Note that the ToggleSplitButton becomes grey instead of blue.
![image](https://user-images.githubusercontent.com/13142665/105752821-9df85800-5efc-11eb-81f0-45dd6906ca20.png)

**Expected behavior**

ToggleSplitButton continues to look On (so shows accent color)

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.5
Issue repros in Xaml Controls Gallery 1.2.17.0

**Comment by chingucoding** [comment]
I would like to take a look at this.
