### ISSUE TITLE
Question: Type of DataPackagePropertySetView.Thumbnail

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#4020]
Is there a reason why `DataPackagePropertySetView.Thumbnail` property in UWP is a `RandomAccessStreamReference` instead of `IRandomAccessStreamReference`? Other similar properties in the same type have use `IRandomAccessStreamReference` instead and the `Thumbnail` property of `DataPackagePropertySet` uses `IRandomAccessStreamReference` as well. Is this just an oversight?

**Comment by StephenLPeters** [comment]
@MikeHillberg This isn't Winui but do you happen to know? @jeffStall is this a ProjectReunion issue?

**Comment by jeffstall** [comment]
@MartinZikmund , can you specify the full type names for the members that you are talking about? For instance, if it is in the Windows.* namespace, this would be an OS design issue that can't really change. If it is in the Microsoft.* namespace, then we can pass this along as a potential fix that could be made.

**Comment by MartinZikmund** [comment]
This is in the `Windows.ApplicationModel.DataTransfer`. I was mainly curious if there was some reason behind it, or an accidental type mismatch, as I was porting the typ to Uno Platform and noticed this difference

**Comment by MikeHillberg** [comment]
The cases where the class is used look like accidents. Everything should be the [IRandomAccessStreamReference](https://docs.microsoft.com/uwp/api/Windows.Storage.Streams.IRandomAccessStreamReference) interface, and [RandomAccessStreamReference](https://docs.microsoft.com/uwp/api/Windows.Storage.Streams.RandomAccessStreamReference) is a helper class that provides some standard implementations. But it shouldn't be an exchange type.

Fortunately in the case of [DataPackagePropertySetView.Thumbnail](https://docs.microsoft.com/uwp/api/Windows.ApplicationModel.DataTransfer.DataPackagePropertySetView.Thumbnail) it's an output type and so harmless. But there are other places where unfortunately it's a input type.
