### ISSUE TITLE
UniformGridLayout sometimes leaves holes in the layout

### ISSUE THREAD

**Issue by micahl** [Microsoft/microsoft-ui-xaml#403]
**Describe the bug**

Using an ItemsRepeater with the UniformGridLayout and scrolling through a large list or resizing the content sometimes a hole will appear where an item should be.  For example, in the screenshot below Item #2838 is missing.

**Steps to reproduce the bug**

Created a dummy app with the markup below and tried scrolling through the content and resizing the window.  

```XAML
    <ScrollViewer>
        <mux:ItemsRepeater x:Name="repeater">
            <mux:ItemsRepeater.Layout>
                <mux:UniformGridLayout ItemsJustification="Start"
                                       ItemsStretch="Fill"
                                       Orientation="Horizontal"
                                       MinRowSpacing="12"
                                       MinColumnSpacing="8"/>
            </mux:ItemsRepeater.Layout>
            <DataTemplate x:DataType="x:String">
                <Grid Background="LightBlue" MinWidth="160" MinHeight="96">
                    <TextBlock Text="{x:Bind}" x:Phase="1"/>
                </Grid>
            </DataTemplate>
        </mux:ItemsRepeater>
    </ScrollViewer>
```

**Expected behavior**

Items that should appear are visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/1009123/54063175-b3a4ed00-41bf-11e9-8a80-663bf7620a84.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml.2.1.190218001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes  |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by MilesChing** [comment]
It seems that this problem still exists when you limit the number of items per row simply by setting `MaximumRowsOrColumns`.

**Comment by ranjeshj** [comment]
@MilesChing can you please open a new issue with a repro ?
