### ISSUE TITLE
Proposal: Round(ed) Button

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#4032]
# Proposal: Round(ed) Button

## Summary

![image](https://user-images.githubusercontent.com/7389110/105944523-6227d480-605b-11eb-9875-e5b6c3f7314a.png)

This would be a button which overrides it's ``CornerRadius`` value to always create a rounded "pill" like appearance

## Rationale

* Based on Button, except the CornerRadius is determined to always be half the height of the button as rendered
* Minimum width matches the height making the Button appear as a circle. (like an Icon only Button for instance)

## Scope

| Capability | Priority |
| :---------- | :------- |
| CornerRadius is handled by the control, and not discreetly | Must |
| Include Accent and Subtle style variants | Should |
| RepeatButton and ToggleButton variants | Could |
| There could be scope for DropDown and SplitButton variants | Could |

## Important Notes

As content changes for buttons, if text is wrapped or font sizes changed, just using styles or CornerRadius values will not work, so this is why I am proposing something more than just including styles.

![image](https://user-images.githubusercontent.com/7389110/105946473-40305100-605f-11eb-8b6a-db289509135b.png)

## Open Questions

Could this perhaps be added as a property on the ButtonBase control when the source is opened, to remove the need to duplicate or derive these controls?

**Comment by huoyaoyuan** [comment]
> Could this perhaps be added as a property on the ButtonBase control when the source is opened, to remove the need to duplicate or derive these controls?

It definitely should. Creating new control for this is opposed to the spirit of xaml that don't create new controls for duplicated functionality with just styling.



> just using styles or CornerRadius values will not work

Styling system should be improved to make that possible.

**Comment by mdtauk** [comment]
> > Could this perhaps be added as a property on the ButtonBase control when the source is opened, to remove the need to duplicate or derive these controls?
> 
> It definitely should. Creating new control for this is opposed to the spirit of xaml that don't create new controls for duplicated functionality with just styling.
> 
Yea the idea of duplicating or even just Deriving new controls for one behaviour change feels bad to me in general.  Ideally there would be a property which would override the CornerRadius which updates anytime the control's content updates, or rendering size changes.  Could be as simple as an ``IsRounded`` or ``IsCircle``

> > just using styles or CornerRadius values will not work
> 
> Styling system should be improved to make that possible.
>
The styles can set the CornerRadius, however styles do not compute their values, and so if the content changes, these set values do not adapt - you would have to write code to update the values.

**Comment by huoyaoyuan** [comment]
> and so if the content changes, these set values do not adapt - you would have to write code to update the values.

I've met other issues that requires updatable binding to ActualSize. This could be the point to improve.

**Comment by niels9001** [comment]
+1 for this ask.

This style is also coming back a lot with Windows 10X and even the new News & Weather UX, so it would be nice to have a default style / control for it.

![image](https://user-images.githubusercontent.com/9866362/105988462-f025ae80-609f-11eb-9739-e70e086e32ee.png)

**Comment by Shomnipotence** [comment]
My God，NOOOOOO@@！！！！

**Comment by SeanLedbetter** [comment]
Overly rounded buttons seem like a bad design choice to me. Right now, Google has them all over the place. I wouldn't say Google is the best at design. I don't know why overly rounded buttons seem so out of place... maybe it's because they are not form fitting to the content area or the squared screen they are displayed on. Also, it reminds me of the pill toggle when Windows 10 first came out. Does anyone remember the pill toggle? I had almost forgotten.
![windows-10-turn-off-window-animations](https://user-images.githubusercontent.com/34668006/106348087-22decb00-6289-11eb-918e-8efe6ef2a16c.png)

**Comment by chigy** [comment]
@mdtauk , Thank you for your proposal! We reviewed your input and we do not believe we want to pursue with this proposal for the following reasons: 1) it is easy to do this with existing functionality, 2) the real ask here seems to dynamically change the corner radius to some percentage of a button and maintain its appropriate roundness. However we do not believe there is enough need for us to consider introducing such capability today.
