### ISSUE TITLE
System.ArgumentOutOfRangeException: 'Not a valid Win32 FileTime.' for formatting default DateTimeOffset value

### ISSUE THREAD

**Issue by ssaran046** [microsoft/microsoft-ui-xaml#4033]
**Describe the bug**

In WinUI Desktop, ArgumentOutOfRangeException is thrown when formatting the default value of DateTimeOffset. Please find the code details below,

DateTimeOffset date = new DateTimeOffset();
DateTimeFormatter formatter = new  DateTimeFormatter("month");
string monthName = formatter.Format(date);

**Steps to reproduce the bug**

Run the sample with the below code,

DateTimeOffset date = new DateTimeOffset();
DateTimeFormatter formatter = new  DateTimeFormatter("month");
string monthName = formatter.Format(date);

**Expected behavior**

`monthName` has value like January, February.

**Screenshots**

NA

**Version Info**

NuGet package version: [Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by huoyaoyuan** [comment]
Related: #3889

**Comment by StephenLPeters** [comment]
Agreed.
