### ISSUE TITLE
Exception is thrown when performing touch interaction on ColorSpectrum control

### ISSUE THREAD

**Issue by ssaran046** [microsoft/microsoft-ui-xaml#4036]
**Describe the bug**

Below Exception is thrown when performing touch interaction on ColorSpectrum control or window that contains ColorSpectrum control and close the window.

Exception thrown at 0x7770B373 (ntdll.dll) in App2.exe: 0xC0000005: Access violation writing location 0x00000014.

_Sample_: [ColorSpectrumException.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5879611/ColorSpectrumException.zip)

**Steps to reproduce the bug**

1. Run the sample
2. Perform touch interaction on ColorSpectrum control or any area of the window.
3. Now, close the window then the exception is thrown

**Expected behavior**

The exception is must not be thrown.

**Screenshots**

NA

**Version Info**

NuGet package version: [Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ssaran046 do you know if this issue is exclusive to Winui3 or if it reproduces with winui2 as well?

**Comment by ssaran046** [comment]
@StephenLPeters not sure about winui2

**Comment by codendone** [comment]
I don't repro this in Preview 4 or the more recent Reunion 0.5 Preview.
