### ISSUE TITLE
Application crashes on start with 0xC0000602

### ISSUE THREAD

**Issue by JacqueSatan** [microsoft/microsoft-ui-xaml#4045]
**Describe the bug**

Hello, I am trying to execute/debug my WinUI 3 app. It does compile, but the following error appears instantly when I try to run the app:

    Unhandled exception at 0x00007FFAB70351F9 (combase.dll) in WinUITest.exe : 0xC0000602:  A FailFast exception has occurred. The exception handlers will not be called and the process will end immediately.

The code shown by Visual Studio 2019 is Microsoft.Xaml.UI.h:260
```cpp
template <typename D> WINRT_IMPL_AUTO(void) consume_Microsoft_UI_Xaml_IApplicationStatics<D>::Start(Microsoft::UI::Xaml::ApplicationInitializationCallback const& callback) const
{
    check_hresult(WINRT_IMPL_SHIM(Microsoft::UI::Xaml::IApplicationStatics)->Start(*(void**)(&callback)));
}
```
**Steps to reproduce the bug**

([Follow these steps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop#create-a-winui-3-desktop-app-for-cwin32))
1. Create a C++ WinUI app for dekstop
2. Compile
3. Run

**Expected behavior**
I expect my app not to crash.
**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.Windows.CppWinRT 2.0.210122.3]
[Microsoft.WinUI 3.0.0-preview3.201113.0]
Microsoft Visual Studio 16.9 Preview

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21292.1010)              | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by huoyaoyuan** [comment]
Duplicate of #3954 and #4023

**Comment by JacqueSatan** [comment]
thanks ans sorry for disturbing
