### ISSUE TITLE
ComboBox text color issue

### ISSUE THREAD

**Issue by beervoley** [microsoft/microsoft-ui-xaml#4047]
**Describe the bug**

Wrong default text color displaying in Dark mode in editable combobox. It's displaying TextFillColorSecondaryBrush (placeholder color) instead of Primary text brush. If a color (that's not just black or white, red for example) is set, then it's being displayed properly.
On top of that, when we switch back from Dark Mode to Light Mode - that Secondary text color stays unchanged and persists in Light mode as well. (doesn't appear in Light Mode alone).

The change to ComboBox colors came in [this PR](https://github.com/microsoft/microsoft-ui-xaml/pull/3938).
**Steps to reproduce the bug**

1. Create Editable Combobox.
2. Switch to Dark Mode.
3. Input some text and observer the text color.
4. Switch back to Light mode and observer the same color.

**Expected behavior**

Editable ComboBox user input text (not placeholder) should be TextFillColorPrimaryBrush in both Themes.

**Screenshots**

That's the wrong color being displayed in Dark Mode:
![image](https://user-images.githubusercontent.com/21356912/106191272-8076f880-615f-11eb-811e-f91294c60019.png)
And that's the same color persisting when switching back to Light Mode:
![image](https://user-images.githubusercontent.com/21356912/106191313-8f5dab00-615f-11eb-8b27-a83d15db1c5a.png)

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop             | Yes

**Comment by beervoley** [comment]
This only happens if the color set for focused state of the textbox is a shade of grey. 
![image](https://user-images.githubusercontent.com/21356912/106221477-8e923c80-6192-11eb-9bdd-5e8fac9a18ce.png)
ContentElement.Foreground is what controls the color.

I'm not sure why that happens and by setting the focused color on ContentElement itself (as property when defining) seems to do the trick.

**Comment by ranjeshj** [comment]
This has been resolved in the latest pre-release.
