### ISSUE TITLE
Discussion: We should talk about color

### ISSUE THREAD

**Issue by lorisobi** [microsoft/microsoft-ui-xaml#4051]
![image](https://user-images.githubusercontent.com/28399150/106232867-5f60e700-61f5-11eb-8987-c7d0c13085cd.png)
The Fluent Web UI uses colors for many elements and sometimes even for buttons and flyouts which is a bit inconsistent.
With the new proposed WinUI style color isn't implemented that well. We should discuss, whether we use (accent) colors to signalize something (Importance or Selection). Below I added one Image showing a concept I made some weeks ago for and NavView Flyout (I used colors to signalize which menus are selected) and an image how MS is using color in their new Clock app for the primary buttons.

![image](https://user-images.githubusercontent.com/28399150/106232812-38a2b080-61f5-11eb-90be-47e45aea90b3.png)
![image](https://user-images.githubusercontent.com/28399150/106233123-11001800-61f6-11eb-907a-adb441a986ba.png)

**Comment by chigy** [comment]
@lorisobi , thank you for your feedback. We currently have no near future plans to revisit colors outside of the effort we currently are focused on. Also, this item is not actionable as is and would be helped if you turned it into a very specific request with supporting data how that solves the concern you have.
