### ISSUE TITLE
Not able to use the Microsoft.Toolkit.Uwp.Notifications package in win ui 3 preview

### ISSUE THREAD

**Issue by MoueenShaik** [microsoft/microsoft-ui-xaml#4054]
**Requirement**: I want the implement windows toast messages in WINUI3 application,
 For this requirement, I am using Microsoft.Toolkit.Uwp.Notifications package, But unfortunately after adding this package I am getting below error's 

**Error	CS0433	The type 'ToastNotification' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.18362.6, Culture=neutral, PublicKeyToken=null' and 'Windows.Foundation.UniversalApiContract, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'**

Below is the code I am trying to use to show the toast notifications in WINUI 3 
Followed below articles to implement :
https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotificationmanager?view=winrt-19041
https://stackoverflow.com/questions/58136119/windows-action-center-toast-activation

.

// Construct the visuals of the toast (using Notifications library)
ToastContent toastContent = new ToastContentBuilder()
    .AddToastActivationInfo("action=viewConversation&conversationId=5", ToastActivationType.Foreground)
    .AddText("Hello world!")
    .GetToastContent();
// And create the toast notification
var toast = new ToastNotification(toastContent.GetXml());
// And then show it
DesktopNotificationManagerCompat.CreateToastNotifier().Show(toast);

Visual Studio version: Version 16.7.0 Preview 2.0
.Net Sdk : Microsoft .Net SDK 5.0.100-preview.5.20279.10(X86)

Please find below screenshots for more details.

![image](https://user-images.githubusercontent.com/47388795/106239459-7ed91f00-61b7-11eb-9fa0-f148fd75ae52.png)
![image](https://user-images.githubusercontent.com/47388795/106239878-2e15f600-61b8-11eb-9700-8ac4dcdfade6.png)
![image](https://user-images.githubusercontent.com/47388795/106240151-a11f6c80-61b8-11eb-931c-65ea583b2850.png)
![image](https://user-images.githubusercontent.com/47388795/106240295-e5ab0800-61b8-11eb-8d25-937a7f1fe8a2.png)
![image](https://user-images.githubusercontent.com/47388795/106239989-5d2c6780-61b8-11eb-9cc9-067cc4c68be3.png)

Please suggest me if I miss something and let me know if you need any other details from my end.

Thanks & regards,
Moueen Shaik

**Comment by huoyaoyuan** [comment]
From which channel are you using WCTK, 7.0 or 8.0?
Only 8.0 supports WinUI 3, and it is published into another feed other than nuget.org. See https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3295.

**Comment by michael-hawker** [comment]
FYI @andrewleader

@MoueenShaik WinUI 3 Desktop works on .NET 5, we had an issue with our Notifications package not being supported on .NET 5 yet, we have fix now in our main [PR here](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/3622).

Not sure if there's more to do to have that support WinUI 3 or if it should work directly? @azchohfi?

You can get info about running our preview bits [in our wiki here](https://github.com/windows-toolkit/WindowsCommunityToolkit/wiki/Preview-Packages), the pr reference will already be in our 'MainLatest' feed.

**Comment by andrewleader** [comment]
Yep .NET 5 is only supported in the [latest preview bits](https://github.com/windows-toolkit/WindowsCommunityToolkit/wiki/Preview-Packages) (the NuGet 7.0.0-preview4 doesn't have .NET 5 support yet either). Could you try that out @MoueenShaik and let us know if it works? You'll also be able to use the new style of sending toast notifications: [See the new preview docs](https://docstaging.z5.web.core.windows.net/aleader/toolkit-7/design/shell/tiles-and-notifications/send-local-toast.html?tabs=uwp)

```csharp
// New simplified API - Just call Show
new ToastContentBuilder()
    .AddArgument("action", "viewConversation")
    .AddArgument("conversationId", 9813)
    .AddText("Andrew sent you a picture")
    .AddText("Check this out, The Enchantments in Washington!")
    .Show();
```

I appreciate any feedback on the new preview, the new API, and the new docs, let us know if you have any problems!

**Comment by azchohfi** [comment]
@michael-hawker I've ported the notifications library to WinUI3 on our WinUI3 branch of the toolkit. There needs to be more testing, but the port was, apparently, successful.
