### ISSUE TITLE
How to change the Window Icon in WinUI Desktop

### ISSUE THREAD

**Issue by Berkunath** [microsoft/microsoft-ui-xaml#4056]
**How to change the Window Icon in WinUI Desktop**
I have WinUI Desktop application and I would like to change the Window Icon which displayed at top left corner of the Window. I could not find any Icon property in Window to change the icon.

**Expected behavior**
Option to change the Window Icon

**Screenshots**
![image](https://user-images.githubusercontent.com/74045266/106248242-b935d100-6236-11eb-937b-ed5c0639e1ee.png)

NuGet package version:
[Microsoft.WinUI 3.0.0-preview3.201113.0]

**Comment by StephenLPeters** [comment]
@pratikone Do you know if there is an API for this? @marb2000 and @Austin-Lamb FYI

**Comment by mdtauk** [comment]
Not sure if it's implemented or just in the spec, but doesn't the new ``Window`` element have an icon property you set?

**Comment by marb2000** [comment]
Unfortunately, the Icon property wasn't added, so you should use the Win32 APIs using PInvoke. This NuGet can help: 
<PackageReference Include="PInvoke.User32" Version="0.7.78" />

The code looks like:

```CS
 public MainWindow()
 {
    this.InitializeComponent();
    LoadIcon("Custom-Icon.ico");
 }
 private void LoadIcon(string iconName)
 {
      //Get the Window's HWND
      var hwnd = this.As<IWindowNative>().WindowHandle;
      IntPtr hIcon = PInvoke.User32.LoadImage(IntPtr.Zero, iconName, 
                PInvoke.User32.ImageType.IMAGE_ICON, 16, 16, PInvoke.User32.LoadImageFlags.LR_LOADFROMFILE);

    PInvoke.User32.SendMessage(hwnd, PInvoke.User32.WindowMessage.WM_SETICON, (IntPtr)0, hIcon);
 }
[ComImport]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
internal interface IWindowNative
{
    IntPtr WindowHandle { get; }
}

```
You should deploy the .ico with your app. In your csproj there should be something like:
```XML
<ItemGroup>
    <None Update="Custom-Icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup> 
```

Does this help?

**Comment by marb2000** [comment]
Closing it. Please, open it again in case the workaround doesn't work.

**Comment by billhenn** [comment]
Question for Microsoft:  An Icon property will be added at some point for this, won't it?  As a consumer of WinUI, we really shouldn't have to do complex Win32 workarounds for setting a simple thing like a Window icon that is necessary for each Window instance.  It should be as easy as pointing a property to an ImageSource.

**Comment by StephenLPeters** [comment]
Agreed! Would you like to open a feature proposal? :)

**Comment by billhenn** [comment]
> Agreed! Would you like to open a feature proposal? :)

I added this question... feel free to comment and add support:  https://github.com/microsoft/microsoft-ui-xaml/issues/4777

**Comment by abhi-msft** [comment]
@marb2000 I am on 0.8 SDK, and I am unable to use CsWin32. Any other workarounds? 
![image](https://user-images.githubusercontent.com/52011872/124531033-7fa75a00-ddc2-11eb-9ab6-64a77947cc81.png)

**Comment by Marv51** [comment]
@abhi-msft Did you add the correct namespaces for CsWin32? The most recent beta has updated all namespaces to be under `Windows.Win32`

I have updated my code above.

**Comment by abhi-msft** [comment]
@Marv51 Missed namespace changes. It worked like a charm, Thank you!

**Comment by ashish-sahu** [comment]
@Marv51 I am using 0.57 SDK version and i getting errors in namespaces.
![image](https://user-images.githubusercontent.com/2473224/127476925-e4dad4f4-60fa-44a6-84b8-88eaa8c1baa3.png)

**Comment by jmecosta** [comment]
for those using windows template studio, this for me helped: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/desktop-winui3-app-with-basic-interop

... csproj
```
<PackageReference Include="PInvoke.User32" Version="0.7.104" />

  <ItemGroup>
    <None Remove="Tekla-2021-Favicon.ico" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Tekla-2021-Favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

```

... app.xaml.cs

```
        public static Window MainWindow { get; set; } = new Window() { Title = "AppDisplayName".GetLocalized() };

        public App()
        {
            this.InitializeComponent();
            this.LoadIcon("Tekla-2021-Favicon.ico");
        }
....

        private void LoadIcon(string iconName)
        {
            //Get the Window's HWND
            var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(MainWindow);
            var hIcon = PInvoke.User32.LoadImage(System.IntPtr.Zero, iconName,
                      PInvoke.User32.ImageType.IMAGE_ICON, 16, 16, PInvoke.User32.LoadImageFlags.LR_LOADFROMFILE);

            PInvoke.User32.SendMessage(hwnd, PInvoke.User32.WindowMessage.WM_SETICON, (System.IntPtr)0, hIcon);
        }
```

**Comment by Slion** [comment]
Using [CsWin32](https://github.com/microsoft/CsWin32) I got the following:

```C#

    public sealed partial class MainWindow : Microsoft.UI.Xaml.Window
    {
    …
        // Handle needs to stay alive as long as this window
        Microsoft.Win32.SafeHandles.SafeFileHandle iIcon;

        private void LoadIcon(string aIconName)
        {
            // Resolve icon path
            string iconPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, aIconName);
            // Get window handle
            var hwnd = new Windows.Win32.Foundation.HWND(WinRT.Interop.WindowNative.GetWindowHandle(this));
            // Load our image
            iIcon = PInvoke.LoadImage(null, iconPath, Windows.Win32.UI.WindowsAndMessaging.GDI_IMAGE_TYPE.IMAGE_ICON, 16, 16, Windows.Win32.UI.WindowsAndMessaging.IMAGE_FLAGS.LR_LOADFROMFILE);
            //Set our icon
            PInvoke.SendMessage(hwnd, PInvoke.WM_SETICON, new Windows.Win32.Foundation.WPARAM(0), new Windows.Win32.Foundation.LPARAM(iIcon.DangerousGetHandle()));
        }
    …
    }
```

**Comment by taoyouh** [comment]
Update: now you can do this with the `AppWindow` class.

**Comment by eerhardt** [comment]
> Update: now you can do this with the AppWindow class.

@taoyouh - I can't seem to find the `AppWindow` class. Can you add a link to it?

**Comment by taoyouh** [comment]
@eerhardt The document is in https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow?view=windows-app-sdk-1.0

Sample code: 
MainWindow.xaml.cs
```
            IntPtr windowHandle = WinRT.Interop.WindowNative.GetWindowHandle(this);
            WindowId windowId = Win32Interop.GetWindowIdFromWindow(windowHandle);
            var appWindow = AppWindow.GetFromWindowId(windowId);
            appWindow.SetIcon(Path.Combine(Package.Current.InstalledLocation.Path, "Icon.ico"));
```

**Comment by dojo90** [comment]
Is there also a way to load the icon from an EmbeddedResource?
I find it very unpleasant that I have to put the icon in my program directory.

**Comment by IM-001** [comment]
I do it like this, to be verified how it will behave it a deployed app, but it's quite straightforward:

`public MainWindow()
{
    this.InitializeComponent();

    this.Title = "My Super WinUI 3 App";
    this.AppWindow.SetIcon("Assets/MyImagePath/my_icon.ico");`
    
I think using the AppWindow class is a must for WinUi 3, you can Resize() the app window, etc.

I also set my icon in my project properties Win32 Resources and I got all my Package.appxmanifest setup done as well.

doc provided by [taoyouh](https://github.com/taoyouh):
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow?view=windows-app-sdk-1.0

**Comment by elibroftw** [comment]
For .NET apps:

```cs
        string path = AppContext.BaseDirectory;
        string iconFileName = "Assets/Icon.ico"; // Build Action Content
        string iconPath = Path.Combine(path, iconFileName);
        AppWindow.SetIcon(iconPath);
```

https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow.seticon?view=windows-app-sdk-1.0#microsoft-ui-windowing-appwindow-seticon(system-string)
