### ISSUE TITLE
TreeView crashes

### ISSUE THREAD

**Issue by Hakobyan8888** [microsoft/microsoft-ui-xaml#4061]
Hell I'm trying to use TreeView control but it crashes with this error

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Cannot find a Resource with the Name/Key TabViewButtonBackground [Line: 28 Position: 10]
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at XamlTestingApp.MainPage.InitializeComponent()
   at XamlTes

To get this error just use TreeView in UWP application and it will crash the app.
Hope you will fix it)))

**Comment by StephenLPeters** [comment]
@Hakobyan8888 thanks for the report, could you please answer the questions @chingucoding to help us narrow down the issue?
