### ISSUE TITLE
WinUI 3 Preview 3 blank app does not compile out of the box on Windows 10 19042.330

### ISSUE THREAD

**Issue by riverar** [microsoft/microsoft-ui-xaml#4062]
Attempting to compile a WinUI 3 Preview 3 blank app on Windows 10 19042 with Visual Studio 2019 Preview 16.9.0 Preview 3.0 results in compilation failure.

> Error MSB3073 The command ""C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\mt.exe" -nologo -manifest "C:\Users\Rafael\.nuget\packages\microsoft.winui\3.0.0-preview3.201113.0\buildTransitive\LiftedWinRTClassRegistrationsUnpackaged.xml" "app.manifest" -out:"obj\merged.g.app.manifest"" exited with code 3.	App1	C:\Users\Rafael\.nuget\packages\microsoft.winui\3.0.0-preview3.201113.0\buildTransitive\Microsoft.WinUI.Win32Manifest.targets	34	

**Steps to reproduce**
1. Install Windows 10 19042
2. Install Visual Studio 2019 Preview, with payloads indicated in the documentation (https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-3)
3. Install WinUI 3 Preview 3 templates (https://aka.ms/winui3/preview3-download)
4. Launch Visual Studio 2019 Preview
5. Create a new app, using the WinUI 3 Preview 3 **Blank App, Packaged (WinUI in Desktop)** template
6. Click Build > Build Solution
7. Observe error

**Screenshots**
![image](https://user-images.githubusercontent.com/475132/106344799-d1224a80-6260-11eb-88d1-9e94984707b8.png)

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042) | Yes |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by stevenwdv** [comment]
I think I have the same problem; I had to adjust the `TargetFramework` in the non-package project file from `net5.0-windows10.0.18362.0` (which I do not have installed) to `net5.0-windows10.0.19041.0`

**Comment by duke7553** [comment]
I think @stevenwdv is right because it is referencing something from 18362, and installing that SDK alongside 19041 fixed the problem for me.

**Comment by riverar** [comment]
Can confirm the `TargetFramework` is `<TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>` despite having chosen different targets in the min/target framework chooser.

![image](https://user-images.githubusercontent.com/475132/106364301-d58f4780-62e2-11eb-81d1-a18f3ced13f5.png)

**Comment by StephenLPeters** [comment]
@alwu-msft is this an issue we should bring up with the VS team?

**Comment by bobasaurus** [comment]
Same problem here.  It's also throwing an unhandled exception the moment I try to build and launch a new project made with this same template.

**Comment by alwu-msft** [comment]
Thanks for the report! We will get this fixed in a future release of WinUI 3; in the meantime you can workaround this issue by either making the change mentioned in stevenwdv's [comment](https://github.com/microsoft/microsoft-ui-xaml/issues/4062#issuecomment-770203065) or manually installing the Windows 10.0.18362.0 SDK using the Visual Studio installer.

**Comment by PylotLight** [comment]
I am also having this issue with a new .net 6 project.
This was configured: <TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
despite selecting 2004 for min and max project.

**Comment by gabbybilka** [comment]
@evelynwu-msft If this is resolved (task.ms/31568265) can you close?
