### ISSUE TITLE
Question: Subscribing to an event using markup extension

### ISSUE THREAD

**Issue by TheXamlGuy** [microsoft/microsoft-ui-xaml#4067]
The latest version of WinUI introduced `IXamlServiceProvider` in the `MarkupExtension`;  a sure  miss in UWP. Unfortunately it doesn't seem to be possible to subscribe to an event with within a markup extension yet, i.e `<Button Click="{local:EventBinding OnClick}">Click Me</Button>`. Seeing that support for event subscription was introduced in WPF 4.5 - see ['Subscribing to an event using a markup extension'](https://thomaslevesque.com/2011/09/23/wpf-4-5-subscribing-to-an-event-using-a-markup-extension/), is there any chance that this is planned for WinUI?

**Comment by omikhailov** [comment]
But it would duplicate x:Bind and Behaviors, wouldn't it?

**Comment by JeanRoca** [comment]
x:Bind supports event binding already. What part of the scenario that you mentioned is not working currently?

**Comment by JeanRoca** [comment]
@TheXamlGuy do you have an update on this? The issue will be closed down by next week and marked as stale.
