### ISSUE TITLE
Crash occurs when setting custom control as flyout content 

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4069]
**Describe the bug**
I have implemented two custom control in a library project namely CustomDatePicker and CustomControl. I have defined custom control as content of flyout in custom date picker theme file. But crash occurs when running the application.
![image](https://user-images.githubusercontent.com/55440472/106444225-7af11980-64a3-11eb-874e-cf9094dd6c64.png)

Suppose if i define **empty DataTemplate in custom date picker theme file**, then application run without any crash.
![image](https://user-images.githubusercontent.com/55440472/106444419-be4b8800-64a3-11eb-92eb-02de7f722425.png)

Please find the sample provided for further details.

**Steps to reproduce the bug**
1. Run attached sample
2. Application crashes due to setting custom control as flyout content in its resource dictionary.

**Expected behavior**
The application should not crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/55440472/106443194-387b0d00-64a2-11eb-8739-286280e92940.png)

**NuGet package version:** 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

**Sample:**
[Flyout-issue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6279480/Flyout-issue.zip)

**Comment by JeanRoca** [comment]
@mageshsankar thank you for sharing this. Would you be able to verify if the crash still repros in preview 4 of WinUI 3?

**Comment by mageshsankar** [comment]
@JeanRoca the reported crash still occurs in preview 4 of WinUI 3.
