### ISSUE TITLE
UniformGridLayout doesn't virtualize when Orientation is the same direction as the scrolling direction

### ISSUE THREAD

**Issue by micahl** [Microsoft/microsoft-ui-xaml#407]
**Describe the bug**

See the markup below.  Virtualization breaks if someone sets the layout's Orientation to be "vertical" when the scrolling direction is also up/down.

**Steps to reproduce the bug**

Use the markup below in a dummy app.  Note that the default scrolling direction of ScrollViewer is up/down and the Orientation of the layout is vertical meaning the items are laid out sequentially in a vertical line and wrap when it hits the bottom.  In this scenario there won't be any wrapping because there is no "bottom" since the layout is given infinite vertical space.  But, that shouldn't prevent virtualization from kicking in.
```XAML
    <ScrollViewer>
        <mux:ItemsRepeater x:Name="repeater">
            <mux:ItemsRepeater.Layout>
                <mux:UniformGridLayout Orientation="Vertical" />
            </mux:ItemsRepeater.Layout>
            <DataTemplate x:DataType="x:String">
                <Button MinWidth="160" MinHeight="96" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
                    <TextBlock Text="{x:Bind}" x:Phase="1"/>
                </Button>
            </DataTemplate>
        </mux:ItemsRepeater>
    </ScrollViewer>
```

```C
        public MainPage()
        {
            this.InitializeComponent();

            var items = from i in Enumerable.Range(0, 1000) select $"Item {i}";
            repeater.ItemsSource = items;
        }
```

**Expected behavior**

Virtualization still works and the items are laid out vertically without any wrapping.

**Screenshots**

![image](https://user-images.githubusercontent.com/1009123/54141347-bcc1d400-43e2-11e9-90e1-48d92aa1e982.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190218001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by micahl** [comment]
I initially thought ItemsStretch should still work here, but thinking about it more I don't know that is reasonable since they're defined to stretch in the direction of layout and here it's vertical with infinite space so there isn't really any extra dead space they can stretch to fill.

**Comment by jevansaks** [comment]
So this is trying to use UniformGridLayout as a stack layout? If this is easy enough to support, then we can do it.
