### ISSUE TITLE
newbie question about opacity

### ISSUE THREAD

**Issue by oldoldman** [microsoft/microsoft-ui-xaml#4070]
I'm prototyping some kind of modal dialog as follow
```xml
<Grid>
    <Canvas x:Name="Layer1" >
        <Rectangle x:Name="Background" Width="100" Height="100" Fill="Green"/>
    </Canvas>
    <Canvas x:Name="Layer2" Opacity=".1" Background="LightGray">
        <Rectangle x:Name="ModalDialog" Canvas.Left="50" Canvas.Top="50" 
            Width="100" Height="100" Fill="Red"/>
    </Canvas>
</Grid>
```
in this xaml, Layer1 is acting as a background, no event will route to it, because it is masked by Layer2. The only imperfect is ModalDialog is not 100% red but 10% red. So is there some tricks to make it 100% red ? Many thanks!

**Comment by chingucoding** [comment]
You need to remove the opacity on the canvas "Layer2". Currently it's opacity is `.1` which is 10%. As a result of that, the canvas and it's children are partially transparent.

**Comment by oldoldman** [comment]
In your alternative solution, the green square will receive events , that's not what I want. To mask Layer1 from receiving events while keeping it visible, I have to 
1. use Layer2
2. set a non-transparent background (to receive events)
3. set opacity to less than 1(to make Layer1 visible)
It seems there is no much options to choose :)

**Comment by chingucoding** [comment]
I see, well you can just do this:

```XAML
<Grid>
    <Canvas x:Name="Layer1" >
        <Rectangle x:Name="Background" Width="100" Height="100" Fill="Green"/>
    </Canvas>
    <Canvas x:Name="Layer2" Opacity=".1" Background="LightGray"/>
    <Canvas>
        <Rectangle x:Name="ModalDialog" Canvas.Left="50" Canvas.Top="50" 
            Width="100" Height="100" Fill="Red"/>
    </Canvas>
</Grid>
```

yielding the following result:
![Image showing red and green square with red square partially overlapping the green square](https://user-images.githubusercontent.com/16122379/106490813-7da93a00-64b6-11eb-84e6-f18b02c68db8.png)

The green square won't receive events, the visual hierarchy is more clear and the red is not opaque.

**Comment by oldoldman** [comment]
I'm not sure the alternative will work. let me try.

**Comment by oldoldman** [comment]
Haha, works!

**Comment by chingucoding** [comment]
Is there anything else I can help you with? Otherwise, feel free to close this issue :)
