### ISSUE TITLE
PipsPager: The spacing between the pips in horizontal orientation is inconsistent with the vertical orientation

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#4071]
### Describe the bug
When in horizontal orientation, the width and height of the bounding box for the pips is 20px by 12px when it should be 12px by 20px.

### Steps to reproduce
View the pips in both orientations:
![image](https://user-images.githubusercontent.com/20007011/106496198-76ac0880-6471-11eb-8395-cdbc9fb9bd6d.png)
![image](https://user-images.githubusercontent.com/20007011/106496153-685dec80-6471-11eb-9eaa-ce8a745c381a.png)
The denser spacing of the pips in vertical orientation is desired.

### Solution Recommendation
Update PipsPager theme resources to allow bounding box customization in both orientations:
Rename existing theme resources to include 'Vertical' in name and create Horizontal resources as well.

| Current | Recommendation |
| :-- | :-- |
| PipsPagerButtonWidth | Rename to PipsPagerVerticalButtonWidth and add PipsPagerHorizontalButtonWidth |
| PipsPagerButtonHeight| Rename to PipsPagerVerticalButtonHeight and add PipsPagerHorizontalButtonHeight |
| PipsPagerNavigationButtonHeight | Rename to PipsPagerVerticalNavigationButtonHeight and add PipsPagerHorizontalNavigationButtonHeight
| PipsPagerNavigationButtonWidth | Rename to PipsPagerVerticalNavigationButtonWidth and add PipsPagerHorizontalNavigationButtonWidth

Two potential options for implementation:
1. Reference these new resources in the code behind when calculating pip size.
2. Create two new styles in the theme resources for horizontal and vertical orientation. Create handler in code behind to reference these styles on orientation change.

**Comment by StephenLPeters** [comment]
@beervoley fyi
