### ISSUE TITLE
CustomFlyoutPresenter style is not applied instead referring default MS FlyoutPresenter style

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4078]
**Describe the bug**
I have implemented CustomFlyoutPresenter in a library project. 

Then, i have created a custom flyout inherited from flyout base and override create presenter as like below at application level. Everything works fine, it refer the CustomFlyoutPresenter style properly.

    public class CustomFlyout : FlyoutBase
    {
        protected override Control CreatePresenter()
        {
            var customFlyoutPresenter = new CustomFlyoutPresenter();
            return customFlyoutPresenter;
        }
    }

![image](https://user-images.githubusercontent.com/55440472/106581431-b3224780-64f7-11eb-920b-1a1a6d48ace5.png)

Suppose, I create a flyout presenter class inherited from CustomFlyoutPresenter at application level and override create presenter as like below in custom flyout. Then, base CustomFlyoutPresenter style is not applied properly.

    public class CustomFlyout : FlyoutBase
    {
        protected override Control CreatePresenter()
        {
            var customFlyoutPresenter = new CustomFlyoutPresenter1();
            return customFlyoutPresenter;
        }
    }

    public class CustomFlyoutPresenter1 : CustomFlyoutPresenter
    {
    }

![image](https://user-images.githubusercontent.com/55440472/106581558-d816ba80-64f7-11eb-8f48-3ab85f7bfe22.png)

**Steps to reproduce the bug**
1. Run the sample.
2. Click the button to open the flyout.
3. Note CustomFlyoutPresenter style is not applied in custom flyout instead it refer MS FlyoutPresenter style.

**Expected behavior**
CustomFlyoutPresenter style should applied properly. 

**NuGet package version:** 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

**Sample:**
[CustomFlyoutPresenter-style-applied-from-base.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6008312/CustomFlyoutPresenter-style-applied-from-base.zip)

**Comment by chrisglein** [comment]
@mageshsankar How are you applying the style? In markup? Is it using [Flyout.FlyoutPresenterStyle](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Flyout.FlyoutPresenterStyle?view=winrt-19041)?

**Comment by mageshsankar** [comment]
@chrisglein, we have defined custom style for CustomFlyoutPresenter in library project. We didn't use Flyout.FlyoutPresenterStyle. Please find the screenshot regarding it below and refer attached sample in description for further details.
![image](https://user-images.githubusercontent.com/55440472/108471845-d57acb80-7240-11eb-8df9-73890d6c1cf7.png)

**Comment by mageshsankar** [comment]
Hi Team,

Any update on this?
