### ISSUE TITLE
ItemsRepeater: FlowLayout repositions items during scroll

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#408]
**Describe the bug**
ItemsRepeater: FlowLayout repositions items during scroll

[Internal Issue](https://microsoft.visualstudio.com/OS/_workitems/edit/19618165)

**Comment by jevansaks** [comment]
@ranjeshj do we need this for the 2.1 release?

**Comment by micahl** [comment]
Not needed for the 2.1 release since FlowLayout is still in 'preview'.

**Comment by ranjeshj** [comment]
Not required for 2.1 release. Flow layout is still in preview and this seems to be pronounced in this particular scenario where flow layout is being customized.

**Comment by jevansaks** [comment]
@ranjeshj can you provide some more details from the internal issue in this issue so that we can enable the community to help us fix it?

**Comment by ranjeshj** [comment]
Closing this issue since it does not repro with latest bits.
