### ISSUE TITLE
Pager Control: unable to hide buttons

### ISSUE THREAD

**Issue by XamlBrewer** [microsoft/microsoft-ui-xaml#4083]
**Describe the bug**
In a WinUI 2.6 (prerelease) Pager Control, setting any of the (First, Last, Next, Previous)ButtonVisibility to 'Hidden' has no effect.

**Steps to reproduce the bug**

1. Add Pager to UWP page
2. Set any of the Button visibilities to 'Hidden'
3. Run -> Buttons are visible

**Expected behavior**
Hidden Button should not be visible (or PagerControlVisibility enum should not have 'Hidden' value). Especially in ButtonPanelMode with first and last page number visible the standard buttons should really become invisible.

**Screenshots**
![PagerButtonVisibilities](https://user-images.githubusercontent.com/9828352/106765123-c426a200-6638-11eb-9378-f415c3d5e327.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0-prerelease.210113001]

Not using WinUI 3.
Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by chingucoding** [comment]
I'll take a look at this.
