### ISSUE TITLE
Pager Control: prefix text is displayed instead of suffix text

### ISSUE THREAD

**Issue by XamlBrewer** [microsoft/microsoft-ui-xaml#4085]
**Describe the bug**
In a WinUI 2.6 (prerelease) Pager Control, the prefix text ("Page") is displayed instead of the suffix text ("of") between the current page number and the total number of pages.

**Steps to reproduce the bug**

1. Add Pager to UWP page
2. Set in any DisplayMode except ButtonPanel
3. Run -> Pager shows "Page {currentPage} **Page** {totalPage}" instead of "Page {currentPage} **of** {totalPage}"

**Expected behavior**
Suffix text "of" should be displayed between the page number and the total number, instead of "Page".

**Screenshots**
![PagerSuffixText](https://user-images.githubusercontent.com/9828352/106777389-3f8e5080-6645-11eb-954a-02f984c721eb.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0-prerelease.210113001]

Not using WinUI 3.
Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@chingucoding FYI

**Comment by chingucoding** [comment]
I'll take a look at this.
