### ISSUE TITLE
WinUI failure to build when App.xaml/App.xaml.cs is a Linked file

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/microsoft-ui-xaml#4096]
**Describe the bug**
I am attempting to share code with multiple WinUI applications. One way to do this is with adding linked files in VS. When using a linked file for App.xaml and app.xaml.cs, winui fails to build.

**Steps to reproduce the bug**
1. Create a New WinUI Desktop project in VS using latest preview 3 - WinUIApp1
2. On the solution, right click and Add a new project - choose New WinUI Desktop project, and name it WinUIApp2
3. In WinUIApp2, delete the app.xaml/app.xaml.cs and MainWindow.xaml/.cs from the project. Go to explorer and confirm they do not exist.
4. In WinUIApp2, right click and choose Add Existing File - find and multiselect the app.xaml/.cs and MainWindow.xaml/.cs from WinUIApp1. Be sure to drop down the arrow on the 'Add' button and choose "Add as Link"
5. In WinUIApp2.csproj, change the rootnamespace to match WinUIApp1, eg:
- <RootNamespace>WinUIApp1</RootNamespace>
6. Choose 'Build" on WinUIApp2. Result fails. Xaml compiler fails to run against the linked files. If you copy the same exact app.xaml/cs files into the project directory, and leave the mainwindow files as a linked file, it will build.

**Expected behavior**
Expect the app to build
Linked files do work for the Window/Pages, just not app.xaml

**Version Info**
Latest Windows Insider build (21301) on desktop 

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type: Only tried Win32

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21301)              | Yes - latest insider build   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**

**Comment by huoyaoyuan** [comment]
It should be a Visual Studio issue that not adding correct thing in project file. The correct file should include: 
```xml
  <ItemGroup>
    <Page Include="..\Path\Page1.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Include="..\Path\Page1.xaml.cs" />
  </ItemGroup>
```

**Comment by marb2000** [comment]
Hey  @JeanRoca, can you track this issue? Make sure it still repro in the latest internal builds of VS, please.
