### ISSUE TITLE
AutoSuggestBox still shows when NavigationView is closed, even when disabled via API

### ISSUE THREAD

**Issue by llongley** [microsoft/microsoft-ui-xaml#4097]
In the NavigationView section of the XAML Controls Gallery, if you turn off the AutoSuggestBox in the "API in action" section at the bottom, things looks normal when the NavigationView is open:

![image](https://user-images.githubusercontent.com/18177025/106834335-158b5d00-664a-11eb-9e5a-076f650d5ad2.png)

However, when the NavigationView is open, the icon still appears:

![image](https://user-images.githubusercontent.com/18177025/106834402-3eabed80-664a-11eb-9ea7-114d9e3a3631.png)

Clicking on the icon opens the NavigationView but does nothing else, since the AutoSuggestBox is not actually present.

**Comment by chingucoding** [comment]
I would like to take a look at this :)
