### ISSUE TITLE
Question: Use something to pick files in a WinUI 3 Blank App

### ISSUE THREAD

**Issue by kirilvalev** [microsoft/microsoft-ui-xaml#4100]
I created a WinUI 3 Blank App and I am trying to select a file from the file system. Is there something in Winui 3 to support me doing so, FilePicker and OpenFileDialog do not seem to work with Winui3.

**Comment by huoyaoyuan** [comment]
They can work with workarounds: https://github.com/microsoft/microsoft-ui-xaml/issues/2716#issuecomment-727043010

**Comment by kirilvalev** [comment]
@huoyaoyuan, thank you. This only seems to work for **WinUI in UWP** projects and not for **WinUI in Desktop** projects.

**Comment by huoyaoyuan** [comment]
It worked for me in WinUI desktop.

**Comment by kirilvalev** [comment]
Would you please share your .csproj file?

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
    <RootNamespace>TestProjectWinUIDesktop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VCRTForwarders.140" Version="1.0.6" />
    <PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview3.201113.0" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
</Project>
`

**Comment by huoyaoyuan** [comment]
The project file is unrelated. I'm just using default of preview3.
Where are you calling the picker? It must be called when a window is shown.

**Comment by kirilvalev** [comment]
Thank you. I am also using WinUI preview 3. New "Blank App, Packaged (WinUI in Desktop)":

`using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Navigation;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace TestProjectWinUIDesktop
{
    /// <summary>
    /// An empty window that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
        }

        private async void myButton_Click(object sender, RoutedEventArgs e)
        {
            myButton.Content = "Clicked";


            // Open a text file.
            Windows.Storage.Pickers.FileOpenPicker open = new Windows.Storage.Pickers.FileOpenPicker
            {
                SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.DocumentsLibrary
            };
            open.FileTypeFilter.Add(".rtf");

            Windows.Storage.StorageFile file = await open.PickSingleFileAsync();

            if (file != null)
            {
                using (Windows.Storage.Streams.IRandomAccessStream randAccStream =
                    await file.OpenAsync(Windows.Storage.FileAccessMode.Read))
                {
                    // Load the file into the Document property of the RichEditBox.
                    // editor.Document.LoadFromStream(Windows.UI.Text.TextSetOptions.FormatRtf, randAccStream);
                }
            }


        }
    }
}`

Somehow the code feature in the editor is not formatting my code, sorry for that...

**Comment by huoyaoyuan** [comment]
You are using the default approach, which doesn't work. You need **workaround** from this comment: https://github.com/microsoft/microsoft-ui-xaml/issues/2716#issuecomment-727043010

**Comment by kirilvalev** [comment]
I understand, thank you! I thought, since the ticket #2716 is closed it would work without a workaround.

**Comment by marb2000** [comment]
Hi there,

In Desktop, or Win32, it's required to specify which Window Handle (HWND) owns the File/Folder Picker. It's the current design. Here you can find a code snipped:

```CS
 public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
        }

        private async void myButton_Click(object sender, RoutedEventArgs e)
        {
            var filePicker = new FileOpenPicker();

            //Get the Window's HWND
            var hwnd = this.As<IWindowNative>().WindowHandle;
       
            //Make folder Picker work in Win32
            var initializeWithWindow = filePicker.As<IInitializeWithWindow>();
            initializeWithWindow.Initialize(hwnd);
      
            filePicker.FileTypeFilter.Add("*");

            var folder = await filePicker.PickSingleFileAsync();
            myText.Text = folder != null ? folder.Path : string.Empty;
        }

        [ComImport]
        [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        public interface IInitializeWithWindow
        {
            void Initialize(IntPtr hwnd);
        }
        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
        internal interface IWindowNative
        {
            IntPtr WindowHandle { get; }
        }
    }
```

**Comment by marb2000** [comment]
Closing the issue. I hope the sample is good enough.

**Comment by nickrandolph** [comment]
@marb2000 the sample works fine.
A note for anyone trying to get this to work - make sure you add "using WinRT;" to the file where you're adding this code, otherwise you'll get compile issues with the "As" method. Window (as with a lot of WinUI classes) has a static As method, which conflicts with the As extension method available when adding the WinRT namespaces.

@marb2000 general comments/questions:
- This is super ugly to have to do this - is there a plan to clean this up so the developers don't have to deal with this hacky workaround?
- Is there a way to fall back to the UWP file picker when running in partial trust?

**Comment by mrjfalk** [comment]
I also ran into this issue, and while the workaround works it's not very nice experience and took some time to find this workaround.

As I use pickers in a number of places I wrote an extension method to help with this (usage: `picker.SetOwnerWindow(this);`), might be useful for others as well: https://gist.github.com/mrjfalk/93f7c66cabce1f68fef7102c38b2505e

**Comment by Rybasum** [comment]
@marb2000 The only reason I have to stay with UWP is that I want to run in AppContainer. Thanks to @nickrandolph I can run WinUI 3 in AppContainer but attempting to use hWnd with a file open picker leads to an Access Denied exception. Please, could Microsoft provide a way to initialise popup windows without an explicit usage of a hWnd?

**Comment by yesseruser** [comment]
You can use the `SaveFileDialog` class from the `Microsoft.Win32` namespace. Here's an example: 
``` C#
using Microsoft.Win32;
using System.IO;

// Saves a file into a user-specified destination

private void SaveButton_Click(object sender, RoutedEventArgs e)
{
    SaveFileDialog saveFileDialog = new SaveFileDialog();
    saveFileDialog.Filter = "Text files (*.txt)|*.txt|All files (*.*)|*.*";
    // This is used for specifying the file filter - .txt files or all files.
    saveFileDialog.InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
    // This specifies the initial folder upon showing the dialog.

    if (saveFileDialog.ShowDialog() == true)
    {
        string fileName = saveFileDialog.FileName;
        // Gets the selected file name with the path.

        File.WriteAllText(fileName, "Example text to save into the file.");
        // Saves into that file.
    }
}
```

**Comment by ghostidentity** [comment]
Hi, Im not sure why its close. I tried on Winui3 but there's an issue. 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/4637625/90c019bc-5194-4ae3-9bee-4114db559555)
