### ISSUE TITLE
Invalid cast from 'WinRT.IInspectable' to 'System.Collections.Generic.IEnumerable`1[Windows.Storage.IStorageFile]' using WinUI

### ISSUE THREAD

**Issue by stevenwdv** [microsoft/microsoft-ui-xaml#4111]
Casting a collection of `StorageFile`s to a collection of `IStorageFiles` and using it fails at runtime (this may also be the case with other interfaces, not sure. This only happens when using WinUI on Desktop, not with UWP.

**Steps to reproduce the bug**
 1. Download the [WinUI 3 Project Templates][1] extension
 2. Create a new C# "Blank App, Packaged (WinUI in Desktop)" via the template (two projects will be created, one for the code, one for the package)
 3. Possibly: edit the non-package project file to make sure it lists the correct  `TargetFramework` for me it lists `net5.0-windows10.0.18362.0` while I only have 10.0.19041.0 installed. (Issue: #4062)
 4. Add the following code to e.g. `OnLauched` in `App.xaml.cs`:
```cs
Task.Run(async () =>
{
    try
    {
        var folder = ApplicationData.Current.LocalFolder;
        var files  = await folder.GetFilesAsync();
        _ = ((IReadOnlyList<IStorageFile>) files).ToList();
    }
    catch (InvalidCastException ex)
    {
        Debugger.Break();
    }
});
```
5. Run the package project (enabling break on CLR exceptions recommended)
6. Observe the `InvalidCastException` in `DynamicInterfaceCastableHelpers.IsInterfaceImplemented`

  [1]: https://marketplace.visualstudio.com/items?itemName=Microsoft-WinUI.WinUIProjectTemplates

**Expected behavior**
Should work without exception.

**Version Info**
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20H2: 19042.746)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by marb2000** [comment]
Hey @Scottj1s,  does this exception sound to you as a CS/WinRT thing?

**Comment by marb2000** [comment]
Hi there,

In Desktop, or Win32, it's required to specify which Window Handle (HWND) owns the File/Folder Picker. It's the current design. Here you can find a code snipped:

```CS
 public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
        }

        private async void myButton_Click(object sender, RoutedEventArgs e)
        {
            var filePicker = new FileOpenPicker();

            //Get the Window's HWND
            var hwnd = this.As<IWindowNative>().WindowHandle;
       
            //Make folder Picker work in Win32
            var initializeWithWindow = filePicker.As<IInitializeWithWindow>();
            initializeWithWindow.Initialize(hwnd);
      
            filePicker.FileTypeFilter.Add("*");

            var folder = await filePicker.PickSingleFileAsync();
            myText.Text = folder != null ? folder.Path : string.Empty;
        }

        [ComImport]
        [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        public interface IInitializeWithWindow
        {
            void Initialize(IntPtr hwnd);
        }
        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
        internal interface IWindowNative
        {
            IntPtr WindowHandle { get; }
        }
    }
```

**Comment by StephenLPeters** [comment]
This looks like the same issue as https://github.com/microsoft/microsoft-ui-xaml/issues/4062. @stevenwdv do you agree?

**Comment by stevenwdv** [comment]
@StephenLPeters No, I actually explicitly mentioned that issue in the steps but it's not the issue I report here. Please read my report again more slowly ;)

**Comment by StephenLPeters** [comment]
@Scottj1s and @stevenbrix FYI

**Comment by marb2000** [comment]
@stevenwdv I have copied this issue into the CS/WinRT repo: https://github.com/microsoft/CsWinRT/issues/747
