### ISSUE TITLE
Path renders blurry when scaling is >100%

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#4116]
Create a simple Path like this:
`<Path Data="M 0 0 H 10 V 10 H 0 V 0" StrokeThickness="1" Stroke="Black" Stretch="Fill" Width="10" Height="10" />`

It will render blurry when display scaling is larger than 100%.

Some pictures with the UWP caption buttons vs them recreated in XAML:
100%
![100x](https://user-images.githubusercontent.com/78622729/107095765-0fe07380-6812-11eb-824e-7c7c08972429.png)

150%
![150x](https://user-images.githubusercontent.com/78622729/107095777-1969db80-6812-11eb-8510-05833cb42860.png)

UseLayoutRounding doesn't fix this, and it seems it's enabled by default.

**Comment by StephenLPeters** [comment]
@gabrieln17 Did you find this issue in Winui3 or System xaml?

**Comment by StephenLPeters** [comment]
@GeGao18 FYI

**Comment by gabrieln17** [comment]
It behaves the same with system xaml, WinUI 2.x and WinUI 3 uwp. With WinUI 3 desktop, it's blurry even with 100% scaling.

**Comment by mdtauk** [comment]
If the stroke thickness is 1epx, and you scale to 150%, that would be 1.5epx, so of course would show some blurring?

I know there was another issue regarding TextBox borders showing blurring at 100% scale, so WinUI 3.0 rendering may have an issue.

But were you expecting the stroke to remain at 1epx with scaling turned on?  Is there an API to prevent scaling of elements?

**Comment by gabrieln17** [comment]
The scaling makes sense, but there doesn't seem to be a way to make sure the lines are sharp.

UseLayoutRounding works for position and dimensions. There could be a similar property for paths and borders.

**Comment by mdtauk** [comment]
Kinda hard to have a 1.5px line not be blurry.

Now maybe there should be a Xaml feature to allow for stroke values which are not scaled.  So it will remain 1px thick even at 150% - 200% - 400% scaling etc.

You can opt out of scaling I think with ``Windows.UI.ViewManagement.ApplicationViewScaling.TrySetDisableLayoutScaling(true);`` but it may be Xbox only.

**Comment by gabrielconl** [comment]
The new titlebar buttons in WinUI3 Preview 4 have the same issue, as they probably also use Path.
![caption](https://user-images.githubusercontent.com/78622729/109516244-a40bc680-7ab0-11eb-9deb-7f7e0fd1169b.png)

**Comment by PlonkaAdam** [comment]
I thought this is a known issue because I have it on my pc and laptop (both on latest windows 11, scale 100%) but apparently it's supposed to work? The "Restore" icon looks awful
![image](https://user-images.githubusercontent.com/35062625/231254548-c660ca11-8648-42ed-b2a9-5fad68530da0.png)

**Comment by ranjeshj** [comment]
Generically scaling up a path at partial pixel percentages is going to incur anti-aliasing. There is no easy solution to this problem and this is not in plan to be addressed at this time.
