### ISSUE TITLE
NavigationView PaneTitle bug on open

### ISSUE THREAD

**Issue by movpushmov** [microsoft/microsoft-ui-xaml#4122]
**Describe the bug**
PaneTitle gets full width, but doesn't expand with NavigationVIew

**Steps to reproduce the bug**
1. Go to XAML Controls Gallery
2. Find NavigationView page
3. Scroll to "API in action"
4. Close and open NavigationView

**Expected behavior**
PaneTitle expands with NavigationView

**Screenshots**
![image](https://user-images.githubusercontent.com/49155506/107163467-b10a2e00-69ba-11eb-84fb-eec7e7e6d231.png)

**Version Info**
Windows 10 1903
Windows 10 1909
Windows 10 2004

NuGet package version: 
[Microsoft.UI.Xaml 2.5.0]
[Microsoft.UI.Xaml 2.4.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Unchecked |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21292.1010)              | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            | Unchecked |
| October 2018 Update (17763)        | Unchecked |
| April 2018 Update (17134)          | Unchecked |
| Fall Creators Update (16299)       | Unchecked |
| Creators Update (15063)            | Unchecked |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | Unchecked |
| Surface Hub        | Unchecked |
| IoT                | Unchecked |

**Additional context**
No context

**Comment by StephenLPeters** [comment]
@Alkanores The screenshot you provided is mid animation correct?

I think that the issues is that the Hamburger button back plate changes size immediately but the panel expands with an animation. This isn't present in with the 2.6 style since the backplate for this component is being removed.

**Comment by Alkanores** [comment]
> @Alkanores The screenshot you provided is mid animation correct?
> 
> I think that the issues is that the Hamburger button back plate changes size immediately but the panel expands with an animation. This isn't present in with the 2.6 style since the backplate for this component is being removed. 

Yes, panel expands with normal animation.

**Comment by Alkanores** [comment]
@StephenLPeters any news?

**Comment by Alkanores** [comment]
Actual for WinUI 2.5/WinUI 2.6

@StephenLPeters

![image](https://user-images.githubusercontent.com/49155506/124719460-d40c2000-df0f-11eb-94bf-1323ec5ffb5e.png)

**Comment by movpushmov** [comment]
@StephenLPeters any news?

**Comment by StephenLPeters** [comment]
@karenbtlai FYI

This hasn't met our prioritization bar yet. We would accept a contribution which fixed the issue but are currently working on things we've deemed more important.

**Comment by karenbtlai** [comment]
Thanks for filing the bug. This animation bug is a known issue, but we are prioritizing other fixes. 

The other issue is that we are currently deciding whether we should fix this animation bug or refactor the template so that the backplate for the PaneToggleButton is only the hamburger icon and not the entire line as per design spec.

**Comment by movpushmov** [comment]
@karenbtlai This bug is actual for winui 3 & Windows 11

https://user-images.githubusercontent.com/49155506/189407428-9e997112-50a9-4018-8b79-548d38726bb0.mov

**Comment by movpushmov** [comment]
@StephenLPeters
