### ISSUE TITLE
Adding an event listener to a xaml file using tab complete fails with Ensure Event Failed.

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#4124]
**Describe the bug**

Trying to add a new event for test page controls in XAML fails with "Ensure event failed":

![Image showing Ensure Event Failed event message](https://user-images.githubusercontent.com/16122379/107248270-6af0b100-6a32-11eb-92da-465dec48760d.png)

**Steps to reproduce the bug**
1. Open test page
2. Try to add event (e.g. Button.Click) using XAML

If those don't repro, building, starting MUXControlsTestApp and retrying the stops usually shows the error message.
**Expected behavior**

Should create function instead of showing error message.

**Additional context**

Uno is also suffering from this (https://github.com/unoplatform/uno/issues/982 , https://github.com/unoplatform/uno/issues/1348#issuecomment-520300471)

**Comment by chingucoding** [comment]
Uno platform is also hitting this issue: https://github.com/unoplatform/uno/issues/1348#issuecomment-520300471

**Comment by StephenLPeters** [comment]
@chingucoding is this an issue in the MuxControlsTest app or an issue when using Winui?

**Comment by chingucoding** [comment]
Both, this happens in the WinUI solution itsself with MUXControlsTestApp but also when writing simple UWP/WinUI apps.

**Comment by StephenLPeters** [comment]
So changing the title from "test pages" to "pages" would be appropriate?

**Comment by StephenLPeters** [comment]
@YuliKl can we had this off to the VS team?

**Comment by chingucoding** [comment]
> So changing the title from "test pages" to "pages" would be appropriate?

Yes, new title is fine.
