### ISSUE TITLE
Exception thrown when creating style setter value programmatically WinUI3 preview 3 for desktop

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4126]
When creating a style setter programmatically, the following exception is thrown

```
var style = new Style(typeof(MyControl));
style.Setters.Add(new Setter() { Property = MyEnumProperty, Value = EnumType.EnumValue });
```

> Exception thrown: 'System.ArgumentException' in WinRT.Runtime.dll
> An exception of type 'System.ArgumentException' occurred in WinRT.Runtime.dll but was not handled in user code
> Value does not fall within the expected range.
> 

> at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
> at ABI.Microsoft.UI.Xaml.ISetter.global::Microsoft.UI.Xaml.ISetter.set_Value(Object value)
> at Microsoft.UI.Xaml.Setter.set_Value(Object value)

**Comment by StephenLPeters** [comment]
This is probably a cswinrt issue @Scottj1s @stevenbrix

**Comment by arivoir** [comment]
This is still happening in preview 4

**Comment by codendone** [comment]
Sounds the same as #3663.

**Comment by arivoir** [comment]
This was fixed.
