### ISSUE TITLE
MenuFlyouts appear darker with WInUI Theming 

### ISSUE THREAD

**Issue by vitorgrs** [microsoft/microsoft-ui-xaml#4137]
MenuFlyouts appears randomly darker when using WinUI theming with OS/SDK applied ThemeShadow. Happens on Photos, Unigram, and several other apps. 

**Steps to reproduce the bug**
1. Open an app like Photos
2. Click on '...' and randomly it happens
![image](https://user-images.githubusercontent.com/9909446/107386686-d8ecb500-6ad2-11eb-8304-792a647cf45e.png)
3. When this happens, ThemeShadow remains active if you alternate between windows. Do a Alt+tab and you'll see
![image](https://user-images.githubusercontent.com/9909446/107386805-fae63780-6ad2-11eb-916d-6d22266e051e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/9909446/107386856-06d1f980-6ad3-11eb-97a3-dbf09dde0f02.png)

**Version Info**
I checked with WinUI 2.4, WinUI 2.5. Windows 19042. UWP targeting Windows SDK 18362 and 19041 and could repro. 

**My guess:** SDK/OS applying ThemeShadow on wrong z-order, because Flyout xaml resources theming changes with WinUI.

**My guess to fix** (still need to check): WinUI should probably make use of ThemeShadow itself on it's own theming resources, and replace SDK shadow styling.

**Comment by mdtauk** [comment]
@karenbtlai https://github.com/microsoft/microsoft-ui-xaml/pull/4079

**Comment by StephenLPeters** [comment]
@kmelmon FYI

**Comment by pratikone** [comment]
can you check if it still gets reproduced ?  feel free to open this issue again if it does.
