### ISSUE TITLE
NavigationView shows unwanted empty block

### ISSUE THREAD

**Issue by Alkanores** [microsoft/microsoft-ui-xaml#4139]
**Describe the bug**
If PaneFooter is empty and IsSettingsVisible="False" NavigationView show unwanted empty bottom block if height of window is small

**Steps to reproduce the bug**

1. Create NavigationView and set IsSettingsVisible to "False"
2. Decrease height of window until you see an empty block

**Expected behavior**
NavigationView must hide this block, If PaneFooter empty and Settings button not visible

**Screenshots**
![image](https://user-images.githubusercontent.com/49155506/107440338-80ee9680-6b44-11eb-9aef-104c346e9eef.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.5.0]
[Microsoft.UI.Xaml 2.4.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Unchecked |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| October 2020 Update (19042)        | Unchecked  |
| May 2020 Update (19041)            | Unchecked   |
| November 2019 Update (18363)       | Unchecked  |
| May 2019 Update (18362)            | Unchecked  |
| October 2018 Update (17763)        | Unchecked |
| April 2018 Update (17134)          | Unchecked  |
| Fall Creators Update (16299)       | Unchecked |
| Creators Update (15063)            | Unchecked  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | Unchecked |
| Surface Hub        | Unchecked |
| IoT                | Unchecked |

**Additional context**
No context.

**Comment by chingucoding** [comment]
Thanks for filing this issue! This was already reported here: #3900

**Comment by Alkanores** [comment]
> Thanks for filing this issue! This was already reported here: #3900

Oh, sorry for duplicate)
