### ISSUE TITLE
🚨How to Enable UI Tooling for WinUI 3 in VS 16.9 Preview 4

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/microsoft-ui-xaml#4140]
# Enable WinUI 3 UI Tooling with Preview Features

Hello Developers!

Today Visual Studio released [16.9 Preview 4](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.9.0.pre.4.0). If you have upgraded to this latest version, you will need to enable some of the WinUI 3 tooling using the Preview Features page. In order to enable the tooling features like Live Visual Tree, Live Property Explorer, and Hot Reload please follow the following steps inside Visual Studio:

1. Navigate to the Preview Features page by going to Tools -> Options -> Environment -> Preview Features 
2. Click on "Enable UI Debugging Tooling for WinUI 3 Projects"
3. Click on OK

This is it! Please feel free to open an issue if you experience any difficulties.

**Comment by jschwizer99** [comment]
With the latest Windows Updates and 16.9 Preview 4 I suffer from a crash of the CppDebug.dll whenever the debugger hits an exception. I can start the application without a debugger attached (Ctrl + F5). The issue could be related to https://developercommunity2.visualstudio.com/t/Unexpected-VS-crash-when-docking-or-spli/1323017. However, 16.9 Preview 4 should contain a fix for that problem.

![image](https://user-images.githubusercontent.com/7672712/107546256-75df4900-6bcc-11eb-9251-900e1536992c.png)

Faulting application name: msvsmon.exe, version: 16.9.1149.0, time stamp: 0x601c922f
Faulting module name: CppDebug.dll, version: 16.0.31004.209, time stamp: 0x7ccaf500
Exception code: 0xc0000005
Fault offset: 0x000000000002ede0
Faulting process id: 0x1ce0
Faulting application start time: 0x01d6ffcd26be3b54
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\Remote Debugger\x64\msvsmon.exe
Faulting module path: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PREVIEW\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\VC\DEBUGGER\x64\CppDebug.dll
Report Id: f27662fa-1cab-400e-a430-3931541438b8

**Comment by get-flat** [comment]
I followed all listed steps but unfortunately Hot Reload does not work for me.
- no UI reload
- no app-in toolbar
- live visual tree throws (i.e. on child node selection or "Show just my xaml" etc.)
Exception thrown at 0x74FC46D2 in App1.exe: Microsoft C++ exception: ATL::CAtlException at memory location 0x1B27F618.
Exception thrown at 0x74FC46D2 in App1.exe: Microsoft C++ exception: ATL::CAtlException at memory location 0x1B27EB40.

(note: Hot Reload works for WPF)

**Comment by JeanRoca** [comment]
@get-flat thanks for the info, can you open an issue with a minimal repo for the team to investigate? Thank you!

**Comment by Fu-Weitao** [comment]
Hi, I was following https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-4, and in 'Install WinUI Preview 4' 
There's 'Make sure your system has a NuGet package source enabled for nuget.org. For more information, see Common NuGet configurations.' 
After reading the article it links to, which was updated in 2017 and also 'nugget.org' I found 'latest Nuget releases are delivered as part of Visual Studio updates', and I'm kinda confused whether I should do something to 'Make sure your system has a NuGet package source enabled for nuget.org'.
I would really appreciate it if you could help me with this question.

**Comment by sketch34** [comment]
One we enable it, how do we access these features in VS? I can't find anywhere that describes *where* these features are or how to use them.

**Comment by JanRajnoha** [comment]
I enabled it but hot reload missing panel on running app. I know, it isn't important, but it could be weird. But overall, it looks it is working for first look.

**Comment by kmgallahan** [comment]
@JeanRoca Do you know if these features are coming out of VS preview anytime soon? Would like to avoid a SxS install if possible.

**Comment by JeanRoca** [comment]
> I enabled it but hot reload missing panel on running app. I know, it isn't important, but it could be weird. But overall, it looks it is working for first look.

We currently do not support the in app toolbar and are unsure of when we can prioritize this. If this is something that you would really like to see please provide feedback on your specific scenario.



> @JeanRoca Do you know if these features are coming out of VS preview anytime soon? Would like to avoid a SxS install if possible.

Unfortunately, the earliest we could have them out of VS preview would be 16.10 GA :/

**Comment by JanRajnoha** [comment]
It's okay without it, but some mention would be nice for other people. Maybe I missed it in docs.

**Comment by ichan-akira** [comment]
How to enable UI tooling for Win UI 3 in VS 16.10 Preview 3?

I seems cannot access Live Visual Tree and Live Property Explorer.

**Comment by ChrisK91** [comment]
I'm using the Project Reunion Extension 0.5.7 with Visual Studio 16.10.0. In my setup "Enable UI Debugging Tooling for WinUI 3 Projects" is not available under "Preview features". Is a certain version required, to enable it?

**Comment by KenionX** [comment]
same issue here VS 16.11.0 Preview 2.0 WinUi3 0.8  Doesnt Hotreload anything, under LTV it say install latest version of VS and WinUI...

**Comment by arivoir** [comment]
I'm getting this message in _Live Visual Tree_ of Visual Studio Version 16.11.0 Preview 2.0

> "The winui 3 version used by the application is not supported for UI Debugging"

![image](https://user-images.githubusercontent.com/17496741/124338972-30beb200-db81-11eb-8776-3a815d4b3664.png)

Anybody else having this problem?

**Comment by brinko99** [comment]
> Anybody else having this problem?

According to the [docs](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/system-requirements#visual-studio-support-for-winui-3-tools), it looks like Live Visual Tree and Hot Reload for ver 0.8 is only available in VS 2019 16.11 Preview 3 (now available).

I find that Live Visual Tree works, but Hot Reload does not work for me. I'm stuck on Win SDK 10.0.18362.0; I'm not sure if that's my trouble.

**Comment by arivoir** [comment]
The visual tree is appearing in Visual Studio 16.11 preview3

![image](https://user-images.githubusercontent.com/17496741/128038322-cc4e596e-45fa-4bfb-aef8-0f2d44742c0a.png)

But the tools to pick an element or show the overlying bounds of the element aren't there

**Comment by arivoir** [comment]
Also, custom controls properties aren't shown in _Live Property Explorer_

![image](https://user-images.githubusercontent.com/17496741/128038758-82ae243d-976e-4757-ac38-5d6211cb71c9.png)

**Comment by brinko99** [comment]
@arivoir Were you able to see Hot Reload working? It is not working for me with either 0.5+ or 0.8+ or 16.11 Preview 3

**Comment by arivoir** [comment]
Modifying xaml seems to work, but modifying code gives this error

> Error	ENC2001	Changes made in project 'FlexGridExplorer' will prevent the debug session from continuing: Changes are not allowed when unmanaged debugging is enabled.	

not sure if I'd need to configure something

**Comment by josetr** [comment]
@arivoir Just change your package debugger type to "Managed Only" as shown below:

![ManagedOnly](https://user-images.githubusercontent.com/37419832/129110650-6987004a-b7a8-4c25-b5c7-5b7b1b5fb063.png)

**Comment by weitzhandler** [comment]
In VS 16.11.5, after installing the latest version of WindowsAppSdk, hot reload doesn't work for the generated project.
I've tried the solutions above, none of which helped.

**Comment by MichaelBakker** [comment]
> In VS 16.11.5, after installing the latest version of WindowsAppSdk, hot reload doesn't work for the generated project. I've tried the solutions above, none of which helped.

Same here

**Comment by kmgallahan** [comment]
I'm pretty sure MS dropped hot reload support for VS 2019, and it is only going to be available in VS 2022 since they don't have the time to make it work in both.

**Comment by arivoir** [comment]
I'm having this problem back in version _Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.4.0 Preview 2.1_

Is it necessary to install any extension?
