### ISSUE TITLE
Accent button foreground should be white

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#4143]
In the new styles, the foreground of an accent button is black which isn't that readable. Consider using white instead

**Comment by mdtauk** [comment]
> In the new styles, the foreground of an accent button is black which isn't that readable. Consider using white instead

Now the Accent colour adapts by using lighter shades in a Dark Theme, and I wouldn't be surprised to see these Light and Dark shades altered in the future to make the contrasts better.

**Comment by StephenLPeters** [comment]
@teaP FYI

**Comment by StephenLPeters** [comment]
@YuliKl FYI

**Comment by YuliKl** [comment]
Thank you for the note @Jaiganeshkumaran. @mdtauk is correct that our goal is to use accent color variants more judiciously in the future.

Closing this issue.
