### ISSUE TITLE
The TextBox with TextWrapping="WrapWholeWords" throws exception

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#4144]
**Describe the bug**
Hi, set TextWrapping="WrapWholeWords" causes crash an app.

**Steps to reproduce the bug**
``` xaml
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <TextBox TextWrapping="WrapWholeWords"/>
</StackPanel>
```
![image](https://user-images.githubusercontent.com/47348109/107488077-f172d300-6b97-11eb-8260-5b5664256973.png)

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
We just released Winui3 Preview 4! does this issue still reproduce with the updated version?
