### ISSUE TITLE
Proposal: Use AnimatedIcon in shell 

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#4146]
# Proposal: Use AnimatedIcon in shell 

## Summary

The [animated icon ](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/6b00ddc1239e9d76b206865ee54e93defb07bd77/active/AnimatedIcon/AnimatedIconSpec.md) would allow nice user experience when interacting with the application. Why not expand that experience to the shell? Imagine if the app icon animates a little when user hovers the pointer over the icon in the start menu. And the icon animates a little more when user press the icon. It could be a unique user experience on a computing device. Most of the work is already done, lot of states are already defined in the proposal, and some of the states and transitions can be used for shell experience.

Animated icon could also be displayed on the app Start-up Screen. Currently only a static icon is displayed, a bit of animation could reduce the perceived wait too.

## Rationale

* Unique fluent experience

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to define an Animated icon for shell| Must |
| This proposal will allow developers to define an Animated icon for Start-up screen| Must |

## Important Notes

Too much of animation could also be jarring for users. The animation need have to be restraint , especially for shell. Start-up screen animation could be little more bold. If this is proposal is implemented, good amount of guidance and possibly tools should accompany it.

## Open Questions

I am not sure if project reunion is the right place.

**Comment by mdtauk** [comment]
The shell would need to decide to move to a version of WinUI which includes the control.

I believe the control will also be used with the Checkbox control to animate the Checked state.

I also think they should wait until the Windows team moves to FluentUI System Icons - so only one set of animated icons will need to be made for it.

**Comment by chigy** [comment]
@harvinders , thank you for your suggestion! 

Reminder that this is a WinUI repo so this suggestion should go to Feedback Hub so that Windows shell team can determine as @mdtauk suggests.

We welcome things WinUI can do to improve supporting scenario like this if you think our support is limited.
