### ISSUE TITLE
Question: How can I do Templated Controls in a WinUI 3 Class Library and use other styles instead the default defined in the construtor?

### ISSUE THREAD

**Issue by marck7jr** [microsoft/microsoft-ui-xaml#4151]
I created a custom Control and defined its default style in a ResourceDictionary and I added it in the MergedDictionaries property in the ResourceDictionary defined in Generic.xaml. It works as expected at first moment, but when I tried to use a named Style calling the respective Key instead of the DefaultStyleKey defined in the custom control construtor, I got this exception:

![image](https://user-images.githubusercontent.com/30981574/107595053-f95b6300-6be9-11eb-990a-8f736bf38f99.png)
![image](https://user-images.githubusercontent.com/30981574/107595068-0b3d0600-6bea-11eb-825c-b4c02c75a688.png)

And here is where I define the custom control with the specified ResourceKey:

![image](https://user-images.githubusercontent.com/30981574/107595288-9ae2b480-6bea-11eb-9c9e-6ff76a6856bd.png)

Summary of the GameControl.xaml file:

![image](https://user-images.githubusercontent.com/30981574/107595960-a6cf7600-6bec-11eb-8789-411edba63736.png)

WinUI Class Library Generic.xaml file:

![image](https://user-images.githubusercontent.com/30981574/107595112-21e35d00-6bea-11eb-9df3-23fd56d18979.png)

Desktop App Generic.xaml file:

![image](https://user-images.githubusercontent.com/30981574/107595427-eeed9900-6bea-11eb-9010-d560a2bb18b4.png)

And the project structure:

![image](https://user-images.githubusercontent.com/30981574/107595167-4808fd00-6bea-11eb-8790-1e8a4593662a.png)

If I instead define these controls inside the Desktop app project, it works fine, but I am wondering how I can achieve this in class library. Thank you for attention.

**Comment by nguyenkien** [comment]
Create solution like this
Mylibrary.sln
  MyLibrary.Shared (contains your code)
  MyLibrary.WinUi (target uwp, contains Uwp specific code and controls style)
  MyLibrary.Wpf (Same as above but for uwp

**Comment by marck7jr** [comment]
Thanks @nguyenkien but that's is not the question and I'll need to reformulate the title, sorry for that; the point is that my Custom Controls only works with their default styles, if I define an alternative one and try to use in Xaml code, that exception is throwed, so I am wondering a way to fix it.

**Comment by nguyenkien** [comment]
You should include this in app.xaml instead 

https://user-images.githubusercontent.com/30981574/107595427-eeed9900-6bea-11eb-9010-d560a2bb18b4.png

**Comment by marck7jr** [comment]
THANK YOU SO MUCH @nguyenkien! It works perfectly. Closing here.
