### ISSUE TITLE
Question: NavigationView has different TabNavigation in UWP and WinUI 3

### ISSUE THREAD

**Issue by mvegaca** [microsoft/microsoft-ui-xaml#4153]
Hi,
I'm Martin from Windows Template Studio Team.

We are working on WinUI 3 templates that use NavigationView control, the same as we are using on UWP Apps.

I've noticed that the TabNavigation is different in UWP and WinUI, in the case of UWP the navigation focus return to the first navigation item after finishing all the focus navigation.

In the case of WinUI 3 the focus keeps on the last focusable item and does not return to the beginning.

I've created a minimum repro app that includes the same basic code in UWP and WinUI 3
[TabNavigationIssueWinUI3App.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5964997/TabNavigationIssueWinUI3App.zip)

![image](https://user-images.githubusercontent.com/5556784/107633243-fd2dca80-6c67-11eb-9a47-4ceb7465a43e.png)

I would like to have the same tab navigation behavior in WinUI, Is there any Issue with that? Have I to apply some workaround?

Many thanks ;)

**Comment by StephenLPeters** [comment]
@Austin-Lamb I don't believe there is any difference in the version of NavView that is in Winui3 and Winui 2, so I think this points to a difference in tab navigation.

**Comment by mvegaca** [comment]
I've verified it's fixed on WinUI 3 Preview 4
