### ISSUE TITLE
TextBox changes height unexpectedly in single line mode when using TextWrapping

### ISSUE THREAD

**Issue by MuziburRahman** [Microsoft/microsoft-ui-xaml#416]
In an attempt to hide the cross button, I set the `TextWrapping` to Wrap while not accepting returns. This works a lot of times, except when the `TextBox` has enough space to grow vertically, it will try to grow vertically, and then will grow horizontally afterwards : 

![hh](https://user-images.githubusercontent.com/21083609/54255473-6e4b3b80-4582-11e9-9e59-ab0a78f3dbf3.gif)

**Steps to reproduce the bug**

Place the `TextBox` in a Control large enough to hold multiple lines of that `TextBox`:

```
<Page
    x:Class="Test2.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Test2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    d:DesignWidth="400"
    d:DesignHeight="500"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <TextBox
        VerticalAlignment="Center"
        HorizontalAlignment="Center"
        TextWrapping="Wrap"
        Loaded="TextBox_Loaded"/>
</Page>
```

**Expected behavior:**
It should try to grow horizontally first, if fails, then it should try vertical growth.

October 2018 Update (17763)   
Desktop

**Comment by jevansaks** [comment]
Interesting. Short of re-templating to remove the delete button, I don't see another workaround. I'm asking the team about the height jumping problem, that just seems weird.

**Comment by jevansaks** [comment]
We found an internal issue that sounds like this bug. It regressed in 17763 but is fixed in insider builds. Can you try on insider?
