### ISSUE TITLE
ItemsRepeater sometimes doesn't load all items after being animated into view

### ISSUE THREAD

**Issue by arcadiogarcia** [microsoft/microsoft-ui-xaml#4165]
**Describe the bug**
 ItemsRepeater with UniformGridLayout sometimes doesn't refresh correctly after it is animated into view. 

The ItemsRepeater only displays the first two items when it should display a higher number based on its size. 

The rest of the items only load after the user interacts with the ItemsRepeater, we notify of changes to the ItemsSource, or we call itemRepeater.InvalidateMeasure(); manually.

**Steps to reproduce the bug**
I have a repro but it is not a public app, I can share the code/videos with MSFT folks (feel free to reach out to me in Teams).

**Expected behavior**
 I would expect ItemsRepeater to always react to size/visibility changes and update the number of elements shown accordingly.

**Screenshots**

**Version Info**

NuGet package version: 
2.5.0-prerelease.200708003

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes|  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
Is it possible to pair down the issue into a min repro app?

**Comment by arcadiogarcia** [comment]
@StephenLPeters  I managed to distill it to the basic elements here: https://github.com/arcadiogarcia/ItemsRepeaterRepro

To repro, press Open right after opening the app and you will only see 3 instead of 6 elements in the pane that opens.

**Comment by mkunstman** [comment]
This also presents when content within the rows updates and is rearranged multiple times.  Instances where a list might update and resort while still visible.  

For example a list of live shows where the most recently started or featured filter to the beginning but old content still sticks around.  In those instances it seems a forced invalidation is also required.

**Comment by dpaulino** [comment]
Any updates on this? I'm hitting strange issues like this too, but haven't nailed down a small repro yet. Running winui 2.5.

**Comment by dpaulino** [comment]
And strangely, if I have 3 items in the list, the bug occurs. But if I have 1 or 2, I cannot reproduce the bug.
