### ISSUE TITLE
New menu flyout style is too large

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#4172]
After adding version="latest", I noticed menus are very large compared to before. I think you need to reduce the size a little bit since many apps already overflow menus and this will reduce the capacity

**Comment by StephenLPeters** [comment]
@Jaiganeshkumaran Can you provide some screenshots of what you are seeing? :)

**Comment by mdtauk** [comment]
Extra padding has been added to the Menu flyouts with the 2.6 visual styles.
