### ISSUE TITLE
[winui3 preview 4] Nuget, can't "install-package Microsoft.WinUI -Version 3.0.0-preview4.210202.1-CI"

### ISSUE THREAD

**Issue by niclar** [microsoft/microsoft-ui-xaml#4175]
In https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/preview_upgrade_instructions.md

one is to run the below command to update to winui4 preivew 4:

install-package Microsoft.WinUI -Version 3.0.0-preview4.210202.1-CI

it returns:

Attempting to gather dependency information for package 'Microsoft.WinUI.3.0.0-preview4.210202.1-CI' with respect to project 'client', targeting 'native,Version=v0.0'
install-package : Package 'Microsoft.WinUI 3.0.0-preview4.210202.1-CI' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json,C:\Program Files (x86)\Microsoft 
SDKs\NuGetPackages\'. Please verify all your online package sources are available (OR) package id, version are specified correctly.
At line:1 char:1
+ install-package Microsoft.WinUI -Version 3.0.0-preview4.210202.1-CI
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by huoyaoyuan** [comment]
It should be documentation issue? The corresponding package doesn't have `-CI` suffix.

**Comment by niclar** [comment]
same result with "install-package Microsoft.WinUI -Version 3.0.0-preview4.210202.1" though

**Comment by crramirez** [comment]
Remember that you need to install the WinUI 3 Preview 4 VSIX package which includes the package. After that I just changed the reference in my project file

**Comment by huoyaoyuan** [comment]
Well, the exact version used by P4 template project is `3.0.0-preview4.210210.4`.

**Comment by anawishnoff** [comment]
Thank you for catching this - this was an oversight on my part as I forgot to update the package number in the upgrade instructions. I have a PR out to update those, but as @huoyaoyuan mentioned above, the correct NuGet package version number is 3.0.0-preview4.210210.4. So, that line should instead read:

`install-package Microsoft.WinUI -Version 3.0.0-preview4.210210.4`

**Comment by StephenLPeters** [comment]
resolved by #4178?
