### ISSUE TITLE
[Preview 4] White line on the left of the window that vanishes once the window is resized

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#4176]
**Describe the bug**

Below is a screenshot of a winui window on a black background:

![image](https://user-images.githubusercontent.com/38145893/107757449-db931880-6d25-11eb-9df4-239b3d1cc7ef.png)

As you can see, there is a white line on the left side that vanishes when the window is resized. The content seems to move about 1 pixel to the left when this is done.

**Steps to reproduce the bug**

Create a new desktop winui project and use the following code as the window content:

```xaml
<Grid Background="Green">
		<NavigationView x:Name="NavView" CompactModeThresholdWidth="10" ExpandedModeThresholdWidth="10000" IsSettingsVisible="False" AlwaysShowHeader="false" IsBackButtonVisible="Collapsed" RequestedTheme="Dark">
			<NavigationView.Resources>
			</NavigationView.Resources>
			<NavigationView.MenuItems>
				<NavigationViewItem Content="Settings" Icon="Setting"/>
			</NavigationView.MenuItems>
			<NavigationView.Content>
				<Button>Click Me</Button>
			</NavigationView.Content>
		</NavigationView>
	</Grid>
```

I have also observed such white lines that appear and disappear when resizing on the edges of a SwapChainPanel.

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@marb2000 and @Austin-Lamb FYI

**Comment by pratikone** [comment]
the white line no longer appears. Instead, with your given example, i can see the background grid's green being visible on the left side of navigation view. I am not sure if its design is intentional. I will let @ranjeshj confirm its design.  The original white line issue is no longer there. Hence i will close this issue now.

![image](https://user-images.githubusercontent.com/115935/209409527-3965417e-be56-42fa-b128-db0aa137654d.png)
