### ISSUE TITLE
[Preview4] Window.Current is null 

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#4177]
**Describe the bug**
The `Window.Current` is '`null` in a Desktop project. I use it to retrieve whether the Ctrl and Shift keys are Down. Using CoreWindow.GetKeyState(). I hope there is an workaround for retrieving the KeyState.

**Steps to reproduce the bug**

1. Build a Preview 4 WinUI app.
2. Inspect the Microsoft.UI.Xaml.Window.Current property.

**Expected behavior**
It should not be null

**Screenshots**
![image](https://user-images.githubusercontent.com/9335559/107783566-b369e080-6d4a-11eb-98c7-3b2e61a445cd.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by sonnemaf** [comment]
@azchohfi found a workaround for my GetKeyState() problem. I should use `KeyboardInput.GetKeyStateForCurrentThread()` instead. Thanks you.

https://twitter.com/AlexandreChohfi/status/1360274722517254145

**Comment by StephenLPeters** [comment]
@anawishnoff FYI @MikeHillberg

**Comment by MikeHillberg** [comment]
We're working on documentation to list the APIs that behave differently on Desktop compared to UWP (several new to Preview4), we'll make sure this one is there.

**Comment by krschau** [comment]
> We're working on documentation to list the APIs that behave differently on Desktop compared to UWP (several new to Preview4), we'll make sure this one is there.

Here's the doc: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api
