### ISSUE TITLE
[Preview 4] Accessing the UIViewSettings class does not work

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#4181]
**Describe the bug**

Accessing the UIViewSettings class to get the UserInteractionMode is not possible.

**Steps to reproduce the bug**

1. Call UIViewSettings.GetForCurrentView()
2. Observe that it returns NULL

**Expected behavior**

There should be a way to use this class in winui 3.

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@MikeHillberg FYI

**Comment by MikeHillberg** [comment]
This API isn't supported for Desktop apps in Preview4 of WinUI. We're working on updating documentation and release notes about what APIs to use instead. Sorry we haven't made it clear enough.

The `View` in these GetForCurrentView APIs is referring to [ApplicationView](https://docs.microsoft.com/uwp/api/Windows.UI.ViewManagement.ApplicationView), which is only supported in a UWP app, not in a Desktop app. Up until Preview4 we had some code that was making this partially work, but it was never going to work well so we removed it. The issue is that ApplicationView fundamentally assumes that there's only one window per thread, and we want to support multiple.

**Comment by chrisglein** [comment]
As Mike has described this is an intended breaking change.

> We're working on updating documentation and release notes about what APIs to use instead. Sorry we haven't made it clear enough.

@anawishnoff as an FYI, as it sounds like there's an effort to better capture this. The direct removal is represented but maybe we can better capture the downstream implications of that.

**Comment by lhak** [comment]
I found out that the IUIViewSettingsInterop interface can be used to get this information in a desktop app. However, getting it to work in C# was quite complicated. Would be nice if the usage could be officially documented.

**Comment by anawishnoff** [comment]
Hi @lhak, we recently published this article on [how to call WinRT COM interop interfaces from .NET 5+ apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/winrt-com-interop-csharp). Is this useful for the scenario you described/is there anything that you feel still needs documenting?

**Comment by codendone** [comment]
Summarizing:

It is now a bit easier to use UIViewSettingsInterop when using  .NET 5.0.205 SDK or later, such as this sample code (where "this" is the WinUI Window object):
```
            var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
            var settings = Windows.UI.ViewManagement.UIViewSettingsInterop.GetForWindow(hwnd);
            var mode = settings.UserInteractionMode;
```
As mentioned above, more info on the interop is here: [Call WinRT COM interop interfaces from .NET 5+ apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/winrt-com-interop-csharp)
