### ISSUE TITLE
Proposal: Allow `ComboBox` `IsTextSearchEnabled` when `ItemTemplate` provided

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/microsoft-ui-xaml#4182]
# Proposal: Allow `ComboBox` `IsTextSearchEnabled` when `ItemTemplate` provided

## Summary
`IsTextSearchEnabled` allows users to type characters into a `ComboBox` and jump to the entry starting with that letter. However, this only works if the `ItemsSource` is a list of strings (understandably so). It would be nice to provide some kind of API to enable this feature when the `ItemsSource` is a custom object and the `ComboBoxItem`s are presented as more complex views of the bound item.

![Example](https://user-images.githubusercontent.com/11050425/107816794-20b94980-6d2a-11eb-8742-844669fd840a.png)

## Rationale
* Customizing the appearance of `ComboBox` items is not uncommon. In the example above, all I've added is an icon.
* TextSearch is a very useful feature. Users can get confused if some ComboBoxes have it enabled (because they are bound to strings) and others don't.
* The developer could try to implement this manually, but then they are at risk of implementing it slightly differently. A first party solution would be preferred.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

## Important Notes

**Example**:
Windows Terminal binds `ComboBox.ItemsSource` to the settings model as such:
```xml
                    <ComboBox x:Name="DefaultProfile"
                              ItemsSource="{x:Bind State.Settings.AllProfiles, Mode=OneWay}"
                              SelectedItem="{x:Bind CurrentDefaultProfile, Mode=TwoWay}"
                              Style="{StaticResource ComboBoxSettingStyle}">
                        <ComboBox.ItemTemplate>
                            <DataTemplate x:DataType="SettingsModel:Profile">
                                <Grid HorizontalAlignment="Stretch" ColumnSpacing="8">

                                    <Grid.ColumnDefinitions>
                                        <!-- icon -->
                                        <ColumnDefinition Width="16"/>
                                        <!-- profile name -->
                                        <ColumnDefinition Width="Auto"/>
                                    </Grid.ColumnDefinitions>

                                    <IconSourceElement
                                    Grid.Column="0"
                                    Width="16"
                                    Height="16"
                                    IconSource="{x:Bind Icon,
                                                        Mode=OneWay,
                                                        Converter={StaticResource IconSourceConverter}}"/>

                                    <TextBlock Grid.Column="1"
                                           Text="{x:Bind Name}"/>

                                </Grid>
                            </DataTemplate>
                        </ComboBox.ItemTemplate>
                    </ComboBox>
```
where `State.Settings.AllProfiles` is an observable vector of profile objects. All we're doing in this template is adding an icon. Binding to `Profile` objects allows us to bind `SelectedItem` and have this work fairly straightforward with little modifications.

**Comment by stmoy** [comment]
Seems like a righteous ask to me, but I thought this should "just work" - the typeahead logic in ComboBox has a set of fallback logic to figure out which item to jump to. Does this work if you provide a `ToString()` implementation on the items themselves?

(Unassigning since there isn't action I can take on this issue beyond "👍 - lets fix this")

**Comment by carlos-zamora** [comment]
> Seems like a righteous ask to me, but I thought this should "just work" - the typeahead logic in ComboBox has a set of fallback logic to figure out which item to jump to. Does this work if you provide a `ToString()` implementation on the items themselves?
> 
> (Unassigning since there isn't action I can take on this issue beyond "👍 - lets fix this")

I added `String ToString()` to the `SettingsModel:Profile` object and that didn't work. There isn't an interface I need to make it follow, right?

CC @DHowett since he was also curious

**Comment by stmoy** [comment]
There shouldn't be an interface that you need to follow, no. I think if you spelunked in the core implementation of ComboBox, I did a pretty decent job commenting the various typeahead fallbacks when I wrote it 😉   I just don't remember them all offhand.

**Comment by DHowett** [comment]
(As a matter of curiosity: how can it know there is a ToString when the entire runtime object model is based on interfaces like COM? There’s no reflection to help us out, so I am a bit confused here!)

**Comment by carlos-zamora** [comment]
Aha! Turns out you need the [`Windows.Foundation.IStringable`](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.IStringable?view=winrt-19041) interface. Then it works!

I guess the only ask I have here is to please include this in the [docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox.istextsearchenabled?view=winrt-19041). Thanks for the quick response folks! Closing!

**Comment by stmoy** [comment]
Thanks for follow up, both! My bad about forgetting about the interface; that'd answers @DHowett's question too, right?

**Comment by carlos-zamora** [comment]
Yup. Dustin and I were chatting on teams haha
