### ISSUE TITLE
Question: Why is the Microsoft.WinUI.AppX.targets file in my project instead of in the NuGet package

### ISSUE THREAD

**Issue by mattleibow** [microsoft/microsoft-ui-xaml#4185]
I just noticed that when I create a new packaged desktop app, there is a `Microsoft.WinUI.AppX.targets` file in the package project. This looks very much like it should be in the actual package? Also, it is hidden in that it is not included in the items in the project, which means I actually missed it.

Why was it put as a copy and not as pert of the package? It looks like it is unchanging between actual projects and more just boilerplate?

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by stevenbrix** [comment]
This is because before VS16.9 P4, the wapproj didn’t support PackageReference in VS. This is something that should be deleted before the 3.0 release

**Comment by alwu-msft** [comment]
Closing as this is no longer true starting with Project Reunion 0.5.
