### ISSUE TITLE
Layout Cycle with ItemsRepeater in WinUI 2.5

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/microsoft-ui-xaml#4186]
**Describe the bug**

Scrolling in the attached sample causes the app to crash with a Layout cycle.

**Steps to reproduce the bug**

- Build the attached sample app.
- Scroll through the list. You might have to do this a few times for the crash to happen.
- Wait for the app to crash.

**Expected behavior**

No crash.

**Screenshots**

N/A

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.5.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| October 2020 Update (19042)        | Yes      |
| May 2020 Update (19041)            | Yes    |
| November 2019 Update (18363)       | Yes      |
| May 2019 Update (18362)            | Yes      |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes    |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

[LayoutCycle.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5974784/LayoutCycle.zip)

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by JPTGamesAndApps** [comment]
The sample crashes in 21H1 as well.
