### ISSUE TITLE
[Preview 4] XamlTypesInfo.g.cs shouldn't warn CS8305

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#4187]
I have a project updated from Preview 3 to Preview 4. The generated `XamlTypesInfo.g.cs` references `ElementAnimator`, thus causing C# compiler warning CS8305 about `Experimental`.

Since I'm not actively using `ElementAnimator` anywhere, I shouldn't get a warning about it. `XamlTypesInfo.g.cs` should generate `#pragma warning disable` for it.

**Comment by MikeHillberg** [comment]
@huoyaoyuan, I think that's a good idea. Fyi @stevenbrix.
