### ISSUE TITLE
Add padding for content and commands inside the command bar

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#4188]
The new styles have padding for AppBarButton but not for the command bar itself so the last button feels weird as others have space but not the last one. Consider adding left and right padding for the command bar.

**Comment by StephenLPeters** [comment]
@Jaiganeshkumaran Thanks for the feedback, could you please attach a screenshot to help with the description of the issue?

**Comment by Jaiganeshkumaran** [comment]
![2021-02-27 (1)](https://user-images.githubusercontent.com/45227503/109374840-46c01b80-78de-11eb-9f00-84d1b79178e4.png)
Now app bar buttons have rounded corners however there's no space in between which is against the guidelines which say there shouldn't be a rounded corner when there's no space in between.
![2021-02-27 (3)](https://user-images.githubusercontent.com/45227503/109374903-afa79380-78de-11eb-8fab-080cf04afc20.png)
The overflow "more button" has some margin but other buttons don't have it.

**Comment by StephenLPeters** [comment]
@teaP I know there were some recent changes, thoughts on this?

**Comment by teaP** [comment]
> @teaP I know there were some recent changes, thoughts on this?

Yes, I will fix it. My test page didn't have any examples without the ... button, but I just discovered this issue on CommandBarFlyout as well and I'll apply the same fix.

**Comment by ranjeshj** [comment]
@teaP Is this already resolved with your changes ?

**Comment by teaP** [comment]
It's not in yet, it's rolled into https://github.com/microsoft/microsoft-ui-xaml/pull/4532.
