### ISSUE TITLE
High Contrast PointerOver and Pressed colors do not work in HyperlinkButton

### ISSUE THREAD

**Issue by dannyp32** [microsoft/microsoft-ui-xaml#419]
**Describe the bug**

When I have a textblock inside of a hyperlink button in high contrast mode, the color doesn't change when I hover over it or click on it.

        <HyperlinkButton>
            <TextBlock Text="hello"></TextBlock>
        </HyperlinkButton>

**Expected behavior**

PointerOver and Pressed states should change the color of the text in high contrast mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/921928/54304396-48be3200-4582-11e9-8d7a-52f54d3014b7.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Does it work if you don't use TextBlock but just set `<HyperlinkButton Content="hello"/>`?

**Comment by jevansaks** [comment]
Nevermind, I set up the repro and see it for both. Very odd. We'll take a look.

**Comment by jevansaks** [comment]
We also had an [internal issue](https://microsoft.visualstudio.com/OS/_workitems/edit/19322324) tracking this as well.

**Comment by chingucoding** [comment]
I think this issue can only be adressed with WinUI 3.0, since the HyperlinkButton has no files in the WinUI repository currently.
