### ISSUE TITLE
[Preview 4] UI elements are resized when the window of a win32 app is minimized

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#4190]
**Describe the bug**

When a window is minimized, all UI elements are resized (in most cases to 0). This only happens for win32 apps and not for UWP apps. This can lead to undesired effects, e.g. the position of scroll viewers might be changed once the window is restored.

**Steps to reproduce the bug**

1. Create a blank win32 and UWP winui 3 app
2. Subscribe to the SizeChanged event of the top UI element
3. Minimize the windows and observe that the win32 app receives the SizeChanged event, but the UWP one does not

**Expected behavior**

The UI elements should not be resized when a window is minimized

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No| Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by marb2000** [comment]
@lhak, I agree about the SizeChanged.  An app shouldn't unnecessarily re-do layout when minimizing, and redo-it again when restoring for performance's sake. **The Window object shouldn't report a new size (SizeChanged) when the window is minimized.** 

Note: Those are the events fired today in WinUI 3 when changing the window size:

--- | WinUI 3 UWP | WinUI 3 Desktop 
----- |----- | ---------
Restore to Maximize  | Window.SizeChanged (max) + XamlRoot.Changed  | SAME
Maximize to Restore |  Window.SizeChanged (restore) + XamlRoot.Changed | SAME
Restore to Minimize | Window.VisibilityChanged + XamlRoot.Changed | Window.SizeChanged (0) +               Window.VisibilityChanged + XamlRoot.Changed
Minimize to Restore | Window.VisibilityChanged + XamlRoot.Changed | Window.SizeChanged (restored) +               Window.VisibilityChanged + XamlRoot.Changed
Maximize to Minimize | Window.SizeChanged (max) + XamlRoot.Changed + Window.VisibilityChanged |               Window.SizeChanged (0) + Window.VisibilityChanged + XamlRoot.Changed
Minimize to Maximize | Window.SizeChanged (max) + XamlRoot.Changed + Window.VisibilityChanged | SAME

**Comment by codendone** [comment]
This is fixed in Project Reunion 0.5.5, which was released last Friday.
