### ISSUE TITLE
[Preview 4] Blank window background is visible before content is shown

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#4191]
**Describe the bug**

When an application is launched, the window shows a blank white background until the XAML content is rendered. This is especially noticable when the content is dark (e.g. dark theme is selected). A workaround requires a manual handling of the WM_ERASEBKGND message.

**Steps to reproduce the bug**

1. Create a blank win32 winui app
2. Set the RequestedTheme of the application to Dark
3. Launch the app and notice that the white window background is visible for a short time

**Expected behavior**

The window should be shown once the content is rendered. Alternatively, a property could be added to the Window class to set it background color.

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@bartekk8 might have an idea if this is performance related. @codendone FYI

**Comment by pratikone** [comment]
in my understanding, this has been fixed. I fixed it.  do open this up if it shows up again.
