### ISSUE TITLE
RadioButtons Up and Down keyboard navigationnot working

### ISSUE THREAD

**Issue by bridgesquared** [microsoft/microsoft-ui-xaml#4194]
**Describe the bug**
When a RadioButtons control is focused, the user cannot use the Up and Down keys to change the selected item, whilst the Left and Right keys work within the current row.

**Steps to reproduce the bug**
1. Create a WinUI for Desktop solution (Preview 4 used).
2. Declare a RadioButtons control on the MainWindow, constrain max columns.
3. Add multiple RadioButton elements.

``` xaml
    <RadioButtons HorizontalAlignment="Center"
                  VerticalAlignment="Center"
                  MaxColumns="3">
        <RadioButtons.Items>
            <RadioButton Content="Red" />
            <RadioButton Content="Blue" />
            <RadioButton Content="Green" />
            <RadioButton Content="Cyan" />
            <RadioButton Content="Magenta" />
            <RadioButton Content="Yellow" />
            <RadioButton Content="Black" />
        </RadioButtons.Items>
    </RadioButtons>
```

4. Run the app and try keyboard navigation of the radio buttons using the arrow keys, left/right work, up/down don't :-(

**Expected behavior**
The user should be able to navigate the RadioButtons control using all four arrow keys

**Screenshots**
![image](https://user-images.githubusercontent.com/11475368/107965375-5ec0a280-6fa2-11eb-86e3-f421ab33d0f3.png)

**Version Info**

NuGet package version: 

`    <PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview4.210210.4" />`

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
This issue has been fixed but it was not in time for the preview 4 release.
