### ISSUE TITLE
[Preview 4] Change in Appearance of AppBarButton with Flyout on CommandBar in WinUI3 

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#4197]
**Describe the bug**

We used a CommandBar with AppBarButton with a Flyout in our UWP application. However, once we switched over to WinUI3 Preview 4 Desktop, the appearance of the button changed. 

The button in the WinUI3 Preview4 application has a ">" next to the icon whereas the UWP application did not. 

See Screenshots below to compare differences.

**Steps to reproduce the bug**
1. Clone the [WinUI3 Problems CommandBarFlyout repository](https://github.com/eleanorleffler/WinUI3Preview4_Problems_CommandBarFlyout).
2. Go to the CommandBarFlyoutWinUIPreview4 folder.
3. Open the CommandBarFlyoutWinUIPreview4 solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Notice the additional ">" next to the first icon in the CommandBar on the right side of the application.

**Expected behavior**

We expect to see no difference in appearance in the UWP and WinUI3 Preview 4 Desktop CommandBar buttons. The button in the WinUI3 Preview 4 Desktop application should only be the AppBarButton icon.

Build and run the CommandBarFlyoutUWP inside the CommandBarFlyoutUWP folder to see expected behavior.

**Screenshots**

![ExpectedBehavior](https://user-images.githubusercontent.com/9272634/107985183-35e2e200-6f8f-11eb-9063-2e8710905c6c.png)

Screenshot#1 - Expected Appearance (UWP)

![CurrentBehavior](https://user-images.githubusercontent.com/9272634/107985157-26fc2f80-6f8f-11eb-9b9c-6830bf6ea346.PNG)

Screenshot#2 - Current Appearance (WinUI3 Desktop)

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Targeting:
Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1803 (10.0; Build 17134)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| 		Yes 	   |  				  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

**Comment by StephenLPeters** [comment]
In winui2 there is a bug where this chevron appears for app bar buttons which have attached flyouts, but only when they are not in command bar's primary commands. It seems like this issue is that command bar is failing to apply its custom style to this app bar button.

**Comment by anawishnoff** [comment]
This bug has been fixed in WinUI 3 in the upcoming Project Reunion 0.8 Preview, which you can expect within the next few days. Thanks for filing this!
