### ISSUE TITLE
[Win-UI] : Not able to add the background tasks Windows.ApplicationModel.Background.IBackgroundTask

### ISSUE THREAD

**Issue by MoueenShaik** [microsoft/microsoft-ui-xaml#4200]
**Describe the bug**
I am trying to add BackgroundTasks which is a type of Windows.ApplicationModel.Background.IBackgroundTask as per the below Microsoft doc in WINUI
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-a-background-task

To achieve my requirement, added the background tasks under the declaration tab in the  Package.appmanifest.

![image](https://user-images.githubusercontent.com/47388795/108002785-85340d00-6fa5-11eb-9264-c027569d9d45.png)
![image](https://user-images.githubusercontent.com/47388795/108002847-b44a7e80-6fa5-11eb-85d8-9bc46076f63b.png)

After adding the background tasks and tried to build the solution but unfortunately, I am getting the below exception.
![image](https://user-images.githubusercontent.com/47388795/108002985-130ff800-6fa6-11eb-8f13-62fffa5dd431.png)
To fix the above issue one of the technical forum suggested that adding an audio task will get resolved.
Adding an audio task to the package.manifest file, build issue got resolved, But when I launch the application getting the below exception

![image](https://user-images.githubusercontent.com/47388795/108003264-13f55980-6fa7-11eb-8192-c1c5de960f8a.png)

FYI :
Visual Studio version: Visual Studio Enterprise 2019 Preview - 16.7.30128.36
.Net SDK : Microsoft .NET SDK 5.0.100-preview.5.20279.10(x86)
WinUIVersion : 3.0.0-preview2.200713.0
csproject: 
![image](https://user-images.githubusercontent.com/47388795/108003448-bad9f580-6fa7-11eb-94da-ae38502850bd.png)

**Steps to reproduce the bug**

1. Create a new Blank app packaged,(WINUI in Desktop) 
2. Add a new class with inherit from IBackgroundTask
3. Add background-tasks to the package.Manifest under declaration tab.
4. Build the solution.

**Expected behavior**
Application should build/run 

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

Could you please guide/help me on how to add background tasks in winUI desktop application without exceptions? and let me know if you need any other details from my end.

Thanks & regards,
Moueen Shaik

**Comment by StephenLPeters** [comment]
Can you please first try upating your Winui3 version from Preview 2 to Preview 4?

**Comment by shahidjaved** [comment]
You can try adding another Extention tag in Package manifest file. like below and it should work as i was having same issue and it worked for me.
	
      <Extensions>
		  <Extension Category="windows.backgroundTasks" EntryPoint="App.Backgrounds.NotificationBackgroundTask"  xmlns:a="http://schemas.microsoft.com/appx/manifest/uap/windows10/10">
		   <BackgroundTasks>
			   <Task Type="pushNotification"/>
          </BackgroundTasks>
        </Extension>
	  </Extensions>
    </Application>
  </Applications>

  <Capabilities>
    <Capability Name="internetClient" />
    <rescap:Capability Name="runFullTrust" />
  </Capabilities>
	<Extensions>
		<Extension Category="windows.activatableClass.inProcessServer" >
			<InProcessServer>
				<Path>App.dll</Path>
				<ActivatableClass ActivatableClassId="AppBackgrounds.NotificationBackgroundTask" ThreadingModel="both" />
			</InProcessServer>
		</Extension>
	</Extensions>
</Package>

**Comment by shahidjaved** [comment]
You can try adding another extentisions tag in Package manifest file. like below image it is working for me.
![image](https://user-images.githubusercontent.com/5259731/144253250-7d0e89a0-a2f9-42be-80c9-57d3d42542a3.png)

**Comment by LaoR-UA** [comment]
> You can try adding another extentisions tag in Package manifest file. like below image it is working for me. ![image](https://user-images.githubusercontent.com/5259731/144253250-7d0e89a0-a2f9-42be-80c9-57d3d42542a3.png)

Thanks. Just need to set a specific DLL, like in the example: https://github.com/microsoft/WindowsAppSDK-Samples/blob/8393a02f0308696246607e157326e87fb04af4d8/Samples/BackgroundTask/OutOfProc%20BackgroundTask/cs-winui/BackgroundTaskBuilder/Package.appxmanifest
