### ISSUE TITLE
VisualStateManager fail on initialization on Project Reunion 0.5.7

### ISSUE THREAD

**Issue by mvegaca** [microsoft/microsoft-ui-xaml#4207]
**Describe the bug**
Hello

I think there is an issue on VisualStateManager initialization. AdaptiveTrigger works when I resize the app but is not working on visual state initialization.

I've created this minimum repro app
[VisualStateManagerIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5988637/VisualStateManagerIssue.zip)

**Steps to reproduce the bug**
1. Launch the app
2. Navigate to Second page using the NavigationView
3. Try resizing the app and observe how the text is updated for narrow and wide window modes.
4. Come back to the first page using back button
5. Reduce the window size to narrow mode (hiding the navigationview pane).
6. Navigate to SecondPage

**Expected behavior**
The second page should show "narrow" but it shows "WIDE".

**Screenshots**

**Resize to wide**

![image](https://user-images.githubusercontent.com/5556784/108064821-7e68d100-705d-11eb-9956-df799b9d3e57.png)

**Resize to narrow**

![image](https://user-images.githubusercontent.com/5556784/108064834-8294ee80-705d-11eb-9b97-931470f84636.png)

**Navigate to second page in narrow mode**

![image](https://user-images.githubusercontent.com/5556784/108064852-87f23900-705d-11eb-88da-95bdd30db0c4.png)

**Comment by chrisglein** [comment]
@mvegaca Just for confirmation did this stop working with preview4 and work on earlier previews, or did it stop working for you with WinUI3?

**Comment by mvegaca** [comment]
Hi @chrisglein
I'm not 100% sure but I think this didn't happen on Preview 3.

**Comment by sibille** [comment]
This issue is still happening after updating to Project Reunion 0.5 Preview

**Comment by sibille** [comment]
This is still happening after update to project reunion version 0.5.6 and affects our ListDetail page in narrow mode:
![image](https://user-images.githubusercontent.com/24698018/117415054-2765f000-af18-11eb-9cdc-cd93fdd3cfb9.png)

**Comment by mvegaca** [comment]
Hi Team!

Do you have any updates here?

**Comment by sibille** [comment]
This is still happening after updating to Project Reunion 0.8
