### ISSUE TITLE
[Preview 4] Window Buttons Removed when using ExtendsContentIntoTitleBar in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#4209]
**Describe the bug**

In WinUI3 Preview4, using the "ExtendsContentIntoTitleBar" removes the standard action buttons on the window (minimize, maximize, and close).

**Steps to reproduce the bug**
1. Clone the [WinUI3 Preview 4 Problems Set Title Bar repository](https://github.com/eleanorleffler/WinUI3Preview4_Problems_SetTitleBar).
2. Go to the SetTitleBarWinUIPreview4 folder.
3. Open the SetTitleBarWinUIPreview4 solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Click the "Set Title Bar On" / "Set Title Bar Off" button to update the window's Title Bar using the "ExtendsContentIntoTitleBar" and "SetTitleBar" methods.

**Expected behavior**

We expect there to be a programmatic way to customize the Title Bar and for the customization to keep the standard window buttons.

**Screenshots**

![SetTitleBarOff](https://user-images.githubusercontent.com/9272634/108078463-56fd0e80-7033-11eb-8a32-8d77ea431340.PNG)

![SetTitleBarExtended](https://user-images.githubusercontent.com/9272634/108078474-5b292c00-7033-11eb-9665-0bf3217423c4.PNG)

Current Behavior

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Targeting:
Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1803 (10.0; Build 17134)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| 		Yes 	   |  				  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

**Comment by StephenLPeters** [comment]
@pratikone and @Austin-Lamb FYI

**Comment by marb2000** [comment]
Adding @pratikone for awareness.

There is clearly a layout issue with the Window captions Buttons and the Grid. I can repro this bug and it do believe it should work.

**Comment by MarcMenghin** [comment]
Same problem here. Setting a Padding reveales the missing Buttons (and makes them usable). Making the header UI element transparent reveals them as well (but no interaction possible).

So they are underneath the UI constrols from XAML.. Looks like a zIndex like issue to me.

**Comment by codendone** [comment]
Collapsing this down to one issue and keeping #4835 as the one to track, since that has the more recent sample.

**Comment by Wufus** [comment]
A workaround is described here [#4166](https://github.com/microsoft/microsoft-ui-xaml/issues/4166#issuecomment-780832725)
But, bugs still exist. As non-draggable area at the top, bottom and right of `MinMaxCloseContainer`
