### ISSUE TITLE
Question: Rendering SVG from string, not file/stream

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#4212]
Suppose you have a string like this: `<svg height="100" width="100"><circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" /></svg>`.

What ways are there to render this without having to write it into a stream or file? There is [Path.Data](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.shapes.path.data?view=winrt-19041) which can take a string, however it only supports the shorthand form.

Edit: GitHub doesn't seem to like having SVG code in quotation marks.

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by codendone** [comment]
With current XAML functionality, the only easy option is put it in a stream so you can use SvgImageSource.SetSourceAsync(stream). As you said, Path supports some functionality, but is very limited compared to SVG.
