### ISSUE TITLE
Dispatcher is null in WinUI Desktop in WinUI 3 Preview 4

### ISSUE THREAD

**Issue by Berkunath** [microsoft/microsoft-ui-xaml#4219]
Dispatcher of Page and other UI elements are return null in WinUI Desktop after upgrade of WinUI 3 Preview 4. We have to run async using Dispatcher. But Dispatcher returns null in WinUI Desktop but WinUI UWP returns proper value for Dispatcher. It works fine in WinUI 3 Preview3

`await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () =>
                    {
// My Action here
                    });`

**Expected behavior**
Dispatcher should not be null or sugestion to Runasync

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

**Comment by marb2000** [comment]
@Berkunath Dispatcher and CoreDisptacher are null in the Preview 4.  You should use DispatcherQueue instead.
[Here](https://github.com/microsoft/WinUI-3-Demos/tree/master/src/WinUI3_Visual_Sorting_Items_Demo/SortingItemsWinUI3Demo) you can find a demo that uses it.

**Comment by nickrandolph** [comment]
@marb2000 is there a reason why Dispatcher and CoreDispatcher are null? This seems to be an unnecessary breaking change for existing UWP style code?

**Comment by StephenLPeters** [comment]
Winui3 doesn't have a core window and Dispatcher and COreDispather both relied on CoreWindow.  Thus these APIs are no longer sufficient for the winui3 app model, DispatcherQueue is their replacement.

**Comment by fiftin** [comment]
Why Dispatcher was not marked as Deprecated?

I spent a lot of time until find this issue

**Comment by Slion** [comment]
Here is what it looks like now:

```C#
_ = DispatcherQueue.TryEnqueue(() => DoYourThing());
```

**Comment by krschau** [comment]
This, and other similar APIs, are outlined here: [Windows Runtime APIs not supported in desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api)

**Comment by DRAirey1** [comment]
DispatcherQueue is null in my WinUI application.

    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240829007" />

**Comment by hdkesting** [comment]
After an attempt to upgrade a 4.8 UWP app to NET9 I got comments in the code:

>   // TODO Windows.UI.Core.CoreDispatcher is not longer supported. For more details see https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/threading

That link at least shows some details (still working on it...)
