### ISSUE TITLE
Include test setup errors in AzDO log snippet

### ISSUE THREAD

**Issue by kaiguo** [microsoft/microsoft-ui-xaml#422]
We currently don't show test setup errors in the log snippet, those errors should be included too to make logs more useful.

Need to update ConvertWttLogToXUnit.cs to include setup errors.

**Comment by jevansaks** [comment]
Do you have any details for future us about _how_ to do this? :)

**Comment by kaiguo** [comment]
> Do you have any details for future us about _how_ to do this? :)

Yep I updated the issue description.

**Comment by kmahone** [comment]
The work to make it easy to get to the full console logs from the test execution should solve this issue. Even if the error does not show up directly in AzDO, it is easy to get to it.
