### ISSUE TITLE
Compact mode sizing not applied for CheckBox control

### ISSUE THREAD

**Issue by susmitha-sundar** [microsoft/microsoft-ui-xaml#4220]
**Describe the bug**

Compact mode sizing not applied for CheckBox control after added the Compact.xaml resource dictionary. But its working for TextBox and ComboBox control.

**Steps to reproduce the bug**

1. Run the attached sample.

**Expected behavior**

CheckBox size should be decreased.

**Screenshots**
Standard size:

![image](https://user-images.githubusercontent.com/60175573/108182035-99574600-712e-11eb-806e-65efb7c3463d.png)

Compact size:

![image](https://user-images.githubusercontent.com/60175573/108182277-d7ed0080-712e-11eb-9d48-cb451779905a.png)

**Version Info**

Windows 10

NuGet package version: 

Microsoft.WinUI 3.0.0-preview4.210210.4

**Additional context**

Sample: 
[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5994587/App1.zip)

**Comment by StephenLPeters** [comment]
This is because Compact.xaml doesn't include any checkbox updates.

**Comment by susmitha-sundar** [comment]
Thank you for the update.

Have further plan to implement the compact mode sizing for CheckBox?

**Comment by ranjeshj** [comment]
No, that is currently not planned. Thanks.

**Comment by mdtauk** [comment]
> Thank you for the update.
> 
> Have further plan to implement the compact mode sizing for CheckBox?

The checkbox is already 20 x 20 epx in size, the compact sizing changes the larger elements like Buttons, TextBoxes etc, which use 32px heights with standard scaling.
