### ISSUE TITLE
CheckBox control's check box size not changed

### ISSUE THREAD

**Issue by susmitha-sundar** [microsoft/microsoft-ui-xaml#4221]
**Describe the bug**

CheckBox control's check box size not changed with different size. CheckBox control's content only clipped.

**Steps to reproduce the bug**

1. Run the attached sample.

**Expected behavior**

CheckBox control's check box size should varied based on width and height.

**Screenshots**

![image](https://user-images.githubusercontent.com/60175573/108189243-89436480-7136-11eb-93dc-1bbe9e6a4256.png)

**Version Info**

OS: Windows 10

NuGet package version: 

Microsoft.WinUI 3.0.0-preview4.210210.4

**Additional context**

Sample link: 
[CheckBox_Size.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5994884/CheckBox_Size.zip)

**Comment by mdtauk** [comment]
That's not how the control is designed, the area around the control resizes, giving more space to the text.

There should be light weight style Resources you can change to assist the size of the actual box and it's checkmark however.

Something like Xbox should be able to change it without re-templating the control

**Comment by StephenLPeters** [comment]
Thats right, you can change the checkbox square size by overriding this resource: https://github.com/microsoft/microsoft-ui-xaml/blob/cbbc626314436b24ae3c73fe33ad9b475ce31cb1/dev/CheckBox/CheckBox_themeresources.xaml#L361

**Comment by SongOfYouth** [comment]
@StephenLPeters Why has this function removed now?
