### ISSUE TITLE
<muxc:ItemsRepeater ItemsSource="{x:Bind IDictionary}">

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4222]
`<muxc:ItemsRepeater ItemsSource="{x:Bind Dictionary}">`

Is items repeater supposed to work with IDictionary as item source ? Shows nothing, however I replace the property type with IEnumerable and the same code iterates the values.

**Comment by StephenLPeters** [comment]
What exact type is your Dictionary in your x:bind? the .net dictionary is IEnumerable so I think it should work.

**Comment by StephenLPeters** [comment]
Here is the code to the supported interfaces: https://github.com/microsoft/microsoft-ui-xaml/blob/cbbc626314436b24ae3c73fe33ad9b475ce31cb1/dev/Repeater/InspectingDataSource.cpp#L12

**Comment by sigmarsson** [comment]
Yeah, cool. `IDictionary `is itself an `IEnumerable `thats why I expected to have it done through an `ItemsRepeater`.
This xaml snippet was migrated from an WPF and even the Key and Value properties could not have been located. Strange, I opted for an `IEnumerable<MyKeyValueClass>`, since specifying generic data types in `x:DataType` isn't possible.

**Comment by StephenLPeters** [comment]
Does the provided code link give you the information you need to get unblocked?

**Comment by sigmarsson** [comment]
Well, still dont understand why `Key` and `Value` properties weren't available in my sepcific `DataTemplete `while iterating through my `Dictionary ` but forged a workaround by implementing my own `KeyValue `class.
