### ISSUE TITLE
RichTextBlock text shifts when lines are added

### ISSUE THREAD

**Issue by rick-palmsens** [microsoft/microsoft-ui-xaml#4223]
**Describe the bug**
I have a `RichTextBlock` to which I add text from code behind using `Paragraph` and `Run`. Whenever the text that has been added results in a new line, it also causes the earlier lines to shift visually.

Whether I use a single `Paragraph` with multiple `Run` or multiple `Paragraph` with a single `Run` does not seem to matter for this bug. 

**Steps to reproduce the bug**
1. Create a `RichTextBlock`
2. Every second add a new `Paragraph` with some text
3. Watch the existing lines shift every time a new `Paragraph` is added

**Expected behavior**
The existing lines are not modified in any way and should remain stationary when text is added.

**Screenshots**
![textboxbug](https://user-images.githubusercontent.com/57390463/108198548-0f05e680-711c-11eb-954b-6776261d4904.gif)

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-preview4.210210.4

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by codendone** [comment]
This also repros in system UWP XAML, even with the simpler TextBlock running in its fast path mode. I agree it is odd, but it seems something in the text system is doing measure/layout in the context of all of the text. This is likely not something which will be fixed anytime soon.

**Comment by rick-palmsens** [comment]
> This is likely not something which will be fixed anytime soon.

Typesetting is quite fundamental for a good looking UI. And right now it is broken. While I understand that it is not a showstopper for a lot of applications, I don't see why it would be given the "basically never" severity either.
