### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#4224]
How do we switch to fullscreen mode?

**Comment by marb2000** [comment]
@Gavin-Williams, the UWP's ApplicationView.TryEnterFullScreenMode Method is not supported in WinUI 3 in Desktop, and currently there is not WinUI 3 API that does that. You should use Win32 APIs instead.

**Comment by Gavin-Williams** [comment]
I don't understand. I'm using .Net 5 + WinUI - Surely there must be a WinRT way to switch an app to fullscreen? It's basic app behaviour. Are you saying I have to call into the classic C API's and manually hide the taskbar and titlebar? I just don't understand what you mean.

**Comment by marb2000** [comment]
Sad but true @Gavin-Williams, you have to call classic C flats APIs. At this moment I don't know when this funtionality will be available. I'm working with @rkarman (who owns non-WinUI windowing APIs) to figure out what we can accomplish from the engineering standpoint. @rkarmanm, feel free to chime in, please.

**Comment by Gavin-Williams** [comment]
Is there some documentation on using the legacy API's with .Net 5? My searches bring stuff up from 2006-2010 but nothing related to .Net 5. I've found some C code to switch to fullscreen, but frankly it looks pretty bad. How do I use it in .Net ?

**Comment by rkarman** [comment]
> Surely there must be a WinRT way to switch an app to fullscreen?

Alas there is not. 😄  There's UWP WinRT APIs specifically for [ApplicationView](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.tryenterfullscreenmode?view=winrt-19041) and [AppWindow](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindowpresenter.requestpresentation?view=winrt-19041), and then there is @oldnewthing's "[blogpost that everyone writing Win32 apps copies](https://devblogs.microsoft.com/oldnewthing/20100412-00/?p=14353)".

However, as @marb2000 is saying above, we are working on bringing a set of windowing APIs to Reunion (WinRT APIs) that will enable this functionality and also looking at what the right level of integration with WinUI3 is for that.

**Comment by Gavin-Williams** [comment]
OK, cool. 

I hope the new API mirrors the UWP way of doing it - borderless window full screen - it's so much better than exclusive! Just being able to switch to desktop or another app instantly and without requiring a device reset is perfect. I'm not sure if Windows does this now anyway across all app types, I have a vague memory that it might do now.

With regard to plopping C code for full screen switching into my project, any recommendation on how I go about it:

A) Add a C++ library project to my solution and build any C functions there, using pinvoke to get them from C#?
B) Look for .Net 5 Win32 libraries that provides all this classic functionality wrapped up?
C) Look at third party libraries like TerraFX that provide wrapped C code from classic C era windows?
D) Use C++/WinRT?

**Comment by Jaiganeshkumaran** [comment]
It would be nice to have Windows+Shift+Enter shortcut for full screen in all WinUI desktop apps

**Comment by oldnewthing** [comment]
I don't think unilaterally going full screen the sort of thing the framework should be doing without the app's permission. Would only the island go full screen, and the non-WinUI app content just disappears? What if the app has multiple islands? Do they somehow negotiate to share the full screen equitably?

**Comment by BitCrusader** [comment]
> I don't think unilaterally going full screen the sort of thing the framework should be doing without the app's permission. Would only the island go full screen, and the non-WinUI app content just disappears? What if the app has multiple islands? Do they somehow negotiate to share the full screen equitably?

It would obviously be part of the Window class, which is not used with XAML Islands.

**Comment by rkarman** [comment]
An update to this. With the 1.0 version of Windows App SDK there is now a WinRT API for switching a window into/out of full screen - see the [FullScreenPresenter](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.fullscreenpresenter?view=windows-app-sdk-1.0) for [AppWindow](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow?view=windows-app-sdk-1.0). The AppWindow [samples](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing) show how to enter/exit different presenters.

Next step for this feature request is of course to have the WinUI Window object provide a method that makes this even easier for you (Window.IsFullScreen = true/false ? ). Please hassle @marb2000 about it, I know I will... :smile:

**Comment by tom-huntington** [comment]
@rkarman I accidentally got WinUI to go full-screen exclusive by calling DirectX (instead of my second win32 window).

Everything seemed to work okay except that that the resolution was stretched. However, I assume `SwapChainPanel` won't work without DWM.

This is a pity, since my constant frame rate app works a lot better in full-screen exclusive (DwmGetCompositionTimingInfo doesn't even give the actual refresh rate).

**Comment by Panchus** [comment]
> An update to this. With the 1.0 version of Windows App SDK there is now a WinRT API for switching a window into/out of full screen - see the [FullScreenPresenter](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.fullscreenpresenter?view=windows-app-sdk-1.0) for [AppWindow](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow?view=windows-app-sdk-1.0). The AppWindow [samples](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing) show how to enter/exit different presenters.
> 
> Next step for this feature request is of course to have the WinUI Window object provide a method that makes this even easier for you (Window.IsFullScreen = true/false ? ). Please hassle @marb2000 about it, I know I will... 😄

For those looking for a quick code snippet of this, I would humbly submit:

```
using WinRT.Interop;
using Microsoft.UI.Windowing;

// public sealed partial class MainWindow : Window

private void myButton_Click(object sender, RoutedEventArgs e)
{
    var windowHandle = WindowNative.GetWindowHandle(this);
    var windowId = Win32Interop.GetWindowIdFromWindow(windowHandle);
    var appWindow = AppWindow.GetFromWindowId(windowId);
    appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
}
```

**Comment by Panchus** [comment]
> > An update to this. With the 1.0 version of Windows App SDK there is now a WinRT API for switching a window into/out of full screen - see the [FullScreenPresenter](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.fullscreenpresenter?view=windows-app-sdk-1.0) for [AppWindow](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow?view=windows-app-sdk-1.0). The AppWindow [samples](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing) show how to enter/exit different presenters.
> > Next step for this feature request is of course to have the WinUI Window object provide a method that makes this even easier for you (Window.IsFullScreen = true/false ? ). Please hassle @marb2000 about it, I know I will... 😄
> 
> For those looking for a quick code snippet of this, I would humbly submit:
> 
> ```
> using WinRT.Interop;
> using Microsoft.UI.Windowing;
> 
> // public sealed partial class MainWindow : Window
> 
> private void myButton_Click(object sender, RoutedEventArgs e)
> {
>     var windowHandle = WindowNative.GetWindowHandle(this);
>     var windowId = Win32Interop.GetWindowIdFromWindow(windowHandle);
>     var appWindow = AppWindow.GetFromWindowId(windowId);
>     appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
> }
> ```

I must point out that doing this just at the start of an application, for example after calling mainWindow.Activate() on App.xaml.cs, makes the window content not quite the same size, it doesn't align with the whole screen leaving a few pixels at the bottom and right margin

I managed to circumvent this doing the following little hack:

```
appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
await Task.Delay(250);
appWindow.SetPresenter(AppWindowPresenterKind.Default);
appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
```

Meaning, it seems it is necessary to force a kind of toggle from fullscreen to overlapped or default and back again for it to render the window contents correctly, hopefully this gets fixed or maybe its just me
I'm running a WinUI app with AppSDK 1.0 and .net 6

**Comment by rkarman** [comment]
> I must point out that doing this just at the start of an application, for example after calling mainWindow.Activate() on App.xaml.cs, makes the window content not quite the same size, it doesn't align with the whole screen leaving a few pixels at the bottom and right margin

This is a known bug and we're tracking it in the WinAppSDK project as issue [#1853](https://github.com/microsoft/WindowsAppSDK/issues/1853).

**Comment by crozone** [comment]
```
var windowHandle = WindowNative.GetWindowHandle(this);
var windowId = Win32Interop.GetWindowIdFromWindow(windowHandle);
var appWindow = AppWindow.GetFromWindowId(windowId);
appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
```

This works well now.

However I'm pretty surprised that this conversion through native window handles is even required. Surely there should be a built-in method for getting from `Microsoft.UI.Xaml.Window` -> `Microsoft.UI.Windowing.AppWindow`?

Grabbing a native handle, so you can get a window ID, so you can get an app window, just to set the presenter mode is a lot of hoops to jump through just to set the app to full screen mode.

**Comment by rkarman** [comment]
We are working on providing a tighter integration between the WinUI Window and the AppWindow class so you don't have to go through all the interop hops to get there. @MikeHillberg is driving this on the WinUI side.

**Comment by Gavin-Williams** [comment]
I'll close this issue. Things are improved with regard to API support. And personally, I'm setup now to use Win32 which provides fullscreen capability.
