### ISSUE TITLE
CoreWindow.GetForCurrentThread() is return null in WinUI Desktop after Upgrade of WinUI 3 Preview 4

### ISSUE THREAD

**Issue by Berkunath** [microsoft/microsoft-ui-xaml#4225]
We have get the PointerCursor, PointerPosition and GetKeystates from the CoreWindow.GetForCurrentThread(). It works fine in WinUI 3 Preview 3. After upgrade of WinUI 3 Preview 4 CoreWindow.GetForCurrentThread() returns null

**Expected behavior**
CoreWindow.GetForCurrentThread() return proper value to get the PointerCursor, PointerPosition and GetKeyStates or suggest alternate solutions

NuGet package version: 
<!-- 
Examples
[Microsoft.WinUI 3.0.0-preview4.210210.4]

**Comment by StephenLPeters** [comment]
This is expected as of preview 4.  @anawishnoff do we have documentation for this?

**Comment by anawishnoff** [comment]
Yes, please see this doc that outlines some replacements and workarounds for this issue: [WinRT API changes for Desktop apps](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/winrt-apis-for-desktop.md)

**Comment by DRAirey1** [comment]
This is the problem I'm having. anawishnoff, your link send us to a dead page. How about just posting the work-around so we don't have to waste any more time with these changes. It's hard enough as it is to upgrade.
