### ISSUE TITLE
DisplayInformation exception in WinUI3 preview4

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4228]
Since preview 4 the following code is throwing an exception

`Windows.Graphics.Display.DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel`

>Element not found. (0x80070490)
>at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)

Is this a bug, or is there any way round?

**Comment by marb2000** [comment]
DisplayInformation.GetForCurrentView() is no longer supported in WinUI 3 in Desktop. You should use [XamlRoot's RasterizationScale](
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.xamlroot.rasterizationscale?view=winrt-19041#Windows_UI_Xaml_XamlRoot_RasterizationScale)

**Comment by maxkatz6** [comment]
Will those unsupported classes removed from public API?

**Comment by marb2000** [comment]
Some APIs belong to WinUI and Reunion projects (e.g. Microsoft.*), others belong to the UWP Platform that ships with the Windows 10 OS. For example, the Windows.Graphics.Display.DisplayInformation works well in UWP apps. We can't remove these APIs. But we do plan to remove the WinUI APIs that don't work from the supported versions (e.g. Reunion 0.5). For example, given Reunion 0.5 will support only WinUI 3 in Desktop, we should remove the Dispatcher,CoreDispatcher, Current, and CoreWindow properties from the Microsoft.UI.Xaml.Window class. Does this make sense to you?

**Comment by sigmarsson** [comment]
@marb2000  How shall I access the current view `DisplayInformation.GetForCurrentView()` is deprecated ?

![image](https://user-images.githubusercontent.com/43340959/108525223-2554a380-72d0-11eb-9cf0-4e18a0f0cdab.png)

**Comment by BorzillaR** [comment]
@marb2000, is there suggested replacement for [DisplayInformation.ScreenHeightInRawPixels](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.screenheightinrawpixels?view=winrt-19041) property?

**Comment by krschau** [comment]
@sigmarsson The answer depends on what you needed the current view for. For the TitleBar in your example, does this help?
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0

More generally, hopefully the answer can be found in this list:
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#classes-with-getforcurrentview-methods

If you're having concerns and this doesn't address them, please open a new issue.

**Comment by krschau** [comment]
@BorzillaR If you want to get monitor info to replace ScreenHeightInRawPixels, you can try using [MonitorFromWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfromwindow) to get the HMONITOR and plug that into [GetMonitorInfoW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfow).

If this doesn't work for what you need, please open a new issue and we'll get it sorted out.
