### ISSUE TITLE
PropertyChanged.Fody ? 

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4229]
Is is possible to harness the Nuget package `PropertyChanged.Fody` to have property notification on the fly ?

**Comment by StephenLPeters** [comment]
@sigmarsson can you provide more information? I'm not sure what the question is.

**Comment by sigmarsson** [comment]
I utilized this package in one of my former WPF application, it injects code at property setters so you needn't do this silly duty. 
[Fody](https://github.com/Fody/PropertyChanged)
Do you think it would just work even with the new `<x:Bind>`  ?

**Comment by maxkatz6** [comment]
@sigmarsson have you tried it before?
It should work without problems, since it's related to .NET assemblies and doesn't actually care about is it wpf or winui.

**Comment by StephenLPeters** [comment]
I'm not sure, but I'd encourage you to try it out and report back if it works.  Seems cool.
