### ISSUE TITLE
ContentDialog's new SmokeLayerBackground template part should not be visible on OS prior to 21H1

### ISSUE THREAD

**Issue by RBrid** [microsoft/microsoft-ui-xaml#4232]
Description:
The new ContentDialog control template in \dev\ContentDialog\ContentDialog_themeresources.xaml unconditionally uses a new SmokeLayerBackground part. It should only be used on the 21H1 OS and later.

Repro Steps:
To make it more obvious, in the file dev\ContentDialog\ContentDialog_themeresources.xaml, use a repro brush
`   <Rectangle x:Name="SmokeLayerBackground" Fill="{StaticResource ReproBrush}"/>`
and declare
`   <SolidColorBrush x:Key="ReproBrush" Color="#AA00AA00" />`
Run the MuxControlsTestApp and bring up a ContentDialog in its dedicated test page.
Result: 
  The green smoke layer appears.
Expected: 
  The old smoke layer with the "SystemControlPageBackground***MediumBrush brush should appear.

Expected Behavior:
On OS versions prior to 21H1, the SmokeLayerBackground template part should not be visible.

I think the declaration in \dev\ContentDialog\ContentDialog_themeresources.xaml should be
```
<Rectangle x:Name="SmokeLayerBackground" Fill="{ThemeResource ContentDialogSmokeFill}"
  contract13Present:Visibility="Visible"
  contract13NotPresent:Visibility="Collapsed"/>
```
instead of
```
<Rectangle x:Name="SmokeLayerBackground" Fill="{ThemeResource ContentDialogSmokeFill}"/>
```
Ideally SmokeLayerBackground would not be present at all on older systems.

Version Info:
WinUI 2.6 + 19041 OS.

**Comment by mdtauk** [comment]
What is the purpose of the ReproBrush and what is the visual and behavioural result of the new Smoke Layer Background?
