### ISSUE TITLE
Theme keys not applied for winui pop controls in application level.

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4236]
**Describe the bug**

The theme keys not applied to the pop-up controls when customising them at application level.
    
**Sample**

[PopupControl_Themekey_Issues.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6002441/PopupControl_Themekey_Issues.zip)

**Steps to reproduce the bug**

1. Run the sample
2. Click the CalendarDatePicker's dropdown button and pop up Calendar will be opened.
3. Note: customised foreground theme key not applied for  the `TodayButton`.

**Expected behavior**

Theme keys must be applied to all Popup controls.

**Screenshots**

![image](https://user-images.githubusercontent.com/55440472/108350625-74d09c00-720a-11eb-9e1c-eb6d17399e33.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes  |
| May 2020 Update (19041)            | |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
I think this will go away once winui3 removes XamlControlsResources.

**Comment by mageshsankar** [comment]
I have removed that `XamlControlsResources` from `Application.Resources` . But, still issue occurs.

**Comment by mageshsankar** [comment]
Hi Team,

Compact mode resources also not merging for controls placed in the popup.

Thanks
Magesh
