### ISSUE TITLE
Page Events

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4237]
I wish to invoke a callback when an `ItemsRepeater `runs to completion, which I cant seem to accomplish by just using the controls events. What is the last event firing when a `Page `is loading, that is supposed to happen after an `ItemsRepeater ` finishes on a `Page `?

**Comment by StephenLPeters** [comment]
Can you give more details about what you are trying to do? it depends on the specific timing.

**Comment by sigmarsson** [comment]
Thanks @StephenLPeters. I was adding `RadioButtons `and set the `SelectedIndex` at the same time, which fired the `SelectionChanged `event. I just wanted that handler to run only at manual selection, so I sought an event occurs when the entire `ItemsRepeater `runs to completion. I did not find, so I opted for the event `PointerEntered`, where I enable the `SelectionChanged` handler, which was initially disabled.

**Comment by StephenLPeters** [comment]
Can you simply attach your SelectionChanged event handler to the RadioButton's after you've set the initial selected index?  Or you could ignore the first instance of the selection changed event.

**Comment by sigmarsson** [comment]
Had I know when all `RadioButtons `fabricated by the `ItemsRepeater `, one could yeah switch on the handler in the right moment. 
I am unaware when this specific moment takes place. Another, I have N `RadioButtons` so had to until all is done.  But I hope the `PointerEntered` event will ensure all these synchronization matters.
