### ISSUE TITLE
An incorrect theme resources applied in case of theme switching

### ISSUE THREAD

**Issue by VladimirDrobyshev** [microsoft/microsoft-ui-xaml#4238]
**An incorrect theme resources applied in case of theme switching**

An application has some dependency properties of the SolidColorBrush type. On each property change, we reload all brushes to the cache. But some properties have old value after setting.

**Steps to reproduce the bug**
1. Run the sample [ThemeBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6002901/ThemeBug.zip).
2. Click the "Change Theme" button - all colors are loaded correctly.
3. Click the "Change Theme" button again - only third color is loaded correctly, other three have the previous value.

**Expected behavior**
All properties must have the correct value.

**Screenshots**
Correct values after first theme switching:
![screen1](https://user-images.githubusercontent.com/12460363/108365893-caa44480-7208-11eb-8417-2d359d002c53.png)

Incorrect values after second theme switching:
![screen2](https://user-images.githubusercontent.com/12460363/108366023-f0c9e480-7208-11eb-8380-f5976fb9ecb0.png)

**Version Info**
NuGet package version:  [Microsoft.WinUI 3.0.0-preview4.210210.4] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | |
| October 2020 Update (19042)        | |
| May 2020 Update (19041)            | |
| November 2019 Update (18363)       | Yes |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        | |
| April 2018 Update (17134)          | |
| Fall Creators Update (16299)       | |
| Creators Update (15063)            | |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | |
| Surface Hub        | |
| IoT                | |

**Comment by BorzillaR** [comment]
After migrating the project on the Project Reunion pre-0.5 sdk, the bug is still reproducible.
