### ISSUE TITLE
How to know when a modifier is pressed on KeyDown event? WinUI3 repview4

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4241]
In preview3 of WinUI3 I was using the following code to know whether the Shift key was pressed while listening to the KeyDown event

```
var cw = CoreWindow.GetForCurrentThread();
return cw.GetAsyncKeyState(VirtualKey.Shift) != CoreVirtualKeyStates.None;
```
This stopped working on preview4 (for Desktop)

The _KeyRoutedEventArgs_ doesn't come with a **KeyModifiers** property as the _PointerRoutedEventArgs_. 

How should we detect shift or control pressed in KeyDown event?

**Comment by marb2000** [comment]
You should use the ### Microsoft.UI.Input.KeyboardInput.GetKeyStateForCurrentThread

https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.input.keyboardinput?view=winui-3.0-preview

**Comment by arivoir** [comment]
That worked! Thanks.

Is it coherent the PointerRoutedEventArgs comes with the KeyModifiers property but KeyDown doesn't have it? What method should I use to get the modifiers in pointer events. Is there any difference between using the routed event property or the KeyboardInput one?
