### ISSUE TITLE
XamlRoot is null in WinUI3 for Desktop preview4

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4242]
Since preview 4, accessing the XamlRoot property of a FrameworkElement after the InitializeComponent of a Window returns null.

```
<Window>
    <Grid x:Name="root" />
</Window>
```

```
public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
        var xamlroot = root.XamlRoot; //This is null
    }
}

```

**Comment by StephenLPeters** [comment]
This is expected.  Xaml elements won't have a XamlRoot until they are added to the tree. Once the OnLoaded event has fired the element should have a valid XamlRoot.
