### ISSUE TITLE
Question: How to hide a navigation view footer area 

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#4243]
Hello!

I want to hide a footer area of the navigation view. I set IsSettingsVisible to false, but a separator with an empty footer area is still visible.

![image](https://user-images.githubusercontent.com/23479280/108387346-8fad0b80-721e-11eb-86de-3eb65dd45416.png)

**Comment by chingucoding** [comment]
This is a bug with NavigationView. There is an open issue for this already (#3900) and PR to fix this (#4193).
