### ISSUE TITLE
Compact mode sizing applied only first time for the popup controls

### ISSUE THREAD

**Issue by susmitha-sundar** [microsoft/microsoft-ui-xaml#4244]
**Describe the bug**

I have created the PopUp host, which has the ComboBox and TextBox controls. I have created the popup only first time. I have used the same host for next time. I have added  the compact.xaml resource dictionary  in MainPage Grid's resources. CompactMode sizing applied only first time for ComboBox and TextBox. At second time standard sizing applied.

**Steps to reproduce the bug**
1. Run the attached sample.
2. Click the ShowPopUp button
3. PopUp opens, and compact sizing applied for TextBox and ComboBox.
4. Click the close button in PopUp. Popup closed.
5. Again click on ShowPopUp button.

**Expected behavior**
Compact sizing should applied for TextBox and ComboBox.

**Screenshots**
First time:
![image](https://user-images.githubusercontent.com/60175573/108393264-79f90f80-7239-11eb-9407-1aa1ca388f41.png)

Second time:
![image](https://user-images.githubusercontent.com/60175573/108393319-8715fe80-7239-11eb-882c-88869bde76e8.png)

**Version Info**
 OS version(s) : Windows 10

NuGet package version: 
Microsoft.WinUI 3.0.0-preview4.210210.4

**Additional context**

Sample: 
[PopUp_Demo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6004588/PopUp_Demo.zip)

**Comment by susmitha-sundar** [comment]
Hi Team,

Any update on this?

**Comment by AmalRajUmapathySelvam** [comment]
Any update on this?
