### ISSUE TITLE
PipsPager: sometimes internal scrollviewer makes external scrollviewers scroll

### ISSUE THREAD

**Issue by beervoley** [microsoft/microsoft-ui-xaml#4246]
**Describe the bug**

Sometimes when moving from one pip to another (by clicking on it directly or using the navigation arrows), external scroll viewers on the page will scroll as well.
**Steps to reproduce the bug**

1. Create a Vertical Pips Pager inside a scroll viewer.
2. Choose the last Pip.
3. Observe the outside scroll viewer scrolling as well.

**Expected behavior**

External scroll viewers shouldn't scroll. It happens because the inner scroll was not "complete" and the bring into view event is bubbled up causing the external scroll viewers to scroll as well. The way to fix it is to handle the bringintoview event on the internal scroll viewer.
**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6 prerelease]

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@regis fyi
