### ISSUE TITLE
Expander Header Stretch is not Exposed

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#4248]
**Describe the bug**
This bug was inherited from the Toolkit style, see our issue describing the problem here: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3070 **This should be resolved before Expander ships stable.**

We found in general that having the `ToggleButton` within the Expander control made re-styling the control very difficult for our developers. I had missed this on the original PR, I would have suggested exploring an alternative approach...

**Expected behavior**
Able to stretch the content of an Expander's Header

**Additional context**
Also there's a duplicate of `ExpanderHeaderUpStyle` both in the Theme Resources and the main Style for Expander.

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by michael-hawker** [comment]
🦙 Also see #4391 and #4390 which should be resolved before shipping stable as well.
