### ISSUE TITLE
Preview4: When dragging across windows with different DPIs, window doesn't resize

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#4252]
**Describe the bug**
If you have multiple monitors with different DPIs and drag from one monitor to the other, the contents of the window correctly changes size for the new screenscale, but the window itself doesn't resize.

**Steps to reproduce the bug**
1. Create a Win32 WinUI3 app.
2. Add some XAML content to the Window
3. Drag the window across multiple monitors with different dpi scaling and observe that the content resizes, but not the window itself.

**Expected behavior**
Window resizes and not just its contents

**Screenshots**

https://user-images.githubusercontent.com/1378165/108467484-1d4a2480-723a-11eb-9dfe-8082765be5a8.mp4

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@dotMorten Is this issue unique to Preview4?

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by StephenLPeters** [comment]
@marb2000 FYI

**Comment by dotMorten** [comment]
> Is this issue unique to Preview4?

Just tried P3 and see the same issue, so no.

**Comment by marb2000** [comment]
I can see how UWP apps like Mail or Win32 apps like Edge already implement the behavior that @dotMorten is describing.

**Comment by dotMorten** [comment]
Verified fixed with version 1.3.230502000
