### ISSUE TITLE
NavigationView Settings item scroll 

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/microsoft-ui-xaml#4253]
**Describe the bug**

In a NavigationView, Settings item got a scrollbar:

**Screenshots**

![image](https://user-images.githubusercontent.com/50652041/108472231-24eae700-7295-11eb-9836-b8ea6b80ee8b.png)
![image](https://user-images.githubusercontent.com/50652041/108473235-70ea5b80-7296-11eb-874e-2a4fb24146e6.png)

**Steps to reproduce:**
- Add Navigation View on a page
- And put the pointer on the right corner side of the item

**Version Info**

NuGet package version: Microsoft.WinUI 3.0.0-preview4.210210.4

Windows app type:
| UWP              | Win32            |
| :---------------: | :---------------: |
|  Yes  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :--------------------: |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |Yes|
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :---------------: |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by chingucoding** [comment]
Thank you for filing this issue, however this has already been filed #3771 and a PR for this is already open (though it's been open for a bit now): #3777

**Comment by LeftTwixWand** [comment]
Ok)
