### ISSUE TITLE
Discussion:  Winui 3 Desktop application with  C++/winrt

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4254]
I create a winui3-preview4 desktop app with  c++/winrt, but i get the following ui

![winui3](https://user-images.githubusercontent.com/16729017/108473906-9775ba00-72c9-11eb-917e-4bcb2eb151ca.gif)

i hope it look like:

![wanted 0](https://user-images.githubusercontent.com/16729017/108473974-b1170180-72c9-11eb-9ddc-7f67600981e6.png)

reference xaml-controls-gallery:
https://docs.microsoft.com/en-us/samples/microsoft/xaml-controls-gallery/xaml-controls-gallery/

ControlList.xaml
![2021-02-19_155628](https://user-images.githubusercontent.com/16729017/108475033-23d4ac80-72cb-11eb-94c4-cbbf36cadd1f.jpg)

MainWindow.xaml

![2021-02-19_155704](https://user-images.githubusercontent.com/16729017/108475053-2afbba80-72cb-11eb-8f8a-15a3916e8a95.jpg)

This is completely unusable！or i'm doing something wrong?

**Comment by StephenLPeters** [comment]
I suspect there is something wrong with your code, however I'm unable to decern what exactly the issue is from these code snippets and arrows pointing to things that look wrong. Could you please open more specific issues that describe a single component you think is not working as it should?

**Comment by shelllet** [comment]
thks, i'will.
