### ISSUE TITLE
TextBox CharacterReceived event is not fired in WinUI Desktop mode

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4256]
**Describe the bug**
TextBox CharacterReceived event is not fired in WinUI Desktop mode

**Steps to reproduce the bug**
1. Run the sample.
2. Type any character.
3. Note, CharacterReceived event of TextBox will not be fired.

**Expected behavior**
CharacterReceived event of TextBox should be fired.

**Version Info**

**NuGet package version:** 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

**Sample:**
[TextBox-CharacterRecieved-event-is-not-fired.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6009160/TextBox-CharacterRecieved-event-is-not-fired.zip)

It works fine in WinUI Universal windows.

**Note:** 

But following specific case works in **[Microsoft.WinUI 3.0.0-preview3.201113.0]**, if we set TextBox as ReadOnly in PreviewKeyDown event, then its CharacterRecieved event is fired. Now, it does not works in **[Microsoft.WinUI 3.0.0-preview4.210210.4]**. Please find the attached sample for further details.

Also, Is there any way to get the equivalent character value based on the key pressed in PreviewKeyDown event of TextBox?

**Comment by marb2000** [comment]
I can repro this bug. It's a regression.  As simple as:

```XML
<TextBox x:Name="MyText"  />
```

```CS
public MainWindow()
{
       this.InitializeComponent();
       this.MyText.CharacterReceived += MyText_CharacterReceived;
}

private void MyText_CharacterReceived(UIElement sender, CharacterReceivedRoutedEventArgs args)
{
       System.Diagnostics.Debug.WriteLine(args.Character);
}
```

**Comment by chrisglein** [comment]
Could this be a regression resulting from the lack of a CoreWindow?
Regression between preview3 and preview 4.
