### ISSUE TITLE
Documentation is posted - WinRT API changes for Desktop apps

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#4257]
Hi folks,

Lots of you using WinUI 3 Preview 4 have noticed that some Windows APIs are no longer supported in Preview 4 for Desktop apps - some notable ones being CoreWindow, CoreDispatcher, ApplicationView, and CoreApplicationView. We've just posted a doc that identifies some of these unsupported APIs in Preview 4, offers replacements and/or workarounds, and provides more context on the reasons behind these changes. You can find this doc on our repo here:

## [WinRT API changes for Desktop apps](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/winrt-apis-for-desktop.md)

Note that this is a *living* document - we are working hard to make a longer, all-encompassing list of the APIs that were affected by this change, and provide workarounds/code snippets/replacement APIs if possible. Stay tuned, and continue to [file bugs](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=) if an API is newly giving you issues in Preview 4. 

Thanks for testing out Preview 4!

**Comment by lhak** [comment]
Just wanted to note that the IUIViewSettingsInterop interface works in a desktop app to access the UIViewSettings class. Is this intentionally not documented because it is not supposed to be used?
