### ISSUE TITLE
Question: Community maintenance of deprecated controls

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#4264]
I have a question regard to the maintenance of deprecated controls. 

With WinUI3 some control elements of UWP are no longer being developed. #3957 **What are the controls** that are no longer being developed and is there a possibility that the community will take over these controls for further development?

The pivot control in particular cannot be replaced by other controls due to some of its properties. For example the change of view without navigation and touch based interaction to other Pivot items (swipe left or right).

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI
