### ISSUE TITLE
Can't bind IsSelected on GridViewItem to Viewmodel

### ISSUE THREAD

**Issue by LokiMidgard** [microsoft/microsoft-ui-xaml#4265]
**Describe the bug**
Can't bind to `IsSelected` in `GridViewItem` (`ItemContainerStyle`) to a dependency property in ViewModel.
Setting the value of `IsSelected` in the `ItemContainerStyle` to a value does not change the selection state of the Control

**Steps to reproduce the bug**

[reproduction Sample](https://github.com/LokiMidgard/BUG-WinUI-GridView-Selection)

**Expected behavior**
Binding to `IsSelected` will reflect the current state of the UI in the viewmodel

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Also setting the `IsSelected` to `true` in the `ItemContainerStyle` will also ignored. So I would imagen it is not a problem with binding but that `GridViewItemPresenter` just ignores the property completely. I couldn't check that in the the LiveProperty view of Visual Studio, it displayed nothing when I selected the GridViewItem.

**Comment by chrisglein** [comment]
Based on this comment it looks like this isn't behaving the same as WPF. But not necessarily a difference between UWP and WinUI3. I've tagged the bug accordingly.
```xml
            <!-- The way I think it should work & worked in WPF-->
            <Style TargetType="GridViewItem" x:Key="normalBind">
                <Setter Property="IsSelected" Value="{Binding IsActive}"/>
            </Style>

            <!-- This should at least bind to the correct Dependency Property on Viewmodel side-->
            <Style TargetType="GridViewItem">
                <Setter Property="IsSelected" Value="{Binding Path=Content.IsActive, RelativeSource={RelativeSource Mode=TemplatedParent}, Mode=TwoWay}"/>
            </Style>
```

Based on this comment it sounds like the binding works in other places, but not specifically with the GridViewItemPresenter:

> o I would imagen it is not a problem with binding but that GridViewItemPresenter just ignores the property completely.

Meta observation: Debugging binding issues can be hard for app authors. _However_, some relief has come via this:

[Improvements to XAML tooling in Visual Studio 2019 version 16.7 Preview 1](https://devblogs.microsoft.com/visualstudio/improvements-to-xaml-tooling-in-visual-studio-2019-version-16-7-preview-1/#xaml-binding-failure-troubleshooting)

@LokiMidgard  you might want to try that out and see if it's helpful?
