### ISSUE TITLE
Can I have both Winforms and WinUI referenced in the same project?

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#4268]
I have a .net 5 class library 'engine'. I want to be able to pass my engine a WinForms panel, but my engine is already setup to accept WinUI SwapChainPanel. So I added 
```xml
<UseWindowsForms>true</UseWindowsForms>
```
But from there I only had problems. all sorts of component crashes and errors. Is this a supported scenario?

I can't seem to reference either project from the other. One issue is getting lots of these errors ...

NETSDK1082	There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'

I'm not wanting to support arm so can I just get rid of any need for arm packs? How can I do that?

**Comment by StephenLPeters** [comment]
WinForms doesn't support ARM, so if you want to remove ARM from your solution file that might get you one step closer. However I don't think winui3 supports islands scenarios currently.  @Austin-Lamb and @MikeHillberg can you weigh in?

**Comment by Gavin-Williams** [comment]
So, just to make it clearer, I'm not interested in islands, not looking at that. I'm just looking to bind the swapchain to whatever is passed in, whether it's a SwapChainPanel or WinForms.Panel.

But I'm thinking of pulling out the application layer into separate projects - One for each of UWP, WinUI and WinForms, so that there is no framework clash. I will try to remove the arm stuff to start with but I couldn't work out how to do it the other day.
