### ISSUE TITLE
UWP - AmbiguousMatchException thrown when binding TextBlock.Text property to the property which exists in both base and derived class

### ISSUE THREAD

**Issue by SaravananAyyanar** [microsoft/microsoft-ui-xaml#427]
**Describe the bug**
I have a property in same name in both base and derived class with different data type. When binding the property to TextBlock.Text property, exception occurs while binding itself.
NOTE: Exception is throwing only in UWP. But works fine in WPF.

**Steps to reproduce the bug**
BindingCode:

```c#
MyData myDataObject = new MyData(DateTime.Now);
Binding myBinding = new Binding();
myBinding.Mode = BindingMode.TwoWay;
myBinding.ConverterParameter = null;
myBinding.UpdateSourceTrigger = UpdateSourceTrigger.Default;
myBinding.Path = new PropertyPath("MyDataProperty");
myBinding.Source = myDataObject;
myBinding.ElementName = myDataObject.MyDataProperty;
textBlock.SetBinding(TextBlock.TextProperty, myBinding);
```

Model:

```c#
public class data
{
    public int MyDataProperty { get; set; }
}


public class MyData : data
{
    private string myDataProperty;


    public MyData() { }


    public MyData(DateTime dateTime)
    {
        myDataProperty = "Last bound time was " + dateTime.ToLongTimeString();
    }


    public new String MyDataProperty
    {
        get { return myDataProperty; }
        set
        {
            myDataProperty = value;
            OnPropertyChanged("MyDataProperty");
        }
    }


    public event PropertyChangedEventHandler PropertyChanged;


    private void OnPropertyChanged(string info)
    {
        PropertyChangedEventHandler handler = PropertyChanged;
        if (handler != null)
            handler(this, new PropertyChangedEventArgs(info));
    }
}
```

Run the sample.

**Expected behavior**
Exception not occured.

**Screenshots**
![image](https://user-images.githubusercontent.com/44993310/54331543-75388380-4640-11e9-986d-6476ba228468.png)

**Comment by jevansaks** [comment]
I could not get this sample to produce an AmbiguousMatchException on latest insider. It either gave no errors (but also didn't work) if I did it from XAML and from code-behind it was giving a debug output error:

```
Error: BindingExpression path error: 'MyDataProperty' property not found on 'App1.MyData'. BindingExpression: Path='MyDataProperty' DataItem='App1.MyData'; target element is 'Windows.UI.Xaml.Controls.TextBlock' (Name='textBlock'); target property is 'Text' (type 'String')
```

@SaravananAyyanar can you provide the version of Windows you're running against and a more complete sample?

I'm also confused by the setting of "myBinding.ElementName" in the repro, why is that being used?

**Comment by SaravananAyyanar** [comment]
complete sample:
[UWPArgumentException.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3002629/UWPArgumentException.zip)

ScreenShots:
![image](https://user-images.githubusercontent.com/44993310/54910118-b6b71180-4f11-11e9-9443-75bcd9bab96a.png)

I have tested latest version and also other version, but exception thrown when run the sample and also output window shown the  error,
Error: BindingExpression path error: 'MyDataProperty' property not found on 'App1.MyData'. BindingExpression: Path='MyDataProperty' DataItem='App1.MyData'; target element is 'Windows.UI.Xaml.Controls.TextBlock' (Name='textBlock'); target property is 'Text' (type 'String')

**Comment by SaravananAyyanar** [comment]
Any update on this query ?

**Comment by jevansaks** [comment]
Sorry for the delay, we'll debug and take a look. That said, this is probably just an accidental difference between the XAML binding behavior and the WPF binding behavior. 

Is using x:Bind an option for you?

**Comment by SaravananAyyanar** [comment]
We are binding the property in code behind for our internal purpose. So, x:Bind is not an option for us. We needs this bug to be fixed.

**Comment by fabiant3** [comment]
@SaravananAyyanar, thank you for reporting this issue around Binding. Chances are that this bug requires framework changes and since that portion has not been open sourced just yet, we won't be able to give you a speedy update. Second, Microsoft's investment has been in x:Bind for the last few years, we see x:Bind as a much better alternative to Binding.
1. I encourage you to unblock yourself by switching to x:Bind. Let us know if you need any help with that.
2. We'll keep track of this bug and once the framework portion is open sourced, we can look into fixing it.

**Comment by SaravananAyyanar** [comment]
@fabiant3 ,can you provide the code for x:bind in code behind as mention above.
 We are binding in code behind for our internal purpose. We needs this bug to be fixed.

**Comment by SaravananAyyanar** [comment]
Any update regarding this?

**Comment by fabiant3** [comment]
@SaravananAyyanar - there are no planned changes to Binding at this moment, the investments we have been making for years now are all in x:Bind. Even if we were to make changes to support this scenario in Binding, there is no vehicle to deliver that since it requires framework updates and that code is not open sourced (yet). 
I recommend making changes to your code, so you can support x:Bind and/or wait until the code becomes open sourced.
