### ISSUE TITLE
’Element is already the child of another element' exception when navigating pages

### ISSUE THREAD

**Issue by ranjeshj** [Microsoft/microsoft-ui-xaml#428]
**Describe the bug**
When navigating back and forth from a page hosing a repeater, we seem to hit an exception saying 'Element is already the child of another element'. 

**Steps to reproduce the bug**
Try navigating back and forth in the ItemsView sample. This is not a consistent repro.
TBD: partner has hit this as well- I'm trying to get a more consistent repro.

**Expected behavior**
No crash

**Comment by jevansaks** [comment]
@ranjeshj -- do you want me to track this for 2.1?

**Comment by ranjeshj** [comment]
no

**Comment by ranjeshj** [comment]
No

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adclements** [comment]
I have a consistent repro. Min version is rs3, target version is rs5, running on rs5.  Started happening with version 2.1.181217001-prerelease.

This is using an ItemsRepeater with a bound DataTemplateSelector, and an ItemsSource with a bound list.

The exception is always thrown under the following conditions:
1) Create and render a virtualizing layout with the ItemsRepeater, and have the data bound to the ItemsSource update - for instance add additional elements, or replace all elements, which triggers OnItemsChangedCore() and subsequent MeasureOverride().
2) Navigate away (discard ItemsRepeater) and create and render another virtualizing layout with ItemsRepeater (could use the same or different bound data).  The crash occurs in MeasureOverride() when calling context.GetOrCreateElementAt() for the new data.

Its important to note that if the data never updates in step (1) above, then the crash will not occur in step (2).

**Comment by davidfishlock** [comment]
I see the same issue when nesting ItemsRepeater to present hierarchical data. When scrolling and the containers are recycled, the same exception is thrown.

**Comment by ranjeshj** [comment]
can you please share a repro app ?

**Comment by davidfishlock** [comment]
It's not a very complex repro, the ItemsRepeater just needs to be inside a DataTemplate and bound to something. It will throw an exception when user scrolls and the parent container is recycled.

https://dev.azure.com/davidfishlock/ItemsRepeater
