### ISSUE TITLE
TreeView control can not scroll contents in Desktop application c++/winrt

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4283]
treeview control in xaml file.
```
  <TreeView CanDragItems="True" AllowDrop="False" DragItemsStarting="treeView_DragItemsStarting"  
              
              x:Name="treeView" ItemsSource="{x:Bind SourceModel.Source}">
        <TreeView.ItemTemplate>
            <DataTemplate x:DataType="local:Item">
                <TreeViewItem ItemsSource="{x:Bind Children}" Content="{x:Bind Title}"/>
            </DataTemplate>

        </TreeView.ItemTemplate>
    </TreeView>
```

![image](https://user-images.githubusercontent.com/16729017/108704843-85a14a80-7547-11eb-87da-272d0f50442b.png)

expand:
![image](https://user-images.githubusercontent.com/16729017/108704800-791cf200-7547-11eb-9842-d938017be17d.png)

related link: https://github.com/microsoft/microsoft-ui-xaml/issues/4254

**Comment by StephenLPeters** [comment]
Why have you set the ScrollViewer properties on the TreeView?  I'm pretty confident those should not be needed.  If they are causing the issue that would be a bug.

**Comment by shelllet** [comment]
I remove `ScrollViewer` property , it still can't scroll contents.

**Comment by StephenLPeters** [comment]
Okay, can you please edit the issue description and we'll look into it.

**Comment by shelllet** [comment]
> Okay, can you please edit the issue description and we'll look into it.

OK, I have removed the `ScrollViewer` relevant code.

**Comment by shelllet** [comment]
ScrollViewer  Control also have this problem.
```
 <ScrollViewer HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto">

            <StackPanel x:Name="stackPanel" Orientation="Vertical" 
                    
           Padding="10" Spacing="10"
                   
                HorizontalAlignment="Center" VerticalAlignment="Center">

                <!--<Button x:Name="myButton" Click="myButton_Click">Click Me</Button>-->
                <local:Indicator x:Name="myIndicator"></local:Indicator>
            </StackPanel>
        </ScrollViewer>
```

**Comment by shelllet** [comment]
RichTextBlock Control also have this problem.
```
<RichTextBlock x:Name="textBlock" TextWrapping="WrapWholeWords" ScrollViewer.VerticalScrollMode="Enabled" ScrollViewer.HorizontalScrollMode="Enabled">
        <Paragraph>I am a RichTextBlock.</Paragraph>
      </RichTextBlock>
```

**Comment by codendone** [comment]
It sounds like layout might be giving the TreeView/ScrollViewer all the space it wants, such that no scrolling is needed, with the consequence that the element might be extending offscreen and being clipped. What is the TreeView.ActualHeight? Is it taller than it should be?

For RichTextBlock, that element does not support scrolling by itself. You'd need to explicitly put it in a ScrollViewer if you need that behavior.

**Comment by shelllet** [comment]
yeah RichTextBlock is really needed to put it in a scrollview, i found it yesterday.
Tks, i will debug it and see  ActualHeight.
doc: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer?view=winrt-19041
![image](https://user-images.githubusercontent.com/16729017/112589070-6db93100-8e3b-11eb-82df-ac97c3854f2b.png)

**Comment by shelllet** [comment]
> It sounds like layout might be giving the TreeView/ScrollViewer all the space it wants, such that no scrolling is needed, with the consequence that the element might be extending offscreen and being clipped. What is the TreeView.ActualHeight? Is it taller than it should be?
> 
> For RichTextBlock, that element does not support scrolling by itself. You'd need to explicitly put it in a ScrollViewer if you need that behavior.
treeView ActualHeight aways smaller than StackPanel ActualHeight.
![image](https://user-images.githubusercontent.com/16729017/112591514-6c8a0300-8e3f-11eb-998d-aab336b28285.png)

**Comment by codendone** [comment]
Is the StackPanel the root element? If not, what is the ActualHeight of the root element? Or if you convert the ActualHeight value to pixels (by multiplying by your monitor's scale factor), is that height plus the offset from the top of the window too tall to fit?

If the parent of the TreeView is a StackPanel I think you might need to either limit the TreeView to a MaxHeight or switch to something like Grid which will limit the space by default. I think the behavior for TreeView is to size-to-content unless its height is constrained, and StackPanel as an ancestor will not constrain its height.

**Comment by shelllet** [comment]
yeah, stackpanel is the root element, I put stackpanel and test button  into it.  my monitor's scal factor is 250%  .

i switch winui to reunion 0.5 release. and  treeview can scroll contents when i put it as root element of page.

**Comment by shelllet** [comment]
`Grid which will limit the space by default` This sentence is very important .

i switch to grid and it's aslo fine! thank you(@codendone ) very much! this issue can be close.
