### ISSUE TITLE
Windows.UI.Xaml.Controls vs Microsoft.UI.Xaml.Controls

### ISSUE THREAD

**Issue by esobrino** [microsoft/microsoft-ui-xaml#4288]
Very basic.  In 2019 VS Preview I added a User Control and it kept complaining about the control having a different base class.  After some troubleshooting I realized that the UserControl in:

   public sealed partial class NavigationControl : UserControl
   {
      public NavigationControl()
      {
         this.InitializeComponent();
      }
   }

Was Windows.UI.XamlControls!

But the generated hidden code looks like:

    partial class NavigationControl : global::Microsoft.UI.Xaml.Controls.UserControl
    {

Since I can't control the generated code... I changed the partial class to look like:

   public sealed partial class NavigationControl : Microsoft.UI.Xaml.Controls.UserControl
   {

And then all was good!

What it will be?  Windows.UI.Xaml.Controls or Microsoft.UI.XamlControls

?

**Comment by StephenLPeters** [comment]
it will be Microsoft.UI.Xaml.Controls

Windows.UI.Xaml is the namespace that is used by the version of XAML that is shipped with the Operating system. Microsoft.UI.Xaml is the namespaced used with the winui2 and winui3 nuget packages.  Some types, like nav view, exist in both Window and Microsoft.UI.Xaml.  We recommend using the Microsoft.UI.Xaml version wherever possible as this is where active development occurs
