### ISSUE TITLE
muxc:NumberBox's all basic appearance customisation properties not working

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4289]
**Describe the bug**

All basic appearance customisation properties like Height, BorderThickness, Background, Padding, etc..,  not working in muxc:NumberBox control.

Sample:

[MUXC_NumberBox.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6022646/MUXC_NumberBox.zip)

**Steps to reproduce the bug**

1. Extract the sample.
2. Run the sample.
3. See the NumberBox,  Height, BorderThickness,, Background, , Padding not applied.

**Expected behavior**

NumberBox sholud be apply the Height, BorderThickness,, Background, , Padding property values.

**Screenshots**

![image](https://user-images.githubusercontent.com/55440472/108724110-fac24f00-754a-11eb-8f9b-9a8055495240.png)

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Wow, thats not great. It looks like this repro's in Winui2 as well..

**Comment by chingucoding** [comment]
I'll take a look at this.
