### ISSUE TITLE
In ItemsView prototype when switching views one container is not recycled from the previous view.

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#429]
**Describe the bug**
when switching views in the ItemsView prototype, it looks like one of the items seem to be held onto and does not get the new template. There might be a case where the pinned element is being held onto when it should be recycled.

**Steps to reproduce the bug**
Switch views in itemsview prototype.

**Expected behavior**
when the view is switched all items should get the new template.

**Comment by chingucoding** [comment]
I think this is the exact same issue as #1954 and the underlying framework bug #3057. Since ItemsRepeater has a workaround for #1954 now, we can probably close this @ranjeshj @StephenLPeters .

**Comment by StephenLPeters** [comment]
That's believable, @ranjeshj can you confirm and close?

**Comment by ranjeshj** [comment]
I could not reproduce this recently, so we can close this. Thanks for pinging on this issue @chingucoding
