### ISSUE TITLE
This breakpoint will not currently be hit.

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4290]
I sometimes have to rebuild the entire bits in order break points be available, meanwhile I am editing the same and only .cs file. 

![image](https://user-images.githubusercontent.com/43340959/108727351-c2aa1480-7528-11eb-9f18-57566fbaf8a6.png)

**Comment by StephenLPeters** [comment]
We'd need more repro steps to understand what is causing this, but it is unlikely to be an issue with the WinUI product.
