### ISSUE TITLE
Snap Points on StackPanel doesn't work when Spacing is used

### ISSUE THREAD

**Issue by carldebilly** [microsoft/microsoft-ui-xaml#4293]
## Describe the bug
When using the `Spacing` property on a `<StackPanel />`, snap points are ignoring it and produce unaligned result.

## Steps to reproduce the bug

1. Use the following XAML on a UWP application:
    ``` xml
   <StackPanel>
       <TextBlock>Snap Points</TextBlock>
       <ComboBox x:Name="snapPointsCombo" SelectedIndex="3">
           <ComboBoxItem>None</ComboBoxItem>
           <ComboBoxItem>Optional</ComboBoxItem>
           <ComboBoxItem>OptionalSingle</ComboBoxItem>
           <ComboBoxItem>Mandatory</ComboBoxItem>
           <ComboBoxItem>MandatorySingle</ComboBoxItem>
       </ComboBox>
       <Slider x:Name="spacing" Minimum="0" Maximum="30" Value="20" />
       <Border BorderBrush="Black" BorderThickness="3" Width="200" Height="225" HorizontalAlignment="Left">
           <ScrollViewer
               VerticalSnapPointsType="{Binding SelectedItem.Content, ElementName=snapPointsCombo}">
               <StackPanel Spacing="{Binding Value, ElementName=spacing}">
                   <Rectangle Fill="#9400D3" Height="75" />
                   <Rectangle Fill="#4B0082" Height="75" />
                   <Rectangle Fill="#0000FF" Height="75" />
                   <Rectangle Fill="#00FF00" Height="75" />
                   <Rectangle Fill="#FFFF00" Height="75" />
                   <Rectangle Fill="#FF7F00" Height="75" />
                   <Rectangle Fill="#FF0000" Height="75" />
                   <Rectangle Fill="#9400D3" Height="75" />
                   <Rectangle Fill="#4B0082" Height="75" />
                   <Rectangle Fill="#0000FF" Height="75" />
                   <Rectangle Fill="#00FF00" Height="75" />
                   <Rectangle Fill="#FFFF00" Height="75" />
                   <Rectangle Fill="#FF7F00" Height="75" />
                   <Rectangle Fill="#FF0000" Height="75" />
                   <Rectangle Fill="#9400D3" Height="75" />
                   <Rectangle Fill="#4B0082" Height="75" />
                   <Rectangle Fill="#0000FF" Height="75" />
                   <Rectangle Fill="#00FF00" Height="75" />
                   <Rectangle Fill="#FFFF00" Height="75" />
                   <Rectangle Fill="#FF7F00" Height="75" />
                   <Rectangle Fill="#FF0000" Height="75" />
               </StackPanel>
           </ScrollViewer>
       </Border>
   </StackPanel>
   ```
2. Run it (also works directly in XAML Studio, no need to create an app to see the problem)
3. Scroll the colors using the mouse wheel - observe everything is as expected
4. Move the slider to the right - which will increase the `Spacing` value on the `<StackPanel />`
5. Try scrolling again the colors... observe the snap points are incorrect.

## Expected behavior
The scrolling should continue to be snapped to elements, even when a spacing is defined.

## Screenshots
Took using XAML Studio. The scrolling is done using the mouse wheel.
![snappoints](https://user-images.githubusercontent.com/4174207/108770090-e6b92600-7527-11eb-8465-4d92f92912c3.gif)

**Version Info**
SDK Windows version 1903 (build 18362) running on a Windows 10 2004 (Build 19041)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |  |
| May 2019 Update (18362)            |  |
| October 2018 Update (17763)        |  |
| April 2018 Update (17134)          |  |
| Fall Creators Update (16299)       |  |
| Creators Update (15063)            |  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@RBrid FYI
