### ISSUE TITLE
Proposal:Support to make custom UserControl as root control

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4296]
There is a scene, such as many controls has same titlebar, so I need to make custom UserControl as root control that i can embed those controls. This has the concept of C++ object-oriented.

related link: [How to make custom UserControl as root control ?](https://github.com/microsoft/microsoft-ui-xaml/issues/4285#issuecomment-783784527)

**Comment by StephenLPeters** [comment]
Commented on your original issue.
