### ISSUE TITLE
Question: Where is the treeview item click event documentation in desktop c++/winrt？

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4298]
I can't find treeview item click or double click, or selectchanged  event document, where is it?

**Comment by StephenLPeters** [comment]
I think this is what you are looking for for click: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.treeview.iteminvoked?view=winui-2.5. SelectionChanged is still in preview so we don't have docs published for that.
