### ISSUE TITLE
UWP WinUI Microsoft.UI.Xaml.Media missing Color

### ISSUE THREAD

**Issue by Fernand-Delavy** [microsoft/microsoft-ui-xaml#4300]
Using Visual Studio 2019 16.8.5

Sample from https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.media.solidcolorbrush?view=winui-3.0-preview
using Microsoft.UI.Xaml.Media and Microsoft.UI

The Colors is present but Color not
SolidColorBrush myBrush = new SolidColorBrush(Color.FromArgb(255, 20, 20, 90)); Color not found

Or Color is else where ? I found it in Windows.UI but should not be used in WinUI ?
Thanks in advance.
Regards.

**Comment by codendone** [comment]
Windows.UI.Color is still the right type to use. See #1541.
