### ISSUE TITLE
Question: Why is there an extra folder on WinUI3 Desktop templates

### ISSUE THREAD

**Issue by sibille** [microsoft/microsoft-ui-xaml#4302]
Comparing the generated code for a WinUI3 Desktop and WinUI3 Uwp App we've seen that there is an extra folder level created for Desktop apps. In Windows Template Sudio this extra level is causing us problems as it prevents us from sharing templates between WinUI Desktop and Uwp apps (for example the pages we offer are mostly the same for Desktop and Uwp). 

If you compare the output generated for SampleAppWinUIDesktop and SampleAppWinUIUwp you can observe there are 3 folders with the app name created for Desktop and 2 levels for Uwp apps.

SampleApp WinUI Desktop:

![image](https://user-images.githubusercontent.com/24698018/108829372-626aaf80-75c8-11eb-9294-ad848a9d8efd.png)

SampleApp WinUI Uwp:

![image](https://user-images.githubusercontent.com/24698018/108829375-64cd0980-75c8-11eb-86a1-f5cbf57e2c05.png)
	
Is there a special reason behind this or is this due to WinUI3 in Desktop being a multiproject vs WinUI3 in Uwp being a single project template?

For WinTS WinUI3 project generation we are using 2 folder levels, as we do for WPF and UWP project generation.  
So far we have not seen any issues with this structure, but wanted to confirm with the WinUI team that the extra folder level for WinUI Desktop is not needed and we're not causing issues by removing it. 

Sample App WinUI WTS: 

![image](https://user-images.githubusercontent.com/24698018/108829448-7ca48d80-75c8-11eb-86e2-66542793bc0f.png)

**Comment by ranjeshj** [comment]
@stevenbrix as FYI

**Comment by marb2000** [comment]
The difference between the UWP and Desktop folder structures is because there is a checkbox on the project creation wizard that allows you to generate the solution on the same folder that the project. That’s it. It doesn’t matter what folder structure do you choose in the Windows Template Studio.
