### ISSUE TITLE
Detachable control

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4303]
Is there a draggable control becomes a separate window if you drag out of its current context and position ?
The reverse operation as dragging the window into the main window to incorporate into its original context.

**Comment by mdtauk** [comment]
TabView?

**Comment by chingucoding** [comment]
TabView doesn't spawn a new window on it's own unfortunately. However there is a sample in the XAML Controls Gallery @sigmarsson that showcases how to achieve this.

**Comment by sigmarsson** [comment]
Merci. Yeah maybe a separate window may not be necessary, just a draggable thing having a different Z coordinate. Will reply if TabView isn't eligible.

**Comment by sigmarsson** [comment]
hmm, don't cut it. I have set both `AllowDropTabs` and `CanDragTabs` True but to no avail. @mdtauk , how did You think a `TabViewItem` can be detached out from the main Window.

**Comment by sigmarsson** [comment]
Okay, I configured the `TabView` as 

`<TabView CanDragTabs="True" AllowDrop="True" TabDroppedOutside="OnTabOutsideDropped" TabDragStarting="OnTabDragStarting" TabDragCompleted="OnTabDragCompleted" DragOver="OnDragOver" Drop="OnDrop">`


So when it is starting to fall outside of the `TabView` we shall invoke this handler, but of course this is not working. How shall I follow this through in a WinUI manner ? 


        ```
private async void OnTabOutsideDropped(TabView sender, TabViewTabDroppedOutsideEventArgs args)
        {
            if (sender.TabItems.Count > 0)
            {
                CoreApplicationView newWindow = CoreApplication.CreateNewView();

                ApplicationView newView = null;
                await newWindow.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
                {
                    Frame frame = new Frame();
                    frame.Navigate(typeof(AboutPage), null, new SuppressNavigationTransitionInfo());
                    Window.Current.Content = frame;
                    Window.Current.Activate();

                    newView = ApplicationView.GetForCurrentView();
                    newWindow.TitleBar.ExtendViewIntoTitleBar = true;
                });

                bool viewShown = await ApplicationViewSwitcher.TryShowAsStandaloneAsync(newView.Id);

                sender.TabItems.Remove(args.Tab);
            }
        }
```

**Comment by ranjeshj** [comment]
@marb2000 @Austin-Lamb as FYI

**Comment by sigmarsson** [comment]
I witness an ex : **"A method was called at an unexpected time."**
At execution of 

`CoreApplicationView newWindow = CoreApplication.CreateNewView();`

**Comment by vitorgrs** [comment]
There was a proposal feature in 2018 Build, that would make possible to move any XAML page. Probably a dead feature, as no one talked about it anymore...

![Drag XAML](https://i.imgur.com/wGzWslj.gif)

**Comment by sigmarsson** [comment]
wow. you snatched it, I wasn't aware of this initiative took place. The seniors will decide it whether this one will be on the control smorgasbord or let the individuals forge it. I attempted but to no avail.

**Comment by sigmarsson** [comment]
@ranjeshj , will you provide an alternative of `CoreApplication.CreateNewView()` , if so what version ? Or would you please share your take on what @vitorgrs is demonstrating ?

**Comment by sigmarsson** [comment]
@ranjeshj , what is your team's stance on developing this feature ? Or shall the community purchase a commercial one, like [Infragistics' Dock Manager](https://www.infragistics.com/help/wpf/xamdockmanager-understanding-xamdockmanager) ?
