### ISSUE TITLE
Microsoft Edge WebView2

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4306]
How shall this component be a prerequisite in an `MSIX` package to ensure the component is installed and be ready in the moment the product launching and requires `WebView2` to display web content ? 

https://developer.microsoft.com/en-US/microsoft-edge/webview2/

**Comment by ranjeshj** [comment]
@codendone @adambarlow FYI

**Comment by codendone** [comment]
For apps installed from the the Store, there is no way today to have the installer ensure the Edge WebView2 Runtime is installed. It is expected that the WebView2 Runtime will quickly become common on many machines, and there are investigations happening to further improve this.

In the meantime, the WebView2 element will show a link to the Runtime installer if the Runtime isn't installed. That isn't an ideal solution, but it does at least provide a fallback for the user to go install the Runtime, which will then be available for future launches of the app and for any other app.

**Comment by sigmarsson** [comment]
Thanks @codendone .

I did hope the MSIX could leap this step by specifying either a WEbView2 `Capability` or `Dependency` ;

https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-manual-conversion

If you are saying - let say - beyond Version 10.0.19042 the OS will ship this component than it becomes seamless experience. As for the positive experience amid annoying manual installer download, I needn't restart my app to load the WebView2 component, which was good benefit after all.

**Comment by codendone** [comment]
The WebView2 Runtime will be installed by default on a future version of Windows. The ETA for that isn't clear yet.

**Comment by davecarlisle** [comment]
Hi @codendone. Just sharing that we have the same desire as @sigmarsson and started looking at this deployment aspect today. With the WinUi GA we're looking to immediately distribute an app that makes use of WebView2 and were hoping for a super clean install experience... and the users not even aware of a webview2 runtime install (and no clicking on additional install links, etc.). We understand that future windows versions will have the WebView2 runtime auto installed which is generally directionally great. Only item is the unknown ETA there and then combined with version actually rolled out to all users WW in large enterprises, etc. Thanks for all the dialog!

**Comment by sigmarsson** [comment]
@davecarlisle If ETA will never harmonize with your roll out schedule, you may need to fabricate your own bootstrapper, which could install the repackaged WeibView2 component. 

In your MSIX - if it is - you can launch the bootstrapper first;

    
  `<Application Id="Your.App.Id" Executable="Bootstrapper.exe" EntryPoint="Windows.FullTrustApplication">`

**Comment by davecarlisle** [comment]
@sigmarsson Ack and with ya... heading that way. Have a good one!

**Comment by sigmarsson** [comment]
Merci captain! Need 2 hit the sack.

**Comment by sigmarsson** [comment]
[WebView2 became part of the OS Windows 11 as EverGreen Runtime](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
