### ISSUE TITLE
Setting Background colors makes the Custom Title Bar dysfunctional 

### ISSUE THREAD

**Issue by marb2000** [microsoft/microsoft-ui-xaml#4314]
**Describe the bug**
In a Desktop WinUI 3 app set a custom title bar. For example:
```XML
<Window
    x:Class="TitleBarIssueColor.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TitleBarIssueColor"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch">

        <StackPanel Height="35" Orientation="Horizontal" 
                    Spacing="15" x:Name="myTitleBar" HorizontalAlignment="Stretch" 
                    VerticalAlignment="Top" >
            <TextBlock  VerticalAlignment="Center" Text="Custom Title Bar" />
        </StackPanel>
      
    </Grid>
</Window>

```
```CS
using Microsoft.UI.Xaml;
namespace TitleBarIssueColor
{
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();

            ExtendsContentIntoTitleBar = true;
            SetTitleBar(myTitleBar);
        }
    }
}
```
Running the sample, and you will get something like this:

![image](https://user-images.githubusercontent.com/12536513/108899985-ed9a7400-75cd-11eb-88d5-cd7a4ce019c3.png)

However, If you set the Background color of the Grid or the StackPanel, you get something like this:

![image](https://user-images.githubusercontent.com/12536513/108900295-51bd3800-75ce-11eb-8bc2-d4870eaa0b0c.png)

```XML
<StackPanel Height="35" Orientation="Horizontal"
                    Background="DarkGray"
                    Spacing="15" x:Name="myTitleBar" HorizontalAlignment="Stretch" 
                    VerticalAlignment="Top" >
            <TextBlock  VerticalAlignment="Center" Text="Custom Title Bar" />
        </StackPanel>
``` 
**Expected behavior**
The caption buttons of the title bar should be visible and clickable.

**Version Info**

NuGet package version:  Microsoft.WinUI 3.0.0-preview4.210210.4

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No Applicable | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |

**Comment by marb2000** [comment]
@Austin-Lamb @pratikone @ocalvo FYI

**Comment by kuozheyu** [comment]
Is this problem fixed?

**Comment by pratikone** [comment]
it is fixed. min max close caption buttons remain on top even when you apply background color to hosting grid
