### ISSUE TITLE
Caption Buttons of several Windows in the same-thread blinking when hovering 

### ISSUE THREAD

**Issue by marb2000** [microsoft/microsoft-ui-xaml#4316]
**Describe the bug**

Create two or more instances of the same Window class with a custom Title Bar. Hover the mouse over the caption buttons of a Window, and observe how the caption buttons of the others Windows start to blinking.

![image](https://user-images.githubusercontent.com/12536513/108902382-e2951300-75d0-11eb-823a-031bd63ab0f0.png)

```XML
<Window
    x:Class="WindowCaptionButtomsBug.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WindowCaptionButtomsBug"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch">

        <StackPanel Height="35" Orientation="Horizontal" 
                    Spacing="15" x:Name="myTitleBar" HorizontalAlignment="Stretch" 
                    VerticalAlignment="Top" >
            <TextBlock  VerticalAlignment="Center" Text="Custom Title Bar" />
        </StackPanel>
        <Button x:Name="myButton" VerticalAlignment="Center"
                HorizontalAlignment="Center"
                Click="myButton_Click">Click Me</Button>
    </Grid>

</Window>

```

```CS
using Microsoft.UI.Xaml;

namespace WindowCaptionButtomsBug
{
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            ExtendsContentIntoTitleBar = true;
            SetTitleBar(myTitleBar);
        }

        private void myButton_Click(object sender, RoutedEventArgs e)
        {
            MainWindow w = new MainWindow();
            w.Activate();
        }
    }
}
```

**Expected behavior**
Others Window's caption button should do nothing.

NuGet package version: [Microsoft.WinUI 3.0.0-preview4.210210.4] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No Applicable | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by marb2000** [comment]
@Austin-Lamb @ocalvo @pratikone FYI

**Comment by beervoley** [comment]
@marb2000 it's been fixed for the future release:)
