### ISSUE TITLE
Proposal: Please add CarouselPanel here

### ISSUE THREAD

**Issue by yowl** [microsoft/microsoft-ui-xaml#432]
# Proposal: Can we get CarouselPanel in here

## Summary
Related to https://github.com/Microsoft/microsoft-ui-xaml/issues/36, in that CarouselPanel is used by UWP ComboBox.  I did look for a feature request just for ComboBox, but I didn't see one so I'm creating this so as to encourage a high performance ComboBox as the CarouselPanel shoud virtualize.

## Rationale
High performance ComboBox's which can have lots (000s ) of items in the ItemsSource are often used in LOBs.  Often just for the purpose of converting a key to a name with only the option to open which is often not exercised.

**Comment by jevansaks** [comment]
The carousel functionality is useful but CarouselPanel itself isn't something we can easily expose (especially since it uses a bunch of internal hooks). But it would be beneficial to build something like that on top of ItemsRepeater. @micahl @ranjeshj do you have any samples like this?

**Comment by ranjeshj** [comment]
> The carousel functionality is useful but CarouselPanel itself isn't something we can easily expose (especially since it uses a bunch of internal hooks). But it would be beneficial to build something like that on top of ItemsRepeater. @micahl @ranjeshj do you have any samples like this?

I don't have a sample, but it should be relatively easy to build it on top of ItemsRepeater i think.

**Comment by yowl** [comment]
Thanks for the replies.  To be honest I wasn't aware of the ItemsRepeater.   If that could be used in the ComboBox ItemsPanel to get virtualization then that would be good.  I'll close this.

**Comment by jevansaks** [comment]
I'd like to keep this open to track at least getting a CarouselPanel sample built using ItemsRepeater.

**Comment by micahl** [comment]
@yowl, the ComboBox's CarouselPanel does UI virtualization today.  Are you hitting a situation where it's not?

**Comment by yowl** [comment]
@micahl, you mean the UWP one? That is fine.  I was refering to this code repo, if I search for CarouselPanel here, https://github.com/Microsoft/microsoft-ui-xaml/find/master, nothing comes back.  I suppose a bit of background to my question is in order as I can see why there is confusion.  Some other projects would benefit from the source code to a virtualizing combobox, and I was thinking of https://github.com/nventive/Uno, and I thought that if the UWP combox source code along with its CarouselPanel was available it would benefit that project.  Maybe you see my request as a bit underhand and if so I apologize for not being upfront about my reason for this issue.

**Comment by micahl** [comment]
@yowl, thanks for clarifying.  It sounds like the ask here is similar to #217.  You may find it useful to see these two docs (one which I just posted yesterday) 

[Custom collection views / ItemsRepeater guidance](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater)
[Attached Layouts](https://docs.microsoft.com/en-us/windows/uwp/design/layout/attached-layouts) - talks about creating a virtualizing layout

They don't necessarily cover everything about creating a virtualizing control, but I think you and others will still find them useful.  There's a lot that can go into building a custom virtualizing control so hearing from you and others on what you need will help prioritize what additional content gets created.

**Comment by yowl** [comment]
And something to mitigate myself.  We have a large investment in Silverlight and hence looking for ways to not throw that away.

**Comment by micahl** [comment]
I'm closing this issue in favor of the general WinUI 3.0 issue (#717).  Adding CarouselPanel here would be included in that work since we plan to make WinUI 3.0 open source.

Fwiw, to see a virtualizing layout that carousels based on a newer architecture you can take a look at [this layout](https://github.com/microsoft/microsoft-ui-xaml/blob/user/ranjeshj/flickdemo/test/Flick/Layouts/VirtualizingUniformCarouselStackLayout.cs) that we used in [this sample](https://github.com/microsoft/microsoft-ui-xaml/blob/user/ranjeshj/flickdemo/test/Flick/AnimatedCarouselPage.xaml).  We're considering a more complete CarouselView control (#771) that would use it.
