### ISSUE TITLE
NavigationView Top - Icon alignment issues

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#4321]
**Describe the bug**

Icon only buttons like "Settings" do not align correctly with the selection indicator

**Steps to reproduce the bug**

**Expected behavior**

The Icon and Selection Indicator should be aligned vertically centred within the button space

**Screenshots**

![image](https://user-images.githubusercontent.com/7389110/108916886-d2a81e00-7626-11eb-96e0-0c5c72292488.png)
![image](https://user-images.githubusercontent.com/7389110/108917202-49451b80-7627-11eb-8116-c7c86c4d795a.png)

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml.2.6.0-prerelease] - Built from source

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@YuliKl @chigy  as FYI

**Comment by YuliKl** [comment]
Thank you @mdtauk for filing this issue. How did you build the shopping bag button? Is it a NavigationViewItem with no Content only an Icon?

**Comment by mdtauk** [comment]
> Thank you @mdtauk for filing this issue. How did you build the shopping bag button? Is it a NavigationViewItem with no Content only an Icon?

Its in the MUXTestApp which I assume tries to keep the examples as relevant as possible

![image](https://user-images.githubusercontent.com/7389110/109764163-18e31b80-7beb-11eb-8ac0-aa7cb3dc1b5e.png)
![image](https://user-images.githubusercontent.com/7389110/109764215-2e584580-7beb-11eb-9cae-fbb409dde337.png)

![image](https://user-images.githubusercontent.com/7389110/109764334-534cb880-7beb-11eb-839b-8d5a71c4b56a.png)

**Comment by ranjeshj** [comment]
@karenbtlai as FYI
