### ISSUE TITLE
Derived ContentDialog does not get WinUI styles

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#4325]
If you have a class deriving from ContentDialog, it does not seem to get the styles from WinUI. It gets the style from System Xaml instead.

**Comment by MagicAndre1981** [comment]
Is this related to https://github.com/microsoft/microsoft-ui-xaml/issues/2331 ?

**Comment by ranjeshj** [comment]
@MagicAndre1981 that bug seems unrelated.

The issue here is that when you derive a content dialog the new control has its own template. The new styles that come via WinUI2 are not 'default' styles, they are implicit styles, so if you want to derive, then the derived type's style should do one of two things

1. Don't re-template (i.e dont touch the template property). Instead, just build on top of the WinUI2 style like so. <Style TargetType="local:MyCustomDialog" BasedOn="{StaticResource DefaultContentDialogStyle}">
2. If you are going to re-template, then you need to start from the WinUI2 style and make updates based on that. This is not recommended since now the template has been forked.

Instead of creating a derived content dialog, the other option would be to just create a style and override properties that you want to which would achieve the same goal.
