### ISSUE TITLE
XamlParseException with no explanation for a UserControl

### ISSUE THREAD

**Issue by duke7553** [microsoft/microsoft-ui-xaml#4327]
**Describe the bug**
After converting my UWP app to WinUI Desktop, one of the controls fails to load its XAML at runtime throwing a XamlParseException with no context or explanation. 

**Steps to reproduce the bug**

1. Build a UWP app with WinUI 2.x and validate it works
2. Do all necessary steps to convert this to WinUI Desktop and see a vague XAML parse exception

**Expected behavior**
The control should load and not break for exception. Also, the exception should provide better insight about what could cause the problem.

**Screenshots**

**Version Info**

NuGet package version: Microsoft.WinUI 3.0.0-preview4.210210.4

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | YES |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21318)              | YES   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

[NavigationToolbarXAML.txt](https://github.com/microsoft/microsoft-ui-xaml/files/6032522/NavigationToolbarXAML.txt)
[stack.txt](https://github.com/microsoft/microsoft-ui-xaml/files/6032549/stack.txt)

**Comment by StephenLPeters** [comment]
Can you provide a repro app for us to see the issue in?

**Comment by duke7553** [comment]
@StephenLPeters Sure, here's a repro app: https://github.com/duke7553/files-preview

**Comment by duke7553** [comment]
@StephenLPeters The stack trace of this bug looks similar to what's been reported here https://github.com/microsoft/microsoft-ui-xaml/issues/4235 . I'm not sure if they're the same.

**Comment by duke7553** [comment]
@alwu-msft If you run into an issue with App.xaml while compiling this repro app, you should add/remove a single space to trick the XAML compiler into accepting the changes in that file. 

This is because of a separate bug that was reported.

**Comment by alwu-msft** [comment]
@duke7553 `files-preview/Files.Extensions/Files.Extensions.vcxproj` includes files from `..\..\files-community\Files\Files.Extensions\` that don't exist, which prevents it from successfully compiling. Is that intentional? The relative path indicates that files are being pulled from outside of the repository.

**Comment by duke7553** [comment]
@alwu-msft Sorry about that. This is an early version of the WinUI desktop version of the project. I expect the Files.Extensions c++ project to be unneeded at this point for getting the controls to load as we don't depend on it anywhere. However, there is a C++ project included with the repository which means it could be referenced incorrectly. I was able to compile and run the package project on my end, but the XamlParseException was blocking us.

**Comment by duke7553** [comment]
Fixed in Reunion v0.5. Closing this now
