### ISSUE TITLE
ContentDialog control not working in desktop c++/winrt.

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4329]
```
void FlowPanel::myButton_Click(IInspectable const&, RoutedEventArgs const&)
{
	static ContentDialog dialog;

	dialog.Title(winrt::box_value(L"xxx") );
	dialog.Content(winrt::box_value(L"xxx") );

	dialog.ShowAsync();
}
```
report error:
![image](https://user-images.githubusercontent.com/16729017/108943311-8515ca80-7693-11eb-9055-9c22541417ad.png)

**Comment by StephenLPeters** [comment]
ContentDialogs that are created from code need to be assigned a XamlRoot so that the dialog knows where to show the UI.  It doesn't look like you've set the xaml root yourself, at least not in the code you've provided so I think there must be more going on that you haven't included. Are you setting the XamlRoot somewhere?

**Comment by shelllet** [comment]
yes!,  i have not set xaml root , i will try agian. later.  thks!

**Comment by shelllet** [comment]
> ContentDialogs that are created from code need to be assigned a XamlRoot so that the dialog knows where to show the UI. It doesn't look like you've set the xaml root yourself, at least not in the code you've provided so I think there must be more going on that you haven't included. Are you setting the XamlRoot somewhere?

Can ContentDialog show as nonmodal Dialog  ?

**Comment by StephenLPeters** [comment]
No it cannot.

**Comment by shelllet** [comment]
Yeah! you are right ,thks, i will close this issue.

![image](https://user-images.githubusercontent.com/16729017/109086710-1e51e900-7747-11eb-8ab7-d5a00d0497f0.png)

**Comment by Song-haJo** [comment]
Hello! Can you let me know how you succeeded?
