### ISSUE TITLE
ItemsWrapGrid does not rearrange items when MaximumRowsOrColumns has changed at runtime

### ISSUE THREAD

**Issue by KanniyappanP** [microsoft/microsoft-ui-xaml#4332]
**Describe the bug**
ItemsWrapGrid does not rearrange items at runtime if MaximumRowsOrColumns has changed.

I am using ItemsWrapGrid in my CustomControl and the control looks similar as RibbonGallery like in Outlook, MSExcel and MSWord.

I used two ItemsControls in my custom RibbonGallery, one for RibbonGallery and the other for RibbonGalleryPopup. Both ItemsControl arranging control items using ItemsWrapGrid inside the ItemsPanel of ItemsControl and the MaximumRowsOrColumns property handle the max row to display items in horizontal orientation. When I change the MaximumRowsorColumns at runtime, ItemsWrapGrid rearranges the items in RibbonGallery ItemsControl.
But it doesn't work If I open/close the RibbonGallery Popup, temsWrapGrid doesn't rearrange items, MaximumRowsOrColumns only holds runtime values, but it doesn't reflect in the UI.

**Steps to reproduce the bug**
1. Create RibbonGallery and RibbonGalleryItem class with Style. 
2. Populate the Items in RibbonGallery ItemsControl with ItemWrapGrid. 
3. Open Popup using button click and populate same collection to RibbonGalleryPopup ItemsControl with ItemsWrapGrid.
4. Change the MaximumRowsColumnCount at runtime after closing the Popup. (Updated the same collection to the RibbonGallery ItemsControl again).
5. Note ItemsWrapGrid doesn't rearrange the items for the MaximumRowsColumnCount property values.

`

    <Style x:Key="RibbonGalleryStyle"
           TargetType="local:RibbonGallery">
        <Setter Property="BorderThickness"
                Value="1" />
        <Setter Property="Background"
                Value="{StaticResource RibbonGalleryBackground}" />
        <Setter Property="BorderBrush"
                Value="{StaticResource RibbonGalleryClBorderBrush}" />
        <Setter Property="CornerRadius"
                Value="2" />
        <Setter Property="VerticalAlignment"
                Value="Top" />
        <Setter Property="Height"
                Value="{StaticResource RibbonGalleryHeight}" />
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="local:RibbonGallery">
                    <Grid x:Name="RootRibbonGalleryGrid"
                          VerticalAlignment="{TemplateBinding VerticalAlignment}"
                          Background="{TemplateBinding Background}"
                          BorderBrush="{TemplateBinding BorderBrush}"
                          BorderThickness="{TemplateBinding BorderThickness}"
                          CornerRadius="{TemplateBinding CornerRadius}">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition />
                            <ColumnDefinition Width="auto" />
                        </Grid.ColumnDefinitions>
                        <Grid>
                            <ScrollViewer x:Name="GalleryItemsScrollViewer"
                                          HorizontalScrollBarVisibility="Hidden"
                                          HorizontalScrollMode="Disabled"
                                          IsHorizontalRailEnabled="False"
                                          IsVerticalRailEnabled="False"
                                          VerticalScrollBarVisibility="Hidden"
                                          VerticalScrollMode="Disabled">
                                <local:RibbonGalleryItemsControl x:Name="RibbonGalleryItemsControl"
                                                                 ItemContainerStyle="{TemplateBinding ItemContainerStyle}"
                                                                 ItemTemplate="{TemplateBinding ItemTemplate}">
                                    <local:RibbonGalleryItemsControl.ItemsPanel>
                                        <ItemsPanelTemplate>
                                            <ItemsWrapGrid Margin="{StaticResource RibbonGalleryItemsPadding}"
                                                           Orientation="Horizontal" />
                                        </ItemsPanelTemplate>
                                    </local:RibbonGalleryItemsControl.ItemsPanel>
                                </local:RibbonGalleryItemsControl>
                            </ScrollViewer>
                        </Grid>
                        <Grid x:Name="ScrollButtonsGrid"
                              Grid.Column="1"
                              Width="{StaticResource ScrollButtonsGridWidth}"
                              Background="{TemplateBinding Background}"
                              BorderBrush="{TemplateBinding BorderBrush}"
                              BorderThickness="1,0,0,0">
                            <Grid.RowDefinitions>
                                <RowDefinition />
                                <RowDefinition Height="auto" />
                                <RowDefinition />
                                <RowDefinition Height="auto" />
                                <RowDefinition />
                            </Grid.RowDefinitions>
                            <RepeatButton x:Name="ScrollUpButton"
                                          Height="{StaticResource ScrollButtonHeight}"
                                          Style="{StaticResource ScrollRepeatButtonStyle}">
                                <RepeatButton.Content>
                                    <TextBlock FontFamily="ms-appx:///Ribbon.WinUI/Assets/RibbonIcons.ttf#RibbonIcons"
                                               Text="&#xE700;" />
                                </RepeatButton.Content>
                            </RepeatButton>
                            <Border x:Name="ScrollUpButtonBorder"
                                    Grid.Row="1"
                                    Height="1"
                                    BorderBrush="{TemplateBinding BorderBrush}"
                                    BorderThickness="0,0,0,1" />
                            <RepeatButton x:Name="ScrollDownButton"
                                          Grid.Row="2"
                                          Height="{StaticResource ScrollButtonHeight}"
                                          Style="{StaticResource ScrollRepeatButtonStyle}">
                                <RepeatButton.Content>
                                    <TextBlock FontFamily="ms-appx:///Ribbon.WinUI/Assets/RibbonIcons.ttf#RibbonIcons"
                                               Text="&#xE701;" />
                                </RepeatButton.Content>
                            </RepeatButton>
                            <Border x:Name="ScrollDownButtonBorder"
                                    Grid.Row="3"
                                    Height="1"
                                    BorderBrush="{TemplateBinding BorderBrush}"
                                    BorderThickness="0,0,0,1" />
                            <Button x:Name="RibbonGalleryPopupButton"
                                    Grid.Row="4"
                                    Width="{StaticResource ScrollButtonsGridWidth}"
                                    Padding="0"
                                    VerticalAlignment="Stretch"
                                    Background="{StaticResource ScrollRepeatButtonBackgroundBrush}"
                                    BorderThickness="0"
                                    CornerRadius="0">
                                <Button.Content>
                                    <TextBlock FontFamily="ms-appx:///Ribbon.WinUI/Assets/RibbonIcons.ttf#RibbonIcons"
                                               Text="&#xE702;" />
                                </Button.Content>
                            </Button>
                        </Grid>
                        
                        <Popup x:Name="RibbonGalleryPopup"
                               HorizontalOffset="-1"
                               IsLightDismissEnabled="False"
                               IsOpen="{TemplateBinding IsExpanded}"
                               VerticalOffset="-1">
                            <Grid x:Name="RibbonGalleryPopupGrid"
                                  Background="{StaticResource RibbonGalleryPopupBackground}"
                                  BorderBrush="{StaticResource RibbonGalleryPopupBorderBrush}"
                                  BorderThickness="1"
                                  CornerRadius="2">
                                <Grid.RowDefinitions>
                                    <RowDefinition />
                                    <RowDefinition Height="auto" />
                                </Grid.RowDefinitions>
                                <ScrollViewer VerticalScrollBarVisibility="Auto"
                                              VerticalScrollMode="Auto">
                                    
                                    <local:RibbonGalleryItemsControl x:Name="PopupGalleryItemsControl"
                                                                     ItemContainerStyle="{TemplateBinding ItemContainerStyle}"
                                                                     ItemTemplate="{TemplateBinding ItemTemplate}">
                                        <local:RibbonGalleryItemsControl.GroupStyle>
                                            <GroupStyle>
                                                <GroupStyle.HeaderTemplate>
                                                    <DataTemplate>
                                                        <StackPanel>
                                                            <Border Width="{Binding ElementName=RibbonGalleryPopupGrid, Path=Width}"
                                                                    Margin="{StaticResource GroupItemsSeparatorMargin}"
                                                                    BorderBrush="{StaticResource GroupSeparatorBorderBrush}"
                                                                    BorderThickness="0,0,0,1"
                                                                    Visibility="{Binding ElementName=PopupGalleryItemsControl, Converter={StaticResource groupItemsBorderVisibilityConverter}}" />
                                                            <TextBlock Margin="{Binding Key, Converter={StaticResource emptyStringToObjectConverter}}"
                                                                       FontFamily="Sagoe UI"
                                                                       FontSize="14"
                                                                       FontWeight="Bold"
                                                                       Text="{Binding Key}" />
                                                        </StackPanel>
                                                    </DataTemplate>
                                                </GroupStyle.HeaderTemplate>
                                            </GroupStyle>
                                        </local:RibbonGalleryItemsControl.GroupStyle>
                                        <local:RibbonGalleryItemsControl.ItemsPanel>
                                            <ItemsPanelTemplate>
                                                <ItemsWrapGrid Margin="{StaticResource ItemWrapMargin}"
                                                               Orientation="Horizontal" />
                                            </ItemsPanelTemplate>
                                        </local:RibbonGalleryItemsControl.ItemsPanel>
                                    </local:RibbonGalleryItemsControl>
                                </ScrollViewer>
                                <StackPanel Grid.Row="1"
                                            BorderBrush="{StaticResource GroupSeparatorBorderBrush}"
                                            BorderThickness="0,1,0,0">
                                    <Thumb x:Name="ResizeThumb"
                                           HorizontalAlignment="Right"
                                           Style="{StaticResource ResizeThumbStyle}" />
                                </StackPanel>
                                <Grid.Shadow>
                                    <ThemeShadow />
                                </Grid.Shadow>
                            </Grid>
                        </Popup>
                        <VisualStateManager.VisualStateGroups>
                            <VisualStateGroup x:Name="RibbonGalleryPopupStates">
                                <VisualState x:Name="RibbonGalleryPopupOpen">
                                    <VisualState.Setters>
                                        <Setter Target="RibbonGalleryPopupGrid.Width"
                                                Value="{Binding ElementName=RootRibbonGalleryGrid, Path=ActualWidth}" />
                                    </VisualState.Setters>
                                </VisualState>
                                <VisualState x:Name="RibbonGalleryPopupClose">
                                    <VisualState.Setters>
                                        <Setter Target="RibbonGalleryPopupGrid.Width"
                                                Value="{Binding ElementName=RootRibbonGalleryGrid, Path=ActualWidth}" />
                                    </VisualState.Setters>
                                </VisualState>
                            </VisualStateGroup>
                            <VisualStateGroup x:Name="SizeModeStates">
                                <VisualState x:Name="SmallMode">
                                    <VisualState.Setters>
                                        <Setter Target="RootRibbonGalleryGrid.Height"
                                                Value="{StaticResource RibbonGallerySimplifiedModeHeight}" />
                                        <Setter Target="ScrollUpButton.Visibility"
                                                Value="Collapsed" />
                                        <Setter Target="ScrollUpButtonBorder.Visibility"
                                                Value="Collapsed" />
                                        <Setter Target="ScrollDownButton.Visibility"
                                                Value="Collapsed" />
                                        <Setter Target="ScrollDownButtonBorder.Visibility"
                                                Value="Collapsed" />
                                        <Setter Target="RibbonGalleryPopupButton.Height"
                                                Value="{StaticResource ScrollButtonHeight}" />
                                    </VisualState.Setters>
                                </VisualState>
                                <VisualState x:Name="LargeMode">
                                    <VisualState.Setters>
                                        <Setter Target="RootRibbonGalleryGrid.Height"
                                                Value="{StaticResource RibbonGalleryHeight}" />
                                        <Setter Target="ScrollUpButton.Visibility"
                                                Value="Visible" />
                                        <Setter Target="ScrollUpButtonBorder.Visibility"
                                                Value="Visible" />
                                        <Setter Target="ScrollDownButton.Visibility"
                                                Value="Visible" />
                                    </VisualState.Setters>
                                </VisualState>
                            </VisualStateGroup>
                        </VisualStateManager.VisualStateGroups>
                    </Grid>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>

    <Style BasedOn="{StaticResource RibbonGalleryStyle}"
           TargetType="local:RibbonGallery" />
`
`

    
    <Style x:Key="RibbonGalleryItemStyle"
           TargetType="local:RibbonGalleryItem">
        <Setter Property="Background"
                Value="Transparent" />
        <Setter Property="BorderBrush"
                Value="Transparent" />
        <Setter Property="BorderThickness"
                Value="4" />
         
        <Setter Property="VerticalContentAlignment"
                Value="Stretch" />
        <Setter Property="HorizontalContentAlignment"
                Value="Stretch" />
        
        <Setter Property="Foreground"
                Value="{StaticResource RibbonGalleryItemForeground}" />
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="local:RibbonGalleryItem">
                    <Border x:Name="RibbonGalleryItemBorder" Width="90" Height="30"
                          BorderThickness="4"
                          CornerRadius="2">
                        <ContentPresenter  
                                           HorizontalAlignment="{TemplateBinding HorizontalAlignment}"
                                          VerticalAlignment="{TemplateBinding VerticalAlignment}"
                                          HorizontalContentAlignment="{TemplateBinding HorizontalContentAlignment}"
                                          VerticalContentAlignment="{TemplateBinding VerticalContentAlignment}"
                                          Content="{TemplateBinding Content}"
                                          ContentTemplate="{TemplateBinding ContentTemplate}"
                                          ContentTransitions="{TemplateBinding ContentTransitions}"
                                          FontFamily="{TemplateBinding FontFamily}"
                                          FontSize="{TemplateBinding FontSize}"
                                          FontStretch="{TemplateBinding FontStretch}"
                                          FontStyle="{TemplateBinding FontStyle}"
                                          FontWeight="{TemplateBinding FontWeight}"
                                          Foreground="{TemplateBinding Foreground}"
                                          TextWrapping="NoWrap" />
                        <VisualStateManager.VisualStateGroups>
                            <VisualStateGroup x:Name="CommonStates">
                                <VisualState x:Name="Normal" />
                                <VisualState x:Name="PointerOver">
                                    <VisualState.Setters>
                                        <Setter Target="RibbonGalleryItemBorder.BorderBrush"
                                                Value="{StaticResource RibbonGalleryItemHoverBorderBrush}" />
                                    </VisualState.Setters>
                                </VisualState>
                                <VisualState x:Name="Pressed">
                                    <VisualState.Setters>
                                        <Setter Target="RibbonGalleryItemBorder.BorderBrush"
                                                Value="{StaticResource RibbonGalleryItemPressedBorderBrush}" />
                                    </VisualState.Setters>
                                </VisualState>

                            </VisualStateGroup>
                            <VisualStateGroup x:Name="SelectedStates">
                                <VisualState x:Name="Selected">
                                    <VisualState.Setters>
                                        <Setter Target="RibbonGalleryItemBorder.BorderBrush"
                                                Value="{StaticResource RibbonGalleryItemSelectedBorderBrush}" />
                                    </VisualState.Setters>
                                </VisualState>
                                <VisualState x:Name="UnSelected">
                                    <VisualState.Setters>
                                        <Setter Target="RibbonGalleryItemBorder.BorderBrush"
                                                Value="{Binding BorderBrush, RelativeSource={RelativeSource Mode=TemplatedParent}}" />
                                    </VisualState.Setters>
                                </VisualState>
                            </VisualStateGroup>
                        </VisualStateManager.VisualStateGroups>
                    </Border>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>

    <Style BasedOn="{StaticResource RibbonGalleryItemStyle}"
           TargetType="local:RibbonGalleryItem" />`

**Expected behavior**

ItemsWrapGrid should rearrange the items for runtime property changes, when RibbonGallery ItemsControl collection updated when open/close a popup.

**Screenshots**

**Version Info** 
I am using WinUI 3 Preview 4 package.
Window 10 Prop 1909

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
|1909| :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@KanniyappanP do you know if this is an issue with system xaml as well?
