### ISSUE TITLE
Question:  How to populate the ComboBox  by binding the ItemsSource property in desktop c++/winrt?

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4334]
winrt Name:
```
namespace Velkhana
{
	[default_interface]
	runtimeclass Name
	{
		Name(String n, Int32 v);

		String Text;
		Int32 Value;
	}
}
```
Source:

```
IObservableVector<Velkhana:: Name> Source();
```

```
   <ComboBox Header="borderType" x:Name="borderType" ItemsSource="{x:Bind Source}"
                  >
        </ComboBox>
```
![image](https://user-images.githubusercontent.com/16729017/108999080-c7172e80-76dc-11eb-8ab1-2c4cbcff520c.png)

ComboboxItem's text is  class name.

![image](https://user-images.githubusercontent.com/16729017/108999107-ced6d300-76dc-11eb-93d3-11f91c63ce9c.png)

if i set `DisplayMemberPath` property, ComboboxItem's text is  empty.
```
<ComboBox Header="borderType" x:Name="borderType"  ItemsSource="{x:Bind Source}"
                  DisplayMemberPath="Text">
        </ComboBox>
```
![image](https://user-images.githubusercontent.com/16729017/108999218-f6c63680-76dc-11eb-8a30-b6347fe2152b.png)

How can i bind Name's Text filed?

**Comment by StephenLPeters** [comment]
@MikeHillberg FYI

@shelllet can you try making the Text property a Dependency property? I think that might be a requirement for DisplayMemberPath

**Comment by shelllet** [comment]
Great! thks.
![image](https://user-images.githubusercontent.com/16729017/109094805-8d363e80-7755-11eb-851f-a0f8bff4b0cb.png)

**Comment by lxy20221110** [comment]
> Great! thks. ![image](https://user-images.githubusercontent.com/16729017/109094805-8d363e80-7755-11eb-851f-a0f8bff4b0cb.png)


Can you tell me how make a Dependency property? I have the same problem
