### ISSUE TITLE
Question: How to compile C# WinUI 3 desktop app?

### ISSUE THREAD

**Issue by jskop** [microsoft/microsoft-ui-xaml#4335]
Hi,

I installed Visual Studio Enterprise 2019 Preview 4 few days ago and WinUI 3 Preview 4 extension. I've created brand new C# WinUI blank desktop packaged app, so far so good. The problems started when I tried to build/run the app (with no additional code or controls) - compiler returned **WMC999 Cannot find type WinRT.IWinRTObject in module WinRT.Runtime.dll**. Then I thought it'd be good try with CsWinRT v. 1.1.0. After adding Microsoft.Windows.CsWinRT package the WMC999 error disappeared but now there's another one: **CS0012 The type 'SuspendingEventArgs' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Windows.SDK.NET, Version=10.0.18362.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35'**. This is what I ended up with. I've installed required Windows SDKs  (17134, 18362 and 19041).
Am I missing something?

**Comment by StephenLPeters** [comment]
@alwu-msft and @stevenbrix this sounds really similar to some issues we've had previously around the vsix not updating the project files with the sdk version, but we can't seem to find those issues.

**Comment by alwu-msft** [comment]
@StephenLPeters No, I don't think is similar.

@jskop I don't think it should've been necessary to add an explicit reference to CsWinr 1.1.0 as we are already pulling it in for you.

@Scottj1s Any ideas what might be going wrong here?

**Comment by jskop** [comment]
Here are my VS installations:
![image](https://user-images.githubusercontent.com/31615175/109115088-d3cc6e80-773e-11eb-8edf-5873eadeedcc.png)
Here are my .NET Core skds:
![image](https://user-images.githubusercontent.com/31615175/109115131-e777d500-773e-11eb-92d5-b2ecb912b8ee.png)
Error message without CsWinRT package:
![image](https://user-images.githubusercontent.com/31615175/109115772-d4b1d000-773f-11eb-915d-04388b3e1ce3.png)
Error message after adding package:
![image](https://user-images.githubusercontent.com/31615175/109116021-2c503b80-7740-11eb-8f1d-74f4b19d9dc6.png)

**Comment by jskop** [comment]
Hi
I've fixed the issue. I installed x86 .NET 6 alpha some time ago which messed with targeting packs. Project dependencies were pointing to Microsoft.Windows.SDK.NET.Ref 10.0.18362.4-preview which was the root cause of CS0012. Included WinRT.Runtime.dll was also missing WinRT.IWinRTObject.
Anyways thank you for your engagement.

Best Regards,
jskop
