### ISSUE TITLE
TabViewItem Headertemplate

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4338]
Can I replace the default tab strip with an AppBarButton for example ? 

```
 <TabViewItem.HeaderTemplate>
...
                        <AppBarButton Icon="Like" Label="SymbolIcon" Click="AppBarButton_Click"/>
...
 </TabViewItem.HeaderTemplate>
```

**Comment by StephenLPeters** [comment]
You can put whatever you want in your header template, this should work, although this seems pretty strange. What are you trying to accomplish?

**Comment by sigmarsson** [comment]
I aim to spawn a new stand alone window by pulling out of its context. By today I learnt TabView might not be necessary fro this purpose. Probalby must only wire up the Drag & Drop related events of another, more simply control.
