### ISSUE TITLE
ItemsRepeater - Unable to explicitly detach recycled element from being parented to ItemsRepeater.

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#434]
**Describe the bug**
I was creating a small sample of how ItemsRepeater could be used in response to https://stackoverflow.microsoft.com/questions/123242/best-approach-for-simple-non-scrolling-ui-virtualization#comment107458_123242.  I have a simple custom layout that only requests enough UIElements to fill the viewport and no more.  This is unlike ItemsControl which will first create all the UIElement needed to match the number of items in the data source before calling the Panel.

The requirement from the post is that it (eventually) should be possible to release unused elements rather than recycle them.  I've tried a few different things in the app to released the recycled elements, but been unable to do so.

**Steps to reproduce the bug**

Internal issue: https://microsoft.visualstudio.com/OS/_queries/edit/19643272/?triage=true

**Comment by chingucoding** [comment]
I think this sounds more like a new API then a bug. Could this be realized through a custom ElementFactory? If the developer provides their own ElementFactory, you can handle recycling as you want, e.g. release the items instead of putting them into a RecyclePool to access them later. What do you think @ranjeshj ?

**Comment by ranjeshj** [comment]
Yes. An API or some method where we don't keep the containers still parented to the repeater is what we need here. A custom factory which does this is a reasonable workaround in its place.

**Comment by chingucoding** [comment]
Given that there is no API on ItemsRepeater to get the realized items, what is the easiest way for users to clear unused elements then? Should we expect users to get the children through the visual tree and pass them to the ItemsRepeater to have them freed detached from the repeater?

**Comment by ranjeshj** [comment]
The only other way I can think of is by setting ItemTemplate and ItemsSource to null, which I think will end up removing everything (based on the code [here](https://github.com/microsoft/microsoft-ui-xaml/blob/607b6de45ac355b4bf7d1db102c35430d3da54e9/dev/Repeater/ViewManager.cpp#L144))

**Comment by chingucoding** [comment]
Yes, setting the itemtemplate or itemssource to null doesn't sound like a good way to handle this. Would this new API require us to have a new method on ElementFactory to "clear" the element? After all, a RecyclePool or ElementFactory could do some stuff behind the scenes that would expect it to get every element back, e.g. when all templates in an array. Detaching the elements without telling the ElementFactory would result in gaps in such array.
