### ISSUE TITLE
ContentDialog.ShowAsync() throws ArgumentException

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4341]
In which case do you throw this ex ? 

![image](https://user-images.githubusercontent.com/43340959/109068940-ce483780-76f0-11eb-9614-d980dc5ebe24.png)

**Comment by StephenLPeters** [comment]
This is because you have not set the XamlRoot of your Dialog. This is a dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/4251
