### ISSUE TITLE
Prism Incorporation

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4346]
Do you know when **Prism** capabilities will be available across a **WinUI project** ? Type registration and its messaging model is somewhat essential to communicate across view models.

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI @sigmarsson this is prism you are referring to right? https://prismlibrary.com/#learn

**Comment by sigmarsson** [comment]
Yes and they opened dialog with the community as well, I guess ; https://github.com/PrismLibrary/Prism
Through Uno - Prism.Uno - it is supposed to be feasible but never tried it for size, neither did I fully understand the concept and Uno/Prism architecture per se.

**Comment by sigmarsson** [comment]
Probably Prism is already available in WinUI today if you install the "UNO Platform Solution Templates" extension to Visual Studio and select the template Uno Cross Platform (Prism) so through the Uno Cross Platform the Prism library is now available. It is probably nothing new, just found today. 

https://github.com/unoplatform/Uno.Prism/issues/15
