### ISSUE TITLE
[Docs] - Roadmap show wrong "latest version"

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#4352]
**Describe the bug**

The [image in the roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-30-timelines-and-milestones) incorrectly highlights Preview 3 as the latest version.

![roadmap image from above linked page](https://github.com/microsoft/microsoft-ui-xaml/raw/master/docs/images/winui-roadmap.jpg)

**Steps to reproduce the bug**

1. Go to https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-30-timelines-and-milestones
2. See that Preview 3 has an adornment indicating it as the latest release

**Expected behavior**

Preview 4 is the latest released version and should be indicated as such.

**Screenshots**

see above.

**Version Info**

n/a

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| n/a | n/a |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | n/a   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | n/a|
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@anawishnoff FYI
