### ISSUE TITLE
The descendant of standard ComboBox loses CornerRadius

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#4362]
**Describe the bug**
Hi, it looks very strange but the inheritor of ComboBox loses CornerRadius

**Steps to reproduce the bug**
```xaml
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center" Spacing="10">
        <ComboBox Width="200"/>
        <local:MyComboBox Width="200"/>
</StackPanel>
```

```csharp
 public class MyComboBox : ComboBox { }
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/47348109/109276604-49136e80-7827-11eb-998b-b4c968d2b5c8.png)

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4] If you seeing your issue in older previews, please try preview4.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
I think that, because of the way that Winui2 is currently being integrated into winui3, you need to include this in your application.resource or page.resources 

```
    <Style TargetType="ComboBox" BasedOn="{StaticResource DefaultComboBoxStyle}"/>
```

**Comment by StephenLPeters** [comment]
Closing the issue, but if this doesn't work or you want more info just post back here.
