### ISSUE TITLE
WinUI for Desktop Print

### ISSUE THREAD

**Issue by Fernand-Delavy** [microsoft/microsoft-ui-xaml#4363]
Visual Studio 2019 16.9.0 Preview5.0 and Windows 10 Pro 19042.844
Goal is use of Windows WinUI for Desktop
1. I do not found how to change the app Titre from WinUI Desktop to my name 
   this crash :
     var appView = ApplicationView.GetForCurrentView();
     var titleBar = appView.TitleBar;
2. Then i want to print app crash
    The print works on UWP standard App
    The print works on UWP WinUI  App
    The print crash on WinUI Desktop  App
Here the Print xaml:
`
<Page
    x:Class="Santé.SantéIImprimer"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Santé"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d" SizeChanged="Grid_SizeChanged"
    x:Name="RootPage">

    <Page.Resources>
        <local:ColorConverter x:Key="FormatConverter" />
    </Page.Resources>

    <ScrollViewer HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto">
        <Grid Name="grid" Loaded="Grid_Loaded">
            <CommandBar x:Name="topBar" IsOpen="True" IsSticky="True"  HorizontalAlignment="Right" Background="{Binding ConverterParameter='Back', Converter={StaticResource FormatConverter}}"  
                        BorderBrush="{Binding ConverterParameter='Back', Converter={StaticResource FormatConverter}}" Closing="TopBar_Closing">
                <AppBarElementContainer>
                    <StackPanel Orientation="Horizontal">
                        <AppBarButton x:Name="backBtn"  Label="Retour" Icon="Back" Click="RetourBtn_Click"  ToolTipService.ToolTip="Retour" />
                        <ComboBox x:Name="pagesBox" HorizontalAlignment="Left" Margin="0,0,0,0" VerticalAlignment="Top" Width="120" SelectionChanged="PagesBox_SelectionChanged"/>
                        <AppBarButton x:Name="printBtn" Label="Imprimer"  Click="ImprimerBtn_Click" ToolTipService.ToolTip="Imprimer">
                            <AppBarButton.Icon>
                                <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE749;"/>
                            </AppBarButton.Icon>
                        </AppBarButton>
                        <AppBarButton x:Name="homeBtn" Label="Début" ToolTipService.ToolTip="Première page" Click="HomeBtn_Click">
                            <AppBarButton.Icon>
                                <FontIcon FontFamily="Segoe UI Symbol" Glyph="&#xE100;" />
                            </AppBarButton.Icon>
                        </AppBarButton>
                        <AppBarButton x:Name="pgUpBtn" Label="Précédente" ToolTipService.ToolTip="Page précédente" Click="PagUp_Click">
                            <AppBarButton.Icon>
                                <FontIcon FontFamily="Segoe UI Symbol" Glyph="&#xE112;" />
                            </AppBarButton.Icon>
                        </AppBarButton>
                        <AppBarButton x:Name="pgDnBtn" Label="Suivante"  ToolTipService.ToolTip="Page suivante" Click="PgDn_Click">
                            <AppBarButton.Icon>
                                <FontIcon FontFamily="Segoe UI Symbol" Glyph="&#xE111;" />
                            </AppBarButton.Icon>
                        </AppBarButton>
                        <AppBarButton x:Name="endBtn" Label="Dernière"  ToolTipService.ToolTip="Dernière page" Click="EndBtn_Click">
                            <AppBarButton.Icon>
                                <FontIcon FontFamily="Segoe UI Symbol" Glyph="&#xE101;" />
                            </AppBarButton.Icon>
                        </AppBarButton>
                    </StackPanel>
                </AppBarElementContainer>
            </CommandBar>
            <Canvas x:Name="canvas"/>
            <ProgressRing x:Name="waitRing" HorizontalAlignment="Left" Margin="1240,100,0,0" VerticalAlignment="Top" Height="55" Width="65"/>
        </Grid>
    </ScrollViewer>
</Page>
`
using System;
using System.Collections.Generic;
using System.Linq;
using Windows.Foundation;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI;
using Microsoft.UI.Text;
using Windows.UI.Core;
using Windows.Graphics.Printing;
using Microsoft.UI.Xaml.Printing;
using Windows.Graphics.Printing.OptionDetails;
using System.Text.RegularExpressions;
using Windows.Storage;

namespace Santé
{
    public sealed partial class SantéIImprimer : Page
    {
        // Mes variables
        public static string                action;
        private Size?                       _pageSize;
        private Rect?                       _imageableRect;
        private Dictionary<int, UIElement>  _pages;
        private PrintDocument               _document;
        private PrintManager                manager;
        private static int                  noPage;
        private Dictionary<int, UIElement>  pages;
        private bool                        pageRangeEditVisible = false;
        private Dictionary<int, UIElement>  pageList;
        private int                         totalPages;
        public static string                criteres;
        private static int                  pageActuelle;

        /*************************************************************************/

        public SantéIImprimer()
        {
            this.InitializeComponent();
        }

        /*************************************************************************/

        private void Grid_Loaded(object sender, RoutedEventArgs e)
        {
            grid.Background = SantéMenu.backColor;
            pagesBox.Visibility = Visibility.Collapsed;
            pageList = new Dictionary<int, UIElement>();
            Imprime();
            totalPages = pages.Count;
            pageActuelle = 1;
            AfficheBoutons();
        }

        /*************************************************************************/

        private void HomeBtn_Click(object sender, RoutedEventArgs e)
        {
            pageActuelle = 1;
            AfficheBoutons();
            pagesBox.SelectedIndex = 0;
        }

        /*************************************************************************/

        private void PgDn_Click(object sender, RoutedEventArgs e)
        {
            pageActuelle++;
            if (pageActuelle > pagesBox.Items.Count)
                pageActuelle = pagesBox.Items.Count;
            AfficheBoutons();
            pagesBox.SelectedIndex = pageActuelle - 1;
        }

        /*************************************************************************/

        private void PagUp_Click(object sender, RoutedEventArgs e)
        {
            pageActuelle--;
            if (pageActuelle < 1)
                pageActuelle = 1;
            AfficheBoutons();
            pagesBox.SelectedIndex = pageActuelle - 1;
        }

        /*************************************************************************/

        private void EndBtn_Click(object sender, RoutedEventArgs e)
        {
            pageActuelle = pagesBox.Items.Count;
            AfficheBoutons();
            pagesBox.SelectedIndex = pageActuelle - 1;
        }

        /*************************************************************************/

        private void AfficheBoutons()
        {
            homeBtn.Visibility = Visibility.Collapsed;
            pgDnBtn.Visibility = Visibility.Collapsed;
            pgUpBtn.Visibility = Visibility.Collapsed;
            endBtn.Visibility = Visibility.Collapsed;
            if (pagesBox.Items.Count == 1)
                return;
            if (pageActuelle == pagesBox.Items.Count)
            {
                homeBtn.Visibility = Visibility.Visible;
                pgUpBtn.Visibility = Visibility.Visible;
                return;
            }
            if (pageActuelle == 1)
            {
                endBtn.Visibility = Visibility.Visible;
                pgDnBtn.Visibility = Visibility.Visible;
                return;
            }
            if (pagesBox.Items.Count > 1)
            {
                homeBtn.Visibility = Visibility.Visible;
                pgDnBtn.Visibility = Visibility.Visible;
                pgUpBtn.Visibility = Visibility.Visible;
                endBtn.Visibility = Visibility.Visible;
            }
        }

        /*************************************************************************/

        private void Imprime()
        {
            int ligne;
            int lignesParPage = 50;
            ligne = lignesParPage;
            Données don;
            string str;
            int hauteur = 20;
            int fontSize = 12;
            DateTime dt;
            int[] hpos = { 80, 110, 210, 260, 310, 360, 650 };
            noPage = 0;
            pages = new Dictionary<int, UIElement>();
            TextBox textBox;
            for (int i = 0; i < SantéFichier.donnees.Count; i++)
            {
                don = SantéFichier.donnees[i];
                if (ligne >= lignesParPage)
                {
                    if (noPage > 0)
                    {
                        pages.Add(noPage, canvas);
                        pagesBox.Items.Add("Page : " + noPage.ToString());
                    }
                    noPage += 1;
                    canvas = new Canvas
                    {
                        Width = 794,
                        Height = 1122
                    };
                    ligne = 3;
                    dt = DateTime.Now;
                    str = "Liste des " + SantéFichier.donnees.Count.ToString() +
                        " données le " + dt.ToString("dd.MM.yyyy");
                    str += " pour : " + SantéFichier.bases[0].Nom;
                    textBox = new TextBox()
                    {
                        Text = str,
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Bold,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Left;
                    textBox.Margin = new Thickness() { Left = hpos[0], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    textBox = new TextBox()
                    {
                        Text = "Page : " + noPage.ToString(),
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Normal,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Right;
                    textBox.Width = 100;
                    textBox.Margin = new Thickness() { Left = hpos[6], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    ligne++;
                    textBox = new TextBox()
                    {
                        Text = "Nom du fichier : " + System.IO.Path.GetFileName(SantéFichier.nomFichier),
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Bold,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Left;
                    textBox.Width = 500;
                    textBox.Margin = new Thickness() { Left = hpos[0], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    ligne += 2;
                    textBox = new TextBox()
                    {
                        Text = "Date",
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Bold,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Left;
                    textBox.Margin = new Thickness() { Left = hpos[0], Top = (ligne * hauteur) - 10, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    textBox = new TextBox()
                    {
                        Text = "Glycémie",
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Bold,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Right;
                    textBox.Width = 100;
                    textBox.Margin = new Thickness() { Left = hpos[1], Top = (ligne * hauteur) - 10, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    textBox = new TextBox()
                    {
                        Text = "Sys",
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Bold,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Left;
                    textBox.Width = 100;
                    textBox.Margin = new Thickness() { Left = hpos[2], Top = (ligne * hauteur) - 10, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    textBox = new TextBox()
                    {
                        Text = "Dia",
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Bold,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Left;
                    textBox.Width = 100;
                    textBox.Margin = new Thickness() { Left = hpos[3], Top = (ligne * hauteur) - 10, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    textBox = new TextBox()
                    {
                        Text = "Pouls",
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Bold,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Left;
                    textBox.Width = 100;
                    textBox.Margin = new Thickness() { Left = hpos[4], Top = (ligne * hauteur) - 10, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    textBox = new TextBox()
                    {
                        Text = "Remarque",
                        FontSize = fontSize,
                        BorderBrush = new SolidColorBrush(Colors.White),
                        BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                        IsReadOnly = true,
                        FontWeight = FontWeights.Bold,
                        Foreground = new SolidColorBrush(Colors.Black)
                    };
                    textBox.TextAlignment = TextAlignment.Left;
                    textBox.Width = 100;
                    textBox.Margin = new Thickness() { Left = hpos[5], Top = (ligne * hauteur) - 10, Right = 0, Bottom = 0 };
                    canvas.Children.Add(textBox);
                    ligne += 1;
                } // Fin du titre
                dt = don.DateDonnee;
                textBox = new TextBox()
                {
                    Text = dt.ToString("dd.MM.yyyy"),
                    FontSize = fontSize,
                    BorderBrush = new SolidColorBrush(Colors.White),
                    BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                    IsReadOnly = true,
                    Foreground = new SolidColorBrush(Colors.Black)
                };
                textBox.TextAlignment = TextAlignment.Left;
                textBox.Margin = new Thickness() { Left = hpos[0], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                canvas.Children.Add(textBox);
                str = don.Diabète;
                textBox = new TextBox()
                {
                    Text = str,
                    FontSize = fontSize,
                    BorderBrush = new SolidColorBrush(Colors.White),
                    BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                    IsReadOnly = true,
                    Foreground = new SolidColorBrush(Colors.Black)
                };
                textBox.TextAlignment = TextAlignment.Right;
                textBox.Width = 100;
                textBox.Margin = new Thickness() { Left = hpos[1], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                canvas.Children.Add(textBox);
                str = don.Sys;
                textBox = new TextBox()
                {
                    Text = str,
                    FontSize = fontSize,
                    BorderBrush = new SolidColorBrush(Colors.White),
                    BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                    IsReadOnly = true,
                    Foreground = new SolidColorBrush(Colors.Black)
                };
                textBox.TextAlignment = TextAlignment.Left;
                textBox.Margin = new Thickness() { Left = hpos[2], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                canvas.Children.Add(textBox);
                str = don.Dia;
                textBox = new TextBox()
                {
                    Text = str,
                    FontSize = fontSize,
                    BorderBrush = new SolidColorBrush(Colors.White),
                    BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                    IsReadOnly = true,
                    Foreground = new SolidColorBrush(Colors.Black)
                };
                textBox.TextAlignment = TextAlignment.Left;
                textBox.Margin = new Thickness() { Left = hpos[3], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                canvas.Children.Add(textBox);
                str = don.Pouls;
                textBox = new TextBox()
                {
                    Text = str,
                    FontSize = fontSize,
                    BorderBrush = new SolidColorBrush(Colors.White),
                    BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                    IsReadOnly = true,
                    Foreground = new SolidColorBrush(Colors.Black)
                };
                textBox.TextAlignment = TextAlignment.Center;
                textBox.Margin = new Thickness() { Left = hpos[4], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                canvas.Children.Add(textBox);
                str = don.Remarque;
                textBox = new TextBox()
                {
                    Text = str,
                    FontSize = fontSize,
                    BorderBrush = new SolidColorBrush(Colors.White),
                    BorderThickness = new Thickness() { Left = 0, Top = 0, Bottom = 0, Right = 0 },
                    IsReadOnly = true,
                    Foreground = new SolidColorBrush(Colors.Black)
                };
                textBox.TextAlignment = TextAlignment.Left;
                textBox.Margin = new Thickness() { Left = hpos[5], Top = ligne * hauteur, Right = 0, Bottom = 0 };
                canvas.Children.Add(textBox);
                if (i == SantéFichier.donnees.Count - 1)
                {
                    pages.Add(noPage, canvas);
                    pagesBox.Items.Add("Page : " + noPage.ToString());
                }
                ligne++;
            }
            pagesBox.SelectedIndex = 0;
        }

        /*************************************************************************/

        private void PagesBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (canvas != null)
                grid.Children.Remove(canvas);
            waitRing.Visibility = Visibility.Visible;
            waitRing.IsActive = true;
            canvas = pages[pagesBox.SelectedIndex + 1] as Canvas;
            canvas.VerticalAlignment = VerticalAlignment.Top;
            canvas.HorizontalAlignment = HorizontalAlignment.Left;
            canvas.Margin = new Thickness() { Left = 10, Top = 100, Bottom = 0, Right = 0 };
            canvas.Background = new SolidColorBrush(Colors.White);
            grid.Children.Add(canvas);
            waitRing.IsActive = false;
        }

        /*************************************************************************/

        private void RetourBtn_Click(object sender, RoutedEventArgs e)
        {
            this.Frame.GoBack();
        }

        /*************************************************************************/

        private async void ImprimerBtn_Click(object sender, RoutedEventArgs e)
        {
            OnRegister(sender, e);
            await Windows.Graphics.Printing.PrintManager.ShowPrintUIAsync();
        }

        /*************************************************************************/

        void OnRegister(object sender, RoutedEventArgs e)
        {
            manager = PrintManager.GetForCurrentView(); // System.Runtime.InteropServices.COMException: 'Interface non enregistrée (0x80040155)'
            manager.PrintTaskRequested += OnPrintTaskRequested;
        }

        /*************************************************************************/

        void OnPrintTaskRequested(PrintManager sender, PrintTaskRequestedEventArgs args)
        {
            var deferral = args.Request.GetDeferral();
            PrintTask printTask = args.Request.CreatePrintTask("Santé",
                OnPrintTaskSourceRequestedHandler);
            printTask.Completed += OnPrintTaskCompleted;
            PrintTaskOptionDetails printDetailedOptions = PrintTaskOptionDetails.GetFromPrintTaskOptions(printTask.Options);
            PrintCustomItemListOptionDetails pageFormat = printDetailedOptions.CreateItemListOption("PageRange", "Page Range");
            pageFormat.AddItem("PrintAll", "Tout");
            pageFormat.AddItem("PrintRange", "Choisir");
            IList<string> displayedOptions = printDetailedOptions.DisplayedOptions;
            displayedOptions.Clear();
            displayedOptions.Add(Windows.Graphics.Printing.StandardPrintTaskOptions.Copies);
            displayedOptions.Add(Windows.Graphics.Printing.StandardPrintTaskOptions.Orientation);
            displayedOptions.Add(Windows.Graphics.Printing.StandardPrintTaskOptions.ColorMode);
            displayedOptions.Add("PageRange");
            PrintCustomTextOptionDetails pageRangeEdit =
                printDetailedOptions.CreateTextOption("PageRangeEdit", "Choix par ex : 2-5 ou 2,4,5");
            printDetailedOptions.OptionChanged += PrintDetailedOptions_OptionChanged;

            deferral.Complete();
        }

        /*************************************************************************/

        async void PrintDetailedOptions_OptionChanged(PrintTaskOptionDetails sender, PrintTaskOptionChangedEventArgs args)
        {
            if (args.OptionId == null)
                return;
            string optionId = args.OptionId.ToString();
            if (optionId == "PageRange")
            {
                IPrintOptionDetails pageRange = sender.Options[optionId];
                string pageRangeValue = pageRange.Value.ToString();
                switch (pageRangeValue)
                {
                    case "PrintRange":
                        // Add PageRangeEdit custom option to the option list
                        sender.DisplayedOptions.Add("PageRangeEdit");
                        pageRangeEditVisible = true;
                        await Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
                                                  () =>
                                                  {
                                                      ShowContent(null);
                                                  });
                        break;
                    default:
                        await Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
                                                  () =>
                                                  {
                                                      ShowContent(null);
                                                  });
                        RemovePageRangeEdit(sender);
                        break;
                }
                Refresh();
            }
            else if (optionId == "PageRangeEdit")
            {
                IPrintOptionDetails pageRange = sender.Options[optionId];
                // Expected range format (p1,p2...)*, (p3-p9)* ...
                if (!Regex.IsMatch(pageRange.Value.ToString(), @"^\s*\d+\s*(\-\s*\d+\s*)?(\,\s*\d+\s*(\-\s*\d+\s*)?)*$"))
                {
                    pageRange.ErrorText = "Choix invalide ! (ex : 1-3, 5)";
                }
                else
                {
                    pageRange.ErrorText = string.Empty;
                    Exception exp = GetPagesInRange(pageRange.Value.ToString());
                    if (exp != null)
                        pageRange.ErrorText = exp.Message;
                    Refresh();
                }
            }
        }

        /*************************************************************************/

        private static readonly char[] enumerationSeparator = new char[] { ',' };
        private static readonly char[] rangeSeparator = new char[] { '-' };

        private Exception GetPagesInRange(string pageRange)
        {
            string[] rangeSplit = pageRange.Split(enumerationSeparator);
            pageList.Clear();
            foreach (string range in rangeSplit)
            {
                if (range.Contains("-"))
                {
                    string[] limits = range.Split(rangeSeparator);
                    int start = int.Parse(limits[0]);
                    int end = int.Parse(limits[1]);
                    if ((start < 1) || (end > totalPages) || (start >= end))
                        return new Exception(string.Format("Choix invalide : {0} - {1}", start, end));
                    for (int i = start; i <= end; ++i)
                        pageList.Add(i, canvas);
                    continue;
                }
                var pageNr = int.Parse(range);
                if (pageNr < 1)
                    return new Exception(string.Format("Page invalide : {0}", pageNr));
                if (pageNr > totalPages)
                    return new Exception(string.Format("Page invalide : {0}", pageNr));
                pageList.Add(pageNr, canvas);
            }
            return null;
        }

        /*************************************************************************/

        private void ShowContent(string selectionText)
        {
            if (selectionText != null)
                selectionText.ToString();
        }

        /*************************************************************************/

        private async void Refresh()
        {
            // Refresh
            await Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
                                    () =>
                                    {
                                        // Refresh preview
                                        _document.InvalidatePreview();
                                    });
        }

        /*************************************************************************/

        private void RemovePageRangeEdit(PrintTaskOptionDetails printTaskOptionDetails)
        {
            if (pageRangeEditVisible)
            {
                string lastDisplayedOption = printTaskOptionDetails.DisplayedOptions.FirstOrDefault(p =>
                    p.Contains("PageRangeEdit"));
                if (!string.IsNullOrEmpty(lastDisplayedOption))
                    printTaskOptionDetails.DisplayedOptions.Remove(lastDisplayedOption);
                pageRangeEditVisible = false;
            }
        }

        /*************************************************************************/

        void OnPrintTaskCompleted(PrintTask sender, PrintTaskCompletedEventArgs args)
        {
            this._pageSize = null;
            this._imageableRect = null;
            this._document = null;
            this._pages = null;
            manager.PrintTaskRequested -= OnPrintTaskRequested;
        }

        /*************************************************************************/

        async void OnPrintTaskSourceRequestedHandler(PrintTaskSourceRequestedArgs args)
        {
            var deferral = args.GetDeferral();
            await this.Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
              () =>
              {
                  this._document = new PrintDocument();
                  this._document.Paginate += OnPaginate;
                  this._document.GetPreviewPage += OnGetPreviewPage;
                  this._document.AddPages += OnAddPages;
                  // Tell the caller about it.   
                  args.SetSource(this._document.DocumentSource);
              }
            );
            deferral.Complete();
        }

        /*************************************************************************/

        async void OnAddPages(object sender, AddPagesEventArgs e)
        {
            await this.Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
            () =>
            {
                if (pageList.Count == 0)
                    for (int i = 0; i < pages.Count; i++)
                        this._document.AddPage(pages[i + 1]);
                else
                {
                    for (int i = 0; i < pageList.Count; i++)
                        this._document.AddPage(pages[pageList.Keys.ElementAt(i)]);
                }

                this._document.AddPagesComplete();
            });
        }

        /*************************************************************************/

        async void OnGetPreviewPage(object sender, GetPreviewPageEventArgs e)
        {
            await this.Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
           () =>
           {
               if (this._pages == null)
                   this._pages = new Dictionary<int, UIElement>();
               if (!this._pages.ContainsKey(e.PageNumber))
               {
                   canvas.Width = this._pageSize.Value.Width;
                   canvas.Height = this._pageSize.Value.Height;
                   this._pages[e.PageNumber] = pages[e.PageNumber];
               }
               this._document.SetPreviewPage(e.PageNumber,
               this._pages[e.PageNumber]);
           });
        }

        /*************************************************************************/

        async void OnPaginate(object sender, PaginateEventArgs e)
        {
            await this.Dispatcher.RunAsync(CoreDispatcherPriority.Normal,
            () =>
            {
                // I have one page and that's *FINAL* !   
                this.GetPageSize(e);
                if (pageList.Count == 0)
                    this._document.SetPreviewPageCount(pages.Count, PreviewPageCountType.Final);
                else
                    this._document.SetPreviewPageCount(pageList.Count, PreviewPageCountType.Final);
            });
        }

        /*************************************************************************/

        void GetPageSize(PaginateEventArgs e)
        {
            if (this._pageSize == null)
            {
                PrintPageDescription description = e.PrintTaskOptions.GetPageDescription(
                (uint)e.CurrentPreviewPageNumber);

                this._pageSize = description.PageSize;
                this._imageableRect = description.ImageableRect;
                _imageableRect.ToString();
            }

        }

        /*************************************************************************/

        private void Grid_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            topBar.Margin = new Thickness() { Left = SantéMenu.positionGauche, Top = 0, Bottom = 0, Right = 0 };
        }

        /*************************************************************************/

        private void TopBar_Closing(object sender, object e)
        {
            ApplicationDataContainer settings = ApplicationData.Current.LocalSettings;
            if (Convert.ToBoolean(settings.Values["TopBar"]))
                topBar.IsOpen = true; topBar.IsOpen = true;
        }

        /*************************************************************************/
    }
}

The crash is there :  manager = PrintManager.GetForCurrentView();

**Comment by StephenLPeters** [comment]
similar to https://github.com/microsoft/microsoft-ui-xaml/issues/4375 @Fernand-Delavy is there a difference between these two issues?

**Comment by Fernand-Delavy** [comment]
Problem no solution found with PrintManage  crash. ( PrintManager.GetForCurrentView() )

May be it is possible to use Win32 PrintDialog, but i do no know how to do this.

**Comment by ranjeshj** [comment]
This looks like a dup of #4375. Lets track it using that bug.
