### ISSUE TITLE
XLS0502 XAML The type 'RadioButtons' does not support direct content.

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4366]
The XAML Controls Gallery app recommends direct content of this control. I witness this error, though a rebuild makes it vanished. 

![image](https://user-images.githubusercontent.com/43340959/109334564-2dc55500-7861-11eb-8b21-aefb20f47477.png)

![image](https://user-images.githubusercontent.com/43340959/109334618-3f0e6180-7861-11eb-9557-2e4b7cd102d3.png)

**Comment by StephenLPeters** [comment]
duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4385

**Comment by StephenLPeters** [comment]
You can fix locally by doing

```
<RadioButtons>
   <RadioButtons.Items>
      ...
   </RadioButtons.Items>
</RadioButtons>
```
