### ISSUE TITLE
Are you TempleteBinding savvy ? 

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4367]
I have set a `TempleteBinding` between properties but target is not updating when source is.

`IsChecked="{TemplateBinding IsChecked}" `

WPF offers `UpdateSourceTrigger` to get updated, is there anything similar existing here too ?

**Comment by StephenLPeters** [comment]
Can you please provide more details about how you achieved the behavior you think is incorrect?

**Comment by sigmarsson** [comment]
#4373
