### ISSUE TITLE
TeachingTip should follow BorderThickness

### ISSUE THREAD

**Issue by ismaelestalayo** [microsoft/microsoft-ui-xaml#4369]
# Proposal: `TeachingTip` should follow the specified BorderThickness

## Summary

The `TeachingTip` control can be personalized with various attributes, like `BorderBrush`, but it does not follow the `BorderThickness` attribute. Simply create a new `TeachingTip` in any app and change the `BorderBrush` and `BorderThickness` attributes like so to reproduce:
```xaml
<muxc:TeachingTip
    Title="Title" Subtitle="Message." IsOpen="True"
    BorderBrush="DodgerBlue"
    BorderThickness="0 4 0 0"/>
```

![image](https://user-images.githubusercontent.com/17100634/109355833-1fd2fc80-7880-11eb-8ef0-98aada8a6da4.png)

I believe it's because the Thickness is hardcoded to 1 on the [TeachingTipPage.xaml](https://github.com/microsoft/microsoft-ui-xaml/blob/7dbf5ffcfd4f03d625cc213d56ea91e53c70d873/dev/TeachingTip/TestUI/TeachingTipPage.xaml#L14)

## Rationale

* I believe that while by default the `BorderThickness` should be 1, it should be available to developers for us to modify without having to re-template the control.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to better modify the style of `TeachingTip` | Should |

**Comment by chingucoding** [comment]
I would like to work on this.
