### ISSUE TITLE
Will you port AccountsSettingsPane Class to WinUI ? 

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4374]
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.ApplicationSettings.AccountsSettingsPane?view=winrt-19041

**Comment by StephenLPeters** [comment]
@MikeHillberg Do you know what this is?

**Comment by sigmarsson** [comment]
@StephenLPeters, it is a modal dialog designed to exhibit accounts retrieved from a provider. e.g.

`await WebAuthenticationCoreManager.FindAccountProviderAsync("https://login.microsoft.com", "consumers");`

**Comment by asklar** [comment]
I'd imagine the API will remain the same; it will be up to the owners of the UI that the API triggers (which is not the xaml team) to decide whether to move the UI to WinUI 3 or not.

**Comment by sigmarsson** [comment]
@asklar frankly, no idea. It is however an old element introduced in `Windows 10.0.10240.0`.
