### ISSUE TITLE
Focus jumps to the top when a text box is the first element

### ISSUE THREAD

**Issue by ameyasv** [microsoft/microsoft-ui-xaml#4380]
Load the attached sample UWP project (POC_uwp_bug.zip)
1. Scroll down to any actionable item, so that the top textbox is out of the viewport
2. Click on this actionable element, button or toggle button. 
3. Afterwards click next to the button, or above, or below, but not another actionable element
4. The focus will jump up to text box at the top

Expected:  The focus does not change

See the attached gif for an animation of the behavior.
[POC_uwp_bug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6062079/POC_uwp_bug.zip)
![uwp_bug](https://user-images.githubusercontent.com/39258694/109506876-2651b600-7ac4-11eb-974b-7bf1b2d1172a.gif)

**Comment by chrisglein** [comment]
If you replace that TextBox to a Button and turn on “Track Focused Element” you can see that if you click in the scroll gutter focus goes to the first Button. It doesn’t scroll the Button into view, but it does change focus to the first focusable element. So I don’t believe this is a TextBox-specific issue.

@RBrid  is this behavior of the ScrollViewer moving focus on clicking in the gutters expected?

**Comment by chrisglein** [comment]
Dupe/related to #597?

**Comment by StephenLPeters** [comment]
looks like a dupe to me
