### ISSUE TITLE
XAML editor not detecting the "Content" metadata tag for properties. I.E: MenuBar.Items

### ISSUE THREAD

**Issue by AndreMarschalek** [microsoft/microsoft-ui-xaml#4385]
**Describe the bug**
[The type 'MenuBar' does not support direct content.] after adding MenuBar and MenuBarItem

**Steps to reproduce the bug**
Create a new project "C#, Windows, WinUI" "Blank App, Packaged (WinUI in Desktop)"
Add a MenuBar and MenuBarItem

**Expected behavior**
no "error" message

**Screenshots**
![image](https://user-images.githubusercontent.com/39925052/109528450-f7801380-7ab4-11eb-8fa7-c273fd2c95f1.png)

**Version Info**

NuGet package version: 
Microsoft.WinUI (3.0.0-preview4.210210.4)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
screenshot and xaml file attached

**Comment by StephenLPeters** [comment]
@RealTommyKlein and @fabiant3 FYI

**Comment by StephenLPeters** [comment]
@AndreMarschalek you can fix this locally by doing 
```
<MenuBar>
   <MenuBar.Items>
      ...
   </MenuBar.Items>
</MenuBar>
```

**Comment by AndreMarschalek** [comment]
with the result of
![image](https://user-images.githubusercontent.com/39925052/109796372-5dd17700-7c18-11eb-8279-58f7625fba68.png)

**Comment by anovik** [comment]
It seems it is still not solved. With WinUI3 1.0 release the project can be built but it still gives the intellisense error. Could you please have a look at this?

**Comment by AlexanderBlackman** [comment]
I've just tested an AppBarButton in a CommandBar flyout.
It also gives an intellisense warning but still compiles.
`Error`	XLS0502	The type 'CommandBarFlyout' does not support direct content.
