### ISSUE TITLE
Question: How to make AppBarButton HorizontalAlignment.Stretch in CommandBarFlyout in C#

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#4386]
Now I want to add AppBarButton to CommandBarFlyout.SecondaryCommand. But I could not make it fill the container. Like this:
![image](https://user-images.githubusercontent.com/42038175/109532686-53b65800-7af4-11eb-88e3-8d11d81d0584.png)

I tried Set HorizontalAlignment = HorizontalAlignment.Stretch but takes no effect.

If AppBarButton was added in XAML, it work well. If I add AppBarButton in C#, that would not be displayed properly.

**Comment by StephenLPeters** [comment]
This should just work without you needing to do any adjustments to app bar button.. Can you provide the code your using to add the app bar button? Maybe include a repro project as well.
