### ISSUE TITLE
FrameworkElement.RequestedTheme Does not change Themed Backgrounds on Panel derived FrameworkElements

### ISSUE THREAD

**Issue by groovykool** [microsoft/microsoft-ui-xaml#4389]
**Describe the bug**
FrameworkElement.RequestedTheme Does not change Themed Backgrounds on Panel derived FrameworkElements when the RequestedTheme of the Grid, Canvas or StackPanel is changed.

**Steps to reproduce the bug**
Repo:https://github.com/groovykool/JWEasyTheme.git

Create a XAML Grid with the Background set to a ThemeResource.
Set the Grid.RequestedTheme to Light and Dark and observe that the Background Color/Brush does not change.

Changing the RequestedTheme of the Frame or the Page works as expected. The Background of the Grid follows the RequestedTheme.

**Expected behavior**
The Grid Background should change when the Grid.RequestedTheme is changed.

**Version Info**
Winui 2.5
NuGet package version: 
2.5
Windows 1909

**Comment by sigmarsson** [comment]
I witnessed something similar in version 3 Preview 4. There is also a Grid layout on a Page. #4270

**Comment by StephenLPeters** [comment]
I think this is by (bad?) design.  Reading the documentation here: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.requestedtheme?view=winrt-19041 RequestedTheme changes the resource lookup for the default template. Grid doesn't have a template, so I think it is expected that it would not change any of the properties on grid, but it would affect children of that grid.

**Comment by StephenLPeters** [comment]
Closing the issue but feel free to comment back here if you want to discuss more. :)

**Comment by groovykool** [comment]
But the Grid theme works correctly when the RequestedTheme is set on the Frame or Page.  If its due to Grid not having a default template, why does it work on the Grid when it is the child of Page and the RequestedTheme is set on the Page?

**Comment by sigmarsson** [comment]
#4270 I even failed to achieve the situation you described as `Grid` placed onto a `Page`.

**Comment by StephenLPeters** [comment]
Basically RequestedTheme only applies to the elements children, not itself.  So when RequestedTheme is set on a page this works because all of the things that get rendered are children of the page.  Normally a templated control has template parts, which reference theme resources and those theme resource lookups get affected by the template root's RequestedTheme property.  But for grid, the background property is not on a child and so the RequestedTheme isn't seen during the lookup.
