### ISSUE TITLE
Swipe control SwipeItem Command Binding is Ignored

### ISSUE THREAD

**Issue by drchilds** [microsoft/microsoft-ui-xaml#439]
**Describe the bug**
A SwipeItem with a Command bound to a valid ICommand in a view model ignores the binding. 

**Steps to reproduce the bug**
1. Using a sample project with a ListView of SwipeControls, bind a ViewModel Command to a SwipeItem.
2. Launch the project and attempt to invoke the command from the SwipeItem.
3. Observe that nothing happens.
4. Set the Invoked event and set a breakpoint in the Invoked event.
5. Launch and Invoke the SwipeItem's event.  
6. Inspect the sender of the event and note that the Command property is null.

**Expected behavior**
Expect that the bound ICommand is invoked.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.0.181018004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)   | Yes   |

**Comment by drchilds** [comment]
See also:  https://stackoverflow.com/questions/53560468/swipeitem-xaml-binding-ignored

**Comment by drchilds** [comment]
Accidentally hit close. Apologies.

**Comment by jevansaks** [comment]
Interesting bug, thanks for the extra details from the SO link. We'll have to debug and see if it's a Swipe problem or Binding.

Could you try using x:Bind instead of Binding to see if that changes anything?

Also what happens if you use Binding to set the SwipeItem's Text property?

**Comment by drchilds** [comment]
Binding on the text property works as expected.

Changing to x:Bind and moving the SwipeItems out of a page resource and into the body of the SwipeControl itself seems to have done the trick, making me think that perhaps I had a problem with my binding syntax. I'll research this a little more when I have a chance.

**Comment by jevansaks** [comment]
@drchilds please let me know what you find. Thanks!

**Comment by jevansaks** [comment]
@drchilds, please reopen once you've had time to investigate and determine this is a platform issue you'd like us to look at.

**Comment by hansmbakker** [comment]
@jevansaks I cannot reopen this issue as I'm not the original poster.

I found [this stackoverflow answer](https://stackoverflow.com/a/57801129/1114918) which explains why it does not work, and the person who answered it seems to hold a good reputation around the UWP topic.

I don't know whether this is a fundamental issue or whether it is possible to fix by Microsoft, but as a developer the point that you can bind something that doesn't support binding feels like a bug. It is very counterintuitive, and googling around shows that multiple people (besides myself) were confused by this. It does not show a binding error. It has both a `Command` and `Invoke` property; the `Invoke` property is usually used with codebehind, the `Command` property is often used with binding to MVVM.

Could you please reopen it?

**Comment by hansmbakker** [comment]
Thank you!

All documentation currently mentions only the `Invoked` option, like [here](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/swipe#handle-an-invoked-swipe-command) but the point is that it is confusing that the available `Command` property does not work as expected. 

[This answer](https://stackoverflow.com/a/56228314/1114918) **seems** like a possible workaround; however I could not get that to work either. The `Invoked` property works.
