### ISSUE TITLE
Bug: Expander Should Not Have a MaxWidth

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#4391]
**Describe the bug**

Expander has a MaxWidth set in the template:
https://github.com/microsoft/microsoft-ui-xaml/blob/4208a01f744690329f6cd326e722d9c78e2358e8/dev/Expander/Expander.xaml#L26

This prevents `HorizontalAlignment = "Stretch"` from working (which is also set by default in the style). Instead, just like other controls, MaxWidth should be unset (double.NaN) and `HorizontalAlignment = "Left"`. I can't think of any other content control that constrains width like this.

**Steps to reproduce the bug**

 1. Add a new Expander control to a page
 2. The expander will not stretch past the MaxWidth

**Expected behavior**

Expander should stretch as most all other controls do.

**Screenshots**

**Version Info**

NuGet package version: 2.6.0 preview

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by michael-hawker** [comment]
🦙 Related to #4248.
