### ISSUE TITLE
(Desktop) WebView2Page throws exception during initialization

### ISSUE THREAD

**Issue by jskop** [microsoft/microsoft-ui-xaml#4393]
Opening WebView2 throws exception:
**Exception thrown at 0x7743A8B2 in XamlControlsGallery.Desktop.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0317AB70.**

![image](https://user-images.githubusercontent.com/31615175/109467166-135ec780-7a6b-11eb-8c30-183c0a477992.png)

**Comment by StephenLPeters** [comment]
@adambarlow and @codendone

**Comment by phizch** [comment]
Also mentioned here: https://github.com/microsoft/microsoft-ui-xaml/issues/4206, and on the WebView2 issues list (There's a link above, I think)

**Comment by codendone** [comment]
If you can F5 past this exception, then this is a dup of #4206, which was just fixed internally. Please reactivate if you're seeing a non-ignorable exception.
