### ISSUE TITLE
Combobox Itemtemplate WinUI 3 Preview 4

### ISSUE THREAD

**Issue by Dalli2602** [microsoft/microsoft-ui-xaml#4395]
I always get an error while adding an Itemtemplate to a combobox in winui preview 4.

   <ComboBox ItemsSource="{x:Bind vm.personList}" DisplayMemberPath="FirstName" Margin="8" SelectedItem="{x:Bind vm.SelectedPerson, Mode=TwoWay}">
            <ComboBox.ItemTemplate>
                <DataTemplate >
                    <StackPanel>
                        <TextBlock Text="{Binding Path=LastName, Mode=OneWay}"></TextBlock>
                    </StackPanel>
                </DataTemplate>
            </ComboBox.ItemTemplate>
        </ComboBox>

This xaml in the mainwindow (.net5 for desktop) end with a error:

Exception thrown at 0x75BDA8B2 (KernelBase.dll) in WinUI3Test.exe: WinRT originate error - 0x8000FFFF : 'Catastrophic failure'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!76832FD0: (caller: 767957D6) ReturnHr(3) tid(9ac) 8007007E The specified module could not be found.

Thanks for your help

**Comment by StephenLPeters** [comment]
@Dalli2602 thanks for the issue report, can you please include a repro app? It will help us track down the issue a lot.

**Comment by Dalli2602** [comment]
Hello @StephenLPeters  thank you for your help. You could donload an project from here:

https://1drv.ms/u/s!AgKnNZZb6YimoNBTqgEpHMJiUzNLiQ?e=waaj79

**Comment by Dalli2602** [comment]
Hi @StephenLPeters anything new to this problem?

**Comment by weitzhandler** [comment]
This issue occurred to me as well, after going in rounds pulling my hair out, I found out that the reason was I set both the `ItemTemplate` and the `DisplayMemberPath` property.
Definitily did not expect a misterious 'Catastrophic failure' message.
