### ISSUE TITLE
Question: Use C++/WinRT Windows Runtime Component in the WPF application

### ISSUE THREAD

**Issue by pavelpokutnev** [microsoft/microsoft-ui-xaml#4401]
Dear WinUI-Team,
I'm starting to evaluate the WinUI 3 Preview 4 and I would like to test following scenario:

1. Create a Windows Runtime Component (WinUI) with C++/WinRT.
2. Use this Component inside of a WPF C# application.

I didn't found any example for this scenario yet, that why my questions below:

1. Is this scenario already supported?
2. Are there any limitations, e.g.: .NET Framework version on the WPF side.
3. Do I require any additional layers or dependencies?
4. Are there any examples for this scenario already available?
5. In case it doesn't work with WPF, does it work with WinForms?

Cheers!

**Comment by StephenLPeters** [comment]
Winui3 Preview 4 does not support Xaml Islands, ie hosting a winui component in a wpf app. However Winui2 does, so today you could do what you are proposing using winui2 and xaml islands. Here is some documentation: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands.  We do plan on supporting xaml islands with winui3 some day, but it isn't ready yet.
