### ISSUE TITLE
Add .net5 Support to XAML islands

### ISSUE THREAD

**Issue by Samuel12321** [microsoft/microsoft-ui-xaml#4408]
## Rationale
We currently have a app that was moved over to .net5 from .NET Framework 4.7. The decision has been made to use XAML Islands to modernize the UI. As WINUI 3 does not currently nor will in the near future support, rounded corners for top level windows which is essential for this app. In order to use XAML Islands we will have to migrate back to .NET Core 3.1.

If you want to encourage adoption of .NET 5, make sure it is actually supported by your own tools such as Xaml Islands.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish XAML islands with .net 5| Must |

**Comment by Austin-Lamb** [comment]
We do not have any plans to support .NET 5 for any scenarios with the copy of XAML in the OS, that's just for WinUI 3.  So for now you'll nee to wait to adopt XAML Islands until WinUI 3 supports islands, which you can see mentioned on the roadmap here (unfortunately not committed for a particular release yet): https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md

**Comment by nesherhh** [comment]
I have partialy ported XAML Islands to .NET 5. Take a look here: https://github.com/nesherhh/XamlIslandsNET5
