### ISSUE TITLE
Question: Remove test certificate generation for WinUI projects in Windows Template Studio

### ISSUE THREAD

**Issue by sibille** [microsoft/microsoft-ui-xaml#4410]
Looking into the WinUI 3 project templates, we've seen that WinUI3 Preview 4 project templates create test certificates for C# Uwp and C++ Uwp and Desktop projects, but not for C# Desktop Apps. 

Visual Studio allows to create Test certificates using this dialog: 
![image](https://user-images.githubusercontent.com/24698018/109816018-8feed300-7c30-11eb-8da2-ce2a17488024.png)

In Windows Template Studio we are thinking about removing test certificate generation for WinUI3 templates (C# Desktop and C++ Uwp and Desktop), do you see any issues here?

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by alwu-msft** [comment]
Yeah, I think that's fine.

**Comment by sibille** [comment]
Working on #4146 we've seen that there is a test certificate created for Windows Runtime Components (C# and C++) too. Do we need the test certificate in this case?
