### ISSUE TITLE
Question: What's the minimum Visual Studio Version to create WinUI3 Apps

### ISSUE THREAD

**Issue by sibille** [microsoft/microsoft-ui-xaml#4411]
Docs recommend installing the latest Preview for VS 16.9 (https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-30-preview-4).
 
What's the minimum version thats required for creation of WinUI3 Apps?

**Comment by sigmarsson** [comment]
Well, any VS Preview - I guess, mine was 4 when I fetched it.

**Comment by huoyaoyuan** [comment]
There shouldn't be SDK breaking changes after VS16.8 and WinUI3P3.

**Comment by StephenLPeters** [comment]
VS16.8 is required for Winui3 :)
