### ISSUE TITLE
Unable to launch WinUI 3 app after installing from .appxbundle

### ISSUE THREAD

**Issue by AJLeuer** [microsoft/microsoft-ui-xaml#4418]
**Describe the bug**

I created a WinUI 3 for desktop app more or less following the template given [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop). Today I reached the point where I'd like to start distributing it for to get some user feedback, and with that in mind, I created an .appxbundle and installed my app via said .appxbundle. However, after installing, clicking my application in the start menu to run it had zero effect. My app simply doesn't launch.

_**Note**_: _If rather than deploying my application from the .appxbundle, I instead build it from Visual Studio, _then_ I am able to run the identical Start menu entry created by Visual Studio with no issue. The problem only occurs when trying to run the start menu entry created by installing from the .appxbundle._

**Steps to reproduce the bug**

1. Check out the code from [this repo](https://github.com/AJLeuer/GHelper.git), master branch.
2. Load the solution in Visual Studio.
a. Visual Studio should be at least version 2019 16.9 Preview
b. You'll also need to have followed all the steps listed [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#install-winui-3-preview-4) under **Install WinUI 3 Preview 4** to run everything properly.
3. Right-click on the "GHelper (Package)" project.
4. Click `Publish` → `Create App Packages...`.
5. In the "Select distribution method" dialogue choose "Sideloading".
6. (I'm not sure what you'll see on the next page, but I assume it'll prompt you for a certificate. Mine might be included but you may prefer to use your own.)
7. Once you've selected a signing method, on the next dialogue "Select and configure packages":
a. choose your preferred location for the output (I chose my Downloads folder).
b. "Version" *should* be ok to leave as it is (but if it's blank just put in something like "1.0.1.0").
c. Set "Generate app bundle" to "Always" if it's not already.
d. Under "Select the packages to create and the solution configuration mappings:", under "Architecture" check "x64", and under "Solution Configuration" select "DebugRelease (x64)" (you could also try "Release", it doesn't seem to matter as both lead to the same outcome).
e. Check "Include public symbol files...".
8. Click "Create".
9. Once the .appxbundle is created in your chosen destination folder, open the directory, find the file starting in "GHelper" and ending in ".appxbundle", and run it. Install the GHelper application.
10. (If you have trouble installing because the certificate is untrusted, you should be able to find the certificate you used in the same directory as the .appxbundle. Try right-clicking it, clicking "Install", choosing the "Store Location" of "Local Machine" and explicitly placing the cert in the "Trusted Publishers" store. That fixed the issue for me anyway.)
11. Locate "GHelper (Package)" in your Start menu and run it.

**Expected behavior**
I expect to see my main application window, the same that I'm able to see when I run my app from within Visual Studio.

**Screenshots**

**Version Info**

NuGet package version:
Microsoft.WinUI 3.0.0-preview4.210210.4

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   | 
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@codendone or @Austin-Lamb FYI

**Comment by StephenLPeters** [comment]
Could be tooling as well, @fabiant3

**Comment by huoyaoyuan** [comment]
It looks like https://github.com/microsoft/microsoft-ui-xaml/issues/3749 , which is already fixed in preview 4.

**Comment by AJLeuer** [comment]
Well, for whatever reason, it seems to be working now. I don't think I changed anything but I tried to publish it again today, following the same steps as before, and now it works. I'll just go ahead and close this.
