### ISSUE TITLE
Why are there two different .dlls produced for a class library?

### ISSUE THREAD

**Issue by billhenn** [microsoft/microsoft-ui-xaml#4421]
When using Visual Studio to compile a WinUI for Desktop class library, I'm seeing that my `bin/Debug/net5.0-windows10.0.18362.0` folder contains a number of files like `MyLibName.dll`.  There also is a `ref` sub-folder with another smaller instance of `MyLibName.dll`.  

I'm curious why there are two .dlls being created here and why the second one is being kept around if it's more of an intermediate assembly?  Thanks in advance for your help.

**Comment by StephenLPeters** [comment]
@alwu-msft fyi

**Comment by MagicAndre1981** [comment]
ref is the [reference assembly](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies) which has no implementation:

>Reference assemblies are a special type of assembly that contain only the minimum amount of metadata required to represent the library's public API surface.
>
>Using a reference assembly enables developers to build programs that target a specific library version without having the full implementation assembly for that version.

**Comment by billhenn** [comment]
Thank you for the information @MagicAndre1981.
