### ISSUE TITLE
Text not shown in TextBox control when changing at run-time when using DateTimeFormatter

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4423]
**Describe the bug**
Text not shown in TextBox control when changing at run-time when using DateTimeFormatter.

We have used DateTimeFormatter for showing the Current date in TextBox control based on CalendarIdentifier. Also, I have tried to call invalidate measure and update layout method. Still, the text is not shown in TextBox. 

Also, I did not face this issue when using TextBlock instead of TextBox.

**Steps to reproduce the bug**
1. Run the sample.
2. Change Hebrew CalendarIdentifier using ComboBox.
3. Now Change to any other CalendarIdentifier using ComboBox.
3. Note TextBox text is not shown.

**Expected behavior**
TextBox text should be shown.

**Version Info**
[Microsoft.WinUI 3.0.0-preview4.210210.4]

**Sample:**
[WinUITest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6089669/WinUITest.zip)

**Comment by StephenLPeters** [comment]
Running locally, I see the text appear once I give the textbox focus.

**Comment by StephenLPeters** [comment]
@chrisglein FYI

**Comment by chrisglein** [comment]
Looking at the code this seems reasonable, and does work when binding to a `TextBlock`. Not sure what is failing with `TextBox` here, as this should be pretty standard. Stephen's comment about it showing when given focus is the most mysterious, as it implies the value has been set but isn't visually applied. This needs some debugging.
