### ISSUE TITLE
Setting Date property of CalendarDatePicker throws ThrowExceptionForHR

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#4425]
**Describe the bug**

When setting the Date property of the CalendarDatePicker (either by using x:Bind or directly from code behind) will throw an exception:

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.IObjectReference.As[T](Guid iid)
   at WinRT.IObjectReference.As[T]()
   at WinRT.MarshalInterface`1.CreateMarshaler(T value)
   at ABI.Microsoft.UI.Xaml.Controls.ICalendarDatePicker.global::Microsoft.UI.Xaml.Controls.ICalendarDatePicker.set_Date(Nullable`1 value)
   at Microsoft.UI.Xaml.Controls.CalendarDatePicker.set_Date(Nullable`1 value)

**Steps to reproduce the bug**
1. Set the Date property of a CalendarDatePicker control.
**Expected behavior**
Don't throw an exception, but instead set the provided date (with type DateTimeOffset?) in the control.

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |

**Comment by StephenLPeters** [comment]
@Scottj1s is this a CSWinrt issue?

**Comment by nzstevem** [comment]
I'm also having difficulty getting a DateTimeOffset? to bind:x to the CalendarDatePicker control's Date. 

"Unhandled exception at 0x785E7C00 (Microsoft.ui.xaml.dll) in Test1.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x16666470, 0x00000002)."

The problem continues in ReUnion 0.5.  

I have a small test program to demo this which I can post if this is of use. The datepicker control works fine but the binding there is to a non-nullable datetimeoffset.  Perhaps there is an issue with the nullable value.

If anyone can point me to a piece of code that successfully two way binds x:binds a calendardatepicker date to a DateTimeOffset?, which should not need any convertor, I'd appreciate it.

**Comment by wbokkers** [comment]
I get the same exception when I try to serialize a DateTimeOffset to the local settings collection. This used to work in UWP and earlier versions of WinUI.

**Comment by wbokkers** [comment]
> If anyone can point me to a piece of code that successfully two way x:binds a calendardatepicker date to a DateTimeOffset?, which should not need any convertor, I'd appreciate it.

I tried using x:Bind with methods (Bind, BindBack) and with a converter to nullable and not-nullable values. Nothing works.

**Comment by codendone** [comment]
This works for me in Project Reunion 0.5.5, which was released last Friday. I tried both x:Bind and setting in code. There was a big CsWinRT update that in release, which I suspect fixed this.
