### ISSUE TITLE
Command bar overflow menu is too low that will block some items in latest preview version (2.6.0)

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#4436]
**Describe the bug**

Latest 2.6.0-preview, the command bar overflow menu is too low that will block some items

**Steps to reproduce the bug**

1. Click ... in commandbar

**Expected behavior**
Should have more space and do not block the items

**Screenshots**
![image](https://user-images.githubusercontent.com/42038175/110232963-128ecf80-7f5c-11eb-9938-0536063049f7.png)

**Version Info**

NuGet package version: 2.6.0-prerelease.210227001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Command bar work properly in 2.5.0

**Comment by StephenLPeters** [comment]
@teaP has this already been fixed?

**Comment by StephenLPeters** [comment]
@zhuxb711 We fixed a very similar bug to this and in our test apps we don't reproduce this. However it looks like you are using the same nuget package we are.  Can you provide us a repro app so we can get this resolved?
