### ISSUE TITLE
Proposal: Allow WrapGrid to be used without ItemsControl

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/microsoft-ui-xaml#444]
## Summary
I don't understand why `WrapGrid` can't be used without `ItemsControl`. 
I just had to create my own WrapPanel because of that.
If there is no inconvenience, then please allow us to use this `Control` .

**Comment by jevansaks** [comment]
@micahl is this a job for flex?

**Comment by ranjeshj** [comment]
We have LayoutPanel in preview which can be used with UniformGridLayout to achieve this i think.
