### ISSUE TITLE
Inconsistency of CalendarIdentifier support in DatePicker and CalendarDatePicker WINUI controls

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4440]
**Describe the bug**
Inconsistency of CalendarIdentifier support in DatePicker and CalendarDatePicker WINUI controls.

In DatePicker control, CalendarIdentifier support was given for both DatePicker and DatePickerFlyout contained in popup.

![image](https://user-images.githubusercontent.com/55440472/110288278-c2704580-800d-11eb-857f-31fc3398a71b.png)

![image](https://user-images.githubusercontent.com/55440472/110288317-cf8d3480-800d-11eb-9165-d739cb9818a4.png)

In CalendarDatePicker control, CalendarIdentifier support was given only for  Calendar contained in popup.

![image](https://user-images.githubusercontent.com/55440472/110288456-095e3b00-800e-11eb-8e43-19dc0c504b95.png)

![image](https://user-images.githubusercontent.com/55440472/110288477-12e7a300-800e-11eb-8f8e-9945565bf0d4.png)

**Steps to reproduce the bug**
1. Run the sample.
2. Modify CalendarIdentifier as UmAlQuraCalendar for both DatePicker and CalendarDatePicker control.
3. Note, TextBlock value in CalendarDatePicker and its FlowDirection not modified based on the CalendarIdentifier as like DatePicker control.

**Expected behavior**
TextBlock value in CalendarDatePicker and its FlowDirection should be modified based on the CalendarIdentifier as like DatePicker control.

**Screenshots**
![image](https://user-images.githubusercontent.com/55440472/110287847-2c3c1f80-800d-11eb-8954-e779bef1f90d.png)

**Version Info**
[Microsoft.WinUI 3.0.0-preview4.210210.4]

**Sample:**
[WinUITest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6099632/WinUITest.zip)

**Comment by StephenLPeters** [comment]
The CalendarDatePicker template has a text box whose text is template bound to the Controls Placeholder text property https://github.com/microsoft/microsoft-ui-xaml/blob/e591e44bea111c0c7f6c682e936b2cc533e0c0d3/dev/CalendarDatePicker/CalendarDatePicker_themeresources.xaml#L255  This text is likely not getting the treatment from the identifier property.
