### ISSUE TITLE
WinUI Xamarin Forms support?

### ISSUE THREAD

**Issue by DmitryBorodiy** [microsoft/microsoft-ui-xaml#4442]
Hello, WinUI and UWP community!

I have one question...

When WinUI projects will be support on Xamarin Forms?

I think this is cool idea, but unfortunately Microsoft.UI libraries don't supported on Xamarin Forms...
When this issue will be resolved?

Thanks!
Best wishes for WinUI Community!

😀😀😀

**Comment by Dmitiry-hub** [comment]
I want using WebView2 in my Xamarin Forms app...

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI

**Comment by StephenLPeters** [comment]
@Dmitiry-hub I think this repository would be a better spot for xamarin forms questions.
