### ISSUE TITLE
Unsynchronized scrolling of two scroll viewer in WinUI

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [microsoft/microsoft-ui-xaml#4447]
**Describe the bug**
Facing unsynchronized scrolling of two scroll viewer in WinUI, in my scenario i am using two scroll viewer and updating the vertical offset of one scroll viewer based on another scroll viewer by using **ChangeView** method. But facing scrolling delay in scroll viewer, both scroll viewer is not scrolling even and in synchronized manner.

**Steps to reproduce the bug**
- Run the sample.
- Scroll any one scroll viewer using mouse scroll wheel.

**Expected behavior**
Both scroll viewer should be scrolled evenly in synchronized manner.

**Screenshots**
[DemoVideo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6103000/DemoVideo.zip)

**Version Info**

WinUI NuGet package version = 3.0.0-preview4.210210.4

OS version = Windows 10 Pro

![image](https://user-images.githubusercontent.com/39787321/110355405-3129bf00-805f-11eb-9b8e-0ced15db82d0.png)

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Demo smple:** 
[WinUIScrollDemo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6103026/WinUIScrollDemo.zip)

**Note:** This scenario works perfectly in WPF and Native UWP

**Comment by BorzillaR** [comment]
Hello, @Ganeshamoorthy10

Seems, you are solving the same issue as I am. There are independent animations during the scrolling, which you cannot control. It could be solved by the composition layer as @Sergio0694 described in [this](https://github.com/microsoft/microsoft-ui-xaml/issues/3342#issuecomment-700610842) post.

**Comment by StephenLPeters** [comment]
@RBrid can you weigh in?
