### ISSUE TITLE
WinUI Xamarin Forms support

### ISSUE THREAD

**Issue by Dmitiry-hub** [microsoft/microsoft-ui-xaml#4448]
Hello, WinUI and UWP community!

I have one question...

When WinUI projects will be support on Xamarin Forms?

I think this is cool idea, but unfortunately Microsoft.UI libraries don't supported on Xamarin Forms...
When this issue will be resolved?

Thanks!
Best wishes for WinUI Community!

😀😀😀

**Comment by StephenLPeters** [comment]
closing as a duplicated of #4442
