### ISSUE TITLE
Creating a UWP app that has a project reference to a WinUI Custom Control Class library fails

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#4454]
**Describe the bug**
When using project references to a custom control library in UWP, you get the following build error:
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3030: Could not copy the file "E:\source\MyControls\MyControls\bin\Debug\uap10.0.17134\MyControls\Themes\Generic.xbf" because it was not found.

**Steps to reproduce the bug**
1. Unzip the following repro: [MyControls.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6105844/MyControls.zip)
2. Open the solutoin and set the `MyControlsTest` project as startup and architecture to x86/x64/arm (ie not anycpu)
3. Try and F5 run the project.

Note the error:

> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3030: Could not copy the file "E:\sources.tmp\MyControls\MyControls\bin\Debug\uap10.0.17134\MyControls\Themes\Generic.xbf" because it was not found.

A workaround can be applied as a post-build step to copy the file to this location from `\MyControls\MyControls\bin\Debug\uap10.0.17134\Themes\Generic.xbf`

**Expected behavior**
No build error - application runs fine

**Version Info**
NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4] 
-->

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@fabiant3 @alwu-msft as FYI

**Comment by nlogozzo** [comment]
Experiencing this on WinUi desktop. Any idea on what is causing it or a possible work around?

**Comment by bpulliam** [comment]
UWP is no longer supported in WinUI3. If you still see the issue without UWP, please reactivate or open a new issue.
