### ISSUE TITLE
When building a Net5 control library, the default template is not being applied

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#4455]
**Describe the bug**
I have a class library with a custom control that has a generic.xaml template. The template defined in the class library doesn't get applied, but you have to re-apply it in the application as well.

**Steps to reproduce the bug**
1. Unzip the repro: [MyControls.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6105933/MyControls.zip)
2. Set the package project as startup.
3. Run the application.
4. Observe that `OnApplyTemplate` in `\MyControls\MyTemplatedControl.cs` isn't hit.
5. Manually define a control template in app.xaml and observe that it is now hit, demonstrating that the template defined in Generic.xaml isn't working.

Note: This might be an artifact or related to #4453 

**Expected behavior**
Control template defined in the class library works (this works if the target is UWP).

**Version Info**
NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4] 
Visual Studio 16.9.0 (I'm fairly certain it worked in the last preview of Update 9)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by azchohfi** [comment]
I believe this might be a regression on 16.9 stable? I started seeing the same issue on my machine today. I will investigate further tomorrow.

**Comment by dotMorten** [comment]
@azchohfi Thanks! That would explain why I couldn't understand why it suddenly was an issue - I had just updated to 16.9.0 stable a few days ago as well.

**Comment by billhenn** [comment]
Wow this is a frustrating one.  I just ran into it myself.  Sure hope this is fixed ASAP.

**Comment by ranjeshj** [comment]
@fabiant3 @alwu-msft as FYI

**Comment by huoyaoyuan** [comment]
This is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4414

**Comment by huoyaoyuan** [comment]
There is already a CsWinRT fix pending. You don't need to investigate again now.

**Comment by dotMorten** [comment]
Closing as duplicate

**Comment by dotMorten** [comment]
...just confirming that your workaround referencing .13 works for the above reproducer

**Comment by huoyaoyuan** [comment]
It works for me. I'm referencing the .13 in the entry exe, not the control library.

**Comment by dotMorten** [comment]
@huoyaoyuan Right. Same.
