### ISSUE TITLE
WinUI v.2.5.0 NavigationView Left orientation is not showing settings button properly

### ISSUE THREAD

**Issue by anup-das** [microsoft/microsoft-ui-xaml#4456]
**Describe the bug**

When using Microsoft.UI.Xaml.NavigationView in left orientation the settings button is showing unwanted vertical scroll bar

**Steps to reproduce the bug**
Compile and run the attached solution in Visual Studio 2019 on the exact configuration to hopefully repro. See also attached screen capture

**Expected behavior**

Settings button should be displayed without the unwanted vertical bar

**Screenshots**

![image](https://user-images.githubusercontent.com/63170829/110425189-f4df7880-80c9-11eb-8a94-53c8e0292b64.png)

**Version Info**

NuGet package version: 

Microsoft.WinUI 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

See attached source code solution VS 2019 v16.9
[BlankApp1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6106160/BlankApp1.zip)

**Comment by chingucoding** [comment]
Thanks for filing this issue @anup-das, however this has already been reported as #3771.
