### ISSUE TITLE
VirtualizingLayoutContext.GetElementAtCore incorrectly named

### ISSUE THREAD

**Issue by micahl** [Microsoft/microsoft-ui-xaml#446]
**Describe the bug**

Looks like we missed something during the big rename after API review.  This protected method should match the public one (GetOrCreateElementAt) instead of being just GetElementAt.  

The IDL currently has this:
overridable Windows.UI.Xaml.UIElement GetElementAtCore(Int32 index, ElementRealizationOptions options);

It should be this:
    overridable Windows.UI.Xaml.UIElement Get **_OrCreate_** ElementAtCore(Int32 index, ElementRealizationOptions options);

**Comment by jevansaks** [comment]
@ranjeshj seems like something we should do for 2.1. Can you take a look?
