### ISSUE TITLE
Question: What are current plans relating to the open-sourcing of WinUI tooling?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#4462]
I have previously asked on community calls about WinUI project tooling (including templates) and if (and when) it will be open-sourced.

The answer I was given at the time was that they never would be.

However, [the WinUI3 project and item templates were recently added to the ProjectReunion repo](https://github.com/microsoft/ProjectReunion/pull/496). 

**Given this change, are any other tooling items related to WinUI3 going to be open-sourced as well?**

If so, will they be included in this repo or the Project Reunion one?

Why were the templates added to the ProjectReunion repo?
Will other parts (or all) of WinUI3 move to that repo too?

Is it best to ask questions about these WinUI specific templates on this repo or on the ProjectReunion one?

**Comment by alwu-msft** [comment]
We do have plans to open source the tooling but we don't have any details to share about that yet.

Moving forward, Project Reunion is the vehicle by which WinUI 3 will be delievered; template issues should go in the Project Reunion repo but issues specific to WinUI will continue to live here. And if that changes in the future, we'll be sure to make a big announcement about it. :)

**Comment by mrlacey** [comment]
This has been brought up at (almost?) every community call, the plans and details for this are still of broad interest.
Hopefully this will be made clear and official soon.

**Comment by duncanmacmichael** [comment]
Closing this question as the WinUI 3 source was made available for searching and debugging in the 1.4.2 release. The latest as of writing this comment is for 1.4.3, available here:

https://github.com/microsoft/microsoft-ui-xaml/releases/tag/winui3%2Frelease%2F1.4.3

**Comment by mrlacey** [comment]
This question was originally about tooling around the product.
The source code made available did not AFAIK include anything  related to tooling.
Happy to leave this closed as an indication that the tooling never will be open

**Comment by duncanmacmichael** [comment]
Hey @mrlacey, thanks for your comment! I think I misunderstood your original post as asking about the source availability in general, yes. But, can you clarify a bit more as to what you mean by tooling? I'll be happy to check on that for you but want to make sure what you mean before I do. :)

**Comment by mrlacey** [comment]
I was interested in the tooling that integrates with Visual Studio: XAML intellisense, completions, extensibility, etc.
I understand from elsewhere that there is no intention of ever making this public though.
