### ISSUE TITLE
InfoBar does not apply Corner Radius

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#4463]
**Describe the bug**

InfoBar does not apply the CornerRadius property to the control

**Steps to reproduce the bug**
1. Add the following xaml to a page

```
<StackPanel Orientation="Horizontal" Margin="20">
                <InfoBar Message="Message 1" HorizontalAlignment="Left" IsOpen="True" IsIconVisible="False" Margin="10,0,3,0" CornerRadius="0"  />
                <InfoBar Message="Message 2" HorizontalAlignment="Left" IsOpen="True" IsIconVisible="False" Margin="10,0,3,0" CornerRadius="11" />
            </StackPanel>
```
            

**Expected behavior**

Radius on 2nd InfoBar
**Screenshots**

![image](https://user-images.githubusercontent.com/9586533/110539556-442da500-80da-11eb-9d42-f89f0430627a.png)

**Version Info**

NuGet package version: 

[Microsoft.WinUi] 3.0.0-preview4.210210.4
[Microsoft.Toolkit.Uwp.UI.Controls] 8.0.0-preview4

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | YES |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | YES   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@omnillogix are you seeing this in WinUI2 or WinUI3 ? Which version of WinUI2 or WinUI3 ? From looking at the code, I would expect this to work.

**Comment by omnillogix** [comment]
> @omnillogix are you seeing this in WinUI2 or WinUI3 ? Which version of WinUI2 or WinUI3 ? From looking at the code, I would expect this to work.

Win32 - From project file...

` <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
    <RootNamespace>App3</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
  </PropertyGroup>`

**Comment by omnillogix** [comment]
Same under Project Reunion 0.5 / Toolkit 8.0.0 preview5

![image](https://user-images.githubusercontent.com/9586533/111391359-b0c41900-8671-11eb-965d-ff6212966a72.png)

**Comment by Jay-o-Way** [comment]
Is this still an issue?

**Comment by omnilogix** [comment]
Any progress on this item?

**Comment by Jay-o-Way** [comment]
This issue is over 2 years old (!) I'm sure that - if one updates to latest framework/sdk and such - this issue is long gone.

**Comment by omnilogix** [comment]
Perhaps, but the WINUI team should mark it as such.  This is the purpose of this feedback loop on github.

**Comment by Jay-o-Way** [comment]
ping @gabbybilka (or anybody)

**Comment by ranjeshj** [comment]
Tried with 1.5 and it seems to be resolved. 

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/28935693/974a4724-5b86-4cb2-bac8-5fb5925c9377)
