### ISSUE TITLE
TextBox context menu uses old design

### ISSUE THREAD

**Issue by gabrielconl** [microsoft/microsoft-ui-xaml#4472]
![image](https://user-images.githubusercontent.com/78622729/110654092-803e3400-81c6-11eb-94d1-7cf054953ac4.png)

When you right click in a TextBox or a derived control you get this menu, which has a design from before v2.2.

**Comment by ranjeshj** [comment]
Should be fixed by this PR https://github.com/microsoft/microsoft-ui-xaml/pull/4586
