### ISSUE TITLE
ToggleMenuFlyoutItem and RadioMenuFlyoutItem do not show assigned icon in winui 2.6 prerelease

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#4473]
**Describe the bug**

When using the new styles for both controls, the assigned icon is ignored.

**Steps to reproduce the bug**

1. Create a new winui 2.6 app and change the styles version to "latest"
2. Add a ToggleMenuFlyoutItem or RadioMenuFlyoutItem
3. Assign an icon to the item 
4. Observe that the icon is not shown

**Expected behavior**

Icon should be shown

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml.2.6.0-prerelease.210227001]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@lhak can you paste a screenshot / markup ?

**Comment by StephenLPeters** [comment]
@tashatitova and @ranjeshj it looks like we removed the ViewBox which was containing the icons on accident.  Here is the line from the PR that removed it https://github.com/microsoft/microsoft-ui-xaml/pull/3958#discussion_r591982143

**Comment by tashatitova** [comment]
@StephenLPeters @ranjeshj yes, accidental removal while cleaning up Reveal. Wasn't caught in testing. Need to add highlighted lines back.

**Comment by chingucoding** [comment]
Taking a look at this.
