### ISSUE TITLE
NavigationViewItem Icon disappear in NavigationView PaneFooter (2.6 prerelease)

### ISSUE THREAD

**Issue by Psykobal** [microsoft/microsoft-ui-xaml#4482]
**Describe the bug**

The icon of NavigationViewItems in the PaneFooter disappear.

**Steps to reproduce the bug**

Add some NavigationViewItems with an icon  in a PaneFooter

**Expected behavior**

Icon appear like in MenuItems

**Screenshots**
![NoIcon_Close](https://user-images.githubusercontent.com/15339175/110745421-83bfd280-823b-11eb-85f0-6608ff469ed2.png)
![NoIcon_Open](https://user-images.githubusercontent.com/15339175/110745426-85899600-823b-11eb-9988-70e5fbdcc486.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.6.0-prerelease.210227001]
[Microsoft.UI.Xaml.2.6.0-prerelease.210217002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Was working until: 
[Microsoft.UI.Xaml.2.6.0-prerelease.210129001]

**Comment by StephenLPeters** [comment]
@karenbtlai FYI @Psykobal I assume that the "Menu Item1" item is supposed to have an icon?

**Comment by StephenLPeters** [comment]
Can you provide the xaml you used to get this UI? or better yet a repro project.

**Comment by Psykobal** [comment]
I made a repro project: [NavigationViewTest](https://github.com/Psykobal/NavigationViewTest)

It has 4 variations. Do you need more details?
