### ISSUE TITLE
Groups in ListView and GridView are read incorrectly by the narrator

### ISSUE THREAD

**Issue by EriWong** [microsoft/microsoft-ui-xaml#4486]
**Describe the bug**

The groups in listview and gridview use the type of the collection of the items as the accessible name (AutomationProperties.Name), which when read by the narrator is not human understandable.  This results in any grouped listview or gridview to fail accessibility checks.

**Steps to reproduce the bug**
This reproes in all gridviews and list views that use groups.  This set of steps uses uses the xaml controls gallery to reproduce the issue, but I can provide a standalone snippet if needed.
1. Launch the xaml controls Gallery 
2. Navigate to the list view page
3. Read an item from the "ListView with Grouped Headers" page using narrator, or use inspect to look at the group.

**result**
The narrator reads out the fully qualified type name of the group ("AppUIBasics.ControlPages.GroupInfoList" in the xaml controls gallery) before reading out the item accessible name.  Further, I could only control the item name by creating a subclass of the GridView and overriding the PrepareContainerForItemOverride method.

**Expected behavior**
There is a way to set the group accessible name, and there is a reasonable default group name.

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.2]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| YES |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        |   YES   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@EriWong you could try setting the automation properties for the container in ChoosingGroupHeaderContainer event.

**Comment by lyf6lyf** [comment]
@ranjeshj I am trying your solution. But I found for many groups the `args.GroupHeaderContainer` is null, then it doesn't work. Do you have any example or guidance about it?

**Comment by tinodo** [comment]
I added another bug for perhaps the same issue: [ListView.ChoosingGroupHeaderContainer returns null for ChoosingGroupHeaderContainerEventArgs.GroupHeaderContainer for all groups except the first the first time the ListView is drawn.](https://github.com/microsoft/microsoft-ui-xaml/issues/8569)
