### ISSUE TITLE
Scroll snap points hinder mouse-wheel scrolling

### ISSUE THREAD

**Issue by RBrid** [microsoft/microsoft-ui-xaml#449]
Scroll snap points, which are now all mandatory, make it hard to scroll with the mouse wheel. If the natural target offset is closer to the current position (a mandatory snap point) than the next snap point, the offset won't change.
A single mouse-wheel delta should allow you to leave the current position. As it is, the mouse-wheel is almost ineffective when scroll snap points are defined.

**Comment by jevansaks** [comment]
Is this a bug or does this feature need some spec work?

**Comment by RBrid** [comment]
@jevansaks, I consider this a bug. I don't expect any API or design change to address this.

**Comment by RBrid** [comment]
This was addressed by my PR #592.
