### ISSUE TITLE
XamlParseException on load a blank page from a custom library in WinUI 3 UWP App (Project Reunion SDK)

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#4497]
Hello!

We are migrating our app from WinUI 3 Preview 4 to the Project Reunion SDK (v. 0.5.0-prerelease). We found that pages wich defined in the class libraries are not loaded anymore.

![image](https://user-images.githubusercontent.com/23479280/110899399-0ca93d80-8312-11eb-8c1b-22a03c7c1472.png)

Looks like a code generator generates a wrong uri.

The issue is unique for Uwp applications. I tried to reproduce it in WinUI for the Desktop application but without success. I also noted that the page uri generated by the code generator is different for the desktop app.

![image](https://user-images.githubusercontent.com/23479280/110899983-12535300-8313-11eb-85b0-337f0178b009.png)

Compare the generated uri with the previous screenshot

WinUI for Uwp: ms-appx:///BlankPage1.xaml
WinUI for Desktop: ms-appx:///ClassLibrary1/BlankPage1.xaml

**Steps to reproduce the bug**

1. Create a blank WinUI 3 for UWP application with Project Reuninon SDK.
2. Add the new Class Library project in existing solution and add the reference to it in the application project.
2. Add the new blank page in the class library.
3. Open the App.xaml.cs file and change the start page for the main frame to the BlankPage1 from ClassLibrary1.
![image](https://user-images.githubusercontent.com/23479280/110900844-762a4b80-8314-11eb-93ef-6b5865d72ac9.png)
4. Run the app

Please note that this issue also occurs for the resource dictionaries with a code-behind part. 

**NuGet package version: **

WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

**Windows app type:**
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes  | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Version 20H2 (OS Build 19042.804)           |  Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by alwu-msft** [comment]
Thanks for the report @BorzillaR! This is definitely a regression that we'll want to fix.

**Comment by alwu-msft** [comment]
This should be fixed with the release of Project Reunion 0.5.

**Comment by alwu-msft** [comment]
This was incorrectly closed, and still reproes.

**Comment by pratikone** [comment]
@evelynwu-msft  does this bug still exist ? do we have any task.ms link for it ?

**Comment by evelynwu-msft** [comment]
@pratikone http://task.ms/32224803. It is almost certainly still an issue although I haven't checked recently.
