### ISSUE TITLE
ScrollViewer’s VerticalOffset value is not changed immediately on mouse wheel or mouse pad scrolling 

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [microsoft/microsoft-ui-xaml#4498]
**Describe the bug**
In my scenario I have arranged cells in rows and columns with vertical scrolling, also I have properly virtualized the cells on scroll change based on vertical offset of scroll viewer. When I scroll through scroll bar or through touch, cells updates and arranges property in new position without any issue.

But, when i scroll using mouse scroll wheel or through mouse pad, I am facing empty space at top and bottom. Please check the attached video.

I don't see any issue in my virtualization logic, because it works properly by scrolling through scroll bar or through touch.

I suspect the issue is due to vertical offset value is not updated immediately on scroll change. For example, when I scroll from 0 to 150, vertical offset value is not changed directly to 150, it changes step by step like 15, 50, 100, 150 which leads empty space at top/bottom on scrolling due to virtualization based on vertical offset.

**Note:** This scenario works perfectly in WPF.

**Steps to reproduce the bug**
- Run the sample
- Scroll through mouse wheel or mouse pad

**Expected behavior**
Empty space should not be reproduced. It should be scrolled without empty space like scroll through scroll bar or through touch.

**Screenshots**
Video: [Scroll_Issue_video.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6128783/Scroll_Issue_video.zip)

**Sample:**
[WinUIScrollDemo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6128789/WinUIScrollDemo.zip)

**Version Info**

WinUI NuGet package version = 3.0.0-preview4.210210.4

OS version = Windows 10 Pro

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@RBrid Can you weigh in?

**Comment by RBrid** [comment]
Hello @Ganeshamoorthy10, you should see the same behaviors for touch and mouse wheel as they are 'independent' manipulations, that is the rendering is done off the UI thread and the UI thread occasionally raises the ScrollViewer.ViewChanged event with newer but still outdated Horizontal/VerticalOffset and ZoomFactor. Those 3 properties are out-of-sync with the actual rendering until the manipulation stops and then a final ScrollViewer.ViewChanged with e.IsIntermediate=False is raised with the final values.  During the manipulations, we also raise ScrollViewer.ViewChanging with the anticipated final View.

Have you tried using safety buffers before and after the visible viewport? i.e. you generate and lay out a couple of additional rows before and after the viewport indicated by ScrollViewer.VerticalOffset. This would get enough time for the UI thread to catch up with the rendering thread.  You could even get fancier and use buffer based on the estimated velocity of ScrollViewer.VerticalOffset.  

Hope this helps. Thanks.
