### ISSUE TITLE
NavigationView pane occasionally left open in compact mode after resizing

### ISSUE THREAD

**Issue by kaiguo** [Microsoft/microsoft-ui-xaml#450]
**Describe the bug**
NavigationView pane gets stuck with open pane after resizing, and light dismiss layer stops working.

**Steps to reproduce the bug**

1. Go to NavigationView test page in MUXControlsTestApp.
2. Quickly changing window width to make NavView switch between expand and compact mode.
3. After resizing a few times, NavView pane will stuck open in compact mode.

**Expected behavior**
NavView pane should be closed after window resizing in compact mode.

**Screenshots**

![Annotation 2019-03-18 152114](https://user-images.githubusercontent.com/4424330/54567562-80b5e280-4991-11e9-808c-80ebe0d7a23b.jpg)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18361.19h1_release_dep)                   |  Yes    |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@kaiguo is this something you think can be fixed in the next couple of weeks? Is it possible to work around what I assume is a SplitView bug?

**Comment by kaiguo** [comment]
I *think* I have a fix for it, I'll ask Ramaswamy to verify first.

This is actually different from the SplitView bug, I wasn't able to repro it in a standalone SplitView.

The SplitView bug is, when you turn off animation, IsPaneOpen property changes correctly but visual transition doesn't happen. This bug happens when animation is turned on. If you close NavView pane and then expand it again before closing animation finishes by resizing the window really quickly, NavView.IsPaneOpen and SplitView.IsPaneOpen get out of sync. You can tell the difference visually, the pane doesn't have any content when that SplitView bug happens, pane content is still there for this bug.
