### ISSUE TITLE
MediaTransportControls are not automatically hiding when playing audio files

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#4500]
**Describe the bug**
The `MediaTransportsControls` are never hiding when playing audio files when [ShowAndHideAutomatically](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediatransportcontrols.showandhideautomatically?view=winrt-19041#Windows_UI_Xaml_Controls_MediaTransportControls_ShowAndHideAutomatically) property is set to true.
There is no issue when playing video files.

**Steps to reproduce the bug**

1. Create an app using the following XAML snippet:
```xml
MediaPlayerElement
      AreTransportControlsEnabled="True"
      AutoPlay="True">
      <MediaPlayerElement.TransportControls>
          <MediaTransportControls ShowAndHideAutomatically="True" />
      </MediaPlayerElement.TransportControls>
 </MediaPlayerElement>
```
2. Load an audio file and wait more than 5 seconds.

**Expected behavior**
The MTC is hiding as done for the video files..

**Current behavior**
The MTC remains visible.

**Additional context**
Here is a small sample app support mp3 and mp4 file to highlight the different behavior between audio and video files.
[MediaPlayer.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6130977/MediaPlayer.zip)

**Comment by StephenLPeters** [comment]
@vgromfeld what version of Winui are you experiencing this with?

**Comment by vgromfeld** [comment]
@StephenLPeters, the `MediaTransportControls `control is not part of WinUI (yet?). It comes from the system default controls set.

**Comment by StephenLPeters** [comment]
@ranjeshj or @YuliKl is this owned by us or maintained by another team?

**Comment by StephenLPeters** [comment]
@YuliKl to find the owning team.
