### ISSUE TITLE
WinUI 0.5: The target "_CalculateXbfSupport" does not exist in the project.

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#4503]
**Describe the bug**
I can't seem to target UWP in a class library any longer with the latest Project Reunion Update
I'm currently met with the following build error when compiling my class library:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\WindowsXaml\v16.0\8.21\Microsoft.Windows.UI.Xaml.Common.targets(89,90): error MSB4057: The target "_CalculateXbfSupport" does not exist in the project.

**Steps to reproduce the bug**

1. Unzip the following simple project:
   [ClassLibrary1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6132722/ClassLibrary1.zip)
2. Compile it.

**Expected behavior**
Observe the above build error

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease] If you're seeing your issue in older previews, please try this release.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Build error can be worked around by adding (albeit this might break UWP):
```xml
  <Target Name="_CalculateXbfSupport" Condition="'$(TargetFramework)'=='uap10.0.17763'"/>
```

**Comment by StephenLPeters** [comment]
@alwu-msft @fabiant3 and @MikeHillberg FYI

**Comment by IsmailHassani** [comment]
I encountered this issue also with a multi-platform class library.
Maybe you need to add a condition to this packagereference to disable it for UWP.

```
<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-windows10.0.18362.0'">
   <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
</ItemGroup>
```

**Comment by krschau** [comment]
Closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615). If you are still seeing the behavior with the latest WindowsAppSDK version, please open a new issue.
