### ISSUE TITLE
In-app acrylic brushes on MSIX apps fail

### ISSUE THREAD

**Issue by xerz-one** [microsoft/microsoft-ui-xaml#4504]
**Describe the bug**
In an MSIX-packaged Win32 project, if setting an in-app acrylic brush as a fill or background property on any element with support for the properties, the project halts during execution and throws an exception like the following:

```
Exception thrown at 0x751BA8B2 in HelloReunion.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0317DD40.
```

The output contains information like the following:

```
Exception thrown at 0x751BA8B2 (KernelBase.dll) in HelloReunion.exe: 0x40080202: WinRT transform error (parameters: 0x8000000B, 0x80070490, 0x00000022, 0x0317D3E4).
Exception thrown at 0x751BA8B2 (KernelBase.dll) in HelloReunion.exe: WinRT originate error - 0x80070490 : 'Windows.Graphics.Display: GetForCurrentView must be called on a thread that is associated with a CoreWindow.'.
Exception thrown at 0x751BA8B2 in HelloReunion.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0317DD40.
```

Notice, specifically, the following message: `GetForCurrentView must be called on a thread that is associated with a CoreWindow.`. This implies there is no support for Win32 window handles, and only CoreWindows on WinRT are compatible.

**Steps to reproduce the bug**
1. Create a new Visual Studio project using the "Blank App, Package (WinUI in Desktop)" template from Project Reunion
2. Set an in-app acrylic brush (e.g. `SystemControlAcrylicElementBrush`) as an element's background or fill property, like in e.g. https://gist.github.com/xerz-one/b8c8a53a837ba231b6814bbe495161b7
3. Build and run the project, load the view where the brushed element is located at

**Expected behavior**

The program executes with no errors and displays an element with an acrylic brush applied. This should not be an issue, since in-app acrylic brushes are now supported.

**Version Info**

NuGet package version: 
WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No                   | Yes                  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

**Comment by xerz-one** [comment]
This is related to issue #4496, a new ticket was opened after it was requested on https://github.com/microsoft/microsoft-ui-xaml/issues/4480#issuecomment-797554683

**Comment by Noemata** [comment]
If you turn off C++ exceptions as shown here, your app will continue to run: https://github.com/microsoft/microsoft-ui-xaml/issues/4510

Regardless, such exceptions should not be leaking into a managed app and will have a significant drag on performance under the hood.  Microsoft needs a better test suite.

**Comment by xerz-one** [comment]
Yes, it will still run if you skip/disable the exception. But it will run without the brush applied - so, no support, unlike currently claimed.

I personally don't know how C++ exceptions should be handled in managed apps, but I understand this one has a legitimate reason to be thrown.

**Comment by StephenLPeters** [comment]
@pratikone FYI

**Comment by pratikone** [comment]
Yeah, I am aware of this noisy warning. It is not related to acrylic directly. Acrylic calls certain apis which only make sense in UWP apps and not Desktop apps and thus this warning appears. It is being tracked internally and will be removed in future releases. 
#4496  though has the same premise, it is a different bug where acrylic is not rendering at all.

**Comment by xerz-one** [comment]
@pratikone Isn't that the same issue though? Here, once skipping the thrown exceptions, the acrylic still doesn't render.

Regardless, as stated, I opened up the ticket as it was requested, already acknowledging #4496. I understand if it's best to work over there.
