### ISSUE TITLE
Question: How will version numbering work with WinUI3?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#4508]
Is the "3" part of WinUI3 part of the name or the version number? (Or some confusing hybrid of the two?)

WinUI3 [ships in a package](https://www.nuget.org/packages/Microsoft.ProjectReunion.WinUI/) with the version number **0.5.0(-prerelease)**

WinUI3 assemblies (in the above package) include file versions of the form **3.0.0.xxx**

This has the potential to get confusing when the package and the product it contain different version numbers.

Is this new release "WinUI3 version 0.5" or "WinUI version 3.0"?
If it's the former, isn't there a high risk of confusion when we get to "WinUI3 version 2.x", given there is already "WinUI2.x"?

This may seem like nit-picking but naming matters as it helps avoid confusion.
As there is already a lot of confusion about what WinUI3 is, I see it as being beneficial to make decisions that help avoid further confusion wherever possible.

Related: version numbers starting 0.x are often treated as (and assumed to be) pre-release versions but it has been stated that the version of WinUI3 shipping with the ProjectReunion 0.5 release will be a stable, supported version. This mixed message with inconsistent version numbers and the expectations around them are already causing confusion.

If this release of WinUI is version 3.0, please version the package in the same way.

**Comment by mrlacey** [comment]
X-Ref: https://github.com/microsoft/ProjectReunion/discussions/582

**Comment by mrlacey** [comment]
Summary of the discussions relating to this topic in the above linked issues (#4427 & #4484):
- WinUI3 "feels" like it's at a 0.5 version level [of completion / stability]
- Using a mixture of both **0.5** and **3** as the version numbers is confusing.

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI

**Comment by MikeHillberg** [comment]
It it a bit confusing, I think better in 1.0 though.

The "3" is part of the component name, so it's the WinUI 3 component in the Windows App SDK 1.0. Prior to 1.0 the WinAppSDK NuGet package (then named Project Reunion) had a dependency on the WinUI3 NuGet package, which was actually just metadata so not independently  usable. In WinAppSDK 1.0 there's only the one NuGet package so hopefully less confusing.
