### ISSUE TITLE
Discussion: What are your VS Debug settings for WinUI 3 Desktop?

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4513]
What are the settings in VS i should check to make sure that I get the best possible development experience for WinUI 3 Desktop?

This [page](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/debugging_crashes.md) suggests setting the _mixed_ debugger type? Is that for developing WinUI 3 apps or for debugging the framework?

Should I load symbols from Microsoft and/or Nuget?

What should my "exception settings" be?

I have [reset](https://www.technipages.com/visual-studio-reset-all-settings) all my VS settings, but the experience has not really been better with vanilla settings.

I often get crashes in App.g.i.cs Program.Main: "Unhandled exception at 0x00007FFE6688BD5C (KernelBase.dll) in MyApp.exe: 0xC0000602:  A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately." Without any details. Surely something is wrong. I can slowly step through the code and find out that way what causes the crash, but that can't be everyone's experience, right?

**Comment by huoyaoyuan** [comment]
I believe there is not enough tooling for mix debugging for now. When I'm debugging:

Go to the output window and see the latest messages. Usually it will contain more exception information.

In the exceptions window, set to always break at Win32/C++ exceptions. This can slow down general performance, and I just enable them temporarily.

Right click on call stack entries and select "load symbol". It will at least tell me the function names.

**Comment by Marv51** [comment]
Experience seems somewhat better with the Reunion 0.5 stable release to me. Closing for now.
