### ISSUE TITLE
ItemsRepeater re-orders/removes items when scrolling within a ScrollViewer and using UniformGridLayout

### ISSUE THREAD

**Issue by brechtb86** [microsoft/microsoft-ui-xaml#4516]
**Describe the bug**

When using an `ItemsRepeater` in a `ScrollViewer` on a `Page` within a `NavigationView` with a custom user control in the `ItemTemplate` and you start to scroll up and down, the items are re-ordered or even removed.

**Steps to reproduce the bug**

1. Open the page "ItemsRepeater Scroll Issue (re-order/remove)". Items are ordered correctly.
2. Start scrolling up and down. Items are re-ordered and sometimes removed.
3. Switch to another page.
4. Switch back to  page "ItemsRepeater Scroll Issue (re-order/remove)". Items are ordered correctly again.
5. Rinse and repeat.

**Expected behavior**

Items should stay in the same order.

**Screenshots**

Click the image below to see a Youtube video:

[![See Youtube video](https://img.youtube.com/vi/pfv2hoaWBOY/0.jpg)](https://www.youtube.com/watch?v=pfv2hoaWBOY)

**Version info**

Nuget package version: [WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease]

Windows app type

**UWP** | **Win32**
-- | --
 ?  |  Yes

**Windows 10 version** | **Saw the problem?**
-- | --
Insider Build (xxxxx) |  
October 2020 Update (19042) | Yes
May 2020 Update (19041) |  
November 2019 Update (18363) |  
May 2019 Update (18362) |  
October 2018 Update (17763) |  
April 2018 Update (17134) |  
Fall Creators Update (16299) |  
Creators Update (15063) |  

**Code**

A small project can be found in my repository: [https://github.com/brechtb86/microsoft-ui-xaml-issues](https://github.com/brechtb86/microsoft-ui-xaml-issues)

ItemsRepeaterScrollIssuePage.xaml:

```
<Page
    x:Class="WinUI3Issues.ItemsRepeaterScrollIssuePage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUI3Issues"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:models="using:WinUI3Issues.Models"
    xmlns:userControls="using:WinUI3Issues.UserControls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    DataContext="{Binding Path=ItemsRepeaterScrollIssueViewModel, Source={StaticResource ViewModelLocator}}">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <TextBlock Grid.Row="0" Text="Start scrolling" />
        <ScrollViewer Grid.Row="1">
            <ItemsRepeater ItemsSource="{Binding Path=DummyObjects}">
                <ItemsRepeater.Layout>
                    <UniformGridLayout Orientation="Horizontal" ItemsStretch="Fill" MinColumnSpacing="24" MinRowSpacing="24"></UniformGridLayout>
                </ItemsRepeater.Layout>
                <ItemsRepeater.ItemTemplate>
                    <DataTemplate x:DataType="models:DummyObject">
                        <Grid>
                            <userControls:DummyObjectControl Title="{Binding Path=Name}"></userControls:DummyObjectControl>
                        </Grid>
                    </DataTemplate>
                </ItemsRepeater.ItemTemplate>
            </ItemsRepeater>
        </ScrollViewer>
    </Grid>
</Page>
```

DummyObjectControl:

```
<UserControl
    x:Class="WinUI3Issues.UserControls.DummyObjectControl"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUI3Issues.UserControls"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Border Height="288" Width="192" BorderThickness="1" BorderBrush="{ThemeResource TextBoxBorderThemeBrush}">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>
            <TextBlock Grid.Row="0" HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="16" Text="{x:Bind Path=Title, Mode=OneWay}"></TextBlock>
        </Grid>
    </Border>
</UserControl>
```

ItemsRepeaterScrollIssueViewModel:

```
public class ItemsRepeaterScrollIssueViewModel : BaseViewModel
{
    public ObservableCollection<DummyObject> DummyObjects { get; set; }

    public ItemsRepeaterScrollIssueViewModel()
    {
        this.DummyObjects = new ObservableCollection<DummyObject>();

        for (var i = 1; i <= 100; i++)
        {
            this.DummyObjects.Add(new DummyObject(){ Name = $"Object_{i}"});
        }
    }
}

```

DummyObject

```
    public class DummyObject
    {
        public string Name { get; set; }
    }

**Comment by StephenLPeters** [comment]
@ranjeshj thoughts?

**Comment by brechtb86** [comment]
Oh yes, one more thing, I'm using Ninject and my viewmodels are resolved as a static, so in the video when I go to the screen for the second time the ObservableCollection is not refilled, the items re-order themselves.

**Comment by brechtb86** [comment]
I updated the project to Project Reunion 0.8. Problem still remains, anyone any thoughts?

**Comment by brechtb86** [comment]
Update, I have implemented something new in my app (search functionality) that obviously changes the `ObservableCollection` and what is shown in the `ItemsRepeater` doesn't represent at all what's inside the collection. I'm 100% sure that the correct items are in the collection on the viewmodel. It's also not just the images that change, the item in the `ItemsRepeater` is totally different (if I play the movie it is the movie that is displayed on the cover, which is also a binding to my `UserControl` inside the repeater

I have a video that explains a bit more: [https://youtu.be/AgZFs0G9U4k](https://youtu.be/AgZFs0G9U4k)

The binding to the Movies collection as you can see in the video is as follows:

```
<ScrollViewer Grid.Row="3">
    <ItemsRepeater ItemsSource="{Binding Path=Movies}">
        <ItemsRepeater.Layout>
            <UniformGridLayout Orientation="Horizontal" ItemsStretch="Fill" MinColumnSpacing="24" MinRowSpacing="24"></UniformGridLayout>
        </ItemsRepeater.Layout>
        <ItemsRepeater.ItemTemplate>
            <DataTemplate x:DataType="viewModels:MovieViewModel">
                <Grid>
                    <movieControls:MovieTile 
                    Title="{Binding Path=Model.Title}"
                    PosterBase64="{Binding Path=Model.Poster}"
                    FilePath="{Binding Path=Model.Path}"
                    PlayCommand="{Binding Path=MoviesViewModel.PlayMovie, Source={StaticResource ViewModelLocator}}"></movieControls:MovieTile>
                </Grid>
            </DataTemplate>
        </ItemsRepeater.ItemTemplate>
    </ItemsRepeater>
</ScrollViewer>
```

**Comment by brechtb86** [comment]
The issue is still there on the release version and .NET 6 .NET 6 and WinUI3 Windows 11 SDK, I committed my sample project in my repository [https://github.com/brechtb86/microsoft-ui-xaml-issues](https://github.com/brechtb86/microsoft-ui-xaml-issues). @ranjeshj Care to look at it if you have time?

**Comment by brechtb86** [comment]
Update, if I set the VerticalCacheLength to a high number, the issue does not present itself, VerticalCacheLength then needs to be higher than the actual amount of items. Is this normal behaviour?

**Comment by chingucoding** [comment]
I think this is an issue with the virtualization code not updating the containers correctly. 

The TL,DR; version of this is that the ItemsRepeater creates a fixed number of realized templates (in your case DummyObjectControl) and keeps updating the controls to what object in the collection they should render. If they don't update correctly, it seems as they will get "shuffled" around since ItemsRepeater keeps reusing the existing controls.
Setting the VerticalCacheLength to a really high value disables the virtualization and every item in your collection gets its own realized control.

**Comment by brechtb86** [comment]
@chingucoding alright, in my actual app these user control items will contain a background image, this will slow down scrolling depending on the amount of items am I right? I will set the VerticalCacheLength to a high number for the time being, I don't expect a very large number of items for now, but it would be nice if this could be fixed.

**Comment by chingucoding** [comment]
Yes that would slow down scrolling performance at some point (depending on the size of items and number of items). Agree with you that it be good if this was fixed.

**Comment by AndrewKeepCoding** [comment]
I manage to reproduce your problem and got to fix it by making the `Title` Dependency Property `static`. So, I guess this problem it's not related to the `ItemsRepeater` itself. At least, I hope so since I want to use as a main component in a app. (・∀・)

**Comment by brechtb86** [comment]
@AndrewKeepCoding This example is just the bare minimum, I'm actually using DP in my real control in an other project, I'll try and make them static too tonight and see what it does, however it still smells fishy to me, we should have to "work around" like this.

**Comment by AndrewKeepCoding** [comment]
@brechtb86 Just to clear. By adding `static` I mean the `TitleProperty` not the actual `Title` property. My understanding is that you need them to be `static`. The code below is from your repo. Your `TitleProperty` is not `static`.

```
public DependencyProperty TitleProperty = DependencyProperty.Register(
    nameof(Title),
    typeof(string),
    typeof(DummyObjectControl),
    new PropertyMetadata(default(string)));
```

**Comment by brechtb86** [comment]
@AndrewKeepCoding Indeed, it fixes the issue, another issue I had was that I set the x:Bind mode not to OneWay, this last fixed the issue when the Observable collection would change. (like filtering the list with a search function).

**Comment by AndrewKeepCoding** [comment]
@brechtb86 Great!
