### ISSUE TITLE
Visual Studio 16.9.1 breaks XAML Islands Project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#4523]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-1691-breaks-XAML-Islands/1367046)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.8.6]
On updating from Visual Studio 16.8.6 to 16.9.1, our previously working XAML Islands build configuration now throws XamlParseExceptions, causing no content to be displayed. The pure UWP configuration works normally.

This happens consistently, it's not just the individual machine.

---
#### Feedback Bot on 3/11/2021, 06:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Nathaniel Cleland on 3/12/2021, 01:20 AM: 

<p>N.b. this problem also manifests itself in Visual Studio 16.10 preview 1.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
Can the original author please provide more information? A repro app would be most helpful but the xaml code which does not parse will be needed for us to investigate this.  @alwu-msft FYI

**Comment by solocle** [comment]
WPF container:
`<Window x:Class="Host.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:xaml="clr-namespace:Microsoft.Toolkit.Wpf.UI.XamlHost;assembly=Microsoft.Toolkit.Wpf.UI.XamlHost"
        xmlns:local="clr-namespace:Host"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800" Closing="Window_Closing">
    <Grid>
        <xaml:WindowsXamlHost InitialTypeName="Gui.ucGui" ChildChanged="WindowsXamlHost_ChildChanged" />
        
    </Grid>
</Window>`
And the Gui.ucGui control that fails to parse:
`<UserControl
    x:Class="Gui.ucGui"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Gui"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    d:DesignHeight="300"
    d:DesignWidth="400">

    <Grid>

    </Grid>
</UserControl>`

**Comment by solocle** [comment]
We found a workaround by adding
`<WapAlwaysBuildDependentProjects>true</WapAlwaysBuildDependentProjects>`

To the package project file.

**Comment by asklar** [comment]
@svetbonev fyi

**Comment by sylveon** [comment]
16.9 and 16.10 both work with my C++ xaml islands app. Seems c# specific.
