### ISSUE TITLE
InfoBar: Close button announcement does not give InfoBar context

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#4534]
**Describe the bug**
With the current announcement on the InfoBar's close button, there is not enough context as to what the button is closing.

**Steps to reproduce the bug**
In Narrator, navigate to the InfoBar XCG page and give focus to the close button. Only "close, button" is announced.

**Expected behavior**
Context that the close button is closing an InfoBar in the announcement: "Close info bar, button"

**Open questions**
- Is it possible to also include severity in this announcement?: "Close error info bar, button"

**Comment by chingucoding** [comment]
Looking into this.
