### ISSUE TITLE
The unhandled exception on closing the touch keyboard in tablet mode

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#4535]
Hello!

I found a bug in tablet mode. When I focus textbox, the touch keyboard is showing. When I close the touch keyboard, the unhandled exception happens suddenly.

You can see this behavior in the gif below.

![image](https://i.imgur.com/VE5K6FZ.gif)

**Steps to reproduce the bug**

1. Create a blank WinUI 3 for UWP application with Project Reuninon SDK.
2. Put TextBox in the MainPage.xaml
2. Run App on the simulator
3. In the simulator enable the tablet mode and focus the text box to show a touch keyboard. 
4. Close the touch keyboard.

**NuGet package version: **

WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

**Windows app type:**
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Version 20H2 (OS Build 19042.804)           |  Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Exception and call stack**

Exception thrown at 0x15B13F5E (dcompi.dll) in App1.exe: 0xC0000005: Access violation reading location 0x00000040.

>	dcompi.dll!Microsoft::UI::Composition::Visual::SetInteraction(class Microsoft::UI::Composition::CompositionPointerEventRouter *)	Unknown
 	dcompi.dll!Microsoft::UI::Composition::Visual::Experimental::SetInteraction(struct IInspectable *)	Unknown
 	Microsoft.ui.xaml.dll!HWCompTreeNodeWinRT::UpdatePrimaryVisualViewportInteraction()	Unknown
 	Microsoft.ui.xaml.dll!HWCompTreeNodeWinRT::UpdatePrimaryVisual()	Unknown
 	Microsoft.ui.xaml.dll!HWCompTreeNodeWinRT::PushProperties()	Unknown
 	Microsoft.ui.xaml.dll!HWCompTreeNode::UpdateTreeVirtual()	Unknown
 	Microsoft.ui.xaml.dll!HWCompTreeNode::UpdateTreeVirtual()	Unknown
 	Microsoft.ui.xaml.dll!CCoreServices::SubmitRenderCommandsToCompositor()	Unknown
 	Microsoft.ui.xaml.dll!CCoreServices::SubmitPrimitiveCompositionCommands()	Unknown
 	Microsoft.ui.xaml.dll!CCoreServices::NWDrawTree()	Unknown
 	Microsoft.ui.xaml.dll!CCoreServices::NWDrawMainTree()	Unknown
 	Microsoft.ui.xaml.dll!CWindowRenderTarget::Draw()	Unknown
 	Microsoft.ui.xaml.dll!CXcpBrowserHost::OnTick()	Unknown
 	Microsoft.ui.xaml.dll!CXcpDispatcher::Tick()	Unknown
 	Microsoft.ui.xaml.dll!CXcpDispatcher::OnReentrancyProtectedWindowMessage()	Unknown
 	Microsoft.ui.xaml.dll!CDeferredInvoke::DispatchQueuedMessage()	Unknown
 	Microsoft.ui.xaml.dll!Microsoft::WRL::Details::DelegateArgTraits<long (__stdcall ABI::Windows::Foundation::ITypedEventHandler_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Microsoft::System::DispatcherQueueTimer *,ABI::Microsoft::System::IDispatcherQueueTimer *>,IInspectable *>::*)(ABI::Microsoft::System::IDispatcherQueueTimer *,IInspectable *)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,ABI::Windows::Foundation::ITypedEventHandler<ABI::Microsoft::System::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::FtmBase>,<lambda_011cd208aea6aa5176cfe2e6aa5f2a84> &,1,ABI::Microsoft::System::IDispatcherQueueTimer *,IInspectable *>::Invoke()	Unknown
 	CoreMessagingXP.dll!Microsoft::WRL::Details::DelegateArgTraits<long ( Windows::Foundation::ITypedEventHandler_impl<struct Windows::Foundation::Internal::AggregateType<class Microsoft::System::DispatcherQueueTimer *,struct Microsoft::System::IDispatcherQueueTimer *>,struct IInspectable *>::*)(struct Microsoft::System::IDispatcherQueueTimer *,struct IInspectable *)>::DelegateInvokeHelper<struct Microsoft::WRL::Implements<struct Microsoft::WRL::RuntimeClassFlags<2>,struct Windows::Foundation::ITypedEventHandler<class Microsoft::System::DispatcherQueueTimer *,struct IInspectable *>,class Microsoft::WRL::FtmBase>,class <lambda_74c1b97b1c2a05a0aae7d9f4d55c50cf>,-1,struct Microsoft::System::IDispatcherQueueTimer *,struct IInspectable *>::Invoke(struct Microsoft::System::IDispatcherQueueTimer *,struct IInspectable *)	Unknown
 	CoreMessagingXP.dll!Microsoft::WRL::InvokeTraits<-2>::InvokeDelegates<class <lambda_2ae92d1256ada6b651b55d5dab7f510d>,struct Windows::Foundation::ITypedEventHandler<class Microsoft::System::DispatcherQueueTimer *,struct IInspectable *> >(class <lambda_2ae92d1256ada6b651b55d5dab7f510d>,class Microsoft::WRL::Details::EventTargetArray *,class Microsoft::WRL::EventSource<struct Windows::Foundation::ITypedEventHandler<class Microsoft::System::DispatcherQueueTimer *,struct IInspectable *>,struct Microsoft::WRL::InvokeModeOptions<-2> > *)	Unknown
 	CoreMessagingXP.dll!Microsoft::WRL::EventSource<struct Windows::Foundation::ITypedEventHandler<class Microsoft::System::DispatcherQueue *,struct IInspectable *>,struct Microsoft::WRL::InvokeModeOptions<-2> >::InvokeAll<class Microsoft::System::DispatcherQueue *,std::nullptr_t>(class Microsoft::System::DispatcherQueue *,std::nullptr_t)	Unknown
 	CoreMessagingXP.dll!Microsoft::System::DispatcherQueueTimer::TimerCallback(void *)	Unknown
 	CoreMessagingXP.dll!CFlat::SehSafe::Execute<<lambda_e16aea3717fc5beac95aa2e513a8f395>>()	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::ActionCallback::ImportAdapter$(class CFlat::Box$1<struct CFlat::FunctionPointerAndUserData$1<long (*)(void *)> > *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Support::ActivationContext::CallbackWithActivationContext(class Microsoft::CoreUI::Dispatch::Timeout *,struct System::UIntPtr)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch(void)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchNextItem(void)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop(enum Microsoft::CoreUI::Dispatch::RunnablePriorityMask)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop(enum Microsoft::CoreUI::Dispatch::RunMode)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessagingEventLoopBridge::Callback_OnSystemDispatch(enum Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority,struct CFlat::Ref<struct System::IntPtr>)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::Callback_OnGroupDispatch(enum Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority,struct CFlat::Ref<struct System::IntPtr>)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::NoContext_GroupDispatchHandler(enum Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority,void *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::NoContext_HighPriorityDispatchHandler(void *)	Unknown
 	CoreMessaging.dll!Microsoft__CoreUI__DispatchGroupHandler$CallbackThunk(class System::Delegate *)	Unknown
 	CoreMessaging.dll!System::Action::Invoke(void)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::Dispatcher::DispatchNextItem(void)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop(struct Microsoft::CoreUI::Dispatch::RunnablePriorityMask)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop(struct Microsoft::CoreUI::Dispatch::RunMode,bool,bool &)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapterBase::DrainCoreMessagingQueue(struct Microsoft::CoreUI::Dispatch::UserAdapterBase__UserPriority,bool,struct System::IntPtr &)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch(bool,struct Microsoft::CoreUI::Dispatch::UserAdapterBase__UserPriority,struct System::IntPtr &)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatchRaw(struct System::IntPtr,struct Microsoft::CoreUI::Dispatch::UserAdapterBase__UserPriority,bool,struct System::IntPtr &)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter_DoWork(struct Microsoft::CoreUI::Dispatch::UserData *,struct Microsoft::CoreUI::Dispatch::UserAdapterBase__UserPriority,bool)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter_HandleDispatchNotifyMessage(struct HWND__ *,unsigned int,long)	Unknown
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc(struct HWND__ *,unsigned int,unsigned int,long)	Unknown
 	user32.dll!__InternalCallWinProc@20()	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	user32.dll!_DispatchMessageW@4()	Unknown
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessMessage(bool bDrainQueue, bool * pbWindowMessagesProcessed, bool * pbInvokeItemProcessed) Line 324	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal(bool bRunAlwaysOnce, void * hEventWait) Line 1950	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessEvents(Windows::UI::Core::CoreProcessEventsOption options) Line 596	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkView::Run()	Unknown
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run()	Unknown
 	twinapi.appcore.dll!<lambda_a740d69e4550265529206848c8e72a27>::<lambda_invoker_stdcall>()	Unknown
 	SHCore.dll!_WrapperThreadProc()	Unknown
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

**Comment by StephenLPeters** [comment]
@jeffstall Callstack looks like a comp crash.

**Comment by codendone** [comment]
I'm not able to repro this on Reunion 0.5.7, but I think there's just something in my setup which happens to be missing the problematic call. I believe this is an issue which is fixed in Reunion 0.8 ([internal task which I believe fixed this](https://microsoft.visualstudio.com/OS/_workitems/edit/31368556/)).

If you still repro this in the 0.8 preview, please reactivate.
