### ISSUE TITLE
Padding of Minimize/Maximize/Close Buttons is Not Consistent When Using ExtendsContentIntoTitleBar

### ISSUE THREAD

**Issue by FreddyD-GH** [microsoft/microsoft-ui-xaml#4536]
**Describe the bug**
When using a custom title bar with `ExtendsContentIntoTitleBar = true`, the size of the title bar buttons changes to 21x46 pixels, instead of the normal 29x45 pixels.  This makes the WinUI window look very bad when you have it next to windows with the standard buttons.  Because this change also alters the hitbox of the close button, it really messes up the end user's muscle-memory when they go to close the window.  From what I can tell, the icons of the button look to be approximately the right size, the main issue is that the buttons lack a significant amount of top/bottom padding .

**Steps to reproduce the bug**
Create a custom title bar with WinUI.

**Expected behavior**
I expect the title bar buttons to be same size as a normal Windows 10 window.

**Screenshots**
![Example](https://user-images.githubusercontent.com/12990709/111295213-82b6e880-8621-11eb-9fca-d126b43e849a.png)

**Version Info**

NuGet package version: 
WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
None

**Comment by huoyaoyuan** [comment]
I remember that I can see both sizes in different type of Win32 applications in Win10.

**Comment by mdtauk** [comment]
Win32 is different from Dialog Windows, and from UWP windows.

![image](https://user-images.githubusercontent.com/7389110/111306748-831aa800-8650-11eb-90b1-0854a7831ea6.png)

Sun Valley is likely to see a re-design of the window chrome for all apps, so either WinUI adapts these buttons based on Windows version, or designed to match what the future design will be

![image](https://user-images.githubusercontent.com/7389110/111307430-5915b580-8651-11eb-8c30-46afe23f3711.png)

**Comment by StephenLPeters** [comment]
@pratikone and @Austin-Lamb

**Comment by FreddyD-GH** [comment]
Maybe I should clarify - if WinUI wants to change the style of the title bar buttons, that's fine with me.  My main point here is that it should be consistent WITHIN WinUI.  If I create two windows WITHIN the same app, it looks ridiculous if their title bar buttons are different.

**Comment by bkaankose** [comment]
This is definitely unwanted behavior and should be considered as bug. WinUI needs to copy UWP when it comes to CoreTitleBar and AppTitleBar, both visually and functionality wise because it was perfect. What's the point of making the app 'look rich' by making it use latest UWP control set and leave the Title Bar (which makes the app unique for most cases) old?

**Comment by FreddyD-GH** [comment]
Looks like this issue has been addressed in the version 0.5.7 servicing update, but the issue still exists in 0.8.0-preview.  As long as the change is also going to be made for 0.8.0, I think this issue could probably be closed.

**Comment by codendone** [comment]
The fix will be in 0.8.0, and unfortunately just missed the snap for the 0.8.0-preview.
