### ISSUE TITLE
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

### ISSUE THREAD

**Issue by s3nt1n3l-hub** [microsoft/microsoft-ui-xaml#4537]
**Describe the bug**
Since updating a project to the latest version of WinUI3 (Reunion 0.5) we receive the following error whenever trying to debug:

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache) in /_/src/coreclr/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 4005
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions) in /_/src/coreclr/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 4062
   at System.Activator.CreateInstance[T]() in /_/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs:line 151
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at Project.Program.Main(String[] args) in C:\Users\USER\Source\Repos\Project\Project.UI\Project.UI\obj\x64\Debug\net5.0-windows10.0.19041.0\App.g.i.cs:line 26

  This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int) in Marshal.cs
    WinRT.BaseActivationFactory.BaseActivationFactory(string, string)
    Microsoft.UI.Xaml.Application._IApplicationStatics._IApplicationStatics()

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
```

**Steps to reproduce the bug**
We used a project created in WinUI3 v3 and followed the official instructions to upgrade to Reunion 0.5. The original project works as expected until Reunion is installed/WinUI3 removed - then we are unable to run the project with the CLASSNOTREG error.

**Expected behavior**
The project will run as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/60322747/111297581-abe97000-8645-11eb-96fc-395897f32a30.png)

**Version Info**
NuGet package version: 
Microsoft.ProjectReunion-v0.5.0-prerelease
Microsoft.ProjectReunion.Foundation-v0.5.0-prerelease
Microsoft.ProjectReunion.WinUI-v0.5.0-prerelease

Windows app type: 
Win32

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@fabiant3 and @RealTommyKlein Is the reflection provider your team's?

**Comment by RealTommyKlein** [comment]
This is not from the reflection provider, as it doesn't exist for WinUI 3/Project Reunion.  As a sanity check, the app being debugged doesn't have "Package" in the name, which is the default for packaging projects (e.g. "`ETIHub.TDHub.Demo.UI (Package)`" instead of "`ETIHub.TDHub.Demo.UI`").  Can you confirm the wapproj/packaging project is being run instead of the unpackaged application?

**Comment by Noemata** [comment]
@RealTommyKlein , lots of folks are making the mistake of running the wrong project.  I'm also baffled by the double compile cycle?  We've been down this road before, and always wind up with a single project.  Better sooner than later.

**Comment by s3nt1n3l-hub** [comment]
@RealTommyKlein - Unfortunately this is not the case (screenshot below):

![image](https://user-images.githubusercontent.com/60322747/111453373-6becc080-870b-11eb-85ec-623ad53e97a8.png)

**Comment by s3nt1n3l-hub** [comment]
For now we've gotten around the issue by creating a new project of type 'Blank App, Packaged (WinUI in Desktop)' and moved the contents of the old project in to it. This 'fresh' project runs without issue.

**Comment by RealTommyKlein** [comment]
@s3nt1n3l-hub - good to hear you got it working.  Did you notice any differences in the working vs. non-working project that weren't covered by our upgrade instructions?

**Comment by tedekeroth** [comment]
> For now we've gotten around the issue by creating a new project of type 'Blank App, Packaged (WinUI in Desktop)' and moved the contents of the old project in to it. This 'fresh' project runs without issue.

I tried that, but I get the same error as described here, when creating a new project:
![image](https://user-images.githubusercontent.com/10088477/116190477-04bf2480-a72b-11eb-9e36-2c478a813cd4.png)

I just copy the global.json file and edit the csproj file (see here https://github.com/microsoft/ProjectReunion/issues/740) but the same error persists.
