### ISSUE TITLE
CustomControl template not loading in WinUI3 for Desktop

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4540]
Custom  controls template is not applied.

Please see attached project

[App7.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6152392/App7.zip)

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by huoyaoyuan** [comment]
Duplicate of #4414

**Comment by arivoir** [comment]
This was fixed in _.NET SDK 5.0.202_
