### ISSUE TITLE
ProgressRing with no size specified Stretches Vertically, but not Horizontally

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#4544]
**Describe the bug**

When omitting size properties on the ProgressRing, the default Height and Width are not equal 

**Steps to reproduce the bug**

Add this to a page:
`            <Grid VerticalAlignment="Stretch" Margin="5" Background="Beige"  Width="200" >
                <ProgressRing IsActive="True" VerticalAlignment="Center" HorizontalAlignment="Center" />
            </Grid>
`

**Expected behavior**

A ProgressRing that is symmetric and centered in the grid
**Screenshots**

![image](https://user-images.githubusercontent.com/9586533/111400485-a95a3b00-8684-11eb-8b09-a252df5dcd49.png)

**Version Info**

NuGet package version: 

![image](https://user-images.githubusercontent.com/9586533/111399957-9b57ea80-8683-11eb-95d4-3245cd94e60c.png)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | YES |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | YES   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Agreed, progress ring should probably have a default height as well as a width.  A height setter in the style of 32 seems needed.

**Comment by chingucoding** [comment]
I would like to take a look at this.

**Comment by michael-hawker** [comment]
@StephenLPeters @chingucoding if a developer wants the progress ring to take up the available space of it's layout container though, how do they do that? Most controls are responsive to the layout they're contained in by default...

This seems to just be masking the underlying problem of what was constraining the layout in the underlying code?

It's also a bit odd that the Stroke Thickness scales with the size and is effectively ignored...?
