### ISSUE TITLE
DataGridRow Drag and Drop Visual does not display most of the time

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#4545]
**Describe the bug**

When performing a Drag and Drop operation with DataGridRow, about 80% of the time the Row visual will not display during dragging.   It does not matter whether the visual is specifically set in code, or the default action.

**Steps to reproduce the bug**

1. Add a DataGrid with rows on a page:
2. Enable Drag and Drop for DataGridRows as necessary:
3. Peform drag operation and observe that the Visual of the row data is often omitted from the drag.  Instead you may see the Caption and/or Glyph

```
private void OnLoadingRow(object sender, Microsoft.Toolkit.Uwp.UI.Controls.DataGridRowEventArgs e)
        {
            e.Row.CanDrag = true;
            e.Row.AllowDrop = true;
            e.Row.DragStarting += Row_DragStarting;
            e.Row.DropCompleted += Row_DropCompleted;
            e.Row.DragEnter += Row_DragEnter;
            e.Row.DragOver += Row_DragOver;
            e.Row.DragLeave += Row_DragLeave;
            e.Row.Drop += Row_Drop;
        }
```

Optionally, code the visual yourself

```
private async void Row_DragStarting(UIElement sender, DragStartingEventArgs args)
        {
            args.AllowedOperations = Windows.ApplicationModel.DataTransfer.DataPackageOperation.Move;

            if (sender is DataGridRow row)
            {
                var def = args.GetDeferral();
                var rtb = new RenderTargetBitmap() { };
                await rtb.RenderAsync(row);
                IBuffer pixelBuffer = await rtb.GetPixelsAsync();
                SoftwareBitmap b = SoftwareBitmap.CreateCopyFromBuffer(pixelBuffer, BitmapPixelFormat.Bgra8, (int)rtb.PixelWidth, (int)rtb.PixelHeight);

                args.DragUI.SetContentFromSoftwareBitmap(b, new Point(rtb.PixelWidth / 2, rtb.PixelHeight / 2));
                def.Complete();
            }
        }
```

**Expected behavior**
Automatic rendering of the Drag Visual for a DataGridRow

**Screenshots**

![TestDnD](https://user-images.githubusercontent.com/9586533/111402502-89c51180-8688-11eb-977e-f89f0fb3e7fe.gif)

**Version Info**

NuGet package version: 

![image](https://user-images.githubusercontent.com/9586533/111401680-f7703e00-8686-11eb-8b33-eaed43d194e3.png)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | YES |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | YES   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by jschwizer99** [comment]
I observe a similar behavior when starting the drag operation by `StartDragAsync`. In some cases, the correct behavior is triggered and the element gets moved around. But sometimes I just see the initial `DataPackageOperation::None`. The events `DragStarting` and `DragOver` are triggered correctly. Attaching modifications to `DragUIOverride` in the `DragOver` works fine. It is the attachment at drag start which fails. The frequency of the failure is system-dependent, which could point in direction of a race.

**Comment by omnillogix** [comment]
So there are multiple issues here.  As @jschwizer99 mentions, the DragStarting can fail to render a visual at random times.  Also, as can be observed in the animation above, the DragOver event is not raised properly.  When entering a DataGridRow, I have applied a Margin to add separation to the rows as a visual indicator of the drop location.  The color of the grid below is Gray as can be seen.  However, no DragOver event is raised when dragging over the Margin area of the rows, and that event is not passed to the visible DataGrid surface either.

**Comment by codendone** [comment]
We just debugged this issue last week. This is unfortunately a bug in Windows specific to non-UWP apps. It isn't clear right now if we can fix this in WinUI3. On the plus side, this has been fixed in Windows, and is available in current Dev Channel builds from the Windows Insider Program.

**Comment by codendone** [comment]
Note: In theory it is possible to avoid the issue if you can avoid any awaits (and taking a deferral) in your DragStarting handler. But that likely isn't reasonable for most uses to already have the bitmap ready.

**Comment by codendone** [comment]
Since #4528 is the same issue, I'm going to close this issue. You can track that one for status.
