### ISSUE TITLE
WinUI3 for desktop also have namespace different with C++/WinRT for UWP

### ISSUE THREAD

**Issue by Dixeran** [microsoft/microsoft-ui-xaml#4547]
**Describe the bug**
As the [limitation for C#](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#limitations-and-known-issues):

> When using C# for a WinUI 3 app in UWP, there are a few API namespace differences compared to C# in a WinUI 3 desktop app or a C# WinUI 2 app: some types are in a Microsoft namespace rather than a System namespace. For example, rather than the INotifyPropertyChanged interface being in the System.ComponentModel namespace, it’s in the Microsoft.UI.Xaml.Data namespace.

In WinUI3 for Win32 desktop, the INotifyPropertyChanged also need to use namespace `Microsoft::UI::Xaml::Data` instead of  `Windows.UI.Xaml.Data` which listed from [here](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property#implement-booksku)

**Steps to reproduce the bug**
1. implement a ViewModel with idl file:
```
namespace App1 {
  [default_interface] runtimeclass ObservableString
      : Windows.UI.Xaml.Data.INotifyPropertyChanged {
    ObservableString(Int32 title);
    Int32 Title;
  }
} 
```
2. data binding failed, `PropertyChanged` never called
3. implement with idl file:
```
namespace App1 {
  [default_interface] runtimeclass ObservableString
      : Microsoft.UI.Xaml.Data.INotifyPropertyChanged {
    ObservableString(Int32 title);
    Int32 Title;
  }
} 
```
4. data binding worked

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 
WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by shaheedmalik** [comment]
UWP hasn't been updated to support WinUI 3 yet. If I recall, UWP won't support WinUI 3 until version WinUI 3.1. The Microsoft namespace replaced the Windows namespace.

**Comment by Dixeran** [comment]
Got it. So I was confused by the out dated document. Thanks for the reply :)
