### ISSUE TITLE
Can you please keep the roadmap more up to date?

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4548]
The latest preview is not on the [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md).

The "[Feature Roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-30-feature-roadmap)" only has two categories left: "Reunion 0.5" (in two weeks) and "Planned for a future update" (which could not be any vaguer.)

I understand not wanting to promise too much. But at this point you are promising nothing that is more than 2 weeks away from shipping.

Are there going to be future previews, I guess so, I remember @ryandemopoulos speaking about roughly monthly previews at some point?

Maybe the "Milestones" in GitHub could be used to track some of the progress? (Currently they are clearly [very outdated](https://github.com/microsoft/microsoft-ui-xaml/milestones).)

(Btw. the project [reunion roadmap](https://github.com/microsoft/ProjectReunion/blob/main/docs/roadmap.md) contains the "unpackaged desktop apps WinUI 3" as part of the Q4 2021 milestone, but the WinUI 3 roadmap does not give and date for that)

**Comment by anawishnoff** [comment]
Thanks for this feedback @Marv51! At this stage in our planning we're looking at three timeframes - Project Reunion 0.5, Project Reunion 0.8, and Post-Project Reunion 0.8. What we have on the roadmap should be updated for those timeframes, but it's always a good idea for me to look through it and clean it up.

You're right that the roadmap image didn't include the Project Reunion 0.5 preview - that's a mistake, it should. The feature roadmap should hopefully provide some clarity there - certain features are marked as preview (the blue diamond) in the Project Reunion 0.5 release. This means that those features will be included in the Project Reunion 0.5 preview. We are hoping to start shipping more previews, and so perhaps the roadmap structure (the timeline picture, mainly) may have to change a bit to better express our ship schedule.

**Comment by Marv51** [comment]
@anawishnoff Thanks for your comments on this. The public roadmap does not really say anything about what Project Reunion 0.8 will contain, is it a bug fix only release for WinUI 3?

**Comment by Marv51** [comment]
This is still an issue to me. The roadmap show on the last community call is not reflected in the document. There are comments all over the issues shedding a bit of light on the actual roadmap.

Some ideas for the updated roadmap:
* You plan on having a 0.8 preview in [late April](https://github.com/microsoft/microsoft-ui-xaml/issues/4816#issuecomment-824228704), early May
* You said preview features will return in 0.8 preview builds
* Currently some development focus on [multi-window support](https://github.com/microsoft/microsoft-ui-xaml/issues/4777#issuecomment-816900808) which might make it into 0.8
* [Return of Pivot](https://github.com/microsoft/microsoft-ui-xaml/issues/4816#issuecomment-824228704)

/cc: @anawishnoff 

Would you accept a pull request for changes to that document?

**Comment by anawishnoff** [comment]
Hi @Marv51, on the feature roadmap portion you can see that certain features are marked with a diamond at the 0.5 and 0.8 release columns - this means that these features will be included in the previews for those releases. So multi-window support for example has a diamond underneath the 0.8 release column - that means it'll be included in the 0.8 preview. If this system is confusing as a whole, let me know. We intended for it to be a nice compact way to show feature progress, but don't want it to spark more confusion.

I will definitely update the main roadmap image with the one that we should during the community call, and add some more context on the scheduling of the preview releases. Thanks for the feedback and the ping on this!

**Comment by Marv51** [comment]
Feel like my feedback has been addressed her. Thanks @anawishnoff.
