### ISSUE TITLE
AppBarButton get symbol with Flyout in CommandBar with 2.6 prerelease

### ISSUE THREAD

**Issue by Psykobal** [microsoft/microsoft-ui-xaml#4549]
**Describe the bug**
AppBarButtons inside CommandBar.PrimaryCommands get a > symbol in 2.6 prerelease

**Steps to reproduce the bug**
Clone and run: [sample](https://github.com/Psykobal/WinUI_Sample)

**Expected behavior**
![NoChevron](https://user-images.githubusercontent.com/15339175/111453253-a9554c00-8713-11eb-8e8c-e700c0cbf2cd.png)
**Screenshots**
![chevron](https://user-images.githubusercontent.com/15339175/111453278-afe3c380-8713-11eb-967f-ece5028cf31f.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.6.0-prerelease.210227001]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Was working until [2.6.0-prerelease.210113001]

**Comment by StephenLPeters** [comment]
@ranjeshj and @YuliKl

**Comment by ranjeshj** [comment]
@StephenLPeters @Psykobal That looks like the correct behavior and I see the chevron with 2.5 stable release as well.

**Comment by Psykobal** [comment]
I don't know if it's the correct behavior (and I hope it isn't) but it changes between 2.5 and 2.6.0-prerelease.210129001, at least in my app and in the sample on my computers. 

With the xaml:
```
<CommandBar` ClosedDisplayMode="Compact"
                       OverflowButtonVisibility="Collapsed">
            <CommandBar.Content>
                <AppBarButton Icon="More">
                    <AppBarButton.Flyout>
                        <CommandBarFlyout Placement="Right">
                            <AppBarButton  Icon="Play" />
                            <AppBarButton  Icon="People" />
                        </CommandBarFlyout>
                    </AppBarButton.Flyout>
                </AppBarButton>
            </CommandBar.Content>
            <CommandBar.PrimaryCommands>
                <AppBarButton Icon="More">
                    <AppBarButton.Flyout>
                        <CommandBarFlyout Placement="Right">
                            <AppBarButton Label="Play"
                                          Icon="Play" />
                            <AppBarButton  Icon="People" />
                        </CommandBarFlyout>
                    </AppBarButton.Flyout>
                </AppBarButton>
            </CommandBar.PrimaryCommands>
        </CommandBar>
```

This is the results I get:

- 2.5.0
![2 5](https://user-images.githubusercontent.com/15339175/111807618-69d55e00-88d3-11eb-8d2a-7bbde369146c.png)

- 2 6 0-prerelease.210113001
![2 6 0-prerelease 210113001](https://user-images.githubusercontent.com/15339175/111807512-4d392600-88d3-11eb-87bf-3bf15314eb31.png)

- 2.6.0-prerelease.210315002 (and all after 210113001)
![2 6 0-prerelease 210315002](https://user-images.githubusercontent.com/15339175/111807869-b5880780-88d3-11eb-8774-6397e7975b4a.png)

It doesn't look like this on yours?

**Comment by StephenLPeters** [comment]
@Psykobal are you using XamlControlsResouces.ControlsResourcesVersion="Version2" or Version 1(the default)

**Comment by Psykobal** [comment]
@StephenLPeters I am using only default parameters:

```
<Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
</Application.Resources>
```
