### ISSUE TITLE
Combobox changing size when popup open

### ISSUE THREAD

**Issue by Alexander-Kamenchuk** [microsoft/microsoft-ui-xaml#4551]
**Describe the bug**
Hi,
The ComboBox loses value and changes a width when the popup was opened. 
Please, take a look at the GIF. It's unexpected for us.
https://i.imgur.com/CCroWdF.gif

**Steps to reproduce the bug**
```xaml
<ComboBox  SelectedIndex="0" Header="Combobox">
   <ComboBox.Items>
      <TextBlock Text="This is long text in combobox item"/>
      <TextBlock Text="Item2"/>
   </ComboBox.Items>
</ComboBox>
```
**Expected behavior**
The width shouldn't change.

**Version Info**
NuGet package version:
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| October 2020 Update (19042)        |  |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |   |
| April 2018 Update (17134)          |   |
| Fall Creators Update (16299)       |   |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        | |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@Alexander-Kamenchuk Can you please try using a newer winui3 preview? https://docs.microsoft.com/en-us/windows/apps/winui/winui3/ or if that doesn't work https://github.com/microsoft/microsoft-ui-xaml/issues/4156

**Comment by Alexander-Kamenchuk** [comment]
Hello. Sorry for late answer. I see the same problems when using a winui3 preview 4

**Comment by StephenLPeters** [comment]
@YuliKl and @chigy FYI

**Comment by alexdi220** [comment]
Hi, the issue still annoying on Reunion 0.5.7\0.8. Do you have any fix or workaround?

**Comment by JonathanWilliams84** [comment]
still an issue as of WindowsAppSdk 1.0.1
More info:
When ComboBox is open it replaces the Content with the "Placeholder". This can be used as a work-around but it is far from an ideal solution.

**Comment by JuanMejiaVelez** [comment]
This is an issue that repros in WinUI 2.x as well, @YuliKl is there any workaround to this?

**Comment by dongle-the-gadget** [comment]
AFAIK, a workaround is to explicitly set the width (i.e. `Width="200"`), but this is rather not ideal for things like localization I would say.

**Comment by Balkoth** [comment]
This is still an issue and should be reopened.

**Comment by seasonyuu** [comment]
Still an issue while using `1.6.250205002`
