### ISSUE TITLE
Foreground Binding in DataTemplate not updated after theme change

### ISSUE THREAD

**Issue by billhenn** [microsoft/microsoft-ui-xaml#4553]
**Describe the bug**

When setting a new theme (Dark/Light), Foreground Bindings within a DataTemplate for a ContentControl (like a Button) aren't immediately refreshing.  Yet once we mouse over the button and move off of it, they are correct from that point on.  This needs to be fixed so they update immediately because DataTemplate-embedded elements like Paths used for glyphs must bind their Fill/Stroke as needed to the current foreground.

**Steps to reproduce the bug**

1) Put this code in a Window's XAML content:
```
<Button>
    <Button.ContentTemplate>
        <DataTemplate>
            <StackPanel>
                <Rectangle Width="16" Height="16" Fill="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=Foreground, Mode=OneWay}" />
                <TextBlock Text="Not updated" Foreground="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=Foreground, Mode=OneWay}" />
                <TextBlock Text="Updated" />
            </StackPanel>
        </DataTemplate>
    </Button.ContentTemplate>
</Button>
<Button Content="Click me" Click="Button_Click" />
```

2) Add this code-behind:
```
private void Button_Click(object sender, RoutedEventArgs e) {
	((FrameworkElement)this.Content).RequestedTheme = ElementTheme.Dark;
}
```

3) I'm assuming your app starts in Light theme.  If not, add `RequestedTheme="Light"` to your application.

4) Run the app and observe the left button's Rectangle/TextBlocks all use a black brush.

5) Click the right button ("Click me") to toggle to Dark theme.  Observe that only the left button's bottom TextBlock's foreground updated.

6) Hover the mouse over the left button and move it out of the button.  Observe that now the Rectangle/TextBlocks all properly use a white brush.

**Expected behavior**

It shouldn't be necessary to hover over the button in step 6 to get it to update the brushes synced up to the new theme properly.  All 3 controls in the DataTemplate should have their foreground updated properly after step 5.

**Screenshots**

Before: 
![image](https://user-images.githubusercontent.com/5760058/111492506-1c11f780-8713-11eb-936e-7847f6391b81.png)

After step 5:
![image](https://user-images.githubusercontent.com/5760058/111492573-29c77d00-8713-11eb-9a1f-acfd3840bd75.png)

After step 6:
![image](https://user-images.githubusercontent.com/5760058/111492617-33e97b80-8713-11eb-8084-b0d8ac415f43.png)

**Version Info**

NuGet package version: 

Microsoft.WinUI 3.0.0-preview4.210210.4 - Couldn't text preview5 yet due to a bug.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
Foreground is a propogating property.  This means that the actual value of Button.Foreground in the property system is null, however the system treats this property in a special way and when it sees null it interprets that as the value of the nearest ancestor which has a non-null value.  I suspect what is happening is that the propagation logic is somehow missing this binding, which seems like a bug.  I think you could work around this by directly setting the foreground property on your button, either by setting it to a theme resource or binding it to one of its ancestors.

**Comment by StephenLPeters** [comment]
@MikeHillberg to make sure I'm not making stuff up about the propogating property.

**Comment by billhenn** [comment]
@StephenLPeters - Even if I change my Button in the XAML to this, there is no change in behavior for the Foreground bindings within the DataTemplate:
```
<Button Foreground="{ThemeResource ButtonForegroundThemeBrush}">
```

We really need this bug resolved since some Path-based icons in buttons will use Strokes and others will use Fill, and they must bind to the foreground color somehow.  This works fine until a theme change occurs, and which time they aren't refreshing themselves properly until forced via something like a Button state change.  Then they work fine from that point on again.  I'm showing the bug with a Rectangle in the sample above, but in a real usage scenario, Path would be used for an icon.

Somewhat related and coming from a WPF background, I miss the ability to set the various TextElement attached properties (Foreground, FontFamily, FontSize, FontWeight, etc.) at any level in the XAML hierarchy (like on panels) and know it would inherit down properly.  In UWP/WinUI, those properties only seem to only be supported on Control, which is limiting in cases like this one where in WPF, I would have bound the Path.Fill/Stroke to the Path's TextElement.Forground instead.

**Comment by codendone** [comment]
I see the binding updating correctly when in a ControlTemplate, but not when in a DataTemplate. The same issue repros in system XAML.

Until this is fixed, you can use a workaround like this, which switches to an ElementName binding with an intermediate UserControl:
```
                    <UserControl x:Name="bindSrc">
                        <StackPanel>
                            <Rectangle Width="16" Height="16" Fill="{Binding ElementName=bindSrc, Path=Foreground, Mode=OneWay}" />
                            <TextBlock Text="Now updates!" Foreground="{Binding ElementName=bindSrc, Path=Foreground, Mode=OneWay}" />
                            <TextBlock Text="Updated" />
                        </StackPanel>
                    </UserControl>
```
