### ISSUE TITLE
Setting DateTime object as Content of ContentPresenter throws expection

### ISSUE THREAD

**Issue by kalin-todorov** [microsoft/microsoft-ui-xaml#4557]
**Describe the bug**
If you set the Content property of ContentPresenter to DateTime object - exception is thrown.

**Steps to reproduce the bug**
1. Create new ContentPresenter
2. Set Content property to DateTime.Today

**Screenshots**
![image](https://user-images.githubusercontent.com/8479530/111539833-06361e00-8777-11eb-9305-2414cacecd68.png)

NuGet package version: 
WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@Scottj1s could this be a cswinrt issue?  if not @alwu-msft do you know how ContentPresenter translates say a String into a textblock when you set it from code?

**Comment by chrisglein** [comment]
Confirmed that on UWP XAML that this works and falls back to an implicit ToString conversion.
So there's something wrong here in either CsWinRT or WinUI3.

**Comment by gabbybilka** [comment]
@Scottj1s is this issue resolved in CsWinRT? (task.ms/32182985) If so, can you close? Thanks!

**Comment by Scottj1s** [comment]
Fixed in cswinrt 1.1.4
