### ISSUE TITLE
ToggleSwitch's header is too close to the control and focus rect needs more padding

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#4561]
The header is too tight to the actual toggle switch. Also the focus rect needs more top/bottom padding - increasing the whitespace between header and switch would give the focus rect more breathing room.

Expected vs Actual:
![toggleswitch](https://user-images.githubusercontent.com/28935693/111570384-f9f39600-8761-11eb-9199-6c6765404a88.png)

**Comment by chingucoding** [comment]
Taking a look at this.
