### ISSUE TITLE
ProjectReunion Break : Simple app with color picker leads to crash in UWP and also Desktop

### ISSUE THREAD

**Issue by syncsiva** [microsoft/microsoft-ui-xaml#4562]
**Describe the bug**
Simple app with color picker leads to crash with ProjectReunion in UWP Desktop. Same works fine with WinUI3 Preview4.

**Steps to reproduce the bug**

[colorpicker-projectreunion.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6161293/colorpicker-projectreunion.zip)

1. Run the attached sample it will leads to exception.

**Expected behavior**
App should run without any exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/18731572/111573439-8d63b000-87d0-11eb-929c-1db062706b83.png)

Below exception occurred in Desktop,
App6.exe has triggered a breakpoint.

**Version Info**
<PackageReference Include="Microsoft.ProjectReunion">
    <Version>0.5.0-prerelease</Version>
</PackageReference>

NuGet package version: 
<PackageReference Include="Microsoft.ProjectReunion">
    <Version>0.5.0-prerelease</Version>
</PackageReference>

**Additional context**
Using flaggable enum in XAML leads to crash in ProjectReunion in our custom control. To check the same in color picker which has `ColorSpectrumComponents ` flaggable enum property.  But it leads to exception when not setting this property also. 

Code:

`
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
    <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    <ColorPicker x:Name="myColorPicker"/>
</StackPanel>
`
https://github.com/microsoft/ProjectReunion/issues/599

**Comment by codendone** [comment]
I don't repro the issue, even when trying the attached repro app running on the 0.5.0-prerelease. Do you still repro the issue? Are there any extra steps to hit the issue?

**Comment by codendone** [comment]
Closing as not reproing. Please reactivate with more info if you still see this.
