### ISSUE TITLE
High CPU load (1 to 2%) for inactive app using WinUI 3 Desktop (Reunion 0.5)

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#4565]
**Describe the bug**
When running my app with Reunion 0.5 prerelease (Desktop), the task manager shows a CPU load ranging from 0.8 to 2%, even when the app is not running any of my code. 

If I hit Break All, the code always stops in the Microsoft.UI.Xaml.Application.Start method. 

**Steps to reproduce the bug**
1. Run a WinUI 3 Desktop app with Reunion 0.5 prerelease bits
2. Check the task manager to see high CPU usage.

**Expected behavior**
Less CPU usage when the application is running and no user-code is running.

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| n/a |  Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)       |  Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |

**Comment by StephenLPeters** [comment]
@bartekk8 for perf

@Austin-Lamb @MikeHillberg @codendone fyi

**Comment by wbokkers** [comment]
This has been mostly solved in Reunion 0.5.5 because the view that is causing the high CPU usage does no longer stay active in memory. I am not sure why the particular control is using this much CPU. There's not much happening in my code, so it must be the XAML.

**Comment by wbokkers** [comment]
After investigating my XAML (and leaving out parts to see the impact on the CPU load), it seems to be related to using a group style in a listview

```xaml
<ListView.GroupStyle>
                <GroupStyle>
                    <GroupStyle.HeaderTemplate>
                        <DataTemplate x:DataType="...">
                                  <TextBlock Text = "{x:Bind GroupName}" />
                        </DataTemplate>
                    </GroupStyle.HeaderTemplate>
                </GroupStyle>
    </ListView.GroupStyle>
```

**Comment by wbokkers** [comment]
I created another issue that is more specific on the cause and adds a link to a github repo that reproduces the issue:

https://github.com/microsoft/microsoft-ui-xaml/issues/4860

https://github.com/wbokkers/reunion-issue-high-cpu

**Comment by wbokkers** [comment]
We still see high CPU loads with Reunion 0.8 Preview.

**Comment by wbokkers** [comment]
With using Windows App SDK 1.1.4, CPU loads are high again. :(
