### ISSUE TITLE
MUXControlsTestApp crashes with old styles

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#4566]
MUXControlsTestApp crashes when using old styles upon navigating to CommonStyles page with following error message:
```
Windows.UI.Xaml.Markup.XamlParseException: 'The text associated with this error code could not be found.

Cannot find a Resource with the Name/Key DefaultGridViewItemStyle [Line: 365 Position: 137]'
```

**Comment by ranjeshj** [comment]
@chingucoding good catch. I think we can add this key to the old styles and just point it to the system GridViewItem style so that this key is available in both. Also, we might need the same for DefaultListViewItem style. @RBrid as FYI. @chingucoding do you want to make a fix for this ?

**Comment by chingucoding** [comment]
Would GridViewItemRevealStyle be the correct style to point to as a fix for this @ranjeshj ? I would create a PR once we know the correct resource in OS Xaml to point to.

**Comment by ranjeshj** [comment]
@chingucoding Yes GridViewItemRevealStyle was the default in old styles.
