### ISSUE TITLE
PointerOver and Pressed color not in sync with accent color for various controls

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/microsoft-ui-xaml#4568]
**Describe the bug**
Right now thumb color for Slider `PointerOver` uses `SystemAccentColorLight1` and `Pressed` uses `SystemAccentColorDark1` (I presume). When changing system accent color these resources aren't updated and require restart of the app to be fixed.

## Update:
This issue also exists with toggle switch, radio buttons etc., anything that uses accent color and not just slider. 

**Steps to reproduce the bug**
1. Implement slider in a sample uwp app.
2. Change system accent color and interact with slider.
3. Restart app and interact with slider.

In case of any doubt, refer the screen recording.

**Expected behavior**
These colors should always be in sync with accent color of the app.

**Screenshots**
![nVkgonvNPi](https://user-images.githubusercontent.com/51203900/111600227-33c2ac00-87f7-11eb-94fb-f1b7442686fa.gif)

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I don't know if this would be classified as platform bug or WinUI bug, so I am filing it here. Also, currently we can manually update these resources by listening to `Windows.UI.ViewManagement.UISettings.ColorValuesChanged`. But for apps that implement customizable accent color this becomes impossible as I don't know how these resources are generated from accent color(Any resource that can guide me to achieve that would be helpful).

## Update
This issue also exists with ToggleSwitch, RadioButtons, CheckBox etc., any control that uses accent color probably.

**Comment by StephenLPeters** [comment]
@YuliKl This looks pretty bad. We should take a look.

**Comment by YuliKl** [comment]
Thank you for reporting, @soumyamahunt . I can repro in [Xaml Control Gallery](https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt). @ranjeshj @StephenLPeters do you think this issue is specific to Slider or indicative of an underlying framework problem?

**Comment by soumyamahunt** [comment]
@YuliKl @StephenLPeters I have updated my comment and the title to reflect that this issue doesn't just exist for slider but for other controls as well.

**Comment by soumyamahunt** [comment]
With the designs updated, in my testing this issue isn't happening any more.
