### ISSUE TITLE
How to disable blinking effect of ContentDialog on appearing and disappearing

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [microsoft/microsoft-ui-xaml#4570]
**Describe the bug**

How to restrict the blinking effect and gray background color in ContentDialog on appearing and disappearing, you can clearly see blinking effect with gray color background while appearing and disappearing the content dialog.

I need to restrict that blinking effect, also that gray color background is not syncing with my theme pattern. Please refer the attached video and screen shot. 

**Note:** I have also tried to restrict the blinking effect and gray background color by customizing the style of ContentDialog, but couldn't able to restrict it.

Could you please check and provide a solution for this?

**Steps to reproduce the bug**

- Run the sample and click Open content dialog button.
- Content dialog will be appeared with blinking effect.

**Expected behavior**
Content dialog should be appeared with out blinking effect.

**Screenshots**

https://user-images.githubusercontent.com/39787321/111618682-aee18d80-880a-11eb-99e1-3394fcff1699.mp4

![Screenshot (21)](https://user-images.githubusercontent.com/39787321/111618805-d0db1000-880a-11eb-9591-7d4e62fc0aa8.png)

![Screenshot (22)](https://user-images.githubusercontent.com/39787321/111619718-ea308c00-880b-11eb-8dfc-f2f735a04b27.png)

**Sample:** [ContentControlDemo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6163694/ContentControlDemo.zip)

**Version Info**

WinUI NuGet package version = 3.0.0-preview4.210210.4

OS version = Windows 10 Pro

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@kmelmon and @gegao18 I think this is the Shadow showing through the partially transparent background.

**Comment by mdtauk** [comment]
I submitted a fix, if this is the same issue - but it was being investigated.

https://github.com/microsoft/microsoft-ui-xaml/pull/4079

**Comment by pratikone** [comment]
since its PR has been merged. closing it
