### ISSUE TITLE
Question: Can I update the CSWinRT version used?

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4571]
Many of the more critical issues/crashes seem to be due to CSWinRT bugs, I saw that they just released an update (1.1.4). It seems to fix some of my issues. 

Can I update to that update myself or do I need to wait for the next WinUI/reunion release?

**Comment by StephenLPeters** [comment]
@Scottj1s thoughts?

**Comment by huoyaoyuan** [comment]
See the workaround in https://github.com/microsoft/microsoft-ui-xaml/issues/4414 . This has been documented in https://github.com/microsoft/CsWinRT/blob/master/docs/versioning.md
