### ISSUE TITLE
AcrylicBrush renders transparent in ProjectReunion 0.5

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#4579]
Hi, I'm building a test app using project Reunion 0.5 and the NavigationView menu does not look like previous releases.  I have not modified the styling.

![image](https://user-images.githubusercontent.com/9586533/111511659-33011b80-870c-11eb-8198-5e3fa7c85e7d.png)

How do I get the previous default style back?

![image](https://user-images.githubusercontent.com/9586533/111511851-588e2500-870c-11eb-92a2-186f28c0253e.png)

**Comment by StephenLPeters** [comment]
This is a known issue, Acrylic is broken in in ProjectReunion 0.5. Currently you wont be able to get the same look from the previous release.
