### ISSUE TITLE
NavigationView causes crash in Reunion-0.5 for Desktop (not UWP)

### ISSUE THREAD

**Issue by canfucius** [microsoft/microsoft-ui-xaml#4581]
**Describe the bug**

**Steps to reproduce the bug**

1. Create a blank WinUI3 for Desktop application with Project Reunion SDK
2. Put NavigationView on the MainWindow.
3. Run the app, Start Debugging (F5).

**Expected behavior**

The app to run without exceptions and without crashing

**Screenshots**

![NavViewError2](https://user-images.githubusercontent.com/7346824/111796341-15f85400-8896-11eb-8236-e92711de8718.PNG)
![NavViewError3](https://user-images.githubusercontent.com/7346824/111796474-332d2280-8896-11eb-98bc-413a82f0f93f.PNG)
![NavViewError4](https://user-images.githubusercontent.com/7346824/111796831-8f904200-8896-11eb-9855-4be465eefd9b.PNG)

**Version Info**

WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

NuGet package version: 

[Microsoft.Extensions.Configuration 5.0.0]
[Microsoft.Extensions.Configuration.Binder 5.0.0]
[Microsoft.Extensions.Configuration.FileExtensions 5.0.0]
[Microsoft.Extensions.Configuration.Json 5.0.0]
[Microsoft.Extensions.DependencyInjection 5.0.1]
[Microsoft.Extensions.Logging 5.0.0]
[Microsoft.Extensions.Logging.Debug 5.0.0]
[Microsoft.ProjectReunion 0.5.0-prerelease]
[Microsoft.ProjectReunion.WinUI 0.5.0-prerelease]
[Microsoft.Toolkit 8.0.0-preview5]
[Microsoft.Toolkit.Mvvm 8.0.0-preview5]
[Microsoft.Toolkit.Uwp.UI 8.0.0-preview5]
[Microsoft.Toolkit.Uwp.UI.Animations 8.0.0-preview5]
[Microsoft.Toolkit.Uwp.UI.Behaviors 8.0.0-preview5]
[Microsoft.Toolkit.Uwp.UI.Controls 8.0.0-preview5]
[Microsoft.Toolkit.Uwp.UI.Controls.DataGrid 8.0.0-preview5]
[Microsoft.Toolkit.Uwp.UI.Controls.Layout 8.0.0-preview5]
[Microsoft.Toolkit.Uwp.UI.Media 8.0.0-preview5]
[Newtonsoft.Json 12.0.3]
[Serilog 2.10.0]
[Serilog.Extensions.Logging 3.0.1]
[Serilog.Sinks.Console 3.1.1]
[Serilog.Sinks.File 4.1.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by kalin-todorov** [comment]
Check this one: #4496

**Comment by canfucius** [comment]
That worked. Strange but it worked.
