### ISSUE TITLE
Fix High Contrast color mappings for buttons

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#4584]
**Describe the bug**
The following controls don't have the most intuitive color mappings when they're drawn in High Contrast.
- ToggleSplitButton
- Button
- ToggleButton

The current mapping may confuse users, especially if they customize the colors of their HC theme. We should correct these mappings, particularly for the new styles, but would not be amiss to apply the same fix to the older styles as well.

## Requested changes
When applying this custom HC theme
![image](https://user-images.githubusercontent.com/13142665/111827103-bc4c5580-88a6-11eb-96f3-a29a75fcfda3.png)
the controls should look like the following.

### ToggleSplitButton
![image](https://user-images.githubusercontent.com/13142665/111827399-16e5b180-88a7-11eb-9866-75c842159a69.png)
 
Needed changes:
**ToggleSplitButton (OFF)**
Rest
- Chevron - SystemColorButtonTextColor

 Hover
- Chevron - SystemColorButtonTextColor
- Main Button Base - SystemColorHighlightTextColor

Pressed
- Chevron - SystemColorButtonTextColor
- Main Button Base - SystemColorHighlightTextColor
- Main Button Stroke -SystemColorHighlightTextColor

**ToggleSplitButton (ON)**
 Hover
- Main Button Base - SystemColorButtonTextColor
- Main Button Stroke - SystemColorButtonTextColor
- Main Button Label - SystemColorButtonFaceColor

Pressed
- Main Button Base - SystemColorButtonFaceColor
- Main Button Stroke - SystemColorButtonFaceColor
- Main Button Label - SystemColorButtonTextColor

### Button
![image](https://user-images.githubusercontent.com/13142665/111827666-64fab500-88a7-11eb-9942-d59f6fc9c897.png)

Needed changes:
Hover
- Button Base - SystemColorHighlightTextColor

Pressed
- Button Base - SystemColorHighlightTextColor
- Button Stroke -SystemColorHighlightTextColor

### ToggleButton
![image](https://user-images.githubusercontent.com/13142665/111827769-88bdfb00-88a7-11eb-9ec1-d3101ab59545.png)

Needed changes:
**ToggleButton (OFF)**
Hover
- Base Fill - SystemColorHighlightTextColor

Pressed
- Base Fill - SystemColorHighlightTextColor
- Base Stroke - SystemColorHighlightTextColor

**ToggleButton (ON)**
Hover
- Text label - SystemColorButtonFaceColor
- Base Fill - SystemColorButtonTextColor
- Base Stroke - SystemColorButtonTextColor

Pressed
- Base Fill - SystemColorHighlightTextColor
- Base Stroke - SystemColorHighlightTextColor

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/32153418)

**Comment by StephenLPeters** [comment]
@chingucoding want to take a look? :)

**Comment by chingucoding** [comment]
Sure thing!
