### ISSUE TITLE
Fix High Contrast color mappings for toggleable controls

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#4585]
**Describe the bug**
Related to #4584
The following controls don't have the most intuitive color mappings when they're drawn in High Contrast.
- CheckBox
- RadioButton
- ToggleSwitch

The current mapping may confuse users, especially if they customize the colors of their HC theme. We should correct these mappings, particularly for the new styles, but would not be amiss to apply the same fix to the older styles as well.

## Requested changes
When applying this custom HC theme
![image](https://user-images.githubusercontent.com/13142665/111827103-bc4c5580-88a6-11eb-96f3-a29a75fcfda3.png)
the controls should look like the following.

### CheckBox
![image](https://user-images.githubusercontent.com/13142665/111828809-13532a00-88a9-11eb-9270-f0e6d0d15fc1.png)

Needed changes:
**CheckBox (Unchecked)**
Rest
- Text label - SystemColorButtonTextColor
- Checkbox Fill - SystemColorButtonFaceColor
- Checkbox Stroke - SystemColorButtonTextColor

Hover
- Text label - SystemColorButtonTextColor
- Checkbox Fill - SystemColorHighlghtTextColor

Pressed
- Text label - SystemColorButtonTextColor

Disabled
- Checkbox Fill - SystemColorButtonFaceColor

**CheckBox (Checked)**
Rest
- Text label - SystemColorButtonTextColor

 Hover
- Text label - SystemColorButtonTextColor
- Checkbox Fill - SystemColorButtonTextColor
- Checkbox Stroke - SystemColorButtonTextColor
- Check mark - SystemColorButtonFaceColor

Pressed
- Text label - SystemColorButtonTextColor
- Checkbox Fill - SystemColorButtonFaceColor
- Checkbox Stroke - SystemColorButtonFaceColor
- Check mark - SystemColorButtonTextColor

### RadioButton
![image](https://user-images.githubusercontent.com/13142665/111828980-531a1180-88a9-11eb-9114-504adb5a830c.png)

Needed changes:
**RadioButton (Unchecked)**
Rest
- Base Fill - SystemColorButtonFaceColor

 Hover
- Base Fill- SystemColorHighlightTextColor
- Base Stroke- SystemColorHighlightColor

Pressed
- Base Fill- SystemColorHighlightTextColor
- Base Stroke - SystemColorHighlightTextColor

Disabled
- Base Fill - SystemColorButtonFaceColor

**RadioButton (checked)**
Hover
- Base Fill - SystemColorButtonFaceColor
- Base Stroke - SystemColorButtonTextColor
- Thumb base - SystemColorButtonTextColor

Pressed
- Base Fill - SystemColorButtonFaceColor
- Base Stroke - SystemColorButtonFaceColor
- Thumb base - SystemColorButtonTextColor

Disabled
- Base Fill - SystemColorButtonFaceColor

### ToggleSwitch
![image](https://user-images.githubusercontent.com/13142665/111829170-91afcc00-88a9-11eb-9dc7-8a2d5f73edd1.png)

Needed changes:
**Toggle switch (OFF)**
Rest
- Base Fill - SystemColorButtonFaceColor
 
Hover
- Base Fill- SystemColorHighlightTextColor
- Thumb base - SystemColorHighlightColor

Pressed
- Base Fill- SystemColorHighlightTextColor
- Thumb base - SystemColorHighlightColor

Disabled
- Base Fill - SystemColorButtonFaceColor

**Toggle switch (ON)**
 Hover
- Base Fill - SystemColorButtonFaceColor
- Base Stroke - SystemColorButtonTextColor
- Thumb base - SystemColorButtonTextColor

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/32153354)

**Comment by StephenLPeters** [comment]
@chingucoding interested in taking a look?

**Comment by chingucoding** [comment]
Sure thing.
