### ISSUE TITLE
WinUI Desktop .Net 6.0 won't build

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#4591]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinUI-Desktop-Net-60-wont-build/1373078)._

---
[regression] [worked-in:16.10.0 preview 1.0]
I use Visual Studio 16.10.0 Preview 1.0
I have a lot of App WinUI Desktop with . Net5.0 SDK 19041

I wanted to test these app's with .NET 6.0

I allways get an error :
APPX3217	SDK folder containing 'Windows.props' for 'Windows 10.0.18362.0' cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information.
i get the same error with 'Windows 10.0.19041.0'

Both 18362 and 19041 are installed see jpeg
[Visul Studio 2019 16.10.0.jpg] (https://aka.ms/dc/file?name=Ba91ccda1eb2f42e2ab876e7313b4bc55637515782859192926_Visul_Studio_2019_16.10.0.jpg&tid=a91ccda1eb2f42e2ab876e7313b4bc55637515782859192926)

---
#### Feedback Bot on 3/17/2021, 11:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 3/18/2021, 09:52 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Srdjan Jovčić [MSFT] on 3/18/2021, 10:14 PM: 

<p>Hi Fernand,</p>
<p>Unfortunately, I was not able to reproduce the issue you are describing. Would you be kind to provide more repro steps, or sample project/solution reproducing the issue?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Fernand Delavy on 3/19/2021, 01:38 AM: 

(private comment, text removed)
#### Fernand Delavy on 3/19/2021, 05:39 AM: 

(private comment, text removed)
#### Feedback Bot on 3/19/2021, 03:14 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by Fernand-Delavy** [comment]
I did send this to Microsoft, they moved my post here but deleted the comment, don't know why.
I repeat 

I create an app named Test WinUI Desktop with Visual Studio 2019 16.10.0 Previewn1.0 nothing modified

I choose 19041

At this time the app compile and run without problem
But the app run .net 5.0 as default !
I change the net to .NET 6.0
And i get error : 
APPX3217 SDK folder containing 'Windows.props' for 'Windows 10.0.18362.0' cannot be located
the same with :
APPX3217 SDK folder containing 'Windows.props' for 'Windows 10.0.19041.0' cannot be located

The zip of theapp attached
[Test.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6177113/Test.zip)
![Kits  18362 19041](https://user-images.githubusercontent.com/43344217/111899689-76ba9480-8a2e-11eb-8ec7-c2e12dff47fa.jpg)


I do something wrong or it is a bis bug ?

**Comment by huoyaoyuan** [comment]
https://github.com/microsoft/CsWinRT/issues/730
It shouldn't be ready yet.

**Comment by Rybasum** [comment]
I have the same issue. How are we supposed to try the new shiny .NET 6 if CsWinRT "shouldn't be ready yet"?

**Comment by StephenLPeters** [comment]
Yes, Winui does not yet support .net 6.

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI

**Comment by Daniellled** [comment]
I am also facing this issue. Yet I am able to compile and run the MAUI SamplesHelloWinUI3 application 

https://github.com/dotnet/net6-mobile-samples/tree/main/HelloWinUI3

But I am unable to create my own application.

**Comment by edwardskrod** [comment]
I hit this issue as well against 6.0.100-preview.5.21278.3

**Comment by tuggernuts** [comment]
I would like guidance as well for testing WinUI 3 apps against .net 6. Assuming not yet supported, will there be a preview or release soon of sdk to allow this?

**Comment by Marv51** [comment]
I believe this has been resolved? My app works. 

What is the official policy on .net 6 support?
Are the current release candidates already supported, or will it be officially supported as soon as it is released? Or will a update WinUI update add support at a later date?

**Comment by suchja** [comment]
@Marv51 How did you create a Winui3 app with .net 6? Doing everything on .NET 5 and then switching to .NET6 target?

And I fully agree that a general statement about when and how to use WinUI3 with .NET 6 is needed! Just searched the microsoft website for any information without success.

**Comment by VincentH-Net** [comment]
WinUI 3 Preview 3 Desktop on .NET 6 and C# 10 works for me in VS 2022 17.1 Preview 1 (on Windows 11).
I only needed to change the `5` to a `6` in `<TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>`
So far no problems.

However, I would like to see an issue / roadmap item to track when this is officially supported & documented, thx!

**Comment by suchja** [comment]
@VincentH-Net the addition `-windows10.0.19041.0` was important. Thank you! I tried it with only `net6.0` as shown in some articles, but that gave me a bunch of errors, because the `UI-Namespace` was not found. Which makes sense.

**Comment by micmor** [comment]
Changing   <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework> to  <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>  worked for me, too.
