### ISSUE TITLE
Scrolling a ListView with WebView2 inside

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4595]
**Describe the bug**
I have a list of posts, that I want to display in a ListView each post in it's separate WebView2. The WebView2 is sized so that the content never has scrollbars. The content consists of very simple html-styled paragraphs. This worked in WebView(1) in UWP perfectly. 
In WebView2 the content is not scrolling property: it glitches, stays inplace and then suddenly scrolls into place when the end of the list is reached. (See video below)

**Expected behavior**
The content should display and scroll as one would expect, with the surrounding content.

**Screenshots**

https://user-images.githubusercontent.com/471338/111863665-422ad800-895d-11eb-8bb6-55e9e5cd2e36.mp4

Each frame is a ListView Item, title "Update *" is XAML TextBlock. Below which is a WebView2.

**Version Info**
I'm on Project Reunion 0.5 Preview WinUI 3 Desktop. Windows 10 20H2 19042

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional Context**
I guess I could work around this by creating the layout entirely in HTML and using only one WebView2, however this is a port from UWP and this worked perfectly before.

**Comment by StephenLPeters** [comment]
@anawishnoff fyi

**Comment by codendone** [comment]
The cause of the scrolling issue is the same as #4596. If you don't need these WebView2 elements to be interactable at all, it should be possible to mark the WebView2 elements as IsHitTestVisible="false" to cause any pointer input to miss them and go to the parent element. If you do want interactivity, then the scroll chaining support mentioned in #4596 is the best solution.

**Comment by Marv51** [comment]
@codendone Thanks for the reply. I set IsHitTestVisible="false" on these WebView2s and the glitchiness and broken rendering persisted. It looks to me like a separate issue from #4596, especially now with IsHitTestVisible=false.


https://user-images.githubusercontent.com/471338/112106094-814f6800-8bad-11eb-87ae-cadf4f2e3d3f.mp4


It does fix the scrolling with the mousewheel described in #4596.

**Comment by codendone** [comment]
@Marv51 Wow, sorry, I thought this was just glitchy scrolling not broken rendering. I agree that is a separate big issue which we'll need to investigate.

**Comment by gabbybilka** [comment]
@codendone is this issue resolved? (task.ms/32224594) If so, can you close? Thanks!

**Comment by codendone** [comment]
Yes, the rendering issue here was fixed a long time ago.
