### ISSUE TITLE
Make ScrollAnchorProvider public in 2.1

### ISSUE THREAD

**Issue by jevansaks** [Microsoft/microsoft-ui-xaml#460]
We're shipping ItemsRepeater but in order to make it all work downlevel with ScrollViewer we need this compat helper. This issue is to be used to track that work.

### Prerelease readiness
- [ ] Dev: quality review + code review done
- [ ] Dev: test coverage added
- [ ] Dev: initial accessibility review done
- [ ] Dev: data metrics plan ready
- [x] PM: spec up to date
- [x] PM: feature ready for feedback
- [ ] PM: docs.microsoft.com updates ready
### Stable release readiness
- [x] Dev: feature previously shipped in a prerelease NuGet package
- [x] Dev: Azure CI tests passing
- [ ] Dev: data metrics ready
- [ ] Dev: accessibility review done
- [x] Dev: API review done
- [ ] Dev: IDL attribute switched from preview to public
- [x] PM: spec done
- [x] PM: glob/loc, privacy, security, license compliance ready
- [x] PM: customer validation done
- [ ] PM: docs.microsoft.com updated
- [x] PM: Xaml Controls Gallery updated

**Comment by chigy** [comment]
@micahl , I don't see documentation linked nor checked off. Does this work not require one?

**Comment by micahl** [comment]
@chigy, it's already done ([link](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.itemsrepeaterscrollhost)), just forgot to check the box which I've done now.  Thanks for following up!
