### ISSUE TITLE
in WebView2 where is BuildLocalStreamUri and NavigateToLocalStreamUri methods 

### ISSUE THREAD

**Issue by mobiletonster** [microsoft/microsoft-ui-xaml#4600]
In WebView  version 1 for UWP, you could navigation to a local stream and use a custom IUriToStreamResolver to direct the browser to load related assets from local files/resources. 

I don't see these types of interfaces in WebView2. Is there an alternate suggestion for how to accomplish these scenarios?

**Comment by StephenLPeters** [comment]
@anawishnoff FYI

**Comment by codendone** [comment]
#1967 mentions some possibilities here. Using SetVirtualHostNameToFolderMapping() can help with app local files, and the the [CoreWebView2.WebResourceRequested event](https://github.com/microsoft/microsoft-ui-xaml/issues/1967#issuecomment-801576819) can theoretically help with using streams.

**Comment by krschau** [comment]
I hope that @codendone's suggestion helped you implement what you needed. If there's still an issue, let me know and I can reopen this item. Thanks!

**Comment by camvm93** [comment]
@codendone @krschau 
Our app  (uwp) was zip all of content to save storage in device. We need to manual unzip resource in local device. 
In webview1, we used IUriToStreamResolver to detect and unzip content if needs.

But on webview2, I cannot find any alternative method to do it.
I tried to use SetVirtualHostNameToFolderMapping and used WebResourceRequested event. but rightnow, it didnot work.

**Comment by Panda-Sharp** [comment]
I have a similar situation of @camvm93 I asked a question with a min repro here
https://github.com/microsoft/microsoft-ui-xaml/discussions/7962

if we can make this work I think I'll be to make also the stream from a zip file works
