### ISSUE TITLE
NumberBox SpinButtons are not clipped correctly

### ISSUE THREAD

**Issue by simon-knuth** [microsoft/microsoft-ui-xaml#4601]
**Describe the bug**
The NumberBox SpinButtons' corners are not clipped correctly, which is especially noticeable in the "pressed" state. The issue persists across **all** states with varying intensity. This impacts the SpinButtons overlay, which is used with `SpinButtonPlacementMode="Compact"`.

**Steps to reproduce the bug**
Display a ComboBox with `SpinButtonPlacementMode="Compact"`. Example XAML:
```
<Page
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controlsxaml="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <controlsxaml:NumberBox HorizontalAlignment="Center" VerticalAlignment="Center" Width="200" SpinButtonPlacementMode="Compact"/>
    </Grid>
</Page>
```

**Expected behavior**
The corners should be clipped.

**Screenshots**
![NumberBox](https://user-images.githubusercontent.com/50021001/111912226-04b37100-8a69-11eb-995f-1d8eb34c001f.jpg)

**Version Info**
[Microsoft.UI.Xaml 2.5.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
I wonder if this is because these repeat buttons are being place in a popup. the popup has OverlayCornerRadius(4 on 2.5 and 8 on 2.6) while the repeat button has ControlCornerRaidus (2 on 2.5 and 4 on 2.6). Perhaps the shadows or maybe the decomp corner radius rendering code is getting confused because the content of the popup is "larger" than the popup itself?

@kmelmon and @gegao18 are there known issues in this space? do either of you know?

**Comment by StephenLPeters** [comment]
This is even more noticable on 2.6 where it looks like a shadows bug.

**Comment by teaP** [comment]
With the visual updates, the buttons are now inset in the flyout, so this issue no longer applies.
