### ISSUE TITLE
ListView:SelectionChanged | SelectionChangedEventArgs property OriginalSource is always null

### ISSUE THREAD

**Issue by bogdan-patraucean** [microsoft/microsoft-ui-xaml#4602]
**Description**
I'm using a ListView and I want to check the OriginalSource property of the SelectionChangedEventArgs to see where the event came from but it is always null.

**Steps to reproduce the bug**

1. Add a ListView
2. Bind it to a data source
3. Create the SelectionChanged event
4. Click on a ListViewItem to fire the event

**Expected behavior**
I would expect to see the OriginalSource property so I can make decisions based on it. For example I want to know if the event was fired by the user's click or because the selected item from the list was deleted.

**Info**
NuGet package version: WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease
Windows app type: Win32 (Desktop app)
Windows Build Number:  19043.867

**Other**
I checked both with Single and Multiple selection mode.

**Comment by StephenLPeters** [comment]
@bogdan-patraucean do you know if this is new to Project reunion/ preview 4 or does it also happen with system xaml?

**Comment by bogdan-patraucean** [comment]
@StephenLPeters I'm actually new to project reunion and this is my first project I do so I can't help you with that. Sorry :(

**Comment by bogdan-patraucean** [comment]
> @bogdan-patraucean do you know if this is new to Project reunion/ preview 4 or does it also happen with system xaml?

@StephenLPeters I'm actually new to project reunion and this is my first project I do so I can't help you with that. Sorry :(

**Comment by chingucoding** [comment]
"System XAML" refers to regular UWP apps, so Stephen was asking whether this behavior is also reproducable in a normal UWP app, not a WinUI 3/Project Reunion app. Hope that helps @bogdan-patraucean.

**Comment by ranjeshj** [comment]
@bogdan-patraucean I'm not sure OrginalSource is going to give you the information you are looking for. Since the ListView itself is raising the event, I'm guessing that there isnt another element to provide in the args. https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.routedeventargs.originalsource?view=winrt-19041#Windows_UI_Xaml_RoutedEventArgs_OriginalSource 

The selection events do not provide information on what casued the selection changed event. You will need to track that by adding handlers to specific events you care about. Could you provide more details on what you are trying to do ?

**Comment by bogdan-patraucean** [comment]
> "System XAML" refers to regular UWP apps, so Stephen was asking whether this behavior is also reproducable in a normal UWP app, not a WinUI 3/Project Reunion app. Hope that helps @bogdan-patraucean.

Yes, thanks for explaining. I tested this using a regular UWP app and the same thing is happening (OrignialSource is null).

**Comment by bogdan-patraucean** [comment]
> @bogdan-patraucean do you know if this is new to Project reunion/ preview 4 or does it also happen with system xaml?

 I tested this using a regular UWP app and the same thing is happening (OriginalSource is null).

**Comment by bogdan-patraucean** [comment]
> @bogdan-patraucean I'm not sure OrginalSource is going to give you the information you are looking for. Since the ListView itself is raising the event, I'm guessing that there isnt another element to provide in the args. https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.routedeventargs.originalsource?view=winrt-19041#Windows_UI_Xaml_RoutedEventArgs_OriginalSource
> 
> The selection events do not provide information on what casued the selection changed event. You will need to track that by adding handlers to specific events you care about. Could you provide more details on what you are trying to do ?

I added a search to my list, and once my list is modified via the search the already selected items are automatically removed, and the SelectionChanged event is triggered, I would like to know that the event was triggered by the List itself, and not by the user click so I can store the selected items and show them back selected once the list is repopulated with all it's items.

**Comment by bogdan-patraucean** [comment]
Since this does not received any update for almost a year, I'll close it tomorrow.

**Comment by bogdan-patraucean** [comment]
Closes due to inactivity.
