### ISSUE TITLE
GC does not collect DependencyObjects

### ISSUE THREAD

**Issue by AlexanderEgorov** [microsoft/microsoft-ui-xaml#4610]
**Describe the bug**
GC does not collect DependencyObjects:
[App2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6183449/App2.zip)

```
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
            refObj = new WeakReference(new MyDependencyObject());
        }
        WeakReference refObj;

        private void myButton_Click(object sender, RoutedEventArgs e) {
            GC.Collect();
            GC.GetTotalMemory(true);
            GC.Collect();
            myButton.Content = refObj.IsAlive.ToString(); //Always TRUE
        }
    }
```

**Steps to reproduce the bug**

1. Run the attached sample
2. Click on the 'Click Me' button

**Expected behavior**
The Button caption should be 'False'

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@Scottj1s I think there is a known issue with cswinrt memory leaks, is this that?
