### ISSUE TITLE
MakePri.exe is fragile and has chance to fail for certain xaml

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#4611]
**Describe the bug**

When investigating https://github.com/microsoft/microsoft-ui-xaml/issues/3672, I'm trying to narrow the problem, but I cannot even get a minimal repro. After a lot of tries, I realized that MakePri is very fragile and can produce different result during continious run.

**Steps to reproduce the bug**

Use the reproduction solution in attachment.
[Reunion0.5P.zip](https://github.com/microsoft/ProjectReunion/files/6149726/Reunion0.5P.zip)

1. Always run `git clean -xdf` with the solution unloaded in Visual Studio, to clean intermediate files. **These files can influence the result.**
2. Open the solution, switch to Release/x64, right click the WinExe project and invoke 'Build`.
3. Right click the wapproj to open it in developer PowerShell
4. Invoke `msbuild /t:Rebuild /p:Configuration=Release` for several times. It can success for the first invocation and then fails for subsequent ones.

I'm getting 6 failures among 27 runs for such simple repro. 
The issue only reproduces for Release. For 19041 SDK, the error message is 'PRI222: unspecified error occurs'. For 18362 SDK, the error message says duplicate entry for 'File/xxx/xxx.xbf'.
It seems that use of Windows Community Toolkit, x:Uid and x:Bind contributes to the fail rate. I was modifying ClassLibrary1/UserControl1 to observe it.
When the project grows, the failure rate comes very high. However, if it success for 2 runs, then it will likely to success for subsequent runs (without git clean).

*Now I'm really unable to investigate myself for such a random issue.*

**Version Info**

NuGet package version: 
[Microsoft.ProjectReunion 0.5.0-prerelease]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by alwu-msft** [comment]
@StephenLPeters This is internally tracked as 32191676.

**Comment by huoyaoyuan** [comment]
Still present in VS 16.10.4 with Reunion 0.8.1

**Comment by huoyaoyuan** [comment]
The issue no longer reproduces in Windows App SDK 1.0 Preview 3.
