### ISSUE TITLE
Unsmooth animation of blue pointer moving to selected items

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/microsoft-ui-xaml#4613]
**Describe the bug**
See my issue at https://github.com/microsoft/terminal/issues/9556

**Steps to reproduce the bug**
1. Open settings
2. Watch the left-panel of settings (containing Startupt, Interactions...)
3. Switch very quickly between the horizontal "tabs" e.g. click on appearance and right after it (don't wait for the window to update) click on Startup

**Expected behavior**
Blue "pointer" at the left indicating what "tab" of settings is selected should smoothly move.

**Screenshots**
Here is the "blue pointer" I am talking about (this screenshot was taken on Windows Terminal Preview)
![image](https://user-images.githubusercontent.com/64481347/112029311-66431080-8b39-11eb-89a8-eedb88ff95e7.png)

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@cl-ement05 can you please provide a video of what you are describing to make sure we are understanding?

**Comment by cl-ement05** [comment]
I reproduced the bug several times the bug here in Windows Term. Watch especially at 0:10 I made a slow-mo. I hope this helps
https://user-images.githubusercontent.com/64481347/112136090-ce900180-8bce-11eb-8f9e-168b336ad8c3.mp4

**Comment by chingucoding** [comment]
This is actually by design right now. If there already is an animation, the indicator just jumps to the final location. Not sure how you would animate it though if it's already inside the animation🤔

**Comment by cl-ement05** [comment]
> Not sure how you would animate it though if it's already inside the animation🤔
Well I imagine this indicator moving is like a car that can only drive forward or drive backward. So, just like a car, if the indicator is on its way to a position but I ask him to go somewhere else while it is moving, it should *slow down* until reaching 0 and then start going *backward*, speed up and go to the new location I asked for.

**Comment by chingucoding** [comment]
> Well I imagine this indicator moving is like a car that can only drive forward or drive backward. So, just like a car, if the indicator is on its way to a position but I ask him to go somewhere else while it is moving, it should slow down until reaching a speed of 0 and then start going backward, speed up and go to the new location I asked for.

Well the thing is that there are two animations, the v1 and the v2, so I'll cover them separately.

##### V1 Animation
This animation does not actually move the indicator, it expands it and then shrinks it. So the issue you have is the following:
Lets say you have items A,B,C,D, and E. You have selected element C and animation finished. Now you click on A. The animation starts, element expands on top of A,B, and C. Now you click on element E. What should the animation do? Expand so it covers elements D and E to? Or should it shrink to C first? Or shrink to A? These kind of problems might actually be the reason why it just jumps when in animation instead.

##### V2 Animation
With V2, the indicator does transition continously, instead it has a small fade out animation on the start element and a small fade in animation on the target element. In that case it could play the fade in animation on the different node, but what if it is already fading in in a different place? Let it completely fade in and than fade out or just fade out immediately instead? This case is probably easier to argue about than V1.
