### ISSUE TITLE
WinUI 2's XamlMetadataProvider provides incorrect UnderlyingType for System.Windows.Input.ICommand

### ISSUE THREAD

**Issue by RealTommyKlein** [microsoft/microsoft-ui-xaml#4614]
**Describe the bug**
WinUI 2's metadata provider, `Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider`, contains incorrect type information for `System.Windows.Input.ICommand` type which can cause crashes.

**Steps to reproduce the bug**

1. Create a new blank C# UWP app
2. Add a reference to the Microsoft.UI.Xaml/WinUI 2 NuGet package (and add `XamlControlsResources` to `App.xaml` as normal)
3. Add the following code to the app's constructor in `App.xaml.cs`:
```
        public App()
        {
            this.InitializeComponent();
            this.Suspending += OnSuspending;

            // Get the IXamlType for ICommand from WinUI 2's metadata provider, which is incorrectly created
            // with an invalid UnderlyingType property causing a crash when accessed
            var winuiXMP = new Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider();
            var winuiType = winuiXMP.GetXamlType("System.Windows.Input.ICommand");
            var winuiUnderlyingType = winuiType.UnderlyingType; //Crashes
        }
```

4. Run the app
5. The app will crash on the last line when attempting to access `winuiType.UnderlyingType`

In reality, this can occur in the following setup:
- A C# application uses a property/field of type `System.Windows.Input.ICommand` in markup
- The C# application references WinUI 2
- The C# application references a C# control library, and the control library does _not_ use `System.Windows.Input.ICommand` anywhere

**Expected behavior**
`winuiUnderlyingType.UnderlyingType` returns the `System.Type` corresponding to `System.Windows.Input.ICommand` (or maybe `winuiXMP.GetXamlType("System.Windows.Input.ICommand")` should return `null` - see the "Additional Context" section)

**Screenshots**

**Version Info**

NuGet package version: [Microsoft.UI.Xaml 2.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

The WinUI 2 metadata provider might need to provide type information for `Windows.UI.Xaml.Input.ICommand` instead of `System.Windows.Input.ICommand`, since the Windows.UI.Xaml version is what exists in native code where WinUI 2's metadata provider is written and should be projected to the System.Windows version.

**Comment by michael-hawker** [comment]
I'm wondering if this is why we've been having more trouble lately with our `ICommand` extension for `ListView` in the Toolkit. It seems to work under `Release` when shipped in the store, but not when debugging locally. We'll have to investigate, but there's definitely something going on with `ICommand` lately that's a big headache.

**Comment by michael-hawker** [comment]
@ranjeshj @StephenLPeters we're seeing issues with `ICommand` that we hadn't seen before when running in Debug: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/4039

It doesn't seem like an isolated incident either. Not sure if it's related to this or something else, but definitely something wonky going on in the SDK, WinUI, or maybe the [Behaviors package](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/4039#issuecomment-877811571).

Is this anything you folks are aware of as a known issue? It's pretty frustrating to have to build in release mode to use `ICommand` in certain cases.

**Comment by StephenLPeters** [comment]
It sounds like @RealTommyKlein understands the issue?  Is the fix simple enough that you can advise how to fix?

**Comment by RealTommyKlein** [comment]
Yes, I believe the solution under the `Additional Context` section could resolve it (WinUI 2's metadata provider has an `IXamlType` for `ICommand`, but its `IXamlType.FullName` property should be in the native `Windows.UI.Xaml.Input.ICommand` namespace instead of the managed `System.Windows.Input.ICommand` namespace).

**Comment by michael-hawker** [comment]
Thanks @RealTommyKlein, I was looking at another filing we had of a similar issue related to mixing in the Behaviors library as well [here](https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4022). However, that mentions it also occurring in release mode. (Which does seem to be an interesting potential overlap with this comment on our other issue [here](https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4039#issuecomment-877811571).)

Does that look to be caused by this as well or potentially something different? It'd be great if we could get a fix with the updated metadata provider in WinUI 2, as it has been causing a lot of issues since `ICommand` is so commonly used.

**Comment by RealTommyKlein** [comment]
@michael-hawker - it's definitely the same issue (the callstack contains `Windows.UI.Xaml.Markup.IXamlType.get_UnderlyingType`), and this bug would affect both Debug and Release builds.
