### ISSUE TITLE
DataGrid does not populate

### ISSUE THREAD

**Issue by canfucius** [microsoft/microsoft-ui-xaml#4616]
**Describe the bug**

DataGrid does not populate data

**Steps to reproduce the bug**

1. Add DataGrid to page.
2. Bind collection to DataGrid

**Expected behavior**

DataGrid should show data as it did in Preview 3

**Screenshots**

![DataGridError1](https://user-images.githubusercontent.com/7346824/112033227-35e47d80-8b0b-11eb-9b05-d16d4ec329d2.PNG)
![DataGridError2](https://user-images.githubusercontent.com/7346824/112033440-69270c80-8b0b-11eb-8b11-22ad457453d8.PNG)
![DataGridError3](https://user-images.githubusercontent.com/7346824/112033546-84921780-8b0b-11eb-89e0-ca5bfe9b7dab.PNG)
![DataGridError4](https://user-images.githubusercontent.com/7346824/112033676-ae4b3e80-8b0b-11eb-8795-207e66bca654.PNG)
![DataGridError5](https://user-images.githubusercontent.com/7346824/112033832-d5a20b80-8b0b-11eb-9c0b-bdb2d9d10520.PNG)
![DataGridError6](https://user-images.githubusercontent.com/7346824/112037845-2ae01c00-8b10-11eb-8011-f47f5ba016b5.PNG)

**Version Info**

Microsoft.ProjectReunion.WinUI
Desktop
Windows 10
Desktop

NuGet package version: 

Microsoft.ProjectReunion
Microsoft.ProjectReunion.Foundation
Microsoft.ProjectReunion.WinUI
Microsoft.Toolkit
Microsoft.Toolkit.Uwp
Microsoft.Toolkit.Uwp.UI
Microsoft.Toolkit.Uwp.UI.Controls
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This worked in Preview 3, but has been broken since Preview 4 and now 5.

**Comment by StephenLPeters** [comment]
@michael-hawker and @RBrid FYI

**Comment by FreddyD-GH** [comment]
@canfucius Have you checked if this is related to the "can't load default styles of custom controls" issue (https://github.com/microsoft/microsoft-ui-xaml/issues/4414)?  More detail and workarounds can be found in that issue and also in https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3295.

**Comment by canfucius** [comment]
I used the 
`  <ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.19041.13" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.19041.13" />
  </ItemGroup>`

solution and put it both my .csproj files.
