### ISSUE TITLE
ScrollViewer fails to arrange child element properly when using MaxWidth

### ISSUE THREAD

**Issue by billhenn** [microsoft/microsoft-ui-xaml#4619]
**Describe the bug**

We have a common usage scenario throughout our app where we have a `ScrollViewer` that contains a panel like a `StackPanel`.  To ensure readability, we put a `MaxWidth` on that panel to prevent its content from getting too wide on large monitors, and we want the panel centered within the `ScrollViewer` at its measured width.  The child elements of the panel are all measured controls, like TextBlocks, ItemsControls, etc. so we cannot set a fixed width on them.

Now the problem arises when the measured widths of those panel child elements don't exceed the `StackPanel.MaxWidth`.  In this scenario, the `ScrollViewer` positions the left edge of the panel to where it should be to center the panel if it was at its measured width.  But `ScrollViewer` incorrectly arranges the panel to its full `MaxWidth`, even though the measured width can be much less than that.  Because of this bug, everything arranges off-center and looks very bad.

**Steps to reproduce the bug**

Use this XAML to see the three scenarios that can happen:
```
<StackPanel Width="600">
    <TextBlock Margin="0,10,0,3" Text="This shows the StackPanel.MaxWidth issue when in a ScrollViewer... the left side of the TextBox shows up where it should, but the ScrollViewer still arranges to the panel's MaxWidth, even though it should arrange to the measured width of the text to properly center the content." TextWrapping="Wrap" />
    <Border BorderBrush="Red" BorderThickness="2">
        <ScrollViewer HorizontalScrollBarVisibility="Disabled" VerticalScrollBarVisibility="Auto">
            <StackPanel MaxWidth="450">
                <TextBox Text="This text is in a control that measures its own width" />
                <Button Content="This text is in a control that measures its own width" HorizontalAlignment="Stretch" />
            </StackPanel>
        </ScrollViewer>
    </Border>

    <TextBlock Margin="0,10,0,3" Text="Here is the same scenario as above but the content in the StackPanel measures wider than the MaxWidth.  Everything is centered properly." TextWrapping="Wrap" />
    <Border BorderBrush="Green" BorderThickness="2">
        <ScrollViewer HorizontalScrollBarVisibility="Disabled" VerticalScrollBarVisibility="Auto">
            <StackPanel MaxWidth="450">
                <TextBox Text="This text is in a control that measures its own width... the text content here is longer than the StackPanel.MaxWdith" />
                <Button Content="This text is in a control that measures its own width... the text content here is longer than the StackPanel.MaxWdith" HorizontalAlignment="Stretch" />
            </StackPanel>
        </ScrollViewer>
    </Border>

    <TextBlock Margin="0,10,0,3" Text="Or by using a fixed StackPanel.Width, everything is centered properly." TextWrapping="Wrap" />
    <Border BorderBrush="Green" BorderThickness="2">
        <ScrollViewer HorizontalScrollBarVisibility="Disabled" VerticalScrollBarVisibility="Auto">
            <StackPanel Width="450">
                <TextBox Text="This text is in a control that measures its own width" />
                <Button Content="This text is in a control that measures its own width" HorizontalAlignment="Stretch" />
            </StackPanel>
        </ScrollViewer>
    </Border>
</StackPanel>
```

**Expected behavior**

In the XAML above, the first scenario shows the bug.  The `TextBox` and `Button` should be center aligned, like the other two scenarios.  Instead, it correctly positions the nested `StackPanel` where it should, but incorrectly makes its width be the full `MaxWidth` instead of the measured width.  

The second scenario shows how child elements that measure more than the `MaxWidth` will arrange properly.

The third scenario shows how a fixed width will also arrange properly.

**Screenshots**

![image](https://user-images.githubusercontent.com/5760058/112047010-18bba900-8b23-11eb-9186-95b5723845f5.png)

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-preview4.210210.4 - Due to other bugs in 0.5, we can't test this ourselves in that version yet.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

We really need this one resolved since it affects hundreds of pages in the app we are porting.

**Comment by StephenLPeters** [comment]
@RBrid can you give this a read and see if something jumps out at you?

**Comment by RBrid** [comment]
@billhenn, does that work for you?
`<StackPanel MaxWidth="450" HorizontalAlignment="Center">`

![image](https://user-images.githubusercontent.com/36547063/112076668-17e14200-8b38-11eb-8447-e5fdacf846d3.png)

Thank you.

**Comment by billhenn** [comment]
@RBrid, thank you for the idea.  That does seem to work around the issue in some tests in our app.  I'll reply back if there is a scenario it doesn't help with.

That being said, is this still going to be a bug that is logged for fixing?  I don't believe the same scenario was an issue in WPF.

**Comment by RBrid** [comment]
Thank you @billhenn, given our current priorities with WinUI 2.6 & 3, the mitigation with the Center alignment above, and the fact that it does not repro with the new ScrollView control (still in preview mode), we are not planning to fix this in the old ScrollViewer. Here's what it looks like in the new ScrollView control:
![image](https://user-images.githubusercontent.com/36547063/112508886-30767580-8d4d-11eb-904d-4f04e0b083c9.png)

**Comment by RBrid** [comment]
Closing this issue since we have no plan to address this in a future release.
