### ISSUE TITLE
CompositionTarget.Rendering not always can be unsubscribed.

### ISSUE THREAD

**Issue by azchohfi** [microsoft/microsoft-ui-xaml#4621]
**Describe the bug**
CompositionTarget.Rendering -= Callback;
is supposed to unassign the method, but sometimes it doesn't.

**Steps to reproduce the bug**
The WCT uses this pattern in our TokenizingTextBox:
```
        public static Task<bool> ExecuteAfterCompositionRenderingAsync(Action action, TaskCreationOptions? options = null)
        {
....
            var taskCompletionSource = options.HasValue ? new TaskCompletionSource<bool>(options.Value)
                : new TaskCompletionSource<bool>();

            try
            {
                void Callback(object sender, object args)
                {
                    CompositionTarget.Rendering -= Callback;

                    action();

                    taskCompletionSource.SetResult(true);
                }

                CompositionTarget.Rendering += Callback;
            }
            catch (Exception e)
            {
                taskCompletionSource.SetException(e); // Note this can just sometimes be a wrong thread exception, see WinUI function notes.
            }

            return taskCompletionSource.Task;
....
        }
```
Opening the WCT sample app (the WinUI3 version) and clicking a few times to add an item from the TTB will eventually reproduce this.
We then get exceptions on taskCompletionSource.SetResult(true), since this is trying to complete the task more than once. I worked around this issue by switching to a TrySetResult, and only if successful we call the callback, but there will be performance and memory problems with this, since that no-op method will still be called at every single time this callback is called (every render...).
This method worked fine on UWP/XAML for a while now, but it intermittently fails to unassign the callback (but after the first time, it keeps calling that callback, even given the fact that we unsubscribe as the very first thing inside the callback).

**Expected behavior**
CompositionTarget.Rendering -= Callback
actually removed the method from the callback list, never being called again unless resubscribed.

**Version Info**
Reunion 0.5-Prerelease, but this is not a new regression, as this has been seem in previous previews.

NuGet package version: 
[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build               | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@azchohfi does this repro on both UWP and Desktop applications?

**Comment by azchohfi** [comment]
I did not test this on UWP, as the previews we are shipping of the WCT support only Desktop.

**Comment by StephenLPeters** [comment]
@Scottj1s my guess is this is a cswinrt issue.

**Comment by manodasanW** [comment]
This has been resolved by the recent event handler fixes from CsWinRT which were part of the Windows App SDK 0.8.2 update.  Tried out the above repro without the workaround and the issue doesn't seem to repro.
