### ISSUE TITLE
Pressing the down arrow key should navigate through suggestions in the AutoSuggestBox (when NavigationView is collapsed)

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#4622]
**Describe the bug**

**Steps to reproduce the bug**

1. Make the app smaller so that the NavigationView is collapsed
2. Press the search button in the NavigationView
3. Type "RichEditBox"
4. Press down arrow key

**Expected behavior**

RichEditBox suggestion would be focused on so user can press enter to navigate to the control's page

**Actual behavior**

Toggle theme button is focused instead

**Screenshots**

**Version Info**
- [x] App downloaded from Store 
    - If so, which version? 1.2.17.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3preview branch)

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by Poopooracoocoo** [comment]
@StephenLPeters @stmoy no updates on this?

**Comment by StephenLPeters** [comment]
Hey, I agree with you that the current behavior is really frustrating and this should be fixed, unfortunately it hasn't been prioritized yet.  I also understand you disagree with our prioritizations, we will get to this eventually.

**Comment by karenbtlai** [comment]
@Poopooracoocoo There actually is an internal bug opened that is scheduled and assigned to me already. Thanks for your feedback again.

**Comment by Poopooracoocoo** [comment]
> Hey, I agree with you that the current behavior is really frustrating and this should be fixed, unfortunately it hasn't been prioritized yet. I also understand you disagree with our prioritizations, we will get to this eventually.

ah i didn't think y'all understood that i disagreed! i keep seeing visual updates being proposed, created and then merged so it makes me a bit angry when some ancient bugs and features are being left to rot.

good to see it's being tracked internally.
