### ISSUE TITLE
Grid view / Textbox popup: Textbox background is transparent

### ISSUE THREAD

**Issue by XPoppyX** [microsoft/microsoft-ui-xaml#4626]
**Describe the bug**
In development uwp file explorer:

In Grid view when wanting to rename an item, a textbox pops up, the problem is that the textbox background is transparent
This happened after updating to Microsoft.UI.Xaml 2.6.0-prerelease.210315002

**Steps to reproduce the bug**
1 - Make a textbox pop over an item in grid view
2 - You will see that the textbox has no background

**Expected behavior**
It should have a solid background

![Captura de pantalla 2021-03-22 2053022](https://user-images.githubusercontent.com/61259627/112080022-f98f3c80-8b5f-11eb-9f90-870ced8a1384.png)

**Screenshots**

The item name is behind the textbox, and it is visible

![Captura de pantalla 2021-03-22 205302](https://user-images.githubusercontent.com/61259627/112076990-43752400-8b5a-11eb-863c-159f3856133e.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.0-prerelease.210315002

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@XPoppyX this looks by design. Can you put the textbox in a flyout ?
@YuliKl as FYI

**Comment by yaichenbaum** [comment]
@ranjeshj This isn't expected, the TextBox is supposed to have a solid background.

**Comment by chingucoding** [comment]
Looking at the release notes for WinUI 2.4 (https://docs.microsoft.com/en-us/windows/apps/winui/winui2/release-notes/winui-2.4) in the unfocused state, the background of a TextBox has always been transparent.

**Comment by mdtauk** [comment]
> Looking at the release notes for WinUI 2.4 (https://docs.microsoft.com/en-us/windows/apps/winui/winui2/release-notes/winui-2.4) in the unfocused state, the background of a TextBox has always been transparent.

Has been the case back to Win8 Xaml IIRC.

Win32 and WPF kept their controls fully opaque, so moving from that to WinUI will brush up against these design differences

**Comment by yaichenbaum** [comment]
@XPoppyX Is the text box focused when you have this issue?

**Comment by mdtauk** [comment]
If this is for the focused state, then I think it could be an issue with the **Control Fill Color Input Active** colour
```Xaml
<Color x:Key="ControlFillColorInputActive">#B31E1E1E</Color>
```
this has an opacity of 70.19%

**Comment by XPoppyX** [comment]
@yaichenbaum The textbox closes when it loses focus, so yes

**Comment by YuliKl** [comment]
> @ranjeshj This isn't expected, the TextBox is supposed to have a solid background.

Styles change. Looking at your screenshots, you're using the new WinUI 2.6 style. The transparency is by design.

Are you not able to put the TextBox into a Flyout?

**Comment by yaichenbaum** [comment]
@YuliKl I guess we can hardcode a solid color, I find it interesting that the styles changed. Overlaying text boxes on top of text blocks is something we are doing in a number of areas. A flyout doesn't really line up with our UX.

**Comment by mdtauk** [comment]
> @YuliKl I guess we can hardcode a solid color, I find it interesting that the styles changed. Overlaying text boxes on top of text blocks is something we are doing in a number of areas. A flyout doesn't really line up with our UX.

Then you should override the ThemeResource for the dark mode to use a solid colour, but it may be worth taking a look @YuliKl as the ControlFillColorInputActive resource for Light theme is 100% opaque, but the change for dark mode, may be a pain point for others.

**Comment by StephenLPeters** [comment]
It does seem odd that one theme is opaque and another is not.. @YuliKl ?

**Comment by mdtauk** [comment]
> It does seem odd that one theme is opaque and another is not.. @YuliKl ?

I presume there is an attempt to not allow Dark Theme resources to dip down into pure black colours.  But at least to my perusing of the ThemeResources that are being added, the darkest opaque colour in the colour ramp seems to be ``#131313``  Which could be used at 100% for the Focused TextBox?

![image](https://user-images.githubusercontent.com/7389110/112398135-625eec00-8cfb-11eb-9bd8-88bf1d43e4b2.png)
![image](https://user-images.githubusercontent.com/7389110/112398157-70147180-8cfb-11eb-9dc8-d7d0c5c9604c.png)
![image](https://user-images.githubusercontent.com/7389110/112398171-799dd980-8cfb-11eb-8d00-64a2da0069cc.png)

**Comment by YuliKl** [comment]
@XPoppyX I've confirmed with Microsoft designers that some transparency is indeed by design and the new colors fit with our overall color story. There's a difference in opacity between light and dark theme because we wanted to ensure that the background looks pure white in light theme.
