### ISSUE TITLE
NavigationView's default min width is too wide to align horizontally to right.

### ISSUE THREAD

**Issue by gaoyulei1983** [microsoft/microsoft-ui-xaml#4627]
**Describe the bug**
I want to put two font Icons on NavigationView and hide the setting button and align it to the right horizontally. However, it can't be aligned to right because its default min width is 635px. I hope you can reduce its default min width.

**Steps to reproduce the bug**
I add the code below in my UWP program, and want to show two font Icon button on the NavigationView. I am using PaneDisplayMode="Top" and want to make it align horizontally to right. 
  ```
<Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:animations="using:Microsoft.Toolkit.Uwp.UI.Animations"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:App1"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <muxc:NavigationView
            HorizontalAlignment="Right"
            IsBackButtonVisible="Collapsed"
            IsSettingsVisible="False"
            PaneDisplayMode="Top">
            <muxc:NavigationView.MenuItems>
                <muxc:NavigationViewItem>
                    <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xEA37;" />
                </muxc:NavigationViewItem>
                <muxc:NavigationViewItem IsSelected="True">
                    <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE74C;" />
                </muxc:NavigationViewItem>
            </muxc:NavigationView.MenuItems>
        </muxc:NavigationView>
    </Grid>
</Page>
```

However, you can see the screen shot here, its width is too wide, and seems not to be aligned to right.
![image](https://user-images.githubusercontent.com/80909481/112145703-a677c100-8c15-11eb-96c7-5cf1667c3421.png)

I also try to set  Width="100" for muxc:NavigationView but it can't resolve my problem, because the More button will be shown. I don't want to show More button. 
![image](https://user-images.githubusercontent.com/80909481/112144067-abd40c00-8c13-11eb-81ab-6573a063123a.png)

I also try to set Width="145" which is the min width that doesn't show the More button. It is still not aligned to the right. 
However, I don't want to set Width for it because the width will change when I change text scale in the windows settings page as below. I also try to set MinWidth = "0" for it, but it doesn't work.
![image](https://user-images.githubusercontent.com/80909481/112144595-65cb7800-8c14-11eb-8d05-7e39493e56cb.png)

**Expected behavior**
Hope the two Navigation View font icon align to the right top. 

**Screenshots**
I hope it can show like below that the Navigation View can align to the right when PaneDisplayMode="Top"
![image](https://user-images.githubusercontent.com/80909481/112144722-87c4fa80-8c14-11eb-81e7-4451d69a463d.png)

**Comment by ranjeshj** [comment]
@gaoyulei1983 Can you provide details on what you are trying to achieve. I'm curious if NavigationView is the correct control for this. Would CommandBar serve better for this ? @YuliKl as FYI

**Comment by gaoyulei1983** [comment]
@ranjeshj I use it for the tab header to switch tab page. In WPF, I usually use Tabcontrol. Now in UWP I hope it can be placed to right and top of the page. I also considered to use Pivot, but I was told it will be deprecated in WinUI next version, and CommandBar doesn't support to switch between its children items naturally, I need to add event to do so. It is not as good as NavigationView.

**Comment by YuliKl** [comment]
@gaoyulei1983 Thank you for the additional information. As you have noticed, NavigationView was not designed to have its items be right aligned, but you may be able to achieve your scenario by placing your NavigationViewItems into the `FooterMenuItems` list instead of `MenuItems`. 

A word of caution: Based on your row definitions, you may be misunderstanding NavigationView's behavior. As described in the [NavigationView design docs](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview), the control is both headers and content. NavigationView will attempt to take up as much available height as possible, so your second row will most likely have a height of 0. For similar reasons, I would not recommend a very narrow NavigationView to avoid showing just a narrow strip as the control's Content.

Lastly, regarding this comment:
> I don't want to set Width for it because the width will change when I change text scale in the windows settings page as below.

Icons are not effected by that setting, it only changes the size of text.

Please close this issue if FooterMenuItems does what you expect. What you're reporting isn't actually a bug, and FooterMenuItems is the feature we added to support this scenario.

**Comment by mdtauk** [comment]
It looks like you want to use a customised Pivot, but as that control is being deprecated, you may have to wait for progress with this proposal #2310 and then tie that to a frame for navigating pages

**Comment by YuliKl** [comment]
> It looks like you want to use a customised Pivot, but as that control is being deprecated, you may have to wait for progress with this proposal #2310 and then tie that to a frame for navigating pages

Or just use NavigationView. No need to wait for a new control :)

**Comment by mdtauk** [comment]
> > It looks like you want to use a customised Pivot, but as that control is being deprecated, you may have to wait for progress with this proposal #2310 and then tie that to a frame for navigating pages
> 
> Or just use NavigationView. No need to wait for a new control :)

Sure if the person is happy to change his layout to match what the NavigationView's layout :)

**Comment by gaoyulei1983** [comment]
I will give you feedback tomorrow.

**Comment by mdtauk** [comment]
NavigationView is designed to take up the whole window space.  I think it supports LtR and RtL document flow, but with LtR the sidebar is on the left or the top orientation is at the top, and designed to be full width.

The control acts as a frame for handling page navigation IIRC.

![image](https://user-images.githubusercontent.com/7389110/112293936-95b56280-8c8a-11eb-9181-ac6985a3d88f.png)

![image](https://user-images.githubusercontent.com/7389110/112293947-99e18000-8c8a-11eb-94fc-ac12191cf836.png)

**Comment by mdtauk** [comment]
> NavigationView is designed to take up the whole window space. I think it supports LtR and RtL document flow, but with LtR the sidebar is on the left or the top orientation is at the top, and designed to be full width.
> 
> The control acts as a frame for handling page navigation IIRC.
> 
> ![image](https://user-images.githubusercontent.com/7389110/112293936-95b56280-8c8a-11eb-9181-ac6985a3d88f.png)
> 
> ![image](https://user-images.githubusercontent.com/7389110/112293947-99e18000-8c8a-11eb-94fc-ac12191cf836.png)

---

You should try populating the Footer Items area

![image](https://user-images.githubusercontent.com/7389110/112297482-dcf12280-8c8d-11eb-92e4-4fcbc2ddde81.png)

```Xaml
        <mux:NavigationView PaneDisplayMode="Top" IsSettingsVisible="False" IsBackButtonVisible="Collapsed">

            <mux:NavigationView.FooterMenuItems>
                <mux:NavigationViewItem IsSelected="True">
                    <mux:NavigationViewItem.Icon>
                        <FontIcon Glyph="&#xEA37;" />
                    </mux:NavigationViewItem.Icon>
                </mux:NavigationViewItem>

                <mux:NavigationViewItem>
                    <mux:NavigationViewItem.Icon>
                        <FontIcon Glyph="&#xE74C;" />
                    </mux:NavigationViewItem.Icon>
                </mux:NavigationViewItem>
            </mux:NavigationView.FooterMenuItems>
            
        </mux:NavigationView>
 ```

**Comment by gaoyulei1983** [comment]
Yes, I took a try about the FooterMenuItems. It works. I will close tomorrow, because I need to confirm with my team member.

**Comment by gaoyulei1983** [comment]
There is still an bug, although I use FooterMenuItems. I put a button besides the navigationView, and the button can't align to the right besides the two font Icons. The navigationView's default width is still too wide.
![image](https://user-images.githubusercontent.com/80909481/112461618-119ed000-8d9b-11eb-8785-6ce61c60a948.png)


> <Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <StackPanel HorizontalAlignment="Right" Orientation="Horizontal">
            <Button HorizontalAlignment="Right" />
            <muxc:NavigationView
                HorizontalAlignment="Right"
                IsBackButtonVisible="Collapsed"
                IsSettingsVisible="False"
                PaneDisplayMode="Top">
                <muxc:NavigationView.FooterMenuItems>
                    <muxc:NavigationViewItem>
                        <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xEA37;" />
                    </muxc:NavigationViewItem>
                    <muxc:NavigationViewItem IsSelected="True">
                        <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE74C;" />
                    </muxc:NavigationViewItem>
                </muxc:NavigationView.FooterMenuItems>
            </muxc:NavigationView>
        </StackPanel>
    </Grid>
</Page>

**Comment by YuliKl** [comment]
Chatted with @gaoyulei1983 offline, and NavigationView is not the correct control to use in this scenario. Closing issue.

**Comment by gaoyulei1983** [comment]
@YuliKl you haven't told me what's the correct control I should use.

**Comment by gaoyulei1983** [comment]
Dear Martin,
              You haven't told me what's the correct control I should use. The FootMenuItems property which you told me is also not correct.
