### ISSUE TITLE
Question: WinUI 2.6 release timeframe?

### ISSUE THREAD

**Issue by niels9001** [microsoft/microsoft-ui-xaml#4630]
Is there a date already when we can expect WinUI 2.6 to roll out (outside of preview) to be used with UWP so we can adopt all the new styling?

The roadmap.md still mentions 2.5 ("to be released in 2020").. would be good to update that section and to mention the release plan for 2.6 :).

**Comment by ranjeshj** [comment]
@anawishnoff @chingucoding we should update the roadmap to update 2.5. @niels9001 don't have a date to share yet.

**Comment by anawishnoff** [comment]
@ranjeshj yup, I'm planning on pushing updates soon
