### ISSUE TITLE
CommamdBar issue (WinUI 3 Desktop)

### ISSUE THREAD

**Issue by itsWindows10** [microsoft/microsoft-ui-xaml#4633]
**Describe the bug**
The CommandBar background is nearly 100% transparent

**Steps to reproduce the bug**
1- Put a TextBlock on your WinUI 3 layout
2- Compile the app
3- Type a text and right click on it, you will find a weird menu with copy and paste options but with a transparent background

**Expected behavior**
Expected: Actual CommandBar with a background
Actual: Transparent CommandBar

**Screenshots**

**Version Info**
Windows app type: Win32
WinUI version: 3 (Project Reunion 0.5 preview)

NuGet package version: 

[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**

**Comment by mdtauk** [comment]
This is by design, as a background appears when you press the "more" button.  You should probably place the control into a panel which has a background set on it already

**Comment by ranjeshj** [comment]
This is the same issue as #4579
