### ISSUE TITLE
ProgressRing disappears within a CommandBar when items go to the overflow list and back again

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#4636]
**Describe the bug**
If the width of the window is changed and items are displayed in the overflow list of the CommandBar, this will cause the ProgressRing to disappear when the width of the window is increased again and the items are displayed in the normal list again.

Example XAML
```xaml
    <CommandBar OverflowButtonVisibility="Auto">
        <CommandBar.PrimaryCommands>
            <AppBarElementContainer>
                <Grid>
                    <muxc:ProgressRing
                                Value="23" 
                                Maximum="30" 
                                Width="40"
                                Height="40"
                                IsIndeterminate="False"/>
                    <TextBlock 
                                Opacity="0.6"
                                Text="23"
                                FontSize="12"
                                VerticalAlignment="Center" 
                                HorizontalAlignment="Center"/>
                </Grid>
            </AppBarElementContainer>
            <AppBarButton Icon="Accept"/>
            <AppBarButton Icon="Add"/>
            <AppBarButton Icon="Account"/>
            <AppBarButton Icon="DockBottom"/>
            <AppBarButton Icon="DisconnectDrive"/>
            <AppBarButton Icon="Favorite"/>
            <AppBarButton Icon="Folder"/>
        </CommandBar.PrimaryCommands>
    </CommandBar>
```

**Steps to reproduce the bug**

1. Copy the example code to your app
2. Change the width of the app to min and back again
3. see the error

**Expected behavior**

**Screenshots**
enough width
![grafik](https://user-images.githubusercontent.com/10946850/112228917-53603700-8c32-11eb-9ed1-4ee356f962d0.png)

overflow list
![grafik](https://user-images.githubusercontent.com/10946850/112228967-670b9d80-8c32-11eb-87ba-ead25d42a7df.png)

all items in the normal list again
![grafik](https://user-images.githubusercontent.com/10946850/112228993-768ae680-8c32-11eb-84ea-7b67aabd4964.png)

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.6.0-prerelease.210315002

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
 | Yes | Yes  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
Looks like AppBarElementContainer might be moving its children based on overflow which is messing with ProgressRing rendering.
