### ISSUE TITLE
Accessing Application.Resources in Application constructor throws COMException

### ISSUE THREAD

**Issue by billhenn** [microsoft/microsoft-ui-xaml#4639]
**Describe the bug**

We are a commercial UI control development company and have been working on a theming system for WinUI.  Part of this theming system is that we need to inject a `ResourceDictionary` into the `Application.Resources`.  

In WPF, customers almost always access and use our theming system in the application's constructor.  However accessing the `Application.Resources` getter in WinUI's application constructor throws a `COMException`.  An exception when trying to do so is confusing and will make our theming system look bad when customers try and use our themes in their own apps, only to find it crashes due to us accessing the `Application.Resources` within our code.

Sure we can write documentation about NOT executing any theme-related stuff in the application constructor and only in OnLaunched, but you know how much people read documentation.  It seems like this is a definite bug and there should be no problem with accessing `Application.Resources` in the constructor.

**Steps to reproduce the bug**

Use this Application constructor in a WinUI app project:
```
public App() {
	this.InitializeComponent();
	this.Suspending += OnSuspending;

	var resources = this.Resources;  // Triggers COMException
}
```

That code throws:
```
System.Runtime.InteropServices.COMException
  HResult=0x8000FFFF
  Message=Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplication.global::Microsoft.UI.Xaml.IApplication.get_Resources()
   at Microsoft.UI.Xaml.Application.get_Resources()
   at WinUITestApp.App..ctor() in S:\Code\Test\WinUITestApp\WinUITestApp\App.xaml.cs:line 35
   at WinUITestApp.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) in S:\Code\Test\WinUITestApp\WinUITestApp\obj\x86\Debug\net5.0-windows10.0.18362.0\App.g.i.cs:line 29
   at ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(ApplicationInitializationCallback invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr p)
```

**Expected behavior**

We should be able to access the `Application.Resources` in the application's constructor without any issues.  

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-preview4.210210.4

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@chrisglein and @MikeHillberg FYI

**Comment by MikeHillberg** [comment]
Agreed this is a bug. The Application constructor is getting called before it's internally fully initialized, and is getting confused in the property getter.
