### ISSUE TITLE
RadioButtons does not select first item when tabbing into a group that has no checked items set

### ISSUE THREAD

**Issue by kikisaints** [microsoft/microsoft-ui-xaml#464]
**Describe the bug**
When using the RadioButtons container control with some items set inside it, but no SelectedIndex has been set and I tab into the group keyboard correctly puts focus on the first item but does not select it. This in turn causes the narrator to not read out the full n of N as it should.

Once I navigate within the list, selection is set with focus and everything's good.

**Steps to reproduce the bug**
- Create a blank app and set up a RadioButtons group control with no specified items as selected, and an item above it to allow for easy navigating into and out of the container:
```xaml
<Button Content="Button"/>
<muxc:RadioButtons Header="App Mode">
    <x:String>Item 1</x:String>
    <x:String>Item 2</x:String>
    <x:String>Item 3</x:String>
    <x:String>Item 4</x:String>
</muxc:RadioButtons>
```
- Tab to Button, and then tab again to put focus on the first item in the RadioButtons list
- Notice that although Item 1 has keyboard focus, selection will not be set until navigation within the list occurs

**Expected behavior**
- Tabbing into the RadioButtons list where no items have been selected yet, should consequently  select the item that has focus

**Screenshots**
![RBGroupKeyboardBug](https://user-images.githubusercontent.com/6964369/54769659-df13d880-4bbe-11e9-916b-75dd131fb369.gif)

**Version Info**
Win UI 2.1 Preview

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18855)                   | Yes  |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Great bug. Even greater is this gif. How did you make it? :)

**Comment by jevansaks** [comment]
@chigy @kikisaints if there's an easy way for people to make gifs like this, we should doc it somewhere and put it in the bug template. Can you share how you made it?

**Comment by kikisaints** [comment]
> @chigy @kikisaints if there's an easy way for people to make gifs like this, we should doc it somewhere and put it in the bug template. Can you share how you made it?

For me, it requires Photoshop - but once you have that, it's relatively easy to make.

**Comment by chigy** [comment]
@kikisaints @jevansaks , it is so fanny but we just created gif for one of our docs. You might want to search for gif creation tools on store. There are multiple free apps out there.

**Comment by chrisglein** [comment]
> @kikisaints @jevansaks , it is so funny but we just created gif for one of our docs. You might want to search for gif creation tools on store. There are multiple free apps out there.

But just imagine if it was built into the Snipping Tool or the Game Bar...

**Comment by chigy** [comment]
@chrisglein only if they had Git Repo where we can make requests. :)

**Comment by jevansaks** [comment]
> @chrisglein Chris Glein FTE only if they had Git Repo where we can make requests. :)

Generally the app teams want feedback and upvotes via Feedback Hub.

**Comment by kikisaints** [comment]
This is no longer the desired behavior. Closing.

**Comment by chigy** [comment]
@kikisaints , what is the desired behavior then?
