### ISSUE TITLE
TextBox InputValidationKind="Inline" not properly aligned

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#4640]
**Describe the bug**

When applying InputValidationKind="Inline" on a TextBox, the error message is right-aligned and cut off

**Steps to reproduce the bug**

Xaml:
`<TextBox InputValidationKind="Inline" Header="Test" Text="{x:Bind ViewModel.Test1, Mode=TwoWay}" HorizontalAlignment="Left" MaxWidth="200" />
`

ViewModel property:
```
[Required]
[EmailAddress(ErrorMessage = "Invalid email address")]
public string Test1 
{ 
    get => _Test1; 
    set { SetField(ref _Test1, value); Validate(value); }
}

```

Implement INotifyDataErrorInfo on ViewModel

**Expected behavior**

Left aligned error text

**Screenshots**

![image](https://user-images.githubusercontent.com/9586533/112338004-ad391f00-8c7b-11eb-9d99-17a0a6cbbfa3.png)

**Version Info**

NuGet package version: 

![image](https://user-images.githubusercontent.com/9586533/112338595-28023a00-8c7c-11eb-8ce8-ede96178b229.png)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

InputValidation ErrorTemplate option is missing for customization

**Comment by StephenLPeters** [comment]
I was actually under the impression that input validation wasn't supported in winui3, but it seems to be working albeit with this bug.  @MikeHillberg @Austin-Lamb @ryandemopoulos

**Comment by mdtauk** [comment]
> I was actually under the impression that input validation wasn't supported in winui3, but it seems to be working albeit with this bug. @MikeHillberg @Austin-Lamb @ryandemopoulos

I think there may be limited support at first, with fuller support post 3.0 release

**Comment by MikeHillberg** [comment]
Yes, it's still in preview, not in release yet.

**Comment by omnilogix** [comment]
I updated to the 0.5 official release.   The InputValidationXXXX properties have been removed, so I'll close this for now

**Comment by StephenLPeters** [comment]
@omnilogix the input validation api's are preview, so they are not included in release builds, only prerelease. hence why they are not in the 0.5 official release.

**Comment by omnilogix** [comment]
Any progress on this item?

**Comment by michael-hawker** [comment]
Tied to Parent Issue: https://github.com/microsoft/microsoft-ui-xaml/issues/179

**Comment by weitzhandler** [comment]
are we ever gonna live to see official input validation support in WinUI?
