### ISSUE TITLE
Handwriting view not working in dark theme

### ISSUE THREAD

**Issue by BreeceW** [microsoft/microsoft-ui-xaml#4644]
**Describe the bug**
The handwriting view no longer has a dark mode in WinUI 2.6, and the hover state of the buttons on it is definitely wrong.

**Steps to reproduce the bug**
1. In dark mode, click on a text box with a pen
2. The handwriting view appears, but it is light gray
3. Expand the field with the chevron
4. Hover over the buttons on the right with the pen (they turn invisible)

**Expected behavior**
The handwriting view used to be black, so in accordance with the new background, I would expect it to be dark gray. Also, though not a bug, it looks like those icons on the side haven’t gotten new icons like many other controls.

**Screenshots**
![The handwriting view in dark mode on WinUI 2.6](https://user-images.githubusercontent.com/18747724/112375802-193a7800-8cba-11eb-9838-cb22722095d8.gif)

**Version Info**

NuGet package version: 
2.6.0-prerelease.210315002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@ranjeshj FYI and @viveksharmadev do you know about this surface? is it related to the ink toolbar?

**Comment by BreeceW** [comment]
I have tried this again on the WinUI 2.7.0 release (with both versions 1 and 2 of control resources), and it seems to be fixed now, so I am closing this issue.
![The handwriting view in WinUI 2.7.0 on Windows 11 showing the word “fixed”](https://user-images.githubusercontent.com/18747724/134841449-46d565fe-c4b0-4dbf-b95b-1d77d7432399.png)
