### ISSUE TITLE
Pivot can still be loaded thru XamlReader

### ISSUE THREAD

**Issue by azchohfi** [microsoft/microsoft-ui-xaml#4645]
Pivot was supposed to be removed in WinUI3 with ProjectReunion 0.5-Prerelease.
If you use it in a Xaml file, it really won't work. Still, if you load it dynamically thru XamlReader, it is loading, and it shouldn't.

**Steps to reproduce the bug**
1. Create a file new project
2. Put this Xaml in your MainWindow,xaml:
```xml
    <Grid x:Name="MainGrid">
```
2. Put this C# in your MainWindow.Xaml.cs, inside the ctor, after InitializeComponent():
```cs
var grid = XamlReader.Load(@"<Grid xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation""
      xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml""
      xmlns:mc=""http://schemas.openxmlformats.org/markup-compatibility/2006"">
        <Pivot>
            <PivotItem Header=""PivotItem1"">
                <Border Background=""Red"" />
            </PivotItem>
            <PivotItem Header=""PivotItem2"">
                <Border Background=""Blue""/>
            </PivotItem>
        </Pivot>
    </Grid>") as Grid;
MainGrid.Children.Add(grid);
```

**Expected behavior**
This should throw an exception, but it is loading the type just fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/527713/112383691-b2619280-8caa-11eb-8170-1f74848897c5.png)

**Version Info**
0.5.0-Prerelease (WinUI Desktop)

NuGet package version: 
[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by WamWooWam** [comment]
just.... wow

**Comment by codendone** [comment]
Pivot was restored as an available control, so this issue no longer applies.
