### ISSUE TITLE
System.InvalidCastException: 'Specified cast is not valid' (when reusing the same UI element and changing the datacontext)

### ISSUE THREAD

**Issue by neelakandan-kannan** [microsoft/microsoft-ui-xaml#4654]
**Describe the bug**
System.InvalidCastException: 'Specified case is not valid' exception occurred when assigning the same binding for different controls.
This issue is not occurring on initial loading. As per my custom control, i am reusing the controls on scrolling. So, i am changing the binding and DataContext on scrolling. 

_**Please note that this is not occurring in WinUI UWP. Its occurring only in WinUI Desktop.**_

Please let me know if this is known issue in WinUI Desktop. Also, this is not occurring only for TextBlock. This is occurring for CheckBox binding too. So, i am suspecting binding is not properly working when binding programmatically.

**Steps to reproduce the bug**
I can't provide the simple example to reproduce this issue. Because, i can't reproduce it in simple sample. 

**Expected behavior**
Exception should not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/32380788/112512334-49b50b80-8db9-11eb-92fd-8ee052ab3557.png)

**Version Info**
Windows 10 20H2

NuGet package version: 
Microsoft.ProjectReunion" Version="0.5.0-prerelease
Microsoft.ProjectReunion.Foundation
Microsoft.ProjectReunion.WinUI" Version="0.5.0-prerelease"

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by chrisglein** [comment]
> I can't provide the simple example to reproduce this issue. Because, i can't reproduce it in simple sample.

Appreciate you may not be able to share everything, but can you share more? A cast exception should tell you what it was trying to cast to and what the type/instance was. Also a stack would be helpful so we know what part of the code was failing on this cast. As is there's not enough to go on here.

**Comment by NeelakandanKannan** [comment]
Hi @chrisglein ,

Thanks for your update.

The following callstack is getting when error is thrown,

   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElement.global::Microsoft.UI.Xaml.IFrameworkElement.SetBinding(DependencyProperty dp, BindingBase binding)

The UI element's datacontext is,

Employee class which has following properties,
* Name
* ID
* Designation

And, binding's property path is **Name**. Please make sure that same binding is working fine on loading. As i mentioned, the error is occurred when reusing the same UI element and changing the datacontext on vertical scrolling. 

I can understand that It would be helpful for you if i provide the simple sample. But, i can't reproduce it.

**Comment by NeelakandanKannan** [comment]
Hi @chrisglein ,

Is there any update regarding this?

**Comment by NeelakandanKannan** [comment]
Hi @chrisglein ,

Is there any update on this?

**Comment by chrisglein** [comment]
No updates. As is we would need to engineer a repro to try to reproduce the same state. Which as you've stated you didn't have luck with.

Unfortunate that the exception doesn't contain the to/from types for the cast. In C# I generally expect something more like this:
```
  | Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Unable to cast object of type 'System.String' to type 'System.Int32'."} | System.InvalidCastException
  | Message | "Unable to cast object of type 'System.String' to type 'System.Int32'." | string
  | StackTrace | "   at App1.MainPage..ctor() in C:\\redacted\\repos\\App1\\MainPage.xaml.cs:line 32" | string
```
Although maybe that's a C#/winrt thing where the types aren't shown. @Scottj1s is that expected?

For the stack you provided the cast is happening inside the SetBinding, not directly in app code as with my example above. Is there more to the stack than just those 2 frames? Can you enable break on thrown exceptions to see if there is context immediately before this exception that might be helpful? Can you provide more of a snippet of the code around this or markup involved (sanitized to meet whatever sharing requirements you have)?

**Comment by Scottj1s** [comment]
@manodasanW, does this look familiar?

**Comment by manodasanW** [comment]
@NeelakandanKannan when this error happens, do you happen to see any other errors in the debug output, possibly an originate error?  If so, changing exception settings to break on that and getting the stack from it in mixed debugging might be helpful.

I am also curious if you happen to still see this error with the latest reunion update as we had made some fixes to address memory leaks and I wonder if that changes anything here as you indicate you are frequently changing bindings for different controls on scroll.
