### ISSUE TITLE
InfoBar: Static resources are not applied when overriden

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#4655]
**Describe the bug**
When overriding the static resources InfoBarContentRootPadding, InfoBarTitleFontSize, and InfoBarInformationalIconGlyph the updated values are not applied. I am assuming this applies to all of the static InfoBar resources.

**Steps to reproduce the bug**
From editing the Xaml Controls Gallery sample code:
```
<muxc:InfoBar x:Name="TestInfoBar1"
                IsOpen="True"
                Title="Title"
                Message="Essential app message for your users to be informed of, acknowledge, or take action on."
                Severity="Informational">
    <muxc:InfoBar.Resources>
        <Thickness x:Key="InfoBarContentRootPadding">0,0,0,0</Thickness>
        <x:Double x:Key="InfoBarTitleFontSize">24</x:Double>
        <x:String x:Key="InfoBarInformationalIconGlyph">&#xE706;</x:String>
    /muxc:InfoBar.Resources>
</muxc:InfoBar>
```

**Expected behavior**
The icon should be flush with the left border instead of keeping the 16px left padding. The Title font size should be 24 instead of 14. The icon should be a sun instead of the 'i'. 
Instead, the default styling remains:
![image](https://user-images.githubusercontent.com/20007011/112519583-bf888b00-8d57-11eb-8cbd-d3f1184a29d2.png)

**Comment by chingucoding** [comment]
Could this be solved by using theme resource binding instead of static resource binding for those resources?
