### ISSUE TITLE
SwapChainPanel is broken on HighDPI computers

### ISSUE THREAD

**Issue by Const-me** [microsoft/microsoft-ui-xaml#4658]
Write a WinUI3 Win32 app that has SwapChainPanel, creates the swap chain with IDXGIFactory2.CreateSwapChainForComposition, initializes Direct2D and DirectWrite, and renders something.
Test the app on a computer with 4k monitor and 150% DPI scaling.

**Expected behavior**
Should look good.

**Screenshots**
http://const.me/tmp/winui3-swap-chain-high-dpi.png

The app has more GUI there, I've cut the portion of the window occupied by SwapChainPanel.

The text was rendered with `D2D1_TEXT_ANTIALIAS_MODE_ALIASED`, yet the SwapChainPanel has cut the top-left 66% portion of the swap chain texture, and stretched that portion using bilinear sampling.

Besides the text, I’m rendering two red squares of size 10 at the top-left and the bottom right corners of the target.
Only one of them is visible, and the size of the square is 22.5 pixels instead of the correct one which is 15 pixels (because 150% DPI scaling).

Once I set desktop scaling to 100%, it works fine (don’t even need to restart the app as I’m listening to `CompositionScaleChanged` event of the swap chain panel), here’s a screenshot made by the same code: http://const.me/tmp/winui3-swap-chain-low-dpi.png The text quality is crap which is expected for `D2D1_TEXT_ANTIALIAS_MODE_ALIASED` option I'm using in my test app to debug DPI scaling issues, the DPI is still OK on that one.

**Version Info**

NuGet package version: 0.5.0-prerelease

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by kmelmon** [comment]
If you are creating your swapchain in pixels (which is recommended), you'll also need to set an inverse scale on your swapchain to counteract the scale that the compositor applies.  For an example that uses UWP XAML, see:
https://github.com/microsoftarchive/msdn-code-gallery-microsoft/blob/master/Official%20Windows%20Platform%20Sample/XAML%20SwapChainPanel%20DirectX%20interop%20sample/%5BC%23%5D%5BC%2B%2B%5D-XAML%20SwapChainPanel%20DirectX%20interop%20sample/C%23%20and%20C%2B%2B/DirectXPanels/DirectXPanelBase.cpp

**Comment by Const-me** [comment]
@kmelmon  Thanks, it worked. Very unobvious behavior, though.
The documentation explicitly states the framework does not scale swap chain content. I have expected an equivalent of BitBlt, or nearest neighbor texture sampler with passthrough shader.

**Comment by kmelmon** [comment]
@Const-me Thanks for the heads-up on the lacking docs.  Can you paste a link to the page you're referring to?  I'll help drive changing it to make this more clear, thanks!

**Comment by Const-me** [comment]
@kmelmon [That document](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.SwapChainPanel?view=winrt-19041#swap-chains) says following:

> Content that's rendered via the swap chain is not stretched when it's resized by the user; instead, the resizing behavior is similar to setting Stretch="None" on an Image element.

Technically that’s probably not wrong, but not obvious that the content is still subject to the transforms set by user in DPI OS preference, and by `IDXGISwapChain2.SetMatrixTransform` method. If the framework does support these transforms when composing pixels from swap chain into GUI, why can’t it stretch the content automatically?

The obvious (but wrong) conclusion is the SwapChainPanel doesn’t scale the content.
