### ISSUE TITLE
RadioButtons selects with focus navigation when using gamepad

### ISSUE THREAD

**Issue by kikisaints** [microsoft/microsoft-ui-xaml#466]
**Describe the bug**
When navigating through a RadioButtons list with gamepad, notice that the selection of the items follows focus.

**Steps to reproduce the bug**
- Create an app and a RadioButtons list
- Navigate through the list with a **gamepad** or Xbox controller
- Observe that the selection follows focus, which is expected behavior with the *keyboard*, but not with gamepad

**Expected behavior**
- Can navigate the list without selection following focus
- Must explicitly press the A button to select an item in the RadioButtons list

**Version Info**
WinUI 2.1 Preview

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18855)                   | Yes |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      | Potentially |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by StephenLPeters** [comment]
This was fixed with the migration to repeater
