### ISSUE TITLE
Question: how can i handle errors in composition thread

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#4660]
I got memory leak in my app and i'm pretty sure it happens on composition thread. But i got no errors, and diagnostic tools does not show it.

Is there way to handle errors and memory problems that happens on composition thread?

**Comment by ad1Dima** [comment]
To be clear, i had this problem https://github.com/microsoft/microsoft-ui-xaml/issues/4673 reported by my users. And it was hard to locate because all errors that i had was random OutOfMemoryException. And problem reproduces on my PC after app was in background for more than hour. 
It must be the way to log and handle errors on Composition thread.

**Comment by StephenLPeters** [comment]
@jeffStall can you weigh in?

**Comment by jeffstall** [comment]
@ad1Dimam, there is no "Composition Thread" in the app, so I'm not quite sure what you're referring to. Perhaps Xaml rendering thread?
@MikeHillberg , this sounds like it may be an issue with the Animated GIF player control in Xaml. Can you assign as appropriate?

**Comment by ad1Dima** [comment]
> Perhaps Xaml rendering thread?

may be. my app is eating RAM but not VisualStudio Diagnostic tool, not TaskManager don't see this. So, i have assumption that it happens out of my app process. And i know that composition animations are working on separate thread.  So i call it Composition thread, no sure of naming
