### ISSUE TITLE
Question: How to make a custom Style BasedOn a default Style from a control library?

### ISSUE THREAD

**Issue by billhenn** [microsoft/microsoft-ui-xaml#4663]
We have this scenario:

- A styled, custom Control is defined in a control library.  Let's say the library is named `FooLib` and the control `FooControl`.
- `FooControl`'s constructor has this line: `this.DefaultStyleKey = typeof(FooControl);` to designate there is a default Style.
- `FooLib` has a `Themes\generic.xaml` file in it where the default `FooControl` Style is set: `<Style TargetType="foo:FooControl">...`.
- Our application project references `FooLib`.
- We make a custom control named `BarControl` in the app project that inherits `FooControl`.
- `BarControl` wants to have its own slightly altered default Style, but also wants to inherit some of `FooControl`'s default Setters.
- `BarControl`'s constructor has this line: `this.DefaultStyleKey = typeof(BarControl);` to designate there is a default Style.
- The app project has a XAML file included in its `Application.Resources` where the default `BarControl` Style is set:  `<Style TargetType="app:BarControl">...`.

What we are finding is that the `BarControl` has its own default Style applied but nothing that should inherit from the base `FooControl` Style's Setters is coming through.  

In WPF, this scenario would allow `FooControl`'s Setters to be applied to `BarControl` unless they are overridden by `BarControl`'s Style, or `OverridesDefaultStyle` was set to true.

We did find after a lot of testing that if we remove the `DefaultStyleKey` line from `BarControl`'s constructor, the inherited Setters seem to get applied, which is what we want.  But it seems to go against proper control design.  The WPF way seems better, with the `OverridesDefaultStyle` option to prevent inherited Setters.

## Questions

1) Is there a way to do a BasedOn for a control's default Style?  We have seen the [Add key names to default control styles](https://github.com/microsoft/microsoft-ui-xaml/pull/1300) PR where the native controls had their default Style keyed like "DefaultButtonStyle" and the x:Key-less actual default Style was BasedOn that key.  However when we tried the same technique to see if we could reference a default `FooControl` Style on `BarControl`'s Style like `BasedOn="{StaticResource DefaultFooControlStyle}"`, we got an exception that DefaultFooControlStyle wasn't found.  

2) Is there some other way to base a Style on an inherited control's default Style?

**Comment by StephenLPeters** [comment]
There is no way to do BasedOn for the default style.  In Winui2 we have default styles which are based on named styles, so that they can be referenced from outside of the library to work around this exact issue. https://github.com/microsoft/microsoft-ui-xaml/blob/5f692a50b0be6c44bd1bdb8c8b3e616e2049dd07/dev/CommonStyles/Button_themeresources.xaml#L134.  Additionally I think that the template setter must also provide the target type, so your style for BarControl would need a template setter which targets BarControl as well.

**Comment by StephenLPeters** [comment]
In UWP you wont get style merging for derived types.  @MikeHillberg
