### ISSUE TITLE
Question: How do you reference a ResourceDictionary internally in a UWP class library?

### ISSUE THREAD

**Issue by YoungFcode** [microsoft/microsoft-ui-xaml#4664]
I have a UWP class library project which contains a number of pages, user controls, etc., which need to be loaded by a UWP application.
This class library is referenced/loaded by a UWP application. When the application runs a page in the class library throws below exception on call to InitializeComponent():
     "Failed to assign to property 'Windows.UI.Xaml.ResourceDictionary.Source' because the type 'Windows.Foundation.String' 
       cannot be assigned to the type 'Windows.Foundation.Uri'."

This apparently indicates that the resource or resource dictionary can't be located from this page.
I added an App.xaml (w/o App.xaml.cs) file to the root of the class library project and included the project Resource Dictionaries in Merged Dictionaries. See attached App.xaml. Is this correct approach?
Also referenced the Resource Dictionary locally in the page xaml, but still get above error.
App.xaml Build Action = Page.

The application App.xaml also references all needed Resource Dictionaries.
What is correct way to reference Resource Dictionary inside the class library?
[App.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6213258/App.zip)

**Comment by StephenLPeters** [comment]
@YoungFcode this sounds right... Can you provide a full repro application?
