### ISSUE TITLE
Question: How to get the binding for an {x:Bind} in code?

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#4669]
I want to discover the binding of a property so I can check the property validation and focus the control.  I could do this with regular bindings in WPF.  The control validation can clearly perform the query of the viewmodel validation for the property.  Is there a way to surface this functionality?

**Comment by StephenLPeters** [comment]
@omnilogix are you asking about a binding object?  x:Bind is implemented by generated code, and doesn't have an associated object.

**Comment by omnilogix** [comment]
Yes, that is what I wanted to confirm.  Is there any other mechanism to determine what property in the ViewModel is associated with a particular control via {x:Bind}?

**Comment by StephenLPeters** [comment]
From the ViewModel author's perspective?  From the app author's perspective you would know because you authored the x:bind. @RealTommyKlein are there debugging tools available?

**Comment by RealTommyKlein** [comment]
You can debug through the generated x:Bind code for your page.  The x:Bind logic is located in a generated file in your `obj` folder based on the page's name, e.g. a `MainPage.xaml` generates to a `MainPage.g.cs` for C#.  From there you can look at the x:Bind implementations for the specific x:Bind you're interested in.  As an example, a `{x:Bind ViewModel.FirstName}` would have its logic handled by the `Update_ViewModel_FirstName` method

**Comment by omnilogix** [comment]
> From the ViewModel author's perspective? From the app author's perspective you would know because you authored the x:bind. @RealTommyKlein are there debugging tools available?

No, from the view perspective.  With WPF, I would discover that the ViewModel validation fails, and find the control in the view that is bound to the failed validation.  Then, the view could navigate to, and focus the offending control.  This is about providing a great UX with minimal navigation required by the user in an error condition.

**Comment by omnilogix** [comment]
> You can debug through the generated x:Bind code for your page. The x:Bind logic is located in a generated file in your `obj` folder based on the page's name, e.g. a `MainPage.xaml` generates to a `MainPage.g.cs` for C#. From there you can look at the x:Bind implementations for the specific x:Bind you're interested in. As an example, a `{x:Bind ViewModel.FirstName}` would have its logic handled by the `Update_ViewModel_FirstName` method

I have already done this while waiting for a response to the original question.  I see there is no binding information, but there could be if Microsoft felt that the information is important, which is why I was asking.  I had hoped that there would have been a dictionary or something that provided the link between view control and veiwmodel property.    Without this information, I either need to add an attached property declaring the property name (which requires me to declare the property path again - which is extra work and error prone), or my users go without this nice functionality in my v-Next app.  Both solutions are a step back.
