### ISSUE TITLE
Gifs consume a lot of resources

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#4673]
Gifs consumes A LOT of CPU. And they continue consumption while app minimised.

**Steps to reproduce the bug**
Here is sample project https://github.com/ad1Dima/GifMemoryBlow/tree/master

1. Run application
2. Open Task manager, observe very hight CPU utilisation
3. Minimize application (do not stop playback, but you can turn volume off)
4. Wait for about 3 minutes (depends on your PC hardware)
5. Restore app
6. Observe how all you RAM is gone, 100% disk utilisation. PC is unresponsive 

**Screenshots**
![image](https://user-images.githubusercontent.com/3244664/112733555-39489080-8f73-11eb-9e76-eb2f08458b6b.png)

**Expected behavior**
1) I hope there is way to play Gifs on GPU
2) Gifs should stop playing automatically at least when app is minimized. In best case all the time when gif is not visible

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       | Yes  |

**Additional context**
There is workaround for memory consumption after app was in background. It's to stop gifs when window is minimised
Here is behaviour for that https://github.com/ad1Dima/GifMemoryBlow/blob/master/PauseGifInBackgroundBehavior.cs

**Comment by StephenLPeters** [comment]
@ad1Dima what version of Winui does this happen on?

**Comment by StephenLPeters** [comment]
@codendone and @gegao18 fyi

**Comment by ad1Dima** [comment]
@StephenLPeters it's UWP itself, I'll try to check this on latest WinUI 3

**Comment by ad1Dima** [comment]
At last, I checked it with Project Reunion 0.5. It doesn't blow memory after minimizing/maximizing window. Due to app model, I guess. But it still consumes a lot of CPU
![image](https://user-images.githubusercontent.com/3244664/113869025-782fdf00-97da-11eb-9311-c7d6e9f8fd11.png)

**Comment by pratikone** [comment]
can you confirm if it still happens ? feel free to re-open the bug if it does and we will look it with fresh perspective.
