### ISSUE TITLE
Proposal: Give api to disable shadow on flyouts in 19h1+

### ISSUE THREAD

**Issue by ahhlun** [Microsoft/microsoft-ui-xaml#468]
![flyout](https://user-images.githubusercontent.com/6519300/54780825-fa3f1200-4bd7-11e9-9f96-494d6f6cb5f0.PNG)

# Proposal: Give api to disable shadow on flyouts in 19h1+

## Summary
I want a way to disable the shadow effects on flyouts in 19h1+

## Rationale
We are using commandbarflyout, and we have custom types that expand off that of type Panel that doesn't have shadow. So want an option to disable the CommandBarflyout one as stop gap.

**Comment by jesbis** [comment]
Are you planning to add shadows to your custom types eventually?

In the meantime does setting IsDefaultShadowEnabled=false on the FlyoutPresenter do what you want?

e.g.:
````
<Flyout>
    <Flyout.FlyoutPresenterStyle>
        <Style TargetType="FlyoutPresenter">
            <Setter Property="IsDefaultShadowEnabled" Value="False" />
        </Style>
    </Flyout.FlyoutPresenterStyle>
</Flyout>
````

**Comment by chigy** [comment]
@ahhlun , we recommend turning on the shadow for the sub-menu using the code Jesse provided above.

**Comment by ahhlun** [comment]
@jesbis can you provide an example using c++ or c++/winrt code behind and not XAML?
The uwp doc site has a lot of setting styles through XAML but I need to do this in code behind.

I have trouble figuring out how to construct "TargetType" and how to set the Setter for the style.

**Comment by jevansaks** [comment]
To set TargetType from code in C++/WinRT you can use the [xaml_typename helper](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/xaml-typename).

The style setter would need to take a boxed boolean, which you can make through winrt::box_value(false).

**Comment by chigy** [comment]
@ahhlun , were you able to get this to work? It is preferred that we show shadow on your example case so hope you were able to handle it.

**Comment by ahhlun** [comment]
we plan to do this soon

**Comment by chigy** [comment]
@ahhlun, great! In that case, may I close this issue?

**Comment by chigy** [comment]
@ahhlun, you previously indicated you are adding shadow in this UI and I do not believe there is additional API needed here, so I am closing this issue.
