### ISSUE TITLE
System XAML issue: ContentDialog not blocking keyboard interactions

### ISSUE THREAD

**Issue by under3415** [microsoft/microsoft-ui-xaml#4685]
**Describe the bug**
With ContentDialog open, user can use keyboard shortcut (either AccessKey or KeyDown event) to trigger UI behind the dialog box.  

**Steps to reproduce the bug**
1. Create a button with `AccessKey = "C"` that does something
2. Open `ContentDialog` with `ShowAsync()`
3. With ContentDialog still open, press `ALT` then `C`
4. Observe that Button click event fires

**Expected behavior**
User cannot click a button while a modal ContentDialog is open

**Screenshots**

**Version Info**
This is happening in `Microsoft.NETCore.UniversalWindowsPlatform` v6.2.12
I was told to log it here as it is a system XAML issue

NuGet package version: 
N/A

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
Windows 10 10.0.19042

**Additional context**
Sample project to demonstrate the issue is here: https://github.com/under3415/NavigationApp

**Comment by StephenLPeters** [comment]
@Austin-Lamb I'm not sure we have a way for modal popups to stop access keys from being invokable..
