### ISSUE TITLE
Question: How to set ComboBox's current item by SelectedItem?

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4696]
My ComboBox bind  vector of Name.

```
<ComboBox Header="Flags" x:Name="VELK_Flags"
                ItemsSource="{x:Bind Flags}" DisplayMemberPath="Key" SelectedValuePath="Value">
</ComboBox>

```

Name defined as follow:
```
runtimeclass Name : Microsoft.UI.Xaml.DependencyObject
	{
		Name(String key, Object data);

		String Key{ get; set; };
		Object Data{ get; set; };
	}
```

when I call SelectedItem as follow  on Loaded, ComboBox current item display  empty.

```
VELK_Flags().SelectedItem(winrt::Velkhana::Name(winrt::to_hstring(L"IMREAD_COLOR"), winrt::box_value(1)));
```

Ite seems that setting currrent item of ComboBox only working by SelectedIndex.

**Comment by StephenLPeters** [comment]
The selected item needs to be one of the items in your flags collection.  This line:
```
VELK_Flags().SelectedItem(winrt::Velkhana::Name(winrt::to_hstring(L"IMREAD_COLOR"), winrt::box_value(1)));
```
Is creating a new object.

**Comment by shelllet** [comment]
> The selected item needs to be one of the items in your flags collection. This line:
> 
> ```
> VELK_Flags().SelectedItem(winrt::Velkhana::Name(winrt::to_hstring(L"IMREAD_COLOR"), winrt::box_value(1)));
> ```
> 
> Is creating a new object.

Do i hava a way to  overload operator ==  for object comparision?

**Comment by StephenLPeters** [comment]
Yeah, you should be able to override operator= in c++  https://www.tutorialspoint.com/cplusplus/cpp_overloading.htm
