### ISSUE TITLE
Ability to turn off "TopPadding" in NavigationView

### ISSUE THREAD

**Issue by jamers99** [microsoft/microsoft-ui-xaml#47]
# The WinUI team has completed [the spec](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/active/NavigationView/TopPadding/TopPaddingMargins.md) for this feature

# Proposal: Ability to turn off "TopPadding" in NavigationView

## Summary
We want to have the NavigationView all the way to the top with ExtendViewIntoTitleBar false.
Here is a screenshot of what I want:
![untitled](https://user-images.githubusercontent.com/20806279/49612694-86079800-f973-11e8-872c-053ab90a7547.png)

## Rationale
I looked at the code for this and found that to achieve this I can put a small margin on my NavigationView and it works.  I should not have to do this kind of hack to achieve a simple customization like this. 
The logic can be found in `microsoft-ui-xaml/dev/NavigationView/NavigationView.cpp` at `NeedTopPaddingForRS5OrHigher`

## Functional Requirements
A property on the NavigationView called something like "EnableAutomaticPadding"

## Usage Examples
The default of the property would be true, so to turn it off I could just set it to false.

### Prerelease readiness
- [x] Dev: quality review + code review done
- [x] Dev: test coverage added
- [x] Dev: initial accessibility review done
- [ ] Dev: telemetry implemented
- [x] PM: spec up to date
- [x] PM: feature ready for feedback
- [x] PM: docs.microsoft.com updates ready
### Stable release readiness
- [x] Dev: feature previously shipped in a prerelease NuGet package
- [ ] Dev: Azure CI tests passing
- [x] Dev: accessibility review done
- [x] Dev: API review done
- [ ] Dev: IDL attribute switched from preview to public
- [ ] Dev: Add test coverage to the NugetReleaseTest test
- [x] PM: spec done
- [x] PM: glob/loc, privacy, security, license compliance ready
- [x] PM: customer validation done
- [x] PM: docs.microsoft.com updated
- [ ] PM: Xaml Controls Gallery updated

**Comment by YuliKl** [comment]
@jamers99 Thank you for the feature request, I agree with you that the top of NavigationView lacks easy customization opportunities. We're planning to add an overwritable ThemeResource to address this. A ThemeResource will allow us to keep the current default padding and also let app developers choose custom values, including 0.

This work is currently tracked by internal bug 18004204.

**Comment by YuliKl** [comment]
Broadening this feature request slightly. We should provide new ThemeResources for both the <b>TopPadding</b> on NavigationView.Content and <b>HeaderContent margin</b> on NavigationView.Header.

**Comment by mdtauk** [comment]
Maybe the platform could provide a TitlebarHeight which can be consumed in XAML without having to query the OccludedRect - and this value updates on DPI changes?

This value could then be used by the NavigationView top padding when Titlebar is extended, and overridden by a non empty/null value in the app resources?

**Comment by YuliKl** [comment]
Very brief spec for this feature request is now available here: https://github.com/Microsoft/microsoft-ui-xaml-specs/pull/8

**Comment by chrisglein** [comment]
Modest starter for whoever picks up this work: https://github.com/microsoft/microsoft-ui-xaml/tree/user/cglein/navViewTopPadding
(just adds the property, doesn't consume it)

**Comment by knightmeister** [comment]
Hi guys, is this still targeting 2.2?

**Comment by YuliKl** [comment]
> Hi guys, is this still targeting 2.2?

While @RBrid would know with more certainty, I believe we are still targeting WinUI 2.2

**Comment by YuliKl** [comment]
Reopening the issue to make sure I update documentation. @RBrid, can you double-check that the Release Checklist is accurate?
