### ISSUE TITLE
Microsoft.UI.Xaml.winmd not included in build output

### ISSUE THREAD

**Issue by ollitanska** [microsoft/microsoft-ui-xaml#4701]
**Describe the bug**

After upgrading to v2.6.0-prerelease.210315002 from v2.6.0-prerelease.210227001, the Microsoft.UI.Xaml.winmd is not included in the output directory anymore. Microsoft.UI.Xaml.dll and Microsoft.UI.Xaml.pri are included as expected.

This causes the following exception when starting up the application: 'System.TypeLoadException: Could not find Windows Runtime type 'Microsoft.UI.Xaml.Controls.XamlControlsResources'.

This regression seems to be caused by this commit:  #4218 

**Steps to reproduce the bug**
1. Follow the Xaml Islands guide on [https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands)
2. Install version v2.6.0-prerelease.210227001 of the package, application should start fine
3. Install version v2.6.0-prerelease.210315002 of the package, application will not start. No .winmd file and got System.TypeLoadException exception

**Expected behavior**
Application would startup normally, Microsoft.UI.Xaml.winmd would be included in the output directory.

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.v2.6.0-prerelease.210315002]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |   |
| November 2019 Update (18363)       |   |
| May 2019 Update (18362)            |   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |
| Xbox               |  |
| Surface Hub        | |
| IoT                |  |

**Additional context**
WPF application that hosts a custom UWP control (which uses WinUI 2.6) via XAML Islands.

**Comment by StephenLPeters** [comment]
@ollitanska Thanks for the bug! do you have a repro app you could provide here?  it would be handy in fixing this :)

**Comment by StephenLPeters** [comment]
@ranjeshj I think this is needed for 2.6 release.

**Comment by ollitanska** [comment]
> @ollitanska Thanks for the bug! do you have a repro app you could provide here? it would be handy in fixing this :)

Here is a minimal repro app.

[XamlIslandsSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6241344/XamlIslandsSample.zip)

**Comment by llongley** [comment]
Hi @ollitanska - I have a candidate fix that works on my side, but I was hoping you could test it out and see if it works for you as well before I send it out for PR.  Could you put this at the very bottom of App1.csproj, just before `</Project>`?

```
  <Target Name="_AddXamlWinmdToPackageLayoutRoot" AfterTargets="BuildNativePackage">
    <ItemGroup>
      <AppxPackagePayload Include="@(XamlWinmd)">
        <TargetPath>Microsoft.UI.Xaml.winmd</TargetPath>
      </AppxPackagePayload>
    </ItemGroup>
    <Copy SourceFiles="@(XamlWinmd)" DestinationFiles="@(XamlWinmd -> '$(OutDir)\%(Filename)%(Extension)')" />
  </Target>
```

If this does work for you, also try it in whatever app you were using where you found this.  If it works in both locations, I can get this fix in the pipeline.

**Comment by ollitanska** [comment]
> Hi @ollitanska - I have a candidate fix that works on my side, but I was hoping you could test it out and see if it works for you as well before I send it out for PR. Could you put this at the very bottom of App1.csproj, just before `</Project>`?
> 
> ```
>   <Target Name="_AddXamlWinmdToPackageLayoutRoot" AfterTargets="BuildNativePackage">
>     <ItemGroup>
>       <AppxPackagePayload Include="@(XamlWinmd)">
>         <TargetPath>Microsoft.UI.Xaml.winmd</TargetPath>
>       </AppxPackagePayload>
>     </ItemGroup>
>     <Copy SourceFiles="@(XamlWinmd)" DestinationFiles="@(XamlWinmd -> '$(OutDir)\%(Filename)%(Extension)')" />
>   </Target>
> ```
> 
> If this does work for you, also try it in whatever app you were using where you found this. If it works in both locations, I can get this fix in the pipeline.

Works great, both on the repro app and our real app!

Thanks for quick response!

**Comment by llongley** [comment]
Sweet, thanks for the confirmation!  I'll get that out for PR.

**Comment by sylveon** [comment]
Is it possible to add an option to not copy the file still, since C++ based Xaml islands apps don't need the winmd.
