### ISSUE TITLE
AutoSuggestBox suggestions positioned incorrectly when using an IME after switching window focus

### ISSUE THREAD

**Issue by docjay** [microsoft/microsoft-ui-xaml#4704]
Using the XAML Controls Gallery, the suggestions list moves and results in a gap between the list and the search box when switching back to the window while using an IME.

1. Use an IME (e.g. Chinese PinYin input)
2. Launch XAML Controls Gallery and go to AutoSuggestBox
3. Type using PinYin input so that the IME appears and there are search results
4. Use taskbar to focus on another window
5. Use taskbar to return focus to the XAML Controls Gallery
6. Notice there is now a gap between the search results and the text box.  Expect that the search results list should still be rendered next to the text box

https://user-images.githubusercontent.com/1240472/113193999-76cc4880-9215-11eb-803d-4e06188fcedd.mp4

**Comment by StephenLPeters** [comment]
I think that the issue is that the IME should be drawing when you restore to this application.

**Comment by StephenLPeters** [comment]
@MikeHillberg Do you know who owns this space?

**Comment by StephenLPeters** [comment]
@marb2000 FYI

**Comment by Austin-Lamb** [comment]
AutoSuggestBox is the Framework team

**Comment by chrisglein** [comment]
> AutoSuggestBox is the Framework team

No longer. We migrated it to Controls.

**Comment by StephenLPeters** [comment]
@Austin-Lamb I think this is an issue with the IME not drawing when it is supposed to be, not with autosuggest box miss positioning its flyout. Do you agree? If we control IME I was guessing that would fall under reach's domain, but the bug could be external
