### ISSUE TITLE
Using ItemsRepeater with IElementFactory throws an ArgumentException

### ISSUE THREAD

**Issue by FreddyDgh** [microsoft/microsoft-ui-xaml#4705]
**Describe the bug**
When using Project Reunion 0.5 GA, setting the `ItemTemplate` property of `ItemsRepeater` to an `IElementFactory` throws an `ArgumentException`.  In Project Reunion 0.5 Preview, there was an `IElementFactoryShim` interface that could be used instead. However, in the GA release, the shim was removed, but the normal functionality of `IElementFactory` was apparently not restored.

**Steps to reproduce the bug**
Create a blank window and add code behind such as the following:
```csharp
public sealed partial class MainWindow : Window
{
    private class MyElementFactory : IElementFactory
    {
        UIElement IElementFactory.GetElement(Microsoft.UI.Xaml.ElementFactoryGetArgs args)
        {
            return new TextBlock() { Text = "Item " + args.Data.ToString() };
        }

        void IElementFactory.RecycleElement(Microsoft.UI.Xaml.ElementFactoryRecycleArgs args)
        {
        }
    }


    public MainWindow()
    {
        this.InitializeComponent();

        this.Content = new ScrollViewer()
        {
            Content = new ItemsRepeater()
            {
                ItemTemplate = new MyElementFactory(),
                ItemsSource = Enumerable.Range(0, 1000),
            }
        };
    }
}
```

**Expected behavior**
I expect that the `ItemTemplate` property of `ItemsRepeater` can be set to an object that implements `IElementFactory`, or a similar interface.

**Screenshots**
N/A

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  Yes  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
N/A

**Comment by MuleaneEve** [comment]
Close this issue in favor of #3448?

**Comment by DilanBoskan** [comment]
This is also the case for UWP with WinUI 2!

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.3.0` has been released which fixes this issue.
* [Release Notes](https://aka.ms/windowsappsdk/1.3/1.3.0/release-notes)
* [Nuget](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000)
