### ISSUE TITLE
Question: StackPanel HorizontalAlignment

### ISSUE THREAD

**Issue by Herdubreid** [microsoft/microsoft-ui-xaml#4708]
I'm not sure if I'm missing something, but is this expected (WinUI 3 in Desktop)?

Create a simple StackPanel:
```xaml
    <StackPanel
        HorizontalAlignment="Left">
        <TextBlock>Some Text</TextBlock>
        <TextBox Width="300" Header="A TextBox..."/>
        <TextBox Width="200" Header="A smaller TextBox..."/>
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    </StackPanel>
```
And the second textbox looks like it's centre aligned instead of left aligned.
![image](https://user-images.githubusercontent.com/21098321/113232159-2ca79d80-92cf-11eb-8ba5-c87da32c3ee6.png)

**Comment by dpaulino** [comment]
Yes this is expected. The HorizontalAlignment=Left designation is applied to the StackPanel in relation to its parent container. So this means that the stackpanel will be on the left side of its parent grid. The HorizontalAlignment=Left has nothing to do with the content inside of the stackpanel. 

If you want the items inside the stackpanel to be left aligned, you can set HorizontalAlignment=Left for the textbox with 200width. Like this
```xaml
    <StackPanel
        HorizontalAlignment="Left">
        <TextBlock>Some Text</TextBlock>
        <TextBox Width="300" Header="A TextBox..."/>
        <TextBox Width="200" Header="A smaller TextBox..." HorizontalAlignment="Left"/>
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    </StackPanel>
```

**Comment by Herdubreid** [comment]
Ahh, that makes sense @dpaulino.

But what confuses me is that `<TextBlock>` and `<Button>` appear to be `left-aligned` by default, but `<TextBox>` is `centre-aligned` by default:
```xaml
    <StackPanel
        HorizontalAlignment="Stretch">
        <TextBlock HorizontalAlignment="Center">Centre aligned TextBlock</TextBlock>
        <TextBlock>Left aligned Text</TextBlock>
        <TextBox Width="300" Header="Center aligned TextBox"/>
        <TextBox HorizontalAlignment="Left" Width="200" Header="Left aligned TextBox"/>
        <Button HorizontalAlignment="Center">Button in the Centre</Button>
        <Button>Button on the Left</Button>
    </StackPanel>
```

![image](https://user-images.githubusercontent.com/21098321/113256651-0fd58f00-92fc-11eb-9c14-89f644490103.png)

I got the feeling I'm missing something fundamental here and it's doing my head in...

**Comment by dpaulino** [comment]
I think textbox has a default horizontal alignment of stretch. Combined with the width=200, you get the Center aligned look. I might be misremembering but I think this is what's happening.

**Comment by Herdubreid** [comment]
That explains it @dpaulino,  `Stretch` seems to be the default and then the `Width` property puts the element in the centre.

Sanity restored, thanks!
