### ISSUE TITLE
Design in Blend dose not work with WinUI 3 (ProjectReunion)

### ISSUE THREAD

**Issue by Samijaf** [microsoft/microsoft-ui-xaml#4711]
Hi, Please, why I'm not able to use Blend for visual studio 2019? what can do to make it work? I'm getting the below error:

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - POS.DesktopUI (Package), "D:\Projects2021\Source\Repos\POS\POS Solution\POS.DesktopUI\POS.DesktopUI (Package)\POS.DesktopUI (Package).wapproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - POS.DesktopUI, "D:\Projects2021\Source\Repos\POS\POS Solution\POS.DesktopUI\POS.DesktopUI\POS.DesktopUI.csproj"
	 - POS Solution, "D:\Projects2021\Source\Repos\POS\POS Solution\POS Solution.sln"

Thank you

**Comment by StephenLPeters** [comment]
@ryandemopoulos and @MikeHillberg FYI

**Comment by marb2000** [comment]
Project Reunion doesn't support XAML Designer neither via Blend nor Visual Studio. Also, there is no plan to support the design in 2021.

The current recommendation is to use Visual Studio and design your app using XAML Hot-Reload features.

**Comment by fourdragons** [comment]
> The current recommendation is to use Visual Studio and design your app using XAML Hot-Reload features.

Me: "Nope, that didn't work. Nope, that didn't work. Nope, that didn't work." Seems like the good ol' days of Peek and Poke. (Youngin's will have zero clue what those are...)
