### ISSUE TITLE
Question: Shadow is not rendering on button. 

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/microsoft-ui-xaml#4712]
I have this code in my app:
![image](https://user-images.githubusercontent.com/16069721/113311812-f9cecb00-9309-11eb-97ee-d0908ed0fa6e.png)

Problem is shadow is not creating under button. Is it okay or shadow should be created according to code?

**Comment by mdtauk** [comment]
ThemeShadow requires a Shadow Receiver to be set I think

**Comment by JanRajnoha** [comment]
According to docs it is not required in this case (I think): https://docs.microsoft.com/en-us/windows/uwp/design/layout/depth-shadow#themeshadow-in-popups

**Comment by StephenLPeters** [comment]
Shadows from popups do not require a ShadowReceiver to be specified, however shadows on normal elements do require both a receiver and for the element with the shadow to have a positive translations of the z coordinate.
