### ISSUE TITLE
Frame Navigation leaks memory.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#4713]
**Steps to reproduce the bug**

[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6244576/App1.zip)

1. Build attached app.
2. Run app.
3. Change pages using Go xxx Page buttons
4. Watch memory growth using Task Manager

**Expected behavior**
Memory should be reclaimed. 

**Screenshots**
n/a

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.6.0-prerelease.210315002]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**

**Comment by Noemata** [comment]
Added memory utilization display to this version (minor change).  Look out debug output window for escalation of memory usage.  Uses about 2MB per page change.  Should be zero.  This an unsustainable level of memory consumption.

[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6246362/App1.zip)

**Comment by Noemata** [comment]
![image](https://user-images.githubusercontent.com/6632315/113353226-567eb580-930b-11eb-96fd-b2981d48cc34.png)

**Comment by Noemata** [comment]
Sufferin succotash ...

With NavigationCacheMode="Disabled", its even worse.  I don't get it.

[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6246509/App1.zip)

![image](https://user-images.githubusercontent.com/6632315/113354839-c5f5a480-930d-11eb-93bc-ccda7a3e73fb.png)

**Comment by Noemata** [comment]
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/6a90654b-eb7c-44de-af6b-04140b0ee6ca/uwp-page-navigation-memory-leak?forum=wpdevelop

**Comment by Noemata** [comment]
This is a Debug release build, so shouldn't have anything to do with .Net Native.

**Comment by Noemata** [comment]
Solved!

After checking some other apps, turns out Navigation is working correctly.  Not leaking.

The bug in this case is with the TabView control.  It's broken, breaks navigation among other things.

Working backwards, I noticed Page destructors weren't being called.  Just by commenting out the TabView control in the following sample, Navigation starts to work correctly.  This code is similar to the above, minus TabView.

[App2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6246859/App2.zip)

**Comment by StephenLPeters** [comment]
@Noemata do you know if this is a regression with 2.6 or if it was present in 2.5 as well?  If you call GC.Collect mannually does it fix the leak?

**Comment by Noemata** [comment]
@StephenLPeters , this problem goes all the way back to the Toolkit version.  Looks like it's been around a very long time.  Hate to say it again, you folks need a way better regression testing strategy.  How could something like this go unnoticed for so long?

**Comment by asierpn** [comment]
@Noemata in my tests by removing the TabView and setting NavigationCacheMode = Disabled the memory seems to stay below 225 MB, but if you set NavigationCacheMode = Enabled the memory keeps growing, in this case it is the DataGrid that is causing the memory leaks with NavigationCacheMode = Enabled.

This scenario must be tested using all WinUI controls.

**Comment by Noemata** [comment]
@asierpn , completely agree with your sentiment about WinUI testing.  Don't know about the DataGrid issue you're seeing.  You have to do an explicit GC.Collect to be sure about memory leaks.  The GC is an engineering marvel, it's very smart about clearing memory and will wait a surprisingly long time when there's no memory pressure.

TabView was a big surprise.  I didn't even think of looking at it for problems given it has been around for so long.  I've never used it because Pivot is lighter and better for most of my needs.  I initially thought the Navigation bug had resurfaced, since it had only gotten fixed in 2019.  Previously it was leaking about 1.5 K per navigation.  Microsoft decided that was ok for 3 years or more!

I'm going to add one more detail here, because occasionally such remarks get noticed.  Microsoft uses the fancy word "Telemetry" a lot.  The way they use the term has become meaningless because there is no intelligence behind their use.  If you have 5 apps in the store that use a specific feature, but those 5 apps are running on every Windows desktop constantly, it doesn't matter that there are only 5 apps using the feature.  The usage is so pervasive, it has become essential.

And if the Telemetry gathering is so sophisticated, how does a TabView memory leak get missed for years?

I had reported bugs through the reporting features build into Windows.  None were ever addressed.  The only place bugs would get addressed is in forums like this!  Microsoft needs "this" more than ever.

**Comment by Noemata** [comment]
@asierpn , here's your sample modified to test DataGrid.  I don't think it's leaking.  The nature of the allocations done by DataGrid probably cause the GC to be fussier about what it decides to release and when.  Small allocations tend to get pooled.  Microsoft's internal tooling should be able to quickly spot a leak if there is one.

[AppDataGrid.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6249537/AppDataGrid.zip)

**Comment by Noemata** [comment]
Question for Microsoft on AppDataGrid ... Why is there any delay when switching pages with NavigationCacheMode set to "Enabled" when the DataGrid control is on the page?  The switch with other controls is instantaneous.

What's causing the performance to degrade with certain controls?

**Comment by Noemata** [comment]
@StephenLPeters , @asierpn , this is a can of worms.  Depressingly so.  @asierpn , I reworked your sample slightly out of curiosity.  Even with ListView, Navigation Frame leaks when NavigationCacheMode is set to "Enabled".  Looks like there is still a bug with Navigation Frame.

Here's the test app:

[ListView.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6249815/ListView.zip)

It's also baffling why page transitions are so incredibly slow???  What's the point of NavigationCacheMode="Enabled" if page redraw for a larger dataset is going to be so slow and you get the bonus memory leak.  You're better off using a swappable content control.  In my view, both the memory leak and performance issue need to be addressed.

I really hope I made some stupid mistake in the code.

**Comment by Noemata** [comment]
@asierpn , some minor cleanup to the version above.  Will be interesting to see what happens with this.

[ListView.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6250348/ListView.zip)

**Comment by asierpn** [comment]
@Noemata at this moment you have the same questions that we have about UWP performance, there is memory leaks using NavigationCacheMode="Enabled" and there is also a delay when switching pages which we don't understand if all the visual tree of the page is cached. This delay increases when the visual tree of the page is big and also when the process is consuming so much memory caused by memory leaks, in low powered machines these delays are very noticeable, and if you stress the app during them you can crash it, this scenario can be easily reproduced with the XAML Controls Gallery official app.

> I'll leave it to you to hound Microsoft on that one. I'm pretty sure they're sick of me already. @asierpn, suggest you file a separate issue for DataGrid with the sample below.

I hope they are not fed up with you, this feedback is necessary to improve the platform even if it is not pleasant to hear. 

We don't use the DataGrid of the Windows Community Toolkit in our production app, I used it in this repro project to show you better our real scenario, we use a 3rd party DataGrid which has the same issue and we have reported it to our UWP controls provider.

**Comment by asierpn** [comment]
@Noemata It seems that Microsoft was aware of these issues for a long time and finally they have started to address them, at least the memory leaks: https://github.com/microsoft/CsWinRT/releases/tag/1.2.0.210402.1

And the issue with the delays navigating to cached pages must be directly related to https://github.com/microsoft/microsoft-ui-xaml/issues/1633, this other issue must be priorized.

**Comment by Noemata** [comment]
@asierpn , I see WinUI 3 and UWP as being separate in many ways.  Hopefully, underlying UWP problems will get fixed as more attention falls on WinUI and the code it shares with UWP.  The CsWinRT memory leaks are unrelated to UWP in most cases.  At the moment, UWP is 3 times faster than WinUI.  Without a .Net Native alternative, WinUI won't be able to reach 1:1.  What is possible is to tune the underlying tech further.  Like UI caching.

**Comment by Noemata** [comment]
I decided to take an even closer look as a result of some other feedback I've received.

@asierpn  and @StephenLPeters , looks like there is a bug in Visual Studio and not with Navigation Frame, at least when used with a simple ListView control.  When running under Visual Studio, there is a significant slow down in page transitions.  What's worse, Visual Studio 2019 seems to be contributing to what appears like a Navigation Frame memory leak.   So Visual Studio 2019 makes it impossible to debug this particular problem.

If you run the version of the ListView1 app below outside of Visual Studio (directly), you will see that after a GC settling period (quite long by the way), memory growth appears to stop.  I lost patience trying to see it grow ...

There are WinUI controls that cause Navigation Frame leaks.  ListView is not one of them.

So I guess this is really a tooling bug.  I'm sure Microsoft has a better way of confirming my findings.  This needs to be forwarded to the Visual Studio team for a close look.

[ListView1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6255053/ListView1.zip)

**Comment by Noemata** [comment]
@asierpn , same test with DataGrid.  No leaks or hangs provided you run this outside of VS.

[DataGrid1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6258813/DataGrid1.zip)

**Comment by Noemata** [comment]
@asierpn and @StephenLPeters , same test with TabView.  Broken in too many ways to even bother with speculation.  Leaks, has binding issues (breaks binding somehow), etc.  Note, was running outside of VS.

[TabView1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6259020/TabView1.zip)

I also noticed this bug has resurfaced, which was closed in 2018.

**Comment by asierpn** [comment]
@Noemata your last results are very interesting, it is really hard to work with this kind of issues when VS is interfering in the tests, but still must be there some issues with frame navigation and memory leaks, open the official XAML Controls Gallery and navigate to each page, you will see how memory usage grows and render performance decreases, if the application is stressed it finally crashes.

**Comment by Noemata** [comment]
@asierpn , I was totally confused also.  Couldn't tell which was up or down for a time.  Yes, VS being the tool we have to diagnose such problems being a contributor to them is a big problem.  XCG (Xaml Controls Gallery) has some non trivial design issues.  Microsoft staffers make the same mistakes we do.  Microsoft's LOB samples have been a really good example of that and have contributed to some poor design choices on the part of companies using those as a de facto starting point.  The only fair way to pin point these sorts of problems is to look at them in isolation.  @asierpn , you'll have to admit, we both made some mistakes either in coding or debugging.  Though it is somewhat unexpected that the tooling we use to debug with contributes to the bugs we are trying to resolve.

**Comment by asierpn** [comment]
@Noemata I'm agree with you, I will restart all my tests to try to find what is causing the memory leaks in our app, your last sample is a good point to start, running it always outside VS.

**Comment by Noemata** [comment]
Note, I haven't yet figured out how to have AutoPage work correctly with NavigationCacheMode="Disabled".

**Comment by Noemata** [comment]
I think I found a way to test for the case where NavigationCacheMode="Disabled".

The code executes without memory leaks until you stop it.  If you let it run for a minute or so and then stop it, then proceed to manually page through, there appears to be a problem.  Everything becomes very sluggish, and a large amount of memory becomes unrecoverable henceforth.

I wonder if this version of the code reveals a form of the problem @asierpn is seeing.  It would be helpful if someone from Microsoft would chime in after looking at the code below:

[ListView2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6260993/ListView2.zip)

I'm hoping someone can spot a coding error, or a better way of doing this sort of testing.

**Comment by Noemata** [comment]
I found the solution to ListView2.  I'll publish the details after Microsoft responds.

**Comment by Noemata** [comment]
After running my revised ListView2 for an hour or more without interaction, memory utilization stays consistent.  System memory never gets stressed.  So all is good on that front.  However, the app crashes after several thousand navigations.

**Comment by Noemata** [comment]
The following testing tool is mostly self explanatory if you have a close look at the code: https://github.com/Noemata/RosettaNavigation

The tool may be used to test both performance and Navigation Frame memory issues for both WinUI and UWP.

**Comment by lukedukeus** [comment]
Somehow, this is still an issue, on windows 11 22000, winui 1.1 preview 3

**Comment by CalebPowell57** [comment]
@Noemata I'm running into this issue and wonder if you've found any workaround or solution? I've tried different target versions, different uwp versions. I've even tried not using frame navigation, but instead, setting the content of a page to another page. In each scenario, it seems on general render, memory is leaked.
