### ISSUE TITLE
SplitButton doesn't open when pressing the "Space" key or the "Enter" key

### ISSUE THREAD

**Issue by ejserna** [microsoft/microsoft-ui-xaml#4714]
**Describe the bug**

The SplitButton doesn't open when pressing these keys. This is an accessibility issue, as there's no other way to open it, other than by clicking on it.

**Steps to reproduce the bug**

1. Create a SplitButton
2. Tab to focus it.
3. Press space or enter.
4. The splitbutton doesn't open.

**Expected behavior**

Expected:
4. The splitbutton should open, just like a DropDownButton

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml.2.6.0-prerelease.210315002

**Comment by StephenLPeters** [comment]
This is by design, the space and enter key invoke the primary button the chevron is invokable via Alt+Down
