### ISSUE TITLE
Exception raised by NavigationView in Reunion 0.5

### ISSUE THREAD

**Issue by ArturRuta** [microsoft/microsoft-ui-xaml#4716]
**Exception raised by NavigationView in Reunion 0.5**

Any page containg a NavigationView having a Frame as Content briefly shows a blank window (without the NavigationView) and then raises a Microsoft C++ Exception winrt::hresult_error at memory location.....
Debugger stops there (actually it asks for loading the symbols in wkernelbase.pdb but even if loaded the exception is still being produced)
if continue is selected in the debugger then the page completes rendering and rendered and behaves normally
This behavio was not present in preview 3 nor 4

**Steps to reproduce the bug**

1. Clean install of Visual Studio 19.10 preview 1.0 + Project Reunion Extension (nothin intherited from previous versoins)
2. Create a blank application
3. Remove the handler for the sample button in the code behind
3. Replace the xaml code with de following sample and run the application

`<Window`
    x:Class="NavigationViewTest.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NavigationViewTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
`<NavigationView x:Name="nvSample">`
`<NavigationView.MenuItems>`
`<NavigationViewItem Icon="Play" Content="Menu Item1" Tag="SamplePage1" />`
`<NavigationViewItem Icon="Save" Content="Menu Item2" Tag="SamplePage2" />`
`<NavigationViewItem Icon="Refresh" Content="Menu Item3" Tag="SamplePage3" />`
`<NavigationViewItem Icon="Download" Content="Menu Item4" Tag="SamplePage4" />`
`</NavigationView.MenuItems>`
`<Frame x:Name="TestFrame"/>`
`</NavigationView>`
`</Window>`

**Expected behavior**

The page with the NavigationView should have been rendered with no exception involved.

**Screenshots**

**Version Info**

NuGet package version: 

Project Reunion 0.5.0.85112000

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This behavio was not present in preview 3 nor 4

**Comment by huoyaoyuan** [comment]
#4496

**Comment by ArturRuta** [comment]
Some additional info. Have found that the problem arises when running the application fom within the debugger. 
Have generated the package and installed and in that configuration it runs smoothly. 
Still the problem is present 100% of times when run from within the debugger.

**Comment by ArturRuta** [comment]
Just found in stackoverflow the same solution and confirm that de bypass in [#4496](https://github.com/microsoft/microsoft-ui-xaml/issues/4496) did work for me. Hope an actual fix will be generated. Thanks a lot. huoyaoyuan

**Comment by StephenLPeters** [comment]
Yup, this is a known issue with the acrylic brush navigation view uses.
