### ISSUE TITLE
TabView breaks Navigation and causes memory leaks.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#4718]
**Describe the bug**
Just by adding the TabView control to a page, it breaks Navigation and causes memory leaks.

**Steps to reproduce the bug**

[App2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6246899/App2.zip)

1. Build App attached above.
2. Run App.
2. Select Page navigation buttons and observe Page deconstructors being called.
3. Close App.
3. Uncomment TabView control on Page 1 Xaml.
4. Run App.
5. Select Page navigation buttons and observe Page 1 deconstructor not being called causing memory leaks.

**Expected behavior**

Page 1 deconstructor should be called so its memory resources can be reclaimed.

**Screenshots**

n/a

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.6.0-prerelease.210315002]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
This issue affects every release of the TabView control, including those in the Community Toolkit, so the problem predates integration into WinUI.

**Comment by duke7553** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/3597

Could this be related to the issue I reported last year?

**Comment by Noemata** [comment]
@duke7553 , I wouldn't be able to speculate on that.  Just adding the control and not using it was enough to cause Navigation to leak.  Have a look at the code.  I don't have much experience with the control, I was looking into an issue someone else had posted.  Would be helpful to have other eyes on the code samples.

There are curious interactions with Navigation Frame and NavigationCacheMode.  NavigationCacheMode="Enabled" seems to trigger a memory leak regardless of what controls you are using.  TabView seems to have additional problems.

For additional context, you can look here: https://github.com/microsoft/microsoft-ui-xaml/issues/4713

**Comment by Noemata** [comment]
I have refined the test so that it can be run outside of Visual Studio 2019, since it adds its own memory leak artifacts.

This version of the test also manifests a previously closed issue: https://github.com/microsoft/WindowsTemplateStudio/issues/2726

[TabView1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6259036/TabView1.zip)

**Comment by Noemata** [comment]
The following testing tool is mostly self explanatory if you have a close look at the code: https://github.com/Noemata/RosettaNavigation

The tool may be used to test both performance and Navigation Frame memory issues for both WinUI and UWP.
