### ISSUE TITLE
InvalidCastException when setting DatePicker SelectedDate property - 'Specified cast is not valid'

### ISSUE THREAD

**Issue by thomasclaudiushuber** [microsoft/microsoft-ui-xaml#4719]
**Describe the bug**
When trying to set `SelectedDate` property of `DatePicker`, an `InvalidCastException` is thrown.

**Steps to reproduce the bug**
1. Create a new WinUI 3 in Desktop app (Reunion 0.5)
2. Add a DatePicker to the MainWindow in a Grid like here:
```
  <Grid Loaded="Grid_Loaded">
    <DatePicker x:Name="datePicker"/>
  </Grid>
```
3. In the codebehind file, add the `Grid_Loaded` handler and set the `SelectedDate` property to a new `DateTimeOffset` instance:
```
private void Grid_Loaded(object sender, RoutedEventArgs e)
{
  var timeOffset = new DateTimeOffset(new DateTime(2021,10,10);
  datePicker.SelectedDate = timeOffset;
}
```

This should just work, but it throws an `InvalidCastException` when trying to set the `SelectedDate` property. The `Date` property works fine, but `SelectedDate` does not, so maybe it has something to do with `Nullable<DateTimeOffset>`, as that's the type of the `SelectedDate` property, while the `Date` property is just of type `DateTimeOffset`.

**Expected behavior**
Selected date should be set without throwing an `InvalidCastException`.

**Screenshots**
![image](https://user-images.githubusercontent.com/7116546/113397933-1ddbec00-939e-11eb-9d48-52c6781468a4.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0] 

Windows app type: Win32

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I was not able to reproduce that error on my SB2, but I was able to reproduce it on my desktop. Both have Windows 19042, I haven't found out why it happens on one machine, but not on the other. But many people reached out to me because of this issue, and using `Date` property instead of `SelectedDate` property is a workaround.

**Comment by riverar** [comment]
Sample project for repro: [DatePickerIssue4719.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6248634/DatePickerIssue4719.zip)

Repros here on 19042.906

**Comment by riverar** [comment]
Does **not** repro on 18363,1440.

**Comment by mrlacey** [comment]
I **can** repro on Insider build 21343.1000 (running on a Surface Book 2)

**Comment by angelazhangmsft** [comment]
This was an issue fixed in C#/WinRT 1.1.4 - the fix will be available in an upcoming .NET SDK update, or a workaround for now is referencing the latest CsWinRT package.

**Comment by Scottj1s** [comment]
Closed per Angela's recommendation

**Comment by riverar** [comment]
For those looking for step-by-step:
1. Add Microsoft.Windows.CsWinRT NuGet package reference (1.1.4 or higher) to your project
2. Edit your .csproj and add `<CsWinRTWindowsMetadata>$(TargetPlatformMinVersion)</CsWinRTWindowsMetadata>`
3. Rebuild / Run

**Comment by angelazhangmsft** [comment]
@riverar - instead of step 2, we recommend adding `<CsWinRTEnabled>false</CsWinRTEnabled>` for overriding the runtime (although both ways work)

**Comment by riverar** [comment]
@angelazhangmsft Agreed. Edited to prevent confusion.

**Comment by thomasclaudiushuber** [comment]
Thanks @angelazhangmsft and @riverar, great that we have an easy workaround for this.

**Comment by thomasclaudiushuber** [comment]
Update: In the meantime I also found out why it worked on the SB2, but not on the desktop machine. The SB2 had the .NET SDK 6.0.0 preview 1 installed. After I uninstalled that SDK, the error also arrived there.

Next, I installed .NET SDK 5.0.300-preview21201.25. Looks with that one the error is also gone. Thanks again everyone here for the help and great support!
