### ISSUE TITLE
WinUI3 - Project Reunion 0.5 - WinRT.Runtime version mismatch

### ISSUE THREAD

**Issue by Rand-Random** [microsoft/microsoft-ui-xaml#4722]
**Describe the bug**
I want to give the latest version a go, and followed the instructions from here
https://docs.microsoft.com/en-us/windows/apps/project-reunion/get-started-with-project-reunion
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop

I have read the instruction now a 5th time, I believe I have done everything correct, but I fail to run a newly created project.

I am getting this error

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1705	Assembly 'Microsoft.WinUI' with identity 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' uses 'WinRT.Runtime, Version=1.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709' which has a higher version than referenced assembly 'WinRT.Runtime' with identity 'WinRT.Runtime, Version=1.0.1.33301, Culture=neutral, PublicKeyToken=99ea127f02d97709'	App5	C:\Users\rfa\source\repos\App5\App5\App5\App.xaml.cs	27	Active

![image](https://user-images.githubusercontent.com/9868626/113396897-83c77400-939c-11eb-9788-c7ba6e8c7836.png)

**Steps to reproduce the bug**
Unknown

**Expected behavior**
The newly created project should build and run.

**Screenshots**
Screenshot provided earlier.

**Version Info**

NuGet package version: 
![image](https://user-images.githubusercontent.com/9868626/113397007-af4a5e80-939c-11eb-84ff-6c1ad746facc.png)

Windows app type:
Win32

Windows 10 version:
![image](https://user-images.githubusercontent.com/9868626/113397124-d6a12b80-939c-11eb-9e37-72bd99ca0f09.png)

Device form factor:
Windows

Visual Studio Version:
![image](https://user-images.githubusercontent.com/9868626/113397462-634be980-939d-11eb-8c72-a48ec105508c.png)

**Additional context**
None.

**Comment by StephenLPeters** [comment]
@anawishnoff Is our documentation missing a step?

**Comment by StephenLPeters** [comment]
@Rand-Random can you provide a zip of you app as well?

**Comment by manodasanW** [comment]
@Rand-Random What version of the .NET 5 SDK do you have installed?  Can you update to the latest and that should get you the latest version of WinRT.Runtime that is needed.,

**Comment by Rand-Random** [comment]
Sorry for my late response, easter interfered.

@manodasanW 
![image](https://user-images.githubusercontent.com/9868626/113687653-dbc9e780-96c8-11eb-8d00-7daa98d95582.png)

5.0.4 (the latest) seems to be installed.

@StephenLPeters 
Here the requested Zip, as I mentioned earlier it is a newly created project.
[App5.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6263479/App5.zip)

**Comment by manodasanW** [comment]
@Rand-Random the .NET runtime installed is indeed recent (5.0.4).  But the .NET SDK installed is on 5.0.100 and I believe is the cause of your issue because WinRT.Runtime is not distributed in the .NET runtime but as part of the .NET SDK due to it is app local.  If you were to install an updated version of the .NET 5 SDK, your issue should go away.

**Comment by Rand-Random** [comment]
@manodasanW 
Oops, didn't know and apparently didn't read my screenshot good enough to notice it myself, that the SDK and runtime has different version numbers.

It is indeed as you say, after installing the latest SDK my newly created project can be built and run.

Though I am wondering why didn't an Visual Studio update install the latest SDK, do you know why?
Double checked the installer of Visual Studio and .NET SDK is installed
![image](https://user-images.githubusercontent.com/9868626/113838012-aee00800-978e-11eb-93c1-16540e228fd7.png)

Doesnt it automatically grab the latest .NET SDK with a new Visual Studio update, is this something I always have to do manually?

@StephenLPeters @anawishnoff
Maybe you want to add this step to the documentation.
Should I create a new issue for this on the [docs.microsoft.com github page](https://github.com/MicrosoftDocs/windows-uwp/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%2042aa9e2a-5cad-de4e-529e-661e3744159b%0A*%20Version%20Independent%20ID%3A%201b8ececa-8e30-ad26-7229-059f62f7868b%0A*%20Content%3A%20%5BGet%20started%20with%20Project%20Reunion%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fapps%2Fproject-reunion%2Fget-started-with-project-reunion)%0A*%20Content%20Source%3A%20%5Bhub%2Fapps%2Fproject-reunion%2Fget-started-with-project-reunion.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-uwp%2Fblob%2Fdocs%2Fhub%2Fapps%2Fproject-reunion%2Fget-started-with-project-reunion.md)%0A*%20Product%3A%20**reunion**%0A*%20Technology%3A%20****%0A*%20GitHub%20Login%3A%20%40mcleanbyron%0A*%20Microsoft%20Alias%3A%20**mcleans**)?

**Comment by anawishnoff** [comment]
@Rand-Random That's a good question. @manodasanW how does the .NET SDK usually get updated?

**Comment by Brouilles** [comment]
Same problem here.

**Comment by jsedlak** [comment]
> @Rand-Random That's a good question. @manodasanW how does the .NET SDK usually get updated?

You can manually install from dotnet.microsoft.com - https://dotnet.microsoft.com/download/visual-studio-sdks

I don't think I've seen .NET 5 SDK installed via the Visual Studio Installer.

**Comment by Rand-Random** [comment]
@manodasanW @anawishnoff 
Since a new version of the SDK was released, I am curious if there is any news regarding automatic updates, or if I am still required to manually install it?

**Comment by anawishnoff** [comment]
Hi @Rand-Random, I believe the easiest way to get the update is to manually[ install the latest .NET SDK](https://dotnet.microsoft.com/download/dotnet/5.0). You can also get the update by upgrading to the latest version of Visual Studio 2019 ([VS 16.9.5 stable](https://visualstudio.microsoft.com/vs/) or [VS 16.10 Preview 3](https://visualstudio.microsoft.com/vs/preview/)).

**Comment by Rand-Random** [comment]
@anawishnoff 
I will give the Visual Studio update a try, but not for next week, free time is planed.

But as I said in comment https://github.com/microsoft/microsoft-ui-xaml/issues/4722#issuecomment-814730412 previous Visual Studio Updates didn’t update the SDK, only updated the runtime.

Though I will trust your comment and give it another try.

**Comment by Rand-Random** [comment]
@anawishnoff 
Plans changed, and I didn't want to keep you waiting.
So I did the Visual Studio update and it again happened as I said it would happen only the .NET 5 Runtime got updated but not the SDK. Is it a Visual Studio bug, since you claimed it should update it?

Before the Visual Studio Update:
![image](https://user-images.githubusercontent.com/9868626/118102524-3269c600-b3d9-11eb-95df-deecab7777ac.png)


After the Visual Studio Update:
![image](https://user-images.githubusercontent.com/9868626/118102543-3ac20100-b3d9-11eb-9020-c1998409261e.png)


According to your statement I should have gotten the .NET 5 SKD 5.0.203 but it is still only 5.0.202.

**Comment by marcpopMSFT** [comment]
@joeloff can you point the customer to our directions on how to collect and share the setup logs?  16.9.5 should install the 5.0.203 SDK and it did for me yesterday when I updated.

**Comment by joeloff** [comment]
You can grab the tool from https://www.microsoft.com/en-us/download/details.aspx?id=12493

**Comment by Rand-Random** [comment]
@marcpopMSFT @joeloff 
Here the produced log file
[vslogs.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6474709/vslogs.zip)

**Comment by Rand-Random** [comment]
@anawishnoff @marcpopMSFT @joeloff 
Since another Visual Studio Update got released, I wondered if you would like me to do something before hand?
Or if I should just do the update like usually.

**Comment by joeloff** [comment]
In the screenshot it shows the SDKs resolving against Program Files (x86), but the logs show that the x64 copy of 5.0.203 was installed.

@Rand-Random can you open a command prompt and run "SET PATH" and share the output? I wonder if the x86 installation jumped to the front of the path, so dotnet.exe will resolve to it instead of the x64 copy.

**Comment by Rand-Random** [comment]
@joeloff 
(added line breaks after ;)

```
Path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;
c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;
C:\Program Files (x86)\dotnet\;
C:\Program Files\Microsoft VS Code\bin;
C:\Program Files\dotnet\;
C:\Program Files\TortoiseSVN\bin;
C:\Program Files\Git\cmd;
C:\Program Files (x86)\Plantronics\Spokes3G\;
C:\Users\rfa\AppData\Local\Microsoft\WindowsApps;
C:\Users\rfa\AppData\Local\GitHubDesktop\bin;
C:\Users\rfa\.dotnet\tools;
C:\rfa\Spark\spark-3.0.1-bin-hadoop2.7\bin;
C:\Program Files (x86)\NuGet
PATHEXT=.COM;
.EXE;
.BAT;
.CMD;
.VBS;
.VBE;
.JS;
.JSE;
.WSF;
.WSH;
.MSC

```

**Comment by joeloff** [comment]
Can you try editing the PATH variable and swapping ```C:\Program Files\dotnet\``` and ```C:\Program Files (x86)\dotnet\"? Once you've done that close and restart Visual Studio and/or any command prompts you used.

**Comment by Rand-Random** [comment]
@joeloff 
swaped and restarted pc, now should I do the visual studio update as usually?

```
Path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;
c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;
C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;
C:\Program Files\dotnet\;
C:\Program Files\Microsoft VS Code\bin;
C:\Program Files (x86)\dotnet\;
C:\Program Files\TortoiseSVN\bin;
C:\Program Files\Git\cmd;
C:\Program Files (x86)\Plantronics\Spokes3G\;
C:\Users\rfa\AppData\Local\Microsoft\WindowsApps;
C:\Users\rfa\AppData\Local\GitHubDesktop\bin;
C:\Users\rfa\.dotnet\tools;
C:\rfa\Spark\spark-3.0.1-bin-hadoop2.7\bin;
C:\Program Files (x86)\NuGet
PATHEXT=.COM;
.EXE;
.BAT;
.CMD;
.VBS;
.VBE;
.JS;
.JSE;
.WSF;
.WSH;
.MSC
```

**Comment by joeloff** [comment]
There's a known issue with the .NET host where the dotnet path values can get swapped around. You can probably go ahead and update Visual Studio. Did restoring the PATH variable fix your original problem?

**Comment by Rand-Random** [comment]
@joeloff 
If by "original problem" you mean the very very orignal problem with WinRT.Runtime version mismatch, than this problem was solved already in https://github.com/microsoft/microsoft-ui-xaml/issues/4722#issuecomment-814730412 by manually installing the SDK, if I remember correctly I installed both versions x86 and x64.
(Though I am not sure which version is actually needed)

The "only" remaining problem was why did I have to manually install the SDK for it to work, why didn't Visual Studio update the SDK.

I believe restoring the PATH would have solved the original problem as well.
Since, as @joeloff pointed out, that after I restored the PATH variable, the command `dotnet --info` displayed the latest version of the .NET SDK, so apparently Visual Studio did update the SDK but only the x64 bit version of it.

![image](https://user-images.githubusercontent.com/9868626/119109576-93208080-ba21-11eb-8082-336deaea9c76.png)
(Sorry about the german setup, hope the image is understandable)

You can see the last modified date in `Program Files` for the directory `5.0.203` of `05/13/2021`.
This is the same date as my previous comment where I claimed Visual Studio didn't install the latest SDK. https://github.com/microsoft/microsoft-ui-xaml/issues/4722#issuecomment-840419842

Should I get rid of the x86 version?

**Comment by joeloff** [comment]
Yes, you can remove the x86 version. Visual Studio will only install the SDK that matches the bitness of the underlying OS. It will however install both x86 and x64 runtimes. When you install two SDKs separately, you end up with two copies of the host, dotnet.exe. When the host is installed, it modifies the PATH to point to dotnet.exe. Installing x86/x64 SDKs means you end up with both on the PATH. And because of the underlying bug I mentioned, when you upgrade the SDKS it's possible for the ordering in the PATH to changes because it will uninstall/install new hosts.

**Comment by Rand-Random** [comment]
@joeloff 
Removed the x86 version as recommended and everything seem fine.

The latest Visual Studio update, I am a little behind on this one, also seemed to work as intended and updated the .net sdk to 5.0.301.

So the culprit all along was me installing x86 version at some point.

Thanks for all the help.
