### ISSUE TITLE
XamlReader.Load cannot find custom usercontrol

### ISSUE THREAD

**Issue by rick-palmsens** [microsoft/microsoft-ui-xaml#4723]
**Describe the bug**
I am converting a class library with controls from UWP to WinUI 3. In our code we create a `DataTemplate` by first generating a string and then passing it on to `XamlReader.Load`. This string references a `UserControl` from the same assembly. In UWP this works fine, but after switching to WinUI it is no longer able to find the `UserControl`.

**Steps to reproduce the bug**
1. Create a WinUI class library
2. Create a `UserControl`
3. Use `XamlReader` to create a `DataTemplate` that references to that `UserControl`, e.g:
```xaml
XamlReader.Load(
@"<DataTemplate xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation""
                xmlns:local=""using:MyLibrary.Controls"">
    <local:MyUserControl/>
</DataTemplate>");
```
4. Get an error

> WinRT originate error - 0x802B000A : 'The type 'MyUserControl' was not found. [Line: 3 Position: 6]'. 

**Expected behavior**
It should find the control like it did in UWP

**Version Info**
NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@alwu-msft and @RealTommyKlein FYI

**Comment by alwu-msft** [comment]
We only generate type information for custom types if either they have been marked with the [`Bindable`](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.data.bindableattribute?view=winui-3.0) attribute or they are used in markup (either the class library or the app consuming the class library). Can you confirm that in the WinUI version of your class library you're doing the same set of stuff as in the UWP version? That is, I'd expect that your UWP code is fulfilling at least one of the two aforementioned conditions, and the WinUI version needs to do the same.

**Comment by rick-palmsens** [comment]
@alwu-msft Adding the `[Bindable]` to the class does indeed seem to fix the error. This was not necessary with the UWP version of the application. I looked at all the references to the custom control and the only difference I can find is that it was included explicitly in the UWP .csproj:
```xml
<Compile Include="Controls\MyUserControl.cs" />
```

Other than that the code is the same.

**Comment by rick-palmsens** [comment]
After some more investigation it turns out that the error also occurs on UWP. But it only happens when the application is packaged. Since we are still in early development (and a UWP release package takes extremely long to compile) we usually run an unpackaged version. WinUI however cannot run without a package, so I'm guessing that is why the issue started showing up when we switched to WinUI.

**Comment by MartinZikmund** [comment]
It would be very helpful if the error message warned about `[Bindable]` being needed here
