### ISSUE TITLE
InfoBar's IconSource binding not updating

### ISSUE THREAD

**Issue by ismaelestalayo** [microsoft/microsoft-ui-xaml#4724]
**Describe the bug**

The `Glyph` attribute of the `FontIconSource` inside the `InfoBar` control does not seem to listen to updates.

To check it was not an issue in my end, I also applied the same binding inside the Content of the `InfoBar`, and that text did update with the new emoji while the Icon of the `InfoBar` stayed the same (it looks like if the binding was `OneTime`, because it only updates once with the first icon passed).

**Steps to reproduce the bug**
1. Create an `InfoBar` inside a `UserControl`, and set its content to bindings:
```xaml
<muxc:InfoBar
    Title="Test" IsOpen="True" Severity="Informational"
    MaxWidth="400" MinWidth="250" Padding="10">
    <muxc:InfoBar.Content>
        <TextBlock TextWrapping="WrapWholeWords">
            <Run Text="{x:Bind Message, Mode=OneWay, FallbackValue=''}"/>
            <Run Text="{x:Bind Icon, Mode=OneWay, FallbackValue=''}"/>
        </TextBlock>
    </muxc:InfoBar.Content>
    <muxc:InfoBar.IconSource>
        <muxc:FontIconSource FontFamily="Segoe UI Emoji" Glyph="{x:Bind Icon, Mode=OneWay}"/>
    </muxc:InfoBar.IconSource>
</muxc:InfoBar>
```
2. Set the `DependecyProperties` in code behind of the `UserControl`:
```cs
public static readonly DependencyProperty MessageProperty =
    DependencyProperty.Register(nameof(Message), typeof(string), typeof(string), null);

public static readonly DependencyProperty IconProperty =
    DependencyProperty.Register(nameof(Icon), typeof(string), typeof(string), null);

...


public string Icon {
    get => GetValue(IconProperty).ToString();
    set => SetValue(IconProperty, value);
}
```

**Expected behavior**
The `FontIconSource` should update its content (just as the `TextBlock` does)

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
Yeah... This is unfortunately to be expected.. the way IconSource's originally worked they did not push properties from them to the icons that were created from them..  I recently added some functionality to IconSource in this PR: https://github.com/microsoft/microsoft-ui-xaml/pull/4563 That makes it so that if you use the CreateIconElement() api on IconSource then changes to these properties will be pushed to the created Icons.  However we didn't update old usages of IconSource to use this new API because we were worried about compatability...  @MikeHillberg This really does appear like a bug, I wonder if we should just bite the bullet and update these despite the compat risk.
