### ISSUE TITLE
VisualTreeHelper.GetParent throws on Span inline

### ISSUE THREAD

**Issue by rozele** [microsoft/microsoft-ui-xaml#4729]
**Describe the bug**

If you attempt to call `VisualTreeHelper.GetParent(span)`, an exception is thrown.

**Steps to reproduce the bug**
1. Create a C# UWP Blank App
2. Paste the contents from https://gist.github.com/rozele/55cca25a38237ee449450b5d78650c11 into `MainPage.xaml.cs`
3. Click anywhere on the app to trigger crash

**Expected behavior**
I'd expect VisualTreeHelper to return the `TextBlock` parent in the best case, but in the worst case return null. In any case I'd expect it to not throw. Note that repeating this for a Hyperlink inline does return the TextBlock parent.

**Screenshots**

N/A

**Version Info**

NuGet package version: 

N/A

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |  Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This issue was discovered while implementing a module in react-native-windows. In react-native-windows, the `<Text>` component is implemented with TextBlock, Run, and Span. Span elements are used for nested `<Text>` components that may have their own styling or `onPress` handling for pointer events.

I encountered this while working on a module that displays a MenuFlyout when the `onPress` handler for the nested `<Text>` is called. The target view passed from `react-native-windows` is the Span, and I needed to get the parent `TextBlock` to attach the MenuFlyout to, so I tried VisualTreeHelper.

**Comment by StephenLPeters** [comment]
@codendone is this expected? I'm not familiar with how span works.

**Comment by codendone** [comment]
The current implementation of `VisualTreeHelper.GetParent` only supports a UIElement or a Hyperlink/ContentLink as a parameter. Any other type will throw an exception for HRESULT E_UNEXPECTED.

**Comment by rozele** [comment]
Fair enough.
