### ISSUE TITLE
Crash in app with TabView control

### ISSUE THREAD

**Issue by j0shuams** [microsoft/microsoft-ui-xaml#4733]
**Describe the bug**
In XamlControlsGallery, under "Navigation View" page, "TabView" control, go to the last control and try to drag one of the tabs to after another one. The app will hang then crash. 

**Steps to reproduce the bug**
Above should work, can provide XCG msix if need be.

**Expected behavior**
App doesn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/70237359/113471436-11dd4200-9411-11eb-9f50-162a4031028b.png)

**Version Info**
NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0] If you're seeing your issue in older previews, please try this release.

Desktop

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | yes    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Call stack
>	Microsoft.ui.xaml.dll!CInputServices::ObjectLeavingTree(CDependencyObject * object) Line 269	C++
 	Microsoft.ui.xaml.dll!CDependencyObject::LeaveImpl(CDependencyObject * pNamescopeOwner, LeaveParams params) Line 1305	C++
 	Microsoft.ui.xaml.dll!CUIElement::LeaveImpl(CDependencyObject * pNamescopeOwner, LeaveParams params) Line 1691	C++
 	Microsoft.ui.xaml.dll!CFrameworkElement::LeaveImpl(CDependencyObject * pNamescopeOwner, LeaveParams params) Line 2503	C++
 	Microsoft.ui.xaml.dll!CControl::LeaveImpl(CDependencyObject * pNamescopeOwner, LeaveParams params) Line 399	C++
 	Microsoft.ui.xaml.dll!CContentControl::LeaveImpl(CDependencyObject * pNamescopeOwner, LeaveParams params) Line 179	C++
 	Microsoft.ui.xaml.dll!CDependencyObject::Leave(CDependencyObject * pNamescopeOwner, LeaveParams params) Line 1184	C++
 	Microsoft.ui.xaml.dll!CDOCollection::ChildLeave(CDependencyObject * pChild, CDependencyObject * pNamescopeOwner, LeaveParams params, unsigned int fCanProcessEnterLeave) Line 388	C++
 	Microsoft.ui.xaml.dll!CDOCollection::RemoveAt(unsigned int nIndex) Line 758	C++
 	Microsoft.ui.xaml.dll!CItemCollection::RemoveAt(unsigned int nIndex) Line 107	C++
 	Microsoft.ui.xaml.dll!Collection_RemoveAt(CCollection * collection, unsigned int index) Line 1723	C++
 	Microsoft.ui.xaml.dll!DirectUI::PresentationFrameworkCollectionTemplateBase<IInspectable *>::RemoveAt(unsigned int index) Line 646	C++
 	Microsoft.ui.xaml.dll!DirectUI::ItemCollection::RemoveAt(unsigned int index) Line 201	C++
 	Microsoft.ui.xaml.dll!DirectUI::ListViewBase::ReorderItemsTo(std::vector<unsigned int,std::allocator<unsigned int>> * pReorderItemIndexes, int insertIndex, int * pTrackedIndex1, int * pTrackedIndex2) Line 1506	C++
 	Microsoft.ui.xaml.dll!DirectUI::ListViewBase::OnReorderDrop(ABI::Windows::Foundation::Point dropPoint) Line 1313	C++
 	Microsoft.ui.xaml.dll!DirectUI::ListViewBase::OnDrop(ABI::Microsoft::UI::Xaml::IDragEventArgs * pArgs) Line 1146	C++
 	Microsoft.UI.Xaml.Controls.dll!winrt::impl::consume_Microsoft_UI_Xaml_Controls_IControlOverrides<winrt::Microsoft::UI::Xaml::Controls::IControlOverrides>::OnDrop(const winrt::Microsoft::UI::Xaml::DragEventArgs & e) Line 5114	C++
 	Microsoft.UI.Xaml.Controls.dll!winrt::Microsoft::UI::Xaml::Controls::IControlOverridesT<TabViewListView>::OnDrop(const winrt::Microsoft::UI::Xaml::DragEventArgs & e) Line 72175	C++
 	Microsoft.UI.Xaml.Controls.dll!winrt::impl::produce<TabViewListView,winrt::Microsoft::UI::Xaml::Controls::IControlOverrides>::OnDrop(void * e) Line 34307	C++
 	Microsoft.ui.xaml.dll!DirectUI::ControlGenerated::OnDropProtected(ABI::Microsoft::UI::Xaml::IDragEventArgs * pE) Line 760	C++
 	Microsoft.ui.xaml.dll!DirectUI::Control::FireEvent(KnownEventIndex nDelegate, DirectUI::DependencyObject * pSender, IInspectable * pArgs) Line 450	C++
 	Microsoft.ui.xaml.dll!DirectUI::DXamlCore::FireEvent(CDependencyObject * pCoreListener, KnownEventIndex eventId, CDependencyObject * pCoreSender, CEventArgs * pCoreArgs, unsigned int flags) Line 1934	C++
 	Microsoft.ui.xaml.dll!AgCoreCallbacks::FireEvent(CDependencyObject * pListener, KnownEventIndex eventId, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 86	C++

**Comment by StephenLPeters** [comment]
Looks like the repro might take dragging the tab multiple times.

**Comment by StephenLPeters** [comment]
Does not repro with winui2

**Comment by Noemata** [comment]
@StephenLPeters , TabView will eventually crash any UWP app as well.  You just need the right test jig to surface the problem sooner.

Have a look here:

https://github.com/Noemata/RosettaNavigation
