### ISSUE TITLE
ScrollViewer does not anchor correctly on window resizing

### ISSUE THREAD

**Issue by rozele** [microsoft/microsoft-ui-xaml#4734]
**Describe the bug**
The WUX ScrollViewer implements IScrollAnchorProvider. It has a property, VerticalAnchorRatio, that when set to 1.0 implements anchoring at the bottom edge of the ScrollViewer. When VerticalAnchorRatio == 1.0 and the views inside the ScrollViewer have CanBeScrollAnchor == true, resizing the window results in the content "jumping" away from the bottom edge.
 
**Steps to reproduce the bug**
1. Clone https://github.com/rozele/ScrollViewerAnchorPoint
2. Check out the `repro` branch (https://github.com/rozele/ScrollViewerAnchorPoint/tree/repro)
3. Run the app
4. Click on the rows in the ScrollViewer to switch CanBeScrollAnchor to true
5. Resize the window and observe the bug

**Expected behavior**
When CanBeScrollAnchor == 1.0, the view port should remain anchored at the bottom edge when the window resizes.

**Screenshots**

https://user-images.githubusercontent.com/1106239/113478450-e3825580-9456-11eb-8ea2-40ad27f190db.mp4

**Version Info**

NuGet package version: N/A

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@RBrid can you lend your expertise? :)
