### ISSUE TITLE
Discussion: Please indicate clear next steps when issues are closed

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#4736]
# Discussion: Set a policy for providing clear next steps  or reasons when issues are closed.

When an issue is closed there should be clear next steps provided.
(This is a general point but based on actual experience.)

As someone searching for a solution to a problem and who finds details of the same problem listed in an issue, if that issue is closed it should point me to the next steps.

- If an issue is closed because something has been implemented and will be available in a future release, the version it will be available in should be clearly stated. This will allow me to know when I can update to get a fix, and/or what new version I need to reference.

- If an issue is closed and there is a workaround available, detailed steps explaining how to implement the workaround should be provided. It's not sufficient to say "as a workaround do X" because a person may not know "how to do X". It should also not be left up to someone else to document the workaround. _[example](https://github.com/microsoft/microsoft-ui-xaml/issues/4719#issuecomment-812638998)_

- If an issue is closed because it is a duplicate, a reference to the other issue should be included. This will allow me to go to the other issue to find more information, and hopefully a resolution to my problem.

- If an issue is closed as out-of-scope or as something that won't be fixed, details of why should be included. This will help me better understand the goals and plans of the team making these decisions.

I'm sure there are more examples that need to be added here and I'd welcome contributions to this list...

**Comment by thomasclaudiushuber** [comment]
Hey @mrlacey , great write up. 

Regarding workarounds:
I think it's also part of the responsibility of the issue creator to provide details. Maybe it's even full responsibility of the issue creator. People are busy on different things, so I think writing "As a workaround do X" is ok and better than nothing. But then the issue creator or another person, like on the linked issue @riverar, should provide the detailed steps of a valid workaround. In the linked issue, I also tried to provide more info why it was working for me on one of my machines, while it failed on another one.

I think in the end, it all comes down to a single point: If you search for a problem, and if you find a closed issue for that problem, you should easily be able to find out if there is a solution available, and you should get detailed steps. I totally agree to this.

But I can imagine that this is a lot of work, especially for issues that are fixed already and just wait for an update to be rolled out. I'm not sure if a policy makes sense, but at least we could have a kind of best practice document for issues.

But as mentioned, **I would mention to put the responsibility on the issue creator. This scales**. As an issue creator, I can add details on the issues that I created, but maybe the WinUI team can not add details to all the issues they close, as this is a by far bigger number.

This means: My recommendation would be that issue creators add details to the issue and confirm workarounds, step by step guidelines etc., if they're not provided in a sufficient way already. I think [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/4719) that you linked is a good example that shows how I created it, you and @riverar confirmed the problem with more details, @angelazhangmsft gave a hint, @riverar provided the details for a workaround, and I as an issue creator provided the info why it worked on one of my machines. If we wouldn't get it working, @angelazhangmsft would have to provide more details, but as we got it working, to me this was totally fine how it was done.

So, maybe instead of pushing more bureaucracy on the WinUI team, we should try to push more responsibility on issue creators, as this is where it scales very well. But I think a policy is hard, I would prefer a recommendation/best practice doc.

**Comment by mrlacey** [comment]
@thomasclaudiushuber some good input. thanks.
Yes, I think "best practice" rather than "policy" may be better but I wanted more than to say "this is a nice idea" and try and encourage (enforce?) adoption.
Also, yes, this applies more widely than just this repo/project.

Regarding the person opening an issue:

1. Yes, it would be good to mention any known workarounds when opening an issue.
2. However, I do not think it should be their responsibility to document discovered workarounds (or any other solutions)


Here's why:

- The person who opened the issue may not have enough information to fully document a workaround.
- Someone with more knowledge still needs to verify that the workaround is sufficient and adequately comprehensive.
- The person from the team who says there is a workaround must, at that point have verified that the workaround works. They have all the information at that point and know all the steps required. Putting (copying) that into an issue should not be a considerable amount of effort. If documenting a workaround is complicated, then hoping the OP can work it out and document it appropriately is unlikely.
- The core team of a project (and enthusiastic contributors) should have the goal of ensuring that use (including workarounds) is well documented. If they don't take this approach it will be easy to slip into the mentality seen in many other projects where documentation is minimal and the team expects users to work it out for themselves or from code. A lack of good documentation is a barrier to adoption, especially among less experienced developers, and I expect WinUI wants all the adoption it can get. Also, relying on the community to provide documentation and fill in the gaps that take time, or the core team doesn't want to do, rarely (as I've seen on other projects) leads to sufficient, well-maintained documentation, and a large number of motivated external contributors. _(Open-source is not an excuse to outsource front-line support to "the community". When the community are able to help each other it's a bonus, it shouldn't be the default.)_
- If the issue identifies a known bug that will be fixed at a later time, having a well-documented work-around in the issue may help the person who eventually works to fix the bug. Hopefully, the person stating that there is a workaround wants to give the best, most complete information to their teammate or fellow contributor to save them time repeating any investigation already done. The workaround may even need to become part of the official fix.
- Adding a vague description of a workaround doesn't help other people who look at the issue and can't work out the workaround for themselves. It's unlikely the person opening an issue is the only one who will encounter the problem. They should look to the project team for complete answers and not be reliant on the people opening issues.
- **Requiring more of a person opening an issue will lead to fewer issues being opened.**

Getting issues raised is a problem across all of open-source. Most people encountering an error will not raise an issue.
Getting good issues, with a clear description/explanation, detailed minimal repro steps, and all required information is even harder.
To then require further responsibility after opening an issue will further discourage the opening of issues.

How would a person opening an issue even know that they are assuming further responsibilities? 
Will we start seeing disclaimers at the bottom of issue templates? "By opening this issue I understand that I will ......"



I know for certain that if opening an issue meant making myself responsible for documenting workarounds and tracking when/where fixes were available it would mean that I would open fewer issues.
Being open-source means I can contribute. It shouldn't mean I have to.
Anything that discourages opening issues is a bad thing. It means fewer bugs are reported and features suggested. Over time this leads to a less stable product and one that fails to fully meet the needs of the people using it.




**Scale is a _possible_ problem.**
I don't propose retrospectively commenting on all closed issues. This could be something applied going forward.
I'm not sure that communicating what the workaround is when stating that there is a workaround, is a lot of effort. As noted above, they've already (hopefully) done the work to verify the workaround before saying there is one.

Providing a general/vague description of a workaround isn't likely to be the end of the work for that person as they'd need to verify that the workaround provided by the OP (or another contributor) is adequate and doesn't have any other side effects. Having the person come back later to review this incurs a switching cost and requires time to refamiliarize themselves with the issue.
Dealing with everything when they first identify the workaround shows ownership of the problem and a desire to help the person reporting the issue. Simply saying "as a workaround do X" can easily become a way to do the minimal amount while still claiming to be helpful. (I've seen this in other projects 😢)

_I'm not saying a desire to do the minimum amount of work is always the case or that it applies to the issues linked above, but I have seen several cases where issues are treated this way and over time the people making these responses start to push the project more in the direction of what's easiest or most interesting for them rather than focusing on what's best for people using the software.
In contrast, I've also known multiple teams successfully reinforce the idea that it benefits the project over the short and long-term to fully support the people using the software by ensuring that any response to the people using the product is as comprehensive as possible. (It's better for everyone to answer questions now than to have a lot of back and forth discussion.)_


Yes, having the person opening the issue do more of the work would scale, but as I've shown above this is unlikely to happen and not in the best interest of the project as a whole.


Tooling may be able to help minimize the amount of work required to document some of these issues. For example:
- Where an issue is fixed, if the issue is tagged in the PR/commit for the fix, the issue could automatically be notified with the build/release that includes the fix.
- If an issue is raised for a bug, the fix will likely include new tests. By connecting the issue to the PR/commit that included the fix it will also be possible to add direct links to the newly added tests in the assumption/hope that they show how to use the fix.

_Sadly, I can't imagine a way to automatically point people to workarounds. yet..._

**Comment by StephenLPeters** [comment]
Great discussion! @gabbybilka and @ryandemopoulos FYI

**Comment by nickrandolph** [comment]
Just to add to this discussion - my view is that closing and item should only be done when the item has actually shipped to production. I understand why the team might want to close issues, to reduce the overall issue count and make it easier to track what's still to be worked on but closing an issue prior to it being shipped leads to the issues @mrlacey raised about not knowing which version a fix/feature has been released in.
I would like to see issues closed once the resolution (fix or feature) has been shipped to production. This includes keeping issues open even if there's a valid workaround, if, there is a resolution being worked on. If the workaround is the resolution, then I think it's fine to close the issue (with clear instructions or link to the workaround).
