### ISSUE TITLE
Is there any event hooks in WinUI3 related to app close and app pre-uninstall?

### ISSUE THREAD

**Issue by gscheartA** [microsoft/microsoft-ui-xaml#4738]
I am developing a desktop app using WinUI3. I need add some event hooks to let me execute some code before app is closed and app is uninstalled. I could not find some suitable API in UWP reference, I don't know if it is supported in WinUI3? Thank you for your kindly answer.

**Comment by StephenLPeters** [comment]
quick google search found me https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.window.closed?view=winrt-19041 and https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow.closerequested?view=winrt-19041 but I suspect you already know about those. With win32 you could use the wm_close message in the winproc, but for UWP I'm not sure what else is available.  @MikeHillberg @Austin-Lamb do you know?
