### ISSUE TITLE
XAML Path geometry parsing problem with relative point

### ISSUE THREAD

**Issue by Meloman19** [microsoft/microsoft-ui-xaml#4741]
**Describe the bug**
There is a problem with parsing the SVG path if relative coordinates are used.

**Steps to reproduce the bug**
Use next string as data of Path:
`m 6 6 h 5 v 5 H 6 Z m 8 0 h 5 v 5 H 14 Z M 0 0 V 17 H 25 V 0 Z m 3 3 H 22 V 14 H 3 Z`
or
```
<Path Data="m 6 6 h 5 v 5 H 6 Z m 8 0 h 5 v 5 H 14 Z M 0 0 V 17 H 25 V 0 Z m 3 3 H 22 V 14 H 3 Z"
      Stretch="Uniform"
      Width="300"
      Height="300"
      Fill="Black"/>
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/23280622/113587520-91e4f100-9637-11eb-8acb-237450ff98dc.png)

**Screenshots**
What I've got:
![image](https://user-images.githubusercontent.com/23280622/113588212-834b0980-9638-11eb-9376-c1fa77d3be9a.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0]

**Additional context**
If I convert coordinates to absolute, then it will be displayed correctly everywhere.
Absolute:
`M 6 6 H 11 V 11 H 6 Z M 14 6 H 19 V 11 H 14 Z M 0 0 V 17 H 25 V 0 Z M 3 3 H 22 V 14 H 3 Z`

What I've got:
![image](https://user-images.githubusercontent.com/23280622/113588859-55b29000-9639-11eb-9917-3a4b7e0e1ed2.png)

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by nCastle1** [comment]
Possibly the same issue as https://github.com/microsoft/microsoft-ui-xaml/issues/3077

**Comment by Meloman19** [comment]
@nCastle1 Yeah. Same issue. But bug is not in the rendering, but in the parsing.
You can try 
`M 8.023 1.023 L 0.023 5.523 L 8.023 10.023 L 16.023 5.523 Z M 2.063 5.523 L 8.023 2.171 L 13.983 5.523 L 8.023 8.876 Z M 16.023 8.523 L 8.023 13.023 L 0.023 8.523 L 1.043 7.95 L 8.023 11.876 L 15.003 7.95 Z M 8.023 14.876 L 15.003 10.95 L 16.023 11.523 L 8.109 15.975 A 0.175 0.175 0 0 1 7.938 15.975 L 0.023 11.523 L 1.043 10.95 Z`
instead
`M 8.023 1.023 l -8 4.5 8 4.5 8-4.5 z m -5.96 4.5 l 5.96 -3.352 5.96 3.352 -5.96 3.353 z m 13.96 3 l -8 4.5 -8 -4.5 1.02 -.573 6.98 3.926 6.98 -3.926 z m -8 6.353 l 6.98 -3.926 1.02 .573 -7.914 4.452 a .175 .175 0 0 1 -.171 0 L .023 11.523 l 1.02-.573 z`
And get right PathGeometry.

@StephenLPeters @codendone I dug a little deeper and I found this.
PathFigures for string with relative coordinates: `m 6 6 h 5 v 5 H 6 Z m 8 0 h 5 v 5 H 14 Z M 0 0 V 17 H 25 V 0 Z m 3 3 H 22 V 14 H 3 Z`
<details>
  <summary>WPF Parse result</summary>

```
IsClosed: True | IsFilled True | StartPoint: 6;6
      PolyLineSegment: 11;6 11;11 6;11 

IsClosed: True | IsFilled True | StartPoint: 14;6
      PolyLineSegment: 19;6 19;11 14;11 

IsClosed: True | IsFilled True | StartPoint: 0;0
      PolyLineSegment: 0;17 25;17 25;0 

IsClosed: True | IsFilled True | StartPoint: 3;3
      PolyLineSegment: 22;3 22;14 3;14 
```
</details>

<details>
  <summary>WinUI 3 Parse result</summary>

```
IsClosed: True | IsFilled True | StartPoint: 6;6
      LineSegment: 11;6
      LineSegment: 11;11
      LineSegment: 6;11

IsClosed: True | IsFilled True | StartPoint: 14;11
      LineSegment: 19;11
      LineSegment: 19;16
      LineSegment: 14;16

IsClosed: True | IsFilled True | StartPoint: 0;0
      LineSegment: 0;17
      LineSegment: 25;17
      LineSegment: 25;0

IsClosed: True | IsFilled True | StartPoint: 28;3
      LineSegment: 22;3
      LineSegment: 22;14
      LineSegment: 3;14
```
</details>

Please note that 2 and 4 PathFigures has different result. _Don't mind the type of segment._
For example second PathFigure:
|  | WPF | WinUI |
| ------------- | ------------- | ------------- |
| StartPoint | 14; 6  | 14; 11  |
| Point | 19; 6 | 19; 11 |
| Point | 19; 11 | 19; 16 |
| Point | 14; 11 | 14; 16 |

**But for absolute**: `M 6 6 H 11 V 11 H 6 Z M 14 6 H 19 V 11 H 14 Z M 0 0 V 17 H 25 V 0 Z M 3 3 H 22 V 14 H 3 Z`
<details>
  <summary>WPF Parse result</summary>

```
IsClosed: True | IsFilled True | StartPoint: 6;6
      PolyLineSegment: 11;6 11;11 6;11 

IsClosed: True | IsFilled True | StartPoint: 14;6
      PolyLineSegment: 19;6 19;11 14;11 

IsClosed: True | IsFilled True | StartPoint: 0;0
      PolyLineSegment: 0;17 25;17 25;0 

IsClosed: True | IsFilled True | StartPoint: 3;3
      PolyLineSegment: 22;3 22;14 3;14 
```
</details>

<details>
  <summary>WinUI 3 Parse result</summary>

```
IsClosed: True | IsFilled True | StartPoint: 6;6
      LineSegment: 11;6
      LineSegment: 11;11
      LineSegment: 6;11

IsClosed: True | IsFilled True | StartPoint: 14;6
      LineSegment: 19;6
      LineSegment: 19;11
      LineSegment: 14;11

IsClosed: True | IsFilled True | StartPoint: 0;0
      LineSegment: 0;17
      LineSegment: 25;17
      LineSegment: 25;0

IsClosed: True | IsFilled True | StartPoint: 3;3
      LineSegment: 22;3
      LineSegment: 22;14
      LineSegment: 3;14
```
</details>


Second PathFigure:
|  | WPF | WinUI |
| ------------- | ------------- | ------------- |
| StartPoint | 14; 6  | 14; 6  |
| Point | 19; 6 | 19; 6 |
| Point | 19; 11 | 19; 11 |
| Point | 14; 11 | 14; 11 |

As you can see WPF has same parsing result in both cases. But WinUI has parsing issue with relative points.
