### ISSUE TITLE
Source Generators fail in WinUI 3 projects because Csc is invoked with AnalyzerConfigFiles #52306

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#4744]
Copied from https://github.com/dotnet/roslyn/issues/52306. See follow-up comments in that issue where [it is indicated this would be a better place to put it](https://github.com/dotnet/roslyn/issues/52306#issuecomment-812751696). ([Or maybe not?](https://github.com/dotnet/roslyn/issues/52306#issuecomment-812755043))

**Describe the bug**

A project reunion project fails to build when it contains code that relies on a Source Generator in any of the XAML code-behind files.

**Steps to reproduce the bug**

(based on @dotMorten's report https://github.com/microsoft/CsWin32/issues/219#issuecomment-811272354

[Minimal repro solution](https://github.com/microsoft/CsWin32/files/6238327/App39.zip)

Or manual steps:

Install Project Reunion Project Templates: https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion
Create a new Blank App, Packaged (WinUI 3 in Desktop) project.
Install the Microsoft.Windows.CsWin32 nuget package (0.1.422-beta)
Add NativeMethods.txt and some interop methods to it.
Open MainWindow.xaml.cs, and in the constructor add a pinvoke method call.
Compile
Observe errors in the error list
![image](https://user-images.githubusercontent.com/1378165/113461086-0158a780-93d0-11eb-93b8-54e9e50421d4.png)
Using VS16.10.p1

**Expected behavior**

The build is successful.

**Analysis**

Examining the build log I've found the problem:
The `XamlPreCompile` target as defined in `MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets` invokes the `Csc` task but omits `AnalyzerConfigFiles` that is normally passed in. As a result, the CsWin32 source generator is not getting the info it needs to generate the APIs referenced in the XAML code-behind.

**Screenshots**

The `CoreCompile` target's invocation of Csc:
image
![image](https://user-images.githubusercontent.com/1378165/113461115-1f260c80-93d0-11eb-9ec2-b0fe2861dc38.png)

`XamlPreCompile` target's invocation of Csc:
image
![image](https://user-images.githubusercontent.com/1378165/113461118-251bed80-93d0-11eb-9174-dc97984c541b.png)

**Comment by StephenLPeters** [comment]
Thanks for all the investigation!! :) @RealTommyKlein and @alwu-msft FYI

**Comment by abhi-msft** [comment]
Do we have any resolution for this? I am using 0.8 and still facing the same issue.

**Comment by agc93** [comment]
Is there any update or workaround for this? 

One of the big advertised features of WinUI 3 was that is supports the latest .NET and would be able to use all the latest .NET 5 features, but source generators are a complete non-starter it seems.

**Comment by Marv51** [comment]
I guess the somewhat obvious workaround is to add the source generator reference to a class library, which you then reference from your WinUI project.

For example my app has a class library called MyApp.CsWin32 which is basically empty except for the CsWin32 nuget reference. (Of course the generator needs to create public types in that case. To do that for CsWin32 you need to set `"public": true` in your NativeMethods.json.

**Comment by RealTommyKlein** [comment]
I believe this was fixed with dotnet/msbuild#6438 - I can repro the issue on Visual Studio 16.9, but not 16.11.1.  @agc93 are you still hitting this with Visual Studio 16.11.1?

**Comment by agc93** [comment]
@RealTommyKlein I am still running into it but I'm on 16.11.0 Preview 3. I'll try again with the non-Preview bits.
