### ISSUE TITLE
CalendarDatePicker throws InvalidCastException when setting Value property

### ISSUE THREAD

**Issue by jasonjtyler** [microsoft/microsoft-ui-xaml#4750]
**Describe the bug**
Setting the Value property in code behind on a CalendarDatePicker results in an InvalidCastException.

**Steps to reproduce the bug**
1. Create a named CalendarDatePicker in a XAML file.
2. In the code behind, set the Value property of the CalendarDatePicker  to anything.

**Expected behavior**
I expected to be able to set the Value property in code behind as a way of initializing the control.

**Screenshots**
![image](https://user-images.githubusercontent.com/2371501/113652771-44717f80-9649-11eb-95a3-fd9c46ed1047.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@Scottj1s This seems like a CsWinrt issue, do you agree?

**Comment by thomasclaudiushuber** [comment]
@StephenLPeters I was not asked, but I agree. :) I will look into this today, as I got some experience with C#/WinRT and DatePicker (With solving this issue #4719 ). 

As C#/WinRT is delivered with the .NET SDK, maybe we should adjust the template for issues on this repo to include a "dotnet --list-sdks" result.

@jasonjtyler Could you run "dotnet --list-sdks" on the command line and post the installed SDKs here?

**Comment by thomasclaudiushuber** [comment]
Ok, it is C#/WinRT related.

Reproducable with **.NET SDK 5.0.201**
Solved with **.NET SDK 5.0.202**

Issue can be closed.

@jasonjtyler Please go to https://dotnet.microsoft.com/download and download and install the latest .NET SDK for .NET 5.0 (you'll get .NET SDK 5.0.202, you can verify this after installation by running "dotnet --list-sdks" on the commandline). 
After the installation, you need to restart Visual Studio. Then run the app again, and it should work. 

More details: The .NET SDK delivers the C#/WinRT, which is a projection of the WinRT APIs to C#. There was an interface mismatch in the older version that got fixed now. You find also more details about C#/WinRT in the #4719 issue.

**Comment by jasonjtyler** [comment]
Oops. I should have thought to update the SDK. That was sort of out of sight, out of mind to me. I was more focused on the NuGet package versions. Updating to 5.0.202 did resolve the issue, thank you very much!
