### ISSUE TITLE
Question: WinUI and Third Party WinSock based library

### ISSUE THREAD

**Issue by A-ndre-S** [microsoft/microsoft-ui-xaml#4755]
Hi to all,

I'm trying to understand why Beckhoff's TcADS library (ADS-DLL) doesn't work with WinUI. I've waited for the production release to see if it may solve my issue but it not.
The library i'm talking about is used to communicate with Beckhoff (https://infosys.beckhoff.com/english.php?content=../content/1033/tcadscommon/html/tcadscommon_intro.htm&id=) devices using a protocol based on TCP/IP and it's based on WinSock.
To use this library the user must firstly open a port to communicate in this protocol using the library function AdsPortOpen() but i always get 0 as a result, meaning that it has failed.
I don't expect miracles, i'm not an expert and i was just wondering if somebody has faced the same problem and knows how to fix it. I don't even know if this is the right place to ask.

p.s. Beckhoff customer care have also indicated me this project https://github.com/Beckhoff/ADS 

Thank you very much for reading this far,
Andre

**Comment by jschwizer99** [comment]
Hi Andre,
Did you configure the network capabilities in your `Package.appxmanifest`? You may need one or several of the capabilities `Internet (Client and Server)`, `Internet(Client)`, `Private Network (Client and Server)` depending on the used socket functionality. I'm running a web server within the WinUI which works fine.

**Comment by A-ndre-S** [comment]
> 
> 
> Hi Andre,
> Did you configure the network capabilities in your `Package.appxmanifest`? You may need one or several of the capabilities `Internet (Client and Server)`, `Internet(Client)`, `Private Network (Client and Server)` depending on the used socket functionality. I'm running a web server within the WinUI which works fine.

Hi jschwizer99,
Unfortunately i've already tried with that but didn't worked
Thank you!

**Comment by StephenLPeters** [comment]
@ryandemopoulos or @anawishnoff FYI

**Comment by A-ndre-S** [comment]
To who can further help:

This library is used to create a communication with a router that is running on windows.
Trying to use this library with a template WinUI "Blank App, Packaged (WinUI 3 in Desktop)" will fail.
Using it in a "MFC App" will work.
Using it in a "Windows Desktop Application (C++/WinRT)" will work. 
The latter application is a just a call to wWinMain without any UI, but is WinRT so i can exclude that the problem is using WinRT instead of Win32 APIs.
I suspect that having the WinUI app packed may result in having some residual sandbox limitations that will not permit to the app to communicate with the background-running router. Have anybody some informations/suggestions/thoughts/encouragements?
Thanks in advance,
Andre

**Comment by alfred-png** [comment]
It seems to me that the same is true for ZeroMQ library. When I include the dynamic version of ZeroMQ (static doesn't compile) in a WinUI Windows Runtime Component, the Windows Runtime Classes are no longer registered and the program fails at runtime.
Can anybody help?
Thank you in advance!
Best regards
Alfred
