### ISSUE TITLE
NavigationView flickering of Reveal Effect

### ISSUE THREAD

**Issue by strathdeek** [microsoft/microsoft-ui-xaml#4756]
**Describe the bug**
On release builds of my app on certain hardware I am experiencing a persistent flickering of the Reveal Effect of the NavigationView. I have been unable to reproduce the problem on my development hardware, however it is apparently occurring with many of the clients laptops. The effect is best shown with the videos linked in the screenshots section

**Steps to reproduce the bug**

1. Open the app in a release build on certain hardware
2. Observe the navigation menu on the left of the screen

**Expected behavior**
The navigation bar should behave normally, with the reveal effect only occurring as the user hovers over the menu.

**Actual behavior**
The navigation view is rapidly and erratically firing a reveal effect, creating a flicker effect

**Screenshots**
See video's saved in google drive:
[Video 1](https://drive.google.com/file/d/1W4c-E05YUqqm-j2CqCWqHUV9QjNOsj3Q/view?usp=sharing)
[Video 2](https://drive.google.com/file/d/1ZT252xaEfW_3J6FxZxzIZ1EeFe4I3Xlt/view?usp=sharing) 
[Video 3](https://drive.google.com/file/d/1fKOhxs8PL5PLIgzOJ8SOX_SdMJhPZSdj/view?usp=sharing)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@jevansaks can you take a look at the videos (2 and 3 especially).

**Comment by jevansaks** [comment]
Looks like a problem with HostBackdropBrush (used by Acrylic). @strathdeek what version of the OS and graphics card do you have?

@StephenLPeters we'll need someone from composition team to take a look at this.

**Comment by strathdeek** [comment]
![Screenshot 2021-04-08 at 17 40 51](https://user-images.githubusercontent.com/24235448/114056138-a4f2fd80-9891-11eb-8f4a-5dd8c420ff5b.png)

@jevansaks Thanks for quick feedback! The windows version is 1909 Build 18363.1379 (see screenshot above). I believe the graphics card is an Intel UHD Graphics 620.

Do you have any suggestions for workarounds in the meantime?

**Comment by jevansaks** [comment]
Do you see it in any other apps in the system that use acrylic, like Settings or Calculator or Xaml Controls Gallery?

**Comment by strathdeek** [comment]
No, we tested settings, calculator, etc.. and we were unable to reproduce the flickering.
