### ISSUE TITLE
WebView exhibits small memory leak when used with Navigation Frame.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#4758]
**Describe the bug**
WebView control exhibits a small memory leak when used with Navigation Frame.

**Steps to reproduce the bug**
1. Go to this repo: https://github.com/Noemata/RosettaNavigation
2. Build WebViewUwp1 project.
3. Run WebViewUwp1 app.
4. Observe reported leak when NavigationCacheMode = NavigationCacheMode.Disabled (default)

**Expected behavior**
No memory leak.

**Screenshots**
n/a

**Version Info**

NuGet package version: 
n/a

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
!!Warning!! if you do decide to try the WebViewWinUI1 sample in this repo, you may experience a seizure if you have photosensitive epilepsy.

The WebViewWinUI1 sample also has a small leak when NavigationCacheMode = NavigationCacheMode.Disabled.

**Comment by StephenLPeters** [comment]
Could be the cswinrt leak @Scottj1s

**Comment by Noemata** [comment]
@StephenLPeters , this looks to be something different.  It's a rather small leak.  The others are significantly larger in comparison.

**Comment by Noemata** [comment]
Also, you may want to take note of the performance gap highlighted by these samples when compared to UWP.  It is significant.
