### ISSUE TITLE
[WinUI 2.6 Preview] Release mode crash caused by NavigationView ItemsRepeater

### ISSUE THREAD

**Issue by duke7553** [microsoft/microsoft-ui-xaml#4759]
**Describe the bug**
After upgrading to the WinUI v2.6 preview, my UWP app crashes at runtime only when compiled in release mode. The crash is hard to debug this way, but I've attached the stack trace. The stack trace indicates the issue lies somewhere in NavigationView's ItemsRepeater FlowLayout. 

**Steps to reproduce the bug**

1. Upgrade a UWP app with a WinUI NavigationView to v2.6-preview.
2. Build it for release mode
3. Observe crash at runtime

**Expected behavior**
ItemsRepeater shouldn't be problematic in the MUX NavigationView, and it should function without crashing just like it does when compiled for debug mode builds. 

**Version Info**

NuGet package version: Microsoft.WinUI 2.6.0-prerelease.210405001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21354)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes|
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

[StackTrace.txt](https://github.com/microsoft/microsoft-ui-xaml/files/6275193/StackTrace.txt)

Removing the reference to our DataTemplateSelector from the markup produced the same crash.

**Comment by StephenLPeters** [comment]
@ranjeshj I think this needs to be fixed for 2.6.   @ojhad thoughts?

**Comment by StephenLPeters** [comment]
@chingucoding I think I remember you looking at flow layout in the past, does this ring any bells?

**Comment by StephenLPeters** [comment]
@duke7553 are you putting custom types into your navigationview items?

**Comment by duke7553** [comment]
@StephenLPeters We're using a DataTemplateSelector (which it still crashes in release even when this isn't set).

We do have various custom types which act as the model for each item in their DataTemplate. One of them is LocationItem:

```
<DataTemplate x:Key="LocationNavItem" x:DataType="local2:LocationItem">
                <muxc:NavigationViewItem
                    AllowDrop="True"
                    BorderThickness="0.8"
                    CanDrag="False"
                    Content="{x:Bind Text}"
                    DataContext="{x:Bind}"
                    DragEnter="NavigationViewItem_DragEnter"
                    DragLeave="NavigationViewItem_DragLeave"
                    DragOver="NavigationViewLocationItem_DragOver"
                    DragStarting="NavigationViewItem_DragStarting"
                    Drop="NavigationViewLocationItem_Drop"
                    IsExpanded="{x:Bind IsExpanded, Mode=TwoWay}"
                    IsRightTapEnabled="True"
                    MenuItemsSource="{x:Bind ChildItems}"
                    RightTapped="NavigationViewLocationItem_RightTapped"
                    SelectsOnInvoked="{x:Bind SelectsOnInvoked}"
                    Tag="{x:Bind Path}"
                    ToolTipService.ToolTip="{x:Bind HoverDisplayText}">
                    <muxc:NavigationViewItem.Icon>
                        <muxc:ImageIcon Source="{x:Bind Icon}"/>
                    </muxc:NavigationViewItem.Icon>
                </muxc:NavigationViewItem>
            </DataTemplate>
```

Example codebehind:
```
public class LocationItem : ObservableObject, INavigationControlItem
    {
        private string path;
        public ObservableCollection<INavigationControlItem> ChildItems { get; set; }
        public FontFamily Font { get; set; } = new FontFamily("Segoe MDL2 Assets");
        public string HoverDisplayText { get; private set; }
        public SvgImageSource Icon { get; set; }

        public bool IsDefaultLocation { get; set; }

        public bool IsExpanded
        {
            get => App.AppSettings.Get(Text == "SidebarFavorites".GetLocalized(), $"section:{Text}");
            set
            {
                App.AppSettings.Set(value, $"section:{Text}");
                OnPropertyChanged(nameof(IsExpanded));
            }
        }

        public NavigationControlItemType ItemType => NavigationControlItemType.Location;

        public string Path
        {
            get => path;
            set
            {
                path = value;
                HoverDisplayText = Path.Contains("?") || Path.ToLower().StartsWith("shell:") || Path.ToLower().EndsWith(ShellLibraryItem.EXTENSION) || Path == "Home" ? Text : Path;
            }
        }

        public SectionType Section { get; set; }
        public bool SelectsOnInvoked { get; set; } = true;
        public string Text { get; set; }

        public int CompareTo(INavigationControlItem other) => Text.CompareTo(other.Text);
    }
```

**Comment by chingucoding** [comment]
Looking at the stacktrace, it seems that it crashes because measuring the NavigationViewItem objects fails. Flowlayout shows up because ItemsRepeater meaasures everything for layouting purposes, when it encounters an element that fails to measure properly, flowlayout would be the first to notice.

**Comment by chingucoding** [comment]
Hmm, not sure if I did everything correct but I wasn't able to repro this issue. @duke7553 if you have the time, it would be amazing if you create a repro app that can be used to dig into this.

**Comment by duke7553** [comment]
@chingucoding I hate to give you an app which has unrelated code, but I can only reproduce this one in Files main branch which should reference the latest WinUI preview.

https://github.com/files-community/Files

**Comment by chingucoding** [comment]
After debugging it a bit, it seems like an issue with the Version 2 styles, more importantly probably with the NavigtaionViewItem(Base) one as those crash in `MeasureOverride`.

**Comment by StephenLPeters** [comment]
Thanks for the added information both of you!

**Comment by chingucoding** [comment]
Also, @StephenLPeters I am looking to this issue, feel free to assign this to me.

Also also, if we can't find a way to repro this in MUXC test app, is it still fine to create a PR?

**Comment by StephenLPeters** [comment]
I think we need to fix it. Not being able to repro in our app doesn't change that :)

**Comment by chingucoding** [comment]
@StephenLPeters Over at the files repo, we finally have a good fix for this: https://github.com/files-community/Files/pull/4606/

The only changes made are the removal of the corner radius setter which seemed to cause the issues on this. What are your thoughts on this? @ranjeshj FYI
