### ISSUE TITLE
Memory in custom controls derived from Button

### ISSUE THREAD

**Issue by Vinothini-V** [microsoft/microsoft-ui-xaml#4762]
Cleared all instance of custom control derived from Button. But still  instance is showed in memory profiler.

I have created custom control derived from Button and also user control which contains Button. In both the cases, after implementing dispose and setting the Button instance to null, it shows instance in Memory profiler as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/72746313/113986452-e15f3300-986a-11eb-9601-fbcf203d214d.png)

Expected :

All object type should be cleared

UWP | Win32
-- | --
No | Yes

Version Info

WinUI NuGet package version = 0.5.0

OS version = Windows 10 Pro

NuGet package version:
[Microsoft.ProjectReunion.WinUI -0.5.0]

**Comment by StephenLPeters** [comment]
@Scottj1s Is this the same cswinrt memory issue?
