### ISSUE TITLE
Keyboard events behave differently between UWP and Islands

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#4763]
**Describe the bug**
(Using System XAML)
We should reconcile how keyboard input is treated in UWP and xaml islands (and winui3 Desktop apps)

**Steps to reproduce the bug**
in a Textbox, handle KeyDown and set `e.Handled=true`

in UWP, the input still reaches the textbox
in xaml islands, the input is blocked from reaching the textbox

**Expected behavior**
keyboard behavior is the same; setting Handled either blocks or doesn't block input, on both app models.

**Additional context**
Repro repo: https://github.com/asklar/kbdIslands
The wpfappcore\wpfappcore.sln has a UWP app (CSUWP) as well as a wpf xaml islands host with a uwp app (WpfCoreApp).
Run CSUWP and see that input flows to the textbox
Run WpfCoreApp and see that input does not flow to the textbox.

This is being hit by React Native for Windows customers 

https://github.com/microsoft/react-native-windows/issues/7523

**Comment by StephenLPeters** [comment]
UWP uses tfs 3 Islands uses tfs 1, which probably explains the difference.  This difference is, I think still present in winui between desktop and UWP apps.

**Comment by StephenLPeters** [comment]
https://docs.microsoft.com/en-us/windows/win32/tsf/text-services-framework

@Austin-Lamb FYI

**Comment by llongley** [comment]
To expand on that, TSF 1 allows through the WM_CHAR message which is handled by the XAML input stack, which pays attention to the Handled property on the event args.  TSF 3, by contrast, handles the WM_CHAR message itself, so XAML never sees it and never has a chance to note that the event shouldn't be handled.
