### ISSUE TITLE
ColorPicker's  selection pointer and tooltip updated inversely (mirrored) in ring shaped color spectrum

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#4765]
**Describe the bug**

While using `ColorSpectrumComponents` value as either `ValueHue` or `SaturationHue`  in ring shaped color spectrum , location of selection pointer and tooltip are mirrored to the location of mouse pointer

Sample:

[ColorPicker_Issues.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6278113/ColorPicker_Issues.zip)

**Steps to reproduce the bug**

1. Run the Sample
2. Select color from first and second ColorPicker's color spectrum.
3. Note:  Selection pointer and tooltip updated inversely(mirrored) in both ColorPickers.

**Expected behavior**

Selection pointer and tooltip should updated properly on where the color region is selected (based on current mouse pointer location).

**Screenshots**

Location of Selection pointer and tooltip are mirrored to the location of mouse pointer in the highlighted section.

![image](https://user-images.githubusercontent.com/57438309/114015073-f0ec7500-9886-11eb-8f7f-b190d12cf58f.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
likely present in winui2 as well. I think we are likely just doing math wrong when these combinations of setting are used...

**Comment by chingucoding** [comment]
I'll take a look and see if we can fix this in WinUI 2.
