### ISSUE TITLE
Tooltip in colorpicker shown when mouse pointer is outside of the control and control has focus

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#4766]
**Describe the bug**

Tooltip shown without hovering the mouse pointer on the color spectrum in ColorPicker when control got focus.

Sample:

[ColorPicker_tooltip_issues.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6278549/ColorPicker_tooltip_issues.zip)

**Steps to reproduce the bug**

1. Run the sample
2. Select color from `ColorPicker 1` and note `ColorPicker 1` selected color tooltip shown.
3. Select color from `ColorPicker 2` and note `ColorPicker 2` selected color tooltip shown.
4. Click on any area other then the  ColorPicker controls.
5. Note: `ColorPicker 1` got focus and selected color tooltip shown without mouse hovering and dragging.

**Expected behavior**

Toolltip in colorpicker should be hidden on following scenario.
1.Control got focus.
2. Mouse pointer is not inside or over the control. 

**Screenshots**

Mouse pointer is  clicked on outside of control and `ColorPicker 1` got focus and tooltip shown.

![image](https://user-images.githubusercontent.com/57438309/114028386-0d43de00-9896-11eb-8d5e-9076030b2b36.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
This is because clicking outside of the color pickers is actually giving the outer scroll viewer the chance to handle the click, which it does by placing focus on its first element.  This is by design, although i'll admit that it is pretty weird.
