### ISSUE TITLE
How to define the code behind Converter for Style applied in Button Control in UWP?

### ISSUE THREAD

**Issue by vijayarasan** [microsoft/microsoft-ui-xaml#4775]
I have tried to fully code behind display control in the UWP application. While Applying Style in Button control I need to use the Converter for apply style in Button control. But Unfortunately Converter not triggered for Button Control.

Here is my attempt to recreate it in CodeBehind, but it is unfortunately not working.

```
//create converter instance
 var converterInstance = new BoolToColorConverter();
 //add the converter to window resources
 this.Resources.Add("BoolToColorConverter", converterInstance);


 Binding myBinding = new Binding();
 myBinding.Converter = (BoolToColorConverter)this.Resources["BoolToColorConverter"];
 myBinding.Mode = BindingMode.TwoWay;
 myBinding.UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged;
 Style buttonStyle = new Style(typeof(Button));
 buttonStyle.Setters.Add(new Setter(Button.BackgroundProperty, myBinding));

 Button button = new Button();
 button.Width = 150;
 button.Height = 50;
 button.Content = "Hello";
 button.Style = buttonStyle;
 parent.Children.Add(button);
```
Screenshot for your reference,
![CodeBehindConverter](https://user-images.githubusercontent.com/58214164/114158743-acbeaa80-9942-11eb-97a3-8dd281312190.png)

I have attached a sample for your reference.

Sample Link: [CodeBehindinConverter.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6284602/CodeBehindinConverter.zip)

If I missed anything in this code behind.

Can you provide how to code-behind Converter for Style applied in Button Control as targetType in UWP platform?

Note: My requirement is needed to apply Style using converter in mentioned target type via code behind in UWP Platform

Regards,
Vijayarasan S

**Note:**
**Please refer to the MSDN link:** https://developercommunity.visualstudio.com/t/how-to-define-the-code-behind-converter-for-style/1382127

**Comment by StephenLPeters** [comment]
Instead of:
```
 buttonStyle.Setters.Add(new Setter(Button.BackgroundProperty, myBinding));
```
you should be doing this:
```
button.SetBinding(Button.BackgroundProperty, myBinding);
```

Also you shouldn't need to add the converter to a resource dictionary.  From code behind you can just do 
```
myBinding.Converter = converterInstance;
```

**Comment by vijayarasan** [comment]
Hi @StephenLPeters,

Sorry for the delay.

I have already mentioned my requirement is needed to apply Style using converter in mentioned target type via code behind in UWP Platform. Can you please share any ideas to trigger the code behind the converter in the UWP Platform?

Regards,
Vijayarasan
