### ISSUE TITLE
WinUI 0.5 Treeview not yet functional.  Same UWP code causes exception in WinUI.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#4776]
**Describe the bug**
The WinUI Treeview code is generating an exception in code that works correctly in UWP.

**Steps to reproduce the bug**

1. Goto https://github.com/Noemata/RosettaNavigation and create local copy of repo
2. Build and run TreeViewUwp1 solution.
3. Observe how it is supposed to run.
4. Build and run TreeViewWinUI1 solution.
5. Crashes on load.

**Expected behavior**
The WinUI TreeView should behave exactly as the UWP variant.

**Screenshots**
n/a

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
n/a

**Comment by StephenLPeters** [comment]
Do you have easy access to the callstack of the crash? :)

**Comment by Noemata** [comment]
@StephenLPeters , just run the sample for yourself.  I've pinpointed where the crash happens for you in the code comments.  I wish I got this level of information from my clients ;-)  These samples were built specifically to ease the process of vetting the remaining issues with UWP and WinUI.  Run them!

**Comment by bpulliam** [comment]
UWP is no longer supported by WinUI 3.  If you can repro the issue on current builds without UWP, please reactivate or open a new issue.

Thanks!
