### ISSUE TITLE
Is there any method or workaround to use system tray in WinUI3 desktop App?

### ISSUE THREAD

**Issue by gscheartA** [microsoft/microsoft-ui-xaml#4782]
I am developing a **desktop app** using winui3, and I am going to put the app into **system tray** after user closing it by X button. Only user right click the icon in system tray and choose exit then the app could be finally closed. 
I am not sure if currently there is any API related it. If no, is there any workaround to get it? Thank you for your kindly help.

**Comment by StephenLPeters** [comment]
similar to https://github.com/microsoft/microsoft-ui-xaml/issues/4792  @MikeHillberg and @Austin-Lamb and @marb2000

**Comment by marb2000** [comment]
It's not a built-in feature of WinUI3 and I don't have a sample that demonstrates how to do it. @dotMorten do you have any?

These are good docs to reuse from Win32 APIs and encapsulate it into a helper like the @dotMorten [sample](https://github.com/dotMorten/WinUIEx/) or [mine](https://github.com/marb2000/DesktopWindow).

**Comment by dotMorten** [comment]
@marb2000 @gscheartA Yes my repo does show how to minimize to tray here: https://github.com/dotMorten/WinUIEx/blob/3aaa34b58c488dba054e80311bfc3aa1cc772950/src/WinUIExSample/MainWindow.xaml.cs#L70-L80

**Comment by marb2000** [comment]
Closing the issue given @dotMorten provides a workaround.
