### ISSUE TITLE
Does/Will WinUI 3 have support for movable/dockable panels

### ISSUE THREAD

**Issue by LouChiShu** [microsoft/microsoft-ui-xaml#4784]
As the title says, does or will WinUI 3 have support for movable/dockable panels. I would like make a 3D engine project and one of the features I would like would be the ability to resize move and dock the various panels as the user sees fit. Moving the panels to a separate window would be a bonus, but not necessarily required.

**Comment by StephenLPeters** [comment]
This should be possible to do today with windowed popups and drag and drop. But we don't have a control designed to do this. I think it is a possibility, you should open a feature request :) @ranjeshj and @MikeHillberg and @ryandemopoulos
