### ISSUE TITLE
Question: Reunion 0.5 preview features :Multi-window support in desktop apps 

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4785]
when i create multi-window, but run error:
```
WinUI: Error creating second Desktop Window on the current process. No more than one Desktop Window is allowed per process.
```
but the doc(https://docs.microsoft.com/en-us/windows/apps/winui/winui3/release-notes/winui3-project-reunion-0.5-preview) says:

Support for multiple windows in desktop apps is in progress, but not yet complete and stable.
Please file a bug on our repo if you find new issues or regressions with multi-window behavior.

**Comment by Marv51** [comment]
Are you using the 0.5 preview or the 0.5 release? The multi window support is a preview feature that is in the 0.5 preview (see also the release notes you linked to) but as with all preview features has been removed from the 0.5 stable release. 

See also this comment: https://github.com/microsoft/microsoft-ui-xaml/issues/4777#issuecomment-816900808

**Comment by shelllet** [comment]
yeah! 

this is `packages.config` content.
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.ProjectReunion" version="0.5.0" targetFramework="native" />
  <package id="Microsoft.ProjectReunion.Foundation" version="0.5.0" targetFramework="native" />
  <package id="Microsoft.ProjectReunion.WinUI" version="0.5.0" targetFramework="native" />
  <package id="Microsoft.Windows.CppWinRT" version="2.0.210329.4" targetFramework="native" />
</packages>
```

**Comment by shelllet** [comment]
> Are you using the 0.5 preview or the 0.5 release? The multi window support is a preview feature that is in the 0.5 preview (see also the release notes you linked to) but, as with all preview features, has been removed from the 0.5 stable release.
> 
> See also this comment: [#4777 (comment)](https://github.com/microsoft/microsoft-ui-xaml/issues/4777#issuecomment-816900808)

**Comment by StephenLPeters** [comment]
@Marv51 is correct, multi window support is currently a preview feature and not present in the 0.5 release bits. If you want to experiment with the feature you can use the prerelease package.

**Comment by shelllet** [comment]
tks
