### ISSUE TITLE
Access violation at startup when targeting x86

### ISSUE THREAD

**Issue by mrjfalk** [microsoft/microsoft-ui-xaml#4789]
**Describe the bug**
When I'm launching a new WinUI Desktop app and compiling for x86 the app crashes at startup (before any window is visible) with the exception:

Exception thrown at 0x1000B481 (HsSrv.dll) in TestWinUI.exe: 0xC0000005: Access violation reading location 0x019A0000.

If I switch to x64 the app runs fine.

**Steps to reproduce the bug**
1. Create a new WinUI app with the template "Blank App, Packaged (WinUI in Desktop)"
2. Set platform to x86
3. Press Start Debugging (F5)
4. The app crashes before any window is even visible with the previously mentioned exception.

**Expected behavior**
The app launches without crashing.

**Screenshots**
Callstack:
![image](https://user-images.githubusercontent.com/8074736/114304621-7dd83e00-9ad4-11eb-9b60-58586fa105ab.png)

**Version Info**
WinUI 3 supported release (Reunion 0.5)

NuGet package version: 
WinUI 3 - Project Reunion 0.5: 0.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| October 2020 Update (19042)        |  Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |   |
| October 2018 Update (17763)        |   |
| April 2018 Update (17134)          |  |
| Fall Creators Update (16299)       |  |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Noemata** [comment]
@mrjfalk , I've never seen this happen.  I've created dozens of x86 WinUI apps.  Based on the failing DLL, perhaps your audio interface components need an update.

**Comment by StephenLPeters** [comment]
I agree with Noemata. I don't think this is related to our package. A quick search seems to point at sound drivers.  Very strange...  @alwu-msft Just in case do you have any ideas?

**Comment by mrjfalk** [comment]
I do have the latest driver, and I've used this sound card for a very long time, and it has never caused issues like this before developing eg uwp, wpf, c++ apps, etc. So even if it is caused by the sound card driver winui should not crash.

**Comment by Noemata** [comment]
@mrjfalk , I would tend to agree.  All I can suggest is to update the OS to the latest bits, update VS2019, and simplify the execution environment.  Temporarily disable any background tasks (if you have something like an animated desktop, etc.).  Also, don't have any other processes running concurrently with Visual Studio.  If that doesn't work, you may have to try an exorcism on your PC, making sure you have Mike Oldfield's "Tubular Bells" playing in the background while it's taking place ;-)

**Comment by alwu-msft** [comment]
Closing as this doesn't appear to have been related to WinUI/Windows App SDK at all.

**Comment by mrjfalk** [comment]
Can confirm that it's caused by the latest [driver](https://dlcdnets.asus.com/pub/ASUS/Audio_Card/Xonar_DGX/DGX_8_1_8_1823_Windows10.zip) for the Asus Xonar DGX audio card. Unfortunately there are no new drivers available. Guess I'll be buying a new sound card.
