### ISSUE TITLE
Teaching Tips that do not fit on screen should not show

### ISSUE THREAD

**Issue by StephenLPeters** [Microsoft/microsoft-ui-xaml#479]
When a developer attempts to show a tip which does not fit on screen, it should not show but instead fire a closing and then closed event

**Comment by jevansaks** [comment]
@stephenlpeters is this needed for 2.1? What happens if we don't do this?

**Comment by StephenLPeters** [comment]
If we show tips which do not fit in window/on screen there is a chance a tip would open which has a clipped close button and would not be able to be close by the user (in easy ways).  This scenario is covered by #480.  The second part is to avoid the app leaking resources that were intended for the tip and were supposed to be cleaned up in the closed event handler.
