### ISSUE TITLE
WinUI 0.5 Crashes when using NavigationView, exact same code works correctly in UWP.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#4790]
**Describe the bug**
There appears to be a cross threading bug in WinUI when the NavigationVIew control is used.  The exact same code works as expected in UWP.  WinUI crashes on start because of this problem.

**Steps to reproduce the bug**

1. Create local copy of repo at: https://github.com/Noemata/RosettaNavigation
2. Build and run the NavigationViewUwp1 project to see how it is supposed to work.
3. Build and run the NavigationViewWinUI1 project, it crashes on load.

**Expected behavior**
WinUI should operate in an equivalent manner to UWP when background threads are used to initialize data.

**Screenshots**
Working UWP app.
![image](https://user-images.githubusercontent.com/6632315/114316780-05bd4880-9ad3-11eb-820d-c5648c8a7078.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
There are many other variations of using the NavigationView that cause WinUI to crash.  Please start with fixing this one.

What's interesting, if you single step the code in just the right way, you can cause WinUI to work correctly.  So if you manage to bypass the cross threading issues in certain scenarios, the problem goes away.

**Comment by StephenLPeters** [comment]
@ojhad FYI

**Comment by codendone** [comment]
This is the same issue as #4499 -- a noisy exception from AcrylicBrush.
