### ISSUE TITLE
Question: Support for MAUI on WinUI in a WPF application window

### ISSUE THREAD

**Issue by dbeavon** [microsoft/microsoft-ui-xaml#4791]
Congratulations on the WinUI release for desktop applications!

_(If I understand correctly, the MAUI team is already starting to use WinUI, and relies on it as the underlying technology for 
targeting the windows desktop.  Apparently they have a preview release that makes use of WinUI for desktop applications.)_

My question is in regards to the following three technologies for building "native U/I" : **MAUI, WinUI, and WPF**.  As I understand, MAUI is an abstraction layer that can sit on top of WinUI.  And WinUI has become a portable technology that can be hosted within a legacy Win32 app.  Given the goals of each of them, should it be possible to build a **MAUI** user interface hosted in **WinUI** island on a **WPF window**?  _(I think the XAML islands for WinUI are still a little a work-in-progress, so the question assumes that will be possible at some point.)_ 

As an alternative, I believe that the MAUI abstraction layer can sit directly in WPF but the end result would probably look quite different, and I don't think that type of a configuration (albeit simpler) would have the same level of support from Microsoft.

It would be nice to see a sample application that accomplished this!  In theory it sounds like you could use controls from all three technologies in the **same** window.  Maybe you could even put a webview2 in there with client-side blazor!

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI
