### ISSUE TITLE
No alternative method for App_Closing or CloseRequested?

### ISSUE THREAD

**Issue by gscheartA** [microsoft/microsoft-ui-xaml#4792]
I am try to develop a **desktop App** using WinUI 3 0.5. I am researching a method to prevent native close event and replacing with other code. I found that App_Closing, Closing and even CloseRequested method could not work currently which caused by remove of  GetForCurrentView and some other API.
May I know if there is any method to prevent the native close event of the App and execute some other code? Thanks for your kindly help.

**Comment by StephenLPeters** [comment]
@marb2000 @Austin-Lamb and @MikeHillberg FYI

**Comment by marb2000** [comment]
I wrote a sample that implements the Window.Closing event in Reunion 0.5 GA. You can find it [here](https://github.com/marb2000/DesktopWindow). It should be good enough for this release because we only allow one Window per app, so basically closing the Window is like closing the app.
