### ISSUE TITLE
C++ WinUI 3 Desktop App

### ISSUE THREAD

**Issue by BobPalank** [microsoft/microsoft-ui-xaml#4795]
C++ WinUI 3 Desktop App:
When I start a new application, I use the CPP/CLR controls toolbox to build the GUI for the app by dropping controls on the form.
How do I drop controls on a form do in WinUI 3 ?
Bob

**Comment by StephenLPeters** [comment]
It sounds like your talking about some UI design tool. Can you provide a link to the "CPP/CLR controls toolbox" you are referring to?  The VS designer is not supported by winui3 currently.
