### ISSUE TITLE
Adding Microsoft.Toolkit.Uwp.UI.Controls nuget package to UWP project breaks XAML Islands WPF app

### ISSUE THREAD

**Issue by Tam66662** [microsoft/microsoft-ui-xaml#4796]
**Describe the bug**
I have a functioning WPF app that hosts a UWP user control, using XAML Islands. I wanted to add a RadialGauge UWP control to my UWP project, but simply adding the Microsoft.Toolkit.Uwp.UI.Controls nuget package to my UWP project prevents the WPF app from launching anymore.

**Steps to reproduce the bug**
1. Follow Microsoft's guidance on [hosting a standard UWP control inside of a WPF App using XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands).
2. Once you have a functioning WPF app that is hosting a UWP control, add the Microsoft.Toolkit.Uwp.UI.Controls nuget package  to the UWP project. 
3. The WPF app now fails to run at all.

I've created a reproducibel sample solution if you don't want to follow the first step above on your own.
1. Download my [minimal reproducible functioning XAML Islands solution](https://drive.google.com/file/d/1ZvaFZ-zJ6iJ7JBnvBkS9Eg54BXTfYxTd/view?usp=sharing). This solution does *not* contain the Microsoft.Toolkit.Uwp.UI.Controls nuget package yet, and if you compile it, you will see that it runs.
2. Build it as Debug/x64, and then run the WpfAppWithUwpControl app. You will see that the application is able to load and run.  Here's a screenshot of what to expect:
![image](https://user-images.githubusercontent.com/12551526/114421926-a874d600-9b6a-11eb-9abb-c5629496b4f2.png)

3. Now go to the MyUwpApp project and add the Microsoft.Toolkit.Uwp.UI.Controls nuget package (at the time of this submission, I used the latest 7.0.1 stable).
4. Run the WPF app again and you'll see that it doesn't run anymore.

**Expected behavior**
I expected the WPF app to still be able to run after adding the Microsoft.Toolkit.Uwp.UI.Controls nuget package. More importantly, I expect to be able to use any Microsoft.Toolkit.Uwp.UI.Controls user control in my WPF app if I have it hosted using XAML Islands.

**Version Info**

OS: Windows 10 Version 1909 (Build 18363.1443)
UWP Project Target Version: Windows 10 Version 1903 (Build 18362)
UWP Project Min Version: Windows 10 Version 1903 (Build 18362)
WPF Project  Target Framework: .NET Core 3.1

NuGet package version: 

[Microsoft.Toolkit.Uwp.UI.Controls 7.0.1]
[Microsoft.NETCore.UniversalWindowsPlatform 6.2.12]
[Microsoft.Toolkit.Win32.UI.XamlApplication 6.1.2]

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@michael-hawker does WCT support xaml islands?

**Comment by michael-hawker** [comment]
@StephenLPeters it should. Our early 7.0 previews were working fine, but then investment in the base helpers for XAML Islands [aren't being maintained anymore](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32#xaml-islands-notice) as everything has shifted to working on WinUI 3. We also pivoted to supporting [WinUI 3](https://aka.ms/wct-winui3) in the Toolkit.

FYI @marb2000 @ocalvo @azchohfi

@Tam66662 is there a specific exception you're seeing?

**Comment by Tam66662** [comment]
@michael-hawker No, there is no exception that I'm able to capture from code in Visual Studio.  When I run the app (F5) it immediately returns back to the Visual Studio UI.  The app crashes before it can even render.  In EventViewer, it says that it crashes inside of Windows.UI.Xaml.dll.

![image](https://user-images.githubusercontent.com/12551526/115609288-34d67580-a29c-11eb-8d45-548f81baad8f.png)

**Comment by michael-hawker** [comment]
Thanks @Tam66662 not sure if the WinUI folks may have more suggestions for getting more details outside of turning on mixed/native debugging and turning of 'my code only'.

Is it only if you include the Controls package? It's a meta package now comprised of multiple sub-packages, so wondering if you'll get similar errors if you include 7.0.1 of `Microsoft.Toolkit.Uwp.UI.Controls.Primitives` or `Microsoft.Toolkit.Uwp.UI.Controls.Layout` directly?

You could also try an earlier version of the controls package like 7.0.0-preview2 or 7.0.0-preview4 to see if those still work, could help us pinpoint more what may have changed, as we also added a WinUI 2.5 dependency later in the release compared to before. Had you added the XamlControlResources to the App.xaml like you would with any WinUI based project?

**Comment by Tam66662** [comment]
@michael-hawker 

Microsoft.Toolkit.Uwp.UI.Controls.Primitives 7.0.1: FAILED
Microsoft.Toolkit.Uwp.UI.Controls.Layout 7.0.1: FAILED
Microsoft.Toolkit.Uwp.UI.Controls 7.0.0_preview2: PASSED
Microsoft.Toolkit.Uwp.UI.Controls 7.0.0_preview4: PASSED
Microsoft.Toolkit.Uwp.UI.Controls 7.0.0_preview5: FAILED

So it appears that something broke between 7.0.0_preview4 and 7.0.0_preview5.

Regards,
Tam

**Comment by Tam66662** [comment]
Just a followup to anyone reading.  I was able to successfully add the Microsoft.Toolkit.Uwp.UI.Controls nuget package to my XAML Islands WPF app, but only if I reverted back to 7.0.0_preview4.  I was even able to add one of the UWP UI controls from that package to my project, and it ran successfully.  

But I still couldn't get it to work with 7.0.0_preview5 or beyond (at the time of this post, latest 7.0.1). After learning the support team has moved on to ensuring WinUI 3 stability, I'm just going to stick with using 7.0.0_preview4 for my needs, and shift to WinUI 3 when the framework becomes available.

Thanks,
Tam

**Comment by michael-hawker** [comment]
Thanks @Tam66662 for trying all the different versions. Good for us to know it happened between preview 4 and 5. We did a lot of changes there, but not sure what in particular would have been related to XAML Islands specifically.

FYI @azchohfi not sure if you want to compare our project files or something to see what might have changed? Maybe we missed a flag setting up the new split packages?

**Comment by StephenLPeters** [comment]
@michael-hawker should we reenable this issue and or transfer this issue to WCT?
