### ISSUE TITLE
Discussion: Scheduling work to the UI Thread via Task Scheduler instead of Dispatcher

### ISSUE THREAD

**Issue by mandalorianbob** [microsoft/microsoft-ui-xaml#4798]
# Discussion: Scheduling work to the UI Thread via Task Scheduler instead of Dispatcher
I was recently talking with my team about the relationship between Tasks, Task Scheduler, Synchronization Context, and the Dispatcher, and I realized that the typical pattern for scheduling work to the UI Thread was odd. You either pass the Dispatcher to the relevant classes or call Windows.ApplicationModel.Core.CoreApplication.MainView.Dispatcher to get it, and then call RunAsync on the Dispatcher with a CoreDispatcherPriority.

However this completely bypasses the Task Scheduler, making me wonder - should there be a Task Scheduler for the ApplicationView that's accessible off the UI thread the way the dispatcher is?

After all, isn't it better to schedule work to the Task Scheduler instead of _some_ tasks, those made on the UI thread, going through Task Scheduler and then background tasks going directly to the Dispatcher? 

And probably more important than that, one of the problems with bypassing the Task Scheduler is this:
```C#
//DO NOT USE THIS CODE.

await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () =>
{
   await signInDialog.ShowAsync(); 
});
// Execution continues here before the call to ShowAsync completes.
```
Right yeah, cuz the Dispatcher isn't a Task Scheduler. So the documentation instead advises ... using a _Task Completion Source_?

But ... again, shouldn't you schedule work to the UI TaskScheduler that uses the Dispatcher?

I thought that would be a better solution - but sure enough, it doesn't really _appear_ supported. 

First, the documentation tells you to create a Task Completion Source for async code, haha. But second, the only way I can see to get the Scheduler is to call TaskScheduler.FromCurrentSynchronizationContext(). But that only works on the UI thread.

Which means that if you're trying to do this from the background (because, for instance, you're in a library, not in the main app, or if you're just not in a UI event and aren't certain) you literally have to
```C#
await CoreApplication.MainView.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () => taskScheduler = TaskScheduler.FromCurrentSynchronizationContext());
```
I mean that does work - but it just screams "This is unexpected!" which always gives me pause. 

Also, for what it's worth, I realized that using that TaskScheduler would involve some repetitive options, so I created a task factory
```C#
var taskFactory = new TaskFactory(CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskContinuationOptions.None, taskScheduler);
```
and passed that around my library for UI work. This works great!

But it immediately made me come here to ask - why is it like this? 

I mean, maybe there could exist - in theory? - multiple Task Schedulers for a given Synchronization Context. But does the XAML Framework actually produce multiple Task Schedulers? 

I really feel there should there be a "canonical" Task Scheduler for the ApplicationView to make scheduling work to the UI thread more consistent, and to eliminate the aforementioned pitfall, accessible from off thread the same way the Dispatcher is accessible.

**Comment by StephenLPeters** [comment]
@Austin-Lamb can you weigh in?

**Comment by JohnnyWestlake** [comment]
```First, the documentation tells you to create a Task Completion Source for async code, haha```

You laugh this off, but what is wrong with this approach? Most people will wrap this up in an extension method for Dispatcher and be on their merry way.

**Comment by mandalorianbob** [comment]
> `First, the documentation tells you to create a Task Completion Source for async code, haha`
> 
> You've dismissed this, but is there an issue with this approach? Most people will wrap this up in an extension method for Dispatcher and be on their merry way.

Well, a couple things. There's the (perhaps minor) performance implications of the extra allocations. 

However, there's a kind of "architectural" concern to me of passing an async lambda to an async method within an async method - and then having to use a TCS in order to tell when it's finished. I'm not saying TCS only has one purpose, but usually you don't find it being used to indicate when Task-based async methods complete.

And that partly results in a code pattern -
```C#
var tcs = new TaskCompletionSource<bool>();
await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () =>
{
   await signInDialog.ShowAsync(); 
   tcs.SetResult(true);
});
await tcs.Task;
```
that tends to violate the "Principle of Least Astonishment" as it were. After having forgotten about this caveat, I've come across code like this - that I had actually written!! - and gone, "What?? Why??" Because it was way less obvious when it's a buncha code instead.

It's very easy to tell _what's_ happening, but it's not obvious as to why.

I should reiterate though - I'm not saying the pattern is bad in an of itself. I'm very much wondering _why_ this pattern was chosen. I get that a lot - all? - UWP devs especially do this, I do! It's my team's standard pattern as well (although we tend to avoid the async lambdas.)

However, recently I began to really try to understand in a deep way how async/await works under the hood. And discovering the relationship between TaskScheduler/SyncContext/Dispatcher made me wonder about doing it differently.

But I don't know if it's better, because I don't know what I don't know when it comes to this stuff. So I'm trying to understand if it's just something where people didn't think of it, or there were historical reasons, or if there's something wrong with what I'm suggesting.

**Comment by omikhailov** [comment]
There is nothing wrong in using TaskContinuationSource with Dispatcher - it asynchronously places delegate in the queue, nothing more. And this is exactly what you want in 99% of cases - just fire and forget.
If subject is what is the purpose of the Dispatcher, there is at least one obvious answer: UI runs in STA and priority queue is only way to set priorities for UI updates.

**Comment by mandalorianbob** [comment]
For context: My understanding from reading the WPF ref source, is that there is a SynchronizationContextTaskScheduler that schedules work to the SynchronizationContext.Current - which is itself a DispatcherSynchronizationContext that queues work to the Dispatcher. 

So, again as far as I understand it, on the UI thread Tasks are scheduled to the Task Scheduler, which posts to the Sync Context, which then queues to the Dispatcher. Off the UI Thread, the typical pattern to schedule UI work bypasses the Task Scheduler and Synchronization Context. As stated above, this has timing implications (may come into play when trying to debug thread related issues) and on top of it, actually has one clear downside, as also stated above.

I'm not saying that calling Dispatcher.RunAsync is _bad_ or _wrong_ or any of that. Nor am I asking about the purpose of the Dispatcher.

So to keep this thread's purpose clear, I am asking: 
What is the reason the Task Scheduler wasn't used in this pattern? And are there any issues using the TaskScheduler now? And, for the future, should the framework provide a more Task-friendly means by which to schedule work on the UI thread?

**Comment by sylveon** [comment]
Keep in mind Dispatcher and DispatcherQueue are fully native code so they can't interop fully seamlessly with C#'s tasks. They need to be usable from C++ code as well.

You don't need to await RunAsync because awaiting the TCS right after achieves the same, and on the new DispatcherQueue (the CoreDispatcher is actually deprecated) you actually *can't* await it, since there's no method to do so.

You'll probably be better served by a method you can await to switch in and out of the UI thread, like `winrt::resume_background()` and `winrt::resume_foreground()` in C++. See this: https://medium.com/criteo-engineering/switching-back-to-the-ui-thread-in-wpf-uwp-in-modern-c-5dc1cc8efa5e

**Comment by mandalorianbob** [comment]
I guess I have not been explaining this very well. However, "Tasks aren't compatible with C++" does explain The Why.

Again, for clarification, I'm not talking about using the Dispatcher - I _already_ use the Dispatcher. (Also, two side notes: you should never leave a Task unawaited, that's how errors get uncaught. And I don't want to be calling thread switching code within a method, on account of it complicating unit tests even more than they already are with all things UI.) 

In UWP for the UI the Tasks are scheduled to the TaskScheduler which posts to the SyncronizationContext which queues work to the Dispatcher.

So I'm not talking about doing _anything_ with the Dispatcher, but actually the _opposite_. What I was asking about was having a single, more available TaskFactory that uses that specific TaskScheduler. This is almost _unrelated_ to the Dispatcher, except that the Dispatcher is the final destination of the work.

But I guess if having this Task Factory globally accessible wouldn't be compatible with C++, I s'pose it aint gonna have built in support. Not really a big deal I suppose, just making sure I wasn't doing something that could somehow lead to deadlocks or something crazy I wasn't seeing.

I think that actually answers my question, so I'll close this.
