### ISSUE TITLE
Navigation view separator line does not update when the size of the content changes. Only updates when the window is resized.

### ISSUE THREAD

**Issue by dannyp32** [microsoft/microsoft-ui-xaml#4800]
Navigation view separator line does not update when the size of the section content changes. Only updates when the window is resized. Ignore the separator line above settings in the screenshot. That one is added by our code. 

To repro make the content there visible, then collapsed it. The separator will still appear at the height where it should have been when the content was visible. 

![image](https://user-images.githubusercontent.com/921928/114468418-4cc53f80-9ba0-11eb-91f7-df83c0d40c7a.png)

![image](https://user-images.githubusercontent.com/921928/114469193-89456b00-9ba1-11eb-8b93-00d21200361c.png)

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

MUXC 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ranjeshj and @karenbtlai FYI

**Comment by karenbtlai** [comment]
@dannyp32 Would you be able to link a repro? I'm unable to repro this in the MUXC test app.
