### ISSUE TITLE
Popup theme resource binding not working 

### ISSUE THREAD

**Issue by KanniyappanP** [microsoft/microsoft-ui-xaml#4802]
I'm using the Popup control in my custom gallery control, and when I load/switch the theme to Dark in the application, the Popup background and foreground are not updated, but the colors are updated to the popup child via **theme resource** binding.

When I did this with template binding, this issue did not occur, and it only occurred in desktop applications, while UWP applications worked fine.

**Replications Steps:**

1. Download the attached simple reproducible WinUI Desktop application [Popup_DarkTheme.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6302561/Popup_DarkTheme.zip)
2. Click the Popup open button
3. Note Popup background and foreground not updated in Dark theme.

**Screenshot:**

**Gallery View**

![image](https://user-images.githubusercontent.com/56436173/114527794-00443780-9c66-11eb-9c0d-8acdd35a7dbb.png)

**Gallery Popup View** 

![image](https://user-images.githubusercontent.com/56436173/114527909-1eaa3300-9c66-11eb-8c4d-58b2e943300d.png)

**Comment by KanniyappanP** [comment]
Hi Team,

I have created this issue in ProjectReunion portal, Please find the link below.

https://github.com/microsoft/ProjectReunion/issues/722

**Comment by StephenLPeters** [comment]
@MikeHillberg and @bartekk8 I don't know what could cause this difference between UWP and desktop apps for resource resolution.  It kinda seems like the popup root either doesn't have or isn't receiving RequestedThemeChanged events.

**Comment by StephenLPeters** [comment]
@codendone Assigning to rendering as the popup owner.

**Comment by bpulliam** [comment]
Closing item where the internal item was fixed a while ago. If you still see this, please open a new issue.
