### ISSUE TITLE
Compact mode sizing not applied for ContentDialog

### ISSUE THREAD

**Issue by KarthikRajaAKR** [microsoft/microsoft-ui-xaml#4805]
**Describe the bug**
Compact sizing is not applied for the content of ContentDialog.

**Steps to reproduce the bug**
1. Run the attached sample. Compact Mode is set for the whole page.
2. Click Show editor button
3. Note that Compact sizing is not applied for the TextBoxes inside ContentDialog. But compact sizing is applied for the Textboxes of MainPage alone.

**Expected behavior**
ContentDialog should inherit compact mode sizing.

**Screenshots**

![image](https://user-images.githubusercontent.com/41435300/114543887-73a27500-9c77-11eb-8569-f36bea8bc9b1.png)

**Version Info**
[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease] 
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| October 2020 Update (19042)        |   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |   |
| October 2018 Update (17763)        |   |
| April 2018 Update (17134)          |   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | |
| Surface Hub        | |
| IoT                |  |

**Samples** 

[ContentDialogDesktopSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6303311/ContentDialogDesktopSample.zip)

[ContentDialogUWPSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6303312/ContentDialogUWPSample.zip)

**Comment by StephenLPeters** [comment]
It looks like you've added the Compact.xaml file to the resources of your Page.Resource dictionary.  ContentDialog unparents its children from itself and moves them into a popup which is not parented to the page (its parented to the application's popup root).  Thus when the textbox's in the ContentDialog resolve their style they wont see your page level resource dictionary.  If you set the XamlControlsResources.UseCompactResources to true, it should work for both.  That API is still preview (because compact styles are preview) so isn't usable in the release version of the nuget package.

**Comment by StephenLPeters** [comment]
Feel free to comment here if you have more questions about this.

**Comment by KarthikRajaAKR** [comment]
Hi @StephenLPeters,

This works for compact keys from winui framework. But in our case, we are having some compact size keys defined within our source. For normal pages, we will merge those keys in resource dictionary of the respective page. But with ContentDialog it only gets themeresources from framework level even if we merge our themeresource keys to App.Xaml resources. Can you please suggest any solution to this?

**Comment by StephenLPeters** [comment]
I think that if you put your resources inside of XamlControlsResources' merged dictionaries they should work. Here is the readme that suggests that: https://github.com/microsoft/microsoft-ui-xaml/blob/9052972906c8a0a1b6cb5d5c61b27d6d27cd7f11/build/NuSpecs/readme.txt#L21
