### ISSUE TITLE
WinUI 3 & Reunion 0.5 error: Microsoft C++ exception: winrt::hresult_error at memory location 0x..... when NavigationView is using

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/microsoft-ui-xaml#4806]
**Describe the bug:**
Impossible to use NavigationView component in WinUI 3 and Project Reunion 0.5.

**Steps to reproduce the bug:**
All you need to do for the bug reproducing, is to add NavigationView item to your XAML code:
```XAML
  <NavigationView/>
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/50652041/114544395-39c77380-9c63-11eb-81a9-5c0dd704e009.png)

**Version Info**

NuGet package version: 
WinUI 3 - Project Reunion 0.5 

Windows app type:
| UWP              | Win32            |
| :---------------: | :---------------: |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :--------------------: |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-----------------: | :---------------: |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I suppose, It's the same error, that describes in this issue: #4790

**Comment by Noemata** [comment]
@LeftTwixWand , same.  Looks like you narrowed it down further.  When I singled stepped through initialization, I was able to get to a running state, so I assumed it was a bit more complicated and related to a background thread.  Regardless, NavigationView is presently unusable with WinUI.

**Comment by LeftTwixWand** [comment]
@Noemata, unfortunately, WinUI 3 is not open source yet, and we can't to check what is happening inside(
Even if I'll get a source code of components from the generic.xaml file, I can't see the C++ code with a logic.
So - we just have to waiting for a fix from the Microsoft guys.

**Comment by Noemata** [comment]
@LeftTwixWand , indeed, we must wait.  Hopefully, Microsoft will change its definition of production ready.  This release is a curious kind of production grade.

**Comment by huoyaoyuan** [comment]
When the exception caught by VS, press F5 and continue works for me.

**Comment by StephenLPeters** [comment]
@ojhad FYI

**Comment by Herdubreid** [comment]
There is a simple workaround for this, as explained in https://github.com/microsoft/microsoft-ui-xaml/issues/4496#issue-829730597

**Comment by LeftTwixWand** [comment]
> When the exception caught by VS, press F5 and continue works for me.

So strange. In one project I can just skip the error, and it will work. But in another, any manipulations with a NavigationView also will throw an exception: `Access violation reading location`

**Comment by anawishnoff** [comment]
Hi @LeftTwixWand, you should see a fix for this bug in the upcoming WinUI 3/Project Reunion 0.8 Preview, which you can expect soon. Thanks for filing this!

**Comment by LeftTwixWand** [comment]
> Hi @LeftTwixWand, you should see a fix for this bug in the upcoming WinUI 3/Project Reunion 0.8 Preview, which you can expect soon. Thanks for filing this!

Thanks for everyone, who making such cool technologies)

**Comment by ranjeshj** [comment]
@DRAirey1 how are you using WinUI without Reunion? Can you provide a repro/details. perhaps you are not hitting the same issue.

**Comment by DRAirey1** [comment]
> @DRAirey1 how are you using WinUI without Reunion?

I just created a new project from the WinUI templates in Visual Studio 2022.

> Can you provide a repro/details. perhaps you are not hitting the same issue.

No. I can't repro. It happens randomly and the variables include using MSAL, different releases of the SDK, debug/release build, etc.

I can tell you that it's related to the BreadcrumbBar. The problem occurred when navigating to a page. The crash occurred while adding that view model to the ObservableCollection<ViewModel> that is bound to the Items Property of the BreadcrumbBar. When I replace the WinUI BreadcrumbBar with a custom control, the problem disappeared.

The problem occurred deep in the WinUI code with an error identical to the OP.
