### ISSUE TITLE
Question: How to create a custom effect for Compositor.CreateEffectFactory?

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#4808]
Hello!

I wonder if it possible to create a custom IGraphicsEffect for ProjectReunion (Desktop) application using C#? Is there a sample how to do this?

[This](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.composition.compositor.createeffectfactory?view=winui-3.0) article says that I can use effects from Win2D library, but I did not find an article about writing the custom effect.

**Comment by StephenLPeters** [comment]
@jeffStall FYI
