### ISSUE TITLE
NavigationViewItem does not respect HorizontalContentAlignment

### ISSUE THREAD

**Issue by ghord** [microsoft/microsoft-ui-xaml#481]
**Describe the bug**
Setting `HorizontalContentAlignment` does not work as expected in `NavigationView` in `PaneDisplayMode` set to `Left`

**Steps to reproduce the bug**
Set `HorizontalContentAlignment` to stretch on your `NavigationViewItem`.

**Expected behavior**
Content gets stretched to the full width of the pane

**Screenshots**
![obraz](https://user-images.githubusercontent.com/10825459/54878496-0de3b600-4e2e-11e9-914b-6f8f19c1de52.png)

![obraz](https://user-images.githubusercontent.com/10825459/54878477-f1e01480-4e2d-11e9-93a1-a2d75bba109b.png)

**Version Info**

NuGet package version: 
2.0.181018004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes  |
| April 2018 Update (17134)        |   |
| Fall Creators Update (16299)     | |
| Creators Update (15063)           |   |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
Seems like a reasonable request. :)
