### ISSUE TITLE
"Cannot find a Resource with the Name/Key" when ResourceDictionary contains one resource

### ISSUE THREAD

**Issue by ti82** [microsoft/microsoft-ui-xaml#4811]
**Describe the bug**
A runtime UnhandledException occurs when a StaticResource references a resource defined in a ResourceDictionary B that only contains a single resource, which itself has a StaticResource to another ResourceDictionary A. Both ResourceDictionary A and B are included in App.xaml as MergedDictionaries.

**Steps to reproduce the bug**
1. Create a new project using the blank UWP template
2. Add a folder to the project "Resources" and inside add new ResourceDictionary Colors.xaml and Brushes.xaml
3. Add a single `<Color x:Key="MyColor">#FF0000</Color>` to the Colors.xaml ResourceDictionary
4. Add a single `<SolidColorBrush x:Key="MyBrush" Color="{StaticResource MyColor}"/>` to Brushes.xaml
5. Add the Colors.xaml and Brushes.xaml to App.xaml:
```
     <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Resources/Colors.xaml"/>
                <ResourceDictionary Source="/Resources/Brushes.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```
6. Add `<Rectangle Fill="{StaticResource MyBrush}" Width="100" Height="100"/>` to the MainPage.xaml

**Expected behavior**
The red Rectangle is shown on the MainPage when the app runs.

**Screenshots**
N/A

**Version Info**

NuGet package version: 
Seeing this with Windows.UI.Xaml but was unable to find a proper location to file the issue, and was redirected here from the doc page for [Windows.UI.Xaml.ResourceDictionary](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.ResourceDictionary?view=winrt-18362).

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | N/A |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
Adding another Brush resource to Brushes.xaml will prevent the UnhandledException.

**Comment by StephenLPeters** [comment]
@bartekk8 and @MikeHillberg weird bug.  Maybe there is some optimization for RD with a single element?

**Comment by chrisglein** [comment]
> Adding another Brush resource to Brushes.xaml will prevent the UnhandledException.

Well, good news is that you have a workaround. But yeah... that definitely sounds like a bug. Perhaps some sort of optimization/confusion with the difference between a collection and a single item.

**Comment by Lightczx** [comment]
Still presents in WinAppSDK 1.4 (WinUI3)

**Comment by SamChaps** [comment]
Can still repro this in WinAppSDK 1.5.
