### ISSUE TITLE
Question: How to create an object with parameters in XAML

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#4812]
`<CustomControl Property="1, test"></CustomControl>`
`Property` is of type `Test` with constructor:
`public Test(int i, string str){}`

**Comment by huoyaoyuan** [comment]
There's no direct support for constructor with parameter. You can make a custom MarkupExtension, or use x:Bind to call a static helper method.

**Comment by StephenLPeters** [comment]
Correct, there is not support for parameterized constructors from markup.

**Comment by HppZ** [comment]
why I can use this: `<Thickness x:Key="ItemMargin">1,2,3,4</Thickness>`
