### ISSUE TITLE
Question: How to reuse VisualStateManager.VisualStateGroups

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#4813]

**Comment by StephenLPeters** [comment]
I don't understand the question, please provide more info.

**Comment by HppZ** [comment]
I need a `Button` based control, and I want reuse those `VisualState` in Button control template, can I do that?

**Comment by StephenLPeters** [comment]
The template property on control is an atomic property. If you are providing a new template you need to provide it in its entirety.  The VisualStateGroups are a part of the template, so if you require a new template for your button based control then you will need to copy the visual states into your template as well. If you can use the DefaultButtonStyle's template then having your template be BasedOn={StaticResource DefaultButtonTemplate}  will get you the whole template from the defualt style.

**Comment by HppZ** [comment]
there is no `DefaultButtonTemplate` or `DefaultButtonStyle`, the default Button style is `<Style TargetType="Button">` with no key specified.

**Comment by StephenLPeters** [comment]
Here is the Winui2 published DefaultButtonStyle: https://github.com/microsoft/microsoft-ui-xaml/blob/e22113fc87a77bd7c3ab24849f6504c3ac2549a9/dev/CommonStyles/Button_themeresources.xaml#L136 In that same file we have an unnamed style which is based on this.
