### ISSUE TITLE
ContentDialog BorderThickness gets ignored

### ISSUE THREAD

**Issue by AtosNicoS** [microsoft/microsoft-ui-xaml#4815]
Setting the Borderthickness of a ContentDialog gets completely ignored. I wanted to remove the border and the only workaround I found is to set the color to the exact same as the background color. I am using windows build 19041

**Comment by StephenLPeters** [comment]
I agree that the BorderThickness does seem to be ignored by content control, however I am seeing the opposite problem that you are describing. With the default ContentControl template I can't get a border to show up at all.  Can you give more specifics about your scenario?

default: 
![image](https://user-images.githubusercontent.com/7758786/114793098-7ddb7680-9d3e-11eb-9093-830478e97c35.png)
updated template:
![image](https://user-images.githubusercontent.com/7758786/114793049-643a2f00-9d3e-11eb-9b6f-b8f51389a396.png)

**Comment by StephenLPeters** [comment]
@ranjeshj I think we should update the content control to template bind these border properties.

@jevansaks or @MikeHillberg do you know if there is a good reason it doesn't today?

**Comment by jevansaks** [comment]
I'm sure it's just an oversight. But a plain ContentControl isn't very exciting on its own though, you really need to subclass it to do anything and when you do you would provide your own template.

@atosnicos, just curious what your scenario is for using ContentControl in this way as opposed to maybe Border or Grid if you just want decoration around some content?

**Comment by AtosNicoS** [comment]
@jevansaks I so super sorry, I made a huge mistake in my bugreport. I was referring to a **ContentDialog**, not a ContentControl. I will edit the original post and title.
