### ISSUE TITLE
👩‍💻☎ WinUI Community Call - April 21, 2021

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#4816]
This call has now ended. Thank you everyone for joining! You can find the recording of the call here:

**https://youtu.be/SyLXctia1B0**

# Details
Date: Wednesday April 21, 2021
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

# Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. In this month's call, we'll be sharing information on the latest and upcoming WinUI 3 releases, as well as welcoming the [.NET MAUI team](https://github.com/dotnet/maui). 

### **Agenda (Tentative)**
- Intro 
- Roadmap updates 
- Ecosystem Spotlight: .NET MAUI
- Q&A with the team and spotlight guests
  - **Questions and topic requests can be pre-submitted by commenting them on this GitHub issue**
  - **Questions can be asked live in the YouTube livestream's comment section**

### **Q&A Code of Conduct**
- To help ensure Q&A remains beneficial for the majority of the call's developer audience, please consider whether your question could be framed so that it might be more broadly relevant to our larger developer audience by ensuring it is reasonably concise, broadly beneficial, well-suited for the fast-paced live Q&A format, or able to spark open ended discussion.  
- Please understand some questions are not well-suited for the fast-paced live Q&A format and should be filed as standalone [Discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=discussion&template=discussion.md&title=Discussion%3A+%5Byour+discussion+title%5D) or [Question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) issues where they can be most appropriately handled. Excluding presentation topic requests, this generally includes requests for dedicated follow-ups or technically complex questions that require investigative time or expertise not included in this month's guest list.

**Comment by AathifMahir** [comment]
When we can expect parity between UWP App Model and win32? Is Reunion 1.0 would form a parity between UWP and Win32 app model and completely removes the lines between both models? Therefore developers no longer need to pick between both the models

**Comment by Noemata** [comment]
May we expect performance improvements in the next release?  Currently, performance is hindered by memory leaks and exceptions that shouldn't be thrown.  Much of this is related to C#/WinRT interop instability and lack of caching.  Does C#/WinRT pose an upper limit to performance for WinUI?

As a related question, why was it decided to not use the UWP JIT interop model?  It seems to be much faster.

**Comment by mdtauk** [comment]
Just a few questions...

- How long until all of UWP and Win32's feature sets will be 100% available in Reunion/WinUI?

- Once Reunion and WinUI have their source opened, will there be a mechanism or process to request new Windows or OS features which could be useful to devs, which can't be encapsulated with Reunion or WinUI?

- Will the WinUI or Reunion teams be open for creating app to app integrations.  As well as persuading the Windows OS team to create UI surfaces to allow safe and secure integration with the Shell?

**Comment by kmgallahan** [comment]
Is there anything the WinUI community can do to convince corporate MS to direct some of that [sweet $19.7 billion in cash used to acquire a speech recognition company](https://news.microsoft.com/2021/04/12/microsoft-accelerates-industry-cloud-strategy-for-healthcare-with-the-acquisition-of-nuance/) towards tackling the growing issue backlog of their flagship native Windows UI product?

That isn't an entirely unserious question. I'm not sure if 100x - 1000x uptick in Visual Studio WinUI telemetry data is the only thing that could help here or not.

Fully acknowledge that most of the code isn't open source, but that means the community doesn't really get the full view of how much is going on behind the scenes.

**Comment by pjmlp** [comment]
I have now started to do requirements analysis with C++ Builder and Qt/Creator/Designer as possible replacements for what are actually modern tooling for C++ developers.

However I would rather stay on Microsoft ecosystem, is there any hope that the lack of tooling caused by killing C++/CX gets adressed, instead of handwaving into some future ISO C++ standard in a couple from years to come?

Currently even MFC has a better developer experience versus having to deal with lack of tooling in WinUI for C++/WinRT.

Intelisense/syntax highlighting for IDL files, with two way editing between C++, IDL and XAML files and having VS deal with the generated files would be an improvement boom to productivity.

**Comment by saint4eva** [comment]
When is support writing UI in C# coming?

**Comment by saint4eva** [comment]
Regarding .NET Maui, how would it target Xbox and other platforms since WinUI is only about desktop?

**Comment by mdtauk** [comment]
> Regarding .NET Maui, how would it target Xbox and other platforms since WinUI is only about desktop?

WinUI 2.X still works with UWP and Xbox etc - but the plan is eventually have WinUI 3 work for UWP and Desktop.  It's just Desktop is the first milestone they are planning to hit.

**Comment by saint4eva** [comment]
> > Regarding .NET Maui, how would it target Xbox and other platforms since WinUI is only about desktop?
> 
> WinUI 2.X still works with UWP and Xbox etc - but the plan is eventually have WinUI 3 work for UWP and Desktop. It's just Desktop is the first milestone they are planning to hit.

Looking forward to using UWP app model in WinUI.

**Comment by shaheedmalik** [comment]
When will UWP be updated to WinUI, so Xbox can take advantage of the features? Win32 in WinUI3 is great, but not really a serious path forward for Universal Windows.

**Comment by pjmlp** [comment]
I fear that in regards to XBox it will be dealt the same way as XNA was.

**Comment by smourier** [comment]
I'm not sure I will be able to attend the call, but can someone tackle this question "Is ActiveX Control support possible/planned for WinUI 3 ": https://github.com/microsoft/microsoft-ui-xaml/issues/4670

I think it's important for a scenario where a legacy Win32 that uses lots of (external) ActiveX controls must be migrated to WinUI 3. It would allow a smooth transition (rewrite the host, and controls one by one) instead of a big bang (rewrite everything) one.

**Comment by Marv51** [comment]
Can you speak about the plan for open-sourcing again? I understand that it is a somewhat high priority now that WinUI 3 stable has shipped. 

What is the goal when you say open-sourcing WinUI? Will the code just be dumped/mirrored here, or is the plan to open up the development process? 
Is the end goal something like what the dotnet project is doing? They have public planning, public issues, live-streamed API-meetings, public code review etc...

**Comment by terrycox** [comment]
I just heard that Pivot won't be available until 0.8. Can you expand on that?

**Comment by terrycox** [comment]
There is news of a refresh of the Windows App Store. How does this affect WinUI 3 and Reunion?

**Comment by anawishnoff** [comment]
@terrycox About your Pivot question - Pivot will be available in the upcoming 0.8 **Preview** release, which you can expect by the end of April 😊. It will continue to be available in WinUI 3 through the subsequent preview and stable releases.

**Comment by anawishnoff** [comment]
@terrycox About your Pivot question - Pivot will be available in the upcoming 0.8 Preview release, which you can expect by the end of April 😊.

**Comment by terrycox** [comment]
Thanks for the response.

 

I thought from the timetable that 0.8 was out in June.

**Comment by terrycox** [comment]
0.8 Preview, got it.

 

Thanks much.

**Comment by jeganraj-m** [comment]
Can you provide me recorded link of May month Community call?

**Comment by terrycox** [comment]
I believe the May call was canceled. The WinUI team will be at Build, however.
