### ISSUE TITLE
The descendant of the CustomControl doesn't apply default style 

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#4826]
**Describe the bug**
Hi, 
If I've inherited a control from my own custom control it doesn't apply a default style. Take a look at the code. It's a critical issue. We faced it while porting WinUI UWP to the Desktop. Also found if I add the style of the CustomControl2 to generic.xaml ` <Style TargetType="local:CustomControl2" BasedOn="{StaticResource baseStyle}"/>` it'll apply although the DefaultStyleKey wasn't overridden.

**Steps to reproduce the bug**
```csharp
namespace ClassLibrary1 {
    public class CustomControl1: Control {
        public CustomControl1() {
            this.DefaultStyleKey = typeof(CustomControl1);
        }
    }
    public class CustomControl2 : CustomControl1 {
        public CustomControl2() : base() { }
    }
}
```

```xaml
    <StackPanel Orientation="Horizontal" 
                HorizontalAlignment="Center" 
                VerticalAlignment="Center" 
                Spacing="10">
        <cl:CustomControl1 Width="100" Height="100" Background="Red"/>
        <cl:CustomControl2 Width="100" Height="100" Background="Green"/>
    </StackPanel>
```

**Expected behavior**
The CustomControl2 should apply the default style of the base class (CustomControl1)

**Screenshots**
![image](https://user-images.githubusercontent.com/47348109/114865888-9067b580-9dfb-11eb-9bde-f0c86a6f754f.png)

**Version Info**
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
[Sample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6317737/Sample.zip)

**Comment by StephenLPeters** [comment]
@MikeHillberg and @bartekk8  I'm guessing whatever difference between Desktop and UWP that is causing this issue is also causing #4827
