### ISSUE TITLE
The custom control doesn't apply the default style when the Style property was bind or set to null

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#4827]
**Describe the bug**
Hi,
When I bind a style property of the CustomControl, it stops applying the default style. The property (which is bind) is null, not initialized. The same effect you can see if set the Style to {x:Null} in XAML. 
We use the same approach in our components to provide a way to customize parts of the control. There is no issue in WinUI UWP.

**Steps to reproduce the bug**
```xaml
    <StackPanel Orientation="Horizontal" 
                HorizontalAlignment="Center" 
                VerticalAlignment="Center" 
                Spacing="10">
        <cl:CustomControl1 Width="100" Height="100" 
                           Background="Red"/>
        <cl:CustomControl1 Width="100" Height="100" 
                           Background="Green"
                           Style="{x:Bind ControlStyle}"/>
        <cl:CustomControl1 Width="100" Height="100" 
                           Background="Blue"
                           Style="{x:Null}"/>
    </StackPanel>
```
```csharp
    public sealed partial class MainWindow : Window, INotifyPropertyChanged {
        public MainWindow() {
            this.InitializeComponent();
        }
        Style controlStyle;
        public Style ControlStyle {
            get => controlStyle;
            set {
                controlStyle = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(ControlStyle)));
            } 
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
```

**Expected behavior**
The default style should be applied

**Screenshots**
![image](https://user-images.githubusercontent.com/47348109/114870823-471a6480-9e01-11eb-9c3a-f64f591c7a10.png)

**Version Info**

NuGet package version: 
 
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

[Sample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6317963/Sample.zip)

**Comment by StephenLPeters** [comment]
@bartekk8 and @MikeHillberg it looks like default style merging isn't performed when you set the style to null, but only in Desktop. I woulnd't expect desktop vs. UWP to affect this behavior... Thoughts?
