### ISSUE TITLE
[WinUI3 Reunion 0.5] ScrollViewer on Navigation View Settings Button

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#4830]
**Describe the bug**

When hovering over the right-hand side of the Settings Button at the bottom of the NavigationView (in WinUI 3, Reunion 0.5), a scrollbar appears.

The scrollbars are not necessary. In UWP, the scrollbars do not appear.

It seems this behavior was introduced when the NavigationFooterItems were added to NavigationView.

**Steps to reproduce the bug**

1. Clone the [WinUI3Reunion05_Problems](https://github.com/eleanorleffler/WinUI3Reunion05_Problems).
2. Go to the WinUI3IssuesReunion05 folder.
3. Open the WinUI3IssuesReunion05.sln solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Find the Settings button at the bottom of the Home Page.
6. Hover over the right side of the Settings Button at the bottom of the NavigationView.

**Expected behavior**

We expect no scrollbar to appear, which is the same behavior in UWP.

**Screenshots**

![ExpectedBehavior](https://user-images.githubusercontent.com/9272634/114934583-ac6d5600-9dff-11eb-978e-61622ec317e2.PNG)

Screenshot#1 - Expected Appearance (UWP)

![CurrentBehavior](https://user-images.githubusercontent.com/9272634/114934602-b3946400-9dff-11eb-96d9-1043846a7aee.PNG)

Screenshot#2 - Current Appearance (WinUI3 Desktop)

**Version Info**

Targeting:
Target: Universal Windows
Target version: Windows 10, version 2004 (10.0; Build19041)
Min version: Windows 10, version 1809 (10.0; Build 17763)

NuGet package version: 
[Microsoft.ProjectReunion 0.5.0]
[Microsoft.ProjectReunion.WinUI 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|        Yes       |                  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

**Comment by StephenLPeters** [comment]
@karenbtlai and @chingucoding this is very familiar, have we fixed this in winui2 already?

**Comment by chingucoding** [comment]
@StephenLPeters I'm fairly sure this was fixed in WinUI 2 recently.

**Comment by nlogozzo** [comment]
Still occurs in WinUI 3 with project reunion 0.8

**Comment by velet76** [comment]
Is there no new content in this update REUNION [V 0.5A] - https://porngameshub.com/reunion?
