### ISSUE TITLE
[WinUI3 Reunion 0.5] Window Resizing Not Handled on Flyouts and Content Dialogs

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#4831]
**Describe the bug**

Flyout and Content Dialogs should be aware of the application window size and 
resize and show/hide scrollbars as needed.

In UWP, this works correctly both when a flyout or content dialog is initially 
opened AND when the application window is resized after the flyout or content 
dialog has been opened.

In WinUI 3, Reunion 0.5, this only works when a flyout or content dialog is 
initially opened, but not when the application window is resized after opening.

**Steps to reproduce the bug**

1. Clone the [WinUI3Reunion05_Problems](https://github.com/eleanorleffler/WinUI3Reunion05_Problems).
2. Go to the WinUI3IssuesReunion05 folder.
3. Open the WinUI3IssuesReunion05.sln solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Click on the second item on the Navigation View ("Dialogs and Flyouts").
6. Click on each of the buttons ("Test Flyout" and "Test Content Dialog").
7. Resize application window.

**Expected behavior**

We expect dialogs and flyouts to resize and show/hide scrollbars when the application window is resized after they are opened.

**Screenshots**

![CurrentBehaviorFlyout](https://user-images.githubusercontent.com/9272634/114938472-c3627700-9e04-11eb-9a7a-47718c0367e0.PNG)

Current Behavior (WinUI3 Desktop) - Flyout

![CurrentBehaviorDialogOnExpand](https://user-images.githubusercontent.com/9272634/114938464-c1001d00-9e04-11eb-86bf-d1e5eebd0031.PNG)

Current Behavior - Dialog (WinUI3 Desktop)
(Note: Dialog is no longer centered within application / was not updated on window resize.)

![ExpectedBehaviorDialogOnExpand](https://user-images.githubusercontent.com/9272634/114938479-c52c3a80-9e04-11eb-925f-10f5247798bc.PNG)

Expected Behavior (UWP) - Dialog

**Version Info**

Targeting:
Target: Universal Windows
Target version: Windows 10, version 2004 (10.0; Build19041)
Min version: Windows 10, version 1809 (10.0; Build 17763)

NuGet package version: 
[Microsoft.ProjectReunion 0.5.0]
[Microsoft.ProjectReunion.WinUI 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|        Yes       |                  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

**Comment by StephenLPeters** [comment]
@marb2000 and @Austin-Lamb FYI

**Comment by sylveon** [comment]
Looks like a bug carried over from Xaml islands (#3577)

**Comment by lyahdav** [comment]
I was about to file an issue for a bug where a Flyout with `ShouldConstrainToRootBounds = false` in XAML Islands will not correctly position when the win32 window is moved:

https://user-images.githubusercontent.com/359157/124999091-5412b280-e002-11eb-98df-acd3d3194177.mov

The code is available at https://github.com/lyahdav/XamlIslandsFlyoutBug/tree/FlyoutWindowMoveBehavior.

Here's the same code working correctly in a UWP app:

https://user-images.githubusercontent.com/359157/124999284-a05df280-e002-11eb-85da-c361fa7acd46.mov

The UWP app is available in this solution: https://github.com/lyahdav/CppWinRtUwpSandbox/blob/Flyout/cppwinrt/Calendar.sln

Please let me know if I should file this separately or if this issue will cover it.

**Comment by lyahdav** [comment]
Likely still relevant

**Comment by ranjeshj** [comment]
Just tried this on WinUI 3 Gallery (with WASDK 1.5). I see that this is fixed in WinUI3 gallery for ContentDialog. When the window size changes, the content dialog repositions itself as expected. Flyouts get dismissed as soon as you resize.
