### ISSUE TITLE
[WinUI3 Reunion 0.5] "mailto:" Hyperlink Not Working

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#4832]
**Describe the bug**

The hyperlink to a website works (opens website in browser window), but the hyperlink with mailto: does not do anything. It does not launch your email application, as it does in UWP.

**Steps to reproduce the bug**

1. Clone the [WinUI3Reunion05_Problems](https://github.com/eleanorleffler/WinUI3Reunion05_Problems).
2. Go to the WinUI3IssuesReunion05 folder.
3. Open the WinUI3IssuesReunion05.sln solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Click on the third item on the Navigation View ("Hyperlinks").
6. Click on the "mailto:" link.

**Expected behavior**

We expect clicking on a "mailto:" link to launch an email application or browser.

**Screenshots**

![ExpectedBehavior](https://user-images.githubusercontent.com/9272634/114939727-78496380-9e06-11eb-97c2-339b77940d10.PNG)

Screenshot#1 - Expected Appearance (UWP)

**Version Info**

Targeting:
Target: Universal Windows
Target version: Windows 10, version 2004 (10.0; Build19041)
Min version: Windows 10, version 1809 (10.0; Build 17763)

NuGet package version: 
[Microsoft.ProjectReunion 0.5.0]
[Microsoft.ProjectReunion.WinUI 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|        Yes       |                  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

**Comment by StephenLPeters** [comment]
@MikeHillberg @Austin-Lamb putting on reach because I think they own the xaml link code, however I wouldn't be surprised if this was a ProjectReunion issue and should be moved there.

**Comment by codendone** [comment]
Same underlying cause as #4438 (Hyperlink and HyperlinkButton use the same code to launch the Uri).
