### ISSUE TITLE
[WinUI3 Reunion 0.5] AppBarButton with Flyout on CommandBar displays ">" symbol

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#4836]
**Describe the bug**

In WinUI 3 Reunion 0.5, the AppBarButton with a flyout (Open icon) displays the ">" symbol, which does not match the look of the other buttons.

In UWP, the AppBarButton with a flyout (Open icon) does not display the ">" symbol.

**Steps to reproduce the bug**

1. Clone the [WinUI3Reunion05_Problems](https://github.com/eleanorleffler/WinUI3Reunion05_Problems).
2. Go to the WinUI3IssuesReunion05 folder.
3. Open the WinUI3IssuesReunion05.sln solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Click on the eighth item on the Navigation View (CommandBarFlyout).
6. Notice ">" symbol. Or see screenshot comparison below!

**Expected behavior**

We expect there to not be a ">" symbol next to the AppBarButton as it did not exist in the UWP version.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/9272634/114948955-abdfba00-9e15-11eb-8057-3a86a51e040b.PNG)

Screenshot#1 - Current Appearance (WinUI3 Desktop) vs. Expected Appearance (UWP)

**Version Info**

Targeting:
Target: Universal Windows
Target version: Windows 10, version 2004 (10.0; Build19041)
Min version: Windows 10, version 1809 (10.0; Build 17763)

NuGet package version: 
[Microsoft.ProjectReunion 0.5.0]
[Microsoft.ProjectReunion.WinUI 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|        Yes       |                  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

**Comment by StephenLPeters** [comment]
This was fixed by this check in https://github.com/microsoft/microsoft-ui-xaml/pull/4801  and will make it to Winui3 -Soon TM-
