### ISSUE TITLE
[WinUI3 Desktop App] Could I execute some code in the process of install and uninstall?

### ISSUE THREAD

**Issue by gscheartA** [microsoft/microsoft-ui-xaml#4838]
I am developing a desktop app using WinUI3. I would execute some code or call some other exe to initialize in the install process and also do same things in uninstall process. Currently I could not found any method to access it. Is there any demo or API instruction about it? Thank you for your kindly help.

**Comment by StephenLPeters** [comment]
Are you talking about the Appx install process?  I don't think we expose any hooks for that. @MikeHillberg ?

**Comment by gscheartA** [comment]
Hi @StephenLPeters  Thanks for your answer. I would call some exe and dll in the install flow like some win32 app installer. So you mean currently here is no method to execute these in the install/uninstall flow or pre-install/pre-uninstall flow, does it?
