### ISSUE TITLE
Question: How to create a control by the runtime class name, such as TextBox?

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4839]
I have a custom winrt class, such as "SomeClass", i can create an object  through the `winrt_get_activation_factory` function in `modue.g.cpp`. may be have a better way .

but how does the internal winrt class  create objects by the runtime class name?

**Comment by sylveon** [comment]
RoGetActivationFactory works much in the same way and takes a string

**Comment by shelllet** [comment]
> RoGetActivationFactory works much in the same way and takes a string

thks, i will try it

**Comment by duncanmacmichael** [comment]
Closing this issue as it appears to have been answered, and has not had activity since April 2021.
