### ISSUE TITLE
Bringing element into view with ItemsRepeater not working properly

### ISSUE THREAD

**Issue by adclements** [Microsoft/microsoft-ui-xaml#484]
After getting an element via ItemsRepeater.GetOrCreateElement(index), and then calling element.StartBringIntoView(), the RealizationRect in the layout attached to the ItemsRepeater is not updating properly - it is static and no longer updates due to scrolling.  Also, sometimes the element is not scrolled into view.

@ranjeshj - Have repro, will send.

**Version Info**
Microsoft.UI.Xaml - 2.1.19031900-prerelease
RS5 - Desktop

**Comment by jevansaks** [comment]
@ranjeshj if you want us to track this for 2.1 please add it to the 2.1 milestone.
