### ISSUE TITLE
Adding a style in code throws COMException

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#4840]
**Describe the bug**
Hi,
Just trying to add a style of the Button to resources in code and got an exception -System.Runtime.InteropServices.COMException: 'Unspecified error'

**Steps to reproduce the bug**
```csharp
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
            Style style = new Style(typeof(Button));
            style.Setters.Add(new Setter(FrameworkElement.WidthProperty, 117d));
            myButton.Resources.Add(typeof(Button), style);
        }

        private void myButton_Click(object sender, RoutedEventArgs e) {
            myButton.Content = "Clicked";
        }
    }
```
```xaml
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    </StackPanel>
```
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47348109/115014692-5827ac00-9ebb-11eb-942a-86c74edcee09.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Why are you adding the style to the Button's Resources?  If you want to set the style from code you can do `myButton.Style=style`  I think the resources property is probably null here and would need to be initialized to a ResourceDictionary if you did want to put the style in the resources (which you shouldn't).

**Comment by alexdi220** [comment]
The same code (setting a style) using in our tests and it works in WinUI UWP. I can't use `myButton.Style=style` by a test logic. But after upgrade the framework and reunion to 0.5.5 the issue stoped reproduce. So I'll close this thread
