### ISSUE TITLE
Compact mode problem

### ISSUE THREAD

**Issue by Alexander-Kamenchuk** [microsoft/microsoft-ui-xaml#4841]
**Describe the bug**
Hi,
I've researched the Compact Mode feature and not at all controls work the same way. The compact mode works only for editors (TextBox, CheckBox ...) but not for CommandBar, Menus and etc. I also notice that some of the editors, for example, the CalendarDatePicker, don't support compact mode.

What is the main idea of this feature? Will other controls, for example, CommandBar or ListBox, support the compact mode in the future? At now it looks strange and raw. The user can't use this feature to provide a high-density UI.

**Steps to reproduce the bug**

```xaml
<StackPanel>
        <StackPanel.Resources>
            <ResourceDictionary Source="ms-appx:///Microsoft.UI.Xaml/DensityStyles/Compact.xaml" />
        </StackPanel.Resources>
            <PasswordBox Width="200"/>
            <TextBlock Text="Compact" HorizontalAlignment="Center"/>
            <TextBox Text="Type here"/>
            <Button x:Name="myButton2" Click="myButton_Click">Compact</Button>
                <Border Width="200" Height="24" BorderBrush="Gray" BorderThickness="1">
                    <CheckBox Content="Two-State" IsChecked="True"/>
                </Border>
            <ComboBox Header="Colors" PlaceholderText="Pick a color">
                <x:String>Blue</x:String>
                <x:String>Red</x:String>
                <x:String>Yellow</x:String>
                <x:String>Green</x:String>
            </ComboBox>
            <DropDownButton Content="Email">
                <DropDownButton.Flyout>
                    <MenuFlyout Placement="Bottom">
                        <MenuFlyoutItem Text="Send"/>
                        <MenuFlyoutItem Text="Reply"/>
                        <MenuFlyoutItem Text="Reply All"/>
                    </MenuFlyout>
                </DropDownButton.Flyout>
            </DropDownButton>
            <Slider Width="170" Minimum="20" Maximum="100" StepFrequency="5" Value="25" TickFrequency="5" TickPlacement="Outside"/>
            <ListBox Width="120">
                <x:String>Blue</x:String>
                <x:String>Red</x:String>
                <x:String>Yellow</x:String>
                <x:String>Green</x:String>
            </ListBox>
            <CalendarDatePicker PlaceholderText="Pick a date" Header="Calendar"/>
            <DatePicker DayFormat="{}{day.integer} {dayofweek.abbreviated}" YearVisible="False"/>
            <CommandBar DefaultLabelPosition="Right">
                <AppBarButton Icon="Accept" Label="Accept"/>
                <AppBarButton Icon="Mail" Label="Mail"/>
            </CommandBar>
        </StackPanel>
```

**Expected behavior**
Controls in compact mode should look the same 

**Screenshots**
![image](https://user-images.githubusercontent.com/80826968/115016202-7098c600-9ebd-11eb-9888-cb0267669c1e.png)

**Version Info**
NuGet package version:
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |   Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
Compact mode is still in preview. At this time there are some notable controls which do not have a compact style.

**Comment by alexdi220** [comment]
Could we expect it's in the future? I mean do you plan that all controls will have a compact style or only some of them like TextBox?
