### ISSUE TITLE
Opening/closing animation to ContentDialog do not play in Xaml Islands

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#4843]
# Proposal: Add an opening/closing animation to ContentDialog

## Summary

This is inspired by https://github.com/microsoft/terminal/issues/9853

> I would animate it like the zoom in animation of PowerPoint when it spawns and I user clicks on cancel, rather than simply disappearing, I would make a "zoom out animation".

Presumably, developers would have to opt their dialogs into the animations, as to not break back-compat.

**Comment by mdtauk** [comment]
There is already an animation for the Content Dialog.  A Zoom and Fade transition when it shows and hides.

**Comment by zadjii-msft** [comment]
Huh. It does looks like there's a very subtle animation after all. I wonder if you don't see that in the Terminal because it's a XAML Island application...

**Comment by StephenLPeters** [comment]
@zadjii-msft So should this be repurposed into a xaml islands bug?

**Comment by zadjii-msft** [comment]
Yea, sounds like it.

**Comment by sylveon** [comment]
Yes, I am not seeing the animation either in my XAML islands application

**Comment by StephenLPeters** [comment]
@Austin-Lamb and @JesseCol FYI

**Comment by marb2000** [comment]
Hi @zadjii-msft !

Unfortunately, as we announced more than one year ago, OS XAML is something that we are not inventing right now. All the investments go to WinUI 3 that will support XAML Islands. It's expected that all these animations work on the WinUI 3 version.

Thanks
-Miguel

**Comment by sylveon** [comment]
But WinUI 3's XAML Islands are still very far away :/

**Comment by marb2000** [comment]
No really! We are super close to the engineering plan for v1, and Islands is part of it. By mid-May we should be able to commit specific work.
