### ISSUE TITLE
DropDownButton doesn't support access key like AppBarButton.

### ISSUE THREAD

**Issue by gaoyulei1983** [microsoft/microsoft-ui-xaml#4844]
**Describe the bug**
I want to add access key to DropDownButton's one menu item. In the DropDownButton, I add AccessKey="C"

**Steps to reproduce the bug**
1) Edit the the code DropDownButtonPage.xaml in https://github.com/Microsoft/Xaml-Controls-Gallery project like this.
                `<muxc:DropDownButton AccessKey="C" Content="Email">
                    <muxc:DropDownButton.Flyout>
                        <MenuFlyout Placement="Bottom">
                            <MenuFlyoutItem AccessKey="O" Text="Send" />
                            <MenuFlyoutItem Text="Reply" />
                            <MenuFlyoutItem Text="Reply All" />
                        </MenuFlyout>
                    </muxc:DropDownButton.Flyout>
                </muxc:DropDownButton>`
2) Then after it built and ran, go to the page, press alt key. It shows like below there is a C access key show under the Email.
![image](https://user-images.githubusercontent.com/80909481/115041704-5e427a80-9f05-11eb-8b6c-126000d2b9c7.png)
3) Press the "C" key, and the drop down menu pops up. but the access key "C" for the menu item "Send". 
![image](https://user-images.githubusercontent.com/80909481/115041958-a1045280-9f05-11eb-93a1-6c5a433e2450.png)

**Expected behavior**
I hope it can directly like this below in the Step3, without press alt key again.
![image](https://user-images.githubusercontent.com/80909481/115042360-f93b5480-9f05-11eb-93ec-0a90cc0da39a.png)

**Version Info**
[Microsoft.UI.Xaml.2.6.0-prerelease.210315002

NuGet package version: 

[Microsoft.UI.Xaml.2.6.0-prerelease.210315002

Windows app type:
UWP         

| Windows 10 version                  | Windows 10 Pro 20H2  19042.928|
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              No
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

**Comment by StephenLPeters** [comment]
In your markup you've set the access key of the button to C, so pressing alt and then C invokes the button. Are you saying that you have another access key on the send menu flyout item that also has it's access key set to C?

**Comment by gaoyulei1983** [comment]
Yes, I have another access key "O" on the menu flyout item which want to continue to be used after Alt+C is activated. You can see it works on AppBarButton.

**Comment by StephenLPeters** [comment]
It works with an appbar button that on invocation opens a flyout with another button in it?

**Comment by StephenLPeters** [comment]
Does pressing alt what the popup is open result in the access key being displayed?

**Comment by gaoyulei1983** [comment]
An AppBarButton opens a flyout with the access key "O" displayed when you press alt+C. It is a continuous behavior without pressing alt again.

**Comment by StephenLPeters** [comment]
@Austin-Lamb can you weigh in on this access key behavior?

**Comment by gaoyulei1983** [comment]
Will anyone resolve this bug?
