### ISSUE TITLE
Xamarin UWP: Refresh View is not working on 2.6.0-prerelease.210227001 version

### ISSUE THREAD

**Issue by rajeshangappan** [microsoft/microsoft-ui-xaml#4852]
Just add the refresh view in any xaml page. complete UWP app is hanged and throws win32 unhandled exception.

**Comment by StephenLPeters** [comment]
@rajeshangappan is RefreshView a control from xamarin?

**Comment by rajeshangappan** [comment]
This issue happens due to below issue fix.
https://github.com/microsoft/microsoft-ui-xaml/issues/3017#issuecomment-667628206
Now, i have removed that above workaround and found some other fix for resource conflicts.
