### ISSUE TITLE
Combobox positioning wrong with custom ItemsPanel

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4853]
**Describe the bug**
When creating a multi-column Combobox the Flyout is opened detached from the Combobox itself.

**Steps to reproduce the bug**
```xaml
xmlns:controls="using:CommunityToolkit.WinUI.UI.Controls"

<ComboBox >
    <ComboBox.ItemTemplate>
        <DataTemplate x:DataType="model:ColorDescriptions">
             <Rectangle Fill="{Binding Color}" Height="20" Width="40" />
         </DataTemplate>
     </ComboBox.ItemTemplate>
     <ComboBox.ItemsPanel>
        <ItemsPanelTemplate>
            <controls:UniformGrid Columns="5" />
         </ItemsPanelTemplate>
     </ComboBox.ItemsPanel>
</ComboBox>
```

[UniformGrid](https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/dev/7.0.1/Microsoft.Toolkit.Uwp.UI.Controls.Primitives/UniformGrid) is from Community Toolkit. 

**Expected behavior**
Combobox flyout should be attached/near the combobox, either below or above but not far away .

**Screenshots**
![grafik](https://user-images.githubusercontent.com/471338/115208497-eb035900-a0fc-11eb-8be9-66b2c9a51255.png)

**Version Info**
Reunion 0.5.5

NuGet package version: 
WinUI 3 - Project Reunion 0.5: 0.5.5

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Marv51** [comment]
nobody?

**Comment by StephenLPeters** [comment]
Very strange that we didn't see this until you commented on it.. Sorry about that I think it must be a github bug since it wasn't appearing in our query.

I haven't looked into this but its possible combo box is measuring the flyout content while it is in a state that results in the wrong value being returned. causing combo box to think the flyout to be a different size than it ends up being. If that's the case, then I would expect this issue to not reproduce if you use a panel with explicate sizing on it.  Can you try that out?

**Comment by Marv51** [comment]
It looks like the top left corner of that dropdown is always in the same spot, when using a custom panel?

When I add an explicit height to the panel the bottom edge of the popup gets adjusted. The top remains in the same spot.


Simpler example without custom panel:
```xaml
  <ComboBox.ItemsPanel>
        <ItemsPanelTemplate>
             <Grid Width="500" Height="150" />
        </ItemsPanelTemplate>
   </ComboBox.ItemsPanel>
```
results in: 
![image](https://user-images.githubusercontent.com/471338/117407118-61ca8f80-af0e-11eb-995c-a18477693e67.png)

**Comment by Marv51** [comment]
I tried to create a simple project that reproduces this issue but failed. Any ideas what could cause this? 

It reliably reproduces in my app, but when I create a new project very similar XAML works correctly.

**Comment by ranjeshj** [comment]
@Marv51 I'm not sure why it would be different in just your app. Do you happen to have a style for ComboBox that is setting some properties in your project maybe ?

**Comment by Marv51** [comment]
Maybe just something weird with my project.... I'll close this for now.
