### ISSUE TITLE
Live Visual Tree crashes WinUI Application due to Access Violation

### ISSUE THREAD

**Issue by jschwizer99** [microsoft/microsoft-ui-xaml#4854]
**Describe the bug**
With a fully updated development environment, Visual Studio 2019 16.10.0 Preview 2 and WinUI Reunion 0.5.5 clicking on a control in the Live Visual Tree triggers an Access Violation. The break-point cannot be silenced as other exceptions. As a consequence, the Live Visual Tree cannot be used anymore. 

The issue seems not to be related to the latest Reunion 0.5.5 update as it can also be observed with Reunion 0.5.0.

Currently, I guess that it could be related to Visual Studio 16.10.0 Preview 2 as it was observed after Visual Studio Update from 16.10 Preview 1. But as I cannot downgrade anymore a Preview version :-( this is just a hypothesis.

Any idea for a fast workaround is highly welcome.

**Steps to reproduce the bug**
- Start a basic WinUI application in x64 Debug mode
- Open Live Visual Tree
- Click in the tree on any control like grid, textbox, or button
  -> Exception thrown at 0x00007FFE104DB93E (Microsoft.VisualStudio.DesignTools.WinUITap.dll) in Sandbox.exe: 0xC0000005: Access violation reading location 0x0000000000000038

Or

- Create blank WinUI C++ App
- Start application in x64 Debug mode
- Open Live Visual Tree
- Click on the button element in the tree

Callstack
```
>	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffe1b80b93e()
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffe1b88e4cc()
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffe1b913c6d()
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffe1b919fd7()
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffe1b9557fc()
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffe1b957edf()
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!00007ffe1b9b0a69()
 	kernel32.dll!00007ffe8f2b7034()	Unknown
 	ntdll.dll!00007ffe909a2651()	Unknown
```

**Expected behavior**
Live Visual Tree does not crash WinUI application

**Screenshots**
![image](https://user-images.githubusercontent.com/7672712/115207652-13d71e80-a0fc-11eb-8b2e-49e0b5134418.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0] 
[WinUI 3 - Project Reunion 0.5: 0.5.5]

Visual Studio:
VS 2019 Preview 16.10.0 Preview 2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

**Comment by alwu-msft** [comment]
@StephenLPeters, this is @RealTommyKlein's bailiwick.

**Comment by jschwizer99** [comment]
@RealTommyKlein Many thanks for the help. The side-by-side installation of Preview 1 to Preview 2 was smooth. With Preview 1 the Live Visual Tree can be used again.

**Comment by HO-COOH** [comment]
I am running into this issue again.
![image](https://github.com/user-attachments/assets/f3f6cdf3-f37f-439a-980e-cebc220a8bda)

It runs fine without live xaml tree, but as soon as you enable it(while the app is running), it crashes and cannot be recovered (continue)

**Comment by wbokkers** [comment]
I see this issue again as well. It happens when a Window closes.

It happened with Windows App SDK before 1.6 only when the TitleBar was customized. With 1.6 it happens all the time.

**Comment by aries-zhang** [comment]
Same here, on WinAppSDK 1.6.240829007
```
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240829007" />
```


![image](https://github.com/user-attachments/assets/c449460a-692b-4aa3-afcf-5498c32a0162)
![image](https://github.com/user-attachments/assets/78c18459-79b4-4942-97d0-0ae1ff67e5fb)
