### ISSUE TITLE
[WinUI3 Reunion 0.5.5] StyleTypedProperty, TemplateVisualState and TemplatePart attributes cannot be set multiple times anymore

### ISSUE THREAD

**Issue by kalin-todorov** [microsoft/microsoft-ui-xaml#4855]
**Describe the bug**
Cannot build our WinUI3 desktop project after upgrading to Reunion 0.5.5 due to the StyleTypedProperty, TemplateVisualState and TemplatePart attributes. They don't allow to be set multiple times as before.

**Steps to reproduce the bug**
Try to build the following code:

```
[StyleTypedProperty(Property = "SeparatorStyle", StyleTargetType = typeof(Button))]
[StyleTypedProperty(Property = "ItemContainerStyle", StyleTargetType = typeof(Button))]
public class CustomControl : Control
{
}
```

**Screenshots**
Here the StyleTypedPropertyAttribute definition before:
![image](https://user-images.githubusercontent.com/8479530/115254040-a47e2080-a135-11eb-981b-5e949e440cb9.png)
And here is now in 0.5.5:
![image](https://user-images.githubusercontent.com/8479530/115254076-ae078880-a135-11eb-86e2-bc92ec810af5.png)

AllowMultiple attribute is missing.

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.5] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes|

**Comment by StephenLPeters** [comment]
@MikeHillberg I'm not sure what team this would fall under, thoughts?

**Comment by codendone** [comment]
@Scottj1s The issue discussed earlier today...

**Comment by jeromelaban** [comment]
This is indeed a blocker to upgrade to 0.5.5 for Windows specific controls of Uno Platform as well.

**Comment by Scottj1s** [comment]
@jeromelaban, this issue has been resolved and will be included in the next Project Reunion servicing release (tentatively, version 0.5.6).
