### ISSUE TITLE
High CPU load when using a GroupStyle in a ListView

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#4860]
**Describe the bug**
When a GroupStyle is defined in a ListView, the CPU load is very high (> 2 % on my Core i9 8th gen).
Even when the view is not used or inactive.

**Steps to reproduce the bug**
1. Define a ListView
2. Add a GroupStyle to the ListView.GroupStyle property
3. Create a default style resource for TargetType="ListViewHeaderItem"
4. Create a grouped list and assign it to a CollectionViewSource
5. Assign the ItemsSource of the ListView to the View property of the CollectionViewSource

I created a repository that demonstrates the issue:
https://github.com/wbokkers/reunion-issue-high-cpu

**Expected behavior**
When the view is not interacted with or inactive, the CPU load should be around 0%

**Screenshots**

![image](https://user-images.githubusercontent.com/4835617/115359746-45fd8480-a1bf-11eb-817d-b9fcd93f47b4.png)

**Version Info**

NuGet package version: 
WinUI 3 - Project Reunion 0.5: 0.5.5

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@bartekk8 and @MikeHillberg FYI

**Comment by wbokkers** [comment]
We still see high CPU loads with Reunion 0.8 Preview.

**Comment by wbokkers** [comment]
With Windows App SDK 1.1.4 I see high CPU loads (again). :(
