### ISSUE TITLE
Question: Could you please backport NavigationBackButtonNormalStyle to WinUI 2?

### ISSUE THREAD

**Issue by omikhailov** [microsoft/microsoft-ui-xaml#4861]
Fluent design guidelines suggest to use branding colors for NavigationView, but if you'll actually try it with latest WinUI 2.6 Preview, you'll notice that Back button foreground color does not match foreground of other elements within NavigationView. This seems already fixed in WinUI 3, because there are two styles in the repository:

https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/NavigationBackButton_v1.xaml
and
https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/NavigationBackButton.xaml

I guess that first one is for WinUI 2 and second one is for WinUI 3, because it uses NavigationViewItemForeground as foreground.

Please port that second style to WinUI 2.6.

And as a side note: in future versions of WinUI 3, it makes sense to allow changing style of back button in the same way as it works for menu button.

**Comment by StephenLPeters** [comment]
NavigationBackButton_v1.xaml and NavigationBackButton.xaml are both used in Winui2 (and currently winui3 as well).  They are swapped in and out using the XamlControlsResources ControlsResourcesVersion property.  Today by default we use the V1 styles, but if you set that property to Version2 we'll use the updated styles. It sounds like you are reporting an issue with the V1 style in winui2? Can you provide a screenshot of the issue?

**Comment by omikhailov** [comment]
Sure, V1:

![image](https://user-images.githubusercontent.com/75426711/115548366-111d2a80-a2b0-11eb-90e7-e88556ff6358.png)

V2:

![image](https://user-images.githubusercontent.com/75426711/115548440-23976400-a2b0-11eb-9503-ceacc4acec3f.png)

Thanks for the help!

**Comment by omikhailov** [comment]
V2 is still under construction, right? After switching to this version I immediately noticed that hamburger menu button does not work correct in LeftMinimal mode. Should I report such bugs or these styles will be anyway tested before release?

**Comment by chingucoding** [comment]
I think it's still worth pointing out those bugs and creating issues. Regarding the BackButton style, @StephenLPeters can we just backport the V2 changes/style or is there anything we need to watch out for? I would look into this then.

**Comment by StephenLPeters** [comment]
I don't think we should use the V2 style in V1, the V2 style uses animated icon.  It does seem like there might be a color issue with the V1 style.  @chingucoding if you'd like to take a look that would be awesome.

**Comment by omikhailov** [comment]
@StephenLPeters  I agree, moving only one line from V2 to V1 would be enough to fix color:

`<Setter Property="Foreground" Value="{ThemeResource NavigationViewItemForeground}" />`
instead of
`<Setter Property="Foreground" Value="{ThemeResource SystemControlForegroundBaseHighBrush}" />`
