### ISSUE TITLE
RadioButtonOuterEllipseFill lightweight radio button style does not work

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4872]
**Describe the bug**
The lightweight style `RadioButtonOuterEllipseFill` (see documentation [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.radiobutton?view=winrt-19041)) does not work. This was working before in UWP at some point.

**Steps to reproduce the bug**
```xaml
 <RadioButton>
    <RadioButton.Resources>
           <ResourceDictionary>
                 <SolidColorBrush x:Key="RadioButtonOuterEllipseFill" Color="Red" />
                 <SolidColorBrush x:Key="RadioButtonOuterEllipseFillPointerOver" Color="Green" />
            </ResourceDictionary>
    </RadioButton.Resources>
</RadioButton>
```
RadioButton is filled white, and when hovered over changes to green, when it should be shown as a radiobutton filled in red that changes to green when pointer is over. Observe that `RadioButtonOuterEllipseFill` is not applied at all.

**Version Info**

NuGet package version:  
WinUI 3 - Project Reunion 0.5: 0.5.5

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
While I am not super familar with how WinUI works behind the scenes, I would guess that [this line](https://github.com/microsoft/microsoft-ui-xaml/blob/2c1d7144a0c5ffe4fae25f0be2fdaf40bd41973c/dev/CommonStyles/RadioButton_themeresources.xaml#L387) should also be a ThemeResource instead of a StaticResource.

**Comment by StephenLPeters** [comment]
I think your analysis is correct. That line should be a theme resource. I beleive if you provide it in the override in this location it will work:
```
<Application.Resources>
  <XamlControlsResources>
    <XamlControlsResources.MergedDictionaries>
      <ResourceDictionary>
        <SolidColorBrush x:Key="RadioButtonOuterEllipseFill" Color="YourOverrideColor"/>
 ...
```

**Comment by StephenLPeters** [comment]
Additionally, this visual state group is the default state and should not have any setters: https://github.com/microsoft/microsoft-ui-xaml/blob/2c1d7144a0c5ffe4fae25f0be2fdaf40bd41973c/dev/CommonStyles/RadioButton_themeresources.xaml#L220

**Comment by StephenLPeters** [comment]
@karenbtlai FYI

**Comment by karenbtlai** [comment]
> Additionally, this visual state group is the default state and should not have any setters:
> 
> https://github.com/microsoft/microsoft-ui-xaml/blob/2c1d7144a0c5ffe4fae25f0be2fdaf40bd41973c/dev/CommonStyles/RadioButton_themeresources.xaml#L220

The setters for the CommonStates were necessary for the colour animations to animate back to the correct colour. It seems when the colour animation bindings were updated they weren't removed, let me investigate and will remove them if necessary.

>I would guess that this line should also be a ThemeResource instead of a StaticResource.

I can send a fix out for that as well.

**Comment by chingucoding** [comment]
@karenbtlai Do you have any updates on this? ^^
