### ISSUE TITLE
It is hard to hit the menu button of NavigationView when app extends view into Title Bar

### ISSUE THREAD

**Issue by omikhailov** [microsoft/microsoft-ui-xaml#4874]
**Describe the bug**
When NavigationView is in LeftMinimal mode, menu button works not as expected.

**Steps to reproduce the bug**
Create new UWP app with WinUI 2.6 and set styles version = Version2

``` 
    <Application.Resources>
        <wc:XamlControlsResources ControlsResourcesVersion="Version2">
            <wc:XamlControlsResources.MergedDictionaries>
                
            </wc:XamlControlsResources.MergedDictionaries>
        </wc:XamlControlsResources>
    </Application.Resources>
```

Add NavigationView to the MainPage

Run the app and decrease window width. NavigationView will switch to LeftMinimal mode.

Try to click in the center of hamburger menu button - it will not open the pane.
Click in the right bottom corner of menu button - and pane will open.

**Expected behavior**
Whole surface of menu button should be clickable, not just right bottom corner.

**Version Info**
WinUI 2.6 Preview

**Comment by StephenLPeters** [comment]
I tried this out with my test app and am not able to reproduce the issue. Could you please make a gif of the issue?

**Comment by omikhailov** [comment]
@StephenLPeters Seems like this happens only when application extends view into Title Bar. Here is a sample project to reproduce:
[App2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6365677/App2.zip)

**Comment by StephenLPeters** [comment]
Thank you! the repro is very helpful.

**Comment by StephenLPeters** [comment]
This issue does not appear to be unique to the new styles, Changing the ControlsResourcesVersion to Version1 still has the issue.  @jevansaks or @Austin-Lamb do you know if extends view into title bar is supposed to be eating mouse input?

**Comment by jevansaks** [comment]
Yes. ExtendsViewIntoTitlebar means you need to supply a visual that represents the hittable region of your titlebar. Are you calling [Window.SetTitlebar](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.window.settitlebar?view=winrt-19041)?

[Do define a draggable region that matches the visual title bar.](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#dos-and-donts)

**Comment by omikhailov** [comment]
Ok, I checked and agree, this behavior is exactly what standard UWP NavigationView had. So, this is not a bug, but a missing feature that would be nice to have in future versions of WinUI.
