### ISSUE TITLE
Inherited DataTemplate not rendering in WinUI for Desktop

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4875]
The following markup renders correctly

```
<ContentControl>
    <ContentControl.ContentTemplate>
        <DataTemplate>
            <TextBlock Text="A"/>
        </DataTemplate>
    </ContentControl.ContentTemplate>
</ContentControl>
```

But if DataTemplate is inherited, nothing is rendered

```
public class MyDataTemplate : DataTemplate
{
}
```

```
<ContentControl>
    <ContentControl.ContentTemplate>
        <local:MyDataTemplate>
            <TextBlock Text="A"/>
        </local:MyDataTemplate>
    </ContentControl.ContentTemplate>
</ContentControl>
```

Here it is the repo project

[App9.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6352306/App9.zip)

**Comment by arivoir** [comment]
More info. Calling LoadContent of the inherited DataTemplate doesn't work either. It returns null.

**Comment by StephenLPeters** [comment]
@arivoir do you know if this works in a UWP?

@MikeHillberg FYI

**Comment by arivoir** [comment]
No. I know it works in WPF

**Comment by chrisglein** [comment]
@arivoir For your repro the derived class from `DataTemplate` doesn't actually add anything. I'm assuming that's just to produce a min repro. But can you capture what you intended to do with a derivation of `DataTemplate`? AKA, what was the scenario?

**Comment by arivoir** [comment]
We're using DataTemplate to allow customers specifying icon templates, which are created from a class inherited from DataTemplate (they can be instantiated multiple times for the same control). It's a way to say customers that template is to specific  for icons.
