### ISSUE TITLE
Question: Documentation ProjectReunion/WinUI

### ISSUE THREAD

**Issue by get-flat** [microsoft/microsoft-ui-xaml#4879]
Following: https://docs.microsoft.com/pl-pl/windows/apps/project-reunion/get-started-with-project-reunion step 6
> To use WinUI 3 tooling such as Live Visual Tree, Hot Reload, and Live Property Explorer in Visual Studio 2019 16.10 Preview, you must enable WinUI 3 tooling with Visual Studio Preview Features. For instructions, see How to Enable UI Tooling for WinUI 3 in VS 16.9 Preview 4.

Following: https://github.com/microsoft/microsoft-ui-xaml/issues/4140
> Click on "Enable UI Debugging Tooling for WinUI 3 Projects"

I don't see "Enable UI Debugging Tooling for WinUI 3 Projects" item in VS Version 16.10.0 Preview 2.0.

**Comment by StephenLPeters** [comment]
@JeanRoca FYI

**Comment by JeanRoca** [comment]
@RealTommyKlein I just updated to VS 16.10 P2.1 and am also not seeing the option to enable UI Tooling. Is this a known issue?

**Comment by RealTommyKlein** [comment]
@JeanRoca @get-flat - that step should no longer be required as of 16.10 Preview 2, the tooling is enabled by default.

**Comment by get-flat** [comment]
@RealTommyKlein It does not work for me. (no UI reload, no in-app toolbar etc.)
Additionally  selecting anything in Live Visual tree throws:
Exception thrown at 0x7A938221 (Microsoft.VisualStudio.DesignTools.WinUITap.dll) in App1.exe: 0xC0000005: Access violation reading location 0x0000001C.

 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!winrt::Windows::Foundation::operator==(struct winrt::Windows::Foundation::IUnknown const &,struct winrt::Windows::Foundation::IUnknown const &)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::DispatcherHelper::operator==(std::nullptr_t)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::UILayerManager::RunOnUIThread(class std::function<void > const &)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::WindowsXamlDiagnosticsTap::HandleHostSelectionChange(class web::json::value)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!`Microsoft::VisualStudio::DesignTools::Ipc::ProtocolHandler::Register<`Microsoft::VisualStudio::DesignTools::UwpTap::WindowsXamlDiagnosticsTap::RegisterCommandSuppressedMessageHandler'::`2'::<lambda_1>>'::`2'::<lambda_1>::operator()()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::Ipc::ProtocolHandler::ProcessInboundMessage(class Microsoft::VisualStudio::DesignTools::Ipc::Message &&)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::Ipc::ProtocolHandler::ProcessThread(void)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!std::thread::_Invoke<class std::tuple<void ( Microsoft::VisualStudio::DesignTools::Ipc::ProtocolHandler::*)(void),class Microsoft::VisualStudio::DesignTools::Ipc::ProtocolHandler *>,0,1>(void *)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!thread_start<unsigned int (__stdcall*)(void *)>()	Unknown
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
>	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

**Comment by RealTommyKlein** [comment]
@get-flat - the in-app toolbar isn't currently supported, so that's expected.  For the LVT exception, that looks like #4854, which will be fixed in 16.10 Preview 3 (and is also likely causing the no Hot Reload issue - if you don't select anything in the Live Visual Tree, does Hot Reload work?).  There's also a workaround [here](https://github.com/microsoft/microsoft-ui-xaml/issues/4854#issuecomment-822852473) - thanks!

**Comment by ichan-akira** [comment]
I actually cannot found Live Visual Tree and Live Property Explorer in VS 16.10 Preview 3.

**Comment by KenionX** [comment]
Using 16.11.0 Preview2.0 hotreload doesnt work at all, if I go on LVT it says "install latest winUI and visual studio"

**Comment by RealTommyKlein** [comment]
@KenionX - due to breaking changes in Reunion 0.8, the currently released version of Visual Studio doesn't support the LVT in 0.8.  The upcoming [16.11 Preview 3 will support 0.8](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#known-issues).
