### ISSUE TITLE
WinUI 3 - ProjectReunion: ComboBox expander not applying RequestedTheme

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/microsoft-ui-xaml#4885]
**Describe the bug**
I have an application, where App.RequestedTheme = ApplicationTheme.Light
But, when I'm creating a ComboBox, which has RequestedTheme = Dark, expander will be Light

**Screenshots**
![image](https://user-images.githubusercontent.com/50652041/115868353-00ea8400-a445-11eb-8dc7-291a03548a16.png)
![image](https://user-images.githubusercontent.com/50652041/115868363-03e57480-a445-11eb-9dd4-923e0b4db32a.png)

**Version Info**

NuGet package version:
WinUI 3 - Project Reunion 0.5: 0.5.5

Windows app type:
| UWP              | Win32            |
| :--------------- | :---------------: |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :--------------------: |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :---------------: |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
This does not reproduce with Winui2. @Austin-Lamb or @codendone FYI. Do we need to do something to propagate requested theme to parented popups in winui3?
