### ISSUE TITLE
DataTransferManager.GetForCurrentView() in WinUI 3

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4886]
**Describe the bug**
Calling `DataTransferManager.GetForCurrentView()` fails with a `System.Runtime.InteropServices.COMException: 'Element not fount'.` This is somewhat expected, given the 'GetForCurrentView' name. 

However, I have not found any mention of this particular class. Especially not in the [WinRT API changes for Desktop apps](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/winrt-apis-for-desktop.md).

Is cleaning this up already somewhere on your radar? Can I work around this to make a share dialog work in WinUI 3?

**Steps to reproduce the bug**
 ```csharp
var dataTransferManager = DataTransferManager.GetForCurrentView();
dataTransferManager.DataRequested += DataTransferManager_DataRequested;
```

**Version Info**

NuGet package version: 
WinUI 3 - Project Reunion 0.5: 0.5.5

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by sylveon** [comment]
You need to use [IDataTransferManagerInterop](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-idatatransfermanagerinterop)

**Comment by Marv51** [comment]
Thanks! IDataTransferManagerInterop is exactly what I was looking for. 

I'm using CsWin32, and with that the code to get the DataTransferManager for the current view is:
```csharp
var guid = Guid.Parse("a5caee9b-8708-49d1-8d36-67d25a8da00c");
IDataTransferManagerInterop iop = DataTransferManager.As<IDataTransferManagerInterop>();
ABI.Windows.ApplicationModel.DataTransfer.DataTransferManager* transferManager = null;
iop.GetForWindow(PInvoke.GetActiveWindow(), guid, (void**)&transferManager);
var realManager = ABI.Windows.ApplicationModel.DataTransfer.DataTransferManager.FromAbi((IntPtr)transferManager);
```

I filed an [issue](https://github.com/microsoft/CsWin32/issues/246) over at CSWin32 to see if that can be simplified in the future, but it works for now.

Thanks!

**Comment by asklar** [comment]
CC @anawishnoff to see if we can update the winui doc to mention this api. In general, any GetForCurrent*** api will not work and you need to use an alternative, but sometimes like in this case the alternative may not be obvious.

**Comment by anawishnoff** [comment]
Thanks! We're planning on publishing this doc to our official docs site soon with some changes and this API should be included.

**Comment by Marv51** [comment]
@anawishnoff Just saw that you added DataTransferManager to the [new page](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api).

Thanks!

**Comment by sylveon** [comment]
I did 🙃 https://github.com/MicrosoftDocs/windows-uwp/pull/3090

**Comment by Marv51** [comment]
@sylveon Ups, sorry! Only saw the [PR](https://github.com/microsoft/microsoft-ui-xaml/pull/4943) by Ana that removes the old page.

**Comment by shuice** [comment]
> IDataTransferManagerInterop is exactly what I was looking for.
> 
> I'm using CsWin32, and with that the code to get the DataTransferManager for the current view is:
> 
> ```cs
> using WinRT;
> 
> var guid = Guid.Parse("a5caee9b-8708-49d1-8d36-67d25a8da00c");
> var iop = DataTransferManager.As<IDataTransferManagerInterop>();
> var transferManager = IntPtr.Zero;
> iop.GetForWindow(PInvoke.GetActiveWindow(), guid, (void**)&transferManager);
> var realManager = DataTransferManager.FromAbi(transferManager);
> ```
> 
> I filed an [issue](https://github.com/microsoft/CsWin32/issues/246) over at CSWin32 to see if that can be simplified in the future, but it works for now.
> 
> Thanks!
> 
> Maybe a comment could be added to the `DataTransferManager` docs or [this document](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/winrt-apis-for-desktop.md)?

I use the following on WinUI3, It's works, a little different on function GetForWindow, and different to page [migrate-to-windows-app-sdk/guides/winui3](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/winui3)
```cs
private void http_server_demo_share_send_uri(string uri)
{
        IntPtr windowHandle = WinRT.Interop.WindowNative.GetWindowHandle(this);
        IDataTransferManagerInterop interop = Windows.ApplicationModel.DataTransfer.DataTransferManager.As<IDataTransferManagerInterop>();

        var guid = Guid.Parse("a5caee9b-8708-49d1-8d36-67d25a8da00c");
        var iop = DataTransferManager.As<IDataTransferManagerInterop>();
        var transferManager = DataTransferManager.FromAbi(iop.GetForWindow(windowHandle, guid));
        transferManager.DataRequested += (DataTransferManager dtm, DataRequestedEventArgs args) =>
        {
                DataPackage dataPackage = new DataPackage();
                dataPackage.SetWebLink(new Uri(uri));
                dataPackage.Properties.Title = "Share uri \"" + uri + "\"";
                args.Request.Data = dataPackage;
        };

        interop.ShowShareUIForWindow(windowHandle);
}


[System.Runtime.InteropServices.ComImport, System.Runtime.InteropServices.Guid("3A3DCD6C-3EAB-43DC-BCDE-45671CE800C8")]
[System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]
interface IDataTransferManagerInterop
{
        IntPtr GetForWindow([System.Runtime.InteropServices.In] IntPtr appWindow, [System.Runtime.InteropServices.In] ref Guid riid);
        void ShowShareUIForWindow(IntPtr appWindow);
}
```
