### ISSUE TITLE
Grid: RowDefinition's MaxHeight is not working when placed in a StackPanel

### ISSUE THREAD

**Issue by carldebilly** [microsoft/microsoft-ui-xaml#4887]
**Describe the bug**
Put the following XAML in _XAML Studio_:
``` xml
    <StackPanel>
        <StackPanel Orientation="Horizontal" Spacing="8">

            <!-- Reference-->
            <Rectangle VerticalAlignment="Center" Fill="Red" Stroke="Black" StrokeThickness="4" Width="60" Height="20" />

            <Grid VerticalAlignment="Center" Background="Red" BorderBrush="Black" BorderThickness="4" Width="60">
                <Grid.RowDefinitions>
                    <RowDefinition MinHeight="12" />
                </Grid.RowDefinitions>
            </Grid>

            <Grid VerticalAlignment="Center" Background="Red" BorderBrush="Black" BorderThickness="4" Width="60">
                <Grid.RowDefinitions>
                    <RowDefinition MaxHeight="12" />
                </Grid.RowDefinitions>
                <Rectangle Height="30" />
            </Grid>
        </StackPanel>
    </StackPanel>
```
Output in XAML Studio:
![image](https://user-images.githubusercontent.com/4174207/115898075-24083a00-a42b-11eb-84b8-f03a66f61579.png)

**Expected behavior**
I Expect the result to be like the following:
![image](https://user-images.githubusercontent.com/4174207/115897193-2a49e680-a42a-11eb-91cb-745e57808f24.png)

Since the `MaxHeight="12"` should limit the inner `<Rectangle />` to `12px`.

**Workaround !! _WHERE THINGS ARE GETTING WEIRD_ !!**
If you remove the outer `<StackPanel />` it's working as expected.

**Version Info**

NuGet package version: None

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes                 |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Wow, this is so strange.  To be clear, this issue is present in System Xaml and is not unique to XamlStudio.  Removing the outermost stack panel results in the expected picture.

**Comment by StephenLPeters** [comment]
@MikeHillberg and @chrisglein FYI, I'm not sure who owns this, putting it on Controls for now.

**Comment by carldebilly** [comment]
This problem still present in WinUI

**Comment by ztowne13** [comment]
This is still an issue in WinUI. I also think it is an issue when nested within a ScrollViewer
