### ISSUE TITLE
StorageFile.CreateStreamedFileAsync throws wrong thread exception

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#4895]
**Describe the bug**
```csharp
var storageFile = await StorageFile.CreateStreamedFileAsync("test.png", OnStorageFileNeeded, null)
```
throws a COMException with is claiming to be on the wrong thread. This is happening for me on the UI thread, which I think should work and has worked in WinUI 2.
(I have some difficulty in providing more information, as for me VisualStudio 2019 16.10 Preview 2.1 becomes completely unresponsive when this exception is encountered. Restarting explorer.exe enabled me to recover from this exception.)

**Expected behavior**
Should not throw exception, this was working in UWP / WinUI 2.

**Version Info**

NuGet package version: 
WinUI 3 - Project Reunion 0.5: 0.5.5

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@Scottj1s could this be a cs winrt issue?

@Austin-Lamb or @MikeHillberg FYI

**Comment by codendone** [comment]
Some StorageFile APIs, such as CopyAsync(), only work in a UWP. I'm not sure if that is impacting here.

Is the error happening in the StorageFile.CreateStreamedFileAsync call itself, or is the error perhaps happening in your OnStorageFileNeeded callback?

**Comment by Marv51** [comment]
@codendone Any call to `StorageFile.CreateStreamedFileAsync` throws this exception for me regardless of context.

**Comment by manodasanW** [comment]
I believe this is the same issue as https://github.com/microsoft/CsWinRT/issues/612 .  I am able to repro to this issue and should able to confirm whether my fix resolves it or not once I am done.

**Comment by Marv51** [comment]
This seems to be working now 🥳
