### ISSUE TITLE
Inherits TabViewItem crash with Microsoft C++-Exception: winrt::hresult_error 

### ISSUE THREAD

**Issue by AndyMahub** [microsoft/microsoft-ui-xaml#4900]
Hi,

i have created only a empty MyTabViewItem-Class with inherits to TabViewItem like this:

> using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.UI.Xaml.Controls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace VereinsOrdner
{
    public class MyTabViewItem : TabViewItem
    {
    }
}

Nothing more. Then i have in MainWindow-Class this method:

> public void OpenNewTab(Type Page, string Header, PageParameters p = null)
        {
            MyTabViewItem t = new MyTabViewItem();
            t.Header = Header;
            t.IsClosable = true;
            Frame frame = new Frame();
            frame.Navigate(Page, p);
            t.Content = frame;
            Tabs.TabItems.Add(t);
            //Tabs.SelectedItem = t;
        }

Okay, i start my app and after the OpenNewTab-Method i receive this message:

> Ausnahme ausgelöst bei 0x75E0A6E2 (KernelBase.dll) in VereinsOrdner.exe: WinRT originate error - 0x800F1000 : 'ListViewItemPresenter can only be used as the first child in the template for a ListViewItem.'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!770411A5: (caller: 76F57BB6) ReturnHr(1) tid(7c5c) 8007007E Das angegebene Modul wurde nicht gefunden.
Ausnahme ausgelöst bei 0x75E0A6E2 in VereinsOrdner.exe: Microsoft C++-Ausnahme: winrt::hresult_error bei Speicherort 0x0317D890.

I don't know, is this my fault, or is this a bug? I would like to expand the TabViewItem with a few own functions.

Thanks for your time and help
Andy

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion 0.5.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | No   |
| May 2020 Update (19041)            | Yes    |

**Comment by StephenLPeters** [comment]
@karenbtlai who saw something similar to this recently as well

**Comment by StephenLPeters** [comment]
@beervoley the tabview expert

**Comment by beervoley** [comment]
@AndyMahub did you have any TabViewItems in XAML markup inside TabView by default before your fix?

**Comment by AndyMahub** [comment]
@beervoley No, in the XAML was nothing between <TabView>-Tabs. Only Attributes like Background and x:Name. 

After a long search, i have add a empty "own Tab"(in the XAML) and it works. 

You can reproduce this. Create a own (empty) class with inherits TabViewItem, create a empty XAML without TabViewItem-Tags and in Code-Behind you add a Tab from the inherited class. App crashes. But if you add a empty Tab in XAML and remove this after app starting in code behind, it works. For me.

**Comment by FreddyD-GH** [comment]
Any ideas for a workaround if your TabViewItem-derived class can't be instantiated in XAML (i.e. no default constructor)?
