### ISSUE TITLE
null ref exception when click on an element in Visual Tree

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#4912]
why this happen? vs16.9.4

![image](https://user-images.githubusercontent.com/12285582/116374433-da5f8b00-a840-11eb-9263-0cf06d47665d.png)

**Comment by StephenLPeters** [comment]
I'm not sure. We'll need more information to answer the question.

**Comment by HppZ** [comment]
what do you need?

**Comment by marb2000** [comment]
@HppZ we need more information about your scenario. What are Reunion version are you using? what are the steps to repro this behavior? A repro code will be super helpful so we can help you satisfactorily?

**Comment by manodasanW** [comment]
@HppZ Can you also provide a stack from when the exception hits?

**Comment by asklar** [comment]
@HppZ Are you seeing this with WinUI 3 or with system XAML/WinUI 2.x?
if it's system XAML/WinUI 2.x, make sure that your app is referencing Microsoft.NETCore.UniversalWindowsPlatform **6.2.12**
Can you try that and confirm if that solves it for you?

**Comment by HppZ** [comment]
it is system XAML and my app is referencing Microsoft.NETCore.UniversalWindowsPlatform 6.2.12.

**Comment by asklar** [comment]
thanks. Adding @RealTommyKlein

**Comment by HppZ** [comment]
I'll post stack next time I hit that ex.

**Comment by RealTommyKlein** [comment]
Thanks for the report - this will be fixed in an upcoming Windows SDK.  As a workaround, you can add this to your project file and rebuild:
```
<PropertyGroup>
  <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
</PropertyGroup>
```

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/117571768-7e2f1d80-b102-11eb-918f-39b6acaaad65.png)

how to fix this?

**Comment by HppZ** [comment]
> Thanks for the report - this will be fixed in an upcoming Windows SDK. As a workaround, you can add this to your project file and rebuild:
> 
> ```
> <PropertyGroup>
>   <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
> </PropertyGroup>
> ```

not work
![image](https://user-images.githubusercontent.com/12285582/117572048-ae2af080-b103-11eb-8195-823e0bb78e8d.png)

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/117655618-e39a1180-b1c9-11eb-8b1a-d4f46d8ebe30.png)

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/117655699-00cee000-b1ca-11eb-8609-d5c7eb319afb.png)

**Comment by evelynwu-msft** [comment]
The reflection-based TypeInfoProvider has been disabled by default for a couple years now so presumably this issue is now moot.
