### ISSUE TITLE
Null Reference Exception in ABI.Microsoft.UI.Xaml.Data.ICustomProperty

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/microsoft-ui-xaml#4926]
**Describe the bug**
First think, I'm not sure, it should be here, but I don't know about better place.

In my app I get Null Reference exception, when I'm trying to Notify Property Change. Null exception but throw after some time, with no specific time or user flow through app, it is random. Problem is probably in function Do_Abi_GetValue_2, but i'm not sure. Here is stack trace of exception:
![image](https://user-images.githubusercontent.com/16069721/116401426-86967700-a82b-11eb-8058-fc2c76d29738.png)

Exception has no other useful information (I think), no keys or values related to exception. I tried to find, what was null, but without success.

**Steps to reproduce the bug**
[Repo link](https://github.com/JanRajnoha/CloudCash-GitHubIssue) - This is copy of real repo, but with changed DB info
1. Start app packaged
2. Sign as User
3. Do some sells and payments
4. Tables
5. Click on T1
6. Do sell by click on some product
7. Pay by Pay button
8. Do payment (you could split table, transfer items, ...)
9. After a few steps between tables view, table and payment you will get Null Reference Exception

**Expected behavior**
No exception, property changed notification should work okay.

**Version Info**
Windows 10 Insider, tested on multiple versions including 21364.1

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.6] 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21364.1)              | Yes    |
| May 2020 Update (19041)            | Not tested   |
| November 2019 Update (18363)       | Not tested    |
| May 2019 Update (18362)            |  Not tested   |
| October 2018 Update (17763)        |  Not tested    |

**Additional context**

**Comment by JanRajnoha** [comment]
@andrewleader thanks for response.

**Comment by StephenLPeters** [comment]
@Scottj1s is this stack cswinrt code?

**Comment by JanRajnoha** [comment]
Hi @Scottj1s, could you confirm that stack trace is from WinRT?

**Comment by Marv51** [comment]
I'm also hitting this seemingly randomly every once in a while PropertyChanged throws exactly this NullReferenceException with the StackTrace above.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ABI.Microsoft.UI.Xaml.Data.ICustomProperty.Vftbl.Do_Abi_GetValue_2(IntPtr thisPtr, IntPtr target, IntPtr* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.System.ComponentModel.PropertyChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, PropertyChangedEventArgs e)
   at MyApp.ZoneArea.set_Origin(Vector2 value)
```

Is there any additional information we can provide to aid in debugging this?

Not knowing when and how often this crash will occur in production makes me quite nervous to deploying our app.

**Comment by JanRajnoha** [comment]
@Marv51 bug is reported in CsWinRt and is planned for release 1.2.8 for June 15

**Comment by Marv51** [comment]
Is there any kind of workaround to work with WinUI 3 and PropertyChanged notifications more reliably? My app crashes from this after maximum 10 minutes of use, is that the experience that everyone is having? 
@anawishnoff or @SavoySchuler?

**Comment by Marv51** [comment]
I can confirm that this is still reproduces in 0.8.0-preview

**Comment by JanRajnoha** [comment]
@Marv51 I think it is not related to WinUI (as bug location), so reunion 0.8 won't affect it.

**Comment by akilarajesh1313** [comment]
Closing this issue as it seems to have been resolved, see thread: https://github.com/microsoft/CsWinRT/issues/840
