### ISSUE TITLE
A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#4935]
The following WInUI related compilation error occured while building the respective Uno Platform head. Uno team delegated the issue right here. 

https://github.com/unoplatform/uno/issues/5864

**Comment by StephenLPeters** [comment]
It looks like the Uno team is sill looking for a repro to investigate the issue. @jeromelaban Will you report back to us if you determine it is likely our issue?
