### ISSUE TITLE
Binding failed to convert value of an inherited type to a base type

### ISSUE THREAD

**Issue by AlexanderEgorov** [microsoft/microsoft-ui-xaml#4936]
**Describe the bug**
Bindings failed to convert value of an inherited type to a base type, if the base type is a DependencyObject descendant. 
[See the attached sample](https://github.com/microsoft/microsoft-ui-xaml/files/6404059/App1.zip)

**Steps to reproduce the bug**

1. Run the attached sample.
2. Check the following binding error in output: "Error: Converter failed to convert value of type 'App1.Data' to type 'DataBase'; BindingExpression: Path='' DataItem='App1.Data'; target element is 'App1.MyClass1' (Name='c'); target property is 'Data' (type 'DataBase')."

**Expected behavior**
Binding should works correctly without errors.

**Version Info**
[WinUI 3 - Project Reunion 0.5: 0.5.6]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@Scottj1s possible cswinrt issue?
