### ISSUE TITLE
Binding failed on DependencyProperty of nullable types

### ISSUE THREAD

**Issue by AlexanderEgorov** [microsoft/microsoft-ui-xaml#4937]
**Describe the bug**
[See the attached sample.](https://github.com/microsoft/microsoft-ui-xaml/files/6404486/App1.zip)
The following property cannot be bound with a two-way binding.
```cs
        public bool? IsChecked { get { return (bool?)GetValue(IsCheckedProperty); } set { SetValue(IsCheckedProperty, value); } }
        public static readonly DependencyProperty IsCheckedProperty =
            DependencyProperty.Register("IsChecked", typeof(bool?), typeof(MyControl), 
                new PropertyMetadata(null, (d, e) => ((MyControl)d).OnIsCheckedChanged()));
        void OnIsCheckedChanged() {
        }
```

**Steps to reproduce the bug**
1. Run the attached sample
2. Click on a button
3. Check an error in output: "Error: Converter failed to convert value of type 'Windows.Foundation.IReference`1<Boolean>' to type 'IReference`1<Boolean>'; BindingExpression: Path='IsChecked' DataItem='App1.MyControl'; target element is 'Microsoft.UI.Xaml.Controls.Primitives.ToggleButton' (Name='null'); target property is 'IsChecked' (type 'Boolean')."

**Expected behavior**
The binding should work without errors.

**Version Info**
[WinUI 3 - Project Reunion 0.5: 0.5.6]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@teaP and @MikeHillberg (or maybe @jevansaks) do you recall the issues/work around here? similar to the issues with NumberBox's value property.

**Comment by teaP** [comment]
> @teaP and @MikeHillberg (or maybe @jevansaks) do you recall the issues/work around here? similar to the issues with NumberBox's value property.

This isn't the same -- NumberBox.Value isn't nullable, it uses NaN as the unset value (which definitely caused OTHER binding issues because NaN != NaN).

**Comment by MikeHillberg** [comment]
But IIRC we wanted to use nullable for NumberBox, but couldn't because of this problem. I think there's an open Issue on this, that nullable isn't generally supported in binding and/or some markup scenarios, except for built-in WUX types.

We've worked around it for double types using NaN, int types using -1 or one of the infinities. I'm not sure how to work around it for a bool unfortunately; it doesn't have any magic values.

**Comment by AndrewFromJapan** [comment]
Is there any progress or workaround on this?

**Comment by weitzhandler** [comment]
Requiring the use of a converter when the clear intention of the property is to use a boolean makes no sense!
