### ISSUE TITLE
Question: Muxc WinUI 2.5 is missing ListView Control?

### ISSUE THREAD

**Issue by AtosNicoS** [microsoft/microsoft-ui-xaml#4939]
I got two questions:

1. Is the themeresource `ListViewItemForegroundSelectedPointerOver` available in any official release? It seems to be the case in [this commit](https://github.com/microsoft/microsoft-ui-xaml/blob/9052972906c8a0a1b6cb5d5c61b27d6d27cd7f11/dev/CommonStyles/ListViewItem_themeresources.xaml) but not in the [2.5 release](https://github.com/microsoft/microsoft-ui-xaml/blob/v2.5.0/dev/CommonStyles/ListViewItem_themeresources.xaml). Is there any way to style this property right now?

2. I have integrated winui 2.5 [like this](https://docs.microsoft.com/de-de/windows/apps/winui/winui2/getting-started). However using `muxc:ListView` as control does not work, even though I've added `xmlns:muxc="using:Microsoft.UI.Xaml.Controls"` to the top. Please dont get me wrong, I am perfectly using `muxc:NavigationView` for example, but the ListView seems missing!? How can such a crucial component be completely missing?

Cheers!
Nico

**Comment by chingucoding** [comment]
ListVIew is not a control supplied by WinUI 2, it is a OS XAML Control and as such, you won't be able to find it in the Microsoft.UI.Xaml.Controls namespace.

The resource should be available in pre-releases, note though that the latest WinUI 2.5 was released at the end of last year while the resource was added 4 months ago, after the WinUI 2.5 release. That is why it is not available in WinUI 2.5 but in WinUI 2.6 pre-releases.

**Comment by StephenLPeters** [comment]
Thanks @chingucoding ! This is correct.

**Comment by StephenLPeters** [comment]
If you have more questions, feel free to post here.

**Comment by AtosNicoS** [comment]
Alright, so the solution is to use `xmlns:wuxc="using:Windows.UI.Xaml.Controls"` instead. I think it would make sense to add this to the getting started docs, do you aggree?
