### ISSUE TITLE
Proposal: [Build Infrastructure] MUX should be usable from non-UAP applications

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/microsoft-ui-xaml#494]
# Proposal: Microsoft.UI.Xaml should be usable from applications that are not `TargetPlatformIdentifier` == `UAP`

This will aid in support for Xaml Islands consumption of MUX.

## Summary
Right now, the nuget package's winmd, pri and dll are only included if the package is being referenced from a project those `TargetPlatformIdentifier` is `UAP`, as enforced [here](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/build/NuSpecs/MUXControls-Nuget-Native.targets#L8).

## Rationale
As Xaml Islands matures, especially in the upcoming 2019 update to Windows, developers may be interested in deploying MUX side-by-side or in a centennialized fashion along with their applications.

**Comment by jevansaks** [comment]
There are a number of things to make this work in the build pipeline. @rbrid is investigating all the different parts. I think this is already on his radar, so assigning to him.
