### ISSUE TITLE
Discussion: Make the WinUI installation easy

### ISSUE THREAD

**Issue by PieroCastillo** [microsoft/microsoft-ui-xaml#4945]
# Discussion: Make the WinUI installation easy.

I want to give to WinUI a try, but the current problem it's the installation is so difficult, in the [Getting started page](https://docs.microsoft.com/en-us/windows/apps/project-reunion/get-started-with-project-reunion#set-up-your-development-environment) says I should install various SDks, also install an VS extension, set up 2 workloads (.net development and uwp workload), so my question is, In the future is possible just installing dotnet sdk and download some nuget packages to use WinUI?
I think a model to follow is Avalonia, just with dotnet sdk and some nuget packages it's ready to use.

**Comment by Spyromaniac31** [comment]
I don't think there's a need for this. The SDKs and workloads are just general necessities for Windows 10 development, not just WinUI 3 specifically.

**Comment by StephenLPeters** [comment]
I think it is possible that we could make accuiring the VSIX a little easier or rather more automatic, however installing SDK's and choosing if you want to make a desktop or UWP program are going to be required steps for windows development.

**Comment by marb2000** [comment]
Thanks for the feedback @PieroCastillo. 

I believe there is still room for improvement here. For example, if we **make Project Reunion part of the Workloads of Visual Studio**, you only will need to select the right Workload, and everything should be installed for you. If you don't want to use the Visual Studio workloads, you always have the manual process, like the one described in the guidelines. 

Being part of these Workloads is something that we are aiming for, but we don't know when this will happen yet, but it tredining for post v1 (Fall 2021)

**Comment by PieroCastillo** [comment]
@marb2000 thanks!, I hope this for WinUI
