### ISSUE TITLE
Question: Do I have wrong references? WinUI 3 C#, Ambigous Reference to normal Types (Grid)

### ISSUE THREAD

**Issue by jamescarter-le** [microsoft/microsoft-ui-xaml#4956]
I am trying to create a WinUI 3.0 (Win32) in C#, .NET5 to get away from UWP as fast as possible.

I've set up a standard app but when trying to write my XAML VS2019 complains about Ambigous References to simple types such as Window, Grid etc.

When I click Go to definition on these objects it suggests both:
System.Windows.Controls (Wrong)
Microsoft.UI.Xaml.Controls (Correct)

![image](https://user-images.githubusercontent.com/1643692/117164460-8b73a180-adbc-11eb-9fa2-5be68f27c750.png)
![image](https://user-images.githubusercontent.com/1643692/117164475-8f072880-adbc-11eb-8686-0b36101a0506.png)

Also, when bringing over UWP code, everywhere I try and add using statements automatically it wants to add ABI.Microsoft.UI.Xaml.Controls, what is behind this?

![image](https://user-images.githubusercontent.com/1643692/117164751-d42b5a80-adbc-11eb-8aa5-25ef33144f9e.png)

**Comment by jamescarter-le** [comment]
![image](https://user-images.githubusercontent.com/1643692/117165494-73505200-adbd-11eb-9fde-c3a904961070.png)

**Comment by huoyaoyuan** [comment]
It should be ReactiveUI bringing WPF reference?
