### ISSUE TITLE
The x:Bind with Converter raise exceptions

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#4967]
**Describe the bug**
Hi, the following simple code causes different exceptions. In this case, it was a `System.Runtime.InteropServices.COMException: 'Unspecified error'` but in our project, I've caught the NullRef `this.localResources.ContainsKey(key)` - the localResources is null.

**Steps to reproduce the bug**
UserControl3.xaml
```xaml
<UserControl
    x:Class="TestApp.UserControl3"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
    <Grid>
        <Grid.Resources>
            <local:MyConverter x:Key="MyConverter"/>
        </Grid.Resources>
        <StackPanel>
            <TextBlock Text="{x:Bind MyProperty, Converter={StaticResource MyConverter}}"/>
        </StackPanel>
    </Grid>
</UserControl>
```
UserControl3.cs
```xaml
public sealed partial class UserControl3 : UserControl {
        public UserControl3() {
            this.InitializeComponent();
        }
        public string MyProperty { get; } = "Test";
    }
```
MainWindow.xaml
```xaml
<Window
    x:Class="TestApp.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
    <Grid RowDefinitions="Auto, *" x:Name="root">
        <StackPanel Spacing="12"
                    Grid.Row="1">
            <local:UserControl3/>
        </StackPanel>
    </Grid>
</Window>
```
MainWindow.cs
```csharp
    public class MyConverter : IValueConverter {
        public object Convert(object value, Type targetType, object parameter, string language) => value;
        public object ConvertBack(object value, Type targetType, object parameter, string language) => value;
    }
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();   
        }
}
```
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47348109/117278744-b2d47800-ae69-11eb-879a-4f7ad501d495.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.5: 0.5.6] If you're seeing your issue in older previews, please try this release.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@alexdi220 Can you try adding a second element to the resource dictionary?  Single element resource dictionaries have some optimizations in them, there might be a bug in that optimization code.

**Comment by alexdi220** [comment]
@StephenLPeters As a temporary solution, I've stopped using converters and convert properties in a code

**Comment by StephenLPeters** [comment]
Did my suggestion work?

**Comment by alexdi220** [comment]
I didn't check it. The code which raises an exception has been removed.

**Comment by StephenLPeters** [comment]
@bartekk8 I think this is the resource dictionary with a single element optimization.

**Comment by chrisglein** [comment]
Sounds like this person's issue has been resolved one way or the other. Not sure if there was an issue with the single element collections, but this issue is a bit stale at this point so let's wait until we see a fresh issue. @bartekk8 FYI in case there's already an issue that tracked that and it's resolved (if so add link).
