### ISSUE TITLE
Remaining tabs are not resized when closing tabs with keyboard

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#4971]
**Describe the bug**

(Moved from https://github.com/microsoft/terminal/issues/9822)

**Steps to reproduce the bug**
1. Open a bunch of tabs, 
2. Close all but a few with the keyboard.

(You can close tabs in the XCG with <kbd>ctrl+f4</kbd>

**Expected behavior**
> I expect tabs to be restored to their original size when the space allows for it.

**Actual Behavior**
> Tabs remain compacted indefinitely. The only way to get the tabs back to their expected size seems to be to grab the mouse and hover over the tab bar and then move the mouse off the tab bar again.

**Version Info**
> Windows Terminal version 1.8.1032.0

NuGet package version:  [Microsoft.UI.Xaml.2.5.0-prerelease.201202003]

**Comment by chingucoding** [comment]
I think the issue is in the folllowing line: https://github.com/microsoft/microsoft-ui-xaml/blob/867b250d714d08fd8f1f133b67a70c3c9934f805/dev/TabView/TabView.cpp#L798

If you remove the false from that line, it should update correctly. @zadjii-msft Would you maybe like to create a PR for this?

**Comment by zadjii-msft** [comment]
Unfortunately I don't think I've got enough disk space left to make a fresh clone of the WinUI repo and get it built 🙃 That looks right to me, from my totally 0 experience with the WinUI codebase. Presumably, that path isn't hit when closing via the close tab button, right? I'd want to make sure we don't accidentally regress #2569

**Comment by chingucoding** [comment]
Fair enough, I would create a PR then if you don't mind :)
Good that you mentioned #2569, I think the function I mentioned will only be called when hitting Ctrl+F4, but I will double check that to be sure.

**Comment by DavidZidar** [comment]
Tabs need to be resized in other cases too (not just Ctrl+F4) like when exiting a shell in Windows Terminal.
