### ISSUE TITLE
Add a more helpful error message if resources are not found

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#4972]
**Describe the bug**

If the x:Uid attribute of a XAML object is set to a non existing id, the app crashes with a winrt::hresult_error exception. This is very unhelpful to identify the cause of the crash.

**Steps to reproduce the bug**

1. Create a new winui app
2. Add the x:Uid attribute to a XAML element with a random value

**Expected behavior**

The error message should clearly point out the issue (the name of the wrong resource id)

**Screenshots**

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.5: 0.5.6] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@chrisglein FYI

**Comment by michael-hawker** [comment]
Related to #3971 and #2350?

**Comment by StephenLPeters** [comment]
yup, looks like the same ask.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.3.0` has been released which fixes this issue.
* [Release Notes](https://aka.ms/windowsappsdk/1.3/1.3.0/release-notes)
* [Nuget](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000)
