### ISSUE TITLE
System focus visual opacity not in sync with Visual.Opacity

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/microsoft-ui-xaml#4981]
**Describe the bug**

There appear to be a number of inconsistencies in the way the focus visual opacity changes when either `UIElement.Opacity` or `Visual.Opacity` are changed, that seem to be either a small bug or something that could probably use some clearer documentation on this behavior. There are three related issues here that are probably caused by the same underlying behavior:

1. Tabbing to a `Button` with its `Visual.Opacity` property set to `0` still results in the white focus visual rectangle being visible, despite the `Button` itself being completely invisible. This doesn't happen if `UIElement.Opacity` is set to `0` instead.
2. If you set `UIElement.Opacity` to `0`, then use a Composition animation to animate `Visual.Opacity` back to `1`, and then try to tab to the `Button`, the focus visual will never be visible again, despite the `Button` itself now being visible.
3. If you set `Visual.Opacity` to `0` and then run the same animation, the focus visual will now be visible again, but the issue is that in this case (as mentioned in (1)), tabbing will show the focus visual even when the `Button` is initially not visible.

**Steps to reproduce the bug**

1. Create a new blank UWP app (I'm targeting the defaults of 19041 and 17763)
2. Add a reference to `Microsoft.Toolkit.Uwp.UI.Animations` and `Microsoft.Toolkit.Uwp.UI.Behaviors`
3. Add the following XAML code to `MainPage.xaml`:
```xml
<Page
    x:Class="ButtonFocusVisualRepro.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:interactivity="using:Microsoft.Xaml.Interactivity"
    xmlns:interactions="using:Microsoft.Xaml.Interactions.Core"
    xmlns:ani="using:Microsoft.Toolkit.Uwp.UI.Animations"
    xmlns:behaviors="using:Microsoft.Toolkit.Uwp.UI.Behaviors"
    xmlns:ui="using:Microsoft.Toolkit.Uwp.UI"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Button Content="Click me!" ui:VisualExtensions.Opacity="0" Height="400" Width="560">
            <ani:Explicit.Animations>
                <ani:AnimationSet x:Name="OpacityAnimation">
                    <ani:OpacityAnimation To="1" Duration="0:0:2"/>
                </ani:AnimationSet>
            </ani:Explicit.Animations>
            <interactivity:Interaction.Behaviors>
                <interactions:EventTriggerBehavior EventName="Click">
                    <behaviors:StartAnimationAction Animation="{x:Bind OpacityAnimation}"/>
                </interactions:EventTriggerBehavior>
            </interactivity:Interaction.Behaviors>
        </Button>
    </Grid>
</Page>
```
4. Verify the issues (1), (2) and (3) described above by just setting/replacing `ui:VisualExtensions.Opacity="0"` with `Opacity="0"`, and/or by modifying the target value for the animation as needed, depending on what issues are you trying to repro.

**Expected behavior**

The focus visual should have the same opacity as the underlying `Visual` element for the object.
As in, setting the opacity of an element through either `Opacity` or `Visual.Opacity` should have the same effect on it.

**Screenshots**

![nC4WFQML1x](https://user-images.githubusercontent.com/10199417/117541016-2a450b80-b012-11eb-84d3-90c247f190f1.gif)

**Version Info**

- `Microsoft.Toolkit.Uwp.UI.Animations` 7.0.1
- `Microsoft.Toolkit.Uwp.UI.Animations` 7.0.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@kmelmon and @jeffstall for the xaml property versus visual property differences.  @codendone and @JJBrychell for the focus visual perspective.  I'd guess that the focus visual only checks the xaml property and that changing the underlying visual's property is not well supported by xaml.

**Comment by Sergio0694** [comment]
Bumping this (see https://github.com/microsoft/microsoft-ui-xaml/discussions/8638).
