### ISSUE TITLE
Discussion: Add animated icon for carets

### ISSUE THREAD

**Issue by beervoley** [microsoft/microsoft-ui-xaml#4982]
In this [PR](https://github.com/microsoft/microsoft-ui-xaml/pull/4949) we introduced scaling for button that use carets. The buttons will scale on Press. 

Idea: instead of manually scaling the icon and adding a lot of code to do it, may be we can instead utilize animated icon to do that?

@ranjeshj @StephenLPeters @marksfoster @stmoy

**Comment by StephenLPeters** [comment]
Using animated icon has costs. They are less customizable by the developer than storyboards and binary size wise they are quite large.  Runtime perf wise they are likely the same. In general I think animated icon should be reserved for cases were storyboards are very difficult (checkbox checkmark for example). Its possible that an animated icon would have avoived the pixel snapping issue that was hit with the scaling animation on the caret, but its possible it would hit the same or other rendering issues.
