### ISSUE TITLE
Segoe UI Variant too blurry for small text

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#4986]
The new Segoe UI Variant font looks blurry in small font sizes. I have also noticed this with the new News & interests tray icon which also seems to use the new font.

**Comment by mdtauk** [comment]
> The new Segoe UI Variant font looks blurry in small font sizes. I have also noticed this with the new News & interests tray icon which also seems to use the new font.

I am not sure why the News and Interests text is blurry, but its not the fault of the font.

![image](https://user-images.githubusercontent.com/7389110/117673813-07962c80-b1a3-11eb-94ae-813246fe9ed9.png)

**Comment by mdtauk** [comment]
@Jaiganeshkumaran unless you have more evidence of blurry text than the News & Interests taskbar (which is blurry for me too) then the title should probably be specific to that...
"News and Interests taskbar text is blurry"
![image](https://user-images.githubusercontent.com/7389110/117809073-995e7200-b255-11eb-8cc0-a358a3eabad4.png)

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by xadxura** [comment]
@Jaiganeshkumaran, blury text was a known issue in the first version of the font. The current version of the font that is in the selfhost build should have addressed the issue. Can you provide the version number of the font you are using?
CMD: c:\windows\fonts\SegUIVar.ttf

**Comment by mdtauk** [comment]
> @Jaiganeshkumaran, blury text was a known issue in the first version of the font. The current version of the font that is in the selfhost build should have addressed the issue. Can you provide the version number of the font you are using?
> CMD: c:\windows\fonts\SegUIVar.ttf

I am using v1.03

**Comment by xadxura** [comment]
Thanks, @mdtauk, the version 1.03 of the font has been hinted. In the image, it is only the text in the News & Interests taskbar that is blurry, so I think the font is not the root issue. Are there other possible causes here? What rendering framework is being used for that text?

**Comment by mdtauk** [comment]
> Thanks, @mdtauk, the version 1.03 of the font has been hinted. In the image, it is only the text in the News & Interests taskbar that is blurry, so I think the font is not the root issue. Are there other possible causes here? What rendering framework is being used for that text?

I suspect it may be web based, as is the content in the flyout News and Interests uses.  It could be displaying a "generated" png also, like with the Live Tiles.  I also don't think it uses Segoe UI Variable - or if it does, its not using the Small variation as you would expect.

**Comment by xadxura** [comment]
Thanks, @mdtauk, sounds like the font is not the culprit. Web views will need to update CSS to get the new font. When doing so, the way the font weight is called needs to be changed, for example, to use bold:
  @font-face {
    font-family: 'SegoeUIVariable';
    src: url('SegUIVar103.ttf') format('TrueType');
  }

  .font {
    font-family: "SegoeUIVariable";
    font-variation-settings: "wght" 700;
  }


Where 700 = bold, 600 = semibold, 400 = regular, 350 = semilight, and 300 = light.

**Comment by mdtauk** [comment]
I'll just assume DesignTokens will handle the new type scale for FluentUI's CSS and future XAML 😉
