### ISSUE TITLE
Question: dcomp.h animations interoperability

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#4998]
I have a scenario where I'm casting `Compositor` to `IDCompositionDevice2` in order to be able to create a `RectangleClip` as in standard UWP this isn't exposed yet for some reason.
Now, everything works pretty fine and cool and I can apply the clip to my UWP visual, and even run animations on it using `IDCompositionAnimation`, the problem now is:
This animation is part of a quite complex storyboard and I would need it to use the same easing as the rest, but I can't really figure out how to do.
Am I actually supposed to use `IDCompositionAnimation.AddCubic`? In that case, I can't figure out how to use it to get a cubic bezier easing.
Tried to search a bit around the web but the original DirectComposition API seems to be rarely used in Win32... 😢

**Comment by FrayxRulez** [comment]
So, my guess is that you're actually interoperating with `IUIAnimationTransitionLibrary2` to create `Microsoft.UI.Composition` animations?

**Comment by StephenLPeters** [comment]
@JeffStall FYI

**Comment by jeffstall** [comment]
Using legacy DComp interfaces on Windows.UI.Composition objects is not supported.

**Comment by FrayxRulez** [comment]
Yes, I imagined that this was not officially supported, but I was still curious to know... But I think I figured out myself :)

**Comment by Extrimis** [comment]
> Yes, I imagined that this was not officially supported, but I was still curious to know... But I think I figured out myself :)

@FrayxRulez how did you make IDComposition to Support with WindowsUI.Composition, do you have any sample code that you can share
