### ISSUE TITLE
Behaviors are detached from controls inside TabView after being attached when returning back to cached page.

### ISSUE THREAD

**Issue by Dieveral** [microsoft/microsoft-ui-xaml#4999]
**Describe the bug**
I have a TabView on one page with NavigationCacheMode="Enabled", and several tabs inside it. Each tab has several controls with behaviors attached to them. Then I navigate to another page. Behaviors are detached from controls in open tab. When I return back to page with TabView, behaviors are attached to controls in open tab and then immediately detached from them. So as a result I have controls without behaviors attached to them. If I click on other tab and on that tab again, behaviors attach to controls and all works as expected.

**Steps to reproduce the bug**

1. Create application with two pages. One page with a TabView that has several tabs. Add some controls to each tab. Attach behaviors to controls. Place button for navigating to another page. Set page's NavigationCacheMode to "Enabled". Place button on another page for returning back to the first page. 
2. Run application.
3. Test if behaviors are working.
4. Navigate to another page.
5. Return back to the first page.
6. Behaviors are not working on open tab until you click on other tab.

Here is a link to repository with demo project:
[https://github.com/Dieveral/TabViewBehaviorBug](https://github.com/Dieveral/TabViewBehaviorBug)
Behavior makes TextBlock bold and changes its color to blue when pointer enters TextBlock. After navigating to another page and returning back this behavior stops working.

**Expected behavior**

Behaviors are attached to controls on open tab when returning back to cached page.

**Screenshots**

![TabViewBehaviorBug](https://user-images.githubusercontent.com/50696412/117942800-1ea85c00-b314-11eb-9ce7-aa78a920050c.gif)

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.5.0]
[Microsoft.Xaml.Behaviors.Uwp.Managed 2.0.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|         Yes        |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |         Yes        |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |         Yes        |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@michael-hawker is Mircosoft.Xaml.Interactivity from the toolkit. If so, any idea what is happening here?

**Comment by michael-hawker** [comment]
@StephenLPeters nope, behaviors are a [separate project](https://github.com/Microsoft/XamlBehaviors), FYI @DVaughan.

@azchohfi has just been helping them update to WinUI 3 as a dependency of ours.

The collection which does the attach/detach code is [done here](https://github.com/microsoft/XamlBehaviors/blob/master/src/BehaviorsSDKManaged/Microsoft.Xaml.Interactivity/Interaction.cs).

Could this be an issue with how TabView/XAML is firing unloaded/loaded events? i.e. it's getting loaded before it's being unloaded in the switch or loaded isn't firing again from the cached version but unloaded still is on the navigate away?

----

We have some behaviors we build on top of the behaviors library in the Toolkit, we even have a [base class we use](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/main/Microsoft.Toolkit.Uwp.UI.Behaviors/BehaviorBase.cs), though we want to try and get rid of it and just use the base behavior type. I did notice we subscribe to `SizeChanged` as well, so I wonder if the toolkit ones would still be working in this scenario or also broken?

**Comment by StephenLPeters** [comment]
@beervoley thoughts on the loaded\unloaded event handlers in tabview?
