### ISSUE TITLE
Question: Does WinUI supports offscreen rendering to a DirectX texture? 

### ISSUE THREAD

**Issue by eladmaimoni** [microsoft/microsoft-ui-xaml#5001]
I wrote a [detailed question](https://stackoverflow.com/questions/67485243/can-winui-3-be-used-for-offscreen-rendering-of-a-xaml-tree) on stackoverflow.

I was wondering if WinUI supports real time offscreen rendering in such a way that will allow the user to embed xaml based UI into an existing 3D Engine. The documentation / roadmap on this matter are not super clear to me.

Certain Xaml based technologies (such as NoesisGUI) already support this feature. It is extremely useful for game engines and other graphics oriented applications.

So is this supported? Can it be supported?

Thanks!

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by GeorgeS2019** [comment]
@elad8a 

All 3D WinUI has not been positively considered but the most optimistic path is for community to make this 3D framework to support Win UI control

**Comment by elad8a** [comment]
@GeorgeS2019 I don't see the connection between these issues. I'm talking about integrating 2D WinUI controls into an **existing** rendering code that works directly with DirectX APIs.

 I'm not suggesting to add 3D support WinUI.
