### ISSUE TITLE
SelectionIndicator not showing in NavigationView at first load

### ISSUE THREAD

**Issue by pellea** [microsoft/microsoft-ui-xaml#5007]
**Describe the bug**

The SelectionIndicator is never displayed when the NavigationView loads for the first time and the MenuItem are loaded dynamically (using ViewModel) after the load of the Page (meaning in the Loaded event).

The ViewModel is assigned to the DataContext also in the `Loaded` event.

![winui-navview](https://user-images.githubusercontent.com/395982/118085238-5d94eb00-b3c2-11eb-854f-9ec00528cc90.gif)

**Steps to reproduce the bug**

View (xaml):
```
    <ui:View.Resources>
        <DataTemplate x:Key="MenuItemTemplate" x:DataType="models:MenuItem">
            <muxc:NavigationViewItem
                Content="{x:Bind Name}"
                IsSelected="{x:Bind IsSelected, Mode=OneWay}"
            >
                <muxc:NavigationViewItem.Icon>
                    <muxc:SymbolIcon Symbol="{x:Bind Icon}" />
                </muxc:NavigationViewItem.Icon>
            </muxc:NavigationViewItem>
        </DataTemplate>
    </ui:View.Resources>

...

<muxc:NavigationView
        x:Name="nav"
        IsSettingsVisible="False"
        IsBackButtonVisible="Collapsed"
        IsBackEnabled="False"
        MenuItemsSource="{x:Bind ViewModel.MenuItems, Mode=OneWay}"
        MenuItemTemplate="{StaticResource MenuItemTemplate}"
        SelectedItem="{x:Bind ViewModel.NavigatedItem, Mode=TwoWay}"
        AlwaysShowHeader="False"
        PaneDisplayMode="Top"
        ExpandedModeThresholdWidth="500"
    >
...
</muxc:NavigationView>
```

ViewModel:
```
public class ShellViewModel : ViewModelBase
    {
        private readonly NavigationService _navigationService;
        private bool _isInitialized;

        #region Property : MenuItems

        private ObservableCollection<MenuItem> _menuItems;

        public ObservableCollection<MenuItem> MenuItems
        {
            get => _menuItems;
            set => SetProperty(ref _menuItems, value);
        }

        #endregion

        #region Property : NavigatedItem

        private object? _navigatedItem;

        public object? NavigatedItem
        {
            get => _navigatedItem;
            set => SetProperty(ref _navigatedItem, value);
        }

        #endregion

        public ShellViewModel(NavigationService navigationService)
        {
            this._navigationService = navigationService;
        }

        public override Task Initialize()
        {
            if (this._isInitialized == false)
            {
                this._isInitialized = true;
                this.LoadMenuItems();
            }

            return Task.CompletedTask;
        }

        private void LoadMenuItems()
        {
            this.MenuItems = new()
            {
                new MenuItem("Search", Symbol.Find, nameof(SearchView), true),
                new MenuItem("Calendar", Symbol.Calendar, nameof(AgendaView))
            };

            this.NavigatedItem = this.MenuItems[0];
        }

        private Task OnNavigateToMenuItem(NavigationViewSelectionChangedEventArgs item)
        {
            if (item.IsSettingsSelected)
            {
                this._navigationService.NavigateTo<SettingsView>();
            }
            else
            {
                if (item.SelectedItem is MenuItem menuItem)
                {
                    switch (menuItem.ViewType)
                    {
                        case nameof(SearchView):
                            this._navigationService.NavigateTo<SearchView>();
                            break;
                        case nameof(AgendaView):
                            this._navigationService.NavigateTo<AgendaView>();
                            break;
                    }
                }
            }

            return Task.CompletedTask;
        }
    }
```

MenuItem:
```

public class MenuItem : ObservableObject
    {
        private string _name;

        public string Name
        {
            get
            {
                return _name;
            }

            set
            {
                SetProperty(ref _name, value);
            }
        }

        private Symbol _icon;

        public Symbol Icon
        {
            get
            {
                return _icon;
            }

            set
            {
                SetProperty(ref _icon, value);
            }
        }

        private string _viewType;

        public string ViewType
        {
            get
            {
                return _viewType;
            }

            set
            {
                SetProperty(ref _viewType, value);
            }
        }

        private bool _isSelected;

        public bool IsSelected
        {
            get
            {
                return _isSelected;
            }

            set
            {
                SetProperty(ref _isSelected, value);
            }
        }

        public MenuItem()
        {
        }

        public MenuItem(string name, Symbol icon, string viewType, bool isSelected = false)
        {
            this.Name = name;
            this.Icon = icon;
            this.ViewType = viewType;
            this.IsSelected = isSelected;
        }
    }
```

If I set or not the `NavigatedItem` the behavior is the same.
If I set or not the `IsSelected` property of the MenuItem, the behavior is also the same.

**Expected behavior**
The selection indicator correctly aligned with the selected menu item.

![image](https://user-images.githubusercontent.com/395982/118090308-b74ce380-b3c9-11eb-903b-a7bf0673bd2b.png)

**Version Info**

Version: 
TargetFramework: net5.0-windows10.0.19041.0
TargetPlatformMinVersion: 10.0.17763.0

FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" 
FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" 

PackageReference Include="Microsoft.ProjectReunion" Version="0.5.6" 
PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.6" 
PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.6" 
PackageReference Include="CommunityToolkit.WinUI" Version="7.0.1" 
PackageReference Include="CommunityToolkit.WinUI.UI" Version="7.0.1" 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes|

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (it's been a while)              | Yes|
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@ranjeshj and @karenbtlai FYI

**Comment by zadjii-msft** [comment]
This looks a little like #2845

**Comment by pellea** [comment]
I have updated the first post, I have copy/paste xml tags in Version Info and it didn't show correctly.

My project targets Project Reunion 0.5.6 with WinUI 3.
The NavigationView is not hierarchical in my sample.

**Comment by pellea** [comment]
I have update my project to Project Reunion 0.8 with .NET 6 preview 4 and I have the same behavior as expected

**Comment by pellea** [comment]
My project is now using the .NET 6 and WinAppSDK 1.0.
The same issue persists, and this bug is still not triaged since May.

@StephenLPeters @zadjii-msft @pratikone @mrlacey
