### ISSUE TITLE
[Critical] GetXamlTypeByName(string typeName) fails for typename Windows.UI.Xaml.Controls.RevealBackgroundBrush

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#5011]
**Describe the bug**
![image](https://user-images.githubusercontent.com/42038175/118139081-98863580-b439-11eb-93b2-4754b778a074.png)

TypeName: "Windows.UI.Xaml.Controls.RevealBackgroundBrush"

Demo project is in here:
[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6473105/App1.zip)

**Steps to reproduce the bug**

1. Install Microsoft.UI.Xaml 2.5.0
2. Override OnWindowCreated(WindowCreatedEventArgs args) in App.cs
3. Set a break point on it
![image](https://user-images.githubusercontent.com/42038175/118139397-e1d68500-b439-11eb-9e44-cacfdbc83378.png)
4. Set break on FileNotFoundException
![image](https://user-images.githubusercontent.com/42038175/118139504-016dad80-b43a-11eb-9143-643bc676e683.png)
5. Make sure you use any Controls from Microsoft.UI.Xaml
![image](https://user-images.githubusercontent.com/42038175/118140387-e6e80400-b43a-11eb-9cd3-3f47aa2d59d8.png)
6. Run demo app in X64 Debug mode
7. Wait until VS hit the break point on "OnWindowCreated"
![image](https://user-images.githubusercontent.com/42038175/118139733-3ed23b00-b43a-11eb-80bb-3bcec9a74dff.png)
8. Wait for a few seconds
9. Press F5 to continue
10. Got the exception.

```
 	System.Private.CoreLib.dll!System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(System.Reflection.AssemblyName assemblyName)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(System.IntPtr gchManagedAssemblyLoadContext, System.Reflection.AssemblyName assemblyName)	Unknown
 	[Native to managed conversion]	
 	[Managed to native  conversion]	
 	System.Private.CoreLib.dll!System.RuntimeTypeHandle.GetTypeByName(string name, bool throwOnError, bool ignoreCase, bool reflectionOnly, ref System.Threading.StackCrawlMark stackMark, System.IntPtr pPrivHostBinder, bool loadTypeFromPartialName)	Unknown
 	System.Private.CoreLib.dll!System.RuntimeType.GetType(string typeName, bool throwOnError, bool ignoreCase, bool reflectionOnly, ref System.Threading.StackCrawlMark stackMark)	Unknown
 	System.Private.CoreLib.dll!System.Type.GetType(string typeName)	Unknown
 	Microsoft.UI.Xaml.Markup.winmd!Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider.GetNonGenericType(string compilerTypeName = "Windows.UI.Xaml.Controls.RevealBackgroundBrush")	Unknown
 	Microsoft.UI.Xaml.Markup.winmd!Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider.CreateXamlType(string typeName)	Unknown
 	Microsoft.UI.Xaml.Markup.winmd!Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider.getXamlType(string typeName)	Unknown
>	App1.exe!App1.App1_XamlTypeInfo.XamlTypeInfoProvider.GetXamlTypeByName(string typeName = "Windows.UI.Xaml.Controls.RevealBackgroundBrush") Line 136	C#
 	App1.exe!App1.App1_XamlTypeInfo.XamlMetaDataProvider.GetXamlType(string fullName = "Windows.UI.Xaml.Controls.RevealBackgroundBrush") Line 100	C#
 	App1.exe!App1.App.GetXamlType(string fullName = "Windows.UI.Xaml.Controls.RevealBackgroundBrush") Line 49	C#

```
**Expected behavior**

Should not throw any exception. It might throw a lot of FileNotFoundException which cause my app stop responding for about 20 seconds on startup

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.5.0]
[Microsoft.UI.Xaml 2.6.0-latestprelease]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
If we don't set any break point on OnWindowCreated or any other function,  or do not use any Controls from Microsoft.UI.Xaml. This issue will not be triggered.

**Comment by zhuxb711** [comment]
Why is there such a problem? Is there a temporary solution or workaround?

**Comment by zhuxb711** [comment]
@chingucoding @ranjeshj Could help take a look? Thanks.

**Comment by chingucoding** [comment]
Can't repro this, even after trying multiple times.

**Comment by StephenLPeters** [comment]
Very strange, does this only repro on debug builds?  Are you able to f5 though the execption and continue running the app?

**Comment by zhuxb711** [comment]
@chingucoding FYR

https://user-images.githubusercontent.com/42038175/118343130-a92dcd00-b559-11eb-833d-6a572e4f362a.mp4

**Comment by zhuxb711** [comment]
I think it might the same issue as https://github.com/microsoft/microsoft-ui-xaml/issues/2042
This issue does not occur in Visual Studio 16.9.4.
This issue does occur in Visual Studio 16.9.5.

@chingucoding Could you confirm this issue in 16.9.5 ?

**Comment by chingucoding** [comment]
Can't repro this with VS 16.9.5 either.

**Comment by zhuxb711** [comment]
I could not repro this in another computer. Might be related to environment
