### ISSUE TITLE
Is it possible to use Rounded Window?

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#5014]
I used `ControlsResourcesVersion="Version2"` and Most controls use rounded corners, Is it possible for Window to use rounded corners as well? Or in Windows 10 Sun Valley version, Are all windows automatically displayed as rounded?

**Comment by jordan-msftfan** [comment]
A long time ago, top level rounded Window were mentioned as To-do items under Roadmap, but it has since disappeared, possibly requiring system-level changes.
