### ISSUE TITLE
WinUI 2.6 - please don't round navigation view pane

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#5015]
In WinUI 2.6, I noticed that the navigation view pane itself is rounded. Please don't do this as it's usually used as a top level control and having rounded edges leaves some empty spaces that aren't symmetrical and doesn't fit well into the design. The items inside should be rounded but don't round the pane itself. If you do round the pane, have some margin for it by default.

**Comment by StephenLPeters** [comment]
@chigy FYI

**Comment by chigy** [comment]
@gabbybilka FYI

**Comment by mdtauk** [comment]
> In WinUI 2.6, I noticed that the navigation view pane itself is rounded. Please don't do this as it's usually used as a top level control and having rounded edges leaves some empty spaces that aren't symmetrical and doesn't fit well into the design. The items inside should be rounded but don't round the pane itself. If you do round the pane, have some margin for it by default.

Isn't this only for the Overlay mode?
![image](https://user-images.githubusercontent.com/7389110/118340285-28e47900-b513-11eb-93b7-ae3cecaaa63e.png)

**Comment by Jaiganeshkumaran** [comment]
It seems to be rounded in left expanded mode as well for me

**Comment by omikhailov** [comment]
Yep, I noticed this too. In May preview version of WinUI 2.6 with V2 styles, menu corners are round. Another doubtful change is that new styles add padding and you have to set negative margin when it's required to stretch some page.

![panel](https://user-images.githubusercontent.com/75426711/118479183-6286d100-b719-11eb-9a6c-c89673d1bfcc.jpg)

**Comment by duke7553** [comment]
We've noticed this CornerRadius bug with the pre-release NavigationView Pane styles in Files too. 

Also, @omikhailov. If I understand your issue correctly, you should be able to simply set this resource to remove the added padding around NavigationView rather than use a negative margin. It worked for us

`<Thickness x:Key="NavigationViewContentPresenterMargin">0,0,0,0</Thickness>
`

**Comment by Jaiganeshkumaran** [comment]
Why hasn't this been fixed yet as WinUI 2.6 has been released? Also in the XAML Controls Gallery app, I see the pane extends to the rest of the title bar with the same background but I don't know how to do the same. I tried to add a grid there with the same background as the pane however I notice some space between the pane and my grid and I couldn't get it properly rounded.

**Comment by mdtauk** [comment]
The rounded corners should only affect the right side (left side when using Right to Left locale) with the other end set to be flush.

The windows themselves in Windows 11 take care of the rounding for you for the window edges.

**Comment by Jaiganeshkumaran** [comment]
It shouldn't be rounded on any side except when extended to the rest of the title bar because it doesn't necessarily need to be top-level. If you want to be rounded for a non-top level navigation view, can round the entire control instead of rounding the pane.

**Comment by Jaiganeshkumaran** [comment]
![image](https://user-images.githubusercontent.com/45227503/123644993-8aeb0a80-d843-11eb-9bb8-c92f96371d3b.png)
This shouldn't be needed. Window will be automatically rounded on Windows Sun Valley and won't be on Windows 10 so it shouldn't be done. Also, it's not always rounded like in maximized or full screen mode.

**Comment by ranjeshj** [comment]
> The rounded corners should only affect the right side (left side when using Right to Left locale) with the other end set to be flush.
> 
> The windows themselves in Windows 11 take care of the rounding for you for the window edges.

I think this makes sense. In Windows 11, the rounding of the window will take care of it and windows 10 it will not have the clipping issue. 

I think NavigationView being the root of the page is the most common scenario. For other cases, this can be customized using the theme resource.

**Comment by gabrielconl** [comment]
Wouldn't it be more consistent to have all corners be square? I can't find anything else in Windows 11 or WinUI 2.6 with rounded corners touching an edge.

**Comment by gabrielconl** [comment]
All of the new UI is designed with this simple rule: if a corner touches an edge it will be squared, otherwise it will be rounded.
![a](https://user-images.githubusercontent.com/84711285/131464652-d9094eb7-c9bc-42f2-ae9a-03e4502bfbcb.png)
![b](https://user-images.githubusercontent.com/84711285/131464660-0cc9bf16-a1b1-4a1f-835c-355df963180f.png)
![c](https://user-images.githubusercontent.com/84711285/131464662-30e56f9c-dbc8-4b59-babf-50df177faaed.png)

**Comment by StephenLPeters** [comment]
I think that the idea is that the pane isn't touching that edge, its floating over it, hence the shadow.

**Comment by AlgoRythm-Dylan** [comment]
For anyone looking for a quick fix to get rid of the corner radius, this line in my App.xaml (Application.Resources > ResourceDictionary section) worked. It might be a bit of a drastic solution, as it will affect the entire application, but it suits my needs very nicely.

```xaml
<CornerRadius x:Key="NavigationViewContentGridCornerRadius">0</CornerRadius>
```
