### ISSUE TITLE
In WinUI 2.6, all menu flyout have rounded corners, but TextBox's context menu is not

### ISSUE THREAD

**Issue by roxk** [microsoft/microsoft-ui-xaml#5019]
**Describe the bug**
Inbox `TextBox`'s context menu doesn't get the rounded corner treatment.

**Steps to reproduce the bug**
1. Create a blank app. Install WinUI `2.6.0-prerelease.210430001` from nuget.
2. Overwrite the stack panel with the following:
```
<StackPanel>
    <TextBox PlaceholderText="Input"/>
    <muxc:MenuBar>
        <muxc:MenuBarItem Title="File">
            <MenuFlyoutItem Text="Open"/>
        </muxc:MenuBarItem>
    </muxc:MenuBar>
</StackPanel>
```
3. Build and see TextBox's context menu is not rounded, but menu bar's menu is rounded.

**Expected behavior**
TextBox's context menu has rounded corner, consistent with all other menu.

**Actual behavior**
TextBox's context menu is not rounded.

**Screenshots**
#### TextBox
![image](https://user-images.githubusercontent.com/16918354/118355975-9b9e3480-b5a5-11eb-869f-7f6cfe9f1d7a.png)

#### CommandBarFlyout
![image](https://user-images.githubusercontent.com/16918354/118355931-609c0100-b5a5-11eb-88ec-1deaf73dcb4d.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 2.6.0-prerelease.210430001] 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |     |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Note**
Just to make sure I didn't miss anything, I tried to reproduce this on the current XAML Control Gallery App on the store and the result is the same. And it seems there is no `muxc:TextBox` available.

**Comment by StephenLPeters** [comment]
@chigy FYI

**Comment by chigy** [comment]
@SavoySchuler FYI

**Comment by gabrielconl** [comment]
![image](https://user-images.githubusercontent.com/84711285/124357975-cf511e80-dc26-11eb-9591-a7b4264242bd.png)

Buttons don't get styled properly in the MUXControlsTestApp.
