### ISSUE TITLE
Why InfoBar is missing in WinUi 3?

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#5020]
I noticed that InfoBar control is not available in winui 3. What is the reason for this? i tested in reunion 0.5

**Comment by huoyaoyuan** [comment]
I got the control in 0.5.0 GA, in desktop version. It was missing in previous versions. What version are you using?

**Comment by ghost1372** [comment]
This is the version I use
```
<PackageReference Include="Microsoft.ProjectReunion" Version="0.5.6" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.6" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.6" />
```

**Comment by ghost1372** [comment]
i Updated to 0.5.7 and infobar exist😁
