### ISSUE TITLE
SwapChainPanel has a thin hole on the sides

### ISSUE THREAD

**Issue by Const-me** [microsoft/microsoft-ui-xaml#5021]
**Describe the bug**

SwapChainPanel has a thin hole on the sides. The hole pierces through the complete WinUI rendering layer, the color visible underneath comes from `GCLP_HBRBACKGROUND` window class style.

**Steps to reproduce the bug**

Create a desktop WinUI3 app that uses SwapChainPanel to render something. The SwapChainPanel needs a working `IDXGISwapChain` to trigger the bug. It doesn't matter what you render in the swap chain.

**Expected Behavior**

SwapChainPanel should blend the content on top of WinUI’s visual elements behind the panel. If should never blend the content on Win32 background of the window.

**Screenshots**

For better visibility of the bug, I've called `CreateSolidBrush` of color `0xFF00FF`, and called `SetClassLongPtr( hwnd, GCLP_HBRBACKGROUND, hbrush );`

![swap-panel-bug](https://user-images.githubusercontent.com/925112/118371299-474a8300-b5ac-11eb-8a0a-c0dd93ab4390.png)

If you wonder why the top area of the background is different — because the main window sets `ExtendsContentIntoTitleBar = true;` that area comes from the title bar behind WinUI visuals.

**Version Info**

Windows 10 20H2 19042.985, WinUI 3 packages version 0.5.7

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by codendone** [comment]
This should be fixed in version 0.8. Please reactivate if you still repro  on 0.8.x.
