### ISSUE TITLE
NavigationView - IsBackButtonVisible should be called BackButtonVisibility

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#5027]
I would assume IsBackButtonVisible means it's a boolean value however it looks like an enumeration similar to Visibility just with another member - Auto added. I think BackButtonVisibility would be a more suitable name than IsBackButtonVisible which is misleading.

**Comment by sylveon** [comment]
To note that this is at least source breaking and could even be an ABI breaking change

**Comment by Jaiganeshkumaran** [comment]
> To note that this is at least source breaking and could even be an ABI breaking change

Well, they can retain the old one but prefer using the new one similar to how DisplayMode exists in NavigationView but you use PaneDisplayMode instead. Also, it isn't an ABI breaking changed because it will be under a new interface as always.

**Comment by chingucoding** [comment]
Duplicate of #4102.

**Comment by Jaiganeshkumaran** [comment]
@chingucoding Thanks for telling, I didn't notice that issue.
