### ISSUE TITLE
WinUI 2.6 - Acrylic fallback should be darker

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5028]
In WinUI 2.6, the acrylic fallback is very close to ApplicationPageBackgroundThemeBrush, making it harder to distinguish areas with acrylic when it's not active with the other sections. Please make it darker to be easily distinguishable from the default page background.

**Comment by StephenLPeters** [comment]
@chigy FYI

**Comment by mdtauk** [comment]
Not sure if it should be darker, but there is something odd happening in the MUXTestApp.

The TestUI pages have the NavigationView which should be displaying the default values, but appear not to be.
![image](https://user-images.githubusercontent.com/7389110/118570850-e4f0ae80-b774-11eb-95dc-77301c35c2d2.png)

The Sidebar is showing the same colour as the page background, yet the values are different in code.

```xaml
<Color x:Key="SolidBackgroundFillColorBase">#F3F3F3</Color>
```

```xaml
<StaticResource x:Key="NavigationViewDefaultPaneBackground" ResourceKey="AcrylicInAppFillColorDefaultBrush" />

<local:AcrylicBrush x:Key="AcrylicInAppFillColorDefaultBrush"
                    TintColor="#FCFCFC"
                    TintOpacity="0.0"
                    FallbackColor="#F9F9F9"
                    BackgroundSource="Backdrop"/>
```

**Comment by karenbtlai** [comment]
@mdtauk The background colour for NavigationView pane is actually transparent, and the #F3F3F3 colour you're seeing here is coming from `ApplicationPageBackgroundThemeBrush`. If you take a look at the `PaneOverlayGroup` in VSM, in the `PaneNotOverlaying` state, it's pointing to `NavigationViewExpandedPaneBackground` which is transparent.

It also turns out there's two files, NavigationView_rs1_themeresources.xaml and NavigationView_rs2_themeresources.xaml that's interfering with one another, causing confusion. :/

**Comment by mdtauk** [comment]
> @mdtauk The background colour for NavigationView pane is actually transparent, and the #F3F3F3 colour you're seeing here is coming from `ApplicationPageBackgroundThemeBrush`. If you take a look at the `PaneOverlayGroup` in VSM, in the `PaneNotOverlaying` state, it's pointing to `NavigationViewExpandedPaneBackground` which is transparent.
> 
> It also turns out there's two files, NavigationView_rs1_themeresources.xaml and NavigationView_rs2_themeresources.xaml that's interfering with one another, causing confusion. :/

Is the transparency by design?  If so could that choice be revisited.

**Comment by Jaiganeshkumaran** [comment]
There should be a way to distinguish between the navigation view and the content. The current technique is to use a different background that's noticeable however other techniques like a shadow or a small line could also be used.

**Comment by mdtauk** [comment]
> There should be a way to distinguish between the navigation view and the content. The current technique is to use a different background that's noticeable however other techniques like a shadow or a small line could also be used.

I have often advocated for an Inset Shadow to be used.  The Border currently only shows in High Contrast modes.

I think the colour should be different
