### ISSUE TITLE
Inheriting the implicit style not working fine in WinUI 3 for desktop

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#5031]
I have a custom control CustomControl1

```
public class CustomControl1 : Control
{
    public CustomControl1()
    {
        this.DefaultStyleKey = typeof(CustomControl1);
    }
}
```

Whose implicit style is 

```
    <Style TargetType="local:CustomControl1">
        <Setter Property="Background" Value="Green"/>
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="local:CustomControl1">
                    <Border
                        Background="{TemplateBinding Background}"
                        BorderBrush="{TemplateBinding BorderBrush}"
                        BorderThickness="{TemplateBinding BorderThickness}">
                    </Border>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
```

And a second custom control CustomControl2, inheriting CustomControl1

```
public class CustomControl2 : CustomControl1
{
    public CustomControl2()
    {
        DefaultStyleKey = typeof(CustomControl2);
    }
}
```

whose implicit style only sets the Background

```
    <Style TargetType="local:CustomControl2">
        <Setter Property="Background" Value="Red"/>
    </Style>
```

The problem is the "Template" of CustomControl1 is not inherited automatically. Therefore nothing is rendered.

This looks as a bug as the implicit style of CustomControl2 doesn't override Template, so it should take the parent one.

In case that were intentional, there should be at least a way to base the style on the parent control implicit style, I couldn't find anything, x:Type doesn't exist in WinUI. Is there any way round?

Here the repo project [App12.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6496512/App12.zip)

**Comment by beervoley** [comment]
@arivoir have you tried naming your CustomControl1 Style and then using it as argument for BasedOn parameter?
Likes this:
` <Style TargetType="local:CustomControl1" BasedOn="{StaticResource DefaultCustomControl1Style}" />
<Style x:Key="DefaultCustomControl1Style" TargetType="local:CustomControl1">
   <Setter......
    ....... />
</Style>

`<Style TargetType="local:CustomControl2" BasedOn="{StaticResource DefaultCustomControl1Style}"/>`

**Comment by beervoley** [comment]
@arivoir try like this:
```
  <Style TargetType="local:CustomControl1" BasedOn="{StaticResource DefaultCustomControl1Style}" />
        <Style TargetType="local:CustomControl2" BasedOn="{StaticResource DefaultCustomControl1Style}">
            <Setter Property="Background" Value="Red"/>
        </Style>

        <Style x:Key="DefaultCustomControl1Style" TargetType="local:CustomControl1">
            <Setter Property="Background" Value="Green"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="local:CustomControl1">
                        <Border
                        Background="{TemplateBinding Background}"
                        BorderBrush="{TemplateBinding BorderBrush}"
                        BorderThickness="{TemplateBinding BorderThickness}">
                        </Border>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
```

**Comment by arivoir** [comment]
@beervoley  using a shared name is not an option as the controls are in different assemblies (I put both in the same project to make the repo sample easier)

**Comment by StephenLPeters** [comment]
I think this is by design, when an item is added to the visual tree the system will search for an unnamed style of the same type to apply, it will then merge that unnamed style with the metadata defined default style. In this case the your CustomControl2's meta data defined default style is the style with just the background property set, so there is nothing to merge with.  In this case, I would suggest that you created a named style for CustomControl1 and have both your CustomControl1 and CustomControl2 unnamed styles be based off the named one.

**Comment by arivoir** [comment]
Using a named resource will only work if you are the owner of the control inheriting and if both are in the same resource dictionary. But what about the other cases?

**Comment by roxk** [comment]
@arivoir Given the current constraint, I think you best bet is to wrap the control instead of inheriting it. If you need those properties/methods, then you will need to use the adapter pattern to adapt one by one.

**Comment by arivoir** [comment]
To put this in context, I'm developing a suite of controls, so I'm looking for a maintainable solution, adapting every control or making copies of the template is a real problem and the reason why the platform must solve this.

**Comment by arivoir** [comment]
I see 2 posible solutions

1. Change the platform so the implicit styles are automatically composed by its style and its ancestors implicit styles
2. Provide a way to allow specifying BasedOn="local:CustomControl" this way the inherited control base its implicit type in the implicit type of its ancestor

**Comment by arivoir** [comment]
This is still a big issue. Is there any light in the horizon?

**Comment by legistek** [comment]
It only grew stale because no one from Microsoft ever responded.

**Comment by roxk** [comment]
> Any solution to this problem in recent releases?

If I understand your situation correctly, you have Control1 in assembly A, and Control2 in assembly B. Control2 inherits Control1.

In this case, in your control 2's style
```
<Style TargetType="local:CustomControl2">
        <Setter Property="Background" Value="Red"/>
    </Style>
```
you just need to declare this style is based on control 1:
```<Style TargetType="local:CustomControl2" BasedOn="{StaticResource Control1Style}">
        <Setter Property="Background" Value="Red"/>
    </Style>
```

For your user of control2, it should work, as in, the system should be able to find `Control1Style` for your control2, regardless of whether control1 is in another assembly, as long as:
1. Both assembly A and B is available for your user's app
2. The generic.xaml of assembly A is available for your user's app
3. If `Control1Style` is defined elsewhere, it is included in your user's `Application.xaml`'s resource dictionary at appropriate location (i.e. `XamlControlResources`'s merged dictionary)

**Comment by roxk** [comment]
@legistek Yes. If not it's a bug. The naming convention is `DefaultXXxStyle`. Eg. .button has `DefaultButtonStyle`. You can start searching your control's styles from check https://github.com/microsoft/microsoft-ui-xaml/tree/winui3/release/1.5.3/controls/dev/CommonStyles
