### ISSUE TITLE
In-app Acrylic is not available in WinUI3 for Desktop

### ISSUE THREAD

**Issue by Sanlorng** [microsoft/microsoft-ui-xaml#5034]
**Describe the bug**

I tried to use the in-app Acrylic effect in WinUI3 for Desktop, but the app couldn't start, and the error was as follows
`0x76DBA6E2 (KernelBase.dll)处(位于 TestInAppAcrylic.exe 中)引发的异常: 0x40080202: WinRT transform error (参数: 0x8000000B, 0x80070490, 0x00000008, 0x029DD864)。
0x76DBA6E2 (KernelBase.dll)处(位于 TestInAppAcrylic.exe 中)引发的异常: WinRT originate error - 0x80070490 : 'Windows.Graphics.Display: GetForCurrentView must be called on a thread that is associated with a CoreWindow.'。
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!752F11A5: (caller: 75207BB6) ReturnHr(1) tid(adc) 8007007E 找不到指定的模块。
0x76DBA6E2 处(位于 TestInAppAcrylic.exe 中)引发的异常: Microsoft C++ 异常: winrt::hresult_error，位于内存位置 0x029DE1C0 处。`
It looks as if there is a problem with the GetForCurrentView call

**Steps to reproduce the bug**

1. Create WinUI 3 for Desktop(Blank App) Project from Project Reunion Template
2. Open MainWindow.xaml file
3. Add StackPanel's property: `Background="{ThemeResource SystemControlAcrylicElementBrush}"`
4. Run debug
5. App crashed when started

**Expected behavior**

The app starts normally，and In-app Acrylic works

**Screenshots**

![Snipaste_2021-05-18_12-42-10](https://user-images.githubusercontent.com/26089739/118591549-ebb00d80-b7d6-11eb-9e0a-8b36a7164011.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.7]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|    |  Yes  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Linjie123** [comment]
@Sanlorng I also encountered the same problem, but my project added a simple navigation control on the main page and run project.

**Comment by Sanlorng** [comment]
> @Sanlorng I also encountered the same problem, but my project added a simple navigation control on the main page and run project.
This may be a problem caused by the control calling an API that is not supported in WinUI3 for Desktop

**Comment by Sanlorng** [comment]
> @Sanlorng I also encountered the same problem, but my project added a simple navigation control on the main page and run project.

This may be a problem caused by the control calling an API that is not supported in WinUI3 for Desktop

**Comment by codendone** [comment]
Same underlying issue as #4806. This will be fixed in the next release.

**Comment by Sanlorng** [comment]
this was fixed in the project reunion 0.8.0-preview
