### ISSUE TITLE
Question: Styling ContentDialog Buttons and Title with a custom Style

### ISSUE THREAD

**Issue by AtosNicoS** [microsoft/microsoft-ui-xaml#5035]
I want to change the ContentDialog Style to have:
1. a larger, bold title
2. custom colors for buttons

This is my current solution:
```xaml
 <!--Content Dialog-->
<Style x:Key="ContentDialogDefaultButtonStyle" TargetType="Button">
    <Setter Property="FontWeight" Value="SemiBold"/>
    <Setter Property="CornerRadius" Value="2"/>
</Style>

<Style x:Key="ContentDialogPrimaryButtonStyle" TargetType="Button" BasedOn="{StaticResource ContentDialogDefaultButtonStyle}">
    <Setter Property="Foreground" Value="{StaticResource AtosSynergyPitchBlackColorBrush}"/>
    <Setter Property="Background" Value="{StaticResource AtosSynergyDodgerBlueColorBrush}"/>
</Style>

<Style x:Key="ContentDialogTitleStyle" TargetType="TextBlock">
    <Setter Property="FontWeight" Value="SemiBold"/>
    <Setter Property="FontSize" Value="24"/>
</Style>

<!--ContentDialogStyle-->
<Style x:Key="ContentDialogStyle" TargetType="ContentDialog">
    <Setter Property="Background" Value="{StaticResource AtosSynergyPitchBlackColorBrush}"/>
    <Setter Property="BorderBrush" Value="{StaticResource AtosSynergyPitchBlackColorBrush}"/>
    <!--TODO: Setting the BorderThickness to 0 does not work: https://github.com/microsoft/microsoft-ui-xaml/issues/4815-->
    <Setter Property="BorderThickness" Value="0"/>

    <!--<Setter Property="TitleTemplate">
        <Setter.Value>
            <DataTemplate>
                <TextBlock Text="{TemplateBinding Content}" FontWeight="SemiBold" FontSize="24"/>
            </DataTemplate>
        </Setter.Value>
    </Setter>

    <Setter Property="PrimaryButtonStyle">
        <Setter.Value>
            <Style TargetType="Button">
                <Setter Property="Foreground" Value="{StaticResource AtosSynergyPitchBlackColorBrush}"/>
                <Setter Property="Background" Value="{StaticResource AtosSynergyDodgerBlueColorBrush}"/>
                <Setter Property="FontWeight" Value="SemiBold"/>
                <Setter Property="CornerRadius" Value="2"/>
            </Style>
        </Setter.Value>
    </Setter>-->

    <!--<Setter Target="PrimaryButton" Property="CornerRadius" Value="2"/>-->

    <!--<Setter Target="PrimaryButton.CornerRadius" Value="2"/>-->
</Style>
```

I can use it like this:
```xaml
<ContentDialog
    [...]
    DefaultButton="Primary"
    PrimaryButtonText="Add new item"
    CloseButtonText="Cancel"
    IsPrimaryButtonEnabled="True"
    Title="Dialog Title"
    Style="{ThemeResource ContentDialogStyle}"
    PrimaryButtonStyle="{ThemeResource ContentDialogPrimaryButtonStyle}"
    CloseButtonStyle="{ThemeResource ContentDialogDefaultButtonStyle}">

    <ContentDialog.TitleTemplate>
        <DataTemplate>
            <TextBlock Text="Dialog Title" Style="{ThemeResource ContentDialogTitleStyle}"/>
        </DataTemplate>
    </ContentDialog.TitleTemplate>
    [...]
````

Now there are two issues with this:
1. The primary button style does not get loaded. Only when I click cancel. I guess that is because of this: https://github.com/microsoft/microsoft-ui-xaml/blob/release/2.5/dev/ContentDialog/ContentDialog_themeresources.xaml#L247
2. Why can't I integrate all changes into a single style, like the greyed out code above? If I add this in the live preview it works, If I start the app with the changes they take no effect

Is there a better way to modify the styles? I think my solution would be to create the buttons on my own and add my own enter keydown logic (sadly).

**Comment by ranjeshj** [comment]
Don't think there is an easy workaround for this. We could expose the primary button style as a resource that is based on AccentButtonStyle. If we did that you might be able to just override that style instead of directly trying to set the style on the primary button.

You could also locally override the accentbuttonstyle. But note that the colors depicts that if you hit enter on the dialog which button will be invoked.

**Comment by mdtauk** [comment]
> Don't think there is an easy workaround for this. We could expose the primary button style as a resource that is based on AccentButtonStyle. If we did that you might be able to just override that style instead of directly trying to set the style on the primary button.
> 
> You could also locally override the accentbuttonstyle. But note that the colors depicts that if you hit enter on the dialog which button will be invoked.

It may be overkill, but couldn't you add a Style property for the Primary Button and Secondary Buttons - which would allow you to specify a style, and it gets carried down to the dialog itself.
