### ISSUE TITLE
Border control should not get the keyboard focus

### ISSUE THREAD

**Issue by jeganraj-m** [microsoft/microsoft-ui-xaml#5042]
**Describe the bug**
Border control gets the focus in click, and it should not get the focus.

**Steps to reproduce the bug**
Add Border and TextBox control, select TextBox then Border. You could see focus lost in TextBox.

**Expected behavior**
Border control should not have focus

**Screenshots**

![image](https://user-images.githubusercontent.com/74640452/118764715-9ab41e00-b897-11eb-9953-25bc02f4e6b2.png)

**Code**

```
<Grid x:Name="rootGrid">
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <StackPanel Grid.Row="1"
                Orientation="Horizontal">
        <Border Height="50"
                Width="200"
                Background="Yellow" />
        <TextBox Height="50"
                 Width="200" />
    </StackPanel>
    <TextBlock x:Name="focusElement"
               Grid.Row="3"
               Width="300" />
    <Button Grid.Row="4"
            Click="Button_Click"
            Content="Current focus element"
            AllowFocusOnInteraction="False" />
</Grid>
```

private void Button_Click(object sender, RoutedEventArgs e)
        {
            focusElement.Text = (FocusManager.GetFocusedElement(rootGrid.XamlRoot).ToString());
        }

**Version Info**
Project-Reunion NuGet package version -  0.5.6
OS version - 20H2

NuGet package version: 
WinUI 3 - Project Reunion 0.5: 0.5.6

Microsoft.ProjectReunion  -  Version="0.5.6"
Microsoft.ProjectReunion.Foundation -  Version="0.5.6"
Microsoft.ProjectReunion.WinUI -  Version="0.5.6"

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 20H2 19042.985             |  Yes  |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional Details**
1. While click in border, focused element shows as "ScrollViewer"
2. AllowFocusOnInteraction API doesn't helps.
3. Logged in Project Reunion too: https://github.com/microsoft/ProjectReunion/issues/834

**Comment by StephenLPeters** [comment]
ScrollViewer has behavior where when you click in its bounds it will set focus on its first focusable child.  I suspect that is what is happening here, although looking at your markup it looks like the first focusable child is the TextBox...  @RBrid thoughts?

**Comment by jeganraj-m** [comment]
My problem is different. I have used Border in my custom control style. I'm trying to avoid focus for my control using "AllowFocusOnInteraction". But Border taking the focus and I can't avoid keyboard focus in my control.

**Comment by ssaran046** [comment]
Hi Team,

Any update on this?

**Comment by StephenLPeters** [comment]
It seems like focus is being moved to the root scroll viewer... By default ScrollViewer is not supposed to be a TabStop, so by my recolection this shouldn't be happening.  @RBrid is that correct?

Maybe the bug is that scrollviewers in Winui3 are focusable?
