### ISSUE TITLE
Question: RichTextBlock: SelectionStart/SelectionEnd range does not match SelectedText.

### ISSUE THREAD

**Issue by akpapa** [microsoft/microsoft-ui-xaml#5047]
Hi,
Project Reunion 0.5.7/.Net 5.0 Desktop App/WInUI 3/Windows 10 21382/VS2019 16.10 preview 4
I have a RichTextBlock which has a Paragraph in it:
```
<Paragraph>
<Run>A</Run>
<Run>B</Run>
<Run>C</Run>
<Run>D</Run>
</Paragraph>
```
In the rtb, it shows `ABCD`.
I am using the rtb's `SelectionChanged `event to get user selected Runs.
Most of the time it works well, for example:
If I select `B` and `C,`  `BC` get highlighted, `SelectedText` is `BC,`  and `SelectionStart.Parent` refers to the Run of `B`, and `SelectionEnd.Parent` refers to the Run of `C`. So far so good.

But if I press my mouse left button down on the right half of `A` then drag my mouse to select `B` and `C`, `BC` get selected and highlighted(`A` does not), `SelectedText` is `BC`. 
But this time,  `SelectionStart.Parent` refers to Run of `A` instead of `B`, maybe because the selection starts on the right half of `A`. 

I want to always get the Runs of `B` and `C`, just the same as `SelectedText`.
This can be easily reproduced and would give user an inconsistent experience.

Is this a bug or I have missed something?
Thank you in advance!

**Comment by StephenLPeters** [comment]
@chrisglein FYI. I'm not even sure if this is a bug or not..

**Comment by chrisglein** [comment]
> But this time, `SelectionStart.Parent` refers to Run of `A` instead of `B`, maybe because the selection starts on the right half of `A`.

Yeah, that definitely seems unexpected. If `SelectedText` doesn't contain `A` then I wouldn't expect `SelectionStart` to include `A`.

**Comment by akpapa** [comment]
Thank you guys for confirming this issue.
It seems that  these `TextPointer`s get first selected and last deselected comparing to `SelectedText`, so the range they wrap up is always equal or wider than `SelectedText`. 
So currently I can use `pointerRangeText.Equals(SelectedText)`, `StartsWith(SelectedText)`, `EndsWith(SelectedText)` to determine if I need correct the pointer. It works pretty good.
It'd be easier if this issue got addressed in the future.
Have a good day!
