### ISSUE TITLE
ItemsRepeater - UniformGridLayout does not display items initially at small window sizes

### ISSUE THREAD

**Issue by jsedlak** [microsoft/microsoft-ui-xaml#5052]
**Describe the bug**
When loading an ItemsRepeater bound to an array of UI elements and using a UniformGridLayout, items do not appear until a certain window width & height have been reached. Using the default layout (stacking) correctly displays the items, even at small window sizes (eg 200x200).

**Steps to reproduce the bug**
Example Project: https://github.com/jsedlak/UniformGridProblem
1. Add a ItemsRepeater that uses a UniformGrid
2. Bind ItemsRepeater to a list of User Controls
3. Add code to force a small window size on load

**Expected behavior**
User Controls should be visible on load.

**Screenshots**
In a real application: Pit Wall - small window size
No UI elements visible
![image](https://user-images.githubusercontent.com/549309/118983342-52096d00-b94a-11eb-861e-f5c86a48efd7.png)

Window size has to be around here for them to show up
![image](https://user-images.githubusercontent.com/549309/118983399-63527980-b94a-11eb-8522-883859656815.png)

Provided sample app - small size
![image](https://user-images.githubusercontent.com/549309/118983521-8846ec80-b94a-11eb-9044-813e9ea218c7.png)

Provided sample app - size required for items to show
![image](https://user-images.githubusercontent.com/549309/118983579-9432ae80-b94a-11eb-8309-178b7fa9d04e.png)

**Version Info**

- WinUI 3
- Project Reunion 0.5.7
- Windows 10.0.19042
- VS 2019 Preview 4.0 v16.10.0

**NuGet package version:** 
Microsoft.ProjectReunion 0.5.7
Microsoft.ProjectReunion.Foundation 0.5.7
Microsoft.ProjectReunion.WinUI 0.5.7
PInvoke.User32 0.7.104 (to resize the window)

**Windows app type:**
Blank App, Packaged (WinUI 3 in Desktop)
Project Reunion

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

@chingucoding have you seen this before?
