### ISSUE TITLE
Support Visual Basic .NET for WinUI 3

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5053]
It seems like WinUI 3 doesn't seem to support Visual Basic. Why? Although Microsoft isn't adding any new features doesn't mean it's dead so please add support for it. Also, what does this mean for existing UWP apps written using Visual Basic? Will they be able to use WinUI 3?

**Comment by StephenLPeters** [comment]
@MikeHillberg @ryandemopoulos FYI
