### ISSUE TITLE
Crash on startup of WinUI3 C# Project - Basic App Instructions - COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

### ISSUE THREAD

**Issue by ivberg** [microsoft/microsoft-ui-xaml#5054]
**Describe the bug**
I followed basic WinUI3 instructions with all the latest & greatest stable tooling (to my knowledge)
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/desktop-build-basic-winui3-app

However, the app crashes on startup - Crash on startup of WinUI3 C# Project - Basic App Instructions - COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

Also the app F5/Debug didn't immediately work. I had to build the project.

Please clarify this. I don't understand the two repos. The other repo bug report has similar instructions pointing to this repo to file bugs on WinUI3. So not sure which one to use

**Steps to reproduce the bug**

1. https://docs.microsoft.com/en-us/windows/apps/winui/winui3/desktop-build-basic-winui3-app
2. Verify all steps followed
3. Hand-added SDK refs per https://docs.microsoft.com/en-us/windows/apps/project-reunion/#net-sdk-references
4. Build/Run/Crash

**Expected behavior**
Example template app doesn't crash

**Screenshots**
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at AppUI.Program.Main(String[] args) in C:\src\App\AppUI\AppUI\obj\x86\Debug\net5.0-windows10.0.19041.0\App.g.i.cs:line 26

  This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int)
    WinRT.BaseActivationFactory.BaseActivationFactory(string, string)
    Microsoft.UI.Xaml.Application._IApplicationStatics._IApplicationStatics()

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

**Version Info**

Project Reunion 0.5
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.5.7" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.7" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.7" />

      <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" />
      <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" />

>dotnet --list-sdks
5.0.203 [C:\Program Files\dotnet\sdk]

Latest production VS (which is listed as supported): 16.9.6

NuGet package version: 

[WinUI 3 - Project Reunion 0.5: 0.5.7] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
No  | Yes

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
|  Insider Build (21387)           | Yes - 21387.co_release_fun.210518-1507
| October 2020 Update (19042)       
| May 2020 Update (19041)            |
| November 2019 Update (18363)    
| May 2019 Update (18362)          
| October 2018 Update (17763) 
| April 2018 Update (17134)      
| Fall Creators Update (16299)     
| Creators Update (15063)         

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop         |  Yes
| Xbox             
| Surface Hub       
| IoT             

**Additional context**
Filed same bug on ReUnion repo has not sure where this bug belongs - https://github.com/microsoft/ProjectReunion/issues/848

**Comment by StephenLPeters** [comment]
Is there a chance you've tried to F5 the unpackaged application?  If so, changing the startup application to the packaged app should resolve that issue.

**Comment by ivberg** [comment]
I guess what happened is either I switched away the default project, or I added this to an existing solution with a default project (which I did) and it didn't set the package as the default.  I found it counterintuitive because normally you F5/Debug the project and then deploy later. Apparently this is not yet supported.

**Comment by jaymarvin98** [comment]
Hello,
I'm experiencing the same on any/all tries to use any samples or templates for WinUI3.  Sure, the Package can be run, but the goal is to also be able to run the desktop app outside of the sandbox in full permission mode. As I understand it, that is a key goal of Win UI 3.  Isn't that the point of the Solution structure...to have both options available for running the app?  Seems like it is almost there; is there a setting/package I'm missing to make running the desktop project possible?
Thank you, and very much looking forward to it, Jay Marvin

**Comment by StephenLPeters** [comment]
I beleive the team still plans to support this, according to the roadmap: https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md
