### ISSUE TITLE
Question: Mix WPF & WinUI3 XAML 

### ISSUE THREAD

**Issue by sherman89** [microsoft/microsoft-ui-xaml#5057]
Is it possible or ever going to be possible, to mix WinUI 3 XAML controls with WPF XAML controls on a Win32 desktop application?

We have a dependency on a third party library which only supports WinForms/WPF, does that prevent us from using WinUI3?

I tried with another WPF control but got System.Xaml error. 

Thank you very much for your hard work!

**Comment by StephenLPeters** [comment]
Yup, using Xaml Islands you can put Winui2 controls inside of a WPF application.  I know that Winui3 plans to support xaml islands, however I'm not sure if that feature has been released yet.  @marb2000

**Comment by marb2000** [comment]
Hi! As per the current engineering plan, XAML Islands is part of the v1 Release. We didn't sign off the plan yet, so it's not committed. We are still working on the plan.

**Comment by sylveon** [comment]
> Just some heads-up: WinUI 3's XAML Islands will work only with .NET 5 apps, .NET Core 3 and .NET Framework are not supported.

Just to clarify, is that line only about using XAML Islands on .NET? WinUI 3's islands should still work in C++, right?

**Comment by sherman89** [comment]
> Yup, using Xaml Islands you can put Winui2 controls inside of a WPF application. I know that Winui3 plans to support xaml islands, however I'm not sure if that feature has been released yet. @marb2000

What if I wanted to create a WinUI application, but use a WPF control (so the other way around), that's not possible, right?

It would be nice if I didn't have to choose WPF just because of this one dependency.



> Hi! As per the current engineering plan, XAML Islands is part of the v1 Release. We didn't sign off the plan yet, so it's not committed. We are still working on the plan.
> 
> Just some heads-up: **WinUI 3's XAML Islands will work only with .NET 5 apps, .NET Core 3 and .NET Framework are not supported.**

Thanks! If I can't host WPF in WinUI then XAML islands from WPF would be the next best thing, though I might just prefer to go for pure WPF with custom styles if the code gets too ugly.

Our WPF dependency will be ported to atleast .NET Core 3.1, but i don't know if they'll ever make a UWP/WinRT version of their WPF control. 

Appreciate your answers 🙂

**Comment by marb2000** [comment]
@sylveon Yes, XAML Islands will work in C++, additionally to .NET 5 apps.

@sherman89 Unfortunately, a WinUI 3 can host neither WPF nor WinForms controls.

**Comment by sherman89** [comment]
Thanks @marb2000 

I guess we will have to stick to WPF then for now, and maybe using XAML islands when it's possible although so far it seems quite involved
