### ISSUE TITLE
Question: Date and Time Picker Entry Control - This the final design?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#5066]
![image](https://user-images.githubusercontent.com/7389110/119072868-2935b600-b9e4-11eb-8b13-65e02a3b846f.png)

![image](https://user-images.githubusercontent.com/7389110/119072675-ce03c380-b9e3-11eb-9c83-d4c56b505847.png)

When you compare the Date and Time picker entry form controls, to the drop down, the background colour does not match.  

**So do these need updating, or is it intentional?**

**Comment by StephenLPeters** [comment]
@chigy FYI.

**Comment by gabrielconl** [comment]
Would it be a good idea to have a mega thread for minor issues and feedback for the new design, now that it's close to being finished?
