### ISSUE TITLE
Keyboard accelerators part of an UserControl get fired even after the parent gets unloaded

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#5067]
**Describe the bug**

Today keyboard accelerators that are part of an UserControl get fired even after the UserControl itself gets unloaded as long as its reference count doesn't reach 0.

**Steps to reproduce the bug**
Steps to reproduce the behaviour:
1. Create a user control and have a keyboard accelerator in it
2. Add some code in the invoked handler for that keyboard accelerator and put a breakpoint
3. Load that user control in a content presenter and duplicate the reference to keep the user control alive after the content in the content presenter has changed.
4. Change the content in the content presenter
5. Notice that the breakpoint for the keyboard accelerator inside the user control which is no longer displayed get hit when you press that shortcut.

**Expected behavior**

Keyboard accelerators shouldn't fire once the parent is unloaded unless it's loaded again even if the instance is still alive.

**Version Info**

NuGet package version: 

WinUI 2.5

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043) | Yes |
| October 2020 Update (19042)        | Yes |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        | Yes |
| IoT                |  |

**Comment by riverar** [comment]
@Jaiganeshkumaran Can you attach a sample project?

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI
