### ISSUE TITLE
NavigationView: navigaitonviewitem with children items causes layout cycle.

### ISSUE THREAD

**Issue by beervoley** [microsoft/microsoft-ui-xaml#5071]
**Describe the bug**

Adding more than **2** subitems to NavigationViewItems that's in NavigationView that doesn't have **fixed** size (without height=#ofpixels) - causes the app to crash with layout cycle.
**Steps to reproduce the bug**

1. Create a Grid with simple NavigationView inside
2. Click on DropDown button of the first item.
3. Observe the crash.
Code to repro:
```
<Grid HorizontalAlignment="Stretch" VerticalAlignment="Top">
  <muxc:NavigationView IsPaneToggleButtonVisible="False" IsPaneOpen="True" PaneDisplayMode="Left" 
            IsSettingsVisible="False" IsBackButtonVisible="Collapsed">
            <muxc:NavigationView.MenuItems>
                <muxc:NavigationViewItem Content="Quick Access" Icon="Favorite">
                    <muxc:NavigationViewItem.MenuItems>
                        <muxc:NavigationViewItem Content="Desktop" Icon="NewWindow"/>
                        <muxc:NavigationViewItem Content="Content"/>
                        <muxc:NavigationViewItem Content="Content"/>
                        <muxc:NavigationViewItem Content="Content"/>
                        <muxc:NavigationViewItem Content="Content"/>
                    </muxc:NavigationViewItem.MenuItems>
                </muxc:NavigationViewItem>
            </muxc:NavigationView.MenuItems>
        </muxc:NavigationView>
</Grid>
```
**Expected behavior**

Application should work properly without crashing.

**Version Info**

NuGet package version: 

2.6.0-prerelease.210430001

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes|

**Comment by beervoley** [comment]
@ranjeshj @karenbtlai FYI

**Comment by rcohn** [comment]
I have been experiencing much the same problem in a WinUI3 app I'm building (using the C# API).

Essentially, I discovered that I get consistent crashes under these conditions:

- When I build a LeftPane NavigationView with submenu items, and
- Those items contain an Image (there is also text), and
- This property is specified for NavigationView: IsSettingsVisable=false
- The user clicks on a toplevel icon to expand the submenu list

It took me nearly an entire day to narrow this down.  Now I find that to avoid the crash I have to keep the Settings icon there and somehow find a way to hide it.

![image](https://user-images.githubusercontent.com/2237248/154379416-00a6fabe-2e9a-44b4-a06f-8fee296b2f55.png)


I would very much request that Microsoft look into this problem as soon as possible.  If you wish I can supply a simple demo that exhibits the problem. The screenshot shows the relevant xaml code (couldn't paste the code in cleanly).

Using Windows App SDK 1.0 on Win10 21H2

Thank you.
