### ISSUE TITLE
[NavigationView] Settings label not vertically aligned with settings icon

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#5076]
Currently, the settings element text and icon are not vertically aligned, instead the text sits a bit lower:
![Screenshot of unaligned settings text and icon](https://user-images.githubusercontent.com/16122379/119241962-7e93d380-bb5a-11eb-9c1c-f2b72f465698.png)

However it would probably be better if they are vertically aligned with each other:
![Mockup of aligned settings text and icon](https://user-images.githubusercontent.com/16122379/119241958-78055c00-bb5a-11eb-962c-a38a67c3ac6d.png)

@mdtauk FYI

**Comment by mdtauk** [comment]
How does it look when using the new Segoe UI Variable font?

What about with other typefaces should it get swapped out with Roboto, Google Sans Text, SF, or any of the localisation fonts?

Is there a typographic alignment setting that would align it as the font changes?

Also how does it look when using the new Fluent UI System Icons' Settings icon?

**Comment by ranjeshj** [comment]
@karenbtlai as FYI.
