### ISSUE TITLE
WinUI for Desktop print

### ISSUE THREAD

**Issue by Fernand-Delavy** [microsoft/microsoft-ui-xaml#5080]
VS 16,9.6
Did somebody find how to print with WinUI for Desktop ?
Problem :  PrintManager crash

Id did try with VS 16.10.0 Preview 4.0 and Maui sdk, same problem PrintManager crash

I did try work around with Win32 PrintDlg, but it have no print function.

**Comment by ranjeshj** [comment]
@Fernand-Delavy Marking this as dup of this issue. Please join the conversation there.
https://github.com/microsoft/microsoft-ui-xaml/issues/4419
