### ISSUE TITLE
Pill-shaped bars look pointy with large display scaling

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#5081]
![Untitled](https://user-images.githubusercontent.com/84711285/119361565-7a7bc900-bcb4-11eb-9ff5-ce20564ebb79.png)

You can see that the scrollbar looks sharp instead of having a rounded end. It also happens a bit with the NavigationView selector, but it's harder to see.

**Comment by beervoley** [comment]
@gabrielconl what is the display scale set at here?

**Comment by gabrielconl** [comment]
It's set to 300%, but you can see it a bit even with lower scaling levels.

**Comment by beervoley** [comment]
@ranjeshj should we ask George to have a look?:)
