### ISSUE TITLE
Gamepad is not working in Webview2 in UWP

### ISSUE THREAD

**Issue by pschaub** [microsoft/microsoft-ui-xaml#5083]
**Description**
I've created a simple UWP application with WinUI 3 (preview) according to the [official documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui).
The webview is loading the URL https://gamepad-tester.com/

I connected a Gamepad (Xbox One Controller) to my computer.
The gamepad works fine in Google Chrome and Microsoft Edge (Chromium).

But the gamepad is not working in **Webview2**.

**Version**
Microsoft.ProjectReunion: 0.5.0-prerelease
Webview2 Runtime: 90.0.818.66
OS: Win10, 21H1 (10.0.19043.985)

**Repro Steps**
Create a simple WinUI3 UWP application and add a webview targeting the URL https://gamepad-tester.com/

--- 
See also: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1318

**Comment by bpulliam** [comment]
UWP is no longer supported by WinUI 3.  If you can repro the issue on current builds without UWP, please reactivate or open a new issue.

Thanks!
