### ISSUE TITLE
A targeted TeachingTip does not get unloaded when its target does

### ISSUE THREAD

**Issue by SavoySchuler** [microsoft/microsoft-ui-xaml#509]
**Describe the bug**

A targeted TeachingTip does not get unloaded when its target gets unloaded. 

**Steps to reproduce the bug**

1. Add a targeted teaching tip to a page-specific instance of a UI element. 
2. Navigate to that page and prompt the tip to open. 
3. Navigate away from that page. 

**Expected behavior**

I expect the teaching tip to get unloaded when its target gets unloaded. 

**Actual behavior**

The target gets unloaded but the teaching tip remains on-screen. 

**Screenshots**

![image xaml controls gallery with a targeted teaching tip on screen that points to nothing](https://user-images.githubusercontent.com/16964652/55268935-cb661300-524b-11e9-8b51-d00ea8d906b2.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190319001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18865)                   | Yes |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |   |
| Xbox                      |   |
| Surface Hub          |    |
| IoT                         |    |

**Additional context**

**Comment by jevansaks** [comment]
Agreed that when the TeachingTip itself gets unloaded we should hide the popup. I'm not sure about watching the target.

**Comment by chingucoding** [comment]
I will fix this :)
