### ISSUE TITLE
Announcing WinUI 3 - Project Reunion 0.8 Preview! 🎉

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#5102]
We've just shipped WinUI 3 - Project Reunion 0.8 Preview! This release is a new, preview version of WinUI 3 that includes lots of new bug fixes, stability improvements, and experimental features that may not be currently available in the latest stable version of WinUI 3. This version of WinUI 3 ships inside of the Project Reunion 0.8 Preview package. 

## Shipping WinUI 3 with Project Reunion

In order to use this preview version of WinUI 3, you'll download the [Project Reunion (Preview) Visual Studio Extension](https://aka.ms/projectreunion/previewdownload) (VSIX) to get started. The Project Reunion (Preview) VSIX includes WinUI Project Templates that you'll use to build your WinUI 3 app, as well as access to other Project Reunion components, such as [DWriteCore](https://docs.microsoft.com/windows/apps/project-reunion/dwritecore) and [MRTCore](https://docs.microsoft.com/windows/apps/project-reunion/mrtcore/mrtcore-overview). The Project Reunion package includes a reference to the WinUI 3 NuGet package. 

For more on Project Reunion, see their [documentation](https://docs.microsoft.com/windows/apps/project-reunion/) and [repository](https://github.com/microsoft/ProjectReunion). For installation instructions, see  [Set up your development environment](https://docs.microsoft.com/windows/apps/project-reunion/set-up-your-development-environment). 

## What's new in WinUI 3 - Project Reunion 0.8 Preview

- The Pivot control has been added back in and can now be used in any WinUI 3 app.
- Most bug fixes from Project Reunion v0.5.5, v0.5.6, and v0.5.7 are included with this release.
- New bug fixes, including:
    - Mouse right-click in TextBox crashes the application
    - NavigationView causes crash in UWP, Reunion 0.5 Preview
    - ProgressBar doesn't show difference between Paused and Error option

    To see the full list of bugs fixed, head over to our [release notes](https://docs.microsoft.com/windows/apps/winui/winui3/release-notes/release-notes-08-preview). 

Please keep in mind that WinUI 3 - Project Reunion 0.8 Preview is still a pre-release product, and has a number of [known issues and limitations](https://docs.microsoft.com/windows/apps/winui/winui3/release-notes/release-notes-08-preview#limitations-and-known-issues) that our team continues to work on. This preview is not intended for production apps.

## Getting started with WinUI 3 - Project Reunion 0.8 Preview
First, you'll need to set up your dev environment with the appropriate technologies. See our documentation for installation instructions and more information on project types: 

**[Install Project Reunion 0.8 Preview](https://docs.microsoft.com/windows/apps/project-reunion/set-up-your-development-environment)**

**[Create WinUI 3 Projects](https://docs.microsoft.com/windows/apps/winui/winui3/create-winui3-projects)**

While you're developing, check out the [API Reference documentation for WinUI 3 - Project Reunion 0.8 Preview](https://docs.microsoft.com/windows/winui/api/).

Take a look at our walk-through docs:

- [Get started with WinUI 3 for desktop apps](https://docs.microsoft.com/windows/apps/winui/winui3/get-started-winui3-for-desktop)
- [Build a basic WinUI 3 app for desktop](https://docs.microsoft.com/windows/apps/winui/winui3/desktop-build-basic-winui3-app)
- [Get started with WinUI 3 for UWP apps (Preview)](https://docs.microsoft.com/windows/apps/winui/winui3/get-started-winui3-for-uwp)

You can also update your existing WinUI 3 app to use the new Project Reunion 0.8 Preview using these instructions: [Update existing projects to the latest release of Project Reunion](https://docs.microsoft.com/windows/apps/project-reunion/update-existing-projects-to-the-latest-release).

We love feedback! We encourage you to file any bug, big or small, on our repo using [this template](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=). Knowing which issues and features are important and/or critical to our customers highly influences which ones we tackle. Even though we now ship with Project Reunion, please continue to file WinUI-specific bugs on this repo.  

## Using WinUI 3 - Project Reunion 0.8 Preview with our ecosystem partners

WinUI 3 - Project Reunion 0.8 Preview is in the process of being integrated into several other important ecosystem technologies. To test out and follow that progress, check out some of our partner technologies below:

- [Actipro Software](https://www.actiprosoftware.com) is migrating their vast UI control offerings over to WinUI 3, including their SyntaxEditor code editor, propertygrid, native type edit boxes, docking/MDI, charts, and more.

- [DevExpress](https://www.devexpress.com/winui/): DevExpress has released 20 new WinUI controls with Project Reunion 0.5 support, including the Data Grid, Scheduler, Charts, Ribbon Toolbar, and more. All 20 UI components are available free-of-charge.

- [GrapeCity](https://www.grapecity.com/) plans to bring their popular desktop UI controls to WinUI later this year! Learn more about their [data connection service components](https://www.grapecity.com/componentone/net-service-component?utm_source=Microsoft%20TAP&utm_medium=Dynamic&utm_campaign=project-reunion-0-5-preview-announcement) for WinUI.

- [Infragistics](https://www.infragistics.com/products/winui): Ultimate UI for WinUI brings business critical, high performing, and feature rich line of business controls to your apps that target any platform that runs Windows (including Windows on ARM64).

- [Syncfusion](https://www.syncfusion.com/winui-controls): Updated their projects to Microsoft.ProjectReunion from Microsoft.WinUI following upgrade instructions. All their controls are working fine.

- [Telerik UI for WinUI](https://www.telerik.com/winui): the market first UI controls suite for crafting Win32 and UWP apps with WinUI 3, comes with feature-rich controls like Ribbon, DataGrid, Charts, Gauges, Barcode, and more.

- [Uno Platform](https://github.com/unoplatform): Use WinUI 3 – Reunion 0.8 Preview, XAML and C# to build pixel-perfect, single-codebase, native applications that can run on Web, Desktop and Mobile. It is free, open-source and available today.

- [Windows Community Toolkit (Microsoft)](https://aka.ms/wct-winui3): The WCT is currently working on supporting Reunion 0.8 Preview. It provides tons of new controls and capabilities for use in your WinUI app. You can check out their open source repo [here](https://aka.ms/windowstoolkit).

## What's next
To keep up with progress being made on WinUI 3, please see our [feature roadmap](https://aka.ms/winui3/feature-roadmap) which gets updated regularly. We also give monthly updates on our WinUI Community Calls, where you can directly ask the team any questions you have.

**Comment by shelllet** [comment]
great!

**Comment by huoyaoyuan** [comment]
There are severe issues in building and tenplating (#5112 #5113). Please ensure you are aware of this.
