### ISSUE TITLE
Possible to use `IInitializeWithWindow` (or alternative) to load UI from .NET `.dll` into `HINSTANCE`/`HWND` of window provided by parent `.exe`?

### ISSUE THREAD

**Issue by GavinRay97** [microsoft/microsoft-ui-xaml#5106]
Heya, this might sound a bit convoluted but I'd really like to use .NET to write the UI for a plugin, that will be loaded as a `.dll` from a closed-source parent `.exe`.

The host application loads the plugin DLL and calls a named entrypoint function, it passes an `hinstance`/`hwnd` to a window it's allocated for the plugin to use as an arg.

I was thinking of adding an `[UnmanagedCallersOnly]` attribute to a function in .NET, and using Dotnet Native Exports (https://github.com/AaronRobinsonMSFT/DNNE) and compiling as a shared library + using the assembly directly:

```csharp
    [UnmanagedCallersOnlyAttribute(EntryPoint = "InitDll")]
    public static int InitDll(IntPtr hwnd)
    {
        // initialize the WinUI application here, use the hwnd that was passed with IInitializeWithWindow
    }
```

The other alternative that I was thinking might be possible was using the `nethost` and `hostfxr` libraries to write a small C++ app to work as a middleman to load + initialize the CLR and the WinUI assembly, and then act as the entrypoint used to start the app:

```
Parent .exe --> Loads MyAppWrapper.dll --> uses nethost.dll and hostfxr.dll to load MyAppAssembly.dll
            --> initializes the CLR and calls the entrypoint method of the .NET app in C/C++ exported function
            --> Entrypoint of .NET app takes an "IntPtr HWND" and uses this to set the render handle target
```

```cpp
#define DLL_EXPORT __declspec(dllexport)

extern "C"
{
  // Entrypoint function called by host .exe when .dll is loaded
  DLL_EXPORT int InitDll(HWND hwnd) {
    load_hostfxr();

    // Initialize and start the .NET Core runtime
    const string_t config_path = root_path + STR("MyAppAssembly.runtimeconfig.json");
    load_assembly_and_get_function_pointer_fn load_assembly_and_get_function_pointer = nullptr;
    load_assembly_and_get_function_pointer = get_dotnet_load_assembly(config_path.c_str());

    // Load app assembly, that has an "UnmanagedCallersOnly" exported entrypoint function taking "IntPtr hwnd"
    const string_t dotnetlib_path = root_path + STR("MyAppAssembly.dll");
    const char_t *dotnet_type = STR("MyAppAssembly.Lib, MyAppAssembly");

    struct dotnet_managed_entrypoint_args { HWND hwnd };

    typedef void (CORECLR_DELEGATE_CALLTYPE *custom_entry_point_fn)(dotnet_managed_entrypoint_args args);
    custom_entry_point_fn custom = nullptr;

    rc = load_assembly_and_get_function_pointer(
        dotnetlib_path.c_str(),
        dotnet_type,
        STR("CustomEntryPointUnmanaged") /*method_name*/,
        UNMANAGEDCALLERSONLY_METHOD,
        nullptr,
        (void**)&winui_app_entrypoint_fn);

    // Call .NET entrypoint, give it the HWND handle
    dotnet_managed_entrypoint_args args{ .hwnd = hwnd };
    winui_app_entrypoint_fn(args);

    return EXIT_SUCCESS;
  }
}
```

Would be grateful for any wisdom on this, I don't know very much about .NET
Thank you! 😃

**Comment by StephenLPeters** [comment]
I don't think this issue is related to Winui. I think it will be better serviced in something like https://github.com/dotnet/runtime

**Comment by GavinRay97** [comment]
I am empathetic to the issue closure, to try to clean up your issues.

But I had been in conversation with several folks from various teams on the .NET and WinUI platforms, and even apologetically sent a tweet to Miguel Ramos about this after some weeks of dead-ends as a last resort:

https://twitter.com/marbtweeting/status/1399876590725570560

![image](https://user-images.githubusercontent.com/26604994/121555405-fb3f0280-c9e0-11eb-9a43-085efe21ace5.png)

I mean no ill-will in saying this, but the .NET runtime provides the low-level primitives for doing this, these surface API's just aren't currently exposed in WinUI.

(Reasonably so -- this is a niche usecase that makes zero sense to prioritize)

But for future searchers, to save them from spending the time I did trying to accomplish this, I think it would be fair to set the following information forward:

- This is possible quite easily in WinForms applications as they deal with HWND's and the `WM_***` message pumps
- If you need to embed a "modern" .NET GUI inside of a parent app, as a plugin or similar, you (as of June 2021) want "XAML Islands"
	- The Windows Terminal XAML Islands code is surprisingly easy to understand, can't recommend it enough
		- https://github.com/microsoft/terminal/blob/main/src/cascadia/WindowsTerminal/AppHost.cpp#L218-L229
	- In the `microsoft/xaml-island-samples`, the example you probably want is https://github.com/microsoft/Xaml-Islands-Samples/tree/master/Samples/Win32/SampleCppApp
		- While trying to build this, I learned this is broken on recent Win SDK and won't compile. This helpful person fixed it for me. Either build from their branch or merge the changes yourself
			- https://github.com/microsoft/Xaml-Islands-Samples/pull/42
- You can quite literally just re-parent windows across processes as a last resort. Yes, it's as batshit insane as it sounds, and it's worked since the 90s. See the following:
	- https://microsoft.public.win32.programmer.gdi.narkive.com/VIe6TOyd/validity-of-creating-a-child-window-in-a-separate-process-to-the-parent-com-win32
	- https://devblogs.microsoft.com/oldnewthing/20130412-00/?p=4683

I hope this helps someone someday and saves you the many hours of my life I burned.

**Comment by GavinRay97** [comment]
It also might be worth noting in the documentation somewhere that it is entirely impossible to tell WinUI not to spawn a fresh window and to just re-use an existing `hwnd`.

**Comment by mdtauk** [comment]
This kind of scenario could be used for VST plugins for Digital Audio Workstation software

**Comment by GavinRay97** [comment]
@mdtauk This was exactly what I was trying to use it for! See the conversion between Miguel and myself here:
https://twitter.com/GavinRayDev/status/1399072530091106307

Also putting the words "VST" and "Digital Audio Workstation" in comments are probably good for future searchers coming from google, nice thought.


![image](https://user-images.githubusercontent.com/26604994/121731638-37489500-cabf-11eb-9721-c83416d80d09.png)

**Comment by sylveon** [comment]
FWIW the reason these kind of plugins are traditionally C++ only is that loading the .NET runtime in a process which doesn't belong to you is a dangerous process (even MS is strongly against using .NET for in-process shell extensions, which load in every process that opens a browse/save as dialog). You can't host multiple .NET Core runtimes in a single process, so if two plugins try to use two incompatible runtime versions (or a shell extension uses a version incompatible with the version the app uses), the world falls apart. The issue is even exacerbated if somebody tries to use .NET Framework instead of .NET Core, or mix those two together.

This isn't an issue with C++.

**Comment by GavinRay97** [comment]
If you use NativeAOT or LLVM NativeAOT for .NET and there's no dynamically loaded runtime, then is there still an issue?
