### ISSUE TITLE
Compiler Error CS0234 from attribute `[Windows.Foundation.Metadata.DefaultOverload]` in XamlTypeInfo.g.cs when project has a folder named 'Windows'

### ISSUE THREAD

**Issue by FreddyD-GH** [microsoft/microsoft-ui-xaml#5108]
**Describe the bug**
If you have a project with an existing namespace of 'MyApp.Windows', having the automatically generated XamlTypeInfo.g.cs file use an attribute of `[Windows.Foundation.Metadata.DefaultOverload]` will cause a compiler error with code `CS0234` and message `The type or namespace name 'Foundation' does not exist in the namespace 'MyApp.Windows' (are you missing an assembly reference?)`.

I believe this could be fixed by changing the generated attribute to `[global::Windows.Foundation.Metadata.DefaultOverload]` instead of just `[Windows.Foundation.Metadata.DefaultOverload]`.  I've often regretted putting all my WinUI Windows in a folder called 'Windows' due to similar problems elsewhere, but I don't see any reason not to use the `global::` prefix in this instance, as the rest of the file is also using it.

I saw this error occur when upgrading to Project Reunion 0.8.0 preview.  I was not getting the error on Project Reunion 0.5.7.

**Steps to reproduce the bug**
Not sure yet if the generated code uses the attribute in all scenarios, but all you need otherwise is to have some other code in a namespace that causes a CS0234 conflict, e.g. 'MyApp.Windows'

**Expected behavior**
The generated code should compile without error.

**Screenshots**
N/A

**Version Info**

NuGet package version: 
WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
N/A

**Comment by ranjeshj** [comment]
@alwu-msft as FYI

**Comment by alwu-msft** [comment]
The fix for this will be in either 0.8 Stable or the first servicing release after that.

**Comment by RealTommyKlein** [comment]
This is fixed in the first servicing release for Reunion 0.8, which should be available in the next 1-2 weeks.  Thanks!
