### ISSUE TITLE
Project template issue for Reunion 0.8 preview

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#5112]
**Describe the bug**
The target platform version specified in project template only applies to wapproj, but not the csproj.

**Steps to reproduce the bug**

1. Create a new WinUI 3 desktop applicaton.
2. Set the target platform version to 18362, and min version to 17763 in creation dialog.
3. The wapproj is created with 18362/17763, but the csproj is created with 19041/17763.

**Expected behavior**
Both projects created with 18362/17763.

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

**Comment by anawishnoff** [comment]
Hi @huoyaoyuan, thanks for filing this issue. I spoke with @alwu-msft, and he provided the following info:

This behavior is expected, if a bit confusing. The min/max version in the .csproj controls what APIs you have access to, and the min/max version in the .wapproj controls what version of the OS the resulting packaged app can be installed on. In a project that is able to package itself (a UWP app or one that is using Single-project MSIX packaging) then the distinction doesn’t exist (i.e. min/max version in the same project controls both APIs that can be used and which OS the resulting package can be installed on), but that’s not the case here.

**Comment by huoyaoyuan** [comment]
I don't think the behavior can be expected, because the projects in this state can't be built and reporting error for project reference.

**Comment by StephenLPeters** [comment]
@alwu-msft FYI
