### ISSUE TITLE
ContentDialog won't use any default style in UWP

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#5119]
**Describe the bug**

Currently, `ContentDialog`, no matter what, will always use default style provided by UWP SDK if a named style is not explicitly set.
This is also valid for the new default style provided by WinUI 2.6.
The only way to get the control to use it is to explicitly set the style to `DefaultContentDialogStyle`.
The only workaround that I found myself was to redefine the control myself and then to create a style for the new control instead.

**Steps to reproduce the bug**

1. Open XAML Controls Gallery.
2. Search for `ContentDialog` and click on `Show dialog`.
3. Notice the dialog using UWP style rather than WinUI style.

**Expected behavior**

`ContentDialog` can properly use custom default styles.

**Screenshots**

![image](https://user-images.githubusercontent.com/8152849/120170793-9fff5a00-c201-11eb-87a1-d64efa8c4929.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.5.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by FrayxRulez** [comment]
Ok, looks like this is a known issues: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-20348#derived-controls-with-winui-styles
I guess that it still makes sense to keep this ticket for public tracking purposes.

**Comment by StephenLPeters** [comment]
Are you seeing this behavior when using a out of the box ContentDialog? I thought that was working today.. I think this behavior is expected (but obviously not ideal) if you have a derived type.

**Comment by StephenLPeters** [comment]
The xaml controls gallery uses a custom content dialog, which is why it shows this behavior...
