### ISSUE TITLE
Question: Not support for AnyCPU build configuration for class libraries in v.0.8 preview.

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#5120]
Hello!

The Project Reunion  0.8 preview version has a limitation (see subject), described in [release notes](https://docs.microsoft.com/en-us/windows/apps/project-reunion/preview-channel#release-notes).

Will this limitation be lifted in the release version?

**Comment by AlexanderEgorov** [comment]
This change will make us to adapt our building farm and also testing system - this requires significant efforts. 
For this reason, we would like to know If you are going to lift this limitation in the next release.

**Comment by StephenLPeters** [comment]
I don't think we are going add anycpu support.  The release notes descirbes why pretty well, in fact I don't think this would even be a limitation.

**Comment by StephenLPeters** [comment]
@MikeHillberg

**Comment by BorzillaR** [comment]
@StephenLPeters, I apologize for forgetting to clarify that I am talking about the class library, not an application. It is impossible to build a class library with "Any CPU" configuration in Project Reunion Preview 0.8. This is a significant change and we want to know if this change remains in the feature releases.

**Comment by kalin-todorov** [comment]
@StephenLPeters is this intentional change for class libraries as well?

**Comment by gmurray81** [comment]
Yeah, this is odd guys, why prevent class libraries from being AnyCPU??

**Comment by Daniellled** [comment]
Is this still a limitation?

**Comment by StephenLPeters** [comment]
@llongley do you know?

**Comment by llongley** [comment]
@StephenLPeters No, I haven't done anything with AnyCPU.  @MikeHillberg or @codendone ?

**Comment by AlexanderEgorov** [comment]
@Daniellled, no, the last version preview3 works correctly.

**Comment by MikeHillberg** [comment]
This issue is probably better for tracking AnyCpu support:
https://github.com/microsoft/WindowsAppSDK/issues/1217
