### ISSUE TITLE
Question: Different styles in WinUI 2.5, 2.6 preview and 3

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#5123]
Why we see 3 different styles? (for example navigationview)
This is acceptable for version 2.6 preview, which has improved a lot, But why does version 3 go back and use the style of version 2.5? Also, some of its effects are disabled.😕

**Version 2.5**
![2 5](https://user-images.githubusercontent.com/9213496/120218165-94865000-c24e-11eb-9bc8-cb36dc709386.png)

**Version 2.6 Preview**

![2 6](https://user-images.githubusercontent.com/9213496/120225106-e1bbef00-c259-11eb-8085-a1aba51a81b1.png)

**Version 3.0**
![3](https://user-images.githubusercontent.com/9213496/120218195-9bad5e00-c24e-11eb-8280-588953fb9712.png)

**Comment by jordan-msftfan** [comment]
i was about to open a new issue to ask **is it now possible to use 2.6 styles on reunion 0.8 preview** ;p

i think the reason winui 3 styles looks different from winui 2.6 is that winui 3 is still in preview
if you look closely, you'll notice that winui 3 has the same style as winui 2.5 but without **reveal**

**Comment by ranjeshj** [comment]
WinUI 3.x has the WinUI 2.5 stabile release bits for the controls, hence what you are seeing there matches the 2.5 styles. 2.6 styles are still in preview. Hope that helps clarify.

**Comment by ghost1372** [comment]
> WinUI 3.x has the WinUI 2.5 stabile release bits for the controls, hence what you are seeing there matches the 2.5 styles. 2.6 styles are still in preview. Hope that helps clarify.

Thanks, when will the stable version 2.6 be released? Also When does WinUI3 use version 2.6?

**Comment by Crypties** [comment]
> WinUI 3.x has the WinUI 2.5 stabile release bits for the controls, hence what you are seeing there matches the 2.5 styles. 2.6 styles are still in preview. 

@ranjeshj   Are sure WinUI 3 will get that SunValley style? WinUI 2.6 is now out of preview and the 3.0 version still can't access that style. From what you can see, what would be the easiest way for someone ready to customize the code of its 3.0 version to either A) have it to use 2.6 controls, or B) have it to use the 2.6 SunValley style?   Thank you for helping @ranjeshj
