### ISSUE TITLE
NavigationView left compact mode - allow different pane backgrounds for expanded and collapsed

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#5125]
Today it's not possible to use a different background for the pane when the NavigationView is expanded in the left compact. I'd like to use background acrylic when collapsed and in-app acrylic when expanded but the same key (NavigationViewDefaultPaneBackground) applies to both expanded and collapsed state.

**Comment by mdtauk** [comment]
There should ideally be background resources for:
- Expanded
- Collapsed
- Overlay


Even if the same colour is used for all or some of them by default.

**Comment by ranjeshj** [comment]
@karenbtlai  as FYI

**Comment by Jaiganeshkumaran** [comment]
It would be much better if NavigationView exposed the internal SplitView's PaneBackground property, at least I can handle the logic for different modes myself.

**Comment by mdtauk** [comment]
> It would be much better if NavigationView exposed the internal SplitView's PaneBackground property, at least I can handle the logic for different modes myself.

I assume the NavigationView passes it's values down to the internal SplitView and applies it.  This is why the light-weight styles apply at the control level, without having to re-template

**Comment by karenbtlai** [comment]
Great, I can definitely create separate themeResources for that. As for exposing SplitView's PaneBackground property, that will be a bigger feature request as it is exposing a new API. @gabbybilka

**Comment by karenbtlai** [comment]
Update: this will not be able to be fixed, as in the latest PR #5231, there will not be a separate setter for Expanded visual state. PaneBackground setters not being orthogonal was causing rendering issues.
