### ISSUE TITLE
<WebView2>: printer not selectable with the mouse

### ISSUE THREAD

**Issue by ChrisK91** [microsoft/microsoft-ui-xaml#5126]
**Describe the bug**
When using a <WebView2>-Element, it's not possible to select a different printer with the mouse. Navigation the printers with the keyboard works as expected.

**Steps to reproduce the bug**
1. Create the sample application below
2. Right click an select "Print" or hit Ctrl + P
3a. Try to select a different printer with the mouse
3b. Open the printer selection with the mouse and navigate with the arrow keys and confirm with enter

MainWindow.xaml
```
<Window
    x:Class="TestingApp.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestingApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <WebView2 Source="https://github.com" />
    </Grid>
</Window>
```

**Expected behavior**
The printer should be selectable with the mouse (3a).

**Screenshots**
https://user-images.githubusercontent.com/1904175/120308279-39973c00-c2d4-11eb-839d-9f4f40cb2935.mp4

**Version Info**

NuGet package version: 

CommunityToolkit.Mvvm" Version="7.0.2"
CommunityToolkit.WinUI.UI.Controls" Version="7.0.2"
Microsoft.ProjectReunion" Version="0.5.7"
Microsoft.ProjectReunion.Foundation" Version="0.5.7"
Microsoft.ProjectReunion.WinUI" Version="0.5.7"

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        |  Yes,  Version 19042.985  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Installed Edge version: Version 91.0.864.37

**Comment by Naveen61097** [comment]
Any update on this issue?
