### ISSUE TITLE
TeachingTip.Attach property not found

### ISSUE THREAD

**Issue by mscherotter** [Microsoft/microsoft-ui-xaml#513]
**Describe the bug**
TeachingTip.Attach property is not found in 2.1.190319001-prerelease

**Steps to reproduce the bug**

1. Create a blank UI Project
2. Add Microsoft.UI.Xaml nuget package to the project
3.  Add a teaching tip to a page 
xmlns:muxc="using:Microsoft.UI.Xaml.Controls"

      <Button Content="test me">
            <muxc:TeachingTip.Attach>
                <muxc:TeachingTip Title="title" Subtitle="subtitle"/>
            </muxc:TeachingTip.Attach>
        </Button>
4. notice that the code fails to compile and inspecting the TeachingTip from metadata shows that no Attach property is available as described here https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.teachingtip.attachproperty 
**Expected behavior**
the TeachingTip.Attach property is found 

**Version Info**
2.1.190319001-prerelease Windows desktop/tablet
NuGet package version: 

2.1.190319001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes                        |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes                         |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by mscherotter** [comment]
[NoTeachingTipAttach.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3025726/NoTeachingTipAttach.zip)

**Comment by jevansaks** [comment]
Thanks for reporting, this was an API change that came about during spec review. You can see the final API proposal here: https://github.com/Microsoft/microsoft-ui-xaml-specs/pull/

The Attach property is now Target and is not an attached property. You can find updated sample snippets here: https://github.com/Microsoft/microsoft-ui-xaml-specs/blob/38e440ad3b0338994457ae7c408db9b25e07b395/active/teachingtip/TeachingTipSpec.md

**Comment by SavoySchuler** [comment]
Hi, @mscherotter, I am the PM for TeachingTip. Thank you for reaching out and for using our prerelease! I am looking into this issue now and I hope to have an answer to you shortly.

**Comment by SavoySchuler** [comment]
@mscherotter Thanks again for reaching out. A teaching tip is not visible by default as it is not a part of the visual tree. As such, it must be opened with .IsOpen=true in the codebehind.

Using your code sample, I added an x:Name for the teaching tip and a Click Event on the button to call  TestTip.IsOpen = true.




.xaml
`    
<Grid>
        <Button Content="test me" x:Name="Button" HorizontalAlignment="Center" Click="TestButton_Click">
        </Button>
        <muxc:TeachingTip x:Name="TestTip" Title="title" Subtitle="subtitle" Target="{x:Bind Button}" /></Grid>
`

.xaml.cs

`private void TestButton_Click(object sender, RoutedEventArgs e)
        {
            TestTip.IsOpen = true;
        }`

Adding this code makes the teaching tip appear when the button is clicked:

![App window with a centered button that says "test me". A teaching tip points down at the button from above with a title that says "title" and a subtitle that says "subtitle".](https://user-images.githubusercontent.com/16964652/55358090-698fee00-5483-11e9-9c4c-56a3aa3b3986.png)

The ["Create a teaching tip"](https://github.com/Microsoft/microsoft-ui-xaml-specs/blob/user/savoyschuler/teachingtip/active/teachingtip/TeachingTipSpec.md#create-a-teaching-tip) example our Guidelines shows a more complete example of teaching tip.

Does this help? Please let me know if you have any issues with this solution.

**Comment by SavoySchuler** [comment]
@mscherotter If you were specifically looking to have the tip show right away, you can use a Loaded event to do so: 

.xaml
`    <Grid>
        <Button x:Name="Button" Content="test me" HorizontalAlignment="Center" Loaded="TestButton_Loaded" >
        </Button>
        <muxc:TeachingTip x:Name="TestTip" Title="title" Subtitle="subtitle" Target="{x:Bind Button}" />
    </Grid>`

.xaml.cs
`        private void TestButton_Loaded(object sender, RoutedEventArgs e)
        {
            TestTip.IsOpen = true;
        }`
