### ISSUE TITLE
Combox Errors in KernelBase.dll--> WinRT Transform error

### ISSUE THREAD

**Issue by MarkBQE** [microsoft/microsoft-ui-xaml#5130]
**Describe the bug**

Combo box throws the following error when bound to an Observable collection of complex custom objects

**Steps to reproduce the bug**

 Bind a combobox to an observable collection using classic binding ItemsSource= {Binding CollectionName}, I am not using x:Bind since I am using MVVM pattern. These errors do not crash the app, however there are bunch of these errors when I click on the ComboBox dropdown. Wondering how this can be fixed, is this a known issue?

```
   <ComboBox x:Name="ClientList"  PlaceholderText="Pick a Client" ItemsSource="{Binding Clients}" DisplayMemberPath="name" SelectedValuePath="id" IsEditable="True"  
          Header="Client" Width="175">
                <Interactivity:Interaction.Behaviors>
                     <Interactions:EventTriggerBehavior EventName="SelectionChanged" SourceObject="{Binding 
                       ElementName=ClientList}" >
                        <Interactions:InvokeCommandAction Command="{Binding ClientSelectionChangedCommand}" CommandParameter="{Binding ElementName=ClientList, Path=SelectedItem}"/>
                    </Interactions:EventTriggerBehavior>
                </Interactivity:Interaction.Behaviors>
      </ComboBox>

```
**Expected behavior**

There should be no errors
**Screenshots**

![image](https://user-images.githubusercontent.com/23547957/120413982-15f0e780-c30e-11eb-8768-e2ae62cac5c8.png)

**Version Info**

NuGet package version: WinUI 0.8.0-preview

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes | 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            | Yes | 
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Petrarca181** [comment]
Was this fixed in some way? I'm on 1.0.0.0  and have the same "WinRT transform error"  also little lag when combo box  is opened.

**Comment by Maikelsoft** [comment]
Is this being fixed? Whenever I click a ComboBox where ItemsSource is bound to IReadOnlyList<Object>, **15** exceptions are thrown (also if the list is empty).
`
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B78BA0).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B76A50).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B76930).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B76A50).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B76930).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B76A50).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B76930).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B783E0).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B782C0).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B783E0).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B782C0).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B7CB50).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B78BA0).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B783E0).
Exception thrown at 0x00007FFBEDFA4F69 (KernelBase.dll) in [My Executable]: 0x40080202: WinRT transform error (parameters: 0x000000008000000B, 0x0000000080070490, 0x0000000000000014, 0x0000001E70B782C0).
`

**Comment by ynborokh** [comment]
Have the same problem with `DropDownButton` for WinAppSDK 1.1.0.

**Comment by timmarriott** [comment]
I have the same issue using Windows App SDK 1.1.5.  Very annoying to see in the output.  It makes it hard to spot issues I would like to see.

**Comment by tpoint75** [comment]
Still exists in  Windows App SDK 1.4

**Comment by AndreiHarasemiuc** [comment]
Still there..

**Comment by Diversiam90815** [comment]
Has this been solved? I also have this issue whenever I open up a  ComboBox..

**Comment by castorix** [comment]
I also get it in 1.5.24

**Comment by HannsKanns** [comment]
There are also apps with WinUI on Maui, which is logical. This has also been the case since Maui 9.0 and makes me nervous (not only that). This issue also affects performance, as it's best to handle bugs consistently and not 'sweep them under the rug'.

**Comment by ChrisGBSIT** [comment]
Still exists

**Comment by tpoint75** [comment]
I also get a lot of this exception spam opening a ComboBox:

Ausnahme ausgelöst bei 0x00007FF81CFC7F9A (KernelBase.dll) in UniHarp.exe: 0x40080202: WinRT transform error (Parameter: 0x000000008000000B, 0x0000000080070490, 0x0000000000000019, 0x000000EA912F7D50).
Ausnahme ausgelöst bei 0x00007FF81CFC7F9A (KernelBase.dll) in UniHarp.exe: 0x40080202: WinRT transform error (Parameter: 0x000000008000000B, 0x0000000080070490, 0x0000000000000019, 0x000000EA912F5C10).
Ausnahme ausgelöst bei 0x00007FF81CFC7F9A (KernelBase.dll) in UniHarp.exe: 0x40080202: WinRT transform error (Parameter: 0x000000008000000B, 0x0000000080070490, 0x0000000000000019, 0x000000EA912F5C10).
Ausnahme ausgelöst bei 0x00007FF81CFC7F9A (KernelBase.dll) in UniHarp.exe: 0x40080202: WinRT transform error (Parameter: 0x000000008000000B, 0x0000000080070490, 0x0000000000000019, 0x000000EA912F5C10).
Ausnahme ausgelöst bei 0x00007FF81CFC7F9A (KernelBase.dll) in UniHarp.exe: 0x40080202: WinRT transform error (Parameter: 0x000000008000000B, 0x0000000080070490, 0x0000000000000019, 0x000000EA912F7430).
Ausnahme ausgelöst bei 0x00007FF81CFC7F9A (KernelBase.dll) in UniHarp.exe: 0x40080202: WinRT transform error (Parameter: 0x000000008000000B, 0x0000000080070490, 0x0000000000000019, 0x000000EA912F7430).
