### ISSUE TITLE
List view - automatically scroll when you press a key

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5131]
In most desktop apps, when you have an item selected and focused through the keyboard and press a key that represents a letter or a number, it will automatically scroll to the first element which starts with the letter/number if it exists. However, this behaviour isn't present in the WinUI list view which makes it harder to navigate through large lists with a keyboard unless there's semantic zoom applied which isn't used a lot these days.

**Comment by ranjeshj** [comment]
@Jaiganeshkumaran This can be tricky for large collections. The list control would somehow have to know which data item to scroll to. In large lists where data is virtualized, this would end up causing de-virtualization. It should be relatively easy to do this from the app though I think.
