### ISSUE TITLE
ProgressRing should scale to available size within layout

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#5134]
@StephenLPeters @chingucoding if a developer wants the progress ring to take up the available space of it's layout container though, how do they do that? Most controls are responsive to the layout they're contained in by default...

This seems to just be masking the underlying problem of what was constraining the layout in the underlying code?

It's also a bit odd that the Stroke Thickness scales with the size and is effectively ignored (`ProgressRingStrokeThickness`)...? (Ties into #3293 as well)

_Originally posted by @michael-hawker in https://github.com/microsoft/microsoft-ui-xaml/issues/4544#issuecomment-853336019_

**Comment by ranjeshj** [comment]
I would expect the mux progress ring to behave the same way the wux progress ring does. This might not currently be the case because the mux progress ring uses lottie under the covers and scaling is probably the easiest way to fit within the layout bounds. If we can support the thickness value, then that atleast gives us the ability to achieve a different size without scaling.

**Comment by michael-hawker** [comment]
@ranjeshj the WUX `ProgressRing` was entirely different:
- It was a different animation (dots spinning in a ring vs. solid ring with segment)
- It didn't support determinate progress
- It only supported a 1:1 aspect ratio and not ovals

On top of that, it still had this same issue where it started as a fixed size instead of adapting to its layout. So, the new MUX ProgressRing has made some improvements, but I think there's still room for more to fix things forward.

We have removed it now that ProgressRing supports progress, but the `RadialProgressBar` in the Toolkit behaves much more how I'd expect as it adapts to the containing layout automatically and has a thickness property, so it's completely customizable by the end developer to suite whatever scenario they'd like without the scaled deformation of the ring's "track".

![image](https://user-images.githubusercontent.com/24302614/120681932-c109ba00-c450-11eb-82c2-77158613b212.png)

**Comment by michael-hawker** [comment]
Related to #2087
