### ISSUE TITLE
How to open a new Window in WinUI 3 for Desktop

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#5135]
I have a xaml file that has a Window inside

```
<Window
    x:Class="MyProject.MyWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Grid>
        <!-- The content of the window -->
    </Grid>
</Window>
```

In previous versions, don't remember which, I was opening the window with the following code

```
var form = new MyWindow();
form.Activate();
```
but it is not working anymore. How should I open a window?

**Comment by MarkBQE** [comment]
var m_window = new Window();
  m_window.Activate();

In the App.xaml you can do something like this. You can try a similar approach if you are trying to create a window from anywhere else. However to set the size, icon etc you may have to look into getting the Window Handle

**Comment by arivoir** [comment]
I get this exception

> Unhandled exception at 0x791B82F0 (Microsoft.ui.xaml.dll) in XXXXX: 0xC000027B: An application-internal exception has occurred (parameters: 0x1DC2B478, 0x00000001).

**Comment by shelllet** [comment]
I remember that in the roadmap it said that creating a new window is not currently supported

**Comment by torquerrr** [comment]
Window in Windows can't create a new window, that's what one should expect.

**Comment by llothar** [comment]
> I remember that in the roadmap it said that creating a new window is not currently supported

I thought it's possible when the old one toplevel window equals one thread model is used?

**Comment by knightmeister** [comment]
I tried this recently with reunion 0.5 and was also unable to get it working. I don't have the code handy, but in the app template where the window is instantiated and activated, I just copy and pasted that so there were two instances of the same object - it crashed while opening the second window.

**Comment by marb2000** [comment]
Multiple windows scenario is not yet suported. It' still in development. You use the preview releases to test the scenario, but it's removed from the supported versions.

**Comment by tinmac** [comment]
@marb2000  Is there an issue/discussion I can track to keep up to date with multiple window support? Thanks.

**Comment by KelvinJPS** [comment]
`var m_window = new MainWindow();
            m_window.Content = new Focus_Task() ;
            m_window.Activate();

`
Focus_Task is the other window
`namespace To_do_list_WinUI3.Views
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class Focus_Task : Page
    {
        public Focus_Task()
        {
            this.InitializeComponent();
        }


    }
}`
