### ISSUE TITLE
Unhandled exception in Microsoft.ui.xaml.dll

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#5136]
These Exceptions appearing on application startup when launching Windows head out of an Uno solution;

![image](https://user-images.githubusercontent.com/43340959/120556612-01d7e380-c3fd-11eb-9756-3f1d2dd0724c.png)

[ Continue ->]

![image](https://user-images.githubusercontent.com/43340959/120556648-11efc300-c3fd-11eb-8a2a-1abaee117a53.png)

[ Continue ->]

![image](https://user-images.githubusercontent.com/43340959/120556682-1fa54880-c3fd-11eb-8835-3d8d9f5518b5.png)

[ Continue ->]

And the process is terminating. 

**Steps to reproduce the bug**

Unfortunetaly I dont know how to reproduce these errors neither I possess tangible info or stack trace why these occur. Excpetions thrown not verbose as Stack traces and inner exceptions are null.  since I attempt to launch a complex app out of the framework Uno 3.8 but I am ready to share with you the requested and respective snippets to elaborate on this. 

NuGet package version: 
```
	<ItemGroup>
		<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-preview" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-preview" />
		<Manifest Include="$(ApplicationManifest)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Prism.DryIoc.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Prism.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Uno.Core" Version="2.4.0-dev.4" />
	</ItemGroup>
```

![image](https://user-images.githubusercontent.com/43340959/120559416-49606e80-c401-11eb-8a3d-12f5c30604f2.png)

![image](https://user-images.githubusercontent.com/43340959/120559630-a3f9ca80-c401-11eb-95fe-6f350b4d9e3f.png)

**Comment by ranjeshj** [comment]
@sigmarsson could you provide a callstack ? There isn't enough information here to debug the issue. You can try following the steps here - https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/debugging_crashes.md

**Comment by sigmarsson** [comment]
**@ranjeshj , Thanks for the guidance !**


Please take a look into the [dump file](https://drive.google.com/file/d/1-rCCZtkrO_UCYJ0eDqOxXhyj4Q544veN/view?usp=sharing)

**Comment by sigmarsson** [comment]
@ranjeshj , today i tested on a different host and witnessed the same crash I guess. 

![image](https://user-images.githubusercontent.com/43340959/121780132-4141c500-cb9f-11eb-86d4-fc7efd0945a9.png)

I cannot see in the stack trace what is actually having the null reference. The exception is thrown does not hold tangible and relevant pieces of information. 

Please see [here](https://drive.google.com/file/d/1ZMkXd6OuymZpD_UXwckfb7PZStjb9LEX/view?usp=sharing) another dump.
