### ISSUE TITLE
System could not hook for sleep and awake event by SystemEvents.PowerModeChanged in WinUI3 Desktop App

### ISSUE THREAD

**Issue by gscheartA** [microsoft/microsoft-ui-xaml#5139]
**Describe the bug**
I use SystemEvents hook API in App_Launched function for computer asleep hook. Here is my code

SystemEvents.PowerModeChanged += OnPowerChange;

private void OnPowerChange(object s, PowerModeChangedEventArgs e) 
{
    switch ( e.Mode ) 
    {
        case PowerModes.Resume: 
        break;
        case PowerModes.Suspend:
        break;
    }
} 

**But it does not work after I let my computer sleep and asleep.**
 
**Steps to reproduce the bug**

1. Add the code above
2. Sleep and wake computer , the event could not be triggered

**Expected behavior**
The event could be detected.

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0] 

Windows app type:
Win32

OS:
October 2020 Update (19042) 

Desktop

**Comment by ranjeshj** [comment]
@marb2000 @MikeHillberg This does not look like a WinUI3 issue. Should this go to reunion repo ?

**Comment by marb2000** [comment]
Agreed. It's an AppLifeCycle issue in Project Reunion.

**Comment by juanmalm** [comment]
Same issue here

**Comment by cnbluefire** [comment]
The events of SystemEvents class cannot be raised because when the SystemEventInvokeInfo object captures the SynchronizationContext of the current thread, the SynchronizationContext.Send is called when RaiseEvent, and DispatcherQueueSynchronizationContext has not implemented the Send method.

Solution:
```cs
SystemEvents.InvokeOnEventsThread(() =>
{
    // No need to set, the default is null
    //SynchronizationContext.SetSynchronizationContext(null);

    SystemEvents.DisplaySettingsChanged += (s, a) =>
    {
        Debug.WriteLine("DisplaySettingsChanged");
    };
});
```

**Comment by alski** [comment]
> The events of SystemEvents class cannot be raised because when the SystemEventInvokeInfo object captures the SynchronizationContext of the current thread, the SynchronizationContext.Send is called when RaiseEvent, and DispatcherQueueSynchronizationContext has not implemented the Send method.
> 
> Solution:
> 
> ```cs
> SystemEvents.InvokeOnEventsThread(() =>
> {
>     // No need to set, the default is null
>     //SynchronizationContext.SetSynchronizationContext(null);
> 
>     SystemEvents.DisplaySettingsChanged += (s, a) =>
>     {
>         Debug.WriteLine("DisplaySettingsChanged");
>     };
> });
> ```

Works for me too. 
https://github.com/microsoft/WindowsAppSDK/discussions/2630 does not.
