### ISSUE TITLE
XBF files do not produce deterministic outputs on rebuild

### ISSUE THREAD

**Issue by jevansaks** [microsoft/microsoft-ui-xaml#514]
This issue was reported in dotnet/roslyn#372. I'm filing this issue here to track the issue for GenXBF not producing deterministic outputs. @martinsuchan said there is a repro app in dotnet/roslyn#23456.

As an aside, when we've looked at this kind of problem in the past in Windows it's related to buffers with uninitialized (but unused) being written out to disk.

**Comment by alwu-msft** [comment]
This is fixed both in WinUI 3 and UWP XAML (starting with the 19041 SDK).
