### ISSUE TITLE
System.ArgumentException when trying to copy a StorageFile supplied by a drop operation

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#5142]
**Describe the bug**

Trying to use a StorageFile object supplied by a drop operation or by a file activation event results in a System.ArgumentException ("Value does not fall within the expected range"). Creating a new StorageFile object with the path of the file works fine.

**Steps to reproduce the bug**

1. Run the attached repro project and drag a file to the window
2. Observe that an exception is thrown
3. Uncomment the commented out line in MainWindow.xaml.cs
4. Observe that the copy operation now succeeds

**Expected behavior**

The supplied StorageFile object should be completely usable

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.ProjectReunion 0.8-preview

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes|
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

[StorageFileRepro.zip](https://github.com/microsoft/ProjectReunion/files/6569693/StorageFileRepro.zip)

**Comment by codendone** [comment]
The issue is in the StorageFile.CopyAsync() implementation, which required being run in a UWP. I believe the problem has been fixed for a future release of Windows. The recommendation for now is to use .NET to do the copy, such as:
```
    // Instead of:
    //     StorageFile result = await file.CopyAsync(ApplicationData.Current.LocalCacheFolder);
    string infile = file.Path;
    string uniqueId = $@"{Guid.NewGuid()}";
    string outfile = ApplicationData.Current.LocalFolder.Path + "\\" + uniqueId + file.Name;
    File.Copy(infile, outfile);
```
