### ISSUE TITLE
Question: [Is there a way to play video in WinUI3 app]

### ISSUE THREAD

**Issue by athulrajts** [microsoft/microsoft-ui-xaml#5150]
Since MediaPlayerElement is absent in 0.5 release, is there any to embed a video in application ?
A workaround i found was to use WebView2, but i can't get it to play on fullscreen.

**Comment by StephenLPeters** [comment]
@codendone or @ryandemopoulos

**Comment by codendone** [comment]
Using WebView2 is the recommendation currently for playing video. As you noted, direct fullscreen support isn't currently implemented. Fullscreen support should eventually be a built-in feature, but we don't currently have a planned timeline for that.

Doing fullscreen right now requires resizing the element to be the full size of the window, and then using win32 APIs to resize/position the window to be fullscreen. [This page](https://devblogs.microsoft.com/oldnewthing/20100412-00/?p=14353) has some old guidance which may help with the window changes.

**Comment by llothar** [comment]
> This page

So endless far away from what Apple offers you with AVKit and AVFoundation  which is not  only a MediaPlayer but a more a whole FinalCut Pro Editing component without a Gui.
