### ISSUE TITLE
[WinUI 2.6] UniformGridLayout has very large row height when its ItemTemplate is aspect ratio constrained

### ISSUE THREAD

**Issue by Ryken100** [microsoft/microsoft-ui-xaml#5154]
**Describe the bug**
Each row in UniformGridLayout becomes very tall when its `ItemTemplate` contains an element that is constrained to an aspect ratio (i.e. the element gets taller as it gets wider), such as an `Image`. The height of each row is equal to the height of the `ItemTemplate` element if it was stretched across the width of the page.

**Steps to reproduce the bug**
1. Create a blank UWP app and reference WinUI 2.6 prerelease
2. Add a `ScrollViewer` and `ItemsRepeater` to MainPage.xaml
3. In code-behind, set `ItemsRepeater.ItemsSource = new bool[100]` (the data source doesn't matter, we just need the items repeater to show some items)
4. Set `ItemsRepeater.Layout` to a `UniformGridLayout`
5. Set `UniformGridLayout.MinItemWidth` so that there are multiple columns in the layout
6. Set `ItemsRepeater.Layout` to an `Image` control that loads any image
7. Observe that the height of each row is much taller than the height of the images

[Repro app](https://github.com/microsoft/microsoft-ui-xaml/files/6610695/UniformGridLayoutRepro.zip)

**Expected behavior**
The height of each row should be equivalent to the height of the elements that make up each row.

**Screenshots**

This screenshot demonstrates the issue. The second row of images should be touching the first row, but instead the rows are very far apart.
![image](https://user-images.githubusercontent.com/26424620/121056798-94c1a680-c78c-11eb-85c9-62885ebdbeb4.png)

This screenshot includes a copy of the image in the background, to demonstrate that the height of each row is equivalent to the height of the image if it was stretched across the width of the window.
![image](https://user-images.githubusercontent.com/26424620/121057034-d81c1500-c78c-11eb-985f-b8b97758db03.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.6.0-prerelease.2104300001]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
It's my understanding that `UniformGridLayout` performs an initial layout pass on the first element to determine the height of each row. Perhaps that initial layout is performed using the entire width of the `ItemsRepeater`, when instead it should be performed using the calculated column width?

**Comment by StephenLPeters** [comment]
@ranjeshj and @chingucoding I think @Ryken100 's additional context is right, do you agree?

**Comment by chingucoding** [comment]
Yup, UniformGridLayout realizes the first item and uses it to measure the rest. Guess that UniFormGridLayout doesn't use the Min/Max Item Height/Width properties correctly. The fix is probably to set the Min/Max Width/Height on the realized item and see what it reports as heigh and width then.

**Comment by JustinXinLiu** [comment]
Is this something that we can fix now? ;)

**Comment by chingucoding** [comment]
> Is this something that we can fix now? ;)

If the question is whether it is technically feasible to fix now, yes we can fix this now! If the question is whether this will happen now, @StephenLPeters and @ranjeshj might know more :)

**Comment by StephenLPeters** [comment]
@chingucoding any chance this is something you would be interested in looking at?

**Comment by chingucoding** [comment]
I can take a look :)

**Comment by chingucoding** [comment]
@Ryken100 To somewhat mitigate this issue, you can set MinItemHeight so that the row height will get evaluated to that value. I know this is not ideal, however as of right now this seems to be the only way to workaround this issue until the bug fix has been merged and released.

**Comment by Ryken100** [comment]
@chingucoding Thanks for the suggestion! Unfortunately it won't work for our situation since our containing control doesn't have any context on what `ItemTemplate` will be used in its `ItemsRepeater` at any given moment. We don't mind waiting :)
