### ISSUE TITLE
Remove folders that dont get loc updates anymore

### ISSUE THREAD

**Issue by ranjeshj** [microsoft/microsoft-ui-xaml#5155]
These localized folders are not getting updates anymore (deprecated by touchdown localization)
bn-BD
ha-Latn-NG
sw-KE
uz-Latn-UZ

we can remove those folders from the build to avoid confusion since those files don't get updates.

**Comment by chingucoding** [comment]
Does this mean, delete them entirely?

**Comment by AndrewKeepCoding** [comment]
This seems to be done (#5429) by @ojhad.
