### ISSUE TITLE
COMException Class not registered when initializing CollectionViewSource

### ISSUE THREAD

**Issue by terrycox** [microsoft/microsoft-ui-xaml#5157]
**Describe the bug**
The following exception occurs when initializing a CollectionViewSource instance from a MsTest execution:

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.UI.Xaml.Data.CollectionViewSource..ctor()
   at Example.ExampleVm..ctor() in C:\Users\Terry Cox\Documents\Projects\Tests and Spikes\Example\Example\Example\ExampleVm.cs:line 36
   at ExampleTest.UnitTest1.TestMethod1() in C:\Users\Terry Cox\Documents\Projects\Tests and Spikes\Example\ExampleTest\UnitTest1.cs:line 12
```

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

The CollectionViewSource constructor executes properly from the Win32 Windows Application project rather than from the MsTest. The evident difference is that the CollectionViewSource constructor is invoked via reflection from the test session.

Steps to reproduce the bug:

Extract the attached Example.zip file. It contains an application created from the C# Blank App, Packaged (WinUI 3 in Desktop) Visual Studio template for Project Reunion 0.8.0-preview. An MsTest project was added to the solution using the Unit Test Project (.NET Core) template. Both the desktop app and the MsTest project were modified as shown in the code. To demonstrate the problem, build the solution and:

1. Set ExampleTest as the Startup Project and run or debug all tests. The test will fail with the above exception.
2. Set Example (Package) as the Startup Project and run or debug the app. The application will execute without an exception.
3. Comment out line 36 in file ExampleVm.cs ]colorSource = new CollectionViewSource();] 
4. Set ExampleTest as the Startup Project and run or debug all tests. The test will run without issue.

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion 0.8.0-preview
Microsoft.ProjectReunion.WinUI 0.8.0-preview

coverlet.collector 1.3.0
Microsoft.NET.Test.Sdk 16.7.1
MSTest.TestAdapter 2.1.1
MSTest.TestFramework 2.1.1

Edition	Windows 10 Pro
Version	21H1
Installed on	‎4/‎17/‎2021
OS build	19043.1023
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Comment by StephenLPeters** [comment]
I think this might be expected.  I don't think the MSTest harness is packaged with Winrt types, so I think similiar to how you can't launch an unpackaged app (with winrt types) from visual studio, you can't use winrt types in your MSTest app.  @MikeHillberg is that right? What is the correct pattern here? something similar to Winui2's test app that the MSTest process interacts with using Mita?

**Comment by terrycox** [comment]
I disagree with this assessment. This is not a UWP issue; it's a WinUI 3 issue, regardless of whether it's a UWP or Win32 app.  Also, CollectionViewSource is intended as a binding source; that's it's purpose. If it's not possible to run MsTest against classes using CollectionViewSource (i.e, ViewModels), then it's not possible to test such apps.

**Comment by Marv51** [comment]
I only had a quick glance at your example, but are you following this [blog post](https://devblogs.microsoft.com/ifdef-windows/winui-desktop-unit-tests/)? 

I did not see the `EnablePreviewMsixTooling` attribute in your ExampleTest.csproj file.

**Comment by terrycox** [comment]
Marv51, 

Thanks. I hadn't seen the blog post and will check it out.

**Comment by akilarajesh1313** [comment]
@terrycox Did using the EnablePreviewMsixTooling attribute solve the issue? If not, I'd be happy to follow up with our team for you.
