### ISSUE TITLE
Discussion: ClickOnce support and packaging apps

### ISSUE THREAD

**Issue by kevmoens** [microsoft/microsoft-ui-xaml#5158]
# Discussion: [your title here] 

## Related Links

We develop line of business applications (for manufacturers) which can be hosted on-premise by a customer.  We currently use click once to allow distribution of our WPF application.  We use mage.exe to create the click once package so the URL works on their server.
After looking at [WinUI 3 Release Notes](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#:~:text=Platform%20and%20OS%20support.%20WinUI%203%20-%20Project,in%20an%20MSIX%20app%3B%20No%20XAML%20Designer%20support) I noticed in the Developer Tools a bullet point of "Desktop apps support .NET 5 and C# 9, and must be packaged in an MSIX app".  

**Is there a plan to support Click Once for WinUI 3 in the future?**

If not, I have looked into MSIX and the only similar flow I saw was to use MakeAppX.exe but that is part of the Windows SDK.  **Is there a Nuget (for MakeAppX.exe)** that I could bundle with our product when we lay down the tools they use to create the MSIX package?  I don't want to require each customer to install the Windows SDK.  We had done similar things in the past with Microsoft downloads and since customers will be modified and sit on a version for 10+ years we have run across where customers are unable to download the packages as Microsoft has stopped support (rightfully so).

-Kevin

**Comment by StephenLPeters** [comment]
@JeanRoca and @ryandemopoulos FYI

**Comment by StephenLPeters** [comment]
@MikeHillberg also

**Comment by krschau** [comment]
I gave this issue a title, please feel free to change it if you feel something else would be more appropriate.
