### ISSUE TITLE
Textbox content display problem    project reunion 0.8_preview

### ISSUE THREAD

**Issue by Linjie123** [microsoft/microsoft-ui-xaml#5163]
**Describe the bug**

I set the vertical board in the content property of the textbox, but it is not displayed normally in the project

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26216203/121136486-4c77b680-c868-11eb-9967-89e990238e31.png)

![image](https://user-images.githubusercontent.com/26216203/121136496-4e417a00-c868-11eb-83ff-8df25511f019.png)

![image](https://user-images.githubusercontent.com/26216203/121136532-58fc0f00-c868-11eb-942a-59c7f7898776.png)

**Version Info**

NuGet package version: 

Windows app type:
 | Win32            |

 |  |

| Windows 10 version     19043.844             

**Additional context**

**Comment by beervoley** [comment]
@StephenLPeters, I think you're right that defaults chosen were wrong but I don't know why the TemplateBindings were also removed from the scrollViewer

**Comment by beervoley** [comment]
@StephenLPeters we removed it in this [PR](https://github.com/microsoft/microsoft-ui-xaml/pull/4037). We removed the bindings together with the wrong set defaults. Probably we need to put the templateBindings back just with the correct set default values ?:)
