### ISSUE TITLE
Visual studio 2019 UWP Winui

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5166]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-studio-2019-UWP-Winui/1439358)._

---
I have app  WinUi UWP created wtih vs 2019 16.9.4
Now i have VS 2019 16.10.0

I found no way to create winui for UWP only Reunion Desktop

I can compile old app, no problem,, but crash on run : ( i can install the old AppPackage and work)
`
#pragma checksum "D:\EuroMillions\EuroMillions\App.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "047CA96F1D27FF2B2E93739A9755EB6B053829B918C01B3E9A93608A4591429B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroMillions
{
#if ! DISABLE_XAML_GENERATED_MAIN
    /// <summary>
    /// Program class
    /// </summary>
    public static class Program
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 0.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        static void Main(string[] args)
        {
            global::Microsoft.UI.Xaml.Application.Start((p) => new App());
        }
    }
#endif

partial class App : global::Microsoft.UI.Xaml.Application
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 0.0.0.0")]
        private bool _contentLoaded;
        /// <summary>
        /// InitializeComponent()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.UI.Xaml.Markup.Compiler"," 0.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent()
        {
            if (_contentLoaded)
                return;

_contentLoaded = true;

global::System.Uri resourceLocator = new global::System.Uri("ms-appx:///App.xaml");
            global::Microsoft.UI.Xaml.Application.LoadComponent(this, resourceLocator);

#if DEBUG && ! DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
            DebugSettings.BindingFailed += (sender, args) =>
            {
                global::System.Diagnostics.Debug.WriteLine(args. Message);
            };
#endif
#if DEBUG && ! DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };
#endif
        }
    }
}

`

---
#### Feedback Bot on 6/2/2021, 11:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by kmgallahan** [comment]
Updating to Reunion .8 preview solved some immediate issues for me.

**Comment by alwu-msft** [comment]
Windows App SDK only supports UWP apps on Preview releases for now. Without further information from the issue filer, such as their project or information about what version of Windows App SDK was being used, this isn't actionable; hopefully they'll find their way here from the VS community tracker.
