### ISSUE TITLE
ProgressRing visual bug

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5173]
WinUI 2.X

no difference between 98% and 99% or the visual step is too small?

![image](https://user-images.githubusercontent.com/12285582/121684796-c7073700-caf1-11eb-8811-882ce9a59c36.png)
![image](https://user-images.githubusercontent.com/12285582/121684808-ca9abe00-caf1-11eb-9846-dc4472c03ff7.png)
![image](https://user-images.githubusercontent.com/12285582/121684828-cf5f7200-caf1-11eb-9bb0-f90f401d01b3.png)

**Comment by hez2010** [comment]
Also reproduce for 5% and 6%, 7% and 8%, 9% and 10%, 15% and 16%, 18% and 19%, 20% and 21%, 23% and 24%, 25% and 26%, 27% and 28%, 30% and 31%, 33% and 34%, 36% and 37%, 40% and 41%, 43% and 44%, 46% and 47%, 49% and 50%, 54% and 55%, 60% and 61%, 66% and 67%, 72% and 73%, 79% and 80%, 85% and 86%, 91% and 92%, 97% and 98%.

And the beginning and the ending of the shape are not connected in 100%.
![image](https://user-images.githubusercontent.com/14960345/121691339-7b588b80-caf9-11eb-971d-065f58134c7e.png)
