### ISSUE TITLE
DeleteButton in TextBox occupies full width when height is set for TextBox control

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#5175]
**Describe the bug**
DeleteButton in TextBox occupies full width when height is set for TextBox control. 

Please find the code example below:
`<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">`
        `<TextBox x:Name="textBox" PlaceholderText="enter a text" Height="300" Width="275" />`
`</StackPanel>`

**Steps to reproduce the bug**
1. Run the sample.
2. Start entering the text.
3. Note, delete button occupies full width of TextBox and text got hidden.

**Expected behavior**
Text should not be hidden, Delete button width should be 32.

**Screenshots**
![image](https://user-images.githubusercontent.com/55440472/121707828-9d034400-caf4-11eb-9709-38bda108528f.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.7]

**Comment by StephenLPeters** [comment]
@chrisglein FYI

**Comment by chrisglein** [comment]
This also repros with UWP XAML. Not a WinUI3 regression.

**Comment by chrisglein** [comment]
This does not repro if you set `TextWrapping="Wrap"`. However then the delete button isn't shown at all, so... really just a workaround if that's the intent.

Also isn't quite as bad if you don't specify `Width` and give the `TextBox` more horizontal breathing room. Still produces a mammoth delete button (seems like it is configured to absorb all available height and be square, but allowing extra width here at least allows the text to show).
