### ISSUE TITLE
Question: Get string resource in a WinUI 3 class library

### ISSUE THREAD

**Issue by iomismo** [microsoft/microsoft-ui-xaml#5182]
Hi, I am trying to load a string resource in a WinUI 3 class library. I mean, a class inside that class library uses Microsoft.ApplicationModel.Resources.ResourceLoader to GetString from a resw file inside that class library (Strings/en-US/Resources.resw), but it throws "ResourceMap not found".

`new Microsoft.ApplicationModel.Resources.ResourceLoader().GetString("MyResourceKey")`

Using x:Uid in xaml views inside the class library works for other resources. Creating the needed resources in the main WinUI Desktop app works.

I have tried different approaches with ResourceLoader(fileName, resourceMap) or ResourceManager but I cannot figure out how to use them from the docs.

Thanks

UPDATE: Fixed using new ResourceManager().MainResourceMap.GetValue("MyLib/Resources/ResourceKey").

**Comment by StephenLPeters** [comment]
> UPDATE: Fixed using new ResourceManager().MainResourceMap.GetValue("MyLib/Resources/ResourceKey").

Sweet!
