### ISSUE TITLE
Proposal: Right click expanded menu as not arrow

### ISSUE THREAD

**Issue by josh-65** [microsoft/microsoft-ui-xaml#5183]
Details are here  https://github.com/files-community/Files/issues/5202

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/121820932-539a2c80-cc8d-11eb-8749-7c8e4f555d58.png)
You sure its not an issue specifically with Files?

**Comment by josh-65** [comment]
According to them it a win ui issue but they might have not update recently. i will link this to them.

**Comment by mdtauk** [comment]
And it seems this may fix itself when WinUI 2.6 is done
![image](https://user-images.githubusercontent.com/7389110/121821306-226f2b80-cc90-11eb-87c9-9df5e4d25685.png)

**Comment by StephenLPeters** [comment]
Yes, this issue has already been fixed. :)
