### ISSUE TITLE
AppBarButtons as Secondary Items in a CommandBarFlyout do not have correct rounded corners

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#5184]
**Describe the bug**

The AppBarButtons in the CommandBarFlyout's SecondaryItems are incorrectly styled

**Steps to reproduce the bug**

1. Open MUXTestApp
2. Click on **CommandBarFlyout** > **Base CommandBarFlyout Tests
3. Click on **Show CommandBarFlyout with sub-menu**

**Expected behavior**

The AppBarButtons which are displayed in the CommandBarFlyout's **SecondaryItems** should be styled to match the MenuFlyout Items

**Screenshots**

![image](https://user-images.githubusercontent.com/7389110/121821400-885bb300-cc90-11eb-8147-b56c368e861c.png)

**Version Info**

NuGet package version: 

Current **Main** branch as of Sun 13th June 2021

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 (19043)        |  Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@teaP do you recognize this issue?

**Comment by StephenLPeters** [comment]
Actually, I think this is a MuxControlsTestApp app bug. There is a checkbox on the first page of the MuxControlsTestApp labled "Long Animations Disabled" which while checked applies a different style to command bar flyout (and some other things) the purpose being to remove some animations so we don't have to wait for them during tests.  If I uncheck that checkbox I see rounded corners on these elements as the default style is not applied.  @mdtauk could you confirm this is the case for your repro as well?

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/122154066-1637c980-ce5c-11eb-8c88-716a6a3e29bf.png)

![image](https://user-images.githubusercontent.com/7389110/122154205-59923800-ce5c-11eb-9e0f-92a1db6b4298.png)


You are absolutely right.  Thanks for responding, I would not have realised that is what was going on.
