### ISSUE TITLE
NavigationView Toggle Header Item not clipped/contained as pane expands.

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#5185]
**Describe the bug**

NavigationView Toggle Header Item not clipped/contained as pane expands.

**Steps to reproduce the bug**

1. Observe as you open the NavigationView pane in Overlay mode

**Expected behavior**

Items and their backplates should be clipped within the sidebar pane as it expands

**Screenshots**

![image](https://user-images.githubusercontent.com/7389110/121821832-73345380-cc93-11eb-8ba4-0fbfa22b8992.png)

**Version Info**

NuGet package version: 

Main branch built as of Sun 13th June 2021

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 (19043)        |  Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@karenbtlai Do you recognize this issue?

**Comment by StephenLPeters** [comment]
@ranjeshj FYI
