### ISSUE TITLE
Scrolling is very slow when binding the TextProperty in WinUI TextBlock

### ISSUE THREAD

**Issue by FarjanaParveen** [microsoft/microsoft-ui-xaml#5191]
**Describe the bug**
We have created the custom control like DataGrid and load the TextBlock as a UI element and bind the TextProperty with underlying data object, vertical scrolling is very slow. 

**Steps to reproduce the bug**
1. Open the sample [Desktop (2).zip](https://github.com/microsoft/microsoft-ui-xaml/files/6649219/Desktop.2.zip)
2. Please vertically scroll, note the scrolling is very slow. This issue is occurs in Desktop.

**Expected behavior**
Vertically scroll should be smooth like UWP 
[UWP (2).zip](https://github.com/microsoft/microsoft-ui-xaml/files/6649223/UWP.2.zip)

**Note : This issue is occurs in Desktop and not occurs in UWP**

**Version Info**

NuGet package version: 
[Microsoft.ProjectReunion.Foundation 0.5.0]
[Microsoft.ProjectReunion 0.5.0]
[Microsoft.ProjectReunion.WinUI 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        ||
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@FarjanaParveen do you know if this is also the case in the ProjectReunion 0.8 preview?

**Comment by FarjanaParveen** [comment]
@StephenLPeters yes this issue is occurs in 0.8 also

**Comment by FarjanaParveen** [comment]
@StephenLPeters  Any update on this?

**Comment by FarjanaParveen** [comment]
@StephenLPeters Any update on this?

**Comment by FarjanaParveen** [comment]
@StephenLPeters  Any update on this?

**Comment by FarjanaParveen** [comment]
@StephenLPeters  Any update on this?

**Comment by FarjanaParveen** [comment]
@StephenLPeters  Any update on this?

**Comment by StephenLPeters** [comment]
Hey @FarjanaParveen sorry I know not getting any responses can be very frustrating. We are tracking all Winui3 with some internal tools so rest assured we are aware of your issue. However I personally don't know the status of the issue.  @codendone might have more info.

@RBrid Might have insights as well.

**Comment by FarjanaParveen** [comment]
@RBrid  Any update on this?

**Comment by FarjanaParveen** [comment]
@RBrid  Any update on this?

**Comment by FarjanaParveen** [comment]
@RBrid Any update on this?

**Comment by FarjanaParveen** [comment]
@RBrid Any update on this?
