### ISSUE TITLE
Question: when will we get the Microsoft fluent design stable system?

### ISSUE THREAD

**Issue by Keshav901** [microsoft/microsoft-ui-xaml#5192]
hello ji;when we will get the microsoft fluent design stable sytem?

**Comment by StephenLPeters** [comment]
Hey @Keshav901 can you be more specific? I'm not sure what you are referring to.

**Comment by Keshav901** [comment]
Hello ji i was asking for this
link = https://www.microsoft.com/design/fluent/#/
Fluent is an open-source, cross-platform design system that gives designers
and developers the frameworks they need to create engaging product
experiences—accessibility, internationalization, and performance included.

**Comment by StephenLPeters** [comment]
@pag3 and @chigy FYI

**Comment by chigy** [comment]
@Keshav901 , please could you be more specific?
I am not sure what you mean by "stable system?"
