### ISSUE TITLE
Question: What is a way that a custom graphic device can be put in WinUI?

### ISSUE THREAD

**Issue by orion160** [microsoft/microsoft-ui-xaml#5193]
For Win32 Apps whats the way to insert a graphic device/context like DirectX, OpenGL or Vulkan. I've read about SwapchainPane but it seems that will only work with DirectX.

#1554 it is a work in progress, as mentioned there is there a way to do it in WinUI 2? If so should i expect a similar way in v3?

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by codendone** [comment]
WinUI 3 support for custom graphics is largely the same as WinUI 2: `SwapChainPanel`, `SurfaceImageSource`, and `VirtualSurfaceImageSource`. All of these take a DirectX surface, so whatever you want to draw with will need to draw or copy into the DX surface.

**Comment by orion160** [comment]
Ok, so there is support for DirectX. As other graphic API have no support or are not on the roadmap, **is it even possible to load an OGL or Vulkan context?**

**Comment by codendone** [comment]
Everything in WinUI is drawn/composed in the end using DirectX. For more information, check out [the composition layer documentation](https://docs.microsoft.com/en-us/windows/uwp/composition/composition-visual-tree). For surfaces, only DirectX surfaces are supported--that is what it is drawing with and to. Using other graphics APIs would require having them do offscreen drawing and then copying to a DX surface (or, if the desired graphics API supports it, perhaps using an interop option for that API to draw to a DX surface).

**Comment by orion160** [comment]
Thanks, before to close the issue, as a doubt, will be GDI replaced in the **long** future?

> Everything in WinUI is drawn/composed in the end using DirectX
