### ISSUE TITLE
Announcing WinUI 3 - Project Reunion 0.8 Release Candidate! 🤩

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#5195]
# Announcing WinUI 3 - Project Reunion 0.8 Release Candidate!

We've just shipped a release candidate for WinUI 3 - Project Reunion 0.8! This release is a new version of WinUI 3 that includes new bug fixes and stability improvements. This is a release candidate build, so while it is mostly stable, it should not be used for production apps. This version of WinUI 3 ships inside of the Project Reunion 0.8 RC package. 

## Shipping WinUI 3 with Project Reunion

In order to use this version of WinUI 3, you'll download the Project Reunion Visual Studio Extension (VSIX) and the Project Reunion NuGet package to get started. The Project Reunion VSIX includes WinUI Project Templates that you'll use to build your WinUI 3 app, as well as access to other Project Reunion components, such as [DWriteCore](https://docs.microsoft.com/windows/apps/project-reunion/dwritecore) and [MRTCore](https://docs.microsoft.com/windows/apps/project-reunion/mrtcore/mrtcore-overview).  

For more on Project Reunion, see their [documentation](https://docs.microsoft.com/windows/apps/project-reunion/) and [repository](https://github.com/microsoft/ProjectReunion). For installation instructions, see  [Project Reunion 0.8 Release Candidate](https://aka.ms/projectreunion/0.8-release-candidate). 

## What's new in WinUI 3 - Project Reunion 0.8 Release Candidate

These are all of the new changes in WinUI 3 since the release of WinUI 3 - Project Reunion 0.5.

- The Pivot control has been added back in and can now be used in any WinUI 3 app.
- All bug fixes from Project Reunion v0.5.5, v0.5.6, and v0.5.7 are included with this release.
- New bug fixes, including:
    - Mouse right-click in TextBox crashes the application
    - NavigationView causes crash in UWP, Reunion 0.5 Preview
    - ProgressBar doesn't show difference between Paused and Error option
    - Crash in RichEditBox when copying/pasting/changing text style
    - Window caption buttons are misplaced when SetTitleBar is not set or null

    To see the full list of bugs fixed, see the **Bugs Fixed in 0.8 Release Candidate** section below. 

- The `ColorHelper.ToDisplayName` API is no longer available. 
- The following types have been removed:
    - `Microsoft.Graphics.IGeometrySource2D`
    - `Microsoft.Graphics.IGeometrySource2DInterop`

    Please use `Windows.Graphics.IGeometrySource2D` and `Windows.Graphics.IGeometrySource2DInterop` instead.
 
- All types in the `Microsoft.System` namespace have been moved to the `Microsoft.UI.Dispatching` namespace, including the [DispatcherQueue class](https://docs.microsoft.com/windows/winui/api/microsoft.system.dispatcherqueue?view=winui-3.0).

- The `AcrylicBrush.BackgroundSource` property has been removed, since `HostBackdrop` is not supported as a `BackgroundSource` in WinUI 3.

### Experimental Features
This release does not include experimental features. If you'd like to continue using experimental features in your app, feel free to continue using the latest [Project Reunion 0.8 Preview](https://docs.microsoft.com/windows/apps/project-reunion/preview-channel).

### Known Issues
Please keep in mind that the WinUI 3 - Project Reunion 0.8 release candidate is still a pre-release product, and has a number of known issues and limitations that our team continues to work on.

For a list of all the known issues for the Project Reunion 0.8 Release Candidate, please see the **[Project Reunion release page](https://aka.ms/projectreunion/0.8-release-candidate)**.

### Bugs Fixed in 0.8 Release Candidate
This is the list of all bugs fixed in WinUI 3 since the 0.8 Preview. For a list of bugs previously fixed in the WinUI 3 - Project Reunion 0.8 Preview, see [this list](https://docs.microsoft.com/windows/apps/winui/winui3/release-notes/release-notes-08-preview#list-of-bugs-fixed-in-winui-3---project-reunion-08-preview).

- Fix tooltip to get the current pointer position rather than using the last seen pointer ID
- #4197: Change in Appearance of AppBarButton with Flyout on CommandBar in WinUI3 
- Crash in shadows code when device goes on low-battery 
- #3001: EffectiveViewport does not work in certain cases for WinUI desktop apps
- #3658: Rotation in Manipulation events is wrong
- Crash in RichEditBox when copying/pasting/changing text style
- #4536: Padding of Minimize/Maximize/Close Buttons is Not Consistent When Using ExtendsContentIntoTitleBar
- [microsoft/projectreunion/#923](https://github.com/microsoft/ProjectReunion/issues/923): Building class library with XAML controls in Release config fails

## Getting started with WinUI 3 - Project Reunion 0.8 release candidate
For this release, you'll download the Project Reunion VSIX and NuGet package directly from the Project Reunion GitHub announcement and manually add references into your project. Please see the information below to help you get started:

**[Install Project Reunion 0.8 RC](https://aka.ms/projectreunion/0.8-release-candidate)**

**[Create WinUI 3 Projects](https://docs.microsoft.com/windows/apps/winui/winui3/winui-project-templates-in-visual-studio)**

While you're developing, check out the [API Reference documentation for WinUI 3 - Project Reunion 0.8 Preview](https://docs.microsoft.com/windows/winui/api/).

Take a look at our walk-through docs:

- [Get started with WinUI 3 for desktop apps](https://docs.microsoft.com/windows/apps/winui/winui3/get-started-winui3-for-desktop)
- [Build a basic WinUI 3 app for desktop](https://docs.microsoft.com/windows/apps/winui/winui3/desktop-build-basic-winui3-app)
- [Get started with WinUI 3 for UWP apps (Preview)](https://docs.microsoft.com/windows/apps/winui/winui3/get-started-winui3-for-uwp)

You can also update your existing WinUI 3 app to use the new Project Reunion 0.8 release candidate using these instructions: [Update existing projects to the latest release of Project Reunion](https://docs.microsoft.com/windows/apps/project-reunion/update-existing-projects-to-the-latest-release).

We love feedback! We encourage you to file any bug, big or small, on our repo using [this template](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=). Knowing which issues and features are important and/or critical to our customers highly influences which ones we tackle. Even though we now ship with Project Reunion, please continue to file WinUI-specific bugs on this repo.  

## Using WinUI 3 - Project Reunion 0.8 Preview with our ecosystem partners

WinUI 3 - Project Reunion 0.8 Preview is in the process of being integrated into several other important ecosystem technologies. To test out and follow that progress, check out some of our partner technologies below:

- [Actipro Software](https://www.actiprosoftware.com) is migrating their vast UI control offerings over to WinUI 3, including their SyntaxEditor code editor, propertygrid, native type edit boxes, docking/MDI, charts, and more.

- [DevExpress](https://www.devexpress.com/winui/): DevExpress has released 20 new WinUI controls with Project Reunion 0.5 support, including the Data Grid, Scheduler, Charts, Ribbon Toolbar, and more. All 20 UI components are available free-of-charge.

- [GrapeCity](https://www.grapecity.com/) plans to bring their popular desktop UI controls to WinUI later this year! Learn more about their [data connection service components](https://www.grapecity.com/componentone/net-service-component?utm_source=Microsoft%20TAP&utm_medium=Dynamic&utm_campaign=project-reunion-0-5-preview-announcement) for WinUI.

- [Infragistics](https://www.infragistics.com/products/winui): Ultimate UI for WinUI brings business critical, high performing, and feature rich line of business controls to your apps that target any platform that runs Windows (including Windows on ARM64).

- [Syncfusion](https://www.syncfusion.com/winui-controls): Updated their projects to Microsoft.ProjectReunion from Microsoft.WinUI following upgrade instructions. All their controls are working fine.

- [Telerik UI for WinUI](https://www.telerik.com/winui): the market first UI controls suite for crafting Win32 and UWP apps with WinUI 3, comes with feature-rich controls like Ribbon, DataGrid, Charts, Gauges, Barcode, and more.

- [Uno Platform](https://github.com/unoplatform): Use WinUI 3 – Reunion 0.8 Preview, XAML and C# to build pixel-perfect, single-codebase, native applications that can run on Web, Desktop and Mobile. It is free, open-source and available today.

- [Windows Community Toolkit (Microsoft)](https://aka.ms/wct-winui3): The WCT is currently working on supporting Reunion 0.8 release candidate. It provides tons of new controls and capabilities for use in your WinUI app. You can check out their open source repo [here](https://aka.ms/windowstoolkit).

## What's next
We'll be releasing the next stable version of WinUI 3, which will ship as a part of the Project Reunion 0.8 release. You can find updates and announcements regarding that here on our GitHub repo.

To keep up with progress being made on WinUI 3, please see our [feature roadmap](https://aka.ms/winui3/feature-roadmap) which gets updated regularly. We also give monthly updates on our WinUI Community Calls, where you can directly ask the team any questions you have.

**Comment by crramirez** [comment]
Hello,

About this: "The AcrylicBrush.BackgroundSource property has been removed, since HostBackdrop is not supported as a BackgroundSource in WinUI 3."

Now I cannot share the XAML with the UWP WinUI 2.5. There is any way, using conditionals to accomplish this? I am trying with: https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/conditional-xaml but it is not working

Regards,
Carlos

**Comment by crramirez** [comment]
Well,

In my case, I discovered that all BackgroundSource values were Backdrop which is the default. So, I deleted them. The only place where I use HostBackdrop is in the App.xaml which is not shared among projects. I am fine for now.

Regards,
Carlos

**Comment by mrlacey** [comment]
With the 0.8RC now out (and feature-locked) when can we expect an update to the roadmap to know what can be expected in the 1.0 release?
Currently, the roadmap lumps all other future customer capabilities under a "Planned for a future update" group but that doesn't help us know what to expect and plan accordingly.
(This is also a question for the next community call 👩‍💻☎ -- but there's no separate issue for questions for that--yet.)

**Comment by huoyaoyuan** [comment]
> since HostBackdrop is not supported as a BackgroundSource in WinUI 3

When an old member contains no longer supported feature, the common practice of .NET is making it an no-op. This helps migrating and sharing code with older platform.

Moreover, the common expectation of HostBackdrop should be "should work sometimes later". Keeping the member as a placeholder should be OK.

**Comment by gabbybilka** [comment]
Check out #6172 to see features from this release in Windows App SDK 1.0.
