### ISSUE TITLE
Subscribtion to the ContentControl.Loaded event resets the IsLoaded flag.

### ISSUE THREAD

**Issue by AlexanderEgorov** [microsoft/microsoft-ui-xaml#5197]
**Steps to reproduce the bug**

1. Run the attached sample [WinUIBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6657259/WinUIBug.zip)
2. Click the button
3. The button's caption says 'False'

```XAML
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <ContentControl x:Name="cc"/>
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    </StackPanel>
```

```C#
        private void myButton_Click(object sender, RoutedEventArgs e) {
            cc.Loaded += MyButton_Loaded;
            myButton.Content = cc.IsLoaded.ToString();
        }
        private void MyButton_Loaded(object sender, RoutedEventArgs e) {
            
        }
```

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.7] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
huh, good bug.

**Comment by StephenLPeters** [comment]
@chrisglein I think this is a Framework team API?
