### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by JCK-cloudLV** [microsoft/microsoft-ui-xaml#5203]
Hi,

The latest release installed via SPM cannot build, so this PR changes the following to fix that:
- Change the structure of public headers directory
- Fix import conditions to import headers correctly

Before:

```objective-c
#if SWIFT_PACKAGE || GTLR_USE_MODULAR_IMPORT
  @import GoogleAPIClientForRESTCore;
#elif GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif
```

After:

```objective-c
#if GTLR_USE_MODULAR_IMPORT
  @import GoogleAPIClientForRESTCore;
#elif GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#elif COCOAPODS
  #import "GTLRObject.h"
#else
  #import <GoogleAPIClientForRESTCore/GTLRObject.h>
#endif
```

Resolves #400 

__Originally posted by @woxtu in https://github.com/google/google-api-objectivec-client-for-rest/pull/424__

**Comment by StephenLPeters** [comment]
This looks like it was filed in the wrong repo.  If I'm wrong let me know.
