### ISSUE TITLE
Question: What is the state about the community calls?

### ISSUE THREAD

**Issue by pavelpokutnev** [microsoft/microsoft-ui-xaml#5205]
Dear WinUI-Team,
i would like to know the state of the monthly community calls? The link for the [ICS file](https://github.com/microsoft/microsoft-ui-xaml/blob/main/communitycalls/WinUICommunityCall.ics) on the main page looks to be broken and the scheduled meetings from the last ICS have not taken place. Can you please comment on it or update the new schedule please?

**Comment by Marv51** [comment]
According to https://twitter.com/WindowsUI/status/1402672613265227782

The next call has been rescheduled for Wednesday June 30th. (I'm sure purely coincidentally past the June 24th Windows event.)

**Comment by michael-hawker** [comment]
@Marv51 thanks for answering the question!

@anawishnoff who's in charge of keeping the ICS file up-to-date?

**Comment by anawishnoff** [comment]
Thanks @Marv51! @pavelpokutnev You should see a GitHub issue in the next week or two to collect questions for the next community call. I'll go ahead and update that .ics file, thanks for bringing this to my attention.
