### ISSUE TITLE
WinUI 3 - default font family should be Segoe Fluent Icons for FontIcon on Build 21327 and later

### ISSUE THREAD

**Issue by jgkumaran** [microsoft/microsoft-ui-xaml#5208]
In Platform XAML, the default font family for FontIcon is Segoe Fluent Icons on Build 21327 and later but in WinUI 3 it's still Segoe MDL2 Assets.

**Comment by mdtauk** [comment]
WinUI 2.6 onwards should bundle the Font with the framework, so the OS minimum version wont cause issues.  Version 1 of the visual style can continue to use the OS font
