### ISSUE TITLE
[ContentDialog] StaticResource binding does not actually evaluate the correct resources for max/min width/height

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#5209]
**Describe the bug**

When overriding the resources for the Min/Max Width/Height of the ContentDialog, those are actually ignored.

**Steps to reproduce the bug**

1. Create an ContentDialog with very wide content (wider than 600 px)
2. Override ContentDialogMaxWidth resource (or whatever it is called)

**Expected behavior**

Observe the ContenDialog is capped at 560 px (the value provided by WinUI 2).
**Screenshots**

**Version Info**

NuGet package version: 

WinUI 2.6 prerelease 210430001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19043)              | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Initially observed by the great folks from the Files repo. @yaichenbaum FYI

Also, if it's fine I would change the binding for these resources back to ThemeResource binding.

**Comment by StephenLPeters** [comment]
Can you be more specific about where you are overriding the light weight style?  You have to been extremely precise to get the system to work.

**Comment by chingucoding** [comment]
The file in question that exhibits the behavior is this one: https://github.com/files-community/Files/blob/85785de496eb3d435ab60787e728145a8c6b5272/Files/Dialogs/SettingsDialog.xaml

Setting Style={StaticResource DefaultContentDialogStyle} results in the dialog not receiving max width as expectede but being using the WinUI resource. When adding the DefaultContentDialogStyle to the App.xaml and changing the StaticResource bindings for Max/Min Width/Height to ThemeResource binding, it works as expected.

**Comment by StephenLPeters** [comment]
I see, it will be very complicated for me to explain why this is the case but there are two things we can do:

1) move the definition of ContentDialogMaxWidth from the base dictionary to the theme dictionary.  You can see that this is already the case for the V1 style of ContentDialog.  This will allow you to override ContentDialogMaxWidth from App.Xaml if you put the resource in a dictionary within XamlControlsResources.MergedDictionaries

2) we can change the mark up extension used from {StaticResource} to {ThemeResource}. This will allow you to define an override at any parent in the visual tree. But not in app.xaml because this resource is defined in the system's Generic.xaml.

We can do both to allow overrides in either location.  I've talked about doing this for all of our resources, but there are concerns about the perf implications of that change.  If you've found a resource you want to override I think we should make both updates to this resource.

**Comment by yaichenbaum** [comment]
@StephenLPeters Obviously others might have different use cases, but for us, the second option would solve the issue we are having in Files.

**Comment by jamorais** [comment]
So for the 2.6 release, what can we do to modify contentdialog max width?
It was working on 2.5. upgrading to 2.6 breaks my apps.

**Comment by chingucoding** [comment]
> So for the 2.6 release, what can we do to modify contentdialog max width?
It was working on 2.5. upgrading to 2.6 breaks my apps.

The only thing you can do is retemplate and change the values through that :/

**Comment by chingucoding** [comment]
I would like to work on this issue.

**Comment by ArchieCoder** [comment]
@chingucoding Hi, in my UWP app which I use Xaml 2.7.1, if my ContentDialog uses BasedOn="{StaticResource DefaultContentDialogStyle}", no matter the value that I put in App.xaml, it does not work 
![image](https://user-images.githubusercontent.com/1608424/170387108-621b008c-dffc-4e7c-bf51-bad1e16ecf19.png)

What is the trick? Thanks

**Comment by jamorais** [comment]
> @chingucoding Hi, in my UWP app which I use Xaml 2.7.1, if my ContentDialog uses BasedOn="{StaticResource DefaultContentDialogStyle}", no matter the value that I put in App.xaml, it does not work ![image](https://user-images.githubusercontent.com/1608424/170387108-621b008c-dffc-4e7c-bf51-bad1e16ecf19.png)
> 
> What is the trick? Thanks

i ended up creating a modified style of the content dialog. Just set the MaxWidth and MaxHeight to your liking.


                    <Style TargetType="ContentDialog" BasedOn="{StaticResource DefaultContentDialogStyle1000}" />

                    <Style x:Key="**DefaultContentDialogStyle1000**" TargetType="ContentDialog">
                        <Setter Property="Foreground" Value="{ThemeResource ContentDialogForeground}" />
                        <Setter Property="Background" Value="{ThemeResource ContentDialogBackground}" />
                        <Setter Property="BorderThickness" Value="{ThemeResource ContentDialogBorderWidth}" />
                        <Setter Property="BorderBrush" Value="{ThemeResource ContentDialogBorderBrush}" />
                        <Setter Property="IsTabStop" Value="False" />
                        <Setter Property="PrimaryButtonStyle" Value="{ThemeResource DefaultButtonStyle}" />
                        <Setter Property="SecondaryButtonStyle" Value="{ThemeResource DefaultButtonStyle}" />
                        <Setter Property="CloseButtonStyle" Value="{ThemeResource DefaultButtonStyle}" />
                        <Setter Property="CornerRadius" Value="{ThemeResource OverlayCornerRadius}" />
                        <Setter Property="Template">
                            <Setter.Value>
                                <ControlTemplate TargetType="ContentDialog">
                                    <Border x:Name="Container">
                                        <VisualStateManager.VisualStateGroups>
                                            <VisualStateGroup x:Name="DialogShowingStates">
                                                <VisualStateGroup.Transitions>
                                                    <VisualTransition To="DialogHidden">
                                                        <Storyboard>
                                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="LayoutRoot" Storyboard.TargetProperty="Visibility">
                                                                <DiscreteObjectKeyFrame KeyTime="0:0:0" Value="Visible" />
                                                            </ObjectAnimationUsingKeyFrames>
                                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="LayoutRoot" Storyboard.TargetProperty="IsHitTestVisible">
                                                                <DiscreteObjectKeyFrame KeyTime="0:0:0" Value="False" />
                                                            </ObjectAnimationUsingKeyFrames>
                                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetName="ScaleTransform" Storyboard.TargetProperty="ScaleX">
                                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0" Value="1.0" />
                                                                <SplineDoubleKeyFrame KeyTime="{StaticResource ControlFastAnimationDuration}" KeySpline="{StaticResource ControlFastOutSlowInKeySpline}" Value="1.05" />
                                                            </DoubleAnimationUsingKeyFrames>
                                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetName="ScaleTransform" Storyboard.TargetProperty="ScaleY">
                                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0" Value="1.0" />
                                                                <SplineDoubleKeyFrame KeyTime="{StaticResource ControlFastAnimationDuration}" KeySpline="{StaticResource ControlFastOutSlowInKeySpline}" Value="1.05" />
                                                            </DoubleAnimationUsingKeyFrames>
                                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetName="LayoutRoot" Storyboard.TargetProperty="Opacity">
                                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0" Value="1.0" />
                                                                <LinearDoubleKeyFrame KeyTime="{StaticResource ControlFasterAnimationDuration}" Value="0.0" />
                                                            </DoubleAnimationUsingKeyFrames>
                                                        </Storyboard>
                                                    </VisualTransition>
                                                    <VisualTransition To="DialogShowing">
                                                        <Storyboard>
                                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="LayoutRoot" Storyboard.TargetProperty="Visibility">
                                                                <DiscreteObjectKeyFrame KeyTime="0:0:0" Value="Visible" />
                                                            </ObjectAnimationUsingKeyFrames>
                                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetName="ScaleTransform" Storyboard.TargetProperty="ScaleX">
                                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0" Value="1.05" />
                                                                <SplineDoubleKeyFrame KeyTime="{StaticResource ControlNormalAnimationDuration}" KeySpline="{StaticResource ControlFastOutSlowInKeySpline}" Value="1.0" />
                                                            </DoubleAnimationUsingKeyFrames>
                                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetName="ScaleTransform" Storyboard.TargetProperty="ScaleY">
                                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0" Value="1.05" />
                                                                <SplineDoubleKeyFrame KeyTime="{StaticResource ControlNormalAnimationDuration}" KeySpline="{StaticResource ControlFastOutSlowInKeySpline}" Value="1.0" />
                                                            </DoubleAnimationUsingKeyFrames>
                                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetName="LayoutRoot" Storyboard.TargetProperty="Opacity">
                                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0" Value="0.0" />
                                                                <LinearDoubleKeyFrame KeyTime="{StaticResource ControlFasterAnimationDuration}" Value="1.0" />
                                                            </DoubleAnimationUsingKeyFrames>
                                                        </Storyboard>
                                                    </VisualTransition>
                                                </VisualStateGroup.Transitions>
                                                <VisualState x:Name="DialogHidden" />
                                                <VisualState x:Name="DialogShowing">
                                                    <VisualState.Setters>
                                                        <Setter Target="LayoutRoot.Visibility" Value="Visible" />
                                                        <Setter Target="BackgroundElement.TabFocusNavigation" Value="Cycle" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="DialogShowingWithoutSmokeLayer">
                                                    <VisualState.Setters>
                                                        <Setter Target="LayoutRoot.Visibility" Value="Visible" />
                                                        <Setter Target="LayoutRoot.Background" Value="{x:Null}" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                            </VisualStateGroup>
                                            <VisualStateGroup x:Name="DialogSizingStates">
                                                <VisualState x:Name="DefaultDialogSizing" />
                                                <VisualState x:Name="FullDialogSizing">
                                                    <VisualState.Setters>
                                                        <Setter Target="BackgroundElement.VerticalAlignment" Value="Stretch" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                            </VisualStateGroup>
                                            <VisualStateGroup x:Name="ButtonsVisibilityStates">
                                                <VisualState x:Name="AllVisible" >
                                                    <VisualState.Setters>
                                                        <Setter Target="FirstSpacer.Width" Value="{StaticResource ContentDialogButtonSpacing}" />
                                                        <Setter Target="SecondaryColumn.Width" Value="*" />
                                                        <Setter Target="SecondaryButton.(Grid.Column)" Value="2" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="NoneVisible">
                                                    <VisualState.Setters>
                                                        <Setter Target="CommandSpace.Visibility" Value="Collapsed" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="PrimaryVisible">
                                                    <VisualState.Setters>
                                                        <Setter Target="PrimaryButton.(Grid.Column)" Value="4" />
                                                        <Setter Target="SecondaryButton.Visibility" Value="Collapsed" />
                                                        <Setter Target="CloseButton.Visibility" Value="Collapsed" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="SecondaryVisible">
                                                    <VisualState.Setters>
                                                        <Setter Target="SecondaryButton.(Grid.Column)" Value="4" />
                                                        <Setter Target="PrimaryButton.Visibility" Value="Collapsed" />
                                                        <Setter Target="CloseButton.Visibility" Value="Collapsed" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="CloseVisible">
                                                    <VisualState.Setters>
                                                        <Setter Target="PrimaryButton.Visibility" Value="Collapsed" />
                                                        <Setter Target="SecondaryButton.Visibility" Value="Collapsed" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="PrimaryAndSecondaryVisible">
                                                    <VisualState.Setters>
                                                        <Setter Target="SecondaryButton.(Grid.Column)" Value="4" />
                                                        <Setter Target="CloseButton.Visibility" Value="Collapsed" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="PrimaryAndCloseVisible">
                                                    <VisualState.Setters>
                                                        <Setter Target="SecondaryButton.Visibility" Value="Collapsed" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="SecondaryAndCloseVisible">
                                                    <VisualState.Setters>
                                                        <Setter Target="PrimaryButton.Visibility" Value="Collapsed" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                            </VisualStateGroup>
                                            <VisualStateGroup x:Name="DefaultButtonStates">
                                                <VisualState x:Name="NoDefaultButton" />
                                                <VisualState x:Name="PrimaryAsDefaultButton">
                                                    <VisualState.Setters>
                                                        <Setter Target="PrimaryButton.Style" Value="{StaticResource AccentButtonStyle}" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="SecondaryAsDefaultButton">
                                                    <VisualState.Setters>
                                                        <Setter Target="SecondaryButton.Style" Value="{StaticResource AccentButtonStyle}" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                                <VisualState x:Name="CloseAsDefaultButton">
                                                    <VisualState.Setters>
                                                        <Setter Target="CloseButton.Style" Value="{StaticResource AccentButtonStyle}" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                            </VisualStateGroup>
                                            <VisualStateGroup x:Name="DialogBorderStates">
                                                <VisualState x:Name="NoBorder" />
                                                <VisualState x:Name="AccentColorBorder">
                                                    <VisualState.Setters>
                                                        <Setter Target="BackgroundElement.BorderBrush" Value="{ThemeResource SystemControlForegroundAccentBrush}" />
                                                    </VisualState.Setters>
                                                </VisualState>
                                            </VisualStateGroup>
                                        </VisualStateManager.VisualStateGroups>
                                        <Grid x:Name="LayoutRoot">
                                            <Rectangle x:Name="SmokeLayerBackground" Fill="{ThemeResource ContentDialogSmokeFill}" />
                                            <Border
                                x:Name="BackgroundElement"
                                Background="{TemplateBinding Background}"
                                FlowDirection="{TemplateBinding FlowDirection}"
                                BorderThickness="{TemplateBinding BorderThickness}"
                                BorderBrush="{TemplateBinding BorderBrush}"
                                BackgroundSizing="InnerBorderEdge"
                                CornerRadius="{TemplateBinding CornerRadius}"
                                MinWidth="{ThemeResource ContentDialogMinWidth}"
                                **MaxWidth="1000"**
                                MinHeight="{ThemeResource ContentDialogMinHeight}"
                                MaxHeight="{ThemeResource ContentDialogMaxHeight}"
                                HorizontalAlignment="Center"
                                VerticalAlignment="Center"
                                RenderTransformOrigin="0.5,0.5">
                                                <Border.RenderTransform>
                                                    <ScaleTransform x:Name="ScaleTransform" />
                                                </Border.RenderTransform>
                                                <Grid x:Name="DialogSpace" CornerRadius="{ThemeResource OverlayCornerRadius}">
                                                    <Grid.RowDefinitions>
                                                        <RowDefinition Height="*" />
                                                        <RowDefinition Height="Auto" />
                                                    </Grid.RowDefinitions>
                                                    <ScrollViewer
                                        x:Name="ContentScrollViewer"
                                        HorizontalScrollBarVisibility="Disabled"
                                        VerticalScrollBarVisibility="Disabled"
                                        ZoomMode="Disabled"
                                        IsTabStop="False">
                                                        <Grid
                                            Background="{ThemeResource ContentDialogTopOverlay}"
                                            Padding="{StaticResource ContentDialogPadding}"
                                            BorderThickness="{StaticResource ContentDialogSeparatorThickness}"
                                            BorderBrush="{ThemeResource ContentDialogSeparatorBorderBrush}">
                                                            <Grid.RowDefinitions>
                                                                <RowDefinition Height="Auto" />
                                                                <RowDefinition Height="*" />
                                                            </Grid.RowDefinitions>
                                                            <ContentControl
                                                x:Name="Title"
                                                Margin="{StaticResource ContentDialogTitleMargin}"
                                                Content="{TemplateBinding Title}"
                                                ContentTemplate="{TemplateBinding TitleTemplate}"
                                                FontSize="20"
                                                FontFamily="XamlAutoFontFamily"
                                                FontWeight="SemiBold"
                                                Foreground="{TemplateBinding Foreground}"
                                                HorizontalAlignment="Left"
                                                VerticalAlignment="Top"
                                                IsTabStop="False">
                                                                <ContentControl.Template>
                                                                    <ControlTemplate TargetType="ContentControl">
                                                                        <ContentPresenter
                                                            Content="{TemplateBinding Content}"
                                                            MaxLines="2"
                                                            TextWrapping="Wrap"
                                                            ContentTemplate="{TemplateBinding ContentTemplate}"
                                                            Margin="{TemplateBinding Padding}"
                                                            ContentTransitions="{TemplateBinding ContentTransitions}"
                                                            HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                                            VerticalAlignment="{TemplateBinding VerticalContentAlignment}" />
                                                                    </ControlTemplate>
                                                                </ContentControl.Template>
                                                            </ContentControl>
                                                            <ContentPresenter
                                                x:Name="Content"
                                                ContentTemplate="{TemplateBinding ContentTemplate}"
                                                Content="{TemplateBinding Content}"
                                                FontSize="{StaticResource ControlContentThemeFontSize}"
                                                FontFamily="{StaticResource ContentControlThemeFontFamily}"
                                                Foreground="{TemplateBinding Foreground}"
                                                Grid.Row="1"
                                                TextWrapping="Wrap" />
                                                        </Grid>
                                                    </ScrollViewer>
                                                    <Grid
                                        x:Name="CommandSpace"
                                        Grid.Row="1"
                                        HorizontalAlignment="Stretch"
                                        VerticalAlignment="Bottom"
                                        XYFocusKeyboardNavigation="Enabled"
                                        Padding="{StaticResource ContentDialogPadding}"
                                        Background="{TemplateBinding Background}">
                                                        <Grid.ColumnDefinitions>
                                                            <ColumnDefinition x:Name="PrimaryColumn" Width="*" />
                                                            <ColumnDefinition x:Name="FirstSpacer" Width="0" />
                                                            <ColumnDefinition x:Name="SecondaryColumn" Width="0" />
                                                            <ColumnDefinition x:Name="SecondSpacer" Width="{StaticResource ContentDialogButtonSpacing}" />
                                                            <ColumnDefinition x:Name="CloseColumn" Width="*" />
                                                        </Grid.ColumnDefinitions>
                                                        <Button
                                            x:Name="PrimaryButton"
                                            Content="{TemplateBinding PrimaryButtonText}"
                                            IsEnabled="{TemplateBinding IsPrimaryButtonEnabled}"
                                            Style="{TemplateBinding PrimaryButtonStyle}"
                                            ElementSoundMode="FocusOnly"
                                            HorizontalAlignment="Stretch" />
                                                        <Button
                                            x:Name="SecondaryButton"
                                            Content="{TemplateBinding SecondaryButtonText}"
                                            IsEnabled="{TemplateBinding IsSecondaryButtonEnabled}"
                                            Style="{TemplateBinding SecondaryButtonStyle}"
                                            ElementSoundMode="FocusOnly"
                                            HorizontalAlignment="Stretch" />
                                                        <Button
                                            x:Name="CloseButton"
                                            Grid.Column="4" 
                                            Content="{TemplateBinding CloseButtonText}"
                                            Style="{TemplateBinding CloseButtonStyle}"
                                            ElementSoundMode="FocusOnly"
                                            HorizontalAlignment="Stretch" />
                                                    </Grid>
                                                </Grid>
                                            </Border>
                                        </Grid>
                                    </Border>
                                </ControlTemplate>
                            </Setter.Value>
                        </Setter>
                    </Style>

**Comment by ArchieCoder** [comment]
@jamorais [jamorais](https://github.com/jamorais) Thanks for answering.

Today, I'm able to use my values set in the App.xaml, but I'm not able to see the new ContentDialog style at all with round corners for example and the 2 tones background. Deleting or adding _<Style BasedOn="{StaticResource DefaultContentDialogStyle}" TargetType="ContentDialog" /> does not do anything!

I tried your style but it does not work, the width is still capped.

**Comment by ArchieCoder** [comment]
@jamorais Your fix works!! Thanks. May I ask you where you found the resource definition?

**Comment by jamorais** [comment]
> @jamorais Your fix works!! Thanks. May I ask you where you found the resource definition?

if i'm not mistaken, on the winui github page

https://github.com/microsoft/microsoft-ui-xaml/blob/8faca194c943df556afa1f0f8a44ad9697cb43ad/dev/CommonStyles/ContentDialog_themeresources_v1.xaml
