### ISSUE TITLE
NavigationView Overlay mode shifts contents as border appears

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#5212]
**Describe the bug**

When you toggle the NavigationView pane and it appears overlaid.  The pane gains rounded corners and a border outline.  This shifts the NavigationViewItems

**Steps to reproduce the bug**

1. MUXTestApp > NavigationView > Navigation IsPaneOpen Test
2. Toggle the navigation pane open and closed with the Hamburger Button
3. Observe the Settings item at the bottom as well as the Home and Apps icons

**Expected behavior**

NavigationViewItems should maintain their horizontal and vertical positions as the pane slides open and closed.

**Screenshots**

![image](https://user-images.githubusercontent.com/7389110/122489703-2ffe1b80-cfd8-11eb-8749-873a9a84bf70.png)
_Toggled Closed - (Settings icon is crisp)_

![image](https://user-images.githubusercontent.com/7389110/122489741-46a47280-cfd8-11eb-8fca-a93eef66a1b5.png)
_Toggled Open - (Settings icon is blurry)_

![image](https://user-images.githubusercontent.com/7389110/122490015-e19d4c80-cfd8-11eb-9cde-5beedbeccf81.png)
_Top NavigationViewItems seem to be shifted down by 1px - Bottom items up by 1px_

![image](https://user-images.githubusercontent.com/7389110/122490252-7b64f980-cfd9-11eb-9803-291f629e27e7.png)
![image](https://user-images.githubusercontent.com/7389110/122490279-8fa8f680-cfd9-11eb-8849-e1adbb0fc5e3.png)

**Version Info**

NuGet package version: 

Current Main branch built Fri 18 Jun 2021

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| 21H1                                           | Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**I believe the problem is that the border around the pane does not exist in the closed state, and adding it on toggle, is repositioning the items.  Perhaps if the border were present in both modes, but set to transparent when closed, and coloured/filled on opening.  So the position of the items takes into account the border thickness.**

**Comment by StephenLPeters** [comment]
@karenbtlai FYI

**Comment by karenbtlai** [comment]
@mdtauk Thanks for the investigation! You are completely correct in the additional context part. I can send a fix for that along with my other PR :)
