### ISSUE TITLE
The FileOpenPicker's method PickSingleFileAsync throws ComException

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#5214]
**Describe the bug**
Hi, just tried to pick an image but got an exception - `System.Runtime.InteropServices.COMException: 'Invalid window handle. (0x80070578)'` To reproduce try the following code.

**Steps to reproduce the bug**
```csharp
            FileOpenPicker filePicker = new FileOpenPicker();
            foreach(string ext in new []{ ".jpeg", ".jpg", ".png", ".bmp" }) 
                filePicker.FileTypeFilter.Add(ext);
            
            filePicker.ViewMode = PickerViewMode.Thumbnail;
            filePicker.SuggestedStartLocation = PickerLocationId.PicturesLibrary;
            filePicker.SettingsIdentifier = "ImageFilePicker";
            filePicker.CommitButtonText = "Insert";

            StorageFile file = await filePicker.PickSingleFileAsync(); //throws exception
```

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.5: 0.5.7] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Jaiganeshkumaran** [comment]
You need to cast the picker to IInitializeWithWindow and call it's Initialize with the window handle to use it in a desktop app.

**Comment by Marv51** [comment]
See #2716

**Comment by StephenLPeters** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.-ctor?view=winrt-19041#remarks

**Comment by alexdi220** [comment]
Thanks all for the answers. But it still looks like a bug. The WA is ok but believe should be fixed in the future versions.
