### ISSUE TITLE
WinUI Project Reunion 0.5 - Win32 C# SwapChainPanel example

### ISSUE THREAD

**Issue by moseforniz** [microsoft/microsoft-ui-xaml#5215]
Hi, I would like develop a desktop application (no UWP) with Net5 (C#) and WinUI3 that interop with a library to show realtime AV streaming.
I searched an example (or tutorial) about SwapChainPanel with this  settings but I haven't found it.
Any suggestion are apreciate.

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by codendone** [comment]
SwapChainPanel requires drawing with DirectX, which is typically done in C++. If you're looking for a C#-only solution, I suggest checking out [Win2D](https://github.com/Microsoft/Win2D) to use its CanvasControl for graphics rendering in WinUI3. I believe there is a sample of Win2D on Project Reunion 0.5.7 [here](https://github.com/microsoft/Win2D-Samples/commit/763d80dd8ea42d73a4533218d1ba9a20f5cdc095).

**Comment by moseforniz** [comment]
@codendone Thanks for your reply. 
I need to add some details to explain better the SwapChainPanel requirement.
I need to use an thirt part library into my application, a method signature of this library need a SwapChainPanel component ref.
The library supplier have an example to implement this library, but this example are written for UWP/C# application, when I translate the code for my WinUI desktop application appeare an error.
I need an example of working WinUI Net5 app that use SwapChainPanle to exclude a my error and ask an intervent of supplier.

**Comment by codendone** [comment]
If there is an existing library you're trying to use I think it would be most helpful to have an example written for that library. Is that library for WinUI3, meaning it references **Microsoft**.UI.Xaml.Controls.SwapChainPanel rather than **Windows**.UI.Xaml.Controls.SwapChainPanel?

**Comment by TomAtWork** [comment]
We have been using for years sharpdx (Netstandard 1.1) to draw 2D content to a swapchain panel on Winforms, WPF and UWP. WIN2D is no alternative (it is much more higher level, no shader access (geometry shader is a must). There is now Vortice.Windows using Net Standard 2.0 - i have not tried it. What would you recommend to draw a 'Hello World' (colored triangle defined with shaders) on a SwapChainPanel using WinUI ?

**Comment by moseforniz** [comment]
> If there is an existing library you're trying to use I think it would be most helpful to have an example written for that library. Is that library for WinUI3, meaning it references **Microsoft**.UI.Xaml.Controls.SwapChainPanel rather than **Windows**.UI.Xaml.Controls.SwapChainPanel?

The library use `Windows.UI.Xaml.Controls.SwapChainPanel` and is not for WinUI3.
Unfortunately the conversation with the supplier is not easy and it's slow, I would like to prepare a simple example to share with their to use like a base for examples and requests.


> We have been using for years sharpdx (Net Standard 1.1) to draw 2D content to a SwapChainPanel on WinForms, WPF and UWP. Win2D is no alternative (it is much more higher level, no shader access (geometry shader is a must). There is now Vortice.Windows using Net Standard 2.0 - i have not tried it.
> What would you recommend to draw a 'Hello World' (colored triangle defined with shaders) on a SwapChainPanel using WinUI ?

I'm a newbie in this context 😅. 
That I search it's exactly an example/tutorial to create an "hello world" application like you descrive.

**Comment by IngmarBitter** [comment]
@moseforniz  did you find a way to create the `hello world` of `WinUi3 + C# + Dx12 swap chain panel`?
I'm looking for the same.
I did find `TerraFX` as library that facilitates `WinForms + C# (net5 or net6) + Dx12 swap chain panel`.
It even allows for C# based Dx12 rendering code.
Now I'm looking to change the WinForms host to a WinUi3 host and a WinUi3 based hello world would be great to help with that.

**Comment by moseforniz** [comment]
@IngmarBitter I'm sorry but for now the project with WinUI3 is in standby.
