### ISSUE TITLE
Implement data automation peer for hierarchical NavigationView

### ISSUE THREAD

**Issue by licanhua** [microsoft/microsoft-ui-xaml#522]
hierarchical NavigationView have the same problem will treeview. narrator may use wrong automationpeer after items are collpsed, then expanded.
Details please see #500

**Comment by jevansaks** [comment]
@licanhua you don't need to file an issue to complete a PR. If you wanted to track the bug, the bug should describe the user impact. Thanks!

**Comment by licanhua** [comment]
@jevansaks This is not for Treeview's PR, but to track the same issue which NavigationView should resolve.

**Comment by jevansaks** [comment]
Oops! Sorry, my bad. Will fix tags.

**Comment by chingucoding** [comment]
Given that we switched to ItemsRepeater for NavigationView, and we also handle expand/collapse with regard to UIA correctly, I think this issue can be closed.

**Comment by chingucoding** [comment]
@StephenLPeters ping

**Comment by StephenLPeters** [comment]
sounds good, thanks. @ojhad and @licanhua fyi
