### ISSUE TITLE
Support interfaces for x:DataType

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5222]
Today x:DataType doesn't support interfaces which means you have to resort back to classic Binding or write a wrapper object. Please support interfaces for x:DataType so x:Bind can be used for them in a data template.

**Comment by StephenLPeters** [comment]
@fabiant3 and @RealTommyKlein FYI

**Comment by JaiganeshKumaran** [comment]
x:DataType set to an interface does actually seem to work in both WinUI 2 and WinUI 3. Looks like a bug with the IntelliSense.
