### ISSUE TITLE
Question: How to save the Deployment step WinUI 0.8-pre ?

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#5225]
I experience **Deploy** is always neccessary after ecah build , otherwise the break points are gone. Perhaps the PDB files are deployed too? Is it possible to debug without continous delivery/deployment ?

**Comment by StephenLPeters** [comment]
How would Deploying not bee neccessary, since you've built a new version of the app?

**Comment by sigmarsson** [comment]
Yeah. True. I've somewhere you planed to eliminate the package project from the chain. Maybe that step could facilitate accelerating a bit the dev phase.

**Comment by ranjeshj** [comment]
I think you are asking about unpackaged apps 
https://github.com/microsoft/ProjectReunion#roadmap

**Comment by krschau** [comment]
Closing. Please @ me to reopen if you don't feel your question was answered.
