### ISSUE TITLE
Question: Deploy exception

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5226]
\bin\x64\Debug\AppX" could not be deleted. UnauthorizedAccessException - Access to the path 'resources.pri' is denied. [0x80070005]

this is killing me.

**Comment by StephenLPeters** [comment]
This implies that something has a handle to your deployment directory.  Make sure that your executable isn't still running.  If it isn't then restarting visual studio would be my next try...

**Comment by HppZ** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP1000: Cannot copy file "\bin\x64\Debug\resources.pri" to layout "\bin\x64\Debug\AppX\resources.pri". IOException - The requested operation cannot be performed on a file with a user-mapped section open. [0x800704C8]

**Comment by HppZ** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0500: The folder "\bin\x64\Debug\AppX" could not be deleted. UnauthorizedAccessException - Access to the path 'resources.pri' is denied. [0x80070005]

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/124102542-0a224d80-da93-11eb-9712-0d62e156c3a3.png)

**Comment by evelynwu-msft** [comment]
That suggests Start Menu was holding onto an app asset (probably the icon). Manually uninstalling the deployed app could possibly force Start Menu to release the file and allow VS to redeploy; killing the `StartMenuExperienceHost.exe` process (a new instance will automatically start after a few seconds) should definitely do the trick.
