### ISSUE TITLE
Question: Integration of custom DirectX 11 3D renderer

### ISSUE THREAD

**Issue by llfab** [microsoft/microsoft-ui-xaml#5228]
We currently build our desktop applications based on WPF. We plan to use WinUI 3 in den future. For 3D rendering we use our own custom renderer based on DirectX 11. We have not managed to integrate the renderer into WPF seamlessly with decent performance because of the different DirectX versions (WPF uses DirectX 9). Therefore, the renderer renders onto a Windows Forms Control surface that is integrated into WPF using WindowsFormsHost. 

Can a Windows Forms Control be integrated into WinUI 3?
WinUI 3 talks about using the latest DirectX version. Would there be an optimized way to integrate a DirectX 11 texture into the WinUI 3 scene graph?

**Comment by StephenLPeters** [comment]
@codendone for the DirectX support

@Austin-Lamb for the Islands question.

We support putting Winui components into WPF or WinForms projects, however I don't think we support putting a WinForms control into a Winui project.  I think SwapChainPanel supports DirectX11, but @codendone will know.

**Comment by codendone** [comment]
For DirectX11, you can use:
* [SurfaceImageSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.surfaceimagesource?view=winrt-20348) to have a DirectX texture tightly integrated with the UI
* [VirtualSurfaceImageSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.virtualsurfaceimagesource?view=winrt-20348) if you want a really large texture that the user can scroll around in where your code only needs to draw tiles the user can see
* [SwapChainPanel](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swapchainpanel?view=winrt-20348) if you have a surface which is redrawing at a high frame rate

**Comment by FrancisKoo** [comment]
@codendone Can I use ffmpeg decode the video and rendered with DirectX in SwapChainPanel

**Comment by GeorgeS2019** [comment]
For discussion of[ **DirectX 3D renderer** using SwapchainPanel in reunion](https://github.com/helix-toolkit/helix-toolkit/issues/1598)

**Comment by codendone** [comment]
I'm not aware of any existing sample for rendering video into a SwapChainPanel. MediaFoundation can be used to render into a swapchain which can be put in a SwapChainPanel, and this is how XAML's MediaElement/MediaPlayerElement works. I see some of the elements for this in [this sample](https://github.com/microsoft/WebRTC-universal-samples/tree/master/Samples/ChatterBox-Sample), but that isn't doing simple video playback. I think having a standalone sample for this would be good.

**Comment by ryan-weil** [comment]
> For DirectX11, you can use:
> 
>     * [SurfaceImageSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.surfaceimagesource?view=winrt-20348) to have a DirectX texture tightly integrated with the UI
> 
>     * [VirtualSurfaceImageSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.virtualsurfaceimagesource?view=winrt-20348) if you want a really large texture that the user can scroll around in where your code only needs to draw tiles the user can see
> 
>     * [SwapChainPanel](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swapchainpanel?view=winrt-20348) if you have a surface which is redrawing at a high frame rate

Is this supported for WPF as well?
