### ISSUE TITLE
(WinUI 3 desktop) Page.TopAppBar & Page.BottomAppBar does not show content

### ISSUE THREAD

**Issue by blissvalley** [microsoft/microsoft-ui-xaml#5229]
I tired placing CommandBar or AppBar inside Page.TopAppBar and Page.BottonAppBar but nothing is shown.

**Comment by StephenLPeters** [comment]
I think these APIs are a hold over from the windows phone days... I'm not surprised they don't work.  @MikeHillberg If there were ever an API to delete these might be the one. Thoughts?

@blissvalley I think your CommandBar should just appear in your page's content.

**Comment by blissvalley** [comment]
@StephenLPeters Yes, the CommandBar appears if I placed it inside page content. BTW, if I have a Page.BottomBar declared, it does show a black bar at the bottom, but no content.

**Comment by chrisglein** [comment]
Agreed that the action here moving forward should be to retire these APIs, if they remain unsupported (as they are today).

**Comment by shelllet** [comment]
😞  another unsupported important feature.

**Comment by krschau** [comment]
This is fixed in 1.1, and currently serviced in 0.8.9. It is expected to be in the next 1.0 servicing fix as well.
