### ISSUE TITLE
recycled TreeViewItems may not generate child TreeViewItems in UWP TreeView

### ISSUE THREAD

**Issue by frauenholz** [microsoft/microsoft-ui-xaml#523]
**Describe the bug**
When binding an ObservableCollection of hierarchical data objects to the Windows.UI.Xaml.ControlsTreeView ItemsSource, 
if a data object is removed from the ObservableCollection (removing the corresponding TreeViewItem and its children), and the data object is added back to the ObservableCollection (adding a recycled TreeViewItem), the added TreeViewItem's child items are not generated.

**Steps to reproduce the bug**

1. bind an ObservableCollection to a TreeView
2. move a TreeViewItem(with children) by swapping (RemoveAt( i ) , InsertAt( i + 1)) item positions in the list
3. repeat step 2, 
the TreeViewItem removed in step 2 will be recycled, and the child nodes will not be generated

Note: the error is not seen when moving a TreeViewItem(with children) from position 1 to position 0 in the ObservableCollection, in fact a TreeViewItem that has lost it's children will get them back in this case.

**Expected behavior**
TreeViewItems retain their child nodes when their positions change in an ObservableCollection 

**Screenshots**

**Version Info**
Windows 10 Pro 1809

NuGet package version: 
Microsoft.Toolkit.Uwp.UI.Controls 5.1.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Windows 10 Pro                       |Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**

[MainPage.xaml.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3041158/MainPage.xaml.zip)

**Comment by jevansaks** [comment]
Thanks for the detailed bug report! We will investigate.
