### ISSUE TITLE
How to Get the MainWindow HWND From Win UI 3 C++ Project

### ISSUE THREAD

**Issue by Extrimis** [microsoft/microsoft-ui-xaml#5230]
I am Creating a Win UI3 C++ application, i would like to get the MainWindow Handle from the Window, How can i achieve it?

**Comment by StephenLPeters** [comment]
I don't think there is a way to get the raw Hwnd... @MikeHillberg @Austin-Lamb or @marb2000 do you know?  @Extrimis why do you need it?

**Comment by Extrimis** [comment]
Actually I would like to call some win32 functions. It was possible in c# version right why is it not possible in c++.

**Comment by codendone** [comment]
The code in #5151 is what you want, just call it with the MainWindow. You can do the `.as<IWindowNative>()` call directly on your MainWindow, or you can get a Window from your MainWindow, such as with `this->try_as<winrt::Microsoft::UI::Xaml::Window>()`.

**Comment by Extrimis** [comment]
Wow That works great. Thank you @codendone.

Here is the code i have used:

``` C++
HWND hwnd;
this->try_as<IWindowNative>()->get_WindowHandle(&hwnd);
//HWND will hold the handle to the window
```
