### ISSUE TITLE
NavigationView in 2.6 has extra margin

### ISSUE THREAD

**Issue by ismaelestalayo** [microsoft/microsoft-ui-xaml#5232]
**Describe the bug**
In the latest WinUI 2.6 pre-release (2.6.0-prerelease.2104300001) There's seems to be a margin between the `NavigationView`'s Pane and the Frame inside of it

**Steps to reproduce the bug**

1. Create a `NavigationView` with a few MenuItems and a Frame like so:
```xaml
<muxc:NavigationView
    x:Name="SettingsNavView" Grid.Row="1"
    IsPaneToggleButtonVisible="False" IsBackButtonVisible="Collapsed"
    IsSettingsVisible="False" IsPaneOpen="True"
    PaneDisplayMode="Left" OpenPaneLength="150"
    Height="550" Width="520">
    <muxc:NavigationView.Resources>
        <SolidColorBrush x:Key="NavigationViewExpandedPaneBackground" Color="#5000ff00"/>
    </muxc:NavigationView.Resources>
    <muxc:NavigationView.MenuItems>
        <muxc:NavigationViewItem Icon="Play" Content="Menu Item1" Tag="SamplePage1" />
        <muxc:NavigationViewItem Icon="Save" Content="Menu Item2" Tag="SamplePage2" />
        <muxc:NavigationViewItem Icon="Refresh" Content="Menu Item3" Tag="SamplePage3" />
        <muxc:NavigationViewItem Icon="Download" Content="Menu Item4" Tag="SamplePage4" />
    </muxc:NavigationView.MenuItems>
    <Frame x:Name="SettingsFrame" Background="#50ff0000">
    </Frame>
</muxc:NavigationView>
```

![image](https://user-images.githubusercontent.com/17100634/122810487-b617ac00-d2cf-11eb-9036-c1573e39c42e.png)

**Expected behavior**
The child Frame should be adyacent to the `NavigationView`'s pane unless a margin is explicitly stated in the code.

**Version Info**

NuGet package version: Microsoft.UI.XAML 2.6.0-prerelease.210430001

_(I manually added 21H1 version 19043 to the table as it was not in the template)_

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by yoshiask** [comment]
I get the same issue with a horizontal top NavigationView. Content margin is always 48 pixels left, 12 pixels top.

**Comment by StephenLPeters** [comment]
@karenbtlai and @ranjeshj FYI

**Comment by karenbtlai** [comment]
The content margin you described has been removed. The fix will happen in the next (pre-)release.

**Comment by ismaelestalayo** [comment]
> The content margin you described has been removed. The fix will happen in the next (pre-)release.

Thanks, good to hear!
I'll close this issue my self 😄
