### ISSUE TITLE
Question: TabView.TabItems.Remove() :: System.ArgumentException

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#5238]
Can you please tell under which circumstances this ex occurs ? 

Just trying to remove one `TabViewItem` from the view. 

![image](https://user-images.githubusercontent.com/43340959/122845737-a070a980-d304-11eb-9cff-6c61d1df98d5.png)

`System.ArgumentException: 'Source object type is not a projected type and does not inherit from a projected type. Arg_ParamName_Name'`

### Exception Details

![image](https://user-images.githubusercontent.com/43340959/122845820-cb5afd80-d304-11eb-9338-301ff8a3bc0d.png)

**Comment by sigmarsson** [comment]
I see a similar exception upon changing tabs : 


![image](https://user-images.githubusercontent.com/43340959/122846663-a10a3f80-d306-11eb-9089-35adc907ee0b.png)

**Comment by ranjeshj** [comment]
@sigmarsson can you provide a repro project ?

**Comment by sigmarsson** [comment]
@ranjeshj , those respective `TabViewItem`s were holding `Page`s that have been [constructed in a custom way](https://github.com/PrismLibrary/Prism/discussions/2496). I changed one `DataTemplate` and this error was gone. So I am leaning into saying that my View--View-Model associations were causing a problem and resulting in this `TabView` related error message.

**Comment by sigmarsson** [comment]
@ranjeshj , I keep encountering this error whenever I navigate to the `Page` below inside a `TabViewItem`

```
<Page
    x:Class="Weather.History.Mvvm.Views.ChartRelayView"
    xmlns:prismmvvm="using:Prism.Mvvm"
    xmlns:prismregion="using:Prism.Regions"
    prismmvvm:ViewModelLocator.AutowireViewModel="True"
    xmlns:inf="using:Weather.History.Prism"
    xmlns:view="using:Weather.History.Mvvm.Views"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">

    <UserControl.Resources>
        <UniformGridLayout x:Key="RelayLayout" MaximumRowsOrColumns="1"/>

        <DataTemplate x:Key="Chart">
            <view:SingleChartView DataContext="{x:Bind}"/>
        </DataTemplate>
    </UserControl.Resources>

    <StackPanel>

        <ItemsRepeater ItemsSource="{x:Bind ViewModel.ContentPresenters}" Layout="{StaticResource RelayLayout}" ItemTemplate="{StaticResource Chart}"/>
    
    </StackPanel>
</Page>
```

**Comment by StephenLPeters** [comment]
I think DataContext is a propagating property, meaning that your SingleChartView will automatically inherit the data context from the parent data template.  The DataTemplate should have its data context set to the data object that it is templating, so you shouldn't need a binding here at all. If you remove the binding are there any issues?

**Comment by sigmarsson** [comment]
No, there aren't, though error message could have been something better.
