### ISSUE TITLE
ContentDialog.ShowAsync() throws ArgumentException

### ISSUE THREAD

**Issue by Baka632** [microsoft/microsoft-ui-xaml#5239]
**Describe the bug**
```
ContentDialog contentDialog = new ContentDialog();
contentDialog.Title = "Hello!";
contentDialog.Content = "Hello from WinUI 3";
contentDialog.PrimaryButtonText = "OK";
await contentDialog.ShowAsync();
```
throws ArgumentException, but it works in UWP.

**Expected behavior**
Should not throw exception, this was working in UWP / WinUI 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/48171809/122907554-dbff8800-d385-11eb-8010-87f49a254667.png)

**Version Info**
NuGet package version: 
WinUI 3 - Project Reunion 0.5: 0.5.7

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |   |
| April 2018 Update (17134)          |   |
| Fall Creators Update (16299)       |  |
| Creators Update (15063)            |   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                | |

**Comment by Marv51** [comment]
From the code you provided it looks like you are not setting the XamlRoot of the ContentDialog. See this [section in the documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-20348#contentdialog-in-appwindow-or-xaml-islands)

**Comment by sylveon** [comment]
You can also set the Xaml root implicitly by declaring your ContentDialog in XAML
