### ISSUE TITLE
Question: .NET UWP XamlParseException error after update Visual Studio 2019 from 16.9.7 to 16.10.2

### ISSUE THREAD

**Issue by vach69** [microsoft/microsoft-ui-xaml#5240]
Hello,
I've updated Visual Studio 2019 from 16.9.7 to 16.10.2 and my solution compiles but at runtime this exception is thrown:

```
Windows.UI.Xaml.Markup.XamlParseException
  HResult=0x802B000A
  Message=Le texte associé à ce code d’erreur est introuvable.

Cannot deserialize XBF metadata type list as 'ToolbarButton' was not found in namespace 'Microsoft.Toolkit.Uwp.UI.Controls.TextToolbarButtons'. [Line: 104 Position: 30]
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

I have no "ToolbarButton" in my solution. I have second machine with the 16.9.4 and it runs perfectly. Is it an issue of Visual Studio or am I doing something wrong?

**Comment by ranjeshj** [comment]
@vach69 Does it work for a new blank app ? If this does not repro for a blank app can you provide a repro app ?

**Comment by vach69** [comment]
I have a minimal repo app. How can i send it to MSFT support team?

**Comment by alwu-msft** [comment]
Hi @vach69, you can zip the repro app and attach it directly to this issue in a comment.
