### ISSUE TITLE
Solution doesn't build - Not compatible errors

### ISSUE THREAD

**Issue by Desbrina** [microsoft/microsoft-ui-xaml#5249]
**Describe the bug**
Solution doesn't build. After creating a new solution and trying to run without any changes get multiple errors

Severity Code Description Project File Line Suppression State Error NU1201 Project Reception is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project Reception supports: net5.0-windows10.0.19041 (.NETCoreApp,Version=v5.0) Reception (Package) C:\Users\Ceri.Turner\OneDrive - David Lloyd Leisure\Documents\Visual Studio\Reception\Reception\Reception (Package)\Reception (Package).wapproj

**Steps to reproduce the bug**
Create a new solution using "Blank App, Packaged (WinUI 3 in Desktop)"
Try and run on the local machine

**Expected behavior**
Expect the project to build and open,

**Screenshots**

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.7] 
[WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)       |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |    |
| Surface Hub       |    |
| IoT                |    |

**Additional context**

**Comment by StephenLPeters** [comment]
@alwu-msft any idea what might be causing this?

**Comment by mqudsi** [comment]
Same problem, but I'm able to build with the default UWP template that uses `0.8.0-preview` but it fails with the above error when upgrading to `0.8.0` (stable).

**Comment by Desbrina** [comment]
I was eventually able to compile, but had to change the minimum and target version.

**Comment by hostar** [comment]
The exact working combination for me was this:
Target: Windows 10, version 2004 (10.0; Build 19041)
Min:     Windows 10, version 1903 (10.0; Build 18362)
