### ISSUE TITLE
NavigationViewItem's AccessKey is no longer triggering the NavigationView's ItemInvoked event

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#5250]
**Describe the bug**
Invoking an access key on a `NavigationViewItem` is no longer triggering the `NavigationView.ItemInvoked` event. It only triggers the `SelectionChanged` event.

**Steps to reproduce the bug**

1. Use the following code:
```xml
<mux:NavigationView PaneDisplayMode="Left" ItemInvoked="NavigationView_ItemInvoked" SelectionChanged="NavigationView_SelectionChanged">
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem AccessKey="A" Content="Item 1" />
        <mux:NavigationViewItem AccessKey="B" Content="Item 2" />
        <mux:NavigationViewItem AccessKey="C" Content="Item 3" />
    </mux:NavigationView.MenuItems>
</mux:NavigationView>
```
2. Add some traces in the `ItemInvoked` and `SelectionChanged` event handlers.
3. Run the application
4. Press *Alt+A*, *Alt+B*, *Alt+C*, to invoke the access keys

**Expected behavior**
The `ItemInvoked` event is raised for each access key.

**Actual behavior**
Only the `SelectionChanged` event is raised.

**Additional context**
There is no issue when using the 2.4.3 package. We get the following expected events' sequence when running this [sample app](https://github.com/microsoft/microsoft-ui-xaml/files/6703277/NavigationViewAndAccessKeyScope.zip)

```
### Invoked Item 1
### selection changed Microsoft.UI.Xaml.Controls.NavigationViewItem
### Invoked Item 2
### selection changed Microsoft.UI.Xaml.Controls.NavigationViewItem
### Invoked Item 3
### selection changed Microsoft.UI.Xaml.Controls.NavigationViewItem
```

Starting with the 2.5.0 package, we are receiving the following events' sequence:
```
### selection changed Microsoft.UI.Xaml.Controls.NavigationViewItem
### selection changed Microsoft.UI.Xaml.Controls.NavigationViewItem
### selection changed Microsoft.UI.Xaml.Controls.NavigationViewItem
```

The `ItemInvoked` event is missing.

**Version Info**
NuGet package version: 
- [Microsoft.UI.Xaml 2.4.3]: No issue with this package
- [Microsoft.UI.Xaml 2.5.0]
- [Microsoft.UI.Xaml 2.6.0-prerelease.210430001]

**Comment by StephenLPeters** [comment]
@ranjeshj and @karenbtlai FYI

**Comment by StephenLPeters** [comment]
@chingucoding have a guess at what change may have caused this regression?

**Comment by chingucoding** [comment]
Didn't we refactor the whole invoke logic some time ago? I think there were other issues we wanted to solve so we changed it but I guess we overlooked access keys.
