### ISSUE TITLE
NavigationView's selection indicator animation looks weird

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#5253]
NavigationView's selection indicator animation looks like it is scaling the indicator vertically, including the portion of the indicator that is rounded by rounded corners, causing the rounding to stretch to a point mid animation which looks pretty bad.

**Comment by StephenLPeters** [comment]
@ranjeshj and @karenbtlai FYI

**Comment by mdtauk** [comment]
You could replace a rectangle with a border if you wish to scale - or animate the height value, instead of a scale transform.

I think there was a similar issue with the ToggleSwitch control's animation too
