### ISSUE TITLE
ItemsRepeater not working properly with CollectionViewSource 

### ISSUE THREAD

**Issue by katan-ms** [microsoft/microsoft-ui-xaml#5256]
**Describe the bug**

When the ItemsSource is set to CollectionViewSource.View in ItemsRepeater, the ItemTemplate is identifying the source as a plain list instead of a grouped list. resulting in ItemsRepeater trying to render plain items as group items and fail.

**Steps to reproduce the bug**

[ItemsRepeaterWithGroupedCollectionViewSource.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6707244/ItemsRepeaterWithGroupedCollectionViewSource.zip)
1. Load project and start debugging
2. Observe that when directly binding to ObservableGroupedCollection, ItemsView can pass IGrouping to ItemTemplate but when binding to CollectionViewSource.View, it cannot.

**Screenshots**

![image](https://user-images.githubusercontent.com/59658471/123222334-22f99480-d4d0-11eb-9f6b-66e29022ff08.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21387)              | Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by ranjeshj** [comment]
ItemsRepeater does not automatically group for you like ListView. You can nest ItemsRepeaters and just bind to the data directly instead of using a CollectionViewSource. More information here - https://docs.microsoft.com/en-us/windows/apps/design/controls/items-repeater#display-grouped-items
