### ISSUE TITLE
Question: [c# textbox keyup - get final key value]

### ISSUE THREAD

**Issue by juliomgm** [microsoft/microsoft-ui-xaml#5257]
How can i get the final value of a key pressed (including numpad) without having to set it key by key (and not the final text inside the textbox)

If i press 'num pad 0' key i will get the number 0 in the textbox, the value i want to get is 0 and not numpad0

If i press 'point' key i will get the a '.' in the textbox, the value i want to get is '.'

`void StackPanel_KeyUp(object sender, KeyRoutedEventArgs e)
{
    statusTextBlock.Text = String.Format(
        "The key {0} was pressed while focus was on {1}",
        e.Key.ToString(), (e.OriginalSource as FrameworkElement).Name);
}`

I just want to know what is the final ascii value of the key on keyup.

thanks.

**Comment by StephenLPeters** [comment]
I think you are looking for [CharacterReceived](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.characterreceived?view=winrt-20348) which has args with a Character property.

**Comment by juliomgm** [comment]
The  CharacterReceived event isn't triggered....

`    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <TextBox x:Name="teste" CharacterReceived="TextBox_CharacterReceived" BeforeTextChanging="teste_BeforeTextChanging"/>
    </StackPanel>`

`        private void TextBox_CharacterReceived(UIElement sender, CharacterReceivedRoutedEventArgs args)
        {
            var receivedchar = args.Character;
        }
        private void teste_BeforeTextChanging(TextBox sender, TextBoxBeforeTextChangingEventArgs args)
        {

        }`

**Comment by StephenLPeters** [comment]
Sounds like something else is handling the event, do you have other UI in your stack panel that might be handling it?
