### ISSUE TITLE
Unreachable code in `AnimatedIcon`

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#5258]
**Describe the bug**

While porting the `AnimatedIcon` source code, I noticed that the `UpdateMirrorTransform()` call cannot be reached by any possible path:

https://github.com/microsoft/microsoft-ui-xaml/blob/ba55e86fab216886a10b0b248c931e11a4e0a64f/dev/AnimatedIcon/AnimatedIcon.cpp#L543-L554

Should it be moved above or removed?

**Steps to reproduce the bug**

See code

**Expected behavior**

Should be reachable.

**Screenshots**

N/A

**Version Info**

`main`

**Comment by chingucoding** [comment]
Looks like dead code to me, a bit surprised the compiler wouldn't mention it. If you are porting it to Uno Platform, did the C# compiler mention this?

**Comment by MartinZikmund** [comment]
@chingucoding yes, I noticed it thanks to IntelliSense underlining it 😀

**Comment by StephenLPeters** [comment]
Wow, our tests missed this too because they only test changing the flow direction, not the initial value... Thank!!

**Comment by StephenLPeters** [comment]
If you want to contribute a fix that'd be awesome! otherwise I'll get to it soon.

**Comment by MartinZikmund** [comment]
@StephenLPeters happy to do it! Just remove the call?
