### ISSUE TITLE
Question: Startup performance

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#5259]
The "WinUI3 Controls Gallery" takes noticeably longer to start than the "XAML Controls Gallery". I'm filing this issue in this repo, because both versions of the app are almost identical. So likely any performance differences are due to the difference in runtime.

I have also noticed the relatively slow startup of WinUI 3 in my own app.

Are others having the same experience?

Considering how much faster dotnet 5 is supposed to be compared to previous versions, I find this rather surprising. Is this the inherent cost of decoupling the runtime from the operating system?

And what is planned to address this? I checked the roadmaps and could not find any performance oriented tasks.

**Comment by omikhailov** [comment]
UWP has .Net Native, .Net 5 – does not, so there is nothing surprising. Here is recent post about AOT from .Net team: https://devblogs.microsoft.com/dotnet/conversation-about-crossgen2/ and it seems like it will be supported in .Net 7 at best.

**Comment by duke7553** [comment]
@Marv51 Also WinUI 3 Desktop apps don't have splash screens, meaning the CoreWindow apps have instant feedback on launch and WinUI 3 desktop apps don't (for now)

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI

**Comment by AathifMahir** [comment]
Hope, NativeAOT support would be added to WinUI 3 Apps as soon as the DotNet 7 Launches. Could make a huge difference in User Experience of the WinUI 3 Apps, Since many of the users were waiting blindly for seconds before the WinUI 3 Apps Opens after Clicking on Specific WinUI 3 Apps
