### ISSUE TITLE
WinUI 2.6 - Light theme flyouts are semi transparent

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#5266]
**Describe the bug**

After upgrading to WinUI 2.6 and using the latest styles, the flyouts (Tooltip and Teachingtip in my case) have semi transparent backgrounds.

**Steps to reproduce the bug**

1. Create object with tooltip or teachingtip
2. Use WinUI 2.6 and open those

**Expected behavior**

**Screenshots**

![Gif of flyouts with transparent backgrounds](https://user-images.githubusercontent.com/16122379/123320286-d6df3c00-d531-11eb-9463-322a55c26092.gif)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19043)              | Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@chingucoding I think we've already fixed this, are you seeing a repro with the latest xaml controls gallery?

**Comment by StephenLPeters** [comment]
sorry, latest mux controls test app.

**Comment by chingucoding** [comment]
Doesn't repro in muxctestapp, closing now as it's fixed.
