### ISSUE TITLE
WinUI 2.6 upgrade- Version 1 styles create faulty/missing hover colors

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#5267]
**Describe the bug**

Some controls no longer seem to have proper hover colors.

**Steps to reproduce the bug**

1. Create controls shown in the gif (NavigationView, Button, GridView).

**Expected behavior**

Hover should be visible to users.

**Screenshots**

![Gif showing missing hover indications](https://user-images.githubusercontent.com/16122379/123321261-09d5ff80-d533-11eb-98da-09e709b89c52.gif)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19043)              | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by karenbtlai** [comment]
@chingucoding Can you provide a repo app? also what OS build are you using. I am able to see the hover colors when using Version1 styles on my machine.

**Comment by chingucoding** [comment]
I was able to repro this with the following PR: https://github.com/chingucoding/UWP-Resources-Gallery/pull/83

OS Version: 19043
