### ISSUE TITLE
WinUI website still lists Windows 10X, not Windows 11

### ISSUE THREAD

**Issue by niels9001** [microsoft/microsoft-ui-xaml#5268]
https://microsoft.github.io/microsoft-ui-xaml/

The main repo website still lists Windows 10X, which is discontinued as we all know. Replacing it with Windows 11 would make sense :).

![image](https://user-images.githubusercontent.com/9866362/123325892-df874080-d538-11eb-819f-1621e86d5241.png)

**Comment by anawishnoff** [comment]
@niels9001 We just pushed an update yesterday, take a look now! :)
