### ISSUE TITLE
WinUI 2.6 - context menu opening animation no longer played

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5272]
In WinUI 2.6, I noticed that the animation for opening the context menu isn't played anymore and it opens plain.

**Comment by mdtauk** [comment]
The CommandBarFlyout was updated to remove the resize animation when it is displayed, if this is what you mean?

**Comment by StephenLPeters** [comment]
There should be a quick opacity animation. Are you seeing that?

**Comment by Jaiganeshkumaran** [comment]
I don't know about MenuFlyout but the default context menu for text controls such as text box doesn't play an animation anymore.

**Comment by StephenLPeters** [comment]
Can you provide more information about your environment? I am seeing a fade in and fade out animation in the XCG on all the OS versions I've tried.  Maybe a gif of what you are seeing as well.

**Comment by StephenLPeters** [comment]
Also, make sure that your Animation Effects setting in the settings app is turned on!

**Comment by Jaiganeshkumaran** [comment]
It's enabled and does show up for most context menus but not in the one for text controls. I'm not able to record it as the screen recorder hides the context menu due to this issue https://github.com/microsoft/WindowsAppSDK/issues/833.

**Comment by StephenLPeters** [comment]
I'm not able to reproduce the issue, can you give us more information about your environment? What app are you seeing it in? do you see the issue in the XamlControlsGallery as well?

**Comment by Jaiganeshkumaran** [comment]
Seems to occur in all apps using CommandBarFlyout, MenuFlyout plays an animation but CommandBarFlyout no longer plays an animation when opened.

**Comment by StephenLPeters** [comment]
Its working for me, so I'm going to need more debugging information.
