### ISSUE TITLE
Question: NavigationView with WinUI 2.6

### ISSUE THREAD

**Issue by Brouilles** [microsoft/microsoft-ui-xaml#5273]
Hi,  
Have you find a way to have the same render than XAML gallery at the top? If I add a margin, it is good. But the back button is not anymore top left aligned.

![](https://cdn.discordapp.com/attachments/671870147354427422/857879710663180332/unknown.png)

![](https://cdn.discordapp.com/attachments/671870147354427422/857879773463314452/unknown.png)

Here my code
```
<winui:NavigationView
            x:Name="navigationView"
            <!--Margin="0,45,0,0"-->
            Canvas.ZIndex="0"
            Grid.Column="1"
            AlwaysShowHeader="False"
            PaneDisplayMode="LeftCompact"
            Header=" "
            IsTabStop="False"
            IsTitleBarAutoPaddingEnabled="False"
            IsBackEnabled="{x:Bind IsBackEnabled, Mode=OneWay}"
            SelectedItem="{x:Bind Selected, Mode=OneWay}"
            ItemInvoked="OnItemInvoked"
            IsSettingsVisible="True"
            PaneOpening="NavigationViewControl_PaneOpened"
            PaneClosing="NavigationViewControl_PaneClosing"
            DisplayModeChanged="NavigationViewControl_DisplayModeChanged">
 ```

**Comment by gabbybilka** [comment]
Hi @Brouilles, I would recommend you check out the sample code here: https://docs.microsoft.com/en-us/windows/apps/design/style/mica#standard-pattern-in-left-navigationview To get the NavigationView back button into the title bar area you will need to [extend into the title bar area](https://docs.microsoft.com/en-us/windows/apps/design/style/mica#title-bar-code-behind) and draw your own custom title bar. 

Here is the Xaml Controls Gallery root page as well if you want to take a look at the live code: https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/Navigation/NavigationRootPage.xaml

**Comment by Brouilles** [comment]
Thanks a lot!
