### ISSUE TITLE
When NavigationView.PaneDisplayMode = "LeftCompact" the animation of indicator in not correct in WinUI2.6

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#5275]
**Describe the bug**
![GIF 2021-6-25 16-27-42](https://user-images.githubusercontent.com/42038175/123395234-8c61cc00-d5d2-11eb-8b9f-df635a3668cb.gif)
You will fount that indicator will be shorter suddenly after about 100ms 

**Steps to reproduce the bug**

1. Upgrade to WinUI 2.6
2. Click the SettingButton in NavigationView

**Expected behavior**
Animation should be completed in one step

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I’m not sure if this animation was designed this way on purpose

**Comment by StephenLPeters** [comment]
Looks like you are using the Version 1 styles (the reveal on your settings button gives it away) if you update to the Version 2 styles do you still notice the issue?

**Comment by Poopooracoocoo** [comment]
lol reveal died??

**Comment by StephenLPeters** [comment]
> lol reveal died??

Reveal exists but is not used by the Version2 styles of the inbox controls.
