### ISSUE TITLE
When CommandBarFlyout open direction is "Top", the origin point is not correct (Miss calculate the height of "PrimaryCommand")

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#5276]
**Describe the bug**
![GIF 2021-6-25 16-36-45](https://user-images.githubusercontent.com/42038175/123396434-e44d0280-d5d3-11eb-8f48-a74adcc27fda.gif)

**Steps to reproduce the bug**

1. Show Commandbarflyout in different direction
2. Find bug

**Expected behavior**
CommandBarFlyout should always show from the point where mouse pressed

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.5.0
Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
Fixing this will be a bit tricky. You'll need to get the secondary popup from the commandbar flyout and attach a handler to it's [ActualPlacementChanged](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.primitives.ipopup4.actualplacementchanged?view=winui-2.6-prerelease) event, to determine if it will open above or below. Then you can call OpenAt and change the Enum value you use to open above...

This seems like something common enough that we should build it in automatically to winui2, but I don't think it is easy to fix.

**Comment by zhuxb711** [comment]
So no solution for WinUI2.5 ?
