### ISSUE TITLE
Flyouts look broken in WinUI 2.6 using light theme

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#5277]
**Describe the bug**

Flyouts (any, from ComboBoxes, AutoSuggestBoxes, MenuFlyouts...) background looks completely broken with light theme

**Steps to reproduce the bug**

1. Open any flyout with light theme

**Expected behavior**

Flyouts have proper contrast when using light theme

**Screenshots**

![image](https://user-images.githubusercontent.com/8152849/123407643-78a36f00-d5ac-11eb-89c7-c83941ff3495.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by FrayxRulez** [comment]
Did some research and I would bet that this code fails to execute: https://github.com/microsoft/microsoft-ui-xaml/blob/0db5d0398cb38d69b06e26ef734cbbdebdebe774/dev/dll/XamlControlsResources.cpp#L163

**Comment by FrayxRulez** [comment]
Or... is it actually caused by this? Is this by design?
https://github.com/microsoft/microsoft-ui-xaml/blob/fc4900a7420f98c69787f5d6de133b6dc32c6379/dev/Materials/Acrylic/AcrylicBrush_19h1_themeresources.xaml#L84

**Comment by ranjeshj** [comment]
Thanks for filing this bug @FrayxRulez . It looks like an issue with the acrylic brush.

**Comment by michaelcoelsch** [comment]
Same problem here.

**Comment by ranjeshj** [comment]
I think this change is likely fixing the root cause. @jevansaks  as FYI
https://github.com/microsoft/microsoft-ui-xaml/commit/069d291452b7341b411ae56728a413499176a792

**Comment by tipa** [comment]
Great to hear this has been taken care of already.
Will we see a hotfix release for this bug? It currently prevents me from upgrading to 2.6

**Comment by michaelcoelsch** [comment]
Thanks @ranjeshj for your investigating and finding the solution
Waiting for a soon hotfix.
It currently prevents me too from upgrading to 2.6

**Comment by FrayxRulez** [comment]
> I think this change is likely fixing the root cause. @jevansaks as FYI
> [069d291](https://github.com/microsoft/microsoft-ui-xaml/commit/069d291452b7341b411ae56728a413499176a792)

Hey @ranjeshj, I just tried the nupkg dropped by the CI and the problem still occurs.

**Comment by FrayxRulez** [comment]
Some further research:
```csharp
flyout.Items[0].Loaded += (s, args) =>
{
    var ciccio = s as MenuFlyoutItem;
    var presenter = ciccio.Ancestors<MenuFlyoutPresenter>().FirstOrDefault();

    var back = presenter.Background as AcrylicBrush;
};
```

Here `back.TintLuminosityOpacity` is equal to `null`, and `BackgroundSource` is `HostBackdrop`, while WinUI style seems to use `AcrylicInAppFillColorDefaultBrush`, that is a `Backdrop` brush...

**Comment by FrayxRulez** [comment]
> > I think this change is likely fixing the root cause. @jevansaks as FYI
> > [069d291](https://github.com/microsoft/microsoft-ui-xaml/commit/069d291452b7341b411ae56728a413499176a792)
> 
> Hey @ranjeshj, I just tried the nupkg dropped by the CI and the problem still occurs.

So, after some further changes on my code everything seems fine, so @jevansaks commit actually fixes this.

**Comment by oduis** [comment]
Hello @FrayxRulez , facing the same problem. May I asked where did you get the preview CI nuget feed?

**Comment by FrayxRulez** [comment]
> Hello @FrayxRulez , facing the same problem. May I asked where did you get the preview CI nuget feed?

A bit tricky to find: https://dev.azure.com/ms/66f07283-7714-4cbf-be8f-73dfb782cfdc/_apis/build/builds/186815/artifacts?artifactName=drop&api-version=6.0&%24format=zip

**Comment by oduis** [comment]
Thanks FrayxRulez! Reference the nuget in the drop file , but since it is not signed correctly it's not really ready for deployment it seems. Guess I'll wait for an official 2.6 hotfix.

**Comment by oduis** [comment]
@ranjeshj , since you said a week ago the hotfix will be out "shortly", do you have a rough estimation when this will be? It's really hindering adoption I think.

**Comment by Poopooracoocoo** [comment]
damn this is one NASTY bug. Why was it released in this state?? oh right... microsoft.
