### ISSUE TITLE
Numberbox w/inline SpinButtons sometimes overlap the clear button

### ISSUE THREAD

**Issue by ismaelestalayo** [microsoft/microsoft-ui-xaml#5278]
**Describe the bug**
I just saw on the **XAML Controls Gallery**'s `GridView` section that the `NumberBox` have the inline `SpinButton` overlapped with the X to clear the input button:

![image](https://user-images.githubusercontent.com/17100634/123434887-422a1c00-d5cd-11eb-8b4b-6fa2c0ec63e2.png)

However this behaviour is not happening `NumberBox` section itself, so it's not a glitch that happens in every scenario.

**Steps to reproduce the bug**

1. Open the XAML Controls Gallery in the  `GridView` section *URL: `xamlcontrolsgallery://item/GridView`*
2. Go to the second example with the three number boxes

**Expected behavior**

The X button to clear the input should not overlap with the `SpinButton`s

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@teaP FYI as well

**Comment by StephenLPeters** [comment]
similar to #5293
