### ISSUE TITLE
WinUI Design Toolkit Bug: [Segoe UI Variable fonts not being recognised in Figma (MacOS) even after local installation]

### ISSUE THREAD

**Issue by yadala1998** [microsoft/microsoft-ui-xaml#5279]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Font Styles

**Describe the bug:**
Although fonts are installed on a Mac, Figma says fonts are missing. Is this happening to anyone else?

-> Regular Small 
-> Semibold Display
-> Semibold Text

These fonts aren't working. Is this an issue with the fonts file?

**Version Info:**
Windows UI release 2.6 - Figma

**Additional context:**
N/A

**Comment by alejo4000** [comment]
Hello! 
Please try these solutions to see if they resolve the issue:

Manage a font as part of an organization: https://help.figma.com/hc/en-us/articles/360039956774
Access local fonts on your computer: https://help.figma.com/hc/en-us/articles/360039956894-Access-local-fonts-on-your-computer

Let us know if that works!

**Comment by yadala1998** [comment]
Can't try the organizations' based solution (Shared Fonts) since our plan is Figma Teams Plan. I have stalled the fonts in my local fonts library. It still doesn't work. I've downloaded the new fonts from https://www.microsoft.com/design/fluent/#/windows. Our other team members on Mac have a similar problem.

**Comment by yadala1998** [comment]
Hi. Just a quick update. This listing - [https://forum.figma.com/t/font-bug/2749] on Figma Forums indicates that Variable Fonts are not supported by Figma. Here is the feature request asking for the addition of Variable Fonts Support in Figma - https://forum.figma.com/t/add-support-for-variable-fonts/325. 

Are these correct? If yes, then is the current Figma Windows UI 2.6 usable on Figma?

**Comment by JohnnyWestlake** [comment]
Would like to confirm the same behaviour on Windows too - Figma just doesn't support variable fonts properly which makes the design toolkit not especially useful right now, unless we can get it in a format for another program.

**Comment by alejo4000** [comment]
We've recently updated the Segoe UI Variable font to include static instances. Could you please try downloading the updated font and installing the static instances and see if those resolve the issue?

https://aka.ms/SegoeUIVariable

**Comment by alejo4000** [comment]
One more suggestion to try, if you're trying the Static Instances with the new download package of Segoe UI Variable, try uninstalling the Variable font version to minimize conflict with Figma.

**Comment by yadala1998** [comment]
Is it possible for you to give the equivalency between the Win UI 2.6 Design System Typesystem and the Static Fonts you have provided here? The names don't match so just want to make sure. And thanks for the update!

**Comment by SpencerHurd** [comment]
Hi yadala1998, can you confirm something for us: is the issue you are seeing that the static instances of font weights (ie: in the type chart in the 'Variable Font' column we have: Small, Text, Display Semibold, etc) do not match what you are seeing in the weight dropdown selector in Figma? Can you tell us what weight names you are seeing in the Figma interface?

**Comment by alejo4000** [comment]
Closing this bug, new update to Fonts provided static instances that should alleviate this problem.
