### ISSUE TITLE
Imporve ItemsWripGrid

### ISSUE THREAD

**Issue by HppZ** [Microsoft/microsoft-ui-xaml#528]
# Proposal:  ItemsWripGrid needs support for different size children

## Summary

I need use different ItemsContainers for different Models, different ItemsContainers have different sizes, their sizes are calculated based on factors like Model properties, Panel‘s size, Window's size or something else.

## Rationale

support this feature makes ItemsWrapGrid more flexible and UWP apps more functional.

**Comment by chrisglein** [comment]
ItemsWrapGrid is only built to be a uniform grid. We have other ideas for layouts to expand our options here to hopefully meet your needs. @micahl can you wrap this into your existing feature requests and make sure it's covered?

**Comment by micahl** [comment]
@HppZ, are there examples of the kind of layout you're targeting?  Is the size of the items independent from all the others (e.g. the main view in the Photos app), or is the expectation that if they change size based on some factors like those you mention that they all change equally (e.g. a grid view of album art that adapts to window resizes)?

**Comment by HppZ** [comment]
1,
Here is my example code:
https://github.com/HppZ/LayoutApp

2,
The Photos app's panel is not one of those panels in UWP API, right?

**Comment by micahl** [comment]
No there isn't a virtualizing panel in UWP that already provides the layout of the Photos app.  Is that the kind of layout you're trying to achieve where each item can be a different size?  Or does the variable item size not matter in your scenario and you're just interested in having the equally sized items be able to stretch to fill the available space for things like window resizing?

**Comment by HppZ** [comment]
Yes, I want each item to have a different size.
just like the layout in my example code: I want show 4 folder items per row & 5 photo items per row, and they are grouped.

**Comment by micahl** [comment]
This may be a lower-level than what you're asking for, but take a look at the new [ItemsRepeater control](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater). We ship two virtualizing layouts with ItemsRepeater that are discussed in that doc.  Both of them are optimized cases of a more general kind of wrapping layout for variable height/width items we call FlowLayout.  

It sounds like that might be what you're after.  We don't currently include it in the official Nuget release.  But, if you want to give it a try it's available to try in the recent prerelease versions of the Nuget package.  Here's a [small sample ](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/TestUI/Samples/FlowLayoutDemoPage.xaml) for it.  If you do try it, please give us feedback.

**Comment by HppZ** [comment]
some screenshots to illustrate what I want to do.
![s1](https://user-images.githubusercontent.com/12285582/57534534-cd56e200-7372-11e9-9e11-ff6e83b7fc11.png)
![s2](https://user-images.githubusercontent.com/12285582/57534535-cdef7880-7372-11e9-9a3e-76f710fcd51e.png)
![s3](https://user-images.githubusercontent.com/12285582/57534536-ce880f00-7372-11e9-87bc-8521d1750752.png)

**Comment by HppZ** [comment]
closed? @micahl
