### ISSUE TITLE
In 100% scaling, WinUI 2.6 NavigationView settings icon is blurry when opened

### ISSUE THREAD

**Issue by roxk** [microsoft/microsoft-ui-xaml#5282]
**Describe the bug**
In 100% scaling, navigation view's settings icon is blurry when it's opened.

**Steps to reproduce the bug**
1. Launch XAML control gallery with WinUI 2.6.
2. Go to navigation view page, click the hamberger menu on the first sample to open it.
3. Observe settings icon is blurry. Other icons are fine.

**Note**: This only happen in opened state. When the navigation view is expanded instead, the settings icon isn't blurry.

**Expected behavior**
The settings icon is not blurry

**Screenshots**
**Closed**
![image](https://user-images.githubusercontent.com/16918354/123446179-33625a00-d60b-11eb-98d3-57b0f6c12515.png)
**Opened**
![image](https://user-images.githubusercontent.com/16918354/123446210-3cebc200-d60b-11eb-96e3-539b5edb8546.png)

**Version Info**
WinUI 2.6

NuGet package version: 
Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 | Yes | 
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
Seems to only be the settings icons in the navigation view in the sample, the root navigation view seems fine to me...

**Comment by StephenLPeters** [comment]
@gegao18 any ideas?

**Comment by roxk** [comment]
@StephenLPeters Did you test it with a large window width? To reproduce this issue, the navigation pane display mode has to be overlay so it can be opened instead of expanded, so testing it when nav view had automagically changed to minimal state is the easiest. I could reproduce the issue with both the root navigation view and the one in the sample.

**Root nav view, minimal, closed**
![image](https://user-images.githubusercontent.com/16918354/123932162-c3b1ed80-d9c3-11eb-85a0-37776fe87174.png)

**Root nav view, minimal, opened**
![image](https://user-images.githubusercontent.com/16918354/123932225-d3313680-d9c3-11eb-84b8-cd9fa892e90e.png)
