### ISSUE TITLE
WinUI 2.6, toggle button in the color picker is using `SystemBaseHighColor` instead of `TextFillColorPrimary`

### ISSUE THREAD

**Issue by roxk** [microsoft/microsoft-ui-xaml#5292]
**Describe the bug**
In WinUI 2.6, some part of color picker is still using `SystemBase*Color`, when all other controls are using `TextFillColor*`. Specifically, the toggle button ("more") is still using `SystemBase*Color`.

**Steps to reproduce the bug**
See the following line:
https://github.com/microsoft/microsoft-ui-xaml/blob/a00cc2b62cacf93f4c370faf354dd0bdb825c415/dev/ColorPicker/ColorPicker.xaml#L370
It is using `SystemBase*Color`, when e.g. `AppBarButton` is using
https://github.com/microsoft/microsoft-ui-xaml/blob/090fd4d11be744473324056d8d00dce797cdda6c/dev/CommonStyles/AppBarButton_themeresources.xaml#L15
I'm not sure if this file is outdated, but since it's not the `_v1` variant, I assume it's the default one resolved in WinUI 2.6. So it seems the toggle button in color picker didn't receive the migration treatment. Not sure if there are other missing parts.

**Expected behavior**
All parts in color picker uses `TextFillColor*`.

**Screenshots**
Using power toy color picker, in XAML control gallery:
**Color picker, toggle button text**
(captured with screenshot of the app, since hovering causes it to enter hover state, changing its color)
![image](https://user-images.githubusercontent.com/16918354/123501739-a6a2b500-d679-11eb-9d93-d6ef09940838.png)
**Color picker RGB text**
![image](https://user-images.githubusercontent.com/16918354/123501785-e9648d00-d679-11eb-9390-3c11ce4b2872.png)

You can see the color of the text "more" is `#000000`, whereas text "R" is `#1A1A1A`.

**Version Info**
WinUI 2.6

NuGet package version: 
Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 21H1 | Yes |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I found this issue while trying to manually add 2.6 styles to my WinUI 3 app. I did a search of `SystemBaseHighColor` in github to see if there are any overrides, found none, but saw color picker using it instead. If this is indeed a bug, it seems a project-wide test in CI that flags any usage of outdated resources could completely eliminate these issues.

**Comment by StephenLPeters** [comment]
Good Catch! thanks for the reprort

**Comment by ranjeshj** [comment]
@roxk would you like to contribute a fix ?
