### ISSUE TITLE
`NumberBox` width with inline buttons overlaps text in Version2 styles

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#5293]
**Describe the bug**

After updating to WinUI 2.6, in all `NumberBox` element without explicit width which have `SpinButtonPlacementMode="Inline"` the buttons now overlap the numeric input. See below for screenshot

**Steps to reproduce the bug**

Create a `NumberBox` with `Inline` spin buttons and no explicit width

**Expected behavior**

Buttons should not overlap

**Screenshots**

![image](https://user-images.githubusercontent.com/1075116/123509884-6db61080-d678-11eb-892a-a77b3b300ed0.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ranjeshj and @teaP FYI
