### ISSUE TITLE
Question: How to completely hide the navigation view footer

### ISSUE THREAD

**Issue by brabebhin** [microsoft/microsoft-ui-xaml#5294]
I am using the navigationview class to replace my old hand made navigation view, and I couldn't help but notice that even if I don't put something in the footer of the navigation view, the UI still reserves some space for the footer.

Is there a way to hide this empty footer space this without going the custom style way?
![image](https://user-images.githubusercontent.com/9284164/123521233-0f138580-d6be-11eb-921e-63ce450a47d0.png)

**Comment by StephenLPeters** [comment]
@karenbtlai or @ojhad FYI

**Comment by karenbtlai** [comment]
If there are no items in the footer, there should be no space underneath. Can you provide more details / code to your app?

**Comment by chingucoding** [comment]
FWIW, I wasn't able to repro this inside the MUXControlsTestApp.

**Comment by brabebhin** [comment]
Interesting. I wasn't able to reproduce it either, seems to be related to my version of the nuget package.
