### ISSUE TITLE
InkToolbarCustomToggleButton in 2.6 does not show if it is checked

### ISSUE THREAD

**Issue by TheJoeFin** [microsoft/microsoft-ui-xaml#5296]
**Describe the bug**

**Steps to reproduce the bug**

Add a InkToolbarCustomToggleButton to an InkToolbar. 
Run app
Click on the InkToolbarCustomToggleButton
Expect to see an underline under the button signifying it has been checked.

**Expected behavior**
I expect to see an underline under the InkToolbarCustomToggleButton which has been activated. 

**Screenshots**

The image below is WinUI 2.6 after clicking on the "Touch/Cursor" InkToolbarCustomToggleButton: Which is the 7th icon from the right
![image](https://user-images.githubusercontent.com/7809853/123531222-75050a80-d6c8-11eb-8c56-3dca62d393b3.png)

The image below is WinUI 2.6.0-prerelease.210315002 after clicking on the "Touch/Cursor" InkToolbarCustomToggleButton
![image](https://user-images.githubusercontent.com/7809853/123531256-bbf30000-d6c8-11eb-8112-e5f39ae25c96.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 Update (19043.1081)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by beervoley** [comment]
@TheJoeFin just trying to fully understand it: you mean that it works as expected in WinUI 2.6.0-prerelease.210315002 but not in WinUI 2.6?

**Comment by TheJoeFin** [comment]
@beervoley 

> you mean that it works as expected in WinUI 2.6.0-prerelease.210315002 but not in WinUI 2.6?
Yes, the prerelease works well for me. I don't have any custom styles on the touch/cursor icon. 

I was using the latest resources when I discovered this bug.

**Comment by beervoley** [comment]
@TheJoeFin got it, thanks!
