### ISSUE TITLE
Using MUX in WPF app -- The expression "[System.Version]::Parse('')" cannot be evaluated

### ISSUE THREAD

**Issue by lymims** [microsoft/microsoft-ui-xaml#530]
**Describe the bug**
Cannot install this package with NuGet.

**Steps to reproduce the bug**
1. Create a new WPF project.
2. Install Microsoft.UI.Xaml with NuGet Package manager
3. Got an error:
    > The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  D:\Path_To_Project\packages\Microsoft.UI.Xaml.2.0.181018004\build\Microsoft.UI.Xaml.props

**Screenshots**
![image](https://user-images.githubusercontent.com/9443706/55621308-b7805b00-57cf-11e9-8aa3-c5ae5c1f9bec.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.0.181018004]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        | Yes   |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@lymims is this still a problem? Did you mean to close this issue?

**Comment by lymims** [comment]
> @lymims is this still a problem? Did you mean to close this 

I think it is because I'm trying to add an UWP package to a WPF project.
When i do this in a UWP project, everything is ok.
thank you for your reply.

**Comment by jevansaks** [comment]
Yes, this is known to be a problem for unpackaged apps. If you use [desktop app packaging (called "Desktop Bridge")](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root) then this works better. There's still some issues that @rbrid is looking into.
