### ISSUE TITLE
Dialog background overlay issue on Windows 10

### ISSUE THREAD

**Issue by matheus-inacio** [microsoft/microsoft-ui-xaml#5301]
The background overlay on the new content dialog (WinUI 2.6) has rounded corners, resulting in a weird effect, since Windows 10 does not have rounded windows.

```xaml
<Grid x:Name="LayoutRoot" contract7Present:CornerRadius="{ThemeResource OverlayCornerRadius}">
    <Rectangle x:Name="SmokeLayerBackground" Fill="{ThemeResource ContentDialogSmokeFill}" />
```
https://github.com/microsoft/microsoft-ui-xaml/blob/9052972906c8a0a1b6cb5d5c61b27d6d27cd7f11/dev/CommonStyles/ContentDialog_themeresources.xaml#L209

My suggestion is to remove `OverlayCornerRadius` from the `LayoutRoot`, because that way the overlay will fill the entire window independently if it has rounded corners.

![image](https://user-images.githubusercontent.com/29243277/123553273-a1fd0000-d750-11eb-8af0-b37e7b92dfe7.png)

### The corner on Windows 10:

![image](https://user-images.githubusercontent.com/29243277/123553295-b7722a00-d750-11eb-8a8f-a33838bc6098.png)

**Comment by StephenLPeters** [comment]
Good Catch!!

**Comment by StephenLPeters** [comment]
Sounds like you understand the problem, want to help us out with a pr for the fix? :D
