### ISSUE TITLE
Slider thumb appears blurry in WinUI 2.6

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#5303]
**Describe the bug**

Slider thumb appears quite blurry in WinUI 2.6, especially on pointer over state.
On my laptop I'm using 125% display scaling, and I believe this is the cause for this glitch.
I guess that it would be enough to set `UseLayoutRounding` to `False` on it?

**Screenshots**

![image](https://user-images.githubusercontent.com/8152849/123682639-875b8180-d84b-11eb-9d69-ae521a901776.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
This issue is doesn't repro at most scale factors but is present at 125%  Additionally the slider thumb isn't centered at this scale factor.  Its a pixel snapping issue and is pretty difficult to fix... We could try UseLayoutRounding false and see if it looks a bit better but a proper solution is difficult.

**Comment by FrayxRulez** [comment]
UseLayoutRounding usually does the trick. I can try here and ping you back with a screenshot of the result!
