### ISSUE TITLE
ListViewItem selected state looks broken

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#5304]
**Describe the bug**

ListViewItem selected pointer over state looks quite broken on WinUI 2.6, on 21H1.

**Steps to reproduce the bug**

1. Select a ListViewItem.
2. Move the mouse in and out of it.

**Screenshots**

https://user-images.githubusercontent.com/8152849/123685729-49605c80-d84f-11eb-9ff5-a3c6f5bad04b.mp4

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@ranjeshj this is close to maybe wanting to cherry pick into 2.6 thoughts?

@marksfoster do you know the intended behavior? is the selected rest state supposed to be accent color or the selected pointer over state supposed to be a grey?

**Comment by lhak** [comment]
Please also change the way selected items (without pointer over) are presented. The selected state is barely visible (low contrast).

**Comment by ranjeshj** [comment]
@beervoley closing this since the change is merged.

**Comment by lmadhavan** [comment]
Will this be hotfixed to 2.6?

**Comment by StephenLPeters** [comment]
Yes.
