### ISSUE TITLE
NavigationView's back button does not respect Fitt's Law

### ISSUE THREAD

**Issue by sylveon** [microsoft/microsoft-ui-xaml#5306]
**Describe the bug**
When a window using the new WinUI navigation view style is maximized, the back button does not work when the mouse is at the complete top left of the monitor. This violates [Fitt's Law](https://en.wikipedia.org/wiki/Fitts's_law) and makes clicking on this button a much more effortful operation.

**Steps to reproduce the bug**
1. Maximize the XAML Controls Gallery window
2. Navigate to any page
3. Move your mouse to the complete top left of the monitor
4. Click.

**Expected behavior**
The back button should trigger and you should go back to the home page

**Screenshots**
![image](https://user-images.githubusercontent.com/6440374/123705295-c4684980-d834-11eb-80b0-66007149ea96.png)

**Version Info**

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000)              | Yes   |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
According to Fitt's law, the time required to rapidly move to a target area is a function of the ratio between the distance to the target and the width of the target. With the current style, the target has a very small width in both X and Y. However, when it works at the complete edge, the width is technically infinite since no matter how much you'll move your mouse you'll hit the target. This can be observed with the start and close buttons: those work when the mouse is at the extreme corner of the monitor and are therefore much easier to hit with a mouse, when the WinUI back button does not and is harder to hit correctly with a mouse:

![image](https://user-images.githubusercontent.com/6440374/123706010-b4049e80-d835-11eb-9ce3-e4ecfb717f2e.png)

**Comment by StephenLPeters** [comment]
Good suggestion! I'm not sure this is doable from winui, but we should look into it.  @ranjeshj @YuliKl FYI

**Comment by gabrielconl** [comment]
AppBarButtons inside CommandBar extend to the edge, but they have an inner margin and appear to be smaller. NavigationView could do the same thing to solve the issue.

**Comment by sylveon** [comment]
I believe it should be doable, since the NavigationView in WinUI 2.5 didn't expose this issue and correctly worked at the complete edge of the monitor. @gabrielconl's suggestion is what I think a solution would look like

**Comment by ranjeshj** [comment]
Thanks for the feedback. Inset backplates are a core part of the design and not something we are planning to update at this time.

**Comment by sylveon** [comment]
There is no need to remove inset backplates to resolve this issue. For example the Windows 11 start button uses inset backplates but can still be activated when the mouse is in the complete bottom left of the screen.

As it stands, WinUI 2.6 is a major regression in UX for me. It makes it much more frustrating to use a NavigationView with a mouse. So much that I might take it out of my programs.

**Comment by michael-hawker** [comment]
> Thanks for the feedback. Inset backplates are a core part of the design and not something we are planning to update at this time.

This isn't a design concern, this is a functional/UX/usability/accessibility concern. This is a regression in usability. It took a long time to get this type of problem fixed with the Start Menu in the first place, let's not forget what we've learned in the past from that.

_The design can still look the same_, but the **hit target** for the button it represents should just extend to the edge of the area, so that if the user misses it or slams their mouse to the top-left corner (which is easier) that the button can still be activated.

If Inset Backplates are going to be used everywhere, this type of accessibility/functional ramification of that change should have been discussed?

**Comment by JustinXinLiu** [comment]
Actually, this is something we could fairly easily fix without affecting the inset backplate. In other words, the design won't be changed at all, but the interaction area take up the entire space.

We first need to increase the size of the back button to like, `48px`. Then we need to create another `Border` inside its template, set its `Background` to `Transparent` so it can receive pointer events, and then give its current root element a `Margin` that's basically half of the _new size - old size_.

**Comment by mrlacey** [comment]
> This isn't a design concern, this is a functional/UX/usability/accessibility concern. This is a regression in usability. It took a long time to get this type of problem fixed with the Start Menu in the first place, let's not forget what we've learned in the past from that.

Given that the Windows 11 taskbar has moved the start button from the corner, I'm not convinced about the strength of this argument.
At an OS UI design level, it has been decided that the ease of accessing a common task by locating it in the corner of the screen isn't important so it might be good to ask them why then change and then see if the same logic still applies for the NavigationView back button.

**Comment by sylveon** [comment]
Even when the taskbar is centered, the start button and other buttons works from the complete bottom edge even if the hover visual doesn't cover this region. NavigationView's menu items do not work from the complete left edge of the screen however.

There are still many parts of the OS quickly accessible via a corner in 11: system UWP back button (top left), window close button (top right) and show desktop button (bottom right). The last one even got a fix this last insider update to make it work when the mouse is at the complete edge of the screen.

FWIW returning the taskbar to being left aligned is the first thing I did after installing the insider builds because of issues like these.

**Comment by winston-de** [comment]
I know I'm a bit late, but I think this same issue exists in other areas in winui 2.6 as well, not just the back button.
For example, in winui 2.5, users could move throw the cursor the the far left side of the screen, then move up and down to select and invoke an item.  However, in winui 2.6, this is no longer possible as there's a 4px margin from the left side. This makes quickly selecting an item in the navigation view much harder, especially when the navigation view is in compact mode and the target size is significantly reduced.

**Comment by StephenLPeters** [comment]
I think keeping the same visual size but increasing the hit target size makes sense.

**Comment by StephenLPeters** [comment]
@chigy FYI

**Comment by mdtauk** [comment]
> I think keeping the same visual size but increasing the hit target size makes sense.

This should probably apply to all controls which have padding between the visual backplates used by adjacent buttons or controls

**Comment by gabrielconl** [comment]
Would this change also include context menus? Because then it could be a good opportunity to use some of the common resources suggested in #4594.

Basically, all context menus (CommandBarFlyout, MenuFlyout, ComboBox flyout etc.) would use the same common resources for margins. I assume that in most cases you would want to have the menus be consistent with each other.
Because of current limitations, this change would mean that the old resources for the menus would need to be deprecated.

Otherwise, there would need to be new resources for the inner/outer margin of each menu.

**Comment by sylveon** [comment]
This is still a problem with the latest WinUI 3 gallery & NavigationView.

**Comment by sylveon** [comment]
This is still a problem, 3 years later in WinUI 3. Can we get @karkarl or someone else to triage this?
