### ISSUE TITLE
WinUI3 not running on Windows 11 insider build (combase.pdb + combase.dll error)

### ISSUE THREAD

**Issue by johot** [microsoft/microsoft-ui-xaml#5313]
**Describe the bug**
When trying to launch a blank WinUI3 project the following error message is displayed

![image](https://user-images.githubusercontent.com/17697920/123758500-469d5000-d8bf-11eb-8fbf-d91eab56dd90.png)

This did work before installing Windows 11 insider build.

**Steps to reproduce the bug**
1. Use Windows 11 Home (Insider) version 22000.51
2. Create blank WinUI3 project
3. Run

**Expected behavior**
It runs preferably showing the new Win 11 styling ;)

**Screenshots**
Se above

**Version Info**
Project Reunion 0.8 VSIX

| Windows 11 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.51)              | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |

**Comment by martibravo** [comment]
It's happening to me too! I created an app (Blank, Packaged, WinUI 3 on Desktop) through Windows Template Studio and it crashes on launch with the same exception. 0xC0000602

**Comment by itsme-alan** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/998

**Comment by BenJKuhn** [comment]
We'll track this against the Windows AppSDK issue https://github.com/microsoft/WindowsAppSDK/issues/998. WinUI team, please go ahead and resolve this one.
