### ISSUE TITLE
Unable to execute Unit Tests in Release mode (.NET Native) with WinUI 2.6.0 (again)

### ISSUE THREAD

**Issue by ChristopheLav** [microsoft/microsoft-ui-xaml#5318]
**Describe the bug**

When I execute the unit tests project in Visual Studio (F5 or with the Tests Explorer), a fatal failure occurs at startup. I encounter the same issue with VSTest in my Azure DevOps pipelines. 

This prevent me to upgrade to WinUI 2.6.0 recently released with the new UI styles.

**Steps to reproduce the bug**

1. Open the repro project
2. Select 'Release' configuration and 'x64' platform
3. Make sure .NET Native tool chain is enabled in project settings
4. Select the tests project as the startup project in the list
5. Click on "Start on local machine" or "Run" in Tests Explorer
6. See the application crash or the 'Tests' output to see the error.

[UTReproUWPApp-WinUI2.6.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6735953/UTReproUWPApp-WinUI2.6.zip)

StrackTrace:

```
   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32 hr, RuntimeTypeHandle typeHnd) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Interop\src\Shared\McgMarshal.cs:line 1189
   at __Interop.ComCallHelpers.Call(__ComObject __this, RuntimeTypeHandle __typeHnd, Int32 __targetIndex, IntPtr arg0, Void* arg1, Void* arg2)
   at __Interop.ForwardComStubs.Stub_5[TThis](__ComObject __this, IntPtr baseInterface, IntPtr& innerInterface, Int32 __targetIndex)
   at Windows.UI.Xaml.Application.__Factory_Windows_UI_Xaml__IApplicationFactory_CreateInstance(String typeName)
   at Windows.UI.Xaml.Application..ctor()
   at UTReproUWPApp.App..ctor() in D:\Demo\UTReproUWPApp\UTReproUWPApp\App.xaml.cs:line 29
   at UnitTestProject1.UnitTestProject1_XamlTypeInfo.XamlTypeInfoProvider.get_OtherProviders() in D:\Demo\UTReproUWPApp\UnitTestProject1\obj\x64\Release\XamlTypeInfo.g.cs:line 462
   at UnitTestProject1.UnitTestProject1_XamlTypeInfo.XamlTypeInfoProvider.CheckOtherMetadataProvidersForName(String typeName) in D:\Demo\UTReproUWPApp\UnitTestProject1\obj\x64\Release\XamlTypeInfo.g.cs:line 476
   at UnitTestProject1.UnitTestProject1_XamlTypeInfo.XamlTypeInfoProvider.GetXamlTypeByName(String typeName) in D:\Demo\UTReproUWPApp\UnitTestProject1\obj\x64\Release\XamlTypeInfo.g.cs:line 172
   at UnitTestProject1.App.GetXamlType(String fullName) in D:\Demo\UTReproUWPApp\UnitTestProject1\obj\x64\Release\XamlTypeInfo.g.cs:line 49
   at __Interop.ReverseComStubs.Stub_6[TResult](Object __this, HSTRING unsafe_fullName, Void** unsafe_result__retval, IntPtr __methodPtr)
```

In the minidump, there is a more precise error (`SpectrumBrush` related?):

![image](https://user-images.githubusercontent.com/19799037/123856152-bd9e0d00-d8ee-11eb-95c3-4d60a81cb832.png)

This error is very similar to that one #2516 I have previously reported (few versions back). The repro project (on this issue) include the fix indicates in the comments. With or without, same issue.

**Expected behavior**

The unit tests need to run successfully :)

**Screenshots**

N/A

**Version Info**

NuGet package version: [Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000)              | Yes (on the previous Insider build too)   |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

No workaround found at the moment. Haye you an idea?

Thank you!

**Comment by StephenLPeters** [comment]
@kmahone You looked at the similar issue last time.  @RealTommyKlein FYI as well.

**Comment by StephenLPeters** [comment]
@ChristopheLav does the same work around for 
        <RevealBorderBrush x:Key="myrevealbrush" xmlns="using:Microsoft.UI.Xaml.Media" />

work with SpectrumBrush?

**Comment by ChristopheLav** [comment]
@StephenLPeters nope, does not work with 2.6.0 (2.4.x + 2.5 releases yes). 

This error seems more precise because related to `SpectrumBrush` (last time, related to whole `XamlControlsResources`) with the same stack (UseCompactResources). I made a search into the repo related to the brush but I found nothing that can help me.

**Comment by StephenLPeters** [comment]
@jevansaks FYI

**Comment by ChristopheLav** [comment]
To unblock me, I refactored my unit tests project to remove the WinUI dependencies. 

The issue remain.

**Comment by kmahone** [comment]
The issue here is that the unittest project is generating an IXMP that includes this code:

```
        private List<IXamlMetadataProvider> OtherProviders
        {
            get
            {
                if(_otherProviders == null)
                {
                    var otherProviders = new List<IXamlMetadataProvider>();
                    IXamlMetadataProvider provider;
                    provider = new Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider() as IXamlMetadataProvider;
                    otherProviders.Add(provider); 
                    provider = new global::UTReproUWPApp.App() as IXamlMetadataProvider;
                    otherProviders.Add(provider); 
                    provider = new UTReproUWPApp.UTReproUWPApp_XamlTypeInfo.XamlMetaDataProvider() as IXamlMetadataProvider;
                    otherProviders.Add(provider); 
                    _otherProviders = otherProviders;
                }
                return _otherProviders;
            }
        }
```

This is the problematic line:
```
provider = new global::UTReproUWPApp.App() as IXamlMetadataProvider;
```

This attempts to create an instance of the main App. But the UnitTest project's App is already running. Only one 'App' instance can be active in a process at a time. 

OtherProviders will get called into anytime we try to activate a xaml type that the UnitTest project does not directly use.

**Comment by kmahone** [comment]
Since this is a bug in the Xaml Compiler we will not be able to fix it in the WinUI nupkg.

@RealTommyKlein shared this workaround:

In UnitTestProject1.csproj, add these properties:
```
<!-- 
    New properties:
    EnableTypeInfoReflection=false: forces Debug builds to use erroneous codegen as well
    XamlCodeGenerationControlFlags=DoNotGenerateOtherProviders: disables default OtherProviders codegen, developers must add the metadata providers individually
-->
 <PropertyGroup>
    <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
    <XamlCodeGenerationControlFlags>DoNotGenerateOtherProviders</XamlCodeGenerationControlFlags>
  </PropertyGroup>
```


In UnitTestProject1’s App’s constructor, manually add all the providers which were present in OtherProviders in XamlTypeInfo.g.cs except for the erroneous application:
```
// Add the providers normally instantiated by the OtherProviders field in XamlTypeInfo.g.cs, except for the erroneously added application type
AddOtherProvider(new global::Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider());
AddOtherProvider(new global::UTReproUWPApp.UTReproUWPApp_XamlTypeInfo.XamlMetaDataProvider());
```
This workaround should unblock this scenario.

Since we are not able to address this bug in the WinUI nupkg, I am closing out this Issue.
