### ISSUE TITLE
Question: WinUI 2.6: How to override new Design Colors

### ISSUE THREAD

**Issue by Shad0wlife** [microsoft/microsoft-ui-xaml#5326]
On WinUI 2.5, the Selection indicator and the RadioButtons Ring of the selected Option were colored as SystemAccentColor.
(This Probably applies in many other places but those are the ones affecting me currently.)

This behaviour changed with the design changes in 2.6. This raises the question:
How do I globally override values like
AccentFillColorDefaultBrush (which seems to affect the RadioButtons via its themeresource file)?

I tried just using a new Dictionary Entry in one of my Merged Dictionaries (which gets referenced after the WinUI design part in the App.xaml file), but that does not work. 

I did replace both
- AccentFillColorDefaultBrush
- SystemControlHighlightAccentBrush (because that is used for the same resource in the [...]themeresource_v1.xaml files)
but only the indicators in the NavView changed to the right color, the RadioButton rings did not.

When overriding AccentFillColorDefaultBrush in the page resources, the expected result (new color) appears.

Did I miss something?

**Comment by StephenLPeters** [comment]
Hello, can you please try overriding this resources within a dictionary placed inside of XamlControlsResource.MergedDictionaries as described here? https://github.com/microsoft/microsoft-ui-xaml/blob/main/build/NuSpecs/readme.txt

Resource overrides are unfortunately pretty difficult to get right, however looking at the code I think this should work.

**Comment by Shad0wlife** [comment]
That works, thank you!
I had missed that the App dictionary setup was changed at some point.
