### ISSUE TITLE
Question: [WinUI 3 is a release?]

### ISSUE THREAD

**Issue by madakr333** [microsoft/microsoft-ui-xaml#5333]
I just want to ask how can WinUI 3 be released if it doesn't even have XAML Designer support? Hot reloads are not working as well, so that means I have to run a project after each change, which take ~1 minute. I lost a lot of production time because of it. Maybe you should do more tests or add some warnings before making people sure that WinUI 3 can be used in production?

**Comment by Symbai** [comment]
> WinUI 3 can be used in production

Who said that? Its still a preview version. Hot reload is something they are working on. Designer as far as I know is not available before release at the end of this year.
