### ISSUE TITLE
NumberBox do not generate Tapped event at Minimum value

### ISSUE THREAD

**Issue by KBaluh** [microsoft/microsoft-ui-xaml#5336]
**Describe the bug**
NumberBox do not generate `Tapped` event when if you reach minimum value.
I want to do some logic for minimum value, but I can't because event did not raised.

**Steps to reproduce the bug**
```xaml
xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
```

```xaml
<muxc:NumberBox Header="" Margin="2" Minimum="1" SpinButtonPlacementMode="Inline"
				HorizontalAlignment="Stretch" VerticalAlignment="Center" 
				Tapped="NumberBox_Tapped">
</muxc:NumberBox>
```

1. Add NumberBox with example code
2. Type into field value 2
3. Click on down button to value 1

**Expected behavior**
When you reach value 1 `Tapped` event generated as when increase or decrease value, even if this value is equal to `Minimum` value

**Actual behavior**
Didn't raise event `Tapped` for value 1, because value 1 is `Minimum`. It's also work with value 0.

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@SavoySchuler and @teaP this feels like a bug to me but maybe it was by design.  Thoughts?
