### ISSUE TITLE
Changing window size and window title

### ISSUE THREAD

**Issue by Desbrina** [microsoft/microsoft-ui-xaml#5337]
I'm using the default window that comes with the project reunion packaged template and i've got a couple of questions

How do i change the window size? With a page i can set it in the xaml but that doesn't seem to work with a window
How to i change the window title? At the moment it shows "WinUI Desktop"

**Comment by Symbai** [comment]
Use search function, this is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/2731 and https://github.com/microsoft/microsoft-ui-xaml/issues/3689

**Comment by StephenLPeters** [comment]
@Desbrina do the issues symbai pointed to answer your questions?

**Comment by Desbrina** [comment]
yeah, that sorted it
