### ISSUE TITLE
WinUI Design Toolkit Idea: more examples and spaceing 

### ISSUE THREAD

**Issue by UIenhancement** [microsoft/microsoft-ui-xaml#5338]
it would be great to have Some app screen examle! 

the WinUI Design Toolkit gives you all the ingredients to design a good software however without a recipe could be hard to achieve a great software. 

- Expand spacing guidance ( best practices, how to make a good hierarchy ) (https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/geometry)
- some examples that provide more insight ( pages with organisms - cards, table ecc. ) ( this will also help to understand how to use all the components )

**Comment by mdtauk** [comment]
Please can you provide Margins, example app layouts, with redlines and metrics called out

**Comment by StephenLPeters** [comment]
@alejo4000 FYI

**Comment by alejo4000** [comment]
Thanks for this great suggestion. As the toolkit evolves, we're always looking for ways to improve and grow!
