### ISSUE TITLE
Performance problem occurs when opening the popup in DatePicker control in WinUI Desktop application

### ISSUE THREAD

**Issue by Subashini2129** [microsoft/microsoft-ui-xaml#5339]
**Describe the bug**
Performance problem occurs when opening the popup in DatePicker control in WinUI Desktop application

**Code snippet**

**XAML:**

`<DatePicker CalendarIdentifier="JulianCalendar" 
                    DayFormat="{}{day.integer} ({dayofweek.abbreviated})"
                    MonthFormat="{}{month.abbreviated}" 
                    YearFormat="{}{year.full}" />`

**C#:**

`ApplicationLanguages.PrimaryLanguageOverride = "bs";`

**Steps to reproduce the bug**
1. Create sample using above code.
2. Then run the application.
2. Open the popup using mouse click.
3. Note it took time when opening the popup in DatePicker control. 

**Expected behavior**
Performance problem should not occur when opening the popup in DatePicker control in WinUI Desktop application.

**Version Info**
NuGet package version:
Microsoft.ProjectReunion(0.5.7)

**Additional context**
**Performance problem does not occur when opening popup in DatePicker control in WINUI UWP application.**

**Comment by Subashini2129** [comment]
Hi Team, 

Any update on this?

**Comment by akilarajesh1313** [comment]
@Subashini2129 Not yet but our teams are currently investigating, thank you for your patience!

**Comment by lakoliu** [comment]
I also have this issue. There is a very noticeable pause between clicking the DatePicker (or TimePIcker) button and seeing the popup.
