### ISSUE TITLE
Navigation view pane background can appear transparent after resizing window while pane is in overlay state

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#5342]
**Describe the bug**

When the muxc navigation view is open in minimal or compact mode, changing the size of the window then back again will cause  the background to appear transparent.

**Steps to reproduce the bug**

1. Open latest version of Xaml Controls Gallery
2. Shrink window until the nav view goes into minimal state
3. Open the pane
4. maximize, then restore the window to it's previous size
5. Navigation view pane background is transparent, and the content displays wrong as well

**Expected behavior**

The background should remain opaque. 

**Screenshots**

https://user-images.githubusercontent.com/59544401/124203343-5b314200-da91-11eb-8ddb-ef09ad5699d6.mp4

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.51)              | yes    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ranjeshj** [comment]
@karenbtlai as FYI

**Comment by matheus-inacio** [comment]
@ranjeshj @karenbtlai It seem that #5431 did not solve this issue.

At least in my local up to date repository and the issue persist.

Maybe this issue should be reopened.

**Comment by matheus-inacio** [comment]
In the issue #5474 there's more details on how to reproduce this issue.

**Comment by karenbtlai** [comment]
@matheus-inacio you're right - I can more consistently repro in xaml-controls-gallery in minimal mode. I'll re-open the bug.
