### ISSUE TITLE
CommandBar Flyout crashes the app on Server 2019, with WinUI 2.6

### ISSUE THREAD

**Issue by driver1998** [microsoft/microsoft-ui-xaml#5344]
**Describe the bug**

CommandBar Flyout crashes the app when opened.

**Steps to reproduce the bug**
Run the XAML Control Gallery app in RS5, and right click on the search bar.

**Expected behavior**
CommandBar Flyout show show up as expected.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes  |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by MCdawanjia** [comment]
老哥，这个驱动有时无法正常在树莓派3B中使用啊！希望可以改进下

**Comment by driver1998** [comment]
> 老哥，这个驱动有时无法正常在树莓派3B中使用啊！希望可以改进下

wrong issue?

**Comment by driver1998** [comment]
I no longer have machines with Server 2019 to validate, feel free to close this issue.
