### ISSUE TITLE
Scrolling down a collection of nested ItemsRepeater with UniformGridLayout as inner layout causes layout cycle hang

### ISSUE THREAD

**Issue by micahl** [microsoft/microsoft-ui-xaml#535]
**Describe the bug**

See title

**Steps to reproduce the bug**

1. Build and run the attached repro.  It's using nested repeaters.  The outer is using a StackLayout and the inner for the items uses a UniformGridLayout.
2. Scroll down a few pages.  The app will seem to hang.

[App10.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3049946/App10.zip)

**Expected behavior**

No hangs

**Version Info**

NuGet package version: 

Latest Microsoft.UI.Xaml

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)   | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Comment by ranjeshj** [comment]
This seems to be a bug caused by ownership of the first element in uniform grid and sharing of the template. We get into a situation in some cases where two repeaters are just stealing recycled elements between each other and constantly invalidate measure because of that.
