### ISSUE TITLE
Listview issues

### ISSUE THREAD

**Issue by TyJOrtiz** [microsoft/microsoft-ui-xaml#5355]
**Describe the bug**
virtualization issues causing items to appear repeated or have wrong data in a listview

**Steps to reproduce the bug**

1. create a listview
2. bind to source
3. items repeat or show wrong data when scrolling

**Expected behavior**
Normal virtualization showing non repeated items

**Screenshots**
before scrolling:
![image](https://user-images.githubusercontent.com/25320332/124371287-1ba35b00-dc35-11eb-85de-807f83623dcd.png)

after scrolling:
![image](https://user-images.githubusercontent.com/25320332/124371274-062e3100-dc35-11eb-863e-9a3dc05b304b.png)

**Version Info**

NuGet package version: 

WinUI 2.6

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

Windows 11 Insider Preview

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by TyJOrtiz** [comment]
Never mind it was an x:phase issue

**Comment by ranjeshj** [comment]
@TyJOrtiz looks like you have identified the issue, so closing this bug.
