### ISSUE TITLE
WinUI 2.6 NavigationView adds corner radius to top left corner of content

### ISSUE THREAD

**Issue by yoshiask** [microsoft/microsoft-ui-xaml#5358]
**Describe the bug**
The content inside a NavigationView has an added corner radius on the top left corner, along with a 1px border along the top. Explicitly setting `CornerRadius="0"` on all elements has no effect. The bug is observed regardless of the display mode of the NavigationView, though `LeftMinimal` seems to have slightly different but still unexpected results.

**Steps to reproduce the bug**
1. Place the following XAML as the content of a page:
```xaml
<muxc:NavigationView>
    <muxc:NavigationView.Content>
        <Border Background="{ThemeResource SystemAccentColorDark1}"/>
    </muxc:NavigationView.Content>
</muxc:NavigationView>
```
2. Run the project.
3. Observe the behavior described and shown in the screenshots.

**Expected behavior**
The NavigationView content should be displayed as-is.

**Screenshots**
`PaneDisplayMode="Left"`
![image](https://user-images.githubusercontent.com/7549325/124391279-7086b600-dcb5-11eb-9423-6e0b2986f40d.png)

`PaneDisplayMode="LeftMinimal"`
![image](https://user-images.githubusercontent.com/7549325/124391595-f35c4080-dcb6-11eb-93db-7b1b914f05f0.png)
![image](https://user-images.githubusercontent.com/7549325/124391601-f820f480-dcb6-11eb-8cbe-e4b10bccbf31.png)

`PaneDisplayMode="Top"`
![image](https://user-images.githubusercontent.com/7549325/124391614-04a54d00-dcb7-11eb-91aa-69840dec55b4.png)

**Version Info**

NuGet package version:
Microsoft.UI.Xaml 2.6.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Jaiganeshkumaran** [comment]
See #5015.
