### ISSUE TITLE
WinUI 2.6 TabView places controls under window controls

### ISSUE THREAD

**Issue by movpushmov** [microsoft/microsoft-ui-xaml#5361]
**Describe the bug**
WinUI 2.6 TabView places controls under window controls

**Steps to reproduce the bug**
1. Open latest version of XAML Controls Gallery
2. Open TabView page
3. Scroll to "Complete TabView windowing sample"
4. Open Window with TabView
5. See bug

**Expected behavior**
"Add" button must be placed before Window controls
![image](https://user-images.githubusercontent.com/49155506/124448641-59b29300-dd8b-11eb-85e3-d613233f65c7.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/49155506/124447970-99c54600-dd8a-11eb-8ac0-6822cff64e5d.png)

**Version Info**
WinUI 2.6

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |  |
| November 2019 Update (18363)       |  |
| May 2019 Update (18362)            |  |
| October 2018 Update (17763)        | |
| April 2018 Update (17134)          | |
| Fall Creators Update (16299)       | |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | |
| Surface Hub        | |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@Alkanores Thanks for reporting this! do you know if it is new to 2.6 or it it was present in 2.5 and before as well?

**Comment by StephenLPeters** [comment]
@Austin-Lamb and @pratikone does winui2 have the tools needed to avoid the Titlebar controls?

**Comment by Alkanores** [comment]
> @Alkanores Thanks for reporting this! do you know if it is new to 2.6 or it it was present in 2.5 and before as well?

Yep, WinUI 2.5 also contains this bug.

![image](https://user-images.githubusercontent.com/49155506/124718755-1719c380-df0f-11eb-928e-36a5c9e51be9.png)

**Comment by ranjeshj** [comment]
Could you use a TabViewStripFooter that allocates space in that area to avoid the overlap as a workaround ?

**Comment by chingucoding** [comment]
Yes that should work. Question is if this is actually an bug with TabView or just the fact that the control was not used properly. I suspect that a NavigationView with DisplayMode set to top would also exhibit this behavior.

**Comment by movpushmov** [comment]
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/49155506/189407884-ba778c55-1b29-4fae-abb9-abb47387cdbf.png">

Fixed in winui3? @StephenLPeters
