### ISSUE TITLE
WinUI 3 AutoSuggestBox in NavigationView is not stretch

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#5362]
**Describe the bug**

AutoSuggestBox in NavigationView is not stretch

**Steps to reproduce the bug**

```
<NavigationView>
            <NavigationView.AutoSuggestBox>
                <AutoSuggestBox QueryIcon="Find" PlaceholderText="Search Artist"/>
            </NavigationView.AutoSuggestBox>
            <ScrollViewer>
                <Frame x:Name="ContentFrame" Padding="12,0,12,24" IsTabStop="True"/>
            </ScrollViewer>
        </NavigationView>
```
![Untitled](https://user-images.githubusercontent.com/9213496/124456426-ea936980-dd9f-11eb-9e1c-271d187540b5.png)

**Expected behavior**

autosuggestbox should be stretch

**Screenshots**

![2](https://user-images.githubusercontent.com/9213496/124456536-0c8cec00-dda0-11eb-944f-5838f0a54e01.png)

**Version Info**

WinUI 3.0
OS: 19043
NuGet package version: 
Microsoft.ProjectReunion" Version="0.8.0
Microsoft.ProjectReunion.Foundation" Version="0.8.0
Microsoft.ProjectReunion.WinUI" Version="0.8.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ghost1372 Thanks! does this issue still occur if you provide at least one NavigationViewItem in the NavigationView.MenuItems collection?

**Comment by ghost1372** [comment]
@StephenLPeters i dont know why, but i tested it again in a new project and everythings worked fine😕 mybe something else in my project is causing this problem. Anyway i close this issue and if i find source of problem i will open it.
Thank you for your response

**Comment by ghost1372** [comment]
@StephenLPeters i dont know why, but i tested it again in a new project and everythings worked fine😕 mybe something else in my project is causing this problem. Anyway i close this issue and if i find source of problem i will open it.
Thank you for your response
