### ISSUE TITLE
0x00007FFAFBC74B89 (KernelBase.dll) : 0xE0434352

### ISSUE THREAD

**Issue by songshizhao** [microsoft/microsoft-ui-xaml#5364]
using v2.6 ,import XamlControlsResources in app.xaml and just use 2 acrylic brush

when in debug mode it work fine ,but in release mode,can not start the app

the error turn out

0x00007FFAFBC74B89 (KernelBase.dll) : 0xE0434352 (: 0xFFFFFFFF80070002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFAD8E90000)

what's more, win store refused the package same as https://github.com/microsoft/microsoft-ui-xaml/issues/5298

**Comment by StephenLPeters** [comment]
@songshizhao can you provide the code you are using to "just use 2 acrylic brush" I think it will help us track down this issue.
