### ISSUE TITLE
[2.6] Button ignores its set Foreground brush on pointer exit

### ISSUE THREAD

**Issue by Ryken100** [microsoft/microsoft-ui-xaml#5365]
**Describe the bug**
If `Button.Foreground` is set to any value, the button's content initially displays this brush. However, after moving the pointer over the button and then removing the pointer from the button, the button's foreground does not reset to the brush set in `Button.Foreground`.

**Steps to reproduce the bug**

1. Create a blank UWP app that references WinUI 2.6
2. Add a `Button` to `MainPage.xaml` and set `Button.Foreground` to any color (such as `Red`)
3. Deploy the app and move the mouse cursor over the button, then remove the cursor
4. Observe the button's foreground will no longer match the color that was set

[Repro App](https://github.com/microsoft/microsoft-ui-xaml/files/6766539/WinUIButtonTest.zip)

This repro app contains a button which demonstrates the problem, as well as a button style based on `DefaultButtonStyle` which fixes the issue.

**Expected behavior**
The button's foreground color should reset to the value set in `Button.Foreground` on pointer exit.

**Screenshots**
[Expected] How the button appears before any pointer interaction (the first button)
![image](https://user-images.githubusercontent.com/26424620/124525929-1c6ff480-ddcf-11eb-8086-92af08c2348a.png)

[Expected] How the button appears on pointer over
![image](https://user-images.githubusercontent.com/26424620/124525952-2e519780-ddcf-11eb-95a3-d18d096f6dd3.png)

[Unexpected] How the button appears on pointer exit (it should reset to red but doesn't)
![image](https://user-images.githubusercontent.com/26424620/124525985-4c1efc80-ddcf-11eb-9db6-eda6d3c50e8c.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
The `ContentPresenter` in `DefaultButtonStyle` doesn't have its `Foreground` property set. I was able to fix the issue in my repro app by creating a new style copied from `DefaultButtonStyle`, and setting `ContentPresenter.Foreground` to `{TemplateBinding Foreground}`. Seems like it should be an easy one line fix :)

**Comment by roxk** [comment]
Using lightweight styling as [documented here](https://docs.microsoft.com/en-us/windows/apps/design/style/xaml-styles#lightweight-styling) works for me:
```
<Button.Resources>
    <SolidColorBrush x:Key="ButtonForeground" Color="Red"/>
    <SolidColorBrush x:Key="ButtonForegroundPointerOver" Color="Blue"/>
    <SolidColorBrush x:Key="ButtonForegroundPressed" Color="Green"/>
</Button.Resources>
```
So it seems to be working as intended? I couldn't find the doc right now but some where in the XAML doc it was mentioned that for interactable control with lightweight styling support, it's no longer recommended to set foreground directly. 

More overridable resources can be found [here](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Button?view=winrt-20348#control-style-and-template).

**Comment by StephenLPeters** [comment]
Thanks for pointing this out... do you know if it also repros with earlier versions of Winui2 or is this new to 2.6?  I'm surprised this would be broken it looks like normal foreground propogation...

**Comment by rudoc** [comment]
> do you know if it also repros with earlier versions of Winui2 or is this new to 2.6?

I will add that `<Button Foreground="{x:Bind ..., Mode=OneWay}"/>` does not work either with 2.6 - the behavior as described by @Ryken100. The issue introduced in
2.6.0-prerelease.210623001 - issue;
2.6.0-prerelease.210430001 - good).
