### ISSUE TITLE
Difference between Start & Left, End & Right TextAlignment in WINUI TextBox control

### ISSUE THREAD

**Issue by Subashini2129** [microsoft/microsoft-ui-xaml#5367]
In TextBox control, if i set the TextAlignment as Start or Left it behaves similarly. What is difference between Start & Left, End & Right TextAlignment in WINUI TextBox control. Can you please explain the use case of Start & Left, End & Right TextAlignment in TextBox control?

**Comment by mdtauk** [comment]
> In TextBox control, if i set the TextAlignment as Start or Left it behaves similarly. What is difference between Start & Left, End & Right TextAlignment in WINUI TextBox control. Can you please explain the use case of Start & Left, End & Right TextAlignment in TextBox control?

I would guess Start and End would be semantic for when the language is Right to Left

**Comment by StephenLPeters** [comment]
> > In TextBox control, if i set the TextAlignment as Start or Left it behaves similarly. What is difference between Start & Left, End & Right TextAlignment in WINUI TextBox control. Can you please explain the use case of Start & Left, End & Right TextAlignment in TextBox control?
> 
> I would guess Start and End would be semantic for when the language is Right to Left

I think this is right. Start will be left for LTR languages and right for RTL languages.  @MikeHillberg could confirm.

**Comment by chrisglein** [comment]
Also believe that is correct.
[Documentation here](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.TextAlignment?view=winrt-20348#fields)
Question has been answered. Closing.
