### ISSUE TITLE
XamlCompiler error WMC1118,TwoWay binding target must be a dependency property

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#5368]
```
 <local:FolderPicker Grid.Row="0" HeaderText="Save Folder" Folder="{x:Bind Attributes.(local:WebUrlRetrieveData.Folder),Mode=TwoWay}"></local:FolderPicker>
```

XamlCompiler error WMC1118: TwoWay binding target 'Folder' must be a dependency property

idl
```
    [default_interface]
    runtimeclass FolderPicker : Microsoft.UI.Xaml.Controls.Control
    {
        FolderPicker();
        String HeaderText;
        String Folder;
        Microsoft.UI.Xaml.DependencyProperty Folder2;
    }
```

i don't know why it throws such an error.

**Comment by StephenLPeters** [comment]
I think you need to name the DependencyProperty in your idl file FolderProperty instead of folder2

**Comment by shelllet** [comment]
> I think you need to name the DependencyProperty in your idl file FolderProperty instead of folder2

Yes, I've tried to replace it with `folder2`, but still this error appears.

**Comment by ranjeshj** [comment]
@shelllet the dependency property needs to be written in a certain way. You can look at details here - https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-dependency-properties#dependency-property-name-conventions

**Comment by shelllet** [comment]
> @shelllet the dependency property needs to be written in a certain way. You can look at details here - https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-dependency-properties#dependency-property-name-conventions

yeah!, i know how to use dependency property, i used dp in `TemplateBinding`
this is the  `folder` dp define:

![image](https://user-images.githubusercontent.com/16729017/124844890-15600680-dfc8-11eb-8c5f-71c3859200b3.png)

**Comment by shelllet** [comment]
> @shelllet the dependency property needs to be written in a certain way. You can look at details here - https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-dependency-properties#dependency-property-name-conventions

it's my fault, I didn't notice: `folder` and `folderproperty` must exist at the same time. thank you!
