### ISSUE TITLE
WinUI 2.6: Mica material does not work in app window

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#5370]
**Describe the bug**

Applying the mica material to an app window shows the accent color instead.

**Steps to reproduce the bug**

1. Run the attached repro project

**Expected behavior**

Mica material works fine in app windows

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

[MicaAppWindowRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6768471/MicaAppWindowRepro.zip)

**Comment by Link1J** [comment]
This is a very similar, if not the exact same as #5319

**Comment by StephenLPeters** [comment]
@jevansaks do you agree this is a dupe?

**Comment by jevansaks** [comment]
Unfortunately it's not a dupe since the fix I had planned wouldn't fix AppWindow. But I think we can probably discuss a mitigation that would help both instead. One thing I notice is that AppWindow doesn't seem to have an activation state exposed. Is there a way to get that or the underlying HWND?

**Comment by lhak** [comment]
I did some testing and using the CompositorWithBlurredWallpaperBackdropBrush interface works fine in app windows (and also XAML islands). The ICompositionSupportsSystemBackdrop interface also seems to be implemented for AppWindow objects but apparently has some bugs, i.e. setting the SystemBackdrop property to the composition brush only has an effect if it is also set on the main Window object.

I think the activation state for appwindows can be determined using the InputActivationListenerPreview/InputActivationListener class. I know that at least the event for state changes works fine.

**Comment by dpaulino** [comment]
Running into this issue as well :(

**Comment by lhak** [comment]
I have implemented a composition brush based on the winui mica code that can be applied as a background here:

https://gist.github.com/lhak/641becbc6a4a5f809c224fc83600bb36

This can be used in app windows by calling the SetAppWindow() member function or in XAML islands by calling the SetWindowActivated() member function and setting the activation state manually.

**Comment by StephenLPeters** [comment]
@marb2000 FYI, we also have a duplicate issue here: https://github.com/microsoft/microsoft-ui-xaml/issues/6553

**Comment by bpulliam** [comment]
Closing since this was duped to #6553. If you are still seeing this on current builds, please open a new issue.
