### ISSUE TITLE
Scrollbar thumb does not shrink upon overscroll

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#5371]
**Describe the bug**

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

i cbf filling it out

latest XCG from store. winui 2.6. windows 10 21h1

**Comment by StephenLPeters** [comment]
I think this is by design.

**Comment by Poopooracoocoo** [comment]
@StephenLPeters bruh what. BY DESIGN??. consult yo designers. surely the new ones don't think the same way @karenbtlai

**Comment by StephenLPeters** [comment]
Maybe we are thinking about different things? I'm just guessing based on the title since there is very little info to go off of.

**Comment by StephenLPeters** [comment]
@chigy and @alejo4000 FYI

**Comment by ranjeshj** [comment]
@Poopooracoocoo can you provide more details or a video of what you are seeing and what you expect to see ?

**Comment by Poopooracoocoo** [comment]
good god tried to show the bug in the MS Store bug here are two bugs lmao:
![image](https://user-images.githubusercontent.com/51363864/124840500-77bc0580-dfce-11eb-9739-e4ab4b41ad4d.png)

**Comment by Poopooracoocoo** [comment]
Okay so look at EdgeHTML's scrollbar (found in the MS Store)
![3LykJUGCTT](https://user-images.githubusercontent.com/51363864/124840601-b8b41a00-dfce-11eb-842c-8562efb909a2.gif)
:

**Comment by Poopooracoocoo** [comment]
The EdgeHTML (and IE) scrollbar works how I'd expect it to. 
No other scrollbars work the same currently. Whether that's the WPF, WinForms or WinUI scrollbars. Or the ones in Office or in Chromium.

**Comment by Poopooracoocoo** [comment]
@StephenLPeters thots?

**Comment by Poopooracoocoo** [comment]
@ranjeshj @alejo4000 @chigy @StephenLPeters So uh. It's been a while...

**Comment by chigy** [comment]
@Poopooracoocoo , thank you for your feedback. Currently, the behavior you see with scroll bar other than EdgeHTML is the intended design.

We currently have no plan on revisiting this at the moment, but I take your feedback in mind when we do.

**Comment by Poopooracoocoo** [comment]
yikes. and you're referring to this as "feedback". we all know how y'all treat "feedback". with the most robotic tone at that. smh.
