### ISSUE TITLE
Discussion: Clean-up Layout Calculations in Styles

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#5377]
# Discussion: Clean-up Layout Calculations in Styles

I noticed lately that there's more and more logic being done in code-behind specific to layout. Traditionally converters have been used in XAML to accomplish this so that the control is still easily re-style-able by others. Moving layout logic calculations to code-behind makes controls harder to visually re-style and can also cause problems if parts of the style are then removed but expected to be there by the code-behind.

Converters of course cause their own set of issues as they're evaluated as part of bindings at runtime, can be harder to debug as binding needs to be valid first, and are then accessible everywhere even if they're only intended for a specific purpose.

`x:Bind` could step in and be a bit of the best of both worlds, providing a more abstracted way from the control to perform logic, in a more encapsulated and usable fashion. Since it's still tied to the template, a re-templated control could re-use those methods easily or choose to not use them (or create their own). Since they're encapsulated methods, they're not exposed to everything else, but if the part of the style using them is removed, then there's no longer code looking for those elements on template and size changes as the ownership has flipped.

However, in it's current state, `x:Bind` doesn't really work well in situations where it'd be useful for Templated Controls. Work should be done to improve `x:Bind` so it can be used for this purpose and control layout logic can then be tidied using those new features.

| Feature | Binding Converter | Code-Behind | x:Bind | Notes |
|---------|----------|----------------|--------|--------|
| Style Accessible/Modifiable | ✔ | ❌ | ✔ | Code-Behind can't be easily re-used or changed by a style. |
| Style Removable | ✔ | ⚠ | ✔ | Code-Behind needs to guard against missing template elements. |
| Style Re-usable | ✔ | ⚠ | ✔ | Code-Behind can only be re-used for the exact same purpose as expected by the control developer and not necessarily for a developer restyling the control. |
| Encapsulated | ❌ | ⚠ | ✔ | Converters need to be more exposed even when for a specific purpose. Code-Behind logic can be intertwined with more functional code of the control which makes it harder to maintain. x:Bind functions can be more easily separated and pertain specifically to the calculation they're performing in tandem with the style template. |
| Compile Time Safety | ❌ | ✔ | ✔ | Binding Converters are evaluated and run completely outside of type-safety at run-time. |

## Related Links
- https://github.com/microsoft/microsoft-ui-xaml/issues/2601
- https://github.com/microsoft/microsoft-ui-xaml/issues/2508
- https://github.com/microsoft/microsoft-ui-xaml/issues/2237
- https://github.com/microsoft/microsoft-ui-xaml/issues/1630

**Comment by michael-hawker** [comment]
(Assuming this needs WinUI 3 for improvements to `x:Bind` moving forward?)

**Comment by StephenLPeters** [comment]
@RealTommyKlein and @fabiant3 FYI
