### ISSUE TITLE
How to change the cursor type while hovering over the scrollviewer element of TextBox control in WINUI Desktop project

### ISSUE THREAD

**Issue by Subashini2129** [microsoft/microsoft-ui-xaml#5384]
Hi Team,

In TextBox control, I have tried to change the cursor type using its `ProtectedCursor` property but it does not have any effect. Also, I have tried changing the `ProtectedCursor` property of the scroll viewer element contained in TextBox, but it also does not have any effect. Please find the sample and screenshot below:

### Sample:

[TextBox-sample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6774350/TextBox-sample.zip)

### Screenshot:

![image](https://user-images.githubusercontent.com/56991221/124702303-d1103000-df0d-11eb-97b5-094b541eb228.png)

**Note:** It always shows IBeam cursor type when hovering over the scrollviewer element in TextBox control instead of hand type cursor which was set in application level.

Could you please suggest any solution regarding it?

**Comment by michael-hawker** [comment]
🦙 Related to #506 and #4834

**Comment by chrisglein** [comment]
This is a gap today, but there's a great proposal here: #506.
In the meantime maybe you could call into the Win32 APIs directly to SetCursor, but that's likely a rough experience. Check up on that proposal and see if it looks like what you're looking for.
