### ISSUE TITLE
Question: What has changed with buttons in 2.6?

### ISSUE THREAD

**Issue by under3415** [microsoft/microsoft-ui-xaml#5385]
Most of my buttons I have painstakingly sized so that the text and icons display correctly on different size screens, are now cutting off text. 

What has changed with buttons in 2.6? 

Have you increased padding or something?

**Comment by ranjeshj** [comment]
@under3415 The buttons (and pretty much every other control) has had a visual update in 2.6 to match the new design system. So yes, that affects paddings as well. Is there a reason why you are not using size to content ?

**Comment by under3415** [comment]
Some buttons are square. Others are in a group, so they need to be same width.
Is there a way to size to content in these scenarios?

**Comment by under3415** [comment]
Btw, Xaml.UI was in pre-release for months without these changes. Then on the very day of the PROD release, you have released a pre-release and a prod release with these, pretty significant, changes. Typically, you want to wind down changes close to release and the last few pre-releases before RTM should just be stability improvements and bug fixes.

**Comment by Link1J** [comment]
The UI changes were in the pre-releases, they just weren't enabled by default.
And you can reenable the old UI design.

**Comment by under3415** [comment]
I didn't know that! Maybe I wasn't paying attention enough.... 

I like the new design, I just felt it was sprung upon us at the last minute.

**Comment by Link1J** [comment]
Well, it wasn't exactly mentioned anywhere in this repo or the docs. So I can't blame you for not knowing.
