### ISSUE TITLE
MUXControlsTestApp button "Show CommandBarFlyout with non-focusable primary commands" causes crash on RS3

### ISSUE THREAD

**Issue by RBrid** [microsoft/microsoft-ui-xaml#5388]
On a RS3 machine, run the MUXControlsTestApp and go to the CommandBarFlyout test page.
Click "Base CommandBarFlyout Tests" button.
click "Show CommandBarFlyout with non-focusable primary commands" button.

Result:
App crash, I believe while executing m_primaryItemsRoot.get().Measure(infiniteSize) in CommandBarFlyoutCommandBar::UpdateTemplateSettings().

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
October 2017 | 1709 (Fall Creators Update) 16299   Redstone 3 (RS3)

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |

**Comment by ranjeshj** [comment]
@RBrid @StephenLPeters This looks like a dup of https://github.com/microsoft/microsoft-ui-xaml/issues/5344
