### ISSUE TITLE
Unit test app referencing UWP app that uses Windows.UI.Xaml crashes

### ISSUE THREAD

**Issue by tonuv** [Microsoft/microsoft-ui-xaml#539]
**Describe the bug**
UWP unit test app references an application which references Windows.UI.Xaml will consistently crash and hence unit tests cannot be run

**Steps to reproduce the bug**
1. Create UWP C# application (App1)
2. Add reference to Windows.UI.Xaml using nuget manager. 
3. Add 
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
    </Application.Resources>
to App.Xaml 
4. Add unit test (UWP C#) project to the solution (UnitTestProject1)
5. Click Test->Run->All Tests - observe that the sample test in the project will run and pass
6. In UnitTest1 project click References->Add reference and check box next to App1
7. Click Test->Run->All Tests - observe that the test app crashes and tests will not run

8. Open registry editor and create a key
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\UnitTestProject1.exe
Add values under this key:
DumpCount (DWORD) 10
DumpFolder (REG_EXPAND_SZ) C:\Temp
DumpType (REG_DWORD) 2
9. Run the unit tests again, test app will fail again but the dump will be created in C:\temp
10. When you open the dump you will see that the application is crashed due to an unhandled exception in Windows.UI.Xaml.dll (0xc000027B)

**Version Info**
This reproes both on VS2017 and 2019 and is independent of OS version and reproes every time

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004

**Additional context**
This bug is blocking unit testing in a UWP project

**Comment by mrlacey** [comment]
This sounds like [the issue I had](https://github.com/Microsoft/microsoft-ui-xaml/issues/230).
Can you try [this workaround](https://github.com/Microsoft/microsoft-ui-xaml/issues/230#issuecomment-458309951)?

If it's that issue, the test project templates have been updated but not released yet. Use the workaround until then.

**Comment by jevansaks** [comment]
Thanks @tonuv for the report and @mrlacey for the pointer. I agree it does seem like the same problem. The external issue in the test templates repo (https://github.com/dotnet/test-templates/pull/56) seems to be resolved. 

@mayankbansal018 how can we get the fix? Is it part of Visual Studio? If so, which version?

**Comment by mayankbansal018** [comment]
@jevansaks, yes the fix will be available in VS, I'm hoping it should be in VS2019 update 1

**Comment by tonuv** [comment]
I tried the workaround suggested, but I still get a crash

**Comment by mayankbansal018** [comment]
@tonuv, can you please share a sample app, for us to investigate?

**Comment by jevansaks** [comment]
We'll use #230 to track.
