### ISSUE TITLE
CommandBarFlyout animations do not look right on RS3

### ISSUE THREAD

**Issue by RBrid** [microsoft/microsoft-ui-xaml#5390]
On a RS3 machine, run the MUXControlsTestApp and go to the CommandBarFlyout test page.
Click "Base CommandBarFlyout Tests" button.
Click any button that shows a flyout with primary and secondary commands.

Result:
The animations for the primary and secondary commands look odd/out of sync.

NuGet package version:
Microsoft.UI.Xaml 2.6.0

Windows 10 version
October 2017	1709 (Fall Creators Update) 16299 Redstone 3 (RS3)

Device form factor
Desktop

**Comment by ranjeshj** [comment]
This is nice to have, but we have many features that degrade down-level so closing this as won't fix.
