### ISSUE TITLE
"CA1416: Validate platform compatibility" error on WinUI XAML code-behind code

### ISSUE THREAD

**Issue by pjmlp** [microsoft/microsoft-ui-xaml#5391]
**Steps to reproduce the bug**

1. Create a C# desktop WinUI 3.0 application
1. Compile the application

**Expected behavior**

No warnings are shown, WinUI is anyway a Windows framework.

**Gotten behavior**

_warning CA1416: This call site is reachable on all platforms_. on WinUI API calls are generated.

**Build Log**

```
Build started...
Restored D:\winui\AStarDemo\AStarDemo\AStarDemo.csproj (in 87 ms).
Restored D:\winui\AStarDemo\AStarDemo (Package)\AStarDemo (Package).wapproj (in 147 ms).
1>------ Build started: Project: AStarDemo, Configuration: Debug x64 ------
1>D:\winui\AStarDemo\AStarDemo\MainWindow.xaml.cs(33,13,33,29): warning CA1416: This call site is reachable on all platforms. 'ContentControl.Content.set' is only supported on: 'Windows'.
1>D:\winui\AStarDemo\AStarDemo\App.xaml.cs(46,13,46,32): warning CA1416: This call site is reachable on all platforms. 'Window.Activate()' is only supported on: 'Windows'.
1>AStarDemo -> D:\winui\AStarDemo\AStarDemo\bin\x64\Debug\net5.0-windows10.0.19041.0\AStarDemo.dll
1>Done building project "AStarDemo.csproj".
2>------ Build started: Project: AStarDemo (Package), Configuration: Debug x64 ------
2>D:\winui\AStarDemo\AStarDemo (Package)\AStarDemo (Package).wapproj : warning NU1701: Package 'Microsoft.ProjectReunion.InteractiveExperiences 0.8.0' was restored using 'net5.0-windows10.0.19041, .NETCoreApp,Version=v3.1, .NETCoreApp,Version=v3.0, .NETCoreApp,Version=v2.0, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, net5.0-windows10.0.17763, net6.0-windows10.0.17763, .NETFramework,Version=v4.6.1' instead of the project target framework 'UAP,Version=v10.0.17763'. This package may not be fully compatible with your project.
2>Done building project "AStarDemo (Package).wapproj".
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Version Info**

WinUI 3.0
Project Reunion 0.8.0 Stable

NuGet package version: 
```
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0" />
    <Manifest Include="$(ApplicationManifest)" />
```

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 21H1           | Yes   |
 

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |   |
| Surface Hub        |   |
| IoT                |   |

**Comment by Marv51** [comment]
Try adding a `[assembly: System.Runtime.Versioning.SupportedOSPlatform("windows10.0.17763.0")]` attribute anywhere, for example at the top of App.xaml.cs.

**Comment by pjmlp** [comment]
I guess that will do it, but it kind of weird to expect all WinUI developers to do that for what is a Windows specific framework after all.

**Comment by alex4998** [comment]
Adding [assembly: System.Runtime.Versioning.SupportedOSPlatform("windows10.0.17763.0")] definitely works and that wouldn't be a problem doing that in my opinion but this attribute has to be taken from autogenerated AssemblyInfo.cs and apparently it is not taken from there. This is the problem. In my case I see that AssemblyInfo is autogenerated and located in one of the sub-folders inside obj folder and contains

[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows10.0.19041.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows10.0.17763.0")]

but that doesn't work. The compiler anyway expects me to but SupportedOSPlatformAttribute somewhere in the project files.
