### ISSUE TITLE
Question: WinUI integration with COM / WinForm / WPF controls

### ISSUE THREAD

**Issue by livehop** [microsoft/microsoft-ui-xaml#5400]
I was wondering if there is any way to embed ActiveX components (created as a WPF / Winforms Control) into WinUI. I have the opportunity build an app from scratch and there is just one critical functionality that has this dependency. I created a winui 3.0 project but I cannot seem to include my WPF / OCX control

**Comment by smourier** [comment]
I think this relates to https://github.com/microsoft/microsoft-ui-xaml/issues/4670

**Comment by StephenLPeters** [comment]
Agreed, same issue.  We don't currently have plans to support this.
