### ISSUE TITLE
NavView Hamburger Button Clipped OnLoad

### ISSUE THREAD

**Issue by karenbtlai** [microsoft/microsoft-ui-xaml#5404]
**Describe the bug**

NavigationView hamburger button is clipped OnLoad. Repros in "NavigationView Stretch Test" page and "NavigationView Animation Test" page.

**Steps to reproduce the bug**

1. Go to NavigationView Stretch Test page or NavigationView Animation Test page of MUXCTestApp
2. Hover over Hamburger button

**Expected behavior**

Hamburger button backplate should not be clipped

**Screenshots**

![image](https://user-images.githubusercontent.com/7976322/124971428-01bf9a80-dfde-11eb-838e-9f4325f8621f.png)

**Version Info**

NuGet package version: 
MUX 2.6

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by myokeeh** [comment]
I've seen this, too.

**Comment by karenbtlai** [comment]
Closing as it no longer repros - fixed somewhere along the way.
