### ISSUE TITLE
Question: What defines this margin on the NavigationView page header?

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#5405]
Excuse the fact that these are two different apps, but one shows the page header for 2.6.1 and the other one shows it for version 2.5. I can't seem to figure it out from the XAML. I'm not quite sure if this is a bug, so I didn't file it as a bug.

App with package version 2.6.1
![image](https://user-images.githubusercontent.com/3663297/124971530-29aefe00-dfde-11eb-9d3f-07c35daec025.png)

App with package version 2.5:
![image](https://user-images.githubusercontent.com/3663297/124971522-24ea4a00-dfde-11eb-8f7d-bebc612762a2.png)

**Comment by myokeeh** [comment]
Okay. I just looked at XAML Controls Gallery, and that appears to be by design--just seems a little awkward to me. Maybe I'll get used to it.

![image](https://user-images.githubusercontent.com/3663297/124982474-98df1f00-dfeb-11eb-85c6-b38a4a7db2e9.png)

**Comment by StephenLPeters** [comment]
Hmm, this looks off to me as well..  the value was changed by @karenbtlai here https://github.com/microsoft/microsoft-ui-xaml/commit/101efd37cc40b39a3d0f031b73b14bcce81e0422.  @alejo4000 and @karenbtlai does this look right to you? I think we maybe regressed this at some point.

**Comment by karenbtlai** [comment]
The NavView Page header is defined as `<Thickness x:Key="NavigationViewHeaderMargin">56,44,0,0</Thickness>` by design. Unfortunately it does not adjust with different window breakpoints yet.

**Comment by mdtauk** [comment]
This is affecting to Settings app I think
![image](https://user-images.githubusercontent.com/7389110/125120320-36207d00-e0ea-11eb-90f5-c4460751107f.png)

**Comment by karenbtlai** [comment]
> This is affecting to Settings app I think
> ![image](https://user-images.githubusercontent.com/7389110/125120320-36207d00-e0ea-11eb-90f5-c4460751107f.png)

Settings is doing some custom work with the layout. This is different from what the WinUI toolkit designers has defined as the margins. I reached out to them to overwrite the NavigationViewHeaderMargin resource to align the left margins.

**Comment by myokeeh** [comment]
> The NavView Page header is defined as `<Thickness x:Key="NavigationViewHeaderMargin">56,44,0,0</Thickness>` by design. Unfortunately it does not adjust with different window breakpoints yet. 

What's the design guidance given this change?

**Comment by karenbtlai** [comment]
> > The NavView Page header is defined as `<Thickness x:Key="NavigationViewHeaderMargin">56,44,0,0</Thickness>` by design. Unfortunately it does not adjust with different window breakpoints yet.
> 
> What's the design guidance given this change?

@myokeeh I can ping the design team and see what they say. In the meantime, you can refer to the [Figma design toolkit](https://www.figma.com/community/file/989931624019688277)

**Comment by ranjeshj** [comment]
This is by design. Our expected page margins are 16, 24 or 56 in order to create great alignment with our default controls.

**Comment by myokeeh** [comment]
It appears this can be overridden:

https://github.com/microsoft/microsoft-ui-xaml/issues/6041#issuecomment-973167056
https://docs.microsoft.com/en-us/windows/apps/design/controls/navigationview


    <Page.Resources>
        <Thickness x:Key="NavigationViewHeaderMargin">10,20,0,20</Thickness>
    </Page.Resources>


Mutch better for me:
![image](https://user-images.githubusercontent.com/3663297/151242164-6f645b66-586b-497a-aa57-1aec00c33fe2.png)
