### ISSUE TITLE
Cannot find a Resource with the Name/Key TabViewButtonBackground

### ISSUE THREAD

**Issue by wusixu** [microsoft/microsoft-ui-xaml#5406]
In my Xaml Islands Win32 C++ project, I can use controls from UWP project, but can't create any WinUI control.
Any WinUI control will throw  below exceptions:
WinRT originate error - 0x80004005 : 'Cannot find a Resource with the Name/Key TabViewButtonBackground'.
WinRT originate error - 0x802B000A : 'Cannot find a Resource with the Name/Key TabViewScrollButtonBackground [Line: 2570 Position: 35]'.
WinRT originate error - 0x802B000A : 'Cannot find a Resource with the Name/Key TabViewButtonBackground [Line: 33 Position: 10]'.

I found a similar issue: [https://github.com/microsoft/microsoft-ui-xaml/issues/2957](https://github.com/microsoft/microsoft-ui-xaml/issues/2957
). I added this to the project:

```
<PropertyGroup>
   <DisableEmbeddedXbf>true</DisableEmbeddedXbf>
</PropertyGroup>
```

but the fix did not work.

Version Info

- Nuget WinUI: 2.6.1

- Microsoft.Windows.CppWinRT 2.0.210707.1

- Windows: Win11 Insider  210629

**Comment by StephenLPeters** [comment]
This is the issue that you get when you don't include <XamlControlsResources> in your App.xaml.  This just happens to be the first key that it looks for and doesn't find.  When you add the Winui nuget package you should have gotten a readme opened which instructed you to add the XCR.  that readme is here: https://github.com/microsoft/microsoft-ui-xaml/blob/main/build/NuSpecs/readme.txt. Let us know if that fixes your issue.

**Comment by wusixu** [comment]
I added XamlControlsResources in my App.xaml, it does not work.

**Comment by wusixu** [comment]
I set up my project strictly according to this[ document](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp)： , and at first everything else worked fine, except the user control. Customized user control threw the exception: 
`
Cannot locate resource from 'ms-appx:///MyUserControl.xaml'
`
I fixed this by removing package.appxmanifest from the UWP project, it worked and MyUserControl was displayed normally,
But when I added a WinUI control, it failed with `Cannot find a Resource with the Name/Key`
![image](https://user-images.githubusercontent.com/51706902/125004204-9d5b1480-e08b-11eb-9b39-99cadabfafe5.png)

![image](https://user-images.githubusercontent.com/51706902/125004166-84eafa00-e08b-11eb-9eb2-b0bb707c8f50.png)

**Comment by StephenLPeters** [comment]
@marb2000 Can you help out here? I'm not sure exactly how the xaml islands project is supposed to be set up

**Comment by luojunyuan** [comment]
I resolved the issue by using the Windows.UI.Xaml version of NavigationView instead of the muxc version.
