### ISSUE TITLE
uwp winui 3 and .net5 project do not work like grpc client app

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5407]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/uwp-winui-3-and-net5-project-do-not-wor/1467215)._

---
I created a UWP WinUi3 project to create a client application that would have to communicate with a grpc server.

I have added according documentation
Google.Protobuf  Version="3.17.3" 
Grpc.Net.ClientFactory Version="2.38.0" 
Grpc.Tools Version="2.38.1"
protobuf-net Version="3.0.101

As can be seen in the project that I attach whenever I put the line 

`var client = new xizServer.Greeter.GreeterClient(channel);`

I get **Error CS0246 The type or namespace name 'xizServer' could not be found**.

The strange thing is that I have a console application with the same code and then it seems to work without problems
what am I doing wrong what may be missing to make it work in the WinUi3 project

Thanks

---
#### Feedback Bot on 7/4/2021, 11:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### José Marcos on 7/5/2021, 04:03 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@Scottj1s could this be a CSWinrt issue? I'm not sure if these are managed or Winrt based. 

UWP isn't fully supported by ProjectReunion 0.8  @ryandemopoulos and @Austin-Lamb FYI

**Comment by inforzip** [comment]
I experiment with a WPF project with net5.0 and the same situation happens. I assume that Wpf doesn't have full support for projectreunion 0.8 either.
However the project console application with net5.0 seems to work.
What is the forecast for solving this problem?

**Comment by krschau** [comment]
Closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615). If you are still seeing the behavior with a Win32 app using the latest WindowsAppSDK version, please open a new issue.
