### ISSUE TITLE
Dark Theme does not cover the title bar

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#5408]
**Describe the bug**
By changing the theme to dark, the title bar is still white and does not change

**Expected behavior**
The color of the title bar should also change as the theme changes
**Screenshots**

![Untitled](https://user-images.githubusercontent.com/9213496/124318069-58b41280-db8d-11eb-8524-a14aec937bc5.png)

**Version Info**
Microsoft.ProjectReunion 0.8.0

OS : 19043

**Comment by StephenLPeters** [comment]
@pratikone and @Austin-Lamb FYI

**Comment by pratikone** [comment]
@ghost1372 can you show how you are changing the theme ? are you setting app theme to Dark or you are changing Windows theme to Dark ? As you are using the normal Win32 titlebar, it follows the same theme as Windows theme. If you want titlebar to be of same theme as App theme (without changing Windows global theme setting), you can explore custom titlebar (https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0)

**Comment by ghost1372** [comment]
I did both of the methods you mentioned, but neither worked
![Animation](https://user-images.githubusercontent.com/9213496/125566611-6a18ab4d-498d-408e-9dbc-1f25095f9b14.gif)

also, I change the theme this way
```
<StackPanel x:Name="themePanel">
      <RadioButton Tag="Light" Checked="OnThemeRadioButtonChecked" Content="Light"  />
      <RadioButton Tag="Dark" Checked="OnThemeRadioButtonChecked" Content="Dark" />
  </StackPanel>
```
and
```
void OnThemeRadioButtonChecked(object sender, RoutedEventArgs e)
{
    var selectedTheme = ((RadioButton)sender)?.Tag?.ToString();
    if (selectedTheme != null)
    {
        ((sender as RadioButton).XamlRoot.Content as Grid).RequestedTheme = GetEnum<ElementTheme>(selectedTheme);
    }
}
```
I have not tested the custom titlebar

**Comment by pratikone** [comment]
I see. that looks like an issue.  I will repro it and follow it up internally. Thanks for providing the repro steps.

**Comment by pratikone** [comment]
We are a working on a more cohesive titlebar experience for winui apps which provide a default titlebar which looks good, without any extra effort.

Until then, you can do this light -> dark titlebar switch manually. 
Just check app theme and use DWMWA_USE_IMMERSIVE_DARK_MODE to switch to dark mode.

refer : https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes
