### ISSUE TITLE
Possible bug on webview2.

### ISSUE THREAD

**Issue by woxip0** [microsoft/microsoft-ui-xaml#5410]
Exception thrown at 0x00007FFB44614B89 in App.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000F185188E30.
**Steps to reproduce the bug**

1. Using up to date visual studio 2019, create a winui blank app.
2. Add `<Webview2 Source="https://<ANY ADDRESS>" />` in any running xaml.

Alternatively:
1. Using up to date visual studio 2019, create a winui blank app.
2. Use this line in the csharp code: `await this.WebBrowser.EnsureCoreWebView2Async();` 

**Expected behavior**
It should load the required addres.

**Version Info**
Project reunion 0.8.0
Nuget package manager 5.10.0
Windows build 19042.985
Visual Studio 16.10.3

NuGet package version: 
Microsoft.ProjectReunion.WinUI 0.8.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | No   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | No  |
| May 2019 Update (18362)             | No  |
| October 2018 Update (17763)        | No |

**Additional context**
I have a warning that is possibly related:
```
Warning	NU1701	Package 'Microsoft.ProjectReunion.InteractiveExperiences 0.8.0' was restored using 'net5.0-windows10.0.19041, .NETCoreApp,Version=v3.1, .NETCoreApp,Version=v3.0, .NETCoreApp,Version=v2.0, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, net5.0-windows10.0.19041, net6.0-windows10.0.19041, .NETFramework,Version=v4.6.1' instead of the project target framework 'UAP,Version=v10.0.19041'. This package may not be fully compatible with your project.
```

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by codendone** [comment]
Do you still repro this issue? Using `<WebView2 Source="https://microsoft.com/" />` works correctly. Has this problem gone away for you, or is only a specific Uri a problem?

**Comment by woxip0** [comment]
Thanks for your answer. I don't think it was an issue with the URI as the code was tested with valid URLs. Anyway, we migrated back from Reunion to WPF in which webview2 works as expected. 

I will try to run the project using Reunion again with up-to-date dependencies soon.
