### ISSUE TITLE
AllowFocusOnInteraction API doesn't work for framework elements other than button base controls

### ISSUE THREAD

**Issue by KanniyappanP** [microsoft/microsoft-ui-xaml#5411]
**Describe the bug**
AllowFocusOnInteraction API doesn't work for framework elements other than button base controls

**Steps to reproduce the bug**
1. Run the attached sample. 
[AllowFocusOnInteraction_API_Issue.zip](https://github.com/microsoft/WindowsAppSDK/files/6784183/AllowFocusOnInteraction_API_Issue.zip)

2. Click the NumberBox to get focus.
3. Click the Button or CheckBox (Both controls enabled the AllowFocusOnInteraction API as false) and note NumberBox focus doesn't changed. 
4. Click the above grid content (it may be either grid, stack panel, content control and etc..), NumberBox focus gets lost. 
   But I have enabled the AllowFocusOnInteraction = false.

**Expected behavior**
NumberBox focus should not lost when click on Grid element if AllowFocusOnInteraction as false.

**Screenshots**
NA

**Version Info**
ProjectReunion 0.8

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | 🆗  |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**
AllowFocusOnInteracton API works only for ButtonBase derived elements only like Button, CheckBox and RadioButton controls and doesn't for other frameworks controls.

Any workaround for this issue would be appreciated.

Thanks, in advance.

**Comment by KanniyappanP** [comment]
Hi Team, 

Any workaround for the reported issue?

**Comment by akilarajesh1313** [comment]
Thank you so much for your patience! We don't have an answer for you yet, but are currently investigating the issue.

**Comment by codendone** [comment]
The problem here is that a different element is taking focus: there is an internal root ScrollViewer above the Window.Content, and any ScrollViewer will take focus on PointerReleased if the event hasn't been handled. If you change your `Grid` to have a PointerReleased handler and set args.Handled=true, that will prevent the root ScrollViewer from processing the PointerReleased.

**Comment by Austin-Lamb** [comment]
It's possible that we should change this root ScrollViewer to set AllowFocusOnInteraction to false - I'm not sure why we'd want it to be taking focus.  But we'd need to think about the implications and compat of that change.

**Comment by jeganraj-m** [comment]
@akilarajesh1313 This looks similar to the issue i'm facing https://github.com/microsoft/microsoft-ui-xaml/issues/5042. 
@codendone  Thanks, your work around works for me, but this need to fix in source level right?

**Comment by codendone** [comment]
@jeganraj-m Yes, for that workaround code is required to implement the PointerReleased handler.

**Comment by jeganraj-m** [comment]
Hi @akilarajesh1313 got any chance to check this
