### ISSUE TITLE
KeyboardAccelerators not invoked for CommandBar.SecondaryCommands 

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#5413]
**Describe the bug**

When adding a secondary command to a commandbar with a keyboard accelerator, the accelerator is not invoked.

```
<CommandBar.SecondaryCommands >
    <AppBarButton Icon="Save" Label="Save" Command="{Binding SaveCommand}" >
        <AppBarButton.KeyboardAccelerators>
            <KeyboardAccelerator Modifiers="Control" Key="S" />
        </AppBarButton.KeyboardAccelerators>
    </AppBarButton>
</CommandBar.SecondaryCommands>
```

**Steps to reproduce the bug**

1) Add the above code snippet to a CommandBar in a Page
2) Create and bind a viewmodel which has a "SaveCommad" ICommand
3) Run and use keyboard keystroke CTRL+S
4) Command is not invoked

**Expected behavior**

Command should be invoked, even though it is not visible (is in secondary area)

This same AppBarButton placed in the CommandBar.PrimaryCommands works as expected

**Screenshots**

**Version Info**

NuGet package version: 

![image](https://user-images.githubusercontent.com/9586533/125002445-c9ce4c80-e009-11eb-9245-a9568c172b77.png)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | YES |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | YES   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@omnilogix if you open the secondary items at least once and then close it?  I think this is a known issue where we don't register keyboard accelerators with the global list until the element with the accelerator enters the visual tree.

**Comment by omnilogix** [comment]
> @omnilogix if you open the secondary items at least once and then close it? I think this is a known issue where we don't register keyboard accelerators with the global list until the element with the accelerator enters the visual tree.

@StephenLPeters  Yeah, I tried opening the secondary as well.  Still no keyboard respose

**Comment by omnilogix** [comment]
Any progress on this item?

**Comment by DmitriyKomin** [comment]
This scenario is working in both WinUI2 Gallery and WinUI3 Gallery samples (on the CommandBar page, hit CTRL+I to activate Settings button in secondary commands). Please let us know if you're still seeing this (eg if there is an aspect of the repro code that diverges and affects the outcome).
