### ISSUE TITLE
`ComboBox` 's `SelectedValue` don't support enum types.

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#5419]
set `ComboBox`'s `ItemsSource ` with enum values.
but 
My().SelectedValue(winrt::box_value(WebBy::ID)); don't working!

`WebBy` defind as below, it's generated by idl.
```
 enum class WebBy : int32_t
    {
        ID = 0,
        XPATH = 1,
        LINK_TEXT = 2,
        PARTIAL_LINK_TEXT = 3,
        NAME = 4,
        TAG_NAME = 5,
        CLASS_NAME = 6,
        CSS_SELECTOR = 7,
    };
```

**Comment by shelllet** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/3875

**Comment by StephenLPeters** [comment]
Looks like you found a duplicate issue does @RealTommyKlein 's reponse help you out? https://github.com/microsoft/microsoft-ui-xaml/issues/3875#issuecomment-780938290
