### ISSUE TITLE
TeachingTip creation error: Cannot find a Resource with the Name/Key TeachingTipBackgroundBrush 

### ISSUE THREAD

**Issue by arcadiogarcia** [Microsoft/microsoft-ui-xaml#542]
**Describe the bug**
An exception is thrown when trying to create a TeachingTip following the instructions from the documentation.

**Steps to reproduce the bug**

1. Create a new UWP C# project, targetting the 19H1 SDK
2. Install the Microsoft.UI.Xaml package, version v2.1.190405004
3. Add a button with a teaching tip using the code from https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip#create-a-teaching-tip I literally copied and pasted this XAML from that page:

```xaml
<Button x:Name="SaveButton" Content="Save">
    <Button.Resources>
        <controls:TeachingTip x:Name="AutoSaveTip"
            Target="{x:Bind SaveButton}"
            Title="Save automatically"
            Subtitle="When you save your file to OneDrive, we save your changes as you go - so you never have to.">
        </controls:TeachingTip>
    </Button.Resources>
</Button>
```

Calling this.InitializeComponent() in the contructor of MainPage throws the following error:
Cannot find a Resource with the Name/Key TeachingTipBackgroundBrush 

**Expected behavior**

The TeachingTip should be created without throwing an error.

**Screenshots**
N/A

**Version Info**

Observed on Windows 1903, 18362
Package version v2.1.190405004
Target and min SDK version: 1809

**Comment by chrisglein** [comment]
I'm able to reproduce that error message, but only if I skip the step in the readme.txt and [getting started guide](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started) of adding this to app.xaml:

```
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
    </Application.Resources>
```

Can you confirm if this is present or not in your application?
The error message here is certainly not clear enough if this is the error. We'll follow up on that once we confirm that you're unblocked.

**Comment by arcadiogarcia** [comment]
Oops looks like my app overrides the application resources later on, so that would definitely explain it, and I forgot that step when creating the minimal repro 🤦‍♂️ Thanks for the help
