### ISSUE TITLE
FlowDirection is not working for DatePicker

### ISSUE THREAD

**Issue by KarthikRajaAKR** [microsoft/microsoft-ui-xaml#5420]
**Describe the bug**
FlowDirection property seems not working for WinUI DatePicker.

**Steps to reproduce the bug**
[UWPTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6790124/UWPTest.zip)

1. Run sample with DatePicker and Set RTL FlowDirection.
2. Note that direction is not updated.

**Expected behavior**
We need to set the RightToLeft flow direction for the default date picker and don't want to use CalendarIdentifier.

**Screenshots**

![image](https://user-images.githubusercontent.com/41435300/125040495-5bdf5f00-e0b5-11eb-82b4-2692b154774c.png)

![image](https://user-images.githubusercontent.com/41435300/125040439-48cc8f00-e0b5-11eb-9ecb-7130880db194.png)

**Version Info**
NuGet package version: 
[WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |   |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |   |
| May 2019 Update (18362)            |   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@RBrid FYI

**Comment by KarthikRajaAKR** [comment]
Hi Team,

Can anyone please look at this query, Is this a behavior or an issue? I suspect that the CalendarIdentifier overrides FlowDirection property.
