### ISSUE TITLE
Question: [Application class has no virtual method OnActivated]

### ISSUE THREAD

**Issue by amaosangm** [microsoft/microsoft-ui-xaml#5421]
Below is the screenshot of Application class: 
![image](https://user-images.githubusercontent.com/32085019/125043018-17f85400-e0cd-11eb-8b27-8522e59760d0.png)
I find the doc of winUI Application class(https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.application.onactivated?view=winui-3.0-preview) and it says there is a OnActivated method, but I tried building winUI projects with Project Reunion 0.5 and 0.8,  neither build has OnActivated method.
Is this a bug or something? Or can someone tell me how could I handle local toast notification activation without thie method?

**Comment by kmgallahan** [comment]
Only available in preview.

![Screenshot 2021-07-09 071501](https://user-images.githubusercontent.com/5379488/125070008-844f6500-e085-11eb-8fa6-d24d770676d0.png)

**Comment by amaosangm** [comment]
> Only available in preview.
> 
> ![Screenshot 2021-07-09 071501](https://user-images.githubusercontent.com/5379488/125070008-844f6500-e085-11eb-8fa6-d24d770676d0.png)

thanks, I see the updated page.
