### ISSUE TITLE
Xaml Compiler error WMC0095 issued when Dependency Properties have Setters

### ISSUE THREAD

**Issue by MRahilly** [microsoft/microsoft-ui-xaml#5422]
error:
MainPage.xaml(20,21): XamlCompiler error WMC0095: Property 'Color1' must be a DependencyProperty to be set with a Setter
MainPage.xaml(21,21): XamlCompiler error WMC0095: Property 'Color2' must be a DependencyProperty to be set with a Setter

pch.h:
#pragma once
#include <windows.h>
#include <unknwn.h>
#include <restrictederrorinfo.h>
#include <hstring.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Data.h>
#include <winrt/Windows.UI.Xaml.Interop.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Navigation.h>
#include <winrt/Windows.UI.Xaml.Media.h> // GradientStop

MainPage.xaml:
<Page
    x:Class="DependencyProperties.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:DependencyProperties"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Page.Resources>
        <Style x:Key="baseButtonStyle" TargetType="local:GradientButton">
            <Setter Property="FontSize" Value="48" />
            <Setter Property="HorizontalAlignment" Value="Center" />
            <Setter Property="Margin" Value="0 12" />
        </Style>

        <Style x:Key="blueRedButtonStyle" 
               TargetType="local:GradientButton"
               BasedOn="{StaticResource baseButtonStyle}">
            <Setter Property="Color1" Value="Blue" />
            <Setter Property="Color2" Value="Red" />
        </Style>
    </Page.Resources>

    <Grid Background="{StaticResource ApplicationPageBackgroundThemeBrush}">
        <StackPanel>
            <local:GradientButton Content="GradientButton #1"
                                  Style="{StaticResource baseButtonStyle}" />

            <local:GradientButton Content="GradientButton #2"
                                  Style="{StaticResource blueRedButtonStyle}" />

            <local:GradientButton Content="GradientButton #3"
                                  Style="{StaticResource baseButtonStyle}"
                                  Color1="Aqua"
                                  Color2="Lime" />
        </StackPanel>
    </Grid>
</Page>

MainPage.idl:
namespace DependencyProperties
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
    }
}

MainPage.h:
#pragma once

#include "MainPage.g.h"
#include "GradientButton.h"

namespace winrt::DependencyProperties::implementation
{
    struct MainPage : MainPageT<MainPage>
    {
        MainPage();
    };
}

namespace winrt::DependencyProperties::factory_implementation
{
    struct MainPage : MainPageT<MainPage, implementation::MainPage>
    {
    };
}

MainPage.cpp:
#include "pch.h"
#include "MainPage.h"
#include "MainPage.g.cpp"

using namespace winrt;
using namespace DependencyProperties::implementation;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::UI::Xaml;
using namespace Windows::UI::Xaml::Controls;
using namespace Windows::UI::Xaml::Controls::Primitives;
using namespace Windows::UI::Xaml::Data;
using namespace Windows::UI::Xaml::Input;
using namespace Windows::UI::Xaml::Media;
using namespace Windows::UI::Xaml::Navigation;

MainPage::MainPage()
{
    InitializeComponent();
}

GradientButton.idl:
namespace DependencyProperties
{
    [default_interface]
    runtimeclass GradientButton : Windows.UI.Xaml.Controls.Button
    {
        GradientButton();

	static Object Color1Property{ get; };
        static Object Color2Property{ get; };
        Windows.UI.Color Color1{ get; set; };
        Windows.UI.Color Color2{ get; set; };
    }
}

GradientButton.h:
#pragma once

#include "GradientButton.g.h"

namespace winrt::DependencyProperties::implementation
{
    struct GradientButton : GradientButtonT<GradientButton>
    {
        static Windows::UI::Xaml::DependencyProperty color1Property;
        static Windows::UI::Xaml::DependencyProperty color2Property;

        Windows::UI::Xaml::Media::GradientStop gradientStop1;
        Windows::UI::Xaml::Media::GradientStop gradientStop2;

        GradientButton();

        static Windows::UI::Xaml::DependencyProperty Color1Property();

        static Windows::UI::Xaml::DependencyProperty Color2Property();

        Windows::UI::Color Color1();
        void Color1(winrt::Windows::UI::Color);

        Windows::UI::Color Color2();
        void Color2(Windows::UI::Color);

        static void OnColorChanged(Windows::UI::Xaml::DependencyObject, Windows::UI::Xaml::DependencyPropertyChangedEventArgs);

        void OnColorChangedInstance(Windows::UI::Xaml::DependencyPropertyChangedEventArgs);
    };
}

namespace winrt::DependencyProperties::factory_implementation
{
    struct GradientButton : GradientButtonT<GradientButton, implementation::GradientButton>
    {
    };
}

/*#pragma once

#include "pch.h"

namespace DependencyProperties
{
    public ref class GradientButton sealed : Windows::UI::Xaml::Controls::Button
    {
    private:
        static Windows::UI::Xaml::DependencyProperty^ color1Property;
        static Windows::UI::Xaml::DependencyProperty^ color2Property;

        Windows::UI::Xaml::Media::GradientStop^ gradientStop1;
        Windows::UI::Xaml::Media::GradientStop^ gradientStop2;

    public:
        GradientButton();

        static property Windows::UI::Xaml::DependencyProperty^ Color1Property
        {
            Windows::UI::Xaml::DependencyProperty^ get();
        }

        static property Windows::UI::Xaml::DependencyProperty^ Color2Property
        {
            Windows::UI::Xaml::DependencyProperty^ get();
        }

        property Windows::UI::Color Color1
        { 
            Windows::UI::Color get(); 
            void set(Windows::UI::Color);
        }

        property Windows::UI::Color Color2
        { 
            Windows::UI::Color get(); 
            void set(Windows::UI::Color);
        }

        static void OnColorChanged(Windows::UI::Xaml::DependencyObject^ sender, Windows::UI::Xaml::DependencyPropertyChangedEventArgs^ args);

    private:
        void OnColorChangedInstance(Windows::UI::Xaml::DependencyPropertyChangedEventArgs^ args);
    };
}*/

GradientButton.cpp:
#include "pch.h"
#include "GradientButton.h"
#include "GradientButton.g.cpp"

using namespace winrt;
using namespace DependencyProperties::implementation;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::UI;
using namespace Windows::UI::Xaml;
using namespace Windows::UI::Xaml::Controls;
using namespace Windows::UI::Xaml::Controls::Primitives;
using namespace Windows::UI::Xaml::Data;
using namespace Windows::UI::Xaml::Input;
using namespace Windows::UI::Xaml::Interop;
using namespace Windows::UI::Xaml::Media;
using namespace Windows::UI::Xaml::Navigation;

DependencyProperty GradientButton::color1Property{
DependencyProperty::Register(L"Color1",
    xaml_typename<Color>(),
    xaml_typename<DependencyProperties::GradientButton>(),
    PropertyMetadata{box_value(Colors::White()),
        PropertyChangedCallback{&GradientButton::OnColorChanged}}) };

DependencyProperty GradientButton::color2Property{
DependencyProperty::Register(L"Color2",
    xaml_typename<Color>(),
    xaml_typename<DependencyProperties::GradientButton>(),
    PropertyMetadata{box_value(Colors::Black()),
        PropertyChangedCallback{&GradientButton::OnColorChanged}}) };

GradientButton::GradientButton()
{
    gradientStop1 = GradientStop();
    gradientStop1.Offset(0);
    gradientStop1.Color(Color1());
    gradientStop2 = GradientStop();
    gradientStop2.Offset(1);
    gradientStop2.Color(Color2());
    LinearGradientBrush brush;
    brush.GradientStops().Append(gradientStop1);
    brush.GradientStops().Append(gradientStop2);
    Foreground(brush);
}

DependencyProperty GradientButton::Color1Property()
{
	return color1Property;
}

DependencyProperty GradientButton::Color2Property()
{
	return color2Property;
}

Color GradientButton::Color1()
{
    return unbox_value<Color>(GetValue(Color1Property()));
}

void GradientButton::Color1(Color value)
{
    SetValue(Color1Property(), box_value(value));
}

Color GradientButton::Color2()
{
    return unbox_value<Color>(GetValue(Color2Property()));
}

void GradientButton::Color2(Color value)
{
    SetValue(Color2Property(), box_value(value));
}

void GradientButton::OnColorChanged(DependencyObject sender, DependencyPropertyChangedEventArgs args)
{
    auto control{ sender.as<DependencyProperties::GradientButton>() };
    auto* pSender{ get_self<DependencyProperties::implementation::GradientButton>(control) };
    pSender->OnColorChangedInstance(args);
}

void GradientButton::OnColorChangedInstance(DependencyPropertyChangedEventArgs args)
{
    if (args.Property() == GradientButton::Color1Property())
    {
        gradientStop1.Color(unbox_value<Color>(args.NewValue()));
    }

    if (args.Property() == GradientButton::Color2Property())
    {
        gradientStop2.Color(unbox_value<Color>(args.NewValue()));
    }
}

/*#include "pch.h"
#include "GradientButton.h"
using namespace DependencyProperties;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::UI;
using namespace Windows::UI::Xaml;
using namespace Windows::UI::Xaml::Controls;
using namespace Windows::UI::Xaml::Controls::Primitives;
using namespace Windows::UI::Xaml::Data;
using namespace Windows::UI::Xaml::Input;
using namespace Windows::UI::Xaml::Interop;
using namespace Windows::UI::Xaml::Media;
using namespace Windows::UI::Xaml::Navigation;
DependencyProperty^ GradientButton::color1Property =
DependencyProperty::Register("Color1",
    TypeName(Color::typeid),
    TypeName(GradientButton::typeid),
    ref new PropertyMetadata(Colors::White,
        ref new PropertyChangedCallback(GradientButton::OnColorChanged)));
DependencyProperty^ GradientButton::color2Property =
DependencyProperty::Register("Color2",
    TypeName(Color::typeid),
    TypeName(GradientButton::typeid),
    ref new PropertyMetadata(Colors::Black,
        ref new PropertyChangedCallback(GradientButton::OnColorChanged)));
GradientButton::GradientButton()
{
    gradientStop1 = ref new GradientStop();
    gradientStop1->Offset = 0;
    gradientStop1->Color = this->Color1;
    gradientStop2 = ref new GradientStop();
    gradientStop2->Offset = 1;
    gradientStop2->Color = this->Color2;
    LinearGradientBrush^ brush = ref new LinearGradientBrush();
    brush->GradientStops->Append(gradientStop1);
    brush->GradientStops->Append(gradientStop2);
    this->Foreground = brush;
}
DependencyProperty^ GradientButton::Color1Property::get()
{
    return color1Property;
}
DependencyProperty^ GradientButton::Color2Property::get()
{
    return color2Property;
}
Color GradientButton::Color1::get()
{
    return Color(GetValue(Color1Property));
}
void GradientButton::Color1::set(Color value)
{
    SetValue(Color1Property, value);
}
Color GradientButton::Color2::get()
{
    return Color(GetValue(Color2Property));
}
void GradientButton::Color2::set(Color value)
{
    SetValue(Color2Property, value);
}
void GradientButton::OnColorChanged(DependencyObject^ sender, DependencyPropertyChangedEventArgs^ args)
{
    dynamic_cast<GradientButton^>(sender)->OnColorChangedInstance(args);
}
void GradientButton::OnColorChangedInstance(DependencyPropertyChangedEventArgs^ args)
{
    if (args->Property == GradientButton::Color1Property)
        gradientStop1->Color = Color(args->NewValue);
    if (args->Property == GradientButton::Color2Property)
        gradientStop2->Color = Color(args->NewValue);
}*/

**Comment by StephenLPeters** [comment]
I believe that the issue is in your idl file:

GradientButton.idl:
```
namespace DependencyProperties
{
  [default_interface]
  runtimeclass GradientButton : Windows.UI.Xaml.Controls.Button
  {
      GradientButton();
  
      static Object Color1Property{ get; };
      static Object Color2Property{ get; };
      Windows.UI.Color Color1{ get; set; };
      Windows.UI.Color Color2{ get; set; };
  }
}
```

The Color1Property needs to be of type DependencyProperty not Object.

**Comment by MRahilly** [comment]
Thank you Stephen. This Petzold 6/e Chapter 05 C++/CX example now moves across to C++/WinRT. I had actually used the same pattern correctly on earlier examples from the book:(
