### ISSUE TITLE
.xaml files are not copied, PRI file not generated correctly when creating NuGet from class library

### ISSUE THREAD

**Issue by edoust** [microsoft/microsoft-ui-xaml#5423]
When you create a WinUI / .NET5 class library, the build output consists of a dll file and of one .xaml/.xbf file for each user control in that class library.

If GeneratePackageOnBuild is set to true, a NuGet is created from the class library. The NuGet file does not contain the .xaml files. Each NuGet has to be manually edited to contain the necessary .xaml files in the right folder structure. Also, the PRI file is not generated. 

If that NuGet is installed in a WinUI / .NET 5 project, the .xaml files are not built into the resulting app package, so they are missing. During runtime of the app, an exception is thrown "Cannot locate resource from 'ms-appx:///ClassLibrary1/Views/CustomerView.xaml".

If the .xbf files are copied to the appx folder manually, the app works, showing the right UI, without throwing an exception.

If the nuget is manually prepared with the .xaml files and makepri is executed, and the resulting PRI file is also included in the Nuget, the app works, showing the right UI, without throwing an exception

**Steps to reproduce the bug**
1. Create .NET 5 / WinUI project with at least one user control, generate NuGet
2. Install the generated NuGet package to a .NET 5 / WinUI app project
3. Add the user control from step 1. to the app project from step 2.
4. Start the app, navigate to where the user control should be showing
5. Witness the Exception

**Expected behavior**
Instead of the error, the UI should be showing

**Version Info**

NuGet package version: 
Most recent 0.8

Windows app type:
Happened on .NET 5 / WinUI 0.8
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by shelllet** [comment]
The `.xbf` file exposes the structure of the class. Why do I need such files and how can I properly avoid generating them?

**Comment by StephenLPeters** [comment]
Are you running in Debug or Release?  Release mode should have everything packaged into the pri file. But if your in debug mode it might expect them to be packaged into the nuget package.

**Comment by edoust** [comment]
@StephenLPeters 
I built as Release with msbuild command line `/p:Configuration=Release /t:clean,build,pack`

The described behavior happens when ProjectReunion is imported as transitive NuGet reference... If it is directly imported in the project, it works fine

**Comment by StephenLPeters** [comment]
@alwu-msft do we perhaps have a bug with indirectly imported references?

**Comment by alwu-msft** [comment]
The .pri not being generated when `GeneratePackageOnBuild` is set to true makes this sound like an MRT Core bug. @rohanp-msft does this ring any bells?

**Comment by edoust** [comment]
Here is a repro, 

Project A: NugetPackagingRepro has a UserControl1.xaml, and a project reference to Project B
Project B: Has nothing but a package reference to Project Reunion 0.8.1

when running `msbuild /p:Configuration=Release /t:clean,build,pack` two nuget packages are created

NuGet for Project A: Xaml files included, **but no PRI file**
NuGet for Project B: PRI file included

[NugetPackagingRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6820654/NugetPackagingRepro.zip)

**Comment by rohanp-msft** [comment]
Looking at this, will update soon.

**Comment by rohanp-msft** [comment]
Hi @edoust ,

The WinUI class library template installs three Project Reunion packages:
![image](https://user-images.githubusercontent.com/35987549/126084855-87bfcb07-a259-4fae-801a-ed1eb3eb9f46.png)

Your class library project was missing all three of these packages. I installed them and rebuilt.

Now, I see the PRI:
S:\temp\NugetPackagingRepro\NugetPackagingRepro\bin\Debug\net5.0-windows10.0.19041.0\NugetPackagingRepro.pri

The PRI does contain the XBF:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PriInfo>
	<ResourceMap name="NugetPackagingRepro" version="1.0" primary="true">
		<Qualifiers/>
		<ResourceMapSubtree name="Files">
			<ResourceMapSubtree name="NugetPackagingRepro">
				<NamedResource name="UserControl1.xbf" uri="ms-resource://NugetPackagingRepro/Files/NugetPackagingRepro/UserControl1.xbf">
					<Candidate type="Path">
						<Value>NugetPackagingRepro\UserControl1.xbf</Value>
					</Candidate>
				</NamedResource>
			</ResourceMapSubtree>
		</ResourceMapSubtree>
	</ResourceMap>
</PriInfo>
```

PRI generation certainly requires the Foundation package.

If I right-click on the class lib project and click on Pack, here's the resulting nupkg:
![image](https://user-images.githubusercontent.com/35987549/126085268-f45b129c-dbb4-4c13-a85b-2012c0d66bc3.png)

I hope that addresses your problem. If it doesn't, feel free to reach back out to us :)

**Comment by rohanp-msft** [comment]
Hi @edoust, can we close this issue now?

**Comment by edoust** [comment]
Hi @rohanp-msft , thanks for the detailed reply, this issue is solved for me. 

But in general I think it would be nice if build & packaging would also work correctly if the references to ProjectReunion comes from an imported nuget or a direct project reference rather than from the project that is built (or as an alternative, a build warning / error would be helpful for tracking down the issue)

**Comment by rohanp-msft** [comment]
> Hi @rohanp-msft , thanks for the detailed reply, this issue is solved for me.
> 
> But in general I think it would be nice if build & packaging would also work correctly if the references to ProjectReunion comes from an imported nuget or a direct project reference rather than from the project that is built (or as an alternative, a build warning / error would be helpful for tracking down the issue)

Will pass the feedback along to our PMs. Thanks.

**Comment by andrewleader** [comment]
Thanks for this feedback @edoust, agreed! We've captured your feedback with a new issue in the Windows App SDK here: https://github.com/microsoft/WindowsAppSDK/issues/1111
