### ISSUE TITLE
Application Crashes when selecting a NumberBox using PenMount Windows Universal Driver in version 2.6.0 and higher

### ISSUE THREAD

**Issue by BalazsSzekeres** [microsoft/microsoft-ui-xaml#5424]
**Describe the bug**
When a NumberBox is selected using a touchscreen driven by the PenMount Windows Universal Driver, the application crashes. If the driver is not in touch but mouse mode, the crash does not happen. If to the same device a mouse is connected, it works as expected, but again as soon as a NumberBox is tapped via the touchscreen, the application crashes. The same field works fine on a Dell XPS 15 touchscreen, as well as in the built-in Simulator. Also, this issue is only apparent in 2.6.0 and higher.

Using Remote debugger the following exception is registered: 	AppName..exe!AppName..App.InitializeComponent.AnonymousMethod__8_0(object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e) Line 53	C#

**Steps to reproduce the bug**
1. Create a NumberBox field.
2. Tap on the field using a PenMount Windows Universal Driver-driven touchscreen, in touch mode.

**Expected behavior**
The NumberBox field should be selected, and the application should continue.

NuGet package version: 
[Microsoft.UI.Xaml.2.6.0]
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
UWP

Device:
Advantech PPC-3100-3S51

Windows 10 version:
Windows 10 Enterprise LTSC 10.0.17763 Update 2021-07

**Comment by StephenLPeters** [comment]
Very strange, @BalazsSzekeres to be clear you are not able to produce the crash with a generic touch screen, only with PenMount acting as touch?  Could you by change get a call stack or a crash dump to provide us? tracking down a repro for this seems challenging.

**Comment by BalazsSzekeres** [comment]
Hi @StephenLPeters, I am currently on holiday, I will get back to you with a crash dump next week!
