### ISSUE TITLE
RichTextBlock crash bug

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5425]
repo: https://github.com/HppZ/RichTextBlockBug
steps: https://user-images.githubusercontent.com/12285582/125070920-2c4b4980-e0eb-11eb-82ab-f3ad87f74058.mp4

**Comment by StephenLPeters** [comment]
@codendone and @Austin-Lamb looks like RichTextBlock is crashing trying to draw the focus rect after clicking on it continuously.  Note that this is a system xaml project. 

@HppZ what version of windows are you seeing this crash on?

**Comment by HppZ** [comment]
latest

________________________________
发件人: Stephen L Peters ***@***.***>
发送时间: Tuesday, July 13, 2021 8:28:28 AM
收件人: microsoft/microsoft-ui-xaml ***@***.***>
抄送: HppZ ***@***.***>; Mention ***@***.***>
主题: Re: [microsoft/microsoft-ui-xaml] RichTextBlock crash bug (#5425)


@codendone<https://github.com/codendone> and @Austin-Lamb<https://github.com/Austin-Lamb> looks like RichTextBlock is crashing trying to draw the focus rect after clicking on it continuously. Note that this is a system xaml project.

@HppZ<https://github.com/HppZ> what version of windows are you seeing this crash on?

―

**Comment by HppZ** [comment]
19042.985

**Comment by HppZ** [comment]
too manys bugs in XAML, it is bad.

**Comment by codendone** [comment]
Thanks for reporting this! I debugged through your repro and this is a bug in RichTextBlockOverflow, which is over-releasing the tapped Hyperlink.

**Comment by HppZ** [comment]
@codendone 
will the fix be released?

**Comment by codendone** [comment]
The fix is in for the Windows App SDK 1.0 coming later this year, and is fixed in the OS for a future release of Windows (no ETA available for this).
