### ISSUE TITLE
NavigationView pane is not displayed when setting display mode to left while the pane is opened

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#5426]
**Describe the bug**
I discovered this issue in my application but it can be reproduced using the _XAML controls gallery_ application. If we maximize the window while the left navigation pane is opened. The pane stays in _left minimal_ mode instead of being displayed in _left_ mode.

**Steps to reproduce the bug**

1. Open XAML control gallery application in windowed mode
2. If needed, resize the window so the navigation view is displayed in _left minimal_ mode
![image](https://user-images.githubusercontent.com/20152272/125080278-ec716b80-e0c4-11eb-9afc-be086fb436e6.png)

3. Click on the hamburger button to open the left nav panel
![image](https://user-images.githubusercontent.com/20152272/125080354-014dff00-e0c5-11eb-875a-fab6dc6cb1e9.png)

4. Click on the window's maximize button

**Actual behavior**
The navigation panel is displayed in *left minimal* mode instead of *left* mode.
![image](https://user-images.githubusercontent.com/20152272/125080435-14f96580-e0c5-11eb-966e-9f3152e9e21f.png)

If we look at the content background, we can also notice that there is something incorrect with the image and the content.

**Expected behavior**
The navigation panel is displayed in *left* mode. Basically doing the same thing than when the navigation panel is not opened.
![image](https://user-images.githubusercontent.com/20152272/125080614-4f630280-e0c5-11eb-88b7-16ea713e2939.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

**Comment by StephenLPeters** [comment]
This is not occuring for me with the XCG version 1.2.19.0  Can you confirm that WinUI 2.6.1 does not solve your issue @vgromfeld ?
