### ISSUE TITLE
Access Violation with New App

### ISSUE THREAD

**Issue by kinahawi** [microsoft/microsoft-ui-xaml#5427]
After creating a brand new, unmodified blank WinUI desktop app, I attempt to run the app and receive the following:
Exception thrown at 0x00007FFA34DA26C3 (ntdll.dll) in HelloWinUI.exe: 0xC0000005: Access violation reading location 0x00007FFA34F70FFF.

I am using Project Reunion Extension version 0.8.0.46122163 in Visual Studio 2019 16.10.3.
The only Nuget packages are those setup on project creation. All are version 0.8.0 (stable). The packages are:
Microsoft.ProjectReunion, Microsoft.ProjectReunion.Foundation, Microsoft.ProjectReunion.WinUI

Windows version is Microsoft Windows 10 Pro, 10.0.19043

Here is the full output from building the project
Build started...
1>------ Build started: Project: HelloWinUI, Configuration: Debug x86 ------
1>C:\Users\bill\source\repos\HelloWinUI\HelloWinUI\HelloWinUI\MainWindow.xaml.cs(29,13,29,29): warning CA1416: This call site is reachable on all platforms. 'ContentControl.Content.set' is only supported on: 'Windows'.
1>C:\Users\bill\source\repos\HelloWinUI\HelloWinUI\HelloWinUI\App.xaml.cs(42,13,42,32): warning CA1416: This call site is reachable on all platforms. 'Window.Activate()' is only supported on: 'Windows'.
1>HelloWinUI -> C:\Users\bill\source\repos\HelloWinUI\HelloWinUI\HelloWinUI\bin\x86\Debug\net5.0-windows10.0.19041.0\HelloWinUI.dll
1>Done building project "HelloWinUI.csproj".
2>------ Build started: Project: HelloWinUI (Package), Configuration: Debug x86 ------
2>C:\Users\bill\source\repos\HelloWinUI\HelloWinUI\HelloWinUI (Package)\HelloWinUI (Package).wapproj : warning NU1701: Package 'Microsoft.ProjectReunion.InteractiveExperiences 0.8.0' was restored using 'net5.0-windows10.0.19041, .NETCoreApp,Version=v3.1, .NETCoreApp,Version=v3.0, .NETCoreApp,Version=v2.0, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, net5.0-windows10.0.17763, net6.0-windows10.0.17763, .NETFramework,Version=v4.6.1' instead of the project target framework 'UAP,Version=v10.0.17763'. This package may not be fully compatible with your project.
2>Done building project "HelloWinUI (Package).wapproj".
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Here is the full output from running the app:
'HelloWinUI.exe' (Win32): Loaded 'C:\Users\bill\source\repos\HelloWinUI\HelloWinUI\HelloWinUI (Package)\bin\x64\Debug\AppX\HelloWinUI\HelloWinUI.exe'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\WRDll.x64.dll'. 
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\ProgramData\WRCore\CoreService\Component\FCS\WRFCSUser.x64.dll'. 
'HelloWinUI.exe' (Win32): Loaded 'C:\Program Files\dotnet\host\fxr\5.0.7\hostfxr.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.7\hostpolicy.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.7\coreclr.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Symbols loaded.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Symbols loaded.
The thread 0x5124 has exited with code 0 (0x0).
'HelloWinUI.exe' (Win32): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.7\System.Private.CoreLib.dll'. 
'HelloWinUI.exe' (Win32): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.7\clrjit.dll'. Symbols loaded.
'HelloWinUI.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.7\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'HelloWinUI.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Symbols loaded.
Exception thrown at 0x00000109EC520003 in HelloWinUI.exe: 0xC000001D: Illegal Instruction.
The Common Language Runtime cannot stop at this exception. Common causes include: incorrect COM interop marshalling and memory corruption. To investigate further use native-only debugging.
Exception thrown at 0x00007FFA34DA26C3 (ntdll.dll) in HelloWinUI.exe: 0xC0000005: Access violation reading location 0x00007FFA34F70FFF.

**Comment by StephenLPeters** [comment]
@alwu-msft do we have known issues in this space?

**Comment by alwu-msft** [comment]
The only one I'm aware of involves Windows 11 which isn't in play here. @ShashankNay did you encounter anything like the issue reported here during manual testing?

**Comment by kinahawi** [comment]
Is there any more data I can collect to help understand this issue? I'd really like to be able to make some progress.
