### ISSUE TITLE
KeyboardAccelerator for MenuFlyoutItem uses stale CanExecute state

### ISSUE THREAD

**Issue by lmadhavan** [microsoft/microsoft-ui-xaml#5437]
**Describe the bug**
A keyboard accelerator attached to a MenuFlyoutItem only works if the command was enabled the last time the menu was opened. If the command was previously disabled and then enabled at a later point (by raising CanExecuteChanged), the accelerator does not work until the menu is manually opened again (which triggers a call to CanExecute). Having to manually open the menu every time defeats the purpose of having an accelerator in the first place. Interestingly, the accelerator works fine if the menu is never opened in the first place.

**Steps to reproduce the bug**
Sample code: https://gist.github.com/lmadhavan/293d786795136e2a735c9bc8af073888

1. Open the menu - the command will be initially disabled.
2. Close the menu and click the "Enable" button.
3. Press Ctrl+T (accelerator key) - nothing happens.
4. Open the menu again - the command will be enabled.
5. Close the menu and press Ctrl+T - console will show that both CanExecute and Execute were called.
6. Continue to press Ctrl+T while toggling between "Enable" and "Disable" - console will show that CanExecute is called every single time and based on the outcome, Execute is called.

**Expected behavior**
In step 3 above, the command should be executed properly. The keyboard accelerator should not be tied to the enabled state of the menu item (step 6 shows that the framework always calls CanExecute before Execute, so there is no reason to disable the accelerator binding when the menu item is disabled).

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.2]
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 (19043)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by lmadhavan** [comment]
I am currently working around this issue by cloning all the keyboard accelerators in my menu onto another container element and having them directly invoke the corresponding commands: https://gist.github.com/lmadhavan/4f56a403bc8fbbda342f41e2657fc0a3

**Comment by StephenLPeters** [comment]
@Austin-Lamb FYI
