### ISSUE TITLE
CalendarView focus visual is cut off for dates at the top when selected using keyboard

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#5439]
**Describe the bug**

**Steps to reproduce the bug**

1. Open xaml controls gallery
2. Navigate to CalendarView page
3. Tab to date picker, use arrow keys to select a date at the top or bottom
4. Focus visual is cut off

**Expected behavior**

The full circle should be rendered and not clipped at the top.

**Screenshots**

![image](https://user-images.githubusercontent.com/59544401/125226592-381f4300-e286-11eb-958e-be81a35d5d8b.png)

Also reproducible in the windows 11 preview calendar.
![image](https://user-images.githubusercontent.com/59544401/125226672-59802f00-e286-11eb-867e-4cb2bcb7d9ce.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.65)              | ye   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@RBrid FYI

**Comment by RBrid** [comment]
The clipping at the top is an old bug that repros in Win10: 
![image](https://user-images.githubusercontent.com/36547063/125371552-d5858000-e335-11eb-9ae0-85d504332a80.png)

**Comment by StephenLPeters** [comment]
IMO it looks worse with rounded focus rect.
