### ISSUE TITLE
ItemsRepeater within ListView causing layout cycles

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#544]
**Describe the bug**
"Layout cycle detected" exception when using ItemsRepeater inside a ListView

**Steps to reproduce the bug**
1. Create an app which uses a ListView, e.g. https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlBottomUpList, using the Incremental Loading example
2. Add an ItemsRepeater control to the data template for the ListViewItems and bind the ItemsSource to a value.
3. Run the app. As enough items are added to require scrolling the list, the layout cycle exception fires.

**Expected behavior**
XAML should handle this scenario without crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/45607479/55908591-b3b55580-5b8e-11e9-8f56-4d163812a7da.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18xxx, Latest)                   | Yes   |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by micahl** [comment]
This issue should be fixed by #557

**Comment by jevansaks** [comment]
Per @micahl's comment, I"m going to close this. Please let us know if you still see it?
