### ISSUE TITLE
MediaPlayerElement transport controls are cutoff at smaller sizes

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#5441]
**Describe the bug**

At smaller sizes (< 350 px), the right side of the media controls for the MediaPlayerElement controls will be cutoff. The content itself shrinks to fit as expected.

**Steps to reproduce the bug**

1. Create new blank uwp projects, set up with winui 2.6
2. Add media player elements with widths of 350, 300, 250, and 200, and enable media player transport controls
3. see cutoff at different sizes

Alternatively, here's a repro app. 

[Repro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6798771/Repro.zip)

**Expected behavior**
The control panel size should be shrunk to meet the size.

**Screenshots**

![image](https://user-images.githubusercontent.com/59544401/125234673-01e9bf80-e296-11eb-95af-193f015d4eb7.png)

![image](https://user-images.githubusercontent.com/59544401/125235598-90127580-e297-11eb-8c88-4467c31f611d.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.65)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Ye |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Side note: the slider is also cut off slightly, may not be related though.

**Comment by StephenLPeters** [comment]
The slider issue has been fixed.

**Comment by StephenLPeters** [comment]
@karenbtlai and @alejo4000 looks like we added a MinWidth to MTC here: https://github.com/microsoft/microsoft-ui-xaml/pull/5090.

MediaPlayerElement's template is a grid which contains a content presenter which contains a MTC.  By setting the width of the MediaPlayerElement we impose a clip on all children which expand beyond that footprint, which because of the minwidth we introduced clips the content with this style.

With the previous style the content shrinks instead of clips: 
![image](https://user-images.githubusercontent.com/7758786/125370092-8c7ffc80-e332-11eb-98c8-8eb1e34677a6.png)

**Comment by ranjeshj** [comment]
Could you update the MinWidth to override this ?

**Comment by winston-de** [comment]
> Could you update the MinWidth to override this ?

Sorry for the delay, I forgot to test this. Yes, this fixed it thank you.
![image](https://user-images.githubusercontent.com/59544401/129601880-30b31f5a-5d88-4eef-8919-d49287a4cae9.png)
