### ISSUE TITLE
Message = "Failed to assign to property 'Microsoft.UI.Xaml.Media.AcrylicBrush.BackgroundSource'. [Line: 978 Position: 73]"

### ISSUE THREAD

**Issue by hezz123456** [microsoft/microsoft-ui-xaml#5443]
An error occurred after updating to WinUI2.6 Message = "Failed to assign to property 'Microsoft.UI.Xaml.Media.AcrylicBrush.BackgroundSource'. [Line: 978 Position: 73]"

**Comment by StephenLPeters** [comment]
@hezz123456 unfortunately this isn't enough information for us to act on.  Can you ensure that the issue is still present in Winui 2.6.1 and if so provide a repro app or informations about what you are doing to cause the issue? Thanks!

**Comment by hezz123456** [comment]
@StephenLPeters The problem that persisted after the 2.6.1 upgrade was the problem that occurred when the 2.1 upgrade to the 2.6.0 release was running the program

**Comment by hezz123456** [comment]
The issue was resolved after upgrading to 2.6.1-prerelease.210709001 without any code changes but in 2.6.0 and 2.6.1 the error Message = "Failed to assign to property'Microsoft. UI. Xaml. Media. AcrylicBrush. BackgroundSource'. [Line: 978 Position: 73] "I don't know why only prerelease works

**Comment by StephenLPeters** [comment]
Weird, @hezz123456 could you provide a repro application, I'm not able to reproduce this issue.

@jevansaks Any idea why the framework package would cause an issue the nuget packaged wouldn't here?

**Comment by JanRajnoha** [comment]
This issue is happening on WinUI 3 / Windows App SDK 0.8.1 too

**Comment by michael-hawker** [comment]
@JanRajnoha do you have more details/example of the XAML/code producing this issue?

**Comment by JanRajnoha** [comment]
@michael-hawker I don't have any specific example app, maybe same example as for bug from CsWinRt or snippet of code, which is using AcrylicBrush
