### ISSUE TITLE
NumberBox SpinButtonPlacementMode=Inline don't show up and down Buttons on Start

### ISSUE THREAD

**Issue by HuHe86** [microsoft/microsoft-ui-xaml#5444]
If i choose spinButtonPlacementMode.Inline the up and down buttons aren't visible.

I fixed the issue as follows
private void NumberBox_LayoutUpdated(object sender, object e)
        {
            NumberBox_.SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Inline;
        }

WinUI NuGet package version 2.6.1

**Comment by StephenLPeters** [comment]
@HuHe86 do you know if this regressed? did it work in winui2.5

@karenbtlai we made a change to inline numberbox's recently: https://github.com/microsoft/microsoft-ui-xaml/pull/5331/files could we have regressed this?

**Comment by HuHe86** [comment]
It worked in winui2.5.
