### ISSUE TITLE
Snooze and Dismiss buttons on toast notification

### ISSUE THREAD

**Issue by Naveen-chawla** [microsoft/microsoft-ui-xaml#5449]
**Query:**
We need to integrate snooze and dismiss buttons in toast notification. But could not link these buttons in WinUI project. So, Please let me know snooze and dismiss buttons in toast notification and toast notification customization in WinUI like below image.

**Required Image:**
![image](https://user-images.githubusercontent.com/61832185/125403477-30b98000-e3d3-11eb-932a-dec6de22a729.png)

<html>
<body>
<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px;"><strong style="box-sizing: border-box; font-weight: 600;">Version Info</strong><br style="box-sizing: border-box;">NuGet package version:<br style="box-sizing: border-box;">[WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview]</p><p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px;">Windows app type:</p>

UWP | Win32
-- | --
Yes | Yes

<table role="table" style="box-sizing: border-box; border-collapse: collapse; border-spacing: 0px; margin-bottom: 0px !important; margin-top: 0px; display: block; max-width: 100%; overflow: auto; width: max-content;"><thead style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--color-bg-primary); border-top: 1px solid var(--color-markdown-table-tr-border);"><th align="left" style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border: 1px solid var(--color-markdown-table-border);">Device form factor</th><th align="left" style="box-sizing: border-box; padding: 6px 13px; font-weight: 600; border: 1px solid var(--color-markdown-table-border);">Saw the problem?</th></tr></thead><tbody style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--color-bg-primary); border-top: 1px solid var(--color-markdown-table-tr-border);"><td align="left" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-markdown-table-border);">Desktop</td><td align="left" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-markdown-table-border);">Yes</td></tr><tr style="box-sizing: border-box; background-color: var(--color-bg-tertiary); border-top: 1px solid var(--color-markdown-table-tr-border);"><td align="left" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-markdown-table-border);">Xbox</td><td align="left" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-markdown-table-border);"></td></tr><tr style="box-sizing: border-box; background-color: var(--color-bg-primary); border-top: 1px solid var(--color-markdown-table-tr-border);"><td align="left" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-markdown-table-border);">Surface Hub</td><td align="left" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-markdown-table-border);"></td></tr><tr style="box-sizing: border-box; background-color: var(--color-bg-tertiary); border-top: 1px solid var(--color-markdown-table-tr-border);"><td align="left" style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--color-markdown-table-border); color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">IoT</td><br class="Apple-interchange-newline">
</body>
</html>

**Comment by StephenLPeters** [comment]
@Naveen-chawla Could you please include more information about your application, the scenario, and what you were not able to achieve?

**Comment by Naveen-chawla** [comment]
@StephenLPeters, We have planned to provide reminder support from system toast notification and need to customize toast notification.
I have attached a simple sample image, Here, We need to give reminder snooze and dismiss details to customer when pressed snooze and dismiss buttons. Could you please give event details of  these toast buttons and how to trigger those events?

![image](https://user-images.githubusercontent.com/61832185/125622294-a6947448-4b79-4cf2-8f27-15b1e7c2ccde.png)

**Comment by StephenLPeters** [comment]
I've not worked with this API before but does this documentation answer your question? https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp#adding-buttons-and-inputs  I see the page say "The activation of foreground buttons are handled in the same way as the main toast body (your App.xaml.cs OnActivated will be called)." So I think you interact with them via the  OnActivated method?
