### ISSUE TITLE
WinUI Design Toolkit Bug: compact mode spaceing 

### ISSUE THREAD

**Issue by UIenhancement** [microsoft/microsoft-ui-xaml#5452]
the space within the compact mode looks very wrong! (XAML control library)
This is not yet in the design toolkit! Hopefully you can improve it 

 have a look at the redesign version on the right side that I made 🙂 the spacing looks much better 

![space](https://user-images.githubusercontent.com/83458494/125480830-01da1a7b-5723-44c7-96bf-df9ddc95044c.png)

**Comment by alejo4000** [comment]
Thanks for pointing this out, the compact sizing is not part of the Windows UI 2.6 toolkit, but it's on our radar. This may be better addressed by the XAML Controls Gallery team, reassigning to the appropriate party.

**Comment by chigy** [comment]
@UIenhancement , please open a bug in XAML Controls Gallery Git Hub.
https://github.com/microsoft/Xaml-Controls-Gallery/issues/new/choose
