### ISSUE TITLE
Xaml Internal Error error WMC9999: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

### ISSUE THREAD

**Issue by omnilogix** [microsoft/microsoft-ui-xaml#5456]
**Describe the bug**

Getting this error when compiling a Project Reunion 0.8 Desktop app.
I was doing some refactoring, and suddenly the project won't compile.  No other obvious errors.  Any help on where to start would be appreciated.

Output:
`1>\.nuget\packages\microsoft.projectreunion.winui\0.8.0\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(465,9): Xaml Internal Error error WMC9999: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.`

NuGet package version: 

![image](https://user-images.githubusercontent.com/9586533/125137265-335d6200-e0c1-11eb-88f1-7ec94671c07a.png)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

Visual Studio 2019 Preview  16.11.0 preview 2

**Comment by StephenLPeters** [comment]
Interesting, @alwu-msft know anything about this?

**Comment by alwu-msft** [comment]
@RealTommyKlein this could be an ArgumentOutOfRangeException bug in XamlCompiler's `CompileXaml` task.

**Comment by evelynwu-msft** [comment]
Closing as unfortunately this isn't actionable; I think it's likely that the error stemmed from one or more of XamlCompiler's on-disk caches having been corrupted somehow. Cleaning the solution (which would remove all of XamlCompiler's cached files) was probably sufficient with the subsequent recreation of the `.xaml` files being unnecessary to the success of the workaround.
