### ISSUE TITLE
WinUI Design Toolkit Bug:  Toolbar Textfild 

### ISSUE THREAD

**Issue by UIenhancement** [microsoft/microsoft-ui-xaml#5460]
## WinUI Toolkit Bug Report

---

![image](https://user-images.githubusercontent.com/83458494/125612556-d3e328dc-e77a-4e1b-bc61-f8a5a3d091e6.png)

**Name of component or part of Toolkit:**
Controls - Menus & Toolbars

**Describe the bug:**
auto height insed of  auto width in the textfild

**Comment by alejo4000** [comment]
Thanks for spotting this! This is on our radar, and as the toolkit evolves, issues like this will be resolved.
