### ISSUE TITLE
WinUI Design Toolkit Bug: Titlebar Controls Glyphs use 12px font, the should be 10px

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#5462]
## WinUI Toolkit Bug Report

---

![image](https://user-images.githubusercontent.com/7389110/125645506-56f67e4b-b48e-4f3a-8215-d07727ab22c1.png)

![image](https://user-images.githubusercontent.com/7389110/125645624-afb27ddb-44b5-4cdc-b684-8fe3b1654e07.png)

**Name of component or part of Toolkit:** 

Title Bar / Parts / Title Bar Caption Control Group
and
Title Bar / Parts / Title Bar Caption Control Button

**Describe the bug:** 

The Glyphs for the Icons don't align to the Pixel Grid at 12px size, but do at 10px size

**Version Info:** 

Windows UI 2.6 - Version 1.0.0 – Last updated 6/24/2021

**Additional context:** 

This applies in Standard, Tall and Future Tall modes

**Comment by alejo4000** [comment]
Thanks for catching that! The caption controls will show 10px in the next Windows UI Toolkit update.
