### ISSUE TITLE
WinUI Design Toolkit Bug: Menus do not have Icon variations

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#5463]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**

Context Menu / Context Menu
Command Bar Flyout / Command Bar Flyout
etc

**Describe the bug:**

There are variations for Radio glyphs and Check marks, but none with icon placeholders.
It has meant detaching instances to go in and manually add them.

**Version Info:**

Windows UI 2.6 - Version 1.0.0 – Last updated 6/24/2021

**Additional context:**

As well as adding in support for Font Glyphs, would it be possible to add ways to add SVG or coloured glyphs to these, so something like this can be done easier.

![image](https://user-images.githubusercontent.com/7389110/125646618-4992f259-f330-440e-9da8-f234f9fd9d68.png)

**Comment by alejo4000** [comment]
Hi mdtauk! I want to make sure I'm understanding correctly. Are you wanting to place a font icon in a Radio button or a Checkbox? And when you reference the Context Menu and Command Bar Flyouts, do you want to place a font icon in those items?

**Comment by mdtauk** [comment]
> Hi mdtauk! I want to make sure I'm understanding correctly. Are you wanting to place a font icon in a Radio button or a Checkbox? And when you reference the Context Menu and Command Bar Flyouts, do you want to place a font icon in those items?

Yes, it is not unusual to want to use Icons within a Content Menu, Menu Flyout, or a Command Bar Flyout's Secondary Items.  At the moment there are Toggles, and Indenting, but nothing with Icon placeholders.

**Comment by alejo4000** [comment]
> > Hi mdtauk! I want to make sure I'm understanding correctly. Are you wanting to place a font icon in a Radio button or a Checkbox? And when you reference the Context Menu and Command Bar Flyouts, do you want to place a font icon in those items?
> 
> Yes, it is not unusual to want to use Icons within a Content Menu, Menu Flyout, or a Command Bar Flyout's Secondary Items. At the moment there are Toggles, and Indenting, but nothing with Icon placeholders.

Adding a custom icon is not currently supported in this control in the WindowsUI 2.6 implementation. The radio glyph and check mark are the only icons available, so if you'd like to see an icon in there, breaking the instance and customizing is the way to go.
