### ISSUE TITLE
Question: Does WinUI 3 now support "dotnet build" for the ef-core add-migration command

### ISSUE THREAD

**Issue by pavll** [microsoft/microsoft-ui-xaml#5465]
Does WinUI 3 now support "dotnet build" for the ef-core add-migration command?

**Comment by MikeHillberg** [comment]
Building with the dotnet.exe CLI isn't currently supported.

**Comment by pavll** [comment]
> Building with the dotnet.exe CLI isn't currently supported.

Ok, thank you for your response.
