### ISSUE TITLE
Unable to get a simple WinUI3 project running on Windows 11

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5466]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-get-a-simple-WinUI3-project-ru/1472123)._

---
[severity:Other]
I am unable to get the default project for WinUI3 running on Windows 11.  I get a combase exception.
[2021-07-10.png](https://aka.ms/dc/file?name=B698382276a95428482332ec82aa885fb637615412504217076_2021-07-10.png&tid=698382276a95428482332ec82aa885fb637615412504217076)

---
#### Feedback Bot on 7/11/2021, 11:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MikeHillberg** [comment]
This looks like an issue with 0.8.0 on Windows 11 that's fixed in 0.8.1 that was just released yesterday. Can you give that a try?

**Comment by marb2000** [comment]
This issue has been solved in the new [service updated 0.8.1](https://www.nuget.org/packages/Microsoft.ProjectReunion.WinUI/0.8.1). 
Closing the issue.
