### ISSUE TITLE
InkToolbarCustomToggleButton not showing `Pressed` state.

### ISSUE THREAD

**Issue by RosarioPulella** [microsoft/microsoft-ui-xaml#5468]
**Describe the bug**

In https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/4092 we moved to WinUI 2.6.1 and our `InfiniteCanvas` control uses a `InkToolbarCustomToggleButton` for enabling drawing with the mouse. After updating to WinUI 2.6.1, when that button is clicked it does not show it in the `pressed` state, but it does behave normally otherwise.

**Steps to reproduce the bug**

1. Checkout the branch for https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/4092 
2. Open the project in visual studio
3. Build and Run `Microsoft.Toolkit.Uwp.SampleApp` in the project.
4. Search for and open the "InfiniteCanvas" sample in the sample app at the top right corner.
5. Click the "Hand Button".
6. See it now visually change into a clear pressed state.

**Expected behavior**

When the "Hand Button" it clicked its visual representation changes to show it is in a pressed state.

**Screenshots**

![togglebutton](https://user-images.githubusercontent.com/7164552/125676418-9063cc53-ae29-4f21-af46-69f78bdc5a8c.gif)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by beervoley** [comment]
Hi @RosarioPulella the [fix ](https://github.com/microsoft/microsoft-ui-xaml/pull/5447) was recently checked in :)

**Comment by beervoley** [comment]
@ranjeshj should I close the issue?

**Comment by michael-hawker** [comment]
@beervoley @ranjeshj is this going into a servicing release in the near future as one of our controls was effected by this upgrading for the 7.1 release of the Toolkit we're going to ship in the next month or so.
