### ISSUE TITLE
WinUI Design Toolkit Bug:  alignment Checkbox

### ISSUE THREAD

**Issue by UIenhancement** [microsoft/microsoft-ui-xaml#5476]
## WinUI Toolkit Bug Report
![image](https://user-images.githubusercontent.com/83458494/125750667-0bad6c4e-9e4e-49ec-a08b-a5a518a84bd6.png)

**Name of component or part of Toolkit:**
Checkbox with label selected

**Describe the bug:**
alignment issue

**Comment by alejo4000** [comment]
This issue has been fixed in the newest version of the toolkit.
