### ISSUE TITLE
Incorrect foreground in TextBox context menu items (Dark theme)

### ISSUE THREAD

**Issue by Alexander-Kamenchuk** [microsoft/microsoft-ui-xaml#5478]
**Describe the bug**
Hi,
The context menu items of the TexBox have a theme problem

**Steps to reproduce the bug**
```xaml
<TextBox Text="Simple TextBox" RequestedTheme="Dark"/>
```
 Right click

**Expected behavior**
Context menu in TextBox should be themed.

**Screenshots**
![imgpsh_mobile_save](https://user-images.githubusercontent.com/80826968/125766091-e085e48d-8656-47a9-8949-8a48807cb89e.jpg)

**Version Info**
NuGet package version:
[WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|     |   Yes   |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |   Yes   |
| May 2020 Update (19041)            |      |
| November 2019 Update (18363)       |      |
| May 2019 Update (18362)            |      |
| October 2018 Update (17763)        |       |
| April 2018 Update (17134)          |       |
| Fall Creators Update (16299)       |       |
| Creators Update (15063)            |       |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |    |
| Surface Hub        |  |
| IoT                |    |

**Comment by StephenLPeters** [comment]
I think this is fixed in Winui2.6 however that hasn't made it into winui3 yet.

**Comment by Alexander-Kamenchuk** [comment]
> I think this is fixed in Winui2.6 however that hasn't made it into winui3 yet.

Hi Stephen
Thanks for the quick response.
I've checked it in WinUI 2.6.
There the problem is in the "Light" theme, and in the "Dark" everything is fine.
![image](https://user-images.githubusercontent.com/80826968/125913074-7a29686c-ca41-4640-871c-d66cb54df0f1.png)
