### ISSUE TITLE
Proposal: Add byte[] to image converter

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [microsoft/microsoft-ui-xaml#5479]
## Rationale
byte[] to image converter is one of the most used ones in xaml and it would be nice to not have to implement it in almost every new project like your every kind of the visibility converter

**Comment by mrlacey** [comment]
Something for the https://github.com/CommunityToolkit/WindowsCommunityToolkit ???

**Comment by ahmed-abdelrazek** [comment]
> 
> 
> Something for the https://github.com/CommunityToolkit/WindowsCommunityToolkit ???

yep
