### ISSUE TITLE
XamlTypeInfo not getting updated when switching git branches

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#5481]
Visual Studio version: 16.10.3

I have a repo that has two branches with different features. In short words, in `master` branch, the exe project references 1 class library project. In `develop` branch, it references 1 more.

This only happens for 0.8.x. Doesn't happen for 0.5.x.

When switching from `develop` to `master`, the `XamlTypeInfo` contains types only in develop branch and causes build error. When switching from `master` to `develop`, there's no error, but every control in the additional project silently won't load.
Only rebuilding the exe project updates `XamlTypeInfo.g.cs`.

**Comment by StephenLPeters** [comment]
@alwu-msft FYI
