### ISSUE TITLE
👨‍💻☎ WinUI Community Call: August 18, 2021  

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#5482]
### This live event has now ended, but you can view the recording on YouTube at the link below. If you didn't get your question answered, feel free to [open it up as a question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) on this repo. Thanks all for joining!

**https://youtu.be/RcA89AnGdJw**

# Details
Date: Wednesday, August 18, 2021
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

# Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. 

### **Agenda**

- Intro, general updates
- Recent WinUI releases
- Demos of new experimental features
- Meet the Interactive Experience Platform team
- Q&A
    - Questions and topic requests can be pre-submitted by commenting them on this GitHub issue
    - Questions can be asked live in the YouTube livestream's comment section

### **Q&A Code of Conduct**
- To help ensure Q&A remains beneficial for the majority of the call's developer audience, please consider whether your question could be framed so that it might be more broadly relevant to our larger developer audience by ensuring it is reasonably concise, broadly beneficial, well-suited for the fast-paced live Q&A format, or able to spark open ended discussion.  
- Please understand some questions are not well-suited for the fast-paced liacve Q&A format and should be filed as standalone [Discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=discussion&template=discussion.md&title=Discussion%3A+%5Byour+discussion+title%5D) or [Question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) issues where they can be most appropriately handled. Excluding presentation topic requests, this generally includes requests for dedicated follow-ups or technically complex questions that require investigative time or expertise not included in this month's guest list.

### Leave us your questions in the comments on this issue or live in the YouTube chat during the stream!

**Comment by Lorymi** [comment]
I am surprised when I see that winforms has started to receive updates, but wpf and uwp have become ghosts and no one is responsible for these two!

Four years ago, a request was made that we will read in 2021,  it is funny (Especially for non-.NET developers)
https://github.com/dotnet/wpf/issues/91

Instead of fixing the basic wpf and uwp problems, ask us about WINUI programs? I wish you cared about the desktop as much as you care about ASP


I think the biggest question right now is what will happen to UWP?  Do you still avoid answering?  Why should UWP be removed from the WINUI roadmap?  And then tell us, maybe one day we will think about it again ?!

https://github.com/microsoft/WindowsAppSDK/discussions/1055

Make no mistake, I'm a fan of Microsoft and .NET, but your decisions always disappoint us users

Take a look at the Flutter project on github to see how active it is and how much people are helping to develop it. or ReactNative??
Now compare the two with MAUI and Xamarin!!!

The only reason is the name Microsoft because it always obsolete a system after a while and does not provide a reason for that

You will obsolete the same WINUI for another two years and put your users in a dilemma

**Comment by groovykool** [comment]
What should a UWP developer that uses Map Control, Win2D and Ink Canvas do considering UWP .NET and C# are 2 full versions behind?

Why should Desktop apps that are currently in development using UWP or WFP (Desktop Bridge) move to WinUI3 and WindowAppSDK considering the huge number of bugs and missing functionality in them?

What are the current requirements for Desktop apps to be submitted to the Windows store?

**Comment by robloo** [comment]
Are additional controls still going to be open sourced and added here to the WinUI library? i.e. Grid source code, CommandBar source code, etc. Or are all controls not already here going to remain in WinUI3-only indefinitely.

Is there still a plan to open source WinUI3? I kind-of expect that promise to be revoked at this point. All the warning signs are there.

**Comment by ghost1372** [comment]
When will we see WinUI 2.6 visual styles in WinUI 3? When will the preview release?

**Comment by mrlacey** [comment]
@anawishnoff  As there's not going to be a July call, you might want to remove the scheduled YouTube entry: https://www.youtube.com/watch?v=KveLAGNafdw 
Also, the issue for the June call is still pinned in the repo.

**Comment by anawishnoff** [comment]
@mrlacey Thanks! Just addressed those issues.

**Comment by pjmlp** [comment]
With the release of [Microsoft Game Developer Kit (GDK)](https://developer.microsoft.com/en-us/games/blog/meet-the-microsoft-game-developer-kit-gdk), UWP has been made into legacy from XBox team point of view:

>  UWP apps and games are community-supported only; partners inside Xbox managed programs (Xbox, Xbox Game Pass, Xbox Game Streaming) should use Microsoft Win32 + GDK.

HoloLens team is also [moving away from UWP](https://docs.microsoft.com/en-gb/windows/mixed-reality/develop/platform-capabilities-and-apis/using-xaml-with-holographic-directx-apps).

> This article relates to the legacy WinRT native APIs. For new native app projects, we recommend using the OpenXR API.

Using XBox and HoloLens as examples why UWP still matters doesn't seem to be the case as per respective teams communication channels and own roadmaps.

So can we actually get an official coherent message on what is happening with UWP across the board?

**Comment by Symbai** [comment]
When can we expect new features for WPF? Just to name a few: Folder dialog, trimming support, AOT support, Acryl brush, Directx 11 + 12 support, bug-free WindowChrome class...

**Comment by mrlacey** [comment]
Question for the call (or anywhere else as an answer would be really enlightening)
[Apparently, it is by design](https://github.com/microsoft/microsoft-ui-xaml/issues/5487#issuecomment-884540972) that a read-only textbox looks the same as one that can be edited. Why is this the case?
I think this is important because:

**Comment by shaheedmalik** [comment]
When is WinUI 3 coming to UWP?

When is WinUI 3 going to be open sourced?

**Comment by Marv51** [comment]
From the last call:

Can you speak about CsWinRT again? It seems responsible for a large number of the really critical bugs. The team seems super small and future of WinUI seems to depend on getting CsWinRT right. Is the feeling of the team that the backlog of major bugs is decreasing?

**Comment by Marv51** [comment]
What factors went into the decision to deviate from the planned "stable releases roughly every three months" to now having 5 months between 0.8 and 1.0. With the Windows 11 design refresh and the increasing amount of developer interest it seems like a sub-optimal time to hold features for a big 1.0 release. 

 To me a smaller 0.9 release in September would have been preferable.

**Comment by pjmlp** [comment]
@Marv51 Given the stagnation of C++/WinRT  Visual Studio tooling in spite of Microsoft decided to deprecate C++/CX, **4 years ago**, I wouldn't have higher expectations for CsWinRT to have a better future.

**Comment by yoshiask** [comment]
> HoloLens team is also [moving away from UWP](https://docs.microsoft.com/en-gb/windows/mixed-reality/develop/platform-capabilities-and-apis/using-xaml-with-holographic-directx-apps).
> 
> > This article relates to the legacy WinRT native APIs. For new native app projects, we recommend using the OpenXR API.

For what it's worth, it looks like OpenXR still uses UWP to some extent under the hood:
https://github.com/microsoft/OpenXR-MixedReality/blob/main/samples/BasicXrApp/BasicXrApp_uwp.vcxproj

**Comment by groovykool** [comment]
> When is WinUI 3 coming to UWP?
Never

https://github.com/microsoft/microsoft-ui-xaml/issues/5484

**Comment by yoshiask** [comment]
There's really not much need for WinUI 3 on UWP. WinUI 2.x has most of the same features, and is still getting updates for the foreseeable future.

**Comment by pjmlp** [comment]
@yoshiask The UWP workload is for legacy applications.

https://docs.microsoft.com/en-us/windows/mixed-reality/develop/choosing-an-engine

And had you bothered to actually read the C++ source code from BasicXrApp instead of giving us the project file, you would have noticed that there is zero UWP code there, the sample has been migrated to OpenXR, and those UWP references are leftovers from the migration.

**Comment by khdc** [comment]
This might be a dumb question, but will you be sticking with the name "WinUI" moving forward, or is there any potential name changes since you are part of the Windows App SDK?

The reason why I ask, is that I am preparing to build my company's internal UX Toolkit and would hate to have my repo and namespaces have the WinUI name it them if it's going to change in the near future. 🤣

**Comment by terrycox** [comment]
There appear to be TreeView behavior changes from WinUI 3 0.5 and 0.8 as regards node selection. Can someone comment on this?

**Comment by Lukespacewalker** [comment]
When will Mica material be available in WinUI 3.0 ?

**Comment by christiannagel** [comment]
When can we expect a fix with the incompatibility of the Identity Client package?
#5143

**Comment by christiannagel** [comment]
It would be great to have AppCenter support for WinUI #5343

**Comment by JanRajnoha** [comment]
WinUI currently have 2 critical bugs for me. The first is bug related to XAML Parse exception, which have many reasons why is thrown, and second is in CsWinRt related to null reference exception in PropertyChanged. This two bugs, for me, are only reason, why our app couldn't be released. I hope, you and CsWinRt team will solve it ASAP.

**Comment by Marv51** [comment]
@christiannagel In https://github.com/microsoft/appcenter-sdk-dotnet/issues/1523 the AppCenter SDK has been working on WinUI and there is a promise to ship next month.

**Comment by LadderLogic** [comment]
Hello. Could y'all please post those links that were part of the stream here? The links didn't get through the youtube. I am specifically interested in Lifted Comp API documentation link. 
Cheers!

**Comment by anawishnoff** [comment]
Sure @LadderLogic - I think this is what we were trying to link you! [Microsoft.UI.Composition Namespace](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.composition?view=winui-3.0)

**Comment by Poopooracoocoo** [comment]
The call is over but I've gotta say this. What the f do y'all wanna do with UWP and your various UI frameworks? And if UWP _is_ dead, what happens to React Native Windows? What a mess.

**Comment by terrycox** [comment]
My apologies for my earlier question. The Treeview behavior issue I thought I had was really a coding issue on my part. WinUI 3 marches on; keep up the good work.

**Comment by terrycox** [comment]
I had asked on the Github WCT discussion thread about the plan for the Toolkit to work with Windows App SDK 1.0 experimental. Here's the reply:


@michael-hawker
michael-hawker
4 days ago
Maintainer
Author
We're waiting for WinUI 3 to support the WinUI 2.6 styles as we just updated to reference those. Once WinUI 3 releases a preview or stable build with support for those, we'll release an updated version of the Toolkit packages for it.

Until then our current version is for the 0.8 release as per the WinUI release notes.

**Comment by groovykool** [comment]
> There's really not much need for WinUI 3 on UWP. WinUI 2.x has most of the same features, and is still getting updates for the foreseeable future.

Quoting Ryan Demopoulos
"As to why someone might target WinUI 3 today, there are several reasons and advantages: the mixture of Win32 support (for example, so you can use libraries & APIs that can’t be used in UWP), plus a modern set of Fluent controls & styles, plus Webview2, plus modern .NET, is a compelling combination for some app authors already."

**Comment by pjmlp** [comment]
Meanwhile they still don't know what to do with Win2D, and expect another reboot if Windows 11 does another Windows 8.
