### ISSUE TITLE
Unit Testing WinUI3 in UWP Applications with MSTest

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5483]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unit-Testing-WinUI3-in-UWP-Applications-/1416652)._

---
! [image.png] (https://aka.ms/dc/image?name=B08a84e72d7b54200b805a2782e969890637560777176460481_20210508-093516-image.png&tid=08a84e72d7b54200b805a2782e969890637560777176460481)

---
#### Feedback Bot on 5/9/2021, 11:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by fabiant3** [comment]
UWP is not a scenario we currently support with WinUI3.
