### ISSUE TITLE
What should a UWP developer that uses Map Control, Win2D and Ink Canvas do considering UWP .NET and C# are 2 full versions behind?

### ISSUE THREAD

**Issue by groovykool** [microsoft/microsoft-ui-xaml#5484]
What should a UWP developer that uses Map Control, Win2D and Ink Canvas do considering UWP .NET and C# are 2 full versions behind?

Why should Desktop apps that are currently in development using UWP or WPF (Desktop Bridge) move to WinUI3 and WindowAppSDK considering the huge number of bugs and missing functionality in them?

What are the current requirements for Desktop apps to be submitted to the Windows store?

**Comment by StephenLPeters** [comment]
@ryandemopoulos @MikeHillberg

**Comment by groovykool** [comment]
Crickets.....

**Comment by ryandemopoulos** [comment]
> What should a UWP developer that uses Map Control, Win2D and Ink Canvas do considering UWP .NET and C# are 2 full versions behind?

If the UWP developer is happy with those controls & capabilities, they should feel free to just keep using them.  If there is a desire to move to newer versions of .NET/C#, then WinUI 3 is planning to add support for most/all of these in future releases – our roadmap can be found [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md).  Of the technologies you mentioned, I suspect Win2D will be the first to be made available for WinUI 3 apps, and we’ll address MapControl and InkCanvas as soon as we can do so while weighing the many other asks from our customers.

> Why should Desktop apps that are currently in development using UWP or WPF (Desktop Bridge) move to WinUI3 and WindowAppSDK considering the huge number of bugs and missing functionality in them?

It’s worth stating upfront that developers should pick the best platform for their needs, which may not be WinUI 3.  Existing investments in UWP and WPF – or even new investments – make sense for many situations; people should use WinUI 3 if it offers them some benefit they care about that WinUI 3 doesn’t yet have.  

As to why someone might target WinUI 3 today, there are several reasons and advantages: the mixture of Win32 support (for example, so you can use libraries & APIs that can’t be used in UWP), plus a modern set of Fluent controls & styles, plus Webview2, plus modern .NET, is a compelling combination for some app authors already.  Later this year we’ll also be adding unpackaged support (for those that don’t want to use MSIX) and other enhancements found on the roadmap I linked above.  A lot has changed – and continues to be changed – under the hood for WinUI 3.  Decoupling from the OS involves a ton of re-architecture to how pixels are drawn, how input works, how we ship and service the product, tooling, and more – all this change has resulted in bugs that we’re trying to address as quickly as possible.

> What are the current requirements for Desktop apps to be submitted to the Windows store?

This repo – and my expertise specifically – focuses on WinUI 3, but I chatted with some colleagues and they gave me a few links that may be useful to you.  Let me know if this isn’t quite what you were looking for or if your question meant something else:

- [Submit your MSI or EXE app to the Microsoft Store | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/publish/msiexe/overview)
    - Specific requirements captured in here: [The MSI or EXE app certification process | Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/publish/msiexe/the-app-certification-process)
- [This article](https://developer.microsoft.com/en-us/microsoft-store/desktop-apps/) includes a video walking through the publication process
- Review [Microsoft Store Policies](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies?redirectedfrom=MSDN) and [App Developer Agreement](https://go.microsoft.com/fwlink/?linkid=528905) (see “Exhibit E” for specifics on Win32 apps)

**Comment by groovykool** [comment]
Thank you for the the response.  I guess its time to abandon UWP and hope for a stable Windows App SDK 1.0.

**Comment by mdtauk** [comment]
> Thank you for the the response. I guess its time to abandon UWP and hope for a stable Windows App SDK 1.0.

Or continue supporting your UWP apps until Windows App SDK has the features you need, then begin transferring the codebase and XAML.
