### ISSUE TITLE
Win32 default title bar issues

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5486]
I've noticed some issues in the default Win32 title bar (at least on Windows 11).
1. When maximized, the close button is not exactly at the end but rather a little to the right. This is inconsistent with modern apps.
2. The title bar icon has no spacing from the left when maximized but it moves when not maximized. In my opinion, it should stay in the same place.
3. WinUI 3 - although the default taskbar has a dark mode version, it isn't enabled automatically by WinUI and requires app developers to do which most won't bother.
4. The size of the caption buttons change when maximized and when resized. The size should stay constant like UWP apps.

**Comment by sylveon** [comment]
UWP XAML also needs to be loaded in every process to render that tooltip. Not a good solution considering how high overhead it is.
