### ISSUE TITLE
NUGET package cannot find WinUI.

### ISSUE THREAD

**Issue by apkqiu** [microsoft/microsoft-ui-xaml#5489]
Steps to reproduce:
1. Right click on my APP project.
2. Click "Manage NUGET Packages".
3. Click "Browse" on the pop-up interface.
4. Enter "WinUI" in the search box.
5. The search results show: no results.

**Comment by apkqiu** [comment]
I found it later. I typed "Windows.UI" and there is an integrated package.

**Comment by apkqiu** [comment]
Oh that's not.

**Comment by Jaiganeshkumaran** [comment]
It should be named Microsoft.UI.Xaml

**Comment by apkqiu** [comment]
I also think it should be this, but I see "Cannot find package". Is it because I am using the wrong version of Visual Studio?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jaiganesh ***@***.***&gt;; 
发送时间: 2021年7月16日(星期五) 下午3:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/microsoft-ui-xaml] NUGET package cannot find WinUI. (#5489)





 
It should be named Microsoft.UI.Xaml

**Comment by apkqiu** [comment]
> It should be listed as Microsoft.UI.Xaml

I also think it should be this, but I see "Cannot find package". Is it because I am using the wrong version of Visual Studio?

**Comment by evelynwu-msft** [comment]
@apkqiu Double check that you have `nuget.org` selected as the package source (it may be necessary to go into Nuget Package Manager settings and enable it as a package source):
<img width="1044" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/50890554/8d20a723-8666-4d78-8d8f-bf88ec50c560">
