### ISSUE TITLE
TeachingTip can't auto update location when window size changed

### ISSUE THREAD

**Issue by hippieZhou** [microsoft/microsoft-ui-xaml#549]
**Describe the bug**

![11](https://user-images.githubusercontent.com/13598361/56012702-420d1100-5d20-11e9-90cd-1dc0a6dc917e.gif)

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
In general, TeachingTip isn't going to reposition on target re-layouts, but I think watching for the window/XamlRoot size changed is feasible.
