### ISSUE TITLE
ListViewItem flickers when pressing up and down arrow keys continuously in WINUI ListView.

### ISSUE THREAD

**Issue by Subashini2129** [microsoft/microsoft-ui-xaml#5492]
Hi Team,

ListViewItem flickers when pressing up and down arrow keys continuously in WINUI ListView control while containing many items. Please find the sample regarding it below:

[ListView-sample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6831223/ListView-sample.zip)

**Replication procedure:**
* Run the application.
* Focus ListView control and press down arrow key continuously.
* Note, the last ListViewItem in view position updating looks like flickering.

Can you please suggest any workaround solution regarding this issue?

**Note:** Does not face this issue with a ListBox control.

**Comment by StephenLPeters** [comment]
@RBrid Weird perfromance issue that reproduces in XamlControlsGallery.  On the list view page if you scroll with arrow keys the items load very slowly but scrolling with mouse is fine.

**Comment by StephenLPeters** [comment]
Any thoughts?

**Comment by RBrid** [comment]
Took some CPU etl files with wpr.exe for the Xaml Controls Gallery app, on a Win11 VM, with and without animations on, and analyzed them in Windows Performance Analyzer. They was no smoking gun whatsoever as far as I could tell. No bottleneck.  

The new rounded listviewitempresenter chrome could be slowing things down, as well as the selection pill animations.

**Comment by StephenLPeters** [comment]
I suspect that the selection pill animation is responsible for this.  We could trying setting <x:Boolean x:Key='ListViewItemSelectionIndicatorVisualEnabled'>False</x:Boolean> and see if that improves the scenario significantly.

**Comment by StephenLPeters** [comment]
@Subashini2129 want to try that out?
