### ISSUE TITLE
System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#5497]
![image](https://user-images.githubusercontent.com/43340959/126015776-d9a6fd33-54a4-4b5f-93fb-2ca3bbb25abc.png)

[Dump](https://drive.google.com/file/d/19jUchr7JYV5IymKOtwKE1bIvlHMkxLYO/view?usp=sharing)

**Comment by StephenLPeters** [comment]
@RealTommyKlein FYI

**Comment by StephenLPeters** [comment]
@sigmarsson can you describe what was going on to cause this issue?

**Comment by sigmarsson** [comment]
@StephenLPeters occurs just before the main window could appear on debug.

**Comment by RealTommyKlein** [comment]
@sigmarsson are you F5'ing the `.csproj` instead of the `.wapproj` by any chance?

**Comment by sigmarsson** [comment]
![image](https://user-images.githubusercontent.com/43340959/126567005-a2b3b45d-d28e-4789-a2f7-5fa773b4e372.png)

**Comment by sigmarsson** [comment]
@RealTommyKlein ?

**Comment by RealTommyKlein** [comment]
@sigmarsson - sorry for the delayed response.  In the dump the app is still running against Reunion 0.5, but from the other thread it sounds like the app is targeting Reunion 0.8 or 0.8 Preview.  If your app is targeting 0.8, can you ensure any components referenced by the app that would also use Reunion (your own projects/libraries, or control libraries like the Windows Community Toolkit) are also targeting 0.8 or later?  There were breaking changes between `0.8.0-preview` and `0.8.0` - that may explain why targeting 0.5 or 0.8 Preview works for your app, but when it targets 0.8 this error occurs.  I was able to reproduce this error (or at least something with an identical callstack/exception) when I had an app targeting 0.8 using a library built against 0.5.
