### ISSUE TITLE
Activation not possible after toast notification click

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#5499]
_As the issue only seems to exist with Win32 WinUI/ProjectReunion applications, I'm filing this here rather than under WindowsAppSdk. Please move if deemed necessary._

**Describe the bug**
A toast notification handler, registered with a `ToastContent`s `.Activated` event group, cannot bring a Win32 WinUI application to the foreground. Activation fails, and GetWindowThreadProcessId(GetForegroundWindow()) returns the pid of `ShellExperienceHost`.

**Steps to reproduce the bug**

In a Win32 Project Reunion 0.8 project, create and display a toast notification content with the following configuration:

```csharp
private ToastNotifier Notifier = ToastNotificationManager.CreateToastNotifier();
private IntPtr Hwnd;

public void ShowNotification() {
    if (Hwnd == IntPtr.Zero) {
        MainWindow = this;
        Hwnd = this.As<IWindowNative>().WindowHandle;
    }

    var content = new ToastNotificationContent {
        ActivationType = ToastActivationType.Foreground,
        // Set other properties
    };
    var toast = new ToastNotification(content.GetXml());
    toast.Activated += OnToastClick;
}

public static OnToastClick(ToastNotification _, object _) {
    [DllImport("user32.dll")]
    static extern bool SetForegroundWindow(IntPtr hWnd);

    [DllImport("user32.dll")]
    static extern bool SendMessage(IntPtr hWnd, int msg, int wParam, int lParam);
    const int WM_SYSCOMMAND = 0x0112;
    const int SC_RESTORE = 0xF120;

    SendMessage(Hwnd, WM_SYSCOMMAND, SC_RESTORE, 0);
    SetForegroundWindow(Hwnd);
}
```

Trigger the notification, switch to a different full-screen application in the foreground, then click the notification. **Make sure no debugger is attached to the WinUI application** as `SetForegroundWindow()` is hard-coded to succeed if a debugger is attached.

The call to `SetForegroundWindow` fails. Investigation by adding `GetForegroundWindow()` and `GetWindowThreadProcessId()` reveals the foreground application at the time of click to be `ShellExperienceHost.exe` but it has activated the application in the background (already unexpected since foreground activation was specified, but permissible if you assume there's background work to be done before showing the UI) but not having granted permissions to the current invoked process' pid (or `ASFW_ANY`) to make itself the foreground window (unexpected).

Because ShellExperienceHost runs at a higher priority, it's not possible to use `AttachThreadInput()` to make a call to `AllowSetForeground()` on SEH's behalf.

Using `ToastActivationType.Protocol` works (although it requires registering the protocol and message passing to the correct instance) but the activation of `MyNamespace.App` actually shows a splash screen (while regular activation of the WinUI app never does), which is awkward and not to mention inefficient since currently toast notifications are not supported when the app isn't running anyway.

**Expected behavior**
When launched with `ToastActivationType.Foreground`, on clicking the toast notification the WinUI application should be brought to the foreground or allowed to bring itself to the foreground in its event handler.

**Version Info**

NuGet package version: 
WinUI 3 - Windows App SDK 0.8: 0.8.0
Win32 application, didn't have any problems with a UWP application

Tested under November 2019 Update (18363)

**Comment by mqudsi** [comment]
Ah, I think I understand now. I assumed that project reunion apps implemented `INotificationActivationCallback` but I see that's not the case. So the app *isn't* being activated by SEH and as far as anyone is concerned, it's just a rogue background app trying to steal the focus in response to an out-of-band event (on toast click) that isn't wired to the actual activation.

If that's the case, I guess `INotificationActivationCallback` is considered part of the lifecycle apis that are still to ship in 1.0 and this can be closed as a "in the works?"

**Comment by StephenLPeters** [comment]
@MikeHillberg and @ryandemopoulos do you know if this is in the plan? Is this Our issue or a Project Reunion issue?

**Comment by StephenLPeters** [comment]
@Austin-Lamb if its our issue FYI

**Comment by asklar** [comment]
CC @alexsnitkovskiy

**Comment by mqudsi** [comment]
Fwiw, I was able to get toast foreground/background activation to work by implementing INotificationActivationCallback in a singleton that registers as the instance provider and hacking up the AppxManifest to register the COM clsid in the registry.

I am curious if this is going to always be required (it’s only packageable to some extent without IDE support, unless there’s a way for a nuget package to make changes (statically or dynamically) to the appx manifest that I don’t know about), and in case a future Project Reunion update *does* remove the boilerplate if it’ll also necessarily break my current implementation.
