### ISSUE TITLE
Allow developers to control the transition time of `AddDeleteThemeTransition`

### ISSUE THREAD

**Issue by MuziburRahman** [microsoft/microsoft-ui-xaml#550]
The transitions in UWP are nice , but this particular transition - `AddDeleteThemeTransition` has relatively larger transitions time than other transitions. This transition starts after a certain time it's supposed to start (of 0.2 or 0.3 seconds) , which seems like UI is lagging when actually it's not. I think this behavior is intended and was particularly designed for `ListView` and similar controls where the adding and deleting transition is played sequentially.

But in many cases I found myself using this transition out of `ListView`. So, the 'intended' delay isn't desired there. It will be very helpful if we could specify whether we need that delay or not when we use the transition.

Notice the delay:
![hh](https://user-images.githubusercontent.com/21083609/56048248-e2872380-5d68-11e9-99d8-93c98784bc76.gif)

**Comment by jevansaks** [comment]
@stmoy Either a doc issue to guide people away from theme transitions to the new comp animation based "show" animations, or a feature request to make this possible.

**Comment by stmoy** [comment]
@MuziburRahman - the video looks like a new page or popup is being opened. Have you tried `NavigationThemeTransition` ? Specifically, I think the `DrillNavigationTransitionInfo` would help achieve this animation with lower latency. `AddDeleteThemeTransition` was tailor-made for ListView, so it's not the right transition to use in this case. 

A few helpful links:
- The [Xaml Controls Gallery](https://aka.ms/galleryapp) has samples for both Page Transitions and Theme Transitions
- The Fluent Design System guidance document on [Page Transitions](https://docs.microsoft.com/en-us/windows/uwp/design/motion/page-transitions) discusses how to build navigation animations

**Comment by MuziburRahman** [comment]
@stmoy 
No, it's not a new page, It's a `Grid` just having `Visibility` to `Visible`, I made sure it has already been opened several times before I captured the video. You can try yourself too, every time a specific amount of delay is there and I think it's intended.
Isn't `NavigationThemeTransition` and other `Page Transitions` are for navigating between pages? 
Not only this specific transition,  same about `ReorderThemeTransition`. It's nice and all, but it always takes time attaching an `UIElement` to the visual tree.

Whatever, I solved the problem using *Composition implicit show/hide animation*.

**Comment by stmoy** [comment]
@MuziburRahman - gotcha, thank you for following up. I am glad you found an approach that worked. Since it's just another Grid on the same page, it makes sense to use implicit show/hide animations. If it had been a different page or popup, other ThemeTransitions may have worked.
