### ISSUE TITLE
Generated C++ files should respect the parent project's PCH name

### ISSUE THREAD

**Issue by syndek** [microsoft/microsoft-ui-xaml#5501]
When developing a C++/WinRT application using WinUI, files generated by the XAML compiler don't respect the parent project's PCH name, and will always generate with the line `#include "pch.h"`. For projects that don't use the name `pch.h` for the PCH, this will result in a compilation error that can't be manually fixed.

I initially thought that this was a C++/WinRT issue, hence this issue I opened [here](https://github.com/microsoft/cppwinrt/issues/985). However, I've been told that this is actually a bug in the XAML compiler and is more relevant here.

**Steps to reproduce the bug**
1. Create a new C++/WinRT application using the `Blank App (WinUI 3 in UWP)` project template.
2. In the created project properties, change the name of the PCH to anything other than `pch.h`.
3. Try to compile the project.

**Expected behavior**
Files generated by the XAML compiler respect the name set and generate with `#include "<pch-name.h>"` rather than `#include "pch.h"`.

**Screenshots**
![image](https://user-images.githubusercontent.com/16063321/126055722-56d7f788-55a9-4e5c-b867-561e3bdb2a69.png)

**Version Info**
NuGet package version: WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview
Windows version: Windows 11 build 22000.71

**Comment by StephenLPeters** [comment]
@fabiant3 and @RealTommyKlein FYI

**Comment by evelynwu-msft** [comment]
This was fixed in WinAppSDk 1.3.
