### ISSUE TITLE
Question: Best way to fill area with fallback colors

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#5502]
Scenario: I have a set of themed brushes that might or might not be defined and I want to be able to fill an area with at least one of those brushes, ideally in a first come first server manner.

I was thinking about using a Grid, render Rectangle controls over each other and hope that if a resource is not defined, the rectangle will show the rectangle underneath is. Is that the best approach? Or would using a converter or something else be better?

**Comment by mrlacey** [comment]
The exact requirements are a bit vague but defining multiple controls on top of each other is inefficient, inflexible, and relies on exceptions that you'll ignore.
I'd do this by looking up the values at runtime and applying the first one that exists (is valid)

Example:

Create a UserControl

```xml
<UserControl
    x:Class="App284.BackgroundControl"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Grid x:Name="VirtualBackground"  />
</UserControl>
```
with this code-behind

```cs
    public sealed partial class BackgroundControl : UserControl
    {
        static readonly SolidColorBrush fallbackBrush = new(Colors.HotPink);

        public BackgroundControl()
        {
            InitializeComponent();
            VirtualBackground.Background = fallbackBrush;
        }

        public string Brushes
        {
            get => (string)GetValue(BrushesProperty);
            set => SetValue(BrushesProperty, value);
        }

        public static readonly DependencyProperty BrushesProperty = DependencyProperty.Register("Brushes", typeof(string), typeof(BackgroundControl), new PropertyMetadata(default(string), new PropertyChangedCallback(OnBrushesChanged)));

        private static void OnBrushesChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if (d is BackgroundControl bgc)
            {
                bool useFallback = true;

                var options = e.NewValue.ToString();

                foreach (var option in options.Split(','))
                {
                    if (Application.Current.Resources.ContainsKey(option))
                    {
                        bgc.VirtualBackground.Background =
                            (SolidColorBrush)Application.Current.Resources[option];
                        useFallback = false;
                        break;
                    }
                }

                if (useFallback)
                {
                    bgc.VirtualBackground.Background = fallbackBrush;
                }
            }
        }
    }
```

Then assuming these brushes are defined:

```xml
    <SolidColorBrush x:Key="Preferred" Color="Red"/>
    <SolidColorBrush x:Key="DynamicFallback" Color="Green"/>
```

You could use it like this:

```xml
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="1*" />
        <ColumnDefinition Width="1*" />
        <ColumnDefinition Width="1*" />
        <ColumnDefinition Width="1*" />
    </Grid.ColumnDefinitions>

    <!-- no brushes defined so use fallback -->
    <local:BackgroundControl Grid.Column="0" />
    <!-- single valid resource defined so use that -->
    <local:BackgroundControl Grid.Column="1" Brushes="Preferred" />
    <!-- Multiple invalid brushes defined so use fallback -->
    <local:BackgroundControl Grid.Column="2" Brushes="Undefined,OtherUndefined" />
    <!-- first value is invalid but 2nd isn't so use that -->
    <local:BackgroundControl Grid.Column="3" Brushes="Undefined,DynamicFallback" />
</Grid>
```

and you'd see something like this when you run it.

![image](https://user-images.githubusercontent.com/189547/126207905-f636179f-fbba-457c-8880-d3ec1af45087.png)




Known issues with the above:
- Doesn't handle brushes beyond a solid color (but could easily be made to support this if necessary)
- Not very efficient if the `Brushes` property will change a lot a runtime (but could be handled better if required)

**Comment by chingucoding** [comment]
I think this won't really work with theme resources would it? For example, if the theme switches, your UI won't update as you referenced a static brush. Will your code even reference resources properly that are only defined in themedictionaries, not as part of the "regular" dictionary?

Also, can you elaborate on "exceptions" I will ignore?

**Comment by mrlacey** [comment]
> I think this won't really work with theme resources would it? For example, if the theme switches, your UI won't update as you referenced a static brush. Will your code even reference resources properly that are only defined in themedictionaries, not as part of the "regular" dictionary?

How are you defining your Theme Resource dictionaries so they're not available at the application resource level. That should have access to everything.

You could specify the theme binding when you set the resource in code-behind.

I used a static as it was a couple of minute throw-away example to show the concept.

> Also, can you elaborate on "exceptions" I will ignore?

If you stack controls on top of each other and rely on ones that aren't defined on top not showing up (or being transparent) there will be lookup and/or binding expression failures for each one that isn't shown.

**Comment by chingucoding** [comment]
> How are you defining your Theme Resource dictionaries so they're not available at the application resource level. That should have access to everything.

Turns out my testing was faulty, sorry about the confusion.

> You could specify the theme binding when you set the resource in code-behind.

Didn't know that that is possible, is there any documentation I could read about this?

> If you stack controls on top of each other and rely on ones that aren't defined on top not showing up (or being transparent) there will be lookup and/or binding expression failures for each one that isn't shown.

That's fair enough though expected with the approach. But yes, you are right that this would end up in faulty resource lookups.

**Comment by StephenLPeters** [comment]
Binding has a FallbackValue property which seems appropriate here?

**Comment by chingucoding** [comment]
Totally missed your comment @StephenLPeters, sorry about this. Yes FallBackValue is a thing, however when I have a list of fallbacks, this wouldn't work would it?

**Comment by chrisglein** [comment]
@chingucoding Do you have some scenarios in mind that would require that this become a more centrally solved problem (i.e. handling a set of fallbacks instead of a single fallback)? Your question starts as "what's the best way" but I wonder if you're getting at more. Is there a proposal lurking behind this? And if so, what are the primary use cases it should target.

**Comment by chingucoding** [comment]
@chrisglein I'm gonna be honest, I don't that this should centrally solved. When developing https://github.com/files-community/Files/pull/5455 I noticed my need for this feature and if there are best practices. Since the need is quite specific, I am not sure how many other people might encounter this issue. Feel free to close this issue if you think there is not much to add here.
