### ISSUE TITLE
Localization in WinUI TextBox controls 

### ISSUE THREAD

**Issue by KanniyappanP** [microsoft/microsoft-ui-xaml#5503]
How to use Language property in WinUI TextBox controls and what will be the behavior of Language property?

**Comment by KanniyappanP** [comment]
Hi Team,

Any update on this?

**Comment by mrlacey** [comment]
The Language property is inherited from FrameworkElement. It is used for globalization/localization
Official docs: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.language
