### ISSUE TITLE
MatrixTransform always crashes

### ISSUE THREAD

**Issue by AghaKhan** [microsoft/microsoft-ui-xaml#5504]
**Describe the bug**
media:RadialGradientBrush.Transform is broken.
Please use any matrix. 

xmlns:media="using:Microsoft.UI.Xaml.Media"
I have a brush 
<media:RadialGradientBrush
        x:Key="YesKey1"
        Center="432, -325"
        RadiusX="47"
        RadiusY="47">
        <GradientStop Offset="0" Color="#4AB749" />
        <GradientStop Offset="1.0" Color="#226835" />
        <media:RadialGradientBrush.Transform>
            <MatrixTransform Matrix="1,0,0,0,1,0" />
        </media:RadialGradientBrush.Transform>
    </media:RadialGradientBrush>
If I remove Transform my application works fine. 

Microsoft Visual Studio Professional 2019
Version 16.9.5
VisualStudio.16.Release/16.9.5+31229.75
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-20310-66783-AA325
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.693.2781
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.693.2781
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.693.2781
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.9.21111.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper 2020.3.4   Build 203.0.20210316.132251
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2021 JetBrains, Inc.

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.21130.2 Commit Hash:dacc0e71a5e060cdcab466a301cacea359c1b6da
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

NVIDIA CUDA 11.2 Wizards   11.2
Wizards to create new NVIDIA CUDA projects and source files.

Office Developer Tools for Visual Studio   16.0.30502.00
Microsoft Office Developer Tools for Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.9.21111.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.9.21111.1
Conda support for Python projects.

Python - Django support   16.9.21111.1
Provides templates and integration for the Django web framework.

Python - Profiling support   16.9.21111.1
Profiling support for Python projects.

Rapid XAML Analysis   0.12.2
Tools to accelerate XAML app development by providing analysis and code fixes.

Rapid XAML Editor Extras   0.12.2
Tools to accelerate XAML app development by providing additional features to the Visual Studio editor.

Rapid XAML Generation   0.12.2
Tools to accelerate XAML app development by generating XAML.

Rapid XAML Roslyn Analyzers   0.12.2
Roslyn analyzers to help with XAML development.

Rapid XAML Templates   0.12.2
Project and item templates to help with XAML development.

Rapid XAML Toolkit   0.12.2
Tools to accelerate XAML app development.
This extension holds references and functionality used by the other Rapid XAML extensions.

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

UnoPlatformPackage Extension   1.0
UnoPlatformPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.31025.194
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.9.1.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VisualSVN   7.3.3
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at https://www.visualsvn.com
Copyright © 2021 VisualSVN Software Ltd. All rights reserved.

Windows Template Studio   4.1.21179.1
Windows Template Studio quickly builds a UWP app, using a wizard-based UI to turn your needs into a foundation of Windows 10 patterns and best practices.

WinUI Essentials   1.2
The easiest way to set up Visual Studio for the ultimate WinUI development experience.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.9.000.292 (d16-9@26a958f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.318 (remotes/origin/7b35adcdd1b204bbdcb279e0f029d151a20a4bf3@7b35adcdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.72 (426ebf6)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

Xamarin.iOS and Xamarin.Mac SDK   14.16.0.5 (ab40b131d)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by StephenLPeters** [comment]
@AghaKhan what is the crash? do you have a call stack or a dump you can share?

**Comment by AghaKhan** [comment]
Thanks for prompt reply.
I am going to send a link where we are only looking why MatrixTransfom (Only in XAML) crashes. I think it works fine in code behind, because I never had this problem. You are only going to look 3 or 4 line of code.
Kindly download the code [BugInXaml](https://1drv.ms/u/s!AtjIdnVOoJXtpNthBNsruHOX_s8Riw?e=A7HSJm)
look Styles.xaml fine. Please uncomment from 11 to 13 and run the application and you will get a crash.  You will get the crash in App.g.i.cs and look the message in (sender,e) Exception = {"The text associated with this error code could not be found.\r\n\r\nFailed to assign to property 'Windows.UI.Xaml.Media.Brush.Transform'. [Line: 12 Position: 30]"}
I hope it will help to fix the problem.

**Comment by StephenLPeters** [comment]
@geGao18 any idea why this transform would cause that crash?
```
        <media:RadialGradientBrush.Transform>
            <MatrixTransform Matrix="1,0,0,0,1,0" />
        </media:RadialGradientBrush.Transform>
```

**Comment by gegao18** [comment]
It's not invertible - it scales the X axis by 1 and the Y axis by 0. That's probably why it's giving an error.

What's the scenario here? That transform will squish the gradient to nothing. If you wanted an identity transform, it'll be "1, 0, 0, 1, 0, 0".

**Comment by AghaKhan** [comment]
Oh No. I tried many vector, and it always fails. Please try any vector. It always fails. Thanks for reply Agha
