### ISSUE TITLE
[dev/internal] Unable to build MUXControlsTestApp with VS 2022 Preview

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#5508]
Using VS 2022 Preview, I am unable to build the MUXControlsTestApp. The build process fails with the following:

```
1>------ Build started: Project: AppTestAutomationHelpers, Configuration: Debug x64 ------
1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for Visual Studio 2015 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install Visual Studio 2015 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
1>Done building project "AppTestAutomationHelpers.vcxproj" -- FAILED.
```

Note that in VS 2022 Preview, the MVSVC v140 C++ build tools are also installed, yet building fails.

**Comment by StephenLPeters** [comment]
@llongley do you have an idea whats going wrong here?  I've heard VS2022 has some huge performance gains for large projects which could be awesome for the Winui projects!

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by chingucoding** [comment]
Closing now since I've been developing WinUI with VS 2022 for some time now and it seems to work fine.
