### ISSUE TITLE
Scroller is arranged incorrectly

### ISSUE THREAD

**Issue by micahl** [Microsoft/microsoft-ui-xaml#551]
**Describe the bug**

Scroller isn't being a good citizen in the layout process which causes unexpected behavior when doing things like setting a Horizontal/VerticalAlignment.  
![image](https://user-images.githubusercontent.com/1009123/56053359-bc319b80-5d08-11e9-81ab-3b3eef6e0a12.png)

In the picture above the left side is using Scroller and the right side is using the old ScrollViewer, but otherwise the markup is identical.  You can see that the ActualHeight of the Scroller ends up being the MaxHeight value that is set on the parent Border rather than the size of the content.  This causes its content to appear incorrectly positioned even though it is Top aligned.

**Steps to reproduce the bug**

Install a recent prerelease package and use this markup.

```xml
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition/>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>

        <Border MaxHeight="380"
                VerticalAlignment="Center"
                BorderBrush="Purple"
                BorderThickness="12"
                Grid.Column="0">
                <muxcp:Scroller ContentOrientation="Vertical"
                                VerticalAlignment="Center">

                    <StackPanel VerticalAlignment="Top"
                                BorderBrush="Lime"
                                BorderThickness="4"
                                Margin="12">
                        <Rectangle Width="296" Height="96" Fill="DarkRed" HorizontalAlignment="Right"/>
                        <Rectangle Width="296" Height="96" Fill="Red" HorizontalAlignment="Left"/>

                    </StackPanel>
                </muxcp:Scroller>
        </Border>

        <Border MaxHeight="380"
                VerticalAlignment="Center"
                BorderBrush="Purple"
                BorderThickness="12"
                Grid.Column="1">
                <ScrollViewer VerticalAlignment="Center">

                    <StackPanel VerticalAlignment="Top"
                                BorderBrush="Lime"
                                BorderThickness="4"
                                Margin="12">

                        <Rectangle Width="296" Height="96" Fill="DarkRed" HorizontalAlignment="Right"/>
                        <Rectangle Width="296" Height="96" Fill="Red" HorizontalAlignment="Left"/>

                    </StackPanel>
                </ScrollViewer>
        </Border>
```

**Expected behavior**

The left side looks like the right side.

**Version Info**

NuGet package version:  Microsoft.UI.Xaml 2.1.190319001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)   | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Comment by jevansaks** [comment]
@regisb want to take a look?

**Comment by RBrid** [comment]
Hey Jevan, yeah feel free to assign to me.
-Régis at the fabulous Ocean Shores

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
