### ISSUE TITLE
NavigationView "Settings" Button missing using WinUI 2.6.x via XAML Island

### ISSUE THREAD

**Issue by brooklynlittell** [microsoft/microsoft-ui-xaml#5511]
**Describe the bug**
The "Settings" button included with the NavigationView control does not appear using WinUI 2.6.x in a WPF XAML Island. This only reproduces using `PaneDisplayMode="Top"`; left-aligned display modes work as expected.

**Steps to reproduce the bug**
1. Create a WPF XAML Island project
2. Add WinUI 2.6.x
3. Add standard NavigationView control with a top display mode
4. Observe no settings button is visible

--- OR ---

Inspect my repro repo: https://github.com/BrandonLittell/nav-view-repro

**Expected behavior**
The settings button should be visible. I currently do not see the control in the view hierarchy.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml.2.6.1-prerelease.210709001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@BrandonLittell is this issue exclusive to xaml islands or does it reproduce with a UWP as well?

**Comment by BrandonLittell** [comment]
@StephenLPeters Exclusive to xaml islands

**Comment by StephenLPeters** [comment]
@BrandonLittell and I assume also regressed with winui 2.6 or 2.6.1 and was not an issue in 2.5?

**Comment by StephenLPeters** [comment]
@ranjeshj and @karenbtlai FYI

**Comment by Link1J** [comment]
The last version with the settings icon showing is 2.5.0-prerelease.200708003.
I believe the regression occurred with the introduction of `NavigationView.FooterMenuItemsSource` as warning for it happen in 2.5.0-prerelease.200812001 but not 2.5.0-prerelease.200708003.
So, it has been broken for most of 2.5, including the final prerelease.

**Comment by BrandonLittell** [comment]
@StephenLPeters @Link1J Provided you 2.5 info
