### ISSUE TITLE
c++/winrt: Reversed z-order between DesktopWindowTargets(siblings).

### ISSUE THREAD

**Issue by SJRyu** [microsoft/microsoft-ui-xaml#5516]
**Describe the bug**
Im using 'winrt::Windows::UI::Composition::Desktop::DesktopWindowTarget'.

**Steps to reproduce the bug**
In my win32/winrt project, 
There are two siblings have DesktopWindowTarget per each, and their client area drawn by d2d and compositon. 
Like the below screenshots z-orders in client area between targets are totally reversed.

**Screenshots**
when left window below to right window.
<img width="941" alt="bug1" src="https://user-images.githubusercontent.com/18696849/126282989-d1365b2e-10cd-4da2-a160-89fb988986d9.PNG">

when right window below to left window. ( i reversed z-order with 'SetWindowPos')
<img width="946" alt="bug1_1" src="https://user-images.githubusercontent.com/18696849/126283000-88df4139-2f28-4b52-8e45-4ea9747dbfa8.PNG">

**Version Info**

Extension : 
<[C++/WinRT 2.0.210714.1]>

Windows app type:
| Win32            |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**

**Comment by StephenLPeters** [comment]
@jeffstall Is this an IXP issue?

**Comment by adadi-MS** [comment]
@SJRyu  Do you have WS_CLIPSIBLINGS set on the 2 child windows that you're creating DesktopWindowTargets on?

**Comment by SJRyu** [comment]
> @SJRyu Do you have WS_CLIPSIBLINGS set on the 2 child windows that you're creating DesktopWindowTargets on?

nope. no styles for them

**Comment by adadi-MS** [comment]
@SJRyu Go ahead and set that style on both windows. The nonclient areas are drawn into the DC for the toplevel parent window - if the children are not told to clip themselves against each other they will draw on top of each other.  Who draws first is not determined by zorder, but by the rather random order in which they get WM_NCPAINT.  WS_CLIPSIBLINGS will prevent them from drawing in the area occupied by sibling windows.

**Comment by SJRyu** [comment]
> @SJRyu Go ahead and set that style on both windows. The nonclient areas are drawn into the DC for the toplevel parent window - if the children are not told to clip themselves against each other they will draw on top of each other. Who draws first is not determined by zorder, but by the rather random order in which they get WM_NCPAINT. WS_CLIPSIBLINGS will prevent them from drawing in the area occupied by sibling windows.

thank you
