### ISSUE TITLE
Setting tabview footer as draggable region does not work inside Navigationview

### ISSUE THREAD

**Issue by JPTGamesAndApps** [microsoft/microsoft-ui-xaml#5518]
**Describe the bug**

When a tab view with its footer as a drag region (for title bar) is wrapped inside the navigation view, the drag region does not work anymore.

**Steps to reproduce the bug**

1.  Set tab view footer as a draggable region as described here: https://docs.microsoft.com/en-us/windows/apps/design/controls/tab-view . Drag region works as expected.
2.  Wrap the tab view inside navigation view. Drag region does not work anymore.

**Expected behavior**
The drag region will continue to work as expected.

**Screenshots**
![Drag Region Issue Screenshot](https://user-images.githubusercontent.com/77933967/126390513-002d8abe-062f-4745-a61b-b5bbe0785cf0.png)

**Version Info**
NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

**Additional context**
Probably somewhat related bug #4183

**Comment by StephenLPeters** [comment]
@beervoley does this sound familiar to you?

**Comment by StephenLPeters** [comment]
@karenbtlai FYI

**Comment by beervoley** [comment]
> @beervoley does this sound familiar to you?

nope, never seen this
it looks like #4183

**Comment by JPTGamesAndApps** [comment]
> > @beervoley does this sound familiar to you?
> 
> nope, never seen this
> it looks like #4183

That was my guess as well. Also, unfortunately, there is no way to render the footer at the top of others elements as ZIndex appears to be limited to what it does with respect to its parent.
