### ISSUE TITLE
Context menus sometimes faded on windows 10

### ISSUE THREAD

**Issue by josh-65** [microsoft/microsoft-ui-xaml#5519]
**Details here**
https://github.com/files-community/Files/issues/5461#issue-949076958

**Comment by StephenLPeters** [comment]
@chigy and @ranjeshj FYI

**Comment by StephenLPeters** [comment]
@josh-65 I think this issue has been fixed with the Winui 2.6.1 release, can you confirm that upgrading to that works?

**Comment by josh-65** [comment]
I don't own the files app nor do i know how to test it anyway. I have mentioned it to the developers and I am waiting for a response or for them to update it.

**Comment by winston-de** [comment]
> I don't own the files app nor do i know how to test it anyway. I have mentioned it to the developers and I am waiting for a response or for them to update it.

Current insider builds for Files use winui 2.6.1.

> @josh-65 I think this issue has been fixed with the Winui 2.6.1 release, can you confirm that upgrading to that works?

Also, this issue does seem to be fixed (on windows v22000.100 anyway, not sure about win 10 builds) with 2.6.1, while apps using plain system xaml are affected (separate issue).

**Comment by josh-65** [comment]
Still happens on Windows 10 19043.1110
