### ISSUE TITLE
DragStartingEventArgs.GetPosition returns different result than DragEventArgs.GetPosition with different DPI Monitor

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#5520]
**Describe the bug**
When using the `GetPosition` function on `DragStartingEventArgs` to retrieve a coordinate, the value provided isn't DPI agnostic (as would be expected). This makes it hard to use the value directly to map to other UI based coordinates and sizes without a workaround to scale back based on the monitor DPI.

However, `DragEventArgs` version of this method does scale correctly.

**Steps to reproduce the bug**
```xml
    <Grid
        x:Name="ParentGrid"
        AllowDrop="True"
        Background="Transparent"
        DragOver="ParentGrid_DragOver"
        RowDefinitions="*,Auto,Auto"
        RowSpacing="8">
        <Rectangle
            x:Name="MyRect"
            Width="400"
            Height="200"
            HorizontalAlignment="Right"
            VerticalAlignment="Bottom"
            CanDrag="True"
            DragStarting="Rectangle_DragStarting"
            Fill="Red" />
        <TextBlock Grid.Row="1">
            <Run Text="Drag Start Position: " />
            <Run x:Name="StartPosition" />
        </TextBlock>
        <TextBlock Grid.Row="2">
            <Run Text="Drag Over Position: " />
            <Run x:Name="DragOverPosition" />
        </TextBlock>
    </Grid>
```

```cs
        private void Rectangle_DragStarting(UIElement sender, DragStartingEventArgs args)
        {
            var position = args.GetPosition(ParentGrid);
            StartPosition.Text = position.ToString();
        }

        private void ParentGrid_DragOver(object sender, DragEventArgs e)
        {
            var position = e.GetPosition(ParentGrid);
            DragOverPosition.Text = position.ToString();
        }
```

Try dragging the rectangle and noticing the starting value and the first drag over value when the mouse cursor is dragged just away from the starting position. At 100% DPI these are the same (as expected):

Start drag in top-left corner on 100% DPI monitor:
 - Drag Start: 1499, 734
 - Drag Over: 1490, 729

Start drag in bottom-right corner on 100% DPI monitor:
 - Drag Start: 1896, 938
 - Drag Over: 1896, 944

At 150% DPI, top-left corner seems ok:
 - Drag Start: 1297, 639
 - Drag Over: 1306, 641

**However, at 150% dragging from the bottom-right corner, we see the issue**:
 - Drag Start: _1891, 935_
 - Drag Over: **1693, 834**

**Expected behavior**
The two `GetPosition` functions should return the same values in all cases regardless of DPI.

_It's also interesting to note that the precision of the Starting points is higher than those provided by Drag Over._ (I've just rounded in the numbers above for ease of comparison.)

![image](https://user-images.githubusercontent.com/24302614/126398755-81ed6fcb-12f2-4974-8a36-75c85de78772.png)

**Version Info**
NuGet package version: Windows App SDK 0.8.1
This also occurs in OS XAML, see this [3 year old post here](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/f6198090-d383-45fe-ad21-c42413b0c726/uwpthe-point-value-differs-with-different-screen-resolution-windows-in-uwp).

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 21H1 Build (19043)              | Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@codendone @JJBrychell and @gegao18 FYI

**Comment by DavidLuong98** [comment]
My team and I experienced the same issue. We used `XamlRoot.RasterizationScale` to factor in the scale used that for the calculations.
