### ISSUE TITLE
Padding of command bar flyout secondary item should be the same as MenuFlyoutItem

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#5523]
Today the padding for command bar flyout secondary items is much larger than MenuFlyoutItem. Since they both are used interactable for similar purposes, I expect it to be the same.

**Comment by Jaiganeshkumaran** [comment]
Here's a command bar flyout. Notice how the options have huge padding: 
![image](https://user-images.githubusercontent.com/45227503/126452971-75e3fdcd-648e-41e7-b202-127bbf463220.png)

And here's a menu flyout. The padding is much smaller:
![image](https://user-images.githubusercontent.com/45227503/126453047-b2762d95-0c44-4b0b-9215-f356f88b113f.png)

**Comment by colinkiama** [comment]
Are you sure? The command bar at the top might just be stretching the with of the flyout.

Could you also post and image of a Command Bar Flyout with one of the secondary items in the "hover" state?

**Comment by Jaiganeshkumaran** [comment]
@colinkiama ![image](https://user-images.githubusercontent.com/45227503/126456546-6b3481a4-8dfc-4952-a756-1c8256623192.png)

**Comment by StephenLPeters** [comment]
Fixed by : https://github.com/microsoft/microsoft-ui-xaml/pull/5433
