### ISSUE TITLE
Moving window by calling Win32 API doesn't work

### ISSUE THREAD

**Issue by un-tone** [microsoft/microsoft-ui-xaml#5529]
**Describe the bug**

I have an app with a completely custom Blazor component that replaces standard window caption and enabled `MainWindow.ExtendsContentIntoTitleBar` property. I use Win32 calls for controlling the window. Maximize/minimize buttons work well with it (`ShowWindow(_hwnd, SW_MAXIMIZE)`, `ShowWindow(_hwnd, SW_MINIMIZE)`, etc). But I have troubles with moving the window in a similar way.

```razor
@* The Caption component *@
<div class="window__caption" @onpointerdown="@(() => Window.DragMove())">
    @ChildContent
</div>

@code {
    [Parameter] 
    public RenderFragment ChildContent {get; set;}

    [CascadingParameter] 
    public IBlazorWindow Window {get; set;}
}
```

```cs
/* the Win32 callings */
const int WM_NCLBUTTONDOWN = 0x00A1;
const int HTCAPTION = 2;

[DllImport("user32.dll", CharSet = CharSet.Auto)]
public static extern IntPtr SendMessage(IntPtr hWnd, int Msg, int wParam, IntPtr lParam);
[DllImport("user32.dll")]
static extern bool ReleaseCapture();

public void DragMove() {
    ReleaseCapture();
    SendMessage(_hwnd, WM_NCLBUTTONDOWN, HTCAPTION, IntPtr.Zero);
}
```

It is a common way to move windows using custom controls. It is expected to work in this case also, but it doesn't.

**Steps to reproduce the bug**

**Expected behavior**
A user moves the window by dragging the custom caption.

**Version Info**

Target framework: net6.0-windows10.0.19041

NuGet package version: 
Microsoft.ProjectReunion.WinUI 0.8.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 (19043.1110)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

I can assume that WebView2 layer can restrict some events or system messages propagation and the `ReleaseCapture()` call doesn't work correctly in this case. I tried to call `webView2.ReleasePointerCaptures()` instead of it and it helps a little - sometimes it makes the movement of the window but without animation, just a leap.

**Comment by pratikone** [comment]
You cannot send and use NC messages to window in WinUI 3 window as it filters them out. It is an intentional design choice. You can use `SetWindowPos` and other similar Win32 apis to move/drag a window. Closing this issue.
