### ISSUE TITLE
NavigationView OpenPaneLength causes content to horizontally surpass the window size in compact mode

### ISSUE THREAD

**Issue by hanzhang54** [microsoft/microsoft-ui-xaml#5533]
**Describe the bug**

After the app enters compact mode, it looks good to change the window size with the UI controls’ size changed coordinately when the window size is large. However, if I keep decreasing the window size, the UI control’s height will be always automatically adapted to the window size while the width stop adapting to smaller size at a certain point. 

**Steps to reproduce the bug**

1. Put some contents into NavigationView and set the OpenPaneLength
2. Enter the compact mode
3. Decrease the window width to be smaller than the OpenPaneLength set in step 1.

**Expected behavior**

The content width is expected to adapt to the window width.

**Screenshots**

Expected behavior:
![image](https://user-images.githubusercontent.com/78525595/126594445-39c9615b-f6c2-4ff1-bbb0-7775afb93434.png)

Abnormal behavior:
![image](https://user-images.githubusercontent.com/78525595/126595047-27a3f44f-0489-488c-bdaf-b14d2168c6d0.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This issue is caused by the OpenPaneLength.
In NavigationView.xaml, the NavigationView is implemented by SplitView for the left displaymode (compact/minimal/normal). The SplitView consists of SplitView.Pane for the menu and SplitView.Content for coordinate content. All the contents are put inside a Grid called ContentGrid in SplitView.Content. 
In NavigationView.cpp, it implements a method called UpdatePaneShadow() to render the shadow effect around the pane. From line 4838 to 4841, the shadowReceiver is set to span all the columns of contentGrid. Then from line 4867 to 4870, the width of shadowReceiver will be set to OpenPaneLength() which is the value we set in the XAML for NavigationView OpenPaneLength property. 
In compact mode, if the window width is smaller than OpenPaneLength, the width of the child content shadowReceiver will be larger than the window width and expand the contentGrid width to be larger than the window width. Thus, part of the content will disappear from the window horizontally.

**Comment by hanzhang54** [comment]
One workaround for this issue is to set the OpenPaneLength to be smaller than the minimum window width in compact mode. Here is the [PR link](https://github.com/microsoft/calculator/pull/1615) for how we did this in Windows Calculator project. 😉
This issue is quite tricky and can be 100% reproduced in the compact mode when the window width is smaller than the OpenPaneLength. Generally, it is very hard for people to connect this issue to the OpenPaneLength. It would be great if we can resolve this issue on WinUI level.

**Comment by StephenLPeters** [comment]
@beervoley and @karenbtlai FYI
