### ISSUE TITLE
NavigationView flashes white when shown/hidden in dark mode

### ISSUE THREAD

**Issue by dan-jac** [microsoft/microsoft-ui-xaml#5534]
**Describe the bug**
NavigationView flashes white when shown/hidden in dark mode

**Steps to reproduce the bug**
Open the current version of XAML Controls Gallery (1.2.19.0).
Use the app's Settings page to switch the app to dark mode.
Adjust the width of the app window such that the left nav is only showing icons. (But not so narrow that it hides entirely.)
Press the hamburger button to show and hide the text labels of the NavigationView.

**Expected behavior**
NavigationView retains a dark background as it animates between showing and hiding the text labels.

**Actual behavior**
NavigationView flashes white as it animates open and closed.

Screenshots
![126638518-90d72bc7-4718-44e1-a3a2-423cd45fb71c](https://user-images.githubusercontent.com/50617707/126639089-24534f7b-66ed-466a-b647-ad87d8c15723.png)
![126638328-af4cc90c-f904-4587-98ee-cf5a532e8ea6](https://user-images.githubusercontent.com/50617707/126639094-99e166d3-dbbd-4ac1-bb4a-ee04092a2217.png)

**Version Info**
XAML Controls Gallery downloaded from Store – 1.2.19.0
(This also repros in other apps that use the NavigationView control.)

Repro'd on Windows 11 build 22000.100.

**Comment by StephenLPeters** [comment]
Should be fixed by: https://github.com/microsoft/microsoft-ui-xaml/pull/5467  @karenbtlai FYI
