### ISSUE TITLE
WinUI 2.6.1 AutoSuggestBox Search Icon Position Offset

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#5537]
**Describe the bug**
The search icon on the AutoSuggestBox seems offset too far to the left or not right-justified.

**Steps to reproduce the bug**
Seems to be the default with no steps needed to reproduce.

**Expected behavior**
The icon ought to be right justified like it was on WinUI 2.5. No overlapping with search text or placeholder text.

**Screenshots**
![image](https://user-images.githubusercontent.com/3663297/126674606-73f36adf-b7a6-4b11-9e4f-4a0b9fe38891.png)

![image](https://user-images.githubusercontent.com/3663297/126674623-97a8dcd6-0398-41c6-b07f-af8076bcfbb0.png)

![image](https://user-images.githubusercontent.com/3663297/126674835-19f50a9c-17c0-4951-a169-5885aab5f8f2.png)

**Version Info**
2.6.1

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21H2)              | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Thanks! @ranjeshj 2.6?

**Comment by myokeeh** [comment]
@ranjeshj I don't know what XCG is.

![image](https://user-images.githubusercontent.com/3663297/128293800-c67f1900-a173-4bf9-8b04-8a9e19f48841.png)

**Comment by StephenLPeters** [comment]
XamlControlsGallery

**Comment by myokeeh** [comment]
@ranjeshj @StephenLPeters here's a solution that reproduces this.
[DELETE9.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6939919/DELETE9.zip)

**Comment by myokeeh** [comment]
@ranjeshj @StephenLPeters does it reproduce for you with this solution?

**Comment by myokeeh** [comment]
When do we expect this fix on 2.7.X?

**Comment by htcfreek** [comment]
Any updates when this fix will be released in 2.7 versions?
