### ISSUE TITLE
CommandBarFlyout position is reevaluated when secondary items are added after flyout has opened

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#5539]
**Describe the bug**

When secondary items are added to a CommandBarFlyout after it has opened, it's position can change unexpectedly. For example, if it is opened towards the bottom of the screen and items are added, it will be moved up.

**Steps to reproduce the bug**

1. Create command bar flyout, and write code to asynchronously add items after the flyout has opened
2. Open close enough to the bottom of the screen that it opens downwards with little room to spare
3. Flyout will reposition upwards once items are added

Repro app:
[Repro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6864846/Repro.zip)

**Expected behavior**

The position should not be reevaluated, as this looks bad. Instead, the secondary items list should become scrollable. 

**Screenshots**

https://user-images.githubusercontent.com/59544401/126699607-f32c7e0b-20d9-48a3-b9ae-644f4dc24907.mp4

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.71)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
I think this is by design, we don't want to scroll secondary commands unless we have to.  Additionally, I think it is more common that async items are loaded quickly enough that this jump is not as jarring as this video.  However I do think there is a good question of it this is really the feel we want.

@alejo4000 what do you and your team think?

**Comment by winston-de** [comment]
There are cases where devs would add items up to a few seconds after the flyout has opened. One example is context menus in Files. The enumeration time for getting shell context menu items can vary from a few milliseconds to several seconds, so in order to prevent the UI from feeling unresponsive, basic (built into the app) context items are shown first, and shell items are added to the bottom once they are loaded.

Also, I would like the clarify, the main issue with this is that users can accidently click something they didn't mean to if they try and invoke an item around the same the command bar flyout jumps.
