### ISSUE TITLE
TeachingTip does not work inside a XamlIsland

### ISSUE THREAD

**Issue by azchohfi** [Microsoft/microsoft-ui-xaml#554]
**Describe the bug**
TeachingTip does not workin when used in the context of a Xaml Island. I'm assuming that the internal popup that is created by the TeachingTip class does not have it's XamlRoot set, so I'm getting a "Catastrophic failure" exception.

**Steps to reproduce the bug**
1. Instantiate a Xaml Island and set it's Child to an instance of TeachingTip
2. Call TeachingTip.IsOpen = true;
3. An exception will be thrown
System.Exception: 'Catastrophic failure
Opening a popup failed because the XAML runtime is running to support DesktopWindowXamlSource, and in this mode a popup must be a child of a live XAML element.'

**Expected behavior**
TeachingTip works on a Xaml Island

**Version Info**
Xaml Island host from Windows Community Toolkit 6.0.0-preview3
.Net Core 3.0.100-preview5-011215
WIndows 10 18877.rs_prerelease
Desktop

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18877)                   | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Comment by jevansaks** [comment]
cherry-picked to release/2.1 as c2da77a0575f8fed8e26416c236443686b110ce1
