### ISSUE TITLE
DxgkSharedResource handle leak when using Images and WriteableBitmaps

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/microsoft-ui-xaml#5541]
**Describe the bug**

I'm displaying two `Microsoft.UI.Xaml.Controls.Image`s with `WriteableBitmap`s as their sources. The `PixelBuffer`s are rapidly updated via `Stream.Write` and `WriteableBitmap.Invalidate` calls. 

I have no apparent memory leaks, however my process handle count keeps slowly increasing. Using WinDbg I can see they all appear to be of the type `DxgkSharedResource`, which I assume are related to [these calls](https://docs.microsoft.com/en-us/windows/win32/direct3d12/shared-heaps).

[This repo shows the general nature of my code, but unfortunately doesn't repro the issue.](https://github.com/kmgallahan/MinRepo_HandleLeak/blob/master/MinRepo_HandleLeak/MinRepo_HandleLeak/MainWindow.xaml.cs) 

If I simply comment out either one of the `Invalidate()` calls or either one of the `Microsoft.UI.Xaml.Controls.Image`'s then the handle count doesn't increase.

So I'm wondering if anyone with access to the source can peak and see if there is some condition where DirectX Shared Resource handles can get created and not cleaned up when using multiple Images and WriteableBitmaps.

**Steps to reproduce the bug**

Unfortunately can't figure out how to repro outside of my codebase, which also requires a hardware connection to a specific camera model to run. I can add that the source data for the WriteableBitmaps comes out of this call from Magick.NET:

```
public static byte[]? ToArray(IntPtr nativeData, int length)
        {
            if (nativeData == IntPtr.Zero)
                return null;

            byte[] buffer = new byte[length];
            Marshal.Copy(nativeData, buffer, 0, length);
            return buffer;
        }
```

**Expected behavior**
No handle leak

**Screenshots**
![Screenshot 2021-07-22 202139](https://user-images.githubusercontent.com/5379488/126724613-51ee2cf5-30cf-4f5d-b492-55750524e967.jpg)

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 0.8: 0.8.1] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by kmgallahan** [comment]
@StephenLPeters

**Comment by StephenLPeters** [comment]
Thanks for the ping, so strange that our bot doesn't tag one in every ~200 issues with the triaging labels...

@codendone and @gegao18 FYI

**Comment by kmgallahan** [comment]
Keep alive, going to look into this again soon

**Comment by kmgallahan** [comment]
After returning to this code base after 2 years and refactoring I'm no longer seeing this behavior.
