### ISSUE TITLE
Question: [No EventManager Class]

### ISSUE THREAD

**Issue by amaosangm** [microsoft/microsoft-ui-xaml#5545]
![image](https://user-images.githubusercontent.com/32085019/126772737-de6ecc68-bb14-433f-948e-ad9516b3d935.png)
![image](https://user-images.githubusercontent.com/32085019/126772751-0736e87f-241d-4c4e-8a9f-d399ee85e967.png)
I want to use event in my custom control, but there is no EventManager Class, I'm certain I have already using System.Windows.

**Comment by StephenLPeters** [comment]
EventManager is a WPF concept that does not exist in UWP.  @MikeHillberg fyi
