### ISSUE TITLE
Question: what is the difference between Microsoft.UI and ABI.Microsoft.UI in WinUI3?

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#5549]
When working with winUI 3 in windows app sdk, when we are using NavigationView or other controls we can see that always there is 2 options for import using, one with ABI and one without it. So what is ABI? and what is the difference between ABI and without ABI options?
For example:
```
Using ABI.Microsoft.UI;

Using Microsoft.UI;
```
Which one we should use in our app?

**Comment by mrlacey** [comment]
Don't use the ABI ones.
They're a side effect of a low-level implementation detail and a future version of Visual Studio (the next preview--I think) will hide them.

**Comment by manodasanW** [comment]
See https://github.com/microsoft/WindowsAppSDK/issues/1103
