### ISSUE TITLE
TreeView selected item changes binding source value

### ISSUE THREAD

**Issue by frauenholz** [microsoft/microsoft-ui-xaml#555]
[treeViewSelectedBug_MainPageXaml.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3076222/treeViewSelectedBug_MainPageXaml.zip)
setting TreeViewList.SelectedItem, either by setting the SelectedItem.Binding Source, or by directly setting TreeViewList.SelectedItem, retains the original value and updates any binding sources with the original value

note: I originally submitted this issue to Visual Studio and they said to bring it here
https://developercommunity.visualstudio.com/content/problem/475498/cannot-set-selecteditem-in-treeview.html

there is a description in the attached source code at the top of the Xaml

**Describe the bug**
the following statement
this.treeView._TreeViewList.SelectedItem = this.MostRecentSelectedItem
changes the value on the right side of the assignment statement

**Steps to reproduce the bug**
open the attached source code and add it to a UWP blank app
put a breakpoint in the MostRecentSelectedItem property setter, and in the Button_Click1 method
run the app
click the two buttons 
see the weird seleted item behavior

**Expected behavior**

**Screenshots**

**Version Info**
Windows 10 Pro 1809

NuGet package version: 
Microsoft.Toolkit.Uwp.UI.Controls 5.1.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Windows 10 Pro     | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Additional context**

[treeViewSelectedBug_MainPageXaml.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3076231/treeViewSelectedBug_MainPageXaml.zip)

**Comment by jevansaks** [comment]
Thanks for the report and repro project!

**Comment by kaiguo** [comment]
This has the same root as #125, closing as dupe.
