### ISSUE TITLE
Setting App.xaml.cs breakpoint in constructor breaks DWM

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#5550]
**Describe the bug**

Under Windows 10 18363, if a breakpoint is added before the call to `this.InitializeComponent()` in the constructor for `App` in a packaged Win32 Project Reunion workspace and the app is run via the package, DWM breaks when the breakpoint is hit and Visual Studio is activated/brought to the foreground.

As far as what it means for DWM to "break:" as best as I can figure, it completely loses track of which windows are minimized and loses all z-order information for all non-minimized windows. Alt-tab no longer works. Clicking in windows does not give them focus (it actually makes them disappear altogether).

**Steps to reproduce the bug**
Create a packaged Win32/.NET Core Project Reunion project, set the package host application as the startup project, add a breakpoint in the main project's `App.xaml.cs` in the `App` constructor prior to the call to the `InitializeComponent` then run the packaged app with the debugger attached.

**Expected behavior**
Not this :)

**Screenshots**
N/A

**Version Info**
Project Reunion 0.8

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@jeffStall Is this something your team would know about?

**Comment by harvinders** [comment]
We are also facing this issue, the whole windows freeze. It is very annoying, currently I am putting the windows to sleep and then resuming the debug. Though sometime, only sometimes, it works.

**Comment by mqudsi** [comment]
@harvinders are you also on 18363?

**Comment by harvinders** [comment]
Yes, on 1909

**Comment by mqudsi** [comment]
I have experienced this once more under 19045 w/ the latest version of Windows App SDK. It all depends on where the breakpoint is placed.
