### ISSUE TITLE
How will Store handle apps updated from uwp to winui3

### ISSUE THREAD

**Issue by MUJaCHe66** [microsoft/microsoft-ui-xaml#5551]
If a user on desktop has a uwp version of an app installed which gets a newer winui3 version uploaded to the store, will the user get updated to the newer winui3 version?

**Comment by Link1J** [comment]
It will handle it like updating a UWP app to a UWP app. The store really doesn't care what technology is used to draw the UI, only that it is packaged in a way it can handle. And the Windows App SDK and WinUI3 aren't changing how you package your apps for the store.

**Comment by MUJaCHe66** [comment]
OK thanks.

**Comment by StephenLPeters** [comment]
@MikeHillberg and @ryandemopoulos FYI

**Comment by bkudiess** [comment]
Thanks @Link1J for the answer. I'll be closing the issue as the question has been answered. @MUJaCHe66, please re-open this issue and let us know if still have any questions.
