### ISSUE TITLE
TabView (TabViewListView) swallowing mouse events and causing UX issues

### ISSUE THREAD

**Issue by ZodmanPerth** [microsoft/microsoft-ui-xaml#5554]
**Describe the bug**

The negative space that would be filled by the `Background` property of the `TabViewListView` part of `TabView` control swallows mouse events.  This causes two issues:
* When the `TabView` is used in the Window Title Bar (and appropriately styled to not have a background), users cannot drag the Window near the tab visuals.  This degrades the user experience and we have received negative customer feedback about it.
* When the `TabView` is used in the Window Title Bar and there is no margin between the `TabView` and the top of the Window, the Window edge above the `TabViewListView` part cannot dragged to resize the Window.

**Steps to reproduce the bug**

I've attached a Visual Studio demo project that can be used to replicate the problem.  I've also attached a link to a walkthrough video that demonstrates the problem.  Please watch the video which demonstrates the issues using the attached project:

Run the attached project.  There are 3 related issues:

1. Attempt to drag the Window by negative space:
    *  at an area that is _not_ occupied by the `TabViewListView`, observe the Window can be dragged.
    *  at an area that _is_ occupied by the `TabViewListView` but not the tabs visuals, observe the Window _cannot_ be dragged.
1. Attempt to resize the Window by the top border:
    *  above the area that is _not_ occupied by the `TabViewListView`, observe the Window can be resized.
    *  above the area that _is_ occupied by the `TabViewListView`, observe the Window _cannot_ be resized and that the mouse pointer does not change to a "resize" pointer.
1. Maximise the Window, jam the mouse pointer (or finger on touch devices) to the top of the screen, and drag down.
    *  On an area that is _not_ occupied by the `TabViewListView`, observe the Window can be dragged down.
    *  On an area that _is_ occupied by the `TabViewListView`, observe the Window _cannot_ be dragged down.

**Expected behavior**

1. The normal Window should be draggable by the area occupied by the `TabViewListView` that is not occupied by the tab visuals.
1. Dragging down on a maximised Window should be allowable on the area occupied by the `TabViewListView` .
1. The Window should be resizable by the edge of the Window above the area occupied by the `TabViewListView`.

I suspect the `TabViewListView` is too greedy in consuming mouse pointer events in order to provide tear-away tabs.  When the pointer is above the `TabViewListView` but not over a tab, it should not swallow mouse pointer events; it should allow the events to pass through to controls beneath the `TabViewListView` (such as the `WindowDragRegion` control defined in the attached demonstration project).

**Screenshots**

Please see the video below for a more thorough demonstration of the issues.

![TabViewIssueScreenShot](https://user-images.githubusercontent.com/546368/126947354-cb99f503-64b1-4ad2-b4e1-458605731736.jpg)

**NuGet package version:**

Microsoft.UI.Xaml 2.6.1

**Which Windows versions did you see the issue on? Leave blank if you didn't try that version.**

Windows 10 Pro, Version 21H1, OS build 19403.1110

**Which device form factors did you see the issue on? Leave blank if you didn't try that device.**

Desktop

**Additional context**

Demonstration project: 
[TabViewIssueReproProject.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6876110/TabViewIssueReproProject.zip)

Link to video walkthrough:
https://1drv.ms/v/s!Aj0ttYc6Owxpk9gUiQnfylMf4fo_oQ

**Comment by StephenLPeters** [comment]
Thanks @ZodmanPerth, seems like an important issue.

Could you try setting the the TabView's background property to Transparent and see if that resolves the issue?  Maybe also try setting the TabViewListView's background to transparent as well, although looking at the code it looks like that should already be null.

**Comment by ZodmanPerth** [comment]
I've tried all 4 combinations of `Background="transparent"` on those controls; no noticeable affect was observed.

Given Windows itself isn't receiving mouse events for dragging the window chrome at the edge I suspect the control is being too heavy-handed with it's mouse event handling in or around that `TabViewListView` control.

**Comment by StephenLPeters** [comment]
Thanks for trying that!

@codendone could you lend your expertise here?

**Comment by codendone** [comment]
The problem is the `ScrollViewer`, which consumes the mouse input regardless of background. The desired behavior could be achieved In the sample app with these changes:
* Change the `TabViewListView` element from Padding="4,8,4,0" to Padding="4,0,4,0". In this sample you could override that in Theme.TabView.xaml, or you could override style by putting this in a ResourceDictionary in your app.xaml: `<Thickness x:Key="TabViewHeaderPadding">4,0,4,0</Thickness>`
* Push the UI down back to the desired spot, such as by setting Margin="0,8,0,0" on the `TabViewListView`.

**Comment by ZodmanPerth** [comment]
Thanks @codendone.  Applying those changes does reduce the size of the `ScrollViewer` to the padded area of the `TabViewListView` control.  

For comparison with the original screenshot, the `TabViewListView` is the area in Gold and the draggable TitleBar area is in green:

![image](https://user-images.githubusercontent.com/546368/127831059-ebc16ab4-14f1-4639-9725-73fb33f8a64e.png)

However your solution is a workaround because the small area to the left of the first tab that is inside the `ScrollViewer` does not allow the mouse events through to drag the Title Bar.  While this may be acceptable in this sample application because the area is so small, in our real application where we have styled the tab visuals much more there is a lot more negative space.

Is there a way to prevent the `ScrollViewer` from consuming the pointer input?  In this case of `TabViewListView` the zoom mode is disabled on the `ScrollViewer` so it would make sense that it didn't consume the pointer events in there airspace where no child controls are present.

Should I be raising this as an issue with the `ScrollViewer` itself?

**Comment by StephenLPeters** [comment]
@RBrid FYI, I think it is by design that the scrollviewer consumes mouse input even where it doesn't have items,  You can still manipulate the scroll viewer from anywhere in its footprint.

@ZodmanPerth you could simply change the right padding of the TabViewHeaderPadding to a larger value which might be sufficient if you have tab header content that doesn't change size.  If you need the scrollviewer to be dynamically sized I'm not there's anything exposed to make this easy.

I think the proper solution here would be to ensure that the scrollviewer's MaxWidth is bound to its content's ActualWidth.

**Comment by ZodmanPerth** [comment]
The problem with the `ScrollViewer` consuming events in the empty space is clear when you have a non-square tabs.  For example, imagine the case where the edges of the tabs were a 45 degree angle; this causes a lot of empty space on the left and right edges of the first/last tabs, and very large spaces between tabs.  Users try and drag the Title Bar by this space and report it as an issue when it doesn't work.
While tabs designed like this may look very ugly it demonstrates a valid case for the `TabView` as a restylable component; one cannot simply make the ScrollViewer as small as possible to work around this issue.

**Comment by ZodmanPerth** [comment]
The core issue here seems to be that the `ScrollViewer` doesn't play nicely when used in the the Title Bar area of an app extending into that area of the window.  Because of `ScrollViewer` consumes all mouse events, it causes a real problem for controls like `TabView` which are prime candidates for such placement.

**Comment by StephenLPeters** [comment]
I agree, but I don't think this warrants changing how scrollviewers work in general.  We could discuss making tab view's scrollviewer special and behave differently.  Another issue though is that ScrollViewer's code is not in Winui2, it is still shipped in system xaml.  So if we did make a change to how ScrollViewers function to fix this it would only be fixed for end users using the next version of windows 11. Or a fix could be made in Winui3.

If someone restyled their tab view items to look as you described, they could also restyle the scrollviewer container to have an edge at a 45 degree angle as well, right?

**Comment by ZodmanPerth** [comment]
I don't think you can restyle a `ScrollViewer's` region, but I would be very happy to be proven wrong.  In UWP we only have rectangular clipping regions, so that wouldn't help.  Possible workaround I can think of are:
* Create a transparent mask on top of the `ScrollViewer` using a separate control, and somehow keep the shape of the mask in sync with the `ScrollViewer's` visual children and scroll position.  This would be very difficult to achieve.
* Create a delegate image of the `ScrollViewer` which the user interacts with and marshall the requried mouse events to the real `ScrollViewer`.  Degree of difficulty is very high. This workaround flies in the face of what XAML is for.

If updating `ScrollViewer` is an option, an alternate mode could be turned on via some boolean property (`AllowInputEventPassthrough`) rather than creating a special case for the `TabView`.  This would allow developers to opt-in to that mode without breaking existing dependencies, while facilitating `ScrollViewers` to be used in many more use cases where it overlays XAML controls in the z order (this appears to have been a persistent issue across other XAML technologies such as WPF as well, so it would be fantastic to finally have a solution for it).

I believe greedy consumption of input events by a control that are not relevant to the features of that control goes against the philosophy of XAML component development.  i.e., the `ScrollViewer` should only consume the input events it needs to provide it's own functionality and allow unconsumed events to pass-through/bubble down.  It should not be marking unused events as handled.

What you mention about WinUI is disconcerting.  Our organisation produces large UWP apps for the Store and are hoping for a path into WinUI to open up and allow us to transition over to WinUI3.  Missing components like `ScrollViewer` will make that transition impossible, resulting in a difficult and costly re-write of our products into some other technology like MAUI or UNO.  We're waiting with bated breath for what WinUI3 will bring.
