### ISSUE TITLE
The CalendarView doesn't sync a current month view with the selected date

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#5555]
**Describe the bug**
Hi, if I've set the MinDate of CalendarView it doesn't scroll into view by a selected date. It displays MinDate's month instead of the month with the selected date.

**Steps to reproduce the bug**
```xaml
<Window
    x:Class="App3.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid x:Name="root">
      <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Top">
          <CalendarView x:Name="calendar"/>
      </StackPanel>
    </Grid>
</Window>
```
```csharp
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
            this.root.Loaded += Root_Loaded;
        }

        private void Root_Loaded(object sender, RoutedEventArgs e) {
            calendar.MinDate = DateTime.Now.AddMonths(-2); // 5/26/2021
            calendar.SelectedDates.Clear();
            calendar.SelectedDates.Add(DateTime.Now.AddDays(1)); // 7/27/2021
        }
    }
```
**Expected behavior**
When the SelectedDate changed the displayed month should be correspond

**Screenshots**
![image](https://user-images.githubusercontent.com/47348109/126967364-b485a860-5a66-4336-bba4-f83dfb88b2e9.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes|

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@RBrid have you seen this before? Do you know the intended design?

**Comment by RBrid** [comment]
@StephenLPeters, @alexdi220, 
Yes, this is by design. Selection is irrelevant when it comes to displayed dates.  CalendarView.SetDisplayDate(DateTimeOffset) is the method to change the dates shown.   Selected and displayed dates are two distinct concepts.

**Comment by alexdi220** [comment]
@RBrid It's weird behavior. Can't imagine if anyone wants to select and display various dates. In addition, it's not the MVVM way, an user can't bind just one property to manage the calendar. Instead of this to set a single selected date we write a code like this:
```csharp
void Select(DateOffset date){
    calendarView.SelectedDates.Clear();
    calendarView.SelectedDates.Add(date);
    calendarView.SetDisplayDate(date);
}
```
Would be nice if you could change this. Another must-have feature is the SelectedDate (get\set) property to bind a date in a single selection mode.
