### ISSUE TITLE
Solution is closed and another  solution is opened when try to start WinUI solution

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5556]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Solution-is-closed-and-another--solution/1485332)._

---
[severity:I'm unable to use this version]
It could be that it happens since I use latest Windows 11 build. And before this version it worked well. This solutions that I am trying to open is just simple solution with no extra code but generated when hitting create new project.

---
#### Feedback Bot on 7/25/2021, 07:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@alwu-msft FYI

This description doesn't make very much sense to me, but maybe this reminds you of something?
