### ISSUE TITLE
Xaml editor shows member functions not properties when trying to use path statement.  Project Reunion 0.8.1 Windows 10 21H1

### ISSUE THREAD

**Issue by markinnh** [microsoft/microsoft-ui-xaml#5557]
Xaml Editor shows member functions not properties in xaml editor
Project Reunion 0.8.1
Windows 10 21H1

![image](https://user-images.githubusercontent.com/32527524/126877869-b9348db0-5cb4-4904-884d-cd8767650ea8.png)

**Comment by StephenLPeters** [comment]
@RealTommyKlein FYI
