### ISSUE TITLE
NavigationView TopNav not yet rendered OverFlow items showing up due to resizing have wrong foreground(style) after theme change

### ISSUE THREAD

**Issue by beervoley** [microsoft/microsoft-ui-xaml#5559]
**Describe the bug**

When I'm trying to resize the window causing Overflow items (that haven't been shown yet) in TopNav to appear in PrimaryList, the overflow items that are shown have wrong foreground (see gif attached).
It only happens if I start in Dark mode (system wide), open XCG and then change the Theme inside XCG to Light.
**Steps to reproduce the bug**

1. Start in system wide Dark Mode.
2. Open XCG -> change XCG theme to Light.
3. Resize the window to smallest possible.
2. Open Navigation View Page.
3. Scroll to TopNav example.
4. Resize the window to allow some Oveflow Items to move to Primary List.
5. Observe their foreground(style).

**Expected behavior**

Moved from Overflow Items should have correct foreground(style) matching other items that are already rendered in the Primary List.
**Screenshots**

I've hovered over the elements after they become visible, that turned their foreground color to the correct one.
![navview_bug](https://user-images.githubusercontent.com/21356912/127073990-0b52bd69-ef79-4599-a394-cfa87ba8a93a.gif)

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by beervoley** [comment]
@StephenLPeters @karenbtlai FYI

**Comment by StephenLPeters** [comment]
What causes them to populate with the right foreground?

**Comment by beervoley** [comment]
I hovered over them

**Comment by StephenLPeters** [comment]
This seems pretty bad to me.  @beervoley do you have an idea what might be going on? I think we should get this into a servicing fix.

**Comment by karenbtlai** [comment]
@beervoley I'm unable to repro. Are you still seeing this on your machine?
