### ISSUE TITLE
TreeView drag items does not update ItemsSource ObservableCollection

### ISSUE THREAD

**Issue by frauenholz** [Microsoft/microsoft-ui-xaml#556]
**Describe the bug**
When dragging TreeViewItems that are part of an ItemsSource that is bound to by an ObservableCollection, it is expected that the bound ObservableCollection would be automatically updated, and that the  ObservableCollection.CollectionChanged event would fire, like in a ListView as described by this article by Jerry Nixon 
http://blog.jerrynixon.com/2013/06/walkthrough-reordering-items-in.html

there is no other way to keep the underlying ObservableCollections synchronized with the TreeView.  The TreeView.DragItemsStarting and TreeView.DragItemsCompleted events do not provide enough info to synchronize the affected ItemsSources

**Steps to reproduce the bug**
1) add the attached files to a UWP blank app
2) put a break point in the two CollectionChanged event handlers
3) re-order TreeView items via drag and drop
4) the underlying CollectionChanged events do not fire

**Expected behavior**
the underlying CollectionChanged events do fire 

**Screenshots**

**Version Info**
Windows 10 Pro 1809

NuGet package version: 
Microsoft.NETCore.UniversalWindowsPlatform v6.2.8

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Windows 10 Pro        | Yes  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Additional context**

[TreeViewDragItemsSourceObservable_MainPage.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3076297/TreeViewDragItemsSourceObservable_MainPage.zip)

**Comment by jevansaks** [comment]
Thanks for reporting this!

**Comment by dpaulino** [comment]
I'm seeing this same issue as well when binding the ItemsSource with an ObservableCollection. I would appreciate if this bug can be investigated soon!

**Comment by dpaulino** [comment]
@kaiguo just wanted to say I really appreciate the quick PR to fix this bug. Hoping it will be reviewed and merged soon.

**Comment by kaiguo** [comment]
@dpaulino It's checked in now 🎉

**Comment by dpaulino** [comment]
@kaiguo wow thanks! Which nuget package version will this become available in?

**Comment by kaiguo** [comment]
> @kaiguo Kai Guo FTE wow thanks! Which nuget package version will this become available in?

It'll be in the next release which is 2.2 I think.

If you want to try it now, you can get the package from CI pipeline https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=12259. There should be an `Artifacts` button on top right corner when the build finishes.

**Comment by jevansaks** [comment]
Yes definitely @dpaulino please try the CI build! We'll push a 2.2 prerelease package next week. You can feel free to ship to the store with a prerelease package if you want. Or if you want to wait for the release, 2.2 is scheduled to be shipped officially in July.

**Comment by dpaulino** [comment]
How do I install the CI package into my UWP solution? Is there a wiki somewhere I can follow? Sorry for the dumb question 😅

**Comment by kaiguo** [comment]
> How do I install the CI package into my UWP solution? Is there a wiki somewhere I can follow? Sorry for the dumb question 😅

https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#package-sources

You can add a NuGet source and point it to `https://dev.azure.com/ms/_apis/resources/Containers/2243452?itemPath=drop%2FMicrosoft.UI.Xaml.2.2.190425001-prerelease.nupkg`

The url above is from the "Copy download URL" button.
![20190425181557](https://user-images.githubusercontent.com/4424330/56777404-368d0180-6786-11e9-899a-dbc09fa4d581.png)

**Comment by dpaulino** [comment]
Much easier than I thought! I will try this soon. Thanks very much!

**Comment by dpaulino** [comment]
I seem to be having some issues setting up that URL as the package source
![image](https://user-images.githubusercontent.com/7649589/56785420-f2abf380-67a9-11e9-9ec8-e1443fab0bdd.png)
![image](https://user-images.githubusercontent.com/7649589/56785428-ffc8e280-67a9-11e9-8fe5-c4f964874604.png)

Am I doing something wrong?

**Comment by kaiguo** [comment]
Yeah didn't work for me either😓
Just download the package then, and update package source to be your local path. That should work.
