### ISSUE TITLE
EnableCollectionSynchronization - worker thread modifying ObservableCollection

### ISSUE THREAD

**Issue by DaRochaRomain** [microsoft/microsoft-ui-xaml#5560]
I'm trying to learn how to use WinUI, and I am currently stuck with something. I have a worker thread that is regularly doing modification on an ObservableCollection. With WPF I would have used https://docs.microsoft.com/fr-fr/dotnet/api/system.windows.data.bindingoperations.enablecollectionsynchronization?view=net-5.0 but I can't find it with WinUI 3. Is there an alternative?

**Comment by StephenLPeters** [comment]
@MikeHillberg Do you know?

**Comment by DaRochaRomain** [comment]
any ideas? Or do I have to use the DispatcherQueue now?

**Comment by StephenLPeters** [comment]
The person who would know for sure is out of the office.  DispatcherQueue is definitely the golden path, but there may be something else available in this space.

**Comment by DaRochaRomain** [comment]
Ok then I'll keep using this while waiting for a response. DispatcherQueue is nice but I would rather not use it when I don't have too.

**Comment by AndrewFromJapan** [comment]
So, DispatcherQueue is the recommended way to update an ObsevableCollection regularly?

**Comment by LadderLogic** [comment]
yes please! Bring the collection sync  to win ui 3. Injecting dispatcher queue into business logic gets ugly quick.
