### ISSUE TITLE
Question: Does WinUI 3 provides any event for GridView that will occur when an item is bringing into the viewport or leaving the viewport

### ISSUE THREAD

**Issue by dylech30th** [microsoft/microsoft-ui-xaml#5567]
I've used to using a custom virtualized container in WPF, it will raise the Unloaded event when an item is leaving the viewport and the Loaded event when an item is bringing into the viewport. This allows me to load and unload some memory-consuming objects on-demand, such as  `BitmapImage`, but it seems that such events won't occur in WinUI 3 when the item is leaving the viewport. I wonder if there is any similar mechanism that will allow me to do the same thing.

**Comment by StephenLPeters** [comment]
Assuming you are using a virtualizing panel then the Loaded and Unloaded events are probably what you are looking for.  While this isn't exactly when the element becomes visible, it is when the element is close to the effective viewport which allows you to scroll it into view without having to wait for the asset to load.

You could also derive this information from the EffectiveViewPortChanged event https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.effectiveviewportchanged?view=winrt-20348
