### ISSUE TITLE
A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll

### ISSUE THREAD

**Issue by KanniyappanP** [microsoft/microsoft-ui-xaml#5572]
I am trying to build the WinUI Desktop library project with latest project reunion upgrade 0.8.1, but i am getting a below issue while build the project.

`\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Windows.targets(50,5): error NETSDK1148: A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.`

But i am not using this package in my lib project.

`<PackageReference Include="Microsoft.Bcl.Build" Version="1.0.21" ExcludeAssets="all" />`

My machine configuration:

VS 2019 16.10.2
SDK 6.0.100-preview.4.21255.9
SDK 5.0.302 also has the same issue.
Any workaround would be appreciated.

Thanks.

**Comment by StephenLPeters** [comment]
@alwu-msft FYIU

**Comment by manodasanW** [comment]
@KanniyappanP do you happen to have any FrameworkReference update for Microsoft.Windows.SDK.NET.Ref in one of your csproj?  And do you happen to see any warning along with the error, it should have additional details on what depends on what and why this error is appearing.

**Comment by KanniyappanP** [comment]
No, i didn't used Microsoft.Windows.SDK.NET.Ref framework in any of our project.

Please find the warnings below.

` Found conflicts between different versions of "WinRT.Runtime" that could not be resolved.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2202,5): warning MSB3277: There was a conflict between "WinRT.Runtime, Version=1.2.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" and "WinRT.Runtime, Version=1.3.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2202,5): warning MSB3277:     "WinRT.Runtime, Version=1.2.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" was chosen because it was primary and "WinRT.Runtime, Version=1.3.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" was not.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2202,5): warning MSB3277:     References which depend on "WinRT.Runtime, Version=1.2.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" [C:\Users\KanniyappanPanneerSe\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.19041.16\lib/WinRT.Runtime.dll].
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2202,5): warning MSB3277:         C:\Users\KanniyappanPanneerSe\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.19041.16\lib/WinRT.Runtime.dll`

**Comment by manodasanW** [comment]
@KanniyappanP do you happen to have any reference to Microsoft.Windows.CsWinRT in your projects and if so which version.  Also can you comment on what version of the .NET SDK do you have installed and are using to build your project.  I am trying to figure out where the 1.3.0.0 reference is coming from and why conflict resolution isn't choosing the higher version.  I believe if you update to the latest .NET SDK 5.0.302 servicing update, that should resolve your issue.

@angelazhangmsft FYI

**Comment by KanniyappanP** [comment]
I didn't use the `Microsoft.Windows.CsWinRT` reference in my projects and i have installed the .NET SDK 5.0.302 and in addition 6.0.4 (for MAUI) in machine. Also, referred the `microsoft.windows.sdk.net.ref` reference version as 10.0.19041.16 in my project.

**Comment by manodasanW** [comment]
To confirm, you still see the issue with .NET SDK 5.0.302?  

And can you clarify what you mean by 

> Also, referred the `microsoft.windows.sdk.net.ref` reference version as 10.0.19041.16 in my project

**Comment by KanniyappanP** [comment]
Yes, please see the image below.

![image](https://user-images.githubusercontent.com/56436173/127611351-add3aa21-0699-437b-94f5-d07a1630d37e.png)

![image](https://user-images.githubusercontent.com/56436173/127611636-ca8fdede-2533-4b8b-aad5-da5fc7e17d7d.png)

![image](https://user-images.githubusercontent.com/56436173/127611666-5f8e3f6a-01b2-46e2-a809-c62a3b47307d.png)

**Comment by manodasanW** [comment]
Thanks @KanniyappanP that was helpful.  I have a feeling what is happening is VS is actually using the .NET 6 SDK and given you are on preview 4, it has the .16 Version of the Windows SDK projection and 1.2 version of WinRT.Runtime.  You have a later version of the .NET 5 SDK with the 1.3 version of WinRT.Runtime but I think it is not actually being used.

If you update your .NET 6 SDK to preview 6, I think that should get you the 1.3 version of WinRT.Runtime.  If that doesn't work, we can loop in someone from the .NET SDK to take a look.
