### ISSUE TITLE
WinUI2: ContentDialogs no longer have an open animation

### ISSUE THREAD

**Issue by xezrunner** [microsoft/microsoft-ui-xaml#5573]
**Describe the bug**
The default ContentDialogs have lost their open animation with WinUI 2.6. 
They now appear instantly, as opposed to playing a slight zoom animation. The close animation still works.

**Steps to reproduce the bug**
1. Open an application that has ContentDialogs (Files, XAML Control Gallery)
2. Invoke a ContentDialog.
3. Observe the lack of animation.

**Expected behavior**
ContentDialogs used to and are supposed to have an open animation as well.

**Screenshots / screen recordings**

https://user-images.githubusercontent.com/8061077/127360292-5372a966-c79d-4029-bb3b-140b14afa4ff.mp4

**Version Info**

WinUI: 2.6.0 and 2.6.1
OS: Windows 11 21H2 build 22000.100 (Dev channel - `co_release`)

NuGet package version: 
Microsoft.UI.Xaml 2.6.1

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

**Additional context**
The Settings app in Windows 11 probably uses a custom ContentDialog implementation/style, as the animation still exists there.

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by IstvanKor** [comment]
If you change the target version of your project to Windows 11 SDK (22000), then open animation of ContentDialogs works correctly in both Win11 and Win10. Min version can be left as your request.

**Comment by xezrunner** [comment]
Keeping this open in light of the [Cleanup of Stale Issues](https://github.com/microsoft/microsoft-ui-xaml/discussions/8638).

This still is broken, in both WinUI 2 and by default in WinUI 3.

**Comment by ranjeshj** [comment]
There are currently no plans to fix this issue in WinUI2. We are looking at the same issue in WinUI3 using this bug -https://github.com/microsoft/microsoft-ui-xaml/issues/8476
