### ISSUE TITLE
App crash when changing ControlsResourcesVersion.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/microsoft-ui-xaml#5574]
[ControlsResourcesVersionRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6895030/ControlsResourcesVersionRepro.zip)
**Describe the bug**
When changing the ControlsResourcesVersion from Version2 to Version1, the attached sample app crashes.

**Steps to reproduce the bug**
1. Run the attached sample:
1. Click "Change version" twice.

**Expected behavior**
No crash.

**Version Info**

NuGet package version: Microsoft.UI.Xaml.2.6.1-prerelease.210709001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.100)              | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
We don't support switching between Version1 and Version2 of ControlsResourcesVersion at runtime.

**Comment by chingucoding** [comment]
@StephenLPeters Out of curiosity, what would it take to change that?

**Comment by StephenLPeters** [comment]
I think it might be theoritically possible but the cost and risk to reward is very high.  The way XCR constructs its dictionaries would need to change and we'd need to invent some way for the app to reconstruct state with an entirely new set of styles...
