### ISSUE TITLE
CommandBar Overflow Menu defaults to go Upwards, no Property/Resource to Override behavior?

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#5578]
**Describe the bug**
CommandBar originally was intended to be below content. However, it's getting more common to use it above content now as a Toolbar. In this case, the fact that the Overflow menu defaults to opening upwards (unless there's no space) is odd.

_In fact the [design guidance](https://docs.microsoft.com/windows/apps/design/controls/command-bar#placement) calls out being able to use them at the **top** or bottom of your app._

This is effecting the Windows Community Toolkit, as our `TabbedCommandBar` control creates a 'ribbon' like experience using NavigationView+CommandBar, but then the Overflow Menu is opening upwards which for a top-level navigation control is odd. Though, as mentioned, I've seen more devs using CommandBars outside the bottom of their apps compared to the Win 8 days. 

You can see this in the XAML Controls Gallery example which puts it over the content in the sample and produces an odd looking result:

![image](https://user-images.githubusercontent.com/24302614/127393404-7a0a0bc5-12df-46ae-8b66-6ee5fc5bfc45.png)

**Steps to reproduce the bug**
1. Open the XAML Controls Gallery
2. Open the CommandBar sample
3. Click on "Add Secondary Commands"
4. Click on "..." to open up menu:

**Expected behavior**
Since the `CommandBar` is being displayed more as a top-level element above the content (vs. it's original below content usage), I'd expect the overflow menu to open down vs. up.

I would expect a property on `CommandBar` or a resource value that could override this behavior. Or at least an alternate style with the opposite behavior.

It could also be great if based on it's alignment or something it could detect better which direction it should open in.

**Screenshots**
![image](https://user-images.githubusercontent.com/24302614/127393910-105d6f44-b5d1-426e-ac0c-3fdc1b49f131.png)

**Version Info**
NuGet package version: 2.6.1

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 20H1 (19043)              | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by jonasnordlund** [comment]
Yes, I'm designing a WinUI 2.6 app for Windows 11 here and the SecondaryCommands menu is always opening upwards except if I place it within a `Page.TopAppBar`. But this is hard to work with because I need to not have it be the very topmost thing because I'm rendering a custom title bar for Mica material reasons that needs this spot.

I've tried to hack my way around it somehow but can't figure anything out. I wonder how they did it in the Windows 11 File Explorer which has a secondary command menu that opens downwards, yet a custom (?) title bar as well above it?

**Comment by Medality** [comment]
With XAML Controls Gallery 1.2.21, the overflow menu is opening downwards. It seems the issue has been fixed on their side, as I've still got the old behavior on my app (WinUI 2.7).
Does anyone know how they managed to do that?
