### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'EETypeRva:0x00118808' to type 'EETypeRva:0x0007BDC8'.

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5579]
**Describe the bug**

System.InvalidCastException: Unable to cast object of type 'EETypeRva:0x00118808' to type 'EETypeRva:0x0007BDC8'.

**Steps to reproduce the bug**

WelcomePage is splashscreen of my app, and WelcomePage inherits from PageBase

```
public PageBase()
{
    this.Transitions = new TransitionCollection()
    {
        new NavigationThemeTransition()
        {
           DefaultNavigationTransitionInfo =  new SlideNavigationTransitionInfo()
           {
               Effect = SlideNavigationTransitionEffect.FromRight
           }
        }
    };
}
```

**Expected behavior**

no exception.

**Screenshots**

![image](https://user-images.githubusercontent.com/12285582/127442126-8616c8cf-55c4-48d7-8329-d4aeea8ab854.png)

**Version Info**

only repro on Windows 17134 & 17133.

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Very strange... sounds like some .net type...  I'm not sure what to make of this.

**Comment by HppZ** [comment]
that is not external!
