### ISSUE TITLE
Using Microsoft.UI.Xaml overwrites existing XAML styles even for non-MUX controls

### ISSUE THREAD

**Issue by Sergio0694** [Microsoft/microsoft-ui-xaml#558]
**Describe the bug**

I'm using a few custom styles in my app, and as soon as I've included the `Microsoft.UI.Xaml` library in my app, I noticed that some of my styles were being overwritten by the library, which is not what I was expecting.
I just want to use specific controls from the `Microsoft.UI.Xaml` library, with the included styles (eg. the `NavigationView` or `TeachingToolTip` controls), but I do _not_ want the library to also replace or modify my existing styles in any way.
For instance, I noticed that including the lib automatically replaced my `MenuFlyoutPresenter` style.

**Steps to reproduce the bug**

1. Create an empty UWP app
2. Create a custom style for a control. For instance:
```xml
<!--Sample style, the colors are just to show the issue-->
<Style TargetType="MenuFlyoutPresenter">
    <Setter Property="Background" Value="Green"/>
    <Setter Property="BorderThickness" Value="2"/>
    <Setter Property="BorderBrush" Value="Yellow"/>
    <Setter Property="MinWidth" Value="220"/>
</Style>
```
3. Include the `Microsoft.UI.Xaml` NuGet package and resource dictionary
4. Add a `Button` with a context menu, for instance:
```xml
<Button Content="Test">
    <Button.ContextFlyout>
        <MenuFlyout>
            <MenuFlyoutItem Text="Test button">
                <MenuFlyoutItem.Icon>
                    <FontIcon Glyph="&#xE134;"/>
                </MenuFlyoutItem.Icon>
            </MenuFlyoutItem>
        </MenuFlyout>
    </Button.ContextFlyout>
</Button>
```
5. Run the app and open the context menu. You'll notice that the `Microsoft.UI.Xaml` library will have replaced the custom style, even if the controls in question (the `Button`, `MenuFlyout`, etc.) used here are not from the NuGet package, but from the default SDK.

**Expected behavior**

The custom styles should not be overwritten by the library.

**OS**
`Windows 10 17763.x`

**NuGet package version:** 
`Microsoft.UI.Xaml 2.1.190405004`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |  Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@Sergio0694 can you be more specific about step 2 for the custom style? Where is that style specified? Is it on the Page or in app.xaml? If it's in app.xaml, what does that look like relative to where you put XamlControlsResources?

**Comment by Sergio0694** [comment]
Hi @jevansaks - the style was defined in a `ResourceDictionary` that was referenced by the `ResourceDictionary.MergedDictionaries` property in the `App.xaml` file.
The `WinUI` dictionary was declared right below it.
I followed your suggestion and tried to move the `WinUI` dictionary right before the reference to this one, and I can confirm that the local styles take precedence in that case.

I mean, this isn't a big issue anyway, as this was just happening for styles with no resource key, so the ones autoloaded by the XAML framework.

Still though, I think maybe adding a small note/disclaimer in the docs advising devs using custom styles to be careful of the order in which they declare them might be helpful for others 🙂

**Comment by chrisglein** [comment]
> Still though, I think maybe adding a small note/disclaimer in the docs advising devs using custom styles to be careful of the order in which they declare them might be helpful for others

Yep, we're going to do exactly that :) We'll add notes to hte docs to make it clear that the WinUI resources need to be first in the order.

**Comment by Sergio0694** [comment]
That's perfect, and I'm glad that working around this was just a matter of changing the order of the declared resource dictionaries. Thanks for the help and for the quick follow up, have a nice day! 😄

**Comment by jevansaks** [comment]
Re-opening this to track updating the documentation with this information.

**Comment by jesbis** [comment]
We've updated these to hopefully make the resource loading clearer:

1. The [WinUI Getting Started documentation](https://docs.microsoft.com/uwp/toolkits/winui/getting-started)
2. The [post-install readme](https://github.com/Microsoft/microsoft-ui-xaml/blob/86a5c42d581330b4b849d35dcfad13951b594d75/build/NuSpecs/readme.txt)
