### ISSUE TITLE
Navigation footer showing arrow keys (up and down buttons)

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/microsoft-ui-xaml#5585]
**Describe the bug**
App Type: WinUI Desktop App
I am using Navigation Footer items and even with one item in the list, App is displaying weird up and down arrow keys that are clickable. I disabled the regular settings page and using my own page as settings under the footer items.

Sample code:
```
    <muxc:NavigationView x:Name="navigationView" SelectionChanged="NavigationView_SelectionChanged"
		IsSettingsVisible="False" IsBackButtonVisible="Collapsed"
		BorderBrush="{ThemeResource TextControlBorderBrush}" BorderThickness="1" PaneDisplayMode="Auto" OpenPaneLength="250"
		Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<muxc:NavigationView.MenuItems>
			<muxc:NavigationViewItem x:Name="Files" Content="Files" >
				<muxc:NavigationViewItem.Icon>
					<FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE118;" />
				</muxc:NavigationViewItem.Icon>
			</muxc:NavigationViewItem>
		</muxc:NavigationView.MenuItems>
		<muxc:NavigationView.FooterMenuItems>
			<muxc:NavigationViewItem x:Name="Settings" Content="Settings" Icon="Setting" IsSelected="true"/>
		</muxc:NavigationView.FooterMenuItems>

		<muxc:NavigationView.Content>
			<Frame x:Name="contentFrame"/>
		</muxc:NavigationView.Content>
    </muxc:NavigationView>
```

**Expected behavior**
Arrow keys should be visible only if there are items that are not visible on the UI based on the window height.

**Screenshots**
![image](https://user-images.githubusercontent.com/52011872/127535040-7d66ee34-7485-4a57-b8a1-de54f1d2bd95.png)

**Version Info**
WindowsAppSDK NuGet package version: 0.8.1
OS version(s): All

**Comment by StephenLPeters** [comment]
Should be fixed by the 2.6 port of winui2.
