### ISSUE TITLE
Question: make ListDetailsView two areas resizable

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [microsoft/microsoft-ui-xaml#5586]
can i make the list to content areas in the `ListDetailsView` resizable by the user something like the grid `GridSplitter`

![image](https://user-images.githubusercontent.com/7858946/127559886-6e1e304e-6a57-4491-9b2f-4c1520882b25.png)

**Comment by kmgallahan** [comment]
Wrong repo

https://github.com/CommunityToolkit/WindowsCommunityToolkit

**Comment by ahmed-abdelrazek** [comment]
> 
> 
> Wrong repo
> 
> https://github.com/CommunityToolkit/WindowsCommunityToolkit

thanks
