### ISSUE TITLE
Setting NavigationView.IsPaneVisible = False at Runtime Crash  The App

### ISSUE THREAD

**Issue by F8RDev** [microsoft/microsoft-ui-xaml#5587]
**Describe the bug**
Setting `NavigationView.IsPaneVisible = False` at runtime crash the apps.

**Steps to reproduce the bug**

1. The bugs only happen if I add `ThemeDictionaries` entries in `App.xaml`, for example:
```
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Dark">
                    <ResourceDictionary.MergedDictionaries>
                        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
                        <ResourceDictionary   Source="/Themes/DarkTheme.xaml" />
                    </ResourceDictionary.MergedDictionaries>
                </ResourceDictionary>
                <ResourceDictionary x:Key="Light">
                    <ResourceDictionary.MergedDictionaries>
                        <XamlControlsResources  xmlns="using:Microsoft.UI.Xaml.Controls"/>
                        <ResourceDictionary Source="/Themes/LightTheme.xaml" />
                    </ResourceDictionary.MergedDictionaries>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>
 ```

2. Run attached project and click `Toogle Nav Pane Visibility` button:
[NavigationView_Bugs.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6904370/NavigationView_Bugs.zip)

**Expected behavior**
The `NavigationView` Pane should toggle the visibility.

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Having two instances of XamlControlsResources in your application.Resources is very strange and I would not be surprised if this is the source of your issues.  Insead you should be able to merge XCR with the dictionary you are constructing here.

Even better is to put your resources into the XamlControlsResources.MergedDictionaries like we recommend here: https://github.com/microsoft/microsoft-ui-xaml/blob/main/build/NuSpecs/readme.txt
