### ISSUE TITLE
CommandBarFlyout opened with mouse sometimes opens taller like it was opened with touch and then snaps to a thinner size

### ISSUE THREAD

**Issue by llongley** [microsoft/microsoft-ui-xaml#5589]
Right-click to open a CommandBarFlyout.  Sometimes, its AppBarButtons will be sized as though we opened with touch, and then snap to a thinner width corresponding to their mouse size.  It's very quick and you may need to do it multiple times to repro the issue, but it's noticeable when you know what to look for.

**Comment by yaira2** [comment]
This is still an issue in WinUI 3.

**Comment by yaira2** [comment]
@DmitriyKomin has this been resolved?
