### ISSUE TITLE
Mica doesn't work when applied to an UserControl

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5590]
**Describe the bug**
When you apply Mica to an UserControl, it doesn't work.

**Steps to reproduce the bug**

1. Create a new UWP project
2. Install WinUI 2.6
2. Replace Page/Frame with UserControl
3. Apply Mica to the UserControl using muxc:BackdropMaterial.ApplyToRootOrPageBackground="True".
4. Deploy and run the app on Windows 11 and see the issue

**Expected behavior**
Mica should be applied on the surface.

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.100)              | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@jevansaks thoughts?

**Comment by jevansaks** [comment]
By default does UserControl draw a background? I can't remember but I feel like Control and UserControl are weird in that they have the Background property but it's up to the template/code-behind to do something with the value. 

Take Mica out of the picture, what happens if you set UserControl's Background="Orange". Do you see anything?

**Comment by Jaiganeshkumaran** [comment]
> By default does UserControl draw a background? I can't remember but I feel like Control and UserControl are weird in that they have the Background property but it's up to the template/code-behind to do something with the value.
> 
> Take Mica out of the picture, what happens if you set UserControl's Background="Orange". Do you see anything?

That's right, the background that I set doesn't actually apply to the content inside by default however at least I should be able to apply Mica to a Grid for example.

**Comment by mdtauk** [comment]
I thought Mica can only be applied to the Window/Page background, at the lowest level surface?

**Comment by Jaiganeshkumaran** [comment]
> I thought Mica can only be applied to the Window/Page background, at the lowest level surface?

The lowest level surface need not be a Page. You can use a UserControl as the root element or any other control for that matter.

**Comment by jevansaks** [comment]
> > I thought Mica can only be applied to the Window/Page background, at the lowest level surface?
> 
> The lowest level surface need not be a Page. You can use a UserControl as the root element or any other control for that matter.

This is true. But the behavior of the BackdropMaterial attached property is that it sets the Background property in the fallback case so it needs to be hooked up correctly in the control. @ranjeshj you can use this issue to track updating the documentation?
