### ISSUE TITLE
ContentDialogs buttons are part of tab-navigation even when the dialog is hidden.

### ISSUE THREAD

**Issue by sylveon** [microsoft/microsoft-ui-xaml#5596]
**Describe the bug**
In WinUI 2.6, when declaring a ContentDialog within a .xaml file, the buttons will be part of tab-navigation even though the dialog is not visible

**Steps to reproduce the bug**

1. Create a new UWP project
2. Add WinUI 2.6
3. In `MainPage.xaml`, write the following:
   ```xaml
   <Page
       x:Class="App11.MainPage"
       xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
       xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
       xmlns:local="using:App11"
       xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
       xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
       mc:Ignorable="d">
   
       <Grid>
           <ContentDialog  x:Name="Dialog"
               d:Visibility="Collapsed"
               Content="Hello world"
               PrimaryButtonText="Yes"
               SecondaryButtonText="No"
               CloseButtonText="Cancel"
               DefaultButton="Primary" />
   
           <Button Content="Show dialog" Click="Button_Click" />
       </Grid>
   </Page>
   ```
4. In `MainPage.xaml.cs`, add a callback:
   ```cs
   private async void Button_Click(object sender, RoutedEventArgs e)
   {
       await Dialog.ShowAsync();
   }
   ```
5. Launch the app
6. Use tab to navigate through the app.
7. Observe there are 3 tab-navigatable buttons which are invisible and perfectly centered, and the focus indicator shows up in the app.

**Expected behavior**
You can only tab-navigate to the button in the page, but once the ContentDialog opens, you can only tab-navigate to buttons in the ContentDialog

**Screenshots**
![image](https://user-images.githubusercontent.com/6440374/127724247-432344d0-2bd0-40ff-a7d7-e717413d3314.png)

See the focus indicator here. If you call FocusManager.GetFocusedElement at this point, the PrimaryButton (or another button) from the ContentDialog is returned.

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes (system XAML islands) |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Hmm, doesn't seem to repro in the MuxControlsTestApp or the XamlControlsGallery but the code you provided does repro the issue...

**Comment by chingucoding** [comment]
I would like to look into this.
