### ISSUE TITLE
Inheriting from a XAML page within the same project fails to compile in C++/WinRT with /std:c++20

### ISSUE THREAD

**Issue by sylveon** [microsoft/microsoft-ui-xaml#5597]
**Describe the bug**
After upgrading to VS 17.0 Preview 2, inheriting from another XAML page within the same project results in a compile error when combined with `/std:c++20` or `/std:c++latest`

**Steps to reproduce the bug**

1. Create a new UWP project using C++/WinRT
2. Set the langage version to C++ 20 or latest in project settings
3. Make `MainPage` unsealed in the IDL
4. Create a new XAML page in the project (named `BlankPage` in the rest of these steps)
5. Remove or rename the `MyProperty` property from `BlankPage.cpp`, `BlankPage.h` and `BlankPage.idl` to avoid conflicts with the base class
6. Make that page inherit from `MainPage` from IDL: `runtimeclass BlankPage : MainPage` (don’t forget `import "MainPage.idl";`)
7. Add `#include "MainPage.h"` to `BlankPage.h`
8. Update `BlankPage.xaml` to declare a root object of type `local:MainPage` instead of Page
9. Compile the project
10. Observe the `'to_abi': no matching overloaded function found` error

**Expected behavior**
The code should compile correctly and run.

**Screenshots**
![image](https://user-images.githubusercontent.com/6440374/127731459-1b847e46-351f-48b3-8264-9f41e0d6cead.png)

**Version Info**

NuGet package version: 
This issue happens whether WinUI 2 is used or not.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes (system XAML islands) |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This happens with the Windows SDK version 22000.100, I think it needs to use the v143 toolset as well.

Developer Community issue: https://developercommunity.visualstudio.com/t/Inheriting-from-a-XAML-page-within-the-s/1491603?entry=myfeedback

Sample repro project: [BlankApp1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6919373/BlankApp1.zip) (edit 2020-08-02: updated the zip, I somehow managed to upload a zip attempting to use a cppwinrt version that didn't exist on NuGet)

**Comment by asklar** [comment]
CC @RealTommyKlein @sotteson1

**Comment by ChrisGuzak** [comment]
for MS folks this is http://task.ms/35009721

**Comment by StephenLPeters** [comment]
@ShashankNay and @RealTommyKlein FYI

**Comment by sylveon** [comment]
Is there any chance of this being fixed in the 22000 SDK before the stable release of Windows 11 (or in a post-release servicing update to the 22000 SDK?)

I really do not want to be stuck using VS 2019 until the next major SDK release (which seems to be in late 2022, if the existing release cycle is anything to go by).

**Comment by asklar** [comment]
I spoke with sylveon offline, here's some more info:

> the xaml compiler generates a class with two types in the hierarchy (one for each page backed by XAML code) that implement `IComponentConnector` (via `implements<Self, IComponentConnector>`)
>
> `to_abi` (signature below) is called at some point internally by cppwinrt. but the C++ compiler can't figure out which template parameters to deduce, since there are two valid options (both `impl::producer<MyBasePage, IComponentConnector>` and `impl::producer<HomePage, IComponentConnector>`). This normally works out fine because `winrt::implements` is only used once in the entire inheritance hierarchy.
```
    template <typename I, typename D>
    impl::abi_t<I>* to_abi(impl::producer<D, I> const* from) noexcept
```
>
>
> this was always invalid, and clang even rejects it in C++17 mode. increased standards compliance in VS 2022 made the issue surface in MSVC as well, when C++20 or C++latest mode is enabled 
>
>i rely on too many C++20 features to rollback to C++17 mode (even then, being stuck on C++17 is also a bummer)
>
>see https://github.com/microsoft/cppwinrt/issues/990 and https://github.com/microsoft/cppwinrt/issues/993

**Comment by RealTommyKlein** [comment]
Thanks for the report, took some time to look into this and make the right fix.  The fix will be available for Windows.UI.Xaml in an upcoming Windows Insider Preview SDK release (likely available late January or early February), and for WinUI 3/Windows App SDK it will be in the Windows App SDK 1.1 release.

Using this pattern (a Xaml control/page with an associated `.xaml` file deriving from another control/page with its own `.xaml` file) will now raise a warning if the compiler is able to detect it.  It's valid but inefficient as the base class's `.xaml` will be fully loaded, only to be overwritten by the derived class's `.xaml` content.

**Comment by sylveon** [comment]
Thanks for the update, and the fix!

In my case, I have a `UIElement` property on the base page, bind a `ContentPresenter` to the property and then set `[contentproperty]` to point to this property in IDL. The result is that pages which inherit from it will not overwrite the base, but rather get ameliored by it. It's a useful pattern to share common behavior between pages, and doesn't result in innefficiency! I can understand the warning being there by default though, but I'd like a way to silence it for such use cases.

For example:
```cs
[contentproperty("InnerContent")]
unsealed runtimeclass BasePage : Windows.UI.Xaml.Controls.Page
{
    Windows.UI.Xaml.UIElement InnerContent;
    static Windows.UI.Xaml.DependencyProperty InnerContentProperty { get; };

    // some common logic here.
}
```
```xaml
<Page x:Class="BasePage">
    <!-- Common logic here -->
    <!-- ... -->
    <ContentPresenter Content="{x:Bind InnerContent}" />
</Page>
```

Then, I inherit from BasePage
```xaml
<BasePage x:Clase="DerivedPage">
    <!-- Content put here will show within BasePage's ContentPresenter -->
</BasePage>
```

**Comment by RealTommyKlein** [comment]
Oh yeah, that design makes sense.  The warning is erring on the side of "don't shoot your foot off" performance-wise :smile:. 
 Xaml compiler warnings can be disabled with the `SuppressXamlWarnings` MSBuild property - it takes in a semicolon separated list of Xaml compiler warning codes (sans the `WMC` prefix) to suppress.  If you want to disable the new upcoming warning (`WMC1508`), you can add this to your project:
```
<PropertyGroup>
   <SuppressXamlWarnings>1508</SuppressXamlWarnings>
</PropertyGroup>
```

**Comment by sylveon** [comment]
Perfect, thank you very much!

**Comment by sylveon** [comment]
Hmm, I'm on the 22543 SDK and this issue still happens. @RealTommyKlein, is this expected?

**Comment by RealTommyKlein** [comment]
@sylveon - strange, the fix is in the 22543 SDK.  Can you sanity-check this repro in your setup?  It should pass when the target SDK is 22543 (already set in the repro) and fail on earlier SDK versions, which is what I saw locally:

[WUXCppWinRTDerivedXClass.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7972591/WUXCppWinRTDerivedXClass.zip)

**Comment by sylveon** [comment]
I had to do a clean build to force the XAML codegen to trigger again, merely upgrading the SDK still used the old codegen - my bad! The issue is resolved now, thanks :)
