### ISSUE TITLE
Open source of Hub control

### ISSUE THREAD

**Issue by xperiandri** [microsoft/microsoft-ui-xaml#5598]
# Proposal: Open source of Hub control
I need Hub control in Uno Platform
https://github.com/unoplatform/uno/issues/5249#issuecomment-890324172
The easiest way of porting is to take original Hub control sources and migrate to Uno Platform.

## Rationale
* Hub control is a crucial control for an app home page
* Uno platform is the major motivation to use UWP and WinUI and drastically expand its spreading

**Comment by StephenLPeters** [comment]
As a part of Winui3 we will be making the framework open source, this will need to wait for that.

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI

**Comment by xperiandri** [comment]
What is the time frame of that?

**Comment by akilarajesh1313** [comment]
Hello @xperiandri, this is our backlog and we don't expect to get to it till sometime next year. Hope that helps!

**Comment by codendone** [comment]
The Hub source is all shared now, with https://github.com/microsoft/microsoft-ui-xaml/blob/winui3/release/1.5-stable/dxaml/xcp/dxaml/lib/Hub_Partial.cpp as one of the main files. This code is in ABI style, so it won't map easily to C# or C++/WinRT code.
