### ISSUE TITLE
Determinate Progress Ring shows the same result when "Value" property setted to 99 and 100

### ISSUE THREAD

**Issue by movpushmov** [microsoft/microsoft-ui-xaml#5599]
**Describe the bug**
Determinate Progress Ring shows the same result when "Value" property setted to 99 and 100

**Steps to reproduce the bug**
1. Go to Xaml Controls Gallery -> Status and Info -> Progress Ring
2. Set "Value" to 99
3. Now set "Value" to 100
4. See the bug

**Expected behavior**
Progress Ring must be vicious circle if Value = 100

**Screenshots**
![image](https://user-images.githubusercontent.com/49155506/127737454-e2905852-9344-49ba-a0d2-6ba518cd3237.png)
![image](https://user-images.githubusercontent.com/49155506/127737445-246e35ff-e976-485f-bfe6-8be0e985d8ce.png)

**Version Info**
WinUI 2.6

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by chingucoding** [comment]
Thank you for filing this issue, however I think this is a duplicate of #3787.

**Comment by movpushmov** [comment]
Yes, this is duplicate. Sorry.
