### ISSUE TITLE
System.MissingMethodException: Method not found: 'Microsoft.System.DispatcherQueue Microsoft.UI.Xaml.DependencyObject.get_DispatcherQueue()'

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#5601]
### **Prism Create Region fails**

has API changed anywhere ? Prism was working with earlier versions. 

![image](https://user-images.githubusercontent.com/43340959/127750538-2d3659ab-8752-4a1e-93f0-f03c6ea94943.png)

**Steps to reproduce the bug**

1. Update to ReUnion 0.8.1
2. Create Prism Region :

`<ContentControl prism:RegionManager.RegionName="{x:Bind inf:RegionNames.TabView}" Grid.ColumnSpan="2" Grid.Row="0" />`

**Version Info**
```
	<ItemGroup>
		<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.1" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.1" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.1" />
		<Manifest Include="$(ApplicationManifest)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Prism.DryIoc.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Prism.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Uno.Core" Version="2.4.0" />
	</ItemGroup>
```

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | No  |
| Surface Hub        | No |
| IoT                |  No |

**Additional context**

[Dump](https://drive.google.com/file/d/1LhB5L8HtqWlH5dp4h-ZUw0zv2vfetRdA/view?usp=sharing)

**Comment by sigmarsson** [comment]
The `DispatherQueue` is existing, is it more like a **Prism** issue ?

**Comment by codendone** [comment]
In Reunion 0.8 DispatcherQueue moved from the Microsoft.System to the Microsoft.UI.Dispatching namespace. The error indicates this version of Prism is still using the old namespace and needs to be updated for 0.8.

**Comment by sigmarsson** [comment]
Thank you much @codendone !
