### ISSUE TITLE
Winui 3, Blank App does not build/ also Latest Github Microsoft-ui-xaml examples does not build

### ISSUE THREAD

**Issue by professordave** [microsoft/microsoft-ui-xaml#5603]
**Describe the bug**

Create a new blank WinUI app.
Try to build it.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The source file for this compilation can be found at: "C:\Users\dkafriss\AppData\Local\Temp\ccf1e6d3-87f9-4612-9126-bacaf99895d4.txt"	App59	C:\Users\dkafriss\.nuget\packages\microsoft.projectreunion.winui\0.8.1\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets	257	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3758	An error has occurred during compilation. error CVT1101: cannot open 'c:\Users\dkafriss\AppData\Local\Temp\tuf5pycu\CSC537CD49A921A4E6588C0AA408B3584C8.TMP' for reading	App59	C:\Users\dkafriss\.nuget\packages\microsoft.projectreunion.winui\0.8.1\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets	257	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4175	The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property.	App59	C:\Users\dkafriss\.nuget\packages\microsoft.projectreunion.winui\0.8.1\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets	257	

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'Microsoft.ProjectReunion.InteractiveExperiences 0.8.1' was restored using 'net5.0-windows10.0.19041, .NETCoreApp,Version=v3.1, .NETCoreApp,Version=v3.0, .NETCoreApp,Version=v2.0, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, net5.0-windows10.0.18362, net6.0-windows10.0.18362, .NETFramework,Version=v4.6.1' instead of the project target framework 'UAP,Version=v10.0.18362'. This package may not be fully compatible with your project.	App59 (Package)	C:\Users\dkafriss\source\repos\App59\App59\App59 (Package)\App59 (Package).wapproj	1	

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/10290573/127757286-78a0b952-be71-49e0-92f1-2d3ec1c30e20.png)

![image](https://user-images.githubusercontent.com/10290573/127757241-945f9324-ef15-4a9e-9aa4-cfff7ba6df99.png)

![image](https://user-images.githubusercontent.com/10290573/127757295-c0081510-a67c-48cd-a85c-9ee7daa83f24.png)
``

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

Windows 10 Enterprise
19043.1110
21H1
Windows Feature Experience Pack 120.2212.3530.0

Visual Studio 2019 16.10.4

Also tried with 
Visual Studio 2019 Preview
16.11.0 Preview 3.0

When using Preview the project type is .net Maui

![image](https://user-images.githubusercontent.com/10290573/127757400-df74d52c-d72e-4ad3-8c1a-73d88bbfb25b.png)

![image](https://user-images.githubusercontent.com/10290573/127757413-87e4ee54-6425-421e-9fd9-d9072362e472.png)

Downloaded the Xaml controls Gallery
from
https://github.com/microsoft/Xaml-Controls-Gallery/tree/winui3

![image](https://user-images.githubusercontent.com/10290573/127757462-4e20c267-7b07-4d43-8324-8939089f231e.png)

![image](https://user-images.githubusercontent.com/10290573/127757493-d3015ec2-76f1-4d02-9ba9-1ebf7de9e54e.png)

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@alwu-msft any idea whats going on here?

**Comment by evelynwu-msft** [comment]
This appears to be an issue with the local environment, not WinUI-related. For future reference, Visual Studio's [Report a problem](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) feature should be used if this sort of error occurs again.
