### ISSUE TITLE
CommandBar can be scrolled while expanded which can cause the popups to position beyond the bounds of the app

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#5604]
(titles are hard)
**Describe the bug**

When a CommandBar is expanded, and in a ScrollViewer, it can be scrolled, which will cause the flyout to move beyond the bounds of the app and the popup to extend beyond the bounds of the parent container.

**Steps to reproduce the bug**

1. Open muxcg and go to commandbar page
2. shrink window until you can scroll
3. expand CommandBar
4. scroll up and down
5. flyouts move up and down

**Expected behavior**

It should dismiss, or scrolling should be disabled.

**Screenshots**

https://user-images.githubusercontent.com/59544401/127757214-b943bcf5-89cc-4a66-836d-0c478b8fa439.mp4

![image](https://user-images.githubusercontent.com/59544401/127757369-8d2bd49d-a30b-44e4-9226-f0317b696d2f.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.100)              | yes    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

****

**Comment by StephenLPeters** [comment]
Thanks @winston-de .

Did you find this issue in another application or just XamlControlsGallery? My intuition is that commandbar inside of a scrollviewer is rare.

Looks like an issue with our control, but a possible work around would be to listen to the EffectiveViewportChanged event on the commandbar and programmatically close it when the viewport changes.
