### ISSUE TITLE
Changing width of SplitButton's chevron button results in unwanted padding

### ISSUE THREAD

**Issue by janfaracik** [microsoft/microsoft-ui-xaml#5605]
**Describe the bug**
Changing the width of SplitButton's chevron button using `<x:Double x:Key="SplitButtonSecondaryButtonSize">16</x:Double>` results in unwanted right padding. This prevents a developer from resizing the secondary button in a SplitButton.

**Steps to reproduce the bug**
1. Create a new page/control in a UWP app with Microsoft.UI.Xaml 
2. Add a SplitButton to the page 
3. Set the width of the SplitButton's chevron button 
4. Notice that the padding is incorrect and the chevron is too far to the left

```
<UserControl ...>
    <UserControl.Resources>
        <x:Double x:Key="SplitButtonSecondaryButtonSize">16</x:Double>
    </UserControl.Resources>

    <Grid>
        <muxc:SplitButton>
            Hello world
        </muxc:SplitButton>
    </Grid>
</UserControl>
```

**Expected behavior**
The chevron should be centered horizontally regardless of the width given.

**Screenshots**
With the secondary button size set to 16px:
![image](https://user-images.githubusercontent.com/43062514/127774355-a0636897-ce20-4853-ac17-4f92c841ca91.png)
What it looks like without setting the size (default):
![image](https://user-images.githubusercontent.com/43062514/127774336-b87bbb39-46a0-4cfb-9596-ac385ceff48c.png)

**How to fix?**
SplitButton currently applies a 12px right padding to the chevron, this needs to be set to 0px. The content alignment of the button should be `Center`, and the horizontal alignment of the animated icon should be `Center` too.

https://github.com/microsoft/microsoft-ui-xaml/blob/7180ad3d3998bcbf2c8fa028ffb1ce3049d78228/dev/SplitButton/SplitButton.xaml#L297

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.6.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by mrlacey** [comment]
Related questions for the team/designers:
- Should any of the templates contain hardcoded inline values like the `Margin` in the example above?
- When resource values can be overridden (such as `SplitButtonSecondaryButtonSize` in the above example) what testing is done to see how changes to these values impact other parts of the design/style?
- Is there a definition of how much of a control's default style can be changed without fully retemplating the control?
- Is the expectation that if a developers changes or overrides anything in the default styles it's on them to retemplate the control or make other changes to ensure everything works correctly?

**Comment by StephenLPeters** [comment]
Seems appropriate to expose the padding value as a resource to enable customizing this behavior. Your prescription could also work too. @janfaracik would you be interested in contributing the fix? :)

However you should keep in mind accessibility concerns while making these changes. We chose this layout width to keep the button touch friendly. If you change to a 16px width your users might find it frustrating to use with touch.





> Related questions for the team/designers:
> 
> * Should any of the templates contain hardcoded inline values like the `Margin` in the example above?

It depends, exposing a value as a resource isn't free, but does open up a point of customization that can be really valuable to not needing to retemplate, which comes with a ton of its own issues.  We try to anticipate which resources would be most valuable and expose those.

> * When resource values can be overridden (such as `SplitButtonSecondaryButtonSize` in the above example) what testing is done to see how changes to these values impact other parts of the design/style?

Today, most of this testing is done manually at the time of creation,  If a developer decides to change some of these values it is also their responsibility to make sure the new values they chose are functional.

> * Is there a definition of how much of a control's default style can be changed without fully retemplating the control?

No, nothing as defined as that.

> * Is the expectation that if a developers changes or overrides anything in the default styles it's on them to retemplate the control or make other changes to ensure everything works correctly?

We try to expose as many customization points as we think is appropriate, if you want to make further adjustments you can either open an issue on us and we will evaluate and decide if exposing that is appropriate, or you can retemplate the control.
