### ISSUE TITLE
WinUI 3 - ListBox drag and drop causes a crash

### ISSUE THREAD

**Issue by DeadlyEmbrace** [microsoft/microsoft-ui-xaml#5607]
**Describe the bug**
A ListBox is used to display controls that can be dragged and dropped to rearrange the controls. To indicate the drop position the appropriate border of the control where the dragged item will be dropped is changed. Dragging and dropping a different control in a different position a few times will result in a crash with the error message posted below.

**Steps to reproduce the bug**
1. Download the repository [here](https://github.com/DeadlyEmbrace/ListBox-dragdrop-error) that contains a repro build.
2. Ensure that the `ListViewDragDropIssue (Package)` is set as the startup project.
3. Press F5 to run the project.
4. Drag and drop a control from one position into another one a few time.
5. After anywhere between 2 and 5 drag and drop operations a crash will occur.

**Expected behavior**
Application should not crash and allow the user to continue dragging controls for as long as they wish.

**Screenshots**
![image](https://user-images.githubusercontent.com/2103860/127886669-d4996f2e-dff3-4c39-9a76-7b01b62fbb11.png)

**Version Info**
WinUI 3 Windows App SDK 0.8.1
Packaged Win32 desktop application
Windows 11 Pro build 22000.100

NuGet package version: 
Microsoft.ProjectReunion 0.8.1
Microsoft.ProjectReunion.Foundation 0.8.1
Microsoft.ProjectReunion.WinUI 0.8.1
Microsoft.Windows.CsWinRT 1.3.3
PropertyChanged.Fody 3.4.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.100)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Does not appear to happen if logic to change the borders `ListPage.xaml.cs` line 57 - 69 are commented out.

**Comment by StephenLPeters** [comment]
We strongly recommend using ListView instead of ListBox.  Is there a reason you are not?

**Comment by DeadlyEmbrace** [comment]
> We strongly recommend using ListView instead of ListBox. Is there a reason you are not?

I looked into Listview but unfortunately it only offers vertical alignment of its content. I also need the ability to lay the content out horizontally which means that a ListView will not serve my purpose.

**Comment by StephenLPeters** [comment]
In that case does GridView fulfill your needs?

**Comment by DeadlyEmbrace** [comment]
Just gave it a try and it fulfills my needs perfectly.
Thanks for pointing it out 😄
