### ISSUE TITLE
Microsoft.UI.Xaml v2.6.1 App Opens up with NavigationView in a semi expanded state 

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#5612]
**Describe the bug**
App opens in this semi expanded state. I think at this window width, it should be collapsed. Clicking the NavigationView menu button puts it in the expanded state WITH the expected button texts and image header. Clicking it again will collapse it--what I expected to begin with.

**Expected behavior**
At this window width, I believe the NavigationView should be collapsed. 

**Screenshots**
App startup with semi expanded state (seems abnormal)
![image](https://user-images.githubusercontent.com/3663297/127971294-5af5194b-2506-4933-a788-24fc86b04b07.png)
App with expanded NavigationView (what seems normal)
![image](https://user-images.githubusercontent.com/3663297/127971693-48616a09-e869-4590-b0cf-ff52172cc259.png)
App with collapsed NavigationView (what I expect when the app starts)
![image](https://user-images.githubusercontent.com/3663297/127971942-674741f9-e4e4-4da1-8d2d-cb4e0118d820.png)

**Version Info**
2.6.1

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19044)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I don't remember this on 2.5.0

**Comment by StephenLPeters** [comment]
@karenbtlai have you seen this?

**Comment by karenbtlai** [comment]
@myokeeh Can you include detailed repro steps or a test app? I'm unable to repro this.

**Comment by myokeeh** [comment]
I just tried creating one from scratch with Windows Template Studio, but can't reproduce this behavior with a mostly blank NavigationView app.

I don't know where to start on providing an app that repros this behavior--I have to gut it substantially.

Although, it's quite reproducable switching between 2.5.0 and 2.6.0/2.6.1. This is definitely a problem starting with 2.6.0.

2.5.0 NavigationView starts collapsed as expected,
2.6.0/2.6.1 NavigationView starts in that semi-expanded state.

**Comment by myokeeh** [comment]
@karenbtlai Looked into this more and seeing that this isn't just a startup issue. Resizing width of the app seems to have that extra or semi-expanded state when sizing down.

Sizing app up (wider): 
- Completely collapsed (0 width NavigationView, just the button)
- NavigationView is a narrow strip with Buttons show up
- NavigationView is wide with buttons with labels

Sizing app down (narrower):
- NavigationView is wide with buttons with labels
- NavigationView is still wide with Buttons only but labels disappear (same as first screenshot)
- Completely collapsed

Cycling through the sizing up/sizing down reproduces the behavoir above.

**Comment by myokeeh** [comment]
This appears related: At the narrowest width of the NavigationView (collapsed), the NavigationView button overlaps with an image I have in the NavigationView.PaneHeader, but I believe it's still because the NavigationView is in this semi-expanded state.

![image](https://user-images.githubusercontent.com/3663297/128240799-3c2a041a-8437-48f3-92d1-0b9926fb52b8.png)

**Comment by JonasLara** [comment]
I don't know if this relates but i got a misaligned NavigationView.HeaderTemplate out-of-the-box

<img width="960" alt="Screenshot 2021-08-05 222825" src="https://user-images.githubusercontent.com/66033534/128461507-8558e4fa-16b8-47dd-90f9-18f5f2b53256.png">

**Comment by myokeeh** [comment]
@JonasLara apparently by design: https://github.com/microsoft/microsoft-ui-xaml/issues/5405 🤷🏽‍♂️

**Comment by myokeeh** [comment]
@karenbtlai I still have difficulty getting this to reproduce with a simpler app. The problem still disappears with v2.5, though.

**Comment by karenbtlai** [comment]
Hey @myokeeh, turns out there's an internal bug (with a repro app) that I just pushed a fix for (#5712) that seems very similar to this. Would you be able to take a look if changes from this PR resolves the issue?

**Comment by myokeeh** [comment]
> Hey @myokeeh, turns out there's an internal bug (with a repro app) that I just pushed a fix for (#5712) that seems very similar to this. Would you be able to take a look if changes from this PR resolves the issue?

I might have to wait for a version released via NuGet, then. I'm not sure how to go about what you mentioned.

**Comment by myokeeh** [comment]
@karenbtlai I just tested this on 2.7.0-prerelease.210816001. It appears the semi-expanded bug is fixed, but when the app is launched at the app's narrowest width, it still has this button overlap bug with the NavigationView expanded: https://github.com/microsoft/microsoft-ui-xaml/issues/5612#issuecomment-892905721

![image](https://user-images.githubusercontent.com/3663297/130015744-24d358dc-c2d3-4262-a927-464e09cb47d6.png)

I believe it should be collapsed--just the icons showing on the left.

**Comment by myokeeh** [comment]
@karenbtlai I just tested this on 2.7.0-prerelease.210816001. It appears the semi-expanded bug is fixed, but when the app is launched at the narrowest width, it still has this button overlap bug with the NavigationView is expanded: https://github.com/microsoft/microsoft-ui-xaml/issues/5612#issuecomment-892905721

![image](https://user-images.githubusercontent.com/3663297/130015744-24d358dc-c2d3-4262-a927-464e09cb47d6.png)

I believe it should be collapsed--just the icons showing on the left.

**Comment by myokeeh** [comment]
@karenbtlai, following up. It appears to be mostly fixed on 2.7.0-prerelease.210816001 except for the issue above.

**Comment by myokeeh** [comment]
@karenbtlai @StephenLPeters, still present in 2.7.0-prerelease.210913003

**Comment by myokeeh** [comment]
Any updates to this? Overall, v2.7 NavigationView seems to have regressed.

**Comment by myokeeh** [comment]
From what I can see, it appears 2.8.0-prerelease.220118001 addressed these issues.
