### ISSUE TITLE
Clunky behaviour with NumberBox and soft keyboard on touchscreen

### ISSUE THREAD

**Issue by dtynewydd** [microsoft/microsoft-ui-xaml#5614]
**Describe the bug**
When selecting a number box on a touch device, the current value is selected, then the first value input is also selected, causing the user to overwrite the first character.

**Steps to reproduce the bug**
NumberBox on page in WinUI3 app. Value initially set in code-behind, Xaml or by user. No bindings.

1. NumberBox has value "100"
2. User taps NumberBox, value is highlighted, soft keyboard appears
3. User types "2"
4. NumberBox has value "2"
5. NumberBox value of "2" is highlighted
6. User types "0"
7. NumberBox value of "2" is replaced with "0"

**Expected behavior**
User's initial input should not be highlighted.

**Version Info**

NuGet package version: 
[Microsoft.ProjectReunion 0.8.1]
[Microsoft.ProjectReunion.Foundation 0.8.1]
[Microsoft.ProjectReunion.WinUI 0.8.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  No |  Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            | No |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  No |
| Tablet                 | Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@dtynewydd do you know if this is the case in Winui2 as well?

**Comment by dtynewydd** [comment]
I just fired up a basic app using winui2 with a NumberBox on the homepage and didn't see the same behaviour @StephenLPeters

**Comment by StephenLPeters** [comment]
@Austin-Lamb I think the soft keyboard behavior is owned by the Reach team, thoughts here?

**Comment by dtynewydd** [comment]
@Austin-Lamb @StephenLPeters has there been any progress on this?

**Comment by ranjeshj** [comment]
@dtynewydd This does not seem to repro anymore. If it does with latest WinAppSDK, could you report back/activate ?
