### ISSUE TITLE
WinUI hosted MFC application and UWP application crashed when more than 122 ListView/GridView loaded. Is it any restriction for the number of ListView/GridView loaded on an application ?

### ISSUE THREAD

**Issue by VrindaJayan** [microsoft/microsoft-ui-xaml#5621]
Dynamically loaded 125 ListView(with or without listview item) on a WinUI hosted MFC application.ListView loaded inside a Grid.

Application crashed with an exception.
Exception details from output tab -
Exception thrown at 0x00007FFBE5B44ED9 (KernelBase.dll) in SampleApp.exe: WinRT originate error - 0x80070057 : 'Style1.xaml is not a valid absolute URI.'.
Exception thrown at 0x00007FFBE5B44ED9 (KernelBase.dll) in SampleApp.exe: WinRT originate error - 0x80070057 : 'Style2.xaml is not a valid absolute URI.'.
Exception thrown at 0x00007FFBE5B44ED9 (KernelBase.dll) in SampleApp.exe: WinRT originate error - 0x80070057 : 'Style3.xaml is not a valid absolute URI.'.
'SampleApp.exe' (Win32): Loaded 'C:\Windows\System32\directmanipulation.dll'. 
'SampleApp.exe' (Win32): Loaded 'C:\Windows\System32\Windows.UI.Xaml.Controls.dll'. 
Unhandled exception at 0x00007FFBE5C1BD3E (KernelBase.dll) in SampleApp.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x00000264CBF44AC0, 0x0000000000000001).

**Comment by StephenLPeters** [comment]
@codendone or @alwu-msft  ring a bell for either of you?

**Comment by alwu-msft** [comment]
We need a repro project. This isn't exactly a common scenario.

**Comment by VrindaJayan** [comment]
> We need a repro project. This isn't exactly a common scenario.
Project is available at :
[https://github.com/VrindaJayan/Sample_StressTestApp/tree/main/SampleApp/SampleApp](url)
