### ISSUE TITLE
WebView/WebView2 memory leak 

### ISSUE THREAD

**Issue by tj-jyk** [microsoft/microsoft-ui-xaml#5622]
**Describe the bug**

WebView2 (and old WebView) exhibits a memory leak when creating and deleting the control in a loop. In my application, the user can change the content every (x) seconds and with a WebView/WebView2 control the user will get a memory leak. I opened the same issue [here](https://github.com/microsoft/WindowsAppSDK/issues/1158)

**Steps to reproduce the bug**

[GitHub repo](https://github.com/tj-jyk/WebView_WebView_memory_leak)

1. Start a loop / a timer `var timer = new DispatcherTimer
			{
				Interval = TimeSpan.FromSeconds(1)
			};
			timer.Tick += Timer_Tick;
			timer.Start();`
2.  In a loop logic find the old WebView/WebView2 control in a DOM `VisualTreeHelper.GetChildrenCount(parent);  ..... VisualTreeHelper.GetChild(parent, i) ...`)
3.  Remove the old WebView from the DOM `(VisualTreeHelper.DisconnectChildrenRecursive(rootGrid);)`
4.  For a WebView call `webViewToRemove.Navigate(new Uri("about:blank"));` For a WebView2:  `webViewToRemove.Close(); `
5. Add a new WebView/WebView2 control to the DOM `rootGrid.Children.Add(newWebView);`
6. Application crashes after 15 minutes.

**Screenshots**

![image](https://user-images.githubusercontent.com/29145276/127843163-d17ed5a5-18a8-4c60-bd2d-e25d30f7a497.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview] 
[Microsoft.Web.WebView2: 1.0.902.49]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Marv51** [comment]
I would recommend checking if WebView2 "tabs" actually get closed. Maybe check if the number of edge processes in Task Manager increases over time? Alternatively, the Edge Task-Manager (Shift+Esc) from the WebView2 Dev-Tools (Right click on WebView2 click "Inspect") has more info about open tabs and other processes.

**Comment by StephenLPeters** [comment]
@predavid @codendone FYI

**Comment by AlexLablaiksSAP** [comment]
For anyone coming across this issue, this is also reproducible in a simple UWP app with at NavigationView as well. In lieu of an actual fix from Microsoft, you can work around this by attaching a function to the [Unloaded](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.unloaded?view=winrt-26100) event which calls [WebView2.Close()](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2.close?view=winui-2.8)
