### ISSUE TITLE
Question: MVVM best practice

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5624]
1, Can I put command in UI binding Model, when?
2, If I have a Button in View, click the Button to scroll view to top, should I put the logic in cs file or ViewModel?
3, How ViewModel control View? for example, scroll view to top.

**Comment by disgyze** [comment]
I'm not a MVVM expert, but here's my thoughts:

1. No. ICommand is used to communicate between a View and ViewModel;
2. It's UI-related stuff. Use code-behind, behaviors or dependency inversion (DI) (by passing an interface that would control scroll viewer, for example);
3. It uses commands/properties/DI to communicate with view.

In your particular case (scrolling to top as a result of a button click) I would prefer using a behaviors (see attached sample).
[ScrollToTopSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6934896/ScrollToTopSample.zip)
