### ISSUE TITLE
Opening a SplitButton flyout via touch moves the dropdown symbol to the left of the text 

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#5625]
**Describe the bug**

**Steps to reproduce the bug**

1. Create a new application with WinUI 2.6
2. Add the following code

```xaml
<CommandBar>
  <CommandBar.PrimaryCommands>
    <AppBarElementContainer>
      <muxc:SplitButton Content="Test">
        <muxc:SplitButton.Flyout>
          <MenuFlyout>
            <MenuFlyoutItem Text="Item"/>
          </MenuFlyout>
        </muxc:SplitButton.Flyout>
      </muxc:SplitButton>
    </AppBarElementContainer>
  </CommandBar.PrimaryCommands>
</CommandBar>
```

3. Open the flyout via touch
4. Observe that the dropdown symbol gets moved to the left of the text

**Expected behavior**

Symbol position should not change

**Screenshots**

![image](https://user-images.githubusercontent.com/38145893/128190131-160a47ed-3f24-4e42-917b-aa6974bb6e81.png)

![image](https://user-images.githubusercontent.com/38145893/128189632-3de04bcd-540e-4933-b7bb-805bd1374b7f.png)

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ranjeshj consider for 2.6.2
