### ISSUE TITLE
Question: In PointerMovedEvent event handler, PointerRoutedEventArgs GetCurrentPoint throws 0x80004005

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5632]
0   System.Runtime.InteropServices       0x7ff84189ef71   System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
1   __Interop                            0x7ff80a2faba2   __Interop.ComCallHelpers.Call($__ComObject __this, RuntimeTypeHandle __typeHnd, Int32 __targetIndex, Void* arg0, Void* arg1) in Call at 15732480:0
2   ???                                  0x7ff80a332e2f   __Interop.ForwardComStubs.Stub_29<System.__Canon, System.__Canon, System.__Canon>(Void* InstParam, $__ComObject __this, __Canon graphicsEffect, Int32 __targetIndex) in Stub_29 at 16707566:0
3   Windows.UI.Xaml.Input                0x7ff80a4897fe   Windows.UI.Xaml.Input.PointerRoutedEventArgs.GetCurrentPoint($UIElement relativeTo) in GetCurrentPoint at 16707566:0

**Comment by HppZ** [comment]
what is Unspecified error (0x80004005)?

**Comment by StephenLPeters** [comment]
@HppZ is this in Winui3?

@JJBrychell and @codendone FYI

**Comment by codendone** [comment]
I can see here that this is system XAML rather than WinUI3 and that this E_FAIL (HRESULT 0x80004005) apparently was returned from GetCurrentPoint(), but need more info to narrow down what happened.

Is there a repro you can share? Or a crash dump?

**Comment by HppZ** [comment]
I have no repro, no dump.
I got that crash stack from AppCenter.
