### ISSUE TITLE
Question: d:DesignWidth / d:DesignHeight

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#5634]
How can I set the dimensions of a `UserControl` only for design time ?

**Comment by mrlacey** [comment]
Just curious: why would you want these different at design time?

**Comment by sigmarsson** [comment]
@mrlacey , in case only my 13" DELL Inspirion is with me, it would help me.

**Comment by mrlacey** [comment]
> @mrlacey , in case only my 13" DELL Inspirion is with me, it would help me.

I still don't understand how having different size controls (or pages/windows?) at design time would be useful for a particular screen size. 
Do you not want the app to also work on that device at run time? And if so, why do you need different design sizing?
Can you not get a workable design-time experience by zooming the designer?

I assume this is UWP (WinUI 2) related as WinUI3 doesn't yet support a XAML Designer and [one is not planned for this year](https://github.com/microsoft/microsoft-ui-xaml/issues/4195#issuecomment-886970252).
If you have a good reason for needing more control over different element sizes at design time, it might be a useful consideration towards getting one sooner.

**Comment by sigmarsson** [comment]
![image](https://user-images.githubusercontent.com/43340959/128683231-f05417b4-c5ba-4cef-985d-10f70ca8fc17.png)
