### ISSUE TITLE
Setting TeachingTip.PreferredPlacement crashes the WinUI desktop application

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#5635]
**Describe the bug**

Setting TeachingTip.PreferredPlacement crashes the WinUI desktop application

**Steps to reproduce the bug**

1. Create a page in step 2 and run the application
2. 
```xaml
<Page
    x:Class="App11.Views.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Style="{StaticResource PageStyle}">

    <Grid x:Name="ContentArea" Margin="{StaticResource MediumLeftRightMargin}">
        <Grid Background="{ThemeResource SystemControlPageBackgroundChromeLowBrush}">
            <!--
                The SystemControlPageBackgroundChromeLowBrush background represents where you should place your content.
                Place your content here.
            -->
            <TeachingTip IsOpen="True" CornerRadius="8"
                         Title="Saving automatically" PreferredPlacement="BottomRight">
                <ListView ItemsSource="{x:Bind ViewModel.List}"/>
            </TeachingTip>

        </Grid>
    </Grid>
</Page>
```
**Expected behavior**

Teaching tip should be displayed at correct location

**Screenshots**

![image](https://user-images.githubusercontent.com/8557046/128625623-ff8f2a5b-173f-446d-94be-cda27d592205.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 0.8: 0.8.0] If you're seeing your issue in older previews of WinUI 3, please try this release.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@harvinders do you get this issue when you set a target for the teaching tip?  What about if you have it initially closed and then open it with a button?

**Comment by harvinders** [comment]
@StephenLPeters 
> do you get this issue when you set a target for the teaching tip? 

Yes

> What about if you have it initially closed and then open it with a button?

No, if I set IsOpen later, it shows up without issue
