### ISSUE TITLE
NumberBox's Custom ContextFlyout not applied 

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#5637]
**Describe the bug**
Custom Context flyout not applied for NumberBox

**Steps to reproduce the bug**

1. Run the [CustomContextFlyout.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6950657/CustomContextFlyout.zip) sample
2. Right click on the NumberBox control to open context flyout
3. Note: Assigned custom MenuFlyout not reflected in opened context flyout.

**Expected behavior**

Custom MenuFlyout should be applied to the NumberBox control

**Screenshots**

Expected output:
![image](https://user-images.githubusercontent.com/57438309/128631064-71b16125-7274-4145-bf98-26b0d89cd4ac.png)

Current output:
![image](https://user-images.githubusercontent.com/57438309/128630988-4ce7a6b9-6871-4b37-b515-135fcb246de9.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 0.8: 0.8.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Same root cause as #5656 but this gets more to the real issue.  the problem is that the internal text box is handling the input and opening a flyout when the numberbox should be instead.
