### ISSUE TITLE
Question: FileOpenPicker Filter for any file type

### ISSUE THREAD

**Issue by meichhorn-conet** [microsoft/microsoft-ui-xaml#5643]
How can I open a file picker to select any file type?

My code:
```csharp
var picker = new FileOpenPicker();
InitializeWithWindow.Initialize(picker, owningWindowHandle);

picker.ViewMode = PickerViewMode.List;
picker.SuggestedStartLocation = startLocation ?? DefaultSuggestedStartLocation;


// add file filters
picker.FileTypeFilter.Add("."); // 1) -> didn't work. No files will be shown
picker.FileTypeFilter.Add(".*"); // 2) -> exception. Filter cannot contain wildcard
// no file type filter -> 3) exception. At least one filter must be specified

// open picker and return selected file
return await picker.PickSingleFileAsync();
```

Version: Microsoft.ProjectReunion 0.8.0-preview

**Comment by ghost1372** [comment]
did you test this?
` picker.FileTypeFilter.Add("*.*"); 
`

**Comment by marb2000** [comment]
Hi @meichhorn-conet, no sure whether @ghost1372 works, feel free to try it, but you can  use "*" and there is a sample here:

https://github.com/microsoft/WinUI-3-Demos/blob/9127534471000e18149fe5df4f841a5ce8123189/src/Build2020Demo/DemoBuildCs/DemoBuildCs/DemoBuildCs/MainWindow.xaml.cs#L35

**Comment by meichhorn-conet** [comment]
`*.*` doesn't work. I got the following error
>WinRT originate error - 0x80070057 : 'File extensions must begin with '.' and contain no wildcards.'.

`*` Works as expected. thx
