### ISSUE TITLE
TextBox default context menu not closed while click the copy button

### ISSUE THREAD

**Issue by susmitha-sundar** [microsoft/microsoft-ui-xaml#5645]
Hi Team,

WinUI TextBox control has default context flyout. Which opens while selecting all the text in TextBox. When I click the copy button, Context flyout does not closed. Whereas I click the paste or cut button, It closed.

![image](https://user-images.githubusercontent.com/60175573/128664437-7158aead-096a-462b-aeb9-0c92de8f13ff.png)

Could you please check this?

Regards,
Susmitha S

**Comment by bpulliam** [comment]
I am unable to repro this in WinUI Gallery 2 or WinUI Gallery 3. If you are still seeing this, please file a new issue with the repro steps and versions of WinUI and the OS.
