### ISSUE TITLE
RichTextBlock can cause the app to crash

### ISSUE THREAD

**Issue by HHChaos** [microsoft/microsoft-ui-xaml#5646]
**Describe the bug**

When I use the `RichTextBlock` control and set a valid value for `MaxLines`, If the hidden content contains a `HyperLinkButton`, then `RichTextBlock` may cause the application to crash.

I have created a demo repo to show this bug: https://github.com/HHChaos/RichTextBlockTest

**Steps to reproduce the bug**
1. Compile and run my demo app (https://github.com/HHChaos/RichTextBlockTest)
2. Click the `Tab` key on the keyboard to switch the focus UI element.

**Expected behavior**

The focus element should be changed correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/9880072/128669818-ed247a2d-3e42-4aed-b8e8-752a0daf5123.png)

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@codendone FYI
