### ISSUE TITLE
Add UWP support in WinUI3

### ISSUE THREAD

**Issue by EP012014** [microsoft/microsoft-ui-xaml#5650]
# Proposal: UWP Support

## Summary
Let WinUI3 capable of building UWP apps

## Rationale
1.We need WinUI3 to develop UWP apps for Xbox and Hololens
2.We need it to upgrade existing UWP apps

## Important Notes
Support .Net Native to avoid reverse engineering

**Comment by akilarajesh1313** [comment]
@EP012014 You can currently use WinUI3 as the UI layer on your native UWP apps!
