### ISSUE TITLE
📢 Announcing: WinUI 3 - Windows App SDK 1.0 Experimental 🛠💻

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#5651]
We've just shipped the latest version of WinUI 3, which is a part of Windows App SDK 1.0 experimental release! This release includes bug fixes and provides access to non-stable APIs and features.  

## Shipping WinUI 3 as a part of the Windows App SDK

In order to use this version of WinUI 3, you'll download the **Windows App SDK (Experimental)** Visual Studio Extension (VSIX) to get started. The Windows App SDK VSIX includes WinUI project templates that you'll use to build your WinUI 3 app, as well as access to other [Windows App SDK components](https://docs.microsoft.com/windows/apps/windows-app-sdk/release-channels#features-available-by-release-channel). The Windows App SDK package includes a reference to the WinUI 3 NuGet package. 

For more on the Windows App SDK, see their [documentation](https://docs.microsoft.com/windows/apps/windows-app-sdk) and [repository](https://github.com/microsoft/WindowsAppSDK). For installation instructions, see  [Set up your development environment](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment). 

**NOTE**: The Windows App SDK was previously known by the code name Project Reunion. Some SDK assets may still use the code name, but these assets will be renamed in a future release. The term Project Reunion may also be used when referring to an existing asset or a specified earlier release.

## What's new

This release is focused on building towards new features for 1.0 stable and fixing bugs. 

### New features

- Support for showing a ContentDialog per window rather than per thread
- Windows App SDK and WinUI 3 are now supported in Visual Studio 2022 Preview 2 and above.

### Bug fixes

- #4021
- UWP: Highlight in RichEditBox is not working correctly with touch
- WebView2 will not allow user to tab out after receiving focus
- Crash when navigating with spatial sound enabled

### Stability
This release includes unstable APIs and does not support building production apps. If you'd like to use WinUI 3 to build a production app, feel free to continue using the latest [Windows App SDK 0.8 release](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel).

### Known Issues
For a list of all the known issues for this Windows App SDK 1.0 experimental release, please see the [Windows App SDK release notes](https://docs.microsoft.com/windows/apps/windows-app-sdk/experimental-channel#version-10-experimental-100-experimental1).

## Getting started 
First, you'll need to set up your dev environment with the appropriate technologies. See our documentation for installation instructions and more information on project types: 

**[Install the Windows App SDK](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment)**

**[Create WinUI 3 Projects](https://docs.microsoft.com/windows/apps/winui/winui3/create-winui3-projects)**

While you're developing, check out the [API Reference documentation](https://docs.microsoft.com/windows/winui/api/).

Take a look at our walk-through docs:

- [Get started developing apps with WinUI 3](https://docs.microsoft.com/windows/apps/winui/winui3/get-started-winui3-for-desktop)
- [Build a basic WinUI 3 app for desktop](https://docs.microsoft.com/windows/apps/winui/winui3/desktop-build-basic-winui3-app)

You can also update your existing WinUI 3 app to use the new Windows App SDK 1.0 experimental release using these instructions: [Update existing projects to the latest release of the Windows App SDK](https://docs.microsoft.com/windows/apps/project-reunion/update-existing-projects-to-the-latest-release).

We love feedback! We encourage you to file any bug, big or small, on our repo using [this template](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=). Knowing which issues and features are important and/or critical to our customers highly influences which ones we tackle. Even though we ship with the Windows App SDK, please continue to file WinUI-specific bugs on this repo.   

## Using WinUI 3 and the Windows App SDK with our ecosystem partners

This latest release is in the process of being integrated into several other important ecosystem technologies. To test out and follow that progress, check out some of our partner technologies below (note that some of these technologies may not yet be available for Windows App SDK 1.0 experimental):

- [Actipro Software](https://www.actiprosoftware.com) is migrating their vast UI control offerings over to WinUI 3, including their SyntaxEditor code editor, propertygrid, native type edit boxes, docking/MDI, charts, and more.

- [DevExpress](https://www.devexpress.com/winui/): DevExpress has released 20 new WinUI controls with Windows App SDK 0.8 support, including the Data Grid, Scheduler, Charts, Ribbon Toolbar, and more. All 20 UI components are available free-of-charge.

- Esri: [ArcGIS Runtime SDK for .NET]( https://developers.arcgis.com/net/) adds mapping, spatial analytics, and location intelligence capabilities to your apps on Android, iOS, and Windows. Support for WinUI 3 is [now available]( https://links.esri.com/arcgis-runtime-dotnet-sdk-winui-blog).

- [GrapeCity](https://www.grapecity.com/): [The ComponentOne WinUI controls](https://www.grapecity.com/componentone/winui-controls/?utm_source=Microsoft_GitHub&utm_medium=Dynamic&utm_campaign=Updated-WinUI-description_08/12/21) support modern desktop apps (Win32) and include calendar, accordion, input and our fast and flexible datagrid, FlexGrid.

- [Infragistics](https://www.infragistics.com/products/winui): Ultimate UI for WinUI brings business critical, high performing, and feature rich line of business controls to your apps that target any platform that runs Windows (including Windows on ARM64).

- [Syncfusion](https://www.syncfusion.com/winui-controls): Updated their projects to Microsoft.ProjectReunion from Microsoft.WinUI following upgrade instructions. All their controls are working fine.

- [Telerik UI for WinUI](https://www.telerik.com/winui): the market first UI controls suite for crafting Win32 and UWP apps with WinUI 3, comes with feature-rich controls like Ribbon, DataGrid, Charts, Gauges, Barcode, and more.

- [Uno Platform](https://github.com/unoplatform): Use WinUI 3 – Windows App SDK 0.8, XAML and C# to build pixel-perfect, single-codebase, native applications that can run on Web, Desktop and Mobile. It is free, open-source and available today.

- [Windows Community Toolkit (Microsoft)](https://aka.ms/wct-winui3): The WCT is currently working on supporting Reunion 0.8 release candidate. It provides tons of new controls and capabilities for use in your WinUI app. You can check out their open source repo [here](https://aka.ms/windowstoolkit).

## What's next
To keep up with progress being made on WinUI 3, please see our [feature roadmap](https://aka.ms/winui3/feature-roadmap) which gets updated regularly. We also give monthly updates on our WinUI Community Calls, where you can directly ask the team any questions you have.

**Comment by harvinders** [comment]
@anawishnoff  Does this also have the new fluent language implementation (cards, mica shadows etc) same as UWP 2.6?

**Comment by ghost1372** [comment]
I was expecting to see WinUI 2.6 visual styles in this version😞

**Comment by anawishnoff** [comment]
@harvinders Not quite yet - those are still planned to be included in WinUI 3 on or before the 1.0 stable release.

**Comment by Zidane** [comment]
Are multiple windows allowed to be running at once in this build?

**Comment by anawishnoff** [comment]
> Are multiple windows allowed to be running at once in this build?
@marb2000 could you provide insight here?

**Comment by michael-hawker** [comment]
@anawishnoff looks like all the WinUI Syncfusion [samples](https://github.com/syncfusion/winui-demos) are C# based and [their docs](https://help.syncfusion.com/winui/overview) don't call out requirements for C# only applications. Do you know if they're focused only on .NET like the Toolkit?

@nlogozzo I also did just publish our sample on using UWP Toolkit components within C++ apps here if that helps: https://github.com/CommunityToolkit/Sample-Windows-CppWinRT - though it does come with caveats, but the same approach would also work for other components like the Syncfusion UWP one. Hopefully we'll get to a _WinUI 3_ version of this sample, as there would be differences, have an issue tracking that on our sample repo. Not sure when we'll get to it yet though as we're focused on our 7.1 release at the moment.

**Comment by edoust** [comment]
When will [AnimatedIcon](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.animatedicon?view=winui-2.6) become available for Windows App SDK?

**Comment by pjmlp** [comment]
Will XAML C++ development experimence with C++/WinRT ever replicate that of C++/CX?

Are we doomed to edit IDL files without syntax highlighting, code completion and manually merge generated files?

Why should we keep burning our productivity with XAML C++, instead of going C++ Builder and Qt Studio/Designer, to be able to enjoy a .NET like development experience with C++ on Microsoft platforms?

Even legacy MFC feels more fun than dealing with C++/WinRT XAML tooling issues.

**Comment by pjmlp** [comment]
@nlogozzo On my book a development experience worse than using MFC isn't worth it, and the team has been deaf to productivity requests during the last 4 years, since it decided to kill C++/CX.

Who wants to edit IDL files and generated content, like if we were stuck with Visual C++ 6.0?!?

**Comment by nlogozzo** [comment]
@pjmlp I hear your frustration. But for me and my applications and the future direction of windows, I'm on the Windows App SDK bandwagon for its controls and design. Hopefully Microsoft fixes all these little annoyances in the future but who knows, like you said they're deaf and I'm sure lazy too

**Comment by pjmlp** [comment]
@nlogozzo You don't need it for Win32 applications when there are designers available on the team.

As for the future direction of Windows, I and others already have plenty of scars from all rewrites that were the future of Windows since version 8.

With Qt and C++ Builder, not only I have my productivity, I also have other platforms as bonus. Apparently they keep forgetting about this little detail.

**Comment by Pinox** [comment]
When will  WinUI 3 / Windows App SDK 1.0  support CLI to create / build and run apps ?

**Comment by prime167** [comment]
@anawishnoff Does this build Support Unpackaged (non-MSIX) Deployment as roadmap says?

**Comment by prime167** [comment]
Never mind, I found it myself(It support Unpackaged (non-MSIX) Deployment )
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/release-channels#features-available-by-release-channel

**Comment by MrDeej** [comment]
"WinUI: Error creating second Desktop Window on the current process. No more than one Desktop Window is allowed per process.'."

This worked in Experimental.

We can still create new AppWindows, but how do we set content to them?

**Comment by Licantrop0** [comment]
@anawishnoff is there a datagrid compatible with this preview?
All the ones I tried (including the [Windows Community Toolkit one](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/datagrid)) need Project Reunion 0.8 and I get many compile errors.

**Comment by michael-hawker** [comment]
@Licantrop0 we didn't support 1.0-experimental, but we recently shipped support for the 1.0-preview3 bits, more info here: https://github.com/CommunityToolkit/WindowsCommunityToolkit/discussions/4350
