### ISSUE TITLE
[uwp] NullReferenceException, then XamlParseException: Cannot create instance of type...

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#5653]
**Describe the bug**

For some user control classes, I can't create them in xaml, an error (actually two) gets thrown. at `this.InitializeComponent()`

For additional context, I get this error during startup:
![image](https://user-images.githubusercontent.com/13891601/128794598-7aea231e-a2a8-4f1d-92ff-ed5585e55bad.png)

**Steps to reproduce the bug**

This is a weird bug, and my app is really big, and it only happens on **some** user controls and not others, but I can't figure out what separates the classes with the problem.

My `MainPage` looks like this:
![image](https://user-images.githubusercontent.com/13891601/128794726-f5210606-80b5-4abb-9234-b9558dc1528c.png)

My `select_sound_effect_ctrl`  xaml looks like this:
![image](https://user-images.githubusercontent.com/13891601/128794814-a68583b2-d556-48e7-840d-d077d5d3ee5f.png)

At startup: First I get
![image](https://user-images.githubusercontent.com/13891601/128794121-2dd659e7-59d8-4dd8-ab0c-eb4660b17e7a.png)

Then I get
![image](https://user-images.githubusercontent.com/13891601/128794160-d33ec1e7-5caa-4540-867a-615e8cdd3fe6.png)

It basically says it can't create an instance of type `select_sound_effect_view_model`, but I don't understand why. It's a `public` class, and as matter of fact, this works (just creating it in code):

![image](https://user-images.githubusercontent.com/13891601/128794315-91b54786-3a87-4f1c-91d0-de1dfea1b4f9.png)

Once again, if I leave the class as it originally is, and I create an instance in code-behind, it works:
![image](https://user-images.githubusercontent.com/13891601/128795449-9eb81844-76ec-41e8-8e31-b8bb1efa65b2.png)

**Expected behavior**

Clearly, the error shouldn't happen. This occurs at random times, code that once worked, sometimes stops working after months. And sure, it's rather simple to create a control in code every now and then, but what when it's used in a more complicated scenario, like, have an `ItemsControl` of such items?

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            |  Yes  |

**Comment by StephenLPeters** [comment]
@RealTommyKlein thoughts on whats going on here?

**Comment by JanRajnoha** [comment]
XamlParseException is the most common problem of WinApp SDK. Will you or WinApp SDK team investigate it more deeper?

**Comment by RealTommyKlein** [comment]
@JanRajnoha - do you have the full callstack for the `NullReferenceException` (Just My Code disabled, and a mixed mode debugger to get both the managed and native callstack)?  The `XamlParseException`'s root case is that `NullReferenceException` - as the framework is creating `sound_effect_view_model` it hits the `NullReferenceException` and can't actually create it, leading to the parse exception.

**Comment by JanRajnoha** [comment]
@RealTommyKlein When I get error again, I'll post it.

**Comment by jtorjo** [comment]
@RealTommyKlein So I just got the error again. Here's the first native callstack:

![image](https://user-images.githubusercontent.com/13891601/129108935-03d66479-f603-40e6-a607-5ff6c083b4f8.png)

and 

![image](https://user-images.githubusercontent.com/13891601/129108993-319d8785-b502-4755-a7ea-ff3eaa548124.png)

and the second call stack:

![image](https://user-images.githubusercontent.com/13891601/129109081-777833e2-b1d9-4e94-8ac1-54e7ab45cc61.png)

and 

![image](https://user-images.githubusercontent.com/13891601/129109134-c6042457-346f-4938-abc5-652d07c052b4.png)

**Comment by jtorjo** [comment]
@RealTommyKlein @JanRajnoha So, since the error war rather new, I managed to pinpoint it. Let me tell you, I'm **beyond shocked** at the culprit:

![image](https://user-images.githubusercontent.com/13891601/129112525-b6cb8d37-41cf-47dc-81da-8f9df79c8a0f.png)

Just adding that public property will generate the above error. I have **no idea why**.

Having said that, I couldn't believe my findings, and I literally commented/uncommented that line 5 times and recompiled to test my findings. And yea, every time the line is uncommented, I get the error.

**Comment by jtorjo** [comment]
I will mention another issue, since I'm almost certain it has something to do with the issue. The class has some static initializations:
![image](https://user-images.githubusercontent.com/13891601/129120505-a320adde-f600-47db-801c-e949cd360c57.png)
