### ISSUE TITLE
NumberBox's ContextFlyout.Opening event not triggered.

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#5656]
**Describe the bug**
If we want to add or remove the context flyout item in NumberBox's ContextFlyout.Opening event, it's not reflected.

**Steps to reproduce the bug**

1. Run the [ContextFlyout_Opening.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6960365/ContextFlyout_Opening.zip) sample
2. Right click on the NumberBox to open context flyout
3. Note: Custom context menu should be applied.

**Expected behavior**

Custom context menu should applied.

**Screenshots**

Expected input:
![image](https://user-images.githubusercontent.com/57438309/128839146-626180c1-c784-40c7-889b-9b815f2e0787.png)

Current output:
![image](https://user-images.githubusercontent.com/57438309/128839342-908f36aa-bf84-4b4d-9cd7-3b0b86cb0933.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 0.8: 0.8.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
It looks like it is opening the default text box flyout instead.  The way numberbox works is it has a textbox in its template. I'm guessing that the inner textbox is handling the input and numberbox is never getting a chance.

**Comment by StephenLPeters** [comment]
@prabakaran-sangameswaran do you happen to know if this is an issue in Winui 2.6 as well? I suspect is is.

**Comment by krschau** [comment]
Probably same underlying issue as https://github.com/microsoft/microsoft-ui-xaml/issues/5637
