### ISSUE TITLE
WinUI 3: Crash when moving the mouse over a GridView

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#5658]
**Describe the bug**

App crashes with WinRT originate error - 0x800F1000 : 'The property path '(RevealBrush.State)' could not be resolved for a Setter.'.  when mouse is moved over the gridview. 

Workaround: Copy the current WinUI 2.6 XAML code of the default GridView style without the reveal effect.

**Steps to reproduce the bug**

1. Add a GridView
2. Move mouse over it

**Expected behavior**

Should not crash

**Screenshots**

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 1.0: 1.0.0-experimental1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@MikeHillberg and @codendone Seems like RevealBrush was moved to preview causing it to not be present in the release packages, however we have styles which reference reveal brush and its properties all over the place. I suspect that there are a number of issues like this one.
