### ISSUE TITLE
Proposal: Simplify DPI awareness settings in default app.manifest template

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#5659]
# Proposal: Simplify DPI awareness settings in default app.manifest template

## Summary
WindowsAppSDK apps are supported on Window 10 1809 and newer. The default app.manifest file contains very complicated logic on how dpi aware the app is. This file is added by the template to every app. The manifest should be simplified, as Windows 10 1809 and newer versions all support the most modern "PerMonitorV2" setting. The compatibility options are not needed.

## Rationale
There is a lot of boilerplate and hard to understand things involved in making the Windows App SDK and WinUI 3 work. This is one complexity that is just not needed.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Same DPI awareness on all currently supported Windows versions | Must |
| Simpler (easier for devs to understand) `app.manifest` file | Must |
| Change anything about how DPI awareness works | Won't |

## Important Notes
This is the current section:
```xml
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <!-- The combination of below two tags have the following effect:
           1) Per-Monitor for >= Windows 10 Anniversary Update
           2) System < Windows 10 Anniversary Update
      -->
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
    </windowsSettings>
  </application>
```

Which should be functionally equivalent to this (which is much easier to understand):
```xml
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </windowsSettings>
  </application>
```

## Open Questions
Are there any parts of Windows App SDK that are expected to be able to run on version earlier than 1703?

**Comment by StephenLPeters** [comment]
@marb2000 @codendone and @gegao18 FYI

**Comment by Marv51** [comment]
I have opened a [PR](https://github.com/microsoft/WindowsAppSDK/pull/1748) to fix this in the WindowsAppSDK repo. Let's get this fixed!
