### ISSUE TITLE
WinUI 3 App fails to start with missing dll message

### ISSUE THREAD

**Issue by jeromebjerome** [microsoft/microsoft-ui-xaml#5660]
ENV: Win 10 Home as Of : 08/10/2021
Visual Studio 2019 16.10.4
WinUI 3: 0.8.1
Windows 10.0.19042 Build 19042

1) Create a - Blank App, Packaged (WinUI 3 in Desktop) - C++
2) Add a Desktop DLL project to the solution
3) Add DLL as reference to the Desktop project
4) In App.xaml.cpp of Desktop project, add a call to any DLL entry
5) Build Solution: Everything is fine
6) Run Package: Failure with error message: "DLL xxx cannot be found"

**Comment by StephenLPeters** [comment]
@alwu-msft FYI
