### ISSUE TITLE
Entered invalid input text is set as SelectedItem when pressing enter key or lost focus of  WINUI ComboBox control

### ISSUE THREAD

**Issue by Subashini2129** [microsoft/microsoft-ui-xaml#5661]
Hi Team, 

**Query 1:**

I have entered invalid input text while pressing enter key in ComboBox control or its lost focus, the entered text is set as SelectedItem. Is this excepted behavior or issue of ComboBox control?

**Replication procedure:**

1. Run the sample.
2. Open popup and select any one item.
3. Now, enter invalid text which does not contain in items source.
3. Press enter key.

Actual result:
Invalid text is set as selected item.

Expected result: 
SelectedItem should be null as like other SelectedIndex reset to its default value.

**Query 2:**

Changing SelectedValuePath property at run-time reset the SelectedItem (null), SelectedIndex (-1) properties to its default value. Experiencing same behavior in all items control like ListView, ListBox whether it is issue or expected behavior? 

**Replication procedure:**

1. Run the sample.
2. Open popup and select any one item.
3. Now, change SelectedValuePath option as ID.

Actual result:
SelectedItem, SelectedIndex property reset to its default value.

Expected result: 
SelectedItem, SelectedIndex properties should not be reset to its default value.

**Sample:**
[ComboBox-sample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6966250/ComboBox-sample.zip)

**Comment by StephenLPeters** [comment]
This is by design.  Editable combobox's are designed to be able to set the value of the combo box to whatever you'd like. You can do input validation yourself from code behind using the TextSubmitted event, but by default anything can be put in an editable combo box.

**Comment by StephenLPeters** [comment]
Think of a font size picker scenario, where you can set any numeric value but only show the common font sizes in the drop down.

**Comment by Subashini2129** [comment]
@StephenLPeters, regarding Query2 Changing SelectedValuePath property at run-time reset the SelectedItem (null), SelectedIndex (-1) properties to its default value. Is this issue?

**Comment by StephenLPeters** [comment]
that does seem a little strange.  @MikeHillberg or @anawishnoff is that expected behavior?
