### ISSUE TITLE
Binding is not working if the DeferLoadStrategy value is set to the element

### ISSUE THREAD

**Issue by ssaran046** [microsoft/microsoft-ui-xaml#5662]
**Describe the bug**

Binding is not working if the DeferLoadStrategy value is set to the element.

Sample: 
[DeferLoadStrategyIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7005773/DeferLoadStrategyIssue.zip)

Note:
If we remove the value x:DeferLoadStrategy="Lazy" then the header value is updated properly.

![image](https://user-images.githubusercontent.com/24865096/129022631-cb79997f-4d4b-4db1-bcee-de5dc55ef74f.png)

**Steps to reproduce the bug**

1. Run the sample
2. Header is not visible to MyCustomControl.

**Expected behavior**

The header should be visible.

![image](https://user-images.githubusercontent.com/24865096/129023548-841dcea9-3139-464a-bc01-c5502b918815.png)

**Screenshots**

The header is not visible but it has the value "Hello".

![image](https://user-images.githubusercontent.com/24865096/129022452-8c91070b-e94d-45d2-bbcc-2b7cbf7598b3.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@ssaran046 what versions of Winui are you seeing this issue on?

@RealTommyKlein what do you make of this?

**Comment by ssaran046** [comment]
@StephenLPeters I am facing this issue on ProjectReunion 0.8.1 version.

**Comment by ssaran046** [comment]
Hi Team,

Any update on this?

**Comment by RealTommyKlein** [comment]
@ssaran046 - what part of your app is realizing the deferred `HeaderContentPresenter` element?  Have you validated that replacing the `Content`'s `TemplateBinding` with a fixed sample value displays correctly?

`x:DeferLoadStrategy` is also deprecated - `x:Load` provides the same functionality, and also supports being set to an `x:Bind` expression.

**Comment by ssaran046** [comment]
@RealTommyKlein 

- Have you validated that replacing the Content's TemplateBinding with a fixed sample value displays correctly? - **Ensured**
- x:Load provides the same functionality - **Ensured**

But it is not working.

**Comment by ssaran046** [comment]
I have attached an issue reproducible demo on the bug description section.

**Comment by RealTommyKlein** [comment]
Thanks @ssaran046.  I tried out that repro, and found that changing Generic.xaml to use a fixed value for `Content` (`"hello world"` instead of `"{TemplateBinding Header}"`) still didn't display, so it wasn't a problem with binding.  It doesn't look like any code actually loads `HeaderPresneter` from its unloaded state.  For your scenario, calling `GetTemplateChild()` probably makes the most sense to load the element ([here are some other options](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/x-load-attribute#loading-elements)).

As an example, I used this code to sanity-check the `TemplateBinding` worked by loading the element as soon as the template is applied (you can modify when the `GetTemplateChild()` is called to when you want to actually load the element):

```
    public sealed class MyCustomControl : Control
    {
        protected override void OnApplyTemplate()
        {
            // Calling GetTemplateChild() will load the HeaderPresneter object from its unloaded state
            var headerPresenter = GetTemplateChild("HeaderPresneter") as ContentPresenter;
        }
    }
```

**Comment by ssaran046** [comment]
Thanks @RealTommyKlein. Your explanation and solution are fine, and it is working.
