### ISSUE TITLE
Controls Version 2 breaks default styling

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#5670]
**Describe the bug**

Upgrading from 2.5.x to 2.6.1 caused controls using default styling to break in our application. This was traced back to the new styles version, and manually specifying controls version 1 resolved the issue.

**Steps to reproduce the bug**

On Windows 10 18363, create a UWP application referencing WinUI 2.6.1 and add in the MUXC resource dictionary. Create a new `Page` that uses some buttons and drop down menus then run. I have `RequestedTheme` set to `Light`, but I have tried `Default` and `Dark` as well with varying degrees of the same breakage.

**Expected behavior**
The default results should be at least legible and not washed out/no contrast.

**Screenshots**

With version 2 (or not set):
![image](https://user-images.githubusercontent.com/606923/129129145-0774bc60-4ed2-4500-89db-a83ffe2c607b.png)

With version 1 explicitly set:
![image](https://user-images.githubusercontent.com/606923/129129192-861d9f3e-fd35-4258-97ce-3a69809a2d84.png)

**Version Info**

NuGet package version:  Microsoft.UI.Xaml 2.6.1

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

The issue is visible (after building) in the XAML designer, without even needing to run the application.

**Comment by StephenLPeters** [comment]
Very strange, and potentially a very bad issue. thanks for reporting it.  Can you provide a repro application and/or the xaml used to get the screen shots from above? Our test applications haven't hit an issue like this.

**Comment by mqudsi** [comment]
I was able to reproduce it just by creating a new UWP project in Visual Studio 16.11.0 Preview 3.0 with the "Blank App (Universal Windows)" C# template, installing Microsoft.UI.Xaml 2.6.2, adding the merged dictionary, and adding a `<Button>Text</Button>` to the `<Grid></Grid>` in `MainPage.xaml`. I'm attaching a copy of the solution that repros the problem for me under Windows 10 18363 (I'm including `obj` and `bin` because I don't think UWP projects support dependency locking and I want to be sure you see what I see - packages restored for Debug/x64 so please use that configuration):

[UwpWinUi2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6989740/UwpWinUi2.zip)

This is how the button renders (text is momentarily visible when the button is depressed):

![image](https://user-images.githubusercontent.com/606923/129510738-fd21d012-163a-4cee-94f2-1e5ba16f195c.png)

**Comment by llongley** [comment]
Unfortunately, I can't seem to repro the issue.  When I run your test app built using Debug/x64 on 18363, I'm seeing this:

![image](https://user-images.githubusercontent.com/18177025/129648669-adcad718-8e12-4d12-a514-d23c5e105276.png)

Just so I'm sure I understand, if you un-upgrade back to 2.5, things look fine, and any version of 2.6 repros the issue for you?

I don't suppose you have any other machine to test it on, to see if it's somehow machine specific?  You might also try deleting %USERPROFILE%\.nuget\packages to see if there's something weird happening with NuGet versions being used, or something like that.

**Comment by mqudsi** [comment]
Hmm. I nuked the nuget packages folder (20 GiB this time - I usually prune it before it gets so large!), deleted obj & bin, and tried again but it didn't change the result.

It doesn't reproduce for me when deploying (side loading) the same locally-broken binaries to a clean Windows 10 18363 installation. But I think this just tells us that there's something more intricate going on rather than it being an exclusively one-off issue: it's a sandboxed UWP app, so ideally the entirety of its state is contained in its appx package, drastically reducing the surface area of "corrupt system" type bugs that plague typical Win32 applications.

Obviously it's of much lower priority if it doesn't readily reproduce, however!

**Comment by mqudsi** [comment]
Note that this problem still exists and for me it reproduces even with inbox apps like Microsoft Store. Here's a screenshot; you can see that the button contents aren't visible:

![image](https://user-images.githubusercontent.com/606923/167725444-3f32b2b3-b639-43ef-b0c8-323db704f05d.png)

**Comment by mqudsi** [comment]
The issue persisted until I upgraded past 18634.

**Comment by ranjeshj** [comment]
@mqudsi thanks for that info.
