### ISSUE TITLE
WinUI Design Toolkit Bug: constraints on dropdown and calendar date picker

### ISSUE THREAD

**Issue by Wolfr** [microsoft/microsoft-ui-xaml#5674]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Dropdown / Dropdown
Calendar / Calendar Date Picker

**Describe the bug:**
On the dropdown and datepicker, if you resize these components, the icon doesn't stay on the right. I figure the constraints should be fixed on those so that the icon stays on the right.

![CleanShot 2021-08-12 at 17 45 28](https://user-images.githubusercontent.com/12690/129227080-f19d293d-8333-4df0-a4e8-cbf4c21b49dd.gif)

**Version Info:**
2.6 duplicated 12th of August from Figma community

**Comment by alejo4000** [comment]
We're currently working on adding autolayouts to components, which will address this problem. Keep an eye out for future updates addressing this.

**Comment by Wolfr** [comment]
Thanks for the update, but FWIW you don't need autolayout to solve this. You need the right constraints.
