### ISSUE TITLE
WinUI Design Toolkit Bug: time picker - support 24h time zone

### ISSUE THREAD

**Issue by Wolfr** [microsoft/microsoft-ui-xaml#5675]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Time Picker / Time Picker

**Describe the bug:**
Time picker does not provide an option to hide "AM" (third section)

**Version Info:**
2.6 duplicated 12th of August

**Additional context:**

Screenshot: 
<img width="383" alt="CleanShot 2021-08-12 at 17 48 25@2x" src="https://user-images.githubusercontent.com/12690/129227544-c9371d54-a064-492b-95d4-6319dc8f8ccf.png">

Desired result:

Had to detach to get to a timepicker that would make sense for a 24h timezone context (not using AM/PM)

<img width="180" alt="CleanShot 2021-08-12 at 17 48 36@2x" src="https://user-images.githubusercontent.com/12690/129227601-0df97f2f-6b60-46ef-a855-c4e5c6bba6fa.png">

**Comment by mdtauk** [comment]
I think this is handled by the Current Culture and localisation, here in the UK we use 24 hour time by default.

![image](https://user-images.githubusercontent.com/7389110/129230047-ad8b5148-e69d-4ad4-8547-98690b320957.png)
![image](https://user-images.githubusercontent.com/7389110/129230094-ab9bea26-ea55-49cf-b735-41e6e587ca5f.png)

```Xaml
<TimePicker ClockIdentifier="24HourClock" Header="24 hour clock" />
```

**Comment by Wolfr** [comment]
Yes - but this is about the Figma library.

**Comment by mdtauk** [comment]
> Yes - but this is about the Figma library.

Ah my mistake - yes there is not a lot of consideration for the localised variants of these controls

**Comment by alejo4000** [comment]
Thanks for calling this out! We're tracking a workitem to add this variant to the Time Picker in a future update.
