### ISSUE TITLE
How to always focus first ListViewItem in ListView control when pressing tab key from previous control in flyout.

### ISSUE THREAD

**Issue by Subashini2129** [microsoft/microsoft-ui-xaml#5676]
Hi Team, 

I am using ListView control in flyout with SelectAll and ok option, whenever I am opening flyout and press tab key it should focus first ListViewItem. Please find the sample and replication procedure regarding the focus issue I am facing.

**Sample:**
[ListView-focus-issue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6976982/ListView-focus-issue.zip)

**Replication procedure:**
1. Run the sample.
2. Click button to open flyout.
3. Press tab key. Note, first ListViewItem is focused.
4. Press down key and to focus 6th ListViewItem.
4. Now close flyout.
5. Again click button to open flyout.
6. Press tab key. Note, 6th ListViewItem is focused.

Is this issue? If it is ListView behavior can you please suggest any work around solution to always focusing first ListViewItem when ListView control got focus.

**Comment by StephenLPeters** [comment]
It is by design. I think you could do something like attach to the ListView's Getting Focus event and set focus on the correct element yourself. Or when the flyout is opened you could set focus on the first element in the list.

@Austin-Lamb do you know what mechanism is being used to inform focus manager which list view item to put focus on?

**Comment by Subashini2129** [comment]
@StephenLPeters, I tried to set focus to first ListViewItem using ListView getting focus event but throws COMException.
![image](https://user-images.githubusercontent.com/56991221/129313660-c9e8ccb8-3feb-49ee-aed8-32dde4346829.png)

**Note:** In my case SelectAll button should be in focused state when opening popup, when pressing tab or down key only I need to move focus to first ListViewItem. So, flyout opened event does not help in my case.

**Comment by Subashini2129** [comment]
Hi Team,

Any update on this issue.

**Comment by bpulliam** [comment]
I believe the ListView is remembering the last item that had focus and that the control is setting it, not the focus manager.  That is by design.  The exception may be a bug.  Moving back to Controls team for further investigation.
