### ISSUE TITLE
Style does not applies to UWP Xamarin.forms Entry element

### ISSUE THREAD

**Issue by MetropolisCZ** [microsoft/microsoft-ui-xaml#5678]
Hi, I have this issue: When I create Xamarin.Forms app and add Entry there, it is not styled by your library.

**Describe the bug**
Style does not applies to UWP Xamarin.forms Entry element

**Steps to reproduce the bug**
Create any Xamarin.Forms app, where you will add Entry element. Add Microsoft.UI.Xaml library (with NuGet) and --> Entry´s style is still 'Windows 10'

**Expected Behavior**
To look like this :)
![image](https://user-images.githubusercontent.com/48151954/129278973-e9a6dc85-f50b-47d6-8e28-6728dc7c0138.png)
(from https://docs.microsoft.com/en-us/windows/apps/get-started/build-apps-for-windows)

**Screenshots**

![image](https://user-images.githubusercontent.com/48151954/129278357-cd75971d-7d9b-4f55-9fba-a4cb54c2255f.png)
Buttons look new, but Entry still old

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.120)              | Yes    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |

Sorry if the issue is stupid :)

**Comment by StephenLPeters** [comment]
Unfortunately I don't know the mechanism that Xamarin Forms apps are intended to receive the WinUI Styles, if they are at all.  I think this would be better to ask in the [Xamarin Forms Github](https://github.com/xamarin/Xamarin.Forms)
