### ISSUE TITLE
Tab navigation in content editable WebView freezes the UI after closing a secondary window

### ISSUE THREAD

**Issue by Kumara-Krishnan** [microsoft/microsoft-ui-xaml#5679]
**Issue:**
Tab navigation in content editable WebView freezes the UI after closing a secondary window.

**Prerequisites:**
OS build version should be higher than 17763.

**Steps to reproduce the bug**
1. Launch the app and focus any textbox. 
2. Now keep tab pressed which will cause navigation across controls. Even if we keep the tab key pressed for a few seconds, it navigates between controls smoothly.
3. Then click new window button to launch a secondary view. Now close the secondary window.
4. Again, focus and textbox and keep tab key pressed. After a few seconds, UI freezes.

When trying the same in OS build version 17763, this issue doesn't occur. It works properly.

**Expected behavior**
1. Tab navigation should work smoothly without freezing the UI.

**Repro Repo:**
https://github.com/Kumara-Krishnan/WebViewFreeze

**Demo Video**
https://workdrive.zohoexternal.com/external/35452a4cc8651089940a884cbac1cd143d514c39544fa47fdf70a62a374ab339

**Version Info**

| Windows 11 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 22H2 (22621)             | No   |
| **Windows 10 version**                  | **Saw the problem?** |
| Insider Build (21390)              | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | No   |

**Comment by StephenLPeters** [comment]
@predavid @codendone FYI

**Comment by Kumara-Krishnan** [comment]
The issue is still reproducible.
