### ISSUE TITLE
Proposal: Support animated webp

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5682]
`Image` does not support animated webp, so please support it.

**Comment by HppZ** [comment]
sometimes webp url failed to load.

**Comment by llongley** [comment]
@chrisglein FYI

**Comment by HppZ** [comment]
webp does not work good on Xbox devices.

**Comment by chrisglein** [comment]
Three separate issues raised here:
- does not support animated webp, so please support it.
- sometimes webp url failed to load.
- webp does not work good on Xbox devices.

It would be most helpful to file these as separate issues with individual repros and justifications/scenarios. For the first issue (not supporting animated webp) can you include the full feature request template? For the other 2 open new issues that include your repro information (per the bug template, not the feature request template).

**Comment by HppZ** [comment]
DAMN
