### ISSUE TITLE
Focus does not move to the first item of the navigation view when in LeftMinimal mode and an item header is present.

### ISSUE THREAD

**Issue by EriWong** [microsoft/microsoft-ui-xaml#569]
**Describe the bug**
The first time a navigation view in LeftMinimal mode is opened via keyboard, and the first item is a item header, focus does not move to the first item non-header item in the list.  Every other time it is opened, focus moves correctly.

**Steps to reproduce the bug**

xaml for minimal repro:
```
        <muxc:NavigationView PaneDisplayMode="LeftMinimal" >
            <muxc:NavigationView.MenuItems>
                <muxc:NavigationViewItemHeader Content="header" ></muxc:NavigationViewItemHeader>
                <muxc:NavigationViewItem Content="item" ></muxc:NavigationViewItem>
            </muxc:NavigationView.MenuItems>
        </muxc:NavigationView>
```
1. Tab to the navigation view
2. hit enter to open it
3. dismiss the menu
4. repeat steps 1 and 2, and note that from here on in, "item" gets focus when the navigation view is opened.

**Expected behavior**
Focus should move consistently each time the navigation view is opened.  I believe the behavior after the first time the navigation view is opened is correct.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by PatrickDesign** [comment]
I wasn't able to repro this issue in the newest build.  I'm running windows version 1903  -- maybe this has been taken care of?

Here's the xaml I tested this with:
```
<Page
    x:Class="MUXControlsTestApp.NavigationViewBlankPage1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:muxcontrols="using:Microsoft.UI.Xaml.Controls"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <muxcontrols:NavigationView PaneDisplayMode="LeftMinimal" >
        <muxcontrols:NavigationView.MenuItems>
            <muxcontrols:NavigationViewItemHeader Content="header" ></muxcontrols:NavigationViewItemHeader>
            <muxcontrols:NavigationViewItem Content="My favorite item!" ></muxcontrols:NavigationViewItem>
        </muxcontrols:NavigationView.MenuItems>
    </muxcontrols:NavigationView>
</Page>
```

**Comment by chingucoding** [comment]
This definitely doesn't repro anymore. Everytime you open the pane, the same item gets focus (the first NavigationViewItem that's not a header or separator). I think this can be closed now. @ranjeshj FYI.
