### ISSUE TITLE
[WinUI 3] Custom TitleBar Window Decorations not working

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/microsoft-ui-xaml#5691]
I have enabled `ExtendsContentIntoTitleBar = true;` and created a custom title bar as follows:
```xml
        <Grid Name="TitleBar" HorizontalAlignment="Stretch" VerticalAlignment="Top" Height="30" Background="Transparent">
            <Grid.ColumnDefinitions>
                <ColumnDefinition x:Name="LeftPaddingColumn" Width="0"/>
                <ColumnDefinition/>
                <ColumnDefinition x:Name="RightPaddingColumn" Width="0"/>
            </Grid.ColumnDefinitions>

            <TextBlock Grid.Column="1" Margin="20,8,0,0" Style="{StaticResource CaptionTextBlockStyle}" Text="{x:Bind ViewModel.Title}"/>
        </Grid>
```
I also set this title bar with `SetTitleBar(TitleBar);`
This is the result:
![image](https://user-images.githubusercontent.com/17648453/129467180-c93546cd-eb0f-4854-b2fb-3b488aa0a892.png)
As you can see, the window decorations (Minimize, Maximize, Close) are not the correct size as they are on every other Windows window and these buttons also don't work (they seem to be disabled and don't do anything when clicked). How can I get them to 1. be the correct size and 2. function correctly?

Btw, using the Windows App SDK V0.8.1 with WinUI 3

**Comment by nlogozzo** [comment]
Fixed by removing the `Background` property.
However, now, sometimes when I hover over the buttons they work correct and other times they seem to be disabled again.

**Comment by seven-mile** [comment]
I'm not sure whether `HorizontalAlignment="Stretch"` has effect on the control buttons' hittesting.
For the titlebar style issue, WinUI3 `Window.ExtendsContentIntoTitleBar` is an analog. You can use the new `AppWindow.ExtendsContentIntoTitleBar` API in 1.0 experimental to get the native Titlebar UX.

**Comment by kmelmon** [comment]
@nlogozzo please try the AppWindow.ExtendsContentIntoTitleBar API as suggested above.  Closing for now, if you continue to run into issues, feel free to reopen

**Comment by crramirez** [comment]
> @nlogozzo please try the AppWindow.ExtendsContentIntoTitleBar API as suggested above. Closing for now, if you continue to run into issues, feel free to reopen

Hello @nlogozzo ,

AppWindow.ExtendsContentIntoTitleBar API works perfectly but only on Windows 11. In Windows 10 we must use the ugly default title bar that ruins all fluent interfaces. Could you (team) fix at least that these buttons work despite they look smaller? In my case, I am using WinUI 3 for a UWP application that targets the enterprise segment, and WinUI 3 is best suited for that but they have and will have Windows 10 for a long time.

Regards,
Carllos

**Comment by hayashida-katsutoshi** [comment]
<Grid Grid.RowDefinitions="Auto,*">
        <StackPanel Grid.Row="0" Height="35" Orientation="Horizontal" Spacing="15" x:Name="TitleBar" HorizontalAlignment="Stretch" VerticalAlignment="Top">
            <TextBlock VerticalAlignment="Center" Text="MyApp" />
        </StackPanel>
    </Grid>
</Window>
```

I use this for the title bar and the Minimize/Maximize/Close are working on a Windows 10 PC. I tested it in WinUI3 unpackaged desktop with Windows App SDK 1.0.

You can add an icon inserting an Image tag before the TextBlock. The icon will have no context menu but fair enough to me.

**Comment by crramirez** [comment]
@hayashida-katsutoshi Works perfectly. Thank you very much
