### ISSUE TITLE
WinUI 3: TabView throws Microsoft.UI.Xaml.Markup.XamlParseException

### ISSUE THREAD

**Issue by riverar** [microsoft/microsoft-ui-xaml#5696]
WindowsAppSDK 1.0-experimental1
Unpackaged C#/XAML application
Windows 11 22000.132

Steps to reproduce:
1. File, New, WinUI 3 desktop application
2. Make the modifications needed to enable unpackaged use (disable entrypoint generation, bootstrap, etc.)
3. Add XAML to MainWindow: `<TabView />` or `<TabView AddTabButtonClick="TabView_AddTabButtonClick" TabCloseRequested="TabView_TabCloseRequested"/>`
4. Observe XAML editor/design has no issues with this code
5. Build / execute
6. Observe exception at runtime: `Microsoft.UI.Xaml.Markup.XamlParseException: 'XAML parsing failed.'`

Is this control supported in unpackaged applications?

**Comment by mrlacey** [comment]
For additional info. This does **not** repro on 21H1 with 0.8.2

**Comment by riverar** [comment]
> For additional info. This does **not** repro on 21H1 with 0.8.2

Interesting thanks! I'll try downgrading too.

**Comment by riverar** [comment]
@mrlacey Did you try reproducing specifically in an **unpackaged** app? I can't even get a bootstrap C#/XAML app off the ground.
