### ISSUE TITLE
Question: [C++/WinRT, Winui3]How to add handlers to a templated child of a templated control?

### ISSUE THREAD

**Issue by ifgotmoney** [microsoft/microsoft-ui-xaml#5698]
I have added a button into a templated control like below:

```
<!-- \Themes\Generic.xaml -->
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:BgLabelControlApp">

    <Style TargetType="local:BgLabelControl" >
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="local:BgLabelControl">
                    <Grid Width="100" Height="100" Background="{TemplateBinding Background}">
                        <Button x:Name="newButton">
<TextBlock>aaa</TextBlock></Button>
                    </Grid>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
</ResourceDictionary>
```

and then I have tried different ways to add handler to this button "newButton", neither of them works:

1.
`<Button x:Name="newButton" Click="myHandler">`
,  and declare handler in IDL file and header file, implement in cpp file. 
in this case, it just doesn't work, no errors.

2.
declare handler in header file
```
void myHandler( Windows::Foundation::IInspectable const& sender,
             Microsoft::UI::Xaml::Input::TappedRoutedEventArgs const& args);
```
implements as below
```
    void BgLabelControl::myHandler( Windows::Foundation::IInspectable const& sender,
         Microsoft::UI::Xaml::Input::TappedRoutedEventArgs const& args)
    {
           OutputDebugString(L"newButton.Clicked\n");
    }

```

and then override OnApplyTemplate()
```
auto myBTN = this->GetTemplateChild(L"newButton").try_as<Microsoft::UI::Xaml::Controls::Button>();
myBTN.AddHandler(winrt::Microsoft::UI::Xaml::UIElement::TappedEvent(), winrt::box_value<winrt::Microsoft::UI::Xaml::Input::TappedEventHandler>({this, &BgLabelControl::myHandler }), true);
```

in this case, C2440 error was found in VS,
`'argument': cannot convert from 'O' to 'winrt::BgLabelControlApp::implementation::BgLabelControl &'	 in file	C:\........\Generated Files\winrt\Microsoft.UI.Xaml.Input.h`

Can anyone help me in this case? it's better if you can show my a complete example, I'm pretty new to C++/WinRT. Winui3, because I'm actually a chemical process engineer.

I have searched some source code in this repo and it seems WinUI3 do this in the same way like I did:

dev/ScrollView/ScrollView.cpp in this repo.

```
...
m_onHorizontalScrollControllerPointerEnteredHandler = winrt::box_value<winrt::PointerEventHandler>({ this, &ScrollView::OnHorizontalScrollControllerPointerEntered });
        horizontalScrollControllerElement.AddHandler(winrt::UIElement::PointerEnteredEvent(), m_onHorizontalScrollControllerPointerEnteredHandler, true);
...
```

by the way, can we have more example codes using C++/WinRT rather than C#/WinRT? a complicated UI example with VS-like UI that have floatable panel/sub-window.

**Comment by llongley** [comment]
Thanks for the question!  To answer the implicit question of which you should do, you can't add event handlers in XAML for templated controls - the correct pattern is to override `OnApplyTemplate()`, as you've done in the second option.  This should work:

```
// In class definition in .h file
winrt::Microsoft::UI::Xaml::Controls::Button::Click_revoker m_buttonClickRevoker{};
```

```
// In implementation in .cpp file
auto myBTN = GetTemplateChild(L"newButton").as<winrt::Microsoft::UI::Xaml::Controls::Button>();
m_buttonClickRevoker = myBTN.Click(winrt::auto_revoke, { this, &BgLabelControl::myHandler });
```

Generally speaking you'll want to attach an event handler using the named method like `Click()`; you don't need to use the generic `AddHandler()` method unless you specifically need to attach a handler for already-handled events.

Let me know if this works for you. :)

**Comment by ifgotmoney** [comment]
@llongley thank you very much!  your solution works fine for me.

**Comment by ifgotmoney** [comment]
@llongley Thank you very much, it works.
