### ISSUE TITLE
WinUI 3 - Update AppWindow custom buttons for Windows 11

### ISSUE THREAD

**Issue by martibravo** [microsoft/microsoft-ui-xaml#5699]
**Describe the bug**
Windows 11 introduced new caption button icons for windows. While being similar to Windows 10's, 11's caption button icons are more rounded and, in my opinion, a little bit thicker, to reflect the change in window geometry. 

When setting `AppWindowTitleBar.ExtendsContentIntoTitleBar` to _true_ the caption buttons don't reflect the new style on Windows 11.  In the screenshots section you can see a side-by-side view of the Settings app and a WinUI3 Desktop App titlebar. Notice that the maximize button is completely square for WinUI3, but rounded in Settings and many other windows. 

**Steps to reproduce the bug**

1. Create a WinUI3 Desktop app with the 1.0.0 experimental release.
2. Set `AppWindow.TitleBar.ExtendsContentIntoTitleBar` to `true`.
3. The caption buttons look like Windows 10's and not Windows 11's.

**Expected behavior**
WinUI3 custom caption buttons should be rounded on W11 and square on W10. WinUI should automatically choose the icons from the Segoe Fluent Icons font.

**Screenshots**

![image](https://user-images.githubusercontent.com/7605780/129586793-a39ab260-2fe7-4c29-9eff-d3d5128b8af6.png)

**Version Info**

NuGet package version: [WinUI 3 - Windows App SDK 1.0.0: 1.0.0-experimental]
Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.132)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by WSLUser** [comment]
Windows 11 looks like crap and you want to encourage apps to by default appear to be the same?

**Comment by martibravo** [comment]
> Windows 11 looks like crap and you want to encourage apps to by default appear to be the same?

Completely off-topic, but Windows 11 has the best UI since W7. Fluent Design now looks like it's ready to build complex and advanced apps with great UX. Microsoft reinvestment in Windows looks good.

**Comment by seven-mile** [comment]
No matter what do you think about the UI Design of Windows 11, the basic non-client area style should be unified. Many details of WinUI3 are supposed to be polished, surely including this issue.

**Comment by mevey** [comment]
Hey, this was a known bug in the experimental release and a fix has already been made. Expect the fix in the Preview 1 release.
