### ISSUE TITLE
Repeater should not run layout when viewport changes for non-virtualizing layouts

### ISSUE THREAD

**Issue by ranjeshj** [Microsoft/microsoft-ui-xaml#570]
**Describe the bug**
When using a non-virtualizing layout with repeater, we end up running layout every time the viewport changes. This is bad for perf and unnecessary. We should not run layout in this case.

**Comment by micahl** [comment]
Verified fixed in the latest prerelease (2.2.190430003-prerelease) since it still happens in the current official release (2.1.190405004.2).
