### ISSUE TITLE
Memory leak on Load/Unload events subscription.

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#5700]
Hello!

After update to v0.8.2 our tests detected the memory leaks. I found that the issue is reproduced if I subscribe on Load and Unload events in a custom control.

![image](https://user-images.githubusercontent.com/23479280/129586203-672c8b5e-1f56-40ba-8c83-56473bbaad74.png)

It is strange, but issue is reproduced only if I subscribe on the both events.

See the sample project in [attachement ](https://github.com/microsoft/microsoft-ui-xaml/files/6993489/App12.zip) to reproduce.

https://i.imgur.com/L28x7nH.gif

**Version Info**
WinUI 3 - Windows App SDK 0.8.2
Windows 20H2 (OS Build 19042.1165)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@bartekk8 @codendone and @MikeHillberg FYI

**Comment by chrisglein** [comment]
@Scottj1s is this maybe a cswinrt issue?

**Comment by ssaran046** [comment]
Hi Team,

I'm also facing the same issue. Any update on this?
