### ISSUE TITLE
(WinUI 3) AppWindow.TitleBar.SetDragRectangles not working with multiple drag areas.

### ISSUE THREAD

**Issue by martibravo** [microsoft/microsoft-ui-xaml#5703]
**Describe the bug**
The new AppWindowTitleBar has a method to define drag areas when using a custom TitleBar, accepting a RectInt32 array as parameter. So I suppose it should draw different drag areas given their X, Y, Width and Height properties. My app has a SearchBox inside the titlebar, and some other buttons. In total, I need WinUI to draw 3 drag rects on my Window, but it only loads the first one in the array.

Given DragRect, DragRect2 and DragRect3, when only appending one of them to the array they work as expected. However, when appending two or all of them, only the first one is applied.

**Steps to reproduce the bug**
1. Create a Project with WinUI 3 on Desktop - Blank App on VS2022. WindowsAppSDK 1.0.0 experimental should be installed, not 0.8.1.
2. Set the MainWindow's Titlebar to ExtendContent `m_titleBar.ExtendsContentIntoTitleBar = true;`
3. Try to calculate and apply some drag areas with `TitleBar.SetDragRectangles(dragRectsArray);`
4. Only the first rect is applied. Others are ignored.

**Expected behavior**
I expected WinUI to draw all the Drag Area Rects inside the array.

**Version Info**

NuGet package version: 
[WinUI 3 - Windows App SDK 1.0: 1.0.0-experimental] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.132)              | Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by martibravo** [comment]
I am closing this as I reviewed my code and found that the mistake was my fault. It's now working as expected. Thank you!

**Comment by Sahil12524** [comment]
> I am closing this as I reviewed my code and found that the mistake was my fault. It's now working as expected. Thank you!

what was the mistake?
