### ISSUE TITLE
How to run WinUI C# custom controls in WinUI C++ applications?

### ISSUE THREAD

**Issue by KanniyappanP** [microsoft/microsoft-ui-xaml#5705]
# Discussion: How to run WinUI C# custom controls WinUI C++ application?

I have created custom controls using WinUI C# class libraries, now trying to include this control in WinUI C++ application.

Is this possible to do this or we need to create separate control for C++. If so, which template need to select for creating custom control in WinUI C++

## Related Links
NA

**Comment by StephenLPeters** [comment]
I think this should just work, except that your c++ application will now load the CLR since it uses a C# component.  Have you tried it and ran into issue?

**Comment by KanniyappanP** [comment]
Hi @StephenLPeters 

yes, I have tried C# component in C++ applications and faced below issue.

`Could not install package 'DevExpress.Maui.Core 21.2.1-pre-21217'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:14.7380946`

Thanks.,

**Comment by hoshiizumiya** [comment]
Sample: https://github.com/[hoshiizumiya/WinUI3-CppWinRT-CsRuntimeComponent-Sample](https://github.com/hoshiizumiya/WinUI3-CppWinRT-CsRuntimeComponent-Sample)
issue: https://github.com/microsoft/CsWinRT/issues/2094
