### ISSUE TITLE
MUXC invalid pointer read (c0000005) crash: SendTelemetryOnSuspend

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#5709]
**Describe the bug**
In my microsoft partner center dashboad I saw that there were a few crashes when MUIX called up the telemetry on suspend.

**Steps to reproduce the bug/ Steps to reproduce the behavior**
not known
```
Frame	Image	Function	Offset
0	Microsoft.UI.Xaml.dll	SendTelemetryOnSuspend	0x0000000000101783	
1	Microsoft.UI.Xaml.dll	DllMain	0x0000000000052F4B	
2	Windows.UI.Xaml.dll	DirectUI::CEventSourceBase_DirectUI::IUntypedEventSource,Windows::Foundation::ITypedEventHandler_Windows::UI::Xaml::Controls::SplitView *,Windows::UI::Xaml::Controls::SplitViewPaneClosingEventArgs *_,Windows::UI::Xaml::Controls::ISplitView,Win	0x0000000000389645	
3	Windows.UI.Xaml.dll	DirectUI::XamlRoot::RaiseChangedEvent	0x0000000000000077	
4	Windows.UI.Xaml.dll	CFxCallbacks::XamlRoot_RaiseChanged	0x0000000000000070	
5	Windows.UI.Xaml.dll	CContentRoot::RaisePendingXamlRootChangedEventIfNeeded	0x000000000000009B	
6	Windows.UI.Xaml.dll	CCoreServices::OnVisibilityChanged	0x0000000000000136	
7	Windows.UI.Xaml.dll	CCoreServices::SetWindowVisibility	0x000000000000002A	
8	Windows.UI.Xaml.dll	CJupiterWindow::UpdateWindowVisibility	0x0000000000000079	
9	Windows.UI.Xaml.dll	CJupiterWindow::OnCoreWindowVisibilityChanged	0x000000000000000E	
10	Windows.UI.Xaml.dll	Microsoft::WRL::Details::DelegateArgTraits_long (__cdecl Windows::Foundation::ITypedEventHandler_impl_Windows::Foundation::Internal::AggregateType_Windows::UI::Core::CoreWindow *,Windows::UI::Core::ICoreWindow *_,Windows::Foundation::Internal:	0x000000000000001B	
11	Windows.UI.dll	Microsoft::WRL::InvokeTraits_-2_::InvokeDelegates__lambda_34d33ca7feb75b9bc38e667307a09231_,Windows::Foundation::ITypedEventHandler_IInspectable *,Windows::UI::Core::CoreWindowEventArgs *_ _	0x0000000000000069	
12	Windows.UI.dll	Microsoft::WRL::EventSource_Windows::Foundation::ITypedEventHandler_IInspectable *,Windows::UI::Core::KeyEventArgs *_,Microsoft::WRL::InvokeModeOptions_-2_ _::DoInvoke__lambda_f4cd532df69a4495b972020eb56331a5_ _	0x0000000000000078	
13	Windows.UI.dll	Windows::UI::Core::WindowServer::OnVisibilityChangedEvent	0x0000000000000159	
14	Windows.UI.dll	Windows::UI::Core::WindowServer::WndProc	0x000000000000025F	
15	user32.dll	UserCallWinProcCheckWow	0x00000000000002F8	
16	user32.dll	CallWindowProcW	0x000000000000008E	
17	Windows.UI.Xaml.dll	CJupiterWindow::CoreWindowSubclassProc	0x00000000000001D5	
18	Windows.UI.Xaml.dll	CJupiterWindow::StaticCoreWindowSubclassProc	0x000000000000004F	
19	user32.dll	UserCallWinProcCheckWow	0x00000000000002F8	
20	user32.dll	DispatchMessageWorker	0x0000000000000249	
21	Windows.UI.dll	Windows::UI::Core::CDispatcher::ProcessMessage	0x000000000000018B	
22	Windows.UI.dll	Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal	0x00000000000000C0	
23	Windows.UI.dll	Windows::UI::Core::CDispatcher::ProcessEvents	0x000000000000007B	
24	Windows.UI.Xaml.dll	CJupiterWindow::RunCoreWindowMessageLoop	0x000000000000004C	
25	Windows.UI.Xaml.dll	DirectUI::DXamlCore::RunMessageLoop	0x0000000000000047	
26	twinapi.appcore.dll	Windows::ApplicationModel::Core::CoreApplicationView::Run	0x000000000000003A	
27	twinapi.appcore.dll	_lambda_643db08282a766b00cec20194396f531_::operator	0x00000000000001EF	
28	SHCore.dll	_WrapperThreadProc	0x00000000000000E9	
29	kernel32.dll	BaseThreadInitThunk	0x0000000000000014	
30	ntdll.dll	RtlUserThreadStart	0x0000000000000021	
```

**Expected behavior**
No crash when MUIX send telemetry on suspend.

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.6.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
Looks very strange, the XamlRoot.Changed event is somehow calling into Winui2's DLL.Main() function... I'm not sure what to make of that, @jevansaks ring any bells?

**Comment by jevansaks** [comment]
So 2 problems:
1) These symbols don't look right
2) XamlRoot.Changed has a bug that if you attach to it with auto_revoke, the object doesn't get kept alive so when the code tries to disconnect from the event, it doesn't work. I made a helper XamlRootChanged_revoker to work around this platform bug.

We would need a crash dump or repro to know which code is getting called back to know what needs to be fixed (or confirm that we maybe already fixed it).

**Comment by jp-weber** [comment]
Unfortunately, I have no crash dump available in the Microsoft Partner Center.

**Comment by StephenLPeters** [comment]
Closing because this seems presently unactionable.
