### ISSUE TITLE
ContentDialog occupies space in a StackPanel

### ISSUE THREAD

**Issue by sylveon** [microsoft/microsoft-ui-xaml#5713]
**Describe the bug**
When putting ContentDialog in a StackPanel, it occupies vertical and horizontal space when it shouldn't. This happens exclusively with controls resources version 2

**Steps to reproduce the bug**
1. Add WinUI 2.6 to a blank app
2. Replace the placeholder Grid with the following in MainPage
   ```xaml
   <StackPanel>
       <ContentDialog />
       <Button>This should be at the top-right</Button>
   </StackPanel>
   ```

**Expected behavior**
The ContentDialog should not take any vertical space in the StackPanel

**Screenshots**
Good behavior, no WinUI installed
![image](https://user-images.githubusercontent.com/6440374/129810887-6f73889b-9116-40d0-9050-975510fd2e1a.png)

Good behavior, WinUI 2.6 and controls resource version 1
![image](https://user-images.githubusercontent.com/6440374/129811006-0fab618b-9ed7-4e2d-b3f3-7c8271af3dc6.png)

Bad behavior, WinUI 2.6 and controls resource version 2
![image](https://user-images.githubusercontent.com/6440374/129810909-5ee69a49-16d0-4962-b297-b51006b52f67.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes (system XAML islands) |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.132)              | Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Same happens when the StackPanel uses Horizontal layout

**Comment by StephenLPeters** [comment]
Somehow [this](https://github.com/microsoft/microsoft-ui-xaml/blob/eaae2ce70bcbe4b00a9ed2724c7cdbf3f09d8765/dev/CommonStyles/ContentDialog_themeresources_v1.xaml#L277) got lost in the move to the v2 [style](https://github.com/microsoft/microsoft-ui-xaml/blob/eaae2ce70bcbe4b00a9ed2724c7cdbf3f09d8765/dev/CommonStyles/ContentDialog_themeresources.xaml#L225)

**Comment by StephenLPeters** [comment]
@tashatitova looks like that happened here: https://github.com/microsoft/microsoft-ui-xaml/commit/67bb9672e3b0c240b6f6a38045198a4afb4b53b4 do you happen to remember why it was removed?

**Comment by chingucoding** [comment]
Unless someone else wants to work on this, I would take this issue.

**Comment by tashatitova** [comment]
@StephenLPeters looks accidental, shouldn't have been removed
