### ISSUE TITLE
Ring-shape ColorSpectrum Incorrectly Calculates Color When Dragging Cursor

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#5715]
**Describe the bug**

The ring-shape ColorSpectrum incorrectly calculates the color when dragging the captured cursor outside the bounds of the spectrum. In this situation the selected color should follow the perimeter of the circle; however, it sometimes jump inside the spectrum to an incorrect position. This only occurs at the right and bottom.

Keep in mind this issue and PR. It's conceivable that margin was done as a hack to fix the math in this case. If it was... this is why we add comments to code.

 * https://github.com/microsoft/microsoft-ui-xaml/issues/3235
 * https://github.com/microsoft/microsoft-ui-xaml/pull/3366

**Expected behavior**

Color should track the perimeter.

**Screenshots**

https://user-images.githubusercontent.com/17993847/129826905-02d8c1f6-6502-4cd2-ba25-705bb9c43196.mp4

**Version Info**

NuGet package version: Microsoft.UI.Xam 2.6.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Interesting.. we actually place the circle not where the mouse is, but where we calculate the currently selected color to be in the color spectrum.  It must be the case there are a few places where that math is wrong...

**Comment by robloo** [comment]
I'm seeing a pretty consistent crash now when selecting colors in the bottom of the spectrum. Seems to be a larger issue.

**Comment by robloo** [comment]
I don't see this in the current WinUI 2 Gallery so closing this. On the app side different tech is being used now anyway.
