### ISSUE TITLE
ComboBox SelectedValue binding

### ISSUE THREAD

**Issue by Mikozans** [microsoft/microsoft-ui-xaml#5719]
**Describe the bug**
ComboBox doesn't show selected value (UWP).

**Steps to reproduce the bug**
1.  Assign selected value
2. Change combo source

It works fine if you do it the other way around (changing first the source and then assigning the value)

**Expected behavior**
Combo shows selected value 

Demo App attached to reproduce it.
[ComboBoxSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7006813/ComboBoxSample.zip)

**Comment by StephenLPeters** [comment]
When the source changes we have no way of knowing if any of the previous values are valid and assume that we have received an entirely new collection, so we discard the selected value.  This is by design.
