### ISSUE TITLE
Discussion: Svg Image Source viewer is incomplete

### ISSUE THREAD

**Issue by humbertomoli99** [microsoft/microsoft-ui-xaml#5724]
# Discussion: Svg Image Source viewer is incomplete images overflow
when inserting an svg image into a container it overflows due to not knowing the actual measurements.

this line what it does is obtain the real measurements of the svg image so that it does not come out cut
```
var document = new Aspose.Svg.SVGDocument(Path.Combine(bitmapFolder, item.image));
var width = document.RootElement.Width.AnimVal.Value;
var height = document.RootElement.Height.AnimVal.Value;

var svgSource = new SvgImageSource(bitmapUri)
{
RasterizePixelHeight = Convert.ToDouble(height),
RasterizePixelWidth = Convert.ToDouble(width),
};
```
`<Image Grid.Column="0" Grid.Row="0"  Source="{Binding Icon1}" Visibility="Visible" Width="32" Height="32" VerticalAlignment="Center" HorizontalAlignment="Center" Stretch="UniformToFill"></Image>`

the problem is that this code runs very slow. there is no native way for this not to happen?

## Related Links
[https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.media.imaging.svgimagesource?view=winui-3.0](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.media.imaging.svgimagesource?view=winui-3.0)

**Comment by StephenLPeters** [comment]
@codendone FYI
