### ISSUE TITLE
InvalidOperationException when attempting to RenderTargetBitmap.RenderAsync

### ISSUE THREAD

**Issue by riverar** [microsoft/microsoft-ui-xaml#5727]
Calling `RenderTargetBitmap.RenderAsync` results in a `InvalidOperationException`.

**Steps to reproduce**
1. `git clone https://github.com/riverar/mux-repros/`
2. `cd mux-repros/unpackaged/mux_issue_5727`
3. `mux_issue_5727.sln`
4. Build/launch project
5. Observe exception in output / program terminates

**Version Info**

Windows App SDK 1.0-experimental1
Unpackaged desktop application
Windows 11 (22000.132)

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by riverar** [comment]
Can still reproduce on Windows App SDK 1.3.230502000

**Comment by riverar** [comment]
@llongley can you add some rationale text per the guidelines set forth by your team?

**Comment by codendone** [comment]
Copying the close rationale from the mirrored internal bug:
> The repro application provided is an unsupported scenario. RenderTargetBitmapis only valid if the content being targeted is connected to the main window xaml tree.
>
> While there may be a minor bug in that we are failing rather than just not rendering (as described in the documentation), this would be very low priority since even without this error it wouldn't do what the developer expected. For this reason, we are going to close this issue.

**Comment by riverar** [comment]
Thanks @codendone, that's great feedback!
