### ISSUE TITLE
Navigating to non-ASCII url fires NavigationStarting event infinite number of times

### ISSUE THREAD

**Issue by monica-ch** [microsoft/microsoft-ui-xaml#5728]
**Describe the bug**
Navigating to non-ASCII url using webview api in UWP fires NavigationStarting event infinite number of times using below code

Uri targetUri = new Uri(http://www.example.com/düsseldorf?neighbourhood=Lörick);
webView.Source = targetUri;    

or 

webView.CoreWebView2.Navigate(“http://www.example.com/düsseldorf?neighbourhood=Lörick”);

**Steps to reproduce the bug**
Sample repro app - https://github.com/monica-ch/UWP-Sample, https://github.com/monica-ch/WinUI-Desktop

**Expected behavior**
NavigationStarting event should fire only once.

**Version Info**
NuGet package version:  Microsoft.ProjectReunion 0.8.0-preview

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes |

**Additional context**
This issue is not seen in applications(Win32,  WPF/WinForms) using webview control for navigation.  Looks like there is unexpected behavior happening in UWP when using non-ascii url’s which calls webview API ‘N’ no of times.

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by krschau** [comment]
Fixed in WinUI 2 by https://github.com/microsoft/microsoft-ui-xaml/pull/6164
