### ISSUE TITLE
Question: Can I use this <StaticResource  ResourceKey=""/> in UWP app?

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5731]
`<StaticResource x:Key="AnotherKey"  ResourceKey="CommonBrushKey"/>` does not work in my UWP app.

**Comment by niels9001** [comment]
Use <StaticResource x:Key="MyBrushKey" /> instead?

**Comment by HppZ** [comment]
sorry, I don't understand.
