### ISSUE TITLE
Question: How to share resources like SolidColorBrush between a controls library and my app?

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5732]
How to share a SolidColorBrush (one instance, need to be accessible by default control style, named control style and my main app) between a controls library and my app?

**Comment by StephenLPeters** [comment]
We do this with Winui2 by publishing a new type called XamlControlsResources which derives from ResourceDictionary and when it is constructed puts the resources we need into its dictionary. Then we have apps include a <XamlControlsResources/> in their App's App.Resources.
