### ISSUE TITLE
Combobox autocompletes even when IsTextSearchEnabled="False"

### ISSUE THREAD

**Issue by mcooley** [microsoft/microsoft-ui-xaml#5733]
**Describe the bug**
I'm using a ComboBox to build a font size picker, which has several default font size choices but allows the user to type in a custom value. ComboBox will auto-select one of the values in the list even when IsTextSearchEnabled="false". This makes it difficult for users to enter a custom value which might be a prefix of one of the default choices.

**Steps to reproduce the bug**
```
<ComboBox IsEditable="True" IsTextSearchEnabled="False">
    <x:String>20</x:String>
    <x:String>40</x:String>
    <x:String>60</x:String>
    <x:String>80</x:String>
</ComboBox>
```
1) Set focus on the combo box and type "8".
2) Tab away from the combo box

Expected behavior: the combo box is set to "8"
Actual behavior: the combo box is set to "80"

**Version Info**
Windows 22000, occurs with or without WinUI 2

**Comment by StephenLPeters** [comment]
This combo box from xaml controls gallery does what you are looking for: https://github.com/microsoft/Xaml-Controls-Gallery/blob/84c97f0d870dc94c9d62626a5080cc1e1d5f26b3/XamlControlsGallery/ControlPages/ComboBoxPage.xaml#L61  It looks like the only difference is the IsTextSearchEnabled value.  Does changing that to true work for your scenario?

**Comment by mcooley** [comment]
In our scenario we really need IsTextSearchEnabled="False".

**Comment by StephenLPeters** [comment]
@mcooley ?

**Comment by mcooley** [comment]
The font size combo box in Xaml Controls Gallery also has the unwanted behavior described in the bug.

Font size pickers in prominent apps (for example, Microsoft Word) don't have the autocomplete behavior, so I'd expect to have a way to turn it off. I thought `IsTextSearchEnabled="False"` would be the way to turn it off. but it doesn't seem to have that effect.
