### ISSUE TITLE
Can't set ComboBox.SelectedItem when ComboBox isn't on screen

### ISSUE THREAD

**Issue by mcooley** [microsoft/microsoft-ui-xaml#5734]
**Describe the bug**
I have a ComboBox with IsEditable="true". When the ComboBox is loaded, I want to restore the user's input from a previous session, which may be a custom value which is not one of the combo box items. This doesn't work if the ComboBox is inside a container with Visibility="Collapsed".

**Steps to reproduce the bug**
```
<Border x:Name="ComboBoxContainer" Visibility="Collapsed">
    <ComboBox
        x:Name="ComboBox"
        IsEditable="True"
        Loaded="ComboBox_Loaded">
            <x:String>20</x:String>
            <x:String>40</x:String>
            <x:String>60</x:String>
            <x:String>80</x:String>
    </ComboBox>
</Border>
<Button Click="SetVisible_Click">Set ComboBoxContainer.Visibility = Visible</Button>

private void SetVisible_Click(object sender, RoutedEventArgs e)
{
    this.ComboBoxContainer.Visibility = Visibility.Visible;
}

private void ComboBox_Loaded(object sender, RoutedEventArgs e)
{
    this.ComboBox.SelectedItem = "100";
}
```
Click the button to make the combo box container visible. Expected behavior: "100" is in the combo box. Actual behavior: nothing is selected

However, if ComboBoxContainer.Visibility is initially set to Visible in the XAML, SelectedItem is set successfully and "100" is in the combo box.

**Expected behavior**
Setting SelectedItem should work even if the control's parent is not visible.

**Version Info**
Windows 22000, occurs with or without WinUI 2

**Comment by StephenLPeters** [comment]
@mcooley does chaning the value to one of the items in the combo box's collection like "80" change the behavior? Do you see the loaded event handler firing at all?

**Comment by mcooley** [comment]
(Sorry for the delayed response here.)

Yes, the Loaded event handler attached to the ComboBox does fire.

Yes, if the loaded event handler sets the value to an item that's already in the collection, like "80", the value is set correctly when the combobox becomes visible.
