### ISSUE TITLE
Can't set first custom value in editable ComboBox when IsTextSearchEnabled="false"

### ISSUE THREAD

**Issue by mcooley** [microsoft/microsoft-ui-xaml#5735]
**Describe the bug**
For a ComboBox configured as below, the first custom value the user enters is ignored.

**Steps to reproduce the bug**
```
<ComboBox
    IsEditable="True"
    IsTextSearchEnabled="False"
    SelectedItem="40">
        <x:String>20</x:String>
        <x:String>40</x:String>
        <x:String>60</x:String>
        <x:String>80</x:String>
</ComboBox>
```
When the ComboBox is first loaded, type "99" into the combo box and tab away. Expected behavior: the selected value is set to "99". Actual behavior: the selected value is reset to "40". 

On the second attempt, the selected value is set to "99" as expected.

**Version Info**
Windows 22000, occurs with or without WinUI 2

**Comment by StephenLPeters** [comment]
Does IsEditable=True and IsTestSearchEnabled=False make sense?

**Comment by mcooley** [comment]
> Does IsEditable=True and IsTestSearchEnabled=False make sense?
Yes, we want a combo box which allows you to type in custom values, but doesn't try to autocomplete to one of the existing values. The scenario is a font size picker which should work like the font size picker in Microsoft Office (for example). IsTextSearchEnabled=False seems to have other issues, though (see #5733).
