### ISSUE TITLE
AddDeleteThemeTransition must freeze control size until animation completes

### ISSUE THREAD

**Issue by xperiandri** [microsoft/microsoft-ui-xaml#5742]
**Describe the bug**

https://user-images.githubusercontent.com/2365592/130326071-6f027368-96a2-4ac4-9c08-0e799b5018d6.mp4

**Steps to reproduce the bug**
1. Create a `ListView` with 3 items
2. Create a button that removes the last item
3. Run the app and click on that button

**Expected behavior**
Control size freeze until the animation complete

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.*]

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@stmoy I think we've discussed this in the past but I'm struggling to remember. Can you weigh in?

**Comment by stmoy** [comment]
Good question - I am also struggling to remember. It seems like there is a need to defer the size change until after the animation is complete. I don't recall if there is a hook to do that, but I don't think there is. I think the item is immediately removed from the tree > the ListView changes size immediately > clips the last item.

@gegao18 do you have any ideas?
