### ISSUE TITLE
No CornerRadius for AppBarToggleButtons in TextCommandBarFlyout of RichEditBox

### ISSUE THREAD

**Issue by tipa** [microsoft/microsoft-ui-xaml#5749]
**Describe the bug**

No `CornerRadius` for `AppBarToggleButtons` in `TextCommandBarFlyout` of `RichEditBox`

**Steps to reproduce the bug**

1. Open XAML Control Gallery
2. Go to RichEditBox page (xamlcontrolsgallery://item/RichEditBox)
3. Right click text field

![image](https://user-images.githubusercontent.com/2863198/130430970-b34a1e9a-56f8-485d-9afe-0f4655a518af.png)

NuGet package version: 
Microsoft.UI.Xaml 2.6.2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Build 19043.1165| Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
Good Catch!

**Comment by tipa** [comment]
Still unfixed

**Comment by DmitriyKomin** [comment]
@tipa, thank you for reporting this. We are tracking AppBarToggleButton lack of rounded corners with #8226 , closing this bug as duplicate.

**Comment by tipa** [comment]
@DmitriyKomin "duplicate" in the sense that the other issue also covers UWP? Or are fixes for UWP not on the table any more?

**Comment by darsh-agrawal71** [comment]
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/114877279/766d874c-1c11-47cf-9af5-d22436f7ff29)
same here, using microsoft.ui.xaml nuget package (latest 2.8.6)
