### ISSUE TITLE
ListView Items can not be recreated after refreshing items

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#5755]
**Describe the bug**
I'm not sure if the title is appropriate or not. Anyway, I'm trying to explain the problem.
i have a listview with following codes
```
<ListView ItemsSource="{x:Bind Subtitles, Mode=OneWay}">
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="local:model">
                    <local:SubsceneUserControl Title="{x:Bind Title}"/>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```
and this is my usercontrol (as itemtemplate) 
```
<Grid>
        <SwipeControl x:Name="ListViewSwipeContainer">
            <Grid VerticalAlignment="Center">
                <Grid.RowDefinitions>
                    <RowDefinition Height="auto"/>
                    <RowDefinition Height="auto"/>
                </Grid.RowDefinitions>
                <TextBlock
                    Margin="10,5,200,5"
                    HorizontalAlignment="Left"
                    VerticalAlignment="Center"
                    FontSize="18"
                    Text="{Binding ElementName=subsceneView, Path=Title}"
                    TextWrapping="Wrap"/>
                <AppBarButton
                    Name="OpenFolderButton"
                    Grid.RowSpan="2"
                    MinWidth="75"
                    Margin="10,0,10,0"
                    HorizontalAlignment="Right"
                    VerticalAlignment="Center"
                    Click="OpenFolderButton_Click"
                    Icon="OpenLocal"
                    IsTabStop="False"
                    Label="Open Folder"
                    Visibility="Collapsed"/>

                <AppBarButton
                    Name="DownloadHoverButton"
                    Grid.RowSpan="2"
                    Margin="10,0,10,0"
                    HorizontalAlignment="Right"
                    VerticalAlignment="Center"
                    Click="DownloadHoverButton_Click"
                    Icon="Download"
                    IsTabStop="False"
                    Label="Download"
                    Visibility="Collapsed"/>

            </Grid>
        </SwipeControl>
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="HoveringStates">
                <VisualState x:Name="HoverButtonsHidden"/>
                <VisualState x:Name="HoverButtonsShown">
                    <VisualState.Setters>
                        <Setter Target="DownloadHoverButton.Visibility" Value="Visible"/>
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>
    </Grid>
```

now I will add some items to it
```
private ObservableCollection<model> _subtitles = new ObservableCollection<model>();
        public ObservableCollection<model> Subtitles
        {
            get { return _subtitles; }
            set { _subtitles = value; }
        }

private void AddItems()
        {
            Subtitles?.Clear();
            for (int i = 0; i < 10; i++)
            {
                Subtitles.Add(new model { Title = "Test " + i });

            }
        }
```
Everything looks good
![1111](https://user-images.githubusercontent.com/9213496/130318185-1b2bc7d2-f2ad-45ec-aa39-fff3fbc8e408.gif)

Now by clicking on the button, the download button is hidden and another button (open folder) is displayed
![2222](https://user-images.githubusercontent.com/9213496/130318224-437e58a4-3656-4a62-baf5-da4387aa83ad.gif)

Now if we delete the items and add them again, we will face the following problem
![333](https://user-images.githubusercontent.com/9213496/130318274-5a3d9a3b-a558-4fe7-8ec6-fb05b611dbe1.gif)

As you can see, open folder button already exist (it should not be), and its location changes with each refresh.

**Steps to reproduce the bug**

1. Download sample project
[App30.zip](https://github.com/microsoft/WindowsAppSDK/files/7025284/App30.zip)

**Expected behavior**

By deleting and adding items, the itemTemplate must be re-created and no previous changes left
**Screenshots**

**Version Info**

NuGet package version: 

```
<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.1" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.1" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.1" />

```

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

I also see this problem in UWP I could not find a better place to report this problem. So I apologize if I reported in the wrong place

**Comment by StephenLPeters** [comment]
This is caused by ListView's virtualization features.  List view items recycle their containers for performance reasons, the VSM state is on the container and is not being reset when the container is recycled.... @ranjeshj or @RBrid what should @ghost1372 be doing differently here?

**Comment by ghost1372** [comment]
Thank you @StephenLPeters 
I changed the itemPanel to a stackpanel. The problem was solved but a new problem was created and scrolling and loading items is very slow.

**Comment by StephenLPeters** [comment]
This is because using a stack panel breaks list view virtualization :/ so while it fixes this recycling issues, its only doing so because it isn't doing the high performance virtualization behaviors.

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by ranjeshj** [comment]
@ghost1372 @StephenLPeters  is right. This is caused by the virtualizing nature of ListView's default panel (ItemsStackPanel). It essentially reuses the same ListViewItem (containers) and when it reuses them it might be in a state that is not correct. When you use stack panel, there is no virtualization and every item gets a container (no reuse) which as you can imagine can get very time consuming if there are many items in your list. You can try using PrepareContainerForItemOverride, ClearContainerForItemOverride to cleanup the ListViewItem's state before they get reused. Even better would be to use the ContainerContentChanging event and do it there so you don't need a derived type.

**Comment by ghost1372** [comment]
Thank you @ranjeshj 
I will definitely try

**Comment by ghost1372** [comment]
@StephenLPeters  can you help me? How exactly should I clear the  ListViewItem's state?

```
 protected override void PrepareContainerForItemOverride(DependencyObject element, object item)
        {
            base.PrepareContainerForItemOverride(element, item);
        }
        protected override void ClearContainerForItemOverride(DependencyObject element, object item)
        {
            base.ClearContainerForItemOverride(element, item);
        }
```

**Comment by StephenLPeters** [comment]
@ghost1372 whatever you do in the DownloadHoverButton_Click to hide the download button and show the open folder button needs to be undone in the PrepareContainerForItemOverride.
