### ISSUE TITLE
Map Header and Subheader to Display and TextLarge

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5759]
Windows 11 and WinUI 2.6 have introduced a new type ramp based on Segoe UI Variable. Most of them have the same names as before (Caption, Base, Title etc...) however instead of Header and Subheader, now we have Display and TextLarge. This means if you use the text styles with unchanged names, you'll get new font but if you use Header and Subheader, you will not. I would recommend mapping Header and Subheader to Display and TextLarge respectively for consistency. Although Display has a much larger font size than Header, replacing may cause issues in fixed layouts. However good user interfaces always make use of dynamic containers and since this will only affect WinUI 2.6+ and developers will need to look into visual issues anyway when upgrading from an older version of WinUI, it makes much more sense. Since Header and Subheader is part of the system styles, it can't be removed so map it to the new styles instead. Maybe it could be removed from WinUI 3 as it's decoupled from the system so deprecated stuff can be gone.

```
<StaticResource x:Key="HeaderTextBlockStyle" ResourceKey="DisplayTextBlockStyle" />
<StaticResource x:Key="SubheaderTextBlockStyle" ResourceKey="TitleLargeTextBlockStyle" />
```

**Comment by StephenLPeters** [comment]
@licanhua and @mdtauk what do you think?

**Comment by mdtauk** [comment]
I think I would expect no big changes to font sizes when I as a developer/designer have specifically used a named resource.

Where the font size does not change, then mapping a new font-weight and Variable style is a good idea.

But where the font size changes, a custom Style that fits the Variations used by WinUI 2.6/2.7/3.0 should be added, and deprecated with 3.0 where the use of that older style is not recommended.
