### ISSUE TITLE
Xaml Islands Crash on Start

### ISSUE THREAD

**Issue by hoo29** [microsoft/microsoft-ui-xaml#5766]
**Describe the bug**

Raising based on advice from microsoft/terminal/issues/11025

When I start apps such as Windows Terminal or Microsoft PowerToys settings page, I very briefly see a window and then the app crashes. Event Viewer contains entries such as these:
```
Faulting application name: PowerToys.Settings.exe, version: 0.43.0.0, time stamp: 0x5e222541
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x891df6d3
Exception code: 0xc000027b
Fault offset: 0x000000000010bd3e
Faulting process ID: 0xdbc
Faulting application start time: 0x01d799b68eb0cd0d
Faulting application path: C:\Program Files\PowerToys\Settings\PowerToys.Settings.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: c419a60a-bf62-47c4-b429-801ff1665c6b
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Faulting application name: WindowsTerminal.exe, version: 1.9.2107.13002, time stamp: 0x60edf3e3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x891df6d3
Exception code: 0xc000027b
Fault offset: 0x000000000010bd3e
Faulting process ID: 0xed0
Faulting application start time: 0x01d798dffb5a7eb6
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.9.1942.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: ac419911-ee2b-4ffe-a588-009d02877944
Faulting package full name: Microsoft.WindowsTerminal_1.9.1942.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Steps to reproduce the bug**
Open the settings page for Microsoft PowerToys
Open Windows Terminal

**Expected behavior**
They open

**Screenshots**
n/a

**Version Info**
Latest stable builds from GitHub / Microsoft Store

NuGet package version: 
n/a

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
Have tried
* sfc /scannow
* repair install of `.NET Core 3.1 Desktop Runtime (v3.1.15) - Windows x64`

**Comment by zadjii-msft** [comment]
I recommended filing this here because both the Terminal and the PowerToys settings are XAML Islands apps. I presumed that both crashing would indicate some sort of issue in Islands itself for this user.

**Comment by hoo29** [comment]
asklar - does the stack trace above help?

**Comment by asklar** [comment]
I couldn't glean anything from the dumps in the Feedback Hub bug unfortunately, and I'm out of the office for a couple of weeks :).  @zadjii-msft @dhowett can you guys follow up?

**Comment by zadjii-msft** [comment]
I think @minksa was taking a look at this in https://github.com/microsoft/microsoft-ui-xaml/issues/5435?

**Comment by StephenLPeters** [comment]
@hoo29 #5435 only repros on older versions of windows 10 (19h1 and 19h2 I think), you are seeing this on 21h1?

**Comment by hoo29** [comment]
Yep
![image](https://user-images.githubusercontent.com/15928164/133829032-a27e9b06-d4f3-4f7d-9cea-c17fcf11c942.png)

**Comment by StephenLPeters** [comment]
@zadjii-msft and @miniksa given that this repros on 21h1 I don't think this is a dupe of #5435, have you seen this issue in terminal?

**Comment by zadjii-msft** [comment]
I haven't come across any other reports of this, no.

**Comment by ranjeshj** [comment]
@kmelmon as FYI

**Comment by htcfreek** [comment]
We have a crash with the same crash data for PowerRemame too: On starting the app and sometimes (if start works) on resizing the window: #

**Comment by StephenLPeters** [comment]
@marb2000 FYI

**Comment by stefansjfw** [comment]
Some more info here https://github.com/microsoft/PowerToys/issues/14356, looks like it can be related to screen resolution and DPI

**Comment by hoo29** [comment]
Had a play by disabling my second monitor and trying out the resolutions mentioned in the other thread. Sadly, it did not change the behaviour for me.

**Comment by stefansjfw** [comment]
@hoo29 What is your default resolution and dpi? Can you try installing [latest PowerToys](https://github.com/microsoft/PowerToys/releases/tag/v0.49.1) and check whether PowerRename works for you? Thanks in advance!

**Comment by hoo29** [comment]
Main monitor is 2560x1440 at 100% scaling. Installed PowerToys 0.49.1 but PowerRename (and the other apps) don't work for me with the same issue.

**Comment by stefansjfw** [comment]
@hoo29 Did you try installing latest version of .NET core desktop? Just to rule out that one...

**Comment by hoo29** [comment]
Downloaded and installed the desktop runtime and runtime from https://dotnet.microsoft.com/download/dotnet/3.1 but no dice.

**Comment by MrM40** [comment]
Version `1.13.220208005-release1.13` run fine, but `1.15.2207.19003` close immediately and give me the KERNELBASE.dll error in event viewer.
Running W10 LTSC 21H1

**Comment by MrM40** [comment]
![image](https://user-images.githubusercontent.com/16258063/184553224-d98f18e2-5294-4c4e-a8af-fd5af923cf1f.png)

**Comment by zadjii-msft** [comment]
Woah wait if that's the issue, then the root cause all this time has just been "you're missing the vclibs". The Windows 10 Terminal package ships those in our package, while the Windows 11 version doesn't. The Windows 11 version of the package can get away with this, because there were certain fixes to framework packages in Windows 11 that weren't able to be backported to Windows 10[1]. If you're on Windows 10, then yea, install the Windows 10 version of the Terminal. 

This probably applies to PowerToys too - if PT is using MUX then they too would be assuming that the VCLibs get installed properly as a dependency here. 



[1]: this is a _mild fact_. My memory might be hazy here.

**Comment by MrM40** [comment]
I must admit I install WT manually (extract the .msixbundle file etc)....I only had my eyes on the version numbers. 
I did wonder about the size difference though, but now it all make sense :-))

**Comment by hoo29** [comment]
Since raising this issue I have installed windows 11 and this is no longer a problem, I will close this issue.

I did install WT from Microsoft store as part of the testing so would have assumed that gave me the W10 version with the required deps.
