### ISSUE TITLE
ItemsControl margin changed while scrolling

### ISSUE THREAD

**Issue by susmitha-sundar** [microsoft/microsoft-ui-xaml#5767]
**Describe the bug**

Hi Team,

I have created the custom control with ItemsControl. In its control template, I have added the checkbox and itemscontrol in same row (for both set Grid.Row = 1) of Grid. I have set the Margin for ItemsControl as Margin(4,35,4,4);  I set the top margin value as 35 pixcel, to set the CheckBox control above the ItemsControl. Its arrange properly while loading. Check the below image,

![image](https://user-images.githubusercontent.com/60175573/130817926-b6897518-721b-44fa-9ff6-13b1990c919e.png)

After scrolling, control overlapped with checkbox,

![image](https://user-images.githubusercontent.com/60175573/130818047-fcca6c9c-dab4-4b9a-a54a-282eb9c64218.png)

**Steps to reproduce the bug**

Run the attached sample and scroll the ItemsControl.

**Version Info**
 WinUI NuGet package version - 0.8.1

NuGet package version: 

[WinUI 3 - Project Reunion 0.8.1]

Sample:

[ItemsControlDemo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7048132/ItemsControlDemo.zip)

**Comment by StephenLPeters** [comment]
@susmitha-sundar I believe this is expected. setting a larger margin on the content of a scroller doesn't change the viewport that scrollable content can be displayed in, it simply causes that content to take up extra space during layout. Then when you scroll that content it ends up drawing in the location that use to contain that extra space.  Instead what you want is a padding between the scrollviewer and its content.  Does the scrollviewer have a padding property that works for you? Can you post the markup you are using?

**Comment by StephenLPeters** [comment]
Yes, this is one of the differences in behavior for the margin and padding property.  If you set the padding does this work?

**Comment by susmitha-sundar** [comment]
Hi Team,

Thank you for the update

Scrollviewer's padding property works and scroll bar shown for entire control. I have faced one more issue. When I press the down key, items control scrolled. But down key not scrolled entirely.  Its needs to manual scrolling to scroll fully. Please refer the below gif,

![ezgif com-gif-maker](https://user-images.githubusercontent.com/60175573/134928615-7c407dad-7360-44f2-b352-f58561903e31.gif)

Sample:
[ItemsControlDemo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7237048/ItemsControlDemo.zip)

Could you please check and provide any suggestion?

**Comment by ranjeshj** [comment]
@susmitha-sundar what scenario are you trying ? It looks like you want items that are selectable. could you just use a ListView instead which already supports selection and provides the selection visuals ?

**Comment by StephenLPeters** [comment]
@susmitha-sundar is the ammount of content that is not scrollable proportional to the padding you've placed on the scrollviewer?

**Comment by StephenLPeters** [comment]
So it is present even if you don't set the padding?
