### ISSUE TITLE
WinUI 2.6.X/2.7.X cause the submission to MSStore failure with error code 1201 (Only in Windows Application Packaging Project with FullTrustProcess)

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#5768]
**Describe the bug**
Failed to submit the package to Microsoft Store if an UWP App is Windows Application Packaging Project with fullTrustProcess.
Once you submit your package. Microsoft Store will report "Attention needed" after a few minutes. Error code is 1201

Someone report the same issue [here](https://github.com/microsoft/microsoft-ui-xaml/issues/5262#issuecomment-904993749)

**Steps to reproduce the bug**
1. Create a Windows Application Packaging Project with UWP project and .Net Framework project
2. Install WinUI 2.6.X or WinUI 2.7.0preview
3. Publish and submit to MSStore

**Expected behavior**
Pass the certification and should not report 1201

**Screenshots**
![image](https://user-images.githubusercontent.com/42038175/130831696-76e38bcd-aec4-45ec-8c79-60851e576ab5.png)

**Version Info**
Encountered issue in:
[Microsoft.UI.Xaml 2.6.1]
[Microsoft.UI.Xaml 2.6.2]
[Microsoft.UI.Xaml 2.7.0-preview]

Disappear in:
[Microsoft.UI.Xaml 2.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
  | Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
None

**Comment by zhuxb711** [comment]
@chingucoding @ranjeshj @michael-hawker Could help take a look at this issue? I have tested X64 only package and it fails again. @gus33000

**Comment by yaichenbaum** [comment]
@dpaulino can you see if your having this issue with Nightingale?

**Comment by zhuxb711** [comment]
@yaichenbaum Have you test it in your project?

**Comment by zhuxb711** [comment]
> > @yaichenbaum Have you test it in your project?
> 
> 
> 
> Files was just approved (x64, x86)...

That is really wired

**Comment by zhuxb711** [comment]
I test it and here is the result:
WinUI 2.5 All -> Worked
WinUI 2.6.2 X64 only Version 1 Style -> Worked
WinUI 2.6.2 X64 only Version 2 Style -> Error 1201
WinUI 2.6.2 X64|ARM Version 1 Style -> Error 1201
WinUI 2.6.2 X64|ARM Version 2 Style -> Error 1201

**Comment by riverar** [comment]
@StephenLPeters @gabbybilka Can you help route this?

**Comment by myokeeh** [comment]
Why can't the Partner Center team ever stay ahead of these so it's never a problem?

**Comment by AathifMahir** [comment]
Noticing same issue on WinUI 2.6.2, without Arm64 binary, i can successfully publish to store.

The workaround for now is drop the support for Arm64 and include all other instructions sets X86, X64, Arm

**Comment by zhuxb711** [comment]
> Noticing same issue on WinUI 2.6.2, without Arm64 binary, i can successfully publish to store.
> 
> The workaround for now is drop the support for Arm64 and include all other instructions sets X86, X64, Arm

It seems that I could not pass the validation even drop the support for Arm64

**Comment by crramirez** [comment]
Just a reminder. Windows 11 ships in about 3 weeks, and our applications are not ready to take advantage of the new styles. Users will see beautiful Settings and an ugly Raft WSL and Files (among others). Would you mind increasing the priority of this?

I don't have the luxury to skip the ARM64 version of my app.

**Comment by zhuxb711** [comment]
Issue still exists in 2.7.0

**Comment by zhuxb711** [comment]
From microsoft store support:
> Please create .NET Native repro following steps here: 
> https://github.com/dotnet/core/blob/main/Documentation/ilcRepro.md#creating-and-sending-a-net-native-repro and please
> send that repro to dotnetnative@microsoft.com. They can assist you with this issue. 

I could not create the ilcRepro because VS will throw some exception when compiling if I added 
```
<NetNativeReproPath>C:\myReproDirectory</NetNativeReproPath>
```

**Comment by StephenLPeters** [comment]
@zhuxb711 do you have a repro project handy that you can share with the team?

**Comment by zhuxb711** [comment]
> @zhuxb711 do you have a repro project handy that you can share with the team?

Yes. My project is opened source. So feel free to download it here:

https://github.com/zhuxb711/RX-Explorer

How to 100% reproduce this issue:

1. Download the repro.
2. Install Microsoft.UI.Xaml 2.6.2 or 2.7.0
3. Go to App.xaml and set Microsoft.UI.Xaml ControlStyleVersion=Version2
4. Build a CI package to publish
5. Submit to Microsoft Store and wait for a few minutes 
6. See error 1201

I could provide a CI package if you want

**Comment by zhuxb711** [comment]
@StephenLPeters Did you find anything that could share with us?

**Comment by AathifMahir** [comment]
> @StephenLPeters Did you find anything that could share with us?

Hey, here's what you need to do let go this issue, first you need to remove ARM64 from All the different project in your solution and then you need to edit your project configuration for Arm and for Arm fulltrust project you need to use any cpu, that's all

It's good go and you'd no longer going to see the error on partner center

**Comment by crramirez** [comment]
@AathifMahir and are you sure it is compiling to ARM64? and not x86 in emulation mode? which architectures are listed in the resulting package? This looks like the solution we needed to do before ARM64 was supported in .NET for example .Net Framework 4.8

**Comment by AathifMahir** [comment]
> @AathifMahir and are you sure it is compiling to ARM64? and not x86 in emulation mode? which architectures are listed in the resulting package? This looks like the solution we needed to do before ARM64 was supported in .NET for example .Net Framework 4.8

It doesn't, currently only option is use Arm aka arm32 instead of Arm64 to get through this error

**Comment by crramirez** [comment]
Well then, thank you for your suggestion. I will wait until they fix the issue. Meanwhile, I'll stay in 2.5. My app needs ARM64 to access 64 binaries, and I don't want to activate again the terrible workaround that I did from x86 emulation mode, mostly because I don't have an arm64 pc to test.

**Comment by zhuxb711** [comment]
> @zhuxb711
> Hey, here's what you need to do let go this issue, first you need to remove ARM64 from All the different project in your solution and then you need to edit your project configuration for Arm and for Arm fulltrust project you need to use any cpu, that's all
> 
> It's good go and you'd no longer going to see the error on partner center

Yes I drop the ARM64 and my configuration for UWP is X64 and ARM, fullTrustProcess is AnyCPU but this seems still exists.

**Comment by AathifMahir** [comment]
> Well then, thank you for your suggestion. I will wait until they fix the issue. Meanwhile, I'll stay in 2.5. My app needs ARM64 to access 64 binaries, and I don't want to activate again the terrible workaround that I did from x86 emulation mode, mostly because I don't have an arm64 pc to test.

By the way, are you sure you named all the different projects arm64 in the solution properly? Make sure to name arm64 in lower case not uppercase like this ARM64, that also could cause some issues with certification

**Comment by zhuxb711** [comment]
@AathifMahir You mean drop ARM64 from configuration manager? 
Or simply remove it from the build option of "Publish" ?

For now I use this build option: 
```
/p:AppxBundlePlatforms="x64|ARM"
```

**Comment by AathifMahir** [comment]
> @AathifMahir You mean drop ARM64 from configuration manager? 
> 
> Or simply remove it from the build option of "Publish" ?
> 
> 
> 
> For now I use this build option: 
> 
> ```
> 
> /p:AppxBundlePlatforms="x64|ARM"
> 
> ```
> 
> 

I mean simply uncheck arm64 when building the msixupload

**Comment by zhuxb711** [comment]
Yes that is the key point. I don't know why the issue still exists after dropping the support for arm64

**Comment by AathifMahir** [comment]
> Yes that is the key point. I don't know why the issue still exists after dropping the support for arm64

If there's some issue with your .sln then the issue would still exist, share your .sln, will look into it

**Comment by zhuxb711** [comment]
@AathifMahir 
Feel free to check it in here: https://github.com/zhuxb711/RX-Explorer
It uses WinUI 2.5 for the time being and will fail with 1201 if upgrade to WinUI 2.6.X or 2.7.0

**Comment by AathifMahir** [comment]
> @AathifMahir
> Feel free to check it in here: https://github.com/zhuxb711/RX-Explorer
> It uses WinUI 2.5 for the time being and will fail with 1201 if upgrade to WinUI 2.6.X or 2.7.0

I went through your files and you use any cpu configs for X64 and X86 binaries too, that's why your having this issue, what you need to do is only use any cpu for Arm aka arm32

**Comment by zhuxb711** [comment]
> > @AathifMahir
> > Feel free to check it in here: https://github.com/zhuxb711/RX-Explorer
> > It uses WinUI 2.5 for the time being and will fail with 1201 if upgrade to WinUI 2.6.X or 2.7.0
> 
> I went through your files and you use any cpu configs for X64 and X86 binaries too, that's why your having this issue, what you need to do is only use any cpu for Arm aka arm32 only

I could not run my application in AnyCPU so it always use X64/Arm. I'm not understand what you mean........Could you give me some screen shot? Very appreciate!

**Comment by AathifMahir** [comment]
@zhuxb711 I was referring to some of these release X64 binaries using Any Cpu
![Screenshot 2021-09-23 164053](https://user-images.githubusercontent.com/17165402/134497513-b64ba4fc-1fa4-440c-bcfd-06b694fc478d.png)

**Comment by AathifMahir** [comment]
> @zhuxb711 I was referring to some of these release X64 binaries using Any Cpu
> ![Screenshot 2021-09-23 164053](https://user-images.githubusercontent.com/17165402/134497513-b64ba4fc-1fa4-440c-bcfd-06b694fc478d.png)

There's another as well in line 96 and 97 that you should change from Any Cpu to x64

**Comment by zhuxb711** [comment]
@AathifMahir I changed those "Any CPU" to "X64" but the issue still exists. Submission failed with code 1201

**Comment by zhuxb711** [comment]
@AathifMahir Like this:

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.29020.237
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "RX_Explorer", "RX_Explorer\RX_Explorer.csproj", "{02D26683-3BD6-4B30-8457-62CD714B0ADF}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "AnimationEffectProvider", "AnimationEffectProvider\AnimationEffectProvider.csproj", "{3B40A94D-6173-4B62-971E-27ABDBECE9D6}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "SystemInformationProvider", "SystemInformationProvider\SystemInformationProvider.vcxproj", "{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "UpdateCheckBackgroundTask", "UpdateCheckBackgroundTask\UpdateCheckBackgroundTask.csproj", "{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "FullTrustProcess", "FullTrustProcess\FullTrustProcess.csproj", "{04F23FCE-9DCC-4B3E-B088-F1016F628C65}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "CommunicateService", "CommunicateService\CommunicateService.csproj", "{7D62AF29-E32F-4402-88E5-D8FEEB062728}"
EndProject
Project("{C7167F0D-BC9F-4E6E-AFE1-012C56B48DB5}") = "Package", "Package\Package.wapproj", "{168437FF-BB72-4770-9F57-252AC94D4FCE}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ComputerVision", "ComputerVision\ComputerVision.csproj", "{5BC5B5AA-53F4-4437-95B3-261F790AE373}"
EndProject
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "OpenDirectoryExt", "OpenDirectoryExt\OpenDirectoryExt.vcxproj", "{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MaintenanceTask", "MaintenanceTask\MaintenanceTask.csproj", "{62F0700F-394A-43DE-92FD-FCFE063069D3}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ShareClassLibrary", "ShareClassLibrary\ShareClassLibrary.csproj", "{57848D87-5F61-4150-B6DC-56A87AC0AEAE}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|ARM = Debug|ARM
		Debug|x64 = Debug|x64
		Release|ARM = Release|ARM
		Release|x64 = Release|x64
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{02D26683-3BD6-4B30-8457-62CD714B0ADF}.Debug|ARM.ActiveCfg = Debug|ARM
		{02D26683-3BD6-4B30-8457-62CD714B0ADF}.Debug|ARM.Build.0 = Debug|ARM
		{02D26683-3BD6-4B30-8457-62CD714B0ADF}.Debug|x64.ActiveCfg = Debug|x64
		{02D26683-3BD6-4B30-8457-62CD714B0ADF}.Debug|x64.Build.0 = Debug|x64
		{02D26683-3BD6-4B30-8457-62CD714B0ADF}.Release|ARM.ActiveCfg = Release|ARM
		{02D26683-3BD6-4B30-8457-62CD714B0ADF}.Release|ARM.Build.0 = Release|ARM
		{02D26683-3BD6-4B30-8457-62CD714B0ADF}.Release|x64.ActiveCfg = Release|x64
		{02D26683-3BD6-4B30-8457-62CD714B0ADF}.Release|x64.Build.0 = Release|x64
		{3B40A94D-6173-4B62-971E-27ABDBECE9D6}.Debug|ARM.ActiveCfg = Debug|ARM
		{3B40A94D-6173-4B62-971E-27ABDBECE9D6}.Debug|ARM.Build.0 = Debug|ARM
		{3B40A94D-6173-4B62-971E-27ABDBECE9D6}.Debug|x64.ActiveCfg = Debug|x64
		{3B40A94D-6173-4B62-971E-27ABDBECE9D6}.Debug|x64.Build.0 = Debug|x64
		{3B40A94D-6173-4B62-971E-27ABDBECE9D6}.Release|ARM.ActiveCfg = Release|ARM
		{3B40A94D-6173-4B62-971E-27ABDBECE9D6}.Release|ARM.Build.0 = Release|ARM
		{3B40A94D-6173-4B62-971E-27ABDBECE9D6}.Release|x64.ActiveCfg = Release|x64
		{3B40A94D-6173-4B62-971E-27ABDBECE9D6}.Release|x64.Build.0 = Release|x64
		{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}.Debug|ARM.ActiveCfg = Debug|ARM
		{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}.Debug|ARM.Build.0 = Debug|ARM
		{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}.Debug|x64.ActiveCfg = Debug|x64
		{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}.Debug|x64.Build.0 = Debug|x64
		{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}.Release|ARM.ActiveCfg = Release|ARM
		{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}.Release|ARM.Build.0 = Release|ARM
		{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}.Release|x64.ActiveCfg = Release|x64
		{B7BEEF6E-1F7F-43B6-A1EC-F447B3F995DF}.Release|x64.Build.0 = Release|x64
		{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}.Debug|ARM.ActiveCfg = Debug|ARM
		{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}.Debug|ARM.Build.0 = Debug|ARM
		{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}.Debug|x64.ActiveCfg = Debug|x64
		{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}.Debug|x64.Build.0 = Debug|x64
		{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}.Release|ARM.ActiveCfg = Release|ARM
		{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}.Release|ARM.Build.0 = Release|ARM
		{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}.Release|x64.ActiveCfg = Release|x64
		{F6D7BF7B-AA4F-4F20-A6FE-45C60C75F88A}.Release|x64.Build.0 = Release|x64
		{04F23FCE-9DCC-4B3E-B088-F1016F628C65}.Debug|ARM.ActiveCfg = Debug|Any CPU
		{04F23FCE-9DCC-4B3E-B088-F1016F628C65}.Debug|ARM.Build.0 = Debug|Any CPU
		{04F23FCE-9DCC-4B3E-B088-F1016F628C65}.Debug|x64.ActiveCfg = Debug|x64
		{04F23FCE-9DCC-4B3E-B088-F1016F628C65}.Debug|x64.Build.0 = Debug|x64
		{04F23FCE-9DCC-4B3E-B088-F1016F628C65}.Release|ARM.ActiveCfg = Release|Any CPU
		{04F23FCE-9DCC-4B3E-B088-F1016F628C65}.Release|ARM.Build.0 = Release|Any CPU
		{04F23FCE-9DCC-4B3E-B088-F1016F628C65}.Release|x64.ActiveCfg = Release|x64
		{04F23FCE-9DCC-4B3E-B088-F1016F628C65}.Release|x64.Build.0 = Release|x64
		{7D62AF29-E32F-4402-88E5-D8FEEB062728}.Debug|ARM.ActiveCfg = Debug|ARM
		{7D62AF29-E32F-4402-88E5-D8FEEB062728}.Debug|ARM.Build.0 = Debug|ARM
		{7D62AF29-E32F-4402-88E5-D8FEEB062728}.Debug|x64.ActiveCfg = Debug|x64
		{7D62AF29-E32F-4402-88E5-D8FEEB062728}.Debug|x64.Build.0 = Debug|x64
		{7D62AF29-E32F-4402-88E5-D8FEEB062728}.Release|ARM.ActiveCfg = Release|ARM
		{7D62AF29-E32F-4402-88E5-D8FEEB062728}.Release|ARM.Build.0 = Release|ARM
		{7D62AF29-E32F-4402-88E5-D8FEEB062728}.Release|x64.ActiveCfg = Release|x64
		{7D62AF29-E32F-4402-88E5-D8FEEB062728}.Release|x64.Build.0 = Release|x64
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Debug|ARM.ActiveCfg = Debug|ARM
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Debug|ARM.Build.0 = Debug|ARM
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Debug|ARM.Deploy.0 = Debug|ARM
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Debug|x64.ActiveCfg = Debug|x64
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Debug|x64.Build.0 = Debug|x64
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Debug|x64.Deploy.0 = Debug|x64
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Release|ARM.ActiveCfg = Release|ARM
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Release|ARM.Build.0 = Release|ARM
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Release|ARM.Deploy.0 = Release|ARM
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Release|x64.ActiveCfg = Release|x64
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Release|x64.Build.0 = Release|x64
		{168437FF-BB72-4770-9F57-252AC94D4FCE}.Release|x64.Deploy.0 = Release|x64
		{5BC5B5AA-53F4-4437-95B3-261F790AE373}.Debug|ARM.ActiveCfg = Debug|ARM
		{5BC5B5AA-53F4-4437-95B3-261F790AE373}.Debug|ARM.Build.0 = Debug|ARM
		{5BC5B5AA-53F4-4437-95B3-261F790AE373}.Debug|x64.ActiveCfg = Debug|x64
		{5BC5B5AA-53F4-4437-95B3-261F790AE373}.Debug|x64.Build.0 = Debug|x64
		{5BC5B5AA-53F4-4437-95B3-261F790AE373}.Release|ARM.ActiveCfg = Release|ARM
		{5BC5B5AA-53F4-4437-95B3-261F790AE373}.Release|ARM.Build.0 = Release|ARM
		{5BC5B5AA-53F4-4437-95B3-261F790AE373}.Release|x64.ActiveCfg = Release|x64
		{5BC5B5AA-53F4-4437-95B3-261F790AE373}.Release|x64.Build.0 = Release|x64
		{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}.Debug|ARM.ActiveCfg = Debug|ARM
		{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}.Debug|ARM.Build.0 = Debug|ARM
		{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}.Debug|x64.ActiveCfg = Debug|x64
		{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}.Debug|x64.Build.0 = Debug|x64
		{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}.Release|ARM.ActiveCfg = Release|ARM
		{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}.Release|ARM.Build.0 = Release|ARM
		{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}.Release|x64.ActiveCfg = Release|x64
		{DB5F5AA6-13B4-458A-A6A9-E29238ADAE06}.Release|x64.Build.0 = Release|x64
		{62F0700F-394A-43DE-92FD-FCFE063069D3}.Debug|ARM.ActiveCfg = Debug|ARM
		{62F0700F-394A-43DE-92FD-FCFE063069D3}.Debug|ARM.Build.0 = Debug|ARM
		{62F0700F-394A-43DE-92FD-FCFE063069D3}.Debug|x64.ActiveCfg = Debug|x64
		{62F0700F-394A-43DE-92FD-FCFE063069D3}.Debug|x64.Build.0 = Debug|x64
		{62F0700F-394A-43DE-92FD-FCFE063069D3}.Release|ARM.ActiveCfg = Release|ARM
		{62F0700F-394A-43DE-92FD-FCFE063069D3}.Release|ARM.Build.0 = Release|ARM
		{62F0700F-394A-43DE-92FD-FCFE063069D3}.Release|x64.ActiveCfg = Release|x64
		{62F0700F-394A-43DE-92FD-FCFE063069D3}.Release|x64.Build.0 = Release|x64
		{57848D87-5F61-4150-B6DC-56A87AC0AEAE}.Debug|ARM.ActiveCfg = Debug|Any CPU
		{57848D87-5F61-4150-B6DC-56A87AC0AEAE}.Debug|ARM.Build.0 = Debug|Any CPU
		{57848D87-5F61-4150-B6DC-56A87AC0AEAE}.Debug|x64.ActiveCfg = Debug|x64
		{57848D87-5F61-4150-B6DC-56A87AC0AEAE}.Debug|x64.Build.0 = Debug|x64
		{57848D87-5F61-4150-B6DC-56A87AC0AEAE}.Release|ARM.ActiveCfg = Release|Any CPU
		{57848D87-5F61-4150-B6DC-56A87AC0AEAE}.Release|ARM.Build.0 = Release|Any CPU
		{57848D87-5F61-4150-B6DC-56A87AC0AEAE}.Release|x64.ActiveCfg = Release|x64
		{57848D87-5F61-4150-B6DC-56A87AC0AEAE}.Release|x64.Build.0 = Release|x64
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {1F958AF6-2FCD-45E8-A81F-456B7637E66E}
	EndGlobalSection
EndGlobal
```

**Comment by michael-hawker** [comment]
We were able to submit an update to our [Sample App](https://github.com/CommunityToolkit/WindowsCommunityToolkit/tree/main/Microsoft.Toolkit.Uwp.SampleApp) to the Microsoft Store using WinUI 2.7, not sure what the differences would be in the scenarios.

**Comment by yaichenbaum** [comment]
> We were able to submit an update to our [Sample App](https://github.com/CommunityToolkit/WindowsCommunityToolkit/tree/main/Microsoft.Toolkit.Uwp.SampleApp) to the Microsoft Store using WinUI 2.7, not sure what the differences would be in the scenarios.

@michael-hawker does the sample app have a full trust process?

**Comment by zhuxb711** [comment]
@michael-hawker I think this issue only on Windows Application Packaging Project which use fulltrustprocess, contains both .Net framework and UWP. Obviously, sample app is not.

**Comment by crramirez** [comment]
@michael-hawker I in fact published a UWP only (with Community Toolkit controls) with 2.7 without issues. 

But my other one is UWP + Desktop Extensions (.NET 5) once I upgrade the WinUI package from 2.5 to 2.6/7 it won't get certified in Microsoft Store. Also, notice that my app has x86_64 and ARM64 binaries.

**Comment by michael-hawker** [comment]
> @michael-hawker does the sample app have a full trust process?

Ah it does not. Sorry, I missed that this issue also involves a full trust component. 🙈

**Comment by crramirez** [comment]
This should be in the issue title btw

**Comment by zhuxb711** [comment]
@ranjeshj @StephenLPeters  Will this issue be fixed in 2.7.1?

**Comment by zhuxb711** [comment]
@StephenLPeters @ranjeshj @chingucoding Please do not ignore this issue. And we want to know whether WinUI Team found anything helpful. Thanks.

**Comment by zhuxb711** [comment]
@StephenLPeters @ranjeshj @chingucoding 

#### I got the log from .Net Native team. Hope this could help you investigate this issue. In short there is a conflicting reference to Microsoft.UI.Xaml.winmd

*****
Calling ilc.exe with arguments:
F:\\AppCompileSdk\\AppCompile\\2.2\\arm\\ilc\\ilc.exe /in:\"F:\\Data\\PkgProc\\CG1amsHrmkarh7dsINl3eQ\\AppCompileSourceDirectory\" /out:\"F:\\Data\\PkgProc\\CG1amsHrmkarh7dsINl3eQ\\ExtractedBundle\\Package_7.1.1.70_ARM\" /WindowsSdkApiXml:\"F:\\AppCompileSdk\\AppCompile\\SupportedAPIs-arm.xml\" /makePriPath:\"D:\\SvcFab\\_App\\PackageProcessingHostType_App44\\PackageProcessingHostPkg.Code.1.0.21270.1\\SDK\\MakePri.exe\" /rcPath:\"D:\\SvcFab\\_App\\PackageProcessingHostType_App44\\PackageProcessingHostPkg.Code.1.0.21270.1\\SDK\\Rc.exe\" /disableVSTel:true /AllowNoManagedCode /buildtype:ret /CscPath:F:\\AppCompileSdk\\AppCompile\\2.2\\csc\\csc.exe /disableGatekeeper /TargetPlatform:arm /exeName:\"RX_Explorer.exe\" /pdbPath:\"F:\\Data\\PkgProc\\CG1amsHrmkarh7dsINl3eQ\\AppCompileSymbolOut\" /RdXmlPath:\"F:\\AppCompileSdk\\AppCompile\\2.2\\LibraryXML\" /UseSharedAssemblies /InSharedAssemblyPath:\"F:\\AppCompileSdk\\AppCompile\\2.2\\SharedAssemblyArtifacts\\arm\" /targetplatformsdklibpath:\"F:\\AppCompileSdk\\AppCompileTargetPlatforms\\Vibranium\" /v:\"d\" /ExtraNutcArguments:\"/d2threads1\"
Output:
The command line argument /MakePriPath is not supported anymore, it will be ignored.
Build started 10/4/2021 8:25:32 AM.
__________________________________________________
Project \"Preparation\" (default targets):

Target CreateToolchainGeneratedAssembly:
Target ConstructPreMergeAssemblyClosure:
  Task \"PreMergeAssemblyClosure\"
  Done executing task \"PreMergeAssemblyClosure\".
Target PreResolveTransforms:
  Task \"McgReferenceResolveFilePath\"
  Done executing task \"McgReferenceResolveFilePath\".
Target ConstructILTransformAssemblyClosure:
  Task \"ResolveToolchainRequiredAssemblyRoots\"
  Done executing task \"ResolveToolchainRequiredAssemblyRoots\".
  Task \"ILTransformAssemblyClosure\"
  Done executing task \"ILTransformAssemblyClosure\".
  Task \"ResolveToolchainRequiredAssemblyRoots\"
  Done executing task \"ResolveToolchainRequiredAssemblyRoots\".
  Task \"ReducedCopyAssemblyClosure\"
    MSBUILD : error : ILT1307: Assemblies 'F:\\Data\\PkgProc\\CG1amsHrmkarh7dsINl3eQ\\AppCompileSourceDirectory\\Microsoft.UI.Xaml.winmd' and 'F:\\Data\\PkgProc\\CG1amsHrmkarh7dsINl3eQ\\AppCompileSourceDirectory\\WinMetadata\\Microsoft.UI.Xaml.winmd' have conflicting simple names.
  Done executing task \"ReducedCopyAssemblyClosure\" -- FAILED.
Done building target \"ConstructILTransformAssemblyClosure\" in file \"Preparation\" -- FAILED.

Done building project \"Preparation\" -- FAILED.

Compilation failed

The only difference in the files is the image base address:
![image](https://user-images.githubusercontent.com/42038175/135977756-24e15eb8-24db-474d-b92a-afb8fe2ef2f0.png)

**Comment by crramirez** [comment]
Thank you, @zhuxb711, for all the effort and time that you are dedicating to solve this.

**Comment by jupagose** [comment]
Same here, hope WinUi Team is taking care about this  ASAP, ARM is an important part of our installed customers.

**Comment by jevansaks** [comment]
Thanks @zhuxb711 for those details. @llongley made a change to remove the WinMetadata copy in https://github.com/microsoft/microsoft-ui-xaml/pull/5379, so I'm surprised to see the copy in the WinMetadata folder in the error output. @llongley can you take a look?

**Comment by gus33000** [comment]
Editing https://github.com/microsoft/microsoft-ui-xaml/blob/c8c76f032c9b44269eb00d5a6f2a54e3e961aca0/build/NuSpecs/MUXControls-Nuget-Common.targets#L27 in my case to the folliowing ```<TargetPath>Microsoft.UI.Xaml.winmd</TargetPath>``` solved the inclusion of the file in the arm64 package under WinMetadata while preserving it at the root of the package.

I have noticed this problem seems to only happen with ARM64 packages when using a Windows Application Packaging (WAP) project. In the past I had issues with WAP where my application would not produce a bundle package if my solution platform names included ```ARM64``` instead of ```arm64```. Making the platform name lowercase allowed me to produce arm64 bundles. Could this be related? It seemed at the time to be a case sensitive issue with some checks in msbuild targets. I can try to reproduce the issue again and providing a bit more logs about this but it isn't strictly WinUI related in this case.

**Comment by zhuxb711** [comment]
@gus33000 How to build a nuget package with the workaround you mention?

**Comment by zhuxb711** [comment]
@llongley So if that WinMetadata is not necessary, why something like '$(WinMetadataDir)' is still exists? 
https://github.com/microsoft/microsoft-ui-xaml/blob/c8c76f032c9b44269eb00d5a6f2a54e3e961aca0/build/NuSpecs/MUXControls-Nuget-Common.targets#L27

**Comment by zhuxb711** [comment]
> > @gus33000 How to build a nuget package with the workaround you mention?
> 
> 
> 
> @zhuxb711 You can edit locally the following file: ```"%userprofile%\.nuget\packages\microsoft.ui.xaml\2.8.0-prerelease.210927001\buildTransitive\Microsoft.UI.Xaml.targets"```
> 
> 
> 
> A note of caution, take backup of it, and consider that this is only a workaround to make msixupload creation not include the file, it may/will break other bundle types.

Very appreciate! That works for me.
@StephenLPeters @llongley Please fix this issue ASAP, thanks.

**Comment by crramirez** [comment]
@zhuxb711 Congrats!! 
![image](https://user-images.githubusercontent.com/8397379/136536725-9cbedac4-9f64-4e6b-97ab-de3a80998faf.png)

**Comment by gus33000** [comment]
Yeah I agree that if this got properly tested for every appx bundle case, at least the block to remove the file from WinMetadata needs to go, as it is now useless.

**Comment by michael-hawker** [comment]
FYI @StephenLPeters @llongley

**Comment by lhak** [comment]
Certification still fails with the latest stable release. Is there a release date for a stable version containing the fix?

**Comment by crramirez** [comment]
I can confirm that I've been using the 2.7.1 preview in production in the Microsoft Store without issues for about one month. For me it is a good candidate for release.

**Comment by gus33000** [comment]
Is there any news about this issue? It will soon be 4 months this bug affects all stable versions of the WinUI 2 nuget package. Probably a few people are still running into this, lack information about the latest prerelease fixing this (or are not able to use prerelease bits due to policy) or are most likely throwing away potential new arm64 native apps because of this issue impacting the state of the ARM64 platform.

**Comment by crramirez** [comment]
We are still running into this but we could use the prerelease version with the store, it is behaving well, so we kept going. Looking forward for the stable version

**Comment by StephenLPeters** [comment]
@crramirez @gus33000 check out the new 2.7.1 stable release patch, which includes this fix (as well as a couple others).

**Comment by crramirez** [comment]
> @crramirez @gus33000 check out the new 2.7.1 stable release patch, which includes this fix (as well as a couple others).

Hello @StephenLPeters ,

I have been working with the 2.7.1 prerelease without any problem. I'll test with the stable release and will back to you.

Thank you

**Comment by crramirez** [comment]
Hello @StephenLPeters,

Tested with 2.7.1 stable and everything is ok.

Regards,
Carlos

**Comment by gus33000** [comment]
> @crramirez @gus33000 check out the new 2.7.1 stable release patch, which includes this fix (as well as a couple others).

Hello, can also confirm it's fully fixed on my side! Thanks a lot!
