### ISSUE TITLE
NavigationView Top mode: ViewItem hover issue

### ISSUE THREAD

**Issue by steam3d** [microsoft/microsoft-ui-xaml#5770]
**Describe the bug**

NavigationViewItem doesn't have any visual style while hovering it. 

**Steps to reproduce the bug**

1. Open NavigationView page
2. Flow mouse on or around the NavigationViewItem
3.  There are no visual changes

**Expected behavior**

There should be animation on hover and "reveal style" when the mouse is near the element

**Actual behavior**

Nothing happens

**Screenshots**

https://user-images.githubusercontent.com/30986874/128595638-c610ff46-abef-46cd-b0f3-536bd1510740.mp4

**Version Info**
- [x] App downloaded from Store 
    - v1.2.20.0
- [ ] App built locally from source 
  - If so, which branch? (WinUI 3 versions are built off the winui3 branch)

**Additional context**

Windows version:
- [ ] Insider Build (xxxxx)
- [x] May 2021 Update (19043)
- [ ] October 2020 Update (19042)
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by gabrielconl** [comment]
Reveal is now deprecated, but I agree that there should be a hover visual, since all other menus have that.

**Comment by StephenLPeters** [comment]
The selected item does have pointer over foreground color changes, but the unselected items do not... likely the resource is pointing at the wrong color.. @karenbtlai FYI

**Comment by steam3d** [comment]
Issue still exist

**Comment by MiroKaku** [comment]
Issue still exist

**Comment by DmitriyKomin** [comment]
This issue has been fixed in WinAppSDK. Please install the latest WinUI 3 Gallery from the store to see the behavior.

**Comment by kmahone** [comment]
Thanks Dmitriy.
