### ISSUE TITLE
Should avoid triggering CI builds and checks for docs changes

### ISSUE THREAD

**Issue by jesbis** [microsoft/microsoft-ui-xaml#578]
**Describe the bug**  
Currently the Azure build pipeline and GitHub check suite run for all changes, including docs.  
This seems like an unnecessary use of time and resources.

The Azure build pipeline should support excluding paths/files:  
https://docs.microsoft.com/azure/devops/pipelines/build/triggers?tabs=yaml#pull-request-validation

Would need to verify this also skips auto-triggering the GitHub check suite. Or at worst we could see if the [`skip-checks`](https://help.github.com/en/articles/about-status-checks) flag on commits works with the repo CI setup.

I think we could exclude at least:

```
exclude:
  - docs/*
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - README.md
```

**Comment by jevansaks** [comment]
Interesting, we'll see if skipping the trigger on the PR build would fix this.

**Comment by jevansaks** [comment]
I tried excluding the folder and, indeed, the PR build no longer triggers. Unfortunately the CI check is blocked:
![image](https://user-images.githubusercontent.com/20667023/56385203-53986200-61d3-11e9-90b6-a6b6bd0dd353.png)

So we'll have to do something more fancy in the yaml pipeline itself to skip the build and quickly report back a check.
