### ISSUE TITLE
Question: How to clear WebView2 cache in AppSDK

### ISSUE THREAD

**Issue by DarrylDreiling-Sphero** [microsoft/microsoft-ui-xaml#5783]
We are using WebView2 in our AppSDK 0.8.2 app.  We have some flows in our app that use WebView2 for authentication stuff.  I would like to be able to clear cache at some point after auth completes.  But from what I have seen none of the API's or approaches to do this seems to be available to WinUI 3 applications.  So how can I do this in WinUI 3?

**Comment by codendone** [comment]
I think there will likely be a more convenient API added in the future, but currently you can do this via the DevToolsProtocol:
```
myWebView2.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.clearBrowserCache", "{}");
```

**Comment by codendone** [comment]
I'm glad that worked for you. Given that, I'm closing this question with my answer above.
