### ISSUE TITLE
WinUI 2: CommandBarFlyout does not allow keyboard navigation the second time it is opened

### ISSUE THREAD

**Issue by lyahdav** [microsoft/microsoft-ui-xaml#5785]
**Describe the bug**

WinUI 2 CommandBarFlyout does not allow keyboard navigation the second time it is opened.

**Steps to reproduce the bug**

1. Open this solution: https://github.com/lyahdav/XamlPlayground/tree/text-block-context-menu
2. Run the UwpXamlApp project in that solution
3. Select text in "TextBlock with bug"
4. Right click
5. Use up/down arrow keys to navigate CommandBarFlyout
6. Click away to hide CommandBarFlyout
7. Select text again
8. Right click again
9. Use up/down arrow keys to navigate CommandBarFlyout

**Expected behavior**
Expected: CommandBarFlyout's AppBarButtons get focused and show focus border.
Actual: No focus happens.

**Screenshots**
Here's a video of the issue and a workaround:

https://user-images.githubusercontent.com/359157/131182493-93bfaa1f-0a1e-46cb-92d0-df2775f114e0.mov

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml.2.7.0-prerelease.210816001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
The offending code can be summarized as:
```
		TextBlock tbl;
		mux::TextCommandBarFlyout cbf;
		tbl.SelectionFlyout(cbf);
		tbl.ContextFlyout(cbf);
		tbl.Text(text);
		tbl.IsTextSelectionEnabled(true);
		xamlContainer.Children().Append(tbl);
```

The workaround is to recreate the CommandBarFlyout on close:
```
			cbf.Closed([=](auto&&...) {
				mux::TextCommandBarFlyout newCbf;
				tbl.SelectionFlyout(newCbf);
				tbl.ContextFlyout(newCbf);
				});
```

**Comment by lyahdav** [comment]
I'm also able to repro this in MUXControlsTestApp on a TextBox with a TextCommandBarFlyout, but only when the menu doesn't have a proofing submenu:

https://user-images.githubusercontent.com/359157/131197209-21d05f8d-665d-4705-8c6e-fe07199d9e7f.mov

**Comment by lyahdav** [comment]
I'm also able to repro this in MUXControlsTestApp on CommandBarFlyout that's unrelated to TextCommandBarFlyout:

https://user-images.githubusercontent.com/359157/131197505-586ab91d-0ea2-4853-86c9-97d65a71b62f.mov

**Comment by StephenLPeters** [comment]
@llongley this sounds similar to a bug you looked into earlier this year, thoughts?

**Comment by lyahdav** [comment]
Likely still relevant

**Comment by DmitriyKomin** [comment]
@lyahdav, thank you for reporting this. Unfortunately we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)). From a quick look, this does not appear to repro in WinAppSDK 1.5. If you see the issue in latest WinAppSDK, please comment here and we will investigate.
