### ISSUE TITLE
WebView2 in WinUI2 support for xaml islands scenarios

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#5787]
**Describe the bug**

WebView2 control in WinUI2 currently lacks proper xaml islands support.
Workarounds include using the CoreWebView2 hwnd-based control directly, but this doesn't play well with input, accessibility, doesn't allow embedding deeper into a xaml tree than at the layer of the DWXS, etc.

**Comment by zadjii-msft** [comment]
@ranjeshj Hey qq - did this actually get done in 2.8? I have a hackathon project rattling around in my brain that would need a `WebView`, but I'm obviously stuck on 2.x for the time being 😄

**Comment by kmahone** [comment]
This is a known limitation for WebView2 in WinUI2 and it is not something that we will be able to address for 2.8.

**Comment by lyahdav** [comment]
Was this fixed recently? I just tried WinUI 2 version 2.8.2-prerelease.220830001 and I got WebView2 working in Xaml Islands (this is in the [React Native Windows playground win32 app](https://github.com/microsoft/react-native-windows/blob/main/packages/playground/windows/playground-win32.sln)):

https://user-images.githubusercontent.com/359157/202327305-c456fc0d-2193-4117-a7ea-863978aec04a.mov

**Comment by lyahdav** [comment]
Perhaps it was this recent commit by @brianostms that fixed it: https://github.com/microsoft/microsoft-ui-xaml/commit/494719e5b839e786e022a72a4eb04d7ae8595c1f

**Comment by zadjii-msft** [comment]
Yea I dunno when it happened, but `WebView2` absolutely works in WinUI2 + Xaml Islands now.

This is a demo scratch app with `Microsoft.Web.WebView2.1.0.1661.34` and `Microsoft.UI.Xaml.2.8.3`.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/18356694/2c5b7102-b4a2-4aa8-9992-de444633d822)

Here's the commit: https://github.com/microsoft/terminal/commit/497fea8d97b7b8507ed6fbfc15dcc314a028fad4

The interesting code is just a button click handler:

```c++
winrt::MUX::Controls::WebView2 wv{ nullptr };
wv = winrt::MUX::Controls::WebView2();
wv.HorizontalAlignment(WUX::HorizontalAlignment::Stretch);
wv.Height(300);
MyStackPanel().Children().Append(wv);
co_await wv.EnsureCoreWebView2Async();
wv.CoreWebView2().Navigate(L"https://www.bing.com");
```

Here it is in the visual tree:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/18356694/1f03ae52-ab58-4b17-9770-58e9aa22868f)


A11y Insights is broken on this scratch app (for unrelated reasons), but Narrator seems to work well enough, as does input and output. 

So, I think this can be closed?

**Comment by DmitriyKomin** [comment]
@lyahdav , @zadjii-msft - thank you for letting us know about the good news :-) I am not sure what change(s) contributed to the improved behavior, but agree that, in the interest of time, it makes sense to close now.
