### ISSUE TITLE
Announcing WebView2 in WinUI2.7 pre-release

### ISSUE THREAD

**Issue by predavid** [microsoft/microsoft-ui-xaml#5789]
**Announcing the the release of WebView2 in the pre-release version of WinUI2.7**
Many of you in the community requested that we make WebView2 available in UWP apps for your PC -based scenarios. We have heard your request. We are introducing WebView2 in the pre-release of WinUI2.7 today. 
Functionality-wise, there isn’t any change from the [WebView2 API spec](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fmicrosoft-ui-xaml-specs%2Fblob%2Fmaster%2Factive%2FWebView2%2FWebView2_spec.md&data=04%7C01%7Cpredavid%40microsoft.com%7Cb2e010fa2d88477c278008d9685104e4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637655519476793141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kaKTdh3GUf5dLRkXIZM6rHtrGZQvb7pBTxuYCbFJVdQ%3D&reserved=0)  that you may have reviewed last year when WebView2 was released in a very early preview of WinUI3. 

**Installation information**
For installation information and known issues see [here](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.7.0-prerelease.210827001) 

**What's next?**
We will be working on addressing the issues/bugs you file and getting WebView2 ready for release in upcoming stable(non-pre-release)versions of WinUI2.x

**Comment by asklar** [comment]
@jevansa @predavid It looks like cppwinrt apps hit an issue when using the new nuget: #5793

**Comment by tipa** [comment]
It's great to hear that WebView2 makes it to WinUI2. I am just starting to see growing need for it in my apps.
Unfortunately, submitting an app using the 2.7 preview fails in the Store certification: 
```
API GetCurrentProcessExplicitAppUserModelID in shell32.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API GetFileVersionInfoSizeW in version.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API GetCurrentProcessExplicitAppUserModelID in shell32.dll is not supported for this application type. WebView2Loader.dll calls this API.
API GetFileVersionInfoSizeW in version.dll is not supported for this application type. WebView2Loader.dll calls this API.
```
Let me know if I should open a separate issue for this.

**Comment by albertomandlate** [comment]
And now you removed it.

**Comment by antonioberetini** [comment]
Would this backport enable us to use Mica Material in WebView apps? We started our project with WinUI 3 and are now stuck until Mica Material is supported in WinUI 3. Its super frustrating since our app design i built around Mica.
