### ISSUE TITLE
There shouldn't be an build error for libraries targeting AnyCPU or below the version version.

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/microsoft-ui-xaml#579]
**Describe the bug**
I can't use this library from another library that references AnyCPU.
There's no reason why this library can't be used by an AnyCPU library, except you have a build task preventing me from doing that.
You also require MinVersion and Version to be 14393 and 17763, which again shouldn't matter for class libraries.

**Steps to reproduce the bug**
1. Create an AnyCPU class library.
2. Reference this package.
3. Build

**Expected behavior**
Build completes.

**Screenshots**
![image](https://user-images.githubusercontent.com/1378165/56379593-ea115700-61c4-11e9-9ae1-479241207d69.png)

**Version Info**
Win10, 1809, VS2019.

NuGet package version: 
2.1.190405004

**Additional context**
The build error is valid for app-heads, but not class libraries.

I also believe a similar check be done to the `MicrosoftUIXamlCheckTargetPlatformVersion` Target, which shouldn't run on class libraries, but only app-heads.
Also to ensure these build files gets run on on app-heads when indirectly references, the entire `\build\` folder should be duplicated to the `transitiveBuild` folder.

**Comment by jevansaks** [comment]
I was under the impression that if your package contained native dlls then the whole app needs to be compiled as native per-platform. Maybe this has changed?

If there's a doc explaining how to do this, we'd be happy to support it. Have you seen a project that has been able to make this work?

Also note that your error is about the **VCLibs** dependency, not Microsoft.UI.Xaml.

**Comment by dotMorten** [comment]
> I was under the impression that if your package contained native dlls then the whole app needs to be compiled as native per-platform

Yes but I'm not compiling an app, but just a class library.

**Comment by dotMorten** [comment]
> If there's a doc explaining how to do this, we'd be happy to support it. Have you seen a project that has been able to make this work?

Yes. I work on the ArcGIS Runtime SDK for .NET. It does this and works just fine. https://www.nuget.org/packages/Esri.ArcGISRuntime.UWP/

**Comment by dotMorten** [comment]
Avoiding vclibs reference:
```xml
  <ItemGroup Condition="'$(ProjectExt)' != '.vcxproj' and ('$(PlatformTarget)' == 'x86' or '$(PlatformTarget)' == 'x64' or '$(PlatformTarget)' == 'ARM' or '$(PlatformTarget)' == 'ARM64')">
     <SDKReference Include="Microsoft.VCLibs, Version=14.0" />
  </ItemGroup>
```

**Comment by dotMorten** [comment]
I noticed there's `SkipMicrosoftUIXamlCheckTargetPlatformVersion` I can use to at least turn the version check off. That'll do for that bit

**Comment by jevansaks** [comment]
You should also be able to have your component library build against the previous 2.1 -prerelease package which doesn't force in the SDKReference dependency like this. The APIs are the same so your component would be compatible. I think that would unblock you for now.

But I'm taking a look into making this change.

**Comment by dotMorten** [comment]
@jevansaks I've submitted a PR for review

**Comment by jevansaks** [comment]
> You also require MinVersion and Version to be 14393 and 17763, which again shouldn't matter for class libraries.

I missed this in the initial report. The 17763 target version dependency is required because you need to compile against a new enough Windows SDK in order for the metadata references in the MUX package's winmd to be resolved. If it's too old you'll get weird compiler errors about type references.

For the MinVersion check: I still kind of like having it because I'd like you to know that our project needs a particular min version in case you're trying to promise something more than we can offer. Is it tripping because the MinVersion in your component is unset, perhaps? I can set up a repro project to investigate.

**Comment by dotMorten** [comment]
Setting `SkipMicrosoftUIXamlCheckTargetPlatformVersion` works for me. I can continue targeting 16299.
I don't think this check really applies for a class library. The specific underlying APIs are needed until runtime.
