### ISSUE TITLE
WinUI Design Toolkit Bug: Frame names on the Controls page could use work

### ISSUE THREAD

**Issue by Wolfr** [microsoft/microsoft-ui-xaml#5795]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Top level frames on the “Controls”  page of 2.6

**Describe the bug:**
The artboards could have better names. For example, the Button artboard is called “Basic input”. The names can be improved on the first 14 top level frames.

Screenshot:
![CleanShot 2021-08-30 at 13 31 51@2x](https://user-images.githubusercontent.com/12690/131332856-db77d1d7-1747-4c36-bf67-dc1f3598f414.png)

**Version Info:**
2.6, duplicated Monday August 30.

**Comment by alejo4000** [comment]
Hi Wolfr, the artboards are named this way to help in the hierarchy in choosing controls in the asset library and in the asset instance switcher dialog.

**Comment by Wolfr** [comment]
Good to know this is intentional! I learned something new. Thank you.
