### ISSUE TITLE
WinUI Design Toolkit Bug: ComboBox is called Dropdown - inconsistency between design file and design docs website

### ISSUE THREAD

**Issue by Wolfr** [microsoft/microsoft-ui-xaml#5796]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Dropdown (listed under “Controls”)

**Describe the bug:**
The development documentation talks about ComboBox, whereas here the control is documented as “Dropdown” on the design docs.
https://docs.microsoft.com/en-us/windows/apps/design/controls/combo-box

<img width="1038" alt="CleanShot 2021-08-30 at 13 35 08@2x" src="https://user-images.githubusercontent.com/12690/131333146-a9aa2431-e60d-4b9c-b01d-2e0aee5bafd1.png">

There is also the problem with the artboard mentioned in #5795.

**Version Info:**
2.6 duplicated August 30.

**Comment by alejo4000** [comment]
@Wolfr I'm looking at the links provided in the toolkit, everything appears to be linking to the intended locations. Can you clarify which links you believe are incorrect or not directing to the correct information?

**Comment by Wolfr** [comment]
The issue is about the naming inconsistency between “Dropdown” and “ComboBox”. If the dev documentation calls it a “ComboBox” imo the design docs should do so as well (or the other way around).

**Comment by alejo4000** [comment]
The combobox link directs to a design document, whereas the dropdown links to a dev doc, as the dropdown button design documentation is located in the Button section, [located here.](https://docs.microsoft.com/en-us/windows/apps/design/controls/buttons#create-a-drop-down-button). We're currently re-evaluating this link in the documentation for these two controls, so thanks for bringing this to our attention!
