### ISSUE TITLE
Informational InfoBar background should not be transparent

### ISSUE THREAD

**Issue by tipa** [microsoft/microsoft-ui-xaml#5797]
**Describe the bug**

Using a `InfoBar` with Severity `Informational` uses an (almost) transparent background.
This causes visual/readability issues when the InfoBar is used in a screen with a non-solid color or color that differs from the default background color. In my case, I want to use the `InfoBar` on a screen with a full-screen `MapView`.
https://github.com/microsoft/microsoft-ui-xaml/blob/ee89dc1c0dc8027af11ac71289af7895d2619e1f/dev/InfoBar/InfoBar_themeresources.xaml#L14
https://github.com/microsoft/microsoft-ui-xaml/blob/5673d0ca4b6b0e4645637bbab37f48f4825baec3/dev/CommonStyles/Common_themeresources_any.xaml#L207
https://github.com/microsoft/microsoft-ui-xaml/blob/5673d0ca4b6b0e4645637bbab37f48f4825baec3/dev/CommonStyles/Common_themeresources_any.xaml#L100

**Expected behavior**
The `informational` should have a solid background color (similar to the background colors of the other severities.
It could be dark-gray for Dark Theme and light-grey for Light Theme

**Version Info**
Microsoft.UI.Xaml 2.6.2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by niels9001** [comment]
Related to: #5741

Great input and feedback you have - I think these issues can be merged because it has the same ask :)

**Comment by tipa** [comment]
I agree, I will close this issue in favor of yours and will add my comments there
