### ISSUE TITLE
NavigationView TopNav layout issue when using MenuItemTemplate with NavigationViewItem as root element

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#5798]
**Describe the bug**

When using NavigationView in top mode, with a MenuItemTemplate that has a NavigationViewItem as the root element, menu items appear to "snap" into place as the window expands and items are moved from the overflow repeater to the main repeater.

This issue does not repro when the template does not use a NavigationViewItem as the root, due to the difference in element recycling behaviors in NavigationView.

**Steps to reproduce the bug**

1. Open attached TopNavTestApp solution
2. Build and run
3. Resize the app window to the smallest width
4. Gradually resize the window to wider widths and observe the behaviors of the menu items as they appear

**Expected behavior**
There should be no difference whether the MenuItemTemplate uses a NavigationViewItem as the root or not.

**Screenshots**

Screenshot taken from a modified version of the MUXControlsTestApp to demonstrate the behavior:
![image](https://user-images.githubusercontent.com/45607479/131373116-e9ef57ed-e5ff-4671-9e97-132ad28ab0a2.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.7.0-prerelease.210827001
Microsoft.UI.Xaml 2.6.2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

[TopNavTestApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7078149/TopNavTestApp.zip)

**Comment by StephenLPeters** [comment]
@ojhad does this ring any bells?
