### ISSUE TITLE
Drag and drop visual has an outdated design

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#5799]
You might have seen this little visual when you drag something over another surface. I think it looked like this since Windows 10 was released, so it could use an update. Since it's very similar to a tooltip, it could use the same design.

![image](https://user-images.githubusercontent.com/84711285/131385059-dddbb200-ef2d-4e78-ac20-ee46e68ee3fe.png)
![image](https://user-images.githubusercontent.com/84711285/131399746-7dab4c1a-21a2-43ed-8f74-db6687c038e0.png)

**Comment by Jaiganeshkumaran** [comment]
This is part of the system and not WinUI specifically.
