### ISSUE TITLE
Error sideloading UWP application using Microsoft.UI.Xaml 2.0.181018003

### ISSUE THREAD

**Issue by tedrog36** [Microsoft/microsoft-ui-xaml#58]
**Describe the bug**
I just updated Microsoft.UI.Xaml to latest version and now I cannot install/side-load my application running the Powershell script created by Visual Studio.  I get the following error:

**Deployment of package Microsoft.UI.Xaml.2.0_2.1810.18003.0_x64__8wekyb3d8bbwe was blocked because the provided package has the same identity as an already-installed package but the contents are different. Increment the version number of the package to be installed, or remove the old package for every user on the system before installing this package.**

When I list installed packages it is definitely installed but I can't remove it because it is used by other windows applications.  Is there a problem with the versioning of this package?

**Windows cannot remove framework Microsoft.UI.Xaml.2.0_2.1810.18003.0_x64__8wekyb3d8bbwe because package(s)
Microsoft.XAMLControlsGallery Microsoft.WindowsCalculator Microsoft.WindowsAlarms currently depends on the framework**

**Steps to reproduce the bug**
1. Update Microsoft.UI.Xaml to latest version
2. Run Powershell script created by Visual studio to install the app
3.. Get error described above

**Expected behavior**
App should be installed and handle the fact that a referenced package is already installed.

**Screenshots**

**Version Info**
Microsoft.UI.Xaml.2.0_2.1810.18003.0_x64__8wekyb3d8bbwe

Windows 10 version:
- April 2018 Update (17134)

Device form factor:
- Desktop

**Additional context**

**Comment by jevansaks** [comment]
I asked around and it sounds like the store may have re-signed the framework package during submission so what came down with the installed apps from the store may in fact be different from what's in the nuget package. I will investigate further.

To unblock yourself you can use the prerelease version of the package for development for now.

**Comment by tedrog36** [comment]
yeah, I rolled back to a previous version to unblock.

**Comment by jevansaks** [comment]
FWIW the 2.1 prerelease would also work (and get you more recent bug fixes).

**Comment by jevansaks** [comment]
I just published a [nuget package](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.0.181018003.1) which should have this resolved. I was able to repro the issue locally and with this package I can now produce packages that successfully sideload.

Please try version 2.0.181018003.1 from nuget.org.
