### ISSUE TITLE
Is It Possible to change on TextBox Focus Bottom Border Blue color?

### ISSUE THREAD

**Issue by sangitamalviya** [microsoft/microsoft-ui-xaml#5802]
NuGet package version: 
[Microsoft.UI.Xaml 2.6.2]
![TextBoxFocusIssue](https://user-images.githubusercontent.com/53295795/131472660-3bb27451-bf05-4c37-91e7-42822b7ceffa.PNG)

**Comment by StephenLPeters** [comment]
Yeah, its the accent color, so the user could change their accent color, or you could override the accent color brushes in your app to point at a different color than the system provided one, or you could change the text box template to point the stroke fill at a different resource.

**Comment by sangitamalviya** [comment]
hi, @StephenLPeters thanks for reply I have tried with set "SystemAccentColor" key .but doesn't reflect with winui2 .when tryed with normal Uwp Project without [Microsoft.UI.Xaml 2.6.2] package it change TextBox BorderColor.
code:-
` <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Default">
                    <Color x:Key="SystemAccentColor">OrangeRed</Color>
                </ResourceDictionary>
                <ResourceDictionary x:Key="Dark">
                    <Color x:Key="SystemAccentColor">DeepPink</Color>
                </ResourceDictionary>
                <ResourceDictionary x:Key="Light">
                    <Color x:Key="SystemAccentColor">OrangeRed</Color>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>`

**Comment by StephenLPeters** [comment]
You'll need to override the https://github.com/microsoft/microsoft-ui-xaml/blob/1f2d163b4e9639fff0e86216387baf2f2c0f2cb7/dev/CommonStyles/TextBox_themeresources.xaml#L38 resource to change that color
