### ISSUE TITLE
Closing an app that's not in focus breaks the Mica material

### ISSUE THREAD

**Issue by bzzrak** [microsoft/microsoft-ui-xaml#5810]
**Describe the bug**
If you have an app that uses Mica in the foreground and close an app that's visible but not in focus, the mica effect will break.

**Steps to reproduce the bug**
1. open app that uses mica (e.g. windows 11 calculator, settings, Files UWP)

2. open some other app (e.g. edge)

3. set focus to the mica app but so that the other app is visible (make the mica app windowed)

4. close or minimise the other app

5. the focus will be back on the mica app but without the transparency.

**Expected behavior**
The focus is back on the app that uses Mica and the transparency effect works.

**Screenshots**
https://imgur.com/a/Cd13vnK

**Version Info**
App type is UWP, OS version is Windows 11 22000.168, WinUI version is 2.6 I assume.

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by fitojb** [comment]
Mica is not a transparency effect, unlike Acrylic.

It just samples the _wallpaper_ for its coloring, not the background immediately behind an app.

So it’s working as intended.

**Comment by StephenLPeters** [comment]
@jevansaks FYI
