### ISSUE TITLE
Incorrect generation of XamlTypeInfo.g.cs with obsolete properties

### ISSUE THREAD

**Issue by brinko99** [microsoft/microsoft-ui-xaml#5812]
When referencing a NuGet package that includes obsolete properties, the generated file `XamlTypeInfo.g.cs` produces error `CS0619`.

e.g.
`XamlTypeInfo.g.cs(744,20,744,32): error CS0619: 'LogEventInfo.Context' is obsolete: 'Use LogEventInfo.Properties instead.  Marked obsolete on NLog 2.0'`

**Steps to reproduce the bug**

(See the enclosed solution)

From a fresh WinUI3 blank application project, include the latest package of NLog. Add the following property to `MainWindow.xaml.cs`:

`public List<LogEventInfo> LogEvents { get; } = new List<LogEventInfo> { new LogEventInfo(), };`

Upon build, the above-mentioned compile error is generated.

`XamlTypeInfo.g.cs` includes the below code causing the error. It appears that the wrong warning is disabled. The file disables 0618, but 0619 is what is produced.

```
#pragma warning disable 0618  //   Warning on Deprecated usage
        private object get_24_LogEventInfo_Context(object instance)
        {
            var that = (global::NLog.LogEventInfo)instance;
            return that.Context;
        }
#pragma warning restore 0618
```

**Expected behavior**
Clean build.

**Version Info**

NuGet package version:  Microsoft.ProjectReunion.WinUI 0.8.2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

[WinUI3_Repo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7086919/WinUI3_Repo.zip)

**Comment by StephenLPeters** [comment]
@codendone FYI
