### ISSUE TITLE
Question: how to handle `WM_HOTKEY`  message?

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#5815]
I wan't to call `RegisterHotKey` to reigster global hotkey, but i don't know how to handle `WM_HOTKEY` in winui3, 
where is windows message loop ?

**Comment by StephenLPeters** [comment]
@MikeHillberg @codendone FYI

**Comment by codendone** [comment]
You can use the HWND version of `RegisterHotKey`, such as this partial code:

```
    MainWindow::MainWindow()
    {
        InitializeComponent();

        WNDCLASSEX wndClass = {};
        wndClass.cbSize = sizeof(wndClass);
        wndClass.lpfnWndProc = HotKeyWndProc;
        wndClass.hInstance = ::GetModuleHandle(nullptr);
        wndClass.lpszClassName = L"HotKeyWindow";

        auto msgWindowClass = ::RegisterClassEx(&wndClass);
        winrt::check_bool(msgWindowClass != 0);

        m_hwndHotkey = ::CreateWindow(wndClass.lpszClassName, nullptr, 0, 0, 0, 0, 0, HWND_MESSAGE, nullptr, wndClass.hInstance, this);
        winrt::check_pointer(m_hwndHotkey);

        const int IDH_MYHOTKEY = 0x20; // define this on your class or somewhere more broad
        if (!::RegisterHotKey(m_hwndHotkey, IDH_MYHOTKEY, MOD_CONTROL | MOD_SHIFT, 'A'))
        {
            winrt::throw_last_error();
        }
    }

    LRESULT CALLBACK MainWindow::HotKeyWndProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
    {
        if (uMsg == WM_HOTKEY)
        {
            // check for IDH_MYHOTKEY and other variables if registering for multiple hotkeys
            OutputDebugString(L"HotKey received\n");
        }
        return ::DefWindowProc(hwnd, uMsg, wParam, lParam);
    }
```

**Comment by shelllet** [comment]
> RegisterHotKey

thx, i will try this later. if so, i remeber that win32 hook api should aslo be possible ,this can use the existing main window `hwnd`

**Comment by akilarajesh1313** [comment]
@shelllet Feel free to let us know if you have any further questions on this!

**Comment by tom-huntington** [comment]
> m_hwndHotkey = ::CreateWindow(wndClass.lpszClassName, nullptr, 0, 0, 0, 0, 0, HWND_MESSAGE, nullptr, wndClass.hInstance, this);

So you're not hooking the WinUI3 window's message loop, you're just creating an additional (invisible) window. Hmmm.

Actually maybe this is sub-classing. Better just copy paste.

**Comment by castorix** [comment]
> > m_hwndHotkey = ::CreateWindow(wndClass.lpszClassName, nullptr, 0, 0, 0, 0, 0, HWND_MESSAGE, nullptr, wndClass.hInstance, this);
> 
> So you're not hooking the WinUI3 window's message loop, you're just creating an additional (invisible) window. Hmmm.
> 
> Actually maybe this is sub-classing. Better just copy paste.

I had posted a sample in C#, using standard subclassing : https://github.com/castorix/WinUI3_DesktopDuplication/blob/master/MainWindow.xaml.cs
