### ISSUE TITLE
First time clicking on Cut, Copy, Paste, Undo, or Select All menu items from TextCommandBarFlyout of a TextBox/TextBlock/PasswordBox makes the control lose focus

### ISSUE THREAD

**Issue by lyahdav** [microsoft/microsoft-ui-xaml#5818]
**Describe the bug**

See title.

**Steps to reproduce the bug**

1. Run [XAML Controls Gallery](https://github.com/microsoft/Xaml-Controls-Gallery) app
2. Go to TextBox example
3. Type "test" in a TextBox
4. Right click TextBox
5. Click "Select All"

**Expected behavior**
Expected: "test" text in TextBox shows up as selected
Actual: "test" text is selected but it doesn't show as selected (Blue background) because the TextBox isn't focused. Subsequent clicks on "Select All" will correctly keep the TextBox focused.

**Screenshots**
Here's a video of the steps above showing the bug and how it works correctly the second time:

https://user-images.githubusercontent.com/359157/131725824-c236050d-b94b-4cbc-a359-9d340a2a4fce.mov

**Version Info**
I'm on version 1.2.20.0 of XAML Controls Gallery.

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |  Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I also confirmed this issue happens when using TextCommandBarFlyout from WinUI version 2.7.0-prerelease.210816001 in a simple UWP app. Here's an example project demonstrating that: https://github.com/lyahdav/XamlPlayground/tree/text-box-with-win-ui-2-cbf

**Comment by lyahdav** [comment]
I also confirmed this bug happens on other controls that use TextCommandBarFlyout, e.g. TextBlock, RichTextBlock, PasswordBox. RichEditBox does not have the bug.
 
One workaround I found is to add:
```
    if (auto control = target.try_as<winrt::Control>())
    {
        control.Focus(winrt::FocusState::Programmatic);
    }
```
before https://github.com/microsoft/microsoft-ui-xaml/blob/4be817e1c3b394d4dba5ce8aa521cfc4e4c6e4f8/dev/CommandBarFlyout/TextCommandBarFlyout.cpp#L925

**Comment by lyahdav** [comment]
Another workaround if you don't want to touch WinUI 2 code is in your app's code to hook into the TextCommandBarFlyout's Opening event and run this:
```
  if (auto commandBarFlyout = sender.try_as<winrt::Microsoft::UI::Xaml::Controls::CommandBarFlyout>()) {
    auto commands = commandBarFlyout.SecondaryCommands();
    for (auto i = 0; i < commands.Size(); ++i) {
      if (const auto appBarButton = commands.GetAt(i).try_as<xaml::Controls::AppBarButton>()) {
        if (!appBarButton.Flyout()) {
          appBarButton.Click([weakCommandBarFlyout = winrt::make_weak(commandBarFlyout)](auto &&...){
            if (auto flyout = weakCommandBarFlyout.get()) {
              if (auto control = flyout.Target().try_as<xaml::Controls::Control>()) {
                control.Focus(xaml::FocusState::Programmatic);
              }
            }
          });
        }
      }
    }
  }
```

**Comment by lyahdav** [comment]
I found a related bug which I think is the same root cause: The first time you right click on a TextBox, if you hit escape, the TextBox doesn't get focused. If you try again it will get focused.

**Comment by StephenLPeters** [comment]
@llongley Do you know whats going on here? Sounds vaguely familiar.

**Comment by DmitriyKomin** [comment]
@lyahdav, thank you for reporting. Unfortunately at this time we are not able to investigate WinUI2-specific issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).

I tried this out in WinUI3 Gallery and it does not repro there.
