### ISSUE TITLE
Flyouts have a hardcoded margin

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#5819]
**Describe the bug**
Flyouts will have a hardcoded 4px margin from the element they appear, which will remain when setting a custom one.

**Steps to reproduce the bug**
```
<Button Content="Button">
    <Button.Flyout>
        <Flyout>
            <Flyout.FlyoutPresenterStyle>
                <Style TargetType="FlyoutPresenter">
                    <Setter Property="Margin" Value="0" />
                </Style>
            </Flyout.FlyoutPresenterStyle>
            <TextBlock>Flyout</TextBlock>
        </Flyout>
    </Button.Flyout>
</Button>
```

**Expected behavior**
The flyout default margin would be changed.

**Screenshots**
When using Margin=0:
![image](https://user-images.githubusercontent.com/84711285/131729081-156744d5-95e4-45f1-a16b-8289c3ff4bcc.png)

When using Margin=4:
![image](https://user-images.githubusercontent.com/84711285/131729140-c5c2782a-d1a2-4644-a2ce-cd9f7bedbaf0.png)

**Version Info**
WinUI 2.6.2
UWP system Xaml

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2021 Update (19043)            | Yes   |

**Additional context**
There are some situations in which it is needed to have an exact spacing around a flyout. They will also act pretty weird when appearing above a control, because they're still anchored to the top.

**Comment by StephenLPeters** [comment]
its not that they have a margin, its that the default placement is not directly adjacent to the contianing element. If you want to move the flyout closer you can use a negative margin or some of the other placement API's https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.primitives.flyoutshowoptions?view=winui-3.0

**Comment by dansmor7** [comment]
I think it would make more sense that the exact spacing would be given by a customizable with a margin, rather than it being a hardcoded value. It is often overwritten by using a -4px margin.
The placement apis are useful, but would it be possible to fix this in WinUI 2?
