### ISSUE TITLE
Flyout menus render rounded corners incorrectly

### ISSUE THREAD

**Issue by torquerrr** [microsoft/microsoft-ui-xaml#5826]
**Describe the bug**

When any "modern" flyout menu is drawn its rounded corners are rendered with a noticeable lag:
1. The rectangle is drawn
2. Rectangle's corners are being rounded

**Steps to reproduce the bug**

1. Open any "modern" app (Photos, To-Do, Terminal, ...)
2. Invoke any context menu

**Expected behavior**

Rounded corners are drawn without any artifacts/lag.

**Screenshots**

![HeDB8rc7dq](https://user-images.githubusercontent.com/25992594/131880927-1608f116-3eeb-4a05-9714-bed6299e2d64.gif)
![8te9OxCzos](https://user-images.githubusercontent.com/25992594/131885499-b1dd2789-a96b-4bd1-ba5b-cddef60d1e85.gif)

**Version Info**

Windows 11 Pro 21H2, build 22000.168
Windows 10 21H1
Windows 10 20H2

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes     |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.168)              | Yes   |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by kmgallahan** [comment]
The entrance animation simulates the menu appearing through a slit in the UI, rather than starting as a thin rect and growing. Given this context the first corners to enter appear rounded as expected, and the other corners aren't yet visible until they pass through the slit.

**Comment by torquerrr** [comment]
@kmgallahan Whatever the reason it seems inconsistent and ugly - like not a "true" rounded corners.

**Comment by kmgallahan** [comment]
The visuals are correct for the chosen animation, so if you want 4 round corners from the start you should rework the issue to propose one or more animations you'd prefer - or none at all.

**Comment by torquerrr** [comment]
This particular animation creates bad experience overall. 
What is the purpose of presenting these animation states to the end user?

**Comment by kmgallahan** [comment]
I'm only here to point out that there is no 'lag' that needs to be fixed, so the original issue is invalid. If you don't want to propose a solution then this issue is just a complaint that you don't like something, which isn't particularly productive.

**Comment by torquerrr** [comment]
Can you please show me where this behavior is defined so I know it is a "feature" and not a "bug" and suggest another way?
Also, let me ask again,
> What is the purpose of presenting these animation states to the end user?

**Comment by kmgallahan** [comment]
Look at the animation in slow motion as it plays, it is behaving logically as a card passing through a slit. It is not meant to present the menu as a thin rectangle that grows to the final size. If you think this behavior is a bug then take the next step and explain what the entire animation should look like in your opinion.

If you are asking why animations are used in user interfaces, use Google.

If you are asking why this animation was chosen, then you'll have to wait for a member of the design team to reply.

**Comment by gabrielconl** [comment]
I think he's referring to these corners, which are square at first and animate into rounded corners after the menu appears.
![image](https://user-images.githubusercontent.com/84711285/131904569-ab6ece31-6cc6-4dec-8345-8945fa4cf589.png)

**Comment by torquerrr** [comment]
@gabrielconl exactly. 
I believe that the animation should present the menu with all corners rounded from the very beginning, as it is done in macOS or GNOME. The current approach produces obvious artifacts.
What's interesting is that desktop menu does not show this artifact:
![image](https://user-images.githubusercontent.com/25992594/131919020-0eb8c336-07f3-4658-88fb-7d31f3d01bc0.png)
Which makes the "slit" justification unconvincing.

**Comment by kmgallahan** [comment]
@gabrielconl The top corners don't look rounded at first because they aren't on the screen yet. The entire context menu in its final size is being fed through a straight slot in the screen. Imagine feeding an envelop with rounded corners though a mail slot in a door. Would the top of the envelop appear to have round corners to somebody watching from the other side? No, because they can only see the sides of the menu as it moves through. Only at **the end of the animation do to top to rounded corners become visible because it is at that time that they finally pass through the slot**.

The current behavior is 100% logical when you think of it that way. The only reason the top corners would be rounded is if:

A. Instead of feeding the menu through a slot at its final size, you start it off as a thing strip and grow the height to a final size. This would require either shrinking/stretching the internal content (which would look bad), or creating an internal slit at the top of the menu below the rounded corners to feed the context through as it grows, which would look really odd.

B. The slit / mail slot itself would have to have rounded corners so as to occlude the sides of the menu to make them appear rounded as it passes through. This would require dynamically creating occlusion masks that match the corner radius of whatever is passing through them at the time. I highly doubt anybody is going to spend this much effort, considering the final result would still look weird anyways.

**Comment by gabrielconl** [comment]
In the first animation, the border doesn't really pass through a slit, rather it adjusts to how large the menu is as it's loading. You can see in the screenshot I gave that the border is always rounded, and the background passes through it.
The second animation is correct, because the border passes through the slit together with the background.

**Comment by StephenLPeters** [comment]
I largely agree with @kmgallahan assessment, his description of the current state of things is correct and the mail slot analogy is spot on.  This is a consequence of two seperate technologies, the renderer applying a clip to the content to achieve the rounded corners, and the renderer applying a clip to the viewport window and a translating the content above that clip to achieve the animation.  We could reverse the order of the clips, so the rounded corners clip are above the view port clip, but then we would have the same issue for the bottom corners, they wouldn't round until they reached the bottom of the viewport. 

We have talked about this issue internally but its actually really hard to solve and some people don't even see it as a bug.

**Comment by StephenLPeters** [comment]
@ranjeshj @codendone FYI for visibility

**Comment by kmgallahan** [comment]
@StephenLPeters Was there discussion regarding adopting a fade in style for the menus, so as to match what the new edge uses?

IMO that is a much cleaner animation than "feeding down through a slot".

**Comment by torquerrr** [comment]
@kmgallahan , @StephenLPeters 
Thank you for the detailed explanation, I appreciate it.
But how will you explain this?
![vX4Uf9kHWC](https://user-images.githubusercontent.com/25992594/132056665-d811faa5-bdc1-4e80-a03c-f62f9aefc92e.gif)
Same menu, just different direction.

**Comment by kmgallahan** [comment]
Traveling in the opposite direction through the slot, so you don't see the bottom corners yet...

![](https://im3.ezgif.com/tmp/ezgif-3-85b6de694426-gif-im/frame_128_delay-0.07s.gif)

**Comment by torquerrr** [comment]
No visible "rounding" animation step kicks in -  you obviously don't see the difference with my original examples.
I don't understand how such obvious design inconsistency can be ignored and even justified.

**Comment by kmgallahan** [comment]
I didn't realize the image links I provided would expire so soon, I updated them. As [shown there](https://github.com/microsoft/microsoft-ui-xaml/issues/5826#issuecomment-912823404) the rounded corners aren't visible until they come onto the screen. 

Look at the sequence:

![frame_005_delay-0 07s](https://user-images.githubusercontent.com/5379488/132094371-1cd72b7c-e4fc-42d2-9dcb-00231ec085f7.gif)

![frame_006_delay-0 07s](https://user-images.githubusercontent.com/5379488/132094372-bbfa80c3-5b4e-40de-ac49-82e4aae208d4.gif)

![frame_007_delay-0 06s](https://user-images.githubusercontent.com/5379488/132094375-9d764610-fcf5-4c3f-8b3c-199748fc4d8f.gif)

![frame_008_delay-0 07s](https://user-images.githubusercontent.com/5379488/132094377-0d011a6e-f194-4bd7-b174-5e2c63d2c343.gif)

![frame_009_delay-0 07s](https://user-images.githubusercontent.com/5379488/132094378-2f7769cf-3ff7-44e9-9696-ba9ed64ea0cd.gif)

What is the problem? Corners not on screen and therefore not visible until they come into view.

**Comment by Poopooracoocoo** [comment]
The corners of the flyout in Terminal during its animation look really off and aren't consistent with other flyouts. You don't see the same artifacts in the other examples in here. 

Btw I don't think Fluent UI has the same "slit" animation. That's something to convey to Design.
