### ISSUE TITLE
[WinUI 3 in UWP] Unable to login via default web account provider

### ISSUE THREAD

**Issue by exchange321** [microsoft/microsoft-ui-xaml#5827]
**Describe the bug**
Greetings. I'm trying out the experimental WinUI 3 in UWP. When I was testing fetching access token via `Windows.Security.Credentials.WebAccountProvider`, it keeps failing with:

> The application requesting authentication tokens is either disabled or incorrectly configured.
>
> onecoreuap\shell\cloudexperiencehost\onecore\app\msa\core\TokenProviderExecutor.cpp(1040)\MicrosoftAccount.TokenProvider.Core.dll!00007FFC117D1717: (caller: 00007FFC1180C3ED) Exception(1) tid(2194) 80860003 The application requesting authentication tokens is either disabled or incorrectly configured.

The app has already been associated with the Microsoft Store, and the `Package.StoreAssociation.xaml` file exists in the directory. When I tried the exact same code with the same association to the Microsoft Store in a normal UWP project, the login works as expected.

**Steps to reproduce the bug**

1. Create a new "[Experimental] Blank App (WinUI 3 in UWP)" project
2. Follow the [Web account manager](https://github.com/microsoft/Windows-universal-samples/tree/main/Samples/WebAccountManagement) sample (https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/WebAccountManagement/cs/DefaultAccountScenario.xaml and https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/WebAccountManagement/cs/DefaultAccountScenario.xaml.cs)
3. Go to "Project" -> "Publish" -> "Associate App with the Store" -> Associate with a reserved app name
4. Start the app and attempt to sign in using default account

**Expected behavior**
The sign-in should be successful

**Version Info**
OS version: Windows 10 Pro 10.0.19043
VS version: Visual Studio Community 2022 Preview 17.0.0 Preview 3.1
Project Reunion 0.8.2.50869118

NuGet package version: 
Microsoft.WindowsAppSDK 1.0.0-experimental1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by StephenLPeters** [comment]
UWP is an experimental winui3 feature, I'm not sure if this is expected to work.   @alwu do you know?

**Comment by krschau** [comment]
Closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615). If you are still seeing the behavior with a Win32 app using the latest WindowsAppSDK version, please open a new issue.
