### ISSUE TITLE
Tabview close last inactive tab cause page shakes

### ISSUE THREAD

**Issue by iloxmn** [microsoft/microsoft-ui-xaml#5829]
**Describe the bug**
Problem1
Tabview close last inactive tab cause page shakes
The official xaml controls gallery has the same problem but built in screen recorder doesn't allow me to record this
Problem2
The new tab animation of Tabview is weired

**Steps to reproduce the bug**

1. Open 2 tabviewitems
2. Close the inactive one

**Expected behavior**
everything stays where it should be and the tabitem doesn't fadeout and fadein

**Screenshots**
Problem1
[https://imgur.com/7kOloO3](url)
Problem2
[https://imgur.com/0Z8Ad4J](url)

**Version Info**

Windows 11 22000.168

NuGet package version: 
Microsoft.UI.Xaml 2.7.0-prerelease.210827001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
Hmm, @iloxmn I'm not able to see this on my machine in Xaml Controls Gallery, which sample reproduces the issue?

**Comment by iloxmn** [comment]
https://user-images.githubusercontent.com/22426402/132088207-72121bf3-ee57-44b4-b657-1579529540cc.mp4
I recorded Xaml Controls Gallery's Tabview with another screen recorder
I think it's reproducible in every default styled Tabview
When there's only 2 tabs,  close the inactive one, the height off current tab will change
I didn't look the code but I found custom styled Tabview doesn't have this problem like Windows Terminal, Files, BILIBILI
