### ISSUE TITLE
Question: Where is the mouse double click event?

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#5836]
I want to double-click the image control and open the image file selection dialog box? But there is no double-click event? what should I do?

**Comment by ghost1372** [comment]
> I want to double-click the image control and open the image file selection dialog box? But there is no double-click event? what should I do?

double click is not exist. you should use `DoubleTapped`

**Comment by shelllet** [comment]
> > I want to double-click the image control and open the image file selection dialog box? But there is no double-click event? what should I do?
> 
> double click is not exist. you should use `DoubleTapped`

thx, very excellent, i didn't expect its work on desktop app when i see named `tap`!
