### ISSUE TITLE
Weird behavior when setting GroupStyle at run-time in ListView control 

### ISSUE THREAD

**Issue by Subashini2129** [microsoft/microsoft-ui-xaml#5837]
**Describe the bug**
Weird behavior when setting GroupStyle at run-time in ListView control. Please find the screenshot regarding it further.

**Steps to reproduce the bug**
1. Run the sample.
2. Check the CheckBox displayed to set group style.

**Expected behavior**
Grouping UI should be updated properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/56991221/132163957-1ff676b7-a079-40db-8fc2-f436232c9cee.png)

**Sample**
[ListView-GroupStyle-issue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7113478/ListView-GroupStyle-issue.zip)

NuGet package version: 
[WinUI 3 - Project Reunion 0.8 Preview: 0.8.1-preview]

**Comment by StephenLPeters** [comment]
@Subashini2129 do you know if this reproduces with Winui2 as well?
