### ISSUE TITLE
Question: [Win 11 like app]

### ISSUE THREAD

**Issue by Petrarca181** [microsoft/microsoft-ui-xaml#5838]
Hello, is it possible to make with current  SDK 1.0.0 exp application that will look like Win 11 settings menu?
I currently  using   ExtendsContentIntoTitleBar.  But  if I set the background property  to any element,  buttons wanish.

So basically I want NavView, Pane, Titlebar share same backround. There is any solution? Or some app example?
Tank you.

**Comment by ghost1372** [comment]
> Hello, is it possible to make with current SDK 1.0.0 exp application that will look like Win 11 settings menu?
> I currently using ExtendsContentIntoTitleBar. But if I set the background property to any element, buttons wanish.
> 
> So basically I want NavView, Pane, Titlebar share same backround. There is any solution? Or some app example?
> Tank you.

Do you mean to use Windows App SDK (WinUI 3)?
if yes, Windows 11 visual styles are not currently included in this version. According to the latest news announced on YouTube, we will probably see visual styles in the next experimental version. Which should probably be published these days.
[Powertoys](https://github.com/microsoft/powertoys) recently has changed its settings page to Windows 11 style (But they use WinUI 2.6) I created the WinUI 3 version from their code The result is not very good, but it is not bad either.
https://github.com/ghost1372/HandySub/blob/master/src/HandySub/HandySub/Pages/SettingsPage.xaml

![image](https://user-images.githubusercontent.com/9213496/132218605-b949255a-c82b-4cb5-bf18-818f284a3b86.png)

**Comment by niels9001** [comment]
For PowerToys, I have created multiple Settings UserControls that replicate the W11 styled cards. 

You can find all the XAML you need in the repo here: https://github.com/microsoft/PowerToys/tree/master/src/settings-ui/Microsoft.PowerToys.Settings.UI

![image](https://user-images.githubusercontent.com/9866362/132247950-f8f6b420-a5a5-4211-9437-cb993ab29dd9.png)

**Comment by Petrarca181** [comment]
Thank  you, very cool examples!
