### ISSUE TITLE
Binding to TabItemsSource doesn't select an active tab

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#5839]
**Describe the bug**

According to the documentation [here](https://docs.microsoft.com/en-us/windows/apps/design/controls/tab-view#guidance-for-tab-selection) tabview should always have an active tab. 

> ### Guidance for Tab selection
> ***No matter how the user interacts with a set of document tabs, there should always be an active tab***. If the user closes the selected tab or breaks the selected tab out into another window, another tab should become the active tab. ***TabView attempts to do this automatically selecting the next tab***. 

However, it seems that is not the case. 
![image](https://user-images.githubusercontent.com/8557046/132215587-a08fa738-b798-4d9c-94ad-8df03084c269.png)

**Steps to reproduce the bug**

1. Bind to TabItemsSource

**Expected behavior**

The first tab should be active

**Screenshots**

See above

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 0.8: 0.8.2] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |Yes  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

I am using reactive ui to bind, but that should not make any difference.

**Comment by StephenLPeters** [comment]
@beervoley or @chingucoding can you advise?

**Comment by chingucoding** [comment]
It seems that TabView does not do anything with regard to selection when the items source changes. I think the correct fix for this would be to simple select the first item if the TabViewItemsSource of a TabView get's set. Or are there maybe better ways to work fix this?
