### ISSUE TITLE
MUXC NavigationView in Secondary Window Causes Unhandled Exception.

### ISSUE THREAD

**Issue by jingkecn** [microsoft/microsoft-ui-xaml#5840]
**Describe the bug**

I have a perso project ([Open Ink](https://github.com/jingkecn/OpenInk.Windows/tree/WinUI/issue-reproduction)) using WinUI.
Everything was working fine until I upgraded WinUI from `2.4.3` to `2.6.2`:

I have an MUXC `NavigationView` in a secondary Window, each time I launch the secondary Window, an `UnhandledException` is issued w/ a message saying:

```
"Failed to assign to property 'Microsoft.UI.Xaml.Controls.FontIconSource.FontFamily'. [Line: 725 Position: 123]"
```

**Steps to reproduce the bug**

1. Clone my project ([Open Ink](https://github.com/jingkecn/OpenInk.Windows/tree/WinUI/issue-reproduction)) w/ the branch `WinUI/issue-reproduction`
2. Open `Starter.sln` in VS2019 or later
3. Build and run the `Main` project to install the app
4. From the Dashboard, click the `Add` button then `Get Started` from the language selection dialog

**Expected behavior**
A secondary Window w/ MUXC `NavigationView` is supposed to be launched (OK w/ WinUI `2.4.3` but KO w `2.6.2`).

**Screenshots**

**Version Info**

NuGet package version:

[Microsoft.UI.Xaml 2.6.2]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  No|

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |  Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Source file to test: `Main > Views > Book > BookViewPage.xaml`.
Please try removing the MUXC `NavigationView` and you'll find that the secondary Window can be successfully launched (w/ WinUI `2.6.2`).

**Comment by StephenLPeters** [comment]
@ranjeshj I think this is the same issue that we hit with Repeater's default layout property with multiple windows.  I think the FontIconSource is not thread safe which is causing it to crash when used by UI on two different threads (multi window apps)  @jingkecn you could try setting this property to a different value for each window, instead of allowing the default to be applied for each one.

**Comment by jingkecn** [comment]
Thank you @StephenLPeters for your reply, I've updated WinUI from 2.6.2 to 2.7.0-prerelease, and it seems that the bug doesn't exist anymore. Hope it helps.
