### ISSUE TITLE
[RichEditBox] Cannot delete selected text

### ISSUE THREAD

**Issue by tipa** [microsoft/microsoft-ui-xaml#5843]
**Describe the bug**
TextCommandBarFlyout "blocks" deletion of selected text in RichEditBox

**Steps to reproduce the bug**
1. Open Xaml Control Gallery and open `RichEditBox` page (xamlcontrolsgallery://item/RichEditBox)
2. Enter text in the `RichEditBox`
3. Select text and see how the TextCommandBarFlyout open automatically
4. Press "del" or "backspace" button on keyboard

**Expected behavior**
Selected text disappears

**Actual behavior**
Nothing happens.

**Comments**
- After dismissing the TextCommandBarFlyout  (e.g. by mouse movement), you CAN delete the text using the "del" or "backspace" keys
- The bug does not occur when using `ControlsResourcesVersion="Version1"` even though a (different!) TextCommandBarFlyout is shown there as well

**Screenshots**
![image](https://user-images.githubusercontent.com/2863198/132412393-3294d599-e6d8-44d1-abbe-a427941cf8aa.png)

**Version Info**
Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
the CBF should be forwarding the unhandled key strokes to the text box...

**Comment by tipa** [comment]
This is quite the annoying issue for apps that use RichEditBox extensively (in my case, it's a journaling app).
Many users reported this issue already and I would welcome a fix in one of the next iterations.

**Comment by tipa** [comment]
*Please* fix this @StephenLPeters. The RichEditBox is **so** frustrating to use currently.

Another problem that I and my users constantly run into is the following:
- Select existing text (-> CBF opens)
- User starts typing -> as soon as you type a space, the space is handled by the CBF instead, causing the "Bold" to toggle instead of writing the space into the RichEditBox

**Comment by StephenLPeters** [comment]
> _Please_ fix this @StephenLPeters. The RichEditBox is **so** frustrating to use currently.
> 
> Another problem that I and my users constantly run into is the following:
> 
> * Select existing text (-> CBF opens)
> * User starts typing -> as soon as you type a space, the space is handled by the CBF instead, causing the "Bold" to toggle instead of writing the space into the RichEditBox

Thanks, also a good issue! We'll prioritize as best we can.

**Comment by tipa** [comment]
Sorry to nag but has this issue any priority?
As I said again, this problem is a **huge** deal breaker for an app like mine, in which Rich Text editing is the core functionality. I am receiving complaints from my users every week and all I can say is that I am unable to help.

**Comment by tipa** [comment]
Will there be any progress? Numerous of my users are complaining (for a good reason). This is such an annoying bug and there's not even a workaround that I know of.
I am surprised that no other developer is affected by this. Am I the only one using this control?

**Comment by kmgallahan** [comment]
@tipa 

Unfortunately lots of developers are affected by lots of issues - there are ~500 issues with the `needs-triage` tag, plus the other 2,000 open issues.

At the same time Microsoft is not increasing the resources / priority given to the WASDK / WinUI teams to sort out those issues (at least in a way that is apparent to end users). 

The situation sucks, but try not to get upset with the WASDK / WinUI teams as they are just acting as an understaffed fire department right now. 

You can always poke into the small bit of code that is open source to try and come up with a workaround yourself - I've done that to resolve a few issues.

**Comment by tipa** [comment]
I'm sorry if my posts came over as criticism towards the WinUI team, that was not intended.
I am disappointed by Microsoft for not increasing resources and priority for WinUI.
It feels like very slow progress was made in the last few months.

**Comment by tipa** [comment]
From what I can tell, this issue has been finally fixed by [this PR](https://github.com/microsoft/microsoft-ui-xaml/pull/6844). Thank you so much @llongley!
