### ISSUE TITLE
navigator.online property inside Webview2 not reflecting offline state with WinUI 2.7.0-prerelease.210827001

### ISSUE THREAD

**Issue by koenvd** [microsoft/microsoft-ui-xaml#5847]
It seems that when the device doesn't have a network connection the `navigator.online` property is still indicating that the Webview is online.

**Steps to reproduce the bug**
1. Create a basic UWP app with a Webview2 control using WinUI 2.7.0-prerelease.210827001.
2. Make sure your device doesn't have any network connection.
3. Start the app
4. The webview will not be able to load the source page
5. However in the console `navigator.online` still returns true.

**Expected behavior**
`navigator.online` should return false.

**Screenshots**
![Screenshot 2021-09-08 214204](https://user-images.githubusercontent.com/15209987/132577045-56538679-ca3e-4f9e-b652-9b5e0d02e12f.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml.2.7.0-prerelease..210827001

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I think this works with Webview2 in WinUI3.0. 

To give some more context but we sometimes use that property to show an extra info message to the user when a certain action fails but the device might just be offline.

**Comment by koenvd** [comment]
This seems to be working as expected on some other devices. So still trying to understand what's going on ...

**Comment by StephenLPeters** [comment]
@codendone @jevansaks and @predavid FYI

**Comment by jevansaks** [comment]
Issues with the WebView2 runtime should be filed over on https://github.com/MicrosoftEdge/WebView2Feedback. 

But since we're here, @jasonstephen15 any ideas?

**Comment by koenvd** [comment]
I took a closer look and apparently this seems to be caused by a vEthernet adapter enabled on my system. Chrome / Edge / Webview2 still keep on reporting their status as online when all other adapters don't have a connection. From the moment I also disable the vEthernet adapter `navigator.onLine` starts returning false.

![vEthernet (2)](https://user-images.githubusercontent.com/15209987/133406923-249a65a6-c7f9-4c55-8174-a5cb91d1a520.png)

Apparently legacy Edge was able to detect this situation which was causing my confusion.

Since Chrome / Edge / Webview2 are all consistent here this is certainly not an issue in WinUI so I will just close the ticket now.

Thanks for looking into this as well and sorry for the early report without detailed investigation from my side.
