### ISSUE TITLE
Proposal: Option to disable automatic top padding for navigation view

### ISSUE THREAD

**Issue by mrjfalk** [Microsoft/microsoft-ui-xaml#585]
# Proposal: Add option to disable automatic top padding for navigation view 

## Summary

When using the navigation view and extending the view into the title bar: `CoreApplication.GetCurrentView().TitleBar.ExtendViewIntoTitleBar = true;`

then the `NavigationView` automatically adds a ContentTopPadding to the layout. This results in the following:
![image](https://user-images.githubusercontent.com/8074736/56396095-9abb3d00-623d-11e9-90fa-69c72e90bb6f.png)

The light blue area is the `Content` of the `NavigationView`, and the red dotted area is the `ContentTopPadding` element automatically added. What I want is to have the light blue area extend to the top of the window.

I'd like to have a simple way to remove this padding, e.g. a bool property or similar on the `NavigationView`.

## Rationale

When I set `CoreApplication.GetCurrentView().TitleBar.ExtendViewIntoTitleBar = true;` I often want to expand my content as well into the title bar. As far as I know, to achieve this right now I've got to modify the complete NavigationView style to remove the element, or set a negative margin on the content matching the height of titlebar (which can change so quite a bit of code). A Boolean/value to override/disable this behaviour would be much better.

I also couldn't find any documentation on this, for me quite "magic" and unexpected, behavior. So at a minimum some comments about this in the documentation would be nice.

**Comment by jevansaks** [comment]
@yulikl sounds like a dupe but I can't find it. :)

**Comment by YuliKl** [comment]
This is tracked by #47. @mrjfalk, please up vote that issue and provide feedback in case it's missing anything.
