### ISSUE TITLE
Broken TabItemTemplateSelector in both WinUI 3 Desktop and UWP with WinUI 2.6.2

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#5852]
**Describe the bug**

Using TabItemTemplateSelector to display a collection as TabViewItem does not display TabItems properly.

**Steps to reproduce the bug**
Simply add `TabItemTemplateSelector` and bind `TabItemsSource` to an `ObservableCollection`

Also, see the repo at [here](https://github.com/harvinders/BrokenTabView)

**Expected behavior**

**Screenshots**

WinUI 3 0.8.2
![image](https://user-images.githubusercontent.com/8557046/132660919-1f413dd9-6d49-4ac2-8b6a-832faa7e1f3d.png)

WinUI 2.6.2 (UWP)
![image](https://user-images.githubusercontent.com/8557046/132662877-4ff9b9b9-d9e9-4fbe-9318-97ee783087db.png)

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.6.2]
[WinUI 3 - Windows App SDK 0.8: 0.8.2] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@beervoley or @chingucoding do you know whats going on here?

**Comment by blake-fm** [comment]
Was able to reproduce this using WinAppSDK 1.0.0 stable on Win11 -- new Win32 app, add TabView, use a TemplateSelector.

Also created a dirty, dirty workaround.  Should be a quick copy/pasta to back out, when the resolved issue makes it to us.  In case it helps anyone:

https://stackoverflow.com/a/70821759/17972737
