### ISSUE TITLE
Control's tapped event listening on interacting with clear button in textbox

### ISSUE THREAD

**Issue by susmitha-sundar** [microsoft/microsoft-ui-xaml#5853]
**Describe the bug**
 I have created the custom control with text box. When go for edit mode, clear button also shown in textbox. When I click the clear button, Control's tapped event called. Whereas I click on text on text, tapped event not raised. 

**Steps to reproduce the bug**

Run the attached sample.

Go for edit mode.

Click the clear button.

**Expected behavior**

Tapped event not raised for text box's  clear button interaction.

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.8.2] 

Sample:

[EditControlIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7136208/EditControlIssue.zip)

**Comment by susmitha-sundar** [comment]
Hi Team,

I did not get any update. Could you provide any update on this?

Regards,
Susmitha S

**Comment by StephenLPeters** [comment]
Sorry about that... not sure what happened with this issue's management. I don't have an update, but the clear button in text box should be handling the click, but instead it appears that the routed event is bubbling up to the textbox which is raising it as a tapped event.

**Comment by chrisglein** [comment]
Key bits of the repro:
```xml
    <StackPanel Orientation="Vertical" HorizontalAlignment="Center" VerticalAlignment="Center">
      <StackPanel.Resources>
        <Style TargetType="local:EditControl">
          <Setter Property="Template">
            <Setter.Value>
              <ControlTemplate TargetType="local:EditControl">
                <Grid Height="{TemplateBinding Height}">

                  <Border Grid.Row="1"
                                        Margin="0,4,4,4"
                                        BorderBrush="#FFC0C0C0"
                                        BorderThickness="1">
                    <TextBox Text="LoadEditControl"/>
                  </Border>
                </Grid>
              </ControlTemplate>
            </Setter.Value>
          </Setter>
        </Style>
      </StackPanel.Resources>
      
      <local:EditControl Height="50" Width="150"/>
      
    </StackPanel>
```

```cs
    public class EditControl : ContentControl
    {
        public EditControl()
        {
            this.DefaultStyleKey = typeof(EditControl);
        }

        protected override void OnTapped(TappedRoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("EditControl::OnTapped()");
            base.OnTapped(e);
        }
    }
```

Result: Clicking on the Clear button causes the EditControl.OnTapped to be fired.
