### ISSUE TITLE
Swipe Control doesn't work since 2.6

### ISSUE THREAD

**Issue by Psykobal** [microsoft/microsoft-ui-xaml#5855]
**Describe the bug**

Since the version 2.6.0 I can't swipe items anymore.

**Steps to reproduce the bug**

1. Create a ListView with a SwipeControl
2. Add SwipeItem to the SwipeControl
3. Launch the app on a touch device
4. Try to swipe the item

**Expected behavior**

The item can be swipe

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0] to 
[Microsoft.UI.Xaml 2.7.0-prerelease.210827001]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |  Yes   |
| May 2020 Update (19041)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |

**Additional context**

As reported by #5762 it seems you can simulate it with the Xaml Controls Gallery application

**Comment by StephenLPeters** [comment]
Strange, these tests pages in both the Xaml Controls Gallery and The MuxControlsTestApp are working for me, and our tests have been running consistently..  What version of windows are you on?

**Comment by ad1Dima** [comment]
i had Windows 10 10.0.20348 and swipe control doesn't work in latest Xaml Controls Gallery
And everything works fine on Windows 11 in Hyper-V

**Comment by Psykobal** [comment]
I tried it on a Surface with Windows 10 19042.867

**Comment by Psykobal** [comment]
Thank you for the link, it seems you are right. I tried ranjeshj workaround https://github.com/microsoft/microsoft-ui-xaml/issues/5299#issuecomment-875798060 and it works

**Comment by StephenLPeters** [comment]
Okay, sorry you hit this, its a very complicated root issue...
