### ISSUE TITLE
CurrencyFormatter's Fraction digit value not applied for double value

### ISSUE THREAD

**Issue by susmitha-sundar** [microsoft/microsoft-ui-xaml#5862]
**Describe the bug**

I have used the Double.TryParse() method to convert the string value to Double. And format the double value with currency symbol and fraction digits using CurrencyFormatter.

**Steps to reproduce the bug**

1. Run the sample
2. Click the convert button.

**Expected behavior**

Output value should come with 2 digit fraction vale.

**Screenshots**

![image](https://user-images.githubusercontent.com/60175573/133052756-71c6558e-158c-4b64-a62e-13b576d599e3.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Project Reunion 0.8.2] 

**Additional context**

```
public MainWindow()
{
    this.InitializeComponent();
    valueTextBox.Text = "1802.100000000001";
}

private void myButton_Click(object sender, RoutedEventArgs e)
{
    Double _columnValue;
    var _value = valueTextBox.Text;
    Double.TryParse(_value, out _columnValue);
    var formatValue = this.SystemCurrency.Format(_columnValue);
    ConvertedValueTextBlock.Text= formatValue;
}

public CurrencyFormatter SystemCurrency
{
    get
    {
        return new CurrencyFormatter(Windows.System.UserProfile.GlobalizationPreferences.Currencies[0]) { FractionDigits = 2 };
    }
}

```
Sample:
[FractionDigitsIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7152916/FractionDigitsIssue.zip)

**Comment by StephenLPeters** [comment]
FractionDigits sets the minimum number, not the max.  I think what you want is the NumberRounder property.
