### ISSUE TITLE
Question: How to run WinUI 3 on desktop

### ISSUE THREAD

**Issue by MEK3DK** [microsoft/microsoft-ui-xaml#5863]
Using Win App SDK 1.0 Experimental and VS 2019 16.10.2

When you create a new WinUI 3 project you have 2 options for C#:

- [Experimental] Blank App, Packaged with WAP (WinUI 3 in Desktop)
- [Experimental] Class Library (WinUI 3 in Desktop)

In regards of WinUI 3 there is a lot talk (and some documentation) about Packaged and UnPackaged applications and I think it is difficult to understand how that will all work, which leads to my questions.

My 3 questions are:

1. Will WinUI 3 always run inside some Windows sandbox just like UWP?
2. When you create a project in Visual Studio with WinUI 3 you can run inside VS but if you go directly to the .exe file and click that, nothing happens, why?
3. Will it ever be possible to copy deploy a WinUI 3 application, such that you can just click the exe file in any location/computer?

/MEK

**Comment by MEK3DK** [comment]
I should note that these questions are related to the Win32 part of WinUI 3.

**Comment by ghost1372** [comment]
Hi
WinUI 3 is currently running on a packaged project that is similar to UWP, except that it does not have UWP restrictions and run as a fulltrust app.
In the roadmap we can see that in version 1.0 we can use it in an unpackaged project, which is expected to be run directly from exe

**Comment by StephenLPeters** [comment]
@ryandemopoulos FYI
