### ISSUE TITLE
Crash when dragging the app to another monitor screen.

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#5864]
**Describe the bug**
When the other monitor has another scaling setting than the originating monitor, the app crashes when moving it to the other monitor. 

**Steps to reproduce the bug**
1. Make sure the scaling settings of the two screens are different
2. Move the app to another monitor.
3. Silent crash 

**Expected behavior**
No crash.

**Version Info**
NuGet package version: 
WinUI 3 - Windows App SDK 0.8: 0.8.3

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| N/A | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2021 Update (19043)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment]
@gegao18 and @codendone FYI

**Comment by wbokkers** [comment]
Event log details for this crash:

Logboeknaam:   Application
Bron:          Application Error
Datum:         13-9-2021 10:00:57
Gebeurtenis-id:1000
Task category: (100)
Niveau:        Error
Keywords:  Classic
User:     n/a
Computer:      ...
Description:
Application name with error: Xelion.exe, version: 1.0.0.0, time stamp: 0x60c8ffcb
Name of module with error: Microsoft.UI.Xaml.dll, version: 3.0.0.2108, time stamp: 0x9712de3e
Exception code: 0xc0000005
Error marge: 0x0021e93f
Id pf process with error: 0x5414
Start time of application with error: 0x01d7a86e8aee7884
Path to application with error: C:\Program Files\WindowsApps\782b3c9d-7e38-4cce-8d9a-04a5aeb8c2b9_8.0.21092.0_x86__yxe4w77fgw9tc\Xelion-Desktop\Xelion.exe
Path to module with error: C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.8_8003.236.617.0_x86__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Rapport-id: 25cbb195-cf2c-4ea7-8994-ada5c7737033
Package name with error: 782b3c9d-7e38-4cce-8d9a-04a5aeb8c2b9_8.0.21092.0_x86__yxe4w77fgw9tc
Relative application id of package with error: App

Event-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-13T08:00:57.7028999Z" />
    <EventRecordID>63772</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>LAPTOP-PETER.xelion.nl</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Xelion.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>60c8ffcb</Data>
    <Data>Microsoft.UI.Xaml.dll</Data>
    <Data>3.0.0.2108</Data>
    <Data>9712de3e</Data>
    <Data>c0000005</Data>
    <Data>0021e93f</Data>
    <Data>5414</Data>
    <Data>01d7a86e8aee7884</Data>
    <Data>C:\Program Files\WindowsApps\782b3c9d-7e38-4cce-8d9a-04a5aeb8c2b9_8.0.21092.0_x86__yxe4w77fgw9tc\Xelion-Desktop\Xelion.exe</Data>
    <Data>C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.8_8003.236.617.0_x86__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll</Data>
    <Data>25cbb195-cf2c-4ea7-8994-ada5c7737033</Data>
    <Data>782b3c9d-7e38-4cce-8d9a-04a5aeb8c2b9_8.0.21092.0_x86__yxe4w77fgw9tc</Data>
    <Data>App</Data>
  </EventData>
</Event>

**Comment by codendone** [comment]
I believe this issue is fixed in yesterday's 0.8.4 release. There was a problem with image reload happening when the monitor scale factor changes.

If you still see this on 0.8.4, please reactivate and attach a native callstack.

**Comment by wbokkers** [comment]
The crash has been solved. Thank you.
Unfortunatelty, now we get strange resizing artifacts when dragging the app to another monitor screen. But it is definitely better than crashing.

**Comment by wbokkers** [comment]
Unfortunately there is still a crash when moving to another monitor. The window is not resized (very small), and if the user resizes the window manually on the new monitor, there is a short freeze and then a crash.

**Comment by codendone** [comment]
Sounds like possibly a new issue there. If you agree, can you open a new issue for that? A native callstack of the crash would be helpful for triage.
