### ISSUE TITLE
Question: [Can‘t create a Winui 3 in desktop project]

### ISSUE THREAD

**Issue by TENX-S** [microsoft/microsoft-ui-xaml#5865]
![image](https://user-images.githubusercontent.com/40336192/133104199-4f38f00a-ba83-48c1-af88-47b46b872447.png)

But I installed .NET SDK:
![image](https://user-images.githubusercontent.com/40336192/133104717-f5eefc97-8609-48af-b692-960000eb1d09.png)

systeminfo:
```shell
OS Name:                   Microsoft Windows 10 Professional
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```

**Comment by kmgallahan** [comment]
Desktop != UWP

**Comment by StephenLPeters** [comment]
You need .Net 5, which I'm not sure the visual studio installer will install... you can get it here: https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by TENX-S** [comment]
![image](https://user-images.githubusercontent.com/40336192/133174567-30448c3e-e94c-4656-a42a-cd9b1b6245a2.png)
![image](https://user-images.githubusercontent.com/40336192/133174594-f763d562-622c-4f6c-bdab-86a5990c6455.png)
I got these errors:
![image](https://user-images.githubusercontent.com/40336192/133176358-18cff77a-f928-45f2-91bf-393710fb7ba8.png)

**Comment by TENX-S** [comment]
After uninstall the package drogon by vcpkg, it works fine :)
