### ISSUE TITLE
Question: Can I host WinForm/WPF Controls in WinUI 3

### ISSUE THREAD

**Issue by IrakliLomidze** [microsoft/microsoft-ui-xaml#5866]
Can I host WinForm/WPF Controls in WinUI 3

https://github.com/microsoft/ProjectReunion -->

**Comment by ghost1372** [comment]
No but you can use winui controls in wpf by xaml island

**Comment by IrakliLomidze** [comment]
Is xaml island the same concept as WPFhostcontrol for WinForm  ?

**Comment by ghost1372** [comment]
> Is xaml island the same concept as WPFhostcontrol for WinForm ?

I do not know the details and I have not used it
But here you can read about it
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands

**Comment by StephenLPeters** [comment]
@marb2000 and @kmelmon FYI

**Comment by MEK3DK** [comment]
@ghost1372 The link you provide relates to UWP/WinRT, and partly to WinUI 2.

The question here is about WinUI 3.

I would also like to know if you can host WPF in a WinUI 3 app (when xaml islands are done)?
Right now it is of course not possible.
