### ISSUE TITLE
Duplicate resources for TopNavigationViewItem style brushes

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#5869]
**Describe the bug**
Three TopNavViewItem resources are defined twice in NavigationView_rs1_themeresources.xaml, with different values in Light theme:
* TopNavigationViewItemBackgroundPointerOver
* TopNavigationViewItemBackgroundPointerOver
* TopNavigationViewItemBackgroundSelected

**Steps to reproduce the bug**

1. Open \dev\NavigationView\NavigationView_rs1_themeresources.xaml
2. Observe TopNavViewItem resources list above in Dark and Light theme dictionaries.

**Expected behavior**
Resources should be defined once.

**Screenshots**

**Version Info**
Latest main

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by aqibbanday** [comment]
Hi, I can remove these duplicate, Which resource should be removed transparent or  secondary?

**Comment by aqibbanday** [comment]
Hi, Please Check the following pull request for the changes.
TopNavigationViewItemBackgroundPressed also had duplicates and i have removed the same.
https://github.com/microsoft/microsoft-ui-xaml/pull/5910
