### ISSUE TITLE
The scrollbar's separator in the bottom right doesn't coordinate with the conscious scrollbars (ScrollViewer V2)

### ISSUE THREAD

**Issue by micahl** [microsoft/microsoft-ui-xaml#587]
**Describe the bug**

As soon as the pointer is over the scrolling area the separator fades in while the scrollbars remain conscious/minimal.

![image](https://user-images.githubusercontent.com/1009123/56432211-623d5280-6281-11e9-99b5-2f5693146dda.png)

**Expected behavior**

Behaves like the existing ScrollViewer control.

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.1.190405004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18362)                   | Yes  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |

**Comment by jevansaks** [comment]
@micahl this is only an issue with the new scrollviewer, right?

**Comment by micahl** [comment]
@jevansaks, yes, I'm seeing this on the new scrollviewer.
