### ISSUE TITLE
Artifact on top of menu flyout during expand animation

### ISSUE THREAD

**Issue by rick-palmsens** [microsoft/microsoft-ui-xaml#5873]
**Describe the bug**
The flyout has a slightly darker bar at the top while it is expanding. It disappears once the animation is done.

**Steps to reproduce the bug**
1. Make a menu
2. Make a sub menu
3. Open the sub menu

**Expected behavior**
No artifact

**Screenshots**
![FlyoutArtifact](https://user-images.githubusercontent.com/57390463/133228558-a3538d8f-7c4d-458f-8166-3fa4a5d0e5ff.gif)

**Version Info**
NuGet package version: 
[WinUI 3 - Windows App SDK 0.8: 0.8.3]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@kmelmon FYI
