### ISSUE TITLE
Provide templates for UWP XAML apps that come with WinUI 2.x preinstalled

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#5874]
Although WinUI 3 will be a better option in the future, WinUI 2.x will still be continued. Today the XAML app templates that come with Visual Studio don't have WinUI 2.x preinstalled however I think there should be one with WinUI 2.x preinstalled.

**Comment by StephenLPeters** [comment]
@alwu-msft is there anything stopping us from making a winui2 vsix with the nuget preinstalled?

**Comment by alwu-msft** [comment]
If this is something we determined was worth pursuing, it would be better to update the existing templates shipped with Visual Studio than to add another VSIX containing nearly identical project templates.
