### ISSUE TITLE
Dragged elements with a negative margin get clipped

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#5875]
**Describe the bug**
Dragging an element that has negative margins will clip everything outside the normal bounds of that element.

**Steps to reproduce the bug**
Try dragging a TabViewItem when using the new 2.6 styles. You'll see that the right/left borders and overlays are not visible.

**Expected behavior**
Everything that is rendered inside the element would show when dragging.

**Screenshots**
![image](https://user-images.githubusercontent.com/84711285/136988105-9b690bd8-da04-43bc-a59b-5356394df6c7.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.6.0

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2021 Update (19043)            | Yes |

**Comment by StephenLPeters** [comment]
@gegao18 This seems pretty difficult to fix... thoughts?
