### ISSUE TITLE
Bug: XAML Controls Gallery: Accessibility: The slider is shown vertically when 'Horizontal' radio button is selected and vice versa

### ISSUE THREAD

**Issue by v-amnat** [microsoft/microsoft-ui-xaml#5876]
**Tags**
A11yFeature, FeatureIssue, XAML Controls Gallery (Debug), Win32, Wipro

**Steps to reproduce the bug**

1. Launch the XAML Controls Gallery (Debug) App
2. Go to search bar and type Color picker and hit enter key.
3. Now select the horizontal radio button of orientation and observe brightness slider is shown vertically.

**Actual behavior**
When horizontal orientation is selected, the slider is shown vertically.

**Expected behavior**
When vertical orientation is selected, slider should be shown in vertical itself and vice versa.

**Attachment**
slider orientation.png

**Version Info**
Microsoft OS: 22449.1000
App: XAML Controls Gallery (Debug) (Version 1.2.16.0
![slider orientation](https://user-images.githubusercontent.com/74585893/133257759-1db7f4ff-1852-499e-b8d0-d29e52ff13be.png)
)

**Comment by StephenLPeters** [comment]
This is by design, horizontal is referring to the layout of the color spectrum and its sliders and text boxes, not the slider.
