### ISSUE TITLE
Bug: XAML Controls Gallery: Accessibility: [MAS2.1.2]: Changing NavigationView from LeftExpanded to LeftCompact programmatically leave the control in a bad state.

### ISSUE THREAD

**Issue by v-amnat** [microsoft/microsoft-ui-xaml#5881]
**Tags**
A11yFeature, Accessibility, A11yMAS, A11ySev1, MAS2.1.2, XAML Controls Gallery (Debug), KeyboardNavigation, Win32, Wipro

**Steps to reproduce the bug**

1. Launch the XAML Controls Gallery (Debug) App
2. Go to search bar and type Info Badge and hit enter key.
3. Now Tab to navigate to the 'Display mode' and invoke it.
4. Now select Left compact mode and Observe that the navigation view is put into the expanded popup state, while the navigation view items are displaying their collapsed state.  This can be dismissed by pressing the esc key to close the popup.

**Actual behavior**
NavigationView is entering a bad state when display mode is changed programmatically.

**Expected behavior**
NavigationView's flyout should be collapsed when programmatically set to the LeftCompact mode.

**User Impact:**
Noticeably glitchy looking UI

**Version Info**
Microsoft OS: 22449.1000
App: XAML Controls Gallery (Debug) (Version 1.2.16.0)

**Attachment**
1. focus trap.png
![focus trap](https://user-images.githubusercontent.com/74585893/133273636-76a21717-5759-4e2e-ba5e-1a577488435a.png)

**Additional Context**
Additionally there is a background flash when the transition occurs, likely because of a color transition between two 0 opacity colors.

**Comment by StephenLPeters** [comment]
repurposing this issue, the root issue is that navigation view is entering the expanded flyout state when it enters the LeftCompact mode, not that focus is getting trapped (you can dismiss the flyout with esc to get tab navigation back.)

**Comment by StephenLPeters** [comment]
@karenbtlai You've been looking at a lot of issues similar to this.  THoughts?
