### ISSUE TITLE
Announcing: WinUI 2.7! 🎉💻🍂

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#5889]
The team has just released WinUI 2.7! This release contains a few new features and several bug fixes picked up from the 2.6.x patches.

### New controls
- [InfoBadge](https://docs.microsoft.com/en-us/windows/apps/design/controls/info-badge): A small piece of UI that non-intrusively and intuitively displays notifications or brings focus to an area within an app - whether that be for notifications, indicating new content, or showing an alert.

### New features
- **Horizontal Orientation in ColorPicker**: You can now set the `Orientation` of a [ColorPicker](https://docs.microsoft.com/en-us/windows/apps/design/controls/color-picker#specify-the-layout-direction)  to switch between a vertical or horizontal layout
  - Huge shoutout to @chingucoding for contributing the horizontal ColorPicker! 🎨

### Bug fixes
To see the full list of bugs fixed in this release, see the official [GitHub release](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.7.0).

## Get started
If you're new to WinUI, get started by following the steps in this doc: [Getting started with the WinUI 2.x library](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started)

If you've used WinUI in the past, get started with 2.7 by downloading the latest NuGet package: [NuGet Download](https://www.nuget.org/packages/Microsoft.UI.Xaml)

## Thank you!
Your contributions as a developer community have been incredibly valuable in shipping WinUI. We'd like to extend a big thank you to everyone who contributed to this release by filing or fixing bugs, requesting features, implementing features, and generally being a significant part of the development process!

**Comment by Negociation** [comment]
Tanks, hopefully it will works better than 2.6.x;

**Comment by HppZ** [comment]
where is webview2?

**Comment by ghost1372** [comment]
> where is webview2?

Temporarily removed

**Comment by HppZ** [comment]
when available?

**Comment by ghost1372** [comment]
> when available?

I do not know, but last night in youtube community call they said that it will be available soon

**Comment by zhuxb711** [comment]
Please pay a little attention on this #5768, still exists in WinUI2.7
