### ISSUE TITLE
Microsoft.UI.Xaml 2.7.0 NoiseAsset_256X256_PNG.png not found

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#5890]
**Describe the bug**
I'm now getting an error creating app packages: Could not copy the file "C:\Users\XXXX\\.nuget\packages\microsoft.ui.xaml\2.7.0\lib\uap10.0\Microsoft.UI.Xaml\Assets\NoiseAsset_256X256_PNG.png" because it was not found.

**Steps to reproduce the bug**
On an existing app, with 2.6.X, upgrade the package to 2.7.0 and create an app package in VS.

**Expected behavior**
Should build and package as it did in 2.6.X

**Version Info**
2.7.0

NuGet package version: 

[Microsoft.UI.Xaml 2.7.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19044)              |  Yes |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by asklar** [comment]
Related: #3554

**Comment by myokeeh** [comment]
I saw that, but wasn't sure how relevant. I tried adding the workaround to my .csproj--didn't help.

**Comment by myokeeh** [comment]
@asklar, actually I think the workaround AND deleting bin/obj folders, rebuilding, THEN creating app packages is the ticket.

**Comment by myokeeh** [comment]
I don't know what to think of this. I've now removed the workaround and can successfully build and create app packages again. I tried deleting bin/obj folders first and it didn't work the first time.

**Comment by myokeeh** [comment]
It seems this is still coming back intermittently--unsure what makes it come back/go away at this point.

**Comment by StephenLPeters** [comment]
@myokeeh do you have an app we can see the issue with that you can share with us?

**Comment by myokeeh** [comment]
@StephenLPeters, I'm no longer able to reproduce. To try and resolve the issue, I cleared NuGet cache, downgraded/upgraded NuGet packages, deleted bin/obj folders, and added the workaround. One of these might have cleared this up.

I've since removed the workaround and my apps still build and I can create packages for Store submission. I'll go ahead and close.
