### ISSUE TITLE
DefaultCommandBarStyle's ellipsis button does not respect high contrast mode background themes

### ISSUE THREAD

**Issue by greedyAI** [microsoft/microsoft-ui-xaml#5891]
**Describe the bug**
The DefaultCommandBarStyle contains an ellipsis button for the overflow items. This ellipsis button's background does not change color to the system set color when in high contrast mode.

**Steps to reproduce the bug**
1. Create a brand new UWP project.
2. Add a CommandBar to the XAML. Within the CommandBar control, add some SecondaryCommmands.
3. In Settings -> Accessibility, set your color mode to any of the high contrast themes (Aquatic, Desert...etc.).
4. Observe the background of the ellipsis button.

**Expected behavior**
The background of the ellipsis button should reflect the color scheme of the high contrast theme.

**Version Info**
2.6.2

NuGet package version: 
[Microsoft.UI.Xaml 2.6.2]

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000)              |  Yes  |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment]
@greedyAI I'm not seeing this issue locally, can you post screenshots of what you are seeing?

**Comment by greedyAI** [comment]
This issue appears in an internal app and has been fixed. It no longer repros on the default WinUI controls.
