### ISSUE TITLE
NavigationView does not work

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5892]
**Describe the bug**

```xml
<muxc:NavigationView Grid.RowSpan="2" Grid.Column="1" AlwaysShowHeader="False" PaneDisplayMode="Top" IsBackButtonVisible="Collapsed">
      <muxc:NavigationView.MenuItems>
          <muxc:NavigationViewItem Content="Test"/>
          <muxc:NavigationViewItem Content="Test1"/>
      </muxc:NavigationView.MenuItems>
</muxc:NavigationView>
```
in my real app:
![image](https://user-images.githubusercontent.com/12285582/133610355-40eea472-1eab-4fff-9fb5-090b6326d192.png)
![image](https://user-images.githubusercontent.com/12285582/133610512-0323f394-60b2-41b3-9bd8-3cfc33df4bf1.png)
![image](https://user-images.githubusercontent.com/12285582/133610449-895c3b53-962f-4e10-bd30-5719d2cc8662.png)

in a demo app:
![image](https://user-images.githubusercontent.com/12285582/133609885-ac76f51e-c553-49f0-b0f3-4dcbed399b03.png)

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

![image](https://user-images.githubusercontent.com/12285582/133610749-141347f6-14a9-4a9b-9c9d-d0589b55c6b5.png)

NuGet package version: Microsoft.UI.Xaml 2.7.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by HppZ** [comment]
try set `MenuItemTemplate` 

![image](https://user-images.githubusercontent.com/12285582/133611819-5f3bbfec-950d-4a6d-9d21-3153772f9690.png)
![image](https://user-images.githubusercontent.com/12285582/133611923-451f154d-e9cb-49bf-8489-75de25f87efe.png)

the indicator is wrong and `Text="123"` not apply.

**Comment by StephenLPeters** [comment]
@HppZ what is the issue in the original posting?

In your comment, I believe MenuItemTemplate is not intended to be used with MenuItems but instead MenuItemsSource @ojhad can you weigh in?

**Comment by HppZ** [comment]
> @HppZ what is the issue in the original posting?

1. NavigationView does not show NavigationViewItem‘s `Content` property in my app. why it's `DataContext` is `PlayViewModel`.

> In your comment, I believe MenuItemTemplate is not intended to be used with MenuItems but instead MenuItemsSource.

2. I know. but when `MenuItemTemplate` is set, NavigationView shows NavigationViewItem‘s `Content` property correctly. but the indicator is wrong placed.

3. NavigationView works in my newly created demo app, but not in my real app.

**Comment by ojhad** [comment]
@StephenLPeters  There was an issue a while back where [ItemsRepeater was overwriting the DataContext](DisplayListAndGridViewsWithOldStyles). I wonder if this is an issue in the same area. 

When `NavigationView` has a  `MenuItemTemplate`, there is code in `NavigationViewItemsFactory` that passes the content to the `NavigationViewItem`. I would guess this is why setting a `MenuItemTemplate` bypasses the issue if it's in `ItemsRepeater`. @HppZ that was a super helpful find!

**Comment by HppZ** [comment]
any update?

**Comment by HppZ** [comment]
hello? @ojhad @StephenLPeters

**Comment by ojhad** [comment]
Adding @ranjeshj since @StephenLPeters is currently out of office

**Comment by HppZ** [comment]
adding @codendone for help.

**Comment by HppZ** [comment]
anyone help?

**Comment by HppZ** [comment]
@karenbtlai adding for help.

**Comment by HppZ** [comment]
@ojhad do you have any idea?

**Comment by HppZ** [comment]
@ranjeshj I need you help.

**Comment by HppZ** [comment]
same bug: https://github.com/microsoft/microsoft-ui-xaml/issues/5274

**Comment by HppZ** [comment]
workaround: remove `FocusVisualKind = FocusVisualKind.Reveal;`

**Comment by HppZ** [comment]
f**k

**Comment by HppZ** [comment]
is it because the NavigationViewItem in winui2.7 does not have `OnTopNavigationPrimaryReveal` state defined?

in `NavigationView_v1.xaml`
![image](https://user-images.githubusercontent.com/12285582/141747448-ec367fca-aa51-49e9-9ef3-a78d45e84dfa.png)

in `NavigationView.xaml`
![image](https://user-images.githubusercontent.com/12285582/141747384-6e7da52a-820d-475c-bf12-ced979ac18c3.png)

**Comment by HppZ** [comment]
@karenbtlai
your commit caused this bug. https://github.com/microsoft/microsoft-ui-xaml/commit/6bdf738ede7f979f91ffdae782f394c17351d677
![image](https://user-images.githubusercontent.com/12285582/141749648-24532d6a-fe73-44e7-b7f3-67e5c6b4aa08.png)

**Comment by StephenLPeters** [comment]
Wow, good job finding the issue. the solution is that if the call to GoToState with the OnTopNavigationPrimaryReveal state name (found here: https://github.com/microsoft/microsoft-ui-xaml/blob/fd22d7ff96871f58fec5d9b284eba02fe762c60e/dev/NavigationView/NavigationViewItem.cpp#L374) fails (because the V2 style doesn't support reveal and therefore those states were removed) we need to fallback to the non reveal version of the state.

**Comment by StephenLPeters** [comment]
@HppZ do you want/need your Application.Current.FocusVisualKind to be Reveal?

**Comment by StephenLPeters** [comment]
@HppZ can you try using the nuget package from the #6317 lab run in your application and see if it resolves your issues? :)

**Comment by crutkas** [comment]
@Hppz, Our repository, as do all Microsoft repositories have a [code of conduct](https://opensource.microsoft.com/codeofconduct).  Our GitHub is a safe spot for everyone and should make everyone feel welcome. Let’s be positive and inclusive. Thanks for understanding.
