### ISSUE TITLE
InkCanvas not working in XAML Controls Gallery app

### ISSUE THREAD

**Issue by WillemBos** [microsoft/microsoft-ui-xaml#5896]
InkCanvas not working in XAML Controls Gallery app

**Steps to reproduce the bug**
1. Go to Open the XAML Controls Gallery app
2. Search for InkCanvas
3. Click with the mouse on the canvas and nothing happens

**Expected behavior**
Click with the mouse on the canvas and something will be drawn
**Actual behavior**
Click with the mouse on the canvas and nothing happens

**Screenshots**

**Version Info**
- [ ] App downloaded from Store 
    - If so, which version? 1.2.19.0

**Additional context**

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] 21H1  Update (19043)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by StevusPrimus** [comment]
Hi @stmoy did you draw with the mouse? I could not test with something else than a mouse.

**Comment by stmoy** [comment]
> Hi @stmoy did you draw with the mouse? I could not test with something else than a mouse.

Yes indeed - I drew this rather awkwardly with my mouse 😅

**Comment by StevusPrimus** [comment]
Hi @stmoy, may I ask which commit and windows version you used to test?

**Comment by StevusPrimus** [comment]
> Still not working on Win10 version 2004 Build 19041 for mouse painting. Checked out from master and freshly build with Win10 version 2004 Build 19041. It works with https://github.com/microsoft/Windows-universal-samples/tree/main/Samples/SimpleInk/cs . After some investigation I have the impression the InkPresenter is not listening to the Pointer events anymore. Anyone has a rough idea where to investigate further?

At that point in time the commit was 84c97f0

**Comment by StevusPrimus** [comment]
![image](https://user-images.githubusercontent.com/11518567/134547129-28b7ef54-e003-450c-b121-0a2f176cf678.png)
Also we traced down the issue the commit in the gallery app. d4b13f7 is the first which is broken, it works with 1ab6078 and below.

**Comment by stmoy** [comment]
@StevusPrimus - thank you for the thorough investigation! We are following up internally on this - it seems like it might be related to a change that was fixed in Windows 11, but we're discussing what to do for Windows 10 users.

**Comment by antokhio** [comment]
Hi, i have the same problem, when i added InkCanvas it was also not working, then i tried workaround from that tread https://github.com/microsoft/microsoft-ui-xaml/issues/5299#issuecomment-875798060 mentioned here:
https://github.com/microsoft/microsoft-ui-xaml/issues/6021 without success.

Next i noticed that https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/simpleink/  that sample still working properly, and started to investigate, seems the problem solving lines of code are:
```
InkDrawingAttributes drawingAttributes = new InkDrawingAttributes();
drawingAttributes.Color = Windows.UI.Colors.Red;
drawingAttributes.Size = new Size(penSize, penSize);
drawingAttributes.IgnorePressure = false;
drawingAttributes.FitToCurve = true;

inkCanvas.InkPresenter.UpdateDefaultDrawingAttributes(drawingAttributes);
inkCanvas.InkPresenter.InputDeviceTypes = CoreInputDeviceTypes.Mouse | CoreInputDeviceTypes.Pen;
```
List after adding this to my project InkCanvas started to work straight away
