### ISSUE TITLE
Access conflict exception

### ISSUE THREAD

**Issue by cbuduknui** [microsoft/microsoft-ui-xaml#5900]
User login using signalr Access conflict：
Two ways:
1. `_userInfo = await _owner.CurrentConnection.InvokeAsync<UserInfo>("UserLogin", _owner.RequestToken, userName);`

2.

```csharp
DispatcherQueue.TryEnqueue(async () =>
  {
        _userInfo = await _owner.CurrentConnection.InvokeAsync<UserInfo>("UserLogin", _owner.RequestToken, userName);
        if (_userInfo == null || _userInfo.LoginPass != md5Pass)
        {
              errorMessage.Text = "Login Fail！";
              errorMessage.Visibility = Visibility.Visible;
              args.Cancel = true;
               return;
        }
  });
```

Exception thrown at 0x00007FFD87324F14 (Microsoft.ui.xaml.dll) in PlatformWinui3.exe: 0xC0000005: Access violation reading location 0x0000000000000008.

But in the following way,There will be no abnormality,The if statement runs first,must be login twice:

```csharp
  DispatcherQueue.TryEnqueue(async () =>
   {
         _userInfo = await _owner.CurrentConnection.InvokeAsync<UserInfo>("UserLogin", _owner.RequestToken, userName);
   });
    if (_userInfo == null || _userInfo.LoginPass != md5Pass)
    {
         errorMessage.Text = "Login Fail！";
         errorMessage.Visibility = Visibility.Visible;
         args.Cancel = true;
         return;
     }
```

Version Info
Microsoft.ProjectReunion  0.8.2
Microsoft.ProjectReunion  0.8.3
Microsoft.WindowsAppSDK  1.0.0-experimental1

Windows Info
Windows 10 19041.0928

Visual Studio 2019 16.11.2

**Comment by StephenLPeters** [comment]
@cbuduknui do you have a callstack you can provide us?
