### ISSUE TITLE
AppxRecipe and Transitive nuget packages

### ISSUE THREAD

**Issue by btueffers** [microsoft/microsoft-ui-xaml#5901]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/1412

<div type='discussions-op-text'>

<sup>Originally posted by **Daniellled** September 13, 2021</sup>
We have a nuget package that contains both debug and release assemblies. In the debug assemblies we do something special that the release assemblies excludes. The nuget package uses the buildTransitive nuget feature to execute a target that makes sure upon debug builds we move the correct dll to the output directory. 

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior

When we compile a MAUI WinUI project the debug dlls end up in the correct directories. Debug is in the debug directory, and release is in the release directory.

However, when debugging a MAUI WinUI application we are noticing that the appxmanifest is always pointing to the release binaries. This is causing the release binary from our nuget package to show up in the AppX folder.

What target should our nuget package override to correct this problem?</div>

**Comment by StephenLPeters** [comment]
@alwu-msft thoughts?
