### ISSUE TITLE
📢Announcing: WinUI 3 - Windows App SDK Preview 1.0 🔎💻

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#5906]
We've just shipped the latest version of WinUI 3, which is a part of Windows App SDK 1.0 preview release! This release includes bug fixes and provides access to APIs and features we are intending to include in the next stable release.   

  

## Shipping WinUI 3 as a part of the Windows App SDK 

  

In order to use this version of WinUI 3, you'll download the **Windows App SDK (Preview)** Visual Studio Extension (VSIX) to get started. The Windows App SDK VSIX includes WinUI project templates that you'll use to build your WinUI 3 app, as well as access to other [Windows App SDK components](https://docs.microsoft.com/windows/apps/windows-app-sdk/release-channels#features-available-by-release-channel). The Windows App SDK package includes a reference to the WinUI 3 NuGet package.  

  

For more on the Windows App SDK, see their [documentation](https://docs.microsoft.com/windows/apps/windows-app-sdk) and [repository](https://github.com/microsoft/WindowsAppSDK). For installation instructions, see  [Set up your development environment](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment).  

  

**NOTE**: The Windows App SDK was previously known by the code name Project Reunion. Some SDK assets may still use the code name, but these assets will be renamed in a future release. The term Project Reunion may also be used when referring to an existing asset or a specified earlier release. 

  

## What's new 

  

This release of WinUI 3 is focused on building towards 1.0 Stable with bug fixes.  

   

### Bug fixes 

 

- RichTextBlockOverflow crash when clicking on a Hyperlink: #5425 

- SubMenuFlyout Item causes a double-highlight in MenuBar, causing a feeling of slow performance 

- Image control unable to render animated GIF with unsupported value for the disposal method header: #1128 

- Identity Client package incompatibility: #5143 

- The keyboard and narrator focus are not in sync for all the link elements of the settings window of the WinUI 3 Control Gallery 
 

### Stability 

This release includes unstable APIs and does not support building production apps. If you'd like to use WinUI 3 to build a production app, feel free to continue using the latest [Windows App SDK 0.8 release](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel). 

  

 

### Known Issues 

- Compiler error when using WebView2 in an ARM64 application — this is a regression from 0.8 and will be fixed in 1.0 Preview 2.

For a list of all the known issues for this Windows App SDK 1.0 preview release, please see the [Windows App SDK release notes](https://docs.microsoft.com/windows/apps/windows-app-sdk/preview-channel#version-10-preview-100-preview1). 

  

  

## Getting started  

First, you'll need to set up your dev environment with the appropriate technologies. See our documentation for installation instructions and more information on project types:  

  

**[Install the Windows App SDK](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment)** 

  

**[Create WinUI 3 Projects](https://docs.microsoft.com/windows/apps/winui/winui3/create-winui3-projects)** 

  

While you're developing, check out the [API Reference documentation](https://docs.microsoft.com/windows/winui/api/). 

  

Take a look at our walk-through docs: 

  

- [Get started developing apps with WinUI 3](https://docs.microsoft.com/windows/apps/winui/winui3/get-started-winui3-for-desktop) 

- [Build a basic WinUI 3 app for desktop](https://docs.microsoft.com/windows/apps/winui/winui3/desktop-build-basic-winui3-app) 

  

You can also update your existing WinUI 3 app to use the new Windows App SDK 1.0 preview release using these instructions: [Update existing projects to the latest release of the Windows App SDK](https://docs.microsoft.com/windows/apps/project-reunion/update-existing-projects-to-the-latest-release). 

  

We love feedback! We encourage you to file any bug, big or small, on our repo using [this template](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=). Knowing which issues and features are important and/or critical to our customers highly influences which ones we tackle. Even though we ship with the Windows App SDK, please continue to file WinUI-specific bugs on this repo.    

  

## Using WinUI 3 and the Windows App SDK with our ecosystem partners 

  

This latest release is in the process of being integrated into several other important ecosystem technologies. To test out and follow that progress, check out some of our partner technologies below (note that some of these technologies may not yet be available for Windows App SDK 1.0 preview): 

  

- [Actipro Software](https://www.actiprosoftware.com) is migrating their vast UI control offerings over to WinUI 3, including their SyntaxEditor code editor, propertygrid, native type edit boxes, docking/MDI, charts, and more. 

  

- [DevExpress](https://www.devexpress.com/winui/): DevExpress has released 20 new WinUI controls with Windows App SDK 0.8 support, including the Data Grid, Scheduler, Charts, Ribbon Toolbar, and more. All 20 UI components are available free-of-charge. 

  

- Esri: [ArcGIS Runtime SDK for .NET]( https://developers.arcgis.com/net/) adds mapping, spatial analytics, and location intelligence capabilities to your apps on Android, iOS, and Windows. Support for WinUI 3 is [now available]( https://links.esri.com/arcgis-runtime-dotnet-sdk-winui-blog). 

  

- [GrapeCity](https://www.grapecity.com/): [The ComponentOne WinUI controls](https://www.grapecity.com/componentone/winui-controls/?utm_source=Microsoft_GitHub&utm_medium=Dynamic&utm_campaign=Updated-WinUI-description_08/12/21) support modern desktop apps (Win32) and include calendar, accordion, input and our fast and flexible datagrid, FlexGrid. 

  

- [Infragistics](https://www.infragistics.com/products/winui): Ultimate UI for WinUI brings business critical, high performing, and feature rich line of business controls to your apps that target any platform that runs Windows (including Windows on ARM64). 

  

- [Syncfusion](https://www.syncfusion.com/winui-controls): Updated their projects to Microsoft.ProjectReunion from Microsoft.WinUI following upgrade instructions. All their controls are working fine. 

  

- [Telerik UI for WinUI](https://www.telerik.com/winui): the market first UI controls suite for crafting Win32 and UWP apps with WinUI 3, comes with feature-rich controls like Ribbon, DataGrid, Charts, Gauges, Barcode, and more. 

  

- [Uno Platform](https://github.com/unoplatform): Use WinUI 3 – Windows App SDK 0.8, XAML and C# to build pixel-perfect, single-codebase, native applications that can run on Web, Desktop and Mobile. It is free, open-source and available today. 

  

- [Windows Community Toolkit (Microsoft)](https://aka.ms/wct-winui3): The WCT is currently working on supporting Windows App SDK 0.8 RC. It provides tons of new controls and capabilities for use in your WinUI app. You can check out their open source repo [here](https://aka.ms/windowstoolkit). 

  

## What's next 

To keep up with progress being made on WinUI 3, please see our [feature roadmap](https://aka.ms/winui3/feature-roadmap) which gets updated regularly. We also give monthly updates on our WinUI Community Calls, where you can directly ask the team any questions you have.

**Comment by MrDeej** [comment]
"WinUI: Error creating second Desktop Window on the current process. No more than one Desktop Window is allowed per process.'."

This worked in Experimental.

We can still create new AppWindows, but how do we set content to them?

**Comment by lhak** [comment]
-The expander control seems to be missing (was present in the experimental1 release)

-The GPU memory leak (reported about a year ago here https://github.com/microsoft/microsoft-ui-xaml/issues/3665) is still present

**Comment by edoust** [comment]
Is there any documentation specifically created for this release? All the links reference to older pages as far as I can see

If I create a new app using this release it does not compile, these packages are referenced

<img width="783" alt="package-refs" src="https://user-images.githubusercontent.com/6137595/134322101-086134b9-dbfd-420c-810c-24f2dca6719c.png">

The error is this:
`XamlCompiler error WMC1012: A project cannot have more than one ApplicationXaml item`

I did not make any changes to the default project template

**Comment by koenvd** [comment]
@edoust You might have to remove the lines referencing the experimental1 release? I have this which seems to be working:

![Screenshot 2021-09-23 134443](https://user-images.githubusercontent.com/15209987/134501476-57f5c243-f2ee-488b-91d4-bb23011e5713.png)

**Comment by edoust** [comment]
@koenvd Thanks, this is working

**Comment by axelriet** [comment]
Maybe I missed something, but after installing the latest bits, I have a question: isn't that just Store apps with the Store requirement somewhat relaxed?

**Comment by SolarisBravo** [comment]
Still getting some pretty brutal performance issues in all versions of WinUI 3, including Preview 1. Running the following on CompositionTarget.Rendering with a completely empty window consistently yields results between 29 and 31ms:
`            PerformanceCounter.Stop();
            Console.WriteLine(PerformanceCounter.Elapsed.TotalMilliseconds + "ms");
            PerformanceCounter.Restart();
`

For comparison, if I do exactly the same in UWP XAML I get results in the ballpark of 0.5ms - that's 60 times faster than WinUI 3, which's current framerate (equivalent to ~33fps) is not acceptable even for a desktop UI. Tested on a machine with the following specs:
OS: Windows 11 Pro (21H2)
GPU: NVIDIA GeForce GTX 1080ti
CPU: AMD Ryzen 5 2600
RAM: 2x8GB DDR4, 3000MHz

**Comment by gabbybilka** [comment]
Check out #6172 to see features from this release in Windows App SDK 1.0.
