### ISSUE TITLE
NavigationView: Settings button repositions itself with some delay

### ISSUE THREAD

**Issue by jevansaks** [microsoft/microsoft-ui-xaml#591]
Opening this bug on behalf of @fede9876, from https://github.com/MicrosoftDocs/winrt-api/issues/881.

When resizing the height of the NavigationView, the Settings button reposition itself to the correct position with some delay.
The problem is very noticeable when positioning a PaneFooter element near the Settings button because the PaneFooter doesn't have this problem, so for a short time they overlap with each others.

Step to reproduce the problem:

- Windows 10 October update (Build 17763)
- create an empty project with Min version and Target version = "Windows 10, version 1809 (Build 17763)"
- add this code between `Grid` tags in MainPane.xaml

```
<NavigationView IsSettingsVisible="True">
    <NavigationView.PaneFooter>
        <NavigationViewItem Content="My Pane Footer"/>
    </NavigationView.PaneFooter>
</NavigationView>
```

Here's a preview of the problem (the entity of the delay may vary between different devices).
![bug](https://user-images.githubusercontent.com/46969041/51625874-992ff080-1f3e-11e9-9f2a-2d64f77e96d8.gif)

**Comment by vgromfeld** [comment]
The same issue is also occurring when the NavigationView is in `PaneDisplayMode=Top` mode.
When resizing, we are seeing a big delay for the settings button to update its position. As in the bug description, the `PaneFooter` content is not impacted by this.

Windows min version = 10.0.15063, max version = 10.0.18362
Nuget version:  2.2.190611001-prerelease

**Comment by Code-ScottLe** [comment]
This is the behavior when it is on top mode:

https://gfycat.com/definitefixedinchworm

**Comment by robloo** [comment]
Still present in:
Windows: Windows 10 Home 1903 build 18362.239
NuGet package version: Microsoft.UI.Xaml 2.2.190830001

Below is a gif in top mode.

![Issue](https://user-images.githubusercontent.com/17993847/64974415-c852f380-d87a-11e9-9080-cd0500e65d7a.gif)

**Comment by jevansaks** [comment]
Thanks for letting us know! @licanhua please take a look?

**Comment by jevansaks** [comment]
Also @chingucoding this might be a relatively simple one if you have time?

**Comment by chingucoding** [comment]
> Also @chingucoding this might be a relatively simple one if you have time?

I will look into this.

**Comment by fede9876** [comment]
I don't know if it's still the right place to point this out by I've just installed Win11 22H2 (Build 22621.674) and the new Task Manager is affected by this exact issue.
