### ISSUE TITLE
RichTextBlock theme bug

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5911]
https://github.com/HppZ/RichTextBlockThemeBug

The pointerover color of HyperLink in RichTextBlock is not correct. it is correct once you switch `RequestedTheme` to `Light` and back to `Dark`.

![image](https://user-images.githubusercontent.com/12285582/133881565-6955dbe6-7ebe-4a1a-b342-1aa637d0db8b.png)
![image](https://user-images.githubusercontent.com/12285582/133881577-80619aea-8bf0-47eb-9c39-0aa5981ddc05.png)

**Comment by HppZ** [comment]
@aqibbanday please help.

**Comment by aqibbanday** [comment]
can you update the sample project.

**Comment by HppZ** [comment]
update what?

**Comment by HppZ** [comment]
The repro project can't work?

**Comment by aqibbanday** [comment]
The solution file is not present

**Comment by HppZ** [comment]
just open App6.csproj file with Visual Studio.

**Comment by HppZ** [comment]
is it a bug?

**Comment by aqibbanday** [comment]
` <RichTextBlock
            x:Name="RichTextBlock1"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            FontSize="60">
            <Paragraph>
                <Hyperlink UnderlineStyle="None">
                    <Hyperlink.Inlines>
                        <Run Text="One" />
                    </Hyperlink.Inlines>
                </Hyperlink>
            </Paragraph>
        </RichTextBlock>`

**Comment by HppZ** [comment]
use `RichTextBlock` directly is ok. but if I put `RichTextBlock` in a templated control, it does not work anymore.

**Comment by HppZ** [comment]
why `RichTextBlock` can't be in a templated control?

**Comment by aqibbanday** [comment]
its a sealed class.

**Comment by HppZ** [comment]
I use it as the root element of my custom control. I think this is ok.
![image](https://user-images.githubusercontent.com/12285582/133882419-19087d5d-5a52-4c0f-92eb-033f8f61eff2.png)

**Comment by aqibbanday** [comment]
This should work. Try creating UserControls.

**Comment by HppZ** [comment]
did you run my repro project? https://github.com/HppZ/RichTextBlockThemeBug

**Comment by HppZ** [comment]
> This should work. Try creating UserControls.

why templated control don't work with `RichTextBlock`

**Comment by aqibbanday** [comment]
Yes, and wht do you mean by templated control? You cannot inherit RTBlock because the class is sealed.

**Comment by HppZ** [comment]
I mean this:
![image](https://user-images.githubusercontent.com/12285582/133882682-52135c3e-e664-48e2-95a6-7a978374274d.png)
![image](https://user-images.githubusercontent.com/12285582/133882688-ac3874d0-0a60-43f8-9638-e601c02406d1.png)

`RichText` is a templated control.

**Comment by HppZ** [comment]
`RichText` exists in my repro project.

**Comment by aqibbanday** [comment]
public sealed class RichTextBlock

**Comment by HppZ** [comment]
> public sealed class RichTextBlock

I don't inherit RichTextBlock, I inherit Control and use RichTextBlock as the template root element. then my templated control does not work.
![image](https://user-images.githubusercontent.com/12285582/133882855-171947d5-2c10-4124-9b43-b715d287e3d4.png)
![image](https://user-images.githubusercontent.com/12285582/133882867-9001f2dc-f73a-45e3-8090-9fc46b34e25e.png)

**Comment by HppZ** [comment]
am I missing something?

**Comment by aqibbanday** [comment]
``

**Comment by aqibbanday** [comment]
` <Style TargetType="local:RichText">
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="local:RichText">
                    <RichTextBlock x:Name="RichTextBlock_Part">
                        <Paragraph />
                    </RichTextBlock>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>`

**Comment by aqibbanday** [comment]
Allow me to commit the changes.

**Comment by HppZ** [comment]
put `<Paragraph />` in RichTextBlock fixed the bug, but why?

**Comment by HppZ** [comment]
> Allow me to commit the changes.

invited.

**Comment by aqibbanday** [comment]
> put `<Paragraph />` in RichTextBlock fixed the bug, but why?

Not sure.

**Comment by HppZ** [comment]
thanks.

ok, i will keep this issue open.

**Comment by StephenLPeters** [comment]
@codendone thoughts?
