### ISSUE TITLE
ProgressRing progress inconsistency

### ISSUE THREAD

**Issue by thombrink** [microsoft/microsoft-ui-xaml#5912]
As shown in the xaml controls gallery, the ProgressRing does not fill consistently (with 'IsIndeterminate=False').

When the progress is set to 100 or 99, it shows like this:
![image](https://user-images.githubusercontent.com/5973204/133883915-d3af009b-950c-449a-9126-08475ed2dae0.png)

Changing the value to 98 or 97 makes a huge difference:
![image](https://user-images.githubusercontent.com/5973204/133883952-dd899245-9154-4fcf-bc75-6e8ec93f219b.png)

Changing the value to 96 and below is consistent:
![image](https://user-images.githubusercontent.com/5973204/133883979-a686620b-ca71-444d-92a6-ddeee300f7e9.png)
![image](https://user-images.githubusercontent.com/5973204/133883984-7ece486b-324b-44cf-950f-1fe4771dd7a6.png)
![image](https://user-images.githubusercontent.com/5973204/133883985-3f24780c-a2a0-40e7-a0ac-6eb1b3f76ab4.png)

I would expect to have half a bar left at 50, but instead it's well over:
![image](https://user-images.githubusercontent.com/5973204/133884071-01d800d0-e674-4395-93fc-7086def67122.png)

If this is expected behavior, then I would like to propose a 'IsAbsolute=true' property. I'm using the ProgressRing for a countdown timer and it looks very weird.

**Comment by chingucoding** [comment]
Unfortunately, this is a known bug with ProgressRing that is being tracked by #3787.

**Comment by StephenLPeters** [comment]
closed as duplicate.
