### ISSUE TITLE
Question: how to implement custom ContentLinkProvider?

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5914]

**Comment by StephenLPeters** [comment]
@chrisglein Do you know?

**Comment by chrisglein** [comment]
> @chrisglein Chris Glein FTE Do you know?

I don't. Don't the the [docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.documents.contentlinkprovider?view=winrt-20348) indicate that this is deprecated? I'm not actually familiar with the feature.

**Comment by chrisglein** [comment]
Feature is deprecated and is indicated in the docs. So the answer is: "you don't" 🤷
