### ISSUE TITLE
Question: How to add HyperLink into RichEditBox?

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#5915]

**Comment by StephenLPeters** [comment]
something like this should work: https://stackoverflow.com/questions/41717420/how-to-convert-a-selected-text-into-a-hyperlink-in-a-richeditbox?rq=1

more generally: https://docs.microsoft.com/en-us/uwp/api/windows.ui.text.itextrange.link?view=winrt-20348
