### ISSUE TITLE
Cannot use multiple Windows in WinUI 3 1.0.0 Preview

### ISSUE THREAD

**Issue by MrDeej** [microsoft/microsoft-ui-xaml#5918]
**Describe the bug**
When I try to create a new Window other than the MainWindow, it throws an Exception from KernelBase.

When I try to create a new AppWindow, I cannot find a way to set a content. 

The AppWindow shows fine, but without content. 

In UWP we used ElementCompositionPreview.SetAppWindowContent(appWindow, new Page()); but this does not exist in WinUI 3.
In WinUI 3 Experimental we first created the new Window(), then got the AppWindow from the Windows Handle and Window ID.

**Steps to reproduce the bug**
1. Create a new WinUI 3 1.0.0 Preview Desktop app
2. Create methods from screenshots
3. Not able to use multiple windows with my app

**Expected behavior**
Desktop app should be able to use multiple windows. Also the Window.Activate() worked fine in WinUI 3 1.0.0 Experimental for multiple Windows on same thread.

**Screenshots**
![image](https://user-images.githubusercontent.com/16320446/133919630-92687c4e-37b4-484d-9478-1b0694d48629.png)
![image](https://user-images.githubusercontent.com/16320446/133919724-8a2ec730-abb4-43d0-a202-cb0e8b1a0d36.png)

**Version Info**
WinUI 3 1.0.0 Preview Desktop, Windows 10 19044, Visual Studio 2019 16.11.2

NuGet package version: 
![image](https://user-images.githubusercontent.com/16320446/133919761-99057ce6-56d8-4593-bfc8-7ce357723ac3.png)
Windows app type: Win32 x86

| Windows version                 
| Insider Build (19044)            

| Device form factor | Saw the problem? 
| Desktop         

**Additional context**
Need this as fast as possible. 

Our current UWP app have grown so large that RH-Bind goes out of memory even in x64 compiler, and currently unable to build. Also our current UWP app is using gRPC.Core wich have production bugs that are solved when using WinUI and Net 5.

This is a large LOB app.

**Comment by codendone** [comment]
Unfortunately the support for multiple Windows was not finished in time to be included in 1.0. The Experimental build had the block for this and other incomplete features disabled, and those blocks are re-enabled for Preview and Stable releases.

**Comment by MrDeej** [comment]
Ohh, thank you for the answear.

It still looks like Winui 3 1.0.0.0 Experimental is more stable than our current UWP build, so I think we will have to go to production with this. But please disable the block in next WinUI 3 Preview. It works perfectly fine for our needs in the Experimental build, with only 1 workaround for activating the window (it displays back the mainwindow when heavily loaded with ui objects).

**Comment by Sacwith** [comment]
how to create Window on Window in winui3 with wpf  preview 1.0?

**Comment by nkasco** [comment]
Any workarounds for this?

**Comment by codendone** [comment]
Multiple Windows on the same thread is now supported in Windows App SDK 1.0.1. Check out the [release notes](https://github.com/microsoft/WindowsAppSDK/discussions/2291) for more info.

**Comment by dotMorten** [comment]
@codendone I'm still seeing this happening on my Windows 10 PC. Exact same code works on my Windows 11 PC. Both 1.0.1 and 1.1.0-preview1 has this behavior.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1378165/161596782-4c39bc49-3175-4ac5-a540-c55fcff3a96a.png">

The release notes didn't mention anything about it being a Win11-only thing.

**Comment by codendone** [comment]
@dotMorten I think you logged microsoft/WindowsAppSDK#2363 for what you were hitting?

**Comment by dotMorten** [comment]
Yeah it was due to another bug in the app Sdk packaging system that led to that behavior. It’s a deployment issue if mixed versions that was causing it: ignore my comment above
