### ISSUE TITLE
The ComboBox with ItemTemplate throws Catastrophic failure

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#5923]
**Describe the bug**
Hi, I've faced a new issue. At now the ComboBox throws the exception when the `ItemTemplate` property. I guess that happens because I've bound the `SelectedItem`. If a remove that or comment the `MyValue` property initializing it will work.

**Steps to reproduce the bug**
```xaml
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <ComboBox DisplayMemberPath="Text"
                  ItemsSource="{x:Bind TestSource}"
                  SelectedItem="{x:Bind MyValue, Mode=TwoWay}">
            <ComboBox.ItemTemplate>
                <DataTemplate>
                    <TextBlock Text="Test"/>
                </DataTemplate>
            </ComboBox.ItemTemplate>
        </ComboBox>
    </StackPanel>
```
```csharp
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            TestSource = new DisplayItem[] {
                new DisplayItem(1, "Value1"),
                new DisplayItem(2, "Value2"),
            };
            MyValue = TestSource[0];

            this.InitializeComponent();
        }

        public IList<DisplayItem> TestSource { get; }
        public DisplayItem MyValue { get; set; }
    }

    public class DisplayItem {
        public DisplayItem(int value, string text) {
            Value = value;
            Text = text;
        }

        public int Value { get; }
        public string Text { get; }
    }
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47348109/133967109-020e2a25-91d7-4a91-864c-5a79d6fe8511.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 0.8: 0.8.0] If you're seeing your issue in older previews of WinUI 3, please try this release.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes|

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |  Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
I'm not positive but I think that calling InitializeComponent after you instantiate a value for MyValue is your problem. If you call InitializeCompnent I think that will work.

**Comment by alexdi220** [comment]
> I'm not positive but I think that calling InitializeComponent after you instantiate a value for MyValue is your problem. If you call InitializeCompnent I think that will work.

Yes, I know, but it's a workaround, not a solution.
