### ISSUE TITLE
Xamarin 5 UWP - Display Alert Issue

### ISSUE THREAD

**Issue by Koub96** [microsoft/microsoft-ui-xaml#5924]
Hello everyone,
Me and my team have just migrated our cross-platform XF 4 project to XF5. The only issue that we have encountered thus far is the following: Our UWP App was throwing an unhandled App.Xaml exception when navigating to a different page for no apparent reason and after some search, installing the nugget **Microsoft.UI.Xaml** explicitly fixed that issue, even though that nugget package is supposed to be installed along with XF5 nugget. But right now a new issue has emerged. When calling the 'await Application.Current.MainPage.**DisplayAlert**(szTitle, szMessage, btnOk, btnCancel);' from the UI thread the alert gets displayed properly but when I click on one of its buttons Ι get an unhandled exception **"No installed components were detected. The property path '(controls:AnimatedIcon.State)' could not be resolved for a Setter.**" where controls is defined as **xmlns:controls="using:Microsoft.UI.Xaml.Controls"** Could you please help me find out what is going wrong? As far as I know the DisplayAlert() is handled by Xamarin.Forms.

You can find a sample that reproduces the issue here: https://github.com/Koub96/Xamarin-5

**Comment by StephenLPeters** [comment]
My guess is that the XF5 package has not updated to the version of the Microsoft.UI.Xaml that you explicitly added to fix the original issue.  Animated Icon was added in 2.6, do you know what version XF5 is built on?

**Comment by Koub96** [comment]
@StephenLPeters Thank you for your quick reply. I see that the latest version of XF5 requires **at least** Microsoft.UI.Xaml version 2.4.3 and **at least** Win2D.uwp version 1.20.0.
So in theory it should not have an issue that I explicitly added the latest version of Microsoft.UI.Xaml.
Keep in mind, that in the original issue, XF5 seemed to not install it's dependency to Microsoft.UI.Xaml at all.
