### ISSUE TITLE
The appearance of List/Grid view and Calender view doesn't match the latest fluent design system principles (WinUI 2.7)

### ISSUE THREAD

**Issue by AbdAlghaniAlbiek** [microsoft/microsoft-ui-xaml#5928]
**Describe the bug**
In the collection section of this app, I noticed that list view and grid view doesn't match the latest fluent design principles
In list view the light interaction is correct but when select on an item of list view items it give me the interaction that was provided in WinUI 2.5, It must be looks like similar to navigation view items interations when hover and select them
In Grid view the items in the sample not rounded like was introduced WinUI 2.7
The Calender view and Calender view picker items should be rounded when hover and select them and when IsGroupLabelVisible is true the text is visible but it is crossed with the date cells

The appearance of list/grid view should be looks like as described in the docs:
[https://docs.microsoft.com/en-us/windows/apps/design/controls/listview-and-gridview](url)

And appearance of Calender view and Calender view picker should be looks like as described in the docs:
[https://docs.microsoft.com/en-us/windows/apps/design/controls/calendar-view](url)

I searched about this in figma toolkit for WinUI 2.6, I found it as it was described in the docs
[https://www.figma.com/community/file/989931624019688277](url)

I don't know if this problem from WinUI library or from this app but If you check this issue, I will be thankful ❤ 

**Steps to reproduce the bug**
1. Go to Collection section
2. Click on List view and Grid view (The apperance isn't correct 😢)
3. Go to Date and Time
4. Click on Calender view and Calender view picker  (The apperance isn't correct also 😢)

**Expected behavior**
They should be look like as described in docs and figma toolkit 

**Actual behavior**
It gives the appearance of WinUI 2.5 not WinUI 2.7

**Version Info**
- [1.2.21.0] (latest version)] App downloaded from Store 

Windows version:
- May 2019 Update (18362)

Device form factor:
- Desktop

**Comment by StephenLPeters** [comment]
![image](https://user-images.githubusercontent.com/7758786/134437123-c9690614-5ced-4f3b-8033-909d103d5122.png)


This is what I see for grid view in XCG, what is it that is incorrect?

**Comment by AbdAlghaniAlbiek** [comment]
![grid view](https://user-images.githubusercontent.com/37735487/134599920-56a7d6ed-e5d0-4083-9220-167cae9dabae.jpg)
![list view](https://user-images.githubusercontent.com/37735487/134599906-adbf212c-e9ee-4fa4-b78e-43762c7b57a0.jpg)
 
I don't know but on my device (Windows 10 May 2019 update) they looks like this ☝☝

**Comment by ranjeshj** [comment]
@AbdAlghaniAlbiek what you see is expected (unfortunately). The List/Grid items are rendered in code (ListViewItemPresenter) and we had to make code changes in OS XAML to achieve this which means it is only available in Win11 and not Win10 unfortunately. With WinUI3, the entire XAML code base will be part of WinUI3 so that will work downlevel as well, but as it stands today with WinUI2 this is expected.
