### ISSUE TITLE
Application.Exit() doesn't work if app doesn't have any windows open

### ISSUE THREAD

**Issue by andrewleader** [microsoft/microsoft-ui-xaml#5931]
**Describe the bug**
While trying to implement single instance redirection, I noticed that the `Exit()` API doesn't work unless the app has windows open. In the case of redirecting activation, after redirecting the activation, the second instance needs to be closed (without ever showing any windows). But calling `Exit()` doesn't do anything, the process stays running...

**Steps to reproduce the bug**

1. Create a new WinUI 3 Desktop app, and in OnLaunched, update it to the following (exits itself after 6 seconds and never shows window)...

![image](https://user-images.githubusercontent.com/13246069/134069843-6cd1f7f6-8d59-4dca-83ae-2037056860d8.png)

2. Launch the app
3. Open Task Manager, and notice that the process is still running (under background processes) after 6 seconds and never exits

**Expected behavior**
App should exit. The `Exit()` API works if there's an open activated window when it's called, but doesn't work when there's no open window.

**Version Info**

NuGet package version: 
[WinUI 3 - Windows App SDK 1.0.0-preview1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Workaround is to use `Process.GetCurrentProcess().Kill()`.

**Comment by Onkelborg** [comment]
This seems to have worked in 0.8.5 - I noticed this behavior when upgrading to 1.0.0

**Comment by pratikone** [comment]
Thanks for posting this error. I found the problem and fixed it internally. Should come up in some future release. This bug will close automatically with that.

**Comment by DJRM2021** [comment]
This issue still happens with WinUI 3

**Comment by DJRM2021** [comment]
> Thanks for posting this error. I found the problem and fixed it internally. Should come up in some future release. This bug will close automatically with that.

May I know if this issue has been fixed and deployed in any release? Is it included in 1.3-experimental?

**Comment by pratikone** [comment]
I just checked. Sadly, it missed the mark for experiemental. I will check again to see if we will do another set of spot fixes for 1.3. Else, it will be part of next release.

**Comment by DJRM2021** [comment]
> I just checked. Sadly, the commit with the fix missed the bus for experiemental fork :). I will check again to see if we will do another set of spot fixes for 1.3 (@bpulliam ). Else, it will be part of next release.

Thanks!

**Comment by DJRM2021** [comment]
>

**Comment by pratikone** [comment]
Yes, hopefully the next version release of winappsdk

**Comment by DJRM2021** [comment]
Can I just ask why is this issue still not fixed? We are now in STABLE 1.3 of WASDK.

**Comment by DJRM2021** [comment]
I tested this on WASDK 1.3 and seems to be working as expected.

**Comment by pratikone** [comment]
oh, did it make it in ? i need to check again.
