### ISSUE TITLE
WinUI Design Toolkit Bug: [Selected state for nav items]

### ISSUE THREAD

**Issue by kennierthanu** [microsoft/microsoft-ui-xaml#5933]
**Describe the bug**

The selected indicator (blue) should be centered on the text string. It is currently placed in the middle of the menu with an icon.

**Steps to reproduce the bug**

1. I found this bug from the build product that my team is working on. I can't find any other examples to demonstrate the bug

**Expected behavior**

The selected indicator should be centered on the text string. 

**Screenshots**

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
I beleive this is by design, but @alejo4000 FYI about the feedback.
