### ISSUE TITLE
Grids don't stretch properly in pages inside a TabViewItem

### ISSUE THREAD

**Issue by manfromarce** [microsoft/microsoft-ui-xaml#5935]
**Describe the bug**
Grids don't stretch when navigating to a page from a Frame contained in a TabViewItem.
This behavior differs from pages that are not inside a TabView.
(See animated GIF below).

**Steps to reproduce the bug**

1.  Add an empty TabView to a page
2.  Create another page and add a grid with `<RowDefinition Height="*"/>`
3.  Navigate to this new page from an existing tab or add a new tab:
```
            TabViewItem newItem = new TabViewItem();
            newItem.Header = "New tab";
            newItem.IconSource = new Microsoft.UI.Xaml.Controls.SymbolIconSource() { Symbol = Symbol.Home };
            Frame frame = new Frame();
            frame.Navigate(typeof(SamplePage1));
            newItem.Content = frame;
            TabView1.TabItems.Add(newItem);
```

**Expected behavior**
Grid should fill all available space as in windows and pages that are not inside a TabView.

**Screenshots**
![Animation](https://user-images.githubusercontent.com/45036600/134126323-f7fbf23c-0fa6-4f25-a580-e1e9640c45bd.gif)

**Version Info**
NuGet package version: both
[Microsoft.UI.Xaml 2.7.0]
and
[WinUI 3 - Windows App SDK 0.8: 0.8.3]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |  Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment]
@chingucoding and @beervoley know whats going on here?

**Comment by chingucoding** [comment]
Could it be that there is a `VerticalAlignment="Stretch"` missing on the TabView causing this? The default TabViewStyle has it set to `Top` which seems coherent with what we are seeing here. We could change the default value but I am not sure if this is worth it or if it might break more than it would solve.

**Comment by manfromarce** [comment]
Thanks for your answer, the problem was caused by VerticalAlignment.
I had no idea it was set to Top by default since the TabView seems to automatically extend across the page.
