### ISSUE TITLE
Question: Where is new GridView/ListView styles in WinUI 2.6/2.7?

### ISSUE THREAD

**Issue by movpushmov** [microsoft/microsoft-ui-xaml#5938]
On [this](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.gridview?view=winrt-20348#visual-updates-in-winui-26) page we see, what GridView styles has been updated in WinUI 2.6:

**"... These updated visuals include rounded corners, improved borders, rounded checkboxes in multiple selection mode, and more..."**

But in my app I can't see this changes!

![image](https://user-images.githubusercontent.com/49155506/134248705-f4bf0243-828b-4ce2-802c-44eda742fe45.png)

XAML UI Controls Gallery also doesn't have this styles

![image](https://user-images.githubusercontent.com/49155506/134248850-19e06c5d-b260-430d-85c2-e464fa6b2ec4.png)

Where is this new styles? How can I get it?

WinUI version 2.6/2.7

**Comment by StephenLPeters** [comment]
ListView and GridView use specialized code to generate the default presenters for their items, for performance reasons. This code lives in the operating system and was updated with windows 11 to show the new styles. If you want new styles on windows 10 you can use the ListViewItemExpanded styles explicitly, they are included in the winui2.6 and 2.7 packages.  You may also have to set the corner radius property on the elements...

**Comment by movpushmov** [comment]
> ListView and GridView use specialized code to generate the default presenters for their items, for performance reasons. This code lives in the operating system and was updated with windows 11 to show the new styles. If you want new styles on windows 10 you can use the ListViewItemExpanded styles explicitly, they are included in the winui2.6 and 2.7 packages. You may also have to set the corner radius property on the elements...

For GridView I can use GridViewItemExpanded, right?
