### ISSUE TITLE
chevron in AppbarButton of CommandBar is not vertical center aligned

### ISSUE THREAD

**Issue by lyf6lyf** [microsoft/microsoft-ui-xaml#5949]
**Describe the bug**
chevron in AppbarButton is not vertical center aligned, when it is folded in the see more button.

**Steps to reproduce the bug**
1. we have below code
```
        <CommandBar
            Background="Transparent"
            DefaultLabelPosition="Right"
            IsOpen="False">
            <AppBarButton Icon="Add" Label="a very long button text. a very long button text. a very long button text." />
            <AppBarButton
                Flyout="{x:Bind _flyout}"
                Icon="Share"
                Label="Share">
                <AppBarButton.Resources>
                    <Visibility x:Key="AppBarButtonHasFlyoutChevronVisibility">Visible</Visibility>
                </AppBarButton.Resources>
            </AppBarButton>
            <CommandBar.SecondaryCommands>
                <AppBarButton Icon="Setting" Label="Settings">
                    <AppBarButton.KeyboardAccelerators>
                        <KeyboardAccelerator Key="I" Modifiers="Control" />
                    </AppBarButton.KeyboardAccelerators>
                </AppBarButton>
            </CommandBar.SecondaryCommands>
        </CommandBar>
```
The chevron is center aligned if it is not folded. 
![image](https://user-images.githubusercontent.com/6219635/134485499-046dcf67-bc08-4898-9fc0-9cf9b0bd9bfe.png)
But it is bottom aligned when it is folded

**Expected behavior**
It should be center aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/6219635/134486071-11489ffd-4804-4a0a-949c-e60f9d1575c7.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.7.0]

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22460.1000)              | yes  |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by lyf6lyf** [comment]
Related to this bug. Actually, we want the chevron only be visible when the button is not folded in the see more button, and it should be invisible when it is not folded. Is there any way to implement this?

**Comment by ranjeshj** [comment]
Looks like an issue with the overflow template. @teaP  ?

**Comment by teaP** [comment]
Yes, it is definitely an overflow template problem, I can repro.
