### ISSUE TITLE
CompactPane doesn't always disappear in Minimal mode

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#595]
**Describe the bug**
I'm working on adding Shell support to Xamarin.Forms on UWP, and I'm using NavigationView. Everything was going great until I switched to WinUI instead of the native control. 
Now I'm often hit with the pane showing up in compact mode (with its contents collapsed) even when in minimal lmode.
 
**Steps to reproduce the bug**

1.	check out https://github.com/dotMorten/Xamarin.Forms.UWPShell.Sample including the submodule
2.	Build the app ShellSample.UWP and run it.
3.	Click the default shell template button, and notice the list of items goes all the way to the left (expected behavior)
4.	Next go to the Xamarin.Forms submodule and check out the branch “uwp-shell-winui“ (this moves the implementation from the native NavigationView to WinUI)
5.	Repeat the steps and now notice the compact pane is showing, even though the mode is set to minimal:
 
![image](https://user-images.githubusercontent.com/1378165/56463285-e7119480-6385-11e9-9e04-e12572dfc3c2.png)
 
Looking at the live visual tree, it appears that the Pane’s parent Grid has the first column set to 40px, instead of 0, thus pushing the content in. The pane content itself appears to not be rendering.
 
The class that renders this is \Xamarin.Forms\Xamarin.Forms.Platform.UAP\Shell\ShellRenderer.cs which is a subclass of NavigationView. There’s a few state transitions in that class that could be part of the reason that happens.
You can also try the two other samples in addition to Xappy. Some of them when you click around a bit, the problem suddenly goes away.
For instance select Gastropods shows the left bar on startup. Open the pane and click the “Home” menu item (this is loading the same page again), and the problem magically disappears.

**Expected behavior**
Pane shouldn't show, like it behaves with the native view control.

**Version Info**
Reproduces at least on Win10 1809, and 1903

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.1

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   | N/A   |
| Xbox                      | N/A   |
| Surface Hub          | N/A    |
| IoT                         | N/A |

**Comment by dotMorten** [comment]
@licanhua found a much simpler repo:
Simple Repro:
```xml
            <mux:NavigationView IsPaneVisible="False">
                <mux:NavigationView.MenuItems>
                    <mux:NavigationViewItem Content="132" />
                </mux:NavigationView.MenuItems>
                <TextBox Text="This is a test only" />
            </mux:NavigationView>
```

**Comment by jevansaks** [comment]
@licanhua I'll assign to you as it sounded like you were looking into a fix?
