### ISSUE TITLE
New window throws exception

### ISSUE THREAD

**Issue by nordleif** [microsoft/microsoft-ui-xaml#5950]
**Describe the bug**
New window throws exception.
Unhandled exception at 0x78635959 (Microsoft.ui.xaml.dll): 0xC000027B: An application-internal exception has occurred (parameters: 0x19372E18, 0x00000001).

**Steps to reproduce the bug**
Create new winui project and add the following code to the OnClick event.

```
private void myButton_Click(object sender, RoutedEventArgs e)
{
    var window = new Window();
    window.Activate();
}
```
Start the project and click the button.

**Expected behavior**
New window opens.

**Screenshots**
![new window](https://user-images.githubusercontent.com/425306/134513651-f46f1a3a-100b-45f2-82c4-2ff1946c3ced.png)

**Version Info**

NuGet package version: 
Microsoft.WindowsAppSDK.1.0.0-preview1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| | Yes|

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |   |
| May 2020 Update (19041)            |  |
| November 2019 Update (18363)       |   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                | |

**Additional context**

**Comment by codendone** [comment]
Same as #5918. Quote from there:

> Unfortunately the support for multiple Windows was not finished in time to be included in 1.0. The Experimental build had the block for this and other incomplete features disabled, and those blocks are re-enabled for Preview and Stable releases.
