### ISSUE TITLE
Xaml islands issues with access keys & keyboard accelerators 

### ISSUE THREAD

**Issue by joseartrivera** [microsoft/microsoft-ui-xaml#5951]
**Describe the bug**
Following the [advanced scenarios documentation](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/advanced-scenarios-xaml-islands-cpp) for Keyboard input leaves a few unaddressed edge cases including Access Keys and events like ProcessKeyboardAccelerators.

It does not seem like calling PreTranslateMessage on the IDesktopWindowXamlSourceNative2 object triggers access keys from appearing or being processed. It also does not trigger the ProcessKeyboardAccelerators event to run for custom handling of keyboard accelerator scoping.

**Steps to reproduce the bug**
1. Create a C++ Win32 app and add a Xaml Island
2. Follow the guide to implement keyboard accelerators by passing messages via Pretranslate Message https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/advanced-scenarios-xaml-islands-cpp
3. Notice that Access Keys (Alt + Key) do not work and ProcessKeyboardAccelerators does not fire. (Other Keyboard Accelerators do work correctly)

**Expected behavior**
Access keys function, ProcessKeyboardAccelerators fires

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.7.0]

**Comment by viniciusjarina** [comment]
Hi @joseartrivera do you happen to have an small application that repro the current issues you hit?
