### ISSUE TITLE
Application.Exit crashes the app with AccessViolationException

### ISSUE THREAD

**Issue by mattleibow** [microsoft/microsoft-ui-xaml#5952]
**Describe the bug**

Calling `Application.Exit()` on my running ap throws an exception:

```
An unhandled exception of type 'System.AccessViolationException' occurred in Microsoft.WinUI.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

I will also say that I am unable to reproduce this on a blank project. However, I am also not sure how to debug this since it just throws with no additional information.

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version:  1.0.0-experimental1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by chrisglein** [comment]
Can you provide a callstack and/or any information on stowed exceptions or thrown exceptions leading up to the crash? Given that you can't repro this in a standalone app we'll need more context if we're able to help.
