### ISSUE TITLE
Use Transitive Build folder

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#596]
# Proposal: Use Transitive Build folder

## Summary
Use Nuget 5.x transitive build feature to ease the use of libraries that takes a dependency on Microsoft.UI.Xaml.

## Rationale
If an application takes a dependency on a class library, that in turn takes a dependency on Microsoft.UI.Xaml, the assemblies are correctly added and deployed to the app.
However, nuget won't run the .targets and .props files in the \build\ folder in indirectly referenced packages.
This means a user have to "magically" know that when referencing the library, he also have to manually add an explicit reference to Microsoft.UI.Xaml. If he doesn't the app won't run right. This can lead to a lot of headscratching and puts a lot of documentation responsibility by the library owner. In addition I believe it'll keep library owners from taking a dependency on Microsoft.UI.Xaml because it would effectively break existing apps until they add htis reference.

## Functional Requirements
The solution is rather simple: All you have to do is duplicate the \build\ folder to \buildTransitive\
The first folder is used when a package is directly referenced, and the second folder will be used when it is referenced indirectly.

## Important Notes
- Documentation of this feature: https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior
- Requires NuGet 5.x, which means it requires VS2019
- VS2017 users would still just need to directly reference MUX in their project heads.
- VS2017 might get this feature backported: https://github.com/NuGet/Home/issues/7961

**Comment by jevansaks** [comment]
Thanks for raising awareness of this new feature! We can take a look at doing this.

**Comment by dotMorten** [comment]
I _think_ you just need to duplicate the /build/ entries in the nuspec, but I couldn't for the life of me figure out how to generate a nuget package with your build scripts, so not entirely sure.

**Comment by dotMorten** [comment]
An alternative solution to this, is to not use `AppxPackageRegistration` to register the library, but use the more nuget-standard way of putting the native libraries in `runtimes\win10-x86\native\` folder of the nuget package, (and the winmd in the \lib\ folder). This entirely avoids the need for all the stuff the targets files does.

I can see how this saves you 2-3 mb in deployment using a shared app package if many apps uses the same library, but on the other hand, it seems to also introduce a set of complexities by not using the features that are already there in NuGet.

**Comment by dotMorten** [comment]
@rrelyea, @onovotny and @karann-msft might have some insights/ideas as well.

**Comment by karann-msft** [comment]
@jevansaks - I wanted to give a heads-up that build transitive only works with vs2019 onwards. Here is the issue tracking an ask to bring it to vs2017 - https://github.com/NuGet/Home/issues/7961

**Comment by jevansaks** [comment]
> An alternative solution to this that'll work with VS2017, is to not use `AppxPackageRegistration` to register the library

In addition to the appx savings for customers, the shared library has other benefits like for us to be able to push out bug fixes independent of apps. It's not common (yet) but it's something that we plan to continue to do. The nuget tooling for it isn't as automatic as just plain binaries, but maybe that's something that we can ask VS to make better in the future.

**Comment by dotMorten** [comment]
> maybe that's something that we can ask VS to make better in the future.

Since we can already do this in VS2019, that would only be useful if it got backported to VS2017. Then the best best is hoping for transitive builds to be backported.

**Comment by dotMorten** [comment]
If this is approved can I just make a PR to make this happen?

**Comment by jevansaks** [comment]
> If this is approved can I just make a PR to make this happen?

Absolutely! We have 2 nuspecs that matter, one for prerelease (dll-based) and release (framework package-based) nupkgs:

* MUXControls.nuspec
* MUXControlsFrameworkPackage.nuspec

Which parts of the targets need to go into "buildTransitive"? Is there documentation that clarifies the need for this? @karann-msft ?

**Comment by dotMorten** [comment]
The way usually do it is just copy the build folder to buildTransitive right before packaging.

**Comment by onovotny** [comment]
You can probably do it with a None include, set the PackagePath and set Pack to true.  We do this in Refit, no copying.

**Comment by dotMorten** [comment]
@onovotny this project doesn't appear to be packaging using the Pack target. Otherwise I agree
