### ISSUE TITLE
Sliding Thumb in ListView moves faster than the pointer

### ISSUE THREAD

**Issue by nxtn-staged** [microsoft/microsoft-ui-xaml#5967]
### Describe the bug

When dragged by the mouse from bottom to top, the sliding Thumb of the ScrollViewer in a ListView moves faster than the pointer and jumps to the top.

### Steps to reproduce the bug

1. Create a ListView with a large number of items.
2. Modify the layout properties, e.g., Height, of controls in the ItemTemplate.
3. Drag the sliding Thumb from bottom to top.

```xaml
<Page
    x:Class="Test.Universal.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <ListView ItemsSource="{x:Bind items}">
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="x:String">
                <TextBlock Height="100" Text="{x:Bind}" />
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
</Page>
```

```cs
using System.Linq;
using Windows.UI.Xaml.Controls;

namespace Test.Universal
{
    public sealed partial class MainPage : Page
    {
        private readonly string[] items;

        public MainPage()
        {
            items = Enumerable.Range(1, 5000).Select(i => i.ToString()).ToArray();

            InitializeComponent();
        }
    }
}
```

### Expected behavior

The ListView scrolls slower and the sliding Thumb exactly follows the pointer.

### Screenshots

![](https://user-images.githubusercontent.com/79820545/134759153-d021300c-fac6-420c-b7ee-8fcb5c4066bb.gif)

### NuGet package version

Microsoft.UI.Xaml 2.6.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

This doesn't reproduce if you change the item count from 5000 to 1000000...

**Comment by StephenLPeters** [comment]
@RBrid is this a known issue? looks like the thumb position isn't applying the layout property when it does it calculations?
