### ISSUE TITLE
Applying "Style" to UI element it returns to its an old view

### ISSUE THREAD

**Issue by steam3d** [microsoft/microsoft-ui-xaml#5969]
### Describe the bug

When applying "Style" to any UI element it returns to its an old appearance. I have installed **Microsoft.UI.Xaml 2.7.0**
There is the toggle switch:
```
<Page
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls">
    ...
    <ToggleSwitch Style="{ThemeResource ToggleSwitch}" Header="Switch"/>
    ...
</Page>
```
And it's style:
```
<ResourceDictionary
    ...
    <Style TargetType="ToggleSwitch" x:Key="ToggleSwitch">
        <Setter Property="Margin" Value="0,16,16,0"/>
    </Style>
    ....
</ResourceDictionary>
```
It's looks like:
![image](https://user-images.githubusercontent.com/30986874/134785164-be333141-8607-4e2a-87bd-731c83548bf3.png)
There is default toggle switch style instead of Microsoft.UI.Xaml 2.7.0 style

Delete the style will change the will change the appearance of the toggle switch
```
<Page
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls">
    ...
    <ToggleSwitch Header="Switch"/>
    ...
</Page>
```
It will look like:
![image](https://user-images.githubusercontent.com/30986874/134785258-8d760a5b-d489-4927-a1fa-8cb30c452664.png)

There is unexpected behavior because "Style" does not change any "appearance" just change Margin.
Sample project: [UiTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7231359/UiTest.zip)
### Steps to rep

roduce the bug

1. Create toggle switch
2. Apply any style

### Expected behavior

The UI element must have the same Microsoft.UI.Xaml 2.7.0 style appearance

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by niels9001** [comment]
Have you set the ControlsResourceVersion to 2 in App.xaml?

**Comment by steam3d** [comment]
@niels9001 Yes.
`<XamlControlsResources ControlsResourcesVersion="Version2" xmlns="using:Microsoft.UI.Xaml.Controls" />`

**Comment by StephenLPeters** [comment]
@eugenegff is correct, what is happening is your custom style is being merged with the metadata defined default style, which for controls not published in the Winui2 nuget package is the style included in system xaml.  In order to avoid this you need your custom style to be BasedOn the style included in Winui2's package.

**Comment by steam3d** [comment]
@eugenegff I got the unhandled exception.  
> Unhandled exception at 0x00007FFFF9DABE3E (KernelBase.dll) in UiTest.exe: 0xC0000602:  A Fail Fast exception occurred. Exception handlers will not be called, the process will terminate immediately.

![image](https://user-images.githubusercontent.com/30986874/135146844-59664f74-8329-43b8-86cf-a2c58cea677d.png)

A change style to:
`    <Style TargetType="ToggleSwitch" x:Key="ToggleSwitch" BasedOn="{StaticResource DefaultToggleSwitchStyle}">
        <Setter Property="Margin" Value="0,16,16,0"/>
    </Style>
`

**Comment by steam3d** [comment]
But if i add any second style:
```
    <Style TargetType="ToggleSwitch" x:Key="ToggleSwitch" BasedOn="{StaticResource DefaultToggleSwitchStyle}">
        <Setter Property="Margin" Value="0,16,16,0"/>
    </Style>

    <Style TargetType="TextBox" x:Key="Txt" BasedOn="{StaticResource DefaultTextBoxStyle}">
        <Setter Property="Foreground" Value="Blue"/>
    </Style>
```

Everything works fine. But it seems to me that this is not the right behavior.

**Comment by steam3d** [comment]
But if i add any second style:
```
    <Style TargetType="ToggleSwitch" x:Key="ToggleSwitch" BasedOn="{StaticResource DefaultToggleSwitchStyle}">
        <Setter Property="Margin" Value="0,16,16,0"/>
    </Style>

    <Style TargetType="TextBox" x:Key="Txt" BasedOn="{StaticResource DefaultTextBoxStyle}">
        <Setter Property="Foreground" Value="Blue"/>
    </Style>
```

Everything works fine. But it seems to me that this is not the right behavior.

**Comment by steam3d** [comment]
But if i add any second style:
```
    <Style TargetType="ToggleSwitch" x:Key="ToggleSwitch" BasedOn="{StaticResource DefaultToggleSwitchStyle}">
        <Setter Property="Margin" Value="0,16,16,0"/>
    </Style>

    <Style TargetType="TextBox" x:Key="Txt" BasedOn="{StaticResource DefaultTextBoxStyle}">
        <Setter Property="Foreground" Value="Blue"/>
    </Style>
```

Everything works fine. But it seems to me that this is not the right behavior.
