### ISSUE TITLE
NavigationView : Switching pane visibility cause Unhandled Exception

### ISSUE THREAD

**Issue by glanium** [microsoft/microsoft-ui-xaml#5971]
### Describe the bug

Switching pane visibility cause Unhandled Exception only when PaneDisplayMode is not Top.

When PaneDisplayMode is Top, no Exception occurs.

### Steps to reproduce the bug

just switch pane visibility

NavigationView.IsPaneVisible = !NavigationView.IsPaneVisible;

Thats all.

### Expected behavior

no exception

### NuGet package version

Microsoft.UI.Xaml 2.6.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Microsoft.UI.Xaml 2.7.0

**Comment by StephenLPeters** [comment]
@glanium can you f5 to continue the application? Is there any info in the exception?

**Comment by glanium** [comment]
> can you f5 to continue the application? Is there any info in the exception?
no.
System.ArgumentException


It's easy to reproduce this issue.
Just create empty project.
install winui package.

copy and paste following code

```xml

<Page
    x:Class="NavViewApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NavViewApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <winui:NavigationView
        x:Name="navView">

        <Button
            Content="push"
            Click="Button_Click"/>

    </winui:NavigationView>
</Page>

```


```csharp
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            navView.IsPaneVisible = !navView.IsPaneVisible;
        }

```


That's all.

**Comment by nickrandolph** [comment]
@StephenLPeters thanks for adding this to the 2.7.1 milestone - any idea what's causing this exception and is there a workaround to prevent it happening (in the absence of an actual fix)?

**Comment by StephenLPeters** [comment]
Not yet, we'll need to investigate when the schedule permits.

**Comment by karenbtlai** [comment]
> @StephenLPeters thanks for adding this to the 2.7.1 milestone - any idea what's causing this exception and is there a workaround to prevent it happening (in the absence of an actual fix)?

I'm investigating this issue now.

**Comment by HppZ** [comment]
I think this is related：https://github.com/microsoft/microsoft-ui-xaml/issues/5892

**Comment by ranjeshj** [comment]
@glanium @nickrandolph @HppZ This does look like a debug only issue when under the debugger. 

This seems to be the code triggering it. You can try setting DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION to skip it.
```
#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };
#endif
```
