### ISSUE TITLE
Appx publish for sideloading doesn't copy the WinUI 2.x framework package in the right folder

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#5972]
### Describe the bug

When a C# app references a C++ Windows Runtime component that has a dependency on WinUI 2.x, in x86 configuration the framework package for WinUI 2.x is copied to the Win32 folder during publishing for side-loading instead of the x86 folder. If the C# app also references WinUI 2.x, then it's copied twice (1 in the Win32 folder and another in the x86 folder).

### Steps to reproduce the bug

1. Create a C# UWP app and install WinUI 2.x through NuGet.
2. Create a C++ WinRT component and install WinUI 2.x through NuGet.
3. Add a project reference to the component from the app.
4. Right click, select publish->create app package, select sideload and follow the instructions.
5. Look inside the AppPackages/<package name>/Dependencies.

### Expected behavior

It shouldn't be copied twice.

### NuGet package version

Microsoft.UI.Xaml 2.6.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@jevansaks is this expected? seems like a valuable bug to track down.

**Comment by jevansaks** [comment]
@StephenLPeters I can guess why it's happening (see build\NuSpecs\MUXControls-Nuget-FrameworkPackage.props for the Win32 + x86 sections and the comment as to one being for C# and the other being for C++/CX). 

@Jaiganeshkumaran what is the *problem* this presents? Having extra copies in the sideload folder seems harmless.

**Comment by Jaiganeshkumaran** [comment]
@jevansaks Sometimes I'm getting a duplicate entry error while packaging the application.

**Comment by jevansaks** [comment]
> @jevansaks Sometimes I'm getting a duplicate entry error while packaging the application.

@Jaiganeshkumaran  even after changing your CX project to use x86 in place of Win32?
