### ISSUE TITLE
ItemsRepeater applying weird arranging behaviour to content when parent's ScrollViewer "HorizontalScrollBarVisibility" is set to "Visible".

### ISSUE THREAD

**Issue by DilanBoskan** [microsoft/microsoft-ui-xaml#5974]
### Describe the bug

When you create an ItemsRepeater and fill the content with differently width sized elements, the alignement of those elements is completely messed up, when you place a ScrollViewer as the parent of the ItemsRepeater and set the ScrollViewers HorizontalScrollBarVisibility to "Visible" or "Hidden" or "Auto" (_Everything but "Disabled"_).

Setting HorizontalAlignment of the Rectangles to "Center" does not help.

### Steps to reproduce the bug

1. Create a new UWP Solution
2. Install Microsoft.UI.Xaml via Nuget
3. In App.xaml replace with the following code:
```xaml
<Application
    x:Class="ItemsRepeaterFix.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:ItemsRepeaterFix">
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>
</Application>
```
4. In MainPage.xaml replace with the following code:
```xaml
<Page
    x:Class="ItemsRepeaterFix.MainPage"
    x:Name="PageElement"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:ItemsRepeaterFix"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <muxc:ItemsRepeaterScrollHost>
            <ScrollViewer ZoomMode="Enabled" HorizontalScrollBarVisibility="Auto">
                <muxc:ItemsRepeater ItemsSource="{Binding ElementName=PageElement, Path=WidhtList}" HorizontalAlignment="Center">
                    <muxc:ItemsRepeater.Layout>
                        <muxc:StackLayout Orientation="Vertical" Spacing="15" ></muxc:StackLayout>
                    </muxc:ItemsRepeater.Layout>

                    <muxc:ItemsRepeater.ItemTemplate>
                        <DataTemplate x:DataType="x:Double">
                            <Rectangle Fill="Green" Width="{Binding}" Height="300"></Rectangle>
                        </DataTemplate>
                    </muxc:ItemsRepeater.ItemTemplate>
                </muxc:ItemsRepeater>
            </ScrollViewer>
        </muxc:ItemsRepeaterScrollHost>
    </Grid>
</Page>
```
5. In MainPage.xaml.cs replace with the following code:
```cs
public sealed partial class MainPage : Page {
        public List<double> WidhtList { get; set; } = new List<double>() {
            500,
            500,
            500,
            1000,
            500,
            500,
            500,
        };
        public MainPage()
        {
            this.InitializeComponent();
        }
}
```

### Expected behavior

All the rectangles are always aligned to the center of the screen and do not jump around.

### Screenshots

![image](https://user-images.githubusercontent.com/63150890/134806289-61f44b60-634a-4eed-878f-efb99c9e21a6.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [x] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

If this is not a bug, I would incredibly appreciate a short guide on how to fix this issue.

**Comment by DilanBoskan** [comment]
Including test solution.
[ItemsRepeaterFix.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7231344/ItemsRepeaterFix.zip)

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by ranjeshj** [comment]
looks like a bug in stack or flyoutlayout algorithm when the non virtualizing direction does not have a finite size.

**Comment by DilanBoskan** [comment]
Just to mention it again:

This bug **only** occurs, when the virtualizing layout is wrapped around a ScrollViewer on which its HorizontalScrollBarVisibility property is set everything **but** "Disabled".

Would incredibly appreciate a fix in the upcoming weeks/months.

**Comment by StephenLPeters** [comment]
@chingucoding does this ring any bells?

**Comment by chingucoding** [comment]
Unfortunately not, seems new to me @StephenLPeters.

**Comment by DilanBoskan** [comment]
Any updates or workarounds on this issue? This is a severe bug and should at the very least be acknowledged as one.

**Comment by StephenLPeters** [comment]
Definitely a bug, we haven't had time to prioritize it yet though.

**Comment by DilanBoskan** [comment]
I really hope that this issue will be resolved in the coming months. It is crucial for the development and then publishment of my app.
Would appreciate anyone who knows this framework better than me to take a look at this.

**Comment by DilanBoskan** [comment]
@kmahone Why was this removed from the Milestone? It has not been fixed from what I know and it is a basic/fundamental feature that does not work as intended.

**Comment by DilanBoskan** [comment]
@StephenLPeters Is there a way someone can get a look into that? I beg you, I really need this issue resolved.

**Comment by DilanBoskan** [comment]
@kmahone Alright thank you for the comment on the issue.

First of all, I do need the virtualization as my items are quite resource intensive. However, in my situation, I do know the maximum width of the elements in the ItemsRepeater so I was able to solve the issue based on your suggestion to set the width of the ItemsRepeater to the maximum width of the element in the collection, thank you.

I wonder how this would be solved if the maximum width of the elements where not known, say when loading images for example. The ItemsRepeater is obviously not supposed to behave in that situation as it does currently. Something is going wrong with the arranging of the elements.

**Comment by kmahone** [comment]
Since there is a workaround I am going to close this. Without knowing the largest width ahead of time it is difficult to make this work without breaking virtualization.
