### ISSUE TITLE
Unexpected AppBarButton.Unloaded is triggered when change the CommandBar width

### ISSUE THREAD

**Issue by lyf6lyf** [microsoft/microsoft-ui-xaml#5976]
### Describe the bug

When we change the width of a `CommandBar`, the `Unloaded` event of the inner `AppBarCommand` is triggered. But in reality, the button is still connected to the main object tree, and its `IsLoaded` is still true.
It also makes the `Behavior.OnDetaching` is called when we attached a behavior to the button.

### Steps to reproduce the bug

1. We have below code
``` xaml
        <CommandBar DefaultLabelPosition="Right" IsOpen="False">
            <AppBarButton Icon="Add" Label="a very long button text. a very long button text. a very long button text." />
            <AppBarButton
                x:Name="button"
                Icon="Share"
                Label="Share" />
            <AppBarButton Icon="Remove" Label="Remove" />
            <AppBarButton Icon="Remove" Label="Remove" />
            <AppBarButton Icon="Remove" Label="Remove" />
            <AppBarButton Icon="Remove" Label="Remove" />
            <AppBarButton Icon="Remove" Label="Remove" />
            <CommandBar.SecondaryCommands>
                <AppBarButton Icon="Setting" Label="Settings" />
            </CommandBar.SecondaryCommands>
        </CommandBar>
```
``` csharp
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            InitializeComponent();
            button.Loaded += OnLoaded;
            button.Unloaded += OnUnloaded;
        }

        private void OnUnloaded(object sender, RoutedEventArgs e)
        {
            Debug.WriteLine($"button {sender.GetHashCode()} unloaded event, isLoaded: {button.IsLoaded}");
        }

        private void OnLoaded(object sender, RoutedEventArgs e)
        {
            Debug.WriteLine($"button {sender.GetHashCode()} loaded event, isLoaded {button.IsLoaded}");
        }
    }
```
2. start the app, then change the window width. 
3. We can see in the Output window:
>button 51192825 loaded event, isLoaded True
...
button 51192825 loaded event, isLoaded True
button 51192825 unloaded event, isLoaded: True
button 51192825 loaded event, isLoaded True
button 51192825 unloaded event, isLoaded: True

### Expected behavior

The Unloaded event should not be triggered. 

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (22460.1000)

**Comment by kmahone** [comment]
There are known issues with Loading/Loaded/Unloaded events. I think what is happening here is that as part of the resize, the buttons are getting removed and re-added to the appbar in a single frame which causes the incorrect behavior for these events. This can result in the Unloaded event being raised incorrectly.

As a work-around, the best thing to do is to check the IsLoaded property in the Unloaded event handler to determine if the element has truly been removed from the tree.

The underlying issue is tracked by: #1900
