### ISSUE TITLE
Frame/Page create a cycle that leaks

### ISSUE THREAD

**Issue by MikeHillberg** [microsoft/microsoft-ui-xaml#598]
**Describe the bug**
Navigating a Frame to a Page make thes the Page a child of the Frame, but also sets a back link from the Page to the Frame (for the Page.Frame property). This creates a cycle.

In a typical Xaml app, there's a Frame set as Window.Current.Content. During Window teardown, the Frame releases the Page, which destructs and release the Frame, which can now too destruct. But if you just change the Window.Content away from the Frame, the cycle keeps the Frame and Page from ever going away, causing a leak.

**Steps to reproduce the bug**

Create a C++/WinRT application with a Button, and in the click handler handler run:

```C++
Window::Current().Content(nullptr);
```

This should cause the MainPage to destruct, but doesn't. Running this code _does_ cause it to destruct:

```C++
Frame().Navigate(xaml_typename<Page>());
```

**Expected behavior**
Both of the above should cause the page to be destructed.

**Comment by jevansaks** [comment]
You're saying that internal to Page it has a strong link to its owning Frame? If that's the case, yes we should not do that.

**Comment by MikeHillberg** [comment]
Yes, Page has a strong link to the parent Frame.
