### ISSUE TITLE
Unable to override CommandBar's MoreButton "EllipsisButton" style

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#5980]
### Describe the bug

I want to override the style of the `CommandBar`'s "more button". This button is using the `EllipsisButton` style but overriding this style does not have any effect.

### Steps to reproduce the bug

Use the following code and start the app.
```xml
<Page [...]>
    <Page.Resources>
        <Style x:Key="EllipsisButton" TargetType="Button">
            <Setter Property="Foreground" Value="Red" />
            <Setter Property="BorderThickness" Value="4" />
            <Setter Property="BorderBrush" Value="Red" />
        </Style>
    </Page.Resources>

    <Grid>
        <CommandBar DefaultLabelPosition="Right">
            <AppBarButton Icon="Accept" Label="Action 1" />
            <AppBarButton Icon="Account" Label="Action 2" />

            <CommandBar.SecondaryCommands>
                <AppBarButton Icon="Add" Label="Action 3" />
                <AppBarButton Icon="AddFriend" Label="Action 4" />
            </CommandBar.SecondaryCommands>
        </CommandBar>
    </Grid>
</Page>
```

The "more button" content should be red and it should have a big red border.

### Expected behavior

The custom style should be applied to the "more button"

### Screenshots

![image](https://user-images.githubusercontent.com/20152272/134934753-cd30c022-134e-4024-8eba-797bb2f791f8.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by StephenLPeters** [comment]
In order to support this, because of how the different peices of winui2 and system xaml sit together, this line https://github.com/microsoft/microsoft-ui-xaml/blob/66c3ec3c4a96f4ddfe8d5ed90b4dbfd2c572bcc4/dev/CommonStyles/CommandBar_themeresources.xaml#L873 needs to be changed to a {ThemeResource} lookup.

**Comment by chingucoding** [comment]
I would like to fix this.
