### ISSUE TITLE
fully transparency in ClientRect area

### ISSUE THREAD

**Issue by LigaLiao** [microsoft/microsoft-ui-xaml#5984]
In the case of using MFC：SetLayeredWindowAttributes(RGB(255, 255, 255), 0, LWA_COLORKEY);
but, in the WinUI, This doesn't work.

**Comment by StephenLPeters** [comment]
@codendone FYI.

I believe full transparency is not supported.

**Comment by codendone** [comment]
WinUI doesn't use GDI rendering, which is what SetLayeredWindowAttributes with LWA_COLORKEY affects. So indeed that API doesn't work with WinUI.

There are some requests on the backlog for WinUI 3 to support transparent window rendering, such as #1247 and #2956. There is no ETA for that currently.
