### ISSUE TITLE
BreadcrumbBar : OneWay binding does not work at all

### ISSUE THREAD

**Issue by glanium** [microsoft/microsoft-ui-xaml#5986]
### Describe the bug

OneWay binding to ItemsSource property doest not work all.

### Steps to reproduce the bug

Create empty project.
Copy and paste following code.

```xml

<Page
    x:Class="BreadcrumbBarApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:BreadcrumbBarApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <StackPanel>
        <Button
            Content="Push"
            Click="Button_Click"/>
        <winui:BreadcrumbBar
            ItemsSource="{Binding Path=Items, Mode=OneWay}"/>
        <ListView
            ItemsSource="{Binding Path=Items, Mode=OneWay}"/>

    </StackPanel>
</Page>

```

```csharp

    public class ViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private List<int> m_items = new List<int>();
        public ViewModel()
        {
            Change();
        }                           
        public List<int> Items
        {
            get => m_items;
            private set
            {
                m_items = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Items)));
            } 
        }
        public void Change()
        {
            var r = new Random();
            var newItems = new List<int>();
            for (var i = 0; i < 10; i++)
                newItems.Add(r.Next());
            Items = newItems;
        }
    }

    public sealed partial class MainPage : Page
    {
        private ViewModel m_viewModel = new ViewModel();
        public MainPage()
        {
            this.InitializeComponent();
            DataContext = m_viewModel;
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            m_viewModel.Change();
        }
    }

```

Push the button.

### Expected behavior

OneWay binding to ItemsSource property  work.

### NuGet package version

Microsoft.UI.Xaml 2.6.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Microsoft.UI.Xaml 2.7.0

**Comment by ranjeshj** [comment]
Do you get any error if you hook to [BindingFailed ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.debugsettings.bindingfailed?view=winrt-20348) event ? 

In your case you might want to make the Items list an ObservableCollection so you don't have to reset the entire collection every time.

**Comment by glanium** [comment]
> Do you get any error if you hook to [BindingFailed ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.debugsettings.bindingfailed?view=winrt-20348) event ?

no binding error



> In your case you might want to make the Items list an ObservableCollection so you don't have to reset the entire collection every time.

yes. i know workaround but what i wanna know is whether this is bug or not??

thx.

**Comment by ranjeshj** [comment]
This is a bug. When the ItemsSource property is changed the BreadcrumbBar's Repeater's itemssource is not updated. It is only updated here - https://github.com/microsoft/microsoft-ui-xaml/blob/4283cb89e0c8b63ac011e8d46a81a79b6accdc45/dev/Breadcrumb/BreadcrumbBar.cpp#L166 when the collection changes.

**Comment by chingucoding** [comment]
I would like to take a look at this.
