### ISSUE TITLE
The Popup doesn't have the ActualHeight when opened

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#5988]
### Describe the bug

Hi, I've subscribed to the popup's Opened event, and the popup's ActualHeight is 0 in the handler. The ActualWidth has an expected value (615 instead of 100)

### Steps to reproduce the bug

```xaml
        <StackPanel>
            <Button Content="ShowPopup" Click="Button_Click"/>
            <Popup x:Name="popup">
                <Border Background="Red" Width="100" Height="100"/>
            </Popup>
        </StackPanel>
```
```csharp
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
        }

        bool isFirst = true;
        private void Button_Click(object sender, RoutedEventArgs e) {
            if(isFirst) {
                isFirst = false;
                popup.Opened += Popup_Opened;
                popup.SizeChanged += Popup_SizeChanged;
            }
            popup.IsOpen = !popup.IsOpen;
        }

        void Popup_SizeChanged(object sender, SizeChangedEventArgs e) => Debug.WriteLine($"Popup_SizeChanged. Size: {popup.ActualWidth} {popup.ActualHeight}");
        void Popup_Opened(object sender, object e) => Debug.WriteLine($"Popup_Opened. Size: {popup.ActualWidth} {popup.ActualHeight}");
    }
```
To see a size look at the screenshot

### Expected behavior

The popup's ActualWidth\Height should correspond with the real size of its content.

### Screenshots

![image](https://user-images.githubusercontent.com/47348109/135129381-51b8ce40-c4a6-41c4-8915-f3cc80e7b698.png)

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by alexdi220** [comment]
I tried several events - Opened, Loaded, SizeChanged (doesn't raised), EffectiveViewportChanged (doesn't raised). But don't found a way to get the actual size of the popup.

**Comment by ranjeshj** [comment]
@llongley ?

**Comment by llongley** [comment]
@alexdi220 Popup is a bit of a weird control in that it functions by putting its content into a separate visual tree.  Try retrieving ActualWidth and ActualHeight of Popup.Child instead of Popup itself, I think that might get you what you want.

**Comment by alexdi220** [comment]
Thanks, @llongley. I've already done it. But it depends) For the sample, the popup's child has no ActualSize on Popup.Opened.  So I was forced to subscribe\unsubribe the child's EffectiveViewPortChanged on Opened\Closed event. It's necessary to raise the quality of that. Because the popup is the base component for all drop-downs and menus.

ps: I'm worried about the whole quality of WinUI components. For the last two weeks, I've found tens of bugs in basic scenarios. Some were posted here or found WA. It's a weird feeling when I start a new feature, I don't know what will happen, what traps still waiting for me. I have no assurance that WinUI will work as expected.
