### ISSUE TITLE
Announcing the release of WebView2 in the pre-release version of WinUI2.8

### ISSUE THREAD

**Issue by predavid** [microsoft/microsoft-ui-xaml#5989]
# Announcing WebView2 in the pre-release version of WinUI2.8 

Back in August we released WebView2 in the WinUI2.7 pre-release. Since then we have fixed some bugs. Most significantly, with the version of WebView2 in this WinUI2.8 pre-release, you will be able to publish your apps to the Store. 

## Installation information
For installation information and known issues see [here](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.8.0-prerelease.210927001)

## What's next?
We will be working on addressing the issues/bugs you file and getting WebView2 ready for release in upcoming stable(non-pre-release)versions of WinUI2.x

**Comment by radujipa** [comment]
@predavid It's great to see WV2 back in this prerelease! 🚀 

Do please prioritise fixing the mechanisms for projecting WinRT APIs through the WebView to the Web as it's one of the main ways to provide deep platform intergrations. 🙏 

- https://github.com/MicrosoftEdge/WebView2Feedback/issues/5
- https://github.com/MicrosoftEdge/WebView2Feedback/issues/1416
- https://github.com/MicrosoftEdge/WebView2Feedback/issues/1702

**Comment by predavid** [comment]
@radujipa - thank you for the list Issues . @champnic and @david-risney - I believe these are Issues you are already tracking on your side.

**Comment by champnic** [comment]
@radujipa Yup! We're currently working on delivering this support.
