### ISSUE TITLE
SymbolThemeFontFamily not working?

### ISSUE THREAD

**Issue by niels9001** [microsoft/microsoft-ui-xaml#5992]
### Describe the bug

It seems that using {ThemeResource SymbolThemeFontFamily} does not provide the expected result when using it for e.g. TextBlock or FontIcon.

### Steps to reproduce the bug

```
<StackPanel>
   <TextBlock Text="&#xE713;" FontFamily="{ThemeResource SymbolThemeFontFamily}" /> <!-- Uses MDL2 -->
   <FontIcon Glyph="&#xE713;" FontFamily="{ThemeResource SymbolThemeFontFamily}" /> <!-- Uses MDL2 -->
   <FontIcon Glyph="&#xE713;" /> <!-- Uses Fluent -->
</StackPanel>
```

### Expected behavior

I'd expect all of the above to look the same. When using {ThemeResource SymbolThemeFontFamily} it should:

- Use Segoe MDL2 Assets on Windows 10
- Use Segoe Fluent Icons on Windows 11
- The same behavior for FontIcon and TextBlock when setting the FontFamily to SymbolThemeFontFamily

### Screenshots

![image](https://user-images.githubusercontent.com/9866362/135239012-0050f87c-0aba-4e80-8141-01e67136ba5a.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Is there any documentation on what we should expect on what platform? Ideally I'd like to use Segoe Fluent Icons at all time (if it's installed), regardless if it's Windows 10 or Windows 11.

**Comment by ranjeshj** [comment]
@niels9001 SymbolThemeFontFamily maps to Fluent icons in win11 and mdl2 in win10. Are you seeing  mdl2 on win11 ? @licanhua  @codendone  @chigy  as FYI

**Comment by niels9001** [comment]
> @niels9001 SymbolThemeFontFamily maps to Fluent icons in win11 and mdl2 in win10. Are you seeing  mdl2 on win11 ? @licanhua  @codendone  @chigy  as FYI

That is correct. The above screenshot was taken on a Windows 11 machine in an UWP app.

**Comment by licanhua** [comment]
If it's UWP app, please check Target Platform Version and MaxTestedVersion in the project file: set targetplatformversion to latest Windows 11 SDK. Also check your MaxTestedVersion and set it to a very big number.

**Comment by niels9001** [comment]
@licanhua But why does a FontIcon use Fluent Icons when NOT setting SymbolThemeFontFamily explicitly? That does not seem logical to me.


```
<StackPanel>
   <TextBlock Text="&#xE713;" FontFamily="{ThemeResource SymbolThemeFontFamily}" /> <!-- Uses MDL2 -->
   <FontIcon Glyph="&#xE713;" FontFamily="{ThemeResource SymbolThemeFontFamily}" /> <!-- Uses MDL2 -->
   <FontIcon Glyph="&#xE713;" /> <!-- Uses Fluent -->
</StackPanel>
```

**Comment by licanhua** [comment]
@niels9001 Does it fix your problem?
FontIcon is implemented in Windows. To provide backward compatibility, windows has if/else logic to choose the default fontfamily depends on your app setting. If your app is targeting Windows 10, it use MDL2, if your app is targeting Windows 11, it use FluentIcons.
@ranjeshj We need to update the document to make WinUI 2.7 user to pay attention to target platform version and maxtestedversion, and use latest SDK when building the app
