### ISSUE TITLE
After updating to version 2.0.181011001, the appbarbutton reveal border only covers a part of the control

### ISSUE THREAD

**Issue by lhak** [Microsoft/microsoft-ui-xaml#6]
After updating the WinUI library to the version mentioned in the title, the following markup:

```xaml
<CommandBar DefaultLabelPosition="Collapsed">
	<CommandBar.PrimaryCommands>
		<AppBarButton Icon="Add" Label="Add"/>
	</CommandBar.PrimaryCommands>
</CommandBar>
```
leads to the reveal border only partially covering the button:

![image](https://user-images.githubusercontent.com/38145893/47034765-8a37e600-d178-11e8-9cb1-3c362ae0421a.png)

with the previous WinUI version it looked like this:

![image](https://user-images.githubusercontent.com/38145893/47034807-9fad1000-d178-11e8-96de-cdcf0430e0aa.png)

This happens on Windows version 1809 (17763.55) and corresponding SDK. Please note that this styling issue also seems to appear without the WinUI library added to the project (it was fine on Windows version 1803 without WinUI) and that the older WinUI version was apparently able to fix it.

**Comment by jevansaks** [comment]
Thanks for your feedback! We have a fix pending for this but it was not included in this update. We should have an update published this week with the fix.

**Comment by lhak** [comment]
Thank you very much for the quick reply. This also seems to be an issue with the default platform styles on Windows 1809. Will it be fixed there as well?

**Comment by touseefbsb** [comment]
this is the best thing about winui library @jevansaks  we can get quick fixes in the platform controls this way, also it would be even faster if community can also actively contribute to the code, would that be possible soon?

**Comment by jevansaks** [comment]
We just pushed [https://www.nuget.org/packages/Microsoft.UI.Xaml/2.0.181018003](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.0.181018003) with a fix. Can you try that?

**Comment by jevansaks** [comment]
@touseefbsb we're excited about it too! We are working on a plan for contributions. I will share more details about it when we're ready. For now we hope to be able to at least be more responsive to community issues and requests like this. Keep it coming!

**Comment by lhak** [comment]
I can confirm that the update has fixed this issue. Thank you very much. Please also fix the corresponding style in Windows as soon as possible because it is a really bad developer experience if the default styles are broken.

**Comment by jevansaks** [comment]
Absolutely. The fix should also be in a Windows Insider flight soon.
