### ISSUE TITLE
Window shouldn't release itself after going out of scope

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/microsoft-ui-xaml#6020]
### Describe the bug

The application crashes itself out of existance when I'm declaring `m_window` as a local variable in `App.xaml.cs` with an Access Denied exception, possibly due to COM-ref counting, and the window freeing itself.

### Steps to reproduce the bug

1. Create WinUI 3 Packaged Desktop App
2. Replace `m_window = new MainWindow()` with `var m_window = new MainWindow()`
And delete field `Window m_window;` in `App`.
4. Replace MainWindow content with repro project content
   - Add MenuBar with MenuBarItems and flyouts
   - Remove Button Click handler
5. Start Project
6. Open Flyout, observe crash
   - Hover over multiple items, will crash
   - Clicking the button accelerates crash on MenuBarItem flyout

### Expected behavior

I expect this to just work out of the box, non-referenced windows are a thing for app-development, and WinForms and WPF don't crash for this exact same scenario.
Migrating from WinForms or WPF to WinUI 3 with this issue is a road-block.

### Screenshots

Images, tell more than thousand words, a video demonstrating the issue:

https://user-images.githubusercontent.com/734738/135734617-721bfdfe-e5be-426a-918c-f07dc6dad587.mp4

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

 [  ] UWP
 [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Repro Project: [App3.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7272407/App3.zip)

**Comment by AliveDevil** [comment]
Just now seen https://github.com/microsoft/microsoft-ui-xaml/issues/5202#issuecomment-879585566.
If implemented I'll be happy to check this again and close this issue when it is resolved.

**Comment by Jaiganeshkumaran** [comment]
Then how will the object be deallocated? In WPF and Windows Forms, the main window is referenced by the Application class automatically so it will not be deallocated until it gets closed however that's not the case under WinUI 3.

**Comment by marb2000** [comment]
As @codendone commented, "your code needs to hold a reference to the new window or it will get released and go away." 
Unfortunately, per the current plan, this won't be fixed on 1.0 Stable, and it was moved to 1.1 when WinUI supports multi-window properly.
