### ISSUE TITLE
Windows App SDK no alternative for communitytoolkit.winui.ui.animations

### ISSUE THREAD

**Issue by tinmac** [microsoft/microsoft-ui-xaml#6029]
**Describe the bug**
In Windows App SDK there is no alternative Nuget package for Project Reunions **communitytoolkit.winui.ui.animations** which is required in NavigationService.cs (see steps below)

**Steps to reproduce the bug**
- Create a new project using Windows Template Studio --> WinUI 3 in Desktop 
- _the project uses Project Reunion 0.8.0 by default_ **not** _Windows App SDK_
- Convert the project to use Windows App SDK following using the instructions [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/update-existing-projects-to-the-latest-release)

**Expected behavior**
The poroject should run using Windows App SDK but instead we see the following error in NavigationService.cs

![image](https://user-images.githubusercontent.com/6616946/135896469-4c5c4acf-c2df-49d5-9d37-3595d6b686a7.png)

NuGet package version: 
Microsoft.WindowsAppSDK 1.0.0-experimental1

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

**Comment by michael-hawker** [comment]
@tinmac this should be resolved now? We shipped `7.1.2` of the toolkit supporting the `1.0.0` release of the WinAppSDK. I believe template studio has updated since then?
