### ISSUE TITLE
The corner of CommandBarFlyout will no longer rounded when closing

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#6034]
### Describe the bug

The corner of CommandBarFlyout will no longer rounded when closing

### Steps to reproduce the bug

1. Create a new CommandBarFlyout without PrimaryCommand
2. Pop it

### Expected behavior

Should have round corner

### Screenshots

![GIF 2021-10-5 10-54-03](https://user-images.githubusercontent.com/42038175/135953129-373b68b6-2296-4c4f-97ae-54d322babfe5.gif)

### NuGet package version

Microsoft.UI.Xaml 2.5.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@zhuxb711 this issue appears to be fixed in the latest versions of winui2.
