### ISSUE TITLE
NavigationView localization within XAML

### ISSUE THREAD

**Issue by JosHuybrighs** [microsoft/microsoft-ui-xaml#6035]
### Describe the bug

It seems not to be possible to use x:Uid based localization for NavigationViewItems in XAML.
I am using Project.Reunion 0.8.4 in a WinUI3 desktop app and are getting XAML parsing errors when doing the following in XAML:

```
<NavigationView x:Name="NavView">
      <NavigationView.FooterMenuItems>
        <NavigationViewItem x:Uid="MP-Import" Tag="Import" Content="Import" ToolTipService.ToolTip="Import photos and videos">
          <NavigationViewItem.Icon>
            <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE8B5;"/>
          </NavigationViewItem.Icon>
        </NavigationViewItem>
      </NavigationView.FooterMenuItems>
      ...
    </NavigationView>
```
When I remove the x:Uid attribute everything works well but then of course there is no translation in one of the available resource languages.

I can probably overcome this by setting up the items in code behind, but it still seems to be a bug.

### Steps to reproduce the bug

Create NavigationView in XAML and configure x:Uid attributes for each navigation item.

### Expected behavior

Both 'Content' and 'ToolTipService.ToolTip' should be localized.

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by evelynwu-msft** [comment]
@JosHuybrighs You cannot use x:Uid to set properties that are also being set directly in the markup. Can you try removing the `Content` and `ToolTipService.ToolTip` attributes from your markup snippet?
