### ISSUE TITLE
How to render content of Control object?

### ISSUE THREAD

**Issue by alex-aparin** [microsoft/microsoft-ui-xaml#6036]
I want to create lightweight custom control, which will only render its content in specific way (without any additional logic like mouse/key handling etc). I think that it will be derived from Control class. But I cannot understand the rendering model of Win UI 3. How can I redefine painting of control? Where can I find good description how rendering is performed within Win UI 3. P.S. due documentation, I guess that it uses similar model like WPF (but it is only my suspiction)

**Comment by llothar** [comment]
I hope we get this answered with documentation link and sample code. 

The main difference is that it is now a retained drawing model where you don't redefine painting (thats only for backward compatibility and i would guess slower than the new native way) but setup composition drawing items which are keept in a scene graph.  I currently port my Linux version from GTK3 -> GTK4 which is doing the same step as WinUI3 and it's all far from easy and self explaining. Especially when it comes to hand optimized drawing.
