### ISSUE TITLE
MicaController should be removed from public metadata

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6037]
It looks like the composition API [MicaController](https://docs.microsoft.com/windows/winui/api/microsoft.ui.composition.systembackdrops.micacontroller?view=winui-3.0-preview) is part of the public API in the latest preview, but I think this api is not meant for public consumption, so it should be removed from the public metadata

**Comment by nickrandolph** [comment]
Can the team at least confirm the status of this? Are these APIs shipping? If so, where's some basic "how to" documentation and why wasn't there any form of spec for it? If not, why are they there and again, where is the spec for whatever it is they're supposed to be for in the future?
@andrewleader calling out that shipping stuff without spec is yet another breach of the agreement for the team to be transparent with what's being worked on.
