### ISSUE TITLE
TogglePaneTopPadding Issue with border 

### ISSUE THREAD

**Issue by ElaJegen** [microsoft/microsoft-ui-xaml#6038]
### Describe the bug

Adding a border to the page that has NavigationView, removes the TogglePaneTopPadding. Due to the toggle button does not work as expected.

### Steps to reproduce the bug

My page xaml
<Page x:Class="WinUITestApp.MainPage" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:controls="using:Microsoft.UI.Xaml.Controls"> <controls:NavigationView  IsPaneToggleButtonVisible="True"/> </Page>

My code for the title bar

var coreTitleBar = CoreApplication.GetCurrentView().TitleBar; coreTitleBar.ExtendViewIntoTitleBar = true;

### Screenshots

First image : without border with TogglePaneTopPadding
<img width="601" alt="2" src="https://user-images.githubusercontent.com/91984487/136085746-4f64bfef-f6bf-43d8-bdd5-036d6be08b35.PNG">
g.
Second Image: with border but no top padding
<img width="602" alt="1" src="https://user-images.githubusercontent.com/91984487/136086495-80112f31-cf17-4a6b-8ade-530350d4508a.PNG">
g!

### Windows app type

- [X] UWP
- [ ] Win32

**Comment by StephenLPeters** [comment]
I think this is the same as https://github.com/microsoft/microsoft-ui-xaml/issues/2
