### ISSUE TITLE
👨‍💻☎ [Cancelled] WinUI Community Call: October 20, 2021

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#6050]
### Instead of a live Q&A, we'll be answering your questions posted here, For additional questions, please feel free to open up separate issues for them on the repo.

----

~~Please join us for the October 2021 edition of the WinUI Community Call. This event will be live-streamed to YouTube at the following link:~~
~~https://youtu.be/h4apI79wt4o~~

# Details
Date: October 20, 2021
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

# Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. In this month's call, we'll be sharing WinUI roadmap updates and info about the latest WinUI 3 release in Windows App SDK Preview 2 (#6049). We'll also be joined by folks from the React Native for Windows team to share latest updates and give an overview of how RN4W integrates with and layers on top of WinUI.

### **Agenda**
- Intro 
- WinUI release updates
- WinUI 3 in Windows App SDK Preview 2 info + demo
- RN4W presentation
- Q & A
  - **Questions and topic requests can be pre-submitted by commenting them on this GitHub issue**
  - **Questions can be asked live in the YouTube livestream's comment section**

### **Q&A Code of Conduct**
- To help ensure Q&A remains beneficial for the majority of the call's developer audience, please consider whether your question could be framed so that it might be more broadly relevant to our larger developer audience by ensuring it is reasonably concise, broadly beneficial, well-suited for the fast-paced live Q&A format, or able to spark open ended discussion.  
- Please understand some questions are not well-suited for the fast-paced live Q&A format and should be filed as standalone [Discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=discussion&template=discussion.md&title=Discussion%3A+%5Byour+discussion+title%5D) or [Question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) issues where they can be most appropriately handled. Excluding presentation topic requests, this generally includes requests for dedicated follow-ups or technically complex questions that require investigative time or expertise not included in this month's guest list.

### Leave us your questions in the comments on this issue or live in the YouTube chat during the stream!

**Comment by pjmlp** [comment]
I would be curious to know if the React Native team has their own special tooling for writing IDL files and integrating generated code back into Visual Studio for Windows Runtime components, or just are too deep into the ways of ATL/WRL that they just deal with it like the rest of us.

**Comment by llothar** [comment]
When will we get the ink canvas control in WinUI3 ?

**Comment by MrDeej** [comment]
Please enable Windowing in next preview. It works good enough in Experimental1 to use. The operating system is called "Windows", not "Window" :) We need multiple windows (on same thread) to enable desktop productivity.

**Comment by jaymarvin98** [comment]
Hello!

Is this the best place/forum to ask general questions?  I hesitate to create an  "Issue".

My question is about the file system interface of UWP, the main actor being StorageFile.  Is this mechanism/API supported in WinUI 3, or Win UI 2 for that matter?  Or do you have to revert to the older System.IO Win32 APIs?

Thanks,
Jay Marvin

**Comment by wjk** [comment]
**Where's the source code?** We were promised source years and years ago, and not one line of core WinUI 3 code has hit GitHub to date. Even if you can't release the WinUI 3 C++ source yet due to its OS repo history, at least _please_ let us be able to submit PRs for the NuGet packaging and MSBuild targets, since (AFAIK) those components were written from scratch. There are plenty of things we, the community would be able to improve on (for example, https://github.com/microsoft/WindowsAppSDK/discussions/1444), if only you let us!

**Comment by harvinders** [comment]
@ryandemopoulos Sorry, have to ask it. When are we going to see 1.0 released? Why I ask? We can then plan our activities properly.

**Comment by seanocali** [comment]
Will there be gamepad support in 1.0?

**Comment by gabbybilka** [comment]
Hey folks, as you've seen by the title update, we've had to cancel the WinUI community call this month. 

Typically, we'd address your questions asked in this issue in the live Q&A. Instead, we'll be replying directly in this thread. We appreciate your flexibility!

**Comment by lhak** [comment]
- Is multi window support still planned for 1.0 (it is on the roadmap, but disabled in the preview versions) ?
- When will xcopy deployment be possible ?

And, finally, when will this bug https://github.com/microsoft/microsoft-ui-xaml/issues/3665 be fixed? It prevents actually using win2d and has not been fixed for almost a year now.

**Comment by terrycox** [comment]
Can Ryan provide any further information regarding Pivot? I'm still using it and need to figure out where to take my code.

**Comment by kmgallahan** [comment]
Hot reload for C# and XAML seems completely broken in Preview 2 with VS 2019. Is 2019 support going to be added back by Nov 8 / Preview 3 / Release?

**Comment by terrycox** [comment]
I'm not sure why the Community Call was canceled, but if it's because you guys are rushing to get ready for Windows App SDK 1.0, I suspect you're rushing too much...

**Comment by ryandemopoulos** [comment]
> Are there going to be updates to the styles of WPF so users don't have to rely on external dependencies?
> 
> * [Feature: new WPF style for Windows 10 dotnet/wpf#1485](https://github.com/dotnet/wpf/issues/1485)
> * [Use accent color as the default color for controls dotnet/wpf#3775](https://github.com/dotnet/wpf/issues/3775)
> 
> And perhaps open-sourcing UXTheme?
> 
> And a more user-facing question I have is whether click and drag support for menus is coming. I'm not sure if there's an issue in this repo already but people (in my circles at least) including myself have noticed this. And hey... isn't Paint using XAML islands now?
> 
> Ah and a question at a more personal level that I'm only asking because the RNW folks are here. It looks like the Xbox app for Windows uses an old version of RNW (and hence WinUI). It also doesn't use MSIX? What's up with that? And what other clients, be it Microsoft or external, use RNW?
> 
> Edit: Also, last time I really checked in with WinUI 3.0, UWP wasn't supported. I'm not much of a UWP developer but are you folks not tired tired of burning those who have followed Microsoft? I remember reading [microsoft/WindowsAppSDK#105](https://github.com/microsoft/WindowsAppSDK/issues/105) where people were complaining about the lack of official .NET 6 support in UWP apps. The entire situation is rather messy. Again, only briefly looked at the docs of UWP stuff. More or less sad for those people.

Regarding WPF and UxTheme, both are good ideas, but neither are planned at this time.  We're focusing our resources on bringing new value primarily to WinUI, as we have a lengthy ToDo list in terms of features to add and bugs to fix.

Could you help me understand what "click and drag support for menus" means?  Is this re-ordering within a menu or something like that?

@stmoy should answer the question around React Native for Windows.

**Comment by ryandemopoulos** [comment]
> Hello!
> 
> Is this the best place/forum to ask general questions? I hesitate to create an "Issue".
> 
> My question is about the file system interface of UWP, the main actor being StorageFile. Is this mechanism/API supported in WinUI 3, or Win UI 2 for that matter? Or do you have to revert to the older System.IO Win32 APIs?
> 
> Thanks, Jay Marvin

@MikeHillberg, are you able to answer this?

**Comment by ryandemopoulos** [comment]
> Is there a plan to add datagrid control?

I don't have a timeframe, but having a DataGrid solution is certainly important.  UWP XAML also did not have a DataGrid, and our team felt it was important enough that we ported the Silverlight DataGrid into the Windows Community Toolkit a few years ago -- it was actually the only control we've ever produced for UWP XAML that was .NET only (since we didn't have the time to re-write it in C++.

We have a lengthy list of high priority things to get to -- not just shipping in WinAppSDK 1.0, but also many other strongly-requested features like Islands, Mica, Muti-Window support, and several other controls.  I think eventually we'll want to bring in DataGrid too but it will be a process of weighing that against other community requests.

**Comment by stmoy** [comment]
@thatsofia 

> It looks like the Xbox app for Windows uses an old version of RNW (and hence WinUI). It also doesn't use MSIX? What's up with that?   

Thanks for reaching out! We work closely with Facebook to ensure that React Native for Windows stays aligned with the RN Core versions - in fact, [we just released v0.66 of RNW](https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.66.0) to coincide with the release of [v0.66 for RN core](https://reactnative.dev/blog/2021/10/01/version-066). Even so, it takes teams awhile to update to the latest version (including folks that we work closely with like the Xbox team). 

> And what other clients, be it Microsoft or external, use RNW?

Great question -- we're working on putting together a customer showcase site, but it has been a work in progress. In the meantime, a few of our big customers include:
- Office (commenting experience) 
- Xbox (Store app on Console, Xbox app on PC)
- PowerApps platform

Some external customers include: 
- [Messenger Desktop ](https://twitter.com/Eli_White/status/1422790525694844928?s=20)
- [Mashreq bank](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/how-mashreq-bank-is-using-react-native-for-windows-to-bring-new/ba-p/2421056)
- [Knomadix](knomadix.com/knomadix-releases-react-native-windows-version-of-knomadix-backpack/)

We can't wait to share even more info when the customer showcase site goes live! 

If you have any other questions, please reach out to the React Native for Windows team on GitHub: https://github.com/microsoft/react-native-windows

**Comment by ryandemopoulos** [comment]
> * Is multi window support still planned for 1.0 (it is on the roadmap, but disabled in the preview versions) ?
> * When will xcopy deployment be possible ?
> 
> And, finally, when will this bug #3665 be fixed? It prevents actually using win2d and has not been fixed for almost a year now.

The roadmap will be updated today -- @gabbybilka is just putting some final touches on it.  Multi-window is likely to come in 1.1 (we are still planning 1.1 but I think it likely makes it).

xcopy deploy is targeted for 1.0.

I don't have an ETA for #3665, but I'd be happy to raise it with my dev team.  Ballpark: could you give me an idea of how rapidly the memory usage grows?  Trying to get a sense of the severity of the issue...

**Comment by seven-mile** [comment]
No matter why the meeting is cancelled, thanks for your magnificent works! I think the fluent development experience on recent-version WinAppSDK has been pleasing most of us.
I want to know which step have Mica & DesktopAcrylic Controllers reached? Are them nearly completed?
Concerning the coming Preview3, will it contain the mere bug fix? Or part of preliminary features will be out too?

**Comment by Scottj1s** [comment]
@jaymarvin98, Some StorageFile APIs are available for desktop (non-UWP) apps, and can be used in both packaged and unpackaged modes.  If you have a specific scenario you feel is not supported, but should be, please enter an issue here.

**Comment by ryandemopoulos** [comment]
> When rapidly changing the size of a CanvasControl (e.g. by resizing the window very quickly) I think I could manage about 1 gigabyte of video memory increase per second. In my application I do an animated size change of a CanvasControl and can completely fill up the VRAM with a single animation, leading to multiple UI freezes during the animation.
> 
> While I could certainly remove this animation for now, this behavior is still very concerning because the same code works perfectly on .net core 3.1+ xaml islands and win2d today.

Yikes!  OK, I took your comment and put it into the original issue so we also have that info.  I'll chat with our dev team about it.  Sorry I don't have an ETA beyond that.

**Comment by gabbybilka** [comment]
@llothar Regarding InkCanvas in WinUI 3, we do not yet have a specific date for adding InkCanvas, but it is still in our roadmap for a future release.

@ghost1372 Regarding designer in WinUI 3, we don't have plans yet to add one. Have you used designer in the past for UWP/WPF? What would you need in a designer for WinUI 3? We are still investigating adding this.

@seanocali Regarding gamepad support in 1.0, unfortunately it will not be supported in WinUI 3 GA. @codendone do you have any additional info on the plans to include gamepad input in Windows App SDK for WinUI 3?

Stay tuned~ for an update to our roadmap later today for our most up to date feature timeline.

**Comment by lhak** [comment]
@ryandemopoulos My question is specifically about self-contained unpackaged apps. This is shown as not supported for 1.0 but as far as I have understood @Scottj1s correctly, this will actually be supported.

**Comment by lhak** [comment]
Will there be a new experimental release that contains all of preview 3 (especially the newer styles) and has the experimental features (like multi-window support) enabled?

**Comment by codendone** [comment]
> Hello! Unfortunately I came across on multiple limitations of WinUi 3 as GUI framework. Here is my questions (I will very appreciate if you cover these ones):
> 
> 1. What is about Vulkan support. My application heavily uses Vulkan engine to render different scenes. I want to easily migrate to WinUi (but it seems like there is no direct support). Some custom control with vulkan rendering will be enough.
> 2. This one is related to the previous question (it's kind of workaround). Will WinUi support of including native controls (especially for native win32 `HWND`) in nearest releases? (Here is list of related issues [Question: How to migrate a simple Win32 app to WinUI 3.0 #3812](https://github.com/microsoft/microsoft-ui-xaml/issues/3812), [Discussion: Legacy Pond (Legacy control container in XAML) for XAML Desktop #1833](https://github.com/microsoft/microsoft-ui-xaml/issues/1833), #[Discussion: Vulkan embedding #3291](https://github.com/microsoft/microsoft-ui-xaml/issues/3291)). I analyzed the WinUI 3 application. I noticed that it does not use native win32 children (it seems like that they are custom drawn, except for top level window - `WinUIDesktopWin32WindowClass`) This is problem because Vulkan API requires native `HWND` . (Just as example - WPF provides similar feature)
> 3. Why does API not have effective way to override appearance of any controls. (I know that composition can be applied for custom draw controls, but it's very ineffective to render such primitives as `Line`, `Rectangle`, `Path` because they are derived class of `Shape`. It has overhead (for example due implementation, each of such instances allocated memory on heap etc). Just as example - WPF proposes direct rendering to Visual object, its content has render instructions which will be processed later on GPU - I did not find similar way in WinUI 3). It's related to [How to render content of Control object? #6036](https://github.com/microsoft/microsoft-ui-xaml/issues/6036)

1. There is no direct support for Vulkan. Some discussion of that and alternatives are in #5193.
2. WinUI3 does not currently have HwndHost (like WPF) to directly support hosting child HWNDs. Depending on your needs, you could put a child HWND in the app yourself and size/position it appropriately. This isn't easy if you need that HWND to take keyboard focus have a proper Accessibility tree, but if it is only for custom rendering these complications likely won't apply.
3. WinUI has largely focused on the user interface of an application rather than being a renderer for application content, and complex custom rendering is less common for the user interface. More capabilities have been added in recent years, but even those focus on shapes and paths. Note that there are both XAML elements for Shape and Path as well as Composition primitives via CompositionSpriteShape, which moves the shape handling/rendering down to the composition layer. If the rendering capabilities you're looking for here are shapes/paths, then perhaps [Win2D](https://github.com/Microsoft/Win2D) is a better fit?

**Comment by thatsofia** [comment]
@ryandemopoulos 
> > Are there going to be updates to the styles of WPF so users don't have to rely on external dependencies?
> > 
> > * [Feature: new WPF style for Windows 10 dotnet/wpf#1485](https://github.com/dotnet/wpf/issues/1485)
> > * [Use accent color as the default color for controls dotnet/wpf#3775](https://github.com/dotnet/wpf/issues/3775)
> > 
> > And perhaps open-sourcing UXTheme?
>
> Regarding WPF and UxTheme, both are good ideas, but neither are planned at this time. We're focusing our resources on bringing new value primarily to WinUI, as we have a lengthy ToDo list in terms of features to add and bugs to fix.

That's sad for numerous reasons and is really hypocritical of MS. I need not say more but our end users are the ones that hurt (and of course us 😢)

> > And a more user-facing question I have is whether click and drag support for menus is coming. I'm not sure if there's an issue in this repo already but people (in my circles at least) including myself have noticed this. And hey... isn't Paint using XAML islands now?
>
> Could you help me understand what "click and drag support for menus" means? Is this re-ordering within a menu or something like that?

Turns out that there is an issue: #815. It's strange that _no one_ on the WinUI team has ever used this behaviour in their own day-to-day lives. I didn't even need to get that feedback from UX in my case as I already saw it myself.

@stmoy 
>>It looks like the Xbox app for Windows uses an old version of RNW (and hence WinUI). It also doesn't use MSIX? What's up with that?
>
>Thanks for reaching out! We work closely with Facebook to ensure that React Native for Windows stays aligned with the RN Core versions - in fact, we just released v0.66 of RNW to coincide with the release of v0.66 for RN core. Even so, it takes teams a while to update to the latest version (including folks that we work closely with like the Xbox team).

Thanks for the reply! Just four big customers is uh... not what I was expecting at this stage.

**Comment by robloo** [comment]
Please confirm status of releasing `WebView2`. This is still marked as preview and cannot be used with Store apps. I'm strongly hoping this will be done for 2.8. Even if there are issues, leave it up to app developers to decide with their own testing if it is acceptable to release. (My use case is so simple it works perfectly already).

https://github.com/microsoft/microsoft-ui-xaml/issues/6224

-original-
https://github.com/microsoft/microsoft-ui-xaml/issues/5610
https://github.com/microsoft/microsoft-ui-xaml/pull/5708

**Comment by apierini** [comment]
Hello, is there an ETA for xaml islands in WinUI 3? I've seen on the roadmap that they are "Planned for a future update", but a more detailed schedule would be very appreciated. 

We have a big win32 desktop app that we would like to modernize and we need to choose bewteen waiting for Win UI 3 xaml islands, using Win UI 2 xaml islands or using some alternative approach (ie WPF hosted inside HWND).

Any suggestions are welcome.

Andrea

**Comment by llothar** [comment]
> Any suggestions are welcome. 

Just wait. Like me and others learned to wait for 14 years since the last exciting Win32 improvement in 2008.

Calling the current state of Windows App SDK Version as 1.0 is this typical agile development result of a failed (underestimated) project. XAML Island for Win 1.0 was the BIG unique sales point for Project Reunion.  I doubt anyone can answer you as they will need a postmortem to know what they have to plan for the next roadmap.  

My christmas wish is that nobody in the high level management withdraws resources from  "Windows App SDK Version 2.0" so i have something to look for in Q4 2022.

**Comment by gabbybilka** [comment]
Closing this issue, please feel free to open up a new issue with questions, bug reports, or discussion topics.

**Comment by pubtom** [comment]
If you need .NET>5 in UWP please give a vote on this: https://developercommunity.visualstudio.com/t/Add-NET-678-support-to-UWP/1596483
