### ISSUE TITLE
ToggleSwitchFillOnPointerOver does not update color of ToggleSwitch

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/microsoft-ui-xaml#6057]
### Describe the bug

ToggleSwitch has a brush ToggleSwitchFillOnPointerOver that does not seem to work. Hovering over the ToggleSwitch removes all color.

Seen on 2.7 and  pre-release 8.2109.27001

### Steps to reproduce the bug

1. Create a new C++/Winrt App and add WinUI 2.8.0-prerelease.210927001
2. Include this XAML code
`xmlns:muxc="using:Microsoft.UI.Xaml.Controls"`
```
    <StackPanel Orientation="Vertical" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="ClickHandler">Click Me</Button>
        <ToggleSwitch x:Name="mySwitch">
            <ToggleSwitch.Resources>
                <SolidColorBrush x:Name="SwitchOne"  x:Key="ToggleSwitchFillOff" Color="Green"/>
                <SolidColorBrush x:Key="ToggleSwitchFillOffPointerOver" Color="Green"/>
                <SolidColorBrush x:Key="ToggleSwitchFillOn" Color="Orange"/>
                <SolidColorBrush x:Key="ToggleSwitchFillOnPointerOver" Color="Orange"/>
            </ToggleSwitch.Resources>
        </ToggleSwitch>
    </StackPanel>
```
3. Turn Toggle Switch to off position and hover over the ToggleSwitch

### Expected behavior

Hover color on ToggleSwitch should stay Green as shown below

https://user-images.githubusercontent.com/42554868/136425315-71cfacb3-9040-4121-9035-242359bd3cfb.mp4

### Screenshots

Actual Behavior is shown below. You can also see this issue on react-native-gallery app

https://user-images.githubusercontent.com/42554868/136425489-91ef3d09-39c4-47e8-8b6c-3c54ababd496.mp4

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [x] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

_Note: I'm new to XAML so please let me know if this is not a bug! :)_

**Comment by IcySnex** [comment]
The last reply is already very old and the bug is still there in the latest version of WinUI and WIndowsAppSDK.
Is there any temporary fix? I really want to style all my controls the same with custom colors.
