### ISSUE TITLE
UIElement.ProtectedCursor property doesn't work

### ISSUE THREAD

**Issue by mikhailvendin** [microsoft/microsoft-ui-xaml#6058]
**Describe the bug**
ProtectedCursor property doesn't change cursor type for the UIElement.

**Steps to reproduce the bug**
1. Open the attached project "Sample_SDK_0.1.0"
[CursorBugSamples.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7293832/CursorBugSamples.zip)
2. Run the project
3. Tap on the 'CursorTestButton' button
4. Cursor doesn't change

**Expected behavior**
Cursor type should be changed for UIElement after set ProtectedCursor property.
In the attached project 'Sample_0.8.0' ProtectedCursor property works as expected and cursor for the test button change.

**Version Info**
NuGet package version: 
[Microsoft.WindowsAppSDK 0.1.0-preview1]

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxx)              |    |
| Ocrober 2020 Update (19042.1110)            |  Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by StephenLPeters** [comment]
@codendone is this expected?
