### ISSUE TITLE
Can a value be set on a Variable Font's set of available AXIS(s), programmatically, using managed code (C#)?

### ISSUE THREAD

**Issue by btueffers** [microsoft/microsoft-ui-xaml#6059]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/1559

<div type='discussions-op-text'>

<sup>Originally posted by **GUI-Kenny** October  6, 2021</sup>
Can a value be set on a Variable Font's set of available AXIS(s), programmatically, using managed code (C#)? Like in a TextBlock control used in XAML.

I know how to do this with Fonts in CSS and HTML5, but don't know if .NET5 (WinUI 3) is set up to handle AXIS(s) from Variable Fonts. I also know, there is an interface, DWriteCore, where I can get AXIS information, and even functions to draw to a Device Context using these values.

Just want to set up a Slider to adjust Axis(s) and display the results.

I'm trying to see, where this capability is in Managed Code (C#).

Thank you in advance, for any assistance.</div>

**Comment by codendone** [comment]
Closing, since the question has been correctly answered above.
