### ISSUE TITLE
Crash on clearing IObservableVector bound to ItemsRepeater::ItemSource

### ISSUE THREAD

**Issue by ramaswamyranganathan** [Microsoft/microsoft-ui-xaml#607]
**Describe the bug**
I have an IObservableVector bound to an ItemsRepeater’s ItemSource.

However, when I clear the vector in the ViewModel, I run into a crash with the following stack below. Instead if I invoke RemoveAtEnd on the vector until its Size is 0, all is well. The crash happens trying to access VectorChangedEventArgs::Index property when the change is a CollectionChange::Reset.

**Steps to reproduce the bug**

1. Bind an ItemsRepeater to an Vector of items
2. When the UI is up and running, perform a user actions that invoked the Vector::Clear() method to empty it

Notice a crash with the following stack:
>      YourPhone.exe!Platform::Collections::Details::VectorChangedEventArgs::Index::[Windows::Foundation::Collections::IVectorChangedEventArgs]::get() Line 196      C++
>      YourPhone.exe!Platform::Collections::Details::VectorChangedEventArgs::[Windows::Foundation::Collections::IVectorChangedEventArgs]::__abi_Windows_Foundation_Collections_IVectorChangedEventArgs____abi_get_Index(unsigned int * __abi_returnValue) C++
>      [Inline Frame] Microsoft.UI.Xaml.dll!winrt::impl::consume_IVectorChangedEventArgs<winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>::Index() Line 5221       C++
>      Microsoft.UI.Xaml.dll!InspectingDataSource::OnVectorChanged(const winrt::Windows::Foundation::Collections::IObservableVector<winrt::Windows::Foundation::IInspectable> & __formal, const winrt::Windows::Foundation::Collections::IVectorChangedEventArgs & e) Line 198 C++
>      [Inline Frame] Microsoft.UI.Xaml.dll!winrt::Windows::UI::Xaml::SizeChangedEventHandler::<lambda_778e218533f9d63cc7aafcdd2f5bac52>::operator()(const winrt::Windows::Foundation::IInspectable &) Line 17953       C++
>      Microsoft.UI.Xaml.dll!winrt::impl::delegate<winrt::Windows::UI::Xaml::SizeChangedEventHandler>::type<<lambda_778e218533f9d63cc7aafcdd2f5bac52> >::Invoke(void * sender, void * e) Line 9014 C++

**Expected behavior**
The ItemsRepeater goes to the empty state without any crash

**Screenshots**

**Version Info**
Microsoft.UI.Xaml.2.1.190405004

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Had an email thread about this and discovered that the VectorChangedEventArgs implementation being used throws an exception when trying to call get_Index on an args where the operation is Reset. This is pretty weird, but we can probably avoid calling Index in this case.
