### ISSUE TITLE
TitleBar Interaction and functionality

### ISSUE THREAD

**Issue by schemburkar** [microsoft/microsoft-ui-xaml#6070]
### Describe the bug

This is in continuation of posts in #4835.

Even with the latest Preview, below functionality is not available, compared to previous like UWP.

- Add Interactive elements in the title bar
- Restrict draggable region in the title bar using left/right margins
- Title bar controls to right side have hit target problems. Only work if hovered on bottom 5px.
   - I could extend the content on title bar and provide interactive elements (Button "Hey 1" ) on the left area only.

     ![image](https://user-images.githubusercontent.com/3159347/128624637-92503b19-adef-4f4e-aece-27440fd3fcff.png)

 - The button "Hey 2" covered by title bar area, is not interactable by mouse/touch but works by using keyboard TAB focus.
      ![image](https://user-images.githubusercontent.com/3159347/128624754-7ca08ba3-5fa6-4d2d-a999-9d42e2df60e7.png)
      

### Steps to reproduce the bug

New Project in C#/.NET using WinUI

### Expected behavior

Expected Target UX similar to an existing UWP app
![image](https://user-images.githubusercontent.com/3159347/127778981-2c260075-5b25-40ce-9292-8a530995110f.png)

![image](https://user-images.githubusercontent.com/3159347/127779034-e22b4be6-8ff4-4d28-9d96-fc84ae004d3e.png)

In UWP versions we could add margin to left/right to restrict the title bar functionality to the middle on the area. Allowing interactive elements on both sides
  - Something like Visual Studio does? Where space between the Project name and User icon is the draggable title bar area
  
    ![image](https://user-images.githubusercontent.com/3159347/128624692-89858c87-84d9-4ee6-858d-b9dd2083519f.png)
  - Like something I have done in my UWP app too! 
    ![image](https://user-images.githubusercontent.com/3159347/128624840-b353a624-9778-4f19-80ad-9bdb3be4c7bb.png)

Additional scenarios that are not supported currently within WinUI title Bar but are used in the newly re-designed official Microsoft Store app in Windows 11. 
All blank space on the title bar is draggable, while retaining input on other elements.

Overall Title Bar
![image](https://user-images.githubusercontent.com/3159347/131140983-445bb4fc-e3c4-4ffe-98d9-5c67c20b17a9.png)

Search  in titlebar with Autocomplete
![image](https://user-images.githubusercontent.com/3159347/131141077-26b55e4f-99dd-426c-9462-f8df11b7c6c3.png)

User Icon in titlebar with menu
![image](https://user-images.githubusercontent.com/3159347/131141130-1e0d62e7-728d-455a-8db7-cc0258417408.png)

### Windows app type

- [ ] UWP
- [ ] Win32

### Additional context

OS: Windows 10 21H1
Target App: WinUI/Desktop/.NET 5/.NET 6/C#

**Comment by kmgallahan** [comment]
> OS: Windows 10 21H1

https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel

> Window title bar customization works only on Windows 11. Use the IsCustomizationSupported method to check for title bar customization feature support. We intend to bring this functionality down-level.

**Comment by minusium** [comment]
> Something like Visual Studio does? Where space between the Project name and User icon is the draggable title bar area

Visual Studio handles titlebar itself, it's a custom titlebar with custom control buttons. You can see you won't see Windows 11's snap window helper when you hover maximize button.

**Comment by knightmeister** [comment]
Just want to chime in here, I've spent a fair amount of time trying to get items in a custom titlebar interactable, with no luck. This worked on UWP but any button, textbox or interactable element I put in a custom titlebar with WinAppSDK 1.0 cannot be selected with the mouse (although I can tab to it).

Do we have an estimated resolution on this, or work around?

I have set `IsHitTestVisible` to `true` with no success.

**Comment by schemburkar** [comment]
>  get items in a custom titlebar interactable, with no luck

@knightmeister  This is what I have experienced as well and currently only interactive elements can be on the left area like [image](https://github.com/microsoft/microsoft-ui-xaml/issues/6070#issuecomment-945113939) in previous post.

> I have set IsHitTestVisible to true with no success.

This doesn't do anything in my opinion. The Title bar drag controls are overlaid programmatically over the elements we add. This was not the case in previous UWP implementations.

In general, this is Title bar area needs enhancements as these requirements are not implemented yet. Question is will these be ever addressed? I have been asking since Aug 2020, no strong commitment so far...

**Comment by BenBtg** [comment]
I'm experiencing the same issue working on an WinUI that requires interactive elements in the TitleBar. 
Only workaround I have found is to not call SetTitleBar(CustomTitleBar). But that just leaves a very small area on the right of the title bar as draggable.

**Comment by sigmarsson** [comment]
In another thread adding this snippet to the ```app.manifest``` suggests to make the magic. For me no avail. 

```  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!--The ID below indicates app support for Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
    </application>
  </compatibility>```

When ```ExtendsContentIntoTitleBar = true``` mouse events no more received or no more delivered.

**Comment by LadderLogic** [comment]
@pratikone any updates on this feature? Interactable titlebar is a norm these days for desktop applications (Visual Studio, Slack, and plethora of modern windows apps are some examples). We are spinning too much effort to workaround.

**Comment by sigmarsson** [comment]
You must invoke this method after your shell has initialized. 

```
// Helper class to workaround custom title bar bugs.
// DISCLAIMER: The resource key names and color values used below are subject to change. Do not depend on them.
// https://github.com/microsoft/TemplateStudio/issues/4516
internal class Win32Ex
{
    private const int WAINACTIVE = 0x00;
    private const int WAACTIVE = 0x01;
    private const int WMACTIVATE = 0x0006;

    [DllImport("user32.dll")]
    private static extern IntPtr GetActiveWindow();

    [DllImport("user32.dll", CharSet = CharSet.Auto)]
    private static extern IntPtr SendMessage(IntPtr hWnd, int msg, int wParam, IntPtr lParam);

    public static void UpdateTitleBar(UIElement shell)
    {
        if (shell is FrameworkElement frameworkElement)
        {
            UpdateTitleBar(frameworkElement.RequestedTheme);
        }
        else
        {
            throw new ArgumentException($"Unable to update application title bar: {shell.GetType()}");
        }
    }

    public static void UpdateTitleBar(ElementTheme theme)
    {
        if (App.Window.ExtendsContentIntoTitleBar)
        {
            if (theme != ElementTheme.Default)
            {
                Application.Current.Resources["WindowCaptionForeground"] = theme switch
                {
                    ElementTheme.Dark => new SolidColorBrush(Colors.White),
                    ElementTheme.Light => new SolidColorBrush(Colors.Black),
                    _ => new SolidColorBrush(Colors.Transparent)
                };

                Application.Current.Resources["WindowCaptionForegroundDisabled"] = theme switch
                {
                    ElementTheme.Dark => new SolidColorBrush(Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF)),
                    ElementTheme.Light => new SolidColorBrush(Color.FromArgb(0x66, 0x00, 0x00, 0x00)),
                    _ => new SolidColorBrush(Colors.Transparent)
                };

                Application.Current.Resources["WindowCaptionButtonBackgroundPointerOver"] = theme switch
                {
                    ElementTheme.Dark => new SolidColorBrush(Color.FromArgb(0x33, 0xFF, 0xFF, 0xFF)),
                    ElementTheme.Light => new SolidColorBrush(Color.FromArgb(0x33, 0x00, 0x00, 0x00)),
                    _ => new SolidColorBrush(Colors.Transparent)
                };

                Application.Current.Resources["WindowCaptionButtonBackgroundPressed"] = theme switch
                {
                    ElementTheme.Dark => new SolidColorBrush(Color.FromArgb(0x66, 0xFF, 0xFF, 0xFF)),
                    ElementTheme.Light => new SolidColorBrush(Color.FromArgb(0x66, 0x00, 0x00, 0x00)),
                    _ => new SolidColorBrush(Colors.Transparent)
                };

                Application.Current.Resources["WindowCaptionButtonStrokePointerOver"] = theme switch
                {
                    ElementTheme.Dark => new SolidColorBrush(Colors.White),
                    ElementTheme.Light => new SolidColorBrush(Colors.Black),
                    _ => new SolidColorBrush(Colors.Transparent)
                };

                Application.Current.Resources["WindowCaptionButtonStrokePressed"] = theme switch
                {
                    ElementTheme.Dark => new SolidColorBrush(Colors.White),
                    ElementTheme.Light => new SolidColorBrush(Colors.Black),
                    _ => new SolidColorBrush(Colors.Transparent)
                };
            }

            Application.Current.Resources["WindowCaptionBackground"] = new SolidColorBrush(Colors.Transparent);
            Application.Current.Resources["WindowCaptionBackgroundDisabled"] = new SolidColorBrush(Colors.Transparent);

            var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(App.Window);

            if (hwnd == GetActiveWindow())
            {
                SendMessage(hwnd, WMACTIVATE, WAINACTIVE, IntPtr.Zero);
                SendMessage(hwnd, WMACTIVATE, WAACTIVE, IntPtr.Zero);
            }
            else
            {
                SendMessage(hwnd, WMACTIVATE, WAACTIVE, IntPtr.Zero);
                SendMessage(hwnd, WMACTIVATE, WAINACTIVE, IntPtr.Zero);
            }
        }
    }
}

```

**Comment by LadderLogic** [comment]
> 

@sigmarsson could you shed some light on this code, or a link to where I can find more explanation? I can see that this code will change the color of the standard MinMaxClose buttons, but I don't understand how this would make the titlebar interactable with custom buttons when ExtendsToTitleBar is set.
Thank you!

**Comment by Jhngrntn** [comment]
OH MAN I finally found a work-around!

If you split the "title bar" into a grid with two (or more) columns, you can set the column you wish to be interactable as the Title Bar in the code behind.

Here's an example:

`public MainWindow()
{
  this.InitializeComponent();
  ExtendsContentIntoTitleBar = true;
  SetTitleBar(TitleBar);

}`

and in xaml:

`<Grid ColumnDefinitions="Auto, *">
	<local:MenuView Grid.Column="1"/>

	<StackPanel Grid.Column="2" Orientation="Horizontal" x:Name="TitleBar">
		<TextBlock Text="Your Title here" />
		<TextBlock Text="Version 1" />
	</StackPanel>
</Grid>`

**Comment by DavidLuong98** [comment]
@pratikone Any updates with the example on how to do it ? My team and I updated to preview and UI elements in title bar is still non interactive. We have an AutoSuggestBox in the titlebar. 

Would you be fine being our point of contact? Do you mind if we reach out to you directly on teams?
