### ISSUE TITLE
Question: How to Use Button in AutoSuggestBox item?

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#6071]
I want the AutoSuggestBox items to have a button, i used a **AppBarButton** Everything works fine except that it does not look good at all
```
<AppBarButton HorizontalAlignment="Right"
                          VerticalAlignment="Center"
                          HorizontalContentAlignment="Stretch"
                          VerticalContentAlignment="Stretch"
                          Click="DeleteHistory_Click"
                          Icon="Delete" />
```
![1](https://user-images.githubusercontent.com/9213496/136651946-faed04a9-6d4a-4472-ae5d-c31c1c14a755.png)

So I used **Button** instead of **AppBarButton**  now The appearance is correct and excellent
![2](https://user-images.githubusercontent.com/9213496/136652032-27f2fb87-1848-4f32-821b-137b0c169226.png)

But a new problem arises and when I click on the button, autosuggestbox Closes and also button click is not working but this problem does not exist in the AppBarButton 
So how can I click on the button without selecting the AutoSuggestBox item?

**Comment by StephenLPeters** [comment]
@ranjeshj @llongley or @kmahone have any of you all examined this before?

**Comment by ghost1372** [comment]
any help?
