### ISSUE TITLE
Improve debugging experience for missing resource

### ISSUE THREAD

**Issue by cfgiugliano** [microsoft/microsoft-ui-xaml#6073]
### Describe the bug

In the following example I am using a ListView with a custom DataTemplate but such template is using a StaticResource which isn't defined. The result is an unhandled exception which doesn't give enough details to the developer to debug the problem.

### Steps to reproduce the bug

Define and use a DataTemplate which uses an undefined StaticResource like in the example below (SmallFontSize isn't defined anywhere).

### Expected behavior

I expect the behavior to be notifying the developer that the StaticResource can't be found or that something is wrong with the DataTemplate.

For example if the missing StaticResource is used by a control and not in a DataTemplate definition, the Exception Thrown  says that XAML parsing failed.

### Screenshots

The example
![Immagine 2021-10-09 165913](https://user-images.githubusercontent.com/74872779/136663437-faf0f133-d65e-479d-81af-0010ca2b92a7.png)

The exception
![Immagine 2021-10-09 165815](https://user-images.githubusercontent.com/74872779/136663453-0f8c27ce-dcc0-44ba-b185-66218b209fde.png)
![Immagine 2021-10-09 170311](https://user-images.githubusercontent.com/74872779/136663549-aff3c777-13d7-428e-ae78-61950f29b225.png)

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

I am using the single project template from WindowsAppSDK 1.0 Preview 2 but I have the same behaviour using the Microsoft.ProjectReunion.WinUI 0.8.4 nuget with the app+package template.

**Comment by asklar** [comment]
thanks for filing @cfgiugliano 

CC @kmelmon @RealTommyKlein @MikeHillberg

**Comment by michael-hawker** [comment]
Related to #4972, #3971, and #2350.

I just hit this again in UWP where a ThemeResource was used in a DataTemplate that didn't exist. Just get a COM exception in `MeasureOverride` of the parent control which is completely unhelpful. If I didn't think about invalid resources like this, could have been a test of patience and frustration to figure out what was going on.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.3.0` has been released which fixes this issue.
* [Release Notes](https://aka.ms/windowsappsdk/1.3/1.3.0/release-notes)
* [Nuget](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000)
