### ISSUE TITLE
Question: Can we get a status update on Win2D for WinUI 3?

### ISSUE THREAD

**Issue by watsonwelch** [microsoft/microsoft-ui-xaml#6074]
As far as I can tell, the most recent visibility into Win2D for WinUI 3 was in July/August with this roadmap proposal: https://github.com/microsoft/WindowsAppSDK/issues/1150

Any chance we could get an update where this is at? Thanks!

**Comment by duncanmacmichael** [comment]
Hi everyone,

Sorry for the delay here. For a quick status update on the overall Win2D for WinUI 3 project, we're currently working on prototypes for the initial refactoring work discussed on the proposal. The latest source code updates are available in the main Win2D repo, in the reunion_master branch, [here](https://github.com/Microsoft/Win2D). Thanks!

**Comment by jtorjo** [comment]
@duncanmacmichael Thanks!

> , we're currently working on prototypes for the initial refactoring work discussed on the proposal.

Where is the proposal?

Any ETA? As far as I remember, there are a lot of things that don't work on the WinUI3 branch -- `CanvasAnimatedControl`, `CanvasBitmap` and so on.

**Comment by duncanmacmichael** [comment]
@jtorjo The roadmap proposal I made, [here](https://github.com/microsoft/WindowsAppSDK/issues/1150). I don't have an exact ETA for when that refactoring work will complete, other than our current goal is to deliver it within the next few iterations of the AppSDK. 

As for the things that don't work on the WInUI 3 branch, all I can recommend right now is to watch the [repo](https://github.com/Microsoft/Win2D/tree/reunion_master). I can at least say that CanvasBitmap is now available for WinAppSDK 1.0, which was not the case in 0.8.
