### ISSUE TITLE
DPI and aliasing issue while using WinUI 3 against C++

### ISSUE THREAD

**Issue by hez2010** [microsoft/microsoft-ui-xaml#6075]
### Describe the bug

While using WinUI 3 in a C++ project (without WAP), I found texts and controls are scaled and have aliasing issue.

### Steps to reproduce the bug

1. Use Visual Studio 2022 to create a C++ WinUI 3 Desktop App (no WAP) from template
2. Build and run
3. See scaling and aliasing in texts and controls

### Screenshots

![image](https://user-images.githubusercontent.com/14960345/136685681-f291226f-a626-4619-8a5c-be5201be4be3.png)

### NuGet package version

WinUI 3 with WindowsAppSDK 1.0-preview 2

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (22471)

### Additional context

I don't know but maybe this issue should be transferred to WindowsAppSDK repo?

**Comment by StephenLPeters** [comment]
@gegao18 FYI

**Comment by hez2010** [comment]
The issue still exists in WASDK 1.0-preview3

**Comment by hez2010** [comment]
I can confirm this issue has been fixed in WASDK 1.0 GA.
