### ISSUE TITLE
TabView is not following fluent design style in WinUI 3 when scaling is not 100% (WindowsAppSDK 1.0)

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#6076]
### Describe the bug

The TabView is not following the fluent design

### Steps to reproduce the bug

Add a TabView with TabViewItem in WinUI 3 desktop app (WindowsAppSDK 1.0 preview 2)

### Screenshots

![image](https://user-images.githubusercontent.com/8557046/136692560-f310ea2f-76a1-4747-a0b6-bbe34bb85ad9.png)

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Please discard the nuget version above, the actual version is WindowsAppSDK 1.0 preview 2

**Comment by harvinders** [comment]
I could still see the issue in preview 3

**Comment by devlead** [comment]
Indeed noticed the same.

A lead might be that the control doesn't seem to be present in Themes so maybe that's the issue, noticed when looking at what controls are themed in NuGet package
https://nuget.info/packages/Microsoft.WindowsAppSDK/1.0.0-preview3

Looking at `generic xaml` then i.e. `TabViewItemHeaderBackground`,  `TabViewItemIconForeground` etc. isn't present.
![image](https://user-images.githubusercontent.com/1647294/141784514-b8848929-34ea-4c83-9301-06128ccb0a6f.png)

As a test I added this to my theme and now it more follows my theme
```xml
                    <!-- TabView -->
                    <SolidColorBrush x:Key="TabViewItemHeaderBackground" Color="{StaticResource SolidBackgroundFillColorBase}" />
                    <SolidColorBrush x:Key="TabViewItemIconForeground" Color="{StaticResource SystemBaseHighColor}" />
                    <SolidColorBrush x:Key="TabViewItemHeaderForeground" Color="{StaticResource SystemBaseHighColor}" />
                    <SolidColorBrush x:Key="TabViewItemHeaderForegroundPointerOver" Color="{StaticResource SystemBaseHighColor}" />
                    <SolidColorBrush x:Key="TabViewItemHeaderForegroundSelected" Color="{StaticResource SystemBaseHighColor}" />
                    <SolidColorBrush x:Key="TabViewItemHeaderBackgroundSelected" Color="{StaticResource SystemBaseHighColor}" Opacity="0.3" />
                    <SolidColorBrush x:Key="TabViewItemHeaderBackgroundPointerOver" Color="{StaticResource SystemBaseHighColor}" Opacity="0.2" />
                    <SolidColorBrush x:Key="TabViewItemHeaderBackgroundDisabled" Color="Transparent" />
```

Keys can i.e. be found here
https://github.com/microsoft/microsoft-ui-xaml/blob/f4d71ea4dd138873a187abfb7eb8fb18e897c60a/dev/TabView/TabView.xaml#L342

**Comment by gabbybilka** [comment]
@MikeHillberg what is the status of this bug for 1.0 servicing?

@harvinders added a bit more context here: https://github.com/microsoft/microsoft-ui-xaml/issues/6310#issuecomment-972157731

**Comment by harvinders** [comment]
@StephenLPeters, Also note the focus on tabitem is also showing properly

![image](https://user-images.githubusercontent.com/8557046/145132630-6492d5e3-bdc1-4d66-8a57-f8f76e2cd8ff.png)

**Comment by harvinders** [comment]
@gabbybilka, @StephenLPeters  The issue comes only when the Scaling is set to anything other 100%, which is most of the time as the screen resolution generally is high these days and OS sets the scaling to 125% or 150%.
![image](https://user-images.githubusercontent.com/8557046/151755945-3b077982-8934-47ed-b826-9451458d8e85.png)

The focus also works fine with 100% scaling

![image](https://user-images.githubusercontent.com/8557046/151756222-0ab39447-9951-4cdf-8a1b-d566e79a1615.png)

**Comment by gabbybilka** [comment]
Fixed as part of 1.1-preview2 🎉 (https://aka.ms/windowsappsdk/1.1/1.1.0-preview2/release-notes)

**Comment by dotMorten** [comment]
Ugh I wish I had seen this earlier. Drove me nuts for hours yesterday. Thanks for fixing. Will this be in 1.0.4 too?

**Comment by gabbybilka** [comment]
> Ugh I wish I had seen this earlier. Drove me nuts for hours yesterday. Thanks for fixing. Will this be in 1.0.4 too?

@dotMorten It's currently targeting 1.1 stable and we're not planning on servicing it in 1.0.
