### ISSUE TITLE
NavigationView on WinUI 3 is not aware of Window.ExtendsContentIntoTitleBar value and does not apply necessarily padding

### ISSUE THREAD

**Issue by Code-ScottLe** [microsoft/microsoft-ui-xaml#6108]
### Describe the bug

NavigationView on WinUI 3 (Windows App SDK 1.0 Preview 2) is currently not aware of the Window.ExtendsContentIntoTitleBar value. If we extends the content into the titlebar, no padding would be added on the NavigationView and this basically steals the input from the titlebar once being extended in. Also, if the Setting button is enabled, this also render the 3 captive buttons (minimize, maximize/windowing, close) from being clicked. 

### Steps to reproduce the bug

1. Create new WinUI 3 + .NET 5 project
2. On MainWindow, add a `NavigationView` control as the root content and set the `PaneDispayMode` to Top.
3. In MainWindow.xaml.cs, on the constructor, set `ExtendsContentIntoTitleBar` to true.
4. Build and run.

### Expected behavior

The NavigationView control should have displayed their padding, but instead the control display no padding.

### Screenshots

![image](https://user-images.githubusercontent.com/10987612/137568787-e24e2781-dd37-4c8f-b075-2ff7d57c8898.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Observe on latest RTM Windows 11. 21H2 22000.194.

**Comment by asklar** [comment]
I think this may be working as expected based on this:
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.extendscontentintotitlebar?view=winui-3.0#remarks

> The following two steps are required when specifying a custom window title bar:
> 
> - Set this property to true to hide the Windows default title bar and allocate space for a custom title bar.
> - Call SetTitleBar with your UIElement.
> If you skip step 1, the default title bar is not hidden and your custom title bar is not shown. If you skip step 2, a small area next > to the min/max/close buttons is allocated for the custom title bar until SetTitleBar is called with a valid UIElement.

**Comment by Code-ScottLe** [comment]
> I think this may be working as expected based on this: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.extendscontentintotitlebar?view=winui-3.0#remarks
> 
> > The following two steps are required when specifying a custom window title bar:
> > 
> > * Set this property to true to hide the Windows default title bar and allocate space for a custom title bar.
> > * Call SetTitleBar with your UIElement.
> >   If you skip step 1, the default title bar is not hidden and your custom title bar is not shown. If you skip step 2, a small area next > to the min/max/close buttons is allocated for the custom title bar until SetTitleBar is called with a valid UIElement.

This basically ask you to call SetTitleBar to something... but what is that "something" when you have the NavigationView as the top element?

NavigationView has an internal element that will be visible and extended out and automatically set itself as the custom titlebar in the case of traditional UWP app, but in this case, it isn't doing that.

**Comment by PureWeen** [comment]
@Code-ScottLe this is where I ended up with this 

https://github.com/dotnet/maui/pull/3693/files#diff-d2287e37dd6ce6009b15f623ac879a733e6f379be91ec0f3cc21dd4afa258721R6

There's a little bit padding you have to give the NavigationView Content to get it all to lined up how you want but overall it seems to work/look alright.

**Comment by gabbybilka** [comment]
@pratikone @karenbtlai What is the latest status on this issue?

**Comment by pratikone** [comment]
there isn't a dedicated inset value so one can use 42 px x 3 padding on the right edge for leaving space for titlebar.
ideally, yes, navigation view should apply padding automatically. i will file a bug on it internally.
