### ISSUE TITLE
NavigationView: visual glitch when setting NavigationViewExpandedPaneBackground to an AcrylicBrush with BackgroundSource=HostBackdrop

### ISSUE THREAD

**Issue by mfeingol** [Microsoft/microsoft-ui-xaml#611]
**Describe the bug**

To enable acrylic on the expanded view of a NavigationView, one can set the NavigationViewExpandedPaneBackground  resource to an acrylic brush. This brush can have its BackgroundSource set to HostBackdrop in order to sample content from behind the app's window.

In 2.0.181018004, this worked fine.

In 2.1.190405004 and 2.1.190405004.1, this works, but a strange dark vertical bar is displayed on the expanded navigation view when the app loses focus. cf screenshots below.

**Steps to reproduce the bug**

Open and run the following repro project:

[UwpApp.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3110511/UwpApp.zip)

**Expected behavior**

No dark vertical bar is displayed when the app loses focus.

**Screenshots**

Window has focus:

![image](https://user-images.githubusercontent.com/218865/56631555-a8d8d700-660a-11e9-94fe-467c8963b056.png)

Window loses focus:

![image](https://user-images.githubusercontent.com/218865/56631576-bd1cd400-660a-11e9-9f06-dddf9d20f8b2.png)

**Version Info**

NuGet package version: 2.1.190405004.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18362)                   | Yes |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
The problem is that the AcrylicBrush's FallbackColor defaults to Transparent (arguably a poor default) which means that in the inactive state you're seeing through to some part of the tree that isn't expected to be visible. Set an opaque FallbackColor on AcrylicBrush to avoid this.

Our recommendation would be to use one of our named resources that are configured with good defaults. https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#acrylic-theme-resources

**Comment by mfeingol** [comment]
That makes sense. Thank you for looking.
