### ISSUE TITLE
Question: Packaging apps with .NET class library

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/microsoft-ui-xaml#6113]
I have WinUI 3 app (Reunion 0.8.4) and some class libraries targeting .NET 5, because I want to use them in web app in future, so I want to avoid duplicated code. But when i try to create package, I always get error, that library is not targeting net5.0-windows10.0.19041.0. Is any possible way to create package?

**Comment by JanRajnoha** [comment]
@StephenLPeters @llongley @evelynwu-msft any update?

**Comment by JanRajnoha** [comment]
Problem is with latest version of WinUI 3 too

**Comment by kmgallahan** [comment]
I have class libs working with WinUI 3 & `<TargetFramework>net6.0</TargetFramework>`. What do your csproj files look like?

**Comment by JanRajnoha** [comment]
@kmgallahan 
library:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/16069721/146181572-f6117e1f-4d54-4948-b88b-a7bed7c9f01d.png">

client:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/16069721/146190607-fa194619-46e0-4198-b342-024cce5fa09b.png">

**Comment by kmgallahan** [comment]
I'd recommend creating a blank WinUI 3 / WASDK 1.0 from the standard single project template, adding a ref to the lib, and seeing if that builds without issue.

That template includes `<PublishProfile>` & `<EnablePreviewMsixTooling>` (for single project support), and does not use `<PublishReadyToRun>`.

**Comment by kmgallahan** [comment]
You might also consider creating a blank lib and trying to publish with that as your ref, then start adding dependencies back to it to see if one of those is causing your issue. I seem to remember running into this problem a few months back but managed to work through it.

**Comment by JanRajnoha** [comment]
When I create WinUI library, it is okay, but .NET 6 library will get error "Assets file doesn't have a target for 'net6.0-windows10.0.19041.0'" during publishing app -> click on Package project -> Publish -> Create package -> Package without Store, but I think this will be same for store app too.

**Comment by kmgallahan** [comment]
Is this the AnyCPU limitation issue?

#5120
https://github.com/microsoft/WindowsAppSDK/issues/893

**Comment by JanRajnoha** [comment]
no, I'm using x86

**Comment by JanRajnoha** [comment]
Any information?

**Comment by JanRajnoha** [comment]
@anawishnoff FYI
