### ISSUE TITLE
TextBox IsTextPredictionEnabled property is not working

### ISSUE THREAD

**Issue by rachelkang** [microsoft/microsoft-ui-xaml#6115]
### Describe the bug

The `IsTextPredictionEnabled` property is not working.

When the IsTextPredictionEnabled is set to False on a TextBox as follows, TextBox behaves as though IsTextPredictionEnabled is set to true.
```xaml
<TextBox IsTextPredictionEnabled="False" />
```

The same applies to AutoSuggestBox.

### Steps to reproduce the bug

1. Create new WinUI project
2. Add `<TextBox IsTextPredictionEnabled="False" />` to the main xaml page
3. Run the app in Tablet mode
4. Use the virtual keyboard to type incomplete words into the textbox
5. Notice that text prediction still works when it shouldn't

I have attached repro projects here as well for your convenience:
https://microsoft-my.sharepoint.com/:f:/p/rachelkang/ElNRWH43GmJBgR4IBOLCPgQBEnAdJCr1d0sSqFu-Ez4g1w?e=4Cdvpe

The UWP project and WinUI project have the same exact code - while it works as expected in UWP, it is not functioning in WinUI.

### Expected behavior

IsTextPredictionEnabled=`False` should disable text prediction.

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Needed for implementing cross-platform controls in .NET MAUI

**Comment by ghostidentity** [comment]
Opening this issue as its working:  I confirmed that I set this option on xaml: IsTextPredictionEnabled="False" IsSpellCheckEnabled="False" but it's being honored.


![image](https://github.com/microsoft/microsoft-ui-xaml/assets/4637625/94170af9-3cd6-40ee-a0d1-416714e12e3f)
