### ISSUE TITLE
Discussion: Please keep maui development time OS version requirement to as low as possible

### ISSUE THREAD

**Issue by ponyspeed888** [microsoft/microsoft-ui-xaml#6118]
Can not run MAUI preview 9 on Windows 1909.  There are developers who use older version of Windows.  I open this issue per request of David Ortinau so that it will be reviewed and addressed.  If possible, please allow developer to use Windows 7 (!!!) for MAUI development

**Comment by kmgallahan** [comment]
https://github.com/dotnet/maui
