### ISSUE TITLE
Different accent colors on Windows10 and Windows11

### ISSUE THREAD

**Issue by Alexander-Kamenchuk** [microsoft/microsoft-ui-xaml#6119]
### Describe the bug

Brushes such as AccentLight2 AccentLight3 or AccentDark2 look different on Windows10 and Windows11.
This changes the color presentation of the application and negatively affects visual states if these colors are used there.

That issue also in the WindowsAppSDK repository:  https://github.com/microsoft/WindowsAppSDK/issues/1617

### Steps to reproduce the bug
```xaml 
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
       <Border x:Name="brush0" Background="{ThemeResource SystemAccentColor}" Width="200" Height="60" Margin="20"/>
       <Border x:Name="brush1" Background="{ThemeResource SystemAccentColorLight2}" Width="100" Height="100" Margin="20"/>
       <Border x:Name="brush2" Background="{ThemeResource SystemAccentColorLight3}" Width="100" Height="100" Margin="20"/>
       <ListBox x:Name="lb" />
       <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
   </StackPanel>
```

### Expected behavior

Colors should look the same

### Screenshots

![image](https://user-images.githubusercontent.com/80826968/137907453-91e59c2b-41a3-47eb-887a-35a40d119a75.png)

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by StephenLPeters** [comment]
@Alexander-Kamenchuk is this also an issue in UWP with Winui2?

@chigy and @MarissaMatt is this expected?

**Comment by Alexander-Kamenchuk** [comment]
Hi, @chigy 
Thanks for paying attention to this problem.
This is a problem of creating a design concept, it seems to me that it does not require specific examples.
It's impossible to think of smooth and stable color changes using the AccentLight and AccentDark varieties.
Varieties in Win11 are very sharp. In Windows 11, an accent level of "3" radically changes the source color with a "Hue" shift, in Windows 10 this is not the case.
![image](https://user-images.githubusercontent.com/80826968/139849255-6fb04b00-6120-4ac7-a180-fd09af1dd0c2.png)


In our application, we had to abandon their use for these reasons.
We only use ListAccent brushes which are stable on Windows10 and on Windows11.
But, I would like to make full use of all the possibilities of the accents palette.
