### ISSUE TITLE
ItemsRepeater leaks parent UserControl and children if event handler is attached in Xaml.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/microsoft-ui-xaml#6123]
### Describe the bug

Xaml like the below causes instances of UserControl1 to never be cleaned up and stay around in memory forever:

```
<UserControl
    x:Class="WinUI3Leaks.UserControl1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUI3Leaks"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <ScrollViewer>
            <ItemsRepeater  ItemsSource="{x:Bind ViewModel.Items, Mode=OneWay}">
                    <ItemsRepeater.ItemTemplate>
                        <DataTemplate x:DataType="x:String">
                            <local:UserControl2 AutomationProperties.Name="{x:Bind}" ViewModelChanged="UserControl2_ViewModelChanged" />
                        </DataTemplate>
                    </ItemsRepeater.ItemTemplate>
            </ItemsRepeater>
        </ScrollViewer>
    </Grid>
</UserControl>
```

Specifically the UserControl2_ViewModelChanged event handler seems to be the culprit. Removing it resolves the leak, but since this is defined in xaml this should not be causing the leak.

### Steps to reproduce the bug

- Run the attached sample:[WinUI3Leaks.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8492171/WinUI3Leaks.zip)
- Click the button multiple times and notice that the amount of UserControl1 instances in memory keeps increasing.

### Expected behavior

UserControl1 instances should be cleaned up.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by jlaanstra** [comment]
Updated repro to 1.1.0-preview1

**Comment by llongley** [comment]
Fixed in WinUI 3.

**Comment by lunelake** [comment]
I'm having the same problem with Win UI 2.8(2.8.0-prerelease.220413001), is this getting fixed soon?

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.1.4` has been released which fixes this issue.

Handy links:
* [Release Notes](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-114)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.1.4)
