### ISSUE TITLE
C++/winRT co_await BluetoothLEDevice::FromBluetoothAddressAsync() returns NULL

### ISSUE THREAD

**Issue by brianreinhold** [Microsoft/microsoft-ui-xaml#613]
**Describe the bug**
The BluetoothLEDevice::FromBluetoothAddressAsync() does two things according to the API documentation: 
1. gives you a BluetoothLEDevice asynchronously, and 
2. starts a connection (unfortunately) - would be far better if a connection could be started independently.

According to [documentation](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client)
one can use data from the DeviceWatcher (hard) or the AdvertisementWatcher (easy).

One needs the BluetoothLEDevice to register a handler for the connection event. A kind of catch-22 since you need the BluetoothLEDevice to register but the connection may already have happened by the time you get it. Its a moot point, however, since the method returns NULL.

**Steps to reproduce the bug**
Create an active AdvertisementWatcher. In the registered callback to receive the advertisements, filter as needed to obtain the advertisement from the device you are interested in. In my case I filtered by service UUIDs (available in the advertisement/scanResponse) and accepted any device that supports the standard BTLE health device profiles.

When you have found a device of interest, connect to it. To connect to it, you need to call one of several methods available in the BluetoothLEDevice class. In my case, since I had the Bluetooth Address I used the ::FromBluetoothAddressAsync()  method. The downside of this method (and all methods in the Windows Bluetooth Low Energy APIs is that as an application developer one cannot set up transport callbacks BEFORE one attempts to connection. I have never seen a transport API where the application does not prepare itself to handle any possible transport action BEFORE one even thinks about starting the connection.

In any case, you need to get the BluetoothLEDevice object in order to register a callback for a connection event, which is really dumb as the connection event may already have happened before the co-await BluetoothLEDevice::::FromBluetoothAddressAsync() returns.

It doesn't matter anyways because the method returns NULL.

**Expected behavior**
The expected API would be
1. Register callbacks to handle all possible types of unsolicited transport events
2. Invoke a connection attempt

Given the API:
Expect to receive a BluetoothLEDevice object and to be able to use it to register for the connection status changed events. 

**Version Info**
Copying the information from the help menu below:

`Microsoft Visual Studio Community 2019
Version 16.0.2
VisualStudio.16.Release/16.0.2+28803.202
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA709
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.0.20307.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.0.12311.10635
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.0.12311.10635
Azure App Service Tools v3.0.0

C# Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10306.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake`

NuGet package version: 
(See above)

I have just started this project a few weeks ago (coming from Android and various embedded platforms, so the only thing I have worked with is the most recent (April 2019)
| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Being a company that is working on remote patient monitoring infrastructure we have numerous Bluetooth Low Energy health devices that work with the centrals we have developed on Android, Linux, and iOS.

**Comment by brianreinhold** [comment]
Now that I have filled in the above, certain UI features did not work as anticipated. I have only tried this on Windows desktop systems and only the latest build of Windows and SDK as of April 2019 since I just started this project a few weeks ago.

**Comment by jevansaks** [comment]
This isn't the right GitHub project to report bugs with bluetooth APIs but I will try to find the right place and get back to you.

**Comment by brianreinhold** [comment]
Okay,


Microsoft gave me a link and that's where the link went.


Brian


________________________________

**Comment by jevansaks** [comment]
No worries, which link did you click on? Was it guidance from someone on the uservoice site?

**Comment by brianreinhold** [comment]
It was guidance from someone in this response


[avatar image]<https://developercommunity.visualstudio.com/users/21741/eb671b75-fb24-62b9-b555-00d12cb493fa.html>Anonymous [MSFT] <https://developercommunity.visualstudio.com/users/21741/eb671b75-fb24-62b9-b555-00d12cb493fa.html> · 21 hours ago<https://developercommunity.visualstudio.com/comments/544156/view.html> 0

We have determined that the feedback applies to another product i.e UWP. We recommend that you submit the feedback to that product team at https://github.com/Microsoft/microsoft-ui-xaml . Thank you and we value your contribution to Developer Community.


Brian


________________________________

**Comment by jevansaks** [comment]
Looks like you have good engagement on https://github.com/Microsoft/Windows-universal-samples/issues/1089, so let's continue the discussion there.

**Comment by brianreinhold** [comment]
The bug you are cancelling involves is a different API than #1089 and the one I really want to use. This cancelled bug is very specific and straight forward to duplicate, and CRITICAL to a Bluetooth health device central, whereas the other one is more general (not well documented for the Bluetooth use case and behaviors inconsistent with documentation). To me it is MUCH more important to get the NULL return of the BluetoothLEDevice resolved!


Brian


________________________________

**Comment by jevansaks** [comment]
There's no way for you to know the right place to file these issues, but Windows is a big team and the Bluetooth team just isn't paying attention to this repo. 

The Bluetooth team has said they'll discuss all your issues on Microsoft/Windows-universal-samples#1089. From that discussion they can file the right tracking items in the way that works for them.
