### ISSUE TITLE
Discussion: [Just call it WinUX]

### ISSUE THREAD

**Issue by pauljurczak** [microsoft/microsoft-ui-xaml#6135]
From documentation at https://docs.microsoft.com/en-us/windows/apps/winui/: 
*The Windows UI Library (WinUI) is a native user experience (UX) framework*. Since the UI acronym faded into obscurity, and UX took its place, isn't WinUX name more apt than WinUI? Rhyming with a name of another notorious OS is an added bonus.

**Comment by bpulliam** [comment]
Can this item be closed?

**Comment by ryandemopoulos** [comment]
To be honest I think there's merit to the idea -- but as @MEK3DK mentioned, we need to focus more on fixing issues and making product progress.  It may be worth revisiting this in the future -- especially once the distinction between WinUI 2 and 3 becomes stronger in terms of features & capabilities.
