### ISSUE TITLE
Flowing AsyncLocal to UI thread in WinUI 3

### ISSUE THREAD

**Issue by rick-palmsens** [microsoft/microsoft-ui-xaml#6143]
I am dispatching work to the UI thread using the MainWindow's `DispatcherQueue`. But when I do that, I lose the value stored in `AsyncLocal`. It seems to not flow the execution context automatically, but I am also worried what will happen if I flow it manually, since that would then also flow the sync context, locale info, etc.

So my question is, what would be the safe way to make sure that `AsyncLocal` variables are flowed to the UI thread?

Example of what I would like to work:
```csharp
var asyncLocal = new AsyncLocal<int>();
asyncLocal.Value = 10;

var dispatcherQueue = _mainWindow.DispatcherQueue;
var taskCompletionSource = new TaskCompletionSource();

dispatcherQueue.TryEnqueue(new DispatcherQueueHandler(() =>
{
    Debug.Assert(asyncLocal.Value == 10);
    asyncLocal.Value = 20;
    Debug.Assert(asyncLocal.Value == 20);

    taskCompletionSource.SetResult();
}));

await taskCompletionSource.Task;
Debug.Assert(asyncLocal.Value == 10);
```

I have also noticed that the stack trace gets lost because the execution context isn't flowed, it would be nice to be able to fix this as well.

**Comment by asklar** [comment]
I'm not familiar with what AsyncLocal is supposed to do, but I'd expect asyncLocal.Value to be == 20 at the end (since the lambda captured a reference). Is that a typo in your code or do you expect this type to act like a value type?

**Comment by nikolayvpavlov** [comment]
The answer I gave on [StackOverflow](https://stackoverflow.com/questions/69674397/flowing-asynclocal-to-ui-thread-in-winui-3/69708788#69708788) 

This is not missing logic, because enqueuing an action to DispatcherQueue is not part of your asynchronous flow. It basically sends a message to the UI thread to execute a method.  The issue should be closed.
