### ISSUE TITLE
Maximize/Minimize window events.

### ISSUE THREAD

**Issue by Petrarca181** [microsoft/microsoft-ui-xaml#6148]
Hello, how to detect when window was maximazed or minimized if  user double clicks titlebar or drags the window from maximazied state? .SizeChanged  event does not trigger in those cases.  Or at least disable  possibility  double click to  maximize/minimize.

**Comment by timkur** [comment]
Would it be possible to reconsider this request?

**Comment by castorix** [comment]
> Would it be possible to reconsider this request?

You can handle WM_SYSCOMMAND, with SetWindowSubclass

**Comment by timkur** [comment]
Yep, I can also use WinUIEx's OnStateChanged event as well....

[https://dotmorten.github.io/WinUIEx/api/WinUIEx.WindowEx.html#WinUIEx_WindowEx_OnStateChanged_WinUIEx_WindowState_](https://dotmorten.github.io/WinUIEx/api/WinUIEx.WindowEx.html#WinUIEx_WindowEx_OnStateChanged_WinUIEx_WindowState_)

I'm hoping to see a native WinUI API for this.

Tim

**Comment by codendone** [comment]
A more convenient and direct API on XAML Window is a future possibility.

I believe this is another option with current APIs:
```cs
        this.AppWindow.Changed += AppWindow_Changed;

        private void AppWindow_Changed(Microsoft.UI.Windowing.AppWindow sender, Microsoft.UI.Windowing.AppWindowChangedEventArgs args)
        {
            var presenter = sender.Presenter as OverlappedPresenter;
            if (presenter != null)
            {
                // Insert code here using "presenter.State" to check for Maximized / Minimized / Restore
            }
        }
```
The main caveat here is that the AppWindow.Changed event may fire for reasons unrelated to this state change, so you may need to cache the old state to detect when it changed.
