### ISSUE TITLE
WinUI3 WebView2 with a custom CoreWebView2Environment

### ISSUE THREAD

**Issue by nickprotop** [microsoft/microsoft-ui-xaml#6150]
### Describe the bug

WinUI3 WebView2 control does not currently support initializing with a custom CoreWebView2Environment. So, it is impossible to use the fixed distribution model with WinUI 3/Net5 applications.

### Steps to reproduce the bug

Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync doesn't accepts parameters.

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by krschau** [comment]
This is definitely functionality that we want to have and are working on a solution for. I don't have an ETA yet, though.

**Comment by kotx** [comment]
Is this on a roadmap yet?

**Comment by sudongg** [comment]
Is there more progress on this issue?
Besides not being able to set the Environment , WebView2 on WinUI3 lacks a lot of features and is not on the roadmap.

**Comment by zhuman** [comment]
Note this is also a hard blocker for running WinUI3 apps with AppContainer/partialTrustApplication security modes, which is supposed to be a supported scenario. Doing this requires that applications pass a UserDataPath that is writable for the app package/process.

**Comment by wbokkers** [comment]
What is the status?

**Comment by mlynch** [comment]
Unfortunately, it seems it's still not possible to use WebView2 and unpackaged Windows App SDK apps until this is resolved. I don't see anything about this on the Windows App SDK roadmap either. This was one of those surprises we ran into later in development that made Windows App SDK basically completely non-viable for unpackaged apps for us.

**Comment by takehark** [comment]
Specifying `WEBVIEW2_BROWSER_EXECUTABLE_FOLDER` environment variable (just used `Environment.SetEnvironmentVariable`) to fixed version runtime directory worked with WinUI 3 (Windows App SDK 1.2.4) both packaged and unpackaged.

https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-fixed-version-runtime-distribution-mode

**Comment by simon-knuth** [comment]
Creating `CoreWebView2Controllers` from custom `CoreWebView2Environment`s appears to be supported in the Windows App SDK now.
Note that `CoreWebView2CompositionController` is not compatible with WinUI3 at the moment.

**Comment by DmitriyKomin** [comment]
I am happy to share that WebView2 custom environment support has been added in WinAppSDK 1.5 (first appearing in [1.5.0-experimental2](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#version-15-experimental-150-experimental2)).

To achieve this scenario, initialize WebView2 with one of the new overrides of _WebView2.EnsureCoreWebView2Async_, and pass in your custom _CoreWebView2Environment_ (and, optionally, custom _CoreWebView2ControllerOptions_):
```
public IAsyncAction EnsureCoreWebView2Async (CoreWebView2Environment environment)
public IAsyncAction EnsureCoreWebView2Async (CoreWebView2Environment environment, CoreWebView2ControllerOptions controllerOptions)
```

**Comment by castorix** [comment]
>  Note that `CoreWebView2CompositionController` is not compatible with WinUI3 at the moment.

COM interfaces like _ICoreWebView2CompositionController_ can be used, but i just noticed they apparently broke transparency in one of the latest Canary versions (https://github.com/MicrosoftEdge/WebView2Feedback/issues/5481)
