### ISSUE TITLE
App.UnhandledException doesn't work at all

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#6153]
### Describe the bug

Hi, how can I show the message when an application was crashed? The App.UnhandledException event doesn't work. I've attached the sample. Also, I've found the issue https://github.com/microsoft/microsoft-ui-xaml/issues/5221 but in my case, it doesn't catch any exceptions from the main thread. Same issue on WindowsAppSDK 1.0 preview 2

### Steps to reproduce the bug

App.xaml.cs
``` csharp
    public partial class App : Application {
        public App() {
            UnhandledException += App_UnhandledException;
            this.InitializeComponent();
        }

        async void App_UnhandledException(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e) {
            var dialog = new Windows.UI.Popups.MessageDialog(e.Exception.ToString());
            await dialog.ShowAsync();
        }

        protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args) {
            m_window = new MainWindow();
            m_window.Activate();
        }

        private Window m_window;
    }
```

MainWindow.xaml.cs
``` csharp
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
        }

        void myButton_Click(object sender, RoutedEventArgs e) {
            throw new ArgumentException("test");
        }
    }
```

### Screenshots

https://i.imgur.com/WnHKKnV.gif

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

### Additional context

[App3.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7410313/App3.zip)

**Comment by Scottj1s** [comment]
App.UnhandledException fix will be available in Windows App SDK 1.2 Preview 2
