### ISSUE TITLE
WinUI 2.x - Can't bind a static property as the setter value of a style

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#6155]
### Describe the bug

Attempting to bind a static property as the setter value of a style results in a crash. This style is inside a control and not in a resource dictionary file + I don't get any design-time/compile-time errors which mean this scenario is supported but it isn't working.

### Steps to reproduce the bug

1. Create a style inside a control's XAML file (not a resource dictionary file).
2. x:Bind a setter to a static property.
3. Build, deploy and run the app.
4. The app will crash.

### Expected behavior

The app shouldn't crash and the binding should work or if it's not supported, a compile time error should be issued.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11

**Comment by Jaiganeshkumaran** [comment]
> I'm not sure what you mean by "Create a style inside a control's XAML file (not a resource dictionary file)." Could you perhaps give a min repro app?
> 
> What is the exception being thrown? can you provide more info?
> 
> x:Bind does some generation of code to wire up the properties, might be the case that some of these properties are null at runtime.

For example, if I have the style with a setter that uses a compiled binding (x:Bind) inside Page.Resources, it doesn't work.

**Comment by StephenLPeters** [comment]
@RealTommyKlein FYI

**Comment by RealTommyKlein** [comment]
@Jaiganeshkumaran - can you share the exception you're getting and the repro class code/markup?  I tried this in a new C# project and it seemed to work - relevant snippets below:

MainPage.xaml.cs:
```
    public sealed partial class MainPage : Page
    {
        public static Windows.UI.Color TestColor { get; } = Windows.UI.Colors.Cyan;
        public MainPage()
        {
            this.InitializeComponent();
        }
    }
```

MainPage.xaml:
```
    <Page.Resources>
        <Style x:Key="testStyle" TargetType="TextBlock">
            <Setter Property="Foreground"  Value="{x:Bind local:MainPage.TestColor}" />
        </Style>
    </Page.Resources>

    <StackPanel>
        <TextBlock Text="testing" Style="{StaticResource testStyle}" />
    </StackPanel>
```
