### ISSUE TITLE
Horizontal Alignments not work for Toggle Switch

### ISSUE THREAD

**Issue by sethuramkumar** [microsoft/microsoft-ui-xaml#6157]
### Describe the bug

Hi Team,
In WinUI-ToggleSwitch control, Horizontal alignment is not working properly.
Refer the below code and Image:
```
<Grid Width="800" Height="300">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        <Border  BorderBrush="Red" Grid.Row="0" Grid.Column="0" BorderThickness="1 1 0 1" />
        <StackPanel Orientation="Vertical" Grid.Column="0">
            <TextBlock Text="Right Aligned" HorizontalAlignment="Center" />
            <ToggleSwitch HorizontalAlignment="Right"  />
        </StackPanel>
        <Border  BorderBrush="Red" Grid.Column="1" BorderThickness="1 1 0 1" />
        <StackPanel Grid.Column="1">
            <TextBlock Text="Left Aligned" HorizontalAlignment="Center" />
            <ToggleSwitch HorizontalAlignment="Left" Grid.Column="1"/>
        </StackPanel>
        <Border  BorderBrush="Red" Grid.Column="2" BorderThickness="1 1 0 1" />
        <StackPanel Grid.Column="2">
            <TextBlock Text="Center Aligned" HorizontalAlignment="Center" />
            <ToggleSwitch HorizontalAlignment="Center" Grid.Column="2"/>
        </StackPanel>
        <Border  BorderBrush="Red" Grid.Column="3" BorderThickness="1 1 0 1" />
        <StackPanel Grid.Column="3">
            <TextBlock Text="Without Alignment" HorizontalAlignment="Center" />
            <ToggleSwitch Grid.Column="3"/>
        </StackPanel>
        <Border  BorderBrush="Red" Grid.Column="4" BorderThickness="0 1 1 1" />
    </Grid>
```

### Steps to reproduce the bug

Declare the ToggleSwitch control in Grid layout.
Give the Horizontal Alignment as Right.
Note the control is not fully aligned in right side.

### Expected behavior

Horizontal alignment should works properly for ToggleSwitch control.

### Screenshots

![image](https://user-images.githubusercontent.com/92511047/138720558-3914203e-db23-484c-85c2-6f604f39672f.png)

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Whether the Horizontal alignment value given or not by default the control is Aligned to left.
Please check and update on this.

**Comment by sethuramkumar** [comment]
Is this issue resolved with above fix?

**Comment by Diegorro98** [comment]
A year from this issue was posted and no actual fix has been released (no workarounds) 😕

**Comment by Gallardo994** [comment]
Giving this thread another bump. Using switches with right alignment is a nightmare. Neither HorizontalAlignment nor HorizontalContentAlignment are respected at all.

![image1](https://i.imgur.com/F7dEvcI.png)
![image2](https://i.imgur.com/Ec8fucE.png)

**Comment by ranjeshj** [comment]
ToggleSwitchThemeMinWidth seems to be the issue.

**Comment by ranjeshj** [comment]
this is a dup of https://github.com/microsoft/microsoft-ui-xaml/issues/3652
