### ISSUE TITLE
ListView/GridView group headers do not have rounded corner

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#6158]
### Describe the bug

The headers in a grouped `ListView` or `GridView` do not have rounded corners

### Steps to reproduce the bug

1. Open the XAML control gallery
2. Navigate to the `NavigationView` sample page
3. Scroll down to the grouped list
4. Focus one group header
5. The focus border is using square corners instead of the rounded corners available for all the other list/grid items
![image](https://user-images.githubusercontent.com/20152272/138723157-0f394815-ee8c-4c00-87a3-46ef636f93f2.png)

### Expected behavior

The group header should also use rounded corners

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by dansmor7** [comment]
Another reason why ListView and GridView templates should be exposed (#6981). Otherwise, fixing this would require an OS update.
