### ISSUE TITLE
Exception on startup with .Debug NetNative builds using release packages

### ISSUE THREAD

**Issue by adclements** [microsoft/microsoft-ui-xaml#616]
Using release version of the nuget package (this does not happen with the -prerelease versions), I am getting a COM exception thrown on app startup saying that the XamlControlsResources class is not registered - coming from this generated line:

        private object Activate_10_XamlControlsResources() { return new global::Microsoft.UI.Xaml.Controls.XamlControlsResources(); }

This only happens in our debug .NetNative build configuration, not in our release .NetNative build configuration. 

Tested with 2.1.1.190405004(.1) and 2.1.190319001-prerelease versions, using RS5.

**Comment by jevansaks** [comment]
Andrew shared the .appx offline. I cracked the Debug .NET Native .appx in that folder and I see the AppxManifest.xml is missing a PackageDependency for Microsoft.UI.Xaml.2.1. This would explain why the type can’t be activated. Is it possible you’re hand-rolling your manifest or have custom MSBuild logic that needs to account for the new framework package dependency?

```xml
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.16299.0" MaxVersionTested="10.0.17763.0"/>
    <PackageDependency Name="Microsoft.NET.Native.Framework.Debug.2.1" MinVersion="2.1.26424.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"/>
    <PackageDependency Name="Microsoft.NET.Native.Runtime.2.1" MinVersion="2.1.26424.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"/>
    <PackageDependency Name="Microsoft.VCLibs.140.00" MinVersion="14.0.26706.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"/>
    <PackageDependency Name="Microsoft.Advertising.Xaml" MinVersion="10.1705.4.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"/>
  </Dependencies>
```

**Comment by brstaffoMS** [comment]
We're seeing this issue as well. What was the solution in this particular case?

**Comment by jevansaks** [comment]
@brstaffoMS can you share a diagnostic log from the build of the app? @adclements never shared what the resolution was so I'm not sure if it's a systemic issue.

Also @SvetBonev do you have any ideas about why Debug .NET Native compile would potentially be missing the nuget `<PackageDependency` for Microsoft.UI.Xaml?

**Comment by brstaffoMS** [comment]
We are actually seeing this when creating a Master .NET Native build of our app. To work around this issue, we are manually inserting the dependency into the Package.appxmanifest file. For some reason, our **non** .NET Native builds (Debug, Release) automatically add that dependency into the AppxManifest during the build. However, Master is requiring us to do this manually.

**Comment by adclements** [comment]
I looked into this again today. We do not have any custom MSBuild logic as part of our build, nor do we dynamically create or inject anything into our manifest.

The project files just contain a package reference like this:
`<PackageReference Include="Microsoft.UI.Xaml">`
`<Version>2.1.190405004</Version>`
`</PackageReference>`

and have this defined in a resource dictionary
`<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>`

**Comment by brstaffoMS** [comment]
What did you do to work around the issue, @adclements? We simply added the dependency to our Package.appxmanifest: 

<Dependencies>    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.16299.0" MaxVersionTested="10.0.17763.0" />

    <PackageDependency Name="Microsoft.UI.Xaml.2.1" MinVersion="2.11904.5004.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />

  </Dependencies>

**Comment by adclements** [comment]
I haven't tried to work around it.  It does not affect our Release build (which also uses .Net Native) only our 'Debug .Net Native' build configuration.  Because of how long it takes to build (20 minutes) we only use that configuration for debugging .Net Native issues, for regular debugging we just use our Debug configuration.  If I really needed to do .Net Native debugging, I could also just use a pre-release version of the nuget package, where the problem does not occur.

**Comment by ad1Dima** [comment]
> We simply added the dependency to our Package.appxmanifest:
> 
> ```
> <PackageDependency Name="Microsoft.UI.Xaml.2.1" MinVersion="2.11904.5004.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
> ```
thx. This helps!

**Comment by jevansaks** [comment]
Just FYI, we're still trying to follow up to find the owners in VS to transfer this issue to!

**Comment by jevansaks** [comment]
This appears to be an issue with .NET Native which was mostly fixed in VS2019. If you are still seeing something like this in VS2019 then please file a bug through Visual Studio's "Send feedback" UI.

**Comment by dfmacom** [comment]
> This appears to be an issue with .NET Native which was mostly fixed in VS2019. If you are still seeing something like this in VS2019 then please file a bug through Visual Studio's "Send feedback" UI.

Hi @jevansaks, could you by chance provide some perspective on similar GitHub issue #9208 whenever you may have a chance? I am having the same type of issued described in here and in #8920/#308, and the fixes outlined in these seem not to do the trick. Thank you

https://github.com/microsoft/microsoft-ui-xaml/issues/9208
