### ISSUE TITLE
WebView2 on UWP doesn't support IME

### ISSUE THREAD

**Issue by zhuxinghan** [microsoft/microsoft-ui-xaml#6167]
### Describe the bug

WebView2 on WinUI 3 app does support IME, but WebView2 on WinUI 2.8 prerelease doesn't.

### Steps to reproduce the bug

1. Create a UWP project
2. Install WinUI 2.8 prerelease which provides WebView2
3. Add a WebView2 to MainPage
4. Navigate WebView2 to any page that allows input
5. For non-English users who use IME to input, note that they has no way to type text into WebView2 with IME

### NuGet package version

2.8 prerelease

### Windows app type

- [X] UWP
- [ ] Win32

### Additional context

Here is a minimum project that can reproduce the problem. It contains a single WebView2 on MainPage and navigates it to a textarea element.
[UWPWebView2NotSupportIME.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7423510/UWPWebView2NotSupportIME.zip)

**Comment by champnic** [comment]
I just created https://github.com/MicrosoftEdge/WebView2Feedback/issues/1899 to track. We already had a scenario internally and are currently working on this. Thanks!
