### ISSUE TITLE
📢Announcing: WinUI 3 in Windows App SDK 1.0 Preview 3 📦

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#6172]
We've just shipped the latest version of WinUI 3, which is a part of Windows App SDK 1.0 preview release! This release includes new features, bug fixes and provides access to APIs and features we are intending to include in the next stable release.   

  

## Shipping WinUI 3 as a part of the Windows App SDK 

  

In order to use this version of WinUI 3, you'll download the **Windows App SDK (Preview)** Visual Studio Extension (VSIX) to get started. The Windows App SDK VSIX includes WinUI project templates that you'll use to build your WinUI 3 app, as well as access to other [Windows App SDK components](https://docs.microsoft.com/windows/apps/windows-app-sdk/release-channels#features-available-by-release-channel). The Windows App SDK package includes a reference to the WinUI 3 NuGet package.  

 

For more on the Windows App SDK, see their [documentation](https://docs.microsoft.com/windows/apps/windows-app-sdk) and [repository](https://github.com/microsoft/WindowsAppSDK). For installation instructions, see  [Set up your development environment](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment).  

  

**NOTE**: The Windows App SDK was previously known by the code name Project Reunion. Some SDK assets may still use the code name, but these assets will be renamed in a future release. The term Project Reunion may also be used when referring to an existing asset or a specified earlier release. 

  

## What's new 

  

This release of WinUI 3 is focused on supporting unpackaged apps. Please view [Instructions for WinUI 3 unpackaged desktop apps](https://aka.ms/winui3/unpackaged-apps) to configure your WinUI 3 application to support unpackaged deployment. 

 

### Stability 

This release includes unstable APIs and does not support building production apps. If you'd like to use WinUI 3 to build a production app, feel free to continue using the latest [Windows App SDK 0.8 release](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel). 

 

### Known Issues 

For a list of all the known issues for this Windows App SDK 1.0 preview release, please see the [Windows App SDK release notes](https://aka.ms/windowsappsdk/1.0-preview-3-release-notes). 

- Unpackaged WinUI 3 applications are **only supported on Windows versions 1909 and later**.
- Unpackaged WinUI 3 applications are **supported on x86 and x64,** arm64 support will be added in the next stable release.
- **Single-project MSIX Packaging Tools** for [VS 2019](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingTools) or [VS 2022](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17) is required for unpackaged apps.
- In an unpackaged app, you may receive a prompt to install .NET 3.5; if you do, you can ignore it.
- Some APIs are not currently supported in unpackaged apps. We are aiming to fix this in the next stable release. A few examples:
  - [ApplicationData](/uwp/api/Windows.Storage.ApplicationData)
  - [StorageFile.GetFileFromApplicationUriAsync](/uwp/api/Windows.Storage.StorageFile.GetFileFromApplicationUriAsync)
  - [ApiInformation](/uwp/api/Windows.Foundation.Metadata.ApiInformation) (not supported on Windows 10)
  - [Package.Current](/uwp/api/windows.applicationmodel.package.current)
- ListView, CalendarView, and GridView controls are using the incorrect styles and we are aiming to fix this in the next stable release. 

## Getting started  

First, you'll need to set up your dev environment with the appropriate technologies. See our documentation for installation instructions and more information on project types:  

  

**[Install the Windows App SDK](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment)** 

  

**[Create WinUI 3 Projects](https://docs.microsoft.com/windows/apps/winui/winui3/create-winui3-projects)** 

  

While you're developing, check out the [API Reference documentation](https://docs.microsoft.com/windows/winui/api/). 

  

Take a look at our walk-through docs: 

  

- [Get started developing apps with WinUI 3](https://docs.microsoft.com/windows/apps/winui/winui3/get-started-winui3-for-desktop) 

- [Build a basic WinUI 3 app for desktop](https://docs.microsoft.com/windows/apps/winui/winui3/desktop-build-basic-winui3-app) 

  

You can also update your existing WinUI 3 app to use the new Windows App SDK 1.0 preview release using these instructions: [Update existing projects to the latest release of the Windows App SDK](https://docs.microsoft.com/windows/apps/project-reunion/update-existing-projects-to-the-latest-release). 

  

We love feedback! We encourage you to file any bug, big or small, on our repo using [this template](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=). Knowing which issues and features are important and/or critical to our customers highly influences which ones we tackle. Even though we ship with the Windows App SDK, please continue to file WinUI-specific bugs on this repo.    

  

## Using WinUI 3 and the Windows App SDK with our ecosystem partners 

  

This latest release is in the process of being integrated into several other important ecosystem technologies. To test out and follow that progress, check out some of our partner technologies below (note that some of these technologies may not yet be available for Windows App SDK 1.0 preview): 

  

- [Actipro Software](https://www.actiprosoftware.com) is migrating their vast UI control offerings over to WinUI 3, including their SyntaxEditor code editor, propertygrid, native type edit boxes, docking/MDI, charts, and more. 

  

- [DevExpress](https://www.devexpress.com/winui/): DevExpress has released 20 new WinUI controls with Windows App SDK 0.8 support, including the Data Grid, Scheduler, Charts, Ribbon Toolbar, and more. All 20 UI components are available free-of-charge. 

  

- Esri: [ArcGIS Runtime SDK for .NET]( https://developers.arcgis.com/net/) adds mapping, spatial analytics, and location intelligence capabilities to your apps on Android, iOS, and Windows. Support for WinUI 3 is [now available]( https://links.esri.com/arcgis-runtime-dotnet-sdk-winui-blog). 

  

- [GrapeCity](https://www.grapecity.com/): [The ComponentOne WinUI controls](https://www.grapecity.com/componentone/winui-controls/?utm_source=Microsoft_GitHub&utm_medium=Dynamic&utm_campaign=Updated-WinUI-description_08/12/21) support modern desktop apps (Win32) and include calendar, accordion, input and our fast and flexible datagrid, FlexGrid. 

  

- [Infragistics](https://www.infragistics.com/products/winui): Ultimate UI for WinUI brings business critical, high performing, and feature rich line of business controls to your apps that target any platform that runs Windows (including Windows on ARM64). 

  

- [Syncfusion](https://www.syncfusion.com/winui-controls): Updated their projects to Microsoft.ProjectReunion from Microsoft.WinUI following upgrade instructions. All their controls are working fine. 

  

- [Telerik UI for WinUI](https://www.telerik.com/winui): the market first UI controls suite for crafting Win32 and UWP apps with WinUI 3, comes with feature-rich controls like Ribbon, DataGrid, Charts, Gauges, Barcode, and more. 

  

- [Uno Platform](https://github.com/unoplatform): Use WinUI 3 – Windows App SDK 0.8, XAML and C# to build pixel-perfect, single-codebase, native applications that can run on Web, Desktop and Mobile. It is free, open-source and available today. 

  

- [Windows Community Toolkit (Microsoft)](https://aka.ms/wct-winui3): The WCT is currently working on supporting Windows App SDK 0.8 RC. It provides tons of new controls and capabilities for use in your WinUI app. You can check out their open source repo [here](https://aka.ms/windowstoolkit). 

  

## What's next 

To keep up with progress being made on WinUI 3, please see our [feature roadmap](https://aka.ms/winui3/feature-roadmap) which gets updated regularly. We also give monthly updates on our WinUI Community Calls, where you can directly ask the team any questions you have.

**Comment by IndianaGary** [comment]
I've been playing with a Maui-based WinUI 3 desktop app and recently updated my Microsoft.WindowsAppSDK nuget package to 1.0.0-preview3. Upon testing the app it crashes with "Cannot find Microsoft.WindowsAppSDK.Bootstrap.dll". After reverting to 1.0.0-experimental1, the problem disappears. Am I doing something wrong?

**Comment by seven-mile** [comment]
@IndianaGary I don't know well about MAUI-based WinUI3. But in preview release compared with experimental1 they renamed `Microsoft.WindowsAppSDK.Bootstrap.dll` to `Microsoft.WindowsAppRuntime.Bootstrap.dll`. Maybe some of your MAUI supportting library hasn't been update to preview channel yet.

**Comment by IndianaGary** [comment]
Basically, Maui maps Maui controls to WinUI 3 controls to support Windows. It's a cross-platform UI abstraction layer based upon Xamarin XAML syntax.  I'll bet that your surmise is likely correct and I'll simply need to wait for Maui Preview 10 due out in the next few weeks.

**Comment by kmgallahan** [comment]
@gabbybilka Now that WASDK 1.0 has been released this issue and all of these older announcements can probably be closed to help with the issue count:

#6049
#5906
#5789
#5651
#5262
#5260
#5195
#5102
#4682
#4480
#4156
#3620
#2917

Could add a note to direct any further comments to the WASDK release issue.

Similarly, there are several old WinUI Community Call issues still open:

#6050 
#5281
#4816
#4150
#3791

**Comment by gabbybilka** [comment]
Thanks @kmgallahan for aggregating this list of stale issues and giving me the nudge I needed 😊 'Tis the season for some issue cleanup.

For this thread, please check out the WASDK 1.0 release for the latest updates on WinUI 3 in Windows App SDK: #6325

**Comment by kmgallahan** [comment]
@gabbybilka 4 leftovers from above list:

![Screenshot 2021-11-23 170547](https://user-images.githubusercontent.com/5379488/143136654-abeafb51-328f-47c7-aba7-4ff20ceabe04.jpg)

Thanks for the cleanup.
