### ISSUE TITLE
WinUI Design Toolkit Bug: ScrollBar is narrow unfocused

### ISSUE THREAD

**Issue by infraprobono** [microsoft/microsoft-ui-xaml#6178]
## WinUI Toolkit Bug Report

---

**ScrollBar**

**The scroll bar is narrow when unfocused and I need it wide by default when ScrollBar is shown **

**WinUI3, ProjectReunion 0.8.1**

**Additional context:**

**Comment by alejo4000** [comment]
@infraprobono is this an issue with the Figma toolkit, or something to do with the XAML and implementation of the Scrollbar?

**Comment by alejo4000** [comment]
Removing Team-design / area-designtoolkit labels, I don't think this is an issue with the Toolkit for WinUI 2.7.

**Comment by StephenLPeters** [comment]
This issue doesn't have enough info to be actionable from our end.
