### ISSUE TITLE
Focus moves unexpected after PointerReleased event

### ISSUE THREAD

**Issue by temamarvel** [microsoft/microsoft-ui-xaml#6179]
### Describe the bug

The focus moved to an element with TabIndex=0 after click on other element. Even if the clicked element handles PointerPressed event.
Steps to reproduce the bug
Please provide any required setup and steps to reproduce the behavior.

### Steps to reproduce the bug

1. Run test app
2. Click on the orange border. Focus moved to blue_border wich has TabIndex = 0;
3. Click on the "Click" button. Focus moved to "Click" button
4. Click on the green border. Focus moved to blue_border wich has TabIndex = 0. Again.

But if you move through elements using "Tab" key, focus moves predictably: blue_border -> orange_border -> "click" button -> green border -> textbox.

### Expected behavior

The clicked element keeps focus after click, like the "click" button does.

### Screenshots

![TCyJp2LSYs](https://user-images.githubusercontent.com/10881721/139250010-97581a19-a521-4773-bb84-90aa5f126993.gif)

### NuGet package version

WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

[ReportsTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7433750/ReportsTest.zip)

**Comment by BorzillaR** [comment]
I think a key point is a difference of such behavior from Wpf.

- In Wpf, the focus sets on the mouse down event. In WinUI, focus sets on the pointer up event.
- In Wpf, the unhandled click moves the focus to ScrollViewer. In WinUI, the unhandled click moves the focus to the first focusable item.

@StephenLPeters , could you explain, please, such difference and the main reasons for it? I think it would be better if this behavior will be compatible with Wpf.

**Comment by StephenLPeters** [comment]
I don't have context on why these changes were made, @MikeHillberg or @RBrid might.

**Comment by MikeHillberg** [comment]
> In Wpf, the focus sets on the mouse down event. In WinUI, focus sets on the pointer up event.

I don't see that in WPF. The way buttons are intended to work is on mouse/pointer up, so that if you mouse-down, move away from the button, then mouse up, the button doesn't click. (If you mouse-down, move away, then back, _then_ mouse-up, the button does click.)
