### ISSUE TITLE
NavigationView Pane menu content disappears when rezising while Animations have been disabled

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/microsoft-ui-xaml#618]
**Describe the bug**
While turning off animations on Settings/Ease of Access/Display[Simplify and personalize Windows][Show animcations in Windows] and resizing the application window that has a NavigationView Expanded when it switches to Compact Mode but the Pane which usually stays in Expanded Mode, is causing the content to go away. 

**Steps to reproduce the bug**
[Prerequisite] Disabled animations on Windows throught Settings
1. Open an app that uses Navigation View (ex. Feedback Hub)
2. Start with the app in a wider mode so that NavigationView Pane is shown side-by-side.
3. Start resizing the app window enought that it reaches the threshold where it changes to Compact mode

**Expected behavior**
The navigation pane changes to Compact Mode, and both, icons and content are visible in Overlay mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/13546698/56761359-03307f80-6752-11e9-977c-6c839e9c7f71.png)

**Version Info**
WinUI 2.1 on 19H1 RTM

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| March 2019 Update (18362)      | Yes                        |
| October 2018 Update (17763)   | Yes                        |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes                        |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by YuliKl** [comment]
I've seen the problem when using remote desktop. Which makes sense given that RD disables animations by default.

**Comment by jevansaks** [comment]
@kaiguo related to the IsOpen pane stuff you recently changed?

**Comment by kaiguo** [comment]
> @kaiguo Kai Guo FTE related to the IsOpen pane stuff you recently changed?

This looks like the SplitView bug. https://microsoft.visualstudio.com/OS/ft_xamlcon/_queries/query/12c35ba7-ad9e-4d99-8bde-275be727827b/

It's still assigned to me, I'll take look.

**Comment by jevansaks** [comment]
Unfortunately we don't think we can work around this because SplitView's internal state is out of sync in this case. Adding needs-winui-3 label and we'll revisit post WinUI 3.0.
