### ISSUE TITLE
WinUI3 preview 3 - Window cannot be moved if content is moved into the titlebar when running unpackaged

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#6185]
### Describe the bug

When running as an unpackaged app, a window with the ExtendsContentIntoTitleBar property set to true cannot be moved when dragging the element set via SetTitleBar(). Running the same app in packaged mode works fine.

### Steps to reproduce the bug

1. Create a new packaged c# WinUI app
2. Set ExtendsContentIntoTitleBar to true and define a titlebar UI element with SetTitleBar()
3. Observe that the window can be moved by dragging the titlebar element
4. Transform the application into an unpackaged app
5. Moving the window is now no longer possible

### Expected behavior

Window should be movable

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by pratikone** [comment]
not a dupe. I will try repro it as unpackaged app

**Comment by imechZhangLY** [comment]
Same problem.

**Comment by sh0622-kim** [comment]
@pratikone I am also having the same problem. Do you have any way to solve this?

**Comment by lhak** [comment]
The workaround from https://github.com/microsoft/WindowsAppSDK/issues/1815 also fixes this issue.

**Comment by lhak** [comment]
Seems to be fixed in 1.0.1
