### ISSUE TITLE
Working with Mica

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#6186]
I know Mica is not supported yet. However, with the help of some PInvoke functions, Mica is activated on WPF apps
![image](https://user-images.githubusercontent.com/9213496/139205690-16406300-9ffe-4c67-9756-8a95f6e82f79.png)

so I tried to do the same in WinUI3 preview 3

```
[DllImport("dwmapi.dll")]
        public static extern int DwmSetWindowAttribute(IntPtr hwnd, DwmWindowAttribute dwAttribute, ref int pvAttribute, int cbAttribute);

        [Flags]
        public enum DwmWindowAttribute : uint
        {
            DWMWA_USE_IMMERSIVE_DARK_MODE = 20,
            DWMWA_MICA_EFFECT = 1029
        }
        public static void EnableMica(IntPtr source, bool darkThemeEnabled)
        {
            int trueValue = 0x01;
            int falseValue = 0x00;

            // Set dark mode before applying the material, otherwise you'll get an ugly flash when displaying the window.
            if (darkThemeEnabled)
                DwmSetWindowAttribute(source, DwmWindowAttribute.DWMWA_USE_IMMERSIVE_DARK_MODE, ref trueValue, Marshal.SizeOf(typeof(int)));
            else
                DwmSetWindowAttribute(source, DwmWindowAttribute.DWMWA_USE_IMMERSIVE_DARK_MODE, ref falseValue, Marshal.SizeOf(typeof(int)));

            DwmSetWindowAttribute(source, DwmWindowAttribute.DWMWA_MICA_EFFECT, ref trueValue, Marshal.SizeOf(typeof(int)));
        }

public MainWindow()
        {
            this.InitializeComponent();
            IntPtr hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
            EnableMica(hwnd, true);
        }
```

TitleBar activates Mica well, but not Windows content

![image](https://user-images.githubusercontent.com/9213496/139206146-07313bdb-b8be-4f0a-ba7e-2d1c3b13ebb4.png)

Is there a solution?😁

**Comment by Link1J** [comment]
> But it seems you should somehow set the background of ClientArea to transparency... Why WPF can handle it automatically?
@seven-mile It doesn't, the example sets the background to transparent. Like you recommended, and is the exact thing WinUI 2 does. 
https://github.com/Difegue/Mica-WPF-Sample/blob/c579d038f762053e84b03f24acf0c8fc24e13d31/MicaTest/MainWindow.xaml#L9

**Comment by Lukespacewalker** [comment]
Window in WinUI 3 doesn't have Background property. How can I set it to transpararent?

**Comment by seven-mile** [comment]
> Window in WinUI 3 doesn't have Background property. How can I set it to transpararent?

I think that's why Mica is still not out?

**Comment by ghost1372** [comment]
> > Window in WinUI 3 doesn't have Background property. How can I set it to transpararent?
> 
> I think that's why Mica is still not out?

I changed the Windows style as mentioned above but nothing happened😫

**Comment by jonasnordlund** [comment]
I read that this method may no longer be supported since Windows 11 Build 22494.1000? I can't confirm this myself though.

**Comment by dongle-the-gadget** [comment]
> I read that this method may no longer be supported since Windows 11 Build 22494.1000? I can't confirm this myself though.

Can't confirm on 22494 either, but it surely doesn't work for 22504+

**Comment by ghost1372** [comment]
@seven-mile FYI, Mica Sample available in [WASDK-Sample Repo](https://github.com/ghost1372/WindowsAppSDK-Samples/tree/main/Samples/Mica), but only for C++, can you convert it to c#?

**Comment by dongle-the-gadget** [comment]
Doesn't look like it's going to work very well in WPF since it requires the use of a Visual layer, thus creating the airspace bug.

**Comment by IcySnex** [comment]
You need to set the background of your application to transparent.

You can do this via Win32 API calls. I have created a sample project here: https://github.com/IcySnex/WinUI3-Transparent-Mica-Acrylic-Blurred.
You can also look at a video here: https://www.youtube.com/watch?v=mfS8PT9Z3u8.
But be aware that you need to have at least the WindowsAppSDK version 1.1 - preview 1.

**Comment by dongle-the-gadget** [comment]
That method depends on a private API that has been removed since 22494+ (in 22523 and later it's replaced. The proper way is to use `Windows.UI.Composition.Compositor`, however this approach requires either a swapchain or a `HwndHost` (or some other way idk), the latter causes the airspace problem.
