### ISSUE TITLE
Uncoditional file copies in _AddXamlWinmdToPackageLayoutRoot may lead to sharing violations during the build

### ISSUE THREAD

**Issue by srdjanjovcic** [microsoft/microsoft-ui-xaml#6190]
### Describe the bug

We have several reports of customers hitting sharing violations during the build, failing to copy Microsoft.UI.Xaml.winmd:

```
Unable to copy file “C:\Users\mosun.nuget\packages\microsoft.ui.xaml\2.6.1\buildTransitive… \lib\uap10.0\Microsoft.UI.Xaml.winmd” to “C:\Users\mosun\source\repos\Unify\Uwp\src\Debug\x64\bin\SurfaceAppPackage\Microsoft.UI.Xaml.winmd”. The process cannot access the file "C:\Users\mosun\source\repos\Unify\Uwp\src\Debug\x64\bin\SurfaceAppPackage\Microsoft.UI.Xaml.winmd’ because it is being used by another process.
```

It turns out that target [_AddXamlWinmdToPackageLayoutRoot](https://github.com/microsoft/microsoft-ui-xaml/blob/bb516c69eb06809b78bae01a5184739372f77479/build/NuSpecs/MUXControls-Nuget-Common.targets#L68) has unconditional copy of files, and that, if `<Copy>` task invocation is changed to:

```
<Copy SourceFiles="@(XamlWinmd)" 
      DestinationFiles="@(XamlWinmd -> '$(OutDir)\%(Filename)%(Extension)')" 
      SkipUnchangedFiles="true"
      />
```

...then problem goes away. Relevant feedback ticket is:

https://developercommunity.visualstudio.com/t/UWP-build-keep-failing-due-to-unable-to-/1538155

_(follow internal links on the feedback ticket to discover more relevant issues, including DTS from a customer outside MSFT)_

### Steps to reproduce the bug

Please follow up with CSS engineer who opened DTS linked internally, or with internal customers on the feedback.

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by StephenLPeters** [comment]
@codendone and @evelynwu-msft FYI

**Comment by evelynwu-msft** [comment]
This is WinUI 2.6, so looping in @ranjeshj and moving to Controls team.

**Comment by StephenLPeters** [comment]
ah, my bad.  @llongley FYI as well

**Comment by hjharvey-MSFT** [comment]
@llongley  I have a VM that Repros the issue. Msg me internally and I can get you a copy
