### ISSUE TITLE
Proposal: Update style of WebView2 scrollbars

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#6192]
# Proposal: Update style of WebView2 scrollbars

## Summary

Add support for automatically hiding scrollbars.
Add support for the setting to turn that off.
Update the style of WebView2 scrollbars

## Rationale

* consistency

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by StephenLPeters** [comment]
@codendone @chigy @predavid FYI

**Comment by krschau** [comment]
At least for scroll bar style, this is something that can be done by setting an environment variable from inside your application:

`Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--enable-features=OverlayScrollbar,OverlayScrollbarWinStyle,OverlayScrollbarWinStyleAnimation");`
