### ISSUE TITLE
Accessibility: Can open the `SplitButton` options using tab navigation

### ISSUE THREAD

**Issue by lyf6lyf** [microsoft/microsoft-ui-xaml#6193]
### Describe the bug

Accessibility: Can open the `SplitButton` options using tab navigation.

### Steps to reproduce the bug

1. Open XAML Control Gallery
2. Search SplitButton and open the sample page
3. Press "tab" several times to focus on the `SplitButton`
4. When we press Enter, the primary button command is executed. But we don't have a way to display the dropdown options. Also, we cannot set different access key to the primary button and secondary button.

### Expected behavior

Users can open the `SplitButton`'s dropdown option when use keyboard navigation.

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (22471)

**Comment by StephenLPeters** [comment]
The keyboard command to open a split button is Alt+Down. This is by design and is standard across many UI platforms. You can see this in action in many of the office programs.

**Comment by lyf6lyf** [comment]
@StephenLPeters  Thanks. Is there any way to assign two access keys to the Primary button and the Options button?
