### ISSUE TITLE
Issue with "use unicode utf-8 for worldwide language support" and ICON

### ISSUE THREAD

**Issue by bithaha** [microsoft/microsoft-ui-xaml#6202]
### Describe the bug

when  "use unicode utf-8 for worldwide language support"  is set,  <NavigationViewItem.Icon="symbolenum">  output grabled code

![image](https://user-images.githubusercontent.com/10111646/139576655-c29b1980-a647-4fc3-9f20-b19d2bf54594.png)

`                <NavigationViewItem  Content="item2" Tag="SamplePage2" Icon="Accept" /> 
`

However, the following code can be displayed normally

```
  <NavigationViewItem Content="item1"  Tag="SamplePage1" >
                    <NavigationViewItem.Icon>
                        <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE8FB;"/>
                    </NavigationViewItem.Icon>
    </NavigationViewItem>
```

![image](https://user-images.githubusercontent.com/10111646/139576735-1b3cb849-ad6d-4403-8f42-6d89f11a782c.png)

### Steps to reproduce the bug

1, select “use unicode utf-8 for worldwide language support”
2, use the following code

```
<NavigationView x:Name="nvSample" Header="sample" SelectionFollowsFocus="Enabled" IsBackButtonVisible="Collapsed" IsSettingsVisible="False">
            <NavigationView.MenuItems>
                <NavigationViewItem Content="item1"  Tag="SamplePage1" >
                    <NavigationViewItem.Icon>
                        <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE8FB;"/>
                    </NavigationViewItem.Icon>
                </NavigationViewItem>
                <NavigationViewItem  Content="item2" Tag="SamplePage2" Icon="Accept" />
                <NavigationViewItem  Content="item3" Tag="SamplePage3" />
                <NavigationViewItem  Content="item4" Tag="SamplePage4" />
            </NavigationView.MenuItems>
             <Frame x:Name="contentFrame"/>
        </NavigationView>
```

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@MarissaMatt @licanhua do you know what might be going on here?

**Comment by MarissaMatt** [comment]
@bithaha is your app using WinUI 2.6 or 2.7? @StephenLPeters it might have something to do with the fallback icon being selected for symbol icon when unicode utf-8 is selected. I will talk to design as well to learn more about icon behavior with unicode utf-8 enabled.

**Comment by bithaha** [comment]
> @bithaha is your app using WinUI 2.6 or 2.7? @StephenLPeters it might have something to do with the fallback icon being selected for symbol icon when unicode utf-8 is selected. I will talk to design as well to learn more about icon behavior with unicode utf-8 enabled.

Win3 1.0 preview 3  c++ Version
