### ISSUE TITLE
Setting a Style using a VisualState.Setter

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#6203]
### Describe the bug

I tried to set the `Style` of a `Button` using a `VisualState.Setter`. This doesn't work. The style doesn't change when the VisualState is triggered.

I tested it using `Microsoft.WindowsAppSDK 1.0.0-preview3`.

### Steps to reproduce the bug

Create a new WinUI3 project and modify the code of the MainWindow.xaml to.

```xml
<StackPanel HorizontalAlignment="Center"
        VerticalAlignment="Center"
        Orientation="Horizontal"
        Spacing="12">
    <Button x:Name="myButton"
        Click="myButton_Click"
        Content="Click Me" />
    <CheckBox x:Name="checkBoxState1"
            Content="visualState1" />
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="visualStateGroup1">
            <VisualState x:Name="visualState1">
                <VisualState.Setters>
                    <Setter Target="myButton.(Button.Style)" Value="{StaticResource AccentButtonStyle}" />
                </VisualState.Setters>
                <VisualState.StateTriggers>
                    <StateTrigger IsActive="{x:Bind IsOn(checkBoxState1.IsChecked), Mode=OneWay}" />
                </VisualState.StateTriggers>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
</StackPanel>
```

Also add the following code to the codebehind.

```cs
private bool IsOn(bool? b) => b == true;
````

### Expected behavior

The state should change to the AccentButtonStyle when the checkbox is checked. The same code works in a UWP app.

### Screenshots

![image](https://user-images.githubusercontent.com/9335559/139635724-ce81b747-cf17-4d54-8805-0d5cdd3f2bfb.png)

### NuGet package version

Microsoft.WinUI 3.0.0-preview4.210210.4

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by StephenLPeters** [comment]
@RealTommyKlein FYI, I confirmed this markup does work in Winui2

**Comment by RealTommyKlein** [comment]
@StephenLPeters - seems like a framework issue and not an x:Bind issue, can you redirect to them?  Moving the VisualStateGroup to a grandparent of the elements in question seemed to work. e.g:

```
    <Grid>
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup x:Name="visualStateGroup1">
                <VisualState x:Name="visualState1">
                    <VisualState.Setters>
                        <Setter Target="myButton.(Button.Style)" Value="{StaticResource AccentButtonStyle}" />
                    </VisualState.Setters>
                    <VisualState.StateTriggers>
                        <StateTrigger IsActive="{x:Bind IsOn(checkBoxState1.IsChecked), Mode=OneWay}" />
                    </VisualState.StateTriggers>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>
        <StackPanel HorizontalAlignment="Center"
        VerticalAlignment="Center"
        Orientation="Horizontal"
        Spacing="12">
            <Button x:Name="myButton"
        Click="myButton_Click"
        Content="Click Me" />
            <CheckBox x:Name="checkBoxState1"
            Content="visualState1" />

        </StackPanel>
    </Grid>
```

Additionally in the original repro, removing the x:Bind in the StateTrigger in favor of something else like `<StateTrigger IsActive="True" />` still repro'd the issue.  Thanks!

**Comment by StephenLPeters** [comment]
@sonnemaf FYI on the grandparent work around that might help you get past this issue while we investigate it.  @chrisglein and @codendone FYI

**Comment by HO-COOH** [comment]
@StephenLPeters   This 3 year old issue still reproducible today. Reopen please.
