### ISSUE TITLE
WinUI 3 1.0 Preview 3 is crashing with ResourceMap Not Found. (0x80073B1F) 

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/microsoft-ui-xaml#6204]
### Describe the bug

I did upgrade for my app from Windows App SDK 0.8 to 1.0 preview 3, but I face issue with combination of NumberBox and xmlns across local files in project. If I use everything, like it was, but without NumberBox, everything is okay. But if i use NumberBox, I have to remove all xmlns into my project. Problem is currently only with NumberBox, I didn't see any other components causing this bug. I think, it could be relate to bug #4499.

### Steps to reproduce the bug

Have some project with WinUI Community toolkit and this code
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/16069721/139692775-707abd2c-edb2-4e0d-bb69-f073e0c6c35f.png">

Another step: Upgrade from Win App SDK 0.8 to 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@MikeHillberg @evelynwu-msft FYI

**Comment by JanRajnoha** [comment]
Any update?

**Comment by JanRajnoha** [comment]
@MikeHillberg @evelynwu-msft Do you know something about it?

**Comment by MikeHillberg** [comment]
Hi - any more info on the crash? (Like a call stack). 

What does it mean to remove the xmlns? (Doesn't it fail to build at that point?)

**Comment by JanRajnoha** [comment]
<img width="701" alt="image" src="https://user-images.githubusercontent.com/16069721/146218023-51100369-9b17-45ae-b914-120c8cef4e31.png">

<img width="562" alt="image" src="https://user-images.githubusercontent.com/16069721/146218269-2cb66385-d59b-44fd-998a-078b61920a47.png">

Build is ok, but when i want to open something with number box, i get this error

**Comment by JanRajnoha** [comment]
Any information?

**Comment by dylech30th** [comment]
Have you ever checked the `Output` window? AFAIK currently most of the useful information of exceptions in WinUI 3 can be found in the output window, the exception object itself is rather useless

**Comment by JanRajnoha** [comment]
This is only output i got for exception from Debug view of Output
<img width="841" alt="image" src="https://user-images.githubusercontent.com/16069721/148582649-6cbbb6f9-a153-456a-97ab-5bb18f25ecfe.png">

**Comment by JanRajnoha** [comment]
@MikeHillberg

**Comment by JanRajnoha** [comment]
Call stack
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/16069721/151067697-836cbf25-6136-4011-b63b-346935d6b960.png">

**Comment by JanRajnoha** [comment]
I did not find problem source, but I replace it with text box with masking and it is okay, so for now, this is workload. In clean project this is not problem, so probably i made mistake somewhere.
