### ISSUE TITLE
CornerRadius results in unwanted gap at the right and bottom side

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#6207]
**Describe the bug**
When I use panels with a border radius. The panels will get unwanted margins at the right and bottom.

**Steps to reproduce the bug**
``` xaml
<Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="80"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="80"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Border Background="Red" CornerRadius="20"/>
        <Border Grid.Column="1" Background="Green" CornerRadius="20"/>
        <Border Grid.Row="1" Background="Red" CornerRadius="20"/>
        <Border Grid.Row="1" Grid.Column="1" Background="Green" CornerRadius="20"/>
 </Grid>
```

You can see the white border between the border panels.

**Expected behavior**
There should be no gaps.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/4835617/139428838-b48aec56-c6f9-4918-a9fc-b94f164b4155.png)

**Version Info**

NuGet package version: 
Windows App SDK 1.0 Preview 3

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

**Comment by StephenLPeters** [comment]
@codendone and @gegao18 FYI

**Comment by codendone** [comment]
The gradient issue is tracked by this separate issue #6194. Since the cause of the gap is unrelated to the gradient, I've restored the original title of this issue to keep these separate.
