### ISSUE TITLE
SemanticZoom combined with GridView cause the GroupHeader swaying during the scrolling

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [microsoft/microsoft-ui-xaml#6210]
### Describe the bug

SemanticZoom combined with GridView cause the GroupHeader swaying during the scrolling

### Steps to reproduce the bug

check the following link https://github.com/microsoft/Xaml-Controls-Gallery/issues/805#issue-1039264977

check out the following project (Do not use full screen mode. Try resize the window to different size. Some size will behavior normal )

https://github.com/OneFingerCodingWarrior/Swaying.git

### Screenshots

![1](https://user-images.githubusercontent.com/53161726/139778133-d5ec2187-f518-4deb-a75b-21b38a1848a4.gif)

If scroll with vertical bar, control behavior normal

![2](https://user-images.githubusercontent.com/53161726/139778185-2dd64398-cfeb-4c1d-b77d-62ae2b768f5a.gif)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Windows version: 21H1 19043.1288
Microsoft Visual Studio Community 2019
Version 16.11.5

**Comment by StephenLPeters** [comment]
@RBrid and @ranjeshj FYI, thoughts on whats causing?

**Comment by OneFingerCodingWarrior** [comment]
Hi Team, Any updates?
