### ISSUE TITLE
ListView items not rendered properly in UI when changing ItemsPanel property of ListView at run-time

### ISSUE THREAD

**Issue by SubashiniMahendran** [microsoft/microsoft-ui-xaml#6212]
### Describe the bug

ListView items not rendered properly in UI when changing ItemsPanel property of ListView at run-time.

Demo:
[ListView-issue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7458307/ListView-issue.zip)

### Steps to reproduce the bug

1. Run the sample.
2. Click Change ItemsPanel button to change the ItemsPanel of ListView.
3. Note ListView items are not rendered properly in UI.
4. Click Add Items button to add items at run-time.
5. Note newly added item at run-time alone rendered in UI.

Actual result:
ListView items not rendered properly in UI when changing ItemsPanel property of ListView at run-time.

### Expected behavior

ListView items should render properly in UI when changing ItemsPanel property of ListView at run-time.

### Screenshots

**Before changing ItemsPanel at run-time:**
![image](https://user-images.githubusercontent.com/92976485/139797103-20f63c74-6aca-44f6-992d-bea20e07394e.png)

**After changing ItemsPanel at run-time:**
![image](https://user-images.githubusercontent.com/92976485/139797162-b66c817f-6a10-4163-b8bf-e3599474fd13.png)

**After changing ItemsPanel at run-time and adding new items at run-time:**
![image](https://user-images.githubusercontent.com/92976485/139797250-eb5f329c-fc14-408a-a3c8-992c0da18189.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
@RBrid is this expected/known?

**Comment by SubashiniMahendran** [comment]
Hi Team, 

Any update on this issue?

**Comment by StephenLPeters** [comment]
@ranjeshj or @RBrid any ideas?
