### ISSUE TITLE
"All GUIDs must be unique." error in Windows App Certification Kit 

### ISSUE THREAD

**Issue by ilovepumpkin** [microsoft/microsoft-ui-xaml#6214]
### Describe the bug

In a simple default WinUi3/UWP project, the WACK reports error "All GUIDs must be unique.".

### Steps to reproduce the bug

I created a project using template "[Experimental] Blank App (WinUI 3 in UWP)". Then associate it with store, then create new package via Microsoft Store. At the last panel, I start the Windows App Certification Kit locally. All tests passed except "General metadata correctness"  - there are lots of errors like "All GUIDs must be unique." 

![image](https://user-images.githubusercontent.com/11310645/139805120-7dea398c-a383-420c-8933-550522c270fb.png)

### Expected behavior

All tests passed. 

### Screenshots

![image](https://user-images.githubusercontent.com/11310645/139804853-79714301-5847-40b0-a236-20e51cd4fa8c.png)

### NuGet package version

WindowsAppSDK 1.0.0-experimental1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@ilovepumpkin Winui3 does not fully support UWP, so this may be expected.  @MikeHillberg or @ryandemopoulos thoughts?

**Comment by krschau** [comment]
Closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615). If you are still seeing the behavior with a Win32 app using the latest WindowsAppSDK version, please open a new issue.
