### ISSUE TITLE
Inline Hyperlink does not work when IsTextSelectionEnabled="True"

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#6215]
### Describe the bug

When using a Hyperlink in a TextBlock, and IsTextSelectionEnabled="True", clicking the hyperlink does nothing.
This is a regression in **Windows App SDK 1.x.x**.  It works in Windows App SDK 0.8

### Steps to reproduce the bug

1. Use **Windows App SDK 1.x.x**
2. Use this XAML:
``` XML
<TextBlock IsTextSelectionEnabled="True" HorizontalAlignment="Left" VerticalAlignment="Top">
    <TextBlock.Inlines>
       <Hyperlink Click="OnHyperlinkClick">
            <Hyperlink.Inlines>
                <Run Text="Click Me!"/>
            </Hyperlink.Inlines>
         </Hyperlink>
    </TextBlock.Inlines>
</TextBlock>
```
3. Click the hyperlink (Click Me!)

The OnHyperlinkClick handler is never fired as long as text selection is enabled.

### Expected behavior

It should be possible to click on a hyperlink in a TextBlock, even when text selection is enabled.

### NuGet package version

WinUI 3 - Windows App SDK 1.x.x 

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by wbokkers** [comment]
@codendone, @StephenLPeters  or others, any change of this to be solved? 

I need to set IsTextSelectionEnabled to False, when it contains hyperlink inlines. But obviously users complain that they can't select any text now. This used to work correctly in SDK 0.8.

**Comment by joshkoon** [comment]
Also repros in WinUI 2.x. Testing locally in a test app shows that the regression was introduced with WinUI 2.6.0-prerelease.210623001; it doesn't repro with 2.6.0-prerelease.210430001 or older.

**Comment by wbokkers** [comment]
Is it possible to give this issue some attention? @gabbybilka @Scottj1s @StephenLPeters @codendone @marb2000 
Some background: in our app there's a chat capability that will show links automatically in a message containing urls. The user wants to be able to select the chat message, but also want to click on a link in the message. 
This bug makes this impossible. Making the textblock selectable, disables the hyperlink.

**Comment by wbokkers** [comment]
🎉🎈😃
This issue has been solved in Windows App SDK 1.2

**Comment by gabbybilka** [comment]
Closing as per @wbokkers message and tweet confirming it was resolved.

**Comment by wbokkers** [comment]
@gabbybilka This is again an issue on the latest WinUI bits.

**Comment by wbokkers** [comment]
@Scottj1s Can you again look into this issue? It once had been solved, but as soon as an hyperlink is added as a Run in a TextBlock, the text in the hyperlink cannot be selected.

**Comment by wbokkers** [comment]
@Scottj1s @gabbybilka Sorry, the hyperlink now works correctly, but the text of the hyperlink cannot be selected. So it is a somewhat different issue from the original.
