### ISSUE TITLE
TextBox and AutoSuggestBox doesn't accept AltGr input when hosted by Xaml island

### ISSUE THREAD

**Issue by stefansjfw** [microsoft/microsoft-ui-xaml#6217]
### Describe the bug

When using xaml islands to host XAML user control with TextBox and/or AutoSuggestBox included (I didn't test other input UI elements), these UI elements aren't accepting ALT GR special characters. E.g. Using German keyboard layout, AltGr (right Alt on the keyboard) + q gives `@` char.

Issue observed here:
https://github.com/microsoft/PowerToys/issues/14099

### Steps to reproduce the bug

1. Take VS project that uses Xaml islands to host some custom user control
2. Put TextBox and/or AutoSuggestBox into custom user control
3. Change keyboard layout to some layout that has AltGr special characters (e.g. German)
4. Observe that TextBox and AutoSuggestBox doesn't accept AltGr special characters as input 

### Expected behavior

TextBox and AutoSuggestBox accepts AltGr special characters

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

**Comment by StephenLPeters** [comment]
@marb2000 do you know how xaml islands could be affecting this scenario?

**Comment by stefansjfw** [comment]
Hi @StephenLPeters @marb2000,
 Any update about this?

**Comment by stefansjfw** [comment]
Also, we're experiencing another issue where users can't type anything in AutoSuggestBox, regardless of keyboard layout, described here https://github.com/microsoft/PowerToys/issues/14514

**Comment by viniciusjarina** [comment]
Hi @stefansjfw 
I tried to repro your issue creating a `TextBox` in a XAML Island, and couldn't repro.
![altgr](https://user-images.githubusercontent.com/926868/145244868-9d9e9019-208b-4b97-80ea-f155682e77ed.gif)

The chars are being sent to the `TextBox` normally.

Do you have an small sample that repros the issue?

**Comment by stefansjfw** [comment]
Ah, sorry, I though I already posted the example.. I was using xaml islands samples repo. Here's the branch:
https://github.com/stefansjfw/Xaml-Islands-Samples/tree/stefan/text_box_altgr_issue

You'll see that I only made minor changes to the master branch (using latest versions and a single TextBox), to simplify the example.

Steps to reproduce:
 - switch to German keyboard layout
 - start the example app
 - try to type AltGr +Q (which should produce @) in TextBox
 - observe that AltGr + Q works in e.g. Notepad, and not in TextBox

**Comment by viniciusjarina** [comment]
This seems an issue on [`XamlBridge.cpp`](https://github.com/stefansjfw/Xaml-Islands-Samples/blob/stefan/text_box_altgr_issue/Samples/Win32/SampleCppApp/XamlBridge.cpp#L125) and not on Island.

I am not sure why the author wants to call `IsDialogMessage` when the `Alt` is pressed.

I removed the Alt check and seems to be working fine (I also tested the tab navigation from/to island/native controls)
```diff
@@ -119,10 +119,7 @@ bool DesktopWindow::NavigateFocus(MSG* msg)
     else
     {
         const bool islandIsFocused = GetFocusedIsland() != nullptr;
-        byte keyboardState[256] = {};
-        WINRT_VERIFY(::GetKeyboardState(keyboardState));
-        const bool isMenuModifier = keyboardState[VK_MENU] & 0x80;
-        if (islandIsFocused && !isMenuModifier)
+        if (islandIsFocused)
         {
             return false;
         }
```
![altgr2](https://user-images.githubusercontent.com/926868/145311911-c7679a8e-45d7-4192-9c88-5ff843d1e180.gif)

**Comment by stefansjfw** [comment]
@viniciusjarina Thanks a lot! It works now!

Have you seen anything similar to another issue we're experiencing : https://github.com/microsoft/PowerToys/issues/14514 ? 
Check this comment in particular https://github.com/microsoft/PowerToys/issues/14514#issuecomment-984829204

**Comment by viniciusjarina** [comment]
Could be related. I didn't know PowerRename was using Island
