### ISSUE TITLE
Navigation pane no longer updating foreground in dark mode theme

### ISSUE THREAD

**Issue by capegreg** [microsoft/microsoft-ui-xaml#6219]
### Describe the bug

Items in the Navigation pane do not update foreground after updating Microsoft.UI.Xaml from 2.5.0 to 2.6.0 or higher. When changing the theme in a UWP to Dark the foreground contrasts with the Microsoft.UI.Xaml.Controls NavigationView background, results in the items appearing missing.

### Steps to reproduce the bug

1. Create a new Visual Studio 2019 project using Windows Template Studio (Universal Windows)
2. Choose a Navigation pane in the WTO wizard. (horizontal was selected for project)
3. Add Theme Selection
4. Make note Microsoft.UI.Xaml version should be at 2.5.0
5. Run project
6. Click Settings icon and choose Dark theme
7. Settings icon foreground changes to light color
8. Change Nuget Package Manager
9. Update Microsoft.UI.Xaml version to 2.6.0
10. Run project (Dark mode theme should still be applied from previous step)
11. Settings icon foreground is dark color and appears hidden in Navigation pane

### Expected behavior

Navigation pane items foreground changes to light color in Dark theme and dark color in light themes.

### Screenshots

**Windows default 2.6.0**

![dark3](https://user-images.githubusercontent.com/1051118/139922457-0ee1a8c1-a46f-42fa-8cf1-b65f24628698.PNG)

![dark](https://user-images.githubusercontent.com/1051118/139922461-fe6956a7-9179-4c5c-88f4-3d82b8e37f9a.PNG)

**Dark 2.6.0**

![dark2](https://user-images.githubusercontent.com/1051118/139922467-33a42cda-86a5-458f-8fab-89da5566dc98.PNG)

![dark4](https://user-images.githubusercontent.com/1051118/139922762-b65cee3f-47b3-410e-bd89-722f59310515.PNG)

**Dark 2.5.0**
![dark5](https://user-images.githubusercontent.com/1051118/139922767-08405959-d916-4d92-832c-ada9991170c1.PNG)

### NuGet package version

Microsoft.UI.Xaml 2.6.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@capegreg can you provide the markup generated by WTO that is reproducing this issue?

**Comment by capegreg** [comment]
How do you get WTO markup? Here are two a screenshots. One is the color properties for TopNavArea when using 2.5.0 **with dark theme**; the other is the same properties in 2.7.0

2.5.0

![image](https://user-images.githubusercontent.com/1051118/141520082-c8eeb83f-1ebc-4ecd-b138-e8d34da55225.png)

2.7.0

![image](https://user-images.githubusercontent.com/1051118/141520249-4dae5436-d690-41c9-864b-efb20dfa8365.png)

**Comment by capegreg** [comment]
Is this issue waiting on me for anything "1 of 2 tasks"?

**Comment by chingucoding** [comment]
@capegreg This is something GitHub renders because there are two checkboxes and only one of them is ticked.
