### ISSUE TITLE
Proposal: Toast feature like Android toast

### ISSUE THREAD

**Issue by hupo376787** [Microsoft/microsoft-ui-xaml#622]
# Proposal: Toast feature, just like Android toast.

## Summary

See the bottom toast, uwp has no toast like this currently.
![image](https://user-images.githubusercontent.com/14960168/56793182-f1c4a180-683d-11e9-9057-9b8c5edf3512.png)

**Comment by jesbis** [comment]
In addition to in-app notifications, the Windows Community Toolkit also has helpers for showing system-level toasts:  

https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast

**Comment by jevansaks** [comment]
Our 2.1 update also includes [TeachingTip](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip) which can do this as well.  See this section for something like what you want: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip#non-targeted-tips

![image](https://user-images.githubusercontent.com/20667023/56825508-2ae51d80-680e-11e9-96fc-b363e9022d81.png)

**Comment by hupo376787** [comment]
Sounds good

**Comment by hupo376787** [comment]
But teaching tip does not support a timer to auto close the tip

**Comment by jevansaks** [comment]
@hupo376787 thanks for the specifics on that, you're right that there is no timeout. Would you mind opening another issue to track that TeachingTip is missing a dismiss timeout? If not maybe @SavoySchuler can file it on your behalf?

**Comment by jevansaks** [comment]
On the other hand, system toasts auto-dismiss so maybe the recommendation should be to use a system toast if you want an ambient popup with timeout.

**Comment by mdtauk** [comment]
TeachingTip having a timeout was an idea discussed, but not implemented for Version 1.  Maybe @SavoySchuler will be able to add that in the future

**Comment by hupo376787** [comment]
OK, thanks guys for your great work. Looking forward to this feature.

**Comment by SavoySchuler** [comment]
Hi, @hupo376787, I was just discussing with @mdtauk that I would be keen to open a TeachingTip V2 proposal if there were real app scenarios to drive it. Do you have one?

**Comment by mdtauk** [comment]
@SavoySchuler  I think I remember discussing a timeout option with you, citing some old Windows Longhorn examples of a progress bar, on the message box, going down until the bubble/tip was dismissed.

However I think this particular proposal, may be better served with the more light-weight #913 Status Banner proposal which I think came from an internal Microsoft dev, so is more likely to be actionable.

**Comment by hupo376787** [comment]
I once made a app which style and behavior almost like android, see gif

![000](https://user-images.githubusercontent.com/14960168/60558531-25f79980-9d7c-11e9-90cc-616895f7fb13.gif)

**Comment by hupo376787** [comment]
Hi, guys. It seems `TeachingTip` still can't disappear automaticaly without any user interaction as android toast behavior.
The `IsLightDismissEnabled` property still need user to interact.
Do you have any plans?

**Comment by ranjeshj** [comment]
@hupo376787 There is a discussion on this in the TeachingTip v2 proposal here - https://github.com/microsoft/microsoft-ui-xaml/issues/638
