### ISSUE TITLE
Broken VS IntelliSense for WinUI 2.x styles & controls

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#6222]
### Describe the bug

Visual Studio's IntelliSense doesn't detect WinUI 2.x styles and thinks it doesn't exist. It also doesn't show them in the dropdown for selecting a style. It also doesn't recognize certain WinUI 2.x types and can't show them in the designer.

### Steps to reproduce the bug

1. Open a UWP app project with WinUI 2.x installed.
2. Apply a style only present in WinUI 2.x (eg: DisplayTextBlockStyle) to a XAML control and notice the IntelliSense saying it couldn't resolve it.

### Expected behavior

Visual Studio should be able to resolve WinUI 2.x styles and controls at design time for a better experience.

### Screenshots

<img width="337" alt="Screenshot 2021-11-03 at 16 20 41" src="https://user-images.githubusercontent.com/45227503/140047660-4631e7fa-6d1a-43b2-99fa-56e6c6bc38bb.png">

<img width="328" alt="Screenshot 2021-11-03 at 18 06 34" src="https://user-images.githubusercontent.com/45227503/140061224-b5067b79-34fe-4c1d-bd65-c952edc9362b.png">

<img width="1863" alt="Screenshot 2021-11-03 at 16 22 07" src="https://user-images.githubusercontent.com/45227503/140048035-8c071b41-b156-4250-b449-ce74985d17df.png">

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11

**Comment by StephenLPeters** [comment]
@jevansaks @evelynwu-msft and @MikeHillberg How can we fix this from WInui2?
