### ISSUE TITLE
Question: How to use GraphicsCapturePicker in WinUI 3?

### ISSUE THREAD

**Issue by lucent-sea** [microsoft/microsoft-ui-xaml#6230]
I'd like to use the `GraphicsCapturePicker` in a WinUI 3 Desktop app.   However, I get the following error when running this code:

```
    var isSupported = GraphicsCaptureSession.IsSupported(); // true
    var picker = new GraphicsCapturePicker();
    var item = await picker.PickSingleItemAsync();
```

```
System.Runtime.InteropServices.COMException: 'The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))'
```

For WPF, I was able to get around this using the examples here: 
https://github.com/Microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/ScreenCapture

But the same technique doesn't appear to be working with WinUI.  Specifically, marshalling the `DispatcherQueueController` here returns `null`: https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/master/dotnet/WPF/ScreenCapture/Composition.WindowsRuntimeHelpers/CoreMessagingHelper.cs

What do I need to do to get the `GraphicsCapturePicker` to work?

Thanks!  :)

**Comment by lucent-sea** [comment]
Nevermind.  I figured it out!  :)  Here's the interop calls that need to be made:

```
            var hwnd = WindowNative.GetWindowHandle(_mainWindow);
            var picker = new GraphicsCapturePicker();
            InitializeWithWindow.Initialize(picker, hwnd);
            var item = await picker.PickSingleItemAsync();
```

**Comment by farzadso** [comment]
@lucent-sea So what we're doing here is telling the picker that its owner is the current window? BTW, thanks for the solution.
