### ISSUE TITLE
Compact sizing - QueryIcon for AutoSuggestBox is cut off

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#6233]
### Describe the bug

The query icon for AutoSuggestBox is cut off when using compact size mode and doesn't have the same padding as the clear button.

### Steps to reproduce the bug

1. Create a AutoSuggestBox with a QueryIcon.
2. Apply compact sizing.

### Expected behavior

The icon shouldn't be cut off and the button should have the same padding as the clear button.

### Screenshots

![image](https://user-images.githubusercontent.com/45227503/140292661-f2e56dda-bba5-4741-a4a9-bb31aaeec9d7.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by chingucoding** [comment]
Just checked this in the MUXControlsTestApp and I think the bug is already fixed: 
![Screenshot of AutoSuggestBox with delete and query icon in compact design layout](https://user-images.githubusercontent.com/16122379/140569682-6958ca76-dd38-482d-ab22-a92a77508a0d.png)

**Comment by Jaiganeshkumaran** [comment]
> Just checked this in the MUXControlsTestApp and I think the bug is already fixed: ![Screenshot of AutoSuggestBox with delete and query icon in compact design layout](https://user-images.githubusercontent.com/16122379/140569682-6958ca76-dd38-482d-ab22-a92a77508a0d.png)

Is this in 2.7.1?

**Comment by chingucoding** [comment]
I think the PR that fixed this was merged after the last release of WinUI 2 so no, I don't think it's in there.
