### ISSUE TITLE
XamlIslands + TreeView + many nodes added = poor performance and high memory usage

### ISSUE THREAD

**Issue by stefansjfw** [microsoft/microsoft-ui-xaml#6234]
### Describe the bug

Using XamlIslands to host custom user control with a single TreeView results in really poor performance and high memory usage.

To present this I forked [Xaml-Islands-Sample repo](https://github.com/microsoft/Xaml-Islands-Samples) and created a test scenario with `TreeViewHostUserControl` present in the repo and adding many elements to it's TreeView element.
Test scenario can be found here:
https://github.com/stefansjfw/Xaml-Islands-Samples/tree/stefan/test_tree_view.
Test scenario only adds 800 items into existing `TreeViewHostUserControl`, without any additional logic and calculations in the background – so, no major changes to the repo code.
This results in following:
 - it takes ~8-10 seconds from starting the app to showing the items in the TreeView 
 - memory usage goes up to 600MB
Note: I tried both Debug and Release mode, results are similar.

If you try to increase number to 8000, the app will consume more than 2GB of memory, and eventually crash after 5,6 minutes of trying to load the tree view control.

P.S I tried the same thing with ListViews, the results are bit better, but poor performance and high memory usage are still present.

### Steps to reproduce the bug

1. Clone https://github.com/stefansjfw/Xaml-Islands-Samples/tree/stefan/test_tree_view branch
2. Build and run `NativeXamlIslands` solution
3. Observe the loading time and memory consumption
4. Open MainUserControl.cpp and change number of items added (line 14) from 800 to 8000
5. Observe the loading time and memory consumption once again

### Expected behavior

Application loads after some reasonable time and doesn't consume unreasonable amount of memory

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

**Comment by StephenLPeters** [comment]
@JesseCol and @marb2000 is this kind of performance deggragation expected in a xaml island? It sounds like we aren't virtualizing. @ranjeshj thoughts?

**Comment by JesseCol** [comment]
No, I wouldn't expect this to be any worse in islands.  Are we sure the same scenario in UWP is better?  I haven't worked with virtualization very much, maybe someone who has can look at the sample and make sure it's not somehow falling off the golden path.

**Comment by stefansjfw** [comment]
Turned out not to be xamlislands related, but virtualization. Putting TreeView in StackPanel was bad idea. Using Grid instead solves the problem.

**Comment by JesseCol** [comment]
Good to know -- thank you @stefansjfw for circling back and updating the thread!
