### ISSUE TITLE
ListView border bottom sometimes doesn't draw

### ISSUE THREAD

**Issue by DHancock** [microsoft/microsoft-ui-xaml#6235]
### Describe the bug

I've configured a ListView to have a uniform one pixel thick border. When the ListView contains more items than can be dsplayed and you resize it by growing its container, the bottom border section is occasionally not drawn. It is more likely to go wrong when the ListView is quite tall.

The screen capture shows it in dark mode but the problem isn't theme dependent.

### Steps to reproduce the bug

1) Build the attached solution.
2) Grow the window...

[BorderAndUICommandIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7476614/BorderAndUICommandIssue.zip)

### Expected behavior

The border is drawn correctly.

### Screenshots

![borderissue](https://user-images.githubusercontent.com/28826959/140381831-9b676aee-71df-4331-bfdf-4251a8a8d8e3.gif)

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Nuget Package: Microsoft.ProjectReunion 0.8.5

**Comment by StephenLPeters** [comment]
@DHancock does this issue occur with the WinAppSDK v1.0-preview3 version?

@codendone FYI

**Comment by DHancock** [comment]
@StephenLPeters - unfortunately it is still reproducible in WinAppSDK v1.0-preview3 (with the new ListView styles)

**Comment by DHancock** [comment]
I have subsequently found that this bug isn't reproducible when I set the display scaling to 100%. 
My laptops recommended scale setting is 125%, and at that scale it is reproducible.
(Settings->System->Display->Scale and layout)

**Comment by StephenLPeters** [comment]
@gegao18 and @codendone FYI
