### ISSUE TITLE
When the description of a StandardUICommand is displayed it ignores dark theme setting

### ISSUE THREAD

**Issue by DHancock** [microsoft/microsoft-ui-xaml#6236]
### Describe the bug

When the description of a StandardUICommand is displayed, it ignores dark theme setting. 

The screen capture shows the Copy command but it also occures for other command types.

### Steps to reproduce the bug

1) Build the attached solution.
2) Toggle theme until dark.
2) Select a list item.
3) Right click to show the content menu.

[BorderAndUICommandIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7476678/BorderAndUICommandIssue.zip)

### Expected behavior

Follows theme setting.

### Screenshots

![darkmodeissue](https://user-images.githubusercontent.com/28826959/140384408-ea9251bb-39ae-4a4d-97db-4ceb73488b5a.PNG)

### NuGet package version

WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Nuget Package: Microsoft.ProjectReunion 0.8.5

**Comment by StephenLPeters** [comment]
@llongley and @codendone looks like themeing isn't being applied to the tooltip. Could be the command bar flyout or the resource system.

**Comment by DHancock** [comment]
This is also reproducible in WindowsAppSDK 1.0.0-preview3
