### ISSUE TITLE
Navigationview causes Access violation reading location on app.current.exit()

### ISSUE THREAD

**Issue by MaoUyen** [microsoft/microsoft-ui-xaml#6238]
**Describe the bug**

not sure if its winui or xaml related but:
when you have opened a navigationview during any time in your application and then execute an application.current.exit()
it throws :   0xC0000005: access violation reading location 0x0000.... 

**Steps to reproduce the bug**

1. Create a new Winui3 project
2. add a navigationview to the stackpanel 
3. add to the myButton_Click function the following line: Application.Current.Exit();
4. see how it throws that exception after you click on the button while the application runs

**Expected behavior**

I expect the application to close

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.ProjectReunion version 8.5

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by StephenLPeters** [comment]
@StephenLPeters  reminder to myself to check if this is a reliable repro of the issue fixed by https://github.com/microsoft/microsoft-ui-xaml/pull/6240
