### ISSUE TITLE
AppWindowPresenterKind.FullScreen generating empty space on first run

### ISSUE THREAD

**Issue by ispysoftware** [microsoft/microsoft-ui-xaml#6245]
### Describe the bug

The current WinUI sample for Presenter types:
https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing/cs-winui/SampleApp

Contains a method for setting WinUI apps full screen. This works but the first time AppWindowPresenterKind.FullScreen is applied it results in empty space along the right hand side and bottom of the display. After exiting full screen and then re-applying it the empty space is used properly.

### Steps to reproduce the bug

Run the sample app, click to enter full screen mode, observe the empty space. Exit full screen and then re-enter it and observe the space used properly.

### Expected behavior

Should use all available space on first run.

### Screenshots

https://imgur.com/a/CK96wSi

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [x] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by DominicMaas** [comment]
Related to https://github.com/microsoft/WindowsAppSDK/issues/1853

**Comment by aepot** [comment]
This is a dup of [#1853](https://github.com/microsoft/WindowsAppSDK/issues/1853).

**Comment by ispysoftware** [comment]
> This is a dup of [#1853](https://github.com/microsoft/WindowsAppSDK/issues/1853).

well that is a dup of this :) I logged it 3 weeks earlier

**Comment by aepot** [comment]
Well, that dup was bound to 1.1 milestone recently. I suggest to close the current one as it contains the same repro.
The only diffrence is relation to 0.8 vs 1.0 SDK. Also if backport to 0.8 is needed then better to suggest it there.
