### ISSUE TITLE
Maximise window options not displayed when using ExtendsContentIntoTitleBar

### ISSUE THREAD

**Issue by ispysoftware** [microsoft/microsoft-ui-xaml#6246]
### Describe the bug

The maximise control doesn't display the standard Windows 11 maximise target options when hovering over the button when ExtendsContentIntoTitleBar is set to true

### Steps to reproduce the bug

Set ExtendsContentIntoTitleBar to true, hover over the maximise button, no options are presented, just the tooltip text "Maximize"

### Expected behavior

Should provide the standard Windows 11 maximize target selection tool

### Screenshots

https://imgur.com/a/FuLUncT

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [x] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@pratikone FYI, do you know whats going on here?

**Comment by gabbybilka** [comment]
Fixed in Windows App SDK 1.0.1, check out the [release notes](https://github.com/microsoft/WindowsAppSDK/discussions/2291) for more info.
