### ISSUE TITLE
WinUI webview2 download file manager displays under application window

### ISSUE THREAD

**Issue by ispysoftware** [microsoft/microsoft-ui-xaml#6247]
### Describe the bug

Downloading a file via the webview2 winui control pops up a download manager window underneath the application window so it's not visible.

### Steps to reproduce the bug

add a webview2 control to a winui project
navigate it to:
https://file-examples.com/index.php/sample-documents-download/sample-doc-download/
click to download a file
the file download manager pops up underneath the active window and is not visible. You have to move the application window to access the download manager.

### Expected behavior

download control should pop up above the current window.

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [x] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@codendone and @krschau FYI
