### ISSUE TITLE
UWP CommandBar broken when targeting Windows 11 22000

### ISSUE THREAD

**Issue by zhuxinghan** [microsoft/microsoft-ui-xaml#6249]
### Describe the bug

When UWP project target Windows 11 22000, CommandBar's behavior becomes strange. Sample project: 
[CommandBar22000.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7490349/CommandBar22000.zip)

### Expected behavior

Targeting 19041:
![19041](https://user-images.githubusercontent.com/15711862/140608049-badba8e2-1048-4e4f-927e-24592c9efd59.gif)

### Screenshots

Targeting 22000:
![22000](https://user-images.githubusercontent.com/15711862/140608060-99f1d22d-6185-4771-a1c9-b59cf3589fde.gif)

### Windows app type

- [X] UWP
- [ ] Win32

### Additional context

I didn't install WinUI package in the sample project, but the problem remains even if WinUI is installed. Installation of WinUI only changes CommandBar's visual style.

**Comment by zhuxb711** [comment]
Same here

**Comment by StephenLPeters** [comment]
@chigy and @ranjeshj  FYI

**Comment by zhuxb711** [comment]
Still exists in Windows SDK 22621

**Comment by Medality** [comment]
Any workarounds for this? I've found out BottomAppBar is not affected, but it cannot be used in all situations.
