### ISSUE TITLE
[uwp] Frame.Navigate( typeof(non_xaml_class_derived_from_Page)) crashes w/ Native Toolchain

### ISSUE THREAD

**Issue by baskren** [microsoft/microsoft-ui-xaml#6250]
### Describe the bug

When given a Non-XAML (pure code) class derived from Page, Frame.Navigate crashes when compiled using Native Toolchain.

## USING SAMPLE PROJECT 

1. Clone the following repo: https://github.com/baskren/NativeToolchain_NonXamlPage_crash.git
2. Run in **Debug** WITHOUT **Native Toolchain**
3. Click **NOT A XAML PAGE** button to navigate from **XAML PAGE** to **NOT A XAML PAGE**, successfully
4. Run in **Debug** WITH **Native Toolchain** or run in **Release**
5. Click **NOT A XAML PAGE** button to crash app.

## FROM SCRATCH
1. Create a new UWP App
2. Create a new class file, named **NoXaml.cs** and derive the class **NoXaml** from Windows.UI.Xaml.Controls.Page
3. Add `[Windows.UI.Xaml.Data.Bindable]` attribute to the **NoXaml** class
4. In App.xaml.cs, replace `rootFrame.Navigate(typeof(MainPage), e.Arguments);` with `rootFrame.Navigate(typeof(NoXaml), e.Arguments);`
5. In the project's options, enable the **Native Toolchain**
6. Build, run, watch crash

### Expected behavior

Frame.Navigate works with Non-XAML Pages.

### Screenshots

![image](https://user-images.githubusercontent.com/2528888/140615319-8a00c395-f7cb-456e-bd66-b8e13944e33f.png)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Note that recommendation from #1949 was applied to test case

**Comment by baskren** [comment]
so @asklar closed a duplicate of this bug immediately (in a different project) but no one has responded in over a week.  Does this mean that I did not post either bug in the right place?  Does this mean that UWP is no longer being supported?

**Comment by StephenLPeters** [comment]
@RealTommyKlein do you know what not xaml page is missing here?

**Comment by RealTommyKlein** [comment]
This is because `NotXamlPage` is missing an access modifier, so it's considered `internal` instead of `public` and inaccessible to Xaml in Release/.NET Native toolchain builds.  Changing the declaration to:
```
   [Windows.UI.Xaml.Data.Bindable]
   public class NotXamlPage : Page
   {
       ...
   }
```
Will fix it.  To make native toolchain vs. non-native toolchain and Debug vs. Release builds have the same behavior (so they would've both crashed instead of the Debug non-native toolchain scenario working), you can add this MSBuild property to your project file although the Designer/Hot Reload experience will be less robust:
```
  <PropertyGroup>
    <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
  </PropertyGroup>
```
