### ISSUE TITLE
Question: Which part of WinUI has been open sourced

### ISSUE THREAD

**Issue by IrakliLomidze** [microsoft/microsoft-ui-xaml#6251]
Dear MSFT

Question: Which part of WinUI has been open-sourced.
Microsoft in last year has promised that WinUI will be decoupled from Windows and will ship as the library and it will be open source. 
My question is the implementation of WinUI will be open source or only wrapper on existing API?

**Comment by saint4eva** [comment]
None.

**Comment by Marv51** [comment]
WinUI 2 is completely open source. WinUI 3 is not open source (yet?). 

However, the controls in WinUI 3 are based on the WinUI 2 controle, changes to controls are generally introduced in WinUI 2 first and then at some later point ported to WinUI 3. Some small parts of WinUI 3 are also open-sourced in the [WindowsAppSKD](https://github.com/microsoft/WindowsAppSDK) repo, like the VS-extensions.

**Comment by saint4eva** [comment]
WinUI is not open source yet.

**Comment by binsys** [comment]
I have the same problem. 
Obviously MSFT has not open sourced any winui core code, such as dxaml CValue CCoreServices UIElement and so on.
According to callstack with pdb symbol, winui (uwp ui) inherits the legacy code of Silverlight.

**Comment by StephenLPeters** [comment]
@Marv51 's description is correct
