### ISSUE TITLE
[WinUI 3][ItemsRepeater] ItemsRepeater without template fails to render at all

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#6252]
### Describe the bug

When using an ItemsRepeater without specifying the ItemTemplate, the UI doesn't render and CPU usage is maxing out a single thread.

### Steps to reproduce the bug

1. Create WinUI 3 app
2. Add ItemsRepeater to MainPage.xaml
3. Add Layout (I was using UniformGridLayout)
4. Add ItemSource
5. Run app

### Expected behavior

The WinUI 2 version tried to apply some form of default template, I would assume the WinUI 3 version to do the same.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

NuGet package: Microsoft.WindowsSDK 1.0.0-preview3
Windows version: Insider Build 19044

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by chingucoding** [comment]
Closing as this is fixed now.
