### ISSUE TITLE
WinUI Design Toolkit Bug: Figma file - typo in color code

### ISSUE THREAD

**Issue by MajorBoo** [microsoft/microsoft-ui-xaml#6254]
## WinUI Toolkit Bug Report

---
**Name of component or part of Toolkit:**
Pages > Guidance & Charts > Color / Dark Theme > System / Solid Attention Background

**Describe the bug:**
SystemFillColorSolidAttentionBackground**l**Brush
must be
SystemFillColorSolidAttentionBackgroundBrush

**Version Info:**
2.7

**Additional context:**
Nope

**Comment by alejo4000** [comment]
Thanks for catching that! It will be fixed in the next update.
