### ISSUE TITLE
Unable to interact with initially hidden WebView2 on UWP

### ISSUE THREAD

**Issue by zhuxinghan** [microsoft/microsoft-ui-xaml#6256]
### Describe the bug

Suppose there's a WebView2 written in Xaml. It is hidden at first, then it is changed to visible and navigated to an uri after user's action. After the WebView2 is shown, it can't be interacted with mouse, but if you use Tab to move focus within it, you can use keyboard, such as up or down arrow key, to interact with it. It seems like something transparent is overlapping on it.

There is no problem if WebView2 isn't initially hidden.

Only UWP project has the problem. The same code on WinUI 3 works OK.

Sample projects:

UWP (has problem):
[HiddenWebView2UWP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7496980/HiddenWebView2UWP.zip)

WinUI 3 (works fine):
[HiddenWebView2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7496982/HiddenWebView2.zip)

### NuGet package version

2.8 preview

### Windows app type

- [X] UWP
- [ ] Win32

**Comment by krschau** [comment]
Hi @zhuxinghan, can you check if you still see this issue using Edge version 97.0.1072.61 or later? A fix went in recently that I think may address this issue. Thanks!

**Comment by zhuxinghan** [comment]
@krschau , my WebView2 is 97.0.1072.69 now, the problem still exists.

**Comment by andrewdewaal** [comment]
This is a problem for us as well using 2.8.0-prerelease.220118001.

**Comment by pwillies** [comment]
Just registering that we are also interested in this one being fixed...

**Comment by fsuk** [comment]
I was able to fix this issue in UWP by placing a Grid control around the WebView2 control
