### ISSUE TITLE
ItemsRepeater's UniformGridLayout properties MinColumnSpacing and MinRowSpacing are flipped

### ISSUE THREAD

**Issue by harvinders** [Microsoft/microsoft-ui-xaml#626]
**Describe the bug**
The effects of `MinColumnSpacing` and `MinRowSpacing` seems to be flipped. `MinColumnSpacing` is effecting the row spacing and `MinRowSpacing` the column spacing

**Steps to reproduce the bug**
```
<controls:ItemsRepeater>
    <controls:ItemsRepeater.ItemTemplate>
        <DataTemplate x:DataType="viewModels:ContentViewModel">
            <local:ContentView ViewModel="{x:Bind}" />
        </DataTemplate>
    </controls:ItemsRepeater.ItemTemplate>
    <controls:ItemsRepeater.Layout>
        <controls:UniformGridLayout Orientation="Horizontal" MinColumnSpacing="20" MinRowSpacing="10"/>
    </controls:ItemsRepeater.Layout>
</controls:ItemsRepeater>

```

**Version Info**
NuGet package version: Microsoft.UI.Xaml 2.1.190405004.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |  Yes    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
@ranjeshj known issue? can you take a look?

**Comment by micahl** [comment]
@ranjeshj I just tried this as well and see it repro.  Looks like we're not accounting for the orientation when applying the column/row spacing.  Fixing this will be a "breaking" change, but one we should make as the current behavior isn't expected.  :)
