### ISSUE TITLE
ThemeResource brushes transparent in WinUI3 WindowsAppSdk 1.0 Preview 3

### ISSUE THREAD

**Issue by dtynewydd** [microsoft/microsoft-ui-xaml#6260]
### Describe the bug

When using a theme resource, an amount of transparency seems to be being added, even if the brush referenced does not have transparency

### Steps to reproduce the bug

Create a winui 3 application using WindowsAppSdk preview 3.

Have an ellipse geometry whose stroke is bound to a theme resource, for example:

```xaml
                    <Color x:Key="ForegroundColor">#FF000000</Color>
                    <SolidColorBrush x:Key="ForegroundBrush" Color="{StaticResource ForegroundColor}"/>
```

### Expected behavior

Ellipse should have the same appearance as if the stroke was set to "Black".

### Screenshots

With "Black" set as stroke:
![image](https://user-images.githubusercontent.com/29239190/140902380-9f1eec33-4b51-47f4-9f17-a5aeacc2fcf2.png)

With "ForegroundBrush":
![image](https://user-images.githubusercontent.com/29239190/140902463-c7bbf993-1669-4d90-a26a-9f9195a4915d.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

**Comment by dtynewydd** [comment]
@StephenLPeters has there been any progress on this?

**Comment by JJBrychell** [comment]
We have been unable to repro this issue using the information specified. The repro steps refer to the stroke property, but it appears that it might be the fill property that is of issue. We attempted to repro with both stoke and fill, and in each case the ellipse drawn with the resource brush, resource color and explicit color appear to be the same.

From the images provided it does appear that is some kind of an artifact in the ellipse, but it is hard to tell whether that is a function of the clipboard copy, the original rendering or the fact that the "ForegroundBrush" image appears to be zoommed in some why. we are therefore going to close this issue. If you have a more complete repro demonstrating this issue, feel free to reopen.
