### ISSUE TITLE
DropDownButton's chevron's click animation has a large delay

### ISSUE THREAD

**Issue by zhuxinghan** [microsoft/microsoft-ui-xaml#6262]
DropDownButton, SplitButton, ToggleSplitButton all have chevrons on their right side. When these buttons are clicked, the chevrons play an animation that moves down and up, but there is a large delay between click and animation start.

The XAML Controls Gallery app can prove this problem:
![1](https://user-images.githubusercontent.com/15711862/140920063-395b84a9-eba3-4ccc-a6c9-5d2151d49f98.gif)

Note that the chevron's animation starts nearly after the flyout menu fully expanded.

**Comment by StephenLPeters** [comment]
Addressed by https://github.com/microsoft/microsoft-ui-xaml/pull/6706
