### ISSUE TITLE
DropCompleted called before DragStarted deferral was completed

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#6264]
### Describe the bug

When I start a drag drop operation from code using StartDragAsync (called from a PointerPressed event), and the pointer is released quickly after that, the DragStarted event is started, but the DropCompleted is started without waiting for the DragStarted to complete. 

### Steps to reproduce the bug

1. Define a DragStarted event handler with async code and a deferral that completes in a finally block.
2. Define a DropCompleted event handler.
2. Call StartDragAsync(..) in a PointerPressed event handler.
2. Quickly release the pointer.
3. The DropCompleted will run before the DragStarted event finishes.

### Expected behavior

Never call a DropCompleted before a DragStarted event finishes. Wait for the deferral to complete.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 Preview 3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by wbokkers** [comment]
Can someone take a look at this issue?

**Comment by StephenLPeters** [comment]
@JJBrychell FYI
