### ISSUE TITLE
WinUI Design Toolkit Bug: Missing Slider disabled state

### ISSUE THREAD

**Issue by Tropix126** [microsoft/microsoft-ui-xaml#6270]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Slider

**Describe the bug:**
The disabled state for Slider appears to be missing in dark mode.

**Version Info:**
Release 2.7

**Additional context:**
![image](https://user-images.githubusercontent.com/42101043/141028404-417fe5ad-277f-4a59-9928-dd6283f10228.png)

**Comment by alejo4000** [comment]
Thanks for letting us know! The fix will show up in the next iteration.
