### ISSUE TITLE
SizeChanged called twice

### ISSUE THREAD

**Issue by miquik** [microsoft/microsoft-ui-xaml#6272]
Hi everybody,
I create a class derived from ContentControl and I add my content. When I "subscribe" to SizeChanged event, this event is called twice. 
Is this the correct behaviour? Is it possible to prevent this? Or any workaround?

Thank you

**Comment by MikeHillberg** [comment]
There are multiple ways to cause layout get updated, and the purpose of SizeChanged is to only be raised once per layout. But if you're seeing it get called multiple times, likely something is dirtying layout during a layout pass. Layout runs in a loop until it stabilizes, and each iteration through the loop raises the event.

If you want to avoid the multiple calls, you could post to the thread using [DependencyObject.Dispatcher](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.DependencyObject.Dispatcher), with logic to only post once. That callback won't get invoked until it's out of the layout loop. (But if you change something in the handler that affects layout, it will trigger SizeChanged again.)
