### ISSUE TITLE
Question: How do you customize TabViewItem.IconSource through data binding?

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#6273]
Consider this scenario: I want the icon to be different type, depending on the state of view model.
For example, display a `SymbolIconSource` when nothing loaded, and switch to `BitmapIconSource` when it has an avatar.

Using a value converter to create icon source isn't realistic, since there may be data binding required.

It's naturally to consider `VisualStateManager` and `StateTrigger`, however I can't make it work with `TabViewItem` in any way. Sometimes the triggers doesn't load, sometimes the setters doesn't work.

I'm going to use the final solution that use `DataTemplateSelector` to create completely different template for `TabViewItem`. I wonder if there's better solution.

**Comment by MikeHillberg** [comment]
Can you bind the TabViewItem.IconSource to a property that provides the appropriate IconSource instance?

There are two icon types in WinUI: [IconElement](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.IconElement) and  [IconSource](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.IconSource). The duplication is unfortunate, but `IconSource` was actually created to be a binding friendlier version of `IconElement`.

**Comment by huoyaoyuan** [comment]
My application prohibits view model to use UI types, for cross-targeting support. I can write a `ValueConverter`, or a custom IconSource that creates appropriate `IconElement`.
