### ISSUE TITLE
Question: [How to navigate to a page from a window in a blank app for desktop WinUI C++?]

### ISSUE THREAD

**Issue by GraeChan** [microsoft/microsoft-ui-xaml#6277]
Hello, how would one navigate to a page from a window in a blank app for desktop WinUI C++? I have setup the blank C++ WinUI app for desktop. The Windowing Sample app looks great but I'm not sure how to apply this to my own project. This example is close to what I need [https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/simple-winui-example](url) but it assume the blank app starts with a Page rather than a Window. I feel like I'm missing a step when following the example. Anyone got any advice?

**Comment by Jaiganeshkumaran** [comment]
That sample is for WinUI 2.x (similar code for WinUI 3 UWP if it ever comes out?) and not WinUI 3 desktop. In WinUI 3 desktop, you could have a Frame inside the window and do navigation that way.
