### ISSUE TITLE
ERROR: Native images generated against multiple versions of assembly Microsoft.UI.Xaml.

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#6280]
### Describe the bug

output window: ERROR: Native images generated against multiple versions of assembly Microsoft.UI.Xaml. Windows.UI.Xaml.dll!00007FF804C97ECB: (caller: 00007FF804CA5D52) ReturnHr(1) tid(2af8) 80070057 The parameter is incorrect.

### Steps to reproduce the bug

UWP app using WinUI 2.7.

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by HppZ** [comment]
https://docs.microsoft.com/en-us/answers/questions/388196/windows-store-app-certification-failed-without-any.html

**Comment by MarkIvanDev** [comment]
I am also having this problem when using the packaging project with UWP and Win32 components. If I am developing a pure UWP this does not happen. And even when I downgrade Microsoft.UI.Xaml to previous versions (2.6.3 until 2.5.0), I still get this error now.

**Comment by StephenLPeters** [comment]
@llongley FYI

**Comment by kathigeiger42** [comment]
Any news on this? I'm also having this problem.
