### ISSUE TITLE
Proposal: Add setter for custom border brush on NavigationViewItem

### ISSUE THREAD

**Issue by yaira2** [microsoft/microsoft-ui-xaml#6283]
# Proposal: Add setter for custom border brush on NavigationViewItem

## Summary

This proposal would add setters for changing the border brush on NavigationViewItem.

## Rationale

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to change the border brush on NavigationViewItem | Must |

## Important Notes
```
<SolidColorBrush x:Key="NavigationViewItemBorderBrushPressed" Color="{ThemeResource ControlStrokeColorDefault}"/>
```

**Comment by chingucoding** [comment]
The v1 styles of the NVI presenter included the visual state setters, the v2 styles lack those visual state setters making customizing the border not possible without retemplating. The `NavigationViewItemBorder[StateName]` brushes have no effect on the v2 styles from what I can tell.

**Comment by StephenLPeters** [comment]
Seems like a bug rather than a feature request.

**Comment by StephenLPeters** [comment]
@karenbtlai FYI
