### ISSUE TITLE
WinUI Design Toolkit Bug: Close button in title bar not aligned correctly

### ISSUE THREAD

**Issue by TizuHD** [microsoft/microsoft-ui-xaml#6284]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Title Bar

**Describe the bug:**
The close button in the Title Bar component is not aligned correctly, it is one pixel off. The button label (the icon) is placed one pixel below where it should be.

**Version Info:**
Windows UI 2.7 (for Figma)

**Additional context:**
Doesn't seem to be intentional (I mean, why would it intentionally be placed one pixel off), but if it is correct me please.

**Comment by alejo4000** [comment]
Hrmm, I can think of a couple reasons why it might've been placed that way, whether intentional or not. Either way, I've fixed it so it's aligned with the other caption controls (min/max) in the title bar. This will show up in the next iteration. Thanks for pointing this out!
