### ISSUE TITLE
WinRT Theme loading error not specific enough

### ISSUE THREAD

**Issue by ebosvitas** [microsoft/microsoft-ui-xaml#6286]
### Describe the bug

When loading a custom theme. If you specify only a "Light" theme and nothing esle the applicaiton wont start if your windowds is set to "Dark". Not in debug/release from VS or when packaged. 

The probelm is that the error is generic and tell you it can't find the key it's looking for. Instead of it telling you there is no such ResourceDictionary with the key your are looking for. 

### Steps to reproduce the bug

1. Make a new project.
2. Load in a custom theme with only  <ResourceDictionary x:Key="Light">
3. Run applicaiton. Works fine.
4. Switch windows theme to "Dark"
5. Run applicaiton. Won't start.
6. Exception thrown at 0x00007FFDD6734F99 (KernelBase.dll) in Company.DesktopClient.exe: WinRT originate error - 0x80004005 : 'Cannot find a Resource with the Name/Key GradientBackground'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFDD884C363: (caller: 00007FFDD8856049) ReturnHr(1) tid(2b78) 8007007E The specified module could not be found.
Exception thrown at 0x00007FFDD6734F99 (KernelBase.dll) in Company.DesktopClient.exe: WinRT originate error - 0x802B000A : 'Cannot find a Resource with the Name/Key GradientBackground [Line: 0 Position: 0]'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFDD884C363: (caller: 00007FFDD8856049) ReturnHr(2) tid(2b78) 8007007E The specified module could not be found.
Exception thrown: 'Microsoft.UI.Xaml.Markup.XamlParseException' in WinRT.Runtime.dll

### Expected behavior

I expected it to tell me that either no theme was found. Or that it would default to the only theme availbe. 

### NuGet package version

0.8.4

### Packaging type

Unpackaged

### Windows version

October 2020 Update (19042)

### IDE

Visual Studio 2019

**Comment by StephenLPeters** [comment]
I think if you named the resource dictionary "Default" it would work.
