### ISSUE TITLE
Question:  xaml islands ETA

### ISSUE THREAD

**Issue by adalfa** [microsoft/microsoft-ui-xaml#6293]
https://github.com/microsoft/ProjectReunion -->
Hello do you have any estimate on XAML Islands for the next years?
we have some customers that are eager to try 

thanks

**Comment by StephenLPeters** [comment]
@ryandemopoulos can you weigh in?

**Comment by StephenLPeters** [comment]
@marb2000 fyi

**Comment by rmarinho** [comment]
Can we try wpf on net6 with winUI via yaml islands?

**Comment by boppbo** [comment]
Leave open

**Comment by rmarinho** [comment]
Oh nice!

**Comment by rmarinho** [comment]
well is not on preview 1.4 :(

**Comment by castorix** [comment]
It is in 1.4 (I tested in WinForms/C# on Windows 10 22H2 and it works correctly)

**Comment by rmarinho** [comment]
Nice, yeah seems so from 1.4 release notes but in a for I wasn't expecting. 
do you have an example @castorix  ? Seems it's low level API available right?
Thanks

**Comment by castorix** [comment]
I mainly just tested [DesktopWindowXamlSource ](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.hosting.desktopwindowxamlsource?view=windows-app-sdk-1.4) with _Content_ and _Initialize_ to associate the XAML window with the Form handle (in this [thread](https://github.com/microsoft/microsoft-ui-xaml/discussions/8808))
(also Microsoft.UI.Content.* like _Microsoft.UI.Content.ContentExternalOutputLink_ but for the reverse (Win32 control drawn in WinUI 3))
But the doc needs to be improved for more complex samples

**Comment by duncanmacmichael** [comment]
Closing this question as XAML Islands are out of experimental in 1.4 and are available for C++ apps, per the release notes. 

https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel#xaml-islands-no-longer-experimental
