### ISSUE TITLE
Question: [How to Multiple ExpressionAnimation on same control?]

### ISSUE THREAD

**Issue by EugenM88** [microsoft/microsoft-ui-xaml#6295]
Greetings guys, im starting to get into some animations for some specific buttons, basically what im doing right now im struggling to find the proper way to insert multiple expression animations for the same control. 

If i only call button1.StartAnimation("some expression animation reference") once, works as intended, however as soon as im trying to start a second animation button1.StartAnimation("a second expression animation reference") the program crashes imediately with error System.ArgumentException: 'Value does not fall within the expected range.'

What im trying to do is to use multiple expression animations for the same control to update different properties at the same time.

My question is simple, how can i execute multiple expression animations on the same control at the same time, OR how can i have an expression animation run multiple expressions and updating multiple target properties

Here is the code that im trying to execute:

            ExpressionAnimation anim1 = _compositor.CreateExpressionAnimation();
            anim1.Expression = "-((self.Scale.X - 1) * (self.ActualSize.X * 0.01) * 50)";
            anim1.Target = "Translation.X";

            ExpressionAnimation anim2 = _compositor.CreateExpressionAnimation();
            anim2.Expression = "-((self.Scale.Y - 1) * (self.ActualSize.Y * 0.01) * 50)";
            anim2.Target = "Translation.Y";

            anim1.SetExpressionReferenceParameter("self", button1);
            anim2.SetExpressionReferenceParameter("self", button1);

            
            button1.StartAnimation(anim1); // works fine
           
            button1.StartAnimation(anim2); // crashes with System.ArgumentException: 'Value does not fall within the expected range.'`

**Comment by EugenM88** [comment]
Hello, I've also tried using CompositionAnimationGroup and adding both expression animations to the group, same issue, as soon as i try to start a group with 2 expression animations program crashes with same error as before, please accept my apologies if im missing something obvious, im really really new to this amazing WinUI3 im probably missing something obvious, any help is deeply appreciated!

Code below to reproduce error with CompositionAnimationGroup
`            ExpressionAnimation anim1 = _compositor.CreateExpressionAnimation();
            anim1.Expression = "-((self.Scale.X - 1) * (self.ActualSize.X * 0.01) * 50)";
            anim1.Target = "Translation.X";



            ExpressionAnimation anim2 = _compositor.CreateExpressionAnimation();
            anim2.Expression = "-((self.Scale.Y - 1) * (self.ActualSize.Y * 0.01) * 50)";
            anim2.Target = "Translation.Y";

            

            anim1.SetExpressionReferenceParameter("self", button1);
            anim2.SetExpressionReferenceParameter("self", button1);
            
            
            //button1.StartAnimation(anim1);
            //button1.StartAnimation(anim2);


            CompositionAnimationGroup animationGroup = _compositor.CreateAnimationGroup();
            animationGroup.Add(anim1);
            animationGroup.Add(anim2);
            button1.StartAnimation(animationGroup);`

**Comment by StephenLPeters** [comment]
Hey @EugenM88 sorry for the delay.  I think that the issue you are seeing is because Translation.X and Translation.Y are are subchannels of the same property.  For this example I would recomend combining these animatoins into a single animation which has the tuple of singles type and targeting the Translation property itself instead of the subchannels.
