### ISSUE TITLE
Where are those default control styles (win2.x)?

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#6300]
such as `NavigationViewItemPresenter`

**Comment by HppZ** [comment]
where is `MUX_NavigationViewItemPresenterStyleWhenOnTopPane` ?

**Comment by HppZ** [comment]
Is winui all code open sourced?

**Comment by HppZ** [comment]
I need it.
ms-appx://Microsoft.UI.Xaml.2.7/Microsoft.UI.Xaml/Themes/19h1_generic.xaml

**Comment by Jaiganeshkumaran** [comment]
You should be able to find it inside the packages folder of your project.

**Comment by HppZ** [comment]
no, I searched `19h1_generic.xaml` using everything. it is not on my disk.

**Comment by HppZ** [comment]
> You should be able to find it inside the packages folder of your project.

I found no `packages` folder in my project.

**Comment by Jaiganeshkumaran** [comment]
> > You should be able to find it inside the packages folder of your project.
> 
> I found no `packages` folder in my project.

Check under the root folder where the solution is, not the project folder.

**Comment by HppZ** [comment]
no winui related stuff.
![image](https://user-images.githubusercontent.com/12285582/141740923-acc6c8e4-bf6b-4b12-b22b-0f8a7f8ca084.png)

**Comment by chingucoding** [comment]
@HppZ If you don't find the WinUI 2 package there, you might want to try `%USERPROFILE%/.nuget/packages`, it might be in there (with bunch of other packages). To answer the original question, all the styles that ship with WinUI 2 are open source and are available on this repository.

**Comment by HppZ** [comment]
> @HppZ If you don't find the WinUI 2 package there, you might want to try `%USERPROFILE%/.nuget/packages`, it might be in there (with bunch of other packages). To answer the original question, all the styles that ship with WinUI 2 are open source and are available on this repository.

found `.nuget\packages\microsoft.ui.xaml\2.7.0\lib\uap10.0\Microsoft.UI.Xaml\Themes\Generic.xaml`, but some styles does not exist:
![image](https://user-images.githubusercontent.com/12285582/141906666-febf9daa-2f07-4957-9a3f-c06282a9df10.png)

**Comment by HppZ** [comment]
and where is `Slider`'s source code?

**Comment by Jaiganeshkumaran** [comment]
> and where is `Slider`'s source code?

Slider is part of the system and not WinUI 2.x

**Comment by HppZ** [comment]
> > @HppZ If you don't find the WinUI 2 package there, you might want to try `%USERPROFILE%/.nuget/packages`, it might be in there (with bunch of other packages). To answer the original question, all the styles that ship with WinUI 2 are open source and are available on this repository.
> 
> found `.nuget\packages\microsoft.ui.xaml\2.7.0\lib\uap10.0\Microsoft.UI.Xaml\Themes\Generic.xaml`, but some styles does not exist: ![image](https://user-images.githubusercontent.com/12285582/141906666-febf9daa-2f07-4957-9a3f-c06282a9df10.png)

@Jaiganeshkumaran @chingucoding where are styles start with MUX?

**Comment by chingucoding** [comment]
Some styles are not in the generic.xaml file but rather imbedded into themeresources that are part of the appx package iirc. You can search for the style in this GitHub repository though: https://github.com/microsoft/microsoft-ui-xaml/search?q=MUX_NavigationViewItemPresenterStyleWhenOnTopPane

**Comment by HppZ** [comment]
> Some styles are not in the generic.xaml file but rather imbedded into themeresources that are part of the appx package iirc. You can search for the style in this GitHub repository though: https://github.com/microsoft/microsoft-ui-xaml/search?q=MUX_NavigationViewItemPresenterStyleWhenOnTopPane

only found MUX styles for RS1. I need the latest.
![image](https://user-images.githubusercontent.com/12285582/142364294-56e9419e-4dfc-4303-b9d5-da02c0db1b8b.png)

**Comment by chingucoding** [comment]
@HppZ The OS version inside the file name indicate the lowest supported OS for those styles. Unless overridden by a file with a higher OS version, the styles inside the RS1 will be used for all OS versions that are RS1 and newer. Since those styles are only defined in RS1 files, those are the styles you are searching for.
