### ISSUE TITLE
WinUI Design Toolkit Bug: RadioButton in the figma file needs to be updated

### ISSUE THREAD

**Issue by MajorBoo** [microsoft/microsoft-ui-xaml#6303]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
RadioButton

**Describe the bug:**
The RadioButton design in the figma file does not match the component we use in the Windows App SDK 1.0 Preview 3. It is more complex, please see the comparison.

**Version Info:**
2.7

**Additional context:**
![radiobutton](https://user-images.githubusercontent.com/93913816/141767458-2d8b0f54-bf3b-4021-8a13-0ea7e2bcc3a7.png)

**Comment by alejo4000** [comment]
Hi @MajorBoo  , Can you give more repro steps as to how you arrived at that visual? Are you using WinUI 3? is the XAML state you attached a hover, pressed, or selected state?

**Comment by MajorBoo** [comment]
> Hi @MajorBoo , Can you give more repro steps as to how you arrived at that visual? Are you using WinUI 3? is the XAML state you attached a hover, pressed, or selected state?

Hello! Yes WinUI 3, the radiobutton comparison state is:  
IsChecked="True" 
IsEnabled="False"

I'm trying to recreate some elements on WPF and I'm not quite sure where to get the reference, like the button:
Should I use the color style from this [file ](https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/Button_themeresources.xaml) or the use reference from the figma file? because if I compare the result xaml vs figma there is a difference between them.

I have attached another comparison, this time of a normal button
![xaml_vs_figma](https://user-images.githubusercontent.com/93913816/142278729-3405f683-e5c8-4230-96a6-210b14bb8f04.png)

Sorry, maybe I don't understand something... But why such a difference? As far as I understand Windows 11 buttons are more similar to those in figma file.

**Comment by alejo4000** [comment]
Hello @MajorBoo, It looks as though there are some discrepancies between the toolkit and WinUI 3. WinUI 2.7 and the toolkit show the most up to date designs. We will be updating WinUI 3 to match the toolkit in the future.
