### ISSUE TITLE
Exception on pinning App to taskbar

### ISSUE THREAD

**Issue by hwogit** [microsoft/microsoft-ui-xaml#6305]
### Describe the bug

Hi,

when I try to pin my app to the taskbar, I get an exception "Interface not registered" and error 0x80040155 when calling RequestPinCurrentAppAsync().

It is a WPF app that has been converted to a bridge app.

What is the cause of the problem?
```

     TaskbarManager taskbar = TaskbarManager.GetDefault();
    
     if (!await taskbar.IsCurrentAppPinnedAsync())
         await taskbar.RequestPinCurrentAppAsync();
```

### Steps to reproduce the bug

```
     TaskbarManager taskbar = TaskbarManager.GetDefault();
    
     if (!await taskbar.IsCurrentAppPinnedAsync())
         await taskbar.RequestPinCurrentAppAsync();
```

### Windows app type

- [ ] UWP
- [ ] Win32

### Windows version

May 2021 Update (19043)

**Comment by Jaiganeshkumaran** [comment]
@hwogit Currently, packaged desktop apps can't programmatically pin themselves to the taskbar using the WinRT TaskbarManager class: https://github.com/microsoft/WindowsAppSDK/issues/1648.

**Comment by Martian2812** [comment]
Any way then ? How we can implement the thing (pinning app to Taskbar)?

**Comment by ojhad** [comment]
@Martian2812 I would recommend going to the linked issue above to find updates & ask questions about this behavior.
