### ISSUE TITLE
Why does XAML parsing fail with a string DependencyObject 

### ISSUE THREAD

**Issue by capegreg** [microsoft/microsoft-ui-xaml#6306]
I am using a DependencyObject in a Windows Template Studio UWP project. I'm not finding any issues when I run the project in debug mode, but when run in release it throws an XAML parsing failed error with no details.

**Error**

Windows.UI.Xaml.Markup.XamlParseException
  HResult=0x802B000A
  Message=XAML parsing failed.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Consider this pseudocode as example
I have a TextBox in MyPage.xaml **

```xml
<Page 
x:Name="MyUI" 
xmlns:views="using:Demo.Views">
<Grid>
  <TextBox Text="{Binding ElementName=MyUI, Path=(views:MyDependencyClass.SomeText)}" />
</Grid>
</Page>
```

Setting the textbox value in code behind, MyPage.xaml.cs and the DependencyObject class

```cs
namespace Demo.Views {

public sealed partial class MyPage : Page, INotifyPropertyChanged {
SettingsDependencyClass.SetMyText(MyUI, "Blah");
}
public abstract class MyDependencyClass : DependencyObject
{
public static readonly DependencyProperty SomeTextProperty;

public static void SetSomeText(DependencyObject DepObject, string value)
{ 
DepObject.SetValue(SomeTextProperty, value); 
}
public static string GetSomeText(DependencyObject DepObject)
{ 
return (string)DepObject.GetValue(SomeTextProperty); 
}
static MyDependencyClass()
{ 
PropertyMetadata MyPropertyMetadata = new PropertyMetadata("");
SomeTextProperty = DependencyProperty.RegisterAttached("SomeText",
typeof(string),
typeof(MyDependencyClass),
MyPropertyMetadata);
}
}
}

```

**Comment by capegreg** [comment]
See reproducible response at https://stackoverflow.com/a/70210474/2288547

**Comment by StephenLPeters** [comment]
@RealTommyKlein FYI

**Comment by RealTommyKlein** [comment]
This is a mix of three things:

1. By default, Xaml in Debug builds uses reflection to resolve types.  In Release builds, it uses a generated type table by analyzing types used in `.xaml` files.  This is why the issue happens in Debug but not Release.  The behavior can be disabled by setting the MSBuild property `EnableTypeInfoReflection` to `false` in your projects, so Debug behavior matches the Release behavior.
2. The `MyDependencyClass` isn't used in markup or marked with a `[Windows.UI.Xaml.Data.Bindable]` attribute, so the Xaml compiler doesn't know it's necessary for Xaml and doesn't generate type info for it in Release builds.
3. There's a bug where the `Bindable` attribute has no effect on `abstract` types.

So the workaround steps would be:
- Add the `[Windows.UI.Xaml.Data.Bindable]` attribute to `MyDependencyClass`
- Make `MyDependencyClass` non-abstract
