### ISSUE TITLE
[UWP] Click of Button with Flyout crashes when built with NativeToolchain AND app project references an unused library project that contains a XAML page

### ISSUE THREAD

**Issue by baskren** [microsoft/microsoft-ui-xaml#6313]
### Describe the bug

If you have a UWP application with the following conditions:
- Contains a **Button** with a **MenuFlyout** as its **Flyout**
- Compiled with Native Toolchain
- References another project that contains a XAML**Page**

... the app will crash when the **Button** is pressed.
![image](https://user-images.githubusercontent.com/2528888/141599879-3ad9699f-3b1d-476d-8d10-83cc9158e6a2.png)

Some notes:
- Many attempts have made to address this via editing the app's **Default.rd.xml** file.  If there is something that could be added that actually address this crash, I would be very grateful as, for the project I am working on, there is no workaround for the consequences of this bug.
- The app won't crash if the project with the XAML**Page** is not referenced
- The app won't crash if the **Page** class is all code (no XAML)

## TO REPLICATE
1. Get demo project: https://github.com/baskren/UWP_UnusedXamlPageInUnusedLibraryCrash
2. Do either a **Release** build or a **Debug** build with **Native Toolchain** enabled
3. Click on the **Button** labeled **XAML**

### Expected behavior

Use of Libraries with XAML **Page** elements should not cause a **Button** with a **MenuFlyout** to crash.  

As an aside (and me just venting), what makes this particularly egregious is:
1.  The bug happens even when the library isn't actually used in the application (and thus should have been removed by the NativeToolchain linking).
2. Because of [this](https://github.com/microsoft/microsoft-ui-xaml/issues/6250) bug, for my application there there just isn't a work around for this issue.

### Windows version

May 2019 Update (18362)

### IDE

Visual Studio 2019

**Comment by StephenLPeters** [comment]
@Scottj1s is this a cswrint issue?

**Comment by baskren** [comment]
keep alive

**Comment by JesseCol** [comment]
Thanks for filing!  Unfortunately we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).
