### ISSUE TITLE
Blank App, Packaged (WinUI3 in Desktop) template project: missing High DPI awareness

### ISSUE THREAD

**Issue by Demonese** [microsoft/microsoft-ui-xaml#6315]
### Describe the bug

Window contents are blur.
In TaskManager, the DPI awareness is "Unknown".

### Steps to reproduce the bug

1. using "Blank App, Packaged (WinUI3 in Desktop)" template to create a c++ project
2. build and run

### Expected behavior

Window contents are clear.
The DPI awareness is "PerMonitorV2".

### Screenshots

![image](https://user-images.githubusercontent.com/57629614/141837751-60623086-3312-42e7-bcf3-7974bd4ff7c5.png)
![image](https://user-images.githubusercontent.com/57629614/141837829-d33b2635-be65-4419-963e-08dfd767b832.png)

### NuGet package version

1.0.0-preview3

### Packaging type

Packaged (MSIX)

### Windows version

May 2021 Update (19043)

### IDE

Visual Studio 2022

### Additional context

200% display scaling:
![image](https://user-images.githubusercontent.com/57629614/141838426-46ec3609-7ea0-48e5-afa3-8c5c6c0b8311.png)

**Comment by hez2010** [comment]
Duplicated #6075

**Comment by hez2010** [comment]
This should already be fixed with WASDK 1.0 GA

**Comment by Demonese** [comment]
1.0 solved this problem
