### ISSUE TITLE
WinUI Design Toolkit Bug: Status Bar component is missing

### ISSUE THREAD

**Issue by adsingh14** [microsoft/microsoft-ui-xaml#6322]
## WinUI Toolkit Bug Report

**Name of component or part of Toolkit:** 

**Describe the bug:** Status bar is a vital part of every app which is missing.

**Version Info:** 2.13.0

**Additional context:** 

I've created this community file for all. Please check status bar via [Figma Link](https://www.figma.com/community/file/1042435569228178035).

**Comment by alejo4000** [comment]
The Status bar is not a Windows UI control, so we haven't included it in the Windows UI toolkit.
