### ISSUE TITLE
Huge bug, mouse right click on any numberbox or textbox crashes new WinUI3 project instantly

### ISSUE THREAD

**Issue by EugenM88** [microsoft/microsoft-ui-xaml#6329]
### Describe the bug

Greetings, i think i've found a very huge bug in WinUI3.

Just create any new packaged project be it WAP or not.

As soon as you add a textbox and mouse right click on it semms at first that the textbox is trying to create a context menu but it only displays a very tiny portion of it and dissapears instantly, however, as soon as you write anything on the textbox and try the context menu again the application imediately crashes with the following error:

Exception thrown at 0x767EB502 in App2.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x027EDD08.

Is this bug already known? if so, what is the workaround?

XAML page code with no special code behind in C#
`<Window
    x:Class="App3.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App3"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">

            <TextBlock Text="Nationality" Width="90" Margin="5 5 5 5"  HorizontalAlignment="Center" VerticalAlignment="Center" TextAlignment="Right"/>
            <TextBox Width="200" HorizontalAlignment="Right" VerticalAlignment="Center" Margin="0"/>

    </StackPanel>
</Window>`

My Environment: VS2022 Community (non preview release)
WinUI3 1.0 Preview 3 (latest at the date of this post)
WinUI 3 Blank App Packaged (WAP and non WAP)
Windows 10 21h1 x64

### Steps to reproduce the bug

1. Create new WinUI3 Blank app Project
2. Add a textbox
3. Right mouse click on it
4. A very tiny context menu appears but dissapears
5. Write a text on the textbox
6. Right mouse click on it again
7. Application crashes.

### Expected behavior

Should simply open the textbox default context menu normaly.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by castorix** [comment]
I cannot reproduce it with an unpackaged C# app on same OS, with VS 2019

**Comment by EugenM88** [comment]
Could you please try the packaged C# app and see if it crashes on your system please?
As much data as we can get to narrow the issue down would be great!

**Comment by DominicMaas** [comment]
Can reproduce this. Windows 11, VS2022, Blank packaged WinUI3 1.0.0 app with the above specified XAML.

```
Exception thrown at 0x7567EB02 (KernelBase.dll) in WinUiTest.exe: WinRT originate error - 0x80070490 : 'Element not found.'.
onecore\com\combase\winrt\error\restrictederror.cpp(1017)\combase.dll!75A83529: (caller: 759928E2) ReturnHr(9) tid(e640) 8007007E The specified module could not be found.
Exception thrown at 0x7567EB02 in WinUiTest.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0301D808.
```

**Comment by EugenM88** [comment]
> Can reproduce this. Windows 11, VS2022, Blank packaged WinUI3 1.0.0 app with the above specified XAML.
> 
> ```
> Exception thrown at 0x7567EB02 (KernelBase.dll) in WinUiTest.exe: WinRT originate error - 0x80070490 : 'Element not found.'.
> onecore\com\combase\winrt\error\restrictederror.cpp(1017)\combase.dll!75A83529: (caller: 759928E2) ReturnHr(9) tid(e640) 8007007E The specified module could not be found.
> Exception thrown at 0x7567EB02 in WinUiTest.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0301D808.
> ```
> 
> Seems to work when running the application from outside Visual Studio (e.g. Start Menu)

Nice find, can confirm too, as soon as i close Visual Studio and run the app from the start menu its partially fixed:
On an empty textbox the context menu still tries to appear very small and then dissapears imediately but as soon as i write any text on the textbox the context menu appears properly.

**Comment by seven-mile** [comment]
Yeah, I encountered it since several versions ago. And if you ignore the exceptions, it won’t crash but the shadow of the context menu will be still missing.

**Comment by ebadger** [comment]
I can also hit in C++ packaged win32.
It only hits with a debugger attached.  If I run without the debugger attached, it doesn't crash.

**Comment by mpettus** [comment]
I am having a similar issue. Right clicking a textbox throws an error if debugger is attached. If it is not, default context menu is displayed properly.
