### ISSUE TITLE
Question: [WinUI 3] I want to create a focusable user control, but it doesn't work.

### ISSUE THREAD

**Issue by dimohy** [microsoft/microsoft-ui-xaml#6330]
I'm making a diagram editor and I use `OnPreviewKeyDown()` to get keys like TAB keys etc which are not normally available with `KeyboardAccelerators`.

Of course, in order to receive the key from the user control I created, it must be Focused.

So I set 'IsTabStop' to 'True' and forced focus. If you force the focus, you can receive the key from `OnPreviewKeyDown()`, but strangely, if you press and move the left mouse button, focus is lost.

(Middle or right mouse button does not lose focus.)

I don't know if this is a bug in WinUI 3, but I can't quite figure out the cause.

**Comment by dimohy** [comment]
Here's a simple test code.:
[WinUI3_LostFocusTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7554767/WinUI3_LostFocusTest.zip)

| MainWindow.xaml
```xaml
<Window
    x:Class="WinUI3_LostFocusTest.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUI3_LostFocusTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <local:TestControl Width="600" Height="600" HorizontalAlignment="Center" VerticalAlignment="Center" />
    </Grid>
</Window>
```

`TestControl` is a UserControl for focus testing.

| TestControl.xaml
```xaml
<UserControl
    x:Class="WinUI3_LostFocusTest.TestControl"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUI3_LostFocusTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d" IsTabStop="True">

    <Border Background="Blue">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>

            <TextBlock Grid.Row="0" x:Name="messageTextBlock" />
            <Button Grid.Row="1">Test</Button>
        </Grid>
    </Border>
</UserControl>
```

| TestControl.xaml.cs
```csharp
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Input;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.
namespace WinUI3_LostFocusTest
{
    public sealed partial class TestControl : UserControl
    {
        public TestControl()
        {
            this.InitializeComponent();

            Focus(FocusState.Programmatic);
        }

        protected override void OnPreviewKeyDown(KeyRoutedEventArgs e)
        {
            messageTextBlock.Text = $"{e.Key}";

            e.Handled = true;
        }

        protected override void OnTapped(TappedRoutedEventArgs e)
        {
            // Force focus, it's working
            Focus(FocusState.Programmatic);
        }

        protected override void OnPointerReleased(PointerRoutedEventArgs e)
        {
            // Force focus but not working
            Focus(FocusState.Programmatic);
        }

        protected override void OnLostFocus(RoutedEventArgs e)
        {
            messageTextBlock.Text = "LOST FOCUS!";
        }
    }
}
```

WinUI 3 1.0 is required, I simply checked the problem with the default template and it shows the same behavior.
Losing focus when the left mouse button is clicked is supplemented with `OnTapped()`, but losing focus when the mouse is released after moving is applied to `OnPointerReleased()`, but it does not work.

**Comment by MikeHillberg** [comment]
At the very root of the content, above your Window in the tree, is a focusable ScrollViewer. So if you click anywhere in the Window that's not focusable, it will take focus. You might be able to block this by canceling the [UIElement.LosingFocus](https://docs.microsoft.com/uwp/api/Microsoft.UI.Xaml.UIElement.LosingFocus) event. Or you could size your control larger, so that while transparent it still keeps focus?

**Comment by dimohy** [comment]
@MikeHillberg 

Is losing focus on left mouse button click correct behavior? If it's the correct behavior, is the only way to not lose focus is to cancel it from the `UIElement.LosingFocus` event? Because there are cases where focus should be canceled normally, right? How do I differentiate it from that event?

**Comment by StephenLPeters** [comment]
@dimohy LosingFocusEventArgs has a NewFocusedElement property you could use to see if focus is moving to the root scroll viewer so you could cancel the event.

**Comment by allangcabral** [comment]
Same problem here, any update to avoid cancel the focus when ScrollViewer is the NewFocusedElement?
