### ISSUE TITLE
Snap Layout on Win 11 Doesn't Show up When ExtendsContentIntoTitleBar is True

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/microsoft-ui-xaml#6333]
### Describe the bug

When we set ExtendsContentIntoTitleBar to **true** in the App.xaml.cs, The Windows 11 Snap layout Doesn't Show up but it works fine if we set ExtendsContentIntoTitleBar to **false**

### Steps to reproduce the bug

1. Go to App.xaml.cs
2. Navigate to OnLauched Method
3. Write "m_window.ExtendsContentIntoTitleBar = true;"
4. Start the app

### Expected behavior

The Windows 11 Snap Layout Should Show Up Either ExtendsContentIntoTitleBar is True or False

### Screenshots

![Screenshot 2021-11-18 021140](https://user-images.githubusercontent.com/17165402/142279904-126ae42b-44c4-4b30-8482-8b430f31db80.png)

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 (22000)

### IDE

Visual Studio 2022

**Comment by AathifMahir** [comment]
> Transferring to the WinUI repo as this is a property on the WinUI Window class.

Sure thing

**Comment by StephenLPeters** [comment]
@pratikone FYI

**Comment by gabbybilka** [comment]
Fixed in Windows App SDK 1.0.1, check out the [release notes](https://github.com/microsoft/WindowsAppSDK/discussions/2291) for more info.
