### ISSUE TITLE
Binding to RadioButtons.SelectedIndex does not work in WinUI3 desktop.

### ISSUE THREAD

**Issue by hayashida-katsutoshi** [microsoft/microsoft-ui-xaml#6335]
### Describe the bug

Binding to RadioButtons.SelectedIndex does not work in WinUI3 desktop.

Microsoft.WindowsAppSDK version 1.0.0.

### Steps to reproduce the bug

``` xml
<RadioButtons SelectedIndex="{Binding SelectedTheme}" Margin="0,0,0,24">
    <RadioButtons.Header>
        <TextBlock Text="Theme Mode"  Style="{StaticResource SubtitleTextBlockStyle}"/>
    </RadioButtons.Header>
    <RadioButtons.Items>
        <x:String>Light</x:String>
        <x:String>Dark</x:String>
    </RadioButtons.Items>
</RadioButtons>
```

``` cs
[ViewModel]
public partial class SettingsViewModel
{
    [PropertyCallMethod("OnSelectedTheme")]
    [Property]
    int selectedTheme;

    void OnSelectedTheme()
    {
        App.Current.RequestedTheme = selectedTheme == 0 ? Microsoft.UI.Xaml.ApplicationTheme.Light : Microsoft.UI.Xaml.ApplicationTheme.Dark;
    }
}
```

MvvmGen generates concrete properties as below.

``` cs
    partial class SettingsViewModel : global::MvvmGen.ViewModels.ViewModelBase
    {
        public SettingsViewModel()
        {
            this.OnInitialize();
        }

        partial void OnInitialize();

        public int SelectedTheme
        {
            get => selectedTheme;
            set
            {
                if (selectedTheme != value)
                {
                    selectedTheme = value;
                    OnPropertyChanged("SelectedTheme");
                    OnSelectedTheme();
                }
            }
        }
    }
```

It looks similar with #4893, but it does not use ItemsSource.

### Expected behavior

The sample code has a radio buttons. It is expected to call setter of SettingsViewModel.SelectedTheme.

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

**Comment by nikolayvpavlov** [comment]
The bug also to happens when setting **SelectedItem** and **SelectedItemIndex** from code.

**Comment by hayashida-katsutoshi** [comment]
Still waiting for update.

**Comment by kmahone** [comment]
Thanks for reporting this issue. I took a look and I did not run into issues binding to RadioButtons.SelectedIndex.

There are two issues with the code in the repro steps.

```
<RadioButtons SelectedIndex="{Binding SelectedTheme}" >
```

By default, Binding is OneWay. So interacting with the RadioButtons UI will not update the ViewModel. You can enable two way binding with:

```
<RadioButtons SelectedIndex="{Binding SelectedTheme, Mode=TwoWay}" >
```

The second issue is with this line:
```
App.Current.RequestedTheme = selectedTheme == 0 ? Microsoft.UI.Xaml.ApplicationTheme.Light : Microsoft.UI.Xaml.ApplicationTheme.Dark;

```
Application.RequestedTheme is only settable on app startup. See the Remarks section of the doc here: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.application.requestedtheme?view=windows-app-sdk-1.4. So this code will not have the intended effect.

From my testing, RadioButtons.SelectedIndex appears to be working as expected in the general case.
