### ISSUE TITLE
Platform XAML - Backport rounded focus rectangles to Windows 10

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#6336]
I know Platform XAML isn't receiving new features anymore however please consider backporting rounded focus rectangles instead of sharp square ones for controls with rounded corners (CornerRadius != 0). WinUI 2.x controls with rounded controls don't look good with sharp square focus rectangles.

**Comment by StephenLPeters** [comment]
I don't think this meets the bar we have for servicing fixes/features. This would be a significant change with compatibility concerns. @codendone could confirm my suspicions.
