### ISSUE TITLE
Incorrect colors and rendering makes some controls unreadable

### ISSUE THREAD

**Issue by SWB2** [microsoft/microsoft-ui-xaml#6344]
### Describe the bug

On Windows 10, certain controls with the new Windows-11 styles do not render correctly on my system, in certain cases to the point of making them unreadable. I have seen this in the XAML Controls Gallery (1.2.21.0), but it is now showing up in wide-release items like the recent refresh of the Microsoft Store (22110.1401.17.0). I am surprised I haven't seen this mentioned anywhere else, which suggests it might be something particular to my system, but I don't what the culprit might be.

Probably the best way to explain this is with screenshots. Here's toward the bottom of the Button page in XAML Controls Gallery:

<img width="375" alt="2021-11-18 18_19_39-XAML Controls Gallery" src="https://user-images.githubusercontent.com/35317667/142512128-aa67ba55-1761-4771-9986-a47ba6f60256.png">

The foreground text is not visible.

Same thing with ToggleButton:

<img width="375" alt="2021-11-18 18_21_09-XAML Controls Gallery" src="https://user-images.githubusercontent.com/35317667/142512270-de500904-02d6-48ea-a989-d2bea488ff60.png">

RadioButton looks off (is the selected RadioButton really supposed to render as a solid circle?):

<img width="375" alt="2021-11-18 18_22_05-XAML Controls Gallery" src="https://user-images.githubusercontent.com/35317667/142512392-14b2f7ab-f47b-4c7d-bc79-804798206833.png">

Also ToggleSwitch:

<img width="375" alt="2021-11-18 18_23_25-XAML Controls Gallery" src="https://user-images.githubusercontent.com/35317667/142512443-222388e4-bc13-4071-aabd-01004ed1b33c.png">

Finally, Here's the new Microsoft Store:

<img width="680" alt="2021-11-18 18_25_52-Microsoft Store" src="https://user-images.githubusercontent.com/35317667/142512679-347a9ac6-bf7d-4f23-aeb3-aeb7092aa973.png">

Some of these (e.g. ToggleSwitch) look fine in light mode. Others look worse. For example, Here's a standard Button:

<img width="440" alt="2021-11-18 18_28_52-XAML Controls Gallery" src="https://user-images.githubusercontent.com/35317667/142512927-6af48ca7-e224-407d-b0ca-f644c613e09c.png">

Side note: The baby-blue accent color does not match my system-preference accent color, which is the Windows 10 default blue. I don't like that (I would prefer my chosen accent color be honored), but I don't know if that's a bug or a deliberate design decision.

### Steps to reproduce the bug

1. Open an app that is using the new Windows-11 style XAML styles (e.g. XAML Controls Gallery or the new Microsoft Store).

### Expected behavior

1. Controls are styled correctly and foreground content is visible.
2. Also, preferably the system defined accent color is honored.

### Windows app type

- [x] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Further details of my system, in case they are relevant:

- Nvidia RTX A4000, Driver version 496.49.
- Windows 10 Pro for Workstations 21H1 19043.1288

**Comment by niels9001** [comment]
Looks like we hit this bug with XAML Islands as well in PowerToys:

https://github.com/microsoft/PowerToys/issues/14164#issuecomment-966855342

**Comment by PaulCoddington** [comment]
I'm also seeing this problem in Win 10 Pro x64 21H1/H2 (AMD Ryzen with NVIDIA).

Power Toys and the new Windows Store have blank controls (and the store has "blank" headers at the top of the page, with white text on near white background).

**Comment by StephenLPeters** [comment]
Possibly related to https://github.com/microsoft/microsoft-ui-xaml/issues/6119#issuecomment-949982972  @chigy FYI

**Comment by Aaron-Junker** [comment]
Could we olease get triage on this issue. There are also more and more people in the Feedback Hub, who report this

**Comment by cdytoby** [comment]
Hello I'm the one who created the issue #6574 , and it seems I'm not the only one.

I highly doubt that it's hardware issue. I have pretty standard hardware: i7-6700K cpu, and a RTX 3070 gpu.

**Comment by stevetangp** [comment]
I was also having this problem, found two ways to fix it.
1. if you are using nvidia driver version before the latest 511.23, see if you are using 10 bit color depth. I had this problem when the color depth was set to 10 bit, when I changed it to 8 bit, the problem was gone.
2. updating to nvidia driver 511.23, with this version of driver, even the color depth is set to 10 bit, the colors are rendering correctly.

**Comment by SWB2** [comment]
Can confirm:

* I have Nvidia hardware
* I'm using 10-bit color depth
* The problem has gone away since updating to RTX/Quadro driver version 511.09

It's still using the wrong accent color per my Windows preferences, but I assume that's an unfortunate design decision rather than a bug.

**Comment by cdytoby** [comment]
I can also confirm, I'm using 10-bit (Monitor) and 12-bit (TV) color, both monitor are HDR and they're not constantly enabled. 

(I enable it only in games that supports HDR, but I don't change color depth because I need to go through all the menus.)

Update driver to 511.23 fixed it.

**Comment by PaulCoddington** [comment]
Can confirm:

NVIDIA card with 10-bit color-managed SDR and 12-bit HDR workflows.

Did not even occur to me to try 8-bit (not an acceptable workaround, due to photo/video editing needs).

Update to latest NVIDIA Studio Driver 511.09 (January 2022) resolves this issue for Windows Store, Feedback Hub and PowerToys (511.23 is the Game Ready driver).
