### ISSUE TITLE
Adding PrimaryCommands dynamically in CommandBarFlyout with no PrimaryCommands initially causes weird cropping.

### ISSUE THREAD

**Issue by karkarl** [microsoft/microsoft-ui-xaml#6345]
### Describe the bug

Adding PrimaryCommands dynamically in CommandBarFlyout with no PrimaryCommands initially causes weird cropping. This is due to `WidthExpansionDelta` setting a non-zero value. The only time `WidthExpansionDelta` is non-zero should be when it expands, such as the "Show expanding CommandBarFlyout" test case. The calculations currently do not account for this specific edge case.

### Steps to reproduce the bug

1. Go to CommandBarFlyout -> Base CommandBarFlyout Tests
2. "Toggle Add Primary Commands Dynamically?"
3. Invoke CBF with "Show CommandBarFlyout with no primary commands" 
4. Observe weird cropping once PrimaryCommands are loaded.

### Expected behavior

There should be no crop.

### Screenshots

![image](https://user-images.githubusercontent.com/7976322/142514443-81e9b8ec-6c9e-47f1-9ef8-1657b183ce65.png)

### Windows app type

- [X] UWP
- [ ] Win32

**Comment by zhuxb711** [comment]
Might be related to #4878
