### ISSUE TITLE
Bug: NumberBox.ValueChanged event is invoked after setting Value programmatically.

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/microsoft-ui-xaml#6347]
### Describe the bug

According to the [NumberBox.ValueChanged documentation](https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.controls.numberbox.valuechanged):

> Occurs after the user triggers evaluation of new input by pressing the Enter key, clicking a spin button, or by changing focus.

However, this event is invoked seemingly any time Value is changed programmatically as well. 

If this is expected behavior, then the docs should be changed to read similar to [TextBox.TextChanged](https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.controls.textbox.textchanged):

> Occurs when content changes in the text box.

### Steps to reproduce the bug

[See this repo](https://github.com/kmgallahan/NumberBoxBugs) to repro. Click the "Set Value programmatically" button.

### Expected behavior

Based on the docs I would not expect that setting Value programmatically would invoke this supposedly user-driven event.

### Screenshots

![Screenshot 2021-11-18 191553](https://user-images.githubusercontent.com/5379488/142517025-8bf3f581-a813-41a0-8233-aee09a3f2e7e.jpg)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Present in WASDK 1.0. 

That version isn't currently available under the bug template's "NuGet package version" combobox.

**Comment by StephenLPeters** [comment]
@SavoySchuler do you know if this behavior is by design and the docs need to be updated or if the docs are correct and we have a bug in the control?

**Comment by kmgallahan** [comment]
Docs still need to be updated here.

**Comment by ranjeshj** [comment]
https://github.com/MicrosoftDocs/winui-api/pull/138
