### ISSUE TITLE
Can't EnsureCoreWebView2 from an Async Main Application

### ISSUE THREAD

**Issue by AtomicBlom** [microsoft/microsoft-ui-xaml#6349]
### Describe the bug

While testing the waters to see if I can port my company's product to WinUI 3 (packaged, desktop) I found that I struggling to migrate the Auth from WebView to WebView2, due to the following exception:

```
Exception thrown at 0x76B3B502 (KernelBase.dll) in WebView2InWinUI3.exe: WinRT originate error - 0x80010106 : 'Cannot change thread mode after it is set.'.
```

I managed to narrow it down to the fact that the guidance for [Single Instancing](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/applifecycle#single-instancing-in-main-or-wwinmain) suggested I should DISABLE_XAML_GENERATED_MAIN and perform my single instance checking in my own main method, which required marking it as Async.

When marking the method as async, even though it's been declared [STAThread], if the first line of code called is `Thread.CurrentThread.GetApartmentState()`, it returns MTA.

ThreadDispatcher.TryEnqueue doesn't move the workload to an STA thread unfortunately.

### Steps to reproduce the bug

I've provided a minimum reproduction sample here: https://github.com/AtomicBlom/WebView2InWinUI3, you can switch the behaviour of the application by changing main method in `Program.cs`

1. Create a new blank WinUI App.
2. Add a WebView 2 to MainPage
3. Add a call after the window is activated to `webView.EnsureCoreWebView2Async()`, and then `webView.CoreWebView2.Navigate("http://www.microsoft.com");`
4. Copy the generated main method and Program class from App.g.i.cs to a new file (Program.cs)
5. Add the DISABLE_XAML_GENERATED_MAIN compiler conditional to the build
6. change the main method from `static void Main(String[] args)` to `static async Task(String[] args)`

### Expected behavior

The application should navigate to the webpage.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by sharpninja** [comment]
I can validate this error.

**Comment by StephenLPeters** [comment]
@krschau FYI

**Comment by pjc2007** [comment]
Making Main non async and using `RedirectActivationToAsync(args).GetAwaiter().GetResult();` seems to have fix it for me
