### ISSUE TITLE
Question: is there any way to control window transparency with button control in winui3+win32

### ISSUE THREAD

**Issue by Sacwith** [microsoft/microsoft-ui-xaml#6351]
I need to create mainwindow in that child window and I need to add 2 buttons in child window first btnclick need to control transparency of Main window and 2 nd btnclik2 need to remove transparency of Mainwindow is this possible to do using winui3 or win32?

**Comment by castorix** [comment]
You can just use **SetLayeredWindowAttributes** :

![WinUI_Transp](https://user-images.githubusercontent.com/22345506/142616842-7e985076-316e-47a5-a089-8b638cc8d1fb.gif)

**Comment by Sacwith** [comment]
Can u please send be code for this please

**Comment by Sacwith** [comment]
@castorix can u please send a bit of source code of ur application im making as exactly urs it would be helpful if u send

**Comment by castorix** [comment]
I had posted a test sample in this thread [Need my button click also should work with transparency and dont want the app to gain the focus.](https://docs.microsoft.com/en-us/answers/questions/630720/need-my-button-click-also-should-work-with-transpa.html)

**Comment by Sacwith** [comment]
Can we make multiple window ? In winui3 like window on window so that I can
put my controls on 2nd window and I will try to control transparancy of
first window through button click so that my controls won't get transparent

**Comment by StephenLPeters** [comment]
@codendone I think transparent windows are not supported in 1.0, correct?
