### ISSUE TITLE
AppWindow.GetFromWindowId crashes in WinUI3 desktop application in unpackaged mode.

### ISSUE THREAD

**Issue by hayashida-katsutoshi** [microsoft/microsoft-ui-xaml#6353]
### Describe the bug

* NuGet package version: Windows App SDK 1.0.0 (stable)
* VisualStudio 2022. 17.0.1
* x64

### Steps to reproduce the bug

1. Create "Blank App, Packaged (WinUI 3 in Desktop)" project.
2. Delete "Package.appxmanifest".
3. Add `<WindowsPackageType>None</WindowsPackageType>` to the property group in the project.
4. Add this code.

``` cs
public MainWindow()
{
    this.InitializeComponent();

    IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
    WindowId myWndId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);
    AppWindow aw = AppWindow.GetFromWindowId(myWndId);
}
```

5. Run the application.

```
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception has been thrown by the target of an invocation.
```

stack trace.
```
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Windowing.AppWindow._IAppWindowStatics.get_Instance()
   at Microsoft.UI.Windowing.AppWindow.GetFromWindowId(WindowId windowId)
   at ModuleHub.MainWindow..ctor() in C:\\k4\\ModuleHub\\ModuleHub\\MainWindow.xaml.cs:line 42"	string
```

Inner exception.

```
SEHException: External component has thrown an exception.
```

stack trace.

```
   at WinRT.Platform.RoGetActivationFactory(IntPtr runtimeClassId, Guid& iid, IntPtr* factory)
   at WinRT.WinrtModule.GetActivationFactory(IntPtr hstrRuntimeClassId)
   at WinRT.WinrtModule.GetActivationFactory(String runtimeClassId)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at Microsoft.UI.Windowing.AppWindow._IAppWindowStatics..ctor()"	string
```

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [x] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

**Comment by castorix** [comment]
I had signaled it in the WindowsAppSDK forum,  but after some tests, I found that the bug is fixed by adding

```
 <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
        <application>
			<!-- Windows 10 -->
			<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>           
        </application> 
    </compatibility>
```

in the app.manifest

**Comment by hayashida-katsutoshi** [comment]
It works! Thank you.

**Comment by ScoPeZs** [comment]
I'm having a similar issue, I can't get the project to start and I'm not getting any errors and @castorix's code didn't fix it for me.

Here's how to reproduce 
Create "Blank App, Packaged (WinUI 3 in Desktop)" project.
Delete "Package.appxmanifest".
Add <WindowsPackageType>None</WindowsPackageType> to the property group in the project.
Try to debug

Here's a video showing what's happening to me.
[https://imgur.com/hDJkpQi](url)

**Comment by BlueprintBen** [comment]
I'm hitting the same issue but am not seeing that fix work - Am still getting the exact same exception on AppWindow.GetFromWindowId(). Here's my app.manifest:
```
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
	<assemblyIdentity version="1.0.0.0" name="WinUI.app"/>
	<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
		<application xmlns="urn:schemas-microsoft-com:asm.v3">
			<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
		</application>
	</compatibility>
</assembly>
```

**Comment by hayashida-katsutoshi** [comment]
Here is my app.manifest.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity version="1.0.0.0" name="Sample.app"/>

  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <!-- The combination of below two tags have the following effect:
           1) Per-Monitor for >= Windows 10 Anniversary Update
           2) System < Windows 10 Anniversary Update
      -->
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
    </windowsSettings>
  </application>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
</assembly>
```

**Comment by rcohn** [comment]
Hello -

I am running Windows App SDK 1.0 for C++/winrt.  When I try to use ApplicationView::GetForCurrentView(), I am still crashing.  Here is the code:

`void App::OnLaunched(LaunchActivatedEventArgs const&)
{
    window = make<MainWindow>();
    window.Activate();

   ApplicationView::GetForCurrentView().SetPreferredMinSize(Size(500, 500));
}`

**Comment by Balkoth** [comment]
There should not be any hacks needed to make a winui3 app run on an already supported platform. Sadly this 1.0 version feels rushed, nowhere near production viable.

**Comment by eshvatskyi** [comment]
any updates?

**Comment by rcohn** [comment]
We decided not to use WinUI3 WinRT/C++.  We're now using C#.  I have other gripes about the 1.0 SDK, but we've eliminated a class of problems by deciding not to use the WinRT/C++ support.

**Comment by tomasfil** [comment]
Same problem here Windows App SDK 1.0 C#

**Comment by eshvatskyi** [comment]
> Same problem here Windows App SDK 1.0 C#

Solution from this thread works, just be sure you added 
<PropertyGroup>
....
<ApplicationManifest>app.manifest</ApplicationManifest>
...
</PropertyGroup>

**Comment by tomasfil** [comment]
@eshvatskyi Agreed. Got it working. Now just gotta wait for working TitleBar customization on windows 10 in WinUI 3.

**Comment by eshvatskyi** [comment]
> @eshvatskyi Agreed. Got it working. Now just gotta wait for working TitleBar customization on windows 10 in WinUI 3.

the wokaround it to use AppWindows.

`
Hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
            var windowId = Win32Interop.GetWindowIdFromWindow(Hwnd);

            _appWindow = AppWindow.GetFromWindowId(windowId);
...
if (_appWindow.Presenter is OverlappedPresenter presenter)
                {
                    presenter.SetBorderAndTitleBar(!value, !value);
                    presenter.IsMaximizable = !value;
                    presenter.IsMinimizable = !value;
                    presenter.IsResizable = !value;
                }

`

**Comment by tomasfil** [comment]
@eshvatskyi Oh god thank you. It is sad that it has to be that much hacky, also I couldnt find this anywhere for like 2 days. WinUI 3 need lots of love

**Comment by StephenLPeters** [comment]
@bpulliam and @codendone FYI

**Comment by rcohn** [comment]
Hello -

Has there been any progress on a fix for **ApplicationView.GetForCurrentView()** crashing in a WinUI3 app?  I would like to use this call (and similar) to get display information: **ApplicationView.GetForCurrentView().VisibleBounds**;

But as long as **GetForCurrentView()** is always crashing, this is a real blocker.

Thank you.

**Comment by pratikone** [comment]
the supportedos clause now is part of app manifest of new winui templates. existing projects can copy from it
