### ISSUE TITLE
New Page wizard doesn't filter out WUX new Page from cppwinrt VSIX

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6355]
### Describe the bug

I have the cppwinrt vsix (for wux/uwp), and the VS wizard UI doesn't filter this out. So you end up with a WUX Page class instead.
You try to build, and get this lovely WMC error:
![image](https://user-images.githubusercontent.com/22989529/142719128-6ece5c6d-efce-4437-805c-07ed436d6539.png)

### Steps to reproduce the bug

In a winui3 project, add->new item
wrongly select the WUX page that is added by the cppwinrt vsix

### Expected behavior

UWP templates are filtered out of the UI if the app is winappsdk

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by Jaiganeshkumaran** [comment]
You should report this to C++/WinRT, not WinUI.

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI
