### ISSUE TITLE
`TwoPaneView` does not revoke events

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/microsoft-ui-xaml#6357]
### Describe the bug

The `TwoPaneView` sets up `m_windowSizeChangedRevoker`, `m_pane1LoadedRevoker` and `m_pane2LoadedRevoker` but it seems they are never revoked. Am I missing something and is it intentional or is it a oversight?

### Steps to reproduce the bug

Looking into the code 👀

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@MartinZikmund the revoker object used to establish these event handlers has code in it's destructor to unregister the events.  We should probably be revoking these in the OnApplyTemplate call as well, this could cause issues in scenarios where a template is applied to the control multiple times.
