### ISSUE TITLE
Question: [Is there any way to make Winui3 applocation Top on all other application on windows even it should come Top on Start Menu windows ]

### ISSUE THREAD

**Issue by Sacwith** [microsoft/microsoft-ui-xaml#6361]
Hi
I am creating a overlay using OverlappedPresenter
iIm making overlay top on all application i have achived this but it not coming top on Windows start Menu is there any way to do it By using Winui3

**Comment by Sacwith** [comment]
any reply @pratikone @mrlacey @joelleigh @Marv51 @

**Comment by sylveon** [comment]
The start menu is using private OS functionality that allows it to present on top of every other window. You can't go over it. What are you trying to achieve?

**Comment by Sacwith** [comment]
I'm trying achieve my winui3 overlay come too on all other applications and
on game window we achived it by using WPF by giving UiAccess=true flag ain
appmanifest but in winui3 we can not able to do that so we are searching
other way to make it too always
