### ISSUE TITLE
Question: [Is it possible to make window transparaent but not controls(controls should remain Non transparant) in Winui3?]

### ISSUE THREAD

**Issue by Sacwith** [microsoft/microsoft-ui-xaml#6364]
I have achieved to make window transparent by using **SetWindowLayeredAttribute:** but its making even controls also transparent i don't want controls to be transparent is there any way to make this using Winui3?

**Comment by EugenM88** [comment]
I dont think it is currently possible, i am waiting for the possibility to add that nice acrylic effect to my window app background but it is not possible so far, you can only add in app acrylic and not app background acrylic effect, for that reason i will assume it is not possible to make the background transparent yet or else we would have that effect by now.

**Comment by mrlacey** [comment]
Not yet possible but there is a proposal for adding this: https://github.com/microsoft/microsoft-ui-xaml/issues/1247
