### ISSUE TITLE
Question: Can we expect WinUI 3 Controls Gallery 1.0 in Store?

### ISSUE THREAD

**Issue by get-flat** [microsoft/microsoft-ui-xaml#6366]
Question: Can we expect WinUI 3 Controls Gallery 1.0 in Store?

**Comment by gregwoo-microsoft** [comment]
Yes @get-flat ! We are currently working on one and it should be available within the next couple of weeks. Stay tuned!

**Comment by gregwoo-microsoft** [comment]
Hey @get-flat! The new version of the WinUI 3 Controls Gallery is out in the Store right now! It uses the WinAppSDK 1.0 that was recently released + a bunch of control updates. We will update the code on the WinUI 3 branch of the XAML Controls Gallery  in early Jan as we are still working out some small details.
