### ISSUE TITLE
Question: Supports multiple top-level windows

### ISSUE THREAD

**Issue by muramasa** [microsoft/microsoft-ui-xaml#6367]
Because it is important feature for me to implement application,
could you provide release plans for that?

That is changed last time
https://github.com/microsoft/microsoft-ui-xaml/pull/6129/files#diff-6a17656d764b8e1930354f341cf7f47960b63845c3046edcd8bbf282aaa2f464R117

I can imagine it is hard to publish plans but if the priority is published, it is so helpful for development plan.

I guess this is related to
https://github.com/microsoft/microsoft-ui-xaml/issues/6338 proposal.

**Comment by kmgallahan** [comment]
Vote and wait:

https://portal.productboard.com/winappsdk/1-windows-app-sdk/tabs/2-planned
