### ISSUE TITLE
Xaml Islands CTRL + SHIFT + Right Arrow unexpected behaviour in AutoSuggest/TextBox

### ISSUE THREAD

**Issue by stefansjfw** [microsoft/microsoft-ui-xaml#6376]
### Describe the bug

Having AutoSuggestBox and/or TextBox in Xaml Island hosted usercontrol results in CTRL + SHIFT + Right Arrow weird behavior while focus is in AutoSuggestBox or TextBox. Instead of selecting text from current position to next blank character, focus jumps to next element in Xaml Island.

Example test code could be found here:
https://github.com/stefansjfw/Xaml-Islands-Samples/tree/stefan/textbox_issue_example

This issue is not present if there are more UI elements next to Xaml Island present in the same window (try reverting deleted code in SampleApp.cpp or just code which creates m_button1 element is enough).

Issue initially discovered here https://github.com/microsoft/PowerToys/issues/14488

### Steps to reproduce the bug

1. Clone https://github.com/stefansjfw/Xaml-Islands-Samples/tree/stefan/textbox_issue_example branch
2. Build and run solution
3. CTRL + SHIFT + Right Arrow while focus is in AutoSuggestBox or TextBox to select text 
4. Observe the behavior

### Expected behavior

CTRL + SHIFT + Right Arrow while focus is in AutoSuggestBox or TextBox works as expected

### Screenshots

CTRL + SHIFT + Right Arrow while focus is in AutoSuggestBox or TextBox moves focus to next UI element

### Windows app type

- [ ] UWP
- [ ] Win32

### Windows version

May 2021 Update (19043)

**Comment by crutkas** [comment]
Team, ping!

**Comment by StephenLPeters** [comment]
@marb2000 and @bpulliam FYI
