### ISSUE TITLE
Question :`Microsoft.ui.xaml.dll` is unable to load

### ISSUE THREAD

**Issue by bryaan** [microsoft/microsoft-ui-xaml#6377]
I am getting an exception in my WinUI3 app that Microsoft.ui.xaml.dll is unable to load. I have included Microsoft.UI.Xaml and Microsoft.Graphics.Win2D in nuget.

```
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=TibraUI
  StackTrace:
   at TibraUI.Program.XamlCheckProcessRequirements()
   at TibraUI.Program.Main(String[] args) in C:\Users\Bryan\src\tibra\Tibra\TibraUI\obj\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\App.g.i.cs:line 28
```

Windows Version 21H1 Build 19043.1348

My App.xaml

```
<Application
    x:Class="TibraUI.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TibraUI">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <!-- Other merged dictionaries here -->
            </ResourceDictionary.MergedDictionaries>
            <!-- Other app resources here -->
        </ResourceDictionary>
    </Application.Resources>
</Application>

```

**Comment by sylveon** [comment]
Are you possibly missing https://www.nuget.org/packages/Microsoft.VCRTForwarders.140/?

**Comment by bryaan** [comment]
@sylveon Didn't work.

**Comment by Thorocaine** [comment]
I am having the same trouble.

**Comment by runceel** [comment]
I faced same issue. In my case, root cause was `launchSettings.json`.

When I had faced this issue the file was:
```json:launchSettings.json
{
  "profiles": {
    "Project Name": {
      "commandName": "Project"
    },
    "WSL": {
      "commandName": "WSL2",
      "environmentVariables": {},
      "distributionName": ""
    }
  }
}
```

I changed the file to fix this issue to:
```json:launchSettings.json
{
  "profiles": {
    "Contoso.Expenses.WindowsAppSdk (Package)": {
      "commandName": "MsixPackage"
    },
    "Contoso.Expenses.WindowsAppSdk (Unpackaged)": {
      "commandName": "Project"
    }
  }
}
```

`launchSettings.json` was ignored by `.gitignore`. I cloned my WinUI 3.0 project from a git repository. Then Visual Studio generated default `launchSettings.json`. It didn't work for WinUI 3.0 project. So I had to change it myself to fix this error.

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI

**Comment by heartacker** [comment]
```
{
  "profiles": {
    "Project Name (Package)": {
      "commandName": "MsixPackage"
    },
    "Project Name (Unpackaged)": {
      "commandName": "Project"
    }
  }
}
```
I face this issue
![image](https://user-images.githubusercontent.com/1876302/184348052-1bb055a1-5e88-47e0-b80c-fd59927bf9d0.png)

- Project Name (Package) this is ok
- Project Name (Unpackaged) this is fail

**Comment by evelynwu-msft** [comment]
@heartacker If you select the included-by-default launch profile `<Project Name> (Unpackaged` then you are launching an *unpackaged* Windows App SDK app and there are additional steps required for that detailed [here](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps#deploy-windows-app-sdk-runtime) (specifically, the Windows App SDK runtime needs to be manually deployed first).

**Comment by corwestermaniddink** [comment]
This is not solved.. don't close
