### ISSUE TITLE
Dynamic add items to CommandBarFlyout might leads PrimaryCommand being covered

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#6379]
### Describe the bug

This issue will be found only when CommandBarFlyout pop up in "Up" direction.
It seems that SecondardCommand extends it height and cover the PrimaryCommand in this situation

### Steps to reproduce the bug

1. Set Placement="RightEdgeAlignedTop"
2. Found a point that force CommandBarFlyout pop in "Up" direction (Down is no more space)
3. Add some AppBarButtons to the SecondaryCommand

### Expected behavior

Do not cover the PrimaryCommand

### Screenshots

![GIF 11-25-2021 4-00-38 PM](https://user-images.githubusercontent.com/42038175/143402971-908c4463-f051-45e2-8976-d1af3276385a.gif)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@karenbtlai and/or @llongley  This was fixed by one of you, correct? (I can't find the PR...);

**Comment by karenbtlai** [comment]
I remembered filing a bug (#6345) related to CommandBarFlyout dynamic load, but have not fixed it yet. Does this bug still repro?

**Comment by zhuxb711** [comment]
@StephenLPeters I saw this bug on Win10 and but Win11 (Might not correct). If CommandBarFlyout pops in "Up" direction, add AppBarBuutton to its SecondaryCommand might lead to this issue.
