### ISSUE TITLE
CommandBarFlyout does not respect ShouldConstrainToRootBounds

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#6380]
### Describe the bug

Set ShouldConstrainToRootBounds="False" but CommandBarFlyout is still limited in the XAML root

### Steps to reproduce the bug

1. Set ShouldConstrainToRootBounds="False"
2. Found that takes no effect

### Expected behavior

Should be able to display outside the XAML root

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by castorix** [comment]
This has already been reported : [The ShouldConstrainToRootBounds property of the Popup doesn't work ](https://github.com/microsoft/microsoft-ui-xaml/issues/5958)

**Comment by zhuxb711** [comment]
@castorix #5958 said that is a bug in WinUI3, also exists in UWP WinUI 2.7

**Comment by StephenLPeters** [comment]
@llongley is there a technical limitation for why this doesn't work today?

**Comment by llongley** [comment]
A very quick test app shows that it seems to work:

<img width="189" alt="image" src="https://user-images.githubusercontent.com/18177025/154374082-d5ae9d8b-6354-4fe0-98f0-cc70f2c871d8.png">

@zhuxb711 do you have a test app demonstrating the issue you're seeing?
