### ISSUE TITLE
Loaded and Unloaded called out of order.

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#6381]
### Describe the bug

Loaded and Unloaded called out of order, which causes EventTriggerBehavior and InvokeCommandAction fail to work.

### Steps to reproduce the bug

[Bug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7601569/Bug.zip)

### Expected behavior

1. EventTriggerBehavior and InvokeCommandAction shoud work.
2. UnLoaded event should raise before Loaded event.

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by azchohfi** [comment]
Adding @evelynwu-msft.
I believe she might know more about this.
I've reported this issue a while ago, and it is already being tracked internally.

**Comment by evelynwu-msft** [comment]
This is a long-standing issue in XAML; this [comment](https://github.com/microsoft/microsoft-ui-xaml/issues/1900#issuecomment-585980935) from @MikeHillberg provides an explanation and workaround.
