### ISSUE TITLE
Not getting the onBackgroundActivated and OnSuspending events in Application class while creating the Winui3 App

### ISSUE THREAD

**Issue by asadishfaq** [microsoft/microsoft-ui-xaml#6383]
### Describe the bug

I am creating a winui3 application and having latest .net sdk but not getting the onBackgroundActivated, OnSuspending events in the App class that extends the Application class.i have windows 10(version 19042), Windows.Foundation.UniversalApiContract (v4.0)
![error](https://user-images.githubusercontent.com/62933407/143447367-d9fc6205-d2c0-4e36-8c7a-b27ec44fe33d.PNG)

### Steps to reproduce the bug

Go to the App.xml.cs file where i have to use the onBackgroundActivated event but cant get this event.

### Expected behavior

i think Application class should have to provide the onBackgroundActivated event.

### Windows app type

- [X] UWP
- [ ] Win32

### Windows version

May 2020 Update (19041)

**Comment by roxk** [comment]
1. WinUI 3 app doesn't have `OnSuspending` post 0.8 preview anymore. 
2. You mentioned you are creating WinUI 3 app, but for app type you ticked UWP. Are you using 0.8 preview?

**Comment by kmgallahan** [comment]
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation#activation-details-for-packaged-apps

**Comment by asadishfaq** [comment]
> 1. WinUI 3 app doesn't have `OnSuspending` post 0.8 preview anymore.
> 2. You mentioned you are creating WinUI 3 app, but for app type you ticked UWP. Are you using 0.8 preview?

i need
