### ISSUE TITLE
WIN UI and UWP life cycle

### ISSUE THREAD

**Issue by aammfe** [microsoft/microsoft-ui-xaml#6387]
Hello!
I have created an application in WIN-UI-3 and trying to get [UWP life cycle hooks/events](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle) in win-ui-3. but unable to find any life cycle hooks/events in it.

1- actually I'm trying to create an activity monitoring application, something like hubstuff and I want to know if I'm on right path
2- Please suggest what should I do ?

this is my .csprod

```
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<OutputType>WinExe</OutputType>
<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
<RootNamespace>App3</RootNamespace>
<ApplicationManifest>app.manifest</ApplicationManifest>
<Platforms>x86;x64;arm64</Platforms>
<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
<UseWinUI>true</UseWinUI>
</PropertyGroup>



<!-- Workaround for https://github.com/dotnet/sdk/issues/17890 -->
<PropertyGroup>
<NoWarn>CA1416, $(NoWarn)</NoWarn>
</PropertyGroup>



<ItemGroup>
<Manifest Include="$(ApplicationManifest)" />
</ItemGroup>



<ItemGroup>
<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />
</ItemGroup>
</Project>
```

**Comment by kmgallahan** [comment]
WinUI 3 lifecycle doesn't work the same as the UWP version.

https://docs.microsoft.com/windows/apps/develop/app-lifecycle-and-system-services

**Comment by StephenLPeters** [comment]
@MikeHillberg do these life cycle events make sense in Winui3?
