### ISSUE TITLE
Question: Notification about main window closing

### ISSUE THREAD

**Issue by anovik** [microsoft/microsoft-ui-xaml#6389]
Could we receive some notification in WinUI3 lifecycle model about main window is closing? Something similar to UWP

`closeRequested(object sender, SystemNavigationCloseRequestedPreviewEventArgs e)`

so it would be possible to handle it and may be cancel it.

If it is not possible in current release, could you consider adding this in the next release?

**Comment by castorix** [comment]
Instead of calling directly Window.Close, you can post WM_CLOSE to the main window and intercept it to ask confirmation  : 

![WinUI_WM_CLOSE](https://user-images.githubusercontent.com/22345506/143677523-1479da6b-2e20-41bf-9e91-21c790935f57.gif)

**Comment by castorix** [comment]
If you close the main window by clicking on the "X" system button, **WM_CLOSE** is sent and you can intercept it (for example with SetWindowSubclass)

**Comment by anovik** [comment]
@castorix Could you please provide a code sample how I can do this in WinUI3 app? Thanks.

**Comment by castorix** [comment]
For example : [WM_CLOSE test](http://pastebin.fr/100002)

**Comment by castorix** [comment]
You can do something like this : [WM_CLOSE test](http://pastebin.fr/100004)

**Comment by anovik** [comment]
@castorix Thanks, it works
