### ISSUE TITLE
TeachingTip throws exception when calling isOpen

### ISSUE THREAD

**Issue by Cryomouse** [microsoft/microsoft-ui-xaml#6393]
### Describe the bug

This bug appears to be extremely similar to [this (#349)](https://github.com/Microsoft/microsoft-ui-xaml/issues/349).

When running under a debugger calling IsOpen(true) on a TeachingTip seems to crash the application. Application runs fine when not under the debugger.

Currently have the WinUI 2022 extension, fresh install on both Visual Studio 2022 and the extension. Followed steps listed [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-unpackaged-cpp) to create an unpackaged C++ application.

### Steps to reproduce the bug

TeachingTip XAML copied from the WinUI control gallery sample:

```
<TeachingTip x:Name="ToggleThemeTeachingTip2"                 
	    Title="Change themes without hassle"
	    Subtitle="It's easier than ever to see control samples in both light and dark theme!"
	    PreferredPlacement="Auto"                                              
	    PlacementMargin="20"
	    IsLightDismissEnabled="True"
	    ActionButtonClick="ToggleThemeTeachingTip2_ActionButtonClick"
	    ActionButtonContent="Toggle theme now"
	    CloseButtonContent="Got it!"/>
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
```
        
C++

```
   void MainWindow::myButton_Click(IInspectable const&, RoutedEventArgs const&)
    {
        myButton().Content(box_value(L"Clicked"));
        ToggleThemeTeachingTip2().IsOpen(true);
    }
```

### Expected behavior

The application should not crash and the TeachingTip control should appear.

### Screenshots

*Edit: Forgot to add symbols to VS, here is a better callstack*
![WinUI Error2](https://user-images.githubusercontent.com/8999998/143786584-b8e73e55-0496-4eb3-8d33-54dab7c64809.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by castorix** [comment]
> When running under a debugger calling IsOpen(true) on a TeachingTip seems to crash the application. Application runs fine when not under the debugger.

This is weird.
I tried to detach the debugger by code, but it still crashes (no crash in C# or packaged)

**Comment by FrancisKoo** [comment]
I also met this issue in C++ unpackaged. @StephenLPeters

**Comment by FrancisKoo** [comment]
An error C2039 occured  : "ProfileButton": is not a member of "winrt::App1::MainWindow"  when I write like below(C++ unpackaged)  @StephenLPeters 

```
<Button x:Name="ProfileButton" Width="40" Height="40"  Background="Orange"
                                Click="ProfileButton_Click"/>
<TextBlock Text="Trunks" HorizontalAlignment="Center"/>
<TeachingTip x:Name="UserInfoTeachingTip" Target="{x:Bind ProfileButton}" />
```

**Comment by StephenLPeters** [comment]
That looks like an x:bind issue.. @RealTommyKlein Thoughts?

**Comment by RealTommyKlein** [comment]
@StephenLPeters @FrancisKoo - to bind to an x:Name'd element in C++/WinRT, you also need to add a corresponding property in your IDL, see: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property#element-to-element-binding

That being said, we should raise an explicit Xaml compiler error when we detect that instead of our generated code failing to compile.

**Comment by FrancisKoo** [comment]
> @StephenLPeters @FrancisKoo - to bind to an x:Name'd element in C++/WinRT, you also need to add a corresponding property in your IDL, see: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property#element-to-element-binding
> 
> That being said, we should raise an explicit Xaml compiler error when we detect that instead of our generated code failing to compile.

@StephenLPeters @RealTommyKlein 
Thanks so much  for your reply. I add it in my IDL and build successful. But it still crash when I open the Teachingtip in C++ unpackaged app. It works good in C++ packaged app.

**Comment by xuepingSu** [comment]
I also met  the same issue ,it crash when calling IsOpen in C++ unpackaged app , but it just happen in debugger，if I click run the app , it is not crash, it can run.
windows 11 ,sdk 10.0.19041.0 ;  WindowsAppSDK 1.1.4 ;   Microsoft.UI.Xaml 2.8.1
here is callstack
![image](https://user-images.githubusercontent.com/23496159/185606834-085e9ba1-1b48-4e0e-95aa-86789d86ffd6.png)
![image](https://user-images.githubusercontent.com/23496159/185606933-7c898b6c-25fb-4d62-b2b0-ba27e8738457.png)
