### ISSUE TITLE
Cannot run Unpackaged C# Winui3 app

### ISSUE THREAD

**Issue by ScoPeZs** [microsoft/microsoft-ui-xaml#6395]
### Describe the bug

Cannot run Unpackaged c# app.

- NuGet package version: Windows App SDK 1.0.0 (stable)
- VisualStudio 2022. 17.0.1
- x64
- Win 11 22000.348

### Steps to reproduce the bug

Create "Blank App, Packaged (WinUI 3 in Desktop)" project.
Delete "Package.appxmanifest".
Add `<WindowsPackageType>None</WindowsPackageType>` to the property group in the project.
Try to debug.

### Screenshots

Here's a video showing what's happening to me.
https://imgur.com/hDJkpQi

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by AkiraVoid** [comment]
Why did you close this? Is there any solution?

**Comment by ojhad** [comment]
@AkiraVoid Are you having similar issues? Please open a separate issue with a min repro if that is the case.
