### ISSUE TITLE
MenuFlyoutItem height issue

### ISSUE THREAD

**Issue by Kanniyappan-P** [microsoft/microsoft-ui-xaml#6396]
### Describe the bug

I'm using a menu flyout item inside a dropdown button, and the menu flyout item height is updated to 40 when the flyout first opens. It is later updated to 32. 

Why item height has been changed at second time loading, it should be fixed right?

Any suggestion on this?

### Steps to reproduce the bug

1. Run the attached sample.
2. Click and open the dropdown.
3. Note Flyout item height updated as 40.
4. Again open the drop down and check flyout item height updated as 32.
5. [MenuFlyoutItemHeight_Issue (2).zip](https://github.com/microsoft/microsoft-ui-xaml/files/7615741/MenuFlyoutItemHeight_Issue.2.zip)

### Expected behavior

Different heights should not be used for flyout items, and they should all be the same.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
40 is the height that is supposed to be used for touch interactions. 32 is the height for mouse interactions. @Kanniyappan-P I assume you are opening the flyout with mouse both times?

**Comment by l619534951** [comment]
test the issue's demo in Windows App SDK 1.1.2

ActualHeight=40（only appears in first open, after that, the ActualHeight is 32.）
`item1.ActualHeight`

ActualHeight= 32（all the times）
`Task.Run(() =>  
    {  
        DispatcherQueue.TryEnqueue(() =>  
                {
                    Debug.WriteLine(item1.ActualHeight);
                });
            });`

@StephenLPeters

**Comment by krschau** [comment]
When looking at this bug, make sure to check out https://github.com/microsoft/microsoft-ui-xaml/issues/6396 and https://github.com/microsoft/microsoft-ui-xaml/issues/7374.

**Comment by ranjeshj** [comment]
This looks like a dup of https://github.com/microsoft/microsoft-ui-xaml/issues/7374. Let's track it as part of that issue.
