### ISSUE TITLE
GridView - Ability to apply the size of the largest item for all items

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#6398]
# Proposal: GridView - Ability to apply the size of the largest item for all items
Today GridView uses the size of the first item for all items however in most cases, users want the size of the largest item to be used for all items. While a custom panel can be used that has the behaviour, I think this is basic and should be built-in to WinUI. Some people use controls such as [WrapPanel](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wrappanel) from the .NET Community Toolkit however such controls are designed for non-uniform layouts, not for uniform layouts with the same size for every control and aren't virtualized

## Summary
Add a property to built-in Panel subclasses that can be used with GridView such as ItemsWrapGrid to use the desired size of the largest element instead of the first element.

## Rationale
* Basic things must be built-in.

## Scope
| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to apply the size of the largest element for all elements in a GridView | Must |

**Comment by JohnnyWestlake** [comment]
Very difficult to do for a virtualised control given you don't know what the largest item is because it might not have been realised. That's why first item was chosen, because there's no sane way of knowing what the largest possible size could be.

**Comment by Jaiganeshkumaran** [comment]
> Very difficult to do for a virtualised control given you don't know what the largest item is because it might not have been realised. That's why first item was chosen, because there's no sane way of knowing what the largest possible size could be that covers all scenarios.
> 
> If the application developer does themselves know a way of figuring this out for their particular usecase, they can use ItemsWrapGrid.ItemHeight/ItemWidth

I understand however what if I don't know the item size? For example, user-generated data. Also its not responsive out of the box for all screen sizes.

**Comment by michael-hawker** [comment]
> I understand however what if I don't know the item size? For example, user-generated data. Also its not responsive out of the box for all screen sizes.

If you don't know how to get the largest item size from your collection, how do you expect the platform to magically figure it out for you? Either you have all your items ahead of time and can figure out like Johnny suggested the size you want to use for your items, or you'd have to adapt things on the fly based on the incoming data.

Are you saying that you want everything to re-adjust its size if a larger item comes in later? As that's a slightly different behavior, but also seems like it could be jarring for everything to suddenly change when scrolling in a list...

**Comment by StephenLPeters** [comment]
@MarissaMatt as FYI but I've close declined this feature proposal as I don't think it works the the virtualized nature of our list controls.
