### ISSUE TITLE
ListViewItem Background property customization is not working properly at run-time in ListView control

### ISSUE THREAD

**Issue by SubashiniMahendran** [microsoft/microsoft-ui-xaml#6399]
### Describe the bug

ListViewItem Background property customization is not working properly in ListView control.

I have custom control with a selection area TextBox and popup with ListView. 
When pressing up and down arrow key in TextBox I need to highlight the next and previous item based on arrow key press. And I have achieved this requirement by using ListViewItem Background property.

It works fine in ProjectReunion 0.8.1 release. After upgrading to Windows SDK 1.0. It does not works. Please find the working and non-working samples below:

**Working sample in ProjectReunion 0.8.1:**
[ListView-Reunion.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7617970/ListView-Reunion.zip)

**Not working sample in Windows SDK 1.0:**
[ListView-Windows-SDK.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7617966/ListView-Windows-SDK.zip)

### Steps to reproduce the bug

Case 1:

1. Run the working sample.
2. Focus the control.
3. Now, press down key to open popup.
4. Then press down key. Note it will highlight the next item on every key press.

Case 2:

1. Now, run the non working sample.
2. Focus the control.
3. Now, press down key to open popup.
4. Then press down key. Note it will not highlight the next item on every key press.
5. Note, if I customize BorderBrush it works fine.

### Expected behavior

ListViewItem Background property customization should not works properly when changing at run-time in ListView control with Windows SDK 1.0

### Screenshots

**ListViewItem Background customization in Project reunion 0.8.1[Working]**
![image](https://user-images.githubusercontent.com/92976485/143863677-ba9833fa-edd4-4feb-9e1c-27db296b7325.png)

**ListViewItem Background customization in Windows SDK 1.0[Not Working]**
![image](https://user-images.githubusercontent.com/92976485/143863880-7ad1b8d9-710f-4e13-9eb9-a6a7225d1696.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
@RBrid FYI
