### ISSUE TITLE
Using Win2D breaks publishing unpackaged app as single file

### ISSUE THREAD

**Issue by DHancock** [microsoft/microsoft-ui-xaml#6400]
### Describe the bug

The application contains a user control that draws itself using composition drawing which requires the Win2D nuget package. When either the debug or release target is published with _PublishSingleFile_ set to true, the previously working application stops with a fail fast exception after opening the main window but before any controls are loaded.

### Steps to reproduce the bug

1. Open the solution attached below.
2. Publish the x64 profile using the debug build configuration.
3. Confirm the exe runs ok.
4. Edit the x64 publishing profile setting _PublishSingleFile_ to true.
5. Publish the app again.
6. Run the exe.

[SingleFileIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7618226/SingleFileIssue.zip)

### Expected behavior

It should work.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

If I start the published single file using Visual Studio, the output window shows quite a few exception messages. It's difficult to know if these are benign, apart from the last two:

```
Exception thrown at 0x00007FFB76E44F69 (KernelBase.dll) in SingleFileIssue.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131604, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFACE450000).
Exception thrown at 0x00007FFB76E44F69 (KernelBase.dll) in SingleFileIssue.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131604, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFACE450000).
Exception thrown at 0x00007FFB76E44F69 (KernelBase.dll) in SingleFileIssue.exe: WinRT originate error - 0x80131604 : 'Exception has been thrown by the target of an invocation.'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFB775BC363: (caller: 00007FFB775C6049) ReturnHr(1) tid(2bc0) 8007007E The specified module could not be found.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFB775BC363: (caller: 00007FFB7773D6A7) ReturnHr(2) tid(2bc0) 8007007E The specified module could not be found.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFB775BC363: (caller: 00007FFB7773D113) ReturnHr(3) tid(2bc0) 8007007E The specified module could not be found.
Unhandled exception at 0x00007FFB76F1B302 (KernelBase.dll) in SingleFileIssue.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x00000165D2E5E4B0, 0x0000000000000002).

Unhandled exception at 0x00007FFB76F1B302 (KernelBase.dll) in SingleFileIssue.exe: 0xC0000602:  A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately.
```

**Comment by DHancock** [comment]
You will find a ```Microsoft.Graphics.Canvas.dll``` is suspiciously loitering in the publishing folder. It's the Win2D dll. If I remove all the Win2D code from the repro solution, publish as single file works.

(I'd be surprised if this isn't a known issue)

**Comment by StephenLPeters** [comment]
@codendone FYI

**Comment by DHancock** [comment]
Retested with current latest packages:

Windows App SDK 1.1.0-preview3 
Microsoft.Graphics.Win2D 1.0.3.1 

Still fails with same problem.

**Comment by appindus-ibiller** [comment]
It seems like anything with Win2D refs are breaking if not being deployed to official channels. Still happening with Windows App SDK 1.1.1 stable. We're supposed to be able to make unpackaged apps but despite the November 2021 release being over 6 months ago, official Microsoft packages are still not supporting it. Pretty unreal.
