### ISSUE TITLE
WinUI build fails when *.xaml files are included in the project

### ISSUE THREAD

**Issue by MaddalaN** [microsoft/microsoft-ui-xaml#6403]
### Describe the bug

WinUI3 project fails to build on jenkins when xaml files are included.

### Steps to reproduce the bug

I have a simple WinUI3 project, here is the project structure (sorry, please disregard the format):

`
Project Sdk="Microsoft.NET.Sdk"
	PropertyGroup
		TargetFrameworknet6.0-windows10.0.19041.0/TargetFramework
		TargetPlatformMinVersion10.0.17763.0/TargetPlatformMinVersion
		RootNamespaceControls/RootNamespace
		RuntimeIdentifierswin10-x86;win10-x64;win10-arm64/RuntimeIdentifiers
		TreatWarningsAsErrorstrue/TreatWarningsAsErrors
		UseWinUItrue/UseWinUI
		SignAssemblyTrue/SignAssembly
		EnablePreviewMsixToolingtrue/EnablePreviewMsixTooling		
	/PropertyGroup
  ItemGroup
      PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" /
      PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.196" /
  /ItemGroup

  ItemGroup
    Page Update="UserControl1.xaml"
      "GeneratorMSBuild:Compile"/Generator
    Page
  /ItemGroup

  ItemGroup
    Page Update="ResourceDictionary1.xaml"
      "GeneratorMSBuild:Compile"/Generator
    /Page
  /ItemGroup
/Project
 `

The Code compiles fine on my local machine using msbuild command line. However it fails on the jenkins with the below error -

C:\Users\ContainerAdministrator\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(255,7): error MSB4018: The "GetLatestMSVCVersion" task failed unexpectedly. [C:\jnlp\workspace\UX_-_WinUI_sampleUI-test-branch1\src\DCF.UXControls\DCF.UXControls.csproj]
13:06:57  C:\Users\ContainerAdministrator\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(255,7): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC'. [C:\jnlp\workspace\UX_-_WinUI_sampleUI-test-branch1\src\DCF.UXControls\DCF.UXControls.csproj]

Note: 
1. Jenkins uses the dotnet 6 docker image and has both dotnet and uwp workloads installed.
2. Jenkins build passes fine when xaml files are not included.

Am I missing anything or please let me know what is required to fix the error reported by the target.

### Expected behavior

The build should pass when xaml files are included in the project.

### NuGet package version

1.0.0

### Packaging type

Unpackaged

### IDE

Visual Studio 2022

### Additional context

Version Info:
dotnet net6.0-windows10.0.19041.0

Nuget package version:
Microsoft.WindowsAppSDK, version - 1.0.0
Microsoft.Windows.SDK.BuildTools, version - 10.0.22000.196

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI

**Comment by tajbender** [comment]
I had the same issue today.
Newest stable vs, appsdk

**Comment by julianadormon** [comment]
Same issue after downloading latest VS. 
Trying to build a Windows app in a .Net Maui Blazor app.

Error | MSB4018 | The "GetLatestMSVCVersion" task failed unexpectedly.System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.FileSystemEnumerableIterator`1.CommonInit()   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)   at System.IO.Directory.EnumerateDirectories(String path)   at InlineCode.GetLatestMSVCVersion.Execute()   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() | SortedDesktop | C:\Users\macminim1\.nuget\packages\microsoft.windowsappsdk\1.2.221109.1\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets | 268 |  

![image](https://user-images.githubusercontent.com/89358714/208269980-6eb65880-ddc4-42be-9739-0fd003bff23e.png)

**Comment by Scottj1s** [comment]
I was able to repro with a bare VS 2022 Community installation (no workloads), and to resolve by installing the "Desktop development with C++" workload.  The usual way to automate installation of necessary workloads and components is via a [.vsconfig file](https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/).  I'm not familiar with Jenkins, but some build agents support a capability/demand system to ensure you have all prereqs installed.  Or you can automate via something like "vs_buildtools.exe --add Microsoft.VisualStudio.Workload.MSBuildTools --quiet --config .vsconfig --wait".  Note: a nuget restore does not modify the Microsoft.UI.Xaml.Markup.Compiler.interop.targets contents.

**Comment by schemburkar** [comment]
Hit this today, installing VS on new machine. Resolved by installing MSVC individual component
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/3159347/d6a94794-fbc6-4302-8d66-7222bf8ee113)

**Comment by jecdx** [comment]
This issue still occurs:
> MSB4018	The "GetLatestMSVCVersion" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC'.

And this GH issue is what comes up in online search results.

[Fix by](https://github.com/microsoft/microsoft-ui-xaml/issues/6403#issuecomment-2133843407) @schemburkar worked for me.

I'm using Visual Studio 2022 Professional v17.13.6
On [maui-samples](https://github.com/dotnet/maui-samples/tree/08e586f330c57c4f41c4a442371c600fa91704a5)/9.0/UserInterface/ControlGallery/ControlGallery.sln

**Comment by peereflits** [comment]
As of today, I have the same issue.
[The fix](https://github.com/microsoft/microsoft-ui-xaml/issues/6403#issuecomment-2133843407) provided by @schemburkar worked for me.

I'm using Visual Studio 2022 Community and Enterprise v17.13.6, so I had to install it twice.
