### ISSUE TITLE
VS shows "Design with Blend" even though you can't use Blend in WinUI 3

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6405]
### Describe the bug

In VS, we still show the "Design with Blend" option when right clicking a XAML file, but you can't actually use Blend to do anything useful in WinUI 3. Recommend removing the option for WinUI3 (should be kept for system XAML).

### Steps to reproduce the bug

right click a xaml file

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI
