### ISSUE TITLE
Setting app icon and title is unreasonably complicated in WinAppSDK

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6406]
There are a number of reports of this sprinkled across this and the appsdk repo but filing this to track getting a resolution.
Today if you want to set the app icon and title, there are a few problems:
1) Window.Title doesn't work from markup (you get a build failure that is not useful). This should be fixed.
2) Setting the icon requires using the under-documented `IWindowNative` API and then dipping down to window messages

Instead, Window should have an Icon property; maybe multiple ones:
- TaskbarIcon
- StartIcon
- TitleBarIcon

**Comment by asklar** [comment]
In the meantime, the docs for IWindowNative have been updated with C++ and C# samples.

**Comment by sylveon** [comment]
Start icon is something you set in the app package (if packaged) or start menu shortcut file (typically via an installer framework), not XAML

**Comment by bpulliam** [comment]
Duplicate of #5773
