### ISSUE TITLE
WinUI 3 should support Mica material

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6407]
It's in the roadmap as post 1.0 but I couldn't find one definitive issue where we track supporting it, so filing this one.
See related discussion here: https://github.com/microsoft/microsoft-ui-xaml/issues/5265#issuecomment-868162198

**Comment by WelterDevelopment** [comment]
It is so frustrating that Microsoft is telling the developer to use WinAppSDK at the developer landing page (developer.microsoft.com/de-de/windows/windows-for-developers/) and at the same time is not making it absolutely clear in the documentation (docs.microsoft.com/en-us/windows/apps/design/style/mica) that this and certain other features are UWP-only.

**Comment by sps014** [comment]
Seriously state of Windows App Development is really bad, 
UWP being sandboxed, pathetic app lifetime management, 
WPF not getting  feature updates (outdated controls), 
WinUI even does not support Mica, or have Windows Background brush.

**Comment by jasmeet21** [comment]
> Seriously state of Windows App Development is really bad, UWP being sandboxed, pathetic app lifetime management, WPF not getting feature updates (outdated controls), WinUI even does not support Mica, or have Windows Background brush.

I completely agree with this. WinUI 3 is in pathetic state, no basic controls (e.g Table) in v1.0 release. Wanted to switch to WinUI but i gave up, still sticking with WPF for time being.

Check out this repo, WPF running with Mica/Background brush.
https://github.com/lepoco/wpfui

**Comment by sps014** [comment]
Actually wpfui doesn't have all the controls like Slider

**Comment by dongle-the-gadget** [comment]
Should be resolved in 1.1 Preview 3?

**Comment by X1nto** [comment]
Mica Backdrop APIs are now available for WinUI 3: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop?view=windows-app-sdk-1.3

**Comment by sotanakamura** [comment]
> Mica Backdrop APIs are now available for WinUI 3 with WinAppSDK 1.3: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.micabackdrop?view=windows-app-sdk-1.3
Excellent!! This issue is resolved!

**Comment by JJBrychell** [comment]
Mica support is currently available in 1.3,
