### ISSUE TITLE
WinUI 3 should include a DataGrid or TableView control

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6408]
This is a topic that comes up pretty much every community call : )
There is a need for a platform-provided table / datagrid control. The existing WCT one is not sufficient or appropriate since that is realistically only consumable by .NET apps. C++ apps are not able to consume it, or unwilling to pay the perf hit of loading a whole CLR just for one control. See CommunityToolkit/WindowsCommunityToolkit#4391 and many other issues filed here.
The platform should include this control rather than rely on developers to roll their own.

**Comment by michael-hawker** [comment]
Duplicate of #1500

**Comment by asklar** [comment]
@michael-hawker please don't close. Thanks :)

**Comment by michael-hawker** [comment]
@asklar @StephenLPeters @RBrid there's already an issue tracking this, why do we need to keep this one open as a duplicate?
