### ISSUE TITLE
[SDK] XAML Compiler emits duplicate definitions

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6413]
XAML Compiler emits code in xamltypeinfo.g.cpp that has duplicate definitions, if e.g. two Pages define an element with the same name (this seems fixed in WinAppSDK).

Repro is: Have two runtimeclasses in IDL, that have a property with the same name, and are used from `x:Bind` in XAML.

**Comment by RealTommyKlein** [comment]
Is this a dupe of #5395?

**Comment by asklar** [comment]
Yeah this looks like the same issue. Is this something we can fix in the inbox SDK, it push into the build tools nuget?



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by bpulliam** [comment]
Closing since #5395 was fixed.
