### ISSUE TITLE
Acrylic doesn't quite work in system XAML islands

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6414]
The backdrop brush only gets applied once you tab away and back into the app. Calling ActivateWindow (away from the app and back) like Miguel suggested doesn't seem to do anything.

See related discussion CommunityToolkit/Microsoft.Toolkit.Win32#170

**Comment by sylveon** [comment]
The linked issue mentions focus. In my code I set the focus to the interop window upon the top-level window being activated, and acrylic works as expected. Does this solve the issue for you?

E.x.:

```cpp
case WM_SETFOCUS:
	SetFocus(m_interopWnd);
	return 0;
```
