### ISSUE TITLE
Question: Behaviors in styles WinUI.

### ISSUE THREAD

**Issue by valvasiliev** [microsoft/microsoft-ui-xaml#6418]
### Describe the bug

```
    <Style x:Key="BaseButtonStyle" TargetType="Button">
        <Setter Property="i:Interaction.Behaviors">
            <Setter.Value>
                <i:BehaviorCollection>
                    <behaviors:SomeButtonBehavior/>
                </i:BehaviorCollection>
            </Setter.Value>
        </Setter>
    </Style>
    <Style x:Key="B1ButtonStyle" TargetType="Button" BasedOn="{StaticResource BaseButtonStyle}"/>
    <Style x:Key="B2ButtonStyle" TargetType="Button" BasedOn="{StaticResource BaseButtonStyle}"/>
    <Style x:Key="B3ButtonStyle" TargetType="Button" BasedOn="{StaticResource BaseButtonStyle}"/>
```

SomeButtonBehavior.OnAttached() Calls only once for first created button.

How to call OnAttached for each instance of button?

**Comment by valvasiliev** [comment]
@gabbybilka Could You push someone in MS? ) It is not last bug with attached props.

**Comment by JohnnyWestlake** [comment]
This is working as intended... you're creating a single instance of a behaviour in the style, and that single instance is being attached to the first thing that tries to load the style. The style might be applied again many times after but it doesn't matter, your single instance BehaviourCollection has already been attached.

**Comment by valvasiliev** [comment]
@JohnnyWestlake Looks like You right. Does WinUI has some kind x:Shated = "false" property for such case?

**Comment by valvasiliev** [comment]
https://stackoverflow.com/questions/1647815/how-to-add-a-blend-behavior-in-a-style-setter
