### ISSUE TITLE
[WinUI] Border not rendering properly if we set corner radius for particular edges

### ISSUE THREAD

**Issue by VigneshRameshh** [microsoft/microsoft-ui-xaml#6419]
### Describe the bug

Border not rendering properly if we set corner radius for particular edges

### Steps to reproduce the bug

1. Run the attached sample [WindowAppSDKUpgrade.zip](https://github.com/microsoft/WindowsAppSDK/files/7627034/WindowAppSDKUpgrade.zip)
2. Check the bord

### Expected behavior

The border should render properly, even if we set a corner radius for particular edges.

### Screenshots

![image](https://user-images.githubusercontent.com/43605205/144081109-c504094d-2525-4a02-af8c-8cddf88800c3.png)

### NuGet package version

1.0.0

### Windows version

October 2020 Update (19042)

### IDE

Visual Studio 2022-preview

**Comment by kmgallahan** [comment]
Dupe of #6194
