### ISSUE TITLE
[CoreWindow] - Minimizing a fullscreen Window doesn't correctly return focus to previous window

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#6428]
### Describe the bug

This (small) bug was reported by a user of my app and I can confirm it. Normally when you minimize a window it returns focus to the previously focused window. This is particularly useful when using a keyboard to control the device. For example, when opening a photo in a photo viewing app from File Explorer, then minimizing it and continuing to browse File Explorer. However, when you minimize a fullscreen Window (with a CoreWindow-based UWP app), it does not correctly return the focus to the previously focused window. Interestingly, closing the window does return the focus, and also existing fullscreen then minimizing does return the focus.

### Steps to reproduce the bug

Create a UWP app (using the system XAML) which has an enter fullscreen button. Ideally add a file associaton so the app can be lauchced from FIle Explorer. Launch the app from File Explorer, enter fullscreen, then minimize it (either using the mouse or WinKey + Down). Note that File Explorer is not focused.

### Expected behavior

The previously focused window should be focused when minimizing a fullscreen window (which does happen when minimizing a non-fullscreen window).

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@MikeHillberg FYI
