### ISSUE TITLE
TeachingTip tests fail in Helix

### ISSUE THREAD

**Issue by llongley** [microsoft/microsoft-ui-xaml#643]
I found out while working on #642 that TeachingTip tests currently aren't being run in Helix, and it looks like they're all failing on at least some run.  See for example this test run:

https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=13416&_a=summary&view=ms.vss-test-web.build-test-results-tab

I'll disable them for now, but they should be re-enabled once they're passing.

**Comment by jevansaks** [comment]
@StephenLPeters can you take a look? We'd want this fixed before we bring in any other TeachingTip code changes.
