### ISSUE TITLE
NavigationView.SettingsItem.Tag is wrongly localized

### ISSUE THREAD

**Issue by hayashida-katsutoshi** [microsoft/microsoft-ui-xaml#6438]
### Describe the bug

`NavigationView` sets `SettingsItem` automatically and it sets `Settings` to `Tag` property. While `Content` is used for display, `Tag` is used for internal use. However `Tag` is localized when OS has configured to non English language, and an application program cannot count `Tag` field. To work around, application has to set the Tag manually to `Settings` like this.

``` cs
        public void NavigationView_Loaded(object sender, RoutedEventArgs e)
        {
            var navigationView = sender as NavigationView;
            var settings = navigationView.SettingsItem as NavigationViewItem;
            settings.Tag = "Settings";
        }
```

### Steps to reproduce the bug

1. Create a WinUI project.
2. Put NavigationView to MainWindow.xaml
3. Add `SelectionChanged="NavigationView_SelectionChanged"` to the NavigationView.
4. Add `NavigationView_SelectionChanged` to MainView class.
``` cs
public void NavigationView_SelectionChanged(NavigationView sender, NavigationViewSelectionChangedEventArgs args)
{
    var selectedItem = args.SelectedItem as Microsoft.UI.Xaml.Controls.NavigationViewItem;
    contentFrame.Navigate(Type.GetType($"Sample.{selectedItem.Tag}"));
}
```
5. Create Settings.xaml
6. Verify that the Settings icon on the Navigation can open Settings.xaml.
7. Change the language setting on the OS to non English.
8. Find that the Settings icon crashes.

### Expected behavior

Default value of `NavigationView.SettingsItem.Tag` is `Settings` in any languages.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] UWP
- [X] Win32

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
Yeah, its pretty strange that the tag on this item is being set at all, but looking through the history it makes sense. Some people use the tag property to navigate in a MVVM friendly way and including the tag on the settings item enables the settings item to participate in that model.  Definitely shouldn't be localized though, this line needs to change: https://github.com/microsoft/microsoft-ui-xaml/blob/6966e161f4abeebd566a8db47a4d2717a89fddca/dev/NavigationView/NavigationView.cpp#L1320

**Comment by chingucoding** [comment]
Taking a look at this.
