### ISSUE TITLE
AutoSuggestBox Query button moves to the left

### ISSUE THREAD

**Issue by hassaanmasood** [microsoft/microsoft-ui-xaml#6439]
### Describe the bug

AutoSuggestBox Query Button slides to the left when width is not defined on the AutoSuggestBox and it has a Placeholder which is bigger than 6-7 Characters. 

**Please provide a fix, through styles, in the comments if possible.**

### Steps to reproduce the bug

1. Create a new WinUI 3 in Desktop App.
2. Place an AutoSuggestBox Control with no width or margins defined so that it expands to the width of the application.
3. Set a Placeholder bigger than 7 characters on the AutoSuggestBox.
4. Set QueryIcon for the Query Button of AutoSuggestBox
5. Run the app in Debugging mode and keep increasing the length of placeholder text while in debug mode. 

Now note the movement of querybutton, as we increase characters in placeholder text the icon button keeps moving to left.

### Expected behavior

Query Button on the AutoSuggestBox should always align to right side, no matter how long the placeholder is.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@hassaanmasood is this the Winui3 version of this issue? https://github.com/microsoft/microsoft-ui-xaml/issues/5537

**Comment by hassaanmasood** [comment]
@StephenLPeters Yes, it is
