### ISSUE TITLE
ColorSpecturm not displayed in ContentDialog control while it loaded from UserControl or CustomControl.

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#6440]
### Describe the bug

After WindowAppSDK 1.0.0 update, ColorSpectrum control not displayed properly inside the `ContentDialog` control while it  loaded from UserControl or CustomControl. Please consider this as a higher priority and check &  fix this issue as soon as possible.

### Steps to reproduce the bug

1. Run the [ColorSpectrum_ContentDialog.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7660160/ColorSpectrum_ContentDialog.zip) sample.
2. Click the `ShowDialog` option.
3. Note: ColorSpectrum control not displayed in ContentDialog.

### Expected behavior

ColorSpecturum should be displayed properly inside the ContentDialog

### Screenshots

Current output: (Issue)

![image](https://user-images.githubusercontent.com/57438309/144834100-a7b2c537-cd29-414e-b8f0-aa0f7ad207dc.png)

Expected output:

![image](https://user-images.githubusercontent.com/57438309/144834374-ba26ff62-1d8c-4a67-915a-d89a04616285.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
@gegao18 looks like a rendering issue, FYI
