### ISSUE TITLE
NavigationView Menu Pane transparent when hosted in Window

### ISSUE THREAD

**Issue by tuggernuts** [microsoft/microsoft-ui-xaml#6441]
### Describe the bug

When I host a NavigationView directly in a Window, there is no "solid grey color" background in the menu pane (left) as mentioned in documentation and seen in demos. 

### Steps to reproduce the bug

1. Visual Studio 2022 with appropriate VSIX extensions
2. New Blank App, Packaged (WinUI 3 in Desktop)
3. Add  NavigationView to a window as a child of Window. Also happens when a child of another control, e.g. Grid.
4. Build and should see something similar to attached screenshot.

### Expected behavior

I would expect that the menu pane would have the default background color.

### Screenshots

![NavigationView](https://user-images.githubusercontent.com/36776999/144928637-8ac69f4b-f906-4069-ae15-711fc3033087.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Targeting .net 6.0, OS 19041, MinOS 17763

**Comment by kmgallahan** [comment]
Looks as per the latest WinUI 3 styles.

![Screenshot 2021-12-06 181056](https://user-images.githubusercontent.com/5379488/144937489-d9eaceaa-04fc-454a-b3c2-9ce58e8eadb4.jpg)

![Screenshot 2021-12-06 180958](https://user-images.githubusercontent.com/5379488/144937497-eb81c305-25bd-42e4-ac14-bf2a46d7bb79.jpg)

**Comment by tuggernuts** [comment]
Wild. This must have changed in the last couple of days? I just now opened the gallery and it was updated to what you show. I literally updated the gallery last week. This is all such a moving target...

For anyone who wants to add some color to the menu pane, add the NavigationView to a grid, and:

`<Grid.Resources>
            <AcrylicBrush x:Key="NavigationViewExpandedPaneBackground" 
                          TintColor="{StaticResource SystemChromeMediumLowColor}"
                          TintOpacity=".9"
                          FallbackColor="{StaticResource SystemChromeMediumLowColor}" />
        </Grid.Resources>`

**Comment by kmgallahan** [comment]
The gallery as hosted in the Microsoft Store runs on WinUI 2, whereas you are using WinUI 3. The newer styles took longer to arrive for the later, although I can't remember the exact timeline.
