### ISSUE TITLE
Microsoft.DataSqlite Version 6.0.0

### ISSUE THREAD

**Issue by Fernand-Delavy** [microsoft/microsoft-ui-xaml#6443]
### Describe the bug

PC Windows Pro 10.19044.1387
Visual Studio 2022 Version 17.0.2

Microsoft.DataSqlite Version 6.0.0 crash on open database here :
using (SqliteConnection comptaDB = new SqliteConnection("Filename = " + localFolder.Path + @"\" + nomFichier))
See Error.jpg
![Error](https://user-images.githubusercontent.com/43344217/145037943-cebf9747-0e78-4829-9847-4e4c8359b0a5.jpg)

But app is working with Microsoft.DataSqlite Version 5.0.12 !!
What is the problem ?

### Steps to reproduce the bug

N/A

### Expected behavior

Microsoft.DataSqlite working

### Screenshots

N/A

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043), May 2020 Update (19041)

**Comment by kmgallahan** [comment]
6 has a dependency on .NET 6, 5 does not. WinUI 2 will never work with .NET 5/6 because UWP XAML / .NET Native [have been deprecated](https://github.com/microsoft/WindowsAppSDK/discussions/1615).

![Screenshot 2021-12-07 103914](https://user-images.githubusercontent.com/5379488/145060420-a0ae82c8-e029-4c9c-911d-86727fbc79d9.jpg)

**Comment by Panda-Sharp** [comment]
> 6 has a dependency on .NET 6, 5 does not. WinUI 2 will never work with .NET 5/6 because UWP XAML & .NET Native [have been deprecated](https://github.com/microsoft/WindowsAppSDK/discussions/1615).
> 
> ![Screenshot 2021-12-07 103914](https://user-images.githubusercontent.com/5379488/145060420-a0ae82c8-e029-4c9c-911d-86727fbc79d9.jpg)
> 
> ![Screenshot 2021-12-07 104621](https://user-images.githubusercontent.com/5379488/145060892-8221d354-0bf6-4950-95a4-d2934e787fea.jpg)

I'm quite sure that means it can ran on .net standard 2.0 AND on .net 6 let's take the Microsoft Toolkit for comparison
https://www.nuget.org/packages/Microsoft.Toolkit/

it runs on:

- .NETStandard 1.4
- .NETStandard 2.0
- .NETStandard 2.1
- net5.0

**Comment by kmgallahan** [comment]
Hmmm I had wrongly assumed this was a part of EF Core 6. 

SQLitePCLRaw has caused problems with UWP \ .NET Native before due to way it is packaged. If I had to guess the problem lies there, rather than having anything to do with WinUI.

https://github.com/ericsink/SQLitePCL.raw
