### ISSUE TITLE
BitmapImage.SetSource from MemoryStream of byte[] issue?

### ISSUE THREAD

**Issue by theznerd** [microsoft/microsoft-ui-xaml#6444]
# Discussion: BitmapImage.SetSource from MemoryStream of byte[] issue?
I'll be frank - I'm an intermediate C# developer and am just starting to play with WinUI. If I have an image stored in a blob column in a database, my understanding is that I could use a ValueConverter to take those bytes and convert them to a BitmapImage to use as the source in an image control ala:
```
public object? Convert(object value, Type targetType, object parameter, string language)
{
    if (value is null)
        return null;

    byte[] imageData = (byte[])value;
    BitmapImage bi = new BitmapImage();
    MemoryStream ms = new MemoryStream();
    ms.Write(imageData, 0, imageData.Length);
    bi.SetSource(ms.AsRandomAccessStream());
    return bi;
}
```
However, when I do this, the BitmapImage has PixelHeight/PixelWidth values of 0. It appears that the BitmapImage isn't processing the stream, but the stream is a valid byte array of all file bytes.

![image](https://user-images.githubusercontent.com/12768931/145102061-fc9bbfc5-6aea-4fb8-a5c0-7821b86f1984.png)

The end result is that the Image control on the page doesn't show anything. Maybe something I'm overlooking, but given how new WinUI is, there doesn't seem to be anyone documenting similar issues. Hoping someone here can assist.

**Comment by HavenDV** [comment]
```cs
using Microsoft.UI.Xaml.Media.Imaging;

#nullable enable

namespace Converters;

public class BytesToBitmapImageConverter : BaseConverter<byte[], ImageSource?>
{
    public static ImageSource? Convert(byte[] value)
    {
        value = value ?? throw new ArgumentNullException(nameof(value));

        if (!value.Any())
        {
            return null;
        }

        using var stream = new MemoryStream();
        stream.Write(value, 0, value.Length);
        stream.Seek(0, SeekOrigin.Begin);

        var image = new BitmapImage();
        image.SetSource(stream.AsRandomAccessStream());

        return image;
    }

    public BytesToBitmapImageConverter()
        : base(Convert)
    {
    }
}
```

**Comment by theznerd** [comment]
Gah, that was it - the missing Seek() method... many thanks!
