### ISSUE TITLE
ListBox design is not updated to match Win11 style

### ISSUE THREAD

**Issue by hassaanmasood** [microsoft/microsoft-ui-xaml#6447]
### Describe the bug

ListBox design is not updated to match the Windows11 style components as well as the style of other item like ListView, ComboBox

### Steps to reproduce the bug

Check XAML Controls Gallery App on Windows 11.

OR

1. Create a new WinUI 3 in desktop App.
2. Place ListBox Control inside MainWindow.
3. Add few ListBoxItems to the ListBox.
4. Run the App

### Expected behavior

ListBox style should match the style of other controls in this library such as with rounded corners on both ListBox itself and items inside. 

### Screenshots

Current Design
![actualdesign](https://user-images.githubusercontent.com/58418307/145273680-8bd8eb9d-6449-4e93-9fec-fb1ee9808a19.png)

Expected Design
![expected design](https://user-images.githubusercontent.com/58418307/145273687-51d391e2-4217-4dd6-a5e2-6b2272513fae.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@chigy FYI

ListBox is a pretty old control, we recommend people use ListView instead.  Updating ListBox style is a relatively expensive endeavor which I think was deprioritized in favor of other work.

**Comment by Fefedu973** [comment]
Bump

**Comment by ghost1372** [comment]
> ListBox is a legacy control no longer recommended for new apps in favor of ListView, ComboBox, or RadioButton/CheckBox groupings depending on the scenario.

https://github.com/microsoft/WinUI-Gallery/pull/2180
