### ISSUE TITLE
Question: How to localize AssemblyTitle in Unpackaged Applications

### ISSUE THREAD

**Issue by Daniellled** [microsoft/microsoft-ui-xaml#6449]
I have an unpackaged application and I was wondering how to localize the AssemblyTitle within the application. I see in a UWP Packaged Application you could modify the manifest. https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest But I see no such options for an unpackaged application.

In SysInternals Process Explorer I am trying to localize the Description.

![image](https://user-images.githubusercontent.com/83433189/145307881-a234bf48-427a-40e4-85c7-4c14c6a9f165.png)

Likewise in the Task Manager

![image](https://user-images.githubusercontent.com/83433189/145307950-33b882a2-f79c-4d09-951c-f602f2d11bf3.png)

Does anyone have an guidance on this?

**Comment by StephenLPeters** [comment]
@MikeHillberg @codendone or @bpulliam how is this supposed to be done in winui3 unpackaged?

**Comment by Jeaninezz** [comment]
Based on this doc: [Localize your WinUI 3 app](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/localize-winui3-app)

To support multiple languages in a WinUI desktop app, and ensure proper localization of your packaged project, add the appropriate resources to the project (see App resources and the Resource Management System) and declare each supported language in the package.appxmanifest file of your project.

As an unpackaged WinUI 3 app (see Create your first WinUI 3 project) doesn't contain a package.appxmanifest file, no further action is needed after adding the appropriate resources to the project.

Besides, based on this issue: [Support PrimaryLanguageOverride from unpackaged apps](https://github.com/microsoft/WindowsAppSDK/issues/1687), currently there is no api that you can use to localize AssemblyTitle in unpackaged WinUI 3 app.

**Comment by duncanmacmichael** [comment]
Closing this question as it appears to have been answered as best it could, and any remaining outstanding questions can be directed to the bug linked above (1687).
