### ISSUE TITLE
WebView2 got exception in winUI3

### ISSUE THREAD

**Issue by sallyc3** [microsoft/microsoft-ui-xaml#6451]
### Describe the bug

We are converting our UWP application to WinUI3.  WebView2 control in xaml does not work in WinUI3.  It works in UWP app.
I followed following link to add the webView2 in xaml.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui#step-2---add-a-webview2-control-to-your-project

The reproduceable code is in https://github.com/sallyc3/IssueWebView2
In Xaml, there is a Grid with single WebView2 control, source = "https://www.microsoft.com"

-Sally

### Steps to reproduce the bug

Build and  run IssueWebView2.
You'll see the exception.

### Expected behavior

Web page showing with www.microsoft.com

### Screenshots

Exception thrown : 
![image](https://user-images.githubusercontent.com/77635845/145348659-9816c367-5db7-4f78-b3dd-a244cd25b981.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by sallyc3** [comment]
Any input on this yet?

**Comment by asklar** [comment]
the issue seems to stem from the fact that your project has `<AppContainerApplication>true</AppContainerApplication>`
setting this to `false` (which is the default in the template) and rebuilding the project, makes the app function correctly.

**Comment by sallyc3** [comment]
<AppContainerApplication>false</AppContainerApplication> in project file, webView2 works now.

But I used the "Blank App, Packaged (WinUI 3 in Desktop)" template. The project sets the above statement to true by default.  I did not change anything.  Should this template set the statement to false?

Now I'll need to test our complete winUI3 app with this new setting to see if everything is ok.

**Comment by sallyc3** [comment]
What's the impact on the function of the WinUI3 application when changed the AppContainer from True to False?  Our app connects to cloud server for file i/o.

**Comment by StephenLPeters** [comment]
@krschau FYI.  @asklar do you know the answer to Sallyc3's question?

**Comment by asklar** [comment]
WinUI3 does not support UWP apps in stable (which loosely translates to corewindow + appcontainer support); If you created the project with an old version of WinUI 3 (the UWP template) then it won't work going forward. You can read more about appcontainer here:
- https://docs.microsoft.com/en-us/cpp/build/reference/appcontainer?view=msvc-170
- https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide
- https://docs.microsoft.com/en-us/windows/win32/secauthz/appcontainer-isolation
