### ISSUE TITLE
"The file to be packed was not found on disk" error when some conditions.

### ISSUE THREAD

**Issue by HavenDV** [microsoft/microsoft-ui-xaml#6456]
### Describe the bug
I'm not sure about the repository for this bug, but I'll start here.
Under certain conditions, an error message appears. At the same time, outside of these conditions, everything works correctly.
```
1>------ Build started: Project: H.OxyPlot.WinUI, Configuration: Debug Any CPU ------
1>H.OxyPlot.WinUI -> C:\Users\haven\source\repos\HavenDV\OxyPlot.Windows\src\libs\H.OxyPlot.WinUI\bin\Debug\net5.0-windows10.0.18362.0\H.OxyPlot.WinUI.dll
1>H.OxyPlot.WinUI -> C:\Users\haven\source\repos\HavenDV\OxyPlot.Windows\src\libs\H.OxyPlot.WinUI\bin\Debug\net6.0-windows10.0.18362.0\H.OxyPlot.WinUI.dll
1>C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error NU5026: The file 'C:\Users\haven\source\repos\HavenDV\OxyPlot.Windows\src\libs\H.OxyPlot.WinUI\C:\Users\haven\source\repos\HavenDV\OxyPlot.Windows\src\shared\H.OxyPlot.Uno.Shared\Themes\Generic.xaml' to be packed was not found on disk.
1>Done building project "H.OxyPlot.WinUI.csproj" -- FAILED.
```

### Steps to reproduce the bug

Conditions:
1. GeneratePackageOnBuild = true
2. shared project is used
3. shared project contains .xaml file
4. UseWinUI = true
5. PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0"
6. WinUI library

Repro: [H.OxyPlot-main.zip](https://github.com/microsoft/WindowsAppSDK/files/7674333/H.OxyPlot-main.zip)
Build "H.OxyPlot.WinUI" in Release mode.

### NuGet package version

1.0.0

### Packaging type

Library

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

**Comment by HavenDV** [comment]
Up

**Comment by JesseCol** [comment]
Project templates have changed considerably over the last few years, can you repro this with the most recent project template?  If so, please provide the repro, thanks!
