### ISSUE TITLE
Theme and ThemeKeys are not working properly

### ISSUE THREAD

**Issue by saravanan-2112** [microsoft/microsoft-ui-xaml#6457]
### Describe the bug

1. The theme is not applied to the ComboBox popup If we change the theme dynamically.
2. ThemeKeys are not working on code behind. I have changed the button border brush on the code behind, whenever the theme changes the border color should be updated based on the key but it is not working.

### Steps to reproduce the bug

1. Run the attached sample - [Theme_Issue.zip](https://github.com/microsoft/WindowsAppSDK/files/7685111/Theme_Issue.zip)

2. Click toggle theme button
3. Now, press the ComboBox DropDown button, then the popup will be opened.
4. The theme is not applied to the popup.
5. Also, the Content button border color is not cahnged.

### Expected behavior

- The theme should be applied to the Combobox popup when changing the theme at runtime.
- Content button border color should be changed when the theme is changed.

### Screenshots

<img width="710" alt="image" src="https://user-images.githubusercontent.com/92977521/145397865-6b0450f3-3235-4760-a2f8-4bb5b0aabd2d.png">

### NuGet package version

1.0.0

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022-preview

**Comment by saravanan-2112** [comment]
Hi Team,

Any update on this?

**Comment by kmgallahan** [comment]
Don't expect much for 2-3 weeks:

https://github.com/microsoft/microsoft-ui-xaml/issues/6462

**Comment by StephenLPeters** [comment]
This is a known issue we are working to resolve.

**Comment by ruben69695** [comment]
I'm having the same issue when applying an AcrylicBrush from the code behind to a Background property in a Border class. The borders created from XAML are working as expected, but the generated from the code behind are not.
