### ISSUE TITLE
FlowLayout vertical items alignment is not consistent.

### ISSUE THREAD

**Issue by pfresnay** [microsoft/microsoft-ui-xaml#646]
**Describe the bug**
FlowLayout in ItemsRepeater vertical items alignment is not consistent.

**Steps to reproduce the bug**
Create an ItemsRepeater with Flowyout and variable sized items.

**Expected behavior**
Consistent vertical alignement
Suggestion : verticalalignement property to specify desired behavior.

**Screenshots**
[Sample screenshot](https://insideso-my.sharepoint.com/:i:/g/personal/pascal_fresnay_excense_fr1/Efgj1iVjGddJuLZg2lg1k24BEEiWWgwK49-IxlIyyEiulA)

**Version Info**
Windows 10 1903
NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.2

**Comment by jevansaks** [comment]
Thanks for the bug report! Pasting the image inline to make it easier. The first line's using center alignment but the second and third line are top-aligned. @ranjeshj any ideas?

![image](https://user-images.githubusercontent.com/20667023/57093550-177cfb00-6cc3-11e9-8905-e178027fb585.png)

**Comment by ranjeshj** [comment]
not sure. can you please share the code to reproduce this ?

**Comment by pfresnay** [comment]
@ranjeshj 

`
<Page
    x:Class="App4.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App4"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Grid>
        <controls:ItemsRepeater ItemsSource="{x:Bind list}">
            <controls:ItemsRepeater.ItemTemplate>
                <DataTemplate x:DataType="local:Item">
                    <Border Width="{x:Bind W}" Height="{x:Bind H}" Background="LightCoral">
                        <TextBlock FontSize="15">
                            <Run Text="{x:Bind W}" />,<Run Text="{x:Bind H}" />
                        </TextBlock>
                    </Border>
                </DataTemplate>
            </controls:ItemsRepeater.ItemTemplate>
            <controls:ItemsRepeater.Layout>
                <controls:FlowLayout MinColumnSpacing="40" MinRowSpacing="40" LineAlignment="Center" />
            </controls:ItemsRepeater.Layout>
        </controls:ItemsRepeater>
    </Grid>
</Page>
`

`namespace App4
{
    public class Item
    {
        public int W { get; set; }
        public int H { get; set; }
    }

    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        public IEnumerable<Item> list { get; } = new List<Item>
        {
            new Item{ W = 300, H = 300 },
            new Item{ W = 350, H = 150 },
            new Item{ W = 300, H = 300 },
            new Item {W = 350, H = 250 },
            new Item {W = 200, H = 250 },
            new Item {W = 200, H = 150 },
            new Item {W = 100, H = 150 },
            new Item {W = 300, H = 150 },
            new Item {W = 300, H = 200 },
            new Item {W = 300, H = 100 }
        };
    }
}`

**Comment by ranjeshj** [comment]
LineAlignment makes the line aligned either to the left, right, center in the above sample, so i think that is working as expected. What is a bit off is that the items are not top aligned consistently. If an item has smaller height, it is not getting the entire slot with the extra space and where it is arranged seems to be inconsistent.

**Comment by ranjeshj** [comment]
I' have created a PR to fix the issue, but the sample needs to be updated to use VerticalAlignment='center' on the items to achieve the look you are going for. Thanks!
