### ISSUE TITLE
UWP - WebView2 - "All GUIDs must be unique." error in Windows App Certification Kit

### ISSUE THREAD

**Issue by akbayt** [microsoft/microsoft-ui-xaml#6463]
### Describe the bug

We have a very simple UWP app with WebView2 and the package validation fails during the runtime metadata validation step.

![image](https://user-images.githubusercontent.com/11097700/145681255-78d8599b-5a4f-4101-af6a-40b531e8a34b.png)

`The type Microsoft.UI.Xaml.Controls.Primitives.IPopup4 in file C:\Program Files\WindowsApps\BytroLabs.CallofWar_1.0.1.0_x86__jbymkwf2aqtfe\Microsoft.UI.Xaml.winmd has the same GUID as the following types: Windows.UI.Xaml.Controls.Primitives.IPopup4. All GUIDs must be unique.`

App Setup:

- UWP c# app
- packages:

![image](https://user-images.githubusercontent.com/11097700/145681319-0ca64ecf-53ff-4b7c-b688-504760df05c5.png)

### Steps to reproduce the bug

1. Solution Explorer
2. Target App
3. Publish
4. Create App Package
5. Microsoft Store as XXXX by YYYY
6. Select x86 + x64 release
7. Create -> Wait until it completes
8. Launch Windows App Certification Kit -> Run -> Wait until it completes
9. It fails :( 

### Expected behavior

Passing the validation -> uploading the app to the store -> getting ready for Christmas

### NuGet package version

Microsoft.UI.Xaml 2.8.0-prerelease.210927001 (`we have to use this pre-release version to be able to use WebView2`)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Windows App Certification Kit: 10.0.22000.194

**Comment by krschau** [comment]
Hi @akbayt, I'm having some trouble repro-ing this. Could you give me a min-repro app? If not, can you tell me if you're using Popups (and how), or maybe what UWP Toolkit controls you're using? Thanks!

**Comment by akbayt** [comment]
Hi @krschau, thanks for your response. Recently I figured that the issue was the `prerelease` version of Microsoft.UI.Xaml. To be able to use WebView2 I had to migrate my project to WinUI 3. So the issue is resolved indirectly.
