### ISSUE TITLE
Payload contains two or more files with the same destination path "Budget Control.deps.json"

### ISSUE THREAD

**Issue by movpushmov** [microsoft/microsoft-ui-xaml#6465]
### Describe the bug

APPX1101 Payload contains two or more files with the same destination path 'Budget Control.deps.json'.

Source files: 

C:\Users\redfo\source\Budget Control\Budget Control\obj\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\Budget Control.deps.json

C:\Users\redfo\source\Budget Control\Budget Control\bin\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\Budget Control.deps.json

### Steps to reproduce the bug

Run this project:

[Budget Control.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7697600/Budget.Control.zip)

### Expected behavior

This project must be built

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by kmgallahan** [comment]
FYI, I had this error and removing a package reference for **Microsoft.EntityFrameworkCore.Tools** made it go away.

**Comment by movpushmov** [comment]
> I had this error and removing a package reference for **Microsoft.EntityFrameworkCore.Tools** made it go away.

Yep, it works! Thank you!

**Comment by briantgil** [comment]
Since I needed EFC Tools for scaffold-dbcontext command, I commented out `<PrivateAssets>all</PrivateAssets>` within the EFC Tools package reference in my .csproj file to resolve the issue:

```xml
    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.16">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.16">
        <!--<PrivateAssets>all</PrivateAssets>-->
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
	</ItemGroup>
```
