### ISSUE TITLE
WinUI 3 - Window.SizeChanged event not working when AppWindow.Changed is registered

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#6466]
### Describe the bug

When you register for the AppWindow.Changed event, Window.SizeChanged is no longer fired except the first time.

### Steps to reproduce the bug

1. Register for the AppWindow.Changed event.
2. Resize the window and notice that the content no longer resizes.

### Expected behavior

The window should correctly resize and the SizeChanged event should be fired even if AppWindow.Changed is registered. AppWindow shouldn't affect the XAML content.

### NuGet package version

1.0.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

**Comment by Jaiganeshkumaran** [comment]
This seems to occur in every control, not just SplitView.

**Comment by Jaiganeshkumaran** [comment]
I found the actual issue. It occurs only when registering for the AppWindow::Changed event.

**Comment by StephenLPeters** [comment]
@marb2000 FYI, can you suggest a dev to think about this?

**Comment by pratikone** [comment]
I just tried and this works correctly in current 1.2 version of winappsdk. You may want to give it a try.
I use this code to test it.
```c#
private void button_Click(object sender, RoutedEventArgs e)
        {
            this.AppWindow.Changed += (sender, args) =>
            {
                Debug.WriteLine("appwindow");

            };
            this.SizeChanged += (sender, args) =>
            {
                Debug.WriteLine("sizechanged");

            };
        }
```
This hits both event handlers in the breakpoint as well as in Output window of Visual Studio.
As a result, I am closing this issue as no repro. If you still find it happening, do comment it here and I will re-open it here.

**Comment by BubbaRichard** [comment]
I just reproduced it. I have 1.2.221116.1 installed.
SizeChanged will not fire if the change is horizontal on any control in a Page but it does fire for vertical changes. The page is loaded in a frame in the main window on it's load. 
SizeChanged also fires for maximize and minimize. Just not for Width changes. I noticed it first in the Split view but it is everything including the page itself.

**Comment by pratikone** [comment]
thanks for testing it. I will check it out.
