### ISSUE TITLE
Fluent v2 Inherited Text Foreground is Incorrect in ListView for TextBox/DatePicker/etc.

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#6469]
### Describe the bug

This is a design bug with the new Fluent v2 styles -- primarily the dark theme. It is not a technical issue.

With the old Fluent v1 and earlier styles, the ListViewItem selection background color was not so different from non-selected item backgrounds. In practice this means the text Foreground brush doesn't need to change if an item is selected or not. However, in Fluent v2, selected backgrounds are now significantly different from non-selected which requires inverting the text Foreground color. This works up until you until you have an input/editing control. Input controls like TextBox override the inherited Foreground color.

Fluent v1: (no issue)

![image](https://user-images.githubusercontent.com/17993847/146631149-9651405b-3edc-43ec-95f6-3f6361bd3b3b.png)

Fluent v2: (issue)

![image](https://user-images.githubusercontent.com/17993847/146631094-923ddee0-7f2e-4aff-bccf-96b0fcbd0df0.png)

With Fluent v2 in dark theme, selected ListViewItems violate the [accessibility contrast requirements](https://docs.microsoft.com/en-us/windows/apps/design/accessibility/accessible-text-requirements) (set by Windows). It is hard to see regardless of the requirements themselves.

### Steps to reproduce the bug

Within a ListView simply place TextBoxes or DatePicker controls as content. You will notice that the default text Foreground colors do not work if the ListViewItem is selected. 

Repro App:
[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7700035/App1.zip)

### Expected behavior

In older styles the Text foreground never needs to change. With the newer styles, editing controls must manually break the foreground brush inheritance when they are selected to avoid issues. This is not always convenient or intuitive.

Bottom line I want to know the recommended solutions Microsoft has for this issue. There needs to be something simple. I'm guessing it was missed during Fluent v2 style development. That said, I've seen styles such as the below which solve this issue but don't seem to have been released or set as the default:

![](https://docs.microsoft.com/en-us/windows/apps/design/controls/images/listview-grouped-example-resized-final.png)

### Screenshots

Issue:

![image](https://user-images.githubusercontent.com/17993847/146629967-44ababba-b8a2-41e8-a860-07583b22fcbc.png)

No Issue:

![image](https://user-images.githubusercontent.com/17993847/145732787-45007829-f660-4f8d-ab99-3dbcd8bb6cc9.png)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@chigy FYI

**Comment by robloo** [comment]
@chigy @StephenLPeters My recommendation is to add another Secondardy/Alternate ListViewItem style that supports the gray background and selection pill design used in the ComboBox. That would allow apps to quickly switch to a container style that doesn't have this issue.

![](https://camo.githubusercontent.com/6dd53e664d17a5138cac6f6615b0460593bcc1a6e9f30a0ae82615072bf4ed0c/68747470733a2f2f646f63732e6d6963726f736f66742e636f6d2f656e2d75732f77696e646f77732f617070732f64657369676e2f636f6e74726f6c732f696d616765732f6c697374766965772d67726f757065642d6578616d706c652d726573697a65642d66696e616c2e706e67)

**Comment by robloo** [comment]
I'm closing this as apps are moving to Fluent v2 / Windows 11 styling in listboxes for the most part. That sidesteps this issue with the older styles.

That said, the newer listbox/listboxitem styles really should have been copied over to this WinUI library repo around the Fluent v2 timeframe. Don't know why it's mismatched in this area.
