### ISSUE TITLE
ComboBox not selecting inside flyout

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/microsoft-ui-xaml#6470]
I have the following flyout defined as such:
```xml
<AppBarButton Label="Filename to Tag" Icon="Edit" ToolTipService.ToolTip="Converts the filenames of the selected music files to tags.">
  <AppBarButton.Flyout>
    <Flyout x:Name="FilenameToTagFlyout">
      <StackPanel>
        <TextBlock Style="{ThemeResource BaseTextBlockStyle}" Text="Convert the selected filenames to tags"/>
        
        <ComboBox x:Name="CmbFilenameToTag" Margin="0,6,0,0" MinWidth="200" PlaceholderText="Select format string">
          <x:String>%artist%- %title%</x:String>
          <x:String>%title%- %artist%</x:String>
          <x:String>%title%</x:String>
        </ComboBox>
        
        <Button Margin="0,6,0,0" Style="{StaticResource AccentButtonStyle}" Content="Convert" Click="FilenameToTag"/>
      </StackPanel>
    </Flyout>
  </AppBarButton.Flyout>
</AppBarButton>
```

However, when I try to select an item in the box, it just doesn't select. Any ideas?

**Comment by robloo** [comment]
Might be related to: https://github.com/microsoft/microsoft-ui-xaml/issues/1467

Isn't it nice how these fundamental issues go unaddressed for over 2 years?

**Comment by nlogozzo** [comment]
Could maybe be related 🤷‍♂️ 

And yes, love how focused Microsoft is on empowering developers by supporting their latest technologies 😁

**Comment by StephenLPeters** [comment]
@llongley FYI

**Comment by 95jonpet** [comment]
This resolved the issue for me: https://social.msdn.microsoft.com/Forums/en-US/ae9d0b92-5c97-40cf-9c39-fa940121b2b7/uwp14393combobox-within-flyout-loss-mouse-amp-touch-interaction-after-target-the-uwp-project?forum=wpdevelop

Set the `AllowFocusOnInteraction` property to `True` on your `ComboBox` element:

```xaml
<ComboBox AllowFocusOnInteraction="True" />
```
