### ISSUE TITLE
ScrollViewer inside a PivotItem crashes app when scrolling with touchpad

### ISSUE THREAD

**Issue by EugenM88** [microsoft/microsoft-ui-xaml#6472]
### Describe the bug

Greetings, this issue is rather fustrating, when i add a ScrollViewer control and inside it i add alot of other controls, as soon as i scroll with trackpad to the end, once it reaches the end the application crashes with a weird error.
It opens a new tab in VS2022 named App.g.i.cs, and program breaks right here:

`
#if DEBUG && !DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
            UnhandledException += (sender, e) =>
            {
                if (global::System.Diagnostics.Debugger.IsAttached) global::System.Diagnostics.Debugger.Break();
            };`

There is no error information here but if i press continue debugging then program displays the following error message:
Unhandled exception at 0x00007FF91B95B302 (KernelBase.dll) in Program Name Hidden.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001C390317D00, 0x0000000000000004).

Note: Program Name Hidden.exe not actual name of the program.

If i use my mouse wheel, it doesnt crash at all, but as soon as i scroll down to the end of scroll viewer, or a listview scroll with the touchpad it instantly crashes with that error.

Even more strange is the fact that if i resize the window manually (even if its by 1 pixel), before ever doing any scroll operation, the program works fine as intended.

This happens even with a clean installation of VS2022.

Im pretty sure im not the only one with this problem, however i cant really think of a proper solution to fix this issue since there doesnt seem to be anyway to even programmatically resize/hide/minimize/maximize the window in WinUI3.

Any help is greatly appreciated!
Thank you so much in advance.

### Steps to reproduce the bug

Create new project...
Add a scroll viewer inside a pivot item.... 
Add a VariableSizedWrapGrid with horizontal orientation...
Add inside the VariableSizedWrapGrid some controls, until scrollviewer automatically shows a vertical scrollbar, try scrolling on your touchpad with 2 fingers down to the end of the list without ever resizing the window.
Program crashes as explained.

### Expected behavior

Program should not crash and should continue to operate as intended.

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by wbokkers** [comment]
Maybe this is related to this issue: https://github.com/microsoft/microsoft-ui-xaml/issues/6218

**Comment by StephenLPeters** [comment]
@RBrid FYI

**Comment by RBrid** [comment]
Thanks for the report and sorry for the trouble. This is the same issue as #6218 for which we are working on providing a fix.

**Comment by EugenM88** [comment]
Excelent news! Thank you!
