### ISSUE TITLE
How to override the MaxWidth of ContentDialog

### ISSUE THREAD

**Issue by naveenkumar-sanjeevirayan** [microsoft/microsoft-ui-xaml#6479]
### Describe the bug

I couldn't override the ContentDialog MaxWidth value when I initialize a ContentDialog in the .Xaml page. 
I need to increase the width of the content dialog based on children's size.

Could you please check and provide a solution for this?

### Steps to reproduce the bug

1. Run the attached sample.
2. Click the button added in the window.

### Expected behavior

Content dialog width should be overridden based on children's size.

### Screenshots

Image:
![image](https://user-images.githubusercontent.com/61832185/145998135-40fe354f-ffef-4c48-8256-1d39c009d703.png)

Sample:
[ContentDialogTesting.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7711579/ContentDialogTesting.zip)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by castorix** [comment]
It seems to work if I add _ContentDialogMinWidth_ and _ContentDialogMaxWidth_ 
in app.xaml , in
 <Application.Resources> 

   < ResourceDictionary >

**Comment by naveenkumar-sanjeevirayan** [comment]
Hi @castorix , It will be working in sample level. But I need to override in control level (class library). Do you have solution for this?

**Comment by karthikraja-arumugam** [comment]
While working with class library we unable to change the width of a content dialog window, Do we have any workaround?

It seems to break after the WindowsSDK update before that we can change the maxwidth resource key of the content dialog itself now we can set resource key only in app.xaml
