### ISSUE TITLE
Microsoft.UI.Xaml version 2.7.0 System.IO.FileLoadException

### ISSUE THREAD

**Issue by capegreg** [microsoft/microsoft-ui-xaml#6481]
### Describe the bug

Getting System.IO.FileLoadException when building an x64 Debug using Microsoft.UI.Xaml version 2.7.0.

Error:

System.IO.FileLoadException
  HResult=0x80131621
  Message=Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Error is when typeName = "Microsoft.UI.Xaml.Controls.StylesVersion"

Partial class:

~\obj\x64\Debug\XamlTypeInfo.g.cs

        public global::Windows.UI.Xaml.Markup.IXamlType GetXamlTypeByName(string typeName)
        {
            return Provider.GetXamlType(typeName);
        }

No error occurs when building x86 Debug OR when using Microsoft.UI.Xaml version 2.5.0

### Steps to reproduce the bug

Add package Microsoft.UI.Xaml version 2.7.0 to UWP C# project.
Build x86 Debug and run project. No issue.
Build x64 Debug and run project. System.IO.FileLoadException error.

Go to packages and install Microsoft.UI.Xaml version 2.5.0 (Note: all version between 2.7.0 & 2.5.0 have same error scenario)
Build x86 Debug and run project. No issue.
Build x64 Debug and run project. No issue.

My environment:
VS 2019

Edition	Windows 10 Pro
Version	21H2
OS build	19044.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

### Expected behavior

No System.IO.FileLoadException error when running x64 build.

### Screenshots

![image](https://user-images.githubusercontent.com/1051118/146062177-e3c10fd7-1f1c-4921-b6f3-5bc9a3c8255d.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Possible related issue may be due to exception.

https://github.com/microsoft/microsoft-ui-xaml/issues/6219

**Comment by nandin-borjigin** [comment]
Experiencing exactly same issue!

**Comment by StephenLPeters** [comment]
Microsoft.UI.Xaml.Controls.StylesVersion is a preview API... is that the cause of the exception? can you try switching to ControlsResourcesVersion?

**Comment by mc0re** [comment]
I have the exact same error. And I don't use `StylesVersion` in my code.

**Comment by mc0re** [comment]
I see the author has gone offline. Maybe satisfied with the `x86` workaround :-)
Is there anything I can provide to help investigate this?

**Comment by mc0re** [comment]
@StephenLPeters Do you need anything?

**Comment by StephenLPeters** [comment]
@ranjeshj and @ojhad FYI

**Comment by ojhad** [comment]
@mc0re Could you please create a new issue and include repro steps specific to the scenario you are seeing?

**Comment by steam3d** [comment]
I have the same issue on Microsoft.UI.Xaml version 2.8.2

**Comment by TorstenKannler** [comment]
The same still happens for version 2.8.5.

Debug x64 => System.IO.FileLoadException
Debug x86 => No issue.
Release x86 => No issue.
Release x64 => No issue.

**Comment by pwfulghum** [comment]
This is marked as a no fix... so basically you can't use the tooklit with x64 / Debug
