### ISSUE TITLE
MenuFlyoutItem.KeyboardAccelerators fires Invoked event twice

### ISSUE THREAD

**Issue by HarutyunDokhoyan** [microsoft/microsoft-ui-xaml#6488]
### Describe the bug

I have implemented MenuFlyoutItem.KeyboardAccelerators and below you can see the code

Xaml code

```
        <Button Content="Edit Options"
            Width="100"
            Height="100"
            HorizontalAlignment="Right">
        <Button.Flyout>
            <MenuFlyout>
                <MenuFlyoutItem x:Name="FlyoutItem1" Text="Copy" Icon="Copy">
                    <MenuFlyoutItem.KeyboardAccelerators>
                        <KeyboardAccelerator x:Name="Test" Key="C" Modifiers="Control" Invoked="Test_Invoked" />
                    </MenuFlyoutItem.KeyboardAccelerators>
                </MenuFlyoutItem>
                <MenuFlyoutSeparator/>
            </MenuFlyout>
        </Button.Flyout>
    </Button>
```
Code-Behind

```
    public sealed partial class MainPage : Page
{
    public MainPage()
    {
        this.InitializeComponent();
    }
    private void Test_Invoked(KeyboardAccelerator sender, KeyboardAcceleratorInvokedEventArgs args)
    {
        Debug.WriteLine($">>>>>>>>>>>>>>>>>>>>>>>>>>>>> invoked Hash = {sender.GetHashCode()}");
    }
}
```

### Steps to reproduce the bug

Before clicking on the button in the application, the CTRL+C hotkey action fires an event. But when I click on the button and MenuFlyout appears, the Ctrl+C hotkey action fires twice the same event. And when I click on another place in the application event again fires normally only once.

### Expected behavior

The CTRL+C hotkey action fires an event only once.

### NuGet package version

Microsoft.UI.Xaml 2.5.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@bpulliam and @JesseCol this sounds familiar... thoughts?
