### ISSUE TITLE
Unable to find a type named "MediaTransportControls" on Empty WinUI3 Desktop Project

### ISSUE THREAD

**Issue by KWodarczyk** [microsoft/microsoft-ui-xaml#6489]
### Describe the bug

Exception is throws while looping over merged dictionaries.

` 
public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();

            foreach (var rd in Application.Current.Resources.MergedDictionaries)
            {
                try
                {
                    foreach (var value in rd.Values)
                    {
                       
                    }
                }
                catch (Exception ex)
                {
                    //Unable to find a type named 'Microsoft.UI.Xaml.Controls.MediaTransportControls'

                    //at WinRT.TypeNameSupport.FindTypeByNameCore(String runtimeClassName, Type[] genericTypes)
                    //at WinRT.TypeNameSupport.FindTypeByName(ReadOnlySpan`1 runtimeClassName)
                    //at ABI.System.Type.FromAbi(Type value)
                    //at ABI.System.Nullable`1.get_Value()
                    //at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
                    //at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
                    //at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
                    //at WinRT.Marshaler`1.<> c.<.cctor > b__0_59(Object box)
                    //at ABI.System.Collections.Generic.KeyValuePair`2.get_Key()
                    //at ABI.System.Collections.Generic.KeyValuePair`2.FromAbi(IntPtr thisPtr)
                    //at ABI.System.Collections.Generic.IEnumerator`1.get__Current()
                    //at ABI.System.Collections.Generic.IEnumerator`1.FromAbiHelper.MoveNext()
                    //at ABI.System.Collections.Generic.IEnumerator`1.MoveNext()
                    //at ABI.System.Collections.Generic.IDictionary`2.FromAbiHelper.DictionaryValueCollection.DictionaryValueEnumerator.MoveNext()
                    //at..\WinUI3Desktop\MainWindow.xaml.cs:line 34
                }
            }
        }

        private void myButton_Click(object sender, RoutedEventArgs e)
        {
            myButton.Content = "Clicked";
        }
    }

`

`<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                
            </ResourceDictionary.MergedDictionaries>
            
        </ResourceDictionary>
    </Application.Resources>`

### Steps to reproduce the bug

Just create new WinUI3 project for Desktop and put the following code in main window and run

`        public MainWindow()
        {
            this.InitializeComponent();

            foreach (var rd in Application.Current.Resources.MergedDictionaries)
            {
                try
                {
                    foreach (var value in rd.Values)
                    {
                       
                    }
                }
                catch (Exception ex)
                {
                    //Unable to find a type named 'Microsoft.UI.Xaml.Controls.MediaTransportControls'

                    //at WinRT.TypeNameSupport.FindTypeByNameCore(String runtimeClassName, Type[] genericTypes)
                    //at WinRT.TypeNameSupport.FindTypeByName(ReadOnlySpan`1 runtimeClassName)
                    //at ABI.System.Type.FromAbi(Type value)
                    //at ABI.System.Nullable`1.get_Value()
                    //at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
                    //at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
                    //at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
                    //at WinRT.Marshaler`1.<> c.<.cctor > b__0_59(Object box)
                    //at ABI.System.Collections.Generic.KeyValuePair`2.get_Key()
                    //at ABI.System.Collections.Generic.KeyValuePair`2.FromAbi(IntPtr thisPtr)
                    //at ABI.System.Collections.Generic.IEnumerator`1.get__Current()
                    //at ABI.System.Collections.Generic.IEnumerator`1.FromAbiHelper.MoveNext()
                    //at ABI.System.Collections.Generic.IEnumerator`1.MoveNext()
                    //at ABI.System.Collections.Generic.IDictionary`2.FromAbiHelper.DictionaryValueCollection.DictionaryValueEnumerator.MoveNext()
                    //at..\WinUI3Desktop\MainWindow.xaml.cs:line 34
                }
            }
        }`

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by MikeHillberg** [comment]
[MediaPlayerElement](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.MediaPlayerElement) and [MediaTransportControls](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.MediaTransportControls) aren't supported yet in WinUI3, and the APIs aren't available, but it looks like the default styles got left in [XamlControlsResources](https://docs.microsoft.com/uwp/api/Microsoft.UI.Xaml.Controls.XamlControlsResources).

I'm not sure what you're enumerating for, but one thing you could do is check the Key first and ignore anything that begins with "Media".

**Comment by KWodarczyk** [comment]
I am enumerating to find datatemplate that I need did not include this logic nor resource dictionary for brevity.
It's still a bug since it should not just throw exception like that right ?

**Comment by MikeHillberg** [comment]
Yep, definitely a bug, thanks for opening the Issue. I was just writing down what I saw and updated the tags to send it to a team.

**Comment by KWodarczyk** [comment]
Comment

**Comment by kmahone** [comment]
The latest preview release of WindowsAppSDK includes MediaTransportControls so this issue has likely been resolved. @KWodarczyk can you try this latest release and see if you are still hitting this issue?
