### ISSUE TITLE
[NavigationView] Text labels get truncated when setting Windows text size to 225%

### ISSUE THREAD

**Issue by niels9001** [microsoft/microsoft-ui-xaml#6491]
### Describe the bug

When setting the text scale in Windows to 225% NavigationViewItems text labels are truncated. PowerToys got flagged by this by the accessibility team: https://github.com/microsoft/PowerToys/issues/14342

### Steps to reproduce the bug

1. Open Windows Settings
2. Navigate to Accessibility
3. Click on Text size
4. Set Text Size to 225% (max)
5. See menu items in the NavigationView

### Expected behavior

NavigationViewItems text labels should not get truncated

### Screenshots

![Uploading image.png…]()

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by StephenLPeters** [comment]
@chigy the current NavigationView design doesn't support anything but clipping very long text, which is much easier to hit at 225% scale.  Does this need to be updated?

**Comment by chigy** [comment]
@niels9001 , @StephenLPeters , we are not required to support over 200% scale so for WinUI, we are not looking to fix 225%.
