### ISSUE TITLE
[NavigationView] Toggling `PaneDisplayMode` and `IsPaneToggleButtonVisible` at the same time causes the BackButton and PaneToggle to line up incorrectly

### ISSUE THREAD

**Issue by PureWeen** [microsoft/microsoft-ui-xaml#6493]
### Describe the bug

If you toggle `PaneDisplayMode` and `IsPaneToggleButtonVisible` at the same time it causes the PaneToggle and BackButton to display incorrectly

```C#
        private void Button_Click(object sender, Windows.UI.Xaml.RoutedEventArgs e)
        {
            if (navigationView.IsPaneToggleButtonVisible)
            {
                navigationView.PaneDisplayMode = NavigationViewPaneDisplayMode.Left;
                navigationView.IsPaneToggleButtonVisible = false;
            }
            else
            {
                navigationView.PaneDisplayMode = NavigationViewPaneDisplayMode.LeftMinimal;
                navigationView.IsPaneToggleButtonVisible = true;
            }
        }
```

### Steps to reproduce the bug

I tested this on both WinappSDK 1.0 and the latest 2.8 pre-release of Microsoft.UI.XAML and saw the same behavior both places

[ToggleButtonOverlap.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7737721/ToggleButtonOverlap.zip)

1) run sample
2) click the toggle button
3) At this point the backbutton will overlap the Pane Toggle button or they will be aligned vertically
4) if you slightly resize the window to trigger a refresh the buttons will line up horizontally like they should

### Expected behavior

The backbutton and pane toggle button should line up horizontally when they are toggled back to visible

### Screenshots

Here they are overlapping after being toggled
<img width="748" alt="image" src="https://user-images.githubusercontent.com/5375137/146607805-c6c25266-16db-4680-90f1-96fc9d64e39f.png">

If I slightly adjust the window size then they display correctly
<img width="746" alt="image" src="https://user-images.githubusercontent.com/5375137/146607845-693b0492-1dde-471f-9a2e-a5e477a5d88b.png">

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@ojhad and @karenbtlai thoughts on a root cause?

**Comment by chingucoding** [comment]
I would like to take a look at this.
