### ISSUE TITLE
Question: How to bind AnimatedIcon to NavigationViewItem.Icon

### ISSUE THREAD

**Issue by kengwang** [microsoft/microsoft-ui-xaml#6496]
I'm trying to use `AnimatedIcon` in `NavigationViewItem`, it works properly when using it in `MenuItems`
```xaml
...
<winui:NavigationViewItem Content="Search">
                    <winui:NavigationViewItem.Icon>
                        <winui:AnimatedIcon>
                            <winui:AnimatedIcon.Source>
                                <animatedVisuals:AnimatedFindVisualSource />
                            </winui:AnimatedIcon.Source>
                            <winui:AnimatedIcon.FallbackIconSource>
                                <winui:SymbolIconSource Symbol="Find" />
                            </winui:AnimatedIcon.FallbackIconSource>
                        </winui:AnimatedIcon>
                    </winui:NavigationViewItem.Icon>
                </winui:NavigationViewItem>
...
```

But when I'm using Binding in `MenuItemTemplate`, it goes wrong
```xaml
<models:NavigationMenuItemModel
                    Content="Search">
                    <models:NavigationMenuItemModel.Icon>
                        <winui:AnimatedIcon>
                            <winui:AnimatedIcon.Source>
                                <animatedVisuals:AnimatedFindVisualSource />
                            </winui:AnimatedIcon.Source>
                            <winui:AnimatedIcon.FallbackIconSource>
                                <winui:FontIconSource FontFamily="{StaticResource SymbolThemeFontFamily}" Glyph="&#xE721;" />
                            </winui:AnimatedIcon.FallbackIconSource>
                        </winui:AnimatedIcon>
                    </models:NavigationMenuItemModel.Icon>
                </models:NavigationMenuItemModel>

...
<winui:NavigationView.MenuItemTemplate>
                <DataTemplate x:DataType="models:NavigationMenuItemModel">
                    <winui:NavigationViewItem
                        Height="40"
                        Content="{x:Bind Content}"
                        Icon="{x:Bind Icon}"
                        MenuItemsSource="{x:Bind Children}" />
                </DataTemplate>
            </winui:NavigationView.MenuItemTemplate>
...
```

Model:
```csharp
using System;
using System.Collections.ObjectModel;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;

public class NavigationMenuItemModel : DependencyObject
{
 public static readonly DependencyProperty ContentProperty = DependencyProperty.Register(
        "Content", typeof(string), typeof(NavigationMenuItemModel), new PropertyMetadata(default(string)));

    public string Content
    {
        get => (string)GetValue(ContentProperty);
        set => SetValue(ContentProperty, value);
    }

    public static readonly DependencyProperty IconProperty = DependencyProperty.Register(
        "Icon", typeof(IconElement), typeof(NavigationMenuItemModel), new PropertyMetadata(default(IconElement)));

    public IconElement Icon
    {
        get => (IconElement)GetValue(IconProperty);
        set => SetValue(IconProperty, value);
    }
}
```

I get an error:
```
System.ArgumentException: Parameter error.

Parameter error.

    at Microsoft.UI.Xaml.Controls.NavigationViewItem.put_Icon(IconElement value)
    at HyPlayer.UWP.Pages.BasePage.XamlBindingSetters.Set_Microsoft_UI_Xaml_Controls_NavigationViewItem_Icon(NavigationViewItem obj, IconElement value, String targetNullValue)
    at HyPlayer.UWP.Pages.BasePage.BasePage_obj6_Bindings.Update_Icon(IconElement obj, Int32 phase)
    at HyPlayer.UWP.Pages.BasePage.BasePage_obj6_Bindings.Update_(NavigationMenuItemModel obj, Int32 phase)
   
```

If the Icon is a FontIcon, it goes well.
I'm wondering why it will throw an error and how to fix it?

**Additional Information: **
Dependencies: Microsoft.UI.Xaml : 2.7.0

**Comment by brandonw3612** [comment]
I wonder if it's because of the namespace thing like by default if you define the `IconElement` property in the class it actually refers to `Windows.UI.Xaml.Controls.IconElement` instead of `Microsoft.UI.Xaml.Controls.IconElement` while `AnimatedIcon` is inherited from the latter one. And I think as you set it a `FontIcon` it works fine because `FontIcon` is inherited from the former one. Additionally I checked out Microsoft's documentation and just found the type of `Icon` property in `NavigationViewItem` is also the one from WinUI Library so maybe you can try this out.

**Comment by kengwang** [comment]
> Re: https://github.com/microsoft/microsoft-ui-xaml/issues/6496#issuecomment-997350595


I've just checked the [documentation](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.animatedicon?view=winui-2.7)
In WinUI 2.7 which I'm using, AnimatedIcon is inherited from `Windows.UI.Xaml.Controls.IconElement` which is the same of which using in the model and `NavigationViewItem`.


![image](https://user-images.githubusercontent.com/30862240/146668932-d5639afe-3fa4-4db3-947f-446e6fa78c13.png)

**Comment by StephenLPeters** [comment]
Hmm, AnimatedIcon is infact a Windows.UI.Xaml.Controls.IconElement.  It does that in a round about way by internally deriving from PathIcon (since IconElement doens't have a public constructor) but I don't think that is the cause of this issue..... I suspect this is a codegen issue with x:Bind, could you try changing the x:Bind to Binding and see if that resolves the issue? @kengwang

**Comment by kengwang** [comment]
> 

I'm currently working on UWP and `Binding` seems not working.
For `Binding` there's no icon displayed, and no error is thrown.

**Comment by kengwang** [comment]
https://github.com/HyPlayer/HyPlayer.UWP/blob/73c72b0c4f14eb3dc33d68e82b843b57c7bdd79c/HyPlayer.UWP/Views/Pages/BasePage.xaml#L120
Project which can reproduce it is here.
I've been removed the line for `Icon` when committing.

**Comment by ojhad** [comment]
@evelynwu-msft @RealTommyKlein This seems like an XMP issue because the error is failing to set the IconElement property to an instance of an AnimatedIcon. Any idea what might be going on here?

**Comment by ojhad** [comment]
Thanks Tommy! Strange that for the author this works with FontIcon. @kengwang can you Tommy's suggestion?

**Comment by kengwang** [comment]
> Re: https://github.com/microsoft/microsoft-ui-xaml/issues/6496#issuecomment-1068087993

Thanks, it works!
