### ISSUE TITLE
TabViewItem header is weirdly rendered when scaling is above 100%

### ISSUE THREAD

**Issue by zipgenius** [microsoft/microsoft-ui-xaml#6497]
### Describe the bug

When screen scaling is set at 125% or above (sometimes the suggested configuration for many notebooks), the TabViewItem header has 4 rounded corners and a gradient background that souldn't be there.

### Steps to reproduce the bug

1. Create a new WindowsApp project;
2. In MainWindow.xaml put a TabView with a TabViewItem, then run the app;
3. Go to Start menu and open the Settings app, then go to System > Display > Scale & layout;
4. If scaling is set to 100%, elevate to anything above it (125% is good enough);
5. The TabViewItem header will transform in something weird.

### Expected behavior

TabViewItem header should scale without any unexpected transformation

### Screenshots

![tabviewIssue](https://user-images.githubusercontent.com/547604/146670389-82390fa2-341b-40fe-bad3-207f44bb43a7.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

I observed this bug in Windows 11 build 22000 and Windows 11 Insider Build 22xxx.
Applying a custom style to the TabViewItem doesn't resolve.
No other workaround found.

**Comment by kmgallahan** [comment]
#6194 
#6207 
#6419 
#6475

**Comment by zipgenius** [comment]
> #6194 #6207 #6419 #6475

I thought they were all unrelated...

**Comment by zadjii-msft** [comment]
This looks awfully a lot like #6076

**Comment by StephenLPeters** [comment]
@gegao18 and @codendone FYI
