### ISSUE TITLE
TextBox caret not visible

### ISSUE THREAD

**Issue by AntonyCorbett** [microsoft/microsoft-ui-xaml#6498]
The TextBox caret is white on a white background (using standard Windows 10 Light theme).

Repro steps: 

1. Use Windows App SDK C# VS2022 Templates to create a new **Blank App, Packaged (WinUI 3 in Desktop)**.
2. Insert a TextBox in **MainWindow.xaml** (e.g. next to the the Button).
3. Build and run.
4. Focus the TextBox and notice the caret is not visible (actually it's white against a light background).

Using Windows 10 - 21H1 (19043.1415). Light theme. VS 2022

**Comment by MUJaCHe66** [comment]
Same issue. Also affects Autosuggestbox. 
Can be reproduced just by checking with Winui 3 Controls Gallery.
Can't find where to style the caret color for a workaround.

**Comment by StephenLPeters** [comment]
@codendone any idea of a root cause?

**Comment by AlanPBourke** [comment]
How do you not notice something like this in testing.

**Comment by dzhukovsky** [comment]
I have the same problem when I use a transparent background for a TextBox/RichEditBox. For some reason, the dark theme cursor is white (as it should be), and the light theme cursor is also white, but should be black.

How to fix it?
