### ISSUE TITLE
ListView check boxes are misaligned on Windows 11

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#6501]
### Describe the bug

ListView Multiple selection check box ticks are misaligned in the latest insider versions of Windows 11.

### Steps to reproduce the bug

1. Open XAML Controls Gallery
2. Search for ListView
3. Check Multiple selection demo

### Expected behavior

Tick is aligned within the CheckBox area

### Screenshots

![image](https://user-images.githubusercontent.com/8152849/146682655-b86478f5-a361-447d-b28e-f5583241abc9.png)

### Windows app type

- [X] UWP
- [ ] Win32

### Windows version

Insider Build (xxxxx)

### Additional context

22523.1000

**Comment by StephenLPeters** [comment]
@FrayxRulez I don't reproduce this issue. I suspect there is more repro steps needed.  What scale factor are you running at? what version of win 11 are you using? Thanks
