### ISSUE TITLE
Text block tooltip binding not working

### ISSUE THREAD

**Issue by killerwife** [microsoft/microsoft-ui-xaml#6504]
### Describe the bug

I have the following code-behind
`            
            private string datalongTooltip { get; set; }

            Binding b = new Binding();
            b.Mode = BindingMode.OneWay;
            b.Source = datalongTooltip;
            ToolTip toolTip = new ToolTip();
            toolTip.SetBinding(ToolTip.ContentProperty, b);
            ToolTipService.SetToolTip(textBlockDatalong, toolTip);
`
And the following xaml
`
<TextBlock Grid.Column="0" Grid.Row="4" x:Name="textBlockDatalong" ToolTipService.Placement="Right"></TextBlock>
`
I expect the binding to change the tooltip to change once I change the datalongTooltip property.

I have also tried the following:
`
<TextBlock Grid.Column="0" Grid.Row="4" x:Name="textBlockDatalong" ToolTipService.Placement="Right" ToolTipService.ToolTip="{x:Bind datalongTooltip}"></TextBlock>
`

To directly bind it to the resource.

And the following works just fine if I do it on every change.

`
            ToolTip toolTip = new ToolTip();
            toolTip.Content = datalongTooltip;
            ToolTipService.SetToolTip(textBlockDatalong, toolTip);
`

As WINUI 3 is quite knew I apologize if I missed the memo on how it should be done.

### Steps to reproduce the bug

1. Change property in ui through any means
2. Get empty or no tooltip

### Expected behavior

See a normal tooltip with the input text.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

I would test unpackaged but I run into this seemingly closed issue https://github.com/microsoft/WindowsAppSDK/issues/1762 which occurs to me on latest VS 2022 17.0.4 (non-preview)

**Comment by MikeHillberg** [comment]
In the x:Bind case:

```xml
<TextBlock Grid.Column="0" Grid.Row="4" x:Name="textBlockDatalong" ToolTipService.Placement="Right" ToolTipService.ToolTip="{x:Bind datalongTooltip}"></TextBlock>
```

you need to similarly set the `Mode=OneWay`, or it will be treated as a one-time binding. (Watching for property changes requires some extra overhead, so it's off by default.) And the `datalongTooltip` property needs to raise change notifications when it changes, either by being a DependencyProperty, or by its class implementing [INotifyPropertyChanged](https://docs.microsoft.com/dotnet/api/Windows.UI.Xaml.Data.INotifyPropertyChanged).

In the programmatic Binding case:

```cs
Binding b = new Binding();
b.Mode = BindingMode.OneWay;
b.Source = datalongTooltip;
ToolTip toolTip = new ToolTip();
toolTip.SetBinding(ToolTip.ContentProperty, b);
ToolTipService.SetToolTip(textBlockDatalong, toolTip);
```
setting the `Source` to `datalongTooltip` is binding to its current value. What you want to bind to is the object on which it's a property, and set the [Binding.Path](https://docs.microsoft.com/uwp/api/Microsoft.UI.Xaml.Data.Binding.Path) to "datalongTooltip". And again the object needs to raise a change notification if the value of the property changes.

**Comment by killerwife** [comment]
Thank you for the response, currently the lack of WINUI 3 examples is a bit daunting, I will test it tomorrow and close the issue accordingly.

**Comment by killerwife** [comment]
ToolTipService.ToolTip="{x:Bind datalongTooltip, Mode=OneWay}

and

Implementing INotifyPropertyChanged PropertyChanged?.Invoke solved it for me. Closing issue. Appreciate the pointers.
