### ISSUE TITLE
How to apply the theme resource changes after it has modified from the code behind

### ISSUE THREAD

**Issue by Naveen61097** [microsoft/microsoft-ui-xaml#6506]
I have created a custom control by overriding textbox. in that control, I have modified the resources collection, but it is not reflected in the UI loaded earlier. Hence need to apply some logic to reapply the theme changes.

    using Microsoft.UI.Xaml;
    using Microsoft.UI.Xaml.Controls;
    using System.Collections.Generic;

    namespace Sample
    {
        public sealed class CustomTextBox : TextBox
        {
            public CustomTextBox()
            {
                this.DefaultStyleKey = typeof(TextBox);
            }
    
            #region IsMandatory
    
            public static readonly DependencyProperty IsMandatoryProperty = DependencyProperty.Register(nameof(IsMandatory), typeof(bool), typeof(CustomTextBox), new PropertyMetadata(false, OnIsMandatoryPropertyChanged));
    
            public bool IsMandatory
            {
                get { return (bool)GetValue(IsMandatoryProperty); }
                set { SetValue(IsMandatoryProperty, value); }
            }
    
            private static void OnIsMandatoryPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
            {
                if (e.OldValue != e.NewValue)
                {
                    var control = d as CustomTextBox;
                    bool isUpdated;
    
                    if (control.IsMandatory)
                    {
                        isUpdated = control.Resources.AddOrUpdate("TextControlHeaderForeground", "Red");
                    }
                    else
                    {
                        isUpdated = control.Resources.AddOrUpdate("TextControlHeaderForeground", control.Resources.GetValueOrDefault("SystemControlForegroundBaseHighBrush"));
                    }
    
                    if (isUpdated)
                    {
                        control.UpdateTheme();
                    }
                }
            }
    
    
            #endregion
    
            public void UpdateTheme()
            {
                // need to update the UI to reflect the changes made in resources
            }
        }
    
        public static class Extensions
        {
            public static TValue GetValueOrDefault<TKey, TValue>(this IDictionary<TKey, TValue> dict, TKey key)
            {
                return dict.TryGetValue(key, out var value) ? value : default(TValue);
            }
    
            public static bool AddOrUpdate<TKey, TValue>(this IDictionary<TKey, TValue> dictionary, TKey key, TValue value)
            {
                if (dictionary.ContainsKey(key))
                {
                    if (!dictionary[key].Equals(value))
                    {
                        dictionary[key] = value;
                        return true;
                    }
                }
                else
                {
                    dictionary.Add(key, value);
                    return true;
                }
    
                return false;
            }
        }
    }

**Comment by MikeHillberg** [comment]
You might be able to work around it by having `UpdateTheme` manipulate the TextBox's [RequestedTheme](https://docs.microsoft.com/uwp/api/Microsoft.UI.Xaml.FrameworkElement.RequestedTheme) property. Change it to something it's not then restore it. That won't cause a flicker but does trigger some re-evaluation of resource references.
