### ISSUE TITLE
Corner radius rendering artifacts

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#6507]
### Describe the bug

Starting from some Windows 11 build (sorry, can't be more specific here) UWP panels with corner radius generate some rendering artifacts.
This doesn't happen always, but frequently enough to be annoying.

### Steps to reproduce the bug

Sadly, I have no retro steps.
This only seems to happen for the bottom left corner.

### Screenshots

![image](https://user-images.githubusercontent.com/8152849/146917277-c3720629-fbeb-429c-a8aa-0db5d87fff88.png)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@codendone and @gegao18 FYI

**Comment by codendone** [comment]
[Internal issue](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/35195843)

**Comment by krschau** [comment]
This is fixed in Insider Preview builds, on builds numbered 22509+.
