### ISSUE TITLE
UWP C++/WinRT Cannot get actual offset of Target property in MenuFlyout

### ISSUE THREAD

**Issue by zyont1000** [microsoft/microsoft-ui-xaml#6508]
### Describe the bug

I have been using Windows::UI::Xaml::Controls::MenuFlyout to display a menu flyout against a Bitmap Icon in a UWP C++/WinRT application.
The XAML content is as below.

        <BitmapIcon UriSource="Assets/MenuBar.png" ShowAsMonochrome="False" x:Name="BitIcon" Tapped="BitIcon_Tapped" Height="72" Width="72">
            <FlyoutBase.AttachedFlyout>
                <MenuFlyout x:Name="BlowFlyOut" Opened="BlowFlyOut_Opened" Placement="Bottom">
                    <ToggleMenuFlyoutItem Text="New"/>
                    <ToggleMenuFlyoutItem Text="Open"/>
                    <ToggleMenuFlyoutItem Text="Save"/>
                    <MenuFlyoutSeparator />
                    <ToggleMenuFlyoutItem Text="Exit"/>
                </MenuFlyout>
            </FlyoutBase.AttachedFlyout>
        </BitmapIcon>

I have been trying to get the _ActualOffset_ of the _Target_ in _Menuflyout_ like below.

_void winrt::MedicalUx::implementation::MainPage::BlowFlyOut_Opened(winrt::Windows::Foundation::IInspectable const& sender, 
    winrt::Windows::Foundation::IInspectable const& e)
{
    Windows::UI::Xaml::Controls::MenuFlyout menuFlyout = sender.as<Windows::UI::Xaml::Controls::MenuFlyout>();
    float targetOffset = menuFlyout.Target().ActualOffset().y;
}_

But I am getting the offset value as zero always.
The same scenario works properly in UWP C# applications.
What am I missing here or is it a known issue?

### Steps to reproduce the bug

1. Create a C++/WinRT project.
2. Place a _BitmapIcon_ in main page XAML.
3. Attach a _MenuFlyout_  to the above _BitmapIcon_
4. Subscribe _MenuFlyout_ _Opened_ event and write a proper handler.
5. Check the _ActualOffset_ value of _MenuFlyout_ _Target_.

        <BitmapIcon UriSource="Assets/MenuBar.png" ShowAsMonochrome="False" x:Name="BitIcon" Tapped="BitIcon_Tapped" Height="72" Width="72">
            <FlyoutBase.AttachedFlyout>
                <MenuFlyout x:Name="BlowFlyOut" Opened="BlowFlyOut_Opened" Placement="Bottom">
                    <ToggleMenuFlyoutItem Text="New"/>
                    <ToggleMenuFlyoutItem Text="Open"/>
                    <ToggleMenuFlyoutItem Text="Save"/>
                    <MenuFlyoutSeparator />
                    <ToggleMenuFlyoutItem Text="Exit"/>
                </MenuFlyout>
            </FlyoutBase.AttachedFlyout>
        </BitmapIcon>

_void winrt::MedicalUx::implementation::MainPage::BlowFlyOut_Opened(winrt::Windows::Foundation::IInspectable const& sender, 
    winrt::Windows::Foundation::IInspectable const& e)
{
    Windows::UI::Xaml::Controls::MenuFlyout menuFlyout = sender.as<Windows::UI::Xaml::Controls::MenuFlyout>();
    float targetOffset = menuFlyout.Target().ActualOffset().y;
}_

### Expected behavior

Should get the actual offset value of object corresponding to the Target.

### NuGet package version

Microsoft.UI.Xaml 2.5.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
@zyont1000 is this issue unique to cppwinrt?

**Comment by zyont1000** [comment]
> @zyont1000 is this issue unique to cppwinrt?

Yes in C# WinRT, we could access that property.
The issue is with C++ WinRT were we cannot access that property .

**Comment by zyont1000** [comment]
In C# WinRT, we could get the actual offset values.
But in C++ WinRT, its always giving value as 0.

**Comment by StephenLPeters** [comment]
@Scottj1s or @kennykerr can you weigh in on possible causes?

**Comment by kennykerr** [comment]
Sorry, nothing comes to mind.
