### ISSUE TITLE
ColumnDefinition with Star sizing and MinWidth leads to clipping

### ISSUE THREAD

**Issue by huynhsontung** [microsoft/microsoft-ui-xaml#6510]
### Describe the bug

Given a `Grid` layout with 2+ columns that all have star sizing, if the first column has `MinWidth` set to a significant value then it is possible to produce clipping when resizing the window. This issue only occurs when the first column has `MinWidth` set.

This bug has even more complicated behavior when interacting with nested `Grid`s (see Screenshots for details).

### Steps to reproduce the bug

The bug can be reproduced using the following layout in a UWP project:

```xml
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*" MinWidth="320" />
        <ColumnDefinition Width="2*" />
    </Grid.ColumnDefinitions>
    <Rectangle
        Grid.Column="0"
        HorizontalAlignment="Stretch"
        VerticalAlignment="Stretch"
        Fill="Firebrick" />
    <Image
        Grid.Column="1"
        HorizontalAlignment="Stretch"
        VerticalAlignment="Stretch"
        Source="/Assets/StoreLogo.png"
        Stretch="Uniform" />
</Grid>
```

Resizing the window will clip the image in the second column.

### Expected behavior

Columns that don't have `MinWidth` set should scale properly without clipping.

### Screenshots

Using the sample layout above, the bug seems to occur once the second column width goes down to 320 * 2 = 640

![zFdjZZYOup](https://user-images.githubusercontent.com/31434093/147039938-c597eb4f-9486-470f-a14a-759b1255d3bf.gif)

When dealing with nested `Grid`s, the bug only occurs when there is not enough space to display everything in the child `Grid`. Using `CommandBar` for example:

![lF18yAlzgD](https://user-images.githubusercontent.com/31434093/147040608-4c8e4192-6d39-405d-9957-9e41e3e1b775.gif)

Another behavior when the `CommandBar` spans across 2 columns

![B4T4jTje2l](https://user-images.githubusercontent.com/31434093/147040748-3f423ba0-e31e-4b54-8691-94a293c79538.gif)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

21H2 (22000.376)

**Comment by StephenLPeters** [comment]
@gegao18 thoughts on whats going on here?
