### ISSUE TITLE
Custom Titlebar blocks interaction with in-app toolbar

### ISSUE THREAD

**Issue by eyalkapah** [microsoft/microsoft-ui-xaml#6515]
### Describe the bug

When implementing a custom toolbar and extend it into the title bar, the in-app toolbar doesn't respond to user interaction and became part of the Titlebar content itself.

### Steps to reproduce the bug

1. Create a new Windows SDK v1 application.
2. Use the following XAML in MainWindow.xaml

 ```
<Grid>
    <StackPanel
        x:Name="TitleBar"
        Grid.Row="0"
        Height="35"
        HorizontalAlignment="Stretch"
        VerticalAlignment="Top"
        Orientation="Horizontal"
        Spacing="15">
        <TextBlock VerticalAlignment="Center" Text="Custom Titlebar Application" />
    </StackPanel>
</Grid>
```

3. Extend the TitleBar in the code behind MainWindow.xaml.cs

```
public MainWindow()
{
    this.InitializeComponent();

    // Custom Title Bar
    ExtendsContentIntoTitleBar = true;

    SetTitleBar(TitleBar);
}
```

### Expected behavior

in-app toolbar should respond to user interaction

### Screenshots

![image](https://user-images.githubusercontent.com/32191482/147219774-1e66704b-4ebd-4c5a-acac-7de7b1019880.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Additional context

Windows version: Windows 11

**Comment by StephenLPeters** [comment]
@pratikone FYI

**Comment by wnstngs** [comment]
With custom title bar minimize, maximize and close buttons very often are not handling mouse events.

**Comment by pratikone** [comment]
Can you upgrade to latest winappsdk release ?  this has been fixed there.

**Comment by luandersonn** [comment]
> Can you upgrade to latest winappsdk release ? this has been fixed there.

Nops, the bug still

**Comment by Kovercrosser** [comment]
Problem still Exits in WinAppSDK 1.2
