### ISSUE TITLE
NavigationView Pane Toggle Button is not aligned properly on first load.

### ISSUE THREAD

**Issue by hassaanmasood** [microsoft/microsoft-ui-xaml#6518]
### Describe the bug

The Pane Toggle Button in NavigationView is not aligned with the rest of the navigation items and back button on the very first load. It is slightly shifted to the right. This issue sometimes also appears in the XAML  Controls Gallery App.

However, on clicking the Pane Toggle Button, it aligns itself properly.

The issue exists with both WinUI3 and 2.x. 

### Steps to reproduce the bug

1. Create a new WinUI3 App or UWP App.
2. Add Navigation View to the Page.

### Expected behavior

The Pane Toggle Button should align itself properly on the first load.

### Screenshots

![BugReportWinUI](https://user-images.githubusercontent.com/58418307/147379276-69e3b3fb-0e6a-4477-8cbf-be811b4ccd30.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by StephenLPeters** [comment]
Present in winui2 as well.  @karenbtlai I think you may have looked into this in the past, right?

**Comment by karenbtlai** [comment]
Yes I have. Let me investigate further.

**Comment by zd-dalibor** [comment]
I have this same issue. The part of toggle pane button on the right side is missing.
![image](https://user-images.githubusercontent.com/226822/206000894-4c0b3311-84b2-4a75-a235-a5b37312de0b.png)
Is thre some temporary fix for this util this bug is fixed?

**Comment by zd-dalibor** [comment]
Quick fix for this is to forse toggle pan button size recalcuation.
Togle size calculation will be trigger when pane title is changed https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/NavigationView/NavigationView.cpp#L3963.

On NaviagtionView load event pan title can be changed, this will recalculate button size
```csharp
private void NavigationView_Loaded(object sender, RoutedEventArgs e) {
    var navigation = (NavigationView)sender;
    navigation.PaneTitle = " ";
    navigation.PaneTitle = "";
}
```

**Comment by hassaanmasood** [comment]
> Quick fix for this is to forse toggle pan button size recalcuation. Togle size calculation will be trigger when pane title is changed https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/NavigationView/NavigationView.cpp#L3963.
> 
> On NaviagtionView load event pan title can be changed, this will recalculate button size
> 
> ```cs
> private void NavigationView_Loaded(object sender, RoutedEventArgs e) {
>     var navigation = (NavigationView)sender;
>     navigation.PaneTitle = " ";
>     navigation.PaneTitle = "";
> }
> ```

Yes, this works. Thanks.
