### ISSUE TITLE
How to extend NavigationView back button properly into Title Bar for WinUI 3 Desktop App?

### ISSUE THREAD

**Issue by hassaanmasood** [microsoft/microsoft-ui-xaml#6519]
With WinUI 3 it is pretty easy to extend the view into TitleBar.  However, aligning NavigationView Back Button on the top left is not working. Doing so causes the title bar buttons to not work/clickable. I have tried setting Canvas.ZIndex property and codes from different sample apps but nothing seems to work for WinUI 3, but they work perfectly with UWP Apps.

It will be great if someone can help.

Here is by UI Code:
	```
<Border x:Name="AppTitleBar"
				IsHitTestVisible="True"
				VerticalAlignment="Top"
				Background="Transparent"
				Margin="48,0,0,0"
				Height="{Binding ElementName=NavigationViewControl, Path=CompactPaneLength}"
				Canvas.ZIndex="1">
			<TextBlock x:Name="AppTitle"  Text="{x:Bind GetAppTitleFromSystem()}"
					   VerticalAlignment="Center"
					   Style="{StaticResource CaptionTextBlockStyle}" />
		</Border>

		<NavigationView Canvas.ZIndex="0"
						x:Name="NavigationViewControl"
						IsTabStop="False"
						IsTitleBarAutoPaddingEnabled="False"
						ItemInvoked="NavigationView_ItemInvoked"
						BackRequested="NavigationView_BackRequested"
						IsSettingsVisible="True"
						IsBackEnabled="{x:Bind AppFrame.CanGoBack, Mode=OneWay}">
			<NavigationView.MenuItems>
				<NavigationViewItem x:Name="CustomerListMenuItem"
									Content="{x:Bind CustomerListLabel}"
									ToolTipService.ToolTip="{x:Bind CustomerListLabel}"
									Icon="ContactInfo" />
				<NavigationViewItem x:Name="OrderListMenuItem"
									Content="{x:Bind OrderListLabel}"
									ToolTipService.ToolTip="{x:Bind OrderListLabel}"
									Icon="Shop" />
			</NavigationView.MenuItems>
			<Frame x:Name="rootFrame"
				   Navigating="OnNavigatingToPage" />
		</NavigationView>
``
![Screenshot 2021-12-25 131042](https://user-images.githubusercontent.com/58418307/147380665-11cb43bb-2f36-4c67-aa5e-267a37d14d85.png)

**Comment by Petrarca181** [comment]
This will foce titlebar always on top. Buttons should work fine. also if covered with some color. 
`<Style TargetType="ContentControl" x:Key="WindowChromeStyle">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="ContentControl">
                            <Grid x:Name="LayoutRoot">
                                <VisualStateManager.VisualStateGroups>
                                    <VisualStateGroup x:Name="CommonStates">
                                        <VisualState x:Name="Normal">
                                            <VisualState.Setters>
                                                <Setter Target="TitleBarMinMaxCloseContainer.Background" Value="{ThemeResource WindowCaptionBackground}" />
                                                <Setter Target="MinimizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MinimizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="MaximizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MaximizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="CloseButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="CloseButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                        <VisualState x:Name="WindowInactive">
                                            <VisualState.Setters>
                                                <Setter Target="TitleBarMinMaxCloseContainer.Background" Value="{ThemeResource WindowCaptionBackground}" />
                                                <Setter Target="MinimizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MinimizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="MaximizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MaximizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="CloseButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="CloseButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                    </VisualStateGroup>
                                </VisualStateManager.VisualStateGroups>
                                <ContentPresenter x:Name="ClientAreaPresenter"
                                    Content="{TemplateBinding Content}"
                                    ContentTemplate="{TemplateBinding ContentTemplate}"
                                    ContentTransitions="{TemplateBinding ContentTransitions}"
                                    Foreground="{TemplateBinding Foreground}"/>
                                <Grid x:Name="TitleBarMinMaxCloseContainer"
                                    HorizontalAlignment="Right"
                                    VerticalAlignment="Top"
                                    Visibility="{Binding CaptionVisibility, RelativeSource={RelativeSource TemplatedParent}}">
                                    <Grid x:Name="MinMaxCloseContainer"
                                        HorizontalAlignment="Right"
                                        VerticalAlignment="Top"
                                        ColumnDefinitions="Auto,Auto,Auto">
                                        <Button x:Name="MinimizeButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Minimize"
                                        AutomationProperties.AutomationId="_MinimizeButton"
                                        Grid.Column="0"
                                        Content="M 0 0 H 10">
                                        </Button>

                                        <Button x:Name="MaximizeButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Maximize"
                                        AutomationProperties.AutomationId="_MaximizeButton"
                                        Grid.Column="1"
                                        Content="M 0 0 H 10 V 10 H 0 V 0">
                                        </Button>
                                        <Button x:Name="CloseButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Close"
                                        AutomationProperties.AutomationId="_CloseButton"
                                        Grid.Column="2"
                                        Content="M 0 0 L 10 10 M 10 0 L 0 10">
                                            <Button.Resources>
                                                <ResourceDictionary>
                                                    <ResourceDictionary.ThemeDictionaries>
                                                        <ResourceDictionary x:Key="Light">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                        <ResourceDictionary x:Key="Dark">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                        <ResourceDictionary x:Key="HighContrast">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                    </ResourceDictionary.ThemeDictionaries>
                                                </ResourceDictionary>
                                            </Button.Resources>
                                        </Button>
                                    </Grid>
                                </Grid>
                            </Grid>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
`

**Comment by Petrarca181** [comment]
This will make titelbar always on top of all elements. Also if some color covers it. 


```<Style TargetType="ContentControl" x:Key="WindowChromeStyle">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="ContentControl">
                            <Grid x:Name="LayoutRoot">
                                <VisualStateManager.VisualStateGroups>
                                    <VisualStateGroup x:Name="CommonStates">
                                        <VisualState x:Name="Normal">
                                            <VisualState.Setters>
                                                <Setter Target="TitleBarMinMaxCloseContainer.Background" Value="{ThemeResource WindowCaptionBackground}" />
                                                <Setter Target="MinimizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MinimizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="MaximizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MaximizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="CloseButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="CloseButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                        <VisualState x:Name="WindowInactive">
                                            <VisualState.Setters>
                                                <Setter Target="TitleBarMinMaxCloseContainer.Background" Value="{ThemeResource WindowCaptionBackground}" />
                                                <Setter Target="MinimizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MinimizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="MaximizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MaximizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="CloseButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="CloseButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                    </VisualStateGroup>
                                </VisualStateManager.VisualStateGroups>
                                <ContentPresenter x:Name="ClientAreaPresenter"
                                    Content="{TemplateBinding Content}"
                                    ContentTemplate="{TemplateBinding ContentTemplate}"
                                    ContentTransitions="{TemplateBinding ContentTransitions}"
                                    Foreground="{TemplateBinding Foreground}"/>
                                <Grid x:Name="TitleBarMinMaxCloseContainer"
                                    HorizontalAlignment="Right"
                                    VerticalAlignment="Top"
                                    Visibility="{Binding CaptionVisibility, RelativeSource={RelativeSource TemplatedParent}}">
                                    <Grid x:Name="MinMaxCloseContainer"
                                        HorizontalAlignment="Right"
                                        VerticalAlignment="Top"
                                        ColumnDefinitions="Auto,Auto,Auto">
                                        <Button x:Name="MinimizeButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Minimize"
                                        AutomationProperties.AutomationId="_MinimizeButton"
                                        Grid.Column="0"
                                        Content="M 0 0 H 10">
                                        </Button>

                                        <Button x:Name="MaximizeButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Maximize"
                                        AutomationProperties.AutomationId="_MaximizeButton"
                                        Grid.Column="1"
                                        Content="M 0 0 H 10 V 10 H 0 V 0">
                                        </Button>
                                        <Button x:Name="CloseButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Close"
                                        AutomationProperties.AutomationId="_CloseButton"
                                        Grid.Column="2"
                                        Content="M 0 0 L 10 10 M 10 0 L 0 10">
                                            <Button.Resources>
                                                <ResourceDictionary>
                                                    <ResourceDictionary.ThemeDictionaries>
                                                        <ResourceDictionary x:Key="Light">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                        <ResourceDictionary x:Key="Dark">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                        <ResourceDictionary x:Key="HighContrast">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                    </ResourceDictionary.ThemeDictionaries>
                                                </ResourceDictionary>
                                            </Button.Resources>
                                        </Button>
                                    </Grid>
                                </Grid>
                            </Grid>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>

**Comment by StephenLPeters** [comment]
@pratikone FYI

**Comment by Sahil12524** [comment]
My Repo: https://github.com/Sahil12524/Windows_Cleanup_WinUI_3
It's Video: https://www.youtube.com/watch?v=3l1JCeVQGPQ
In my case the title bar's textblock is aware of Theme changes.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42999635/3a641c18-b0d3-4b11-893e-f33591c8a027)

**Comment by duncanmacmichael** [comment]
Closing this issue as it appears to have been answered.
