### ISSUE TITLE
`SplashScreen image can be found exception` occurs while try to package the app using single-project MSIX

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#6520]
### Describe the bug

![image](https://user-images.githubusercontent.com/57438309/147413773-d2d9211a-29f1-4657-a70e-d86afae8116e.png)

While we try to convert the `Blank App, packaged with Windows Application Packaging Project` to single `Blank App, packaged` by using the given guidelines in https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp page, it builds the application properly, but cannot be able to launch the application by throws the error.

Note:
If we remove the SplashScreen images assigning tag from `Package.appxmanifest` file, then the application runs properly.

![image](https://user-images.githubusercontent.com/57438309/147414181-ff442a9e-b53e-413c-8f84-71b9ba4ed9ae.png)

### Steps to reproduce the bug

1. Open the [App8.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7777249/App8.zip) sample
2. Build the solution (it's succeed)
3. Try to run the solution
4. Note: It throws the `DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(28,27): error 0x80070003: Cannot install or update package cb0bed1f-136b-48ef-bff6-ecc888319622_0hx8bvsc3x46r because the splash screen image [SplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found` exception.		

### Expected behavior

Application should run without any excpetion,

### Screenshots

![image](https://user-images.githubusercontent.com/57438309/147413520-580a14cc-a9fe-4716-b9bf-ae73929d41bb.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI
