### ISSUE TITLE
WinUI 2.7 crashes XAML Designer and VS on Insider build 22523

### ISSUE THREAD

**Issue by KodWhat** [microsoft/microsoft-ui-xaml#6522]
### Describe the bug

When a project includes WinUI 2.7 and loading a XAML file, VS hangs for a few seconds and then either restarts, closes or freezes.
It occurs only on the latest insider build (22523) and not on the stable build

The issue does not occurs on stable (22000) and with projects without WinUI 2.7 installed

Tested on: 
- My machine: Issue occurs
- Official Win 11 Development Environment VM (stable build): No issue
- Fresh install of build 22523 : Issue occurs
- With VS 2019 and 2022

### Steps to reproduce the bug

1. Create a new UWP project
2. Install WinUI Nuget package version 2.7
3. Add the required lines in App.xaml
4. Go to MainPage.xaml
5. VS should hang then crash
If VS doesn't crash, build the solution and/or close/reopen VS should trigger the crash next time MainPage.xaml is opened

### Expected behavior

VS should not crash
(Or at least, the designer should handle the issue and not crash the entire environment)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by riverar** [comment]
Reproduces on `Windows 11 22523.1000`. This bug is especially terrible because Visual Studio will attempt to re-open the solution automatically and crash again.

**Comment by torchgm** [comment]
Can reproduce on 22518 and 22523; first attempt in VS2022 and VS2019 hung the process indefinitely, any successive attempt to load the XAML designer leads to the aforementioned crash-looping.

**Comment by AlexeyKataev** [comment]
I have a similar problem on this same build. Crash occurs when opening XAML in Visual Studio 2019 or Blend for Visual Studio. In the new settings application on the "Apps - Installed Apps" page, after the preview is displayed in the list of installed applications, a crash occurs. I cannot uninstall any program via the UI. Problems are also present with other WinUI applications.

**Comment by AlexeyKataev** [comment]
> 
[ActivityLog.txt](https://github.com/microsoft/microsoft-ui-xaml/files/7796105/ActivityLog.txt)

https://user-images.githubusercontent.com/53377659/147821915-4f9e850e-9ab3-46ae-b5c7-8ba71aea5717.mp4

https://user-images.githubusercontent.com/53377659/147821996-31935c6e-3620-4974-8ede-6844382c6563.mp4

**Comment by muznyo** [comment]
Happens on build 22526 too

**Comment by dongle-the-gadget** [comment]
Can reproduce on both 22523 and 22526, had to disable XAML Designer to get IntelliSense for XAML files without VS crashing.

**Comment by muznyo** [comment]
> Happens on build 22526 too

After updating to build 22533, XAML designer stopped crashing the Visual Studio so I assume it's fixed.

**Comment by evelynwu-msft** [comment]
This should be reported through Visual Studio's [Send Feedback](https://developercommunity.visualstudio.com/report?entry=problem) menu option.

**Comment by kmahone** [comment]
I tried out this scenario on a recent build of Windows 11 (22621) and was unable to reproduce the problem. It appears that the issue in the OS has been resolved.
