### ISSUE TITLE
Run and deploy Unpackaged app on Windows 11 does not work.

### ISSUE THREAD

**Issue by Petrarca181** [microsoft/microsoft-ui-xaml#6523]
Hello, I followed the tutorial from Microsoft site to  run and publish  unpackaged  winui 3 desktop app.  On windows 10 everything works fine., but on windows 11 app just does not start.  Everything is identical on both systems.  I only noticed one thing  after installing Microsoft.WindowsAppRuntime.1.0.msix on win11 if I try to launch it again I should see "reinstall"  button. but there is  "install" button like nothing was installed before.

Any suggestions?

**Comment by StephenLPeters** [comment]
@MikeHillberg @ryandemopoulos thoughts?

**Comment by Scottj1s** [comment]
@Petrarca181 I do see the symptoms you describe - an Install button displayed on second run.  Despite this, the package was successfully installed on the first run.  If your concern is only with the button label, we can move this issue to a more appropriate home.
