### ISSUE TITLE
GridView button click to new page frame 

### ISSUE THREAD

**Issue by SPG-144** [microsoft/microsoft-ui-xaml#6525]
### Describe the bug

       C# UWP
  
       xaml 
      <Grid>
        <GridView HorizontalAlignment="Center" VerticalAlignment="Center">
            <GridViewItem x:Name="Mine">
                <Button x:Name="Test" Click="Test_Click" Width="70" Height="70" Background="Green"/>
            </GridViewItem>
        </GridView>
    </Grid>

        cs   
        private void SomeButton_Click(object sender, RoutedEventArgs e)
        {
            _ = Frame.Navigate(typeof(Page1));
        } 
This does not work when nested in a gridview it only gives a debug error
The same combination works in a Grid, and stackpanel but not in a GridView
DebugSettings.BindingFailed += (sender, args) =>
UnhandledException += (sender, e) =>
 

### Steps to reproduce the bug

Place button with click for navigating to another page in a gridview and it will not work

### Expected behavior

Simple page / frame navigation

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/96801843/147617832-b429b807-62ac-4e77-abb7-f57052b7a97c.png)

### NuGet package version

WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by StephenLPeters** [comment]
@SPG-144 your markup defines the click handler as Test_Click but the code has SomeButton_Click, is that the issue?

**Comment by SPG-144** [comment]
Hi Stephen
The problem is this:
The button_Click to a  Frame.Navigate(typeof(Page));  command  inside a GridView element it does not work, and comes up with the error code that I posted.
If you install this same scenario in a StackPanel or a Frame or anything else the button click to page navigation works. this does not make any sense.

Try it out for yourself set up an Mvvm template with 2 pages install from the nuget the Microsoft.UI.Xaml 2.8.0-Prerelase update for the UI then on page 1 install a GridView, then install a button inside the GridView element with a new click event handler,  then In the xaml.cs set up the frame.navigate to page2 then build it and it will not work.
Thank you for looking into this.
Scott

**Comment by StephenLPeters** [comment]
Can you clarify what you mean by does not work?  Is there a crash, or is just nothing happening? if you set a breakpoint in the event handler is the call to frame.navigate occuring?

**Comment by SPG-144** [comment]
Hi Stephen
Simply put:
Using the Microsoft Visual studio 2019 -2022 Mvvm template with and simple navigation between 2 pages.
In my application I have one page with several buttons that navigate to different pages
These buttons are nested in a ***GridView*** With the NuGet Microsoft Win.Ui.Xaml  2.5.0 version the button click function works to navigate to the desired pages.
When I updated to the Win.Ui.Xaml   to the 2.8.0 preview version I get a debugger message. Look at the attachment pic.
