### ISSUE TITLE
Unwanted spacing and overlap issues around drop-down in MS ComboBox control in 125 and 175 scaling

### ISSUE THREAD

**Issue by SubashiniMahendran** [microsoft/microsoft-ui-xaml#6531]
### Describe the bug

Unwanted spacing and overlap issues around drop-down and border element in MS ComboBox control in 125 and 175 scaling. Please find the sample regarding it below:
[ComboBox-UI-issue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7792687/ComboBox-UI-issue.zip)

### Steps to reproduce the bug

1. Change the system scaling to 125 or 175.
2. Run the application.
3. Press the drop down icon, don`t release the mouse press.

Note: Unwanted spacing and overlap issues around drop-down icon in MS ComboBox control in 125 and 175 scaling.

### Expected behavior

Unwanted spacing and overlap issues around drop-down icon in MS ComboBox control should not occur in 125 and 175 scaling.

### Screenshots

**Issue not reproducing scaling:**

100 scaling:

![image](https://user-images.githubusercontent.com/92976485/147747965-f9bda2e1-6a7d-4074-980f-94ac5172abfc.png)

150 scaling:

![image](https://user-images.githubusercontent.com/92976485/147747737-0eb027e8-9382-46be-b59f-af0bb2a34902.png)

**Issue reproducing scaling:**

125 scaling:

![image](https://user-images.githubusercontent.com/92976485/147747895-34fd6a1f-c5f4-4c79-afad-734b6a057e84.png)

175 scaling:

![image](https://user-images.githubusercontent.com/92976485/147747843-d2b27424-516b-41b4-a025-672569230fd5.png)

### NuGet package version

WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

**Note:** I have custom control with similar MS ComboBox control UI contained in project reunion 0.8.3.

**Comment by StephenLPeters** [comment]
@gegao18 and @codendone this is a pixel snapping issue. This issue has come up a lot and I wonder if we could consider a more wholistic solution than twiddling the numbers in Winui3.
