### ISSUE TITLE
The type or namespace name 'TabViewAddTabButtonClickArgs' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by ChasTechProjects** [microsoft/microsoft-ui-xaml#6532]
### Describe the bug

I'm trying to create a TabView as laid out in the guide [here.](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.tabview?view=winui-3.0) I have added the TabView to my MainWindow.xaml however when I try to paste the C# code into MainWindow.xaml.cs, I get told that TabViewAddTabButtonClickArgs could not be found.

Here is the code in particular causing issues:
`private void Tabs_AddTabButtonClick(TabView sender, TabViewAddTabButtonClickEventArgs e)`

Here is the error:
`The type or namespace name 'TabViewAddTabButtonClickArgs' could not be found (are you missing a using directive or an assembly reference?)`

Pressing Alt + Enter does not give any helpful suggestions.

The rest of the code in the guide does not appear to have any issues.

### Steps to reproduce the bug

1. Create a new project in Visual Studio 2022 as C# and Blank App packaged.
2. Paste the code found [here](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.tabview?view=winui-3.0) into the respective files.
3. The IDE should say there is 1 error, which will be the one in the title.

### Expected behavior

IDE should show no errors and the program should compile successfully.

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by castorix** [comment]
You can see with VS and Intellisense that the parameters are :
`(TabView sender, object args)`

**Comment by StephenLPeters** [comment]
Your code says TabViewAddTabButtonClick**Event**Args but the error message says TabViewAddTabButtonClickArgs, do you have a typo?
