### ISSUE TITLE
Converter for Button style in UWP is not working properly in code behind 

### ISSUE THREAD

**Issue by vijayarasan** [microsoft/microsoft-ui-xaml#6533]
have tried to fully code behind display control in the UWP application. While Applying Style in Button control I need to use the Converter for apply style in Button control. But Unfortunately Converter not triggered for Button Control.

Here is my attempt to recreate it in CodeBehind, but it is unfortunately not working.

``` C#

//create converter instance
 var converterInstance = new BoolToColorConverter();
 //add the converter to window resources
 this.Resources.Add("BoolToColorConverter", converterInstance);


 Binding myBinding = new Binding();
 myBinding.Converter = (BoolToColorConverter)this.Resources["BoolToColorConverter"];
 myBinding.Mode = BindingMode.TwoWay;
 myBinding.UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged;
 Style buttonStyle = new Style(typeof(Button));
 buttonStyle.Setters.Add(new Setter(Button.BackgroundProperty, myBinding));

 Button button = new Button();
 button.Width = 150;
 button.Height = 50;
 button.Content = "Hello";
 button.Style = buttonStyle;
 parent.Children.Add(button);

```

Screenshot for your reference,
![CodeBehindConverter](https://user-images.githubusercontent.com/58214164/147808523-00ab2260-ea54-4c1d-9f18-57e35ab7c577.png)

I have attached a sample for your reference.

**Sample Link:** [CodeBehindinConverter.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7795521/CodeBehindinConverter.zip)

If I missed anything in this code behind.

Can you provide how to code-behind Converter for Style applied in Button Control as targetType in UWP platform?

Note: My requirement is needed to apply Style using converter in mentioned target type via code behind in UWP Platform

Note: Can you please provide any working solution to achieve the Converter in code behind for Style applied in Button Control?

Regards,
Vijayarasan S

**Comment by StephenLPeters** [comment]
@vijayarasan do you have to put the converter into the page resources if your creating and setting it from code?  @RealTommyKlein is vijayarasan missing something?

**Comment by RealTommyKlein** [comment]
I think the issue is the use of a `Binding` in a Style Setter, which isn't supported; see the docs here: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.setter?view=winrt-22000#migration-notes

Is it possible for the converter to run before applying the Setter/Style, and setting the outcome of the converter as the Setter's value instead of a `Binding`?
