### ISSUE TITLE
InputKeyboardSource.GetKeyStateForCurrentThread(VirtualKey.Shift) returns CoreVirtualKeyStates.Locked after the shift key has already been released

### ISSUE THREAD

**Issue by WelterDevelopment** [microsoft/microsoft-ui-xaml#6535]
### Describe the bug

The `Shift` key behaves exactly like the `Caps Lock` key. Pressing (and releasing) it once sets its key state to CoreVirtualKeyStates.Locked and pressing (and releasing) it again sets it to CoreVirtualKeyStates.None. But what I want is that the key state is always None when `Shift` is unpressed and `Caps Lock` is off. 

Since InputKeyboardSource.GetKeyStateForCurrentThread() is in the Microsoft.UI Namespace, I guess it is a WinUI (3) related issue?

### Steps to reproduce the bug

- Open a new WinAppDSK 1.0 C# WAP template
- Replace the StackPanel in MainWindow.xaml with:
``` xaml
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
  <TextBox x:Name="myTextBox" KeyDown="myTextBox_KeyDown" IsTabStop="True" Text="&#x9;This is some text that is indented by a tab character."></TextBox>
</StackPanel>
```
- Add this to MainWindow.xaml.cs:
``` csharp
private void myTextBox_KeyDown(object sender, KeyRoutedEventArgs e)
{
  if (e.Key == Windows.System.VirtualKey.Tab)
  {
    e.Handled = true;
    Windows.UI.Core.CoreVirtualKeyStates shiftkey = Microsoft.UI.Input.InputKeyboardSource.GetKeyStateForCurrentThread(Windows.System.VirtualKey.Shift);
    
    if (shiftkey != Windows.UI.Core.CoreVirtualKeyStates.None)
    {
      if (myTextBox.Text.StartsWith('\t'))
        myTextBox.Text = myTextBox.Text.Remove(0, 1);
    }
    else
    {
      myTextBox.Text = myTextBox.Text.Insert(0,"\t");
    }
  }
}
```
- Build, deploy and run the app
- Play around with the `Tab` Key and the `Shift`+`Tab` combination, without(!) `Caps Lock`. You will see that the insertion and removal of the tab character will happen quite randomly
- My understanding from what I tested is that pressing the `Shift` key once leads to a permanent CoreVirtualKeyStates.Locked state. Pressing the `Shift` key again leads to a permanent CoreVirtualKeyStates.None state. That is exactly how the `Caps Lock` Key itself shoud work, but not the `Shift` key!

### Expected behavior

InputKeyboardSource.GetKeyStateForCurrentThread(Windows.System.VirtualKey.Shift) should always return Windows.UI.Core.CoreVirtualKeyStates.None when the `Shift` key is not pressed and when `Caps Lock` is off.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Testet on 21H2 (22000.376) stable

**Comment by StephenLPeters** [comment]
@WelterDevelopment the CorVirtualKeyStates uses a flags enum (https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corevirtualkeystates?view=winrt-22000) so that every key can behave similarly to the caps lock key where pressing it once puts you into the locked state.  In order to check for none vs down results (ignoring the locked state) you should bitwise & your result with the enum value you are checking against.  You can see an example here: https://github.com/microsoft/microsoft-ui-xaml/blob/7168b0b4dd2392aab6a186b1d3539b43f73a94f2/dev/RadioButtons/RadioButtons.cpp#L106
