### ISSUE TITLE
Discussion: Keyboard navigation for ItemsControl

### ISSUE THREAD

**Issue by saravanan-2112** [microsoft/microsoft-ui-xaml#6537]
I'm using ItemsControl with the ItemsWrapGrid panel. The arrow key navigation is not working to navigate between the items of the ItemsControl. 

Is that any other control that has arrow key navigation?

How can we achieve arrow key navigation?

Please refer to the attached demo,

[ItemsControl_KeyboardNavigation.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7802209/ItemsControl_KeyboardNavigation.zip)
 
Code:

        <ItemsControl HorizontalAlignment="Center" VerticalAlignment="Center">
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                    <ItemsWrapGrid Orientation="Horizontal" MaximumRowsOrColumns="4"/>
                </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
        </ItemsControl>

**Comment by WelterDevelopment** [comment]
Yes, it seems that you can only navigate via the tab key, which is (afaik) handled by the Window. You should use an abstraction like ListView that handles keyboard navigation by itself. I think what you want is:

``` xaml
 <ListView HorizontalAlignment="Center" VerticalAlignment="Center" SelectionMode="None">
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <Button Margin="5" Content="Item"/>
            <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                    <ItemsWrapGrid Orientation="Horizontal" MaximumRowsOrColumns="4"/>
                </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
</ListView>
```

**Comment by Jaiganeshkumaran** [comment]
@WelterDevelopment Not needed. Set these properties on your container to get arrow key navigation: `TabFocusNavigation="Once" XYFocusKeyboardNavigation="Enabled"`. It even works for a StackPanel.

**Comment by WelterDevelopment** [comment]
@Jaiganeshkumaran Nice! Thats good to know :)

**Comment by saravanan-2112** [comment]
@WelterDevelopment @Jaiganeshkumaran your suggestions are working fine.

@Jaiganeshkumaran TabFocusNavigation has an option for "Cycle" navigation. Is that any way to do the same for arrow keys (cyclic navigation)? I have tried but didn't get any solution.

**Comment by StephenLPeters** [comment]
@saravanan-2112 there are many xyfocus navigation api's.  You could use the Control.XYFocusDown and Control.XYFocusUp api's to accomplish this.  Im sure there are other ways too.  https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.xyfocusdown?view=winrt-22000
