### ISSUE TITLE
BodyLarge TextBlock style is missing 

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#6539]
### Describe the bug

As described in the documentation [type ramp](https://docs.microsoft.com/en-us/windows/apps/design/style/typography#type-ramp), the body strong style is missing from WinUI 3

### Steps to reproduce the bug

Try to add a style for textblock

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
@codendone FYI
