### ISSUE TITLE
WinUI 3 doesn't show in VS2022 XAML designer?

### ISSUE THREAD

**Issue by mingtong** [microsoft/microsoft-ui-xaml#6540]
### Describe the bug

I am using VS 2022 Pro on Windows 11.
I've installed WinUI 3 with extension from the link https://aka.ms/windowsappsdk/stable-vsix-2022-cs .
After I create a blank WinUI project with a MainWindow.xaml, the XAML designer cannot display the window, neither Blend, only xaml source code is showing.
Am I missed something?

### Steps to reproduce the bug

1, Create a blank WinUI3 project.
2, Double click on MainWindow.

### Expected behavior

MainWindow is showed in designer.

### Screenshots

MainWindow show is showed in source code window.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by pjmlp** [comment]
You are missing that WinUI 3.0 doesn't support the designer, they expect us to use hot code reloading instead.

https://github.com/microsoft/microsoft-ui-xaml/issues/5917

**Comment by gabbybilka** [comment]
Thanks for your feedback, as @pjmlp noted, the current discussion around the XAML designer is centralized in this issue: #5917 Closing this issue as the lack of designer is currently expected in VS2022.

**Comment by CAKCy** [comment]
Please read and act accordingly!

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7456966/7f950b63-7462-413d-9611-734eee4c48fc)

The link again:
https://developercommunity.visualstudio.com/t/Feature-request-Visual-designer-for-Wi/1608476?q=WinUI+Designer

Oh! And SPREAD THE WORD! 
PLEASE!
