### ISSUE TITLE
visual studio 2022 preview 1.1 error winui3 kernalbase.dll

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6542]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/visual-studio-2022-preview-11-error-win/1617958)._

---
[severity:It bothers me. A fix would be nice]

winui3 latest preview

error info: 

Exception thrown at 0x00007FFCD25C478C in FireBrowserUwp.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000327A17D850.

file:
C:\Windows\System32\KernelBase.dll

10.0.22000.348 (WinBuild.160101.0800)

note it appears randomly when following the steps :

make tabs render page with add button and close the app with tabs sometimes gives the error randomly 
<local:renderpage <name of page > as first page to render name: own choice

---
#### Feedback Bot on 12/20/2021, 05:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Dolly Wang [MSFT] on 12/21/2021, 01:06 AM: 

<p>Thanks for your feedback. We’re unable to reproduce it using a simple project in our side,  Does this issue just occur in specific project? For us investigate this further, could you provide a sample project that we can reproduce your issue? As you mentioned it appears randomly, how about the frequency?<br>
We look forward to hearing from you!</p>

#### jarno beerten on 12/21/2021, 01:29 AM: 

(private comment, text removed)
#### jarno beerten on 12/21/2021, 01:33 AM: 

<p><a target='_blank' href="https://aka.ms/dc/file?name=B2732afc96591408cb2c45123e5024481637756758040067659_FireBrowserUwp.zip&amp;tid=2732afc96591408cb2c45123e5024481637756758040067659">FireBrowserUwp.zip</a></p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=Bf9418ce335df4e4d833ae9415cfb3eab637756759544571902_error.png&amp;tid=f9418ce335df4e4d833ae9415cfb3eab637756759544571902">error.png</a></p>
<p>open mutible tabs and close all tabs and then close the app</p>

#### Feedback Bot on 12/21/2021, 10:44 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jarno9981** [comment]
I can confirm latest beta build windows fixes the  kernelbase.dll issue for my project
