### ISSUE TITLE
Discussion: Build failure in single-project MSIX projects

### ISSUE THREAD

**Issue by dhanushkumar-kumar** [microsoft/microsoft-ui-xaml#6545]
# Discussion: Build failing when build the single package app throw msbuild.

I have created the WINUI 3 project in my visual studio. And. Then modified this project as single project as per the below mentioned guidelines. Now, trying to build this .csproj file using MsBuild.exe on cmd. 

single package guileliness : https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp

Sample : 
[WAPP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7813667/WAPP.zip)

**Command : C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin>MSBuild.exe "D:\1\WAPP\WAPP.csproj" /p:Configuration=Release;Platform=x86**

![build-failure](https://user-images.githubusercontent.com/93641001/148189311-ba0a88e7-3dcd-4f61-9eb5-e2752a0475ea.png)

I have builded this sample in visual studio and tried to build this same .csproj using msbuild.exe. Now, Build was passed.

![passed-build](https://user-images.githubusercontent.com/93641001/148189588-d5b81c49-8bda-48a0-ad12-e325a8401175.png)

As I checked with the changes in sample bin folder, When build on visual studio dll's  will be generate in this path **D:\1\WAPP\bin\x86\Release\net5.0-windows10.0.19041.0\win10-x86**  As like in the below screenshot.

![image](https://user-images.githubusercontent.com/93641001/148189955-98be0947-e7f9-462c-8b23-4f551f9b653b.png)

If I run this project file directly on msbuild it will not generate any dll's in **D:\1\WAPP\bin\x86\Release\net5.0-windows10.0.19041.0\win10-x86** and **ref/[ProjectName].dll.**

![directonmsbuild](https://user-images.githubusercontent.com/93641001/148192152-37008278-799d-4f41-95c8-71a3b3e7c778.png)

If I build the project with having the above all dll's and ref/[ProjectName].dll in bin folder, I could build this project successfully. These dll's are not generating when build directly in **msbuild*. It will only generate when we build with Visual studio.

## Machine configuration

Edition	: Windows 10 Pro
Version	: 20H2
Installed on :	‎06-‎03-‎2021
OS build	: 19042.1415
Experience :	Windows Feature Experience Pack 120.2212.3920.0

## Visual studio configuration

Microsoft Visual Studio Professional 2019 Preview
Version 16.11.8 Preview 1.0

Microsoft .Net Framework
Version 4.8.04084

## Related Links

https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp

**Comment by evelynwu-msft** [comment]
The build error states: `Assets file 'D:\1\WAPP\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.`

Did you first restore the project's Nuget packages before building it on the command line with `msbuild`? Visual Studio automatically does this for you when building but when building on the command line you need to do it manually before the first build.
