### ISSUE TITLE
NavigationView "LeftMinimal" pane mode issue on Windows 10.0.17763

### ISSUE THREAD

**Issue by steam3d** [microsoft/microsoft-ui-xaml#6547]
### Describe the bug

1. When resize window to small size (when LeftMinimal pane mode turns on) the "back" icon changes size to the large.
2. When restart the app (when LeftMinimal pane mode is enabled), the app loads with open pane. You must click to icon burger to reopen the pane and fix the issue.

Source code:
[NavView.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7814079/NavView.zip)

Microsoft.UI.Xaml 2.7.0 and preview 2.8.0 have this issue.

### Steps to reproduce the bug

1. Open the app
2. Resize windows to the smallest size

### Expected behavior

The "back" icon does not change its size.
The pane does not open when the app starts.

### Screenshots

https://user-images.githubusercontent.com/30986874/148200508-0e30e263-cbae-4042-b4cd-2d970982c564.mp4
<video src='https://user-images.githubusercontent.com/30986874/148200508-0e30e263-cbae-4042-b4cd-2d970982c564.mp4' />

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2018 Update (17763)

**Comment by StephenLPeters** [comment]
@karenbtlai I thought we resolved this issue? is this a corner case we didn't catch?

**Comment by karenbtlai** [comment]
I thought we did as well. I can investigate into this.
