### ISSUE TITLE
WinUI Design Toolkit Bug: Dark dialogs of the maximum size have offset smoke

### ISSUE THREAD

**Issue by SecondThundeR** [microsoft/microsoft-ui-xaml#6548]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:** Dialog

**Describe the bug:** The dark dialog variant with the maximum size have offset smoke that go beyond the dialog component frame *(This also applies to the Single Button variant)*

![image](https://user-images.githubusercontent.com/36604233/148244787-a5e73b50-d38c-40f0-8fa2-0ee0772dd8ff.png)
*Light Variant*

![image](https://user-images.githubusercontent.com/36604233/148244849-cdda43cc-7f64-4d89-9195-9188aa893e6d.png)
*Dark Variant*

**Version Info:** 2.7 (11.16.21)

**Additional context:** This can be fixed by moving the smoke to the dialog component

![image](https://user-images.githubusercontent.com/36604233/148245008-5fa06579-b7a6-48be-8587-d2e60e1d8943.png)
*Fixed Variant Example*

**Comment by alejo4000** [comment]
Thanks for flagging that, @SecondThundeR ! That fix will be in the next published update of the toolkit.
