### ISSUE TITLE
Bound NavigationViewItem Icon crashes on the 4th Bound Icon

### ISSUE THREAD

**Issue by Daniellled** [microsoft/microsoft-ui-xaml#6549]
### Describe the bug

Assume a main window page has a NavigationView that is bound to an observable collection. In the data template the NavigationViewItem Icon property is bound to a SymbolIcon data object.

Example of broken Window/Page
```
<Window
    x:Class="NavigationViewSample.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NavigationViewSample"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Grid.Resources>
            <DataTemplate x:Key="NavigationViewMenuItem" x:DataType="local:NavigationViewModel">
                <!-- This does not work -->
                <NavigationViewItem Content="{x:Bind Header}" Icon="{x:Bind MenuIcon}" />
            </DataTemplate>
        </Grid.Resources>
        <Button Content="Add Navigation Item" Grid.Row="0" Click="Button_Click"/>
        <NavigationView Grid.Row="1" x:Name="NavView" MenuItemsSource="{x:Bind MenuItems}"  MenuItemTemplate="{StaticResource NavigationViewMenuItem}" >
            <Frame x:Name="RootFrame"></Frame>
        </NavigationView>
    </Grid>
</Window>
```

Example of broken data model
```
    public class NavigationViewModel
    {
        public string Header { get; set; }

        /*
         * This does not work
         */ 
        public SymbolIcon MenuIcon { get; set; }

        public Type Type { get; set; }
    }
```

MainWindow constructor populating data model/observable collection

```
        public MainWindow()
        {
            this.InitializeComponent();
            NavView.SelectionChanged += NavView_SelectionChanged;
            MenuItems = new ObservableCollection<NavigationViewModel>();
            MenuItems.Add(new NavigationViewModel() { Header = "Account", MenuIcon = new SymbolIcon(Symbol.Account), Type = typeof(Views.Account));
            MenuItems.Add(new NavigationViewModel() { Header = "Admin", MenuIcon = new SymbolIcon(Symbol.Admin), Type = typeof(Views.Admin));
            MenuItems.Add(new NavigationViewModel() { Header = "Phone", MenuIcon = new SymbolIcon(Symbol.Phone), Type = typeof(Views.Phone));
            //When below line is uncommented application crashes- i.e when Collection is loaded with more 3 items only crash happens
            MenuItems.Add(new NavigationViewModel() { Header = "Mail", MenuIcon = new SymbolIcon(Symbol.Mail), Type = typeof(Views.Mail));

        }
```

If you comment out the line 

`            MenuItems.Add(new NavigationViewModel() { Header = "Mail", MenuIcon = new SymbolIcon(Symbol.Mail), Type = typeof(Views.Mail));`

everything works fine. But when you add the 4th element into the list an exception is thrown

> System.ArgumentException
>   HResult=0x80070057
>   Message=Value does not fall within the expected range.
>   Source=WinRT.Runtime
>   StackTrace:
>    at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
> 

For some reason it only throws the exception after the 4th element is added to the collection. 3 elements are fine.

### Steps to reproduce the bug

1. Download the zip file
2. Run the application

[NavigationViewSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7816901/NavigationViewSample.zip)

### Expected behavior

A developer should be able to bind to an already created SymbolIcon object or any IconElement.

### Screenshots

With 4 elements

![image](https://user-images.githubusercontent.com/83433189/148267020-1ef24ae0-8207-45be-96ea-396dc8ce416a.png)

Working with only 3 elements

![image](https://user-images.githubusercontent.com/83433189/148267113-ec5c65d3-3231-4c60-9fbb-1ea020d0c04c.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
IconElements are UIElements, which can be parented in the visual tree.  UIElements cannot have multiple parrents and an exception will be thrown if you try to add them in multiple places.  This is what we created IconSource for, to have a sharable object that can create IconElements for cases like this.

**Comment by StephenLPeters** [comment]
The view model contains unique symbol icons so I don't think this is a case of multiparenting the icon..  @RealTommyKlein is there something wrong with the generated code for the x:bind?

**Comment by RealTommyKlein** [comment]
@StephenLPeters - this is the multiparent icon issue (same callstack) - I suspect this is virtualization related.  When the 4th entry for `Mail` is present for some reason the navigation view reapplies the 3rd entry, `Phone`, after applying `Mail`.  Not sure if it's worth duping this to #6496 (more info/workaround in [this comment](https://github.com/microsoft/microsoft-ui-xaml/issues/6496#issuecomment-1068087993)), or leaving it up as a separate virtualization-specific issue.
