### ISSUE TITLE
Uses old Reveal effect from RS4 instead of using the new more subtle 19H1 Reveal effect.

### ISSUE THREAD

**Issue by christoph-fer** [microsoft/microsoft-ui-xaml#655]
The Reveal effect is noticeably different when WinUI Nuget package isn't installed - It uses the new 19H1 reveal effect as expected where the border reveal radius is smaller. But when I install the WinUI nuget package, the reveal effect is noticeably different - It uses the old 1809 reveal style, where the border reveal radius is larger.

### **Demonstration:**

**Old 1809 reveal style with WinUI installed on 19H1 Build:**

(the border reveal radius is large)

![Old 1809 Reveal Style](https://user-images.githubusercontent.com/39899690/57174962-facbf900-6e63-11e9-9a50-f7dae1511ac8.gif)

**New 19H1 reveal style without WinUI installed on 19H1 Build:**

(the border reveal radius is smaller)

![New 19H1 Reveal Style](https://user-images.githubusercontent.com/39899690/57174969-03bcca80-6e64-11e9-9a6e-3b0850932a6d.gif)

**Comment by jevansaks** [comment]
This doesn't seem like an intentional difference, but the code does have quite a bit of conditionals for the windows build so it's possible there's a bug there. We'll take a look.

**Comment by codendone** [comment]
As mentioned above, the Reveal code is different in the Windows build from WinUI, but the visual appearance is supposed to be the same.  There have not been any intentional changes in appears since RS4.  Definitely a bug.
