### ISSUE TITLE
ComboBox dropdown / flyout opens in the wrong location when using certain RelativePanel attached properties

### ISSUE THREAD

**Issue by blake-fm** [microsoft/microsoft-ui-xaml#6554]
### Describe the bug

When using RelativePanel.LeftOf in the default tutorial as per repro, the dropdown / flyout left edge is anchored exactly 69px (not kidding) from the right edge of the ComboBox control.

When using RightOf, or no attached properties, left aligns to left as normal.

Other RelativePanel properties also change the alignment, e.g. AlignHorizontalCenterWith myButton halves the effect.  Didn't measure that one, but it's a reasonably safe bet.

### Steps to reproduce the bug

1. Follow the [WinUI 3 Unpackaged template steps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-unpackaged-csharp)
2. Replace the StackPanel and its content with
```
    <RelativePanel>
        <Button x:Name="myButton"
                RelativePanel.AlignVerticalCenterWithPanel="True"
                RelativePanel.AlignHorizontalCenterWithPanel="True"
                Click="myButton_Click">Click Me</Button>
        <ComboBox RelativePanel.LeftOf="myButton"
                  RelativePanel.AlignVerticalCenterWithPanel="True"
                  SelectedIndex="1">
            <ComboBoxItem Content="Test item" />
            <ComboBoxItem Content="A reasonably long item" />
            <ComboBoxItem Content="A significantly longer item.  It's really, relly long.  Too long, maybe." />
        </ComboBox>
    </RelativePanel>
```
3. Observe the whackiness

### Expected behavior

Using RelativePanel attached properties have on their own no effect on the ComboBox, other than positioning the control in its flyout closed state.

### Screenshots

LeftOf:
![image](https://user-images.githubusercontent.com/89286531/148350921-7fd9cf0c-d47f-494f-9717-1cc6175e27b2.png)
![image](https://user-images.githubusercontent.com/89286531/148350941-329e9d20-3181-4c6d-b409-7f8fbbfd60a3.png)

RightOf / no attached properties:
![image](https://user-images.githubusercontent.com/89286531/148351125-944dee72-364b-4232-b800-6c66858c059d.png)
![image](https://user-images.githubusercontent.com/89286531/148351137-18578aa6-d1ee-4f1a-a167-b8bbc85a2500.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Screenshots are Win 11, also repro'd on 19043.

**Comment by StephenLPeters** [comment]
@ranjeshj FYI
