### ISSUE TITLE
Question: What's the difference between the WinUI API and Platform API

### ISSUE THREAD

**Issue by maidamai0** [microsoft/microsoft-ui-xaml#6563]
I noticed there are some APIs both in the SDK and the windows UI API, such as [NavigationView](https://docs.microsoft.com/en-us/windows/apps/design/controls/navigationview)

Is there any difference between them, which one should I use?

**Comment by castorix** [comment]
There is either the [UWP version](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview?view=winrt-22000) or the [WInUI version](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.navigationview?view=winui-3.0)

**Comment by maidamai0** [comment]
@castorix Thank you!
The **UWP** version is just a **WinRT** API in the **SDK** so it can be used in C++ code. **WinUI3** can be used in C++ code directly with **Xaml Islands**. So my question is what's the difference between them? Why do I prefer one to the other?

**Comment by mdtauk** [comment]
UWP/Platform API is the older system that is bundled with Windows, and used to receive updates as the Windows versions updated.

WinUI 3/WinAppSDK is the beginning of an effort to separate the API from Windows, so it can be updated at a different pace and timing, and is not tied to Windows directly.  It is an on-going process and some parts of WinUI 3 are still missing, and to use those, you have to use the UWP versions (Media Player, Map Control, etc)

**Comment by Jaiganeshkumaran** [comment]
> @castorix Thank you! The **UWP** version is just a **WinRT** API in the **SDK** so it can be used in C++ code. **WinUI3** can be used in C++ code directly with **Xaml Islands**. So my question is what's the difference between them? Why do I prefer one to the other?

For controls that are in both WinUI and the platform XAML, use the WinUI version since the platform XAML version hasn't been updated in a while.
