### ISSUE TITLE
ComboBoxes are clipped by container

### ISSUE THREAD

**Issue by terrycox** [microsoft/microsoft-ui-xaml#6565]
### Describe the bug

ComboBoxes, when expanded, are sometimes clipped by the lower boundaries of their window with no ScrollBar showing. See the first screenshot. If an expanded Combobox's items all fit in the container, it displays properly.

In other cases the scrollbar displays, but the expanded area is the window's lower bounds and not all items in the ItemSource list display. See the second screenshot.

When the ComboBox expands upward it sometimes has a transparency issue. See the third screenshot.

The items displayed are always in alphabetic order. Some ComboBoxes uses are fine with the ordering.  Others are not, such as the examples shown. These are 'ranges'. For example, Self-Assurance ranges from Timid to Cocky. The sorting destroys the range order.

### Steps to reproduce the bug

Launch StoryBuilder (in GitHub in the storybuilder-org repository.)

Open the Snow White sample.
Select the Evil Queen Character story element in the Navigation Pane.
Scroll to the Inner Traits tab.
Click on the down arrow keys on the Sociability, Stability, Shrewdness, and Conscientiousness controls to demonstrate these behaviors.

### Expected behavior

Well-bounded ComboBoxes, extended either downward or upward based on available space, with a vertical ScrollBar displayed if not all items fit, with no transparency issues, and with the ItemsSource sort order preserved.

### Screenshots

![image](https://user-images.githubusercontent.com/5607778/148764033-84d1431e-46a8-4b0b-9823-273dbc1225dc.png)

![image](https://user-images.githubusercontent.com/5607778/148764071-2cb85213-5398-4378-978b-e376b30ee010.png)

![image](https://user-images.githubusercontent.com/5607778/148764112-776aa913-c440-4bac-b1df-e7b61dd62a79.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

This is on Windows 11 Pro 21H2 (Build 22000.376)

**Comment by terrycox** [comment]
Checking if this has been looked at

**Comment by codendone** [comment]
This issue is caused by the flyout positioning code of ComboBox assuming that IsConstrainedToRootBounds="False" is supported. Since that isn't yet functional in WinUI3, this problem can result.
