### ISSUE TITLE
File activation does not work for single instance app

### ISSUE THREAD

**Issue by PaulTaro** [microsoft/microsoft-ui-xaml#6566]
I have a single instance game app using DISABLE_XAML_GENERATED_MAIN with the recomended implementaion of Program.cs. If I try file activation, the app crashes before calling OnLaunched. If a run my app as multi-instance, file activation works as expected.
Here is the screenshot of the crash:

![image](https://user-images.githubusercontent.com/49974414/148771365-7d78fd05-f143-41e2-8da7-2f9bc8557c12.png)

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI
