### ISSUE TITLE
WebView2 does not work with WindowsAppSdk and Windows 1809

### ISSUE THREAD

**Issue by Finnur** [microsoft/microsoft-ui-xaml#6568]
### Describe the bug

We're using WebView2 with the WindowsAppSdk but on Windows 1809 (Version 17763) it crashes since EnsureCoreWebView2Async fails
It works on later versions of Windows and it works using the WebView2 Preview for WinUI2.

It's a clean set up machine with the WebView2 Standalone Runtime and Microsoft Edge installed

The error in the event log says:
Activation context generation failed for "C:\Users\user\AppData\Local\Packages\.....\LocalCache\Local\Microsoft\EdgeWebView\Application\96.0.1054.62\msedgewebview2.exe". Dependent Assembly 96.0.1054.62,language="&#x2a;",type="win32",version="96.0.1054.62" could not be found. Please use sxstrace.exe for detailed diagnosis.

### Steps to reproduce the bug

Create a new WindowsAppSdk project
Add Webview2 to the view
Call "EnsureCoreWebView2Async" on the WebView
The CoreWebView2 prperty will still be null and there will be an erro in the event viewer

### Expected behavior

It works on other versions of windows so I'd expect it to work on 1809 as well

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 1809 (17763, October 2018 Update)

### IDE

Visual Studio 2022-preview

**Comment by krschau** [comment]
Reopening for investigation.

**Comment by Finnur** [comment]
Is there any news on this?
