### ISSUE TITLE
Unexpected exception in the output at app start

### ISSUE THREAD

**Issue by kamilgrygiel** [microsoft/microsoft-ui-xaml#6575]
### Describe the bug

There are unexpected exceptions in the output related to WinUI Package project.
It occurs when in Project properties -> Debug -> Debugger type -> Application process `Mixed` or `Native` is selected. When I change it to Managed only type there are no exceptions but it also reduces output.

### Steps to reproduce the bug

1. Set in Project properties -> Debug -> Debugger type -> Application process `Mixed` or `Native`
2. Start project
2. In the output you'll see exceptions like `Exception thrown at 0x00007FFAB7644F69 ... 0x40080202: WinRT transform error...`

### Expected behavior

There are no unexpected exceptions in the output

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
This isn't going to meet our bar for investigation for a long time.
