### ISSUE TITLE
TwoPaneView disabling virtualization of child elements

### ISSUE THREAD

**Issue by zateutsch** [microsoft/microsoft-ui-xaml#6578]
### Describe the bug

A ListView placed inside of a TwoPaneView loses the ability to virtualize items. It appears to me that this occurs because the leftmost pane of the TwoPaneView has gridcolumn width of [Auto](https://github.com/microsoft/microsoft-ui-xaml/blob/1bc21ec356d021d8552259fbe1378a3a3346933d/dev/TwoPaneView/TwoPaneView.xaml#L86), which would prevent virtualization.

### Steps to reproduce the bug

1. Place a ListView with a large amount of items within Pane1 of a TwoPaneView.
2.  Run app
3.  ListView loads all elements in Visual Tree with no virtualization.

```xml
<TwoPaneView>
    <TwoPaneView.Pane1>
        <ListView ItemsSource="{x:Bind Items}" Grid.Column="0">
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="local:ListItem">
                    <TextBlock Text="{x:Bind text, Mode=TwoWay}"/>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </TwoPaneView.Pane1>
</TwoPaneView>
```

### Expected behavior

ListView virtualizes items.

### Screenshots

![Visual tree with all list view items](https://user-images.githubusercontent.com/88554871/149066350-c3afe34c-b144-4819-b655-7763f8e0b3c6.png)
All 1000 ListView items are loaded.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
I'm not sure the reason provided is correct.  I don't think that the horizontal column width specification would affect vertical virtualization.  This is not going to meet our bar for investigation, but perhaps someone from the community has investigated and found the solutions in the past.

**Comment by Marv51** [comment]
I looked into this issue some more, interestingly it seems to be related to the way that TwoPaneView initalizes itself: 

In the example @zateutsch provided above, the issue goes away if you set the ListView as `Visibility="Collapsed"`, then in the TwoPaneView.Loaded event you set the Visibility back to visible.

I think this is related to the height of the first row (`m_rowTop`) of the RootGrid of the TwoPaneView.

In the ControlTemplate it is set to Star, however the `c_pane1LengthDefault` is set to `GridUnitType::Auto` here: https://github.com/microsoft/microsoft-ui-xaml/blob/9052972906c8a0a1b6cb5d5c61b27d6d27cd7f11/dev/TwoPaneView/TwoPaneView.h#L14

Here this value gets applied (only in some modes): 
https://github.com/microsoft/microsoft-ui-xaml/blob/9052972906c8a0a1b6cb5d5c61b27d6d27cd7f11/dev/TwoPaneView/TwoPaneView.cpp#L213

I think that the control first renders in a top bottom mode (with pane1 height set to auto) before it changes automatically to a left right mode. 

Could someone more familiar with the idl and c++ world find way to fix this?

@StephenLPeters with this information, could you please consider this issue again ?

**Comment by Marv51** [comment]
I think this is still important (re #8638)

**Comment by kmahone** [comment]
This behavior is a consequence of how the layout system works. Since the size of the ListView is not being constrained, it will size to all the available space which results in everything getting devirtualized. To ensure that ListView virtualization continues to work it is best to set a MaxWidth and MaxHeight on the control to constrain its size.
