### ISSUE TITLE
Use customize main entry point instead of auto generated main build failed with WMC999 Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Dingshouqing** [microsoft/microsoft-ui-xaml#6579]
### Describe the bug

Add customized Main entry point to load App instead of autogenerated code, after change build project failed and show below error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	WMC9999	Object reference not set to an instance of an object.	TestBasePackageTool	.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.UI.Xaml.Markup.Compiler.interop.targets	616	

### Steps to reproduce the bug

1. Set App.xmal Build Action to "Page"
![3](https://user-images.githubusercontent.com/17266569/149080300-c626a1a8-749c-45ad-89e8-e6bfa34fb9b7.png)
2. Add Main entry point as below
 ![2](https://user-images.githubusercontent.com/17266569/149080133-cc5266ac-1dd7-4398-91d8-ae6fbc5663aa.png)
3. Set Startup object to newly added entry point
4. Build project and get blow failed mesage
![1](https://user-images.githubusercontent.com/17266569/149080046-4f7c34f3-bb81-43cc-ac63-66fd1c18aece.png)

### Expected behavior

could build success and launch windows after run

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by StephenLPeters** [comment]
@fabiant3 and @evelynwu-msft is this supported?

**Comment by bogdan-patraucean** [comment]
Have you added this to your .csproj file?
```
        <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
		<DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
		<DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
		<DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|arm64'">
		<DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|arm64'">
		<DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
	</PropertyGroup>
```
I did something similar to achieve single instancing and for me it's working.
