### ISSUE TITLE
Combobox not showing properly in RTL direction

### ISSUE THREAD

**Issue by vijayarasan** [microsoft/microsoft-ui-xaml#6580]
### Describe the bug

I have ContentControl and loaded the ComboBox as Content. The first time loaded the large number of items contain Items to ComboBox.  After opening the dropdown it's properly showing. After, I have set the ContentControl as Null and Again set the ComboBox with small items containing ItemsSource to ComboBox. now, opening the dropdown its shows previously loaded Items popup height with newly loaded items. The popup Height is not loaded based on items in the ItemsSource of ComboBox. The reported problem only occurs in the **RightToLeft** direction.  In the Same scenario with the **LeftoRight** direction the reported problem does not occur.

### Steps to reproduce the bug

Step 1: Run the sample

Step 2: Click the FirstComboBox button to display the Combobox in ContentControl

Step 3: Open the DropDown. The popup height properly loaded based on Items in ComboBox

Step 4: Click the Content Button

Step 5: Click the SecondComboBox button to display the Combobox in ContentControl. Open the DropDown.

**Observed Behavior:** 
 The popup height is not properly loaded based on Items in ComboBox in the RTL direction.
 
The reported problem shows below mentioned screenshot,
![DropDownIssue](https://user-images.githubusercontent.com/58214164/149125978-1150818f-a82f-44fe-a4bb-f059e39079d6.png)

 
 **Note:** The reported problem does not occur while using the **LeftToRight** flow direction.

I have attached the sample for your reference

**Sample Link :** [RTLIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7853920/RTLIssue.zip)
 

### Expected behavior

The popup height should be properly loaded based on Items in ComboBox in the RTL direction.

The Popup will be shown below mentioned screenshot,
![DropwSownShowingProper](https://user-images.githubusercontent.com/58214164/149126266-05d494fa-1b5d-41cf-b5c9-55dcf1b04fa6.png)

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by StephenLPeters** [comment]
The UI you've posted looks like WPF UI (which I verified by looking at the added project.) This issue should be redirected there. https://github.com/dotnet/wpf  @chrisglein could you transfer this issue?

**Comment by chrisglein** [comment]
> The UI you've posted looks like WPF UI (which I verified by looking at the added project.) This issue should be redirected there. https://github.com/dotnet/wpf @chrisglein Chris Glein FTE could you transfer this issue?

I think you're looking for @fabiant3, not me. Anyway, GitHub issue transfer doesn't work cross organization (e.g. from `microsoft` to `dotnet`), so I don't believe you can do a simple move. It'll need to be recreated.

**Comment by vishalmsft** [comment]
The issue has been created and tracked in WPF repo dotnet/wpf/issues/5946
