### ISSUE TITLE
Access Denied to start any process

### ISSUE THREAD

**Issue by LazieWouters** [microsoft/microsoft-ui-xaml#6581]
### Describe the bug

I can't launch any app because the code below shows this error: _System.ComponentModel.Win32Exception: 'Access Denied'_

var process = Process.Start(@"C:\foo.exe"); 

### Steps to reproduce the bug

Try open any executable in your OS with
var process = Process.Start(@"C:\path_of_the_app.exe")   

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by Marv51** [comment]
You checked the UWP app type checkbox. Is that correct? In that case you can't start processes outside of you applications own executables, because of the sandboxed app model.

**Comment by StephenLPeters** [comment]
@Marv51 is correct, this is not supported from a UWP.
