### ISSUE TITLE
work work `NavigationView` WinUI` only MSIX published

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6584]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/work-work-NavigationView-WinUI-only-M/1511044)._

---
In Release or Debug there are no problems.
It only happens after MSIX deployment.

Project Reunion 0.8.2

at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
    at ABI. Microsoft.UI.Xaml.IApplicationStatics.global::Microsoft.UI.Xaml.IApplicationStatics.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
    at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)

x64 published

---
#### Feedback Bot on 8/23/2021, 02:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/2/2021, 06:58 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
The info provided isn't enough to be actionable, so I'm closing the issue. If the original author is present feel free to provide more info and we can reopen.
