### ISSUE TITLE
TreeView SelectionChanged Event Missing After Upgrade

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6585]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/TreeView-SelectionChanged-Event-Missing-/1547961)._

---
[severity:It's more difficult to complete my work]
The Treeview SelectionChanged Event is missing after upgrading Microsoft.WindowsAppSDK to 1.0.0-preview2

---
#### Feedback Bot on 10/7/2021, 07:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Enbi Zhang [MSFT] on 10/12/2021, 00:44 AM: 

<p>Thanks for your feedback!<br>
What’s the type of your project?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### William Kline on 10/12/2021, 10:28 AM: 

(private comment, text removed)
#### Feedback Bot on 10/13/2021, 02:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
The TreeView SelectionChanged event is a preview API which means that it is only included in versions of the package that are compiled as preview versions.   @MikeHillberg is the windows app sdk version 1.0.0.previewX not actually a preview package?

**Comment by StephenLPeters** [comment]
@codendone and @llongley FYI

**Comment by lukaszzielnica** [comment]
When SelectionChanged event is about to leave preview API?
It's been two years since this feature is completed... (https://github.com/microsoft/microsoft-ui-xaml/pull/2063).

**Comment by SamChaps** [comment]
It would be great if the SelectionChanged could leave the preview API. My team has been using the SelectionChanged for a while now.
