### ISSUE TITLE
ContextMenu View Code option is not available for MainWindow.xaml and App.xaml in WinUI 3 Project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6586]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ContextMenu-View-Code-option-is-not-avai/1548971)._

---
[severity:It's more difficult to complete my work]
ContextMenu View Code Option is not available for MainWindow.xaml and App.xaml in WinUI 3 Project

! [Untitled2.png] (https://aka.ms/dc/image?name=Bba2652d424574c5c88bc876d0e0e18d8637693142112665920_Untitled2.png&tid=ba2652d424574c5c88bc876d0e0e18d8637693142112665920)

! [Untitled.png] (https://aka.ms/dc/image?name=B8b96f4ec81674be2b9f2ea970759d36f637693141975467821_Untitled.png&tid=8b96f4ec81674be2b9f2ea970759d36f637693141975467821)

---
#### Feedback Bot on 10/8/2021, 07:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Paul Wang [MSFT] on 10/11/2021, 02:55 AM: 

<p>Does the ContextMenu view code option refer to ‘view code’ in the following figure?<br>
<img src="https://aka.ms/dc/image?name=B579311953d5a40928a298402ccb619c5637695430403896240_ViewCode.png&amp;tid=579311953d5a40928a298402ccb619c5637695430403896240" alt="ViewCode.png"></p>

#### Mahdi Hosseini on 10/11/2021, 10:50 PM: 

<p>yes, but is not available in WinUI 3 Project only in MainWindows.xaml and App.xaml</p>

#### Paul Wang [MSFT] on 10/12/2021, 11:05 PM: 

<p>Can you provide me with a simple winui 3 project template？</p>

#### Mahdi Hosseini on 10/12/2021, 11:59 PM: 

<p>I also noticed that this menu is available when the project loads but hides after a few seconds</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=Bc07e0bbc3bf74ec980f858da2d852582637697051456651760_App11.zip&amp;tid=c07e0bbc3bf74ec980f858da2d852582637697051456651760">App11.zip</a></p>
<p><img src="https://aka.ms/dc/image?name=B6bf45e23a1014b12b13dc75b783f6605637697051715603467_Animation.gif&amp;tid=6bf45e23a1014b12b13dc75b783f6605637697051715603467" alt="Animation.gif"></p>

#### Feedback Bot on 10/14/2021, 07:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@evelynwu-msft or maybe @MikeHillberg any idea why this isn't working with these files for Winui3?
