### ISSUE TITLE
Can't create My First WinUI Desktop App

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6588]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-create-My-First-WinUI-Desktop-App/1595735)._

---
I tried to follow this link:
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-packaged-csharp

In Step 3 I don't find an option "Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop)", only "Blank App, Packaged (WinUI 3 in Desktop)" and "Class Library (WinUI 3 in Desktop)". Having no choice, I selected "Blank App, Packaged (WinUI 3 in Desktop)". 
1. The generated solution has 2 projects, according to the the description, I expected no packaging project.
2. Got 2 Warnings in the error list:
Warning	WMC9999	Type universe cannot resolve assembly: Microsoft.InteractiveExperiences.Projection, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.	App13	C:\Users\User\source\repos\App13\App13\App13\MainWindow.xaml	1	
Warning	MSB4181	The "CompileXaml" task returned false but did not log an error.	App13	C:\Users\User\.nuget\packages\microsoft.projectreunion.winui\0.8.4\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets	341
3. In Step 7 "Enable deployment for your project in Configuration Manager" it's not possible to click the deploy check box.
4. Build with 2 errors.

Windows 11, Visual Studio 2022 17.0.1, all Desktop and Mobile workloads (5) installed, MSIX Packaging Tools installed, Windows 11 SDK installed
Two weeks ago, I could create a WinUI Desktop App.

---
#### Feedback Bot on 11/25/2021, 09:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Johannes Kleinz solved on 11/25/2021, 00:04 PM, 0 votes: 

<p>Install  Single-Project MSIX  Packaging Tools</p>

**Comment by StephenLPeters** [comment]
@evelynwu-msft sounds like either vsix issues or possibly documentation issues. Can you weigh in?
