### ISSUE TITLE
vs17.1prv1:  GraphicsControls.Sample.WinUI fails

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6589]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/vs171prv1:--GraphicsControlsSampleWin/1582772)._

---
Github get https://github.com/dotnet/Microsoft.Maui.Graphics.Controls
load in
Build OK
Deploy fails with the error shown

---
#### Thomas Giebink on 11/13/2021, 10:59 AM: 

<ul>
<li>
<pre><code>  $exception	{&quot;Unable to create a wrapper object. The WinRT object 2303813027232 has type Microsoft.UI.Dispatching.DispatcherQueue which cannot be assigned to type Microsoft.UI.Dispatching.DispatcherQueue&quot;}	System.ArgumentException
</code></pre>
</li>
</ul>
<ul>
<li>
<pre><code>  Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  HResult	-2147024809	int
  HelpLink	null	string
</code></pre>
</li>
<li>
<pre><code>  InnerException	null	System.Exception
  Message	&quot;Unable to create a wrapper object. The WinRT object 2303813027232 has type Microsoft.UI.Dispatching.DispatcherQueue which cannot be assigned to type Microsoft.UI.Dispatching.DispatcherQueue&quot;	string
  ParamName	null	string
  Source	&quot;WinRT.Runtime&quot;	string
  StackTrace	&quot;   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)\r\n   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)\r\n   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)\r\n   at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)\r\n   at Microsoft.UI.Dispatching.DispatcherQueue.FromAbi(IntPtr thisPtr)\r\n   at ABI.Microsoft.UI.Dispatching.DispatcherQueue.FromAbi(IntPtr thisPtr)\r\n   at ABI.Microsoft.UI.Dispatching.IDispatcherQueueStatics.global::Microsoft.UI.Dispatching.IDispatcherQueueStatics.GetForCurrentThread()\r\n   at Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread()\r\n   at GraphicsControls.Sample.WinUI.Program.&lt;&gt;c.&lt;Main&gt;b__0_0(ApplicationInitializationCallbackParams p) in C:\\Users\\giebi\\Source\\Repos\\Microsoft.Maui.Graphics.Controls\\src\\GraphicsControls.Sample\\GraphicsControls.Sample.WinUI\\obj\\Debug\\net6.0-windows10.0.19041\\win-x64\\Platforms\\Windows\\App.g.i.cs:line 27\r\n   at ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.&lt;&gt;c__DisplayClass10_0.&lt;Do_Abi_Invoke&gt;b__0(ApplicationInitializationCallback invoke)\r\n   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)\r\n   at ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr p)&quot;	string
</code></pre>
</li>
<li>
<pre><code>  TargetSite	{T CreateRcwForComObject[T](IntPtr, Boolean)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
</code></pre>
</li>
<li>
<pre><code>  Static members		
</code></pre>
</li>
<li>
<pre><code>  Non-Public members		
</code></pre>
</li>
</ul>

#### Feedback Bot on 11/14/2021, 10:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@jfversluis I think this issue should have been directed to https://github.com/dotnet/Microsoft.Maui.Graphics.Controls repro instead of our repro. I'm going to close this as external but you may want to open an issue on your end.

**Comment by jfversluis** [comment]
Similar issue already on the right repo here: https://github.com/dotnet/Microsoft.Maui.Graphics.Controls/issues/96
