### ISSUE TITLE
Feature: Rounded corners

### ISSUE THREAD

**Issue by chrisglein** [microsoft/microsoft-ui-xaml#659]
Tracking item for ensuring our control adequately set supports rounded corners (CornerRadius > 0).

* Basic Input
  * Button
  * DropDownButton
    - [x] and Flyout
  * SplitButton
    - [x] and Flyout
  * Slider
    - [x] thumb
    - [x] track
    - [x] filled track
  - [x] Checkbox
  - ToggleButton
  - ToggleSplitButton
* Collections
  * Multi-select
    - [ ] Multi-select list items
    - [x] Multi-select TreeView
    - [ ] Multi-select GridView (larger checkbox rounding)
  - [x] FlipView
* Dialogs & Flyouts
  * Dialogs
  - [x] Flyouts
* Text
  * TextBox
  * PasswordBox
  - [x] AutoSuggestBox
    - [x] and Flyout (only bottom corners)
  * RichEditBox
* Scrolling
  - [x] Panning scrollbar
* Status & Information
  * ProgressBar
  - [x] Tooltips
  - [x] TeachingTip
* Menus & toolbars
  - [x] CommandBarFlyout
  * MenuFlyout
  - [x] MenuBar flyout
* NavigationView
  - [x] Selected item pill/fry
* Pivot
  - [x] Selected item underline
* Pickers
  * ComboBox
    * box
    - [x] flyout (only bottom corners, box bottom removed)
  * DatePicker
    - [x] box
    - [x] flyout
  * CalendarDatePicker
    * box
    - [x] flyout
  * CalendarView
 * TimePicker
    - [x] box
    - [x] flyout
  * ColorPicker
    - [x] main picker
    - [x] preview
    - [x] slider
    - [x] input boxes
* MediaPlayer
  - [x] track
- [x] [Tab Control](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fmicrosoft-ui-xaml%2Fpull%2F629%23issuecomment-490701816&data=01%7C01%7Ccglein%40microsoft.com%7C3d99ec29cf8a4e855c9608d6d417bd97%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=lf4TSXbUZXEXQORLDaDVZBT0e7Od%2FkxM0uNDWyJiogY%3D&reserved=0)

**Comment by duke7553** [comment]
Another obvious example of no **CornerRadius** support I noticed was the AutoSuggestBox.

**Comment by chigy** [comment]
@chrisglein , I don't think CalendarView needs any change?

**Comment by chigy** [comment]
@chrisglein , here are some items that were missing from the list.

- Pivot - selection bar
- Media player - Tooltip (it should get by the work on Tooltip but being precise)
- Time Picker - Is this included in Date Picker?
- Toggle Button - Is this part of button?
- ToggleSplitButton - Is this part of split button?
- Web view - I don't know if slider there needs separate work

**Comment by chrisglein** [comment]
> Pivot - selection bar

Good catch. Added to the list.

> Media player - Tooltip (it should get by the work on Tooltip but being precise)

This one doesn't use a different tooltip type, does it? As long as it's a vanilla ToolTip it should be covered.

> Time Picker - Is this included in Date Picker?

Neglected to have that on my list (even though I had to do work to fix it). No, this isn't covered by DatePicker - they're separate. I just missed this one when referencing the figma page. Added now.

> Toggle Button - Is this part of button?

Worth calling out separately. I'll add it.

> ToggleSplitButton - Is this part of split button?

Probably? I'll add it to be explicit.

> Web view - I don't know if slider there needs separate work

Which slider? Do you mean scrollbars?

**Comment by chrisglein** [comment]
> @chrisglein , I don't think CalendarView needs any change?

CalendarView seemed to work as is. I don't think we need to change it based on what I'm seeing.

**Comment by chigy** [comment]
@chrisglein , 
To make sure that Media player 

- gets it for free, would you at least test it to make sure?
- Sorry, yes, Webview question was about scrollbars.

**Comment by saniyamazmanova** [comment]
Is it possible to get corner radius values for the items on the list?

**Comment by mdtauk** [comment]
> > @chrisglein , I don't think CalendarView needs any change?
> 
> CalendarView seemed to work as is. I don't think we need to change it based on what I'm seeing.

When placed as a control it should use the 2px corner radius right?  4px when used as a flyout?

**Comment by kaiguo** [comment]
> Is it possible to get corner radius values for the items on the list?

The default values are 2 for controls and 4 for overlays. https://github.com/microsoft/microsoft-ui-xaml-specs/pull/32/files#diff-7e5bdf641a5e75aa9cef33ea78c49a71

**Comment by kaiguo** [comment]
> > > @chrisglein
> > >             
> > >             Chris Glein
> > >             FTE , I don't think CalendarView needs any change?
> > 
> > 
> > CalendarView seemed to work as is. I don't think we need to change it based on what I'm seeing.
> 
> When placed as a control it should use the 2px corner radius right? 4px when used as a flyout?

Correct, CalendarView has 2px CornerRadius, and it gets 4px radius when used inside the CalendarDatePicker Flyout.

**Comment by kaiguo** [comment]
There's a separate issue #1096 tracking ListviewItem and GridViewItem updates after WinUI 3. Closing this one.
