### ISSUE TITLE
project.assets.json not found (again!)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6591]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/projectassetsjson-not-found-again/1530296)._

---
[severity:I'm unable to use this version]
Hi I've been trying whole day to specify the error but gave up. I've hit the above error, NETSDK 1004 "Assets file 'C:/Users/pass/to/project.assets.json' not found. ...."
I've added VS Extension 'Project Reunion (0.8.3)', 'C++/WinRT (2.0.210913)', 'Single-project MSIX Packaging Tools for  VS 2019 (0.9.10)' (all those are the newest by today) with VSIX package.
Then I try to compile just generated project by the templates of 
(1) C#-Windows-Desktop and,
(2) C++-Windows-Desktop of,
"Blank App, Packaged (WinUI3 in Desktop)".
Both solution has generate two projects. One is for application the other is Package. I compile them and get compile error;
(a)both of (Desktop) and (Package) project for (1), and
(b) only (Package) Project for (2).
All error message is the same one NETSDK 1004. 
First, I'm using Japanese version of Windows 10 and VS2019Pro is also Japanese version. So I change VS to English version (16.11.3) but it does not work.
The templates are NOT "Experimental" ones. I guess 'Single-project MSIX Packaging Tools for  VS 2019 (0.9.10)' or 'Project Reunion (0.8.3)' is doing something bad because I had made some C++/WinRT programs in former days and I update 'Project Reunion' today.

One another problem. Searching FAQ with keyword, "project.assets.json" returns too many answers to look over.

---
#### Feedback Bot on 9/16/2021, 02:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### yasnori yamada on 9/27/2021, 08:15 PM: 

<p>Has no one hit the same issue? Please teach me the correct version combination of VSIX packages.<br>
Or does the Project Reunion stop working by Win11?</p>

#### yasnori yamada on 9/28/2021, 06:38 PM: 

<p>So, I realize now the WindowsAppSDK includes WinUI. Then I uninstall whole VisualStudio 2019 Pro, re-install it cleanly then add only C++/WinRT and WindowsAppSDK[1.0.0-Experimental] VSIX packages. As result, the NETSDK 1004 error on Package project was disappeared but still remain C# project. Though the message says “Run a NuGet package restore to generate this file.”, it does not work because the error comes from VSIX and the WindowsAppSDK is not available in NuGet.<br>
After all;<br>
Situation changed that the error still remain on C# project on “[Experimental] Blank App, Packaged with WAP (WinUI3 in Desktop)” template.<br>
As for C++/WinRT with WinAppSDK, the NETSDK 1004 error disappeared with “{Experimental] Blank App, Packaged with WAP (WinUI3 Desktop)” template.</p>

#### Angela Zhang [MSFT] on 9/29/2021, 04:51 PM: 

(private comment, text removed)
#### yasnori yamada on 9/30/2021, 01:35 AM: 

<p>I still stack in this issue. I almost giving up going with VS. WinUI3’s environment is too buggy and time consuming. In git, are there same issue reported?<br>
The reason why I ask here is that Microsoft product’s support page guide here. (The issue occurs in VS2019 Pro, then I wanted to ask official support first there are no such support team.)</p>
<p>I rechecked MS WinUI3 explanation and now I understand there are three kind of WinUI3 VSIX packages released simultaneously.<br>
(1) stable version “Project Reunion”<br>
(2) preview version “Windows App SDK”<br>
(3) experimental version “Windows App SDK experimental”<br>
With this three VSIX and two language (C++ and C#) I’ve cross checked.<br>
Both of (1) and (3) occurs NETSDK 1004 error (in “Desktop with Package” template). Only (2) does not generate it. There seems wrong system variable definitions in getting MS resources.</p>
<p>Because I’m in hurry to evaluate WinUI3, I start with (2).</p>

#### Angela Zhang [MSFT] on 9/30/2021, 10:48 AM: 

(private comment, text removed)
#### Feedback Bot on 1/4/2022, 00:01 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI
