### ISSUE TITLE
VS 2022 Preview 5 does not have option for WinUI 3 project to target Windows 11 22000 SDK

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6592]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-Preview-5-does-not-have-option-f/1555045)._

---
VS 2022 Preview 5 does not have any options for WinUI 3 app to target the latest version of Win 11 22000 SDK , despite having the SDK installed.

! [image.png] (https://aka.ms/dc/image?name=B7447cc91329b495b8dd17c8d5ef31f45637698710526992138_20211014-220412-image.png&tid=7447cc91329b495b8dd17c8d5ef31f45637698710526992138)

! [image.png] (https://aka.ms/dc/image?name=B36021c35b713431ba4a66e3169e15da3637698710661443291_20211014-220425-image.png&tid=36021c35b713431ba4a66e3169e15da3637698710661443291)

Repo steps:

Installs latest version of Windows App SDK (Project Reunion), create a blank app/project, right click on project -> properties.

---
#### Feedback Bot on 10/15/2021, 00:53 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI, is this expected?
