### ISSUE TITLE
Question: How to get the installation location of a C++ Win32 WinUI 3.0 app as a string

### ISSUE THREAD

**Issue by ackh** [microsoft/microsoft-ui-xaml#6597]
In the UWP app that I'm attempting to port over to WinUI I need to load files that are part of the UWP app package as an array/vector of individual bytes. The UWP C++ code that I'm using to do so looks as follows:

````cpp
std::vector<char> MyApp::ReadFileFromStorageFolder(const std::wstring& relativePath)
{
  path filePath = path{ winrt::Windows::ApplicationModel::Package::Current().InstalledLocation().Path().data() } / path{ relativePath };

  std::ifstream inputFileStream(filePath, std::ios::binary | std::ios::ate);
  std::ifstream::pos_type pos = inputFileStream.tellg();

  std::vector<char> result(pos);
  inputFileStream.seekg(0, std::ios::beg);
  inputFileStream.read(&result[0], pos);

  return result;
}
````

I'm not sure what to do with the `InstalledLocation` property because calling that property simply never returns when running the WinUI app with that code. It just blocks the UI thread forever.

Is that an API that is actually intended to work within WinUI? If not, is there a corresponding new API that I could use?

The end goal is simply to read binary files bundled together with the app as soon as the app starts. It is perfectly sufficient to do this synchronously because the file sizes are measured in single digit kilobytes.

**Comment by Marv51** [comment]
If you are running as a unpackaged app `Pachage.Current` seems to be unsupported, according to the [release notes](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel) 

From the release notes:
> Known issues for WinUI applications without MSIX-packaging (unpackaged apps):
> Some APIs require package identity and are not supported in unpackaged apps, such as:
[...]
> Package.Current

**Comment by sylveon** [comment]
You can use [QueryFullProcessImageName](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-queryfullprocessimagenamew) to get the location of the .exe file, then just throw that into `std::filesystem::path` and call `.parent_path()` to get the folder path

**Comment by StephenLPeters** [comment]
@MikeHillberg thoughts?
