### ISSUE TITLE
XamlCompiler can't resolve reference

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#660]
Reproducing project attached.  Main feature of interest is that SharpDX.Direct2D1 NuGet package has PrivateAssets=&quot;Compile,&quot; which causes the XamlCompile task to not recieve a reference during build and report an error.  Normally, though, for C Sharp compile this is fine.  Is this a bug or is this the expected behavior?

To repro:
*Unzip project
*Open solution from command line
*Build in Visual Studio

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/307562/xamlcompiler-cant-resolve-reference.html
VSTS ticketId: 660460_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by danzil** [comment]
I've reactivated the VS developer community issue because this is not a Xaml Compiler issue. If the compile task does not receive the right references, that points to a UWP project system issue and not the task itself.
