### ISSUE TITLE
FontIcon doesn't respect IsTextScaleFactorEnabled="True"

### ISSUE THREAD

**Issue by samyun** [microsoft/microsoft-ui-xaml#6608]
### Describe the bug

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.fonticon.istextscalefactorenabled?view=winrt-22000 indicates that FontIcon, being derived off Windows.UI.Xaml.Controls, should resize based on system text scaling if it's enabled. It does not. 

### Steps to reproduce the bug

Set `IsTextScaleFactorEnabled="True"` on a `FontIcon`.

### Screenshots

![image](https://user-images.githubusercontent.com/4411707/149594869-67fe94bd-f881-4814-b928-2a89c7cfc057.png)

### Windows app type

- [ ] UWP
- [ ] Win32

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
We use this property all over the code base like here: https://github.com/microsoft/microsoft-ui-xaml/blob/d7b8e9bf27e1e79512582297cf10fd2ba548bcab/dev/Breadcrumb/BreadcrumbBar.xaml#L331.  In those cases I'm confident it does work.  Can you provide more info  on what you've done for that screenshot? markup as well as what version of winui you are using.

**Comment by codendone** [comment]
The `FontIcon` control specifically forces IsTextScaleFactorEnabled="False" on the TextBlock it creates to draw the icon. (This happens in CFontIcon::ApplyTemplate.) Because of this, setting IsTextScaleFactorEnabled="True" on it has no effect, which is wrong.

**Comment by samyun** [comment]
What Michael said - the attribute works for TextBlock, but not for FontIcon. This has been like this since at least Windows 10 TH1, and probably earlier.
