### ISSUE TITLE
Moving App.xaml to folder in UWP project breaks build.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#661]
VSF_TYPE_MARKDOWN
In Visual Studio 2019 SP3, I have a Universal Windows App, started from a template.  It builds fine.

I have created a &quot;UI&quot; folder, and moved &quot;MainPage.xaml&quot; (and associated .cs file) into the UI folder.   The build is still fine.

But when I move App.xaml (and associated .cs file) the build breaks -- see attached image -- with errors on both App.xaml and MainPage.xaml.

Also, the output only complains about 1 thing: &quot;Application main file must be named App.xaml&quot;, not the 21 errors shown in the attachment.

Moving App.xaml back into the root folder &quot;fixes&quot; the problem.

I have since learned that in this app type, App.xaml MUST be in the root.   That's fine, but I still believe the 21 extra errors are indicative of a bug, especially how the output and errors windows are not in agreement.  Hopefully this problem report helps!

Thanks!
-Eric.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/502906/moving-appxaml-to-folder-in-uwp-project-breaks-bui.html
VSTS ticketId: 826365_
_These are the original issue comments:_

Visual Studio Feedback System on 3/24/2019, 07:06 PM (42 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by danzil** [comment]
We fixed this issue in the upcoming version of the Windows SDK and it is also fixed in WinUI 3.0 Alpha that we just released for preview today.

**Comment by danzil** [comment]
We fixed this issue in the upcoming version of the Windows SDK and it is also fixed in WinUI 3.0 Alpha that we just released for preview today.
