### ISSUE TITLE
MediaPlayer in frame server mode quite limited and has some bugs so cannot be used as a full replacement for MediaPlayerElement

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#6610]
I am actually using UWP (not WinUI 3). However, I imagine this might be relevant when you come to implement media elements for WinUI 3.

The first issue I'd like to report is that numerous users of my app have experienced videos getting stuck when playing using MediaPlayer and MediaPlayerElement. This can happen if MediaPlayer is re-used for lots of videos or if you try to play more than one video at once in separate windows. I haven't reproduced this myself, but this was my motivation for trying to write my own version of MediaPlayerElement by using MediaPlayer in frame server mode. Here is a list of issues I encountered.

1. MediaPlayer.RenderSubtitlesToSurface does not work. I tried it using a CanvasRenderTarget and it worked occasionally but then crashed then app (bypassing and exception handlers). I tried it using the approach suggested on this page - https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/play-audio-and-video-with-mediaplayer - and it simply threw an InvaildArgumentException or something like that. Here is a sample project. 
[VideoFrameServerTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7875344/VideoFrameServerTest.zip). I have had to implement my own subtitle rendering using Win2D (which wasn't actually as painful as I thought).

2. MediaPlayer.PlaybackSession.NaturalVideoSizeChanged does not always fire when the natural width and height properties become available.
3. It is not clear how CopyFrameToVideoSurface fills the surface (or rectangle within the surface) that it is given. I assumed that it would stretch to fill. However, it looks like it's doing some sort of uniform scale fitting, but in a strange way so the video ends up at the bottom right or something. In order to do pixel perfect rendering, one needs to know exactly how the video fills the space. It would be simpler if it just stretched. But maybe there could be some options and better documentation.
4. It is not really possible to use this to render HDR video for the following reasons.
   a. If the target surface for CopyFrameToVideoSurface is 16-bit float then you get an InvaildArgumentException for some videos. For other videos, when used in conjunction with NormalizedSourceRect, the video is stretched in the Y-direction for some reason.
   b. If the target surface for CopyFrameToVideoSurface is 16-bit float then the video appears washed out. This isn't as bad as a failure to convert from sRGB to scRGB and I don't know what causes it. There needs to be some control over the color management that happens during the rendering.
   c. As far as I can see, there is no way to tell that the video contains HDR content. (Except maybe using some completely different API).
5. A minor point - not sure if this is intentional or not. The VideoFrameAvailable event keeps on firing even if the video is paused if you haven't called CopyFrameToVideoSurface after the last time the event fired. Not a big issue really.

I'm on Windows 11.

**Comment by StephenLPeters** [comment]
@asklar and @ocalvo FYI

**Comment by brabebhin** [comment]
I actually been trying to get 1 to work for quite some time now, and it just doesn't work. I don't think trying to render subtitles with win2D is a realistic solution, especially when you get to nasty stuff like SSA/AAS or other scripted formats.

**Comment by lukasf** [comment]
Guys, this is really important. You cannot release a UI framework which cannot render videos. Using UWP MediaPlayer in frame server mode (even if it would work correctly) is a poor workaround. The whole point of WinUI is to have open source code where devs can debug and improve stuff. This is not the case when using UWP APIs and rendering the results into WinUI.

The UWP MediaPlayer and related APIs have quite a lot of bugs and issues that are hard to work around. Especially MediaPlaybackList has multiple issues.

Having a clean, open-source media API in WinUI would allow us to debug into issues, fix bugs and improve the code and APIs. Please take this seriously. We need a true open source media API in WinUI.

**Comment by brabebhin** [comment]
Agreed. The sooner the winUI media engine becomes open source, the faster we can start debugging known issues and provide fixes/troubleshooting.

**Comment by DmitriyKomin** [comment]
We have shipped MediaPlayerElement in WinAppSDK 1.3.

**Comment by benstevens48** [comment]
@DmitriyKomin - this issue was at least as much about fixing issues with MediaPlayer frame server mode and RenderSubtitlesToSurface. Have any of those issues been fixed?

**Comment by brabebhin** [comment]
@DmitriyKomin frame server mode allows implementing some scenarios which are not possible with MPE (particularly when MPE isn't even available). Both should be fully supported. AFAIK, rendering subtitles to directx surface never worked.

**Comment by dotMorten** [comment]
Should this be reopened? The above linked issue is also hitting issues with subtitles, and when I had my implementation in WinUIEx of the MediaPlayerElement I hit that same limitation and could never make it work.

**Comment by softworkz** [comment]
I second that!

This is the original code from which the sample snippets in the documentation were taken: https://github.com/MicrosoftDocs/windows-dev-docs/tree/docs/uwp/audio-video-camera/code/MediaPlayer_RS1/cs

It doesn't work anymore (Frame Server with Subtitles).

**Comment by brabebhin** [comment]
Note that i did manage to get the subtitles to render, using a CanvasRenderTarget. The official docs use a SoftwareBitmap, which never worked for me.

I suspect the problem is in the configuration of the directx surface behind each of those. It would be good to have the docs explicitly mention what kind of surface you need, how it should be configured.
