### ISSUE TITLE
Touch screen text selection is broken

### ISSUE THREAD

**Issue by aquinn39** [microsoft/microsoft-ui-xaml#6611]
### Describe the bug

As shown in the video below, the little circles that appear that allow you to select text and move the text cursor when a textbox is tapped disappear whenever text is selected by double tapping a word, preventing the selection from being changed with touch. I believe the cause of this issue might be because the touch text selection flyout takes focus when shown in WinUI but not in UWP.

https://user-images.githubusercontent.com/43898231/149654559-a893e133-aeef-45b4-8937-dd345485985e.mp4

.

### Steps to reproduce the bug

Double tap on a word in a textbox in any WinUI 2.7.0 UI.

### Expected behavior

The text selection circles should stay there, as seen in the below video (Recorded using a UWP app that does not use WinUI), as can be seen, the circles stay there and can be dragged when a word is selected by being double tapped.

https://user-images.githubusercontent.com/43898231/149654681-24cc452d-cc01-4a83-9d9a-71a6c5b9a218.mp4

)

### Screenshots

![image](https://user-images.githubusercontent.com/43898231/149654897-1c700006-80b2-411c-b113-c0e6b548aa48.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Additional context

I found this issue on Windows 11 (Build 22000.434) (No Windows 11 versions are available in the 'Windows version' drop down above. I have not tested on any other versions of Windows.

**Comment by StephenLPeters** [comment]
@ranjeshj @llongley @kmahone I believe this is the CommandBarFlyout stealing focus away from the text element.  I think this (as well as another issue we triaged recently) should be prioritized pretty highly.

**Comment by aquinn39** [comment]
This seems to have been fixed by https://github.com/microsoft/microsoft-ui-xaml/pull/6844.
