### ISSUE TITLE
Binding can cause Catastrophic Failures

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [microsoft/microsoft-ui-xaml#6612]
### Describe the bug

When binding in ListView to a List it works most of the time, however, if the ItemSource is repeatedly changed, it causes catastrophic failures at the app level. 

Errors can include kernalBase.dll, comBase, memory allocation errors, and failure to set AnimatedIconSource (which is never set)

This happens in SDK v1.0.0 but does not happen in Reunion 0.8 or WPF

### Steps to reproduce the bug

In my code this happens without the reproduction steps below,  due to the complexity of my app and to show the error in as simple way as possible, I wrote a really simple click here and watch the error happen.

Create a new Desktop WinUI app

In XAML - Add the XAML and Code below (very simple) - then run and click the "Click Me" quickly, after about 5 seconds it will error.

```
<Grid>
		<Grid.RowDefinitions>
			<RowDefinition/>
			<RowDefinition Height="Auto"/>
		</Grid.RowDefinitions>

		<ListView	x:Name="UxListView" SelectionMode="None" IsTabStop="False"  >
			<ListView.Resources>
				<ResourceDictionary Source="ms-appx:///Microsoft.UI.Xaml/DensityStyles/Compact.xaml" />
			</ListView.Resources>

			<ListView.ItemTemplate>
				<DataTemplate>
					<CheckBox	IsChecked="{Binding IsChecked, Mode=TwoWay}" Content="{Binding Text, Mode=OneWay}"		VerticalAlignment="Center" Checked="CheckBox_Checked" Unchecked="CheckBox_Checked" />
				</DataTemplate>
			</ListView.ItemTemplate>

		</ListView>

		<Button Grid.Row="1" x:Name="myButton" Click="myButton_Click" HorizontalAlignment="Center" Margin="16" >Click Me</Button>

	</Grid>
```

**In Code behind, Add this**

```
public sealed partial class MainWindow : Window {
		public MainWindow() {
			this.InitializeComponent();
		}

		public MyModel stringModel = new();

		private void myButton_Click(object sender, RoutedEventArgs e) {
			UxListView.ItemsSource = null;
			UxListView.ItemsSource = stringModel.StringList;
		}


		private void CheckBox_Checked(object sender, RoutedEventArgs e) {	}
	}

	public class MyModel {

		public MyModel() {

			for (var i = 1; i < 100000; i++) {
				var newStringItem = new StringItem();

				newStringItem.IsChecked = true;
				newStringItem.Text = "This is some text to bind to the checkbox " + i.ToString() + " " + GuidHelper.CreateNewGuid();

				StringList.Add(newStringItem);
			}

		}

		public List<StringItem> StringList { get; set; } = new();

	}

	public class StringItem {
		public bool IsChecked { get; set; }
		public string Text { get; set; }
	}

```

### Expected behavior

Setting the ItemSource property should reset the view.

### Screenshots

![image](https://user-images.githubusercontent.com/32410442/149658612-af4c8eb8-5c3d-449c-a82c-4999b1aa3ae2.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Additional context

Windows 11 Pro retail

**Comment by StephenLPeters** [comment]
@RBrid @codendone and @MikeHillberg FYI about this 1.0 regression.

**Comment by Marv51** [comment]
Any update on this? This looks so similar to this issue: #8604 
I have also experienced this. 

Currently Checkboxes in ListViews should definitely be avoided.

**Comment by ranjeshj** [comment]
Tried the repro with WinAppSDK 1.4 and it works as expected. We did fix an issue with Checkbox where creating too many of them  would lead to a crash (checkbox uses lottie animations under the covers).
