### ISSUE TITLE
ItemsRepeater with NonVirtualizingLayout doesn't react to Replace action on ItemsSource

### ISSUE THREAD

**Issue by acouvert-msft** [microsoft/microsoft-ui-xaml#6614]
### Describe the bug

When replacing an entry in an `ObservableCollection`, used as `ItemsSource `of an `ItemsRepeater` configured with an `NonVirtualizingLayout` layout,  the control receives a collection changed event about the `Replace` action but the  `NonVirtualizingLayoutContext` provided  to the `MeasureOverride `and `ArrangeOverride` will still have old `Children` representing old value.

### Steps to reproduce the bug

1. Create an `ItemsRepeater` with an `ObservableCollection` as `ItemsSource` and a `NonVirtualizingLayout` as `Layout`
2. Update the `ObservableCollection` by replacing one entry with a new value
3. Observe that the UI is not updated and still displays the old value of the entry which has been replaced.

### Expected behavior

The UI should refresh and displays the new value instead of the old one.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Note that `ItemsRepeater::OnItemsSourceViewChanged` is well received as expected when the replace action occurs.

**Comment by StephenLPeters** [comment]
@ranjeshj FYI

**Comment by danmartinez** [comment]
I encounter this issue during insertion and removal as well, not just when replacing an entry. I also encounter it with all Layout types. I do not encounter it when the collection is of a standard type rather than a custom runtime class.
