### ISSUE TITLE
[RichEditBox] ITextDocument.SetText does not fall back on Font Family correctly for spacing between Emojis

### ISSUE THREAD

**Issue by Havoc9792** [microsoft/microsoft-ui-xaml#6617]
### Describe the bug

We have a customized version of Noto Color Emoji Font with space character removed ie U+0020. 

Spacing is normal for typing or copy & paste. But if I add Emojis between space in between programmatically with ITextDocument.SetText, the spacing becomes full-width.

```
    <Application.Resources>
        <FontFamily x:Key="SegoeWithNotoColorEmojiFontFamily">ms-appx:///Assets/CustomizedNotoColorEmoji.ttf#CNoto Color Emoji, Segoe UI</FontFamily>
        <Style x:Key="TransparentRichEditBoxStyle" TargetType="RichEditBox" >

            <Setter Property="FontFamily" Value="{StaticResource SegoeWithNotoColorEmojiFontFamily}" />
        </Style>
    </Application.Resources>
```

```
<Grid>
        <RichEditBox
            Width="600"
            Height="300"
            Name="Box1"
            Style="{StaticResource TransparentRichEditBoxStyle}" Margin="450,82,450,618">

        </RichEditBox>
        <Button Click="ButtonBase_OnClick" Margin="62,195,0,0" VerticalAlignment="Top">
            Emoji with space
        </Button>
        <Button Click="ButtonBase1_OnClick" Margin="62,679,0,0" VerticalAlignment="Top">
            Just space
        </Button>

    </Grid>

```
```
        private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
            Box1.Document.GetText(TextGetOptions.NoHidden, out var text);
            Box1.Document.SetText(TextSetOptions.None, text + "\uD83D\uDE3A \uD83D\uDE3A");
        }
        private void ButtonBase1_OnClick(object sender, RoutedEventArgs e)
        {
            Box1.Document.GetText(TextGetOptions.NoHidden, out var text);
            Box1.Document.SetText(TextSetOptions.None, text + " ");
        }
```

### Steps to reproduce the bug

1. Click on Button "Just space", once or multiple times, or just type spaces into RichEditBox
2. Can see spaces are normal size
3. Click on Button "Emoji with space"
4. Very wide spacing can be observed.

### Expected behavior

Spacing should be normal

### Screenshots

After step 2:
![image](https://user-images.githubusercontent.com/10755232/149945435-ecaaf5ac-650a-4a8b-9078-31e79f48cbb4.png)

After step 3:
![image](https://user-images.githubusercontent.com/10755232/149945513-8788c5e9-9f24-465e-957e-c4c66beb024e.png)

### Windows app type

- [X] UWP
- [ ] Win32

**Comment by Havoc9792** [comment]
any updates please?

**Comment by codendone** [comment]
I'm assuming the Noto Color Emoji font is a symbol font. Font fallback explicitly does not happen if the font being used is marked as a symbol font, since character codes in that case are symbols and there is no automatic information for how to fall back to an appropriate symbol from another font.

**Comment by Havoc9792** [comment]
@codendone Sorry for the late reply. I think there are something to do with the way ITextDocument.SetText or RichEditBox handle spacing between Emojis.

I have tested with original NotoColorEmoji which I download from https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji_WindowsCompatible.ttf :

`<FontFamily x:Key="SegoeWithNotoColorEmojiFontFamily">ms-appx:///Assets/NotoColorEmoji_WindowsCompatible.ttf#Noto Color Emoji, Segoe UI</FontFamily>`

Click on Button "Emoji with space" + [Text][space key][Text]
![image](https://user-images.githubusercontent.com/10755232/167913165-52569c97-ba43-4aa9-b32d-221fd9a2e889.png)

After another click on Button "Emoji with space" 
![image](https://user-images.githubusercontent.com/10755232/167913208-7ad98942-9839-4241-99f9-48b649a4453f.png)

You can see before we set the content with ITextDocument.SetText, the space between text is full-width. And after calling ITextDocument.SetText, the space becomes " ", which is unexpected. It should be full-width as intended by NotoColorEmoji_WindowsCompatible.ttf. But the space between emoji does not change.

**Comment by Havoc9792** [comment]
Repeating with our customized font:

![image](https://user-images.githubusercontent.com/10755232/167914828-2b84200c-4fe0-4491-8f62-df9b679c4f85.png)

![image](https://user-images.githubusercontent.com/10755232/167914863-507c2218-91f8-4433-9208-6b8b5381e1b6.png)

Now it seems to be unrelated to font fallback, as we did not expect spacing to change after ITextDocument.SetText when using standard NotoColorEmoji_WindowsCompatible.ttf. 

Or is there different logics in spacing between emojis and spacing between text?
