### ISSUE TITLE
Background acrylic and In-app acrylic behaves the same in WinUI 3.

### ISSUE THREAD

**Issue by Realinspirer** [microsoft/microsoft-ui-xaml#6618]
### Describe the bug

In WinUI 3, **Background acrylic** and **In-app acrylic** applies the same brush, i.e. the latter one. This can also be seen in the [WinUI 3 Controls Gallery](https://www.microsoft.com/store/productId/9P3JFPWWDZRC). Here's the image from the app -

![image](https://user-images.githubusercontent.com/97922606/149941568-cd1db32c-6049-466b-a1dc-eb2a04915a5c.png)
_Background acrylic_

![image](https://user-images.githubusercontent.com/97922606/149941513-81fd7893-60f1-43f8-b98e-647b379578ce.png)
_In-app acrylic_

I think the cause of this bug is that in WinUI 3, `<AcrylicBrush>` has no property called `BackgroundSource`. It takes values like `Backdrop` or `HostBackdrop` to denote **In-app** or **Background** respectively.

**Mica** also doesn't work in WinUI 3.

### Steps to reproduce the bug

You can see this bug every time you try to set any brush from **Background acrylic** as the brush (`AcrylicBackgroundFillColorDefaultBrush`, for instance). Here's an example to reproduce this bug -

1. Start a `Grid`, and add a `Rectangle` inside it. Set the `Fill` property to a solid color and set the size to something like (200,200).
```
<Grid>
        <Rectangle Fill="Blue" Width="200" Height="200"></Rectangle>
</Grid>
```
![image](https://user-images.githubusercontent.com/97922606/149945618-65cbbb67-1613-4bef-ab5c-63bcd814f2a5.png)

2. Inside the `Grid` and below the `Rectangle`, add another `Grid`. Set its `Background` property to `{ThemeResource AcrylicInAppFillColorDefaultBrush}`.
```
<Grid>
        <Rectangle Fill="Blue" Width="200" Height="200"></Rectangle>
        <Grid Background="{ThemeResource AcrylicInAppFillColorDefaultBrush}"></Grid>
</Grid>
```
![image](https://user-images.githubusercontent.com/97922606/149946096-e8fe26a8-1998-41bc-98df-3ca7daa1aaae.png)
_As you can see, in-app acrylic works just fine!_

3. Change the value of `Background` to `{ThemeResource AcrylicBackgroundFillColorDefaultBrush}` and check if anything changes.
```
    <Grid>
        <Rectangle Fill="Blue" Width="200" Height="200"></Rectangle>
        <Grid Background="{ThemeResource AcrylicBackgroundFillColorDefaultBrush}"></Grid>
    </Grid>
```
![image](https://user-images.githubusercontent.com/97922606/149946993-71bb2219-b78e-4e71-aa37-d8481734a1c8.png)
_You can see that nothing changes even after setting the `Background` to a **Background acrylic brush**._

### Expected behavior

Expected behavior can be understood from these images from [XAML Controls Gallery](https://www.microsoft.com/store/productId/9MSVH128X2ZT) -

![image](https://user-images.githubusercontent.com/97922606/149949266-25a31a8f-2239-49ed-8c39-53d6986b0d57.png)
_Background acrylic selects the application background as the source._

![image](https://user-images.githubusercontent.com/97922606/149949778-03e2b8b4-1069-4656-a074-d7aefd83a643.png)
_In-app acrylic selects whatever is behind the control as the source._

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] Win32
- [x] UWP

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx), May 2021 Update (19043), October 2020 Update (19042), May 2020 Update (19041), November 2019 Update (18363), May 2019 Update (18362), October 2018 Update (17763)

### Workaround for this bug
I think you already know what I am about to mention, but you can place the current background image of the user's PC behind a `Grid`, and apply the **Background acrylic** as the brush (if this gets patched, then the brush will work as expected, without making changes). But this is not the absolute solution, it will not work as expected (image resizes with window and many problems).

**Comment by kmgallahan** [comment]
Background acrylic isn't currently supported. You can vote for it and other things here:

https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/28-background-acrylic

**Comment by Realinspirer** [comment]
> 

Thank you! Well, I already knew it, just wanted to make things clear.
