### ISSUE TITLE
Question: Is there a way to detect Windows theme change?

### ISSUE THREAD

**Issue by Aladriel** [microsoft/microsoft-ui-xaml#6621]
I'm trying to capture theme change event to change SVG icon sources. I tried using code that is working in UWP:
```
UISettings uiSettings = new UISettings();
uiSettings.ColorValuesChanged += ColorValuesChanged;
```
uiSettings.GetColorValue(UIColorType.Background) is returning 'Black' and 'White' for Dark and Light mode properly
however, ColorValuesChanged method is not invoked on theme change.
I'm storing uiSettings reference as a field

"Microsoft.WindowsAppSDK" Version="1.0.0"

**Comment by knat** [comment]
FrameworkElement.ActualThemeChanged

**Comment by Aladriel** [comment]
Thanks, that's what I was looking for
