### ISSUE TITLE
TeachingTip does does not open when IsOpen is set early

### ISSUE THREAD

**Issue by chausner** [microsoft/microsoft-ui-xaml#6628]
### Describe the bug

I am experiencing an issue where a `TeachingTip` does not show even after setting `IsOpen` to `True`. The problem occurs when `IsOpen` is set "too early" during window initialization.

### Steps to reproduce the bug

1. Create a new WinUI packaged app and replace the main window's XAML with
```xaml
<Window
    x:Class="App2.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
    <Grid>
        <Button x:Name="myButton">Click Me</Button>
        <TeachingTip Target="{x:Bind myButton}" Title="Test" IsOpen="{x:Bind TipShown, Mode=OneWay}" />
    </Grid>
</Window>
```
and add to code-behind:
```csharp
public sealed partial class MainWindow : Window
{
    public bool TipShown { get; set; }

    public MainWindow()
    {
        this.InitializeComponent();

        Activated += MainWindow_Activated;
    }

    private void MainWindow_Activated(object sender, WindowActivatedEventArgs args)
    {
        TipShown = true;
        Bindings.Update();
    }
}
```
2. Run the application. The teaching tip will not be visible. You may verify in the Visual Live Tree that `IsOpen` is indeed set to `True`.
3. In Visual Live Tree, disabling and enabling `IsOpen` again makes the teaching tip visible.

I also tried setting `IsOpen` in `myButton.Loaded` instead of `Window.Activated` but the outcome is the same. I have not been able to find an event invoked during window activation/loading where I can safely enable the teaching tip.

One hacky workaround I found is adding an `await Task.Delay(100);` in the event handler before setting the property:
```csharp
private async void MainWindow_Activated(object sender, WindowActivatedEventArgs args)
{
    await Task.Delay(100);
    TipShown = true;
    Bindings.Update();
}
```
This also makes the teaching tip visible.

### Expected behavior

The TeachingTip should get displayed.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Additional context

Might be related to https://github.com/microsoft/microsoft-ui-xaml/issues/5921 or https://github.com/microsoft/microsoft-ui-xaml/issues/6627.

**Comment by StephenLPeters** [comment]
Similar to some older issues: https://github.com/microsoft/microsoft-ui-xaml/issues/349 however I thought we had squashed all of these bugs... https://github.com/microsoft/microsoft-ui-xaml/pull/619.   Looking through the code I think its possible that this change could have fixed this issue: https://github.com/microsoft/microsoft-ui-xaml/pull/6541 but doesn't exist in winui3 yet. There also looks like there is an issue where initial state being set to open wont be respected... We should investigate.

**Comment by dhoehna** [comment]
Running into this as well.  Changing `IsOpen` in a button click event works but not in the constructor.

**Comment by ranjeshj** [comment]
This is fixed. Tried the repro above on WinAppSDK 1.5 and it works now.

**Comment by chausner** [comment]
Did a quick test with version 1.5 and cannot reproduce the issue anymore. Thanks!
