### ISSUE TITLE
CanvasImageSource disappears upon minimize / screen lock - UWP

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/microsoft-ui-xaml#6631]
### Describe the bug

When using a CanvasImageSource as an ImageSource in UWP the image is initially shown but upon minimise or screen lock the image disappears.

This occurs when drawn with text, CanvasGeometry, CanvasSvgDocument and ink strokes.

### Steps to reproduce the bug

As above.

Can be see in this repo https://github.com/tonyhallett/FontSvgImageSource where the first icon displayed is from a CanvasImageSource drawn in the same manner as Xamarin Forms that is experiencing the issue.

https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs#L39

https://github.com/xamarin/Xamarin.Forms/issues/8293
https://github.com/xamarin/Xamarin.Forms/issues/14323

### Expected behavior

Does not disappear

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
@codendone I'm unfamiliar with CanvasImageSource. Do you know what this is? Is it a Winui type?

**Comment by tonyhallett** [comment]
Yes.
