### ISSUE TITLE
Bug: don't work property IconSource in IconSourceElement

### ISSUE THREAD

**Issue by maxes-pl** [microsoft/microsoft-ui-xaml#6633]
### Describe the bug

Property IconSource bind in xaml element "IconSourceElement" dosn't work, when binding returning ImageIconSource. 

### Steps to reproduce the bug

Xaml code:
```
  <IconSourceElement
    HorizontalAlignment="Left"
    Width="24"
    Height="24"
    IconSource="{x:Bind IconSource24, Mode=OneWay}"/>
```
Interface:
```
 [bindable]
  runtimeclass CmdBase : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
  {
    Microsoft.UI.Xaml.Controls.IconSource IconSource24{get;};
  };
```
Implementation:
```
muxc::IconSource IconSource24()
{
  muxc::ImageIconSource source{muxc::ImageIconSource()};
  source.ImageSource(/* load file with png image with IRandomAccessStream */);

  muxc::ImageIcon out{muxc::ImageIcon()};
  out.Source(tmp1);
  return out;
}
```

Setting an icon for the TabViewItem class also doesn't work  (pseudo code below):
```
muxc::TabViewItem tab;
tab.IconSource(CmdBase::IconSource24());
tab.Header(box_value(form.Title()));
```

### Expected behavior

Display the bitmap as an icon 

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
This code doesn't make sense to me:
```
muxc::IconSource IconSource24()
{
  muxc::ImageIconSource source{muxc::ImageIconSource()};
  source.ImageSource(/* load file with png image with IRandomAccessStream */);

  muxc::ImageIcon out{muxc::ImageIcon()};
  out.Source(tmp1);
  return out;
}
```
the ImageIconSource you created isn't used anywhere, the tmp1 variable isn't defined, and you fucntion return type is IconSource but you are returning an ImageIcon.  Something isn't right here, I'm not sure how this code compiles.

**Comment by maxes-pl** [comment]
Sorry, my mistake - this is not the code I pasted. Correct is: 

```
muxc::IconSource IconSource24()
{
  muxm::Imaging::BitmapImage tmp1;
  tmp1.SetSource(/* load file with png image with IRandomAccessStream - loader.as<wss::IRandomAccessStream>()) */;

  muxc::ImageIconSource icon_source;
  icon_source.ImageSource(tmp1);
  return icon_source;
}
```

**Comment by maxes-pl** [comment]
And then tries to attach an icon to the element:

`<IconSourceElement  
  Width="24"
  Height="24"
  HorizontalAlignment="Left"
  IconSource="{x:Bind IconSource24, Mode=OneWay}"/>`

**Comment by StephenLPeters** [comment]
I see, and I assume this works with BitmapIcon instead of ImageIcon?

**Comment by maxes-pl** [comment]
Yes. It also works for :

```
muxc::IconElement IconElement24()
{
  auto tmp{IconSource24()};
  if(tmp)
  {
    return tmp.CreateIconElementCore();
  }
  return nullptr;
}

```
And bind to xaml element:

```
<NavigationViewItem Icon="{x:Bind IconElement24, Mode=OneWay}" SelectsOnInvoked="True">

```

**Comment by zhuxb711** [comment]
Don't close this as the issue still exists

**Comment by ranjeshj** [comment]
Sorry for the delayed response. could you please attach a repro app?
