### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by xiao-cao-x** [microsoft/microsoft-ui-xaml#6636]
Does WinUI3 support MVU mode? Like Flutter.
Does Visual Studio support WinUI 3 xaml hot reload?

**Comment by dylech30th** [comment]
Hot reload is supported in Visual Studio 2022
MVU is not currently supported.

**Comment by xiao-cao-x** [comment]
> Hot reload is supported in Visual Studio 2022 MVU is not currently supported.

我试了xaml热重载并不能刷新UI

**Comment by dylech30th** [comment]
https://docs.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022#visual-studio-2022-with-a-net-app-when-using-the-debugger
稍微查了一下，看起来你需要稍微修改一下launchSettings.json文件

**Comment by xiao-cao-x** [comment]
![image](https://user-images.githubusercontent.com/76673990/150736640-e2809bbc-f8d0-4312-9583-f38b9ea25621.png)
如下

**Comment by xiao-cao-x** [comment]
热重载按钮可以点 但是不能刷新UI

**Comment by dylech30th** [comment]
可以提供一些更详细的信息吗？比如你期望的结果和实际运行之后(点击Hot Reload)按钮之后的结果，以及一个复现例，我可以在我的机器上试一下

**Comment by xiao-cao-x** [comment]
https://user-images.githubusercontent.com/76673990/150737281-145975c6-922a-44d6-85f5-bf8eac43c980.mp4

**Comment by dylech30th** [comment]
我注意到这个UI似乎是Windows App SDK 1.0 Preview 2以前的旧Fluent Design的风格，WindowsAppSDK的插件升级了嘛

**Comment by xiao-cao-x** [comment]
![image](https://user-images.githubusercontent.com/76673990/150739246-90f32568-7154-4606-96e5-cf7e05dfeb6a.png)

**Comment by dylech30th** [comment]
是WindowsAppSDK的插件，也就是这个
![image](https://user-images.githubusercontent.com/31894334/150739324-e4a7535e-da13-4b61-a0c7-870be49aed54.png)
可以在[这里](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads)下载1.0 Stable版本

**Comment by xiao-cao-x** [comment]
我安装这个插件的时候失败了 说让我去安装程序里安装 然后后来好像没装 也能用 但是进去的时候 .NET版本是5 我自己改成6的

**Comment by dylech30th** [comment]
你的WinUI的版本是旧版本(1.0 Stable以前的版本)，我猜测nuget包前缀是ProjectReunion
可以遵循[这篇文章中的指示](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/update-existing-projects-to-the-latest-release)来把你的WinUI版本升到1.0 Stable

**Comment by xiao-cao-x** [comment]
去年弄过一下WinUI stable版本的 但是今年插件就安不上了 想试试热重载也不行

**Comment by dylech30th** [comment]
安装插件的报错信息是什么呢

**Comment by xiao-cao-x** [comment]
![image](https://user-images.githubusercontent.com/76673990/150740559-519f025b-f934-435c-bed0-0f7940133f51.png)

**Comment by dylech30th** [comment]
View Install Log里面写的是什么

**Comment by xiao-cao-x** [comment]
```console
2022/1/24 15:34:47 - 正在开始将扩展安装到 Visual Studio Enterprise 2022 Preview...
2022/1/24 15:34:47 - VSIX TaskScheduler: VSIX Update Configuration task 已成功注册。
2022/1/24 15:34:47 - 帐户名与安全标识间无任何映射完成。
2022/1/24 15:34:51 - 安装 Microsoft.WindowsAppSDK.Cs.Dev17 失败。该扩展的版本比 Visual Studio 要求的版本低。请改为从 Visual Studio 安装程序安装扩展。
2022/1/24 15:34:51 - 安装错误: System.InvalidOperationException: 安装 Microsoft.WindowsAppSDK.Cs.Dev17 失败。该扩展的版本比 Visual Studio 要求的版本低。请改为从 Visual Studio 安装程序安装扩展。
   在 Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureComponentAndPackageAreHigherVersion(ILogger logger, IDependencyGraph dGraph, Catalog catalog, Component vsixComponent)
   在 Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
2022/1/24 15:34:51 - Capping recursion at 5 directories in each extension root due to 'default limit'.
```

**Comment by xiao-cao-x** [comment]
![image](https://user-images.githubusercontent.com/76673990/150740866-5aa3b452-ac30-4445-adfd-7b6916986446.png)

**Comment by dylech30th** [comment]
尝试一下把Visual Studio 2022降级到17.0.x试试？

**Comment by dylech30th** [comment]
草（），互联网真小，这都能遇到同好

**Comment by xiao-cao-x** [comment]
要不加个联系方式?

**Comment by dylech30th** [comment]
我的[blog首页](https://sora.ink/]那一行图标第二个是我的QQ，就不发在github上面了(

**Comment by xiao-cao-x** [comment]
> 我的[blog首页](https://sora.ink/)那一行图标第二个是我的QQ，就不发在github上面了(

我QQ加不了人(

**Comment by dylech30th** [comment]
草，那你往[decem0730@hotmail.com](mailto:decem0730@hotmail.com)发一下你的联系方式好了，我去加
