### ISSUE TITLE
SplitButton border is different from Button border in dark mode

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#6638]
### Describe the bug

The border of the `SplitButton` is different from the one of the `Button` in dark mode.

### Steps to reproduce the bug

1. Open Xaml control gallery.
2. Set the app theme to dark
3. Open the `Button` sample page.
4. Open the `SplitButton` sample page.

Compare the border of the two buttons

### Expected behavior

The `SplitButton` border is different from the one on `Button`. It seems that linear gradient is not applied in dark mode. We can see it in light mode.

### Screenshots

![image](https://user-images.githubusercontent.com/20152272/151209544-6d656c91-6a9f-4b44-95b3-d0f82a7bbdf7.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@chigy FYI
