### ISSUE TITLE
InvokedItemContainer from ItemInvoked event parameter is null when selecting a databound item in a NavigationView overflow dropdown

### ISSUE THREAD

**Issue by torleifat** [microsoft/microsoft-ui-xaml#6640]
### Describe the bug

I hope I am using the correctly terminology here when I say Overflow, what I mean is when you resize the application so the NavigationView can no longer display all icons and some are put in a drop-down menu.
So whenever the ItemInvoked event fires, if the selected item was one of the items in the dropdown menu the InvokedItemContainer (from NavigationViewItemInvokedEventArgs)  will be null. I first noticed this in a C++ app, but it seems like the same behavior is present in a C# app under the same circumstances. This will only happen with data-bound items as far as I can see. If the NavigationViewItems are defined in Xaml the event fires and InvokedItemContainer is not null.

The ItemInvoked property in NavigationViewItemInvokedEventArgs is the correct one either way, it is only the InvokedItemContainer that is null. At first I thought it may have something to do with the MenuItemTemplate I was using, but removing this produced the same effect.

### Steps to reproduce the bug

1. Create a WinUI 3 C# Blank App.

2. Replace default stackpanel with this in MainWindow.xaml:
```
    <NavigationView ItemInvoked="ItemInvokedEvent" PaneDisplayMode="Top" MenuItemsSource="{x:Bind ViewModel.MenuItems}" >
        <NavigationView.MenuItemTemplate>
            <DataTemplate x:DataType="local:NavigationItem">
                <NavigationViewItem Content="{x:Bind Name}"/>
            </DataTemplate>
        </NavigationView.MenuItemTemplate>
    </NavigationView>

```
3. Replace the code in MainViewModel.xaml.cs with this:
```
public sealed partial class MainWindow : Window
{
	public MainWindow()
	{
		this.ViewModel = new MainViewModel();
		this.InitializeComponent();
	}

	private void ItemInvokedEvent(NavigationView sender, NavigationViewItemInvokedEventArgs args)
	{
		if (args.InvokedItemContainer == null)
			System.Diagnostics.Debug.WriteLine("InvokedItemContainer is null");
		else
			System.Diagnostics.Debug.WriteLine("InvokedItemContainer is not null");
	}

	public MainViewModel ViewModel { get; private set; }
}

public class MainViewModel
{
	public MainViewModel()
	{
		this.MenuItems =
			new System.Collections.ObjectModel.ObservableCollection<NavigationItem>()
			{
				new NavigationItem{ Name = "Item 1" },
				new NavigationItem{ Name = "Item 2" },
				new NavigationItem{ Name = "Item 3" },
			};
	}

	public System.Collections.ObjectModel.ObservableCollection<NavigationItem> MenuItems { get; private set; }
}

public class NavigationItem
{
	public string Name { get; set; }
}

```
4. Build and run the app.
5. Resize the app until one or two of the items end up in the overflow drop-down.
6. Try clicking one of the menu items in the drop-down and observe the state of InvokedItemContainer when ItemInvoked fires.

### Expected behavior

I would have expected InvokedItemContainer not to be null.

### Screenshots

![overflow_menu_cs](https://user-images.githubusercontent.com/1870870/151319741-a5e61f8d-4abd-403d-a3d4-2b3939256ba9.png)
In this image clicking Item 2 or 3 will result in a ItemInvoked event where the ItemInvokedContainer is null.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

I have only seen this when PaneDisplayMode is set to Top as I could not reproduce the circumstances that create the overflow menu when the mode was set to Left.

**Comment by StephenLPeters** [comment]
@ojhad is this behavior expected?
