### ISSUE TITLE
"A cycle occurred while laying out the GUI." Exception occurred while adding the Inlines to the TextBlock in WINUI_Desktop

### ISSUE THREAD

**Issue by SathiyathanamSathish** [microsoft/microsoft-ui-xaml#6642]
### Describe the bug

**"A cycle occurred while laying out the GUI." exception occurred while adding the Inlines to the TextBlock in WINUI**

### Steps to reproduce the bug

1. Run the attached Sample.
2. Note the "A cycle occurred while laying out the GUI." exception occurred.

You can find the sample in the bottom of the query.

### Expected behavior

The "A cycle occurred while laying out the GUI." exception should not occur and TextBlock should update based on the Inlines.

### Screenshots

![image](https://user-images.githubusercontent.com/89458634/151144264-21d9746a-e9dd-4a74-9a73-1d60ca5eeb25.png)

### NuGet package version

1.0.0

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022-preview

### Additional context

We have a custom button that has the content as ContentPresenter. By using this custom button we have tried to change the TextBlcok foreground based on its content by using the [Run](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.documents.run?view=winui-3.0#properties) and [TextBlock.Inlines](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.textblock.inlines?view=windowsdesktop-6.0). Please refer to the below image which we have tried 

![image](https://user-images.githubusercontent.com/89458634/151145356-b1d14d60-23d5-4333-ad9a-5bbd1966612f.png)

![image](https://user-images.githubusercontent.com/89458634/151145492-dc682efc-9ae0-418a-b43a-cd78756c5cf0.png)

And in the Custom Button ArrangeOverride method, I have changed the custom button contentpresenter ie. TextBlcok inline based on its content. While I am doing this, the button ArrangeOverride is called multiple times so that only this exception occurred. **We need to know why the Button ArrangeOverried is called multiple times when we change textblock inlines.**

### Sample Location

**WINUI Sample** - [TextBlock_Inline_WINUI.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7940871/TextBlock_Inline.zip)

And i have added the same codes in the **UWP** platform. In **UWP** also the same **"Layout cycle detected."** exception occurred.

**UWP Sample** - [TextBlock_Inline_UWP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7942557/TextBlock_Inline.zip)

But the same codes does not occur any issues in the **WPF** sample and ArrangeOverride is also called only one time:

**WPF Sample** - [TextBlock_Inline_WPF.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7942567/TextBlock_Inline_WPF.zip)

**Comment by tripjump** [comment]
I am using MAUI and I got this error with:
- Label and multiBinding
- FormattedString and multiple spans

**Comment by tripjump** [comment]
I am using MAUI and I got this error with:

Label and multiBinding
FormattedString and multiple spans

**Comment by StephenLPeters** [comment]
@SathiyathanamSathish your ArrangeOverride method is calling ApplyInline which clears the text box and then adds new content, this is causing the layout to be dirtied which is causing a new layout to be run which repeats the process causing a cycle.

**Comment by tripjump** [comment]
I have got the same error using MAUI with ListView.
When the control containing the ListView is made invisible then visible I got the crash.

**Comment by Davidoutz** [comment]
I've also this error with collectionview and listview on .net MAUI while jumping back from one page to another. 
@tripjump Did you ever find out the problem or a workaround ?

**Comment by symbiogenesis** [comment]
I am seeing this on MAUI targeting WinUI. It happens when clicking a button that executes a navigation command, from within a CollectionView that is bound to a lot of records.

**Comment by HeikkiK** [comment]
I had this issue when page where navigation started from had next code with border (not commented out): 
.Net7 in use and seem to occur only with WinUI. Not in android emulator at least (didn't test in real device). Didn't have any effect when took content or parameter from border out. Needed to leave content without border to get it work. In navigated to page I also have Listview with border but it didn't have any difference if I took border out from there (or anything else)

        <ListView x:Name="MainPanel" ItemsSource="{Binding SearchItems}" BackgroundColor="#232323" ItemTapped="MainPanel_ItemTapped" HasUnevenRows="True" SeparatorColor="Transparent">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        
                            <Grid>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*" />
                                    <ColumnDefinition Width="Auto" />
                                </Grid.ColumnDefinitions>
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto"/>
                                    <RowDefinition Height="Auto"/>
                                </Grid.RowDefinitions>
                                <Label Grid.Column="0" Text="{Binding CurrentName}" FontSize="14" TextColor="White" Margin="3,0,0,0" LineBreakMode="WordWrap"/>
                                <Image Grid.Column="1" HeightRequest="25" WidthRequest="25" Source="video.png" IsVisible="{Binding IsLocked}" Margin="0,3,5,3" Aspect="AspectFit"/>
                                <Image Grid.Column="1" Grid.Row="1" HeightRequest="25" WidthRequest="25" Source="star_border.png" Margin="0,0,5,3" Aspect="AspectFit"/>
                            </Grid>
                        
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
