### ISSUE TITLE
ScrollViewer blocks the focus visual of contents

### ISSUE THREAD

**Issue by zhit-microsoft** [microsoft/microsoft-ui-xaml#6643]
### Describe the bug

ScrollViewer is clipping the focus visual of content.

### Steps to reproduce the bug

In a sample WinUI UWP app add the following XAML element.

```
<ScrollViewer>
    <StackPanel>
        <ComboBox />
        <ComboBox />
        <ComboBox />
    </StackPanel>
</ScrollViewer>
```

### Expected behavior

![image](https://user-images.githubusercontent.com/67346523/151459056-48b94093-89c6-487e-89ca-818e27731762.png)

### Screenshots

Actual Behavior:
![image](https://user-images.githubusercontent.com/67346523/151459123-f05f7877-1ee4-4471-902d-6175651db5bb.png)

Expected Behavior
![image](https://user-images.githubusercontent.com/67346523/151459056-48b94093-89c6-487e-89ca-818e27731762.png)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
I don't reproduce this issue.  @zhit-microsoft could you provide more info?

**Comment by zhit-microsoft** [comment]
@StephenLPeters, what information do you need?

**Comment by StephenLPeters** [comment]
The build of windows you are using, the version of winui you are using. any repro steps that you are doing beyond launch the app and hit tab.
