### ISSUE TITLE
XAML Islands CommandBarFlyout breaks JAWS screen reader's ability to read ContentDialog

### ISSUE THREAD

**Issue by lyahdav** [microsoft/microsoft-ui-xaml#6645]
### Describe the bug

In a XAML Islands app, if you have the [JAWS screen reader](https://www.freedomscientific.com/products/software/jaws/) running and you press Insert+B while a ContentDialog is open, it'll read out the contents of the dialog. But then if you open a CommandBarFlyout, close the flyout, open a ContentDialog again and press Insert+B, JAWS will read out the contents of the window behind the ContentDialog instead of the ContentDialog.

### Steps to reproduce the bug

1. Download this repo/branch: https://github.com/lyahdav/XamlPlayground/tree/ContentDialog-JAWS-bug-attempt-repro
2. Open XamlPlayground.sln
3. Run the XamlIslandsApp project in that solution
4. Run JAWS
5. Click the button on the app to open a ContentDialog
6. Press Insert+B, confirm JAWS reads ContentDialog
7. Close dialog
8. Right click on TextBox to open a CommandBarFlyout
9. Close CommandBarFlyout
10. Click the button again to open a ContentDialog
11. Press Insert+B, observe JAWS reads the contents of window behind the ContentDialog

### Expected behavior

Expected that JAWS reads the ContentDialog contents

### Screenshots

Here's a video of the steps above:

https://user-images.githubusercontent.com/359157/151463871-d94acdbe-b354-4783-953d-28a9721d70c2.mov

Here's the same thing in a UWP app, which doesn't have the bug:

https://user-images.githubusercontent.com/359157/151463918-07dd7f6d-8e7b-4513-95e2-469db4743362.mov

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

The XamlPlayground.sln in the repo/branch https://github.com/lyahdav/XamlPlayground/tree/ContentDialog-JAWS-bug-attempt-repro also has the UWP app in UwpXamlApp project. Just set it as the startup project to try it.

**Comment by lyahdav** [comment]
I just tested this with the TextCommandBarFlyout from WinUI 2.7.1 instead of system XAML's TextCommandBarFlyout and the same bug occurs. That code is here: https://github.com/lyahdav/XamlPlayground/tree/ContentDialog-JAWS-bug-attempt-repro-winui-2.7.1

**Comment by stmoy** [comment]
Looking for JAWS contact on the accessibility team. Unclear if the issue is in RNW, WinUI, Xaml Islands, or JAWS. 😅

**Comment by AgneLukoseviciute** [comment]
I wasn't able to repro with Narrator nor NVDA, so this is likely a bug with JAWS. @lyahdav, could you share what build of JAWS was used for testing so we can file a bug accordingly, latest should be 2022.2112.

**Comment by lyahdav** [comment]
@AgneLukoseviciute I'm on JAWS version 2022.2112.24

**Comment by AgneLukoseviciute** [comment]
@lyahdav, thanks for the info! I've relayed the information and we'll be filing a separate bug to address this 😊
