### ISSUE TITLE
BasedOn="{StaticResource DefaultStyle}" throws an error when used in a Resource file that's included in App.Resources

### ISSUE THREAD

**Issue by bogdan-patraucean** [microsoft/microsoft-ui-xaml#6648]
### Describe the bug

I'm trying to create a new style for **ListViewItem** based on the existing **DefaultListViewItemStyle** and place it in it's own Resource file.

**Styles.xaml**:

```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Style x:Key="NewListViewItemStyle" TargetType="ListViewItem" BasedOn="{StaticResource DefaultListViewItemStyle}">
        <Setter Property="Background" Value="Transparent"></Setter>
    </Style>
</ResourceDictionary>
``` 

**App.xaml**:
```
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
                <ResourceDictionary Source="/Resources/Styles.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
</Application.Resources>
```

**Page.xaml** (how I try to use it):

```
<ListView ItemContainerStyle="{StaticResource NewListViewItemStyle}">
```

When I try to run the app I get this error: **"Cannot find a Resource with the Name/Key DefaultListViewItemStyle"**

I also tried adding the style resource like this, but still the same error:

```
<controls:XamlControlsResources>
      <controls:XamlControlsResources.MergedDictionaries>
          <ResourceDictionary Source="/Resources/Styles.xaml"/>
      </controls:XamlControlsResources.MergedDictionaries>
</controls:XamlControlsResources>
```

The only way it works is by reincluding the  `<XamlControlsResources  xmlns="using:Microsoft.UI.Xaml.Controls"/>` in the **Styles.xaml**:

```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <ResourceDictionary.MergedDictionaries>
        <XamlControlsResources  xmlns="using:Microsoft.UI.Xaml.Controls"/>
    </ResourceDictionary.MergedDictionaries>
    <Style x:Key="NewListViewItemStyle" TargetType="ListViewItem" BasedOn="{StaticResource DefaultListViewItemStyle}">
        <Setter Property="Background" Value="Transparent"></Setter>
    </Style>
</ResourceDictionary>
``` 

I see a problem to this solution because,  `<XamlControlsResources  xmlns="using:Microsoft.UI.Xaml.Controls"/>` is already included in App.xaml, so I don't think it should be needed in the Styles.xaml as that file is also part of Application.Resources.

I'm new to the XAML world and maybe this makes sense, but I studied the official documentation and asked questions about this in the Discord community and I did not found any answers for why doesn't work, or how should it work.

### Steps to reproduce the bug

1. Create a Resource file with a new style that's based on the default one.
2. Include the Resource file in Application.Resources
3. Use the style wherever you want.
4. Wait for the error to be triggered when you try to build the app. 

### Expected behavior

Including `<XamlControlsResources  xmlns="using:Microsoft.UI.Xaml.Controls"/>` in Application.Resources should be enough to be able to create a new style based on a default one. Reincluding `<XamlControlsResources  xmlns="using:Microsoft.UI.Xaml.Controls"/>` in the Resource file should not be needed and **no error should appear** if it's not reincluded.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
The problem here is that a resource lookup that originates from a dictionary in App.xaml originates that new lookup form the dictionary that the reference is in.  In this case, the look for DefaultListViewItemStyle is originating from the sibling dictionary and the lookup will not search the siblings.

What you've done by putting XCR inside of your custom dictionaries' MergedDictionaries resolves this issue, and I don't see any reason why you couldn't remove the one included in App.xaml to remove the duplication (remembering that lookups originating from XCR wont look in this dictionary. 

The other thing you could do is define your style in a dictionary in the .Resources of an element in your visual tree. These dictionaries are re-searched by the lookup and would avoid this issue.

**Comment by HavenDV** [comment]
But what if you want to have styles organized like this and based on WinUI styles? As I understand it, including XamlControlsResources in each of these files slows down the resulting Lookup in the global space.
```xml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="HeaderedContentControl.xaml" />
        <ResourceDictionary Source="ToolTip.xaml" />
        <ResourceDictionary Source="HyperlinkButton.xaml" />
        <ResourceDictionary Source="Button.xaml" />
        <ResourceDictionary Source="DataGrid.xaml" />
        <ResourceDictionary Source="ListView.xaml" />
        <ResourceDictionary Source="Grid.xaml" />
        <ResourceDictionary Source="StackPanel.xaml" />
        <ResourceDictionary Source="TextBox.xaml" />
        <ResourceDictionary Source="PasswordBox.xaml" />
        <ResourceDictionary Source="DatePicker.xaml" />
        <ResourceDictionary Source="ComboBox.xaml" />
        <ResourceDictionary Source="MenuItem.xaml" />
        <ResourceDictionary Source="Expander.xaml" />
        <ResourceDictionary Source="UserControl.xaml" />
        <ResourceDictionary Source="GridSplitter.xaml" />
    </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

**Comment by StephenLPeters** [comment]
Yeah, that would be expensive.  In the winui2 project we don't hit this issue because we have a build step where we combine all of our "Foo.xaml" files into one xaml file.  I don't see a good way of doing this with the way the resource lookup system works today... I think the only option is to define this dictionary in your visual tree instead of your app.xaml. Definitely a big issue, but not one that will be fixable in winui2. In winui3 we should be able to removed XCR all together.  @codendone and @llongley is that still planned?

**Comment by codendone** [comment]
Yes, the plan is to remove XamlControlsResources in WinUI3 ([internal task](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/21236506)). Not sure yet which release that will be in.
