### ISSUE TITLE
UnLoaded event is incorrectly raised by the contents of CommadBar PrimaryCommands

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#6652]
### Describe the bug

`UnLoaded` event is getting raised when the contents of `CommandBar`'s `PrimaryCommands` comes back in view after being placed in the secondary commands.

Whenever the `PrimaryCommand`s contents like `AppBarButton` etc is displayed, a `Loaded` event is raised. When the commandbar width is reduced enough the content moves to `SeconderyCommand`, at that time `UnLoaded` event is raised. 

If the command bar's width is increased again, a `Loaded` event is raised which is immediately followed by a `UnLoaded` event. `UnLoaded` event should not be raised at this point.

This cause framework like ReactiveUI not to work properly as it depends on the proper firing of `Loaded` and `UnLoaded` events by the UI elements.

### Steps to reproduce the bug

1. Create a CommandBar like 

```xaml
    <CommandBar>
        <CommandBar.PrimaryCommands>
            <AppBarButton Content="Button" Loaded="FrameworkElement_OnLoaded" Unloaded="FrameworkElement_OnUnloaded"/>
            <AppBarElementContainer>
                <SplitButton Content="SplitButton" Loaded="FrameworkElement_OnLoaded" Unloaded="FrameworkElement_OnUnloaded"/>
            </AppBarElementContainer>
        </CommandBar.PrimaryCommands>
    </CommandBar>
```

```cs
        private void FrameworkElement_OnLoaded(object sender, RoutedEventArgs e)
        {
            if(sender is ContentControl element)
                Trace.WriteLine($"Loaded {element.Content}");
        }

        private void FrameworkElement_OnUnloaded(object sender, RoutedEventArgs e)
        {
            if (sender is ContentControl element)
                Trace.WriteLine($"Unloaded {element.Content}");
        }
```

2. Reduce the width of the application to make sure Buttons move to the secondary commands.
3. Increate the width of the application and notice that when the buttons are displayed again, both `Loaded` and `UnLoaded` event is raised.

### Expected behavior

`UnLoaded` event should not be raised

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by StephenLPeters** [comment]
Loaded/Unloaded events are asynchronous events and aren't guaranteed to be ordered the way you'd expect.  Additionally, when the icon moves from the overflow menu to the main menu it is unloading from the overflow menu.  So the unloaded event is expected and the framework does not guarantee that it will be delivered in the order you'd expect.
