### ISSUE TITLE
App failing to start with Fast fail Exception when Microsoft.Ui.Xaml.Controls used with  Foreground Sessions

### ISSUE THREAD

**Issue by sps014** [microsoft/microsoft-ui-xaml#6656]
### Describe the bug

Hello guys, my UWP app crashes fails to start with `FastFailException` `Operation Not Supported`  , actually i wanted to prevent my app from sleeping so i am using ExtendedForegroundSession API with 
```xml
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.0.0" MaxVersionTested="10.0.0.0" />
  </Dependencies>
 ...
      <rescap:Capability Name="extendedExecutionUnconstrained" />
```

if I remove Microsoft.Ui.Xaml.Control from app.xaml then app runs fine  without crashing,
remove  
```xml
 <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>
```

I don't want to remove modern UI elements to make my app work.
Please any suggestions regarding it?
Thanks in advanced

### Steps to reproduce the bug

Reproducing bus is easy
1. Create an UWP app and make it non suspending 
[Creating non suspending UWP app tutorial](https://docs.microsoft.com/en-gb/archive/blogs/mvpawardprogram/non-suspending-uwp-desktop-apps)
2. Add `Microsoft.Ui.Xaml` nuget package
3. Add Resources in app.Xaml
```xml
 <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>
```
4. Start app and now you will see app failing to start

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

**Comment by StephenLPeters** [comment]
@sps014 do you have a callstack with the crash? I suspect this has to do with the min/max tested version you've specified, but a callstack would be really helpful.

**Comment by sps014** [comment]
@StephenLPeters I have created an minimal reproduceable sample here : https://github.com/sps014/uwpTestMica
Actually debugger fails to attach so i am not able to send you call stack.
Hope this helps.
Thanks
