### ISSUE TITLE
AnimatedIcon does not dirty layout when Source changes.

### ISSUE THREAD

**Issue by StephenLPeters** [microsoft/microsoft-ui-xaml#6659]
AnimatedIcon does not dirty its layout when the source property changes which can cause icons to be rendered at very wrong sizes if you change the source property while the icon is in the tree, until something else dirties the layout.  The fix is to Invalidate measure when the source property changes.

![image](https://user-images.githubusercontent.com/7758786/151842303-3dafe781-50ee-4320-b02f-8ade4c466907.png)

**Comment by chingucoding** [comment]
Mind if I work on this? What would be the best way to write a test for this, change icon to something smaller/bigger and see if the layout changed?

**Comment by StephenLPeters** [comment]
Go for it! I think you can reproduce the issue by setting the source property from null to some AnimatedVisual in the Loaded event on the control. Also set some layout properties like MaxWidth=10 or something and you should see the icon rendering larger than should be allowed.  For a proper test... We probably need some internal test hook to push out the render size of the composition island as a property that the test can query.
