### ISSUE TITLE
ItemsRepeater fails to realize virtualized elements from bottom of list as items are removed from top of list

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#6661]
### Describe the bug

When removing items from a list hosted by an ItemsRepeater, virtualized items are not realized as they are needed, causing the UI to render empty space. Remaining items are not realized until nearly all items are removed, or window is resized.

### Steps to reproduce the bug

1. Build and deploy attached test app, ItemsRepeaterTestApp
2. Generate approximately 30 items using the Add Item button
3. Remove items from the top of the list using the X buttons until empty space appears
4. Observe debugger output - OnElementPrepared is not called until nearly all items are removed, then is called on remaining items in a batch.

[ItemsRepeaterTestApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7974378/ItemsRepeaterTestApp.zip)

### Expected behavior

ItemsRepeater should be realizing items as they are about to come into view.

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Still repros on latest WinUI 2.8.0-prerelease.220118001.

**Comment by StephenLPeters** [comment]
@ranjeshj FYI, thoughts on whats going on?

**Comment by axodox** [comment]
We have noticed the same thing when showing a list of strings in a ListBox with WindowsAppSDK 1.2.230217.4. We can work around with setting the ItemsPanelTemplate to a non-virtualizing StackPanel, since we do not have so many items in the list.

**Comment by stevenbrix** [comment]
what's the status here? we see this in our app consistently still with WindowsAppSDK 1.4

**Comment by stevenbrix** [comment]
FWIW it seems that increasing the `verticalCacheLength` seems to help alleviate the problem, although it will still happen. in general i find it's very easy to get an items repeater in a state where it renders random spaces which seem to be caused by it not realizing elements it should
