### ISSUE TITLE
Question: WinUI interfering with MIDI APIs

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/microsoft-ui-xaml#6663]
I am using the [`midiIn` ](https://docs.microsoft.com/en-us/windows/win32/api/mmeapi/nf-mmeapi-midiinopen) APIs to get a callback when I press notes on my connected (piano) keyboard. This works fine with a console application, but I never get any callbacks in my WinUI application. The midi objects are created in the `Application.OnLaunched` method, so they should have main thread affinity.

Does WinUI does not run a standard Win32 `PeekMessage`/`DispatchMessage` loop on the main thread? Is there a way to make it do so?

It would be possible to create a separate thread for my midi objects and run my own message loop there, but this is a good amount of extra complexity that I would rather avoid, and I'm not sure that would fix the issue.

Thanks for any suggestions

**Comment by tristanlabelle** [comment]
I might have spoken too fast, I added an artificial message loop after my call to `midiInStart` and I'm still not receiving callbacks. What could be different in a WinUI app preventing the callbacks? :/

```cs
        while (GetMessage(out var msg, default, 0, 0))
        {
            TranslateMessage(in msg);
            DispatchMessage(in msg);
        }

**Comment by tristanlabelle** [comment]
It appears to be a bug with the .NET debugger. I filed an issue below but I'll leave the WinUI team close this question in case they have insights.

https://github.com/dotnet/runtime/issues/64668

**Comment by StephenLPeters** [comment]
@MikeHillberg thoughts?
