### ISSUE TITLE
Discussion: Review assigned issues

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#6664]
# Discussion: Should assigned issues be (re-)reviewed? 

With so many open issues it can be hard to see what is being worked on and where progress is being made (or likely to be made)

Please can I request a full review of all open issues. 
I know this is a lot and will take time.
If not all, then:
- all unassigned issues 
- all issues assigned to people no longer on the team
- all assigned items that are still tagged as requiring triage.

When there are a lot of open issues it is easy for things to get lost or missed, and so it is important to keep on top of everything.

When issues are not managed or reviewed regularly, it can lead to comments like [this](https://github.com/microsoft/microsoft-ui-xaml/issues/1500#issuecomment-1026388986) where a highly requested item is now assumed to be abandoned because it is assigned to someone who is no longer on the team.

**Comment by kmgallahan** [comment]
https://youtu.be/k6WJmymqNKE?t=1990

**Comment by mrlacey** [comment]
> Discussed on the community call:
> 
> https://youtu.be/k6WJmymqNKE?t=1990
> 
> You were there, but for others to review.

That they're having these discussion internally and not in the open was part of my reason for creating this. :/

**Comment by MEK3DK** [comment]
I think it's fine you create this discussion, but don't expect much, it seems like the team is overwhelmed.

Just to fix basic stuff there is years of work and it does not seem like resources are added/available for this.

And yes I was also part of the community call.

**Comment by StephenLPeters** [comment]
@gabbybilka and @ryandemopoulos FYI
