### ISSUE TITLE
TabViewItem close buttons aren't square in Controlsv2 anymore

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#6666]
Check out any Terminal version 1.13+, or even in the XCG. 

![image](https://user-images.githubusercontent.com/18356694/152063979-84c0492b-31b5-4e1d-864d-fa9b8ebc228d.png)

(the contrast is VERY subtle, but the button hover outline is clearly rectangular)

For comparison, the old tab close button was much more square:
![image](https://user-images.githubusercontent.com/18356694/152064107-38dd51f2-fe60-4f13-a61b-20809371bb4f.png)

We're on [Microsoft.UI.Xaml.2.7.0-prerelease.210913003], Controlsv2. Terminal is XAML Islands, XCG isn't.

**Comment by hassaanmasood** [comment]
Tab Item close button design is aligned with other controls such as 'Search Button' in AutoSuggestBox or DropButton in Editable ComboBox. The new button is much more accessible than previous small button. It is big and easily clickable. Windows Terminal App itself is not yet updated to use the latest WinUI controls.

**Comment by zadjii-msft** [comment]
> Windows Terminal App itself is not yet updated to use the latest WinUI controls

I work on the Terminal, we're updating to these controls in this current upcoming release 😉 

I'm confident our users are going to file an issue that the buttons are no longer square, hence pre-emptively filing this upstream. I'm all for bigger buttons, but I'd still think they should be square.

For example, Edgium tabs:
![image](https://user-images.githubusercontent.com/18356694/152147685-837ca85d-4f1b-4847-94bc-615976e6d8e7.png)


Bigger that controlsv1, but still square.

**Comment by StephenLPeters** [comment]
@zadjii-msft have you tried to customize this value with light weight styling?

**Comment by StephenLPeters** [comment]
@chigy FYI

**Comment by zadjii-msft** [comment]
@StephenLPeters I haven't tried that yet. I'd bet it'd probably work. I just wanted to make sure this was on the radar as an intentional ControlsV2 change. I don't want other 3p developers to be surprised by this as well ☺️

**Comment by chigy** [comment]
The official design should be in the toolkit. https://aka.ms/figmatoolkit
