### ISSUE TITLE
Question: Migrating Store submissions from UWP (appx) to WinUI3 (msix)

### ISSUE THREAD

**Issue by andrewdewaal** [microsoft/microsoft-ui-xaml#6690]
What are the steps for migrating Microsoft Store submissions from APPX to MSIX?

For context:
Currently, we have a UWP app, and create APPX packages for Store submissions.

We are looking to migrate to using WinUI3. We have created a minimal test solution to create an MSIX package with the same certificate, package name, package display name, publisher, publisher display name, and package display name as the UWP app.

We have confirmed by installing a debug version of the UWP app, then the WinUI3 app, upgrades and points to the expected AppData/Local/Packages folder.

If we create an MSIX package for sideloading the WinUI3, install the app, and then find the app on the Microsoft Store, we see the "Open" option, which opens the installed WinUI3 app.

This tells us that we should be able to have a seamless transition from using APPX to MSIX, but were unable to find clear documentation regarding any considerations, steps, or known issues.

This is some of the documentation we have read through, but were unable to find anything directly regarding this sort of migration.
https://docs.microsoft.com/en-us/windows/msix/package/app-package-formats
https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare

Any advice would be greatly appreciated.
Thanks!

**Comment by StephenLPeters** [comment]
@gabbybilka and @ryandemopoulos FYI
