### ISSUE TITLE
[Windows 10] BackdropMaterial.ApplyToRootOrPageBackground not working on other control than Page

### ISSUE THREAD

**Issue by acouvert-msft** [microsoft/microsoft-ui-xaml#6692]
### Describe the bug

On Windows 10, if` mux:BackdropMaterial.ApplyToRootOrPageBackground="True" `is set on something different than a `Page`, the XAML rendering will not use the background color (`MicaController::sc_darkThemeColor `or `MicaController::sc_lightThemeColor`) as expected despite being propagated. The visible background color will actually be the one attached to the Window.

### Steps to reproduce the bug

```
<Page
    x:Class="Tests.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mux="using:Microsoft.UI.Xaml.Controls"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <UserControl mux:BackdropMaterial.ApplyToRootOrPageBackground="True" RequestedTheme="{x:Bind CurrentTheme.Value, Mode=OneWay}">
        <StackPanel x:Name="ThemePanel">
            <RadioButton
                Checked="OnThemeRadioButtonChecked"
                Content="Light"
                Tag="Light" />
            <RadioButton
                Checked="OnThemeRadioButtonChecked"
                Content="Dark"
                Tag="Dark" />
            <RadioButton
                Checked="OnThemeRadioButtonChecked"
                Content="Use system setting"
                IsChecked="True"
                Tag="Default" />
        </StackPanel>
    </UserControl>
</Page>
```

### Expected behavior

On Windows 11, mux:BackdropMaterial.ApplyToRootOrPageBackground="True" can be set on `UserControl `and it will behave as expected for both case of transparency or use of the fallback background color. 

I'd expect to be able to use this property on any control and  have a similar behavior on Windows 10.

### Screenshots

When switching to Dark theme, the background should be `MicaController::sc_darkThemeColor` but remains the Window default white one (which btw is different than the expected MicaController::sc_lightThemeColor).

![animation_win10_usercontrol](https://user-images.githubusercontent.com/61151817/153055295-b9ed7cec-93d6-4013-ab8f-b763814f9be3.gif)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@DmitriyKomin or @jevansaks is this expected/understood?

**Comment by jevansaks** [comment]
It depends what version of Windows 10. IIRC that logic relies on the ActualThemeChanged event which didn't appear until 10.0.16299.0. @acouvert-msft what version of Win10 are you running on? Is it <16299?

**Comment by acouvert-msft** [comment]
@jevansaks I got the issue on Windows 10 for at least 20H2 (19042.1526) and 21H2 (19044.1526). I didn't check other Windows 10  versions.

**Comment by jevansaks** [comment]
Hmmm ... I don't know, then. @StephenLPeters someone will need to debug. Sorry. :(
