### ISSUE TITLE
Visual Studio 16.10.0 breaks support for Xaml Islands Apps

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6699]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-16100-breaks-support-for/1634426)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.9.8]
Visual Studio 16.10.0 and above (including 17) break support for Xaml islands apps throwing Error APPX0501 as seen below.
The issue has also been reported [here](https://github.com/CommunityToolkit/Microsoft.Toolkit.Win32/issues/328)  and [here](https://github.com/michalleptuch/rounded-flyout/issues/1), but no workaround has been found thus far.
This is a frequently reported bug breaking xaml islands support for a lot of developers.

APPX0501	Validation error. error 80080204: App manifest validation error: Line 66, Column 27, Reason: The field "*[local-name()='Extensions']/*[local-name()='Extension']/*[local-name()='InProcessServer']/*[local-name()='ActivatableClass']" with value "Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication" must only be declared once. A duplicate exists on Line 60, Column 27.

Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX0501	Validation error. error 80080204: App manifest validation error: Line 190, Column 27, Reason: The field "*[local-name()='Extensions']/*[local-name()='Extension']/*[local-name()='InProcessServer']/*[local-name()='ActivatableClass']" with value "Microsoft.Toolkit.Win32.UI.XamlHost.XamlApplication" must only be declared once. A duplicate exists on Line 80, Column 27.	ModernFlyouts.Package	C:\Users\samue\Source\Repos\ModernFlyouts-0.11final\ModernFlyouts.Package\bin\x64\Debug\AppxManifest.xml	1

---
#### Feedback Bot on 1/11/2022, 07:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by atiyka** [comment]
Any estimation when will be this issue fixed?

**Comment by asklar** [comment]
@svetbonev it looks like this got moved from devcom, but this is a regression in vs 16.10 (even when using old WinUI packages). 
Can you help route this?

**Comment by atiyka** [comment]
[Here is the issue](https://github.com/CommunityToolkit/Microsoft.Toolkit.Win32/issues/328) about that app manifest validation error with the newest VS 2019 (also referenced in the post). I'm not sure where has to be posted/mentioned to be fixed this issue in VS.

**Comment by asklar** [comment]
@atiyka For VS to take a fix, it would need to be filed in the Developer Community website, here's the link to the original post: https://developercommunity2.visualstudio.com/t/Visual-Studio-16100-breaks-support-for/1634426?
Maybe there needs to be another issue filed in DevCom, since the original one was closed, hence why I asked Svet to help route it :)

**Comment by atiyka** [comment]
oh yeah, sorry, I didn't observed you not asking from me :)

**Comment by TamBuiWork** [comment]
@StephenLPeters Can I better understand why this issue was closed?  If it's because this was filed to the [Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-16100-breaks-support-for/1634426), that ticket's supposed "resolution" is to refer to _this_ Github issue 6699. As far as I can tell, this issue still exists in Visual Studio 2019 version 16.11.

**Comment by michael-hawker** [comment]
@StephenLPeters @asklar the VS issue is closed as a duplicate of this one, and this one is closed as external. Something needs to be open somewhere no? Was originally reported here: https://github.com/CommunityToolkit/Microsoft.Toolkit.Win32/issues/328

**Comment by asklar** [comment]
@srdjanjovcic  I think this should be tracked in DevCom, agree? / is this something your team might be tracking already?

**Comment by srdjanjovcic** [comment]
@asklar I'll start email thread with relevant people from my team (it seems that I cannot ping them here?)
