### ISSUE TITLE
VS can't load a project with Microsoft.UI.Xaml.Controls

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#670]
I'm trying to create a WPF project using the new UI Xaml controls following the steps indicated here:
https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started
The first problem is that the NuGet package manager starts installing it to the project but throws and error and asks to restart VS to finish.
When the solution loads again the projct with this package fails to load with an error that basically says &quot;... Version string portion was too short or too long ... &quot;.
Here is the ofending line from the . CSPROJ file. Deleting it the project loads fine, but obviously the controls are not accessible.
&lt;Import Project=&quot;.. \packages\Microsoft.UI.Xaml.2.1.190405004.2\build\Microsoft.UI.Xaml.props&quot; Condition=&quot;Exists('.. \packages\Microsoft.UI.Xaml.2.1.190405004.2\build\Microsoft.UI.Xaml.props')&quot; /&gt;

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/559516/vs-cant-load-a-project-with-microsoftuixamlcontrol.html
VSTS ticketId: 888496_
_These are the original issue comments:_

Visual Studio Feedback System on 5/7/2019, 01:24 AM (36 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Niel Sutton [MSFT] on 5/7/2019, 06:03 PM (20 hours ago): <p>Seeing the same issue...</p><p>Output Windows shows this:</p><p><em>Added package 'Microsoft.UI.Xaml.2.1.190405004.2' to 'packages.config'<br>Install failed. Rolling back...<br>Removed package 'Microsoft.UI.Xaml 2.1.190405004.2' from 'packages.config'</em></p><p>Full version info:</p><p>Microsoft Visual Studio Enterprise 2019 Preview<br>Version 16.1.0 Preview 3.0<br>VisualStudio.16.Preview/16.1.0-pre.3.0+28902.138<br>Microsoft .NET Framework<br>Version 4.8.03752<br><br>Installed Version: Enterprise<br><br>Visual C++ 2019   00435-60000-00000-AA492<br>Microsoft Visual C++ 2019<br><br>ADL Tools Service Provider   1.0<br>This package contains services used by Data Lake tools<br><br>Application Insights Tools for Visual Studio Package   9.0.20307.1<br>Application Insights Tools for Visual Studio<br><br>ASP.NET and Web Tools 2019   16.1.373.27518<br>ASP.NET and Web Tools 2019<br><br>ASP.NET Web Frameworks and Tools 2019   16.1.373.27518<br>For additional information, visit https://www.asp.net/<br><br>Azure App Service Tools v3.0.0   16.1.373.27518<br>Azure App Service Tools v3.0.0<br><br>Azure Data Lake Node   1.0<br>This package contains the Data Lake integration nodes for Server Explorer.<br><br>Azure Data Lake Tools for Visual Studio   2.3.9000.0<br>Microsoft Azure Data Lake Tools for Visual Studio<br><br>Azure Functions and Web Jobs Tools   16.1.373.27518<br>Azure Functions and Web Jobs Tools<br><br>Azure Stream Analytics Tools for Visual Studio   2.3.9000.0<br>Microsoft Azure Stream Analytics Tools for Visual Studio<br><br>C# Tools   3.1.0-beta3-19223-09+ce8ac3f71fa4c73b78cf8218d58b322bdbdfa1c9<br>C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.<br><br>Common Azure Tools   1.10<br>Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.<br><br>Cookiecutter   16.1.19113.1<br>Provides tools for finding, instantiating and customizing templates in cookiecutter format.<br><br>Fabric.DiagnosticEvents   1.0<br>Fabric Diagnostic Events<br><br>GitHub.VisualStudio   2.9.1.7781<br>A Visual Studio Extension that brings the GitHub Flow into Visual Studio.<br><br>IntelliCode Extension   1.0<br>IntelliCode Visual Studio Extension Detailed Info<br><br>Microsoft Azure HDInsight Azure Node   2.3.9000.0<br>HDInsight Node under Azure Node<br><br>Microsoft Azure Hive Query Language Service   2.3.9000.0<br>Language service for Hive query<br><br>Microsoft Azure Service Fabric Tools for Visual Studio   2.5<br>Microsoft Azure Service Fabric Tools for Visual Studio<br><br>Microsoft Azure Stream Analytics Language Service   2.3.9000.0<br>Language service for Azure Stream Analytics<br><br>Microsoft Azure Stream Analytics Node   1.0<br>Azure Stream Analytics Node under Azure Node<br><br>Microsoft Azure Tools   2.9<br>Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2<br><br>Microsoft Continuous Delivery Tools for Visual Studio   0.4<br>Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.<br><br>Microsoft JVM Debugger   1.0<br>Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines<br><br>Microsoft Library Manager   1.0<br>Install client-side libraries easily to any web project<br><br>Microsoft MI-Based Debugger   1.0<br>Provides support for connecting Visual Studio to MI compatible debuggers<br><br>Microsoft Visual C++ Wizards   1.0<br>Microsoft Visual C++ Wizards<br><br>Microsoft Visual Studio Tools for Containers   1.1<br>Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.<br><br>Microsoft Visual Studio VC Package   1.0<br>Microsoft Visual Studio VC Package<br><br>Node.js Tools   1.5.10424.1 Commit Hash:c3ce0ae0b29c0b3a755ffc12f8a685fe7ddd3600<br>Adds support for developing and debugging Node.js apps in Visual Studio<br><br>NuGet Package Manager   5.1.0<br>NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.<br><br>ProjectServicesPackage Extension   1.0<br>ProjectServicesPackage Visual Studio Extension Detailed Info<br><br>Python   16.1.19113.1<br>Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.<br><br>Python - Conda support   16.1.19113.1<br>Conda support for Python projects.<br><br>Python - Django support   16.1.19113.1<br>Provides templates and integration for the Django web framework.<br><br>Python - IronPython support   16.1.19113.1<br>Provides templates and integration for IronPython-based projects.<br><br>Python - Profiling support   16.1.19113.1<br>Profiling support for Python projects.<br><br>ResourcePackage Extension   1.0<br>ResourcePackage Visual Studio Extension Detailed Info<br><br>ResourcePackage Extension   1.0<br>ResourcePackage Visual Studio Extension Detailed Info<br><br>Snapshot Debugging Extension   1.0<br>Snapshot Debugging Visual Studio Extension Detailed Info<br><br>SQL Server Data Tools   16.0.61904.23160<br>Microsoft SQL Server Data Tools<br><br>Test Adapter for Boost.Test   1.0<br>Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.<br><br>Test Adapter for Google Test   1.0<br>Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.<br><br>ToolWindowHostedEditor   1.0<br>Hosting json editor into a tool window<br><br>TypeScript Tools   16.0.10422.2001<br>TypeScript Tools for Microsoft Visual Studio<br><br>Visual Basic Tools   3.1.0-beta3-19223-09+ce8ac3f71fa4c73b78cf8218d58b322bdbdfa1c9<br>Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.<br><br>Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19224.1+a5510fb603e5014e8515e4e53ec558b40e415f7c<br>Microsoft Visual F# Tools 10.4 for F# 4.6<br><br>Visual Studio Code Debug Adapter Host Package   1.0<br>Interop layer for hosting Visual Studio Code debug adapters in Visual Studio<br><br>Visual Studio Tools for CMake   1.0<br>Visual Studio Tools for CMake<br><br>Visual Studio Tools for CMake   1.0<br>Visual Studio Tools for CMake<br><br>Visual Studio Tools for Containers   1.0<br>Visual Studio Tools for Containers<br><br>Visual Studio Tools for Kubernetes   1.0<br>Visual Studio Tools for Kubernetes</p>

_These are the original issue solutions:_
(no solutions)

**Comment by jevansaks** [comment]
@marb2000 @ocalvo Is this a scenario that's expected to work? If so, we'll need your help to make it so. Otherwise maybe you can help make the error message more clear?

Another report came in via #664.

**Comment by ocalvo** [comment]
This is a new scenario, by default the Targets file of MUXC assumes that the Msbuild TargetFramework property has been set.

I should not have this assumption and we should add a condition and if it's not set then assume 19H1 as this is the first version of Windows where MUXC can be references from a non UWP project.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CarlSharp** [comment]
Thank you for looking into this. In the meantime, is there a suggested work around for this?

Will explicitly setting TargetFramework on the project allow the package to function as expected?

**Comment by jevansaks** [comment]
@CarlSharp what is the intended goal here? Are you trying to make a .NET Core 3 UWP app that uses Microsoft.UI.Xaml? I don't think .NET Core 3 works in UWP apps yet.

**Comment by CarlSharp** [comment]
@jevansaks, I was curious about what was mentioned above:
>... this is the first version of Windows where MUXC can be references from a non UWP project.

I was looking to reference page file content from a separate project - namely for testing. Alternatively, I've managed to get a shared library of .xaml files working between a Universal Windows and Unit Test App project. Which in retrospect appears to a better solution.

Any other suggestions are welcome. Thank you for taking the time.

**Comment by jevansaks** [comment]
Yes, I would agree that using the Unit Test project is the right approach for what you want to do. So it sounds like you're unblocked?
