### ISSUE TITLE
Indeterminate ProgressBar plays animations while Visibility is Collapsed

### ISSUE THREAD

**Issue by alexhinz** [microsoft/microsoft-ui-xaml#6702]
### Describe the bug

The WinUI `ProgressBar` plays its Indeterminate animation continuously while its Visibility is Collapsed. This incurs an unnecessary performance load on DWM.exe while the animation is not in use from the user's perspective.

Note that the WUXC ProgressBar [had a similar bug in Win 8, which was fixed](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.ProgressBar?view=winrt-22000#notes-for-windows-8x). The MUXC ProgressBar does not appear to similarly monitor and factor in its Visibility when updating VisualStates, so it regressed relative to recent versions of WUXC ProgressBar.

I believe the workaround is similar to that of the Win 8 WUXC ProgressBar. When collapsing the MUXC ProgressBar, also set `IsIndeterminate="False"`.

### Steps to reproduce the bug

This snippet reproduces the continuous animation:
```xml
<muxc:ProgressBar
    IsIndeterminate="True"
    Visibility="Collapsed" />
```

My application's repro is using the 2.8 prerelease.

### Expected behavior

When the MUXC ProgressBar is set to `Visibility="Collapsed"`, the animation is paused, similar to what is done in WUXC ProgressBar. For example, it could go to a VisualState that does not use a `Storyboard` with `RepeatBehavior="Forever"`.

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by StephenLPeters** [comment]
@karenbtlai FYI. @ranjeshj easy perf gain

**Comment by chingucoding** [comment]
I would like to look into this.
