### ISSUE TITLE
Setting `ScrollViewer`'s `VerticalScrollBarVisibility` to `Visible` does not produce implied effect

### ISSUE THREAD

**Issue by marwalsch** [microsoft/microsoft-ui-xaml#6703]
### Describe the bug

When a `ScrollViewer`'s `VerticalScrollBarVisibility` is set to `Visible`, it apparently behaves in the exact same manner as in `Auto` state:
- The Scrollbar is visible when the content is actually scrollable;
- the scrollbar disappears in the opposite case.

However, in compliance with the enum's corresponding value the scrollbar should always be present, even in the latter case (and reach its full width).

Even though I have the suspicion this is by design the API implicates otherwise.

### Steps to reproduce the bug

- Set a `ScrollViewer`'s `VerticalScrollBarVisibility` to `Auto`/`Visible`;
- Observe how the bar disappears when content is not actually scrollable (just like in auto mode).

### Expected behavior

Setting `VerticalScrollBarVisibility` to `Visible` should always display the bar.

### Screenshots

![image](https://user-images.githubusercontent.com/72074423/153592652-e46d573e-c240-4b0d-95c2-c8b0be00f53c.png)

![image](https://user-images.githubusercontent.com/72074423/153592723-70e5d302-cc7f-43c8-95e4-ed4939604514.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by kmgallahan** [comment]
The ScrollViewer's vertical ScrollBar container's visibility is bound [here](https://github.com/microsoft/microsoft-ui-xaml/blob/9aedb008999ce3b15546c5b467e97ef2c7e8f770/dev/CommonStyles/ScrollViewer_themeresources.xaml#L238) and set [here](https://github.com/microsoft/microsoft-ui-xaml/blob/9aedb008999ce3b15546c5b467e97ef2c7e8f770/dev/ScrollView/ScrollView.cpp#L1628). No apparent logic to check VerticalScrollBarVisibility.

**Comment by StephenLPeters** [comment]
Confusingly, what you've linked to the ScrollView code (a winui2 control) where as the ScrollViewer (a system xaml control) is the control in question.  ScrollViewer's scrollbar integration is a little wonky, and is one of the things that was fixed in ScrollView.  @RBrid correct me if i'm wrong, it is by design that the auto and visible behave the same here.  I think there are some differences between the enum values though... do you know what they are?

**Comment by RBrid** [comment]
It seems to work for me as expected: even when using ScrollBarVisibility.Visible, the user needs to hover over the scrollbar area for a couple seconds before it appears.

**Comment by kmgallahan** [comment]
@RBrid I believe the issue was created because the OP wants the scrollbar to always be visible, even if no scrolling can be performed. That would be the differentiation between using Auto and Visible.

> Observe how the bar disappears when content is not actually scrollable (just like in auto mode).

**Comment by marwalsch** [comment]
Thanks for following up.

@RBrid 
@kmgallahan is right. I would argue that `ScrollBarVisibility.Visible` still requiring a hover to have it appear at all might be a good fit as long as `ScrollBarVisibility.Auto` exists. I noticed as well that even when hovering it in a `ScrollViewer` not being overflown, the arrows appear, but the actual bar does not (which I'd expect to at full length at this point).
Are there any difference between these two values at all?

**Comment by marwalsch** [comment]
@RBrid 
Thanks, I wasn't aware of the windows-wide scrollbar setting, now it makes more sense. I assume there is no way to activate this setting on application scope regardless of the Windows setting, the same way we can force a specific theme on application root?
