### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by just-a-mango** [microsoft/microsoft-ui-xaml#6708]
### Describe the bug

When creating a new "Blank App, Packaged (WinUI 3 in Desktop)", and installing Microsoft.UI.Xaml using NuGet, the app crashes, with this error message: 
DEP1000: Cannot copy file "C:\Users\mango\.nuget\packages\microsoft.ui.xaml\2.7.0\buildTransitive\..\lib\uap10.0\Microsoft.UI.Xaml.winmd" to layout "\Microsoft.UI.Xaml.winmd". UnauthorizedAccessException - Access to the path '\Microsoft.UI.Xaml.winmd' is denied. [0x80070005]

### Steps to reproduce the bug

1. Create a new "Blank App, Packaged (WinUI 3 in Desktop)"
2. Install any version of Microsoft.UI.Xaml using NuGet
3. Try to start

### Expected behavior

The app was supposed to launch fine

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [x] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

**Comment by wernerbuchner** [comment]
Same is happening to me.... VS22 17.06., Microsoft.UI.XAML 2.7.0 on a windows 11 machine

**Comment by just-a-mango** [comment]
> Same is happening to me.... VS22 17.06., Microsoft.UI.XAML 2.7.0 on a windows 11 machine

Same, Windows 11

**Comment by asklar** [comment]
You can't mix and match winui3 and winu2.x, they are not compatible. If your project template is for winui3, then it already references winui3 (included with windows app sdk).

**Comment by just-a-mango** [comment]
Then how do I create a WinUI 2 xaml app without win ui 3 referenced ?

**Comment by asklar** [comment]
Just create a UWP project in File->New project
![image](https://user-images.githubusercontent.com/22989529/154833244-47560834-58e5-4a5a-9a30-74b7bd933bc1.png)

here's a getting started: https://devblogs.microsoft.com/ifdef-windows/building-your-first-uwp-application/

**Comment by just-a-mango** [comment]
> @just-a-mango Just create a UWP project in File->New project
> 
> ![image](https://user-images.githubusercontent.com/22989529/154833244-47560834-58e5-4a5a-9a30-74b7bd933bc1.png)
> 
> 
> 
> here's a getting started: https://devblogs.microsoft.com/ifdef-windows/building-your-first-uwp-application/

Oh thanks, didn't know that, will check it out!
