### ISSUE TITLE
GoToState should take FrameworkElement as a parameter but takes Control

### ISSUE THREAD

**Issue by plonkaadam** [microsoft/microsoft-ui-xaml#6710]
### Describe the bug

It's possible to attach `VisualStateManager.VisualStateGroups` to any framework element (such as Grid) but not possible to change VisualState by using `VisualStateManager.GoToState` cause it requires `Microsoft.UI.Xaml.Controls.Control` as a parameter.

### Steps to reproduce the bug

1. Set VisualStateGroups to Grid element
2. Try to change Grid VisualState from code behind

### Expected behavior

GoToState should take FrameworkElement as a parameter

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment]
This is because VSM is tied to a template, not an element.  VSM has a requirement that it be placed on the root element of a control template in order to work, so while it can be placed on any framework element, it only functions on framework elements that are associated with controls.

**Comment by StephenLPeters** [comment]
@plonkaadam what is the reason you want VSM on arbitrary Framework elements?
