### ISSUE TITLE
PivotItem IsEnabled="False" has no effect

### ISSUE THREAD

**Issue by orapps44** [microsoft/microsoft-ui-xaml#6711]
### Describe the bug

When setting PivotItem property IsEnabled="False" pivot control still alow user to navigate to the disabled PivotItem.

### Steps to reproduce the bug

//XAML
```text
<Pivot Title="EMAIL">
    <PivotItem Header="All">
        <TextBlock Text="all emails go here." />
    </PivotItem>
    <PivotItem Header="Unread"  IsEnabled="False">
        <TextBlock Text="unread emails go here." />
    </PivotItem>
    <PivotItem Header="Flagged">
        <TextBlock Text="flagged emails go here." />
    </PivotItem>
    <PivotItem Header="Urgent">
        <TextBlock Text="urgent emails go here." />
    </PivotItem>
</Pivot>
```

### Expected behavior

When PivotItem property IsEnabled is set to false, PivotItem should be visible but disabled, and PivotItem selection shouldn't be allowed.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2018 Update (17763)

**Comment by StephenLPeters** [comment]
What input methods allow you to navigate to that item? Mouse, touch, keyboard, programmatic?

**Comment by orapps44** [comment]
Input method used : Mouse

**Comment by StephenLPeters** [comment]
Pivot isn't in active development so I don't think this will get addressed over other issues any time soon.

**Comment by HO-COOH** [comment]
Encountered the same issue. This should get repopened
