### ISSUE TITLE
Lose NavigationViewItem selection after setting an item property

### ISSUE THREAD

**Issue by rcohn** [microsoft/microsoft-ui-xaml#6712]
### Describe the bug

I have a small demo that allows me to change a property on a NavigationViewItem.  This is implemented using an ObservableCollection<Category> object, where Category is a class that derives from INotifyPropertyChanged.  It has one changeable property: Name.

The property change works as expected, but I then lose the item selection until I click on it again.

Why does the item selection go away when I change its property?  Is there a workaround to restore the selection programmatically? I've tried just setting SelectedItem on the navigationview, but that doesn't work.

### Steps to reproduce the bug

1. Start the app
2. Click on the first button in the NavigationViewItem list (item becomes selected at this point)
3. Click the "Test Name Change" button
4. The item's name changes to "blah blah blah" as expected, **but the item is no longer selected**
5. Clicking on the item restores the selection

### Expected behavior

1. Start the app
2. Click on the first button in the NavigationViewItem list (item becomes selected at this point)
3. Click the "Test Name Change" button
4. The item's name changes to "blah blah blah" as expected **and the item remains selected**

### Screenshots

![image](https://user-images.githubusercontent.com/2237248/153824293-6fd8f4d0-d0a0-4980-b48c-923cc393ec84.png)
[MainWindow.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8058932/MainWindow.zip)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

I attached a screenshot of the handler that sets the Name property on the selected item.
Also attached the MainWindow.xaml and MainWindow.xaml.cs files for the project.

**Comment by StephenLPeters** [comment]
@ojhad thoughts?
