### ISSUE TITLE
Star emoji ⭐ not rendered correctly

### ISSUE THREAD

**Issue by Marv51** [microsoft/microsoft-ui-xaml#6713]
### Describe the bug

The star emoji ⭐ ("White Medium Star", U+2B50). Does not get rendered correctly (see screenshot below).
It is missing the yellow color and is a lot smaller than other emojis.

All other emoji that I tried work as expected.

### Steps to reproduce the bug

```xaml
<Button>&#x2B50;</Button>
```

You can also see this bug when you copy a star emoji (or use the emoji picker) into the search field in the "WinUI 3 Controls Gallery". However, this issue is not specific to the sample app and reproduces for me in all places that I tried.

### Expected behavior

The yellow Microsoft style star emoji should be rendered.
https://emojipedia.org/star/

### Screenshots

![image](https://user-images.githubusercontent.com/471338/153832242-099daca3-34fa-4b12-94e4-2e14f9c060dc.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 21H2 (22000.526)

### Additional context

Please let me know if any more information on this issue would be helpful to solve this issue.

As the star is quite old (Unicode 5.1) I tried some other emoji from that generation and even older ones, but I was not able to find any other emoji that have the same issue.

**Comment by castorix** [comment]
You must set the font, like :
` <Button x:Name='testButton' 
         FontFamily='Segoe UI Emoji' FontSize='20'
         Content='&#x2B50;' 
         />`
![Button_Star_Emoji](https://user-images.githubusercontent.com/22345506/154011820-024f8d26-01f2-4a6f-b087-ee65f3c5689c.jpg)

**Comment by Marv51** [comment]
@castorix Interesting, I guess my issue is more that all other emoji work without specifying the "Segoe UI Emoji" font, except the star?
Maybe the fallback logic to switch to the emoji font is having an issue?
As a counter example: [☺️ (White Smiling Face, 0x263A)](https://emojipedia.org/emoji/%E2%98%BA/) has a similar unicode codepoint, is also not included in Segoe UI but nevertheless renders perfectly in WinUI 3.
![image](https://user-images.githubusercontent.com/471338/154023502-73150dde-daa4-4f6d-9068-4da2d2293b09.png)

**Comment by castorix** [comment]
Yes, weird
When no font is specified, it uses "Segoe UI" and  both should be colored, acording to : https://www.fileformat.info/info/unicode/char/2b50/index.htm
https://www.fileformat.info/info/unicode/char/263a/index.htm

**Comment by StephenLPeters** [comment]
@licanhua @MarissaMatt @codendone FYI

**Comment by codendone** [comment]
I believe this behavior is by design. The Segoe UI font includes the star glyph, which is not colored. Because it has the glyph, font fallback will not be involved and won't find/use the more colorful glyph from the Segoe UI Emoji font. Explicitly specifying Segoe UI Emoji is the right solution.

**Comment by Marv51** [comment]
@codendone Where should I file a bug to remove that star glyph from Segoe UI? It is not what the customer expects. When customers copy text from many places (iOS, Android, Firefox, Word, etc...) it looks broken.

**Comment by codendone** [comment]
@Marv51 Even if the font owners wanted to remove the glyph, they can't do it at this point because it would be a breaking change which could negatively impact any app using the font. We're unfortunately stuck with this behavior at this point.

**Comment by mqudsi** [comment]
This is by-design from Unicode. You need to use the variation selector codepoint to force the colored emoji to show.

(So you put the start emoji and the next character (before the space or anything) should be U+FE0F)
