### ISSUE TITLE
Zoom stops working intermittently

### ISSUE THREAD

**Issue by HavenDV** [microsoft/microsoft-ui-xaml#6717]
### Describe the bug

In some places (but only sometimes) the application stops responding to the torsion of the wheel. This manifests itself both when using `ScrollViewer ZoomMode="Enabled"` and when using events.
However, the UWP app with the same code works fine.

### Steps to reproduce the bug

[ZoomIssue.zip](https://github.com/microsoft/WindowsAppSDK/files/8052701/ZoomIssue.zip)

1. Build and run H.OxyPlot.Apps.WinUI app
2. Hold Ctrl and try turning the mouse wheel while in different places. In some places (but only sometimes) the application stops responding to the torsion of the wheel.
3. Here is a UWP project for comparison

### Expected behavior

Like UWP

### NuGet package version

1.0.0

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

**Comment by HavenDV** [comment]
The issue has been moved from another repository and is likely to be drowned in the list of other issues. I am writing this post to raise an issue.

**Comment by StephenLPeters** [comment]
@RBrid FYI, could also be a pointer event issue.. @JJBrychell

**Comment by HavenDV** [comment]
Up

**Comment by ranjeshj** [comment]
@HavenDV there have been several fixes to the scroll controls since 1.0. Can you please try the latest 1.5 stable build and see if this still repros. Thanks you!
