### ISSUE TITLE
Window does not resize when being dragged between displays with different DPI

### ISSUE THREAD

**Issue by Balkoth** [microsoft/microsoft-ui-xaml#6720]
### Describe the bug

The main application window does not resize itself when being dragged between displays with different DPI.

Primary is a 4K 150% DPI display.
Secondary is a FHD 100% DPI display.

### Steps to reproduce the bug

1.) Create a new WinUI 3 app with the template: Blank App, Packaged (WinUI 3 in Desktop)
2.) Build and run the app
3.) Move the app between two displays with differing DPI settings

### Expected behavior

The main app window should resize.

### Screenshots

The main app window stays the same on all displays.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 10 version 2004 (19041, May 2020 Update)

### IDE

Visual Studio 2022

**Comment by Balkoth** [comment]
This is still not fixed in https://github.com/microsoft/WindowsAppSDK/discussions/2331

**Comment by dotMorten** [comment]
For what it's worth, here's how I handled it in WinUIEx:
https://github.com/dotMorten/WinUIEx/commit/74b9de2d1a470bdf4c3d736f61d4f0a47e715d40
Basically detect WM_DPICHANGE from the windows messages, then grab the windows size, device by old dpi and multiply by new dpi.

The entire AppWindow API around window sizing should have been in device independent units. Not sure why it was exposed as uint raw pixels - no one wants to work in those units.

**Comment by Balkoth** [comment]
I appreciate your support, but bugs like this should have never made it into the first stable release. The fact that it is still not fixed nearly half a year and 3 point fixes is a real downer. Remember this is basic windowing functionality, dragging a window from one screen to another is nothing that is special.

**Comment by marb2000** [comment]
The **PR with the functionality is ready for the next shipping vehicle** which is WinAppSDK 1.2. It doesn't meet the bar for 1.1 at this point because 1.1 Preview3 is practically done (and Stable is only for new supercritical crashes)

The workaround proposed by @dotMorten is correct. WM_DPICHANGE is the message that you need to listen to and resize the window based on the dpi.

**Comment by Balkoth** [comment]
@dotMorten 
Did you try your fix for yourself? If i use the current WinUI3 1.0.3 and WinUIEx 1.4 in a fresh created app by just replacing the default Window base with WindowEx in MainWindow.cs and MainWindow.xaml.cs the app crashes when being dragged between monitors with different DPI settings.

**Comment by dotMorten** [comment]
@Balkoth Figured it out and published an update.

**Comment by Balkoth** [comment]
https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged

Has this always been there? I saw your implementation looks like the suggested c++ code there. I worked around it by limiting the amount of handled WM_DPICHANGED messages to 1 per 100ms an locking on the firtst receive. Will try this approach and report back.

**Comment by dotMorten** [comment]
@Balkoth Please discuss this in the linked WinUIEx issue above

**Comment by Balkoth** [comment]
@marb2000 
Has the fix made it into v1.1.0? I upgraded my project and removed my workaround and the window seems to resize now.

**Comment by Balkoth** [comment]
I still would like to know if it is now safe with v1.1.2 to remove the workaround and rely on the framwork itself?

**Comment by marb2000** [comment]
Finally, we were able to add it to 1.1.2. Feel free to open it again in case it didn't work for you.
