### ISSUE TITLE
Question: Winui community call tomorrow? (16th)

### ISSUE THREAD

**Issue by MEK3DK** [microsoft/microsoft-ui-xaml#6722]
At the end of the last community call it was stated that the next one would be tomorrow on the 16th of february, but there is no post about it here and nothing on YouTube.

Will it happen or?

**Comment by kmgallahan** [comment]
@gabbybilka

**Comment by gabbybilka** [comment]
@MEK3DK No, no call tomorrow. We've needed to cancel February's community call as we weren't able to gather everything we needed to for the call and are full steam ahead on servicing 1.0 and developing 1.1. Our next call will be March 16th. I'll make an announcement post!
