### ISSUE TITLE
📢 Announcement: Next WinUI Community Call on March 16, 2022

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#6726]
As asked in #6722, we are skipping our WinUI Community Call previously announced for February 16 and working towards our next call the third week of March: **March 16**. As usual, closer to March 16th, we'll publish an announcement with the agenda and invitation for questions to be answered on the call.

This month we weren't able to gather everything we needed for hosting a community call and have been focusing on our upcoming releases:
- Finding and fixing bugs for WinAppSDK 1.0 servicing
- Working towards WinUI 2.8 with WebView2
- Working towards WinAppSDK 1.1 with ETA of Q2 of 2022.

We look forward to seeing you in March!

**Comment by wbokkers** [comment]
Skipping a community call to find an fix bugs, pleases me a lot.
Issues that plague our users the most:
- layout cycle crashed due to a scrollviewer bug: https://github.com/microsoft/microsoft-ui-xaml/issues/6218
- drag/drop crashes: https://github.com/microsoft/microsoft-ui-xaml/issues/4574
- navigation view issues (when using top navigation): https://github.com/microsoft/microsoft-ui-xaml/issues/6626
- Recently I found that a lot of our users run into an issue with the clipboard: https://github.com/microsoft/microsoft-ui-xaml/issues/6754
-

**Comment by fox62843** [comment]
@gabbybilka 
Sorry to bother you.

Currently, it seems that WinUI development is having difficulty.

In a similar story, Google has created a mechanism to develop Windows applications with Flutter 2.10.
It seems that FluentUI can also be used, and I personally feel that we are coming to a situation where I don't see any merit in using WinUI 3.0.

The situation is that Microsoft and Google are separately developing a mechanism to easily develop Windows applications, but couldn't they have foreseen this would happen?
Shouldn't Microsoft have had a discussion with Google beforehand?

As someone who wants to create Windows applications with FluentUI, I feel very frustrated.

**Comment by michael-hawker** [comment]
@gabbybilka can this issue be pinned for visibility?

**Comment by gabbybilka** [comment]
@wbokkers Thanks for the prioritized list of bugs that are crashing users in your app. I'll reach out to get some more eyes on them.

@fox62843 Thanks for the question around Fluent UI in Flutter, I'll add this to our list of questions to address at our next community call.

@michael-hawker Pinned, I'll leave it up until the next call announcement, thanks!

**Comment by nikolayvpavlov** [comment]
We need to hear what the actual commitment of Microsoft on Windows App SDK and WinUI 3.0 is.  

1. Are there Microsoft Windows applications (like, Notepad) developed in WinUI 3?
2. What is Microsoft's actual commitment, when news on projects like One Outlook (Project Monarch) is reportedly built on web technologies and not native?  If Microsoft are not basing their core products on WinUI, why should developers do so?
3. Looking at the number of commits and active contributors, it looks like WinUI 3 is being developed by a handful of people only, which makes it hard to believe that WinUI 3 is really the next UI platform.  Looks like more of a hobbyist project.

This year I will need to make a decision on how to modernize a WPF app in our core product.  How can I be sure WinUI 3 is the way to go?

**Comment by Jimbo99** [comment]
> This year I will need to make a decision on how to modernize a WPF app in our core product. How can I be sure WinUI 3 is the way to go?

I'm in a similar boat - looking to release a (what was going to be UWP) project that needs to run on Windows & Linux platforms. The more I go through the conversion process to WinUI 3 (and Windows App SDK) the less confidence I have in it, to be frank.

I would very much like reassurance Microsoft is completely committed to WinUI 3? And that it will be receiving more resources from Microsoft to make it more robust and to progress it?

**Comment by wbokkers** [comment]
@gabbybilka Thank you, Gabby! As soon as these issues are addressed, it gives me confidence that WinUI 3 is the way forward for our company. Right now it's very unstable. Our WinUI app is quite large and probably it's the largest code base around using WinUI 3. It would be a major pain if we need to backtrack on our decision and port all of our code to WPF.

**Comment by pjmlp** [comment]
I have already moved back to Web development and focused on cross platform middleware for the few native applications I might still do for Windows, UWP management (including how Windows 11 is being pushed) has burned me  in investing any resources into anything WinUI going forward.

So what I am curious to know, specially given the track of single commits per day across WindowsUI, Cs/WinRT, C++/WinRT, lack of designer, deprecating C++/CX without comparable tooling in C++/WinRT for longer than six years, and with WinUI 3.0 being at least two years away of Forms/WPF parity, requiring code rewrites (yet again), is there any message for the disappointed crowd, burned by all rewrites and left turns since Windows 8, that should convince us to reconsider having moved on?

Concrete message, telling it will get better isn't worthwhile, it has already been repeated multiple times at several BUILDs since Windows 8, after each turn.

**Comment by fox62843** [comment]
Windows11はWinUI3の元に成り立ってるOSだと思っているのですが、合ってますか？

もしそうなら、時間がかかってもProject Reunionは成功させないといけないと思っています。
違うなら、Googleと手を組むべきだと思います。

**Comment by fox62843** [comment]
I believe Windows 11 is the OS that WinUI3 is based on, am I right?

If so, I think Project Reunion must succeed even if it takes a long time.
If not, I think you should join forces with Google.

**Comment by pjmlp** [comment]
@fox62843 Apparently Windows 11 is still relying on UWP, that is why we are seeing WinUI 2.x.releases.

**Comment by fox62843** [comment]
@pjmlp 

Very hard to believe...
Then I wouldn't be surprised if the future comes when I have to choose Flutter.

**Comment by pjmlp** [comment]
@fox62843 So here is some help for you to believe, about the new Windows 11 store being built with UWP and not WinUI 3.0.

https://www.windowslatest.com/2021/07/03/windows-11s-microsoft-store-drops-html-for-full-xaml-experience

> With Windows 11, Microsoft is replacing the existing Store with a new Store that’s written in XAML/C# and it’s fully “**UWP**”, according to Microsoft officials.

**Comment by wbokkers** [comment]
UWP and WinUI 3 are not really competitors. If you want a packaged sandboxed app that does not need raw win32 capabilities, you still should use UWP instead of WinUI 3.. So I see no issue in selecting UWP instead of WinUI 3 if UWP is sufficient for what you want to achieve.

**Comment by pjmlp** [comment]
Other than being officially deprecated....

**Comment by wbokkers** [comment]
WinUI 3 is not yet complete. UWP is not deprecated afaik.
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported

**Comment by Jimbo99** [comment]
'Going forward, UWP will only receive “bug, reliability, and security fixes,” and not new features, Microsoft says' according to https://www.thurrott.com/dev/258377/microsoft-officially-deprecates-uwp

**Comment by wbokkers** [comment]
See also: https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide
he Microsoft development story continues to evolve, and along with initiatives such as [WinUI](https://docs.microsoft.com/en-us/windows/apps/winui/), [MSIX](https://docs.microsoft.com/en-us/windows/msix/), and the [Windows App SDK](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/), UWP is a powerful tool for creating client apps.

No new features, does not mean deprecation. Thurrott..... sigh.

**Comment by Jimbo99** [comment]
No new features is exactly what deprecation means. Yes, it will carry on working but it will slowly be left behind until it is effectively unusable.

**Comment by pjmlp** [comment]
@wbokkers Same applies to VB 6 and Silverlight, and I doubt anyone would feel like writing a new greefield application with them.

**Comment by fox62843** [comment]
Even so, the Files app, which is by far the easiest to use, makes solid use of WinUI3, and the programming language is free; Flutter is limited to the Dart language, so I guess WinUI has an advantage in this regard.
Windows 11 also supports ARMSoC, so you can run Windows directly on your mobile device. Personally, I think that WindowsPhone may be revived.

DeepLで翻訳しました (https://www.deepl.com/app/?utm_medium=ios-share)

**Comment by huoyaoyuan** [comment]
There definitely needs more developers for WinUI, or the whole xaml ui area. PRs in WPF are unreviewed for a long time.

I inspected several new Windows components (notepad, taskmgr) and find they are using WinUI 2 (Windows class with `Windows.UI` namespace`. The controls of WinUI 3 is left behind WinUI 2. WinUI 3 is still not open-sourced. It's a big architectural change, but it seems that the focus is still WinUI 2.

> UWP and WinUI 3 are not really competitors. If you want a packaged sandboxed app that does not need raw win32 capabilities, you still should use UWP instead of WinUI 3.. So I see no issue in selecting UWP instead of WinUI 3 if UWP is sufficient for what you want to achieve.

UWP couples too much things. A sandbox which is too restrictive, highly outdated .NET. I'm really glad to see that the window content (via xaml island/WinUI 3) and store are decoupled comparing to 2015. WinUI 3 is on the right direction, but only if it gets full-featured.

**Comment by rick-palmsens** [comment]
Is interactive content in custom title bars on the todo list? It is not a very useful feature if I can't even put a menu in it. UWP supported it just fine, but in WinUI the title bar feel the need to simply consume all input.

https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=winui3#interactive-content

**Comment by Tropix126** [comment]
> * Are there Microsoft Windows applications (like, Notepad) developed in WinUI 3?

> I believe Windows 11 is the OS that WinUI3 is based on, am I right?

I can say with almost complete certainty that none of the production-ready OS apps or the shell use WinUI 3 at all. At the moment this is pretty identifiable due to the fact that the Windows App SDK doesn't yet support mica transparency, only the fallback colors. Paint, Notepad, Terminal and the new Task Manager apps all use XAML Islands, while the rest use WinUI 2.4 - 2.7 or System XAML.

**Comment by dongle-the-gadget** [comment]
> > * Are there Microsoft Windows applications (like, Notepad) developed in WinUI 3?
> 
> > I believe Windows 11 is the OS that WinUI3 is based on, am I right?
> 
> I can say with almost complete certainty that none of the production-ready Windows 11 apps or the shell use WinUI 3 at all. At the moment this is pretty identifiable due to the fact that the Windows App SDK doesn't yet support mica transparency, only the fallback colors _(citation needed on this one, although I am yet to find a reunion app that uses mica without DWM hacks)_. Paint, Notepad, Terminal and the new Task Manager apps all use XAML Islands, while the rest use WinUI 2.4 - 2.7 or System XAML. The non-fluent apps are either legacy WebView with a modified version of WinJS (OOBE, some parts of the new photos app, some parts of the emoji picker and touch keyboard), WebView2 (widgets panel), or Win32/WPF.

Emoji panel is whole WebView, touch keyboard looks like native except for the emoji/GIF thingy.

**Comment by gabbybilka** [comment]
Closing as the March community call issue is live! #6815 

All questions that were asked in this thread will be added to our list to address during the March community call.

**Comment by saint4eva** [comment]
> @pjmlp
> 
> Very hard to believe... Then I wouldn't be surprised if the future comes when I have to choose Flutter.

It does not matter which stack you are using. If Google flutter is more efficient and productive for you to build amazing Windows apps, kindly use it. As you can see, WimAppSdk and WinUI are progressing in a very slow manner.
