### ISSUE TITLE
Question: How to set window size smaller than 139*39

### ISSUE THREAD

**Issue by YesOhh** [microsoft/microsoft-ui-xaml#6727]
WinUI 3 Desktop C#
After referring to the [WinUIEx/src/WinUIEx/WindowEx.cs](https://github.com/dotMorten/WinUIEx/blob/cd395e2c451df7eb431d4f522eadbe5e5e72f498/src/WinUIEx/WindowEx.cs#L66-L94)
I am not sure if 139 * 39 is the smallest size of the window. I have tried to set a smaller size like 40 * 100 but it didn't work.
I want to set a window's width smaller than 139 but can I set a size smaller that 139*39 and if so how can I set it?

**Comment by castorix** [comment]
If you remove caption for example with [OverlappedPresenter.SetBorderAndTitleBar](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.overlappedpresenter.setborderandtitlebar?view=windows-app-sdk-1.0)
you can set any size

**Comment by YesOhh** [comment]
@castorix Thank you for your solution
