### ISSUE TITLE
Show ContentDialog without setting XamlRoot?

### ISSUE THREAD

**Issue by akash07k** [microsoft/microsoft-ui-xaml#6728]
Actually I'm developing a different type of app where I'm not launching the MainWindow from the App.xaml.cs class.
Instead of it, I'm putting all my logic in the App.xaml.cs only.
It will be a background app hence I'm not showing/activating the MainWindow by default.
Now I want that at some time, my app should display a ContentDialog.
Since I'm doing everything in App.xaml.cs and there's no role of Main.xaml.cs hence I'm unable to set the XamlRoot for the ContentDialog.
And when I'm performing dialog.ShowAsync() then I'm getting error:
Value does not fall within the expected range.
So there should be a way to show the ContentDialog even without setting XamlRoot.
Please help

**Comment by akash07k** [comment]
@michael-hawker 
Please help if possible. Sorry to ping you individually..

**Comment by akash07k** [comment]
Ok @michael-hawker 
I'll try with Window.
I hope the experience doesn't get degraded in terms of snappyness, accessibility and UX.
Also, can please help me in connecting with someone who works in this area?

**Comment by FabricioGonzalez** [comment]
If you don't want to use the current window to do this. Create a new one that only displays the dialog.
Otherwise you will need to set the content dialog the xamlRoot of your current window's content

**Comment by akash07k** [comment]
Ok

**Comment by StephenLPeters** [comment]
ContentDialog requires a xaml root in order to draw to the screen.  If your app doesn't have any other content drawing to the screen then ContentDialog wont work for your scenario. I'd suggest making a window to contain the UI you intend to show.

**Comment by akash07k** [comment]
ok, thanks
