### ISSUE TITLE
Cannot Compile UWP Application

### ISSUE THREAD

**Issue by AceCoderLaura** [microsoft/microsoft-ui-xaml#6741]
### Describe the bug

MarkupCompilePass2 fails with the error:
```
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(410,5): Error WMC9999 Xaml Internal Error: Cannot find type System.ServiceModel.WSHttpBinding in module System.ServiceModel.Http.dll.
```

### Steps to reproduce the bug

1. Download and extract this project: [gfgdfgd.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8094264/gfgdfgd.zip)
 2. Restore NuGet packages
 3. Build the UWP project
 4. Observe the error

### Expected behavior

Successful compilation.

### Screenshots

![image](https://user-images.githubusercontent.com/21048448/154596684-f2358d72-bc63-4f82-ab2c-77721a8626db.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2020 Update (19041)

### Additional context

A long while after hitting this issue I realized what was wrong and slapped together a sample project (see steps).

Please change the error message to tell the user to remove the packages instead of the current, cryptic error. I wasted a lot of time on this and it would be great if you could save the time of other developers by amending the message.

**Comment by krschau** [comment]
Closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615).

I've added the scenario and unhelpful message to an internal item aimed at improving these errors, thanks for reporting it.
