### ISSUE TITLE
HyperlinkButton style is creating problem in aligning with other elements.

### ISSUE THREAD

**Issue by hassaanmasood** [microsoft/microsoft-ui-xaml#6743]
### Describe the bug

For example the link button present on right side of the XAML Controls Gallery, they are not aligning left aligning with Heading elements, also it is creating problem in Windows Settings Apps in latest dev build on various places. Please revert the link button style as in Windows 10 which was simple underline on Hover with no background and padding. Also remove accent color from the link button, because if we are using accents like green, yellow, red, the link buttons really look awkward. They should be in blue always. They will look much button. Please consider these changes.

### Steps to reproduce the bug

1. Open XAML Controls Gallery App.
2. Go to any control page.
3. See the links present on the right side.

### Expected behavior

Link button should not have any padding and should not show background on hover. It should also not use accent color. It just underline on hover and use blue color always as it is familiar from the web experience also.

### Windows app type

- [ *] UWP
- [ ] Win32

**Comment by StephenLPeters** [comment]
I tend to agree, @chigy thoughts?![image](https://user-images.githubusercontent.com/7758786/156847485-a3954698-3817-4690-8123-ef216bcf5401.png)
