### ISSUE TITLE
WinUI Design Toolkit Bug: Dialog - Incorrect color in the Dark theme

### ISSUE THREAD

**Issue by MajorXAML** [microsoft/microsoft-ui-xaml#6749]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Dialog

**Describe the bug:**
Incorrect Content Bg color in the Dark theme. Both themes should use LayerFillColorAltBrush according to the [xaml ](https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/ContentDialog_themeresources.xaml#L14) file. 

**Version Info:**
2.7 (11.16.21)

**Additional context:**
![image](https://user-images.githubusercontent.com/93913816/154822300-644855da-84e5-46a8-b004-42d928834cf2.png)

**Comment by MajorXAML** [comment]
**Update:**
Incorrect content bg color only in Max Size Dialog.
![image](https://user-images.githubusercontent.com/93913816/154822520-f21da0ab-579a-461a-b245-346892b462bd.png)

**Comment by alejo4000** [comment]
Thanks for catching this! The colors have been updated and will appear in the next update.
