### ISSUE TITLE
Proposal: Expose secret hooks for including SwapChainPanel in RenderTargetBitmap

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#675]
## Summary
When using RenderTargetBitmap against a SwapChainPanel, the area of the swap chain comes back black leading to a lot of confusing among consumers of such a control. However this doesn't happen with Bing Maps control, which is also SwapChain based, due to it having access to "special" internal APIs.
I'm proposing exposing the internal hooks that allows a SwapChainPanel to participate in the rendering of a RenderTargetBitmap render pass.

## Rationale
When you want to create a screenshot of your current progress for a thumbnail, layout out a UI for printing etc, you need RenderTargetBitmap. However this falls apart once your UI Tree contains SwapChainPanels, which is often used in games, map controls etc where high-performance DX rendering is needed, but also often where you'd be very interested in being able to capture current game progress, or print out the map with some pretty XAML elements around it (or to insert in email/attachment etc).

Currently this limitation is documented here:
> Custom Microsoft DirectX content (your own swap chain) inside a SwapChainBackgroundPanel or SwapChainPanel can't be captured using RenderTargetBitmap.
[Link](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap#xaml-visuals-and-rendertargetbitmap-capture-capabilities)

When I was asking the Bing Maps team how they were able to make it work, I was informed they had access to private APIs that external control developers do not.
Since I don't know the extent of what it requires to make this work for Bing Maps, it's hard for me to propose a specific API, but it appears those are sufficient? I'm assuming some sort of event occurs and the swapchain performs a render pass to a software buffer or something.

## Functional Requirements
RenderTargetBitmap "just works" when used against any SwapChainPanel once the newly provided hooks has been implemented for control.

## Important Notes
While you could render the swap chain panel yourself to a bitmap (since you own rendering to the swap chain), it's not always enough, as you would want to also capture any XAML Elements that might be around or on top of the swapchainpanel.

**Comment by jesbis** [comment]
@dotMorten we've improved RenderTargetBitmap over the last several Windows releases, and it should be able to capture most SwapChainPanel content. 
Are you still seeing black areas instead of content on a recent build? 

I'll make sure the docs get updated.

**Comment by dotMorten** [comment]
@jesbis TBH it's been a very long time, since I tried this, but I keep checking back on the docs. If the docs are not up-to-date, I'll definite try again and if it works, close this issue.

**Comment by jesbis** [comment]
I verified RenderTargetBitmap captures SwapChainPanel content on 17763 and submitted a doc update for the outdated info.

**Comment by dotMorten** [comment]
Confirmed this works on 1903. Thank you!
