### ISSUE TITLE
Hyperlink from TextBlock within ToggleSwitch Header can't be clicked

### ISSUE THREAD

**Issue by Slion** [microsoft/microsoft-ui-xaml#6751]
### Describe the bug

Hyperlink from TextBlock within ToggleSwitch Header can't be clicked.

### Steps to reproduce the bug

Just use the XAML below to reproduce:                
```XML
<ToggleSwitch AutomationProperties.Name="simple ToggleSwitch">
    <ToggleSwitch.Header>
        <TextBlock TextWrapping="WrapWholeWords" MaxLines="100">
            <Span xml:space="preserve"><Hyperlink NavigateUri="https://docs.microsoft.com/en-us/windows/powertoys/#fancyzones">FancyZones from Microsoft PowerToys</Hyperlink></Span>
        </TextBlock>
    </ToggleSwitch.Header>
</ToggleSwitch>
```

### Expected behavior

Hyperlink should be clickable.

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Windows 11

**Comment by StephenLPeters** [comment]
@gegao18 this seems similar to a hyperlink issue you fixed recently. @codendone FYI
