### ISSUE TITLE
Question: How to set AppWindowContent

### ISSUE THREAD

**Issue by YesOhh** [microsoft/microsoft-ui-xaml#6755]
WinUI3 1.0.0 Desktop c#
![image](https://user-images.githubusercontent.com/22308850/154931834-bf441452-4b4d-46e2-9260-97b9466b6885.png)

In UWP, I can use 
`
ElementCompositionPreview.SetAppWindowContent(appWindow, new Page());
`
to set an AppWindow's content.
However, this function doesn't exist in the WinUI3.

How can I set an existed Page to an AppWindow created by AppWindow.Create()

**Comment by Jaiganeshkumaran** [comment]
In AppSDK, the AppWindow class doesn't own and manage its own window, but represents an existing window that already has content that was drawn using a UI framework.

**Comment by YesOhh** [comment]
> In AppSDK, the AppWindow class doesn't own and manage its own window, but represents an existing window that already has content that was drawn using a UI framework. Note that currently, you cannot have multiple windows with WinUI 3.

@Jaiganeshkumaran Thank you.
So, I can't compose an AppWindow created by `AppWIndow.Create()` with a Frame in WinUI3 now?
As UWP could create an AppWindow and use `ElementCompositionPreview.SetAppWindowContent(appWindow, new Page());` to generate a window with style & code defined in XAML, is there any way can implement the same function in WinUI3 now?

**Comment by castorix** [comment]
You set the Content at the Root of the MainWindow
(I must do this in VB.NEt as I cannot load directly the XAML)

**Comment by Jaiganeshkumaran** [comment]
That’s write, you can’t keep WinUI 3 content in an AppWindow other than the initial one.

**Comment by MrDeej** [comment]
If you use AppSDK 1.0.0_experimental, you can use multiple windows, and set the content almost like in UWP.

**Comment by YesOhh** [comment]
> If you use AppSDK 1.0.0_experimental, you can use multiple windows, and set the content almost like in UWP.

@MrDeej Thank you.
I used 1.0.0_experimental and it did work. However, some APIs have not been added into the experimental version such as `Win32Interop` `OverlappedPresenter.SetBorderAndTitleBar`.
Maybe I should wait for AppSDK1.1...
