### ISSUE TITLE
Question: How to get AppWindow in 1.0.0-experimental

### ISSUE THREAD

**Issue by YesOhh** [microsoft/microsoft-ui-xaml#6758]
WinUI3 1.0.0-experimental c#
![image](https://user-images.githubusercontent.com/22308850/155057394-4209c058-4866-4ef8-b077-5c29494d5969.png)

It seems that `Win32Interop` doesn't exist in `Microsoft.UI`.
![image](https://user-images.githubusercontent.com/22308850/155058272-f957634d-8a92-4cdf-bc11-5e3e8dd3bf3e.png)

Is there a way to retrieve a Window's AppWindow so that I can use AppWindow to move/resize the window?

**Comment by asklar** [comment]
looks like that api was added after 1.0.0-experimental1 (there were several months between that and 1.0.0), so I don't think that API exists in experimental. Recommend using 1.0.0, not experimental.
