### ISSUE TITLE
Question: Should standard XAML controls adopt Fabric design styling?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#676]
With WinUI 3.0 taking the entire XAML platform and decoupling it from Windows, should every control be given a design review to align it with the designs used in the Fabric Web controls?

Things like the indeterminate progress bar animation, which is still aligned to the Windows Phone design, looks different with the Fabric Web controls.

- Buttons have slightly rounded corners, and only primary buttons are filled in with the accent colours, standard buttons are outlined;

- Textfield validation is different to that proposed for XAML;

- SearchBox handles it's search glyph differently;

- Sliders use a circle thumb rather than a capsule;

- Spinner is different between Windows (spinning dots), Xbox and Fabric;

Etc.  And as well as differences in designs, there are some controls in fabric, not present in XAML, such as the shimmer for loading UI elements, chips, and Coachmark.

There should be a unified vision now all these "flavours" of Fluent design and Microsoft UIs, are to be open sourced.  Not to mention new control styles for WinForms and WPF going forward.

**Comment by chigy** [comment]
@mdtauk Thank you for your list and great question. 

Fabric is one version of Fluent so we are not likely going to be in complete alignment as we need to have a native Windows experience that may or may not make sense to Web which also needs to run on different platforms. However we are looking at making sure we are coherent and in alignment where makes sense. First item is already in the works. https://github.com/microsoft/microsoft-ui-xaml/issues/524

I'll be sure to take your list into consideration but look out for more GitHub proposals to come!
