### ISSUE TITLE
Can't Create New WinUI Project

### ISSUE THREAD

**Issue by Kurt-von-Laven** [microsoft/microsoft-ui-xaml#6767]
### Describe the bug

In Visual Studio 17.1.0, WinUI does not appear in the drop down menu of new project templates. I suspect this is because some tool, workload, component, or feature needs to be installed that is not documented [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b).

### Steps to reproduce the bug

1. Completely uninstall all versions of Visual Studio and associated tools, components, etc.
2. Install Visual Studio 17.1.0.
3. Install all of the workloads documented [here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b):

> - On the Workloads tab of the installation dialog, select:
> 
>   - Universal Windows Platform development
>     - Then in the Installation details pane of the installation dialog for that workload, make sure C++ (v143) Universal Windows Platform tools is selected.
>   - .NET Desktop Development for C# app development
>     - Then in the Installation details pane of the installation dialog, select Windows App SDK C# Templates (at the bottom of the list).
>   - Desktop development with C++ for C++ app development
>     - Then in the Installation details pane of the installation dialog, select Windows App SDK C++ Templates (at the bottom of the list).
> - On the Individual components tab of the installation dialog, in the SDKs, libraries, and frameworks section, make sure Windows 10 SDK (10.0.19041.0) is selected.

4. Follow the steps documented [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app#packaged-create-a-new-project-for-a-packaged-c-or-c-winui-3-desktop-app):

> 2. In Visual Studio, select **File** > **New** > **Project**.
> 
> 3. In the New Project dialog's drop-down filters, select **C#/C++**, **Windows**, and **WinUI**, respectively.

### Expected behavior

I expected WinUI to appear in the drop down menu of project types and **Blank App, Packaged (WinUI 3 in Desktop)** to appear in the list of project templates, but both are absent.

### Windows app type

- [ ] UWP
- [ ] Win32

### Additional context

I installed Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022 for x64 from [here]( https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) as suggested by Microsoft customer support and rebooted. There was no change in symptoms.

**Comment by castorix** [comment]
Did you install the VSIX ?
[Current releases](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#current-releases)

**Comment by Kurt-von-Laven** [comment]
They are neither required nor able to be installed on Visual Studio 17.1.0, but I did attempt to install the Windows App SDK (1.0 Stable) C# Visual Studio 2022 extension to no avail. The error message given stated it was already installed.

**Comment by castorix** [comment]
When I do a trace, the WinUI templates that I installed are read from my VS 2020 installation directory + \COMMON7\IDE\EXTENSIONS\...\ProjectTemplates\VC\1033
=>

WinUI.Desktop.CppWinRT.PackagedApp
WinUI.Desktop.CppWinRT.SingleProjectPackagedApp
WinUI.Neutral.CppWinRT.RuntimeComponent

WinUI.Desktop.Cs.ClassLibrary
WinUI.Desktop.Cs.PackagedApp
WinUI.Desktop.Cs.SingleProjectPackagedApp

**Comment by Kurt-von-Laven** [comment]
Are you also on Visual Studio 17.1.0? The [documentation](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b#visual-studio-project-and-item-templates) explicitly states that the extension only needs to be installed on earlier versions, which leads me to suspect that this issue is related to the release of 17.1.0.

> If you followed the instructions in [Required workloads and components](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b#required-workloads-and-components) above, then the templates are already installed.

I also wonder whether you had already installed the extension prior to upgrading and, if so, at which version of Visual Studio, and what version of the extension?

**Comment by castorix** [comment]
> I also wonder whether you had already installed the extension prior to upgrading and, if so, at which version of Visual Studio, and what version of the extension?

Yes, you're right. I have 17.1.0, but I had installed the 2 VSIX before upgrading (they have been updated with 17.1.0, which I can see in "Manage Extensions", 1.0.0.59203563 for C++, 1.0.0.59203525 for C#)

**Comment by Kurt-von-Laven** [comment]
When I open the C# VS 2022 VSIX Installer with Microsoft Visual Studio Version Selector, I see the following error message:

> This extension is already installed to all applicable products.

I also see the same versions listed in "Manage Extensions" for both of those extensions, and WinUI appears in the new project templates now, but none of these were listed previously even though I had already tried installing `WindowsAppSDK.Cs.Extension.Dev17.Standalone.vsix` and performed all of the steps described above followed by a reboot. I changed nothing and tried nothing I hadn't already tried. Maybe a second reboot was required? I'm certain there is a bug here, but I don't know how to help uncover it at this point. I'm guessing we should close this issue, and someone can open a new one linking to it if they encounter the same problem?

**Comment by huoyaoyuan** [comment]
For VS 17.1, you can install the template via VS installer. You can try to install or uninstall and see if there's still problem.

**Comment by Kurt-von-Laven** [comment]
This issue is about that process not working as intended.

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI

**Comment by GideonUng** [comment]
Same issue. clean windows 11 & vs 17.1 install

**Comment by jonaskohl** [comment]
Same issue with Windows 11 & VS 17.2.1. Installing the VSIX manually fails stating a newer version of the product is already installed.
