### ISSUE TITLE
WinUI project templates for WinUI3 projects is defective in BOTH VS 2022 and VS 2019 (problem identified and solution given)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6768]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinUI-project-templates-for-WinUI3-proje/1676749)._

---
The _**SAME Project template problem**_ that causes WinUI default projects to **fail to build** in Microsoft Visual Studio Version 17.2.0 Preview 1.0 affects WinUI projects in Visual Studio 2019
Version 16.11.10 . 

The solution is exactly the same as for VS2022 that I found ( in this comments: https://developercommunity.visualstudio.com/t/Version-1720-Preview-10-:-installatio/1669429#T-N1676486 )

*   I just updated my configuration of Microsoft Visual Studio Community 2019 Version 16.11.10 / .NET Framework v. 4.8.04084 via Extensions> Manage Extensions  
    ! [image.png] (https://aka.ms/dc/image?name=B5e0c5decc3cd4de5b1ff7e9f614913cf637813177906029063_20220224-094308-image.png&tid=5e0c5decc3cd4de5b1ff7e9f614913cf637813177906029063)
    
*   I have to _MANUALLY change properties to these_  (see full discussion on thread link above) _by default the build action is set to NONE and Custom Tool is BLANK_
    ! [image.png] (https://aka.ms/dc/image?name=B3cb583b775f144d6a040cfff47c189ff637813178642236218_20220224-094422-image.png&tid=3cb583b775f144d6a040cfff47c189ff637813178642236218)  
    ! [image.png] (https://aka.ms/dc/image?name=Bf37cbd773a2d463aadcdf3cdf98c3243637813178904460657_20220224-094449-image.png&tid=f37cbd773a2d463aadcdf3cdf98c3243637813178904460657)
    
*   I do NOT have this problem on my “good machine” VS 2022 and VS 2019 installations. I have no idea why both installations are affected on my “bad machine” ??
    
*   **VS 2019** this is what the default template for WinUI projects creates  
    ! [image.png] (https://aka.ms/dc/image?name=B45279c62f0294cc282b39ce4c8275613637813181328766294_20220224-094851-image.png&tid=45279c62f0294cc282b39ce4c8275613637813181328766294)  
    ! [image.png] (https://aka.ms/dc/image?name=B1ac62581c69e4559af441141c0a58876637813181554689180_20220224-094914-image.png&tid=1ac62581c69e4559af441141c0a58876637813181554689180)

---
#### Feedback Bot on 2/24/2022, 09:50 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
@evelynwu-msft FYI
