### ISSUE TITLE
Get value of selected item in ListView

### ISSUE THREAD

**Issue by kcovert** [microsoft/microsoft-ui-xaml#6771]
I've been through the documentation web pages and still can't see how to do this. Seems like it would be the most common action. Lot's of devs asking the same which I can tell by the number of query results, no answers though. Seems like the ListView supports everything under the sun but this most common need. Going on two hours now for something that should take seconds to find out.

**Comment by kcovert** [comment]
Looking at XAML Control library app now for something. Is a bound control.

**Comment by yoshiask** [comment]
Did `SelectedValue` not fit your needs?

**Comment by StephenLPeters** [comment]
Thanks yoshiask!
