### ISSUE TITLE
WinUI 3 app icon not changing in the title bar

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6773]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinUI-3-app-icon-not-changing-in-the-tit/1634854)._

---
Icon added for the app into visual assets not displaying in the title bar.
I added icon in the project property, Win32 Resources too.

Project Details:
Visual Studio 2022 (17.0.4)
Project Type: Blank App, Packaged (WinUI 3 in Desktop).

---
#### Feedback Bot on 1/12/2022, 00:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by FabricioGonzalez** [comment]
Use the AppWindow Class to do this.
Here a piece of code that can help you

` var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(MainWindow);

            WindowId windowId = Win32Interop.GetWindowIdFromWindow(hWnd);

            AppWindow appWindow = AppWindow.GetFromWindowId(windowId);

            appWindow.SetIcon("Resources/app.ico");`
The main window is the window you want to change icon.
I don't know if this is the best way. But solved my problem when I needed;

**Comment by bpulliam** [comment]
Fabricio's solution seems to answer the question.  Feature proposal #5773 also covers the request.
