### ISSUE TITLE
Question: Show flyout with triangle 

### ISSUE THREAD

**Issue by dkreho1** [microsoft/microsoft-ui-xaml#6774]
If I understand correctly, flyouts in WinUI 3 are what is on macOS referred to as a popover. I was just wondering is there a way of achieving the triangle that points to the control that caused the popover, using flyouts (or any other control for that matter)?
![popover](https://user-images.githubusercontent.com/92307873/156064875-08d605e1-abee-4052-889c-1177ed8cd8f3.png)

**Comment by mdtauk** [comment]
There is the Teaching Tip control
![image](https://user-images.githubusercontent.com/7389110/156065540-9bfc037d-d54c-476f-b309-ddf46aa92d12.png)

**Comment by dkreho1** [comment]
@mdtauk 
Thanks for the quick response
