### ISSUE TITLE
WinUI Design Toolkit Bug: Wrong Windows logo color on Guidance page

### ISSUE THREAD

**Issue by SecondThundeR** [microsoft/microsoft-ui-xaml#6776]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:** Dark Theme Colors Guide Page

**Describe the bug:** The Windows logo in the header on the Dark Theme Colors page is set to the wrong color

<img width="733" alt="image" src="https://user-images.githubusercontent.com/36604233/156246231-3dacd5f8-2e4f-479a-ba7a-b1fe3d9afe43.png">

**Version Info:** 2.7 (2.28.22)

**Additional context:** To fix this, the color for the `Windows Mark` component must be set from `Light/Fill Color/Text/Primary` to `Dark/Fill Color/Text/Primary`

**Comment by alejo4000** [comment]
Thanks for bringing this to our attention, @SecondThundeR ! You'll see this fix in our next update.
