### ISSUE TITLE
Changing the theme of the application programmatically is resetting the `TopNavigationViewContentGridCornerRadius` to `0 0 0 0`

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#6778]
### Describe the bug

Changing the theme of the application programatically is resetting the `TopNavigationViewContentGridCornerRadius` to `0 0 0 0`

### Steps to reproduce the bug

1. Create a XAML something like below

```cs
    <UserControl.Resources>
        <Thickness x:Key="TopNavigationViewContentGridBorderThickness">1,1,1,1</Thickness>
        <CornerRadius x:Key="TopNavigationViewContentGridCornerRadius">16 0 0 0</CornerRadius>
    </UserControl.Resources>
    <Grid x:Name="LayoutRoot" >
...
            <NavigationView x:Name="NavigationView" Grid.Column="1" PaneDisplayMode="Top" IsSettingsVisible="False" IsBackEnabled="False" IsBackButtonVisible="Collapsed" >
...
```

2. the view looks something like 
![image](https://user-images.githubusercontent.com/8557046/156370198-46552305-ecb7-40b8-b827-0f874b2192a2.png)

3. Change the theme to dark programmatically
```cs
            if (App.MainWindow.Content is FrameworkElement rootElement)
            {
                rootElement.RequestedTheme = Theme;
            }

```
5. the view looks like 
![image](https://user-images.githubusercontent.com/8557046/156370357-8f1fc807-3695-49ab-b9fb-847191907589.png)

### Expected behavior

The CornerRadius should not change

### Screenshots

After going back to light theme

Here you would notice that the left `TopNavigationViewContentGridBorderThickness` of `1` is also reset to `0`
![image](https://user-images.githubusercontent.com/8557046/156371089-a5aa5c42-bb72-493e-bd19-52d1204ad154.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (20H2): Build 19042

**Comment by StephenLPeters** [comment]
This doesn't appear to be an issue in winui2.  Perhaps issue with the port @llongley ?
