### ISSUE TITLE
Question: Where is the best place to release the resources of my SwapChainPanel

### ISSUE THREAD

**Issue by jeremyVignelles** [microsoft/microsoft-ui-xaml#6779]
I have a WinUI unpackaged app with just a SwapChainPanel subclass inside it.

In my constructor, I have:
```cs
        this.Loaded += VideoView_Loaded;
        this.Unloaded += VideoView_Unloaded;
```

The loaded event does get triggered, but the unloaded event does not get triggered when I close the application.
I could listen for the window to be closed, but my end goal would be to redistribute that component (trying to implement a WinUI port of [LibVLCSharp](https://code.videolan.org/videolan/libvlcsharp) ).

What is the best way to free the ressources? (like D3D11Device etc...) Where is the best place to call `DirectXHelpers.ReportLiveObjects();` in my test app to know if I'm introducing leaks ?

**Comment by StephenLPeters** [comment]
@codendone FYI
