### ISSUE TITLE
WinUI 3.0 with UWP

### ISSUE THREAD

**Issue by Pariventhan2015** [microsoft/microsoft-ui-xaml#6781]
Is the Win3.0 fully supports for UWP? We have a Project in UWP we are looking that to migrate. Any suggestion? or Best article to refer it.

**Comment by castorix** [comment]
Did you see MSDN articles like [Migrate from UWP to the Windows App SDK](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/migrate-to-windows-app-sdk-ovw) ?

**Comment by StephenLPeters** [comment]
Winui3 does not fully support the UWP app model currently.  @ryandemopoulos FYI

**Comment by Pariventhan2015** [comment]
I gone through Microsoft article, and before that want to understand is that fully available to migrate. We have developed enterprise application. We are thinking to migrate that.

**Comment by MEK3DK** [comment]
> I gone through Microsoft article, and before that want to understand is that fully available to migrate. We have developed enterprise application. We are thinking to migrate that.

I think you need to read up on the difference between WinUI 2 and WinUI 3 they are 2 completely different things even though their names are almost the same....
In regards of WinUI 3 then no it is not ready atm for enterprise applications.

**Comment by krschau** [comment]
Closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615). If you have further questions about migrating your app, please open a new issue.
