### ISSUE TITLE
VS2022 Compile: Cannot resolve metadata for WinUI types. Please ensure that Nuget Restore was successful

### ISSUE THREAD

**Issue by mirkomaga** [microsoft/microsoft-ui-xaml#6782]
Hi
Has this ever happened to you? how do i solve?

![image](https://user-images.githubusercontent.com/56160646/156544700-fe7248e4-a029-4b36-b104-c36ca07f0e8c.png)
![image](https://user-images.githubusercontent.com/56160646/156544741-90a18219-297d-4234-8324-ae455afe19e7.png)

**Comment by StephenLPeters** [comment]
@evelynwu-msft any known issues that explain this?

**Comment by Phil4121** [comment]
Same issue here after updating to the new Microsoft.WindowsAppSDK (1.0.1)

**Comment by MusixTX** [comment]
Same here after updating to the new Microsoft.WindowsAppSDK (1.0.1)

**Comment by rmoergeli** [comment]
Same here after updating to the new Microsoft.WindowsAppSDK (1.0.1)

**Comment by Mephisztoe** [comment]
Same here after updating to the new Microsoft.WindowsAppSDK (1.0.1)

**Comment by Mephisztoe** [comment]
> 

Have a look at your csproj file. Because upgrading to 1.0.1 adds a reference there which is not being removed when downgrading again. As soon as you remove the additional line you should be good to go.

**Comment by Mephisztoe** [comment]
> Same here after updating to the new Microsoft.WindowsAppSDK (1.0.1) . Downgrade to 1.0.0,don,t resolve it

@ajgarciaj [ajgarciaj](https://github.com/ajgarciaj)
Have a look at your csproj file. Because upgrading to 1.0.1 adds a reference there which is not being removed when downgrading again. As soon as you remove the additional line you should be good to go.

**Comment by kmgallahan** [comment]
I've done these steps before to get past a similar problem:

1. Visual Studio > Build > Clean Solution > Close VS
2. Project Folder > Delete **bin** & **obj** folders
3. User Folder > Delete **.nuget** folder (or at least the microsoft.windows*.* folders inside)

---

FYI, I'm running 1.01 right now just fine and didn't run into this problem - unclear on the cause.

**Comment by ajgarciaj** [comment]
> > Same here after updating to the new Microsoft.WindowsAppSDK (1.0.1) . Downgrade to 1.0.0,don,t resolve it
> 
> @ajgarciaj [ajgarciaj](https://github.com/ajgarciaj) Have a look at your csproj file. Because upgrading to 1.0.1 adds a reference there which is not being removed when downgrading again. As soon as you remove the additional line you should be good to go.

This seemed to be not working for me, i changed 2 references in csproj file and the error persist. Thanks.

**Comment by ajgarciaj** [comment]
> I've done these steps before to get past a similar problem (that is to say I couldn't compile after a package upgrade, and could do so after cleaning house):
> 
> 1. Visual Studio > Build > Clean Solution > Close VS
> 2. Project Folder > Delete **bin** & **obj** folders
> 3. User Folder > Delete **.nuget** folder (or at least the microsoft.windows*.* folders inside) - note: this is just the default location of the folder
> 
> FYI, I'm running 1.01 right now just fine and didn't run into this problem - unclear on the cause.

Thnks, it's working

**Comment by riverar** [comment]
Make sure your `<TargetFramework>` points to a Windows-specific (`-windows`) target framework moniker (e.g. `net6.0-windows10.0.17763.0`).

**Comment by GaryGormley** [comment]
Also tried what @kmgallahan suggested. Can build windows, but not android or ios, keep getting this Error	WMC1007	Cannot resolve metadata for WinUI types. Please ensure that Nuget Restore was successful. ! !

**Comment by ajgarciaj** [comment]
Uninstall 1.01 version from Nuget packets administrator works fine finally. Now i can build with alls platforms.

**Comment by Visual-IT-2021** [comment]
Same here. Problems for months. David and James are always very excited in their videos. But my enthusiasm isn't that big anymore.

Uninstalling the SDK was the solution.

**Comment by cmsdesigner** [comment]
Make sur you have this in you .csproj 
<ApplicationId Condition="$(TargetFramework.Contains('-windows'))">01837340-F8F7-4005-8980-CE617BD87B29</ApplicationId>
clean solution and rebuild is
that works for me

**Comment by MikeMoolenaar** [comment]
To clarify, I got it working by doing the following.
Add this line to the `.csproj`:
```xml
<ApplicationId Condition="$(TargetFramework.Contains('-windows'))">1CD0A983-580B-459D-9F18-2C2B97BC38FB</ApplicationId>
```
Remove any references to WindowsAppSDK outside the Windows condition itemgroup, so only the below code should be there:
```xml
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
	  <!-- Required - WinUI does not yet have buildTransitive for everything -->
	  <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
	  <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.0.30" />
</ItemGroup>
```
Then clean the solution and start the application again.

**Comment by Visual-IT-2021** [comment]
Solved it by doing this

<ApplicationId Condition="$(TargetFramework.Contains('-windows'))">01837340-F8F7-4005-8980-CE617BD87B29</ApplicationId>

and 
<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
		
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.0.1" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.3" />
	</ItemGroup>

**Comment by thomiel** [comment]
Getting this in a maui app -- but only if I want to run the app on Android rather than Windows. I tried this from the previous comment some time before, it seems:
		
		<ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
			
			<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.4" />
		</ItemGroup>

Thing is, if a new version of WindowsAppSDK is updated via NuGet, I get a dupe in the regular PackageReference ItemGroup. (Of course I have forgotten all the details by then.) So I add this comment -- just as a reminder to myself. :)

Maybe this should be forwarded to the Visual Studio 2022 team...?

**Comment by 7vn** [comment]
This issue still persists.

**Comment by StevenLiuCanton** [comment]
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/15335737/d0faf8c5-d79e-4638-ac04-c7dac99c44f7)
I faced same error. After removing PackageReference part above, I works now.
