### ISSUE TITLE
NavigationView crashes when full screen

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#6788]
### Describe the bug
NavigationView crashes when app switches to full screen sometimes.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (2004): Build 19041

### Additional context

Microsoft (R) Windows Debugger Version 10.0.22473.1005 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Users\haopeng\Documents\Tencent Files\2654637140\FileRecv\BilibiliUwpApp.exe.38756.dmp]
User Mini Dump File with Full Memory: Only application data is available

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
OK                                             C:\Users\haopeng\Downloads\bili-pdb
Symbol search path is: srv*;C:\Users\haopeng\Downloads\bili-pdb
Executable search path is: 
Windows 10 Version 19042 MP (4 procs) Free x64
Product: WinNt, suite: SingleUserTS Personal
Edition build lab: 19041.1.amd64fre.vb_release.191206-1406
Machine Name:
Debug session time: Tue Feb 22 14:47:06.000 2022 (UTC + 8:00)
System Uptime: 8 days 22:30:24.618
Process Uptime: 0 days 0:00:22.000
................................................................
................................................................
................................................................
.................
Loading unloaded module list
...............
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(9764.bcb8): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
ntdll!NtWaitForMultipleObjects+0x14:
00007ffe`a3f4d8c4 c3              ret
0:008> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Unable to verify checksum for BilibiliUwpApp.dll
*** WARNING: Unable to verify checksum for BilibiliUwpApp.exe
*** WARNING: Unable to verify checksum for IJKMediaPlayer.dll

KEY_VALUES_STRING: 1

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.mSec
    Value: 7765

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 11880

    Key  : Analysis.Init.CPU.mSec
    Value: 890

    Key  : Analysis.Init.Elapsed.mSec
    Value: 2359

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 1107

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 772224

    Key  : Timeline.Process.Start.DeltaSec
    Value: 22

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1

    Key  : WER.Process.Version
    Value: 2.13.20.0

FILE_IN_CAB:  BilibiliUwpApp.exe.38756.dmp

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=00007ffe6b4e7c10 rbx=0000022d3d262480 rcx=0000022d4dfee998
rdx=00007ffe34563ad8 rsi=0000022d3d1c8580 rdi=0000000000000000
rip=00007ffe6b41758d rsp=000000ecf86ff198 rbp=0000000000000000
 r8=000000ecf86ff1f0  r9=0000022d4e77ac60 r10=0000022d3d15fe98
r11=0000022d3d15fe90 r12=0000000000000fe5 r13=0000000000000000
r14=0000000000000001 r15=0000000000000000
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
Windows_UI_Xaml!ctl::ComObjectBase::QueryInterfaceBase+0x9 [inlined in Windows_UI_Xaml!ctl::ComObject<DirectUI::Page>::QueryInterface+0xd]:
00007ffe`6b41758d 488b01          mov     rax,qword ptr [rcx] ds:0000022d`4dfee998=????????????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffe6b41758d (Windows_UI_Xaml!ctl::ComObjectBase::QueryInterfaceBase+0x0000000000000009)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000022d4dfee998
Attempt to read from address 0000022d4dfee998

PROCESS_NAME:  BilibiliUwpApp.exe

READ_ADDRESS:  0000022d4dfee998 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000022d4dfee998

STACK_TEXT:  
000000ec`f86ff198 00007ffe`6b4005f5     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : Windows_UI_Xaml!ctl::ComObject<DirectUI::Page>::QueryInterface+0xd
000000ec`f86ff1a0 00007ffe`340f585b     : 000000ec`f86ff240 00007ffe`a19296db 00000000`00000002 00000000`00000000 : Windows_UI_Xaml!ctl::Details::WeakReferenceImpl::Resolve+0x45
000000ec`f86ff1d0 00007ffe`340f7113     : 00007ffe`a1bbf020 0000022d`3d15ffb0 0000022d`4dfeea70 0000022d`4dfeeae8 : Microsoft_UI_Xaml!winrt::weak_ref<winrt::Windows::UI::Xaml::DependencyObject>::get+0x3f
000000ec`f86ff210 00007ffe`340f57de     : 00007ffe`a1bbf020 0000022d`3d15ffb0 00000000`00000001 0000022d`4dfee990 : Microsoft_UI_Xaml!PropertyChanged_revoker::~PropertyChanged_revoker+0x33
000000ec`f86ff240 00007ffe`340f4da4     : 0000022d`3d15ffb0 00007ffe`00000000 00000000`00000001 00007ffe`00000000 : Microsoft_UI_Xaml!NavigationViewItemRevokers::~NavigationViewItemRevokers+0x12
000000ec`f86ff270 00007ffe`340fcdc4     : 0000022d`3d1c8570 0000022d`4e7b3c60 0000022d`4dfe1768 00000000`00000000 : Microsoft_UI_Xaml!winrt::impl::heap_implements<NavigationViewItemRevokers>::`scalar deleting destructor'+0x14
000000ec`f86ff2a0 00007ffe`6b3b00f8     : 00000000`00000000 00000000`00000000 000000ec`f86ff480 00007ffe`6b25ca31 : Microsoft_UI_Xaml!winrt::impl::produce_base<winrt::impl::reference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,winrt::Windows::Foundation::IReference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,void>::Release+0x64
000000ec`f86ff2d0 00007ffe`6b3aeba6     : 00000000`00000000 0000022d`1488e401 00000000`00000fe5 00000000`00000000 : Windows_UI_Xaml!DirectUI::TrackerTargetReference::Clear+0x1b8
000000ec`f86ff350 00007ffe`6b3ae896     : 0000022d`1488e430 00000000`00000000 0000022d`3d160060 00000000`00000000 : Windows_UI_Xaml!DirectUI::DependencyObject::ClearPeerReferences+0x146
000000ec`f86ff380 00007ffe`6b31efd2     : 00000000`00000000 0000022d`1488e480 0000022d`3bc62d10 00007ffe`6b31f04f : Windows_UI_Xaml!DirectUI::DependencyObject::DisconnectFrameworkPeerCore+0x26
000000ec`f86ff3c0 00007ffe`6b31ef71     : 00000000`00000001 0000022d`3bc62d10 0000022d`4e6213c0 0000022d`4e6218a0 : Windows_UI_Xaml!DirectUI::DependencyObject::DisconnectFrameworkPeer+0x42
000000ec`f86ff3f0 00007ffe`6b320a30     : 00000000`00000001 00000000`00000000 0000022d`4e6218a0 00000000`00000000 : Windows_UI_Xaml!DirectUI::DependencyObject::EndShutdown+0x11
000000ec`f86ff420 00007ffe`6b31ff6d     : 0000022d`4e77ac70 00000000`00000000 0000022d`1486b940 0000022d`1488e528 : Windows_UI_Xaml!DirectUI::DXamlCore::ShutdownAllPeers+0x1d0
000000ec`f86ff4c0 00007ffe`6b31fcae     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : Windows_UI_Xaml!DirectUI::DXamlCore::CommonShutdown+0x1d5
000000ec`f86ff530 00007ffe`6b31f395     : 0000022d`1488e430 00000000`00000000 0000022d`1488e430 00000000`00000000 : Windows_UI_Xaml!DirectUI::DXamlCore::DeinitializeInstance+0x15a
000000ec`f86ff560 00007ffe`6bcdc4b1     : 0000022d`1486ea10 0000022d`1488e430 000000ec`f86ff600 0000022d`14879160 : Windows_UI_Xaml!DirectUI::DXamlCore::Deinitialize+0x85
000000ec`f86ff590 00007ffe`9be33da6     : 0000022d`36865701 00000000`00000000 000000ec`f86ff5f0 000000ec`f86ff628 : Windows_UI_Xaml!DirectUI::FrameworkView::Uninitialize+0x51
000000ec`f86ff5d0 00007ffe`9be309a0     : 0000022d`00000005 00000000`00000000 0000022d`14877120 00000000`00000004 : twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationView::Uninitialize+0x76
000000ec`f86ff640 00007ffe`9be3e673     : 0000022d`14877120 00000000`80004005 0000022d`14877120 000000ec`f86ff6e8 : twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationViewAgileContainer::UninitializeView+0x58
000000ec`f86ff680 00007ffe`a220c889     : 0000022d`00000000 00000000`00000005 00000000`00000004 00000000`00000000 : twinapi_appcore!<lambda_643db08282a766b00cec20194396f531>::operator()+0x203
000000ec`f86ff720 00007ffe`a3707034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : SHCore!_WrapperThreadProc+0xe9
000000ec`f86ff800 00007ffe`a3f02651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x14
000000ec`f86ff830 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21

FAULTING_SOURCE_LINE:  onecoreuap\windows\dxaml\xcp\components\com\inc\ComObject.h

FAULTING_SOURCE_FILE:  onecoreuap\windows\dxaml\xcp\components\com\inc\ComObject.h

FAULTING_SOURCE_LINE_NUMBER:  36

FAULTING_SOURCE_CODE:  
No source found for 'onecoreuap\windows\dxaml\xcp\components\com\comobjectbase.cpp'

SYMBOL_NAME:  Windows_UI_Xaml!ctl::ComObject<DirectUI::Page>::QueryInterface+d

MODULE_NAME: Windows_UI_Xaml

IMAGE_NAME:  Windows.UI.Xaml.dll

STACK_COMMAND:  ~8s ; .ecxr ; kb

FAILURE_BUCKET_ID:  INVALID_POINTER_READ_c0000005_Windows.UI.Xaml.dll!ctl::ComObject_DirectUI::Page_::QueryInterface

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  10.0.19041.1503

FAILURE_ID_HASH:  {c17dd6b6-9dbb-0b81-2ebd-9fbba0b17957}

Followup:     MachineOwner
---------

0:008> k
 # Child-SP          RetAddr               Call Site
00 000000ec`f86fdc58 00007ffe`a192cb20     ntdll!NtWaitForMultipleObjects+0x14
01 000000ec`f86fdc60 00007ffe`a192ca1e     KERNELBASE!WaitForMultipleObjectsEx+0xf0
02 000000ec`f86fdf50 00007ffe`a376092a     KERNELBASE!WaitForMultipleObjects+0xe
03 000000ec`f86fdf90 00007ffe`a3760366     kernel32!WerpReportFaultInternal+0x58a
04 000000ec`f86fe0b0 00007ffe`a19eba69     kernel32!WerpReportFault+0xbe
05 000000ec`f86fe0f0 00007ffe`a3f551b0     KERNELBASE!UnhandledExceptionFilter+0x3d9
06 000000ec`f86fe210 00007ffe`a3f3c766     ntdll!RtlUserThreadStart$filt$0+0xa2
07 000000ec`f86fe250 00007ffe`a3f520cf     ntdll!_C_specific_handler+0x96
08 000000ec`f86fe2c0 00007ffe`a3f01454     ntdll!RtlpExecuteHandlerForException+0xf
09 000000ec`f86fe2f0 00007ffe`a3f50bfe     ntdll!RtlDispatchException+0x244
0a 000000ec`f86fea00 00007ffe`6b41758d     ntdll!KiUserExceptionDispatch+0x2e
0b (Inline Function) --------`--------     Windows_UI_Xaml!ctl::ComObjectBase::QueryInterfaceBase+0x9 [onecoreuap\windows\dxaml\xcp\components\com\comobjectbase.cpp @ 34] 
0c 000000ec`f86ff198 00007ffe`6b4005f5     Windows_UI_Xaml!ctl::ComObject<DirectUI::Page>::QueryInterface+0xd [onecoreuap\windows\dxaml\xcp\components\com\inc\ComObject.h @ 36] 
0d 000000ec`f86ff1a0 00007ffe`340f585b     Windows_UI_Xaml!ctl::Details::WeakReferenceImpl::Resolve+0x45 [onecoreuap\windows\dxaml\xcp\components\com\weakreference.cpp @ 35] 
0e 000000ec`f86ff1d0 00007ffe`340f7113     Microsoft_UI_Xaml!winrt::weak_ref<winrt::Windows::UI::Xaml::DependencyObject>::get+0x3f [C:\a\_work\1\s\BuildOutput\Intermediates\x64\Microsoft.UI.Xaml\obj\Generated Files\winrt\base.h @ 4097] 
0f (Inline Function) --------`--------     Microsoft_UI_Xaml!PropertyChanged_revoker::revoke+0x2a [C:\a\_work\1\s\dev\inc\CppWinRTHelpers.h @ 312] 
10 000000ec`f86ff210 00007ffe`340f57de     Microsoft_UI_Xaml!PropertyChanged_revoker::~PropertyChanged_revoker+0x33 [C:\a\_work\1\s\dev\inc\CppWinRTHelpers.h @ 302] 
11 000000ec`f86ff240 00007ffe`340f4da4     Microsoft_UI_Xaml!NavigationViewItemRevokers::~NavigationViewItemRevokers+0x12
12 000000ec`f86ff270 00007ffe`340fcdc4     Microsoft_UI_Xaml!winrt::impl::heap_implements<NavigationViewItemRevokers>::`scalar deleting destructor'+0x14
13 (Inline Function) --------`--------     Microsoft_UI_Xaml!winrt::impl::root_implements<winrt::impl::reference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,winrt::Windows::Foundation::IReference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,winrt::Windows::Foundation::IPropertyValue>::NonDelegatingRelease+0x5a [C:\a\_work\1\s\BuildOutput\Intermediates\x64\Microsoft.UI.Xaml\obj\Generated Files\winrt\base.h @ 7325] 
14 (Inline Function) --------`--------     Microsoft_UI_Xaml!winrt::impl::root_implements<winrt::impl::reference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,winrt::Windows::Foundation::IReference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,winrt::Windows::Foundation::IPropertyValue>::Release+0x5a [C:\a\_work\1\s\BuildOutput\Intermediates\x64\Microsoft.UI.Xaml\obj\Generated Files\winrt\base.h @ 7206] 
15 (Inline Function) --------`--------     Microsoft_UI_Xaml!winrt::implements<winrt::impl::reference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,winrt::Windows::Foundation::IReference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,winrt::Windows::Foundation::IPropertyValue>::Release+0x5a [C:\a\_work\1\s\BuildOutput\Intermediates\x64\Microsoft.UI.Xaml\obj\Generated Files\winrt\base.h @ 7802] 
16 000000ec`f86ff2a0 00007ffe`6b3b00f8     Microsoft_UI_Xaml!winrt::impl::produce_base<winrt::impl::reference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,winrt::Windows::Foundation::IReference<enum winrt::Microsoft::UI::Xaml::Controls::NavigationViewDisplayMode>,void>::Release+0x64 [C:\a\_work\1\s\BuildOutput\Intermediates\x64\Microsoft.UI.Xaml\obj\Generated Files\winrt\base.h @ 6874] 
17 000000ec`f86ff2d0 00007ffe`6b3aeba6     Windows_UI_Xaml!DirectUI::TrackerTargetReference::Clear+0x1b8 [onecoreuap\windows\dxaml\xcp\components\lifetime\lib\trackertargetreference.cpp @ 697] 
18 (Inline Function) --------`--------     Windows_UI_Xaml!DirectUI::TrackerPtr<IInspectable,1,0>::Clear+0xe [onecoreuap\windows\dxaml\xcp\components\lifetime\inc\TrackerPtr.h @ 267] 
19 (Inline Function) --------`--------     Windows_UI_Xaml!ctl::WeakReferenceSourceNoThreadId::RemovePtrValue+0x17 [onecoreuap\windows\dxaml\xcp\components\lifetime\inc\WeakReferenceSourceNoThreadId.h @ 233] 
1a 000000ec`f86ff350 00007ffe`6b3ae896     Windows_UI_Xaml!DirectUI::DependencyObject::ClearPeerReferences+0x146 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dependencyobject.cpp @ 757] 
1b 000000ec`f86ff380 00007ffe`6b31efd2     Windows_UI_Xaml!DirectUI::DependencyObject::DisconnectFrameworkPeerCore+0x26 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dependencyobject.cpp @ 493] 
1c 000000ec`f86ff3c0 00007ffe`6b31ef71     Windows_UI_Xaml!DirectUI::DependencyObject::DisconnectFrameworkPeer+0x42 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dependencyobject.cpp @ 547] 
1d 000000ec`f86ff3f0 00007ffe`6b320a30     Windows_UI_Xaml!DirectUI::DependencyObject::EndShutdown+0x11 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dependencyobject.cpp @ 639] 
1e 000000ec`f86ff420 00007ffe`6b31ff6d     Windows_UI_Xaml!DirectUI::DXamlCore::ShutdownAllPeers+0x1d0 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp @ 1812] 
1f 000000ec`f86ff4c0 00007ffe`6b31fcae     Windows_UI_Xaml!DirectUI::DXamlCore::CommonShutdown+0x1d5 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp @ 862] 
20 000000ec`f86ff530 00007ffe`6b31f395     Windows_UI_Xaml!DirectUI::DXamlCore::DeinitializeInstance+0x15a [onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp @ 973] 
21 000000ec`f86ff560 00007ffe`6bcdc4b1     Windows_UI_Xaml!DirectUI::DXamlCore::Deinitialize+0x85 [onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp @ 2958] 
22 000000ec`f86ff590 00007ffe`9be33da6     Windows_UI_Xaml!DirectUI::FrameworkView::Uninitialize+0x51 [onecoreuap\windows\dxaml\xcp\dxaml\lib\frameworkview_partial.cpp @ 132] 
23 000000ec`f86ff5d0 00007ffe`9be309a0     twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationView::Uninitialize+0x76
24 000000ec`f86ff640 00007ffe`9be3e673     twinapi_appcore!Windows::ApplicationModel::Core::CoreApplicationViewAgileContainer::UninitializeView+0x58
25 000000ec`f86ff680 00007ffe`a220c889     twinapi_appcore!<lambda_643db08282a766b00cec20194396f531>::operator()+0x203
26 000000ec`f86ff720 00007ffe`a3707034     SHCore!_WrapperThreadProc+0xe9
27 000000ec`f86ff800 00007ffe`a3f02651     kernel32!BaseThreadInitThunk+0x14
28 000000ec`f86ff830 00000000`00000000     ntdll!RtlUserThreadStart+0x21

**Comment by StephenLPeters** [comment]
@HppZ what version of Winui are you seeing this issue with?

**Comment by HppZ** [comment]
> @HppZ what version of Winui are you seeing this issue with?

winui 2.7

**Comment by StephenLPeters** [comment]
Are you able to reproduce it with the 2.8 prerelease package? There was a code fix in this code path that fixed an issue like this already.

**Comment by HppZ** [comment]
not sure.
the crash is from one of my app users, I can't reproduce it on my devices.

**Comment by HppZ** [comment]
@StephenLPeters

**Comment by StephenLPeters** [comment]
https://github.com/microsoft/microsoft-ui-xaml/pull/6797  The callstack is similar to an issue that this PR fixes. without a repro it will be difficult to say for sure though.
