### ISSUE TITLE
Hosting a control from C# component using XAML Island in MFC not working

### ISSUE THREAD

**Issue by DeepthiCG** [microsoft/microsoft-ui-xaml#6793]
### Describe the bug

Xaml Island hosting in MFC not works, if the C++WinRT dll used for xaml hosting refers C#WinRT dll.

### Steps to reproduce the bug

There are 3 components
1. C# WinRT component containing a XAML page
2. C++WinRT dll that supports hosting controls in MFC application
3. MFC application

Dependency is like
MFC -> C++WinRT Dll ->C#WinRT component
I have to use a custom xaml user control created in C# component to be hosted in MFC application.

Building of this project working. When running , below exception occurs. 

MFCApp.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'. 
onecore\com\combase\objact\dllcache.cxx(2127)\combase.dll!00007FFFD3053A4E: (caller: 00007FFFD2F1BBA9) ReturnHr(1) tid(69ec) 8007007E The specified module could not be found.
onecore\com\combase\objact\dllcache.cxx(4671)\combase.dll!00007FFFD3029CC0: (caller: 00007FFFD2F1E0F5) ReturnHr(2) tid(69ec) 8007007E The specified module could not be found.
onecore\com\combase\objact\dllcache.cxx(4803)\combase.dll!00007FFFD3029CE3: (caller: 00007FFFD2F1E0F5) ReturnHr(3) tid(69ec) 8007007E The specified module could not be found.
'MFCApp.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\u0358337.inf_amd64_4c4ee6c1ac83c0d2\B358199\amdhdl64.dll'. 
'MFCApp.exe' (Win32): Loaded '..\bin\x64\Release\MFCApp\ClassLibraryCsharp.dll'. 
'MFCApp.exe' (Win32): Unloaded '..\bin\x64\Release\MFCApp\ClassLibraryCsharp.dll'
'MFCApp.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\u0358337.inf_amd64_4c4ee6c1ac83c0d2\B358199\amdhdl64.dll'
Exception thrown at 0x00007FFFD25E4F69 (KernelBase.dll) in MFCApp.exe: WinRT originate error - 0x8007007E : 'The specified module could not be found.'.
'MFCApp.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
Exception thrown at 0x00007FFFD25E4F69 in MFCApp.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000AC747CABE0.

### Expected behavior

It should be possible to host the controls created in C#WinRT in MFC.

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by StephenLPeters** [comment]
@DeepthiCG is this a Winui2 or Winui3 issue?

@bpulliam FYI

**Comment by DeepthiCG** [comment]
> is this a Winui2 or Winui3 issue?

This is a XAML Island related issue. In C# component,  native winrt controls are only used. Also This C# component can be used in C++WinRT Blank app without any issues. Issue exists when hosting in an MFC application using XAML Island.

**Comment by JJBrychell** [comment]
This appears to be an issue with WinUI2, which is currently in maintenance mode and we are making limited changes there. We are therefore going to close this issue. If this is WinUI3/WinAppSdk feel free to reopen providing a sample application that demostrates the scenario.
