### ISSUE TITLE
Question: Order of page loading/unloading events during navigation

### ISSUE THREAD

**Issue by UpsettingBoy** [microsoft/microsoft-ui-xaml#6794]
WinUi 3 Win32 app.

During page navigations, I have detected that the loading event of the next page happens before the unloading event of the previous one. Is this normal/expected behaviour?

**Comment by StephenLPeters** [comment]
This is expected behavior with the Winui framework. These events are asynchronous and you can't depend on them occurring in the expected order. Instead of using these events you can use the Page.OnNavigatedFrom and Page.OnNavigatedTo overloads, which will occur in the expected order.
