### ISSUE TITLE
UWP XAML exception when showing a ToolTip based on a user control, but only on second try

### ISSUE THREAD

**Issue by Calphalon** [microsoft/microsoft-ui-xaml#6802]
### Describe the bug

When trying to show a tooltip based on a user control that contains a ListView it works perfectly the first time the ToolTip is shown, but when requested a second time, UWP throws an unhandled XAML exception: "The parameter is incorrect. The value does not fall into the expected range", this appears to be from System.Collections.ListDictionaryInternal.NodeKeyValueCollection. 

### Steps to reproduce the bug

Please see [this StackOverflow Post](https://stackoverflow.com/questions/70910523/uwp-xaml-exception-when-showing-a-tooltip-based-on-a-user-control-but-only-on-s?noredirect=1#comment126184859_70910523) for details, but the short version is:

- Create a UserControl with a ListView
- Set the UserControl as the Content of a ToolTip for a simple Control, such as a TextBlock
- Mouse over the Control to show the ToolTip - Works
- Move away from the control to hide the ToolTip
- Mouse over the Control to show the ToolTip - Fails

### Expected behavior

Should work all the time, not just once.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by StephenLPeters** [comment]
This seems like a pretty strange usage of ToolTip. While it should work, and this does appear to be a bug, I don't think it will meet our bar for investigating any time soon.
