### ISSUE TITLE
Click on HTML Content in WebView2 cause other window disappear.

### ISSUE THREAD

**Issue by AsladaGSX** [microsoft/microsoft-ui-xaml#6804]
This is duplicated. https://github.com/MicrosoftEdge/WebView2Feedback/issues/2244

**Description**

see https://stackoverflow.com/questions/71369678/when-i-click-objects-in-webview2-contents-in-other-window-disappears

**Version**
SDK: Microsoft.Web.WebView2 installed with Microsoft.UI.XAML 2.8.0-prerelease.210927001 from nuget.
Runtime: 99.0.1150.30 
Framework: UWP, WinUI2, AppWindow   
OS: Win10 21H2 

**Repro Steps**

1. Run
2. Click 'New Browser'
3. Click '+' in opened window.
4. Click added 'New Item' tab.
5. Click any item in opened WebView2. ----> Probrem: The contents of the first window disappear.
6. Close first window. ----> Probrem: The contents of the second window disappear.

https://github.com/AsladaGSX/studying_temporary_dl/raw/main/Operation.mp4

Excepted behavior is no window content disappear.

**Additional context**
https://github.com/AsladaGSX/studying_temporary_dl/

[AB#38451448](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38451448)

**Comment by StephenLPeters** [comment]
@krschau and @DmitriyKomin FYI

**Comment by AsladaGSX** [comment]
[krschau](https://github.com/krschau) commented in [original issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2244#issuecomment-1110293521).
