### ISSUE TITLE
TextBox IsSpellCheckEnabled breaks after WinAppSdk 1.0

### ISSUE THREAD

**Issue by mqudsi** [microsoft/microsoft-ui-xaml#6805]
### Describe the bug

After upgrading from 0.8.7-xxx to Windows App SDK 1.0, I have observed that my application with a spellcheck-enabled `TextBox` always ends up behaving as if `IsSpellCheck = false` after some time (i.e. it starts up with spellcheck support correctly performing auto replacements of typos and flagging misspelled words, but after leaving the app running overnight, the next day the text box is no longer doing spell check).

### Steps to reproduce the bug

Create a Win32 WinUI 3 app w/ Windows App SDK 1.0, and add a `<TextBox IsSpellCheckEnabled="true" />` UI element. Leave the app running overnight, let the system sleep or whatever, then randomly check in on it.

### Expected behavior

Spell check should continue to work.

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (1909): Build 18363

### Additional context

I've long reported that [`IsSpellCheckEnabled = true` causes (handled) unmanaged Win32 exceptions](https://github.com/microsoft/microsoft-ui-xaml/issues/5409). After upgrading to Windows App SDK 1.0, I had to disable unmanaged code debugging because the textboxes would trigger so many more spellcheck-related exceptions from time-to-time. I presume they are related and will provide some stack traces.

**Comment by StephenLPeters** [comment]
@codendone and @MikeHillberg FYI
