### ISSUE TITLE
Question: Is Hub control deprecated?

### ISSUE THREAD

**Issue by xperiandri** [microsoft/microsoft-ui-xaml#6806]
[This section](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Hub?view=winrt-22000#remarks) of docs tells that usage of Hub control is not recommended. Why?

Also, it is still not open-sourced #5598

Because of that remark, the Uno Platform team decided not take any action to port it
https://github.com/unoplatform/uno/issues/5249

And how would you recommend implementing such UI with 3 sections of different scrollable data then?
![image](https://user-images.githubusercontent.com/2365592/157532466-25900580-9c3a-4db9-9716-66735704ffd0.png)

**Comment by StephenLPeters** [comment]
Yes, the hub control is not in active development and is not recommended for use. This UI looks like it would be acheivable with a combination of GridView's and ScrollViewers

**Comment by xperiandri** [comment]
How is the main page built within Windows Store? I cannot attach to process to view a live visual tree
![image](https://user-images.githubusercontent.com/2365592/157833483-8d91e79f-9760-412b-a0c8-f266464e7356.png)
