### ISSUE TITLE
NavigationView back button incorrectly named for accessibility 

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#681]
**Describe the bug**

Based on the analysis by [Accessibility Insights](https://accessibilityinsights.io/docs/en/windows/overview), the back button should not be named "Back Button" as accessibility tools like narrator will read this as "Button, Back button" which includes redundancy.

**Expected behavior**

The name should just be "Back" (so it's read as "Button, Back")
or something specific of indicating navigation, such as "Navigate Back" (so it's read as "Button, navigate back".)

**Screenshots**

Error as reported by [App Insights for Windows](https://aka.ms/accessibilityinsights-windows/download):

![image](https://user-images.githubusercontent.com/189547/57487897-8da2d400-7266-11e9-8fcc-7ff587709fcb.png)

**Version Info**

NuGet package version: 2.2.190430003-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by YuliKl** [comment]
Thank you for the feedback. Looks like we've already fixed this problem with #571
