### ISSUE TITLE
AutoSuggestBox menu is zero-height

### ISSUE THREAD

**Issue by yoshiask** [microsoft/microsoft-ui-xaml#6812]
### Describe the bug

The suggestion menu of a WinUI AutoSuggestBox appears to be near zero height, even when list of suggestions is not empty.

### Steps to reproduce the bug

1. Install and open [XAML Studio](https://www.microsoft.com/store/apps/9NTLS214TKMQ).
2. Copy the following XAML into the editor:
```xaml
<Page
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Padding="40">
        <AutoSuggestBox>
            <x:String>Howdy</x:String>
            <x:String>Suggestion</x:String>
            <x:String>Another suggestion</x:String>
        </AutoSuggestBox>
    </Grid>
</Page>
```
3. Type some text into the box. Observe that a tiny sliver of the suggestions menu appears.

### Expected behavior

The suggestions menu should show the current suggestions (`AutoSuggestBox.Items`).

### Screenshots

![image](https://user-images.githubusercontent.com/7549325/157679626-2d6e6934-e909-487d-bff0-2c126d8ab205.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (20H2): Build 19042

### Additional context

XAML Studio still uses WinUI 2.3, but I initially ran into this issue with an Uno UWP app using WinUI 2.7 and was able to repro with WinUI 2.8.0-prerelease.220118001.

**Comment by StephenLPeters** [comment]
This is the UI i get when I use your pasted markup: 
![image](https://user-images.githubusercontent.com/7758786/157775108-ea9cb075-0d58-42e9-a94e-c09d2d36607f.png)

**Comment by yoshiask** [comment]
That's weird. I just tried the same repro on my dev box (which is on Win11 10.0.22572) and I get this:
![image](https://user-images.githubusercontent.com/7549325/157796227-69e09227-f81e-460f-a8b6-a2161851d6eb.png)

**Comment by yume-chan** [comment]
I can reproduce using the given markup.

To me it looks like `AutoSuggestBox` doesn't pass `Items` to `ListView` (only passes `ItemsSource`), so directly add items in `<AutoSuggestBox>` doesn't work.

**Comment by yoshiask** [comment]
Yes, that seems to be the issue. Binding `ItemsSource` to the data context works as expected.
![image](https://user-images.githubusercontent.com/7549325/157919429-5b66a375-e051-4222-922b-46683211ea99.png)

**Comment by ojhad** [comment]
I can't reproduce this either. @yoshiask what SDK version are you using?
 @RealTommyKlein Any ideas as to what could be going wrong here?

**Comment by yoshiask** [comment]
@ojhad I'm targeting v2004 / b19041.

**Comment by RealTommyKlein** [comment]
> I can reproduce using the given markup.
> 
> To me it looks like `AutoSuggestBox` doesn't pass `Items` to `ListView` (only passes `ItemsSource`), so directly add items in `<AutoSuggestBox>` doesn't work.

This is what I found as well.  This is unrelated to Binding/x:Bind, setting `ItemsSource` works but `Items` doesn't.  @ojhad here's a repro in a VS project, where the project's markup uses `Items` which doesn't work, but clicking the Button sets `ItemsSource` in code-behind which then works: [AutoSuggestBoxRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8253750/AutoSuggestBoxRepro.zip) .  Note that Binding/x:Bind is never used.
