### ISSUE TITLE
👨‍💻☎ WinUI Community Call: March 16, 2022

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#6815]
### https://youtu.be/fRpXbB8WUko

# Details
Date: March 16, 2022
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

# Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. In this month's call, we'll be sharing the latest info around the WinUI & Windows App SDK roadmap and releases and give an overview of the Windows App SDK Samples repository.

### **Call Summary**
- Updated Windows App SDK 1.0 release cadence expectations, [docs](https://docs.microsoft.com/windows/apps/windows-app-sdk/release-channels) to be updated shortly.
- Windows App SDK 1.0.1 coming *very soon* with critical bug fixes & **multi-window** support!
- Windows App SDK 0.8.7 coming soon with several C#/.NET Performance improvements following up from 0.8.7-preview1 released in February.
- Overview of [Windows App SDK Samples repo](https://github.com/microsoft/WindowsAppSDK-Samples) & demo of the Windowing sample in WinUI. [Video available.](https://www.youtube.com/watch?v=bAKquLQm4jQ)
- Published Windows App SDK [roadmap](https://aka.ms/WinAppSDKRoadmap) with more confident information about the features coming for WinUI 3 in Windows App SDK 1.1.
- Invitation to [send us your comments](https://github.com/microsoft/microsoft-ui-xaml/issues/6836) about the community call, I'd love to hear what we should continue/stop doing in the calls. E.g. do you like this call summary? 😊 
- Q&A

### **Q&A Code of Conduct**
- To help ensure Q&A remains beneficial for the majority of the call's developer audience, please consider whether your question could be framed so that it might be more broadly relevant to our larger developer audience by ensuring it is reasonably concise, broadly beneficial, well-suited for the fast-paced live Q&A format, or able to spark open ended discussion.  
- Please understand some questions are not well-suited for the fast-paced live Q&A format and should be filed as standalone [Discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=discussion&template=discussion.md&title=Discussion%3A+%5Byour+discussion+title%5D) or [Question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) issues where they can be most appropriately handled. Excluding presentation topic requests, this generally includes requests for dedicated follow-ups or technically complex questions that require investigative time or expertise not included in this month's guest list.

### Leave us your questions in the comments on this issue or live in the YouTube chat during the stream!

**Comment by tinmac** [comment]
Can you update us on the windowing API's that are being developed, is there an issue we can follow?

**Comment by scout208** [comment]
Could you please address the issue with the touch keyboard not displaying when text input controls get focus? (https://github.com/microsoft/microsoft-ui-xaml/issues/6291)

**Comment by Tropix126** [comment]
This might be WAY out of the scope of what can be answered in the community call, but this has been worrying me. New inbox apps on Windows 11 and many other cruical areas of the shell have been undergoing large overhauls from Win32/GDI to UWP Xaml. If these core components of the operating system are only now being migrated, and UWP is already on life support, how is support expected to be maintained for these areas?

**Comment by AzAgarampur** [comment]
Not sure if this is the right place to ask this but will comctl32/uxtheme GDI controls from classic windows desktop applications ever have a dark mode to match the themes that WinUI/XAML apps have?

**Comment by nikolayvpavlov** [comment]
We need to hear what the actual commitment of Microsoft on Windows App SDK and WinUI 3.0 is.

1. Are there Microsoft Windows applications (like, Notepad) developed in WinUI 3?
2. What is Microsoft's actual commitment, when news has it that a project like One Outlook (Project Monarch) is reportedly built on web technologies and not native? If Microsoft are not basing their core products on WinUI, why should developers do so?
3. Looking at the number of commits and active contributors, it looks like WinUI 3 is being developed by a handful of people only, which makes it hard to believe that WinUI 3 is really the next UI platform. Looks like more of a hobbyist project.

This year I will need to make a decision on how to modernize a WPF app in our core product. How can I be sure WinUI 3 is the way to go?

**Comment by pubtom** [comment]
Please weake up Microsoft and add .NET 7/8 support to UWP!

https://developercommunity.visualstudio.com/t/Add-NET-678-support-to-UWP/1596483?space=61

**Comment by mrlacey** [comment]
I think it's worth adding the main docs page for WinUI to the list of places that need to get updated for each community call:

![image](https://user-images.githubusercontent.com/189547/158075529-8ff6f7cc-2da5-4b76-83d5-aa6081c488f7.png)

**Comment by seven-mile** [comment]
😉Long time no see. Would you release a 1.1preview build or 1.0servicing at this time point? After silence for several months, I think most of developers are thirst for new releases. At least, please disclose more information about your recent progress! As promised WinUI3 is going to be open-source, currently it's too mysterious for us however.

**Comment by MEK3DK** [comment]
As others write, please in this community call, focus on what **Microsoft** wants with WinUI 3.
I think it is safe to say that the community is in doubt whether Microsoft is committed to delivering WinUI 3 for professional use.

Example of an issue regarding whether WinUI can be used/is used.
[Real projects with WinUI](https://github.com/microsoft/microsoft-ui-xaml/issues/6791)

Since there is 2500 open issues in here there is plenty of examples to pick from, but one example is: [Modern WinUI Datagrid](https://github.com/microsoft/microsoft-ui-xaml/issues/1500#issuecomment-1026388986) This has been open for 2,5 years and yet such a control is still not a direct part of WinUI 3.

It all comes down to resources and what resources are Microsoft putting into WinUI 3? Or are those resources already being scaled back?

To be honest, WinUI was/is very exciting, and looked to be something that could finally replace WPF. But it starts feeling like Silverlight or UWP all over again. So please bring us some hope :-)

**Comment by pjmlp** [comment]
Hope alone doesn't cut it any longer:

- Rewrite Win32 into Windows 8 WinRT model, using three API models across mobile, tablet and desktop
- Rewrite Windows 8 WinRT into Windows 8.1 UAP model, using two API models across mobile/tablet and desktop
- Rewrite Windows 8.1 UAP into Windows 10 UWP model, using one Core model across mobile, table, desktop, HoloLens and XBox
- Merge classical Win32 with Windows 10 UWP model via XAML Islands
- Rewrite Windows 10 UWP back into Win32 with WinUI 3.0 model, only for desktop, leaving behind HoloLens/XBox on their own
- Rewrite Windows 10 UWP back into Win32/DirectX in what concers games targeting HoloLens/XBox as respecitve teams decide to refocus on Win32

Bugs accumulate, less capabable tooling (C++/WinRT vs C++/CX, no designer), lots of missing APIs, many basic stuff requires additional work on our side to write boilerplate on our side for what is platform code on UWP side, CsWinRT versus plain Forms/WPF, and we get asked to rewrite code yet again.

So if you want people like myself that decided 6 years of this is enough, actually provide facts how this is going to happen, without rewrites of any sort.

I really wanted .NET Native and C++/CX alongside UWP to be the future, pity it ended up not being so and now everyone is shipping Electron apps instead.

**Comment by terrycox** [comment]
Can you address how WinUI 2 is playing out against WinUI 3? When does WinUI 2 go into maintenance mode?

**Comment by harvinders** [comment]
Recently, the team has mentioned that they would like to concentrate on improving the quality and address fundamental infrastructure pieces. I am wondering if it would mean addressing an issue about loading Xaml controls using reflection from assemblies not part of the main app? This would enable many of us to start writing applications with plug-in architecture. Please see #6299 for more details. Can the team say if this issue comes under core infrastructure? Any hope of getting it fixed this year?

**Comment by llothar** [comment]
Can we make the Xaml compiler a standalone executable, or even as a standalone/redistributeable DLL.
This is one missing feature if  we want to use easily cmake integration.

Also it should be able work in interpreter mode so we can integrate it with script languages and script plug-in architecture as mentioned by @harvinders  above.

**Comment by huoyaoyuan** [comment]
I mentioned that in Reunion roadmap updated today, you say you will increase usage of WinUI 3 in the Windows OS.
**Please hurry up.** The first release of Windows 11 looks very incomplete, as the same of WindowsAppSDK 1.0.

I can understand you are getting rid of design debt of Windows 8, which coupled too much things. But the transition period is too long. **It's 10 years from Windows 8 release now.**

**Comment by llothar** [comment]
When 1.0 or 1.1 gives us more freedom to deploy non MSIX packages, are you going to provide WiX (Windows Installer XML Toolkit) with samples and tutorials?

**Comment by SavoySchuler** [comment]
@tinmac 

> Can you update us on the windowing API's that are being developed, is there an issue we can follow?

Hi, @tinmac! These can be found on the [1.1 WinAppSDK Roadmap](https://github.com/microsoft/WindowsAppSDK#roadmap). 🙂

**Comment by TamBuiWork** [comment]
Thank you for addressing a rough timeframe for media controls on WinUI3. Sounds like Ryan Demopoulos says he's confident it should arrive with SDK 1.2 (2H'22?). This gives developers like me a clear direction for the coming year on how I want to approach projects related to those features, and which frameworks to use.

For anyone else interested in what was said, fast forward the stream to approx "-38:25" timeframe.

**Comment by Pinox** [comment]
I literally can't watch these community calls anymore, it just makes me sad :((

I was hoping that open sourcing WinUI can solve some of the 2.5k issues we have but to me it's starting to look like a lost cause as it's probably only going to increase the issues we have.  Sad that we still have to wait more years for open sourced WinUI.  

The whole time I'm thinking MS does not have the resources to fix this mess. Too much work and not enough resources. Goes beyond my comprehension why an executive can't fix the overall state of affairs and I mean no disrespect to MS employees here.
