### ISSUE TITLE
Left-right keyboard navigation not moved to previous or next row items in a ItemsControl

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#6818]
### Describe the bug

When we use the right arrow key to move the focus from the last item in a row to the next row item, the focus does not move and vice versa.

### Steps to reproduce the bug

1. Download and run the [ItemsControl_Navigation_Issue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8234347/ItemsControl_Navigation_Issue.zip) sample

2. Select second item (Pumpskins) from the Leaf and Salad group
3. Continusly press the `Right Arrow` keys two times.
4. Keyboard focus not moved to upcoming row's items

### Expected behavior

1.While pressing `Left Arrow` keys, focus should be moved to all previous row items (Backward direction)
2.While pressing `Right Arrow` keys, focus should be moved to all next row items (forward direction).

### Screenshots

Expcected behaviour:

![image](https://user-images.githubusercontent.com/57438309/157924228-1f839205-ed95-4fdd-b97d-10554c25e8aa.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ojhad** [comment]
This is by design. ItemsControl is a low level component and is just using XYFocus. GridView has the behavior you are looking for and may be more suited for your needs.
