### ISSUE TITLE
XAML automatic completion doesn't work in C++ project

### ISSUE THREAD

**Issue by wnstngs** [microsoft/microsoft-ui-xaml#6821]
### Describe the bug

There is no autocompletion for markup in the C++ WinUI 3 project. In the C# project it works.

### Steps to reproduce the bug

1. Create new 'Blank App, Packaged (WinUI 3 in Desktop' project (C++ language)
2. Open `MainWindow.xaml` file
3. Try to create new Button control
4. Try to configure Button properties

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by ojhad** [comment]
@evelynwu-msft FYI
