### ISSUE TITLE
Question: Is TabViewItem suppose to have shadow?

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#6822]
If I understand correctly, figma toolkit shows TabViewItem without any shadow, however WinAppSdk 1.0 has TabViewItem with shadow. 

Which is correct? I am trying to create a ribbon control directly beneath the TabViewItems and need to decide if that control should have shadow and how much.

**Comment by ojhad** [comment]
Figma and WinUI2 are correct. WinUI3 should get an update shortly to include this functionality. @chigy FYI
