### ISSUE TITLE
Treeview in WinUI3 crashes on pressing the close button 

### ISSUE THREAD

**Issue by vickoza** [microsoft/microsoft-ui-xaml#6832]
![image](https://user-images.githubusercontent.com/14866412/158463169-462827fc-4a72-43bc-8129-5a62425d355a.png)

**Comment by ojhad** [comment]
What version of WinUI3 are you using? Are you able to make a minimum repro project for the issue?

**Comment by vickoza** [comment]
> What version of WinUI3 are you using? Are you able to make a minimum repro project for the issue?

I believe the latest stable version but how do I check and how do I create a minimum repo project for the issue?

**Comment by ojhad** [comment]
Can you recreate the crash in a separate project that has the minimum required code to do so? Alternatively, could you provide the code you are using and the steps you take to cause the crash?
