### ISSUE TITLE
Question: [How to add ResourceDictionary with Code-behind] C++/WinRT

### ISSUE THREAD

**Issue by odyright** [microsoft/microsoft-ui-xaml#6839]
I got that error : ` This Xaml file must have a code-behind class to use {x:Bind}` when I was compiling.

**Comment by ojhad** [comment]
x:Bind is a Xaml markup exclusive feature, so you unable to utilize it from code-behind. Beyond that, we would need more details about your specific scenario to be able to answer your question.

**Comment by odyright** [comment]
I found what i was looking for: [resource-dictionaries-with-xbind](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-in-depth#resource-dictionaries-with-xbind)
but when i tried to create a Resource dict. file, it doesn't generate the nested file for code behind.
![Screenshot 2022-03-16 135343](https://user-images.githubusercontent.com/4316506/159141011-cbcc9117-eefb-46db-99dd-71c615f3b5c5.png)
