### ISSUE TITLE
XAML 2009 support?

### ISSUE THREAD

**Issue by markolbert** [microsoft/microsoft-ui-xaml#6841]
Does WinUI 3 v1 support XAML 2009? If so, how do I engage it (i.e., assemblies to install, xmlns referenes, etc.)?

**Comment by ojhad** [comment]
@fabiant3 @MikeHillberg Can you weigh in?

**Comment by evelynwu-msft** [comment]
@markolbert It does not, but it is a feature request that we are aware of: #7037.
