### ISSUE TITLE
Is it possible to use WinRT XAML controls in WinUI 3?

### ISSUE THREAD

**Issue by IVVOVVI** [microsoft/microsoft-ui-xaml#6845]
I know the XAML Islands, but these existing docs are all about Win32, WinForm and WPF. How to use custom and 3rd party WinRT (UWP) XAML controls in WinUI3?

**Comment by ojhad** [comment]
Components targeting the UWP platform (System Xaml) like Windows Community Toolkit are not compatible with WinUI3 by default. Windows Community Toolkit and many of our other partners have produced compatible versions.

WinUI3 does not support islands to WinUI2.

@MikeHillberg to double check

**Comment by ojhad** [comment]
@marb2000 FYI

**Comment by IVVOVVI** [comment]
Thanks for your reply. I have two problems here.
1. I've made a lot of custom controls over the past decade, based on C++/CX and PPL. The Windows App SDK only supports C++/WinRT, so rewriting them will take a lot of work. And I also have some 3rd party controls, not WinUI2. Is there a way to keep using these controls? Or will it be supported in the future?
2. It seems that WinUI3 Composition can't be used with MediaPlayerSurface?
