### ISSUE TITLE
CommandBarFlyout doesnt work or unstable

### ISSUE THREAD

**Issue by bryfa** [microsoft/microsoft-ui-xaml#6849]
### Describe the bug

Exception thrown at 0x753D60B2 in WinUI3FlyoutCommandApp.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0337D6B8.

### Steps to reproduce the bug

1. Just create a WinUI3 packaged desktop app for C#
2. Copy the sample code from the docs
3. Run it and try it out

### Expected behavior

Should be stable

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

### Additional context

Also tried it on other windows versions, but same issues

**Comment by ojhad** [comment]
Is this a first chance exception which is handled if you continue past the error?

**Comment by bryfa** [comment]
> Is this a first chance exception which is handled if you continue past the error?

No the app completely fails crashes

**Comment by ojhad** [comment]
@bryfa would you be able to provide a link to the sample you are using?

**Comment by bryfa** [comment]
I cant attach a zip file. The system rejects the upload with a message: not included in the list. Zip should be in the list

**Comment by ojhad** [comment]
The link to docs you got the specific sample from should be sufficient so we can try it out.

**Comment by bryfa** [comment]
Samples are taken from the XAML Control Gallery
