### ISSUE TITLE
ColorPicker crashes

### ISSUE THREAD

**Issue by bryfa** [microsoft/microsoft-ui-xaml#6850]
### Describe the bug

In some situations the ColorPicker crashes.

### Steps to reproduce the bug

1. Just create a WinUI3 desktop app
2. Add the control and use, it try to select a color

We had problems in some situations. If you create a new app and use the colorpicker then it works fine.
In other more complex scenario's where we have all kind of components in our setup,  it crashes.

I could not pin point the issue. But just added the control and tried to choose a color.

### Expected behavior

Should be stable

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx), Windows 10 (21H2): Build 19044

**Comment by ojhad** [comment]
Without repro steps this is going to be challenging to track down. Can you try and get a crash dump with your app?

**Comment by bryfa** [comment]
Exception thrown at 0x00007FF80BD2354C in TCScripter.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x00000072137A8520.

![image](https://user-images.githubusercontent.com/8579202/158952764-c5826b78-7a9a-4fd5-9ce0-59c61d147603.png)

**Comment by bryfa** [comment]
![image](https://user-images.githubusercontent.com/8579202/158953373-c0974857-b78b-47e5-824a-da063854a89d.png)

**Comment by bryfa** [comment]
Faulting application name: TCScripter.exe, version: 1.0.0.0, time stamp: 0x6216d2c0
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2111, time stamp: 0xde84111e
Exception code: 0xc000027b
Fault offset: 0x0000000000766328
Faulting process id: 0x0xF7EC
Faulting application start time: 0x0x1D83A986060C311
Faulting application path: C:\Users\...\bin\x64\Debug\AppX\TCScripter\TCScripter.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.0_0.319.455.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: b034f85a-94d9-41f9-bc6a-b865156f83cd
Faulting package full name: TCScripter_1.0.3.0_x64__pyendzcebvdmp
Faulting package-relative application ID: App

**Comment by bryfa** [comment]
sorry closed this issue by accident.. 
The crash dump:
https://moworksnl-my.sharepoint.com/:u:/g/personal/barry_faassen_moworks_nl/Ee_zD6hVFX9Nrx9uCi3mXm4BxZ5ImDF4E2XMoHzlBaVhIQ?e=YLpw4v

**Comment by AndrewKeepCoding** [comment]
I think I got to reproduce your problem by making a right-click in any of the `TextBox`es inside the `ColorPicker`. Your problem might be related to #4804. It's still open but it seems to have high priority so let's be patient. 

One walk around I would suggest "for the moment", is to override the `TextBox` style inside the `ColorPicker` by setting `IsHitTestVisible` to `false` and ignore any click to the `TextBox`es.

```csharp
<ColorPicker>
    <ColorPicker.Resources>
        <Style TargetType="TextBox">
            <Setter Property="IsHitTestVisible" Value="False"/>
        </Style>
    </ColorPicker.Resources>
</ColorPicker>
```

**Comment by bryfa** [comment]
At the current setup it crashes directly without any mouseclick

**Comment by AndrewKeepCoding** [comment]
I haven't heavy used the `ColorPicker` so much but, besides the `TextBox` problem, I`ve never had a problem. You might need to isolate the problem and share your minimal project.
