### ISSUE TITLE
The scroll bar display problem of listview under stackpanel and grid？

### ISSUE THREAD

**Issue by Linjie123** [microsoft/microsoft-ui-xaml#6851]
The listview in the stackpanel layout cannot display the scroll bar. In the grid layout, the listview displays the sliding bar and the mouse can scroll.

<Grid Height="500">
        <Grid.ColumnDefinitions>
            <ColumnDefinition />
            <ColumnDefinition />
        </Grid.ColumnDefinitions>

        <StackPanel Grid.Column="0" Orientation="Vertical">
            <TextBlock FontSize="30" Text="StackPanel" />
            <ListView>
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
            </ListView>
        </StackPanel>

        <Grid Grid.Column="1">
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition />
            </Grid.RowDefinitions>

            <TextBlock FontSize="30" Text="Grid" />
            <ListView Grid.Row="1">
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
                <ListViewItem Content="1" />
            </ListView>
        </Grid>
    </Grid>

https://user-images.githubusercontent.com/26216203/158944690-9b2a5e37-3f14-4fe4-aed8-3bccad77955c.mp4

**Comment by IVVOVVI** [comment]
This is by design since the first version of WPF in 2006. StackPanel doesn't FIT parent panel, StackPanel OVERFLOWs the parent panel. In other words the Height of the StackPanel is infinite.

**Comment by IVVOVVI** [comment]
This is by design since the first version of WPF in 2006. StackPanel is a simple panel. It uses infinite height to layout.

**Comment by IVVOVVI** [comment]
I'm not good at English, don't know how to explain this. You can check this doc (https://docs.microsoft.com/en-us/windows/apps/design/layout/layout-panels#stackpanel). In short, StackPanel just stacks all child elements.

**Comment by Linjie123** [comment]
我应该理解这个问题了，stackpanel默认高度是没有限制的，所以里面的listview中的内容应该是全部展示的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月19日 00:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [microsoft/microsoft-ui-xaml] The scroll bar display problem of listview under stackpanel and grid？ (Issue #6851) |

I'm not good at English, don't know how to explain this. You can check this doc (https://docs.microsoft.com/en-us/windows/apps/design/layout/layout-panels#stackpanel). In short, StackPanel just stacks all child elements.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ojhad** [comment]
@IVVOVVI is correct, this is by design. StackPanel will grow to contain whatever content you place inside it. What are you trying to achieve?
