### ISSUE TITLE
2.8.0-prerelease.220118001 WebView2.dll Microsoft Store certification failures

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#6852]
### Describe the bug

See https://github.com/MicrosoftEdge/WebView2Feedback/issues/1868

I've been struggling with apps that fail certification ("Attention needed") because of WebView2.

Submitting it a few more times will eventually get it to pass. How or why I don't know.

```
Error Found: The supported APIs test detected the following errors:
API _CxxThrowException in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_exception_copy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_exception_destroy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_terminate in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API _purecall in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API wcsrchr in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?_Xlength_error@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?_Xout_of_range@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrAssign@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCopy@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCopyException@@YAXPEAXPEBX1@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCreate@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCurrentException@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrDestroy@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrRethrow@@YAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __CxxFrameHandler4 in vcruntime140_1.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
```

### Steps to reproduce the bug

Use 2.8.0-prerelease.220118001 in app
Submit app to Store

### Expected behavior

App should pass without problem because of 2.8.0-prerelease.220118001

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Version 2.8.0-prerelease.220118001 is not available in the drop-down on this form.

**Comment by ojhad** [comment]
@krschau any ideas on what could be going on here?

**Comment by Richasy** [comment]
Same issue, even if I set the minimum SDK of the application to 22000, the store still cannot be verified, I have failed several times in this step

**Comment by lars-rogalski** [comment]
@Richasy I reinstellend Nugget Packs (clear Cache) and reinstalled SDK after that it worked for me, i have no idea why that worked.

**Comment by myokeeh** [comment]
Can we please get this fixed? I can't keep hitting "Submit to the Microsoft Store" hoping it will work eventually.

**Comment by tipa** [comment]
Hitting the same problem. I need to use the preview version because it contains a [recently implemented fix](https://github.com/microsoft/microsoft-ui-xaml/issues/5843) for a extremely annoying issue.
Any updates on this?

**Comment by onein528** [comment]
Same issue.

**Comment by krschau** [comment]
This is the same issue @myokeeh mentioned in the original post, so keep an eye on https://github.com/MicrosoftEdge/WebView2Feedback/issues/1868 as well as this issue.

The Store team is looking into this. They've made one WACK improvement that I suspect will help, but we're continuing to investigate.

**Comment by DavidShoe** [comment]
We have gotten word from the store team that the WACK tools have been updated so that should solve the API check issues during store ingestion.  Of course if anyone does see any problems please let us know.

**Comment by myokeeh** [comment]
@DavidShoe @krschau this is happening again.
