### ISSUE TITLE
ToolTip corner radius

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#6854]
ToolTip currently uses ControlCornerRadius, but since it's an overlay, shouldn't it use OverlayCornerRadius?
From my understanding, there was an issue with shadows which made them look ugly with a large corner radius, but now on Windows 11 it was fixed.

Current vs suggested:
![old](https://user-images.githubusercontent.com/101892345/159077833-464e0b88-c12a-471f-8358-16b9c995fb44.png)
![new](https://user-images.githubusercontent.com/101892345/159077838-4ab511dc-4160-40af-bfdc-d1a871f8d7be.png)

**Comment by ojhad** [comment]
@chigy do you know what the correct approach here is?
