### ISSUE TITLE
How can we set up to capture WndProc messages in a WinUI3 desktop app?

### ISSUE THREAD

**Issue by rcohn** [microsoft/microsoft-ui-xaml#6856]
Hello -

I've seen a couple variations of this question.  #2945 has code to set up a WndProc message handler, but that method does not intercept any messages (I used the code in that response verbatim).  My goal is to handle the WM_GETMINMAXINFO message to limit window size.

Running on Win10, using Windows App SDK 1.0 as a WinUI3 C# unpackaged desktop app.

Any pointers would be most appreciated.

Thank you.

**Comment by castorix** [comment]
I had posted a sample with **SetWindowSubclass** in [this thread](https://github.com/microsoft/WindowsAppSDK/discussions/2101)

**Comment by ojhad** [comment]
@bpulliam FYI

**Comment by rcohn** [comment]
Hi -

Yesterday I found your code example on http://pastebin.fr/101995, and it worked fine.  I appreciate your very quick response and the solution to a trick problem.

Thanks very much.

**Comment by dongle-the-gadget** [comment]
Or you can use the WinUIEx NuGet package.

**Comment by rcohn** [comment]
Hi @dongle-the-gadget -
WinUIEx looks pretty useful.
Thanks for the tip.

**Comment by Enzojz** [comment]
I found an article on this, tested and works for WinUI3
https://www.travelneil.com/wndproc-in-uwp.html

**Comment by castorix** [comment]
> I found an article on this

The best method is with **SetWindowSubclass**, which has replaced SetWindowLong since XP, that we used ~30 years ago...
([Subclassing Controls](https://docs.microsoft.com/en-us/windows/win32/controls/subclassing-overview))

**Comment by Enzojz** [comment]
> > I found an article on this
> 
> The best method is with **SetWindowSubclass**, which has replaced SetWindowLong since XP, that we used ~30 years ago... ([Subclassing Controls](https://docs.microsoft.com/en-us/windows/win32/controls/subclassing-overview))

Works well, thank you
