### ISSUE TITLE
Regression: Minimize/maximize/close broken by 1.0.1 runtime update with customized title bar

### ISSUE THREAD

**Issue by fredemmott** [microsoft/microsoft-ui-xaml#6859]
### Describe the bug

I am using Microsoft::UI::Xaml::Window with ExtendsContentIntoTitleBar

This works fine but is a bit awkward with the 1.0.0 libraries.

With 1.0.1 runtime - no rebuild - they visually act as expected (hover/click color changes), but they don't minimize/maximize/close the window.

### Steps to reproduce the bug

1. Get a clean windows install with no Windows App runtime
2. manually install windows app runtime 1.0.0
3. install MSIX from https://github.com/fredemmott/OpenKneeboard/releases/tag/v0.2.1
4. test minimize/maximize/close in that app (openkneeboard). They work fine.
5. close openkneeboard
6. install windows app runtime 1.0.1 update
7. launch open kneeboard
8. minimize/maximize/close still have visual effects on hover/click (color changes) but no longer minimize/maximize/close the app

### Expected behavior

Minimize/close/maximize buttons should minimize/maximize/close the window with 1.0.1 runtime as they did in 1.0.0.

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by fredemmott** [comment]
So, this is broken if I follow the instructions at https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel and https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0

The 1.0.1 release notes at https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel mention:

> Additionally, for apps with custom title bars, we have made changes in this release (and fixed numerous issues) that include fixes to the glass window used for drag&drop operations. The recommendation is to use the default values and behaviors (give them a try!). If your title bar used margins so that the default caption buttons were interactive, we recommend visualizing your drag region by setting the background of your title bar to red and then adjusting the margins to extend the drag region to the caption controls.

It was not clear this was a breaking change, rather than an option; as a breaking change in a .z release, I would expect it to only affect applications built against the new version of the SDK

**Comment by ojhad** [comment]
@bpulliam @pratikone please take a look

**Comment by pratikone** [comment]
see if it is same issue as #6895 . Remove the right margin from titlebar element. it shifts the whole custom titlebar to left enough that caption buttons stop working.  working to get the docs updated

**Comment by fredemmott** [comment]
I tried that; it fixed the buttons, but it also shifted the overall layout a bunch; after around an hour, I hadn't found a way to get both the buttons to work, and to have the content in the correct position.

Regardless, I don't think having to change the code is an ok expectation/fix for compatibility with an automatically-installed .z update

**Comment by pratikone** [comment]
yeah, we were fixing a few things. with new updates, it will ignore any margin (except for left margin). do try that out. I am closing this bug, if you continue to face any issue, feel free to open this up.
