### ISSUE TITLE
Can't run app from Store, but could from Visual Studio

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/microsoft-ui-xaml#6860]
### Describe the bug

I recently published app to Store, but found out app could not launch. So I try run app from Visual Studio and everything is okay. App is WinUI 3 packaged, C#, desktop type. 

Event viewer report:
Faulting application name: CloudCash.Client.exe, version: 1.0.1.0, time stamp: 0x61e1d74c
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2203, time stamp: 0x18fd9864
Exception code: 0xc000027b
Fault offset: 0x00237ca9
Faulting process id: 0x0x58C8
Faulting application start time: 0x0x1D83C764D801E4D
Faulting application path: C:\Program Files\WindowsApps\ParaBellumSoftware.CloudCash_1.0.29.0_x86__gt9edag94s58j\CloudCash.Client\CloudCash.Client.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.0_1.440.209.0_x86__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: 1c662a86-1d75-48ba-8144-bd62db652af1
Faulting package full name: ParaBellumSoftware.CloudCash_1.0.29.0_x86__gt9edag94s58j
Faulting package-relative application ID: App

Partner Center exception classification: stowed_exception_80131040_winrt.runtime.dll!unknown

Stack trace from Partner Center related to app:
Frame	Image	Function	Offset
0	combase.dll	RoOriginateLanguageException	0x0000000000000038	
1	WinRT.Runtime.dll	undefined	0x00000000000391FE	
2	Microsoft.WinUI.dll	global::Microsoft.UI.Xaml.Controls.ITabViewStatics.get_CanDragTabsPropertyt	0x0000000000000003	
3	Microsoft.ui.xaml.dll	DirectUI::FrameworkApplicationFactory::Start	0x000000000000018E	
4	Microsoft.WinUI.dll	undefined	0x0000000000320DBC	
5	CloudCash.Client.dll	undefined	0x0000000000023092	
6	coreclr.dll	CallDescrWorkerInternal	0x0000000000000034	
7	coreclr.dll	CallDescrWorkerWithHandler	0x0000000000000066	
8	coreclr.dll	MethodDescCallSite::CallTargetWorker	0x00000000000000E7	
9	coreclr.dll	RunMainInternal	0x00000000000000E4	
10	coreclr.dll	RunMain	0x000000000000009F	
11	coreclr.dll	Assembly::ExecuteMainMethod	0x000000000000017C	
12	coreclr.dll	CorHost2::ExecuteAssembly	0x000000000000013D	
13	coreclr.dll	coreclr_execute_assembly	0x00000000000000C6	
14	hostpolicy.dll	run_app_for_context	0x0000000000000414	
15	hostpolicy.dll	run_app	0x0000000000000052	
16	hostpolicy.dll	corehost_main	0x00000000000000F5	
17	hostfxr.dll	execute_app	0x0000000000000253	
18	hostfxr.dll	`anonymous namespace'::read_config_and_execute	0x00000000000000B9	
19	hostfxr.dll	fx_muxer_t::handle_exec_host_command	0x0000000000000104	
20	hostfxr.dll	fx_muxer_t::execute	0x0000000000000238	
21	hostfxr.dll	hostfxr_main_startupinfo	0x000000000000008B	
22	CloudCash.Client.exe	exe_start	0x000000000000079A	
23	CloudCash.Client.exe	wmain	0x000000000000008A	
24	CloudCash.Client.exe	__scrt_common_main_seh	0x00000000000000FA	
25	kernel32.dll	BaseThreadInitThunk	0x0000000000000019	
26	ntdll.dll	__RtlUserThreadStart	0x000000000000002B	
27	ntdll.dll	_RtlUserThreadStart	0x000000000000001B	

I have no idea, where to look, what to try, ... Simply how to debug. 

### Steps to reproduce the bug

1. Run app

### Expected behavior

App is launching

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by ojhad** [comment]
@JanRajnoha Are you able to launch the app via sideloading by creating an MSIX package? Are you able to share a crash dump?

**Comment by JanRajnoha** [comment]
@ojhad Nothing is working, just launching from Visual Studio, so official package through store or installing via PowerShell script (sideloading) is same -> not working. Crash dump I'll try to find

**Comment by JanRajnoha** [comment]
I don't know, where to find dump file, but I could provide file from WinDbg.

**Comment by JanRajnoha** [comment]
[WinDbgReport.txt](https://github.com/microsoft/microsoft-ui-xaml/files/8326305/WinDbgReport.txt)

**Comment by JanRajnoha** [comment]
It is problem in Microsoft.UI.Xaml, but fyi @danielayala94 @Scottj1s maybe you will know more

**Comment by ojhad** [comment]
@JanRajnoha Here are some instructions on how you can collect a crash dump: https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/debugging_crashes.md

**Comment by JanRajnoha** [comment]
I found solution for this problem. I have wrong entry point in package manifest.

**Comment by JanRajnoha** [comment]
I found solution for this problem. I ahve bad entry point in package manifest and therefore app could not start properly

**Comment by mlynch** [comment]
I'm seeing the same issue but with an unpackaged Windows App SDK 1.0.2 + WinUI 3 app installed with the setup program created from this extension: https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects

I can't get the exe to launch at all when installed, but I can run it from VS 2022. All I see in the event viewer is this: 
![image](https://user-images.githubusercontent.com/11214/167277189-ba32c052-f428-47ae-9b5d-c4d9a5b6707a.png)

**Comment by mlynch** [comment]
@dannyr-git good luck, it's a nightmare to debug this. For me it was because I was using WebView2 which was broken in unpackaged apps since you couldn't configure the user data directory  (there might be a workaround for that now), but I didn't see any reference to that in your app

**Comment by dannyr-git** [comment]
> @dannyr-git good luck, it's a nightmare to debug this. For me it was because I was using WebView2 which was broken in unpackaged apps since you couldn't configure the user data directory (there might be a workaround for that now), but I didn't see any reference to that in your app

Haha, yes I had to debug quite a few 'broken for unpackaged' things so far myself.  things like ApplicationData are only available for packaged, etc.

But this is different.  This app will work on the box I wrote it on, but no one else's.  I'm pretty sure it is because the actual SDK is installed and not just the runtime environment for Windows Apps.

**Comment by JesseCol** [comment]
Looks like the original issue was addressed by fixing the entry point in the manifest.  Closing it out.
