### ISSUE TITLE
Any  winui 3 app does not work on windows 10

### ISSUE THREAD

**Issue by Petrarca181** [microsoft/microsoft-ui-xaml#6861]
Fresh installed Windows 10, downloaded from  MS site.  All SDK dependencies installed. Net  6 installed.  Any winui 3 app just does not start, both packaged and unpackaged.  Any suggestion where start to search?

**Comment by castorix** [comment]
Have you installed the Runtime ? 
[Current releases](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#current-releases)

**Comment by Petrarca181** [comment]
> Have you installed the Runtime ? [Current releases](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#current-releases)

Yes.

**Comment by castorix** [comment]
> > Have you installed the Runtime ? [Current releases](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#current-releases)
> 
> Yes. Also .msix packages are self contained, no?

WindowsAppRuntimeInstall.exe, which must return 0 for each package

**Comment by Petrarca181** [comment]
> > > Have you installed the Runtime ? [Current releases](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#current-releases)
> > 
> > 
> > Yes. Also .msix packages are self contained, no?
> 
> WindowsAppRuntimeInstall.exe, which must return 0 for each package

Yes everything is installed correctly. But leave apart unpackged apps. Why .msix bundles do not work?

**Comment by ojhad** [comment]
@Petrarca181 would you be able to share a crash dump? Which app are you trying to run?

**Comment by ghost1372** [comment]
> > Have you installed the Runtime ? [Current releases](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#current-releases)
> 
> Yes. Also .msix packages are self contained, no?

Self Contained is not working and will be available in WASDK v1.0.X

**Comment by Petrarca181** [comment]
> @Petrarca181 would you be able to share a crash dump? Which app are you trying to run?

My personal app i'm writing.  But also just create new blank app and pack, same result.

https://www.mediafire.com/file/ggharbzaj7zfkdu/dumps.zip/file

**Comment by Petrarca181** [comment]
Little update: after some  test i noticed  that  apps created with Single Projeckt MSIX   does not work.  If I port me app to the old template  everything works fine.
