### ISSUE TITLE
Long-touching navigation view item would cause the pressed backplate to stay

### ISSUE THREAD

**Issue by roxk** [microsoft/microsoft-ui-xaml#6863]
### Describe the bug

Long touching navigation view item would cause the pressed backplate to stay. Only reproducible with touch. Cannot reproduce with right click.

### Steps to reproduce the bug

1. Launch Xaml Control Gallery
2. Long touch any item until context menu shows up
3. Dismiss the menu.
4. Observe the backplate of the item pressed in (2) remained visible.

### Expected behavior

The backplate disappear after user had lifted his finger from the navigation view item at (3).

### Screenshots
https://user-images.githubusercontent.com/16918354/159270069-6114b012-22f6-481e-b019-5607d3ec1d4d.mp4

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (22579.1)

### Additional context

XCG version is 1.2.22.0. WinUI version is 2.8.0-prerelease.220118001 (The combo box in the bug report template doesn't have this release yet)

**Comment by ojhad** [comment]
@chingucoding assigning to you. Thanks for taking a look!
