### ISSUE TITLE
MenuFlyoutItem doesn't support KeyValuePair as CommandParameter in Winui Desktop

### ISSUE THREAD

**Issue by JosHuybrighs** [microsoft/microsoft-ui-xaml#6865]
### Describe the bug

I am porting a UWP desktop bridge app to WinUI3 Desktop and found an issue when assigning a KeyValuePair to the CommandParameter of a MenuFlyoutItem.
The following code generates an exception when executing:
```
void ShowMoreMenu(bool isLocA, FrameworkElement senderElement)
{
  var vm = this.DataContext as ConflictsViewModel;
  var itemVM = (ConflictItemViewModel)senderElement.DataContext;
  MenuFlyout menu = new MenuFlyout();
  FontFamily fontFamily = new FontFamily("Segoe MDL2 Assets");
  var cmdParm = new KeyValuePair<bool, ConflictItemViewModel>(isLocA, itemVM);
  menu.Items.Add(new MenuFlyoutItem
  {
      Text = ResourceLoaderHelper.GetString("Menu-Open"),
      Icon = new FontIcon() { Glyph = "\xE8E5", FontFamily = fontFamily },
      Command = vm.OpenCmd,
      CommandParameter = cmdParm
  });
  ...
  menu.ShowAt(senderElement);
}
```
The exception is:
```
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
An exception of type 'System.Reflection.TargetInvocationException' occurred in System.Private.CoreLib.dll but was not handled in user code
```

When I remove the CommandParameter assignment or assign a 'real' object to it then it is OK.
I can work around this by creating a special class to hold the key and value, create an object and assign this to CommandParameter. 

This seems to be a bug unless I missed something. 

### Steps to reproduce the bug

Create a WinUI Desktop app with a Page and a Button.
Call the above code when the button is clicked.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by ojhad** [comment]
Confirmed this is a bug, please continue to use your workaround until we can take a look.
