### ISSUE TITLE
`MenuFlyout` and `CommandBarFlyout` have different opening animation

### ISSUE THREAD

**Issue by roxk** [microsoft/microsoft-ui-xaml#6869]
### Describe the bug

A menu flyout opens by sliding in, whereas a command bar flyout opens by fading in. 

### Steps to reproduce the bug

1. Create `MenuFlyout` and `CommandBarFlyout`
2. Open them.
3. Observe different opening animation

### Expected behavior

The animation should be the same?
Also, it seems the command bar flyout isn't aligned to the mouse cursor, whereas menu flyout is aligning perfectly.

It' be great if WinUI's figma can specify these kinds of animation as well.

### Screenshots

https://user-images.githubusercontent.com/16918354/159403244-66aa1b5f-a7aa-45ba-9ab2-696664fd576b.mp4

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by yaira2** [comment]
This hasn't been resolved in WinUI 3.

**Comment by yaira2** [comment]
@DmitriyKomin can you please explain the rationale for this? Depending on the item that's right clicked, we'll sometimes display a `MenuFlyout` and other times a `CommandBarFlyout`.

Having different animations appears to our users as a bug so it'll help if this issue is resolved or if you provide an explanation we can pass on to users.

**Comment by RichardLuo0** [comment]
Plz change this. I always feel the fade-in animation is very awkward

**Comment by yaira2** [comment]
@DmitriyKomin

**Comment by codendone** [comment]
As the names of these flyout types may imply, their origins are in supporting different control contexts with different expected usage patterns. Each animation was chosen for that specific context. Using them directly side by side wasn't part of that design. While I can see the experience being a bit jarring in the way shown here, changing the animations would have other repercussions and likely require added customization that just isn't a priority at this moment relative to the severity.

**Comment by yaira2** [comment]
Animations can significantly impact the user experience, so this response is disappointing to me. I understand that the controls are independent, but there should still be consistency between them. While I agree that there are higher priority items, it would be beneficial for the community to keep this issue open for tracking.

**Comment by p3rid0t** [comment]
I think this issue should be reopened and reconsidered, even if just to provide a space for discussion.

The `CommandBarFlyout` animation feels sluggish. It takes too long to open, and often suffers from stuttering or disappearing altogether. Plus it adds even more unnecessary inconsistencies into the Windows UI ecosystem...

My two cents: I'd consider replacing the custom fade animation with the `Flyout` animation. Why? 
The `MenuFlyout` animation wouldn't fit as it would be too fast (and `CommandBarFlyout`s are usually bigger than `MenuFlyouts`)
Meanwhile, normal `Flyout`s have a smoother animation that is more appropriate and optimized for larger surfaces.
