### ISSUE TITLE
[Watson] moappcrash: FAIL_FAST_EXCEPTION_c0000602_Microsoft.UI.Xaml.dll!winrt::impl::consume_Windows_Foundation_Collections_IMap_winrt::Windows::UI::Xaml::ResourceDictionary,winrt::Windows::Foundation::IInspectable,winrt::Windows::Foundation::IIns...

### ISSUE THREAD

**Issue by chabiss** [microsoft/microsoft-ui-xaml#6870]
### Describe the bug

Top Crasher for DevDiv [Bug 1492791](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1492791): [Watson] moappcrash: FAIL_FAST_EXCEPTION_c0000602_Microsoft.UI.Xaml.dll!winrt::impl::consume_Windows_Foundation_Collections_IMap_winrt::Windows::UI::Xaml::ResourceDictionary,winrt::Windows::Foundation::IInspectable,winrt::Windows::Foundation::IIns...

[Investigate via Watson](https://prism.vsdata.io/redirect/InvestigateFailure/f5291346-6259-9ee7-05e9-fe09443bffbb/?source=Watson&eventTypeName=moappcrash) | [Search Watson for Cabs](https://prism.vsdata.io/redirect/CabSearch/f5291346-6259-9ee7-05e9-fe09443bffbb/?source=Watson&eventTypeName=moappcrash) | [Internal Users](https://prism.vsdata.io/redirect/InternalSEFailures/f5291346-6259-9ee7-05e9-fe09443bffbb/?source=Watson&eventTypeName=moappcrash) | [Sessions](https://prism.vsdata.io/redirect/AllSEFailures/f5291346-6259-9ee7-05e9-fe09443bffbb/?source=Watson&eventTypeName=moappcrash) | [Help](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_wiki/wikis/DevDiv.wiki/2375/Help)
PRISM
Failure Hash: [f5291346-6259-9ee7-05e9-fe09443bffbb](https://prism.vsdata.io/failure/?eventType=Crash&failureHash=f5291346-6259-9ee7-05e9-fe09443bffbb&query=e:moappcrash)
Call Stack
The call stack provided below is only a SAMPLE. Please use the cab search link above to obtain latest cabs and call stacks.
KERNELBASE!RaiseException
VCRUNTIME140.APP!_CxxThrowException
Microsoft.UI.Xaml.7ffa5bed0000!winrt::throw_hresult
Microsoft.UI.Xaml.7ffa5bed0000!winrt::impl::consume_Windows_Foundation_Collections_IMap_winrt::Windows::UI::Xaml::ResourceDictionary,winrt::Windows::Foundation::IInspectable,winrt::Windows::Foundation::IInspectable_::Lookup
Microsoft.UI.Xaml.7ffa5bed0000!XamlControlsResources::UpdateAcrylicBrushesDarkTheme
Microsoft.UI.Xaml.7ffa5bed0000!XamlControlsResources::UpdateSource
Microsoft.UI.Xaml.7ffa5bed0000!winrt::impl::heap_implements_XamlControlsResources_::heap_implements_XamlControlsResources_
Microsoft.UI.Xaml.7ffa5bed0000!winrt::impl::produce_winrt::Microsoft::UI::Xaml::Controls::XamlControlsResourcesFactory,winrt::Windows::Foundation::IActivationFactory_::ActivateInstance
Windows!DomainBoundILStubClass.IL_STUB_CLRtoWinRT()
unknown!unknown
unknown!noop
unknown!unknown
unknown!unknown
unknown!unknown
coreclr!ThePreStub
coreclr!CallDescrWorkerInternal
coreclr!RuntimeTypeHandle::CreateInstance
unknown!noop
unknown!unknown
unknown!printable
coreclr!GCFrame::`vftable'
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown[Investigate via Watson](https://prism.vsdata.io/redirect/InvestigateFailure/f5291346-6259-9ee7-05e9-fe09443bffbb/?source=Watson&eventTypeName=moappcrash) | [Search Watson for Cabs](https://prism.vsdata.io/redirect/CabSearch/f5291346-6259-9ee7-05e9-fe09443bffbb/?source=Watson&eventTypeName=moappcrash) | [Internal Users](https://prism.vsdata.io/redirect/InternalSEFailures/f5291346-6259-9ee7-05e9-fe09443bffbb/?source=Watson&eventTypeName=moappcrash) | [Sessions](https://prism.vsdata.io/redirect/AllSEFailures/f5291346-6259-9ee7-05e9-fe09443bffbb/?source=Watson&eventTypeName=moappcrash) | [Help](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_wiki/wikis/DevDiv.wiki/2375/Help)
PRISM
Failure Hash: [f5291346-6259-9ee7-05e9-fe09443bffbb](https://prism.vsdata.io/failure/?eventType=Crash&failureHash=f5291346-6259-9ee7-05e9-fe09443bffbb&query=e:moappcrash)
Call Stack
The call stack provided below is only a SAMPLE. Please use the cab search link above to obtain latest cabs and call stacks.
KERNELBASE!RaiseException
VCRUNTIME140.APP!_CxxThrowException
Microsoft.UI.Xaml.7ffa5bed0000!winrt::throw_hresult
Microsoft.UI.Xaml.7ffa5bed0000!winrt::impl::consume_Windows_Foundation_Collections_IMap_winrt::Windows::UI::Xaml::ResourceDictionary,winrt::Windows::Foundation::IInspectable,winrt::Windows::Foundation::IInspectable_::Lookup
Microsoft.UI.Xaml.7ffa5bed0000!XamlControlsResources::UpdateAcrylicBrushesDarkTheme
Microsoft.UI.Xaml.7ffa5bed0000!XamlControlsResources::UpdateSource
Microsoft.UI.Xaml.7ffa5bed0000!winrt::impl::heap_implements_XamlControlsResources_::heap_implements_XamlControlsResources_
Microsoft.UI.Xaml.7ffa5bed0000!winrt::impl::produce_winrt::Microsoft::UI::Xaml::Controls::XamlControlsResourcesFactory,winrt::Windows::Foundation::IActivationFactory_::ActivateInstance
Windows!DomainBoundILStubClass.IL_STUB_CLRtoWinRT()
unknown!unknown
unknown!noop
unknown!unknown
unknown!unknown
unknown!unknown
coreclr!ThePreStub
coreclr!CallDescrWorkerInternal
coreclr!RuntimeTypeHandle::CreateInstance
unknown!noop
unknown!unknown
unknown!printable
coreclr!GCFrame::`vftable'
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown
unknown!unknown

### Steps to reproduce the bug

No steps

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by ojhad** [comment]
Looks like this [internal bug](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/33817206) which was fixed in this PR: https://github.com/microsoft/microsoft-ui-xaml/pull/6665
