### ISSUE TITLE
Setting Maximized for PreferredLaunchWindowingMode in UWP is not working

### ISSUE THREAD

**Issue by kumaresan-cgvak** [microsoft/microsoft-ui-xaml#6874]
Xamarin Forms - UWP

**Describe the bug:**
Setting `ApplicationViewWindowingMode.Maximized` for `ApplicationView.PreferredLaunchWindowingMode` is not working in Xamarin Forms UWP projects.

`ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.Maximized`

**Version Info:**
Latest Version

Sample:
[MaximiseSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8326291/MaximiseSample.zip)

**Comment by alejo4000** [comment]
Removing design and toolkit tags, this is not related to the WinUI toolkit.

**Comment by ojhad** [comment]
This API is not part of WinUI. @bpulliam do you have an idea of where this could be routed?
