### ISSUE TITLE
Question: WinUI in the Windows shell

### ISSUE THREAD

**Issue by dansmor7** [microsoft/microsoft-ui-xaml#6881]
I have two questions regarding WinUI and the Windows shell.

First:
How often does Windows update WinUI versions?
WinUI updates every 6 months, and Windows updates every year. Are they aligned in any way?

There was a small issue (#4561) which was fixed in March 2021, but you can still see it in the Windows shell today, and it will probably continue existing until the Fall update.
Is it intentional that small fixes take 1.5 years to show up in full releases?

Second:
When controls have such small issues, sometimes they are fixed manually when used in the shell or in inbox apps.
When WinUI fixes that itself, are the manual fixes removed? The big problem is when retemplating controls, because they will miss future improvements.

I'd expect that the shell and inbox app devs would follow such WinUI changes and adjust accordingly, but from what I've seen in the past that doesn't always happen.

**Comment by ojhad** [comment]
@dansmor7 Where are you seeing this toggle switch issue? If a control is re-templated then they lose fixes like this unfortunately. Lightweight styling is an option to avoid re-templating issues you mentioned: https://docs.microsoft.com/en-us/windows/apps/design/style/xaml-styles#lightweight-styling

**Comment by dansmor7** [comment]
It can be seen in various Settings pages, such as taskbar options.
I see that this one is not an issue with the WinUI version, because it was fixed in 2.6 and the latest stable Windows build uses 2.7. I'm not sure if it still happens in the preview builds, but I hope this kind of issue can be fixed and rolled out before the full yearly updates.

**Comment by ojhad** [comment]
Thanks for the feedback!

**Comment by Poopooracoocoo** [comment]
>How often does Windows update WinUI versions?
WinUI updates every 6 months, and Windows updates every year. Are they aligned in any way?

Any answers to this question as a Microsoft employee working on Windows controls? @ojhad
