### ISSUE TITLE
Question: Gamepad support in WinUI 3

### ISSUE THREAD

**Issue by camhw** [microsoft/microsoft-ui-xaml#6891]
Is there any info on gamepad support in Windows App SDK for WinUI 3?  Is it possible that it'd make it into WinAppSDK 1.1 or 1.2?  I haven't seen mention of it in the [WinAppSDK roadmap](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/roadmap.md), [WinUI 3 roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md#winui-3-feature-roadmap), or in any of the community calls.

The latest info I could find was that it [isn't supported in WinUI 3 GA](https://github.com/microsoft/microsoft-ui-xaml/issues/6050#issuecomment-947889199).

Edit: Clarified the question [here](https://github.com/microsoft/microsoft-ui-xaml/issues/6891#issuecomment-1087173143).

**Comment by ojhad** [comment]
@codendone Is there any info on this?

**Comment by castorix** [comment]
Gamepads work with WinUI
I tested with an old gamepad which is not recognized by XInput, but then I tested  with [DirectInput ](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee416842(v=vs.85)) and it worked
 (I added a WM_TIMER message to check button status with [IDirectInputDevice8::GetDeviceState,](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee417897(v=vs.85)) like in MS samples)

**Comment by camhw** [comment]
@castorix Thanks for the response :+1:

I should have been clearer in my original question, sorry about that. UWP has out of the box support to navigate and interact with the UI with gamepads, whereas WinUI3 in WinAppSDK doesn't seem to have this yet.  I'm wondering if anyone has any insight into the current state of this, or if there are any plans for it if this is indeed the case.  This is the sort of support I'm looking for: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.input.focusmanager?view=winui-3.0.

I did end up testing [Windows.Gaming.Input](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input?view=winrt-22000), and this seems to work entirely as expected.  So as an alternative I'd imagine I can either map gamepad inputs to keyboard inputs, or use [FocusManager](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.input.focusmanager?view=winui-3.0) to emulate the above support.

I'll keep this issue updated as I find time to continue investigating, though insight from anyone who's had experience with this would certainly be appreciated.

**Comment by camhw** [comment]
For now, what I've done is use [InputInjector](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.inputinjector?view=winrt-22000) to map gamepad inputs to keyboard inputs, and enable navigation using keyboard navigation strategies (e.g. [XYFocusKeyboardNavigation](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.uielement.xyfocuskeyboardnavigation?view=winui-3.0)).  As far as I can tell, this is the simplest way of achieving UWP's out of the box gamepad navigation without implementing custom focus management logic.  This should also support [focus navigation strategies](https://docs.microsoft.com/en-us/windows/apps/design/input/focus-navigation).

From the sounds of it, UWP does the reverse and [maps keyboard input to gamepad inputs](https://docs.microsoft.com/en-us/windows/apps/design/input/gamepad-and-remote-interactions#built-in-button-support), so I'm not sure why keyboard navigation works in WinUI3 in WinAppSDK, but gamepad navigation doesn't.

**Comment by camhw** [comment]
>From the sounds of it, UWP does the reverse and [maps keyboard input to gamepad inputs](https://docs.microsoft.com/en-us/windows/apps/design/input/gamepad-and-remote-interactions#built-in-button-support)

The moment I posted this I realized it's likely that the more direct way that I'm looking for would be to just inject gamepad inputs, if WinAppSDK is also doing this mapping.  [InjectGamepadInput](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.inputinjector.injectgamepadinput?view=winrt-22000#windows-ui-input-preview-injection-inputinjector-injectgamepadinput(windows-ui-input-preview-injection-injectedinputgamepadinfo)) didn't work out, this is just treated as another controller.

As it turns out, [Window.System.VirtualKey](https://docs.microsoft.com/en-us/uwp/api/windows.system.virtualkey?view=winrt-22000) also has gamepad inputs as virtual keys.  Injecting these as keyboard input results in the exact out of the box UI navigation that UWP has, even with [XYFocusKeyboardNavigation](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.uielement.xyfocuskeyboardnavigation?view=winui-3.0) disabled.

I'm happy to move forward with this solution for now, unless anyone has any suggestions.  I'll close the issue in a few days otherwise.

**Comment by seanocali** [comment]
So just so I'm clear this 10 month old article is total BS, right? None of this actually works, nor has it ever worked in WinUI 3.
[https://docs.microsoft.com/en-us/windows/apps/design/input/gamepad-and-remote-interactions](https://docs.microsoft.com/en-us/windows/apps/design/input/gamepad-and-remote-interactions)

There's no gamepad support whatsoever. KeyDown/KeyUp doesn't register events for VirtualKey.Gamepad*,  no XYNavigation, no FocusEngage, no Mouse Mode, nothing.

**Comment by seanocali** [comment]
> > From the sounds of it, UWP does the reverse and [maps keyboard input to gamepad inputs](https://docs.microsoft.com/en-us/windows/apps/design/input/gamepad-and-remote-interactions#built-in-button-support)
> 
> The moment I posted this I realized it's likely that the more direct way that I'm looking for would be to just inject gamepad inputs, if WinAppSDK is also doing this mapping. [InjectGamepadInput](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.inputinjector.injectgamepadinput?view=winrt-22000#windows-ui-input-preview-injection-inputinjector-injectgamepadinput(windows-ui-input-preview-injection-injectedinputgamepadinfo)) didn't work out, this is just treated as another controller.
> 
> As it turns out, [Window.System.VirtualKey](https://docs.microsoft.com/en-us/uwp/api/windows.system.virtualkey?view=winrt-22000) also has gamepad inputs as virtual keys. Injecting these as keyboard input results in the exact out of the box UI navigation that UWP has, even with [XYFocusKeyboardNavigation](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.uielement.xyfocuskeyboardnavigation?view=winui-3.0) disabled.
> 
> I'm happy to move forward with this solution for now, unless anyone has any suggestions. I'll close the issue in a few days otherwise.

So you're saying that a Control's XYNavigation and FocusEngage responds to keyboard injection of a gamepad VirtualKeys? How do you trigger the injection with an actual gamepad though? Using Win32 API?

**Comment by camhw** [comment]
>So just so I'm clear this 10 month old article is total BS, right? None of this actually works, nor has it ever worked in WinUI 3.
https://docs.microsoft.com/en-us/windows/apps/design/input/gamepad-and-remote-interactions

It worked with WinUI3 in UWP (before the switch to WinAppSDK).  I think this article is still valuable despite it not functioning in WinUI3 in WinAppSDK by default, since it shows the keypoard to gamepad mappings and gets across the general philosophy well.

>So you're saying that a Control's XYNavigation and FocusEngage responds to keyboard injection of a gamepad VirtualKeys?

Yep, seems that way :+1:

>How do you trigger the injection with an actual gamepad though?

I'm personally using [Windows.Gaming.Input](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad?view=winrt-22000) to map gamepad state to keyboard inputs via [InputInjector.InjectKeyboardInput](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.inputinjector.injectkeyboardinput?view=winrt-22000#windows-ui-input-preview-injection-inputinjector-injectkeyboardinput(windows-foundation-collections-iiterable((windows-ui-input-preview-injection-injectedinputkeyboardinfo)))).  One thing to note about this library is [Windows.Gaming.Input.Gamepads()](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad.gamepads?view=winrt-22000#windows-gaming-input-gamepad-gamepads) will be empty on app launch (this is the case for UWP as well).  You need to listen to the [GamepadAdded](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad.gamepadadded?view=winrt-22000) event instead.

**Comment by camhw** [comment]
Going to close this issue since a workaround has been identified.
