### ISSUE TITLE
CornerRadius doesn't take effect in NavigationBackButtonNormalStyle

### ISSUE THREAD

**Issue by lyf6lyf** [microsoft/microsoft-ui-xaml#6892]
### Describe the bug

When we use `NavigationBackButtonNormalStyle`, set `CornerRadius` doesn't take effect.

### Steps to reproduce the bug

1. Create an UWP project.
2. Add a button ```        <Button
            Margin="200"
            CornerRadius="8"
            Style="{StaticResource NavigationBackButtonNormalStyle}" />```
3. run the project

### Expected behavior

The button should have corner radius

### Screenshots

![image](https://user-images.githubusercontent.com/6219635/160343967-d573639f-13be-43f1-93f7-df55d82f0828.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by sigmarsson** [comment]
Confirmed. But beneath even the back color fails to take effect. 

```
        <Style x:Key="FunctionButtonStyle" TargetType="uc:FunctionButton">
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="uc:FunctionButton">
                        <RelativePanel>
                            <SymbolIcon Symbol="{TemplateBinding Symbol}" RelativePanel.AlignTopWithPanel="True" Margin="5">
                                <SymbolIcon.RenderTransform>
                                    <ScaleTransform CenterX="0" CenterY="0" ScaleX="0.5" ScaleY="0.5"/>
                                </SymbolIcon.RenderTransform>
                            </SymbolIcon>
                            <TextBlock Text="{TemplateBinding Content}" RelativePanel.AlignBottomWithPanel="True" Margin="5" FontSize="10" />
                        </RelativePanel>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
            <Setter Property="Width" Value="75"/>
            <Setter Property="Height" Value="45"/>
            <Setter Property="CornerRadius" Value="0"/>
            <Setter Property="Background" Value="#282828"/>
        </Style>
```
