### ISSUE TITLE
ToggleSwitch stroke resources not respected

### ISSUE THREAD

**Issue by dynsim** [microsoft/microsoft-ui-xaml#6896]
### Describe the bug

ToggleSwitch has some stroke resources that do not seem to work. When they are set, the stroke instead becomes transparent/removed.

This includes the following resources:
```
ToggleSwitchStrokeOffPointerOver
ToggleSwitchStrokeOffPressed
ToggleSwitchStrokeOffDisabled
```

Similar behavior is seen with a RadioButton and the following resources:
```
RadioButtonOuterEllipseStrokePointerOver
RadioButtonOuterEllipseStrokeDisabled
RadioButtonOuterEllipseCheckedStrokeDisabled
```

A sample repository can be seen here: https://github.com/dynsim/WinUI3ControlResourceIssues

### Steps to reproduce the bug

1. Create a default WinUI 3 packaged app for C#
2. Insert the following code:
```
<ToggleSwitch>
    <ToggleSwitch.Resources>
        <SolidColorBrush x:Key="ToggleSwitchStrokeOffPointerOver" Color="Red"/>
    </ToggleSwitch.Resources>
</ToggleSwitch>
```
3. Run the app and see that the stroke is now missing.

This can be repeated with the resources mentioned above.

### Expected behavior

I expect the stroke colors set in the resources should be respected.

### Screenshots

https://user-images.githubusercontent.com/71330283/160579765-0a1af834-bb1d-41e1-9040-295adbb6aa48.mp4

https://user-images.githubusercontent.com/71330283/160579777-cec39ba5-e0a8-4230-b8ad-5feadadf31e6.mp4

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000, Windows 10 (20H2): Build 19042

**Comment by ojhad** [comment]
Can you try to change your definition to use Color instead of SolidColorBrush? This should fix your issue.

**Comment by dynsim** [comment]
@ojhad: Thank you for your answer. It does work indeed.

Can you shed some light on when `Color` should be used over `SolidColorBrush`? Should `Color` generally be used?

It seems that some resources work just fine using  `SolidColorBrush`, e.g. `ToggleSwitchStrokeOff`:
```XML
<ToggleSwitch>
    <ToggleSwitch.Resources>
        <SolidColorBrush x:Key="ToggleSwitchStrokeOff" Color="#ff0000"/>
    </ToggleSwitch.Resources>
</ToggleSwitch>
```

Which produces this result:
![image](https://user-images.githubusercontent.com/71330283/160815971-b2b0cb84-e74b-483c-b66f-c7bbafe51770.png)

**Comment by ojhad** [comment]
Awesome! The guidance would be to look and match to the property type that is defined on the API. You would have to look at the template of toggle switch to see how the resource is ultimately being used.

**Comment by KWodarczyk** [comment]
This still does not work for other brushers like ToggleSwitchKnobFillOffPointerOver etc
