### ISSUE TITLE
Proposal: ItemsUpdatingScrollMode support for ItemsRepeater

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#690]
# Proposal: ItemsUpdatingScrollMode support for ItemsRepeater

## Summary

I'm developing a messaging app and the messages list is a crucial part of the UX.
ListView mostly fits my needs, but it has many throwbacks:
- I can't customize the ListViewItem style, as this would affect virtualization.
- I had to implement on my own items selection as the system provided one doesn't fit my needs.

Would be great to be able to replace it with an ItemsRepeater, but a key feature (for my scenario) is currently missing: ItemsUpdatingScrollMode

## Rationale
Allow to lock ItemsRepeater scrolling adjustment to be locked to last or first visible item: this would enable scenarios where you want to keep the list position at the end while adding new items without having to programmatically scroll the view.

**Comment by jevansaks** [comment]
This should be supported now with the "anchoring" feature. I think it's even available in the ScrollViewer in the OS as of RS5. But you could also try out the MUX.ScrollViewer that's in preview.

@micahl @ranjeshj @rbrid any samples here to refer to?

**Comment by ranjeshj** [comment]
ScrollViewer's HorizontalAnchorRatio/VerticalAnchorRatio is what you need. 
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer.horizontalanchorratio

**Comment by micahl** [comment]
Specifically, you'll want to set the VerticalAnchorRatio to 1.0 for a bottoms-up list.  Here's a sample I put together a few weeks ago:  https://github.com/micahl/bottomsuplist/tree/oldscrollviewer

Note: There's a known issue tracked by #562.

**Comment by micahl** [comment]
@FrayxRulez I'm closing this issue under the assumption that scroll anchoring provides what you need (or at least it will once all known issues are addressed).  If that's not the case then let me know.

**Comment by FrayxRulez** [comment]
Hi all, thanks for your answers, but I'm actually looking for a backward compatible solution as I'm targeting RS2 as minimum version.

**Comment by ranjeshj** [comment]
ItemsRepeaterScrollHost can do the same thing for versions below RS5. 
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater

**Comment by FrayxRulez** [comment]
Missed it, thank you!
