### ISSUE TITLE
Announcement: WinUI 3 in Windows App SDK 1.1 Preview 1 🎈

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#6900]
### 1.1 Preview 1 Release of Windows App SDK 

We've just released our first preview of the 1.1 release of the Windows App SDK! This preview includes several new capabilities for WinUI 3 apps, including:
- Support for running applications with elevated privileges
- Self-contained app deployment
- Support for multi-window applications (also available in version 1.0.1 and newer)
- Push and app notifications
- Enabling developers to add, remove, and modify environment variables without having to directly use the registry API.

**Known issue for WinUI 3 applications:** Users are unable to drop an element when drag and drop is enabled.

To see everything that's new and changed, see the full [release notes here](https://aka.ms/windowsappsdk/1.1/1.1.0-preview1/release-notes). 

### What's next 
To keep up with progress being made on WinUI 3 in the Windows App SDK, please see our [feature roadmap](https://aka.ms/winappsdkroadmap), which gets updated regularly.  

### Providing feedback
As we introduce new & upcoming features in our preview releases, we appreciate all of your feedback as we work towards a stable release:
- For WinUI 3 feedback, please open an issue here, on the [WinUI repo](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose).
- For feedback regarding all other Windows App SDK components, please open an issue on the [Windows App SDK repo](https://github.com/microsoft/WindowsAppSDK/issues/new/choose).

**Comment by kmgallahan** [comment]
@gabbybilka per https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#version-11-preview-1-110-preview1

> The preview channel is not supported for use in production environments, and apps that use the preview releases cannot be published to the Microsoft Store. There are currently no releases available from the preview channel, and we recommend using the [latest stable release](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel).

Could use an update.

**Comment by ThierryFourniol** [comment]
Thank you so much for the v1.1 Preview 1 as **the Self-contained app deployment is an amazing capability**... except:
**Known issue for WinUI 3 applications: Users are unable to drop an element when drag and drop is enabled.**
This is tragic as my drag and drop desktop app is not fit for purpose anymore!
I confirm Dropping an element is crashing the app indeed!
So please can you fix it ASAP? Or is there any quick workaround? Please 'save my life'. Thank you!

**Comment by knightmeister** [comment]
Can you guys address this?

https://github.com/microsoft/microsoft-ui-xaml/issues/4804

I would have thought this is a simple fix, pretty poor UX having an app crash for something as trivial as write clicking a textbox.

**Comment by artkat** [comment]
"**Users are unable to drop an element when drag and drop is enabled.**"
This issue is long overdue for being resolved.
Drag-and-drop is one of the cornerstone UI features of GUI (Windows, Mac, etc.)
Having new features is nice, but please, fix critical outstanding bugs!!!

**Comment by pjmlp** [comment]
Support for running applications with elevated privileges is only for Windows 11 folks, while Win32 doesn't have any issue since Vista introduced UAC, a strange trend is starting to show up.

**Comment by ThierryFourniol** [comment]
Self-contained works well with the Preview 1, Great and many thanks for that,
but is there a way to get a single .exe file instead of about 344 files next to the .exe file?
Because <PublishSingleFile>true</PublishSingleFile> does not work for me, sadly.
Has anyone managed to achieve this? Thanks!
