### ISSUE TITLE
ExtendsContentIntoTitleBar and wrong window top border color

### ISSUE THREAD

**Issue by pavel-zhukov** [microsoft/microsoft-ui-xaml#6901]
### Describe the bug

In WinUI 3 project, the top border of window is drawn black when `ExtendsContentIntoTitleBar` is `true`.

### Steps to reproduce the bug

1. Create 'Blank App, Packaged (with WinUI 3 in Desktop)'
2. Set `ExtendsContentIntoTitleBar` to `true` in the MainWindow constructor

### Screenshots

![winui](https://user-images.githubusercontent.com/60793395/160762953-beb537f9-3c61-4dab-840a-e3f8498dd4c2.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [x] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by bongvisu** [comment]
Any progress on this issue?

**Comment by bongvisu** [comment]
![image](https://user-images.githubusercontent.com/26132826/167126115-89faeafd-428a-4b85-8642-ced91f712922.png)

**Comment by bongvisu** [comment]
![TopBorderColor](https://user-images.githubusercontent.com/26132826/167233493-a6a48d5d-eaf6-4a17-ad0e-b7bd3400c318.png)

**Comment by minisbett** [comment]
bump

**Comment by Haky00** [comment]
This bug is still present in the 1.1 version.

**Comment by pavel-zhukov** [comment]
Any developer's comment? Nope?

**Comment by pavel-zhukov** [comment]
A workaround:
```
using System;
using System.Runtime.InteropServices;
using WinRT.Interop;

public sealed partial class MainWindow : Window {

  [StructLayout(LayoutKind.Sequential)]
  struct MARGINS {
    public int cxLeftWidth;
    public int cxRightWidth;
    public int cyTopHeight;
    public int cyBottomHeight;
  }

  [DllImport("dwmapi")]
  static extern long DwmExtendFrameIntoClientArea(IntPtr hWnd, ref MARGINS pMarInset);

  public MainWindow() {
    var handle = WindowNative.GetWindowHandle(this);
    var margins = new MARGINS { cxLeftWidth = 0, cxRightWidth = 0, cyBottomHeight = 0, cyTopHeight = 2 };
    Activated +=
      (object sender, WindowActivatedEventArgs args) => DwmExtendFrameIntoClientArea(handle, ref margins);
    ExtendsContentIntoTitleBar = true;
  }

  // ...

}
```

**Comment by progmars** [comment]
Additional bug related to this wrong border.

If you want to disable resizing for your app and add the code:

    if (appWindow.Presenter is OverlappedPresenter p)
           p.IsResizable = false;

then the side and bottom borders will not support resizing and won't show the resizer cursor, but the top border will still show the resize cursor (but resizing will not actually work):

![image](https://user-images.githubusercontent.com/4199737/185797320-8e032eb0-8390-4202-8d23-c7a531e6f415.png)

@pavel-zhukov  your fix deals with both issues - it fixes the color and also gets rid of the wrong resize cursor.

I hope the team will do something about it; these hacks are ugly.

**Comment by mdtauk** [comment]
This is still an Issue, not sure if its WinUI 3 related, or WinAppSDK
https://github.com/microsoft/WindowsAppSDK/issues/3752

**Comment by pratikone** [comment]
I would close this issue because the other issue mentioned here is more accurate : in high contrast setting, parts of top border is missing. I would follow that issue to track it. Closing it as dup.

**Comment by bogdan-patraucean** [comment]
So where exactly is this going to be fixed?

**Comment by pratikone** [comment]
It is in the pipeline of the team and should be done in a future release. The developers will update the high contrast bug if it is fixed internally and with the tag of build it will be coming in .

**Comment by HO-COOH** [comment]
> A workaround:
> 
> ```
> using System;
> using System.Runtime.InteropServices;
> using WinRT.Interop;
> 
> public sealed partial class MainWindow : Window {
> 
>   [StructLayout(LayoutKind.Sequential)]
>   struct MARGINS {
>     public int cxLeftWidth;
>     public int cxRightWidth;
>     public int cyTopHeight;
>     public int cyBottomHeight;
>   }
> 
>   [DllImport("dwmapi")]
>   static extern IntPtr DwmExtendFrameIntoClientArea(IntPtr hWnd, ref MARGINS pMarInset);
> 
>   public MainWindow() {
>     var handle = WindowNative.GetWindowHandle(this);
>     var margins = new MARGINS { cxLeftWidth = 0, cxRightWidth = 0, cyBottomHeight = 0, cyTopHeight = 2 };
>     Activated +=
>       (object sender, WindowActivatedEventArgs args) => DwmExtendFrameIntoClientArea(handle, ref margins);
>     ExtendsContentIntoTitleBar = true;
>   }
> 
>   // ...
> 
> }
> ```

This workaround no longer works for at least WASDK 1.4/1.5. I have not tried older versions.

**Comment by pavel-zhukov** [comment]
The workaround still works for me. Win10, WASDK 1.5.

**Comment by pingzing** [comment]
> A workaround:
> 
> ```
> using System;
> using System.Runtime.InteropServices;
> using WinRT.Interop;
> 
> public sealed partial class MainWindow : Window {
> 
>   [StructLayout(LayoutKind.Sequential)]
>   struct MARGINS {
>     public int cxLeftWidth;
>     public int cxRightWidth;
>     public int cyTopHeight;
>     public int cyBottomHeight;
>   }
> 
>   [DllImport("dwmapi")]
>   static extern IntPtr DwmExtendFrameIntoClientArea(IntPtr hWnd, ref MARGINS pMarInset);
> 
>   public MainWindow() {
>     var handle = WindowNative.GetWindowHandle(this);
>     var margins = new MARGINS { cxLeftWidth = 0, cxRightWidth = 0, cyBottomHeight = 0, cyTopHeight = 2 };
>     Activated +=
>       (object sender, WindowActivatedEventArgs args) => DwmExtendFrameIntoClientArea(handle, ref margins);
>     ExtendsContentIntoTitleBar = true;
>   }
> 
>   // ...
> 
> }
> ```

This workaround still works as of WASDK 1.6, but with a small caveat: the following _does not work_

```csharp
// Some Microsoft.UI.XamlWindow

// Assume that all the PInvoke and MARGINS struct stuff is defined above

var titleBar = AppWindow.TitleBar;
titleBar.ExtendsContentIntoTitleBar = true; // <-- Doesn't work with the DwmExtendFrameIntoClientArea workaround!
Activated +=
    (object sender, WindowActivatedEventArgs args) => DwmExtendFrameIntoClientArea(handle, ref margins);
```

Whereas this following DOES work:

```csharp
// Some Microsoft.UI.XamlWindow

// Assume that all the PInvoke and MARGINS struct stuff is defined above

this.ExtendsContentIntoTitleBar = true; // Using the property directly on `Window` *does* work!
Activated +=
    (object sender, WindowActivatedEventArgs args) => DwmExtendFrameIntoClientArea(handle, ref margins);
```

Not sure what the underlying difference is, but using `AppWidnow.TitleBar.ExtendsContentIntoTitleBar` seems to not play nicely with `DwmExtendFrameIntoClientArea()`.

**Comment by bongvisu** [comment]
thanks!

2024년 12월 4일 (수) 오전 8:29, Neil McAlister ***@***.***>님이 작성:

**Comment by bogdan-patraucean** [comment]
Did anyone try the workaround in Windows App SDK 2.2? It does not seem to work anymore. If I do this, I loose all the borders now.
