### ISSUE TITLE
SetTitleBar partially occludes the supplied UIElement

### ISSUE THREAD

**Issue by sakurai-5317** [microsoft/microsoft-ui-xaml#6903]
### Describe the bug

Calling `Window.SetTitleBar` with a `UIElement` causes that `UIElement` to be partially occluded by an acrylic brush, mostly hiding the `ULElement` from view and making `SetTitleBar` pointless.

### Steps to reproduce the bug

Create a `Window` with the following XAML:

```xaml
                <Window>
                    <Grid>
                        <Grid.RowDefinitions>
                            <RowDefinition Height="40" />
                            <RowDefinition />
                        </Grid.RowDefinitions>
                        <Grid
                            x:Name="AppNonClientArea"
                            IsHitTestVisible="False">
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="Auto" />
                                <ColumnDefinition />
                                <ColumnDefinition Width="120" />
                            </Grid.ColumnDefinitions>
                            <Border
                                IsHitTestVisible="False"
                                Padding="6,8,4,8">
                                <Image
                                    Width="16" Height="16"
                                    VerticalAlignment="Center"
                                    HorizontalAlignment="Left"
                                    Margin="4" />
                            </Border>
                            <Border
                                IsHitTestVisible="False"
                                Grid.Column="1">
                                <TextBlock
                                    IsHitTestVisible="False"
                                    Style="{StaticResource CaptionTextBlockStyle}"
                                    Foreground="{ThemeResource TextFillColorPrimaryBrush}"
                                    VerticalAlignment="Center"
                                    HorizontalTextAlignment="Left"
                                    Text="Window Title" />
                            </Border>
                        </Grid>
                        <Border
                            Grid.Row="1"
                            Background="{ThemeResource AcrylicBackgroundFillColorDefaultBrush}">
                            <TextBlock>Content here</TextBlock>
                        </Border>
                    </Grid>
                </Window>
```

Then in the window's code behind:

```cs
ExtendsContentIntoTitleBar = true;
SetTitleBar(AppNonClientArea);
```

### Expected behavior

The `UIElement` passed to `SetTitleBar` is visible in the foreground, above any Acrylic brushes drawn by the system.

### Screenshots

![image](https://user-images.githubusercontent.com/102683793/160880980-e8b8053a-8cf0-46b1-a66f-fd65b9e37c7a.png)

![image](https://user-images.githubusercontent.com/102683793/160881140-503fead9-44e7-45d2-bb6f-5f45dfbedbd1.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000, Windows 10 (21H1): Build 19043

### Additional context

Cannot select Windows App SDK 1.0.1 in the NuGet package version for this issue.  This does not appear to affect 1.0.0 unless the 1.0.1 runtime is installed.

**Comment by ParkhutRoman** [comment]
You can edit default WindowChromeStyle , more here https://github.com/microsoft/WindowsAppSDK/issues/1626

**Comment by lhak** [comment]
There has definitely been a change in the template of the window controls styles. In 1.0.1 the buttons are now on top of the window content. In my opinion this makes it a lot easier to implement custom titlebars and works similar to the UWP titlebar. 

I think the SetTitleBar() call only sets the area where the window can be draged. It does not change the rendering of the passed UIElement.
