### ISSUE TITLE
Application Hangs with UniformGridLayout with Data Binding using XamlReader

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#6904]
### Describe the bug

When loading some XAML with ItemsRepeater and a UniformGridLayout dynamically via XamlReader:

```xml
        <muxc:ItemsRepeater 
            ItemsSource="{Binding}">
            <muxc:ItemsRepeater.Layout>
                <muxc:UniformGridLayout Orientation="Horizontal" 
                                        MinItemWidth="200" MinItemHeight="200"
                                        MinRowSpacing="16" MinColumnSpacing="8"
                                        ItemsStretch="Uniform"
                                        />
            </muxc:ItemsRepeater.Layout>
            <muxc:ItemsRepeater.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <Border Background="#99FFFFFF" VerticalAlignment="Bottom">
                            <TextBlock Text="{Binding title}" TextWrapping="WrapWholeWords"
                                    Foreground="Black" Margin="4"/>
                        </Border>
                    </Grid>
                </DataTemplate>
            </muxc:ItemsRepeater.ItemTemplate>
        </muxc:ItemsRepeater>
```

With an associated DataContext, the application will hang indefinitely.

I hit this when upgrading XAML Studio to use WinUI 2.7.1 from 2.3.1911. Thought I had broken something else, but this broke my go-to example of a conversion of the Toolkit's AdaptiveGridView to use UniformGridLayout instead, as we'd like this scenario to work to deprecate `AdaptiveGridView` in the future.

Appears this broke in WinUI 2.5.

### Steps to reproduce the bug

1. Run the attached project:
[UniformGridLayoutIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8383016/UniformGridLayoutIssue.zip)
2. Click button, see issue.

Note: Downgrade package reference to 2.4.3 and it'll work fine.

Also Note: `ScrollViewer` can be removed too from `DynamicFiles\Visual.xaml` and it still repros.

### Expected behavior

Application shouldn't hang and content should be loaded.

### Screenshots

CPU and memory seem to be consistent during hang:

![image](https://user-images.githubusercontent.com/24302614/160903654-0835a0f3-68c9-4cfe-8a6e-147ef408d762.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Possibly Related to #6799 and #6689

**Comment by chingucoding** [comment]
The behavior was correct in https://github.com/microsoft/microsoft-ui-xaml/tree/v2.5.0-prerelease.200708003 but regressed with https://github.com/microsoft/microsoft-ui-xaml/tree/v2.5.0-prerelease.200812001. Not sure what exactly is causing this, it might be WinUI just hitting a bug in the OS right now.

**Comment by michael-hawker** [comment]
> Not sure what exactly is causing this, it might be WinUI just hitting a bug in the OS right now.

Note, that using the older package on the same OS version is working, so you're saying that something about the change in the code might be hitting a new OS issue? However, if we can identify the changed bits between those two versions in the code, could we possibly revert or work-around it still?

There were definitely changes to some of the layout related code as seen in the diff for the UniformGrid files here: https://github.com/microsoft/microsoft-ui-xaml/compare/v2.5.0-prerelease.200708003...v2.5.0-prerelease.200812001#diff-aef8e5d00840ae38a1ba4b51a391f62d0cc2c1d46db0f6f8ebe8ad8f0d78aaf5L75

@chingucoding, I think they're all encapsulated in the PR you did here to fix this crash: https://github.com/microsoft/microsoft-ui-xaml/pull/2969

Could we try reverting that change locally and seeing if that resolves the issue here? Then find a way to forward-fix the original issue and this new regression, if that's the case?
