### ISSUE TITLE
Question: Location of WinUI 3.0 Default Control Templates

### ISSUE THREAD

**Issue by tuggernuts** [microsoft/microsoft-ui-xaml#6905]
Where exactly can I find the current default control templates for WinUI 3.0? I've been searching here and elsewhere for definitive information on this, and I can't find any guidance. There seems to have been changes over time as to the location on disk.

Specifically, I just need to get at the default template for a TextBox. Everything I've been able to locate on my machine appears to be slightly different than the actual default template being employed at run time.

**Comment by castorix** [comment]
> Specifically, I just need to get at the default template for a TextBox.

It should be in **generic.xaml**
at
`<Style TargetType="TextBox">`

**Comment by tuggernuts** [comment]
> It should be in **generic.xaml** ...

I'm sorry, but this is not helpful. Obviously, the template is going to be in Generic.xaml.

The question is: where can the applicable generic.xaml file be found for a WinUI 3 app?  How do I know what template is being applied? I've found several on my machine, but some do not contain the template for a TextBox, and some contain a template that appears to be different than the template that is applied at runtime. I can tell this by copying the template and applying as a style as a static resource. It looks different.

More importantly, where is this documented? Where do I go to see how to find the location of any given template?

**Comment by ParkhutRoman** [comment]
@tuggernuts  `%USERPROFILE%\.nuget\packages\microsoft.windowsappsdk\[lib version]\lib\[TargetFramework]\Microsoft.WinUI\Themes`
for example 
`%USERPROFILE%\.nuget\packages\microsoft.windowsappsdk\1.1.0-preview1\lib\net5.0-windows10.0.22000.0\Microsoft.WinUI\Themes`
don't edit generic.xaml, just use for reference or to override default in your own generic.xaml

**Comment by ParkhutRoman** [comment]
> How do I know what template is being applied?

now no way to know, we need to wait Xaml Designer to work with WinUI 3.0

**Comment by tuggernuts** [comment]
Thank you, @ParkhutRoman.

I understand how to use these files. I just don't know WHERE to find these files - other than blindly fumbling about.  And if there is no way to know what template is being applied, how can you point me to those .nuget directories with any confidence? 

Because when I swap out the template (which I don't intend to do in production) using a style taken from the location you provided...there is a small difference in rendering. So am I really finding the right template?

I am not trying to be difficult, just frustrated. It is disconcerting that using this framework requires divining rods and augury. This was straightforward in WPF & even UWP.

jerry

And are you really in Lviv now? If so, please stay safe. Слава Україні

**Comment by ParkhutRoman** [comment]
@tuggernuts 
> And are you really in Lviv now? If so, please stay safe. Слава Україні

Героям слава. It is safe here at the moment. Thx.

> So am I really finding the right template?

To get 100% path what lib control(TextBox for example) using just Go To Definition
![image](https://user-images.githubusercontent.com/12161245/161190049-5a480f75-ba6f-4896-9b78-da7958cbed31.png)

and there will be a path in the decompiled header
![image](https://user-images.githubusercontent.com/12161245/161190462-87726f9b-4791-448c-8bec-582b2c4bab8f.png)

> I am not trying to be difficult, just frustrated. It is disconcerting that using this framework requires divining rods and augury. This was straightforward in WPF & even UWP.

Yep in WPF/UWP we could just Edit Template in Xaml Designer and don't care where its from in 90% cases.
![image](https://user-images.githubusercontent.com/12161245/161191200-2563a51c-6c43-4b2b-8881-2dd337c24aac.png)

**Comment by tuggernuts** [comment]
@ParkhutRoman Thank you.

**Comment by krschau** [comment]
Thanks for answering this, @ParkhutRoman.
