### ISSUE TITLE
Cannot subclass Selector control

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#6911]
### Describe the bug

You can't in C# subclass the Microsoft.UI.Xaml.Controls.Primitives.Selector primitive.
It currently has a constructor that takes `WinRT.DerivedComposed` or `WinRT.IObjectReference`, but otherwise no useable constructor.

### Steps to reproduce the bug

Attempt to create a custom control that derives from Selector:
```cs
    public class Ribbon : Microsoft.UI.Xaml.Controls.Primitives.Selector
    {
        public Ribbon() : base(WinRT.DerivedComposed.Instance)
        {
            DefaultStyleKey = typeof(Ribbon);
        }
    }
```

### Expected behavior

Selector is sub-classable similar to how it is in WPF.

### Screenshots

![image](https://user-images.githubusercontent.com/1378165/161090403-525bce75-0de5-422f-b22f-9e02f97ef4a6.png)

Trying with passing in "Instance" gets an odd NullRef exception when trying to set the style key:
![image](https://user-images.githubusercontent.com/1378165/161091427-f8933d7f-8a8d-4463-bb9c-8db097d2a4e0.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by ojhad** [comment]
@MikeHillberg FYI

**Comment by pharazfadaei** [comment]
I'm having the same issue with `MenuFlyoutItemBase`.

**Comment by ranjeshj** [comment]
linking to https://github.com/microsoft/microsoft-ui-xaml/issues/780. We can use that proposal to track anything that blocks subclassing from platform types.
