### ISSUE TITLE
Faulting module name : Windows.UI.Xaml.dll, version : 10.0.22000.593

### ISSUE THREAD

**Issue by LRDR6** [microsoft/microsoft-ui-xaml#6913]
Microsoft photos app keeps crashing for me, either when I press F11 to go fullscreen, when I use the left and right keys to navigate between photos or even just crashing 3-5 seconds after I open a picture. 
I've tried uninstalling and reinstalling the app using Powershell, running DISM tool, checking for viruses, checking/cleaning registries using CCleaner... I even did a complete clean reinstall of Windows 11 using the Media Creation tool and a brand new USB flash drive, none of these managed to resolve the issue.

This is my first time using GitHub so I apologize if this is not the correct way to submit a bug report.

Log Name :Application 
Source :       Application Error 
Date :         30.03.2022 21:04:21 
Event ID :1000 
Task Category :(100) 
Level :       Error 
Keywords :    Classic 
User :  N/A 
Computer :   PC-LD 
Description : 
Faulting application name: Microsoft.Photos.exe, version : 2021.21120.8011.0, time stamp : 0x61b15fec 
Faulting module name : Windows.UI.Xaml.dll, version : 10.0.22000.593, time stamp : 0x79c78cff 
Exception code : 0xc000027b 
Fault offset : 0x0000000000834ac0 
Faulting process ID : 0x4798 
Faulting application start time : 0x01d84468eb685e3a 
Faulting application path : C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2021.21120.8011.0_x64__8wekyb3d8bbwe\Microsoft.Photos.exe 
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll 
Report Id : 5bb090f3-8478-43e7-9556-6af5a60d6552 
Faulting package full name : Microsoft.Windows.Photos_2021.21120.8011.0_x64__8wekyb3d8bbwe 
Faulting package-relative application ID : App 
Event XML : http://schemas.microsoft.com/win/2004/08/events/event">             1000     0     2     100     0     0x80000000000000          3186               Application     PC-LD                Microsoft.Photos.exe     2021.21120.8011.0     61b15fec     Windows.UI.Xaml.dll     10.0.22000.593     79c78cff     c000027b     0000000000834ac0     4798     01d84468eb685e3a     C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2021.21120.8011.0_x64__8wekyb3d8bbwe\Microsoft.Photos.exe     C:\Windows\System32\Windows.UI.Xaml.dll     5bb090f3-8478-43e7-9556-6af5a60d6552     Microsoft.Windows.Photos_2021.21120.8011.0_x64__8wekyb3d8bbwe     App

**Comment by ojhad** [comment]
Hey, could you file this feedback via feedback hub? This will allow the app team to get the right information to look into this. Thanks!

**Comment by ebug64** [comment]
Hi there. Did you ever find a solution to this? It's been driving me crazy for months now. I can't trim videos using Photos Legacy without the app crashing.
