### ISSUE TITLE
Problems with the display of pages from a dynamically loaded assemblyBug title

### ISSUE THREAD

**Issue by amazatis** [microsoft/microsoft-ui-xaml#6920]
### Describe the bug

I am writing an app in WinUi with which it should be possible to reload plug-ins. The problem is that when I instantiate a page in my dynamically called method from a reloaded assembly and return it, it crashed. If I use a standard page, it is displayed successfully. I do not understand the difference. In the example the TestPage is also of type Page (WinUI Page).

--- MainWindow.xaml.cs
assembly = Assembly.LoadFile(dir);
var types = assembly.GetTypes();
string classname = module.Namespace + "." + module.Classname;
type = assembly.GetType(classname);
method = type.GetMethod("ShowModule", objectTypes);
classInstance = Activator.CreateInstance(type);
mResult = (ModuleResult)method.Invoke(classInstance, param);
this.ContentHost.Children.Add(mResult.Page);

--- Module assembly
public override ModuleResult ShowModule(ModuleParameters iModulParameters)
{
TestPage module = new TestPage(); // --- It crashed => this ist a empty Page
moduleResult.Content = module;

//Page module = new Page(); // --- works successfully
//moduleResult.Content = module;

return moduleResult;
}

### Steps to reproduce the bug

--- MainWindow.xaml.cs
assembly = Assembly.LoadFile(dir);
var types = assembly.GetTypes();
string classname = module.Namespace + "." + module.Classname;
type = assembly.GetType(classname);
method = type.GetMethod("ShowModule", objectTypes);
classInstance = Activator.CreateInstance(type);
mResult = (ModuleResult)method.Invoke(classInstance, param);
this.ContentHost.Children.Add(mResult.Page);

--- Module assembly
public override ModuleResult ShowModule(ModuleParameters iModulParameters)
{
TestPage module = new TestPage(); // --- It crashed => this ist a empty Page
moduleResult.Content = module;

//Page module = new Page(); // --- works successfully
//moduleResult.Content = module;

return moduleResult;
}

### Screenshots

![188150-screenshot-2022-03-30-074759](https://user-images.githubusercontent.com/99548469/161257533-28f6b437-5b74-4fe7-8b6a-e9aeb73fb687.jpg)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ojhad** [comment]
@Scottj1s Is this a supported scenario for CSWinRT?

**Comment by amazatis** [comment]
I hope so. I need this possibility in WinUI for applications to be able to insert plug-ins. This technique has worked under WPF, UWP.
