### ISSUE TITLE
ListView/GridView crashes with incremental loading

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#6921]
### Describe the bug

ListView/GridView crashes when binding to a list with incremental loading support. The crash happens after the `LoadMoreItemsAsync` call.

This is a regression from 1.0.0. 1.0.1/1.1.0-preview both have this issue.

### Steps to reproduce the bug

Sample collection:
```csharp
    public class MyCollection<T> : ObservableCollection<T>, ISupportIncrementalLoading
    {
        public MyCollection() { }

        public IAsyncOperation<LoadMoreItemsResult> LoadMoreItemsAsync(uint count)
            => Task.FromResult(new LoadMoreItemsResult(0)).AsAsyncOperation();

        public bool HasMoreItems => true;
    }
```

The implementation of incremental loading is incomplete, but it's sufficient crashes ListView when `HasMoreItems` returns `true`.
Bind a `ListView` to this `MyObject<object>`.

The exact exception message can vary depending on the containing visual tree. Putting the ListView to window root is enough to crash.

### Expected behavior

Incremental loading works correctly.

### Screenshots

N/A

### NuGet package version

WinUI 3 - Windows App SDK 1.0.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by dylech30th** [comment]
#6883

**Comment by huoyaoyuan** [comment]
Closing as a duplicate of #6883.
