### ISSUE TITLE
How to detect hotspot when clicking on a Microsoft.UI.Xaml.Controls.NavigationViewItem

### ISSUE THREAD

**Issue by rcohn** [microsoft/microsoft-ui-xaml#6923]
Hello -

Is there a clean way to detect where on a NavigationViewItem the user has clicked?

The scenario is that I would like to respond to a NavigationView.ItemInvoked event differently if the user clicks on the left part of the NavigationViewItem compared to having clicked on the right part of the item.

Another way to do this would be to somehow define a "hotspot" on the item.  Clicking in that hotspot would provide this capability.  The only way I can think of is to capture the cursor position at the time the ItemInvoked handler has been called, and use that position relative to the parent container of the NavigationView to carry out "hotspot" activity.  But that's a bit of a hack.  Hopefully there's some kind of built-in mapping capability in the NavigationViewItem.

Thanks very much for any pointers that can be provided.

**Comment by dkreho1** [comment]
One way of achieving that would be to respond to PointerPressed event of the given NavigationViewItem. Here is how I did it in C++.

    navigationViewItem.PointerPressed([](winrt::Windows::Foundation::IInspectable const& sender, winrt::Microsoft::UI::Xaml::Input::PointerRoutedEventArgs const& args) {

        auto navigationViewItem = winrt::unbox_value<winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem>(sender);

        winrt::Windows::Foundation::Point point = args.GetCurrentPoint(navigationViewItem).Position();

        if (point.X < navigationViewItem.ActualWidth() / 2) {
            // Click detected in left part of NavigationViewItem
        } else {
            // Click detected in right part of NavigationViewItem
        }
    });

GetCurrentPoint returns a point pressed, relative to the UI Element that is the method parameter. Using the NavigationViewItem itself as the parameter you get where that point is inside the item, then just compare it to half of the width of the item. Hope this helps 😀

**Comment by rcohn** [comment]
Hi @dkreho1 -

Your information is going to be very helpful.  I suspected it would be something like this - just didn't know how to go about getting the click position.  I'll give this a try.

Very much appreciated!

**Comment by ojhad** [comment]
Thanks @dkreho1 for answering this question!
