### ISSUE TITLE
AutoSuggestBox: input not selectable in the secondary menu of the CommandBar/Flyout

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#6924]
### Describe the bug

When an AutoSuggestBox is added to the secondary CommandBar/Flyout menu, the AutoSuggestBox input is not selectable. The AutoSuggestBox in the primary commands works as expected.

```xaml
           <muxc:CommandBarFlyout 
                x:Name="CommandBarFlyout1"
                Placement="Right">
                <muxc:CommandBarFlyout.PrimaryCommands>
                    <AppBarElementContainer>
                        <AutoSuggestBox 
                        Width="200"
                        Height="40"
                        QueryIcon="Find"
                        VerticalAlignment="Center"
                        Margin="0,0,1,0" />
                    </AppBarElementContainer>
                    <AppBarButton Label="Save" Icon="Cancel" ToolTipService.ToolTip="Save"  />
                    <AppBarButton Label="Delete" Icon="Delete" ToolTipService.ToolTip="Delete"  />
                </muxc:CommandBarFlyout.PrimaryCommands>
                <muxc:CommandBarFlyout.SecondaryCommands>
                    <AppBarElementContainer>
                        <AutoSuggestBox 
                        Width="200"
                        Height="40"
                        QueryIcon="Find"
                        VerticalAlignment="Center"
                        Margin="0,0,1,0" />
                    </AppBarElementContainer>
                </muxc:CommandBarFlyout.SecondaryCommands>
            </muxc:CommandBarFlyout>
```

### Steps to reproduce the bug

1. Add an AutoSuggestBox with AppBarElementContainer in the secondary commands of the CommandBar/Flyout
2. Open the CommandBar/Flyout
3. The AutoSuggestBox input is not selectable

### Expected behavior

The AutoSuggestBox should works in the same way in the secondary commands, like in the primary commands.

### Screenshots

![AutoSuggestBox](https://user-images.githubusercontent.com/10946850/161393759-9b85cbc8-028c-4c97-9a50-b01b8412bb3c.gif)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [x] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by ojhad** [comment]
CommandBar flyout is meant for single actions in a contextual fashion. What are you trying to achieve here? Maybe a custom popup would be more appropriate?

**Comment by jp-weber** [comment]
It is an example to show that the same bug exists in the CommandBar and the CommandBarFlyout. The bug should also exist in WinUI3, but I have not tested it.

This shows the error in my application by using a CommandBar in the NavigationView header for the search:
![2fast_search](https://user-images.githubusercontent.com/10946850/162506806-ccb572c7-f5ea-475c-803b-2b671517b3ed.gif)

**Comment by stephtr** [comment]
Yes, it also exists in WinUI3.

> CommandBar flyout is meant for single actions in a contextual fashion. What are you trying to achieve here? Maybe a custom popup would be more appropriate?

Even the TabbedCommandBar example of the Windows Community Toolkit Sample App exhibits that issue (and a use case which makes sense in my opinion):

https://user-images.githubusercontent.com/5764184/212468977-769371a9-5ed0-45db-8282-20807452962e.mp4

**Comment by jp-weber** [comment]
Any news for the issue?

**Comment by jp-weber** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/8614#issuecomment-1889995863
