### ISSUE TITLE
Question: Are WinUI3 MenuFlyout and other flyouts able to leave the application window?

### ISSUE THREAD

**Issue by kurmachu** [microsoft/microsoft-ui-xaml#6925]
In windows, most context menus are separate from their respective window, and can "float" past the window borders. However, from looking at the WinUI3 controls gallery, it seems that context menus are restricted to the application window. Is this just the control gallery, or is this actually a limitation of WinUI3? If so, are there plans to add this functionality? (Say, when background acrylic and multi window support launches?)

Compare the uwp xaml gallery and the WinUI3 gallery:
![image](https://user-images.githubusercontent.com/31492625/161405656-62b12623-f09e-4707-a5a8-4a7ea982d2e1.png)
![image](https://user-images.githubusercontent.com/31492625/161405660-0d316a94-3a3c-4404-8a8b-adcd255a1498.png)

**Comment by castorix** [comment]
It is a known problem : [#5958](https://github.com/microsoft/microsoft-ui-xaml/issues/5958)
