### ISSUE TITLE
TitleTemplate shows (almost) no effect

### ISSUE THREAD

**Issue by amazatis** [microsoft/microsoft-ui-xaml#6926]
### Describe the bug

I wanted to create a style for a ContentDialog and found one from UWP. However, it has no effect. Then I tried to adjust the title in the template in the ContentDialog. Unfortunately, only the size is changed. The background and text are not displayed. Why can't the ContentDialog be styled? Is this a bug?

### Steps to reproduce the bug

    <ContentDialog.TitleTemplate>
        <DataTemplate>
            <Border Height="50" HorizontalAlignment="Stretch" Background="Yellow" BorderBrush="Red" BorderThickness="0,0,0,1" >
                <TextBlock x:Name="Title" Style="{StaticResource SubheaderTextBlockStyle}" />
            </Border>
        </DataTemplate>
    </ContentDialog.TitleTemplate>

### Screenshots

<img width="242" alt="image" src="https://user-images.githubusercontent.com/99548469/161437940-d26a549d-5c8c-452a-b460-b0b60e799c7e.png">

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ojhad** [comment]
@amazatis Looks like your TitleTemplate does not contain any content. I assume this is why you are not seeing an effect. Adding some content should solve your problem.

**Comment by amazatis** [comment]
Yes, would work. However, I don't get the desired effect with Border. The border size depends on the length of the text. I would like to use Border to create a title bar across the entire width of the dialogue and at the top.
