### ISSUE TITLE
Crash in exe when selecting tab which binds to ObservableCollection<UIElement>

### ISSUE THREAD

**Issue by TRadigk** [microsoft/microsoft-ui-xaml#6931]
### Describe the bug

Hi dear team of WindowsAppSDK developers,
today I would like to forward an issue I discovered recently. The scenario is as follows:
As a user I want to have multiple views accessible via Tabs, which can be put into separate windows (undock) and put back into the TabView (dock), as I know from my WebBrowser.

As far as I know this is not yet supported, as the example from WinUi controls gallery (V1.13.10.0) states today. Checking https://portal.productboard.com/winappsdk/1-windows-app-sdk/tabs/2-planned I found this is not even on the agenda, though the framework already hit Version 1.0.0 ("feature complete" ??).

In my current implementation I perform the steps described below but found that a crash in my exe occurs, which can't be investigated with the VisualStudio (2022) debugger. I can even tell that the issue is within a binding to a collection of complex items, but not like "string". In my code I can "pop out" the tab into a new window, and on closing, create a new tab with the same content, the window showed last. When, while in window state, the content if the underlying ViewModel (singleton) is changed, and the window gets closed, a new tab is created. But when the tab is selected, the crash occurs. This crash does not occur when the collection is of string (got this example in another tab). This crash does also not occur as long as the collection is not changed (but e.g. initialized with one element).
I've experimented with collapsing the visibility of the tab, which is selected for "new window" and restoring visibility on window close, but without success. Neither does it make a difference of using a new or the same instance of the same view.
At some point I was able to hit errors like "writing to protected memory or corrupt memory" or something like "C++ error at memory location xyz". It looked like depending on the type of collection visualizer, like ListView, ItemsControl and so on. The error does not seem to be different between 1.0.0, 1.0.1 or 1.1.0 preview 1.

Please let me know if:
* "tab to window" is a feature you will address in the future (would also be nice to know kind of "when")
* there is a workaround
* a code sample is required

### Steps to reproduce the bug

1. Create a Tab Layout with tabs bound from a collection of a ViewModel
2. Let at least one  tab host a page as content
3. Let the page bind to properties of a ViewModel
4. Let the ViewModel have an ObservableCollection of complex type (like UIElement)
5. On ButtonClick delete the tab from the viewmodel tab collection, create a new instance of the tabs content (page) and use it as content for the window
6. modify the content of the ViewModel via another button action, so that the content of the view in the new window changes
7. Close the new window and invoke creation of a new tab with the same type of page as content
8. Select the tab

### Expected behavior

As a user I am able to pull* tabs out of its container which creates a new window with the same content as the tab showed (as like modern browsers and other applications allow).

* or create via click on a button

### Screenshots

(sorry for the screenshot with german localization)
![grafik](https://user-images.githubusercontent.com/92845708/161605246-0770aa77-b8aa-4112-ae8e-1b048b2d0e75.png)

### NuGet package version

1.1.0-preview1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

### Additional context

Microsoft.Extensions.DependencyInjection" Version="6.0.0" 
Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" 
Microsoft.Toolkit.Mvvm" Version="7.1.2" 
Microsoft.WindowsAppSDK" Version="1.1.0-preview1"
Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.194"
WinUIEx" Version="1.2.0"

**Comment by btueffers** [comment]
https://task.ms/38831750

**Comment by TRadigk** [comment]
As a workaround I switched to transient ViewModels and reload the data to be displayed upon construction (if possible). This results in a very minor delay upon loading which I am willing to pay for "not crashing" executable. If the delay would be bigger I could display a spinner, but how would I know when the xaml tree is loaded completely?
Nevertheless I am curious how this "feels" with a Tab-Experience like in today's web browsers.

**Comment by TRadigk** [comment]
An example is found in Winui3 Gallery, which I didn't try myself yet, but accept as possible solution.
