### ISSUE TITLE
Visual Studio Solution Explorer does not display 'Resource' files correctly

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6932]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-Solution-Explorer-does-not/1702310)._

---
[severity:I'm unable to use this version]
In Visual Studio, I tried to change the 'generated by' property of my application icon file to 'resource', but just after that Visual Studio immediately hid the file from Solution Explorer, but the file was not deleted. folder, Solution Explorer still does not display the file correctly.
Programming language: C#
Program type: Win UI 3

---
#### Feedback Bot on 3/25/2022, 01:58 AM: 

(private comment, text removed)
#### Lady Zhang [MSFT] on 3/25/2022, 08:05 AM: 

(private comment, text removed)
#### 梓瑞 罗 on 3/30/2022, 03:51 AM: 

(private comment, text removed)
#### Feedback Bot on 3/30/2022, 07:31 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ojhad** [comment]
@fabiant3 FYI
