### ISSUE TITLE
WinUI3 app suddenly fails to deploy and run

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6934]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinUI3-app-suddenly-fails-to-deploy-and-/10000663)._

---
[severity:I'm unable to use this version]
My development environment, which successfully and repeatedly built, deployed and ran under the debugger the app I'm developing for weeks with no problems, has suddenly been unable to do so. It builds with no problems. It starts the deploy under debug. And then it just silently fails. With the following message in the output pane:

The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.

This is a bad thing, on many levels.

First, that error message is absolutely useless. I would be no worse off it nothing was reported because it provides no information whatsoever about what the problem might be, what went wrong, or anything else. Error messages need to report actionable information to be of any use. Please correct this mistake (which, I'm sorry to say, is a proverbial Microsoft problem -- you need someone in charge who forbids the generation of useless error messages).

Second, and more importantly, how do I get back to developing my app? Suggestions would be welcome!

---
#### Feedback Bot on 3/31/2022, 01:54 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ojhad** [comment]
@fabiant3 FYI

**Comment by genifycom** [comment]
Same here. After weeks, suddenly fails with this error. Tried a VS 2022 restart, clean, delete obj and bin.
