### ISSUE TITLE
Question: awaiting during app exit

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#6935]
I have a one-window application using WinUI 3 with the WindowsAppSDK. In OnLaunched I create a Window, assign content to Window.Content, hook up the Close event, and call Window.Activate(). It all works fine. When the window is closed I receive the Close event on the UI thread. When the close event handler exits (with args.Handed = false), the app exits. 

My question is, how can I await a cleanup task before the app exits? Say I create a cleanupTask for the cleanup work -- writing a file, for example. If I make the close handler <c>async void</c> and use <c>await cleanupTask</c> then the handler returns when it hits the <c>await</c> and the app exits before the task completes. On the other hand if I use cleanupTask.Wait() then it frequently deadlocks because at the time the Close was triggered by the user there were (or could be) various UI tasks being awaited within the app, any one of which may attempt to re-aquire the UI thread while the close handler is doing a Wait on the UI thread. 

Is there some standard way of doing this? 

Edit: what I am currently doing is cancelling the close by setting args.Handled = true, and then starting a task that awaits the cleanup and then closes the window. Since the "close" button is still accessible to the user during the cleanup, this means resetting the close event handler to do nothing but ignore intervening close requests, then resetting it again when the cleanup is done and we are actually ready to close. It's a bit of a pain and also one has to replace the rest of the UI so that the user doesn't do anything while the cleanup is in progress.  There should be an easier way --

**Comment by ojhad** [comment]
@bpulliam FYI
