### ISSUE TITLE
[WinUI 3] Changing the theme of the NavigationView doesn't work as expected

### ISSUE THREAD

**Issue by mgnsm** [microsoft/microsoft-ui-xaml#6938]
### Describe the bug

When I set the `RequestedTheme` property of a `NavigationView` in WinUI 3 (targeting version 1.0.1 of the Microsoft.WindowsAppSDK package) to `ElementTheme.Dark`, the background brushes are not changed as expected.

Given the following XAML markup:

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <NavigationView x:Name="navigationView">
            <NavigationView.MenuItems>
                <NavigationViewItem Content="Item A" />
                <NavigationViewItem Content="Item B" />
                <NavigationViewItem Content="Item C" />
            </NavigationView.MenuItems>
        </NavigationView>

        <Button Content="Switch Theme" Click="Button_Click" />
    </Grid>

...the control initially looks like this:

![image](https://user-images.githubusercontent.com/29161836/161999347-9a3f6349-fa70-47aa-a4c0-416700f4cc83.png)

After changing the theme using the following code:

    private void Button_Click(object sender, RoutedEventArgs e)
    {
        navigationView.RequestedTheme = ElementTheme.Dark;
    }

...it looks like this:

![image](https://user-images.githubusercontent.com/29161836/161999757-1fbd8dd7-05c8-40f1-8fca-e9202c168006.png)

The foreground color seems to have changed but the background is still light which means  I can no longer see the navigation items...

### Steps to reproduce the bug

1. Create a new WinUI 3 app using the latest version of the `Blank App, Packaged (WinUI 3 in Desktop)` template in Visual Studio 2022
2. Copy the above XAML markup into the `MainWindow.xaml` file
3. Copy the above event handler into the `MainWindow.xaml.cs` file
4. Run the app and click on the "Switch Theme" button

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (2004): Build 19041

**Comment by ghost1372** [comment]
Place the navigationview on the grid and change the grid background as follows

```
<Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
<NavigationView/>
</Grid>
```
I think this should fix your problem

**Comment by mgnsm** [comment]
> Place the navigationview on the grid and change the grid background as follows
> 
> ```
> <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
> <NavigationView/>
> </Grid>
> ```
> 
> I think this should fix your problem

This doesn't fix the problem. The background of the `NavigationView` is still not changed as expected.
