### ISSUE TITLE
WinUI VariableSizedWrapGrid Wrap beyond window

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6939]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinUI-VariableSizedWrapGrid-Wrap-beyond-/10004673)._

---
When wrapping beyond the window size, the cells are not truncating as you would expect. 
With the Orientation property set to Vertical (the default), you can resize the window width and the grid is truncated as expected, but when you resize the window height the grid cells are no longer uniform and appear to overlap one another.

The same problem happens when Orientation is set to Horizontal, but in reverse. The grid is truncated when adjusting the height of the window, and becomes non-uniform and overlaps cells when resizing the width.

---
#### Feedback Bot on 4/6/2022, 07:14 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ojhad** [comment]
Need a repro.
