### ISSUE TITLE
Where are the default WinUI3 control style files?

### ISSUE THREAD

**Issue by IVVOVVI** [microsoft/microsoft-ui-xaml#6940]
I can find UWP control style files (generic.xaml and themeresources.xaml) in this folder (C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\10.0.19041.0\Generic). Where can I find WinUI 3 control style files? I need to know the default control styles in order to customize the styles of WinUI 3 controls.

**Comment by castorix** [comment]
generic.xaml is in the current package version path 
For example :
` "%USERPROFILE%\.nuget\packages\microsoft.windowsappsdk\1.0.1\lib\uap10.0\Microsoft.UI\Themes"`

**Comment by IVVOVVI** [comment]
Thank you.
