### ISSUE TITLE
Proposal: WinUI splash screen appear after 3 to 5 seconds... Unlike UWP one click splash screen appear smoothly with just few milliseconds.

### ISSUE THREAD

**Issue by nextcodelab** [microsoft/microsoft-ui-xaml#6942]
I really like WinUI but the issue is... if you click icon in WinUI app the splash screen appear between 3 to 5 seconds without smooth animation maybe on desktop version.

Unlike UWP one click splash screen appear in just few milliseconds and have smooth animation.. 

Please improve start up on splash screen in WinUI3.

**Comment by ojhad** [comment]
This seems like a bug. @bpulliam FYI

**Comment by Aurumaker72** [comment]
It also seems like the crossfade splashscreen transition is missing from WinUI

**Comment by castorix** [comment]
You can use a Layered window
I made a basic sample : [WinUI3_SplashScreen](https://github.com/castorix/WinUI3_SplashScreen)
I added an animation (fade out) when it is destroyed, but you can also add it on creation with fade in.

**Comment by knightmeister** [comment]
It would be fantastic to have the option to use a splash screen in the same way as in UWP and define it as part of the package manifest. The system could display the splash screen as soon as the window is created and then transition to the page once WinUI and everything else is loaded.
