### ISSUE TITLE
Implement Description property in controls that dont have it.

### ISSUE THREAD

**Issue by cesarchefinho** [microsoft/microsoft-ui-xaml#6946]
the majority of controls in winui3 have Header and Descriptions properties.

To have an consistent look and feel controls like DatePicker needs to have Description.

This is important to for example display messages bellow all input controls in an padronized way

**Comment by ojhad** [comment]
Thank you for your suggestion. Unfortunately this is out of scope for the work we are doing in the near future. To achieve a similar experience I would suggest working around this by adding the control to a grid with a textblock.

**Comment by cesarchefinho** [comment]
> Thank you for your suggestion. Unfortunately this is out of scope for the work we are doing in the near future. To achieve a similar experience I would suggest working around this by adding the control to a grid with a textblock.

Adding a textblock with grid don't resolve because I'm am using an metodology that expect that the control have their description property. For example, é an error framework and other use cases.

**Comment by ojhad** [comment]
For accessibility purposes, I would recommend using Automation Properties: https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Automation.AutomationProperties?view=winrt-22000
