### ISSUE TITLE
New ScrollViewer crashes immediately in a bottoms up list using ItemsRepeater

### ISSUE THREAD

**Issue by micahl** [microsoft/microsoft-ui-xaml#695]
**Describe the bug**

I'm updating a sample app I made to use ItemsRepeater to present a bottoms-up list for a chat UX.  I'm trying to use the new ScrollViewer since the old ScrollViewer hits issue #562.  When I use the new ScrollViewer the app crashes.  
>System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component. at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)

Fwiw, if I try using Scroller only I don't see this crash which points at an issue with the new ScrollViewer.  However, assuming this was fixed, I'd expect I'd run into #561 with the new ScrollViewer since its wrapping Scroller with the UX I expect to have (i.e. scroll bars).

**Steps to reproduce the bug**

1. Clone https://github.com/micahl/bottomsuplist/tree/newscrollviewer
2. Open and build

**Expected behavior**

The app launches and I can enter dummy text messages

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| April 2019 Update (18362)         | Yes   |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by RBrid** [comment]
@Micah, does this repro for you in a Release build?  It seems to only occur in a Debug build for me.

And I'm seeing these well known errors in Debug only:
Exception thrown at 0x777233D2 (KernelBase.dll) in BottomsUpList.exe: 0xE0434352 (parameters: 0x80004002, 0x00000000, 0x00000000, 0x00000000, 0x01D10000).
Exception thrown at 0x777233D2 (KernelBase.dll) in BottomsUpList.exe: WinRT originate error - 0x80004002 : 'System.InvalidCastException: Unable to cast object of type 'Microsoft.UI.Xaml.Controls.InputKind' to type 'System.Int32'.
   at Microsoft.UI.Xaml.Markup.XamlReflectionType.CreateFromString(String value)'.
onecore\com\combase\winrt\error\restrictederror.cpp(1014)\combase.dll!762BCC1E: (caller: 761E9B71) ReturnHr(2) tid(82dc) 8007007E The specified module could not be found.
Exception thrown at 0x777233D2 (KernelBase.dll) in BottomsUpList.exe: WinRT originate error - 0x802B000A : 'Failed to assign to property 'Microsoft.UI.Xaml.Controls.Primitives.Scroller.IgnoredInputKind'. [Line: 1679 Position: 777]'.

So this is probably a dup of what the Parser team already fixed.

**Comment by micahl** [comment]
Ah, that's not the exception message I was seeing, but it didn't repro when I tried a Release build.  If I bump the app's target version to 18362 then it no longer repros in Debug.  So... it seems like it could be a dupe of that issue.  Now I hit #561 in ScrollViewer.  Closing this one.  :)
