### ISSUE TITLE
Question: How to add COM based UI-Controls (like ExplorerBrowser) to WinUI3

### ISSUE THREAD

**Issue by tajbender** [microsoft/microsoft-ui-xaml#6951]
Ages ago, Microsoft released the [Windows API Code Pack](https://github.com/timdetering/Microsoft.Windows_API_Code_Pack/tree/master/source/WindowsAPICodePack/Shell/ExplorerBrowser) for using native Windows Controls like **ExplorerBrowser** in Windows Forms Applications.

There, they've built an C#-Wrapper for the underlying COM-Based UI-Control, that then was hosted in an WinForms UserControl.

Is it possible to adopt this approach using WinUI3 / WinRT? I know, I can get the underlying native **HWND**  handle for an WinUI3 main window. Using that, in my understanding, it should at least be possible to bind the COM Control against the main window.

However, I couldn't find any more docs or examples how to connect the message loop for handling drawing, focus issues, etc pp.

Any ideas and comments on this?

Regards, and thanks in advance!

**Comment by castorix** [comment]
I did a test in C# and ExplorerBrowser can work, but I had to use a Win32 Region (_SetWindowRgn_) to enable its UI
(and I did not set the DarkMode on right part...) :

![WinUI3_ExplorerBrowser](https://user-images.githubusercontent.com/22345506/162563219-518868fa-9d39-4b12-9839-a25c0a0936d7.jpg)

**Comment by tajbender** [comment]
@castorix Thanks for your reply. Could you share the snippet?

I can get the ExplorerBrowser to be drawn into the window, but the UI still doesn't work for me 😞 

I'm new to WinUI and really appreciate your time spent on this. Thanks in advance! 👍

**Comment by castorix** [comment]
> @castorix Thanks for your reply. Could you share the snippet?

I made a more complete sample, but still using a Region : [WinUI3_ExplorerBrowser.zip](https://app.box.com/s/wmtnw883g6qjvtzuwzxszv8y7x84xj33)
(maybe there is a better way because I must remove/set it for Popup windows like ContentDialog (otherwise they are hidden by the Region)...)

![WinUI3_ExplorerBrowser2](https://user-images.githubusercontent.com/22345506/162609808-fcb4e666-e55c-478d-adb1-332a212878b6.jpg)

**Comment by tajbender** [comment]
@castorix Thank you very, very much on this! 👍 

I wonder, if there's a way to handle these overlays correctly... If you have an idea, you're welcome. However, and again, many thanks. This really helps to find out how it *could* be done.

**Comment by castorix** [comment]
The problem is that this control needs user interaction.
I don't see atm how to allow mouse without a region on the underlying  window...

**Comment by tajbender** [comment]
Hallo, @castorix,

thank you so much for your efforts.

Yes, I understand the Focus-Problem. My thought was, when the control has the focus (via keyboard or some kind of **`OnMouseOver()`**, then set the region to **`true`**.

On the other hand, when the control has lost keyboard focus, or another XAML-Control got the focus via mouse click, then set the region to **`false`** again.

The [SwapChainPanel](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swapchainpanel?view=winrt-22000t) would just handle the correct drawing issues, when the form has to repaint any stuff like overlays, etc. pp.

As said, I'm a WinUI-newbie, and just want to make sure that I don't drop the possibility of using it for my own projects in the future, although there would be _any chance_ that I can get this combination up and running, at least with some hacks 🤔 

Thank you very, very much in advance,

Regards, tajbender
