### ISSUE TITLE
Opening list in ComboBox causes layout side effects

### ISSUE THREAD

**Issue by gwalschlager** [microsoft/microsoft-ui-xaml#6956]
### Describe the bug

When clicking in a ComboBox in order to display list of choices, any immediately adjacent control to the right "disappears" until a selection is made when it reappears. 

### Steps to reproduce the bug

I assumed the adjacent control didn't disappear, but was just hidden. If I examine the ComboBox ActualWidth property while no list is showing it's 321.6. If I then click the list, the ActualWidth is reduced to 64. After making a selection, the ActualWidth is once again 321.6 so clearly the size is changing and thus causing the adjacent control to be hidden behind the ComboBox while list is open.

Create a Grid with two Auto width columns: column 0 is a ComboBox and column 1 is a ToggleSwitch. Set the source of the ComboBox to show a list of strings each of maybe 20 characters. When run, you can see the ComboBox on left and ToggleSwitch on the right. Now click in ComboBox. List will appear overlaying the combo box, but the ToggleSwitch cannot be seen. It appears to be happening because the width of the ComboBox is being reduced while the list is open, thus affecting the layout.

### Expected behavior

Clearly displaying the combo box list shouldn't affect layout.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ojhad** [comment]
@gwalschlager I would try adding a MaxWidth to the ComboBox to avoid this behavior

**Comment by JuanMejiaVelez** [comment]
This behavior is present in WinUI 2.x as well. This should not require any changes from the user to avoid it.
