### ISSUE TITLE
Question: How can we use Settings icon in our app

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#6959]
I looked at the NavigationView xaml, but couldn't find a Settings icon reference there. How can we use commonly used animated icons in our apps too?

**Comment by castorix** [comment]
Settings icons are usually Gear symbols

Like :
` FontIcon fi = new FontIcon()
            {
                FontFamily = new FontFamily("Segoe UI Emoji"),
                Glyph = "\U00002699",           
                FontSize = 50
            };`

![Gear](https://user-images.githubusercontent.com/22345506/162577614-931b9bc7-70f5-4019-9c1b-0eb709f65331.jpg)

**Comment by chingucoding** [comment]
The settings item for the NavigationView is created in code behind. The icon is being set using the following C++ code:

```c++
auto const settingsItem = m_settingsItem.get();
auto const settingsIcon = winrt::AnimatedIcon();
settingsIcon.Source(winrt::AnimatedSettingsVisualSource());
auto const settingsFallbackIcon = winrt::SymbolIconSource();
settingsFallbackIcon.Symbol(winrt::Symbol::Setting);
settingsIcon.FallbackIconSource(settingsFallbackIcon);
settingsItem.Icon(settingsIcon);
```

The AnimatedSettingsIconVisualSource is shipped as part of WinUI 2 so you can also use it in your app.

**Comment by harvinders** [comment]
I also found that we can do it in pure XAML too, there is a button style [PaneToggleButtonStyle] for inspiration (https://github.com/microsoft/microsoft-ui-xaml/blob/d3fef08fdf2b3e86386928097216fdfbedfda02c/dev/NavigationView/NavigationView_rs1_themeresources.xaml#L317)
