### ISSUE TITLE
XamlCompiler error WMC0010: Unknown attachable member 'foo' on element 'TextBlock'

### ISSUE THREAD

**Issue by dojo90** [microsoft/microsoft-ui-xaml#6966]
### Describe the bug

Using a custom attached property throws following error: `XamlCompiler error WMC0010: Unknown attachable member 'foo' on element 'TextBlock'`

### Steps to reproduce the bug

1. Create `Translation` class with `Set/GetNamespace`
2. use my xaml example

```cs
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using NLog;
using System;

namespace AttachedProperties
{
    public class Translation
    {
        public static readonly DependencyProperty NamespaceProperty = DependencyProperty.RegisterAttached("Namespace", typeof(string), typeof(Translation), new PropertyMetadata(default, NamespacePropertyChangedCallback));

        public static string GetNamespace(UIElement target)
        {
            return (string)target.GetValue(NamespaceProperty);
        }

        public static void SetNamespace(UIElement target, string value)
        {
            target.SetValue(NamespaceProperty, value);
        }

        private static void NamespacePropertyChangedCallback(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {

        }
    }
}
```

```xaml
<Window
...
  xmlns:attachedproperties="clr-namespace:AttachedProperties">

<TextBlock Text="Hello World" attachedproperties:Translation.Namespace="Foo"/>
```

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

I also tried this class/solution (https://github.com/microsoft/microsoft-ui-xaml/issues/2658), but I also got the same error.

**Comment by dojo90** [comment]
Changing the declaration from 'xmlns:attachedproperties="clr-namespace:AttachedProperties"' to 'xmlns:attachedproperties="using:AttachedProperties"' helped compile the application.

see: https://github.com/microsoft/microsoft-ui-xaml/issues/2667#issuecomment-643878245

Maybe one of the developers can give a short explanation what the difference is and why the namespace has to be included this way.

**Comment by MikeHillberg** [comment]
For a custom xmlns in Xaml markup, WPF uses the "clr-namespace" scheme to indicate a namespace. In WinUI we support more than just C#, so the "clr" part would be a misnomer. So we wanted a new name, and "using" was nice because it's a familiar term in C# and C++. (I'd like to make this into a semicolon-delimited list so you can put multiple WinRT namespaces into a single xmlns.)
