### ISSUE TITLE
Modifying PublishProfiles Disables Debugging

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6967]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Modifying-PublishProfiles-Disables-Debug/10000749)._

---
[severity:It's more difficult to complete my work]
I've just spent several hours wrestling with not being able to launch a WinUI3 app in the VS2022 debugger. Previously I had no problem doing so: hit F5, wait a few seconds, and everything ran.

There was no useful information provided about why the launch failed. Deployment would succeed and then the launch process would abort. The only message in the Output window was something vague about an unknown error having taken place and the suggestion it might have something to do with the app not running under the right version of dotnet (please, please, please replace these uninformative, and hence useless, error messages with something that at least points in the direction of a solution, or something to research).

In desperation I added a dummy WinUI3 app to the solution, confirmed that it ran normally under the debugger and then began comparing every file in the broken project to the test project.

I ultimately found that, somehow, the PublishProfiles in the broken app had gotten munged up. I'd be happy to share what I had to change...but I just discovered that the default .gitignore created by VS apparently exempts them from being tracked. From what I can recall the ToolsVersion attribute of the Project tag had gone missing, the platform was defined differently (i.e., not arm64, which appears to be the default), the PublishDir was different, PublishSingleFile was true (rather than the default of false), and PublishReadyToRun only appeared once (in the default/newly-created project it appears twice, once for the Debug configuration and once for all other configurations).

I had been experimenting with publishing the app as a sideload and undoubtedly messed something up in my experimentation. But there was absolutely no hint in the error message that revising/reverting the PublishProfiles might be necessary.

I urge you to:

- update the error message to include checking PublishProfiles as a possibility
- provide a way to revert PublishProfiles to a state allowing debugging to proceed

In fact, I don't understand why fixing the PublishProfiles doesn't happen automatically when the Debug configuration is active. It seems like yet another example of playing hide the football: VS2022 "knows" what it needs to launch the app under the debugger, the configuration doesn't match the necessary requirements, but it doesn't automatically modify them. Or at least give you a chance to confirm the necessary modifications before doing so.

Needless to say this makes for a really poor development experience.

---
#### Feedback Bot on 3/31/2022, 01:53 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CompCodeNet** [comment]
In line with this issue, I created a WinUI3 App using "Blank App, Packaged" template. Runs fine, but if remove PublishProfile property in csproj or remove the PublishProfiles directory, then a popup message appears about installing .net runtime.  

**1. Why does a standalone desktop app need a "PublishProfile" in order to run/debug a local build?**

**2. Documentation please!**
