### ISSUE TITLE
NavigationView is missing acrylic and shadow

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#6968]
### Describe the bug

When you open a NavigationView in LeftMinimal or LeftCompact modes, it will expand as a flyout but it doesn't have acrylic or a shadow.

### Steps to reproduce the bug

Create a NavigationView with PaneDisplayMode as LeftMinimal or LeftCompact.

### Screenshots

![image](https://user-images.githubusercontent.com/101892345/163278318-de016f0f-5cc2-44ed-937b-c0ed63fe808b.png)

### NuGet package version

2.7.1, 2.8.0-prerelease

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

The Figma design does have both of them, and it respects the design guidelines since it's an overlay.

**Comment by ojhad** [comment]
@karenbtlai this looks similar to an issue we recently encountered

**Comment by karenbtlai** [comment]
Oh yes, I remember investigating this. Turns out something happened with some dependencies, since DropShadows now require set elevation and depth for shadows to show. This is why all flyout shadows still work, since they have set elevation in codebehind already. 

Should this be a prioritized fix? @ranjeshj

**Comment by dongle-the-gadget** [comment]
Isn't Acrylic replaced by Mica for this particular use?

**Comment by dansmor7** [comment]
Not really, since it's a transient surface that overlaps other content.

**Comment by dongle-the-gadget** [comment]
> Not really, since it's a transient surface that overlaps other content.

How about in-app acrylic? It creates depth within the app

**Comment by mdtauk** [comment]
> Isn't Acrylic replaced by Mica for this particular use?

This would be for when the NavigationView is in Overlay mode.  Mica is used when the control is permanently open on the side, or in a collapsed/narrow state.

When the NavigationView slides in overlayed above the app's UI, it should be Acrylic blurring what is behind it
