### ISSUE TITLE
Error on VSIX install: This extension is not installable on any currently installed products 

### ISSUE THREAD

**Issue by sanuraghu111** [microsoft/microsoft-ui-xaml#6972]
4/14/2022 10:45:08 AM - Microsoft VSIX Installer
4/14/2022 10:45:08 AM - -------------------------------------------
4/14/2022 10:45:08 AM - vsixinstaller.exe version:
4/14/2022 10:45:08 AM - 17.1.1035-preview2
4/14/2022 10:45:08 AM - -------------------------------------------
4/14/2022 10:45:08 AM - Command line parameters:
4/14/2022 10:45:08 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\maraghu\Downloads\redhat.vscode-yaml-1.6.0.vsix
4/14/2022 10:45:08 AM - -------------------------------------------
4/14/2022 10:45:08 AM - Microsoft VSIX Installer
4/14/2022 10:45:08 AM - -------------------------------------------
4/14/2022 10:45:09 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (59357c76) since it does not support extensions
4/14/2022 10:45:09 AM - Initializing Install...
4/14/2022 10:45:09 AM - Extension Details...
4/14/2022 10:45:09 AM - 	Identifier         : vscode-yaml
4/14/2022 10:45:09 AM - 	Name               : YAML
4/14/2022 10:45:09 AM - 	Author             : redhat
4/14/2022 10:45:09 AM - 	Version            : 1.6.0
4/14/2022 10:45:09 AM - 	Description        : YAML Language Support by Red Hat, with built-in Kubernetes syntax support
4/14/2022 10:45:09 AM - 	Locale             : en-US
4/14/2022 10:45:09 AM - 	MoreInfoURL        : 
4/14/2022 10:45:09 AM - 	InstalledByMSI     : False
4/14/2022 10:45:09 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
4/14/2022 10:45:09 AM - 
4/14/2022 10:45:09 AM - 	SignatureState     : Unsigned
4/14/2022 10:45:09 AM - 	Supported Products : 
4/14/2022 10:45:09 AM - 		Microsoft.VisualStudio.Code
4/14/2022 10:45:09 AM - 			Version : 
4/14/2022 10:45:09 AM - 			ProductArchitecture : x86
4/14/2022 10:45:09 AM - 
4/14/2022 10:45:09 AM - 	References         : 
4/14/2022 10:45:09 AM - Signature Details...
4/14/2022 10:45:09 AM - 	Extension is not signed.
4/14/2022 10:45:09 AM - 
4/14/2022 10:45:09 AM - Searching for applicable products...
4/14/2022 10:45:09 AM - Found installed product - Global Location
4/14/2022 10:45:09 AM - Found installed product - Visual Studio Professional 2022
4/14/2022 10:45:09 AM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by kmgallahan** [comment]
> redhat.vscode-yaml-1.6.0.vsix

Why are you posting in this repo?

**Comment by ojhad** [comment]
This is not the correct repo for this issue.
