### ISSUE TITLE
Question: Has the OS bug fix for excessive TabViewItem memory usage shipped yet?

### ISSUE THREAD

**Issue by lukeblevins** [microsoft/microsoft-ui-xaml#6979]
If not, is there a timeframe for when this will come to Windows or the decoupled UI stack?

Context: https://github.com/microsoft/microsoft-ui-xaml/issues/3597#issuecomment-941793722

FYI @StephenLPeters @RBrid

**Comment by ojhad** [comment]
@RBrid do you have any information on this?

**Comment by RBrid** [comment]
@lukeblevins , @ojhad , the last info I got was that an OS servicing release on May 17th would include this leak fix.

The fix has also been ported into WinUI3 / WinAppSDK on 4/18. So it looks like it will be part of WinAppSDK 1.1 Preview3.

**Comment by lukeblevins** [comment]
@RBrid Was there an OS servicing release yesterday? Also did this fix ship in WinUI3 preview yet?

**Comment by lukeblevins** [comment]
@ojhad @RBrid @StephenLPeters Any update?

**Comment by lukeblevins** [comment]
@ojhad @RBrid @StephenLPeters Any update on this with v1.2 or v1.3?

**Comment by lukeblevins** [comment]
Closing myself because this bug wasn't acknowledged by the WinUI team for over a year.
