### ISSUE TITLE
👨‍💻☎ WinUI Community Call: April 20, 2022

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#6980]
### https://www.youtube.com/watch?v=bNHGU6xmUzE

# Details
Date: April 20, 2022
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

# Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. In this month's call, we'll share the latest updates around WinUI 3 in Windows App SDK, @Scottj1s will be giving us a rundown of HybridCRT and the different CRT options for WASDK applications, _and_ we'll be joined by @jlaanstra from the Phone Link (previously Your Phone) team to share their journey around how they migrated from UWP to Windows App SDK and WinUI 3.

### **Agenda**
- Intro
- Spotlight: Phone Link. Check out Johan's sample repo for how they migrated from UWP to WinUI 3: https://github.com/jlaanstra/WinAppSDK-samples
- Latest news around WinUI 3 releases & content
- Deep dive into [HybridCRT](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines/HybridCRT.md) usage and development.
- Q&A

### **Q&A Code of Conduct**
- To help ensure Q&A remains beneficial for the majority of the call's developer audience, please consider whether your question could be framed so that it might be more broadly relevant to our larger developer audience by ensuring it is reasonably concise, broadly beneficial, well-suited for the fast-paced live Q&A format, or able to spark open ended discussion.  
- Please understand some questions are not well-suited for the fast-paced live Q&A format and should be filed as standalone [Discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=discussion&template=discussion.md&title=Discussion%3A+%5Byour+discussion+title%5D) or [Question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) issues where they can be most appropriately handled. Excluding presentation topic requests, this generally includes requests for dedicated follow-ups or technically complex questions that require investigative time or expertise not included in this month's guest list.

### Leave us your questions in the comments on this issue or live in the YouTube chat during the stream!

**Comment by lukeblevins** [comment]
Need a better sense of when/by which mechanisms the servicing fix mentioned in an issue linked to this [question](https://github.com/microsoft/microsoft-ui-xaml/issues/6979) will ship. 

My project leverages TabView as a multitasking control with nested Frames in each TabViewItem and suffers from a large memory leak caused by the OS bug described in the hyperlink above. 

Is there a workaround for consumers of TabView until the servicing fix ships?

**Comment by ghost1372** [comment]
Is mica available in the second preview (1.1.0-preview2)?

**Comment by ghost1372** [comment]
when we can attach UI framework content to an AppWindow?
can we see this feature in v1.1.0?

**Comment by ghost1372** [comment]
When can we use all the multilingual capabilities like changing the language in runtime just like uwp? currently application must be restarted.

**Comment by artkat** [comment]
"Users are unable to drop an element when drag and drop is enabled."
When will this long-overdue issue finally be fixed?

**Comment by AndrewKeepCoding** [comment]
I'd like to know if we can expect a built-in DataGrid this year or it might take longer.

**Comment by harvinders** [comment]
I have asked this in the last community call, asking again, hoping this time we get a response

> Recently, the team has mentioned that they would like to concentrate on improving the quality and address fundamental infrastructure pieces. I am wondering if it would mean addressing an issue about loading Xaml controls using reflection from assemblies not part of the main app? This would enable many of us to start writing applications with plug-in architecture. Please see https://github.com/microsoft/microsoft-ui-xaml/issues/6299 for more details. Can the team say if this issue comes under core infrastructure? Any hope of getting it fixed this year?

**Comment by harvinders** [comment]
It seems that many bug fixes from this repo are not making it to WinAppSDK 1.1 preview. Could the team share with us about the plan to bring these bug fixes to WinAppSDK. Some examples that come to mind, WinUI 3 Desktop still has tab items with shadows, the tabview still missing right top border after the last item, teaching tip fails to open if IsOpen is set to true whilst it is running close animation. I think the team has fixed many many other issues and we would like to understand the timeline to bring these fixes to WinUI desktop as some are very critical for our projects.

**Comment by niels9001** [comment]
Question: when is InfoBadge expected to be available in WinUI 3 (see https://github.com/microsoft/microsoft-ui-xaml/issues/7001)?

**Comment by gabbybilka** [comment]
@MikeHillberg I believe you were wanting to check out @kmgallahan's question post-call?
