### ISSUE TITLE
ListView and GridView templates don't exist in MUX

### ISSUE THREAD

**Issue by dansmor7** [microsoft/microsoft-ui-xaml#6981]
ListView and GridView templates are not present in WinUI, they're only found in the OS files.
Is there a reason for that? Also, are there other controls that don't have exposed templates?

**Comment by Jaiganeshkumaran** [comment]
Are you using UWP? Then only controls that are open-sourced here are under the Microsoft.UI.Xaml namespace.

**Comment by dansmor7** [comment]
I wanted to talk specifically about the template.
Almost all controls that aren't open sourced have templates overridden by MUX, except for those two.

**Comment by ojhad** [comment]
We had no need to bring over those templates, so the OS generic.xaml file is a good source for those templates.

**Comment by dansmor7** [comment]
I think it's a bit weird that some things stay tied to the OS, especially when the goal is to open up everything.
One thing I wanted to suggest was adding a lightweight styling resource for ListView padding, which can't really be added without decoupling it from the OS.
