### ISSUE TITLE
CommandBarFlyout bad spacing

### ISSUE THREAD

**Issue by MikeHillberg** [microsoft/microsoft-ui-xaml#6984]
### Describe the bug

CommandBarFlyout in WinUI3 1.1 preview has a gap between the toolbar and the menu items. Doesn't repro in 1.0.

Expected (using Xaml Controls Gallery):

![image](https://user-images.githubusercontent.com/18429489/163703582-e1a7ba2d-35d7-4d1b-abb5-76ac91c82d8a.png)

Actual:

![image](https://user-images.githubusercontent.com/18429489/163703486-3aa339b6-e142-4888-859d-22c48073fd8f.png)

### Steps to reproduce the bug

CommandBarFlyout sample page in Xaml Controls Gallery.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by dimohy** [comment]
This still exists in the official 1.1 release and is bothering me.

![image](https://user-images.githubusercontent.com/58620778/176357252-329146f5-15da-4532-8cdc-eec6ce8bedd5.png)

It baffles me that it is also reproduced in WinUI 3 Gallery.

**Comment by michael-hawker** [comment]
@MikeHillberg @ranjeshj shouldn't this be assigned to a milestone to be looked at for a patch as a regression?

**Comment by bpulliam** [comment]
I'm not seeing this anymore in WinUI 3 Gallery v2.0 based on WinAppSDK 1.3.
