### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component when parsing Application.Current.Resources.MergedDictionaries

### ISSUE THREAD

**Issue by JRallee** [microsoft/microsoft-ui-xaml#6988]
I have a specific requirement to parse all SolidColorBrushes from different resource dictionaries and build something out of the same.
Trying to loop through custom resource dictionaries (ones added via App.xaml) are throwing the E_FAIL error.

In App.xaml, add,
`<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                
                <ResourceDictionary Source="Resources\Sample.xaml"/>
            </ResourceDictionary.MergedDictionaries>
             
        </ResourceDictionary>
    </Application.Resources>`
    
    
    And in Main.xaml.cs (from constructor or after launch or some button click event), add,
   ```
 foreach (var dictionary in dictionaries)
            {
                if (dictionary is XamlControlsResources) continue;
                foreach(var entry in dictionary)
                {}
    }
```
    
    This results in an error and the exception does not provide any useful information.
    Any such experiences? Or am i missing something?
    
    Attached exception stack trace,
    
<img width="596" alt="image" src="https://user-images.githubusercontent.com/16042739/163721945-86e0e06c-f6ec-482a-9581-4093c263876f.png">

**NuGet package version**
1.0.2 Stable has this issue
1.1.0 preview 1 release also has this issue

**Comment by MikeHillberg** [comment]
Does it matter what's in the Sample.xaml dictionary? I tried with it just containing this and didn't hit the crash:

```xml
<SolidColorBrush x:Key="MyBrush">Red</SolidColorBrush>
```

**Comment by JesseCol** [comment]
Hi, can you please post a repro that includes all the Xaml files you're using?  Thanks!
