### ISSUE TITLE
Translations are overwritten by any other translation

### ISSUE THREAD

**Issue by K-Steiner** [microsoft/microsoft-ui-xaml#6994]
### Describe the bug

When the list of all strings is open and the search is used, translated texts are overwritten against another text.

### Steps to reproduce the bug

1. Open a XLIFF File
2. Display the list with all strings
3. Search for a word
=> In approx. >90% a translation is overwritten with a wrong text

If not, repeat step 3 until it happens.

### Expected behavior

The search must not cause any changes

### Screenshots

![AfterLoad](https://user-images.githubusercontent.com/89185455/164054673-f2e34bda-8443-45f7-ad16-b9898e96032e.png)
![AfterSearch](https://user-images.githubusercontent.com/89185455/164054703-fb670be4-f8e2-4f1b-b97a-2a7a2314bbe5.png)

### Windows app type

- [ ] UWP
- [x] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by K-Steiner** [comment]
The real correct translation after loading
The one from picture 1 (AfterLoad) was created after the search, and is apparently only 50% defective

![RealAfterLoad](https://user-images.githubusercontent.com/89185455/164056097-a8b457a6-8c2c-4607-b44c-470f5bb09e9b.png)

**Comment by ojhad** [comment]
Which windows app type are you using? Is there a min repro you can provide?

**Comment by K-Steiner** [comment]
I use this one [standalone [Multilingual app toolkit 4.0 Editor](https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-mat)](https://go.microsoft.com/fwlink/p/?LinkID=245767&clcid=0x407) (German)

From https://docs.microsoft.com/en-us/windows/apps/design/globalizing/multilingual-app-toolkit-editor-downloads

**Comment by ojhad** [comment]
If i'm understanding correctly, this sounds like an issue with the localization tool. Is this related to WinUI in any way?

**Comment by K-Steiner** [comment]
- If i'm understanding correctly, this sounds like an issue with the localization tool.
Yes
- Is this related to WinUI in any way?
Can not say, I have not programmed it
- It looks like a timing issue to me.
It seems that the detail data is filled from the list data before the list is completely updated.

**Comment by ojhad** [comment]
This doesn't look like an issue with WinUI, so I don't think we can help. I'd suggest contacting the creators of the localization tool.
