### ISSUE TITLE
Announcing: WinUI 3 in Windows App SDK 1.1 Preview 2 🌼

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#6996]
### 1.1 Preview 2 Release of Windows App SDK 

We've just released our second preview of the 1.1 release of the Windows App SDK! This preview includes several new capabilities for WinUI 3 apps, including:
- Additional windowing functionality (see [Windows and Messages](https://docs.microsoft.com/windows/win32/api/_winmsg/)) available in AppWindow APIs.
- Tall title bar support for apps drawing custom title bars with AppWindowTitleBar.ExtendsContentIntoTitleBar.
- Improved usability and troubleshooting in Bootstrapper APIs for deployment.
- Several bug fixes across the WinUI and Notifications areas.
- Performance improvements in C# applications.

**Regression from 1.1 Preview 1:** Push notifications are not supported for unpackaged apps. This is expected to be restored in the next release.

To see everything that's new and changed, see the full [release notes here](https://aka.ms/windowsappsdk/1.1/1.1.0-preview2/release-notes). 

### What's next 
To keep up with progress being made on the Windows App SDK, please see our [feature roadmap](https://aka.ms/winappsdkroadmap), which gets updated regularly.  

### Providing feedback
As we introduce new & upcoming features in our preview releases, we appreciate all of your feedback as we work towards a stable release:
- For WinUI 3 feedback, please open an issue here, on the [WinUI repo](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose).
- For feedback regarding all other Windows App SDK components, please open an issue on the [Windows App SDK repo](https://github.com/microsoft/WindowsAppSDK/issues/new/choose).

**Comment by jschwizer99** [comment]
When using drag & drop with WinUI App SDK 1.1 Preview 2 I still face hard exceptions in `KernelBase.dll` for `get_DataView()` and `get_Modifiers()` with `An application-internal exception has occurred (parameters: 0x0000018DB3F5ABF0`. The same code works nicely with WinUI App SDK 1.0.2. I couldn't find any hint that the drag & drop issues of Preview 1 have been solved and thus assume they are still the same issues. @gabbybilka Could you confirm my observation?

I would love to try out the fixes and new functionality of Preview 2, but with drag & drop failing that hard the app is not very useful.

**Comment by gabbybilka** [comment]
@jschwizer99 Just checked in with our eng team - the drag and drop issue is not yet fixed in Preview 2. I'll update the rel notes to clarify.

However, they noted that your issue looks different/has a different cause than the one they are tracking. Can you open an issue tracking the bug found in Preview 1 with your usecase and exceptions? Thanks for letting us know.

**Comment by shelllet** [comment]
I suspect this version is still not available。 i'm debuging my app to find out what's wrong?

**Comment by shelllet** [comment]
Can't believe it's true，I think I'd be happy to be a microsoft-ui-xaml tester.

**Comment by jschwizer99** [comment]
> Can you open an issue tracking the bug found in Preview 1 with your usecase and exceptions? Thanks for letting us know.

@gabbybilka Many thanks for the fast response. I've opened a new ticket https://github.com/microsoft/microsoft-ui-xaml/issues/7002 related to the crash. When trying to break it down to a minimal version I had quite some difficulties as it turned out that the effective drop area was also far off the expected layout boundaries of the drop element.

**Comment by Samuel12321** [comment]
@gabbybilka will ShouldConstrainToRootBounds="False" be fixed in Preview 3?

**Comment by nlogozzo** [comment]
Will we see WinUI 2.7 updates to WinUI 3 in Win App SDK 1.1 for example `InfoBadge`?

**Comment by charlesroddie** [comment]
Where is the best place to track AOT support? Is it this repo, or https://github.com/microsoft/CsWinRT, or https://github.com/microsoft/WindowsAppSDK .

**Comment by bogdan-patraucean** [comment]
@nlogozzo at the time, InfoBadge is not supported, not even in preview 3 :( I'm also needing this.

**Comment by nlogozzo** [comment]
I've long switched to GNOME and GTK for application development. Windows doesn't attract me anymore

**Comment by nlogozzo** [comment]
@bogdan-patraucean I've long switched to GNOME and GTK for application development. Windows doesn't attract me anymore
