### ISSUE TITLE
Question: When will InfoBadge be available in WinUI3? 

### ISSUE THREAD

**Issue by stefansjfw** [microsoft/microsoft-ui-xaml#7001]
Hi all, we're using WinAppSdk 1.0.3 in PowerToys until recently (https://github.com/microsoft/PowerToys/pull/17797) and during migration we saw that InfoBadge component is not available yet. Is it planned to be added anytime soon?

Thanks!

**Comment by ojhad** [comment]
We are currently working on it; however we don't have an ETA yet.

**Comment by agneszitte-nventive** [comment]
> We are currently working on it; however we don't have an ETA yet.

@ojhad do you have an item that we can follow in order to get updated on when InfoBadge will be available in WinUI3, please?
Thanks in advance for your answer!
