### ISSUE TITLE
Drag-and-drop crashes the app (unrecoverable)

### ISSUE THREAD

**Issue by artkat** [microsoft/microsoft-ui-xaml#7007]
### Describe the bug

Drag-and-drop will crash the application. Sometimes at the first drag-drop operation, other times after 50 drag-drop operations. But eventually, it will crash.

sample code: https://github.com/artkat/WinUI_DnDCrash/tree/main

### Steps to reproduce the bug

Perform drag-drop operations between source and target.

### Expected behavior

No crash.

### Screenshots

![image](https://user-images.githubusercontent.com/3071447/164409370-8415f358-6f03-4528-adbc-e76d76116c2e.png)

![image](https://user-images.githubusercontent.com/3071447/164407969-3d83a80a-4f96-4bf4-a560-73d6657dee91.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Issues persists in: WindowsAppSDK 1.0.2, 1.0.3, 1.1.0-preview2

**Comment by wbokkers** [comment]
With WinAppSDK 1.1.1, I have a crash dump of a similar situation. How can I send this, @bpulliam?
Attached you find relevant stack traces of the stowed exception:
[Xelion-drag-drop-inside-app-WinAppSDK111.txt](https://github.com/microsoft/microsoft-ui-xaml/files/8917603/Xelion-drag-drop-inside-app-WinAppSDK111.txt)
.

**Comment by Scottj1s** [comment]
fix is now available in Windows App SDK 1.2 Preview 1
