### ISSUE TITLE
Drag-and-Drop target position is at wrong place.

### ISSUE THREAD

**Issue by artkat** [microsoft/microsoft-ui-xaml#7008]
### Describe the bug

When using display-scaling (other than 100%), the drag-drop target seems to be at another position than the actual target control.

Demo application code: https://github.com/artkat/WinUI_DnDCrash

### Steps to reproduce the bug

Drag item to drop area. 

### Expected behavior

Accept drop within the allocated drop area.

### Screenshots

![image](https://user-images.githubusercontent.com/3071447/164414649-b81b7de7-340b-4c74-aa4b-f52c4b803698.png)

![image](https://user-images.githubusercontent.com/3071447/164414928-f44747fb-6061-4755-8273-1fcfbcfcf4c6.png)

![image](https://user-images.githubusercontent.com/3071447/164415118-e09ec166-8a9e-4489-b354-d2fbe34e0b3f.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

So far, only happens with WinAppSDK 1.1.0-preview2

**Comment by michael-hawker** [comment]
Is this maybe also related to #5520?

**Comment by codendone** [comment]
Not the same as 5520. This bug is a regression in 1.1. [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/39188084)

**Comment by gabbybilka** [comment]
Fixed in 1.1.0, thanks for reporting.
