### ISSUE TITLE
Question: How to change the caption button foreground based on themes(light/dark) [WinUI 3 WinAppSDK 1.1p2]

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#7009]
The [documentation](https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=winui3#color-and-transparency-in-caption-buttons) mentioned that we can customise the foreground of the caption buttons by defining resources in app.xaml. 
This neatly sets the colors but these colors are not responsive to the change in the theme.
```xaml
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
            <!-- Other merged dictionaries here -->
        </ResourceDictionary.MergedDictionaries>
        <!-- Other app resources here -->
        <SolidColorBrush x:Key="WindowCaptionBackground">Green</SolidColorBrush>
        <SolidColorBrush x:Key="WindowCaptionBackgroundDisabled">LightGreen</SolidColorBrush>
        <SolidColorBrush x:Key="WindowCaptionForeground">Red</SolidColorBrush>
        <SolidColorBrush x:Key="WindowCaptionForegroundDisabled">Pink</SolidColorBrush>
    </ResourceDictionary>
</Application.Resources>
```
I have tried defining these resources in the Dark and Light section of the dictionary, however I could not make it work. Is it that the caption buttons are ignoring these changes? or I am doing something incorrect. My App is based on WinAppSDK 1.1 preview 2.

```xaml
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" /><ResourceDictionary>
                    <ResourceDictionary.ThemeDictionaries>
                        <ResourceDictionary x:Key="Default">
                            <Color x:Key="CaptionColor">#FFFFFF</Color>
                            <Color x:Key="CaptionColorDisabled" >#5DFFFFFF</Color>
                        </ResourceDictionary>
                        <ResourceDictionary x:Key="Light">
                            <Color x:Key="CaptionColor">#E4000000</Color>
                            <Color x:Key="CaptionColorDisabled" >#5C000000</Color>
                        </ResourceDictionary>
                        <ResourceDictionary x:Key="Dark">
                            <Color x:Key="CaptionColor">#FFFFFF</Color>
                            <Color x:Key="CaptionColorDisabled" >#5DFFFFFF</Color>
                        </ResourceDictionary>
                        <ResourceDictionary x:Key="HighContrast">
                            <Color x:Key="CaptionColor">#E4000000</Color>
                            <Color x:Key="CaptionColorDisabled" >#5C000000</Color>
                        </ResourceDictionary>
                    </ResourceDictionary.ThemeDictionaries>
                    <SolidColorBrush x:Key="WindowCaptionForeground" Color="{ThemeResource CaptionColor}"/>
                    <SolidColorBrush x:Key="WindowCaptionForegroundDisabled" Color="{ThemeResource CaptionColorDisabled}" />
                    <SolidColorBrush x:Key="WindowCaptionBackground" Color="Transparent"/>
                    <SolidColorBrush x:Key="WindowCaptionBackgroundDisabled" Color="Transparent" />
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

**Comment by ghost1372** [comment]
@harvinders i have this issue too, i used c# code for doing this. you can find my codes in ThemeHelper class
https://github.com/ghost1372/SettingsUI/blob/57b2b8e147407974646cfa6294754877bfcc2398/src/SettingsUI/Tools/Helpers/ThemeHelper.cs#L83-L99

**Comment by harvinders** [comment]
@ghost1372 , Is this Win 11 specific? I am on Windows 10 and get TitleBar as null.

**Comment by ghost1372** [comment]
> @ghost1372 , Is this Win 11 specific? I am on Windows 10 and get TitleBar as null.

Titlebar customization is not available in win10 currently only available in win11

**Comment by harvinders** [comment]
Sorry @ghost1372, I did not get you, I can't follow how calling Initialise is going to ensure that Titlebar is not null.

I am talking about this line   https://github.com/ghost1372/SettingsUI/blob/57b2b8e147407974646cfa6294754877bfcc2398/src/SettingsUI/Tools/Helpers/ThemeHelper.cs#L86

I also noticed that on Windows 10, TitleBar property is not supported.

**Comment by ghost1372** [comment]
We get titlebar from `appWindow` and we get appwindow from `window`, so we need to call initialize method.

I didnt test it in win10 but it should work, also according to the wasdk release notes Titlebar customization is not supported in win10. but I think the color change should work

**Comment by ghost1372** [comment]
> Sorry @ghost1372, I did not get you, I can't follow how calling Initialise is going to ensure that Titlebar is not null.
> 
> I am talking about this line   https://github.com/ghost1372/SettingsUI/blob/57b2b8e147407974646cfa6294754877bfcc2398/src/SettingsUI/Tools/Helpers/ThemeHelper.cs#L86
> 
> I also noticed that on Windows 10, TitleBar property is not supported.

Clone settingsUI and run demo with vs2022 and  see if theme changing is working or not

**Comment by castorix** [comment]
> @ghost1372 , Is this Win 11 specific? I am on Windows 10 and get TitleBar as null.

On Windows 10, you use **ExtendsContentIntoTitleBar** + **SetTitleBar** (with a Manifest for >=Windows 8 compatibility) and you can customize about everything from _WindowChromeStyle_ in XAML 
Simple test  (Windows 10 21H1) :

![CustomTitleBar_Win10](https://user-images.githubusercontent.com/22345506/164975622-bab11663-57ff-45d8-8472-ec5e986a73a3.gif)

**Comment by l619534951** [comment]
if set 
```
appWindow.TitleBar.ExtendsContentIntoTitleBar = true;
```

        private void SetCapitionButtonColorForWin11()
        {
            var currentTheme = ((FrameworkElement)Content).ActualTheme;
            if (currentTheme == ElementTheme.Dark)
            {
                appWindow.TitleBar.ButtonForegroundColor = Colors.White;
                appWindow.TitleBar.ButtonInactiveForegroundColor = Colors.White;
            }
            else if (currentTheme == ElementTheme.Light)
            {
                appWindow.TitleBar.ButtonForegroundColor = Colors.Black;
                appWindow.TitleBar.ButtonInactiveForegroundColor = Colors.Black;
            } else
            {
                if (App.Current.RequestedTheme == ApplicationTheme.Dark)
                {
                    appWindow.TitleBar.ButtonForegroundColor = Colors.White;
                    appWindow.TitleBar.ButtonInactiveForegroundColor = Colors.White;
                } else
                {
                    appWindow.TitleBar.ButtonForegroundColor = Colors.Black;
                    appWindow.TitleBar.ButtonInactiveForegroundColor = Colors.Black;
                }
            }
        }

if set 
```
ExtendsContentIntoTitleBar = true;
SetTitleBar(AppTitleBar);
```

> this code is from winui3-gallery source code

        private void SetCapitionButtonColorForWin10()
        {
            var res = Microsoft.UI.Xaml.Application.Current.Resources;
            Action<Windows.UI.Color> SetTitleBarButtonForegroundColor = (Windows.UI.Color color) => { res["WindowCaptionForeground"] = color; };
            var currentTheme = ((FrameworkElement)Content).ActualTheme;
            if (currentTheme == ElementTheme.Dark)
            {
                SetTitleBarButtonForegroundColor(Colors.White);
            }
            else if (currentTheme == ElementTheme.Light)
            {
                SetTitleBarButtonForegroundColor(Colors.Black);
            }
            else
            {
                if (App.Current.RequestedTheme == ApplicationTheme.Dark)
                {
                    SetTitleBarButtonForegroundColor(Colors.White);
                }
                else
                {
                    SetTitleBarButtonForegroundColor(Colors.Black);
                }
            }
            TriggerTitleBarRepaint();
        }

        private void TriggerTitleBarRepaint()
        {
            if (PInvoke.GetActiveWindow() == App.Hwnd)
            {
                PInvoke.SendMessage((HWND)App.Hwnd,PInvoke.WM_ACTIVATE, PInvoke.WA_INACTIVE, IntPtr.Zero);
                PInvoke.SendMessage((HWND)App.Hwnd,PInvoke.WM_ACTIVATE, PInvoke.WA_ACTIVE, IntPtr.Zero);
            } else
            {
                PInvoke.SendMessage((HWND)App.Hwnd, PInvoke.WM_ACTIVATE, PInvoke.WA_ACTIVE, IntPtr.Zero);
                PInvoke.SendMessage((HWND)App.Hwnd, PInvoke.WM_ACTIVATE, PInvoke.WA_INACTIVE, IntPtr.Zero);
            }
        }
