### ISSUE TITLE
Elusive Issue with TextBox being Temporarily Uneditable

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#702]
**Describe the bug**
Sometimes, clicking into a `TextBox` to edit results in being unable to type/change anything into it. Clicking out of the `TextBox` and back allows editing again. Paste seems to work, but can't edit text or add to text. It happens regardless of `IsReadOnly` attribute set to `False` or omitted.

**Steps to reproduce the bug**

It's very hard to reproduce.

1. Click on a `TextBox`
2. Type any text

**Actual behavior**
Once in a while, the text in the `TextBox` can't be edited. It's very hard to reproduce.

**Expected behavior**
`TextBox` should be editable 100% of the time if `IsReadOnly="False"` 

**Version Info**
Existed even prior to WinUI NuGet existing

NuGet package version: 
2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18362)                   | Yes   |
| October 2018 Update (17763)   | Yes     |
| April 2018 Update (17134)        | Yes      |
| Fall Creators Update (16299)     | Yes   |
| Creators Update (15063)           |     |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I've seen this same issue on `TextBox` on other UWP apps like WorkingHours

**Comment by chrisglein** [comment]
Without a crisp repro this will be hard to act on. If there's more detail (which apps, which specific textboxes, whether you have to move between multiple textboxes, etc.) that will help. Or capture a video. As is I've tried to replicate this and been unable to.
