### ISSUE TITLE
Bug title

### ISSUE THREAD

**Issue by Cody-Cooper** [microsoft/microsoft-ui-xaml#7020]
### Describe the bug

Error in event viewer:

```
Faulting application name: SystemSettings.exe, version: 10.0.22000.593, time stamp: 0x27a6d211
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22000.613, time stamp: 0x7aaa0c48
Exception code: 0xc000027b
Fault offset: 0x0000000000834ac0
Faulting process id: 0x37a4
Faulting application start time: 0x01d85840db8967b2
Faulting application path: C:\Windows\ImmersiveControlPanel\SystemSettings.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: ee1f0a2a-3d94-4f81-b0f8-bb0a9ea7ae77
Faulting package full name: windows.immersivecontrolpanel_10.0.6.1000_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: microsoft.windows.immersivecontrolpanel
```

I'm unable to launch system settings and can only right click in task manager and most other system apps. Not sure how to test if the right clicking issue is related to this, but figured I'd throw it in there for good measure.

### Steps to reproduce the bug

Not sure how to reproduce this, all I do is try to open settings app.

### Expected behavior

Settings app to open up

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by asklar** [comment]
for issues with inbox apps, please file Feedback Hub items; this repo is for issues in usage/development of WinUI apps (not issues with inbox Windows apps).
