### ISSUE TITLE
Discussion: Make INavigationTransitionInfoPrivate interface public

### ISSUE THREAD

**Issue by ahmed605** [microsoft/microsoft-ui-xaml#7025]
Making the the (WUX's) private interface, `INavigationTransitionInfoPrivate`, public would allow developers to create custom `Page` transition animations without needing to recreate a custom version of the `Frame` control

I wrote about that interface and how to use it here in my blog: http://ahmed-walid.tk/2021/12/02/navigationtransitioninfo/

And here's a simple demo: 

https://user-images.githubusercontent.com/34550324/165122816-fe884695-be0a-4234-b658-3b3b5f3a4f6c.mp4

Thoughts?

**Comment by ahmed605** [comment]
I'm willing to write the docs of it on docs.microsoft.com if my proposal/suggestion got accepted 🙂

**Comment by asklar** [comment]
Thanks for the feedback @ahmed605 ! Unfortunately we don't currently have plans to do this. We may in the future consider doing this or something to enable the same scenario, as part of WinAppSDK.
