### ISSUE TITLE
App crashes when I try to capture session in graphics diagnostics

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml#7035]
### Describe the bug

When I launch graphics diagnostic in a .net 6 / WinUI app with Vortice (Dx11 in C#) the app crashes with the following error...

> Unhandled exception at 0x00007FFDFAC52082 (Microsoft.ui.xaml.dll) in DemoTests.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001C7009617B0, 0x0000000000000002).

### Steps to reproduce the bug

Start a graphics diagnostics session for a DirectX11 app.

### Expected behavior

I expect graphics diagnostics to work and capture the frame.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ojhad** [comment]
Would you be able to provide a min repro of this problem? Also can you provide a link to explain what Vortice is?
