### ISSUE TITLE
Hot reload doesn't work with WinUI 3

### ISSUE THREAD

**Issue by kostya9** [microsoft/microsoft-ui-xaml#7043]
### Describe the bug

C# hot reload doesn't work with the default WinUI 3 project

### Steps to reproduce the bug

1. Create new WinUI3 project
2. Run in Debug mode and (Packaged) configuratoion
3. Try to edit the button content assignment to other text
4. Click hot reload

Actual: Error message box with text "Hot Reload can't ..."

### Expected behavior

Hot reload is successful

### Screenshots

![image](https://user-images.githubusercontent.com/3115913/166160409-bda0d3cc-dee8-4698-9b38-ad7e0416abc5.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 2: 1.1.0-preview2

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Tried Visual Studio 2022 17.1, Visual Studio 2022 17.2 Preview 5.0
Tried .NET 6, .NET 7 preview
Tried Microsoft.WindowsAppSDK Versions 1.0.0, 1.0.3, 1.1.0-preview2

Cannot try with "Unpackaged" configuration since it throws "Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)" on startup (https://github.com/microsoft/microsoft-ui-xaml/issues/6377)

**Comment by castorix** [comment]
It works fine for me : WinUI 3, Windows App SDK 1.1.0-preview2, Windows 10 21H1.
Test Unpackaged  app :

![HotReload_Options](https://user-images.githubusercontent.com/22345506/166161535-1aa63d5c-52c1-43fa-a3c6-402a8a12a0ea.jpg)


![WinUI3_HotReload](https://user-images.githubusercontent.com/22345506/166161498-3b332421-05ab-440d-bdc2-d5ea85bee97e.gif)

**Comment by kmgallahan** [comment]
XAML hot reload is mostly reliable outside of bindings.

C# hot reload sometimes works, but you must do step 2 [here](https://docs.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022#update-running-code-with-hot-reload).

> Make sure that Enable native code debugging is disabled in the debugger settings or the debug launch profile.

**Comment by marb2000** [comment]
Actually, XAML Hot Reload doesn't work with succinct RowDefinition:  <Grid RowDefinitions="Auto, Auto, *, Auto">

**Comment by heartacker** [comment]
I have the same issue. 
And I had try to using unpack launch config ,but I face the error https://github.com/microsoft/microsoft-ui-xaml/issues/6377#issuecomment-1213029097

**Comment by jpgarza93** [comment]
> Windows App SDK 1.1.0-preview2,

This did it for me.

> Actually, XAML Hot Reload doesn't work with succinct RowDefinition:
> 
> ```
> <Grid RowDefinitions="Auto, Auto, *, Auto">
> ```

this did it for me, wow

**Comment by lukasf** [comment]
It seems to be a problem in WinUI 3: https://github.com/microsoft/microsoft-ui-xaml/issues/673

**Comment by AMArostegui** [comment]
In my case, XAML hot reload only works when running a x86 application, not for x64 or Any Cpu configurations

**Comment by manusoft** [comment]
> Actually, XAML Hot Reload doesn't work with succinct RowDefinition:
> 
> ```
> <Grid RowDefinitions="Auto, Auto, *, Auto">
> ```

Remove RowDefinitions it works.. great!

**Comment by Reza-Noei** [comment]
Thanks @marb2000  it worked for me too ! 

But it's a bug actually, Any plan to resolve it ?
Because it saves my time and reduces a lots of spaces in the code.

**Comment by evelynwu-msft** [comment]
Original issue is solved (https://github.com/microsoft/microsoft-ui-xaml/issues/7043#issuecomment-1114358797), known limitation in C# hot reload, unrelated to WinUI 3. Subsequent comments are duplicate reports of #5944.
