### ISSUE TITLE
Question: Can we expect WinAppSDK 1.1 to bring TabView Visuals in sync with Figma design?

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#7045]
It seems there are many improvements done to TabView in WinUI 2.X but these are not showing up in WinAppSDK yet, some notable once is listed below. Could the team update us when they plan to bring these fixes to WinAppSDK?

1. TabView FooterStrip lacks bottom border (#5981) 
2. TabViewItem still has shadow (#6822)

**Comment by ojhad** [comment]
Not in 1.1 but it will be in a future release
