### ISSUE TITLE
`ThemeResource` doesn't work if used for an element inside `SwipeItems`

### ISSUE THREAD

**Issue by roxk** [microsoft/microsoft-ui-xaml#7047]
### Describe the bug

`ThemeResource` is not evaluated again when theme is changed when the element is inside `SwipeItems`.

### Steps to reproduce the bug

1. Create a blank C# app
2. Paste the following in `MainPage.xaml`
```
<Page <!-- Omitted -->>
    <Page.Resources>
        <DependencyObjectCollection x:Key="collection">
            <SwipeItem x:Name="textBlock2" Foreground="{ThemeResource TextFillColorPrimaryBrush}"/>
        </DependencyObjectCollection>
        <!-- Uncomment this and comment the above to reproduce the issue -->
        <!--<muxc:SwipeItems x:Key="collection">
            <muxc:SwipeItem x:Name="textBlock2" Foreground="{ThemeResource TextFillColorPrimaryBrush}"/>
        </muxc:SwipeItems>-->
    </Page.Resources>
    <StackPanel>
        <Button Content="Reset" Click="OnReset"/>
        <Button Content="Apply Color" Click="OnApplyColor"/>
        <TextBlock x:Name="textBlock1" Foreground="Red" Text="Hello world"/>
    </StackPanel>
</Page>
```
3. Add the following to `MainPage.xaml.cs`
```
private void OnApplyColor(object sender, RoutedEventArgs e)
{
    textBlock1.Foreground = textBlock2.Foreground;
}
private void OnReset(object sender, RoutedEventArgs e)
{
    textBlock1.Foreground = new SolidColorBrush(Colors.Red);
}
```
4. Run the app. Click apply color. Observe text color is changed to current theme's foreground
5. Change theme. Click reset then apply color again. Observe text color is changed to current theme's foreground
6. Close the app and comment/uncomment portion of xaml as described. Essentially, Switch the collection type from `DependencyObjectCollection` to `SwipeItems`.
7. Repeat (4)~(5). Observe after changing theme text color isn't changed to current but last theme's foreground. IOW `ThemeResource` isn't working

### Expected behavior

`ThemeResource` work.

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (22610.1)

### Additional context

1. SDK is 22000
2. As noted in the comment, only
- `DependencyObjectCollection` work correctly with list element with `ThemeResource` ✅
- `SwipeItems` didn't work ❌
- I tried changing `SwipeItems` to implement `IObservableVector` (need to modify custom build task) and it didn't work either ❌
- Tried to implement a custom collection, didn't work either ❌
3. This bug affects `SwipeControl`, obviously. I encountered this issue when trying to make a swipe item always use the same text color even with `RevealMode::Execute`.
4. Minimal repro: https://github.com/roxk/ThemeResourceForDoInsideCollectionBug

### Workaround
Do not declare `SwipeItem` inline in `SwipeItems`. Declare `SwipeItem` separately and add the item to `SwipeItems` in code behind.

**Comment by michael-hawker** [comment]
It looks like `SwipeItems` is inheriting from `DependencyObject` here:

https://github.com/microsoft/microsoft-ui-xaml/blob/77111484445727c7e29a9997344485cdad031fbf/dev/SwipeControl/SwipeControl.idl#L29

However, it should probably be instead inheriting from `DependencyObjectCollection`, looks like the wrong base class was used. This is going to interfere with how the xaml engine can walk the Visual Tree to hook up resources and bindings and such properly. We've had to deal with this in the Toolkit for our `AnimationSet` class and such in the past.

Related to #931 as well, as since DependencyObjectCollection isn't generic, it does make type safety harder.

**Comment by roxk** [comment]
Note that no xaml collection type (e.g. [BlockCollection](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.documents.blockcollection?view=winrt-22000)) inherits from `DependencyObjectCollection`. WUX's [SwipeItems](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swipeitems?view=winrt-22000) also didn't work and is inheriting from `DependenbyObject` as well. In fact, if you look into the [doc of DOC](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.DependencyObjectCollection?view=winrt-22000), there is 0 inherited classes.

If this is intended behavior that all collection type must inherit `DOC`, all of WUX and MUX's collection types have this bug. _And_ the doc needs to be updated to reflect this requirement as this requirement is no where to be seen before.
