### ISSUE TITLE
(Microsoft)Windows::UI::Xaml::Controls::TreeView - Memory Leak

### ISSUE THREAD

**Issue by luishdemetrio** [microsoft/microsoft-ui-xaml#7049]
### Describe the bug

Hi, we noticed that the TreeView for UWP/WinUI3 is presenting a memory leak when the ItemsSource is updated.

It seams that memory is being allocated (**Microsoft_UI_Xaml!XcpAllocation::OSMemoryAllocateFailFast**) after the **ItemsSource** is updated (**Microsoft_UI_Xaml_Controls!TreeViewNode::OnItemsSourceChanged**), but the  memory is not being released. The **Microsoft_UI_Xaml_Controls!TreeViewNodeVector::Clear+86** is not deallocating the memory allocated via **malloc_base:**

Follows the code that I used:

MainWindow.xaml.cpp

namespace winrt::App4::implementation
{
    MainWindow::MainWindow()
    {
        InitializeComponent();

        m_treeViewItems = winrt::single_threaded_observable_vector<int>();

        myTreeView().ItemsSource(m_treeViewItems);
    }

    void MainWindow::Reset(int max)
    {
        for (int i = 0; i < max; i++)
        {
            m_treeViewItems.Clear();

            for (int i = 0; i < 20; i++)
            {
                m_treeViewItems.Append(i);
            }
        }
    }

    Windows::Foundation::Collections::IObservableVector<int> MainWindow::TreeViewItems()
    {
        return m_treeViewItems;
    }    
}

void winrt::App4::implementation::MainWindow::Button_Click(winrt::Windows::Foundation::IInspectable const& sender, winrt::Microsoft::UI::Xaml::RoutedEventArgs const& e)
{
    Reset(20);
}

void winrt::App4::implementation::MainWindow::Button_Click_1(winrt::Windows::Foundation::IInspectable const& sender, winrt::Microsoft::UI::Xaml::RoutedEventArgs const& e)
{
    Reset(200);
}

MainWindow.xaml.h

namespace winrt::App4::implementation
{
    struct MainWindow : MainWindowT<MainWindow>
    {
        MainWindow();

        Windows::Foundation::Collections::IObservableVector<int> TreeViewItems();

        void Reset(int max);

    private:
        Windows::Foundation::Collections::IObservableVector<int> m_treeViewItems;

    public:
        void Button_Click(winrt::Windows::Foundation::IInspectable const& sender, winrt::Microsoft::UI::Xaml::RoutedEventArgs const& e);
        void Button_Click_1(winrt::Windows::Foundation::IInspectable const& sender, winrt::Microsoft::UI::Xaml::RoutedEventArgs const& e);
    };
}

namespace winrt::App4::factory_implementation
{
    struct MainWindow : MainWindowT<MainWindow, implementation::MainWindow>
    {
    };
}

MainWindow.xaml

 <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="119*"/>
            <RowDefinition Height="881*"/>
        </Grid.RowDefinitions>

        <StackPanel Grid.Row="0" Margin="10" Orientation="Horizontal">

            <Button Content="Reset" Grid.Row="0" Margin="10" Click="Button_Click" />

            <Button Content="Reset 200" Grid.Row="0" Margin="10" Click="Button_Click_1" />
        </StackPanel>

        <TreeView x:Name="myTreeView" Grid.Row="1" Margin="10"/>
    </Grid>

### Steps to reproduce the bug

1. Run the app
2. Click on the Reset 200 a few time (3, 4 times)
3. Observe memory increasing

### Expected behavior

Memory will increase. 

### Screenshots

![image](https://user-images.githubusercontent.com/49683427/166325047-a151c74e-0754-4c13-91de-77e2f35dff2c.png)

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by michael-hawker** [comment]
Note that `TreeView` in UWP is the OS TreeView which is probably more out-of-date than including WinUI 2.x and using the `muxc:TreeView`. Though considering this is also occurring in WinUI 3 means that'll be exercising the latest code as well in that scenario. So, this would indicate a long-standing issue with TreeView or something it depends on in the platform that has been there for a long time.
