### ISSUE TITLE
Bug: RadioButtons clips items to size of first item

### ISSUE THREAD

**Issue by chrisglein** [microsoft/microsoft-ui-xaml#705]
**Describe the bug**
RadioButtons is built on ListView. And this appears to be doing a Grid-like thing where it doesn’t know how big each item should be so it measures the first item and then uses that as the grid size for all the following items. A classic non-uniform layout problem.

**Steps to reproduce the bug**
```
    <controls:RadioButtons ItemsSource="{x:Bind Items}">
        <controls:RadioButtons.ItemTemplate>
            <DataTemplate>
                <TextBlock Text="{Binding}"/>
            </DataTemplate>
        </controls:RadioButtons.ItemTemplate>
    </controls:RadioButtons>
```
```
    public sealed partial class MainPage : Page
    {
        public List<string> Items = new List<string>(new string[] { "Light theme", "Dark theme", "Use my Windows Thingy" });
``` 

**Expected behavior**
Text is not clipped

**Screenshots**
![image](https://user-images.githubusercontent.com/26607885/57733221-de923e00-7653-11e9-9722-d2a4d855da1c.png)
(Note third item is clipped)

**Additional context**
The problem is the going to be in the layout used here:
![image](https://user-images.githubusercontent.com/26607885/57733228-e2be5b80-7653-11e9-9e0e-8cb1d19864a5.png)

It doesn’t appear that RadioButtons allows you to set ListView’s ItemsPanel, which could provide a workaround. And RadioButtons isn’t using a layout that handles variable sized items.
A hacky workaround would be to put a MinWidth on your TextBlock so that the first item uses up more space. But the real fix should be to change the layout used by RadioButtons.

**Comment by Felix-Dev** [comment]
Any updates on this? Experiencing the exact same problem.

**Comment by jevansaks** [comment]
@stephenlpeters is picking up RadioButtons and can look into this as part of that work.
