### ISSUE TITLE
Access Violation and app crash when trying to debug Application.Current

### ISSUE THREAD

**Issue by mattleibow** [microsoft/microsoft-ui-xaml#7050]
### Describe the bug

I noticed that my app was crashing when trying to read the resources from a background thread:

```cs
var res = Application.Current?.Resources
```

I don't actually want to start using things, but rather I wanted to get the dispatcher queue and then enqueue a delegate to update the dictionary. But, it appears just reading this crashes the app and also adding `Application.Current` in the IDE's debug intermediate window also throws.

### Steps to reproduce the bug

On a background thread:

```cs
var res = Application.Current?.Resources
```

### Expected behavior

No crash and the resource dictionary is readable.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

**Comment by MikeHillberg** [comment]
In the meantime, the best practice is to store away a copy of the DispatcherQueue somewhere in an app global.

**Comment by bpulliam** [comment]
Is this still an issue? Are you able to access the resources now (though Application.Current or some other method).
Thanks!

**Comment by mattleibow** [comment]
My issue was with accessing the resources from a different window on a different thread. Now the multi-thread window support has been removed.
