### ISSUE TITLE
BitmapImage.SetSourceAsync() unspecified error

### ISSUE THREAD

**Issue by markolbert** [microsoft/microsoft-ui-xaml#7052]
### Describe the bug

Calling `SetSourceAsync()` on a newly created `BitmapImage` sometimes results in an unspecified WinRT exception being thrown. The exception is not caught when the call is within a try/catch block and causes the desktop app to crash.

The exception message is "Error HRESULT E_FAIL has been returned from a call to a COM component."

I am not sure what is going wrong inside the `SetSourceAsync()` call. FWIW, I can save the response stream (which is an image tile downloaded from OpenStreetMaps) to a file which behaves normally as a PNG file. So the downloaded stream would appear to be a valid image, which somehow `SetSourceAsync()` is gacking on.

### Steps to reproduce the bug

```
        try
        {
            using var responseStream = await response.Content.ReadAsInputStreamAsync();

            var randomAccessStream = new InMemoryRandomAccessStream();
            await RandomAccessStream.CopyAsync( responseStream, randomAccessStream );
            randomAccessStream.Seek( 0 );

            var retVal = new Image();

            var source = new BitmapImage();

            // this is the line that throws the exception occasionally
            await source.SetSourceAsync( randomAccessStream );

            retVal.Source = source;
            AttachedProperties.SetTileCoordinates( retVal, coordinates );

            return new AsyncWebResult<Image, HttpStatusCode>( retVal, response.StatusCode );
        }
        catch ( Exception ex )
        {
            Logger?.Error<string>( "Could not set bitmap image, message was '{0}'", ex.Message );

            return new AsyncWebResult<Image, HttpStatusCode>( null,
                                                              response.StatusCode,
                                                              response.RequestMessage.RequestUri.AbsoluteUri,
                                                              $"Could not set bitmap image, message was '{ex.Message}'" );
        }
```

### Expected behavior

There should be no unhandled exception.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by markolbert** [comment]
I wrote one of the streams which throws the exception to a PNG file. Here it is, attached, in case that helps diagnose why the exception is being thrown
![tile](https://user-images.githubusercontent.com/9095610/166521183-85bb13b3-7775-40c5-a4ee-763ca6676899.png)
.

**Comment by codendone** [comment]
That code works fine for me with that PNG when I load that PNG from app assets. Is the full stream in response.Content complete by the time the RandomAccessStream.CopyAsync() call happens?

**Comment by markolbert** [comment]
Oops! I frequently forget await doesn’t mean “wait till complete”, so that could well be the problem. I’ll check in the morning. Thanx for the quick reply.

**Comment by markolbert** [comment]
Hi @codendone, I realize github isn't really the right place to seek tech support...but I am totally confused and stumped on how to use continuations with IAsyncOperation<T>. And it seems like that's what I need to do in order to ensure subsequent async operations don't occur until the precedent operation is complete.

Do you have any references or examples you can point me to?

**Comment by kmgallahan** [comment]
@markolbert Why not just use [copyandcloseasync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.randomaccessstream.copyandcloseasync?view=winrt-22000) instead since it is designed to do what you want?

> The CopyAndCloseAsync method is similar to [CopyAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.randomaccessstream.copyasync?view=winrt-22000#windows-storage-streams-randomaccessstream-copyasync(windows-storage-streams-iinputstream-windows-storage-streams-ioutputstream)) but also calls and waits for [FlushAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.ioutputstream.flushasync?view=winrt-22000#windows-storage-streams-ioutputstream-flushasync) and [Close](https://docs.microsoft.com/en-us/windows/desktop/api/windows.foundation/nf-windows-foundation-iclosable-close) on the output stream before its asynchronous operation completes.

**Comment by markolbert** [comment]
I tried that before posting here. Same problem.
