### ISSUE TITLE
Question: WinUI Hybrid Mode

### ISSUE THREAD

**Issue by Pinox** [microsoft/microsoft-ui-xaml#7053]
Hi Guys,

Just a question regarding WinUI 3.0.  In MAUI it's possible to use something that's called Blazor Hybrid -> essentially the mix of two technologies to give you a way of building UIs that spans MAUI XAML + Web UI.

![image](https://user-images.githubusercontent.com/5297255/166556252-c849c29d-f274-4b84-94c0-9627f9c6fd53.png)

I really like this approach especially where I want to reuse navigation menu's that's build in Blazor across all my platform specific apps but have Native UI to compliment the Web UI in Android + iOS.

On the windows side I would prefer to stick to native winui 3.0 apps and not use the MAUI / windows implementation. 

The problem is I'm not sure if this dual hybrid implementation is possible for WinUI 3.   My navigations menus (like a hamburger menu) is all Blazor and when the user clicks on menu item it can then display a native WinUI 3 page.

Are there any plans for something like this in native WinUI 3 as it will be really useful when creating cross platform apps where I can reuse all the existing code from MAUI ( Blazor Code) or Blazor WASM in a native app ?

I essentially then have the same integration of the 2 UI tech in the same app namely using Blazor for menu navigation and either Blazor or native WinUI 3 for page content.

**Comment by ojhad** [comment]
@fabiant3 do you know the answer to this question.
@Pinox have you tried asking on the MAUI repo? https://github.com/dotnet/maui

**Comment by Pinox** [comment]
@ojhad , I can but this is a WinUI 3.0 question and not related to MAUI as I'm looking for similiar MAUI functionality in native WinUI3 apps.

**Comment by Pinox** [comment]
I opened a feature request on the maui repo regarding the BlazorWebView that essentially enables the Blazor Hybrid approach within native apps.

Would appreciate if this can also be prioritized within the WinUI repo.  Makes it very expensive for developers to write code in Blazor and then you can't tightly integrate it within a native WinUI 3 app.

Because of the lack of BlazorWebView support in WinUI 3  there is a clear disadvantage developing in WinUI versus Winforms or WPF at the moment.
