### ISSUE TITLE
Segue Fluent Icons distribution

### ISSUE THREAD

**Issue by tholp** [microsoft/microsoft-ui-xaml#7055]
The Segoe Fluent Icons font is not available on Windows 10, but it can be downloaded.  But the license in the download prohibits distribution.  Does that mean that end users of a program that uses these icons will have to download and install the font themselves?

**Comment by ojhad** [comment]
@chigy do you know the answer to this one?

**Comment by chigy** [comment]
@tholp ,
The Segoe Fluent icons download is for developers and designers building applications for Windows 11. It can’t be distributed to Windows 10 or anywhere else.

There is an open source Fluent system icons that is available for any platform, though not sure f that works for your needs.
[https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ffluentui-system-icons&data=05%7C01%7Cchigy%40microsoft.com%7C16e841c5aee9449b392a08da2e2e0706%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637873072464667552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F%2FUFvcV6l85qXKx541sUDPoiliaCjDH2zCNRjTEVwQ0%3D&reserved=0](url)

**Comment by tholp** [comment]
Wonder how many that build apps for **_only_** for Windows 11?  I certainly can't allow myself to such luxury.

But thank you for the answer; I am aware of the mentioned icon set (I think; because I can't make the link work), it is very limited and while they are quite nice and useful they leave big gaps.

**Comment by chigy** [comment]
@tholp , I updated the link. I hope that link works for you.

While app developers do build apps for OS version outside of Windows 11, Windows 11 brings the new design language. Our recommendation is for apps that runs in an older OS to continue using the existing icons. Since we didn't update the character code, they should fallback properly.

**Comment by Fabi** [comment]
> @tholp , I updated the link. I hope that link works for you.
> 
> While app developers do build apps for OS version outside of Windows 11, Windows 11 brings the new design language. Our recommendation is for apps that runs in an older OS to continue using the existing icons. Since we didn't update the character code, they should fallback properly.

That is not acceptable and really (sorry) stupid actually.

**Comment by chigy** [comment]
> That is not acceptable and really (sorry) stupid actually. 
Please elaborate?

>But as a workaround just let your app download it automatically. Does it's job for now and does not violate the license
I do believe that is not part of the license and was the source of original question?

**Comment by torgeros** [comment]
Did I get that right? Wwe are not allowed to develop apps in WinUI 3 using `Segoe Fluent Icons` and then distribute that app to windows 10 devices? In what use cases is it applicable to download the font to Windows 10 devices manually? Or is it just not allowed to use the font but we have to use the [fluentui-system-icons](https://github.com/microsoft/fluentui-system-icons) directly instead?

**Comment by Fabi** [comment]
> Did I get that right? Wwe are not allowed to develop apps in WinUI 3 using `Segoe Fluent Icons` and then distribute that app to windows 10 devices? In what use cases is it applicable to download the font to Windows 10 devices manually?
> 
> Or is it just not allowed to use the font but we have to use the [fluentui-system-icons](https://github.com/microsoft/fluentui-system-icons) directly instead?
> 
> How about embedding the font in the app as a resource in the app?

you would need to let the app download the font. That's basically the only way to avoid manual downloads

**Comment by torgeros** [comment]
@Fabi okay but is it allowed by the license of the Segoe font(s)?

**Comment by Fabi** [comment]
> @Fabi okay but is it allowed by the license of the Segoe font(s)?

You are not allowed to bundle them. If manual downloads are allowed (thats the way to go with that license), nobody can disallow automatic downloads with that license. If they do or try it's and invalid term of the license that's for sure.

So tldr: That is allowed to let a published app download the font

**Comment by m0lDaViA** [comment]
> > [@Fabi](https://github.com/Fabi) okay but is it allowed by the license of the Segoe font(s)?
> 
> You are not allowed to bundle them. If manual downloads are allowed (thats the way to go with that license), nobody can disallow automatic downloads with that license. If they do or try it's and invalid term of the license that's for sure.
> 
> So tldr: That is allowed to let a published app download the font

Why do you think this is allowed? if it's not allowed for end users to use, then you're not allowed to automatically download it via your application.

**Comment by m0lDaViA** [comment]
> > > > [@Fabi](https://github.com/Fabi) okay but is it allowed by the license of the Segoe font(s)?
> > > 
> > > 
> > > You are not allowed to bundle them. If manual downloads are allowed (thats the way to go with that license), nobody can disallow automatic downloads with that license. If they do or try it's and invalid term of the license that's for sure.
> > > So tldr: That is allowed to let a published app download the font
> > 
> > 
> > Why do you think this is allowed? if it's not allowed for end users to use, then you're not allowed to automatically download it via your application.
> 
> You are

Why do you think so?
