### ISSUE TITLE
App will be Crash with an InfoBar and Publishing as Single File Option

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#7063]
### Describe the bug

If we have an InfoBar in MainWindow and publish it as a Single File (PublishSingleFile = true) App will not run and will crash.

i tested with visual studio debugger and i get 

```
Exception thrown at 0x76C0F152 in App22.exe: Microsoft C++ exception: EEMessageException at memory location 0x0377EC8C.
Exception thrown at 0x76C0F152 (KernelBase.dll) in App22.exe: 0xE0434352 (parameters: 0x80131524, 0x00000000, 0x00000000, 0x00000000, 0x00AA0000).
Unhandled exception at 0x76C0F152 (KernelBase.dll) in App22.exe: 0xE0434352 (parameters: 0x80131524, 0x00000000, 0x00000000, 0x00000000, 0x00AA0000).

```

### Steps to reproduce the bug

1.Create a New WinUI 3 Project
2.Change To Unpackaged Project
None
3. Add InfoBar on MainWindow

```xml
<Window
    x:Class="App1.MainWindow">
    <StackPanel>
        <InfoBar
                        Title="Up To Date"
                        IsClosable="False"
                        IsOpen="True"
                        Severity="Success" />
    </StackPanel>
</Window>
```
4.Publish Project as Single File (PublishSingleFile = true)
5.Run Published App

### Expected behavior

App should run without any problems

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Tested with WASDK 1.1.0-preview1, preview2 and preview 3
i reported this issue in wasdk repo but no one tracking this issue.
microsoft/microsoft-ui-xaml#7143

**Comment by ojhad** [comment]
@RealTommyKlein Any ideas on what could be going on here?

**Comment by beeradmoore** [comment]
@ghost1372 , any idea why this is closed? This is still an issue. Should we be focusing on any one specific issue of the duplicate/related issues instead?

**Comment by ghost1372** [comment]
@beeradmoore 
i reopened this issue here
https://github.com/microsoft/microsoft-ui-xaml/issues/7143

**Comment by beeradmoore** [comment]
Thanks. I have gone and subscribed to that one now.
