### ISSUE TITLE
Question: Title bar command area customization

### ISSUE THREAD

**Issue by Aladriel** [microsoft/microsoft-ui-xaml#7064]
Hi,

I have been using WinAppSdk in 1.0.0 version so far. To workaround titlebar issues I have created custom control with command buttons (minimize, maximize, close) that was set as title bar and it worked like a charm as it covered native command bar
It looked like that:
![image](https://user-images.githubusercontent.com/15796859/167084249-0320bed7-ab3f-47f4-9915-7ce12ae1ee19.png)

After upgrading WinAppSdk to 1.0.3 version where bugfixes for titlebar were implemeted, that custom title bar control no longer cover native command bar and it looks like this:
![image](https://user-images.githubusercontent.com/15796859/167084985-e026fc59-b61e-4cb0-a4f6-7c4b4c587b49.png)
You can see that it's darker as grey background of native command bar overlaps. 

Command buttons that were part of custom control are no longer clickable (hover also doesn't work) when SetTitleBar is used on that control.

On top of that this is not reversable. I went back to WinAppSdk 1.0.0 with all nuget cache clearing etc. and I can still see all those changes from 1.0.3 version. My colleague didn't even upgrade to 1.0.3, but run other app that was using that version and all those changes were imposed on our app.

So I have 3 questions based on that:
1. Is it possible to customize native command bar and if yes, how to do that? I would like to change color and size of command buttons to match it with my custom bar, as currently it look like this;
![image](https://user-images.githubusercontent.com/15796859/167088298-c353240a-f954-4dec-865b-133ec6a86107.png)

2. Is it possible to have some property for MainWindow class that would allow for titlebar to work like in 1.0.0 version?
3. Most important question: Why this change is not reversible? And why running another application with newer version can change behaviour of mine? (I guess that some common OS .xaml files were changed)

Best regards
Bartek

**Comment by castorix** [comment]
> 1 . Is it possible to customize native command bar and if yes, how to do that?

You can copy and update the style (in App.xaml) _<Style TargetType="ContentControl" x:Key="WindowChromeStyle">_
For example, I changed colors and some alignments) :




![CustomTitleBar_Win10](https://user-images.githubusercontent.com/22345506/167094170-ffb4de59-41cf-449d-87c5-7729e90cad1c.gif)

**Comment by Aladriel** [comment]
> > 1 . Is it possible to customize native command bar and if yes, how to do that?
> 
> You can copy and update the style (in App.xaml) _<Style TargetType="ContentControl" x:Key="WindowChromeStyle">_ and also resources like _WindowCaptionButtonBackground_, _WindowCaptionButtonBackgroundPointerOver_, _CloseButtonBackgroundPointerOver_, etc... For example, I changed colors
> 
> ```
>         <SolidColorBrush x:Key="WindowCaptionButtonBackground" Color="Green" Opacity="0.3"/>
>         <SolidColorBrush x:Key="WindowCaptionButtonBackgroundPointerOver" Color="Yellow" Opacity="0.8"/>
>         <SolidColorBrush x:Key="CloseButtonBackgroundPointerOver" Color="Magenta" Opacity="0.8"/>
> ```
> 
> and some alignments in the style :
> 
> ![CustomTitleBar_Win10](https://user-images.githubusercontent.com/22345506/167094170-ffb4de59-41cf-449d-87c5-7729e90cad1c.gif)

Thanks, that's right, that was my first approach when WinUI bug with not visible native caption buttons made me do custom control with buttons.

I still have problem with styling button stroke (path). How did you manage to override that? I'm able to set WindowCaptionButtonStrokePointerOver and this one works, however when I try to set WindowCaptionButtonStroke it does not change anything.

**Comment by castorix** [comment]
I just uploaded a basic test sample : [WinUI3_CustomCaption](https://github.com/castorix/WinUI3_CustomCaption)
where I updated a few values (with a Manifest on Windows 10 21 H1, for the layered window)
which seems to work fine on my OS
