### ISSUE TITLE
Can't build an app after switching to Visual Studio 2022

### ISSUE THREAD

**Issue by Hazest** [microsoft/microsoft-ui-xaml#7065]
### Describe the bug

After installing visual studio 2022 (previously 2019), the application stopped building using the msbuild command.

### Steps to reproduce the bug

msbuild commend: 
```msbuild XXX.sln /p:Platform=x64 /p:Configuration=\"XXX\" /nodeReuse:False /t:\"rebuild\" /p:AppxPackageDir=.\\XXX\\ /p:GenerateAppxPackageOnBuild=true /p:NoWarn=\"XXX\"```

Information about error:
```
"c:\XXX.sln" (rebuild target) (1) ->
"c:\XXX.csproj" (Rebuild target) (30) ->
(_GenerateAppxSymbolPackage target) -> 
  C:\XXX\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(341,5): error MSB6006: "mspdbcmf.exe" exited with code -1073740791. [c:\XXX.csproj]
```

### Expected behavior

Application will build correctly. 

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Additional context

We have a build server based on windows server 2019. We need to update visual studio to version 2022 because we need to start using .net 6. 

This is a **critical problem for us** because it stops our further work.

**Comment by Hazest** [comment]
It's worth adding that 5% of the builds are successful

**Comment by Hazest** [comment]
I found workaround for this problem. I added _/p:DebugSymbols=false /p:DebugType=None_ to build command.

**Comment by gugchil** [comment]
Disabling PDB files generation solves the issue. However, what is the cause of the issue? is Virtual machine memory not enough or what? The pipeline started failing after regular commit just out of the blue...

/p:DebugSymbols=false /p:DebugType=None

**Comment by LevYas** [comment]
I found a more elegant solution to this - disable symbol packaging by adding
```
<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
```
You can read more about my case and how I ended up with this solution: https://yastr.dev/posts/wap-references-dotnet/
