### ISSUE TITLE
Is there a reason why the DISABLE_XAML_GENERATED_MAIN does not work for x86 platforms?

### ISSUE THREAD

**Issue by andrewittorio** [microsoft/microsoft-ui-xaml#7068]
Hello, 

I have a WinUI3 Desktop application and I am working to make it single-instanced. 

I am following this article: https://blogs.windows.com/windowsdeveloper/2022/01/28/making-the-app-single-instanced-part-3/.

The mechanism works fine, but I Noticed that if I change the solution platform from x64 to x86, the static Main method in the Program class is not called and the single instance is not possible. Is there a reason for that? Where am I doing wrong?

Here the vs project : 

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MyApp</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|arm64'">
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|arm64'">
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.3" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.197" />
    <PackageReference Include="WinUIEx" Version="1.4.2" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!-- Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
       Tools extension to be activated for this project even if the Windows App SDK Nuget
       package has not yet been restored -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnablePreviewMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>

</Project>
```

Thank you. Best regards,

**Comment by andrewittorio** [comment]
Hi Mike,

Thank you for your answer. 

I was meaning that if I set a breakpoint on the first line of my Main method, the breakpoint is not fired. So as the app runs, I suppose that the auto generated code is called. 

I can also add that I did not copy the main from the auto generated code, but I created it manually as explained in the sample. 

Thank you,

**Comment by applefanbois** [comment]
I modified my WinUI3 project by adding the DISABLE_XAML_GENERATED_MAIN and the creating the Program.cs. Everything is firing normally, but while the UI is being created the execution eventually stop, never on the same spot. I trace with F10 step by step and eventually it won't go to the next line, the cpu is zero, the code still answer to resize window, but the app is not displaying anything. Never seen such a thing in my entire life. How is it possible that a main thread will simply not continue to the next instruction and never the same one without any errors.

**Comment by applefanbois** [comment]
I just want to say that the WinUI3 single-instance sample project has a huge problem that will make it useless for most people because everything useful wlh not work. Writable bitmap will never initialize with content and Webview2 will not start ever. The problematic lines of codes were right in the beginning.

static async Task Main(string[] args) //This will break everything using COM
static int Main(string[] args) //This is the solution to make everything work normally.

I don't know why making the main an async Task would break everything, but it does.

"await writeableBitmap.SetSourceAsync(filestream)"  would hang and never complete and
"await webView2.EnsureCoreWebView2Async();" would throw or fail

So the solution was to replace the Main function definition with "static int Main(string[] args)"
