### ISSUE TITLE
Proposal: Add the ability to lower the lower limit of cell height in the DataGrid

### ISSUE THREAD

**Issue by MisakiAkatsuki** [microsoft/microsoft-ui-xaml#7071]
# Proposal: Add the ability to lower the lower limit of cell height in the DataGrid

## Summary

I would like to use DataGrid to display simple numbers (or symbols) like in the image.
However, the cell height of the DataGrid in the current WinUI is more than twice the height of the Form, which significantly reduces the amount of information that can enter the first view.
I would like to lower the height of the cells.

![image](https://user-images.githubusercontent.com/3259637/167224546-c15e942e-0a4d-4957-89c9-67c4edda64e3.png)

## Rationale

* Useful for displaying chunks of data that don't make much sense in a single cell

**Comment by kmgallahan** [comment]
WinUI doesn't have a DataGrid. If you are using the Windows Community Toolkit DataGrid then this issue belongs there.

**Comment by MisakiAkatsuki** [comment]
Thank you.
I was using it here and misunderstood.
`xmlns:controls="using:CommunityToolkit.WinUI.UI.Controls"`
