### ISSUE TITLE
NEW XAML BINDING Extension

### ISSUE THREAD

**Issue by cesarchefinho** [microsoft/microsoft-ui-xaml#7073]
I made an Binding extension that upgrade xaml Binding to understand ComponentModel.DataAnnotations, Validator, Error Messages, Masking in ViewModel

I suggest to contribute it to Windows Communitytoolkit and in UNO community too

Please feel free to use, contribute, improve or adopt in oficial XAML Microsoft implementation

Thanks

https://github.com/cesarchefinho/MVVMBindingExtensions

**Comment by asklar** [comment]
Hi @cesarchefinho - it looks like you are referring to a C# library; I recommend you post this on the [Windows Community Toolkit repo](https://github.com/CommunityToolkit/WindowsCommunityToolkit), as this repo is for the WinUI framework (written in C++).
