### ISSUE TITLE
Elements in a GridView cannot cast a ThemeShadow

### ISSUE THREAD

**Issue by williamfigtree** [microsoft/microsoft-ui-xaml#7076]
### Describe the bug

Elements in a GridView do not produce a shadow effect when assigned a ThemeShadow and Z translation and a non-ancestor reciever element is defined. They should cast a shadow on the reciever element.

### Steps to reproduce the bug

1. Create a new WinUI3 app
2. Add the following to the MainWindow XAML and code behind

```
// XAML
<Grid>
    <Grid.Resources>
        <ThemeShadow x:Name="BackgroundShadow"/>
    </Grid.Resources>
    <Grid x:Name="BackgroundGrid" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" />
    <GridView>
        <Rectangle Height="100" Width="100" Fill="Turquoise" Shadow="{StaticResource BackgroundShadow}" Translation="0, 0, 32"/>
    </GridView>
</Grid>

// code behind
BackgroundShadow.Receivers.Add(BackgroundGrid);
```

3. Run the app and observe that no shadow is cast from the Rectangle onto BackgroundGrid
4. Stop the app and change the GridView to a Grid
5. Run the app and observe that a shadow is cast from the Rectangle onto BackgroundGrid

### Expected behavior

Elements within a GridView should cast a shadow on the defined reciever element.

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (1909): Build 18363

**Comment by roxk** [comment]
This is [by design](https://docs.microsoft.com/en-us/windows/apps/design/layout/depth-shadow#themeshadow-in-other-elements):
> Receivers cannot be an ancestor of the caster in the visual tree.

You might want to look into [the shadow API in community toolkit](https://twitter.com/XAMLLlama/status/1425636561148792834).

**Comment by williamfigtree** [comment]
@roxk As I noted above, the receiver in this example is not an ancestor of the caster in the visual tree.

**Comment by roxk** [comment]
> the receiver in this example is not an ancestor of the caster in the visual tree.

Their wording can be better, but in my own testing, what they meant seems to be that the elements have to be the same depth in the tree. So your rectangle inside a grid view doesn't have the same depth as the background (even though background grid isn't an ancestor of the rectangle).

**Comment by williamfigtree** [comment]
> what they meant seems to be that the elements have to be the same depth in the tree.

Interesting. That doesn't quite match up with my testing. Here's the example I was talking about where the `GridView` is changed to `Grid`. The shadow is working and the rectangle and background grid are at different depths in the visual tree. I hope the problem isn't to do with the depth of the elements, that would cause a lot of difficulty when constructing complex UIs.
![image](https://user-images.githubusercontent.com/92142629/167996906-4a3c2504-547b-4373-a3cc-00dca735cff5.png)
