### ISSUE TITLE
Build-Time Error When Adding a new Page to Application Project

### ISSUE THREAD

**Issue by one-and-only** [microsoft/microsoft-ui-xaml#7084]
### Describe the bug

When adding a new Blank Page (C++/WinRT) to a Windows App SDK Application, you get a build-time error, even when changing nothing about the page and not referencing it for any navigation, etc. The error is the following:
`WMC9999 Unable to cast object of type 'System.Xaml.XamlType' to type 'Microsoft.UI.Xaml.Markup.Compiler.DirectUI.DirectUIXamlType'.`

### Steps to reproduce the bug

1. Install all applicable tools for Windows App SDK (version 1.0.0 and 1.1.0-preview3 are the versions I encountered this issue on)
1. Using Visual Studio 2022, create a new Blank App, Packaged (WinUI3 in Desktop), uncheck Place solution and project in the same directory.
1. Build the default to make sure it works (it should build)
1. Add a new Blank Page (C++/WinRT) to the solution. changing the page contents is not necessary. The default page content should cause the build-time error.
1. Build the application project. It should fail with the following error:
WMC9999 Unable to cast object of type 'System.Xaml.XamlType' to type 'Microsoft.UI.Xaml.Markup.Compiler.DirectUI.DirectUIXamlType'.

### Expected behavior

Adding a new page shouldn't break the build process and consuming the page in the application should work as intended.

### Screenshots

![Build-Time Error](https://camo.githubusercontent.com/8eeb28623138d636d311d0412b42511694e153b279fec43fdfca0b1c6caae0b3/68747470733a2f2f696d6775722e636f6d2f32384d323356572e706e67)

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [x] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

I'm not sure how to tell if the app is Win32 or UWP, since I'm using C++/WinRT. Is it Win32? I have checked both, but I think I saw UWP somewhere along the line of app development.

**Comment by asklar** [comment]
You can't use the C++/WinRT item templates for blank page, those are for UWP XAML
Instead, use the Blank page item template from the winappsdk vsix (the one that says WinUI 3):

![image](https://user-images.githubusercontent.com/22989529/167789184-2c63b4d9-c19c-488c-8e05-b9bf48cf81a8.png)

Download the C++ extension here: https://docs.microsoft.com/windows/apps/windows-app-sdk/downloads

**Comment by one-and-only** [comment]
I have already downloaded that extension, but the WinUI 3 items are not shown in the `New Item` list. Do I have to install the C# version of the extension, too? I am only shown the C++/WinRT items.

**Comment by one-and-only** [comment]
**UPDATE:** WinUI Templates are only visible in VS2019 [and below, I assume]. VS2022 shows no such templates, which is the version of the project that I am working on. Is this a known issue?

**Comment by one-and-only** [comment]
It turns out I had somehow unchecked the `C++ App SDK Templates` option in Visual Studio Installer. The templates showed up and adding a new WinUI Window/Page resolved the issue. Thank you.
