### ISSUE TITLE
NavigationView hamburger button shows the Focus rectangle when using the mouse when resizing

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/microsoft-ui-xaml#7088]
### Describe the bug

Using the mouse, when resizing at smaller size, the big white rectangle will appear around the hamburger menu. It's affecting all apps using the NavigationView.

### Steps to reproduce the bug

1- Launch the sample app
2- Resize the app to a smaller size using the mouse

### Expected behavior

No focus rectangle

### Screenshots

https://user-images.githubusercontent.com/1608424/168124636-f88b683c-be76-417e-865f-41ab87475305.mp4

![167894573-58e68277-7e55-4d02-a02f-015ee67602a3](https://user-images.githubusercontent.com/1608424/168124638-a3c5fca4-77e9-4b47-933e-306188f561d1.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

It affects all apps using the NavigationView

**Comment by TRadigk** [comment]
I tried to reproduce this and found that at the first app start, I can reproduce the described issue - search lost focus, the hamburger menu bottom got the focus indicator.
On the second app start (without restarting my computer) and from then on "what's new" got the focus. The textbox (search) loses the focus.
