### ISSUE TITLE
Can't build WinUI 2 (MUXControlsTestApp from MUXControls.sln) in Visual Studio 2022

### ISSUE THREAD

**Issue by lyahdav** [microsoft/microsoft-ui-xaml#7097]
### Describe the bug

I can't build MUXControlsTestApp in Visual Studio 2022. When I open the solution it gives warnings:

> C:\Users\lyahdav\source\repos\microsoft-ui-xaml\dev\dll\Microsoft.UI.Xaml.vcxproj : warning  : The build tools for Visual Studio 2019 (v142) cannot be found. To build using the Visual Studio 2022 (v143) build tools, either click the Project menu or right-click the solution, and then select "Retarget Solution". Install Visual Studio 2019 (v142) to build using the Visual Studio 2019 (v142) build tools.
> 
> C:\Users\lyahdav\source\repos\microsoft-ui-xaml\test\TestAppCX\TestAppCX.vcxproj : warning  : The build tools for Visual Studio 2019 (v142) cannot be found. To build using the Visual Studio 2022 (v143) build tools, either click the Project menu or right-click the solution, and then select "Retarget Solution". Install Visual Studio 2019 (v142) to build using the Visual Studio 2019 (v142) build tools.

But I already installed v142 build tools (see screenshot below).

### Steps to reproduce the bug

1. Clone this repo.
2. Open MUXControls.sln in Visual Studio 2022.
3. Build MUXControlsTestApp in Debug, x64 configuration.

### Expected behavior

Project builds.

### Screenshots

![Screen Shot 2022-05-13 at 5 26 44 PM](https://user-images.githubusercontent.com/359157/168403750-c349d911-9641-4092-acd3-97de4e3f2f47.png)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by lyahdav** [comment]
I thought installing the MSVC v142 C++ build tools should be enough to fix this, but apparently it's not. You need to install VS 2019 and then you can build from VS 2022. Not sure if that's expected.

**Comment by lyahdav** [comment]
Actually I started getting the error "The build tools for Visual Studio 2019 (v142) cannot be found" again after I made some changes to C# code. To fix I had to open the solution in Visual Studio 2019. Would be nice to be able to work on this project entirely in VS 2022.

**Comment by ojhad** [comment]
@llongley fyi
