### ISSUE TITLE
Putting ItemsRepeater inside ScrollViewer throws exception

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#710]
**Describe the bug**
If ItemsRepeater is added into the WinUI version of ScrollViewer following exception is thrown

{System.InvalidCastException: Unable to cast object of type 'Microsoft.UI.Xaml.Controls.InputKind' to type 'System.Int32'.
   at Microsoft.UI.Xaml.Markup.XamlReflectionType.CreateFromString(String value)}

**Steps to reproduce the bug**
```
<Page
    x:Class="WinUITest.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUITest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <!--<controls:ItemsRepeaterScrollHost>-->
            <controls:ScrollViewer x:Name="ScrollViewer">
                <controls:ItemsRepeater x:Name="CategoryList" >
                    <controls:ItemsRepeater.ItemTemplate>
                        <DataTemplate x:DataType="x:String">
                            <TextBlock Text="{x:Bind}"/>
                        </DataTemplate>
                    </controls:ItemsRepeater.ItemTemplate>
                    <controls:ItemsRepeater.Layout>
                        <controls:StackLayout Orientation="Vertical" Spacing="20" />
                    </controls:ItemsRepeater.Layout>
                </controls:ItemsRepeater>
            </controls:ScrollViewer>
        <!--</controls:ItemsRepeaterScrollHost>-->

    </Grid>
</Page>

```
**Expected behavior**
It should work same as OS version of ScrollViewer

**Version Info**

NuGet package version: 
2.2.190430003-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        | Yes   |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by micahl** [comment]
@harvinders, thanks for trying out the new ScrollViewer and reporting!  This is a known issue caused by a bug in the markup compiler that only affects Debug builds (#594).  The [latest Win10 SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk) contains a markup compiler with the fix.  You'll need to install that version of the SDK if you don't have it already.  You can still have it target earlier versions of the OS, but I think you'll have to bump the app's target version to something more recent to ensure compilation uses the latest drop of the markup compiler.

Sorry for the extra hoops.  Is there a place we could have documented the above that would have been helpful to you?

**Comment by chrisglein** [comment]
Right now searching on that error doesn't produce any matching search results. As long as a quick search can find people the workaround I think we're fine... but we're not in that place. The question is which docs are a good candidate to park this compatibility error. @micahl any suggestions?

**Comment by harvinders** [comment]
I think a simple compilation error would have been enough, if that is possible. Otherwise even a runtime exception with proper explanation would have been better.

**Comment by micahl** [comment]
@harvinders, @RBrid is going to bump the required target SDK version for our prerelease packages.  That should help folks avoid hitting this error.  Thanks for your feedback!
