### ISSUE TITLE
[WinUI 3]How do I use Functions in x:Bind in C++ Solution

### ISSUE THREAD

**Issue by TanWei** [microsoft/microsoft-ui-xaml#7100]
I use Functions in x:Bind like this:
~~~
CPP
winrt::Microsoft::UI::Xaml::Visibility ClassName::VisibilityByConnectState(hstring name)
{
    ......;
}

XAML
 <Grid  Visibility="{x:Bind VisibilityByConnectState('connecting_state1'), Mode=OneWay}"/>
~~~

it works onetime;
how can I notify UI refresh.

I've tried：
~~~
.h
winrt::event<Microsoft::UI::Xaml::Data::PropertyChangedEventHandler> property_changed_;
.cpp
property_changed_(*this, Microsoft::UI::Xaml::Data::PropertyChangedEventArgs(L"VisibilityByConnectState"));
~~~

but function VisibilityByConnectState was not called.

**Comment by roxk** [comment]
You don't call property changed with the function name. Instead, you should call property changed with the name of the parameter that you would pass to the function. E.g.

```
// cpp
winrt::Microsoft::UI::Xaml::Visibility ClassName::VisibilityByConnectState(string state)
{
    ......;
}
// Remember to declare SomeState in .idl
hstring SomeState() { return isConnecting ? L"connecting_state1" : L"connecting_state2"; } 

// xaml
// This line says, whenever SomeState changes (one way binding), pass the value of SomeState to VisibilityByConnectState, and bind the function return value to Visiblity
<Grid Visibility={x:Bind VisibilityByConnectState(SomeState), Mode=OneWay}/>
```

 I suggest you familiarize yourself with [the basics of binding first](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart), and then try out function binding.

**Comment by TanWei** [comment]
> You don't call property changed with the function name. Instead, you should call property changed with the name of the parameter that you would pass to the function. E.g.
> 
> ```
> // cpp
> winrt::Microsoft::UI::Xaml::Visibility ClassName::VisibilityByConnectState(string state)
> {
>     ......;
> }
> // Remember to declare SomeState in .idl
> hstring SomeState() { return isConnecting ? L"connecting_state1" : L"connecting_state2"; } 
> 
> // xaml
> // This line says, whenever SomeState changes (one way binding), pass the value of SomeState to VisibilityByConnectState, and bind the function return value to Visiblity
> <Grid Visibility={x:Bind VisibilityByConnectState(SomeState), Mode=OneWay}/>
> ```
> 
> I suggest you familiarize yourself with [the basics of binding first](https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart), and then try out function binding.

Thank you for your reply.

I tried your code and it didn't work.

I saw the c# code example of functions in x: bind earlier(https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings):

~~~
public class Person : INotifyPropertyChanged
{
    //Implementation for an Icon property and a CancellationToken property with PropertyChanged notifications
    ...

    //IconToBitmap function is essentially a multi binding converter between several options.
    public Uri IconToBitmap (Uri icon, Uri cancellationToken)
    {
        Uri foo = new Uri(...);        
        if (isCancelled)
        {
            foo = cancellationToken;
        }
        else 
        {
            if (this.fullName.Contains("Sr"))
            {
               //pass a different Uri back
               foo = new Uri(...);
            }
            else
            {
                foo = icon;
            }
        }
        return foo;
    }

    //Ensure FullName property handles change notification on itself as well as IconToBitmap since the function uses it
    public string FullName
    {
        get { return this.fullName; }
        set
        {
            this.fullName = value;
            this.OnPropertyChanged ();
            this.OnPropertyChanged ("IconToBitmap"); 
            //this ensures Image.Source binding re-evaluates when FullName changes in addition to Icon and CancellationToken
        }
    }
}
~~~

It does call property changed with the function name.Why doesn't it work in C++.

**Comment by TanWei** [comment]
> While dispatching function name works, if you already have a state to pass to the function anyways, you should dispatch update to the state as that makes data flow clearer.
> 
> Just tested and my original code work. Dispatching function name also work. Both C# and C++ work.
> 
> In your output window for Build, did you see a line saying `XamlCompiler warning WMC1506: OneWay bindings require at least one of their steps to support raising notifications when their value changes`? Did you forget to implement `INotifyPropertyChanged`?

Thank you for solving this problem. Just because I forgot to add "oneway" in my actual code

> While dispatching function name works, if you already have a state to pass to the function anyways, you should dispatch update to the state as that makes data flow clearer.
> 
> Just tested and my original code work. Dispatching function name also work. Both C# and C++ work.
> 
> In your output window for Build, did you see a line saying `XamlCompiler warning WMC1506: OneWay bindings require at least one of their steps to support raising notifications when their value changes`? Did you forget to implement `INotifyPropertyChanged`?

Thank you for solving this problem. Just because I forgot to add "oneway" in my actual code. What a stupid mistake.
