### ISSUE TITLE
Question: What is the plan for XamlIslands ?

### ISSUE THREAD

**Issue by JensNordenbro** [microsoft/microsoft-ui-xaml#7104]
Hi! 

XamlIslands seems to be in preview and only "supported" on outdated netcore3.1. 
Does WinUI3 have a corresponding use case for WinForms, WPF?

**Comment by kmgallahan** [comment]
https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/9-xaml-islands-use-winui-3-from-wpf-or-winforms

https://github.com/microsoft/WindowsAppSDK/discussions/2233#discussioncomment-2338216

**Comment by Samuel12321** [comment]
would actually be more useful for Winui2 Xaml islands to support being hosted from a winui3 app, to workaround missing features in Winui 3.
Unfortunately islands not supporting .net 5 has pretty much killed it

**Comment by boppbo** [comment]
Related: #6293
