### ISSUE TITLE
Media Transport Control's progress bar is pre-2.6

### ISSUE THREAD

**Issue by roxk** [microsoft/microsoft-ui-xaml#7105]
### Describe the bug

As titled.

### Steps to reproduce the bug

1. Change the video source of the test app to something from the internet
2. Launch the test app and go to the media transport control page
3. Observe the progress bar has dots, which is pre-2.6

### Expected behavior

The progress bar is post-2.6

### Screenshots

**Current behavior, pre-2.6**
![Screenshot 2022-05-16 122415](https://user-images.githubusercontent.com/16918354/168625433-da6a4cdb-8da8-4856-8636-f0695165d925.png)

**Expected behavior, post-2.6**
![Screenshot 2022-05-16 122706](https://user-images.githubusercontent.com/16918354/168625556-b630219f-4cce-4163-b237-faaca1b505a8.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by gabbybilka** [comment]
Thanks for opening this issue, similarly to the PR the current focus of the team is to assist our users in moving from WinUI 2 to WinUI 3. As the progress bar is different in WinUI 3 and this isn't a critical issue for WinUI 2, we will close this as out of scope.
