### ISSUE TITLE
ItemsRepeater cannot show inside ToolTip

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#711]
**Describe the bug**
`ItemsRepeater` cannot show inside `ToolTip`

**Steps to reproduce the bug**
Place an `ItemsRepeater` inside a `StackPanel`, then inside a `ToolTip`.
The size of `ItemsRepeater` is correctly measured (changes the size of `ToolTip`), but showing blank.

**Expected behavior**
Shows normally as outside `ToolTip`, or `ItemsControl` inside `ToolTip`.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 19H1 (18362)                   | Yes   |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by micahl** [comment]
@huoyaoyuan thanks for filing this issue!  I was able to reproduce it.  I implemented a basic NonVirtualizingLayout and the items appear correctly inside the ToolTip.  So, it looks like an issue with the virtualization logic in the default StackLayout the ItemsRepeater is using.  We'll have to investigate.

**Comment by mikernet** [comment]
This is also the case for an ItemsRepeater inside a Flyout.

**Comment by kmahone** [comment]
Sounds like the same underlying issue as #2349
