### ISSUE TITLE
Background acrylic not supported on windows 10

### ISSUE THREAD

**Issue by Samuel12321** [microsoft/microsoft-ui-xaml#7112]
### Describe the bug

Background acrylic not supported on windows 10 DesktopAcrylicController.IsSupported() returns false.

Someone else encountered it here  #7061

### Steps to reproduce the bug

try DesktopAcrylicController.IsSupported() on windows 10

### Expected behavior

DesktopAcrylicController.IsSupported() returns true

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

This is not documented and no indication was given with the release of 1.1preview 3 that acrylic would not work with windows 10.

**Comment by castorix** [comment]
It still returns false with 1.1.0 stable version... 
(Windows 10 21H1)

**Comment by Samuel12321** [comment]
turns out this isn't a bug, the WinUI team have announced that acrylic will not be supported on windows 10.
So much for down-level support

**Comment by philn0401** [comment]
@Samuel12321: Can you give me the link to the announcement? It's quite disappointed :(

**Comment by OculiViridi** [comment]
So, if acrylic is not going to be supported on Windows 10, then how did they made the acrylic effect on the new [Windows Terminal](https://github.com/microsoft/terminal) application? 😕

**Comment by OculiViridi** [comment]
> It still returns false with 1.1.0 stable version... (Windows 10 21H1)

The same on Windows 10 21H2 (19044.1889) with WinUI 3 - Windows App SDK 1.1.4.

**Comment by Samuel12321** [comment]
> So, if acrylic is not going to be supported on Windows 10, then how did they made the acrylic effect on the new [Windows Terminal](https://github.com/microsoft/terminal) application? 😕

windows terminal uses winui 2 islands

**Comment by oold** [comment]
That is pretty backwards. Use the latest version, get less features and worse support.

**Comment by codendone** [comment]
Update: Desktop acrylic on Win10 will be supported starting in 1.2-preview2.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.2.220930.4-preview2` has been released which fixes this issue.
		
Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2-preview2/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.220930.4-preview2)
