### ISSUE TITLE
Creating fresh WinUI Blank Package and running it throws exception.

### ISSUE THREAD

**Issue by olivegamestudio** [microsoft/microsoft-ui-xaml#7113]
### Describe the bug

Repro steps:

- Create a new WinUI Blank Package app in Visual Studio 2022 17.2
- Build and run package app.

Exception reported straight away:

onecoreuap\windows\moderncore\inputv2\inputhost\outside\lifted\desktopwindowtoplevelhost.cpp(94)\Microsoft.UI.Input.dll!00007FFC366A7490: (caller: 00007FFC366A7781) FailFast(1) tid(5338) 8000FFFF Catastrophic failure
Unhandled exception at 0x00007FFCDE96FA32 (KernelBase.dll) in XXX.exe: Fatal program exit requested.

### Steps to reproduce the bug

- Create a new WinUI Blank Package app in Visual Studio 2022 17.2
- Build and run package app.

### Expected behavior

Expected to see a blank window ready to be worked on.

### NuGet package version

WinUI 3 - Project Reunion 0.8: 0.8.8

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by mqudsi** [comment]
WinUI 3 0.8.x is dead; switch to Windows App SDK 1.0.x or Windows App SDK 1.1 preview.

**Comment by krschau** [comment]
@olivegamestudio Do you still see this with the WindowsAppSDK 1.1? This is just a hunch, but can you make sure you have the runtime installed? It's called the "installer" here: https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
