### ISSUE TITLE
Question: New features is nice but irrelevant as long as outstanding bugs are ignored.

### ISSUE THREAD

**Issue by artkat** [microsoft/microsoft-ui-xaml#7123]
We are approaching the deadline of our application release... which we might have to **postpone due to serious framework bugs** that have been reported long ago and still haven't been addressed:
#7007, #6022 drag-n-drop will crash the whole app.
#5221 App.UnhandledException (reported nearly a year ago!!)

New features is nice but irrelevant as long as outstanding bugs are ignored.

**Comment by knightmeister** [comment]
I agree. I love WinUI but Microsoft needs to stop chasing the new shiny thing and focus on fixing the bugs. There are so many issues with WinUI at present - 2.6k - including several that I raised years ago that are serious problems.

**Comment by Scottj1s** [comment]
@artkat Thanks for raising the alarm.  We're working on fixing the DragDrop and UnhandledException issues now.

**Comment by Scottj1s** [comment]
DragDrop fix is now available in Windows App SDK 1.2 Preview 1.  UnhandledException fix will be available in Preview 2.
