### ISSUE TITLE
InfoBar ignores HorizontalContentAlignment

### ISSUE THREAD

**Issue by grochocki** [microsoft/microsoft-ui-xaml#7127]
### Describe the bug

InfoBar ignores HorizontalContentAlignment property.

### Steps to reproduce the bug

Try the following code:

```xml
<muxc:InfoBar
    IsOpen="True"
    Severity="Warning"
    Title="Title"
    HorizontalContentAlignment="Center"
    Message="Essential app message for your users to be informed of, acknowledge, or take action on." />
```

Actual:
<img width="859" alt="image" src="https://user-images.githubusercontent.com/1414423/169452100-e769a2e5-0b50-4073-9ef4-f5d9b64652e8.png">

Expected (mock):
![image](https://user-images.githubusercontent.com/1414423/169452328-834963e1-1638-4456-8365-4288511b6fa5.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by michael-hawker** [comment]
Looks like the template is pretty bare bones and doesn't provide any of the usually template bindings for dealing with alignment configuration. 🙁

Related to #6945
