### ISSUE TITLE
ProgressRing animation will not work properly when reused

### ISSUE THREAD

**Issue by HHChaos** [microsoft/microsoft-ui-xaml#7128]
### Describe the bug

When I use `ProgressRing`, if the control is reused (page cache or whatever), the animation of `ProgressRing` will stay in a wrong state.
But if I use the `ProgressRing` provided by `Windows.UI.Xaml.Controls` namespace, this problem does not exist.

### Steps to reproduce the bug

1. Compile and run my demo app (https://github.com/HHChaos/WinUIProgressRingBugDemo)
2. Click the "Reload ProgressRing" button.

### Screenshots

![image](https://user-images.githubusercontent.com/9880072/169472871-e2b9aa64-4042-49ce-aed9-b30b6bc4f677.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by roxk** [comment]
Dup of #6775, which is already fixed in 2.8.
