### ISSUE TITLE
Nothing happened in opening built .exe file

### ISSUE THREAD

**Issue by ara-kurd-dev** [microsoft/microsoft-ui-xaml#7132]
### Describe the bug

I want to deploy my app but when build finished successfully it didn't open and nothing appear like error message or something like that.
below is build output:
```
Build started...
1>------ Build started: Project: xamltest, Configuration: Release x64 ------
Restored C:\Users\<user name>\Desktop\test\xamltest\xamltest.csproj (in 341 ms).
1>  xamltest -> C:\Users\<user name>\Desktop\test\xamltest\bin\x64\Release\xamltest.exe
1>  Processing application code
1>  Computing application closure and generating interop code
1>    Loading 81 modules...
1>    Generating code...
1>    Interop code generated.
1>  Compiling interop code
1>  Generating System.Reflection.DispatchProxy proxy code.
1>  Cleaning up unreferenced code
1>  Generating native code
1>  Generating fixups for native code
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

### Steps to reproduce the bug

Opening program in bin\x64\Release\<name>.exe

### Windows app type

- [ ] UWP
- [x] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by hez2010** [comment]
I see you may be using .NET Native which hasn't been supported by WinUI 3. In this case you may encountered exceptions during startup resulting in nothing happening but a silent failure. 
You can check the Event Viewer for exception details.

**Comment by asklar** [comment]
is this really win32 or is it a uwp app? for a uwp app (or any packaged app), you can't just run the exe, that won't work, you need to start the app via e.g. the start menu, or programmatically through the [activation manager API](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-iapplicationactivationmanager).

**Comment by ara-kurd-dev** [comment]
Thanks a lot @asklar I did not know this condition for UWP apps. But how can I achieve [activation manager API](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-iapplicationactivationmanager). can you provide some facilitation, please?

**Comment by asklar** [comment]
Either launch the app from the Start menu, or you can write a launcher exe or script. 

- If you have NodeJS installed, you can use `npx launch-package [package name]`, e.g. `npx launch-package microsoft.windowscalculator`.
- From the command line, you can `start shell:AppsFolder\Microsoft.WindowsCalculator_8wekyb3d8bbwe!App`. Note the `!App`  prefix. 
- You can use a tool included in the SDK/App Certification kit: `"C:\Program Files (x86)\Windows Kits\10\App Certification Kit\microsoft.windows.softwarelogo.appxlauncher.exe" Microsoft.WindowsCalculator_8wekyb3d8bbwe!App`. Note the parameter you pass is the package name followed by the `!app name` like `!App`.
- You can write your own launcher, see [Launcher application](https://docs.microsoft.com/windows/uwp/xbox-apps/automate-launching-uwp-apps#launcher-application-1).
