### ISSUE TITLE
Proposal: CornerRadius for CheckBox looks wrong => Change CornerRadius

### ISSUE THREAD

**Issue by jp-weber** [microsoft/microsoft-ui-xaml#7133]
The current CornerRadius value for the CheckBox looks very wrong, it looks like a RadioButton:
![grafik](https://user-images.githubusercontent.com/10946850/169658468-c2c64888-d08c-49e0-bb4c-b85f044d7b92.png)

The CornerRadius should be adapted for this control.

**Comment by athulrajts** [comment]
If you give higher values for corner radius, square will become circle, i think that is expected.

**Comment by kmgallahan** [comment]
Doesn't look the same as when I run the latest version WinUI 3 Gallery:

![Screenshot 2022-05-21 130736](https://user-images.githubusercontent.com/5379488/169661968-9fff863d-31e4-4529-b1e8-5f98cdadf163.jpg)

**Comment by kmgallahan** [comment]
Based on this and your other opened issue I'd say there is something wrong with your environment, don't know what though.

You didn't fill out any environment details so I'm not sure if this you are running WinUI 2 or 3.

**Comment by jp-weber** [comment]
My picture is from the WinUI2 Gallery. But you are right, I edited now the WinUI version in the first comment.
![grafik](https://user-images.githubusercontent.com/10946850/169662963-d814dcdd-e719-41b3-952b-a8be30fa58d7.png)

But I can confirm, that when I use the CheckBox in my app, it looks right. This problem is apparently only related to the WinUI2 gallery app.
