### ISSUE TITLE
WinRT originate error - 0x80131508 : 'Index was outside the bounds of the array.'.

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#7135]
### Describe the bug

Difficult to describe; changed between tabs on a tab view though perhaps it isn't significant. I do not even know if the first or the second as "The specified module could not be found." error has caused the process termination. 

![image](https://user-images.githubusercontent.com/43340959/169695447-3bf8a533-545e-4811-b648-4ee61a30eb98.png)

### Steps to reproduce the bug

Sorry I do not know but ready to furnish further info upon demand. 

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (20H2): Build 19042

### Additional context

Exception thrown at 0x00007FFE7D474F69 (KernelBase.dll) in Weather.History.Windows.Desktop.exe: WinRT originate error - 0x80131508 : 'Index was outside the bounds of the array.'.
The thread 0x5e80 has exited with code 0 (0x0).
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFE7F24BEE3: (caller: 00007FFE7F255BC9) ReturnHr(1) tid(105c) 8007007E The specified module could not be found.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFE7F24BEE3: (caller: 00007FFE7F3CCC47) ReturnHr(2) tid(105c) 8007007E The specified module could not be found.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFE7F24BEE3: (caller: 00007FFE7F3CC6B3) ReturnHr(3) tid(105c) 8007007E The specified module could not be found.
Unhandled exception at 0x00007FFE7D54B362 (KernelBase.dll) in Weather.History.Windows.Desktop.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001F2731DD7E0, 0x0000000000000001).

**Comment by sigmarsson** [comment]
sorry, there was a fat change set committed recently that vanished this error. I just suspect the view models I hopped on and off by changing the tabs - are now created by Prism auto view model locator. But honestly not sure about this at all.

**Comment by bpulliam** [comment]
Without a repro, I'm going to close this issue.  If you see it again, please let us know the repro.  Thanks
