### ISSUE TITLE
winui 3 textbox clear button is not shown correctly

### ISSUE THREAD

**Issue by sxmike** [microsoft/microsoft-ui-xaml#7139]
### Describe the bug

My windows: win 10 chinese simplified
When my winui 3 app stared, the textbox is shown like this:

![image](https://user-images.githubusercontent.com/37815391/169678088-7bd4cf6c-d8c9-42ac-89d7-bbbddcbcddd5.png)

Obviously the clear button is not shown correctly.

### Steps to reproduce the bug

win 10 chinese simplified version
visual studio 2022
Just build a winui 3 project and place a textbox in the window.

**Comment by ojhad** [comment]
@sxmike which version of winui3 are you using?

**Comment by swat199538** [comment]
me too.

**Comment by Jay-o-Way** [comment]
Caused by this: https://github.com/microsoft/microsoft-ui-xaml/issues/8375

**Comment by Jay-o-Way** [comment]
Is this still an issue with the latest version? /needinfo

**Comment by ranjeshj** [comment]
This should be fixed in 1.5 stable. Please let us know if you still see it with the latest release.
https://github.com/microsoft/microsoft-ui-xaml/issues/8375
