### ISSUE TITLE
TextBox.PlaceholderText does support FlowDirection.RightToLeft

### ISSUE THREAD

**Issue by chrisahill** [microsoft/microsoft-ui-xaml#714]
**Describe the bug**
`TextBox.PlaceholderText` does not support `FlowDirection.RightToLeft` I've applied various globalization strategies provided by MS describing how to handle RTL and none of them seem to address this issue.

`xml:lang` and `FrameworkElement.Langauge`
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.language

**Steps to reproduce the bug**
```Xaml
<TextBox
  xml:lang="ar"
  Language="ar"
  Header="Header"
  PlaceholderText="Hello World" 
  FlowDirection="RightToLeft" />
```

**Expected behavior**
The text should be rendered on the right side of the text box, but instead renders on the left.

**Screenshots**
![image](https://user-images.githubusercontent.com/3513437/57808160-9fc5bc00-7717-11e9-81e0-cb03f6f71448.png)

**Language Setting**
![image](https://user-images.githubusercontent.com/3513437/57806014-16ac8600-7713-11e9-9a13-675764a4e088.png)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes (UWP)  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional Info**
Found a similar issue with Xamrin Forms
https://github.com/xamarin/Xamarin.Forms/issues/3359

**Comment by chrisahill** [comment]
Looks like the text flipping is entirely dependent on the language loaded. If the language is Arabic it will render to the right and if the language is English it will render to the left. 

![image](https://user-images.githubusercontent.com/3513437/57811630-993b4280-771f-11e9-9c09-e5a21d88bb07.png)

Mixing English with Arabic is the case i'm handling like below, where there isn't a specific Arabic translation.
![image](https://user-images.githubusercontent.com/3513437/57811801-11a20380-7720-11e9-8541-5eb0ca915b65.png)

^^ I guess in the above case here the user would have switch to an English keyboard to type in a Url and when typing in English text will be entered `LeftToRight` and if typing using `Arabic` language the cursor would insert text from `RightToLeft`

**Comment by jevansaks** [comment]
Yeah, that's just the richedit behavior -- paragraph alignment follows the flow direction of the text paragraph. For testing purposes you can make english text flow right to left. See https://www.w3.org/International/questions/qa-bidi-unicode-controls and use the LRO or RLO unicode characters to force text to flow the other way.

&#x202E;Then you can make your text look unreadable, ha ha!
