### ISSUE TITLE
Question: Page Navigation :: Lost Bindig => KeepAlive ?

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#7141]
Is there anything existing in WinUI like [KeepAlive](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.page.keepalive?redirectedfrom=MSDN&view=windowsdesktop-6.0#System_Windows_Controls_Page_KeepAlive) ? I witness ```x:Bind Mode=OneWay``` losing binding upon navigation across ```Pages```. Any1 anything like such vexing issue expreienced ? Thank you.

**Comment by ojhad** [comment]
Is this what you are looking for?
https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.page.navigationcachemode?view=windows-app-sdk-1.0#microsoft-ui-xaml-controls-page-navigationcachemode

**Comment by gautambjain** [comment]
NavigationCacheMode doesn't solve the purpose. I had to change Page to UserControl and explicitly hide and show to keep it alive in WinUI.
