### ISSUE TITLE
Add or remove file from solution takes long time

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#7145]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-or-remove-file-from-solution-takes-l/1553317)._

---
[severity:It's more difficult to complete my work]
The overall performance of Visual Studio 2022 preview 5 is significantly impacting my productivity. Adding and removing files is a common activity and the current performance level isn't what I would expect.

---
#### Feedback Bot on 10/14/2021, 02:15 AM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 10/14/2021, 07:57 PM: 

(private comment, text removed)
#### Daren May on 10/19/2021, 10:29 AM: 

(private comment, text removed)
#### Daren May on 10/29/2021, 00:39 PM: 

(private comment, text removed)
#### Daren May on 10/19/2021, 10:37 AM: 

(private comment, text removed)
#### Daren May on 10/27/2021, 01:31 PM: 

(private comment, text removed)
#### Feedback Bot on 11/2/2021, 10:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mgoertz-msft** [comment]
From David Kean's investigation: 99% of this delay of ~104 seconds is executing the XAML compiler during design-time build down these two methods.

![c156c588-436d-4d35-8a1b-59e2308f8a52](https://user-images.githubusercontent.com/14282894/170292785-cc5a645a-ba1a-48e4-859d-91146aaedde7.png)

Looking at the data, it looks like GC time is definitely not helping here, during the delay I see 50 GB (!) of allocations here:

![f2b82c2a-3c50-469a-b826-8f29e957e08d](https://user-images.githubusercontent.com/14282894/170292872-6ef094a5-e803-483f-83f2-6e11008007d4.png)

**Comment by ojhad** [comment]
@fabiant3 FYI
