### ISSUE TITLE
NavigationView crashes after adding FooterMenuItems while using DataTemplate

### ISSUE THREAD

**Issue by JasonWues** [microsoft/microsoft-ui-xaml#7147]
### Describe the bug

Using the DataTemplate data template to render NavigationViewItems and then add FooterMenuItems will encounter crash,
This problem does not occur without using DataTemplat.

### Steps to reproduce the bug

    <Grid>
        <NavigationView x:Name="MainNav"
                        MenuItemsSource="{x:Bind addresseList,Mode=OneWay}"
                        PaneDisplayMode="LeftCompact"
                        Loaded="MainNavLoadedAsync"
                        PaneTitle="WeatherN"
                        SelectionChanged="MainNavSelectionChangedAsync">
            <NavigationView.MenuItemTemplate>
                <DataTemplate x:DataType="Model:Address">
                    <NavigationViewItem Content="{x:Bind Cname}" Tag="{x:Bind Cid}" Icon="{x:Bind Icon}"/>
                </DataTemplate>
            </NavigationView.MenuItemTemplate>
            <NavigationView.FooterMenuItems>
                <NavigationViewItem Content="test"/>
            </NavigationView.FooterMenuItems>
            
        </NavigationView>
    </Grid>

    public class Address
    {
        public string Cip { get; set; }
        public string Cid { get; set; }
        public string Cname { get; set; }
        public IconElement Icon { get; set; }
    }

    public ObservableCollection<Address> addresseList { get; set; }

this is the code i use

### Screenshots

![Snipaste_2022-05-26_13-56-38](https://user-images.githubusercontent.com/33679139/170426175-43f6dfab-0481-43f2-b7d0-4a77b7a1bf42.png)
![Snipaste_2022-05-26_13-58-20](https://user-images.githubusercontent.com/33679139/170426371-06f9b109-94a8-4944-8a28-5dec5f2521e8.png)
Jump here after compiling.

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [x] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by Shad0wlife** [comment]
FooterMenuItems also use the DataTemplate, which is counter-intuitive in my opinion. I reported the same almost two years ago, but progress on that issue has stalled.
The relevant Pull Requests are #3811 for the potential fix and #4518 for the API Spec change describing the fix.

**Comment by hawkerm** [comment]
I'm encountering this in UWP as well. I have a hierarchical set of regular MenuItems, so have to use a DataTemplateSelector for that already, but then that's being used for the FooterMenuItems, which I just want a static list of `NavigationViewItem` in my XAML for, but that also calls the template selector with the `NavigationViewItem` which makes little sense as I can't make a DataTemplate for a `NavigationViewItem` from a `NavigationViewItem` easily without shadow copying all the bindings which is silly. I tried using a `ContentPresenter` to pass in the `NavigationViewItem`, but it crashed.

```xml
        <DataTemplate x:Key="DefaultMenuTemplate" x:DataType="muxc:NavigationViewItem">
            <ContentPresenter Content="{Binding}"/>
        </DataTemplate>

    <muxc:NavigationView MenuItemsSource="{x:Bind ViewModel.Items}" PaneDisplayMode="Left"
                         MenuItemTemplateSelector="{StaticResource MenuTemplateSelector}"
                         ItemInvoked="NavigationView_ItemInvoked">
        <muxc:NavigationView.FooterMenuItems>
            <muxc:NavigationViewItem Icon="Add" Content="Add Item" SelectsOnInvoked="False">
```

**Comment by wesol1** [comment]
Maybe it will help someone, here is my workaround. I got hierarchical data, template selector and couple of footer menu items. On the last footer menu item I added Loaded event in which I assign template selector to NavigationView. Works for me: 
 <NavigationView x:Name="NavigationViewControl"
                    AlwaysShowHeader="False"
                    ExpandedModeThresholdWidth="285"
                    IsBackButtonVisible="Collapsed"
                    IsPaneOpen="True"
                    IsSettingsVisible="False"
                    MenuItemsSource="{Binding Children}"
                    PaneClosing="OnPaneClosing"
                    PaneDisplayMode="Left"
                    PaneOpening="OnPaneOpening"
                    PaneTitle="Projects"
                    SelectionChanged="OnNavigationViewItemSelectionChanged">
        <NavigationView.PaneCustomContent>
            <controls:BusyIndicator IsBusy="{Binding IsBusy}" Text="Loading Projects..." />
        </NavigationView.PaneCustomContent>
        <NavigationView.FooterMenuItems>
            <NavigationViewItem x:Name="HelpNavigationViewItem"
                                Content="Help"
                                Tag="Help"
                                Tapped="HelpNavigationViewItem_Tapped">
                <NavigationViewItem.Resources>
                    <TeachingTip x:Name="HelpTeachingTip"
                                 PreferredPlacement="TopRight"
                                 Target="{x:Bind HelpNavigationViewItem}">
                        <TextBlock Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." TextWrapping="WrapWholeWords" />
                    </TeachingTip>
                </NavigationViewItem.Resources>
                <NavigationViewItem.Icon>
                    <FontIcon FontFamily="{StaticResource FluentIcons}"
                              FontSize="16px"
                              Glyph="{utils:FluentIconGlyphProvider IsSegoe=False,
                                                                    Name='Question'}" />
                </NavigationViewItem.Icon>
            </NavigationViewItem>
            <NavigationViewItem x:Name="FiltersNavigationViewItem"
                                Content="Filters"
                                Tag="Filters">
                <NavigationViewItem.Icon>
                    <FontIcon FontFamily="{StaticResource FluentIcons}"
                              FontSize="16px"
                              Glyph="{utils:FluentIconGlyphProvider IsSegoe=False,
                                                                    Name='Filter'}" />
                </NavigationViewItem.Icon>
            </NavigationViewItem>
            <NavigationViewItem x:Name="AddNavigationViewItem"
                                Content="Add Project"
                                Loaded="AddNavigationViewItem_Loaded"
                                Tag="Add">
                <NavigationViewItem.Icon>
                    <FontIcon FontFamily="{StaticResource FluentIcons}"
                              FontSize="16px"
                              Glyph="{utils:FluentIconGlyphProvider IsSegoe=False,
                                                                    Name='Add'}" />
                </NavigationViewItem.Icon>
            </NavigationViewItem>
        </NavigationView.FooterMenuItems>
        <Frame>
            <views:ApplicationsDashboardPage DataContext="{Binding ActiveChild.ActiveChild.ActiveChild}" />
        </Frame>
    </NavigationView>
