### ISSUE TITLE
Error from xaml targets appears before building a C# UWP project

### ISSUE THREAD

**Issue by MSLukeWest** [microsoft/microsoft-ui-xaml#715]
**Describe the bug**
1. Create a C# UWP project

**Steps to reproduce the bug**
1. Create a new C# UWP project, don't build
2. Open the error list

Result: You'll see one error: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'

**Expected behavior**
No errors in the error list

**Version Info**
19h1 (18362) SDK
19h1 (18362) OS
Any VS 2019 build

**Additional context**
This warning comes from the CompileXaml task in target DesignTimeMarkupCompilationCT in Microsoft.Windows.UI.Xaml.Common.targets

This comes from a design time build in Visual Studio.  If you build the project it goes away.

**Comment by jevansaks** [comment]
@fabiant3 I've seen this one come from CompileXaml before -- it usually points to an incomplete nuget restore but it's never clear what's wrong or how to recover. Do you know who can provide guidance?

**Comment by fabiant3** [comment]
This usually point towards an issue with how the XAML Compiler is being invoked by VS. Adding @SvetBonev

**Comment by danzil** [comment]
@SvetBonev, any chance you could look at this issue? It looks like another interaction between NuGet and the project system that missed a reference to be passed to the Xaml Compiler.

**Comment by SvetBonev** [comment]
@fabiant3-zz This issue has been fixed in VS and will be available in the next update of Dev16.
