### ISSUE TITLE
Microsoft Graphics Win2D WinUI Desktop is missing

### ISSUE THREAD

**Issue by AghaKhan** [microsoft/microsoft-ui-xaml#7154]
### Describe the bug

If you want to develop WinUI 3 and want to create your own user control, then you are out of luck. I have developed UWP control, and it worked fine, because Win2D.uwp is available. You will also find www.nuget.org/packages/Microsoft.Maui.Graphics.Win2D.WinUI.Desktop is available, if you are developing Maui application. Microsoft has not provided any implementation of Win2D for Desktop application. I am blocked.  

### Steps to reproduce the bug

Try to add  WinUI library with Desk Top application. to add Win2D

### Expected behavior

I should be able to create such controls.

### Screenshots

![image](https://user-images.githubusercontent.com/5318363/170619878-71be3406-b8b3-43fd-bee8-4458e26788ce.png)

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by MikeHillberg** [comment]
Are you looking for https://www.nuget.org/packages/Microsoft.Graphics.Win2D?

**Comment by kmgallahan** [comment]
> Microsoft has not provided any implementation of Win2D for Desktop application.

Very assertive even while showing the package you are looking for in your screenshot...

**Comment by AghaKhan** [comment]
No, it did not work. Simple Win2D will not work. For uwp Microsoft has provided Win2D.uwp and for maui sur they have provided.  and tried what you suggested, it didn't work. [https://1drv.ms/u/s!AtjIdnVOoJXtofEa1kQwUB_g_xBfNw?e=LKeQLg](url)

**Comment by AghaKhan** [comment]
Even this project is Empty, still this will not compile. Please download from above link. Thanks for reply.[https://1drv.ms/u/s!AtjIdnVOoJXtofEa1kQwUB_g_xBfNw?e=LVRlAw](url)

**Comment by castorix** [comment]
You can use **Direct2D** 
I use it in C#, C++, and even VB, and it works perfectly
A test with [ID2D1SpriteBatch](https://docs.microsoft.com/en-us/windows/win32/api/d2d1_3/nn-d2d1_3-id2d1spritebatch) :

![WinUI3_Direct2D_SpriteBatch](https://user-images.githubusercontent.com/22345506/167647913-d579b2dd-2377-4b5c-a57f-c251d07a399a.jpg)

**Comment by AghaKhan** [comment]
Well, we are missing the point. We want to develop WinUI and we must focus on only WinUI 3. I have developed this application with Win2D.uwp and work fine, but I am looking Win2D for desktop. 
![image](https://user-images.githubusercontent.com/5318363/170641931-2d652d50-9fa9-46cf-aea2-3adecdf879ac.png)

**Comment by castorix** [comment]
> but I am looking Win2D for desktop

I don't see why .you need Win2D, which wraps Direct2D
You don't need any external DLL to use existing native APIs

**Comment by AghaKhan** [comment]
Thank you for your reply. The above application you see is written with Win2D, and I am using UWP. Just ask yourself a question, why we use Win2D? Win2D is framework to call primitive calls, like Draw Rectangle, draw a curve. I think there are only 25 such calls and direct from GPU, so they are extremely fast. Best of all Microsoft supports Win2D not only Windows, but also other operating systems. I need Win2D for fast rendering.  Microsoft has provided all over Win2D, why not WinUI? I want to create User controls which are lighting fast and don't want to call any graphic call (protected mode). I hope you understand that. Regards

**Comment by lhak** [comment]
@AghaKhan You are referencing an outdated version of the windows app sdk (1.0 experimental). Just update to the latest version (and remove all other nuget packages except Microsoft.WindowsAppSDK). Then the win2d nuget package will install.

**Comment by AghaKhan** [comment]
Hi lhak: It seems it is working. It compiles but have not written yet.  Thanks for help. I did not find CanvasAnimatedControl, but found CanvasControl. As I recall CanvasAnimatedControl call 60 FPS whereas CanvasAnimatedControl updates when it is needed. Kindly let me know why CanvasAnimatedControl  is not available. Regards

**Comment by AghaKhan** [comment]
CanvasAnimatedControl Class
XAML control intended for displaying animating content. Currently unsupported for WinUI3.

**Comment by AghaKhan** [comment]
It works fine. That is the reson I closed it.
