### ISSUE TITLE
Creating image based on simple drawing. 

### ISSUE THREAD

**Issue by AghaKhan** [microsoft/microsoft-ui-xaml#7155]
You may be able to create an image based on simple drawings under WPF. For some unknow reason(s) it is missing Windows App SDK. I used mini language to create such image under WPF.

**Comment by castorix** [comment]
There are many ways to draw on screen then save the image
One of the ways is to embed the _InkPicture_ control :

![InkPicture](https://user-images.githubusercontent.com/22345506/170647596-3bbaaff0-79c8-4a67-9fea-f256e023e979.gif)

**Comment by bpulliam** [comment]
Can this item be closed?

**Comment by AghaKhan** [comment]
Please close it.
