### ISSUE TITLE
Unable to access WinUI 3 API documentation.

### ISSUE THREAD

**Issue by MarkBrainfire** [microsoft/microsoft-ui-xaml#7157]
### Describe the bug

API documentation for WinUI 3 (Desktop) is no longer available.  Attempts to access it is redirected to WinUI 2.7 documentation.  See attached video.

https://user-images.githubusercontent.com/78389339/170804351-47fb3da5-3659-446d-bf75-f130f54bf7d4.mp4

### Steps to reproduce the bug

1. Attempt to access the WinUI 3 documentation.
2. It is impossible. Instead, you are redirected to WinUI 2.7 API documentation.

Please see attached video.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by kmgallahan** [comment]
I noticed this too today and opened this issue:

https://github.com/MicrosoftDocs/winui-api/issues/119

**Comment by gabbybilka** [comment]
Thanks for the tag, looped in some of our docs folks to take a look.
cc: @stevewri

**Comment by krschau** [comment]
Closing this, as issue https://github.com/MicrosoftDocs/winui-api/issues/119 mentioned above is better for tracking.
