### ISSUE TITLE
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.1

### ISSUE THREAD

**Issue by StevenTCramer** [microsoft/microsoft-ui-xaml#716]
Faulting application name: Todo.exe, version: 1.56.1905.10002, time stamp: 0x5cd55963
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.1, time stamp: 0x59570cf9
Exception code: 0xc000027b
Fault offset: 0x0000000000712720
Faulting process id: 0x6f94
Faulting application start time: 0x01d50b8d2bc63aa0
Faulting application path: C:\Program Files\WindowsApps\Microsoft.Todos_1.56.21302.0_x64__8wekyb3d8bbwe\Todo.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 653f96bb-909a-42a4-8d71-89694026609a
Faulting package full name: Microsoft.Todos_1.56.21302.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

Error in event viewer.

And Feedback hub is the same issue.

Faulting application name: PilotshubApp.exe, version: 1.1811.1903.27002, time stamp: 0x5c9bb208
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.1, time stamp: 0x59570cf9
Exception code: 0xc000027b
Fault offset: 0x0000000000712720
Faulting process id: 0x5254
Faulting application start time: 0x01d50b8b4723c14e
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsFeedbackHub_1.1811.10862.0_x64__8wekyb3d8bbwe\PilotshubApp.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: e3c3046b-6c29-4b69-8547-209ef68986ba
Faulting package full name: Microsoft.WindowsFeedbackHub_1.1811.10862.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by jevansaks** [comment]
Thanks for reporting this issue. Did this just start happening after upgrade to 18362? Is this VM uploading telemetry? These report GUIDs are not showing up in the system.

Also do you see any files in:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive

If there's anything there that might be helpful for correlating to the problem.

**Comment by StevenTCramer** [comment]
Three or four days ago when I installed with the Windows 10 April Update.

Got another update today and still same.  My current version is Version 10.0.18362 Build 18362

**Comment by jevansaks** [comment]
How about the other questions? 

Is the device uploading telemetry, or did you opt out? 
![image](https://user-images.githubusercontent.com/20667023/57825346-4ed3b900-7753-11e9-9976-f9c7754e48be.png)

And are there any files in the `C:\ProgramData\Microsoft\Windows\WER\ReportArchive` location?

**Comment by StevenTCramer** [comment]
Yes full send info is enabled.  And 

```
C:\ProgramData\Microsoft\Windows\WER\ReportArchive                                                                                                                       
λ  ls                                                                                                                                                                    
                                                                                                                                                                         
                                                                                                                                                                         
    Directory: C:\ProgramData\Microsoft\Windows\WER\ReportArchive                                                                                                        
                                                                                                                                                                         
                                                                                                                                                                         
Mode                LastWriteTime         Length Name                                                                                                                    
----                -------------         ------ ----                                                                                                                    
d-----       2019-05-14   8:30 AM                AppCrash_brave.exe_de577af9fa9fe44121f11fad5fe2330a58df7c0_401f4fd3_91b5902f-2ebb-47a2-8134-ec723aede142                
d-----       2019-05-11   2:03 PM                AppCrash_C__git_blazor-st_e224c9fb1533f394b3d21378f60e656ef2b73ca_bb5a3de7_cab_b9ccf0a9-31f8-436d-bde0-236cf017a334     
d-----       2019-05-11   6:51 AM                AppCrash_C__Program Files_5e728d83aa179b54865d4617bc27fd7a8cda843_13971451_250f13cc-0845-42b1-96e5-92e4ab8affec         
d-----       2019-05-11   6:51 AM                AppCrash_C__Program Files_5e728d83aa179b54865d4617bc27fd7a8cda843_13971451_5738f618-0414-4a37-8a56-dd1be28380f7         
d-----       2019-05-10   6:47 PM                AppCrash_C__Program Files_5e728d83aa179b54865d4617bc27fd7a8cda843_13971451_83c63d6c-a151-4e49-af37-f6b8d3d395b6         
d-----       2019-05-10   6:47 PM                AppCrash_C__Program Files_5e728d83aa179b54865d4617bc27fd7a8cda843_13971451_8daad3d2-b065-4dbc-b95f-a4f8dcfa4d2d         
d-----       2019-05-10   6:46 PM                AppCrash_C__Program Files_5e728d83aa179b54865d4617bc27fd7a8cda843_13971451_a6b8d655-11c4-473f-b3dc-b65729008673         
d-----       2019-05-11   6:51 AM                AppCrash_C__Program Files_5e728d83aa179b54865d4617bc27fd7a8cda843_13971451_b2543d23-cbb0-4cff-8f5d-7d6a2ce2ac65         
d-----       2019-05-15  12:07 PM                AppCrash_C__Program Files_9615ecf2b4dc0b14c33d9f9468f56564c9b712_13971451_06db5c71-6a22-4ee0-9593-0f5b547e6a9b          
d-----       2019-05-10   7:57 PM                AppCrash_C__Program Files_9615ecf2b4dc0b14c33d9f9468f56564c9b712_13971451_0bc6c760-c60b-4e65-b1fd-10f511f393be          
d-----       2019-05-09  10:18 AM                AppCrash_C__Program Files_9615ecf2b4dc0b14c33d9f9468f56564c9b712_13971451_24035ec5-8853-488e-9a1d-875fea49379d          
d-----       2019-05-15  12:09 PM                AppCrash_C__Program Files_9615ecf2b4dc0b14c33d9f9468f56564c9b712_13971451_2759a67e-8516-41ad-ae35-666dc131af10          
d-----       2019-05-11   4:32 PM                AppCrash_C__Program Files_9615ecf2b4dc0b14c33d9f9468f56564c9b712_13971451_2b48474a-c88d-4d34-a5c6-0685be276293          
d-----       2019-05-15   8:20 PM                AppCrash_C__Program Files_9615ecf2b4dc0b14c33d9f9468f56564c9b712_13971451_2db542d5-c2ac-472f-847a-9aa250c9d155          
d-----       2019-05-09  10:06 PM                AppCrash_C__Program Files_9615ecf2b4dc0b14c33d9f9468f56564c9b712_13971451_33f73f5b-a11d-457e-ac0a-e9f6601f9cc2          
...
```

**Comment by jevansaks** [comment]
Could you zip that directory up and share it out? If you don't want to attach it to a comment you because of privacy concerns can email it to me (my email is in my github profile).

**Comment by StevenTCramer** [comment]
@jevansaks I have it zipped but I do not see your email in your profile.

**Comment by jevansaks** [comment]
oops, fixed.

**Comment by jevansaks** [comment]
You may be hitting a bug that we’ve been trying to track down a repro for! This is very exciting. I will follow up with you over email to collect more diagnostics. Thank you so much for taking the time to report this issue!

**Comment by StevenTCramer** [comment]
Updated to Windows Version 10.0.18362 Build 18362 kb4505057 today and the problem still persists

**Comment by jevansaks** [comment]
Thank you for the ping! We've got an email thread going internally trying to dig into this. We'll follow up with you soon. If you can keep your machine in the broken state for a little longer, we might need to have you grab some info from the debugger.

**Comment by jevansaks** [comment]
@StevenTCramer if you're still in this state, my colleague Srinivas emailed you yesterday to collect some additional traces from your machine. We'd really appreciate it if you could take some time to help us get to the bottom of this!

**Comment by StevenTCramer** [comment]
@jevansaks I just responded to him and yes I am still in this state.  Don't know how to get out of it frankly.  Please reach out to me on Skype (StevenTCramer) for faster response. Email these days has a low signal to noise ratio.

**Comment by jevansaks** [comment]
Thanks for going the extra mile to help us out. I'm asking to see what the next steps are.

**Comment by jevansaks** [comment]
Sorry for the delay, and thanks again @StevenTCramer for the help. The platform team believes that they understand the issues that contributed to this problem and they're working on getting the fixes out. I'm asking to see if there are any remediation steps you can run locally to unblock yourself (if you're still in this situation).

**Comment by AlexanderYW** [comment]
Hi @jevansaks, is this issue still a thing?, cause I'm experiencing that error with Adobe XD

```Faulting application name: XD.exe, version: 23.1.32.2, time stamp: 0x5d9dac01
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.418, time stamp: 0x253810c2
Exception code: 0xc000027b
Fault offset: 0x0000000000712dc0
Faulting process ID: 0x4528
Faulting application start time: 0x01d580fa74e8c8b6
Faulting application path: C:\Program Files\WindowsApps\Adobe.CC.XD_23.1.32.2_x64__adky2gkssdxte\XD.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report ID: 9f436721-9ed3-4e32-b079-2cc36d3e3daf
Faulting package full name: Adobe.CC.XD_23.1.32.2_x64__adky2gkssdxte
Faulting package-relative application ID: App
```

**Comment by jevansaks** [comment]
@alexanderYW can you file a Feedback Hub item from the affected machine, then share an URL with the feedback hub link? That will enable us to correlate the crashes to see if it is.

For you is the adobe app crashing on launch?

**Comment by AlexanderYW** [comment]
@jevansaks sure the URL is https://aka.ms/AA69i4n

Yes it does, unless i open a Adobe XD file directly then it crashes on launch and gives this error
![image](https://user-images.githubusercontent.com/4184558/66777219-af188380-eec8-11e9-84d7-7011433c9381.png)

**Comment by jevansaks** [comment]
This is showing as a different crash but the backend doesn't have full data. I've requested more -- can you trigger the crash a couple more times and i'll see if the data we need shows up?

**Comment by AlexanderYW** [comment]
You mean a different crash regarding what i posted i got from the event viewer?, not quite sure how i can make sure that the backend have full data

I tried triggering the crash by launching the app 3 different ways hope that helps

**Comment by jevansaks** [comment]
Thanks! I will check on the backend tomorrow and see if the data has been uploaded/processed.

**Comment by TheManFromDelmote** [comment]
Faulting application name: SecHealthUI.exe, version: 10.0.18362.387, time stamp: 0x5d8990a3
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.449, time stamp: 0xb90db728
I have been trying to add another exclusion to defender, now the windows closes and I get this message after selecting the drop down item containing File/Folder/File type/Process


Exception code: 0xc000027b
Fault offset: 0x0000000000712ec0
Faulting process ID: 0x242c
Faulting application start time: 0x01d594dbeb68c529
Faulting application path: C:\WINDOWS\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy\SecHealthUI.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report ID: 562c4d97-b029-47b5-ae96-5469758ca4f5
Faulting package full name: Microsoft.Windows.SecHealthUI_10.0.18362.449_neutral__cw5n1h2txyewy
Faulting package-relative application ID: SecHealthUI

**Comment by jevansaks** [comment]
Sorry this one fell off my radar, I have some diagnostic cabs now that I'm going to follow up with @DanZil on.

**Comment by AlexanderYW** [comment]
No problem 😊

**Comment by jevansaks** [comment]
I've followed up with a couple of the bucket issues here but crashes that appear here aren't actually WinUI issues, they're app problems. That said, we should do better to make these issues identify the app more clearly when they occur so let's use this issue to track that problem.

**Comment by michael-hawker** [comment]
@jevansaks I'm having a similar type of issue using 2.2.190917002 (looks like fault offset is different though):

```
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.418, time stamp: 0x253810c2
Exception code: 0xc000027b
Fault offset: 0x0000000000712dc0
Faulting process id: 0x94d4
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 078d4156-8a65-4cbf-b61c-ed99ae5f1f65
```

App seems to run fine in release mode from VS, but when deployed through app package crashes on splash screen startup (though then works fine if I debug installed app package, so not sure how to get more info).

**Comment by michael-hawker** [comment]
Circling back the error I faced was because I had a WinUI component referencing a non-WinUI style (from generic.xaml) for NavigationViewItem.  I was able to prefix the style with `MUX_` as appears to be done internally for the NavigationView component in order to work around the issue.

However, it was a bit weird this error didn't really come-up right away when running in Debug or Release mode.

**Comment by jevansaks** [comment]
The fix for the original issue still hasn't made it out to servicing. If you are affected then the manual remediation is to uninstall all the affected apps and then re-install them from the store.

If you’re comfortable with PowerShell then you can search for the apps that are using the shared framework (Either Xaml.2.0, Xaml.2.1 or Xaml2.2) and uninstall all of them. For example to identify all the apps using the 2.0 framework:
```powershell
get-appxpackage | Where-Object { ($_.Dependencies | Where-Object { $_.Name.Contains("Xaml.2.0")}).Count -gt 0 } | Select-Object Name
```

And you could uninstall them with `Remove-AppxPackage -AllUsers ...`. To confirm that the framework is uninstalled, run:

```powershell
get-appxpackage Microsoft.UI.Xaml.2.0
```

And make sure that the output is empty. Then re-install the apps from the store.

**Comment by StevenTCramer** [comment]
@jevansaks Yes Srinivas helped me to do just this on two different occasions.  Hopefully the fix will make it out soon.

**Comment by jdsemma** [comment]
Reregistering the Microsoft.UI.Xaml.2.0 and 2.1 packages in a logon script is working for our users on mandatory profiles under 1903. We were only seeing the crashes with Photos and Paint3D, but also hadn't tried checking every UWP app out there. Will be glad to see the fixes appear in an update!

**Comment by jevansaks** [comment]
> How did you go about re-registering those packages?

Once they are uninstalled then they will get re-installed by the installation of a dependent app that uses them.

**Comment by jdsemma** [comment]
I made a powershell logon script with a couple of lines. Basically I ran get-appxpackage Microsoft.UI.Xaml.2 and looked for the full command line to use for both 2.0 and 2.1 versions, x86 and x64. Like this:

add-appxpackage -disabledevelopmentmode -register "C:\program files\windowsapps\Microsoft.UI.Xaml.2.1_2.119whateveritwas\AppxManifest.xml" 
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.0_2.1810.18004.0_x86__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.0_2.1810.18004.0_x64__8wekyb3d8bbwe\AppxManifest.xml"

Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.1_2.11906.6001.0_x86__8wekyb3d8bbwe\AppxManifest.xml"
Add-AppxPackage -DisableDevelopmentMode -Register "C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.1_2.11906.6001.0_x64__8wekyb3d8bbwe\AppxManifest.xml"

This does resolve the Photos app crashing on startup, but apparently by virtue of it not being 'installed' for the user at all until they run it the first time. I haven't yet experimented with running add-appxpackage on Photos after I do these UI.Xaml lines; I'll need to, as the default file association for .gif is Internet Explorer!! Crazytown.

**Comment by dvucinozd** [comment]
kill photos.exe in task manager and go to power shell as admin
paste following:
`$Apps = @("WindowsCalculator","Photos");

$base   = @();
$depend = @();
$Apps | %{
    $base   += $base   = (Get-AppxPackage -Name "*$_*").InstallLocation;
    $depend += $depend = (Get-AppxPackage -Name "*$_*").Dependencies.InstallLocation;
    };

$Apps = (($base + $depend) | Sort -Unique);
$Apps | %{Add-AppxPackage -Path "$_\Appxmanifest.xml" -Register -DisableDevelopmentMode};`

**Comment by adixon501** [comment]
Running Windows 10 Enterprise (build 18362.592)

i am getting the same error when launching the Windows Store. It crashes on initialization. I've tried all the PowerShell scripts out there for re-registering the app.

From the Event Viewer
```
Faulting application name: WinStore.App.exe, version: 12001.1001.5.0, time stamp: 0x5e2a5807
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.449, time stamp: 0xb90db728
Exception code: 0xc000027b
Fault offset: 0x0000000000712ec0
Faulting process id: 0x28fc
Faulting application start time: 0x01d5ddd7ee5b71bb
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsStore_12001.1001.5.0_x64__8wekyb3d8bbwe\WinStore.App.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: a847e41b-2367-47f4-93dd-d9a3c39d070e
Faulting package full name: Microsoft.WindowsStore_12001.1001.5.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

That error log is followed up with two identical events
```
Failure to write an application setting for package Microsoft.WindowsStore_8wekyb3d8bbwe. Error Code: -2147009080
```

**Comment by ranjeshj** [comment]
@adixon501 This is a very generic crash and from the event viewer information hard to figure out if this is the same issue as this bug. Could you collect a crash dump and share it to make this actionable ?

**Comment by adixon501** [comment]
> @adixon501 This is a very generic crash and from the event viewer information hard to figure out if this is the same issue as this bug. Could you collect a crash dump and share it to make this actionable ?

I just reset my pc. no more crash

**Comment by jshanzeng** [comment]
I'm on windows version 1809 (build 17763.1217) and I seem to be getting a similar error only when trying to launch the Alexa app. 

This is from Event Viewer:

Faulting application name: Alexa.exe, version: 1.0.0.0, time stamp: 0x5ebafaf8
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17763.1217, time stamp: 0x2df2c0ae
Exception code: 0xc000027b
Fault offset: 0x0000000000701f82
Faulting process id: 0x35e4
Faulting application start time: 0x01d63520ee1e73c3
Faulting application path: C:\Program Files\WindowsApps\57540AMZNMobileLLC.AmazonAlexa_2.11.410.0_x64__22t9g3sebte08\Alexa.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: ef5f660c-9f5f-4412-9ef9-4f766f41f350
Faulting package full name: 57540AMZNMobileLLC.AmazonAlexa_2.11.410.0_x64__22t9g3sebte08
Faulting package-relative application ID: App

Is there a quick fix to this?

**Comment by pajeroid** [comment]
I'm also getting this on a customers PC when they try and launch the Samsung Printer Experience app.

Faulting application name: PrinterApp.exe, version: 1.0.0.0, time stamp: 0x56ebdf42
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.815, time stamp: 0x9fa806f2
Exception code: 0xc000027b
Fault offset: 0x0000000000713530
Faulting process ID: 0x41e0
Faulting application start time: 0x01d638ce6d09188d
Faulting application path: C:\Program Files\WindowsApps\SAMSUNGELECTRONICSCO.LTD.SamsungPrinterExperience_1.3.15.0_x64__3c1yjt4zspk6g\PrinterApp.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report ID: 8e30020e-4f83-4a0c-a514-b6ca3d4c4200
Faulting package full name: SAMSUNGELECTRONICSCO.LTD.SamsungPrinterExperience_1.3.15.0_x64__3c1yjt4zspk6g
Faulting package-relative application ID: SamsungPrinterExperience

Any clues?

**Comment by codendone** [comment]
@jshanzeng and @pajeroid: Both of your crashes show Exception code: 0xc000027b, which means this is a [stowed exception crash](https://channel9.msdn.com/Shows/Inside/C000027B?term=stowed%20exception&lang-en=true).  There unfortunately isn't enough information in the text you provided to see the cause of a stowed exception crash.  (The "Report ID" _could_ be enough information, but it looks like Windows Error Reporting didn't save your crash report. If the report was uploaded, WER may have done a +1 to the appropriate crash bucket and didn't save anything else due to enough other hits in the bucket.)

For stowed exception crashes, you should be able to get more info on the crash by loading a crash dump in WinDbg and then using !pde.dse to dump the stowed exceptions.  !pde is available [here](https://onedrive.live.com/?authkey=%21AJeSzeiu8SQ7T4w&id=DAE128BD454CF957%217152&cid=DAE128BD454CF957) in the PDE*.zip.  (It is linked off the channel9 page above.)  Put the appropiate x64 or x86 dll in that zip in the winext directory of a WinDbg install, and then "!pde.dse" should work on stowed exception crash dumps.

Alternatively, if you can share a crash dump, I'll take a look.

**Comment by greek1979** [comment]
Hi all,
Please excuse me for crashing into the party, but it seems as MS Photos app crashing for me may be related to this problem. It all started yesterday after Windows force-upgraded itself (I guess...) to the latest 2004 release. Everything was working just fine before, and I never had any issues with Calculator, Photos, Feedback Hub, etc. WS apps. But now none of them runs. I managed to get the Store and Calc running again by uninstall and reset; this did not work for Photos, though. Keeps crashing without any reason:

```
Faulting application name: Microsoft.Photos.exe, version: 2020.19111.24110.0, time stamp: 0x5e7549b1
Faulting module name: KERNELBASE.dll, version: 10.0.19041.207, time stamp: 0x746c1866
Exception code: 0xc000027b
Fault offset: 0x000000000010b37c
Faulting process id: 0x2728
Faulting application start time: 0x01d63d1460bc66c3
Faulting application path: C:\Program Files\WindowsApps\Microsoft.Windows.Photos_2020.19111.24110.0_x64__8wekyb3d8bbwe\Microsoft.Photos.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: cebfa354-5b98-407b-b24a-408afdc7ebcc
Faulting package full name: Microsoft.Windows.Photos_2020.19111.24110.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

I have also captured a crash dump (never done it before, but after tweaking with Registry, it seems to work): https://1drv.ms/u/s!Ar1IzqW4JqTEgfonPnDwhEcYQOW2Qw?e=Hqvepe

P.S. Speaking of UI.Xaml, I could not either register or repair it - Windows does not find the package at all...

**Comment by codendone** [comment]
@greek1979 Thanks for sharing that dump. It looks like the Microsoft.UI.Xaml.Controls.XamlControlsResources couldn't be found, and Microsoft.UI.Xaml.dll isn't loaded like it should be, as if the framework package isn't properly installed. How did you check for the package?  If you run "get-appxpackage Microsoft.UI.Xaml.2.1" in a powershell, what does that show? (It should list two entries, one for x86 and one for x64.)

**Comment by greek1979** [comment]
Hi @codendone,
When checking for the Xaml.2.1 package, I get the following output (omitted the x86 part, it is exactly the same except the x86):

```
Name              : Microsoft.UI.Xaml.2.1
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 2.11906.6001.0
PackageFullName   : Microsoft.UI.Xaml.2.1_2.11906.6001.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.1_2.11906.6001.0_x64__8wekyb3d8bbwe
IsFramework       : True
PackageFamilyName : Microsoft.UI.Xaml.2.1_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

The weird thing is, I did not absolutely anything to my Windows 10 installation. It was working just fine, all Store apps, the one day, and after self-upgrading to 2004, none worked, crashing at the start with the same error (as viewed in Event Viewer). Apps > Reset or Apps > Repair did not help. It seems to me as some module has not registered itself after the system upgrade - but how to restore it? (creating new user a/c and copying all settings and file is not a good idea...)

**Comment by codendone** [comment]
@greek1979 Based on the package being there, it looks like the problem you're hitting is more fine-grained, such as perhaps a missing or corrupt file or bad regkey.  If you can run one of the failing apps, then post an issue in Feedback Hub as a "Problem" in category "Developer Platform" "App deployment", and finally provide the URL to the feedback item here, I'll forward that on to the appropriate team to hopefully debug the problem from the feedback data.

**Comment by greek1979** [comment]
Well... The problem with Feedback Hub I have is that it crashes, too. Generating a nice crash dump. Re-installing it does not help. (The Feedback Hub worked perfectly well before that damned 2004 Windows update) Ok, I will see whether the underlying issue can be workarounded or fixed somehow, and should I find a solution, will post it here. Although it smells for Windows 10 "Reset" option now.

**Comment by codendone** [comment]
@greek1979 Well that is unfortunate. Feedback Hub uses The Xaml 2.0 package, so it is interesting to see that apparently multiple versions are affected.  Would it be okay for me to email you a PowerShell script which would package most of the same logs as Feedback Hub, so you could then privately share those results?

**Comment by greek1979** [comment]
@codendone , yes, most certainly! You can use my email addressed attached to the GitHub account. Not sure if it can be seen; if not, it is leonid-at-hot-dot-ee.

**Comment by jenishngl** [comment]
I too am facing the same issue

Faulting application name: Todo.exe, version: 2.20.2006.10003, time stamp: 0x5ee0ad29
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17134.1098, time stamp: 0x5b0689cd
Exception code: 0xc0000409
Fault offset: 0x00000000004a6043
Faulting process id: 0x1220c
Faulting application start time: 0x01d64bb96c4cbbae
Faulting application path: C:\Program Files\WindowsApps\Microsoft.Todos_2.20.31623.0_x64__8wekyb3d8bbwe\Todo.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 3db862e0-730f-4b58-9db0-50713e126b10

**Comment by StephenLPeters** [comment]
@codendone did we get a resolution to this?

**Comment by codendone** [comment]
@jenishngl Your crash looks different, since it isn't a stowed exception (code 0xc000027b).  Unfortunately, it looks like your specific crash report isn't available in backend, so I can't see what you're hitting.  If Feedback Hub works for you, can you file a Feedback Hub item from the affected machine, then share an URL with the feedback hub link?  We can use that data to see what crash you're hitting.  Alternatively, if you'd like to share a crash dump, that would also work.

**Comment by jenishngl** [comment]
> @jenishngl Your crash looks different, since it isn't a stowed exception (code 0xc000027b). Unfortunately, it looks like your specific crash report isn't available in backend, so I can't see what you're hitting. If Feedback Hub works for you, can you file a Feedback Hub item from the affected machine, then share an URL with the feedback hub link? We can use that data to see what crash you're hitting. Alternatively, if you'd like to share a crash dump, that would also work.

Since I am using a laptop maintained by my employer, feedback hub doesn't work. Will try to send in the crash dump. Do you mind sharing me steps to capture the crash dump?

**Comment by codendone** [comment]
@jenishngl To capture crash dumps, especially for issues hit on process launch, I recommend setting some regkeys to tell Windows to save dumps, as described here: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps. Using the Full dump type is best.

**Comment by jenishngl** [comment]
Been busy at work and was not able to respond earlier.
A complete reinstall of windows fixed all my issues

**Comment by jkw** [comment]
Got this issue in Windows 10 Pro Insider Preview Build 20226.rs_prerelease.200925-1415. Shout if I can post any more useful info.

From logbook (Swedish):
```
Felet uppstod i programmet med namn: Calculator.exe, version 10.2009.4.0, tidsstämpel 0x5f777369
, felet uppstod i modulen med namn: Windows.UI.Xaml.dll, version 10.0.20226.1000, tidsstämpel 0x561516a5
Undantagskod: 0xc000027b
Felförskjutning: 0x0000000000880bcc
Process-ID: 0x4350
Programmets starttid: 0x01d6ae1a7bbfb559
Sökväg till program: C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.2009.4.0_x64__8wekyb3d8bbwe\Calculator.exe
Sökväg till modul: C:\Windows\System32\Windows.UI.Xaml.dll
Rapport-ID: 94c9394d-5b0c-4320-93bd-eafd4a18b029
Fullständigt namn på felaktigt paket: Microsoft.WindowsCalculator_10.2009.4.0_x64__8wekyb3d8bbwe
Program-ID relativt till felaktigt paket: App
```

**Comment by Jones-Bones** [comment]
Just to leave this out if anyone else searches this, re-registering/reinstalling XAML components helped in my case. From PowerShell execute:
`Get-AppxPackage *xaml* | %{Add-AppxPackage -Register "$($_.InstallLocation)\Appxmanifest.xml" -DisableDevelopmentMode -ForceApplicationShutdown}`

**Comment by Vascro** [comment]
I've been having the same issue on my Surface Pro X for months now. I submitted multiple feedback hub incidents as well as trying a reset on my pc. Unfortunately, this keeps happening. I am on Windows 11 and whenever I open settings and scroll all the way down system, settings completely crashes. This only happens when scrolling via the touchscreen or the typecover, not with a bluetooth mouse. No other part of the settings menu does this either.
I've attached 3 different logs of the issue; event viewer, text from a dmp file that I opened in windbg and ran !analyze -v, and the report archive. Hopefully one of these helps diagnose the issue.

[dmp export.txt](https://github.com/microsoft/microsoft-ui-xaml/files/7759176/dmp.export.txt)
[event viewer crash log.txt](https://github.com/microsoft/microsoft-ui-xaml/files/7759177/event.viewer.crash.log.txt)
[Report archive.txt](https://github.com/microsoft/microsoft-ui-xaml/files/7759178/Report.archive.txt)

**Comment by mudnug** [comment]
I have a lot of Mail and Calendar crashes and thought they were very buggy apps, but looking in my event log led me here.

@Jones-Bones If this is off topic, please forgive me. I tried running your script and 12-15 packages were processed, but eventually I got this error
`
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D06, The package could not be installed because a higher version of this package is         already installed.                                                                                                                                   Windows cannot install package Microsoft.Advertising.Xaml_10.1808.3.0_x64__8wekyb3d8bbwe because it has version 10.1808.3.0. A higher version        10.1811.1.0 of this package is already installed.                                                                                                    NOTE: For additional information, look for [ActivityId] b7a1140b-069f-0006-f3ed-a1b79f06d801 in the Event Log or use the command line                Get-AppPackageLog -ActivityID b7a1140b-069f-0006-f3ed-a1b79f06d801                                                                                   At line:1 char:28                                                                                                                                    + ...  *xaml* | %{Add-AppxPackage -Register "$($_.InstallLocation)\Appxmani ...                                                                      +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                              + CategoryInfo          : NotSpecified: (C:\Program File...ppxmanifest.xml:String) [Add-AppxPackage], Exception                                      + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand                                   `

If you expect only a slight modification will solve the issue, please let me know.

As a side note, I spend a lot of money on Microsoft subscriptions each month so it pains me to know that I'm apparently not even considered the customer. Instead it looks like I'm the product and their Advertising code seems to have broken my experience.
