### ISSUE TITLE
Application.UnhandledException strips Message and StackTrace

### ISSUE THREAD

**Issue by mattjohnsonpint** [microsoft/microsoft-ui-xaml#7160]
### Describe the bug

When the `Microsoft.UI.Xaml.Application.UnhandledException` event is raised, the exception it captures has no stack trace, and the message has reverted to the default message for the exception.  This makes it very difficult to determine the cause of an unhandled exception.

### Steps to reproduce the bug

```csharp
Microsoft.UI.Xaml.Application.Current.UnhandledException += (sender, e) => {
    var stackTrace = e.Exception.StackTrace;   // set a breakpoint and examine here
}
```

Then go throw an exception somewhere, such as in a button click.  Set a breakpoint and debug the app.

### Expected behavior

The stack trace should be populated.  Instead, it is `null`.

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Testing from within VS 2022 17.3.0 Preview 1.1 from within a MAUI app.

**Comment by mattjohnsonpint** [comment]
Also, it appears that while the exception message is available on `e.Message` (in the event args), it is *not* set on `e.Exception.Message`.  Only the default message string for the exception is coming through (for example, `"Exception of type 'System.Exception' was thrown.")

**Comment by mattjohnsonpint** [comment]
Just to make sure this wasn't a MAUI specific thing, I just created a brand new WinUI3 desktop app following [Create your first WinUI 3 project](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app). 

Then I went to the existing button handler in `MainWindow.xaml.cs` and modified it to throw an exception:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/1396388/170894713-1962845f-9861-44e5-8261-1a27bb610a13.png">

Then in `App.xaml.cs`, I hooked the `UnhandledException` event and set a breakpoint:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/1396388/170894750-25d8d2a0-a879-483f-b0ff-e18c3149d696.png">

Then I ran the app and clicked the button.  Visual Studio first stops at the exception itself. 
<img width="599" alt="image" src="https://user-images.githubusercontent.com/1396388/170894801-02a880d4-2129-4a7e-a754-f866e103c32f.png">

Clicking "View Details" brings up a quick watch on that exception, and you can see the message and stack trace are there like they should be.
<img width="731" alt="image" src="https://user-images.githubusercontent.com/1396388/170894827-226a0379-7358-4265-94de-b879b06195ee.png">

Then I click the green arrow button to continue.  VS stops at this generated code, which is annoying, but I can just click continue again.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/1396388/170894849-2071a213-d38f-4d22-b126-860b7cfe0b85.png">

Then finally it stops at the breakpoint I set in my `UnhandledException` handler.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/1396388/170894872-70524f19-5a34-4313-9483-1ec0b2572204.png">

Do a quick watch on `args` and you see the following:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/1396388/170894918-bf964b35-a5d3-4919-9845-fb9c27e1eb4c.png">

Notice that while `args.Message` has the correct `"Test Message"` from the original exception, `args.Exception.Message` has reverted to the default value of `"Exception of type 'System.Exception' was thrown."`

Also notice that `args.Exception.StackTrace` is `null`, as are several other properties of the exception.

**Comment by mattjohnsonpint** [comment]
A real hack of a workaround, but it seems while `AppDomain.UnhandledException` never fires, `AppDomain.FirstChanceException` does.  So I suppose I can do this:

```csharp
private Exception _lastFirstChanceException = null;

public App()
{
    this.InitializeComponent();

    AppDomain.CurrentDomain.FirstChanceException += (sender, args) =>
    {
        _lastFirstChanceException = args.Exception;
    };

    this.UnhandledException += (sender, args) =>
    {
        var exception = _lastFirstChanceException;
        // ... use that instead of args.Exception
    };
}
```

Though I'm not sure how well that will hold up under multi-threading.  Can I trust that the last first chance exception is indeed the same one that I want in the unhandled exception handler?  I'm not sure.

**Comment by mattjohnsonpint** [comment]
FYI - I also tried in a UWP application and it works fine, so the issue is specific for WinUI 3.

**Comment by Scottj1s** [comment]
App.UnhandledException fix will be available in Windows App SDK 1.2 Preview 2.

**Comment by terrycox** [comment]
This doesn't appear to be fixed in preview 2 and we're running out of time.

**Comment by mattjohnsonpint** [comment]
I just tested this again, and it appears to be working now.

![image](https://user-images.githubusercontent.com/1396388/226748825-ab40592e-6b14-418b-a51f-8d4dc67be2b1.png)

I have the latest Windows App SDK Version 1.2.5 (1.2.230313.1).  I'm not sure specifically which version it was fixed in, as it's not mentioned [in the release notes](https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel) and I hadn't tested previous versions before upgrading.  Not sure how to effectively downgrade to test older versions either.  But anyway, it does work now.  Thanks!

**Comment by tipa** [comment]
@mattjohnsonpint given the bug is fixed in the WinAppSDK now, wouldn't it possible to remove the introduced `FirstChanceException`-hack from the SDK again?

**Comment by mattjohnsonpint** [comment]
> @mattjohnsonpint given the bug is fixed in the WinAppSDK now, wouldn't it possible to remove the introduced `FirstChanceException`-hack from the Sentry SDK again?

Perhaps. I don't work there presently. Maybe @jamescrosswell would like to take a look.
