### ISSUE TITLE
WinUI Design Toolkit Bug: [Flyout closing event issue]

### ISSUE THREAD

**Issue by FrancescoCarraro** [microsoft/microsoft-ui-xaml#7167]
## WinUI Toolkit Bug Report
Flyout closing event is raised even if flyout is hidden. this is a non-sense

**Version Info:**
7.1.2

**Comment by alejo4000** [comment]
Removed tags for WinUI Toolkit and design, changed title to reflect. This looks like a code bug, not a bug with the design toolkit.
