### ISSUE TITLE
Question: WinUI 3 App SDK 1.1 :: what is the default icon set shipped ? 

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#7168]
I reckon[ this is ](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font)not the default icon set available in WinUI 3 1.1 currently . Which one is the default available set and will you enrich this set in the future ? If not, which additional ones do you recommend as Nuget package addon ?

**Comment by dongle-the-gadget** [comment]
It is the official app icon set for Windows 11.
If you are using `SymbolIcon`, it should use the new icons automatically.
If you are using `FontIcon`, then you need to change the `FontFamily` property.

**Comment by bpulliam** [comment]
Closing the issue for questions answered a while ago.
