### ISSUE TITLE
WinUI3 - Unable to call method on host object with parameters

### ISSUE THREAD

**Issue by rsegner** [microsoft/microsoft-ui-xaml#7170]
### Describe the bug

When a host object is added to an instance of WebView2 as outlined in #4377 we are unable to call methods on the host object with parameters. The output to the JS console is `Error: The parameter is incorrect.`

### Steps to reproduce the bug

1. Create a WinUI 3 project (either UWP or Desktop)
2. Follow https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript
3. Add host object using the `ICoreWebView2Interop` interface as outlined in #4377 
4. Call a method on the host object, passing in a primitive type

Example Repo: https://github.com/rsegner/WinUi3WebViewTest/tree/main/WinUI3WebViewTest

### Expected behavior

The method should return the expected result based on the input parameter

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [X] UWP
- [ ] Win32

### Windows version

Windows 10 (21H2): Build 19044

**Comment by krschau** [comment]
There's a .Net IDispatch bug that's causing this not to work. There's a fix when using WebView2 in .Net, but it's not available for WinRT yet. Until it is, I suggest using WinRT code as described in the article [Call native-side WinRT code from web-side code](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=csharp). 
That article focuses on OS provided APIs, to use your own WinRT APIs please see 
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2529#issuecomment-1163490872

**Comment by rsegner** [comment]
@krschau I was able to get this working perfectly in a UWP app as specified by the documentation, however am having some trouble with a WinUI3 project. Any pointers?

**Comment by krschau** [comment]
@rsegner Trying it out myself in WinUI 3, I'm not seeing the WebView2 properties page after installing WebView2 into the WinRTAdapter project. Is that what you're hitting? I'll ask the Edge folks about what's happening there.

**Comment by rsegner** [comment]
@krschau any luck yet? I was able to create a WinUI3 C# class library referencing the Windows SDK along with WinRT, however in order to get the wv2winRT tool working I also needed to reference the preview of webview2. This causes a dependency error in the main application.

**Comment by krschau** [comment]
@rsegner Sorry for the delay! I now have a working example: https://github.com/krschau/WinUI-WebView2-Samples/tree/master/NativeWebWinUI3App

I'm going to write up actual instructions, and get it into the [tutorial](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js) linked above, but I wanted to at least get the working example to you asap. If you look at the [commit history](https://github.com/krschau/WinUI-WebView2-Samples/commits/master/NativeWebWinUI3App), I broke the commits down by each step in the tutorial so you should be able to kind of follow along. The two last steps are the big departures from the WinUI 2 instructions: adding the cswinrt reference, and updating the csproj with CsWinrtInclude and updating to WinAppSDK 1.1.

**Comment by rsegner** [comment]
That's excellent news, thanks @krschau, I will give it a go

**Comment by rsegner** [comment]
Thanks @krschau, that is great, however, this still doesn't work for custom types. 

If I try to add a new windows runtime component to the solution and reference it in the WinRTAdapter, I get the following error:
![image](https://user-images.githubusercontent.com/6117848/182812848-2af93fc7-becb-4a3f-aa7e-594074d04f1f.png)

And If I try to add a simple class library that references the WinRTCS library I get:
![image](https://user-images.githubusercontent.com/6117848/182813116-31c8d574-7820-4982-b6b3-ceb122eeb79a.png)

**Comment by krschau** [comment]
@rsegner I added a custom cppwinrt component to my [example](https://github.com/krschau/WinUI-WebView2-Samples/tree/master/NativeWebWinUI3App). There's a [new section](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=csharp#custom-3rd-party-winrt-components) in the "Windows Runtime components with C++/WinRT" doc that was helpful, and then I also used part of [this one](https://docs.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component). There's a little more detail in my project's README. Hopefully this helps.

**Comment by rsegner** [comment]
Thanks for the example @krschau. 

What I am wanting to do is create a WinUI3 class library that can reference the WindowsAppSDK and expose methods to the WebView. I have done a lot of experimentation around this and found that it may not be currently possible as the WinRT.Runtime.dll is referenced both by WindowsAppSDK and CSWinRT. I end up with an error like:

`Payload contains two or more files with the same destination path "WinRT.Runtime.dll`

Is there a way I can create a C# WinUI3 class library containing objects that I can provide as a host object to webview2, which still has access to the APIs exposed by WindowsAppSDK?

**Comment by rsegner** [comment]
@krschau Please see this example repo: https://github.com/rsegner/WebViewWinRTTest

Here I am trying to create a WinUI3 class library, referenced by a WinUI3 application including a WinRTAdapter. It builds successfully however I get a `Member not found` at runtime.
