### ISSUE TITLE
NavigationView does not resize correctly when it has hierarchical FooterMenuItems

### ISSUE THREAD

**Issue by KubaSzostak** [microsoft/microsoft-ui-xaml#7171]
### Describe the bug

`NavigationView` does not resize correctly when it has hierarchical `FooterMenuItems` and the navigation item is expanded or collapsed.

### Steps to reproduce the bug

1. In VisualStudio 2022 (17.2.2) create new project - `Blank App, Packaged (WinUI 3 in Desktop)` .

2. Add code to MainWindow.xaml file

```xaml
<Window
    x:Class="NavigationViewBug.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    
    <NavigationView x:Name="NavView" IsSettingsVisible="False"  >
        
        <NavigationView.MenuItems>
            <NavigationViewItem Content="Home" Icon="Home" Background="LightYellow" />
            <NavigationViewItem Content="Mail" Icon="Mail" />
            <NavigationViewItem Content="Calendar" Icon="Calendar"/>
        </NavigationView.MenuItems>

        <NavigationView.FooterMenuItems>
            <NavigationViewItem Content="Settings" Icon="Setting" Background="LightCyan" SelectsOnInvoked="False">
                <NavigationViewItem.MenuItems>
                    <NavigationViewItem Content="Connection" Icon="MapDrive"  Background="LightCoral"/>
                    <NavigationViewItem Content="Permissions" Icon="Permissions"  Background="LightSkyBlue"/>
                    <NavigationViewItem Content="Language"  Icon="Character"  Background="LightPink"/>
                </NavigationViewItem.MenuItems>
            </NavigationViewItem>
        </NavigationView.FooterMenuItems>

    </NavigationView>
    
</Window>
```

3. Run the project
4. Click the _Settings_ button  
    [`FooterMenuItems` container will not expand]
5. Resize the window
    [Now `FooterMenuItems` container will expand correctly]
6. Click the _Settings_ button again
    [`FooterMenuItems` container will collapse correctly, but `MenuItems` container will lost its position]
7. Resize the window again
    [`FooterMenuItems` and `MenuItems` containres got proper size and position again]

### Expected behavior

`FooterMenuItems` and `MenuItems` containers have proper size and position when expanding nested footer menu items.

### Screenshots

![NavigationView-Bug](https://user-images.githubusercontent.com/4609437/171147014-59bb1f44-598e-494f-8b08-e7fba26fab03.gif)

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Temporary solution for this issue:

```cs
private void NavView_ItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args)
{
    NavView.DispatcherQueue.TryEnqueue(DispatcherQueuePriority.High, () => { 
        NavView.Height = NavView.ActualHeight - 1;
        NavView.UpdateLayout();
    });
    NavView.DispatcherQueue.TryEnqueue(DispatcherQueuePriority.Low, () => {
        NavView.Height = double.NaN;
        NavView.UpdateLayout();
    });
}
```

**Comment by minze-it** [comment]
Hey there,
we found that this behaviour can also be reproduced in a maximized app on a tablet pc (i.e. surface pro) when rotating the device from landscape to portrait or vice versa which increases the impact dramatically.
Just wanted to mention that.
