### ISSUE TITLE
Stack trace does not give line number of offending code

### ISSUE THREAD

**Issue by sam-wheat** [microsoft/microsoft-ui-xaml#7172]
### Describe the bug

See https://github.com/CommunityToolkit/dotnet/issues/282

Address questions to @michael-hawker

### Steps to reproduce the bug

See https://github.com/CommunityToolkit/dotnet/issues/282 which contains steps to reproduce and an example project.

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by ojhad** [comment]
The stack trace in question is from WPF, please file this issue in that repo: https://github.com/dotnet/wpf/issues
