### ISSUE TITLE
Can neither build, cancel build, or exit VS 2022 Preview after setting Windows API 7 as target for MAUI project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#7178]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Can-neither-build-cancel-build-or-exit/10054681)._

---
[severity:It's more difficult to complete my work]
![image.png](https://aka.ms/dc/image?name=B4d55ffd9e49f4a48a65d3ccd12d7a8a6637891681202029041_20220526-082159-image.png&tid=4d55ffd9e49f4a48a65d3ccd12d7a8a6637891681202029041)
![image.png](https://aka.ms/dc/image?name=B208fb966fb144c17899bc738be3d5101637891681336693263_20220526-082213-image.png&tid=208fb966fb144c17899bc738be3d5101637891681336693263)
![image.png](https://aka.ms/dc/image?name=B07e3f78414e34374bf615c7e0536c8f6637891681560459350_20220526-082235-image.png&tid=07e3f78414e34374bf615c7e0536c8f6637891681560459350)
![image.png](https://aka.ms/dc/image?name=Bc8d5439a2d364b8ea4d3b2f216d51d89637891681881353185_20220526-082307-image.png&tid=c8d5439a2d364b8ea4d3b2f216d51d89637891681881353185)
![image.png](https://aka.ms/dc/image?name=B20d312de5a554344ae0ba050ab6749f2637891682048465220_20220526-082324-image.png&tid=20d312de5a554344ae0ba050ab6749f2637891682048465220)

When working in my .NET MAUI project in 17.3.0 Preview 1.1, I decided to test Windows targeting compatibility.  I set the Applicaton > Windows Targets >"Target Windows Framework" setting in project properties to net6.0-windows7.0.  After doing this, my build is in some indeterminate and bugged state.  The icon on the bottom of the screen shows the "building" state.  When I navigate to the "Build" menu, I cannot cancel the build.  Starting a new build gives a "Catastrophic failure" error.  I cannot exit Visual Studio normally, as "The build must be stopped before the solution can be closed."

---
#### Feedback Bot on 5/26/2022, 11:17 PM: 

(private comment, text removed)
#### Winnie zhang (CSI Interfusion Inc) [MSFT] on 5/30/2022, 07:57 PM: 

(private comment, text removed)
#### Seth Ficke on 5/31/2022, 06:44 AM: 

(private comment, text removed)
#### Winnie zhang (CSI Interfusion Inc) [MSFT] on 5/31/2022, 11:09 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by krschau** [comment]
The WinAppSDK does not support Windows 7, so it's expected that things don't work. 
We would expect this scenario to raise the following error:
`1>C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(188,5): error NETSDK1135: SupportedOSPlatformVersion 10.0.19041.0 cannot be higher than TargetPlatformVersion 7.0.1`,
so the WinAppSDK probably hasn't even come into play yet when you see the E_UNEXPECTED HRESULT error. 

If you're seeing similar errors on a supported platform, the Visual Studio team would be more equipped to examine the correlated logs and dumps.

**Comment by Babushka001** [comment]
I just had this exact same issue.
1. start VS2022 17.3.3
2. new MAUI app template
3. build starts automatically....but never stops (note I don't have android simulator or any device other than my windows PC
4. I stop the build
5. I go to the project settings and disable all platforms other than windows
6. start build. You get the Catastrophic failure" error

build stops (apparently). cannot close vs (get build must be stopped) but there is no building going on. Cannot run project -> this gives another error ("Cannot start debugging" "cannot be launched.)

This issue persists. Why was it closed. How is MAUI production-ready if a clean VS install with .net 6 and MAUI cannot start its own template?!
