### ISSUE TITLE
How to link WinUI library

### ISSUE THREAD

**Issue by AghaKhan** [microsoft/microsoft-ui-xaml#7180]
I have successfully created a library with Windows SDK and WinUI desktop, and it works fine. The visual Studio 2022 give an option to add Project Reference where I added library refence to my project. It works fine. Now I like to share this library to other people. I created new project and created a folder Controls and placed WinUIControls.dll in that folder. Also try to add Project Reference to my application, but it is not a project. There is a browse button and so I browsed and selected WinUIControls.dll. As a result, a small triangle appears (Debug mode) on Assembles sign of trouble, but it compiles but Run time it crashes. I placed full video and project to look at it.[https://1drv.ms/u/s!AtjIdnVOoJXtpZ9TA73TpnxJC4fRLg?e=wrciMm](url)

**Comment by MEK3DK** [comment]
The short answer is that you can't do it.
One of the reasons why WinUI is not really usefull for real world applications yet.

It has been mentioned in many bugs in here, but there does not seem to be any focus on the problem: [WinUI 3 Cant instantiate a UserControl](https://github.com/microsoft/microsoft-ui-xaml/issues/6299)

**Comment by AghaKhan** [comment]
WOW, Thank you. Thank you and Thank you
