### ISSUE TITLE
Question: Language switch

### ISSUE THREAD

**Issue by Pupka-Lipinski** [microsoft/microsoft-ui-xaml#7182]
we would like to implement a language switch, so that the user is able to switch the needed language in the application.

For this i set ` Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride`, but it change only the language on application restart. 
Is there a way to force reload the screen / window?

attached is my demo project
[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8829864/App1.zip)
.

**Comment by krschau** [comment]
I believe this behavior is expected. See this description in the [ApplicationLanguages.PrimaryLanguageOverride Property](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.applicationlanguages.primarylanguageoverride?view=winrt-22621#remarks) API doc:

> When you set the PrimaryLanguageOverride, this is immediately reflected in the [ApplicationLanguages.Languages](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.applicationlanguages.languages?view=winrt-22621#windows-globalization-applicationlanguages-languages) property. However, this change may not take effect immediately on resources loaded in the app UI. To make sure the app responds to such changes, you can listen to the [QualifierValues](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.resources.core.resourcecontext.qualifiervalues?view=winrt-22621#windows-applicationmodel-resources-core-resourcecontext-qualifiervalues) property on a default resource context and take whatever actions may be needed to reload resources. Those requirements may vary depending on the UI framework used by the app, and it may be necessary to restart the app.

Then, you can reload your strings from the default ResourceContext. There's an example in [Updating strings in response to qualifier value change events](https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest#updating-strings-in-response-to-qualifier-value-change-events) that should be helpful.

Hope this helps!

**Comment by Pupka-Lipinski** [comment]
Thanks for the response. 
I also found those article earlier but the issue is how to reset the resource container.
Unfortunately winui 3 is not based on WindowsCore. [Core unsupported classes](https://docs.microsoft.com/de-de/windows/apps/desktop/modernize/desktop-to-uwp-supported-api)

So that each time i try to get the `Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView()` i get the exception "RPC_E_WRONG_THREAD", Even if i use the dispatcher and dispatcherqueue.

So question is is there a way in winui 3 to reset the ResourceContext to that my page is able to reload?

**Comment by krschau** [comment]
I see, sorry about missing the UWP/WinUI3 difference here. From the [MRT to MRT Core migration](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/mrtcore) doc, are you able to use the
`Microsoft.Windows.ApplicationModel.Resources.ResourceManager.CreateResourceContext()` API
rather than
`Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView()`?

And this version of the [ResourceLoader](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applicationmodel.resources.resourceloader?view=windows-app-sdk-1.1)?
`Microsoft.Windows.ApplicationModel.Resources.ResourceLoader `

**Comment by Pupka-Lipinski** [comment]
So far i see there is no option to reset / reinit the ResourceManager or the ResourceContext.
The current issue is that i set the language to a different one with `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride`, but the app is not updating. 

I also figured out that this only happens with the xaml x:uid markup.
`<TextBlock  x:Uid="TestTextBlock" />`

Is there an option to reset the resource so that the UI is updating to the other language ?

**Comment by AndrewKeepCoding** [comment]
You can try the [WinUI3Localizer](https://github.com/AndrewKeepCoding/WinUI3Localizer): 
- Switch languages without app restarting
- You/users can edit localized strings even after deployment
- You/users can add new languages even after deployment
- Use standard Resources.resw (see [Microsoft docs](https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest))

**Comment by MarcoOliveira2** [comment]
You solved this problem? @Pupka-Lipinski

**Comment by Pupka-Lipinski** [comment]
@MarcoOliveira2 : 
all you need to do is:
 - set Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride
 - reload you page frame.Navigate(frame.CurrentSourcePageType);

**Comment by MarcoOliveira2** [comment]
I change to:

```
private async void Lang_PT(object sender, RoutedEventArgs e)
{
     ApplicationLanguages.PrimaryLanguageOverride = "pt";
     Type t = ContentFrame.Content.GetType();
     ContentFrame.Navigate(t);
}

```

Still the same problem :/

**Comment by lostluna1** [comment]
> 我为此发布了一个 NuGet 包。
> 
> [WinUI3Localizer](https://github.com/AndrewKeepCoding/WinUI3Localizer)：
> 
> * 在不重新启动应用程序的情况下切换语言
> * 您/用户即使在部署后也可以编辑本地化字符串
> * 您/用户即使在部署后也可以添加新语言
> * 使用标准 Resources.resw（请参阅 [Microsoft 文档](https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest))



> I have published a NuGet package for this.
> 
> [WinUI3Localizer](https://github.com/AndrewKeepCoding/WinUI3Localizer):
> 
> * Switch languages without app restarting
> * You/users can edit localized strings even after deployment
> * You/users can add new languages even after deployment
> * Use standard Resources.resw (see [Microsoft docs](https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest))

It perfectly solved my problem, so that I didn't need to consult the poor and even unknown WinUi documentation
