### ISSUE TITLE
Detect keystrokes and mouse right click 

### ISSUE THREAD

**Issue by LazieWouters** [microsoft/microsoft-ui-xaml#7183]
Hi, I haven't found any sample codes showing how to detect if a key is pressed or if the mouse was right clicked.
Are those functions supported in WinUI 3?

**Comment by castorix** [comment]
There are events like _UIElement.KeyDown_ or _UIElement.PointerPressed_ (_PointerPointProperties.IsRightButtonPressed_)
or with Win32 Hooks (_SetWindowsHookEx_),  or inside _CompositionTarget_Rendering_ with _GetKeyState_ (like I did in the last sample I posted to exit Fullscreen with Escape)

**Comment by LazieWouters** [comment]
> 

Thanks.

I was able to capture the key using the second code below. The first sometimes works, sometimes it doesn't. I don't know why the code has this behavior.
Maybe there is some better way than this solution I found.

Now I'm looking for more information about UIElement.PointerPressed.

Thank you for the tips

```
if (Microsoft.UI.Input.KeyboardInput.GetKeyStateForCurrentThread(VirtualKey.LeftControl) == CoreVirtualKeyStates.Down)
                  //do something
```

               ```
 if (Microsoft.UI.Input.KeyboardInput.GetKeyStateForCurrentThread(VirtualKey.LeftControl).HasFlag(CoreVirtualKeyStates.Down))
                {
                    //do something
                    Microsoft.UI.Input.KeyboardInput.GetKeyStateForCurrentThread(VirtualKey.LeftControl).HasFlag(CoreVirtualKeyStates.None);
                }
```
