### ISSUE TITLE
NavigationViewItem Visibility not changing from Collapsed to Visible

### ISSUE THREAD

**Issue by bogdan-patraucean** [microsoft/microsoft-ui-xaml#7186]
### Describe the bug

A **NavigationViewItem** placed in **FooterMenuItems** section with the **Visibility** set to **Collapsed** by default, and then changed at runtime via code behind or binding to **Visible**, will **not be** displayed until the Pane Toggle Button is pressed. 

There is a weird animation playing, so it looks like the item tries to appear but the **MenuItems** section prevent this from happening. If there is no item placed in the **MenuItems** section the footer item will be displayed correctly.

This was tested both with WinUI **3** (WASDK) and WinUI **2.7** (UWP), both versions presenting the same behaviour.

### Steps to reproduce the bug

1. Create a new app (WASDK -> WinUI 3 / UWP -> WinUI 2.7)
2. Add a **NavigationView**
3. Add a **NavigationViewItem** in **MenuItems** section (_otherwise will work_)
4. Add a **NavigationViewItem** in **FooterMenuItems**, with **Visibility** set to **Collapsed**
5. Add a Button with a Click handler (I chose to add it in the ContentOverlay section of the NavigationView for simplicity)
6. In the Click handler set the Footer Item's Visibility to Visible
7. Notice that the item will not be displayed :(
8. Press Pane Toggle Button and the item will appear / remove the Item from MenuItems section  and the item will appear.

**MainWindow.xaml**
_______________________

```
<Grid>
        <NavigationView IsPaneOpen="False">
            <NavigationView.ContentOverlay>
                <Button Content="Display Footer Item" Click="Button_Click" HorizontalAlignment="Center"></Button>
            </NavigationView.ContentOverlay>
            <NavigationView.MenuItems>
                <NavigationViewItem Content="Health">
                    <NavigationViewItem.Icon>
                        <FontIcon FontFamily="{StaticResource SymbolThemeFontFamily}" Glyph="&#xe95e;"/>
                    </NavigationViewItem.Icon>
                </NavigationViewItem>
            </NavigationView.MenuItems>
            <NavigationView.FooterMenuItems>
                <NavigationViewItem x:Name="FooterItem" Content="FooterItem"  Visibility="Collapsed">
                    <NavigationViewItem.Icon>
                        <FontIcon FontFamily="{StaticResource SymbolThemeFontFamily}" Glyph="&#xe90f;"/>
                    </NavigationViewItem.Icon>
                </NavigationViewItem>
            </NavigationView.FooterMenuItems>
        </NavigationView>
    </Grid>
```

**MainWindow.xaml.cs**
___________________________

```
private void Button_Click(object sender, RoutedEventArgs e)
{
     FooterItem.Visibility = Visibility.Visible;
}
```

### Expected behavior

Footer Menu Items **should be displayed** when changing the Visibility to Visible using code behind or binding.

### Screenshots

https://user-images.githubusercontent.com/26826125/171994661-0cfd86b7-40d6-4df3-a528-c4b92db8a133.mp4

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [x] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by KubaSzostak** [comment]
Seems to be related to #7171

**Comment by bogdan-patraucean** [comment]
UP. This issue should not be part of https://github.com/microsoft/microsoft-ui-xaml/discussions/8638.
