### ISSUE TITLE
Windows APP SDK 1.1.0 Drag and Drop Crash still present

### ISSUE THREAD

**Issue by shane-vorwerk** [microsoft/microsoft-ui-xaml#7192]
### Describe the bug

After a certain amount of repetitive drag and drop operations, the application will simply crash.  This may be anything between 1 and about 60 repetitions. There is no way to recover from the crash and the application simply disappears.  

Debugging in Visual Studio 2022 stops with and Unhandled Exception. The application has crashed at this point and shuts down.  There is also no way to debug this now as can be seen from the two screenshots.

Unfortunately this means that the application I am developing cannot be released to end users as the core SDK is unstable and there does not seem to be a work around for this issue.

### Steps to reproduce the bug

Please see #7007  and #7002. This bug and related bugs have been reported many times. It is very concerning that this crash is still present after more than a year of development. 

### Expected behavior

Application continues running and unlimited drag and drop operations can be performed.

### Screenshots

![image](https://user-images.githubusercontent.com/74031723/172086226-4411c721-3ff4-4703-8834-0114f431b6a5.png)
![image](https://user-images.githubusercontent.com/74031723/172099520-4b021f55-448e-4220-9dfc-dcaf3a401cb2.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by sudongg** [comment]
The 1.1 stable version still can not be used in production.
Is this really the native SDK of windows?

**Comment by wbokkers** [comment]
I see instant crashes as soon as I drag/drop something from outside the app onto the app. Drag/drop from inside the app still works in our app.

**Comment by shane-vorwerk** [comment]
> I see instant crashes as soon as I drag/drop something from outside the app onto the app. Drag/drop from inside the app still works in our app.
> 
> This is a regression from 1.0.3 where drag/drop works quite stable (at least in Windows 11).

@wbokkers  I am also working on Windows 11 and with the  most up to date released version of Visual Studio 17.2.3. As I said in my comment in #7203 I can consistently recreate the bug. And as you can see from the screen shots included here I cannot even get a debug output for the error any more - earlier versions of Visual Studio 17.1.x  showed the error as described in #7007.  The important issue is that  the number of times a DnD operation needs to be repeated before the crash happens is a bit random (usually close to 60). Sometimes you think it is working fine and so keep going and suddenly the application  crashes. So if you do 10 - 15 repetitions you will think it is working fine but that has just not reach the threshold that triggers the crash.

**Comment by wbokkers** [comment]
@shane-vorwerk Than it's even worse than I expected.😢

**Comment by shane-vorwerk** [comment]
> @shane-vorwerk Than it's even worse than I expected.😢

@wbokkers I would be interested to know if you can reproduce this crash  in your app - that is dragging elements internally.

**Comment by wbokkers** [comment]
And even in Windows App SDK 1.1.1 this crash is still present.  https://github.com/microsoft/microsoft-ui-xaml/issues/7007#issuecomment-1157447916

As far as our app is concerned 1.1.1 does nothing to solve D&D crashes and even adds some more.

**Comment by shane-vorwerk** [comment]
> And even in Windows App SDK 1.1.1 this crash is still present. [#7007 (comment)](https://github.com/microsoft/microsoft-ui-xaml/issues/7007#issuecomment-1157447916)
> 
> As far as our app is concerned 1.1.1 does nothing to solve D&D crashes and even adds some more.

@wbokkers  I have tested it out myself again - it is partially fixed as far as I can see. But if you are using the DragStartingEventArgs  Data.Properties to pass data to the drop target element  which receives DragEventArgs  and you access the passed data via the DataView, it will still crash. I implemented my own as a work around. But it looks like I will also need to test this all further to be sure.

**Comment by wbokkers** [comment]
@shane-vorwerk I use Data.Properties in some situations, but in most cases it will not crash. What do you use as a work around? I am using a global helper to store most d&d data for the current operation. This solved most crashes. Maybe I can do more here.

**Comment by wbokkers** [comment]
In the WinUI Community Call it was mentioned that d&d issues are related to timing and lifetime issues between WinRT and WinUI. Hopefully this is not an indication that these issues will never really go away due to a way too complex implementation/architecture.

**Comment by shane-vorwerk** [comment]
> @shane-vorwerk I use Data.Properties in some situations, but in most cases it will not crash. What do you use as a work around? I am using a global helper to store most d&d data for the current operation. This solved most crashes. Maybe I can do more here.

@wbokkers  I modified the code from #7007 to add in Data.Properties/DataView - with that I got to about 30 repetitions before the app crashed - without it I could go well beyond 100 repetitions and it seemed stable to me.  

For my workaround I have excluded any Data.Properties/DataView use and just used a global class to hold the data like you have.

**Comment by wbokkers** [comment]
@shane-vorwerk If we use workarounds, and base our feedback on code with workarounds, Microsoft will never be able to fix the issues completely. 

To @bpulliam, @codendone, and others, can you please test full examples, including the proper use of Data.Properties/DataView with all possible scenario's (text, bitmaps, files, ..., using C++, using C#) before considering a fix 'done'?

**Comment by shane-vorwerk** [comment]
@wbokkers  I agree, I only need the work around for the main app precisely because the SDK is so unstable.  All my tests/feedback only use the SDK itself.  Microsoft needs to make this properly stable. I have used everything from MCF(C++) to UWP (C#) and all have been stable platforms to work with. This is the first SDK that is so unstable.

**Comment by Scottj1s** [comment]
fix is now available in Windows App SDK 1.2 Preview 1

**Comment by amercer-fdi** [comment]
This is still happening in version 1.3230331000. NuGet package "Microsoft.WindowsAppSDK".

![image](https://user-images.githubusercontent.com/61432947/235824222-99c0f50c-23ad-46f5-8511-70d3f33e6270.png)

![image](https://user-images.githubusercontent.com/61432947/235824440-9d973ffd-d141-4108-87e6-2098cc5e6e28.png)

It's intermittent. Sometimes it works the first time and fails the second time, fully crashing the program.

**Comment by amercer-fdi** [comment]
> fix is now available in Windows App SDK 1.2 Preview 1

@Scottj1s, this is still happening in version 1.3230331000. NuGet package "Microsoft.WindowsAppSDK".

![image](https://user-images.githubusercontent.com/61432947/235824222-99c0f50c-23ad-46f5-8511-70d3f33e6270.png)

![image](https://user-images.githubusercontent.com/61432947/235824440-9d973ffd-d141-4108-87e6-2098cc5e6e28.png)

It's intermittent. Sometimes it works the first time and fails the second time, fully crashing the program.

**Comment by Scottj1s** [comment]
@amercer-fdi Thanks for the report, we'll investigate further
