### ISSUE TITLE
Debug_test x86 configuration fails to build

### ISSUE THREAD

**Issue by chrisglein** [Microsoft/microsoft-ui-xaml#72]
**Describe the bug**
When selecting the Debug_test x86 configurations from the project the build fails.

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | The   "CreatePriFilesForPortableLibraries" task was not given a value for   the required parameter "IntermediateExtension". | MUXControlsTestApp   (test\MUXControlsTestApp\MUXControlsTestApp) | C:\Program Files (x86)\Microsoft Visual   Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets | 1275 |  

**Steps to reproduce the bug**
1. Set configuration to `Debug`
2. Set platform to `x86`

**Expected behavior**
It builds? Also, it's probably no clear what "Debug_test" is needed for.

**Comment by jevansaks** [comment]
@ranjeshj did you already send out the PR for this one?

**Comment by ranjeshj** [comment]
Yes this is already fixed.
