### ISSUE TITLE
Acrylic does not work if mica is enabled

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#7200]
### Describe the bug

When mica is enabled, acrylic surfaces do not render correctly, as can be seen here with a dropdown menu:

![image](https://user-images.githubusercontent.com/38145893/172337144-d4d4b7af-cdf9-4b42-bda7-b39c8abfcda9.png)

In comparison, with mica disabled:

![image](https://user-images.githubusercontent.com/38145893/172337184-32c174d1-1407-4798-9d51-7231211da429.png)

### Steps to reproduce the bug

1. Create a window with mica background and add some controls like a dropdown menu or combo box

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by krschau** [comment]
@codendone Is this known?

**Comment by seven-mile** [comment]
Will a fix for this be available in the coming servicing update?

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.1.5` has been released which fixes this issue.
		
Handy links:
* [Release Notes](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-115)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.1.5)
