### ISSUE TITLE
Update of Single-project MSIX Packaging Tools for VS 2022 breaks VS2022.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#7204]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Update-of-Single-project-MSIX-Packaging-/10061785)._

---
I installed the update released today (Jun 3). None of my extensions could work after the update. This is the second time in a row that installing an update of an extension cause VS2022 to stop functioning! The previous time I had to reset VS2022 for it to work. I hope this will happen again.

---
#### Feedback Bot on 6/5/2022, 08:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ojhad** [comment]
Closing due to not enough info for repro. Seems to me that this might not be the correct location for this issue.
