### ISSUE TITLE
Microsoft.UI.Xaml compatibility issues

### ISSUE THREAD

**Issue by 10Develops** [microsoft/microsoft-ui-xaml#721]
I want compatibility for my app on all Windows 10 versions, but use fluent design when Anniversary Update or above. However, the Microsoft.UI.Xaml NuGet package throwing Target version error, which I solved with SkipMicrosoftUIXamlCheckTargetPlatformVersion tag. But now I still getting errors now from Visual Studio, how to skip that?

> Error: Your application is taking a dependency on a framework package that has a TargetPlatformMinVersion that is higher than what your app is depending on. Change your app manifest to make sure the TargetPlafromMinVersion of your app’s dependencies is greater than or equal to the framework’s TargetPlatformMinVersion. TargetPlatformIdentifier: 'Windows.Universal'. Application's TargetPlatformVersion: '10.0.10240.0'. Dependent framework's TargetPlatformVersion: '10.0.14393.0'.

**Comment by YuliKl** [comment]
@10Develops - at the moment, as the [read me describes](https://github.com/microsoft/microsoft-ui-xaml#version-support), our NuGet package is supported on Windows versions 14393 or greater. As the error you're seeing indicates, your app is targeting version 10240, which is less than 14393. Unfortunately, what you're trying to do is not currently possible.

Please take a look at our [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md) and comment in #717 with additional concerns.
