### ISSUE TITLE
Can't add WinUI page in "Add new Item" page

### ISSUE THREAD

**Issue by JIHOON2087-LEE** [microsoft/microsoft-ui-xaml#7211]
I created the WinUI3 project and
I tried to add a page for WinUI3 in "Add new Item" dialog, but I can't find any item/template for WinUI3.

**Comment by EddieLotter** [comment]
I suspect this is a duplicate of #7148

**Comment by krschau** [comment]
I think @EddieLotter is right, closing this as a dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/7148
