### ISSUE TITLE
NavigationView does not update selection indicator correctly when ItemsSources change 

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#7216]
### Describe the bug

If NavigationView.MenuItemsSource/FooterMenuItemsSource uses a databinding and the underlying object changes, NavigationView.SelectedItem will update correctly, but NavigationViewItem.IsSelected does not get set and the selection indicator does not appear.

### Steps to reproduce the bug

1. Download attached TopNavTestApp.zip, build and deploy
2. Observe NavView loads correctly with selection
3. Click buttons "MenuItem Set 1" and "MenuItem Set 2" to switch view models
4. Observe selection indicator does not appear, although NavigationView.SelectedItem is set
[TopNavTestApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8874015/TopNavTestApp.zip)
.

### Expected behavior

Selection indicator should appear even when databound objects change.

### Screenshots

![image](https://user-images.githubusercontent.com/45607479/172944718-e949fb02-d8ba-4d4d-833f-0abda250968e.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Still repros on latest 2.8.0-prerelease.220601001 package.

**Comment by NightLJM** [comment]
I ran into this issue too. What I did was:
1. reset the `MenuItems` 
2. set "SelectedItem".

But if I delay 1 second or use bellow logic between step 1 and step 2, it works well.
``` C#
        Task ContainerFromMenuItemAsync(object selectedItem)
        {
            var taskCompletionSource = new TaskCompletionSource<bool>();
            void OnLayoutUpdated(object sender, object e)
            {
                if (MyNav.ContainerFromMenuItem(selectedItem) is not null)
                {
                    taskCompletionSource.SetResult(true);
                    MyNav.LayoutUpdated -= OnLayoutUpdated;
                }
            }
            MyNav.LayoutUpdated += OnLayoutUpdated;
           return taskCompletionSource.Task;
        }
```

**Comment by hawkerm** [comment]
I'm noticing a similar issue when trying to use `IsSelected` in a DataTemplate with loading a `NavigationView`. When I had `NavigationViewItem`s hard-coded in XAML it was working fine, but now switching to use `MenuItemsSource` the `NavigationViewItem` is showing as selected, but I'm not seeing my `SelectedItem` binding update nor the selection indicator on the NavigationView itself.

**Comment by hawkerm** [comment]
I wonder if this part of the selection update is getting skipped during initialization (`m_appliedTemplate`)?

https://github.com/microsoft/microsoft-ui-xaml/blob/bace2c55557d42e52f1914c49d6fa75a06df10f6/dev/NavigationView/NavigationView.cpp#L271-L282

Not sure if TODO is relevant here as well, it does call out datasource?

But the internals of the control are still setting the selection of the container here?

https://github.com/microsoft/microsoft-ui-xaml/blob/bace2c55557d42e52f1914c49d6fa75a06df10f6/dev/NavigationView/NavigationView.cpp#L938-L950

Just a thought?

**Comment by hawkerm** [comment]
Related to #5007 and #2845

**Comment by asierpn** [comment]
Please reopen this issue again, it's very common to change the ItemsSource and the NavigationView doesn't work well on this scenario.

**Comment by ADD-David-Antolin** [comment]
@llongley If you close it at least explain why.
