### ISSUE TITLE
Can you please include Haitian Creole [ht] and Hmong Daw (Latin)  mww to Multilingual App Toolkit?

### ISSUE THREAD

**Issue by pooranoayaw** [microsoft/microsoft-ui-xaml#7218]
Please add these two languages Haitian Creole [ht] and Hmong Daw (Latin) [mww] to MAT? They are available in Cognitive Services https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support.

Meanwhile, can you tell us how to go about adding these languages manually?

**Comment by krschau** [comment]
I think this request belongs in the [Multilingual App Toolkit](https://github.com/microsoft/Multilingual-App-Toolkit) repo. Unfortunately I can't transfer the issue to that repo, so you'll have to re-open it over there.
