### ISSUE TITLE
Question: Alignment ContentDialog Buttons

### ISSUE THREAD

**Issue by amazatis** [microsoft/microsoft-ui-xaml#7227]
Is it possible to place the buttons of the ContentDialog on the right side?

**Comment by castorix** [comment]
You can copy and modify **DefaultContentDialogStyle**

A test with a [Derived control](https://docs.microsoft.com/en-us/windows/apps/design/style/xaml-styles#derived-controls) :

![ContentDialog_Buttons_Right](https://user-images.githubusercontent.com/22345506/173249255-0dff0249-0534-4ba0-bce5-1972516e74bd.jpg)

**Comment by amazatis** [comment]
Thanks...
