### ISSUE TITLE
Question: Integrate Windows App SDK Runtime into Windows?

### ISSUE THREAD

**Issue by nikolayvpavlov** [microsoft/microsoft-ui-xaml#7236]
Are there plans to integrate Windows App SDK Runtime into Windows and have it distributed and updated via Windows Update?

If Windows App SDK is to become the next platform for app development, it must become an integral part of the OS.  It is good to allow apps to bind to a specific version of the SDK, which is possible now when the project is self-contained.  However, having the runtime integrated and automatically updated will definitely improve the experience for users and developers.

Benefits:

1. Automatic bug fixes in the SDK via WIndows Updates that do not require to recompile and re-deploy the applications.
2. Streamlined update process.
3. "Lighter" installation packages for unpackaged apps (now a simple 500KB app with all resources embedded comes as a 300 MB self-contained package).

**Comment by krschau** [comment]
@gabbybilka or @ryandemopoulos, could you chime in here?

**Comment by marb2000** [comment]
Yes, there are plans to deploy the Windows App SDK within the Windows OS, but not in the short term though. 

But you don't have to wait until this happens for getting updates automatically. By default, WinAppSDK apps are Framework-Dependent apps that require having installed the runtime on your machine. This runtime is updated automatically via Store every time there is a new release. You can also opt out of this mode. Also, once the Framework is installed, all the apps will share it.

**Comment by nikolayvpavlov** [comment]
@marb2000 , thank you for this answer.  It is sad to hear that short-term Windows App SDK will be a foster child within the ecosystem of Windows OS.  Just like .NET Framework, which became an integral part of Windows Vista, Windows App SDK must be included in the next release of Windows 11.  Otherwise it is just a set of libraries which people need to take care of themselves. What you describe means that developers who do not want to rely on the Store for one or another reason must include the runtime in their installation packages, or create self-contained apps.  The latter, though, make it impossible to rely on automatic updates.
