### ISSUE TITLE
Incorrect window (close, maximize...), settings and back button icon size

### ISSUE THREAD

**Issue by Haky00** [microsoft/microsoft-ui-xaml#7237]
### Describe the bug

It seems that all buttons with a default icon, such as:

- Window buttons (close, maximize, restore, minimize) when `ExtendsContentIntoTitleBar = true`
- Back and Settings button for `NavigationView`

are scaled incorrectly, and look blurry and/or have artifacts. In the screenshots, I compare them with the same UWP icons. This occurs on both Windows 10 and 11, both with custom apps and the WinUI 3 Gallery app from Microsoft Store. Also, for some reason, the window button foreground is gray, even when the window is focused - this is not standard behavior for UWP (store, terminal) or even Win32 apps.

### Steps to reproduce the bug

1. Start a new WinUI 3 project
2. Set `ExtendsContentIntoTitleBar = true` in the code-behind for MainWindow
3. Add a `NavigationView` (`PaneDisplayMode` does not matter)

### Expected behavior

Icons that look sharp and are sized correctly.

### Screenshots

![WinUI-3_Icon-issues](https://user-images.githubusercontent.com/32370956/173551659-e51dc879-5497-4544-8c09-35f4d114d249.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044

### Additional context

The actual version of package version used is 1.1 release, but it was not available to select in the dropdown.

**Comment by JaiganeshKumaran** [comment]
This should be in high priority because I don't want to spend time making a simple title bar look correct. Another thing is the background colour doesn't change when pressed unlike UWP and Win32 default title bar.
