### ISSUE TITLE
Question:Is there any way to handle multiple resources.pri files in a deployment folder? 

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/microsoft-ui-xaml#7241]
I have a UWP app for hosting WinRT XAML controls in a C++ desktop (Win32) app and **resources.pri** file is also there. If I create another UWP app for another Win32 app with same deployment location, another **resources.pri** file will be generated with **same name**. It will cause issues in first app. Is there any way to handle this issue, like different name for different .pri files?

**Comment by DominicMaas** [comment]
Did you ever discover a solution for this?
