### ISSUE TITLE
Webview2 OpenDefaultDownloadDialog not working. 

### ISSUE THREAD

**Issue by shyamshr93** [microsoft/microsoft-ui-xaml#7242]
### Describe the bug

Calling OpenDefaultDownloadDialog in Webview2 doesn't open the download dialog. Downloading File also doesn't open the default download dialog. The only time download dialog is opened when clicking on "Save as" in the context menu of WebView2.

### Steps to reproduce the bug

call web.CoreWebView2.OpenDefaultDownloadDialog();

where web is WebView2 control.

### Expected behavior

It should open the Default Download Dialog when calling OpenDefaultDownloadDialog();

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by krschau** [comment]
I opened this issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/2525 in the WebView2 repo, since it looks like an issue there.
