### ISSUE TITLE
CompositionTarget.Rendering throws InvalidCastException

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#7247]
### Describe the bug

When [we hook into the `CompositionTarget.Rendering` event](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/winui/CommunityToolkit.WinUI.UI/Helpers/CompositionTargetHelper.cs) we're seeing an `InvalidCastException` native exception thrown (seems continuable though):

```
System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
```

This doesn't happen on UWP, though I'm not sure if we're actually getting the proper behavior of waiting on WinUI 3.

Saw both on WinAppSDK 1.0.3 and 1.1.1.

### Steps to reproduce the bug

Hook into the `Composition.Rendering` event

You can also include the `CommunityToolkit.WinUI.UI` 7.1.2 package and use our `CompositionTargetHelper` static method helper.

### Expected behavior

No exception thrown.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by JJBrychell** [comment]
Unable to repro this on any version 1.1 to 1.3 using the CompositionTargetHelper class in included in comments. Also the report doesn't indicate whether the error is occurring when attempting to assign the event handler or when the event handler is being executed.

If this continues to be an issue feel free to reopen with more a more actionable repro.
