### ISSUE TITLE
NavigationView not invalidating layout correctly after resizing

### ISSUE THREAD

**Issue by kaiguo** [microsoft/microsoft-ui-xaml#726]
**Describe the bug**

Reported by @joshkoon 

**Steps to reproduce the bug**

See the below images. Left is the bad state, Right is expected. This one is a little trickier to repro and seems like we aren’t invalidating the layout someplace:

a.	With CompactModeThresholdWidth=0, Resize the window to just under the ExpandedMode threshold width. (pane is collapsed)

b.	Click the hamburger to open the pane (opens over content)

c.	Resize the window to OVER the ExpandedMode threshold width (pane collapses before threshold and immediately expands after threshold)

d.	Resize the window the under the ExpandedMode threshold width. Pane collapses but doesn’t seem to update its width for all elements. I can verify IsPaneOpen property changed events are firing correctly and elements are responding, but the phone icon and (custom) separator lines still believe they are rendering at full width.

**Screenshots**

![1](https://user-images.githubusercontent.com/4424330/57953591-5a36f980-78a5-11e9-9388-79d8034eb27b.png)![2](https://user-images.githubusercontent.com/4424330/57953601-602cda80-78a5-11e9-9d20-eaac705a04c5.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Thanks @kaiguo, what are the next steps for this? Do you want to debug this or do you need help from someone more familiar with layout?

**Comment by joshkoon** [comment]
Attaching an app that repros the behavior. Left image is expected; right image shows the bug - the emoji button is render at 304px instead of 40px.
[NavViewTestApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3199089/NavViewTestApp.zip)
![NavViewBugNoRepro](https://user-images.githubusercontent.com/45607479/58040863-6f9d6500-7aeb-11e9-89dc-de52938103c5.png)![NavViewBugRepro](https://user-images.githubusercontent.com/45607479/58040868-71ffbf00-7aeb-11e9-896a-daabcea61b77.png)
