### ISSUE TITLE
CoreWebView2.AddHostObjectToScript throws System.Exception

### ISSUE THREAD

**Issue by Billeclipse** [microsoft/microsoft-ui-xaml#7261]
### Describe the bug

CoreWebView2.AddHostObjectToScript throws System.Exception: 'The group or resource is not in the correct state to perform the requested operation.'

### Steps to reproduce the bug

Repro Steps

1.  Create an UWP project
2.  Add necessary nuget packages (Microsoft.Web.Webview2 latest stable release and Microsoft.UI.Xaml 2.8.0-prerelease)
3.  Add WebView2 component to MainPage.xaml
4.  Create HostObject class with necessary tags
5.  Add code for navigation starting or navigation completed method in WebView2 (MainPage.xaml.cs)
6.  Ensure CoreWebView2 is not null by calling myWebView.EnsureCoreWebView2Async(); inside method
7.  Try use myWebView.CoreWebView2.AddHostObjectToScript("HostObject", hostObject); inside method
(Also tried to make a new project uwp (as Windows Runtime Component) and create the HostObject class there but still same exception. In addition tried to change tags on HostObject class but still same issue)

### Expected behavior

System.Exception: 'The group or resource is not in the correct state to perform the requested operation.'

### Screenshots

![image](https://user-images.githubusercontent.com/17092072/174574744-574f4b99-e5e0-440b-9d3f-8658ebafa992.png)

### NuGet package version

Microsoft.UI.Xaml 2.8.0-prerelease.220601001

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Example of HostObject class:
```
[AllowForWeb] // Tried it with and without this tag
[ClassInterface(ClassInterfaceType.AutoDual)]
[ComVisible(true)]
public class JsCallbacksUwp
{
    public JsCallbacksUwp()
    {

    }
}
```

Example code for Navigation Completed that throws the exception:
```
private async void WebView2_NavigationCompleted(WebView2 sender, CoreWebView2NavigationCompletedEventArgs args)
  {
      await sender.EnsureCoreWebView2Async();

      var browserHostObject = new JSCallbacksUwp();

      sender.CoreWebView2.AddHostObjectToScript("HostObject", browserHostObject);
  }
```

**Comment by krschau** [comment]
I see that you got this question answered over at https://github.com/MicrosoftEdge/WebView2Feedback/issues/2529.

For others coming across this, I suggest looking at that issue. The key to using the `AddHostObjectToScript()` API in WinUI 2 is to follow the steps in the article [Call native-side WinRT code from web-side code](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=csharp). 

For more information about using this API in WinUI 3, see https://github.com/microsoft/microsoft-ui-xaml/issues/4377.
