### ISSUE TITLE
Implicit style not working after set and remove a second style

### ISSUE THREAD

**Issue by chrisdreams13** [microsoft/microsoft-ui-xaml#7264]
### Describe the bug

I tried to add an "Error" Style to a control if has error in it's view-model, then when it's ok I remove that style as there are no error, expecting the implicit style will be applied, but no style is shown.

```
    <StackPanel x:Name="Stack">
        <StackPanel.Resources>
            <Style TargetType="TextBox">
                <Setter Property="Margin" Value="50"></Setter>
            </Style>

            <Style x:Name="Error" TargetType="TextBox">
                <Setter Property="Margin" Value="50"/> <!-- redefined as it's not inherit from implicit -->
                <Setter Property="Background" Value="Red"/>
            </Style>
        </StackPanel.Resources>

        <TextBox x:Name="Changing"></TextBox>
    </StackPanel>
```

For example I applied and remove style each second.

```
public sealed partial class MainWindow
{

    public MainWindow()
    {
        InitializeComponent();
            
        var timer = new DispatcherTimer
        {
            Interval = TimeSpan.FromMilliseconds(1000)
        };
        timer.Tick += Step;
        timer.Start();
    }

    private void Step(object sender, object e)
    {
        Changing.Style = Changing.Style == null ? Stack.Resources["Error"] as Style : null;
    }
}
```

### Steps to reproduce the bug

1. Create an implicit style for TexBox
2. Create an explicit style for TexBox
3. Create a Texbox inside a window or UserControl
4. Change the Textbox's Style in code for the explicit style (previous value is null)
5. Change the Textbox's Style in code for null (initial one)
6. Check that Textbox doesn't have any style applied, neither the implicit one.

### Expected behavior

Implicit styling should be applied after add and remove a second style

### Screenshots

![image](https://user-images.githubusercontent.com/6045302/174668480-5236bbb6-5572-4dec-8d02-d9e20bf406f7.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by ADD-David-Antolin** [comment]
If its not resolved I do not see why it should be closed.
