### ISSUE TITLE
WebView2 for UWP html pages has <Input  type="file"> can't browse to files to select file 

### ISSUE THREAD

**Issue by ZakaryaAtef** [microsoft/microsoft-ui-xaml#7278]
I'm currently using webview2 version 1.0.1248-prerelease 
while trying to select file from browse button on any website it does nothing 
I tried it for uwp it doesn't work 
but for windows forms it works fine

**Comment by ZakaryaAtef** [comment]
I added duplicate issue under bugs section

**Comment by krschau** [comment]
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/7280

**Comment by krschau** [comment]
Please see https://github.com/microsoft/microsoft-ui-xaml/issues/7280 for more information.

**Comment by dineshgaikwad09** [comment]
Is there any solution?
