### ISSUE TITLE
Dotnet publish command not working for winUI3 non-packaged application

### ISSUE THREAD

**Issue by pbasithmpy** [microsoft/microsoft-ui-xaml#7279]
Hi,
I want to make an installer for winUI3 application using wix. so for publishing before build I used these codes in my wixproj
`<Target` Name="BeforeBuild">
    `<Exec` Command="dotnet publish ..\WinUIApp\WinUIApp.csproj -c $(Configuration) -r win10-x64 -p:PublishSingleFile=true `--self-contained` false -o ..\Executables\UI" />
    `<PropertyGroup>
      `<LinkerBaseInputPaths>..\Executables\Service</LinkerBaseInputPaths>
     ` <DefineConstants>BasePath=..\Executables\UI</DefineConstants>
    `</PropertyGroup>
    `<HeatDirectory` RunAsSeparateProcess="true" OutputFile="UI.wxs" DirectoryRefId="INSTALLFOLDER" `ComponentGroupName="ServiceProject"` SuppressCom="true" Directory="..\Executables\UI" SuppressFragments="true" `SuppressRegistry="true"` SuppressRootDirectory="true" AutoGenerateGuids="false" GenerateGuidsNow="true" `ToolPath="$(WixToolPath)"` PreprocessorVariable="var.BasePath" />
  `</Target>`

When I build the installer, dotnet publish command is failing. showind dotnet publish ....... exited with code 1. But when I publish application using VS publish interface, it is working fine. can any one solve my problem please
``

**Comment by dynsim** [comment]
As far as I know, WinUI 3 projects do not support `dotnet` commands. It seems to be [on the roadmap](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/57-support-dotnet-build).

I do not know if you can get this to work using Wix, but you should be able to perform what you want using `msbuild`. I think you may be able to find some inspiration [here](https://docs.microsoft.com/en-us/windows/apps/package-and-deploy/ci-for-winui3?pivots=winui3-packaged-csharp#step-3-set-up-your-workflow).

**Comment by pbasithmpy** [comment]
fixed with visual studio 2022 17.3 version
