### ISSUE TITLE
WebView2 for UWP html pages has <Input type="file"> can't browse to files to select file

### ISSUE THREAD

**Issue by ZakaryaAtef** [microsoft/microsoft-ui-xaml#7280]
### Describe the bug

I'm currently using webview2
while trying to select file from browse button on any website it does nothing
I tried it for uwp it doesn't work
but for windows forms it works fine

### Steps to reproduce the bug

1-create a uwp app
2-add WebView2 control 
3-navigate to any website has file browse button
4-click on the select file button it does nothing!!!

### Expected behavior

When we click on file select button it should open file choose dialogue from windows 

### NuGet package version

Microsoft.UI.Xaml 2.8.0-prerelease.220601001

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by krschau** [comment]
Hi @ZakaryaAtef. This is a known issue with the WebView2 control, and something they're actively working on. It's being tracked here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1639. My current understanding is the last comment there ("It won't be available in time for the first GA, but we hope to finish this work soon") is still true.
