### ISSUE TITLE
Can't create DataTemplate in codebehind

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#7285]
### Describe the bug

I want to create a DataTemplate in codebehind, but I find that it's impossible. I googled everywhere, but for WinUI, there's no solution.

### Steps to reproduce the bug

![image](https://user-images.githubusercontent.com/13891601/175804525-c4e156cb-88e7-4024-af1a-ff71ef9d6edf.png)

The above should work. For WPF, there are much easier steps to create a `DataTemplate` in code. But for WinUI, there's no such thing.

And by the way, `DataTemplate.LoadElement` does nothing.

### Expected behavior

The above should work. Or at least, there should be a way for me to achieve this.

To be clear, here's more or less what I want to achieve (I'm using the `DataGrid` from `CommunityToolkit.WinUI.UI`)

![image](https://user-images.githubusercontent.com/13891601/175804710-34b41f3b-46b4-49a2-bb0b-559bb8bda8ff.png)

### NuGet package version

1.0.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 2004 (19041, May 2020 Update)

### IDE

Visual Studio 2022

**Comment by francoistanguay** [comment]
See https://github.com/microsoft/microsoft-ui-xaml/issues/2898
