### ISSUE TITLE
Changing the value of an application resource in code -- if a Style depends on it, it doesn't update.

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#7287]
### Describe the bug

Changing the value of a `x:Double` application resource in code -- if another style depends on it, that doesn't update.

### Steps to reproduce the bug

I have another resource dictionary, added in my App.xaml

    // added last
    <ResourceDictionary Source="ResourceDictionary1.xaml" x:Key="Default"/>

The resource dictionary:

    <ResourceDictionary
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="using:App1">

        <x:Double x:Key="TextBlockFontSize">14</x:Double>
        <Style TargetType="TextBlock">
            <Setter Property="FontSize" Value="{ThemeResource TextBlockFontSize}"/>
        </Style>

    </ResourceDictionary>

In OnAppLaunched, I have this (basically, I want to load this from a settings file, and update it on the fly):

    protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args) {
        this.Resources["TextBlockFontSize"] = 42d;
        m_window = new MainWindow();
        m_window.Activate();
    }

If I do the same with `PivotHeaderItemFontSize` value: if I add it as an  `x:Double` to the dictionary, and then change it in code in `OnLaunched`, it works correctly.

### Expected behavior

In the above code, changing the value of `TextBlockFontSize` should update the font size to 42pt -- so if you have a `<TextBlock Text='titi'/>` in MainWindow.xaml, that should end up having a font size of 42pt 

### NuGet package version

1.0.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 2004 (19041, May 2020 Update)

### IDE

Visual Studio 2022

**Comment by zoltanfGH** [comment]
I have the same problem, where changing font size doesn't update the value.

I have a class where the font size is.

`public partial class FontSizeHelper : ObservableObject
{
    [ObservableProperty]
    private double _caption = 12;
}`

A simple resourcedictionary style for a button.

`

    <ResourceDictionary.MergedDictionaries>        
        <ResourceDictionary>
            <styles:FontSizeHelper x:Key="FontSizeHelper"/>
        </ResourceDictionary>
    </ResourceDictionary.MergedDictionaries>

    <Style x:Key="DefaultCaptionStyle" TargetType="Button" >
        <Setter Property="FontSize" Value="{Binding Caption, Mode=TwoWay, Source={StaticResource FontSizeHelper}}"/>
    </Style>  

`

And I use it like this:
`<Button Margin="4,2,2,2" Content="xxx" Tapped="Button_Tapped" Style="{StaticResource DefaultCaptionStyle}"/>`

And I update the value:
`((FontSizeHelper)Application.Current.Resources["FontSizeHelper"]).Caption = newFontSize;`

The value updates, but the style stays the same.
