### ISSUE TITLE
SetTitleBar doesn't work in unpackaged project

### ISSUE THREAD

**Issue by KenionX** [microsoft/microsoft-ui-xaml#7292]
### Describe the bug

Toolbar buttons (close, minimize, maximize) and window position dragging is only working in packaged WinUI3.

### Steps to reproduce the bug

- Create an unpackaged WinUI3 project
- ExtendsContentIntoTitleBar = true;
- SetTitleBar(CustomTitleBar);

### Expected behavior

Same behaviour as packaged version

### Screenshots

![customTitlebar](https://user-images.githubusercontent.com/63214030/176324935-cf774498-8e32-4711-8d83-5a3f74ac7a33.gif)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by AndrewKeepCoding** [comment]
It works for me even in unpackaged apps.
This is a minimal sample.
**MainWindow.xaml**
```xaml
<Grid RowDefinitions="32,*">
    <Grid x:Name="CustomTitleBar" Grid.Row="0" Background="HotPink">
        <TextBlock VerticalAlignment="Center">Title</TextBlock>
    </Grid>
    <Grid Grid.Row="1">
        <TextBlock>Body</TextBlock>
    </Grid>
</Grid>
```
**MainWindow.xaml.cs**
```csharp
public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
        ExtendsContentIntoTitleBar = true;
        SetTitleBar(CustomTitleBar);
    }
}
```
Though, I did had similar a experience with the captions buttons but I can't remember what was causing that. Can you post your minimal code that repros the issue?

**Comment by castorix** [comment]
On Windows 10, it works with a **Manifest**
(I had posted a sample test with rounded System buttons : [WinUI3_CustomCaption](https://github.com/castorix/WinUI3_CustomCaption) )

**Comment by KenionX** [comment]
> On Windows 10, it works with a **Manifest** (I had posted a test sample with rounded System buttons : [WinUI3_CustomCaption](https://github.com/castorix/WinUI3_CustomCaption) )

Thanks, adding the manifest fixed the issue 👍
