### ISSUE TITLE
High DPI Unaware

### ISSUE THREAD

**Issue by Hemofelicity** [microsoft/microsoft-ui-xaml#7293]
I want my app to run 96dpi regardless of system scale, without having to scale the frame. I'm not even entirely sure how I'd get the system scale to scale the frame. Setting the app manifest to unaware and also doing it programmatically before a window call does nothing for the fact that my laptop scale is set to 125%. It still stretches 96 dpi content. What really gets me about this is, why would an app anticipate scaling? If you have to shutdown the app and log in and out to scale???? I can scale the frame. I imagine this will cause me grief somewhere though. My app is a piece of desktop software that I'd like to use the WinUI interface for. C++, UI, desktop . . . . win. Not a mobile app that needs fifty configurations. I will use WinUI directly for scaled UI.

**Comment by krschau** [comment]
The recommended way to get the scale is the [XamlRoot.RasterizationScale property](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.xamlroot.rasterizationscale?view=windows-app-sdk-1.1), and you can subscribe to the [XamlRoot.Changed](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.xamlroot.changed?view=windows-app-sdk-1.1) event to know when it changes.

@marb2000 might know more about what you're trying to do.

**Comment by Hemofelicity** [comment]
Just went back to working on my UI. Posting my answer from Stack. Seems obvious now. Not so obvious without the proper background.

To adjust the scaling of your app, to compensate for system scaling, `x:Name` the root element of your class in Xaml i.e. `x:Name="root"`. If you have separated your Window, Frame, Page, it's easiest to target the root element and its scale in the Loaded override function of the Page. If you want to adjust the Frame, it will have to be the root element of the Window and you'll probably target the overloaded function OnNavigated. It all depends on the level of separation between Window, Frame, and Page in Xaml.

When targeting the root element scale from Page, the Page must be loaded, and it's easiest to scale in the Loaded overload function. Scale using `root().Scale(float3)`. To adjust scale based on the scaling of your device, call `root().XamlRoot()` and get the rasterization scale:

`double rastScale = root().XamlRoot().RasterizationScale()`

Then set the scale with:

`root().Scale({float(1/rastScale), float(1/rastScale), 1.0f})`

These techniques are poorly documented. The `XamlRoot()` idea is poorly documented or the right document just doesn't readily appear via search. You cannot use `this->XamlRoot()` as this returns null. You cannot x:Name the Xaml Class to get `XamlRoot()`. `XamlRoot()` is not just some static function defined in the plumbing.
