### ISSUE TITLE
 Unhandled exception thrown at 0x534343D9 (Microsoft.ui.xaml.dll) in CppApp.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0B03B088, 0x00000003).

### ISSUE THREAD

**Issue by sulthan31** [microsoft/microsoft-ui-xaml#7294]
### Describe the bug

I have created the C# component with WinUI 3 controls and referred the component from a Windows App SDK C++/WinRT app in the below-mentioned reference link after rebuilding the application to run the application exception thrown. 

**Reference link** - https://docs.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/create-winrt-component-winui-cswinrt 

**Sample**

[Sample_WinUI.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9011976/Sample_WinUI.zip)

### Steps to reproduce the bug

Step 1; Run the sample.

Note: Exception is thrown.

### Expected behavior

Sample run without exception

### Screenshots

![image](https://user-images.githubusercontent.com/92780496/176475784-d86244ea-55ac-4967-8886-fa85ae559494.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by JeganRavichandran** [comment]
???

**Comment by HO-COOH** [comment]
Let's pin one of the PM to reopen. @codendone @bpulliam  @ojhad
