### ISSUE TITLE
Question: correct way of animating `Translation` of `UIElement`

### ISSUE THREAD

**Issue by nor0x** [microsoft/microsoft-ui-xaml#7301]
i have the following simple snippet which i expect to render an animated change of translation of a `UIElement`. I set the `TranslationTransition` with a `Duration` and set a new `Translation` afterwards

```csharp
myView.TranslationTransition = new Vector3Transition()
{
    Duration = TimeSpan.FromSeconds(1)
};
myView.Translation = new Vector3(1, 2, 3);
```

however it fails on setting the `TranslationTransition`:

```
Exception thrown: 'System.UnauthorizedAccessException' in WinRT.Runtime.dll
WinRT information: Access denied.  Calling TranslationTransition API is not allowed on this object at this time, as this object currently has the Projection property in use.
An exception of type 'System.UnauthorizedAccessException' occurred in WinRT.Runtime.dll but was not handled in user code
WinRT information: Access denied.  Calling TranslationTransition API is not allowed on this object at this time, as this object currently has the Projection property in use.
Access is denied. (0x80070005 (E_ACCESSDENIED))

```

I already found the issue with a discussion here (https://github.com/microsoft/microsoft-ui-xaml/issues/4904) however i couldn't find the correct way of achieving such a simple movement animation in my UI - it's quite confusing to be honest

**Comment by krschau** [comment]
@gegao18 Do you know the answer to this one?

**Comment by gegao18** [comment]
Hi @nor0x, have you checked what other properties are set on your "myView" element? Does it have a Projection set on it? TranslationTransition isn't compatible with Projection, so you'll have to set myView.Projection = null before using TranslationTransition.

**Comment by nor0x** [comment]
Hi @gegao18 , thanks for the reply - i already tried nulling `Projection` before setting `TranslationTransition` and still get the same error.

Here you can see all the properties from the `FrameworkElement` with `Projection` being `null`
![properties](https://user-images.githubusercontent.com/3210391/176744606-143e4be8-7784-4fbc-8123-e99b1a1d58da.png)

**Comment by gegao18** [comment]
Thanks @nor0x. Can you also check that it doesn't have an animated Projection and isn't picking one up through a style?

Looking through your table, RenderTransform is also going to conflict with Translation/TranslationTransition and cause a problem for you.

**Comment by nor0x** [comment]
`Style` is also null and i have tried setting `RenderTransform` to null before setting `TranslationTransition`

**Comment by castorix** [comment]
I use the old function [CreateOrUpdateSpringAnimation ](https://github.com/microsoft/WinUI-Gallery/blob/260cb720ef83b3d134bc4805cffcfac9461dce33/WinUIGallery/ControlPagesSampleCode/Motion/AnimationInterop/AnimationInteropSample1_cs.txt)from WinUI 3 Gallery and it works correctly (with Buttons for example, to animate them to simulate down/up when clicked, with "Translation" instead of "Scale")
![Button_Translation](https://user-images.githubusercontent.com/22345506/176762207-c2666ce6-cae9-4c1b-88aa-7bb42be6defb.gif)

**Comment by gegao18** [comment]
@nor0x would you mind sharing the project where you're hitting this problem? We can take a look at what's going on.
