### ISSUE TITLE
UserControl, IOT, gpio, Raspberry pi3

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#7303]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/UserControl-IOT-gpio-Raspberry-pi3/10077947)._

---
Hello, I am developing in c# for raspberry pi 3, I have a user control that I use as a viewer of states and errors of the app, I call it and it is shown on the page that is currently being shown. This part works well.
The problem I have is that it does not show when I call it from some event of the gpio.   If I touch any button on the screen that is linked to the user control if it is displayed, but from the gpio not.
The same problem I have when receiving an msj from the site, it has to open a page and it does not.
The iot version is 16299. Thanks a lot!

---
#### Fiona Niu[MSFT] on 6/22/2022, 11:15 PM: 

(private comment, text removed)
#### cristianfea on 6/29/2022, 07:49 AM: 

(private comment, text removed)
#### Feedback Bot on 6/29/2022, 08:17 PM: 

(private comment, text removed)
#### ET [MSFT] on 6/30/2022, 07:05 AM: 

(private comment, text removed)
#### cristianfea on 6/30/2022, 08:42 AM: 

(private comment, text removed)
#### ET [MSFT] on 6/30/2022, 08:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CristianFea** [comment]
[pruebaUserControl.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9023647/pruebaUserControl.zip)
