### ISSUE TITLE
DependencyObjects (brushes, etc.) cannot be added twice to a resource dictionary with different keys

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#7306]
In RNW we expose styling that translates to calls like:

![image](https://user-images.githubusercontent.com/22989529/176961814-c2bdf016-31d4-479a-b418-b03385f53a45.png)

The problem is that ResourceDictionary's Remove functionality (which is called as part of Insert too), has some code that removes "the entry whose value is the DO associated with the entry whose key you passed in".
So if your RD has: `{key1, brushA}`, `{key2, brushA}` and you call `Remove(key2)`, it might actually remove the `{key1, brushA}` entry!
This is non deterministic as it depends on what bucket gets picked by some hashing function for the map backing the RD.

**Comment by michael-hawker** [comment]
@asklar want to update the title to have DO as the full `DependencyObject`? Should help folks in the future trying to search for issues to discover this one as it's not in the initial comment text as well.

**Comment by asklar** [comment]
good idea, done.

> @asklar want to update the title to have DO as the full `DependencyObject`? Should help folks in the future trying to search for issues to discover this one as it's not in the initial comment text as well.
