### ISSUE TITLE
ItemsRepeater slow rendering issue

### ISSUE THREAD

**Issue by eslyverano** [microsoft/microsoft-ui-xaml#7308]
### Describe the bug

When rendering items on a ItemsRepeater (StackLayout-Vertical), some of the items take a couple of seconds to appear on the list, despite all of them being loaded on the attached ObservableCollection every time. This is something that happens randomly, I cannot really find the cause (See attached video)
In my code, I'm getting records from a SQLite db and populating an IObservableVector that is "x Bound" to the ItemsRepeater.ItemsSource. 
** This doesn't seem to happen when there are plenty of items on the Vector. (more Items that fill the Viewport height) 

### Steps to reproduce the bug

1. Create an ItemsRepeater  i.e. `<ScrollViewer Grid.Row="1">
            <ItemsRepeater x:Name="list" ItemsSource="{x:Bind tmArray}">
                <ItemsRepeater.Layout>
                    <StackLayout Orientation="Vertical" />
                </ItemsRepeater.Layout>
                <ItemsRepeater.ItemTemplate>
                    <DataTemplate x:DataType="local:TimerViewModel">
                        <StackPanel x:Name="tmItem" Orientation="Vertical" Background="Transparent" DataContext="{x:Bind}" Padding="0,8,0,4"
                                     PointerEntered="tmItem_PointerEntered" PointerExited="tmItem_PointerExited" Tapped="tmItem_Tapped">
                            <TextBlock Text="{x:Bind Name}" />
                            <TextBlock Text="{x:Bind DurationLabel}" Style="{StaticResource CaptionTextBlockStyle}" />
                        </StackPanel>
                    </DataTemplate>
                </ItemsRepeater.ItemTemplate>
            </ItemsRepeater>            
        </ScrollViewer>`
2. Bind an IObservableVector to it and add 2 or 3 items in it.

### Expected behavior

ALL items on the ItemsRepeater should appear immediately.

### Screenshots

https://user-images.githubusercontent.com/4444901/176983978-c0b52ba1-dc76-4751-b8b5-9e172cf43b23.mp4

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ojhad** [comment]
@eslyverano which nuget package version are you using?

**Comment by eslyverano** [comment]
@ojhad 
Microsoft.WindowsAppSDK       1.1.1
Microsoft.Windows.CppWinRT   2.0.220608.4
Microsoft.Windows.ImplementationLibrary      1.0.220201.1
Microsoft.Windows.SDK.BuildTools            10.0.22621.1

**Comment by ranjeshj** [comment]
@eslyverano Can you try to narrow down the issue. I'm not sure if the issue is caused by ItemsRepeater or a delay in loading the data into the collection from the database. I suspect it is the latter. You could try to take a trace and see the time between when the collection updates and when it is reflected in the UI.

**Comment by eslyverano** [comment]
@ranjeshj I've just double checked the loading process takes always the same time. I changed the ItemsRepeater for a ListBox and the rendering issue disappeared, the items appear immediately every time. Thank you for looking into this.

**Comment by eslyverano** [comment]
@ranjeshj Can this XAML attribute be the issue? DataContext="{x:Bind}"
Although, I have tried this before in other ItemsRepeaters (in C# projects) and it works OK.

**Comment by ranjeshj** [comment]
@eslyverano does it work for Binding but not x:Bind ? x:Bind by default does one time binding, but if you are seeing the visual update, I'm guessing the collection update is notified to the view.
You say it works for ListBox which would indicate it is a control issue.

**Comment by stevenbrix** [comment]
this issue still exists and should be re-opened
