### ISSUE TITLE
XamlControlsResources does not work when main program class is renamed

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/microsoft-ui-xaml#7311]
### Describe the bug

When using WinUI 2, the main program's class name must be `App` in order for the styles in XamlControlsResources to be applied. If you rename it something else, all the controls lack the WinUI styling.

### Steps to reproduce the bug

1. Create new UWP app (CppWinRT)
2. Change default namespace in CppWinRT settings
3. Rename `App` class to something else (do changes in all files)
4. Update appxmanifest entrypoint to be `NewNamespace.NewAppClass`
5. Add WinUI 2 nuget package and follow directions
6. Add a `AutoSuggestBox` to a control
7. Build + deploy
8. Notice how controls use W10 styling

### Expected behavior

XamlControlsResources works normally

### Screenshots

![image](https://user-images.githubusercontent.com/42058942/177022332-a566ccc6-2f8c-448e-a7d8-11193777864a.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

This also happens for UWP apps written in C# or VB.

**Comment by evelynwu-msft** [comment]
If you have renamed `app.xaml` (say, to `NewAppClass.xaml`), then you need to add the following to `NewAppClass::OnLaunched()` as you have effectively opted out of the framework's automatic load of `app.xaml`:
```c++
Uri resourceLocator{ L"ms-appx:///NewAppClass.xaml" };
Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Application);
```

**Comment by AzAgarampur** [comment]
Sorry about the late reply, your solution works. It is possible to document this behavior somewhere and provide others with information that tells them what to do in this situation?
