### ISSUE TITLE
Same control property name and binding name cause function template has already been defined compile error

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#7313]
### Describe the bug

MainPage.xaml
```xml
<Page
    x:Class="UwpCpp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UwpCpp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <TextBlock Text="{x:Bind Header}"/>
        <muxc:Expander>
            <muxc:Expander.Header>
                <TextBlock Text="Expander"/>
            </muxc:Expander.Header>
        </muxc:Expander>
    </StackPanel>
</Page>
```

MainPage.idl
```idl
namespace UwpCpp
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        String Header;
    }
}
```

Error message
```
>C:\Users\Peter\source\repos\UwpCpp\Generated Files\XamlTypeInfo.g.cpp(112,44): error C2995: 'winrt::Windows::Foundation::IInspectable winrt::UwpCpp::implementation::GetReferenceTypeMember_Header(const winrt::Windows::Foundation::IInspectable &)': function template has already been defined
1>C:\Users\Peter\source\repos\UwpCpp\Generated Files\XamlTypeInfo.g.cpp(106): message : see declaration of 'winrt::UwpCpp::implementation::GetReferenceTypeMember_Header'
1>C:\Users\Peter\source\repos\UwpCpp\Generated Files\XamlTypeInfo.g.cpp(200,6): error C2995: 'void winrt::UwpCpp::implementation::SetReferenceTypeMember_Header(const winrt::Windows::Foundation::IInspectable &,const winrt::Windows::Foundation::IInspectable &)': function template has already been defined
1>C:\Users\Peter\source\repos\UwpCpp\Generated Files\XamlTypeInfo.g.cpp(192): message : see declaration of 'winrt::UwpCpp::implementation::SetReferenceTypeMember_Header'
```

### Steps to reproduce the bug

Create a C++/WinRT UWP project, install winui2 nuget package, use the code above

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Windows version

Windows 11 (22H2): Build 22621

**Comment by HO-COOH** [comment]
I found this bugs me so much. I just wasted another afternoon trying to figure out the source of the duplicate template function. I found out that you don't even need to have that `TextBlock`. Simply add a property called `Header` in the `idl` file (remove that `TextBlock` in my original post), and the compilation error appears.

**Comment by HO-COOH** [comment]
To avoid getting closed, this issue still exist on WinUI 2.8.5. Fortunately windows app sdk seems good.

**Comment by JesseCol** [comment]
Thanks for filing!  Unfortunately we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).

**Comment by JaiganeshKumaran** [comment]
Same XAML-compiler bug probably also exists in WinUI 3.

**Comment by JesseCol** [comment]
Hello, the issue opener has noted above that they don't see this problem in WinAppSDK.  If you still see a problem here, feel free to open a new issue with WinAppSDK-specific repro steps.  Thanks!
