### ISSUE TITLE
Discussion: [Cannot able to Run any other .exe or .mp3 file from winui3]

### ISSUE THREAD

**Issue by Mohan-Babblu** [microsoft/microsoft-ui-xaml#7316]
Hi Currently I am working in a winui3 application , where I need to open an .mp3 audio file on button click , whenever I try to click the button , it will throw win32 unhandled exception debugger doesn't know how to debug this kind of exception . 
This is the code I've  used to :

        private void Button_Click(object sender, RoutedEventArgs e)
        {
           
            string a = "C:\\AudioRecording\\AudioRecording_20220704121343.mp3";
            Process.Start(a);        
        }

Note : The same code I've tried in WPF and it is working properly .

**Comment by rocksdanister** [comment]
Use this code instead:
```cs
string a = "C:\\AudioRecording\\test.mp3";
var ps = new System.Diagnostics.ProcessStartInfo(a)
{
    UseShellExecute = true,
    Verb = "open"
};
System.Diagnostics.Process.Start(ps);
```
**Documentation:**
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=net-6.0
The reason its required is because `The default is true on .NET Framework apps and false on .NET Core apps.` unlike framework apps.

**Comment by Mohan-Babblu** [comment]
@rocksdanister Thank you
