### ISSUE TITLE
Using Narrator in scan mode can crash the app when there is an invisible hyperlink in a TextBlock

### ISSUE THREAD

**Issue by h82258652** [microsoft/microsoft-ui-xaml#7319]
### Describe the bug

When a ```TextBlock``` contains a ```Hyperlink``` and there is not enough space to display this ```Hyperlink```, using Narrator in scan mode and navigating to this element, the app will crash.
Like this:
```xaml
    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button Content="Justin" />
        <TextBlock
            Width="200"
            Height="50"
            TextWrapping="Wrap">
            <Hyperlink NavigateUri="https://www.baidu.com/">Hello world</Hyperlink>
            <Run>Hello world wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww</Run>
            <Hyperlink NavigateUri="https://www.baidu.com/">Hello world</Hyperlink>
        </TextBlock>
        <Button Content="Rudy" />
    </StackPanel>
```

I have created a demo repo to show this bug: https://github.com/h82258652/NarratorTextBlockBugDemo

### Steps to reproduce the bug

1. Launch Narrator.
2. Enter scan mode.
3. Navigate to the ```TextBlock``` element.

### Expected behavior

The app should not crash.

### Screenshots

I record a video for this bug.

https://user-images.githubusercontent.com/5144550/177262857-63ba508b-8a7e-481e-a7eb-855a0acabb5c.mp4

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK.1.2.221109.1` has been released which fixes this issue.
		
Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2.0/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221109.1)

cc: @JJBrychell
