### ISSUE TITLE
NavigationView Accessibility: Control does not support deselecting menu items

### ISSUE THREAD

**Issue by joshkoon** [microsoft/microsoft-ui-xaml#732]
**Describe the bug**
When using Narrator, users should be able to select/deselect the active item via spacebar. Selection works; deselection does not.

**Steps to reproduce the bug**
1. Create an app with a NavigationView
2. Launch the app and observe the default behavior is all nodes are deselected
3. Select an item
4. Attempt to deselect the active item via spacebar - with or without Narrator. Selection does not change, and SelectionChanged event does not fire. ItemInvoked does fire. Behavior is identical when using the Enter key, but should be different.

**Expected behavior**
Item deselects. SelectionChanged event fires, allowing developers to handle the event to hide UI

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (latest)                   | Yes  |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Deselecting items is blocked no matter whether accessibility or even programmatically. This is by design.
