### ISSUE TITLE
NavigationView memory leak

### ISSUE THREAD

**Issue by l619534951** [microsoft/microsoft-ui-xaml#7322]
### Describe the bug

after navigate many times, memory usage is increased and has not been recycled.  
both packaged and unpackaged has the problem.

### Steps to reproduce the bug

1. run demo project.  
2. click "Content Grid" item.  
3. click "Blank" item.  
4. repeat step 1-2 many many times.  
5. memory has not been recycled.(also appears when Frame Element IsNavigationStackEnabled="False")  

### Expected behavior

memory should  be recycled.

### Screenshots

![leak](https://user-images.githubusercontent.com/17621099/177466412-ee4cc4ce-204e-40a3-a481-dd8d3d201214.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### demo is here
https://github.com/l619534951/NavMemLeak  
> it's created by VS2022 extendsion "Template Studio for WinUI (C#)", and all the code is default.  
https://marketplace.visualstudio.com/items?itemName=TemplateStudio.TemplateStudioForWinUICs  
Memory leak also appears in the project that I created by "Windows App SDK C# VS2022 Templates"

**Comment by l619534951** [comment]
It seems to be the bug of [CsWinRT](https://github.com/microsoft/CsWinRT),and also appears in a simple ListView with text, There is no good idea for that now, close issue.

**Comment by krschau** [comment]
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5978
