### ISSUE TITLE
double Microsoft.UI.Input.PointerPoint.Position should be int

### ISSUE THREAD

**Issue by Padanian** [microsoft/microsoft-ui-xaml#7323]
### Describe the bug

Consider the following

```
` 
        Microsoft.UI.Input.PointerPoint ptrPt;
        IntPtr hWnd;
        WindowId windowId;
        AppWindow appWindow;

        private void Grid_PointerMoved(object sender, PointerRoutedEventArgs e)
        {
             hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
             windowId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);
             appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(windowId);
             ptrPt = e.GetCurrentPoint(null);

             eDiff.X =  appWindow.Position.X + (int)ptrPt.Position.X;
             eDiff.Y =  appWindow.Position.Y + (int)ptrPt.Position.Y;

             // Set the new point
             appWindow.Move(eDiff);

        }

`
```

Is there any good reason why appWindow.Position.X is int while the pointer position is double?

### Steps to reproduce the bug

See example above

### Expected behavior

Pointer should be int.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by krschau** [comment]
@jlnordin, is this something you can speak to?

**Comment by jlnordin** [comment]
There are a few reasons:

- AppWindow uses integers to better integrate with Win32 HWND concepts. A Win32 window can only be positioned on integer boundaries, so we use Ints in that API.
- Windows App SDK's PointerPoint (`Microsoft.UI.Input.PointerPoint`) is based on the Windows Platform SDK's PointerPoint (`Windows.UI.Input.PointerPoint`) and we wanted to make porting between these two easier.
- PointerPoint can also be arbitrarily modified by scales, rotations, or other transformations depending on how it is used, such as when delivered in relation to a Xaml element with custom scaling. To support these scenarios we use doubles.
