### ISSUE TITLE
AppBarButton PointerPressed Event doesn't fire

### ISSUE THREAD

**Issue by Padanian** [microsoft/microsoft-ui-xaml#7324]
### Describe the bug

As per title, AppBarButton UIElement only fires Click, but not PointerPressed

XAML
```

        <AppBarButton HorizontalAlignment="Left" Label="Move" PointerPressed="Window_PointerPressed">
            <AppBarButton.Icon>
                <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE759;" />
            </AppBarButton.Icon>
        </AppBarButton>



```
C#
```
        private void Window_PointerPressed(object sender, PointerRoutedEventArgs e)
        {
            ptrPtStart=e.GetCurrentPoint(sender as UIElement );
        }
```

### Steps to reproduce the bug

copy and paste provided sample into new solution

### Expected behavior

PointerPressed shall fire before Click, as the latter is fired on release

### NuGet package version

WinUI 3 - Windows App SDK 1.1.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by DHancock** [comment]
According to [UIElement.PointerPressed](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.pointerpressed?view=windows-app-sdk-1.1) that is intended, as indicated:

>Specific Windows Runtime controls may have class-based handling for the PointerPressed input event. If so, the control probably has an override for the method [OnPointerPressed](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.onpointerpressed(windows.ui.xaml.input.pointerroutedeventargs)). Typically the event is marked handled by the class handler, and the PointerPressed event is not raised for handling by any user code handlers on that control. For example, [ButtonBase](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.primitives.buttonbase?view=windows-app-sdk-1.1) has class handling that handles PointerPressed and instead fires [Click](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.primitives.buttonbase.click?view=windows-app-sdk-1.1).

**Comment by Padanian** [comment]
Supposed it is so, how to circumvene it, if possible at all?

**Comment by DHancock** [comment]
I don't know if you can, but then why you want to. I'm guessing that the windows ui designers are trying to ensure a standard button behaviour.

**Comment by MikeHillberg** [comment]
If there is some reason you need to circumvent, the [AddHandler](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.addhandler?view=windows-app-sdk-1.1) method has a `handledEventsToo` parameter to get a handler called even for the case where an upstream event handler has set `Handled` in the event args.

**Comment by sigmarsson** [comment]
Tried both way for size to have the event fired but to no avail. ```PointerPressed``` never fired on this user control. How can I implement a draggable user control ?

```
    public sealed partial class ChartLegendView : UserControl
    {
        public ChartLegendView()
        {
            InitializeComponent();

            PointerPressed += new PointerEventHandler(OnPointerPressed);
            
            AddHandler(UIElement.PointerPressedEvent, new PointerEventHandler(OnPointerPressed), true);
        }

        private void OnPointerPressed(object sender, PointerRoutedEventArgs args)
        {
            var point = args.OriginalSource as PointerPoint;

            if (point.Properties.IsLeftButtonPressed)
            {
                CapturePointer(args.Pointer);

                args.Handled = true;
            }
        }
    }
```

**Comment by DHancock** [comment]
Are you sure that your user control has focus? I had to add the following event handler in mine:

in the constructor:

```c#
LosingFocus += Cell_LosingFocus;
````

and the handler:

````c#
    // Above every thing else in the visual tree is a scroll viewer that's
    // provided by Microsoft. It steals focus immediately after a User
    // Control receives focus. This cancels that focus change.
    private void Cell_LosingFocus(UIElement sender, LosingFocusEventArgs args)
    {
        if (args.NewFocusedElement is ScrollViewer)
        {
            bool cancelled = args.TryCancel();
            Debug.Assert(cancelled);
        }
    }
````

(of course, you may need extra logic if it contains it's own ScrollViewer)

**Comment by sigmarsson** [comment]
@Padanian probably you ought to put a ```Grid``` onto your ```AppBarButton.Icon```, which receives ```Pointer*``` events. I tried the above snippet with a ```TeachingTip``` , neither does it work.

**Comment by Padanian** [comment]
Thanks, but I dropped WinUI altogether. This was not the only problem I came across. I reverted my app back to WPF and happy.

**Comment by eliyahuA** [comment]
Seems I got it to work, might be useful for future reference

```
Button button = new()
PointerEventHandler h = (sender, e) =>  this.logger.Info("PointerPressed has fired");
button.AddHandler(UIElement.PointerPressedEvent, h, true);
button.Click += (sender, e) =>  this.logger.Info("Click event has fired");
```
output:
```
Info|2024-07-20 23:12:43.7143|: Click event has fired
Info|2024-07-20 23:12:43.7143|: PointerPressed has fired
```
`button.ClickMode`  will influence regarding what fires first, PointerPressed  or Click 

> Tried both way for size to have the event fired but to no avail. `PointerPressed` never fired on this user control. How can I implement a draggable user control ?
> 
> ```
>     public sealed partial class ChartLegendView : UserControl
>     {
>         public ChartLegendView()
>         {
>             InitializeComponent();
> 
>             PointerPressed += new PointerEventHandler(OnPointerPressed);
>             
>             AddHandler(UIElement.PointerPressedEvent, new PointerEventHandler(OnPointerPressed), true);
>         }
> 
>         private void OnPointerPressed(object sender, PointerRoutedEventArgs args)
>         {
>             var point = args.OriginalSource as PointerPoint;
> 
>             if (point.Properties.IsLeftButtonPressed)
>             {
>                 CapturePointer(args.Pointer);
> 
>                 args.Handled = true;
>             }
>         }
>     }
> ```

**Comment by eduardobragaxz** [comment]
Thanks @eliyahuA!
