### ISSUE TITLE
[WinUI3] Question: Where is Control.IsEnabled ?

### ISSUE THREAD

**Issue by dojo90** [microsoft/microsoft-ui-xaml#7325]
The `Control.IsEnabled` property is not available anymore. I also couldn't find any informations about it. Can someone please update me on how to disable a control?

see: https://docs.microsoft.com/de-de/windows/winui/api/microsoft.ui.xaml.controls.control.isenabled

**Comment by dojo90** [comment]
Ah I have overlooked something.
My problem is that I would like to disable the `Grid` and all inner `controls` should be disabled as well.

`Grid` is a `Panel` / `framework element` and not a `Control`. So the corresponding property is missing there.

**Comment by castorix** [comment]
> My problem is that I would like to disable the Grid and all inner controls should be disabled as well.

You can use a parent control (like a  **ContentControl** for example)
and all child controls will be disabled with IsEnabled = false

**Comment by krschau** [comment]
@dojo90 Please try @castorix's suggestion of using a ContentControl. I think this will work so I'm closing the issue, but you can still comment here if you have trouble with this solution.

**Comment by legistek** [comment]
I do have trouble with the solution - it's overkill; it makes the visual tree more complicated, harder to debug, etc., is a needless performance drain.

But someone 10+ years ago, no doubt worried about Surface RT performance, decided to ditch inheritable DPs, and we're still stuck with that decision.
