### ISSUE TITLE
segoe-fluent-icons-font - StockDown and StockUp icons are other way around

### ISSUE THREAD

**Issue by Rafaelki** [microsoft/microsoft-ui-xaml#7332]
### Describe the bug

It seems that SharePoint is changing its icons from [Fluent UI](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons#available-icons) to [segoe-fluent-icons-font](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font).

Our product has been using icons from Fluent UI in production environments for a while now and suddenly these icons have changed. We are having many complaints from clients as this was unexpected, but the bug that I want to raise is related specifically to these 2 icons, StockDown and StockUp which seem to be the other way around. We use them in production environments to indicate the direction of the stock so please fix them as soon as possible.

![image](https://user-images.githubusercontent.com/24438807/177749338-73a0314d-65bb-4c5f-ac71-c0b1463b2f83.png)

### Steps to reproduce the bug

Go to https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font and find StockDown and StockUp	

### Screenshots

![image](https://user-images.githubusercontent.com/24438807/177750320-acb4ea80-6dc2-412b-b215-889d72f06ef3.png)

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by krschau** [comment]
@Rafaelki thanks for pointing this out! We're fixing it and it should go out with the next font refresh.

**Comment by Marweis** [comment]
Is there an ETA for this fix?

**Comment by krschau** [comment]
I want to clarify that WinUI/Xaml has no control over the fonts, this issue just happened to be noticed here and I escalated it internally. As such, my understanding (but I am not sure of this) is that the fix will go out in a fall OS update. I've been told this wouldn't be serviced downlevel, so if you really want to use these specific characters, you may want to check what OS version is running and switch them if necessary.

We understand this isn't ideal. Instead, I would use these characters:
U+F08E CaretSolidDown
U+F090 CaretSolidUp
U+F0AE ArrowDown8
U+F0AD ArrowUp8
The CaretSolid ones are particularly similar.

I've also noticed that the [documentation](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font) has been changed to reflect the characters as they should and will be. I've asked that a note be included to indicate that on some builds they are swapped.
