### ISSUE TITLE
Can't build with ARM64 version of Visual Studio

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#7347]
### Describe the bug

When using the latest preview of Visual Studio 2022 for ARM64, compiling WinUI from commandline causes the following error:

```
(MarkupCompilePass2 target) ->
  C:\Users\mn\.nuget\packages\microsoft.windowsappsdk\1.1.2\buildTransitive\..\tools\net472\..\x64\genxbf.dll : X
amlCompiler error WMC0621: Cannot resolve 'GenXbf.dll' under path 'C:\Users\mn\.nuget\packages\microsoft.windowsa
ppsdk\1.1.2\buildTransitive\..\tools\net472\..\x64\genxbf.dll'.  Please ensure that the Nuget was properly restored and
 that the path is available on disk. 
```

There is an ARM64 version of `genxbf.dll` in `\tools\arm64\` and if I take that and copy it into the x64 folder, the build does work. Looks like it is mostly an issue of not loading the correct DLL in the xaml compiler.

### Steps to reproduce the bug

Install VS2022 Preview onto a PC with Windows 11 ARM64.
Open the VS Developer Prompt and compile a WinUI 3 project with msbuild.

### Expected behavior

Build compiles fine on ARM64

### NuGet package version

1.1.2

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

### Additional context

Same thing happens from within VS:
![image](https://user-images.githubusercontent.com/1378165/178032661-081679e9-de52-4159-9af2-2c2a6b3b2cbe.png)

**Comment by krschau** [comment]
This looks like a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/7140, and we're tracking it internally with http://task.ms/39763998.

**Comment by krschau** [comment]
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/7140
