### ISSUE TITLE
Setting SelectedIndex to -1 on a ComboBox still displays the first item as selected

### ISSUE THREAD

**Issue by bogdan-patraucean** [microsoft/microsoft-ui-xaml#7348]
### Describe the bug

Sometimes the available options in a ComboBox are not yet configured so I don't want to show any of them as selected. To do that I try to set SelectedIndex to **-1**. That I can do but, the first ComboBox item is still displayed as being selected in the dropdown.

### Steps to reproduce the bug

Create a ComboBox with 3 options and set SelectedIndex to -1:

_.xaml file_

```
<ComboBox PlaceholderText="Select Option" SelectedIndex="-1">
     <TextBlock Text="Option 1"></TextBlock>
     <TextBlock Text="Option 2" ></TextBlock>
     <TextBlock Text="Option 3" ></TextBlock>
</ComboBox>
```

### Expected behavior

Once I set SelectedIndex to -1 I expect no option to be displayed as selected in the dropdown.

### Screenshots

ComboBox collapsed (notice that the placeholder is displayed here because SelectedIndex is -1):
<img width="120" alt="image" src="https://user-images.githubusercontent.com/26826125/178122113-094f4260-b86b-4bb5-ba7a-be97c8f90190.png">

ComboBox with dropdown opened (notice that even SelectedIndex is -1, **Option 1** is displayed as selected):
<img width="115" alt="image" src="https://user-images.githubusercontent.com/26826125/178122130-9b417b6a-10a1-43ce-a4a5-95bc6a35416c.png">

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

### Additional context

I even tried wrapping each  item in a ComboBoxItem with IsSelected = false, but still the same problem.

```
<ComboBox PlaceholderText="Select Option" SelectedIndex="-1">
     <ComboBoxItem IsSelected="False">
              <TextBlock Text="Option 1"></TextBlock>
      </ComboBoxItem>
      <ComboBoxItem IsSelected="False">
              <TextBlock Text="Option 2"></TextBlock>
      </ComboBoxItem>
      <ComboBoxItem IsSelected="False">
               <TextBlock Text="Option 3"></TextBlock>
      </ComboBoxItem>
</ComboBox>
```

**Comment by bogdan-patraucean** [comment]
Any updates on this?

**Comment by ranjeshj** [comment]
@bogdan-patraucean this is by design. The dropdown is showing that you are 'selecting' option 1. It is not selected yet. You can hit esc and not choose a selection to get back to the collapsed state with nothing selected.

**Comment by bogdan-patraucean** [comment]
@ranjeshj thanks for the update. It's very counterintuitive for the end user. Please consider improving the UX because the item looks exactly the same the it's selected and when it's not.
