### ISSUE TITLE
Link to install WebView2 for WinUi2 (UWP) application lead to wrong page

### ISSUE THREAD

**Issue by TiMeJuMp** [microsoft/microsoft-ui-xaml#7354]
### Describe the bug

If the user does not have WebView2 installed in a WinUI2 app, the provided link does not link correct to the part what is needed to install.
What is missing, that the user needs to also install Microsoft Edge Dev/ Beta/Canary to get WebView2 work correctly. 
Probably you can add this information. 

Is there a plan, when Microsoft Edge (production) has everything build in, that a user does not have to install Dev/beta / can Build? 

### Steps to reproduce the bug

Precondition: Pc with not installed WebView2 and not installed Microsoft Edge Dev / Beta / Can
1. Implement WebView2 in WinUI2 (UWP) app
2. Download and Start app
3. See error Message

**Comment by aquinn39** [comment]
@krschau I have this issue as well. When I click the link though it doesn't take me to the right place, it just goes to https://developer.microsoft.com/en-US/microsoft-edge/ for me. Also, with what you're saying about WebView 2 distribution, is this going to be done via Windows Update or the Microsoft Store (i.e. The Store installs it if necessary when an app that requires it is install from the Store like with WinUI 2) or some other way?

![Screenshot 2022-07-21 020608](https://user-images.githubusercontent.com/43898231/180030615-e5cdd07d-0f56-45be-a06b-5391319567d4.png)

**Comment by krschau** [comment]
@TiMeJuMp @aquinn39 It looks like there's an issue with link re-direction in certain cases. I'm looking into it. Some questions for you that might help us:
- Are you on Windows 10?
- Do you have a language other than English set as the default language on your machine, or in your browser, or in your app?

@aquinn39 There's a bunch of good info about the rollout of the WebView2 runtime in this [blog post](https://blogs.windows.com/msedgedev/2022/06/27/delivering-the-microsoft-edge-webview2-runtime-to-windows-10-consumers/). If you've got more questions specifically about that, they link to their GitHub and Twitter at the bottom and will be able to help.

**Comment by aquinn39** [comment]
@krschau Thanks for the link to the blog post about the rollout of the WebView 2 runtime.
Yep I'm happy help you out with those questions.

- Yes, the screenshot I sent was from a Virtual Machine running Windows 10 version 1909 (OS Build 18363.1556)
- The VM's language is set to English (Australia) but also has English (United States) installed. I haven't changed the language settings in the app so it should be using the system default. The browser I was using (Edge) has English (Australia) as its default language as well but also has English (United States) and English added.
Here is Windows and Edge's language settings from the VM if it helps:
![image](https://user-images.githubusercontent.com/43898231/184093373-dfe186c2-47dd-41d2-8c11-b7645e4b878b.png)
![image](https://user-images.githubusercontent.com/43898231/184093494-068546ca-7775-492b-a47e-d7e68b0f825b.png)

- I'm in Australia (And the VM's country or region setting is set to Australia)

**Comment by krschau** [comment]
@aquinn39 Thanks for the detailed response! We have someone in this area looking at it, although she's been unable to repro so far. If you want, you could try looking running Fiddler (or similar tool) to capture the incoming requests and headers. 

I'll say, even though I know this isn't a great response, that this problem is only going to get more and more rare as we push the WV2 runtime to as many Win10 users as we can. This effort is happening pretty quickly, and you can read more about it here: https://blogs.windows.com/msedgedev/2022/06/27/delivering-the-microsoft-edge-webview2-runtime-to-windows-10-consumers/.

**Comment by aquinn39** [comment]
@krschau Just tested this again on a Windows 10 1909 VM and the link worked!
