### ISSUE TITLE
ListView horizontal scrolling not working

### ISSUE THREAD

**Issue by skanvk15** [microsoft/microsoft-ui-xaml#7362]
### Describe the bug

Horizontal scrolling on ListView does not work. The horizontal bar cannot be dragged. Clicking on the left or right side moves bar incrementally but does not scroll.

### Steps to reproduce the bug

1. Create WinUI 3 app with MainWindow.xaml:
```
<Window
    x:Class="ListViewScrollTest.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:ListViewScrollTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <ListView
            ScrollViewer.HorizontalScrollBarVisibility="Auto"
            ScrollViewer.VerticalScrollBarVisibility="Auto"
            ItemsSource="{x:Bind ListItems}">
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="local:Item">
                    <Grid ColumnSpacing="20">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="120"/>
                            <ColumnDefinition MaxWidth="240"/>
                        </Grid.ColumnDefinitions>

                        <TextBlock Grid.Column="0" Text="{x:Bind Key}" TextWrapping="NoWrap"/>
                        <TextBlock Grid.Column="1" Text="{x:Bind Value}" TextWrapping="NoWrap"/>
                    </Grid>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </Grid>
</Window>
```

2.  Add following code to MainWindow.xaml.cs
```
using Microsoft.UI.Xaml;
using System;
using System.Collections.Generic;

namespace ListViewScrollTest
{
    /// <summary>
    /// An empty window that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();

            for (int i = 0; i < 10; ++i)
            {
                ListItems.Add(new Item() { Key = $"key {i} {Guid.NewGuid()}", Value = $"value {i} {Guid.NewGuid()}" });
            }
        }

        public List<Item> ListItems = new List<Item>();
    }

    public class Item
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }
}
```

3. Run and resize window so horizontal scroll bar on ListView is shown

4. Try to scroll horizontally

### Expected behavior

Horizontal scrolling should work

### Screenshots

![image](https://user-images.githubusercontent.com/51756883/178522471-ea2b37fc-ca45-4900-819a-d46be74faa6f.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.2

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ranjeshj** [comment]
you need to set a few more properties for horizontal scrolling to work. can you try setting these on the ListView?
        ScrollViewer.HorizontalScrollBarVisibility="Auto"
        ScrollViewer.VerticalScrollBarVisibility="Disabled"
        ScrollViewer.HorizontalScrollMode="Enabled"
        ScrollViewer.VerticalScrollMode="Disabled"

**Comment by GuildOfCalamity** [comment]
This still appears to be a problem when the content is inside a `<Frame>` from a `<NavigationView>`
