### ISSUE TITLE
Proposal: Make WinUI test framework generic and one of the best UI automation test option in visualstudio|Testing

### ISSUE THREAD

**Issue by licanhua** [microsoft/microsoft-ui-xaml#737]
# Proposal: Promote winui test infrastucture

[UI automation](https://docs.microsoft.com/en-us/visualstudio/test/use-ui-automation-to-test-your-code?view=vs-2019) is very important for customer to deliver high quality application.
And winui solution is very mature and stable, and easy to integrate with Azure pipeline.
We already have sperate projects for winui API testing and e2e testing. it's possible to make them generic and reused by all UWP apps.

## Summary

Goal: Make winui test infrastructure reused by other projects
Steps:
1. Make API testing and e2e testing project generic and independent on winui
2. publish them as nuget
3. winui consume the nuget.
4. Update document on visualstudio|testing

## Open Questions

Why winui is more robust than other automation framework?

**Comment by YuliKl** [comment]
@licanhua - can you be super specific about what's valuable and what can be shared that isn't already available?

**Comment by jevansaks** [comment]
@licanhua when you have time to add more details you can re-open this.
