### ISSUE TITLE
MenuFlyout show with incorrect size sometime(100% Reproduce)

### ISSUE THREAD

**Issue by l619534951** [microsoft/microsoft-ui-xaml#7374]
### Describe the bug

MenuFlyout show with incorrect size when it's show before user click window.( item height = 40 )
[MenuFlyoutBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9113187/MenuFlyoutBug.zip)
 

### Steps to reproduce the bug

1. run demo.  
2. do not click window, wait for demo startup, and MenuFlyout show automatically, it's height equal to red background rect area's height. (MenuItem = 40)  
3. click button, and MenuFlyout show again, it's height equal to green background rect area's height.  (MenuItem = 32)
> ps: if mouse move over window content( not include title bar) before the menu show, the menu will show with correct size. 

### Expected behavior

MenuItem height = 32

### Screenshots

![f1](https://user-images.githubusercontent.com/17621099/179021408-a0a72b65-4c3a-4b01-b067-2d5f185556b0.png)
![f2](https://user-images.githubusercontent.com/17621099/179021414-75d21e1c-7bc8-4a10-9a73-4819a8e5b4cf.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.2

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

if replace StackPanel_Loaded with the code below, and click window before menu show, it's will show with correct size.
```
private void StackPanel_Loaded(object sender, RoutedEventArgs e)
{
    Task.Run(() =>
    {
        Thread.Sleep(5000);
        DispatcherQueue.TryEnqueue(() => MyMenu.ShowAt(StackPanel));
    });
}
```

**Comment by krschau** [comment]
This is interesting that even opening the flyout programmatically, it's using the different styles. Thanks for linking to the similar issue, that's really helpful!

**Comment by ranjeshj** [comment]
The size of the items depend on the last input mode. If you use touch, the items are larger so that they are easier touch targets. If you use mouse, they can be smaller so you dont have to move the mouse far to reach the items. When doing programmatically, I expect the last input method will be used.

**Comment by l619534951** [comment]
the last input is from mouse's click (before the app run), and the screen is non-touch. I suppose get the last input mode from system or detect screen is touchable should be better for that.

**Comment by eskaufel** [comment]
> The size of the items depend on the last input mode. If you use touch, the items are larger so that they are easier touch targets. If you use mouse, they can be smaller so you dont have to move the mouse far to reach the items. When doing programmatically, I expect the last input method will be used.

It seems that touch is used as a fallback if there are no registered input. Do you know if there are any apis to disable touch rendering or in any other way possible to override this behavior @ranjeshj?

**Comment by HO-COOH** [comment]
Glad I find this issue so that I don't waste another week on this

**Comment by ranjeshj** [comment]
@eskaufel I'm not aware of any APIs to get that behavior. We use the last interaction mode to decide how to show. If you don't interact, then there is a default. The default is touch so that it is accessible. Sorry, there are no plans to update this behavior.
