### ISSUE TITLE
`ListViewBase.ItemClick` can be triggered with a null `ItemClickEventArgs.ClickedItem` even if it does not contain any null item.

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#7382]
### Describe the bug

The system `ListView` and `GridView` controls exhibit an unexpected behavior when their items are reordered while a `ListViewBase.ItemClick` event is being processed. It seems that there is some internal race inside the control since we can receive a null `ItemClickEventArgs.ClickedItem` in the event even if there is no null item within the list.

This issue can easily by hit in our application but I didn't find a way to reproduce this issue in a sample app 😥. It seems to depend on the complexity on the template, the load on the UI thread and the click speed.

### Steps to reproduce the bug

To repro the issue, we need to click several times on a list item and the first click triggers a reorder of the list.

1. click on list view item
2. ItemClick event is raised
3. list is reordered
4. 2nd click
5. ItemClick event is raised with a null item

### Expected behavior

`ItemClickEventArgs.ClickedItem` should not be null if the list does not contain any null values.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx), Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044

**Comment by ranjeshj** [comment]
@vgromfeld does the re-order need to happen in the click event? I'm thinking that the indices/items in the collection are changing because of the re-order. You can try doing the re-order in a dispatcher call so it does'nt happen in the same callstack.

**Comment by vgromfeld** [comment]
@ranjeshj, there is no re-order initiated during the click event. It seems that clicking then re-ordering then clicking again triggers the issue, but it does not repro everytime....

**Comment by ranjeshj** [comment]
@vgromfeld can you share a repro app and specific steps when you get a chance ?

**Comment by tipa** [comment]
I'm also seeing crashes (not on my machine, but on clients devices) where the `ClickedItem` property is null. I do not use re-ordering (only insert/delete) and the template is pretty complex. I'm also using a `CollectionViewSource` and `GroupStyle`
