### ISSUE TITLE
`NavigationViewItem` is sending an unexpected `Unloaded` event

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#7387]
### Describe the bug

`NavigationViewItem` is sending both a `Loaded` and an `Unloaded` event when it loads.

### Steps to reproduce the bug

1. Use the following XAML:
```xml
 <muxc:NavigationView x:Name="navigationView">
    <muxc:NavigationView.MenuItems>
        <muxc:NavigationViewItem Content="Item 1" />
        <muxc:NavigationViewItem Content="Item 2" />
    </muxc:NavigationView.MenuItems>
</muxc:NavigationView>
```
2. And the following code behind:
```cs
public MainPage()
{
    InitializeComponent();
    AddNavigationViewItem();
}

private void AddNavigationViewItem()
{
    var item = new Muxc.NavigationViewItem
    {
        Content = "Other item",
        Tag = "tag",
    };
    item.Loaded += OnLoaded;
    item.Unloaded += OnUnloaded;

    navigationView.MenuItems.Insert(2, item);
}

private void OnLoaded(object sender, RoutedEventArgs e) => Trace.WriteLine("## loaded");

private void OnUnloaded(object sender, RoutedEventArgs e) => Trace.WriteLine("## unloaded");
}
```
3. Run the application
4. The debugger output window displays:
```
## loaded
## unloaded
````
Whereas the `NavigationViewItem` is still loaded and working in the app.

### Expected behavior

The `Unloaded` event must not be sent if the control is not unloaded.

### NuGet package version

Microsoft.UI.Xaml 2.7.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The `2.8.0-prerelease.220712001` build does not seem to have the issue but since it is only `prerelease`, I cannot use it ☹️

**Comment by krschau** [comment]
@vgromfeld, since you say this doesn't repro in 2.8-prerelease, can you try it in the stable 2.8 release that [just came out](https://github.com/microsoft/microsoft-ui-xaml/discussions/7391)?
