### ISSUE TITLE
SetDragRectangles doesn't work with changing rects

### ISSUE THREAD

**Issue by jamers99** [microsoft/microsoft-ui-xaml#7392]
### Describe the bug

`AppWindow.TitleBar.SetDragRectangles` works well for the most part, clunky as it is, it's pretty straightforward.

However, when you need to change the rectangles (UI changed in title bar) there is a bug that it doesn't completely update.

### Steps to reproduce the bug

1. Create an app that has interactive content that may change in size in the title bar.
2. Make on the interactive content `SizeChanged` event, calculate the Rect and call `SetDragRectangles`
3. Run the app
4. Change the interactive content size
5. Try to interact in the new area that would have previously been part of the grip
**It doesn't interact with the element.** _It doesn't even grip... it just blocks interaction. If you right click it pops the window menu._

Here is a simple project reproducing the issue: [TitleBarTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9134501/TitleBarTest.zip)

### Expected behavior

It should fully update and I should be able to interact with my control everywhere, including in the new space it took up.

### Screenshots

Here is a video describing the issue.
https://user-images.githubusercontent.com/20806279/179582055-4fe6d676-a3e2-4e24-9ddf-6b5a9ebb0d24.mp4

### NuGet package version

WinUI 3 - Windows App SDK 1.1.2

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

This is incredibly important to our app. We have browser style tabs in our title bar.

**Comment by ghost1372** [comment]
related to
https://github.com/microsoft/WindowsAppSDK/issues/2518

**Comment by jamers99** [comment]
@mevey do you think this will be fixed when microsoft/WindowsAppSDK#2518 is fixed?

**Comment by jamers99** [comment]
This was resolved in microsoft/WindowsAppSDK#2574! See microsoft/WindowsAppSDK#2953 for additional discussion.
