### ISSUE TITLE
[InfoBar] Successful severity uses an ugly background color

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/microsoft-ui-xaml#7400]
### Describe the bug

Setting the InfoBar.Severity property to Success uses an ugly background color

![image](https://user-images.githubusercontent.com/1608424/180010971-68db4cfb-af9c-415b-9cfb-2d932c1e041a.png)

### Steps to reproduce the bug

InforBar.Severity="Success"

### Expected behavior

Something nicer!

### Screenshots

![image](https://user-images.githubusercontent.com/1608424/180010944-8d86d990-8b44-407c-ab81-079ecfe83889.png)

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [X] UWP
- [ ] Win32

**Comment by Jay-o-Way** [comment]
It's just dark green? "Ugly" is a very personal opinion. Got a suggestion for something better?

**Comment by ArchieCoder** [comment]
yes, this is of course a personal opinion, but I have yet to see this color palette in any official Windows app for a successful message. 

GitHub green color would be better as an example.

![image](https://user-images.githubusercontent.com/1608424/185803870-00aad004-ec21-4351-a879-01290657393a.png)

**Comment by Jay-o-Way** [comment]
I think that's because of the transparency. Using 100% green icon on a 100% green background is a no-go: It won't be even visible. And the color(s) is/are too bright to match the light/dark theme.

**Comment by mdtauk** [comment]
The green has a yellow bias, I brought up this specific colour back when the control first appeared.
https://github.com/microsoft/microsoft-ui-xaml/issues/913#issuecomment-736479707
