### ISSUE TITLE
TeachingTip on Xaml Islands requires an package identity.

### ISSUE THREAD

**Issue by azchohfi** [microsoft/microsoft-ui-xaml#742]
**Describe the bug**
Trying to use the TeachingTip on a Xaml Island context requires a package identity.

**Steps to reproduce the bug**
Have a custom xaml island element, and the moment you call ToggleThemeTeachingTip1.IsOpen = true; it will throw an exception:
{"The process has no package identity. (0x80073D54)"}

**Expected behavior**
This should not be required by such a simple control. It should work without an app id.

NuGet package version: 
Microsoft.UI.Xaml 2.2.190430003-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18898)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by azchohfi** [comment]
It is very weird, because if I have the debugger attached, it will actually render the UI thread once more and show the teaching tip, but then it crashes.
![image](https://user-images.githubusercontent.com/527713/58216784-bd18fe00-7cb4-11e9-9817-1b4b1ebf702e.png)

**Comment by jevansaks** [comment]
We're probably calling an API to get the package identity for some telemetry and we should defend against the unpackaged scenario.
