### ISSUE TITLE
Teaching tip - Crash

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/microsoft-ui-xaml#744]
**Describe the bug**

Set the Teaching Tip -> IsOpen = true in design mode run the app , app get crashed

**Steps to reproduce the bug**

1. Add Teaching Tip in XAML and set IsOpen = true & build
2. Start the app in VS 
3. App get crashed

**Expected behavior**
Starting app , teaching tip show in the screen.

**Screenshots**

**Version Info**
Microsoft.UI.Xaml 2.2.190430003 , Windows 10 1903

NuGet package version: 
Microsoft.UI.Xaml 2.2.190430003

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            |    |   Yes
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |  Yes
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by duke7553** [comment]
Hey, I ran into this too and was provided a workaround. https://github.com/microsoft/microsoft-ui-xaml/issues/538

**Comment by duke7553** [comment]
In other words, don’t set isOpen from markup, but set it from the event described in the link a sent.

**Comment by YuliKl** [comment]
Thank you for reporting this issue. Looks like we're already tracking this problem with #538.
