### ISSUE TITLE
Documentation: Need to show an example of using a DataTemplateSelector with ItemsRepeater

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#746]
# Proposal: ItemTemplateSelector for ItemsRepeater

## Summary
Please Add ItemTemplateSelector, just [like ItemsControl has](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemscontrol.itemtemplateselector#Windows_UI_Xaml_Controls_ItemsControl_ItemTemplateSelector)

## Rationale
* ItemsContol has one
* This is usable for presenting collection of mixed data

**Comment by micahl** [comment]
@ad1Dima the ItemTemplate property of the ItemsRepeater accepts a DataTemplate or DataTemplateSelector.  This is something we should explain more clearly in our [documentation](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater#create-an-itemsrepeater) with an example.  I'm converting this issue to a bug to track getting this done.

**Comment by micahl** [comment]
Closing this issue now that the updates to the docs went live this afternoon.  https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater#create-an-itemsrepeater
