### ISSUE TITLE
Dynamic page Navigation WInui3 

### ISSUE THREAD

**Issue by Mohan-Babblu** [microsoft/microsoft-ui-xaml#7522]
Hi Currently I am working in a winui3 application . where I need to use dynamic pages instead of. I'm using NavigationMenuItem controls to Navigate pages , but instead of pages I need to use Dynamic Page navigate .
This is the code I've used :
[DynamicXAMLPages(1).zip](https://github.com/microsoft/microsoft-ui-xaml/files/9178476/DynamicXAMLPages.1.zip)

**Comment by AndrewKeepCoding** [comment]
I took a look at your project but couldn't understand your problem. Can you be more specific?
