### ISSUE TITLE
Windows Server support

### ISSUE THREAD

**Issue by mashbrno** [microsoft/microsoft-ui-xaml#7523]
I'm evaluating WinUI 3 for my application. Several customers use terminals and require running on Windows Server 2016 and newer. These are still supported OSes.
Neither published default Visual Studio 2022 template was unable to run on Windows Server 2022: `This app can't run on your PC`

**Comment by bpulliam** [comment]
There is an OS fix that should resolve this issue.
More details in https://github.com/microsoft/WindowsAppSDK/issues/2829.
