### ISSUE TITLE
WinUI 2.8 broke its support contract

### ISSUE THREAD

**Issue by tim-weis** [microsoft/microsoft-ui-xaml#7525]
### Describe the bug

As [documented](https://docs.microsoft.com/en-us/windows/apps/winui/):

> WinUI 2 works downlevel to Windows 10 Creators Update (Version 1703, OS build 15063).

This is no longer the case with WinUI 2.8, which apparently requires build 17763. This change makes it impossible to use WinUI 2.8 when targeting Windows 10 Mobile. Microsoft may not care about Windows 10 Mobile, but there is a non-zero number of developers that do.

### Steps to reproduce the bug

1. Create a *"Blank App (C++/WinRT)"* project
2. Add a reference to the WinUI 2.8 NuGet package
3. Build the project from VS2022
4. Launch VS2017 and try to deploy the AppX to a Windows 10 Mobile device

The deploy will error out due to the AppX requiring an OS build number of 17763.

Retargeting the application for the latest supported Windows 10 Mobile OS (build 15063) will fail the build.

### Expected behavior

The application should build against the documented minimum OS version (build 15063). I'm not asking to have the referenced documentation updated nilly-willy to reflect the current status. I'm specifically asking you to deliver on your support promise.

If a contract can be terminated unilaterally then that contract has no value. If that is indeed how you're planning to go about this moving forward, then please make sure to be *unambiguously* clear about this in your documentation. That at least gives us something to go off of when we need to pick or reject any particular UI system in the future.

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by nta** [comment]
1. The documentation page lives in [another repository](https://github.com/MicrosoftDocs/windows-uwp/blob/52186d323cca21ca0ce1b648390824563a0a8f71/hub/apps/winui/index.md).
2. Windows 10 Mobile itself is [no longer supported](https://support.microsoft.com/en-us/windows/windows-10-mobile-end-of-support-faq-8c2dd1cf-a571-00f0-0881-bb83926d05c5) as of December 10, 2019.
3. Reference documentation does not in any way imply a contractual promise.
4. Why are you targeting an unsupported operating system?

**Comment by tim-weis** [comment]
> 1. The documentation page lives in [another repository](https://github.com/MicrosoftDocs/windows-uwp/blob/52186d323cca21ca0ce1b648390824563a0a8f71/hub/apps/winui/index.md).

Thanks for the profound insight.

> 2. Windows 10 Mobile itself is [no longer supported](https://support.microsoft.com/en-us/windows/windows-10-mobile-end-of-support-faq-8c2dd1cf-a571-00f0-0881-bb83926d05c5) as of December 10, 2019.

Same.

> 3. Reference documentation does not in any way imply a contractual promise.

Then what does?

> 4. Why are you targeting an unsupported operating system?

Because there is demand. If it helps you sleep better you may assume that I'm targeting HoloLens devices, that are still in support but also dropped below the WinUI 2.8 support baseline.

> 5. WinUI 2 is open-source, you can probably fix this yourself.

It is, *except* for the interesting parts: WebView2. Now even if I were able to fix this in an alternate universe, where do you suggest I push my changes to instruct the Microsoft Store to be a bit more lenient when it comes to WACK-certification of my binaries? There's more to software deployment than `xcopy`-ing binaries to *my* device.

**Comment by driver1998** [comment]
WebView2 never supports ARM32, they have a stub implementation for ARM32. Retargeting to 15063 should be possible with this stub implementation.

**Comment by riverar** [comment]
@tim-weis So basically the support promise was baloney as you suggested. This is the same pattern used by Windows App SDK folks, so no shocker here.
