### ISSUE TITLE
NavigationView regression on WinUI 2.8

### ISSUE THREAD

**Issue by acouvert-msft** [microsoft/microsoft-ui-xaml#7533]
### Describe the bug

A `NavigationViewItem` with its `MenuItems `filled with one or more `NavigationViewItem`, failed to draw the content of `MenuItems` when using WinUI 2.8. 

This is a regression, as such scenario was working perfectly fine with prior version of WinUI.

### Steps to reproduce the bug

Create a UWP project with WinUI 2.8 with the following:

.xaml:
```
<muxc:NavigationView Loaded="NavView_Loaded">
  <muxc:NavigationView.MenuItems>
    <muxc:NavigationViewItem x:Name="items" Content="Items" IsExpanded="True" />
  </muxc:NavigationView.MenuItems>
</muxc:NavigationView>
```

.xaml.cs:
```
private Mux.NavigationViewItem CreateMenuItem(string title)
  => new Mux.NavigationViewItem
  {
    Content = title,
  };

private void NavView_Loaded(object sender, RoutedEventArgs e)
  => items.MenuItems.Add(CreateMenuItem("Item 0"));
```

### Expected behavior

The `NavigationViewItem` which is part of a `NavigationViewItem.MenuItems` is expected to be drawn as it was the case with previous WinUI version.

### Screenshots

WinUI 2.8:
![image](https://user-images.githubusercontent.com/61151817/181003777-ce9ec03c-5d21-4cab-bce9-232f5e6a7c72.png)
![image](https://user-images.githubusercontent.com/61151817/181004057-7a75562b-9229-4f2f-994c-43a4955fa8e8.png)
Note that **Item 0** is not visible whereas `MenuItems` contains the expected elements.

WinUI 2.7.2:
![image](https://user-images.githubusercontent.com/61151817/181004448-dee5760b-d0db-4926-8def-f591caade761.png)
Note that **Item 0** is visible as expected.

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by krschau** [comment]
@ranjeshj FYI

**Comment by HO-COOH** [comment]
Another note on this bug, after adding subitem to the `NavigationViewItem`, the app crash if the panel is manually or automatically compacted.
![image](https://user-images.githubusercontent.com/42881734/182575466-74cc3bcc-ca60-46c9-b8f4-741e417b5a0b.png)
