### ISSUE TITLE
Cannot change NavigationViewItem foreground color in Top mode

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/microsoft-ui-xaml#7534]
### Describe the bug

NavigationViewItem ``Foreground`` is not respected in ``Top`` mode.

This closed issue #2105 might be related.

### Steps to reproduce the bug

```xaml
<NavigationView PaneDisplayMode="Top">
    <NavigationView.MenuItems>
        <NavigationViewItem Content="Default Menu Item" />
        <NavigationViewItem Content="Red Menu Item" Foreground="Red" />
        <NavigationViewItem Content="Green Menu Item" Foreground="Green" />
        <NavigationViewItem Content="Blue Menu Item" Foreground="Blue" />
    </NavigationView.MenuItems>
</NavigationView>
```

### Expected behavior

NavigationViewItem foreground should change in ``Top`` mode as it does in ``Left`` mode.

### Screenshots

``Left`` mode works.
![image](https://user-images.githubusercontent.com/80524586/181173168-4bbd90bd-ac8f-4532-90d1-d8a52c8920b2.png)

``Top`` mode doesn't work.
![image](https://user-images.githubusercontent.com/80524586/181173411-36b6142b-f7c8-42ef-9145-27299edfc686.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000

### Additional context

I also checked these properties but they work without a problem.
- ``Background``
- ``FontSize``
- ``FontWeight``

**Comment by ranjeshj** [comment]
NavigationViewItem Top style is likely not template binding correctly to the foreground property

**Comment by AndrewKeepCoding** [comment]
Removing this line fixes the issue. I'm not sure why there's a separate foreground for Top style.

```xaml
<Setter Target="NavigationViewItemPresenter.Foreground" Value="{ThemeResource TopNavigationViewItemForeground}" />
```

**Comment by AndrewKeepCoding** [comment]
Closing this because it works on WindowsAppSDK v1.3.230602002.
