### ISSUE TITLE
MediaPlayerElement crashes on Windows 10 N SKU

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/microsoft-ui-xaml#754]
Having:

<MediaPlayerElement AutoPlay="False" /> will crash at the call of InitializeComponent(). Even more interesting, if the attribute “AutoPlay=False” is removed, the XAML does not make the app crashes, but the crash will happen later when on a call like: MediaPlayerElement.MediaPlayer.MediaEnded += OnMediaElementEnded since the MediaPlayer is null.

**Steps to reproduce the bug**
Just put the XAML code above in a xaml file and run the code on a Windows 10 N SKU (i.e. version with no media player)

**Expected behavior**
It should not crash, but just do nothing. The documentation should put a warning or remark about the Windows 10 N SKU in MediaPlayerElement.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes  |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
We also got a report of the Sound element not working on Windows N either.
