### ISSUE TITLE
WinUI3 C++/WinRT - error when I create a DataTemplate Selector.

### ISSUE THREAD

**Issue by PirvulescuDaniel** [microsoft/microsoft-ui-xaml#7542]
### Describe the bug

When i want to implement a DataType Selector in c++/WinRT i got an error message at compilation

"Error WMC9999 Unable to cast object of type 'System.Xaml.XamlType' to type 'Microsoft.UI.Xaml.Markup.Compiler.DirectUI.DirectUIXamlType'"

I recreate the [example](https://docs.microsoft.com/en-us/windows/apps/design/controls/data-template-selector) from Microsoft with same data Types and i got the same error.

### Steps to reproduce the bug

I create a WinRT component that inherit "Windows.UI.Xaml.Controls.DataTemplateSelector".
I override "SelectTemplateCore()", both methods(with one and two parameters).
I implement the logic that choose the right template.
I add this Selector to MainWindow
Implement the templates in XAML(pics below)

### Screenshots

![image](https://user-images.githubusercontent.com/81375865/181736938-abd0ef72-93c4-417f-aaee-e68e05699a48.png)
![image](https://user-images.githubusercontent.com/81375865/181737067-9d4e96ca-f597-4868-b365-916979ae93d4.png)
![image](https://user-images.githubusercontent.com/81375865/181737180-fc3fe256-710c-4415-a2c4-fa60c8101eee.png)
![image](https://user-images.githubusercontent.com/81375865/181737201-8bc47469-e705-4077-b7b5-96113c862293.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

The code from Microsoft example: https://pastebin.com/TwdgjrKC

**Comment by evelynwu-msft** [comment]
@PirvulescuDaniel Your code appears to be mixing UWP XAML (**`Windows`**`::UI::Xaml` namespace) with WinUI 3 (**`Microsoft`**::UI::Xaml` namespace). The two frameworks are *not* compatible with each other so you should update your project so that it's using only one or the other.

**Comment by ClaudiuHBann** [comment]
@evelynwu-msft was right, try to use just one namespace like Microsoft.

I made a github repo with the minimum code for the data template selector example [here](https://github.com/ClaudiuHBann/DataTemplateSelector)
