### ISSUE TITLE
XAML HotReload not working 

### ISSUE THREAD

**Issue by SkySpiritDev** [microsoft/microsoft-ui-xaml#7549]
### Describe the bug

XAML HotReload does not work if Grid with ColumeDefinitions is specified in the code.

Example:

```
<Grid ColumnDefinitions="30, *">
                    <FontIcon Grid.Column="0" FontFamily="Segoe MDL2 Assets" Glyph="&#xE910;"/>
                    <TextBox Grid.Column="1" x:Name="UiEmail"></TextBox>
</Grid>
```

When you try to change something, VS 2022 (version 17.2.6) gives the following errors:

![Screenshot_1](https://user-images.githubusercontent.com/82184365/181908226-5a8bafbf-83e8-46f3-8ca4-272897ae6afb.png)

As you can see, it emphasizes exactly 
ColumnDefinitions="..."

Probably XAML Hotreload doesn't know how to work with this yet?

### Steps to reproduce the bug

Try to update to VS 2022 Preview - no results.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by HEIC-to-JPEG-Dev** [comment]
2nd this - no IDE visual editor and you can't use all the features of XAML if you use hot reload.
