### ISSUE TITLE
Pivot crashes when given unlimited width

### ISSUE THREAD

**Issue by jamers99** [microsoft/microsoft-ui-xaml#7558]
### Describe the bug

If you place a `Pivot` in a `StackPanel` with an `Orientation` of `Horizontal`, it crashes with no detail.
If you add override `MeasureOverride`, you'll get a bit of detail from an `AccessViolationException`
```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
``` 

### Steps to reproduce the bug

1. Create a new WinUI app
2. Set the `MainWindow`'s `Content` to a `StackPanel` with an `Orientation` of `Horizontal`
3. Within the `StackPanel`, put a `Pivot` control
4. Run the app

### Expected behavior

It should have the Pivot aligned to the left and should not crash the app.

### Screenshots

![image](https://user-images.githubusercontent.com/20806279/182251547-d0508eba-ddec-4400-a1cf-c7d2d642c347.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

**Here is a sample app**
[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9237577/App1.zip)

**Comment by jamers99** [comment]
Any update on this?

**Comment by tom-huntington** [comment]
Not getting a crash in cppwinrt, but the rest of the `StackPanel`'s children are off the edge of the `Window`.

Seems like somethings going wrong calculating the width

**Comment by ranjeshj** [comment]
This does not crash anymore with winui3 1.4.2. I tried the contents of the attached app1.zip and it did not crash. This works as well
```
    <StackPanel Orientation="Horizontal">

        <Pivot Title="EMAIL">
            <PivotItem Header="All">
                <TextBlock Text="all emails go here." />
            </PivotItem>
            <PivotItem Header="Unread">
                <TextBlock Text="unread emails go here." />
            </PivotItem>
            <PivotItem Header="Flagged">
                <TextBlock Text="flagged emails go here." />
            </PivotItem>
            <PivotItem Header="Urgent">
                <TextBlock Text="urgent emails go here." />
            </PivotItem>
        </Pivot>
    </StackPanel>
```

**Comment by tom-huntington** [comment]
@ranjeshj I installed the latest nuget but am still getting this issue https://github.com/microsoft/microsoft-ui-xaml/issues/8968

I was never getting the crash.

My fix (setting `MaxWidth`) is sufficient for now
