### ISSUE TITLE
Crash randomly when WindowHelper.CreateWindow();

### ISSUE THREAD

**Issue by MrDeej** [microsoft/microsoft-ui-xaml#7564]
### Describe the bug

Our internal LOB app make use of createWindow and since we upgraded from 1.0_experimental to 1.1.3 we have been experiencing randomly crashes on our company pc's.  It happends when we create new window, but only randomly on the 5-15 creation. 

In event viewer in windows, it says it crashed du to kernelbase.dll, but that does not help us developers much. 

And today we tried downloading the WinUI 3 Gallery app from Windows Store on one of the affected computers, and yes, this app also crashes randomly when using the new create new window command. 

Please prioritize this bug

Kind Regards,
Eirik

### Steps to reproduce the bug

Use Windows 10.19044

1. Download Winui 3 Gallery app from Windows Store.
2. Repeatedly click the "Create new Window" button within the app.

### Expected behavior

yeah, maybe not crash?

### Screenshots

![event viewer](https://user-images.githubusercontent.com/16320446/183050382-e62017fa-d432-4aac-9a19-78fbb9817701.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

The screenshot is from Winui 3 Gallery app, but the bug was detecting in our 2 million codeline internal LOB app, which I cannot share here. 

But the same bug shows itself in the Gallery app so, good times.

It does not crash on my Windows 11 Machine.

**Comment by MrDeej** [comment]
It does not crash on my Windows 11 Machine.

**Comment by MrDeej** [comment]
This issue seems resolved when using WinUI 1.1.4

**Comment by gabbybilka** [comment]
@codendone Does this still repro on 1.1.4?

**Comment by codendone** [comment]
Yes, we still repro an issue here (a problematic leak) which we're investigating.
