### ISSUE TITLE
PasswordBox RevealButton does not reappear on edit starting

### ISSUE THREAD

**Issue by vasanth1005** [microsoft/microsoft-ui-xaml#7567]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
PasswordBox

**Describe the bug:**
Once you have entered a value gone out of editing mode and come back to editing the RevealButton does not reappear until you have deleted the entire password and then typed a single character.

**Version Info:**
WinUI 3 - Windows App SDK 1.1.3

**Additional context:**

**Comment by chingucoding** [comment]
This is a duplicate of #1224 and intentional (also assumed this is a bug but it's a security feature).

**Comment by vasanth1005** [comment]
Yes understood, I did try to find the issue but anyways thanks
