### ISSUE TITLE
App destructor not called on graceful exit

### ISSUE THREAD

**Issue by javs** [microsoft/microsoft-ui-xaml#7576]
### Describe the bug

The current app instance is held at WinMain return causing the destructor to never be called. This is useful for profiling as well as last chance cleanup of external resources.

### Steps to reproduce the bug

1. Create C++ project template from "Blank App, Packaged (WinUI3 in Desktop)"
2. Add `App::~App()` to h/cpp with some code and a breakpoint.
3. Start debug.
4. Close app.
5. Breakpoint is never hit.

### Expected behavior

Current App instance should be released before WinMain returns, hitting the destructor breakpoint.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by pratikone** [comment]
this is expected behavior for UWP. UWP apps can be suspended, resumed and don't go through usual app launch/tear down cycle.  You can read this for more details on that : https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/details-about-destructors

**Comment by Ajith-GS** [comment]
> this is expected behavior for UWP. UWP apps can be suspended, resumed and don't go through usual app launch/tear down cycle. You can read this for more details on that : https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/details-about-destructors

Hi, 
What is the case of WinUI3 application? Not UWP
