### ISSUE TITLE
Acrylic blur does not work if Window use MicaBackdrop

### ISSUE THREAD

**Issue by Sanlorng** [microsoft/microsoft-ui-xaml#7578]
### Describe the bug

if Window enabled Mica, Acrylic blur does not work. this issue reported in #7200 and it was marked as fixed. But i reproduce the bug when i use WindowsAppSDK **1.1.3**

### Steps to reproduce the bug

1. add ComboBox Component.
2. expand ComboBox Dropdown.

### Expected behavior

In-App Acrylic blur works.

### Screenshots

if Mica disabled， Acrylic blur works
![image](https://user-images.githubusercontent.com/26089739/183600467-0e6ed182-2dca-4b9b-9840-c5e166cb0eba.png)

if Mica enbled, Acrylic blur does not work

![image](https://user-images.githubusercontent.com/26089739/183602112-59ab386d-7e62-4809-9b71-82e0a80b3ae3.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by codendone** [comment]
A fix is coming for #7200, but isn't available yet. Please use that issue for tracking. Closing as dup of that issue. Thanks.
