### ISSUE TITLE
Full client rect Xaml Island at default window size leaves single pixel gap

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/microsoft-ui-xaml#758]
**Describe the bug**
A single pixel border is left on the bottom of the client area.

**Steps to reproduce the bug**
4K screen at 250% display scale
1. `CreateWindowExW(, , , WS_OVERLAPPEDWINDOW, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, , , , );` results in a window with size 2880x1499
2. During `WM_CREATE` set the Xaml Island rect to the full client rect.
3. Example available at https://github.com/MarkIngramUK/XamlIslands

**Expected behavior**
The Xaml Island to fill the full client rect

**Screenshots**
It's not immediately obvious from the screenshot, but look at the full size image, then look at the last row of pixels.
![Window](https://user-images.githubusercontent.com/4758079/58374568-5f94e380-7f38-11e9-9237-e45aa7c112e5.png)

**Version Info**
1903

NuGet package version: 
N/A

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes  |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Manually setting the window size to 2880x1499 also causes the problem to appear, however, if you set the window size to 2880x1498, and then use the mouse to resize the window, or programmatically set the size to 2880x1499, the single pixel gap doesn't appear - it only seems to happen when setting the size during `WM_CREATE`.

**Comment by marb2000** [comment]
Hum! I couldn't repro in my machine: 1909 , secondary 4K monitor and 250% DPI. @MarkIngramUK do you still see the issue?

**Comment by MarkIngramUK** [comment]
@marb2000 I've got a freshly installed 1903 laptop here, which I've not tried it on before, and I'm still seeing it. I'll get 1909 installed and try it on that. I have noticed that if I minimise the window and restore it again, the red line isn't visible anymore.

Result from trying today (you may need to click the image to see the single red pixel line):
![XamlIslands](https://user-images.githubusercontent.com/4758079/67037994-7a9a0700-f116-11e9-87d7-da66eb6999a8.png)

**Comment by marb2000** [comment]
Thanks! I will keep on the backlog so we can fix it in WinUI at some point,

**Comment by shaheedmalik** [comment]
I see the red line all the way at the bottom.
