### ISSUE TITLE
Can't open text selection context menu

### ISSUE THREAD

**Issue by Sanlorng** [microsoft/microsoft-ui-xaml#7582]
### Describe the bug

when some text selected, and right click selected text, the app will crash and show the error information
`0x767487E2 (KernelBase.dll)处(位于 DandanPlay For WinUI 3.exe 中)引发的异常: WinRT originate error - 0x80070490 : 'Element not found.'。
0x767487E2 处(位于 DandanPlay For WinUI 3.exe 中)引发的异常: Microsoft C++ 异常: winrt::hresult_error，位于内存位置 0x0057DC10 处。`

### Steps to reproduce the bug

1. Create WinUI App
2. Add TextBlock in the MainWindow.xaml and add TextBlock.IsTextSelectionEnabled="True"
3. select text, and right click selected text
4. App crash

### Expected behavior

right click selected text can display selection context menu

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by JJBrychell** [comment]
While I could repro this on a 1.1 build, I wasn't able to repro it on any from 1.3 or later so I am going to close this as fixed.  If it still exists in recent releases of WinAppSdk, feel free to reactivate.
