### ISSUE TITLE
XamlControlsResources causes crash when used from plain win32 desktop app

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/microsoft-ui-xaml#7606]
### Describe the bug

When trying to use WinUI 3 with a plain win32 app from scratch (unpackaged & no winui project template), instantiating `XamlControlsResources` to place into your `Application`'s resources causes a crash.

### Steps to reproduce the bug

1. Download the example VS solution attached here
2. Build and run
3. Notice how there is a crash
4. Comment out the code in the .ctor of the `App` class
5. Rebuild and run
6. Notice how everything works now (except lack of WinUI styles)

### Expected behavior

Creating `XamlControlsResources` won't cause an exception and crash the app; this program should work just like every other unpackaged win32 desktop app using WinUI 3.

### NuGet package version

1.1.2

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

Zip file with VS solution:
[Test.zip](https://github.com/microsoft/WindowsAppSDK/files/9332214/Test.zip)

**Comment by DarranRowe** [comment]
@AzAgarampur Getting it working from there doesn't actually require too much extra work. @riverar is correct in saying that the application requires an IXamlMetadataProvider implementation. But the fact is, as the name implies, it only needs to provide the metadata.
This means that the App class has to implement the IXamlMetadataProvider interface, but for the basic task of showing a standard Xaml window or controls, it is good enough to just fall through to the WinUI provided provider. The difficulty is when you are using custom controls, including having Xaml files in your project. If the project generates the XamlMetadataProvider class in the winrt::<Project Name>::implementation namespace then use that.
I attached a little project to this showing the basic provider at work, and it does get as far as showing the window. But be aware, Visual Studio will not generate the .xbf file for any xaml files in the Win32 desktop project. You can get around this in other ways, but it is annoying.
But the interesting thing about this is that this is the same issue you face getting a Xaml Islands application running. Using WinUI 2 in a Xaml Islands application required that you provide a custom application type to be able to load WinUI 2 properly. The same thing is true for the experimental release of Xaml Islands for the Windows App SDK/WinUI 3.
[TestApplication.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9339464/TestApplication.zip)

**Comment by riverar** [comment]
While this is true, in my experience you won't get far with a more complete implementation of `IXamlMetadataProvider` sadly. It's one of the reasons the Rust implementation of the Windows App SDK has not progressed very far and I will be putting on hold. The reality is XAML is not designed/documented for use outside of MSBuild + Visual Studio + C#/C++. If you try to venture off this path, you're going to be running into a lot of walls.

**Comment by lyahdav** [comment]
@DarranRowe thanks for providing that test app, this is very helpful since I'm trying to get a WinUI 3 app building without Visual Studio. But when I run your solution, on app launch I get error:
> Exception thrown at 0x00007FFE85E14FD9 (KernelBase.dll) in TestApplication.exe: WinRT originate error - 0x80070005 : 'Access is denied.'.

Here's the full output: https://gist.github.com/lyahdav/00db0cdcaae9eb2602b2a4a45f79677e
And here's the call stack: https://gist.github.com/lyahdav/2a574c318c15655c11083f73b613955f

Any idea what's going on?

**Comment by lyahdav** [comment]
Oh wait, I think that's due to WinAppSDK 1.1.4 bug: https://github.com/microsoft/WindowsAppSDK/issues/2918. I'll try to downgrade and report back.

**Comment by lyahdav** [comment]
Yeah that was it. I downgraded the WindowsAppSDK version to 1.0.4 and I also had to install the 1.0.4 runtime from here: https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-10. Then the app launched.

**Comment by sotanakamura** [comment]
I would like to share a step by step guide to create a WinUI 3 app from an empty win32 project. This issue helped me to apply the Winui3 theme. Thank you all.
https://github.com/sotanakamura/winui3-without-xaml

**Comment by riverar** [comment]
@sotanakamura You won't get far that way. You will need to include the WinUI 3 nuget to bring in required SxS manifests, the xaml compiler, etc.

**Comment by sotanakamura** [comment]
Thank you for your reply. In that guide I wrote about installing WinUI 3 and the C++/WinRT nuget packages. Is it still having problems? I am not a Windows app developer, I am just playing with WinUI 3. That guide is not for product development. If that guide still has problems, please let me know.

**Comment by tomaszkot** [comment]
I have similar issue: https://github.com/microsoft/WindowsAppSDK-Samples/issues/328
