### ISSUE TITLE
Proposal: Add Background Acrylic back to left NavigationView

### ISSUE THREAD

**Issue by carmellolb** [microsoft/microsoft-ui-xaml#761]
# Proposal: Add Background Acrylic back to left NavigationView

## Summary
Background Acrylic provides context, by showing that the NavigationView is the focus. It also provides a beautiful design. Please add it back to NavigationView, I'm not sure why you ever removed it.

## Rationale

* It provided context, and directed people's attention to it.
* It added transparency, which allowed everything to connect, and flow.
* It looked beautiful, and fit well with Fluent Design.
* The plain grey look is unappealing, and does not draw users' attention well.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to draw users attention to the left NavigationView pane | Must |
| This proposal will allow end users to experience a beautiful design, and a consistent, connected experience. | Must |
| This proposal will allow developers to allow their NavigationView panes switch between Background Acrylic and In-App Acrylic based on the window size. | Could |
| This proposal will allow end users to see Reveal effects easier. | Could |

## Open Questions
Part of Acrylic's purpose is to provide context, and a beautiful design. Why remove those two things and therefore ruin the flow, look, and ease-to-use of the app by removing a stable Acrylic material on the left NavigationView?

**Comment by YuliKl** [comment]
@carmellolb - Thank you for your feedback. We'll work with the Fluent design team to define the right color or material for the expanded pane. As I mentioned in [another issue](https://github.com/MicrosoftDocs/windows-uwp/issues/1661), the use of background acrylic in this state does not fit into the overall Fluent Design System.

**Comment by mdtauk** [comment]
Does the overlay pane not use In App Acrylic?  It used to.

**Comment by Felix-Dev** [comment]
@mdtauk Based on XAML Control Gallery, InApp Acrylic is still used for the overlay pane, as far as I can see.

**Comment by YuliKl** [comment]
Yes, @Felix-Dev is correct. When NavigationView's pane is open as an overlay on top of content, the default control style still uses in-app acrylic. The issue that @carmellolb opened is talking about the mode when the pane is open side-by-side with content - in this state, the pane does not use any type of acrylic. We've outlined the rationale for these choices in the [Acrylic documentation](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic?view=winui-2.2#when-to-use-acrylic).

**Comment by carmellolb** [comment]
> Does the overlay pane not use In App Acrylic? It used to.

Yes, it does, but I am saying why not Background Acrylic? It only uses In App Acrylic when the window is small and you expand the hamburger menu. But the Background Acrylic when the window is big is gone.

**Comment by carmellolb** [comment]
> Yes, @Felix-Dev is correct. When NavigationView's pane is open as an overlay on top of content, the default control style still uses in-app acrylic. The issue that @carmellolb opened is talking about the mode when the pane is open side-by-side with content - in this state, the pane does not use any type of acrylic. We've outlined the rationale for these choices in the [Acrylic documentation](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic?view=winui-2.2#when-to-use-acrylic).

I really hope you will reconsider, as I think it was not a smart idea to remove it. I know I've said this many times, I'm very sorry if I seem persistent, but your explanation of why you removed it basically makes all transparency irrelevant, because all transparency "shows what's behind it" and if that is the case then all transparency must be "distracting". I highly recommend with the support of many others that you re-add Background Acrylic to NavigationView.

**Comment by YuliKl** [comment]
@carmellolb - I definitely appreciate your passion about this subject. Opening an issue in this GitHub repo is the most effect way to drive changes into Xaml controls, so you've found the right place to make your voice heard. Thank you for sharing your thoughts and please encourage others to react to this issue by up-voting.

**Comment by mdtauk** [comment]
> ... in this state, the pane does not use any type of acrylic. We've outlined the rationale for these choices in the Acrylic documentation

Does this mean that the Settings App and other apps are going to lose their Acrylic NavigationView Panes?  That would be a serious aesthetic regression.

**Comment by carmellolb** [comment]
> > ... in this state, the pane does not use any type of acrylic. We've outlined the rationale for these choices in the Acrylic documentation
> 
> Does this mean that the Settings App and other apps are going to lose their Acrylic NavigationView Panes? That would be a serious aesthetic regression.

Agree. I hope they never remove it from there, but also I think they should add it back to everything. It seems they are caring less and less about aesthetic which, unlike what they seem to be showing, is a huge component of the system.

**Comment by Felix-Dev** [comment]
@mdtauk @carmellolb @duke7553 @YuliKl 

What can we do to try to revert this change? Would that even still be possible or is Acrylic Background for the NavigationView (except for InApp acrylic) now done for good?

**Comment by duke7553** [comment]
@Felix-Dev Upon giving this issue greater thought, I realize it doesn't make much sense to include Acrylic by default on the NavigationView Pane background. From what I've gathered Fluent Design isn't merely about looks, but also just as much about function. Acrylic in its previous form was greatly overused, shoving this unnecessary, distracting material towards users in the name of "context". We have learned that context can be better provided via Z-depth, etc. Because of this, Acrylic should be reserved for temporary surfaces. If you need Acrylic on this surface _that_ much, you can apply an AcrylicBrush to the following keys:
```
x:Key="NavigationViewDefaultPaneBackground"
x:Key="NavigationViewTopPaneBackground"
x:Key="NavigationViewExpandedPaneBackground"
```

I hope this makes sense, as I don't work for Microsoft, but I'm just a passionate user like yourselves.

**Comment by duke7553** [comment]
I do think Microsoft should provide guidelines for the background color of this now-opaque pane. IMO, the current color choice (which appears to be a fallback color) contrasts too much with the rest of the app's UI. It should match the application's background color more.

**Comment by YuliKl** [comment]
I agree with everything @duke7553 said, both about the (over)use of acrylic and the need to update NavigationView's pane color.

@duke7553, would you like to open a separate proposal as you suggested?

**Comment by PharazFadaei** [comment]
To my eyes, the only situation that using background (as opposed to in-app) acrylic seems correct, is in navigation panes. I think background acrylic in the navigation pane of Settings app was a great improvement in terms of aesthetics. I just can't figure it out, if using background acrylic in navigation panes is discouraged, then what was the purpose of background acrylics in the first place?

**Comment by Felix-Dev** [comment]
@PharazFadei

Background Acrylic *might* be pretty much dead now. In another issue (linked here in the thread), @YuliKl says:
> When NavigationView’s pane is placed side-by-side with the app content, this visual bridge is unnecessary and is in fact distracting because the acrylic invites unrelated content to shine through.

"[...]because the acrylic invites unrelated content to shine through"

That's just how background acrylic works (although I'd say because the background content is so heavily blurred it really doesn't distract) and that seemingly is a problem for the MS teams when applied in apps. Whether it's the titlebar, navigation pane, or other app regions, "unrelated content [will always] shine though".

It's really unfortunate, because I **never** found it to be distracting, it was beautiful and - coming from it - the current solution is huge step back visually, without even providing any improvement IMO.
I also haven't seen any complaints about background acrylic used in apps like Settings on the usual sites, such as reddit (though I'm not claiming there are none) but perhaps MS has internal data showing otherwise.

**Comment by carmellolb** [comment]
> @PharazFadaei
> 
> Background Acrylic _might_ be pretty much dead now. In another issue (linked here in the thread), @YuliKl says:
> 
> > When NavigationView’s pane is placed side-by-side with the app content, this visual bridge is unnecessary and is in fact distracting because the acrylic invites unrelated content to shine through.
> 
> "[...]because the acrylic invites unrelated content to shine through"
> 
> That's just how background acrylic works (although I'd say because the background content is so heavily blurred it really doesn't distract) and that seemingly is a problem for the MS teams when applied in apps. Whether it's the titlebar, navigation pane, or other app regions, "unrelated content [will always] shine though".
> 
> It's really unfortunate, because I **never** found it to be distracting, it was beautiful and - coming from it - the current solution is huge step back visually, without even providing any improvement IMO.
> I also haven't seen any complaints about background acrylic used in apps like Settings on the usual sites, such as reddit (though I'm not claiming there are none) but perhaps MS has internal data showing otherwise.

It's really a matter of how transparent it is. If it is heavily blurred, like in the Settings app, there should be no problem. Microsoft seems to not realize that, and is taking the dreaded all or nothing approach. It's really a shame, because as you said, it is a HUGE visual step back.

**Comment by Felix-Dev** [comment]
Just look at this beauty:
![image](https://user-images.githubusercontent.com/1398851/60122552-bb47cc00-9785-11e9-8b39-79525a11e063.png)

It provided beautiful context, every navigation view item is still clearly visible, background is blurred so much that it doesn't distract.

Too bad such a visual master piece will be removed in the near future 😥

**Comment by YuliKl** [comment]
@Chigy, as the WinUI representative working with Fluent designers, do you anticipate that having NavigationView draw background acrylic on its Pane in Expanded mode will support the evolution of the Fluent Design System?

**Comment by chigy** [comment]
@YuliKl ,
I cannot say never because I am not the driver of the conversation, however as far as I am aware of the activities going on with Fluent, there is no plan to re-introduce acrylic on the surface we purposefully removed from.

As @carmellolb states in the original proposal, use of acrylic draws attention to this surface (NavView) which is _reverse_ of what we want happen. We want user to be able to focus on the content, not draw unnecessary attention to what's not important. And that is part of the reason why it was removed and we are adding it to transient UI that does need attention when it does appear on screen.

**Comment by carmellolb** [comment]
> @YuliKl ,
> I cannot say never because I am not the driver of the conversation, however as far as I am aware of the activities going on with Fluent, there is no plan to re-introduce acrylic on the surface we purposefully removed from.
> 
> As @carmellolb states in the original proposal, use of acrylic draws attention to this surface (NavView) which is _reverse_ of what we want happen. We want user to be able to focus on the content, not draw unnecessary attention to what's not important. And that is part of the reason why it was removed and we are adding it to transient UI that does need attention when it does appear on screen.

I think a better approach than just not adding it back would be to add it in a less transparent form, kind of like on the Windows Shell. I think that would not draw users' attention as much if any. I think the current grey definitely draws a lot of attention, because of its contrast with the white background. I hope you reconsider.

**Comment by YuliKl** [comment]
Unfortunately this proposal doesn't move NavigationView's visual design in the direction that we see the Fluent Design System heading.

I do believe that we need to revisit the current grey that has replaced acrylic in the Pane. While it doesn't appear that putting back acrylic will be the right solution, the current grey also doesn't feel like the right long-term design. 

**Would one of you be willing to open a new proposal to update NavigationView's Pane with some (non-Acrylic) material or color?** While I can open the issue myself, it carries more weight coming from the community.

**Comment by carmellolb** [comment]
> Unfortunately this proposal doesn't move NavigationView's visual design in the direction that we see the Fluent Design System heading.
> 
> I do believe that we need to revisit the current grey that has replaced acrylic in the Pane. While it doesn't appear that putting back acrylic will be the right solution, the current grey also doesn't feel like the right long-term design.
> 
> **Would one of you be willing to open a new proposal to update NavigationView's Pane with some (non-Acrylic) material or color?** While I can open the issue myself, it carries more weight coming from the community.

I just opened one. If Background Acrylic cannot be added, I definitely think another color or material would be a lot better.
Link: [](https://github.com/microsoft/microsoft-ui-xaml/issues/947)

**Comment by mdtauk** [comment]
Rather than remove Acrylic altogether, why not implement a less Transparent opacity version by default?

**Comment by chigy** [comment]
> Rather than remove Acrylic altogether, why not implement a less Transparent opacity version by default?

@mdtauk , Acrylic has a performance implications, thus we recommend do not use on a larger surface. It is partly due to the transparency as well as use of blur. Without blur, text cannot be made legible. If we make it opaque background, then gray is the best option there is.

**Comment by mdtauk** [comment]
> > Rather than remove Acrylic altogether, why not implement a less Transparent opacity version by default?
> 
> @mdtauk , Acrylic has a performance implications, thus we recommend do not use on a larger surface. It is partly due to the transparency as well as use of blur. Without blur, text cannot be made legible. If we make it opaque background, then gray is the best option there is.

Acrylic performance would be device dependent - but it is true that Acrylic has more to it than the plain Gaussian blur of Aero Glass.  There should be better fallbacks for things like Tablet Mode, where it pre-blurs the Background Wallpaper, and uses that on those surfaces - but I don't want to stray from the topic.

For legibility an 80-90% opacity will assuage the legibility concerns.

It would be interesting to learn some of the performance analysis, and whether device type was considered.  There could be a case to be made of having Acrylic active in unfocused windows, as well as the active window, if the PC is capable, to avoid the distraction of the colour shifting when moving between windows.

**Comment by YuliKl** [comment]
@mdtauk, your point about distracting colour shifts when moving between windows is one more reason why we recommend not using acrylic on long-lived, non-transient surfaces like NavigationView's expanded left pane.

**Comment by mdtauk** [comment]
> @mdtauk, your point about distracting colour shifts when moving between windows is one more reason why we recommend not using acrylic on long-lived, non-transient surfaces like NavigationView's expanded left pane.

I can see that, but the Acrylic sidebar is (I would argue) a quintessential paradigm for Modern Windows app design - along with extending into the TitleBar.

Apps like Your Phone look "uncomfortable" and not as elegant with the opaque titlebar, and the grey sidebar.  Acrylic looses it's impact when it is reserved for small overlayed elements.

Settings is also one of the better looking UI surfaces, and other Navigation Views don't look so good in comparison to it.

**Comment by Poopooracoocoo** [comment]
On the performance of acrylic: does this have anything to do with why opening the input indicator flyout is faster than flyouts like the clock (or even the start menu and action centre)?

**Comment by mdtauk** [comment]
I mentioned this in another thread, but as a counter to the argument of the Acrylic sidebar being "distracting" (which doesn't seem to be an issue where it is used on macOS or other platforms)

>I believe Settings uses a 60% value, but changing it to 80% would preserve the transparency, but make it less "distracting".
>
>So why not update the AcrylicBrush theme resources used by the controls, to use a different percentage opacity?

**Comment by mdtauk** [comment]
Here is an illustration of the before and after, with 80% acrylic
![image](https://user-images.githubusercontent.com/7389110/68527825-4cf24900-02e3-11ea-8e3d-56bc165ac720.png)

**Comment by YuliKl** [comment]
@mdtauk, would you mind filing this feedback through the Feedback Hub? Your proposal to change Settings to use 80% acrylic feels good, and isn't up to the WinUI team to implement. We already provide a variety of [AcrylicBrush resources](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#acrylic-theme-resources), including `SystemControlAcrylicWindowBrush`. The Settings app would need to make a change in their code to use a different resource.  The WinUI team can't make the change for the Settings app.

**Comment by mdtauk** [comment]
@YuliKl  I created the image to try to illustrate the difference.  I have no problem with the 60% Acrylic - but would rather see it change to 80% than have the Acrylic removed all together, if that is seriously being proposed on the grounds of it being distracting.

I'd also prefer the NavigationView to have its acrylic restored, with either 60% or 80% Acrylic - but I suspect that "battle" has been lost, and more and more apps will now look more like Your Phone and less like Settings

**Comment by carmellolb** [comment]
> @YuliKl I created the image to try to illustrate the difference. I have no problem with the 60% Acrylic - but would rather see it change to 80% than have the Acrylic removed all together, if that is seriously being proposed on the grounds of it being distracting.
> 
> I'd also prefer the NavigationView to have its acrylic restored, with either 60% or 80% Acrylic - but I suspect that "battle" has been lost, and more and more apps will now look more like Your Phone and less like Settings

It’s really a shame too, because it was one of the best features of fluent design, and one of the most well known. Also, NavigationView was one of the most prominent areas. Maybe one day they will change their mind and reapply it.

**Comment by carmellolb** [comment]
Updates on this issue? Any news? Still no plans to re-add? @YuliKl @chigy

**Comment by Felix-Dev** [comment]
@carmellolb Last info we got was:

> All the tools for customization are in place. I just don't have the blessing of the Fluent design team to change NavigationView's default appearance.

(https://github.com/microsoft/microsoft-ui-xaml/issues/1523#issuecomment-549564417)

So for this specific request you would have to talk to the Fluent Design team directly. This repository here, I'm afraid, is unfortunately not the right place for that.
