### ISSUE TITLE
Memory leak in Multi-window scenario

### ISSUE THREAD

**Issue by getrou** [microsoft/microsoft-ui-xaml#7617]
### Describe the bug

In a WinAppSDK multi-window scenario, the memory footprint increases even when windows are closed out.

### Steps to reproduce the bug

1. Go to https://github.com/microsoft/WinUI-Samples and clone the repo.
2. Run MyApp.package.
3. Take a memory snapshot using VS's diagnostic tools.
4. Click the "Open Mini" button and then close out all the extra windows that were opened.
5. Take a second memory snapshot and compare.

### Expected behavior

Memory footprint is the same before and after multi-window scenario.

### Screenshots

![image](https://user-images.githubusercontent.com/52982368/185446734-91b20bb0-4bd6-47e5-9a72-b928d9517834.png)

### NuGet package version

1.2.220727.1-experimental1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by danielancines** [comment]
I've been making some tests here, and the problem appears to be in a Window object that still forever allocated, in my tests, even I closed New Window and check if it removed from App.Current.Windows collection, the object never will be collect by GC and I cannot find who is locking up on the object tree. Unfortunately I didn't find any workaround for this issue, do you guys have any idea?

**Comment by danielancines** [comment]
This issue was resolved #13400

**Comment by JJBrychell** [comment]
There has been a lot of work on the shutdown process in 1.4 and we hope that that has addressed this issue. If this still continues to occur under 1.4, please feel free to reopen.

**Comment by rodirigos** [comment]
Still happening in dotnet8.
