### ISSUE TITLE
TreeView crash when too many TreeviewNode is expanded.

### ISSUE THREAD

**Issue by herolss** [microsoft/microsoft-ui-xaml#7618]
### Describe the bug

using template Selector，Loaded about thousands Treeview Node。

System.ArgumentException
  HResult=0x80070057
  Message=Source object type is not a projected type and does not inherit from a projected type. Arg_ParamName_Name
  Source=WinRT.Runtime
  StackTrace:
   在 WinRT.CastExtensions.GetRefForObject(Object value)

### Steps to reproduce the bug

1. expanded ItemNode. 
2.  drag scrollbar
3. WINUI3 app crash

### Screenshots

![Treeview scrash  2022-08-17 092509](https://user-images.githubusercontent.com/44991955/185014412-ee65cbed-534c-449a-b4b7-e919860d576f.png)

### NuGet package version

1.1.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by Suriman** [comment]
The same happens to us. I post here a sample application and a picture with the exception. It seems like it is trying to reuse a node but if it was bound formerly to a specific viewmodel type, and later it is bound to another type, it still tries to cast the current viewmodel to the other one's type.

PD.- You get the exception right after starting the application.
![WinUITreeViewIssue](https://user-images.githubusercontent.com/3469909/217023612-93beec87-70b4-4ec8-a273-cbee7378c120.PNG)

**Comment by ADD-Lorenzo-Martin** [comment]
[WinUITreeviewErrors.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10665454/WinUITreeviewErrors.zip)
This is the sample application.

**Comment by herolss** [comment]
yes, you are right.
the exception is issued by different class type of TreeViewItemViewModel,  using abstract class inherit for specific tree node.
so, i use one class type of TreeViewItemViewModelBase, using TreeNodeType Enum to distinguish specific tree node.
now, the exception not occur again
----- 原始邮件 -----
发件人：Suriman ***@***.***>
收件人：microsoft/microsoft-ui-xaml ***@***.***>
抄送人：herolss ***@***.***>,  Author ***@***.***>
主题：Re: [microsoft/microsoft-ui-xaml] TreeView crash when too many TreeviewNode is expanded. (Issue #7618)
日期：2023年02月07日 00点09分


The same happens to us. I post here a sample application and a picture with the exception. It seems like it is trying to reuse a node but if it was bound formerly to a specific viewmodel type, and later it is bound to another type, it still tries to cast the current viewmodel to the other one's type.
PD.- You get the exception right after starting the application.



&mdash;

**Comment by herolss** [comment]
thanks for that.
----- 原始邮件 -----
发件人：ADD-Lorenzo-Martin ***@***.***>
收件人：microsoft/microsoft-ui-xaml ***@***.***>
抄送人：herolss ***@***.***>,  Author ***@***.***>
主题：Re: [microsoft/microsoft-ui-xaml] TreeView crash when too many TreeviewNode is expanded. (Issue #7618)
日期：2023年02月07日 01点03分


WinUITreeviewErrors.zip

This is the sample application.

&mdash;

**Comment by ADD-Lorenzo-Martin** [comment]
> thanks for that. ----- 原始邮件 ----- 发件人：ADD-Lorenzo-Martin ***@***.***> 收件人：microsoft/microsoft-ui-xaml ***@***.***> 抄送人：herolss ***@***.***>, Author ***@***.***> 主题：Re: [microsoft/microsoft-ui-xaml] TreeView crash when too many TreeviewNode is expanded. (Issue #7618) 日期：2023年02月07日 01点03分 WinUITreeviewErrors.zip This is the sample application. &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

You are welcome :)

**Comment by fabianoriccardi** [comment]
For the ones navigating in this TreeView nightmare, refers to #8791.
