### ISSUE TITLE
Simultaneous Mouse and multi-touch input Crash (CppWinRT) 

### ISSUE THREAD

**Issue by techjogger** [microsoft/microsoft-ui-xaml#7622]
### Describe the bug

Simultaneous Mouse and multi-touch input causes an ...... Unhandled exception at 0x00007FF8408A26DB (Microsoft.InputStateManager.dll) in ***.exe: Fatal program exit requested.

### Steps to reproduce the bug

1. Run a CppWinRT Windows App SDK 1.1.4 App
2. Simultaneously use the Mouse and two figures .
3. App crashes... 

### Expected behavior

App does not crash

### Screenshots

![crash](https://user-images.githubusercontent.com/13125455/185646940-4a5708d5-4689-4613-88f7-673e92771fbf.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Crashes on Windows 10 too

Here is a sample app which will crash by following the repo steps...

https://github.com/SiliconBender/GroupedListViewWinUI3

**Comment by chrkon** [comment]
I can confirm this behaviour on Windows 11 in a WinUI3 Desktop App.
Just put two fingers on the TouchScreen and move the Mouse ... 
-> App is terminated.

**Comment by techjogger** [comment]
This crash is still present in the latest stable version of Windows App SDK 1.2.

**Comment by chrkon** [comment]
The Crash is still present in the latest Windows App SDK [1.3.3 (1.3.230724000)](https://learn.microsoft.com/de-de/windows/apps/windows-app-sdk/stable-channel#version-133-13230724000) (released 07/25/2023).

So I don't think this issue should be closed!

Is anybody working on this issue?

**Comment by codendone** [comment]
@chrkon Yes, a fix was checked in a few days ago and is currently going through additional testing.

**Comment by duncanmacmichael** [comment]
Fixed in 1.4.0. @bpulliam please close this issue as I cannot. :)
