### ISSUE TITLE
Disabling IsMaximizable and IsMinimizable does not work with ExtendsContentIntoTitleBar=true

### ISSUE THREAD

**Issue by progmars** [microsoft/microsoft-ui-xaml#7628]
### Describe the bug

Cannot disable maximize and minimize buttons and commands from the title bar if `ExtendsContentIntoTitleBar` is enabled. `IsMaximizable = false` and `IsMinimizable = false` has no effect. Only `IsResizable = false` works as expected.

Only if `ExtendsContentIntoTitleBar` is set to `false`, then `IsMaximizable = false` and `IsMinimizable = false` works as expected.

### Steps to reproduce the bug

1. Create a default blank WinUI 3 App (doesn't matter packaged or not).
2. Open App.xaml.cs file and add the bug test code in OnLaunched method to make it look as follows:

        protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
        {
            m_window = new MainWindow();
            m_window.Activate();

            // the bug test code follows
            var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(m_window);

            // Retrieve the WindowId that corresponds to hWnd.
            Microsoft.UI.WindowId windowId =
                Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);

            // to have custom title styles work together with WindowCaption* SolidColorBrush resources
            m_window.ExtendsContentIntoTitleBar = true;

            // Lastly, retrieve the AppWindow for the current (XAML) WinUI 3 window.
            var appWindow = AppWindow.GetFromWindowId(windowId);

            if (appWindow.Presenter is OverlappedPresenter p)
            {           
                p.IsMinimizable = false;
                p.IsMaximizable = false;
                p.IsResizable = false;
            }
        }

### Expected behavior

`p.IsMinimizable = false` and `p.IsMaximizable = false` should remove the respective commands from the titlebar buttons and also from the command menu.

### Screenshots

Not working with extended content:
![image](https://user-images.githubusercontent.com/4199737/185796858-197da73d-cb41-4c0a-a622-b734c53da346.png)

Working if content is not extended into titlebar:
![image](https://user-images.githubusercontent.com/4199737/185796989-db972853-f25c-4e57-8951-0c4325103c2d.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Experimental: 1.2.220727.1-experimental1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by tranhuynhthaitrung** [comment]
These caption buttons work not smooth too when ExtendsContentIntoTitleBar = true

Sometime, we click these buttons but it not working

**Comment by riverar** [comment]
Ping @rkarman

**Comment by HEIC-to-JPEG-Dev** [comment]
I'm seeing this with a new app on SDK 1.2 - IsMaximizable does not prevent the window going to Maximum, or disable the chrome buttons.

**Comment by pratikone** [comment]
There are 3 different ways to customize titlebar right now (we are exploring merging some of them).  You are using WinUI 3 custom titlebar with Appwindow apis. These app window apis only work if you use their custom titlebar. We are working on a unified solution.

 For now, you can switch to appwindow titlebar and they will start working. https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindowtitlebar?view=windows-app-sdk-1.1

We also support calling appwindow api directly from window class like this in Winappsdk 1.2 onwards 🎉🎉
```C++
m_window.AppWindow.Presenter 
```
So, you can skip some of the boilerplate code to access appwindow apis easily 😊

**Comment by ElectricThanhTung** [comment]
I am also facing this same problem. I hope it will be fixed in upcoming updates.

**Comment by Petrarca181** [comment]
Any temporary solution to hide those buttons?   Something like navigate through visual tree, find "MinMaxCloseContainer"    and  hide buttons?

**Comment by mhVuF** [comment]
> Any temporary solution to hide those buttons? Something like navigate through visual tree, find "MinMaxCloseContainer" and hide buttons?

@Petrarca181 you can do that with WinAPI:
```cs
private void RemoveMinimizeMaximize(IntPtr hwnd)
{
    SetWindowLongPtr(hwnd, GWL_STYLE, GetWindowLongPtr(hwnd, GWL_STYLE) & ~WS_MAXIMIZEBOX & ~WS_MINIMIZEBOX);
}
```
