### ISSUE TITLE
SetBorderAndTitleBar(true, false) with IsResizable = false removes the border although it should remove only the titlebar

### ISSUE THREAD

**Issue by progmars** [microsoft/microsoft-ui-xaml#7629]
### Describe the bug

When creating a non-resizable window with a border and without titlebar, I set `IsResizable = false` and call `SetBorderAndTitleBar(true, false)`. However, the border is completely hidden together with its shadow.

### Steps to reproduce the bug

Create a default blank WinUI 3 App (doesn't matter packaged or not).

Open App.xaml.cs file and add the bug test code in OnLaunched method to make it look as follows:

     protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
     {
             m_window = new MainWindow();
             m_window.Activate();

            // the bug test code follows
            var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(m_window);

            // Retrieve the WindowId that corresponds to hWnd.
            Microsoft.UI.WindowId windowId =
                Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);

            // Lastly, retrieve the AppWindow for the current (XAML) WinUI 3 window.
            var appWindow = AppWindow.GetFromWindowId(windowId);

            if (appWindow.Presenter is OverlappedPresenter p)
            {
                p.SetBorderAndTitleBar(true, false);
                p.IsResizable = false;
            }
     }

### Expected behavior

WinUI should remove the title bar and keep non-resizable borders with their default shadow.

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Experimental: 1.2.220727.1-experimental1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by Jay-o-Way** [comment]
Hi. No progress yet?

**Comment by Gallardo994** [comment]
Faced same issue here, trying to make desktop-wide toast notifications (cannot use integrated notifications as I'm running a privileged app).

All I'm left with is either ugly window without title bar and shadows, or a proper window with shadows and borders, but also with titlebar buttons.

**Comment by mdtauk** [comment]
Whilst working on this more flexible type of WinUI window, why not go the step further and enable all these
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/018104d3-22c4-4d5f-855f-558961cb0d01)

These examples are using mica, but should also work with Acrylic and Solid colours too
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/057e636b-a764-4a52-b0bf-2bbd9f4d778d)

**Comment by mdtauk** [comment]
Window.Border
Window.TitleBar
Window.Resizable
Window.Background
Window.Shadow

**Comment by Jay-o-Way** [comment]
Over a year old. Would be nice if this is going to be fixed.
