### ISSUE TITLE
WebView2 hosted by NavigationView/Frame/Page crashes app on exit

### ISSUE THREAD

**Issue by Balkoth** [microsoft/microsoft-ui-xaml#7632]
### Describe the bug

If a WebView2 control is hosted in a Page which itself is navigated via a NavigationView/Frame and navigation happens a few times, the app crashes on exit with the following error message:
![image](https://user-images.githubusercontent.com/80055480/185705661-b33cf753-4c68-46c9-b9a7-12992e40e6de.png)
![image](https://user-images.githubusercontent.com/80055480/185706128-afb00f4f-6d89-4f49-9aa6-f591fabe2ad5.png)

### Steps to reproduce the bug

1. Open the attached sample [TestNavWebView.zip](https://github.com/microsoft/WindowsAppSDK/files/9385445/TestNavWebView.zip)
2. Build and run it
3. Navigate 5 times between the 2 pages
4. Exit the app and observere the above crash

### NuGet package version

1.1.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by codendone** [comment]
The problem here is the underlying WebView2 objects don't get closed soon enough. #7260 has more details, including the workaround to explicitly `Close()` any WebView2 elements before the app exits. We'll use that issue to track the platform fix.
