### ISSUE TITLE
Proposal:Unable to apply styles to MainWindow. This was possible in wpf. Have a requirement to apply rounded corners to Mainwindow. 

### ISSUE THREAD

**Issue by harsh261** [microsoft/microsoft-ui-xaml#7638]
# Proposal: Ability to apply styles to Main Window

Ability to Apply styles to Main Window. How to apply rounded corners to Main Window.
## Summary

Need ability to apply styles to Main Window. 
## Rationale

* This was possible in WPF
* This was possible in UWP
* Not possible in wpf in windows 10

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by evelynwu-msft** [comment]
Duplicate of #7305.

**Comment by evelynwu-msft** [comment]
On second thought, not *really* a duplicate of #7305 as rounded corners don't come free with being a control, but the ability to apply a general style to a `Window` will require #7305.

**Comment by harsh261** [comment]
Thank you @evelynwu-msft !
