### ISSUE TITLE
When ItemsRepeater is unloaded, update the ItemsSource collection will crash the app

### ISSUE THREAD

**Issue by h82258652** [microsoft/microsoft-ui-xaml#7639]
### Describe the bug

When ```ItemsRepeater``` is unloaded, update the ```ItemsSource``` collection will crash the app.
![image](https://user-images.githubusercontent.com/5144550/186410286-2628d885-ebea-46da-a90a-fe13060350c5.png)

### Steps to reproduce the bug

I create a repro demo here: https://github.com/h82258652/ItemsRepeaterCrashDemo

1. Launch the app.
2. Hold your mouse left button on the "Click me" button.
3. A few seconds later, will get the exception.

### Expected behavior

Should not raise any exception.

### NuGet package version

Microsoft.UI.Xaml 2.8.1

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by bkudiess** [comment]
Can you try setting ItemSource to null before unloading the repeater? Does that help?

**Comment by h82258652** [comment]
Yes, it helps. But I already have lots of codes like this in my app. ```ListView``` and ```ItemsControl``` don't have this issue. I hope WinUI can fix this.

**Comment by AndrewKeepCoding** [comment]
This is still reproducible in WinAppSDK v1.6.250108002.
This issue affects not only the `ItemsRepeater` but also the `ItemsView` and CommunityToolkit's `SettingsExpander`, which uses the `ItemsRepeater` internally.
Please reopen this.

**Comment by tipa** [comment]
I agree wth @AndrewKeepCoding, please re-open this issue, this is clearly a bug. With the example project in the linked issue, the crash can also be easily and reliably reproduced.

**Comment by Hemantxk** [comment]
@AndrewKeepCoding @tipa Is this still reproducing in latest WinAppSDK 2.3.1? We had fixed a bug related to ItemsRepeater leaking, can you please check with latest package?

**Comment by tipa** [comment]
Thanks! I retested the two related issues I linked:

- CommunityToolkit/Windows#616
- microsoft/microsoft-ui-xaml#10341

Both crashes are still reproducible with WinAppSDK 2.3.1.

The original #7639 repro is a UWP/WinUI 2 project, so I also ported its relevant logic to WinUI 3. I could not reproduce that particular crash with either WinAppSDK 1.6.241114003 or 2.3.1. Therefore, the ItemsRepeater leak fix may have resolved #7639’s scenario, but it does not appear to resolve the two related crashes above.

**Comment by Hemantxk** [comment]
Thanks @tipa for confirmation. I couldn't' reproduce this (#7639) either with WinUI3. The other two issues that you linked seem unrelated to this one.

**Comment by AndrewKeepCoding** [comment]
Thanks @Hemantxk!
Just confirmed the same steps @tipa did. We still have issues with the `ItemsRepeater`. Both of the links @tipa mentioned above contain 100% reproducible project. Please use those to narrow it down the issue.🙂
