### ISSUE TITLE
Datagrid sorting memory leak

### ISSUE THREAD

**Issue by FrancoisKr** [microsoft/microsoft-ui-xaml#7641]
### Describe the bug

When clicking multiple times on columns headers with sorting implemented, memory usage increases on each click (sort) and eventually the application will crash with the following exception:
Message = "Insufficient memory to continue the execution of the program."

### Steps to reproduce the bug

Set up a datagrid with sorting as per:
https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/datagrid_guidance/group_sort_filter

Click multiple times on column headers

Memory usage increases on each click

### Expected behavior

Datagrid is sorted without memory leak

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by gabbybilka** [comment]
@michael-hawker FYI - I believe this is on WCT.

**Comment by michael-hawker** [comment]
Looks similar/the same to this one that was also filed: https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4737

I asked if @RBrid had a few moments to assist as this is still all code that was contributed by the WinUI team. FYI @ryandemopoulos

**Comment by FrancoisKr** [comment]
I don't have the problem with the mouse over, only when sorting the columns when sorting CanUserSortColumns="True".

This can be very easily reproduced and observed with the WCT sample app
![Datagrid memory leak](https://user-images.githubusercontent.com/36109031/186995481-b0d8d473-1e65-448e-b0c8-3e3b8297706c.jpg)
.

**Comment by FrancoisKr** [comment]
After further investigation this is not related to the datagrid itself.

It's due to the creation of a new Observable Collection on each sort as shown in the sample code of the documentation:
https://learn.microsoft.com/en-us/windows/communitytoolkit/controls/datagrid_guidance/group_sort_filter

The right way is to use the same observable collection (clear and repopulate the same observable collection on each sort).

**Comment by michael-hawker** [comment]
Thanks for the info on your investigation @FrancoisKr. I would have thought the garbage collector would clean-up old collections, so it's still a bit odd. I suppose there should at least be an issue on the docs repo to improve the sample maybe?

**Comment by michael-hawker** [comment]
@gabbybilka how do you want to best track this? Should this issue remain here and updated to call out the sample/docs or open a separate issue in the https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs repo where this documentation lives?
