### ISSUE TITLE
NavigationView expanded side nav missing border and rounded corners

### ISSUE THREAD

**Issue by MajorXAML** [microsoft/microsoft-ui-xaml#7644]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
NavigationView 

**Describe the bug:**
I noticed that NavigationView in VisualStudio project is different from the version presented in Windows UI Toolkit (figma)

**Version Info:**
2.7

**Additional context:**
I also noticed similar changes in the Windows 11 preview and WinUI 3 Gallery itself

![image_2022-08-25_020733055](https://user-images.githubusercontent.com/93913816/186539016-10614d2f-23bc-447a-bf80-a83e90acee41.png)

**Comment by alejo4000** [comment]
Hi @MajorXAML, I think this might be a bug on XAML and not the toolkit. I've checked previous versions of the XAML Controls apps (WinUI 2, WinUI 3) and WinUI 2 matches the toolkit, but WinUI 3 matches what your project is showing. Do you have WinUI 3 installed for your VS Project?

**Comment by MajorXAML** [comment]
Hi @alejo4000 
I'm a little confused. Because Toolkit displays controls from winui 3 and they should be the same or am I missing something? These changes are not only in WinUI Gallery 3, but also in Window 11 itself. In the Windows settings there is no border (but the corners are rounded). In the new task manger the side menu looks different again. Maybe you can explain which side-menu is considered correct 🤔

![Untitled111](https://user-images.githubusercontent.com/93913816/187262707-596d0ba6-f124-4665-b2e9-7ad8ebacb8ca.png)

> Do you have WinUI 3 installed for your VS Project?

Yep
