### ISSUE TITLE
CommandBarFlyout with Placement="Right" aligns to the left of a TreeViewItem.

### ISSUE THREAD

**Issue by tinodo** [microsoft/microsoft-ui-xaml#7649]
### Describe the bug

When I use: CommandBarFlyout.ShowAt(sender)
and my sender is a TreeViewItem and my CommandBarFlyout is set with Placement="Right", the flyout will occur on the left of the TreeViewItem, which I didn't expect.
I would expect the flyout to appear at the right of the TreeViewItem.

### Steps to reproduce the bug

Create a control/page/window with the following XAML:

``` <UserControl.Resources>
        <CommandBarFlyout Placement="Right" x:Name="CommandBarFlyout1">
            <AppBarButton Label="Share" Icon="Share" ToolTipService.ToolTip="Share" />
            <AppBarButton Label="Save" Icon="Save" ToolTipService.ToolTip="Save" />
            <AppBarButton Label="Delete" Icon="Delete" ToolTipService.ToolTip="Delete"/>
            <CommandBarFlyout.SecondaryCommands>
                <AppBarButton x:Name="ResizeButton1" Label="Resize"  />
                <AppBarButton x:Name="MoveButton1" Label="Move"  />
            </CommandBarFlyout.SecondaryCommands>
        </CommandBarFlyout>

    </UserControl.Resources>
    
    <Grid ColumnDefinitions="*" RowDefinitions="Auto, *">
        <TreeView Grid.Row="1" Grid.Column="0" SelectionMode="Single" Name="tvActions" ItemsSource="{x:Bind ActionNodes}" >
                <TreeView.ItemTemplate>
                    <DataTemplate x:DataType="controlpages:ActionNodeContent">
                    <TreeViewItem ContextRequested="TreeViewItem_ContextRequested" IsExpanded="True" ItemsSource="{x:Bind Children}" Tag="{x:Bind}">
                        <TextBlock TextDecorations="{x:Bind IsEnabled, Converter={StaticResource TextDecorationsConverter}, Mode=OneWay}" Text="{x:Bind Title, Mode=OneWay}" />
                    </TreeViewItem>
                </DataTemplate>
                </TreeView.ItemTemplate>
            </TreeView>
    </Grid>

With the following C# code behind the TreeViewItem_ContextRequested method:

       private void TreeViewItem_ContextRequested(UIElement sender, ContextRequestedEventArgs args)
        {
            var isTransient = true;
            FlyoutShowOptions myOption = new FlyoutShowOptions();
            myOption.ShowMode = isTransient ? FlyoutShowMode.Transient : FlyoutShowMode.Standard;
            CommandBarFlyout1.ShowAt(sender, myOption);
        }
```

Start the app, right-click an item in the TreeView and see the Flyout appear on the left of the TreeViewItem.

### Expected behavior

I would expect the flyout to appear to the RIGHT of the TreeViewItem since the CommandBarFlyout Placement="Right"

### Screenshots

![image](https://user-images.githubusercontent.com/44774639/186711859-4ffa695c-5422-42e3-b151-e93a82d84d55.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The flyout sample was taken from the WinUI 3 Gallery and applied to a TreeView from the same app.

**Comment by tinodo** [comment]
A workaround is:
Get the TextBlock from the TreeViewItem.Content, and use THAT object in CommandBarFlyout1.ShowAt(sender, myOption);

**Comment by bkudiess** [comment]
Could you try setting myOption.Placement to right.
