### ISSUE TITLE
Using AddSingleton, a strange exception occurs

### ISSUE THREAD

**Issue by ssccinng** [microsoft/microsoft-ui-xaml#7653]
### Describe the bug

When I register a callback function in the ViewModel, when I leave this page (it is useless to enter again), if the callback function is called, the program will crash(wher server start, there will be a callback message). If a static class is used to implement similar functions, this problem will not occur, and such an error will not occur when addsingleton is used in the console application

（use snap7 s7server）

### Steps to reproduce the bug

It's complicated, so I simply recorded a video to demonstrate various situations, and only one case won't crash
https://youtu.be/WTO86JzAY5M

### Expected behavior

It can be started normally

### Windows app type

- [ ] UWP
- [ ] Win32

### Windows version

Windows 10 (21H2): Build 19044

**Comment by bkudiess** [comment]
This seems unrelated to WinUI.

**Comment by ssccinng** [comment]
> This seems unrelated to WinUI.

At the end of the video, I tested the console application under the same scenario. It works normally, but winui does not work. Should I submit this question in the dotnet runtime

**Comment by ssccinng** [comment]
https://github.com/ssccinng/TestWinUI3Bug
