### ISSUE TITLE
WinUI 3 Custom TitleBar "Minimize/Maxmize/Close" Button too Small

### ISSUE THREAD

**Issue by MSEDGE-CORE** [microsoft/microsoft-ui-xaml#7656]
### Describe the bug

WinUI 3 Custom TitleBar "Minimize/Maxmize/Close" Button too Small and it's not conform to the Fluent Design and other apps (like Edge/Store/Settings etc. WinUI 2 Apps)

### Steps to reproduce the bug

1. Launch an WinUI3 App
2. Go to the top right corner

### Expected behavior

![image](https://user-images.githubusercontent.com/74437699/187056182-a6180f78-d587-476c-8a89-5179193412dc.png)
it should be Vertically centered of the TitleBar

### Screenshots

![image](https://user-images.githubusercontent.com/74437699/187056184-a38794c2-19e0-449c-8042-4b4b051b1e11.png)
![image](https://user-images.githubusercontent.com/74437699/187056194-d1af6d15-8e7a-4559-a948-51d07ce22ed0.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Experimental: 1.2.220727.1-experimental1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by pratikone** [comment]
this looks like a bug.

**Comment by pratikone** [comment]
It is fixed in 1.4 and should be closed

**Comment by akoc1** [comment]
Hey there! I solved this problem with this line of code in MainWindow.xaml.cs file:

`this.AppWindow.TitleBar.PreferredHeightOption = TitleBarHeightOption.Tall;`
