### ISSUE TITLE
Build errors after adding WinUI 3 library  to WinUI App

### ISSUE THREAD

**Issue by AlanKharebov** [microsoft/microsoft-ui-xaml#7657]
### Describe the bug

I wanted to add WinUI 3 library to WinUI 3 App.
After added libary tp app, I am getting this error,.

`
Error	NETSDK1022	Duplicate 'Page' items were included. The .NET SDK includes 'Page' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultPageItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'MainWindow.xaml'	ProjectK.Toolkit.WinUI.Controls.TestApp	C:\Users\ak61u\.nuget\packages\microsoft.projectreunion.winui\0.8.12\buildTransitive\Microsoft.WinUI.targets	54	
`

### Steps to reproduce the bug

What I have 
## 1. Visual Studio 2022  Preview 17.4.0 1.0
![image](https://user-images.githubusercontent.com/17842209/187057007-3c3b4cd6-60ca-4184-8df5-540976482684.png)

##  2. Create WinUI 3 App in Visual Studio 2022 Preview 
![image](https://user-images.githubusercontent.com/17842209/187057051-c20c7aa7-bade-423b-9898-d6de739e4c10.png)

## 3. Add Class Library
![image](https://user-images.githubusercontent.com/17842209/187057113-636e6d92-6d06-49f4-a000-49e9350282d7.png)

## 4. Solution now have  two projects App1 and ClassLibrary1 
![image](https://user-images.githubusercontent.com/17842209/187057147-7dd33d4c-08b1-481f-a0da-adb42b12ea9b.png)

## 5. App Runs
![image](https://user-images.githubusercontent.com/17842209/187057189-4cd62f4a-c757-45d7-a54c-5ee2f7df633d.png)

## 6. Nuget Packages 
![image](https://user-images.githubusercontent.com/17842209/187057296-63e16d16-0c41-46f6-a7e2-4305ec999658.png)

## After adding project ClassLibrary1  to app App1, Visaal Studio shows Warnings and Error

![image](https://user-images.githubusercontent.com/17842209/187057331-c64dff04-ece3-4deb-8c28-9395fe51336d.png)

### Expected behavior

Adding WinUI 3 libray to WinUI 3 App, should not cause any error.
This is expected behavour.

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by evelynwu-msft** [comment]
@AlanKharebov Can you share your solution? I am not able to reproduce this which leads me to suspect that for the "add project ClassLibrary1 to app App1" step I am not doing the same thing that you are.
