### ISSUE TITLE
Can't remove padding of custom ContentDialog WinUI3

### ISSUE THREAD

**Issue by AtosNicoS** [microsoft/microsoft-ui-xaml#7659]
### Describe the bug

As requested, here is a new Bug For WinUI3. It is a followup on this one:
https://github.com/microsoft/microsoft-ui-xaml/issues/5688

### Steps to reproduce the bug

There is no way to set a padding

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by bpulliam** [comment]
Are you still seeing this in 1.2? The WinUI2 fix was ported a while ago, so it would be a different issue if you're still seeing it.
