### ISSUE TITLE
insert items to an ObservableCollection<> which bounded to NavigationView.MenuItemsSource throws exception

### ISSUE THREAD

**Issue by Palatis** [microsoft/microsoft-ui-xaml#766]
**Describe the bug**
I had a `NavigationView` where its `MenuItemsSource` set to an `ObservableCollection`.
When I try to manipulate the collection, it throws an `System.Exception` with `Message` = "The operation attempted to access data outside the valid range (Exception from HRESULT: 0x8000000B)".

**Steps to reproduce the bug**

1. with these codes
2. hit the button like crazy (much easier to reproduce if done before previous animation ends)
```
XAML:
<winui:NavigationView PaneDisplayMode="Top" MenuItemsSource="{x:Bind SomeStrings}"/>
```
```
C#:
public ObservableCollection<string> SomeStrings { get; } = new ObservableCollection<string>();
...
public Button_Click(object sender, RoutedEventArgs args) => SomeStrings.Insert(0, "blah");
```

**Version Info**

NuGet package version: 2.2.190430003-prerelease, 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | |
| May 2019 Update (18362.145)            | yes |
| October 2018 Update (17763)        | |
| April 2018 Update (17134)          | |
| Fall Creators Update (16299)       | |
| Creators Update (15063)            | |
| Anniversary Update (14393)         | |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | yes   |
| Mobile                   | |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
There is some logic for doing overflow in top mode that we've seen issues like this before. @licanhua do you have time to take a look at this crash?

**Comment by licanhua** [comment]
@Palatis What's your actual use case? 
Top NavigationView don't support duplicated items in MenuItemsSource . You may workaround the problem by put 'blah' in a object and then provides unique object in MenuItemsSource .

This is a known restriction and kind of 'by design'. The problems happens when duplicated items are found in the MenuItemsSource and items are going to overflow.

Top navigationview has problem to split the data into two parts because two "blah" in the array.
For example, the MenuItemsSource=["blah","blah"] , If customer select a item by 'blah', C++ has problem to know if it's the first one or 2nd one. so topnavigationview depends on ObservableCollection.indexOf the identify the problem.

**Comment by Palatis** [comment]
okay, in fact I'm having my own data class to do some more complex binding, I was using the example just to demonstrate, didn't know that the underlying native code has difficulties distinquishing between the 2 "blah"s.

However the problem is the same for the following code:
```
C#:
publi8c class MyClass {
  public string Header;
}
public ObservableCollection<MyClass> MyStuff { get; } = new ObservableCollection<MyClass>();
...
public Button_Click(object sender, RoutedEventArgs args) => MyStuff.Insert(0, new MyClass() { Header = "blah" });
```
```
XAML:
<winui:NavigationView PaneDisplayMode="Top" MenuItemsSource="{x:Bind SomeStrings}">
  <winui:NavigationView.MenuItemTemplate>
    <DataTemplate x:DataType="{local:MyClass">
      <winui:NavigationViewItem Content="{x:Bind Header}"/>
    </DataTemplate>
  </winui:NavigationView.MenuItemTemplate>
</winui:NavigationView>
```

If I replace `MyStuff.Insert()` with `MyStuff.Add()` then no exception is being thrown (so far)...

**Comment by Palatis** [comment]
I actually found a bit little more...

When there are too many items, `NavigationView` arrange them to a drop-down menu (`More...` button)
1. With no item selected (`NavView.SelectedItem == null`) it throws exception when I do `MyStuff.Add()` or `MyStuff.Insert()` (access data outside valid range), but everything else is fine (UI draws with no problem, data is added to the collection).
2. As soon as I click on the item inside the drop-down menu, it throws an exception (access data outside valid range).
3. selecting those items where they're not inside the drop-down menu runs with no problem at all.

**Comment by Palatis** [comment]
I found a way to workaround the problem...
detach the `MenuItemsSource` from the `NavigationView` before toying around with the collection...

```
public Button_Click(object sender, RoutedEventArgs args) {
   NavView.MenuItemsSource = null; 
   MyStuff.Insert(0, new MyClass() { Header = "blah" });
   NavView.MenuItemsSource  = MyStuff;
}
```

however I don't think this is the **correct** way of doing things...

**Comment by Palatis** [comment]
> @Palatis What's your actual use case?

I'm using the `NavigationView` as a `TabControl` (because I liked its Look & Feel & Animation... instead of `Pivot` and `Microsoft.Toolkit.Uwp.UI.Controls.TabControl`), something like the tabs in a web browser.
I'll have a bunch of files with different content for the user to modify.

**Comment by licanhua** [comment]
Yes. it's a bug. and I didn't see any other way to workaround the problem except what you provided.

**Comment by Palatis** [comment]
selecting the item programatically also crashes the app.

```
// code that don't work
public Button_Click(object sender, RoutedEventArgs args)
{
   var item = new MyClass() { Header = "blah" };
   MyStuff.Insert(0, item);
   NavView.SelectedItem = item;
}
```

however detach `ItemsSource` first before manipulating does work:
```
// code that works
public Button_Click(object sender, RoutedEventArgs args)
{
   var item = new MyClass() { Header = "blah" };
   NavView.MenuItemsSource = null; 
   MyStuff.Insert(0, item);
   NavView.MenuItemsSource  = MyStuff;
   NavView.SelectedItem = item;
}
```

**Comment by licanhua** [comment]
@jevansaks problem may exists in SplitDataSourceBase. The datasource is split to two datasource: primary and overflow. they both have index to the raw datasource. when a new item is inserted to the position like 0, the index to original datasource didn't keep update and caused the problem.
Except code change, a lot of test effort should be involved, and the estimation may over 1 day. assign back the bug to you to do the triage.

**Comment by jevansaks** [comment]
Thanks for investigating. Since our focus is on WinUI 3.0 right now, i'll move this to the backlog. @Palatis (and others) if you want to contribute a fix to this, we would welcome it but we won't be able to get to it ourselves for a while.

**Comment by MichaelRumpler** [comment]
It's got nothing to do with the `ObservableCollection`. I bound `MenuItemsSource` to an array and replaced the whole array and I also get an IndexOutOfRangeException.

**Comment by ranjeshj** [comment]
@MichaelRumpler  This issue is quite old and NavigationView has had quite a fixes since then (a complete refactor in fact). Are you seeing this issue with the latest prerelease version ? If so, can you file a new issue and provide a repro app ?

**Comment by MichaelRumpler** [comment]
Ok, I created #2818
