### ISSUE TITLE
Font icon's "MirroredWhenRightToLeft" property is not working in Run time changes.

### ISSUE THREAD

**Issue by sethuramkumar** [microsoft/microsoft-ui-xaml#7661]
### Describe the bug

Hi Team,

when changing the flow direction in run time, with **MirroredWhenRightToLeft** property of font icon as true, font icon is not mirrored, not updated properly.
**"MirroredWhenRightToLeft** property works fine on initial loading alone.

```
<Grid Width="800" Height="200" BorderBrush="RoyalBlue" BorderThickness="3">
    <Grid.Resources>
        <Style TargetType="StackPanel">
            <Setter Property="HorizontalAlignment" Value="Center"/>
            <Setter Property="VerticalAlignment" Value="Center"/>
        </Style>
    </Grid.Resources>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*"/>
        <ColumnDefinition Width="*"/>
        <ColumnDefinition Width="*"/>
    </Grid.ColumnDefinitions>
    <StackPanel Orientation="Vertical" FlowDirection="RightToLeft"   >
        <TextBlock Text="Right To Left - On Inital loading"/>
        <FontIcon Glyph="&#xE76C;"  Foreground="Black" FontSize="30" MirroredWhenRightToLeft="True" />
    </StackPanel>
    <StackPanel Orientation="Vertical" Grid.Column="1" x:Name="panel" >
        <TextBlock x:Name="textBlock" Text="Right To Left - Run time changing"/>
        <FontIcon Glyph="&#xE76C;" Foreground="Black" FontSize="30" MirroredWhenRightToLeft="True" />
    </StackPanel>
    <Button x:Name="myButton" Grid.Column="2" Click="myButton_Click">Change Flow Direction</Button>
</Grid>

```
Code Behind:

```
private void myButton_Click(object sender, RoutedEventArgs e)
{
    textBlock.Text = "Right To Left- Changed in Run time";
    panel.FlowDirection = FlowDirection.RightToLeft;
}
```

### Steps to reproduce the bug

1.Provide font icon within a grid/stacklayout with **MirroredWhenRightToLeft** as true.
2,Modify the flow direction in run time.
3.Note icon is not mirrored.

### Expected behavior

Icon should be mirrored based on the flow direction when the flow direction is changed at run time.

### Screenshots

Before Changing the flow direction:

![image](https://user-images.githubusercontent.com/92511047/187205734-f050bc10-fc67-4fa0-8349-fbf72e54e888.png)

After Changing the flow direction :

![image](https://user-images.githubusercontent.com/92511047/187205830-267f1800-b0c6-44e1-8fa9-e05f70d03303.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ghost1372** [comment]
fixed in 1.3.3
