### ISSUE TITLE
What a way to create a semibold font?

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#7664]
Hi, the enum FontAttributes contains only 3 states - None, Bold, Italic. How can I set a semibold font?

**Comment by mdtauk** [comment]
in Xaml, you would use FontWeight.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/6641b77a-a86c-4708-b7dd-183b212d582c)
