### ISSUE TITLE
ListView incorrect Visual Style in 1.2.0-experimental1

### ISSUE THREAD

**Issue by Sanlorng** [microsoft/microsoft-ui-xaml#7666]
### Describe the bug

the incorret visual style reported in #6064 was reproduced. 

### Steps to reproduce the bug

1. Create ListViewControl
2. SelectionMode set Single or Multiple
3. Select item

### Expected behavior

Display the correct visual style

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Experimental: 1.2.220727.1-experimental1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by kmgallahan** [comment]
Upgraded to 1.2 Preview today. My ListViews are once again tilting... woe is me... 

@gabbybilka @codendone

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.2.220930.4-preview2` has been released which fixes this issue.
		
Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2-preview2/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.220930.4-preview2)
