### ISSUE TITLE
Changing the background color of a TabView results in a 1px gap underneath inactive `TabViewItem`s

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#7674]
### Describe the bug

As noted in https://github.com/microsoft/terminal/issues/13725

From WinUI Controls Gallery:
![](https://user-images.githubusercontent.com/18356694/187287364-ba2a4131-4895-4756-be60-fe59f28057d7.png)

### Steps to reproduce the bug

Set a Background to the TabView. 

Hover an inactive tab.

### Expected behavior

The bottom of inactive tabs is flush with the bottom of the tab view, like the active tab is (but probably without the curves?)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

### Additional context

We're on 2.7.3, but blocked from 2.8 for ~ reasons ~ that y'all are already familiar with.

**Comment by dansmor7** [comment]
The gap is somewhat intentional - TabView has a semi-transparent border, and the gap exists so that the inactive tab doesn't overlap it.
This can be changed by modifying `TabViewItemBorderThickness` to something like `1,1,1,0`.

**Comment by zadjii-msft** [comment]
> The gap is somewhat intentional - TabView has a semi-transparent border, and the gap exists so that the inactive tab doesn't overlap it. This can be changed by modifying `TabViewItemBorderThickness` to something like `1,1,1,0`.

THANK YOU that totally worked!
![image](https://user-images.githubusercontent.com/18356694/187909912-de5b34c3-843e-4aee-ba8c-f3b53332e2dd.png)
