### ISSUE TITLE
WinUI 3 hot reload stopped working after some Updates

### ISSUE THREAD

**Issue by DmitriMilokhov** [microsoft/microsoft-ui-xaml#7687]
### Describe the bug

Hello. After installation some update via Windows Update Center Hot Reload for WinUI 3 apps stooped working. I have feeling that these ones:
![image](https://user-images.githubusercontent.com/32032852/188472538-53f26bcd-8868-48af-8928-8a9faa329e89.png)

Also xaml debug tools have disappeared from the app when it is on debug, and live visual tree shows nothing: 
![image](https://user-images.githubusercontent.com/32032852/188472977-4b227a07-fa2d-4084-b06c-d47be32aa6d7.png)

All settings are set. It (hot reload, debug tools, live tree) used to work several days ago until some updates are installed.

### Steps to reproduce the bug

1. Start Debugging some WinUI 3 project.
2. See that hot reload is not working. 

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H1): Build 19043

**Comment by SoggyBottomBoy** [comment]
I have the same issue. I tried the "repair" visual studio option which did not fix the problem.

### Visual Studio Version
Version 17.4.0 Preview 1.0

### NuGet package version
WinUI 3 - Windows App SDK 1.1.4

### Windows version
Windows 10 (21H1): Build 19043

**Comment by SoggyBottomBoy** [comment]
I created a fresh WinUI project and copied across all my source code and the hot-reload was once again available. However 3 days later I again have the same issue and am unsure how to get diagnostic information to resolve the problem. I haven't changed any settings in visual studio nor have I changed the csproj or the appsettings.

Is there are way to get further information with regards to why the xaml hot reload is unavailable?

**Comment by kmgallahan** [comment]
Try deleting the .bin and .obj folders in your project (VS closed).

**Comment by SoggyBottomBoy** [comment]
no luck...
![image](https://user-images.githubusercontent.com/36346832/189779582-595740f3-1816-4b2d-af2d-d97515f69be0.png)

**Comment by AtosNicoS** [comment]
I have the same issue. It seems to come after some visual studio update.

**Comment by TimKAtos** [comment]
I have the same issue as well

**Comment by Trix07** [comment]
I had the same issue, as you described, and was able to find a workaround.

Run the following commands in an elevated command prompt, where you replace the WindowsAppRuntime version with your currently installed version.

```
takeown /f “C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1004.584.2120.0_x64__8wekyb3d8bbwe” /r /d y
icacls.exe “C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1004.584.2120.0_x64__8wekyb3d8bbwe” /grant Users:(RD,R,REA,RX) /t
```

**Comment by TimKAtos** [comment]
@Trix07 it tells me that y is not an valid value for option /d

**Comment by Trix07** [comment]
That's weird, are you sure you typed it correctly? And that it's an elevated command prompt?

I'm afraid that the "/d" is required since it uses "/r", so it cannot be ignored.

![image](https://user-images.githubusercontent.com/83061617/195525376-2ff56b87-afdd-40c1-a666-c3f3ab9cc81a.png)

**Comment by TimKAtos** [comment]
Ah my bad. My system is set to german so it required j for "Ja" instead of y for "yes"

**Comment by TimKAtos** [comment]
@Trix07  After the first command it tells me that various files now belong to my user. This is right. After that I run the second command but it tells me that "Assignments of account names and security identifiers were not performed. 0 files processed." 

Do you know what this problem is?

After I restarted Visual Studio the problem remained.

**Comment by Trix07** [comment]
Not really, when I ran the last command I got the following: "Successfully processed 233 files; Failed processing 0 files".
Perhaps you don't have the required permission?

Other than that the only thing I didn't mention was that I took ownership of the WindowsApps folder before running the commands. That was only to verify my installed WindowsAppRuntime version, but perhaps it's necessary.
https://www.makeuseof.com/windows-access-windowsapps-folder/

**Comment by SoggyBottomBoy** [comment]
I'm not sure where this is documented but I have now just realised that the issue I was having was due to debugging an x64 build. By switching to x86 build the xaml hot reload just worked.

I'm curious if this is the expected behaviour? i.e. xaml hot reload is only support for x86 builds?

**Comment by Trix07** [comment]
@SoggyBottomBoy I don't think that's the case since x64 works fine for me, although now and then it breaks, and I have to run the command I posted earlier again.
