### ISSUE TITLE
NavigationView.PaneDisplayMode="Top" doesn't layout tabs correctly when selecting items in the overflow menu

### ISSUE THREAD

**Issue by Palatis** [microsoft/microsoft-ui-xaml#769]
**Describe the bug**
When `NavigationView` with `PaneDisplayMode="Top"`, it doesn't update the layout correctly when an item is selected from the overflow menu.

**Steps to reproduce the bug**
1. with the following code
2. click on the `NavigationViewItem` inside the overflowed menu

```
XAML:
<winui:NavigationView PaneDisplayMode="Top" MenuItemsSource="{x:Bind SomeItems}"/>
```
```
C#:
// need a long list to make the tabs overflow
public string[] SomeItems { get; } = new string[] { "Tab 1", "Tab 2", "Tab 3", ... , "Tab 20" };
```

**Screenshots**
Yeah I know a picture worth a thousand words, but this time a thousand word is probably not enough, so I attached a video on Youtube...

https://www.youtube.com/watch?v=kjip7NWV5j0

however with XBox Game Bar, the overflow dropdown flyout is not captured...

As you can see in the video, `PaneFooter` is pushed outside the window...

**Version Info**

NuGet package version: v2.2.190430003-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362.145)            |  yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |   yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by Palatis** [comment]
however, with these:
```
XAML:
<winui:NavigationView PaneDisplayMode="Top" MenuItemsSource="{x:Bind SomeItems}" SelectionChanged="NavView_SelectionChanged"/>
```
```
C#:
// need a long list to make the tabs overflow
public string[] SomeItems { get; } = new string[] { "Tab 1", "Tab 2", "Tab 3", ... , "Tab 20" };
...
private void NavView_SelectionChanged(winui.NavigationView sender, winui.NavigationViewSelectionChangedEventArgs args) =>
  NavView.InvalidateMeasure();
```

Then the `NavigationView` will render it's children correctly.

**Comment by jevansaks** [comment]
Interesting bug, thanks for the detailed report!

**Comment by jevansaks** [comment]
Another report in #943.

**Comment by StephenLPeters** [comment]
Thanks!
