### ISSUE TITLE
VS 2019/2022 debug WinUI3 unpackaged app crash immediately (v1.14)

### ISSUE THREAD

**Issue by gscheartA** [microsoft/microsoft-ui-xaml#7694]
### Describe the bug

Create WinUI3 unpackaged app and fill some code, after some days, I debug the code, but the app crash immediately.
Here are the error logs print in console:

D:\a\_work\1\s\dev\WindowsAppRuntime_BootstrapDLL\MddBootstrap.cpp(814)\Microsoft.WindowsAppRuntime.Bootstrap.dll!00007FF80F64A779: (caller: 00007FF80F6492CF) LogHr(1) tid(174c) 80040010 Object is not in any of the inplace active states
    Msg:[Bootstrap.Intitialize: Scanning packages for Major.Minor=1.1, Tag=, MinVersion=1004.584.2120.0] CallContext:[\Initialize] 

D:\a\_work\1\s\dev\WindowsAppRuntime_BootstrapDLL\MddBootstrap.cpp(923)\Microsoft.WindowsAppRuntime.Bootstrap.dll!00007FF80F64B1FE: (caller: 00007FF80F6492CF) LogHr(2) tid(174c) 80040012 Not able to perform the operation because object is not given storage yet
    Msg:[Bootstrap.Intitialize: Microsoft.WinAppRuntime.DDLM.1004.584.2120.0-x6_1004.584.2120.0_x64__8wekyb3d8bbwe is applicable (Major.Minor=1.1, Tag=, MinVersion=1004.584.2120.0)] CallContext:[\Initialize] 
D:\a\_work\1\s\dev\WindowsAppRuntime_BootstrapDLL\MddBootstrap.cpp(914)\Microsoft.WindowsAppRuntime.Bootstrap.dll!00007FF80F64B098: (caller: 00007FF80F6492CF) LogHr(3) tid(174c) 80040011 Not able to convert object
    Msg:[Bootstrap.Intitialize: Microsoft.WinAppRuntime.DDLM.1004.584.2120.0-x8_1004.584.2120.0_x86__8wekyb3d8bbwe not applicable. Architecture doesn't match current architecture x64 (Major.Minor=1.1, Tag=, MinVersion=1004.584.2120.0)] CallContext:[\Initialize] 

D:\a\_work\1\s\dev\WindowsAppRuntime_BootstrapDLL\MddBootstrap.cpp(946)\Microsoft.WindowsAppRuntime.Bootstrap.dll!00007FF80F64BB26: (caller: 00007FF80F6492CF) LogHr(4) tid(174c) 80040013     Msg:[Bootstrap.Intitialize: Microsoft.WinAppRuntime.DDLM.1004.584.2120.0-x6_1004.584.2120.0_x64__8wekyb3d8bbwe best matches the criteria (Major.Minor=1.1, Tag=, MinVersion=1004.584.2120.0) of 98 packages scanned] CallContext:[\Initialize] 

D:\a\_work\1\s\dev\WindowsAppRuntime_BootstrapDLL\MddBootstrap.cpp(373)\Microsoft.WindowsAppRuntime.Bootstrap.dll!00007FF80F648AE7: (caller: 00007FF80F64779A) Exception(1) tid(174c) 80070005 Access is denied.
    Msg:[Error in LoadLibrary: 5 (0x5) loading C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1004.584.2120.0_x64__8wekyb3d8bbwe\Microsoft.WindowsAppRuntime.dll] CallContext:[\Initialize] 
Exception thrown at 0x00007FF88CC74FD9 in demo.exe: Microsoft C++ exception: wil::ResultException at memory location 0x000000417F77A940.
Exception thrown at 0x00007FF88CC74FD9 in demo.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
D:\a\_work\1\s\dev\WindowsAppRuntime_BootstrapDLL\MddBootstrap.cpp(213)\Microsoft.WindowsAppRuntime.Bootstrap.dll!00007FF80F65D87B: (caller: 00007FF80F647487) ReturnHr(1) tid(174c) 80070005 Access is denied.
    Msg:[D:\a\_work\1\s\dev\WindowsAppRuntime_BootstrapDLL\MddBootstrap.cpp(373)\Microsoft.WindowsAppRuntime.Bootstrap.dll!00007FF80F648AE7: (caller: 00007FF80F64779A) Exception(1) tid(174c) 80070005 Access is denied.
    Msg:[Error in LoadLibrary: 5 (0x5) loading C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1004.584.2120.0_x64__8wekyb3d8bbwe\Microsoft.WindowsAppRuntime.dll] CallContext:[\Initialize] 
] CallContext:[\Initialize] 
D:\a\_work\1\s\dev\WindowsAppRuntime_BootstrapDLL\MddBootstrap.cpp(166)\Microsoft.WindowsAppRuntime.Bootstrap.dll!00007FF80F6475C8: (caller: 00007FF7A0CA6491) ReturnHr(2) tid(174c) 80070005 Access is denied.
    CallContext:[\Initialize] 
The thread 0x3bd0 has exited with code -2147024891 (0x80070005).
The thread 0x24c0 has exited with code -2147024891 (0x80070005).
The thread 0x386c has exited with code -2147024891 (0x80070005).
The thread 0x28a8 has exited with code -2147024891 (0x80070005).
The thread 0x37d4 has exited with code -2147024891 (0x80070005).
The thread 0x3d24 has exited with code -2147024891 (0x80070005).
The thread 0x8ec has exited with code -2147024891 (0x80070005).
The thread 0x4294 has exited with code -2147024891 (0x80070005).
The thread 0x23e8 has exited with code -2147024891 (0x80070005).
The thread 0x42c0 has exited with code -2147024891 (0x80070005).
The thread 0x173c has exited with code -2147024891 (0x80070005).
The thread 0x291c has exited with code -2147024891 (0x80070005).
The thread 0x1210 has exited with code -2147024891 (0x80070005).
The thread 0x940 has exited with code -2147024891 (0x80070005).
The thread 0x13e4 has exited with code -2147024891 (0x80070005).
The thread 0x584 has exited with code -2147024891 (0x80070005).

### Steps to reproduce the bug

Install WinUI3 template and runtime(1.14 version).
Create a WinUI3 template project and fill some code.
Try to debug after somedays(maybe restart PC some times)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by gscheartA** [comment]
I found this issue will be fixed after downgrading sdk/runtime version to 1.13. 
I also found some related issue: https://issuehint.com/issue/microsoft/WindowsAppSDK/2918
Maybe useful for locating.

**Comment by bpulliam** [comment]
Upgrading to 1.2 should resolve this issue.  Please let us know if you still have issues after the upgrade.

**Comment by alkalinin** [comment]
I still have crashes with 1.2, see https://github.com/microsoft/WindowsAppSDK/issues/3298
