### ISSUE TITLE
Access Violation in WinUI 3

### ISSUE THREAD

**Issue by hez2010** [microsoft/microsoft-ui-xaml#7695]
### Describe the bug

We encountered access violation while developing a WinUI 3 app. It happens in the `PropertyChanged` event for our `ColumnsViewModel` (we use this ViewModel to provide column properties for ListView).
Given that the failure happens in unmanaged code with 0xC0000005, we think this might be a bug of WinUI 3.

### Steps to reproduce the bug

App dump: https://1drv.ms/u/s!ApWNk8G_rszRgooFZijjJphwT7b17g?e=1UowSc

### Expected behavior

No crashing is expected. 

### Screenshots

![image](https://user-images.githubusercontent.com/14960345/188847464-d6f38407-ed5b-4871-9cb0-050d633d1280.png)

![image](https://user-images.githubusercontent.com/14960345/188850723-c5e2b7a7-c454-4f0e-b52c-5fac4ace4b92.png)

### NuGet package version

WASDK 1.2-preview1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (25193)

**Comment by lukedukeus** [comment]
I hit this issue when binding to a property on an interface or abstract class with a treeview

**Comment by yaichenbaum** [comment]
This issue is blocking us from adopting WinUI 3. @gabbybilka

**Comment by MikeHillberg** [comment]
Agree it looks like a bug in WinUI3. Thanks for providing the debug info. In response to the property change notification, it's trying to reach back and get the new value, and it looks like the pointer it has to the internal ICustomProperty reflection object is bad.

In the interest of getting unblocked, maybe you could switch this binding to an {x:Bind}, or otherwise add some code to replace it. If it's happening for all of the bindings on this object, then that would be interesting to know too.

**Comment by hez2010** [comment]
We workarounded the issue by not replacing the whole viewModel but instead changing the properties of the viewModel. 
See https://github.com/files-community/Files/pull/10447.

**Comment by hez2010** [comment]
To recap this issue, it may happen when you are replacing the existing ViewModel with a new instance of ViewModel and then notify the changes using the `PropertyChanged` event.

```csharp
class ParentViewModel : INotifyPropertyChanged
{
    private ChildViewModel _children;
    public ChildViewModel Children
    {
        get => ...
        set
        {
            _children = value;
            PropertyChanged?.Invoke(this, new(nameof(ChildViewModel)));
        }
    }
}
```
Then bind your page to `ParentViewModel` and the column definitations of a `ListView` to `Children`. You may reproduce it if the `Children` being replaced frequently.

**Comment by yaira2** [comment]
@llongley as someone who manages a large repo, I understand the challenge of trying to manage issues and I appreciate everything that's being done to close old issues. Having said that, it's disappointing when issues get closed without having a discussion with the author who took the time to report the issue and keep it active. This doesn't reflect well on WinUI and I hope you reconsider the processes being used to close issues.
