### ISSUE TITLE
CommandBarFlyout causes crash with Windows.Ul.Xaml.LayoutCycleException

### ISSUE THREAD

**Issue by ThinhDb** [microsoft/microsoft-ui-xaml#7696]
### Describe the bug

Right-click Flyout menu using Command bar throw Windows.Ul.Xaml.LayoutCycleException & System.Exception on 2K monitor (2560x1440 & 125% Scale)
 
![image](https://user-images.githubusercontent.com/109563914/189006342-455b1e30-3ca0-42ef-8680-be61f30269c7.png)

![image](https://user-images.githubusercontent.com/109563914/189006413-a370405c-242f-4ca5-96f8-64250e0a4645.png)

![image](https://user-images.githubusercontent.com/109563914/189006442-669986f8-a7c5-4f4f-ac6f-f924aa1084b4.png)

### Steps to reproduce the bug

* Have two monitors side by side. One 4K monitor at 3840x2160 - 150% scale, and one 2K monitor at 2560x1440 - 125% scale.
<img width="166" alt="image" src="https://user-images.githubusercontent.com/109563914/189006656-eb2ac5c3-2637-4436-9fae-c0a9742eb51c.png">
<img width="159" alt="image" src="https://user-images.githubusercontent.com/109563914/189006672-ca8b41a5-4ff3-47fd-963c-b4c5dfd14fdc.png">

There are three scenarios:

Scenario 1:
* Start the application on the 4K monitor, right-click (first Tab or Orange grid) to show the flyout menu, then left-click anywhere to hide the flyout menu. Observe there is no scroller on the flyout.
<img width="376" alt="image" src="https://user-images.githubusercontent.com/109563914/189007090-324bf1d6-d3f8-4109-b957-e7a1cb140c9b.png">

* Next, move the application to the 2K monitor, and right-click (first Tab or Orange grid) to show the flyout menu, this time the flyout menu has a scroller. 
Scroll the flyout menu. Application crashes with  `Windows.Ul.Xaml.LayoutCycleException`
<img width="270" alt="image" src="https://user-images.githubusercontent.com/109563914/189007139-7622c09c-474a-4677-bb92-e669a4e6fdbb.png">

Scenario 2:
* Start the application on the 2K monitor, and right-click (first Tab or Orange grid) to show the flyout menu with the scroller. Scroll the menu. 
Application crashes with 
`System.Exception: ClassFactory cannot supply requested class\r\n\r\nWindows.Ul.Xaml.Controls.Primitives.CommandBarFlyoutCommandBarTemplateSettings`
And
 `Windows.Ul.Xaml.LayoutCycleException`

Scenario 3:
* Start the application on the 2K monitor, and right-click (first Tab or Orange grid) to show the flyout menu with the scroller, but don't scroll it. Left click to hide the menu.
* Move the application to the 4K monitor, right-click to show the flyout menu, and then left-click to hide it.
* Move the application back to the 2K monitor. 
Right-click and scroll the flyout menu. Application crashes with  `Windows.Ul.Xaml.LayoutCycleException`

### Expected behavior

The application shouldn't crash

Reproduce sample app:
[LayoutCycleTestApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9522476/LayoutCycleTestApp.zip)

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by yaira2** [comment]
This issue hasn't been resolved

**Comment by codendone** [comment]
A fix for this issue has just been completed for WinAppSDK 1.5 (same fix as for #6218). This had already been partially improved in WinAppSDK and also partially fixed in Windows 11 for system XAML (/WinUI2).
