### ISSUE TITLE
MediaPlayerElement most 4K 60 fps videos cannot seek

### ISSUE THREAD

**Issue by sudongg** [microsoft/microsoft-ui-xaml#7697]
### Describe the bug

In WinAppSDK 1.2 preview 1, I tried to play the video using MediaPlayerElement, but almost all 4K 60 fps video can't seek.
And uwp 18362 have the same problem.

//sample：
https://www.dropbox.com/s/sr950wny2qiiz8d/GODZILLA%20VS%20KONG%20Trailer%20%284K%20ULTRA%20HD%2060FPS%29%20NEW%202021.mkv?dl=0

### Steps to reproduce the bug

. MainWindow.xaml add
 `<MediaPlayerElement x:Name="PlayerElement"/>`

. MainWindow.xaml.cs add

```
        public MainWindow()
        {
            this.InitializeComponent();
             Play();
        }

        async void Play()
        {
            //open 4K 60 fps video
            var file = await StorageFile.GetFileFromPathAsync("E:\\GODZILLA VS KONG Trailer (4K ULTRA HD 60FPS) NEW 2021.mkv");
            _MediaSource = MediaSource.CreateFromStorageFile(file);
            PlayerElement.AutoPlay = true;
            PlayerElement.Source = _MediaSource;
   
            PlayerElement.AreTransportControlsEnabled = true;
        }

```
. Run
. Trying to drag the slider nothing happens

### Expected behavior

seek is valid

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Experimental: 1.2.220727.1-experimental1

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H1): Build 19043

**Comment by codendone** [comment]
Thanks for reporting this. Owners of the underlying MediaPlayer runtime have confirmed that this should work but something about sample media you provided is causing this bug. A bug has been opened ([internal link](http://task.ms/41251059)) for that team.
