### ISSUE TITLE
Webview2 do not work in WinUI3(1.14) unpackaged win32 app(x64 platform)

### ISSUE THREAD

**Issue by gscheartA** [microsoft/microsoft-ui-xaml#7705]
### Describe the bug

I use Webview2 in WinUI3(1.14) unpackaged win32 app.
I can use wbview2.EnsureCoreWebView2Async ... API  and webview show correctly in x86 platform.
But the webview could not shown in x64 platform. After I adding wbview2.EnsureCoreWebView2Async, I got "**Access Denied**" error.
I don't know if here is any difference between x86 and x64 related to webview2. This issue seems that the app use high privilege folder to store webview2 temp file in x64, but use exe folder by default in x86. By the way, I use 2 PC to test this issue and 1 machine reproduce it. Thank you for your help.

### Steps to reproduce the bug

1.Create WinUI3 unpackaged win32 app.
2.Create Webview2 control
3.Debug the app in x86 and x64(Some machines will reproduce this issue)

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by castorix** [comment]
Did you try to copy Microsoft.Web.WebView2.Core.dll  from "C:\Program Files\WindowsApps\" + the right Microsoft.WindowsAppRuntime x64 directory
to your executable x64 directory ?
(I had this problem with x86 and this fixed it, as workaround)
