### ISSUE TITLE
[ARM64] [WinUI] Build solution failed with the "ValidateAppxManifest" task failed unexpectedly

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#7706]
### Describe the bug

Build solution failed with the "ValidateAppxManifest" task failed unexpectedly.
![image](https://user-images.githubusercontent.com/97647558/189308478-dacad125-c8b2-4983-981a-27d307a0ff74.png)
![image](https://user-images.githubusercontent.com/97647558/189310042-5d23a7e0-91e8-4c42-8e8c-2edcf50bb43e.png)

### Steps to reproduce the bug
Environment:
Affected Branch: d17.4
Affected Build: 32908.99
Affected Product Language: ENU

1.Create project: Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop) (C#/C++).

2.Right click on the App project -> Add -> New Item -> User Control(WinUI 3).

3.Build and run your solution on your development computer.

### Expected behavior

Build successfully.

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by evelynwu-msft** [comment]
@bpulliam I suspect this is the same root cause as what I described here: https://github.com/microsoft/microsoft-ui-xaml/issues/7862#issuecomment-1294385149.

**Comment by bpulliam** [comment]
Please update the Windows.SDK.BuildTools  nuget to build 10.0.22621.755 and that should resolve your issue.
Thanks!

**Comment by XamlTest** [comment]
After successfully creating the project, an error box appears after the build has been running for a while.
![image](https://user-images.githubusercontent.com/97647558/199955175-2f144728-a437-4c3a-ae87-16608c6dbbea.png)
