### ISSUE TITLE
[x64] [WinUI]Unpackaged exception in x64 Solution Platforms build

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#7709]
### Describe the bug

Unpackaged exception in x64 Solution Platforms build
![image](https://user-images.githubusercontent.com/97647558/189352477-ef1d1c6c-93da-4723-8c6d-517c67e36a5a.png)

### Steps to reproduce the bug

Environment:
Affected Branch: d17.4
Affected Build: 32908.99
Affected Product Language: ENU
OS: Win10-22H2

**More info**: This issue does not reproduce on OS: Win11-22H2.

1.Create a new app using the "Blank App, Packaged(WinUI 3 in Desktop)" C++ project template
2.Add this property to the project file: 
![image](https://user-images.githubusercontent.com/97647558/205202428-e7e2a08d-2c1f-4e36-935c-498371f8e132.png)

3.Change 'AppxPackage' property to false:<AppxPackage>false</AppxPackage>
4. In [https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads downloads ](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads) downloads Windows App SDK 1.1-> Version-> 1.1.4-> Runtime downloads-> Installer(x64) and Installer(x86)
5. Select Solution Platforms is x64
6. Build and run

### Expected behavior

No Exception

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by XamlTest** [comment]
This is the exception that occurs after F5 starts.
![image](https://user-images.githubusercontent.com/97647558/191920128-0f66add9-3061-4693-aca8-a71a2c0c528d.png)

**Comment by XamlTest** [comment]
On d17.4-33006.217 F5 starts the interface appears, but then the error appears.
![image](https://user-images.githubusercontent.com/97647558/194735615-f829a7b1-64e3-4ee2-a575-8c701406ff54.png)
Error MSB6003 The specified task executable "MakePri.exe" could not be run. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.File name: 'Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'   at Microsoft.VisualStudio.Telemetry.TelemetrySessionInitializer.BuildInitializer(TelemetrySessionSettings telemetrySessionSettings)   at Microsoft.VisualStudio.Telemetry.TelemetryService.get_DefaultSession()   at Microsoft.Build.Msix.Telemetry.CreateTelemetrySession(String vsTelemetrySession)   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)   at Microsoft.Build.Msix.TelemetryOperation..ctor(String vsTelemetrySession, String eventNameSuffix)   at Microsoft.Build.Msix.Pri.WinAppSdkGenerateProjectPriFile.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)   at Microsoft.Build.Utilities.ToolTask.Execute()WRN: Assembly binding logging is turned OFF.To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.Note: There is some performance penalty associated with assembly bind failure logging.To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by Scottj1s** [comment]
@XamlTest thanks for reporting this. There have been a number of fixes in unpackaged support - does this problem still exist for you in WinAppSDK 1.4+?

**Comment by XamlTest** [comment]
@Scottj1s Tried again on VS 17.9 Preview 3 with WinAppSDK 1.4.230913002, all works well without any errors.
