### ISSUE TITLE
Compilation error when using `LayerOnMicaAltFillColorDefaultBrush` in 1.1.4

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#7711]
### Describe the bug

As per the documentation MicaAlt is available in 1.1, however when I tried to use the brush `LayerOnMicaAltFillColorDefaultBrush` as suggested [here](https://docs.microsoft.com/en-us/windows/apps/design/style/mica#app-layering-with-mica-alt) I get compilation error

### Steps to reproduce the bug

1. Try to use brush `LayerOnMicaAltFillColorDefaultBrush` on a Grid 
2. Compilation error

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by codendone** [comment]
It looks like this is a typo in the docs, which should instead say `LayerOnMicaBaseAltFillColorDefaultBrush`.

**Comment by gabbybilka** [comment]
Submitted issue on docs page: https://github.com/MicrosoftDocs/windows-dev-docs/issues/4050

Closing here.
