### ISSUE TITLE
GridView and ListView visuals are broken in 1.2 experimental

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#7712]
### Describe the bug

The visuals have gone back to looking like UWP

### Steps to reproduce the bug

1. Use GridView or ListView in 1.2 experimental 

### Expected behavior

Should look same as 1.x

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Experimental: 1.2.220727.1-experimental1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by kmgallahan** [comment]
Dupe of #7666, although it didn't mention GridView

**Comment by gabbybilka** [comment]
@codendone @ranjeshj FYI

**Comment by ranjeshj** [comment]
@kmgallahan  you are right. This is a dup of #7666
