### ISSUE TITLE
Ui icon bug

### ISSUE THREAD

**Issue by asrorbekh** [microsoft/microsoft-ui-xaml#7717]
## WinUI Toolkit Bug Report

---

**Ui bug at the end of icon:**
![image](https://user-images.githubusercontent.com/88960956/189835734-b62aa1ed-498a-4414-89b8-f0eb974fe8f6.png)

and
![image](https://user-images.githubusercontent.com/88960956/189835743-983de729-2b78-4b27-9314-a16f3022c55f.png)

**Version Info:**
xaml. 2.7 version!

**Comment by alejo4000** [comment]
Removing area-DesignToolkit and team-Design tags, this is an implementation bug with the control, not with the Figma toolkit.
