### ISSUE TITLE
Proposal: Implement an 'ItemHovered' event

### ISSUE THREAD

**Issue by ferrariofilippo** [microsoft/microsoft-ui-xaml#7724]
# Proposal: Implement an `ItemHovered` event

## Summary
An event that is invoked whenever a ListView's item is hovered.

## Rationale
* Now it's only possible to set the style of hovered items, it would be great if there was a public event that gets called whenever an item is hovered. This would allow programmers to add more on-hover-features (item preview, select-on-hover, ...)

**Comment by Jaiganeshkumaran** [comment]
PointerEntered and PointerExited can already be used.

**Comment by ferrariofilippo** [comment]
I know, but when I opened this issue I was having troubles with these events, because of their activation-area.
Now I found a way around the problem.
