### ISSUE TITLE
Focus doesn't land on the first control if we press tab from the last control

### ISSUE THREAD

**Issue by akash07k** [microsoft/microsoft-ui-xaml#7742]
### Describe the bug

    Whenever we are on the last control in a WinUI tab and press tab, we should land to the first control instantly. However, it doesn't happen in WinUI apps.
    The focus wrapping behaviour is very common throughout whole Windows platform including all sorts of apps such as WinForms, WPF, UWP Web etc.
    But we can't go to the first control in WinUI based apps if we are on the last control.
Happens even in WinUI3 Controls Gallery

### Steps to reproduce the bug

1. Create a WinUI 3 based app.
2. Add some controls to the Window.
3. Run the app,
4. Navigate to the last control via tab.
5. Once you reach to the last control, ty pressing tab and observe
6. The focus will remain on the last control itself.
7. It won't move further and won't even go back to the first control

### Expected behavior

    Whenever we are on the last control in a WinUI tab and press tab, we should land to the first control instantly. However, it doesn't happen in WinUI apps.
    The focus wrapping behaviour is very common throughout whole Windows platform including all sorts of apps such as WinForms, WPF, UWP Web etc.
    But we can't go to the first control in WinUI based apps if we are on the last control.

### Windows app type

- [ ] UWP
- [x] Win32

### Device form factor

Desktop

### Windows version

Windows 11 Insider Build 25201

**Comment by JohnPughFromSydney** [comment]
If it helps, I've noticed that pages with a CommandBar with no AppBarButtons have this problem, but if the CommandBar has buttons, the tabbing works fine

**Comment by akash07k** [comment]
I'll update to the latest SDK once and will check again.
> If it helps, I've noticed that pages with a CommandBar with no AppBarButtons have this problem, but if the CommandBar has buttons, the tabbing works fine

**Comment by JesseCol** [comment]
Thanks akash07k, I've tried this out with the latest WinUI3 Gallery and with a WinAppSDK 1.4 sample app, and the tabbing wraps around as I expect.  If you're still having a problem, please paste some Xaml that repros the problem.  Thanks!
