### ISSUE TITLE
BorderBrush does not apply to ListViewItem 

### ISSUE THREAD

**Issue by pluto-dev** [microsoft/microsoft-ui-xaml#7751]
### Describe the bug

It's currently not possible to change the BorderBrush for a ListViewItem

### Steps to reproduce the bug

1. Create a new project
2. Add a simple ListView with ListViewItems
3. Set the BorderThickness to 1 and change the Color of the BorderBrush of the ListViewItem

### Expected behavior

I expected to be able to change the color of a ListViewItem

### Screenshots

![unknown](https://user-images.githubusercontent.com/38720155/191600843-543fbddf-51f4-4086-b077-8136080500bf.png)

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by bogdan-patraucean** [comment]
#6595 there is already an issue for this

**Comment by pluto-dev** [comment]
> #6595 there is already an issue for this

I disagree. The other issue is marked as WinUi3 issue. It would be a shame if they only fix it in WinUi3 and not in WinUi2.

**Comment by pluto-dev** [comment]
Is it fixed?

**Comment by mdtauk** [comment]
The ListViewItem Presenter does not have BorderBrush, Thickness, properties.

**Comment by JJBrychell** [comment]
Since there is a separate WinUI3 issue (#6595) and  WinUI2 has entered maintenance mode, this issue is being closed.

**Comment by Prem-Kumar-Shanmugam** [comment]
is it fixed ?
