### ISSUE TITLE
AppBarButton icon is not centered by default

### ISSUE THREAD

**Issue by bogdan-patraucean** [microsoft/microsoft-ui-xaml#7761]
### Describe the bug

If you try to set an icon for the AppBarButton, that icon will not be centered by default.

There is a workaround for this, setting **LabelPosition="Collapsed"**. On the other hand, setting **VerticalAlignment="Center"** on the FontIcon element itself, does not work.

### Steps to reproduce the bug

Just use an AppBarButton like this:

```
<AppBarButton>
    <AppBarButton.Icon>
       <FontIcon VerticalAlignment="Center" Glyph="&#xe713;" FontSize="18"/>
    </AppBarButton.Icon>
</AppBarButton>
```

### Expected behavior

The code below should center the icon by default:

```
<AppBarButton>
    <AppBarButton.Icon>
       <FontIcon Glyph="&#xe713;" FontSize="18"/>
    </AppBarButton.Icon>
</AppBarButton>
```

### Screenshots

![image](https://user-images.githubusercontent.com/26826125/192149349-63a81744-c82b-4b5e-a785-43e2ce46424a.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by bogdan-patraucean** [comment]
#6945 it might be related to this issue

**Comment by bogdan-patraucean** [comment]
UP. This issue should not be part of https://github.com/microsoft/microsoft-ui-xaml/discussions/8638.

**Comment by DmitriyKomin** [comment]
Hey @bogdan-patraucean, thank you for reporting the issue. It appears that the case you describe leaves room for the label, which is empty. Setting  LabelPosition="Collapsed" is an appropriate way to remove the label's layout slot. Please comment here if you have any remaining concerns.

**Comment by bogdan-patraucean** [comment]
@DmitriyKomin thanks a lot for the update. I would expect there is no space occupied by the label if the label is empty. To me it's a much intuitive development experience.
