### ISSUE TITLE
Windows Capabilities in appxmanifest not properly used by building .msix [MAUI]

### ISSUE THREAD

**Issue by Redth** [microsoft/microsoft-ui-xaml#7766]
### Description

**Originally from: https://github.com/dotnet/maui/issues/10287**

When the `Capability` `runFullTrust` is replaced with something else (for instance `removableStorage`) and the `msix` file is build, the following is shown during the installation:
![image](https://user-images.githubusercontent.com/37712964/191975535-84ea508f-eccd-4280-a8c1-922eda2b8b39.png)
(The msix file can be found here [MauiIssue-WindowsCapabilities Action Artefact](https://github.com/Tardigrade42/MauiIssue-WindowsCapabilities/actions/runs/3112994129))
As you see, the `runFullTrust` was not removed from the `msix` which is strange.

### Link to public reproduction project repository

https://github.com/Tardigrade42/MauiIssue-WindowsCapabilities

### Version with bug

6.0.486 (current)

### Steps to reproduce the bug

1. Create a Maui-App from the template
2. Go to "Platforms > Windows > Package.appxmanifest"
3. Change:
```XML
<Capabilities>
   <rescap:Capability Name="runFullTrust" />
</Capabilities>
```
to
```XML
<Capabilities>
   <uap:Capability Name="removableStorage" />
</Capabilities>
```
4. Build app with `dotnet publish`
5. Open the MSIX file on your computer

### Expected behavior

`runFullTrust` was not removed from the `msix`

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by evelynwu-msft** [comment]
Tracked internally as http://aka.ms/41603067

**Comment by Tardigrade42** [comment]
Hi,
since I am waiting for a solution of this issue for a while now, I wanted to ask if there is progress with this case or if there is a workaround?

**Comment by evelynwu-msft** [comment]
@Tardigrade42 Unfortunately there is no workaround. However, a fix will be included in the 1.3 release and we are aiming to bring it into an upcoming 1.2 servicing release as well.

**Comment by Tardigrade42** [comment]
Thank you very much :)
I have no idea how often you are building releases. When will this release be available on Visual Studio?

**Comment by evelynwu-msft** [comment]
@Tardigrade42 We're aiming to include this in the January 2023 1.2 servicing update.

**Comment by Tardigrade42** [comment]
That sounds great🙂. Thank you!

**Comment by evelynwu-msft** [comment]
[Windows App SDK 1.2.3](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-123-12230118102) shipped today with the fix for this issue.
