### ISSUE TITLE
ScrollViewer - LayoutCycleException

### ISSUE THREAD

**Issue by aleibhardt** [microsoft/microsoft-ui-xaml#7768]
### Describe the bug

Since updating to the latest WinUI (we are currently on WinUI 2.8.1), we have been seeing an increase in LayoutCycleException in our logging. 
When these issues hit, the app becomes completely unresponsive and we have to tell the user to restart the application. These are extremely critical issues that reflect very poorly on our application.

The issue appears to be around being at the rightmost extent of the scroll viewer while at specific zoom levels. The issue also appears to be very specific to certain screen resolutions and DPI settings. 

I have been able to get a minimal reproduction through a sample application. From this reproduction I have been able to nail down the version where the issue started reproducing:
https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.6.0-prerelease.210623001

I have been able to work around the bug for now by using the scrollviewer style from the OS and not from the WinUI controls library. For now, this is the workaround we are going with, however I believe this issue should still be fixed. Maybe it's related to this issue as well. https://github.com/microsoft/microsoft-ui-xaml/issues/7696

### Steps to reproduce the bug

I have been able to reproduce this reliably with the following screen resolution settings:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/19656543/192657090-7d4f00d0-0cbf-4d19-8644-d870d123cfce.png">

Install this sample application:
[LayoutCycleTests.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9660251/LayoutCycleTests.zip)

Run the application.

A second after the app launches, it should go to a zoom level and horizontal offset that is known to crash the application. 

If this doesn't work, try to zoom in and out while at the right most extent of the scrollviewer on the first page in the flipview. 

As an aside, these LayoutCycleExceptions are very hard to diagnose in our application. The exception has no useful information in it, and the only way to get to the bottom of these issues is hope that you can reproduce the issue and then bang against the code until you find out what is causing the issue. 

### Expected behavior

The app doesn't crash.

Actual Behavior:
The app throws a layout cycle exception, and crashes.

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by aleibhardt** [comment]
Has there been any update on this. We are seeing a fresh hit of xaml layout cycle exceptions in our app, and they are next to impossible to debug on our end.

**Comment by danmartinez** [comment]
We're experiencing this same issue -- specifically, a layout cycle exception being thrown when scrolling to the right edge under certain display scales. For example, using the recommended settings of 2880x1920 at 200% on a Surface Pro 8 results in no layout exceptions, but the same resolution at 225% does.

**Comment by Lightczx** [comment]
Setting root containing element's `UseLayoutRounding` to false may help reduce the failure time.

**Comment by Abe-Froman** [comment]
Just left a comment on #3989 reporting the same thing, though that issue is staler than this one.

`UseLayoutRounding` on the root element didn't help in my case, but I did just go through & remove every single `ScrollViewer` from the app (no longer getting the issue) and adding them back in one-by-one and now know exactly which one causes the issue. Still don't know why though...

Running latest WinAppSDK (1.4.231008000) though it was happening with 1.4.230913002 as well.

**Comment by codendone** [comment]
A fix for this issue has just been completed for WinAppSDK 1.5 (same fix as for #6218). This had already been partially improved in WinAppSDK and also partially fixed in Windows 11 for system XAML (/WinUI2).

**Comment by yaira2** [comment]
@codendone were the improvements for WinUI 2 released yet?

**Comment by codendone** [comment]
@yaira2 Yes, it looks like the partial improvements were released in a Windows 11 update sometime in 2022. If you still repro the issue in WinUI2 on an updated Windows 11 build, then it would seem those weren't sufficient for your scenario.

A workaround is possible for the primary additional issue here: Set “UseLayoutRounding = false” on the “VerticalPanningRoot” element in ScrollBars. (Or maybe the "HorizontalPanningRoot" if you have horizontal scrollbars.)

One option is to restyle ScrollBar (such as by copying the default ScrollBar style) and set this property on the element in style. The default `<Style>` block for ScrollBar is rather large, so this might not be the most desirable option.

Another option is to run code like this to search for the element under the subtree of the given element and set the property on it:
```cs
        private void DisableLayoutRoundingOnVerticalPanningRoots(FrameworkElement element)
        {
            if (element == null)
            {
                return;
            }

            if (element.Name == "VerticalPanningRoot")
            {
                element.UseLayoutRounding = false;
            }

            for (int i = 0; i < VisualTreeHelper.GetChildrenCount(element); i++)
            {
                DisableLayoutRoundingOnVerticalPanningRoots(VisualTreeHelper.GetChild(element, i) as FrameworkElement);
            }
        }
```

**Comment by MaxWellHays** [comment]
> Another option is to run code like this to search for the element under the subtree of the given element and set the property on it

@codendone, when do you recommend executing this code which sets `UseLayoutRounding = false` for `VerticalPanningRoot`?
I have problem with not having `VerticalPanningRoot` in visual tree to change it's `UseLayoutRounding` property.
I use `ListView`, which uses `ScrollViewer` in its default template, which uses `ScrollBar { Name: "VerticalScrollBar" }`, which has `VerticalPanningRoot` element in its template.

I tried to unsure that all elements are loaded by the time when I search for element, but it still doesn't work unfortunately, when `ScrollBar.Loaded` event happens, `ScrollBar` still doesn't have any visual tree children. I think it happens because `Load` event is fired before `OnTemplateApplied` has been executed. I don't know any other way to find out when `VerticalPanningRoot` will be added to the tree (there is no event which fires after `OnTemplateApplied`).

Here is my code which I tried to use to set `element.UseLayoutRounding = false`:

```
private void OnListViewLoaded(object sender, RoutedEventArgs e)
{
    var scrollViewer = ListView.GetAllVisualTreeChildren().OfType<ScrollViewer>().FirstOrDefault();
    if (scrollViewer != null)
    {
        if (scrollViewer.IsLoaded)
        {
            OnScrollViewerLoaded(scrollViewer, e);
        }
        else
        {
            scrollViewer.Loaded += OnScrollViewerLoaded;
        }
    }
    else
    {
        Log.Warn($"{nameof(ScrollViewer)} haven't been found in {nameof(ListView)} on {nameof(OnListViewLoaded)}");
    }
}

private void OnScrollViewerLoaded(object sender, RoutedEventArgs e)
{
    var scrollViewer = (ScrollViewer)sender;
    var verticalScrollBar = scrollViewer.GetAllVisualTreeChildren()
        .OfType<ScrollBar>()
        .FirstOrDefault(bar => bar.Name == "VerticalScrollBar");
    if (verticalScrollBar != null)
    {
        if (verticalScrollBar.IsLoaded)
        {
            OnVerticalScrollBarLoaded(verticalScrollBar, e);
        }
        else
        {
            verticalScrollBar.Loaded += OnVerticalScrollBarLoaded;
        }
    }
    else
    {
        Log.Warn($"{nameof(verticalScrollBar)} haven't been found in {nameof(ScrollViewer)} on {nameof(OnScrollViewerLoaded)}");
    }
}

private void OnVerticalScrollBarLoaded(object sender, RoutedEventArgs e)
{
    var verticalScrollBar = (ScrollBar)sender;
    var childrenCount = VisualTreeHelper.GetChildrenCount(verticalScrollBar);
    var verticalPanningRoot = verticalScrollBar
        .GetAllVisualTreeChildren()
        .OfType<FrameworkElement>()
        .FirstOrDefault(fe => fe.Name == "VerticalPanningRoot");
    if (verticalPanningRoot != null)
    {
        verticalPanningRoot.UseLayoutRounding = false;
    }
    else
    {
        Log.Warn($"{nameof(verticalPanningRoot)} haven't been found in {nameof(ScrollBar)} on {nameof(OnVerticalScrollBarLoaded)}");
    }
}
```

Here is what I see during debugging:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/1606000/f1f9c4ca-b07c-430a-8d68-50ae0957e90f)

**Comment by MaxWellHays** [comment]
I think I found a solution, I can call `element.ApplyTemplate` after it loaded in case if `VisualTreeHelper.GetChildrenCount(verticalScrollBar) == 0`, it works then.

Here is my fixed solution:
```
private void OnVerticalScrollBarLoaded(object sender, RoutedEventArgs e)
{
    var verticalScrollBar = (ScrollBar)sender;
    if (VisualTreeHelper.GetChildrenCount(verticalScrollBar) == 0)
    {
        verticalScrollBar.ApplyTemplate();
    }

    var verticalPanningRoot = verticalScrollBar
        .GetAllVisualTreeChildren()
        .OfType<FrameworkElement>()
        .FirstOrDefault(fe => fe.Name == "VerticalPanningRoot");
    if (verticalPanningRoot != null)
    {
        verticalPanningRoot.UseLayoutRounding = false;
    }
    else
    {
        Log.Warn($"{nameof(verticalPanningRoot)} haven't been found in {nameof(ScrollBar)} on {nameof(OnVerticalScrollBarLoaded)}");
    }
}
```

**Comment by aquinn39** [comment]
This issue still seems to exist on WinUI 2.8.7 on Windows 11 23H2. I don't know what the WinUI ScrollVIewer does to break it, but using the following code to replace it with the default UWP style fixes the issue. Seems to depend on the height of the content inside the viewer. I guess it depends on what horizontal value the ScrollViewer lands on when it hits the bottom of the scrollable area or something.

 Kind of disappointing that such a bug exists; this is why people don't want to use WinUI - something as simple as scrolling should not crash an application and such a bug should definitely not hang around for years. Half the Windows 11 OS uses WinUI 2 as well, all of which most likely have this bug...

```
<ScrollViewer.Style>
   <Style TargetType="ScrollViewer"/>
</ScrollViewer.Style>
```

**Comment by aquinn39** [comment]
I am also curious as to what the WinUI 2 ScrollViewer style even does as it still seems to look and behave the same as the UWP one.
