### ISSUE TITLE
Proposal: Allow composition to scRGB/FP16 to allow HDR UI elements

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/microsoft-ui-xaml#777]
# Proposal: Allow composition to scRGB/FP16 to allow HDR UI elements 

## Summary

If an application combines a Direct3D SwapChain with HDR support and UI that represents colours which are shown in the SwapChain, it would be good if the UI was capable of showing the same colours as in the SwapChain.

## Rationale

* Without HDR support, developers would either have to choose between being unable to display HDR colours in the UI, or having to implement custom controls on top of a Direct3D SwapChain.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to enable HDR support | Must |
| This proposal will allow end users to view HDR colours in the UI | Must |
| This proposal will allow developers to query whether HDR support is enabled | Must |

## Important Notes

Dragging a window between monitors can enable or disable HDR, depending on a device's capabilities, so some kind of notification within the application would be useful, as the UI would need to update to reflect the lack of HDR support.
I would like this considered for the WinUI 3.0 timeframe. 

## Open Questions

* Is there a downside to always enabling HDR support (FP16 scanout) if a device supports it?

**Comment by jevansaks** [comment]
Sounds similar to #67 ?

**Comment by MarkIngramUK** [comment]
Yikes. Not sure how I missed that?! I'll contribute to that proposal instead...
