### ISSUE TITLE
Application crash at launch

### ISSUE THREAD

**Issue by dragonofmercy** [microsoft/microsoft-ui-xaml#7770]
### Describe the bug

Each time I run my application it's crash without error except in the event viewer, see below.  

```
Faulting application name: ImageViewer.exe, version: 1.22.9.28, time stamp: 0x62fff1bf
Faulting module name: Microsoft.UI.Xaml.dll, version: 3.0.0.2209, time stamp: 0xd30bb7f9
Exception code: 0xc000027b
Fault offset: 0x0000000000327738
Faulting process id: 0x0x1CC8
Faulting application start time: 0x0x1D8D335AF248928
Faulting application path:  %userpath%\AppData\Local\Dragon Industries\Image Viewer\ImageViewer.exe
Faulting module path: %userpath%\AppData\Local\Dragon Industries\Image Viewer\Microsoft.UI.Xaml.dll
Report Id: 81b353e1-5b94-48c5-9361-8e3e8e6ecdef
Faulting package full name: 
Faulting package-relative application ID: 
```

I have installed all required package:

1.  .NET 6.0 Desktop Runtime (v6.0.9)
2. Windows AppRuntime 1.1.5

Tested both with packaged and un-packaged build

### Steps to reproduce the bug

You can try to install my application on your computer or see my code on my project  
https://github.com/dragonofmercy/image-viewer

### Expected behavior

My application start normally

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by dragonofmercy** [comment]
I forgot to send the crashdump  
[ImageViewer.exe.10732.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9665150/ImageViewer.exe.10732.zip)

**Comment by codendone** [comment]
Thanks for attaching the dump. Unfortunately, the dump is missing the stowed exception memory to show the failure callstack(s). If you attach a full memory dump of the process, I'll get the stacks from that. Or you can try to dump the stowed exceptions yourself using the info in the [debugging_crashes.md doc](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/debugging_crashes.md#stowed-exception-crashes-exception-code-0xc000027b), particularly the steps in the second paragraph of the "Stowed Exception crashes" section.

**Comment by dragonofmercy** [comment]
Thanks for your answer, I will send you that but unfortunally I cannot access to the machine until Monday. I will do that as quick as possible :-)

**Comment by dragonofmercy** [comment]
KERNELBASE!RaiseFailFastException+0x152:
00007ff9`5fe75bd2 0f1f440000      nop     dword ptr [rax+rax]

0:000> !pde.dse
Stowed Exception Array @ 0x0000025d048813a0

Stowed Exception #1 @ 0x0000025d04a69aa8
	0x80004003 (FACILITY_NULL - Default): E_POINTER - Pointer that is not valid

	Stack	 : 0x25d7c662ee0

Stowed Exception #2 @ 0x0000025d048ab7d0
	0x80004003 (FACILITY_NULL - Default): E_POINTER - Pointer that is not valid

	Stack	 : 0x25d048a9ae8

**Comment by dragonofmercy** [comment]
Ok I find something with windbg it's my code issue, sorry for the ticket, I close it
