### ISSUE TITLE
Horizontal scrolling with touchpad doesn't work in WebView2

### ISSUE THREAD

**Issue by aquinn39** [microsoft/microsoft-ui-xaml#7772]
### Describe the bug

Trying to scroll a WebView2 web page horizontally with a touchpad does not work - it just scrolls vertically instead. Horizontal scrolling with touchpad works fine in Microsoft Edge so it should work in WebView2. Also, I tested horizontal scrolling with touch in WebView2 and that works fine.

### Steps to reproduce the bug

1. Add a WebView2 to a WinUI app
2. Set the source of the WebView2
3. Build and run the app, then attempt to scroll the web page horizontally with a touchpad

### Expected behavior

The web page should scroll horizontally like in Microsoft Edge.

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Looks like WebView2::HandlePointerWheelChanged() is failing to check if the wheel event is PointerPoint.Properties.IsHorizontalMouseWheel and just handles all of them as vertical wheel.

**Comment by Iucapad** [comment]
I encounter this issue in a UWP application project using a WebView2 for it's main UI.
I hope it gets fixed at some point🤞

**Comment by vagisha-nidhi195** [comment]
@codendone  Is there an update on this issue?

**Comment by Iucapad** [comment]
Good job, thanks @tjamesmac !

**Comment by bpulliam** [comment]
Fixed in 1.3.2

**Comment by aquinn39** [comment]
Does anyone know if the fix is coming to WinUI 2?

**Comment by codendone** [comment]
@aquinn39 Yes, a release of WinUI 2 is planned soon containing this fix.
