### ISSUE TITLE
[A11y] AppBarButton's MenuFlyout not getting focus when in More button

### ISSUE THREAD

**Issue by alcail** [microsoft/microsoft-ui-xaml#7774]
### Describe the bug

Focus is lost when opening a MenuFlyout of an AppBarButton when on the More button.

### Steps to reproduce the bug

1. Have a CommandBar with AppBarButton defined with a MenuFlyout with at least one MenuFlyoutItem ("Sort" button for example).
2. Press Tab key till your focus is on the "Sort" button
3. Press Enter key
4. Focus is on the first MenuFlyoutItem
5. Now, minimize your app so the "Sort" button is in the "More" button
6. Press Tab key till your focus is on the "More" button
7. Press Enter key
8. Press Down arrow key till your focus is on the "Sort" button
9. Press Enter key.
10. Focus is lost and thus not on the first MenuFlyoutItem as supposed to be

### Expected behavior

Step 10 should see focus being on the he first MenuFlyoutItem of "Sort" button

### Screenshots

Actual behaviour: 
![image](https://user-images.githubusercontent.com/82416644/193326429-ca384f98-449d-4a41-acb6-c206a27eed78.png)

Expected behaviour: 
![image](https://user-images.githubusercontent.com/82416644/193327185-6cb34602-95b8-45b1-a4c0-bc3cb799382f.png)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by alcail** [comment]
I found a work around by adding Opened event handler on each of our AppBarButton Flyout

![image](https://user-images.githubusercontent.com/82416644/194177001-08266e70-7461-4ec5-9858-ed7801ea9107.png)

with
![image](https://user-images.githubusercontent.com/82416644/194177142-ca4e9f22-368a-4371-80f2-af00aca2808c.png)

**Comment by alcail** [comment]
Any update?

**Comment by JesseCol** [comment]
Hi, can you please paste the Xaml you're using in the repro?  Thanks!

**Comment by JesseCol** [comment]
Please holler if you get a chance to post a repro.  For now I'm closing it out.  Thanks!
