### ISSUE TITLE
TemplateBinding in VisualState setter doesn't work

### ISSUE THREAD

**Issue by FrozDark** [microsoft/microsoft-ui-xaml#7779]
### Describe the bug

When you set TemplateBinding in VisualState setters it has no effect

### Steps to reproduce the bug

1. Create style with VisualStateGroups
2. Set any VisualState (PointerOver for instance)
3. Use TemplateBinding
4. Check the resuls moving to that visual state of a control

### Expected behavior

Should be working

### NuGet package version

1.2.220727.1-experimental1

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by evelynwu-msft** [comment]
@FrozDark Could you provide a minimal repro project that includes the XAML markup that you're trying to make work? There's ambiguity in your description and I want to ensure that I'm investigating the correct thing.

**Comment by FrozDark** [comment]
> @FrozDark Could you provide a minimal repro project that includes the XAML markup that you're trying to make work? There's ambiguity in your description and I want to ensure that I'm investigating the correct thing.

Sorry for a very late reply. I couldn't create a WinUI template

In short the issue here:
```
<VisualStateGroup x:Name="WildStates">
    <VisualState x:Name="NoWild" />
    <VisualState x:Name="Wild">
        <VisualState.Setters>
            <Setter Target="PART_Content.Padding" Value="{TemplateBinding Padding}" />
        </VisualState.Setters>
    </VisualState>
</VisualStateGroup>
```

As you can see there is that TemplateBinding placed inside a VisualState.Setters doesn't work

**Comment by kmgallahan** [comment]
Although the documentation is lacking here, Stackoverflow indicates that TemplateBinding can only be used in a ControlTemplate's **visual tree**, which means it would not work in a trigger like this (by undocumented design).

`Generic.xaml` has not instances of TemplateBinding being used in a visual state trigger.
