### ISSUE TITLE
ButtonRevealStyle doesn't have highlight effect with custom RevealBackgroundBrush

### ISSUE THREAD

**Issue by AlKau** [microsoft/microsoft-ui-xaml#778]
**Describe the bug**
When nuget Microsoft.UI.Xaml is installed, custom **RevealBackgroundBrush** doesn't have highlight effect in Button with **ButtonRevealStyle** style. However it works properly without nuget.

**Steps to reproduce the bug**

1. Install nuget Microsoft.UI.Xaml 2.1.190405004.2
2. Add to resource `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />`
3. Create Button with style **ButtonRevealStyle**
4. Redefine **RevealBackgroundBrush** brushes from ButtonRevealStyle x:Key="**ButtonRevealBackgroundPointerOver**" and x:Key="**ButtonRevealBackgroundPressed**"

**Screenshots**

ButtonRevealStyle with Custom Theme (Microsoft.UI.Xaml.Controls nuget isn't installed):
![RevealButton-OK](https://user-images.githubusercontent.com/22179504/58637333-f841af80-82fa-11e9-94f1-ab998c2dbcc8.png)

ButtonRevealStyle with Default Theme (Microsoft.UI.Xaml.Controls is installed):
![RevealButton-MUX-OK](https://user-images.githubusercontent.com/22179504/58637341-fc6dcd00-82fa-11e9-8620-50c93be72406.png)

ButtonRevealStyle with Custom Theme (Microsoft.UI.Xaml.Controls is installed):
![RevealButton-MUX-Wrong](https://user-images.githubusercontent.com/22179504/58637347-fe379080-82fa-11e9-9a18-75dd10a25a32.png)

**XAML Code**

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>

        <Grid Grid.Row="0">
            <Button x:Name="Correct"
                    Height="400"
                    Style="{StaticResource ButtonRevealStyle}"
                    Content="ButtonRevealStyle with Custom Theme"
                    ToolTipService.ToolTip="Ok"
                    HorizontalAlignment="Center"
                    VerticalAlignment="Center">
                <Button.Resources>
                    <ResourceDictionary>
                        <ResourceDictionary.ThemeDictionaries>
                            <ResourceDictionary x:Key="Default">
                                <RevealBackgroundBrush x:Key="ButtonRevealBackground"
                                                       TargetTheme="Dark"
                                                       Color="DarkGreen"
                                                       FallbackColor="Red" />

                                <RevealBackgroundBrush x:Key="ButtonRevealBackgroundPointerOver"
                                                       TargetTheme="Dark"
                                                       Color="DarkGreen"
                                                       FallbackColor="Red" />

                                <RevealBackgroundBrush x:Key="ButtonRevealBackgroundPressed"
                                                       TargetTheme="Dark"
                                                       Color="DarkGreen"
                                                       FallbackColor="Red" />

                                <RevealBorderBrush x:Key="ButtonRevealBorderBrushPointerOver"
                                                   TargetTheme="Dark"
                                                   Color="DarkGreen"
                                                   FallbackColor="Red" />

                                <RevealBorderBrush x:Key="ButtonRevealBorderBrushPressed"
                                                   TargetTheme="Dark"
                                                   Color="DarkGreen"
                                                   FallbackColor="Red" />
                            </ResourceDictionary>
                            <ResourceDictionary x:Key="Light" />

                        </ResourceDictionary.ThemeDictionaries>
                    </ResourceDictionary>
                </Button.Resources>
            </Button>

        </Grid>

        <Grid Grid.Row="1">
            <Grid.Resources>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
            </Grid.Resources>

            
            <Button x:Name="Incorrect"
                    Height="400"
                    Style="{StaticResource ButtonRevealStyle}"
                    Content="Microsoft.UI.Xaml.Controls.ButtonRevealStyle with Custom Theme (it doesn't work properly)"
                    ToolTipService.ToolTip="RevealBackgroundBrush doesn't have highlight effect, when the pointer has PointerOver or Pressed state"
                    HorizontalAlignment="Center"
                    VerticalAlignment="Center">
                <Button.Resources>
                    <ResourceDictionary>
                        <ResourceDictionary.ThemeDictionaries>
                            <ResourceDictionary x:Key="Default">
                                <RevealBackgroundBrush x:Key="ButtonRevealBackground"
                                                       TargetTheme="Dark"
                                                       Color="DarkGreen"
                                                       FallbackColor="Red" />

                                <RevealBackgroundBrush x:Key="ButtonRevealBackgroundPointerOver"
                                                       TargetTheme="Dark"
                                                       Color="DarkGreen"
                                                       FallbackColor="Red" />

                                <RevealBackgroundBrush x:Key="ButtonRevealBackgroundPressed"
                                                       TargetTheme="Dark"
                                                       Color="DarkGreen"
                                                       FallbackColor="Red" />

                                <RevealBorderBrush x:Key="ButtonRevealBorderBrushPointerOver"
                                                   TargetTheme="Dark"
                                                   Color="DarkGreen"
                                                   FallbackColor="Red" />

                                <RevealBorderBrush x:Key="ButtonRevealBorderBrushPressed"
                                                   TargetTheme="Dark"
                                                   Color="DarkGreen"
                                                   FallbackColor="Red" />
                            </ResourceDictionary>
                            <ResourceDictionary x:Key="Light" />

                        </ResourceDictionary.ThemeDictionaries>
                    </ResourceDictionary>
                </Button.Resources>
            </Button>

        </Grid>
    </Grid>

[Sample project](https://github.com/AlKau/UWP-Samples/tree/master/RevealButton)

**Links**
This may be related to #105 and #559.

**Expected behavior**
The reveal highlight effect should be visible for a custom RevealBackgroundBrush with Microsoft.UI.Xaml nuget.

**Version Info**

OS: Windows 10 pro 1809 (17763.503)
NuGet package version: Microsoft.UI.Xaml 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |            Yes              |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional**

Custom **RevealBorderBrush** works properly.

**Comment by jevansaks** [comment]
If you're using WinUI then you will need to create the WinUI versions of the Reveal brushes. In your code, try importing the "using:Microsoft.UI.Xaml.Media" namespace and then using `muxm:RevealBackgroundBrush`, etc in your markup. That should get the correct pairing of brushes and lights.

**Comment by niels9001** [comment]
@jevansaks Should we define all Reveal brushes in e.g. App.xaml referencing using the <muxm> namespace?

**Comment by niels9001** [comment]
> @niels9001 Are you asking how to use the brush from the WInUI Namaespace ? Something like this should work
> 
> ```
> <Page
>  ....
>     xmlns:media="using:Microsoft.UI.Xaml.Media"
> >
>  ... media:RevealBackgroundBrush ..
> ```

`<Page
...
 xmlns:media="using:Microsoft.UI.Xaml.Media">
<Page.Resources>
<media:RevealBackgroundBrush x:Key="ButtonRevealBackground" />
<media:RevealBackgroundBrush x:Key="ButtonRevealBackgroundPointerOver" />
....
</Page.Resources`

Like this? There's quite a lot of them actually :-). We'd also need to check what the default values are or will that fall back to the default values if we use the code stated above?

**Comment by ranjeshj** [comment]
@niels9001  If you want to share them across the app, you can do the same in Application.Resources in App.xaml.  I am a little bit confused on what you need regarding fallback. Are you asking if there will be a default value available if Reveal is not available in a down-level OS release ?

**Comment by niels9001** [comment]
> @niels9001  If you want to share them across the app, you can do the same in Application.Resources in App.xaml.  I am a little bit confused on what you need regarding fallback. Are you asking if there will be a default value available if Reveal is not available in a down-level OS release ?

My question was about my sample XAML: should that work or do we need to add the actual colors for each brush as well (like how they are defined in generic.xaml (or themes.xaml?)?

That means that if, in theory, we have a UI with all controls, we'd need to add a lot of brushes in the Application.Resources. Would be nice to have that list copy-and-paste ready (with the right namespace) instead of going into each control style to dig up the right RevealBrushes.

I'm happy to do that (so we can put it in the Docs?) if I can get it to work :)!

Please let me know!

**Comment by ranjeshj** [comment]
I'm still wondering what you are trying to achieve. Are you trying to add reveal on all the built in controls ? Could you use the named styles to achieve that ? 

https://docs.microsoft.com/en-us/windows/uwp/design/style/reveal#enabling-reveal-on-other-controls

If you want to change the defaults to the reveal styles for the entire app, you can do that as well by building on top of these named styles.

**Comment by niels9001** [comment]
I'm trying to make Reveal work for a listview and a normal button in a Xaml Island.

My point was that I'd need to define 6 brushes for each control (Normal, PointerOver, Pressed for both the background and borderbrush).

Can you confirm that the code I posted above should work? Because somehow it isn't for me :(.

**Comment by ranjeshj** [comment]
@kikisaints What is the best option here ?
