### ISSUE TITLE
WinUI3 Window Icon from EmbeddedResource / Resource

### ISSUE THREAD

**Issue by dojo90** [microsoft/microsoft-ui-xaml#7782]
Hello,

Is it possible to load / set the window icon from an `EmbeddedResource` or `Resource`?

Unfortunately, the solution described here (https://github.com/microsoft/microsoft-ui-xaml/issues/4056#issuecomment-1118094495) only works if the file was physically stored on the file system. I would like to avoid that!

**Comment by Balkoth** [comment]
Set "Build Action" of the icon file to "Embedded resource".

```cs
// Load the icon for the application from the embedded resources. Replace [FILENAME] with real filename.
Icon _icon = new Icon(typeof(App).Assembly.GetManifestResourceStream("ClientAdminTools.Properties.Resources.[FILENAME].ico")!);

// Get AppWindow and call SetIcon like this:
appWindow.SetIcon(Win32Interop.GetIconIdFromIcon(_icon.Handle));
```

Remember to keep a reference to _icon around, so it does not get disposed.

**Comment by DarranRowe** [comment]
If you embed the resource as a Windows native resource, you can use LoadIcon or LoadImage from the Windows API. Since those return a HICON, you can use the return in GetIconIdFromIcon.

**Comment by dojo90** [comment]
> Set "Build Action" of the icon file to "Embedded resource".
> 
> ```cs
> // Load the icon for the application from the embedded resources. Replace [FILENAME] with real filename.
> Icon _icon = new Icon(typeof(App).Assembly.GetManifestResourceStream("ClientAdminTools.Properties.Resources.[FILENAME].ico")!);
> 
> // Get AppWindow and call SetIcon like this:
> appWindow.SetIcon(Win32Interop.GetIconIdFromIcon(_icon.Handle));
> ```
> 
> Remember to keep a reference to _icon around, so it does not get disposed.

Thank you very much for your solution!



> If you embed the resource as a Windows native resource, you can use LoadIcon or LoadImage from the Windows API. Since those return a HICON, you can use the return in GetIconIdFromIcon.

Could you post an example? Unfortunately, the icon is not set. Neither as a `Resource` nor as a `PRIResource`.

**Comment by dojo90** [comment]
Ah then I misunderstood your original answer. Thanks for posting your solution for the sake of completeness. 🙂👍
