### ISSUE TITLE
Project references not resloved in a WinUI 3 C++ project

### ISSUE THREAD

**Issue by Ruyi-Wonton** [microsoft/microsoft-ui-xaml#7789]
### Describe the bug

In WinUI3 **C++** project, why is there exclamation mark in the Reference, prompting "..... references could not be resolved"

### Steps to reproduce the bug

 1.	Create a new project using the template Blank App, Packaged (WinUI 3 in Desktop) – C++
 2.	Build and run the project successfully
 3.	Close the project 
 4.	Reopen the project

### Expected behavior

Ability to link to related files normally, displaying the correct file attributes.

### Screenshots

![InkedMicrosoftTeams-image (2)_LI](https://user-images.githubusercontent.com/93764466/192221184-38796246-396c-43ee-9949-c7aa824c505c.jpg)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by pratikone** [comment]
i can repro it. it is still happening.
