### ISSUE TITLE
In-App acrylic doesn't work over `WebView2`

### ISSUE THREAD

**Issue by grork** [microsoft/microsoft-ui-xaml#7796]
### Describe the bug

When you layer In-App acrylic over `WebView2`, it doesn't apply any acrylic effect to that content. When layered with other, non-`WebView2` content, it behaves as expected. This holds true when you layer non-`WebView2` content simultaneously as with `WebView2` content.

### Steps to reproduce the bug

1. Create a new Packaged App using the Windows SDK 1.1 called `SampleSDKApp`
2. Paste the following code into `MainWindow.xaml` + comment out the button handler in `MainWindow.xaml.cs`
3. Run it and scroll over the web content or the kitten

```
<Window x:Class="SampleSDKApp.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:controls="using:Microsoft.UI.Xaml.Controls">
    <Grid>
        <controls:ScrollViewer>
            <Image Source="http://placekitten.com/900/2000"
                   Width="900" />
        </controls:ScrollViewer>
        <controls:WebView2 HorizontalAlignment="Stretch"
                           VerticalAlignment="Stretch"
                           Source="https://www.bing.com"
                           Width="300" />
        <Rectangle HorizontalAlignment="Stretch"
                   VerticalAlignment="Top"
                   Height="150">
            <Rectangle.Fill>
                <AcrylicBrush TintOpacity="0.1"
                              TintLuminosityOpacity="0.1"
                              TintColor="Red"
                              FallbackColor="Red" />
            </Rectangle.Fill>
        </Rectangle>
    </Grid>
</Window>
```

### Expected behavior

Acrylic works!

### Screenshots

![Screenshot 2022-10-07 140335](https://user-images.githubusercontent.com/1811056/194652233-a4c174aa-9e8b-4574-a6af-143deab6d638.png)

### NuGet package version

Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 22000.1042

**Comment by codendone** [comment]
AcrylicBrush in WinUI 3 / WinAppSDK does not support blending and blurring "external" content, which is SwapChainPanel, MediaPlayerElement, or WebView2 content (all of these are composed by DWM.exe rather than as part of WinAppSDK rendering).

The plan for a future release is to allow popups/menus to use DesktopAcrylicController (along with a simple property to have the platform use DesktopAcrylicController), which will allow these popups/menus to have acrylic which is rendered by DWM.exe and can blend external content.

**Comment by grork** [comment]
You specifically mention popups will be addressed – I assume thats intentionally excluding the specific scenario in this repro, which isn't a popup or a menu; it's just an overlay. If so, is that planned for the future or just 'Maybe. One day!'

**Comment by codendone** [comment]
There are currently no designs to support acrylic over external content other than with a popup.

**Comment by grork** [comment]
Fixing closed status
