### ISSUE TITLE
WinUI 3 missing architectures for store deploy

### ISSUE THREAD

**Issue by lk-code** [microsoft/microsoft-ui-xaml#7800]
### Describe the bug

I have created a relatively simple app in WinUI3 and now want to upload it to the store. Actually should be created x86,x64 and arm64. But in the Visual Studio dialog only x64 is activated. x86 and arm64 are grayed out. If I compile the app by hand under Debug in x86 and arm64, there are no errors and the app also runs. Why can't I create store packages with all three architectures? I have a similar app (still in UWP) and had tried copying the settings from the csproj, but to no avail.

### Steps to reproduce the bug

1. create WinUI 3 project (with Windows Template Studio)
2. right click on the project in the Solution Explorer and then on "Package and Publish"
3. In the following dialog select the first item: "Microsoft Store as {App-Name} by Lars Krämer".
4. The "Select and configure packages" page follows. Here I can set the version of the app and which architectures should be compiled. Neutral", "x86", "x64" and "ARM" are displayed. But I can only select "x64". In the end, only a single MSIX file and no MSIXBUNDLE, etc. is generated.
Used Windows Template Studio Version (wizardVersion) 5.2.1

Installed NuGet are:
* CommunityToolkit.Mvvm 8.0.0
* CommunityToolkit.WinUI.UI 7.1.2
* CommunityToolkit.WinUI.UI.Controls 7.1.2
* Microsoft.AppCenter.Analytics 4.5.3
* Microsoft.AppCenter.Crashes 4.5.3
* Microsoft.Extensions.Configuration 6.0.1
* Microsoft.Extensions.Configuration.Abstractions 6.0.0
* Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0
* Microsoft.Extensions.Hosting 6.0.1
* Microsoft.Extensions.Options.ConfigurationExtensions 6.0.0
* Microsoft.WindowsAppSDK 1.1.5
* Microsoft.Xaml.Behaviors.WinUI.Managed 2.0.9
* Newtonsoft.Json 13.0.1
* WinUIEx 1.8.0

### Screenshots

<img width="610" alt="Screenshot 2022-10-09 230138" src="https://user-images.githubusercontent.com/1656571/194779303-7210b3cc-fb73-4d38-957c-50464d674ba3.png">

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DarranRowe** [comment]
Is this a single project or do you have a separate packaging project?
If it is a single project, I believe there is an issue where the single project packaging addon will not make MSIX bundles. Try disabling packaging for that project and create a separate packaging project and see if the issue persists.

**Comment by lk-code** [comment]
In the solution I have three projects (1x WinUI 3 app, 2x .NET 6 libraries). I have created a new project with Windows Template Studio. Now I can at least select x64 and ARM64, but x86 and ARM are still missing.
I thought that maybe a NuGet library from Windows Template Studio is not available for x86 and ARM, so I created an empty WinUI app. And indeed, in an empty WinUI3 app (without Windows Template Studio, etc.) it is possible to select x86, x64 and ARM64 :/

**Comment by DarranRowe** [comment]
Well, packaging projects only produce MSIX output for platforms available in the project. Have you checked what platforms are in the Template Studio projects? Also, could you verify if adding a platform helps?
Also, x86, x64 and arm64 are what you would be interested in for Windows App SDK/WinUI 3 projects. These are the only platforms that the redistributable is available for.

**Comment by lk-code** [comment]
What exactly do you mean by platform?
In the csproj file, the Platforms entry is as follows: "<Platforms>x86;x64;arm64</Platforms>"

"Also, x86, x64 and arm64 are what you would be interested in for Windows App SDK/WinUI 3 projects. These are the only platforms that the redistributable is available for." I know that, I am also only interested in x86, x64 and arm64 for this app. The arm entry just caught my eye.

So far I have not detected any difference between an empty WinUI3 app and a WTS app :( .

**Comment by DarranRowe** [comment]
Well, this is one of those cases where I thought it was obvious what I meant by platform. But obviously it wasn't as obvious.

The platform that I was referring to is the solution platform that you set via. configuration manager.

![Screenshot 2022-10-17 183402](https://user-images.githubusercontent.com/52577874/196245835-7e28c0b3-29a6-4e0e-8ef1-0650874426a1.png)
![Screenshot 2022-10-17 183730](https://user-images.githubusercontent.com/52577874/196245877-fa54f051-c4ae-4bd0-be1a-59344b9b5877.png)

![Screenshot 2022-10-17 183823](https://user-images.githubusercontent.com/52577874/196245924-65307451-2fc5-4f31-9ba4-5c9287feb762.png)
![Screenshot 2022-10-17 183900](https://user-images.githubusercontent.com/52577874/196245935-43e5bcd1-f689-4cf8-8729-b9b6b0334892.png)

As you should be able to see from the screenshots, there is a relationship between the solution platforms in configuration manager and the platforms that you can create packages for.

**Comment by lk-code** [comment]
Ok I have now set it up so that (as in your screenshot) all three platforms are selectable. All three packages are now saved in one folder. However, the folder has the extension "_Test" (SimpleMarkdown_2.1.23.0_Test). Is this a hint that this is not a version for the store? In addition, as with the UWP project, a *.msixupload should be generated. I can't find it either :( Do you have any ideas for that too?

**Comment by evelynwu-msft** [comment]
> Ok I have now set it up so that (as in your screenshot) all three platforms are selectable. All three packages are now saved in one folder. However, the folder has the extension "_Test" (SimpleMarkdown_2.1.23.0_Test). Is this a hint that this is not a version for the store? In addition, as with the UWP project, a *.msixupload should be generated. I can't find it either :( Do you have any ideas for that too?

The "_Test" suffix on the MSIX package output directory is a historical artifact and has no bearing on the validity of the final output. (You can control the package output directory by setting the `AppxPackageTestDir` MSBuild property.)

The lack of an `*.msixupload` file being produced is a feature gap on our part, unfortunately, that we hope to address for WinAppSDK 1.3.

**Comment by lk-code** [comment]
> The "_Test" suffix on the MSIX package output directory is a historical artifact and has no bearing on the validity of the final output. (You can control the package output directory by setting the AppxPackageTestDir MSBuild property.)

That's good to know :)

> The lack of an *.msixupload file being produced is a feature gap on our part, unfortunately, that we hope to address for WinAppSDK 1.3.

That's good to know too, thanks :)

**Comment by lk-code** [comment]
Hi, because currently only MSIX files are created and the store only accepts MSIXBUNDLE files (if previously uploaded) I wrote a small tool to quickly and easily create a MSIXBUNDLE file: https://github.com/lk-code/msix-store-tool.

Feel free to write comments or hints

**Comment by MikeHillberg** [comment]
Thanks @lk-code!

What that tool does is run `makeappx bundle` and then `signtool`. I don't know if it's something just about my app, but I also had to rename the `.msix` files to `.appx` first, before running makeappx (otherwise the Store submission got confused). And rather than signtool, I set `<PackageCertificateKey>` in my proj  file to point to my `_Store.pfx` file.
