### ISSUE TITLE
InfoBar: Some colors don't update when the theme is changed

### ISSUE THREAD

**Issue by jess-rod** [microsoft/microsoft-ui-xaml#7807]
### Describe the bug

When `InfoBar` is inside a popup control (e.g. `Flyout`), some colors don't update when the theme changes from `Dark` to `Light`.

### Steps to reproduce the bug

1. Create a new project (Blank app) in UWP for Windows 10 (not tested in Windows 11).
2. Add WinUI to the project.
3. On `MainPage.xaml`, replace the `Grid` element with this:
```
    <StackPanel x:Name="Root"
                Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
                Padding="16"
                RequestedTheme="Dark"
                Spacing="16">

        <Button x:Name="ThemeButton"
                Click="ThemeButton_Click"
                Content="Toggle theme" />

        <Button Content="Open info bar">
            <Button.Flyout>
                <Flyout>
                    <Grid x:Name="FlyoutRoot">
                        <muxc:InfoBar IsOpen="True"
                                      Severity="Error"
                                      Title="Title" />
                    </Grid>
                </Flyout>
            </Button.Flyout>
        </Button>

    </StackPanel>
```
4. On MainPage.xaml.cs, add the following event handler:
```
private void ThemeButton_Click(object sender, RoutedEventArgs e)
{
    Root.RequestedTheme = Root.RequestedTheme == ElementTheme.Light ? ElementTheme.Dark : ElementTheme.Light;
}
```
5. Start debugging.
6. Click on the button with the label "Open info bar".
7. Close the flyout.
8. Click on the button with the label "Toggle theme". 
9. Click on the button with the label "Open info bar". 
10.  Notice how the background and the icon colors haven't changed. 

### Expected behavior

All colors are updated whenever the theme changes no matter if the InfoBar control is part of a popup or not.

### Screenshots

![image](https://user-images.githubusercontent.com/56958190/194922275-3c2985f6-8b50-45e4-9fc2-ee50f09a75ea.png)

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (20H2): Build 19042

**Comment by jess-rod** [comment]
Is there any estimated date for this bug to be fixed? I appreciate the update. Thank you.

**Comment by enda-mullally** [comment]
This small UI issue is still present in WinAppSDK 2.4.0. I've found myself having to use the above code-behind solution by @jess-rod (ty :-))). Please consider reopning this issue.
