### ISSUE TITLE
HyperlinkButton control does not show up as a link (with blue color text) like shown on MSDN docs https://learn.microsoft.com/en-us/windows/apps/design/controls/hyperlinks#create-a-hyperlinkbutton

### ISSUE THREAD

**Issue by lavinders** [microsoft/microsoft-ui-xaml#7808]
### Describe the bug

HyperlinkButton control does not show up as a link (with blue color text) like shown on MSDN docs https://learn.microsoft.com/en-us/windows/apps/design/controls/hyperlinks#create-a-hyperlinkbutton

### Steps to reproduce the bug

1. Go to any page in WinUI gallery app.
2. Look at visual of hyperlinkbutton control and observe its color is not blue just like shown on MSDN page HyperlinkButton control does not show up as a link (with blue color text) like shown on MSDN docs https://learn.microsoft.com/en-us/windows/apps/design/controls/hyperlinks#create-a-hyperlinkbutton

### Expected behavior

Hyperlinkbutton text shows up in blue or theme specific color for hyperlinks.

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Jay-o-Way** [comment]
screenshot please

**Comment by lavinders** [comment]
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/17276086/200915953-0717f38b-257a-4d37-9eeb-d55a95a4ee21.png">

**Comment by lavinders** [comment]
Changing foreground color to blue will make it blue but still won't show as hyperlink, is that the official recommendation and does that work for dark mode, high contrast scenarios, accessibility scenarios?
