### ISSUE TITLE
Application crash on start on Windows 10, version 1809 (build 17763)

### ISSUE THREAD

**Issue by Aladriel** [microsoft/microsoft-ui-xaml#7820]
### Describe the bug

I'm trying to run self-contained application that runs on WinAppSdk 1.1.5 on Windows 10, version 1809 (build 17763). I am able to install msix and cert, install all necessary prerequirements like dotnet. However on app start it crashes and in event log I can see crash report: (screen from sample app, but same behaviour on my application)
![winAppSdkError](https://user-images.githubusercontent.com/15796859/195316682-b551f34b-1461-4855-bf7c-38da1f3514c2.png)

I have no issues with 21H2 Windows 10. I also tried to run some simple example app with WinAppSdk 1.1.0-preview3 on 1809 but the result is the same.

System requirements for Windows app development state that minimal requirements for app development is Windows 10, version 1809 (build 17763) or later. But that may be true for building application, as I can build it on such OS, but I cannot run it.

### Steps to reproduce the bug

Install WinAppSdk 1.1.5 application on Windows 10, version 1809 (build 17763)
Try to run it

### Expected behavior

Application starts and run properly

### Windows app type

- [ ] UWP
- [X] Win32

**Comment by MagicAndre1981** [comment]
make sure you have added `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` to the [csproj file](https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps).

if you still have the crashes you need to create a [crash dump of the app and analyze the dump](https://github.com/dotnet/maui/issues/7473#issuecomment-1140258629). You likely have a bug in your code with Win10 and because the unhandled exception handler is (still?) broken for WinUI3 you get the Stowed Exceptions (those 0xC000027B exceptions) and app exits. Make sure you handle all exceptions in code

**Comment by Aladriel** [comment]
Thanks for answer.
Yes, I have this property set, and msix package is creating properly with all dependencies embedded into msix.
I have followed those steps to get crash dump, but it baiscally confirmed that there is some issue with platform:
![windowsCrashDump](https://user-images.githubusercontent.com/15796859/196920293-b5ddd3c6-7953-40eb-887f-aaa6944f3d5c.jpg)
As I said, I can run same application on Windows 10 1903 without any problems, but it crashes like this on 1809

**Comment by Aladriel** [comment]
I have performed additional tests to find what is causing this issue:
1. I have deployed a blank packaged WinUi3 (framework dependent) project (straight from VS template, no changes) with WinAppSdk 1.1.3 and I was able to install and run it on Win 1809
2. After changing framework dependent to self-contained application crash as described above
3. I have updated WinAppSdk to 1.2.0-preview2, performed exactly the same tests, behaviour is same. Crash on self-contained app on Win 1809, framework-dependent is working fine
4. Run tests on Windows 10 21H2, both self-contained and framework dependent works fine

So it seems that self-contained app is using some system dependencies that are not available, or not working properly on 1809 causing application crash

**Comment by MagicAndre1981** [comment]
> So it seems that self-contained app is using some system dependencies that are not available, or not working properly on 1809 causing application crash

thanks for the additional testing

**Comment by WalkaZxamlem** [comment]
> it should be fixed now. I just tested on latest winappsdk bits on same window 10 version and it is launching fine, with self contained. Closing this bug. If it still appears with latest bits, feel free to reopen it
 Hi @pratikone, what was your testing methodology? I've just tried latest winappsdk and there is no change. You can try to create .msix (self-contained with certificate) and then install it on windows 1809 machine. 
So I wouldn't close this ;)

**Comment by pratikone** [comment]
i was launching via the solution on VS. i  will try the msix way.
