### ISSUE TITLE
XAML parsing failed exception in published application, but no error at all in Visual Studio 2022

### ISSUE THREAD

**Issue by bjorn-malmo** [microsoft/microsoft-ui-xaml#7828]
### Describe the bug

When loading a page in a NavigationView frame, where the page contains an element with an invalid style, this is not reported when running the application in Visual Studio 2022. 
However, when running the published application, this error is raised in InitializeComponent, resulting in an unhandled error with a really sparse message: XAML parsing failed. This error is NOT raised in App.UnhandledException event.

It would be really helpful if;
- this error was raised within Visual Studio during development
- the error message was more descriptive
- the error could be caught in App.UnhandledException

### Steps to reproduce the bug

Create an application with a MainWindow.xaml:

`<Window x:Class="App4.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <NavigationView x:Name="nav" 
                    PaneTitle="Test app"
                    SelectionChanged="NavigationView_SelectionChanged">

        <NavigationView.MenuItems>
            <NavigationViewItem Content="Correct page" Tag="Page1"/>
            <NavigationViewItem Content="Invalid page" Tag="Page2"/>
        </NavigationView.MenuItems>

        <Frame x:Name="frame" VerticalAlignment="Center"/>

    </NavigationView>
</Window>`

You will need a code-behind event handler:
`    private void NavigationView_SelectionChanged(NavigationView sender, NavigationViewSelectionChangedEventArgs args)
    {
        switch ((string)((NavigationViewItem)args.SelectedItem).Tag)
        {
            case "Page1":
                frame.Content = new Page1();
                break;

            case "Page2":
                frame.Content = new Page2();
                break;
        }
    }`

Add a new Page1.xaml:
`<Page
    x:Class="App4.Page1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Grid>
        <StackPanel MaxWidth="300">

            <StackPanel.Resources>
                <Style TargetType="TextBlock" x:Name="Header1">
                    <Setter Property="FontSize" Value="18"/>
                    <Setter Property="FontWeight" Value="Bold"/>
                </Style>
            </StackPanel.Resources>

            <TextBlock Text="Enter your name" 
                       Style="{StaticResource Header1}"/>

            <TextBox   PlaceholderText="Username"/>

        </StackPanel>
    </Grid>
</Page>`

and finally add a new Page2.xaml:
`<Page
    x:Class="App4.Page2"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Grid>
        <StackPanel MaxWidth="300">

            <StackPanel.Resources>
                <Style TargetType="TextBlock" x:Name="Header1">
                    <Setter Property="FontSize" Value="18"/>
                    <Setter Property="FontWeight" Value="Bold"/>
                </Style>
            </StackPanel.Resources>

            <TextBlock Text="Enter your name again" 
                       Style="{StaticResource Header1}"/>

            
            <TextBox   PlaceholderText="Username one more time"
                       Style="{StaticResource Header1}"/>

        </StackPanel>
    </Grid>
</Page>
`

**Note that in Page2.xaml, we have applied a style to a textbox which targets a textblock**

This application will run fine within Visual Studio 2022 without any errors or exceptions being raised.

Now, publish the application to an msix-file, install the application and run it. The application will crash when selecting Page2.

### Expected behavior

The error should be raised while developing inside Visual Studio 2022

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Visual Studio 2022 V17.3.6

Windows App SDK 1.1.3

**Comment by SoftEntwickler** [comment]
I have a problem with parsing of XAML in published app too.
Have @bjorn-malmo you found a solution?
