### ISSUE TITLE
NavigationViewItemSelector does not respond to property changes to set color and width

### ISSUE THREAD

**Issue by rcohn** [microsoft/microsoft-ui-xaml#7832]
### Describe the bug

Hello -

In a WinUI3 unpackaged desktop app, I've been trying to set a NavigationViewItemSelector (NVIS) to something other than its default color and width.  To that end I've been trying to set NVIS properties.  

For example, this does nothing to the NVIS appearance:
```
 <NavigationView.MenuItems>
	  <NavigationViewItem>One</NavigationViewItem>
	  <NavigationViewItemSeparator Background="Red"></NavigationViewItemSeparator>
	  <NavigationViewItem>Two</NavigationViewItem>
 </NavigationView.MenuItems>

```
I tried BorderBrush with same results.

Can you tell me if NavigationViewItemSeparator is broken in WinUI3 (am using WindowsAppSDK 1.1.5).

Can anybody point to some sample code that is using NavigationViewItemSeparator with properties set to something than the default?

Thank you.

### Steps to reproduce the bug

I gave a code snippet in the above field showing what should be the simplest case for using NavigationViewItemSeparator.

Do you need to have a working demo?

### Expected behavior

I would expect the NavigationViewItemSeparator to change color.

### Screenshots

![image](https://user-images.githubusercontent.com/2237248/195959068-66fda1f8-7693-481e-9de6-1c64e88669e5.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Scighost** [comment]
You should modify the XAML resource.

``` xaml
<NavigationView>
    <NavigationView.Resources>
        <SolidColorBrush x:Key="NavigationViewItemSeparatorForeground" Color="Red" />
    </NavigationView.Resources>
    <NavigationView.MenuItems>
        <NavigationViewItem>One</NavigationViewItem>
        <NavigationViewItemSeparator />
        <NavigationViewItem>Two</NavigationViewItem>
    </NavigationView.MenuItems>
</NavigationView>
```

<img width="235" alt="image" src="https://user-images.githubusercontent.com/61003590/196838449-a60f3d35-3468-4e1c-bcbf-85de26fcb584.png">

NavigationViewSeparator template is defined in:
https://github.com/microsoft/microsoft-ui-xaml/blob/29f18e7ef2c68ae9ccb204ca3f632a03ec7f26c0/dev/NavigationView/NavigationView.xaml#L924-L961
