### ISSUE TITLE
Flyout in ListView doesn't open for selected item

### ISSUE THREAD

**Issue by davidegiacometti** [microsoft/microsoft-ui-xaml#7838]
### Describe the bug

Sample: https://github.com/davidegiacometti/flyout-bug

ListView with an AttachedFlyout on the item.
RightTapped on the item show the flyout.

### Steps to reproduce the bug

Usually happens if you reproduce the steps 2 or 3 times in a row fast.
1 select an item of the list
2 right click
3 flyout not showed

### Expected behavior

Flyout should always be opened

### Screenshots

![Bug](https://user-images.githubusercontent.com/25966642/196040094-ce479336-f50e-4e9d-b1ba-d9f1844cd52d.gif)

Red dot: mouse right click

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by davidegiacometti** [comment]
I have news.
The issue is in the `ShowAt` call:

```
flyoutBase.ShowAt(owner, new FlyoutShowOptions
{
    Position = e.GetPosition(owner),
});
```

If I pass `ShowMode = FlyoutShowMode.Transient` the issue doesn't happen but the context menu doesn't get focus.

**Comment by davidegiacometti** [comment]
Still happening with latest stable 1.3.230602002 and latest preview 1.4.230628000.

**Comment by ranjeshj** [comment]
This seems to work fine for me. I do see that sometime the flyout does not open. That might be because the right_tapped handler is on the TextBlock and there is area outside the TextBlock where you can click. Adding the handler on the ListViewItem itself might avoid that.
