### ISSUE TITLE
Selection Start offset not right in textblock?

### ISSUE THREAD

**Issue by ljzj2** [microsoft/microsoft-ui-xaml#7843]
### Describe the bug

with IsTextSelectionEnabled=True,I select some text and get the startselection's offset but it is not right.

### Steps to reproduce the bug

1.add a textblock set IsTextSelectionEnabled=true.
2.select the text.

`<TextBlock Text="罩云飘远岫，喷雨泛长河。低飞昏岭腹，斜足洒岩阿。泫丛珠缔叶，起溜镜图波。濛柳添丝密，含吹织空罗。" SelectionChanged="TextBlock_SelectionChanged"
                   IsTextSelectionEnabled="True" />`

### Expected behavior
If I select `云飘远` the StartSelection.Offset will be 1

### Actual

StartSelection.Offset is not right.

**Comment by ljzj2** [comment]
@Jay-o-Way  please check it.

**Comment by Jay-o-Way** [comment]
If I am correct, these kind if indexes are often zero-based, so the first character would start at zero.

**Comment by ljzj2** [comment]
yes,if the first character start at zero.
罩-0
云-1
飘-2

**Comment by ljzj2** [comment]
云飘远岫=1

**Comment by Jay-o-Way** [comment]
The it's not a bug, just the way it works.

**Comment by ljzj2** [comment]
@Jay-o-Way  but it is the expected behavior not the actual.
actual the StartSelection.Offset will be wrong please check it.

you can add a button in the UI and select some words like `远岫` and click the button to get the offset it will be others not 3

**Comment by Jay-o-Way** [comment]
So what IS the actual result then? Just be clear about it, don't let me do all the work...

**Comment by ljzj2** [comment]
If I select this:

![image](https://user-images.githubusercontent.com/110752116/196688293-2f8c4533-d8a7-4342-bc24-042ed6123401.png)

offset is 3

If this:
![image](https://user-images.githubusercontent.com/110752116/196688388-7fc69e9c-9f5b-47b5-9c7f-25a62fe6a62b.png)
offset is 12
all is wrong

**Comment by ljzj2** [comment]
If this 
![image](https://user-images.githubusercontent.com/110752116/196688568-7ec3b6f2-2ccb-4da4-954d-9fe57e397b34.png)
offset is 7

**Comment by ljzj2** [comment]
@Jay-o-Way

**Comment by Jay-o-Way** [comment]
I think it has to do with the fact that Chinese/Asian characters use two bytes. But I'm not the expert on this.

**Comment by ljzj2** [comment]
@Jay-o-Way  thank you. who can help me.
