### ISSUE TITLE
Blank WinUI3 app reads out $"{Window.Title} Window DesktopChildSiteBridge" when using narrator

### ISSUE THREAD

**Issue by PureWeen** [microsoft/microsoft-ui-xaml#7853]
### Describe the bug

If you enable narrator and have it read out any default WinUI3 app it reads out 

$"{Window.Title} Window DesktopChildSiteBridge pane" 

If you look at application insights you'll see there's a pane component with the name "DesktopChildSiteBridge"
![image](https://user-images.githubusercontent.com/5375137/196996187-2e5309f9-c020-4028-a210-45df0e63920d.png)

This issue was reported to the .NET MAUI team by Roberto from C+AI Accessibility

https://github.com/dotnet/maui/issues/10131

### Steps to reproduce the bug

Run the following app which is just the default template. You can see the same issue if you run the WinUI3 Gallery

[App103.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9831752/App103.zip)

### Expected behavior

• Expected behaviour: Narrator announces $"{Window.Title} Window"
• Actual behaviour: Narrator announces $"{Window.Title} Window DesktopChildSiteBridge pane"

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by codendone** [comment]
[internal bug](http://task.ms/41935066)

**Comment by ionvasilian** [comment]
Thank you for reporting the issue. A fix for the issue will be available with the WindowsAppSDK 1.3 release.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.3.0` has been released which fixes this issue.
* [Release Notes](https://aka.ms/windowsappsdk/1.3/1.3.0/release-notes)
* [Nuget](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000) to try it out.
