### ISSUE TITLE
Bug when a CommandBarFlyout get opened from a button click within another CommandBarFlyout

### ISSUE THREAD

**Issue by yucu** [microsoft/microsoft-ui-xaml#786]
**Describe the bug**
When you click a button in SecondaryCommands of a CommandBarFlyout, that will open another CommandBarFlyout, the second CommandBarFlyout will appear and disappear.

**Steps to reproduce the bug**
See VS project at: https://microsoft-my.sharepoint-df.com/:u:/p/yucu/EUNg00vH4sNBiVm8X5w7o88B7I460r6Ogpi3AgTdgwtQdA?e=lcrDcC

**Expected behavior**
The second CommandBarFlyout stay open.

**Screenshots**
![image](https://user-images.githubusercontent.com/31290648/58739851-77012000-83c1-11e9-9de7-b12ee345f1d7.png)
Click the button in the red circle.

**Version Info**
WUX

NuGet package version: 
NA

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
This isn't a scenario we support but I *think* what you might want is more options under your AppBarButton, which is supported via the "Flyout" property on AppBarButton. This would enable cascading submenus off the CommandBarFlyout, which I think is what you're looking for.
