### ISSUE TITLE
Memory leak on click event of Buttons wrapped TabView

### ISSUE THREAD

**Issue by Gypsy-H-Takumi** [microsoft/microsoft-ui-xaml#7860]
### Describe the bug

I researched about User Control that was uncalled destructor.
```
<TabView>
    <TabViewItem Header="1st">
        <Button Click="Button_Click" Content="BUTTON"/>
    </TabViewItem>
</TabView>
```
If I have such event in your TabView, the destructor won't be called when I switch pages, causing a memory leak.

### Steps to reproduce the bug

1. TabView outer frame
2. Some Event inner frame

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by lukeblevins** [comment]
@gabbybilka This issue is identical to #3597. Any update from the team on it? This delay is absolutely not ideal for customers relying on TabView for any kind of complex content.

**Comment by Gypsy-H-Takumi** [comment]
I have found my own solution. That is to remove the event and assign null for the ICommand when want to dispose.
```
Button_Click -= <Method>;
*.Command = null;
```
