### ISSUE TITLE
[ARM64][WinUI] Publish/Package failed because of "WinAppSdkGenerateAppInstallerFile"

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#7862]
### Describe the bug

Publish/Package WinUI project failed with 2 errors.

### Steps to reproduce the bug

**VS version**: 17.4.0 [33021.125.d17.4]
Note: 
1. This issue reproduces on the TargetFramework(net7.0-windows10.0.19041.0, net6.0-windows10.0.19041.0).
2. This issue does not reproduce on x64.

**Repro Steps:**
1. Create a Blank App, Packaged(WinUI 3 in Desktop) project
3. Right click on project node -> Package and Publish -> Create App Packages
4. Select Sideloading with "Enable automatic updates" checked
5. Select a certificate by "Create", click Next
6. Select "Yes, use current certificate", click Next
7. Select packages for x86 and x64, click Next
8. Enter a valid location in Installer location -> Create

**Actual Result:** Publish Failed with 2 errors.
APPX000: Task 'WinAppSdkGenerateAppInstallerFile' failed. Retrieving the COM class factory for component with CLSID {5842A140-FF9F-4166-8F5C-62F5B7B0C781} failed due to the following error: 800700c1  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1).
MSB4018: The "WinAppSdkGenerateAppInstallerFile" task failed unexpectedly.
![image](https://user-images.githubusercontent.com/97647558/197504067-3e8a4ba9-371d-4fc4-8bad-c75b2378b919.png)

### Expected behavior

Expected Result: Publish/Package successfully without error.

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Preview 1: 1.2.0-preview1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by evelynwu-msft** [comment]
I think the `TargetPlatform` of the TFM needs to be `net7.0-windows10.0.22621.0` as the 22621 Windows SDK is the first one that includes an ARM64 version of `AppxPackaging.dll`

@bpulliam If targeting the latest Windows SDK is in fact the solution then we should update the C# [project template](https://github.com/microsoft/WindowsAppSDK/blob/9917f2d8cf111ccb196e06f7845162e8cbc014d7/dev/VSIX/ProjectTemplates/Desktop/CSharp/SingleProjectPackagedApp/ProjectTemplate.csproj#L4) accordingly.

**Comment by Scottj1s** [comment]
Closing with recommended workaround, and fixed in 1.2
