### ISSUE TITLE
[WinUI2] If more than four AppBarButton added to the CommandBar then the 5th, 6th etc. AppBarButtons never will be visible on a small display device

### ISSUE THREAD

**Issue by pubtom** [microsoft/microsoft-ui-xaml#7864]
### Describe the bug

If more than four AppBarButton added to the CommandBar then the 5th, 6th etc. AppBarButtons never will be visible on a small display device.

It is not working since WinUI2 >=2.6 version. The last working version was the WinUI 2.5 version.

Since
**WinUI 2.0 - 2.7** works downlevel to Windows 10 Creators Update (Version 1703, OS build 15063). 
**WinUI 2.8 and later** works downlevel to Windows 10 October 2018 Update (Version 1809, OS build 17763).

it is important to fix this issue in the **WinUI 2.7.3** version line, since this is the latest version supports 15063 and before builds.

### Steps to reproduce the bug

Create an empty MainPage.xaml with a CommandBar. 
Add more then 4 AppBarButton item to the CommandBar.
**Run this on a small display device.** I ran this on Windows 10 Mobile (both device & emulators), but any small display device has this issue.

    <Page.BottomAppBar>
        <CommandBar  Name="myCommandBar">
            <AppBarButton Icon="Setting" Label="1" />
            <AppBarButton Icon="Setting" Label="2" />
            <AppBarButton Icon="Setting" Label="3" />
            <AppBarButton Icon="Setting" Label="4" />
            <AppBarButton Icon="Setting" Label="5" />
            <AppBarButton Icon="Setting" Label="6" />
        </CommandBar>
    </Page.BottomAppBar>
    <Grid>
    </Grid>

### Expected behavior

All the 6 AppBarButtons visible when clicking on the "..."

### Screenshots

Doesn't work in WinUI 2.6 - 2.7.3 versions, Item 5 & Item 6 are missing:
![Doesn't work in WinUI 2 6 - 2 7 3 versions](https://user-images.githubusercontent.com/64859544/197611285-3acdba98-2d0c-4a77-af52-136b5b79f1fe.png)

Works correctly in the WinUI 2,5 version:
![Works in WinUI 2 5 version](https://user-images.githubusercontent.com/64859544/197611417-0a6097e0-2f0f-40b0-b3cd-fdf860fda2c6.png)

### Windows app type

- [X] UWP
- [ ] Win32

### Windows version

Windows 10 (21H1): Build 19043

**Comment by ranjeshj** [comment]
[microsoft-ui-xaml/docs/contribution_handling.md at main · microsoft/microsoft-ui-xaml (github.com)](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)
The WinUI team is currently spending its time on WinUI 3. To help with this focus, new bugs filed against WinUI 2 are closed in this repo unless they're a security issue or are business critical.
