### ISSUE TITLE
[WinUI2] NavigationView displaying empty whitespace after the Pane on small display devices

### ISSUE THREAD

**Issue by pubtom** [microsoft/microsoft-ui-xaml#7865]
### Describe the bug

NavigationView displaying **empty whitespace(s)** after the Pane **on small display devices**.
**PaneDisplayMode="LeftMinimal"**

**Last working version was the WinUI 2.3.200213001 version!** It's getting worse on newer WinUI versions:
2.4 - 2.5 versions displaying one empty whitespace line
2.6 and later versions displaying two empty whitespace lines.

### Steps to reproduce the bug

Create just a basic NavigationView and **see how it is displayed on a small display device**.

See that:

WinUI 2.3.200213001 version displaying correctly the NavigationView without any unneccesery whitespace.
WinUI 2.4 - 2.5 versions are displaying one empty whitespace line. Not good!
WinUI 2.6 and later versions are displaying two empty whitespace lines. Not good!

I run this example on a Windows 10 Mobile device and also on emulators, but any small display device has this issue.
I put Rectangle controls with StrokeThickness just to help to visualize the error.

```
<Page
...
    xmlns:mux="using:Microsoft.UI.Xaml.Controls">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="100"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Rectangle Grid.Row="0" Width="300" Height="100" VerticalAlignment="Top" HorizontalAlignment="Left" Fill="LightCoral" Stroke="Yellow" StrokeThickness="1"/>
        <mux:NavigationView Grid.Row="1"  Name="myNavigationView" IsBackButtonVisible="Collapsed" IsSettingsVisible="False" PaneDisplayMode="LeftMinimal">
            <mux:NavigationView.MenuItems>
                <mux:NavigationViewItem Content="Item 1"/>
                <mux:NavigationViewItem Content="Item 2"/>
                <mux:NavigationViewItem Content="Item 3"/>
            </mux:NavigationView.MenuItems>
            <mux:NavigationView.Content>
                <Rectangle  Width="300" Height="200" VerticalAlignment="Top" HorizontalAlignment="Left" Fill="Blue" Stroke="Red" StrokeThickness="1"/>
            </mux:NavigationView.Content>
        </mux:NavigationView>
    </Grid>
</Page>
```

### Expected behavior

NavigationView displaying without any unneccesery whitespace. (like in the 2.3.200213001 version)

### Screenshots

WinUI 2.3.200213001 version displaying correctly the NavigationView without any unneccesery whitespace:
![WinUI 2 3 200213001](https://user-images.githubusercontent.com/64859544/197634329-a93938f9-36be-4d4a-bb59-fc8902a4510a.png)

WinUI 2.4 - 2.5 versions displaying one empty whitespace line:
![WinUI 2 4 -2 5](https://user-images.githubusercontent.com/64859544/197634705-dc34c026-c04c-4970-8f6b-1617362b7d66.png)

WinUI 2.6 and later versions displaying two empty whitespace lines:
![WinUI 2 6 -](https://user-images.githubusercontent.com/64859544/197634737-96124bf7-492f-4722-9e53-30293bce6e09.png)

### Windows app type

- [X] UWP
- [ ] Win32

**Comment by pubtom** [comment]
@Microsoft Please solve this issue ASAP!

**Comment by ojhad** [comment]
I am unable to repro this on Windows 11 when sizing the window to a small size. Since Windows Phone is no longer supported, we are not fixing bugs that only occur there.
