### ISSUE TITLE
Adding menu items to text context menu has dead space

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#7867]
### Describe the bug

The text context menu becomes broken when customized. This happens in WinUI 3 but not in WinUI 2.

### Steps to reproduce the bug

In the Gallery app, go to the RichEditBox page.
In the Customizing RichEditBox's CommandBarFlyout - Adding 'Share' example, type some text and right click to bring up the context menu.

In WinUI 2 gallery this works as expected:

![image](https://user-images.githubusercontent.com/22989529/197922930-ca52244d-235a-4c97-80ad-ce190c4a9b24.png)

In WinUI 3 gallery, a dead space gap exists between the added command and the rest of the menu:

![image](https://user-images.githubusercontent.com/22989529/197922870-736de0a2-644c-4d34-b0e1-89dc706fb345.png)

### Expected behavior

No dead space gap

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Preview 1: 1.2.0-preview1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by asklar** [comment]
Duplicate of #6984

**Comment by bpulliam** [comment]
I'm not seeing this anymore in WinUI 3 Gallery v2.0 based on WinAppSDK 1.3.
