### ISSUE TITLE
The TakeFocusRequested event in DesktopWindowXamlSource does not fire.

### ISSUE THREAD

**Issue by DarranRowe** [microsoft/microsoft-ui-xaml#7870]
### Describe the bug

I have been writing a sample to show how Xaml Islands work with the Windows App SDK/WinUI 3. In this sample, I have noticed that the control navigation does not work correctly. Pressing tab works fine navigating across any Windows API controls, but once focus enters the xaml source, the focus was never able to leave.

The issue stemmed from the event handler for DesktopWindowXamlSource.TakeFocusRequested not executing. After making sure that I had hooked up the event properly, I tested similar code out targeting the UWP version. This version does work as expected.

As a side note, the GotFocus event also doesn't fire in the way that is documented in the UWP documentation. This doesn't work with the UWP version either and I have opened an issue in the Windows Feedback Hub. But is this expected?

### Steps to reproduce the bug

Using the repository at [XamlIslandTest3](https://github.com/DarranRowe/XamlIslandTest3), open it, build and run it.
Press the tab key 3 times. You should notice that focus goes to the first Windows API button, then to the Xaml button then vanishes. If you press space at this point, the Xaml button is what receives the key press. This means that focus is still on the Xaml button.

Contrasting it with the [UWP sample](https://github.com/DarranRowe/XamlIslandTest), if you do the same thing, the second Windows API button is what takes the key presses.

The code to move focus out of the Xaml source is in the TakeFocusRequested handler.

As a note, the UWP sample currently loads WinUI 2.7 using the Windows 11 Dynamic Dependency API.

### Expected behavior

For the second Windows API button to have keyboard focus after pressing tab 3 times.

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Experimental 2: 1.2.220909.2-experimental2

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by bpulliam** [comment]
The Islands feature set is still in development. Others are free to comment but this will not be our primary focus for now.
