### ISSUE TITLE
Regression: elastic scrolling/rubber bounce on scrolling is missing on touchpads

### ISSUE THREAD

**Issue by BreeceW** [microsoft/microsoft-ui-xaml#7874]
### Describe the bug

Windows App SDK 1.2 has broken the elasticity effects and animation curves from scroll views when scrolled from a touchpad. This issue only applies to touchpads. Touchscreen scrolling was not affected by this regression.

### Steps to reproduce the bug

1. Open a WinUI 3 app with a control that uses ScrollViewer (e.g., ListView)
2. On a laptop with a Precision Touchpad, use the two-finger scrolling gesture
3. Observe scrolling feels unnatural and does not bounce at top and bottom

### Expected behavior

The scrolling animation curves should feel like how they are in Windows App SDK 1.1 and WinUI 2 when using a touchpad.

#### Windows App SDK 1.1.5 behavior (expected)
https://user-images.githubusercontent.com/18747724/198851897-9579ac04-6b42-4058-83ce-4d1d6fe37976.mp4

Beautiful, smooth with Precision Touchpad

#### Windows App SDK 1.2.220930.4-preview2 (regression)
https://user-images.githubusercontent.com/18747724/198851903-fc64db4a-31f5-41b6-a64e-f6042857353e.mp4

Unnatural, no bounce effect with precision touchpad

### NuGet package version

WinUI 3 - Windows App SDK 1.2 Preview 2: 1.2.220930.4-preview2
Issue affects first 1.2 experimental release.

### Windows app type

☐ UWP
🗹 Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This issue seems to be a re-introduction of #2513, UWP aside, though I do not know how non-Precision Touchpad devices are affected this time.

**Comment by lhak** [comment]
Seems that the touchpad is only used in some kind of mouse emulation mode as touchpad gestures in general are broken (https://github.com/microsoft/microsoft-ui-xaml/issues/7572)

**Comment by codendone** [comment]
[internal bug](http://task.ms/41861881)

**Comment by simon-knuth** [comment]
Yup, this just shipped in 1.2 stable, precision touchpads are now glorified mouse wheels. I'm kind of astonished by how this regression impacting an interaction that's probably central to most apps was just carried through for 3 months straight. 😐 I really hope this won't be forgotten and instead serviced soon.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK.1.2.221209.1` has been released which fixes this issue.

Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2.221209.1/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1)
