### ISSUE TITLE
Toast Notifications:  Notification.Visual.GetBinding - Does not seem to support anything other than the generic text in the notification

### ISSUE THREAD

**Issue by Snappee** [microsoft/microsoft-ui-xaml#7877]
### Describe the bug

Your documentation mentions that through the 'Notification.Visual.Bindings' collection that a Developer can retrieve the various elements that are bound to the notification.   While this sounds great, every example only shows the type of 'KnownNotificationBindings.ToastGeneric' - which works.  

However, there are NO OTHER enumerations - so text is it from what I can tell.  This means that the whole discussion of 'Toast Content' doesn't really apply . . . as I don't see a way to retrieve any other content other than the text (as a 'Receiver' of the notification.).

Am I missing something here?

### Steps to reproduce the bug

1) Create a basic UWP application - as shown in various examples.

GitHub: WindowsNotifications/NotificationListenerActionCenterApp

2) Update the dependencies, build it
3) Review the MyToastNotificationControl User Control
4) On your event that handles the notification, do the following: - "UpdateTextContext"

YourClass.Notification.Visual.GetBinding(KnownNotificationBindings.ToastGeneric);

5) You'll see that there are NO other bindings available other than the raw text.   

### Expected behavior

I expect under the 'Visual' property of the Notification, to retrieve all of the various content types that can be bound to an incoming notification.

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Additional context

Visual Studio 2022:  64 Bit, 17.3.4
Windows 10 Professional - Current

**Comment by Snappee** [comment]
Come on gang, at least go through the darn triage process!

**Comment by Scottj1s** [comment]
@Snappee this issue appears to be UWP-related.  Please open new feedback here:
https://learn.microsoft.com/en-us/answers/topics/windows-uwp-feedback.html

**Comment by Snappee** [comment]
Thanks Scott . . . my only bitch is that I called out UWP in my original post - and it took 30 days to inform me that I need to take it up with another group/site.   That sure slows development down.  

Also, are you saying that you tested it in a different environment, and it worked?   If so, what environment?

Appreciate the feedback.  Please advise . . .
