### ISSUE TITLE
UniformGridLayout uses assignment instead of comparison

### ISSUE THREAD

**Issue by grokys** [microsoft/microsoft-ui-xaml#788]
**Describe the bug**

On this line: https://github.com/microsoft/microsoft-ui-xaml/blob/61ea8fb19e84504a909cbe7bfa40202d2dc09090/dev/Repeater/UniformGridLayout.cpp#L270

That should be a comparison, not an assignment,

**Version Info**

Current master

**Additional context**

Apologies for not filling in more of the sections, but I think this describes the issue sufficiently.

**Comment by jevansaks** [comment]
Yikes! Great catch @grokys. @Ranjeshj, good opportunity to switch Repeater over to the per-property codegen callbacks.

**Comment by grokys** [comment]
In case you're wondering how I noticed this, I'm porting `ItemsRepeater` to Avalonia: https://github.com/AvaloniaUI/Avalonia/pull/2603 -- just in case you're interested!
