### ISSUE TITLE
[UWP] How to change App.Current.Resources after installing Microsoft.UI.Xaml in C#?

### ISSUE THREAD

**Issue by nextcodelab** [microsoft/microsoft-ui-xaml#7884]
### Describe the bug

https://learn.microsoft.com/en-us/answers/questions/1075757/uwp-how-to-change-appcurrentresources-after-instal.html

After Installing this package [Microsoft.UI.Xaml][1]

I always getting this error... and I can't change the App.Current.Resources dynamically in C#.

  [1]: https://www.nuget.org/packages/Microsoft.UI.Xaml
  [2]: /answers/storage/attachments/257168-screenshot-2022-11-04-173651.png

in my App.xaml
```xaml
<Application
    x:Class="UniversalProject.UWP.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    xmlns:local="using:UniversalProject.UWP"
    xmlns:uwpbasic="using:UWP.Basic.Controls">
    <Application.Resources>
        <controls:XamlControlsResources>
            <controls:XamlControlsResources.MergedDictionaries>
                <ResourceDictionary>
                </ResourceDictionary>
                <ResourceDictionary Source="Styles/ApplicationStyles.xaml" />
            </controls:XamlControlsResources.MergedDictionaries>
        </controls:XamlControlsResources>        
        <!--<ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Styles/ApplicationStyles.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>-->
    </Application.Resources>
</Application>
```
Please help me to change resources dynamically in C# with Microsoft.UI.Xaml

### Steps to reproduce the bug

Do not launch

### Expected behavior

Change the resources value like Solid and Color....

### Screenshots

![Screenshot 2022-11-04 173651](https://user-images.githubusercontent.com/73583588/199946273-f2d706b0-f494-41a4-b32c-8b3b36d35f95.png)

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by roxk** [comment]
@nextcodelab You just need to add another `ResourceDictionary` entry inside `controls:XamlControlsResources.MergedDictionaries` node, and add your resources there.

**Comment by nextcodelab** [comment]
> @nextcodelab You just need to add another `ResourceDictionary` entry inside `controls:XamlControlsResources.MergedDictionaries` node, and add your resources there.

I tried it and no success..
```xaml
<Application.Resources>
        <controls:XamlControlsResources>
            <controls:XamlControlsResources.MergedDictionaries>
                <ResourceDictionary>
                    <Color x:Key="SystemAccentColor">Blue</Color>
                </ResourceDictionary>
                <ResourceDictionary Source="Styles/ApplicationStyles.xaml" />
            </controls:XamlControlsResources.MergedDictionaries>
        </controls:XamlControlsResources>
    </Application.Resources>
```
resul still getting this error.
![Screenshot 2022-11-05 100203](https://user-images.githubusercontent.com/73583588/200096285-72e8234b-9950-44c8-a00a-b575a99095f9.png)

**Comment by nextcodelab** [comment]
Fixed by accessing the merge dictionaries
```cs
var r = Application.Current.Resources;
                var Resources = r.MergedDictionaries[0];
                Resources["SystemAccentColor"] = SystemAccentSolidColor.Color;
```

**Comment by Scottj1s** [comment]
@nextcodelab looks like you've found a solution - please reopen if you feel there's an issue with the framework.

**Comment by rahulragava** [comment]
> Already fixed by accessing merge dictionary by index.
> 
> ```
> <Application.Resources>
> <controls:XamlControlsResources>
> <controls:XamlControlsResources.MergedDictionaries>
> <ResourceDictionary>
> <Color x:Key="SystemAccentColor">Blue</Color>
> </ResourceDictionary>
> <ResourceDictionary Source="Styles/ApplicationStyles.xaml" />
> </controls:XamlControlsResources.MergedDictionaries>
> </controls:XamlControlsResources>
> </Application.Resources>
> ```
> 
> var r = Application.Current.Resources; var Resources = r.MergedDictionaries[0]; Resources["SystemAccentColor"] = SystemAccentSolidColor.Color;

nope still having same problem as author. same exception gets thrown. is there any solution regarding this ?
