### ISSUE TITLE
ComboBox how to cancel the selected item?

### ISSUE THREAD

**Issue by OldManWangJY** [microsoft/microsoft-ui-xaml#7886]
When I clear the Text of the ComboBox or click again, the selected item is still not canceled

**Comment by Scottj1s** [comment]
@OldManWangJY Can you provide a repro, along with expected and actual results? I'm not sure I understand where the bug is.

**Comment by OldManWangJY** [comment]
I have raised the same question [here](https://stackoverflow.com/questions/74319843/winui3-combobox-how-to-cancel-the-selected-item/74328666#74328666), but the desired effect is to add a clear button, which may require me to customize the combobox

**Comment by OldManWangJY** [comment]
> @OldManWangJY你能提供一个重现，以及预期和实际结果吗？我不确定我明白错误在哪里。

 I have raised the same question [here](https://stackoverflow.com/questions/74319843/winui3-combobox-how-to-cancel-the-selected-item/74328666#74328666), but the desired effect is to add a clear button, which may require me to customize the combobox
