### ISSUE TITLE
Why does UserControl does not derive from ContentControl like in WPF?

### ISSUE THREAD

**Issue by opcodewriter** [microsoft/microsoft-ui-xaml#790]
Why does the UserControl class in UWP does not derive from ContentControl like in WPF?
I guess there's a specific reason for this?

**Comment by MikeHillberg** [comment]
The main purpose of ContentControl is to display any object, so it has an object-typed Content property, and has a ContentTemplate. UserControl is just meant to display an element tree, so it has no ContentTemplate property, and its Content property is UIElement-typed.

**Comment by opcodewriter** [comment]
Thanks, I see. Do you agree having UserControl derived from ContentControl in WPF was a mistake?
I think so, it doesn't make sense.

**Comment by opcodewriter** [comment]
Oh, why does Frame derive from ContentControl in UWP? Now I'm confused..

**Comment by jevansaks** [comment]
@opcodewriter I assume the design for UserControl is that we don't want to presume that every UserControl can have content -- maybe it can have none or multiple. If you want your UserControl to have Content then you should follow the pattern of ContentControl and have Content, ContentTemplate, ContentTemplateSelector and bind those properties through to a ContentPresenter in your tree.



> Oh, why does Frame derive from ContentControl in UWP? Now I'm confused..
> Shouldn't Frame also only derive from Control?

Again, I can only guess here but Frame is essentially a ContentControl with policy about the backstack and choosing which piece of content is visible at the current time.
