### ISSUE TITLE
Ability to run via exe file (WinUI 3)

### ISSUE THREAD

**Issue by SBProX** [microsoft/microsoft-ui-xaml#7907]
Give the ability to run applications through an exe file directly, and without certificates, in fact, like any classic WPF application, for example.

It is extremely unusual and inconvenient to do MSIX builds with certificates, I would like more freedom of action in this regard.

**Comment by rocksdanister** [comment]
This is already possible and is called unpackaged distribution:
https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app

**Comment by bpulliam** [comment]
Give unpackaged a try! Thanks
