### ISSUE TITLE
Winforms-When added the option(button) in panel not shown the option with DPIAwaresness in 4.7.2 .NET framework

### ISSUE THREAD

**Issue by SaravananAyyanar** [microsoft/microsoft-ui-xaml#791]
**Describe the bug**
Control size and alignment is not proper in the panel with DPI awareness in 4.7.2 framework, but working fine in all other .NET frameworks.

```xml
XML code:
<System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="true"/>    
  </System.Windows.Forms.ApplicationConfigurationSection>
```
**Sample**
[FrameWorkPanel.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3247037/FrameWorkPanel.zip)

**Steps to reproduce the bug**
1.Run the Sample.
2.Click the button in the form.

**Observed**
Button is not properly added and aligned. Button text is not shown.

**Screenshots**
![FrameWork_4 7 2](https://user-images.githubusercontent.com/44993310/58794252-63e68e00-8615-11e9-8578-83c8e45bfe8c.png)

**Expected**
Button should be properly aligned as below.

**Screenshots**
![FrameWork_4 6](https://user-images.githubusercontent.com/44993310/58797033-84661680-861c-11e9-9ec9-7988420aef29.png)

**Additional context**
Attached the Same sample  shown the option properly when framework as 4.6
This cases reproduced 4.7.2 frame work only.

**Comment by jevansaks** [comment]
@SaravananAyyanar it sounds like this issue is about WinForms and not about WinUI or WinForms/WinUI interop -- can you please file the issue on https://github.com/dotnet/winforms ?
