### ISSUE TITLE
Adding a TextBox to a page in a NavigationView crashes a WinAppSdk 1.2 app

### ISSUE THREAD

**Issue by ackh** [microsoft/microsoft-ui-xaml#7911]
### Describe the bug

Adding a `TextBox` control to a page that is programmatically added via `NavigationView` crashes the app. This used to work in WinAppSdk 1.1.5 but now fails in WinAppSdk 1.2.221109.1.

### Steps to reproduce the bug

Prerequisites:
- Windows App SDK 1.2 is installed

1. Download the attached [zip file](https://github.com/microsoft/microsoft-ui-xaml/files/9992480/WinAppSdk_Issue_1.2.zip) and extract its content
2. Open "WinAppSdk_Issue_1.2.sln" in Visual Studio 17.4
3. Build and run the solution
4. Switch to the "Page2" tab of the `NavigationView`. The app crashes with an access violation exception in the `LoadComponent` function of file Microsoft.UI.Xaml.h

### Expected behavior

`TextBox` elements can be used in XAML without crashing the app.

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

At the time of this bug submission, the "Nuget package version" drop down does not list the WinAppSdk 1.2 package. The NuGet packaged used is as follows:

`Microsoft.WindowsAppSDK.1.2.221109.1`

**Comment by MikeHillberg** [comment]
Thanks for opening this. Until it's serviced, there's a workaround [in this comment](https://github.com/microsoft/WindowsAppSDK/issues/3117#issuecomment-1314945705).

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK.1.2.221116.1` has been released which fixes this issue.
		
Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2.221116.1/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221116.1)
