### ISSUE TITLE
ContentDialog wrong position on Window maximize/restore

### ISSUE THREAD

**Issue by davidegiacometti** [microsoft/microsoft-ui-xaml#7918]
### Describe the bug

ContentDialog defined in XAML and ContentDialog defined in code-behind behaves differently on Window maximize/minimize.

### Steps to reproduce the bug

1. Put a ContentDialog in XAML code
2. Call `.ShowAsync()` method in code-behind
3. Snap window or click (maximize/restore button)
4. The ContentDialog is moved but isn't centered

Working as expected if the ContentDialog is defined in the code-behind.

### Expected behavior

ContentDialog is centered on the window.

### Screenshots

![Bug](https://user-images.githubusercontent.com/25966642/201536861-20f1a67f-3d44-4f97-a187-5136fb812889.gif)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.0

### Windows version

Windows 10 (21H2): Build 19044

**Comment by gabbybilka** [comment]
Does this also repro on window size changes? Curious if related to #4831

**Comment by davidegiacometti** [comment]
Doesn't repro on window resizing but only on maximize/restore.

**Comment by KWodarczyk** [comment]
Any workarounds for ContentDialogs created in xaml ?

**Comment by davidegiacometti** [comment]
Still happening with latest stable 1.3.230602002 and latest preview 1.4.230628000.

**Comment by ranjeshj** [comment]
This is the same issue as https://github.com/microsoft/microsoft-ui-xaml/issues/7401. Let's use that as the primary bug.
