### ISSUE TITLE
Windows.Storage.BulkAccess.FileInformationFactory.GetVirtualized* functions do not work with WinUI3 

### ISSUE THREAD

**Issue by anup-das** [microsoft/microsoft-ui-xaml#7919]
### Describe the bug

The following functions
FileInformationFactory.GetVirtualizedItems
FileInformationFactory.GetVirtualizedFilesVector
FileInformationFactory.GetVirtualizedFoldersVector

do not work in WinUI3 (Desktop) 

### Steps to reproduce the bug

Trying to bind the returned result to a WinUI 3 control results in an exception. See attached simple app source code to repro the issue

[Bug Repro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10002721/Bug.Repro.zip)

### Expected behavior

The API's should work as they do under UWP

### Screenshots
![WinUI 3 App Exception](https://user-images.githubusercontent.com/63170829/201654984-489fd443-b5c1-4b5c-b38b-c21255bcd122.png)

_No response_

### NuGet package version

WinUI 3 - Windows App SDK 1.2.0

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Jaiganeshkumaran** [comment]
This is probably because these methods return objects implementing interfaces in UWP XAML and not WinUI 3. You could workaround it by creating a wrapper that implements the WinUI 3 interfaces.

**Comment by anup-das** [comment]
@Jaiganeshkumaran Thanks. Can you point me to some source code to achieve this ? This does not look trivial to me since I need it in C++

**Comment by anup-das** [comment]
Narrowed down the issue further. FileInformationFactory is not the issue. Hence closing this.
See https://github.com/microsoft/microsoft-ui-xaml/issues/7927

**Comment by anup-das** [comment]
Reopening as this is still an issue. I was confused as there are multiple issues here especially when using C++/WinRT.  The API provided by MS does not work with WinUI 3 controls.
