### ISSUE TITLE
Proposal: ProgressDialog Control

### ISSUE THREAD

**Issue by shaggygi** [microsoft/microsoft-ui-xaml#792]
# Proposal: Add ProgressDialog Control
Would be nice to have control similar to MahApps ProgressDialog.  See link below for details.

https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/Dialogs/ProgressDialog.xaml

## Summary
Instead of creating custom logic/UI, it would be nice to have a native control to perform basic progress UI and updates.

**Comment by YuliKl** [comment]
Hi @shaggygi, thank you for the proposal. Can you elaborate a bit on what you're looking for? Is a ProgressBar sufficient for the "basic progress UI" requirement? What kind of updates would you expect the control to handle?

**Comment by mdtauk** [comment]
I know with Windows phone, WinRT, and UWP apps, the general thinking is not to block the UI thread, and to keep progress bars for actions in the app, and allow the user to continue using the app.

A ProgressDialog seems like it would be modal, and stop the app being used whilst progress continues.

You could also use a ContentDialog with a progress bar and message on it, but that requires wiring up the logic yourself.

**Comment by shaggygi** [comment]
@YuliKl Thanks for reply.  The ProgressDialog is a bit more as it provides a dialog to up UI with things such as text along with a ProgressBar.  You can see an example of the ProgressDialog [here](https://mahapps.com/controls/dialogs.html).

@mdtauk MahApps also provides a [ProgressDialogController](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/Dialogs/ProgressDialogController.cs) where it allows the main app (or parent window) to communicate to the ProgressDialog along with canceling if needed.

**Comment by YuliKl** [comment]
@shaggygi, I think what you're proposing is already relatively straight-forward to create using a [ContentDialog](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs). Yes, every app that wanted to show a progress dialog would need to set more than just a string as ContentDialog's content, but the work required is pretty straightforward. 

Given our [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md), I don't think we can prioritize spending time implementing a feature that is already enabled.

**Comment by shaggygi** [comment]
@YuliKl Understood.  Thanks for taking some time to review.  I'll go ahead and close for now.

**Comment by YuliKl** [comment]
> What if you could add ContentDialogs to the app, via File > New Item, and there were templates or boilerplate options, without making specific controls for Progress and Login UX?

You can already add ContentDialog as a new item.
![image](https://user-images.githubusercontent.com/13142665/58978630-138c3f00-8781-11e9-8ef6-2a3da61bcda1.png)

As far as specific templates, that seems like a great suggestion for https://github.com/microsoft/WindowsTemplateStudio

**Comment by mdtauk** [comment]
> > What if you could add ContentDialogs to the app, via File > New Item, and there were templates or boilerplate options, without making specific controls for Progress and Login UX?
> 
> You can already add ContentDialog as a new item.
> ![image](https://user-images.githubusercontent.com/13142665/58978630-138c3f00-8781-11e9-8ef6-2a3da61bcda1.png)
> 
> As far as specific templates, that seems like a great suggestion for https://github.com/microsoft/WindowsTemplateStudio

My comment was about providing different ContentDialogs with the code and UI for making a Progress Dialog, or a Login Dialog - and the developer can then wire it all up.

But I still think displaying a dialog which locks the app while progress is made is not ideal for modern apps.

Windows Phone used to provide a system progress bar in the Status Bar which would display without locking the app.

![image](https://user-images.githubusercontent.com/7389110/58978931-d0ec5600-87c4-11e9-995e-1e5dc2eba847.png)

Perhaps something like this should be the guidance for displaying progress of a recently invoked action.
