### ISSUE TITLE
Setting the RenderTransformOrigin before Rotation of an Image results in a System.UnauthorizedAccessException.

### ISSUE THREAD

**Issue by aljohnston112** [microsoft/microsoft-ui-xaml#7925]
### Describe the bug

I have this code
           
 ```
                var sourcePath = Path.GetFullPath(
                Path.Combine(
                    Path.GetDirectoryName(Assembly.GetEntryAssembly().Location),
                    fileUrl
                    )
                );
                var file = await StorageFile.GetFileFromPathAsync(sourcePath);

                using IRandomAccessStream fileStream = await file.OpenReadAsync();
                BitmapImage bitmapImage = new();
                bitmapImage.SetSource(fileStream);
                
                var image = new Image();
                image.Source = bitmapImage;
                image.Rotation = 180; 
```
The Image rotates, but the position of the Image moves outside of the bounds of the spot in the Grid it is in, so I see that I can try to set the origin to midway and try this
```
                var sourcePath = Path.GetFullPath(
                Path.Combine(
                    Path.GetDirectoryName(Assembly.GetEntryAssembly().Location),
                    fileUrl
                    )
                );
                var file = await StorageFile.GetFileFromPathAsync(sourcePath);

                using IRandomAccessStream fileStream = await file.OpenReadAsync();
                BitmapImage bitmapImage = new();
                bitmapImage.SetSource(fileStream);
                
                var image = new Image();
                image.Source = bitmapImage;
                image.RenderTransformOrigin = new Point(0.5, 0.5);
                image.Rotation = 180;
```
The last line here results in the exception with Message = "Access is denied. (0x80070005 (E_ACCESSDENIED))", Source =" WinRT.Runtime", and StackTrace = 
"at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
 at Microsoft.UI.Xaml.UIElement.set_Rotation(Single value)"
   

### Steps to reproduce the bug

1. Try out the snippets of code above.

### Expected behavior

I expect the Image to be rotated 180 degrees around the center.

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

WindowsApppSDK is 1.2.221109.1

**Comment by castorix** [comment]
It works by using _TransformGroup_, like I did in [MainWindow.xaml.cs](https://github.com/castorix/WinUI3_DirectShow_Capture/blob/master/MainWindow.xaml.cs)
(you can also replace _ScaleTransform_ by _RotateTransform_ with .Angle = 180)
