### ISSUE TITLE
Sometimes blank microsoft login page comes while trying to login using AzureAuth

### ISSUE THREAD

**Issue by AnzarN** [microsoft/microsoft-ui-xaml#7926]
### Describe the bug

![blank login screen](https://user-images.githubusercontent.com/118263613/201892529-b9c7dbc5-6df9-40a3-b2d7-ab7d9762c57a.png)

Sometimes while login with Microsoft login page blank screen appear with no textbox and label to enter password.

### Steps to reproduce the bug

try to login with Azure Auth -> Microsoft Login screen should appear -> Sometimes that login screen is blank with no textbox to enter password.

### Expected behavior

Microsoft Login screen should always appear properly with textbox and label, so user can enter password properly.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (21H2): Build 19044

**Comment by Scottj1s** [comment]
@AnzarN, I'm closing this issue as it's not related to WinUI - maybe followup with [other related reports](https://answers.microsoft.com/en-us/search/search?SearchTerm=blank%20login%20page&tab=&status=all&advFil=&IsSuggestedTerm=false&isFilterExpanded=undefined&CurrentScope.ForumName=&CurrentScope.Filter=&ContentTypeScope=&page=1&sort=Relevance&dir=Desc)
