### ISSUE TITLE
The "Package and Publish" context menu is missing in WinUI project

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#7928]
### Describe the bug

Missing the "Package and Publish" context menu in WinUI project
![image](https://user-images.githubusercontent.com/97647558/202125311-0807d64c-ae95-4d7b-8d5f-641da42d1e6c.png)

### Steps to reproduce the bug

Environment:
Affected build: 17.5.0 Preview 2.0 [33115.268.main]

1. Create a new C# Blank App, Packaged (WinUI 3 in Desktop) Project
2. Right click on project node and observe

### Expected behavior

Should have "Package and Publish" context menu in WinUI project

![image](https://user-images.githubusercontent.com/97647558/202125500-290cfddc-bd64-4a76-a3fb-2d3e42e97b1b.png)

### Additional context

1. Works fine in 17.3.6 and 17.4.0.
2. The issue is also reproduced in 17.5 P1.

**Comment by JanRajnoha** [comment]
Do you have any ETA on this bug?

**Comment by JanRajnoha** [comment]
@gabbybilka

**Comment by gabbybilka** [comment]
We are looking into this issue with the Visual Studio team, tracking internally with https://task.ms/40112544

cc: @evelynwu-msft & @Scottj1s for updates

**Comment by JanRajnoha** [comment]
Fixed in VS 17.5.0 Preview 2
