### ISSUE TITLE
TreeView: Binding doesn't seem to work

### ISSUE THREAD

**Issue by FrancoisM** [microsoft/microsoft-ui-xaml#793]
**Describe the bug**
If the source of a TreeView is set after the construction of the page, the ItemTemplates bindings doesn't seem to work.

**Steps to reproduce the bug**
Here is a [repro](https://github.com/FrancoisM/ReproTreeView).
When I set the Items in ctor the tree view displays well. If I set the items later, I only see two checkboxes.

**Expected behavior**
Wether I set the items in ctor or later should not matter.

**Version Info**
UWP 6.2.8
Targeting 17763, Min 17134

**Comment by jevansaks** [comment]
Interesting bug! @kaiguo can you see if this is a TreeView issue or a Binding issue?

**Comment by kaiguo** [comment]
@FrancoisM, I think this has been fixed by #43.

Looks like your repro project is not using NuGet package, if you switch over to NuGet the issue should be gone.

**Comment by FrancoisM** [comment]
Tks. I don't use the nuget package indeed. I'll try but I don't understand why I am supposed to. This is so confusing 🤔

**Comment by Felix-Dev** [comment]
> Tks. I don't use the nuget package indeed. I'll try but I don't understand why I am supposed to. This is so confusing

The fix by MS was done in December 2018 at which point the 1809 Windows SDK already shipped. If this fix was back-ported into the SDK, then you would only get it with the 1903 SDK and above. Since your app is targeting 1809 and below, the fix isn't available to you in the SDK and you have to use the WinUI nuget package to benefit from the it.

**Comment by FrancoisM** [comment]
I see. tks.
I cannot target 1809 yet as not installed in Azure pipelines agents. I'll use the nuget and revert to close the issue if solved.

**Comment by FrancoisM** [comment]
Ok it now works with the nuget package tks.

**Comment by Felix-Dev** [comment]
As a general rule: If you want to have the newest UWP control fixes you should always use the WinUI control (via nuget) instead of the corresponding Windows SDK control.
