### ISSUE TITLE
Winui3: Unable to get PointerPressed and PointerReleased event in TextBox UIElement

### ISSUE THREAD

**Issue by harshith187** [microsoft/microsoft-ui-xaml#7936]
### Describe the bug

Hi,

I have a grid where each cell is of type TextBox[In read-only mode]. I'm not able to capture the pointer pressed and the pointer released event in TextBox. I'm able to capture other pointer events as the pointer entered etc. Below is my sample grid.
![image](https://user-images.githubusercontent.com/29576770/202635134-8a31c6c0-d606-48e5-a11c-bf3498622360.png)
I Have discussed this in [Microsoft Forum](https://learn.microsoft.com/en-us/answers/questions/1072351/winui3-how-to-get-pointerpressed-and-pointerreleas.html), turns out this is a bug issue.

### Steps to reproduce the bug

1. Create a TextBox in XAML from winrt::Microsoft::UI::XAML namespace
2. Try to capture PointerPressed or PointerReleased Event

**Comment by kmahone** [comment]
In general, most control will internally handle pointer events for their own implementation and then mark them as handled so they don't end up being raised externally.

It is still possible to get access to these handled events using UIElement.AddHandler and setting the 'handledEventsToo' parameter to true.
