### ISSUE TITLE
Only one ContentDialog can be open per thread (even with multiple AppWindows)

### ISSUE THREAD

**Issue by stmoy** [microsoft/microsoft-ui-xaml#794]
**Describe the bug**

XAML has a limitation today of only being able to open one ContentDialog per thread at a time, meaning an app can’t show a modal dialog in two AppWindows at the same time.

If you try to open a second dialog on the thread you’ll get an error HRESULT, so the app can try/catch in most projections, but they don't really have a good alternative if they hit this case.

**Steps to reproduce the bug**

1. Create two AppWindows, each with a button that opens a ContentDialog.
2. Open the ContentDialog on AppWindow 1. 
3. Open the ContentDialog on AppWindow 2.
Result: Crash.

**Expected behavior**

Expected: ContentDialogs open modal to each AppWindow. 

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Agreed, this has come up as a pain point before. I don't know the original motivation but it seems like a restriction that we can remove.

**Comment by baochenw** [comment]
It looks not reasonable the WinUI3 supports multiple windows.
