### ISSUE TITLE
microsoft-ui-xaml  2.8.1 webview2 gamepad input

### ISSUE THREAD

**Issue by chen-gk** [microsoft/microsoft-ui-xaml#7945]
### Describe the bug

i use webview2 on uwp to show a website and use javascript to get gamepad input but isn't work

javascript code=>
window.addEventListener("gamepadconnected", (e) => {
  console.log("Gamepad connected at index %d: %s. %d buttons, %d axes.",
    e.gamepad.index, e.gamepad.id,
    e.gamepad.buttons.length, e.gamepad.axes.length);
});

this  javascript is working on chrome and old version webview, but it's not work on webview2

### Steps to reproduce the bug

1. create webview2 on uwp 
2. set webview2.source to website
3. website run javascript =>
window.addEventListener("gamepadconnected", (e) => {
  console.log("Gamepad connected at index %d: %s. %d buttons, %d axes.",
    e.gamepad.index, e.gamepad.id,
    e.gamepad.buttons.length, e.gamepad.axes.length);
});
4. connect xbox one to pc and click 

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.1

**Comment by Sentry-Thibault** [comment]
Hi guys, 
Maybe same problem [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4366#issuecomment-1939292626).
