### ISSUE TITLE
Question: WinUI3 - Windows.Current is null, then how to set mouse pointer position?

### ISSUE THREAD

**Issue by super-brian** [microsoft/microsoft-ui-xaml#7947]
### Describe the bug

Maybe similar to this question: https://github.com/microsoft/microsoft-ui-xaml/issues/2609
But here, it is focused on moving mouse pointer to a position.

For UWP, I did like this: 
`Window.Current.CoreWindow.PointerPosition = new Point(x, (y + 25.0) / scaleMultiplier);`
But VS complains that Window.Current is null.

From this issue, https://github.com/microsoft/microsoft-ui-xaml/issues/4152
I see that ProtectedCursor is there, but it is for the shape of mouse pointer.
Then, how can I move mouse pointer?

### Steps to reproduce the bug

1. Create new Blank App, Packaged (WinUI in Desktop) app
2. Open MainWindow.xaml.cs and try get Window.Current

### Expected behavior

Window.Current in Blank App, Packaged (WinUI in UWP) returns a window instance

**Comment by DarranRowe** [comment]
CoreWindow is [documented](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#core-unsupported-classes) to be outright unsupported in desktop applications. So yes, this is expected.

As for moving the mouse pointer, don't forget, you are now in desktop application land. This means that [SetCursorPos](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setcursorpos) is available. The .NET framework also has classes like [Cursor](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.cursor?view=netframework-4.8), or you could just platform invoke SetCursorPos.

**Comment by super-brian** [comment]
@DarranRowe Could you provide me with some sample code to do 'platform invoke' for WinUI (.Net6)?

**Comment by DarranRowe** [comment]
It is no different from using platform invoke in any other situation.

You first set up the class to reference the native function:
```
namespace Win32
{
    public sealed class Win32Invoke
    {
        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool SetCursorPos(int x, int y);
    }
}
```
and just call it:
`Win32.Win32Invoke.SetCursorPos(0, 0);`

There is nothing special about the namespace or class name used here. You can also use using to get rid of the namespace name as you normally can with C#. The function name needs to match the exported if you don't provide the entry point in the DllImport attribute though.
