### ISSUE TITLE
Layout error for simple XAML with ProgressBar

### ISSUE THREAD

**Issue by ajkennedy-HEC** [microsoft/microsoft-ui-xaml#7952]
### Describe the bug

Possibly related to #1441 and #477. A simple window with the following XAML will crash instantly on startup with a layout cycle error.

```
<Window
    x:Class="LayoutCrash.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

  <StackPanel Orientation="Horizontal">
    <ProgressBar MinWidth="200" Value="100" BorderThickness="3"/>
  </StackPanel>
</Window>
```

![image](https://user-images.githubusercontent.com/14296437/203404406-a679d624-c941-4d4e-aefd-3cbbd9cbb434.png)

The crash requires ProgressBar.Value to be large (98, 99 or 100 in my case) and BorderThickness to be greater than 0. It appears there is some layout fighting between the StackPanel and the ProgressBar with the BorderThickness.

My DPI is set to 125%, but a coworker was able to reproduce the issue with DPI set to 100%. I'm running this in Unpackaged mode.

### Steps to reproduce the bug

Start a fresh WinUI 3 project, and paste in the XAML above. Start the project and it should crash instantly with the exception in the screenshot above.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.1: 1.2.221116.1

### Windows version

Windows 11 (21H2): Build 22000

**Comment by anovik** [comment]
I have a XAML parsing error in WinUI3 project each time when ProgressBar is on the page, even no need for set a value or thickness. Had to remove them all. The same error is for ProgressRing.

**Comment by codendone** [comment]
A fix for this issue has just been completed for WinAppSDK 1.5. ProgressBar didn't handle if BorderThickness or Padding was set on it. Moving these properties up to a parent element would be a workaround on older builds.
