### ISSUE TITLE
'Suspending': is not a member of 'winrt::Microsoft::UI::Xaml::Application'

### ISSUE THREAD

**Issue by junglie85** [microsoft/microsoft-ui-xaml#7957]
### Describe the bug

According to the [docs](https://learn.microsoft.com/en-us/windows/uwp/launch-resume/suspend-an-app), I should be able to suspend and resume an app, but I get an error that `Suspending` is not a member of `Application`.

However, the `winrt/Windows::UI::Xaml` namespace doesn't seem to exist, but the `winrt/Microsoft::UI::Xaml` namespace does.

I'm using C++/WinRT with WinUI 3 and the Windows App SDK. How am I supposed to register a handler for suspending and resuming the application?

### Steps to reproduce the bug

```
MainPage::MainPage()
{
    InitializeComponent();
    Microsoft::UI::Xaml::Application::Current().Suspending({ this, &MainPage::OnSuspending});
}
```

### Expected behavior

Successfully register a handler for suspension events.

### Windows version

Windows 10 (21H2): Build 19044

**Comment by DarranRowe** [comment]
This is one of those cases where there is a fundamental difference in the process model here.
Even if packaged, the Windows App SDK/WinUI 3 uses the desktop process model, not the UWP CoreApplication model. This is also [documented](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/feature-mapping-table), the table gives [power/state notifications](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-power) as a replacement to suspend/resume.

It isn't a complete replacement though. There are some scenarios that you can't replicate without extraordinary measures. But your application doesn't have to passively wait for suspend/resume requests anymore. It must actively monitor the state and react to that.

**Comment by junglie85** [comment]
Thanks. I hadn't seen those documents so appreciate you sharing them.

What are the state notifications and how do they differ to power notifications?

**Comment by DarranRowe** [comment]
You shouldn't really think of them as separate entities. They come as a pair, much like how suspend and resume have to come together.

But if you really want a way to link them together, think about the monitor state, if it is on off or dimmed. This is a stated that is based upon power. You can technically class the battery state in this too. If it is discharged, charging, full or even not present as a state.
