### ISSUE TITLE
Loaded event for the controls is trigger when the item remove from the listview 

### ISSUE THREAD

**Issue by saiganesh-sakthivel** [microsoft/microsoft-ui-xaml#7958]
### Describe the bug

Loaded event for the controls is trigger when the item remove from the listview. It occurs when we off the Show animations in the windows (Go to the **Settings** - > **Ease to Access** -> turn off the **Show Animations in Windows** and turn off the **Show transparency in windows** and turn off **Automatically hide scroll bars in windows**). Rebuild the sample and run the sample. Add the items through the button click, the loaded event will trigger for the controls(TextBox and DatePicker) in the itemtemplate and remove the item, the loaded event will trigger(excepted behavior should not trigger at remove time) and also add the item again, this time the load event is not triggering and again remove the item, the loaded event is triggering (excepted behavior should not happened).

### Steps to reproduce the bug

1. Go to the **settings** -> **Ease to Access**
2. turn off the **Show Animations in Windows**, **Show transparency in windows** and **Automatically hide scroll bars in windows**.
3. Run the Sample [LoadedIssueinListView.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10076135/LoadedIssueinListView.zip)
4. Click the Add button.
5. Load event will call for the textbox and datepicker which is placed inside the ItemTemplate of Listview.
6. Click the remove button.
7. Load event is triggered for the textbox and datepicker.
8. Again click add button.
9. Load event is not triggered for the textbox and datepicker.

### Expected behavior

1. When Click the remove button, it should not trigger the load event for textbox and datepicker.
2. when click the add button for second time, it should trigger load event for textbox and datepicker. 

### NuGet package version

WinUI 3 - Windows App SDK 1.2.1: 1.2.221116.1

### Windows version

Windows 10 (20H2): Build 19042

**Comment by andreaslennartz** [comment]
This issue is still open with the latest release of Windows App SDK.  Events are not properly triggered in the ListView if Animations are turned off in Windows. Any updates if/when this is going to be fixed?

**Comment by saiganesh-sakthivel** [comment]
Hi Team,

Any update regarding this?

**Comment by ranjeshj** [comment]
@saiganesh-sakthivel Loaded and Unloaded on ListView's items are not likely to be reliable because ListView recycles the items. Use the ContainerContentChanging event instead to know when listview is reusing containers/recycling containers to do the appropriate setup/cleanup. See here - https://stackoverflow.com/questions/56204802/uwp-how-to-properly-recycle-items-in-listview
