### ISSUE TITLE
[WinUI][.NET 5.0.22] Latest stable 1.2.221116.1 Microsoft.WindowsAppSDK version does not support .NET 5.0.22 in VS 16.11.22

### ISSUE THREAD

**Issue by kanglinqian** [microsoft/microsoft-ui-xaml#7961]
### Describe the bug

Latest stable 1.2.221116.1 Microsoft.WindowsAppSDK version does not support .NET 5.0.22 in VS 16.11.22.
Have one error in Error List as “This version of WindowsAppSDK requires .NET 6+ and WinRT.Runtime.dll version 2.0 or greater”.
![image](https://user-images.githubusercontent.com/117792173/203754676-10cfc1ef-2ed2-44ce-bb77-b031e097dd04.png)

### Steps to reproduce the bug

Environment:
Affected Branch: d16.11
Affected Build: 33123.337

Steps to reproduce:
1.Create a C# Blank App, Packaged (WinUI 3 in Desktop)
2.In NuGet.Config add feed [https://pkgs.dev.azure.com/dnceng/internal/_packaging/5.0.504-servicing.22570.14-shipping/nuget/v3/index.json]  
3.Open *.csproj and change the TargetFramework to <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
4.Have one error in Error List

Workaround:
1.Right-click the project to open Manage NuGet Packages
2.Select Microsoft.WindowsAppSDK in Installed
3.Downgrade the version to 1.1.5

**Comment by kmgallahan** [comment]
.NET 5 support ended May 10, 2022.

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by hawkerm** [comment]
@kanglinqian you should update to .NET 6, as was mentioned .NET 5 is no longer in support. .NET 6 is the long-term serviced build.

**Comment by kanglinqian** [comment]
A warning prompt appears that it is not supported. NET6.0，want to ask, what .NET (3.1, 5.0, 6.0) does winui support on 16.11.22 Preview1?
![image](https://user-images.githubusercontent.com/117792173/205578538-da5b8e41-d108-41ff-adab-0b455bb0588a.png)
![image](https://user-images.githubusercontent.com/117792173/205578651-49cf5b6f-f68a-4146-9b5e-0283fa1586e3.png)

**Comment by bpulliam** [comment]
To stay on .NET 5 and VS 2019, you will need to stay on WinAppSDK 1.1.  Version 1.2 requires .NET 6 and VS 2022.
