### ISSUE TITLE
ms-appx should be able to refer to same project as it is used in.

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#7964]
My application resources look something like this: 

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <ResourceDictionary Source="ms-appx:///LIB/0 - Framework/zzz.xaml" />
                <ResourceDictionary Source="/1 - Container/3 - App/yyyyy.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

That works fine. The first entry references a directory in a class library project in the same solution (project name = "LIB"), the second entry refers to a directory in the app project. 

What should also work though, is this, where APP is the name of the app's project in the solution: 

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <ResourceDictionary Source="ms-appx:///LIB/0 - Framework/zzz.xaml" />
                <ResourceDictionary Source="ms-appx:///APP/1 - Container/3 - App/yyyyy.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

But it doesn't work! Instead, an unhandled exception occurs when XAML is trying to find and load the yyyyy.xaml file from the app. 

Not a biggie but it certainly cost me hours of debugging time given the lack of error messages before hitting the unhandled exception.

**Comment by evelynwu-msft** [comment]
@sjb-sjb I think you have an extra `/` in your problematic URI. Does it work if you specify `ms-appx://APP/1 - Container/3 - App/yyyyy.xaml` (note that there is no `/` immediately after the URI scheme)?

**Comment by sjb-sjb** [comment]
@evelynwu-msft i think you are saying that one can omit the “ms-appx:///APP” and it will work. That is exactly what I said in my posting, but the point is that if you DO specify “ms-appx:///APP” then it should work. Or at least generate a meaningful error message.

**Comment by evelynwu-msft** [comment]
@sjb-sjb

The primary drawback of your proposal is that it leads to resource URIs no longer consistently reflecting the logical layout of the resources within the package and the potential for aliasing conflicts. Suppose I have an app named `Emerald` and a library referenced by that app also named `Emerald`; not best practices to be sure but it's legal. Both projects contain a file named `themes\generic.xaml` that is marked as a PRIResource and so can be referenced via `ms-appx` URI. Per your proposal, the URI `ms-appx:///Emerald/themes/generic.xaml` is now ambiguous... is it referring to the file `themes\generic.xaml` belonging to the *app* project, or is it referring to the file `themes\generic.xaml` belonging to the *library* project?

That simply isn't a change we're going to make.
