### ISSUE TITLE
[UWP][Webview2]Return a new stream response in WebResourceRequested doesn't wrok

### ISSUE THREAD

**Issue by Panda-Sharp** [microsoft/microsoft-ui-xaml#7965]
### Describe the bug

Yesterday I created this new discussion > https://github.com/microsoft/microsoft-ui-xaml/discussions/7962
Asking for some help, today I spent some more time to investigate and I noticed that my code should work, in fact works in WPF and WinUI, but doesn't work in UWP. 

I tried to follow these suggestions:
- https://github.com/microsoft/microsoft-ui-xaml/issues/4600
- https://github.com/microsoft/microsoft-ui-xaml/issues/1967
- https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webresourcerequested?tabs=dotnet
but no luck

### Steps to reproduce the bug

The easiest way to reproduce, is cloning my min repro samples in this repo https://github.com/Panda-Sharp/WebView2WebResourceRquested
- WebView2WebResourceRquestedSample (UWP doesn't work)
- WebView2WebResourceRquestedWinUI (WinUI works)
- WebView2WebResourceRquestedWpf (Wpf works)

### Expected behavior

Able to replace the response in webview2 in UWP with a custom stream, like in WPF and WinUI

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.1

### Windows version

Windows 10 (21H2): Build 19044

**Comment by ArchieCoder** [comment]
I saw this behaviour a while ago. A fix would be really welcome!

**Comment by bkaankose** [comment]
This is a serious blocker for me as well. Not sure the team will fix it though.

**Comment by SeriousGeorge** [comment]
Yes, it would be great if the UWP CoreWebView2_WebResourceRequested would work. It just responds to nothing.
We have also Training-Courses zipped and encrypted (sensitive informations). In the old webview with the IUriToStreamResolver we could intercept each subsequent loaded file and decrypt it in memory .

In webview2 this is failing completely in UWP.

Any informations and/or progress on this?

**Comment by Panda-Sharp** [comment]
> Yes, it would be great if the UWP CoreWebView2_WebResourceRequested would work. It just responds to nothing. We have also Training-Courses zipped and encrypted (sensitive informations). In the old webview with the IUriToStreamResolver we could intercept each subsequent loaded file and decrypt it in memory .
> 
> In webview2 this is failing completely in UWP.
> 
> Any informations and/or progress on this?

we're in a similar situation, the only work around so far, would be to use our own httpserver implementation, but it's time and resources consuming

**Comment by IcySnex** [comment]
I came across this issue when porting my library over to UWP.
But in fact this is not an issue with WebView2 but rather UWP. The way you are converting your response stream to an `IRandomAccessStream` requested by the `WebView2.CoreWebView2.Environment.CreateWebResourceResponse` method is not valid.

Currently you are doing this:
```cs
var memoryStream = new MemoryStream(Encoding.UTF8.GetBytes("Moby"));
var cwv2Response = WebView2.CoreWebView2.Environment.CreateWebResourceResponse(memoryStream.AsRandomAccessStream(), 200, "OK", "Content-Type: text/plain");
```
But you have to do this:
```cs
var randomMemoryStream = new InMemoryRandomAccessStream();
await randomMemoryStream.WriteAsync(Encoding.UTF8.GetBytes("Moby").AsBuffer());
var cwv2Response = WebView2.CoreWebView2.Environment.CreateWebResourceResponse(randomMemoryStream, 200, "OK", "Content-Type: text/plain");
```

I also took the time to make a [pull request](https://github.com/Panda-Sharp/WebView2WebResourceRquested/pull/1) for your sample repo.

**Comment by Panda-Sharp** [comment]
@IcySnex thanks a lot I'll take a look, hopefully will work also in the main scenario, not only in the min repro, and help everyone.

**Comment by Panda-Sharp** [comment]
I can confirm that @lcySnex fix works, if anyone is interested to take a look I cleaned up the samples in my repo: https://github.com/Panda-Sharp/WebView2WebResourceRquested
