### ISSUE TITLE
Creating a MenuBar dynamically

### ISSUE THREAD

**Issue by bastecklein** [microsoft/microsoft-ui-xaml#797]
**Describe the bug**
When you create a MenuBar in XAML, everything works as expected.  When you create it in C# dynamically, or add a new MenuBarItem to an existing MenuBar, regular mouseover behavior does not work as expected.  

**Steps to reproduce the bug**
1. Create an empty MenuBar in XAML
<muxc:MenuBar Name="menuBar"></muxc:MenuBar>

2. Add items to the MenuBar using c#
Microsoft.UI.Xaml.Controls.MenuBarItem mainMenuBarHelp = new Microsoft.UI.Xaml.Controls.MenuBarItem();
mainMenuBarHelp.Title = "Help";
mainMenuBar.Items.Add(mainMenuBarHelp);
// etc, add several

3. When you open on MenuItem and mouse over to the next one, it does not automatically open the menu to the side of it.

**Expected behavior**
Mousing over from one menu to the next should automatically open them like it does when you create the control using XAML

**Version Info**

NuGet package version: 
2.1.190405004.2

 May 2019 Update (18362) Desktop

**Comment by mrlacey** [comment]
Additionally, if you have some items created in XAML and some in code-behind. The open item will move with the cursor for those created in XAML but stop once it opens any created from code-behind.

**Comment by mrlacey** [comment]
I started down that road but couldn't see anything different in what gets generated. I gave up because I reached the limit of my ability to debug this.
