### ISSUE TITLE
ListView (WinUI3) control occasionaly freezes until mouse is clicked on some other item

### ISSUE THREAD

**Issue by anup-das** [microsoft/microsoft-ui-xaml#7972]
### Describe the bug

I have implemented a file explorer like functionality in my app. The list of sub-folders are displayed in a listview control. 
Based on user actions in the UI, I have to completely remove all items in the ListView control and repopulate them. 

In testing i found that ListView control is freezing occasionaly ( 1 in 10 or times).  i.e. Items are showing normally but verical scrollbar is not visible when it is expected, moving mouse pointer / wheel has no effect - no highlighted item is shown). It remains in this state until I click somewhere else in the window or even outside the window after few seconds.

I have tried using x:Bind and directly populating the items of the control (code-behind) both have the same result.

### Steps to reproduce the bug

Populate ListViewControl and remove all items. Repeat this frequently based on some user action like clicking a button say 10 to 15 times and you should see this issue.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by anup-das** [comment]
Update: I ported the same code to C# and the issue seems to have gone! I suspect this to be a threading issue related to C++/WinRT co_routines implementation

**Comment by Scottj1s** [comment]
@anup-das Thanks for reporting.  If possible, please provide a minimal repro project.

**Comment by anup-das** [comment]
@Scottj1s I have made a minimal repro project to reproduce the issue as well as issue #7975 (currently disabled with #if 0 statement).

Instructions to repro:
1. The app currently reads the folders of Music library. So populate the Music library with lots of folders. You can modify this if you want with any location containing lots of folders with multiple levels of sub-folders. I run into this  issue 1 in 20 times with my music library of 2,116 folders :-)
2. Build the app
3.  Navigate to deeply nested folder levels and then use BreadCrumsBar control to go back to previous level

![image](https://user-images.githubusercontent.com/63170829/206677837-ba9efd79-6273-4abd-90ef-c5e6f5595613.png)

I run into the listview freezes issue with one of the following 1) icons do not refresh or 2) listview click is unresponsive or 3) moving the mouse wheel has no effect. 

Sometimes I need to just move the mouse below the minimize title bar button to trigger some messages in the application message queue after which the list view un-freezes :-)

This does not happen in C# which has a different implementation (Task and await) than C++/WinRT's co_await (co_routines). I would like to know what I am doing wrong. Thanks.

**Comment by anup-das** [comment]
Here is the source code ...
[Test.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10193807/Test.zip)

**Comment by sylveon** [comment]
I looked at your app and noticed that the Windows App SDK was out of date - I updated it and ran the app and cannot reproduce either of your issues. Is it also fixed on your side if you update the SDK?

**Comment by anup-das** [comment]
It took just 5 tries for me with the updated SDK for the ListView to freeze

**Comment by anup-das** [comment]
Unable to repro with 1.3 release
