### ISSUE TITLE
ItemsRepeater inside a tooltip only displays the first item

### ISSUE THREAD

**Issue by gary-89** [microsoft/microsoft-ui-xaml#7979]
### Describe the bug

An ItemsRepeater inside a tooltip displays only the first item

### Steps to reproduce the bug

1. Create a user control with the following code-behind:
```csharp
public string[] Source { get; } = { "string1", "string2" };
```

2. Add this to its XAML:
```xaml
<Button Content="Button">
    <ToolTipService.ToolTip>
        <ToolTip>
            <ItemsRepeater ItemsSource="{x:Bind Source}" />
        </ToolTip>
    </ToolTipService.ToolTip>
</Button>
```

### Expected behavior

All the items for the `ItemRepeater` source should be displayed.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.1: 1.2.221116.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by gary-89** [comment]
This appears to be a duplicate of #711, but I've provided code to reproduce, and the other issue seems to have been forgotten

**Comment by mikernet** [comment]
This is also the case for an ItemsRepeater inside a Flyout.

**Comment by kmahone** [comment]
Looks like the same underlying cause as: ItemsRepeater renders only the first item when no ScrollViewer in the visual tree under a popup #2349
