### ISSUE TITLE
Cannot use winui in a .net framework application in a XAML island

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#798]
**Describe the bug**

Using winui in a .net framework application (XAML island) does not work

**Steps to reproduce the bug**

1. Add winui nuget package
2. Observe that the Microsoft.UI.Xaml namespace is not present

Adding the .winmd and .dll files manually allows the application to build but it crashes because it cannot locate the ms-appx:///Microsoft.UI.Xaml/Themes/19h1_themeresources.xaml file.

**Expected behavior**

winui is usable in a XAML island

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml v2.2.190430003-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | X   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  X  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
@ocalvo Can you offer any advice here? I think this scenario should work, but I don't remember if all the tooling improvements you were looking into are in yet.

**Comment by michael-hawker** [comment]
We have a PR open on the toolkit [here](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/pull/119) to try and resolve this, but I believe the current approach breaks MSIX support, so I think it still needs more work.

**Comment by ocalvo** [comment]
These are 2 independent issues. Both are needed to improve the user experience with MUXC and Islands.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lhak** [comment]
Any idea when this issue will be resolved? I can get an older version of the winui library to work if I use it in a packing app (unpacked version does not work due to missing resources.pri file). However, the latest release crashes with a System.IO.FileNotFoundException and the following stack trace:

```
System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
Microsoft.UI.Xaml.Controls.XamlControlsResources..ctor()
```

**Comment by michael-hawker** [comment]
@lhak have you tried the most recent nuget packages from the toolkit for XAML Islands? There's [an example and instructions](https://github.com/marb2000/XamlIslands/tree/master/1903_Hands_On_Labs/Exercise01) that's kept up-to-date you can try too.

If you're still having issues, can you attach a sample project to an issue on [our repo here](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32).  Thanks!

**Comment by lhak** [comment]
@michael-hawker Yes, I used the most recent nuget package. The page you linked to explicitly talks about .net core. So far, I have been using .net framework. Do you know if winui is just not supported for .net framework, or if this is indeed a bug?

**Comment by lhak** [comment]
Just a quick update: winui v2.2.190822001-prerelease works again (but still only in a packaged app) if the files are manually copied to the project. However, one issue I also noted previously is that all reveal and acryllic effects are missing once the XamlControlsResources object is initialized.

**Comment by jingkecn** [comment]
> System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
> Microsoft.UI.Xaml.Controls.XamlControlsResources..ctor()

My colleague got the this exact issue, any idea?
