### ISSUE TITLE
XAML Compiler Causes Build Failures with x:Bind + C# Record

### ISSUE THREAD

**Issue by lzl1918** [microsoft/microsoft-ui-xaml#7983]
### Describe the bug

x:Bind does not sometimes work with record types where the following build error can occur:
```
XamlTypeInfo.g.cs: error CS8852: Init-only property or indexer '{Type}.{Property}' can only be assigned in an object initializer, or on 'this' or 'base' in an instance constructor or an 'init' accessor.
```

### Steps to reproduce the bug

1. Create a new WinUI project
2. Specify Microsoft.WindowsAppSDK=1.2.221116.1, Microsoft.Windows.SDK.BuildTools=10.0.22621.755
    * Not sure whether SDK version matters but just in case
3. Use the following code for MainWindow, and then get build errors.

MainWindow.xaml:
```xaml

<ListView ItemsSource="{x:Bind Items, Mode=OneWay}"/>
```
MainWindow.xaml.cs
```csharp
public record Item(int Property);
public sealed partial class MainWindow : Window
{
    private ObservableCollection<Item> _items = new ObservableCollection<Item>();
    public IList<Item> Items => _items;
}
```

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### IDE

Visual Studio 2022

**Comment by Marv51** [comment]
Seems pretty similar to this issue I filed a while back: #5315

**Comment by hoshiizumiya** [comment]
Same as #5315
