### ISSUE TITLE
Changing FlyoutShowMode does not take effect

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#7987]
### Describe the bug

Setting the `ShowMode` of a `Flyout` does not take effect. See the [pull request here](https://github.com/microsoft/WinUI-Gallery/pull/1133) for an example. Even setting it manually in xaml like this 
```xaml
                <Button Content="Click for flyout">
                    <Button.Flyout>
                        <Flyout x:Name="CustomFlyout" ShowMode="Transient">
                            <TextBlock Text="This is a flyout"/>
                        </Flyout>
                    </Button.Flyout>
                </Button>
```
I would still get `Standard` mode when the flyout is opened, as this suggests
```xml
            <local:ControlExample.Xaml>
                <x:String xml:space="preserve">
&lt;Button Content="Click for flyout"&gt;
    &lt;Button.Flyout&gt;
        &lt;Flyout ShowMode="$(ShowMode)"&gt;
            &lt;TextBlock Text="This is a flyout" /&gt;
        &lt;/Flyout&gt;
    &lt;/Button.Flyout&gt;
&lt;/Button&gt;
                </x:String>
            </local:ControlExample.Xaml>
            <local:ControlExample.Substitutions>
                <local:ControlExampleSubstitution Key="ShowMode" Value="{x:Bind CustomFlyout.ShowMode, Mode=OneWay}"/>
            </local:ControlExample.Substitutions>
        </local:ControlExample>
```

### Steps to reproduce the bug

See above

### Screenshots

![flyout](https://user-images.githubusercontent.com/42881734/205445348-270eb0d0-6adb-40ed-98b1-38ec295a4d29.gif)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by HO-COOH** [comment]
Still reproducible with WinUI 2.8.5 package.

**Comment by ranjeshj** [comment]
This repros in WinUI3. @HO-COOH good find.
