### ISSUE TITLE
[UWP] NotifyCollectionChangedAction.Add behaves differently while working with custom ObservableCollection

### ISSUE THREAD

**Issue by sethuramkumar** [microsoft/microsoft-ui-xaml#7993]
### Describe the bug

Exception throws when using AddRange() for custom observable collection and using OnCollectionChanged as below:
```
OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add,addedItems));

```

Same scenario works fine when OnCollectionChanged was used as below:
```
OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));

```

Created a custom class based on Observable Collection and declare a method "AddRange()" as below .

```
public class ObservableRangeCollection<TItem> : ObservableCollection<TItem>
{
    public void AddRange(IEnumerable<TItem> list)
    {
        if (list == null)
            throw new ArgumentNullException(nameof(list));

        IList addedItems = new List<TItem>();
        IList OldList = Items as List<TItem>;
        foreach (TItem item in list)
        {
            Items.Add(item);
            addedItems.Add(item);
        }
        // Exception case
        OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Add,addedItems));

        // working case
      //  OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
    }
}


```

Code used in Model:
```
public class Model
{
    public string Country { get; set; }

    public Model(string country)
    {
        Country = country;
    }
}
```
Code Used in ViewModel
```
public class ViewModel : INotifyPropertyChanged
{

    private ObservableRangeCollection<Model> _countries;

    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    public ObservableRangeCollection<Model> Countries
    {
        get { return _countries; }
        set
        {
            _countries = value;
            OnPropertyChanged("Employees");
        }
    }

    public ViewModel() 
    {
        Countries= new ObservableRangeCollection<Model>();
    }
}

```

Code used in Main Page:
```
<StackPanel Orientation="Vertical">
    <ListView Width="300" Height="150" Margin="3" ItemsSource="{Binding Countries}" BorderBrush=
        <ListView.ItemTemplate>
            <DataTemplate>
                <TextBlock Text="{Binding Country}"/>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
    <Button Content="Add Range" Click="Button_Click" Height="30" HorizontalAlignment="Center"/>
</StackPanel>

```
Code Behind:
```
private void Button_Click(object sender, RoutedEventArgs e)
{
    List<Model> list = new List<Model>
    {
        new Model("Austria"),new Model("Africa"),new Model("China")
    };
    viewModel.Countries.AddRange(list);
}

```

Why does OnCollectionChanged with NotifyCollectionChangedAction.Reset as parameter has to be raised for Adding items in the collection?

Note: Sample works fine when OnCollectionChanged() raised with NotifyCollectionChangedAction.Add, addedItems and starting index as parameter.
Exception occurs only when using the OnCollectionChanged with NotifyCollectionChangedAction.Add and addedItems.

### Steps to reproduce the bug

1. Declare Custom class based on ObservableCollection.
2. Declare a method to Add range of items and then raise OnCollectionChanged() with NotifyCollecitonChangedAction.Add and addedItems as parameter.

### Expected behavior

Exception should not be thrown, items should be properly added in the  collection.

### Screenshots

Exception Image:
![image](https://user-images.githubusercontent.com/92511047/205988563-72f7eee6-4527-464c-836b-2b1c8f8e4d24.png)

### NuGet package version

None

### Windows version

Windows 11 (21H2): Build 22000

**Comment by michael-hawker** [comment]
@DmitriyKomin tags were added but no comments/info about what is required here?

Would this maybe be related to what needs to be done to support https://github.com/dotnet/runtime/issues/18087 as well?
