### ISSUE TITLE
[16.11][WinUI] Show error 'UserControl1' does not contain a definition for 'InitializeComponent' when adding a user control to Class library(WinUI 3)

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#7998]
### Describe the bug

Error: 'UserControl1' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'UserControl1' could be found (are you missing a using directive or an assembly reference?)

### Steps to reproduce the bug

1. Open VS 16.11.21
2. Create a Class Library(WinUI 3 in Desktop)
3. Add new item: User Control
4. Open UserControl1.xaml.cs file

**Actual Result:** There are 2 errors in Error List.
**Error: CS1061** UserControl1' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'UserControl1' could be found (are you missing a using directive or an assembly reference?)

### Expected behavior

No error in Error List.

### Screenshots

![image](https://user-images.githubusercontent.com/97647558/206389422-4c61492f-2c47-4cfd-ae45-bfdbe974fcd1.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

TargetFramework: net5.0-windows10.0.19041.0
Nuget package version: WinUI3 - Windows App SDK 1.1.4 or 1.1.5

**Comment by TRadigk** [comment]
I think this is not an issue:

![grafik](https://user-images.githubusercontent.com/92845708/206839879-46e1969d-bbfc-4ff7-b7f8-6e96640ae603.png)
VS 16.11.21

But note that you might have to install Microsoft.Windows.CsWinRT at least in version 1.6.0 with the help of nuget.

**Comment by evelynwu-msft** [comment]
@XamlTest Does the error persist after you build the project? `InitializeComponent()` is generated during project build, and VS doesn't always immediately realize that a design-time build needs to be triggered.

**Comment by hassaanmasood** [comment]
This is a real issue. Not able to build the project. Even after restarting the VS, the InitializeComponent method is not being generated. On the XAML file, everything is fine and there is no error.

**Comment by Scottj1s** [comment]
@XamlTest It sounds like you're seeing an issue with design time builds being disabled? We cannot repro this.
@hassaanmasood Please open an issue if you're still seeing explicit build errors.

**Comment by XamlTest** [comment]
I tried on the Visual Studio 16.11.32, the issue does not repro any more, and also not repro on the 17.9 Preview 3 build.
