### ISSUE TITLE
NavigationView prevents scrolling in Content

### ISSUE THREAD

**Issue by wldevries** [microsoft/microsoft-ui-xaml#800]
**Describe the bug**
WinUI `NavigationView` is presented as a drop in replacement for the SDK `NavigationView`, but it behaves differently for scrolling elements inside it's `Content`. Scrolling on a `GridView` inside the `Content` of the SDK version works fine, but does not work in the WinUI version (sporadically it works for some reason).

**Steps to reproduce the bug**
1. Create UWP project for 1809
2. Add `NavigationView` with inside a `Frame` in its `Content`
3. Navigate the `Frame` to a page with `GridView`  with enough content to have a vertical scrollbar
4. Try scrolling
5. Replace the `NavigationView` with the WinUI 2.1 one.
6. Try scrolling

**Expected behavior**
Before and after updating to WinUI scrolling works.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml v 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by YuliKl** [comment]
@wldevries, thank you for reporting this issue. Can you confirm that there's no namespace mismatch happening in your app? Both the markup and code behind need to reference **Microsoft**.UI.XAML.Controls instead of **Windows**.UI.XAML.Controls.

**Comment by wldevries** [comment]
Yes, I am sure.

The namespace change is quite inconvenient since you also need the original namespace for `Page` and the like.

**Comment by jevansaks** [comment]
I haven't seen this issue either, and we use a WinUI NavigationView in the Xaml Controls Gallery and the scenario works fine there. @wldevries can you add a repro app? (Either zipped and attached to this issue or comment or point at a GitHub repo).

**Comment by YuliKl** [comment]
@wldevries, are you still seeing the problem? If so, can you point us to an app with the repro?
