### ISSUE TITLE
WinUI 3 app crashes when NavigationViewItem IsSelected="True" and built with WindowsAppSDK 1.2.221109.1 or later

### ISSUE THREAD

**Issue by j-2-3** [microsoft/microsoft-ui-xaml#8002]
### Describe the bug

I have a WinUI 3 app that used to work fine up until WindowsAppSDK ver. 1.2.220930.4-preview2 but crashes with 'Value does not fall within the expected range.' unhandled exception message when built with newer WindowsAppSDK.

The issue is with preselecting NavigationViewItem via IsSelected property (set to "True") in xaml when NavigationViewItem Content is something different than simple string:
(xaml angle brackets swapped for brackets just to have it displayed correctly here)

 [NavigationViewItem.Content]The text[/NavigationViewItem.Content]

works fine, 

but:

 [NavigationViewItem.Content]
      [TextBlock Text="The text"/]
 [/NavigationViewItem.Content]
 
 does not.

### Steps to reproduce the bug

1. Create WinUI 3 app using Template Studio for WinUI 'Blank' project type and 'Self-Contained' in the Features creator tab
 (actually i think any blank WinUI app will do)
2. Update Microsoft.WindowsAppSDK Nuget reference to version 1.2.221109.1 or 1.2.221116.1
3. Replace MainPage.xaml content (the top level grid) with the one from the attachment
4. Run the app in debug mode and observe the exception thrown (when run without debugger it just won't start)
[MainPage.zip](https://github.com/microsoft/WindowsAppSDK/files/10140634/MainPage.zip)

### Expected behavior

It should be possible to use the NavigationViewItem IsSelected property in xaml without restrictions to the NavigationViewItem Content

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022

**Comment by Fritierkelle** [comment]
It looks like this issue still exists in 1.4.
