### ISSUE TITLE
WinUI3 App crashed.

### ISSUE THREAD

**Issue by boxing-wang** [microsoft/microsoft-ui-xaml#8010]
### Describe the bug

WinUI 3 App with CommandBarFlyout crashed when it has SecondaryCommands or the number of PrimaryCommands is more than 7. 

### Steps to reproduce the bug

1. Create a new WinUI 3 desktop app using C++/WinRT.
2. Copy the XAML code from WinUI 3 Gallery sample.
3. Change the C# source code to C++ code.
4. Compile and run, the app crashed.

Am i doing something wrong.

### Expected behavior

App can run correctly like WinUI 3 Gallery.

### Screenshots

![bug](https://user-images.githubusercontent.com/34464852/206843544-712428fe-faa9-425b-831b-286946168343.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.1: 1.2.221116.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by zhuxb711** [comment]
Also meet this issue on my side. But not sure the root cause.

**Comment by zhuxb711** [comment]
I have two devices Windows 11 21H2 & Windows 11 22H2, only seen this issue on Windows 11 21H2

**Comment by zhuxb711** [comment]
I have upgraded the one which use Windows 11 21H2 to 22H2, the issue is still exists so not related to 21H2
