### ISSUE TITLE
WinUI 3 : Getting Memory leaks when using MFC regular DLL with WinUI 3 application

### ISSUE THREAD

**Issue by mavajikitl** [microsoft/microsoft-ui-xaml#8016]
### Describe the bug

Getting memory leaks when using MFC regular DLL with WinUI 3 application.
This leaks is getting only when I set Page via `window.content()` or `Frame.Navigate()` method and if I we don't set page to window content and only activate window, leaks will not come, but in our requirement both showing **Page** content and use of mfc dll is required.

I reproduce the issue in this sample project [MemoryLeakTestCPP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10227671/MemoryLeakTestCPP.zip)

This project is tested on Microsoft Visual Studio Professional 2019 ( Version 16.11.8 ) in Debug x86 environment.

Below is screenshot of output having leaks.

![memory-leak](https://user-images.githubusercontent.com/90607336/207584887-3c3c5570-f815-4c0a-a291-e26fe33eb9b0.png)

MainPage.xaml is looks like below, if we remove <Button> from it then one leak will be reduced, so I think leaks are getting due to no destruction of **Page**  
```
<Page>
    <StackPanel>
         <Button>Click me</Button>
    </StackPanel>
</Page>
```
From MFC DLL, for testing I only declare one object of class(CTestClass) from mfc dll in WinUI project.
DLL is linked via .lib in WinUI project. 

### Steps to reproduce the bug

1. Download the project having leaks from [MemoryLeakTestCPP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10227671/MemoryLeakTestCPP.zip)
2. Unzip and build it in Microsoft Visual Studio Professional 2019 ( Version 16.11.8 ) in Debug x86 environment.
3. Run the application in debug mode
4. Close the application 
5. Detected Memory Leaks will be show in **Output** tab.

### Expected behavior

Memory leaks should not be detected

### NuGet package version

WinUI 3 - Windows App SDK 1.2.1: 1.2.221116.1

### Windows version

Windows 10 (20H2): Build 19042

### Additional context

NuGet packages used in projects are:

Microsoft.WindowsAppSDK.1.2.221116.1
Microsoft.Windows.SDK.BuildTools.10.0.22621.755	
Microsoft.Windows.ImplementationLibrary.1.0.211019.2
Microsoft.Windows.CppWinRT.2.0.210806.1

**Comment by mavajikitl** [comment]
@kennykerr or @Scottj1s Can you please help in this ?

**Comment by mavajikitl** [comment]
@kennykerr or @Scottj1s Can you please help in this ?

**Comment by bpulliam** [comment]
This is not currently a priority due to size leaked.
