### ISSUE TITLE
ItemsRepeater renders items outside its control size when it has a large amount of items

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/microsoft-ui-xaml#8028]
### Describe the bug

``ItemsRepeater`` renders items outside its control size when it has a large amount of items. In my testing environment, I can reproduce this with 200,000 items. 

### Steps to reproduce the bug

1. Create a plain WinUI 3 app.
2. Add this code below:
3. Click the button and you'll see that items are rendered outside the control.

**MainWindow.xaml**
```xaml
<Window
    x:Class="ItemsRepeaterOutsideRenderingBugSample.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid RowDefinitions="Auto,*,*">
        <StackPanel Orientation="Horizontal">
            <NumberBox
                x:Name="ItemsCountControl"
                Value="200000" />
            <Button
                Click="Button_Click"
                Content="Create items" />
        </StackPanel>
        <ScrollViewer
            Grid.Row="1"
            BorderBrush="HotPink"
            BorderThickness="2">
            <ItemsRepeater x:Name="ItemsRepeaterControl" />
        </ScrollViewer>
        <TextBlock
            Grid.Row="2"
            Text="Bottom" />
    </Grid>

</Window>
```

**MainWindow.xaml.cs**
```csharp
using Microsoft.UI.Xaml;
using System.Collections.Generic;

namespace ItemsRepeaterOutsideRenderingBugSample;

public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
    }

    private void Button_Click(object sender, RoutedEventArgs e)
    {
        List<int> items = new();

        for (int i = 0; i < this.ItemsCountControl.Value; i++)
        {
            items.Add(i);
        }

        this.ItemsRepeaterControl.ItemsSource = items;
    }
}
```

### Expected behavior

Items should not be rendered outside the ``ItemsRepeater``.

### Screenshots

![image](https://user-images.githubusercontent.com/80524586/208375909-95102b49-9d3f-4264-bd98-310c14d80b24.png)

![image](https://user-images.githubusercontent.com/80524586/208376090-06ffe4ab-69d3-440e-b140-27684cba7937.png)

![image](https://user-images.githubusercontent.com/80524586/208376186-db8dccd8-46aa-4f16-902c-9192273a4940.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

``ListView`` has the same issue but it breaks with less items.

**Comment by AndrewKeepCoding** [comment]
[Here](https://github.com/AndrewKeepCoding/ItemsRepeaterOutsideRenderingBugSample) is a reproducible project.

**Comment by AndrewKeepCoding** [comment]
This is still reproducible in WindowsAppSDK v1.3.230602002.

**Comment by DmitriyKomin** [comment]
@AndrewKeepCoding, thank you for reporting this. Per internal investigation, this is due to a known DWM limitation and is unlikely to be fixed. Following are additional details, including a workaround:

This is the known DWM "2^21" sizing limitation.  The ScrollViewer content clipping gets out of whack starting in that extent neighborhood.

110399 items render properly. With 110400 items, the last one renders below the ScrollViewer's bounds.
Each item is 19px tall. So 110399 items == 2097581px, 110400 items == 2097600px.  As expected, we're in the 2^21 neighborhood. This is more than a decade old DWM limitation. 

Explicitly setting a Clip on the ScrollViewer does not address the issue:
```
        <ScrollViewer Width="150" Height="450">
            <ItemsRepeater x:Name="ItemsRepeaterControl"/>
            <ScrollViewer.Clip>
                <RectangleGeometry Rect="0,0,150,450"/>
            </ScrollViewer.Clip>
        </ScrollViewer>
```

Using the new ScrollView instead of the old ScrollViewer does get around the bug.
```
        <ScrollView Width="150" Height="450">
            <ItemsRepeater x:Name="ItemsRepeaterControl"/>
        </ScrollView>
```

**Comment by AndrewKeepCoding** [comment]
@DmitriyKomin Thanks for the details.
