### ISSUE TITLE
Is there anyway to force updating GUI during the code excute in UI thread

### ISSUE THREAD

**Issue by ruihuasun** [microsoft/microsoft-ui-xaml#8031]
### Discussed in https://github.com/microsoft/microsoft-ui-xaml/discussions/8030

<div type='discussions-op-text'>

<sup>Originally posted by **ruihuasun** December 20, 2022</sup>
I want to progammly select a new created item in treeview, however, the TreeViewItem/TreeViewNode of that item will not been built till the GUI update, also will not been built till the rootnode expand (if the rootnode is in collapsed state, but itemsource change).

The tree structure is:
rootnode
--node1
----subnode1
----subnode2
--node2

If I do something like that
```
rootnodeitem.NotifyPropertyChanged("ItemSouceBindData");      // It will update rootnode children.
treeview.Expand(rootnode);      // Try to make rootnode expand to make new TreeViewItem load
foreach(var node in rootnode.Children) treeview.Expand(node);
treeview.SelectedNode = treeview.NodefromContainer(treeview.ContainerfromItem(subnode1item));
```

Line3 and line4 are all useless, for after the `treeview.Expand(rootnode);`, node1.Children.Count=0, So `treeview.Expand(node)` will do nothing and `treeview.ContainerfromItem(subnode1item)` or `treeview.NodefromContainer(...)` will all return null.

So I wonder if I can do something like that
```
rootnodeitem.NotifyPropertyChanged("ItemSouceBindData");      // It will update rootnode children.
FoceRefreshGUI();
treeview.Expand(rootnode);      // Try to make rootnode expand to make new TreeViewItem load
FoceRefreshGUI();
foreach(var node in rootnode.Children) treeview.Expand(node);
FoceRefreshGUI();
treeview.SelectedNode = treeview.NodefromContainer(treeview.ContainerfromItem(subnode1item));
```

I try lots of things like use `await Task.Run(async () => { await Task.Delay(10000); });`, but it is hard to control the delay time and also it will not gurantee the GUI finish update during the delay time.

So I wonder is there anyway to force updating GUI during the code excute in UI thread?
Or Is there anyway to force treeview refresh to build all its new chilnodes?

Thank you very much if you have any idea</div>

**Comment by JohnnyWestlake** [comment]
Calling `.Measure(...,...)` on a UIElement will typically expand it's VisualTree

**Comment by ruihuasun** [comment]
After long time repeated test, I found this problem which I cannot programmly select/expand may not caused by GUI, but a known bug #7044 .

**Comment by ruihuasun** [comment]
> found this problem which I cannot programmly select/expand may not caused by UI not updating immediately, but a known bug

Thank u for ur answer! But it's a pity that it cannot solve the TreeView problem.

**Comment by ruihuasun** [comment]
I think TreeView is not a control mature enough for production use, considering there are lots of bugs in it. Really "lots of".

**Comment by ruihuasun** [comment]
For the bug still exists, I will mark it close for now.
