### ISSUE TITLE
WinUI Design Toolkit Bug: [descriptive bug title here]

### ISSUE THREAD

**Issue by rcmpgi** [microsoft/microsoft-ui-xaml#8034]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**

Windows.UI.Xaml.dll

**Describe the bug:**

OneDrive will not load on Windows 11 22H2. It crashes shortly after starting:
Faulting application name: OneDrive.exe, version: 22.238.1114.2, time stamp: 0x178b5ba0
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.963, time stamp: 0x89a1dc34
Exception code: 0xc000027b
Fault offset: 0x00000000005b116e
Faulting process ID: 0x0x2640
Faulting application start time: 0x0x1D915F2C68B7C20
Faulting application path: C:\Users\xxx\AppData\Local\Microsoft\OneDrive\OneDrive.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report ID: 0d648752-c07e-43c8-9752-2c21548c2d6a
Faulting package full name: 
Faulting package-relative application ID: 

**Version Info:**

10.0.22621.963

**Additional context:**

Possibly caused by the terrible security practice of putting executable files into user-writeable areas (%userprofile%\AppData\Local\Microsoft\OneDrive) and then these getting blocked by AppLocker. Even after increasingly dangerous AppLocker allow lists the problem persists. Uninstalling and re-installing OneDrive has not resolved the problem.

**Comment by gabbybilka** [comment]
This report is outside of the scope of this repo, I'd recommend opening a ticket on Feedback Hub with this issue.
