### ISSUE TITLE
MenuFlyoutItem's Text property isn't fast path

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#8038]
### Describe the bug

The title is pretty self explanatory: the Text property of MenuFlyoutItems in both MenuFlyouts and MenuBars are not fast path.

I'm not sure this is a bug or a design choice. I was going to make this a question, but it's not an option. So, in case it's a bug, this is it.

I'm also a little bit curious, because the Icon property is fast path, but not the Text property.

### Steps to reproduce the bug

1. Create a WinUI 3, packaged project;
2. Create a MenuBar and add some items; add a button with a MenuFlyout and add some items;
3. Add the debug code on the OnLaunched method in App.xaml.cs;
4. Run the app.

### Expected behavior

I was expecting the text in the items to be green, but they're not.

### Screenshots

![NotFastPath1](https://user-images.githubusercontent.com/50815710/209350586-2f47752b-a913-466a-9fc5-571896af49a7.png)
![NotFastPath2](https://user-images.githubusercontent.com/50815710/209350597-9c7351c9-c2bf-43ab-a63c-e3361a85e420.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by eduardobragaxz** [comment]
The label on SecondaryCommands in a CommandBar act the same.

**Comment by bpulliam** [comment]
This is unfortunate, but given our current backlog, not the highest priority since the text is rendering correctly.

**Comment by eduardobragaxz** [comment]
That's alright. To be honest, I was more curious than concerned :P
