### ISSUE TITLE
midiOutOpen fails for Microsoft GS Wavetable Synth for Packaged app

### ISSUE THREAD

**Issue by melanchall** [microsoft/microsoft-ui-xaml#8055]
### Describe the bug

Bug is created by suggestion from https://github.com/dotnet/maui/issues/12368.

Looks like WinUI has a bug which causes `midiOutOpen` system function return `1` (`MMSYSERR_ERROR`) for _Microsoft GS Wavetable Synth_ built in Windows Synth when an app is in Packaged mode. So it means it's impossible to use the synth in this case.

Please note that `midiOutOpen` works for any different type of a project (.NET Framework, .NET Core, .NET).

### Steps to reproduce the bug

1. Just open the solution from the sample repo: https://github.com/melanchall/maui-midioutopen-bug.
2. Run the app.
3. Click **'Click me'** button.

**Actual:** `midiOutOpen` fails with the result of `1` (I throw an exception to make it clear).

![image](https://user-images.githubusercontent.com/26361185/210148662-1e612fed-b69b-47d7-bcab-2f73a9bf4bef.png)

### Expected behavior

`midiOutOpen` returns `0` which means no errors occurred.

### NuGet package version

None

### Windows version

Windows 10 (21H2): Build 19044

**Comment by castorix** [comment]
I had referenced a similar issue  : [#2337](https://github.com/microsoft/WindowsAppSDK/discussions/2337)
in this test sample : [WinUI3_Midi](https://github.com/castorix/WinUI3_Midi)

**Comment by melanchall** [comment]
@gabbybilka Is there any chance someone will look into the issue in the near term?
