### ISSUE TITLE
ContentDialog shading not extending into titlebar

### ISSUE THREAD

**Issue by zoltanfGH** [microsoft/microsoft-ui-xaml#8060]
### Describe the bug

When the ContentDialog opens it fades the background with transparent gray color. But when the app is using `ExtendContentIntoTitlebar = true` the fading is not present in the titlebar, which created a weird look by interrupting the design.

### Steps to reproduce the bug

Open the Winui 3 Gallery app.
Make sure the app is using the ExtendsContentIntoTitleBar, to enable custom titlebar.
Create a ContentDialog with the sample show dialog button.

### Expected behavior

The background fading should extend into the titlebar also, if ExtendsContentIntoTitleBar is set to true.

### Screenshots

![extended](https://user-images.githubusercontent.com/35294063/210344819-a0e77a3a-e3b7-47ea-9be1-6c838b4eee92.png)
![normal](https://user-images.githubusercontent.com/35294063/210344835-f42e1033-78b8-4f06-bb3e-c19a35f50057.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Petrarca181** [comment]
Duplicate [](https://github.com/microsoft/microsoft-ui-xaml/issues/6534  )
Scroll down to solution.
