### ISSUE TITLE
Supporting cursor for button and other controls in WinUI 3

### ISSUE THREAD

**Issue by NandishNR** [microsoft/microsoft-ui-xaml#8062]
In WPF, we had support of cursor property for button and other controls. However, WinUI 3 don't have cursor property for any of the control. How this can be achieved

**Comment by castorix** [comment]
You can call _set_ProtectedCursor_ with _System.Reflection_

**Comment by NandishNR** [comment]
I have to use it in XAML code at UI level and in styles as well like below. Migrating project from WPF to WinUI3 and it's not be possible in most of the cases to set_ProtectedCursor in code level.

`<Style TargetType="Button" x:Key="loginBtn" BasedOn="{StaticResource hoverBtnStyle}">
        <Setter Property="Cursor" Value="Hand" />
        <Setter Property="FontWeight" Value="Medium"/>
        <Setter Property="FontSize" Value="12"/>
</Style>`
and
`<Button Margin="0,0,10,0" Cursor="Hand" Command=""/>`

**Comment by NandishNR** [comment]
Any update on the ticket request? Please do provide an update. It was nice/flexible feature in WPF and difficult to handle this in code behind as most of the style sits in resource dictionary.

**Comment by vmiguelangmsft** [comment]
> Handled by creating custom control and using pointer entered event.

would you mind sharing an example I'm using winui 3 sdk 1.6
