### ISSUE TITLE
ListView Default Keyboard Accelerators

### ISSUE THREAD

**Issue by ferrariofilippo** [microsoft/microsoft-ui-xaml#8063]
### Describe the bug

Currently, `ListView` handles  `Ctrl + Alt + A` (or equivalent) by default, selecting all its items. This is a problem since, if the listview contains editable items (such as `TextBox`es), the user can't enter specific characters, such as Ā (`Ctrl + Alt + A` - Latvian Keyboard Layout).

### Steps to reproduce the bug

1. Press `Ctrl + Alt + A` on a `ListView`
2. See that all items are selected

### Expected behavior

When the user presses `Ctrl + Alt + A` (or `AltGr + A`), listview should not handle `KeyboardAccelerator`

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by JJBrychell** [comment]
The ListView control was looking to see if the control key was pressed to determine its accelerators, but it wasn't looking to see if any other modifier was pressed as well.

The fix is in and projected for the 1.5 release.
