### ISSUE TITLE
Default C++ WinAppSDK with WAP app project crashes at startup with "Class not registered"

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#8065]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Default-C-WinAppSDK-with-WAP-app-proje/10233364)._

---

VS 17.5.0 Preview 2 (no problems on 17.4.3)
WinAppSDK C++ template extension version 1.2.221109.1
WinAppSDK 1.2.221209.1
Microsoft.Windows.SDK.BuildTools 10.0.22621.755

File -> New Project -> C++ Blank App packaged with WAP
Ensure the Package project is selected to start.
F5 -> crash
 
![image.png](https://aka.ms/dc/image?name=Bf2d4bd404fed46e0bfd6404b667fe0bf638070052254891522_20221218-160705-image.png&tid=f2d4bd404fed46e0bfd6404b667fe0bf638070052254891522)

Turns out WinUI winmd is not being copied 
Looking at the vs.appxrecipe, this line present in a PC with VS 17.4.3, is not present on the PC using latest VS preview (17.5 preview 2)
 
![image.png](https://aka.ms/dc/image?name=B7d0dd3cb5bb743fea23c86b87ee13795638070052319585107_20221218-160711-image.png&tid=7d0dd3cb5bb743fea23c86b87ee13795638070052319585107)

---
#### Feedback Bot on 12/19/2022, 00:16 AM: 

(private comment, text removed)
#### Abby Zhang [MSFT] on 12/19/2022, 11:53 PM: 

(private comment, text removed)
#### Alexander Sklar on 12/21/2022, 04:02 PM: 

(private comment, text removed)
#### Feedback Bot on 12/21/2022, 10:00 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by asklar** [comment]
@bpulliam @codendone looks like i don't have permissions to reactivate this - mind reopening this? @sylveon just ran into it themselves.

**Comment by sylveon** [comment]
I opened #8915
