### ISSUE TITLE
ColorPicker eating a lot of CPU and preventing App from closing when outside of the debugger

### ISSUE THREAD

**Issue by danielgruethling** [microsoft/microsoft-ui-xaml#8079]
### Describe the bug

When the application is compiled and executed outside of the debugger showing a color picker will prevent that application from closing normally and increase CPU usage drastically once you try to close it. For my machine it will rise from 0% usage to hover around 20%.

### Steps to reproduce the bug

1. Compile the included project.
2. Open the executable outside of the debugger.
3. Change the color.
4. Close the application by clicking the X in the menu bar.
5. Observe a rise in cpu usage and a task that is not closing in the Task-Manager.

### Expected behavior

Simply having a ColorPicker in the application should not prevent it from closing nor increase the cpu load drastically when trying to close it.

### Screenshots

Application screenshot:
![grafik](https://user-images.githubusercontent.com/31628469/211299153-0d0c1195-87a3-4a76-9d55-42b1343e9303.png)

Usual CPU load:
![grafik](https://user-images.githubusercontent.com/31628469/211299257-071edd8d-0cff-4269-8e30-0c2909780523.png)

CPU load when trying to close the application:
![grafik](https://user-images.githubusercontent.com/31628469/211299348-434cfa05-aa04-44ad-a984-a0fdef5e0c75.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Here is some example code which is the packaged sample project from the Visual Studio integration that I changed to a basic unpackaged and self contained application only showing a ColorPicker.
[ColorPickerExample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10372750/ColorPickerExample.zip)

The outlined line is the only code change:
![grafik](https://user-images.githubusercontent.com/31628469/211516282-61dc71eb-a4e6-42a7-ba69-316c8dadf00d.png)

The outlined lines are the 2 options added to the csproj:
![grafik](https://user-images.githubusercontent.com/31628469/211516634-1c0cbb86-2096-4ea1-b518-688140f78333.png)

**Comment by jschwizer99** [comment]
This closing issue may be related to the crash at the exit caused by the colorpicker under Windows 10 as reported in https://github.com/microsoft/microsoft-ui-xaml/issues/7239. See also details in https://github.com/microsoft/microsoft-ui-xaml/issues/7239#issuecomment-1320957451.

**Comment by gabbybilka** [comment]
#7239 was resolved with 1.2.3, is this also fixed?

**Comment by danielgruethling** [comment]
I updated the WindowsAppSDK Nuget package to 1.2.230118.102 and this seems to be fixed.
