### ISSUE TITLE
When the DropDownButton/MenuBar control popup content,the back shadow will flash twice

### ISSUE THREAD

**Issue by wuyang26** [microsoft/microsoft-ui-xaml#8080]
### Describe the bug

environment:windows11/WinUI 3  Gallery/WinAppSDK 1.2
When click the DropDownButton or MenuBar control,popup content the back shadow animation will flash twice,Or from the invisible to the visible twice,Other controls such as Combobox flash only 1 time.

### Steps to reproduce the bug

1.Run WinUI 3 Gallery
2. Click DropDownButton 
3. when the control popup,you can see the the back shadow animation will flash twice,Or from the invisible to the visible twice

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by eduardobragaxz** [comment]
Seems to have been fixed in the latest update.

**Comment by DmitriyKomin** [comment]
We made fixes in this area in WinAppSDK 1.4. The shadow animation for DropDownButton looks correct in latest WinUI3 Gallery.
