### ISSUE TITLE
WinUI Control layout Bug: Number box control with Clear all (X) button overlapping inline SpinButtons

### ISSUE THREAD

**Issue by mimtiaz3555** [microsoft/microsoft-ui-xaml#8081]
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**
Number Box Control with Spin Buttons

**Describe the bug:**
The NumberBox control in an initially collapsed container has it's Clear All (X) button overlapping with inline Spin Buttons. The issue still exists in the 2.8.2 version. 

**Version Info:**
Microsoft.UI.XAML: 2.8.2

![image](https://user-images.githubusercontent.com/109691760/211862292-686d5a57-13b9-4e92-9149-1a2aca81420e.png)

**Comment by sjb-sjb** [comment]
Another concern with the NumberBox control is that setting the Background to Transparent does not make the control transparent. 

I tried copying in the NumberBox template from generic.xaml but when I ran it (without modification) I got an exception.
