### ISSUE TITLE
TreeView: IsSelected binding doesn't seem to work from View Model to View.

### ISSUE THREAD

**Issue by FrancoisM** [microsoft/microsoft-ui-xaml#809]
**Describe the bug**
Binding IsSleected in the ItemTemplate of a TreeView has no effect from View Model to View.

**Steps to reproduce the bug**
Here is a [repro](https://github.com/FrancoisM/ReproTreeView).

**Expected behavior**
When I set IsSelected to true on my view model, the box should be checked but it isn't.

**Version Info**
Targeting 17763

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.2

**Additional context**
There is already a similar [issue](https://github.com/microsoft/microsoft-ui-xaml/issues/125) open but if focus on binding from view to view model (which seems to work on my side) whereas I think the binding is broken from view model to view..

**Comment by FrancoisM** [comment]
I think I understand the reason of what I observe.
Until a node is ex

**Comment by jevansaks** [comment]
@kaiguo this sounds like a dupe, maybe we were tracking it as an internal issue? Either way, can you take a look?

**Comment by FrancoisM** [comment]
Hello,

I upgraded to 2.1.19 but issue remains.
Did you manage to reproduce with my sample?

**Comment by kaiguo** [comment]
Yes, I was able to repro the issue but we don't have a fix for this yet.

You can use this new selection APIs as workaround: https://github.com/microsoft/microsoft-ui-xaml-specs/pull/31/files?short_path=81ff309#diff-81ff3094337017f74d91702b19e8750c. They will be available in 2.2.

**Comment by kaiguo** [comment]
This has the same root as #125, closing as dupe.
