### ISSUE TITLE
Unhandled exception when constructing more than one MediaPlayerElement

### ISSUE THREAD

**Issue by LemmingEm** [microsoft/microsoft-ui-xaml#8090]
### Describe the bug

When more than one MediaPlayerElement is constructed with the same or different network files set as the media source, an unhandled win32 exception may be thrown before both controls finish loading.

The unhandled exception is not always thrown and on some occasions both controls will finish loading and behave as expected.

It has not been possible to reproduce this issue when a single MediaPlayerElement is constructed.

### Steps to reproduce the bug

1. Clone sample repo: https://github.com/LemmingEm/MediaPlayerElement
2. Build solution and start debugging

If an unhandled win32 exception does not occur before both MediaPlayerElements have loaded, stop debugging and retry. An unhandled win32 exception will occur within 10 attempts.

A dump file has been uploaded here: https://drive.google.com/file/d/1a05SDQ3eZAlCp90oj9_rHbngRRf8k50A/view?usp=sharing

### Expected behavior

An unhandled exception should not be thrown when more than one MediaPlayerElement is constructed with network files set as the media source.

### Screenshots

<img width="1921" alt="UnhandledException" src="https://user-images.githubusercontent.com/121949959/211063281-0406656d-682a-443b-acfe-4021ffe6c4b2.png">

### NuGet package version

Windows App SDK 1.2.2: 1.2.221209.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

11th Gen Intel Core i7
NVIDIA GeForce RTX 3080 Ti
32GB RAM

**Comment by DominicMaas** [comment]
Also encountered this recently. Couldn't repro, but on one launch of my application it threw an exception. 

AMD Ryzen 5 5600X (I believe)
NVIDIA GeForce RTX 3070
32GB RAM

**Comment by DmitriyKomin** [comment]
We made targeted fixes in this area in WinAppSDK 1.4. Please let us know if you are still seeing this issue.
