### ISSUE TITLE
[Arm64][WinUI] Cannot show application after run Packaged WinUI 3 project in x86 configuration successful

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8093]
### Describe the bug

Cannot show application after running Packaged WinUI 3 project in x86 configuration successful.

### Steps to reproduce the bug

1. Create C# Blank App, Packaged with Windows Application Packaging Project(WinUI 3 in Desktop)
2. Use the default configuration: Debug & **x86**
3. F5 to run the project
4. After running successfully, no application display.

**Expected Result:**
Should pop up running application.

**Actual Result:**
There is no application after waiting 1-2 minutes.

### Screenshots

![WinUI3](https://user-images.githubusercontent.com/97647558/212315810-ea0fa125-c06e-4d32-84fb-b98e9bfae4ab.gif)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This issue only reproduced on Arm 64 machine, C# Packaged WinUI 3 project, Win11 x86, not reproduce on x64, Arm64.

**Comment by DarranRowe** [comment]
Well, with Visual Studio 17.4.4, Windows App SDK 1.2.2 and with a C++ project, I don't see this problem. The default project runs without any issue on my Surface Pro X.
Are you able to try the current release version of Visual Studio or perhaps .NET 7 to see if you have the same issues? This could be a Visual Studio or a .NET 6 issue after all.

**Comment by XamlTest** [comment]
I have tried with Visual Studio 17.4.4, Windows App SDK 1.2.2, .NET 7, Application work well. Maybe this is .NET 6 issue.

**Comment by XamlTest** [comment]
This issue also reproduced on 17.8 preview 3 with .NET 8 rc2.

**Comment by Scottj1s** [comment]
Additional findings:
I can repro on a Surface Pro X, targeting Windows App SDK [1.4.231219000](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.4.231219000)
I only repro when launching the app in a debugger - both Visual Studio and Windbg repro
I cannot repro launching the app outside a debugger (or via Ctrl+F5 in VS)
I cannot repro with a single-project app (not using the Windows Application Packaging project)

So this appears to be an issue launching an x86 WAP-based app on arm64 under the CLR debugger.   I was unable to generate a [CLR startup trace](https://github.com/dotnet/runtime/blob/main/docs/design/features/host-tracing.md) - the trace text file was 0 bytes.  But I do see what appears to be stack corruption in Windbg, attempting to load a DLL.  

I've opened an issue on the Visual Studio team to investigate further:
[Debug launch of x86 C# WinAppSDK WAP-based project hangs on arm64](https://developercommunity.visualstudio.com/t/Debug-launch-of-x86-C-WinAppSDK-WAP-bas/10575502?port=1025&fsid=036cb65a-ab68-4f32-8cf7-6659ecc7cb28&ref=native&refTime=1706728636210&refUserId=3ecae279-b085-41e5-8176-afdfb2972795)

**Comment by Scottj1s** [comment]
@XamlTest The debugger team is investigating, but has pointed out that with the WAP configuration solution, mixed debugging is the default (surprisingly).  If you don't need that, disabling native debugging should unblock you.

**Comment by Scottj1s** [comment]
Closing this issue as the .NET debugger team is now tracking it:
[Debug launch of x86 C# WinAppSDK project hangs on arm64](https://developercommunity.visualstudio.com/t/Debug-launch-of-x86-C-WinAppSDK-WAP-bas/10575502?port=1025&fsid=036cb65a-ab68-4f32-8cf7-6659ecc7cb28&ref=native&refTime=1706728636210&refUserId=3ecae279-b085-41e5-8176-afdfb2972795)

**Comment by XamlTest** [comment]
@Scottj1s Thanks for investigating, after changing Application process from "Mixed" to "Managed Only", it works.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/57736b4c-229f-4c57-8a15-c4061331b8f6)
