### ISSUE TITLE
UWP: Clicking inside a WebView component with a touch screen won't bring app to the foreground (i.e. doesn't focus)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#8096]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/UWP:-Clicking-inside-a-WebView-component/10246341)._

---
[severity:Other]
Hi,
We have a UWP application with a [WebView](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview?view=winrt-22621) component.
We found that the app doesn't gain focus by using a touch screen to click inside the webview element.
It happens with multiple PCs on Windows 11 22H2 (probably also happens on earlier versions).

Scenario:
1. Launch the UWP app
2. Click on another app so that the new app will be in the FG, and the UWP app will be in the background.
3. Using a touchscreen, click inside the Webview element of the UWP.

Expected:
UWP is focused and brought to the foreground.

Actual:
Touch event occurs but UWP app remains in the background.

Microsoft sample for WebView to reproduce with:
[XamlWebView.zip](https://aka.ms/dc/file?name=B5877137fdd5d47b682b31dd831502e1a638085235626176808_XamlWebView.zip&tid=5877137fdd5d47b682b31dd831502e1a638085235626176808)

---
#### Feedback Bot on 1/5/2023, 06:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by giladnoy** [comment]
Hi @gabbybilka 
Are there any updates about this issue?

**Comment by giladnoy** [comment]
Hey
Checking in if there are any updates on the matter.

**Comment by DmitriyKomin** [comment]
Unfortunately we are not investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)). If this is a blocker, please consider using the WebView2 control available in both WinUI 2.8 and WinAppSDK.
