### ISSUE TITLE
UWP - Can't host WebView2 in secondary view

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#8098]
In UWP, hosting a WebView2 instance in a secondary view while also having it in the main throws hresult_wrong_thread.

**Comment by DmitriyKomin** [comment]
@JaiganeshKumaran, thank you for reporting the issue. Unfortunately at this time we are not able to investigate WinUI2-specific issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).
