### ISSUE TITLE
Title Bar Buttons Smaller & Blurred

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/microsoft-ui-xaml#8102]
### Describe the bug

When using a custom title bar on a WinUI 3 desktop app, the Minimize, Maximize/Restore, and Close buttons appear smaller and blurred. Comparing to the standard title bar of Windows app SDK WinUI 3 desktop apps, the latter looks better and clearer.

### Steps to reproduce the bug

Start a new VS 2022 project using the C# Windows App SDK template:
![image](https://user-images.githubusercontent.com/77593544/213110992-85b6a9b2-b03b-4aa4-8ea1-996c84ff5968.png)

Run the project for the 1st time. A blank WinUI 3 app window should appear.
Next, define the custom title bar. Delete all code in the MainWindow.xaml file and replace them with these:
![image](https://user-images.githubusercontent.com/77593544/213111550-29a1e504-5c1b-4477-a1f2-41da0b03cac5.png)

On the MainWindow.xaml.cs file, add these two lines of code inside the constructor method:
![image](https://user-images.githubusercontent.com/77593544/213111813-e04ead1e-4c51-4bcd-b60b-f35f6cb75b68.png)

Build and run the project.

Here is a comparison:
![image](https://user-images.githubusercontent.com/77593544/213111905-4174afd7-4dcc-4af3-80e8-4c7f0180d4ae.png)

### Expected behavior

The 3 buttons, Minimize, Maximize/Restore, and Close, of an app having a custom title bar, should look and feel the same as the default ones (no custom title bar). They appear smaller and the glyphs appear to be scaled down resulting in a lower quality resolution (take a look at the close button); The X character or symbol appears blurrier and have thinner lines.

The over-all degraded visual quality of these buttons in a custom title bar makes users alienated thus resulting in poor user acceptance of Windows App SDK/WinUI 3 apps.

### Screenshots

![image](https://user-images.githubusercontent.com/77593544/213112380-8079cf98-4b64-433e-830a-215c8f707b6e.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DJRM2021** [comment]
Hi, any updates on this issue? Thanks!

**Comment by pratikone** [comment]
Now that Window.ExtendsContentIntoTitleBar is using appwindow titlebar. This should be gone. if you continue to see this, do comment here and I will re-open the bug.
