### ISSUE TITLE
Custom Title Bar Does not honor Windowing classes

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/microsoft-ui-xaml#8105]
### Describe the bug

When a Windows App SDK WinUI 3 desktop app is using a custom title bar, in the case of using windowing classes, whatever you do with the presenter class, it will not be honored by WinUI.

As an example, trying to set IsMaximizable and IsMinimizable on an OverlappedWindowsPresenter class does nothing if the app is using a custom title bar.

### Steps to reproduce the bug

Create a VS 2022 project using the Windows App SDK / WinUI 3 Desktop App template.
![image](https://user-images.githubusercontent.com/77593544/213138037-4cbd96c5-2257-4ece-98c5-6b97cdb91dfd.png)

On the MainWindow.xaml file, define your custom title bar element:
![image](https://user-images.githubusercontent.com/77593544/213138096-619e6523-29ec-4fc8-bd9c-f392fd26b3ab.png)

On the MainWindow.xaml.cs file, add the following inside the constructor method:
![image](https://user-images.githubusercontent.com/77593544/213138443-738a3c34-0bb6-4438-80c0-9c18432e7e09.png)

Run the project. A small window should appear. Notice that the Minimize and Maximize buttons are present and displayed.
![image](https://user-images.githubusercontent.com/77593544/213138645-e2bfc3ba-2835-4fec-83a7-3a9799d78e5c.png)

### Expected behavior

The expected behavior is that when we use the IsMaximizable and IsMinimizable properties of the OverlappedWindowsPresenter class, the window should appear with only the Close button.On the example below, the ExtendsContentIntoTitleBar() and SetTitleBar() methods are commented out. 
![image](https://user-images.githubusercontent.com/77593544/213139251-8ae5a8bb-5d1b-44b1-8d14-7b917e1c9fa2.png)

AS you can see here, only the Close button is displayed.
![image](https://user-images.githubusercontent.com/77593544/213139612-44a5c3b5-2c88-4624-9ef0-ccc14ebd3862.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by gitpicard** [comment]
Can confirm that I have this issue as well.

**Comment by yki5000** [comment]
I think I had the same issue and had to hide the Maximize/ Minimize button in the app.xaml (code adapted from generic.xaml).

**Comment by JaiganeshKumaran** [comment]
You should set ExtendsContentIntoTitleBar from AppWindow.TitleBar instead of ExtendsContentIntoTitleBar in the XAML window. They don't both sync up right now for some reason.

**Comment by DJRM2021** [comment]
**Workaround**
Provided that a custom title bar is defined in the XAML file, on the C# code-behind file, do the following:

`OverlappedPresenter windowPresenter;`
`windowPresenter = (OverlappedPresenter)AppWindow.Presenter;`
`windowPresenter.IsMaximizable = false;`
`windowPresenter.IsMinimizable = false;`
`windowPresenter.IsResizable = false;`
`AppWindow.TitleBar.ExtendsContentIntoTitleBar = true;`

[AppWindowTitleBar.ExtendsContentIntoTitleBar Property](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindowtitlebar.extendscontentintotitlebar?view=windows-app-sdk-1.2#microsoft-ui-windowing-appwindowtitlebar-extendscontentintotitlebar)

**Comment by pratikone** [comment]
This is fixed now because WinUI 3 custom titlebar now uses appwindow titlebar
