### ISSUE TITLE
Building a project after deleting a XAML file results in an error

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#811]
VSF_TYPE_MARKDOWN**Repro steps**

1. File -&gt; New -&gt; WPF App (.NET Framework)
2. Build the project once
3. Delete MainWindow.xaml
4. Without saving, build the project

**Expected:** No error
**Actual:** error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unknown build error, 'Object reference not set to an instance of an object.'	WpfApp36

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/595515/building-a-project-after-deleting-a-xaml-file-resu.html
VSTS ticketId: 905549_
_These are the original issue comments:_

David Kean [MSFT] on 6/5/2019, 00:14 AM (10 hours ago): <p>This was also raised here: <a target='_blank' href="https://github.com/dotnet/project-system/issues/4728">https://github.com/dotnet/project-system/issues/4728</a></p>

Visual Studio Feedback System on 6/5/2019, 03:16 AM (7 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by mrlacey** [comment]
I suspect the correct repo for this is actually https://github.com/dotnet/wpf

However, I would not expect this to work.
The file is still referenced if the project has not been saved and so the build process would assume the file is still there and so where it goes to parse and package it, it would fail to find the file and so be unable to successfully complete the build.

**Comment by davkean** [comment]
The project is saved before build. Even if this was case the, the error message isn't appropriate.

**Comment by danzil** [comment]
I opened an issue in the WPF repo: https://github.com/dotnet/wpf/issues/2156
