### ISSUE TITLE
Interacting with WebView2 in AppWindow causes the main window to be focused/activated instead of the AppWindow

### ISSUE THREAD

**Issue by aquinn39** [microsoft/microsoft-ui-xaml#8113]
### Describe the bug

When interacting with a WebView2 control that's in an AppWindow (e.g. clicking, tapping or tabbing into the control), the main window becomes focuses/activated and focus is taken away from the AppWindow. This seems to happen any time you interact with a WebView2 that's in an AppWindow. It seems like the WebView2 might be finding its associated CoreWindow and focusing/activating it, not taking into account that it might be in an AppWindow and AppWindows don't have their own CoreWindows but are rather associated with an existing one. Either way it it's a big issue when using WebView2 in an AppWindow.

### Steps to reproduce the bug

1. Create a new UWP app
2. Install WinUI and create a page in the app with a WebView2 control and set its source to anything
3. Program the app to show that app window and have the app window's contents set to the page with the WebView2 control
4. Run the app and show the app window
5. Click, tap or tab to the WebView2 control
6. The AppWindow will lose focus/deactivate and the app's main window will gain focus/get activated

### Expected behavior

If a WebView2 in an AppWindow is interacted with, the AppWindow should be focused/activated if it isn't already; no other window should be focuses/activated.

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.1

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This issue does not happen with the WebView (i.e. The Edge Legacy one), only WebView2 (i.e. The Edge Chromium one).

Also, I saw this issue on Windows 10 22H2 (Build 19045) as well but there's no option above for that version.

**Comment by DmitriyKomin** [comment]
@aquinn39, thank you for reporting this issue. Unfortunately at this time we are not able to investigate WinUI2-specific issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).
