### ISSUE TITLE
Which control does File Explorer use in Windows 11 to display the context menu?

### ISSUE THREAD

**Issue by amtopel** [microsoft/microsoft-ui-xaml#8122]
Hi, this isn't an issue, just a question.  Does anyone know which control File Explorer uses in Windows 11 for its context menu?  To my untrained eye, it doesn't quite look and behave like a WinUI 3 MenuFlyout.  Anyone know what it is?  Thanks for any info.

**Comment by mdtauk** [comment]
CommandBarFlyout
![image](https://user-images.githubusercontent.com/7389110/214165035-63e0edc2-2e24-454b-a249-0109eb672697.png)

**Comment by amtopel** [comment]
Great.  Thank you very much.

**Comment by amtopel** [comment]
@mdtauk Can I ask one more quick question?  Do you know Explorer is able to place that single control, at any arbitrary point, over a regular non-WinUI window?  And use a fade animation?  Thanks again for any info.  I appreciate it.

**Comment by contextfree** [comment]
I think Explorer (and most other parts of the Windows 11 shell and built-in apps) still use UWP XAML/WinUI 2 and XAML Islands for their new UI, not WinUI 3.

**Comment by amtopel** [comment]
Well could you accomplish the same thing with WinUI 3?  A floating CommandBarFlyout that appears over an ordinary hwnd?

**Comment by sylveon** [comment]
No, because ShouldConstraintToRootBounds=False is still unimplemented.

**Comment by castorix** [comment]
> Well could you accomplish the same thing with WinUI 3? A floating CommandBarFlyout that appears over an ordinary hwnd?

You can use transparency :

![MenuFlyout](https://user-images.githubusercontent.com/22345506/214805763-70684586-daa8-4323-95d7-c37513d156ca.gif)

**Comment by amtopel** [comment]
@castorix Thanks.  Could you provide more information, or the source code for your example?  I was under the impression that transparency wasn't supported yet.  Thanks for any info on you accomplished that.

**Comment by amtopel** [comment]
Cool, thank you very much.
