### ISSUE TITLE
Title bar text in custom title bar does not show in high contrast themes

### ISSUE THREAD

**Issue by lavinders** [microsoft/microsoft-ui-xaml#8127]
### Describe the bug

Without any theme applied:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/17276086/214694964-cfc762e6-9527-4c44-a024-3ab8afa2f232.png">

With high contrast theme applied:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/17276086/214695129-f1b420f7-dbb9-48a5-9346-5c184360a18b.png">

<img width="845" alt="image" src="https://user-images.githubusercontent.com/17276086/214695449-404ffe4a-12c7-46e2-9cc6-8ef933ecdbcc.png">

### Steps to reproduce the bug

1. Create a new Winui project with following xaml and .cs, Build and launch it.
2. In settings app Accessibility constrast themes, change to aquatic / desert themes.

<Window
    x:Class="App12.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App12"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <ScrollViewer HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto" 
                  HorizontalScrollMode="Auto" VerticalScrollMode="Auto"
                  Background="{ThemeResource SystemControlBackgroundChromeMediumLowBrush}">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
            <Border x:Name="AppTitleBar" Grid.Row="0" VerticalAlignment="Top" >
                <TextBlock x:Name="AppTitle" VerticalAlignment="Top" />
            </Border>
            <TextBlock x:Name="Content" Grid.Row="1" Text="Test content"/>
        </Grid>
    </ScrollViewer>
</Window>

// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Navigation;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace App12
{
    /// <summary>
    /// An empty window that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();

            AppTitle.Text = "Test title";
            Window window = this as Window;
            window.ExtendsContentIntoTitleBar = true;  // enable custom titlebar
            window.SetTitleBar(AppTitleBar);
        }

     
    }
}
 

### Expected behavior

Title bar content is visible.

### NuGet package version

None

**Comment by pratikone** [comment]
No longer reproducible.  I believe this got fixed with latest version of winappsdk
