### ISSUE TITLE
Window.ExtendsContentIntoTitleBar should sync with AppWindow.TitleBar.ExtendsContentIntoTitleBar

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#8135]
### Describe the bug

Currently, both XAML Window and AppWindow have completely separate ways of extending window content into the title bar. These are incompatible with each other and cause lots of confusion. Also, the custom caption buttons rendered by XAML Window are very poor compared to AppWindow, which is decent and acceptable.

### Steps to reproduce the bug

1. Set Window.ExtendsContentIntoTitleBar to true
2. AppWindow.TitleBar.ExtendsContentIntoTitleBar won't be true

(or)

1. Set AppWindow.TitleBar.ExtendsContentIntoTitleBar to true
2. Window.ExtendsContentIntoTitleBar won't be true

### Expected behavior

Both properties should do the same and sync up.

### Screenshots

**With Window.ExtendsContentIntoTitleBar**
![With Window.ExtendsContentIntoTitleBar
](https://media.discordapp.net/attachments/580484470877061120/1068530591160610897/Screenshot_2023-01-27_at_19.28.35.png)

**With AppWindow.TitleBar.ExtendsContentIntoTitleBar**
![](https://media.discordapp.net/attachments/580484470877061120/1068535020945420418/image.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Instead of forwarding Window.ExtendsContentIntoTitleBar to AppWindow.TitleBar.ExtendsContentIntoTitleBar, either Window.ExtendsContentIntoTitleBar can be removed completely. You might always want to consider removing all other duplicating properties (eg: Title) and only expose them through AppWindow (Window.AppWindow in the future).  

An alternative to all this is to just unseal AppWindow and make XAML Window derive from it, but this can introduce complications.

**Comment by DarranRowe** [comment]
It was mentioned in an issue/discussion on the Windows App SDK repository that they intend to consolidate these. Also, ExtendsContentIntoTitleBar, Title and anything else like that cannot be removed from Microsoft.UI.Xaml.Window, but they can be deprecated. The big issue with this is that WinRT components are COM components. This means that they have a set of interfaces that define the operations that the component is able to do, but when an interface is officially defined it is immutable. This means that IWindow, which is the default interface of the Microsoft.UI.Xaml.Window runtime class, is stuck with these members.

**Comment by pratikone** [comment]
It has been done in winappsdk 1.4. WinUI 3 custom titlebar uses Appwindow titlebar under the hood.
