### ISSUE TITLE
Duplicate build output files for unpackaged winui3 project and v142 toolset

### ISSUE THREAD

**Issue by Nehluxhes** [microsoft/microsoft-ui-xaml#8142]
### Describe the bug

When building an **unpackaged** C++ winui 3 with the **v142 toolset**, I end up with duplicate files in a PROJECTNAME subfolder, including all the Assets folder but also some xbf files.
Also while xbf files are supposed to be optional (according to this https://github.com/microsoft/WindowsAppSDK/issues/2006 ), deleting them prevent the program from running.

If reverting back to the v143 toolset, or using a packaged application, I don't have those duplicate files and can delete xbf files with no problem.

### Steps to reproduce the bug

1. Create the base C++ project template "Blank App, Packaged (WinUI3 in Desktop)"
2. Make it unpackaged, so in vcxproj file add `<WindowsPackageType>None</WindowsPackageType>` and change `<AppxPackage>false</AppxPackage>`
3. In project properties, set Platform toolset to v142
4. Build the project => duplicate files in output directory

### Expected behavior

No duplicate files and xbf files not required for the program to run

### Screenshots

![image](https://user-images.githubusercontent.com/4388375/195349063-56f4827f-3d1a-430d-8444-eb6a243999f3.png)
![image](https://user-images.githubusercontent.com/4388375/195349247-353ceaac-92ac-4506-a17c-d1fdab3877ae.png)
![image](https://user-images.githubusercontent.com/4388375/195349353-c875cdac-1e6b-4997-80f8-84771d8f1c61.png)

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by pituluk** [comment]
This is still an issue.
