### ISSUE TITLE
When adding a NavigationViewItem to MenuItems it fails to draw the content of the MenuItems

### ISSUE THREAD

**Issue by MetalMonkey-GSD** [microsoft/microsoft-ui-xaml#8147]
### Describe the bug

When adding a NavigationViewItem to MenuItems it fails to draw the content of the MenuItems.

Issue is already known for WinUI 2.8, see here for bug description: https://github.com/microsoft/microsoft-ui-xaml/issues/7533
And it has allegedly been fixed here: https://github.com/microsoft/microsoft-ui-xaml/pull/7771

However the fix is not present in the latest WinUI 2.8.2 release and also not in the latest Windows App SDK 1.2.230118.102

Here it is stated, that the fix has been approved to merge into WinUI 2.8 and WinUI 3: https://github.com/microsoft/microsoft-ui-xaml/pull/7771#issuecomment-1322551629

However the problem still persists with the latest Windows App SDK (1.2.230118.102).

### Steps to reproduce the bug

see above

### NuGet package version

Windows App SDK 1.2.2: 1.2.221209.1

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update), Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by gabbybilka** [comment]
@ojhad from this PR, did this also get ported to WinUI 3? #7771
