### ISSUE TITLE
ResourceDictionary.HasKey is missing

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#8152]
### Describe the bug

The HasKey method of ResourceDictionary is missing. It's awkward to have to dig and find out that one can use resources.Keys.Contains instead. 

### Steps to reproduce the bug

Install Microsoft.WindowsAppSDK 1.2.220902.1-preview1 and look for the ResourceDictionary.HasKey method. 

### NuGet package version

None

**Comment by sotanakamura** [comment]
I can't reproduce the bug with Microsoft.WindowsAppSDK 1.2.230118.102. Could you provide more information to reproduce the bug?

```cpp
// App.xaml.cpp

void App::OnLaunched(LaunchActivatedEventArgs const&)
{
    auto result = Resources().HasKey(box_value(L"BodyTextBlockStyle"));
    window = make<MainWindow>();
    window.Activate();
}
```

**Comment by sjb-sjb** [comment]
I am using c# and a desktop WinUI 3 application. 

        protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs e)
        {
            base.OnLaunched(e);

            Application.Current.Resources.HasKey("xx"); // CS1061, Microsoft.UI.Xaml.ResourceDictionary does not contain HasKey

            ...
        }

Here is decompiled assembly 
#region Assembly Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b
// C:\Users\steve\.nuget\packages\microsoft.windowsappsdk\1.2.230118.102\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
// Decompiled with ICSharpCode.Decompiler 7.1.0.6543
#endregion

<code>
namespace Microsoft.UI.Xaml
{
    //
    // Summary:
    //     Defines a repository for XAML resources, such as styles, that your app uses.
    //     You define the resources in XAML and can then retrieve them in XAML using the
    //     {StaticResource} markup extension and {ThemeResource} markup extension s. You
    //     can also access resources with code, but that is less common.
    [WindowsRuntimeType("Microsoft.UI.Xaml")]
    [WindowsRuntimeHelperType(typeof(ABI.Microsoft.UI.Xaml.ResourceDictionary))]
    [ProjectedRuntimeClass(typeof(IResourceDictionary))]
    [ObjectReferenceWrapper("_inner")]
    [ContractVersion(typeof(WinUIContract), 65536u)]
    public class ResourceDictionary : DependencyObject, IDictionary<object, object>, ICollection<System.Collections.Generic.KeyValuePair<object, object>>, IEnumerable<System.Collections.Generic.KeyValuePair<object, object>>, IEnumerable, ICustomQueryInterface, IWinRTObject, IDynamicInterfaceCastable, IEquatable<ResourceDictionary>
    {
        internal sealed class _IResourceDictionaryFactory : IWinRTObject, IDynamicInterfaceCastable
        {
            private IObjectReference _obj;

            private static _IResourceDictionaryFactory _instance = new _IResourceDictionaryFactory();

            private volatile ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> _queryInterfaceCache;

            private volatile ConcurrentDictionary<RuntimeTypeHandle, object> _additionalTypeData;

            private IntPtr ThisPtr => _obj.ThisPtr;

            internal static _IResourceDictionaryFactory Instance => _instance;

            IObjectReference IWinRTObject.NativeObject => _obj;

            bool IWinRTObject.HasUnwrappableNativeObject => false;

            ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> IWinRTObject.QueryInterfaceCache => _queryInterfaceCache ?? MakeQueryInterfaceCache();

            ConcurrentDictionary<RuntimeTypeHandle, object> IWinRTObject.AdditionalTypeData => _additionalTypeData ?? MakeAdditionalTypeData();

            public _IResourceDictionaryFactory()
            {
                _obj = WinRT.ActivationFactory<ResourceDictionary>.As(GuidGenerator.GetIID(typeof(IResourceDictionaryFactory).GetHelperType()));
            }

            private ConcurrentDictionary<RuntimeTypeHandle, IObjectReference> MakeQueryInterfaceCache()
            {
                Interlocked.CompareExchange(ref _queryInterfaceCache, new ConcurrentDictionary<RuntimeTypeHandle, IObjectReference>(), null);
                return _queryInterfaceCache;
            }

            private ConcurrentDictionary<RuntimeTypeHandle, object> MakeAdditionalTypeData()
            {
                Interlocked.CompareExchange(ref _additionalTypeData, new ConcurrentDictionary<RuntimeTypeHandle, object>(), null);
                return _additionalTypeData;
            }

            public unsafe IntPtr CreateInstance(object baseInterface, out IntPtr innerInterface)
            {
                ObjectReferenceValue value = default(ObjectReferenceValue);
                IntPtr intPtr = default(IntPtr);
                IntPtr result = default(IntPtr);
                try {
                    value = MarshalInspectable<object>.CreateMarshaler2(baseInterface);
                    ExceptionHelpers.ThrowExceptionForHR(((delegate* unmanaged[Stdcall]<IntPtr, IntPtr, out IntPtr, out IntPtr, int>)(*(IntPtr*)((nint)(*(IntPtr*)(void*)ThisPtr) + (nint)6 * (nint)sizeof(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, out IntPtr, out IntPtr, int>))))(ThisPtr, MarshalInspectable<object>.GetAbi(value), out intPtr, out result));
                    innerInterface = intPtr;
                    return result;
                } finally {
                    MarshalInspectable<object>.DisposeMarshaler(value);
                }
            }
        }

        [StructLayout(LayoutKind.Sequential, Size = 1)]
        private struct InterfaceTag<I>
        {
        }

        private IObjectReference _inner;

        private volatile IObjectReference ___objRef_global__Microsoft_UI_Xaml_IResourceDictionary;

        private volatile IObjectReference ___objRef_global__System_Collections_Generic_IDictionary_object__object_;

        private volatile IObjectReference ___objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__;

        private Dictionary<object, (IntPtr, object)> _lookupCache = new Dictionary<object, (IntPtr, object)>();

        private IntPtr ThisPtr {
            get {
                if (_inner != null) {
                    return _inner.ThisPtr;
                }

                return ((IWinRTObject)this).NativeObject.ThisPtr;
            }
        }

        private IObjectReference _objRef_global__Microsoft_UI_Xaml_IResourceDictionary => ___objRef_global__Microsoft_UI_Xaml_IResourceDictionary ?? Make___objRef_global__Microsoft_UI_Xaml_IResourceDictionary();

        private IObjectReference _objRef_global__System_Collections_Generic_IDictionary_object__object_ => ___objRef_global__System_Collections_Generic_IDictionary_object__object_ ?? Make___objRef_global__System_Collections_Generic_IDictionary_object__object_();

        private IObjectReference _objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__ => ___objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__ ?? Make___objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__();

        private IResourceDictionary _default => null;

        bool IWinRTObject.HasUnwrappableNativeObject => GetType() == typeof(ResourceDictionary);

        IObjectReference IWinRTObject.NativeObject => _inner;

        public ICollection<object> Keys => IDictionaryMethods<object, object>.get_Keys(_objRef_global__System_Collections_Generic_IDictionary_object__object_);

        public ICollection<object> Values => IDictionaryMethods<object, object>.get_Values(_objRef_global__System_Collections_Generic_IDictionary_object__object_);

        public int Count => IDictionaryMethods<object, object>.get_Count(_objRef_global__System_Collections_Generic_IDictionary_object__object_);

        public bool IsReadOnly => IDictionaryMethods<object, object>.get_IsReadOnly(_objRef_global__System_Collections_Generic_IDictionary_object__object_);

        public object this[object key] {
            get {
                return IDictionaryMethods<object, object>.Indexer_Get(_objRef_global__System_Collections_Generic_IDictionary_object__object_, _lookupCache, key);
            }
            set {
                IDictionaryMethods<object, object>.Indexer_Set(_objRef_global__System_Collections_Generic_IDictionary_object__object_, key, value);
            }
        }

        //
        // Summary:
        //     Gets a collection of the ResourceDictionary dictionaries that constitute the
        //     various resource dictionaries in the merged dictionaries.
        //
        // Returns:
        //     A list collection of the ResourceDictionary dictionaries that constitute the
        //     various resource dictionaries in the merged dictionaries.
        public IList<ResourceDictionary> MergedDictionaries => IResourceDictionaryMethods.get_MergedDictionaries(_objRef_global__Microsoft_UI_Xaml_IResourceDictionary);

        //
        // Summary:
        //     Gets or sets a Uniform Resource Identifier (URI) that provides the source location
        //     of a merged resource dictionary.
        //
        // Returns:
        //     A Uniform Resource Identifier (URI) that provides the source location of a merged
        //     resource dictionary. This is typically a path that references a XAML resource
        //     within the app, or a reference to a loose XAML file.
        public Uri Source {
            get {
                return IResourceDictionaryMethods.get_Source(_objRef_global__Microsoft_UI_Xaml_IResourceDictionary);
            }
            set {
                IResourceDictionaryMethods.set_Source(_objRef_global__Microsoft_UI_Xaml_IResourceDictionary, value);
            }
        }

        //
        // Summary:
        //     Gets a collection of merged resource dictionaries that are specifically keyed
        //     and composed to address theme scenarios, for example supplying theme values for
        //     "HighContrast".
        //
        // Returns:
        //     A dictionary of ResourceDictionary theme dictionaries. Each must be keyed with
        //     **x:Key**.
        public IDictionary<object, object> ThemeDictionaries => IResourceDictionaryMethods.get_ThemeDictionaries(_objRef_global__Microsoft_UI_Xaml_IResourceDictionary);

        private IObjectReference Make___objRef_global__Microsoft_UI_Xaml_IResourceDictionary()
        {
            Interlocked.CompareExchange(ref ___objRef_global__Microsoft_UI_Xaml_IResourceDictionary, ((IWinRTObject)this).NativeObject.As<IUnknownVftbl>(new Guid(_003CGuidPatcherImplementationDetails_003E._003CIIDData_003EMicrosoft_002EUI_002EXaml_002EIResourceDictionary())), null);
            return ___objRef_global__Microsoft_UI_Xaml_IResourceDictionary;
        }

        private IObjectReference Make___objRef_global__System_Collections_Generic_IDictionary_object__object_()
        {
            Interlocked.CompareExchange(ref ___objRef_global__System_Collections_Generic_IDictionary_object__object_, (IObjectReference)typeof(IObjectReference).GetMethod("As", Type.EmptyTypes)!.MakeGenericMethod(typeof(IDictionary<object, object>).GetHelperType().FindVftblType()).Invoke(((IWinRTObject)this).NativeObject, null), null);
            return ___objRef_global__System_Collections_Generic_IDictionary_object__object_;
        }

        private IObjectReference Make___objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__()
        {
            Interlocked.CompareExchange(ref ___objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__, (IObjectReference)typeof(IObjectReference).GetMethod("As", Type.EmptyTypes)!.MakeGenericMethod(typeof(IEnumerable<System.Collections.Generic.KeyValuePair<object, object>>).GetHelperType().FindVftblType()).Invoke(((IWinRTObject)this).NativeObject, null), null);
            return ___objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__;
        }

        //
        // Summary:
        //     Initializes a new instance of the ResourceDictionary class.
        public ResourceDictionary()
            : base(DerivedComposed.Instance)
        {
            bool flag = GetType() != typeof(ResourceDictionary);
            object baseInterface = (flag ? this : null);
            IntPtr innerInterface;
            IntPtr newInstance = _IResourceDictionaryFactory.Instance.CreateInstance(baseInterface, out innerInterface);
            try {
                ComWrappersHelper.Init(flag, this, newInstance, innerInterface, out _inner);
            } finally {
                Marshal.Release(innerInterface);
            }
        }

        public new static ResourceDictionary FromAbi(IntPtr thisPtr)
        {
            if (thisPtr == IntPtr.Zero) {
                return null;
            }

            return MarshalInspectable<ResourceDictionary>.FromAbi(thisPtr);
        }

        protected internal ResourceDictionary(IObjectReference objRef)
            : base(DerivedComposed.Instance)
        {
            _inner = objRef.As(new Guid(_003CGuidPatcherImplementationDetails_003E._003CIIDData_003EMicrosoft_002EUI_002EXaml_002EIResourceDictionary()));
        }

        public static bool operator ==(ResourceDictionary x, ResourceDictionary y)
        {
            return (x?.ThisPtr ?? IntPtr.Zero) == (y?.ThisPtr ?? IntPtr.Zero);
        }

        public static bool operator !=(ResourceDictionary x, ResourceDictionary y)
        {
            return !(x == y);
        }

        public bool Equals(ResourceDictionary other)
        {
            return this == other;
        }

        public override bool Equals(object obj)
        {
            ResourceDictionary resourceDictionary = obj as ResourceDictionary;
            if ((object)resourceDictionary != null) {
                return this == resourceDictionary;
            }

            return false;
        }

        public override int GetHashCode()
        {
            return ThisPtr.GetHashCode();
        }

        protected ResourceDictionary(DerivedComposed _)
            : base(_)
        {
        }

        public void Add(object key, object value)
        {
            IDictionaryMethods<object, object>.Add(_objRef_global__System_Collections_Generic_IDictionary_object__object_, key, value);
        }

        public bool ContainsKey(object key)
        {
            return IDictionaryMethods<object, object>.ContainsKey(_objRef_global__System_Collections_Generic_IDictionary_object__object_, key);
        }

        //
        // Summary:
        //     Removes a specific item from the ResourceDictionary.
        //
        // Parameters:
        //   key:
        //     The key of the item to remove.
        public bool Remove(object key)
        {
            return IDictionaryMethods<object, object>.Remove(_objRef_global__System_Collections_Generic_IDictionary_object__object_, key);
        }

        public bool TryGetValue(object key, out object value)
        {
            return IDictionaryMethods<object, object>.TryGetValue(_objRef_global__System_Collections_Generic_IDictionary_object__object_, _lookupCache, key, out value);
        }

        public void Add(System.Collections.Generic.KeyValuePair<object, object> item)
        {
            IDictionaryMethods<object, object>.Add(_objRef_global__System_Collections_Generic_IDictionary_object__object_, item);
        }

        //
        // Summary:
        //     Removes all items from this ResourceDictionary.
        public void Clear()
        {
            IDictionaryMethods<object, object>.Clear(_objRef_global__System_Collections_Generic_IDictionary_object__object_);
        }

        public bool Contains(System.Collections.Generic.KeyValuePair<object, object> item)
        {
            return IDictionaryMethods<object, object>.Contains(_objRef_global__System_Collections_Generic_IDictionary_object__object_, _lookupCache, item);
        }

        public void CopyTo(System.Collections.Generic.KeyValuePair<object, object>[] array, int arrayIndex)
        {
            IDictionaryMethods<object, object>.CopyTo(_objRef_global__System_Collections_Generic_IDictionary_object__object_, _objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__, array, arrayIndex);
        }

        bool ICollection<System.Collections.Generic.KeyValuePair<object, object>>.Remove(System.Collections.Generic.KeyValuePair<object, object> item)
        {
            return IDictionaryMethods<object, object>.Remove(_objRef_global__System_Collections_Generic_IDictionary_object__object_, item);
        }

        public System.Collections.Generic.IEnumerator<System.Collections.Generic.KeyValuePair<object, object>> GetEnumerator()
        {
            return IEnumerableMethods<System.Collections.Generic.KeyValuePair<object, object>>.GetEnumerator(_objRef_global__System_Collections_Generic_IEnumerable_global__System_Collections_Generic_KeyValuePair_object__object__);
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        protected override bool IsOverridableInterface(Guid iid)
        {
            return base.IsOverridableInterface(iid);
        }

        CustomQueryInterfaceResult ICustomQueryInterface.GetInterface(ref Guid iid, out IntPtr ppv)
        {
            ppv = IntPtr.Zero;
            if (IsOverridableInterface(iid) || WinRT.InterfaceIIDs.IInspectable_IID == iid) {
                return CustomQueryInterfaceResult.NotHandled;
            }

            if (((IWinRTObject)this).NativeObject.TryAs(iid, out ppv) >= 0) {
                return CustomQueryInterfaceResult.Handled;
            }

            return CustomQueryInterfaceResult.NotHandled;
        }
    }
}
</code>

**Comment by riverar** [comment]
@sjb-sjb Your code is not formatted correctly https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by DarranRowe** [comment]
@sjb-sjb Are you actually using 1.2 preview 1 like in the bug report? If you are, if you update to 1.2.3, do you have the same issue?

**Comment by sjb-sjb** [comment]
As you can see, I upgraded to 1.2.230118.102 before I replied.

**Comment by riverar** [comment]
@DarranRowe Do you work at Microsoft? If so, can you please edit your profile to reflect that?

**Comment by evelynwu-msft** [comment]
@sjb-sjb When working with C#, `IMap<K,V>::HasKey(K)` is projected onto `IDictionary<TKey,TValue>.Contains(TKey)` so your code needs to use the latter.
