### ISSUE TITLE
HtmlUtilities::ConvertToText Crash in WinUI 3 App with C++/WinRT

### ISSUE THREAD

**Issue by sotanakamura** [microsoft/microsoft-ui-xaml#8153]
### Describe the bug

I have a problem on Windows SDK API `HtmlUtilities::ConvertToText` in WinUI 3 App with C++/WinRT. Calling it in UWP app is OK, but not in WinUI 3 App. In WinUI 3 App, Calling it after starting the application by `Application::Start` throws an exception. However, Calling it before starting application has no problem and calling it again after starting application is OK too. 

### Steps to reproduce the bug

1. Create a project from WinUI 3 and UWP project template.
2. Call `HtmlUtilities::ConvertToText` after `Application::Start`

### Expected behavior

Call `HtmlUtilities::ConvertToText` anywhere without an exception.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Additional information provided by community
https://github.com/microsoft/WindowsAppSDK/discussions/3401#discussion-4824959

**Comment by JesseCol** [comment]
Sounds like this is an issue in the HtmlUtilities::ConvertToText component?  Some code that works fine in UWP doesn't work in a non-UWP context because not all the same objects are available.  Please follow up with owners of that component.  Thanks!
