### ISSUE TITLE
ListView scroller is inactive when placed in a StackPanel or a Grid

### ISSUE THREAD

**Issue by jeromebjerome** [microsoft/microsoft-ui-xaml#8155]
### Describe the bug

As of: 02/06/2023 Windows 11 10.0.22621 Build 22621
Visual Studio 17.4.4

I created a simple Winui / C++ project and modified the Xaml file so as to have a StackPanel (vertical) orient) containing a CommandBar with 2 buttons and a ListView.
I added a large number of rows to the list.
In this configuration, it is impossible to scroll the ListView.

If I remove the StackPanel and the CommandBar, it works.
I have the same issue if I replace the Panel by a Grid.

**Below is the Xaml file**

<Window
    x:Class="App2.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel 
        Orientation="Vertical" 
        HorizontalAlignment="Stretch"
        VerticalAlignment="Stretch">

        <CommandBar VerticalAlignment="Top" HorizontalAlignment="Left">
            <AppBarButton Icon="OpenFile"/>
            <AppBarButton Icon="Save"/>
        </CommandBar>

    <ListView>

            <ListView.Items>

                <TextBlock Text="text_1"/>
                <TextBlock Text="text_2"/>
                <TextBlock Text="text_3"/>
                <TextBlock Text="text_4"/>
                <TextBlock Text="text_5"/>
                <TextBlock Text="text_6"/>
                <TextBlock Text="text_7"/>
                <TextBlock Text="text_8"/>
                <TextBlock Text="text_9"/>
                <TextBlock Text="text_10"/>
                <TextBlock Text="text_11"/>
                <TextBlock Text="text_12"/>
                <TextBlock Text="text_13"/>
                <TextBlock Text="text_14"/>
                <TextBlock Text="text_15"/>
                <TextBlock Text="text_16"/>
                <TextBlock Text="text_17"/>
                <TextBlock Text="text_18"/>
                <TextBlock Text="text_19"/>
                <TextBlock Text="text_20"/>
                <TextBlock Text="text_21"/>
                <TextBlock Text="text_22"/>
                <TextBlock Text="text_23"/>
                <TextBlock Text="text_24"/>
                <TextBlock Text="text_25"/>
                <TextBlock Text="text_26"/>
                <TextBlock Text="text_27"/>
                <TextBlock Text="text_28"/>
                <TextBlock Text="text_29"/>
                <TextBlock Text="text_30"/>
                <TextBlock Text="text_31"/>
                <TextBlock Text="text_32"/>
                <TextBlock Text="text_33"/>
                <TextBlock Text="text_34"/>
                <TextBlock Text="text_35"/>
                <TextBlock Text="text_36"/>
                <TextBlock Text="text_37"/>
                <TextBlock Text="text_38"/>
                <TextBlock Text="text_39"/>
                <TextBlock Text="text_40"/>
                <TextBlock Text="text_41"/>
                <TextBlock Text="text_42"/>
                <TextBlock Text="text_43"/>
                <TextBlock Text="text_44"/>
                <TextBlock Text="text_45"/>
                <TextBlock Text="text_46"/>
                <TextBlock Text="text_47"/>
                <TextBlock Text="text_48"/>
                <TextBlock Text="text_49"/>
                <TextBlock Text="text_50"/>
                <TextBlock Text="text_51"/>
                <TextBlock Text="text_52"/>
                <TextBlock Text="text_53"/>
                <TextBlock Text="text_54"/>
                <TextBlock Text="text_55"/>
                <TextBlock Text="text_56"/>
                <TextBlock Text="text_57"/>
                <TextBlock Text="text_58"/>
                <TextBlock Text="text_59"/>
                <TextBlock Text="text_60"/>
                <TextBlock Text="text_61"/>
                <TextBlock Text="text_62"/>
                <TextBlock Text="text_63"/>
                <TextBlock Text="text_64"/>
                <TextBlock Text="text_65"/>
                <TextBlock Text="text_66"/>
                <TextBlock Text="text_67"/>
                <TextBlock Text="text_68"/>
                <TextBlock Text="text_69"/>
                <TextBlock Text="text_70"/>
                <TextBlock Text="text_71"/>
                <TextBlock Text="text_72"/>
                <TextBlock Text="text_73"/>
                <TextBlock Text="text_74"/>
                <TextBlock Text="text_75"/>
                <TextBlock Text="text_76"/>
                <TextBlock Text="text_77"/>
                <TextBlock Text="text_78"/>
                <TextBlock Text="text_79"/>
                <TextBlock Text="text_80"/>

            </ListView.Items>
            
        </ListView>
        
    </StackPanel>

</Window>

### Steps to reproduce the bug

1) I created a simple Winui / C++ project (single project for App and msx) and modified the Xaml file so as to have a StackPanel (vertical) orient) containing a CommandBar with 2 buttons and a ListView.
2) Iadded a large number of rows to the list.
In this configuration, it is impossible to scroll the ListView.

Rem: 
If I remove the StackPanel and the CommandBar, it works.
I have the same issue if I replace the Panel by a Grid.

### Expected behavior

Scrolling should work

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by castorix** [comment]
If I copy your XAML code in a test project, but by adding a Height it works for me, like :
` <ListView Height="200">`

**Comment by jeromebjerome** [comment]
I have noticed that setting a height value can sometimes make it work but is it not even any value. 
It can work with 800 but fail with 1200.
Anyway I want my list to occupy the entire window height.

**Comment by castorix** [comment]
If you want the Listview in the entire window, you can use a Grid, like :

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>

        <CommandBar Grid.Row="0" VerticalAlignment="Top" HorizontalAlignment="Left">
            <AppBarButton Icon="OpenFile"/>
            <AppBarButton Icon="Save"/>
        </CommandBar>

        <ListView Grid.Row="1" ScrollViewer.VerticalScrollBarVisibility="Visible">

            <ListView.Items>

                <TextBlock Text="text_1"/>
                <TextBlock Text="text_2"/>
                <TextBlock Text="text_3"/>
                <TextBlock Text="text_4"/>
                <TextBlock Text="text_5"/>
                <TextBlock Text="text_6"/>
                <TextBlock Text="text_7"/>
                <TextBlock Text="text_8"/>
                <TextBlock Text="text_9"/>
                <TextBlock Text="text_10"/>
                <TextBlock Text="text_11"/>
                <TextBlock Text="text_12"/>
                <TextBlock Text="text_13"/>
                <TextBlock Text="text_14"/>
                <TextBlock Text="text_15"/>
                <TextBlock Text="text_16"/>
                <TextBlock Text="text_17"/>
                <TextBlock Text="text_18"/>
                <TextBlock Text="text_19"/>
                <TextBlock Text="text_20"/>
                <TextBlock Text="text_21"/>
                <TextBlock Text="text_22"/>
                <TextBlock Text="text_23"/>
                <TextBlock Text="text_24"/>
                <TextBlock Text="text_25"/>
                <TextBlock Text="text_26"/>
                <TextBlock Text="text_27"/>
                <TextBlock Text="text_28"/>
                <TextBlock Text="text_29"/>
                <TextBlock Text="text_30"/>
                <TextBlock Text="text_31"/>
                <TextBlock Text="text_32"/>
                <TextBlock Text="text_33"/>
                <TextBlock Text="text_34"/>
                <TextBlock Text="text_35"/>
                <TextBlock Text="text_36"/>
                <TextBlock Text="text_37"/>
                <TextBlock Text="text_38"/>
                <TextBlock Text="text_39"/>
                <TextBlock Text="text_40"/>
                <TextBlock Text="text_41"/>
                <TextBlock Text="text_42"/>
                <TextBlock Text="text_43"/>
                <TextBlock Text="text_44"/>
                <TextBlock Text="text_45"/>
                <TextBlock Text="text_46"/>
                <TextBlock Text="text_47"/>
                <TextBlock Text="text_48"/>
                <TextBlock Text="text_49"/>
                <TextBlock Text="text_50"/>
                <TextBlock Text="text_51"/>
                <TextBlock Text="text_52"/>
                <TextBlock Text="text_53"/>
                <TextBlock Text="text_54"/>
                <TextBlock Text="text_55"/>
                <TextBlock Text="text_56"/>
                <TextBlock Text="text_57"/>
                <TextBlock Text="text_58"/>
                <TextBlock Text="text_59"/>
                <TextBlock Text="text_60"/>
                <TextBlock Text="text_61"/>
                <TextBlock Text="text_62"/>
                <TextBlock Text="text_63"/>
                <TextBlock Text="text_64"/>
                <TextBlock Text="text_65"/>
                <TextBlock Text="text_66"/>
                <TextBlock Text="text_67"/>
                <TextBlock Text="text_68"/>
                <TextBlock Text="text_69"/>
                <TextBlock Text="text_70"/>
                <TextBlock Text="text_71"/>
                <TextBlock Text="text_72"/>
                <TextBlock Text="text_73"/>
                <TextBlock Text="text_74"/>
                <TextBlock Text="text_75"/>
                <TextBlock Text="text_76"/>
                <TextBlock Text="text_77"/>
                <TextBlock Text="text_78"/>
                <TextBlock Text="text_79"/>
                <TextBlock Text="text_80"/>

            </ListView.Items>

        </ListView>
    </Grid>

**Comment by jeromebjerome** [comment]
Yes it works on the sample.
For my knowledge, what is the explaination ?
Thank you.

**Comment by castorix** [comment]
From the Live Visual Tree, the _ActualHeight_ of the ListView and ScrollViewer = 3200 and ScrollViewer _ExtentHeight_ = 3200 in your original sample, 
while with the Grid, it is calculated, ~672 in my test, and changes when the window is resized, and ScrollViewer _ExtentHeight_ = 3200
Then I think that in the first case, as _ActualHeight_ = _ExtentHeight_, the ScrollViewer thinks that no Scrollbar is needed...
(to be confirmed...)

**Comment by kmahone** [comment]
> From the Live Visual Tree, the _ActualHeight_ of the ListView and ScrollViewer = 3200 and ScrollViewer _ExtentHeight_ = 3200 in your original sample, while with the Grid, it is calculated, ~672 in my test, and changes when the window is resized, and ScrollViewer _ExtentHeight_ = 3200 Then I think that in the first case, as _ActualHeight_ = _ExtentHeight_, the ScrollViewer thinks that no Scrollbar is needed... (to be confirmed...)

This is correct. When you put an element in a vertical StackPanel, the StackPanel will always allow its children to be as tall as they want. So if you have a ListView it will grow vertically to be as tall as it requires. This has the effect of the ListView never showing its scrollbars, since the ListView itself is as tall as it needs to be. This is just a consequence of how the layout system works in Xaml.

To avoid this, you should always put a ListView inside a something that constrains its layout. Or set a Height or MaxHeight on the ListView itself.
