### ISSUE TITLE
Turning off transparency effects should not turn off shadows

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#816]
**Describe the bug**

Specifically in combo boxes, the shadow shouldn't be removed when transparency effects are turned off. 

**Steps to reproduce the bug**

1. Open any combo box

**Expected behavior**

There would be a shadow

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)      | No  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |

**Comment by mdtauk** [comment]
I would have thought Shadows would come under the "enable visual effects" setting, not the transparency one

**Comment by jevansaks** [comment]
> I would have thought Shadows would come under the "enable visual effects" setting, not the transparency one

Me too, it's possible the code is just checking for the wrong setting. There is a "Show shadows under windows" setting that I would think should be respected here instead:

![image](https://user-images.githubusercontent.com/20667023/59052847-e608c980-8844-11e9-8a34-3cb7ec8f6b7b.png)

**Comment by Poopooracoocoo** [comment]
I wish all of those settings were in the UWP Settings app. It's kinda sad how Windows is holding this back.

**Comment by mdtauk** [comment]
The text in the Control Panel settings dialog, should probably be re-worded to something like

### Show shadows on windows and on screen controls

**Comment by Poopooracoocoo** [comment]
I think it should be separate. That wouldn't match anything else in that dialogue.

**Comment by chigy** [comment]
The fact it is using the same setting as what turns off Acrylic is on purpose, but I seem to remember this setting said something else. Investigating...

**Comment by mdtauk** [comment]
> I think it should be separate. That wouldn't match anything else in that dialogue.

So you want two options, something like this?
### Show shadows under windows
### Show shadows within apps

**Comment by chigy** [comment]
@mdtauk and @Poopooracoocoo , This is not something we can control (not my team to decide) so please open Feedback Hub item and let me know the ID of the item you opened so I can track the item's progress on my end.

**Comment by Poopooracoocoo** [comment]
@mdtauk There are things like 
- show shadows under windows
- show shadows under mouse pointer

so something like
- show shadows under menus

would be appropriate

@chigy 

What category?

**Comment by duke7553** [comment]
@Poopooracoocoo I do think there should be a greater distinction between the transparency and shadow effects. Since Fluent Design has become more diverse in what it contains over time, there should be separate toggles for each of them. (Ideally, in the Settings app)

**Comment by mdtauk** [comment]
A setting for Shadows, and a setting for Transparency.

**Comment by chigy** [comment]
@Poopooracoocoo , It should be opened against 'Desktop environment' + 'Settings'

**Comment by Poopooracoocoo** [comment]
https://aka.ms/AA5burp

**Comment by chigy** [comment]
@Poopooracoocoo , Thanks. I've added details on our end for whoever is responsible for this setting to have the context. May I close this item since there is nothing WinUI can do at this point?

FYI @mdtauk

**Comment by Poopooracoocoo** [comment]
I hope something gets done.

**Comment by chigy** [comment]
@Poopooracoocoo , since I am not from the team who makes the call, I am not able to promise anything but, at least, it is on the hands of people who does to take a look.

**Comment by Poopooracoocoo** [comment]
And from experience, they won't take a look. :(

Have a nice day

**Comment by Poopooracoocoo** [comment]
Sorry for mentioning you again @chigy I hope the bot doesn't move this lol

Do you know if this has progressed? Are any of the peeps who work on these kind of things on GitHub or Twitter? 

This kind of setting would bring consistency. win32 tooltips and menus keep their shadows but WinUI ones don't.

**Comment by chigy** [comment]
@Poopooracoocoo , I see on the database, it has the following comment. Good news is that they didn't dismiss it, and it will be considered in the future feature discussion. I cannot tell how much in future, however...

"Thanks for the feedback!

This is not a product issue, but rather a feature request/spec defect.  We will consider this feedback among all others of its kind periodically as we work to deliver outstanding experiences to our customers and partners."

**Comment by Poopooracoocoo** [comment]
btw I found more issues!

![image](https://user-images.githubusercontent.com/51363864/65300772-ffe1d880-dbb7-11e9-989c-ccec31578974.png)

UWP apps don't listen to:
- fade or slide menus into view
- fade or slide tooltips into view
- fade out menu items after clicking
- slide open combo boxes

Unticking animate controls and elements inside windows also disables smooth scrolling in Edge Spartan

and now that I see your comment again, I wish I could see that FBH comment myself.

**Comment by chigy** [comment]
@Poopooracoocoo , your last comments are slightly different from the original request. The difference here is that you area asking UWP to link to existing settings vs. the previous one was to change the existing setting to conform to a new UWP behavior somehow. Latter is hard because our team don't own the settings themselves. 

I won't promise anything here but if you created a request that reads something like "UWP should respect existing settings," and if this is something the team feels worth investment now, I'll see what I can do. Again, this will only be UWP respecting existing setting as is, rather than asking to add new settings. Latter will still need to go to Feedback Hub.

**Comment by Poopooracoocoo** [comment]
I'm not asking for the existing setting to conform to new UWP behaviour. In both the issue and the comment I'm asking for the same thing: for UWP to link to existing settings. :)

Sorry, I may have misunderstood your reply. :/ I read my own comment again and the original issue but I don't understand what you meant.

**Comment by chigy** [comment]
@Poopooracoocoo , because you are asking our new features to conform to more than a decade old settings, certain features are easier to do than others. Shadow one will require revisiting the way setting is setup in order to properly support the new features. Whereas your latest asks seems doable within the current setting framework/definition on my first look (though it may not be once we take a look).

**Comment by Poopooracoocoo** [comment]
It's still weird that shadows and acrylic are tied together.
