### ISSUE TITLE
Pivot control does not work with appsdk 1.3-experimental1

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#8160]
### Describe the bug

After upgrading to 1.3-experimental1 using a Pivot control results in a crash with WinRT originate error - 0x80004002 and then XAML parsing failed.

### Steps to reproduce the bug

1. Add a Pivot to an app using appsdk 1.3-experimental1

### Expected behavior

Should work as in 1.2

### NuGet package version

WinUI 3 - Windows App SDK 1.3 Experimental 1: 1.3.230202101-experimental1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by sigmarsson** [comment]
True. But even after I revert the nuget package to ```1.2.230118```

<img width="583" alt="image" src="https://user-images.githubusercontent.com/43340959/218939905-591ca3c0-153d-4645-be7c-494ca0c0c5c6.png">

**Comment by sigmarsson** [comment]
@lhak is it persisting by running ```x86``` configuration ?

**Comment by AdriaanLarcai** [comment]
Experiencing the same issue after trying out 1.3 experimental 1. Any views, controls or pages that contain a Pivot control will fail with a XAML parsing exception.

**Comment by gabbybilka** [comment]
Thanks for finding and filing, this is an issue we'll be relnoting for an upcoming preview release and targeting to fix for 1.3 stable.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.3.0` has been released which fixes this issue.
* [Release Notes](https://aka.ms/windowsappsdk/1.3/1.3.0/release-notes)
* [Nuget](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000)
