### ISSUE TITLE
When the Windows setting "Scroll inactive windows when hovering over them" is disabled, scrolling with the mouse is broken in WinUI3 app

### ISSUE THREAD

**Issue by jhert0** [microsoft/microsoft-ui-xaml#8161]
### Describe the bug

Unable to scroll TreeViews and DataGrids, potentially ListViews also but I didn't test them. A user was unable to scroll those controls and I was able to reproduce it by turning off that setting. We are both on Windows 11.

### Steps to reproduce the bug

Turn off the "Scroll inactive windows when hovering over them" setting in the Windows Setting app.
Try to scroll a TreeView or DataGrid.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

**Comment by bogdan-patraucean** [comment]
I can confirm it's affecting ListView as well. Apps like WinUI 3 Gallery and File Explorer too are affected by this issue.

**Comment by bogdan-patraucean** [comment]
@jhert0 I think you can close it as it was fixed with the [release ](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#:~:text=%237622.-,Fixed%20an,-issue%20that%20prevented)of WinAppSdk 1.4.
I tested it too and it works now.

**Comment by jhert0** [comment]
Yes, it works now, thank you.

**Comment by tpoint75** [comment]
It is broken in Windows App SDK 1.6.1!
