### ISSUE TITLE
Cannot open include file: 'Microsoft.UI.Composition.h'

### ISSUE THREAD

**Issue by dmitry-egorov** [microsoft/microsoft-ui-xaml#8168]
### Describe the bug

When including the file 'microsoft.ui.composition.interop.h' it tries to include 'Microsoft.UI.Composition.h':
#include <Microsoft.ui.composition.h>

The file could not be found, and I also can't find it anywhere on my system. There's a winrt generated version, but I think that's not the right file, and using it generates a bunch of errors in the 'microsoft.ui.composition.interop.h'. Am I missing something?

For context, I'm trying to interop with native C++ API.

### Steps to reproduce the bug

1. Create a project from "Blank App, Packaged (WinUI 3 in Desktop)".
2. Add '#include <microsoft.ui.composition.interop.h>' to pch.h.

### Expected behavior

The solution builds without errors.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DarranRowe** [comment]
This is one of those situations where it is easy to grab the wrong header if you are not careful, and it isn't documented afaik.
But the header you want is winrt/microsoft.ui.composition.interop.h. This header is written to interop with C++/WinRT. This header is also not a generated one, it is in the Windows App SDK package.
The header you are trying to use is for the C ABI, these headers aren't included with the Windows App SDK package by default, but you can generate them using the abi.exe tool. This tool can be downloaded from Nuget. But these headers would expose the raw interfaces.

But anyway, with the C++/WinRT header, what errors are you getting? I just created a new WinUI 3 project, included the winrt version of this header and then built the project and it built successfully.

**Comment by dmitry-egorov** [comment]
Thank you, that was very helpful and clarified things for me.

When talking about C++/WinRT header, I meant the "winrt/microsoft.ui.composition.h", not "winrt/microsoft.ui.composition.interop.h". Out of desparation I changed "microsoft.ui.composition.interop.h" file (C ABI, as you pointed out) to include "winrt/microsoft.ui.composition.h" and that, of course, gave me errors. So no bugs there.

As for my overall goal, I was trying to get a Direct2D device context from Win2d's CanvasDrawingSession. Following [this example](https://microsoft.github.io/Win2D/WinUI3/html/Interop.htm), I included "Microsoft.Graphics.Canvas.h", which is a header for the C ABI, as I now understand. It includes "microsoft.ui.composition.h", which was missing, and that led me to investigate "microsoft.ui.composition.native.h", which does the same. And then I wrote here.

So in the end, seems like I'll have to generate C ABI for Windows App SDK, so that Microsoft.Graphics.Canvas.h works correctly. Unless Direct2d has winrt headers and win2d exposes instances for them somehow.

**Comment by DarranRowe** [comment]
The thing is, I do mean winrt/microsoft.ui.composition.interop.h.
As far as Win2D's headers are concerned, did you add the Microsoft.Graphics.Win2D NuGet package? This causes C++/WinRT to generate the winrt/Microsoft.Graphics.Canvas.h file.

**Comment by DarranRowe** [comment]
Ah, I see what I missed there. I missed the fact that there was a single ICanvasDevice usage near the bottom.
You can get abi.exe from the Microsoft.Windows.AbiWinRT NuGet package.
