### ISSUE TITLE
Subclassing Path causes rendering issues

### ISSUE THREAD

**Issue by Siyh** [microsoft/microsoft-ui-xaml#8169]
### Describe the bug

When drawing Microsoft.UI.Xaml.Shapes.Path objects to Microsoft.UI.Xaml.Controls.Canvas controls Paths are sometimes improperly rendered when transformed using the Transform property of the Geometry objects.

### Steps to reproduce the bug

The code [here](https://stackoverflow.com/questions/75353670/subclassing-path-causes-rendering-issues) produces a window with two tabs. The first is blank. The second has four concentric ellipses drawn on it which take their transforms from either the Window or the Canvas. The ellipses are drawn as either Path objects or NumberSpacePath objects. NumberSpacePath inherits from Path but adds and changes nothing.

The two outer rings draw and resize without issue. However, when the second tab is first switched to, the innermost black ring is not rendered. Switching back to the first tab and again to the second tab causes it to be rendered. Additionally, enlarging the window causes the innermost two rings to be clipped, like on the attached image. Again, switching and returning tabs causes them to be rendered correctly.

### Expected behavior

All ellipses rendered completely when the tab is first switched to.

### Screenshots

![image](https://user-images.githubusercontent.com/19655141/217061919-797eb325-263c-493b-a5ab-a0a2ef82db6e.png)

### NuGet package version

None

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DmitriyKomin** [comment]
@Siyh - thank you for reporting this. We noticed this issue has been reported again more recently, but with a simpler repro in #8793 , so making that one the tracking bug.
