### ISSUE TITLE
InfoBadge icon is not visible

### ISSUE THREAD

**Issue by nxtn-staged** [microsoft/microsoft-ui-xaml#8176]
### Describe the bug

The icon in an icon info badge is not visible in WinUI 3.

### Steps to reproduce the bug

```xaml
<InfoBadge HorizontalAlignment="Center" VerticalAlignment="Center">
    <InfoBadge.IconSource>
        <SymbolIconSource Symbol="Sync"/>
    </InfoBadge.IconSource>
</InfoBadge>
```

### Screenshots

<img width="25" alt="image" src="https://user-images.githubusercontent.com/79820545/218391509-5eb5e643-627f-439d-8cc8-489c3d52cdbc.png">

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Jay-o-Way** [comment]
I'm **thinking** it's because SymbolIcon uses code points in the range of E1**, where Sync=E117. These have been deprecated for years. See also https://github.com/microsoft/microsoft-ui-xaml/issues/8375

**Comment by greatoceansoftware** [comment]
Any update on this? I would really like to use infobadges with icons.

**Comment by Jay-o-Way** [comment]
Use a FontIcon in the mean time
FYI @karkarl

**Comment by ranjeshj** [comment]
resolving as dup of https://github.com/microsoft/microsoft-ui-xaml/issues/8385

**Comment by Diegorro98** [comment]
FontIcon is also not working. See WinUI3 Gallery InfoBadge Section (winui3gallery://item/InfoBadge) "Placing an InfoBadge Inside Another Control", the InfoBadge element has a custom icon, but it is not visible.

**Comment by Jay-o-Way** [comment]
@Diegorro98 that seems to be an issue for that app. Please file a report on https://github.com/microsoft/WinUI-Gallery/issues

**Comment by Diegorro98** [comment]
@Jay-o-Way no it isn't only in the app, it is happening to me in the app I'm building. I used that example to easily show the issue. 
But you can go ahead and build an app with the following element:
```xaml
<InfoBadge Style="{StaticResource CautionIconInfoBadgeStyle}"/>
```
The exclamation icon is missing

Or this example from [Microsoft Learn](https://learn.microsoft.com/es-es/windows/apps/design/controls/info-badge#example-placing-an-infobadge-inside-another-control):
```xaml
<Button Width="200" Height="60" Padding="4"
        HorizontalContentAlignment="Stretch" VerticalContentAlignment="Stretch">
    <Grid>
        <SymbolIcon Symbol="Sync"/>
        <InfoBadge x:Name="buttonInfoBadge"
                        Background="#C42B1C"
                        HorizontalAlignment="Right" 
                        VerticalAlignment="Top"
                        Width="16" Height="16">
            <InfoBadge.IconSource>
                <FontIconSource Glyph="&#xEA6A;"/>
            </InfoBadge.IconSource>
        </InfoBadge>
    </Grid>
</Button>
```
The icon is also missing...

**Comment by greatoceansoftware** [comment]
Any update on this?

**Comment by ranjeshj** [comment]
I can repro this with latest 1.5 release. Reopening.

**Comment by SjVer** [comment]
Encountered the same issue. It's not just the `SymbolIconSource` that doesn't work with the `InfoBadge`, but all other icon sources too.

This snippet should be fine: 
```xaml
<InfoBadge Style="{ThemeResource SuccessIconInfoBadgeStyle}">
    <InfoBadge.IconSource>
        <FontIconSource Glyph="&#xE8FB;"/>
    </InfoBadge.IconSource>
</InfoBadge>
```
But it just shows a weird green squashed-looking circle: <img width="39" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/72567996/735e6d1c-f3b9-49ea-985c-149031e9f239">

Hope this gets fixed ASAP.

**Comment by leohu1** [comment]
I have the same problem

**Comment by castorix** [comment]
> Encountered the same issue. It's not just the `SymbolIconSource` that doesn't work with the `InfoBadge`, but all other icon sources too.

It works by setting the font.
For example, with Red Heart glyph

```
        <InfoBadge Style="{ThemeResource SuccessIconInfoBadgeStyle}" Width="42" MinHeight="42">
            <InfoBadge.IconSource>               
                <FontIconSource FontFamily="Segoe UI Emoji" Glyph="&#x2764;"/>
            </InfoBadge.IconSource>
        </InfoBadge>
```

I get : 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/22345506/9ac4acd7-2569-4dd5-828c-e68dd8a35a87)

**Comment by Jay-o-Way** [comment]
Yeah but a font shouldn't be hardcoded. At all.
