### ISSUE TITLE
The WINDOWS constant is missing when XamlPreCompile runs

### ISSUE THREAD

**Issue by mattleibow** [microsoft/microsoft-ui-xaml#8181]
### Describe the bug

When building for Windows, the `XamlPreCompile` task does not have any of the implicit defines by the .NET SDK.

There is a `AddImplicitDefineConstants` target that basically adds all these:

> TRACE;DEBUG;NET;NET7_0;NETCOREAPP;WINDOWS;WINDOWS10_0_19041_0;NET5_0_OR_GREATER;NET6_0_OR_GREATER;NET7_0_OR_GREATER;NETCOREAPP1_0_OR_GREATER;NETCOREAPP1_1_OR_GREATER;NETCOREAPP2_0_OR_GREATER;NETCOREAPP2_1_OR_GREATER;NETCOREAPP2_2_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER;WINDOWS10_0_19041_0_OR_GREATER;WINDOWS10_0_19041_0_OR_GREATER;WINDOWS10_0_18362_0_OR_GREATER;WINDOWS10_0_18362_0_OR_GREATER;WINDOWS10_0_17763_0_OR_GREATER;WINDOWS10_0_17763_0_OR_GREATER;WINDOWS8_0_OR_GREATER;WINDOWS7_0_OR_GREATER

But, when the `XamlPreCompile` task is running, nothing has been set and all we have is:

> TRACE;DEBUG;NET;NET7_0;NETCOREAPP

As a result, having an app with a TFM of `net7.0-windows10.0.19041.0` is weird and you get compiler errors: https://github.com/dotnet/maui/issues/6815

### Steps to reproduce the bug

In a MAUI app (or any app for that matter), add this code somewhere:

```cs
#if ANDROID
var os = "Android";
#elif IOS
var os = "iOS";
#elif MACCATALYST
var os = "Mac Catalyst";
#elif WINDOWS
var os = "Windows";
#endif

Debug.WriteLine(os);
```

The app will fail to compile.

Add
```cs
#else
var os = "ERROR";
```

So that the full snippet is:

```cs
#if ANDROID
var os = "Android";
#elif IOS
var os = "iOS";
#elif MACCATALYST
var os = "Mac Catalyst";
#elif WINDOWS
var os = "Windows";
#else
var os = "ERROR";
#endif

Debug.WriteLine(os);
```

The output will be `Windows`.

### Expected behavior

The app compiles without the `#else`

### Screenshots

![image](https://user-images.githubusercontent.com/1096616/199853390-d24e974e-3682-432b-9f89-7c788787fea1.png)

### NuGet package version

1.1.5

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

### Additional context

Added the binlogs:

Build without the `#else` that fails: [error.binlog.zip](https://github.com/microsoft/WindowsAppSDK/files/9933651/error.binlog.zip)
Build with the `#else` that runs: [fixed.binlog.zip](https://github.com/microsoft/WindowsAppSDK/files/9933652/fixed.binlog.zip)

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.3.0` has been released which fixes this issue.
* [Release Notes](https://aka.ms/windowsappsdk/1.3/1.3.0/release-notes)
* [Nuget](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000) to try it out.
