### ISSUE TITLE
WinUi 3 - Combobox inconsistency in Windows 10 Enterprise LTSC Deployment Machine

### ISSUE THREAD

**Issue by ravi-chandra-t** [microsoft/microsoft-ui-xaml#8185]
### Describe the bug

We are using multiple Combobox in our application.  It is working as expected in all most all the deployment machines.

We are seeing some inconsistency with Windows 10 Enterprise(build 17763). Some of the Combobox are not working as expected. sometimes the Combobox are not populated or It is not triggering the events in case of selection changed.

This issues we are only seeing in the Windows 10 Enterprise(build 17763)

### Steps to reproduce the bug

It is inconsistent.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows version

Windows 10 (1809): Build 17763

**Comment by DmitriyKomin** [comment]
@ravi-chandra-t, can you help provide a simple repro app for this issue?
