### ISSUE TITLE
NavigationView出了Bug——动画Bug

### ISSUE THREAD

**Issue by Starcloudsea** [microsoft/microsoft-ui-xaml#8186]
### Describe the bug

点击第一，第二个按钮时，动画正常
但是点击第3，第四个按钮时动画抽风（如GIF，在底下的”截图“里）

### Steps to reproduce the bug

在WinUI 3 Gallery中转到：Navigation》Navigation，你可以在第4个演示（Tying selection and focus - Tabs）里复现此Bug：随便点按钮

### Expected behavior

很顺畅的动画（至少不会抽风）

### Screenshots

![动画](https://user-images.githubusercontent.com/84891987/219045735-99f8f4e9-d55a-4493-bb13-e7e7d3cc1d06.gif)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621

**Comment by misaya** [comment]
我因为生产环境用了WinUI3, 已经被其他同事和领导骂的哭晕在厕所。
BUG 太多了，前段时间还老hang
