### ISSUE TITLE
WebView2 freezes if another instance of a UWP app is suspended (such as if it's minimised or on another virtual desktop)

### ISSUE THREAD

**Issue by aquinn39** [microsoft/microsoft-ui-xaml#8190]
### Describe the bug

If a UWP app supports multiple instances, and multiple instances are currently running with WebView2s, suspending (which happens automatically if a UWP app is minimised or on another virtual desktop) any one of them will cause all WebView2s in all instances to freeze, even if they are in an unminised desktop on the current virtual desktop. This issue is similar to https://github.com/microsoft/microsoft-ui-xaml/issues/6253.

### Steps to reproduce the bug

1. Create a UWP project
2. Install WinUI 2.8.2
3. Install WebView2 1.0.1518.46
4. Add a WebView2 to MainPage and set its source to anything
5. Change package.appxmanifest to support multiple instances
6. Build, deploy and launch the app
7. Launch the app again
8. Minimise one of the windows of one of the instances of the app
9. The other instance's WebView2 will freeze

### Expected behavior

WebView2s in running instances should not freeze when other instances of a UWP app are suspended.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

NuGet Package version is 2.8.2 but it's not in the above list.

**Comment by DmitriyKomin** [comment]
Hey @aquinn39, thank you for filing the issue. Unfortunately (much like for #6253), we are currently unable to investigate WinUI2-specific issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).
