### ISSUE TITLE
Microsoft.Ui.Composition parity with Windows.Ui.Composition (or interop)

### ISSUE THREAD

**Issue by smj389** [microsoft/microsoft-ui-xaml#8192]
### Describe the bug

Microsoft.Ui.ICompositorInterop is missing the methods for connecting to a DXGI Swap Chain. Since, the equivalent functionality now exists at the XAML layer (SwapChain and MediaPlayerElement) is it possible to reinstate it at the Visual Layer please?

### Steps to reproduce the bug

1. Attempt to port app from UWP to Windows App sdk that uses a swapchain
2. Become sad when the APIs are missing

### NuGet package version

WinUI 3 - Windows App SDK 1.3 Experimental 1: 1.3.230202101-experimental1

**Comment by DarranRowe** [comment]
Just for clarification, is this about using Microsoft.UI.Composition in general, or is it about using this in conjunction with Xaml?
If it is about using it in general, is there an issue stopping you from using Windows.UI.Composition? This is supported in desktop applications.

**Comment by smj389** [comment]
In conjunction with XAML. I would have thought the Windows AppSDK would offer a comprehensive solution.
________________________________

**Comment by smj389** [comment]
I have seen that in preview you have an API ContentExternalOutputLink which allows interop with DComposition. It would be good to be able to interop with Windows.UI.Composition as well.

**Comment by ClearSeve** [comment]
Does ContentExternalOutputLink no longer exist in the latest version of WinUI3 (1.3.230228005-preview1)?

**Comment by smj389** [comment]
@ClearSeve - it exists in the latest experimental version (not preview.) But that doesn’t allow interoperability with Windows.UI.Composition only DComp.

**Comment by ClearSeve** [comment]
> @ClearSeve - it exists in the latest experimental version (not preview.) But that doesn’t allow interoperability with Windows.UI.Composition only DComp.

I see. Thank you very much

**Comment by ClearSeve** [comment]
I see. Thank you very much
