### ISSUE TITLE
winui3 popup corewindowflyout or corewindowdialog cause app crashed

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#8195]
### Describe the bug

winui3 popup corewindowflyout or corewindowdialog cause app crashed

当我使用corewindowdialog或corewindowflyout时，初始化这些控件时和messagedialog操作类似，但是这些控件关闭后造成了主程序内存冲突
When I use corewindowdialog or corewindowflyout, initializing these controls is similar to the messagedialog operation, but these controls are closed and cause a main program memory conflict

![image](https://user-images.githubusercontent.com/49179966/219078441-aa8bc096-6a6d-4b60-a525-43a20b780f41.png)

### Steps to reproduce the bug

1.点击按钮弹出corewindowflyout或corewindowdialog
2.关闭后应用发生内存冲突

1. Click the button to pop up CoreWindowFlyOut or CoreWindowDialog
2. A memory conflict occurs in the app after closing

### Expected behavior

弹出这些控件并关闭后不应该发生冲突
There should be no conflicts after these controls pop up and close

### Screenshots

![image](https://user-images.githubusercontent.com/49179966/219078441-aa8bc096-6a6d-4b60-a525-43a20b780f41.png)

### NuGet package version

Windows App SDK 1.2.3: 1.2.230118.102

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by gabbybilka** [comment]
This is not supported as CoreWindowFlyout and CoreWindowPopup require a CoreWindow which does not exist in WinUI 3.
