### ISSUE TITLE
Setting Padding for a TabViewItem causes a cascade failure at runtime while computing element size

### ISSUE THREAD

**Issue by cazangabriel** [microsoft/microsoft-ui-xaml#8198]
### Describe the bug

**Name of component or part of Toolkit:**

TabView / TabViewItem

**Describe the bug:**

If setting up Padding for both the TabView element and a child TabViewItem opening the app causes the TabViewItem to continuously grow in size. (infinite loop)

**Version Info:**

Microsoft.Windows.SDK.BuildTools 1.2.221109.1
Microsoft.WindowsAppSDK 1.2.221109.1

**Additional context:**

[tabview_padding_bug.txt](https://github.com/microsoft/microsoft-ui-xaml/files/10760671/tabview_padding_bug.txt)

### Steps to reproduce the bug

1. Create a new project in VS "Blank App, Packaged (WinUI 3 in Desktop)"
2. Add the following code to MainWindow.xaml

```
<Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>


        <TabView IsAddTabButtonVisible="False" TabWidthMode="SizeToContent" CloseButtonOverlayMode="OnPointerOver"  Padding="4,4,4,4"
                     CanDrag="False" CanDragTabs="False" CanReorderTabs="False" IsDoubleTapEnabled="False" IsFocusEngagementEnabled="False" >
            <TabView.TabItems>
                <TabViewItem Header="Tab1" Padding="2,2,2,2" />
                <TabViewItem Header="Tab2"/>
                <TabViewItem Header="Tab3"/>
            </TabView.TabItems>
        </TabView>
        
    </Grid>
```

- note the the Padding on TabViewItem

3. run the app
4. (bug) the TabViewItem grows in size continuously / exponentially over time, on it's own (when the element size is calculated at runtime some sort of cascade failure takes place)

### Expected behavior
The size of the TabViewItem should stay fixed at runtime, not grow continuously over time.

_No response_

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DmitriyKomin** [comment]
@cazangabriel, thank you for reporting the issue. We are unable to repro this on WASDK 1.4, and we believe it was likely fixed in that timeframe. Please comment here and bring it to our attention if you find that it still reproes on the latest WASDK.
