### ISSUE TITLE
How to add icon to winui3 application 

### ISSUE THREAD

**Issue by Mohan-Babblu** [microsoft/microsoft-ui-xaml#8199]
### Describe the bug

Hi , I am currently working in an Win-Ui 3 Project for unpackaged version , where i have added the icon to my application .

### Steps to reproduce the bug

1.Create  a new winui3 unpackaged version
2.i need to place icons in all the red circle area of screen shot

### Screenshots

![Icongit](https://user-images.githubusercontent.com/88727251/219598687-98a70214-edcf-4534-9b59-9dc1f601637c.PNG)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000

**Comment by castorix** [comment]
With [AppWindow.SetIcon](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.windowing.appwindow.seticon?view=windows-app-sdk-1.2) or WM_SETICON for the window
and in Properties (Win32 Resources) for the .exe
