### ISSUE TITLE
TextBox in WinUI3 cannot invoke IME

### ISSUE THREAD

**Issue by Searchstars** [microsoft/microsoft-ui-xaml#8202]
### Describe the bug

When I click on the TextBox and start typing, no matter how I try to switch the input method, the input method does not work, which prevents me from typing Chinese, Japanese... and more language

### Steps to reproduce the bug

1. Create a new TextBox
2. Focus on the TextBox and type in it, try to switch the input method, but you will find that it doesn't work 😢

### Screenshots

![image](https://user-images.githubusercontent.com/47274115/219701156-b64a8108-65da-4af3-8020-3afaa6653e1d.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows Insider Build (25295.1000)

**Comment by llongley** [comment]
I'm not seeing the issue reproduce as described.  I have both Japanese and simplified Chinese language packs installed; when I press Win+Space to select Japanese and then Alt+` to select kana, I can type and select from the IME normally:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/18177025/f17d8f86-a21d-452f-ac8a-769721ad20fb)

Similarly, when I press Win+Space to select simplified Chinese, I can type and press a number to select a word.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/18177025/1309ea25-168f-49cc-ba93-25cb71a6e0f9)

If you're still seeing an issue, please feel free to provide more information and reopen this issue.
