### ISSUE TITLE
App crashed when close window too fast after opening

### ISSUE THREAD

**Issue by khoabui1412** [microsoft/microsoft-ui-xaml#8209]
### Describe the bug

When close too fast when openning the window, app is crashed with access violation:
 ```
       private void OpenWindow(object sender, RoutedEventArgs e)
        {
            var wn = new Window1();
            wn .Activate();
            wn .Show();
            wn .Close();
        }
```

I think that because window is closed before xaml in that window is loaded. 

### Steps to reproduce the bug

Close too fast after opening

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621

**Comment by bpulliam** [comment]
This should be fixed in 1.4 Preview 1

**Comment by khoabui1412** [comment]
@bpulliam, it happens again in latest version 1.5.24

**Comment by khoabui1412** [comment]
Sorry, i mean wasdk version 1.5.6 (1.5.240802000)
