### ISSUE TITLE
New window stay not in foreground after activation if using MenuFlyoutSubItem

### ISSUE THREAD

**Issue by fargus68** [microsoft/microsoft-ui-xaml#8210]
### Describe the bug

In case of using MenuFlyoutSubItem a new window stay not in foreground

### Steps to reproduce the bug

Create an empty winui 3 packaged app, paste the source of section "Additional context" and add a new window to the app

1.) Start the app
2.) Click on the Sub-Menu Level 2
=> new Window on top of main window in foreground
3.) Click on the Sub-Sub-Menu Level 3
=> new Window on top of main window for a short period in foreground, then main window come to foreground again

### Expected behavior

Same behaviour when using MenuFlyoutSubItem as it is when using not MenuFlyoutSubItem
=> new window stay in foreground

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Window
    x:Class="App2.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Left" VerticalAlignment="Top">
        <MenuBar VerticalAlignment="Top">
            <MenuBarItem Title="Level 1" ></MenuBarItem>
            <MenuBarItem Title="Level 2">
                <MenuFlyoutItem Text="Level 2" Click="Level2_Click"/>
            </MenuBarItem>
            <MenuBarItem Title="Level 3">
                <MenuBarItem.Items>
                    <MenuFlyoutSubItem Text="Level 3">
                        <MenuFlyoutItem Text="Level 3" Click="Level3_Click"/>
                    </MenuFlyoutSubItem>
                </MenuBarItem.Items>
            </MenuBarItem>
        </MenuBar>
    </StackPanel>
</Window>

Code behind:

using Microsoft.UI.Xaml;

namespace App2;

public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
    }

    private void Level2_Click(object sender, RoutedEventArgs e)
    {
        BlankWindow1 window = new();
        window.Activate();
    }

    private void Level3_Click(object sender, RoutedEventArgs e)
    {
        BlankWindow1 window = new();
        window.Activate();
    }
}

**Comment by bpulliam** [comment]
Please try this with 1.4 Preview 1, this may have already been fixed.

**Comment by fargus68** [comment]
it works as expected with Winapp-SDK-Versions
1.3.230602002
1.4.230628000-preview1
