### ISSUE TITLE
Typo in Windows Store Apps documentation

### ISSUE THREAD

**Issue by snail501** [microsoft/microsoft-ui-xaml#8213]
### Describe the bug

Typo in the documentation for windows store apps.
At present it reads:

10.2.3

Your product must not contain or enable malware as defined by the Microsoft criteria for [Unwanted and Malicious Software](https://learn.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria). Further, your product must not offer to install secondary software that is not developed you and does not enhance the functionality of your product.

### Steps to reproduce the bug

1. Go on the Windows website
2. Navigate to the section about Windows Store Apps
3. Go down to subsection 10.2.3

### Expected behavior

It should grammatically read:

10.2.3

Your product must not contain or enable malware as defined by the Microsoft criteria for [Unwanted and Malicious Software](https://learn.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria). Further, your product must not offer to install secondary software that is not developed **_by_** you and does not enhance the functionality of your product.

### NuGet package version

None

**Comment by JaiganeshKumaran** [comment]
This has been fixed now.
