### ISSUE TITLE
Rendering bugs with NavigationView across different releases.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#822]
The NavigationView control exhibits inconsistent rendering across different releases of Microsoft.UI.Xaml.Controls.

Example with Microsoft.UI.Xaml v 2.0.181018004, you get this which is mostly correct:

![image](https://user-images.githubusercontent.com/6632315/59119957-2b4ef900-8922-11e9-8d8a-9d39c3e8f6a2.png)

Notice that the XAML markup shown below does not properly extend the selection area:

`<ui:NavigationViewItem.Icon>
<PathIcon Data= ...  />
</ui:NavigationViewItem.Icon>`

When using Microsoft.UI.Xaml v2.1.190405004.2 you get this:

![image](https://user-images.githubusercontent.com/6632315/59120214-dc559380-8922-11e9-9553-a12410b95796.png)

Which is way worse and quite wrong.

Please start using a regression testing system that takes UI snapshots to compare results.  This sort of thing should never happen with newer releases.

**Comment by jevansaks** [comment]
Thanks for reporting, @Noemata! You're right that we don't have visual verification coverage of this scenario, but we will absolutely add it.

Can you provide the specific PathIcon Data you used? I suspect that we're doing something wrong to size to content instead of enforce a size on that icon.

**Comment by Noemata** [comment]
Thank you for the super fast response.  Here's the complete XAML:

`                <ui:NavigationViewItem Content="Info" IsEnabled="{Binding NotInSetup}" HorizontalAlignment="Left" >
                    <ui:NavigationViewItem.Icon>
                        <PathIcon Data="F1 M 8.40961,0C 9.4508,0 10.2517,0.400459 11.0526,1.12128C 11.7734,1.8421 12.0938,2.72311 12.0938,3.68421C 12.0938,4.7254 11.7734,5.52632 11.0526,6.24714C 10.3318,6.96796 9.4508,7.36842 8.4897,7.36842C 7.44851,7.36842 6.5675,6.96796 5.84668,6.24714C 5.12586,5.52632 4.80549,4.64531 4.80549,3.68421C 4.80549,2.72311 5.12586,1.8421 5.92677,1.12128C 6.64759,0.400459 7.44851,0 8.40961,0 Z M 0,18.1808L 12.0938,17.8604L 12.0938,44.1304C 12.0938,44.8512 12.3341,45.3318 12.6545,45.6522C 13.135,46.0526 13.7757,46.2929 14.4966,46.2929L 18.0206,46.2929L 18.0206,48.7757L 0.640732,48.7757L 0.640732,46.2929L 3.84439,46.2929C 4.80549,46.2929 5.52631,46.0526 5.92677,45.6522C 6.40732,45.1716 6.64759,44.4508 6.64759,43.5698L 6.64759,24.3478C 6.64759,23.1464 6.32723,22.1853 5.60641,21.6247C 4.88558,20.984 3.84439,20.6636 2.48284,20.6636L 0,20.6636L 0,18.1808 Z "  />
                    </ui:NavigationViewItem.Icon>    
                </ui:NavigationViewItem>`

**Comment by Noemata** [comment]
I should add that the behavior of NavigationView has also changed.  With just the addition of the latest nuget package, the hamburger menu starts in an open state when it should be closed.  Again, using snapshots of visuals during regression testing would catch all such flaws provided you had appropriate thresholds for differences, so you could add visual acrylic enhancements, and still have tests pass because of you threshold on significant luminance changes or significant dimensional changes.

**Comment by jevansaks** [comment]
Great, thanks for sharing the path data. Also sounds like you're seeing another issue here too where the pane is starting out expanded. We've been wrestling with issues around SplitView's behavior so this might be another issue. If you have a standalone repro solution we can take a look into that problem as well.

**Comment by Noemata** [comment]
Any word on fixing this?
