### ISSUE TITLE
Customized title caption buttons not retaining inactive styling

### ISSUE THREAD

**Issue by oensch** [microsoft/microsoft-ui-xaml#8228]
### Describe the bug

In my WinUI 3 app, I have a fully customized title bar. If I click away from the window, the foreground for the caption buttons fades as expected. When moused over while the window is still inactive, the background/foreground changes as expected, but when moving the mouse away again, the foreground returns to the active brush instead of reverting back to the inactive brush, even though the window is still inactive.

### Steps to reproduce the bug

This can also be seen in the WinUI 3 Gallery App:

1. Open the app
2. Click away from the window (the caption button foregrounds take on their inactive styling)
3. Move the pointer over a caption button to see its background/foreground change
4. Move the pointer away from the button(s) to see that the foreground doesn't return to the inactive styling

### Expected behavior

On an inactive window, the caption buttons should return to inactive styling if moused over and then moused away from (assuming the window hasn't otherwise been made active).

### NuGet package version

WinUI 3 - Windows App SDK 1.2.3: 1.2.230118.102

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Balkoth** [comment]
Seeing this too  on the WinUI 3 Gallery App...

**Comment by Balkoth** [comment]
This is still an issue in Windows App SDK 1.3.2 (1.3.230602002)

**Comment by pratikone** [comment]
has been fixed in winappsdk 1.4. 
closing the issue. If you continue to see the issue in some scenario, comment here and I will re-open the bug
