### ISSUE TITLE
Issue with choice of encoding for Resources.resw for Chinese and Kanji characters

### ISSUE THREAD

**Issue by Wind-Explorer** [microsoft/microsoft-ui-xaml#8231]
### Describe the bug

As we may know `Resources.resw` is used to localize apps in WinUI. However my app here seems to struggle with displaying Chinese and Japanese characters pre-defined in `Resources.resw` using the default encoding.

![image](https://user-images.githubusercontent.com/66894537/221785034-13f89da9-6a75-43de-8f43-d95c939227f7.png)

However when I copy-pasted some Hindi text into `Resources.resw` and save the file, a pop-up appeared prompting to change the encoding of the file in order to save the content.

After letting Visual Studio change the encoding, I see that the file has turned from `UTF-8` to `UTF-8 with BOM`.

![image](https://user-images.githubusercontent.com/66894537/221785860-61a384ca-40de-4206-9a0f-df830eb43e1f.png)

With that the displaying of text is working as expected.

![image](https://user-images.githubusercontent.com/66894537/221788411-c749b883-f67d-45d2-8d30-d744f82bad2c.png)

### Steps to reproduce the bug

1. In a new WinUI project, configure and set up the resources file (`[Project]/Strings/en-US/Resources.resw`)
2. Assign Chinese or Japanese characters as value to a string linked to an existing interface element (in new blank project template there is a `myButton`).
3. Run the app.

### Expected behavior

The default encoding / decoding methods should allow the content in the app interface to display exactly what's in the values of `Resources.resw`.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

While creating this issue I experimented with another project I had which was originated from the WinUI Template Studio, and there seems to not be an issue with that...however I still do believe that failing to decode special characters by default is unexpected behaviour and should be seen as a bug.

**Comment by bpulliam** [comment]
The default code page was changed in the WinUI templates in WinAppSDK 1.3.
