### ISSUE TITLE
Selected ListView items especially textbox are shown differently in high constrast theme impacting accessibility.

### ISSUE THREAD

**Issue by lavinders** [microsoft/microsoft-ui-xaml#8235]
### Describe the bug

Text content shown in ListView's selected item in high contrast theme has some text content limited background which gives undesired experience from accessibility perspective. 

### Steps to reproduce the bug

1. Create a WinUI 3 sample project and use following xaml:

<Window
    x:Class="App2.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
    <ListView SelectionMode="Single"
              Grid.Row="1"
              BorderBrush="{ThemeResource SystemControlForegroundBaseMediumLowBrush}">
      <x:String>aa</x:String>
      <x:String>bb</x:String>
      <x:String>cc</x:String>
    </ListView>
  </StackPanel>
</Window>

2. In settings, accessibility, change contrast theme to desert.
3. Build and run the app and observe the textblock content shown for selected item.

Now compare it with WinUI3 gallery sample list view example selected item.

### Expected behavior

Either we should clearly document what we need to add in XAML to match the display of what is shown in WinUI 3 gallery sample app or we should fix the bug where nothing special is required for correctly rendering high contrast text within listview.

### Screenshots

WinUI3 ListView sample

![image](https://user-images.githubusercontent.com/17276086/221998639-821fa662-ef2a-415a-956d-4a9386036d9c.png)

Sample app using VS template

![image](https://user-images.githubusercontent.com/17276086/221998811-67223194-f865-4bc7-973c-1edb5c02259d.png)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
This is intentional and documented here (although it could be better). The default has been chosen so that even without extra work from the app author the text is visible/accessible. When turning this off, the app author needs to do extra testing to ensure that accessibility tools don't trigger this as an issue for different themes.

If you could contribute here to make the docs better, that would be awesome. Thanks @lavinders !
https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.xaml/uielement_highcontrastadjustment.md
