### ISSUE TITLE
Add more sample proposals

### ISSUE THREAD

**Issue by ClearSeve** [microsoft/microsoft-ui-xaml#8239]
I have not contacted WPF UWP WinUI2 before, but I have development experience in C++, MFC, C #, WinForm, etc. It is a little difficult to use WinUI3 directly. I have seen that the official WinUI-Gallery and WindowsAppSDK-Samples are not very helpful to learn. It is suggested that some product frameworks like Windows11 can be developed, such as mspaint (simple menubar) or notepad (multiple tabview), to demonstrate how to use xaml, so that we can learn better

source language:
之前没有接触过WPF UWP WinUI2, 但我具备C++, MFC, C#, WinForm等开发经验, 直接使用WinUI3有点困难, 我看过官方提供的WinUI-Gallery和WindowsAppSDK-Samples学习起来帮助不大, 建议可以出一些像Windows11带的产品框架, 比如mspaint(简单menubar),或者notepad(多tabview), 演示如何使用xaml, 这样能够让我们更好的学习

**Comment by sotanakamura** [comment]
Tutorials for beginners are not documented well. Please refer to [design](https://learn.microsoft.com/ja-jp/windows/apps/design/) which contains coding. If you want more samples, please tell it to [doc repositry](https://github.com/MicrosoftDocs/windows-dev-docs). Don't remember to close this issue.

**Comment by castorix** [comment]
> I have seen that the official WinUI-Gallery and WindowsAppSDK-Samples are not very helpful to learn.

I think WinUI 3 Gallery is well presented and useful for most of controls
You can click on "XAML source code" and "C# source code" on the right, then you can copy/paste and adapt blocks of code

**Comment by sotanakamura** [comment]
@ClearSeve Please close this issue.
