### ISSUE TITLE
Add nuget dependency on Microsoft.VCRTForwarders.140

### ISSUE THREAD

**Issue by jevansaks** [microsoft/microsoft-ui-xaml#824]
We need to add a dependency on the VCRTForwarders nuget package so that the dll-based packages work in unpackaged apps.

https://www.nuget.org/packages/Microsoft.VCRTForwarders.140/

**Comment by RBrid** [comment]
After discussions with Oscar, Miguel and Jevan, it turned out that we should not add this dependency @ the WinUI Controls nuget level. Closing this issue.
