### ISSUE TITLE
Proposal: Deprecate MenuFlyout in favor of CommandBarFlyout

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#8244]
# Proposal: Deprecate MenuFlyout in favor of CommandBarFlyout

## Summary
I understand the need of the MenuFlyout control as a stop gap between “legacy” UIs and WinUI applications, and how it’s easier to do stuff the same way. MenuFlyouts look and work like those same flyouts in countless Windows programs, like Visual Studio, for example. But I personally think we should just migrate every command oriented flyout to being CommandBarFlyouts.

And I know you can just use one if you want, but that's not really the point.

## Rationale
The following are two reasons why the WinUI team should, at least, consider this. 

* Consistency: by having only one of these types of flyouts will ensure consistency throughout apps, and even throughout areas of the same app, both in look and in feel;

* Avoid confusion: related to the first point, a developer might use different flyouts for different parts of their app because they think one looks better here, but not there.

## Important Notes
The CommandBarFlyout control should have the same opening animation as the MenuFlyout currently has. The current opening animation is too subtle

Also important would be to rename PrimaryCommands/SecondaryCommands to TopCommands and BottomCommands, or something of the sort. A person using a MenuBar only using SecondaryCommands for the MenuItems (too look like MenuFlyouts) might think they’re somehow making their commands less important.

This would also allow for MenuBarItems to have flyouts that have both primary and secondary commands.

**Comment by sylveon** [comment]
There are a few discrepancies that need to be addressed before this is done:
- No AppBarRadioButton (while there is RadioMenuFlyoutItem)
- Better documentation: it is not obvious that the way to add a sub-menu is to attach a Flyout to an AppBarButton. I could not find any docs telling you how to do that and had to dig into the CommandBarFlyout test UI code to figure that out.
- MenuFlyout is less resource intensive than CommandBarFlyout.
