### ISSUE TITLE
InjectedInputPointerInfo doesn't work with multi-monitor setup

### ISSUE THREAD

**Issue by zrajnai-shapr3d** [microsoft/microsoft-ui-xaml#8247]
### Describe the bug

We are investigating the usage of [Windows.UI.Input.Preview.Injection](https://learn.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection) to automate our UWP testing.
The sample found at [Simulate user input through input injection](https://learn.microsoft.com/en-us/windows/apps/design/input/input-injection) however doesn't work with a multi-monitor setup.
It is clicking in the wrong places. We tried different mult-monitor setups (changing scales on both monitors to 100%, switch primary displays etc..) but it didn't help.
The sample code seems to be OK.

### Steps to reproduce the bug

1. Run the sample at [Simulate user input through input injection](https://learn.microsoft.com/en-us/windows/apps/design/input/input-injection) on a multi-monitor system.

### Expected behavior

InputInjection works with multi-monitor setups

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by JesseCol** [comment]
Unfortunately we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).
