### ISSUE TITLE
Changing the theme on runtime while no backdrop is set, will not apply the correct colors

### ISSUE THREAD

**Issue by bogdan-patraucean** [microsoft/microsoft-ui-xaml#8249]
### Describe the bug

Trying to change the app's theme at runtime will not apply the theme corresponding colors if the theme is not the same as the one set in the OS. If themes are matching (Light set in the app, Light set in the OS, or Dark set in the app, Dark in the OS) the corresponsing colors will be applied. The problem only happens when the themes are **not in sync**.

The problem is both in WinUI 3 and in WinUI 2.8.

### Steps to reproduce the bug

1. Create a WinAppSdk or an UWP app
2. Change the theme at runtime using:

 `(Content as FrameworkElement).RequestedTheme = ElementTheme.Dark;` in **MainWindow** or **MainPage** constructor.

3. If the requested theme is Dark, now change the OS theme to Light. (or vice-versa)
4. Run the app and notice how the background should be black but it's white.

This issue can also be reproduced in WinUI 2/3 Gallery:

1. Set the app's theme to Light
2. Set the OS theme to Dark
3. Go to System Backdrops section
4. Click on Create Window with mica
5. Change the backdrop to None
6. Notice how the button dissapears

Switching the OS theme to Light, or the app's theme to Dark will make the button appear. (so when themes are in sync, it works)

### Expected behavior

I would expect the colors to change accordingly, the same way they change when themes are in sync.

### Screenshots

<img width="253" alt="image" src="https://user-images.githubusercontent.com/26826125/222957668-e8b8f0fd-e453-4fd2-b7b3-9f94b057f95f.png">

App theme: Dark
OS theme: Light
Backdrop: Mica

<img width="257" alt="image" src="https://user-images.githubusercontent.com/26826125/222957683-a5a928a9-aee3-4a4d-bab1-90c4f016555f.png">

App theme: Dark
OS theme: Light
Backdrop: None

<img width="251" alt="image" src="https://user-images.githubusercontent.com/26826125/222957704-15c364b9-a96d-4d28-8b77-3850eae0844b.png">

App theme: Dark
OS theme: Dark
Backdrop: None

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.1

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (21H2): Build 19044

### Additional context

On UWP, as there is a MainPage, not a Window, you can fix the issue by changing the theme using:
`MainPage.RequestedTheme = ElementTheme.Dark`
RequestedTheme is not available on Window as a property so this solution does not work in both app types.

There is also a workaround, applying a Background Brush to the root element of the Window, or MainPage.

`<RootElement Background="{ThemeResource SolidBackgroundFillColorBaseBrush}"> </RootElement>`

This workaround applies when there is no backdrop, but then, if you set a backdrop, it has no effect, so the background has to be removed. It's not an ideal workaround as it does not work in every scenario and this also does not explain why does it work without a background set when themes are in sync.

In my example I put the code that changes the theme is in the constructor, but this will eventually be part of an event handler, when you want to react combobox selection. 

This also affects the transition between Backdrops (if the theme is Light in the app, and Dark in the OS) for a split of a second there is a black color that appears, before the Backdrop is changed.

**Comment by steam3d** [comment]
I think it connected with my issue
https://github.com/microsoft/WindowsAppSDK/issues/3487

**Comment by bogdan-patraucean** [comment]
UP. This issue should not be part of https://github.com/microsoft/microsoft-ui-xaml/discussions/8638.

**Comment by DmitriyKomin** [comment]
This is fixed in WinUI3 with SystemBackdrop type and Mica/DesktopAcrylic that respond to theme change.
