### ISSUE TITLE
[WinUI][.NET 8.0 Preview 2] Unpackaged WinUI 3 desktop app failed with Not compatible errors

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8251]
### Describe the bug

Unpackaged C# WinUI 3 desktop app failed with 8 NU1201 errors when using .NET 8.0 Preview 2, but it can deploy successfully.
![image](https://user-images.githubusercontent.com/97647558/223042323-3f30d02a-be2c-4169-924c-097662040c09.png)

### Steps to reproduce the bug

**VS Build**: 17.6 Preview 3 - 33505.33main
**Repro Steps:** 
1. Install .NET 8 Preview 2 SDK: 
Feed: [https://pkgs.dev.azure.com/dnceng/public/_packaging/8.0.100-preview.2.23153.6-shipping/nuget/v3/index.json](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkgs.dev.azure.com%2Fdnceng%2Fpublic%2F_packaging%2F8.0.100-preview.2.23153.6-shipping%2Fnuget%2Fv3%2Findex.json&data=05%7C01%7Cv-dollywang%40microsoft.com%7C14a1be4ad59c4732fe6208db1dd90025%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638136590222829784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BK7CjE4zxHl56sFeEc71PQmkEvG4liegMLX7Rx7MsTo%3D&reserved=0) 
Artifacts: [Pipelines - Run 20230304.1-8.0.100-preview.2.23153.6-169162 artifacts (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2127876%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C01%7Cv-dollywang%40microsoft.com%7C14a1be4ad59c4732fe6208db1dd90025%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638136590222985996%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2WrIN%2BKEnJZeQAenW3XgglPKskG63ii4QxaH9CIIAnU%3D&reserved=0)
2. Create C# Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop)
3. Update the TargetFramework from "net6.0-windows10.0.19041.0" to "net8.0-windows10.0.19041.0"
4. Run he project.

**Actual Result:** 
App run successfully, but there are 8 errors in Error List.

### Expected behavior

Project run successfully without errors.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

NuGet package version: Windows App SDK 1.2.230217.4

**Comment by ShashankNay** [comment]
Have you tried running this as a Single-Project setup _(Blank App, Packaged (WinUI3 in Desktop)_?

Using the same .NET8 Preview build and the 1.3.230228005-preview1 WindowsApp SDK version I am able to successfully get this application running. Make sure to include `<WindowsPackageType>None</WindowsPackageType>` into your .csproj as well in order to run the application unpackaged.

**Comment by XamlTest** [comment]
@ShashankNay we tried with below scenarios:
1. Create a Blank App, Packaged (WinUI3 in Desktop project, application run successfully without any error.
2. Create Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop) project with .NET 6, application run successfully, but Error List have 8 errors.
3. Create Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop) project with .NET 8, and include <WindowsPackageType>None</WindowsPackageType> into my .csproj file, application cannot show up and Error List have 8 errors.

Please check my project: [WinUI-Unpackaged.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11405982/WinUI-Unpackaged.zip)
