### ISSUE TITLE
Contols do not give an error when a style that contains unsupported properties is assigned to them.

### ISSUE THREAD

**Issue by Donsroom** [microsoft/microsoft-ui-xaml#8254]
### Describe the bug

Controls allow their style to be set to styles that contain properties that are unsupported by the control. This can happen if a control's Style is set to a style that targets a control  type that is different to the type of the control the style is assigned to.

It appears that the Visual Studio IDE tolerates this and the application compiles without errors. The application will also run without errors when run from within the IDE. However, if run outside the IDE, the application will crash silently at the point the control is first referenced. In this case, there will be no indication of what caused the crash.

### Steps to reproduce the bug

These steps use a PasswordBox but the issue appears to affect any type of control.

1. Create an application that includes a PasswordBox control.
2. Assign a style to the PasswordBox Style property.
3. Make sure this style's TargetType is set to TextBox.
4. Make sure this style includes a property that is not supported by the PasswordBox control. For example IsReadOnly.
5. Compile the application.
6. Run the application outside of the Visual Studio IDE.

The application will crash at the point the PasswordBox is first referenced.

### Expected behavior

The xaml editor and/or Visual Studio IDE should give an error if a style is assigned to a control and that style targets a different type of control than the one being assigned to. Or, at least give an error if the assigned style contains setters for properties that are not supported by the control the style is being assigned to.

Note  that this currently seems to work correctly if the style targets the same type as the type of the control it is being assigned to. In this case it will give an error if the style contains setters for properties that are not supported by the control.

However, if the style targets a different type than the type of the control it is being assigned to no errors are thrown even if the style contains setters for properties that are not supported by the control. In this case, the application will compile and run properly inside the IDE but will crash silently when run outside the IDE.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.4: 1.2.230217.4

### Windows version

Windows 11 (22H2): Build 22621

**Comment by JJBrychell** [comment]
This appears to be fixed in 1.4.  

      <PasswordBox Style="{StaticResource DefaultTextBoxStyle}"/>
 
Message Cannot apply a Style with TargetType 'Microsoft.UI.Xaml.Controls.TextBox' to an object of type 'Microsoft.UI.Xaml.Controls.PasswordBox'.

**Comment by DmitriyKomin** [comment]
@Donsroom, thank you for reporting this. Per @JJBrychell's experiment we believe this is fixed now. Please comment here if you still see the issue on 1.4+.
