### ISSUE TITLE
Mica Does not apply on UserControl Embedded in a Page

### ISSUE THREAD

**Issue by avknaidu** [microsoft/microsoft-ui-xaml#8259]
### Describe the bug

When using `muxc:BackdropMaterial.ApplyToRootOrPageBackground="True"` on a page that contains `UserControl`, the background of "UserControl" remains unchanged. 

### Steps to reproduce the bug

- Create a new UWP Project with WinUI2
- Create a User Controls. Add it to `MainPage.xaml`
- Set `muxc:BackdropMaterial.ApplyToRootOrPageBackground="True"` on `MainPage.xaml`
- Run the project, you will see background of page transform with mica correctly. But not User Control. I tried changing the background to Transparent on UserControl. Still the same.

### Expected behavior

It should respect the background brush of parent and apply to itself unless explicitly set to something else.

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000

**Comment by sotanakamura** [comment]
I cannot reproduce the bug. The color of TextBlock background is the same as parent page with Mica.
```xaml
<!-- App.xaml -->
<Application
    x:Class="BlankApp1.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:BlankApp1"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls">

    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>

</Application>
```
```xaml
<!-- MainPage.xaml -->
<Page
    x:Class="BlankApp1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:BlankApp1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    muxc:BackdropMaterial.ApplyToRootOrPageBackground="True">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="ClickHandler" Background="Transparent" FontSize="50">Click Me</Button>
    </StackPanel>
</Page>
```
```cpp
// pch.h
#pragma once
#include <windows.h>
#include <unknwn.h>
#include <restrictederrorinfo.h>
#include <hstring.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.ApplicationModel.Activation.h>
#include <winrt/Windows.UI.Xaml.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
#include <winrt/Windows.UI.Xaml.Data.h>
#include <winrt/Windows.UI.Xaml.Interop.h>
#include <winrt/Windows.UI.Xaml.Markup.h>
#include <winrt/Windows.UI.Xaml.Navigation.h>
#include <winrt/Microsoft.UI.Xaml.Automation.Peers.h>
#include <winrt/Microsoft.UI.Xaml.Controls.Primitives.h>
#include <winrt/Microsoft.UI.Xaml.Media.h>
#include <winrt/Microsoft.UI.Xaml.XamlTypeInfo.h>
```

**Comment by avknaidu** [comment]
If the controls are directly in  the page it's fine. Try creating a User Control with a Button, and then use the User Control in the page, you will see it will not apply Mica on User Control.

**Comment by ranjeshj** [comment]
@avknaidu This is by design. Mica is supported only as the window backdrop. https://learn.microsoft.com/en-us/windows/apps/design/style/mica#mica
