### ISSUE TITLE
PathIconSource claims to support sharing but throws exception (AKA shared Geometry issue)

### ISSUE THREAD

**Issue by verelpode** [microsoft/microsoft-ui-xaml#827]
A very common requirement is to use the same icon/symbol in multiple different buttons/places within an app.  Nearly every non-trivial app needs this ability.  The documentation for [PathIconSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.pathiconsource) says this is supported:
> PathIconSource is similar to PathIcon. However, because it is not a FrameworkElement, it can be shared.

It says it can be shared but if you try to share it, ArgumentException (HResult=0x80070057) is thrown.  [SymbolIconSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symboliconsource) shares successfully but not PathIconSource.

Actually the underlying problem is that [Geometry](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.geometry) fails to share when you use the same Geometry instance with multiple instances of [IconSourceElement](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.iconsourceelement.iconsource) or [PathIcon](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.pathicon) or [Shapes.Path](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.shapes.path).

In comparison, the older WPF-Desktop does support sharing of Geometry instances provided that you first invoke [Geometry.Freeze (Freezable.Freeze)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.freezable.freeze).  Unfortunately UWP does not support Freeze.  (It supports [Style.Seal](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.style.seal) but not Freeze.)

To work around this problem in UWP, we're forced to clone the Geometry instances whenever they're used in multiple places (very wasteful!), but how should that be done?  UWP does not support the [System.Windows.Media.Geometry.Clone](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.geometry.clone) method.  For app authors to implement their own version of Clone is no small task because it requires manually copying all properties of all subclasses of Geometry, PathFigure, and all subclasses of [PathSegment](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.pathsegment).  Furthermore it's wasteful to have multiple clones of the same icons in RAM.  It's also a substantial performance hit because whenever you create a new instance of a Page or UserControl, you must first clone all the icons/Geometry instances that the Page uses.

The problem of cloning Geometry is further worsened by the fact that UWP also lacks support for the ["capacity" parameter](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.pointcollection.-ctor?view=netframework-4.8#System_Windows_Media_PointCollection__ctor_System_Int32_) in the constructor of [PointCollection](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.pointcollection) necessary for [PolyBezierSegment.Points](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.polybeziersegment.points) and other subclasses of PathSegment.  The missing "capacity" parameter means that when you clone a PointCollection, the internal data is repeatedly reallocated/resized unnecessarily.  This makes cloning even more expensive.

WPF-Desktop also has [System.Windows.Media.StreamGeometry](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.streamgeometry) which is great for making efficient shared path-based icons, but again this feature is missing in UWP unfortunately.

## Expected behavior
* [PathIconSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.pathiconsource) should do what the documentation says it does ("it can be shared"), meaning the ArgumentException should be eliminated.
* It would be nice if [Shapes.Path](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.shapes.path) also supports shared Geometry but this is non-essential if at least PathIconSource supports sharing.
* I like WPF's [Geometry.Freeze (Freezable.Freeze)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.freezable.freeze) (and also UWP's [Style.Seal](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.style.seal)) but I'd also be happy if the shared-icon solution is implemented in a different manner than Freeze or Seal.
* In any event, please also support the ["capacity" parameter](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.pointcollection.-ctor?view=netframework-4.8#System_Windows_Media_PointCollection__ctor_System_Int32_).  Even if the need for cloning is eliminated, the capacity parameter is still needed in other cases such as when deserializing a point list from a file, or when converting an SVG Path to a Xaml Geometry.  Any case of building a PathGeometry can benefit from the capacity parameter.
* Ideally UWP would also support an equivalent of [System.Windows.Media.StreamGeometry](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.streamgeometry), but the highest priority is to eliminate the ArgumentException when PathIconSource is shared.

**Comment by verelpode** [comment]
In response to a suggestion from @be5invis, here is more info on the icon topic.

Icons are a very important topic, considering that most apps uses multiple icons in multiple places in multiple kinds of GUI elements (icons in buttons, toolbars, menus, tabs, standalone, etc).  Thus it's surprising to observe that, currently, icon rendering hardly works in WinUI/UWP unfortunately.

### Example 1:
Look at a really simple case where you have an instance of `Windows.UI.Xaml.Media.Imaging.BitmapImage` that was produced from a PNG, and you want to use this PNG `BitmapImage` as an icon.  That should be super simple, right?  But no, unfortunately neither `Windows.UI.Xaml.Controls.BitmapIconSource` nor `Windows.UI.Xaml.Controls.BitmapIcon` support the ability to render a specified **instance** of `BitmapImage` -- surprising but true.

### Example 2:
You have an instance of `Windows.UI.Xaml.Media.PathGeometry` that you want to use as a monochrome vector icon in multiple places or pages in your app.  Again that should be super simple, right?  But no, unfortunately exceptions are thrown whenever you try to use/share the same instance of a `Geometry` in multiple different instances of `Windows.UI.Xaml.Controls.PathIconSource`, `Windows.UI.Xaml.Controls.PathIcon`, or `Windows.UI.Xaml.Shapes.Path`.

### Example 3:
You have an SVG file that you want to use as an icon in multiple places in your app.  Again you're out of luck because the SVG renderer contains bugs:  See issue https://github.com/microsoft/microsoft-ui-xaml/issues/825

**Comment by Mangepange** [comment]
Seems like this is still an issue. Are there currently no way of sharing data for PathIcons?

**Comment by KubaO** [comment]
This needs to be reopened. It is still a problem.
