### ISSUE TITLE
NavigationView move focus wrongly before animation finish

### ISSUE THREAD

**Issue by antoniohou** [microsoft/microsoft-ui-xaml#8279]
### Describe the bug

When i change navigation and move focus before selection indicator finish moving, the focus will skip the item between the animation.

### Steps to reproduce the bug

1. Open WinUI 2 Gallery
2. Go to NavigationView page
3. Click the fisrt navigation sample "menu Item2"
4. Click down
5. Click Enter
6. Click Up as fast as you can before animation finish

### Expected behavior

Focus change one by one. Not skipping anything.

### Screenshots

https://user-images.githubusercontent.com/7922655/224882026-2836b39d-3c25-4453-9901-105a34a08b01.mp4

### NuGet package version

None

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Xbox gamepad have the same behavior too.

**Comment by ojhad** [comment]
I was unable to repro this in the latest WinUI3 Gallery. If you are still seeing this there, please leave a comment.

**Comment by antoniohou** [comment]
@ojhad I can still see this using the latest WinUI3 Gallery. You should press up or down just after pressing enter. The focus will skip the icon before the animation finish.
