### ISSUE TITLE
Question: New default body FontSize - 14 epx or 15 epx?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#828]
Settings and Feedback hub, has moved to using a 14 epx value for it's main body FontSize.  Previously this default font size was 15epx.

Will the guidance and type ramp be updated along with WinUI 3.0?

**Comment by contextfree** [comment]
I think this change to the defaults has already been made as part of the Fluent Standard sizing introduced with Windows 10 version 1809: https://docs.microsoft.com/en-us/windows/uwp/design/style/spacing

**Comment by mdtauk** [comment]
> I think this change to the defaults has already been made as part of the Fluent Standard sizing introduced with Windows 10 version 1809: https://docs.microsoft.com/en-us/windows/uwp/design/style/spacing

Thank you for that article link - I knew I wasn't imagining the font size change
