### ISSUE TITLE
Scrollbar thumb does not shrink upon overscroll via touchpad or touchscreen

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#830]
**Describe the bug**

Scrollbar does not shrink open overscroll via touchpad/touchscreen

**Steps to reproduce the bug**

1. Open Start menu
2. Drag down

**Expected behavior**

Scrollbar would shrink like pre-conscious scrollbars or like IE

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)      | Yes   |
| April 2018 Update (17134)           | Yes  |
| Fall Creators Update (16299)        | No  |
| Creators Update (15063)              | No   |
| Anniversary Update (14393)         | No   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

I'm sorry if it's not in the scope of WinUI but I hope you can raise this issue with the people working on Windows just like the issue I submitted earlier on the Start Menu's missing backplate

**Comment by jevansaks** [comment]
Seems like a reasonable request. It's something we can look into post-WinUI 3.0.

**Comment by Poopooracoocoo** [comment]
It's still funny to me that the conscious scrollbar rewrite didnt implement this. Its not as funny as the task view and touch keyboard rewrites though as those impact me greatly

**Comment by Poopooracoocoo** [comment]
I noticed that when auto hiding scrollbars are disabled, all scrollbars will briefly be hidden and then expand.

**Comment by DragoCubed** [comment]
I've also noticed that when you scroll semi-fast the new scrollbar will be very choppy.

**Comment by micahl** [comment]
@DragoCubed choppy how?

**Comment by Poopooracoocoo** [comment]
It's definitely not in sync and a bit behind. Rather hard to explain without a recording. I'm easily able to reproduce it.

**Comment by DragoCubed** [comment]
@micahl

What happened? What changed with W10 v1803? Were you able to repro the choppiness?

**Comment by micahl** [comment]
@DragoCubed, dunno.  We did introduce the setting to keep scrollbars always visible with v1803.  Perhaps something with that change is related to the issue.  I haven't noticed any choppiness with the scrollbar on the start menu.  I assume that's where you're seeing the choppiness.  Any chance you have a video that demonstrates it?

**Comment by Poopooracoocoo** [comment]
@mmicahl I remember the choppiness being there before that setting was introduced. By the way, content doesn't get pushed when pushed when hiding scrollbars are disabled. If I record it I'll update this

**Comment by Poopooracoocoo** [comment]
On scrollbars: 

I've disabled auto-hide scrollbars and in XAML Controls Gallery, the NavigationView looks like this: 
![image](https://user-images.githubusercontent.com/51363864/63645608-cf885500-c745-11e9-9039-e78ac8da80d7.png)

**Comment by Poopooracoocoo** [comment]
[Spongebob voice and titlecard] 4541 issues later and almost four years later...

Now see #5371 for my nth time trying to get Microsoft to fix this. @jevansaks 

It's been 4 years since version 1803 came with "conscious scrollbars" that were probably made by an unconscious person bc they're annoying as lololol. And now we're at Windows 11. Not only have all of my issues been ignored on GitHub and the Feedback Hub, but this tiny thing would be MUCH better than annoying animated icons. At least those are just a tiny annoyance and don't actually confuse users like expanding UI elements... *looks at Alarms & Clock app*

**Comment by Poopooracoocoo** [comment]
Do not close

**Comment by DmitriyKomin** [comment]
@Poopooracoocoo, thank you for the proposal. Unfortunately, at this time the identified issue is not going to meet our bar for investigation.
