### ISSUE TITLE
Documentation is not clear about availability of WINUI 3 source code 

### ISSUE THREAD

**Issue by lucaregini** [microsoft/microsoft-ui-xaml#8306]
### Describe the bug

On the documentation front page I can read this:

**WinUI 3 is a part of the Windows App SDK family**

And this can lead to the wrong conclusion that the source code for WINUI 3 is on the Windows SDK repo. When I go there I am then pointed again to this repo. The reality is that WINUI 3 source code has not been made available yet.

### Steps to reproduce the bug

Just go on the frontpage of the documentation of this repo

### Expected behavior

Mention explicitly on the frontpage of this repository that the source code of WINUI 3 is not open source yet. That would avoid a lot of confusion.

### NuGet package version

None

**Comment by duncanmacmichael** [comment]
Closing this issue as the WinUI 3 source code was made available with the 1.4.2 release. As of the time of writing this comment, the latest release is for 1.4.3, available here:

https://github.com/microsoft/microsoft-ui-xaml/releases/tag/winui3%2Frelease%2F1.4.3
