### ISSUE TITLE
Drag file to application, but cursor icon is always ban state and no effect

### ISSUE THREAD

**Issue by HHHHHHHHHHHHHHHHHHHHHCS** [microsoft/microsoft-ui-xaml#8307]
### Describe the bug

I want to drag a file from outside the application and output the file address. 
But cursor icon is ban state. And after release the mouse, there is no effect.

### Steps to reproduce the bug

```XMAL
<TextBox x:Name="tbFilePath" Width="300" Height="50" AllowDrop="True" DragEnter="tbFilePath_DragEnter"
             Drop="tbFilePath_Drop" />
```

```C#

private void tbFilePath_DragEnter(object sender, DragEventArgs e)
{
	if (e.DataView.Contains(StandardDataFormats.StorageItems))
	{
		e.AcceptedOperation = DataPackageOperation.Copy;
	}
}

private async void tbFilePath_Drop(object sender, DragEventArgs e)
{
	if (e.DataView.Contains(StandardDataFormats.StorageItems))
	{
		var items = await e.DataView.GetStorageItemsAsync();
		if (items != null && items.Count > 0)
		{
			var file = items[0] as StorageFile;
			if (file != null)
			{
				tbFilePath.Text = file.Path;
			}
		}
	}
}

```

1. drag txt file into TextBox
2. cursor icon is ban state

### Expected behavior

TextBox.text show file path.

### NuGet package version

None

**Comment by castorix** [comment]
It works for me with :
       
        private void tbFilePath_DragOver(object sender, DragEventArgs e)
        {
            e.AcceptedOperation = Windows.ApplicationModel.DataTransfer.DataPackageOperation.Copy;
        }

and in XAML  :

`AllowDrop="True" DragOver="tbFilePath_DragOver"`

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
[DragTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11038127/DragTest.zip)
This is test demo.    

https://user-images.githubusercontent.com/14230366/226851985-572226e3-c83a-4f8e-9b98-a46ce40677fe.mp4

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
> It works for me with :
> 
> ```
>     private void tbFilePath_DragOver(object sender, DragEventArgs e)
>     {
>         e.AcceptedOperation = Windows.ApplicationModel.DataTransfer.DataPackageOperation.Copy;
>     }
> ```
> 
> and in XAML :
> 
> `AllowDrop="True" DragOver="tbFilePath_DragOver"`

I have uploaded the test demo and WPF can run.
Does WINUI require permissions?

**Comment by castorix** [comment]
> Can I take a look at your test demo? I have no clue about this problem now. thx

Same code as yours
I even tested your [DragTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11038127/DragTest.zip) sample and it works too (Windows 10 22H2)
