### ISSUE TITLE
Cannot build apps targeting net7.0-Windows10.0.x.x win MSAL Client is added

### ISSUE THREAD

**Issue by baskren** [microsoft/microsoft-ui-xaml#8314]
### Describe the bug

Add MSAL Client library to library project targeting net7.0-windows10.0.x (or net6.0-windows10.0.x + WindowsAppSDK) and project build fails with the following errors:
```
C:\Program Files\dotnet\sdk\7.0.300-preview.23122.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm'.
C:\Program Files\dotnet\sdk\7.0.300-preview.23122.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'win10-arm-aot'.
```

### Steps to reproduce the bug

1. Create library project targeting net7.0-windows10.0.18362
2. Add NuGet package reference to any version of MSAL between 4.26 and 4.51.
3. Build project

Sample Project: https://github.com/baskren/WinuiMsalFail

Build log for Sample Project: https://raw.githubusercontent.com/baskren/WinuiMsalFail/main/REFERENCE%20FILES/BuildLog.txt

### Expected behavior

Project builds and MSAL calls are available.

### Screenshots

n/a

### NuGet package version

WinUI 3 - Windows App SDK Preview 1: 1.3.230228005-preview1

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Have tried on the following NuGet package versions of WindowsAppSDK
- 1.1.3
- 1.2.230313.1
- 1.3.230228005-preview1

The following may or may not be related but the symptoms are different.
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2673
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3236
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3583
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3941\
- https://github.com/microsoft/microsoft-ui-xaml/issues/5143

However, the symptoms are the same as: https://github.com/dotnet/maui/issues/6052

**Comment by baskren** [comment]
Wow.  This is quite the hot potato

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4023

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3583#issuecomment-1561390685

Looks like no one want to fix this issue.  So, in other words, no MSAL for WinUI?!?!

**Comment by ghostidentity** [comment]
I have working msal integration targetting .net 7, yes MSAL is working but not yet for azure ad b2c. only b2b.

**Comment by baskren** [comment]
@ghostidentity : It's been a while since I've tried this.  What versions of netX.0-windows10.x.x.x.x,  MSAL, WindowsAppSDK, and Windows.SDK.BuildTols are you using?

**Comment by ghostidentity** [comment]
Here's the confirmation that its working. https://mtagab-my.sharepoint.com/:v:/g/personal/admin_mtagab_app/Ed7chTRhxAhLknz7Y7zp5aQBx9FVZXr49-PfgsCfceFpqQ?e=IgB5eM

**Comment by baskren** [comment]
@ghostidentity : great video.  Looking forward to learning which combination of NuGet packages you're using!

**Comment by baskren** [comment]
@ghostidentity : Seriously, what versions of WindowsAppSDK and MSAL NuGet packages are you using?  I still can't get this to work.

**Comment by ghostidentity** [comment]
appsdk: 1.3.230502000 , msal : Microsoft.Identity.Client-> 4.54.1

**Comment by massej** [comment]
I have the same issue @ghostidentity where is your video?

**Comment by bpulliam** [comment]
Since it is working, closing issue.
