### ISSUE TITLE
WinUI 3 self-contained, non-packaged desktop app crashes on Windows Server 2019

### ISSUE THREAD

**Issue by rcohn** [microsoft/microsoft-ui-xaml#8336]
Hello -

I work on a WinUI 3 self-contained, non-packaged desktop app, which works well on Windows 10 and Windows 11:

`<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>`
`<WindowsPackageType>None</WindowsPackageType>`

However, when I try starting the app on Windows Server 2019 (1809 OSB 17763.3887), the app crashes early in startup with an 0xc000027b exception, which is attributed to the Microsoft.ui.xaml.dll (version: 3.0.0.2206) module.  The app starts up (I'm told by our QA group) on a Windows 2022 server without this crash.

It was my understanding that, as a self-contained app, everything needed to run the app was contained in the app package - including all WindowsAppRuntime components.  On systems where the app does start up (Win10, Win11 and Server 2022), there are installed Windows App Runtime components (eg: Windows App Runtime DDLM). But it could be that these components are side effects of installing Microsoft store apps and don't matter for my app.

Really, my question is: what _else_ is needed beyond what is built into the WinUI 3 desktop app package to allow the app to start up and run?

Thank you for any advice/information that can be offered.

**Comment by JesseCol** [comment]
Hi, can you please use Microsoft.Windows.ApplicationModel.Resources.ResourceLoader instead?  Please let us know if this is still a problem for you.

**Comment by rcohn** [comment]
Hello @JesseCol -
Is there any reason to believe that the problem with ResourceLoader on Server 2019 will be any different?  Do you know of any fixes or updates that would address this problem?  It would be good to no longer have to exclude Server 2019 from the platforms that can run our WinUi3 app.  If we test and find that the problem still exists, would Microsoft raise the priority level in finding a fix for this?
Thank you.

**Comment by JesseCol** [comment]
Hi, unfortunately this repo doesn't handle issues related to Windows.ApplicationModel.Resources.ResourceLoader.
