### ISSUE TITLE
Unresponsive app on navigationViewItem radiobutton key down,  high cpu 

### ISSUE THREAD

**Issue by KWodarczyk** [microsoft/microsoft-ui-xaml#8343]
### Describe the bug

When using the minimalistic page below once you press tab -> tab -> down arrow, the app become unresponsive and CPU goes up significantly looks like  TabFocusNavigation="Cycle" + GroupName="somename" is strongly connected to this issue

```
<Page
    x:Class="WinUI3SimpleApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUI3SimpleApp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <NavigationView
        TabFocusNavigation="Cycle">
        <NavigationView.MenuItems>
            <NavigationViewItem>
                <RadioButton
                        IsTabStop="False"
                        GroupName="ThemeRadioButton">
                    <RadioButton.Template>
                        <ControlTemplate>
                            <Button Content="!"/>
                        </ControlTemplate>
                    </RadioButton.Template>
                </RadioButton>
            </NavigationViewItem>
        </NavigationView.MenuItems>
    </NavigationView>
</Page>
```

![image](https://user-images.githubusercontent.com/5243438/228851886-149f7c9c-d8e7-46b5-a3ed-cd1193b27fa1.png)

### Steps to reproduce the bug

copy paste xaml above and do tab -> tab -> down arrow

### Expected behavior

application should not freze

### Screenshots

![image](https://user-images.githubusercontent.com/5243438/228852132-5a5ff9be-1437-4c15-84c4-d0e985213c44.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ojhad** [comment]
This should be fixed in 1.4, please give it a try.
