### ISSUE TITLE
Directory.GetCurrentDirectory() points to C:\WINDOWS\system32

### ISSUE THREAD

**Issue by KWodarczyk** [microsoft/microsoft-ui-xaml#8349]
### Describe the bug

Directory.GetCurrentDirectory() retrns "C:\WINDOWS\system32" is this as designed ? is it safe to change that that using 
```System.IO.Directory.SetCurrentDirectory(System.AppDomain.CurrentDomain.BaseDirectory);```

### Steps to reproduce the bug

just run this code

```
namespace WinUI3SimpleApp
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            DataContext = this;

            string dir = Directory.GetCurrentDirectory();//returns "C:\WINDOWS\system32"
        }
    }
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/5243438/229113206-dabe1d87-cf43-407b-9012-daaa2b538b7a.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

### Windows version

Windows 11 (21H2): Build 22000

**Comment by castorix** [comment]
You can see this similar thread https://github.com/microsoft/WindowsAppSDK/discussions/2195

**Comment by KWodarczyk** [comment]
@DarranRowe  if it's expected, is safe then to change the path using System.IO.Directory.SetCurrentDirectory  ?

**Comment by DarranRowe** [comment]
Yes it is.
From everything written, the only reason why System32 is the working directory is due to no other directory being set. The package support framework simply sets the working directory to the directory supplied, so it is fine for you to just change the working directory yourself.
