### ISSUE TITLE
Proposal: Update strokes that are currently using 2px to 1px

### ISSUE THREAD

**Issue by sravya03** [microsoft/microsoft-ui-xaml#835]
# Proposal: Control border stroke consistency

## Summary
Across Windows products, applications are moving against using thicker 2px borders in favor of lighter 1px borders. This is to update default control visuals to use lighter borders to align with the majority of the visuals being drawn and implemented (except for GridView).

## Rationale
* Web and app ecosystems are a mix of styles
* Styles are emerging to enforce purpose and function
* Apps and shell turn of fstrokes, others lighten and deemphasize
* New design follow this trend, thus our updates should also follow

## Scope
| Capability| Priority |
|:--|:-|
| Developers are able to use WinUI2.2* package and without any work, get the new Windows visual style. | Must |
| Developers have flexibility to style values of border thickness without retemplating. (This is to be tracked by #1031.) | Should |
| Developers and end users experience control update that feel coherent with the same controls used by Fabric, Edge, and Xbox. | Should |

*Just using the next version #.

# Design details and visuals
**All form type style controls to get 1px border update.**
Button
DropDownButton
SplitButton
*add link to comp*

TimePicker entry point
ColorPicker controls on form
[Visual comp](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/chigy/borderstrokes/active/borderstrokes/images/Pickers%20cont%20....png)

ComboBox entry point
Editable ComboBox entry point (NOTE: Focus state's accent color border remains 2px)
DatePicker entry point
CalendarPicker entry point
[Visual comp](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/chigy/borderstrokes/active/borderstrokes/images/Pickers.png)

CheckBox
RadioButton
ToggleSwitch
[Visual comp](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/chigy/borderstrokes/active/borderstrokes/images/Selectors.png)

TextBox (NOTE: Focus state's accent color border remains 2px)
RichEditBox (NOTE: Focus state's accent color border remains 2px)
[Visual comp](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/chigy/borderstrokes/active/borderstrokes/images/Text%20Inputs.png)

TreeView's checkbox
[Visual comp](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/chigy/borderstrokes/active/borderstrokes/images/Tree%20View.png)

GridView's checkbox
*add link to comp*

## Open Questions
* Will this impact layout?

**Comment by jevansaks** [comment]
Will this proposal address the problem that Xbox has right now where their system apps disable the automatic scaling because they need finer control over the thickness of lines?

**Comment by mdtauk** [comment]
I have proposed this myself, and I believe Microsoft did discuss it, but was conflicted. @chigy

![buttons](https://user-images.githubusercontent.com/7389110/59224723-f31c1480-8bc6-11e9-9f18-643421d98466.png)
![Checks and Radios](https://user-images.githubusercontent.com/7389110/59224724-f31c1480-8bc6-11e9-8fba-33e7029bbb8f.png)
![combo boxes](https://user-images.githubusercontent.com/7389110/59224725-f3b4ab00-8bc6-11e9-946b-7c115cb3ace1.png)
![Flyouts](https://user-images.githubusercontent.com/7389110/59224726-f3b4ab00-8bc6-11e9-9074-f0c9e4c20d54.png)

**Comment by chigy** [comment]
> Will this proposal address the problem that Xbox has right now where their system apps disable the automatic scaling because they need finer control over the thickness of lines?

I do not believe so. I believe they use 1px. So we'd have to draw 0.5px to have them draw 1px at 200% scale factor.

**Comment by mdtauk** [comment]
> > Will this proposal address the problem that Xbox has right now where their system apps disable the automatic scaling because they need finer control over the thickness of lines?
> 
> @jevansaks , I do not believe so. I believe they use 1px. So we'd have to draw 0.5px to have them draw 1px at 200% scale factor.

Does Xbox still use those thin 1 epx borders for UI elements.  I thought that had been superseded by the new Filled in panels with 2 epx spacing between elements.

![080173](https://user-images.githubusercontent.com/7389110/59235789-148ef780-8beb-11e9-8374-9f93c72b4b67.jpg)

**Comment by chigy** [comment]
Added an open issue.

**Comment by mdtauk** [comment]
I posted this in the NumberBox issue, but I think it is relevant here now this is an open issue and a proposal being considered.

If the borders for the Text Field controls, as well as the pickers and other controls which share a design pattern.

![Comparing Similar Controls](https://user-images.githubusercontent.com/7389110/59379619-022dce80-8d4f-11e9-8fe3-835cee0b7fb3.png)

I have also added the Date/Time/Calendar pickers

**Comment by chigy** [comment]
> > > Will this proposal address the problem that Xbox has right now where their system apps disable the automatic scaling because they need finer control over the thickness of lines?
> > 
> > 
> > @jevansaks , I do not believe so. I believe they use 1px. So we'd have to draw 0.5px to have them draw 1px at 200% scale factor.
> 
> Does Xbox still use those thin 1 epx borders for UI elements. I thought that had been superseded by the new Filled in panels with 2 epx spacing between elements.
> 
*Removed image*
> 
> Of course there could be separate ThemeResources for when the DeviceFamily is Xbox.

@mdtauk , you are right, the Xbox design no longer uses the 1px line. However the answer to @jevansaks 's question remains the same. What we are doing here does not address the scaling issue.

**Comment by chigy** [comment]
> I posted this in the NumberBox issue, but I think it is relevant here now this is an open issue and a proposal being considered.

@mdtauk , not sure what you mean? Open issue is merely asking if we make the 2px line to 1px, does it make the control smaller and does it introduce layout issues. I did not mean to say we are redesigning all of the controls? Where did I make a mistake?

**Comment by chigy** [comment]
**Status update:** Reviewed with WinUI team and there was no immediate concern with the design's plan here to make the 2px lines to 1px other than the open issue around whether that impacts layout. Will be part of the consideration before a formal pitch is made to the group.

**Comment by mdtauk** [comment]
> > I posted this in the NumberBox issue, but I think it is relevant here now this is an open issue and a proposal being considered.
> 
> @mdtauk , not sure what you mean? Open issue is merely asking if we make the 2px line to 1px, does it make the control smaller and does it introduce layout issues. I did not mean to say we are redesigning all of the controls? Where did I make a mistake?

@chigy I think I may have mis-interpreted the intention behind this issue.  I thought the issue was asking if the borders should change, and so i contributed to the discussion.  I am still relatively new to using GitHub.

The reason I posted the image was to illustrate a conceptual approach to handling borders on control to provide a consistent visual language to indicate how a control would function.

As for the open question :- Most controls with a border are still measured from their outer dimensions.  Overlays will now have a shadow, but that shadow is not part of the bounding box for the controls.  The buttons within the bordered controls will need some adjustments in padding around the Icon to maintain the touch target sizing.

**Comment by LucasHaines** [comment]
We discussed as this scope for the Density work in 1809. One item that came up was the impact this may have on sight impaired users. I wish I had more concrete data on this, but we didn't pursue it during user research testing due to time and resources. Might be a good open question.

**Comment by mdtauk** [comment]
> We discussed as this change when scoping the Density work in 1809. One item that came up was the impact this may have on sight impaired users. I wish I had more concrete data on this, but we didn't pursue it during user research testing due to time and resources. Might be a good open question.

Sounds like a good consideration.  The focus state border would still be 2 epx thickness - but how High Contrast themes would adapt the controls needs to be considered too.

**Comment by mdtauk** [comment]
Will the Calendar Picker/View get a change in border thickness?
![image](https://user-images.githubusercontent.com/7389110/59702190-13fbef80-91ef-11e9-9038-2223a3ba3020.png)

![image](https://user-images.githubusercontent.com/7389110/59702317-5291aa00-91ef-11e9-89c0-9ee4574f8de6.png)


It will change the size of the control so will need some careful thought, considering the space between the 40 x 40 boxes would reduce.

![image](https://user-images.githubusercontent.com/7389110/59702519-d186e280-91ef-11e9-8a05-e350fcf66504.png)

![image](https://user-images.githubusercontent.com/7389110/59702699-35111000-91f0-11e9-9c41-bedda4d0481c.png)

**Comment by chigy** [comment]
**Update:** 
Reviewed the controls once again with the design team and decided to break out the GridView becoming 4px as they are not the same type of issue. I've opened issue #898.

**Comment by chigy** [comment]
> Will the Calendar Picker/View get a change in border thickness?
Thanks for asking. No, it will not.

The problem we are trying to solve with this border thickness update is to make the UI that is always visible lighter weight as we received it is a bit too accentuated unnecessarily. Calendar view's borders are designed so that it works with the hover state that gets user's attention (so we are not making it 1px as it could make it less visible). In other words, we do not have a problem with the CalendarView today so we are not going to go change it unless we identify an issue.

**Comment by mdtauk** [comment]
@chigy Thank you for the response
