### ISSUE TITLE
Binding GridView to collection that implements IItemsRangeInfo results in exception

### ISSUE THREAD

**Issue by anup-das** [microsoft/microsoft-ui-xaml#8350]
### Describe the bug

I have ported the Microsoft XamlDataVirtualization (Scenario1) code from UWP sample over to WinUI 3. Changing Windows.UI.Xaml namespace to Microsoft.UI.Xaml and CoreDispatcher to DispatcherQueue

The code should run but instead it results in an exception. I have narrowed it down to the x:Bind that is causing the exception

Call Stack
>	XamlDataVirtualization.dll!XamlDataVirtualization.App.InitializeComponent.AnonymousMethod__4_1(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e) Line 68	C#
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.UnhandledExceptionEventHandler.Do_Abi_Invoke(System.IntPtr thisPtr, System.IntPtr sender, System.IntPtr e)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	XamlDataVirtualization.dll!XamlDataVirtualization.Program.Main(string[] args) Line 31	C#

Exception message:
+		Exception	{"Source object type is not a projected type and does not inherit from a projected type. (Parameter 'value')"}	System.Exception {System.ArgumentException}

### Steps to reproduce the bug

Build and run the code attached.
[XamlDataVirtualization.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11128517/XamlDataVirtualization.zip)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by JaiganeshKumaran** [comment]
Does the collection implement IEnumerable or something as well?
