### ISSUE TITLE
WinUI Design : How can we set Window background color as Transparent

### ISSUE THREAD

**Issue by Anil8608** [microsoft/microsoft-ui-xaml#8353]

**Comment by castorix** [comment]
You can see this thread : [Proposal: Borderless transparent window background support in apps using WinUI #1247](https://github.com/microsoft/microsoft-ui-xaml/issues/1247)
(the method I posted with _SwapChainPanel_ can be improved (clickthrough, ...))

**Comment by cnbluefire** [comment]
A temporary solution
[cnbluefire/WinUI3TransparentBackground](https://github.com/cnbluefire/WinUI3TransparentBackground)

**Comment by chigy** [comment]
Issue appears to have been closed so closing the issue.
