### ISSUE TITLE
'No installed components were detected. (0x800F1000)' on assignment of control property

### ISSUE THREAD

**Issue by NandishNR** [microsoft/microsoft-ui-xaml#8355]
### Describe the bug

![image](https://user-images.githubusercontent.com/47853879/229508326-05773ca2-09be-4e6f-b5a9-e22a3f0ba225.png)

I have implemented loading of views dynamically through property binding. This works well only for the 1st time of launching the child window and loading views dynamically. However, if I close the 1st instance and open the child window instance 2nd time onwards and trying to load views leads to crash.

What is causing here to fail? also, all views loading 2nd time also newly created instances. 

### Steps to reproduce the bug

1. Open window and perform loading of view
2. Close first child window instance and main application still running
3. Open child window instance 2nd time and try to load views dynamically

### Screenshots

![WindowCrash](https://user-images.githubusercontent.com/47853879/229508586-3b910285-9a9d-4cac-bc50-e9233cb8528b.png)

### NuGet package version

None

**Comment by kondareddy** [comment]
Just added screenshot of XAML for better understanding.
![image](https://user-images.githubusercontent.com/1445374/229694478-b489b067-24c3-440f-9139-82b9de01363c.png)
code side dynamically assigning content dynamically
![image](https://user-images.githubusercontent.com/1445374/229694866-c968e311-37a4-44b2-9055-2efcc34c2bd0.png)

**Comment by NandishNR** [comment]
This issue is resolved by changing ContentControl to ContentPresenter in XAML view
