### ISSUE TITLE
TextBlock TextTrimming="CharacterEllipsis" doesn't work for long strings with BodyTextBlockStyle

### ISSUE THREAD

**Issue by MikeBarker-MSFT** [microsoft/microsoft-ui-xaml#8367]
### Describe the bug

The ellipsis trimming is not applied correctly on a TextBlock when:
a) `TextTrimming="CharacterEllipsis"`; and
b) A long string with no spaces is used for the Text property; and
c) `Style="{StaticResource BodyTextBlockStyle}"`

Example:
```xaml
        <TextBlock
            x:Name="textBlock"
            Text="Some text is not so very long but ThisIsAVeryLongLongLongWordStupidlyLongInfact indeed."
            Style="{StaticResource BodyTextBlockStyle}"
            Width="518"
            MaxLines="1"
            TextTrimming="CharacterEllipsis"
            />
```

![image](https://user-images.githubusercontent.com/36843930/230372751-be067ffa-47c0-4eff-b7c0-2c41a15f938e.png)

### Steps to reproduce the bug

Create a new WinUI3 project.
Add the following TextBlock to the MainWindow:

```xaml
        <TextBlock
            x:Name="textBlock"
            Text="Some text is not so very long but ThisIsAVeryLongLongLongWordStupidlyLongInfact indeed."
            Style="{StaticResource BodyTextBlockStyle}"
            Width="518"
            MaxLines="1"
            TextTrimming="CharacterEllipsis"
            />
```

### Expected behavior

Expected: The character trimming takes place at the end of the long text, with an ellipsis.

Actual: The text is cut-off early.

### Screenshots

![image](https://user-images.githubusercontent.com/36843930/230373033-170fa364-fd56-4664-8f7e-9b074bfd9729.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

**Comment by seven-mile** [comment]
Really annoying, do we have any workaround?
In fact, after inspect the text block using the VS xaml debug tools (select it and open the realtime property sidebar), the ellipsis works.

**Comment by JJBrychell** [comment]
This behavior is by design.

The TextBlock style that is being used indicates that text should be wrapped.  However, in the example code, it is set to a single line.  So what is happening is that the text is being wrapped to two lines (breaking at the beginning of the long word) and then being truncated to a single line so the ellipse is added to the end of the first line.  Add "TextWrapping='NoWrap'" and it will function as you expect.
