### ISSUE TITLE
winrt::Windows::UI::Xaml::Media::GeometryGroup Linker errors

### ISSUE THREAD

**Issue by ayanok** [microsoft/microsoft-ui-xaml#8368]
### Describe the bug

I'm Simply trying to use the Geometry Classes from winrt::Windows::UI::Xaml::Media and getting linker error `error LNK2001: unresolved external symbol "public: __cdecl winrt::Windows::UI::Xaml::Media::GeometryGroup::GeometryGroup(void)" (??0GeometryGroup@Media@Xaml@UI@Windows@winrt@@QEAA@XZ)`

Which is normally simply a missing header file. I am including:
`#include <winrt/Microsoft.UI.Xaml.Media.h>
#include <winrt/Microsoft.UI.Xaml.Shapes.h>

using namespace winrt::Windows::UI::Xaml::Media;
using namespace winrt::Microsoft::UI::Xaml::Shapes;

GeometryGroup group1 = GeometryGroup();
`

### Steps to reproduce the bug

In a Windows App SDK project simply try to use any of the Geometry classes in winrt::Windows::UI::Xaml::Media.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
> using namespace winrt::Windows::UI::Xaml::Media;

That should be `Microsoft` rather than `Windows` in there, yes?

**Comment by ayanok** [comment]
Well now I just feel silly. Thanks!
