### ISSUE TITLE
ColorPicker in ContentDialog in WinUI3 does not show spectrum always

### ISSUE THREAD

**Issue by vineetmishra82** [microsoft/microsoft-ui-xaml#8371]
### Describe the bug

For a project in WinUI3, I am inserting ColorPicker in a StackPanel to be shown under ContentDialoag progmatically.

```
`StackPanel stack = new StackPanel();
            stack.Children.Clear();
            stack.Spacing = 5.0;
 TextBox textBox = new TextBox();
            textBox.PlaceholderText = "Enter Team name";

            ComboBox country = new ComboBox();
            country.ItemsSource = CountryList;
            country.PlaceholderText = "Select Country";

            ColorPicker colorPicker = new ColorPicker();
            colorPicker.IsColorSpectrumVisible = true;
            colorPicker.IsAlphaEnabled= true;
            colorPicker.IsAlphaSliderVisible= true;

            stack.Children.Add(textBox);
            stack.Children.Add(country);
            stack.Children.Add(colorPicker);

            ContentDialog newTeam = new ContentDialog()
            {
                Title = "Create New Team",
                Content = stack,
                PrimaryButtonText = "Create",
                CloseButtonText = "Cancel"
            };

            newTeam.XamlRoot = this.Content.XamlRoot;
            var result = await getDialogResult(newTeam);
//And so on, the ContentDialog is working fine`
```

           

### Steps to reproduce the bug

A simple button click event which gives a ContentDialog popup

```
` private async void NewTeamButton_Click(object sender, RoutedEventArgs e)
        {
            StackPanel stack = new StackPanel();
            stack.Children.Clear();
            stack.Spacing = 5.0;

            TextBox textBox = new TextBox();
            textBox.PlaceholderText = "Enter Team name";

            ComboBox country = new ComboBox();
            country.ItemsSource = CountryList;
            country.PlaceholderText = "Select Country";

            ColorPicker colorPicker = new ColorPicker();
            colorPicker.IsColorSpectrumVisible = true;
            colorPicker.IsAlphaEnabled= true;
            colorPicker.IsAlphaSliderVisible= true;

            stack.Children.Add(textBox);
            stack.Children.Add(country);
            stack.Children.Add(colorPicker);

            ContentDialog newTeam = new ContentDialog()
            {
                Title = "Create New Team",
                PrimaryButtonText = "Create",
                CloseButtonText = "Cancel",
                Content = stack

           };

            newTeam.XamlRoot = this.Content.XamlRoot;
            var result = await getDialogResult(newTeam);`

```
### Expected behavior

The color spectrum some times shows and most of the times not.

On my lucky day 

![ColorSpectrumVisible](https://user-images.githubusercontent.com/60233390/230630184-feb17b75-0075-43e3-8d29-1b5664b6c7c6.PNG)

### Screenshots

On My Unlucky day and most of the time

![ColorSpectrumNotVisible](https://user-images.githubusercontent.com/60233390/230630265-073efa41-000f-40a5-a9b5-ce41c1f28ab2.PNG)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230217.4

### Windows version

Windows 10 (21H2): Build 19044

**Comment by JJBrychell** [comment]
A fix for this has been submitted and should be available in the 1.6 release.

There is a known issue with Loading/Loaded/Unload events that can cause an unloaded event to be fired when the element is in the tree.  This happens when an element is removed and readded to the tree in a single frame.  That is what is happening here.  The content dialog is remove and re-added to the tree to adjust z-order with the smoke layer causing the situation to arise.

The fix for the erroneous event is most likely too much of a breaking change for a dot release, so we have worked around it and in the color picker's Unloaded event we only discard the spectrum if element was not added back.
