### ISSUE TITLE
Deprecated icons used through-out the code!

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/microsoft-ui-xaml#8375]
### Describe the bug

As Microsoft has declared icon codes ranging E0** - E5** as deprecated (1) who-knows-how-long-ago, Microsoft should follow their own rules. Yet, up till now, there are loads of icon codes used in the repo. This is mostly notable in CJK context, where these icons show as "garbled chinese" characters. I've seen cases of people showing this bad UI even in the search bar in Windows Explorer. One of the most "core" things of Windows!

1) ![Message](https://user-images.githubusercontent.com/65828559/111816539-3f889e00-88dd-11eb-85f6-e9b0f0f65256.png)

### Steps to reproduce the bug

it's the code

### Screenshots

![image](https://user-images.githubusercontent.com/65828559/230734252-57d3f603-e38e-422b-9345-f07ba795450a.png)

### Additional context

| old icon | appearance     | new icon |
|----------|----------------|----------|
| E001    | ✔ | E73E      |
| 10A      | ✖              |          |
|          |                | 8BB ~close~    |
|          |                | 947 ~multiply~ |
|          | →              | 894 clear    |
|          |                | 711 ~cancel~   |
| 052      | 👁       | F78D |
| 26B      | chev.R.small | 970      |
| 26C      | chev.L.small | 96F      |
| 0E2      | chev.L       | 76B      |
| 0E3      | chev.R       | 76C      |
| 0E4      | chev.U       | 70E      |
| 0E5      | chev.D       | 70D      |
| 094,11A  | 🔎       | 721     |
| 00B      | 🖤   | B52      |
| 115      | ⚙     | 713      |

**Comment by Jay-o-Way** [comment]
Random example: ![image](https://user-images.githubusercontent.com/90539564/230774577-e2b81272-cf8b-4abd-8e75-68a42a8111f7.png)

**Comment by Jay-o-Way** [comment]
FYI @MarissaMatt @licanhua @codendone @StephenLPeters
This should be high priority _imo_

**Comment by Jay-o-Way** [comment]
@crutkas You know I've been pushing for this for a long time now - here & there. For some reason, it looks like this isn't getting much traction yet. If you see the weight of this issue, is there somebody "at the office" you would like to bring this to attention? Or should I do this myself?

**Comment by Jay-o-Way** [comment]
Are y'all ignoring me or something?

**Comment by Jay-o-Way** [comment]
Ping @kmahone

**Comment by kmahone** [comment]
Hi @Jay-o-Way, thanks for reporting.
@karkarl is investigating this.

**Comment by JJBrychell** [comment]
This was fixed in 1.4.  Old codepoints are currently being translated to the new ones.
