### ISSUE TITLE
Changing a tab's width in SizeToContent mode animates... s l o w l y

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#8384]
Regressed in WinUI 2.8. Didn't repro in 2.7

Simplest repro is the WinUI controls gallery:
![size-to-content-mux](https://user-images.githubusercontent.com/18356694/231292405-fac400df-17da-47af-af15-2288085bfce8.gif)

We're ingesting this in Terminal and this hits for anyone using `"tabWidthMode": "titleLength"`

**Comment by zadjii-msft** [comment]
(Pretty sure this was fixed in 2.8.4, in https://github.com/microsoft/microsoft-ui-xaml/pull/8430)

**Comment by DmitriyKomin** [comment]
Does not repro in WinUI3 Gallery (and WinUI2 Gallery). Resolving fixed.
