### ISSUE TITLE
Do you have any plans for WinUI3 XAML Islands

### ISSUE THREAD

**Issue by ClearSeve** [microsoft/microsoft-ui-xaml#8387]
Do you have any plans for WinUI3 XAML Islands

**Comment by Jay-o-Way** [comment]
Why>

**Comment by bpulliam** [comment]
Dup of #6293

**Comment by duncanmacmichael** [comment]
Closing this question as XAML Islands are out of experimental in 1.4 and are available for C++ apps, per the release notes.

https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel#xaml-islands-no-longer-experimental
