### ISSUE TITLE
TabItemsChanged doesn't seem to get raised anymore in WinUI 2.8

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/microsoft-ui-xaml#8388]
WinUI version: 2.8.2

downstream: https://github.com/microsoft/terminal/issues/15121

After updating to 2.8, Terminal's TabView no longer seems to raise `TabItemsChanged` events anymore. Breakpoints in the Terminal get hit for `TabDragStarting` and `TabDragCompleted`, but we don't get a `TabItemsChanged`. 

Looking at the diff between 2.7 and 2.8, it looks like there was some code added around `m_isDragging` which might end up filtering out the `TabItemsChanged` events. #6632 introduced the one I'm thinking of, and that was first available in a 2.8.0 prerelease.

I _think_ I can work around it with some finagling on my side, but this was a serious unexpected regression others might want to know about.

**Comment by mahara** [comment]
https://github.com/microsoft/microsoft-ui-xaml/pull/8420

**Comment by DHowett** [comment]
@zadjii-msft would you mind closing this one out now that we've verified it? thx!
