### ISSUE TITLE
Your package Microsoft.UI.Xaml.2.8 specifies version 8.2304.12003.0, but 8.2207.14002.0 is the minimum available version.

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#8394]
### Describe the bug

An update to Microsoft.UI.Xaml is causing Store submission issues yet again.

```
Your package Microsoft.UI.Xaml.2.8 specifies version 8.2304.12003.0, but 8.2207.14002.0 is the minimum available version.
```

### Steps to reproduce the bug

Update to 2.8.3 and submit app to Store

### Expected behavior

Microsoft should have some way to catch this by now. This isn't the first time the Store team and Microsft.Ui.Xaml team don't seem to be in sync in preventing submission issues.

### Screenshots

<img width="603" alt="image" src="https://user-images.githubusercontent.com/3663297/232180161-f96cc0f7-b15e-4a67-b3cf-2ecdf6256a4f.png">

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Raspberry-Monster** [comment]
I have met this bug too. It seems that it was caused by Microsoft which didn't update the UI.Xaml.2.8 or they uploaded a wrong version.

**Comment by Raspberry-Monster** [comment]
Thank you for replying me. I have tested it on virtual machine using appinstaller and it seems that the bug has been solved. I am really appreciate for your help. Have a great day!

**Comment by kmahone** [comment]
Thanks for confirming.

**Comment by jp-weber** [comment]
> @Raspberry-Monster @myokeeh the nuget package was published on 4/13, but the framework package didn't get published until 4/17, so there was a period of a couple of days where publishing to the Store would fail.
> 
> Can you try again now? Things should be unblocked now.

Is it possible to tune this in the future so that the nuget package is only released when the framework package has been already updated? Currently this leads to confusion.

**Comment by myokeeh** [comment]
@kmahone with the 2.8.4 release, was there another mistake that might be causing delays in flights getting past certification? I have a flight that I submitted early yesterday and a couple submission attempts since then, but it's getting stuck. No errors shown--just not progressing past "Certification"

**Comment by kmahone** [comment]
@myokeeh the 2.8.4 package was published to the Store before the nuget package went live, so it should not be hitting the issue that occurred with the 2.8.3 release.
