### ISSUE TITLE
Windows WebView2 ScriptDialogOpening CoreWebView2ScriptDialogOpeningEventArgsIt not useful

### ISSUE THREAD

**Issue by OMendozaG** [microsoft/microsoft-ui-xaml#8413]
### Describe the bug

But with CoreWebView2ScriptDialogOpeningEventArgs, you cannot tell it that it has not been intercepted and to finally launch the original, okay, this is not a bug, it is a feature proposal.

What is a bug, though, is that CoreWebView2ScriptDialogOpeningEventArgs has an Accept but no cancel. Therefore, in the case of a Confirm,

```
if (e.Kind == CoreWebView2ScriptDialogKind.Confirm) {
	if (Confirm(e.Message)) {
		e.Accept();
	}
}
```

There is no way for the confirm to return FALSE. Because if you not fire Accept, return of confirm( on javascript will be null.

This does not give me the tools to substitute the original behavior of Confirm since it can result in true or false.

Yes, I could do a workaround and intercept the result by JavaScript and if it is === null, transform it to false. But that is not a solution. CoreWebView2ScriptDialogOpeningEventArgs should allow me to substitute the original behavior of the events.

Also, as I said before, I do not understand why it does not have a return property that allows me to launch the default event despite having intercepted it.

### Steps to reproduce the bug

Create a WebView2
Intercept ScriptDialogOpening
Try to return false on the javascript confirm call.

### Expected behavior

Confirm dialog, by default, can be true or false.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

### Windows version

Windows Insider Build (xxxxx), Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044, Windows 10 (21H1): Build 19043, Windows 10 (20H2): Build 19042, Windows 10 (1809): Build 17763

**Comment by DmitriyKomin** [comment]
Thanks @champnic. Closing this bug to avoid duplication.
