### ISSUE TITLE
Window drag and caption buttons do not work when custom title bar is applied

### ISSUE THREAD

**Issue by ojh050118** [microsoft/microsoft-ui-xaml#8418]
### Describe the bug

I applied a custom title bar, but the dragging and caption buttons do not work. Occurs with package versions 1.2.230313.1 and 1.3.230331000.

### Steps to reproduce the bug

xaml:
```xaml
<Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="32"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Grid x:Name="AppTitleBar" Grid.Row="0">
            <Image x:Name="TitleBarIcon" Source="/Images/finder.png"
                   HorizontalAlignment="Left"
                   Width="16" Height="16"
                   Margin="8,0,0,0"/>
            <TextBlock x:Name="TitleTextBlock"
                Text="{x:Bind Title}"
                Style="{StaticResource CaptionTextBlockStyle}"
                VerticalAlignment="Center"
                Margin="28,0,0,0"/>
        </Grid>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center" Spacing="10" Grid.Row="1">
            <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
            <TextBox Name="TextBox" PlaceholderText="Text me" MinWidth="200"></TextBox>
        </StackPanel>
    </Grid>
```

CSharp:
```csharp
public MainWindow()
{
    InitializeComponent();

    SystemBackdrop = new MicaBackdrop();
    Title = TitleTextBlock.Text = "Remote Audio";
    ExtendsContentIntoTitleBar = true;
    SetTitleBar(AppTitleBar);
}
```

### Expected behavior

Window dragging and caption buttons all work.

### Screenshots

![custom title bar](https://user-images.githubusercontent.com/51792037/232234438-f18353cb-73d1-4a5b-b52e-a156aa844441.gif)

### NuGet package version

Windows App SDK 1.3 Preview 1: 1.3.230228005-preview1

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ojh050118** [comment]
This issue was resolved by recreating the project with the "Blank App, Packaged" project template instead of "Blank App, Package with Windows Application Packaging Project".
 I'll keep this thread open though.

**Comment by rocksdanister** [comment]
I have the same issue on my application running on visual studio:
https://github.com/rocksdanister/lively

Microsoft store version with winappsdk updated separately don't show this problem.
Switching to WinAppSDK method from WinUI3 for customizing titlebar fixed the issue for me in visual studio.

**Comment by pratikone** [comment]
Thanks for posting this. We are currently in process of improving this experience.  Meanwhile, I can suggest some workaround if possible. @ojh050118  does it still occur with latest release of WinAppSDK ?

**Comment by pratikone** [comment]
It has been fixed and now works fine.
<img width="1308" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/115935/2a27d829-8b77-485c-a193-949f85020858">
