### ISSUE TITLE
Proposal: Hover state preview

### ISSUE THREAD

**Issue by sravya03** [microsoft/microsoft-ui-xaml#842]
## Summary
When the control is hovered over, it draws the UI that is going to be added.

## Rationale
Align to app and web design to increase consistency.

## Open questions
* Does this help or maybe hinder user by creating a model that accidentally let users do things? Fabric has this model, do they have any data that indicate this is better?
**Because of the open question above, design team decided to halt this item for now.**

**Comment by chigy** [comment]
This item is currently halted as value prop of doing this is not fully understood.

**Comment by chigy** [comment]
### **Status update**
This proposal is moved to the future backlog for a later discussion. Until then, this item will not be acted on. Community members are welcome to continue adding comments, feedback, where this change is useful, or not so useful, etc.

**Comment by mdtauk** [comment]
I am not sure why Fabric Web implemented it, and I think as long as the hover state of the unchecked controls is clear and obvious - there is no need to include the check mark or radio bullet on hover

**Comment by chigy** [comment]
As far as I am aware, we have no plan to address this in the (immediate) future. We will open a new issue with reasons, etc. but closing this to keep the query clean.
