### ISSUE TITLE
Webview2 crash when console message event raises at N times

### ISSUE THREAD

**Issue by khoabui1412** [microsoft/microsoft-ui-xaml#8421]
### Describe the bug

Register an event:
```
CoreWebView2.GetDevToolsProtocolEventReceiver("Runtime.consoleAPICalled").DevToolsProtocolEventReceived += CoreWebView2_consoleAPICalled;
CoreWebView2.CallDevToolsProtocolMethodAsync("Runtime.enable", "{}");
```

when CoreWebView2_consoleAPICalled is received at N times, webview is crashed with "Access violation":
<img width="884" alt="image" src="https://user-images.githubusercontent.com/65955727/233560318-f394bb14-333d-4628-bb1f-aaef115a562b.png">

### Steps to reproduce the bug

Receive console message at n times

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by champnic** [comment]
@khoabui1412 I've moved this issue to the WebView2Feedback repo: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3807

**Comment by DmitriyKomin** [comment]
Thanks @champnic . Closing this issue to avoid duplication.
