### ISSUE TITLE
SystemBackdrop does not work correctly in multi window applications

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#8423]
### Describe the bug

When using mulitple windows in the same application that both have the SystemBackdrop property set, switching from one to the other does not correctly deactivate the effect.

### Steps to reproduce the bug

1. Run this repro project:
[MicaMultipleWindows.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11297991/MicaMultipleWindows.zip)

2. Click on the button to open a secondary window
3. Observe, the the first window will still have the mica background applied. Only switching away to different applications deactivates the effect.

### Expected behavior

Switching between multiple windows that use the backdrop effect should work correctly.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Windows App SDK 1.3 stable

**Comment by codendone** [comment]
[internal bug](http://task.ms/42963771)
