### ISSUE TITLE
When the app is maximized, the hidden taskbar cannot be triggered.

### ISSUE THREAD

**Issue by lgBlog** [microsoft/microsoft-ui-xaml#8431]
### Describe the bug

The taskbar is set to auto-hide. When the app is set to maximized, the taskbar does not appear when the mouse is moved to the bottom of the screen

### Steps to reproduce the bug

1.Create a new empty WinUI3 application.
2.Extend the content to the title bar.
```
      AppWindowTitleBar titleBar = this.AppWindow.TitleBar; 
      titleBar.ExtendsContentIntoTitleBar = true;
      titleBar.ButtonBackgroundColor = Colors.Transparent;
      titleBar.ButtonInactiveBackgroundColor = Colors.Transparent;
```
3.Set the taskbar to hidden mode.
4.Maximize the app
5. Move the mouse to the bottom of the screen

### Expected behavior

The hidden taskbar will be shown

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by yaira2** [comment]
This is still an issue in Windows App SDK 1.3.1

**Comment by yaira2** [comment]
Are there any updates on this issue? We're getting a lot of user complaints because of this.

**Comment by AgentRBY** [comment]
Any updates?

**Comment by BreeceW** [comment]
Here is a workaround:

C#
```csharp
[DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
static extern bool SetPropW(IntPtr hWnd, string lpString, IntPtr hData);
...
var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
SetPropW(hWnd, "NonRudeHWND", new IntPtr(1));
```

C++
```C++
#include <microsoft.ui.xaml.window.h>
...
const auto windowNative{ this->try_as<IWindowNative>() };
HWND hWnd{};
windowNative->get_WindowHandle(&hWnd);
SetPropW(hWnd, L"NonRudeHWND", reinterpret_cast<HANDLE>(TRUE));
```

The `NonRudeHWND` property is documented [here](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist2-markfullscreenwindow#remarks).

**Comment by yaira2** [comment]
@BreeceW thank you for the workaround. Looks like it did the trick.
