### ISSUE TITLE
UWP ListView Touch Unhandled Win32 Exception

### ISSUE THREAD

**Issue by Calphalon** [microsoft/microsoft-ui-xaml#8434]
### Describe the bug

I have a ListView in my UWP app. When I touch the ListView I sometimes get an Unhandled Exception as shown below:

> Unhandled exception at 0x00007FFB1D7BCFC4 (Windows.UI.Xaml.dll) in KOTHMain.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001FF7AA6BD00, 0x0000000000000005).

This is not caught by my App_UnhandledExcpetion handler, it just crashes the app.

From the Call Stack (attached) you can see this is some type of Touch HitTest exception. I have checked several other ListViews in my app, as well as GridViews, and they do not exhibit this behavior. Just one, on one page. Also, the ListView works fine with the mouse.

I have no idea what is causing this exception, nor how to handle it in any way.

Any help would be appreciated.

![Call Stack 2023-04-26](https://user-images.githubusercontent.com/101216848/234760264-837d8c4f-9ba3-48da-bf30-5e7d9173912a.png)

### Steps to reproduce the bug

Create a UPW Page with a ListView (see XAML Below).
Touch it randomly to select items and scroll.  After a few seconds, crash.

For what it's worth, here is my XAML:

```
<ListView x:Name="lstHelpItems" Grid.Row="1" Grid.Column="0" ItemsSource="{Binding Mode=OneTime, Source={StaticResource cvsHelpView}}" d:Background="LightGray" AccessKey="H" KeyTipPlacementMode="Top" TabIndex="0" Padding="0,0,20,0">
			<ListView.Resources>
				<SolidColorBrush x:Key="ListViewItemBackgroundSelected" Color="white" Opacity="0.0" />
				<SolidColorBrush x:Key="ListViewItemBackgroundPointerOver" Color="Black" Opacity="0.1"  />
				<SolidColorBrush x:Key="ListViewItemBackgroundSelectedPointerOver" Color="Black" Opacity="0.2"  />
				<SolidColorBrush x:Key="ListViewItemBackgroundPressed" Color="Black" Opacity="0.3"  />
				<SolidColorBrush x:Key="ListViewItemBackgroundSelectedPressed" Color="Black" Opacity="0.3"  />
			</ListView.Resources>
			<ListView.GroupStyle>
				<GroupStyle>
					<GroupStyle.HeaderTemplate>
						<DataTemplate x:DataType="local:HelpGrouping">
							<TextBlock Text="{x:Bind HelpCategoryText , FallbackValue=Category}" Style="{StaticResource KOTHCompletionListHeading}" TextWrapping="NoWrap"/>
						</DataTemplate>
					</GroupStyle.HeaderTemplate>
				</GroupStyle>
			</ListView.GroupStyle>
			<ListView.ItemContainerStyle>
				<Style TargetType="ListViewItem">
					<Setter Property="HorizontalContentAlignment" Value="Stretch"/>
				</Style>
			</ListView.ItemContainerStyle>
			<ListView.ItemTemplate>
				<DataTemplate x:DataType="local:HelpViewEntry">
					<Border BorderThickness="{x:Bind BorderThickness, Mode=OneWay}" BorderBrush="Black" Padding="5,5,5,5" Background="{StaticResource KOTHHelpEntryBackground}" Margin="-5,5,-5,5">
						<Grid x:Name="grdListViewItem" Width="auto" HorizontalAlignment="Stretch">
							<Grid.RowDefinitions>
								<RowDefinition Height="Auto"/>
							</Grid.RowDefinitions>
							<Grid.ColumnDefinitions>
								<ColumnDefinition Width="*"/>
							</Grid.ColumnDefinitions>
							<TextBlock x:Name="lblHelpTitleText" VerticalAlignment="Center" Grid.Row="0" Grid.Column="0" Text="{x:Bind HelpTitleText, Mode=OneTime}" HorizontalAlignment="Left" Style="{StaticResource KOTHCompletionListItem}" TextWrapping="NoWrap" Foreground="Black"/>
						</Grid>
					</Border>
				</DataTemplate>
			</ListView.ItemTemplate>
		</ListView>
```

### Expected behavior

I have several other ListViews on other pages that use almost the exact same XAML.  They do not exhibit this behavior.  Also, this one works with the mouse just fine.

I cannot say for sure what exact 'touch' causes the problem. I cannot prove it but having scrolled the ListView seems to be a pre-requisite.

I expect it not to crash, especially with an exception I cannot handle in any way.  

### Screenshots

See attached Call Stack image.

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Actually, WinUI2- 2.8.3 (just updated) - still has the problem.

**Comment by Calphalon** [comment]
I have attached a sample project that manifests the problem.  The issue seems to be with placing a ListView in a Grid Column that has the Width set to Auto.  If the Column Width is a fixed number or "*", no error.
[Test1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11349703/Test1.zip)

**Comment by ranjeshj** [comment]
@Calphalon does this repro with WinUI3/WinAppSDK ? 

The bar for UWP/WinUI2 fixes is very high. See here - https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2.

**Comment by Calphalon** [comment]
I am sorry, but I do not know the answer to your question. I have not used WinUI3 and will not do so until it supports Visual Basic, so apparently that may be never.  My sample app should provide you, the developers, with the information needed to test.  You note that you will only fix WinUI2 issues if they are business critical, but you do not note business critical for whom.  You are only hurting developers and users by your decision not to fix.

**Comment by DmitriyKomin** [comment]
@Calphalon, as @ranjeshj mentioned above, unfortunately we are not able to investigate WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)). I searched for this particular call stack and it has only been observed in the context of WniUI2. In light of that, I will go ahead and close it. 

RE VisualBasic support in WinApSDK, please add your thoughts/vote to https://github.com/microsoft/microsoft-ui-xaml/issues/7184.
