### ISSUE TITLE
The UWP/WPF project add WinUI Items occour errors CS0234 and CS0236

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8435]
### Describe the bug

Add a User Control (WinUI 3) to your UWP/WPF project and it should deploy successfully. But errors CS0234 and CS0236 appear in the Error List. If the UWP/WPF project does not support "Add about WinUI Items", it should be disabled.

### Steps to reproduce the bug

1. Create a C# UWP/WPF Core/WPF Framework project.
2. Right click the project->Add->New Items...->WinUi->User Control(WinUI 3).
3. Build the project.

Actual Result:
CS0234 and CS0236 errors show in the Error List. I am not sure if it is because WinUI items do not apply to these project, if so, could you please disable them? if not, could you please fix the errors?

Error Message:
![image](https://user-images.githubusercontent.com/97647558/234817658-97a6533f-08e6-45fc-b42f-66cbcf55f534.png)

### Expected behavior

Build the project successfully, or we should disable WinUI items for these projects.

### Screenshots

![image](https://user-images.githubusercontent.com/97647558/234815690-a2f3536d-873c-498c-9a31-b5f7942c094e.png)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This issue also reproduced on VS 16.11.26.

**Comment by Scottj1s** [comment]
UWP/WPF are not compatible with Microsoft UI XAML (WinUI3)
