### ISSUE TITLE
Winui3 : How to fetch values from Settings for display resolution and display orientation and add it to a combobox 

### ISSUE THREAD

**Issue by Mohan-Babblu** [microsoft/microsoft-ui-xaml#8437]
### Describe the bug

Hi,

I am working on a winui3 application , Where i have 2 combo box named display resolution & display orientation.
My requirement is that i need to fetch the data from display setting [Resolution & Orientation ]& and add the values to combox box.
 for each system resolution will change accordingly , so i can't hardcode the value i need to fetch data dynamically and need to add the value to  combo box

### Steps to reproduce the bug

1.Open display setting
2.check on display resolution and display orientation 
3.fetch those data in c# & add it to combobox

### NuGet package version

WinUI 3 - Windows App SDK Preview 1: 1.3.230228005-preview1

### Windows version

Windows 10 (21H2): Build 19044, Windows 10 (21H1): Build 19043, Windows 10 (20H2): Build 19042, Windows 10 (1809): Build 17763

**Comment by castorix** [comment]
One of the ways is with EnumDisplaySettings(Ex) :

            {
                DEVMODE devmode = new DEVMODE();
                devmode.dmSize = (short)Marshal.SizeOf(typeof(DEVMODE));
                bool bRet = EnumDisplaySettingsEx(IntPtr.Zero, ENUM_CURRENT_SETTINGS, ref devmode, 0);
                if (!bRet)
                {
                    devmode.dmSize = (short)Marshal.SizeOf(typeof(DEVMODE));
                    bRet = EnumDisplaySettingsEx(IntPtr.Zero, ENUM_REGISTRY_SETTINGS, ref devmode, 0);
                }
                Debug.WriteLine("Bits Per Pel : " + devmode.dmBitsPerPel);
                Debug.WriteLine("Display Frequency (Htz) : " + devmode.dmDisplayFrequency);
                Debug.WriteLine("Log Pixels : " + devmode.dmLogPixels);
                Debug.WriteLine("Pels Width : " + devmode.dmPelsWidth);
                Debug.WriteLine("Pels Height : " + devmode.dmPelsHeight);
                Debug.WriteLine("Position X : " + devmode.dmPositionX);
                Debug.WriteLine("Position Y : " + devmode.dmPositionY);
                float nRatio = (float)((float)devmode.dmPelsWidth / (float)devmode.dmPelsHeight);
                string sOrientation = "";
                if (nRatio > 1) sOrientation = "Landscape"; else sOrientation = "Portrait";
                Debug.WriteLine("Orientation : " + devmode.dmDisplayOrientation.ToString() + " (" + sOrientation +")");
            }

with :

        [DllImport("User32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
        public static extern bool EnumDisplaySettingsEx(IntPtr lpszDeviceName, int iModeNum, ref DEVMODE lpDevMode, int dwFlags);

        public const int ENUM_CURRENT_SETTINGS = -1;
        public const int ENUM_REGISTRY_SETTINGS = -2;

        public const int EDS_RAWMODE = 0x00000002;
        public const int EDS_ROTATEDMODE = 0x00000004;

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        public struct DEVMODE
        {
            private const int CCHDEVICENAME = 32;
            private const int CCHFORMNAME = 32;

            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = CCHDEVICENAME)]
            public string dmDeviceName;
            public short dmSpecVersion;
            public short dmDriverVersion;
            public short dmSize;
            public short dmDriverExtra;
            public int dmFields;
            public int dmPositionX;
            public int dmPositionY;
            public DISPLAYORIENTATION dmDisplayOrientation;
            public int dmDisplayFixedOutput;
            public short dmColor;
            public short dmDuplex;
            public short dmYResolution;
            public short dmTTOption;
            public short dmCollate;
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = CCHFORMNAME)]
            public string dmFormName;
            public short dmLogPixels;
            public int dmBitsPerPel;
            public int dmPelsWidth;
            public int dmPelsHeight;
            public int dmDisplayFlags;
            public int dmDisplayFrequency;
            public int dmICMMethod;
            public int dmICMIntent;
            public int dmMediaType;
            public int dmDitherType;
            public int dmReserved1;
            public int dmReserved2;
            public int dmPanningWidth;
            public int dmPanningHeight;
        }

        public enum DISPLAYORIENTATION : int
        {
            DMDO_DEFAULT = 0,
            DMDO_90 = 1,
            DMDO_180 = 2,
            DMDO_270 = 3
        }

**Comment by Mohan-Babblu** [comment]
> One of the ways is with EnumDisplaySettings(Ex) :
> 
> ```
>         {
>             DEVMODE devmode = new DEVMODE();
>             devmode.dmSize = (short)Marshal.SizeOf(typeof(DEVMODE));
>             bool bRet = EnumDisplaySettingsEx(IntPtr.Zero, ENUM_CURRENT_SETTINGS, ref devmode, 0);
>             if (!bRet)
>             {
>                 devmode.dmSize = (short)Marshal.SizeOf(typeof(DEVMODE));
>                 bRet = EnumDisplaySettingsEx(IntPtr.Zero, ENUM_REGISTRY_SETTINGS, ref devmode, 0);
>             }
>             Debug.WriteLine("Bits Per Pel : " + devmode.dmBitsPerPel);
>             Debug.WriteLine("Display Frequency (Htz) : " + devmode.dmDisplayFrequency);
>             Debug.WriteLine("Log Pixels : " + devmode.dmLogPixels);
>             Debug.WriteLine("Pels Width : " + devmode.dmPelsWidth);
>             Debug.WriteLine("Pels Height : " + devmode.dmPelsHeight);
>             Debug.WriteLine("Position X : " + devmode.dmPositionX);
>             Debug.WriteLine("Position Y : " + devmode.dmPositionY);
>             float nRatio = (float)((float)devmode.dmPelsWidth / (float)devmode.dmPelsHeight);
>             string sOrientation = "";
>             if (nRatio > 1) sOrientation = "Landscape"; else sOrientation = "Portrait";
>             Debug.WriteLine("Orientation : " + devmode.dmDisplayOrientation.ToString() + " (" + sOrientation +")");
>         }
> ```
> 
> with :
> 
> ```
>     [DllImport("User32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
>     public static extern bool EnumDisplaySettingsEx(IntPtr lpszDeviceName, int iModeNum, ref DEVMODE lpDevMode, int dwFlags);
> 
>     public const int ENUM_CURRENT_SETTINGS = -1;
>     public const int ENUM_REGISTRY_SETTINGS = -2;
> 
>     public const int EDS_RAWMODE = 0x00000002;
>     public const int EDS_ROTATEDMODE = 0x00000004;
> 
>     [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
>     public struct DEVMODE
>     {
>         private const int CCHDEVICENAME = 32;
>         private const int CCHFORMNAME = 32;
> 
>         [MarshalAs(UnmanagedType.ByValTStr, SizeConst = CCHDEVICENAME)]
>         public string dmDeviceName;
>         public short dmSpecVersion;
>         public short dmDriverVersion;
>         public short dmSize;
>         public short dmDriverExtra;
>         public int dmFields;
>         public int dmPositionX;
>         public int dmPositionY;
>         public DISPLAYORIENTATION dmDisplayOrientation;
>         public int dmDisplayFixedOutput;
>         public short dmColor;
>         public short dmDuplex;
>         public short dmYResolution;
>         public short dmTTOption;
>         public short dmCollate;
>         [MarshalAs(UnmanagedType.ByValTStr, SizeConst = CCHFORMNAME)]
>         public string dmFormName;
>         public short dmLogPixels;
>         public int dmBitsPerPel;
>         public int dmPelsWidth;
>         public int dmPelsHeight;
>         public int dmDisplayFlags;
>         public int dmDisplayFrequency;
>         public int dmICMMethod;
>         public int dmICMIntent;
>         public int dmMediaType;
>         public int dmDitherType;
>         public int dmReserved1;
>         public int dmReserved2;
>         public int dmPanningWidth;
>         public int dmPanningHeight;
>     }
> 
>     public enum DISPLAYORIENTATION : int
>     {
>         DMDO_DEFAULT = 0,
>         DMDO_90 = 1,
>         DMDO_180 = 2,
>         DMDO_270 = 3
>     }
> ```

Hi @castorix ,

This code will display the current selected resolution and orientation, But the things is for me i need to fetch all the data's like ["1920x1080", "1680x1050", "1600x900", "1366x768"] from display settings and i need add this data's to my combobox.

**Comment by volvereabhi** [comment]
How to get display scale value ?

**Comment by castorix** [comment]
> How to get display scale value ?

You can use [XamlRoot.RasterizationScale](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.xamlroot.rasterizationscale?view=windows-app-sdk-1.1)
(or APIs like _GetScaleFactorForMonitor_ )

**Comment by duncanmacmichael** [comment]
Closing as this question appears to have been answered.
