### ISSUE TITLE
WinUI 3: Context MenuFlyout disappears upon deleting newest item or item at last index of StackPanelBug title

### ISSUE THREAD

**Issue by VitorX** [microsoft/microsoft-ui-xaml#8438]
### Describe the bug

This bug was original report from Q&A forum post below, and **this issue is only reproduced in C++ project**. The C# project works well.
https://learn.microsoft.com/en-us/answers/questions/1245561/winui-3-context-menuflyout-disappears-upon-deletin

_I am trying to create a list of elements within a StackPanel where each child element has a right-click context menu with two items: Insert and Delete. Insert adds a new element right after the target of the right-click, and Delete removes the target element. The issue is that the context menu becomes blank/disappears in the following two cases:_

_Before any insertions are made, deleting the last element in the StackPanel (1a and 1b in the screenshot below).
After inserting new items, deleting the last/newest inserted element in the StackPanel (2a and 2b in the screenshot below). winui-context-screens_
[
![image](https://user-images.githubusercontent.com/12635993/233548018-49338ba3-8335-4a2b-9b02-7312e0914f75.png)
](url)

### Steps to reproduce the bug

1. clone the code from [here]( https://github.com/dhaval-ceva/winui3-context-menu-issue-mwe)
2. Run the project and right click the 'Child 4' button and click 'delete'
3. Then right click other buttons, the menu flyout becomes blank/disappears

### NuGet package version

Windows App SDK 1.3.0: 1.3.230331000

**Comment by ranjeshj** [comment]
@VitorX does this happen only when removing the element to which the context menu is parented to ? What if a different element is removed? Also, can you please verify if this is fixed in WASDK 1.4 ? Thanks!
