### ISSUE TITLE
Proposal: Change pivot text sizes

### ISSUE THREAD

**Issue by sravya03** [microsoft/microsoft-ui-xaml#844]
# Proposal: Introduce smaller size pivot header

## Summary
We have seen many applications using smaller pivot header compared to the one we provide by default. This is to make it available to developers through light weight styling way.

## Rationale
* We are providing Pivot that people are likely modify because they are too big.
* Updating Pivot text does not change the footprint of the control in a seamless way.

## Scope
| Capability| Priority |
|:--|:-|
| Developers will not see anything changed when using WinUI2.2* package. | Must |
| Developers are able to use light weight styling to create smaller size header for Pivot control easily. | Must |
| Developers and end users experience control update that feel coherent with the same controls used by Fabric, Edge, and Xbox. | Should |

*Timing here is not a commitment, but to follow the release cycle. Just using the next version #.

## Design details and visuals
This impacts Pivot control.
[Visual comp](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/chigy/ControlUpdates/active/ControlUpdates/images/Pivot.png)

## Open Questions
* Is this a priority and where is this used inside shell surfaces?
* Is Pivot the right control to use or is NavView?

**Comment by mdtauk** [comment]
Please could you reduce the space between the Pivot Title and the Pivot Item Headers.

![image](https://user-images.githubusercontent.com/7389110/59223803-c23ae000-8bc4-11e9-8867-27da0e3bb18b.png)

**Comment by chigy** [comment]
Added a few open questions.

**Comment by mdtauk** [comment]
If the Pivot is no longer to be used as a top level control, then the Pivot Title would be more like a control Header, and the pivots would not need to appear as if they were page headings.

This is obviously a big change to the control, so I think you should include a style which preserves both a top level, and body level style to the control.

![image](https://user-images.githubusercontent.com/7389110/59381254-e6c4c280-8d52-11e9-8004-6bc0ccf4d26f.png)

**Comment by chigy** [comment]
>If the Pivot is no longer to be used as a top level control

@mdtauk , Curious. Where did you come to this conclusion?

**Comment by mdtauk** [comment]
> > If the Pivot is no longer to be used as a top level control
> 
> @mdtauk , Curious. Where did you come to this conclusion?

#848

>  We certainly want to support touch/tablet features, but not necessarily on the Pivot control. While Pivot is definitely not deprecated, we're not adding new features to this control. _We think that scenarios that used to be achieved with Pivot are now better served using NavigationView or (upcoming) TabControl._
>
emphasis mine

**Comment by chigy** [comment]
@mdtauk , thanks. There is no firm consensus about the Pivot control and we are still walking through what it means. At minimum, we would need to support apps that already use them and I do not want to break those customers with this change, thus some idea around a new size as an option was added to the proposal.

That said, as @YuliKl mentions, there is not much engineering priority put on this control today, so we might not proceed with this proposal.

So I don't want you to spend a lot of energy on this proposal. That said, to help you push your design ideas forward for other topics like this, it would be helpful if your suggestions were to come with examples in the context. How the control is used inside typical apps and why your proposal better support those apps.

**Comment by mdtauk** [comment]
@chigy  My familiarity with the pivot control goes back to Windows Phone, and the design it had back then.  I don't have any super strong feelings about the control design, other than the gap between Title and Item Headings being uncomfortably large.

It was only the proposal showing up that made me think about it.  And so I wanted to share my thoughts.

**Comment by chigy** [comment]
> @chigy My familiarity with the pivot control goes back to Windows Phone, and the design it had back then. I don't have any super strong feelings about the control design, other than the gap between Title and Item Headings being uncomfortably large.
> 
> It was only the proposal showing up that made me think about it. And so I wanted to share my thoughts.

@mdtauk, sounds good!

Possibly totally side tracking, but I thought you might appreciate this back story... I was a PM who worked with design to bring Pivot control to phone originally. :) I know the evolution of this control first hand. It is a bit awkward design nowadays since it originated from phone where it celebrated space and had a lot of built in "phone-ness" that didn't quite work out on other devices. Also, we have always been limited in what we can change because we cannot break customers.

**Comment by mdtauk** [comment]
> Possibly totally side tracking, but I thought you might appreciate this back story... I was a PM who worked with design to bring Pivot control to phone originally. :) I know the evolution of this control first hand. It is a bit awkward design nowadays since it originated from phone where it celebrated space and had a lot of built in "phone-ness" that didn't quite work out on other devices. Also, we have always been limited in what we can change because we cannot break customers.
>
Wonderful story!  The translation from Phone to WinRT was difficult, as people saw it in the same way as Tabs.
And now Tabs are coming, it does feel like it could be a little too heavy a control to use, where Pivot could become quite light weight.

**Comment by shaheedmalik** [comment]
> > @chigy My familiarity with the pivot control goes back to Windows Phone, and the design it had back then. I don't have any super strong feelings about the control design, other than the gap between Title and Item Headings being uncomfortably large.
> > It was only the proposal showing up that made me think about it. And so I wanted to share my thoughts.
> 
> @mdtauk, sounds good and thanks for sharing!
> 
> Possibly totally side tracking, but I thought you might appreciate this back story... I was a PM who worked with design to bring Pivot control to phone originally. :) I know the evolution of this control first hand. It is a bit awkward design nowadays since it originated from phone where it celebrated space and had a lot of built in "phone-ness" that didn't quite work out on other devices. Also, we have always been limited in what we can change because we cannot break customers.

You did good with that. Tablets greatly benefited from that feature not just phones. When it was taken away users were forced to tap on everything.

Is it possible for the features of pivots be implemented into the Tab Control?

**Comment by chigy** [comment]
>Is it possible for the features of pivots be implemented into the Tab Control?

@shaheedmalik , which features do you need and how you envision using them? If you have list of those, please have them in a new proposal so we can discuss. What our current thinking, though, Pivot is more suitable for mobile devices that people are not building using WinUI and it might be premature to add any of these features until/unless the needs arise. That said, you might already have the needs that we are not aware and we'd like to find out. (@YuliKl FYI)

**Comment by chigy** [comment]
@Poopooracoocoo , you seem confused about one of my comments. Do you want to share what's on your mind?

**Comment by YuliKl** [comment]
> When it was taken away users were forced to tap on everything.

@shaheedmalik, @Poopooracoocoo, I apologize if my comments in #848 have resulted in confusion. Pivot has not been taken away. The control is still part of Xaml, it's still available for app developers to use, it still responds to touch gestures as before.

I marked #848 as "declined" because we have very finite resources and can't make every update that you, our customers, want us to make. We need to make hard choices and assign priorities to the work you ask us to do. The unfortunately reality is that we won't prioritize making improvements to Pivot in the foreseeable future, and I didn't want an open proposal to sit around collecting dust and being ignored.

**Comment by Poopooracoocoo** [comment]
@chigy 
It's because you said 
> That said, as @YuliKl mentions, there is not much engineering priority put on this control today, so we might not proceed with this proposal.

My issue was closed and will probably be forgotten about forever. I understand that you need to prioritise things (I'm on GitHub, of course I understand that lol) but marking it as declined just shows me that it will be ignored forever. A lot of projects use open issues to see what they can work on and use milestones (iirc) to priortise. I even think Windows Calculator does this (but Microsoft is massive so I don't blame y'all). 

> The unfortunately reality is that we won't prioritize making improvements to Pivot in the foreseeable future, and I didn't want an open proposal to sit around collecting dust and being ignored.

This makes me a bit sad as tabs don't replace pivots. To me they're like win32 tabs while the WinUI tabs seem to suit browsers, Office, Terminal and Adobe products but not something like the File Explorer properties window as I mentioned in #848 . They aren't static tabs.

**Comment by shaheedmalik** [comment]
> When it was taken away users were forced to tap on everything.
> 
> @shaheedmalik, @Poopooracoocoo, I apologize if my comments in #848 have resulted in confusion. Pivot has not been taken away. The control is still part of Xaml, it's still available for app developers to use, it still responds to touch gestures as before.
> I marked #848 as "declined" because we have very finite resources and can't make every update that you, our customers, want us to make. We need to make hard choices and assign priorities to the work you ask us to do. The unfortunately reality is that we won't prioritize making improvements to Pivot in the foreseeable future, and I didn't want an open proposal to sit around collecting dust and being ignored.

Correct. It wasn't taken away, developers are using TabControl and NavigationView in lieu of using the Pivot control. Which in essence, is taken away from the user. The developer still has the ability to use it, but these two controls aren't as user friendly for tablet use.

**Comment by chigy** [comment]
### **Status update**
This proposal is moved to the future backlog for a later discussion. Until then, this item will not be acted on. Community members are welcome to continue adding comments, feedback, where this change is useful, or not so useful, etc.
@mdtauk , @shaheedmalik, @Poopooracoocoo, @YuliKl FYI

**Comment by mdtauk** [comment]
I think when this is looked at again, both for the selection indicator, usage, and font sizes - there should be some consistency brought to it in WinUI, FastDNA, and FluentUI

![image](https://user-images.githubusercontent.com/7389110/79628877-1562b500-813d-11ea-8f17-e5c95097fd05.png)

**Comment by chigy** [comment]
We are recommending people use NavigationView control rather than Pivot control. We do not have a plan to maintain this control at the moment so closing the item.

**Comment by shaheedmalik** [comment]
> We are recommending people use NavigationView control rather than Pivot control. We do not have a plan to maintain this control at the moment so closing the item.

Shouldn't the properties of pivot be merged into NavigationView?

**Comment by chigy** [comment]
@shaheedmalik , please let me know if there are any properties that Pivot has that NavigationView doesn't that will cause problem. Other than swipe to move to next pivot which is primarily a mobile concept, we couldn't identify any, thus reaching this decision.
