### ISSUE TITLE
Unexpected warning when building C++ Packaging Project

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8440]
### Describe the bug

Create a C++ Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop) and Build, but a warning show in the Error List.

### Steps to reproduce the bug

1.Create a new C++ Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop). In the following dialog box, set the Target version to Windows 10, version 2004 (build 19041) and Minimum version to Windows 10, version 1809 (build 17763) and then click OK.
2.Build the project.

Actual Result: A warning show in the Error List.

### Expected behavior

No Errors or Warning in Error List.

### Screenshots

![image](https://user-images.githubusercontent.com/97647558/235040481-8ec064d0-04bf-4033-996e-4db8a6f32ef7.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.0: 1.3.230331000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This issue repo on VS 16.11.26, not repro on latest main17.7.0 Preview 1.0 [33627.278.main].
Platform Toolset are set to Visual Studio 2019 (v142).

**Comment by Scottj1s** [comment]
The warning is being generated by Visual Studio's Desktop Bridge targets
