### ISSUE TITLE
WinUI 3: x:Bind codegen is broken and produce infinite setter calling while using with TwoWay mode

### ISSUE THREAD

**Issue by Malstraem** [microsoft/microsoft-ui-xaml#8441]
### Describe the bug

`x:Bind` with `TwoWay` calls setter until the stack is overflow.

WIth xaml
```xaml
<Grid>
    <ListBox ItemsSource="{x:Bind viewModel.Foos}"
             SelectedItem="{x:Bind viewModel.SelectedFoo, Mode=TwoWay}"/>
</Grid>
```
we have code gen

```csharp
private void Update_viewModel_SelectedFoo(global::BindSetterCalling.Foo obj, int phase)
{
    if ((phase & ((1 << 0) | NOT_PHASED | DATA_CHANGED)) != 0)
    {
        // MainWindow.xaml line 10
        if (!isobj2SelectedItemDisabled)
        {
            XamlBindingSetters.Set_Microsoft_UI_Xaml_Controls_Primitives_Selector_SelectedItem(this.obj2, obj, null);
        }
    }
}
private void UpdateTwoWay_2_SelectedItem()
{
    if (this.initialized)
    {
        if (this.dataRoot != null)
        {
            if (this.dataRoot.viewModel != null)
            {
                this.dataRoot.viewModel.SelectedFoo = (global::BindSetterCalling.Foo)this.obj2.SelectedItem;
            }
        }
    }
}
```

The problem is probably that the value of the `isobj2SelectedItemDisabled` never changes and is always `false`

Also there is method which never calling (but probably resolve the problem?)
```csharp
public void Disable(int lineNumber, int columnNumber)
{
    if (lineNumber == 10 && columnNumber == 14)
    {
        isobj2ItemsSourceDisabled = true;
    }
    else if (lineNumber == 11 && columnNumber == 14)
    {
        isobj2SelectedItemDisabled = true;
    }
}
```

### Steps to reproduce the bug

Open [Bind.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11352010/Bind.zip) and start debugging packaged target. Click on any listbox item.

### Expected behavior

`Binding` have not this problem and works as expected. With xaml

```xaml
<Grid DataContext="{x:Bind viewModel}">
    <ListBox ItemsSource="{x:Bind viewModel.Foos}"
             SelectedItem="{Binding SelectedFoo, Mode=TwoWay}"/>
</Grid>
```
setter execute once.

`x:Bind` should work like  `Binding`.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.0: 1.3.230331000

**Comment by kmgallahan** [comment]
By default x:Bind is updated on every observed PropertyChanged notification and **doesn't check for value equality**. 

You dispatch a new notification each time the property setter is called, which keeps triggering the binding over and over again.

Boilerplate INotifyPropertyChanged code is usually taken care of automatically these days via Roslyn Code Generators or Fody. Both of these handle equality checking automatically.

CommunityToolkit:

``` cs
public string? Name
{
    get => name;
    set
    {
        if (!EqualityComparer<string?>.Default.Equals(name, value))
        {
            OnNameChanging(value);
            OnPropertyChanging();
            name = value;
            OnNameChanged(value);
            OnPropertyChanged();
        }
    }
}

partial void OnNameChanging(string? value);
partial void OnNameChanged(string? value);
```

Fody PropertyChanged:

``` cs
public string GivenNames
    {
        get => givenNames;
        set
        {
            if (value != givenNames)
            {
                givenNames = value;
                OnPropertyChanged(InternalEventArgsCache.GivenNames);
                OnPropertyChanged(InternalEventArgsCache.FullName);
            }
        }
    }

```

**Comment by Malstraem** [comment]
@kmgallahan,
> By default x:Bind is updated on every observed PropertyChanged notification and **doesn't check for value equality**.
Why?

I know about CommunityToolkit and activily use it, its great to reduce boilerprate by using attributes. But such behavior of x:Bind is a violation of the INPC contract, which does not imply that the user should check for equality. 

And `Binding` considers that. Why x:Bind shoudn't?

**Comment by kmgallahan** [comment]
> a violation of the INPC contract

Per the [`INotifyPropertyChanged` Interface API documentation](https://learn.microsoft.com/dotnet/api/System.ComponentModel.INotifyPropertyChanged):

> Notifies clients that a property value has changed.

> The [INotifyPropertyChanged](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged?view=net-7.0) interface is used to notify clients, typically binding clients, that a property value has changed.

> Occurs when a property value changes.

>  `if (value != this.phoneNumberValue)...`

The INPC documentation does not state that it notifies when a setter has been called. 

The example code there shows that you should perform equality checks to prevent erroneous notifications.

x:Bind has been in use for 8 years now. Every consumer of it already does equality checking in the INPC code, and all the libraries that generate INPC boilerplate do the checking.

To suggest x:Bind be changed to check for equality means that all existing code would now be double-checking for equality.

It might be frustrating to find that x:Bind doesn't work exactly like Binding, but it wasn't created to be a drop-in replacement. 

I'd also argue that it is the INPC code that produces notifications, so equality checks are its responsibility, not consumers (which can be more than Binding and x:Bind).

**Comment by Malstraem** [comment]
@kmgallahan, thanks for the clarification, issue can be closed i think.

**Comment by isubad** [comment]
@kmgallahan @malstraem 
Could you please clarify in which Windows App SDK version this issue was fully fixed?
I'm currently using Windows App SDK 1.7.x, but I am still encountering the same behavior."

![Image](https://github.com/user-attachments/assets/d145b542-f871-451e-8270-0404b7fcca86)
