### ISSUE TITLE
[Redacted] A team member edited the title to remove content that violated this project's code of conduct

### ISSUE THREAD

**Issue by shithappens2016** [microsoft/microsoft-ui-xaml#8448]
[Redacted]

#8444

**Comment by roxk** [comment]
You are the one that didn't answer/explain any technical details, though. Heck, your issue doesn't even fit any issue template. And you insulted kenny.

I don't want to bring troubles to the WinUI/WASDK mod teams so it's fine if they think blocking/deleting this comment is more appropriate, thanks!

**Comment by shithappens2016** [comment]
@roxk 
Yes, I spoken the word blind once.
![5](https://user-images.githubusercontent.com/13523412/235569372-1d9ab1a2-deea-464c-9f5b-1ee28cf4aae3.png)

You call that an insult? I say it was just a metaphor to describe his indiscretion.


Speaking of insults. I really want to say some insulting words to you when I see you trying so hard to defend your boss. I think you deserve which insulting words that I have not said.

**Comment by shithappens2016** [comment]
>  if they think blocking/deleting this comment is more appropriate, thanks!

People, look at what he said. pure bureaucracy. As my friend once said, they don't have time to deal with bugs. Because they spend all their time dealing with people who report bugs.  Remove the comments or don't let people talk and problem issolved.

**Comment by hktiy** [comment]
大哥，有病就去治，在这里发什么神经？

**Comment by hktiy** [comment]
自己先嘴臭，还要怪别人？你三岁呢？

**Comment by YexuanXiao** [comment]
I think Kenny has made it very clear that C++/WinRT is just a forwarding layer that interacts with Windows objects (COM), so if you operate on objects that are essentially COM (which means dynamic linking), it will be less efficient than operating on pure C++ objects.

**Comment by shithappens2016** [comment]
@YexuanXiao 
You probably didn't read my original post carefully. My point is that the performance of Windows objects (COM) becomes very bad in C++. It doesn't even compare to the performance of Windows objects (COM) in C#. And look what this Kenny guy said at the end.

![1](https://github.com/microsoft/microsoft-ui-xaml/assets/13523412/9b803d7f-6b45-4f71-9db1-94a0a386e342)

**Comment by hktiy** [comment]
我还以为他骂你妈死了呢...
