### ISSUE TITLE
[Win10] Unpackaged WinUI 3 project failed with Error MSB3774: Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.19041.0

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8458]
### Describe the bug

Unpackaged WinUI 3 project failed with Error MSB3774: "Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.19041.0".

### Steps to reproduce the bug

**Environment:**
OS Version: Windows 10(19045.2846)
Windows App SDK: 1.2 & 1.3

**More info:** 
1. This issue only reproduces on Win10, does not reproduce on Win11.
2. This issue does not reproduce on VS 17.6 Preview 6 and 17.7.0 Preview 2.0 [33705.509.main].

**Repro Steps:**
1. Install VS 17.6.0 Preview 7.0 [33705.201.d17.6] from [Pipelines - Run rel.d17.6-33705.201 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D7732671%26view%3Dresults&data=05%7C01%7Cv-dollywang%40microsoft.com%7C0a77b04946774c6aadda08db4db0aebf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638189193656689966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Cjr4FajaYwPmZ2X%2Bkrk%2FzBF6mDOazfhDlZ4%2FgZkOsUQ%3D&reserved=0)
2. Make sure "Windows App SDK C# Templates" is installed.
3. Create C# Blank App, Packaged with Windows Application Packaging(WinUI 3 in Desktop)
4. Press F5

**Actual Result:**
Run failed with an Error MSB3774: "Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.19041.0". 

**Expected Result:**
Run successfully without errors.

### Screenshots

![image](https://user-images.githubusercontent.com/97647558/236615462-1386e326-c384-46c4-ad8e-4c2189ca2779.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.0: 1.3.230331000

**Comment by veton** [comment]
Installing **Windows 11 SDK** through Visual Studio Installer solved the issue.

**Comment by Scottj1s** [comment]
For backward compat, SDK references such as UCRT are still included by default, but can be opted out via <WinUISDKReferences>false</WinUISDKReferences>
