### ISSUE TITLE
[.NET 8.0] Unpackaged WinUI 3 desktop app failed with Not compatible errors

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8463]
### Describe the bug

Unpackaged C# WinUI 3 desktop app deploy successfully when using .NET 8.0 Preview 4, but there are 8 errors in Error List.
![image](https://user-images.githubusercontent.com/97647558/236745033-c41c8e4d-2d6f-4b77-914f-d2da9114aec4.png)

The same issue https://github.com/microsoft/microsoft-ui-xaml/issues/8251 is closed, so we create a new one to track.

### Steps to reproduce the bug

**VS Build:** 17.7.0 Preview 1.0 [33704.131.d17.7]
**Repro Steps:**

1. Install .NET 8 Preview 4 SDK from [dotnet/installer: .NET SDK Installer (github.com)](https://github.com/dotnet/installer)

2. Add feed for .NET 8.0

3. Create C# Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop)

4. Update the TargetFramework from "net6.0-windows10.0.19041.0" to "net8.0-windows10.0.19041.0"

5. Update the Microsoft.WindowsAppSDK to 1.3.230331000

6. Run the project.

**Actual Result:**
App run successfully, but there are 8 errors in Error List.

### Expected behavior

Project run successfully without errors.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.0: 1.3.230331000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

We tried with below scenarios:
1. Create a C# Blank App, Packaged (WinUI3 in Desktop project with .NET 8.0, application run successfully without any error.
2. Create C# Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop) project with .NET 6.0, application run successfully without any error.
3. Create C# Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop) project with .NET 8.0, application run successfully, but there are 8 errors in Error List.
4. Create C# Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop) project with .NET 8.0, and include `<WindowsPackageType>None</WindowsPackageType>` into my .csproj file, application cannot show up and Error List have 8 errors.

**Comment by ghost1372** [comment]
.Net 8 is not supported by WASDK, so please reopen issue in WASDK repo

**Comment by Scottj1s** [comment]
The issue here is that the WAP project is targeting 17763, which is lower than the head App2 project, which is targeting 19041.  The solution is to adjust one or the other version.
