### ISSUE TITLE
UWP ListView Touch Unhandled Win32 Exception

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#8466]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/UWP-ListView-Touch-Unhandled-Win32-Excep/10349750)._

---
[severity:I'm unable to use this version]
I have a ListView in my UWP app.  When I touch the ListView I sometimes get an Unhandled Exception as shown below:

>Unhandled exception at 0x00007FFB1D7BCFC4 (Windows.UI.Xaml.dll) in KOTHMain.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001FF7AA6BD00, 0x0000000000000005).`

This is not caught by my App_UnhandledExcpetion handler, it just crashes the app.

From the Call Stack (attached) you can see this is some type of Touch HitTest exception.  I have checked several other ListViews in my app, as well as GridViews, and they do not exhibit this behavior.  Just one, on one page.  Also, the ListView works fine with the mouse.

I have no idea what is causing this exception, nor how to handle it in any way.  

Any help would be appreciated.

---
#### Feedback Bot on 4/26/2023, 11:43 PM: 

(private comment, text removed)
#### Liliya Tang [MSFT] on 4/27/2023, 00:04 AM: 

(private comment, text removed)
#### Ron on 4/27/2023, 08:54 PM: 

(private comment, text removed)
#### Ron on 4/27/2023, 04:30 PM: 

(private comment, text removed)
#### Liliya Tang [MSFT] on 5/3/2023, 11:29 PM: 

(private comment, text removed)
#### Ron on 5/4/2023, 07:44 AM: 

(private comment, text removed)
#### Feedback Bot on 5/4/2023, 11:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by codendone** [comment]
Closing as dup of #8145.
