### ISSUE TITLE
Failed to add InlineUIContainer to InlineCollection.

### ISSUE THREAD

**Issue by YexuanXiao** [microsoft/microsoft-ui-xaml#8479]
### Describe the bug

Error XHR0015 Failed to add InlineUIContainer to InlineCollection. Unspecified error.
Error XHR0010 Failed to find the property "Microsoft.UI.Xaml.Documents.InlineUIContainer.Child"

### Steps to reproduce the bug

```xaml

<TextBlock>
<TextBlock.Inlines>
<InlineUIContainer>
<Button />
</InlineUIContainer>
</TextBlock.Inlines>
</TextBlock>

```

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows Insider Build (xxxxx)

**Comment by codendone** [comment]
The [documentation](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.documents.inlineuicontainer?view=windows-app-sdk-1.4) and error message could certainly be clearer, but `InlineUIContainer` is only supported inside of a `RichTextBlock`. Trying to use InlineUIContainer inside of a TextBlock fails, which then leads to confusing the downstream message you saw of not finding the Child property.
