### ISSUE TITLE
Proposal: Pivot underline/highlight should follow finger

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#848]
# Proposal: Pivot underline/highlight should follow finger 

## Summary

Pivot underline/highlight should follow finger

## Rationale

* Because it gives visual feedback

**Comment by jevansaks** [comment]
@poopooracoocoo can you elaborate on the scenario? When touching the header and dragging to change the pivot, or something else?

**Comment by mdtauk** [comment]
I think the proposal is as you are dragging between Pivot items, the Pivot Selection Indicator should stretch along with the direction you are dragging your finger - before it springs to its normal size underneath the Pivot Item Header.

**Comment by YuliKl** [comment]
@Poopooracoocoo, thank you for the suggestion. Given WinUI's ambitious [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md), and controls like NavigationView in Top mode and TabControl (#304), we're not able to make active investments in Pivot. While this feels like a nice fit-and-finish proposal, I don't believe that we can justify this investment given everything else the team is hoping to accomplish.

**Comment by shaheedmalik** [comment]
I understand how you guys feel, but tablet features are severely lacking in polish. Elements such as this would help improve the interface for tablet users. Put in In WinUI 3, if need be.

**Comment by YuliKl** [comment]
We certainly want to support touch/tablet features, but not necessarily on the Pivot control. While Pivot is definitely not deprecated, we're not adding new features to this control. We think that scenarios that used to be achieved with Pivot are now better served using NavigationView or (upcoming) TabControl.

**Comment by shaheedmalik** [comment]
If the upcoming TabControl is to replace Pivots, then it needs the ability to swipe between tabs. Windows 10 is surely lacking in the usability of gestures within apps. Windows 8.1 was better in that regard. 

My 4 year old niece is able to play with an Android tablet just by swiping gestures. Many of these gestures came from Windows 8.1. There are videos of monkeys using swiping gestures to browse apps.
https://www.youtube.com/watch?v=vjNZzPZmYTY
I don't want to tap on everything, I want to swipe.
When it comes to Windows 10 tablet usability, it has regressed. Let's fix that.

**Comment by Poopooracoocoo** [comment]
I thought tabs were going to co-exist with pivots. I'm really confused. What about (for example) the Feedback Hub's "All feedback" and "My feedback" pivots? What about a future file explorer with a properties window? 
#304 says this: 
> Note that "static-style" tabs also exist as a paradigm. "Static-style" tabs are tabs that do not support user interaction beyond switching tabs. UWP already has a solution for static-style tabs in the form of Pivot and NavigationView.

~

> While this feels like a nice fit-and-finish proposal, I don't believe that we can justify this investment given everything else the team is hoping to accomplish.

Why close this though? Is it really hard to implement this? It's genuine question as I don't know about how WinUI works behind the scenes. It doesn't have to be closed and forgotten forever. It could just be something to work on in a couple of months or _later_

This doesn't seem like a big feature request and yet can make a big difference to how pivots feel (slow and unresponsive).

**Comment by mdtauk** [comment]
Maybe @JustinXinLiu could take a look - I believe he was one of those responsible for the stretchy indicator animation in ll the other controls.

**Comment by JustinXinLiu** [comment]
Well as much as I like the this stick-to-ginger interaction (in fact, I even implemented [one](https://twitter.com/justinxinliu/status/698641062479290369?s=21) a few years ago and you are free to use it), this currently doesn’t fit in our overall Fluent Design System. Just compare this with the indicator stretching animation from NavigationView, we shouldn’t have two similar visuals that act differently. So to me this will require some design thinking first. Good question though.

**Comment by YuliKl** [comment]
> I thought tabs were going to co-exist with pivots. 

Yes, absolutely. We're not disabling any existing functionality in the Pivot control. What's already implemented will continue to work. However, using dev time to make improvements to Pivot doesn't align with our other priorities.

> Is it really hard to implement this?

Animation changes, especially animations tied directly to touch input are not trivial. In Pivot's case, this change would likely require removing Pivot's current underline and starting that part from scratch. Maybe not "really hard" but a substantial amount of work. Which doesn't fit with the WinUI roadmap or the Fluent Design System direction.

**Comment by Poopooracoocoo** [comment]
What *is* the Fluent Design System direction? Why isn't this a part of it? (in response to Yulia)

Justin brought up a really good point. They don't fit in the Fluent Design System. Top NavigationViews and Pivots don't look different and it doesn't show that you can swipe between Pivots. When you aren't using touch or touchpad gestures, there's no difference between them apart from the animation.

**Comment by YuliKl** [comment]
@Poopooracoocoo, I've given this proposal some more thought and don't think this is a good idea. As you know, Pivot allows swiping anywhere, on its headers area and its items’ content area, to change the selected pivot item. The underline used to indicate the selected item is drawn immediately bellow the item header text. So when I swipe on the content, the underline can't follow my finger because my finger is nowhere near the current position of the underline.

**Comment by mdtauk** [comment]
@YuliKl  I think it is less about matching the position of the finger, but to start a translation/translation with elastic transform - either left or right, which moves at the same speed and rate as the finger swipe gesture.

**Comment by Poopooracoocoo** [comment]
@YuliKl What @mdtauk said is what I was suggesting. Check this out: https://material.io/design/components/tabs.html#behavior

**Comment by Poopooracoocoo** [comment]
@YuliKl Any hopes of reopening this proposal? 

It would add some polish and it doesn't have to be done right now. I understand that you guys are busy with WinUI 3 but this could be done after and as I said before, tabs don't replace pivots in a file explorer properties window for example or even just for the feedback hub.

**Comment by YuliKl** [comment]
@Poopooracoocoo, is this proposal (specifically the https://material.io/design/components/tabs.html#behavior part) different from #940 that you opened more recently?

**Comment by Poopooracoocoo** [comment]
@YuliKl this one is for swiping the other is for tapping. When it's tapped it can have a fancy animation. That link has two videos. One for each issue.

**Comment by YuliKl** [comment]
@Poopooracoocoo, I see. Unfortunately I continue to believe that a swipe animation is impractical for a UWP app. Material design is targeting phone, so physically small, screens. Their swipe example would not scale well if the Pivot (or Material Tabs) control was the width of a maximized window on a 24-inch monitor.

**Comment by shaheedmalik** [comment]
But it would scale on a 10 in tablet. Nobody is going to use a minimized app design on a full sized maximized app. Those particular designs would be used in a snapped view app.

**Comment by Poopooracoocoo** [comment]
@YuliaKl How does this not scale? As @mdtauk said, this is not about matching the position of the finger. This is more of a touch thing. 24 inch monitors are usually not touchscreens. This is more for laptops and tablets but really any touch device. Every Surface device has a touchscreen

**Comment by Poopooracoocoo** [comment]
so the winui 3.0 alpha has been released and i'd really like to hear further explanation. sorry for the trouble @YuliKl @jevansaks

**Comment by YuliKl** [comment]
@Poopooracoocoo I'm not sure I understand what explanation you're looking for in relation to the WinUI 3.0 alpha. If anything, I expect that having tried the alpha you might get a sense for the more fundamental work still left for us, which I believe takes precedence over new features for Pivot.

**Comment by mdtauk** [comment]
@Poopooracoocoo  WinUI 3.0 is not finished yet, and so at the earliest, it will be next year once it is released, that they will consider taking a new look at Pivot, and deciding if and what changes should be made.

**Comment by Poopooracoocoo** [comment]
@mdtauk I understand that WinUI 3.0 isn't finished yet. I was a bit worried about this issue as it was closed and probably won't be looked at again because it's closed.
