### ISSUE TITLE
Windows Enterprise Edition seems to be unable to drag and drop?

### ISSUE THREAD

**Issue by HHHHHHHHHHHHHHHHHHHHHCS** [microsoft/microsoft-ui-xaml#8489]
### Describe the bug

I want to drag text from another application to enter textbox. 
The professional version runs well.
But the enterprise version cannot drag and drop.
I don't why...

### Steps to reproduce the bug

1. selecte text 
2. drag into textbox

### Expected behavior

textbox show drag text

### Screenshots

The professional version

WIN10 21H2 19044.1766

![Yes](https://github.com/microsoft/microsoft-ui-xaml/assets/14230366/ac067ae7-24ff-448f-b0a4-0d51504955a8)

![0](https://github.com/microsoft/microsoft-ui-xaml/assets/14230366/b5ca91a3-e58f-42c3-8a67-d1b1b606fcfd)

=========================================================

The enterprise version

WIN10 22H2 19045.2965

I tried Enterprise Edition 2021H2, but I couldn't drag and drop.

![No](https://github.com/microsoft/microsoft-ui-xaml/assets/14230366/62c851dd-1bd1-480c-a9a2-68e7e12b5892)

![1](https://github.com/microsoft/microsoft-ui-xaml/assets/14230366/7d83265f-91a8-4aa9-923e-e3c0579869df)

=========================================================

SDK and OS.

![SDK](https://github.com/microsoft/microsoft-ui-xaml/assets/14230366/9fb3eee5-97ff-4e76-83dc-14948556c9e9)

![OS](https://github.com/microsoft/microsoft-ui-xaml/assets/14230366/55b41fd6-c31b-4233-bc94-0a4ead7da1e5)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
> Huh, I always thought this was a Windows Sandbox issue. Windows Sandbox runs Windows 10 Enterprise....
> 
> I can confirm this bug exists at the very least within Windows Sandbox (in my case, dragging an item (music file) from the WinUI App to the desktop).

Do you have some solution? thx

**Comment by DominicMaas** [comment]
> Do you have some solution? thx

Nope, sorry!

**Comment by rocksdanister** [comment]
I think the issue is because the application is run as administrator (drag'n'drop is not supported.)

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
> I think the issue is because the application is run as administrator (drag'n'drop is not supported.)

Thank you very much.  I'm trying to open UAC,  and run without admin. It's can drag & drop!!!

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
> > Do you have some solution? thx
> 
> Nope, sorry!

I solved him through rocksdanister.   
Open UAC  and  run without admin.
