### ISSUE TITLE
Incorrect Target framework in .csproj file after changing Target framework from .NET 6.0 to.NET 7.0 in Properties.

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8494]
### Describe the bug

1. With .NET 7/.NET 8 SDK installed, the default target framework is .NET 6 instead the higher .NET 7/.NET 8 for WinUI project.
2. Incorrect Target framework in .csproj file after changing Target framework from .NET 6.0 to.NET 7.0 in Properties.

There is a similar [issue](https://developercommunity.visualstudio.com/t/Using-C-project-properties-to-change-Ta/10220321?ref=native&refTime=1670006497287&refUserId=3ecae279-b085-41e5-8176-afdfb2972795).

### Steps to reproduce the bug

**Environment:**
VS build: 17.7.0 Preview 2.0 [33715.387.main]
OS: Win10&Win11

**Preinstall:** 
Install .NET 7/.NET 8 from https://github.com/dotnet/installer in machine.

**Repro Steps:**
1. Create Blank App, Packaged (WinUI 3 in Desktop)
2. Right click the project node to open Properties.
3. Check the default Target framework is .NET 6.0 instead of .NET 7.0
4. Change the Target framework from .NET 6.0 to.NET 7.0 in the Target Framework list.
5. Open the project file .csproj to check the <TargetFramework>.

**Expected Result:**
Target Framework should be `<TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>`.

**Actual result:**
Target Framework is `<TargetFramework>net7.0</TargetFramework>`, it will build failed.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/2169ff6d-cee0-4cfc-9d69-3a4f6795d186)

### NuGet package version

None

**Comment by Scottj1s** [comment]
Fixed In: Visual Studio 2022 version 17.8 Preview 1
