### ISSUE TITLE
Mica backdrop crashes WinUI 3 application

### ISSUE THREAD

**Issue by dgellow** [microsoft/microsoft-ui-xaml#8495]
## Package versions
Microsoft.WindowsAppSDK: 1.3.230502000
Microsoft.Windows.SDK.BuildTools: 10.0.22621.756
CommunityToolkit.WinUI: 7.1.2
Microsoft.Extensions.DependencyInjection: 7.0.0

## Crash details

Given this `App.xaml.cs`:

```csharp
namespace Demo.WinUI;

public partial class App : Application
{
    private Window mainWindow;

    public App()
    {
        InitializeComponent();
    }

    protected override void OnLaunched(LaunchActivatedEventArgs args)
    {
        mainWindow = new MainWindow();
        mainWindow.SystemBackdrop = new MicaBackdrop() { Kind = MicaKind.Base };
        mainWindow.Activate();
    }
}
```

And this `MainWindow.xaml`:
```xaml
<Window
    x:Class="Demo.WinUI.Views.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
</Window>
```

My WinUI 3 application crashes with:

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.WinUI.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.WinUI.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.WinUI.dll
Exception thrown at 0x00007FF9AD5D536C (KernelBase.dll) in Demo.WinUI.exe: WinRT originate error - 0x80131534 : 'The type initializer for '_IMicaBackdropFactory' threw an exception.'.
onecore\com\combase\winrt\error\restrictederror.cpp(1017)\combase.dll!00007FF9AFDCC07A: (caller: 00007FF9AFDD15EF) ReturnHr(83) tid(cc5c) 8007007E The specified module could not be found.
```

--- 

When trying to use the XAML setter:
```xaml
    <Window.SystemBackdrop>
        <MicaBackdrop Kind="Base" />
    </Window.SystemBackdrop>
```

The application crashes with a XAML parsing error:

```
Microsoft.UI.Xaml.Markup.XamlParseException
  HResult=0x802B000A
  Message=XAML parsing failed.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
```

Without the MicaBackdrop the application works as expected.

### Steps to reproduce the bug

1. Create a new project
2. Install Microsoft.WindowsAppSDK v1.3.230502000
3. Set MicaBackdrop to the Window
4. 💥

### Expected behavior

No crash, and a Mica backdrop.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by christineyan4** [comment]
Hi, after following the repro steps above with a packaged WinUI3 app, I'm seeing the app build and run on 1.3.230502000, and it renders MicaBackdrop without crashing. Could you share a repro project or a crash dump? Also, was this a packaged or unpackaged app? Thanks!

**Comment by dgellow** [comment]
Hi @christineyan4, thanks for the answer. I think I found the problem. It is a project with a WinUI project and an MSIX packaging project, I updated WindowsAppSDK in the WinUI dependency but did not notice the Packaging project still had a reference to an older WindowsAppSDK version. Once consolidated the project seems to build and run correctly, with a Mica backdrop.

I'm closing this issue.

**Comment by Slion** [comment]
Had the same issue with the same root cause. Thanks for posting this.
