### ISSUE TITLE
[WinUI] C# Project Referencing a C# Library User Control failed with CS1061 and NETSDK1 errors

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8499]
### Describe the bug

On Visual Studio 16.11.26, add a WinUI class library to WinUI desktop project, build failed with CS1061 and NETSDK1 errors.
The [test case](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1366329) failed on 16.11, work as expected on Visual Studio 17.7 Preview 2.
Copy the bug from [[16.11] [WinUI]C# Project Referencing a C# Library User Control failed with CS1061 and CS0103 errors](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1581852)

### Steps to reproduce the bug

**Environment:**
VS Build: 16.11.26
OS: Windows 10

**Repo:** [WinUIIssues.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11539313/WinUIIssues.zip)

**Repro Steps:**
1. Create C# Blank App, Packaged (WinUI 3 in Desktop) project and rename to MyCSDesktopProject.
2. Create C# Class Library(WinUI 3 in Desktop) project and rename to MyCsClassLibrary -> Add User Control -> Add some code.
3. Focus on MyCSDesktopProject -> add existing project MyCsClassLibrary
4. Click on MyCSDesktopProject, add reference MyCsClassLibrary.
5. Build the solution.

**Expected Result:**
Build successfully without errors.

**Actual Result:**
Build failed with CS1061 and NETSDK1 errors.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/093af543-c6fc-4040-9855-c41c8012b5fd)

### NuGet package version

None

**Comment by Scottj1s** [comment]
The InitializeComponent error is a known spurious issue that can be remedied with a clean rebuild. Does that unblock your scenario?
