### ISSUE TITLE
Against the Backdrop that is configured, strange exceptions occur in the debugging application mode

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#8507]
### Describe the bug

Against the Backdrop that is configured, strange exceptions occur in the debugging application mode.

![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/8aadce73-9fef-4300-8e4b-b8b00c3ff729)

The following exception is displayed.

0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\UIAnimation.dll”。已加载符号。
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG

If you modify the application theme (when setting (Window.Content as FrameWorkElement).RequestedTheme) against the customized SystemBackdrop, App.UnhandledException will be triggered

User-defined MicaSystemBackdrop

    public class MicaSystemBackdrop : SystemBackdrop
    {
        private MicaController _micaController;

        public SystemBackdropConfiguration BackdropConfiguration { get; private set; }

        public MicaKind Kind { get; set; } = MicaKind.Base;

        /// <summary>
        /// 在 Window.SystemBackdrop 上设置时触发该方法
        /// </summary>
        protected override void OnTargetConnected(ICompositionSupportsSystemBackdrop connectedTarget, XamlRoot xamlRoot)
        {
            base.OnTargetConnected(connectedTarget, xamlRoot);

            if (_micaController != null)
            {
                throw new ApplicationException(ResourceService.GetLocalized("Resources/SystemBackdropControllerInitializeFailed"));
            }

            _micaController = new MicaController() { Kind = Kind };
            _micaController.AddSystemBackdropTarget(connectedTarget);

            SetControllerConfiguration(connectedTarget, xamlRoot);
        }

        /// <summary>
        /// 从 Window.SystemBackdrop 对象中清除此对象时调用。
        /// </summary>
        protected override void OnTargetDisconnected(ICompositionSupportsSystemBackdrop disconnectedTarget)
        {
            base.OnTargetDisconnected(disconnectedTarget);

            _micaController.RemoveSystemBackdropTarget(disconnectedTarget);
            _micaController = null;
        }

        /// <summary>
        /// 设置应用于系统背景目标的系统策略
        /// </summary>
        private void SetControllerConfiguration(ICompositionSupportsSystemBackdrop connectedTarget, XamlRoot xamlRoot)
        {
            BackdropConfiguration = GetDefaultSystemBackdropConfiguration(connectedTarget, xamlRoot);
            BackdropConfiguration.IsInputActive = true;
            _micaController.SetSystemBackdropConfiguration(BackdropConfiguration);
        }
    }

### Steps to reproduce the bug

1.User-defined MicaSystemBackdrop

    public class MicaSystemBackdrop : SystemBackdrop
    {
        private MicaController _micaController;

        public SystemBackdropConfiguration BackdropConfiguration { get; private set; }

        public MicaKind Kind { get; set; } = MicaKind.Base;

        /// <summary>
        /// 在 Window.SystemBackdrop 上设置时触发该方法
        /// </summary>
        protected override void OnTargetConnected(ICompositionSupportsSystemBackdrop connectedTarget, XamlRoot xamlRoot)
        {
            base.OnTargetConnected(connectedTarget, xamlRoot);

            if (_micaController != null)
            {
                throw new ApplicationException(ResourceService.GetLocalized("Resources/SystemBackdropControllerInitializeFailed"));
            }

            _micaController = new MicaController() { Kind = Kind };
            _micaController.AddSystemBackdropTarget(connectedTarget);

            SetControllerConfiguration(connectedTarget, xamlRoot);
        }

        /// <summary>
        /// 从 Window.SystemBackdrop 对象中清除此对象时调用。
        /// </summary>
        protected override void OnTargetDisconnected(ICompositionSupportsSystemBackdrop disconnectedTarget)
        {
            base.OnTargetDisconnected(disconnectedTarget);

            _micaController.RemoveSystemBackdropTarget(disconnectedTarget);
            _micaController = null;
        }

        /// <summary>
        /// 设置应用于系统背景目标的系统策略
        /// </summary>
        private void SetControllerConfiguration(ICompositionSupportsSystemBackdrop connectedTarget, XamlRoot xamlRoot)
        {
            BackdropConfiguration = GetDefaultSystemBackdropConfiguration(connectedTarget, xamlRoot);
            BackdropConfiguration.IsInputActive = true;
            _micaController.SetSystemBackdropConfiguration(BackdropConfiguration);
        }
    }

2.Set the SystemBackdrop on an instance of the Window class
3.Actively modify the application theme color (Window.Content as FrameWorkElement).RequestedTheme) 
4.The App.UnhandledException event is triggered, and something strange is printed on the console.
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\UIAnimation.dll”。已加载符号。
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'target'。
Microsoft.ui.xaml.dll!00007FFB181448B4: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG
0x00007FFBE097536C (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80070057 : 'Value does not fall within the expected range.'。
Microsoft.ui.xaml.dll!00007FFB749C74C3: CallContext:[\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity\ImageDecodeActivity] 80070057 - E_INVALIDARG

### Expected behavior

The debug console doesn't output so much weird stuff, and it doesn't throw an App.UnhandledException when the theme color changes are applied

### NuGet package version

Windows App SDK 1.3.1: 1.3.230502000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by christineyan4** [comment]
Hi, I've followed the repro steps above to set the user-defined MicaSystemBackdrop on the Window. I then modified the application theme color from MainWindow.xaml.cs, which runs and display the requested theme. I've also tried just manually changing the theme from Windows settings, and that works as expected as well. In both cases, I'm not repro-ing either the crash or the strange exceptions listed above! 

Could you share a sample repro project? I'm wondering if there are any repro steps I'm missing. Thanks!

**Comment by ranjeshj** [comment]
Please re-activate once there is a sample. Thanks!
