### ISSUE TITLE
{x:Bind}: Changes made to the cloned instance are reflected

### ISSUE THREAD

**Issue by shinta0806** [microsoft/microsoft-ui-xaml#8513]
### Describe the bug

Changes made to the cloned instance, not the bound instance, will be reflected.

### Steps to reproduce the bug

1. Bind some value in XAML.
2. Clone the value.
3. Changes the cloned value.
4. Reflected in XAML.

Sample program in GitHub:
https://github.com/shinta0806/TestCloneBind

### Expected behavior

Changes made to the only original instance will be reflected.

### Screenshots

![ss](https://github.com/microsoft/microsoft-ui-xaml/assets/7196473/676b0191-7f1b-4dfc-895c-0ab9e13e01c0)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmgallahan** [comment]
https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone

> The [MemberwiseClone](https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone) method creates a shallow copy by creating a new object, and then copying the nonstatic fields of the current object to the new object. If a field is a value type, a bit-by-bit copy of the field is performed. If a field is a reference type, the reference is copied but the referred object is not; therefore, the original object and its clone refer to the same object.

**Comment by kmgallahan** [comment]
You are using [`MemberwiseClone`](https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone) on an object that inherits from [`ObservableObject`](https://learn.microsoft.com/dotnet/api/communitytoolkit.mvvm.componentmodel.observableobject) which declares the `PropertyChanged` event, and this results in undesirable behavior:

> The Problem with Events and MemberwiseClone
> 
> If you use MemberwiseClone, it will clone any event the object has. This means the newly cloned object will fire off events to whatever objects were registered with the object you cloned from. This tends to be undesirable for a number of reasons:
> 
> * The object that registered an interest in receiving events from the original object is now getting events from the newly cloned object also.
> * Because the object that registered for an event doesn't know about the newly cloned object, it doesn't know to deregister its interest from the cloned object.
> * Because events hold references to objects, it can cause objects to hang around in memory after you think you have killed all references to that object

https://www.codeproject.com/Articles/6753/Events-and-Clones

**Comment by shinta0806** [comment]
Thank you very much!
