### ISSUE TITLE
FolderPicker Won't Initially Allow Selection of Starting Folder

### ISSUE THREAD

**Issue by markolbert** [microsoft/microsoft-ui-xaml#8514]
### Describe the bug

When calling `PickSingleFolderAsync()`, the initial folder (whatever that's set to or remembered) cannot be selected (i.e., the Select button is grayed out).

Drilling down and then up, or up and then down, through the folder tree then allows you to select that same initial folder that you couldn't initially select.

### Steps to reproduce the bug

Here's the code that sets up the FolderPicker to illustrate the behavior:

```
var picker = new FolderPicker { SuggestedStartLocation = PickerLocationId.Desktop };

var hWnd = WinRT.Interop.WindowNative.GetWindowHandle( App.Current.MainWindow );
WinRT.Interop.InitializeWithWindow.Initialize( picker, hWnd );

picker.SuggestedStartLocation = PickerLocationId.Desktop;

_storageFolder = await picker.PickSingleFolderAsync();
ExportFolder = _storageFolder == null ? null : _storageFolder.Path;
```

### Expected behavior

You shouldn't have to drill down/up (or up/down) to be able to select the initial starting folder.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DarranRowe** [comment]
Just to add a little information.
This is fully reproducible in a Windows API application without the Windows App SDK loaded. This would mean that this is an Windows issue and not a WinUI issue.

**Comment by hgy59** [comment]
This seems to be a bug in PickerHost.exe of Windows.
(related SO issue https://stackoverflow.com/questions/50657601/uwp-folderpicker-select-folder-button-disabled-by-default)

But how can we tell Microsoft that this is a bug in Windows?
