### ISSUE TITLE
[TabView] Sluggish transitioning animation of the Tabview item header

### ISSUE THREAD

**Issue by Jimex** [microsoft/microsoft-ui-xaml#8517]
### Describe the bug

The animation seems sluggish when transitioning the tab item header from a long title to a shorter one

### Steps to reproduce the bug

1. Create a WinUI3 project
2. Add a Tabview to the window and set the size TabWidthMode to "SizeToContent"
3. Add a tab item from code behind with a long title
4. Chang the title of the existing tab item to a short one

### Expected behavior

The duration of  the transition animation should be very short

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/3145858/804f45b0-9e72-44b5-a696-9d1b7fc7c978

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by zadjii-msft** [comment]
Pretty sure this was fixed in 2.8.4, in #8430, which was originally tracked at #8384

**Comment by DmitriyKomin** [comment]
@Jimex, thank you for reporting this. As @zadjii-msft commented, this appears to be the same issue as #8384 , which has now been fixed. Please let us know if you still repro the issue with latest WinAppSDK.
