### ISSUE TITLE
WinUIEdit.dll version number *lowered* between windows app SDK version 1.2 and 1.3

### ISSUE THREAD

**Issue by fredemmott** [microsoft/microsoft-ui-xaml#8518]
### Describe the bug

Windows App SDK v1.2.230118.102:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/360927/9f05c1be-fd2c-423d-9c16-5c930e9cd7ca)

Windows App SDK v1.3.230320000:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/360927/18388a0f-4e27-4e79-9dee-1a389dc30785)

This is a practical problem because, by default, when **upgrading** a self-contained app that uses Windows App SDK v1.2 to a new version that uses v1.3, MSI-based installers will remove WinUIEdit.dll because of this version degrade. ~~As a workaround, [REINSTALLMODE](https://learn.microsoft.com/en-us/windows/win32/msi/reinstallmode) can be set to ignore version metadata.~~

This causes the crash at https://github.com/OpenKneeboard/OpenKneeboard/issues/359#issuecomment-1569069587

### Steps to reproduce the bug

1. Install Windows App SDK v1.2, inspect WinUIEdit.dll metadata
2. Install Windows App SDK v1.3, inspect WinUIEdit.dll metadata
3. See downgrade

Real-world:
1. install https://github.com/OpenKneeboard/OpenKneeboard/releases/tag/v1.4.3
2. upgrade to MSI from https://github.com/OpenKneeboard/OpenKneeboard/actions/runs/5128711389
3. run it
4. settings -> advanced
5. crash
6. repair or uninstall + reinstall
7. run it
8. settings -> advanced
9. works fine

### Expected behavior

DLL version numbers should only increase in newer versions of the SDK.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by bpulliam** [comment]
This was a one-time change to move to standard version numbers.  Sorry for the inconvenience.

**Comment by fredemmott** [comment]
@bpulliam fwiw, this means that some MSI tools can not author installers for apps that upgrade the windows app SDK, because Microsoft are not following their own versioning standards.

This is not just a one-off cost; it means that some (including myself) will need to re-author our installers in new tools, and maintain a more complex setup with more technical debt forever. In my case, I need to move from CPack to raw WiX, then explicitly tie this DLL's version to another (perhaps the main windows app runtime dll). There are simpler, less time-consuming alternatives to raw WiX, but they seem to either require paid licenses (e.g. InstallShield) or move away from MSI (InnoSetup).

This could be avoided if the version number for this one DLL was re-incremented to a version greater than a past revision.

**Comment by fredemmott** [comment]
Yep, this is a re-occuring cost despite this change being made in 2023. To handle updates from old versions of my software, I still need to violate standard windows installer behavior and special-case this DLL when making changes to the installer for new versions of my software.
