### ISSUE TITLE
Accessibility: MAS2.5.3: Label in name: CommandBar.SecondaryCommands button label does not match name

### ISSUE THREAD

**Issue by evanve** [microsoft/microsoft-ui-xaml#852]
**Describe the bug**
In a recent round of accessibility testing, we had a bug assigned to us where the Name of the ellipsis button did not match up with the “Label” (in this case, the tool tip).  The Name property is simply “More” or “Less” depending on the state button.  The ellipsis button’s label is either “See more” or “See less”.

According to this new accessibility rule (MAS 2.5.3 Label in Name) that is a part of WCAG 2.1, the name of a control should start with the label that is displayed visually to the user.  From what I can gather, this rule is intended to help speech-input-only users who expect to be able to set focus to/invoke a control based on reading the label for that control.

**Steps to reproduce the bug**
Create a command bar with secondary commands.

**Expected behavior**
Proposed solution:

You can have as both label and name:
“more” “less”
Or
“see more” “see less”
Or
“show more” “show less”

**Screenshots**
![image](https://user-images.githubusercontent.com/51717649/59294544-b47e6c80-8c4f-11e9-8981-3c2a53d7f894.png)

**Comment by YuliKl** [comment]
CommandBar and CommandBarFlyout need to use the identical strings for the UIA name and tooltip text of their More buttons. I propose using the strings "**more**" and "**less**"
