### ISSUE TITLE
Crash while running on secondary monitor and locking the PC 

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#8528]
### Describe the bug

Running the Xelion app (WinUI) on a secondary monitor crashes the app when the PC is locked. 
The app crashes due to an OutOfMemory exception:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/4835617/c27aad3c-9d2d-4b38-a536-529bc12bc87e)

Attached you will find a complete trace from a dump. 
[Exception analysis (dump 10996).txt](https://github.com/microsoft/microsoft-ui-xaml/files/11663109/Exception.analysis.dump.10996.txt)

### Steps to reproduce the bug

1. Run the Xelion app on a multi-monitor setup  (laptop screen, main monitor, secondary monitor).
2. Drag Xelion to the secondary monitor
3. Lock the PC
4. Return back in about 12 minutes and unlock the PC
5. Xelion has been terminated due to a crash.

NOTE: When Xelion runs on the main monitor there is no crash.

### Expected behavior

No crashes

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by wbokkers** [comment]
Confirmed that this is fixed in a patched Windows App SDK with version of 1.3.230724001

**Comment by codendone** [comment]
I would expect that this still repros in 1.3.230724001, but there was a fix for exactly this scenario in 1.4 (http://task.ms/45487187). Closing as fixed.
