### ISSUE TITLE
Incremental build after changing property on command line produces non-runnable app

### ISSUE THREAD

**Issue by srdjanjovcic** [microsoft/microsoft-ui-xaml#8529]
### Describe the bug

While investigating incremental build issues with MAUI app's WinUI projection, I have discovered that switching from packaged to unpackaged mode when building produces broken app. I have discovered that culprit is that second build, with /p:WindowsPackageType=None retained same resources.pri as packaged build, which breaks the app.

Repro is with a MAUI app, but I didn't test with plain WinUI app, although I expect that it would hit the same issue.

### Steps to reproduce the bug

1. Create a MAUI app
2. Rebuild it once in packaged mode:
- msbuild /r /t:Rebuild MauiApp1.csproj
3. Observe size and content of resources.pri under bin\Debug\net7.0-windows10.0.19041.0\win10-x64\resources.pri. 
- It should be around 140Kb
4. Run incremental build, forcing unpackaged mode:
- msbuild /p:WindowsPackageType=None MauiApp1.csproj
5. Try launching bin\Debug\net7.0-windows10.0.19041.0\win10-x64\MauiApp1.exe
- App crashes.
7. Observe size and content of resources.pri under bin\Debug\net7.0-windows10.0.19041.0\win10-x64\resources.pri. 
- It is still 140Kb, while it should be over 1Mb 

WORKAROUND:

8. Delete \obj\Debug\net7.0-windows10.0.19041.0\win10-x64\priconfig.xml
9. Do incremental build:
- msbuild /p:WindowsPackageType=None MauiApp1.csproj
10. Observe size and content of resources.pri under bin\Debug\net7.0-windows10.0.19041.0\win10-x64\resources.pri. 
- Now it is expected 1Mb+ in size.
11. Try launching bin\Debug\net7.0-windows10.0.19041.0\win10-x64\MauiApp1.exe
- App launches successfully.

### Expected behavior

5. Launching MauiApp1.exe should succeed after switching mode incrementally.

### NuGet package version

None

**Comment by bpulliam** [comment]
While I agree this would be nice, there is an obvious workaround to do a clean build when changing the package type.
