### ISSUE TITLE
When continously scrolling down, ItemsRepeater jumps back up on Xbox One

### ISSUE THREAD

**Issue by Phranky** [microsoft/microsoft-ui-xaml#853]
**Describe the bug**
I have 2 nested ItemsRepeaters to display a hierarchical list of data. When I press and hold the D-pad down key on the Xbox-controller the focus is moved down through the vertical lists but at one point jumps back to the top of the list and continues to move down until it jumps up again.

**Steps to reproduce the bug**
1. Download the attached demo app
2. compile it and deploy it to a Xbox One and run it
3. press and hold the D-pad down key

**Expected behavior**
focus is moved down continuously and is not jumping back up 

**Screenshots**
I added a video illustrating the behavior. (Please pay attention to the scrollbar on the right for a clearer impression)

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001
Microsoft.UI.Xaml 2.2.190430003-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                  |     |
| May 2019 Update (18362)        | Yes   |
| October 2018 Update (17763)  |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |   |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |                               |
| Mobile                   |                               |
| Xbox                      | Yes                         |
| Surface Hub          |                               |
| IoT                         |                               |

**Additional context**

[ItemsRepeaterDemo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3278096/ItemsRepeaterDemo.zip)
[ItemsRepeaterScrollingIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3278216/ItemsRepeaterScrollingIssue.zip)

**Comment by ranjeshj** [comment]
Can you try doing an UpdateLayout on KeyDown of the outer repeater? I believe what might be happening is that the scrolling is happening faster than we can run layout and XYFocus logic is unable to find an element because none have been realized further down. Doing an UpdateLayout during keydown provides an opportunity for layout to run.

**Comment by Phranky** [comment]
Thanks for your answer.
I added an UpdateLayout on KeyDown, but unfortunately it didn't change anything. It still starts jumping at one point if I press and hold the D-Pad down (or up) key.

**Comment by ranjeshj** [comment]
can you please share your repro app ?

**Comment by Phranky** [comment]
@ranjeshj: You'll find the application to reproduce the issue in the ZIP-file attached to my original post above.

**Comment by ranjeshj** [comment]
I just tried the app on xbox with rs5_release bits and once i added a key_down on TopList in which i did UpdateLayout(), i never hit the jumping issue. Which build of xbox are you running ?

**Comment by ranjeshj** [comment]
Once i add the udpatelayout to keydown, I see the issue when it first loads and if i immediately press and hold the down button. But after a few seconds it is hard to repro. Is that what you see as well ? The first load might be an issue where the cache pages have not been loaded yet.

**Comment by Phranky** [comment]
@ranjeshj It's kind of what I experience. But it's not only on first load. I can reproduce it in _most_ cases when scrolling up or down. I already played with the cache length but it doesn't change this behavior.

**Comment by ranjeshj** [comment]
I think there is an issue with the way the repeaters outside the visible range realize elements. It looks like we get to a point were the repeaters outside the visible range don't realize any elements (because their realization window is empty) and that causes XYFocus to not find a reasonable candidate.
