### ISSUE TITLE
RadioButton with GroupName inside ContentDialog

### ISSUE THREAD

**Issue by benderto** [microsoft/microsoft-ui-xaml#8534]
### Describe the bug

I have x64 packaged WinUI3 application, latest version WindowsAppSDK. There is a problem when I want to set `IsChecked` state of some `RadioButton` inside the `ContentDialog`. Sometimes it ends up in System.Runtime.InteropServices.COMException without any additional info. It seems very random. Sometimes it crashes on second showing, sometimes on tenth. It never crashes on the first showing. I have user control that inherits from the `ContentDialog` instead of the `UserControl` and I set the checked state of some `RadioButton` inside `Loaded` method. Each `RadioButton` has a `GroupName` assigned to it. When I remove `GroupName` from the XAML, everything work just fine.

### Steps to reproduce the bug

1. Create new blank packaged WinUI3 app with Windows app packaging project
2. Create new user control, change its base class to `ContentDialog` and add some radio buttons
Xaml for this component

```
<ContentDialog
    x:Class="RadioButtonGroupCrash.Dialog"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:RadioButtonGroupCrash"
    IsPrimaryButtonEnabled="True"
    IsSecondaryButtonEnabled="True"
    PrimaryButtonText="Ok"
    SecondaryButtonText="Cancel">

    <StackPanel>
        <RadioButton x:Name="rb1" GroupName="group">
        </RadioButton>

        <RadioButton x:Name="rb2" GroupName="group">
        </RadioButton>
    </StackPanel>
</ContentDialog>
```
Code behind
```
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;

namespace RadioButtonGroupCrash
{
    public sealed partial class Dialog : ContentDialog
    {
        public Dialog()
        {
            this.InitializeComponent();
            Loaded += Dialog_Loaded;
        }

        private void Dialog_Loaded(object sender, RoutedEventArgs e)
        {
            rb1.IsChecked = true;
        }
    }
}
```
3. Show dialog in MainWindow code behind
```
private async void myButton_Click(object sender, RoutedEventArgs e)
{
    await new Dialog() { XamlRoot = App.MainWindow.Content.XamlRoot }.ShowAsync();
}
```

Example
[RadioButtonGroupCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11688744/RadioButtonGroupCrash.zip)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

 WinRT.Runtime.dll!WinRT.ExceptionHelpers.ThrowExceptionForHR.__Throw|20_0(int hr)	Unknown
 Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.Primitives.IToggleButtonMethods.set_IsChecked(WinRT.IObjectReference _obj, bool? value)	Unknown
RadioButtonGroupCrash.dll!RadioButtonGroupCrash.Dialog.Dialog_Loaded(object sender, Microsoft.UI.Xaml.RoutedEventArgs e) Line 16	C#
 Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(System.IntPtr thisPtr, System.IntPtr sender, System.IntPtr e)	Unknown
 [Native to Managed Transition]	
 	Microsoft.ui.xaml.dll!DirectUI::CRoutedEventSourceBase<DirectUI::IUntypedEventSource,ABI::Microsoft::UI::Xaml::IRoutedEventHandler,IInspectable,ABI::Microsoft::UI::Xaml::IRoutedEventArgs>::Raise()	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::CRoutedEventSourceBase<DirectUI::IUntypedEventSource,ABI::Microsoft::UI::Xaml::IRoutedEventHandler,IInspectable,ABI::Microsoft::UI::Xaml::IRoutedEventArgs>::UntypedRaise()	Unknown
 Microsoft.ui.xaml.dll!CCoreServices::CLR_FireEvent()	Unknown
 Microsoft.ui.xaml.dll!CommonBrowserHost::CLR_FireEvent()	Unknown
 Microsoft.ui.xaml.dll!CControlBase::ScriptCallback()	Unknown
 Microsoft.ui.xaml.dll!CXcpDispatcher::OnScriptCallback()	Unknown
 Microsoft.ui.xaml.dll!CXcpDispatcher::OnWindowMessage()	Unknown
 Microsoft.ui.xaml.dll!CXcpDispatcher::WindowProc()	Unknown
 user32.dll!UserCallWinProcCheckWow()	Unknown
 user32.dll!SendMessageWorker(struct tagWND *,unsigned int,unsigned __int64,__int64,int)	Unknown
 user32.dll!SendMessageW()	Unknown
 Microsoft.ui.xaml.dll!CXcpBrowserHost::SyncScriptCallbackRequest()	Unknown
 Microsoft.ui.xaml.dll!CEventManager::RaiseHelper()	Unknown
 Microsoft.ui.xaml.dll!CEventManager::RaiseLoadedEventForObject()	Unknown
 Microsoft.ui.xaml.dll!CEventManager::RaiseLoadedEvent()	Unknown
 Microsoft.ui.xaml.dll!CCoreServices::NWDrawTree()	Unknown
 Microsoft.ui.xaml.dll!CCoreServices::NWDrawMainTree()	Unknown
 Microsoft.ui.xaml.dll!CWindowRenderTarget::Draw()	Unknown
 Microsoft.ui.xaml.dll!CXcpBrowserHost::OnTick()	Unknown
 Microsoft.ui.xaml.dll!CXcpDispatcher::Tick()	Unknown
 Microsoft.ui.xaml.dll!CXcpDispatcher::OnReentrancyProtectedWindowMessage()	Unknown
 Microsoft.ui.xaml.dll!CXcpDispatcher::WindowProc()	Unknown
 Microsoft.ui.xaml.dll!CDeferredInvoke::DispatchQueuedMessage()	Unknown
 Microsoft.ui.xaml.dll!Microsoft::WRL::Details::DelegateArgTraits<long (__cdecl ABI::Windows::Foundation::ITypedEventHandler_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Microsoft::UI::Dispatching::DispatcherQueueTimer *,ABI::Microsoft::UI::Dispatching::IDispatcherQueueTimer *>,IInspectable *>::*)(ABI::Microsoft::UI::Dispatching::IDispatcherQueueTimer *,IInspectable *)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,ABI::Windows::Foundation::ITypedEventHandler<ABI::Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::FtmBase>,`CXcpDispatcher::Init'::`75'::<lambda_1> &,1,ABI::Microsoft::UI::Dispatching::IDispatcherQueueTimer *,IInspectable *>::Invoke()	Unknown
 CoreMessagingXP.dll!Microsoft::WRL::Details::DelegateArgTraits<long >::DelegateInvokeHelper<struct Microsoft::WRL::Implements<struct Microsoft::WRL::RuntimeClassFlags<2>,struct Windows::Foundation::ITypedEventHandler<class Microsoft::UI::Dispatching::DispatcherQueueTimer *,struct IInspectable *>,class Microsoft::WRL::FtmBase>,class <lambda_82cf8073f4f042d1a68771c460cb9f49>,-1,struct Microsoft::UI::Dispatching::IDispatcherQueueTimer *,struct IInspectable *>::Invoke(struct Microsoft::UI::Dispatching::IDispatcherQueueTimer *,struct IInspectable *)	Unknown
 CoreMessagingXP.dll!Microsoft::WRL::InvokeTraits<-2>::InvokeDelegates<class <lambda_1e854da9c9ccd42f6138c3b007a32877>,struct Windows::Foundation::ITypedEventHandler<class Microsoft::UI::Dispatching::DispatcherQueueTimer *,struct IInspectable *> >(class <lambda_1e854da9c9ccd42f6138c3b007a32877>,class Microsoft::WRL::Details::EventTargetArray *,class Microsoft::WRL::EventSource<struct Windows::Foundation::ITypedEventHandler<class Microsoft::UI::Dispatching::DispatcherQueueTimer *,struct IInspectable *>,struct Microsoft::WRL::InvokeModeOptions<-2> > *)	Unknown
 	CoreMessagingXP.dll!Microsoft::UI::Dispatching::DispatcherQueueTimer::TimerCallback(void *)	Unknown
 	CoreMessagingXP.dll!CFlat::SehSafe::Execute<<lambda_654db17c35df07198786f0867aa10de6>>()	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::TimeoutHandler::ImportAdapter$(class CFlat::Box$1<struct CFlat::FunctionPointerAndUserData$1<long > > *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch(void)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchNextItem(class Microsoft::CoreUI::Dispatch::DispatchItem *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop(enum Microsoft::CoreUI::Dispatch::RunnablePriorityMask)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop(enum Microsoft::CoreUI::Dispatch::RunMode)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::DrainCoreMessagingQueue(enum Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority,void * *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch(bool,enum Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority,void * *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatchRaw(enum Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority,bool,void * *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::DoWork(struct HWND__ *,enum Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority,bool)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::HandleDispatchNotifyMessage(struct HWND__ *,unsigned __int64,__int64)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::WindowProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchClientMessage()	Unknown
 	user32.dll!__fnDWORD()	Unknown
 	ntdll.dll!KiUserCallbackDispatcherContinue()	Unknown
 	win32u.dll!NtUserGetMessage()	Unknown
 	user32.dll!GetMessageW()	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::RunDesktopWindowMessageLoop()	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::StartDesktop()	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplicationFactory::Start()	Unknown
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference _obj, Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	RadioButtonGroupCrash.dll!RadioButtonGroupCrash.Program.Main(string[] args) Line 31	C#
 	[Native to Managed Transition]	
 	[Inline Frame] hostpolicy.dll!coreclr_t::execute_assembly(int) Line 89	C++
 	hostpolicy.dll!run_app_for_context(const hostpolicy_context_t & context, int argc, const wchar_t * * argv) Line 255	C++
 	hostpolicy.dll!run_app(const int argc, const wchar_t * * argv) Line 284	C++
 	hostpolicy.dll!corehost_main(const int argc, const wchar_t * * argv) Line 430	C++
 	hostfxr.dll!execute_app(const std::wstring & impl_dll_dir, corehost_init_t * init, const int argc, const wchar_t * * argv) Line 146	C++
 	hostfxr.dll!`anonymous namespace'::read_config_and_execute(const std::wstring & host_command, const host_startup_info_t & host_info, const std::wstring & app_candidate, const std::unordered_map<enum known_options,std::vector<std::wstring,std::allocator<std::wstring>>,known_options_hash,std::equal_to<enum known_options>,std::allocator<std::pair<enum known_options const ,std::vector<std::wstring,std::allocator<std::wstring>>>>> & opts, int new_argc, const wchar_t * * new_argv, host_mode_t mode, const bool is_sdk_command, wchar_t * out_buffer, int buffer_size, int * required_buffer_size) Line 533	C++
 	hostfxr.dll!fx_muxer_t::handle_exec_host_command(const std::wstring & host_command, const host_startup_info_t & host_info, const std::wstring & app_candidate, const std::unordered_map<enum known_options,std::vector<std::wstring,std::allocator<std::wstring>>,known_options_hash,std::equal_to<enum known_options>,std::allocator<std::pair<enum known_options const ,std::vector<std::wstring,std::allocator<std::wstring>>>>> & opts, int argc, const wchar_t * * argv, int argoff, host_mode_t mode, const bool is_sdk_command, wchar_t * result_buffer, int buffer_size, int * required_buffer_size) Line 1018	C++
 	hostfxr.dll!fx_muxer_t::execute(const std::wstring host_command, const int argc, const wchar_t * * argv, const host_startup_info_t & host_info, wchar_t * result_buffer, int buffer_size, int * required_buffer_size) Line 579	C++
 	hostfxr.dll!hostfxr_main_startupinfo(const int argc, const wchar_t * * argv, const wchar_t * host_path, const wchar_t * dotnet_root, const wchar_t * app_path) Line 61	C++
 	RadioButtonGroupCrash.exe!exe_start(const int argc, const wchar_t * * argv) Line 235	C++
 	RadioButtonGroupCrash.exe!wmain(const int argc, const wchar_t * * argv) Line 304	C++
 	[Inline Frame] RadioButtonGroupCrash.exe!invoke_main() Line 90	C++
 	RadioButtonGroupCrash.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

**Comment by ranjeshj** [comment]
RadioButtons control might be an option here. (Note the 's' at the end). RadioButtons is easier to get right and accessibility experience is better. This still seems like a bug.

**Comment by JJBrychell** [comment]
This issue has been addressed and is scheduled for the next preview release of 1.6.

Problem arises from managed garbage collection interaction with the internal radio button tables.  When a radio button is named it is entered into an internal table that is searched when determining which button(s) to uncheck when a new button is checked.  The entry stays in this table until the radio button is destructed, but with garbage collection it can stick around for a while after it been removed from the tree.  So when you show/hide the content dialog, you can get multiple sets of radio buttons for the dialog in this internal table.  This is handled correctly, except when the timing of garbage collection is just right.  When garbage collection happens, it does so off the UI thread, so it only partially destructs the UI element and then schedules the rest of it to be done on the UI thread.  If a check box checked changes comes in between when garbage collection has partially destructed the item, but the UI thread hasn't completed that destruction, the radio button code doesn't realize that even though it still exists, it is in a bad state that ultimately causes this crash.  We have modified the process to no longer rely on any of the data that is partially destructed in garbage collection.
