### ISSUE TITLE
Proposal: Adding ability to get the HTML Source code without Executing a script on the page

### ISSUE THREAD

**Issue by musasystem** [microsoft/microsoft-ui-xaml#8541]
Hello,

I like the WebView2 but since I'm dealing a lot of the HTML of the page I find it suitable to be able to retreive the printed HTML source code of the current page direct by using for example:
`html = webView2.CoreWebView2.getHTML()`
and it runs synchronously, the only possible wait to show the HTML of the page is by using 
`Dim html As String
html = Await WebView2.ExecuteScriptAsync("document.documentElement.outerHTML;")

' The Html comes back with unicode character codes, other escaped characters, and
' wrapped in double quotes, so I'm using this code to clean it up for what I'm doing.
html = Regex.Unescape(html)
html = html.Remove(0, 1)
html = html.Remove(html.Length - 1, 1)` 
as shown by [Xaviorq8] on stackoverflow

I would like to hear your opinion

**Comment by kmgallahan** [comment]
Not really the repo for WebView2 stuff.

https://github.com/MicrosoftEdge/WebView2Feedback
