### ISSUE TITLE
Binding to the Size property of ItemsSource does not work

### ISSUE THREAD

**Issue by YexuanXiao** [microsoft/microsoft-ui-xaml#8546]
### Describe the bug

I tried to use the Size property of ItemsSource to determine how wide the serial number column is, so I wrote the following XAML, but the binding actually didn’t work.

```xaml

            <ListView
                Name="MusicViewList"
                Grid.Row="1"
                IsItemClickEnabled="True">
                <ListView.ItemTemplate>
                    <DataTemplate x:DataType="local:InfoViewModel">
                        <local:InfoListItem
                            Title="{x:Bind Title}"
                            Artist="{x:Bind Artist}"
                            Bitrate="{x:Bind local:InfoViewModel.TransformBitrate(Bitrate)}"
                            State="{x:Bind State, Mode=OneWay}"
                            Track="{x:Bind Track}"
                            TrackWidth="{x:Bind local:InfoListItem.DecideTrackWidth(((}"
                            Duration="{x:Bind local:InfoViewModel.TransformDuration(Duration)}" />
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>

```
Because the collection is obtained from the NavigatedTo event, there is no name for directly binding it.

A simple example is as follows:

```xaml

            <ListView
                Name="MusicViewList">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <Grid />
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>

            <TextBlock
                Text="{x:Bind ((IBindableObservableVector)MusicViewList.ItemsSource).Size,
                              Mode=OneWay}" />

```

### Steps to reproduce the bug

none

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows Insider Build (xxxxx)

**Comment by kmgallahan** [comment]
`ListiView.ItemsSource` = an `Object` that implements one of [a few interfaces](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.itemscontrol.itemssource?view=windows-app-sdk-1.3#remarks).

None of those interfaces define a `Size` property, and you haven't identified the specific type you are binding to other than a cast to `IBindableObservableVector`.

**Comment by DmitriyKomin** [comment]
@YexuanXiao, as @kmgallahan noted, IBindableObservableVector that is cast to in the x:Bind expression does not have a Size property. Try casting to the type with the Size property instead.
