### ISSUE TITLE
Proposal: Add Tag value to NavigationView's Settings item

### ISSUE THREAD

**Issue by YuliKl** [microsoft/microsoft-ui-xaml#855]
# Proposal: Add Tag value to NavigationView's Settings item

## Summary

NavigationView provides a Settings item with default icon, localized text, tooltip etc. But this item does not set its Tag property. The Tag should also be set to "settings"

## Rationale
At least one customer [has reported](https://github.com/microsoft/microsoft-ui-xaml/issues/833#issuecomment-500766685) creating a custom settings item because of the missing Tag value.

**Comment by jevansaks** [comment]
Seems reasonable, let's do it.
