### ISSUE TITLE
ScrollViewer: Shift + Mouse wheel doesn't scroll horizontally. 

### ISSUE THREAD

**Issue by acouvert-msft** [microsoft/microsoft-ui-xaml#8553]
### Describe the bug

By pressing shift while moving the mouse wheel on top of a Scrollviewer, no horizontal scrolling is occurring.

### Steps to reproduce the bug

Xaml:
```
<ScrollViewer
        Width="500"
        Height="500"
        HorizontalScrollBarVisibility="Visible"
        HorizontalScrollMode="Enabled"
        VerticalScrollBarVisibility="Visible"
        VerticalScrollMode="Enabled">
        <Border
            Width="1000"
            Height="1000"
            Background="Green" />
</ScrollViewer>
```

When moving the mouse wheel on top of the Scrollviewer, vertical scrolling is occurring ✅.
When pressing shift while moving the mouse wheel on top of the Scrollviewer, no horizontal scrolling is occurring ⚠️.

### Expected behavior

I'd expect that when pressing shift while moving the mouse wheel on top of the Scrollviewer, horizontal scrolling would occur.

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

**Comment by jeremy-visionaid** [comment]
I also observe this problem in Win UI 3

**Comment by kaismic** [comment]
I have the same issue. Using .NET 6, WinUI 3 in Windows 10

**Comment by cosmin42** [comment]
Same problem here, it works using the touch pad though.

**Comment by jeremy-visionaid** [comment]
I see there is a 4 year old proposal for this: #877 
Doesn't give me great hope that this will be addressed any time soon :(

**Comment by ranjeshj** [comment]
dup of https://github.com/microsoft/microsoft-ui-xaml/issues/877
