### ISSUE TITLE
CommandBar crashes applications in RS1

### ISSUE THREAD

**Issue by gascardi** [microsoft/microsoft-ui-xaml#856]
**Describe the bug**
Adding a CommandBar control to a page crashes the app with a XAML exception.
This breaks the promise of WinUI providing backward compatibility for RS1 devices.

**Steps to reproduce the bug**
1. Add a `<CommandBar />` control to a page
2. Open the app
3. Navigate to the page with the CommandBar

**Expected behavior**
CommandBar is displayed normally.

**Actual behavior**
App crashes with a XAML unhandled exception:
```
System.Exception: The text associated with this error code could not be found.
Failed to assign to property 'Windows.UI.Color.A'. [Line: 0 Position: 0]
```

**Version Info**
NuGet package version: 
We started seeing this when we upgraded from 2.0.181018003 to 2.1.190405004.1, but still see it in the latest stable 2.1.190606001.

We started seeing telemetry from users and they're all for RS1 devices.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            |  No  |
| October 2018 Update (17763)        | No     |
| April 2018 Update (17134)          |   No   |
| Fall Creators Update (16299)       |  No    |
| Creators Update (15063)            | No     |
| Anniversary Update (14393)         | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |    |
| IoT                         |    |

**Comment by jevansaks** [comment]
Thanks for reporting! Have you also added `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />` to your app.xaml? If yes, can you share a minimal repro app with this?

Also starting with 2.2 we are dropping support for 14393 (1607), the min version will be 15063 (1703). I see in your bug report that you are seeing it on 14393 and not 18362, what about 15063?

**Comment by gascardi** [comment]
Yes, we have <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" /> in our your app.xaml. It worked in RS1 before this update.

Good to know the minimum will be upgraded, this might force us to drop support to our RS1 users.

I updated the table. I confirmed we have telemetry from customers in RS2+ that navigated to the page with the CommandBar control and the app didn't crash.

Sample app:
[CommandBarCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3278971/CommandBarCrash.zip)

**Comment by jevansaks** [comment]
[RS1 is out of official support](https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet) so we are dropping support for RS1 starting in WinUI 2.2.

**Comment by gascardi** [comment]
This bug is before WinUI 2.2 though, which does state that RS1 is supported, so can you document that in the README files?

**Comment by jevansaks** [comment]
> This bug is before WinUI 2.2 though, which does state that RS1 is supported, so can you document that in the README files?

Yes we're about to update the readme that RS1 is no longer supported.

**Comment by gascardi** [comment]
Thank you, that will be very helpful!
