### ISSUE TITLE
SplitButton and ToggleSplitButton don't respect Flyout placement

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#8560]
### Describe the bug

SplitButton and ToggleSplitButton's flyout always show below, no matter what value you set to Placement.

### Steps to reproduce the bug

This is supposed to be inside a horizontal StackPanel, but it's not showing for some reason.

<StackPanel HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Orientation="Horizontal">

    <Button Content="Button">

        <Button.Flyout>

            <MenuFlyout Placement="Top"/>

        </Button.Flyout>

    </Button>

    <DropDownButton Content="DropDownButton">

        <DropDownButton.Flyout>

            <MenuFlyout Placement="Top"/>

        </DropDownButton.Flyout>

    </DropDownButton>

    <SplitButton Content="SplitButton">

        <SplitButton.Flyout>

            <MenuFlyout Placement="Top"/>

        </SplitButton.Flyout>

    </SplitButton>

    <ToggleSplitButton Content="ToggleSplitButton">

        <ToggleSplitButton.Flyout>

            <MenuFlyout Placement="Top"/>

        </ToggleSplitButton.Flyout>

    </ToggleSplitButton>
    
</StackPanel>

### Expected behavior

It should work with every control you can set a Flyout.

### NuGet package version

WinUI 3 - Windows App SDK 1.4 Experimental 1: 1.4.230518007-experimental1

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Also happens with Flyout and CommanBarFlyout.

**Comment by ranjeshj** [comment]
@eduardobragaxz this is by design and intentional.

**Comment by eduardobragaxz** [comment]
@ranjeshj why is that?
