### ISSUE TITLE
Proposal: Chip control for WinUI apps

### ISSUE THREAD

**Issue by DmitryBorodiy** [microsoft/microsoft-ui-xaml#8564]
# Proposal: Chip control for WinUI apps

## Summary 

Chips are compact elements that represent an attribute, text, entity, or action. They allow users to enter information, select a choice, filter content, or trigger an action.

## Rationale

Chips allow users to enter information, make selections, filter content, or trigger actions. While buttons are expected to appear consistently and with familiar calls to action, chips should appear dynamically as a group of multiple interactive elements.

## Scope

Microsoft.UI.Xaml.Controls.Chip - chip control.
Microsoft.UI.Xaml.Controls.ChipGroup - chip group control.

**Comment by christosk92** [comment]
This already exists in the community toolkit labs repository.
https://github.com/CommunityToolkit/Labs-Windows/issues/427

**Comment by JohnnyWestlake** [comment]
Worth noting that the Community Toolkit version is implemented in C#, so not immediately usable by all WinUI 3 apps. A C++/WinRT port of it seems reasonable.
