### ISSUE TITLE
MenuBar access keys displayed when opening a MenuBarItem with all its items disabled

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#8565]
### Describe the bug

If we use the access keys to open a `MenuBarItem` which has all its `MenuFlyoutItem` disabled, the access keys of the parent `MenuBar` (and all the other controls within the same scope) are displayed.

<img width="152" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/20152272/c308efa8-54f2-4012-9ef0-c3702e6363db">

### Steps to reproduce the bug

1. Create a blank UWP app and add the following XAML to the main page:
```xml
<mux:MenuBar>
    <mux:MenuBarItem Title="File" AccessKey="F">
        <MenuFlyoutItem AccessKey="N" Text="New" />
        <MenuFlyoutItem AccessKey="O" Text="Open" />
    </mux:MenuBarItem>
    <mux:MenuBarItem Title="Edit" AccessKey="E">
        <MenuFlyoutItem
            AccessKey="C"
            IsEnabled="False"
            Text="Copy" />
        <MenuFlyoutItem
            AccessKey="V"
            IsEnabled="False"
            Text="Paste" />
    </mux:MenuBarItem>
    <mux:MenuBarItem Title="Display" AccessKey="D">
        <MenuFlyoutItem AccessKey="F" Text="Full screen" />
    </mux:MenuBarItem>
</mux:MenuBar>
```
2. Run the application
3. Press ALT+E to open the "Edit" menu
4. The "Edit" menu opens.
5. The runtime displays the access keys of all the `MenuBarItem` instead of displaying nothing since the opened `MenuBarItem` scope does not contain any active access key.

### Expected behavior

There are no access keys displayed when opening the "Edit" menu since its scope does not contain any active access keys

### Screenshots

![mux access keys issue](https://github.com/microsoft/microsoft-ui-xaml/assets/20152272/3a7850f0-300c-403d-a06f-1b205e4c7c46)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The same issue occurs when using XAML Island

**Comment by ranjeshj** [comment]
Thanks for reporting. We're focusing on WinUI3 issues as mentioned here - https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2
