### ISSUE TITLE
ListView.ChoosingGroupHeaderContainer returns null for ChoosingGroupHeaderContainerEventArgs.GroupHeaderContainer for all groups except the first the first time the ListView is drawn.

### ISSUE THREAD

**Issue by tinodo** [microsoft/microsoft-ui-xaml#8569]
### Describe the bug

To make my WinUI application pass all accessibility tests, I need to use the `ChoosingGroupHeaderContainer` event on a `ListView`. Only this way, I can set the `AutomationProperties.Name` property, which is required. (More information: [ListViewBase.ChoosingGroupHeaderContainer Event](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.choosinggroupheadercontainer?view=winrt-22621))

When I use the event, the first time the `ListView` is drawn, for _all groups_, _except the first_, the `args.GroupHeaderContainer` value is `null`. Hence, I cannot set the `AutomationProperties.Name` property. During my tests, I found that the second time the `ListView` is drawn, because the underlying `ObservableGroupedCollection` is updated, the `GroupHeaderContainer` contains the proper `ListViewBaseHeaderItem`, they are no longer null.

To me, this appears to be a bug.

### Steps to reproduce the bug

1. Create a `ListView` bound to a `CollectionViewSource` with `IsSourceGrouped="True"` and implement the `ChoosingGroupHeaderContainer` event on the `ListView`.
2. Create the proper data source for the `CollectionViewSource` and check in the implementation of the `ChoosingGroupHeaderContainer` event whether the `args.GroupHeaderContainer` is null. You will see that the first time the `ListView` is rendered, for all groups except the first, the property is null. 
3. Change the items in the data source, forcing the `ListView` to update and check the `ChoosingGroupHeaderContainer` events for the `args.GroupHeaderContainer`. You will see that these are now properly populated for all groups.

### Expected behavior

I expect the `ChoosingGroupHeaderContainer` event to **always** pass the proper `ListViewBaseHeaderItem` in the `args.GroupHeaderContainer` property.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

XAML Example:

```
                <ListView ChoosingGroupHeaderContainer="ListView_ChoosingGroupHeaderContainer"
                    SelectionMode="None"
                    ItemTemplate="{StaticResource RegistrationListViewTemplate}"
                    ItemsSource="{Binding Source={StaticResource RegistrationsCVS}}">
                    <ListView.ItemsPanel>
                        <ItemsPanelTemplate>
                            <ItemsStackPanel AreStickyGroupHeadersEnabled="True"/>
                        </ItemsPanelTemplate>
                    </ListView.ItemsPanel>
                    <ListView.ItemContainerStyle>
                        <Style TargetType="ListViewItem">
                            <Setter Property="HorizontalContentAlignment" Value="Stretch"/>
                        </Style>
                    </ListView.ItemContainerStyle>
                    <ListView.GroupStyle>
                        <GroupStyle>
                            <GroupStyle.HeaderTemplate>
                                <DataTemplate x:DataType="communityCollections:IReadOnlyObservableGroup">
                                    <Border>
                                        <TextBlock Text="{Binding Key}" Style="{ThemeResource TitleTextBlockStyle}"/>
                                    </Border>
                                </DataTemplate>
                            </GroupStyle.HeaderTemplate>
                            <GroupStyle.HeaderContainerStyle>
                                <Style TargetType="ListViewHeaderItem">
                                    <Setter Property="HorizontalContentAlignment" Value="Stretch"/>
                                </Style>
                            </GroupStyle.HeaderContainerStyle>
                        </GroupStyle>
                    </ListView.GroupStyle>
                </ListView>
```
                
C#
```
        private void ListView_ChoosingGroupHeaderContainer(ListViewBase sender, ChoosingGroupHeaderContainerEventArgs args)
        {
            if (args.Group is ObservableGroup<string, MyClass> group)
            {
                if (args.GroupHeaderContainer == null)
                {
                    ???
                }
                else
                {
                    AutomationProperties.SetName(args.GroupHeaderContainer, group.Key);
                }
            }
        }
```

**Comment by ranjeshj** [comment]
Hety @tinodo, In the case where the provided container is null, you can create a new ListViewHeaderItem, set the automation properties on it, then set that in the args. ListView will use that object for the header.
