### ISSUE TITLE
MediaPlayerElement TransportControls Scaling Issue inside of Viewbox

### ISSUE THREAD

**Issue by elijahwass99** [microsoft/microsoft-ui-xaml#8574]
### Describe the bug

When a MediaPlayerElement is used inside of a Viewbox control with AreTransportControlsEnabled enabled, the TransportControls are very small. In this case, I also have the Stretch property set to "Uniform".

### Steps to reproduce the bug

1. Place a MediaPlayerElement control inside a Viewbox
- Set `AreTransportControlsEnabled` to **true**
- Set `Stretch` to **Uniform**

### Expected behavior

TransportControls do not scale down.

### NuGet package version

Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

**Comment by ranjeshj** [comment]
@elijahwass99 This is by design. Anything in a viewbox will get scaled including text. Are you trying to just scale the video? Can you just set the size and stretch properties instead of using a ViewBox ?
