### ISSUE TITLE
Generic InvalidCast Error - How to Debug Further?

### ISSUE THREAD

**Issue by Dealman** [microsoft/microsoft-ui-xaml#8583]
Been learning WinUI 3 for a little while now and everything has been coming along nicely until yesterday when my program just out of the blue has stopped working.

The error I get seems to be rather generic;
```
Exception thrown: 'System.InvalidCastException' in WinRT.Runtime.dll
WinRT information: No such interface supported
```

Which just points me to some generated code. I'm still fairly new to debugging 'properly' in Visual Studio, so this isn't at all helpful for me. And I have no idea how to further try to debug this.

Regardless, by spending a few hours today breakpointing my stuff, I think I've narrowed it down a bit.

I have 4 JSON files which I deserialize into 4 lists of object `ResourceBase` when the app is started. These files are deserialized properly and I have verified that all properties are valid.

After this is all done, I bind a `GridView` to display these objects, which then creates a custom UserControl for each item. This is where the error starts happening.

I have narrowed it down to a specific item, but that's about as far as I got. Which is this item;

```json
{
  "Name": "Kashyyykian Domesticated Milk",
  "Category": "Organic/Creature/Resources/Creature Food/Milk/Domesticated Milk",
  "Icon": "Milk.png",
  "IsRecycled": false,
  "Attributes": [
    {
      "Name": "Decay Resistance",
      "ShortName": "DR",
      "Min": 1,
      "Max": 1000
    },
    {
      "Name": "Flavor",
      "ShortName": "FL",
      "Min": 1,
      "Max": 700
    },
    {
      "Name": "Overall Quality",
      "ShortName": "OQ",
      "Min": 1,
      "Max": 1000
    },
    {
      "Name": "Potential Energy",
      "ShortName": "PE",
      "Min": 300,
      "Max": 1000
    }
  ]
},
```

Specifically, when the UserControl attempts to bind to the list of attributes - it throws the aforementioned exception. The bindings are done like such;

```xaml
<DataTemplate x:Key="ResourceAttributeTemplate" x:DataType="models:ResourceAttribute">
    <Grid BorderBrush="{StaticResource AccentControlElevationBorderBrush}" BorderThickness="1" Width="128" Height="auto">
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition/>
            <ColumnDefinition Width="auto"/>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>
        <TextBlock Text="{x:Bind Name, Converter={StaticResource BottomCornerRadiusFilterConverter}}" Style="{StaticResource BaseTextBlockStyle}" Grid.Row="0" Grid.ColumnSpan="3" TextAlignment="Center"/>
        <TextBlock Text="{x:Bind Min, Converter={StaticResource StringFormatConverter}, ConverterParameter='{}{0}'}" Grid.Row="1" Grid.Column="0" TextAlignment="Center"/>
        <TextBlock Text="-" Grid.Row="1" Grid.Column="1" TextAlignment="Center"/>
        <TextBlock Text="{x:Bind Max, Converter={StaticResource StringFormatConverter}, ConverterParameter='{}{0}'}" Grid.Row="1" Grid.Column="2" TextAlignment="Center"/>
    </Grid>
</DataTemplate>
```

And the ResourceAttribute class is defined as such;
```cs
public class ResourceAttribute
{
    public string Name
    {
        get; set;
    }
    public string ShortName
    {
        get; set;
    }
    public int Min
    {
        get; set;
    }
    public int Max
    {
        get; set;
    }
}
```

This is the debug info I get before it crashes;
```
[ResourceDataService]: Decay Resistance(DR) | Min: 1(Int32) Max: 1000(Int32)
[ResourceDataService]: Flavor(FL) | Min: 1(Int32) Max: 700(Int32)
[ResourceDataService]: Overall Quality(OQ) | Min: 1(Int32) Max: 1000(Int32)
[ResourceDataService]: Potential Energy(PE) | Min: 300(Int32) Max: 1000(Int32)
```

The properties are deserialized as expected.

Any help how to further debug what's going on here would be greatly appreciated...

**Comment by Dealman** [comment]
Spotted the error just after I posted this as tends to be the case...

For some reason `Converter={StaticResource BottomCornerRadiusFilterConverter}` had made its way to where I bind the `Name` property. Not entirely sure how.

While the issue can be closed now, I still would love to know if there's a better way to debug this error to find specifically where the cast fails...?

**Comment by duncanmacmichael** [comment]
Closing this issue per the original poster's comment and length of time since last activity.
