### ISSUE TITLE
No acrylic effect above dynamic contents

### ISSUE THREAD

**Issue by Nevodev** [microsoft/microsoft-ui-xaml#8587]
### Describe the bug

There's no acrylic effect above dynamic contents. Both WinUI 3 Gallery and third-party apps.

WinUI 2 Gallery:
![winui2gallery](https://github.com/microsoft/microsoft-ui-xaml/assets/51047891/17e9dba3-5f06-448c-abdb-33945d0e2209)

WinUI 3 Gallery:

![winui3gallery](https://github.com/microsoft/microsoft-ui-xaml/assets/51047891/52bc3ef5-2abd-4a90-aa05-5a7c6d3278d1)

Apple Music Preview:
- Dynamic Covers:
![amp1](https://github.com/microsoft/microsoft-ui-xaml/assets/51047891/2faa1992-3ee8-4887-a6e2-e3b81ec4b96c)
- Menu Flyouts (the background is animated so you can see it shows gray):
![amp2](https://github.com/microsoft/microsoft-ui-xaml/assets/51047891/bb13d062-94f9-448e-b805-e78924cb474e)
- Clearer in this pic:
![amp3](https://github.com/microsoft/microsoft-ui-xaml/assets/51047891/38a112dd-8d78-4459-914d-4b5cb1609ba6)
(The content in the list is static, so you can see it's blurred, but the background it's not)

### Steps to reproduce the bug

For WinUI 3 Gallery:
1. Open Media > MediaPlayerElement in the side menu
2. You can see there's no acrylic effect.

### NuGet package version

None

### Windows version

Windows Insider Build (xxxxx)

**Comment by DmitriyKomin** [comment]
@Nevodev - unfortunately, acrylic over externally-rendered content like MediaPlayerElement is not supported and is a known limitation of WinAppSDK composition. More details in this doc: [Enhance UI with the Visual layer (Windows App SDK/WinUI 3) - Windows apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/composition)
