### ISSUE TITLE
Static library for WinUI3 target is not getting compiled when build parallelly with any other target.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#8589]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Static-library-for-WinUI3-target-is-not-/10398912)._

---
Recently we started writing code for WinUI3 windows application. As part of it we decided to create a static library target which will have all WinUI3 related code and thus WinUI 3 related properties are set accordingly. When I am building this target along it builds fine. We are using a TWBuild.cmake script to build a target like below.

```
D:\TW\Workspace>**cmake -DTW_BUILD_TYPE=Build -DTW_BUILD_PRESET=Windows-x64-Debug -D**BUILD_PARALLEL**=OFF -P D:\TW\Workspace\TWBuild.cmake -- WinUILib
TW_BUILD_TARGETS WinUILib**
'C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe' '--build' '--preset' 'Windows-x64-Debug' '--target' 'WinUILib' '--' '/m:17' '/p:CL_MPcount=20' '/v:m' '/nologo'

Determining projects to restore...
  Restored D:\TW\Builds\TWInt\Windows-x64\WinUILib.vcxproj (in 413 ms).
  Checking Build System
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(505,5): warning MSB8021: The value 'MultiByte' of the variable 'CharacterSet' is incompatible with the value 'true' of the variable 'WindowsAppContainer'. [D:\TW\Builds\TWInt\Windows-x64\DemoApp.vcxproj]
  Building Custom Rule D:/TW/Workspace/CMakeLists.txt
  cmake_pch.cxx
  TWWinUI3App.cpp
  WinUILib.vcxproj -> D:\TW\Builds\TWLib\Windows-x64\Debug\WinUILib.lib
  C:\Users\mohsin.siddiqui\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\native\.. \.. \runtimes\win10-x64\native\Microsoft.WindowsAppRuntime.Bootstrap.dll
  1 File(s) copied
========= Build Successful =========

D:\TW\Workspace>
```
In TWBuild.cmake it has cmake argument as BUILD_PARALLEL which decide if I want to build multiple targets in parallel (with value ON or OFF). 

So if I compile WinUI3Lib and RegularLib sequentially , it works fine. 

```
D:\TW\Workspace>cmake -DTW_BUILD_TYPE=Build -DTW_BUILD_PRESET=Windows-x64-Debug -DBUILD_PARALLEL=OFF -P D:\TW\Workspace\TWBuild.cmake -- WinUI3Lib RegularLib
TW_BUILD_TARGETS WinUI3Lib; RegularLib
'C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe' '--build' '--preset' 'Windows-x64-Debug' '--target' 'WinUI3Lib' 'RegularLib' '--' '/m:17' '/p:CL_MPcount=20' '/v:m' '/nologo'

**Determining projects to restore...
  Restored D:\TW\Builds\TWInt\Windows-x64\WinUI3Lib.vcxproj (in 417 ms).**
  Checking Build System
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(505,5): warning MSB8021: The value 'MultiByte' of the variable 'CharacterSet' is incompatible with the value 'true' of the variable 'WindowsAppContainer'. [D:\TW\Builds\TWInt\Windows-x64\WinUI3Lib.vcxproj]
  Building Custom Rule D:/TW/Workspace/CMakeLists.txt
  cmake_pch.cxx
  TWWinUI3App.cpp
  WinUI3Lib.vcxproj -> D:\TW\Builds\TWLib\Windows-x64\Debug\WinUI3Lib.lib
  C:\Users\mohsin.siddiqui\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\native\.. \.. \runtimes\win10-x64\native\Microsoft.WindowsAppRuntime.Bootstrap.dll
  1 File(s) copied

Building Custom Rule D:/TW/Workspace/CMakeLists.txt
  TWWinUIApp.cpp
  RegularLib.vcxproj -> D:\TW\Builds\TWLib\Windows-x64\Debug\RegularLib.lib
========= Build Successful =========

```

But when I compile these targets parallelly WinUI3Lib fails. I found that it did not Restore WinUI3Lib as it did when I compiled sequentially. 

```
D:\TW\Workspace>cmake -DTW_BUILD_TYPE=Build -DTW_BUILD_PRESET=Windows-x64-Debug -DBUILD_PARALLEL**=ON** -P D:\TW\Workspace\TWBuild.cmake -- WinUI3Lib RegularLib
TW_BUILD_TARGETS WinUI3Lib; RegularLib
projects RegularLib.vcxproj; WinUI3Lib.vcxproj
'C:/Program' 'Files/Microsoft' 'Visual' 'Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/.. /.. /.. /.. /.. /.. /.. /MSBuild/Current/Bin/amd64/MSBuild.exe' '/m:17' '/p:Configuration=Debug' '/p:CL_MPcount=20' '/v:m' '/nologo' 'targets.vcxproj'

Checking Build System
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(505,5): warning MSB8021: The value 'MultiByte' of the variable 'CharacterSet' is incompatible with the value 'true' of the variable 'WindowsAppContainer'. [D:\TW\Builds\TWInt\Windows-x64\WinUI3Lib.vcxproj]
  Building Custom Rule D:/TW/Workspace/CMakeLists.txt
  Building Custom Rule D:/TW/Workspace/CMakeLists.txt
  TWWinUIApp.cpp
  cmake_pch.cxx
  RegularLib.vcxproj -> D:\TW\Builds\TWLib\Windows-x64\Debug\RegularLib.lib
D:/TW/Workspace/TWWinUI3Includes.hpp(7,10): fatal  error C1083: Cannot open include file: 'winrt/Microsoft.UI.Xaml.Controls.h': No such file or directory [D:\TW\Builds\TWInt\Windows-x64\WinUI3Lib.vcxproj]
CMake Error at TWBuild.cmake:86 (message):
  ========= Build Failed =========

D:\TW\Workspace>
```

winrt/Microsoft.UI.Xaml.Controls.h should be generated under WinUI3Lib's build directory. What I believe is that in case of running in parallel build, MSbuild task which generated these projection files in Generated Folder is not getting executed and I dont know why ?

Since if I pass multiple target to msbuild, they do not get compiled parallelly, we have followed below MS document to make them build as MSBuild task.

https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-task?view=vs-2022

I will attach sample project which can be used to reproduce this issue.

So at large we have below issue.
If I compile WinUI3 library along with any other library parallel, it does not work.

[Workspace.zip](https://aka.ms/dc/file?name=B43a703720f2644bd99fdbc0f7cdd1ecb638231163439689130_Workspace.zip&tid=43a703720f2644bd99fdbc0f7cdd1ecb638231163439689130)

---
#### Feedback Bot on 6/25/2023, 00:00 AM: 

(private comment, text removed)
#### Shelley Zhang [MSFT] on 6/25/2023, 03:19 AM: 

(private comment, text removed)
#### Mohammad Siddiqui on 6/25/2023, 03:43 AM: 

(private comment, text removed)
#### Mohammad Siddiqui on 6/26/2023, 09:57 AM: 

(private comment, text removed)
#### Shelley Zhang [MSFT] on 6/26/2023, 03:21 AM: 

(private comment, text removed)
#### Shelley Zhang [MSFT] on 6/26/2023, 07:02 PM: 

(private comment, text removed)
#### Shelley Zhang [MSFT] on 6/27/2023, 06:21 PM: 

(private comment, text removed)
#### Feedback Bot on 6/27/2023, 06:33 PM: 

(private comment, text removed)
#### Feedback Bot on 6/28/2023, 09:06 AM: 

(private comment, text removed)

---
#### Shelley Zhang [MSFT] solved on 6/26/2023, 10:46 PM, 0 votes: 

<p>It should be a WinUI 3 issue. Please file a GitHub issue at WinUI 3 GitHub repo: <a target='_blank' href="https://github.com/microsoft/microsoft-ui-xaml">https://github.com/microsoft/microsoft-ui-xaml</a>.</p>

#### Mohammad Siddiqui on 6/27/2023, 00:19 AM: 

(private comment, text removed)

**Comment by mohsin-52715** [comment]
This issue needs some urgent workaround/fix as its causing few other build issues.

**Comment by Scottj1s** [comment]
@mohsin-52715 Unfortunately, WinAppSDK does not support CMake so we can't investigate further.
