### ISSUE TITLE
App freezes sometimes when create new window

### ISSUE THREAD

**Issue by khoabui1412** [microsoft/microsoft-ui-xaml#8591]
### Describe the bug

Sometimes, when create new window, the new window is totally empty without titlebar and app is frozen
<img width="473" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/65955727/7d56c385-4a20-4769-8e97-57fe8157035d">

I cannot interact directly in the UI anymore, but when I close the window by click "x" button in menu-bar, it can jump into my break point in close function (don't understand because if app is frozen, UI thread should not be occupied anymore?).

Call Stack when I break all while app is freezing (I used c#):

<img width="935" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/65955727/995778b5-a34b-4acb-b439-ac853a7c87bf">

### Steps to reproduce the bug

Sometimes happened when create new windows

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 11 (22H2): Build 22621

**Comment by JesseCol** [comment]
It looks like InProcessClient64.dll might be part of a product called "SentinelOne", do you have that installed?  It looks like it causes problems with some applications, for example: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/InProcessClient64-dll-is-blocking-your-Autodesk-product-s-from-launching.html

If you are using SentinelOne, does this issue still happen when you disable it?

**Comment by JesseCol** [comment]
Closing for now, please reply if this is still an issue for you.
