### ISSUE TITLE
Inconsistent/Weird hover behavior with ListViewItemPresenter

### ISSUE THREAD

**Issue by blendermf** [microsoft/microsoft-ui-xaml#8597]
### Describe the bug

There are 2 inconsistencies I'm seeing.

1. When CanDragItems and/or CanReorderItems is set to True for the ListView, and you release a click (and presumably any sort of pointer tap event) while still hovering, the hover styling dissapears. This is more noticable when SelectionMode is set to Multiple, and you deselect an item by clicking on it.
2. Seemingly regardless of any settings on the ListView, releasing a click on a child Button(presumably other controls with pointer tap behaviours) while still hovering also incorrectly removes the hover style

### Steps to reproduce the bug

1. Create a ListView with CanDragItems and/or CanReorderItems and SelectionMode="Multiple" to make this more obvious eg.
```xml
    <ListView x:Name="TestListView" CanDragItems="True" CanReorderItems="True" SelectionMode="Multiple" >
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="local:TestData">
                <Grid >
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*" />
                        <ColumnDefinition Width="Auto" />
                    </Grid.ColumnDefinitions>
                    <TextBlock Text="{x:Bind Name}" Grid.Column="0"/>
                    <Button Content="Test" Grid.Column="1"></Button>
                </Grid>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
```
2. Populate it with data
```C#
    public struct TestData
    {
        public string Name;

        public TestData(string name)
        {
            this.Name = name;
        }
    }
    /// <summary>
    /// An empty window that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainWindow : Window
    {
        public ObservableCollection<TestData> TestDataCollection { get; set; } = new () {
            new ( "Test 1" ),
            new ( "Test 2" ),
            new ( "Test 3" ),
        };

        public MainWindow()
        {
            this.InitializeComponent();

            this.TestListView.ItemsSource = this.TestDataCollection;
        }
    }
```
3. Run the app
4. Depending on which inconsistency:
    a) First Inconsistency: Click on an item to select it (technically the bug happens here also, but is more noticable on the next step) and then click again to deselect it, while not moving the cursor
    b) And the second: Click the button in the list view item while not moving the cursor

### Expected behavior

The ListViewItemPresenter should keep it's hover styling (instead it reverts to nothing)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 11 (22H2): Build 22621

**Comment by zhuxb711** [comment]
Duplicated with https://github.com/microsoft/microsoft-ui-xaml/issues/3191. It's a bug of ListView

**Comment by blendermf** [comment]
So this issue still exists. It's marked as a duplicate of #3139, which itself is listed as a duplicate of #3458 which is closed as fixed. However, the issue as described in this post still exists. The first inconsistency only happens if the item is deselected by the click now (not sure if that was always true), but the second one is exactly the same
