### ISSUE TITLE
Cannot find a Resource with the Name/Key TreeViewItemMinHeight

### ISSUE THREAD

**Issue by FrancoisM** [microsoft/microsoft-ui-xaml#861]
**Describe the bug**
A user of my app has the following error:

> Cannot find a Resource with the Name/Key TreeViewItemMinHeight

**Steps to reproduce the bug**
Unfortunaltely, I couldn't reproduce it.

**Expected behavior**
No error.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by FrancoisM** [comment]
My user updated his Windows to 1903 and the error went away.
Yet I don't understand as I thought that by using the nuget package we were independent of Windows 10 versions?

**Comment by jevansaks** [comment]
Yes, it should be the case that WinUI insulates you from the version of the OS you're running on, especially for things like this. If you weren't able to repro it yourself running on 17134 (1803) and it corrected itself for the user once they upgrade to 18362 (1903) then I suspect this might be related to a AppX installation bug that the AppX team is tracking down.

**Comment by FrancoisM** [comment]
I was myself already on 1809. This is the user who was on 1803 and who upgraded directly to 1903 after I sent him a link to do so.

**Comment by jevansaks** [comment]
Thanks. I could set up an 1803 VM if you want me to try your app out and debug it if it's crashing. Is your app in the store? If it's not something you want to share openly, you can email me (my email is on my github profile) or DM me on twitter [@JevanSaks](https://twitter.com/jevansaks).

**Comment by FrancoisM** [comment]
Thank you @jevansaks. The app cannot be shared as it belongs to my client and is privately distributed.
However, I have that [repo ](https://github.com/FrancoisM/ReproTreeView)that I created for another `TreeView` issue. It should crash the app with 1803 as well.
(Btw since yesterday another user whose Windows is also on 1803 experienced the crashes as well).

**Comment by jevansaks** [comment]
Thanks for sharing that. I'm out next week but @kaiguo is taking a look at a bunch of TreeView issues so I'm going to ask him to take a look when he has time.

**Comment by kaiguo** [comment]
@FrancoisM your repro app is using data binding, unfortunately TreeView databing only works on 1809+ (including 1809) for now.

TreeView takes dependency on ListView, and ListView is not part of WinUI library at this moment, which means TreeView behavior is not fully insulated from OS changes. Once we ship WinUI 3, ListView and all the other dependencies will be fully decoupled from OS, then the feature will be backward compatible to 15063 (1703).
