### ISSUE TITLE
After open systembackdrop in menuflyout(Default),menuflyout background show transparent casually

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#8618]
### Describe the bug

After open systembackdrop in menuflyout(Default),menuflyout background show transparent casually.

![74936e45677cb6e6c4aeae498573c40c](https://github.com/microsoft/WindowsAppSDK/assets/49179966/f6aaabd3-76d9-4516-921f-9ae540dbd4f9)

### Steps to reproduce the bug

No special steps, just display a normal menuflyout control

### Expected behavior

After open systembackdrop in menuflyout(default settings)，the menuflyout background with systembackdrop should not be transparent.

### Screenshots

![74936e45677cb6e6c4aeae498573c40c](https://github.com/microsoft/WindowsAppSDK/assets/49179966/938cbd6a-b023-414e-9431-8c510a3e04c7)

### NuGet package version

Windows App SDK 1.4 Experimental 1: 1.4.230518007-experimental1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Nuget package version is not in 1.4 experimental 1(1.4.230518007-experimental 1),but in new version 1.4 preview 1(1.4.230628000-preview1)

### Steps to reproduce the bug

No special steps, just display a normal menuflyout control

### Expected behavior

After open systembackdrop in menuflyout(default settings)，the menuflyout background with systembackdrop should not be transparent.

### NuGet package version

WinUI 3 - Windows App SDK 1.4 Experimental 1: 1.4.230518007-experimental1

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Nuget package version is not in 1.4 experimental 1(1.4.230518007-experimental 1),but in new version 1.4 preview 1(1.4.230628000-preview1)

**Comment by gegao18** [comment]
您好Gaoyifei1011,

Do you always see this behavior, or only sometimes? Do you have a repro app? Can you also attach a [dxdiag](https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85) with your system's display information on it?

Thanks,
George

**Comment by codendone** [comment]
This should be fixed in the [1.4.230822000](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.4.230822000) release, which had a couple fixes for transparent-menu issues.
