### ISSUE TITLE
Unable to build xaml island with prerelease version of WinUI2

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#8631]
### Describe the bug

I am unable to build my win32 application after adding WinUI 2.8+ prerelease version.

The [guide](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp) stated that:
>If you chose not to package the MyDesktopWin32App project, you must install the prerelease version of the [Microsoft.UI.Xaml](https://www.nuget.org/packages/Microsoft.UI.Xaml) NuGet package. Unpackaged desktop apps must use the prerelease version of this package.

### Steps to reproduce the bug

1. Follow the guide
2. Build error:
```
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(410,5): XamlCompiler error WMC0901: A type with a full name of 'Microsoft.UI.Xaml.Controls.IconSource' already exists in an included reference.
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(410,5): XamlCompiler error WMC0901: A type with a full name of 'Microsoft.UI.Xaml.Controls.TreeViewNode' already exists in an included reference.
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(410,5): XamlCompiler error WMC0901: A type with a full name of 'Windows.Foundation.Collections.IVector`1[[Microsoft.UI.Xaml.Controls.TreeViewNode, Microsoft.UI.Xaml, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime]]' already exists in an included reference.
1>Done building project "UWPCppProj.vcxproj" -- FAILED.
```

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Also tried using the release package, aka 2.8.5, it builds and run but got this exception.
```
Exception thrown at 0x00007FF99699536C in Gallery.exe: Microsoft C++ exception: winrt::hresult_class_not_registered at memory location 0x000000ED1713C558.
Exception thrown at 0x00007FF99699536C in Gallery.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
'Gallery.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Symbols loaded without source information.
'Gallery.exe' (Win32): Loaded 'C:\Windows\System32\BCP47Langs.dll'. Symbols loaded without source information.
Exception thrown at 0x00007FF99699536C (KernelBase.dll) in Gallery.exe: WinRT originate error - 0x802B000A : 'Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources' [Line: 8 Position: 32]'.
'Gallery.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. Symbols loaded without source information.
Unhandled exception at 0x00007FF9797C9BB0 (Windows.UI.Xaml.dll) in Gallery.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0000029F98E7ABB0, 0x0000000000000002).


```
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/62a1ec6d-65ad-46c5-85da-5102e231a134)

**Comment by DarranRowe** [comment]
As a little suggestion. For the release version, look into the Dynamic Dependencies API or Registration Free WinRT.

**Comment by HO-COOH** [comment]
@DarranRowe Adding this
```
        <activatableClass
            name="Microsoft.UI.Xaml.Controls.XamlControlsResources"
            threadingModel="STA"
            xmlns="urn:schemas-microsoft-com:winrt.v1" />
```
to `app.manifest` does not help with the release version's case.

**Comment by HO-COOH** [comment]
@DarranRowe Thanks for that detail. But if you see my OP, I am getting `winrt::hresult_class_not_registered` exception, instead of your `resource not found`. Can you please share your project?

**Comment by DarranRowe** [comment]
Sure.

[quicktest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12033123/quicktest.zip)

This is just a simple console application that goes as far as instantiating a XamlControlsResources instance and adding it to the application's merged resources.

It is extremely important that you do one more step after you build the project. Registration free WinRT requires that Microsoft.UI.Xaml.dll must be found in the same directory as the executable. So you must copy files out of the WinUI 2 appx file. The appx packages for each supported platform can be found as part of the Nuget package.

![Screenshot 2023-07-12 230607](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/bc200803-62dc-4a85-8271-c491b4ca5ba8)

This is an example of where you can find the packages. 

![Screenshot 2023-07-12 231004](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/77d0bb1b-de30-435b-9cf8-4a13d7fda19d)

This is how the directory should look.

**Comment by Scottj1s** [comment]
@HO-COOH I suspect you haven't installed the WinUI 2* framework package, which is a required manual step for pre-releases (release builds publish the framework package to the store).  That said, we are no longer supporting WinUI 2, so closing this issue.
