### ISSUE TITLE
`ListView` does not apply DataContext to items correctly

### ISSUE THREAD

**Issue by Fortelle** [microsoft/microsoft-ui-xaml#8643]
### Describe the bug

In a `ListView`, only the initial visible items obtain `DataContext`.

### Steps to reproduce the bug

1. In `MainPage.xaml`
```
<ListView ItemsSource="{x:Bind Entries}" >
    <ItemsControl.ItemTemplate>
        <DataTemplate>
            <Grid >
                <Grid.ColumnDefinitions>
                    <ColumnDefinition />
                    <ColumnDefinition />
                </Grid.ColumnDefinitions>
                <TextBlock Text="{Binding Key, Mode=OneTime}" />
                <TextBlock Grid.Column="1" Loaded="TextBlock_Loaded" />
            </Grid>
        </DataTemplate>
    </ItemsControl.ItemTemplate>
</ListView>
```
2. In `MainPage.xaml.cs`
```
public class TestEntry
{
    public string Key { get; set; }
    public string Value { get; set; }
}

public TestEntry[] Entries { get; } = Enumerable.Range(0, 30)
    .Select((_, i) => new TestEntry { Key = $"Key {i}", Value = $"Value {i}" })
    .ToArray();

private void TextBlock_Loaded(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
{
    ((TextBlock)sender).Text = (((FrameworkElement)sender).DataContext as TestEntry)?.Value ?? "(null)";
}
```

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/38492315/675f3bae-1786-4aba-b5d6-34bae22b8dc2)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/38492315/9bbfe6b1-00f9-4b3e-b089-743c4cc1c753)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 10 (21H2): Build 19044

**Comment by ranjeshj** [comment]
Your binding says 'OneTime', try switching to OneWay instead. 
Also, the loaded/unloaded events on items in a ListView are unreliable since the items get reused. If you want to setup/clean up when items come and go out of the view, please use the ContainerContentChanging event instead. In this case I think OneWay should avoid the need for these events.
