### ISSUE TITLE
ListView creates two containers for one item

### ISSUE THREAD

**Issue by ynborokh** [microsoft/microsoft-ui-xaml#8651]
### Describe the bug

There are scenarios when `ListView` creates two containers for one item, which can lead to some hard-to-spot bugs.

### Steps to reproduce the bug

1. Load the solution from [this repo](https://github.com/ynborokh/containerBug).
2. Start the application.
3. Scroll down to the end of the list. We need to do it to make sure that the items from the beginning of the list don't have containers due to the virtualization mechanism of `ListView` because once we are at the end of the list, the beginning of the list is far enough to be beyond the range of the items with containers.
4. Press the `Add item` button. After the button is pressed, a new item is added to the beginning of the list. `PrepareContainerForItemOverride` is called in CustomListView - so we create a container for a newly added item. This happens only if we add a new item to the beginning of the list. If we were at the beginning of the list and we were adding a new item to the end of the list, `PrepareContainerForItemOverride` wouldn't be called and the bug cannot be reproduced.
5. Now scroll back to the beginning of the list. At some moment, `PrepareContainerForItemOverride` will be called again for one of the items that already have containers. Usually, it happens for a newly created item from p.4, but not always. And in this moment we have two containers created for a single item. It can lead to some hard-to-spot bugs. I won't describe the precise scenarios here, because I think that the core problem is that we cannot have two containers for a single item, so the details don't matter. To fix the problem, I have the following implementation of `CustomListView`:
```
internal class CustomListView : ListView
{
    private Dictionary<string, ListViewItem> _items = new();

    protected override void PrepareContainerForItemOverride(DependencyObject element, object item)
    {
        base.PrepareContainerForItemOverride(element, item);

        if (_items.ContainsKey((string)item))
        {
            ItemsPanelRoot.Children.Remove(_items[(string)item]); // remove redundant container
        }

        _items[(string)item] = (ListViewItem)element;
    }

    protected override void ClearContainerForItemOverride(DependencyObject element, object item)
    {
        _items.Remove((string)item);

        base.ClearContainerForItemOverride(element, item);
    }
}
```
The mechanism of this workaround is the following: on each `PrepareContainerForItemOverride` call I put the container along with its item into a dictionary, and on each `ClearContainerForItemOverride` I remove them from this dictionary. If during `PrepareContainerForItemOverride` execution I see that I already have a container for some item, I remove it directly from the items panel. It works and eliminates the bugs, but it's a workaround I would like not to use.

### Expected behavior

I would like to have a clear behaviour: for each item, we have only one container, and, before a new container for an item is created, the old one should be destroyed and for each `PrepareContainerForItemOverride` we should have `ClearContainerForItemOverride`.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Additional context

My OS version is Windows 10 22H2 19045.3208.
I can reproduce the bug also on Windows App SDK version 1.4.230628000-preview1.

**Comment by ranjeshj** [comment]
@ynborokh I'm not entirely sure what you are trying to achieve. Can you explain your scenario a bit? ListView does several optimizations with its containers to reduce the amount of work done especially when panning since it is a perf sensitive scenario. That might mean delaying calling of ClearContainer until absolutely needed. We also try to reuse containers as much as possible since allocations are expensive. These optimizations might be responsible for the behaviors you are seeing. 

If you need a way to setup/teardown when items are created/recycled, ContainerContentChanging event is something to look into. You don't need to derive from ListView and override the Prepare/Clear containers for that.
