### ISSUE TITLE
Text wrapping does not work with textblock control inside a WinUI Breadcrumb 

### ISSUE THREAD

**Issue by nepomucenobr** [microsoft/microsoft-ui-xaml#8653]
### Describe the bug

If you add a TextBlock component inside a breadcrumb, TextWrapping does not work as it would with a standalone TextBlock. Here is an example:

XAML
```<muxc:BreadcrumbBar x:Name="MyBreadcrumb">
	<muxc:BreadcrumbBar.ItemTemplate>
		<DataTemplate x:DataType="local:Folder">
			<muxc:BreadcrumbBarItem AutomationProperties.Name="{Binding Name}" Content="{Binding}">
				<muxc:BreadcrumbBarItem.ContentTemplate>
					<DataTemplate>
						<TextBlock Text="{Binding Name}" TextWrapping="Wrap" />
					</DataTemplate>
				</muxc:BreadcrumbBarItem.ContentTemplate>
			</muxc:BreadcrumbBarItem>
		</DataTemplate>
	</muxc:BreadcrumbBar.ItemTemplate>
</muxc:BreadcrumbBar>

<TextBlock
	Grid.Row="1"
	Margin="0,20,0,0"
	Text="A superbly helluvafsahlhadsfkhasdlfhsllongnameforafolderdeargoodnessgraciousohmygoshes"
	TextWrapping="Wrap" />
```

CS
```
public sealed partial class MainPage : Page
{
	public MainPage()
	{
		this.InitializeComponent();

		MyBreadcrumb.ItemsSource = new List<Folder>
		{
			new Folder { Name = "Home"},
			new Folder { Name = "Folder1" },
			new Folder { Name = "Folder2" },
			new Folder { Name = "Folder3" },
			new Folder { Name = "Folder4" },
			new Folder { Name = "Folder5 - 123e4567-e89b-12d3-a456-426614174000" },
			new Folder { Name = "A superbly helluvafsahlhadsfkhasdlfhsllongnameforafolderdeargoodnessgraciousohmygoshes" }
		};
	}
}

public class Folder
{
	public string Name { get; set; }
}
```

**Microsoft.UI.XAML nuget package version**: 2.8.5 (this can also be observed in the  2.7 version)
**Microsoft.NETCore.UniversalWindowsPlatform nuget package version**: 6.2.14
**Target Windows version**: Windows 11 (10.0; Build 22000)

### Steps to reproduce the bug

1. Add a breadcrumb control to the page
2. Change the DataTemplate by adding a TextBlock with TextWrapping
3. When setting the ItemsSource, add a folder with a very large number of characters

### Expected behavior

TextWrapping should be respected. Please look at the screenshot on how it works fine when the textblock is outside the breadcrumb, but not when it's inside.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/3769981/6e7a3781-27b9-439a-943e-cea04ea4a6ea)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (21H2): Build 22000

**Comment by Jay-o-Way** [comment]
The whole point of a BreadCrumb is that it's all on one line. You might consider trimming, but wrapping is a non-issue.

**Comment by ranjeshj** [comment]
@nepomucenobr This is by design.
