### ISSUE TITLE
Resizable pointer shows up even when a window is maximized

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#8665]
### Describe the bug

The pointer will change from default to the one indicating the window is resizable even when the window is maximized.

### Steps to reproduce the bug

1. Create a WinUI 3 project;
2. Set ExtendsContentIntoTitleBar to true;
3. Build and run the app;
4. Maximize it and hover over the upper edge.

### NuGet package version

Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022-preview

**Comment by jeremy-visionaid** [comment]
Oh yup, I'm seeing this one too

**Comment by Arko109** [comment]
Same issue on Windows 10 19045.3930

**Comment by codendone** [comment]
Switching this to fixed-internally rather than duplicate.

**Comment by codendone** [comment]
The fix will be serviced to 1.5.

**Comment by codendone** [comment]
The fix is now in [Version 1.5.4 (1.5.240607001)](https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-154-15240607001).
