### ISSUE TITLE
After expanding the title bar, you can also adjust the window size to maximize the top position of the window

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#8667]
### Describe the bug

In windows app sdk 1.4 preview 1, you can also adjust the window size when extending the title bar to maximize the top position of the window

### Steps to reproduce the bug

1.Click the Window Maximizer button
2.Move the mouse to the top of the window
3.Drag the window to modify the window size

### Expected behavior

When expanding the title bar and maximizing the window, mouse over the top of the window should not be able to resize the window

### Screenshots

![7a47047652ee1bafca475cc90380376d](https://github.com/microsoft/WindowsAppSDK/assets/49179966/3bc4608b-856d-4ab8-bd38-ac47e3fcdac2)

### NuGet package version

Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by eduardobragaxz** [comment]
It seems so, although they're saying they can resize the window, but I can't reproduce that.

**Comment by codendone** [comment]
This was resolved as duplicate of an issue fixed in 1.5.4.
