### ISSUE TITLE
Window subclassing results in System.ExecutionEngineException at random times

### ISSUE THREAD

**Issue by eFail** [microsoft/microsoft-ui-xaml#8669]
### Describe the bug

While we're waiting for APIs related to windowing functionality to come online for WinUI, it's my understanding that window subclassing is the current officially recommended solution for accomplishing certain tasks.  One example where this is needed is to handle `WM_GETMINMAXINFO`, so that a window can be given a maximum size.

Maybe I'm doing something wrong, but it seems to be the case that as soon as a WinUI window gets subclassed, this results in a `System.ExecutionEngineException` exception being thrown some time later if you resize or move the window.

### Steps to reproduce the bug

1. In Visual Studio, create a new WinUI `Blank App, Packaged`.
2. Replace the generated `MainWindow` class with the code below.  Observe that this code subclasses the window, but doesn't do anything special yet.  It passes all messages back to `DefSubclassProc()`.
3. Run the app.
4. Do a mixture of the following:
    - Grab the corner of the window and then quickly expand and collapse the size of the window several times, with quick speed.  Go really big and all the way down to 0x0 while doing this.  Keep doing it for a good 15s or so.
    - Drag the window around on screen.  Move it between two monitors with different DPI/resolution.
    - Leave the window open, but now go off and do some other work for a while.

### Expected behavior
At no point does anything go wrong.

### Actual behavior
At some point after doing step 4, the application will encounter a `System.ExecutionEngineException` exception.  It's not 100% consistent, but it does happen.  You may have to terminate and then restart the app a few times before you get it to happen.  I can't figure out what specific thing causes it, but it certainly seems to be related to resizing the window.  The exception also doesn't include any information that tells me what went wrong (see screenshot).

Is there something wrong with my P/Invoke code, or is there a real issue here somewhere in WinUI?  I have verified with 100% certainty that this starts happening as soon as `SetWindowSubclass()` is used to insert `WndProc()`.

```csharp
    public sealed partial class MainWindow : Window
    {
        #region P/Invoke
        [DllImport("Comctl32.dll", SetLastError=true)]
        public static extern bool SetWindowSubclass(IntPtr hwnd, SUBCLASSPROC subclassProc, uint subclassID, uint referenceData);

        [DllImport("Comctl32.dll", SetLastError=true)]
        public static extern int DefSubclassProc(IntPtr hwnd, uint msg, IntPtr wParam, IntPtr lParam);
        
        public delegate int SUBCLASSPROC(IntPtr hwnd, uint msg, IntPtr wParam, IntPtr lParam, UIntPtr subclassID, IntPtr referenceData);
        #endregion
        
        public MainWindow()
        {
            this.InitializeComponent();

            SetWindowSubclass(WindowNative.GetWindowHandle(this), new SUBCLASSPROC(WndProc), 0, 0);
        }

        void myButton_Click(object sender, RoutedEventArgs e)
        {
            myButton.Content = "Clicked";
        }

        static int WndProc(IntPtr hwnd, uint msg, IntPtr wParam, IntPtr lParam, UIntPtr subclassID, IntPtr referenceData)
        {
            return DefSubclassProc(hwnd, msg, wParam, lParam);
        }
    }
```

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/1672416/2ce8c444-e977-499e-8b8e-3e4957fd13b2)

### Additional context
**WinUI:** v1.3.230502000
**Windows:** 22H2

**Comment by DHancock** [comment]
I would recommend using [CsWin32](https://www.nuget.org/packages/Microsoft.Windows.CsWin32/0.3.18-beta) for your PInvoke definitions. It removes most of the problems that can easily happen with rolling your own. One thing that stands out in your code is that you aren't keeping a reference to the new subclass delegate. It may go stale which will cause a crash. If you change the contructor to:
````c#

 private readonly SUBCLASSPROC subClassDelegate;

 public MainWindow()
 {
     this.InitializeComponent();
     subClassDelegate = new SUBCLASSPROC(WndProc);
     SetWindowSubclass(WindowNative.GetWindowHandle(this), subClassDelegate, 0, 0);
 }
 ````

**Comment by eFail** [comment]
@DHancock I'll post an update here if it turns out I'm speaking too soon, but I think you solved the problem.  I'm keeping a reference to the delegate now and the exception seems to have gone away.  Thanks for your help!

**Comment by riverar** [comment]
@eFail Are you still hitting this? I am.
