### ISSUE TITLE
WebView2 control loses pointer capture when when moving mouse outside of the control

### ISSUE THREAD

**Issue by ghord** [microsoft/microsoft-ui-xaml#8677]
### Describe the bug

I'm hosting a monaco editor in WebView2 control, and I have focus issue that I think is a bug.

I've added following javascript at the startup to illustrate the issue:

```javascript
window.addEventListener("gotpointercapture", event => {
    console.log("gotpointercapture");
});

window.addEventListener("lostpointercapture", event => {
    console.log("lostpointercapture");
});

window.addEventListener("mousemove", event => {
    console.log("mousemove");
});
```

As you can see in the gif, lostpointercapture event fires straight away when you move the mouse outside of WebView2.

![dif](https://github.com/microsoft/WindowsAppSDK/assets/10825459/a83f5ffd-65fe-4f96-a65d-706b821e2107)

This makes small input controls hosted using WebView practically unusable, as both scrolling and text selection break once you move at least 1 pixel outside of webview.

### Steps to reproduce the bug

1. Host any html content in WebView2
2. Hook up gotpointercapture/lostpointercapture event
3. Capture pointer in javascript on mouse down
4. Move pointer outside of the host WebView2, while holding down mouse button.
5. Pointer capture gets released. Moreover, mousemove events do not seem to be sent to the content.

### Expected behavior

Focus does not get lost and hosted window gets onmousemove messages correctly until user releases mouse button.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This issue does not occur in WPF implementation of WebView2 control, so this is WinUI3 specific.

I've seen some code in backported WinUI2 code here that claims to work around this specific issue:

https://github.com/microsoft/microsoft-ui-xaml/blob/3b77866fbdb2f2eda3fc24a6c92568439b700540/dev/WebView2/WebView2.cpp#L186-L198C21

```c#
    if (deviceType == winrt::PointerDeviceType::Mouse)
    {
        // WebView takes mouse capture to avoid missing pointer released events that occur outside of the element that
        // end pointer pressed state inside the webview. Example, scrollbar is being used and mouse is moved out
        // of webview bounds before being released, the webview will miss the released event and upon reentry into
        // the webview, the mouse will still cause the scrollbar to move as if selected.
        m_hasMouseCapture = this->CapturePointer(args.Pointer());

```

I don't think this works in WinUI3.

I would be very grateful to at least get a workaround for this issue.

**Comment by ghord** [comment]
The same issue can be reproduced with WinUI3 Controls gallery easily:

![dif2](https://github.com/microsoft/microsoft-ui-xaml/assets/10825459/1f305d57-f7a1-476e-a4cd-62ef84655920)

As you can see, once you drag the mouse outside of the WebView2, selection is no longer being updated.

**Comment by Fydar** [comment]
Just bumping this issue and sharing the GIFs I produced demonstrating this issue.

<p align="center">
  <img src ="https://raw.githubusercontent.com/Fydar/MauiCapturePointerIssue/main/docs/expected-behaviour-in-wpf.gif" alt="Expected Behaviour">
  <br/>
  <sub><b>Figure 1</b>: <i>Expected behaviour demonstrated using Microsoft Edge.</i></sub>
</p>


<p align="center">
  <img src ="https://raw.githubusercontent.com/Fydar/MauiCapturePointerIssue/main/docs/actual-behaviour-in-maui.gif" alt="Actual Behaviour">
  <br/>
  <sub><b>Figure 2</b>: <i>Actual behaviour demonstrated in a MAUI Blazor Hybrid application.</i></sub>
</p>

**Comment by ghord** [comment]
Just to anyone curious, 1.5.4 changes:

> Fixed an issue where WebView2 sent extra blur and focus events on every click. For more info, see GitHub issue [#9288](https://github.com/microsoft/microsoft-ui-xaml/issues/9288). This also fixes problems with dropdowns not responding, as seen in GitHub issue [#9566](https://github.com/microsoft/microsoft-ui-xaml/issues/9566).

Do not fix this issue. Mouse capture is still lost when you drag outside the WebView2 control no matter what.

**Comment by Thomr77** [comment]
Hi everyone,

Is it possible that this could get attention as it really makes scrolling a Maui Blazor website very hard for the user - especially with larger vertical content?

We had a look at implementing the above workaround, but the WebView2 PointerMoved event is not called - the same goes for PointerGestureRecognizer PointerMoved.

A solution would be very greatly appreciated for Maui Blazor!

**Comment by Fydar** [comment]
Would be a wonderful Christmas present to have this fixed 🥺🎄

I love .NET Blazor Hybrid, apart from the lack of cursor graphic support and the pointer capture issues 🥲

**Comment by Thomr77** [comment]
Hi @codendone - that is truly awesome - thank you!! 😁
