### ISSUE TITLE
TeachingTip does not show if it isn't parented in the tree

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#868]
**Describe the bug**

`TeachingTip` do not show when creating in .cs code.

**Steps to reproduce the bug**

`<Button x:Name="SaveButton" Content="Save" Tapped="Button_Tapped"/>`

```
        private void Button_Tapped(object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
        {
            MUXC.TeachingTip tip = new MUXC.TeachingTip();
            tip.Title = "Error";
            tip.Subtitle = "It seems you are not connected to the Internet :(";
            tip.CloseButtonContent = "OK";
            tip.IsLightDismissEnabled = true;
            tip.IsOpen = true;
        }
```

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |  Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment]
@hupo376787 does this issue still happen if you keep a reference to the TeachingTip in your code-behind? It's possible that the TeachingTip gets garbage-collected by .NET before it can be shown.

**Comment by hupo376787** [comment]
Yes, still happen. Here is a small repo: [TeachingTipBug](https://github.com/hupo376787/TeachingTipBug.git).

It seems that they just block the crash bug. But still not showing tip.

**Comment by jevansaks** [comment]
Thank you for the repro app, I'll debug it!

**Comment by jevansaks** [comment]
Ok, I spent some time debugging this. I don't know what the fix would be in the control yet, but the problem is that the TeachingTip isn't able to apply its default template for some reason. 

As a workaround, if you add the TeachingTip to the page's resources, then it's able to find its style correctly.

Code-behind:
```c#
            var tip = new MUXC.TeachingTip();
            this.Resources["tip"] = tip; // Add to resources due to issue microsoft/microsoft-ui-xaml#868
            tip.Title = "Error";
            tip.Subtitle = "It seems you are not connected to the Internet :(";
            tip.CloseButtonContent = "OK";
            tip.IsLightDismissEnabled = true;
            tip.IsOpen = true;
```

We'll keep this issue open to figure out a proper fix, but hopefully this workaround can unblock you.

**Comment by hupo376787** [comment]
Thanks, this workaround works.

**Comment by hupo376787** [comment]
Hey, guys. Any new progress on this issue?

**Comment by StephenLPeters** [comment]
Hello @hupo376787. We haven't yet had reason to prioritize fixing this. Is this issue causing your problems now? It is possible our prioritization is wrong.

**Comment by hupo376787** [comment]
Well, currently I wrote C# code to call a `TeachingTip`, I had to add extra code
`this.Resources["tip"] = tip;`
This means I can only use it in a page, not in a helper class.

I want to use it in a helper class, so any workaround?
Thx.

**Comment by mrlacey** [comment]
> I want to use it in a helper class, so any workaround?

Get the current view and attach the teaching tip to the first child?

**Comment by chingucoding** [comment]
Could we try to get the template of the TeachingTip inside the constructore and apply the default template that way?
