### ISSUE TITLE
Question: Will MDL2 Icons become rounded to match WinUI 3.0

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#869]
As the Windows design language evolves to adopt a more rounded and softer appearance, will this extend to the suite of MDL2 Icons that are used across platforms?

![image](https://user-images.githubusercontent.com/7389110/59449382-d79b4e80-8dfe-11e9-84fd-e3c7ed379b4f.png)

Not all of the icons would need changing, but some of them could be given a smoother appearance.

Whilst we are looking at the icons, will there be any effort into creating versions of the icons that are designed for a larger scale?  At the moment the majority of the MDL2 icons are optimised for a 16 x 16 px size (where the stroke thickness equates to 1 px at that size) - but the Office Icons are designed to also work at 12 x 12 px, and 24 x 24 px sizes.

Apple announced SF Symbols at WWDC.  They have finally followed Microsoft and Android in using font based icons for scaling - but they provide two scales for each icon (as well as icon weights to match their UI font weights).

Do MDL2 Icons need a 24 x 24 px scale for each glyph/icon?

![image](https://user-images.githubusercontent.com/7389110/59451282-03203800-8e03-11e9-82dc-1369702c899f.png)

**Comment by chigy** [comment]
@mdtauk , asking folks who owns this font.

**Comment by chigy** [comment]
@mdtauk , a contact in font team told me “We’re always exploring ways to align across our design system, but not ready to discuss specific design direction at this time.”

So, in short, there's nothing we can share to public today, but I'll be sure to share it back to the community once it becomes some information I am able to share.

That said, I encourage to point out things that might break visually if this is not updated in this proposal.

**Comment by Poopooracoocoo** [comment]
> a contact in font team told me “We’re always exploring ways to align across our design system, but not ready to discuss specific design direction at this time.”

oh my god the division at microsoft. it was so weird seeing people from the same company calling other people customers.

**Comment by chigy** [comment]
> > a contact in font team told me “We’re always exploring ways to align across our design system, but not ready to discuss specific design direction at this time.”
> 
> oh my god the division at microsoft. it was so weird seeing people from the same company calling other people customers.

@Poopooracoocoo , maybe you thought that response was sent to me and I quoted it? It is not. I know the contact very well. That said, I cannot share what they are working on even if I knew because that's not for me to decide as I am not part of that team. So I asked her to write a response I can quote back here.

To your comment, we do treat teams who use our technologies as "our customers" because they are indeed our platform customers. They provide us requirements, feedback, we provide them with products, we even tell them no we cannot do certain features just like we do to the community, etc. 

Our (internal) customers are asked to open GitHub issues and work just as they are external developers. So I'm not sure referring to who use our products "our customers" regardless internal or external is such a bad thing especially if you are an external developers? I wonder...?

**Comment by mdtauk** [comment]
With all the talk of breaking down the internal walls between various teams within Microsoft, I am sure that some people believe there are no more departments, or that small teams do not have "ownership" of certain technologies or features.

MDL2 Icons need to be the product of a single team, to ensure there is a consistent design the all those icons will match.
But each app has a subset of the icons that they use, so if Calculator needs a new icon in it's app, they would ask those in charge of the MDL2 Icons Font to design and include it in the "Full MDL2 Assets" font - which would then allow the Calculator devs to make an icon font containing only the Icons they need/use.

I believe the Office Team have their own set of Icons and Icon Fonts designed to a 12, 16, 24 px scale.  Xbox also have their own Icon Fonts.  But the icon styles all work to the same design spec.

----

The move to a more Rounded UI design, may or may not need a change to that base icon design spec, that the MDL2 Asset owners will have to change and implement.

I only asked if the changes had been considered, and explored.  It sounds like they have been, or are being considered - but nothing to announce yet.

**Comment by Poopooracoocoo** [comment]
By "it was so weird", I was referring to some OneNote case. I think it was in this very repo. This situation reminded me of it. It's just kinda weird to me as an outsider.

**Comment by chigy** [comment]
@Poopooracoocoo , I am not familiar with the OneNote case? Do you care to elaborate or are we good with leaving this with conclusion that @mdtauk nicely put?

>I only asked if the changes had been considered, and explored. It sounds like they have been, or are being considered - but nothing to announce yet.

**Comment by Poopooracoocoo** [comment]
This is what I find weird about rounding things. Will the Microsoft and Windows logos change too? The Office icons have rounded corners. as I've said before, the way Micrsoft's design insisted on sharp corners made something really unique and somehow consistent. And the fact that they don't want to bring Fluent to other controls is rather sad

**Comment by chigy** [comment]
@Poopooracoocoo , I posted earlier on but design teams are exploring ways to align design across the company. We cannot talk specific options they are exploring.

**Comment by mdtauk** [comment]
I know this was closed, but it appears that MDL2 Icons have been replaced with the open source Fluent Icons...

https://medium.com/microsoft-design/developing-an-open-source-icon-system-at-microsoft-b1796315df9f
