### ISSUE TITLE
WebP fails to load

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#8694]
### Describe the bug

Several customers reported that on their Windows 10 machine, `.webp` images frequently fails to load. Windows 11 does not seems reproducible.

This is reproducible on even WASDK 1.4 preview 1.

### Steps to reproduce the bug

1. Package a `.web` image in `Assets`
2. Use `Image` control to load it
```xml
<Image Source="ms-appx:///Assets/image.webp" Width="50" Height="50"/>
```

### NuGet package version

WinUI 3 - Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Windows version

Windows 10 2004: 19041

**Comment by DarranRowe** [comment]
Part of me is wondering if these machines don't have the Webp Image Extensions installed from the Microsoft Store.
While I would have to double check the Windows 10 image, the Webp Image Extension is bundled with Windows 11.

**Comment by HO-COOH** [comment]
Does not seems like to be the issue. I have a customer reported the extension is not installed but the image is shown.
![a6d244a0e540cd47a139718a56b1b625](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/725e3fbf-a7a6-4b5f-991c-b684fd7ccbc2)

And another Windows 10 that the extension is not even installable.

**Comment by castorix** [comment]
On my Windows 10 OS (22H2), it calls 
_IWICImagingFactory::CreateDecoderFromStream_ with _GUID_VendorMicrosoftBuiltIn_
which reads registry key _{7693E886-51C9-4070-8419-9F70738EC8FA}_ in _HKEY_LOCAL_MACHINE_
where I have _%SystemRoot%\system32\mswebp.dll_

**Comment by codendone** [comment]
Sharing comments from the internal bug:
> I still could not reproduce the issue. Since there are not more new reports, I'm resolving this as 'Not Repro'.
>
> If there are still customers reporting this issue, please ask the customer to try to view WebP in Photos app or MSPaint and confirm if the OS has WebP support.
