### ISSUE TITLE
[WinUI] ItemsSource="ABCD" or ItemsSource="1234" throwing XamlParseException

### ISSUE THREAD

**Issue by agneszitte** [microsoft/microsoft-ui-xaml#8696]
### Describe the bug

Using `ItemsSource="ABCD"` or `ItemsSource="1234"` for example as a quick `ItemsSource` during tests, throw a `XamlParseException` on WinUI. (As opposed to building fine on UWP)

```
Exception thrown: 'Microsoft.UI.Xaml.Markup.XamlParseException' in WinRT.Runtime.dll
WinRT information: Failed to assign to property 'Microsoft.UI.Xaml.Controls.ItemsControl.ItemsSource'. [Line: 16 Position: 17]
XAML parsing failed.
```

### Steps to reproduce the bug

Try this snippet of code in a WinUI app:

```
	<StackPanel>
		<ItemsControl ItemsSource="ABCDEFG" />
		<ComboBox ItemsSource="ABCDEFG" />
		<ItemsControl ItemsSource="123456" />
		<ComboBox ItemsSource="123456" />
		<ItemsControl ItemsSource="@#$%?!" />
		<ComboBox ItemsSource="@#$%?!" />
	</StackPanel>
```
- WinUI Sample App:  [TestComboBoxWinUIOnly.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12234668/TestComboBoxWinUIOnly.zip)
- UWP Sample App (to compare): [TestComboBoxUWPOnly.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12234667/TestComboBoxUWPOnly.zip)

### Expected behavior

There should be no `XamlParseException` like for UWP

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

I did not find a similar issue opened so I added this one. This is really useful to have on hand for quick tests.

**Comment by brabebhin** [comment]
As long as there's a readable error in the output this is actually fine - such a situation is obviously bogus and should be hunted down. One of the annoying parts of UWP was having to track down such weird XAML lines (usually typos) when things suddenly stopped working.

**Comment by JesseCol** [comment]
Thanks!  This is currently by-design.
