### ISSUE TITLE
Proposal: Add Chart Example on WinUI 3 Gallery

### ISSUE THREAD

**Issue by ghostidentity** [microsoft/microsoft-ui-xaml#8701]
I noticed that, WinUI 3 gallery example dont have chart example. So this proposal would want to make it happen.

Similar to SceneBuilder, there are multiple charts that can be selected. 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/4637625/3c85fd39-027a-4f66-98f7-8c03874d0924)

**Comment by castorix** [comment]
As workaround, OCX controls can be used (like the old _MSChart.ocx_)

**Comment by dotMorten** [comment]
WinUI3 doesn't have any chart controls though?

**Comment by ghostidentity** [comment]
Oh I got it, just wondering if they could make  it happen as its UI framework. Will close the proposal instead.
