### ISSUE TITLE
MediaPlayerElement freezes when playing mp4 urls that are more than 30 seconds

### ISSUE THREAD

**Issue by aborlaza-gpsw** [microsoft/microsoft-ui-xaml#8708]
### Describe the bug

MediaPlayer freezes when playing source that are mp4 URLs

```
<MediaPlayerElement x:Name="MediaPlayerElementControl"
            Margin="5,5,5,5"
            Height="500"
            Width="500"
            Source="http://localhost/videos/samplefile.MP4"
            AreTransportControlsEnabled="True"
            HorizontalAlignment="Stretch" VerticalAlignment="Stretch"/>
```

I will play, then buffer, then continue to play.
Then for some reason after ~5 seconds, the sound keeps playing but the image freezes.
Pausing and playing again will cause the player to speed up and display the skipped parts of the video.

### Steps to reproduce the bug

1. Create MediaPlayerElement control
2. Source should be a mp4 url that is longer than 30 seconds.
If not reproducable with 30 seconds, try a 1 min video
```
<MediaPlayerElement x:Name="MediaPlayerElementControl"
            Margin="5,5,5,5"
            Height="500"
            Width="500"
            Source="http://localhost/videos/samplefile.MP4"
            AreTransportControlsEnabled="True"
            HorizontalAlignment="Stretch" VerticalAlignment="Stretch"/>
```

### Expected behavior

Should not freeze and continue to play + stream url 

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by christosk92** [comment]
Could you register MediaFailed event for the underlying mediaplayer and see if it raises an error. 
I'm experiencing a very similar with OGG files (https://github.com/microsoft/WindowsAppSDK/issues/3305#issuecomment-1649911929)

**Comment by ranjeshj** [comment]
@aborlaza-gpsw closing as dup of https://github.com/microsoft/WindowsAppSDK/issues/3305 . If it is not the same issue, please report back.

**Comment by aborlaza-gpsw** [comment]
This is NOT THE SAME ISSUE! This is just playing a simple URL (not live stream lnk

**Comment by aborlaza-gpsw** [comment]
> Could you register MediaFailed event for the underlying mediaplayer and see if it raises an error. I'm experiencing a very similar issue with OGG files ([microsoft/WindowsAppSDK#3305 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/3305#issuecomment-1649911929))

It does not throw any MediaFailed events. The playback just lags.
Then for some reason after ~5 seconds, the sound keeps playing but the image freezes.
Pausing and playing again will cause the player to speed up and display the skipped parts of the video.
