### ISSUE TITLE
Infinite spinning wheel cursor after app startup

### ISSUE THREAD

**Issue by VistaSunset** [microsoft/microsoft-ui-xaml#8717]
### Describe the bug

When executing a WinUI 3 project, if the cursor sits still before and after the app window has spawned (keeping the cursor unmoved on the newly spawned window), the cursor will change to an infinite spinning wheel during construction. The spinning wheel will only go away after moving the cursor, whereas it should be reverting to a default cursor after the window has finished constructing.

### Steps to reproduce the bug

1. Create a new blank WinUI 3 app project.
2. Build the project, then close the debug app window once it has spawned.
3. Start the project from the Start menu and make sure that the cursor sits still where the window will spawn. After the window has spawned, the cursor will switch to an infinite spinning wheel that doesn't change until the mouse moves.

### Expected behavior

The cursor should remain as a default cursor, at least after the app has finished spawning.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by VistaSunset** [comment]
Related to [microsoft/WinUI-Gallery/issues/1012](https://github.com/microsoft/WinUI-Gallery/issues/1012) and [microsoft/microsoft-ui-xaml/issues/8689](https://github.com/microsoft/microsoft-ui-xaml/issues/8689).

**Comment by codendone** [comment]
Closing as dup of #8689.
