### ISSUE TITLE
ctrl+space shortcut conflicts with 'switching language' in file explorer

### ISSUE THREAD

**Issue by teadrinker2015** [microsoft/microsoft-ui-xaml#8722]
### Describe the bug

as title described

### Steps to reproduce the bug

rename file name in file explorer and press ctrl+space, and it pops up a "I have no idea but it says 'winUI desktop'" window.

### Expected behavior

switch language

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DarranRowe** [comment]
![Screenshot 2023-08-07 201108](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/f6b9794a-23ac-4dda-8268-3a7a8d5ba574)

[https://github.com/microsoft/PowerToys](https://github.com/microsoft/PowerToys)

**Comment by teadrinker2015** [comment]
> ![Screenshot 2023-08-07 201108](https://user-images.githubusercontent.com/52577874/258905087-f6b9794a-23ac-4dda-8268-3a7a8d5ba574.png)
> 
> https://github.com/microsoft/PowerToys

Thank you. That solves my problem. It's weird that I installed powertoys long time ago, but only realized this problem recently (yesterday after reboot to 22H2)... Anyway, It's a powertoys's issue.
