### ISSUE TITLE
Top 1px border is broken

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#873]
**Describe the bug**

The top 1 px border is broken 
**Steps to reproduce the bug**

1. Open any app (such as Settings)

**Expected behavior**

1 px would be normal 
**Screenshots**

https://www.reddit.com/r/Windows10/comments/7t55ub/dear_microsoft_please_fix_the_borders/

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**I'm really not sure if this is in the scope of WinUI** but as I understand it, WinUI 3 will be handling a lot more.

**Comment by jevansaks** [comment]
Sorry for the delayed response. This issue is not specifically about the UI platform, this is about the UI design in windows for non-client area recently (I personally agree with the complaint, FWIW). Can you file an issue in feedback hub and I can make sure it finds its way to the right owners?

**Comment by Poopooracoocoo** [comment]
I am 99.99% sure that it will be ignored. I've already filed an issue in feedback hub. i'll update this when i get on my own laptop

**Comment by Poopooracoocoo** [comment]
@jevansaks Here it is:
https://aka.ms/AA5i329

**Comment by jevansaks** [comment]
Thanks! I'm following up to see if I can get the feedback added to the right collection.
