### ISSUE TITLE
BitmapImage is not loading the online OSM link URI in the view.

### ISSUE THREAD

**Issue by saiganesh-sakthivel** [microsoft/microsoft-ui-xaml#8737]
### Describe the bug

We are using the BitmapImage to set the ImageSource for the custom view in the native Xamarin.Forms code. In order to obtain the online URI of OSM (https://a.tile.openstreetmap.org/1/1/1.png), we have used the BitmapImage. However, the BitmapImage has failed to load the online OSM URI link. We received an exception in the ImageFailed event. We have prepared a simple UWP sample to replicate the issue.

Sample link: [App2.zip](https://github.com/microsoft/WindowsAppSDK/files/12272159/App2.zip)

### Steps to reproduce the bug

1. Run the sample.
2. exception will thrown.be 

### Expected behavior

1. It should load the imagesource.

### Screenshots

<img width="464" alt="image" src="https://github.com/microsoft/WindowsAppSDK/assets/61176526/d7b8e2a5-89f9-4fc5-9e13-919bf4010eb4">

_No response_

### NuGet package version

None

**Comment by JJBrychell** [comment]
We are unable to repro this issue in WinUI3, but were able to do so using WinUi2. Since WinUi2 is in maintenance mode and the issue resolved in WinUI3, we are closing this issue.
