### ISSUE TITLE
SetVirtualHostNameToFolderMapping Does Not Trigger WebResourceRequested Event

### ISSUE THREAD

**Issue by camvm93** [microsoft/microsoft-ui-xaml#8740]
### Describe the bug

Hi,

Our project intends to upgrade from web view to webview2 for our application. (UWP app)
Our project display data as HTML for customer and use the local file.  All files are in zip file format, we need to detect and unzip them before loading them into webview.

In the old Webview, we used IUriToStreamResolver to detect and unzip it. 

In webview2, we used SetVirtualHostNameToFolderMapping and listen to the WebResourceRequested event. But it never triggers the WebResourceRequested event. 

![image](https://github.com/microsoft/WindowsAppSDK/assets/114783831/05a37fa1-b258-4fb1-9e4d-71db283cd39a)

Note: it still works fine WebResourceResponseReceived. If we tried to unzip manually.

Any suggestion,  it is blocking us to upgrade. Can anyone take a look?

Thanks,

### Steps to reproduce the bug

Use SetVirtualHostNameToFolderMapping to host in local file.

Add listen WebResourceRequested Event.

Expected: we should received event.
Actual: Nothing happened. 

### NuGet package version

None

**Comment by camvm93** [comment]
@bpulliam Any update on this issue. 
Currently, we cannot upgrade to webview2. Any suggestion? 
All content in zip file, we need to detect requested resource and unzip it and load into webview.
I read MS document about webview2.
1. If we use SetVirtualHostNameToFolderMapping, then webview2 won't fire WebResourceRequested event.
2. If we use Navigate to html file on local file, it will through error due to security and we cannot disable security.
disable Cross-Origin Resource Sharing (CORS) i

**Comment by DmitriyKomin** [comment]
This sounds like an Edge/CoreWebView2 Issue that should be moved to [WebView2Feedback](https://github.com/MicrosoftEdge/WebView2Feedback). @champnic, can you take a look?

**Comment by champnic** [comment]
This is a known issue on WebView2:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2103
