### ISSUE TITLE
Bug title  Extended TitleBars have no top border in High Contrast themes

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#8743]
### Describe the bug

When you extend into the client area, the TitleBar looses its top most border in HighContrast.

![image](https://github.com/microsoft/WindowsAppSDK/assets/7389110/4cb77b37-6d23-4400-a89c-b7829452509a)

AFAIK there is no Window event that fires when the App becomes inactive, so when you try to add a border to compensate, there is no easy way to detect when to swap out the resource or colour.

### Steps to reproduce the bug

Activate High Contrast Themes, and open a Window with an extended title bar

### Expected behavior

The Top border should be retained in HighContrast, or an easy way to compensate for the loss of this border should be possible.

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/7389110/5969ee77-c6a1-47bf-9b28-a86ab6f9f42e)

### NuGet package version

Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by bpulliam** [comment]
Resolving as a dup of #6901. The developer is looking at the issue now.

**Comment by bogdan-patraucean** [comment]
@bpulliam so is someone still working on this or? the other issue was closed as well.
