### ISSUE TITLE
v1.4 crashes with fail-fast on system backdrops

### ISSUE THREAD

**Issue by jcoc611-microsoft** [microsoft/microsoft-ui-xaml#8744]
### Describe the bug

After upgrading to v1.4, we are noticing crashes with fail-fast exceptions when using system backdrops (e.g. acrylic) on context menus or AppBar.

Crash is in `CPopup::EnsureContentExternalBackdropLink` with `hr=80004003 - Invalid pointer`

Downgrading to 1.3 and rebuilding seems to fix the issue for us.

### Steps to reproduce the bug

1. Create an app with an App Bar or context menu using `Background="{ThemeResource SystemControlAcrylicElementBrush}"`
2. Try interacting with the menu a few times.
3. Fail-fast crash!

### NuGet package version

Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Other

**Comment by codendone** [comment]
This should be fixed in 1.4.230811000-preview2.
