### ISSUE TITLE
Proposal:  Thumbnails for known default file types

### ISSUE THREAD

**Issue by gravnetic** [microsoft/microsoft-ui-xaml#875]
Assign thumbnail preview for default filetypes.  SVG is a growing filetype that is surely going to be around for the foreseeable future.  How about supporting preview and thumbnails?

Please also consider default Adobe formats:  PSD, AI, and PDF

The solutions for implementing preview thumbnails on filetypes that are common to many users require registry access and editing.  

This is an unintuitive and dangerous solution for most Windows users since unfamiliarity with the UI and implications of not following as instructed in these areas of the filesystem can have adverse and negative experiences.

Allow registered filetypes simple, expanded ability to preview thumbnails.

**Comment by jevansaks** [comment]
I think this is a great suggestion, but outside the scope for our project. Can you file this feedback in Feedback Hub and I can try to route it to the correct owners?

**Comment by gravnetic** [comment]
Jevansaks, may I ask where the feedback huh is?

**Comment by jevansaks** [comment]
Feedback Hub is an app that ships in Windows. (https://en.wikipedia.org/wiki/Feedback_Hub)
