### ISSUE TITLE
1.4 preview: Flyout backdrop theme is derived from system theme and not from its associated element

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#8756]
### Describe the bug

The background of flyouts in 1.4 preview 1/2 is derived from the system theme instead of the theme of the associated element like the reset of the flyout:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/38145893/0c2ddcbc-bed3-4739-8006-76d344bdd6e7)

### Steps to reproduce the bug

1. Create a new winui project (1.4 preview 1/2) and use the following xaml:

```xaml

<Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" RequestedTheme="Dark">
    <Button x:Name="myButton" HorizontalAlignment="Center">
        <Button.Flyout>
            <MenuFlyout>
                <MenuFlyoutItem Text="Test" />
            </MenuFlyout>
        </Button.Flyout>
        Click Me
    </Button>
</Grid>
```

2. Open the app when the system mode is set to light theme and open the flyout

### Expected behavior

The flyout should have a dark theme backdrop

### NuGet package version

WinUI 3 - Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by AdriaanLarcai** [comment]
This is still an issue in the release version of 1.4. How did this pass QA? What are you guys doing?

**Comment by AdriaanLarcai** [comment]
The workaround for this is to either override the style for FlyoutPresenter and any other derivative controls such as the MenuFlyoutPresenter in your app's style resource dictionaries like this:

```
  <Style TargetType="FlyoutPresenter">
      <Setter Property="Background" Value="{ThemeResource ApplicationPageBackgroundThemeBrush}"/>
      <Setter Property="BorderBrush" Value="{ThemeResource ApplicationPageBackgroundThemeBrush}"/>
  </Style>
```
```
  <Style TargetType="MenuFlyoutPresenter">
      <Setter Property="Background" Value="{ThemeResource ApplicationPageBackgroundThemeBrush}"/>
      <Setter Property="BorderBrush" Value="{ThemeResource ApplicationPageBackgroundThemeBrush}"/>
  </Style>
```

Or by overriding the respective brush resources, like so:

`<StaticResource x:Key="FlyoutPresenterBackground" ResourceKey="ApplicationPageBackgroundThemeBrush" />`
`<StaticResource x:Key="MenuFlyoutPresenterBackground" ResourceKey="ApplicationPageBackgroundThemeBrush" />`

**Comment by DHancock** [comment]
Thanks. That's much simpler than the workaround I'd implemented. I did change the brushes though:

````xml

    <Style TargetType="MenuFlyoutPresenter" BasedOn="{StaticResource DefaultMenuFlyoutPresenterStyle}">
        <Setter Property="Background" Value="{ThemeResource FlyoutPresenterBackground}"/>
        <Setter Property="BorderBrush" Value="{ThemeResource FlyoutBorderThemeBrush}"/>
    </Style>
````

**Comment by DHancock** [comment]
Ugh. The workaround above works fine for when the window's root layout element's `RequestedTheme` is specifically set to either Light or Dark when the theme is changed via my apps settings, however it doesn't work if the `RequestedTheme` is _ElementTheme.Default_ and the user changes the systems app preferred theme mode (Personalization->Colors->Choose your default app mode). The flyouts will again have the wrong background, extra code is required. 

My app has a single window and the theme mode is saved in the settings. This allows it to always set the `RequestedTheme` to be either Light or Dark even when the settings indicate use of the _ElementTheme.Default_ theme. I do this in the Window's `Activated` event handler:

````c#
  Activated += (s, e) =>
  {
      if (rootViewModel.SettingsViewModel.SelectedTheme == ElementTheme.Default)
      {
          if (e.WindowActivationState == WindowActivationState.Deactivated)
          {
              // allows any system theme changes to be shown while in the background (flyouts will have been closed)
              LayoutRoot.RequestedTheme = ElementTheme.Default;
          }
          else
          {
              // force the requested theme to always be either light or dark so that flyouts can pick up the correct colors
              LayoutRoot.RequestedTheme = Application.Current.RequestedTheme == ApplicationTheme.Light ? ElementTheme.Light : ElementTheme.Dark;
          }
      }
  };
````

**Comment by krschau** [comment]
@bpulliam Dev Home would love if this could get fixed sooner rather than later. We're itching to move up to 1.4 so that we can use the new widget interfaces.

**Comment by codendone** [comment]
There is a fix for this in [1.4.230913002](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.4.230913002).

**Comment by LucaCris** [comment]
> There is a fix for this in [1.4.230913002](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.4.230913002).

Nope:

![immagine](https://github.com/microsoft/microsoft-ui-xaml/assets/50824617/f0d4cf15-ba3e-4445-98ec-49286b36dbc3)

My extra added things are ok (Light), but system specific items get app theme, not element theme.

**Comment by codendone** [comment]
@LucaCris Please open a new issue providing more information on your scenario. The available fix is for MenuFlyout and CommandBarFlyoutCommandBar. There may be additional work required for other controls or custom styling of those controls.

**Comment by LucaCris** [comment]
My scenario is complex, @codendone ... A Dark frame of controls with inside a Light canvas viewer.

1.3 result is correct:
 
![immagine](https://github.com/microsoft/microsoft-ui-xaml/assets/50824617/df75ab8d-e233-4612-aa22-022bab49a835)

No time to create a dummy project now.

**Comment by codendone** [comment]
@LucaCris Is this a `CommandBarFlyoutCommandBar`? Do you have custom style defined for it? If you do, try adding this to its style definition:
```
    <Setter Property="SystemBackdrop" Value="{StaticResource CommandBarFlyoutSystemBackdrop}" />
```

**Comment by LucaCris** [comment]
> @LucaCris Is this a `CommandBarFlyoutCommandBar`? Do you have custom style defined for it? If you do, try adding this to its style definition:
> 
> ```
>     <Setter Property="SystemBackdrop" Value="{StaticResource CommandBarFlyoutSystemBackdrop}" />
> ```

No styles for me. And a similar problem is also present in latest WinUI Gallery App...

![immagine](https://github.com/microsoft/microsoft-ui-xaml/assets/50824617/4273e063-4a37-4a37-b543-891d8a6dc903)

(try doing Light/Dark combinations).

**Comment by LucaCris** [comment]
Upgraded to latest AppSDK: **unresolved**.

Light RichEditBox inside Dark app:

![immagine](https://github.com/microsoft/microsoft-ui-xaml/assets/50824617/861bda0f-d74a-4faf-adb0-b0c2230b2058)

Standard TextBox dark menu:

![immagine](https://github.com/microsoft/microsoft-ui-xaml/assets/50824617/d9f2f810-b544-4d89-869f-b8b4101208a2)

**Comment by LucaCris** [comment]
> @LucaCris Is this a `CommandBarFlyoutCommandBar`? Do you have custom style defined for it? 

Fixed with:

            <Style TargetType="CommandBarFlyoutCommandBar">
                <Setter Property="RequestedTheme" Value="Dark" />
            </Style>

Now it is dark, but correctly dark:

![immagine](https://github.com/microsoft/microsoft-ui-xaml/assets/50824617/7d2c80ca-54c1-4770-8649-4cb2b886e99d)

(light doesn't work)
