### ISSUE TITLE
Proposal: Dockable Windows

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#876]
# Proposal: Dockable Windows 

## Summary
Add support for dockable windows that can be docked to a window like what we have in Visual Studio 

## Rationale

* This is one of a popular Desktop apps modes, which UWP is currently lacking
* Allows us to make apps who's layout is personalised by the user

## Scope

| Capability | Priority |
| :---------- | :------- |
| Dock window  | Must |
| Dock window container control, inside which the dock window docks | Must |
| Dock window container (inside) dock options (top,bottom,center,left,right) | Must |
| Undock options (float) | Must |
| Dock options to any window (outside) (top,bottom,left,right) | Should |

**Comment by jevansaks** [comment]
Thanks, @harvinders ! We already have a proposal but it didn't have "dockable" in the title so it was hard to find. I updated the title. Can you add your thoughts to #668?
