### ISSUE TITLE
For Windows WinUI3 windows are always "inactive"

### ISSUE THREAD

**Issue by LucaCris** [microsoft/microsoft-ui-xaml#8764]
### Describe the bug

Unable to scroll any scroller control using mouse wheel if mouse option to scroll inactive windows is OFF.

### Steps to reproduce the bug

1. Go to Windows Mouse settings
2. Disable scroll of inactive windows on mouse over
3. Open WinUI 3 Gallery App
4. Nothing will scroll using mouse wheel, even if focused

### Expected behavior

The same that happens for any other software: scroll working when window is active.

### NuGet package version

1.1.3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by AgentRBY** [comment]
Up

**Comment by duncanmacmichael** [comment]
Fixed in 1.4.0. @bpulliam please close this issue as I cannot. :)

**Comment by tpoint75** [comment]
It is broken in Windows App SDK 1.6.1!
