### ISSUE TITLE
TeachingTip.IsOpen and TeachingTip.Visibility isn't working right.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/microsoft-ui-xaml#8766]
### Describe the bug

I have a teaching tip.  `IsOpen` and `Visibility` are bound to variables `_isTeachingTipOpen` and `_shouldShowTeachingTip` both of these are decorated with the `[ObservableProperty]` attribute from the windows community toolkit.  The PointerEntered and PointerExited events are triggered with ic:EventTriggerBehavior and ic:InvokeCommandAction.

My goal is to make a TeachingTip show/hide itself like a tooltip on a mouse hover.  I managed to make this happen, but with an odd combination.  

I set the mode for IsOpen to OneWay and the mode for Visibility to OneTime.

Anything else, results in not correct behavior.  I've tried
1. Declaring Visibility only in XAML and trying with modes OneWay and OneTime
2. Declaring IsOpen only in XAML and trying with modes OneWay and OneTime
3. Using both IsOpen and Visibility in XAML and switching between the 4 combinations of modes.

All other options either
1. The Teaching Tip didn't show up at all, or
2. Teaching tip did show up, but never went away.

I did verify that the event handlers are being called and the variables are changing.

### Steps to reproduce the bug

1. Make a new WinUI 3 project.
2. Make a button.
3. Make a TeachingTip and set the target to the button made earlier.
    1.  Set the binding mode of Visibility to OneTime
    2. Set the binding mode of IsOpen to OneWay 
5. Use the community toolkit to make two observable properties.  One maps to IsOpen and the other to Visibility.
6. Make two events, PointerEntered and PointerExited.
7. When PointerEntered fires, wait 1.5 seconds, then show the TeachingTip by turning IsOpen and Visibility to true.
8. When PointerExited fires, wait 500 ms, then hide the TeachingTip by setting IsOpen and Visibility to false.

[Here](https://github.com/microsoft/devhome/blob/user/dhoehna/ToolTipPersisted/tools/SetupFlow/DevHome.SetupFlow/Views/SetupFlowPage.xaml#L123) is the code.

### Expected behavior

I would have to either change Visibility or IsOpen to manually show/hide a teaching tip not both, and only in a certain way.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows Insider Build (xxxxx)

**Comment by DmitriyKomin** [comment]
@dhoehna, thank you for reporting this. Would you be able to provide a small standalone WinAppSDK repro app for us to investigate this further?
