### ISSUE TITLE
Auto ScrollBarVisibility only shows the scroll bar on mouse over

### ISSUE THREAD

**Issue by williamfigtree** [microsoft/microsoft-ui-xaml#8767]
### Describe the bug

Setting `ScrollViewer.VerticalScrollBarVisibility` or `ScrollViewer.HorizontalScrollBarVisibility` to `Auto` does not show the scroll bar when the viewer content exceeds the allocated size. Instead, it is only shown on mouse over.

### Steps to reproduce the bug

1. Use Xaml like:
```
<Grid RowDefinitions="*, Auto">
        <ScrollViewer VerticalScrollBarVisibility="Auto" Grid.Row="0">
            <TextBlock
                TextWrapping="WrapWholeWords"
                FontSize="20"
                Text="This is a very long text. This is a very long text. This is a very long text. This is a very long text. This is a very long text. This is a very long text. This is a very long text."/>
        </ScrollViewer>
        <Rectangle Fill="CornflowerBlue" Height="200" Grid.Row="1"/>
    </Grid>
```

2. Resize the app so that the text content no longer fits in the viewport.
3. Observe no vertical scroll bar appears.
4. Mouse over the text content.
5. Observe a vertical scroll bar appears.

### Expected behavior

The scrollbar should be visible whenever the viewport cannot display all of the content. Per: https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.scrollbarvisibility?view=windowsdesktop-7.0

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

In my use case I have text blocks with long content that requires a vertical scrollbar. This can include instructions to the user. When the scroll bar does not appear there is no clue to the user that there is more content than what is immediately displayable within the viewport.

**Comment by ranjeshj** [comment]
dup of https://github.com/microsoft/microsoft-ui-xaml/issues/8769
