### ISSUE TITLE
Updating an ObservableCollection bound to a MenuItemsSource crashes with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by BretJohnson** [microsoft/microsoft-ui-xaml#8770]
### Describe the bug

When a `NavigationView` uses `MenuItemsSource` to bind to an ObservableCollection, updates to the ObservableCollection will often cause the app to crash with an `System.ArgumentOutOfRangeException: 'This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')'`.

These issues look similar - I expect the root cause is the same/similar:
- https://github.com/microsoft/microsoft-ui-xaml/issues/8684
- https://social.msdn.microsoft.com/Forums/en-US/d0d6709e-2da3-450a-8212-f1b07cf9fd51/uwpargumentoutofrangeexception-when-clearing-collection?forum=wpdevelop
- https://github.com/microsoft/microsoft-ui-xaml/issues/2818
  Here the source is bound to an array instead of an ObservableCollection, but it still crashes (sometimes).
  Note that https://github.com/microsoft/microsoft-ui-xaml/pull/3138 claims to fix this bug, but it's not completely fixed. I still see crashes when updating the repro app (attached) to use an array instead of an ObservableCollection.
  
Fixing this is important to MAUI, given that MAUI shell uses NavigationVIew with MenuItemsSource. Here's the bug we're using to track this issue on the MAUI side: https://github.com/dotnet/maui/issues/16929

### Steps to reproduce the bug

1. Open the repro project, here
[NavigationViewUpdateCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12415058/NavigationViewUpdateCrash.zip)
2. Build and run it. The app has a NavigationView with a MenuItemsSource set to a simple ObservableCollection, with 7 items.
4. Select one of the navigation items on the left. The NavigationView_ItemInvoked code adds an item to the ObservableCollection, then removes the first item.

Result:
App crashes with `System.ArgumentOutOfRangeException: 'This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')'`. The full call stack is here: https://gist.github.com/BretJohnson/82f2c831a1a7ed2ddf1d74bb5710c717

Looking at what's happening, the CollectionChanged is triggered by the Add (which works fine) and then again with the Remove (which crashes). The CollectionChanged triggers updating the layout, which then appears to reference some old data in the collection when computing the new layout. 

Note that the exception message is also wrong and should really be fixed too - the offending index here (per the debugger) isn't larger than Int32.MaxValue - it's 7, which happens to be one bigger than the current max index of 6. Something in the layout code is referencing an index past the end, which used to be valid but no longer is after the remove.

I tried various workarounds. Doing the remove first then the add doesn't crash, but it's hard to generalize for all the MAUI scenarios that need it (since sometimes the Add and Remove are far removed). Switching from ObservableCollection to just using an array or List and updating `MenuItemsSource` when it changes didn't work either - that also crashes on updates in WinUI runtime code; the symptoms are a bit different the root cause of that crash looks similar.

### Expected behavior

It shouldn't crash.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/245892/1a86e86b-4adb-46b3-80c5-bec404dd08e2)

### NuGet package version

None

**Comment by zadjii-msft** [comment]
Huh, MSFT:33651693 has an internal report of a crash in `MeasureOverride` in an `ItemsRepeater` that we were pretty sure was related to a nav view. 

MSFT:34550937 mentioned something similar, but I'm not sure that's totally relevant. The notes in our bug (34550937) mentioned something about the backing collection changing while a layout was in progress - I'm not sure that's totally relevant though. We were using a `MenuItems` and switching to a `MenuItemSource` fixed it for us[^1]. The error text though - "The operation attempted to access data outside the valid range" seems closer to what you're seeing here.  

[^1]: https://github.com/microsoft/terminal/pull/14630

**Comment by BretJohnson** [comment]
https://github.com/dotnet/maui/issues/16324 looks like another variant - another issue with ObservableCollection based bindings acting up during the layout pass. That bug produces a "Child collection must not be modified during measure or arrange." exception, like @zadjii-msft reported happens for their Terminal MenuItems bug https://github.com/microsoft/microsoft-ui-xaml/issues/8770#issuecomment-1695825256

**Comment by busitech** [comment]
@llongley If this issue is completed, how is the fix being made available?   I see no references in the sidebar to a release containing the solution.

**Comment by busitech** [comment]
@BretJohnson have you ever been able to fine an open issue that tracks the root cause of this issue in any publicly accessible repo?

**Comment by busitech** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/8684
