### ISSUE TITLE
Bug Interop SetParent Method - Child window not Resize or Drag inside parent window on Windows 11

### ISSUE THREAD

**Issue by danielancines** [microsoft/microsoft-ui-xaml#8779]
### Describe the bug

Using the SetParent method from user32.dll, to put a new window inside de main window, on Windows 11 Enterprise and Pro, Version 21H2 OS Build 22000.2176, the child window goes inside the parent window, but looses the resizable property and title bar, this behavior is not happening on Win 10.

### Steps to reproduce the bug

. Create new WinUI3 Project
. On click button, get MainWindow handle
. Create new Window
. Activate new Window
. Get new Window handle
. Change child window parent with SetParent method.

### Expected behavior

Child window, inside de MainWindow be resizable and draggable.

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/2250055/760affc6-36e5-4848-839a-68082d822cef)

### NuGet package version

Windows App SDK 1.3.2: 1.3.230602002

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

https://github.com/danielancines/winUI3-setParent

**Comment by DarthMazut** [comment]
@danielancines I just tried to use `SetWindowLong` with different style values e.g. `WS_EX_OVERLAPPEDWINDOW`, `WS_EX_TOOLWINDOW` but it stops working when I call `SetParent` (no matter whether I call it before or just after window is opened).  What style value did you use?

Besides UI there are also other issues regarding parent-child relation after using `SetParent`:
1. When I close parent window the application seems to continue running in the background (this can be observed in VisualStudio diagnostic Tools), so the only way at this point is to terminate app by pressing `Stop Debugging` in IDE
2. Child window is not showing in TaskBar

So I find that there is another way to set this parent-child relation between windows:
```cs
AppWindow.Create(appWindowPresenter, ownerWindowId)
```

but with this approach I'm not sure how I can define XAML for the content of such created window, and here when I close the supposed parent window the child still stays open, so I'm not sure at this point whether there are any benefits of trying to set this relation.

**Comment by danielancines** [comment]
@DarthMazut I tried all styles and nothing worked until now.
Today I get this behavior, apparently the resizable border is not resizing properly when width is bigger than width when the window became a child of MainWindow.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/2250055/1f54641c-bd4c-4d9d-828c-6cb332c63347)

I created a project using dotnet Maui and the problem is the same: https://github.com/danielancines/Maui-Win11-Resize-Issue

**Comment by danielancines** [comment]
Apparently the content is resizing, WTF?!?!?!

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/2250055/aee7753a-cc34-47a9-aa17-26356d42efb8)

**Comment by danielancines** [comment]
@castorix thanks for reply, but the problem is on Win11, my implementation on win10 is working fine. I didn't use GWL_EXSTYLE for win10, but on win11 I'm trying everything and the GWL_EXSTYLE was the only way to get resize working partially.

**Comment by castorix** [comment]
> @castorix thanks for reply, but the problem is on Win11, my implementation on win10 is working fine. I didn't use GWL_EXSTYLE for win10, but on win11 I'm trying everything and the GWL_EXSTYLE was the only way to get resize working partially.

I only have Windows 10. I made a small test sample with a SwapChainPanel (Windows 10, Windows App SDK 1.1.0), maybe you can test it on Windows 11 : [WinUI3_SwapChainPanel_SetParent.zip](https://app.box.com/s/byr3ctxjog2fmbvrvhg59t1k4t528nft)

**Comment by danielancines** [comment]
I found a Workaround and update on a new branch:
[Workaround Branch](https://github.com/danielancines/WinUI-Win11-Resize-Issue/tree/workaround
)

**Comment by danielancines** [comment]
Hi, what is the duplicated issue of this?

**Comment by JesseCol** [comment]
Hi, this was resolved as dupe of [8707](https://github.com/microsoft/microsoft-ui-xaml/issues/8707).  Thanks!
