### ISSUE TITLE
ItemTemplate on ItemsView throws an unhandled exception

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#8781]
### Describe the bug

If you set your own data template for an ItemsView the app throws an unhandled exception whenever the ItemsView is loaded. The app will work normally until the ItemsView is loaded.

### Steps to reproduce the bug

1. Create a packaged WinUI 3 app;
2. Create a blank page and set it as content of the main window;
3. In the page's xaml write a button and an ItemsView - set x:Load to false - and a simple DataTemplate for the ItemsView's ItemTemplate;
4. On the code behind create an ObservableCollection to add your items, write a simple code to add them;
5. On the click event for the button write code to load/unload the ItemsView;
6. Exception thrown when you click the button to load the ItemsView.

<ItemsView Height="500"
           x:Load="False"
           ItemsSource="{x:Bind ListOfStrings}"
           x:Name="ItemsViewOfStrings">

    <ItemsView.ItemTemplate>

        <DataTemplate x:DataType="x:String">

            <TextBlock FontSize="20"
                       FontWeight="Bold"
                       Text="{x:Bind }"/>

        </DataTemplate>

    </ItemsView.ItemTemplate>

</ItemsView>

### Expected behavior

No exception.

### NuGet package version

Windows App SDK 1.4 Preview 2: 1.4.230811000-preview2

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022-preview

### Additional context

- I tried first adding the items with a while loop inside the page's constructor, then one by one with another button's click.
- Had to create a page because I can't use FindName/UnloadObject on a window, even if it's from a control you'd expect to work.
- This problem isn't present on 1.4 experimental.

**Comment by ranjeshj** [comment]
@eduardobragaxz ItemsView requires ItemContainer to be the root of the template. Do you see this message in the exception thrown? This is currently a requirement to ensure that ItemsView's features work correctly.

**Comment by eduardobragaxz** [comment]
Hey @ranjeshj, it does work when the root of the template is ItemContainer, thanks!

Is the goal to not have to do this in the future? It's definitely distinct from other collection controls.

Doing it like I did before doesn't show any specific message. It just throws a xaml unhandled exception.
