### ISSUE TITLE
ContextFlyout throw exception in a GridView with Template in v1.4

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#8782]
### Describe the bug

i am using a ContextFlyout in my DataTemplate:

```
 <GridView.ItemTemplate>
     <DataTemplate>
         <Grid>
             <Grid.ContextFlyout>
                 <MenuFlyout>
                     <MenuFlyoutItem Text="Open Image (Photo App)" />
```

Right clicking on the item to open the menu will result in an error.
The app works without issues in version 1.3.3, after updating to v1.4-preview2 causes crashes

### Steps to reproduce the bug

create app with ContextFlyout in datatemplate

### NuGet package version

Windows App SDK 1.4 Preview 2: 1.4.230811000-preview2

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by codendone** [comment]
I currently can't repro this issue. Is there more required to hit this? Can you share a callstack of the exception?

**Comment by ghost1372** [comment]
Hi @codendone 
sorry for late response.

I removed the following option from csproj and it seems to have solved the problem. 
`<AccelerateBuildsInVisualStudio>True</AccelerateBuildsInVisualStudio>`
