### ISSUE TITLE
Slide effect of SlideNavigationTransitionInfo goes over another control

### ISSUE THREAD

**Issue by yki5000** [microsoft/microsoft-ui-xaml#8785]
### Describe the bug

I added it in the xaml but the sliding effect seems broken, it goes over the navigation bar.
It looks less bad, if I add the effect in code and not as xaml TransitionCollection.

Look here, tested in C++ and C#, same result: 

https://github.com/yki5000/WinUI3_Unpackaged_CPP/issues/3

I'm on 1.3. (only use stable versions but I don't know, if this version is officially supportet because it works in the WinUI 3 gallery)

### Steps to reproduce the bug

1. Create an unpackaged app.
2. Create a page with some test content.
3. Add a frame to the main window.
4. Add a NavigationView to the main window (left compact design).
5. Add the TransitionCollection to the frame.

> <Frame x:Name="frmContent" >
	<Frame.ContentTransitions>
		<TransitionCollection>
			<EdgeUIThemeTransition Edge="Left">
			</EdgeUIThemeTransition>	
		</TransitionCollection>
	</Frame.ContentTransitions>
</Frame>

6. Test the navigation by the navigate method, you should see the error.
7. For the second test just remove the  TransitionCollection from the frame and add the following code and adjust it. The error is still there but it looks less bad.

> // Create the slide transition and set the transition effect to FromRight.
SlideNavigationTransitionInfo slideEffect = SlideNavigationTransitionInfo();
slideEffect.Effect(SlideNavigationTransitionEffect(SlideNavigationTransitionEffect::FromRight));
Frame().Navigate(winrt::xaml_typename<BasicNavigation::Page2>(),winrt::box_value(name().Text()),slideEffect);

### Expected behavior

Slide effect of SlideNavigationTransitionInfo should not go over an other control.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by yki5000** [comment]
If you look on my page, I tested it in c#, same result.

**Comment by lhak** [comment]
Have you tried putting the frame into the NavigationView.Content section?

**Comment by Fritierkelle** [comment]
@Ihak, thank you.
The NavigationView was not implemented correctly by me.

**Comment by yki5000** [comment]
@ihak, thank you.
The NavigationView was not implemented correctly by me.
