### ISSUE TITLE
Is it possible to host a UWP control inside a WinUI application?

### ISSUE THREAD

**Issue by JeganRavichandran** [microsoft/microsoft-ui-xaml#8786]
### Describe the bug

I am using a third party UWP control, but it is not available in the WinUI platform yet, can I host it in the WinUI application? if so how?

### Steps to reproduce the bug

This is a question, not a bug.

### NuGet package version

None

**Comment by codendone** [comment]
Hi @JeganRavichandran. No, it is not possible to host a UWP control inside a WinUI3 application: having two versions of XAML loaded in the same process has a variety of problems.

**Comment by duncanmacmichael** [comment]
Closing this issue as it appears to have been answered.
