### ISSUE TITLE
Blank WinUI app doesn't build

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#8796]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blank-WinUI-app-doesnt-build/10420779)._

---
When blank WinUI app is created via the New project dialog, it fails to build because of

> CS8618	Non-nullable field 'm_window' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.	App40	C:\Dev\Throwaway\App40\App.xaml.cs	33	Active

It works when line 48 of App.xaml.cs is changed to 

private Window? m_window;

This should not be necessary though, as Nullable reference types are not explicitly declared in the .csproj.

---
#### Feedback Bot on 7/23/2023, 10:24 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by evelynwu-msft** [comment]
This warning only appears if the [project-wide nullable context](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts) is enabled (e.g. `<Nullable>enabled</Nullable>`). This setting is disabled by default in the Windows App SDK project templates.
