### ISSUE TITLE
Dynamically discover tests to create Helix Work Items instead using a static list

### ISSUE THREAD

**Issue by kmahone** [microsoft/microsoft-ui-xaml#88]
For [Enable WinUI tests in Helix](https://github.com/Microsoft/microsoft-ui-xaml/pull/83), we create a hard-coded list of Helix Work Items to create for running tests. Each test class has an entry in RunTestsInHelix.proj that needs to be maintained (e.g. add a new entry when a new test class is created).

Instead we could parse the output of "te.exe /list" to discover the full set of tests and then dynamically create the work items as needed. This would mean that we would not need to manually maintain the list and it would also mean that we could get better parallelization, by having each Helix work item run an equal number of test methods - right now the break down is by test class even though not every test class has the same number of tests (and we needed to special case NavigationViewTests due to it having a significantly longer runtime).

**Comment by jevansaks** [comment]
The implication without having this is that devs manually need to modify the XML for the helix thing when adding new test classes. Seems ok for now as long as 1 person in the PR remembers to remind the dev.

**Comment by kmahone** [comment]
Fixed with #642
