### ISSUE TITLE
[.NET 8 RC1] WinUI 3 App(C# Unpackaged) fails to run.

### ISSUE THREAD

**Issue by AnnYang01** [microsoft/microsoft-ui-xaml#8801]
### Describe the bug

When we create a "Blank App, Packaged (WinUI 3 in Desktop)" with .NET 8 RC1, we met 3 errors about NETSDK1083 (record in https://github.com/microsoft/WindowsAppSDK/issues/3842), we update the `<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>` to `<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>`, and run it, it fails to run.

### Steps to reproduce the bug

1.Install VS from [Pipelines - Run main-34029.95](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8325241&view=results) (Contains the .NET 8 RC1)
2.Create a new app using the "Blank App, Packaged (WinUI 3 in Desktop)" 
3. In order to avoid NETSDK1083 error, we should update the `<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>` to `<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>`
4. Add this property to the first PropertyGroup of project file: <WindowsPackageType>None</WindowsPackageType>
5. To debug in Visual Studio, select the 'Unpackaged' launch profile in the Start drop down.
6. Build and run.

### Actual result
fail to run
output log
Exception thrown: 'System.DllNotFoundException' in Microsoft.WindowsAppRuntime.Bootstrap.Net.dll
The program '[13388] App8.exe: Program Trace' has exited with code 0 (0x0).
The program '[13388] App8.exe' has exited with code 3762504530 (0xe0434352).
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/131441429/0908934f-7584-4467-bf3f-977a39168ac2)

### Expected behavior

App runs without errors.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

VS version: 17.8.0 Preview 2.0 [34029.95.main]
Windows App SDK version: 1.3.230602002

**Comment by ghost1372** [comment]
There was a breaking change in .NET8 to how it handles the runtime identifier graph: [[Breaking change]: Projects targeting .NET 8 and higher will by default use a smaller, portable RID graph. · Issue #36527 · dotnet/docs (github.com)](https://github.com/dotnet/docs/issues/36527). To use .NET8 with Windows App SDK, [setting UseRidGraph to true](https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list#recommended-action) is recommended.

**Comment by AnnYang01** [comment]
@ghost1372 
I have added a RuntimeHostConfigurationOption MSBuild item in my project file, but it still fails to run.  attach my project.
[App16.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12520126/App16.zip)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/131441429/67a1db24-fd22-4884-bb66-9d27bec8e257)

**Comment by AnnYang01** [comment]
@ghost1372  Add`<UseRidGraph>true</UseRidGraph>`into `PropertyGroup` tab, WinUI 3 App(C# Unpackaged) can run successfully now, so maybe this issue can be closed.

**Comment by dotMorten** [comment]
I don't think this issue should be closed. WindowsAppSDK needs to deal with these breaking changes correctly

**Comment by KritR** [comment]
@dotMorten If I’m understanding this correctly then, until all my app’s dependencies use portable id’s, my application needs to use the legacy runtime identifier graph?

**Comment by dotMorten** [comment]
I believe so yes. @richlander can probably confirm

**Comment by riverar** [comment]
I got my first question about this today too. If a MUX/WAS patch is not the pipeline, perhaps adding an explicit compatibility note to http://aka.ms/netsdk1083 would help? (Link is displayed in build errors.)

**Comment by greatoceansoftware** [comment]
I am having the same issue. Trying to update my WinUI 3/.NET 6 to .NET 8. While setting the RIDUseGraph to true works, I also found that the following change in the project file also works (so far; I haven't tried to create and distribute MSIX yet):

Modified the following lines in .csproj from:

```
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
	<PublishProfile>win10-$(Platform).pubxml</PublishProfile>

```
To:

```
	<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
	<PublishProfile>win-$(Platform).pubxml</PublishProfile>
```

**Comment by riverar** [comment]
@llongley Can you share the fix details here?

**Comment by greatoceansoftware** [comment]
Yes, @llongley would like to know the details.

**Comment by riverar** [comment]
@Scottj1s Can you help close the loop here?
