### ISSUE TITLE
Broken hit testing on extended title bar when maximized

### ISSUE THREAD

**Issue by BreeceW** [microsoft/microsoft-ui-xaml#8805]
### Describe the bug

In Windows App SDK 1.4+, it is not possible to interact with the edges of the title bar for an AppWindow or WinUI 3 Window with ExtendsContentIntoTitleBar set to true when the window is maximized. This means that users are not able to click on the close/restore/minimize buttons if the cursor is in the topmost or rightmost position on screen. This also breaks restoring a window by dragging it from the very top or farthest sides of the title bar.

Instead of showing the correct cursor and performing the correct action, the cursor on the edges of the title bar becomes a resize cursor, although no resizing occurs.

### Steps to reproduce the bug

1. Create a blank WinUI 3 app
2. In the constructor of MainWindow, set `ExtendsContentIntoTitleBar = true`
3. Run the app
4. Maximize the window
5. Move your cursor to the top right of the screen. Note that the close button will not highlight red and clicking does nothing and the cursor is a resize cursor (see similar effect on minimize and restore buttons on top edge)
6. Move your cursor to the top center of the screen and click and drag down. Note the window does not restore and move and the cursor is a resize cursor
7. Issue occurs on far left edge, far right edge, and top edge, as well as top left and right corners

### Expected behavior

The title bar should behave (perform hit testing) like the default Windows title bar. Users should be able to interact with window controls on the far edges and corners of the screen when windows are maximized.

### Screenshots

![Laptop screen with WinUI 3 window with extended title bar. Cursor is in top right of screen and is a NESW drag cursor](https://github.com/microsoft/microsoft-ui-xaml/assets/18747724/4f9c8788-510e-4bc8-8263-91d94bdf8467)

This is the cursor showing in the top right corner:
![NESW drag cursor](https://github.com/microsoft/microsoft-ui-xaml/assets/18747724/37747285-491b-41a0-99ac-9dc48c271618)

It should be a normal arrow cursor, and the button should be red when hovered (and close the window when clicked):
![Arrow cursor](https://github.com/microsoft/microsoft-ui-xaml/assets/18747724/19414805-251c-410b-acf1-ec99079599d4)

### NuGet package version

Microsoft.WindowsAppSDK 1.4.230822000
Microsoft.WindowsAppSDK 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by 0x5bfa** [comment]
Isn't this issue related to WinAppSdk rather than WinUI?

**Comment by 0x5bfa** [comment]
Thanks for the quick response, I hope so!

**Comment by codendone** [comment]
A fix has been checked in. Using #8665 as the main tracking bug.
