### ISSUE TITLE
Application crashes when trying to open any flyouts or popups

### ISSUE THREAD

**Issue by NicholasChrzan** [microsoft/microsoft-ui-xaml#8807]
### Describe the bug

Application crashes when trying to open any flyouts or popups. From crash dump the error looks like it's happening here:
00000093`8057d2a0 00007ffd`a156d9b2 KERNELBASE!RaiseFailFastException+0x152
00000093`8057d880 00007ffd`a28ac68a combase!RoFailFastWithErrorContextInternal2+0x43a
00000093`8057dae0 00007ffc`b4aa6ee4 Microsoft_ui_xaml!FailFastWithStowedExceptions+0x58
00000093`8057db10 00007ffc`b497b814 Microsoft_ui_xaml!CPopup::EnsureContentExternalBackdropLink+0xc4
00000093`8057dbe0 00007ffc`b4af14b9 Microsoft_ui_xaml!CPopup::SetSystemBackdrop+0x29
00000093`8057dc20 00007ffc`b4f7247f Microsoft_ui_xaml!DirectUI::Popup::put_SystemBackdrop+0x1f
00000093`8057dc50 00007ffc`aa980559 wuceffectsi!SystemBackdropInternal::BaseController::SetSystemBackdropOnTarget+0x5d
00000093`8057dc80 00007ffc`aa983427 wuceffectsi!std::_Func_impl_no_alloc<<lambda_a2494cd3adddb5624028b9688cb43847>,void>::_Do_call+0x37
00000093`8057dcb0 00007ffc`aa97f8cc wuceffectsi!SystemBackdropInternal::BaseController::RunOnCompositionThread+0x118
00000093`8057dd60 00007ffc`aa97e913 wuceffectsi!SystemBackdropInternal::BaseController::SetSystemBackdropOnTargets+0xf7

### Steps to reproduce the bug

Open any flyout or menuflyout
App crashes.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by lhak** [comment]
I think I saw something similar after upgrading a project to appsdk 1.4. In my case, deleting the obj and bin folders and rebuilding helped.

**Comment by ranjeshj** [comment]
@NicholasChrzan this seems to work in WinUI 3 Gallery (compiled against 1.4). can you share a repro project?

**Comment by NicholasChrzan** [comment]
I had also just updated visual studio. It looks like restarting my laptop and purging the obj and
