### ISSUE TITLE
MenuFlyoutItem Tapped event callback method was not called

### ISSUE THREAD

**Issue by jhonToni** [microsoft/microsoft-ui-xaml#8811]
### Describe the bug

The tapped event callback method of MenuFlyoutItem  was not called.

### Steps to reproduce the bug

When i click on the `MenuFlyoutItem`  the Tapped event callback method was not called.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The sample app repo url : [https://github.com/jhonToni/WinuiMenuFlyoutSample](https://github.com/jhonToni/WinuiMenuFlyoutSample)

**Comment by jhert0** [comment]
This is happening in my application also.

**Comment by DmitriyKomin** [comment]
@jhonToni: This behavior is by design - the Tapped event is only fired in response to touch (Mouse click should trigger 'Click' event).

**Comment by jhert0** [comment]
That seems to be inconsistent with other controls, for example on a Button I can used the Tapped event and it works with the mouse.

**Comment by YexuanXiao** [comment]
> @jhonToni: This behavior is by design - the Tapped event is only fired in response to touch (Mouse click should trigger 'Click' event).

This is not what the documentation describes:https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.tapped?view=windows-app-sdk-1.4

>Touch, mouse devices and pen devices can all produce a Tap action. For more info, see [Handle pointer input](https://learn.microsoft.com/en-us/windows/apps/design/input/handle-pointer-input).
