### ISSUE TITLE
Regression: Initial control is not focused

### ISSUE THREAD

**Issue by BreeceW** [microsoft/microsoft-ui-xaml#8816]
### Describe the bug

WinUI 3 on Windows App SDK 1.4 does not focus the initial control in a window by default. In previous releases, the control with the lowest TabIndex would automatically get focus. Now the user must tab once before they can do anything useful with the keyboard.

### Steps to reproduce the bug

1. Create a new WinUI 3 app with the Visual Studio template and update to Windows App SDK 1.4
2. The default template should have included a button and a clicked handler that changes the button’s text
3. Run the app
4. Press the space key. This should have triggered the button click and changed the button’s text from “Click Me” to “Clicked” but it does not
5. Press the tab key and then press space. Now the button has been “clicked.”

### Expected behavior

The button (generally, the control with the lowest TabIndex) should be focused automatically when the window opens, instead of having to tab to it first.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Interestingly, if the window is deactivated immediately after it opens (i.e., user selects a different window) and then returns to the window (even without clicking inside the window content area), the correct control will become focused.

**Comment by pratikone** [comment]
Found and fixed the issue. Closing now. should be available in next winappsdk minor release like 1.6
