### ISSUE TITLE
[WinUI3 1.4 Regression] Incorrect open direction in CommandBar

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#8822]
### Describe the bug

Set CommandBar.ClosedDisplayMode = "Minimal"

Closed:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42038175/b4796691-b86b-415a-998c-ce923e512708)

Opened (Incorrect):
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42038175/eca5e35c-a064-405e-a8ab-25a4cfba14ee)

### Steps to reproduce the bug

1. Create a new CommandBar with multiple PrimaryCommands in XAML
2. Set ClosedDisplayMode to "Minimal"

### Expected behavior

Open direction should be "Top" instead of "Bottom"

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This issue has never seen in Windows App Sdk 1.3.X

**Comment by zhuxb711** [comment]
@bpulliam Still exists in Windows App SDK 1.4.2. Could share any plans about fixing this bug?

**Comment by zhuxb711** [comment]
@bpulliam @Scottj1s Please make it more transparent but just keeping silent.

![GIF 10-19-2023 5-08-31 PM](https://github.com/microsoft/microsoft-ui-xaml/assets/42038175/24873c82-f1ba-4bc9-9dc3-89bec1531b5d)

**Comment by zhuxb711** [comment]
@llongley Not fixed in the latest WindowsAppSdk release?

**Comment by gegao18** [comment]
We have the fix in WinAppSDK 1.5.
