### ISSUE TITLE
ItemTemplateSelector for ItemsView

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#8826]
### Describe the bug

why we can not use ItemTemplateSelector in ItemsView? is there any solution?

### Steps to reproduce the bug

ItemTemplateSelector for ItemsView

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
You should be able to set a DataTemplateSelector on the ItemTemplate property in ItemsView. ItemTemplate property is of type IElementFactory and both DataTemplate and DataTemplateSelector implement that interface. If you want to get fancy, you can create your own implementation as well.
