### ISSUE TITLE
Property Change in MenuBarItem not working.

### ISSUE THREAD

**Issue by JustBoredTbh** [microsoft/microsoft-ui-xaml#8827]
### Describe the bug

I tried to change the font, Colour and Size of a MenuBarItem, but when rendered, the MenuBarItem does not reflect the change. I also restarted the build but it still didn't work.
A somewhat similar issue raised but no solutions have been provided #7070

### Steps to reproduce the bug

1. Add this code to your MainWindow.xaml file
```
<MenuBarItem Title="View"
             FontFamily="{StaticResource Righteous}"
             FontSize="14"
             FontWeight="Normal"
             Foreground="#5b5b5b">
    <MenuFlyoutItem Text="Edit History"
                    FontFamily="{StaticResource Righteous}"
                    FontSize="14"
                    FontWeight="Normal"
                    Foreground="#5b5b5b"/>
    <MenuFlyoutSeparator/>
    <MenuFlyoutItem Text="Pending Audits"
                    FontFamily="{StaticResource Righteous}"
                    FontSize="14"
                    FontWeight="Normal"
                    Foreground="#5b5b5b"/>
    <MenuFlyoutSeparator/>
    <MenuFlyoutItem Text="Approved Commits"
                    FontFamily="{StaticResource Righteous}"
                    FontSize="14"
                    FontWeight="Normal"
                    Foreground="#5b5b5b"/>
</MenuBarItem>
```
2. The FontFamily can be any random FontFamily added to the resource dictionary.

### Expected behavior

MenuBarItem was expected to have the same fontstyle as its flyout.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/137584397/2b092aa8-a5ec-4be1-ad70-43dfb911e314)

Rather it still has the default MenuBarItem Style.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The MenuBarItem Is Inside a custom app bar.

**Comment by JustBoredTbh** [comment]
The Margin Property Seems to be working. But any Text Styling doesn't work.

**Comment by kmgallahan** [comment]
What is the parent of your ResourceDictionary?

**Comment by JustBoredTbh** [comment]
its an Application-level Resource Dict

> What is the parent of your ResourceDictionary?

**Comment by JustBoredTbh** [comment]
I found a way to change the font of the menubaritem using the app.xaml file.
You override the contentcontroltheme properties like this:

```<FontFamily x:Key="ContentControlThemeFontFamily">/Assets/Fonts/Righteous Regular.ttf/#Righteous</FontFamily>```
