### ISSUE TITLE
Cannot scroll ComboBox items by touch after second expand 

### ISSUE THREAD

**Issue by adamfierek** [microsoft/microsoft-ui-xaml#8831]
### Describe the bug

After second expand of ComboBox, scrolling items list is impossible by touch. Need to unload and load CB again

### Steps to reproduce the bug

1. Load page with ComboBox
2. Expand cb items by touch
3. Try to scroll by touch
4. Unfocus cb
5. Expand cb again
6. Scrolling by touch does not work

### Expected behavior

Scrolling cb by touch works every time

### NuGet package version

WinUI 3 - Windows App SDK 1.4.1: 1.4.230913002

### Windows version

Windows 11 (22H2): Build 22621
Windows 10 1809

### Additional context

On previous SDK version it worked (1.3).

**Comment by adamfierek** [comment]
Today I updated SDK to 1.4.1 and this bug still exists! It's not minor since it makes ComboBoxes unusable in touch-only systems.

**Comment by adamfierek** [comment]
Ok, the issue is closed and marked as fixed. Can we have any comment? In which release this fix will be included? When we can expect it?

**Comment by codendone** [comment]
The fix is in for 1.5. It is tagged for considering for 1.4 servicing, which requires some additional testing and discussion. Stay tuned for an update on that.

**Comment by adamfierek** [comment]
Thank you for information

**Comment by codendone** [comment]
Update: The fix is now approved for an upcoming 1.4 servicing release.

**Comment by bpulliam** [comment]
The fix is in 1.4.2, now available.
