### ISSUE TITLE
Unable to reach teaching tip using TAB

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#8833]
### Describe the bug

The teaching tip content cannot be accessed when using TAB

### Steps to reproduce the bug

1. start the WinUI 2 gallery
2. Open the teaching tip page
3. Using TAB focus the last "Show Teaching Tip" button
4. Press ENTER to open the teaching tip with hero content
5. Once opened, press TAB to try to focus the content of the teaching tip
6. TAB cycles through all the app controls except the teaching tip content which is unreachable.

### Expected behavior

Teaching tip content can be focused using TAB

### Screenshots

![teaching tip accessibility issue](https://github.com/microsoft/microsoft-ui-xaml/assets/20152272/03821b87-75ac-4f05-b5bc-ad1b03792cb8)

### NuGet package version

None

**Comment by vgromfeld** [comment]
This issue is similar to #2822

**Comment by ranjeshj** [comment]
This is by design. F6 will take you into the teaching tip.
