### ISSUE TITLE
AppBarButton's parent inside a CommandBar is null

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#8834]
### Describe the bug

I was expecting it to return the CommandBar, but it returns null.

### Steps to reproduce the bug

Add an AppBarButton inside a CommandBar and another outside. The one inside has a null parent.

### Expected behavior

Parent shouldn't be null.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
This is by design I believe (current design). The AppBarButton is not in the children collection of the CommandBar, so parent is null. VisualTreeHelper can help you get the parent.
