### ISSUE TITLE
Context menu is displayed out of screen

### ISSUE THREAD

**Issue by acouvert-msft** [microsoft/microsoft-ui-xaml#8838]
### Describe the bug

Depending of where it is triggered, a context menu may be partially displayed outside the application window. 
If the window is on the edge of the screen, the context menu won't be visible / accessible.

### Steps to reproduce the bug

1. Open WinUI 2 Gallery 
2. Navigate to RichTextBlock page
3. Move the application to the right edge of the screen
4. Move the mouse as right as possible on top of one of the RichEditBox and right click to show the context menu.
5. See that the menu is partially displayed outside the screen.

### Expected behavior

The context menu should always be fully visible.

### Screenshots

![repro](https://github.com/microsoft/microsoft-ui-xaml/assets/61151817/14c31559-b54e-4c40-be1f-299b800fb577)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
This is fixed in WinUI3.
