### ISSUE TITLE
ComboBox: Can't scroll to view and access all ItemsSource item (on small screen / scaled up text)

### ISSUE THREAD

**Issue by acouvert-msft** [microsoft/microsoft-ui-xaml#8839]
### Describe the bug

When display resolution is small and / or when font size is big, all the ItemsSouce item won't be fit in the available screen area, resulting in some item not be visible / accessible.

### Steps to reproduce the bug

1. Configure your scale layout to the biggest font scale available
2. Open WinUI Gallery
3. Navigate to ComboBox page
4. Try to list all available Font Size
5. Observe that the last items are not visible

### Expected behavior

We should have a mechanism allowing the user to see and access all items for all configuratio.

### Screenshots

On a screen with big enough resolution:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/61151817/63361d26-826a-40fa-a3e1-a1c9209f6a5f)

On a screen with small resolution and large font scale (Note that 72 is missing):
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/61151817/87a8fadc-1be9-4355-b053-eb9841c009f0)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

**Comment by bpulliam** [comment]
Does this also repro on WinUI 3?

**Comment by ranjeshj** [comment]
This is fixed in WinUI3.
