### ISSUE TITLE
ListView does not trigger "Loaded" events of items when Animations are turned off

### ISSUE THREAD

**Issue by andreaslennartz** [microsoft/microsoft-ui-xaml#8841]
### Describe the bug

The "Loaded" events of items in a ListView are not properly triggered when "Show animations" is turned off. (Go to Settings - > Ease to Access -> turn off Show Animations)

Consider a ListView that is bound to items using a data template
```C#
        <DataTemplate x:Name="itemTemplate" x:DataType="local:Item">
                <StackPanel Loaded="Grid_Loaded">
                    <TextBox
                        Loaded="TextBox_Loaded"                        
                        Text="{Binding Path=Value1, Mode=TwoWay}" />

                    <DatePicker
                        Loaded="DatePicker_Loaded"
                        SelectedDate="{Binding Path=Value2, Mode=TwoWay}" />
                </StackPanel>
            </DataTemplate>

<ListView
            ItemTemplate="{StaticResource itemTemplate}"
            ItemsSource="{Binding Children}"/>
```

When an item is added the first time, the Loaded-events in the template (e.g. the event on the StackPanel, or the two other on the TextBox or DatePicker) are properly invoked.
When removing an item in the bound collection, the loaded event is also invoked. This seems to be wrong - when removing an item, the Loaded event should not be triggered.
When adding a new item again to the list, the Loaded are not triggered at all for this item. This seems to be a bug. 

### Steps to reproduce the bug

- Go to the settings -> Ease to Access and turn off the Show Animations in Windows.
- Rebuild and run the attached project. 
- Click the Add button.
 Loaded-events will be called for the Textbox and Datepicker, which is good 
- Click the Remove button for the freshly added item.
- Loaded events are called again for the Textbox and Datepicker - this is unexpected. 
- Again click add button.
- Now the Loaded  events are not triggered at all 

### Expected behavior

When removing an item from the ItemSource of a ListView, the Loaded events should not be triggered. 
When re-adding items again, the Loaded events should be triggered. 

### Screenshots

[LoadedIssueinListView.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12542088/LoadedIssueinListView.zip)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044, Windows 10 (21H1): Build 19043, Windows 10 (20H2): Build 19042

**Comment by andreaslennartz** [comment]
Just in case somebody stumbles across the same issue. I create a workaround for this, by creating always a new data template (with `XamlReader.Load(..)`) when re-adding an item. The new data template has a different name, which seem to convince the ListView to properly call the Loaded-event again. Posting this here because it looks like the WinUI team is currently swamped with issues. 
[ListViewIssue_SolutionWithUserControl.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12549486/ListViewIssue_SolutionWithUserControl.zip)

**Comment by bkaankose** [comment]
Technically Loaded and Unloaded events should fire whenever the UI element is added to the visual tree. Bug you describe is probably related to the UI virtualization. This functionality re-uses the same UI elements but only updating the bindings on the fly. In that case this should not be considered as a bug, because you are re-using the existing container that is already realized in the visual tree.

If you disable virtualization by using a different ItemsPanelTemplate (like a Stackpanel) in your ListView, this issue might not happen.

This is just a theory though, I'm pretty sure WinUI guys can investigate the scenario better here :)

**Comment by andreaslennartz** [comment]
Hi @bkaankose ,
thanks a lot for pointing this out! I just tried it out:

```xaml
<ListView.ItemsPanel>
    <ItemsPanelTemplate>
        <StackPanel Orientation="Vertical" />
    </ItemsPanelTemplate>
</ListView.ItemsPanel>
```

and now everything works fine! 

Looks like the current ItemsPanelTemplate (which is `<ItemsStackPanel Orientation="Vertical" />`  in `generic.xaml`) seems to cause the issue. 

Looks like the best workaround for the time being.

**Comment by ranjeshj** [comment]
@andreaslennartz this is by design. ListView virtualizes its items as @bkaankose mentions above and loaded will not be triggered when items are recycled. Use ContainerContentChanging or other events to update the container when items come into view or when they get recycled.
