### ISSUE TITLE
Proposal: Introduce ComboBoxDropdownBackground Property in WinUI 3

### ISSUE THREAD

**Issue by ghostidentity** [microsoft/microsoft-ui-xaml#8863]
Description:
The current ComboBox control in WinUI 3 obliges developers to override the entire ControlTemplate to modify the background color of the dropdown container. This process is cumbersome and potentially error-prone, especially when the modification is as straightforward as a simple visual change.

Use Case:
The ability to easily customize the background color of the entire dropdown container is important for:

Branding: To align the application's ComboBox with corporate or design guidelines.
User Experience: To offer enhanced visual cues and improve usability.
Flexibility: To simplify theming and styling across different scenarios and layouts.
Proposed Solution:
Introduce a new XAML property for the ComboBox in WinUI 3, named ComboBoxDropdownBackground. This property will target the background color of the entire dropdown container, making it easier for developers to apply quick visual changes without dealing with ControlTemplates.

<ComboBox ComboBoxDropdownBackground="{ThemeResource SystemAccentColorDark3}">
    <ComboBoxItem Content="Item 1" />
    <ComboBoxItem Content="Item 2" />
</ComboBox>

Alternatives Considered:
Global Styling: Would affect all ComboBox instances, and therefore isn't a desirable solution for every use case.
Third-party Libraries: Using an external library to achieve this might introduce unnecessary overhead or conflicts with existing features.
Overriding ControlTemplate: This approach seems overkill for such a simple visual modification and could introduce unwanted side effects.
Additional Context:
Simplifying the way for developers to make this particular modification can streamline the development process. It will also make the framework more approachable for newcomers and reduce the risk of errors that can arise from meddling with complex ControlTemplates.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/4637625/1d6090e9-25b1-4a36-8b75-6f230b04fd23)

**Comment by DHancock** [comment]
This is already possible using [lightweight styling](https://learn.microsoft.com/en-us/windows/apps/design/style/xaml-styles#lightweight-styling) without touching the control template.
The two brushes that you need to modify are:
````xml
    <SolidColorBrush x:Key="ComboBoxDropDownBackground" Color="Pink"/>
    <SolidColorBrush x:Key="ComboBoxDropDownBorderBrush" Color="Red"/>
````

**Comment by ghostidentity** [comment]
@DHancock  thank you.  Im now closing the proposal.
