### ISSUE TITLE
InkToolbar crashes app

### ISSUE THREAD

**Issue by Norgerman** [microsoft/microsoft-ui-xaml#8865]
### Describe the bug

Every app load Inktoolbar will make app crashed. Such as snapping tool.

### Steps to reproduce the bug

For snapping tool: 
1.  Just open a file, then will crash

Or just use [SimpleInk](https://github.com/Microsoft/Windows-universal-samples/tree/main/Samples/SimpleInk): 
Will crash on app started.

### Screenshots

<img width="432" alt="4c33fe8dcbae95fd9e1a7b515afcf3d" src="https://github.com/microsoft/microsoft-ui-xaml/assets/9065389/d8cee2ce-795f-4015-bc10-cfdcc406c072">

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

[SimpleInk](https://github.com/Microsoft/Windows-universal-samples/tree/main/Samples/SimpleInk) crash dump attached

[SimpleInk.exe.10284.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12605361/SimpleInk.exe.10284.zip)

**Comment by ranjeshj** [comment]
Please file a feedback bug for SnippingTool.exe.

**Comment by codendone** [comment]
From the crash dump, it looks like your copy of `C:\Windows\System32\Windows.UI.Xaml.InkControls.dll` has been corrupted.

**Comment by Norgerman** [comment]
Comparing to the normal pc, checksum of the file are same.
