### ISSUE TITLE
Behaviors set in DataTemplates are mixing among ListView's items

### ISSUE THREAD

**Issue by adamfierek** [microsoft/microsoft-ui-xaml#8866]
### Describe the bug

When behavior (Microsoft.Xaml.Behaviors.WinUI.Managed) is attached to DataTemplate of ListViewItem, instances of bevaviors seems to mixing each other during ListView scroll or collection changed.

### Steps to reproduce the bug

1. Add behavior to ListViewItem's DataTemplate (e.g. for setting bacground)
2. Play with ListView
3. Behaviors are mixed (they seems to modify item's property based on another item binding)

### Expected behavior

Behaviors are sticked to their context

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (1809): Build 17763

**Comment by ranjeshj** [comment]
If Behaviors are coming from community toolkit, please file this bug there. it looks like Behaviors are not accounting for virtualization in ListView.
