### ISSUE TITLE
[WinUI 3] TabView as TitleBar: TabStripFooter glitches out when maximizing Window

### ISSUE THREAD

**Issue by 22ms** [microsoft/microsoft-ui-xaml#8878]
### Describe the bug

When my TabView acting as my TitleBar reaches 8+ TabViewItems, maximizing/snapping causes the TabView.TabStripFooter (which I set to be the TitleBar) to behave unexpectedly. For very small time frame, on maximizing the window, the TabStripFooter moves to the middle of the screen and then immediately snaps to it's expected position. This causes the drag area of the window to move to the middle, resulting loss of control of the headers in that certain area, since the api thinks the drag region should be there. I've changed the color of the TabStripFooter to red to make this bug visible.
Note: the bug does not occur when manually resizing the window. Only maximizing/snapping causes the bug.

### Steps to reproduce the bug

1. Create a blank WinUI 3 project
2. Add a TabView inside of MainWindow.xaml
3. Add 8+ Items in the TabView
4. Create a TabStripHeader and TabStripFooter
5. Set the minimum width of the TabStripFooter to 188 and the background color to red
6. Set the TabStripFooter as the TitleBar inside of the MainWindow.xaml.cs constructor
7. Set ExtendsContentIntoTitleBar = true inside of the MainWindow.xaml.cs constructor
8. Start the application and maximize the window
9. Try moving the window in the middle/try controlling TabViewItem headers in that area

### Expected behavior

The TabStripFooter should stay where its supposed to be on maximizing not overdrawing the TabViewItem headers

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/62474166/9d02e654-6aed-4475-ac8e-f02df4ba63fc

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

MainWindow.xaml

<?xml version="1.0" encoding="utf-8"?>
<Window
    x:Class="BugTest.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:BugTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <TabView x:Name="TabViewMain">
        
        <TabViewItem Header="Test"/>
        <TabViewItem Header="Test"/>
        <TabViewItem Header="Test"/>
        <TabViewItem Header="Test"/>
        <TabViewItem Header="Test"/>
        <TabViewItem Header="Test"/>
        <TabViewItem Header="Test"/>
        <TabViewItem Header="Test"/>

        <TabView.TabStripHeader>
            <Grid x:Name="ShellTitlebarInset" Background="Transparent"/>
        </TabView.TabStripHeader>
        <TabView.TabStripFooter>
            <Grid x:Name="CustomDragRegion" Background="Red" MinWidth="188"/>
        </TabView.TabStripFooter>
    </TabView>
</Window>

MainWindow.xaml.cs:

```
using Microsoft.UI.Xaml;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace BugTest
{
    /// <summary>
    /// An empty window that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            this.SetTitleBar(CustomDragRegion);
            this.ExtendsContentIntoTitleBar = true;
        }
    }
}
```

**Comment by kmgallahan** [comment]
At this time you are responsible for calling `AppWindow.TitleBar.SetDragRectangles` when required to update the non-client area.

WASDK 1.4 introduced `Microsoft.UI.Input.InputNonClientPointerSource` to replace `SetDragRectangles`, but I haven't tried using it yet.
