### ISSUE TITLE
winui2 Programmatically adding NavigationViewItem to NavigationViewItem crash

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#8881]
### Describe the bug

The item is not shown, and making it to conpact mode crashes the app. I mentioned it in #7533 but seems to get ignored. Now as I tried 2.8.5, the issue is still there.

### Steps to reproduce the bug

1. In `MainPage.xaml`,
```xml
    <muxc:NavigationView>
        <muxc:NavigationView.MenuItems>
            <muxc:NavigationViewItem Content="Item1" x:Name="Item"/>
        </muxc:NavigationView.MenuItems>

        <Button Click="Button_Click">Click to add</Button>
    </muxc:NavigationView>
```
2. In code behind
```cpp
void winrt::WinUI2Cpp::implementation::MainPage::Button_Click(winrt::Windows::Foundation::IInspectable const& sender, winrt::Windows::UI::Xaml::RoutedEventArgs const& e)
{
	winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem item;
	item.Content(winrt::box_value(L"subitem"));
	Item().MenuItems().Append(item);
}
```
3. The subitem is not shown.
4. Click the hamburger button to make it compact, app crashes.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/89a446fa-e800-44ee-aac6-da26bce9a634)

### NuGet package version

None

### Windows version

Windows 10 (1809): Build 17763

### Additional context

You don't even bother to update the issue template now? It is WinUI 2.8.5!

**Comment by ojhad** [comment]
This issue is fixed in WinUI3. Closing as Won't Fix for WinUI2 as per this document: https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2
