### ISSUE TITLE
Exceptions thrown from the ThreadPool silently crash apps

### ISSUE THREAD

**Issue by williamfigtree** [microsoft/microsoft-ui-xaml#8885]
### Describe the bug

Any exception thrown from work queued on `System.Threading.ThreadPool` silently crashes the executing app.

The exception is not caught in any of `Application.UnhandledException`, `CoreApplication.UnhandeldErrorDetected`, or `TaskScheduler.UnobservedTaskException`. The debugger also does not report an Unhandled Exception or an application-internal exception in Program.cs.

### Steps to reproduce the bug

1. Create a new dotnet WinUI 3 app.
2. In `App.xaml.cs` constructor, subscribe to the `App.UnhandledException` event.
3. In `MainWindow.xaml.cs` constructor, throw an exception from the `ThreadPool` e.g.

```
ThreadPool.QueueUserWorkItem(x => throw new Exception("bang!"), 1, false);
```
4. Run the app with attached debugger and observe it crash silently without invoking `App.UnhandledException`.

### Expected behavior

`Application.UnhandledException` should be invoked on crash to allow for fatal logging.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

A set of similar issues were addressed in https://github.com/microsoft/microsoft-ui-xaml/issues/5221 and fixed in WinAppSdk 1.2 though this seems to have slipped through.

**Comment by AdriaanLarcai** [comment]
Could this also affect internal .Net classes such as `System.Net.Http.HttpConnectionPool` that rely on `ThreadPool.QueueUserWorkItem`?

If so, then this could theoretically affect an app that relies heavily on web API calls made using an HttpClient.

**Comment by AzureGulf** [comment]
having peppered my code with traps for unhandled exceptions (both system and microsoft.ui.xml), looks like I am experiencing a similar problem:

Exception thrown at 0x00007FFF61B7DE84 (Microsoft.UI.Windowing.Core.dll) in MemoryReadBug.exe: 0xC0000005: Access violation reading location 0x0000000000000030. 
(always at the same address 0x...DE84)

WinUI 3 packaged app and MicrosoftWindowsAppSDK 1.5.231202003-experimental1

Any progress on this bug, release date?? Thanks

**Comment by Scottj1s** [comment]
@williamfigtree Unfortunately, App.UnhandledException can only report exceptions that originate from user code that's invoked by the Windows App SDK runtime.  For ThreadPool crashes, you'll need to also subscribe to System.AppDomain.CurrentDomain.UnhandledException.  This behavior is the same for UWP apps as well as Windows App SDK apps.

**Comment by williamfigtree** [comment]
Thanks @Scottj1s that's solved the issue for me.
