### ISSUE TITLE
Not a Mixed Reality app

### ISSUE THREAD

**Issue by kcovert** [microsoft/microsoft-ui-xaml#8889]
Forgive but no better pigeonhole for this. 

Need help, I recently released a UWP app to the Microsoft store that I developed to not just run in Mixed Reality but do Mixed Reality things. Problem is whoever is making the decision at the MS store has decided it was not a Mixed Reality app because it was a "flat app". So, this person with their definition is telling me to remove the Mixed Reality check in my store submission.

Need to speak with someone in the know please,
Kirk

**Comment by bpulliam** [comment]
Microsoft Store support is a good place to start.

**Comment by kcovert** [comment]
That's where the issues are. I just had to uncheck HoloLens to get the submission approved. I built it for my HoloLens 2. I was hoping someone inside would stand up for UWP and what it was about. No ore MS stores apps for me again after this.

Kirk
