### ISSUE TITLE
AppWindowTitleBar.SetDragRectangles doesn't work in Windows App SDK 1.4.230822000

### ISSUE THREAD

**Issue by Starcloudsea** [microsoft/microsoft-ui-xaml#8901]
### Describe the bug

After updating to Windows App SDK 1.4.230822000, 
`AppWindowTitleBar.SetDragRectangles(new RectInt32[]{new RectInt32(800, 0, ScreenWidth - 80, 40)});`
It no longer has the effect of changing the title bar draggable area, and every time I use this method again, the Windows App SDK uses the default title bar draggable area instead of my customized title bar draggable area.
Hopefully Microsoft can fix this!

### Steps to reproduce the bug

1, Install Windows App SDK 1.4.230822000 NuGet package for your "Blank Project (Packaged)".
2, use` AppWindowTitleBar.SetDragRectangles(new RectInt32[]{new RectInt32(800, 0, 80, 40)});` to set the draggable area of the title bar.
3, run the app, move the mouse to the upper left corner of the app and double click.
4, you will see the app is maximized, which means this method is not working.
5, back to Windows App SDK 1.3.230724000, run the app again, move the mouse to the upper left corner of the app and double click.
6, you will see that the app is not maximized, which means this method worked.

### Expected behavior

Run the app, mouse over the top left corner of the app, double click, the app is not maximized.

### Screenshots

I don't know if there are any problems with these, but I'd like to try to provide them.
![image](https://github.com/microsoft/WindowsAppSDK/assets/84891987/b233ade9-2eec-40bf-a7b8-ebce339a850c)
![image](https://github.com/microsoft/WindowsAppSDK/assets/84891987/288a2c97-bdd0-46b1-877e-c7ca058d1ea1)

### NuGet package version

Windows App SDK 1.4.0: 1.4.230822000

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

### Additional context

By the way, I'm not sure if anyone has mentioned this, and I'm not sure if Microsoft has a replacement method, because I've searched for it many times, and I haven't found any information about it at all, so if there is a replacement method, I hope you guys can let me know, thanks!

**Comment by steam3d** [comment]
@DarranRowe How it use? I also set `AppWindowTitleBar.SetDragRectangles` and it does nothing

**Comment by lhak** [comment]
As stated in the release notes, you might have to call 

```csharp
AppWindow.TitleBar.IconShowOptions = IconShowOptions.HideIconAndSystemMenu
```

to disable the system menu when clicking at the upper left corner of the window.

**Comment by Starcloudsea** [comment]
Hi, I almost forgot about this issue, I already got the answer from Microsoft Q&A a few months ago, but I forgot about this issue, sorry.

Here is the solution from Microsoft Q&A:
https://learn.microsoft.com/en-us/answers/questions/1362230/how-to-fix-appwindow-titlebar-setdragrectangles-no
