### ISSUE TITLE
Exception on application close if text context menu flyout opened (WinUI3 1.3, 1.4)

### ISSUE THREAD

**Issue by Korzhukov** [microsoft/microsoft-ui-xaml#8902]
### Describe the bug

C++ and C# projects. If context menu for any text control is open, application crashes when closed. The crash is silent if the application is not running under a debugger, but is shown in the Application Event Log.

### Steps to reproduce the bug

1. Create standard blank WinUI3 project
2. Open **MainWindow.xaml** and add `<TextBox/>` after `</Button>`
3. Build and launch the application
4. Right-click the TextBox to bring up the context menu.
5. Close the app with **X**

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/28443945/ae62f287-39c8-48d7-944f-6ca3afce25b7

### NuGet package version

WinUI 3 - Windows App SDK 1.4.1: 1.4.230913002

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

I also tried to find a way to close all possible flyouts on close, but couldn't find a way without traversing the entire xaml tree.

**Comment by Korzhukov** [comment]
Questionable workaround:
```

   LRESULT Subclassproc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam, UINT_PTR, DWORD_PTR )
    {
        switch (uMsg)
        {
        case WM_CLOSE:
        {
            static bool realClose = false;
            if (!realClose)
            {
                SetFocus(NULL);
                DispatcherTimer timer;
                timer.Interval(std::chrono::milliseconds(50));
                timer.Tick([&hWnd](IInspectable const&, IInspectable const&) {
                    realClose = true;
                    SendMessage(hWnd, WM_CLOSE, 0, 0);
                    });
                timer.Start();
                return 0;
            }
        }
        }
        return DefSubclassProc(hWnd, uMsg, wParam, lParam);
    }
```

**Comment by Korzhukov** [comment]
You can also see such crashes in PowerToys and WinUI 3 Gallery, but not in Windows 11 native apps.

**Comment by codendone** [comment]
This has the same underlying cause as #8605, with a more direct repro. Resolving as duplicate.

A better workaround might be to listen for Window.Closed and walk through VisualTreeHelper.GetOpenPopupsForXamlRoot() and Close() all of those popups. But this clearly needs to be fixed in the platform.
