### ISSUE TITLE
How can I build for WinUI3 from ui-xaml source?

### ISSUE THREAD

**Issue by takatsuka2022** [microsoft/microsoft-ui-xaml#8929]
I can confirm that there is a memory leak related to ScrollViewer, so I would like to investigate.

**Comment by ghost1372** [comment]
According to what was mentioned in the call yesterday, Source only for 2 namespaces *
The source will only be released for 2 namespaces *microsoft.ui.xaml** and **microsoft.ui.xaml.control** (if I'm not mistaken).
And the release time of the source is after the release of version 1.4.2.
And more importantly, you will not be able to compile, and currently you can only read the codes

**Comment by takatsuka2022** [comment]
I got it.
thank you.

**Comment by ghost1372** [comment]
> I got it. thank you.

also they will publish entire symbols so i think you can do something...

**Comment by dongle-the-gadget** [comment]
Currently, the source code in the repository is for WinUI 2, not WinUI 3.

**Comment by takatsuka2022** [comment]
> also they will publish entire symbols so i think you can do something...
I would like to wait until the symbols are released to the public.

**Comment by takatsuka2022** [comment]
> Currently, the source code in the repository is for WinUI 2, not WinUI 3.

I will wait until the WinUI3 source is released.
