### ISSUE TITLE
WinUI 3 - Unable to click `X` by going to the top right of a maximized window using custom title bar

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/microsoft-ui-xaml#8936]
### Describe the bug

Using this guide to create a tall titlebar: https://learn.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk#system-caption-buttons

### Steps to reproduce the bug

1. Follow this guide to create a custom title bar: https://learn.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk
2. Run the app and maximize the window
3. Drag your mouse to the top right of the screen and see that the `X` button is not activated

https://github.com/microsoft/microsoft-ui-xaml/assets/17648453/43469a6c-2dce-49c1-8cac-be510cde66c3

You can see from this video, my app that uses a tall title bar and PowerToys which uses a regular sized title bar (both with WinUI 3) are unable to click the close caption button when moving the mouse to the very top right of the screen.

Unlike Store (as shown in the capture) that is able to click the `X` button no problem.

### Expected behavior

WinUI 3 apps with custom title bars should accept the mouse in the very top right of the screen and be able to click the close caption button as seen in Store, Settings, and every other WinUI 3 app.

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/17648453/43469a6c-2dce-49c1-8cac-be510cde66c3

### NuGet package version

WinUI 3 - Windows App SDK 1.4.1: 1.4.230913002

### Windows version

Windows 11 (22H2): Build 22621

**Comment by MSEDGE-CORE** [comment]
It might be forgotten to remove window-resizing area in maxmized window. It's also not available to move window by dragging at the very top of the TitleBar.

**Comment by Jay-o-Way** [comment]
I assume this isn't fixed just yet?

**Comment by codendone** [comment]
A fix has been checked in. Using #8665 as the main tracking bug.
