### ISSUE TITLE
PasswordBox reveal 'eye' icon loses alignment when any PasswordBox style resource exists in the project

### ISSUE THREAD

**Issue by Stuart88** [microsoft/microsoft-ui-xaml#8938]
### Describe the bug

Windows 11.

The reveal icon is normally aligned to the right of the input area. 

If any style resource exists for `PasswordBox`, the reveal 'eye' icon aligns to the left and is lost behind the inputted text.

This happens even if the style is not set as a static resource for the control.

### Steps to reproduce the bug

Create default new WinUI app.

Add `PasswordBox` with no styling. 

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23031872/c8337cf0-adc2-4f80-983f-c69a28b91cd1)

The reveal 'eye' icon appears to the right:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23031872/bab4c6e5-0a83-4ecb-acb2-a0c9bf207898)

Create a style resource for the password box. It can contain any styling (or even no styling at all).

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23031872/350beaf2-2108-4c2a-9203-a6584005831c)

There is no need to apply the style as a static resource. Keep `PasswordBox` as default.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23031872/10ff3ad2-8f28-468c-beea-0d8102f1699e)

The reveal 'eye' icon appears to the left behind the password text.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23031872/2196233e-e342-47a2-89b7-0d93baab3e1c)

### Expected behavior

Password reveal icon should remain on the right in its own space.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23031872/842a41cf-03a4-4215-b516-509278d1616a)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.1: 1.4.230913002

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
@Stuart88 you overwrote the default style. Can you try basing your style on top of the default style? The default style is named - DefaultPasswordBoxStyle.

**Comment by Stuart88** [comment]
> @Stuart88 you overwrote the default style. Can you try basing your style on top of the default style? The default style is named - DefaultPasswordBoxStyle.

What's the style property for setting the position of the peek icon?

I would not expect this to happen and there is no documentation pertaining to it.

**Comment by codendone** [comment]
> What's the style property for setting the position of the peek icon?

All of the layout and style of the PasswordBox comes from the `<Style x:Key="DefaultPasswordBoxStyle">` style. Adding `BasedOn="{StaticResource DefaultPasswordBoxStyle}"` to your style will bring in all those defaults.

**Comment by Stuart88** [comment]
> > What's the style property for setting the position of the peek icon?
> 
> All of the layout and style of the PasswordBox comes from the `<Style x:Key="DefaultPasswordBoxStyle">` style. Adding `BasedOn="{StaticResource DefaultPasswordBoxStyle}"` to your style will bring in all those defaults.


Thanks.

I would however still argue that a reveal icon is core styling that should just work, without needing to retrofit something every time a custom styling is applied. 

I can't think of any other components that suffer a UI breakage like that when default styling is overridden - though I haven't tested extensively.
