### ISSUE TITLE
How to properly use OneWay Data Binding in my `WinAppSDK/WinUI3` Desktop Project with `C++/WinRT`?

### ISSUE THREAD

**Issue by shenpengfii** [microsoft/microsoft-ui-xaml#8939]
# Problem Description
Given that there's not an official guidance about how to use Data Binding in  `WinAppSDK/WinUI3` coded with `C++/WinRT`, I have to follow the UWP document of [Data Binding with `C++/WinRT`](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property).  
 
However, **I always see a line of warning**: 
`XamlCompiler warning WMC1506: OneWay bindings require at least one of their steps to support raising notifications when their value changes`. 

# Project Environment
Projected with the latest stable version `Visual Studio Community 2022 17.7.4`.

# Promise to Have Checked
1. In `.idl` file, promise to implement the runtimeclass inheriting the interface `INotifyPropertyChanged`;
2. In `XAML` file, promise to code `{x:Bind ***, Mode=OneWay}`;
3. In `.cpp` file, promise to code:
```cpp
m_propertyChanged(*this, Windows::UI::Xaml::Data::PropertyChangedEventArgs{ L"Content" });
```

## In Details

I've checked out the closest Issue(#7100) from mine, it tells the same as my problem:
> In your output window for Build, did you see a line saying XamlCompiler warning WMC1506: OneWay bindings require at least one of their steps to support raising notifications when their value changes? Did you forget to implement INotifyPropertyChanged?

However, I've implemented the `INotifyPropertyChanged` interface in my project like this:
```IDL
// Message.idl
namespace XXX
{
	runtimeclass Message : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		Message(String content);
		String Content;
	}
}
```
```cpp
// Message.cpp
void Message::Content(hstring const& value)
{
    if (m_content != value) {
        m_content = value;
        m_propertyChanged(*this, Windows::UI::Xaml::Data::PropertyChangedEventArgs{ L"Content" });
    }
}
```
```xaml
<!---MainWindow.XAML--->
<TextBox x:Name="textBoxProducer" 
    Text="{x:Bind MainViewModel.MessageProducer.Content, Mode=OneWay}" .../>
```
Whenever I want to change the text of `TextBox` in runtime like this:
```cpp
MainViewModel().MessageProducer().Content(L"Start Produing...");
```
yet it doesn't work.   
The text of `TextBox` won't change, but an exception would occur to make the app crash.

**Comment by tux2nicolae** [comment]
I'm having the same issue, can you provide more info on how do you fixed it?
