### ISSUE TITLE
Password Box Not Showing OnScreen Keyboard when activiated via touch

### ISSUE THREAD

**Issue by JJBrychell** [microsoft/microsoft-ui-xaml#8946]
### Describe the bug

Activating a password box using on a touch device does not show the on screen keyboard.

### Steps to reproduce the bug

On a touch device (or using properly configure touch emulator)

1. Open WinUI 3 gallery
2. Navigate to the PasswordBox Page
3. Using Touch Place focus into a Password Box

### Expected behavior

That the on screen keyboard would be displayed

### NuGet package version

WinUI 3 - Windows App SDK 1.4.1: 1.4.230913002

### Additional context

This issue is being split off of #6291 as that issue has been fixed, which in turn exposed a completely different issue with password boxes.

Tagging the following users from that thread:  @JanRajnoha, @elliotdennis, @WalkaZxamlem

**Comment by JJBrychell** [comment]
We know the cause of this, but it it is going to be a challenge to fix.

**Comment by WalkaZxamlem** [comment]
Hi guys, as it is closed I wanted to confirm when it will be released? ;)

**Comment by JanRajnoha** [comment]
Is it released? I don't see anything in release notes for latest releases (including 1.4.3).

**Comment by codendone** [comment]
@JanRajnoha This fix unfortunately didn't make it into 1.4.3. It should be in the next servicing release.
