### ISSUE TITLE
Discussion: Inner and Outer Borders for Flyouts and Elevated Acrylic surfaces

### ISSUE THREAD

**Issue by mdtauk** [microsoft/microsoft-ui-xaml#895]
# Discussion: Inner and Outer Borders for Flyouts and Elevated Acrylic surfaces

![Flyout Designs](https://user-images.githubusercontent.com/7389110/59730025-b4c2cd00-9238-11e9-9a3c-de4993f66520.png)

## Summary
Inner and Outer Borders used to help Flyouts and other elevated surfaces to stand out in both Light and Dark Themes more so than at present.

## Rationale
Elevated surfaces have been introduced to Fluent Design with the use of **ThemeShadow** and projected depth shadows.

With the Dark Theme these shadows are easily lost, and so I believe there should be more visual affordance for this, which would also work with High Contrast themes, by including an inner border which can be given a strong outline colour.

![image](https://user-images.githubusercontent.com/7389110/59733833-1d18ab00-9247-11e9-8bfa-d817641c22ad.png)

## Scope
| Capability | Priority |
| :---------- | :------- |
| Elevated visual borders should adapt to High Contrast themes | Must |
| Elevated visual borders should use ThemeResources for consistency | Should |
| Menu, DropDown, and Button Flyouts as well as Picker Flyouts would use the same style | Could |

## Examples
![Flyout Examples](https://user-images.githubusercontent.com/7389110/59732691-3a4b7a80-9243-11e9-845c-ccdec441d7e9.png)

## Open Questions
I believe the dark outer border re-enforces the elevation, and in my mockups would fall 1 pixel outside of the bounding box.  The inner border alone will help, but are there any problems this would cause, which I am not aware of?

Do elevated dark surfaces need to lighten with their increased elevation as with Android Q's forthcoming Dark Mode - or does the inner border alone create enough of a cue?

Are there any particular flyouts which should avoid using this style, if they were to become the new default for flyouts?

**Comment by chigy** [comment]
### **Status update:**
Bringing this to the design team's attention.

**Comment by chigy** [comment]
### Status update

Turning this into a "Discussion" category since there is no known immediate plan to look at flyout design.

**Comment by mdtauk** [comment]
I think much of this has been covered by the WinUI 2.6 update, so I am closing this issue!

https://docs.microsoft.com/en-us/windows/apps/design/style/mica#app-layering-with-mica
