### ISSUE TITLE
PRI175 : Duplicate Entry

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#8959]
### Describe the bug

Installed Prism 9 pre and having the nugets beneath : 

```
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI" Version="7.1.2" />
    <PackageReference Include="DryIoc.dll" Version="5.4.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Uno.WinUI" Version="2.0.0-rc1.2" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.4.230913002" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
    <PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageReference Include="Uno.Extensions.Hosting.WinUI" Version="3.0.0-dev.2304" />
    <PackageReference Include="Uno.WinUI" Version="5.0.0-dev.3403" />
    <PackageReference Include="WinUIEx" Version="2.3.1" />
    <PackageReference Include="Prism.DryIoc.Uno.WinUI" Version="9.0.271-pre" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
```

<img width="809" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/43340959/d80227c8-5d68-4358-81b3-48e27e65b8c4">

### Steps to reproduce the bug

F5

### NuGet package version

WinUI 3 - Windows App SDK 1.4.1: 1.4.230913002

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Perhaps it is an UNO issue ?

**Comment by sigmarsson** [comment]
`WINAPPSDKGENERATEPROJECTPRIFILE : error : PRI277: 0x80073b0f - Conflicting values for resource 'Files/Uno.UI.Toolkit/Themes/Generic.xbf'`

**Comment by michael-hawker** [comment]
I'm seeing this issue with UWP app trying to upgrade WinUI versions - see https://github.com/microsoft/microsoft-ui-xaml/issues/3672#issuecomment-1906878702 - I'm already on VS 17.8.4 though.

Trying the `<DisableEmbeddedXbf>false</DisableEmbeddedXbf>` mentioned in the VS thread... though not sure the ramifications of this; however, it didn't work. So back to the original issue where I can't upgrade from 2.7.3 (as I'm seeing a catastophic failure with AnimatedIcon unloading, so wanted to check against latest).

**Comment by evelynwu-msft** [comment]
Very likely same as #8857
