### ISSUE TITLE
Proposal: Add flexbox layout panel

### ISSUE THREAD

**Issue by kmelmon** [microsoft/microsoft-ui-xaml#896]
# Proposal: Add flexbox layout panel

## Summary
The flexbox layout is super popular with web developers, and is also used by react-native.
This proposes we add a new kind of panel to XAML that supports flexbox directly.

## Rationale

* Very powerful layout that's already popular with a large web community
* Would provide significant value to react-native-windows implementation which currently implements flexbox "outside" XAML

## Important Notes

See related issues in react-native-windows repo:  
https://github.com/microsoft/react-native-windows/issues/2642
https://github.com/microsoft/react-native-windows/issues/2643

**Comment by micahl** [comment]
@kmelmon check out #694.

**Comment by YuliKl** [comment]
Resolving as a dupe. @kmelmon, please reactivate if you disagree.
