### ISSUE TITLE
Exception makes the App crash when using OneWay Data Binding in `Windows App SDK/WinUI3` Desktop Project with `C++/WinRT`.

### ISSUE THREAD

**Issue by shenpengfii** [microsoft/microsoft-ui-xaml#8972]
### Describe the bug

I want to make a `Windows App SDK` Desktop Application with `C++/WinRT`, but I couldn't find an appropriate official document. 

And I have to follow the `UWP` document to implement the function of [Data Binding with `C++/WinRT`](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property).  

Based on those steps, I made a few changes to fit my `Windows App SDK` project. But whenever I launch the App, it crashes with an exception: 
```
The application called an interface that was marshalled for a different thread.
```

### Steps to reproduce the bug

I've inherited the `INotifyPropertyChanged` interface in my project like this:
```IDL
// BookSku.idl
namespace Bookstore
{
    runtimeclass BookSku : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        BookSku(String title);
        String Title;
    }
}
```
```cpp
// BookSku.cpp
void BookSku::Title(winrt::hstring const& value)
{
    if (m_title != value)
    {
        m_title = value;
        m_propertyChanged(*this, Windows::UI::Xaml::Data::PropertyChangedEventArgs{ L"Title" });
    }
}
```
```xaml
<!---MainWindow.XAML--->
 <Button Click="ClickHandler" Content="{x:Bind MainViewModel.BookSku.Title, Mode=OneWay}"/>
```
Whenever I want to change the `Content` attribute of my `Button` in runtime like this:
```cpp
// MainWindow.cpp
void MainWindow::ClickHandler(Windows::Foundation::IInspectable const& sender, Microsoft::UI::Xaml::RoutedEventArgs const& args)
{
  MainViewModel().BookSku().Title(L"To Kill a Mockingbird");
}
```
It just couldn't work!

### Expected behavior

When clicking the button, the `Content` attribute of button would change from the original to `To Kill a Mockingbird` as above code.

### NuGet package version

Windows App SDK 1.4.1: 1.4.230913002

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by codendone** [comment]
From your example:
> m_propertyChanged(*this, Windows::UI::Xaml::Data::PropertyChangedEventArgs{ L"Title" });

This should use **Microsoft**::UI::Xaml:.. instead of **Windows**.
