### ISSUE TITLE
Unable to set ItemsRepeater.TabFocusNavigation via Style

### ISSUE THREAD

**Issue by garrettpauls** [microsoft/microsoft-ui-xaml#8979]
### Describe the bug

Attempting to set `ItemsRepeater.TabNavigationStyle` to `Local` through a Style doesn't work. Setting it directly produces the expected behavior.

### Steps to reproduce the bug

Create a new WinUI application, update WindowsAppSDK to the latest version (currently 1.4.231008000), then add the following to MainWindow:

`MainWindow.xaml`
```
<Window
	x:Class="WinUIBug.MainWindow"
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

	<StackPanel Orientation="Vertical" Spacing="8">
		<StackPanel.Resources>
			<DataTemplate x:Key="ItemsRepeaterItemTemplate">
				<Button Content="{Binding}" Width="100" />
			</DataTemplate>
			<Style TargetType="ItemsRepeater" x:Key="ItemsRepeaterStyle">
				<Setter Property="ItemTemplate" Value="{StaticResource ItemsRepeaterItemTemplate}" />
				<Setter Property="TabFocusNavigation" Value="Local" />
			</Style>
		</StackPanel.Resources>

		<Button Content="ItemsRepeater with TabFocusNavigation set directly:" HorizontalAlignment="Stretch" />

		<ItemsRepeater 
			ItemsSource="{x:Bind Values}"
			ItemTemplate="{StaticResource ItemsRepeaterItemTemplate}" 
			TabFocusNavigation="Local" />

		<Button Content="ItemsRepeater with TabFocusNavigation set via Style:" HorizontalAlignment="Stretch" />

		<ItemsRepeater
			ItemsSource="{x:Bind Values}"
			Style="{StaticResource ItemsRepeaterStyle}" />

		<Button Content="Outside Items Repeater" HorizontalAlignment="Stretch" />
	</StackPanel>
</Window>
```

`MainWindow.xaml.cs`
```
using System.Collections.ObjectModel;
using Microsoft.UI.Xaml;

namespace WinUIBug;

public sealed partial class MainWindow : Window
{
	public MainWindow()
	{
		InitializeComponent();
	}

	public ObservableCollection<string> Values { get; } = new () {"One", "Two", "Three"};
}
```

### Expected behavior

I expect both `ItemsRepeater` controls to exhibit `TabFocusNavigation="Local"`, allowing the user to tab from the button before the repeater, through each button in the repeater, and then to the next button after the repeater.

The first ItemsRepeater behaves as expected, because TabFocusNavigation=Local is set directly.

The second ItemsRepeater exhibits the default TabFocusNavigation behavior (Once) instead of the expected behavior (Local) which should have been set by the Style. The user is only able to tab to the first button in the repeater, and then tab moves directly to the control after the repeater.

### Screenshots

![ItemsRepeaterTagFocusNavigationBug](https://github.com/microsoft/microsoft-ui-xaml/assets/670089/d6b78e50-8939-4bb5-8485-be743588c73c)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ranjeshj** [comment]
ItemsRepeater sets the TabFocusNavigation in its constructor. Unfortunately, that writes it as 'local' value for the dependency property. That takes precedent over a style set value. That is what is tripping this up. There isn't an easy way to fix this, some options include.
1. add support for setting the property with more granularity as local or style set value.
2. make items repeater have a default style. only controls support that now, and ItemsRepeater is not a control.
Neither of these are simple fixes.

A few workarounds include
1. Add an attached property that sets the TabFocusNavigation property locally (in code).
2. Derive from ItemsRepeater and update the property in ctor.
