### ISSUE TITLE
Derived AppBarButton is broken; sizing problems

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#8986]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Derived-AppBarButton-is-broken;-sizing-p/10491605)._

---
[severity:I'm unable to use this version]
Deriving from AppBarButton results in incorrect display of the button both in the primary command area and in the secondary command area. 

Steps to reproduce: Create an WinUI 3 packaged desktop app, and add the following class -- 

public class DerivedAppBarButton : AppBarButton {}

Then add the following to your main window (within a StackPanel for example)

```
<CommandBar>
    <CommandBar.PrimaryCommands>
        <AppBarButton Icon="Like" Label="Built-In"/>
        <local:DerivedAppBarButton Icon="Like" Label="Derived"/>
     </CommandBar.PrimaryCommands>
     <CommandBar.SecondaryCommands>
         <AppBarButton Icon="Like" Label="Built-In"/>
         <local:DerivedAppBarButton Icon="Like" Label="Derived"/>
     </CommandBar.SecondaryCommands>
</CommandBar>
```

Run the program and hover over each of the two buttons in the primary button region. Observe that the background shown for the derived button is taller than the built-in button and also taller than the secondary/overflow menu button ("..."). 

Now expand the secondary menu and hover over each button. Observe that the background shown for the derived button is narrower than the built-in button, indeed the label is cut off. As well the background shown for the derived button is flush to the left edge of the overflow list, while the background for the built-in button has a margin.

Expected behavior is that the derived button should behave exactly the same as the built-in button. 

---
#### Feedback Bot on 10/15/2023, 08:28 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by ranjeshj** [comment]
This is likely because the derived type does not get the correct style, same as this bug https://github.com/microsoft/microsoft-ui-xaml/issues/4325
