### ISSUE TITLE
Two runtimeclass with same property name but differnent type cause function template already defined error

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#8994]
### Describe the bug

Two controls with same property name but with differnent type, cause function template already defined compilation error in C++WinRT.

### Steps to reproduce the bug

1. Create a C++WinRT UWP project (~~maybe exist in WinUI3 C++WinRT project too, didn't check~~, WinUI3 fixed in #5395 )
2. Create two templated control, with these idl.
```
namespace UWPCpp2
{
    [bindable]
    [default_interface]
    runtimeclass ViewModel1 : Windows.UI.Xaml.Controls.Control
    {
        ViewModel1();
        String MyProperty;
    }
}
```
```
namespace UWPCpp2
{
    [bindable]
    [default_interface]
    runtimeclass ViewModel2 : Windows.UI.Xaml.Controls.Control
    {
        ViewModel2();
        Object MyProperty;
    }
}
```
3. Build the project, you get compilation error.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/2e33719a-2ee7-4ce1-a550-6666b91eed87)

### NuGet package version

None

### Windows version

Windows Insider Build (xxxxx)

### Additional context

Somewhat related issue: #7313 , still not getting fixed after 1.5 year. Seems hopeless for code-gen issues getting fixed.

**Comment by HO-COOH** [comment]
Just found out, this does not even need to be a `Control`, just any `runtimeclass` and the issue happens.

**Comment by JesseCol** [comment]
Thanks!  I see this is fixed in WinUI3.  Unfortunately, we are not currently investigating WinUI2 issues that are not business or security critical (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).
