### ISSUE TITLE
Using AccessKey to Close Window Causes Exception

### ISSUE THREAD

**Issue by johnt-star** [microsoft/microsoft-ui-xaml#9002]
### Describe the bug

If a button is used to close a window, everything works as expected.

However, if an AccessKey is assigned to the button, then the AccessKey is invoked to close the window, an exception occurs. 
![Exception](https://github.com/microsoft/WindowsAppSDK/assets/77626323/5b766a02-bff8-4420-8438-114064c2c6ea)

### Steps to reproduce the bug

[AccessKey.zip](https://github.com/microsoft/WindowsAppSDK/files/13030209/AccessKey.zip)

Project file included to demonstrate issue.

1) In main window, add a button that when tapped, launches a second window.
2) In second window, add a button that when tapped, closes the second window.
3) In second window, add an AccessKey for the button, that when invoked, also closes the second window.

### Expected behavior

Using AccessKey to close window should not cause exception and should work the same way as tapping corresponding button.

### Screenshots

![MainWindow](https://github.com/microsoft/WindowsAppSDK/assets/77626323/2d88645e-3292-4c49-bc24-2384940c1b8b)
![MainWindowXaml](https://github.com/microsoft/WindowsAppSDK/assets/77626323/ec7f39d4-7c01-48b2-8024-3afae8dcdd19)
![SecondWindow](https://github.com/microsoft/WindowsAppSDK/assets/77626323/e1137171-b26f-4e58-a1ca-f1412021fb2d)

Some code screen shots - project attached in zip file

### NuGet package version

Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by JJBrychell** [comment]
After and access key is triggered, we will sometimes attempt to reset focus, but if the page is destruction, things can get confused.

The fix is in and scheduled for 1.5.
