### ISSUE TITLE
Can't get the KeyDown event when pressing [Ins] Key

### ISSUE THREAD

**Issue by yangxiaopo** [microsoft/microsoft-ui-xaml#9025]
### Describe the bug

Can't get the KeyDown event when pressing [Ins] Key.
Also see https://learn.microsoft.com/en-us/answers/questions/1375737/winui3-how-to-get-insert-overwrite-in-winui3-textb

### Steps to reproduce the bug

1.Add a KeyDown event on a WinUI3 TextBox.
2.Can't get the KeyDown event when pressing [Ins] Key.

### NuGet package version

None

**Comment by gegao18** [comment]
Thanks for reporting this. This is by design since TextBox itself uses and handles the Insert key. You should be able to get it from PreviewKeyDown. Let us know if that's not the case.
