### ISSUE TITLE
A click doesn't trigger the AutoSuggestBox.SuggestionChosen Event 

### ISSUE THREAD

**Issue by yangxiaopo** [microsoft/microsoft-ui-xaml#9026]
### Describe the bug

The chosen item doesn't show in AutoSuggestBox.
Also see https://learn.microsoft.com/en-us/answers/questions/1374937/why-autosuggestbox-need-click-more-than-1-time-to

### Steps to reproduce the bug

\<AutoSuggestBox x:Name="Control1" TextChanged="AutoSuggestBox_TextChanged"
                        SuggestionChosen="AutoSuggestBox_SuggestionChosen" Width="300" 
                                AutomationProperties.Name="Basic AutoSuggestBox"
                                QuerySubmitted="AutoSuggestBox_QuerySubmitted"
                                QueryIcon="Find"
                                GotFocus="AutoSuggestBox_GotFocus"/>

private void AutoSuggestBox_GotFocus(object sender, RoutedEventArgs e)
        {
            AutoSuggestBox box = (sender as AutoSuggestBox);
            box.ItemsSource = Cats;
            box.IsSuggestionListOpen = true;
        }
1.click the find icon
2.choose a suggested item
3.there is nothing in the AutoSuggestBox

### Screenshots

https://imgur.com/a/nYGgkNE

### NuGet package version

None

**Comment by gegao18** [comment]
Thanks for reporting this. Have you tried the QuerySubmitted event work as a workaround?

**Comment by ranjeshj** [comment]
Please reactivate if Query Submitted does not work for you.
