### ISSUE TITLE
AutoSuggestBox VisualState Foreground issue

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/microsoft-ui-xaml#9029]
### Describe the bug

AutoSuggestBox does not switch back its `Foreground` after pointer exit.
It does switch back its `Foreground` after losing focus but not when the inside text is selected.
Check the XAML and the video below:

```xaml
<StackPanel
    HorizontalAlignment="Center"
    VerticalAlignment="Center"
    Orientation="Horizontal"
    Spacing="10">
    <TextBox
        Foreground="Blue"
        Header="TextBox"
        Text="ABCDE" />
    <AutoSuggestBox
        Foreground="Blue"
        Header="AutoSuggestBox"
        Text="ABCDE" />
</StackPanel>
```

https://github.com/microsoft/microsoft-ui-xaml/assets/80524586/3357da19-10eb-409f-a6fc-8287785b0210

### Steps to reproduce the bug

Use the code above or check this [repo](https://github.com/AndrewKeepCoding/AutoSuggestBoxForegroundIssue).

### Expected behavior

AutoSuggestBox should switch back its `Foreground` after pointer exit.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

**Comment by karkarl** [comment]
Fixed in internal PR: 10250839
