### ISSUE TITLE
Application/startups

### ISSUE THREAD

**Issue by DIEGOHJJACOBO** [microsoft/microsoft-ui-xaml#9033]
[Windows.Foundation.Metadata.ContractVersion(typeof(Windows.Foundation.UniversalApiContract), 65536)]
[Windows.Foundation.Metadata.Guid(2824267380, 45238, 19395, 187, 168, 27, 160, 110, 64, 212, 181)]
public delegate void RoutedEventHandler(object sender, RoutedEventArgs e);

**Comment by bpulliam** [comment]
not currently actionable.  please provide more details
