### ISSUE TITLE
[Checkbox] Focus size is incorrect for no-label checkboxes

### ISSUE THREAD

**Issue by ToukZ** [microsoft/microsoft-ui-xaml#9035]
### Describe the bug

When using the checkbox component, setting no label or contents for it will cause the Focus visual to not display properly, highlighting more space than it should.

While having a no-label checkbox is debatable UI design-wise, one could want to have it's label be displayed elsewhere - like on top or below the checkbox.

I tried using the **"FocusVisualMargin"** aswell to limit the empty focus space, but that overrides the CornerRadius.

### Steps to reproduce the bug

1. Create a no-label Checkbox
2. Repeatably press Tab until the Checkbox created in **1.** is in Focus
3. See Error

### Expected behavior

FocusVisual space should adapt to highlight only the checkbox incase where there is no label or contents inside of it.

"FocusVisualMargin" should not override the CornerRadius for the FocusVisual of the component.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/58863075/2812cbc5-640c-418f-80f9-b4e16a7a5ab4)
(No-label checkbox with big FocusVisual empty space)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/58863075/61768f91-2560-4cd3-9e2a-e32912873e55)
(FocusVisualMargin overrides the CornerRadius of the component)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by ranjeshj** [comment]
CheckBox has a default min width. you can reduce the MinWidth property to modify that behavior.

**Comment by ToukZ** [comment]
Tried setting both `MinWidth` and `MinHeight` properties to 0 (and many other values) to validate this solution, but was met up with this:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/58863075/2d865f6d-bf7a-4c57-a4e6-6e0c12db3e82)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/58863075/68dd37d4-b051-4e60-88e7-0eba9a653609)

I still do not think that it looks quite right, the FocusVisual should neatly 'hug' the checkbox, like concentric circles.
