### ISSUE TITLE
Hololens 2 ComboBox: 2 identical string items freeze the app

### ISSUE THREAD

**Issue by khelkun** [microsoft/microsoft-ui-xaml#9037]
### Describe the bug

Put at least 2 identical string items in  [Windows.UI.Xaml.Controls.ComboBox](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox) for UWP mixed reality application on the Hololens 2 device, then open the drop down and try to scroll a bit in the item list. It does not throw an exception but freezes the application.

### Steps to reproduce the bug

1. Create a UWP app for hololens.
2. Add a [Windows.UI.Xaml.Controls.ComboBox] and inject 2 identical string items into it.
3. Deploy to the Hololens 2 device.
4. Run the app on the Hololens 2 device, then open the combo box drop down.
5.Try to scroll, or just over cursor, into the drop down list.
6. The app should be freezed and does not throw an exception.

### Expected behavior

no freeze

### NuGet package version

Microsoft.NETCore.UniversalWindowsPlatform/6.2.9

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

OS Build 22621.1244 Edition Windows Holographic For Business
Application build configuration: Debug or Release
Application build architecture: ARM or ARM64

**Comment by khelkun** [comment]
Actually I may have mis assumed the freeze is due to the high item count, I'll re-open if I have better report details

**Comment by khelkun** [comment]
Re-open because I think I've identified the root cause, so I modified title and description

**Comment by ranjeshj** [comment]
Sorry, this currently does not meet the bar for fixing in WinUI2. See https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2

**Comment by khelkun** [comment]
@ranjeshj ok fair enough, thanks for the feedback
