### ISSUE TITLE
scrollviewer will auto scroll to top when activate the window

### ISSUE THREAD

**Issue by ljzj2** [microsoft/microsoft-ui-xaml#9039]
### Describe the bug

when I scroll down the scrollviewer and open other program and re-open the window by tab+alt or click the icon in taskbar
the scrollviewer will return to top automatically.

sometimes in the window I click white space it will scroll to top too.

### Steps to reproduce the bug

1. create packaged project
2. create new Window
3. set the new window to modal:presenter.IsModal=true;
4. Activate the new window
5. create some textbox and a grid and add many controls to the grid
6. alt+tab or click white space of your desktop
7. re alt+tab or click the icon in taskbar to open.
8. you will find the bug
9. if you first create the control to the grid and you click the white space in the window it will scroll to top too.
10. if you close the modal window the original button (or other control) can not be clicked and you have to wait some seconds.

### Expected behavior

1.do not scroll
2.when I close the modal the parent window control can clicked.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/110752116/82cf28e1-ac92-4be7-a5a9-6db7f08ae419)

### NuGet package version

None

**Comment by ranjeshj** [comment]
@ljzj2 when the window gets activated, focus lands on the last focused element in that window. If the last focused element is scrolled away, then it will be brought into focus. Is that what you are seeing? That is by design. 

If that is not the case, please attach the repro project.

**Comment by ljzj2** [comment]
@ranjeshj  not only window gets activated. If I just scroll to bottom then click the white space. it will auto scroll to top too.

**Comment by ranjeshj** [comment]
@ljzj2 yes, that is the same case where the scrollviewer gets focus and puts focus on the first focusible element. That is by current design.
