### ISSUE TITLE
Syntax error when using ICompositionSupportsSystemBackdrop.SystemBackdrop() 

### ISSUE THREAD

**Issue by Bobby-Ling** [microsoft/microsoft-ui-xaml#9041]
### Describe the bug

When I tryied using code like 
```C++
myICompositionSupportsSystemBackdrop.SystemBackdrop(myCompositionBackdropBrush) 
```
VS2022 says 
```
E0304 No instance of overloaded function "winrt::Microsoft::UI::Composition::ICompositionSupportsSystemBackdrop::SystemBackdrop" 
```
I have created a new winUI3 C++ project using Windows App SDK 1.4.2, cpp/winrt version 2.0.220929.3, and included no header files other than those provided in `pch.h`.

Code behind works fine in C#:
```C#
public static void SetTransparent(Window window)
{
    var brushHolder = window.As<ICompositionSupportsSystemBackdrop>();
    var colorBrush = WindowsCompositionHelper.Compositor.CreateColorBrush(Windows.UI.Color.FromArgb(0, 255, 255, 255));
    brushHolder.SystemBackdrop = colorBrush;
}
```
My C++ code is as follows: (see **Steps to reproduce the bug**)

### Steps to reproduce the bug

1. Create a new C++ winUI3 (packaged) project
2. Include header files:
```cpp
#include <winrt/Microsoft.UI.Composition.SystemBackdrops.h>
#include <winrt/Windows.System.h>
#include <dispatcherqueue.h>
```
3. Paste code below in any function (I've done nothing else apart from this)
```cpp
using namespace Microsoft::UI::Composition;
using namespace Windows::System;//for DispatcherQueue
ICompositionSupportsSystemBackdrop mySysBackDrop;
Microsoft::UI::Composition::Compositor myCompositor;
CompositionBackdropBrush myBackdropBrush = myCompositor.CreateBackdropBrush();
mySysBackDrop.SystemBackdrop(myBackdropBrush);
```
4. Than there is an reload error in the picture below
5. Notice: It reports a **syntax** error, so I **omitted** unnecessary parts like **DispatcherQueue** and the code to create a CreateBackdropBrush is **not correct**. What I'm wondering is that inexplicable **syntax** error.

### Expected behavior

No syntax error

### Screenshots

![image_66](https://github.com/microsoft/microsoft-ui-xaml/assets/113997895/a64d2e35-1899-45ab-9b20-6a952fe27129)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by DarranRowe** [comment]
Basically, you went for the wrong compositor.
If we have a look at the IDL for ICompositionSupportsSystemBackdrop:
```
[contract(Microsoft.Foundation.WindowsAppSDKContract, 1.1)]
[uuid(397DAFE4-B6C2-5BB9-951D-F5707DE8B7BC)]
interface ICompositionSupportsSystemBackdrop : IInspectable
{
    [propget] HRESULT SystemBackdrop([out] [retval] Windows.UI.Composition.CompositionBrush** value);
    [propput] HRESULT SystemBackdrop([in] Windows.UI.Composition.CompositionBrush* value);
 }
```
This is a bit verbose, but it makes this very clear. The type of the property is **Windows.UI.Composition**.CompositionBrush. If you then look at your own code, you are using **Microsoft.UI.Composition**. These are not the same.
There is an issue with the documentation where two of the three CompositionBrush links will link to Microsoft.UI.Composition.CompositionBrush, but this is a mistake in the documentation.

**Comment by Bobby-Ling** [comment]
Thank you very much! Hope it will help those who are misleaded.
