### ISSUE TITLE
TreeView throws exception occasionally when expanding/collapsing

### ISSUE THREAD

**Issue by GuildOfCalamity** [microsoft/microsoft-ui-xaml#9046]
### Which version of the app?

WinUI 3 Gallery

### Description

While testing the TreeView control it can trigger the UnhandledException catch.

### Screenshots

![image](https://user-images.githubusercontent.com/81915293/230730407-5bb89274-edb0-4e6d-a744-0aa7161b9e24.png)

![image](https://user-images.githubusercontent.com/81915293/230730416-c4f72d5f-51b2-4e66-bca8-55598e7bba40.png)

### Windows version

November 2021 Update/21H2 (19044)

### Additional context

Using Visual Studio version 17.6.0 (Preview version 2.0)

[Packages/Nugets]
Microsoft.Windows.CsWinRT version 2.0.1
Microsoft.WindowsAppSDK version 1.2.230217.4

**Comment by ranjeshj** [comment]
I'm not able to repro this issue. @GuildOfCalamity can you provide more details? On latest WinUI3 gallery, I don't see the crash.
