### ISSUE TITLE
Why did you delete the repo?

### ISSUE THREAD

**Issue by pluto-dev** [microsoft/microsoft-ui-xaml#9052]
### Describe the bug

I just need to ask, why? [aac7a6d](https://github.com/microsoft/microsoft-ui-xaml/commit/aac7a6ddf1b21a4aa72f3f8eea93745f5ba86f93)

It makes it harder to search the repo through Github, and for me it was just super confusing.

### Steps to reproduce the bug

...

### NuGet package version

None

### Windows version

Windows Insider Build (xxxxx)

**Comment by DarranRowe** [comment]
They didn't. The WinUI 2 source is available under the [WinUI2/Main](https://github.com/microsoft/microsoft-ui-xaml/tree/winui2/main) branch while the WinUI 3 source is available under [WinUI3/Release/1.4-stable](https://github.com/microsoft/microsoft-ui-xaml/tree/winui3/release/1.4-stable).

**Comment by joelspadin** [comment]
This makes it nearly impossible to search the repo for anything, because GitHub only seems to index the default branch.

**Comment by evelynwu-msft** [comment]
Apologies for how long it took us to get things in place. Beginning with the 1.5.5 release, the source code for the latest (i.e. highest major.minor.patch) non-experimental release can always be found in [`main`](https://github.com/microsoft/microsoft-ui-xaml/tree/main/src) in addition to the usual `winui3/release/` release branch.
