### ISSUE TITLE
Source-link not pointing to Github

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#9055]
### Describe the bug

When you debug WinUI 3 source with symbols, you're required to first clone the repo making sure you get the correct tag, and point it to the location of the source.
However Source linking should take care of this, and this was previously fixed for WinUI 2:
https://github.com/microsoft/microsoft-ui-xaml/pull/5687

Could you please apply that fix to the WinUI 3 source as well, so when you build it'll create symbols that points to the correct tag/commit here? This will greatly simplify debugging WinUI3.

### Steps to reproduce the bug

Debug WinUI 3 without WinUI 3 source on disk.

### Expected behavior

Source code is automatically downloaded.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by riverar** [comment]
@llongley When closing issues, it's customary to provide a reason or other text to close the loop. (see also [previous instance](https://github.com/microsoft/microsoft-ui-xaml/issues/5727#issuecomment-1702371193) of same behavior)

**Comment by dotMorten** [comment]
@llongley Can you please explain how this was addressed? I'm not seeing source links working. When I double-click the callstack after loading the v1.5 symbols, source isn't being pulled from github:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/1378165/365fb286-91df-485d-976f-43edc7133871)

**Comment by evelynwu-msft** [comment]
> @llongley When closing issues, it's customary to provide a reason or other text to close the loop. (see also [previous instance](https://github.com/microsoft/microsoft-ui-xaml/issues/5727#issuecomment-1702371193) of same behavior)

Thanks for the reminder! We can and will do better about adding additional information and context before closing an issue.

**Comment by evelynwu-msft** [comment]
> @llongley Can you please explain how this was addressed? I'm not seeing source links working. When I double-click the callstack after loading the v1.5 symbols, source isn't being pulled from github: ![image](https://private-user-images.githubusercontent.com/1378165/309845349-365fb286-91df-485d-976f-43edc7133871.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTAzMTcsIm5iZiI6MTcwOTY5MDAxNywicGF0aCI6Ii8xMzc4MTY1LzMwOTg0NTM0OS0zNjVmYjI4Ni05MWRmLTQ4NWQtOTc2Zi00M2VkYzcxMzM4NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDE1MzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc0NjdjNGM0MzUwN2NkMTA3MmY1ZmNhODhjMDAxMDYyMWMxNDczNDUxNDMwN2IxYzhhNTk4NzAwYWYyYzJmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Nmvs1Ep-hFOOHqI8vlhFpphWtqRIEt_QlPZJLQ-pBAk) Not until I point it to a local clone of the repo does this start working

@dotMorten As a sanity check, can you verify that you have source server support enabled in Visual Studio? I just double checked this scenario and it worked for me.
<img width="533" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/50890554/75841075-a4f5-4c4a-b9ba-f924a9a35893">

**Comment by dotMorten** [comment]
Cleared my symbol cache and tried again. Seem to work now! Not sure why it didn't the other day. 🥳🍾

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/1378165/e0b3c94c-f81e-4636-bef0-b17e7a231d65)
