### ISSUE TITLE
Proposal: Add IsReadOnly property to NumberBox

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/microsoft-ui-xaml#9056]
# Proposal: Add IsReadOnly property to NumberBox

## Summary

The `TextBox` control has `IsReadonly` but the `NumberBox` doesn't.

## Rationale

There are cases when you want to switch if the `NumberBox` is read-only or not. We can make the `NumberBox` read-only with the `IsEnabled` property but it makes the look grayed out and makes the value unselectable thus unenabled for copying the value to clipboard.

**Comment by danielgruethling** [comment]
This was already proposed in #2204 three years ago with no progress yet. There is a workaround using the visual tree but it does not work correctly as shown in #8752.

**Comment by AndrewKeepCoding** [comment]
@danielgruethling Thanks for pointing it out. Closing this as duplicate.
