### ISSUE TITLE
state/province field not accepted on developer registration page 

### ISSUE THREAD

**Issue by XLynLi** [microsoft/microsoft-ui-xaml#9066]
### Describe the bug

While I register a developer account,
on Registration - Account info page, after click next button, state/province filed is highlighted as not valid.
I try many times, but got the same result. Sometime the page show Error code 2201

### Steps to reproduce the bug

1. Go to https://partner.microsoft.com/en-us/dashboard/Registration/AccountInfo?pageName=CP_AccountInfo&navType=next
2. enter infomation
3. Click next

### Screenshots

![register_dev_error](https://github.com/microsoft/microsoft-ui-xaml/assets/150407741/0caaee6c-68b7-4c3b-9f54-3f4c6ecd6940)

### NuGet package version

None

**Comment by ranjeshj** [comment]
Sorry, this is unrelated to the winui repo.
