### ISSUE TITLE
Proposal: Disable System ContextMenu for Custom TitleBar

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#9072]
System ContextMenu Should be Disabled for Custom TitleBar by default or Disabled when ContextFlyout is used.
this is not a winui fluent design:
![Screenshot 2023-11-12 182749](https://github.com/microsoft/microsoft-ui-xaml/assets/9213496/8519bb77-76bf-4a8a-b06b-4e3e09aec443)

if we can use contextflyout our design will be great, currently only right click on interactive element on titlebar is possible and right click on drag regions will be open system context menu and not contextflyout

![Screenshot 2023-11-12 182921](https://github.com/microsoft/microsoft-ui-xaml/assets/9213496/b94bb73d-5ce6-4cfb-a739-7a19241e5b28)

**Comment by bpulliam** [comment]
Dup of #9090
