### ISSUE TITLE
Keyboard Accelerator with ALT modifier causes chime when pressed

### ISSUE THREAD

**Issue by LightJack05** [microsoft/microsoft-ui-xaml#9074]
### Describe the bug

A keyboard accelerator using the Alt modifier (i.e. Alt + 1) will cause the application to play an alert sound, as if the action can't be completed.

This bug has already been mentioned here: https://github.com/microsoft/microsoft-ui-xaml/issues/4379

### Steps to reproduce the bug

Create a Keyboard Accelerator like this:

```
<Button x:Name="btnReset">
    <SymbolIcon Symbol="Refresh"/>
    <Button.KeyboardAccelerators>
        <KeyboardAccelerator
            Modifiers="Menu"
            Key="Number1"
            />
    </Button.KeyboardAccelerators>
</Button>
```

Press the Keyboard Accelerator, you will hear an alert sound.

### Expected behavior

The keyboard accelerator should override this chime behaviour.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Actually on Windows 11 23H2 (22631)

**Comment by bpulliam** [comment]
#4379 has been reopened.
