### ISSUE TITLE
Some button types do not restore text colour after being hovered with pointer. 

### ISSUE THREAD

**Issue by johnt-star** [microsoft/microsoft-ui-xaml#9083]
### Describe the bug

The following button types exhibit this behavior:

- DropDownButton
- RepeatButton
- ToggleButton

Assume a project has the above types included, with the button text set to red. When you hover over each of the button types, the button text turns white. When the pointer leaves the control, the text remains white instead of returning to red.

Note that if you use a standard button, the button text returns to red as expected, after no longer hovering over button.

### Steps to reproduce the bug

1. Create a new Blank App project (WinUI 3 in Desktop)
2. In **MainWindow.xaml**, add the following lines:

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Foreground="Red" Click="myButton_Click">Button</Button>
        <DropDownButton x:Name="dropDownButton" Foreground="Red">Drop Down Button</DropDownButton>
        <RepeatButton x:Name="repeatButton" Foreground="Red">Repeat Button</RepeatButton>
        <ToggleButton x:Name="toggleButton" Foreground="Red">Toggle Button</ToggleButton>
    </StackPanel>

3. Run project and hover mouse over each button type
4. Only the Button's text returns to Red while all others remain white

### Expected behavior

After hovering over various button types, the button text colour should return back to the configured Foreground colour instead of remaining the hovered colour.

### Screenshots

Project startup:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/77626323/55c7e29a-cc43-4d79-9459-f391ce4ae6ce)

After hovering over each button:
[TextColourIssues.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13371078/TextColourIssues.zip)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/77626323/a5d66af9-1497-441d-9a11-4131a05d8bfa)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Project attached
[TextColourIssues.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13371084/TextColourIssues.zip)

**Comment by johnt-star** [comment]
Xaml code was stripped out from Steps to reproduce...here is a screen shot:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/77626323/48697ec5-f610-4c48-bf12-e7172148fcb9)

**Comment by ranjeshj** [comment]
It looks like the template for these controls are missing a TemplateBinding to the Foreground property in the ContentPresenter template part. Thanks for filing this bug. We need to make a pass across all content control derived controls since this looks like a common pattern of bug.

**Comment by karkarl** [comment]
Fixed in internal PR: 10250839
