### ISSUE TITLE
Many MSDN documentation links to files are broken

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9084]
### Describe the bug

After you made major changes to the main branch source code, all links to files (eg. style resources) in the documentation is broken.

### Steps to reproduce the bug

Example:
[Button Page](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.button?view=windows-app-sdk-1.4), click on the `Button_themeresources.xaml` link, and you got 404.

### NuGet package version

None

**Comment by bpulliam** [comment]
This will be for instances that linked to the Xaml repo source. They need to be adjusted for the Source Sharing changes.

**Comment by evelynwu-msft** [comment]
All documentation pages should now have updated links.

**Comment by HO-COOH** [comment]
@evelynwu-msft No, actually you did not fixed the link. You simply replace those links with this
![image](https://github.com/user-attachments/assets/dc0fe8fc-c1f3-4042-818c-c933368142e1). And also why not replace that `Users\<username>` with `%userprofile%` so we can directly paste in the Run dialog?

Also, please note that for C++ projects, nuget does not store packages under this path but under the current project's path.
