### ISSUE TITLE
Proposal: Right-Click on any app in the Taskbar and a new option should come up in the normal menu called "Run as Administrator"

### ISSUE THREAD

**Issue by skanda890** [microsoft/microsoft-ui-xaml#9085]
Right-click on any app in the Taskbar and a new option should come up in the normal menu called "Run as Administrator". This should also happen with pinned items.

**Comment by bpulliam** [comment]
Please log this using Feedback Hub so that it can go to the Shell Team.

**Comment by skanda890** [comment]
Okay

**Comment by skanda890** [comment]
Label this as 'Please-File-on-Feedback-Hub' Or some other label like that.

**Comment by skanda890** [comment]
Feedback Hub:
https://aka.ms/AAnnqgy
