### ISSUE TITLE
HyperlinkButton does not work with "ms-settings:" as NavigateUri

### ISSUE THREAD

**Issue by remokeitel** [microsoft/microsoft-ui-xaml#9086]
### Describe the bug

Windows settings app does not open if NavigateUri is set to "ms-settings:xxx".

Only referred to Microsoft.UI.Xaml.Controls.HyperlinkButton! On UWP (Windows.UI.Xaml.Controls.HyperlinkButton, with and without WinUI2) all is fine.

### Steps to reproduce the bug

Create HyperlinkButton element:
`<HyperlinkButton Content="Windows colors settings" NavigateUri="ms-settings:personalization-colors" />`

Click on HyperlinkButton.

### Expected behavior

Opened Windows settings app

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

**Comment by remokeitel** [comment]
I see no bug fix, only a workaround, which I already have implemented.

**Comment by bpulliam** [comment]
This is being tracked with #4438
