### ISSUE TITLE
NavigationViewItem with IsSelected="True" results in an error (unless an icon is set???)

### ISSUE THREAD

**Issue by heliuawa** [microsoft/microsoft-ui-xaml#9087]
### Describe the bug

```
<NavigationViewItem Width="80" Height="75" Tag="home">
    <StackPanel Margin="8,0,0,0">
        <FontIcon Glyph="&#xE80F;"/>
        <TextBlock Text="主页"/>
    </StackPanel>
</NavigationViewItem>
```

There is nothing wrong with starting this way, Add IsSelected="True" and you'll get an error
If I add an icon to the NavigationViewItem, I don't have any problems
But I don't need an icon

### Steps to reproduce the bug

NavigationViewItem setting IsSelected="True" error，plus Icon is fine

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Fritierkelle** [comment]
@heliuawa Hi, I fixed it by the NavigationView's loaded event:

`void winrt::App1::implementation::MainWindow::nvMainWindow_Loaded(winrt::Windows::Foundation::IInspectable const&, winrt::Microsoft::UI::Xaml::RoutedEventArgs const&)
{
	auto nviStandard = nvMainWindow().FindName(winrt::to_hstring("nviStandard")).as<winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem>();
	nvMainWindow().SelectedItem(nviStandard);
}`

**Comment by heliuawa** [comment]
Okay, I know, thank you.
________________________________
发件人: Fritierkelle ***@***.***>
发送时间: Thursday, November 23, 2023 9:56:57 AM
收件人: microsoft/microsoft-ui-xaml ***@***.***>
抄送: 河流 ***@***.***>; Mention ***@***.***>
主题: Re: [microsoft/microsoft-ui-xaml] NavigationViewItem with IsSelected="True" results in an error (unless an icon is set???) (Issue #9087)


@heliuawa<https://github.com/heliuawa> Hi, I fixed it by the NavigationView's loaded event:

void winrt::App1::implementation::MainWindow::nvMainWindow_Loaded(winrt::Windows::Foundation::IInspectable const&, winrt::Microsoft::UI::Xaml::RoutedEventArgs const&) { auto nviStandard = nvMainWindow().FindName(winrt::to_hstring("nviStandard")).as<winrt::Microsoft::UI::Xaml::Controls::NavigationViewItem>(); nvMainWindow().SelectedItem(nviStandard); }

―

**Comment by heliuawa** [comment]
@Fritierkelle Can you tell me how to do that?

**Comment by Fritierkelle** [comment]
@heliuawa 
- Just add the "loaded" event to your NavigationView tag.
- Add a x:Name to your NavigationViewItem tag.
-  Just use the "FindName" method of the NavigationView to find the named NavigationViewItem.
-  Set the found NavigationViewItem by the NavigationView's "SelectedItem" method.

In the example code above nviStandard is the found NavigationViewItem but I also named the item "nviStandard" by x:Name.
nvMainWindow is the name of my NavigationView.

Regards

**Comment by heliuawa** [comment]
@ranjeshj ok
