### ISSUE TITLE
TabView contextmenu bug

### ISSUE THREAD

**Issue by maihcx** [microsoft/microsoft-ui-xaml#9094]
### Which version of the app?

WinUI 2 Gallery

### Description

1) Pull tab outside
2) Right click on tab to open context menu in newly created window
3) Bug!!!

### Screenshots

![image](https://user-images.githubusercontent.com/59072697/196581703-ea612e40-c873-4148-a433-288d5ab7858e.png)

### Windows version

Windows 11 22H2 (22621)

**Comment by ranjeshj** [comment]
Does not repro in WinUI3 Gallery. We are not taking any fixes for WinUI2 - please see https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2
