### ISSUE TITLE
Child collection must not be modified during measure or arrange

### ISSUE THREAD

**Issue by bjorn-malmo** [microsoft/microsoft-ui-xaml#9096]
### Describe the bug

I'm working on a report layout application, where the user can drag/drop objects, and rearrange items already added. The requirements for flexible layout are many.
I have created an application which basically has one ObservableCollection with pages, and on each page an ObservableCollection with blocks. 
Rearranging the blocks within a single page works just fine, but the "overflow" logic, moving blocks that doesn't fit on the page to the next page, sometimes throws the dreaded:

Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
WinRT information: Child collection must not be modified during measure or arrange.
No installed components were detected.

This happens at the time I add a block to the collection. 
I cannot share the project with the community, so I need to understand how this is supposed to work at all.

The question I have is this; 
Having an ObservableCollection bound to an ItemsRepeater, how can I ensure that modifying the collection does not happen at the same time as an Arrange/Measure pass? Of course all my modifications are performed on the UI thread, but it appears that Arrange/Measure is utilizing other threads. 

### Steps to reproduce the bug

No simple way to recreate..

### Expected behavior

If the Measure/Arrange pass cannot complete, it should not throw an exception that cannot be handled.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

I've tried the latest 1.4.230822000 as well this morning, with the same results

**Comment by ranjeshj** [comment]
This is by design. Changing the collection while layout is happening is not supported. Try making the collection change through a dispatcher callback.
