### ISSUE TITLE
Setting ExtendsContentIntoTitleBar in XAML causes WMC0612

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9100]
### Describe the bug

Setting ExtendsContentIntoTitleBar in XAML causes 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	WMC0612	The XAML Binary Format (XBF) generator reported syntax error '0x09C4' : Property Not Found	WinUI3Cpp	C:\Users\Peter\Source\Repos\WinUI3Cpp\MainWindow.xaml	11	
```

### Steps to reproduce the bug

1. In `MainWindow.xaml`, add the property
```
<Window
    x:Class="WinUI3Cpp.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUI3Cpp"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    ExtendsContentIntoTitleBar="True"
    mc:Ignorable="d">
```

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 (1809): Build 17763

**Comment by ghost1372** [comment]
This is known issue and duplicate,
You should set it in code-behinde

`
Window.Extend....
//Or
 this.Extrnd...
`

**Comment by HO-COOH** [comment]
@ghost1372 I didn't find another open issue about this.

**Comment by ghost1372** [comment]
> @ghost1372 I didn't find another open issue about this.

i cant remember dup issue, but there was same issue for Title and they fixed in v1.3
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-131-13230502000

**Comment by pratikone** [comment]
ExtendsContentIntoTitleBar="True" is not supported in markup. It is only supported in code behind in C# /C++

**Comment by HO-COOH** [comment]
> ExtendsContentIntoTitleBar="True" is not supported in markup. It is only supported in code behind in C# /C++. Closing as not an issue.

Documented nowhere?

**Comment by Iridium-IO** [comment]
If it's not supported in markup, it shouldn't be in markup
