### ISSUE TITLE
Proposal: Can you make a new button in the Taskbar?

### ISSUE THREAD

**Issue by skanda890** [microsoft/microsoft-ui-xaml#9101]
Can you make a new button in the Taskbar called 'Restart Task'? The job of that button is to restart that task.

**Comment by skanda890** [comment]
Feedback Hub:
https://aka.ms/AAno4ed

**Comment by kmgallahan** [comment]
This isn't the place to request Windows features. This repo is for WinUI, a framework for building Windows applications.

**Comment by skanda890** [comment]
Then where should I report these issues?
