### ISSUE TITLE
In MenuBar control, can't set Foreground colour for MenuBarItem but you can for MenuFlyoutItem

### ISSUE THREAD

**Issue by johnt-star** [microsoft/microsoft-ui-xaml#9102]
### Describe the bug

Setting the Foreground colour for MenuBarItem leaves the colour white.

However, changing the MenuFlyoutItem does change the colour to new colour.

### Steps to reproduce the bug

1. Create a new project using the Blank App (WinUI 3 in DeskTop) template.
2. Open WinUI 3 Gallery sample app and go to MenuBar sample.
3. Copy the Xaml source code from first example
4. In the project's MainWindow.xaml, paste the xaml code, as shown in the screen shot below.
5. Add the lines 'Foreground="Red"' to the lines for <MenuBarItem> and <MenuFlyoutItem>, as shown in screen shot below 

### Expected behavior

You should be able to set Foreground colour of MenuBarItem in the same manner as MenuFlyoutItem

### Screenshots

Updated code to MainWindow.xaml:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/77626323/dcd4795e-a63d-4ffb-807b-8d56e577dbf7)

MenuBarItem is still white while MenuFlyoutItems are red
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/77626323/6af29001-0f39-4b4e-936f-9fae6082d754)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Project Files
[MenuBarSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13401105/MenuBarSample.zip)

**Comment by karkarl** [comment]
Fixed in internal PR: 10250839
