### ISSUE TITLE
FontIcon and SymbolIcon has weird padding on Windows 10

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9104]
### Describe the bug

`FontIcon` and `SymbolIcon` has weird padding that makes it offset to its center in its container. And this issue only seems to happen on Windows 10 with WinUI3, not with WinUI2.

### Steps to reproduce the bug

1. Use this xaml in WinUI3 project
```xml
        <Button Padding="0">
            <FontIcon Glyph="&#xE77;"/>
        </Button>
```
You got 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/55d6a819-46e0-40ca-9e50-5c715e34f03d)

2. Use this xaml in WinUI3 project
```xml
        <Button Padding="0" HorizontalAlignment="Center">
            <SymbolIcon Symbol="Accept"/>
        </Button>
```
You got 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/0f9b27de-93af-4869-8e3c-a00a49e31ae9).

In UWP with WinUI2, with the same xaml, the result it expected.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/404d9ce4-6be6-4bb3-97fc-636189a7cb7c)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 (1809): Build 17763

### Additional context
This issue is so universal, that it also bugged WinUI3 Gallery. 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/5042dfd6-1504-45b4-abbd-0512d6477744)

**Comment by kmgallahan** [comment]
![Screenshot 2023-11-19 165638](https://github.com/microsoft/microsoft-ui-xaml/assets/5379488/318af7d1-06cb-44cb-bcca-c77e2143ce84)

**Comment by kmgallahan** [comment]
> Windows 10 (1809): Build 17763

FYI, your version of Windows has been unsupported for 3 years now.

https://learn.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro

https://learn.microsoft.com/en-us/lifecycle/products/windows-10-enterprise-and-education

**Comment by HO-COOH** [comment]
> Shows fine for me on W10 Build 19045.3693:
> 
> ![Screenshot 2023-11-19 165638](https://user-images.githubusercontent.com/5379488/284092708-318af7d1-06cb-44cb-bcca-c77e2143ce84.jpg)
> 
> > Windows 10 (1809): Build 17763
> 
> Your version of Windows has been unsupported for 2-3 years now.
> 
> https://learn.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro
> 
> https://learn.microsoft.com/en-us/lifecycle/products/windows-10-enterprise-and-education
I am aware of this. But since WinUI3 is labeled support down to 17763, I need to ensure the compatibility to the lowest version I want to support. So I want to know if this issue comes from the `Segoe MDL2 Assets` system font. If that is the case, I might as well bundle a Fluent Icon font instead

**Comment by ranjeshj** [comment]
Will share this info with the font team.

**Comment by Jay-o-Way** [comment]
I'm gonna take a quick, wild guess and say this is caused by old OS, or maybe old version of .NET or framework or something like that. Also, I know that SymbolIcon (used to?) uses MDL2 and deprecated icon codes. I'll have to search to see if Microsoft has fixed this recently...
Just out of personal curiosity: is there a reason you're still using an OS version that's 5.5 years old? 🙂

**Comment by gegao18** [comment]
Thanks for reporting this. Since the target version of Windows has been out-of-support for years now, this bug is out-of-scope for the focus of the team.
