### ISSUE TITLE
[WindowsAppSDK + .NET8] Getting warning "Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK."

### ISSUE THREAD

**Issue by DierkDroth** [microsoft/microsoft-ui-xaml#9107]
### Describe the bug

I just upgraded my WindowsAppSDK project to latest .NET8 and now am getting this warning
```
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
```

I have this in my project file
```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Unusual.Windows</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
    <PackageCertificateThumbprint>48ed018aa6aae0c5bad88252a60201b47a770122</PackageCertificateThumbprint>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <DefaultLanguage>en-US</DefaultLanguage>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
  </PropertyGroup>
```
[Related](https://github.com/microsoft/microsoft-ui-xaml/issues/8599)?

How could that issue be resolved?

### Steps to reproduce the bug

Please see above

### Expected behavior

WindowsAppSDK project should build in .NET8 as it did in .NET7

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by remokeitel** [comment]
Does it help if you change `<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>` to `<EnableMsixTooling>true</EnableMsixTooling>`? Also update Microsoft.WindowsAppSDK NuGet package, clean the solution and delete bin and obj folders of the project, then rebuild.

**Comment by DierkDroth** [comment]
@remokeitel thanks for your feedback.

Yes, I'm on latest NuGet package and already cleaned up the solution a couple of time: the problem persists.
The warning suggests that the WindowAppSDK NuGet just it 'not ready yet' for .NET8. I certainly could just disable the warning, but that would not resolve the issue which is within the WindowsAppSDDK NuGet itself.

**Comment by kmgallahan** [comment]
In the WinUI project -> Properties -> PublishProfiles -> change every instance of win10 to win, including in the file names

I'd recommend doing a solution search for "win10" to ensure you don't miss anything.

**Comment by DierkDroth** [comment]
Thanks for your feedback @kmgallahan.

I can't seem to find the option you mentioned (please see screenshot). Where would I find that?

Also: I already tweaked all my *.csproj files to replace `win10 `by `win `(please see my original) post, because I could not compile at all my solution at all after upgrading to .NET 8. Now, it gives my warnings (as per my original post) but build and runs.
Still like to see resolved the cause of the warnings...

<img width="1280" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/26179242/7c41aa4c-acb5-4c0a-9c90-7e0d73d531f3">

**Comment by brandonw3612** [comment]
As is described in the warning message, version-specific or distribution-specific runtime identifiers won't be found by the .NET SDK by default. Even after updating the .csproj file by changing the identifiers to win-ARCH, however, the upstream WinAppSDK package has not got ready for .NET 8, and that's where the warning message came from.

Currently I'm also upgrading a couple of my WinAppSDK projects to .NET 8, (the LTS version, of course). One possible workaround for this would be add a `UseRidGraph` field to the project file.

```
<UseRidGraph>true</UseRidGraph>
```
Here is a [reference](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph#recommended-action) to that, as stated in the breaking changes of .NET 8.

**Comment by DierkDroth** [comment]
Thanks @brandonw3612.

In fact I came across the article you referenced before, but was shying away to apply any 'backward compatible' changes to my solution, since I found it hard to believe that Microsoft did not prepare their own WindowsAppSDK as they rolled .NET8 last week. Oh well...

In any case: your suggested change got me rid of the warnings. Hopefully it does not bring unwanted side affects ... we'll see. Thanks again

**Comment by DarranRowe** [comment]
Well, we haven't been seeing any of the 1.5 preview releases yet, and 1.4.3 isn't a good place for adding .NET 8 support. I also wonder about the status of Cs/WinRT and Native AOT support. Getting the Windows App SDK WinRT projection .NET 8 compatible is one thing, but I feel that it would be tough pushing Native AOT back to 1.6.

**Comment by remokeitel** [comment]
I don't use `<UseRidGraph>true</UseRidGraph>` and don't get any warnings. I upgraded my Windows App SDK project at last weekend to .NET 8 with changing identifiers from win10-xxx to win-xxx.
There would be another issue in your project.

**Comment by DarranRowe** [comment]
@remokeitel 
Do you use `<RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />`? This is seen as the same thing.
Without this, the build process will output:
`1>C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.`
It is also understandable, for example, the bootstrapper is in a win10 rid named directory.

**Comment by remokeitel** [comment]
@DarranRowe 
No, I don't use this option.
There is no warning regarding runtime identifiers.

**Comment by DarranRowe** [comment]
![Screenshot 2023-11-20 213714](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/b3f83cb4-77b5-4855-9a8d-8e539861cbaa)

So it is a project template thing. But interestingly, it seems to get fixed by adding the PublishProfile element back to the other WinUI 3 project type.

**Comment by Scottj1s** [comment]
@DierkDroth thanks for your patience - the next servicing release of Windows App SDK, 1.4.4, will be out shortly and the UseRidGraph workaround will no longer be necessary.
@DarranRowe support for NativeAOT is nearly complete in both C#/WinRT and Windows App SDK and we intend to deliver that with Windows App SDK 1.5.

**Comment by DierkDroth** [comment]
Thanks for the update @Scottj1s

**Comment by vec715** [comment]
Any updates on how to solve this issue? It still persists as of June 2024
