### ISSUE TITLE
When do you update the Visual Studio project templates

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#9112]
### Describe the bug

When do you update the Visual Studio control templates
什么时候更新Visual Studio的控件模板

目前Windows 应用 SDK的最新版本是1.4.3，.NET 平台下最新的.NET版本是.NET 8，在Visual Studio 17.8 更新后，Visual Studio自带的Windows 应用 SDK的模板仍然是1.3，这个版本太旧了。除此之外，Windows 应用 SDK模板创建的.NET 版本仍然使用的是.NET 6，目前Visual Studio安装的.NET桌面应用开发已经默认使用.NET 8而不再使用.NET 6。根据上述的问题，请立即为Visual Studio的Windows 应用 SDK模板发布一个新版本。

在1.2版本前，开发者可以通过Windows 应用 SDK官网自行下载Visual Studio模板，然而在1.2版本后，这一下载渠道已经被关闭，未来能否可以通过官网自行下载Visual Studio模板？

The latest version of the Windows Application SDK is 1.4.3, the latest for the.NET platform. NET version is.NET 8, after Visual Studio 17.8 update, Visual Studio comes with the Windows application SDK template is still 1.3, this version is too old. In addition, the Windows application SDK template is created. NET version is still used. NET 6, currently installed by Visual Studio. NET desktop application development has been used by default. NET 8 and no longer used. NET 6. Based on the above questions, release a new version of the Visual Studio Windows Application SDK template immediately.

Before version 1.2, developers can download Visual Studio templates through the Windows SDK official website, but after version 1.2, this download channel has been closed, can you download Visual Studio templates through the official website in the future?

### Steps to reproduce the bug

As mentioned above

### Expected behavior

更新Visual Studio Windows 应用 SDK的模板，并将.NET平台下的版本更新到.NET 8

Update the Visual Studio Windows application SDK template and will. NET platform version updated to. NET 8

### Screenshots

None

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by HO-COOH** [comment]
The title is misleading. Should be "update the project templates" instead of "update the control templates"

**Comment by Gaoyifei1011** [comment]
> The title is misleading. Should be "update the project templates" instead of "update the control templates"

This issue has come to my attention and the misleading title has been revised

**Comment by Gaoyifei1011** [comment]
> Reference in new issue

Thank you very much, I have found the project template

**Comment by bpulliam** [comment]
Updated templates are going through the Visual Studio ingestion. One key update is that the version of WinAppSDK is no longer hard-coded and will populate with the current version. This will keep the templates up-to-date and remove unneeded maintenance.

**Comment by bpulliam** [comment]
The templates are updated as of Visual Studio 17.10 preview 5
