### ISSUE TITLE
ItemsRepeater with layout horizontal does not update ScrollableWidth of ScrollViewer

### ISSUE THREAD

**Issue by adamfierek** [microsoft/microsoft-ui-xaml#9117]
### Describe the bug

I'm trying to make a horizontal scrollable list with item animation using ScrollViewer and ItemsRepeater. 

When ItemsRepeater's layout is set to Vertical, scrolling is working because ScrollViewer has ScrollableHeight. If i change layout to Horizontal, ScrollableWidth equals 0, but ItemsRepeater width is 2120. Because of that, horizontal scrolling is not working. 

### Steps to reproduce the bug

1. Place ItemsRepeater with horizontal layout in ScrollViewer
2. Feed ItemsRepeater with items
3. ScrollViewer can't scroll horizontally, because of ScrollingWidth=0

### Expected behavior

Ability of scrolling ItemsRepeater horizontally 

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (1809): Build 17763

**Comment by ranjeshj** [comment]
@adamfierek Can you share your markup ? You need to set HorizontalScrollBarVisibility to auto and HorizontalScrollMode to enabled in order for the ScrollViewer to scroll horizontally.
