### ISSUE TITLE
How can I build for WinUI3 from microsoft-ui-xaml source?

### ISSUE THREAD

**Issue by takatsuka2022** [microsoft/microsoft-ui-xaml#9120]
I am planning to Build microsoft-ui-xaml-winui3-release-1.4.3.
When I open XamlCompilerPrerequisites.sln, I get the following screen (NuGet(WinUI.Dependencies)needs your credentials.).
How can I resolve this?
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/100827114/81775dfb-dccb-479d-959f-f3b0b58aac94)

**Comment by kmgallahan** [comment]
You can't.

https://github.com/microsoft/microsoft-ui-xaml/discussions/8980

> Q: ​Will we be able to build from the source or only view due to private dependencies?

> A: To be clear, we are doing shared source, not open source, as there are underlying interwoven components linking WinUI 3 to the system that we can't share. We will not support building, deploying, or running the source code and will not accept PRs for it. We will support viewing, searching, and debugging of the source code when it is available.

**Comment by takatsuka2022** [comment]
Thanks for the reply.
Unfortunately, I give up.
