### ISSUE TITLE
Change Windows Search Provider Feedback Link goes to wrong location

### ISSUE THREAD

**Issue by ibebbs** [microsoft/microsoft-ui-xaml#9123]
I have created an MSIX app package per the instructions outlined in [Windows Search providers](https://learn.microsoft.com/en-gb/windows/apps/develop/search/search-providers) and installed this package in a Windows 11 VM with Insider Preview build 22631.2787 per the [Windows Insider blog post](https://blogs.windows.com/windows-insider/2023/11/16/releasing-windows-11-builds-22621-2787-and-22631-2787-to-the-release-preview-channel/). However, despite an extensive search, I can't find any means of changing the Windows Search Provider.

Please could you provide some information on how to change the Windows Serch Provider.

Thanks

Note: I am posting this issue here as this is the repository linked to at the bottom of the [Windows Search providers](https://learn.microsoft.com/en-gb/windows/apps/develop/search/search-providers) page.

**Comment by bpulliam** [comment]
Thanks for filing this bug.  As you guessed, this is not the right place for your issue to be addressed. However, thanks to your bug, the link has been corrected and now directs you to the Feedback Hub.
