### ISSUE TITLE
where is the Application URL (optional): The URL of your application. its a uwp app on visual studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#9127]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/where-is-the-Application-URL-optional:/10525124)._

---
where is the Application URL (optional): The URL of your application. its a uwp app on visual studio 2022
https://learn.microsoft.com/en-us/windows/uwp/maps-and-location/authentication-key
![Screenshot (7).png](https://aka.ms/dc/image?name=Bbbca5cea05c5494e863ce9344f607efc638364100972712686_Screenshot_(7).png&tid=bbca5cea05c5494e863ce9344f607efc638364100972712686)

---
#### Feedback Bot on 11/24/2023, 00:36 AM: 

(private comment, text removed)
#### chabiss [MSFT] on 11/27/2023, 10:07 AM: 

(private comment, text removed)

**Comment by ranjeshj** [comment]
Please add more details to the bug.
