### ISSUE TITLE
Long running UWP App crashes | Exception c0000374

### ISSUE THREAD

**Issue by ElaJegen** [microsoft/microsoft-ui-xaml#9128]
### Describe the bug

This is an UWP app that communicates to PLC controllers. It send commands, receive real-time data every second, display data with graphs and textfields.

Application was running for 19+ hours before a crash happened.
With Event Log, we were able to collect Exception codes:
Error codes:
1: c0000005 (Windows.UI.Xaml.dll)
2: c0000374 (ntdll.dll)

We were not able to reproduce this exceptions on our debug environment.
Don't have a steps to reproduce. Really appreciate any help!

**Event Log for c0000005 error:**
Application Error:
Faulting application name: [App Name], version: 1.0.0.0, time stamp: 0x5e5883fd
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.19041.3693, time stamp: 0x4d0a8551
Exception code: 0xc0000005
Fault offset: 0x000000000014eb49
Faulting process id: 0x259c
Faulting application start time: 0x01da196718830019
Faulting application path: C:\Program Files\WindowsApps\[App Name]
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 47086d13-72cf-43b7-b2e0-4c730e9cc6ed
Faulting package full name: [App Name]
Faulting package-relative application ID: App

--------------------------------------------------------------------------
**Event Log for c0000374**
Application Error:
Faulting application name: [App Name], version: 1.0.0.0, time stamp: 0x5e5883fd
Faulting module name: ntdll.dll, version: 10.0.19041.3636, time stamp: 0x9b64aa6f
Exception code: 0xc0000374
Fault offset: 0x00000000000ff349
Faulting process id: 0x2dcc
Faulting application start time: 0x01da20c57b485de4
Faulting application path: C:\Program Files\WindowsApps\[App Name]
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: e5a51a12-41fc-4f84-a96e-f84965d38824
Faulting package full name:[App Name]
Faulting package-relative application ID: App

Windows Error Reporting:
[App Name]
   1.0.0.0 
   5e5883fd 
   ntdll.dll 
   10.0.19041.3636 
   9b64aa6f 
   c0000374 
   00000000000ff349 
   2dcc 
   01da20c57b485de4 
   C:\Program Files\WindowsApps\[App Name]
   C:\Windows\SYSTEM32\ntdll.dll 
   e5a51a12-41fc-4f84-a96e-f84965d38824 
  [App Name]
   App 

### Steps to reproduce the bug

Don't have any steps tp reproduce

### NuGet package version

None

```[tasklist]
### Tasks
```

**Comment by ranjeshj** [comment]
[microsoft-ui-xaml/docs/contribution_handling.md at main · microsoft/microsoft-ui-xaml (github.com)](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)
The WinUI team is currently spending its time on WinUI 3. To help with this focus, new bugs filed against WinUI 2 are closed in this repo unless they're a security issue or are business critical.
