### ISSUE TITLE
ComboBox.SelectedItem programmatic binding only works the first time bound property is set

### ISSUE THREAD

**Issue by baskren** [microsoft/microsoft-ui-xaml#9133]
### Describe the bug

[I have provided a demo app](https://github.com/baskren/WinUI3_ComboBoxBinding) with two combo boxes, both having their `ComboBox.ItemsSource` bound to the same class instance DependencyProperty (`MainPage.ViewModel` in demo project) and both have their `ComboBox.SelectedItem` bound to the same class instance class DependencyProperty (`MainPage.Item` in demo project).   The only difference is that one is bound via XAML and the other is bound programmatically.

### FIRST COMBO BOX

```xaml
      <TextBlock AutomationProperties.AutomationId="HelloTextBlock"
          Text="{x:Bind Item, Mode=OneWay}"
          HorizontalAlignment="Center" />
      <ComboBox ItemsSource="{x:Bind ViewModel, Mode=OneWay}" SelectedItem="{x:Bind Item, Mode=OneWay}" />
```

### SECOND COMBO BOX

```xaml
    <StackPanel
      Grid.Column="1"
      Spacing="10"
      HorizontalAlignment="Center"
      VerticalAlignment="Center"
      >
      <TextBlock Text="PROGRAMMATIC BIND" />
      <TextBlock x:Name="textBlockProg" />
      <ComboBox x:Name="comboBoxProg"  />
    </StackPanel>
```

```C#
        textBlockProg.Bind(TextBlock.TextProperty, this, nameof(Item));
        comboBoxProg.Bind(ComboBox.ItemsSourceProperty, this, nameof(ViewModel));
        comboBoxProg.Bind(ComboBox.SelectedItemProperty, this, nameof(Item));
```

where the `.Bind` extension method is:
```C#
    public static void Bind(this DependencyObject target, DependencyProperty targetProperty, object source, string path = null)
    {
        var binding = new Binding
        {
            Source = source,
            Mode = BindingMode.OneWay
        };
        if (!string.IsNullOrWhiteSpace(path))
            binding.Path = new PropertyPath(path);
        BindingOperations.SetBinding(target, targetProperty, binding);
    }

```

The first time `MainPage.Item` and `MainPage.ViewModel` are set, both **ComboBoxes** show the correct corresponding content for `ComboBox.ItemsSource` and `ComboBox.SelectedItem`.  

```C#
    private void button_Click1(object sender, RoutedEventArgs e)
    {
        Item = "A";
    }

    private void button_Click2(object sender, RoutedEventArgs e)
    {
        ViewModel = new string[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P" };
    }

    private void button_Click3(object sender, RoutedEventArgs e)
    {
        ViewModel = null;
        Item = null;
    }
```
However, after setting the `MainPage.ViewModel` and `MainPage.Item` properties to null, _and then setting`MainPage.ViewModel` and `MainPage.Item` again_, only the ComboBox that has been bound via XAML will show the correct corresponding content for its SelectedItem.  The programmatically bound combo box does not show any content for its SelectedItem.  HOWEVER, BOTH COMBO BOXES SHOW ItemsSource = ViewModel!

### Steps to reproduce the bug

1. Clone, build and run the provided small demo repo here :https://github.com/baskren/WinUI3_ComboBoxBinding
2. Click on the [SET SELECTED ITEM] and then the [SET ITEMS SOURCE] buttons
3. observe the population of both `ComboBox.SelectedItem` values in the UI
4. observe the population of both `ComboBox.ItemsSource` lists in the UI
5. Click the [RESET] button
6. For a second time, click on the [SET SELECTED ITEM] and then the [SET ITEMS SOURCE] buttons
7. observer the PROGRAMMITIC BIND  `ComboBox.SelectedItem`  does not show values in the UI but the  XAML BIN `ComboBox.SelectedItem` does show values in the UI
8. observe the population of both `ComboBox.ItemsSource` lists in the UI

### Expected behavior

Binding to `ComboBox.SelectedItem` should be the same regardless of if the binding is via XAML or programmatic

### Screenshots

From demo project

## FIRST TIME
The first time `MainPage.ItemsSource` and `MainPage.SelectedItem` is set:
<img width="791" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/2528888/659cb7f0-9672-4782-a995-6408ed3c700f">

## SECOND TIME
After setting `MainPage.ItemsSource` and `MainPage.SelectedItem` to null and then setting them again to valid values:
<img width="791" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/2528888/ccf7ca31-b943-4983-9e88-9a41336c3676">

But both `ComboBox.ItemsSource` lists are populated:
<img width="791" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/2528888/1a92aa10-b895-4105-96e9-0b72471dc21f">

<img width="791" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/2528888/5cd96962-1d0c-4695-b251-70c3d138db87">

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Since both of **NuGet package version** and **Windows version** inputs are not up to date, here is the correct information:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.4.230913002" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.755" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
```

<img width="706" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/2528888/be2ede75-0cb4-42cb-9c4e-90b566de57f4">

**Comment by kmgallahan** [comment]
``` xaml
<ComboBox ItemsSource="{x:Bind ViewModel, Mode=OneWay}" SelectedItem="{x:Bind Item, Mode=TwoWay}" />
```

!=

``` cs
var binding = new Binding
{
    Source = source,
    Mode = BindingMode.OneWay
};
```

**Comment by baskren** [comment]
> ```
> <ComboBox ItemsSource="{x:Bind ViewModel, Mode=OneWay}" SelectedItem="{x:Bind Item, Mode=TwoWay}" />
> ```
> 
> !=
> 
> ```cs
> var binding = new Binding
> {
>     Source = source,
>     Mode = BindingMode.OneWay
> };
> ```

@kmgallahan : if not, what is?

**Comment by kmgallahan** [comment]
Mode=TwoWay

!=

BindingMode.OneWay

**Comment by baskren** [comment]
@kmgallahan  : Thank you for pointing that out.  You are correct.  

That being said, it presents a new problem (actually, it presents my original problem, I just wrote the problem statement wrong).   If I change my XAML to:

```XAML
      <ComboBox ItemsSource="{x:Bind ViewModel, Mode=OneWay}" SelectedItem="{x:Bind Item, Mode=OneWay}" />
```

... so they are the same, I get the same issue.  I will edit my original problem statement above to reflect this.

**Comment by baskren** [comment]
@kmgallahan : That's what I was afraid was going on here.

**Comment by baskren** [comment]
> At a more fundamental level, your bindings are still very different as the new x:Bind with generated code is not the same thing as the old Binding style.
> 
> If you want to reproduce your Binding in XAML then:
> 
> ```
> <Page DataContext="{Binding RelativeSource={RelativeSource Self}}"
> 
> <ComboBox ItemsSource="{Binding ViewModel, Mode=OneWay}" SelectedItem="{Binding Item, Mode=OneWay}" />
> ```
> 
> You can't create an x:Bind programmatically.

This is meant as a serious question, something I haven't been able to get my head around since I started working with UWP about 6 years ago.  You seem to be very knowledgable so I'm hoping you have insights into my question:

This is yet another example of where you can do something in XAML but, "you can't do ________ programmatically".  From an outsiders POV, I feel as if UI code is second class to XAML.  I understand the benefits of separation of concerns - but there are other ways to do that other than XAML. So, strategically, why are there so many "features" in UWP/WinUI that are not available in code?

**Comment by kmgallahan** [comment]
> This is yet another example of where you can do something in XAML but, "you can't do ________ programmatically".
> why are there so many "features" in UWP/WinUI that are not available in code?

The general reason is that the XAML compiler only processes XAML documents and spits out C# or C++ depending on the project. It doesn't try to parse non-XAML documents (.cs or .cpp) looking for additional tasks.

Specifically regarding x:Bind, the XAML compiler is responsible for generating all of the high-performance binding code (vs. the slower Binding code that relies on reflection). You can view this code for your sample project in Visual Studio by going to Edit > Go To > Go To File > type in "MainPage.g.cs".

You could probably write all that code by hand or create your own .NET Source Generator and it might work (not sure if anyone has tried that before).

Not sure what other features you are referring to.

**Comment by baskren** [comment]
Thank you @kmgallahan.  That confirms a suspicion or two I had and, at last, I think I can be at peace with what I'm working with.
