### ISSUE TITLE
[RichEditBox] 'More options' button is not working properly

### ISSUE THREAD

**Issue by ToukZ** [microsoft/microsoft-ui-xaml#9140]
### Describe the bug

On RichEditBox, selecting any written text opens up a 'Text Editing Bar' that allows you to modify the selected text's visuals. It also has an Ellipsis button that would display more options of actions to be done by the user, but currently it is not possible to access those options as they close rapidly on open.

### Steps to reproduce the bug

1. Go to 'RichEditBox' component
2. Type any Text on a RichEditBox
3. Highlight that text to open up a Text Editing Bar
4. Click on the 'Ellipsis' Button to show 'more options'
5. See Error

### Expected behavior

More Options should correctly stay open, allowing the user to interact with it.

### Screenshots

![richEditBoxIssue](https://github.com/microsoft/microsoft-ui-xaml/assets/58863075/4578039e-00d0-4807-adb7-89abac0f7ff8)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.2: 1.4.231008000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by kmgallahan** [comment]
Additional note: This only happens when the flyout opens automatically on selecting the text. Manually opening via right-click works as expected.

**Comment by HO-COOH** [comment]
More additional note: This also happens to WinUI2 with WinUI2 gallery

**Comment by JJBrychell** [comment]
Several issues here.  

- The control was listening for text changes and dismissing the flyout when that happened.  However, it didn't limit it based upon change type and so it was dismissing when a format change occurred (as well as actual text change).  Hence when clicking on one of the format buttons, that would incorrectly dismiss the flyout.
- The more button was incorrectly taking focus when clicked causing the RichEditBox to dismiss the flyout.
- The more popup menu would also take focus (again causing RichEditBox to dismiss the flyout).

This fix is in and should be in 1.5
