### ISSUE TITLE
What's new in Windows app SDK 1.5 experimental 1?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#9146]
### Describe the bug

What's new in Windows app SDK 1.5 experimental 1?
Windows app sdk 1.5 experimental 1 更新了什么？

At present, the Windows app SDK 1.5 experimental 1 has provided an installation package in nuget, but no changelog has been provided, and we hope to release a changelog soon
目前 Windows app sdk 1.5 experimental 1 已经在nuget中提供了安装包，但是还没有提供更新日志，希望能尽快发布一份更新日志

### Steps to reproduce the bug

None

### Expected behavior

See describe

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/d2a0d566-81f4-4afc-b6e4-b0b4ddd318f9)

### NuGet package version

Windows App SDK 1.4.3: 1.4.231115000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

None

**Comment by duncanmacmichael** [comment]
Hi @Gaoyifei1011, sorry for the delay in getting the release notes out. You can check out the list of new and modified experimental APIs here:

https://learn.microsoft.com/windows/apps/windows-app-sdk/experimental-channel#version-15-experimental-150-experimental1
