### ISSUE TITLE
Proposal:Hope to set the app's icon as a window icon automatically in the future version

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#9156]
# Proposal: [your title here] 

Hope to set the app's icon as a window icon automatically in the future version
希望未来的版本能将应用的图标自动设定为窗口图标

## Summary

In the case of WPF application, if the application does not obviously set the icon (that is, it does not actively set the Windows.Icon property, the default window will set the application icon as a window icon), but this behavior does not happen in Winui 3, I hope that the future version can achieve this function.
在WPF应用中，如果应用没有明显设置图标的情况下（也就是没有主动设置Windows.Icon属性，默认窗口会将应用图标设置为窗口图标），然而这一行为却没有在Winui 3中发生，希望未来的版本中能实现这一功能。

## Rationale

In Winui3, although the application icon can be set through the AppWindow.SetIcon () method, it is necessary to specify the specific Ico file path or open icon handle, but if the window icon can be bound to the application icon by default, this step can be automatically eliminated.

在Winui3 中，虽然可以通过AppWindow.SetIcon（）方法设定应用图标，但却必须要指定具体的Ico文件路径或打开的图标句柄，但如果窗口图标可以默认与应用图标绑定，就可以自动省去这一步骤。

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/49179966/ec17a17b-dba2-4f15-af5d-b5897860f239)
The WPF application automatically sets the window icon
WPF应用会自动设置窗口图标

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by JaiganeshKumaran** [comment]
Duplicate of #4761.

**Comment by Gaoyifei1011** [comment]
> Duplicate of #4761.

Ok, I've received this message, this issue is about to be closed.
