### ISSUE TITLE
Window titlebar controls do not respect users' theme and settings

### ISSUE THREAD

**Issue by abcdabcabcabcd00** [microsoft/microsoft-ui-xaml#9166]
### Describe the bug

When using `AppWindowTitleBar.ExtendsContentIntoTitleBar`; the titlebar used by WinUI does not respect the users' theme and settings
Specifically; if a theme defines a custom look for the titlebar controls or the user changes the size of the titlebar controls

### Steps to reproduce the bug

- Install a custom theme or modify registry keys in `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics` (Specifically `CaptionHeight` and `BorderWidth`)
- Sign out and back in
- Open a Win32 app (i.e. `regedit`)
- Open any WinUI app (Both WinUI 2 and 3 work)
- Notice the titlebar controls don't follow the changed proportions or theme

### Expected behavior

The titlebar controls size as expected

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044, Windows 10 (21H1): Build 19043, Windows 10 (20H2): Build 19042, Windows 10 (1809): Build 17763

### Additional context

Fixing this issue would be great for accessibility; as titlebar control size may be increased by people with disabilities (i.e. poor vision; tremors) to aid in allowing them to keep using Windows

**Comment by HO-COOH** [comment]
You are not really supposed to change that in `regedit`, but here is another approach (in case they don't recognize it as bug)
- For Windows 11, go to settings->Acceesibility->Text size, make text bigger
- For windows 10, go to settings->Ease of Access->Display->Make text bigger.

And notice how normal win32 title bar caption buttons and title bar get bigger, but not UWP nor WinUI3(after setting `ExtendContentIntoTitleBar`).

**Comment by pratikone** [comment]
@HO-COOH  is right here. I don't think we follow that. WinUI has its own comprehensive accessibility capabilities which it follows from what the OS provides. I don't think the registry entries will work with it. 

This looks like a good request for Feedback hub in your Windows. This is because it will require OS changes to have options for thicker titlebar size. Do post there so that accessibility team will be able to track it and work on it. 

Closing this as a not an bug.

**Comment by HO-COOH** [comment]
@pratikone I do think that for WinUI3 with `ExtendContentIntoTitleBar=true`, this is a bug tho. Because the whole titlebar is self-drawn and should respect accessibility changes.
