### ISSUE TITLE
Windows.Gaming.Input only detect devices as RawGameControllers

### ISSUE THREAD

**Issue by LudoTexx** [microsoft/microsoft-ui-xaml#9169]
### Describe the bug

When try to get Joystick or racing wheels with  _Windows.Gaming.Input_ all the devices are only recognized at _RawGameControllers_.

Joystick = Virpil controls
Racing wheels = Fanatec

### Steps to reproduce the bug

using Windows.Gaming.Input;

var tmp = Windows.Gaming.Input.RacingWheel.RacingWheels; // EMPTY
var tmp2 = Windows.Gaming.Input.FlightStick.FlightSticks; // EMPTY
var tmp3 = Windows.Gaming.Input.Gamepad.Gamepads; // EMPTY
var tmp4 = Windows.Gaming.Input.ArcadeStick.ArcadeSticks; // EMPTY
var tmp5 = Windows.Gaming.Input.RawGameController.RawGameControllers; // Found all my joysticks and racing wheel

### Expected behavior

Founding my joystick in _Windows.Gaming.Input.FlightStick.FlightSticks;_ 
Founding my racing wheel in _Windows.Gaming.Input.RacingWheel.RacingWheels;_

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/19667047/bdc6a4e1-7904-49c6-8798-915846f25167)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DarranRowe** [comment]
I think reading the documentation is in order here.
The Windows documentation for all of these states similar things. If we take [Gamepad.Gamepads](https://learn.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad.gamepads?view=winrt-22621#windows-gaming-input-gamepad-gamepads) as an example, then it states:

"This list is initially empty and will not list gamepads even if they are already connected. After a short period this will return a complete list of gamepads."

in the Remarks section. This essentially means that you should use Gamepad.Gamepads or the other similar properties as early as you can in your application to start populating the lists. This means that by the time you want to use them, the lists will be populated.

**Comment by LudoTexx** [comment]
Thanks for your answer.

This is the same for  RawGameController as you can see in MS documentation.
 I call Windows.Gaming.Input.RawGameController.RawGameControllers in my MainWindows.cs, the list is empty as except. And later in my program, the list is populated when I need to use it. The doc is clear on this. 

But this not work for GamePad, Joystick and RacingWheel.

**Comment by DarranRowe** [comment]
![Screenshot 2023-12-17 205008](https://github.com/microsoft/microsoft-ui-xaml/assets/52577874/a37dea58-4012-49fa-9e29-0a7f1054c0e5)

It does work. This is with an XBox Series controller though. The documentation does state that runtime classes like GamePd needs an XBox One/XBox 360 certified controller. I wonder if that basically means that it needs an XInput driver.
