### ISSUE TITLE
Strange top line window when window is miximized

### ISSUE THREAD

**Issue by leonardomelosantos** [microsoft/microsoft-ui-xaml#9176]
### Describe the bug

I need help about issue on WinUI (MAUI) Platform. When we set ExtendsContentIntoTitleBar to true in the application on Dark Mode, we have strange top line when we click to maximize window. This behavior occurs when the screen/monitor have Resolution 100%, 125% etc.

![TitleBar_WithTopLineWhenMaximized](https://github.com/microsoft/microsoft-ui-xaml/assets/3422111/60efea9f-3783-4032-b978-5e25ac6783f7)

### Steps to reproduce the bug

1. Open the application and keep window normal size (non-maximized)
2. Change resolution from 125% to 100% in Windows Settings
3. Back to application and maximize the window.
4. Result: Strange top line appears.

### Screenshots

![TitleBar_WithTopLineWhenMaximized](https://github.com/microsoft/microsoft-ui-xaml/assets/3422111/60efea9f-3783-4032-b978-5e25ac6783f7)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by kmgallahan** [comment]
That non-maximized screenshot with the thick borders indicates that your Windows theme is broken. Try setting your Windows theme to default in Settings. Not sure if it is related to the line, but the borders should get fixed at least.

**Comment by pratikone** [comment]
The regular WinUI apps don't have this issue. Are you seeing it in a hello world MAUI app too ? If not, it could be due to some conflict in your app theming. Need more information.
