### ISSUE TITLE
If the NavigationView's SelectedItem is set after having set the ItemsSource the NavigationViewItem is not selected.

### ISSUE THREAD

**Issue by Suriman** [microsoft/microsoft-ui-xaml#9185]
### Describe the bug

When setting the SelectedItem of a NavigationView after having set the ItemsSource, the NavigationViewItem which has to be selected doesn't select.

### Steps to reproduce the bug

1 - Open the attached sample and compile it.
2 - Execute the NavigationViewSelectionDisappears.Windows project as Package.
3 - You'll see that the NavigationViewItem is not selected.

### Expected behavior

The NavigationViewItem has to be selected.

### NuGet package version

None

**Comment by Suriman** [comment]
[NavigationViewItemIsSelectedValue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13758701/NavigationViewItemIsSelectedValue.zip)

**Comment by kmgallahan** [comment]
IMO, you should provide a minimal repro sample rather than a large market-platform project with many extraneous references. 

~I couldn't run it unless I installed things I'd prefer not to.

**Comment by Suriman** [comment]
I attach the solution with the Windows target framework only.
[NavigationViewItemIsSelectedValueWindowsOnly.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13817210/NavigationViewItemIsSelectedValueWindowsOnly.zip)

**Comment by kmgallahan** [comment]
This is not a minimal repro:

``` XML
    <PackageReference Include="Uno.Resizetizer" Version="1.2.1" />
    <PackageReference Include="Uno.WinUI" Version="5.0.48" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.4.231008000" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="Uno.Material.WinUI" Version="4.0.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.48" />
    <PackageReference Include ="Prism.Core" Version="8.1.97"/>
```

This is a minimal repro from making a new app from the standard template and copying over bits of your code: 

https://github.com/kmgallahan/NavSelectedItemSample

and it shows the NavigationView working as expected.

You should start eliminating or adding dependencies and complications in a test project until you find what is causing your problem.

**Comment by gegao18** [comment]
Thanks for reporting this @Suriman, and thanks @kmgallahan for investigating. I'm closing this for now since it seems to be an external issue. Please reopen if you've identified the problem to be something on WinUI 3.
