### ISSUE TITLE
RichEditBox context flyout menu animation glitch

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9193]
### Describe the bug

RichEditBox context flyout menu has unnatural animation upon showing less items. 

### Steps to reproduce the bug

1. Go to **RichEditBox** page in WinUI3 gallery.
2. Type some random text, right click to open the context menu (select text to open the menu is already a bug reported in #9140)
3. Click **See more** (the last button), to expand the menu
4. Click the button again to **Show less** item in the menu, observe the glitch

### Expected behavior

The animation should be smooth and natural

### Screenshots

![richeditbox-glitch](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/d7ee9536-512e-4062-9238-386e69241631)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 10 (1809): Build 17763

**Comment by gegao18** [comment]
Thanks for reporting this. This is not something we'll likely get to.

**Comment by yoshiask** [comment]
What? Why not? It's this kind of polish that WinUI 3 is sorely lacking compared to other UI frameworks.
