### ISSUE TITLE
100 threads are created when reordering ListView with 2 items in WinUI3

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9195]
### Describe the bug

Why would you need to create and destory 100 threads when reordering a **ListView** with 2 items (in **Release** build) ? 

### Steps to reproduce the bug

1. Create a ListView with this
```xml
    <ListView CanReorderItems="True" AllowDrop="True">
        <x:String>Item1</x:String>
        <x:String>Item1</x:String>
    </ListView>
```
2. Build in **Release** mode, launch with visual studio debugger
3. Try reorder the item, observe the output window

### Expected behavior

I don't know what to expect

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/0e163d4d-6fe4-45c6-be34-95e6c22f3377

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 10 (1809): Build 17763

**Comment by kmgallahan** [comment]
I think this is a problem with how drag & drop is implemented. Unsure if inherent to built-in ListView / GridView drag & drop code, or more general. Could be tested by implementing some custom drag & drop code.

I'm guessing threads will keep getting created for as long as the mouse is moving in a drag state.

Semi-related: https://github.com/microsoft/microsoft-ui-xaml/issues/8851

**Comment by RBrid** [comment]
The number is now reduced to 14 threads according to my observations, with the latest WinUI3 and OS version 10.0.22621.3527.

**Comment by HO-COOH** [comment]
@RBrid Just tried with this release 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/14ce7d1e-7f47-4058-bbec-b750cdb7639b)

28 threads on my side. Still not very reasonable, reopen please.

**Comment by RBrid** [comment]
Hello - I verified again that 14 threads are created per drag&drop operation using the latest 1.6 build. So not reopening this at the moment. Maybe you did two successive operations and saw 28 threads?
