### ISSUE TITLE
TreeView can't auto scroll to the selected item

### ISSUE THREAD

**Issue by wuyang26** [microsoft/microsoft-ui-xaml#9200]
### Describe the bug

By ItemSource binding data ,If the Selected Item has not been displayed yet, you cannot scroll to this selection

    the code:
     var treeList = TreeHelper.FindVisualChild<TreeViewList>(treeView);
     treeList.ScrollIntoView(treeView.SelectedNode);

### Steps to reproduce the bug

1、binding the treeview ItemSource property
2、Write a button click event
3、Expand tree items in the event (select an item outside of the visible view to expand by code)
4、Execute sub item selection under expanded items by code
5、Execute scrolling to selection items in the event
      var treeList = TreeHelper.FindVisualChild<TreeViewList>(treeView);
      treeList.ScrollIntoView(treeView.SelectedNode);

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by wuyang26** [comment]
Not within the above issues！

**Comment by ranjeshj** [comment]
Is the selected node collapsed? Would expanding the parent node first make this realized and then you can scroll into view ?

**Comment by weitzhandler** [comment]
This issue still exists.

**Comment by wuyang26** [comment]
No, can not scroll into view. I think because ui virtualizationv.
Before the first expand,the visual  tree has not yet been implemented,like wpf treeview,but wpf can realize by additional behavior,yet can not find the same event Selected in winui TreeViewItem.
