### ISSUE TITLE
When adjusting the left border of the window, the window right area flashes

### ISSUE THREAD

**Issue by wuyang26** [microsoft/microsoft-ui-xaml#9201]
### Describe the bug

When adjusting the left border of the Winui3 window, the right area of the window continues to blink, but Winui2 and the system standard window do not blink

### Steps to reproduce the bug

1、Run the Winui 3 gallery App
2、press the mouse resize the window left border
3、look the window right area

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmgallahan** [comment]
Dupe #5148
