### ISSUE TITLE
Datagrid : Expanding a column after a total row deletion crashs the Datagrid

### ISSUE THREAD

**Issue by O4D** [microsoft/microsoft-ui-xaml#9205]
### Describe the bug
[DataGrid_VisualCrash SIMPLE.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13833466/DataGrid_VisualCrash.SIMPLE.zip)
A. After a total deletion of all the rows present in Datagrid, the column resizing crash on visual.cs

Complementary/Very similars bugs :
B. After 50 element added then all deleted, it crash on visual.cs
C. (Same project) A scrollviewer Visible without any row in the Datagrid trigger a crash on visual.cs

### Steps to reproduce the bug

A. Column resize bug

1. Click on 'Add 10'
2. Click on 'Erase All'
3. Resize the column width with mouse
4. See error "The specified Visual is not an ancestor of this Visual"

B. 50 elements total deletion bug

1. Click on 'ADD 10' (5 times, so 50elements)
2. Click on 'Erase All'
3. See error "The specified Visual is not an ancestor of this Visual"

C. Scrollviewer visibility bug

1. In XAML, set the Scrollviewer visibility to "Visible"
2. Launch the project
3. See error "The specified Visual is not an ancestor of this Visual"

### Expected behavior

No crash

### Screenshots

[DataGrid_VisualCrash SIMPLE.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13833466/DataGrid_VisualCrash.SIMPLE.zip)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

.NET concerned : .NET Framework 4.7.2 and .NET 7

This issue is reported because of a more problematic issue which is happening on datagrid on a more complex C# Solution : when the datagrid is displayed, after 2 total deletion of the rows, the same crash appears. So I'm trying to isolate any crash source.

[DataGrid_VisualCrash SIMPLE.zip](https://github.com/microsoft/microsoft-ui-xaml/files/13833466/DataGrid_VisualCrash.SIMPLE.zip)

**Comment by kmgallahan** [comment]
``` xml
<UseWPF>true</UseWPF>
```

Wrong repo.
