### ISSUE TITLE
Hebrew translation of "Free" in your CameraCaptureUI means "No money required" rather than "Without constraints"

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#9207]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Hebrew-translation-of-Free-in-your-Cam/10553486)._

---
[severity:I'm unable to use this version]
We had a complaint about a bug in our code from a Hebrew linguist who wrote to us "Free" translated as "doesn't cost money", while the actual meaning is "unrestricted action".  This is not text that we put in our resources, it comes from your CameraCaptureUI.

He recommended using חופשי instead of חינם, but obviously that is not in our power.

I have attached 4.png to illustrate the UI we are seeing.

Note that the severity "I'm unable to use this version" does not mean we can't use Visual Studio at all...it means we can't use Visual Studio to present the UI we would like to see.   None of the other options were really apt.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by codendone** [comment]
Logged an [internal bug](http://task.ms/48554041) for the CameraCaptureUI owners in Windows.
