### ISSUE TITLE
Automatic bool-visibility conversion regressed between C++17 and 20 

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/microsoft-ui-xaml#9214]
### Describe the bug

> \App6\App6\Generated Files\MainWindow.xaml.g.hpp(172,92): error C3779: 'winrt::impl::consume_Windows_Foundation_IReference<winrt::Windows::Foundation::IReference<bool>,T>::Value': a function that returns 'auto' cannot be used before it is defined

### Steps to reproduce the bug

https://github.com/tom-huntington/auto-bool-visibility-conversion-cpp20-regression

MainWindow.xaml
```xaml
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
    <CheckBox x:Name="myButton" Content="Click Me" />
    <TextBlock Text="Hello" Visibility="{x:Bind myButton.IsChecked, Mode=OneWay}"/>
</StackPanel>
```

MainWindow.idl
```idl
Microsoft.UI.Xaml.Controls.CheckBox myButton{ get; };
```

### Expected behavior

That it compiles with `/std:c++20` as it did with `/std:c++17`

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

docs: https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension#remarks

> Starting in Windows 10, version 1607, the XAML framework provides a built in Boolean to Visibility converter. The converter maps true to the Visible enumeration value and false to Collapsed so you can bind a Visibility property to a Boolean without creating a converter. Note that this is not a feature of function binding, only property binding. To use the built in converter, your app's minimum target SDK version must be 14393 or later. You can't use it when your app targets earlier versions of Windows 10. For more info about target versions, see [Version adaptive code](https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/version-adaptive-code).

**Comment by asklar** [comment]
@tom-huntington  that repo is private (I get a 404)

**Comment by tom-huntington** [comment]
> @tom-huntington that repo is private (I get a 404)

Sorry. Fixed.

**Comment by sylveon** [comment]
Looks like a missing `#include <winrt/Windows.Foundation.h>`

**Comment by tom-huntington** [comment]
> Looks like a missing `#include <winrt/Windows.Foundation.h>`

I know that's way the error message is saying.

`pch.h` includes it and adding extra includes `MainWindow.xaml.{h,cpp}` doesn't fix it??

**Comment by asklar** [comment]
@tom-huntington  did this get fixed?

**Comment by tom-huntington** [comment]
> @tom-huntington did this get fixed?

No, but realized there's a work around. Just force the instantiation of `IReference<bool>::Value`

```
//MainWindow.xaml.h
#if 1
inline void force_instantiation_of_IRefBoolValue()
{
    &winrt::Windows::Foundation::IReference<bool>::Value;
}
#else
//error C3779 : 'winrt::impl::consume_Windows_Foundation_IReference<winrt::Windows::Foundation::IReference<bool>,T>::Value' : a function that returns 'auto' cannot be used before it is defined
#endif
```
