### ISSUE TITLE
Moving mouse wheel and click hangs WinUI application

### ISSUE THREAD

**Issue by jeremy-visionaid** [microsoft/microsoft-ui-xaml#9223]
### Describe the bug

This appears to be a WinUI bug, not a Windows App SDK bug:
https://github.com/microsoft/microsoft-ui-xaml/issues/9233

### Steps to reproduce the bug

As per:
https://github.com/microsoft/microsoft-ui-xaml/issues/9233#

### NuGet package version

None

**Comment by bpulliam** [comment]
#9233 was moved into this repo, so closing this as dup.  Thanks for the heads up.
