### ISSUE TITLE
Protocol Activation - Unpackaged App: Microsoft.Windows.AppLifecycle.AppInstance.GetActivatedEventArgs() returns object with Data as WinRT.IInspectable

### ISSUE THREAD

**Issue by AdriaanLarcai** [microsoft/microsoft-ui-xaml#9225]
### Describe the bug

Attempting to get single instancing working via protocol activation in a Self Contained Unpackaged app.
When attempting to retrieve AppActivationArguments during app startup using GetActivatedEventArgs() method on the current AppInstance returns an AppActivationArguments object where the Data property is returned as a WinRT.IInspectable object. The returned WinRT.IInspectable is unusable and attempting to resolve it always results in protected memory access exceptions.

### Steps to reproduce the bug

Create a new WinUI3 Unpackaged project.
Implement the single instancing pattern by overriding the generated program.cs and attempt to retrieve the AppActivationArguments by calling Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent().GetActivatedEventArgs()  when the app is started.
Inspect the Data property of the AppActivationArguments object.

### Expected behavior

The AppActivationArguments Data property should be set to the appropriate IActivatedEventArgs implementation based on the launch type (Launch, Protocol, etc.) as it is when building and running a Packaged app.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/74778708/1c47faba-1790-450a-8ae3-d5d8674c46b9)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DarranRowe** [comment]
Forgive me if I missed something, but besides this being an issue that is better placed in the Windows App SDK repository, isn't this behaviour expected?
In an unpackaged situation, the argument can refer to four distinct startup types. Each of these use a different interface type. What's more, when packaged, this is extended to the 44 supported by Windows, but it then uses the inbuilt Windows activation functionality. This is also part of the API, the [AppActivationArguments.Data](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appactivationarguments.data?view=windows-app-sdk-1.4#microsoft-windows-applifecycle-appactivationarguments-data) property is documented to return IInspectable/Object. .NET projects IInspectable to Object. The idea here is that you obtain the instance of AppActivationArguments, inspect AppActivationArguments.Kind to tell what kind of activation that you are working with, retrieve the IInspectable instance from AppActivationArguments.Data and then query this for the appropriate interface based upon Kind. There is information on this in the [documentation](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation). You can also show [samples](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/AppLifecycle/Activation) illustrating this too.
While there is some slight differences, this is also the way that UWP does it. [Windows.ApplicationModel.AppInstance.GetActivatedEventArgs](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.appinstance.getactivatedeventargs?view=winrt-22621#windows-applicationmodel-appinstance-getactivatedeventargs) returns an [IActivatedEventArgs](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.iactivatedeventargs?view=winrt-22621) here. You would then query [IActivatedEventArgs.Kind](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.iactivatedeventargs?view=winrt-22621) then query this for the appropriate interface based upon Kind.
