### ISSUE TITLE
Xbox UWP app: Pointer mode does not work properly when scaling is set to default (200 %)

### ISSUE THREAD

**Issue by remokeitel** [microsoft/microsoft-ui-xaml#9231]
### Describe the bug

The UWP app is configured for the Xbox so that the pointer mode is only enabled when requested (RequiresPointerMode = ApplicationRequiresPointerMode.WhenRequested). The scaling is set to default (200 % for UWP apps). One page was created with a ScrollViewer and one with a WebView2 control. Both controls have the properties "RequiresPointer=WhenEngaged" and "IsFocusEngagementEnabled=True". As soon as the controls receive the focus and the pointer mode is activated (IsFocusEngaged = True), the pointer appears. However, the pointer can only be used in 25 % of the area of the control at the top left. As soon as scaling is disabled (ApplicationViewScaling.TrySetDisableLayoutScaling(true)) and the app is displayed at 100 %, the pointer can be navigated over the entire area of the control.

### Steps to reproduce the bug

App.xaml.cs:
```
public App()
{
    this.InitializeComponent();
    this.Suspending += OnSuspending;

    if (AnalyticsInfo.VersionInfo.DeviceFamily == "Windows.Xbox")
    {
        this.RequiresPointerMode = ApplicationRequiresPointerMode.WhenRequested;
        //ApplicationViewScaling.TrySetDisableLayoutScaling(true);
    }
}
```

MainPage.xaml:
```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>
    <TextBox Grid.Row="0" Text="Test" />
    <ScrollViewer
        x:Name="ScrollViewer"
        Grid.Row="1"
        IsFocusEngagementEnabled="True"
        RequiresPointer="WhenEngaged"
        GotFocus="ScrollViewer_GotFocus">
        <StackPanel>
            <TextBlock Text="Hello" />
        </StackPanel>
    </ScrollViewer>
</Grid>
```

MainPage.xaml.cs:
```
public MainPage()
{
    this.InitializeComponent();
}

private void ScrollViewer_GotFocus(object sender, RoutedEventArgs args)
{
    ScrollViewer.IsFocusEngaged = true;
}
```

Navigate to ScrollViewer with Xbox Controller, so that it gets the focus.

### Expected behavior

Pointer can be navigated over the entire area of the control by default Xbox UWP scaling (200 %)

### NuGet package version

None

### Additional context

Operating System:
Xbox

OS Version:
10.0.25398.2538

**Comment by ranjeshj** [comment]
@remokeitel 
https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2
<snip>
The WinUI team is currently spending its time on WinUI 3. To help with this focus, any new bug filed against WinUI 2 is closed in this repo unless it's a security issue or is critical to our business priorities.
</snip>

**Comment by remokeitel** [comment]
@ranjeshj But on Xbox there is no WinUI 3 available! And this issue has nothing to do with WinUI, but with UWP (without WinUI).

**Comment by softworkz** [comment]
## Don't Ever Use WinUI3!

That's  the message that this is telling: Eventually, they will abandon WinUI3 in the same way like they do for WinUI2 - from one day to another.

Anyway, it seems like WinUI3 has been abandoned already and whether:

- Your issue remains open and ignored (WinUI3), or
- Your issue is closed and ignored (WinUI2)

doesn't make a difference at all.
