### ISSUE TITLE
Moving mouse wheel and click hangs WinUI application

### ISSUE THREAD

**Issue by wesol1** [microsoft/microsoft-ui-xaml#9233]
https://github.com/microsoft/WindowsAppSDK/assets/103489461/964667a0-ae71-47eb-b6f0-88f47653aee0

### Describe the bug

It's introduced from the first version of 1.4 (with last 1.3 works well).
When you move mouse wheel and quick/accidentally click left/right mouse button application hangs.
Moving pointer cursors outside the app or switching to another one brings it back to life. 
You can observe such thing with WinUI 3 Gallery app.

### Steps to reproduce the bug

1. Open WinUI app (or WinUI 3 gallery)
2. Start moving the mouse wheel and then quick click left/right mouse button
3. Try couple of times if not successful

### Expected behavior

Application should be responsive not frozen.

### Screenshots

Movie added as attachment.

### NuGet package version

Windows App SDK 1.4.3: 1.4.231115000

### IDE

Visual Studio 2022

### Additional context

In attached movie I used WinUI 3 Gallery app, as I cannot show you our commercial one.
Such freeze was introduce with first 1.4 version, probably with new Scrollxxx features.

**Comment by mikolaj-boc** [comment]
Hi @llongley, thanks for the fix! Do you happen to know when a build with the fix is expected?

**Comment by TheEdster3** [comment]
Would also love to know when the fix would be available. A few weeks off from a release and trying to determine if we need to put the effort into some kind of workaround or not. :)

**Comment by codendone** [comment]
Status update: The fix is currently in for the upcoming 1.5 release and will be evaluated later this week for potential servicing to 1.4.

**Comment by codendone** [comment]
@jeremy-visionaid Yes, the fix is part of the 1.4.24021100 release. Thanks for confirming it is working for you!
