### ISSUE TITLE
WebView2: Select text and scroll no longer works.

### ISSUE THREAD

**Issue by AdriaanLarcai** [microsoft/microsoft-ui-xaml#9237]
### Describe the bug

Selecting text in a Webview2 control, and while holding the left mouse button pressed, scrolling with the mouse wheel causes the app to freeze / mouse input to be lost.

### Steps to reproduce the bug

Create a new Windows App SDK 1.4 Desktop application.
Add a WebView2 control with a source where the text / content is larger than the control's viewspace.
Select any visible text and, while holding the left mouse button pressed, scroll in any direction using the mouse wheel.

### Expected behavior

The WebView2 control should scroll the content in the direction of the mouse wheel.
This was working in a prior version.

### NuGet package version

Windows App SDK 1.4.3: 1.4.231115000

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update), Windows 11 version 21H2 (22000), Windows 10 version 22H2 (19045, 2022 Update), Windows 10 version 21H2 (19044, November 2021 Update), Windows 10 version 21H1 (19043, May 2021 Update), Windows 10 version 20H2 (19042, October 2020 Update), Windows 10 version 2004 (19041, May 2020 Update), Windows 10 version 1909 (18363, November 2019 Update), Windows 10 version 1903 (18362, May 2019 Update), Windows 10 version 1809 (17763, October 2018 Update)

### IDE

Visual Studio 2022

**Comment by applefanbois** [comment]
We have the same problem, reported by all our users.

**Comment by DmitriyKomin** [comment]
@AdriaanLarcai, thank you for reporting this. I tested the scenario locally and text selection + mouse-wheel scroll + small control size is working well:

https://github.com/microsoft/microsoft-ui-xaml/assets/45051803/fe14f548-3654-4064-ad49-5ce5079f324e

This is with WinAppSDK 1.4.230913002 / WebView2Runtime 121.0.2277.128.

Resolving Not Repro. If you find you can still repro the issue, please comment here and provide a repro app / video. Thanks!

**Comment by AdriaanLarcai** [comment]
Hi, perhaps my issue description was not clear enough. I will update it. But the issue is not selecting text and then scrolling. The issue is selecting text, and while still holding the left mouse button pressed, using the mouse wheel to scroll up and down. Users do this when they need to select more text than what's visible on screen. This is functionality that used to work, and no longer works.

**Comment by DmitriyKomin** [comment]
Thanks @AdriaanLarcai and @applefanbois. I am still not able to repro this - holding down left mouse button and scrolling with the wheel works well for me, even after updating to the same WinAppSDK 1.4.230913002 that you used (+ WebView2Runtime 121.0.2277.128). Can you attach a video of the repro that you are seeing?

**Comment by DmitriyKomin** [comment]
This issue is also being tracked on Edge side at MicrosoftEdge/WebView2Feedback#4291. Not clear yet if it's specific to WinAppSDK or an underlying Edge/CoreWebView2 issue, makes sense to keep both open for now.
