### ISSUE TITLE
WinUI 3 Gallery crashes on "Semantic Zoom" page

### ISSUE THREAD

**Issue by rnikander** [microsoft/microsoft-ui-xaml#9239]
### Describe the bug

I downloaded the "WinUI 3 Gallery" from the Microsoft Store. If I go to the "Scrolling" section and click on "SemanticZoom", it usually crashes within a second or two. 

### Steps to reproduce the bug

1. Navigate to the SemanticZoom
2. Wait, or try to scroll down a bit.

### NuGet package version

None

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

**Comment by codendone** [comment]
This was tracked with [this internal bug](http://task.ms/46819062). That bug says this was fixed in WinUI Gallery main, but it still repros.
