### ISSUE TITLE
Version 1.4.4 source code is missing

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#9245]
### Describe the bug

The source code for the stable version 1.4.4 is missing

### Steps to reproduce the bug

Check the 1.4 stable branch. Only the source code for 1.4.3 is available 

### NuGet package version

None

**Comment by evelynwu-msft** [comment]
Thanks for letting us know! The WinUI 3 source for the 1.4.4 release has now been [published](https://github.com/microsoft/microsoft-ui-xaml/tree/winui3/release/1.4.4). We're still ironing out the kinks from our process so we appreciate your patience. :)
