### ISSUE TITLE
AutoSuggestBox does not have a way to disable spell checking

### ISSUE THREAD

**Issue by lucas-yotsui** [microsoft/microsoft-ui-xaml#9249]
### Describe the bug

I'm new to WinUI so I don't have a lot of knowledge on how all this stuff works, why some things were implemented the way they were, etc, etc. But I have noticed that the AutoSuggestBox elements do not have any way to disable the spell checking, which in my opinion does not make any sense! The text input by the user and the options shown are not always considered grammarly correct. 

Take for example the application I'm currently developing, in which we have an AutoSuggestBox used for a group of names that are all acronyms. those are perfectly valid names for our application, however I keep getting red squiggly lines every time I use it.

I believe this problem can be easily solved by giving this element a _IsSpellCheckEnabled_ field just like a regular TextBox field.

(Sorry if my english is not the best, it isn't my first language ¯\\_(ツ)_/¯ )

### Steps to reproduce the bug

I don't think any code sample is really needed here, just implement a simple AutoSuggestBox and input it with anything not grammarly correct.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmgallahan** [comment]
``` xaml
<AutoSuggestBox>
  <AutoSuggestBox.TextBoxStyle>
    <Style TargetType="TextBox">
      <Setter Property="IsSpellCheckEnabled" Value="False" />
    </Style>
  </AutoSuggestBox.TextBoxStyle>
</AutoSuggestBox>
```

**Comment by lucas-yotsui** [comment]
> ```
> <AutoSuggestBox>
>   <AutoSuggestBox.TextBoxStyle>
>     <Style TargetType="TextBox">
>       <Setter Property="IsSpellCheckEnabled" Value="False" />
>     </Style>
>   </AutoSuggestBox.TextBoxStyle>
> </AutoSuggestBox>
> ```

Sorry guys, clearly it was a skill issue here, as I had no idea this was even possible. However, I noticed that when I did this my query icon disapperared, is there any way I can keep it while doing this? The icon is actually an important part of my design

**Comment by kmgallahan** [comment]
``` xaml
<AutoSuggestBox QueryIcon="Find">
  <AutoSuggestBox.TextBoxStyle>
    <Style BasedOn="{StaticResource AutoSuggestBoxTextBoxStyle}" TargetType="TextBox">
      <Setter Property="IsSpellCheckEnabled" Value="False" />
    </Style>
  </AutoSuggestBox.TextBoxStyle>
</AutoSuggestBox>
```

FYI, not all MUXC (Microsoft.UI.XAML.Controls) controls have a property that allows you to set one or more styles for an internal part of the control like `AutoSuggestBox.TextBoxStyle`.

Above using `BasedOn` it stating the style should inherit everything found in the default style `AutoSuggestBoxTextBoxStyle`, which can be found in your `generic.xaml` file, which is typically located here-ish: 

```
C:\Users\<username>\.nuget\packages\microsoft.windowsappsdk\<wasdkversion>\lib\<platform>\Microsoft.WinUI\Themes
```

It is a 36K line file that contains default styles and named 'light-weight' styles to set some individual values.

**Comment by lucas-yotsui** [comment]
> ``` xaml
> <AutoSuggestBox QueryIcon="Find">
>   <AutoSuggestBox.TextBoxStyle>
>     <Style BasedOn="{StaticResource AutoSuggestBoxTextBoxStyle}" TargetType="TextBox">
>       <Setter Property="IsSpellCheckEnabled" Value="False" />
>     </Style>
>   </AutoSuggestBox.TextBoxStyle>
> </AutoSuggestBox>
> ```

Thank you so much, this worked perfectly!

Clearly I have much to learn on XAML and WinUI I'm general, thanks for the tips and the solution!
