### ISSUE TITLE
Custom control inherits MediaPlayerElement and crashes when running

### ISSUE THREAD

**Issue by BigHeadDev** [microsoft/microsoft-ui-xaml#9258]
### Describe the bug

I plan to create my custom player control that inherits MediaPlayerElement. I haven't written any code, but when I use it in xaml, it directly causes the program to crash

**winui3 unpackage mode**

### Steps to reproduce the bug

1，create a new class named "MediaPlayerElementEx"
2，inherited MediaPlayerElement
3，use it on HomePage.xaml directly <controls:MediaPlayerElementEx />
4，run app

### Expected behavior

app crashed

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23449064/053cf627-e69f-4c49-9756-dfa071d05f24)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23449064/7cf1a7e7-3390-4e81-9570-aee759e53332)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23449064/a6255521-59f0-472e-a112-7615f22ef754)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.4: 1.4.231219000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Same as #8973.

**Comment by BigHeadDev** [comment]
> Same as #8973.

So, isn't this bug fixed in future plans?
