### ISSUE TITLE
PointerEntered event isn't triggered in a Grid column with a hidden or empty content. 

### ISSUE THREAD

**Issue by sgoarin** [microsoft/microsoft-ui-xaml#9270]
### Describe the bug

In WINUI 3, the PointerEntered event isn't triggered in a Grid column with a hidden or empty content.  It works when the content isn't hidden or empty. The code below works only on column 2 of the grid.

### Steps to reproduce the bug

**XAML code:**
<ListView x:Name="ProjectList"  
        BorderThickness="1" 
        BorderBrush="{ThemeResource SystemControlForegroundBaseMediumLowBrush}" 
        SelectionMode="Single"
        Width="350"
        Height="400"
        HorizontalAlignment="Left"
        Grid.Row="2"
        Grid.Column="0"
        Margin="50, 0, 0, 10">

    <ListView.Resources>

    </ListView.Resources>
    <ListView.ItemTemplate>

        <DataTemplate>
            <ContentControl>
                    <Grid PointerEntered="ProjectList_PointerEnteredGrid" PointerExited="ProjectList_PointerExitedGrid">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="0"/>
                        <ColumnDefinition Width="278"/>
                        <ColumnDefinition Width="Auto"/>
                    </Grid.ColumnDefinitions>

                    <TextBlock  Grid.Column="0" Text="{Binding ProjectId}" Visibility="Collapsed" />
                    <TextBlock  Grid.Column="1" Text="{Binding ProjectName}"/>
                        <ContentControl Grid.Column="2">
                        <Button x:Name="btnMore"  HorizontalAlignment="Right" Visibility="Collapsed">
                            <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE712;"/>
                            <Button.Flyout>
                                <MenuFlyout>
                                    <MenuFlyoutItem DataContext="{Binding ProjectId}" Text="Edit" Click="EditProjectName"/>
                                        <MenuFlyoutItem DataContext="{Binding ProjectId}" Text="Delete" Click="ConfirmDeletion"/>
                                    <MenuFlyoutItem Text="Environments"/>
                                </MenuFlyout>
                            </Button.Flyout>

                        </Button>
                    </ContentControl>

                </Grid>
            </ContentControl>

        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>

**C# code:**
private void ProjectList_PointerEnteredGrid(object sender, RoutedEventArgs e)
{
    var uc = (Grid)sender;
    Button btnMore = (Button)uc.FindName("btnMore");
    btnMore.Visibility = Visibility.Visible;
}

private void ProjectList_PointerExitedGrid(object sender, RoutedEventArgs e)
{
    var uc = (Grid)sender;
    Button btnMore = (Button)uc.FindName("btnMore");
    btnMore.Visibility = Visibility.Collapsed;
}

### Expected behavior

PointerEntered placed at Grid or at ListView level should be triggered regardless of content.

### Screenshots

![Screenshot](https://github.com/microsoft/microsoft-ui-xaml/assets/25203477/18e4c1ca-e945-45b3-8cb1-6d9a9cb0869d)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.4: 1.4.231219000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
The grid itself has no rendering, so there is nothing to hit test. You can set background on the grid so hit testing works. It can be set to transparent.
