### ISSUE TITLE
ListView CanReorderItems not working with custom ItemsPanel

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9275]
### Describe the bug

It seems that using any custom panel as `ItemsPanel` for `ListView`, it can no longer reorder items. Built-in `StackPanel` works fine.

### Steps to reproduce the bug

1. Create a new WinUI3 project, install the `CommunityToolkit.WinUI.Controls` package
2. Use this xaml
```xml
<Window ... 
    xmlns:controls="using:CommunityToolkit.WinUI.UI.Controls">
    <ListView CanReorderItems="True" AllowDrop="True">
        <ListView.ItemsPanel>
            <ItemsPanelTemplate>
                <controls:WrapPanel Orientation="Horizontal"/>
            </ItemsPanelTemplate>
        </ListView.ItemsPanel>

        <x:String>Item1</x:String>
        <x:String>Item2</x:String>
        <x:String>Item3</x:String>
    </ListView>
```
3. Try drag and reorder the items. It only shows a red stop sign.

### Expected behavior

Should be able to reorder the items.

### NuGet package version

WinUI 3 - Windows App SDK 1.5 Experimental 1: 1.5.231202003-experimental1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by FireCubeStudios** [comment]
Pretty sure this is intentional

**Comment by HO-COOH** [comment]
> Pretty sure this is intentional. toolkit wrap panels themselves has to include drag and drop support

Maybe that's true. Can you share an example to implement that with custom panel?

**Comment by ranjeshj** [comment]
This is by design. The panels need to impliment some interfaces to participate in drag and drop. StackPanel impliments IInsertionPanel. https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.iinsertionpanel?view=winrt-22621. Not sure if that is sufficient.
