### ISSUE TITLE
'ProtectedCursor': is not a member of 'winrt::Microsoft::UI::Xaml::UIElement'

### ISSUE THREAD

**Issue by levinli303** [microsoft/microsoft-ui-xaml#9277]
### Describe the bug

In cpp, `UIElement.ProtectedCursor()` throws compiler error `'ProtectedCursor': is not a member of 'winrt::Microsoft::UI::Xaml::UIElement'`  on 1.4.4

### Steps to reproduce the bug

As in the description

### NuGet package version

WinUI 3 - Windows App SDK 1.4.4: 1.4.231219000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by sylveon** [comment]
This is not a bug, it's [an intended change](https://github.com/microsoft/cppwinrt/pull/1319). `ProtectedCursor` is protected so it should've never been exposed publicly in the first place.

The proper way is to do it like in C#, by inheriting from the UI element.

You can also do `element.as<IUIElementProtected>().ProtectedCursor()` to minimize code changes on your end, but it's more of a workaround/hack.

**Comment by sylveon** [comment]
There's a bigger question about whether or not this member should be made public in a future WASDK update (so that C# users can also enjoy being able to set the cursor without inheritance), or a better API for setting the cursor introduced.

**Comment by levinli303** [comment]
thanks for the workaround. yeah it would be best for there to be public API to change cursors. I can close this if you think that a public API should be tracked in a different issue.

**Comment by codendone** [comment]
A public `UIElement.Cursor` property remains a desired API addition on the backlog ([internal tracking item](http://task.ms/10803936)). We don't have a timeline for that currently. I don't see a "feature proposal" tracking that in this repo; feel free to log that, if desired.
