### ISSUE TITLE
Image rendering issue

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#928]
there is a Image rendering issue, but I don't know how to reproduce it. sometimes it is normal, sometimes it is black or like the second one.
![image](https://user-images.githubusercontent.com/12285582/59963378-ee3f5500-9524-11e9-8afb-323b37c4d637.png)

**Comment by HppZ** [comment]
![image](https://user-images.githubusercontent.com/12285582/59966014-813db680-9548-11e9-9e88-fb809b01c21c.png)

**Comment by jevansaks** [comment]
Thanks @HppZ for the report -- we'll need a bit more information than you've provided, though. What application? What OS version? 

When you do see it, how persistent is it? Does it continue to show incorrectly even after you scroll?

**Comment by HppZ** [comment]
version: Windows 1903
app: UWP app written in c#/xaml

When you do see it, how persistent is it?
don't know

Does it continue to show incorrectly even after you scroll?
yes

**Comment by HppZ** [comment]
Can you open source Image?

**Comment by jevansaks** [comment]
Sorry for the delay. That's in the plan for WinUI 3.0, but I don't think it will help here.

With the information provided there's unfortunately nothing we can do with this report.

**Comment by HppZ** [comment]
I don't understand why MS closed my issue just because I can't provide a repro project, I can't repro in demo project, but it exists in real project.
'nothing they can do' is their best reason.

SAD.

**Comment by HppZ** [comment]
@codendone PLEASE TAKE A LOOK.

**Comment by codendone** [comment]
Hi @HppZ. Do you see the same rendering issue on multiple machines, particularly ones with different graphics cards? The image looks like a possible issue in the large "atlas" surface holding multiple images, and issues in a graphics driver can be a cause for that.

How frequently does this occur in your real project?

**Comment by codendone** [comment]
Knowing if this repros on different graphic cards would be helpful, or which graphic card if you only see it on one type (or brand) of card. A full process memory dump and matching screenshot when you have a repro would give us some information to help narrow down the issue.

How are these images loaded? Via Uri, a Stream (where did the stream come from?), SoftwareBitmap, or something else (like WriteableBitmap or SurfaceImageSoure)?

**Comment by HppZ** [comment]
bug reproduced.

![Untitled](https://user-images.githubusercontent.com/12285582/127742097-261d8d1f-c76a-42b4-a6ad-c25b2336d50b.png)

**Comment by HppZ** [comment]
dump file created by TaskManager, onedrive link: https://1drv.ms/u/s!Aujg7zvpbIVkgi-1rpWHm6hXYHce?e=ppGehO

**Comment by HppZ** [comment]
dump file created by procdump: https://1drv.ms/u/s!Aujg7zvpbIVkgjAkuWinwvktPyTm?e=7erYWZ

**Comment by HppZ** [comment]
@codendone 

>Knowing if this repros on different graphic cards would be helpful.

yes, repros on different graphic cards.


>How are these images loaded?

via URI, local path or http path.

device information:
[DxDiag.txt](https://github.com/microsoft/microsoft-ui-xaml/files/6911324/DxDiag.txt)

**Comment by HppZ** [comment]
any update here?

**Comment by Zuescho** [comment]
UP. This issue should not be part of https://github.com/microsoft/microsoft-ui-xaml/discussions/8638.

**Comment by JJBrychell** [comment]
Based upon the initial date of this issue it is assumed that was filed against UWP/WinUI 2.
What looks to be happening is that original rendering surface memory was given back but something is still holding on it.  It then gets reused by something else overwriting the image with other images and then also render it.

Because WinUI2 is currently in maintenance mode and because WinUI3 uses a WinAppSdk version of composition, without a repro, it is difficult to determine wither this issue is still applicable to WinUI3.  If this issue continues to repro in WinUI3 feel free to reopen.
