### ISSUE TITLE
Can't flip through flipview items after opening and closing a window

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#9292]
### Describe the bug

Can't flip through flipview items after opening a window, closing it, navigating to the page where the flipview is.

### Steps to reproduce the bug

1. Make a new project where you can navigate between two pages;
2. Place a button on the first page and set the click to open a window, and populate a flipview with some pictures in the second page;
3. Run the app and click the button, the window will open so you close it, then navigate to the second page and try flipping through the flipview.

### NuGet package version

WinUI 3 - Windows App SDK 1.5 Experimental 2: 1.5.240124002-experimental2

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This bug is new in 1.5 experimental 2. It works in experimental 1.

**Comment by RBrid** [comment]
Thanks for your bug report. We are in the process of fixing it.

**Comment by eduardobragaxz** [comment]
Nice

**Comment by bpulliam** [comment]
This is in 1.5.
