### ISSUE TITLE
ScrollViewer hangs when click + scrolling until window focus is lost

### ISSUE THREAD

**Issue by EvilAngel00** [microsoft/microsoft-ui-xaml#9295]
### Describe the bug

When using the ScrollViewer control, attempting to scroll while pressing down a mouse button (left, right or middle) will freeze the application window until focus is lost by either clicking on the title bar, resizing or minimizing the window.

### Steps to reproduce the bug

Minimal repro project: 
[TestScrollViewer.zip](https://github.com/microsoft/microsoft-ui-xaml/files/14081723/TestScrollViewer.zip)

1. Open the application
2. Scrolling with mouse wheel should work normally
3. Press a mouse button and while the button is pressed, attempt to scroll
4. The ScrollViewer freezes and it's not possible to click any of the buttons anymore

### Expected behavior

The ScrollViewer should still be able to scroll while mouse buttons are pressed.

### Video Example

https://github.com/microsoft/microsoft-ui-xaml/assets/6838045/c7863b2c-0eaf-4ebb-a9a4-36d054e8e1c5

### NuGet package version

WinUI 3 - Windows App SDK 1.4.4: 1.4.230913002

### Windows version

Windows 11 (23H2): Build 22631.3007

**Comment by Marv51** [comment]
I also see this in my app.

**Comment by kmgallahan** [comment]
dupe #9233

**Comment by EvilAngel00** [comment]
Thanks, I didn't find it before. I'll close this one.
