### ISSUE TITLE
WebView2 Google Menu Bug

### ISSUE THREAD

**Issue by savronix** [microsoft/microsoft-ui-xaml#9298]
### Describe the bug

I created an empty project with Template Studio for WinUI with VS 2022. I added a tabview to my project. Then I added WebView2 to each generated item. The problem starts here. When I redirect to www.google.com, no matter what I choose from the dropdown menu, it does not work. This is also valid in WinUI 3 Gallery application. this problem needs to be fixed. This project I developed is available in my repo.

https://github.com/microsoft/microsoft-ui-xaml/assets/99677404/9242ed24-b8ac-4bf2-9046-3566a3139d08

### Steps to reproduce the bug

I don't know what to write here.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.4: 1.4.231219000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by osmansavuran** [comment]
there is a bug not only on google.com but in all menus. when i click on quality to change quality on youtube the menu closes.
