### ISSUE TITLE
ListView virtualization breaks when using different item templates

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#9307]
### Describe the bug

`ListView` virtualization logic breaks when selecting different item templates from `ChoosingItemContainer`.

### Steps to reproduce the bug

Have a `ObservableCollection` filled with items that resolve the same `DataTemplate` A.
Replace the items in the collection with a new set of items that resolve the `DataTemplate` B.
All the previous `ListViewItem` will end up in the recycle queue, and `ChoosingItemContainer` will fire proposing the aforementioned containers.
Since none of the recycled containers will actually match, a new `ListViewItem` will be created for each new item added to the view.
In addition to this, the ListView will stop recycling new containers at all, realizing all items available in the collection and finally breaking any kind of virtualization.
The only way to recover from this seems to be consuming the unmatching containers from the recycle queue, after this the ListView will start to unload out-of-bounds containers and recycle them.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.4: 1.4.231219000

**Comment by ranjeshj** [comment]
@FrayxRulez can you please share a repro project?

**Comment by FrayxRulez** [comment]
Some more detail on the mechanism, from the WinUI sources and from a minimal repro. Same
behaviour in WinUI 2 (UWP) and WinUI 3.

## What happens

With `ChoosingItemContainer` and an app-side container pool, refusing a mismatched suggestion
can put the panel into a state it never leaves: `ContainerContentChanging` stops being raised
with `InRecycleQueue: true` altogether, so the app's pool never receives a container, every item
gets a newly built one, and the realized set grows with the item count instead of staying at a
viewport's worth.

Measured on a 5000-item list, two templates, after a `Clear()` and a refill with the other type:

| | panel children | realized | containers built |
|---|---|---|---|
| refuse the mismatched suggestion | 1970 | 1279 | 1866 |
| consume it (re-template it instead) | 104 | 103 | 104 |

## Repro

1. `ListView` with `ChoosingItemContainer`, two `DataTemplate`s, and an app-side pool keyed by
   template. On a mismatch, set `args.ItemContainer = null` and supply one of the right type from
   the pool, or build one when the pool is empty.
2. Fill the collection with 500 items of type A, scroll to the end and back.
3. `Clear()` the collection and add 5000 items of type B.

Every one of the 5000 gets a freshly built container, and no `InRecycleQueue` notification is
raised during the refill.

## Why

Three behaviours that are individually defensible and deadlock in combination.

**1. The suggestion path ignores the flag the candidate search respects.**
`ModernCollectionBasePanel::GenerateContainerAtIndex` takes the back of the queue unconditionally:

```cpp
else if (!m_recycleQueue.empty())
{
    spSuggestedContainer = std::move(m_recycleQueue.back()).AsOrNull<IUIElement>();
    m_recycleQueue.pop_back();
}
```

while `FindRecyclingCandidateImpl` skips containers the app has refused:

```cpp
auto it = std::find_if(m_recycleQueue.rbegin(), m_recycleQueue.rend(),
    [&spContainer](ctl::WeakRefPtr& arg) { ... return !denied; });
```

So the panel can conclude a usable candidate exists while still suggesting a refused one.

**2. A refused container is put first in line to be suggested again.** On refusal it is marked and
`push_back`-ed — the same end the suggestion is popped from, so it is the very next suggestion:

```cpp
p_virtualizationinfo->SetWasRejectedAsAContainerByApp(true);
m_recycleQueue.push_back(std::move(wrContainer));
```

**3. The rescue cannot run when nothing is off-screen.** `EnsureRecycleContainerCandidate` is the
only path that can produce a fresh candidate, and it only harvests containers already disjoint from
the realization window, giving up at the first one that is not:

```cpp
while (areDisjoint && (!found) && (currentPosition < ValidContainersBeforeFallback) && ...)
// if !areDisjoint, we reached the start of the virtualization window and will not find a candidate anymore
```

During a `Clear()` and refill the containers at the front are the ones just realized and still
inside the window, so the walk exits having recycled nothing. `RecycleLinkedContainer` never runs,
which is what would raise `InRecycleQueue` *and* clear `WasRejectedAsAContainerByApp` — the flag's
only reset site. So no un-refused container ever reaches the queue, every suggestion is the refused
one off the back, and each newly built container is realized and inside the window, which keeps the
harvest failing.

Scrolling never hits this because there is always something off-screen to harvest. The same handler
holds at 104 containers while scrolling and reaches 1970 across a refill.

**The fallbacks that would break the cycle are unreachable here.** Both `QueueLengthBeforeFallback`
and `ValidContainersBeforeFallback` sit behind `if (spRecyclingContext)`, and a recycling context
only exists when an `ItemTemplateSelector` is set with no `ItemTemplate`. An app using
`ChoosingItemContainer` has no fallback at all. `FindRecyclingCandidateImpl` also carries a comment
describing a fallback that is not implemented:

```cpp
// However, if we cannot find another candidate to
// recycle, since the queue is not empty, we will just suggest a container from the queue and that is
// perfect.
```

The `find_if` below it simply reports no candidate.

## Possible fixes

Any one of these breaks the cycle:

- have the suggestion path skip refused containers, using the same predicate as
  `FindRecyclingCandidateImpl`
- implement the fallback the comment above already describes
- `push_front` a refused container instead of `push_back`, so it is not immediately re-suggested

## Workaround

Never leave a suggestion unconsumed: when the app has nothing of the right type to swap in, take
the suggested container and re-template it rather than refusing it. That is enough to keep the
queue moving — 104 containers instead of 1970 in the table above.

Worth noting for anyone reading the event's contract: setting `args.ItemContainer = null` is *not*
a refusal. With a null container the panel uses its own suggestion as-is:

```cpp
else if (!spContainerAsSelectorItem)
{
    if (spSuggestedContainer) { spContainer = spSuggestedContainer; }
```

A refusal is handing back a container that is not the suggested one, and only that path marks and
re-queues it.
