### ISSUE TITLE
UWP bug: cannot access Application.Resources

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/microsoft-ui-xaml#932]
**Describe the bug**
When creating a new UWP app from the templates and trying to access its `Resources` getter, I get an exception.

**Steps to reproduce the bug**
- Open VS
- Create an UWP from the IDE templates
- In `App.xaml.cs` after `InitializeComponent()` in the constructor, add `var r = Resources`, and hit <kbd>F5</kbd> to start debugging.
- When the debugger gets to that line an `Exception` is thrown with the following message:
>`'Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))'`

**Expected behavior**
Access to application resources

**Screenshots**
![image](https://user-images.githubusercontent.com/2716316/59969702-dbe10d80-955c-11e9-8a5f-a326ace70c20.png)

**Version Info**
IDE: VS 16.1.3
OS: Windows 10 Pro x64 ver. 1809 (build 17763.557)

NuGet package version: 
`Microsoft.NETCore.UniversalWindowsPlatform`: 6.2.8.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I do not want to use `Microsoft.UI.Xaml.*`, because I use Uno (the reproduction occurs in plain UWP tho).

**Comment by jevansaks** [comment]
I believe this is a known issue and you have to wait until something like OnLaunched to be able to access those things. I'll leave this issue active to see if the framework folks want to try to fix this in the future.

**Comment by weitzhandler** [comment]
@jevansaks
Thanks for your response.

I'm unable to add static resources to the MainPage.xaml file.

**Comment by bpulliam** [comment]
UWP is no longer supported by WinUI 3.  If you can repro the issue on current builds without UWP, please reactivate or open a new issue.

Thanks!
