### ISSUE TITLE
Fluent icon "MusicAlbum"  doesn't seem to exist in control "MenuFlyoutItem"

### ISSUE THREAD

**Issue by Miaoyww** [microsoft/microsoft-ui-xaml#9329]
### Describe the bug

Just like the title, while i try to use MenuFlyoutItem control with icon "MusicAlbum" like this:
```
<MenuFlyoutItem Text="CheckAlbum" Icon="MusicAlbum" />
```
It crashed and reported\
```
"Failed to create a 'Microsoft.UI.Xaml.Controls.IconElement' from the text 'MusicAlbum'. [Line: 46 Position: 49]”
```
but when i tried to use FontIcon like this, it worked well.
```
                   <MenuFlyoutItem Text="CheckAlbum">
                        <MenuFlyoutItem.Icon>
                            <FontIcon Glyph="&#xE93C;"/>
                        </MenuFlyoutItem.Icon>
                    </MenuFlyoutItem>
```

### Steps to reproduce the bug

Above..

### NuGet package version

None

### Windows version

Windows Insider Build (xxxxx)

### Additional context

Windows Version: Windows 11 23H2 os.22631.3085

**Comment by kmgallahan** [comment]
Named glyphs only work if they exist in the Symbol Enum, which MusicAlbum does not:

https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.symbol

**Comment by Miaoyww** [comment]
alright, well thanks
