### ISSUE TITLE
Proposal: Add MaximumRowsOrColumns Property to UniformGridLayout 

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#933]
# Proposal: Add Columns and Rows Properties to UniformGridLayout 
It would be nice if the UniformGridLayout also had Columns and Rows properties like the UniformGrid control from the [Windows Community Toolkit](https://github.com/windows-toolkit/WindowsCommunityToolkit). The current UniformGridLayout  is a **WrapLayout**, these properties make it a **UniformGrid**.

## Summary
Extra Columns and Rows dependency properties

**Comment by micahl** [comment]
Thanks for opening this!  You're right that the UniformGridLayout is a constrained version of a WrapLayout.  The UniformGridLayout is similar to what the layout for the Community Toolkit's AdaptiveGridView is doing.  They take as input an item size (or base size that can grow) and use that to calculate the number and size of columns.

If the UniformGridLayout had a MaxRowsOrColumns would that enable the scenario you have in mind?  For example, if a 3 column layout that grows to fill the space would be: `<UniformGridLayout ItemsStretch="Fill" MaxRowsOrColumns="3"/>`.

This proposal may also tie into #696.

**Comment by sonnemaf** [comment]
Yes it would. A MaxRowOrColumns with a ItemStretch would also satisfy me needs. I don't need the GridLayout (#696) but I can image it is useful.

**Comment by micahl** [comment]
Cool.  There's precedence with that name existing on some of the other wrapping layouts (e.g. VariableSizedWrapGrid, WrapGrid, ItemsWrapGrid) so following precedent here doesn't seem like it would be controversial.

Btw, this might be a straightforward addition if you were interested in making the contribution.  Besides adding the property I think it would just be a minor adjustment to the logic in the [UniformGridLayout::Algorithm_ShouldBreakLine](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/UniformGridLayout.cpp) method + testing.

**Comment by sonnemaf** [comment]
I would love to contribute it but i have no experience wit C++. I'm a C#/XAML developer. I hope to find time to jump on this train.

**Comment by jevansaks** [comment]
> I would love to contribute it but i have no experience wit C++. I'm a C#/XAML developer. I hope to find time to jump on this train.

@sonnemaf I totally understand, the barrier to entry can be high. That said, I think modern C++ is not too far from C# in terms of approachability. Is there anything I/we can do to make this easier for you? Would a "getting started" or some other materials like that help?

**Comment by sonnemaf** [comment]
For now my limited available time is holding me back, sorry.

A "getting started" would off course help a lot.

**Comment by micahl** [comment]
Here's a PR to add support for a MaximumRowsOrColumns property that can be used with ItemsStretch as discussed earlier in this thread: https://github.com/microsoft/microsoft-ui-xaml/pull/1068

**Comment by sonnemaf** [comment]
Thank you @micahl. You saved me from learning modern C++ and implementing it myself. Not that I don't want to learn it. I just don't have the time for it.

**Comment by chingucoding** [comment]
@sonnemaf Since there is a MaximumRowsOrColumns property now, is there still a need to manually specify Rows/Columns?

Or do you think that the main idea of this proposal was addressed (and hence we can close it)? 😅

**Comment by sonnemaf** [comment]
No this is already perfect. I will close the issue. Thanks
