### ISSUE TITLE
Closing the Application with an opened context flyout causes a crash

### ISSUE THREAD

**Issue by jaimecbernardo** [microsoft/microsoft-ui-xaml#9336]
### Describe the bug

When we close an application with a context flyout opened, it logs a crash in the Event Viewer:
https://github.com/microsoft/PowerToys/issues/28820
This is an issue in PowerToys utilities, which we fixed an instance of it by looping while waiting for the context flyout to closed before really closing, but it is reproable in the WinUI3 gallery as well.

### Steps to reproduce the bug

1. Open the WinUI 3 Gallery application that's shipped in the Microsoft Store.
2. Enter the Text > TextBox screen.
3. Right click in the simple text box example so that the context menu appears.
4. Close the Gallery by clicking the exit button with the context menu opened. This will cause a crash.
5. Verify that there's an Event Viewer entry for the issue.

### Expected behavior

That the application crashes without the issue.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/26118718/9d9bc32a-dac3-45a3-90e9-6c765a64343e)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/26118718/d975e50c-155d-4185-bec5-08f1bfcefc6b)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.5: 1.4.240411001

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The crash doesn't seem to occur if "Animation Effects" are turned off in the Windows settings.

**Comment by jaimecbernardo** [comment]
Maybe this is the same as #8605 ?

**Comment by codendone** [comment]
Closing as dup of #8605.
