### ISSUE TITLE
Drag Drop Issue in High Dpi Screen

### ISSUE THREAD

**Issue by ahmadsafi24** [microsoft/microsoft-ui-xaml#9344]
### Describe the bug

Mouse Wheel And Drag Drop not working well In High Dpi (screen scaling 150)

if dpi is 100 drag drop and mouse wheel on a grid is working well but,
if dpi is 150 drag drop and mouse wheel on a grid is working just on small area

### Steps to reproduce the bug

just create an winui3 app and add related mouse events.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.5: 1.4.240411001

### Windows version

Windows 11 (22H2): Build 22621

**Comment by bpulliam** [comment]
Can you post an example project?

**Comment by ahmadsafi24** [comment]
found it app.manifest was removed.
this line in app.manifest fixes the problem.
<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
