### ISSUE TITLE
Background Task + Sqlite

### ISSUE THREAD

**Issue by JozefGula** [microsoft/microsoft-ui-xaml#9351]
Hello, 

I have packaged WinUI3 application (Net8.0). My solution contains 3 projects:

1. MyApplication
2. MyApplication.Component
3. MyApplication.DataSource

Project reference are:
1. MyApplication.Component contains MyApplication.DataSource
2. MyApplication contains MyApplication.DataSource and MyApplication.Component

MyApplication.DataSource uses EF core + Sqlite

If I start MyApplication and call the "DataSource" implementation located in MyApplication.DataSource, everything works correctly.

If background task from MyApplication.Component call the "DataSource" implementation located in MyApplication.DataSource will fail:

**DllNotFoundException: Unable to load DLL 'e_sqlite3' or one of its dependencies: The specified module could not be found. (0x8007007E)**

* my application is "packaged" and the same error occurs when installing and running it in the system and when debugging through Visual Studio.

Windows 10 PRO
Version 22H2
OS Build: 19045.4046
all updates installed

Can anyone advise me on what could be causing the error, or at least point me in the direction of what could be the cause and how to solve it?

Thanks a lot

**Comment by bpulliam** [comment]
Not a WinUI issue.  I would try VS or the SqlLite teams.
