### ISSUE TITLE
Unable to scroll content of new ScrollViewers after closing a window. Issue not present in 1.5 Experimental 1 and earlier

### ISSUE THREAD

**Issue by cwhitlatch** [microsoft/microsoft-ui-xaml#9355]
### Describe the bug

Once a secondary Window created and then closed, all newly created ScrollViewers will no longer scroll. Application must be restarted to correct. Issue began in 1.5.240124002-experimental2 & 1.5.240205001-preview1. 

### Steps to reproduce the bug

The following repro application exhibits the issue. 
[ScrollbarFreezeRepo.zip](https://github.com/microsoft/WindowsAppSDK/files/14338066/ScrollbarFreezeRepo.zip)

### NuGet package version

None

**Comment by DJRM2021** [comment]
This issue also happens across all WinUI 3 controls that have built-in scrollviewer, like the NavigationView, ListView, etc.
