### ISSUE TITLE
Media Keys are not Captured Regardless of Whether the Event is Handled or Not

### ISSUE THREAD

**Issue by iharwell** [microsoft/microsoft-ui-xaml#9369]
### Describe the bug

When handling KeyDown events, media keys are still passed on to other applications even if the event is tagged as handled. In fact, other media will start playing even if the program is halted in the middle of executing its event handler, well before it has a chance to indicate whether the event was handled or not.

### Steps to reproduce the bug

1. Create a Window with a grid as its content.
2. Create a KeyDown handler for the grid, and set "Handled" to true if the virtual key is 0xB3 (the play/pause media key) when cast to an integer.
3. Open a tab in Chrome and navigate to a YouTube video.
4. Ensure the media play key on your keyboard works by switching input focus to Visual Studio and pressing it. The YouTube video should start playing.
5. With a breakpoint in the KeyDown handler, and the Window in focus, and press the media play button.
6. Observe as the breakpoint is hit, and the YouTube video immediately starts playing while the program is halted.

### Expected behavior

When the media key is pressed, no other program should respond until the program in focus has completed its own event handler. In addition, if the program in focus indicates that it has handled the event, no other program should respond to the key press at all. After all, media keys are still keys, and, as such, should behave as other keys do wherein a strict order of execution is maintained throughout the entire event propagation pipeline.

In prior UI frameworks, this sort of behavior was possible by, for instance, hooking into the message loop using HwndSource.AddHook() in WPF. UWP should also be capable of similar functionality through the CoreWindow class.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.5: 1.4.240411001

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Actively playing media in any app will usually capture the media keys at the Windows level, where Windows then won't deliver those keys to other apps. Closing as external.

**Comment by iharwell** [comment]
In this case, are you able to provide guidance on how to achieve a remote control functionality within the WinUI framework? WPF and UWP both support this relatively easily, but there is no obvious way to accomplish it within WinUI 3.

Specifically, how would I receive a media key and consume it so that I can then pass that event on to a separate device on which the media is playing, for instance?

Or does WinUI 3 specifically prohibit anything other than the MediaPlayer with active media from consuming such events? If so, why?

As mentioned, other frameworks do support this. It's clearly a behavior unique to WinUI 3, and thus is an internal issue.
