### ISSUE TITLE
Scroller scroll+zoom leads to wrong position

### ISSUE THREAD

**Issue by adrientetar** [microsoft/microsoft-ui-xaml#937]
**Describe the bug**

I have an issue with Scroller where scrolling and zooming around my content in OnControlLoaded puts me in a wrong position. If I only scroll, I end up in the right position, but if I zoom right after scrolling I'm in a totally off position, even though I specified centerPoint=null so it should zoom around viewport center in that case.

**Steps to reproduce the bug**

Try running my app with [the Zoom instruction](https://github.com/adrientetar/Fonte/blob/470d66ca1204c112d584841c0d6428211db8598a/Fonte.App/Controls/DesignCanvas.xaml.cs#L293-L295) commented and uncommented. When it's commented out, you'll center around the position where I want to be, so you can see metrics lines on the Canvas. With the Zoom, you end up way off center, while the Zoom isn't supposed to translate the Canvas at all (I set centerPoint=null which defaults to viewport center).

**Expected behavior**

**Screenshots**

**Version Info**

2.2.190611001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | X   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | X   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment]
Thanks for trying out Scroller and giving feedback! I'm sure @rbrid would want to take a look.

**Comment by adrientetar** [comment]
@RBrid, I still have the same problem with your updated code from #829 fwiw.

**Comment by RBrid** [comment]
@adrientetar, today the fix for the "scroll+zoom leads to wrong position" bug got merged into master. 
I also spent some time with the Fonte application. Your ViewTo call when the app loads seems to land on the requested view. I did not notice anything wrong at the Scroller level at this point. Replacing it with an old platform ScrollViewer resulted in the same behavior. Maybe you can elaborate on the unexpected Scroller behavior?  Thank you.

**Comment by adrientetar** [comment]
@RBrid, yeah you are right that it behaves correctly. I tried changing to ScrollViewer and indeed I do need to premultiply my offsets to account for the changing zoomFactor (I thought it might be done internally but I see that it makes more sense to let caller do it as needed). My bad and thanks for the help.
