### ISSUE TITLE
NavigationView expand/collapse animation doesn't sync correctly between menu and content

### ISSUE THREAD

**Issue by garrettpauls** [microsoft/microsoft-ui-xaml#9370]
### Describe the bug

When the NavigationView menu expands or collapses inline with the content (for instance, the default NavigationView used in the WinUI 3 Gallery), the animation speed of the menu panel width change doesn't match the speed of the content width change, so you end up with a background flicker on the right side of the window.

This is more noticeable when the content color isn't the same as the window background, but still very abrupt either way. It would be nice if this could be cleaned up.

### Steps to reproduce the bug

1. Add a NavigationView to any application, with menu items and content that is not colored the same as the window background.
2. Click the menu button to expand and collapse the menu, and watch the right side of the window.
3. Notice that there's a flicker of window background (or content getting pushed out of bounds) while the content catches up with the collapsing (or expanding) of the menu panel.

### Expected behavior

The content of the NavigationView should expand and shrink at the same rate as the menu panel, so the background of the window does not get shown (when collapsing the menu), and the main content does not get pushed out of bounds (when expanding the menu).

### Screenshots

![NavigationViewExpandBug](https://github.com/microsoft/microsoft-ui-xaml/assets/670089/179994f1-4d23-438a-af60-e297c60d9886)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.5: 1.4.240411001

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

I also see this on Windows 11 23H2 build 22631.3155

**Comment by ranjeshj** [comment]
Thanks for reporting. There are currently no plans to fix this.
