### ISSUE TITLE
UISettings.ColorValuesChanged not fired

### ISSUE THREAD

**Issue by Arko109** [microsoft/microsoft-ui-xaml#9372]
### Describe the bug

The `UISettings.ColorValuesChanged` event does not work for me.

### Steps to reproduce the bug

1. Create empty project
2. In `MainWindow`, add the following code:
```csharp
public MainWindow()
{
    InitializeComponent();
    var settings = new UISettings();
    settings.ColorValuesChanged += Settings_ColorValuesChanged;
}

private void Settings_ColorValuesChanged(UISettings sender, object args)
{
    Debug.WriteLine("Theme changed");
}
```
3. Change Windows colors, nothing will be printed in the output

### Expected behavior

`Theme changed` printed in the output.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.5: 1.4.240411001

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Actual Windows build: 19045.3930

**Comment by kmgallahan** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/4006

**Comment by DarranRowe** [comment]
One possible thing to try is handle the WM_SETTINGCHANGE message.
WM_SETTINGCHANGE is sent to all top level windows when a system wide setting is changed. What you are looking for is the string value to not be null and, if it isn't null, contains the text ImmersiveColorSet. As a bit of an example:

```
	void main_window::on_settingchange(uint32_t uiaction, const wchar_t *setting)
	{
		//ImmersiveColorSet - changes to the windows colouring, including light/dark theme and border/titlebar colours
		//WindowsThemeElement - changes to colouring of the windows theme
		//uiAction 0x0043 - high contrast theme

		if (setting == nullptr)
		{
			if (uiaction == 0x0043)
			{
				//handle high contrast
			}
		}
		else
		{
			std::wstring_view setting_sv = setting;
			//ImmersiveColorSet
			if (setting_sv == L"ImmersiveColorSet")
			{
				immersive_colours_set();
			}
		}
	}
```

This is likely going to be the best way to handle it on Windows 10, although this is still technically undocumented and unsupported.

**Comment by Arko109** [comment]
For anyone that will have the same question, here's how I did it in C# using the WinUIEx library:

`MainWindow.xaml.cs`
```csharp
private readonly WindowMessageMonitor monitor;
private readonly DispatcherQueue dispatcherQueue;

public MainWindow()
{
    monitor = new WindowMessageMonitor(this);
    monitor.WindowMessageReceived += Monitor_WindowMessageReceived;
    dispatcherQueue = DispatcherQueue.GetForCurrentThread();

    //...
}

private void Monitor_WindowMessageReceived(object? sender, WindowMessageEventArgs e)
{
    if (e.Message.MessageId == 0x001A) //WM_SETTINGCHANGE
    {
        dispatcherQueue.TryEnqueue(() => TitleBarHelper.UpdateTitleBar(ElementTheme.Default));
    }
}
```

`TitleBarHelper` is the default helper generated with Template Studio for WinUI.

I couldn't replicate the C++ code fully, because there's no string in the event args, so I don't have anything to compare "ImmersiveColorSet" to, so I suspect the method is called more often than necessary.

**Comment by fabianoriccardi** [comment]
I think the issue should be reopened because the provided solution seems *temporary*: I think that the official documented C# APIs should provide an event that notifies when the user change system colors. I don't care if the name is `UISettings.ColorValuesChanged` or whatever other class/event name, but this remains a basic feature for modern systems.

**Comment by castorix** [comment]
> I think the issue should be reopened because the provided solution seems _temporary_: I think that the official documented C# APIs should provide an event that notifies when the user change system colors. I don't care if the name is `UISettings.ColorValuesChanged` or whatever other class/event name, but this remains a basic feature for modern systems.

_UISettings.ColorValuesChanged_ works, but it must be declared **global** (like _ThemeSettings_)
Tested on  Windows 10 22H2, Windows app SDK 1.5.24 :

![UISettings](https://github.com/user-attachments/assets/66e8108e-b0dd-4253-9b51-4f0f41995d9d)

**Comment by fabianoriccardi** [comment]
What do you mean with `global`? A static member of a class? I have tried this, but it doesn't work. 
I'm using Win10 22H2 and WASDK v1.5.5.

**Comment by castorix** [comment]
> What do you mean with `global`? A static member of a class? I have tried this, but it doesn't work. I'm using Win10 22H2 and WASDK v1.5.5.

I mean not inside _MainWindow_ constructor :

```
        UISettings settings = null;
        private void Settings_ColorValuesChanged(UISettings sender, object args)
        {
            Console.Beep(4000, 10);
            Debug.WriteLine("Theme changed");
        }
```
in _public MainWindow()_ :

```
settings = new UISettings();
settings.ColorValuesChanged += Settings_ColorValuesChanged;
```

**Comment by fabianoriccardi** [comment]
I have just tried creating a new WinUI project from scratch but no way... I have tried to change both Accent Color and Theme (Light/Dark), but the event is not triggered.

This is the code:

```csharp
public sealed partial class MainWindow : Window
{
    UISettings settings = null;
    private void Settings_ColorValuesChanged(UISettings sender, object args)
    {
        Console.Beep(4000, 10);
        Debug.WriteLine("Theme changed");
    }

    public MainWindow()
    {
        this.InitializeComponent();

        settings = new UISettings();
        settings.ColorValuesChanged += Settings_ColorValuesChanged;
    }

    private void myButton_Click(object sender, RoutedEventArgs e)
    {
        myButton.Content = "Clicked";
    }
}
```

**Comment by castorix** [comment]
> I have just tried creating a new WinUI project from scratch but no way... I have tried to change both Accent Color and Theme (Light/Dark), but the event is not triggered.

Is it Unpackaged ? (with 	_< WindowsPackageType>None< /WindowsPackageType >_ (without spaces...))

**Comment by fabianoriccardi** [comment]
It is packaged... does it work only if unpackaged?

**Comment by castorix** [comment]
> It is packaged... does it work only if unpackaged?

If Packaged, on my Windows 10 OS, only _WM_SETTINGCHANGE_ or _WM_DWMCOLORIZATIONCOLORCHANGED_ messages work.

**Comment by fabianoriccardi** [comment]
So, should the event `ColorValuesChanged` trigger with Packaged application? Both WM_SETTINGCHANGE and WM_DWMCOLORIZATIONCOLORCHANGED seems related to Accent Color.

**Comment by castorix** [comment]
> So, should the event `ColorValuesChanged` trigger with Packaged application? Both WM_SETTINGCHANGE and WM_DWMCOLORIZATIONCOLORCHANGED seems related to Accent Color.

As it had been posted by @DarranRowe, it is not clear : [Events](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#events)
On my Windows 10 OS (22H2),  it only works in Unpackaged app
WM_SETTINGCHANGE  or WM_DWMCOLORIZATIONCOLORCHANGED work for both Unpackaged/Packaged, when Dark/Light mode is changed or Accent color

**Comment by fabianoriccardi** [comment]
Ok that's clear. So, my question will become a feature request: may we have an **official** and **supported** C#/WindowsAppSDK API that allows to listen for theme changes? Of course, I expect this API to work on any both packaged and unpackaged applications and on supported OSes (win11 and win10, which maintains an abundant market share w.r.t. win11).
