### ISSUE TITLE
ScrollView control doesn't scoll.

### ISSUE THREAD

**Issue by Simon-IT** [microsoft/microsoft-ui-xaml#9373]
### Describe the bug

Hi,
creating a very simple C# WinUI 3 desktop app for text scrolling test, I've found a problem if a TextBlock control contained in a ScrollView control are inside a Grid and its row position is not 0: simply in position 1 the vertical scroll bar doesn't appear and so scrolling is impossible.
Thank you for the time !!

### Steps to reproduce the bug

1. Create a simple WinUI 3 C# Desktop app.
2.  In MainWindow.xaml file sets the Window content as:
```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="240"/>
        <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>

    <!-- Use Grid.Row values between 0 (works) and 1 (doesn't work) to see the behaviour -->
    <ScrollView Margin="16" Grid.Row="1">
        <TextBlock TextWrapping="WrapWholeWords">
            TextBlock is the primary control for displaying read-only text in apps. 
            You can use it to display single-line or multi-line text, inline hyperlinks, 
            and text with formatting like bold, italic, or underlined.
            TextBlock is typically easier to use and provides better text rendering 
            performance than RichTextBlock, so it's preferred for most app UI text. 
            It also provides many of the same formatting options for customizing how your 
            text is rendered. Although you can put line breaks in the text, TextBlock is 
            designed to display a single paragraph and doesn't support text indentation. 
            Consider a RichTextBlock if you need support for multiple paragraphs, multi-column text, 
            or inline UI elements like images.
        </TextBlock>
    </ScrollView>
</Grid>
```
3. Resize the window until the viewport doesn't contain all the text

### Expected behavior

Vertical scroll bar should appears in both 0 and 1 grid position

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/24890180/b2ed411d-c442-46a5-9f04-c09920daf90c)

### NuGet package version

None

### Additional context

WinUI 3 - WindowsApp SDK 1.4.5: 1.4.240211001
Windows 11 23H2: Build 22631.3155

**Comment by eduardobragaxz** [comment]
Try RowDefinition Height="*" instead of Auto.

**Comment by Simon-IT** [comment]
Thank you @eduardobragaxz with "*" it works. But, in your opinion, is It a correct behaviour ? Why in row 0 it works ?

**Comment by kmgallahan** [comment]
@Simon-IT Which row it is is doesn't matter.

If you put something in a row with Auto as the height, the row will grow to whatever size the content wants. The ScrollView wants to be as big as its content (the TextBlock), so the grid lets it be that big (hence no scrolling). The row is now running off the bottom of the screen.

If you put something in a row with * as the height the row stretches to fill however much space it can, then tells its children that is how much space they have to work with. The ScrollView now doesn't get to be all big as it wants, so it's height is constrained and scrolling now works.

**Comment by ranjeshj** [comment]
Thanks @kmgallahan for the detailed response. @Simon-IT hope that helps.

**Comment by Simon-IT** [comment]
@Thak you @kmgallahan for the detailed response. Thank you all guys for time.
