### ISSUE TITLE
MapControl has a blue background

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#9377]
### Describe the bug

The default background of the mapcontrol is blue. This should be the background color of the MapControl.Background property instead.

### Steps to reproduce the bug

Launch the mapcontrol. Before it loads the tiles, you'll see the "blue window of death".
Use Two-finger drag to "tilt" the map into 2.5D mode, and zoom out to the entire world. Notice the blue areas above and below
+

### Expected behavior

Background matches the background of my control - at least if it's a solid color brush, you should be able to forward that color to html.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/1378165/5c394846-aae1-41ca-addc-5ec6e9dfed00)

### NuGet package version

1.5.240227000

### Windows version

22H2 (22621.3085)

### Additional context

Problem is caused by this line of code: https://github.com/microsoft/microsoft-ui-xaml/blob/a7cc34079da375f3380a09d1eb75870a700923c2/controls/dev/MapControl/map.html#L19
It looks like some early debugging code that was never cleaned up.

**Comment by gegao18** [comment]
Thanks for reporting and investigating this. We've checked in a fix for our first 1.5 servicing release.

**Comment by riverar** [comment]
@gegao18 What was the change? Is it now wired to the control background?

**Comment by riverar** [comment]
@gegao18 Hello?

**Comment by gegao18** [comment]
For 1.5.1 we just took out the blue background. The maps page now has a transparent background, which will show the default white of the WebView2. I'm reopening this to hook up the map background to the control background for the invalid and zoomed out states.

**Comment by riverar** [comment]
@gegao18 Thanks for the follow up!
