### ISSUE TITLE
Winui 3 background task not run in x64 debug

### ISSUE THREAD

**Issue by jhonToni** [microsoft/microsoft-ui-xaml#9391]
### Describe the bug

When i try to start my background task from visual studio 2022 in x64 debug,  Windows 11 event viewer contain this log:
`Failed to trigger background task with entry point Samples.Tasks.ExampleToastTask and name ExampleToastTask. Error code: 0x80073CFC.`
(The debug working in x86 debug).

### Steps to reproduce the bug

1. I run the application debug for x64 patform in visual studio 2022
2. I manually run the task from visual studio UI

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows 11 (23H2): Build 22631

### Additional context

Repo url: [https://github.com/jhonToni/Winui3BackgroudWorkerBug](https://github.com/jhonToni/Winui3BackgroudWorkerBug)

**Comment by jhonToni** [comment]
Problem solved. The task project was bad configured for the x64 architecture.

**Comment by parko65** [comment]
> Problem solved. The task project was bad configured for the x64 architecture.

I'm trying the code from your repo? Is it in a working state?

**Comment by jhonToni** [comment]
@parko65, the code in the repo was updated with correct configuration.

**Comment by mcash95** [comment]
having the same issue, updated .csproj file already. im in .net9 however, any changes required?
