### ISSUE TITLE
Error: Converter failed to convert value of type 'Windows.Foundation.IReference`1<Microsoft.UI.Xaml.GridLength>' to type 'Double'; 

### ISSUE THREAD

**Issue by snandaworld** [microsoft/microsoft-ui-xaml#9392]
### Describe the bug

Started getting the Below error while Debugging WinUI 3 App with MSIX and Self-contained package after upgrading the Windows app SDK to v.1.5.
**Error:** Converter failed to convert value of type 'Windows.Foundation.IReference`1<Microsoft.UI.Xaml.GridLength>' to type 'Double'; BindingExpression: Path='TemplateSettings.CompactPaneGridLength' DataItem='Microsoft.UI.Xaml.Controls.SplitView'; target element is 'Microsoft.UI.Xaml.Media.Animation.SplineDoubleKeyFrame' (Name='null'); target property is 'Value' (type 'Double'). 

### Steps to reproduce the bug

1. Run any WinUI 3 App with MSIX and Self-contained package in Debug mode and observe the Output window. You will see the error message.

### Expected behavior

Prior to WAS 1.5, this error wasn't seen. 

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23169384/e63eee34-8ddf-481a-b255-1b55919aea05)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by parko65** [comment]
I started seeing this after upgrading WinUI3 app to SDK 1.5 and .net8. I've rolled back to .net7 and latest 1.4 until I understand what detrimental effect this has.

**Comment by ranjeshj** [comment]
Looks like a dup of [9384](https://github.com/microsoft/microsoft-ui-xaml/issues/9384)
