### ISSUE TITLE
Pen input causes the UI to get stuck

### ISSUE THREAD

**Issue by Poker-sang** [microsoft/microsoft-ui-xaml#9402]
### Describe the bug

When using the pen to operate WinUI apps, the interface gets stuck. But the title bar button works fine.

### Steps to reproduce the bug

Use pen to operate a WinUI app.

### Expected behavior

Not stuck

### Screenshots

see https://drive.google.com/file/d/1-rfyMfcFEvmU2nOm7g_LuOg5PcZijiI6/view

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Device: Surface Go 3 Windows 11 23H2

Original issue: <https://github.com/Pixeval/Pixeval/issues/352>

**Comment by codendone** [comment]
We're not able to repro this issue. Can you share a standalone repro app?

**Comment by Poker-sang** [comment]
I'm totally sorry for this. This issue magically disappeared.
