### ISSUE TITLE
Flyout Menus Acrylic Background Bug

### ISSUE THREAD

**Issue by FF69B3** [microsoft/microsoft-ui-xaml#9406]
### Describe the bug

When the menu is first displayed, there is no acrylic background, You need to switch the window once for the acrylic background to work.

### Steps to reproduce the bug

1.run WinUIGallery
2.look Menubar

### Screenshots

![20240306112934](https://github.com/microsoft/microsoft-ui-xaml/assets/94247503/7d65e0b7-302f-436b-be5f-36cebe356782)
![20240306112956](https://github.com/microsoft/microsoft-ui-xaml/assets/94247503/b93bf152-1ddf-4f4d-b94f-7a5ec6335cfe)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows Insider Build (xxxxx), Windows 11 (22H2): Build 22621

### Additional context

Windows11 23H2  22631.3235

**Comment by marticliment** [comment]
This issue also happens on regular Flyout Menus with AppSdk 1.5.0

**Comment by FF69B3** [comment]
> This issue also happens on regular Flyout Menus with AppSdk 1.5.0, and is reproducible on any WinUI3 App

Yes

**Comment by marticliment** [comment]
While this issue has bee fixed on context menus (App Sdk 1.5.1), it is still reproducible on other flyouts such as ComboBoxes, Scrollbars and Menubar items:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/53119851/e4e8d03e-a601-4886-8e71-0015386b934b)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/53119851/f7483347-297d-4b91-be83-6da07d16abc6)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/53119851/7490ab8e-5c6f-4e0d-abd0-c28c23d9dd50)
