### ISSUE TITLE
Regression the position of one of images in MenuFlyoutItem is incorrect

### ISSUE THREAD

**Issue by 0x5bfa** [microsoft/microsoft-ui-xaml#9409]
### Describe the bug

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/62196528/054a93c5-735c-485d-af96-3ddc2daf1794)

### Steps to reproduce the bug

1. Add flyout item more than 2
2. See the icon position is wrong

### Expected behavior

The same position as before.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Fixed in the upcoming 1.5.1 servicing release.

**Comment by 0x5bfa** [comment]
This is not fixed at all.
Let me know how you fixed and verified to have fixed?

**Comment by yaira2** [comment]
More specifically, this issue occurs when the menu item is hidden and then made visible later. The issue does not occur when the item is visible from the start.

**Comment by codendone** [comment]
The scenario @yaira2 mentioned is exactly what the fix was for, but it sounds like the fix wasn't complete.

**Comment by llongley** [comment]
> There's an example app that can repro this issue. https://github.com/files-community/Files Upgrade the version in Files.App.csproj file to repro.

@0x5bfa Could you provide more specific repro steps using this app?  I've brought up the right-click menu in multiple places, but I haven't yet been able to see this repro with the latest version of the Microsoft.WindowsAppSDK NuGet package.

**Comment by yaira2** [comment]
Try right clicking a photo

**Comment by 0x5bfa** [comment]
1. Select an item
2. Right click

In the latest commit, this icon is already hidden to publish a release to the public. Please check out to the Upgrading commit first.

**Comment by llongley** [comment]
I've added some extra checks to ensure that we're in the correct visual state at the right time.  The Files use case should be fixed in the next version of WinAppSDK.

**Comment by yaira2** [comment]
@llongley thank you for the fix.
