### ISSUE TITLE
NavigationView: Unable to set access key on back and settings buttons

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#941]
**Describe the bug**
We cannot set access key on the back or settings buttons in NavigationView.

**Steps to reproduce the bug**
1. Create new app with the following XAML snippet
```xml
<mux:NavigationView PaneDisplayMode="Top" IsBackEnabled="True">
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem AccessKey="A" Content="Item A" KeyTipPlacementMode="Bottom"/>
        <mux:NavigationViewItem AccessKey="B" Content="Item B" KeyTipPlacementMode="Bottom"/>
    </mux:NavigationView.MenuItems>
</mux:NavigationView>
```
2. Launch the application
3. Press the *alt* key
4. The access key tooltips are displayed only for the menu items.

**Expected behavior**
The access key tooltips are displayed for **all** the navigation view items : back, items and settings

**Screenshots**
![image](https://user-images.githubusercontent.com/20152272/60094581-c7fbfe00-974c-11e9-85b7-cb21cd674ed0.png)

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001
Microsoft.UI.Xaml 2.2.190611001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
We should have a way to customize the settings and back button items to provide the access key as well as the keyboard accelerators we might want to use.

**Proposed fix**
[edit by YuliKl]
Add four new properties to NavigationView:
- `SettingsAccessKey` of type String
- `SettingsKeyTipPlacementMode` of type KeyTipPlacementMode
- `BackAcessKey` of type String
- `BackKeyTipPlacementMode` of type KeyTipPlacementMode

My expectation is that these properties are temporary and will be removed in a later WinUI 3.x release to be replaced with a more comprehensive and scale-able solution.

**Comment by jevansaks** [comment]
Thanks for filing @vgromfeld! The back button has some specific keyboard handling already, but it's not implemented as an access key and I don't know if we should allow customizing it. @yulikl to noodle on this.

**Comment by YuliKl** [comment]
@vgromfeld, do you think this bug would be resolved if we implemented #944?

**Comment by vgromfeld** [comment]
Implementing #944 will not solve the issue. We need to be able to set at least the `AccessKey` property on the internal back button. We cannot do that through `ICommand`
We may also need to set `KeyTipPlacementMode` for the back button but this is something the `NavigationView` can do on its own based on its display mode (bottom key tip placement when in top mode, right key tip placement when in left pane mode).

I can propose the following ways to allow us to make it work:
- Have a fixed predefined access key on the `NavigationView` template
  - This would be a quick fix but we will loose the ability to localize the access keys to match the button label.
- Have pass through properties on  `NavigationView`; something like `BackButtonAccessKey` 
  - This gives us the flexibility to configure the access key but is not the usual way
- Allow us to provide a custom back button and use it instead of the default one
  - This would give us the liberty to configure the back button as we want but I don't know if it can break some inner behaviors/expectations between `NavigationView` and its back button.
  - If no button is provided, the `NavigationView` will still use its own button

**Comment by jevansaks** [comment]
> We cannot do that through `ICommand`

In 1809 we added XamlUICommand which gives us a way to package up AccessKey+KeyboardAccelerator+Text to be passed through to the target to enable this scenario. Flat properties might still preferable, but XamlUICommand is a nice strategy for not having an explosion of properties.

**Comment by vgromfeld** [comment]
@jevansaks, agreed, `XamlUICommand` is a very nice addition to the platform but as far as I know it is not available on Windows builds older than 1809. I don't know how complicated it would be but is it something that can be added in the Microsoft-ui-xaml package ?

**Comment by jevansaks** [comment]
> I don't know how complicated it would be but is it something that can be added in the Microsoft-ui-xaml package ?

That's the perennial question! As with most things the answer is we have to wait for WinUI 3.0. 

Do you think you need a workaround in the short term? If so, we can look into adding some stopgap properties that we would then plan to remove later.

**Comment by vgromfeld** [comment]
Looking at our timeline and the WinUI 3.0 timeline (stable release in 2020), I think we will need a workaround in the short term.

**Comment by YuliKl** [comment]
Property explosion feels like a real concern, especially given the number of properties on UIElement that had been added to support key tips. But I agree that we have a functional gap here with a more immediate need to address it. I've added a **Proposed fix** subsection to the description.

**Comment by jevansaks** [comment]
Thanks. We'll add these properties to unblock the scenario for now, but we need to figure this out more holistically going forward.

**Comment by RBrid** [comment]
@jevansaks, @YuliKl, are we sure we want to introduce 4 new NavigationView properties for the short term?

I wrote this utility method which works for 19H1 at least (it may need tweaks on RS versions):
```
private void SetKeyTips(
    NavigationView navView,
    string backAccessKey,
    string settingsAccessKey,
    KeyTipPlacementMode keyTipPlacementMode)
{
    Grid rootGrid = VisualTreeHelper.GetChild(navView, 0) as Grid;
    Grid paneToggleButtonGrid = VisualTreeHelper.GetChild(rootGrid, 0) as Grid;
    Grid buttonHolderGrid = VisualTreeHelper.GetChild(paneToggleButtonGrid, 1) as Grid;
    Button navigationViewBackButton = VisualTreeHelper.GetChild(buttonHolderGrid, 0) as Button;

    navigationViewBackButton.AccessKey = backAccessKey;
    navigationViewBackButton.KeyTipPlacementMode = keyTipPlacementMode;

    Grid grid = VisualTreeHelper.GetChild(rootGrid, 1) as Grid;
    StackPanel topNavArea = VisualTreeHelper.GetChild(grid, 0) as StackPanel;
    Grid topNavGrid = VisualTreeHelper.GetChild(topNavArea, 1) as Grid;
    NavigationViewItem settingsTopNavPaneItem = VisualTreeHelper.GetChild(topNavGrid, 7) as NavigationViewItem;

    settingsTopNavPaneItem.AccessKey = settingsAccessKey;
    settingsTopNavPaneItem.KeyTipPlacementMode = keyTipPlacementMode;
}
```

By calling it like this
```
private void NavigationViewTestPage_Loaded(object sender, RoutedEventArgs e)
{
    SetKeyTips(this.navView, "K", "S", KeyTipPlacementMode.Bottom);
}
```
you get the expected result:
![image](https://user-images.githubusercontent.com/36547063/60629986-e85f3480-9dac-11e9-815a-0922e0725e8d.png)

Thoughts? Thanks.

**Comment by YuliKl** [comment]
@vgromfeld, what is the Min version your app supports?

**Comment by vgromfeld** [comment]
Our min app version is RS3

**Comment by vgromfeld** [comment]
I've integrated the following code in our app and it works (tested on RS3 and 19H1).

```csharp
private void OnNavigationBarLoaded(object sender, RoutedEventArgs e)
{
    var rootGrid = VisualTreeHelper.GetChild(navigationBar, 0) as Grid;
    var paneToggleButtonGrid = VisualTreeHelper.GetChild(rootGrid, 0) as Grid;
    var buttonHolderGrid = VisualTreeHelper.GetChild(paneToggleButtonGrid, 1) as Grid;
    var navigationViewBackButton = VisualTreeHelper.GetChild(buttonHolderGrid, 0) as Button;

    navigationViewBackButton.AccessKey = "A";
    navigationViewBackButton.KeyTipPlacementMode = Windows.UI.Xaml.Input.KeyTipPlacementMode.Bottom;
}
```
I've only tested the back button because we are not using the default settings button because of #591.

Do you plan to integrate the utility method soon ?

**Comment by RBrid** [comment]
@vgromfeld, thank you for testing that code. Given this workaround, we are not planning to do a product change for this in the coming WinUI 2.2 release. We will reconsider this for a later release. 

In the meantime, you should use the kind of code above in your application as a workaround. Sorry for the inconvenience.

**Comment by YuliKl** [comment]
I've opened a doc bug to share this workaround more broadly. Closing this issue as the immediate problem is resolved.
