### ISSUE TITLE
Proposal: improve DragEventArgs.AcceptedOperation and AllowedOperations docs

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/microsoft-ui-xaml#9411]
Thank you!
# Proposal: improve DragEventArgs.AcceptedOperation and AllowedOperations docs

## Summary
DragEventArgs.AcceptedOperation and AllowedOperations have an ambiguous name. Please add more content to point out and clarify the difference between the two.

## Links
- https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.drageventargs.acceptedoperation
- https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.drageventargs.allowedoperations

**Comment by jwmsft** [comment]
Thanks for raising this issue. It appears that the AcceptedOperations property incorrectly had the description for the AllowedOperations property, which is indeed confusing. I've corrected the documentation and added more information to clarify the difference between these properties.
