### ISSUE TITLE
Two runtimeclass with same property name but different type cause cannot convert argument error

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9419]
### Describe the bug

Same with #8994, but WinUI3 C++ project gives a different error.

### Steps to reproduce the bug

1. Create a C++ WinUI3 project
2. Update every nuget to latest, I have
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/5f3564b9-a9c2-45e1-997c-def25bc11408)

4. Create two runtimeclass
```
    [bindable]
    [default_interface]
    runtimeclass MyClass1 
    {
        MyClass1();
        Int32 MyProperty;
    }

    [bindable]
    [default_interface]
    runtimeclass MyClass2 
    {
        MyClass2();
        Object MyProperty;
    }
```
5. Build project, you get
```
error C2665: 'winrt::_5_Function_Template_Conflict_WinUI3::implementation::MyClass2::MyProperty': no overloaded function could convert all the argument types
1>(compiling source file '/MyClass2.cpp')
1>C:\Users\Peter\Desktop\WinUI-Bug\5-Function-Template-Conflict\5-Function-Template-Conflict-WinUI3\MyClass2.cpp(14,20):
1>could be 'void winrt::_5_Function_Template_Conflict_WinUI3::implementation::MyClass2::MyProperty(int32_t)'
1>	C:\Users\Peter\Desktop\WinUI-Bug\5-Function-Template-Conflict\5-Function-Template-Conflict-WinUI3\Generated Files\winrt\_5_Function_Template_Conflict_WinUI3.h(94,25):
1>	'void winrt::_5_Function_Template_Conflict_WinUI3::implementation::MyClass2::MyProperty(int32_t)': cannot convert argument 1 from 'const winrt::Windows::Foundation::IInspectable' to 'int32_t'
1>		C:\Users\Peter\Desktop\WinUI-Bug\5-Function-Template-Conflict\5-Function-Template-Conflict-WinUI3\Generated Files\winrt\_5_Function_Template_Conflict_WinUI3.h(94,37):
1>		No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

[Repo here](https://github.com/HO-COOH/WinUI-Bug/tree/main/5-Function-Template-Conflict)
### Expected behavior

Builds fine

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows 10 (1809): Build 17763

**Comment by codendone** [comment]
It looks like your repro specifies `Object MyProperty;` as the property in the idl file but still specifies `int32_t` as the type in the .h and .cpp files:
```
        int32_t MyProperty();
        void MyProperty(int32_t value);
```

Fixing the code to match the changed property type in the idl should fix the compile issue.

**Comment by HO-COOH** [comment]
My bad. I have updated the code, and it seems this issue does get fixed for WinUI3. And UWP's issue remains. Please also take a look at #8994 if possible, thanks!
