### ISSUE TITLE
Software keyboard broken in 1.5

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#9420]
### Describe the bug

After updating to 1.5, the software keyboard does not popup anymore when selecting a textbox with touch.

### Steps to reproduce the bug

Can be reproduced in WinUI Gallery

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by adamfierek** [comment]
On 1.5.1 still not working. That kind of bug is acceptable in Experimental release but not in Stable.

**Comment by baaaaif** [comment]
can't test it myself, but my upvote for an asap fix. Very important (critical) for our customer!

**Comment by MichalMucek** [comment]
The keyboard is also not shown for the other text-based -Box controls (PasswordBox, RichTextBox, etc.). It doesn't work for editable ComboBox too.

**Comment by gegao18** [comment]
Hi, thanks for reporting this. The fix for this will be part of 1.5.2.

**Comment by baaaaif** [comment]
@gegao18 this issue isn't mentioned in the 1.5.2 release notes. Is this really included in 1.5.2?

**Comment by gegao18** [comment]
This was the same bug as the IME positioning issue fixed in 1.5.2. We didn't have the correct coordinates for the TextBox at high display scales, which meant the soft keyboard didn't realize the TextBox was focused.

> Fixed an issue where a textbox input method editor (IME) window would be incorrectly positioned when running at a scale factor other than 100%. For more info, see GitHub issue [#9382](https://github.com/microsoft/microsoft-ui-xaml/issues/9382).
