### ISSUE TITLE
NavigationView requires double-click to expand sub-menus

### ISSUE THREAD

**Issue by jpageacsys** [microsoft/microsoft-ui-xaml#9423]
### Describe the bug

After updating from 1.4.240211001 to 1.5.240227000 navigation view. This seems universal. I created a test app and switching versions causes this issue. Switching back fixes it. the WinUI 3 Gallery app has this issue as well and in the example text it states:
"In both Top and Left modes, clicking the arrows on NavigationViewItems will expand or collapse the subtree. Clicking or tapping elsewhere on the NavigationViewItem will collapse or expand the subtree."
If this is intended behavior, the documentation should reflect it, otherwise this looks like a bug.

### Steps to reproduce the bug

Create a default WinUI 3 app.
Make a basic NavigationView control with sub menu items.
```
<Window
    x:Class="NavTest.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NavTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <NavigationView>
        <NavigationView.MenuItems>
            <NavigationViewItem Content="Home" Tag="home" Icon="Home"/>
            <NavigationViewItem Content="Profile" Tag="profile" Icon="Contact">
                <NavigationViewItem.MenuItems>
                    <NavigationViewItem Content="Edit" Tag="edit" Icon="Edit"/>
                    <NavigationViewItem Content="View" Tag="view" Icon="View"/>
                </NavigationViewItem.MenuItems>
            </NavigationViewItem>
        </NavigationView.MenuItems>
        <Frame x:Name="ContentFrame"/>
    </NavigationView>
</Window>
```
Expanding requires a double click.

### Expected behavior

I expect a click or tap on a parent NavigationViewItem to expand or collapse the submenu.

### NuGet package version

Windows App SDK 1.5.0: 1.5.240227000

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

### Additional context

My windows OS build is 22631.3235 Version 23H2 Windows 11 Pro

**Comment by duncanmacmichael** [comment]
Fixed in 1.5.1, closing issue.
