### ISSUE TITLE
Clicking on NavigationView's NavigationViewItem chevron displays empty child list

### ISSUE THREAD

**Issue by tflopez** [microsoft/microsoft-ui-xaml#9426]
### Describe the bug

When the `NavigationView.PaneDisplayMode` is set to `Top`, clicking on the expand/collapse chevron on a child `NavigationViewItem` with children displays a blank pane rather than a list of child items.  Clicking on the `NavigationViewItem`'s label or icon does show the list of children as expected.  This is new behavior in Microsoft.WindowsAppSDK 1.5.240227000.  Microsoft.WindowsAppSDK 1.4.240211001 shows the child list regardless of where you click in the child `NavigationViewItem`.

When the `NavigationView.PaneDisplayMode` is set to `Left`, clicking on the expand/collapse chevron does not expand the `NavigationViewItem`'s node to display its children.  Double-clicking on the chevron does expand the node, however.

### Steps to reproduce the bug

1. Start the attached app
2. Click on the chevron next to the "Account" item
3. See the blank pane

[TestApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/14564850/TestApp.zip)

### Expected behavior

Clicking on the expand/collapse chevron on a `NavigationViewItem` with children will open and display its list of children.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/151940189/b889d89b-6680-40a6-91c7-3c2985842dc0)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/151940189/3aaaa700-7b35-49a6-ae64-8bc9a9a39b12)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (21H2): Build 19044

### Additional context

Thank you!

**Comment by codendone** [comment]
Fixed in the upcoming 1.5 servicing release.

**Comment by tflopez** [comment]
Thank you!
