### ISSUE TITLE
NavigationViewItems cannot be interacted with after first touch

### ISSUE THREAD

**Issue by ojhad** [microsoft/microsoft-ui-xaml#9429]
### Describe the bug

When NavigationViewItems are interacted with using touch, they get stuck and you can't interact with them again. There's no way to get them to recover. 

### Steps to reproduce the bug

1. Open WinUI3 Gallery
2. Tap on a NavigationViewItem in the NavigationView on the left
3. Tap a different NavigationViewItem
4. Try and tap the NavigationViewItem from step 2, observe how it does not get selected

### Expected behavior

You should be able to select the NavigationViewItem again

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows Insider Build (xxxxx)

**Comment by duncanmacmichael** [comment]
Fixed in 1.5.1, closing issue.
