### ISSUE TITLE
Popup Overlay Incorrect in Scale/Transform Scenarios -- Regression after 1.3.230724000

### ISSUE THREAD

**Issue by cwhitlatch** [microsoft/microsoft-ui-xaml#9433]
### Describe the bug

If a parent container of a Popup implements a transform or changes scale, the overlay ignores and does not adjust size. Mouse over and click behavior will also be incorrect. The root issue appears to be a regression when ShouldConstrainToRootBounds was introduced. 1.3.230724000 and earlier work properly and overlay content is scaled/located correctly. 

Sample app demonstrating the issue:  [PopupSizeIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/14582420/PopupSizeIssue.zip)

### Steps to reproduce the bug

Wrap a combobox within a LayoutTransformControl with scaling applied. 

Sample App: [PopupSizeIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/14582420/PopupSizeIssue.zip)

### Expected behavior

Popup overlay should be sized properly to the scale/transform applied.

### Screenshots

Using Live Visual Tree will show the PopupBorder being sized correctly and the overlay being incorrect:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/833262/0afbc275-b9ac-4b59-9b5f-d3776eae06cb)

From the sample app, the incorrect layout:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/833262/26ef1c7d-3c3b-478b-81e5-81fdabd12101)

And the correct layout if running 1.3.230724000 or earlier:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/833262/6d1d4003-0ab7-43bc-99c6-4d7c3084d83a)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

All Popups exhibit this issue, regardless of where they are defined. ShouldConstrainToRootBounds True/False both exhibit the issue.

**Comment by gegao18** [comment]
Thanks for reporting this. We have a fix for this issue in WASDK 1.5.2.
