### ISSUE TITLE
Crash when accessing new WebView2 types in WinAppSDK 1.5.240311000 - e.g. `CoreWebView2EnvironmentOptions.AreBrowserExtensionsEnabled`

### ISSUE THREAD

**Issue by softworkz** [microsoft/microsoft-ui-xaml#9437]
### Describe the bug

There appears to be a mistake in compilation of WebView2Core bindings in WinAppSDK 1.5.

Newly added members (since 1.4) cannot be invoked.

#### Repro project here: https://github.com/softworkz/WinUI3WebView2ExtensionsBug

.
Or just execute this code snippet in a C# WinUI3 project, updated to WinAppSDK 1.5.240311000:

```cs
            var options = new CoreWebView2EnvironmentOptions();
            options.AdditionalBrowserArguments = "--enable-disble ";
            options.AreBrowserExtensionsEnabled = true;
```

`AdditionalBrowserArguments` can be set but `AreBrowserExtensionsEnabled` "crashes" (or errors).

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/4985349/aecea58a-38ec-4c00-9316-6d761d3f7448)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/4985349/db79d1e6-a2f8-4eab-af34-2c70f95bf646)

### Expected behavior

Properties and methods can be accessed without error.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The WinAppSDK runtime 1.5.240311000 includes `Microsoft.Web.WebView2.Core` version 1.0.2210.55.

But WinAppSDK appears to be compiled with WebView2Version set to 1.0.1823.32 - which is still the same as of version 1.4.x.

I'll submit a PR in a moment from which I think (well - cannot compile this mess) that it is the root cause of this.

**Comment by softworkz** [comment]
A few hours ago, I was able to find a workaround:

`CoreWebView2.Profile.AddBrowserExtensionAsync()` can be substituted by adding this

```
 --load-extension=\"{extensionDir}\" 
```

And  `CoreWebView2EnvironmentOptions.AreBrowserExtensionsEnabled ` can be replaced by this undocumented command line switch:

```
--embedded-browser-webview-enable-extension
```

Thanks to that, it's no longer pressing issue from my side. I haven't checked whether and how many other API members are affected besides these two, though.

**Comment by DmitriyKomin** [comment]
@softworkz, thank you for reporting this, and also for following up with the workaround :-). We've root-caused this to an issue in the CoreWebview2 SDK - the underlying _struct EnvironmentOptionsCom_ does not implement _ICoreWebView2EnvironmentOptions6_ declaring _AreBrowserExtensionsEnabled_. The accidental accidental omission is limited this interface & API, other new WebView2 APIs exposed in WASDK 1.5 are not affected.

You've already opened MicrosoftEdge/WebView2Feedback#4421, so we'll use that to track the underlying issue.

**Comment by softworkz** [comment]
@DmitriyKomin - Thanks for following up and investigating!
