### ISSUE TITLE
TextBox in WinUI3 cannot invoke IME when the OutputType is Exe

### ISSUE THREAD

**Issue by myot233** [microsoft/microsoft-ui-xaml#9446]
### Describe the bug

the bug is the same as #8202 

### Steps to reproduce the bug

1.Chage Project 's OutputType from WinExe to Exe
2.Create a new TextBox
3.Focus on the TextBox and type in it, try to switch the input method, but you will find that it doesn't work 

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Dup of #9420.
