### ISSUE TITLE
NavigationView hardcodes 8px bottom margin

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#945]
**Describe the bug**
In our application we want to be able to hide the navigation view. To do so, we have defined our application layout as follow:
```xml
<Grid Background="Blue">
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>
    <mux:NavigationView
        Background="Red"
        IsBackEnabled="True"
        PaneDisplayMode="Top">
        <mux:NavigationView.MenuItems>
            <mux:NavigationViewItem Content="Item A" />
            <mux:NavigationViewItem Content="Item B" />
        </mux:NavigationView.MenuItems>
        <mux:NavigationView.PaneFooter>
            <mux:NavigationViewItem Icon="People" />
        </mux:NavigationView.PaneFooter>
    </mux:NavigationView>
    <Frame Grid.Row="1" Background="Green" />
</Grid>
```
We are only using the top navigation bar of the `NavigationView`. The content of the application will go in a separate row of our main grid.

The `NavigationView` is displaying an unexpected empty line of 8px under the navigation menu items.

**Steps to reproduce the bug**
1. Create new application and copy the code snippet from above
2. Run the application
3. Notice the red line under the blue `NavigationView` and the green content `Frame`
![image](https://user-images.githubusercontent.com/20152272/60102477-11087e00-975e-11e9-86df-d8d856e2c91e.png)

**Expected behavior**
I shouldn't see any red line between the navigation bar and the content.

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001
Microsoft.UI.Xaml 2.2.190611001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I've been able to workaround this issue by retemplating the control and removing the 8px bottom margin from `PaneToggleButtonGrid`. This is working in my case (`PaneDisplayMode="Top"`) but might not be generic enough to address all the cases.

**Comment by jevansaks** [comment]
Thanks for reporting this @vgromfeld! Is this margin only present when you have no content? If there was Content that filled the window, would the 8px be present at the bottom instead or is it still at the top?

**Comment by YuliKl** [comment]
I initially thought that this issue might be related to #47, but on closer inspection looks like different margins are involved.

>We are only using the top navigation bar of the NavigationView. The content of the application will go in a separate row of our main grid.

We didn't really design NavigationView to be used in this way and I'm actually very curious why you've chosen not to utilize NavigationView's content area.

> I've been able to workaround this issue by retemplating the control and removing the 8px bottom margin from PaneToggleButtonGrid. This is working in my case (PaneDisplayMode="Top") but might not be generic enough to address all the cases.

PaneToggleButtonGrid holds the hamburger button. I believe that in a majority of use cases the Grid's 8px bottom margin is desirable and forces a separation between the hamburger button and everything bellow it. So I don't think it makes sense to remove this margin. 

To avoid forcing apps to retemplate, we can expose the margin as a resource, something like *PaneToggleButtonContainerMargin*, instead of hardcoding  the Grid's `Margin="0,0,0,8"` into the template.

**Comment by mdtauk** [comment]
Maybe the Pane part of the control could become a primitive so this scenario could be better supported in the future, but yea, its a bit odd that they chose not to put the stuff in the Content area.

**Comment by vgromfeld** [comment]
@jevansaks, the margin is always there whether there is content or not. I've built a quick sample app to set the content inside (left pane) and outside (right pane) of `NavigationView`:
![image](https://user-images.githubusercontent.com/20152272/60266957-67ee8e80-98e9-11e9-9c61-3bb07f31d57b.png)

As you can see the margin is still there when the content is inside `NavigationView` but, it is not visible. It is "drawn" behind the content. 

@YuliKl, we choose to not use the `NavigationView` content because we want to be able to fully hide all the navigation elements when entering in some UI state. We are basically keeping only our content in the window.

Adding a *PaneToggleButtonContainerMargin* resource can help to avoid the retemplating but in the mean time, can't you just set the margin directly on the hamburger button (since it seems needed only for this one) and avoid the need for custom resource ?

**Comment by jevansaks** [comment]
> Adding a _PaneToggleButtonContainerMargin_ resource can help to avoid the retemplating but in the mean time, can't you just set the margin directly on the hamburger button (since it seems needed only for this one) and avoid the need for custom resource ?

Can you tell me what you mean? The margin is here: https://github.com/microsoft/microsoft-ui-xaml/blob/82edd199316795fc4fdd83565f9e323fa5383474/dev/NavigationView/NavigationView.xaml#L150

Oh I think I see you're saying put the margin on the TogglePaneButton only so that the margin only comes in for left nav mode or when the hamburger button is visible?

**Comment by vgromfeld** [comment]
> Oh I think I see you're saying put the margin on the TogglePaneButton only so that the margin only comes in for left nav mode or when the hamburger button is visible?
Yes, doing that will avoid exposing too much of the internal layout

**Comment by YuliKl** [comment]
The PaneToggleButtonGrid holds the back and hamburger buttons. These buttons are sometimes side-by-side, sometimes stack one on top of the other, and sometimes collapsed entirely. Setting an 8px margin only on the hamburger button may not preserve the correct horizontal alignment between the hamburger and back buttons.

**Comment by dotMorten** [comment]
> Maybe the Pane part of the control could become a primitive so this scenario could be better supported in the future, 

I like this idea. I could definitely have used that when porting Xamarin.Forms' Shell to UWP

**Comment by chingucoding** [comment]
@YuliKl @StephenLPeters Is it fine to remove the margin as it doesn't seem to make a difference and causes some spacing issues?

**Comment by StephenLPeters** [comment]
After reading the thread I think it would be safe but I'm not positive.  I don't think there would be a breaking change but I'm not sure if it is present for a reason.

**Comment by chingucoding** [comment]
Seems like that margin has been here since the initial commit on the GitHub repository. This might be a long shot but @ojhad, do you know why this margin is there even though it doesn't seem to make a difference?

**Comment by aqibbanday** [comment]
I see the PaneToggleButtonGrid Margin="0,0,0,8" has been removed from https://github.com/microsoft/microsoft-ui-xaml/blob/82edd199316795fc4fdd83565f9e323fa5383474/dev/NavigationView/NavigationView.xaml#L150 but still exists in NavigationView_v1.xaml any update on what should be done?
