### ISSUE TITLE
MapControl: Scrolling isn't responsive

### ISSUE THREAD

**Issue by tipa** [microsoft/microsoft-ui-xaml#9456]
### Describe the bug

When using the mouse wheel to scroll in or out of the MapControl there is delay before the zooming animation starts

### Steps to reproduce the bug

1. Put MapControl in Page
2. Use mouse wheel to scroll in or out
3 Observe delay 

The map only starts zooming after the scrolling action has completed.
Some mice have an "infinte scroll" (https://www.youtube.com/watch?v=5r5VRevVLJg) which makes the issue even more apparent - the zooming can delay multiple seconds

### Expected behavior

The map reacts immediately and zooms in or out accordingly

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
@tipa thanks for the report. I don't see the delay in Gallery. I'm curious if this is a network issue. The infinite scroll wheel is interesting - the behavior you are going to get is what the underlying Azure maps behavior.

**Comment by kmahone** [comment]
The Xaml MapControl is using WebView2 to show an Azure Maps web control. I can repro something similar to what you describe with a logitech mx master. If I spin the mouse wheel it starts to zoom in slowly and then suddenly zooms in very quickly. I can also reproduce the same behavior on this Azure Maps demo page: https://demo.azuremaps.com/
Since this is the behavior of the Azure Maps html control we cannot fix this in the Xaml Map control which wraps the web control.

**Comment by tipa** [comment]
The problem was not present on the UWP Maps control so I would argue you could fix it by not using the Azure Maps web control, but implement a native control. Please reopen this issue.

**Comment by kmahone** [comment]
I will pass on the bug report about the scrolling behavior to the Azure Maps team.

Do you hit the same issue on that azure maps demo page, or is it only in the Xaml MapControl?

**Comment by tipa** [comment]
Yes it's clearly an Azure Maps problem, I also see it on https://www.bing.com/maps.
Please just make a native map control, similar to the one on UWP. The new one is **so** far from usable, I highly doubt it ever will be: https://github.com/microsoft/microsoft-ui-xaml/issues?q=is%3Aopen+is%3Aissue+mapcontrol+
iOS & macOS have a native map controls, Android has a native map control, this Azure Maps web wrapper thing has no future.

**Comment by tipa** [comment]
@kmahone What MapControl is the Microsoft Maps app using, which comes preinstalled on Windows? It does not show this horrible scrolling lag.
Is there now a bug report for the Azure Maps team that can be publicly tracked? I have the gut feeling that this won't be fixed anytime soon...

**Comment by duncanmacmichael** [comment]
> @kmahone What MapControl is the Microsoft Maps app using, which comes preinstalled on Windows? It does not show this horrible scrolling lag. Is there now a bug report for the Azure Maps team that can be publicly tracked? I have the gut feeling that this won't be fixed anytime soon...

The inbox Microsoft Maps app uses the UWP Maps control. We checked with the Azure Maps team and they don't track bugs publicly, but we did pass this along to them which is the best we can do for now. Thanks for your feedback!
