### ISSUE TITLE
WinUI3 XAML Custom Control: Label Text Not Displaying for Multiple Instances Correctly

### ISSUE THREAD

**Issue by Sam-aki** [microsoft/microsoft-ui-xaml#9462]
### Describe the bug

In WinUI3, when creating a custom control and placing multiple controls, the text displayed by the string property named "Label" is only displayed on one control.

reference:
[Build XAML controls with C#](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-csharp-winui-3) 

### Steps to reproduce the bug

1. Create a App and Custom Control according to "[Build XAML controls with C#](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/xaml-templated-controls-csharp-winui-3)"
![custom_xamlcode](https://github.com/microsoft/microsoft-ui-xaml/assets/113489176/9f7c45c1-ec67-4149-b7fc-b5210b7440b8)
![control_behindcode](https://github.com/microsoft/microsoft-ui-xaml/assets/113489176/ed68df16-f757-40a0-be1a-06dcf37c6bab)

2. Place two or more controls
![xamlcode](https://github.com/microsoft/microsoft-ui-xaml/assets/113489176/3d67e534-4187-42bd-a69a-6f133f6cfed3)

3. No Label is displayed on one control.
![result](https://github.com/microsoft/microsoft-ui-xaml/assets/113489176/58ca590e-0827-4727-ae51-485353db1802)

### Expected behavior

i believe that all placed controls should display the label we set for each of them.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
@Sam-aki I just tried this and it works as expected. Can you share your project?

**Comment by Sam-aki** [comment]
@ranjeshj  thank you for your reply. i share [the project](https://github.com/Sam-aki/BgLabelControl-)

**Comment by ranjeshj** [comment]
@Sam-aki Thanks for sharing the app. I see the issue now. The dependency property needs be static.
```
  public **static** DependencyProperty LabelProperty = DependencyProperty.Register(
              nameof(Label),
              typeof(string),
              typeof(BgLabelControl),
              new PropertyMetadata(default(string), new PropertyChangedCallback(OnLabelChanged)));
```
If you are using VisualStudio, type 'propdp' and hit the tab key. That will autogenerate the dependency property for you the correct way. I find that snippet quite useful.

**Comment by Sam-aki** [comment]
I didn't know it. Thanks for the info.
