### ISSUE TITLE
Proposal:Visual designer for WinUI3

### ISSUE THREAD

**Issue by kmilch** [microsoft/microsoft-ui-xaml#9465]
It has been over two years now.

**Comment by xperiandri** [comment]
Any updates?

**Comment by codendone** [comment]
Closing as dup of #5917.

**Comment by sasakrsmanovic** [comment]
It will be of interest to anyone searching for a Visual Designer.... Hot Design from Uno Platform achieves this goal of being a Visual designer for WinUI3 (and other targets) 
https://github.com/unoplatform/uno/discussions/18833
