### ISSUE TITLE
Symbol Icon shows wrong symbol for FullScreen

### ISSUE THREAD

**Issue by insomniachi** [microsoft/microsoft-ui-xaml#9467]
### Describe the bug

SymbolIcon for enum FullScreen shows wrong symbol

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/6525704/93107a43-93fa-4362-a258-6a15880f6575)

instead of 

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/6525704/9f77765b-43d3-41f1-885e-71e1eb2ee075)

### Steps to reproduce the bug

```<SymbolIcon Symbol="FullScreen" />```

### Expected behavior

show correct symbol

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

**Comment by karkarl** [comment]
Fixed - [Bug 49621301](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/49621301): [GitHub] Symbol Icon shows wrong symbol for FullScreen
