### ISSUE TITLE
How to pass package family name in ms-settings uri?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#9470]
### Describe the bug

How to pass package family name in ms-settings uri?

如图所描述，ms-settings:appfeatures-app URI 可以传递 packagefamilyname 作为可选参数，所以想请求一下，这个参数如何传递，有相应的示例代码吗？
As described in the figure, ms-settings: AppFeature-App URI can pass packagefamilyname as an optional parameter, so I would like to ask how to pass this parameter, is there a corresponding example code?
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/49179966/dbb7b0ca-f28e-4932-86d5-a5ab01ee7450)

### Steps to reproduce the bug

See describe

### Expected behavior

See describe

### Screenshots

See describe

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Let's track this at microsoft/WindowsAppSDK#4279.
