### ISSUE TITLE
FilePicker does not open when running as administrator

### ISSUE THREAD

**Issue by shinta0806** [microsoft/microsoft-ui-xaml#9476]
### Describe the bug

FilePicker does not open when running as administrator.
(Attempted to perform an unauthorized operation exception)
(Open when running as a general user)

### Steps to reproduce the bug

1. Run WinUI 3 program as administrator.
2. Open FileSavePicker.
3. Attempted to perform an unauthorized operation exception

Sample program in GitHub:
https://github.com/shinta0806/TestFilePicker
(This sample program is for #9387, but reproduce this bug, too)

### Screenshots

![1](https://github.com/microsoft/microsoft-ui-xaml/assets/7196473/61d00087-4bb3-43e7-a0c1-95ff092b395d)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by DarranRowe** [comment]
Yes, this is a pretty well known issue in Windows. There is also a report over on the WindowsAppSDK repository. microsoft/WindowsAppSDK#2504

**Comment by shinta0806** [comment]
Thank you!
