### ISSUE TITLE
Touch keyboard is not shown in Windows App SDK 1.5

### ISSUE THREAD

**Issue by MichalMucek** [microsoft/microsoft-ui-xaml#9479]
### Describe the bug

The system touch keyboard stopped showing in Windows App SDK 1.5 when a TextBox or PasswordBox was tapped. This can be reproduced by WinUI 3 Gallery, ver. 2.4.1.0. The issue occurs on Windows 10 and 11.

### Steps to reproduce the bug

1. Install WinUI 3 Gallery, version 2.4.1.0 on a tablet or other devices with a touch screen (Windows 10 or 11).
2. Open the application and tap on any TextBox or PasswordBox (it can be the search field in the navigation menu).

### Expected behavior

The system touch keyboard should be shown.

### NuGet package version

Windows App SDK 1.5.1: 1.5.240311000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update), Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ranjeshj** [comment]
dup of https://github.com/microsoft/microsoft-ui-xaml/issues/9420
