### ISSUE TITLE
Minimize button display status issue when switching apps

### ISSUE THREAD

**Issue by tingjiangcao** [microsoft/microsoft-ui-xaml#9481]
### Describe the bug

Minimize the program first.

In "windows+tab" or "alt+tab" interface, the minimize button is "hover" style.
It should be the default style

### Steps to reproduce the bug

1.Minimize the program
2."windows+tab" or "alt+tab"

### Screenshots

![Snipaste_2024-03-24_18-12-13](https://github.com/microsoft/microsoft-ui-xaml/assets/51285674/43ab3f25-fe02-4cb8-ac67-0f06ccf1702b)

### NuGet package version

None

**Comment by 632575987** [comment]
> ### Describe the bug
> 
> Minimize the program first.
> 
> 
> 
> In "windows+tab" or "alt+tab" interface, the minimize button is "hover" style.
> 
> It should be the default style
> 
> ### Steps to reproduce the bug
> 
> 1.Minimize the program
> 
> 2."windows+tab" or "alt+tab"
> 
> ### Expected behavior
> 
> _No response_
> 
> ### Screenshots
> 
> ![Snipaste_2024-03-24_18-12-13](https://github.com/microsoft/microsoft-ui-xaml/assets/51285674/43ab3f25-fe02-4cb8-ac67-0f06ccf1702b)
> 
> 
> 
> ### NuGet package version
> 
> None
> 
> ### Windows version
> 
> _No response_
> 
> ### Additional context
> 
> _No response_

解决了吗？

**Comment by tingjiangcao** [comment]
> > ### Describe the bug
> > Minimize the program first.
> > In "windows+tab" or "alt+tab" interface, the minimize button is "hover" style.
> > It should be the default style
> > ### Steps to reproduce the bug
> > 1.Minimize the program
> > 2."windows+tab" or "alt+tab"
> > ### Expected behavior
> > _No response_
> > ### Screenshots
> > ![Snipaste_2024-03-24_18-12-13](https://private-user-images.githubusercontent.com/51285674/316300436-43ab3f25-fe02-4cb8-ac67-0f06ccf1702b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTAzNTYsIm5iZiI6MTcxMzUxMDA1NiwicGF0aCI6Ii81MTI4NTY3NC8zMTYzMDA0MzYtNDNhYjNmMjUtZmUwMi00Y2I4LWFjNjctMGYwNmNjZjE3MDJiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxODI0NGIyNTdjZDNjYTJmMDcxOGQzNmEyM2IyZTEzMzRjMTZmZGVmMmE5M2I1ZmMzMDQ5YzA0NzgwNTQyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vfKkYjx_MZ4nfUwZ8nI4426ZEKGBdGjiFGUeQHtPh0o)
> > ### NuGet package version
> > None
> > ### Windows version
> > _No response_
> > ### Additional context
> > _No response_
> 
> 解决了吗？

没呢，貌似是win11的问题
