### ISSUE TITLE
Undocumented behavior for `UpdateSourceTrigger`

### ISSUE THREAD

**Issue by ShortDevelopment** [microsoft/microsoft-ui-xaml#9497]
### Describe the bug

According to the [documentation](https://learn.microsoft.com/de-de/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.data.updatesourcetrigger?view=windows-app-sdk-1.4) the default behavior for `UpdateSourceTrigger` should be `PropertyChanged`.
But there is an undocumented special / unexpected behavior for `TextBox.Text` leading to errors (See #7188).
https://github.com/microsoft/microsoft-ui-xaml/blob/3d10001ba8e12336cad392846b1030ba691b784a/src/XamlCompiler/BuildTasks/Microsoft/Xaml/XamlCompiler/UpdateSourceTrigger.cs#L10

~This seems like a breaking change from UWP.~

### Steps to reproduce the bug

```xaml
<TextBox Text="{x:Bind MyProperty, Mode=TwoWay}" />
```

### Expected behavior

Update `MyProperty` on `PropertyChanged` not on `LostFocus`.
Or explicitly document this.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

https://github.com/microsoft/microsoft-ui-xaml/blob/3d10001ba8e12336cad392846b1030ba691b784a/src/XamlCompiler/BuildTasks/Microsoft/Xaml/XamlCompiler/BindAssignment.cs#L205-L222

**Comment by codendone** [comment]
You found that this is indeed intentional special behavior for the TextBox.Text property. The other code for doing this is here: https://github.com/microsoft/microsoft-ui-xaml/blob/3d10001ba8e12336cad392846b1030ba691b784a/dxaml/xcp/dxaml/lib/BindingExpression_Partial.cpp#L360-L361

UWP has the same behavior/code. I agree this should be documented.

**Comment by ShortDevelopment** [comment]
I'm sorry, I thought I was sure this behavior didn't exist in UWP, but there it is:
`Microsoft.Windows.UI.Xaml.Build.Tasks.Utilities.XamlTypeExtensions`
```cs
internal static bool NeedsLostFocusForTwoWay(this XamlMember member)
   => member.Name == "Text" && member.DeclaringType.UnderlyingType.FullName == "Windows.UI.Xaml.Controls.TextBox";
```

**Comment by codendone** [comment]
The [UpdateSourceTrigger documentation](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.data.binding.updatesourcetrigger) has been updated.
