### ISSUE TITLE
Call Frame.GetNavigationState will fire page OnNavigatedFrom

### ISSUE THREAD

**Issue by h82258652** [microsoft/microsoft-ui-xaml#950]
**Describe the bug**

If call ```Frame.GetNavigationState``` once, while navigated to a new page, the new page ```OnNavigatedFrom``` will be fired.

**Steps to reproduce the bug**

1. Register ```Frame.Navigated``` event and call ```GetNavigationState``` in the event handler.
2. override the second page ```OnNavigatedFrom``` method and do some logs here.
3. navigate to the second page.

**Expected behavior**

The second page ```OnNavigatedFrom``` should not be called.

**Version Info**

Windows 10 18362 SDK

**Additional context**

I create a demo repo here: https://github.com/h82258652/UwpFrameNavigationStateBugDemo
You can run the regular and bug project.

**Comment by jevansaks** [comment]
Thanks for the detailed bug report and repro! We won't be able to fix this until post-WinUI 3.0 so we'll take a look at this later.

**Comment by h82258652** [comment]
Hello @jevansaks, any progress on this?

**Comment by ranjeshj** [comment]
@h82258652 This does repro for me. Frame is in platform code so unfortunately we will need to be fixed post WinUI3. Are you blocked on this issue ? @chrisglein as FYI.

**Comment by lhak** [comment]
I think this behavior is intended and is also documented on the corresponding page for this method. However, I was also confused when I first encountered it. OnNavigatingFrom() might be the method you are looking for.

**Comment by h82258652** [comment]
@ranjeshj I was blocked on this one year ago, and I could not solve it. At final, I create my own ```Frame``` control instead of the framework control. But my ```Frame``` control is not universal. I hope it can be solved because I will create another project recently.
@lhak I think to add listeners to an event should not change the behavior.

**Comment by MikeHillberg** [comment]
@lhak is right, this is intentional behavior. The motivation is a scenario like this ... You've navigated from pages A to B to C. So the navigation state is A and B, and the current page is C. But GetNavigationState wants to get all of A/B/C. So as part of GetNavigationState it navigates the Frame to null, causing an OnNavigatingFrom(C), and getting C into the navigation state.
