### ISSUE TITLE
StackPanel applies Spacing to InfoBar when IsOpen is false

### ISSUE THREAD

**Issue by SnowyWreath** [microsoft/microsoft-ui-xaml#9507]
### Describe the bug

Similar to #916, StackPanel is still applying spacing between an InfoBar and its neighbors when the InfoBar is not open.

### Steps to reproduce the bug

```
<StackPanel Spacing="24">
   <InfoBar IsOpen="True" Title="This is a title" />
   <InfoBar IsOpen="False" Title="This is a title" />
   <InfoBar IsOpen="False" Title="This is a title" />
   <InfoBar IsOpen="False" Title="This is a title" />
   <InfoBar IsOpen="True" Title="This is a title" />
</StackPanel>
```

### Expected behavior

Spacing should only be applied between an InfoBar and a neighbor when the InfoBar is open. When an InfoBar is closed, it is collapsed for all intents and purposes, even though the control's Visibility is still equal to Visible.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmgallahan** [comment]
My reply to #9500 applies the same here:

> Would it be better to have a zero size when IsActive is False?

> No. `Visibility=Collapsed` means collapsed. If the control collapses as a side effect of `IsActive=false` then others will show up to complain that the ProgressRing should retain its size when `IsActive=false` for their scenarios.

Just substitute `IsOpen=false` for `IsActive=false`.

Introducing side effects that are only beneficial for some scenarios is a bad idea.

**Comment by ranjeshj** [comment]
@kmgallahan is correct. We only ignore spacing for Visibility=Collapsed items. You should be able to use that property to get the desired behavior.
