### ISSUE TITLE
Continuable System.IO.FileLoadException loading Microsoft.UI.Xaml.Controls.StylesVersion in Debug x64

### ISSUE THREAD

**Issue by nthorn** [microsoft/microsoft-ui-xaml#9510]
### Describe the bug

Adding the Microsoft.UI.Xaml NuGet package to a new C# UWP project causes it to hit a `System.IO.FileLoadException` on launch. Inspection of local variables a little way up in the call stack suggests it's trying to load `Microsoft.UI.Xaml.Controls.StylesVersion` even though this class isn't referenced directly anywhere in the project.

### Steps to reproduce the bug

1. In Visual Studio 2022, create a new C# UWP project
2. Right click the project file and select "Manage NuGet Packages"
3. Install the latest Microsoft.UI.Xaml NuGet package
4. Add this code to App.xaml (as recommended by the readme.txt file that pops up):
```
        <Application.Resources>
            <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
        </Application.Resources>
```
5. Change the configuration to x64 Debug and hit F5

Observe that it breaks on a `System.IO.FileLoadException`. You can hit F5 to continue past this exception and continue execution.

### Expected behavior

It should not throw an exception.

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

I believe this is the same as issue #6481, which was closed with no resolution.

**Comment by codendone** [comment]
Looks like a dup of #6481

**Comment by nthorn** [comment]
> Looks like a dup of #6481

Correct. That bug was closed with a request to file a new bug, hence my filing a new one.

**Comment by ranjeshj** [comment]
Sorry, we are taking only critical fixes for WinUI2. See https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2
