### ISSUE TITLE
Unable to Remove Focus Underline Color in Microsoft.UI.Xaml.Controls.TextBox

### ISSUE THREAD

**Issue by Phenek** [microsoft/microsoft-ui-xaml#9514]
### Describe the bug

The Microsoft.UI.Xaml.Controls.TextBox control does not allow for the removal of the underline focus color, even when setting the FocusVisualPrimaryThickness and FocusVisualSecondaryThickness properties to zero. This behavior is observed in .NET MAUI applications targeting WinUI.

### Steps to reproduce the bug

    1. Create a .NET MAUI application targeting WinUI.
    2. Add a TextBox control to the UI.
    3. create an appropriate handler to access the native TextBox
    4. Attempt to remove the underline focus color by setting the FocusVisualPrimaryThickness and FocusVisualSecondaryThickness properties to zero.
    
   ```csharp
    public partial class BlankEntryHandler : EntryHandler
    {
        protected override TextBox CreatePlatformView()
        {
            var platformView = base.CreatePlatformView();
            
            platformView.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Transparent);
            
            platformView.BorderBrush = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Transparent);
            platformView.BorderThickness = new Microsoft.UI.Xaml.Thickness(0);

            platformView.FocusVisualMargin = new Microsoft.UI.Xaml.Thickness(0);
            platformView.Margin = new Microsoft.UI.Xaml.Thickness(-2, -2, -2, 0);

            platformView.FocusVisualPrimaryBrush = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Transparent);
            platformView.FocusVisualPrimaryThickness = new Microsoft.UI.Xaml.Thickness(0);

            platformView.FocusVisualSecondaryBrush = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Transparent);
            platformView.FocusVisualSecondaryThickness = new Microsoft.UI.Xaml.Thickness(0);

            platformView.SelectionHighlightColor = new Microsoft.UI.Xaml.Media.SolidColorBrush(Microsoft.UI.Colors.Transparent);
           
            return platformView;
        }
    }
```

### Expected behavior

The underline focus color should be removed from the TextBox control when setting the FocusVisualPrimaryThickness and FocusVisualSecondaryThickness properties to zero.

### Screenshots

I need to make disappear this underline, because I am using another border implementation.
![Screenshot 2024-04-04 at 14 36 26](https://github.com/microsoft/microsoft-ui-xaml/assets/4518686/1d91bbec-0369-415d-90cf-c2085c69132c)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Additional context

I am trying to use TextBox with .Net MAUI

**Comment by baaaaif** [comment]
may this will help you https://learn.microsoft.com/en-us/answers/questions/893844/how-to-remove-underline-when-entry-receives-focus

**Comment by roxk** [comment]
The textbox control's look is controlled via [light-weight styling](https://learn.microsoft.com/en-us/windows/apps/design/style/xaml-styles#lightweight-styling), and textbox' styles are defined [here](https://github.com/microsoft/microsoft-ui-xaml/blob/winui3/release/1.5.1/controls/dev/CommonStyles/TextBox_themeresources.xaml). You'd want to disable these or as the above post indicated, set the thickness to 0 (but then you'd have to create an outer border).

**Comment by Phenek** [comment]
Hello Guys!

First thanks for your time.

I ended with your suggestions with first this solution:
@baaaaif
```
"TextControlBorderThemeThickness"
"TextControlBorderThemeThicknessFocused"
```
It works!

Then @roxk give me a information about backgrounds styles:
```
"TextControlBackgroundPointerOver"
"TextControlBackgroundFocused"
```

The complete solution in MAUI handler is:
```
    protected override TextBox CreatePlatformView()
    {
        var platformView = base.CreatePlatformView();
        platformView.Margin = new Thickness(-5);

        var rd = MauiWinUIApplication.Current.Resources;
        platformView.BorderBrush = new SolidColorBrush(Colors.Transparent);
        rd["TextControlBorderBrushPointerOver"] = new SolidColorBrush(Colors.Transparent);
        rd["TextControlBorderBrushFocused"] = new SolidColorBrush(Colors.Transparent);

        platformView.Background = new SolidColorBrush(Colors.Transparent);
        rd["TextControlBackgroundPointerOver"] = new SolidColorBrush(Colors.Transparent);
        rd["TextControlBackgroundFocused"] = new SolidColorBrush(Colors.Transparent);

        platformView.BorderThickness = new Thickness(0);
        rd["TextControlBorderThemeThickness"] = new Thickness(0);
        rd["TextControlBorderThemeThicknessFocused"] = new Thickness(0);

        return platformView;
    }
```

For me is kind of a workaround cause we are not able to manipulate BorderBrush alone, 
we need to fight with default style in resources...

Maybe default style should have their proper name "default", so we could at least remove them easly by doing
`platform.style = null`

**Comment by roxk** [comment]
> we need to fight with default style in resources and find hardcoded names
This is a feature and not "hard coded" name, just like you won't say css's :hover selector is a hard coded name.

> Maybe default style should have their proper name "default", so we could at least remove them
You can actually do that:

```
<Style x:Key="EmptyStyle" x:TargetType="TextBlock"></Style>
<TextBlock Style={StaticResource EmptyStyle}/>
```

**Comment by ranjeshj** [comment]
@Phenek The lightweight style is the way to go here. There are currently no plans to change the names of any resources in WinUI3 since that could break existing apps.
