### ISSUE TITLE
Can't deploy app: DEP1700: The recipe file "...\xxx.build.appxrecipe" does not exist.

### ISSUE THREAD

**Issue by ChiefInnovator** [microsoft/microsoft-ui-xaml#9517]
### Describe the bug

Visual Studio solution does not deploy MAUI application.  It says it needs to be deployed by checking the checkbox in the Configuration Manager for the solution.  That was checked, but the error continues.

This is the same bug that was closed at ...
https://github.com/microsoft/microsoft-ui-xaml/issues/7754

### Steps to reproduce the bug

1) Compile
2) Debug <- Cannot debug since application is not deployable.

### Expected behavior

The application should be deployed and able to run from Visual Studio.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/15870558/34aeed1a-dbaa-42a0-86f7-6dad86567ab7)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by JesseCol** [comment]
Thanks @ChiefInnovator , can you please provide a minimal repro app we can take a look at?  Thanks!
