### ISSUE TITLE
Bug: Second item in sub menu is selected first when using arrow key navigationBug title

### ISSUE THREAD

**Issue by andrew-james-heard** [microsoft/microsoft-ui-xaml#9519]
### Describe the bug

for Windows Explorer: file > context button or right-click > Open with (has focus) > right-cursor > submenu is displayed but nothing has focus...
but to give keyboard focus to the 1st item in the list I now have to press cursor-down (2nd item is selected), cursor-up (1st item is selected)
in other words it takes 1 less key to select the 2nd item than the 1st
I haven't discovered any other way from the keyboard to more efficiently select the 1st item in the sub-menu

### Steps to reproduce the bug

1. select file/ thumbnail
2. context button or right-click
3. Open with (has focus)
4. right-cursor
5. submenu is displayed but nothing has focus

### Expected behavior

maybe give 1st item in the sub-menu focus when right-cursor is pressed?

### NuGet package version

None

### Windows version

Windows 11 (21H2): Build 22000

**Comment by 0x5bfa** [comment]
Video recorded
https://github.com/files-community/Files/assets/62196528/f4ac0be4-f3fe-468f-b3c9-14e9ded5544f

**Comment by ranjeshj** [comment]
The item is focused but it does not seem to be drawing the focus rect.

**Comment by yaira2** [comment]
@ranjeshj I'm pretty sure it's not focused because in that case, pressing the `enter` key would trigger the item.
