### ISSUE TITLE
Ink on InkCanvas flashes when Ink Canvas (or parent control) is enabled or disabled

### ISSUE THREAD

**Issue by TheJoeFin** [microsoft/microsoft-ui-xaml#9525]
### Describe the bug

When there is ink on an InkCanvas and the parent control `IsEnabled` value is changed the ink flashes.

### Steps to reproduce the bug

Issue is visible in my app Ink Calendar and Journal.

1. Switch between views (which enables and disables the parent flipview)
2. Tap the lock symbol (also enables and disables the parent flipview)

Notice flashing ink.

### Expected behavior

Ink once loaded should flash when the parent control `IsEnabled` changes. 

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/7809853/b2f519ac-ef78-462a-ad9e-172ae797182c

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

I am actually using WinUI 2.8.6 and on Windows 11 23H2

**Comment by TheJoeFin** [comment]
I reviewed all of the possibly related issues and they are not duplicates of this issue. 😊

**Comment by ranjeshj** [comment]
@TheJoeFin sorry, we are only making business critical fixes in winui2 at this point - https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2
