### ISSUE TITLE
Proposal: Update hover visual

### ISSUE THREAD

**Issue by sravya03** [microsoft/microsoft-ui-xaml#953]
## Summary
Update the hover visual to align more with the depth model. When item is hovered over, the item is lifted. When you get closer to the item, the color becomes lighter.

## Rationale
* The button today indicates hover via grid border lines. Removed the border and using color is more coherent and consistent.
* Follows the other control updates being proposed.

## Important Notes
Here are the scoped changes proposed. Ones with asterisk are places where change is proposed.
![image](https://user-images.githubusercontent.com/22958680/62231877-bf18d080-b379-11e9-8e4c-a9d9c19aa409.png)

Controls impacted:

- Button
- ToggleButton
- Checkbox
- SplitButton
- ToggleButton
- ToggleSplitButton

![Buttons   Hyperlinks](https://user-images.githubusercontent.com/22958680/62232586-795d0780-b37b-11e9-922c-72441b60fddf.png)

![Buttons   Hyperlinks - Dark Theme](https://user-images.githubusercontent.com/22958680/62232594-7bbf6180-b37b-11e9-9dc5-d04a5aa3af1f.png)

**Comment by mdtauk** [comment]
Fluent Web, and Fabric Web use this elevate on hover design.  Take a look at the Microsoft Store app pages

**Comment by mdtauk** [comment]
![buttons](https://user-images.githubusercontent.com/7389110/60227000-7efb9500-9885-11e9-839a-bfdc2c8141f7.png)

Here is a look at 4 different Microsoft buttons using Fluent Design.

And on the right is an idea how you could blend those ideas into a new design

**Comment by chigy** [comment]
### Status update
This proposal is being closed in favor of the another proposal that was created that better defines the scope of the ask. 

BTW, I do believe the other proposal does cover the suggestion @mdtauk mentioned in one of the feedback.

@mdtauk , @sravya03 FYI

**Comment by chigy** [comment]
### Status update
Re-opening this because more systematic update to the button (#1054) was tabled but we still want to do the visual update to remove the border during hover state in WinUI2.2 to bring the design more in line to be more coherent and familiar.

**Comment by mdtauk** [comment]
Is there a rationale why the Slider hover is the Theme Base High colour, and not Accent Light 1/2 like with the hover on the Accent coloured Button/Checkbox/RadioButton/ToggleSwitch?

**Comment by chigy** [comment]
@mdtauk , you should open it as a proposal or idea. For this change, we are minimizing impact by not touching controls other than button related since we are trying to target WinUI2.2 release which is coming up shortly.

**Comment by mdtauk** [comment]
@chigy #1193  Done
