### ISSUE TITLE
Rider wpf desktop application cannot add windowsAppSDK

### ISSUE THREAD

**Issue by ZiercPro** [microsoft/microsoft-ui-xaml#9531]
### Describe the bug

I'm a newbie developer and want to try to develop a small app using winUI3, but it fails when I add windowsAppSDK to my project and i got following error：
[MSB4086] 尝试在条件“'$(TargetPlatformVersion)' '10.0.18362.0'”中对计算结果为“”而不是数字的“$(TargetPlatformVersion)”进行数值比较。 C:\Users\LJTX\.nuget\packages\microsoft.windowsappsdk\1.5.240311000\buildTransitive\Microsoft.InteractiveExperiences.Common.targets，(15:27)

### Steps to reproduce the bug

1. Create a project modeled after a WPF desktop application
2. Use NuGet to search for WindowsAppSDK and install it into the project you just created

### Expected behavior

I don't know whether this is a problem with windowsAppSDK or Rider. I searched online for a long time and couldn't find a solution. Hoping to get answers from you guys, I would be very grateful if you could clear up my confusion.

### Screenshots

![Snipaste_2024-03-29_15-03-08](https://github.com/microsoft/WindowsAppSDK/assets/118733490/6ea4ef62-c647-41b1-a8af-440d0b7103c6)

### NuGet package version

Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Insider Build (xxxxx)

### IDE

Other

### Additional context

please forgive my ignorance

**Comment by duncanmacmichael** [comment]
Fixed in 1.5.3, closing issue.
