### ISSUE TITLE
The error "Property Not Found" occurs when using x:DataType in a DataTemplate.

### ISSUE THREAD

**Issue by GochenRyan** [microsoft/microsoft-ui-xaml#9552]
### Source Code
```
<?xml version="1.0" encoding="utf-8"?>
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:DockToy" 
    xmlns:models="using:DockToy.models">

    <DataTemplate x:Key="RootDockTemplate" x:DataType="models:IRoot">
        <local:RootControl Content="{Binding Content}"/>
    </DataTemplate>

    <DataTemplate x:Key="DocumentDockTemplate" x:DataType="models:IDocument">
        <local:DocumentControl Content="{Binding Content}"/>
    </DataTemplate>

    <local:DockTemplateSelector 
            x:Key="DockControlSelector"
            RootDockTemplate="{StaticResource RootDockTemplate}"
            DocumnentDockTemplate="{StaticResource DocumentDockTemplate}"/>
</ResourceDictionary>
```
### Error
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	WMC0612	The XAML Binary Format (XBF) generator reported syntax error '0x09C4' : Property Not Found	DockToy	S:\Github\WinUISample\WinUISample\DockToy\DockTemplate.xaml	8			
```	

### Steps to reproduce the bug

1. Clone https://github.com/GochenRyan/WinUISample
2. Uncomment the commented-out code in DockTemplate.xaml and comment out lines 16-22
3. Build

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

### Additional context

After removing x:DataType="models:IRoot" and x:DataType="models:IDocument", the build succeeds.

**Comment by kmgallahan** [comment]
Your sample project has 2 problems.

1. You are using x:DataType in a ResourceDictionary that does not have a code-behind file
2. You have a self-referential infinite loop of ContentTemplateSelector, as RootControl uses a selector that can select it

Getting rid of the infinite loop and doing this works:

``` xaml
<?xml version="1.0" encoding="utf-8" ?>
<Window
  x:Class="DockToy.MainWindow"
  xmlns:controls="using:DockToy.controls"
  xmlns:local="using:DockToy"
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">

  <Page>
    <Page.Resources>
      <ResourceDictionary
        xmlns:local="using:DockToy"
        xmlns:models="using:DockToy.models"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation">

        <DataTemplate x:Key="RootDockTemplate" x:DataType="models:IRoot">
          <local:RootControl Content="{x:Bind Content}" />
        </DataTemplate>

        <DataTemplate x:Key="DocumentDockTemplate" x:DataType="models:IDocument">
          <local:DocumentControl Content="{x:Bind Content}" />
        </DataTemplate>

        <local:DockTemplateSelector
          x:Key="DockControlSelector"
          DocumnentDockTemplate="{StaticResource DocumentDockTemplate}"
          RootDockTemplate="{StaticResource RootDockTemplate}" />
      </ResourceDictionary>
    </Page.Resources>
    <local:DockControl ContentTemplateSelector="{StaticResource DockControlSelector}">
      <controls:RootDock>
        <controls:DocumentDock>
          <TextBlock Text="I am a TextBlock" />
        </controls:DocumentDock>
      </controls:RootDock>
    </local:DockControl>
  </Page>
</Window>
```

Also note that a ContentControl, like UserControl, has special requirements on resource lookup:

https://learn.microsoft.com/en-us/windows/apps/design/style/xaml-resource-dictionary#usercontrol-usage-scope

**Comment by bpulliam** [comment]
Let us know if the suggestions don't work for you.

**Comment by GochenRyan** [comment]
Thanks for the suggestion. While @kmgallahan recommendation is indeed effective, it doesn't align with the specific requirements I aim to address. In fact, I intend to create a WinUI Class Library, so ultimately, I won't have a `Window`.

Regarding the first problem, placing `DataTemplates` under `ResourceDictionary` is intended for inclusion in the `MergedDictionaries` section of app.xaml for sharing purposes. By setting `ContentTemplateSelector` on the subclass of `ContentControl`, for each Model object in the node tree Dock-RootDock-DocumentDock, `DockControlSelector` helps it find the corresponding control.

As for the second problem, to be honest, I haven't quite grasped it. Could you please provide further clarification on how I can replicate it? I've attempted to by placing breakpoints in SelectTemplateCore, but I haven't observed an infinite loop.

**Comment by GochenRyan** [comment]
```
<local:DockControl ContentTemplateSelector="{StaticResource DockControlSelector}">
    <controls:RootDock>
    <controls:DocumentDock>
        <TextBlock Text="I am a TextBlock" />
    </controls:DocumentDock>
    </controls:RootDock>
</local:DockControl>
```
If I write it this way, I can only set the control corresponding to `RootDock`, and subsequent child nodes cannot be processed.

**Comment by GochenRyan** [comment]
Maybe I should create a new control to apply the selector to all nodes in its content
