### ISSUE TITLE
InAppAcrylicBrush render issue

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#9559]
### Describe the bug

Sometimes AcrylicBrush from CommunityToolkit will not render correctly. Although I know this issue might belongs to CommunityToolkit but I create an issue here in case this issue caused by the Windows App Sdk itself.

### Steps to reproduce the bug

1. Switch on the LoadingControl
2. Move the slider to adjust the BlurAmount
3. See the render issue

### Screenshots

![GIF 4-12-2024 3-41-49 PM](https://github.com/microsoft/WindowsAppSDK/assets/42038175/7157f0af-c25c-4a0f-a827-02b26055591e)

### NuGet package version

Windows App SDK 1.5.2: 1.5.240404000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Demo: 
[LoadingControlTest.zip](https://github.com/microsoft/WindowsAppSDK/files/14957783/LoadingControlTest.zip)

**Comment by kmahone** [comment]
Since this is an issue with types from Windows Community Toolkit, please file the issue on the Community Toolkit github repo (https://github.com/CommunityToolkit/WindowsCommunityToolkit).
