### ISSUE TITLE
TypeDescriptor issue in .NET8

### ISSUE THREAD

**Issue by Fikus14** [microsoft/microsoft-ui-xaml#9564]
### Describe the bug

"FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified." is thrown when calling TypeDescriptor.GetProperties 

### Steps to reproduce the bug

1. Create new WinUI 3 app targeting .NET8
2. Call TypeDescriptor.GetProperties() passing in any control inherited from Microsoft.UI.Xaml.Controls.Control

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/24782272/f327ba6c-274b-4a5f-91a2-ad2fe6ee526c)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/24782272/5a6beb01-f708-4025-8ee3-ad961928e858)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by JesseCol** [comment]
Can you please share out a minimal repro app?  It's surprising to me that System.Windows.Forms.dll is required here.  Thanks!
