### ISSUE TITLE
HTML select popup not following webview2

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9569]
### Describe the bug

`select` popup in a web page is not following webview2 control itself.

### Steps to reproduce the bug

1. Open WinUI 3 Gallery, go to `WebView2` page.
3. Right click to open console, navigate with  `window.location.href = "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select"`
4. Click the `select`, scroll the winui3 content (not the web page).

### Expected behavior

`select` popup will dismiss when the web page scrolls. I guess it should also be dismissed when the WebView2 itself gets scrolled with native winui3 content.

### Screenshots

![WebView2Scroll](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/367dfa13-6dd7-4c14-83ff-bbc0bee3e839)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
@HO-COOH thanks for filing this issue. This turned out to be a core WebView issue that is tracked in a different internal repo. Closing this issue as external.

**Comment by HO-COOH** [comment]
@ranjeshj I think these kind of "tracked internally" issues should not be closed, otherwise we developers just lost tracking, and never get notified when it is fixed. So do we constantly trying for newer versions just to see if it's fixed and waste time???
For this particular issue, it's obviously not for the "WebView2 Feedback" repo, so where should we look for? 
This is just another reason why the number of issues in this winui repo get bloated.
