### ISSUE TITLE
NavigationView not resetting its SelectedItem if all items are unselected

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#957]
**Describe the bug**
Setting the `NavigationViewItem.IsSelected` property to `false` for all the items in `NavigationView.MenuItems` is not resetting `NavigationView.SelectedItem`

**Steps to reproduce the bug**
1. Create a new app with the following XAML code:
```xml
<mux:NavigationView
    x:Name="navView"
    IsBackEnabled="True"
    PaneDisplayMode="Top">
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem x:Name="navViewItemA" Content="Item A" />
        <mux:NavigationViewItem x:Name="navViewItemB" Content="Item B" />
    </mux:NavigationView.MenuItems>

    <StackPanel>
        <Button Click="SelectItemAClicked" Content="Select item A" />
        <Button Click="SelectItemBCliked" Content="Select item B" />
        <Button Click="SelectNoneBCliked" Content="Select None" />
    </StackPanel>
</mux:NavigationView>
```
2. Add the following code behind:
```csharp
private void SelectItemAClicked(object sender, RoutedEventArgs e)
{
    navViewItemB.IsSelected = false;
    navViewItemA.IsSelected = true;
}

private void SelectItemBCliked(object sender, RoutedEventArgs e)
{
    navViewItemA.IsSelected = false;
    navViewItemB.IsSelected = true;
}

private void SelectNoneBCliked(object sender, RoutedEventArgs e)
{
    navViewItemA.IsSelected = false;
    navViewItemB.IsSelected = false;
}
```
3. Run the application and click on the three buttons in the following order : *Select Item A*, *Select Item B*, *Select None*
3.1. Notice that *Item A* and *Item B* are properly selected when clicking on the first two buttons
3.2. Notice that *Item B* remains selected when clicking on *None*

**Expected behavior**
When setting all the items to `IsSelected = false`, the `SelectedItem` of `NavigationView` should revert to `null`

**Screenshots**

![image](https://user-images.githubusercontent.com/20152272/60257324-88135300-98d3-11e9-8c62-f335dbe94250.png)

**Version Info**
NuGet package version:
Microsoft.UI.Xaml 2.1.190606001
Microsoft.UI.Xaml 2.2.190611001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**
If we manually set the `SelectedItem` from the code behind, the `NavigationView` is properly deselecting all its items. I'm using this as a workaround for now but it would be great if toggling the `NavigationViewItem.IsSelected` works. It simplifies a lot the binding.

**Proposed fix**
[proposed by Yulikl]
NavigationViewItem has a boolean IsSelected property. When all of NavigationView's MenuItems set IsSelected to false, NavigationView should return null as its SelectedItem.

**Comment by jevansaks** [comment]
This is intentional per the original spec'd behavior -- NavigationView doesn't allow itself to get into the "no items are selected" state.

What is the scenario where you want this? Or is it simply that there's a scenario where these two get out of sync? (if it's just that SelectedItem and IsSelected get out of sync, that would be a bug)

**Comment by vgromfeld** [comment]
The scenario is to disable all the navigation items when the user is navigating to the settings page (using the nav view settings button). 
In this case, he is no longer on "Item A" or "Item B" page and I don't want to let him think that he is still on one "Item A/B" page whereas he is seeing the settings page.

I want to have something similar to the store application where the store section name (apps, games, movies...) remains selected for all the pages of this section (first page, product page...)

**Comment by licanhua** [comment]
@vgromfeld, I'm confused by this description: _I want to have something similar to the store application where the store section name (apps, games, movies...) remains selected for all the pages of this section (first page, product page...)_
What event trigged the 'navigating to the settings page', in my understanding, user clicked settings button, focus moved to the settings button, then navigating the pages.
But in your case, look like navigating happens first, then switch the selection.

It's possible to have a two way binding like selectedItem for navview.SelectedItem, then after x.IsSelected=false, also set selectedItem=null

**Comment by YuliKl** [comment]
To elaborate a little bit, the confusing part is that NavigationView's default behavior is to un-select all of its menu items when the Settings item is selected through user interaction. I know you're using NavigationView in a somewhat unique way. So is the default behavior not working or is your experience different from the default as @licanhua suggested?

**Comment by vgromfeld** [comment]
@licanhua, for now, the navigation to the settings page can be done only using the navigation view settings button. I'm actually using some binding to `SelectedItem` to workaround the `IsSelected` not working issue and it works.
If there is no binding to the `IsSelected` property, clicking on the settings item is properly unselecting all the navigation items.

But, let me go back on what we're trying to achieve and why I want to use binding with `IsSelected`:

I basically want two tabs in our application. The first "tab" will always display the same page (say *tab1-page*), the second tab will contain different pages (say *tab2-page1*, *tab2-page2*...).

The navigation to the tab pages can be performed by clicking on the navigation view items but also if the application is (re-)launched using file, deeplink... activation.

What I want is the following:
- **When the user clicks on one of the tab**, navigate to the page of this tab (*tab1-page* for *tab1* or the first page of *tab2*). The tab on which the user has clicked should be selected. This is the default behavior of the control.
- **App activation**: based on the activation kind (launch, resume, file, deeplink,...) I will request a navigation to either the unique page of *tab1* or one of the pages of *tab2*. The tab corresponding to the targeted page should be selected. If we have a deeplink to *tab2-page23* for example, we want *tab2* to be selected. This is where the `IsSelected`/`SelectedItem` is needed.
- **User clicks on the navigation view settings button**, we want all tabs to be disabled.

@YuliKl, I would say that my needs are the current behavior + some additional control to have more flexibility since the navigation view control is not the only actor *controlling* the app navigation.

**Comment by YuliKl** [comment]
NavigationViewItem has a boolean IsSelected property. When all of NavigationView's MenuItems set IsSelected to false, NavigationView should return null as its SelectedItem.

@vgromfeld, would the behavior above fix the issue you've encountered?

**Comment by YuliKl** [comment]
> NavigationViewItem has a boolean IsSelected property. When all of NavigationView's MenuItems set IsSelected to false, NavigationView should return null as its SelectedItem.
> 
> @vgromfeld, would the behavior above fix the issue you've encountered?

@vgromfeld, can you comment?

**Comment by vgromfeld** [comment]
Yes, setting `NavigationView.SelectedItem` to `null` when all `NavigationViewItem.IsSelected` properties are false will fix the issue.

Sorry for the delay 😓

**Comment by chingucoding** [comment]
What would be an acceptable fix for this issue now? Should we just set `SelectedItem` to `null` if every item was unselected?

**Comment by YuliKl** [comment]
> What would be an acceptable fix for this issue now? Should we just set `SelectedItem` to `null` if every item was unselected?

Yes 😎

![image](https://user-images.githubusercontent.com/13142665/65984711-30860580-e435-11e9-8a9a-18079aaa31ac.png)

**Comment by chingucoding** [comment]
> Yes 😎

Thank you for the clarification! If it is okay, I would like to fix this. 😄

**Comment by jevansaks** [comment]
I believe @teaP was already working on this as I saw she just sent out the fix for TabView and our plan is to implement the same fix for NavigationView. See my earlier comment: https://github.com/microsoft/microsoft-ui-xaml/issues/957#issuecomment-530919266

**Comment by chingucoding** [comment]
Okay, I will leave this to @teaP then.

**Comment by Felix-Dev** [comment]
@teaP Are you working on this right now or can I add a fix for this?

**Comment by ranjeshj** [comment]
@teaP is not working on this. You can pick it up if @chingucoding is ok with it. It looks like he called dibs earlier in the conversation thread :)

**Comment by chingucoding** [comment]
Thanks for ping @ranjeshj ! @Felix-Dev If you would like to fix this, sure go for it.

**Comment by rcohn** [comment]
Hello -

Is there another ticket for this problem, or can this problem be reopened? I'm not able to implement a solution that allows me to dynamically create a NavigationViewItem and then select it.  

This is in a WinUI3 app.  I can supply some demo code to show this if needed.

Thank you.

**Comment by ranjeshj** [comment]
> Hello -
> 
> Is there another ticket for this problem, or can this problem be reopened? I'm not able to implement a solution that allows me to dynamically create a NavigationViewItem and then select it.
> 
> This is in a WinUI3 app. I can supply some demo code to show this if needed.
> 
> Thank you.

@rcohn That sounds like a different issue. You can create a new issue with the repro details.
