### ISSUE TITLE
Package.appxmanifest file can't be opened with designer

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#9571]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Packageappxmanifest-file-cant-be-opene/10641967)._

---
winui3 project

1.Unpackaged direct start will report an error (new project): DllNotFoundException

2.The configuration is as follows:  
<WindowsPackageType>None</WindowsPackageType  
<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained  
will cause Package.appxmanifest can not be opened by designer, only xml code can be viewed. And it seems that all the visual assets of the icon set in it are invalidated.

---
#### Feedback Bot on 4/18/2024, 10:08 PM: 

(private comment, text removed)
#### Feedback Bot on 4/22/2024, 06:51 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by JesseCol** [comment]
Hi, can you please attach or link to a repro project so we could have a look?  Thanks!
