### ISSUE TITLE
GeometryGroup is leaking memory

### ISSUE THREAD

**Issue by hexawyz** [microsoft/microsoft-ui-xaml#9578]
### Describe the bug

GeometryGroup objects that stop being referenced from the application leak native memory. (AFAIK there is no leak in the managed heap)

### Steps to reproduce the bug

1. Clone the repo containing the repro app: https://github.com/hexawyz/LeakyUI
2. Build and run the app
3. Observe the memory grow indefinitely

### Expected behavior

The memory should not grow indefinitely and memory associated with the `GeometryGroup` objects should be freed. (See second screenshot for the behavior of the alternative solution without `GeometryGroup` in my case)

### Screenshots

1. Memory usage of the demo app rising when using `GeometryGroup`: ![image](https://github.com/microsoft/microsoft-ui-xaml/assets/8518235/1e5da1c6-b2ee-49da-a8ee-1e15e8ab111b)
2. Memory usage of the demo app **not** rising when **not** using `GeometryGroup`: ![image](https://github.com/microsoft/microsoft-ui-xaml/assets/8518235/6aa60985-91a5-47cc-8b48-dfcafe89a6ed)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

As I created a custom chart component using GeometryGroup to draw multiple grid lines, and when using a few of these components, I observed the memory of my process skyrocket very quickly.

Using diagnostics in Visual Studio it did not seem that the leak comes from the managed heap, which made the investigation a bit more tedious.

As my first tentative repro were too simple they did not show the bug, so I decided to go for a less simple repro and include the whole component in isolation from the main project. This more complete project, allowed me to pinpoint the source of the memory leak to the usage of `GeometryGroup`. I didn't observe anything as bad using regular `PathGeometry`.

The demo app also includes a "fixed" version of the code that uses `PathGeometry` object with multiple `PathFigure` instead. You can enable it by removing the `#define` on the first line here: https://github.com/hexawyz/LeakyUI/blob/master/LeakyUI/Controls/LineChart.cs#L1. (This fixed version of the code is what produced screenshot 2)

Also of importance, it seems that `GeometryGroup` objects leak memory even when they are never attached to any `Path`. (Just commenting the 3 lines here should be enough to verify this: https://github.com/hexawyz/LeakyUI/blob/master/LeakyUI/Controls/LineChart.cs#L217 )

**Comment by JJBrychell** [comment]
This leak is confirmed.  The WinUI CD2DFactory::CD2DGeometryGroup::Create function has the D2DFactory create a D2DGeometryGroup (which is created with a ref count of 1) and then initializes a WinUI CD2DGeometryGroup with it, adding a second reference when it is stored in a member variable.  However, the original reference that came out of construction is never released.  So we end up leaving this function with one reference but a ref count of 2.
