### ISSUE TITLE
Memory retention issue persists after setting DataGrid to "null"

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [microsoft/microsoft-ui-xaml#9579]
### Describe the bug

I'm currently using the CommunityToolKit DataGrid in my application. Upon adding the DataGrid through a button, I observed that the application's memory usage increased from 98MB to 108MB. However, even after setting the DataGrid reference to null upon button click, the memory usage remains at 108MB instead of reverting back to the initial 98MB.

**Additionally, I need confirmation on the proper method to dispose of the Community DataGrid. Is simply setting the DataGrid reference to null sufficient, or are there additional steps that need to be taken?**

### Steps to reproduce the bug

1.Run the sample
2.Watch the process memory in the Diagnostic Tools.
3.Click Add Datagrid button.
4.Repeat step 2.
5.Click Dispose button.
6.Wait for few seconds and repeat step 2.

### Expected behavior

My goal is to ensure that after setting the DataGrid reference to null, the application's memory usage returns to its original level of 98MB.

Demo Sample - [DataGrid_Demo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15108664/DataGrid_Demo.zip)

Video reference - [DataGrid_MemoryConsumption.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15108649/DataGrid_MemoryConsumption.zip)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

### Additional context

I am facing this issue in the older versions of the SDK too.

**Comment by kmahone** [comment]
Thanks. DataGrid is a component of the Community Toolkit.
Please file this issue in the Community Toolkit github repo.
