### ISSUE TITLE
About how to set the rotation direction of the camera preview control

### ISSUE THREAD

**Issue by GreenShadeZhang** [microsoft/microsoft-ui-xaml#9586]
### Describe the bug

Please tell me how to operate the MediaCapture class to rotate the video content of MediaFrameSource. When I use the uwp api to operate, I cannot effectively rotate the video.

### Steps to reproduce the bug

Use the following code to operate.
```
   var video = _mediaCapture.VideoDeviceController;
   var props = _mediaCapture.VideoDeviceController.GetMediaStreamProperties(MediaStreamType.VideoPreview);
   Guid RotationKey = new Guid("C380465D-2271-428C-9B83-ECEA3B4A85C1");
   props.Properties.Add(RotationKey, 90);
   try
   {
       await _mediaCapture.SetEncodingPropertiesAsync(MediaStreamType.VideoPreview, props, null);

   }
   catch (Exception ex)
   {

   }
```

This code does not work effectively. Is there a new API or is this feature simply unavailable?

### NuGet package version

Windows App SDK 1.5.1: 1.5.240311000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by codendone** [comment]
It looks like MediaStreamType.VideoPreview properties only apply to the way UWP XAML rendered the preview of a MediaCapture, which used private APIs. Investigation will be required to see if there is a way to apply it for WinAppSDK.

For preview, you may be able to apply a transform, similar to what the sample in WinUI 3 Gallery does for simple mirroring. But if you also need to apply a rotation to the recorded video, I think there will still be an issue.

**Comment by GreenShadeZhang** [comment]
> It looks like MediaStreamType.VideoPreview properties only apply to the way UWP XAML rendered the preview of a MediaCapture, which used private APIs. Investigation will be required to see if there is a way to apply it for WinAppSDK.
> 
> For preview, you may be able to apply a transform, similar to what the sample in WinUI 3 Gallery does for simple mirroring. But if you also need to apply a rotation to the recorded video, I think there will still be an issue.

I achieved this by setting the PlaybackSession.PlaybackRotation of the MediaPlayerElement's MediaPlayer object
```csharp
 private void CameraPreviewControl_PreviewCameraChanged(object? sender, CommunityToolkit.WinUI.Controls.PreviewCameraChangedEventArgs e)
    {
        if (e.CameraName != null && e.CameraName.EndsWith("Cam"))
        {
            CameraPreviewControl.MediaPlayer.PlaybackSession.PlaybackRotation = Windows.Media.MediaProperties.MediaRotation.Clockwise270Degrees;
        }
        else
        {
            CameraPreviewControl.MediaPlayer.PlaybackSession.PlaybackRotation = Windows.Media.MediaProperties.MediaRotation.None;
        }
    }
```
