### ISSUE TITLE
AutoSuggestBox suggest list broken by microsoft.ui.xaml

### ISSUE THREAD

**Issue by tedrog36** [microsoft/microsoft-ui-xaml#959]
**Describe the bug**
The suggestions list does not show when using Microsoft.UI.Xaml version 2.1.190606001.

Additional info:  the suggestion list displays properly in Microsoft.UI.Xaml 2.0.181018004.  First broken in Microsoft.UI.Xaml 2.1.190319001-prerelease.  Still broken in latest nuget Microsoft.UI.Xaml 2.2.190611001-prerelease.

**Steps to reproduce the bug**
1. Run the provided project
2. Start typing in the auto suggest box.

**Expected behavior**
The suggestions list should show.  The list shows fine if Microsoft.UI.Xaml is not included as part  of the project.  If you comment out the "XamlControlsResources" line in App.xaml it will work properly.
**Screenshots**

This screenshot shows sliver of suggestion list that shows.
![bad-suggestion-list](https://user-images.githubusercontent.com/3768598/60278133-d2dd9c80-98cc-11e9-9f96-e36806ff79ef.JPG)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.1.190606001.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| April 2018 Update (17134)          | Yes  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**
Project to reproduce problem.
[App-UWP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3335423/App-UWP.zip)

**Comment by jevansaks** [comment]
Thanks for reporting, this seems like a bad regression. We'll take a look.

**Comment by mrjfalk** [comment]
Can confirm this as well, I just spent a long time trying to figure out why my autosuggestbox didn't work, as mentioned rolling back to 2.1.18... fixes it.

**Comment by llongley** [comment]
Should be fixed by https://github.com/microsoft/microsoft-ui-xaml/pull/1116 - thanks!
