### ISSUE TITLE
Unhandled exception when using an icon as a resource

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#9590]
### Describe the bug

When setting an FontIcon or SymbolIcon as resource in App.xaml and using it, on an AppBarButton for example, I get an unhandled exception

### Steps to reproduce the bug

````
<FontIcon x:Key="MyIcon"
          Glyph="&#xE700;"/>
````

````
<AppBarButton Height="50" 
              Width="50"
              Icon="{StaticResource MyIcon}"/>
````

### Expected behavior

I'm not sure if this is intended or a bug. It does feel like we should be able to do this.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmgallahan** [comment]
Documented as not supported:

https://learn.microsoft.com/en-us/windows/apps/design/style/xaml-resource-dictionary#xaml-resources-must-be-shareable

> XAML resources must be shareable
For an object to exist in a [ResourceDictionary](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.ResourceDictionary), that object must be shareable.

> Being shareable is required because, when the object tree of an app is constructed and used at run time, objects cannot exist at multiple locations in the tree. Internally, the resource system creates copies of resource values to use in the object graph of your app when each XAML resource is requested.

> A [ResourceDictionary](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.ResourceDictionary) and Windows Runtime XAML in general supports these objects for shareable usage:


- Styles and templates ([Style](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Style) and classes derived from [FrameworkTemplate](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.FrameworkTemplate))
- Brushes and colors (classes derived from [Brush](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Brush), and [Color](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Color) values)
- Animation types including [Storyboard](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Animation.Storyboard)
- Transforms (classes derived from [GeneralTransform](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.GeneralTransform))
- [Matrix](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Matrix) and [Matrix3D](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Media3D.Matrix3D)
- [Point](https://learn.microsoft.com/en-us/uwp/api/Windows.Foundation.Point) values
- Certain other UI-related structures such as [Thickness](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Thickness) and [CornerRadius](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.CornerRadius)
- [XAML intrinsic data types](https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-intrinsic-data-types)

**Comment by eduardobragaxz** [comment]
That's unfortunate. Thanks for the link!
