### ISSUE TITLE
How to generate the smallest possible publishing file for unpackaged Winui3 app?

### ISSUE THREAD

**Issue by Shiiho11** [microsoft/microsoft-ui-xaml#9591]
**Question Overview**
I want to try publishing an mini unpackaged Winui3 app. 
The published file contains many window sdk DLL files, resulting in the large application files (approximately 30MB).
This is too big for a mini app.
Is there any way to remove these files while ensuring the normal operation of the program?

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/51045202/1173082a-a19a-4d54-b49d-1debe06e54a0)

**Detail**
1. I followed the [Winui3 guidelines](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app#unpackaged-create-a-new-project-for-an-unpackaged-c-or-c-winui-3-desktop-app) to create an unpackaged Winui3 app
2. I used Markup`<Windows PackageType>None</Windows PackageType>`. I didn't use Markup`<WindowsAppSDKSelfContained>`(To minimize the size of published files as much as possible).
3. PublishProfiles: deployment framework-dependent(To minimize the size of published files as much as possible).
4. The published file contains many window sdk DLL files, resulting in the large application files.

**Question**
1. These DLL files appear to be Windows SDK DLLs. Can't call the SDK that has been installed in some way?(I am a beginner, not sure if this is feasible)
2. I just want to develop a small tool and distribute small executable files(unpackaged).
3. Is there any way to remove these files while ensuring the normal operation of the program?
4. Should I switch to Winui2 or UWP or Other UI frameworks?

**Comment by ghost1372** [comment]
turn off SelfContained

`<SelfContained>false</SelfContained>
`
also you can use Trim

`<PublishTrimmed>true</PublishTrimmed>
`
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0

**Comment by DarranRowe** [comment]
> turn off SelfContained
> 
> `<SelfContained>false</SelfContained> ` also you can use Trim
> 
> `<PublishTrimmed>true</PublishTrimmed> ` https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0

Out of curiosity, how small does this get for you? I am just wondering because a Hybrid CRT build of a C++ application is around 600KiB for the default template. It is closer to 515KiB if you don't mind having the dependency on the Visual C++ Redist.
