### ISSUE TITLE
AppBarButton MenuFlyout is not dismissed

### ISSUE THREAD

**Issue by asierpn** [microsoft/microsoft-ui-xaml#960]
**Describe the bug**

An AppBarButton's MenuFlyout is not dismissed when you click outside the flyout.

**Steps to reproduce the bug**

1. Execute the sample project.
2. Click on the download button in the bottom app bar.
3. Click outside the flyout.

**Expected behavior**
The flyout should be dismissed.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)        | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**

[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3335705/App1.zip)

**Comment by jevansaks** [comment]
Thanks, @asierpn! This sounds familiar and might require a fix to the XAML framework to address (in which case it would be post WinUI 3.0) but we'll investigate.

**Comment by chingucoding** [comment]
I think this was fixed at some point. When using the following code snippet:
```xaml
  <Page.BottomAppBar>
    <CommandBar>
      <CommandBar.PrimaryCommands>
        <AppBarButton Content="Download"
                      Icon="Download">
          <AppBarButton.Flyout>
            <MenuFlyout>
              <MenuFlyoutItem Text="PDF" />
              <MenuFlyoutItem Text="Excel" />
            </MenuFlyout>
          </AppBarButton.Flyout>
        </AppBarButton>
      </CommandBar.PrimaryCommands>
    </CommandBar>
  </Page.BottomAppBar>
```
the flyout closes when one clicks outside of it.

**Comment by asierpn** [comment]
On my side it works fine now too.
