### ISSUE TITLE
Possible leak in RefreshContainer where it doesn't stop a "Forever" composition animation

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/microsoft-ui-xaml#9604]
### Describe the bug

https://github.com/microsoft/microsoft-ui-xaml/blob/2a60e27c591846556fa9ec4d8f305afdf0f96dc1/controls/dev/PullToRefresh/RefreshVisualizer/RefreshVisualizer.cpp#L422-L444

This animation apparently never stops?

So, if many `RefreshContainer`s are repeatedly added to visual tree, goes into interacting state, then removed from visual tree, those animations are likely to get stuck?

This shouldn't be a problem for a single `RefreshContainer` as the next interaction will cause another `StartAnimation("RotationAngle", ..)` which should stop the previous one.

### Steps to reproduce the bug

-

### NuGet package version

None

**Comment by codendone** [comment]
Do you see an issue in the running app, or are you just noticing some suspect code?

**Comment by Youssef1313** [comment]
Just noticed suspicious code. The only way this can start causing issues is repeated interaction with **different** RefreshContainers. Each container will keep one animation running unnecessarily, if I understand correctly.

**Comment by kmahone** [comment]
Once the RefreshContainer is removed from the tree and all references to it go away to RefreshContainer should get destroyed and so should the animation. So there should be no leak.

Are you seeing a leak of the RefreshContainer in this scenario?
