### ISSUE TITLE
ScrollViewer sometimes does not render content on wheel scrolling

### ISSUE THREAD

**Issue by asierpn** [microsoft/microsoft-ui-xaml#961]
**Describe the bug**

The content of the ScrollViewer is not rendered sometimes when scrolling using the mouse wheel, using the scrollbar it works fine.

**Steps to reproduce the bug**

1. Execute the sample project.
2. Scroll the DataGrid in each tab: Page 1, Page 2 Page 3 using the mouse wheel repeatedly.
3. In some moment the content is not rendered.

**Expected behavior**

The content is rendered always.

**Screenshots**

[screencast.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3335907/screencast.zip)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | No   |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**

[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3335919/App1.zip)

The sample project uses the GridControl from DevExpress, I have been working [with them](https://www.devexpress.com/Support/Center/Question/Details/T693162/data-rows-are-not-rendered-on-wheel-scrolling-if-gridcontrol-s-parent-container-is-a) on this issue, but seems that the issue is related with ScrollViewer. It is reported [here](https://stackoverflow.com/questions/51669463/scrolling-with-scroll-wheel-doesnt-render-scrolling-by-clicking-dragging-scrol) using other 1st and 3rd party controls. In some computers like mine it happens very often under certain conditions as in the sample Project. My boss uses a Surface Pro 4 and he gets the issue very often when projecting to a secondary monitor.

**Comment by jevansaks** [comment]
Thanks, this seems like it could be a problem with the control inside the ScrollViewer. You say it's a GridControl? Could you provide more information about this control and how it works? 

Also the detail that it is hardware or monitor/projection-related makes me think that it has to do with a graphics layer problem of some kind. Does this control perhaps use Win2D under the covers?

**Comment by asierpn** [comment]
@jevansaks The GridControl is a data grid control developed by DevExpress. You can[ download a trial](https://go.devexpress.com/DevExpressDownload_UWPTrial.aspx) to inspect it, but I think that the issue happens with other controls that use the ScrollViewer as it is reported in the [second link](https://stackoverflow.com/questions/51669463/scrolling-with-scroll-wheel-doesnt-render-scrolling-by-clicking-dragging-scrol) which I've provided.

**Comment by jevansaks** [comment]
> issue happens with other controls that use the ScrollViewer as it is reported in the [second link](https://stackoverflow.com/questions/51669463/scrolling-with-scroll-wheel-doesnt-render-scrolling-by-clicking-dragging-scrol) which I've provided.

I think that issue is #666 . Do you think that's the same thing happening here? Do you still see the issue on Windows 1903?

**Comment by huoyaoyuan** [comment]
If dragging to resize the window to resize the ScrollViewier, then it sometimes doesn't render too.
Still see on 1903.

**Comment by asierpn** [comment]
Yes, I think that is exactly the same issue than #666

**Comment by asierpn** [comment]
I've updated to 1903 now and I'm not being able to reproduce the issue. I need to do more tests in other machines, but in my development machine now it works better, where I was able to reproduce the issue with a few attempts.

**Comment by jevansaks** [comment]
> but in my development machine now it works better, where I was able to reproduce the issue with a few attempts.

Thank you, that sounds promising!
