### ISSUE TITLE
PublishSingleFile fail to work when you have a WinUI3 Class Lib

### ISSUE THREAD

**Issue by ReneeGA2020** [microsoft/microsoft-ui-xaml#9611]
### Describe the bug

When PublishSingleFile is on, the build process will try to find the lib dll in the wrong location

### Steps to reproduce the bug

1. Create a new winUI3 app
2. Add a c# winUI3 Class Lib
3. Add dependency
4. Build with win-x64 + PublishSingleFile + WindowsAppSDKSelfContained + WindowsPackageType = None + SelfContained
->
Error CS0006: Metadata file 'C:\Users\xxxxx\source\repos\App8\ClassLibrary1\bin\Release\net8.0-windows10.0.19041.0\win-x64\ClassLibrary1.dll' could not be found

Test project:
[App8.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15205054/App8.zip)

### Expected behavior

Build successfully

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Additional context

ClassLibrary1.dll can actually be found in ClassLibrary1\bin\Release\net8.0-windows10.0.19041.0\ClassLibrary1.dll instead of 'ClassLibrary1\bin\Release\net8.0-windows10.0.19041.0\ **win-x64**\ClassLibrary1.dll'

**Comment by ghost1372** [comment]
i think you should report it in WASDK repo
https://github.com/microsoft/windowsappsdk

**Comment by ReneeGA2020** [comment]
ok
