### ISSUE TITLE
Voice Access commang like "Delete that" is not working wit PasswordBox

### ISSUE THREAD

**Issue by samdsmx** [microsoft/microsoft-ui-xaml#9615]
### Describe the bug

I test the voice command with TextBox control and works as expected. But not for PasswordBox when the password is not reveal. If
PasswordRevealMode is true the "delete that" command works.

### Steps to reproduce the bug

Using a PasswordBox control, try to delete the content using voice access command "Delete that"

### Screenshots

[delete that.webm](https://github.com/microsoft/microsoft-ui-xaml/assets/5838427/ac310233-d7cd-42c3-ac90-c37c641405bb)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/5838427/a8909660-a222-4dfb-bcbb-cc36a43b3ba6)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmahone** [comment]
Thanks for reporting this issue. I've moved the internal version of this bug to the Voice Access team.
