### ISSUE TITLE
Button does not spread in RelativePanel

### ISSUE THREAD

**Issue by shinta0806** [microsoft/microsoft-ui-xaml#9617]
### Describe the bug

Place the Button in the RelativePanel,

- RelativePanel.AlignLeftWithPanel="True" 
- RelativePanel.AlignRightWithPanel="True"

does not cause the Button to extend to the left or right.

The same problem exists in the vertical direction.

- RelativePanel.AlignTopWithPanel="True" 
- RelativePanel.AlignBottomWithPanel="True"

### Steps to reproduce the bug

1. Place the RelativePanel.
2. Place the Button inside the RelativePanel.
3. Set AlignLeftWithPanel / AlignRightWithPanel property.

Sample program in GitHub:
https://github.com/shinta0806/TestRelativePanel

### Expected behavior

TextBox spreads in RelativePanel.
I would like the Button to behave the same as the TextBox.

### Screenshots

![2](https://github.com/microsoft/microsoft-ui-xaml/assets/7196473/d4de5cdb-38f9-479c-8349-6de8b83f5875)

![1](https://github.com/microsoft/microsoft-ui-xaml/assets/7196473/6ee28b1f-9d78-4840-8f5d-69b750ff62b7)

[NG] Button
[NG] ComboBox

[OK] TextBox

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
I suspect this is due to the behavior certain controls choose. Button will stretch if `HorizontalAlignment` and `VerticalAlignment` are set, like this:
```xml
<RelativePanel Background="Aquamarine">
    <Button Content="Button" RelativePanel.AlignLeftWithPanel="True" RelativePanel.AlignRightWithPanel="True"
        RelativePanel.AlignTopWithPanel="True" RelativePanel.AlignBottomWithPanel="True" HorizontalAlignment="Stretch" VerticalAlignment="Stretch"/>
</RelativePanel>
```

But RelativeLayout owners will need to confirm if that is required or if there is a bug here.

**Comment by MikeHillberg** [comment]
Button's default style [sets the HorizontalAlignment to left](https://github.com/microsoft/microsoft-ui-xaml/blob/d4c4e539c55b562e78e7f026195d5b6c8af234ea/controls/dev/CommonStyles/Button_themeresources.xaml#L125). So it's the same in a `StackPanel` or `Grid` that it won't fill all available space unless you explicitly set it to `Stretch`.

**Comment by shinta0806** [comment]
Thank you very much!
I close this ticket.
