### ISSUE TITLE
Native debugging for WinUI apps stopped working

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/microsoft-ui-xaml#9619]
### Describe the bug

The steps outlined here used to work: https://github.com/microsoft/microsoft-ui-xaml/tree/winui3/release/1.5-stable?tab=readme-ov-file#debugging-winui-3

But they stopped working.

The PDBs are loaded, but it says no source information available.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/31348972/082d17fd-2943-4b95-b045-d98cab8c9989)

### Steps to reproduce the bug

Follow the steps using:

1. VS 17.10 Preview 5
2. Microsoft.WindowsAppSDK 1.5.240428000
3. Microsoft.Windows.SDK.BuildTools 10.0.22621.756
4. Source code from https://github.com/microsoft/microsoft-ui-xaml/commit/2a60e27c591846556fa9ec4d8f305afdf0f96dc1
5. I have "Just my code" **disabled**
6. I added the repo root to solution's "Debug Source Files"

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/31348972/b5b6528b-9709-4141-b9cd-cf7f9e5dd204)

Not sure if it's a VS regression, or PDBs from https://msdl.microsoft.com/download/symbols became corrupted/wrong somehow.

### Expected behavior

Debugging should work

### NuGet package version

None

**Comment by evelynwu-msft** [comment]
Can you verify that your Visual Studio installation is configured for Source Server support like in the screenshot below?
<img width="538" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/50890554/c6ac79f6-fc07-4539-b442-0a4adb8ffacc">

If that is configured correctly and the source files are still not being resolved (whether via the command stamped into the PDBs or your local clone) then I recommend [reporting an issue through Visual Studio](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) so that the appropriate team can investigate further.

**Comment by Youssef1313** [comment]
@evelynwu-msft Sorry for the late reply. I have "Enable source server support" checked.

**Comment by evelynwu-msft** [comment]
@Youssef1313 Unfortunately, it appears that the backend is removing private information, which includes source information, from the symbols we publish. It may not be possible to rectify this for symbols that have already been published but we'll do our best to resolve this quickly to minimize the number of future releases that are similarly affected.

**Comment by Youssef1313** [comment]
Thank you @evelynwu-msft for looking into this.

Is there any workaround available? Or any specific version that can work?

**Comment by Youssef1313** [comment]
Hi @evelynwu-msft

I think this was supposed to be fixed in [1.4.240512000](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.4.240512000), but I'm still seeing the same issue with 1.4.240512000 and commit 326f5a684bd765db6d7c939e971486810381688d

**Comment by Youssef1313** [comment]
My bad, it's working fine with that version. I assume next 1.5.x versions will work as well?

**Comment by evelynwu-msft** [comment]
@Youssef1313 The backend has been updated and we've republished the symbols for 1.4.6 and 1.5.3 so you should once again be able to do source debugging. Thanks for bringing this to our attention!

**Comment by Youssef1313** [comment]
Thank you @evelynwu-msft
