### ISSUE TITLE
Issue occurs for custom control that was inherited from ComboBoxItem 

### ISSUE THREAD

**Issue by Jothika4341** [microsoft/microsoft-ui-xaml#9620]
### Describe the bug

When creating a custom control that was inherited from ComboBoxItem , Facing issue in selecting the item in which the selected item is not properly binded in the custom control when the isEditable Property is True 

### Steps to reproduce the bug
Sample: [SampleCustomControlWinUI.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15260306/SampleCustomControlWinUI.zip)

1.Run the sample that has been attached 
2.Click the Custom control which is a Combo Box.

**Note: Selected item not properly binded.** 

### Expected behavior

Selected Item should be properly binded when the isEditable property sets to true 

### Screenshots

![Image](https://github.com/microsoft/microsoft-ui-xaml/assets/161836322/5c2937f8-7121-45d5-b2ea-7c19d732e484)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by ranjeshj** [comment]
@Jothika4341 you can try overriding ToString on your custom control.

**Comment by Jothika4341** [comment]
@ranjeshj, Tried by overriding ToString , it works. Thank you.
