### ISSUE TITLE
Memory Increases When Retrieving BindingPath.Path

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [microsoft/microsoft-ui-xaml#9625]
### Describe the bug

I have a scenario where I need to retrieve the BindingPath.Path in various parts of my application multiple times. However, when I attempt to retrieve it, the memory usage spikes significantly, from 99mb to 710mb. Once the process is completed, it decreases back to 187mb. I have attached a video demonstration showcasing the memory consumption and provided a sample for your reference.

[MemoryConsumption.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15278683/MemoryConsumption.zip)

### Steps to reproduce the bug

1.Run the sample.
2.Watch the process memory in the Diagnostic Tools or Task Manager.
3.Click Check button.

### Expected behavior

 Memory do not want to increase that much while retrieving the path.

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/124787498/be876ceb-0fd7-427f-a374-ac88ad791723

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

**Comment by ChidanandMurugaiah** [comment]
The mentioned concerns do not pertain to the problem I've reported here.

**Comment by JesseCol** [comment]
Hi, thanks for posting.  If you call GC.Collect() in this loop, do you still see this leak?  Thanks!

**Comment by ChidanandMurugaiah** [comment]
@JesseCol, Thank you for the update. We attempted your suggestion, and it did indeed resolve the memory leak. However, it introduced a performance issue. Without invoking GC.Collect(), the loop took 10 seconds to complete. Upon calling GC.Collect(), it took over 2 minutes to finish the loop. For your reference I attached the video demonstration with this update.

[DataGrid_PerformanceIssue_with_GC.Collect().zip](https://github.com/microsoft/microsoft-ui-xaml/files/15330248/DataGrid_PerformanceIssue_with_GC.Collect.zip)

**Comment by JesseCol** [comment]
Thanks!  My suggestion of running GC.Collect() isn't that this would be a good way to fix the problem, it was just to see if there's a true memory leak here or if it's just that not all of the managed objects have been collected yet.  

It sounds like what you're seeing here is normal CLR behavior.  Your loop is allocating a lot of new objects, and they won't get cleaned up until the garbage collector runs.  In a real-world app, you usually wouldn't call GC.Collect() yourself, you'd just let the CLR manage the memory itself.
