### ISSUE TITLE
Focus does not move into the frame after navigating to one from a navigation view.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/microsoft-ui-xaml#9631]
### Describe the bug

After selecting an item in a navigation view, focus should move to the first focusable element inside the frame.  Instead focus stays in the navigation view.

### Steps to reproduce the bug

1. Make a simple app with a navigation view and a frame.
2. Add a new page with a button.
3. Make a SelectionChanged event.
4. In the event, navigate to the page made earlier.

### Expected behavior

Focus moves to the button inside the frame.

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/2517139/c8a2d75d-7bd8-4749-b4d5-68a847926808

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Windows version

Windows Insider Build (xxxxx)

**Comment by kmgallahan** [comment]
NavigationView has no knowledge of the Frame you are using, or if it is being used with a Frame at all. It merely reports user interactions and you are responsible for determining what to do with them. 

If that means you call a method on Frame to display some content, then you need to decide what to do after that content loads. That might mean focusing on something in the Frame, but that is up to the developer and is not something NavigationView should try to figure out by making assumptions.
