### ISSUE TITLE
The Print UI dialogue is not shown on the Windows platform when the "EntryPoint" is set as "Windows.PartialTrustApplication" in Package.appxmanifest.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#9635]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-Print-UI-dialogue-is-not-shown-on-th/10658279)._

---
**Describe the bug**

The default Print UI dialogue is not shown on the Windows platform when the **EntryPoint** is set as **“Windows.PartialTrustApplication”** in **Package.appxmanifest**.

**Steps to reproduce the bug**

*   Run the attached sample on a machine with a Windows platform.
*   Click the button to execute the associated functionality to open the default print dialogue of the Windows platform.
*   Observe that the application does not show the Print preview dialogue.

[App1 (2).zip](https://aka.ms/dc/file?name=Bacaf304082c740cdb61f6036dc0f91a4638512568921839790_App1_(2).zip&tid=acaf304082c740cdb61f6036dc0f91a4638512568921839790)

**Expected behavior**

When the **EntryPoint** is set as **“$targetentrypoint$”** in **Package.appxmanifest**, it displays the default Print UI dialogue correctly in the Windows platform. However, when the **EntryPoint** is changed to **“Windows.PartialTrustApplication”** in **Package.appxmanifest**, the print dialogue is not shown. The print dialogue should be displayed properly.

---
#### Feedback Bot on 5/14/2024, 07:06 PM: 

(private comment, text removed)
#### Feedback Bot on 5/15/2024, 08:32 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by codendone** [comment]
Dup of #9616.
