### ISSUE TITLE
The first time "microsoft." is typed into a TextBox control, it will be capitalized for no reason

### ISSUE THREAD

**Issue by shufan** [microsoft/microsoft-ui-xaml#9637]
### Describe the bug

The first time "microsoft." is typed into a TextBox control, it will be capitalized for no reason.

This only occurs the first time ever "microsoft." is typed into a particular TextBox control. If you clear the text in the TextBox and type "microsoft." again it will properly remain uncapitalized. On the first time ever "microsoft." is typed into a particular TextBox control the issue repros with 100% reliability.

I have not seen this repro with any other words, and in fact neither "microsofts.", "microsof.", or "microsoft"  repro this issue.

### Steps to reproduce the bug

1. Download and open the WinUI 3 Gallery app and navigate to the TextBox control page or find any other WinUI 3 TextBox control
2. In a WinUI 3 TextBox control, type "microsoft." notice that it gets capitalized after typing the period. This is unexpected/undesired behavior.

### Expected behavior

The expectation is that "microsoft." should not be capitalized for no reason.

### Screenshots

After typing "microsoft." this is what my TextBox looked like... ![image](https://github.com/microsoft/microsoft-ui-xaml/assets/1192397/544aa98d-e5b2-4ac4-8803-b2e9ee6db0f8)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by shufan** [comment]
This also reproes for AutoSuggestBox and NumberBox.

**Comment by BreeceW** [comment]
This sounds like intentional auto correct. If you set the `InputScope` of the TextBox to match the kind of input requested, it could turn off auto correct, and you could still override it with `IsSpellCheckEnabled="False"`.

**Comment by JohnnyWestlake** [comment]
This is default autocorrect behaviour (it detects Microsoft as a proper noun and capitalises it). You can disable this by setting `IsSpellCheckEnabled="False"`

**Comment by shufan** [comment]
Aha, thanks! I should have tried more proper nouns. I tried "tony" and just assumed that wasn't a behavior. Will close, seems fine as long as it can be disabled as you mention.
