### ISSUE TITLE
Multiple x:Bind to Name fails to build

### ISSUE THREAD

**Issue by shinta0806** [microsoft/microsoft-ui-xaml#9638]
### Describe the bug

If a constant is specified for Name in x:Bind, it will build once, but not more than once.

XAML:
```XAML
<StackPanel >
	<TextBlock Name="{x:Bind v:MainPage.CONST_NAME_A}" Text="A" />
	<TextBlock Name="{x:Bind v:MainPage.CONST_NAME_B}" Text="B" />
</StackPanel>
```

C#:
```C#
public const String CONST_NAME_A = "NameA";
public const String CONST_NAME_B = "NameB";
```

Error messages during build:
`WMC0047	Element name '' is already used in this scope.`

### Steps to reproduce the bug

1. [OK] Specify the Name of some UIElement by x:Bind.
2. [NG] Specify the Name of another UIElement by x:Bind.

Sample program in GitHub:
https://github.com/shinta0806/TestNameBind

### Expected behavior

Can x:Bind to Name multiple times

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by shinta0806** [comment]
Hi, AI,
This case occurs even without DataTemplate.

**Comment by JohnnyWestlake** [comment]
Fwiw, this isn't a scenario that's advised (binding or manually setting Name)
https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.name?view=winrt-22621#name-and-data-binding
https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.name?view=winrt-22621#setting-name-in-code

(Complicated by the fact that x:Bind runs *after* InitializeComponent)

**Comment by shinta0806** [comment]
Thank you for the information.

I wanted to unify constants in XAML and C#.
I wanted to specify Name in XAML and FrameworkElement.FindName() in C#.

However, it is unavoidable because of the restrictions you mentioned.
I close this ticket.
