### ISSUE TITLE
While scrolling through the rows in the DataGrid, the value of the ComboBox element in the DataGridTemplateColumn CellTemplate is not updated correctly

### ISSUE THREAD

**Issue by vijayarasan** [microsoft/microsoft-ui-xaml#9639]
### Describe the bug

I have defined the ComboBox element in the CellTemplate of the DataGridTemplateColumn. I have bound the SelectedItems property of the ComboBox with an object type property. In this case, when vertically scrolling, the previously selected value is cleared and not maintained. Please refer to the sample and video demo attached for your reference.

[ComboboxSelectedItemDemo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15344866/ComboboxSelectedItemDemo.zip)

### Steps to reproduce the bug

1. Run the sample.
2. Change the first cell value.
3. Change the second cell value also.
4. Scroll the DataGrid to vertically.

 **Observed Behavior :**
   The value is cleared when scrolling the DataGrid.

### Expected behavior

The value should not clear when scrolling the DataGrid.

### Screenshots

![SelectedItemCleared](https://github.com/microsoft/microsoft-ui-xaml/assets/58214164/8f6dc5eb-7ad4-4d15-b576-3380059baaed)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

**Comment by kmgallahan** [comment]
WinUI does not have a built-in DataGrid. You are using a DataGrid from the old version of the Windows Community Toolkit:

https://github.com/CommunityToolkit/WindowsCommunityToolkit

It is not being brought into the new version as-is:

https://github.com/CommunityToolkit/Windows/discussions/31#discussioncomment-5686828

**Comment by ranjeshj** [comment]
@vijayarasan The data grid is from the Windows Community Toolkit, not WinUI. Please report the issue in their repo. Thanks!
https://github.com/CommunityToolkit/WindowsCommunityToolkit/tree/rel/7.1.0
