### ISSUE TITLE
[ListView] The app crash when try to use the right click during a reorder operation.

### ISSUE THREAD

**Issue by jtsilva13** [microsoft/microsoft-ui-xaml#9647]
### Describe the bug

If user click on the right mouse button while draging the item for many times, the component freezes.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/170362320/1d52ded1-6048-4304-964f-0cdb4c7570a2)

### Steps to reproduce the bug

1. Open an app with `ListView` with `CanDragItems="True" CanReorderItems="True" AllowDrop="True"`
2. Click and drag a item
3. While draging the item click with the right button from the mouse

### Expected behavior

The component should not freeze.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/170362320/ebeffd7c-f4dc-4b62-84bf-72ba16937a3b)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
I can repro weirdness in the ListView and GridView samples in WinUI 3 Gallery. The ListView/GridView can get left in a state where it still has items dimmed (other than the one which was dragged) and doesn't entirely respond to mouse input anymore (some events still get through, but it is largely unresponsive).
