### ISSUE TITLE
MenuFlyout text color has the wrong theme when the IsEnable property is changed in CodeBehind and the application theme is different from the OS theme

### ISSUE THREAD

**Issue by rlom** [microsoft/microsoft-ui-xaml#9662]
### Describe the bug

I created a button with a MenuFlyout with three MenuFlyoutItem. When I click the first one, the next two switch to the Disabled state. However, when the application theme is different from the OS theme, the text is the wrong color.

### Steps to reproduce the bug

1- I created a button with a MenuFlyout with three MenuFlyoutItem.
![image](https://github.com/microsoft/WindowsAppSDK/assets/14186796/d26f6f25-f416-4b7b-913a-9348ecbc9ee4)

2- Create a click event on the first MenuFlyout item that changes the IsEnable property to false.
![image](https://github.com/microsoft/WindowsAppSDK/assets/14186796/81aa80d7-5392-4548-9aca-a25dfcb9a26e)

3- Put a different theme in your application than the OS theme.

### Expected behavior

The color of the text must be in accordance with the theme, fully visible.

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/14186796/ea6f2466-e357-482a-9ec6-ae48449f8b36)

![FlyoutSOThemeProblem](https://github.com/microsoft/WindowsAppSDK/assets/14186796/ac86d6d8-2e67-4cb3-8e32-5168375fcc8b)

### NuGet package version

Windows App SDK 1.5.3: 1.5.240428000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 2004 (19041, May 2020 Update)

### IDE

Visual Studio 2022

**Comment by llongley** [comment]
I can't seem to repro the issue with the latest WASDK.  My computer's theme is dark, and when I put the app in light theme, I see this:

![image](https://github.com/user-attachments/assets/4126db5e-c4b5-487d-8a86-fe9681f99471)

If you're still seeing this, then if you could provide a simple repro app that I can test against the latest WASDK to see if this has been fixed, that would be great.  Thanks!
