### ISSUE TITLE
Pivot Item Content disappears from Pivot when dragging

### ISSUE THREAD

**Issue by rafanuness** [microsoft/microsoft-ui-xaml#9664]
### Describe the bug

I created a Pivot with two "tabs": Followers and Following. I disabled the carousel mode setting the IsHeaderItemsCarouselEnabled property to false. When I drag to the left the first tab (trying to go to the second), if I keep dragging after the content of the second tab appears and the Header of the first tab goes outside the Pivot, when I release it, the content disapears. The same occurs when trying to go to the second tab to the first dragging to the right and keep dragging after the content of the first one appears and the Header of the second tab goes outside the Pivot. 
**It only occurs when the Pivot have just two PivotItems.**

### Steps to reproduce the bug

1- Create a Pivot with two PivotItems and set the IsHeaderItemsCarouselEnabled to false :

```
<StackPanel Background="LightBlue" Width="250">
            <Pivot IsHeaderItemsCarouselEnabled="False">
                <PivotItem Header="Followers">
                    <ListView>
                        <ListViewItem Content="Follower 1"/>
                        <ListViewItem Content="Follower 2"/>
                        <ListViewItem Content="Follower 3"/>
                    </ListView>
                </PivotItem>               

                <PivotItem Header="Following" >
                    <ListView>
                        <ListViewItem Content="Person 1"/>
                        <ListViewItem Content="Person 2"/>
                        <ListViewItem Content="Person 3"/>
                    </ListView>
                </PivotItem>
            </Pivot>
        </StackPanel>
```

2- Drag to the left and keep dragging after the content for the next tab appears and the Header of the first tab goes outside the Pivot :
![image](https://github.com/microsoft/WindowsAppSDK/assets/69986484/56c3ee7a-0ed0-4f4b-bc70-7f08572e86a7)

3- Release it:

![image](https://github.com/microsoft/WindowsAppSDK/assets/69986484/f16eb5d0-c3cc-4056-bc58-2585f80d50f6)

### Expected behavior

The content must not disappear and the selected tab must change.

### Screenshots

![PivotBug](https://github.com/microsoft/WindowsAppSDK/assets/69986484/1a748fc1-c077-45c1-bd75-7da4515a6f62)

### NuGet package version

Windows App SDK 1.5.3: 1.5.240428000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022, Visual Studio 2019

**Comment by ranjeshj** [comment]
Pivot is not recommended anymore, and we are not planning on making fixes in this control. Please consider using SelectorBar - https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.selectorbar?view=windows-app-sdk-1.5
