### ISSUE TITLE
Binding to own dependency properties is not working

### ISSUE THREAD

**Issue by Woopsalla** [microsoft/microsoft-ui-xaml#9678]
### Describe the bug

The attached demo project contains a simple GUI with a button and a derived user control _MyUserControl_. 
MyUserControl only contains a border whose background is bound to the background of the user control:

```
void MyUserControl::CreateGui()
{
    winrt::Microsoft::UI::Xaml::Controls::Border b;
    Content(b);
    b.BorderThickness(winrt::Microsoft::UI::Xaml::Thickness{ 1, 1, 1, 1 });
    b.BorderBrush(winrt::Microsoft::UI::Xaml::Media::SolidColorBrush(winrt::Windows::UI::Colors::Black()));

    winrt::Microsoft::UI::Xaml::Data::Binding binding;
    binding.Source(*this);
    binding.Path(winrt::Microsoft::UI::Xaml::PropertyPath(L"Background"));
    b.SetBinding(winrt::Microsoft::UI::Xaml::Controls::Border::BackgroundProperty(), binding);
}
```
MyUserControl also registers its own DependencyProperty _AnotherBrush_ of type Brush:

```
void MyUserControl::InitClass()
{
    mAnotherBrushProperty =
        Microsoft::UI::Xaml::DependencyProperty::Register(
            L"AnotherBrush",
            winrt::xaml_typename<winrt::Microsoft::UI::Xaml::Media::Brush>(),
            winrt::xaml_typename<winrt::UnpackagedDesktopApp::MyUserControl>(),
            Microsoft::UI::Xaml::PropertyMetadata(nullptr)
        );
}
```
InitClass is called in App::OnLaunched before MainWindow is created.
When the MainWindow is initialized, the brushes of the MyUserCOntrol instance are set:
 
```
mUC = winrt::UnpackagedDesktopApp::MyUserControl();
sp.Children().Append(mUC);
mUC.Width(200);
mUC.Height(100);
mUC.Background(winrt::Microsoft::UI::Xaml::Media::SolidColorBrush(winrt::Windows::UI::Colors::GreenYellow()));
mUC.AnotherBrush(winrt::Microsoft::UI::Xaml::Media::SolidColorBrush(winrt::Windows::UI::Colors::Red()));
mUC.Foreground(winrt::Microsoft::UI::Xaml::Media::SolidColorBrush(winrt::Windows::UI::Colors::CornflowerBlue()));
```
When the button is pressed, the background of the MyUserControl instance is bound to its own dependency property AnotherBrush:

```
void MainWindow::myButton_Click(IInspectable const&, RoutedEventArgs const&)
{
    auto checkAnotherBrush = mUC.AnotherBrush();

    winrt::Microsoft::UI::Xaml::Data::Binding binding;
    binding.Source(mUC);
    binding.Path(winrt::Microsoft::UI::Xaml::PropertyPath(L"AnotherBrush")); //doesn't work!!
    //binding.Path(winrt::Microsoft::UI::Xaml::PropertyPath(L"Foreground")); //works
    mUC.SetBinding(winrt::Microsoft::UI::Xaml::Controls::Control::BackgroundProperty(), binding);

    auto checkUCBackground = mUC.Background();

    mBtn.Content(box_value(L"Clicked"));
}
```
The background of MyUserControl should now have the same color as AnotherBrush (i.e. red). When debugging, you can see from the variable checkAnotherBrush that AnotherBrush is actually set. However, the variable checkUCBackground shows that the background is unexpectedly NULL after the binding has been applied. 
However, if the background is bound to the built-in Foreground property instead, it works! 
[DemoApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15452041/DemoApp.zip)

### Steps to reproduce the bug

1.Build and run the attached demo app.
2. Click the button.
3. Debug the method MainWindow::myButton_Click.

### Expected behavior

Binding should also work for own dependency properties.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.10.0

**Comment by Woopsalla** [comment]
Is there any natural intelligence other than AI that can help with this problem? A hint as to the cause of the problem and a possible workaround would help. The demo project is so simple that it is surprising that binding does not work. Maybe someone has a hint on how to further analyze the problem?

**Comment by Woopsalla** [comment]
Thank you Evelyn Wu for your help.  This has solved the problem. Can you recommend any documentation that goes into the subject in more depth? I spent a lot of time looking for a solution and also got suggested solutions elsewhere that actually went in the wrong direction. Perhaps the right reference can shed some light on the subject.

**Comment by evelynwu-msft** [comment]
@Woopsalla This [MSDN article](https://learn.microsoft.com/en-us/windows/uwp/data-binding/data-binding-in-depth) describes in-depth the requirements for different binding scenarios; if you search for `BindableAttribute` you'll find more information about when it is required. (Even though the article itself is in the context of UWP, the same requirements exist for Windows App SDK; I'm looking into why the Windows App SDK version of the article contains significantly less information in comparison.)
