### ISSUE TITLE
WinUI repo “microsoft-ui-xaml-lift” report a large number of errors after building

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#9682]
### Describe the bug

Failed to build WinUI repo(https://microsoft.visualstudio.com/DefaultCollection/WinUI/_git/microsoft-ui-xaml-lift) with a large number of errors. The repo can be built successfully before, not sure what's causing these errors (Xaml code, Visual Studio or Virtual Machine).

Such as below screenshots:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/eb859dea-06c8-4084-9ef9-7822eec9cbf8)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/004a9bfe-2b6d-4b24-97b1-498acd2c7995)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/b71c4172-41b3-49f8-8f87-9431c286f1f6)

### Steps to reproduce the bug

**Repro Steps:**
1. Clone WinUI repo from https://microsoft.visualstudio.com/DefaultCollection/WinUI/_git/microsoft-ui-xaml-lift
2. Open Visual Studio go to Tools->Command Line ->Developer Command Prompt to open a Developer CMD prompt.
3. In the root of repo, run **init.cmd**
4. After Initialize successfully.
5. Run **build.cmd**.

**Actual Result:**
ERROR: Build solution for c:\repo\dxaml\Microsoft.UI.Xaml.sln FAILED.
**Binlog:** 
[Microsoft.UI.Xaml.amd64chk.zip](https://github.com/microsoft/microsoft-ui-xaml/files/15497060/Microsoft.UI.Xaml.amd64chk.zip)

### Expected behavior

Build Successfully.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Additional context

Windows Version: 23H2(22631.3593).
VS Version: 17.11.0 Preview 2.0 [34928.264.main]

**Comment by kmgallahan** [comment]
AFAIK it is not possible to build from the source. Only MS can create WinUI / WASDK builds.

**Comment by codendone** [comment]
@kmgallahan is correct. See #8980:
> ### Q: ​Will we be able to build from the source or only view due to private dependencies?
> #### A: To be clear, we are doing shared source, not open source, as there are underlying interwoven components linking WinUI 3 to the system that we can't share. We will not support building, deploying, or running the source code and will not accept PRs for it. We will support viewing, searching, and debugging of the source code when it is available.

We should get this info added to some place easier to find, such as contribution_handling.md.

**Comment by codendone** [comment]
I updated my comment above to point to another reference, which can be a little hidden due to being in the winui3/ branches.
