### ISSUE TITLE
ItemsSource breaks with AOT

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#9699]
### Describe the bug

1. If you set the source for a collection control in XAML, you'll get an unhandled win32 exception;
2. If you set the source in code it'll run until you try to modify the collection. You'll get the same exception then.

### Steps to reproduce the bug

[Repro](https://github.com/eduardobragaxz/AOTRepro)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

1.6 experimental 1

**Comment by eduardobragaxz** [comment]
A workaround for controls that have an Items property is to add the items directly into it. Unfortunately, that's not the case of ItemsRepeater.

**Comment by Scottj1s** [comment]
@eduardobragaxz thanks for reporting this.  The issue has been fixed and will be available in the next preview release of the [Microsoft.Windows.CsWinRT](https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/) package.

**Comment by eduardobragaxz** [comment]
Nice.
