### ISSUE TITLE
XamlDirect - Any benefits to be had moving from XAML Parsing?

### ISSUE THREAD

**Issue by mdtauk** [Microsoft/microsoft-ui-xaml#97]
With XamlDirect looking to become richer in future versions of Windows - is there any benefits to be had from moving the XAML UI controls away from using XAML files, and handling them in code using XAML Direct?

**Comment by jevansaks** [comment]
This is a great question, I'll bring it up with the parser team. It is at least worth an investigation.

**Comment by michael-hawker** [comment]
It'd be nice if this could be a compiler type change across all apps/usages I think instead.  XAML is nice for human readability, re-templating, and re-use.

**Comment by jevansaks** [comment]
XamlDirect was designed for middleware (like React Native) to activate and get/set properties faster than through the WinRT API and without needing the overhead of "peers" (an internal implementation detail that adds overhead to some objects when calling through the WinRT ABI). XAML / XBF still has size/performance advantages over code-based approaches. I think Michael's suggestion to have it be a XamlCompiler experimentation option is a good one and we might look into this in the future. But for now this isn't something on our roadmap.
