### ISSUE TITLE
TitleBar doesn't support TitleBarHeightOption.Standard

### ISSUE THREAD

**Issue by riverar** [microsoft/microsoft-ui-xaml#9701]
The AppWindow `TitleBarHeightOption` is set to `Standard` by default driven by system metrics, but the TitleBar control doesn't seem to be customizable to match. (I expect the glyphs, text, etc. to align with the system controls.) Am I missing something? Feels like the new TitleBar control should have matching Standard/Tall/Collapsed modes for easy use out of the box?

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/475132/860ef600-f8e5-4c1a-8cc3-11b575387688)

**Comment by mdtauk** [comment]
The Figma design guidance states the new type of Title Bar with the buttons, and subtitles etc should support Standard and Tall modes.

<img width="875" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/7389110/41ef8018-5aa4-4532-9ee7-aadecb99a67d">

**Comment by karkarl** [comment]
Thanks for the response @mdtauk. WinUI TitleBar will come with the height options as outlined in the Figma file above. Please reference the WIP Specs: https://github.com/microsoft/microsoft-ui-xaml/blob/main/specs/TitleBar/titlebar-functional-spec.md?plain=1#L486

Marking as resolved.
