### ISSUE TITLE
Can't select text from TextBox/AutoSuggestBox set as content in TitleBar with the cursor

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#9702]
### Describe the bug

When using a TextBox/AutoSuggestBox as content in the TitleBar control you can't select the text with the cursor. It drags the window instead. Also, the cursor doesn't change into the caret when hovering the TextBox/AutoSuggestBox.

### Steps to reproduce the bug

Create a project with the TitleBar control and add a TextBox/AutoSuggestBox as content and run.

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Experimental 1: 1.6.240531000-experimental1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by AndrewKeepCoding** [comment]
Same here.

**Comment by ghost1372** [comment]
footer and header also does not work, all of them calculated as a drag regions

**Comment by veler** [comment]
Hi,

I reproduce a similar issue. My monitor is on 125% scale. As you can see on the video below, I can click on the Settings button if the mice cursor is some space to the left of it, but not fully hover it.

https://github.com/microsoft/microsoft-ui-xaml/assets/3747805/61805901-358d-4032-b34e-b67e309e7c9c

This issue does NOT reproduce is my monitor scale is at 100%.

**Comment by ghost1372** [comment]
@ranjeshj ?

**Comment by karkarl** [comment]
@veler I am able to repro this issue only if the scale factor has changed, is that the case for you? It seems that on scale factor changed, TitleBar needs to recalculate its passthrough regions.

**Comment by karkarl** [comment]
The issue doesn't repro in the experimental2 release, can you try verifying if this resolves your issue? A bunch of PR's were missed in the experimental1 cherry-pick...
