### ISSUE TITLE
Enabling NumberBox AcceptsExpression ignores numbers smaller than 1 when entered in scientific notation

### ISSUE THREAD

**Issue by ThierryPalmSens** [microsoft/microsoft-ui-xaml#9704]
### Describe the bug

When entering a value smaller than 1 in scientific notation, i.e. '1e-1', '1e-2', and so on the value in the field is not updated. The NumberBoxParser.cpp does not check whether the '-' or '+' symbols are preceded by an 'e' or 'E'. For example, when entering '1e-2' it will try to subtract '2' from '1e', but '1e' is not valid so it will not update the value in the field.

### Steps to reproduce the bug

1. Place a NumberBox control in a WinUI3 app and set AcceptsExpression to true.
2. Run the app.
3. Enter ''1e-2".

### Expected behavior

The NumberBoxParser should ignore the '+' and '-' symbols when preceded by an 'e' or 'E' and parse '1e-2' as '0.01'.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

**Comment by tpoint75** [comment]
And what makes the NumberBox if I enter 1^15?
Right it displays 1000000000000000. This implementation is not useful for scientific application.
