### ISSUE TITLE
Expanders need a button on the arrow to assist with the narrator.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/microsoft-ui-xaml#9706]
### Describe the bug

The expander control lacks any information that tells a user using the narrator that they are on an actionable item.  Narrator announces a "group" and if the expander is expanded or not, but not if the user can take an action.

### Steps to reproduce the bug

1. Open the WinUI 3 Gallery
2. Go to the expander page.
3. Turn on narrator.
4. Tab over to an expander.
5. Narrator read [Title] group [state]

### Expected behavior

Narrator announces that the expander can be interacted with.  [title] Group CanExpand(?)  I don't know the best content.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

**Comment by kmahone** [comment]
Thanks for providing this feedback. The Xaml Expander control implements the ExpandCollapse Pattern through UIAutomation. Xaml does not directly control how Narrator (or other assistive technology) describes the control. 
In this case it reads out the state of the control as either Collapsed or Expanded.

I will pass along this feedback to the Narrator team to see if they want to be more descriptive in this scenario.
