### ISSUE TITLE
ListView doesn't respect Visibility of contents

### ISSUE THREAD

**Issue by krschau** [microsoft/microsoft-ui-xaml#9708]
### Describe the bug

If you have a `ListView` and set `Visibility="Collapsed"` on an item inside it, the `ListView` still leaves space for the item and shows the background color on hover. This is unlike other controls with their Visibility collapsed.

Here is a screenshot of the XAML bellow:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/47155823/c82a557a-73eb-4b4e-b22d-56e4804abea5)

### Steps to reproduce the bug

Min repro: Create a blank WinUI 3 Desktop app and add set the content of the MainWindow to the following:

```xml
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <ListView>
            <TextBlock>Text 1</TextBlock>
            <TextBlock Visibility="Collapsed">Text 2</TextBlock>
            <TextBlock>Text 3</TextBlock>
            <TextBlock>Text 4</TextBlock>
        </ListView>
    </StackPanel>
```

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Additional context

Causing Dev Home bug https://github.com/microsoft/devhome/issues/3161. Dev Home is on a slightly lower version of WASDK 1.5 but I repro'ed with latest version above.

**Comment by ranjeshj** [comment]
@krschau ListView lays out ListViewItem and even though the content is not visible, the ListViewItem is. This approach in general is not going to work well with virtualizing controls. I'd recommend removing from the list (or items source) instead.

**Comment by krschau** [comment]
@ranjeshj I can understand the Collapsed item still taking up space (although using the word "collapsed" for that case doesn't make much sense) but it seems to be very unexpected behavior that the empty space would still change color when a cursor moves over it.

**Comment by ranjeshj** [comment]
@krschau what is collapsed is the TextBlock, not the ListViewItem that gets created automatically for you. Take a look at the live visual tree and you can see the elements that get created. You will notice a ListViewItem container for each item to provide the hover, pressed, selected visuals.
