### ISSUE TITLE
Able to change the window height even if IsResizable is false but ExtendsContentIntoTitleBar is true

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#9709]
### Describe the bug

If you set ExtendsContentIntoTitleBar to true you'll still be able to change a window's height when IsResizable is false.

### Steps to reproduce the bug

Set presenter.IsResizable to false and ExtendsContentIntoTitleBar to true and try to change the window's height with the cursror.

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Experimental 1: 1.6.240531000-experimental1

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

I'm not sure this is already fixed internally as part of #8665. @codendone

**Comment by codendone** [comment]
This is very similar to #9670, though that issue is only talking about the cursor being incorrect.

I'm not able to actually resize the window **when using 1.5**, but I do repro the issue with **1.6-experimental1**.

**Comment by codendone** [comment]
This was closed as fixed/duplicate of #7629. The fix will be in the next 1.6 release.
