### ISSUE TITLE
`NumberBox` different visuals in 1.6-exp1

### ISSUE THREAD

**Issue by morning4coffe-dev** [microsoft/microsoft-ui-xaml#9714]
### Describe the bug

With the update to WinUI3-WASDK 1.6-exp1, the `NumberBox` has changed the background of the control. It seems to be a bug, since all other input fields are using ligher default background. 
## Old `NumberBox` (1.5.3):
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/78549750/cf56fb1c-c8d3-40b5-b57b-a7baf2cdc6c4)
## New `NumberBox` (1.6-exp1):
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/78549750/f5b99720-cc51-47d7-b583-edb602780391)
- other input fields in 1.6-exp1: 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/78549750/0a0a990c-72b7-458a-9538-04866d76a930)

### Steps to reproduce the bug

1. Create a new WinUI3 project
2. Update to 1.6-exp1
3. Add `NumberBox` control 

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Experimental 1: 1.6.240531000-experimental1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
This is fixed in [1.6.240701003-experimental2](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.6.240701003-experimental2).
