### ISSUE TITLE
ElementName bindings deeper in ItemsRepeater.ItemTemplate don't work 

### ISSUE THREAD

**Issue by Naveen61097** [microsoft/microsoft-ui-xaml#9715]
Still Facing this Issue on Windows App SDK v1.5.240404000

_Originally posted by @AathifMahir in https://github.com/microsoft/microsoft-ui-xaml/issues/560#issuecomment-2082448161_

**Comment by Naveen61097** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/560#issuecomment-2072902364

**Comment by Naveen61097** [comment]
Upon checking the issue in the latest version (1.5.240607001) I have identified that the `ElementName` binding is working fine for the very first Element inside the `DataTemplate`. But using the `ElementName` binding inside its Children/Content, it breaks.

Here is the sample code, with issue and also a workaround solution,

<UserControl x:Class="App9.UserControl1"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="using:App9"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             x:Name="RootControl"
             mc:Ignorable="d">

    <Grid Margin="0,100,0,0" ColumnSpacing="100">

        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        
        <StackPanel Grid.Column="0">
            <TextBlock Text="TextBlock located directly inside DataTemplate"
                       Height="100"
                       TextWrapping="Wrap" />

            <ItemsRepeater ItemsSource="{x:Bind Users}">
                <ItemsRepeater.ItemTemplate>
                    <DataTemplate x:DataType="x:String">
                        <TextBlock Text="{Binding ViewModel.SampleText, ElementName=RootControl, Mode=OneWay}" />
                    </DataTemplate>
                </ItemsRepeater.ItemTemplate>
            </ItemsRepeater>
        </StackPanel>

        <StackPanel Grid.Column="1">
            <TextBlock Text="TextBlock not located directly inside DataTemplate"
                       Height="100"
                       TextWrapping="Wrap" />

            <ItemsRepeater ItemsSource="{x:Bind Users}">
                <ItemsRepeater.ItemTemplate>
                    <DataTemplate x:DataType="x:String">
                        <StackPanel>
                            <TextBlock Text="{Binding ViewModel.SampleText, ElementName=RootControl, Mode=OneWay}" />
                        </StackPanel>
                    </DataTemplate>
                </ItemsRepeater.ItemTemplate>
            </ItemsRepeater>
        </StackPanel>

        <StackPanel Grid.Column="2">
            <TextBlock Text="TextBlock not located directly inside DataTemplate - Workaround"
                       Height="100"
                       TextWrapping="Wrap" />

            <ItemsRepeater ItemsSource="{x:Bind Users}">
                <ItemsRepeater.ItemTemplate>
                    <DataTemplate x:DataType="x:String">
                        <StackPanel x:Name="RootPanel"
                                    Loaded="RootPanel_Loaded">
                            <TextBlock Text="{Binding Tag.ViewModel.SampleText, ElementName=RootPanel, Mode=OneWay}" />
                        </StackPanel>
                    </DataTemplate>
                </ItemsRepeater.ItemTemplate>
            </ItemsRepeater>
        </StackPanel>

    </Grid>
</UserControl>


    public sealed partial class UserControl1 : UserControl
    {
        public List<string> Users { get; set; } = [];

        public InvoiceViewModel ViewModel { get; set; } = new InvoiceViewModel()
        {
            SampleText = "Test String"
        };

        public UserControl1()
        {
            for (int i = 0; i < 10; i++)
            {
                Users.Add(i.ToString());
            }

            this.InitializeComponent();
            this.DataContext = this;
        }

        private void RootPanel_Loaded(object sender, RoutedEventArgs e)
        {
            (sender as FrameworkElement).Tag = this;
        }
    }

    public class InvoiceViewModel
    {
        public string SampleText { get; set; }
    }

Output:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/59611026/db01cddc-106f-48e2-b563-47ae5a920f82)


As a workaround, On the `Loaded` event of the very first element, I have assigned the `this` object to its `Tag` property and used it to get the ViewModel object inside the DataTemplate.

As we have migrated all the existing ListView controls to ItemsRepeater and ItemsView, this is a showstopper issue for us. Provide the fix ASAP and also your input on proceeding with the above workaround.

**Comment by Naveen61097** [comment]
@michael-hawker @AndrewKeepCoding your thoughts on the workaround please.

**Comment by michael-hawker** [comment]
Surprised this would have regressed between releases. Related to #2508 which would be having x:Bind properly work in these scenarios to begin with. FYI @evelynwu-msft.

**Comment by Naveen61097** [comment]
Related to #2508, In my case, the ViewModel object will be passed to the Xaml UserControl through Constructor or Dependency Property i.e through code-behind. In such cases I cannot assign x:Name for it, hence the x: Bind is not working.

**Comment by AndrewKeepCoding** [comment]
@Naveen61097 AFAIK, the fix addressed in v1.5 never fixed this issue. Can you share a reproducible project of your case?

**Comment by ranjeshj** [comment]
I created a simpler repro to show the problem. ElementName bindings at root work as expected now, but nested inside don't seem to.

```
 <StackPanel>
     <TextBlock Text="Hello" x:Name="MyTextBlock1"/>
     <TextBlock Text="World" x:Name="MyTextBlock2"/>
     <ItemsRepeater x:Name="repeater1">
         <ItemsRepeater.ItemTemplate>
             <DataTemplate>
                 <TextBlock Text="{Binding Text, ElementName=MyTextBlock1, Mode=OneWay}" />
             </DataTemplate>
         </ItemsRepeater.ItemTemplate>
     </ItemsRepeater>

     <ItemsRepeater x:Name="repeater2">
         <ItemsRepeater.ItemTemplate>
             <DataTemplate>
                 <StackPanel>
                     <TextBlock Text="{Binding Text, ElementName=MyTextBlock2, Mode=OneWay}" />
                 </StackPanel>
             </DataTemplate>
         </ItemsRepeater.ItemTemplate>
     </ItemsRepeater>
 </StackPanel>

 repeater1.ItemsSource = repeater2.ItemsSource = Enumerable.Range(0, 5);
```

**Comment by ranjeshj** [comment]
One potential simpler workaround than the loaded event would be to bind to root of the template and bind again like so (not ideal but should work)

```
  <ItemsRepeater x:Name="repeater2">
      <ItemsRepeater.ItemTemplate>
          <DataTemplate>
              <StackPanel x:Name="mystack" Tag="{Binding Text, ElementName=MyTextBlock2, Mode=OneWay}">
                  <TextBlock Text="{Binding Tag, ElementName=mystack, Mode=OneWay}" />
              </StackPanel>
          </DataTemplate>
      </ItemsRepeater.ItemTemplate>
  </ItemsRepeater>
```
