### ISSUE TITLE
"1.5.4" x64 download link is broken

### ISSUE THREAD

**Issue by karmeye** [microsoft/microsoft-ui-xaml#9728]
### Describe the bug

Cannot download WinAppSDK 1.5.4 installer x64 from https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

> This page isn’t workingdownload.microsoft.com is currently unable to handle this request.
HTTP ERROR 503

### Steps to reproduce the bug

1. https://aka.ms/windowsappsdk/1.5/1.5.240607001/windowsappruntimeinstall-x64.exe

### NuGet package version

None

**Comment by codendone** [comment]
The link looks correct and is working for me. Maybe there was a temporary server issue. Is it working for you now?
