### ISSUE TITLE
The icons and labels of inactive left NavigationView categories and the active category are both black

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#973]
**Describe the bug**

Inactive NavigationView categories are the same colour as the active category

**Steps to reproduce the bug**

1. Open Settings
2. Click on System

**Expected behavior**

Only the icon and label of the Display category would be black and have the highlight

**Screenshots**

![image](https://user-images.githubusercontent.com/51363864/60410784-363d3680-9c0d-11e9-89c0-522dcecb73ce.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

What Spotify looks like: 
![image](https://user-images.githubusercontent.com/51363864/60410801-553bc880-9c0d-11e9-8f30-ff49de71d041.png)

the top DisplayMode is not affected and neither is the pivot control.

**Comment by mdtauk** [comment]
I think this is by design

**Comment by jevansaks** [comment]
This by design, but it sounds like you might be asking to change it? @poopooracoocoo do you want me to change this to a discussion topic?

**Comment by Poopooracoocoo** [comment]
Sure thing! :D @jevansaks 

I didn't know this was by design but I can see why. I'm pretty sure that Settings doesn't use the new NavigationView or a new version of WinUI as the highlight is thicker and lacks the animation so when/if it gets updated, which category is active will be less obvious. 

This has to do with accessibility of course but the top display mode and pivots aren't affected. 

and IIRC there's no way to tell which category is active with SplitViews

(this is a comment i made a couple of days ago and forgot to hit comment on)

**Comment by jevansaks** [comment]
Re-opening as discussion. It's currently by-design for the spec but I could see merit to changing it.

**Comment by mdtauk** [comment]
As an alternative to making the other NavigationViewItems greyed out, you could make the currently selected one Semibold so the **current** item stands out, without the potential of failing the contrast ratio tests for all the other items.

**Comment by Poopooracoocoo** [comment]
https://assets.pcmag.com/media/images/604444-google-drive-web.png?thumb=y

This is an image of Google Drive's design that I just took from a Google search.

**Comment by Poopooracoocoo** [comment]
The design of navigation panes has been changed to make the visual indicator of the active category more visible.
