### ISSUE TITLE
How to nest ItemsControl?

### ISSUE THREAD

**Issue by Tartarusome** [microsoft/microsoft-ui-xaml#9735]
### Describe the bug

I hava two custom controls defined by class and ResourcesDictionary , both inherit from ItemsControl.
When I insert the second one between the ControlTemplate and the ItemsPresenter of the first one, this control's items disappeared.
before
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/142856268/f52c4782-f497-43ca-93b5-0ccdf33cca80)
after
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/142856268/6f76e477-8659-415d-a5e8-eda3807f9eac)

### Steps to reproduce the bug

first one
`<Setter Property="Template">
    <Setter.Value>
        <ControlTemplate TargetType="FirstItemsControl">
            <SecondItemsControl>
                <ItemsPresenter></ItemsPresenter>
            </SecondItemsControl>
        </ControlTemplate>
    </Setter.Value>
</Setter>`

second one
`<Setter Property="Template">
    <Setter.Value>
        <ControlTemplate TargetType="SecondItemsControl">
            <SomePanel>
                <ItemsPresenter></ItemsPresenter>
            </SomePanel>
        </ControlTemplate>
    </Setter.Value>
</Setter>`

### NuGet package version

WinUI 3 - Windows App SDK 1.5.4: 1.5.240607001

### Additional context

I tried these properties below, but they can only hide the internal structure from the visual tree.
[Browsable(false)]
[EditorBrowsable(EditorBrowsableState.Never)]
```[tasklist]
### Tasks
```

**Comment by kmahone** [comment]
Can you please share a full repro for this issue? I am not able to reproduce the issue with the steps provided.
