### ISSUE TITLE
Custom Title Bar Drag Region prevents click on taskbar buttons in Fullscreen mode at certain size

### ISSUE THREAD

**Issue by jpageacsys** [microsoft/microsoft-ui-xaml#9749]
### Describe the bug

My app has tabs similar to Google Chrome or Edge in the taskbar.  I have a grid in the TabStripFooter with a margin to the right and I update with SetDragRectangles whenever the size changes. This works perfectly at any size with any number of tabs when the app is not fullscreen. However, once I open around 5 tabs in fullscreen mode, I can no longer click on the taskbar buttons. Users started reporting this behavior last week even though I didn't change the code at all. I made a quick barebones test app to reproduce the issue.

Edit:
I've seen in this issue that we should now use "SetRegionRects"
https://github.com/microsoft/microsoft-ui-xaml/issues/8878
I've tried that as well and the behavior is identical.
This issue is closed, but people are still commenting with similar issues:
https://github.com/microsoft/WindowsAppSDK/issues/2574

Workaround:
I downgraded Microsoft.WindowsAppSDK to 1.4.240512000 and that fixed the issue. Seems like a bug in the update since the code works as expected when I downgrade the library.

### Steps to reproduce the bug

I created a repository with an example of the issue. The UpdateDragRegion function records the correct coordinates and position.
https://github.com/joelphilippage/TabViewTest

### Expected behavior

The intended behavior is that the user can interact with tabs normally and use the default task bar buttons (minimize, Fullscreen, and close).

### NuGet package version

WinUI 3 - Windows App SDK 1.5.4: 1.5.240607001

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kjean667** [comment]
I have encountered a similar issue with the drag area not being correctly updated, and thus making some buttons on the titlebar unclickable, when maximizing the window.
For me it was working fine with WindowsAppSDK 1.4.240211001 but not with later releases.

**Comment by jpageacsys** [comment]
I tried the latest pre-release version of 1.6 which fixed it, but unfortunately it broke several controls I'm using so I can't update yet.
