### ISSUE TITLE
How To delate the entire titlebar

### ISSUE THREAD

**Issue by Tartarusome** [microsoft/microsoft-ui-xaml#9750]
I used win32 dll to set the height of titlebar to 0, which is equal to Windows.Style="None" if WPF.
but the window would reserve a region with colored background, like the red region below.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/142856268/4b3bdb11-006b-4c0c-8016-f46142ced5b0)

i write SetLayeredWindowAttributes(hWnd, 0, 0, LWA_ALPHA);  but it doesnt work.

Here is my cs-behind
`public sealed partial class DockWindow : Window
{
    public DockWindow()
    {
        this.InitializeComponent();
        //style=none
        IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);

        // Get the window's style
        int style = GetWindowLongPtr(hWnd, GWL_STYLE).ToInt32();

        // Modify the window's style to remove the caption
        SetWindowLongPtr(hWnd, GWL_STYLE, new IntPtr(style & ~(WS_CAPTION)));

        // Get the window's position and size
        RECT windowRect;
        GetWindowRect(hWnd, out windowRect);

        // Set the window's position and size to hide the title bar
        SetWindowPos(
            hWnd,
            IntPtr.Zero,
            windowRect.Left,
            windowRect.Top - 24,
            windowRect.Right - windowRect.Left,
            windowRect.Bottom - windowRect.Top + 24,
            SWP_NOZORDER | SWP_FRAMECHANGED
        );

        // Set the window's transparency
        SetLayeredWindowAttributes(hWnd, 0, 0, LWA_ALPHA); // 200 is the alpha value (0-255)
    }

    private const int GWL_STYLE = -16;
    private const int WS_CAPTION = 0x00C00000;
    private const int SWP_NOZORDER = 0x0004;
    private const int SWP_FRAMECHANGED = 0x0020;
    private const int LWA_ALPHA = 0x00000002;

    [DllImport("user32.dll", SetLastError = true)]
    private static extern IntPtr GetWindowLongPtr(IntPtr hWnd, int nIndex);

    [DllImport("user32.dll", EntryPoint = "SetWindowLongPtr", SetLastError = true)]
    private static extern IntPtr SetWindowLongPtr(IntPtr hWnd, int nIndex, IntPtr dwNewLong);

    [DllImport("user32.dll", SetLastError = true)]
    private static extern bool GetWindowRect(IntPtr hWnd, out RECT lpRect);

    [DllImport("user32.dll", SetLastError = true)]
    private static extern bool SetWindowPos(
        IntPtr hWnd,
        IntPtr hWndInsertAfter,
        int X,
        int Y,
        int cx,
        int cy,
        uint uFlags
    );

    [StructLayout(LayoutKind.Sequential)]
    private struct RECT
    {
        public int Left;
        public int Top;
        public int Right;
        public int Bottom;
    }

    [DllImport("user32.dll", SetLastError = true)]
    private static extern bool SetLayeredWindowAttributes(
        IntPtr hWnd,
        uint crKey,
        byte bAlpha,
        uint dwFlags
    );
}`

**Comment by castorix** [comment]
With 1.4, I use _OverlappedPresenter.SetBorderAndTitleBar_(false, false) + _OverlappedPresenter.IsResizable_ = false

**Comment by Tartarusome** [comment]
> With 1.4, I use _OverlappedPresenter.SetBorderAndTitleBar_(false, false)在 1.4 中，我使用 OverlappedPresenter.SetBorderAndTitleBar（false， false） and _OverlappedPresenter.IsResizable_ = false (removes WS_THICKFRAME)和 OverlappedPresenter.IsResizable = false（删除WS_THICKFRAME）

It works on 1.5.4 too, but how can I resize the window?Must I create a small triangle in the corner by myself?

**Comment by castorix** [comment]
> It works on 1.5.4 too, but how can I resize the window?Must I create a small triangle in the corner by myself?

A way is to let it resizable and subclass it (_SetWindowSubclass_) to handle _WM_NCCALCSIZE_ (mainly to increment the first RECT.top to reduce the size of top border) 
I tested on Windows 10 and I had to increment left and decrement right and bottom too (quick test with random values, should be calculated with APIs like AdjustWindowRect...) :

![NoCaption_Resizable](https://github.com/microsoft/microsoft-ui-xaml/assets/22345506/bb3461d0-296b-4a52-baa8-4f7a91a78635)

**Comment by Tartarusome** [comment]
> > It works on 1.5.4 too, but how can I resize the window?Must I create a small triangle in the corner by myself?它也适用于 1.5.4，但是如何调整窗口大小？我必须自己在角落里创建一个小三角形吗？
> 
> A way is to let it resizable and subclass it (_SetWindowSubclass_) to handle _WM_NCCALCSIZE_ (mainly to increment the first RECT.top to reduce the size of top border)一种方法是让它可调整大小并对其进行子类化 （SetWindowSubclass） 以处理WM_NCCALCSIZE（主要是增加第一个 RECT.top 以减小顶部边框的大小） I tested on Windows 10 and I had to increment left and decrement right and bottom too (quick test with random values, should be calculated with APIs like AdjustWindowRect...) and set lParam to -1 in _WM_NCACTIVATE_, as MSDN says... and also _SetWindowPos_ in Activated event for the first time the window is displayed) :我在 Windows 10 上进行了测试，我也必须向左递增，向右递减右键和下键（使用随机值进行快速测试，应该使用 AdjustWindowRect 等 API 进行计算...）并在 WM_NCACTIVATE 年将 lParam 设置为 -1，正如 MSDN 所说......以及首次显示窗口时激活事件中的 SetWindowPos）：
> 
> ![NoCaption_Resizable](https://private-user-images.githubusercontent.com/22345506/341997412-bb3461d0-296b-4a52-baa8-4f7a91a78635.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTU4NTcsIm5iZiI6MTcxOTI5NTU1NywicGF0aCI6Ii8yMjM0NTUwNi8zNDE5OTc0MTItYmIzNDYxZDAtMjk2Yi00YTUyLWJhYTgtNGY3YTkxYTc4NjM1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NGFmYTUyZWVhNTEwNDBjZGE5OTRiZjM2YWQ1ZDA3NjhiOWZiZDhlZTE5ODhjZmIzYTFmNzk0M2JhNzlhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.__epSRcOXQjUIP6H9xiVUFzl7DjwzlXjaoUx8OIkEWQ) [ ![NoCaption_Resizable](https://private-user-images.githubusercontent.com/22345506/341997412-bb3461d0-296b-4a52-baa8-4f7a91a78635.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTU4NTcsIm5iZiI6MTcxOTI5NTU1NywicGF0aCI6Ii8yMjM0NTUwNi8zNDE5OTc0MTItYmIzNDYxZDAtMjk2Yi00YTUyLWJhYTgtNGY3YTkxYTc4NjM1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NGFmYTUyZWVhNTEwNDBjZGE5OTRiZjM2YWQ1ZDA3NjhiOWZiZDhlZTE5ODhjZmIzYTFmNzk0M2JhNzlhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.__epSRcOXQjUIP6H9xiVUFzl7DjwzlXjaoUx8OIkEWQ) ](https://private-user-images.githubusercontent.com/22345506/341997412-bb3461d0-296b-4a52-baa8-4f7a91a78635.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTU4NTcsIm5iZiI6MTcxOTI5NTU1NywicGF0aCI6Ii8yMjM0NTUwNi8zNDE5OTc0MTItYmIzNDYxZDAtMjk2Yi00YTUyLWJhYTgtNGY3YTkxYTc4NjM1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NGFmYTUyZWVhNTEwNDBjZGE5OTRiZjM2YWQ1ZDA3NjhiOWZiZDhlZTE5ODhjZmIzYTFmNzk0M2JhNzlhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.__epSRcOXQjUIP6H9xiVUFzl7DjwzlXjaoUx8OIkEWQ) [ ](https://private-user-images.githubusercontent.com/22345506/341997412-bb3461d0-296b-4a52-baa8-4f7a91a78635.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTU4NTcsIm5iZiI6MTcxOTI5NTU1NywicGF0aCI6Ii8yMjM0NTUwNi8zNDE5OTc0MTItYmIzNDYxZDAtMjk2Yi00YTUyLWJhYTgtNGY3YTkxYTc4NjM1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NGFmYTUyZWVhNTEwNDBjZGE5OTRiZjM2YWQ1ZDA3NjhiOWZiZDhlZTE5ODhjZmIzYTFmNzk0M2JhNzlhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.__epSRcOXQjUIP6H9xiVUFzl7DjwzlXjaoUx8OIkEWQ)

Hey bro. I just found a perfect way.It looks like the following:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/142856268/9ac09879-0d6b-4fdb-9747-2b24b57776d9)
This code would totally hide the title bar and the three caption buttons, but preserve a 32 or maybe 48 px draggable rectangle overlay.You can set it to be interactive if you want.
[MS Learn Document](https://learn.microsoft.com/zh-cn/windows/apps/develop/title-bar#interactive-content)

Here is the code.
` public DockWindow()
 {
     this.InitializeComponent();
     ExtendsContentIntoTitleBar = true;
     SetTitleBar(Part_TitleBar);
     var TestTitleBar = AppWindow.TitleBar;
     **TestTitleBar.PreferredHeightOption = TitleBarHeightOption.Collapsed;**
 }`

**Comment by codendone** [comment]
It sounds like this has been solved.
