### ISSUE TITLE
How to change the selection text foreground color in WPF MS TextBox control  

### ISSUE THREAD

**Issue by YuvarajMasilamani** [microsoft/microsoft-ui-xaml#9754]
### Describe the bug

When we changed the text box selection color using the selection brush property, the foreground color of the selection text was black and the opacity of the selection brush was altered.  We then set the selection opacity property to 1, and the selection text was disabled.
[TextBoxSelectionIssue.zip](https://github.com/user-attachments/files/15950401/TextBoxSelectionIssue.zip)

### Steps to reproduce the bug

1. Set the SelectionBrush property.
2. Run the sample.
3. Note the issue

### Expected behavior

When the text box selection color was changed, the opacity of the color did not change, and the selection text color was changed to white

### Screenshots

After changing the selection color
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/102359751/8c95a797-d5b9-4f15-9b42-697363886429)

After changing the SelectionOpacity
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/102359751/75cf542d-0afa-4a18-b19c-4eaa975d3366)

Expected behaviour
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/102359751/85550228-a445-4cd4-9166-50053786afa0)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

**Comment by YuvarajMasilamani** [comment]
Is there any way to change the selection text foreground color in the textbox control?

**Comment by codendone** [comment]
I think the [dotnet/wpf](https://github.com/dotnet/wpf) repo is the right place for WPF questions.
