### ISSUE TITLE
EmbeddedResource in Xaml

### ISSUE THREAD

**Issue by RoccoZero** [microsoft/microsoft-ui-xaml#9759]
I don't understand why this code doesn't work
```
<Image Source="pack://application:,,,/Resources/Steam.png" Width="30"/>
```
[https://stackoverflow.com/questions/62032643/using-image-in-xaml-from-resources-resx](url)

how should I use embedded resource?
I just don't want all the resources to be in the bin folder
can someone help me on how to use EmbeddedResource in Xaml?

**Comment by Gaoyifei1011** [comment]
> I don't understand why this code doesn't work
> 
> ```
> <Image Source="pack://application:,,,/Resources/Steam.png" Width="30"/>
> ```
> 
> [https://stackoverflow.com/questions/62032643/using-image-in-xaml-from-resources-resx](url)
> 
> how should I use embedded resource? I just don't want all the resources to be in the bin folder can someone help me on how to use EmbeddedResource in Xaml?

This applies only to wpf, please use ms-appx for winui resources
