### ISSUE TITLE
Remove usage of unsupported API ICompositionNotifyPropertyChangedPartner in Reveal tests

### ISSUE THREAD

**Issue by DmitriyKomin** [microsoft/microsoft-ui-xaml#976]
The API ICompositionNotifyPropertyChangedPartner is internal and not supported in Windows going forward. Currently, it's used in the following tests:

RevealBrushTests .RevealButtonStates_Values
RevealBrushTests RevealButtonStates_FastRelease_Values
RevealBrushTests RevealButtonStates_SlowRelease_Values
RevealBrushTests RevealHoverLightPosition_Values

Remove references to the API and disable the tests for now. At that point, we should open another issue to track re-enabling the tests with a different mechanism for tracing COMP expression values.

**Comment by JJBrychell** [comment]
Fixed in August 2020 when the interface was changed to IExpCompositionPropertyChanged.
