### ISSUE TITLE
ListView issue

### ISSUE THREAD

**Issue by jpeterstewart** [microsoft/microsoft-ui-xaml#9766]
### Describe the bug

ListView overflows its bottom boundary in the app window after adding 52,452 items.

### Steps to reproduce the bug

The small test app in this repository can be used to reproduce the bugs:

[ItemsView Issue](https://github.com/jpeterstewart/ItemsView_Issue)

### Expected behavior

No overflow outside the ListView frame.

### Screenshots

<img width="732" alt="image" src="https://github.com/microsoft/WindowsAppSDK/assets/36552625/5df93c2a-3446-4b2e-9c9f-01e26500dad3">

### NuGet package version

Windows App SDK 1.5.4: 1.5.240311000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 23H2 (22631.3737, 2024 Update)

### IDE

Visual Studio 2022

### Additional context

I moved an issue with ItemsView to a separate issue report so that they can be tracked separately.

**Comment by ranjeshj** [comment]
dup of https://github.com/microsoft/microsoft-ui-xaml/issues/8028
