### ISSUE TITLE
ItemsView issue

### ISSUE THREAD

**Issue by jpeterstewart** [microsoft/microsoft-ui-xaml#9767]
### Describe the bug

•	ItemsView can be made to crash by just scrolling up and down a little after adding a few hundred items.
•	ItemsView becomes slow as molasses when adding new items after a few hundred items.

### Steps to reproduce the bug

The small test app in this repository can be used to reproduce the bugs:

[ItemsView Issue](https://github.com/jpeterstewart/ItemsView_Issue)

### Expected behavior

1. No crashes
2. No huge slowdown when adding items

### Screenshots

It would have to be a video, not a screenshot, but it can be easily reproduced with the test app.

### NuGet package version

Windows App SDK 1.5.4: 1.5.240311000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 23H2 (22631.3737, 2024 Update)

### IDE

Visual Studio 2022

### Additional context

I moved this issue with ItemsView to a separate issue report so that it can be tracked separately.

**Comment by Gaoyifei1011** [comment]
> I can see it becoming painfully slow, but at least it does not crash here when scrolling.
> 
> Windows 10 version 22H2 19045.4414

I try to use ItemsView in my project, and after adding the content of more than 100 try to roll, also met the same problem, this is done by the Application. The UnhandledException event capture the exception information
![801b2c6ee59f42f9863f691f6d56cd83](https://github.com/microsoft/microsoft-ui-xaml/assets/49179966/16ccf5db-e297-49d6-93cc-49e56b57cf8c)

**Comment by jpeterstewart** [comment]
Yes, it's absolutely possible to make it crash, even though it's intermittent.

**Comment by RBrid** [comment]
Thanks for your report. We fixed the slow performance issue for the WinAppSDK 1.6 release, but could not repro the crashing issue. Could you please open a separate GitHub issue if you can repro the crash in 1.6? Thanks.

**Comment by jpeterstewart** [comment]
Great news! I look forward to being able to use ItemsView in 1.6. Any estimate of when it will be available as a preview so I can try it out?

 

Thanks,

 

Peter
