### ISSUE TITLE
TabView item drag does not adapt to DPI change

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/microsoft-ui-xaml#9776]
### Describe the bug

The visual / tooltip shown when dragging a TabViewItem is not per monitor dpi aware.

#8442 is for WinUI2. Same issue here for WinUI3.

### Steps to reproduce the bug

1. Open WinUi3 Gallery, go to TabView page
2. Drag a TagViewItem to another monitor with a different dpi

The font size and visual size are not changing

### Screenshots

![TabView](https://github.com/microsoft/microsoft-ui-xaml/assets/42881734/9af6323a-2967-48f4-827a-b4ada6379e13)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.4: 1.5.240607001

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
I believe this is an OS issue, making the underlying cause/fix the same as #8442. Let's track through that one issue. I added a comment in that issue to note the issue also applies to WinUI3.
