### ISSUE TITLE
Regression: pressing F6 with Light Dismissible TeachingTip does nothing now

### ISSUE THREAD

**Issue by TANG-Kai** [microsoft/microsoft-ui-xaml#9777]
### Describe the bug

If a teaching tip is light dismissible with action items in them (buttons, links...), pressing F6 does nothing. So user cannot navigate to the action buttons with keyboard.
Worse, when Narrator is open, it will say "Press F6 to new notification", but pressing it does nothing.
This was supposedly solved by #3545 but it is back.

### Steps to reproduce the bug

1. Go to WinUI 2 Gallery.
2. Click the "show a non-targeted TeachingTip with buttons" show teaching tip button.
3. Press F6 or tab

### Expected behavior

The focus should move on to the first action button.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This bug doesn't repro in WinUI 3.

**Comment by ranjeshj** [comment]
Sorry, resolving this as won't fix for WinUI2. Please see https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2
