### ISSUE TITLE
CharacterReceived event is not working in WinUI 3 ComboBox

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/microsoft-ui-xaml#9786]
### Describe the bug

The CharacterReceived event is not calling while typing characters in editable ComboBox.
Sample code is given below.

- **XAML**

```
 <ComboBox x:Name="TEST" IsEditable="True" CharacterReceived="ComboBox_CharacterReceived" >
     <x:String>123</x:String>
     <x:String>234</x:String>
     <x:String>125</x:String>
 </ComboBox>
```

- **C++**

```
void winrt::TestApp::implementation::MainWindow::ComboBox_CharacterReceived( winrt::Microsoft::UI::Xaml::UIElement const& sender, winrt::Microsoft::UI::Xaml::Input::CharacterReceivedRoutedEventArgs const& args )
{
    OutputDebugString( (L"\nComboBox_CharacterReceived" );
}
```

Is there any additional stuff We should do to trigger this event?
Any help is greatly appreciated.

### Steps to reproduce the bug

Create a C++ WinUI3 application.
Add a ComboBox control in XAML.
Add CharacterReceived event.
Put OutputDebugString inside the CharacterReceived handler.

### Expected behavior

While typing characters, the CharacterReceived event should be triggered each time.

### NuGet package version

Windows App SDK 1.5.4: 1.5.240607001

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by jususnja-ms** [comment]
I have a similar problem. I was not able to make CharacterReceived event be called from few UIElements where I try to put it.
