### ISSUE TITLE
Proposal: Visual WYSIWYG editor for WinUI

### ISSUE THREAD

**Issue by steskalja** [microsoft/microsoft-ui-xaml#9787]
# Proposal: Visual WYSIWYG editor for WinUI

## Summary
To ease the use of building WinUI based apps in Visual Studio, it would be beneficial to have a WYSIWYG editor similar to Winforms or WPF

## Rationale
* Ease of use
* Rapid prototyping
* It would allow novice or inexperienced WinUI developers a much easier entry point
* Allow for faster development of one off, and utility apps. In the similar vain of WinForms

**Comment by Balkoth** [comment]
Duplicate of #5917

**Comment by chrisglein** [comment]
Tracked with duplicate https://github.com/microsoft/microsoft-ui-xaml/issues/5917
