### ISSUE TITLE
SplitView Overlay DisplayModes should have a shadow

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#979]
*Ported from Xaml Controls Gallery, needs description update*

**If this is an addition/modification to an existing sample page, which one?**
SplitView

**Describe the sample**

There should be a shadow for the CompactOverlay and Overlay DisplayModes

**Is your sample request related to a problem? Please describe it**

There is no visual difference between when content is pushed and when it covered.

**Additional context**

**Comment by chigy** [comment]
Adding the history behind this to help triage team...

We added shadow to NavigationView but not SplitView purposefully. This was more of a release timing decision. We did think it should be on SplitView if we could. Since we implemented shadow on NavigationView so late near the release cutoff point, we decided not to add shadow to SplitView because we were afraid it would introduce unnecessary backward compatibility bugs to applications that are using SplitView and implementing shadow on their own like Edge.

**Comment by Poopooracoocoo** [comment]
Would be good to implement it then so Edge devs don't have to implement it themselves. Spartan is being replaced by Anaheim anyway :P

**Comment by chigy** [comment]
>Edit: wait a minute. Edge doesn't use SplitView as an overlay, does it?

@Poopooracoocoo , by Edge, I mean Edge shell, not Web View. On Edge, if you click on Favorites, they use SplitView there.

**Comment by Poopooracoocoo** [comment]
It doesn't go over the content on the right of it though (the favs), does it? It instead goes over the website and the content to the right of it stays as it is when the splitview is expanded. The shadow on that side makes sense. 

I hope I made sense :)

**Comment by jevansaks** [comment]
@chigy just to confirm, you are saying we **should** add shadow to SplitView in WinUI 3.x?

**Comment by chigy** [comment]
@jevansaks , yes, however I'm cautioning about the potential backward compatibility issue with people who already added shadow in custom code.

**Comment by chigy** [comment]
> It doesn't go over the content on the right of it though (the favs), does it? It instead goes over the website and the content to the right of it stays as it is when the splitview is expanded. The shadow on that side makes sense.
> 
> I hope I made sense :)

@Poopooracoocoo , The SplitView on Edge opens from left side of the UI. so the shadow will be on the left side of the pane if that explains what you were asking.

**Comment by Poopooracoocoo** [comment]
@chigy What I meant was that the shadow is on the left side of the SplitView, covering the website instead of the SpltiView's content. It's not an overlay
![image](https://user-images.githubusercontent.com/51363864/60564281-65d17780-9da2-11e9-8c9b-99cc29505e41.png)

**Comment by mdtauk** [comment]
If you are now able to set the Translation-Z value in XAML, perhaps you could have elevation ThemeResources for both sides of the SplitView - so a developer could choose to elevate the right pane of the Split View, which would automatically place a shadow on the left pane, or the other way around of course.

**Comment by Poopooracoocoo** [comment]
Depth is very complicated, even more so in a browser.

**Comment by mdtauk** [comment]
> Depth is very complicated, even more so in a browser.

Depth is what generates the shadows in XAML - so if you are asking for a shadow on SplitView, this would be how it is implemented

**Comment by chigy** [comment]
> If you are now able to set the Translation-Z value in XAML, perhaps you could have elevation ThemeResources for both sides of the SplitView - so a developer could choose to elevate the right pane of the Split View, which would automatically place a shadow on the left pane, or the other way around of course.
> 

@mdtauk , why do you think such a capability is needed? I do believe SplitView has a property to have it appear on the left or right, so based on that, the shadow placement could be altered? Trying to understand you have more use case scenarios that I am not thinking at the moment?

**Comment by mdtauk** [comment]
@chigy  _Needed_ is up to the individual developers.  But adding **Translation** ThemeResources for the Side Pane, the Content Pane, and the Overlay Pane, would make it easy for developers to control the shadowing - and those same styling resources could be used for the NavigationView's templates.

**Comment by chingucoding** [comment]
@StephenLPeters @chigy @jevansaks Looking at the conversation, is this something we should do post WinUI 3?

**Comment by StephenLPeters** [comment]
Split view is a winui 2 control, so I don't think the Needs winui 3 tag is appropriate, however this seems relatively low priority and like we would want to do some more investigation before blindly checking in a shadow update.
