### ISSUE TITLE
Hope to provide an unique name for Microsoft.UI.Xaml.winmd and dll

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#9790]
### Describe the bug

Hope to provide a unique name for Microsoft.UI.Xaml.Winmd and Microsoft.UI.Xaml.dll
希望能为 Microsoft.UI.Xaml.Winmd 和 Microsoft.UI.Xaml.dll 提供一个独一的名称

Currently, in WinUI 3 and WinUI 2, the UI library name they use is both Microsoft.UI.Xaml.dll, and the API entry is both Microsoft.UI.Xaml.winmd. When building an MSIX application, if the package dependencies include both WinUI 2 and WinUI 3, Namely PackageDependency with Microsoft. UI. Xaml. 2.8 and Microsoft WindowsAppRuntime. 1.5, then can only use WinUI 2 framework, The framework of WinUI 3 cannot be used. When the framework of WinUI 3 is created, it will automatically index to the Microt.ui.xaml.dll of WinUI 2 according to package dependency, resulting in application startup failure.

目前，在 WinUI 3 和 WinUI 2 中，他们使用的 UI 库的名称都是 Microsoft.UI.Xaml.dll，API 的入口都是 Microsoft.UI.Xaml.winmd。当构建一个 MSIX 的应用时，如果包依赖都包含 WinUI 2 和 WinUI 3 时，也就是 PackageDependency 同时拥有 Microsoft.UI.Xaml.2.8 和 Microsoft.WindowsAppRuntime.1.5 时，这时只能使用 WinUI 2 的框架，不能使用 WinUI 3 的框架，当创建 WinUI 3 的框架时，根据包依赖，会自动索引到 WinUI 2 的 Microsoft.UI.Xaml.dll，导致应用程序启动失败。

### Steps to reproduce the bug

1. Create a new blank WinUI 3 Windows-based application packaging project (Wapproj)
2. Add a UWP template application to the solution
3. Add nuget dependency Microsoft.UI.Xaml library to UWP blank application (WinUI 2)
4. The Windows application packaging project adds dependencies to the UWP template application
5. Modify Package.appxmanifest and add entry points for the UWP application and WinUI 3 desktop application
5. Deploy and test the application
6. The UWP application starts normally, but the WinUI 3 desktop application fails to start

1.创建一个新的空白的 WinUI 3 的基于 Windows 应用程序打包项目（Wapproj）
2.在解决方案中添加一个 UWP 模板应用
3.为 UWP 空白应用添加 nuget 依赖 Microsoft.UI.Xaml 库（WinUI 2）
4.Windows 应用程序打包项目添加对 UWP 模板应用的依赖
5.修改 Package.appxmanifest，同时为 UWP 应用和 WinUI 3 桌面应用添加入口点
5.部署并测试应用
6.UWP 应用正常启动，WinUI 3 桌面应用启动失败

### Expected behavior

WinUI 3 桌面应用和 UWP 应用都能正常运行
WinUI 3 desktop applications and UWP applications work properly

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/49179966/4257a6af-fd2c-4f3a-a90d-d5272b8f7581)
As shown in the figure, in the WinUI 3 desktop application, the error loading of WinUI 2's Microsoft.UI.Xaml.dll and Windows.UI.Xaml.dll causes the application to fail to start normally.
如图所示，在 WinUI 3 桌面应用中，错误的加载了 WinUI 2 的 Microsoft.UI.Xaml.dll 和 Windows.UI.Xaml.dll 导致应用程序无法正常启动。

### NuGet package version

WinUI 3 - Windows App SDK 1.5.4: 1.5.240607001

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\GetStoreApp.exe”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\win32u.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\gdi32full.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\msvcp_win.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\shell32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\advapi32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\imm32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\host\fxr\9.0.0-preview.5.24306.7\hostfxr.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\hostpolicy.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\coreclr.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ole32.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\combase.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\oleaut32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\bcryptprimitives.dll”。符号已加载，没有源信息。
线程 18880 已退出，返回值为 0 (0x0)。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Private.CoreLib.dll”。
“GetStoreApp.exe”(CoreCLR: DefaultDomain): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Private.CoreLib.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\kernel.appcore.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\GetStoreApp.dll”。
“GetStoreApp.exe”(Win32): 已卸载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\GetStoreApp.dll”
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\GetStoreApp.dll”。
线程 10748 已退出，返回值为 0 (0x0)。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\GetStoreApp.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Runtime.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Runtime.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\uxtheme.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\clrjit.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\icu.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Runtime.InteropServices.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Runtime.InteropServices.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\WinRT.Runtime.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\WinRT.Runtime.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Collections.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Collections.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Collections.Concurrent.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Collections.Concurrent.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.Windows.SDK.NET.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.Windows.SDK.NET.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.WinUI.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.WinUI.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Memory.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Memory.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Runtime.CompilerServices.Unsafe.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Runtime.CompilerServices.Unsafe.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Threading.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Threading.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\clbcatq.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.ApplicationModel.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\WinTypes.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.StateRepositoryCore.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Private.Uri.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Private.Uri.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.ObjectModel.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.ObjectModel.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.ComponentModel.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.ComponentModel.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Numerics.Vectors.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Numerics.Vectors.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.Windows.ApplicationModel.Resources.Projection.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.Windows.ApplicationModel.Resources.Projection.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6-experimental2_6000.183.650.0_x64__8wekyb3d8bbwe\Microsoft.Windows.ApplicationModel.Resources.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\BCP47mrm.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6-experimental2_6000.183.650.0_x64__8wekyb3d8bbwe\Microsoft.Internal.FrameworkUdk.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6-experimental2_6000.183.650.0_x64__8wekyb3d8bbwe\MRM.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\SHCore.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ntmarta.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\CoreMessaging.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\BCP47Langs.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\profapi.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\dcomp.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Microsoft.Internal.WarpPal.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Microsoft.Internal.FrameworkUdk.System.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.Globalization.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Linq.Expressions.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Linq.Expressions.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Security.Cryptography.Algorithms.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Security.Cryptography.Algorithms.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Security.Cryptography.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\System.Security.Cryptography.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\bcrypt.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Winlangdb.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.Storage.ApplicationData.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\twinapi.appcore.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\windows.storage.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\shlwapi.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\propsys.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\mssprxy.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\cfgmgr32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\OneCoreUAPCommonProxyStub.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\urlmon.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\iertutil.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\sspicli.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\StructuredQuery.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ntshrui.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\srvcli.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\cscapi.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.Storage.Search.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\edputil.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.ApplicationModel.Store.Preview.DOSettings.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\wbem\wbemprox.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\wbemcomn.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\wbem\wbemsvc.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\wbem\fastprox.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\amsi.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.Management.Deployment.Projection.dll”。
“GetStoreApp.exe”(Win32): 已卸载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.Management.Deployment.Projection.dll”
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.Management.Deployment.Projection.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.Management.Deployment.Projection.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\wpnapps.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\msxml6.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ExecModelClient.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.Shell.ServiceHostBuilder.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\execmodelproxy.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.InteractiveExperiences.Projection.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“D:\Github\GetStoreApp\GetStoreAppPackage\bin\x64\Debug\AppX\Microsoft.InteractiveExperiences.Projection.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6-experimental2_6000.183.650.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll”。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\d3d11.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\DWrite.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6-experimental2_6000.183.650.0_x64__8wekyb3d8bbwe\Microsoft.UI.Windowing.Core.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6-experimental2_6000.183.650.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\powrprof.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\version.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\d2d1.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\dxgi.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6-experimental2_6000.183.650.0_x64__8wekyb3d8bbwe\Microsoft.WindowsAppRuntime.Insights.Resource.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\directxdatabasehelper.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\DXCore.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已卸载“C:\Windows\System32\DXCore.dll”
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\umpdc.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\DXCore.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ResourcePolicyClient.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已卸载“C:\Windows\System32\ResourcePolicyClient.dll”
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.UI.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_f42d50ef4c9376ba\igd10iumd64.dll”。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\apphelp.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_f42d50ef4c9376ba\igd10um64gen11.dll”。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\crypt32.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ncrypt.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\ntasn1.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.UI.Immersive.dll”。符号已加载，没有源信息。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_f42d50ef4c9376ba\igdgmm64.dll”。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_f42d50ef4c9376ba\igc64.dll”。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\TextShaping.dll”。符号已加载，没有源信息。
线程 3768 已退出，返回值为 0 (0x0)。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\WindowsApps\Microsoft.UI.Xaml.2.8_8.2310.30001.0_x64__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll”。已加载符号。
“GetStoreApp.exe”(Win32): 已加载“C:\Windows\System32\Windows.UI.Xaml.dll”。已加载符号。
Microsoft.UI.Xaml.dll!00007FF961941021: 80004005 - 鏈寚瀹氱殑閿欒
0x00007FFA21CFEE5A (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x80004005 : 'Failed to assign to property 'Microsoft.UI.Xaml.ResourceDictionary.Source' because the type 'Windows.Foundation.String' cannot be assigned to the type 'Windows.Foundation.Uri'.'。
0x00007FFA21CFEE5A (KernelBase.dll)处(位于 GetStoreApp.exe 中)引发的异常: WinRT originate error - 0x802B000A : 'Failed to assign to property 'Microsoft.UI.Xaml.ResourceDictionary.Source' because the type 'Windows.Foundation.String' cannot be assigned to the type 'Windows.Foundation.Uri'. [Line: 16 Position: 37]'。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\netstandard.dll”。
“GetStoreApp.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0-preview.5.24306.7\netstandard.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“GetStoreApp.exe”(Win32): 已加载“C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Impl.dll”。符号已加载，没有源信息。

**Comment by codendone** [comment]
Having WinUI2 and WinUI3 in the same project is not supported.
