### ISSUE TITLE
TabViewItem header hit test/mouse over problems in 1.6.0 experimental 2

### ISSUE THREAD

**Issue by DHancock** [microsoft/microsoft-ui-xaml#9791]
### Describe the bug

The hit test and mouse over areas for tab view item headers and their buttons are incorrect. Please see the attached video.
The bug is only evident when there is an even number of tabs and the display scaling is set to 125%. It isn't reproducible at 100% scaling, I haven't tried other scale factors.

https://github.com/microsoft/microsoft-ui-xaml/assets/28826959/fb4fd2db-f064-4db5-ab01-886622ca9f81

### Steps to reproduce the bug

1. Build the attached solution.
2. Set display scale to 125%.
3. Open an even number of tabs.

[HitTestIssue.zip](https://github.com/user-attachments/files/16111034/HitTestIssue.zip)

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Experimental 2: 1.6.240701003-experimental2

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

I also experienced similar bugs in my real app in the tab's contents, not just the tab item headers. For example the expander drop down buttons could be clicked when the mouse was outside of any part of it's expender. I suspect it's a common cause.

**Comment by codendone** [comment]
This is a known issue in both 1.6-experimental1 and experimental2. I believe the fix was just checked in, but leaving active for the fix developer to verify.

**Comment by llongley** [comment]
Yes, this should be fixed in the newest version of WindowsAppSDK.
