### ISSUE TITLE
Xaml.Media.Imaging.SurfaceImageSource variable margins

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/microsoft-ui-xaml#9800]
**Edit** I realized the problem only reproduces if I have the `Image` in a `ScrollViewer` (i.e. the left margin is always 2px otherwise) and so don't care about this anymore. 

----
### Describe the bug

[Tutorial](https://learn.microsoft.com/en-us/previous-versions/windows/apps/hh825871(v=win.10)#surfaceimagesource) on `SurfaceImageSource` for context.

[`ISurfaceImageSourceNative::BeginDraw`](https://learn.microsoft.com/en-us/windows/win32/api/windows.ui.xaml.media.dxinterop/nf-windows-ui-xaml-media-dxinterop-isurfaceimagesourcenative-begindraw) returns a surface that is bigger than the `pixelWidth` and `pixelHeight` you parse to the [`SurfaceImageSource` constructor](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.surfaceimagesource.-ctor?view=winrt-26100).

The problem is that the left margin actually varies between different runs of the program. The top margin is always 0px. The right and bottom margins change in proportion with the hight and width.

If I translate my rendering with a left offset of 4px. I will get only my clear colour displayed some of the time. Other times I will get a pixel or two of `SurfaceImageSource`'s clear colour 😢.

I can get the actual size from [`IDXGISurface::GetDesc`](https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgisurface-getdesc) but that doesn't help.

Maybe being a pixel or two off is not the end of the world.

### Steps to reproduce the bug

```xaml
<ScrollViewer HorizontalScrollMode="Enabled" HorizontalScrollBarVisibility="Visible">
    <Image Margin="960,780,0,0" Stretch="None" x:Name="SentenceBySentenceImage"/>
</ScrollViewer>
```

### NuGet package version

WinUI 3 - Windows App SDK 1.5.4: 1.5.240607001

**Comment by DarranRowe** [comment]
There is no here of whether or not the offset parameter is being used correctly. It is also true that the documentation for this parameter isn't good in the reference. The Windows.UI.Xaml version only describes it as "Receives the point (x,y) offset of the surface that will be drawn into.Receives the point (x,y) offset of the surface that will be drawn into." where the [Microsoft.UI.Xaml version](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/microsoft.ui.xaml.media.dxinterop/nf-microsoft-ui-xaml-media-dxinterop-isurfaceimagesourcenative-begindraw) doesn't even document anything.
Looking at the DirectComposition documentation for [IDCompositionSurface::BeginDraw](https://learn.microsoft.com/en-us/windows/win32/api/dcomp/nf-dcomp-idcompositionsurface-begindraw) and [ICompositionDrawingSurfaceInterop::BeginDraw](https://learn.microsoft.com/en-us/windows/win32/api/windows.ui.composition.interop/nf-windows-ui-composition-interop-icompositiondrawingsurfaceinterop-begindraw) provide some extra context for the parameter with the same name. That is, you need to offset your drawing rectangle by the x and y values given in the offset parameter.

**Comment by tom-huntington** [comment]
Yes I forgot about the `[out]          POINT      *updateOffset` parameter.

Thanks!
