### ISSUE TITLE
Unable to interact with title bar after maximizing when dialog is shown

### ISSUE THREAD

**Issue by MichalMucek** [microsoft/microsoft-ui-xaml#9806]
### Describe the bug

Window title bar does not take any clicks (unable to move, minimize, maximize, or close) after following the below steps.

### Steps to reproduce the bug

1. Open WinUI 3 Gallery, version 2.4.3.0, not maximized.
2. Go to ContentDialog.
3. Click Show dialog.
4. Maximize the application window.
5. Restore the application window.
6. Maximize the application window again.

### Expected behavior

The title bar should be fully functional.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.5: 1.5.240627000

### Additional context

I did see the issue on Windows 11 version 23H2 (not listed in the form). I didn't have a chance to test other versions.

**Comment by codendone** [comment]
Interesting that the titlebar is fine on the first maximize but breaks when maximizing again. Even after closing the ContentDialog the titlebar stays broken. Switching to a different app and back fixes it.

**Comment by MichalMucek** [comment]
@llongley Is it no longer reproducible on 1.6 Experimental?
