### ISSUE TITLE
Titlebar buttons inactive on window maximize.

### ISSUE THREAD

**Issue by Wandtket** [microsoft/microsoft-ui-xaml#9809]
### Describe the bug

Titlebar buttons inactive when window is in a maximized state (except for minimize button on occasion). When you move the window out of the maximized position the buttons become clickable again.

It worked properly in 1.5.240428000.

### Steps to reproduce the bug

Create a new WinUI Project, Extend Content into Title Bar, Maximize the window and try to interact with anything in the top right most part of the screen.

### Expected behavior

Buttons should remain clickable when maximized.

### Screenshots

![Dropdown gif](https://github.com/microsoft/WindowsAppSDK/assets/13137508/eea18880-7a8d-4c4f-a164-cb6a4b5c8699)

### NuGet package version

Windows App SDK 1.5.5: 1.5.240627000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by codendone** [comment]
@Wandtket Can you attach a simple repro app? We're not able to repro.

**Comment by Wandtket** [comment]
@codendone As Requested,

[TitleBar.zip](https://github.com/user-attachments/files/16183036/TitleBar.zip)

I added a TabView with the buttons I used in the screenshot.

**Comment by codendone** [comment]
This was resolved as duplicate of #9749 -- fixed by the same change.
