### ISSUE TITLE
Proposal:Add ShowHeader enum property to NavigationView

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#981]
# Proposal: Add ShowHeader enum property to NavigationView

## Summary
Currently, it is not possible to entirely get rid of the `Header` of `NavigationView`. Setting `AlwayShowHeader` to false still shows the header in Small mode. 

It would make sense if Visibility is controlled by an enum, such as shown below
```
enum ShowHeader {Always,Mode1,Mode2,Never}
```

```
 <winui:NavigationView
        x:Name="navigationView"
        Background="{ThemeResource SystemControlBackgroundAltHighBrush}"
        IsBackButtonVisible="Visible"
        IsBackEnabled="{x:Bind ViewModel.IsBackEnabled, Mode=OneWay}"
        IsSettingsVisible="True"
        ShowHeader="Never"
        SelectedItem="{x:Bind ViewModel.Selected, Mode=OneWay}">
```
Also
```
navigationView.ShowHeader = Mode1|Mode2;
```

## Rationale

* If the context is clear it is should not be forced upon the developer to show header in compact mode.
* The option of re-templating is also not a good option and best avoided 

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to control visibility of the header according to application need | Must |

**Comment by YuliKl** [comment]
@harvinders, thank you for opening this proposal. Unfortunately, there's a fundamental problem with hamburger button and content overlap in Minimal mode, and a header is the best solution we came up with for getting around this problem. 

The hamburger itself is just a small square button in the top left corner of the app window. Typically, app content is allowed to scroll vertically. Here's an example of a Xaml Controls Gallery screen if it didn't have a header:
![image](https://user-images.githubusercontent.com/13142665/60541183-db1b4a80-9cc5-11e9-9d52-552dea71012b.png)

Here's what the same screen might look like when scrolled:
![image](https://user-images.githubusercontent.com/13142665/60541252-056d0800-9cc6-11e9-89c2-4f0e3c5d4821.png)

The back and hamburger buttons are floating over the content, obscuring some of the area in a strange way. By having a header, we're able to draw a clean dividing line that the content scrolls underneath.
![image](https://user-images.githubusercontent.com/13142665/60541388-60066400-9cc6-11e9-9792-393ab78c9064.png)


All this is to say that the header area serves a purpose and is necessary to ensure a reasonable user experience in Minimal mode.
