### ISSUE TITLE
Question: Will Composition get future updates as nuget package and as windows platform changes too?

### ISSUE THREAD

**Issue by vitorgrs** [microsoft/microsoft-ui-xaml#982]
Hi. With XAML, it's pretty clear the development it's going to be happening as a nuget package going further with WinUI 3.0. And this shouldn't be a problem going further.   
Might be early to ask this but does that includes Composition API changes? 
**After Win3.0 comes with Composition, will it get updated on windows as platform updates too?**

How will Composition compatibility work with previous versions of Windows 10 (and on 8?).
Doesn't some composition APIs relies on some changes made in dwm/dcomp in some 10 versions?

And how it will work in the future too? Won't a new planned feature for Composition sometime require a change on dwm/dcomp and then it will work just in a future Windows 10 Build that new feature?

Thanks already!

**Comment by jevansaks** [comment]
Assigning to @HarneetSidhana to answer this question.

**Comment by jesbis** [comment]
Sorry for the delayed response.

WinUI 3 will include composition and input functionality in addition to Xaml and be updated over time. 

Our goal for the composition layer is to support core capabilities in the same backward-compatible form as the rest of WinUI, with some exceptions where supporting a capability on previous versions of Windows is infeasible. The exact list is still being determined, and we are figuring out a mechanism where these features can light up depending on which version of the OS the app is running on.
