### ISSUE TITLE
New TitleBar Control can not set TitleBar.PreferredHeightOption: The group or resource is not in the correct state to perform the requested operation.

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#9833]
### Describe the bug

we can not set/change TitleBar Height Option:

`appWindow.TitleBar.PreferredHeightOption = TitleBarHeightOption.Tall;
`

> System.Runtime.InteropServices.COMException: 'The group or resource is not in the correct state to perform the requested operation.
> 
> The group or resource is not in the correct state to perform the requested operation.
> '
> 

### Steps to reproduce the bug

1.Change New TitleBar control Height

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Experimental 2: 1.6.240701003-experimental2

### Windows version

Windows 11 (22H2): Build 22621

**Comment by HO-COOH** [comment]
Encountered the same issue. You need to first call `ExtendsContentIntoTitleBar = true;` then you can call `PreferredHeightOption`
