### ISSUE TITLE
Error is API docs of UIElement

### ISSUE THREAD

**Issue by fabianoriccardi** [microsoft/microsoft-ui-xaml#9837]
[In UIElement API page](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement?view=windows-app-sdk-1.5) it is stated the following: 

> Although UIElement defines the events for focus reporting ([GotFocus](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.gotfocus?view=windows-app-sdk-1.5#microsoft-ui-xaml-uielement-gotfocus), [LostFocus](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.lostfocus?view=windows-app-sdk-1.5#microsoft-ui-xaml-uielement-lostfocus)), UIElement does not define an API for programmatically setting the focus. This capability is defined by the [Control](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.control?view=windows-app-sdk-1.5) class.

Which is not quite true, because the Focus method is defined in UIElement and not in Control. Maybe this paragraph is inherited from UWP docs...

**Comment by jwmsft** [comment]
Thanks for reporting this issue. The incorrect paragraph that was copied from the UWP docs has been removed.
