### ISSUE TITLE
TabView.CornerRadius isn't applied

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#9846]
### Describe the bug

When trying to create a tabview with rounded corners, the corner radius isn't applied
See green outline:
<img width="439" alt="image" src="https://github.com/user-attachments/assets/94a2bc45-484e-46e3-b609-294c0cee4f0d">

### Steps to reproduce the bug

Add the following XAML:
```xml
   <TabView Height="200" BorderBrush="{ThemeResource TabViewBorderBrush}" BorderThickness="1,0,1,1" Padding="0" CornerRadius="0,0,10,10">
       <TabViewItem Header="Tab 1">
           <RichEditBox Header="RichEditBox" PlaceholderText="Tab 1 Content" Margin="10" />
       </TabViewItem>
       <TabViewItem Header="Tab 2">
           <TextBlock Text="Tab 2 Content" Margin="10" />
       </TabViewItem>
   </TabView>
```

### Expected behavior

Corners are rounded.

It appears this line isn't template-binding the corner radius property:
https://github.com/microsoft/microsoft-ui-xaml/blob/66a7b0ae71c19f89c6a7d86a1986794ad1a1bf09/src/controls/dev/TabView/TabView.xaml#L45
and needs `CornerRadius="{TemplateBinding CornerRadius}"` added

### NuGet package version

WinUI 3 - Windows App SDK 1.5.5: 1.5.240627000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by karkarl** [comment]
Closing as the change is merged in the internal repo.
