### ISSUE TITLE
Multiple languages in NavigationView

### ISSUE THREAD

**Issue by doghappy** [microsoft/microsoft-ui-xaml#985]
**Multiple languages in NavigationView**

When I changed the `ApplicationLanguages.PrimaryLanguageOverride` to "en-US", the text of the `Settings NavigationViewItem` was still '设置'.

![image](https://user-images.githubusercontent.com/20038914/60573843-02981300-9dab-11e9-890f-2a5458e68200.png)

**Comment by jevansaks** [comment]
@doghappy Are you trying to change the language override dynamically? It should work if you set it in your Application's OnLaunched. Dynamic changes aren't supported properly across our control set right now.
