### ISSUE TITLE
Proposal: Update scrollbar indicator

### ISSUE THREAD

**Issue by sravya03** [microsoft/microsoft-ui-xaml#987]
## Summary
Update the styling of the scrollbar indicator to be more pill shaped as opposed to the square rectangle. 

## Rationale
* Consistency with other apps, web, etc.
* More modern visual refresh

**Comment by mdtauk** [comment]
It should have 2epx corner radius set when it is fully visible, but perhaps pill shaped when it is not in focus.

**Comment by Poopooracoocoo** [comment]
This doesn't align with the Fluent Design System. 


#830 is relevant

**Comment by Felix-Dev** [comment]
@sravya03 @chigy I really would like to see these UI update proposals to come with Visual Comps right from the start. As it is right now, most of these kind of proposals get created describing some UI change in a general text-based way only, without the important visual comps which fundamentally help in assessing these proposals.

I remember reading that @sravya03 works at MS too so it should be possible to ship these proposals with the visual comps provided by @chigy right from the start.

**Comment by mdtauk** [comment]
This is what I was referring to.

![image](https://user-images.githubusercontent.com/7389110/60724806-461b8a00-9f2f-11e9-8c25-2ff3a250163e.png)

2px rounding on the full scrollbar, pill shaped for the scrolling indicator

**Comment by chigy** [comment]
> @sravya03 @chigy I really would like to see these UI update proposals to come with Visual Comps right from the start. As it is right now, most of these kind of proposals get created describing some UI change in a general text-based way only, without the important visual comps which fundamentally help in assessing these proposals.
> 
> I remember reading that @sravya03 works at MS too and if that's correct it should be possible to ship these proposals with the visual comps provided by @chigy right from the start.

@Felix-Dev , it is because we are opening issues before the comps are figured out. We are truly doing this out in open. Perhaps this could have been better off with the "Discussion" since we have no plan on acting on this anytime soon.

**Comment by chigy** [comment]
> This is what I was referring to.

I've removed image for space... 
> 
> 2px rounding on the full scrollbar, pill shaped for the scrolling indicator

@mdtauk , the top image is something we are doing with the #524. The bottom one is specifically something we are not doing with #524 because the scrollbar touches the corners. Refer to [Corner Radius (aka Rounded Corner) How-To document PR](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/34)

**Comment by chigy** [comment]
### Status update
This proposal is moved to the future backlog for a later discussion. Until then, this item will not be acted on. Community members are welcome to continue adding comments, feedback, where this change is useful, or not so useful, etc.
@mdtaulk , @Felix-Dev , @Poopooracoocoo FYI

**Comment by chigy** [comment]
We have made the updates to scrollbar indicator since this proposal was originally posted and believe issues are addressed.

**Comment by Poopooracoocoo** [comment]
>and believe issues are addressed

These are all still open though
https://github.com/microsoft/microsoft-ui-xaml/issues/8530
https://github.com/microsoft/microsoft-ui-xaml/issues/7682
https://github.com/microsoft/microsoft-ui-xaml/issues/5442
https://github.com/microsoft/microsoft-ui-xaml/issues/2971
https://github.com/microsoft/microsoft-ui-xaml/issues/830
