### ISSUE TITLE
AOT Warning: (CsWinRT1028) The XamlMetaDataProvider is not marked partial

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#9876]
**Describe the bug**

AOT Warning: (CsWinRT1028) The XamlMetaDataProvider is not marked partial

**To Reproduce**

The XamlMetaDataProvider is not marked partial

**Expected behavior**

**Version Info**

CsWinRT 2.1.0-prerelease.240801.1
Windows SDK 10.0.26100.37-preview
.NET SDK 9.0.0-preview6
Windows App SDK 1.6.240701003-experimental2

**Additional context**

![image](https://github.com/user-attachments/assets/f437aea9-3d6e-4b9b-9b51-b1131161a844)

**Comment by codendone** [comment]
This is fixed for the next 1.6 release.
