### ISSUE TITLE
How do I know when the UWP CoreWindow Window position changes?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#9896]
### Describe the bug

How do I know when the UWP CoreWindow Window position changes?
如何知道 UWP CoreWindow 窗口位置发生变化？

My UWP application uses the default download box of WebView2, but the position of the default download box does not move when the position of the WebView2 download box changes, so I want to turn off the default download box of WebView2 when the position of the UWP CoreWindow window changes. I did not find the corresponding event in UWP CoreWindow to get the position dynamics of the window, is there any feasible solution?
我的 UWP 应用使用到了 WebView2 的默认下载框，然而 WebView2 下载框在窗口位置发生变化时，默认下载框的位置却没有移动，所以我想在 UWP CoreWindow 的窗口位置发生变化时关掉 WebView2 的默认下载框。我在 UWP CoreWindow 并没有找到相应的事件来获取窗口的位置动态，请问有什么可行的解决方案吗？

CoreWindow API Documents
CoreWindow API 文档
https://learn.microsoft.com/zh-cn/uwp/api/windows.ui.core.corewindow?view=winrt-26100

![{4858EFA9-97AC-46DA-ACD5-8D83784A74D1}](https://github.com/user-attachments/assets/f459740f-54a8-47e0-b17e-f54b9df676b5)

### Steps to reproduce the bug

See describe

### Expected behavior

Please provide a feasible solution
请提供一个可行的解决方案

### Screenshots

![image](https://github.com/user-attachments/assets/ce2544d2-f496-4344-a023-bbacda8fd74d)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows Insider Build (xxxxx), Windows 11 (22H2): Build 22621

### Additional context

Windows 11 26100

**Comment by codendone** [comment]
CoreWindow does not raise any events when its position changes. If this is an important issue, you could start a regular timer which polls CoreWindow.Bounds and checks if the position has changed.
