### ISSUE TITLE
WinUI 3 release mode crash Microsoft.ui.xaml.dll,

### ISSUE THREAD

**Issue by jpcassano** [microsoft/microsoft-ui-xaml#9914]
### Describe the bug

When trying to launch a packaged WinUI 3 application in Release mode that was created using the Blank App, Packaged (WinUI 3 in Desktop) project template, I receive an exception stating, "Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.5.0" and the application crashes. 

### Steps to reproduce the bug

1. Launch Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.11.1 on Windows 11 Pro Version 23H2 Build 22631.4037.
2. Select Create a new project and use the Blank App, Packaged (WinUI 3 in Desktop) project template to create a new project.
3. Add the `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` parameter to the application .csproj file to indicate that the application should be self contained.
4. Select release and x64 from the configuration manager and try to run the application.
5. The application crashes 

### Expected behavior

The application should launch without an exception.

### Screenshots

![image](https://github.com/user-attachments/assets/9f966d4c-77bd-4a59-86fe-e9ec66781a0e)
![image](https://github.com/user-attachments/assets/aef6cc1b-a7a1-47e8-8970-6701508f4d0d)
![image](https://github.com/user-attachments/assets/f1d9d24d-7960-4836-b382-384631c1219e)
![image](https://github.com/user-attachments/assets/927f2fcb-f313-49c3-849d-654efeae6be1)
![image](https://github.com/user-attachments/assets/3574db29-0c76-40dd-b090-287f96df0881)
![image](https://github.com/user-attachments/assets/f77355b9-a934-4301-b611-7eb5170a2a96)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.6: 1.5.240802000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

The application also crashes after successfully installing if you use the create app package option by right clicking the project file and following the steps to sideload the app. The msix is created and installs the app but the application will crash when launching and the event viewer shows "Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.5.0",

**Comment by j-cassano** [comment]
As described in the comments of the linked issues this is a bug that will be fixed in Windows App SDK 1.6. The workaround for this issue is to set `<PublishTrimmed>false</PublishTrimmed>` in the pubxml files for release builds.

**Comment by jpcassano** [comment]
As described in the comments of the linked issues this is a bug that will be fixed in Windows App SDK 1.6. The workaround for this issue is to set <PublishTrimmed>false</PublishTrimmed> in the pubxml files for release builds.

**Comment by jpcassano** [comment]
As described in the comments of the linked issues this is a bug that will be fixed in Windows App SDK 1.6. The workaround for this issue is to set false in the pubxml files for release builds.

**Comment by Cyp9715** [comment]
`    
  <PropertyGroup>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">False</PublishTrimmed>
  </PropertyGroup>
`

Modifying the .pubxml file as shown above resolved the issue.  
However, why has Microsoft set this as the default option to True?  
Honestly, I'm not entirely sure what this feature does, but if there is a potential issue, it would be better to set False as the default option to ensure proper functionality.
