### ISSUE TITLE
Proposal:Restore AcrylicBrush.BackgroundSource Property in WinUI 3

### ISSUE THREAD

**Issue by Tirehar** [microsoft/microsoft-ui-xaml#9915]
# Proposal: Restore AcrylicBrush.BackgroundSource Property in WinUI 3

## Summary
Restore the BackgroundSource property for AcrylicBrush in WinUI 3 to provide developers with the ability to control the acrylic background layer’s source and behavior, enhancing the visual customization of applications.

## Rationale

*Enhanced Visual Customization: The BackgroundSource property allows for more granular control over the appearance of acrylic materials, enabling developers to create more visually appealing and distinct applications.
*Consistency with UWP: Restoring this property would maintain feature parity with UWP, making it easier for developers transitioning from UWP to WinUI 3.
*Developer Demand: There has been significant feedback from the developer community expressing the desire for this feature to be available in WinUI 3.
*Design Flexibility: This feature provides additional design flexibility, which is crucial for building modern, high-quality user interfaces.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Restore the BackgroundSource property for AcrylicBrush | Must |
| Ensure compatibility with existing AcrylicBrush functionality | Must |
| Offer support for all previously available BackgroundSource options | Should |
| Maintain performance and resource efficiency | Must |

## Open Questions
*Are there any technical limitations or challenges in implementing this feature in WinUI 3 that need to be addressed?
*What is the expected timeline for the restoration of this property, considering the current WinUI 3 roadmap and priorities?

**Comment by duncanmacmichael** [comment]
Hi @Tirehar, we really appreciate this detailed and thoughtful feedback and we understand where you're coming from! Unfortunately we don't plan on adding this feature because the model in WinUI 3 is to set it on the window:

```XML
<Window.SystemBackdrop>
        <DesktopAcrylicBackdrop />
</Window.SystemBackdrop>
```

This is due to WinUI 3's undocked architecture, which means you can only put desktop acrylic on the window instead of on any element like you could in WinUI 2.

Hope this answers your question. Thanks!

**Comment by michael-hawker** [comment]
I'd suggest to re-open this issue and at least provide the property, as it makes multi-targeting both UWP and WinUI 3 more difficult. Just have the property be marked deprecated in WinUI 3 and point to the alternative docs/way of doing it.
