### ISSUE TITLE
ListView control overflows when it contains a large number of items

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/microsoft-ui-xaml#9931]
### Describe the bug

ListView control items are displayed outside the list view control boundary if the control is populated with a huge number of items, such as 550000 items.
![image](https://github.com/user-attachments/assets/2388965e-fbc4-4971-8680-2205535357de)

How do we fix this issue?
Is there any workaround/property/API available to fix this issue?
Any help would be highly appreciated.

### Steps to reproduce the bug

A sample application with above described issue is attached.
[ListViewTestApp.zip](https://github.com/user-attachments/files/16761060/ListViewTestApp.zip)

Build and run the application in Visual Studio.

### Expected behavior

All items in the ListView should to stay confined and visible only when scrolling.

### NuGet package version

Windows App SDK 1.5.6: 1.5.240802000

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by codendone** [comment]
Looks like a dup of #8028?
