### ISSUE TITLE
WinUI: Popup shows underneath AutoSuggestBox results flyout

### ISSUE THREAD

**Issue by eshalisa** [microsoft/microsoft-ui-xaml#9935]
### Describe the bug
Get test project from https://github.com/eshalisa/TestProjects
I have a popup that should show over the AutoSuggestBox results flyout when I hover. It is always showing underneath, even when it opens after the results flyout.

This worked on Microsoft.WindowsAppSDK version 1.3.230724000.

### Steps to reproduce the bug

Launch test app
Type "A" into the AutoSuggestBox
Put the curser over the "Apple" result

### Expected behavior

The popup should show above the flyout if it opens after the flyout.

### Screenshots

![image](https://github.com/user-attachments/assets/c202f3dc-e3a0-472c-a19a-6f161223b26f)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.6: 1.5.240802000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Try setting `ShouldConstrainToRootBounds=false` on the Popup.

**Comment by eshalisa** [comment]
> Try setting `ShouldConstrainToRootBounds=false` on the Popup.

That worked, thank you!
