### ISSUE TITLE
Tapped event is also fired by the middle, back, and forward mouse buttons

### ISSUE THREAD

**Issue by hyam1567** [microsoft/microsoft-ui-xaml#9949]
### Describe the bug

The Tapped event is also fired by the middle, back, and forward mouse buttons.
Also, TappedRoutedEventArgs cannot determine which button was pressed.
```
// xaml
<Rectangle Fill="red" Width="200" Height="200" Tapped="Rectangle_Tapped"/>
// cs
private void Rectangle_Tapped( object sender, TappedRoutedEventArgs e ) {}
```

### Steps to reproduce the bug

1. Launch the app.
2. Click the middle mouse button on the red rectangle.

### NuGet package version

WinUI 3 - Windows App SDK 1.6.0: 1.6.240829007

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Yes, the [Tapped](https://learn.microsoft.com/uwp/api/windows.ui.xaml.uielement.tapped) event fires for any mouse button, pen, or finger tap. It isn't an ideal event, and it can cause confusion for controls like Button which have a Clicked event firing independently from Tapped.

To detect a specific mouse button, you need to use PointerPressed/PointerReleased/etc. with GetCurrentPoint() on the event args to inspect the PointerPoint properties.
