### ISSUE TITLE
ProgressRing is not visible on Windows 11 inside the ContentDialog

### ISSUE THREAD

**Issue by AlexRUiLs** [microsoft/microsoft-ui-xaml#9950]
### Describe the bug

The bug still exists: https://github.com/microsoft/microsoft-ui-xaml/issues/5925

UWP ContentDialog doesn't show ProgressRing (set as active and visible) on Windows 11.
On Windows 10 the ProgressRing shown as expected but on Windows 11 the ProgressRing is not shown.

Microsoft.UI.Xaml Nuget version 2.8.6

### Steps to reproduce the bug

1. Create a page with ProgressRing control active and visible
2. Set this page as content of ContentDialog
3. Show the ContentDialog

### Expected behavior

Animated ProgressRing should be visible inside the ContentDialog.

### Screenshots

![image](https://github.com/user-attachments/assets/45e999c1-276d-4715-87f3-37c376bb4cba)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows Insider Build (xxxxx)

### Additional context

23H2 22631.4037

**Comment by llongley** [comment]
This doesn't appear to repro in WinUI 3:

![Image](https://github.com/user-attachments/assets/8c608b2a-8a54-4d69-a72c-9c397c11c867)

**Comment by ancker1** [comment]
I have the same problem with WinUI 3 using Windows 11.

I have tried adding it programmatically and through XAML. @llongley which version of Windows are you using? In thread #5925, some have reported that it is not a problem on Windows 10.
