### ISSUE TITLE
Build errors when using "dotnet build"

### ISSUE THREAD

**Issue by fubar-coder** [microsoft/microsoft-ui-xaml#9959]
### Describe the bug

I got build errors when I use `dotnet build`. Everything's (almost) fine, if I use VS 2022 (17.11.2).

```text
EXEC : error : Could not read the Windows SDK's Platform.xml at C:\Program Files (x86)\Windows Kits\10\Platforms\UAP\10.0.19041.0\Platform.xml [D:\Entwicklung\Material.Icons\Material.Icons.WinUI3\Material.Icons.WinUI3.csproj]
C:\Users\fubar\.nuget\packages\microsoft.windows.cswinrt\2.1.1\build\Microsoft.Windows.CsWinRT.targets(290,5): error MSB3073: Der Befehl ""C:\Users\fubar\.nuget\packages\microsoft.windows.cswinrt\2.1.1\cswinrt.exe" @"Generated Files\\CsWinRT\cswinrt.rsp"" wurde mit dem Code 1 beendet. [D:\Entwicklung\Material.Icons\Material.Icons.WinUI3\Material.Icons.WinUI3.csproj]
```

The error indicates that it tries to use a `Platform.xml` from the Windows 10 SDK, version `10.0.19041.0`, while only `10.0.22621.0` is installed.

After changing the TFM from `net8.0-windows10.0.19041.0` to `net8.0-windows10.0.22621.0`, I get the following error:

```text
C:\Users\fubar\.nuget\packages\microsoft.windowsappsdk\1.6.240829007\buildTransitive\MrtCore.PriGen.targets(914,5): error MSB4062: Die Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent-Aufgabe konnte nicht aus der C:\Program Files\dotnet\sdk\8.0.401\\Microsoft\VisualStudio\v17.0\AppxPackage\\Microsoft.Build.Packaging.Pri.Tasks.dll-Assembly geladen werden. Could not load file or assembly 'C:\Program Files\dotnet\sdk\8.0.401\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll'. Das System kann den angegebenen Pfad nicht finden. Stellen Sie sicher, dass die <UsingTask>-Deklaration korrekt ist, die Assembly und alle zugehörigen Abhängigkeiten verfügbar sind und die Aufgabe eine öffentliche Klasse enthält, die Microsoft.Build.Framework.ITask implementiert. [D:\Entwicklung\Material.Icons\Material.Icons.WinUI3\Material.Icons.WinUI3.csproj]
```

I only need to be able to build the library `Material.Icons.WinUI3`, not the demo application.

### Steps to reproduce the bug

1. Clone `https://github.com/fubar-coder/Material.Icons.git`
2. `cd Material.Icons`
3. `dotnet build`

### Expected behavior

Successful build

### NuGet package version

WinUI 3 - Windows App SDK 1.6.0: 1.6.240829007

### Additional context

- Windows 11, 23H2
- VS 2022 17.11.2
- .NET SDK 8.0.401

**Comment by lhak** [comment]
I think adding `<EnableMsixTooling>true</EnableMsixTooling>` to the csproj file is required to get dotnet build to work.

**Comment by fubar-coder** [comment]
@lhak I tested it, and the error 1 (the one with the missing `Platform.xml`) still exists. However, the build astonishingly succeeds after updating the TFM to `net8.0-windows10.0.22621.0`.

So, there's still the problem, that `cswinrt` (2.1.1, which is the latest version), or whatever it is, that looks for the `Platform.xml`, still ignores the fact, that there is a more recent UAP platform, which  **does** contain a `PreviousPlatforms.xml`, which **does** contain an entry for `10.0.19041.0`.

**Comment by evelynwu-msft** [comment]
> @lhak I tested it, and the error 1 (the one with the missing `Platform.xml`) still exists. However, the build astonishingly succeeds after updating the TFM to `net8.0-windows10.0.22621.0`.
> 
> So, there's still the problem, that `cswinrt` (2.1.1, which is the latest version), or whatever it is, that looks for the `Platform.xml`, still ignores the fact, that there is a more recent UAP platform, which **does** contain a `PreviousPlatforms.xml`, which **does** contain an entry for `10.0.19041.0`.

Fundamentally, you need to have installed the version of the Windows SDK that corresponds to the Windows version that you are targeting, e.g. since you are targeting Windows version 10.0.19041.0 you *must* have the 10.0.19041.0 Windows SDK installed.

> EDIT: Why does it need `EnableMsixTooling` set to `true`, when I don't need to create an MSIX package to build the library?

I agree that it's unintuitive but basically Single-project MSIX is what provides Windows App SDK with build tasks that are compatible with `dotnet build`.
