### ISSUE TITLE
TextBox selection is broken when there are multiple lines

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/microsoft-ui-xaml#9965]
### Describe the bug

If you write multiple lines in a TextBox and select text from the second line and below, the selection won't go away. In light mode the foreground changes back to black when selecting another piece of the text.

### Steps to reproduce the bug

Create a project, add a TextBox that wraps text and/or accepts return and write on it.

### Screenshots

https://github.com/user-attachments/assets/b5cf4c47-23c8-484d-a51e-74d06b3cb952

### NuGet package version

WinUI 3 - Windows App SDK 1.6.0: 1.6.240829007

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmgallahan** [comment]
I thought it was just me due to some custom TextBox work, but hadn't investigated yet. Thanks for opening the issue.

**Comment by AlexanderBlackman** [comment]
I've had the same problem with RichEditBox too.
![Image](https://github.com/user-attachments/assets/2b22fdec-96c3-4687-b954-e5901f1c907c)

**Comment by thecco** [comment]
![Image](https://github.com/user-attachments/assets/6d4a2300-ffee-4396-91ac-91c649d03db2)

Windows App SDK 1.6.241114003
Windows11  23H2, 24H2

**Comment by jeremy-visionaid** [comment]
+1. I'm also seeing this in MAUI apps using the Editor control on Windows

**Comment by kmgallahan** [comment]
@codendone Are we going to have to wait until 1.8 to see a fix for this bug... ?

This interferes with my daily work and it's present in every app that updates WinUI and uses a multiline TextBox.

**Comment by codendone** [comment]
The fix has been checked in for the next 1.6 servicing release in January.
