### ISSUE TITLE
FocusVisualKind.Reveal crashes app in 1.6

### ISSUE THREAD

**Issue by NGeras** [microsoft/microsoft-ui-xaml#9966]
### Describe the bug

After upgrading from stable 1.5 to stable 1.6 app crashes when FocusVisualKind is set to FocusVisualKind.Reveal and focus is applied second or third time.
Error:

> Exception thrown at 0x75F88FA4 (KernelBase.dll) in TestApp.exe: WinRT originate error - 0x80070057 : 'An invalid Duration is specified. It must be >= 1ms and <= 24 days'.
Microsoft.UI.Xaml.dll!7BF484EA: 80070057 - E_INVALIDARG
'TestApp.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MsSpellCheckingFacility.dll'. 
Unhandled exception at 0x7B817E41 (Microsoft.ui.xaml.dll) in TestApp.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x1EF7D870, 0x00000002).

### Steps to reproduce the bug

1. Create a WinUI3 app
2. Apply **FocusVisualKind** in App.xaml.cs like this
```
public App()
{
    this.InitializeComponent();
    FocusVisualKind = FocusVisualKind.Reveal;
}
```
3. Launch the app and move focus through the app with TAB key

### Expected behavior

App should not crash as it was in 1.5

### Screenshots

https://github.com/user-attachments/assets/872d08c2-786c-4c4d-8d22-67cc04277f12

### NuGet package version

WinUI 3 - Windows App SDK 1.6.0: 1.6.240829007

**Comment by JesseCol** [comment]
Thanks for filing!  This will be fixed in the next WinAppSDK 1.6 release.
