### ISSUE TITLE
Cannot dynamically change controls' disabled background color, all though you can do it statically through custom dictionary.

### ISSUE THREAD

**Issue by johnt-star** [microsoft/microsoft-ui-xaml#9968]
### Describe the bug

Not so much a bug as missing functionality.

Most controls can have their disabled background color statically set via a custom dictionary, by using an entry such as
    
    <SolidColorBrush x:Key="ButtonBackgroundDisabled" Color="LightBlue" />

( See https://github.com/microsoft/WindowsAppSDK/issues/4702 where custom dictionary entry does not work )

My problem is that the user can change the background color of the container the control is on, so I need to dynamically change the Control's disabled background color.

Ideally, this could be done by exposing the controls disabled background color, the way it is currently done for background color.

In the meantime, in the following link, someone showed me how to access the elements of the Visual Tree for a check box

https://github.com/microsoft/microsoft-ui-xaml/issues/9236

Could something like this be done for TextBox type controls (AutoSuggestBox, NumberBox, PasswordBox and TextBox) and the Button type controls (Button, HyperlinkButton, RadioButton, RadioButtons, RepeatButton, SplitButton, ToggleButton and ToggleSplitButton)?

Thank you in advance!

### Steps to reproduce the bug

No control property to dynamically change the disabled back ground color. 

Ideally the code would look similar to 

        private void SetButtonBackGroundDisabledColor(Windows.UI.Color color)
        {
                Button.DisabledBackground = new SolidColorBrush(color);
        }

Can only do it statically in a custom dictionary by adding following line:
    
    <SolidColorBrush x:Key="ButtonBackgroundDisabled" Color="LightBlue" />

### NuGet package version

WinUI 3 - Windows App SDK 1.6.0: 1.6.240829007

### Windows version

Windows 10 (21H2): Build 19044

**Comment by castorix** [comment]
You can do :

```
private void SetButtonBackGroundDisabledColor(Button btn, Windows.UI.Color color)
{ 
    btn.Resources["ButtonBackgroundDisabled"] = new SolidColorBrush(color);
}
```

**Comment by johnt-star** [comment]
Thanks for the reply!

I verified this works.

I also like the methodology and can use it elsewhere in my code.

Will close this ticket

**Comment by johnt-star** [comment]
Will use suggested code to achieve what I need
