### ISSUE TITLE
Migrating from BackRequested UWP to WinUI-3

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#9975]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Migrating-from-BackRequested-UWP-to-WinU/10735834)._

---
[severity:It's more difficult to complete my work]
In a UWP project (intended for PCs and tablets) I implemented a BackRequested, so that tablets can launch the 'back to previous page action' with the default button offered by tablets, via the following code: In the Page.xaml code of my page there is no change made. In the Page.xams.cs code:

```
protected async override void OnNavigatedTo(NavigationEventArgs e)
{
    Windows.UI.Core.SystemNavigationManager.GetForCurrentView(). BackRequested += BackRequested;
    
...
}         

private static async void BackRequested(object sender, Windows.UI.Core.BackRequestedEventArgs e)
{
    e.Handled = true;

//  code for Back action
}
```

This UWP code works great! I am migrating this code to WinUI-3. If the previous code compiles very well under WinUI-3, when running, there is a crash at the line:

`Windows.UI.Core.SystemNavigationManager.GetForCurrentView(). BackRequested += BackRequested;`

The error message:

>    An unhandled exception of type 'System.AccessViolationException' occurred in Microsoft.Windows.SDK.NET.dll Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Is it possible to migrate this UWP code to WinUI-3, by making the minimum of modifications and especially without touching the Xaml code (because I have 4403 *.xaml files)!

Thanks in advance

---
#### Feedback Bot on 9/1/2024, 06:40 PM: 

(private comment, text removed)
#### Ann Yang [MSFT] on 9/1/2024, 11:30 PM: 

(private comment, text removed)
#### COM-ADD on 9/2/2024, 00:37 AM: 

(private comment, text removed)
#### Feedback Bot on 9/2/2024, 01:07 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by llongley** [comment]
SystemNavigationManager is not currently implemented in WinUI 3.  There's a proposal to implement it here:

https://github.com/microsoft/WindowsAppSDK/issues/2398

For now, the workaround is to add your own button to the title bar.
