### ISSUE TITLE
Discussion: Windows.UI.Xaml vs Microsoft.UI.Xaml

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#998]
Forgive me if this has been published somewhere, but I've not come across it. 

I'd like to know how Microsoft.UI.Xaml is different to Windows.UI.Xaml, other than it's later and more up-to-date than the Windows.UI.Xaml namespace.

Here are some dot points I'd love to see documented, or pointed to in order to read more about it.

1) Will Windows.UI.Xaml be kept up to date going forwards with new Windows releases, with the changes made in Microsoft.UI.Xaml?

2) Is the intent to bring more of Windows.UI.Xaml.Controls into Microsoft.UI.Xaml.Controls and open source them? The vast majority of controls don't exist in this repo, for example TextBlock, TextBox, Grid, StackPanel, etc.

3) To confirm, this repository is the correct place to raise bugs & feature proposals for controls in Windows.UI.Xaml, that aren't yet in Microsoft.UI.Xaml?

**Comment by weltkante** [comment]
From the [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md):

1) > The existing UWP Xaml APIs that ship as part of the OS will no longer receive new feature updates. They will still receive security updates and critical fixes according to the Windows 10 support lifecycle.
   
   This means the `Windows.UI.Xaml` namespace is going to be locked down. If it weren't for backwards compatibility it could probably be removed, but you'll want to compile/run old source code so it must stay.

2) > WinUI 3 will greatly expand the scope of WinUI to include the full UI platform

   WinUI 3 will move the XAML, Composition and Input layer of the stack into this repository, so I believe all of the old controls are going to get open sourced as well.

3) can't answer that, they are probably focusing on WinUI 3 so bugfixes and feature proposal for the `Windows.UI.Xaml` namespace will probably very limited (I'd assume all new features will go here and not into the old namespace)

**Comment by jesbis** [comment]
>  believe all of the old controls are going to get open sourced as well.

Yes, the goal is to move all of the old controls into Microsoft.UI.Xaml and open source them. 

To clarify about the composition+input layer: that layer will likely get open sourced after the Xaml/controls layer and may or may not be in a different repo.

> To confirm, this repository is the correct place to raise bugs & feature proposals for controls in Windows.UI.Xaml, that aren't yet in Microsoft.UI.Xaml?

Yes, this repo is the correct place 🙂 Microsoft.UI.Xaml is basically the next version of Windows.UI.Xaml so the current plan is that all future new features will go into the Microsoft.UI.Xaml NuGet package(s).

**Comment by wstaelens** [comment]
So none of these can be used with MAUI .NET ?

**Comment by anantashrit** [comment]
Why the license of microsoft-ui-xaml package not under MIT ? https://www.nuget.org/packages/Microsoft.UI.Xaml/2.4.3/license
I am using WebView2 using the microsoft-ui-xaml package. In OSS audit, it is found that license has clauses related to Data collection and the release has been halted because there is not much info on what data is collected, whether is enabled by default and whether it can be disabled? Any inputs please help.

**Comment by weltkante** [comment]
> Why the license of microsoft-ui-xaml package not under MIT ?

Probably because WinUI 3 hasn't been open sourced yet? The repo only has some WinUI 2 controls as far as I can tell.
