### ISSUE TITLE
Multiple finger touch on Navigation View multiple items become selected

### ISSUE THREAD

**Issue by AndersonRodr** [microsoft/microsoft-ui-xaml#9986]
### Describe the bug

When touch on many items at same time, more than one item stays selected.

### Steps to reproduce the bug

1. Go to WinUI Gallery 2 or WinUI Gallery 3.
2. Go to Navigation View;
3. In a touch PC, touch more than one item. More than one stays selected.

### Expected behavior

Only one item must be selected.

### Screenshots

![image](https://github.com/user-attachments/assets/84251b0d-5202-42e2-aef5-8a03de9a1538)

https://github.com/user-attachments/assets/37ad6b45-3c93-4246-8ff6-9e8a3d5f7afc

### NuGet package version

None

**Comment by codendone** [comment]
This should be fixed in WinAppSDK 1.6. It looks good in local testing of WinUI 3 Gallery built on 1.6. I believe this fix from the [release notes](https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel) is what fixed this:
> Fixed an issue where touching and dragging on a Button in a ScrollViewer would leave it in a pressed state.
