### ISSUE TITLE
WinUI 3 app started via debugger will always have unicolor (black) title bar

### ISSUE THREAD

**Issue by whiskhub** [microsoft/microsoft-ui-xaml#9987]
### Describe the bug

WinUI 3 apps started via the Visual Studio debugger will always show a unicolor (black/white) title bar based on the Windows color theme. **No Mica effect will be shown.**

Setting `DWMWA_USE_IMMERSIVE_DARK_MODE` via `DwmSetWindowAttribute` has no influence here.

Starting the app via start menu etc. will instead always show a light Mica title bar, which is the default and expected Win32 behavior.

### Steps to reproduce the bug

1. Create blank WinUI 3 app
2. Start the app via Visual Studio debugger
3. You will see an unicolor black/white title bar

### Expected behavior

Same behavior for the title bar color if starting the app via Visual Studio debugger, or in other ways like start menu. Currently expected behavior would be a light Mica title bar.

### Screenshots

Title bar when started via Visual Strudio:
![image](https://github.com/user-attachments/assets/1af15d81-b681-443d-b4f9-4b7240301bbb)

Title bar when started via start menu:
![image](https://github.com/user-attachments/assets/3dae0070-bd14-41e6-862a-707cc994d08b)

### NuGet package version

WinUI 3 - Windows App SDK 1.6.0: 1.6.240829007

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment]
Actually, this is caused by #9988. Turning off the "Enable in-app toolbar" option in the Debugging->XAML Hot Reload settings in Visual Studio makes this go away. The in-app toolbar needs to know if ExtendsContentIntoTitleBar is set, which is how #9988 is triggered. We'll track with that issue.
